### ISSUE TITLE
path may not be null or empty string && compileSdkVersion is not specified

### ISSUE THREAD

**Issue by oftoapp** [expo/expo#22584]
### Minimal reproducible example

instructions on summary.

### Summary

Guys, I detect a problem on newest versions of expo, following the getstarting and don't changing anything we can simulate the error.

basically we can simulate this only running these two commands:
❯ `npx create-expo-app@latest -t expo-template-blank-typescript test-failed`
❯ `npx expo run:android`

<br /> <br/>

**CMD 1**: `npx create-expo-app@latest -t expo-template-blank-typescript test-failed`
```
✔ Downloaded and extracted project files.
> npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 1222 packages, and audited 1223 packages in 1m

62 packages are looking for funding
  run `npm fund` for details

14 vulnerabilities (9 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.


✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd test-failed
- npm run android
- npm run ios
- npm run web
```

<br /><br /><br />

**CMD 2**: `npx expo run:android`
```
📝  Android package Learn more: https://expo.fyi/android-package

✔ What would you like your Android package name to be? … com.teste.failed

✔ Created native project | gitignore skipped
✔ Added Metro config
✔ Updated package.json and added index.js entry point for iOS and Android
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead

› Installing using npm
> npm install
Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
✔ Config synced
› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ag/proto/test-failed/android/app/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path=''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
5 actionable tasks: 4 executed, 1 from cache
Error: /Users/ag/proto/test-failed/android/gradlew exited with non-zero code: 1
Error: /Users/ag/proto/test-failed/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/ag/proto/test-failed/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (/Users/ag/proto/test-failed/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/Users/ag/proto/test-failed/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/Users/ag/proto/test-failed/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/Users/ag/proto/test-failed/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:31:24)
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.asdf/installs/nodejs/lts/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.7
    Expo Workflow: bare

**Comment by oftoapp** [comment]
debugging the build code, I found this error:
```
resolveEntryPoint(projectRoot, { platform })
Uncaught Error Error: GetEnv.NoBoolean:  is not a boolean.
    at boolish (/Users/ag/ofto/mobile/node_modules/getenv/index.js:70:15)
    at <anonymous> (/Users/ag/ofto/mobile/node_modules/getenv/index.js:84:27)
    at <anonymous> (/Users/ag/ofto/mobile/node_modules/@expo/config/build/plugins/withInternal.js:14:42)

```

to fix it I put EXPO_DEBUG="false" on build process.

I think this bug is on withInternal.js:14:42

**Comment by SleeplessByte** [comment]
Seeing the exact same error on `eas` trying to build android development app. `EXPO_DEBUG=false` unfortunately doesn't solve it.

**Comment by oftoapp** [comment]
@SleeplessByte you should put it as string.
EXPO_DEBUG='false' or EXPO_DEBUG="false"

**Comment by SleeplessByte** [comment]
> @SleeplessByte you should put it as string. EXPO_DEBUG='false' or EXPO_DEBUG="false"

It is.

In my case builds break when it's `app.config.js` or `app.config.ts`, and if I then _copy_ the generated `json` from the "Read app config" step and save it as `app.config.json`, the build starts working again (no other changes!)

**Comment by Kudo** [comment]
@oftoapp that sounds strange to me. do you have any predefined `EXPO_DEBUG` environment variable and its value is not a boolean like value? to troubleshoot the problem further, could you print out the value near the **/Users/ag/ofto/mobile/node_modules/getenv/index.js:70**?

**Comment by nlaffey-augeo** [comment]
I'm encountering this same issue and reproduced it as well with:

❯ npx create-expo-app@latest -t expo-template-blank-typescript test-failed
❯ npx expo run:android

I tried the suggestions of using EXPO_DEBUG="false" as well as copying my app.config.js to app.config.json, neither of which helped.

**Comment by Kudo** [comment]
would be good if someone could help to check the error stacktrace. if that the same from `Uncaught Error Error: GetEnv.NoBoolean:  is not a boolean.`, would be good to help investigating what is the actual value.

**Comment by luccasr73** [comment]
+1 same error here, only on android, iOS build works fine

**Comment by luccasr73** [comment]
@ReimagineDigital you find any workaround?

**Comment by tarikpnr** [comment]
I experienced the same error mentioned above. If you have config plugins attached to your `app.json`, make sure to double-check them so that they are correctly installed/configured.

**Comment by luccasr73** [comment]
something curious made the android build work, I tried to edit the `node_modules/expo/scripts/resolveAppEntry.js` file hoping to have some debug log, adding a console.log on line 20 of that file and running prebuild + npx expo run:android made android build work

**Comment by mckeny3** [comment]
This usually happen if you have a plug-in config but not the package....for instance...you remove mapbox...but still have the config in app.config.js or app.json...that's what happen in my case..

**Comment by luccasr73** [comment]
@ReimagineDigital I had tested this, without success, I keep doing what I said above until I find a definitive solution

**Comment by bitlab-code** [comment]
same issue here template bare-minimum

**Comment by bitlab-code** [comment]
more info about my issue, hoping it helps

`yarn create expo-app --template bare-minimum`
`cd newapp`
`yarn android`

Work fine, build ok and emulator start correctly

To use typescript i've followed this: https://reactnative.dev/docs/typescript#adding-typescript-to-an-existing-project

`yarn add --dev @tsconfig/react-native @types/jest @types/react @types/react-test-renderer typescript`
created `tsconfig.json` with
```json
{
  "extends": "@tsconfig/react-native/tsconfig.json"
}
```
and renamed `App.js` to `App.tsx` and `index.js` to '`index.ts`

finally, running `yarn android` have got the error:
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/------/newapp/android/app/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path=''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
5 actionable tasks: 4 executed, 1 from cache
Error: /------/newapp/android/gradlew exited with non-zero code: 1
Error: /------/newapp/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/------/newapp/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (/------/newapp/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/------/newapp/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/------/newapp/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/------/newapp/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:31:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by mckeny3** [comment]
just create a project not long ago and had that problem.....solved it by doing this rm -rf node_modules && rm -rf yarn.lock && yarn install && yarn run android......

**Comment by bitlab-code** [comment]
> just create a project not long ago and had that problem.....solved it by doing this rm -rf node_modules && rm -rf yarn.lock && yarn install && yarn run android......

tried, without success in my case

**Comment by bitlab-code** [comment]
Solved, but i'm very confused about it.

Just tried to change: `"main": "index.js"` with `"main": "index.ts"` into `package.json` and now work fine.

I not able to understand how this can raise an exception into `app/build.gradle`, maybe path is an empty string due to the missing file `index.js`? ...and what about `compileSdkVersion is not specified`?

Anyway, now it work for me, hope this help someone

---
_work but not with Android 13, just jump into another issue (https://github.com/expo/expo/pull/22286) and hope that the fix will release asap_

**Comment by mbaroukhcw** [comment]
Same for me but it was because I using

```
"env": {
        "APP_NAME": "value"
}
```

in eas.json and it seems that Gradle override this value with "Gradle (Gradle)".

But imho, the real problem is how node_modules/expo/scripts/resolveAppEntry.js works.
It clear the console so the real error was not seen.
Any error in this script returns just the infamous
```
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path=''
```

trace.

**Comment by geoff-schultz** [comment]
My experience yesterday encountering this error:

I recently migrated from an Intel Mac to an ARM64 Mac and was in the process of setting up my development environment. After working for some time in the new environment, I encountered an issue when I cleared the build cache and attempted to rebuild. This resulted in the null path errors described above. 

Interestingly, the project still built successfully on the Intel Mac. The main difference I observed, aside from the hardware, was the JDK (Java Development Kit) version. On the Intel Mac, I had Java JDK 16.0.1 installed, whereas the ARM64 Mac had OpenJDK. To resolve the issue, I uninstalled OpenJDK and installed Java JDK 17.0.7.

 After this change, everything started working smoothly without requiring any further modifications.

**Comment by tolypash** [comment]
I got this after upgrading to Expo SDK 49. iOS build was fine. Android not.

I was getting this error:

```
A problem occurred evaluating settings 'Sally POS'.
> path may not be null or empty string. path='null'
```

@samipe solution worked for me, all i had to do is change settings.gradle line 10 to:

`includeBuild('../node_modules/@react-native/gradle-plugin')`

Thanks @samipe !

**Comment by phillihoch** [comment]
> I got this after upgrading to Expo SDK 49. iOS build was fine. Android not.
> 
> I was getting this error:
> 
> ```
> A problem occurred evaluating settings 'Sally POS'.
> > path may not be null or empty string. path='null'
> ```
> 
> @samipe solution worked for me, all i had to do is change settings.gradle line 10 to:
> 
> `includeBuild('../node_modules/@react-native/gradle-plugin')`
> 
> Thanks @samipe !

@tolypash I got the same error when upgrading to Expo SDK 49 but I think your solution is kind of a weird workaround.

I had a look what the issue with the replaced line of code was.
I came to this conclusion:
You replaced `includeBuild(new File(["node", "--print", "require.resolve('react-native-gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())` for `includeBuild('../node_modules/@react-native/gradle-plugin')`.
My take is, that expo wants to use `react-native-gradle-plugin` instead of the gradle-plugin inside @react-native.

After executing `npx expo install react-native-gradle-plugin` it worked without replacing code in settings.gradle.

**Comment by ogmzh** [comment]
@phillihoch you absolute champ :)

**Comment by AlancitoAntarSB** [comment]
> I got this after upgrading to Expo SDK 49. iOS build was fine. Android not.
> 
> I was getting this error:
> 
> ```
> A problem occurred evaluating settings 'project'.
> > path may not be null or empty string. path='null'
> ```
> 
> @samipe solution worked for me, all i had to do is change settings.gradle line 10 to:
> 
> `includeBuild('../node_modules/@react-native/gradle-plugin')`
> 
> Thanks @samipe !


Give this guy some tacos 🌮 🌮 🔥 💯

**Comment by brentvatne** [comment]
this is happening in bare projects that missed upgrade instructions for the react-native gradle plugin package: https://react-native-community.github.io/upgrade-helper/?from=0.71.0&to=0.72.1#RnDiffApp-android-settings.gradle - the package name changed from `react-native-gradle-plugin` to `@react-native/gradle-plugin`.

we use a slightly different version of that diff in expo projects, in order to support monorepos by default:

```
includeBuild(new File(["node", "--print", "require.resolve('react-native-gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())
```

you should change this to:

```
includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())
```

we always recommend reviewing the [update helper diff](https://react-native-community.github.io/upgrade-helper/) in our upgrade instructions in [sdk release notes](https://blog.expo.dev/expo-sdk-49-c6d398cdf740). if you have any doubt about the changes suggested in upgrade helper diffs, you can refer to a new project on the target sdk version by creating it or looking at the template project on the corresponding sdk branch on github: https://github.com/expo/expo/tree/sdk-49/templates/expo-template-bare-minimum

**Comment by mustafabahaa** [comment]
I just want to share my point of view

to fix this
remove your android project files generated by expo
remove package-lock.json and node modules

npm install
then run the prebuild command again

this is the clean way, we won't need to patch the older expo configuration this is not the way.
this is how i fixed it on my side

**Comment by armemon** [comment]
> I just want to share my point of view
> 
> to fix this remove your android project files generated by expo remove package-lock.json and node modules
> 
> npm install then run the prebuild command again
> 
> this is the clean way, we won't need to patch the older expo configuration this is not the way. this is how i fixed it on my side

Worked for me

**Comment by DanielLMA** [comment]
> I got this after upgrading to Expo SDK 49. iOS build was fine. Android not.
> 
> I was getting this error:
> 
> ```
> A problem occurred evaluating settings 'project'.
> > path may not be null or empty string. path='null'
> ```
> 
> @samipe solution worked for me, all i had to do is change settings.gradle line 10 to:
> 
> `includeBuild('../node_modules/@react-native/gradle-plugin')`
> 
> Thanks @samipe !

My problem was that react-native was still at 0.71.# while expo was upgraded to 49. This was the unintended result of branch merging. This led to the above path='null' error until I updated react-native to 0.72.4. I had a series of other errors I had to sift through while trying to run `npx detox build` that were all related to packages (e.g., expo-splash-screen). Getting all package versions aligned (i.e., updating) was the key to solving the issue.

**Comment by jnjdev42** [comment]
I checked everything like @samipe said. Still not working. I really don't understand.

**Comment by michaelroevievictoria** [comment]
> I just want to share my point of view
> 
> to fix this remove your android project files generated by expo remove package-lock.json and node modules
> 
> npm install then run the prebuild command again
> 
> this is the clean way, we won't need to patch the older expo configuration this is not the way. this is how i fixed it on my side

This works on me, 
usually i do is ```npm run prebuild --clean``` then the error appear.
