### ISSUE TITLE
uuid/v5 import is deprecated

### ISSUE THREAD

**Issue by wSedlacek** [expo/expo#22580]
### Summary

https://github.com/expo/expo/blob/9d5e5238612f2e3c0021094f7954d85c0b8bd78b/packages/expo/src/environment/getInstallationIdAsync.ts#L2

```
Deep requiring like `const uuidv5 = require('uuid/v5');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.
```

### SDK Version

48.0.5

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 3.5.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.1.0, 33.0.0
        System Images: android-Sv2 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.7.1 => 0.7.1 
      babel-preset-expo: ~9.3.2 => 9.3.2 
      expo: 48.0.15 => 48.0.15 
      metro: 0.74.1 => 0.74.1 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.19.4 => 0.19.4 
    Expo Workflow: managed
 ```

### Minimal reproducible example

Install `expo` with `pnpm` using `uuid@9.0.0`

Notes: 

This commit reverted a change that would have fixed the issue https://github.com/expo/expo/commit/3329e04d849b3ce0de9f59d38d66a29455573c80

It is worth noting I am using [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values)

**Comment by bndkt** [comment]
+1 for this one. I currently need to keep a resolution/override in my monorepo for `"uuid": "^3.4.0"` for this reason, which I'd prefer to remove.

**Comment by brentvatne** [comment]
we had to revert that upgrade because more recent versions of uuid have native dependencies in the react-native environment. if you are seeing this error, there is a problem with how pnpm is constructing your node_modules tree, such that the incorrect version of `uuid` is imported by the `expo` package. `expo` depends on `uuid@^3.4.0` and if another version is being imported that is a problem with the package manager
