### ISSUE TITLE
undefined userAgent on expo go app

### ISSUE THREAD

**Issue by tanay-pingalkar** [expo/expo#22590]
### Summary

`fetch("url")` gave me a 403 response on expo go app , but on web it was working fine , i tried changing user-agent `fetch("url", {headers: { "User-Agent": "Mozilla/5.0" })` and then it worked as expected. checking user agent via `navigator.userAgent` returned undefined. Can there be a work around it. Or am i missing on something. 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Environment

``` 
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD   
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.4        
      expo: ~48.0.15 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed
```

### Reproducible demo

```
const res = await fetch("url");
console.log (JSON.stringify(res));
```

response on expo go app

**Comment by pencilcheck** [comment]
need some transformation but wonder if there is already some babel that does this properly
