### ISSUE TITLE
Unable to fix Error 400:redirect_uri_mismatch EXPO

### ISSUE THREAD

**Issue by futurester0x0** [expo/expo#22594]
I'm encountering an issue with access being blocked and receiving the error message 'Access blocked: This app's request is invalid' along with 'Error 400: redirect_uri_mismatch'. I'm not sure if the problem lies in my Google Console configuration or if it's related to expo-auth-session. I have attached the relevant code below for your reference;

Problem: Unable to solve Access blocked: This app's request is invalid Error 400: redirect_uri_mismatch

Request details: redirect_uri=https://auth.expo.io/@user.name/slug

Google Console configure for expo:

Authorized JavaScript origins https://auth.expo.io/

Authorized redirect URIs https://auth.expo.io/@user.name/slug

Google Console configure for WebClient: Authorized JavaScript origins URL1: http://localhost URL2: http://localhost:5000 URL3: https://app-name.firebaseapp.com/

Authorized redirect URIs https://app-name.firebaseapp.com/__/auth/handler

Google Console configure for androidClient: Package Name: com.android.appname

Google Console configure for iosClient: Bundle ID: com.ios.appname

Here is a Code from ../hooks/useAuth.js

import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { startAsync, makeRedirectUri } from 'expo-auth-session';
import * as Google from 'expo-auth-session/providers/google';
import { auth } from '../firebase';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Crypto from 'expo-crypto';

const AuthContext = createContext({});

const request = {
  androidClientId: 'XXXX',
  iosClientId: 'XXXX',
  expoClientId: 'XXXX',
  webClientId: 'XXXX',
  scopes: ['profile', 'email'],
  permissions: ['public_profile', 'email', 'gender', 'location'],
};

export const AuthProvider = ({ children }) => {
  const [error, setError] = useState(null);
  const [user, setUser] = useState(null);
  const [loadingInitial, setLoadingInitial] = useState(true);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((user) => {
      if (user) {
        // Logged in...
        setUser(user);
      } else {
        // Not logged in...
        setUser(null);
      }

      setLoadingInitial(false);
    });

    return () => unsubscribe();
  }, []);

  const logout = async () => {
    setLoading(true);

    try {
      await auth.signOut();
    } catch (error) {
      setError(error);
    } finally {
      setLoading(false);
    }
  };

  const signInWithGoogle = async () => {
    setLoading(true);

    try {
      const redirectUri = makeRedirectUri({ useProxy: true });
      const { type, params } = await startAsync({
        authUrl: `https://accounts.google.com/o/oauth2/v2/auth?client_id=${request.webClientId}&redirect_uri=${encodeURIComponent(
          redirectUri
        )}&response_type=token&scope=${encodeURIComponent(request.scopes.join(' '))}`,
      });

      if (type === 'success') {
        try {
          const { access_token } = params;

          const credential = auth.GoogleAuthProvider.credential(null, access_token);
          await auth.signInWithCredential(credential);

          const nonce = await Crypto.digestStringAsync(
            Crypto.CryptoDigestAlgorithm.SHA256,
            Math.random().toString(36).substring(2)
          );

          await AsyncStorage.setItem('nonce', nonce);
        } catch (error) {
          setError(error);
        }
      }
    } catch (error) {
      setError(error);
    } finally {
      setLoading(false);
    }
  };

  const memoedValue = useMemo(
    () => ({
      user,
      loading,
      error,
      signInWithGoogle,
      logout,
    }),
    [user, loading, error]
  );

  return (
    <AuthContext.Provider value={memoedValue}>{!loadingInitial && children}</AuthContext.Provider>
  );
};

export default function useAuth() {
  return useContext(AuthContext);
}

Code from ../firebase.js,

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "XXX",
  authDomain: "app-name.firebaseapp.com",
  projectId: "app-name",
  storageBucket: "app-name.appspot.com",
  messagingSenderId: "XXXX",
  appId: "X:X:web:X"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth();
const db = getFirestore();

export { auth, db };
Code from ../screens/LoginScreen.js,

import React from 'react';
import { View, Text, Button, StyleSheet } from 'react-native';
import useAuth from '../hooks/useAuth';

const LoginScreen = () => {
  const { signInWithGoogle, loading } = useAuth();

  return (
    <View style={styles.container}>
      <Text style={styles.title}>{loading ? 'Loading...' : 'Login to the App'}</Text>
      <Button title="Login" onPress={signInWithGoogle} color="#007AFF" />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
});

export default LoginScreen;

**Comment by AlirezaHosseinii** [comment]
I'm also facing the same issue and shared my problem in the following link:
https://stackoverflow.com/questions/76373358/how-to-deal-with-access-blocked-this-apps-request-is-invalid-trying-to-sign-i

Any solution for this?

**Comment by ahannan08** [comment]
sa

> I'm also facing the same issue and shared my problem in the following link: https://stackoverflow.com/questions/76373358/how-to-deal-with-access-blocked-this-apps-request-is-invalid-trying-to-sign-i
> 
> Any solution for this?

same here?? did u find the solution yet?

**Comment by ahannan08** [comment]
> I'm encountering an issue with access being blocked and receiving the error message 'Access blocked: This app's request is invalid' along with 'Error 400: redirect_uri_mismatch'. I'm not sure if the problem lies in my Google Console configuration or if it's related to expo-auth-session. I have attached the relevant code below for your reference;
> 
> Problem: Unable to solve Access blocked: This app's request is invalid Error 400: redirect_uri_mismatch
> 
> Request details: redirect_uri=https://auth.expo.io/@user.name/slug
> 
> Google Console configure for expo:
> 
> Authorized JavaScript origins https://auth.expo.io/
> 
> Authorized redirect URIs https://auth.expo.io/@user.name/slug
> 
> Google Console configure for WebClient: Authorized JavaScript origins URL1: http://localhost URL2: http://localhost:5000 URL3: https://app-name.firebaseapp.com/
> 
> Authorized redirect URIs https://app-name.firebaseapp.com/__/auth/handler
> 
> Google Console configure for androidClient: Package Name: com.android.appname
> 
> Google Console configure for iosClient: Bundle ID: com.ios.appname
> 
> Here is a Code from ../hooks/useAuth.js
> 
> import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'; import { startAsync, makeRedirectUri } from 'expo-auth-session'; import * as Google from 'expo-auth-session/providers/google'; import { auth } from '../firebase'; import AsyncStorage from '@react-native-async-storage/async-storage'; import * as Crypto from 'expo-crypto';
> 
> const AuthContext = createContext({});
> 
> const request = { androidClientId: 'XXXX', iosClientId: 'XXXX', expoClientId: 'XXXX', webClientId: 'XXXX', scopes: ['profile', 'email'], permissions: ['public_profile', 'email', 'gender', 'location'], };
> 
> export const AuthProvider = ({ children }) => { const [error, setError] = useState(null); const [user, setUser] = useState(null); const [loadingInitial, setLoadingInitial] = useState(true); const [loading, setLoading] = useState(false);
> 
> useEffect(() => { const unsubscribe = auth.onAuthStateChanged((user) => { if (user) { // Logged in... setUser(user); } else { // Not logged in... setUser(null); }
> 
> ```
>   setLoadingInitial(false);
> });
> 
> return () => unsubscribe();
> ```
> 
> }, []);
> 
> const logout = async () => { setLoading(true);
> 
> ```
> try {
>   await auth.signOut();
> } catch (error) {
>   setError(error);
> } finally {
>   setLoading(false);
> }
> ```
> 
> };
> 
> const signInWithGoogle = async () => { setLoading(true);
> 
> ```
> try {
>   const redirectUri = makeRedirectUri({ useProxy: true });
>   const { type, params } = await startAsync({
>     authUrl: `https://accounts.google.com/o/oauth2/v2/auth?client_id=${request.webClientId}&redirect_uri=${encodeURIComponent(
>       redirectUri
>     )}&response_type=token&scope=${encodeURIComponent(request.scopes.join(' '))}`,
>   });
> 
>   if (type === 'success') {
>     try {
>       const { access_token } = params;
> 
>       const credential = auth.GoogleAuthProvider.credential(null, access_token);
>       await auth.signInWithCredential(credential);
> 
>       const nonce = await Crypto.digestStringAsync(
>         Crypto.CryptoDigestAlgorithm.SHA256,
>         Math.random().toString(36).substring(2)
>       );
> 
>       await AsyncStorage.setItem('nonce', nonce);
>     } catch (error) {
>       setError(error);
>     }
>   }
> } catch (error) {
>   setError(error);
> } finally {
>   setLoading(false);
> }
> ```
> 
> };
> 
> const memoedValue = useMemo( () => ({ user, loading, error, signInWithGoogle, logout, }), [user, loading, error] );
> 
> return ( <AuthContext.Provider value={memoedValue}>{!loadingInitial && children}</AuthContext.Provider> ); };
> 
> export default function useAuth() { return useContext(AuthContext); }
> 
> Code from ../firebase.js,
> 
> // Import the functions you need from the SDKs you need import { initializeApp } from "firebase/app"; import { getAuth } from "firebase/auth"; import { getFirestore } from "firebase/firestore"; // TODO: Add SDKs for Firebase products that you want to use // https://firebase.google.com/docs/web/setup#available-libraries
> 
> // Your web app's Firebase configuration const firebaseConfig = { apiKey: "XXX", authDomain: "app-name.firebaseapp.com", projectId: "app-name", storageBucket: "app-name.appspot.com", messagingSenderId: "XXXX", appId: "X:X:web:X" };
> 
> // Initialize Firebase const app = initializeApp(firebaseConfig); const auth = getAuth(); const db = getFirestore();
> 
> export { auth, db }; Code from ../screens/LoginScreen.js,
> 
> import React from 'react'; import { View, Text, Button, StyleSheet } from 'react-native'; import useAuth from '../hooks/useAuth';
> 
> const LoginScreen = () => { const { signInWithGoogle, loading } = useAuth();
> 
> return ( {loading ? 'Loading...' : 'Login to the App'} ); };
> 
> const styles = StyleSheet.create({ container: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F5F5F5', }, title: { fontSize: 24, fontWeight: 'bold', marginBottom: 20, }, });
> 
> export default LoginScreen;

were u able to solve this issue?

**Comment by tmswartz12** [comment]
Has anyone been able to solve this? I am having the same issue as well

**Comment by ahannan08** [comment]
> Has anyone been able to solve this? I am having the same issue as well

bhai i tried for 3 days and gave up. It seems googlw doesnt allow phone 0auth2 for everyone...kuch special permission we need i believe. also we decided to stick with otp auth and discarded to implement this...
