### ISSUE TITLE
Install ipa on device

### ISSUE THREAD

**Issue by clementino36** [expo/expo#226]
Hi,
I successfully generated an ipa file by letting Expo create a p12 and a push certificate. 
Now i'm trying to install it on an iPhone via Itunes (drag, drop & sync). I see the app installing itself on the iPhone but at the end of the installation the app's icon just disappears. 
One thing to note: the generated ipa's size is 140 Mb but when i drag and drop it into Itunes, it says that the size is 275 Mb. Could the size be the installation's issue ?
Also, why does Expo absolutely needs a push certificate to build the ipa ?
I've also tryed to build the ipa with my own p12 certificate, then by letting Expo create the push certificate, but then `exp build:status` returns `iOS: There was an error with this build. Please try again.` .
I'm running out of ideas here...
Thanks.

**Comment by terribleben** [comment]
Hello! The build generated by Expo is signed for the app store, so you'll need to use Testflight to run it on test devices. See these [instructions](https://docs.expo.io/versions/v17.0.0/guides/building-standalone-apps.html#5-test-it-on-your-device-or-simulator).

**Comment by xcarpentier** [comment]
@terribleben @clementino36 You can resign too if you give the certificate to expo and if you provide  an ad-hoc provisioning profile with the UDID of your device(s). https://github.com/saucelabs/isign
cc. @dikaiosune

**Comment by clementino36** [comment]
Thanks both!

**Comment by ScriiptTeam** [comment]
One thing. Cydia Impactor.
