### ISSUE TITLE
IOS Build 'cassert' file not found, Could not build Objective-C module 'ExpoGL'

### ISSUE THREAD

**Issue by keung7252** [expo/expo#22623]
### Summary

SDK 48
IOS Build 'cassert' file not found

Compiling MONACOONE » SplashScreen.storyboard

❌ (ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:10:10)

8 | #pragma once
9 |

10 | #include
| ^ 'cassert' file not found
11 | #include
12 | #include
13 | #include
› Preparing MONACOONE » Info.plist

❌ (ios/Pods/Headers/Public/hermes-engine/jsi/jsi.h:10:10)

8 | #pragma once
9 |

10 | #include
| ^ 'cassert' file not found
11 | #include
12 | #include
13 | #include
Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.2
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
Yarn: 1.22.18 - /usr/local/bin/yarn
npm: 9.1.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
Watchman: 2023.05.01.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.12.0 - /Users/keung/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
Android SDK:
API Levels: 21, 23, 25, 26, 27, 28, 29, 30, 31, 33
Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9477386
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
npmPackages:
expo: ^48.0.0 => 48.0.17
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.71.8 => 0.71.8
react-native-web: ~0.18.11 => 0.18.12
npmGlobalPackages:
eas-cli: 3.13.0
expo-cli: 6.3.2
Expo Workflow: managed

### Minimal reproducible example

{
  "dependencies": {
    "@expo/react-native-action-sheet": "^3.12.0",
    "@expo/vector-icons": "^13.0.0",
    "@miblanchard/react-native-slider": "^2.1.0",
    "@neverdull-agency/expo-unlimited-secure-store": "^1.0.10",
    "@openspacelabs/react-native-zoomable-view": "^2.0.4",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-masked-view/masked-view": "0.2.8",
    "@react-native-picker/picker": "2.4.8",
    "@react-navigation/drawer": "^6.1.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@reduxjs/toolkit": "^1.6.1",
    "@sentry/react-native": "4.13.0",
    "axios": "^0.21.4",
    "expo": "^48.0.0",
    "expo-analytics-segment": "~11.2.1",
    "expo-application": "~5.1.1",
    "expo-asset": "~8.9.1",
    "expo-av": "~13.2.1",
    "expo-blur": "~12.2.2",
    "expo-camera": "~13.2.1",
    "expo-constants": "~14.2.1",
    "expo-device": "~5.2.1",
    "expo-draw": "git+https://github.com/MarangoniEduardo/expo-draw.git",
    "expo-file-system": "~15.2.2",
    "expo-firebase-analytics": "~7.0.0",
    "expo-gl": "~12.4.0",
    "expo-gl-cpp": "~11.3.0",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-localization": "~14.1.1",
    "expo-next-react-navigation": "^1.2.1",
    "expo-notifications": "~0.18.1",
    "expo-ota-manager": "^1.1.4",
    "expo-permissions": "~14.1.1",
    "expo-radio-button": "^1.0.8",
    "expo-screen-orientation": "~5.1.1",
    "expo-secure-store": "~12.1.1",
    "expo-sharing": "~11.2.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "firebase": "8.2.3",
    "i18next": "^20.6.0",
    "modal-enhanced-react-native-web": "^0.2.0",
    "moment": "^2.29.1",
    "native-base": "^3.1.0",
    "next": "^11.0.1",
    "next-fonts": "^1.5.1",
    "next-images": "^1.8.1",
    "nextjs-progressbar": "^0.0.11",
    "no-scroll": "^2.1.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^11.11.4",
    "react-native": "0.71.8",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-custom-qr-codes-expo": "^2.2.0",
    "react-native-elements": "^3.4.2",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-htmlview": "^0.16.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "^13.0.1",
    "react-native-qrcode-svg": "^6.1.2",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-scalable-image": "^1.1.0",
    "react-native-screens": "~3.20.0",
    "react-native-signature-canvas": "^4.3.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "13.4.0",
    "react-native-table-component": "^1.2.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "3.5.0",
    "react-native-web": "~0.18.11",
    "react-native-webview": "11.26.0",
    "react-native-youtube-iframe": "^2.2.2",
    "react-redux": "^7.2.4",
    "recoil": "^0.7.5",
    "redux": "^4.1.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "rn-pdf-reader-js": "^4.1.1",
    "sentry-expo": "~6.1.0",
    "styled-components": "^5.3.1",
    "styled-system": "^5.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@expo/next-adapter": "^3.0.1",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^8.0.0",
    "prettier": "2.4.1"
  },
  "scripts": {
    "start": "next dev",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build": "next build"
  },
  "private": true,
  "version": "0.0.0"
}

**Comment by keung7252** [comment]
https://expo.dev/accounts/innowave/projects/monacoone/builds/caea29e7-c225-4709-bee9-3b81c7db0314

**Comment by keung7252** [comment]
Could not build Objective-C module 'ExpoGL'

**Comment by keung7252** [comment]
@expo-bot anyone can help

**Comment by Microtribute** [comment]
I have run into the same error.

**Comment by briantanabe** [comment]
Haven't been able to upgrade my expo version because of this, if anyone has any insight 👀

**Comment by williekwok** [comment]
Same issue - can't update to expo 48 - no issues with expo 47

**Comment by valentinchelle** [comment]
i have the same issue. Following.

**Comment by luisflorido** [comment]
I was trying to update from SDK 45 to 49 and had this exactly issue, after running the project in xcode and not from expo saw the issue in my case was with `expo-gl`, just reinstalled the package and removed `expo-gl-cpp` (probably the main issue), I got more errors but with [react native upgrade tool](https://react-native-community.github.io/upgrade-helper/) fixed all the issues

**Comment by adshodgson** [comment]
> `xpo-gl-cpp`

Thank you, saved me a huge headache!

**Comment by adshodgson** [comment]
> I was trying to update from SDK 45 to 49 and had this exactly issue, after running the project in xcode and not from expo saw the issue in my case was with `expo-gl`, just reinstalled the package and removed `expo-gl-cpp` (probably the main issue), I got more errors but with [react native upgrade tool](https://react-native-community.github.io/upgrade-helper/) fixed all the issues


xpo-gl-cpp

Thank you, saved me a huge headache!
