### ISSUE TITLE
Disk space usage increases with each local build

### ISSUE THREAD

**Issue by LouisMuriuki** [expo/expo#22636]
### Summary

Whenever I perform a local build for my app using `npx expo run:android -d` the Disk space usage increases tremendously. Is this normal? are there any temporary files I should delete to recover my storage space?

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

"@expo/html-elements": "^0.4.2",
    "@expo/vector-icons": "^13.0.0",
    "@fortawesome/fontawesome-svg-core": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/checkbox": "^0.5.15",
    "@react-native-community/netinfo": "9.3.7",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.5",
    "@realm/react": "^0.4.3",
    "@tanstack/react-query": "^4.29.5",
    "axios": "^1.4.0",
    "expo": "~48.0.15",
    "expo-asset": "~8.9.1",
    "expo-blur": "~12.2.2",
    "expo-constants": "~14.2.1",
    "expo-font": "~11.1.1",
    "expo-image-manipulator": "^11.1.1",
    "expo-network": "~5.2.1",
    "expo-notifications": "~0.18.1",
    "expo-print": "~12.2.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "immer": "^9.0.18",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-react-native": "5.1.4",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.7",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modalize": "^2.1.1",
    "react-native-pager-view": "6.1.2",
    "react-native-portalize": "^1.0.7",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-thermal-printer": "^2.3.5",
    "react-native-toast-notifications": "^3.3.1",
    "react-native-web": "~0.18.10",
    "react-phone-number-input": "^3.2.21",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "realm": "^11.8.0"

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33
        Build Tools: 33.0.2
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~48.0.15 => 48.0.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: bare

### Reproducible demo

not sure if this requires a reproducible

**Comment by harshpatel991** [comment]
For iOS builds, go to `~/Library/Developer/Xcode/DerivedData` and clean out any mentions of your app. I free'd up 35 gigs
