### ISSUE TITLE
On android, the Function definition is not available

### ISSUE THREAD

**Issue by AsteriskZuo** [expo/expo#22633]
### Minimal reproducible example

https://github.com/easemob/react-native-chat-library/tree/dev/example

### Summary

I want to use uuid in react-native projects that use expo, uuid package requires `react-native-get-random-values` package, `reacting-native-get-random-values` package requires `expo-random` package or `expo-crypto` package, The key Function ` Function (" getRandomBase64String ", this @ RandomModule: : getRandomBase64String) ` or ` Function (" digestString." This @ CryptoModule: : digestString) ` ` Function ` couldn't find it. The uuid cannot be used at expo 45. 'Function' defined position should ` packages/expo-modules-core/android/SRC/main/Java/expo/modules/kotlin/objects/ObjectDefinitionBuilder.kt ` here, But expo version 45 couldn't find this file.

```
{
  "name": "uikit-example",
  "dependencies": {
    "expo": "~45.0.4",
    "expo-crypto": "^11.0.0",
    "expo-random": "^13.1.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.5",
    "react-native-get-random-values": "^1.8.0"
  },
...
}

```

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /opt/homebrew/Cellar/node@16/16.18.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/Cellar/node@16/16.18.1/bin/yarn
      npm: 8.19.2 - /opt/homebrew/Cellar/node@16/16.18.1/bin/npm
      Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/opt/cocoapods/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 32, 33, 33
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.2
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```

**Comment by brentvatne** [comment]
you're using incompatible package versions. you can see this by running `expo doctor` or `npx expo-doctor` in your project
