### ISSUE TITLE
[expo-barcode-scanner] issue with scanning code128 barcodes on iOS

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo#22642]
### Minimal reproducible example

https://snack.expo.dev/@philiplindberg/basic-barcodescanner-usage?platform=ios

### Summary

When trying to scan code128 barcodes, I've noticed that on iOS the barcode has to be perfectly centered for it to be detected, while on Android the barcode is detected as long as it's in frame.

Here's a couple of screen recordings that demonstrate the issue:

### iOS
https://github.com/expo/expo/assets/1865904/6c4355b5-33b7-4a7c-8341-a7c54d23a78f

### Android
https://github.com/expo/expo/assets/1865904/2abd8de5-be73-44bb-99b1-3c86d27ce0ab

Here's the barcode I used when testing:

![barcode](https://github.com/expo/expo/assets/1865904/04837b13-859e-4b19-a2cb-d6b3691cabe1)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.asdf/installs/nodejs/lts/bin/node
      Yarn: 3.5.1 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.7
    Expo Workflow: bare

**Comment by AdiCutitoiu** [comment]
Any updates on this? Facing the same issue

**Comment by oliverphardman** [comment]
Still facing this issue 😦
