### ISSUE TITLE
"Problem loading the project" Failed to load app from http://localholst:8081

### ISSUE THREAD

**Issue by mankybansal** [expo/expo#22652]
### Summary

We am seeing the following error when trying to run our dev client. We haven't had an issue on any other computers, but we are seeing this only on one device.

iOS simulator version: 14.4
Expo Version: 48

|iOS|Android|
|-|-|
|![Screenshot 2023-05-25 at 13 17 35](https://github.com/expo/expo/assets/12834184/475132e1-2b22-42ff-aa04-072a6d30a415)|![Screenshot 2023-05-25 at 13 17 53](https://github.com/expo/expo/assets/12834184/c16662ab-6885-4d83-8a9f-b40bc826bbec)|

Tried:
* The app loads fine in a tunnel. We have never seen this before and can't repro this on other machines. 
* create-expo-app loads fine in Expo go in the simulator
* Different port, did not work
* Resetting network settings, did not work.
* Tried to connect to server on a different computer's simulator on the same network 
* Tried new dev-client simulator build

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

    "expo-dev-client": "~2.2.1",
    "expo": "^48.0.0",
    "expo-updates": "~0.16.4",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Flamingo 2022.2.1 Patch 1 Flamingo 2022.2.1 Patch 1
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.10.0
    Expo Workflow: managed

### Reproducible demo

No repro available :(

**Comment by scalptrader** [comment]
Hi. I had the same issue today and for me it was due to node version. I had installed Node v20.2.0 and it seemed to cause an issue. Reverting back to Node v16.20.0 and it's working again for me.

**Comment by mankybansal** [comment]
> Hi. I had the same issue today and for me it was due to node version. I had installed Node v20.2.0 and it seemed to cause an issue. Reverting back to Node v16.20.0 and it's working again for me.

Woah, you are a life savior! This worked. What an annoying fix for 4 days of debugging 🥲

**Comment by mustvlad** [comment]
> Hi. I had the same issue today and for me it was due to node version. I had installed Node v20.2.0 and it seemed to cause an issue. Reverting back to Node v16.20.0 and it's working again for me.

Indeed. It seem to be an issue with node 20 somehow. Reverted to 18 and works great.

**Comment by vanacoree** [comment]
> > Hi. I had the same issue today and for me it was due to node version. I had installed Node v20.2.0 and it seemed to cause an issue. Reverting back to Node v16.20.0 and it's working again for me.
> 
> Indeed. It seem to be an issue with node 20 somehow. Reverted to 18 and works great.

How does reverting back work on Mac?

**Comment by dj-doMains** [comment]
> > > Hi. I had the same issue today and for me it was due to node version. I had installed Node v20.2.0 and it seemed to cause an issue. Reverting back to Node v16.20.0 and it's working again for me.
> > 
> > 
> > Indeed. It seem to be an issue with node 20 somehow. Reverted to 18 and works great.
> 
> How does reverting back work on Mac?

@vanacoree I use the `n` package. It makes it super easy to swap between node versions.
https://www.npmjs.com/package/n

**Comment by icarofr** [comment]
Bug still present. Tested with Node.js 16, 18 and 20...

```
    "expo": "^49.0.6",
    "expo-apple-authentication": "~6.1.0",
    "expo-auth-session": "~5.0.2",
    "expo-dev-client": "~2.4.10",
    "expo-device": "~5.4.0",
    "react": "18.2.0",
        ```

**Comment by houkanshan** [comment]
Had the same issue on Node `v20.2`. Solved to by upgrading to `v20.9`

**Comment by keitanamazue** [comment]
You need to change http to https.
https://ngrok.com/

**Comment by TowhidKashem** [comment]
If anyone else is having this issue, try deleting the `.expo` file at the root of your project and try again.

And if that doesn't work then use the tunneling option which works but is much slooower:

https://docs.expo.dev/more/expo-cli/#tunneling

**Comment by scaryguy** [comment]
I was out using public Wi-Fi with my Mac and the only thing worked for me was using tunneling (`npx expot start --tunnel`) *AND* using hotspot on my phone. Having phone and the Mac connected to the same public Wi-Fi did was **not** working.

**Comment by wolfcarves** [comment]
This is annoying when you need to rebuild your development client, what I did for this case it to run "yarn dev --clear" and wait for the error to come out and if it does then I just need to delete the .expo folder and re-run the "yarn dev --clear" again. This happens probably because it is cached to the previous build.

**Comment by sultanmyrza** [comment]
For android emulator make sure you are connected to internet.

my node version was `v20.16.0` also I didn't want to use [tunneling](https://docs.expo.dev/more/expo-cli/#tunneling). I was trying to run on android emulator. Solution for me was to make sure my android emulator is connected to the internet.

![image](https://github.com/user-attachments/assets/060e0f38-ce9c-41d5-893f-18deed04c4ce)

**Comment by ssthil** [comment]
Thanks @TowhidKashem 
Deleting the `.expo` file at the root of the project worked for me 👍 🚀

![Simulator Screenshot - iPhone 15 - 2024-09-30 at 16 05 15](https://github.com/user-attachments/assets/4e999875-360c-4c3b-ad10-64874c5cfd2d)

**Comment by JeanBarbosa** [comment]
Check Firewall/Antivirus
Sometimes, firewall or antivirus software can block incoming connections. Ensure that port 8081 is open on your development machine, and there are no restrictions on your local network.

You can temporarily disable the firewall/antivirus to check if that resolves the issue.
Alternatively, add a rule to allow traffic through port 8081.

**Comment by AESMatias** [comment]
> I was out using public Wi-Fi with my Mac and the only thing worked for me was using tunneling (`npx expot start --tunnel`) _AND_ using hotspot on my phone. Having phone and the Mac connected to the same public Wi-Fi did was **not** working.

Thank u so much! I was trying so many things, however i try ```npx expo start --tunel``` and solved! Either ```LTS 16``` nor ```20.16.0``` worked for me.

**Comment by wDebashree** [comment]
> If anyone else is having this issue, try deleting the `.expo` file at the root of your project and try again.
> 
> And if that doesn't work then use the tunneling option which works but is much slooower:
> 
> https://docs.expo.dev/more/expo-cli/#tunneling

Tunneling is the only thing that worked for me. (things that did not work were changing the node versions, using ngrok directly when ip address:8081 did not work, allowing inbound/outbound rules for 8081, etc.)

**Comment by TahseenSust** [comment]
Rebooting my router worked for me

**Comment by chhornponleu** [comment]
Got this issue on Mac. I need to disable Firewall to get it working.

**Comment by Ismailn16** [comment]
Is there a faster alternative to tunnelling? nothing else has worked for me, although i haven't tried reverting to older versions of node

**Comment by rajkumardongre** [comment]
Deleting .expo work for me

**Comment by patrickgeorge1** [comment]
In my case (developing on android emulator) it was an issue related to the emulator WiFi. It said "connected but not internet". I just clicked "disconnect" in WiFi settings and then "connect". This resolved my issue.

**Comment by Fusinix** [comment]
In my case, i had "Lockdown mode" turned on on my iphone, so turning it of worked for me.

**Comment by Nader-CS** [comment]
For me, it was solved when the device and my laptop were on the same network.

**Comment by jottenlips** [comment]
I had this issue with my android emulator. It was solved for me by going into the android emulators wifi settings and toggling wifi.

**Comment by adidahl** [comment]
I've changed my Wifi password, forgot to update it on my Android testing device, and got this issue.After reconnecting everything worked fine.

**Comment by cwangsanata** [comment]
Router reset resolved this issue for me.
