### ISSUE TITLE
error: index.js: [BABEL]: Cannot find module 'expo/config'

### ISSUE THREAD

**Issue by BMTmohammedtaha** [expo/expo#22663]
### Summary

The error message suggests that there is a missing module called 'expo/config' that cannot be found. This module is required by the 'expo-router' package, specifically in the 'getExpoConstantsManifest.js' file.

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

^46.0.21

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ^46.0.21 => 46.0.21
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.9 => 0.69.9
      react-native-web: ~0.18.7 => 0.18.12
    Expo Workflow: managed

### Minimal reproducible example

Logs for your project will appear below. Press Ctrl+C to exit.
Android Bundling failed 780ms
error: index.js: [BABEL]: Cannot find module 'expo/config'
Require stack:
- ___APP_PATH___\node_modules\expo-router\node\getExpoConstantsManifest.js
- ___APP_PATH___\node_modules\expo-router\babel.js
- ___APP_PATH___\node_modules\@babel\core\lib\config\files\module-types.js
- ___APP_PATH___\node_modules\@babel\core\lib\config\files\configuration.js
- ___APP_PATH___\node_modules\@babel\core\lib\config\files\index.js
- ___APP_PATH___\node_modules\@babel\core\lib\index.js
- ___APP_PATH___\node_modules\metro-transform-worker\src\index.js
- ___APP_PATH___\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js
- ___APP_PATH___\node_modules\metro\src\DeltaBundler\Transformer.js
- ___APP_PATH___\node_modules\metro\src\Bundler.js
- ___APP_PATH___\node_modules\metro\src\IncrementalBundler.js
- ___APP_PATH___\node_modules\metro\src\Server.js
- ___APP_PATH___\node_modules\metro\src\commands\dependencies.js
- ___APP_PATH___\node_modules\metro\src\index.flow.js
- ___APP_PATH___\node_modules\metro\src\index.js
- ___APP_PATH___\node_modules\@expo\cli\build\src\start\server\metro\resolveFromProject.js
- ___APP_PATH___\node_modules\@expo\cli\build\src\start\server\metro\instantiateMetro.js
- ___APP_PATH___\node_modules\@expo\cli\build\src\start\server\metro\MetroBundlerDevServer.js
- ___APP_PATH___\node_modules\@expo\cli\build\src\start\server\DevServerManager.js
- ___APP_PATH___\node_modules\@expo\cli\build\src\start\startAsync.js
- ___APP_PATH___\node_modules\@expo\cli\build\src\start\index.js
- ___APP_PATH___\node_modules\@expo\cli\build\bin\cli (While processing: ___APP_PATH___\node_modules\expo-router\babel.js)

**Comment by rafaelrcamargo** [comment]
@BMTmohammedtaha have you solved it?

**Comment by nasir733** [comment]
How did you solved it @BMTmohammedtaha  ?

**Comment by nisseenn** [comment]
+1

**Comment by AdHi018** [comment]
@nisseenn that didn't work for me. Does anyone have any other solutions?

**Comment by chakradharreddy82** [comment]
@BMTmohammedtaha  How did you solve it?

**Comment by amerllica** [comment]
@BMTmohammedtaha, How did you solve this issue?

**Comment by Genusuppal** [comment]
For those of you still looking for answer, I just found a work-around.
Do the following change to the file "C:\Users\<YourUsername>\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\env\paths.js" (Linux & MacOS will be different but similar)

Line No: 8
```diff
      exports.getAbsolute = exports.getProductionPath = exports.getPublicPaths = exports.getServedPath = exports.getPathsAsync = exports.getPaths = void 0;
      /* eslint-env node */
-     const config_1 = require("expo/config");
+     const config_1 = require("@expo/config");
      const find_yarn_workspace_root_1 = __importDefault(require("find-yarn-workspace-root"));
```

(This problem has actually been fixed in newer versions of expo-cli)

**Comment by 775647651** [comment]
> For those of you still looking for answer, I just found a work-around. Do the following change to the file "C:\Users<YourUsername>\AppData\Roaming\npm\node_modules\expo-cli\node_modules@expo\webpack-config\webpack\env\paths.js" (Linux & MacOS will be different but similar)
> 
> Line No: 8
> 
> ```diff
>       exports.getAbsolute = exports.getProductionPath = exports.getPublicPaths = exports.getServedPath = exports.getPathsAsync = exports.getPaths = void 0;
>       /* eslint-env node */
> -     const config_1 = require("expo/config");
> +     const config_1 = require("@expo/config");
>       const find_yarn_workspace_root_1 = __importDefault(require("find-yarn-workspace-root"));
> ```
> 
> (This problem has actually been fixed in newer versions of expo-cli)

You have solved my problem, thank you very much

**Comment by Jdonis2002** [comment]
in my case I do this change...
![image](https://github.com/expo/expo/assets/88345275/384ceac9-ed08-46ce-8b65-12f156190785)

![image](https://github.com/expo/expo/assets/88345275/8fc7a511-6827-4925-a386-141f54549c79)

**Comment by PierreAndreis** [comment]
why is this happening? I have expo installed. I don't think they mean for it to be actually importing @expo/config

@EvanBacon

**Comment by federalbyro** [comment]
[BABEL]: Cannot find module 'expo/config'
   json: "expo-build-properties": "~0.3.0"
   I don't understand

**Comment by s4rath07** [comment]
Teach me. What are your ways

**Comment by guillempuche** [comment]
## Solution for Expo v52 `Cannot find module 'expo/config'` error in a Yarn v2 monorepo

While working on a Yarn monorepo project, I encountered and solved the `Cannot find module 'expo/config'` error. Here's what I learned from studying the [Trezor monorepo](https://github.com/trezor/trezor-suite).

### The Problem
The issue arose because Yarn was inconsistently installing Expo's dependencies. Some packages like those listed in [expo/package.json](https://github.com/expo/expo/blob/main/packages/expo/package.json#L69-L88) were being installed in the app's directory, while others (like `babel-preset-expo`) were installed in the root directory.

### Attempted Solutions

1. **Metro Configuration**: I first tried configuring Metro's module resolution:
```js
nodeModulesPaths: [
    path.resolve(appRoot, 'node_modules'),
    path.resolve(monorepoRoot, 'node_modules'),
]
```
This didn't work because `babel-preset-expo` still couldn't locate `expo/config` when they were in the same directory level.

2. **Yarn Configuration**: I also tried these approaches in `yarnrc.yml`:
```yaml
# Approach 1: Limiting hoisting
nmHoistingLimits: workspaces

# Approach 2: Adding package extensions
packageExtensions:
  "@expo/cli@*":
    peerDependencies:
      "expo": "*"
```

### The Solution
The fix was to add the following configuration to the root `package.json`:
```json
{
  "dependenciesMeta": {
    "<your_monorepo_name>": {
      "built": true
    }
  }
}
```
This ensures proper package installation and resolution across the monorepo structure.

**Comment by guatedude2** [comment]
I recommend this solution for the yarn v2 monorepo:
in your package.json of the app add this:

```json
  "installConfig": {
    "hoistingLimits": "workspaces"
  },
```

no other config required aside from the [expo yarn v2 configuration](https://docs.expo.dev/more/create-expo/#yarn-2-modern) in the docs

> ## Solution for Expo v52 `Cannot find module 'expo/config'` error in a Yarn v2 monorepo
> While working on a Yarn monorepo project, I encountered and solved the `Cannot find module 'expo/config'` error. Here's what I learned from studying the [Trezor monorepo](https://github.com/trezor/trezor-suite).
> 
> ### The Problem
> The issue arose because Yarn was inconsistently installing Expo's dependencies. Some packages like those listed in [expo/package.json](https://github.com/expo/expo/blob/main/packages/expo/package.json#L69-L88) were being installed in the app's directory, while others (like `babel-preset-expo`) were installed in the root directory.
> 
> ### Attempted Solutions
> 1. **Metro Configuration**: I first tried configuring Metro's module resolution:
> 
> nodeModulesPaths: [
>     path.resolve(appRoot, 'node_modules'),
>     path.resolve(monorepoRoot, 'node_modules'),
> ]
> This didn't work because `babel-preset-expo` still couldn't locate `expo/config` when they were in the same directory level.
> 
> 2. **Yarn Configuration**: I also tried these approaches in `yarnrc.yml`:
> 
> # Approach 1: Limiting hoisting
> nmHoistingLimits: workspaces
> 
> # Approach 2: Adding package extensions
> packageExtensions:
>   "@expo/cli@*":
>     peerDependencies:
>       "expo": "*"
> ### The Solution
> The fix was to add the following configuration to the root `package.json`:
> 
> {
>   "dependenciesMeta": {
>     "<your_monorepo_name>": {
>       "built": true
>     }
>   }
> }
> Some of my configuration files:
> 
> // metro.config.js
> const path = require('node:path')
> const { getDefaultConfig } = require('expo/metro-config')
> const { mergeConfig } = require('@react-native/metro-config')
> const { wrapWithReanimatedMetroConfig } = require('react-native-reanimated/metro-config')
> 
> const appRoot = __dirname
> const monorepoRoot = path.resolve(appRoot, '../..')
> 
> const defaultConfig = getDefaultConfig(appRoot)
> 
> const customConfig = {
>   watchFolders: [
>     appRoot,
>   ],
>   resolver: {
>     platforms: ['android', 'ios'],
>     nodeModulesPaths: [
>       path.resolve(appRoot, 'node_modules'),
>       path.resolve(monorepoRoot, 'node_modules'),
>     ],
>     sourceExts: [
>       ...defaultConfig.resolver.sourceExts,
>       'mjs',
>     ],
>     disableHierarchicalLookup: true,
>     unstable_enablePackageExports: true,
>     unstable_conditionNames: ['react-native', 'require'],
>   },
>   resetCache: true,
> }
> 
> module.exports = wrapWithReanimatedMetroConfig(
>   mergeConfig(defaultConfig, customConfig),
> )
> // babel.config.js
> module.exports = api => {
>   api.cache(false)
> 
>   return {
>     env: {
>       production: {
>         plugins: ['transform-remove-console'],
>       },
>     },
>     presets: ['babel-preset-expo'],
>     plugins: [
>       ...(process.env.EAS_BUILD_PLATFORM === 'android'
>         ? []
>         : [
>             ['@tamagui/babel-plugin',
>               {
>                 components: ['@mymonorepo/shared-ui-core', 'tamagui'],
>                 config: '../../packages/shared/ui/core/src/themes/tamagui.config.ts',
>                 logTimings: true,
>                 disableExtraction: process.env.NODE_ENV === 'development',
>                 disable: true,
>               },
>             ],
>           ]),
>       'react-native-reanimated/plugin',
>     ],
>   }
> }
> This ensures proper package installation and resolution across the monorepo structure.
