### ISSUE TITLE
Unexpected end of stream on <dev-client server>

### ISSUE THREAD

**Issue by Foxeye-Rinx** [expo/expo#22668]
### Summary

I create a new project but the development build cannot connect to development server, which is started  by `npx expo start --dev-client`

<img width="368" alt="image" src="https://github.com/expo/expo/assets/22351393/8e624d87-e4d1-4439-858a-25a8967f8546">

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

package.json:
``` package.json
{
  "name": "test-flipper",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.15",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "expo-dev-client": "~2.2.1",
    "expo-build-properties": "~0.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

### Environment

```
Need to install the following packages:
  expo-env-info@1.0.5
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 3.6.0 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.2.0 - ~/.volta/tools/image/node/20.2.0/bin/node
      npm: 9.6.6 - ~/.volta/tools/image/node/20.2.0/bin/npm
      Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed
```

### Reproducible demo

Make sure you created an expo account and eas-cli is [loggedin
](https://docs.expo.dev/build/setup/#2-log-in-to-your-expo-account)

Create a GitHub repo then on the folder run:
`npx create-expo-app@latest .`

Run this command and answer questions: 
`eas build:configure`

```
✔ Would you like to automatically create an EAS project for @<your-expo-username>/<project-name>? … yes
✔ Created @@<your-expo-username>/<project-name> on Expo
✔ Linked local project to EAS project <project-id>
💡 The following process will configure your iOS and/or Android project to be compatible with EAS Build. These changes only apply to your local project files and you can safely revert them at any time.

✔ Which platforms would you like to configure for EAS Build? › All

✔ Generated eas.json
```
Run commands:
`npx expo install expo-dev-client`
`npx expo install expo-build-properties`

Build development-build and answer questions then install to the android simulator:
`eas build --profile development --platform android`

```
📝  Android application id Learn more
✔ What would you like your Android application id to be? … <your-application-id>
✔ Using remote Android credentials (Expo server)
✔ Generate a new Android Keystore? … yes
Detected that you do not have keytool installed locally.
✔ Generating keystore in the cloud...
✔ Created keystore
```
```
✔ Install and run the Android build on an emulator? … yes

✔ Successfully downloaded app 11s

Using open emulator: Pixel_3a_API_33_arm64-v8a

Installing your app...
✔ Successfully installed your app!

Starting your app...
✔ Successfully started your app!
```
Run development server:
`npx expo start --dev-client`

Connect to the dev server from android simulator device and see the error

**Comment by pyromaticx** [comment]
Experiencing this also with node v20.2.0 and local build on Win 11 / Physical device. My project is empty aside from adding expo-dev-client and react-native-nfc-manager libraries.

**Comment by pyromaticx** [comment]
Downgrading node to v18.16.0 works around the issue for me. After downgrade, I re-ran `npx expo install` and rebuilt.

**Comment by Foxeye-Rinx** [comment]
@pyromaticx, thanks! I just checked the eas build uses node 16 to build and the dev server with node v18.16.0 works. This is the image from EAS build:
<img width="801" alt="image" src="https://github.com/expo/expo/assets/22351393/4fbc7e4a-ccf0-463b-ba1e-99632422335c">

**Comment by Foxeye-Rinx** [comment]
https://docs.expo.dev/get-started/installation/#expo-cli
On the doc said that ` Only Node.js LTS releases (even-numbered) are recommended`, at the moment, it's 18.16.0 so I will close this issue.

**Comment by obsessivetree** [comment]
I was just having this issue while using node 20.2.0. Switched to 22.14.0 and it worked.
