### ISSUE TITLE
[expo-notifications] [bare] `getExpoPushTokenAsync` throws saying to call FirebaseApp.initializeApp(Context) first, when it has been called

### ISSUE THREAD

**Issue by jsindos** [expo/expo#22674]
### Minimal reproducible example

https://snack.expo.dev/@jsindos/push-notifications

### Summary

I'm running the minimal reproducible example above in a bare project, but have also installed the [Firebase JS SDK](https://docs.expo.dev/guides/using-firebase/?redirected#using-firebase-js-sdk) with the below code, having successfully set up a web app in my Firebase project.

```
npx expo install firebase
```
```
import { initializeApp } from 'firebase/app';

// Optionally import the services that you want to use
// import {...} from "firebase/auth";
// import {...} from "firebase/database";
// import {...} from "firebase/firestore";
// import {...} from "firebase/functions";
// import {...} from "firebase/storage";

// Initialize Firebase
const firebaseConfig = {
  apiKey: 'api-key',
  authDomain: 'project-id.firebaseapp.com',
  databaseURL: 'https://project-id.firebaseio.com',
  projectId: 'project-id',
  storageBucket: 'project-id.appspot.com',
  messagingSenderId: 'sender-id',
  appId: 'app-id',
  measurementId: 'G-measurement-id',
};

const app = initializeApp(firebaseConfig);
// For more information on how to access Firebase in your project,
// see the Firebase documentation: https://firebase.google.com/docs/web/setup#access-firebase
```

I am getting the following error when running `token = (await Notifications.getExpoPushTokenAsync()).data`

```
Possible Unhandled Promise Rejection (id: 0):
Error: Encountered an exception while calling native method:
Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Default FirebaseApp is not initialized in this process com.myapp. Make sure to call FirebaseApp.initializeApp(Context) first.
```

The error is telling me to do what I have done, so I am a little bit stuck. I am also going to try and add additional configuration following [Get Credentials for development builds](https://docs.expo.dev/push-notifications/push-notifications-setup/#get-credentials-for-development-builds), which requires creating an Android project in Firebase.

Any other ideas appreciated.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2023.03.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.0.1
    Expo Workflow: bare

**Comment by Kudo** [comment]
hi there! to get `Notifications.getExpoPushTokenAsync()` working on bare project, you need to [setup firebase and fcm manually](https://firebase.google.com/docs/android/setup), which includes something like
- copy **google-services.json** to **android/app/google-services.json**
- add `classpath 'com.google.gms:google-services:4.3.3'`
- add `apply plugin: 'com.google.gms.google-services'`

**Comment by aliaro428** [comment]
Once you've added this Expo code, you need to prebuild your app before running it.
