### ISSUE TITLE
[docs] CI build documentation implies `eas-cli` can repair expired provisioning profiles

### ISSUE THREAD

**Issue by bradjones1** [expo/expo#22673]
### Summary

I _think_ this is a documentation bug but it might be a bug in EAS cli? I'm erring on the side of docs, though.

In the section titled [(Optional) Provide an ASC Api Token for your Apple Team](https://docs.expo.dev/build/building-on-ci/#optional-provide-an-asc-api-token-for-your-apple-team) it states:

> In the event your iOS credentials need to be repaired, we will need an ASC API key to authenticate ourselves to Apple in CI. A common case is when your provisioning profile needs to be re-signed.

I ran into a situation where my provisioning profile had expired (it happens every year...) and I was getting messages like this in my CI logs:

```
Provisioning Profile has expired.
Failed to set up credentials.
    Error: Provisioning profile is not configured correctly. Run this command 
    again in interactive mode.
```

Reading the docs, it seemed to me that EAS could fix this for me, but apparently that's not the case. I think the documentation could be clearer on what exactly it can and cannot fix automatically with the Apple API keys in non-interactive mode.

### Link to the related docs page

https://docs.expo.dev/build/building-on-ci/#optional-provide-an-asc-api-token-for-your-apple-team

**Comment by brentvatne** [comment]
thanks for calling this out! I've removed this section from docs for now: b058eea7ff3a148ce0ee247c4c45101071c13b71

we're going to revisit this feature soon and hopefully we'll have a good solution to share before too long
