### ISSUE TITLE
Debugger does not work out-of-the-box: "Status: Waiting"

### ISSUE THREAD

**Issue by crummy** [expo/expo#22686]
### Summary

I'm new to React Native and Expo so bear with me. I've tried and failed to get a debugger connected on the little app I'm working on, so I've tried to create a new app from scratch and even then cannot connect the debugger.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

```
  "dependencies": {
    "expo": "~48.0.15",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.8"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - /usr/local/bin/node
      Yarn: 3.5.1 - /usr/local/bin/yarn
      npm: 9.3.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    npmGlobalPackages:
      eas-cli: 3.13.2
    Expo Workflow: managed
```

### Reproducible demo

Here are the steps I took:

```
npx create-expo-app my-app
cd my-app
npx expo start
i (to open iOS simulator)
In the simulator, ensure Expo Go is loaded and connected to my development instance.
```
Then I visited localhost:19000/debugger-ui in my browser.

<img width="598" alt="image" src="https://github.com/expo/expo/assets/690626/fac24252-3526-464b-be0e-586d991bcd3c">

The Status section is always "Waiting", unless I have another debugger running like React Native Debugger (which has similar problems) - then Status reports another debugger is running.

In the documentation I can see normally Status shows Connected. I have not been able to reach that point.

**Comment by Kudo** [comment]
hi there! the [remote debugging](http://localhost:19000/debugger-ui) does not work well on hermes engine. (which is default js engine on sdk 48), and we are getting to deprecate the legacy remote debugging entirely in next sdk. as a replacement, please try to press `j` key in terminal ui from `npx expo start` as the [doc mentioned](https://docs.expo.dev/guides/using-hermes/#javascript-debugger).
