### ISSUE TITLE
React navigation header not fast refreshing`

### ISSUE THREAD

**Issue by Enzodtz** [expo/expo#22680]
### Summary

Hi,

I'm using react navigation and I'm not being able to fast refresh my header changes.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.4
      expo: ~48.0.15 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

### Minimal reproducible example

If i try to change the header of my screen in this manner:

```tsx

...

<NavigationContainer>
  <Tab.Navigator>
    <Tab.Screen
      options={{
        headerTitle: Header,
      }}
      name="Screen"
      component={Screen}
    />
  </Tab.Navigator>
</NavigationContainer>

...
```

to this header:

```tsx
export function Header() {
  return <Text>A</Text>;
}
```

and try to add a text into it, it wont change in the screen, altought it still says "refreshing app".

If I try it this way:

```tsx
  header: () => <Header />,
```

it works. 

Obviously, this is related to the non re-creation on every re-render of the pure component without a wrapper function, and not a problem by itself, but I would like to ask if there's anyway in which I can achieve that desired behaviour during development without performance loss in production.

Thanks.

**Comment by Kudo** [comment]
hi there! i've tried the code and the fast refreshing works for me on ios Expo Go. would be good if you could provide a github repor minimal reproducible example.

```jsx
import * as React from "react";
import { Text, View } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";

function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Settings!</Text>
    </View>
  );
}

function Header() {
  return <Text>A</Text>;
}
const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen
          name="Home"
          component={HomeScreen}
          options={{ headerTitle: () => <Header /> }}
        />
        <Tab.Screen name="Settings" component={SettingsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

```

**Comment by ghost2023** [comment]
same on android physical device
