### ISSUE TITLE
[EAS CLI][Organization] I can no longer do builds with membership account?!

### ISSUE THREAD

**Issue by firasrg** [expo/expo#22696]
### Summary

Hello!

Since last year, my team and I, use Expo to develop our apps. We've made **an organization account** to perform builds as we go (our product owner / manager add developers as members). In dev environement, I was able to launch DEV or QA builds, if I login with my membership account. 

But today, while I was trying to do a new one, I got a strange behavior from **eas-cli** and error was thrown after succesfully connecting to my Apple Developer Account. 

```shell
Failed to set up credentials.
Entity not authorized: AppleAppIdentifierEntity[04ab8988-04e7-428f-8e2e-2d2c6bda5637] (viewer = RegularUserViewerContext[358e285f-4bc1-45d8-ac1f-1bd16e9f19fd], action = READ, ruleIndex = -1)
Request ID: 22496db2-dee8-4bd6-9f53-e5224f31b030
    Error: GraphQL request failed.
error Command failed with exit code 1.
```

I've tried multiple times to relaunch it, but didn't work! So I came to an idea, I've logout (with Expo CLI), and **logged in with the organization account**; The build was launched without any issue!

What is this behavior please ? I don't see any explanation to it neither on docs or your Github. 

Please help. 

### What platform(s) does this occur on?

iOS

### SDK Version

46

### Environment

  expo-env-info 1.0.5 environment info:               
    System:                                           
      OS: Windows 10 10.0.19045                       
    Binaries:                                         
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD   
    npmPackages:                                      
      expo: ^46.0.0 => 46.0.20                        
      react: 18.0.0 => 18.0.0                         
      react-native: 0.69.9 => 0.69.9                  
    Expo Workflow: managed      

### Minimal reproducible example

 I don't need to add any code here as it's not about code.

But, this is the command I've used to launch the build:
`eas build --platform ios --profile development` 

This is a part of my eas.json:
```json
{
  "cli": {
    "version": ">= 0.52.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "resourceClass": "m-medium"
      }
    }
 }
 ```

**Comment by brentvatne** [comment]
hi @firasrg! which account was this under? when was the last time you successfully ran a build from your account? (not the org account). can you link to that build? what eas cli version are you using?

**Comment by firasrg** [comment]
Hi

> which account was this under?

My own expo account (for work). 

---

> when was the last time you successfully ran a build from your account?

Based on our builds history, it was a month ago: Apr 17, 2023 3:56 PM

---

> can you link to that build?

I can send you like in private msg, not here sorry. 

---

> what eas cli version are you using?

v3.9.1

**Comment by brentvatne** [comment]
i asked around internally about this and here's our take of the situation

> The ‘organization account’ (ig*-****e), owns the credentials. It has given the user, ig*-**g, VIEWER permissions
The user, ig*-**g, is trying to read/write the credentials owned by the organization account, but is encountering an error
A while ago, we changed the privacy policy of credentials. In order to read or write them, you need to have at least `PUBLISH` permissions.

so, this should be resolved if your account is given publish permissions

**Comment by firasrg** [comment]
Hello @brentvatne !

Thank you for your time investigating on this. The information seems to be correct. I respect your new privacy policy 
but, I think that it's not clear that, EAS Cli shows me that strange error. 

Instead: I'd suggest a friendly msg like this one: 
> Sorry, you don't have enough permissions to do builds. Please refer to your organization account holder.
