### ISSUE TITLE
Expo camera does not scan barcodes on IOS and it does on Android

### ISSUE THREAD

**Issue by rpostulart** [expo/expo#22694]
### Minimal reproducible example

https://snack.expo.dev/@rpostulart/expo-camera-barcode-scanner

### Summary

With this code I have no issues on scanning barcodes on Android, but on IOS nothing happens. It seems like something with focus and trigger the onBarCodeScanned. Also in the log nothing happens.

Any help please?

**
Barcode can be generated here: https://barcode.tec-it.com/en
**

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 11.7.2
Shell: 5.0.11 - /usr/local/bin/bash
Binaries:
Node: 16.13.0 - /usr/local/bin/node
Yarn: 1.22.5 - /usr/local/bin/yarn
npm: 9.5.0 - /usr/local/bin/npm
Managers:
CocoaPods: 1.11.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
Android SDK:
API Levels: 30
Build Tools: 30.0.2
System Images: android-30 | Google Play Intel x86 Atom
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6626763
Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
npmPackages:
expo: ~47.0.14 => 47.0.14
react: 18.1.0 => 18.1.0
react-dom: 18.1.0 => 18.1.0
react-native: 0.70.8 => 0.70.8
react-native-web: ~0.18.7 => 0.18.12
npmGlobalPackages:
eas-cli: 3.6.1
expo-cli: 6.1.0
Expo Workflow: bare

**Comment by sjchmiela** [comment]
Hey! What iOS version do you have on your device?

Could you please try scanning the code again using https://snack.expo.dev/@sjchmiela/expo-camera-barcode-scanner? I made minimal changes to your Snack and tried scanning the code myself and it seemed to work! 🤔 

![IMG_9686](https://github.com/expo/expo/assets/1151041/e1d0687c-7cf8-4173-9b92-3e7979c032b1)

**Comment by atablash** [comment]
Same issue here! Expo 49.

We wanted to switch from `expo-barcode-scanner` to `expo-camera`, because `expo-barcode-scanner` did crash from time to time.

So the `expo-camera` works fine with Expo Go, but does not work with the final (TestFlight) build.

We scan Aztec codes.

**Comment by gusnaughton** [comment]
Same issue here, mainly dealing with expo-barcode-scanner's lack of ability to expand beyond the 1:1 aspect ratio. My use case is working perfectly on Android, but neither feedback nor errors on iOS.

**Comment by gusnaughton** [comment]
@atablash did you find a solution for the testflight app not working?

**Comment by lucarducci** [comment]
I still have the same issue, please reopen.
Using expo 49.0.8 and Expo-camera 13.4.4.

It works on expo but not on testflight

**Comment by patozavala** [comment]
Same issue here. Works on expo, but not on TestFlight.
