### ISSUE TITLE
Validate params on Facebook before making native API call

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#227]
If you pass in appId as a number rather than string your app will crash, we should validate this and warn.

We should validate the other params as well.

**Comment by nikki93** [comment]
👌 will check this out soon -- can be done in pureJS so will prioritize the native changes for next SDK first. @brentvatne do you think it's worth doing a typecheck pass over the entire API?

**Comment by brentvatne** [comment]
@nikki93 - yep definitely worth it

**Comment by dikaiosune** [comment]
Assigning @nsillik, who's been doing a pass over SDK APIs to do more JS-side validation.
