### ISSUE TITLE
eas build stuck at Bundle React Native code and images

### ISSUE THREAD

**Issue by okoroeugene** [expo/expo#22711]
### Minimal reproducible example

.

### Summary

This is a production store build on the eas cloud infrastructure and for every time it gets stuck at `bundle react native code and images the transform cache was reset.`

Meanwhile, development builds (internal distribution) works fine, this issue only happens with store builds.

Also, before now I was getting this error `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` and then I changed the `resourceClass` from `m-medium` to `large`, ever since I changed it to large, I then get stuck at `Bundle React Native code and images`

<img width="1126" alt="Screen Shot 2023-05-31 at 9 44 05 PM" src="https://github.com/expo/expo/assets/21360216/fd153bc3-f2c5-4ef8-83e1-4338d015507b">

here's my `eas.json` config for production build:

```
"production": {
      "distribution": "store",
      "ios": {
        "buildConfiguration": "Release",
        "resourceClass": "m-medium"
      },
      "env": {
        "API_URL": "https://api.production.com"
      }
    }
```

also here's a list of my packages just incase there's a package installed that has compatibility issues:

```
"dependencies": {
    "@invertase/react-native-apple-authentication": "2.2.2",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/geolocation": "3.0.6",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-firebase/analytics": "17.5.0",
    "@react-native-firebase/app": "17.5.0",
    "@react-native-firebase/auth": "17.5.0",
    "@react-native-firebase/database": "17.5.0",
    "@react-native-firebase/firestore": "17.5.0",
    "@react-native-firebase/functions": "17.5.0",
    "@react-native-firebase/messaging": "17.5.0",
    "@react-native-firebase/storage": "17.5.0",
    "@react-native-google-signin/google-signin": "9.0.0",
    "@react-native-picker/picker": "2.4.8",
    "@react-navigation/drawer": "6.6.2",
    "@react-navigation/native": "6.1.6",
    "@react-navigation/stack": "6.3.16",
    "algoliasearch": "3.29.0",
    "deep-equal": "1.0.1",
    "deprecated-react-native-prop-types": "2.3.0",
    "dotenv": "16.0.3",
    "dotenvenc": "1.0.4",
    "expo": "48.0.17",
    "expo-build-properties": "~0.6.0",
    "expo-clipboard": "~4.1.2",
    "expo-dev-client": "~2.2.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "1.4.4",
    "firebase": "9.6.11",
    "iap-receipt-validator": "1.0.6",
    "moment": "2.29.4",
    "moment-timezone": "0.5.35",
    "patch-package": "6.4.7",
    "prop-types": "15.6.2",
    "react": "18.2.0",
    "react-instantsearch-native": "5.2.x",
    "react-native": "0.71.8",
    "react-native-busy-indicator": "https://github.com/okoroeugene/react-native-busy-indicator#master",
    "react-native-calendars": "1.1292.0",
    "react-native-collapsible": "1.6.0",
    "react-native-credit-card-input": "0.4.1",
    "react-native-elements": "3.4.2",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-global-props": "1.1.1",
    "react-native-iap": "12.10.4",
    "react-native-image-picker": "4.10.3",
    "react-native-maps": "1.3.2",
    "react-native-message-bar": "https://github.com/okoroeugene/react-native-message-bar",
    "react-native-modal": "13.0.1",
    "react-native-modal-datetime-picker": "15.0.1",
    "react-native-popup-menu": "0.15.11",
    "react-native-raw-bottom-sheet": "2.2.0",
    "react-native-reanimated": "2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-simple-toast": "1.1.3",
    "react-native-store-review": "0.1.5",
    "react-native-swiper": "1.6.0",
    "react-native-webview": "11.26.0",
    "rollbar-react-native": "0.9.3"
  },
  "devDependencies": {
    "@babel/core": "^7.22.1",
    "@babel/plugin-proposal-optional-chaining": "^7.21.0",
    "@babel/preset-env": "^7.22.4",
    "jest": "29.2.1",
    "jest-expo": "48.0.0",
    "jest-fetch-mock": "3.0.3",
    "react-native-dotenv": "3.4.8",
    "request": "2.34",
    "typescript": "4.9.4",
    "utf-8-validate": "5.0.2"
  },
```

I've exhausted every possible solution and i'll be open to suggestions, ty!

### Environment

System:
      OS: macOS 12.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2023.01.23.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.17 => 48.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.3.7
    Expo Workflow: managed

**Comment by andrewkucz** [comment]
Thought I'd share what worked for me in case any one searching online finds this issue but I was having the same problem. Building worked locally on my M1 MBP so I was very confused. Ultimately the following worked for me, adding resourceClass and fastlane version to my eas config.

Not sure which did it but my build worked after this. Fastlane v2.213.0 was the one on my laptop that it was working with.

GL

```
{
    "preview": {
      "distribution": "internal",
      "resourceClass": "large",
      "ios": {
        "fastlane": "2.213.0"
      }
    },
    "production": {}
  }
}

```

**Comment by okoroeugene** [comment]
@andrewkucz tried that it doesn't work.
funny enough builds for internal distribution works just fine, it gets stuck only for store builds 🤔

**Comment by brunocrosier** [comment]
@andrewkucz just want to say THANK YOU! spent hours on this 😭

**Comment by Rajanikanth9** [comment]
till 24 hours over, but building showing as blank black screen, even cancelled, the build not yet cancelled. how can resolve? can anyone help me please?
