### ISSUE TITLE
Run Android command doesnt pick generated APK File when using product flavors and variant option

### ISSUE THREAD

**Issue by srilalitharanikintali** [expo/expo#22725]
### Summary

Hi,

When running run-android command for an expo app which has product flavors and with a variant option other than default debug, After the build step is done the APK file is not picked from the expected generated folder. 

When I debugged the issue I identified that it is occurring due to this [line](https://github.com/expo/expo/blob/887aceac3db640a2900961ccff84eebe63e718c3/packages/%40expo/cli/src/run/android/resolveGradleProps.ts#L35), we give the variant value as <flavor-name><build-type> but the line mentioned takes the first word as build type

The issue has already been mentioned [here](https://github.com/expo/expo/issues/18315). But as it has been marked stale and closed I am rising a new issue

### What platform(s) does this occur on?

Android

### SDK Version

48.0.16

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 20230101.175141.0 - /usr/local/bin/watchman
    npmPackages:
      @expo/metro-config: 0.7.1 => 0.7.1 
      babel-preset-expo: ~9.3.2 => 9.3.2 
      expo: 48.0.16 => 48.0.16 
      metro: 0.74.1 => 0.74.1 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.12 => 0.18.12 
    Expo Workflow: managed

### Minimal reproducible example

Example Repository - https://github.com/srilalitharanikintali/expo-run-android-example

Command to run the app - npx nx run test-flavors:run-android

Steps to reproduce:

1. To check without product flavors - remove productFlavors in  `packages/test-flavors/android/app/build.gradle` and run the command mentioned above
2. To check with product flavors - you can directly run the command mentioned above

Attaching the outputs with and without product flavors

![Without Product Flavors](https://github.com/expo/expo/assets/28941709/c23b1a1f-b753-45ae-9f57-252825a16edb)
![With Product Flavors](https://github.com/expo/expo/assets/28941709/9c5b7f16-04c5-48ee-9990-41181bf98b5b)

**Comment by prasaduu** [comment]
I'm also facing the same issue

**Comment by jaymes-bearden** [comment]
Facing the same issue as well.

**Comment by srilalitharanikintali** [comment]
Hi @jaymes-bearden 

Flipping the resolved values directly without spreading them would not help when we have multiple dimensions along with flavors, instead, I guess instead we can do this

```
const flavorsAndBuildType = variant.split(/(?=[A-Z])/).map((v)=>v.toLowerCase()
     );
const buildType = flavorsAndBuildType[flavorsAndBuildType.length-1]
const flavors = flavorsAndBuildType.slice(0,flavorsAndBuildType.length-1)
```

We are currently using this as a patch in our project and it seems to work fine for us

**Comment by chakravarthi-bb** [comment]
I am still facing this issue of build twice
