### ISSUE TITLE
"expo upgrade is not supported in the local CLI" is confusing

### ISSUE THREAD

**Issue by dcposch** [expo/expo#22747]
### Summary

Currently, `npx expo upgrade` gives the following message.

```
$ expo upgrade is not supported in the local CLI, please use expo-cli upgrade instead
```

But then the global `expo-cli` says its deprecated, and to use `npx expo` instead.

This cost me some time and confusion. The error message would benefit from clarification.

- is `expo upgrade` deprecated in general, and we should just use `npm i expo@latest` instead?
- or is the old global CLI deprecated mostly, but still the recommended way to do expo version upgrade?

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.13.2
    Expo Workflow: managed
```

### Minimal reproducible example

```
npx expo upgrade
```

**Comment by alanjhughes** [comment]
The steps to upgrading have changed and are detailed [here](https://blog.expo.dev/expo-sdk-48-ccb8302e231)

**Comment by pfcodes** [comment]
Running `npx expo upgrade` should probably give the correct instructions instead of instructing users to install the deprecated global cli.

**Comment by colingoodale** [comment]
The error message from the cli is a time waster.

**Comment by Yumesh-Kumar** [comment]
This works for me
`npx expo-cli upgrade`

**Comment by dcposch** [comment]
In what way does it work / what do you see when you run that command? I see the following:

```
$ npx expo-cli upgrade

  $ expo upgrade is not supported in the local CLI, please use expo-cli upgrade instead
```

**Comment by Yumesh-Kumar** [comment]
> In what way does it work / what do you see when you run that command? I see the following:
> 
> ```
> $ npx expo-cli upgrade
> 
>   $ expo upgrade is not supported in the local CLI, please use expo-cli upgrade instead
> ```

in my case when I tried to upgrade expo SDK from 48 to 49 it worked

**Comment by Yumesh-Kumar** [comment]
> > In what way does it work / what do you see when you run that command? I see the following:
> > ```
> > $ npx expo-cli upgrade
> > 
> >   $ expo upgrade is not supported in the local CLI, please use expo-cli upgrade instead
> > ```
> 
> in my case when I tried to upgrade expo SDK from 48 to 49 it worked

![image](https://github.com/expo/expo/assets/86765481/3504e303-5cdd-4fa6-b07e-2a9895564a18)

**Comment by dcposch** [comment]
I think you must have an older version of `expo-cli` still installed...

Try `npx expo-cli@latest upgrade` and you should see the `expo upgrade is not supported` error.

Fixed here: https://github.com/expo/expo/pull/23752

**Comment by dcposch** [comment]
Still an issue

**Comment by berengamble** [comment]
Even more confusing.. It appears to work, then says it's not supported

```
npx expo-cli@latest upgrade
Need to install the following packages:
expo-cli@6.3.10
Ok to proceed? (y) Y
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated expo-cli@6.3.10: The global Expo CLI has been superseded by 'npx expo' and eas-cli –– Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421

  $ expo upgrade is not supported in the local CLI, please use expo-cli upgrade instead

```

**Comment by moedeveloper** [comment]
Still the same issue any fix?

**Comment by zaidhaan** [comment]
The linked PR for this discussion looks to suggest that `npm install expo@latest && npx expo install --fix` would fix this.

(I have not tried it myself though)

**Comment by vithal-wadje** [comment]
Someone suggested in the comment section use the following command 

`npx expo-cli upgrade`

The above command worked for me to fix the warning **expo upgrade is not supported in the local CLI**
![image](https://github.com/expo/expo/assets/9838323/dc63c9e7-4895-409a-a357-3a045bff43c7)

**Note:** I am using the VS code and PowerShell command terminal.

**Comment by edi** [comment]
Seems like a circular error.

If I run `npx expo upgrade`, I get `expo upgrade is not supported in the local CLI, please use expo-cli upgrade instead`

However, if I run the suggested command `expo-cli upgrade`, then I get:

```
The global expo-cli package has been deprecated.                   

The new Expo CLI is now bundled in your project in the expo package.   
Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.        

To use the local CLI instead (recommended in SDK 46 and higher), run:   
› npx expo <command>
```

So, running it locally, tells me to run it globally. Running it globally, tells me to run it locally.
However, the latter error thrown by `expo-cli upgrade` still goes through with upgrading my project, just that it is weird and confusing.

**Comment by ViniciusPolloGomes** [comment]
for expo version 50 seconds documentation I used the following command:

```
yarn add expo-router@~3.4.7 react-native-safe-area-context@4.8.2 react-native-screens@~3.29.0 expo-linking@~6.2.2 expo-constants@~15.4.5 
expo-status-bar@~1.11.1
```

It is important to highlight that we must use nvm to change to a more compatible node version, which is guided in the expo node 18.18.0 documentation

https://www.youtube.com/watch?v=Zrq8reSxfUU

`{
  "name": "igniteteams",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo-google-fonts/roboto": "^0.2.3",
    "@expo/webpack-config": "^19.0.1",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.14",
    "expo": "~50.0.5",
    "expo-constants": "~15.4.5",
    "expo-font": "~11.10.2",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.7",
    "expo-status-bar": "~1.11.1",
    "expo-updates": "~0.24.9",
    "phosphor-react-native": "^1.1.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-web": "~0.19.6",
    "styled-components": "^5.3.9"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "@types/styled-components": "^5.1.26",
    "@types/styled-components-react-native": "^5.2.1",
    "babel-plugin-module-resolver": "^5.0.0",
    "typescript": "^5.3.0"
  },
  "resolution": {
    "@types/react": "~18.0.14"
  },
  "private": true,
  "packageManager": "yarn@4.1.0"
}`

**Comment by vonovak** [comment]
Hello,

`npx expo upgrade` now gives:

> $ expo upgrade is not supported in the local CLI, please follow this guide https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/ instead

Hence I'm going to close this as resolved

Thank you 👍
