### ISSUE TITLE
expo-auth-session/providers/google Android Standalone Issue

### ISSUE THREAD

**Issue by Freem11** [expo/expo#22743]
### Summary

HI, I'm on SDK 48 and I have pretty much cloned the example for the expo-auth-session/providers/google and on IOS it works flawlessly but on Android it keeps returning with  "response?dismiss" 
Note: I'm also using expo-auth-session/providers/facebook and it is working fine on both platforms 

I have been working with a member of the expo team on the forums and they say that the standalone Android is working when they test so I'm hoping that someone can spot where I have messed up?

I'm also going to include all my dependencies just in case one of them is causing a conflict of some sort?

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "^6.7.3",
    "@supabase/supabase-js": "^1.35.7",
    "expo": "~48.0.18",
    "expo-application": "~5.1.1",
    "expo-auth-session": "~4.0.3",
    "expo-build-properties": "^0.6.0",
    "expo-constants": "~14.2.1",
    "expo-crypto": "~12.2.1",
    "expo-font": "~11.1.1",
    "expo-image-picker": "^14.0.3",
    "expo-location": "^15.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-task-manager": "^11.1.1",
    "expo-updates": "~0.16.4",
    "expo-web-browser": "~12.1.1",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.8",
    "react-native-autocomplete-dropdown": "^2.0.7",
    "react-native-dotenv": "^3.3.1",
    "react-native-email": "^2.1.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-inset-shadow": "^1.0.3",
    "react-native-lightbox-v2": "^0.9.0",
    "react-native-maps": "1.3.2",
    "react-native-modal-datetime-picker": "^15.0.1",
    "react-native-pager-view": "^6.1.2",
    "react-native-places-input": "^1.1.7",
    "react-native-reanimated": "~2.14.4",
    "react-native-size-matters": "^0.4.0",
    "react-native-tab-view": "^3.3.0",
    "react-native-url-polyfill": "^1.3.0",
    "supercluster": "^7.1.5",
    "use-supercluster": "^0.4.0"

### Environment

eas project info
manage project

USAGE
  $ eas project:COMMAND

COMMANDS
  project:info  information about the current project
  project:init  create or link an EAS project

matthewfreeman@Matthews-iMac DiveGoMobile % eas open
✔ Opened https://expo.dev/accounts/freem11/projects/DiveGoMobile
matthewfreeman@Matthews-iMac DiveGoMobile % npx expo-env-info                
Need to install the following packages:
  expo-env-info
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.3.7
    Expo Workflow: bare

### Reproducible demo

app.json:

"expo": {
    "name": "DiveGo",
    "slug": "DiveGoMobile",
     "scheme": [
      "com.divego",
      "fbXXXXXXXXXXX"
    ],
....}

signin.js:

import * as WebBrowser from "expo-web-browser";
import * as AuthSession from "expo-auth-session";
import * as Google from "expo-auth-session/providers/google";
import * as Facebook from "expo-auth-session/providers/facebook";

WebBrowser.maybeCompleteAuthSession();

const googleAndroidClientId = config.ANDROID_CLIENT_ID;
const googleIOSClientId = config.IOS_CLIENT_ID;
const facebookAppId = config.FACEBOOK_APP_ID;

const [req, res, promptAsync] = Google.useAuthRequest({
    androidClientId: googleAndroidClientId,
    iosClientId: googleIOSClientId,
  });

  const [req2, res2, promptAsync2] = Facebook.useAuthRequest({
    clientId: facebookAppId,
  });

 useEffect(() => {
    handleFacebookSignIn();
  }, [res2]);

  useEffect(() => {
    handleGoogleSignIn();
  }, [res]);

  async function handleGoogleSignIn() {
    alert("response?" + res.type).                          <----FAILS HERE
    if (res?.type === "success") {
      await getGoogleUserData(res.authentication.accessToken);
    }
  }

async function handleFacebookSignIn() {
    if (res2 && res2?.type === "success" && res2.authentication) {
      await getFacebokUserData(res2.authentication.accessToken);
    }
  }

const handlePAsync = async () => {
    const res1 = await promptAsync2();
  };

  return (
    <View style={styles.container}> ....

<TouchableWithoutFeedback
          onPress={() => {promptAsync( { showInRecents: true } );}}
          disabled={!req}
        >
          
          <View style={[styles.SignUpWithButtons]}>
            <Image source={googleLogo} style={[styles.gLogo]} />
            <Text
              style={{
                color: "#FFFFFF",
                fontFamily: "PermanentMarker_400Regular",
                fontSize: 12,
                opacity: 0.7,
              }}
            >
              Sign In With Google
            </Text>
          </View>
        </TouchableWithoutFeedback>

        <TouchableWithoutFeedback onPress={handlePAsync}>
          <View style={[styles.SignUpWithButtons]}>
            <Image source={facebookLogo} style={[styles.fbLogo]} />
            <Text
              style={{
                marginLeft: scale(5),
                color: "#FFFFFF",
                fontFamily: "PermanentMarker_400Regular",
                fontSize: 12,
                opacity: 0.7,
              }}
            >
              Sign In With Facebook
            </Text>
          </View>
        </TouchableWithoutFeedback>
...
     </View>

**Comment by RickYangzz** [comment]
I met the same issue.

**Comment by Freem11** [comment]
@RickYangzz if you still are, you should know that Expo deprecated this library and the Facebook equivalent last year (early 2023) they now recommend using "@react-native-google-signin/google-signin" which is what I switched to and with some struggling manged to get it working
