### ISSUE TITLE
Android EAS build failed, Error loading TypeScript application entry point with Expo Routing File System,  SDK 48

### ISSUE THREAD

**Issue by Nanfack-Takoutsi-Yvan** [expo/expo#22749]
### Minimal reproducible example

GitHub Repository: https://github.com/Nanfack-Takoutsi-Yvan/expo-error-report.git  Instructions to run the project:  Clone the repository to your local machine. Install the required dependencies by running npm install or yarn install. Configure your environment variables, if necessary. Build the Expo app for Android using the command expo build:android. Observe the error message related to the application entry point. Note: Ensure that you have the latest Expo SDK version installed to test against the latest updates and resolve any potential compatibility issues.  git remote set-url origin git@github.com-Nanfack-Takoutsi-Yvan:Nanfack-Takoutsi-Yvan/expo-error-report.git

### Summary

I am encountering an issue while building my Expo app for Android with TypeScript. I have recently implemented the new Expo routing file system and have not made any changes to the file structure. However, during the build process, I consistently encounter the following error while my entry point is index.ts:

```bash
Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.
```
```bash
[stderr] 
Error: @build-script-error-begin
[stderr] 
Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.
[stderr] 
@build-script-error-end
[stderr] 
    at /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:36:11
[stderr] 
    at Object.<anonymous> (/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:99:3)
[stderr] 
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
[stderr] 
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[stderr] 
    at Module.load (node:internal/modules/cjs/loader:1033:32)
[stderr] 
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[stderr] 
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[stderr] 
    at node:internal/main/run_main_module:22:47
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':expo-updates:createReleaseExpoManifest'.
[stderr] 
> Process 'command 'node'' finished with non-zero exit value 1
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================

[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 3m 25s
114 actionable tasks: 114 executed
```
here is my `index.ts`  file:
```ts
import "expo-router/entry"
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/yvanov/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.11 => 48.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.3.7
    Expo Workflow: managed

**Comment by ablankenship10** [comment]
Change your index.ts to index.js. Agree this is a bug though, the default install should work by default.

**Comment by Nanfack-Takoutsi-Yvan** [comment]
Thank you for your quick and kind reply, I did and it led me to another error. Please note that I use eas to build my application. 

```bash
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1:
[stderr] 
Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
A problem was found with the configuration of task ':app:createBundleReleaseJsAndAssets' (type 'BundleHermesCTask').
[stderr] 
- In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '/home/expo/workingdir/build/********' which doesn't exist.
[stderr] 
Reason: An input file was expected to be present but it doesn't exist.
[stderr] 
Possible solutions:
[stderr] 
1. Make sure the file exists before the task is called.
[stderr] 
2. Make sure that the task which produces the file is declared as an input.
[stderr] 
Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace
[stderr] 
option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 4m 19s
196 actionable tasks: 196 executed
````

**Comment by 1623311678** [comment]
> Change your index.ts to index.js. Agree this is a bug though, the default install should work by default.

Isn't that a problem for expo-updates?
I saw this error 'Execution failed for task ': expo - updates: createReleaseExpoManifest'.
Of course, I also encountered this problem, using expo SDK48 and expo-updates@0.16

**Comment by 1623311678** [comment]
> Thank you for your quick and kind reply, I did and it led me to another error. Please note that I use eas to build my application.
> 
> ```shell
> [stderr] 
> FAILURE: Build completed with 2 failures.
> [stderr] 
> 1:
> [stderr] 
> Task failed with an exception.
> [stderr] 
> -----------
> [stderr] 
> * What went wrong:
> [stderr] 
> A problem was found with the configuration of task ':app:createBundleReleaseJsAndAssets' (type 'BundleHermesCTask').
> [stderr] 
> - In plugin 'com.facebook.react' type 'com.facebook.react.tasks.BundleHermesCTask' property 'entryFile' specifies file '/home/expo/workingdir/build/********' which doesn't exist.
> [stderr] 
> Reason: An input file was expected to be present but it doesn't exist.
> [stderr] 
> Possible solutions:
> [stderr] 
> 1. Make sure the file exists before the task is called.
> [stderr] 
> 2. Make sure that the task which produces the file is declared as an input.
> [stderr] 
> Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
> [stderr] 
> * Try:
> [stderr] 
> > Run with --stacktrace
> [stderr] 
> option to get the stack trace.
> [stderr] 
> > Run with --info or --debug option to get more log output.
> [stderr] 
> > Run with --scan to get full insights.
> [stderr] 
> ==============================================================================
> [stderr] 
> 2: Task failed with an exception.
> [stderr] 
> -----------
> [stderr] 
> * What went wrong:
> [stderr] 
> java.lang.StackOverflowError (no error message)
> [stderr] 
> * Try:
> [stderr] 
> > Run with --stacktrace option to get the stack trace.
> [stderr] 
> > Run with --info or --debug option to get more log output.
> [stderr] 
> > Run with --scan to get full insights.
> [stderr] 
> ==============================================================================
> [stderr] 
> * Get more help at https://help.gradle.org
> [stderr] 
> BUILD FAILED in 4m 19s
> 196 actionable tasks: 196 executed
> ```

Just remove the dependencies expo-updates EAS and it will work

**Comment by 1623311678** [comment]
> > Change your index.ts to index.js. Agree this is a bug though, the default install should work by default.
> 
> Isn't that a problem for expo-updates? I saw this error 'Execution failed for task ': expo - updates: createReleaseExpoManifest'. Of course, I also encountered this problem, using expo SDK48 and expo-updates@0.16

<img width="668" alt="image" src="https://github.com/expo/expo/assets/41052302/8945f757-049c-4623-a4d2-ddc3fc9cbec2">

I changed index.ts to index.js, and now it can be compiled by EAS, thank you very much

**Comment by Nanfack-Takoutsi-Yvan** [comment]
> <img alt="image" width="668" src="https://user-images.githubusercontent.com/41052302/248503844-8945f757-049c-4623-a4d2-ddc3fc9cbec2.png">
> I changed index.ts to index.js, and now it can be compiled by EAS, thank you very much

Glad it solved your problem. But I still can't build the project for android.

**Comment by lucksp** [comment]
Issue here is that when I change to `index.js`, then the iOS build fails because 

> Error: Unable to resolve module ./index.ts from /Users/lucksp/dev/myflyid/.: 

None of these files exist:
  * index.ts(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * index.ts/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/Users/lucksp/dev/myflyid/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (/Users/lucksp/dev/myflyid/node_modules/metro/src/node-haste/DependencyGraph.js:271:43)
    at /Users/lucksp/dev/myflyid/node_modules/metro/src/lib/transformHelpers.js:171:21
    at Server._resolveRelativePath (/Users/lucksp/dev/myflyid/node_modules/metro/src/Server.js:1132:12)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/lucksp/dev/myflyid/node_modules/metro/src/Server.js:448:37)
    at async Server._processRequest (/Users/lucksp/dev/myflyid/node_modules/metro/src/Server.js:381:9)
› Stopped server

**Comment by Oladapodaniel** [comment]
> > <img alt="image" width="668" src="https://user-images.githubusercontent.com/41052302/248503844-8945f757-049c-4623-a4d2-ddc3fc9cbec2.png">
> > I changed index.ts to index.js, and now it can be compiled by EAS, thank you very much
> 
> Glad it solved your problem. But I still can't build the project for android.



> > > Change your index.ts to index.js. Agree this is a bug though, the default install should work by default.
> > 
> > 
> > Isn't that a problem for expo-updates? I saw this error 'Execution failed for task ': expo - updates: createReleaseExpoManifest'. Of course, I also encountered this problem, using expo SDK48 and expo-updates@0.16
> 
> <img alt="image" width="668" src="https://private-user-images.githubusercontent.com/41052302/248503844-8945f757-049c-4623-a4d2-ddc3fc9cbec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjMwNDQsIm5iZiI6MTcwNjc2Mjc0NCwicGF0aCI6Ii80MTA1MjMwMi8yNDg1MDM4NDQtODk0NWY3NTctMDQ5Yy00NjIzLWE0ZDItZGRjM2ZjOWNiZWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA0NDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZWZmNDM3OTQ3YzA0ZDVhNjI4NThhOTU2NDhkZmVmMDdjOWIyZmVlZTFkOGYwZWMzODY5MzIwMWNmYmNjMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6SWUa-xMQG_FcT_CSsUT_8XwfolLuXl0yZWdxvRNm7k">
> I changed index.ts to index.js, and now it can be compiled by EAS, thank you very much

this worked but since i just have in my index.js
import "expo-router/entry";

how do i wrap the whole app with redux provider from here?
