### ISSUE TITLE
Just Ejected and I can't build ios even after running pod install

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo#2275]
<img width="279" alt="screen shot 2018-09-22 at 8 40 58 pm" src="https://user-images.githubusercontent.com/31741411/45923931-fab85380-bea7-11e8-9b52-6ae6da921da4.png">

**Comment by ChronSyn** [comment]
Why have you made almost 30 tickets to discuss the same issue?

**Comment by ide** [comment]
Closing all of these issues. Please create one GitHub issue per issue you encounter and use the GitHub website if you're using software that led to creating dozens of issues.
