### ISSUE TITLE
 Expo prebuild command hangs with the message "Attempting to install CocoaPods CLI with Gem,"

### ISSUE THREAD

**Issue by josiaharkson** [expo/expo#22758]
### Summary

Please when I run the comand `sudo npx expo prebuild --clean` on my Macbook 
The following error appear on my command line, and exits

``` 
$ sudo npx expo prebuild --clean

Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard
✔ Cleared android, ios code
✔ Created native projects | gitignore skipped
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using Yarn
✔ Config synced
  CocoaPods CLI not found in your PATH, installing it now.
› Attempting to install CocoaPods CLI with Gem
Successfully installed cocoapods-1.12.1
1 gem installed
› Successfully installed CocoaPods CLI with Gem
✔ Installed CocoaPods CLI.
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache        Manipulate the CocoaPods cache
    + env          Display pod environment
    + init         Generate a Podfile for the current directory
    + install      Install project dependencies according to versions from a
                   Podfile.lock
    + ipc          Inter-process communication
    + lib          Develop pods
    + list         List pods
    + outdated     Show outdated project dependencies
    + repo         Manage spec-repositories
    + setup        Set up the CocoaPods environment
    + spec         Manage pod specs
    + update       Update outdated project dependencies and create new Podfile.lock

Options:

    --allow-root   Allows CocoaPods to run as root
    --silent       Show nothing
    --version      Show the version of the tool
    --verbose      Show more debugging information
    --no-ansi      Show output without ANSI codes
    --help         Show help banner of specified command
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:102:in `ensure_not_root_or_allowed!'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:48:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
``` 

### What platform(s) does this occur on?

Android, iOS

### SDK Version

~47.0.14

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.14 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      expo-cli: 6.3.7
    Expo Workflow: bare

### Minimal reproducible example

Please  run the comand `sudo npx expo prebuild --clean`

**Comment by FranklysG** [comment]
same error

**Comment by foaudkajj** [comment]
+1

**Comment by Andreibv** [comment]
+2

**Comment by FranklysG** [comment]
THIS WORK FOR ME

Aparentemente consegui resolver, dando as permissões de leitura e gravação para toda a pasta do projeto react-native com expo

Antes disso, verifique se o vc consegue chamar o pod --version no terminal 

<img width="297" alt="image" src="https://github.com/user-attachments/assets/6e511a6d-2edd-4430-b6e1-b08e821c07d3" />

Agora siga os passos

1 - delete ./ios
2 - Tutorial das imagens
3 - npx expo prebuild
4 - npx expo run:ios

2 (Tutorial das imagens)

 ### Clique com direito na pasta e depois em obeter informações
 
<img width="325" alt="Captura de Tela 2024-12-27 às 16 10 47" src="https://github.com/user-attachments/assets/7011c3fb-1a52-4ba6-be88-902b4228615e" />

### Mude as configurações para leitura e gravação de todos os usuarios

<img width="272" alt="Captura de Tela 2024-12-27 às 16 11 37" src="https://github.com/user-attachments/assets/1cf4c668-9a87-4172-a046-1bff8f388ebe" />

### Agora aplique em todas as pastas de dentro do seu projeto

<img width="277" alt="Captura de Tela 2024-12-27 às 16 12 38" src="https://github.com/user-attachments/assets/37599d61-0745-45b3-aac7-361f357080aa" />
