### ISSUE TITLE
Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.

### ISSUE THREAD

**Issue by EsyAwesome** [expo/expo#2276]
Hi, I'm using expo XDE and have this issue - 
Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.

I press on the link, but dont know what to do.
Can anyone please tell what to do to in order to solve this problem ?
Thanks

**Comment by tsapeta** [comment]
Hi @EsyAwesome,
Can you post the content of your `package.json` file? `react-native` dependency should look like:
```
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"
```
Where `30.0.0` is the version of Expo SDK you'd like to use.

**Comment by EsyAwesome** [comment]
Hi, @tsapeta  and here is the content of my `package.jason` :

`{
  "name": "Mates",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.14.0",
    "jest-expo": "~27.0.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-navigation": "^2.0.4"
  }
}
`
Do I need to stay on top of eny new release of:  "https://github.com/expo/react-native/archive/sdk-new version' "   ?
Thanks
Elad

**Comment by tsapeta** [comment]
Yeah, you need to use Expo fork of React Native for SDK27. So use this in your dependencies:
```
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz"
```
