### ISSUE TITLE
Tried to register two views with the same name exponent camera

### ISSUE THREAD

**Issue by Biplovkumar** [expo/expo#2277]
### Attention

Tried to register two views with the same name exponent camera
  
### Environment

App.json : -  

{
  "expo": {
    "name": "xxxxxxxxxxxxx",
    "description": "xxxxxxxxxxxxx",
    "slug": "xxxxxxxxxxxxx",
    "privacy": "public",
    "sdkVersion": "28.0.0",
    "version": "1.0.0",

    "ios": {
      "bundleIdentifier": "xxxxxxxxxxxxx",
      "buildNumber": "1.0.0",
      "icon": "./assets/icons/icon_ios.png",
      "splash": {
        "image": "./assets/icons/loading.png",
        "resizeMode": "cover",
        "backgroundColor": "#8EBDB3"
      },
      "isTabletOnly": false,
      "supportsTablet": true
    },
    "android": {
      "package": "xxxxxxxxxxxxx",
      "versionCode": 1,
      "icon": "./assets/icons/icon.png",
      "splash": {
        "resizeMode": "cover",
        "ldpi": "./assets/icons/loading.png",
        "mdpi": "./assets/icons/loading.png",
        "hdpi": "./assets/icons/loading.png",
        "xhdpi": "./assets/icons/loading.png",
        "xxhdpi": "./assets/icons/loading.png",
        "xxxhdpi": "./assets/icons/loading.png",
        "backgroundColor": "#8EBDB3"
      }
    
    },
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/icon_ios.png",
    "splash": {
      "image": "./assets/icons/loading.png",
      "resizeMode": "cover",
      "backgroundColor": "#8EBDB3"
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4"
      ],
      "config": "rn-cli.config.js"
    }
  }
}

Package.json File:-  

{
  "name": "xxxxxxxxxxxxx",
  "version": "1.0.0",
  "description": "xxxxxxxxxxxxx",
  "author": "Biplov Kumar",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "@expo/vector-icons": "6.3.0",
    "@expo/videoplayer": "^0.4.0",
    "axios": "^0.18.0",
    "expo": "^28.0.0",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "radio-button-react-native": "^1.1.6",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-circular-progress": "^1.0.1",
    "react-native-countdown-component": "^1.7.3",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-snap-carousel": "^3.7.4",
    "react-navigation": "^2.16.0"
  },
  "scripts": {
    "postinstall": "git submodule update",
    "clean-install": "rm -rf node_modules && npm cache clean --force && watchman watch-del-all && npm install"
  }
}

### Steps to Reproduce

(Write your steps here:)

1. when i run my app with Expo start  Always  Shown this error 
2. when i reload my app then some times it loading and some times it doesn't
3. from updatin my sdk 27 to 28.0.0

### Expected Behavior

Work Properly

### Actual Behavior

![img-0576](https://user-images.githubusercontent.com/30401136/45932809-dcce1a00-bf9f-11e8-8fb4-7e71fba906d5.PNG)

(Write what happened. Add screenshots!)

Thanks for helping me.!

**Comment by Biplovkumar** [comment]
App.js File :- 

`
import React from 'react';
import Expo, { AppLoading, Asset, Font, Icon } from 'expo';
import { Platform, StatusBar, StyleSheet, View, Image, Dimensions } from 'react-native';
import AppNavigator from './src/navigation/AppNavigator';



export default class AppContainer extends React.Component {
  state = {
    isLoadingComplete: false,
  };

  render() {
    console.disableYellowBox = ["Unable to symbolicate"];

    if (!this.state.isLoadingComplete) {
      return (
        <AppLoading
          startAsync={this._loadResourcesAsync}
          onError={this._handleLoadingError}
          onFinish={this._handleFinishLoading}
        />
      );
    } else {
      return (
        <View style={styles.container}>
          {Platform.OS === 'ios' && <StatusBar barStyle="default" />}
          <AppNavigator />
        </View>
      );
    }
  }



  _loadResourcesAsync = async () => {
    return Promise.all([
      Asset.loadAsync([
        require('./assets/images/bg_screen1.jpg')
      ]),
      Font.loadAsync({
        // This is the font that we are using for our tab bar
        ...Icon.Ionicons.font,
        // We include SpaceMono because we use it in HomeScreen.js. Feel free
        // to remove this if you are not using it in your app
        'light': require('./assets/fonts/Lato-Light.ttf'),
      }),
    ]);
  };


  _handleLoadingError = error => {
    // In this case, you might want to report the error to your error
    // reporting service, for example Sentry
    console.warn(error);
  };

  _handleFinishLoading = () => {
    this.setState({ isLoadingComplete: true });
  };


}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
});

Expo.registerRootComponent(AppContainer);
`

**Comment by ide** [comment]
The error message needs to be clearer but concurrent cameras are not supported.

**Comment by Biplovkumar** [comment]
What is the solution ?

**Comment by ide** [comment]
You cannot have two cameras on the screen at the same time. The solution depends on your app and you may need to debug further to ensure you meet that constraint.
