### ISSUE TITLE
Confusing message when port is in use on Windows

### ISSUE THREAD

**Issue by loganrosen** [expo/expo#22774]
### Summary

When running Expo on Windows (via PowerShell), if the default port (8081) is in use, the message is confusing:

```
PS C:\Users\logan\social-app> yarn android
yarn run v1.22.19
$ expo run:android
› Port 8081 is
× Use port 8082 instead? ... yes
```

Port 8081 is...what? 😄 Based on the code, it's in use, but that's not clear from the message. It looks like this is happening because it's failing to find the process that's listening on that port, as [the underlying code](https://github.com/expo/expo/blob/b0b41037be7bd8bb2a0171a32dc93b5686f0f26e/packages/%40expo/cli/src/utils/getRunningProcess.ts#L12) calls `lsof`, which is not available in PowerShell.

So I think there are two things here:
1. The message should end with something generic like "in use" if it can't find the running process.
2. The running process logic should ideally be adjusted to work on Windows as well.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.0
      expo: ~48.0.18 => 48.0.18
      react: 18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ^0.18.11 => 0.18.12
    Expo Workflow: bare

### Minimal reproducible example

1. Run `npx expo run:android` on an existing Expo project, in PowerShell on Windows.
2. Run it again in another window.
3. Observe the error message.

**Comment by Johnrobmiller** [comment]
Port 8081 **_is_**. it truly is.
