### ISSUE TITLE
Android azure ad redirectUri bare workflow not working

### ISSUE THREAD

**Issue by davfront22** [expo/expo#22779]
### Summary

To provide context, I am integrating Azure AD into our Android application for authentication purposes. However, I have run into an issue with the post-authentication redirection process. The application should return to its previous state after a successful authentication, but it isn't performing as expected.

The configuration appears correct, with the intent-filter correctly defined for the appropriate activity in the AndroidManifest.xml and the corresponding scheme set in the React Native app.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.8
    Expo Workflow: bare

### Reproducible demo

https://github.com/DanielRiv2024/Test

**Comment by MarcinNowak-codes** [comment]
I'm not using `expo-auth-session` but have OAuth2 flow in application. In my opinion the redirect url in your code should be something like: `test://example.com/` based on you `app.json`

**Comment by anhkieet** [comment]
@davfront22 have you solved this issue? I am having this issue too

**Comment by reboottime** [comment]
I'm having the same issue
