### ISSUE TITLE
How to close or reconnect SQlite ?

### ISSUE THREAD

**Issue by timeturnback** [expo/expo#2278]
I have this code to check that the database is exsist or not , and check the version of the database so I can load the new version of db .

```
export function getDatabase()
{
	return SQLite.openDatabase(c.APP_DATABASE_LOCAL_NAME);
}

export function checkDatabase(callback)
{
	database = getDatabase();
	console.log(database);
	database.transaction(
      	tx => {
	        tx.executeSql('select Version from INFO', 
	        	[], 
	        	(_, { rows }) =>{
	          		let versiondata = rows._array[0];
	          		if (versiondata.Version !== c.APP_DATA_VERSION) 
	          			{
	        				console.log("wrong version download");
	          				downloadDatabase(callback);
	          			} else callback(true);
	          		},
	        	(_,error) => {
	        		console.log("no database download");
	        		downloadDatabase(callback);
	        		});
		    },
		    null,
		    null
    );
}
export function downloadDatabase(callback)
{
	FileSystem.downloadAsync(
	  Asset.fromModule(require('../../assets/data/database.db')).uri,
	  FileSystem.documentDirectory + 'SQLite/' + c.APP_DATABASE_LOCAL_NAME
	)
	  .then(({ uri }) => {
	    console.log('Finished downloading to ', uri);
	    callback(true);
	  })
	  .catch(error => {
	    console.error(error);
	  });
}
```

The problems is when I download the database , the new database replace the database.db file but somehow , the connection is still connect to the old database . every query to the db return error as no table is on that connecting database . Is there some how I can close , or reconnect the database . Thank

**Comment by esamelson** [comment]
Hi @timeturnback - have you tried `database.close()`? I'm not sure why this isn't documented 🤔 but you can see it in the source code here: https://github.com/expo/expo/blob/f680127237fef701a55d99053335034bdbf15ae9/packages/expo/src/SQLite.ts#L45

**Comment by timeturnback** [comment]
I've try 
```
db = SQLite.openDatabase(c.APP_DATABASE_LOCAL_NAME);
db.close();
```

it return 
[Unhandled promise rejection: TypeError: db.close is not a function. (In 'db.close()', 'db.close' is undefined)]

**Comment by timeturnback** [comment]
Yes , thank for review . I figure my way out of this problems . I just want to report for the dev team for the improvement

**Comment by esamelson** [comment]
@zocheyado no one is currently working on this, but we'd be happy to accept a PR adding this functionality!

**Comment by ZackLeonardo** [comment]
+1

**Comment by timeturnback** [comment]
pls review this issue cause we usually use 2 database : read and write

**Comment by blankonn** [comment]
apparently, the function is already there, but it is not really accessible.. try this :
```
const db = SQLite.openDatabase('test.db');
db._db.close();
```

**Comment by FiberJW** [comment]
This seems to be resolved, so I’ll close this for now. If you notice any related bugs in the future, please open a new issue :)

**Comment by esamelson** [comment]
actually, this is still a feature we don't currently support in the SQLite module. We have no timeline for adding it in the future, but I'm going to keep this open so we can track it.

**Comment by jph98** [comment]
I have exactly this issue at the moment, but it only happens on first install of the app, close and re-run fixes the issue.  Looking at the database connection when this is affected it appears that the database exists, but there are zero tables present and it's unusable when I first issue a connection to the client:

```
return SQLite.openDatabase('loq.db');
```

Initialisation code is as follows:

```
try {            
            await this.checkDirectoryExists();
            const dbInfo = await FileSystem.getInfoAsync(LOCAL_SQLITE_DB, {
                intermediate: true    
            });            
            console.log(dbInfo);
            if (!dbInfo['exists']) {
                if (DEBUG) console.log(`Creating DB at path: ${LOCAL_SQLITE_DB}`);
                const sourceDbUri = Asset.fromModule(SOURCE_DB_ASSET).uri;
                if (DEBUG) console.log(sourceDbUri)
                await FileSystem.downloadAsync(sourceDbUri, LOCAL_SQLITE_DB);
                if (DEBUG) console.log(`Done downloading DB`);
                const dbInfo = await FileSystem.getInfoAsync(LOCAL_SQLITE_DB, {
                    intermediate: true    
                });            
                console.log(dbInfo);
                this.getNumberOfTables();
            } else {
                console.log(`Using DB found at: ${LOCAL_SQLITE_DB}`);
            }

          } catch (e) {            
            console.log(e);
          } 
```

Does anyone have a workaround for this?

**Comment by allandiego** [comment]
Im facing a similar issue using  expo-sqlite driver with typeorm, when i try to restore the downloaded backup file i get this error:
(1032) SQLITE_READONLY_DBMOVED
https://www.sqlite.org/rescode.html#readonly_dbmoved

to restore i do the following:
1 - close connection await getConnection().close();
2 - rename original database file
3 - rename the backup file to the original database file name 
all files are in FileSystem.documentDirectory + 'SQLite/'
4 - open connection

when i try to make a database insert delete etc i get the error (1032) SQLITE_READONLY_DBMOVED, i think the driver somehow is holding the database file because selects still point to renamed original database file.
Or maybe something related with the MY_DATABASE-journal file that I saw being created  in FileSystem.documentDirectory + 'SQLite/' when the database is open

https://www.sqlite.org/tempfiles.html

**Comment by Stophface** [comment]
> apparently, the function is already there, but it is not really accessible.. try this :
> 
> ```
> const db = SQLite.openDatabase('test.db');
> db._db.close();
> ```

That is not working.

**Comment by staghouse** [comment]
Any update on this?

**Comment by trajano** [comment]
Though in the normal course of using my app I don't need the .close() but when the app gets reloaded in Expo Go sometimes the database does not get freed up and so it makes the app hang on some reloads

**Comment by Gustl22** [comment]
A workaround is to access the private attribute [`_db` of `WebSQLDatabase`](https://github.com/nolanlawson/node-websql/blob/cba15f9d0574614f9c39063794bf651a27660d9c/lib/websql/WebSQLDatabase.js#L27)  from the `@expo/websql` package and close it with [the provided method](https://github.com/expo/expo/blob/f680127237fef701a55d99053335034bdbf15ae9/packages/expo/src/SQLite.ts#L45):

```
const database: SQLite.WebSQLDatabase = SQLite.openDatabase(MY_DATABASE_NAME);

// @ts-ignore
database._db.close();
```

**Comment by staghouse** [comment]
This is still an issue

**Comment by Gustl22** [comment]
Agreeing, still an issue

**Comment by gabacode** [comment]
> A workaround is to access the private attribute [`_db` of `WebSQLDatabase`](https://github.com/nolanlawson/node-websql/blob/cba15f9d0574614f9c39063794bf651a27660d9c/lib/websql/WebSQLDatabase.js#L27) from the `@expo/websql` package and close it with [the provided method](https://github.com/expo/expo/blob/f680127237fef701a55d99053335034bdbf15ae9/packages/expo/src/SQLite.ts#L45):
> 
> ```
> const database: SQLite.WebSQLDatabase = SQLite.openDatabase(MY_DATABASE_NAME);
> 
> // @ts-ignore
> database._db.close();
> ```

while the workaround is great it would be awesome to have a proper method to do this that is ts friendly

**Comment by trajano** [comment]
it's not "friendly" but you can always use the fallback by doing `(database as any).close()`

**Comment by AlenToma** [comment]
Try my new library [expo-sqlite-wrapper](https://www.npmjs.com/package/expo-sqlite-wrapper) added support to close and many other feature. check it out. 

This library is a wrapper around expo sqlite so there will not be many changes to your code.

**Comment by Darshan-leocan** [comment]
> I've try
> 
> ```
> db = SQLite.openDatabase(c.APP_DATABASE_LOCAL_NAME);
> db.close();
> ```
> 
> it return [Unhandled promise rejection: TypeError: db.close is not a function. (In 'db.close()', 'db.close' is undefined)]

> define let db; before use bd.
