### ISSUE TITLE
app.config.ts losing environment variable configuration on standalone app

### ISSUE THREAD

**Issue by Overdash** [expo/expo#22784]
### Minimal reproducible example

https://snack.expo.dev/@prodeej/config-env-bug

### Summary

(To see the bug you'll need to create a standalone binary on any platform)

I'll try to be as accurate as possible.
I'm using both `app.json` and `app.config.ts`. `app.json` mainly has production level configurations, of which are overridden in `app.config.ts` if the environment is not production. (Please check code snippets below)

When I build an APK for internal testing via the `preview` track (`BUILD_ENV` is expected to be set to staging) the APK works as expected.

However. when I build an .aab via the `production` track where `BUILD_ENV` is expected to be production, the App (downloaded from the app store) starts off correctly in production, but after restarting, the app is relegated to its staging configuration!
The same thing happens with an .apk built for production and TestFlight binaries.

After some testing, it seems the `process.env.BUILD_ENV` is lost and become `undentified` after the restart!

I've checked the `Spin up build environment` stage build logs and everything looks ok... 
```
...

Project environment variables:
  BUILD_ENV=production
...
```

Any help on this? I've ran out of ideas :( . 

Example code:

app.config.ts
```
if (process.env.BUILD_ENV === 'production') {
    // PROD config - most fields in app.json should be configured PROD ready
    return {
      ...config,
      slug: "app",
      name: "App",
      extra: <AppVars> {
        ...config.extra,
        ENV_TAG: "production",
        ...
      }
    };
  } else {
    // Staging/Remote DEV config (i.e. TestFlight)
    // change bundle/package name to allow us to install different variants of the app on the same device
    // https://docs.expo.dev/build-reference/variants/
    return <ExpoConfig> {
      ...config,
      name: "App (Staging)",
      ios: {
        ...config.ios,
        bundleIdentifier: "com.app.dev",
      },
      android: {
        ...config.android,
        googleServicesFile: "./google-services.dev.json",
        package: "com.app.dev",
      },
      extra: <AppVars> {
        ...config.extra, 
      ENV_TAG: "staging",
      ...
      }
    }
  }
```

eas.json
```
"build": {
    "development": {
      "distribution": "internal",
      "channel": "development",
      "android": {
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "buildConfiguration": "Debug"
      },
      "env": {
        "BUILD_ENV": "dev"
      }
    },
    "preview": {
      "channel": "staging",
      "distribution": "internal",
      "env": {
        "BUILD_ENV": "staging"
      }
    },
    "production": {
      "channel": "production",
      "autoIncrement": true,
      "env": {
        "BUILD_ENV": "production"
      }
    }
  },
```

P.S. changing the order of the If-statement just inverses the problem where the `staging` apk get's production configurations.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 18.12.1 - P:\Programs\nodejs\node.EXE   
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - P:\Programs\nodejs\npm.CMD      
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.4       
      expo: ^48.0.5 => 48.0.19
      react: ~18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
      react-native-web: ^0.18.7 => 0.18.10
    Expo Workflow: managed
```

**Comment by jamesjohnoliver** [comment]
Can you access your BUILD_ENV variable through the expo-constants package?
https://docs.expo.dev/versions/latest/config/app/#extra
"Values are accessible via Constants.expoConfig.extra"

**Comment by thoth-seshat** [comment]
I've also noticed that expo env aren't showing up here

**Comment by wahidshadab** [comment]
+1
