### ISSUE TITLE
`expo-av` doesn't start in web-mode in `solito` and `turbo` wrappers

### ISSUE THREAD

**Issue by scarych** [expo/expo#22808]
### Minimal reproducible example

https://github.com/scarych/expo-av-solito-bug

### Summary

When using the expo-av package in the solito and turbo wrappers for a web application, an error is generated during the dependency import process. The error appears as follows:
```
error - ../../node_modules/@react-native/assets/registry.js
Module parse failed: Unexpected token (13:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
|
> export type PackagerAsset = {
|   +__packager_asset: boolean,
|   +fileSystemLocation: string,

Import trace for requested module:
../../node_modules/@react-native/assets/registry.js
../../node_modules/react-native/Libraries/Image/AssetRegistry.js
../../node_modules/expo-asset/build/Asset.js
../../node_modules/expo-asset/build/index.js
../../node_modules/expo-av/build/AV.js
../../node_modules/expo-av/build/Audio.js
../../node_modules/expo-av/build/index.js
../../packages/app/features/useJingleSound.ts
../../packages/app/features/home/screen.tsx
```
This issue prevents the `expo-av` package from running properly in the `web` mode of the `solito` and `turbo` wrappers.

To reproduce the issue, use the following code in the `useJingleHook.tsx` file:
```ts
import { Audio } from 'expo-av'
import { useEffect, useRef } from 'react'

export const useJingleSound = () => {
  const jingleSound = useRef<Audio.Sound | undefined>(undefined)

  useEffect(() => {
    ;(async () => {
      jingleSound.current = (
        await Audio.Sound.createAsync(
          {
            uri: 'https://scarych-test.storage.yandexcloud.net/2023/03/21/6419d95d0a6eb6a996d55e2e-night.mp3',
          },
          { volume: 0.5 }
        )
      ).sound
    })()
  }, [])

  return { jingleSound }
}
```
To play the sound, use the following code:

```ts
import { useJingleSound } from './useJingleHook.tsx';

export function PlaySound() {
  const { jingleSound } = useJingleSound()
  const playJingle = () => {
    jingleSound.current?.replayAsync()
  }

  return (<Button onPress={playJingle} title="Play"/>);
}
```
It is recommended to investigate and resolve this issue so that the expo-av package can be used successfully in the web mode of the solito and turbo wrappers.

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 3.4.1 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 18, 19, 26, 27, 28, 29
        Build Tools: 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    Expo Workflow: managed
```

**Comment by kalmndo** [comment]
Hi i'm encountered this issue last week, how about to solve recording on the web?

**Comment by kalmndo** [comment]
I was encountered this issue last week

my solution is change the node_modules/@react-native/assets with patch-package

> ```diff
> diff --git a/node_modules/@react-native/assets/registry.js b/node_modules/@react-native/assets/registry.js
> index 088187f..0a384d1 100644
> --- a/node_modules/@react-native/assets/registry.js
> +++ b/node_modules/@react-native/assets/registry.js
> @@ -10,28 +10,16 @@
>  
>  'use strict';
>   
> -export type PackagerAsset = {
> -  +__packager_asset: boolean,
> -  +fileSystemLocation: string,
> -  +httpServerLocation: string,
> -  +width: ?number,
> -  +height: ?number,
> -  +scales: Array<number>,
> -  +hash: string,
> -  +name: string,
> -  +type: string,
> -  ...
> -};
>  
> -const assets: Array<PackagerAsset> = [];
> +const assets = [];
>  
> -function registerAsset(asset: PackagerAsset): number {
> +function registerAsset(asset) {
>    // `push` returns new array length, so the first asset will
>    // get id 1 (not 0) to make the value truthy
>    return assets.push(asset);
>  }
>  
> -function getAssetByID(assetId: number): PackagerAsset {
> +function getAssetByID(assetId) {
>    return assets[assetId - 1];
>  }
>  
> ```

and add this to next.config.js transpilePackages

```
'@react-native/assets',
'expo-modules-core',
'expo-asset',
'expo-av',
```

**Comment by JWesorick** [comment]
I am also experiencing this issue.

**Comment by sourabhLX** [comment]
same hear any Update's ?? 
@kalmndo if you have time can you give some steps toward your version  of the fix.

**Comment by joseito-fernandes** [comment]
i am also facing this same issue

**Comment by joseito-fernandes** [comment]
Why does the js file even have ts type declarations/annotations?

**Comment by timohe** [comment]
For future reference, if someone has the same issue: For me the solution above worked. If you use yarn you can patch with `yarn patch @react-native/assets-registry`, you might need to add @react-native/assets-registry first manually as a dev-dependency for it to work.

**Comment by stounej** [comment]
@timohe can you please tell me  how to add @react-native/assets-registry first manually as a dev-dependency

**Comment by karim-attia** [comment]
> @timohe can you please tell me how to add @react-native/assets-registry first manually as a dev-dependency

   yarn add @react-native/assets-registry --dev
