### ISSUE TITLE
Ejected from an Expo App (mid project) Cannot compile due to semantic issue thrown

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo#2280]
Hi guys,

I had to eject from expo due to no FS module for expo. Sadly my project is now unusable.

I cannot even build the project when I'm in xcode 9/10beta. I did a pod install and a pod update and the project is still throwing a **semantic error** how do I fix this?

![screen shot 2018-09-24 at 12 35 45 am](https://user-images.githubusercontent.com/31741411/45941279-40e9e180-bf92-11e8-8045-eb6639289d82.png)

**Comment by esamelson** [comment]
Hi @FrederickEngelhardt - could you look in your `ios/Podfile.lock` and see which version of `FBAudienceNetwork` is installed? If it's `4.99.1`, try changing it to `4.28.1` and rerun `pod install`.
