### ISSUE TITLE
EAS Update publishing unversioned web bundle

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo#22803]
### Minimal reproducible example

N/A

### Summary

When publishing OTA updates with `eas update`, I've noticed that two separate bundles are uploaded: one versioned bundle for iOS & Android, and one unversioned bundle for web. Is this the expected behavior? Why should the web bundle be published at all?

Terminal output when running `eas update`:
```
philiplindberg@Philips-MBP trustlabs % eas update
✔ Which branch would you like to use? › preview - current update: "Add sponsor banner to home screen" (36 minutes ago by philiplindberg)
✔ Provide an update message: … Add sponsor banner to home screen
[expo-cli] Starting Metro Bundler
[expo-cli]
[expo-cli] iOS Bundling complete 13505ms
[expo-cli] Web Bundling complete 31324ms
[expo-cli]
[expo-cli] Android Bundling complete 31428m
...
[expo-cli] Export was successful. Your exported files can be found in dist
✔ Exported bundle(s)
✔ Uploaded 3 app bundles
✔ Uploading assets skipped - no new assets found
✔ Channel: preview pointed at branch: preview
✔ Published!

👉 Since multiple runtime versions are defined, multiple update groups have been published.

Branch             preview
Runtime version    1.0.0
Platform           android, ios
Update group ID    08014d8e-dfba-4427-9a51-ba668b381c31
Android update ID  91ae0d70-13f7-420f-9a5c-7dcfec61f8c5
iOS update ID      eb457bce-0480-459f-aefa-8e665caabddb
Message            Add sponsor banner to home screen
Commit             e06ca54838d4cac8ac10aaccdafdb6745b00cca7
Website link       https://expo.dev/accounts/trusthealth/projects/trustlabs/updates/08014d8e-dfba-4427-9a51-ba668b381c31

Branch           preview
Runtime version  UNVERSIONED
Platform         web
Update group ID  8d8d71ea-7e4a-4707-ae57-0a273dad53d3
Message          Add sponsor banner to home screen
Commit           e06ca54838d4cac8ac10aaccdafdb6745b00cca7
Website link     https://expo.dev/accounts/trusthealth/projects/trustlabs/updates/8d8d71ea-7e4a-4707-ae57-0a273dad53d3
```

Screenshot of published updates in my Expo Console:

<img width="1242" alt="CleanShot 2023-06-08 at 15 50 10@2x" src="https://github.com/expo/expo/assets/1865904/1d9197dd-c8d5-4910-9219-cdbb1df6d7f6">

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
      Yarn: 3.5.1 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    Expo Workflow: bare

**Comment by orbiteleven** [comment]
There seems to be no obvious way to limit `eas update` to a runtime version.
