### ISSUE TITLE
Cannot run application after eject

### ISSUE THREAD

**Issue by ronce96** [expo/expo#2281]
## Description
After running `npm run eject` de android project cannot resolve ReactApplication and ReactNativeHost and it does not compile.

## Expected Behavior
I can compile the android project generated by `npm run eject` and execute it in the androi emulator

## Observed Behavior
The project has some errors in the imports, like ReactApplication or ReactNativeHost. The MainActivity does not implement the method `getUseDeveloperSupport()` that is required as it extends `ReactActivity`

## Environment

* `npm ls react-native-scripts`: empty
* `npm ls react-native`: react-native@0.55.4
* `npm ls expo`: empty
* `node -v`: v8.11.3
* `npm -v`: 5.6.0
* `yarn --version`: 1.9.4
* `watchman version`: The term 'watchman' is not recognized as the name of a cmdlet

1. Operating system: Microsoft Windows 10 Enterprise
2. Phone/emulator/simulator & version: Android emulator, API 27, Android 8.1 (Google APIs)

## Reproducible Demo
```
$ npm install -g expo-cli
$ expo init my-app
$ cd my-app/
$ npm run eject
```
Then open Android Studio and try to compile the Android project generated after `npm eject`

**Comment by FiberJW** [comment]
Hi, we’re closing inactive issues that apply to SDK versions we no longer support. I wasn’t able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
