### ISSUE TITLE
[docs] https://docs.expo.dev/versions/latest/sdk/speech/

### ISSUE THREAD

**Issue by rjapenga** [expo/expo#22825]
### Summary

The type for rate in Text to Speech API is a number for Android and a text for IoS. Documentation says that it is a text for both.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/speech/

### Anything else?

Not sure it is a typo or a code bug. So I didn't edit the documentation.

**Comment by alanjhughes** [comment]
Hi @rjapenga - `rate` is a number on both and in the docs. Where are you seeing it as a string?
