### ISSUE TITLE
Notifications.addListener standalone app

### ISSUE THREAD

**Issue by saundefined** [expo/expo#2282]
### Environment

Environment:
  OS: macOS 10.14
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/saundefined-6dd94db2-044b-4d55-b33c-79cbff50d83a.tar.gz

Device: iPhone 7, iOS 12

### Steps to Reproduce

1. run `expo build:ios`
2. deliver via testflight
3. send push notification

### Expected Behavior

On development mode in Expo I have alert with notification object, but on standalone app I haven't it.

### Actual Behavior

On standalone app _handleNotification is not called, I try run app by clicking on notification, run the app and then push notification - there are nothing happens

I **received** that notification, but `_handleNotification` not called

### Code

```
componentDidMount() {
      this.registerForPushNotificationsAsync();
      this._notificationSubscription = Notifications.addListener(
          this._handleNotification);
    });
  }

  _handleNotification = (notification) => {
    alert(JSON.stringify(notification));
  };
```

**Comment by esamelson** [comment]
Hi @saundefined - thanks for the report. Do you know if the behavior you're seeing is exclusive to iOS 12 (e.g. did it work on a previous version of iOS)?

**Comment by saundefined** [comment]
@esamelson just now I rebuild ios bundle – all works fine
