### ISSUE TITLE
Issue opening Branch deep links on Android when the app is backgrounded

### ISSUE THREAD

**Issue by adoankim** [expo/expo#2283]
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.4
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.5.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/feeldservices-31ed2a7a-f3a6-4246-9686-0bd4219e0505.tar.gz

Target : 
 - Android
 - ExpoKit

### Steps to Reproduce

- Open the app from cold
- On the terminal with the Expo bundle server wait for the build to finish. After the build you will see:

```
Object {
  "error": null,
  "params": Object {
    "+clicked_branch_link": false,
    "+is_first_session": true,
    "+non_branch_link": "exp13f5502b39b149d8a02ab7ff5385ff98://",
    "cached_initial_event": true,
  },
  "uri": "exp13f5502b39b149d8a02ab7ff5385ff98://",
}
```

- Kill the app
- Open the link on your device browser https://feeld.github.io/ExpoBranchRepro/
- Click the test link. The app will open and you will see in the terminal with the Expo bundle server something similar to:

```
Object {
  "error": null,
  "params": Object {
    "$marketing_title": "testing",
    "$one_time_use": false,
    "+click_timestamp": 1537788372,
    "+clicked_branch_link": true,
    "+is_first_session": false,
    "+match_guaranteed": true,
    "cached_initial_event": true,
    "test-data": "1234",
    "~creation_source": 1,
    "~feature": "marketing",
    "~id": "572726388101131030",
    "~marketing": true,
    "~referring_link": "https://feeld-expo.test-app.link/testing",
  },
  "uri": "https://feeld-expo.test-app.link/testing",
}
```

- Background the app
- Open the device browser on https://feeld.github.io/ExpoBranchRepro/
- Click again on the test link
- The app will open and you will see in the terminal with the Expo bundle server:
```
Object {
  "error": null,
  "params": Object {
    "+clicked_branch_link": false,
    "+is_first_session": false,
  },
  "uri": null,
}
```

### Expected Behavior

When opening a link with the app in the background the expected outcome is (only the `+click_timestamp` and `~id` will differ):
```
Object {
  "error": null,
  "params": Object {
    "$marketing_title": "testing",
    "$one_time_use": false,
    "+click_timestamp": 1537788372,
    "+clicked_branch_link": true,
    "+is_first_session": false,
    "+match_guaranteed": true,
    "cached_initial_event": true,
    "test-data": "1234",
    "~creation_source": 1,
    "~feature": "marketing",
    "~id": "572726388101131030",
    "~marketing": true,
    "~referring_link": "https://feeld-expo.test-app.link/testing",
  },
  "uri": "https://feeld-expo.test-app.link/testing",
}
```

### Actual Behavior

But the actual outcome is:
```
Object {
  "error": null,
  "params": Object {
    "+clicked_branch_link": false,
    "+is_first_session": false,
  },
  "uri": null,
}
```

### Reproducible Demo

https://github.com/Feeld/ExpoBranchRepro

**Comment by esamelson** [comment]
Hi @adoankim - thanks for the report and the clear repro case. We'll look into this as soon as we can.

**Comment by rahamin1** [comment]
@adoankim @esamelson Hi guys. I am having issue with implementing a simple app and looking for help. Please see: https://www.upwork.com/ab/find-work/details/~014bd359c92b9d5fe4 and let me know if you can help.
My apologies for posting this here. I am under time pressure and stuck...

**Comment by Svarto** [comment]
@adoankim sorry for resurrecting this old one, but I have exactly the same issue! How did you implement that edit in the Android java? I tried changing it directly in the node_modules folder but it isn't built properly (at least not OTA), does it need a full new standalone version build to be reflected?

**Comment by Aryk** [comment]
I'm getting this issue too I believe. I'm on Managed, is it impossible to get this working on Expo Managed SDK 44?

**Comment by Aryk** [comment]
I'm getting this issue too I believe. I'm on Managed, is it impossible to get this working on Expo Managed SDK 44?

@sjchmiela is it at all possible to get this working on SDK 44 Managed?

**Comment by Svarto** [comment]
> I'm getting this issue too I believe. I'm on Managed, is it impossible to get this working on Expo Managed SDK 44?
> 
> @sjchmiela is it at all possible to get this working on SDK 44 Managed?

Do you by any chance call the branch subscribe functions within the React Navigation subscribe function? 

This + using the latest branch version through config plugins is what fixed it for me.

**Comment by Aryk** [comment]
@Svarto I'm calling it in a useEffect callback in my top-level component before the NavigationContainer, so I don't think it is in my react navigation subscribe function. 

Should I be calling it there?

I'm not using EAS yet (had too many issues getting it set up) so just continued to use expo build. 

Would it be possible to have it run if I put it inside the react navigation subscribe function?

**Comment by Svarto** [comment]
@Aryk sounds like you are doing what you can. Calling it within a useEffect has been what has worked best for me. Sorry, can't help you more on this

**Comment by Aryk** [comment]
@Svarto Can you share what you have for your intent filters in your app.json? It's possible that maybe I don't have everything there that I need.

I used to have: 

```
        {
          "action": "VIEW",
          "data": [
            {
              "scheme": "tribefy"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        },
```

 I now have:

```
        {
          "action": "VIEW",
          "data": [
            {
              "scheme": "tribefy",
              "host": "open"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        },
        {
          "autoVerify": true,
          "action": "VIEW",
          "data": [
            {
              "scheme": "https",
              "host": "join.tribefy.com"
            },
            {
              "scheme": "https",
              "host": "c8dwg-alternate.app.link"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
```

**Comment by Svarto** [comment]
@Aryk ops must have missed this. If still relevant, here is what i got for my intentFilters:

```
 
 ​      ​"intentFilters"​: [ 
 ​        { 
 ​          ​"action"​: ​"​VIEW​"​, 
 ​          ​"autoVerify"​: ​true​, 
 ​          ​"data"​: [ 
 ​            { 
 ​              ​"scheme"​: ​"​https​"​, 
 ​              ​"host"​: ​""xxx.app.link​"​, 
 ​              ​"pathPattern"​: ​"​.*​" 
 ​            } 
 ​          ], 
 ​          ​"category"​: [​"​BROWSABLE​"​, ​"​DEFAULT​"​] 
 ​        } 
 ​      ],
```
