### ISSUE TITLE
SDK 29/30 documentation page error for AR section

### ISSUE THREAD

**Issue by arthurpark** [expo/expo#2284]
### Steps to Reproduce

1. Go to https://docs.expo.io/versions/v30.0.0/sdk/AR
2. Go to https://docs.expo.io/versions/v29.0.0/sdk/AR 
3. Go to https://docs.expo.io/versions/v28.0.0/sdk/AR

### Expected Behavior

All 3 links loads.

### Actual Behavior

1. and 2. shows `An unexpected error has occured.` error message.
3. loads.

![screen shot on 2018-09-24 at 12 17 33](https://user-images.githubusercontent.com/369170/45973633-dff2f580-bff3-11e8-9ef2-1aad95a85908.png)

**Comment by jakubste** [comment]
It's working again. Kudos to @dsokal
