### ISSUE TITLE
Cannot use Reanimated 3 with expo

### ISSUE THREAD

**Issue by mbenmass** [expo/expo#22853]
### Summary

I cannot manage to make Reanimated 3 work with expo.
When I run :
`npx expo start --clear` or `expo start -c`
I get the following error :
Error: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.3.0 vs. 2.14.4). Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must downgrade to 2.14.4 which is bundled into Expo SDK., js engine: hermes

### SDK Version

48.0.18

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.05.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.3.8
    Expo Workflow: bare

### Minimal reproducible example

Here is my config :

babel.config.js
`module.exports = function (api) {
    api.cache(true);
    return {
        presets: ['babel-preset-expo'],
        plugins: [
            ...
            'react-native-reanimated/plugin',
        ]
    };
  };`

**Comment by mbenmass** [comment]
Thanks for your help.
I tried deleting node_modules, rebuild the app and started expo with the --clear argument, but I still get the same error. 
Any clue please ?

**Comment by aleqsio** [comment]
@mbenmass Expo GO supports only reanimated v2 in the current release. If you want to use v3, you need to use `npx expo run:android`, `npx expo run:ios`, `npx eas build` or `npx expo prebuild` to use Continuous Native Generation

https://docs.expo.dev/workflow/prebuild/

**Comment by wcastand** [comment]
wait i'm lost, in the issue expo workflow is bare, you try using prebuild but the solve is that you can't use v3 with Expo Go which is not bare workflow but doesn't need prebuild either. I'm lost how that is the solution to your problem x)
