### ISSUE TITLE
CLI - Expo init bad request

### ISSUE THREAD

**Issue by boldham31** [expo/expo#2285]
Every time I attempt to connect to access Expo via the CLI I receive an ECONNREFUSED error and when I open the IP Address that is listed it tells me that I made a 400 Bad Request. I have been trying to figure this out for 5 hours and I can't figure out the root of the problem. Any thoughts?
  
### Environment

![image](https://user-images.githubusercontent.com/17152030/45974397-d030dc80-c006-11e8-874c-e862b913e7b1.png)

I'm targeting Android and iOS at this point.

### Steps to Reproduce

1. expo init
2. Choose a project name: my-first-app
3. Choose a template: blank

### Expected Behavior

The CLI was supposed to access the blank project files, download them and create an app.

### Actual Behavior

I consistently receive a connection error as shown in the screenshot. I double-checked my proxy settings and everything is correct.

![image](https://user-images.githubusercontent.com/17152030/45973968-9a3f2880-c005-11e8-93f4-1b5226b07159.png)

When I navigate to that IP Address, I get a 400 Bad Request error.

![image](https://user-images.githubusercontent.com/17152030/45974034-c65aa980-c005-11e8-935a-9788d41ccd3c.png)

### Reproducible Demo

There's no code to reproduce this, as I am unable to even generate a project.

**Comment by boldham31** [comment]
After further debugging, this is not unique to the expo init command. My computer is unable to connect to expo server to get any info at all

**Comment by esamelson** [comment]
Hey @boldham31 - are you able to load https://d306o6r76fnu7o.cloudfront.net/tabs-30.1.0.tar.gz ? If not, then there is likely an issue with your proxy -- you need to be able to access our CDN in order to interact with many of our tools.

**Comment by boldham31** [comment]
@esamelson thanks for the reply. Yes, I'm able to access that link. I'm using Windows and I've tried applying the proxy settings as detailed in https://docs.expo.io/versions/latest/introduction/troubleshooting-proxies, but I'm getting bad request errors every time I try to use any command in that scenario as well. Is there anyone that can help me troubleshoot this in Windows, and then I can update the documentation for Expo to include a Windows section in the Troubleshooting Proxies page.

**Comment by esamelson** [comment]
@boldham31 could you post an issue on the https://github.com/expo/expo-cli repo instead? Feel free to link back to this one, but I think it will be easier for us to help you out from there.

**Comment by boldham31** [comment]
@esamelson will do, thanks.

**Comment by sjchmiela** [comment]
I'll close this issue in favor of https://github.com/expo/expo-cli/issues/63. 🙂
