### ISSUE TITLE
Https tunnel certificate issued to different url than expo web url

### ISSUE THREAD

**Issue by mtzfactory** [expo/expo#22860]
### Summary

When enabling the tunnel with `ngrok` and opening the url in the browser I get a warning that the certificate is not valid.

I think the errors is because the certificate is issued to `*.ngrok.io` but the tunnel url is `*.exp.direct`.

How can I fix this problem?

- Connection not secure, in Chorme
   <img width="552" alt="Screenshot 2023-06-13 at 11 55 06" src="https://github.com/expo/expo/assets/200234/1ce569ce-bf0a-46e9-9758-787691fae57d">

- Certificate details, in Chrome
   <img width="1057" alt="Screenshot 2023-06-13 at 11 55 17" src="https://github.com/expo/expo/assets/200234/4d9075bd-0a8f-45cd-ac21-9d24b85cbc52">

- Certificate details, in Safari
   <img width="486" alt="Screenshot 2023-06-13 at 11 59 26" src="https://github.com/expo/expo/assets/200234/7ee3924d-cc2c-4f88-b29d-3551e3394f60">

### What platform(s) does this occur on?

Web

### SDK Version

48.0.15

### Environment

```bash
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v20.3.0/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/rmartinez/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Minimal reproducible example

Create an example app following the instruction fro Expo Router [docs](https://expo.github.io/router/docs/)

```bash
npx create-expo-app@latest --example with-router
```

Once the example is installed, run the following command:

```bash
npm run start --clear --tunnel --https
```

This will start the expo project enabling the tunnel:

```
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
Tunnel connected.
Tunnel ready.

[QR]

› Metro waiting on exp://what-ever.anonymous.19000.exp.direct
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:19000

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Web Bundling complete 8101ms
```

Now you can press `w` or open the url `https://what-ever.anonymous.19000.exp.direct` in your browser...

**Comment by rohitverma-dev29** [comment]
I am facing a similar issue on SDK 50.0.7. The certificate URL appears to be correctly issued to *.exp.direct, but I am still receiving an invalid certificate error.

<img width="884" alt="Screenshot 2024-02-19 at 3 57 46 PM" src="https://github.com/expo/expo/assets/85377375/5701a6e0-469c-4b9e-8a68-a09a5a184119">
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-19 at 15 54 24](https://github.com/expo/expo/assets/85377375/473be46d-736b-4cb2-97d9-b638c6d95822)
