### ISSUE TITLE
ExpoKit and Firebase Invites have conflicting dependencies on GoogleSignIn versions, i.e 3.0 and 4.1 respectively.

### ISSUE THREAD

**Issue by Mozartted** [expo/expo#2287]
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10L201y
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

### Steps to Reproduce

Expokit and Firebase/Invites have conflicting dependencies on GoogleSignIn.

Google SignIn points to version 3.0 on Expo while it's pointing to 4.1 on FirebaseInvites, thus I'm unable to resolve the dependency on the Podfile.

Steps to reproduce.

1. Detach project to Expokit
2. Setup with Firebase dependencies on the podfile, these include 
- FirebaseCore
- FirebaseAuth
- FirebaseDynamicLinks ~>5.3.0
- FirebaseInvites ~> 5.3.0 
3.run pod install or pod update

### Expected Behavior
Pod installs properly and without error

### Actual Behavior

![img_0836](https://user-images.githubusercontent.com/11639772/45996654-dff70200-c094-11e8-831a-cc25babda4dc.JPG)

### Proposed Solution
Based on the nature of the issue, I presumed that updating the version of GoogleSignIn on expo would likely solve this.

**Comment by esamelson** [comment]
Hi @Mozartted - thanks for letting us know about this. We'll update this dependency for our next release.

**Comment by Mozartted** [comment]
Thanks, @esamelson, when might that be due?

**Comment by esamelson** [comment]
@Mozartted most likely in the next few weeks. You can keep an eye on our [blog](https://blog.expo.io) - we'll post there as soon as it's out.

**Comment by Mozartted** [comment]
hi @esamelson, has there been any updates no this?

**Comment by EvanBacon** [comment]
Fixed in v31

**Comment by Mozartted** [comment]
> Fixed in v31

Thanks @EvanBacon haven't been following the issue for the last few weeks.
