### ISSUE TITLE
`yarn create expo-app` leads to `spawn ENOTDIR` error when trying to start

### ISSUE THREAD

**Issue by Emperor-Koala** [expo/expo#22876]
### Summary

Not sure if this is the right place to report this, if not I'll gladly move it to the correct repository.

After using `yarn create expo-app` to create a new expo app using Yarn, attempting to run the newly created app using `yarn start` or `yarn expo start` will result in the following error: 
```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at spawn (/home/matthew/yarn-test/.yarn/unplugged/cross-spawn-npm-6.0.5-2deab6c280/node_modules/cross-spawn/index.js:12:24)
    at run (/home/matthew/yarn-test/.yarn/unplugged/expo-npm-48.0.19-3d5e78cd8e/node_modules/expo/bin/cli.js:11:12)
    at Object.<anonymous> (/home/matthew/yarn-test/.yarn/unplugged/expo-npm-48.0.19-3d5e78cd8e/node_modules/expo/bin/cli.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at require$$0.Module._extensions..js (/home/matthew/yarn-test/.pnp.cjs:21861:33)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at require$$0.Module._load (/home/matthew/yarn-test/.pnp.cjs:21680:22) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'spawn'
}

Node.js v18.16.0
```

I've been looking around online for several days trying to see if anyone else has encountered this issue, but to no avail. I've seen some other projects have had similar bug reports, but using the solutions presented there have not worked. Examples of solutions that haven't worked:
* Unplug the offending package (https://github.com/yarnpkg/berry/issues/856#issuecomment-580607912)
* Uninstalling antivirus (https://github.com/facebook/create-react-app/issues/12465#issuecomment-1203393919)
* Downgrading Node
* Using an older Expo SDK

I have also tested to confirm this error occurs on both MacOS and Ubuntu 22.04.

### SDK Version

48.0.18

### Environment

MacOS Environment:
```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 3.5.1 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    Expo Workflow: managed
```

Ubuntu 22.04 Environment:
```
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 3.6.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
```

### Minimal reproducible example

Steps: 
1. Create a new Expo project using `yarn create expo-app`
2. `cd` into the new project
3. Run `yarn start` or `yarn expo start`

**Comment by mattmcnally** [comment]
I'm also encountering this exact issue - the `create-expo-app` version being used is `2.0.3` (via `yarn create expo-app`).

**Comment by Jemeni11** [comment]
This answer doesn't even apply to me since I was using TypeScript from the get-go and I have no errors like that in my IDE.
https://github.com/expo/expo/issues/22897#issuecomment-1597911398

**Comment by mattmcnally** [comment]
Why was this closed? The issue has not yet been fixed.
