### ISSUE TITLE
Expo export throws an error

### ISSUE THREAD

**Issue by liemdo** [expo/expo#22884]
### Summary

When I run `expo export`, I get this error:

```
Processing asset bundle patterns:
- /Users/user/myapp/apps/apps/mobility/**/*
TypeError: (0 , _minimatch).default is not a function
TypeError: (0 , _minimatch).default is not a function
    at /Users/user/myapp/apps/node_modules/.pnpm/@expo+cli@0.7.3_expo-modules-autolinking@1.2.0/node_modules/@expo/cli/build/src/export/exportAssets.js:80:128
    at Array.some (<anonymous>)
    at shouldBundleAsset (/Users/user/myapp/apps/node_modules/.pnpm/@expo+cli@0.7.3_expo-modules-autolinking@1.2.0/node_modules/@expo/cli/build/src/export/exportAssets.js:80:89)
    at /Users/user/myapp/apps/node_modules/.pnpm/@expo+cli@0.7.3_expo-modules-autolinking@1.2.0/node_modules/@expo/cli/build/src/export/exportAssets.js:54:30
    at Array.map (<anonymous>)
    at resolveAssetBundlePatternsAsync (/Users/user/myapp/apps/node_modules/.pnpm/@expo+cli@0.7.3_expo-modules-autolinking@1.2.0/node_modules/@expo/cli/build/src/export/exportAssets.js:53:37)
    at Object.exportAssetsAsync (/Users/user/myapp/apps/node_modules/.pnpm/@expo+cli@0.7.3_expo-modules-autolinking@1.2.0/node_modules/@expo/cli/build/src/export/exportAssets.js:98:11)
    at async Object.exportAppAsync (/Users/user/myapp/apps/node_modules/.pnpm/@expo+cli@0.7.3_expo-modules-autolinking@1.2.0/node_modules/@expo/cli/build/src/export/exportApp.js:99:25)
    at async exportAsync (/Users/user/myapp/apps/node_modules/.pnpm/@expo+cli@0.7.3_expo-modules-autolinking@1.2.0/node_modules/@expo/cli/build/src/export/exportAsync.js:44:5)
``` 

The error is caused by this line: https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/export/exportAssets.ts#L73

### SDK Version

48

### Environment

System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/user/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-29 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    Expo Workflow: bare

### Minimal reproducible example

`npx expo export`

**Comment by byCedric** [comment]
Hi @liemdo! Thanks for filing this issue. While this is a bug in the CLI, I want to give a heads-up that _currently_ you have to change a few things if you want to use pnpm with Expo/React Native. Better support for pnpm is coming in later versions of React Native though.

For now, you'd have to create `.npmrc` file in the root of your project and add `node-linker=hoisted`. This is because multiple parts of React Native aren't playing nice with pnpm's isolated node modules structure.
- See [this example for monorepo + pnpm](https://github.com/byCedric/expo-monorepo-example#pnpm-workarounds)
- See [pnpm's docs on React Native](https://pnpm.io/npmrc#node-linker)

**Comment by tanjunior** [comment]
I am still getting this error on `49.0.13`

**Comment by optimech** [comment]
> I am still getting this error on `49.0.13`

hi, did you find any fix?

**Comment by tanjunior** [comment]
> > I am still getting this error on `49.0.13`
> 
> hi, did you find any fix?

I switched back to pnpm from bun and it's fine.

**Comment by sweebee** [comment]
any news on this, I'm also getting this error.

**Comment by dylanrandle** [comment]
I'm getting this error with npm on SDK49

**Comment by dylanrandle** [comment]
FWIW I manually added the `glob` and  `minimatch` dependencies added in this [PR](github.com/expo/expo/pull/22941) to my `package-lock.json` (then re-ran `npm i`). Seems to fix the issue for me.

**Comment by sbassalian** [comment]
Search `"node_modules/@expo/cli"` in your `package-lock.json` file. Add to `"dependencies"`

```
"glob": "^7.1.7",
"minimatch": "^3.0.4",
```
