### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you mightnts) or a class/function (for composite components) but got: undefined. You likely forgot to export your component  have mixed up default and named imports.

### ISSUE THREAD

**Issue by amicharski** [expo/expo#22897]
### Minimal reproducible example

https://github.com/amicharski/react-native-is-annoying-sometimes

### Summary

I built a basic app with the Expo framework that just has a login page, a custom font, and custom styling. I'm getting this error and I have no idea why. I triple checked it with other developers to make sure I'm not going insane and all of my imports seem to be working fine, but I still get this error:

```
 LOG  false
 LOG  true
 ERROR  Warning: React.jsx: type is invalid -- expected a string (for built-in 
components) or a class/function (for composite components) but got: undefined. 
You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 LOG  true
 ERROR  Warning: React.jsx: type is invalid -- expected a string (for built-in 
components) or a class/function (for composite components) but got: undefined. 
You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.

This error is located at:
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~48.0.18 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

**Comment by brentvatne** [comment]
i'd recommend using typescript! it will quite quickly show you the problem.

<img width="788" alt="image" src="https://github.com/expo/expo/assets/90494/882f78ce-ee48-46e3-b10d-a9265e61e932">

all you need to do is rename `App.js` to `App.tsx` and then run `npx expo start` and it'll prompt you to install typescript and configure it. also see https://expo.github.io/router/docs/ for more information about how to use expo-router

**Comment by Jemeni11** [comment]
Hey, @brentvatne!
I have the same error but I was already using typescript and my IDE isn't showing any errors

**Comment by dexkode4** [comment]
I am having the same error

**Comment by brentvatne** [comment]
this error just means you are trying to render something that is undefined. for example:

```
let MyComponent = undefined

return <MyComponent />
```

that will give you this error

**Comment by dexkode4** [comment]
I haven't even edited the code , straight out of the command 
`npx create-expo-app --template`

Navigation with typescript template

**Comment by dexkode4** [comment]
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Check the render method of `GestureHandlerRootView`.**

**Comment by dexkode4** [comment]
maybe something is wrong in expo's api **GestureHandlerRootView**

**Comment by Jemeni11** [comment]
> I haven't even edited the code , straight out of the command `npx create-expo-app --template`
> 
> Navigation with typescript template

Same! I haven't written a single line of code yet this is the exact project I got from running yarn create expo-app --template and selecting Navigation (TypeScript).

**Comment by dexkode4** [comment]
I used two mac book and still get the same error, so obviously something isn't right here

**Comment by brentvatne** [comment]
@dexkode4 - see https://expo.fyi/manual-debugging

**Comment by amerikan** [comment]
I'm getting exact problem. Brand new project I created right now. I'm on M1 Mac.

1.  `yarn create expo-app --template`
2.  choose the Navigation (Typescript) option. 
3. Run `yarn ios` I get the following saying to check GestureHandlerRootView:

```
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `GestureHandlerRootView`.
```

**Comment by amerikan** [comment]
I was able to get it working with Yarn only if I installed `react-native-gesture-handler` (`expo install react-native-gesture-handler`). After that `yarn ios` worked with no problem. @brentvatne do you happen to know why this is needed with yarn, but not when npx is used? Seems like a bug to me?

**Comment by brentvatne** [comment]
thanks for catching that, it seems that at some point a dependency (perhaps @react-navigation/native) changed so that rngh became required. i added that dependency to the sdk 48 template and published a new version of it. this dependency is not needed in sdk 49, so i did not change that template.

**Comment by EliasMwita** [comment]
in have this kind of error I tried to solve it but it seem to be disappoint me

**Comment by nasirhussainn** [comment]
Getting this error - Even though all other screens were imported and exported in the same way and didnt get any error

**Comment by Khaleeq01** [comment]
lement type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:35914:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:35935:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:23529:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:23579:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:28009:32)
    at updateContextProvider (http://localhost:3000/static/js/bundle.js:29718:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:30133:18)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:35047:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:34317:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:34240:9)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
I am getting this error someone help me ? I am making mern stack quiz app

**Comment by ChefPixel** [comment]
i solved the problem declaring instead export default function "example.Button" in const Button = () => and then export default Button...that worked for me

**Comment by arixstudio** [comment]
Late to the party here, but if you are sure about the export method of your component, simply kill the server and run again. It will be gone

**Comment by pranavgeek** [comment]
I am having this error any idea how can i solve it: Warning: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CellRenderer`.

**Comment by devendra-dangi** [comment]
ERROR  Warning: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Drawer`.

This error is located at:
    in GestureHandlerRootView
    in GestureHandlerRootView (created by Drawer)
    in Drawer (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
    in FrameSizeProviderInner (created by FrameSizeProvider)
    in FrameSizeProvider (created by SafeAreaProviderCompat)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationStateListenerProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by DrawerNavigation)
    in DrawerNavigation (created by App)
    in ThemeProvider
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in NavigationContainerInner (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in DaikinTechHub(RootComponent), js engine: hermes


  "react": "18.3.1",
   "react-native": "0.76.9",
  "@react-navigation/bottom-tabs": "^7.4.2",
    "@react-navigation/drawer": "^7.5.3",
    "@react-navigation/material-top-tabs": "^7.3.2",
    "@react-navigation/native": "^7.1.6",
    "@react-navigation/stack": "^7.2.10",
    "react-native-safe-area-context": "^5.4.0",
    "react-native-screens": "^4.4.0",
    "react-native-gesture-handler": "^1.9.0",


I am also facing the same issue anyone who can provide solution for this ?
