### ISSUE TITLE
Console.log doesn't print functions inside objects.

### ISSUE THREAD

**Issue by funkjunky** [expo/expo#229]
in Expo console.log({ myFnc: () => {}) and you'll see an empty object.

https://snack.expo.io/HJkMRgGfb

**Comment by dikaiosune** [comment]
Hi! Thanks for the report! This appears to be a result of the underlying problem raised in https://github.com/expo/expo/issues/168, so we'll continue to track progress on a resolution there.

**Comment by brentvatne** [comment]
yup this will likely be fixed in the next release
