### ISSUE TITLE
Expo Push Notification not coming on Android devices

### ISSUE THREAD

**Issue by shashi-kiwi** [expo/expo#22905]
### Minimal reproducible example

Expo Push Notification not coming on Android devices

### Summary

We are using expo-push-notifications. On iOS we are able to get the notifications but on Android remote push notifications are not coming neither by Expo Push Notification Test tool nor by Firebase console.

### Environment

Debug and Release both

**Comment by Justin-Jingcheng-Peng** [comment]
Are you able to fix this?
