### ISSUE TITLE
Compatibility Issue with Passing PlatformColor to setBackgroundColorAsync

### ISSUE THREAD

**Issue by Spart-v6** [expo/expo#22901]
### Summary

I am encountering an issue while attempting to pass a PlatformColor as an argument to the setBackgroundColorAsync function in the expo-navigation-bar package. I came across the code of the setBackgroundColorAsync function which expects a ColorValue, which can be either a string or an OpaqueColorValue.

When I pass a PlatformColor as an argument to setBackgroundColorAsync, it throws an error indicating an incompatible class, java.util.HashMap, cannot be passed as an argument to a parameter expecting an int.
This is the full error message:
```
WARN  Possible Unhandled Promise Rejection (id: 1):
Error: Argument of an incompatible class: class java.util.HashMap cannot be passed as an argument to parameter expecting int.
```

This error is unexpected, as PlatformColor is accepted by other components such as the backgroundColor prop of the <View/> element. The backgroundColor also expects a ColorValue i.e. either string or OpaqueColorValue.
For instance, the following code snippet works without any issues:
```jsx
<View style={{backgroundColor: PlatformColor('@android:color/system_neutral2_900')}}>
</View>
```

Meanwhile, when attempting to use the same PlatformColor with setBackgroundColorAsync as shown below, it results in an error:
```jsx
NavigationBar.setBackgroundColorAsync(PlatformColor('@android:color/system_neutral2_900'));
```

Is there any way to resolve this issue and pass the PlatformColor as an argument to setBackgroundColorAsync?

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~48.0.5 => 48.0.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    Expo Workflow: managed

### Minimal reproducible example

I've reproduced the same issue in this snack:
https://snack.expo.dev/@ankur24/issue

Please run this on a physical device (android preferably) in the Expo Go app

**Comment by hirbod** [comment]
Untested, but you might be able to achieve what you need like so:

```tsx
import { processColor, PlatformColor } from 'react-native';

const color = processColor(PlatformColor('@android:color/system_neutral2_900'));
NavigationBar.setBackgroundColorAsync(color);
```

setBackgroundColorAsync is expecting [an int value representing the color.](https://github.com/expo/expo/blob/main/packages/expo-navigation-bar/android/src/main/java/expo/modules/navigationbar/NavigationBarModule.kt#L48) When you use PlatformColor, it is not returning a simple int color value; instead, it's returning a complex object (OpaqueColorValue) that encapsulates a color reference for the Android platform.

While my solution is only a workaround, it should be quick and fast enough imho.

**Comment by Spart-v6** [comment]
Hi, I've tested processColor already, and it does not work.
It throws the same warning message:
Error: Argument of an incompatible class: class java.util.HashMap cannot be passed as an argument to parameter expecting int.

Do you have any other workaround method?

**Comment by hirbod** [comment]
Hmm, I might be able to fix this in native-land

**Comment by hirbod** [comment]
Nope

**Comment by hirbod** [comment]
Not stale

**Comment by hirbod** [comment]
Nope
