### ISSUE TITLE
[expo-image]Expo go crashes when using expo-Image blurhash on Android 

### ISSUE THREAD

**Issue by sperrys** [expo/expo#22921]
### Minimal reproducible example

https://github.com/sperrys/expo-blurhash-bug

### Summary

In looking to migrate to the expo-image package, we ran into a consistent issue using a blurhash placeholder on android. On IOS, the transition from a blurhash placeholder to a downloaded image works as expected. On Android, using expo-go, the same blurhash transition crashes the expo app. 

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.7
    Expo Workflow: managed

**Comment by feRpicoral** [comment]
I'm having the same issue. It works fine on a development build, but using a blurhash as a placeholder on `expo-image` crashes Expo Go on Android.

**Comment by feRpicoral** [comment]
@sperrys I believe you forgot to push something to the MRE as it doesn't have `expo-image` installed

**Comment by sperrys** [comment]
@feRpicoral , thanks for the ping. Updated.

**Comment by feRpicoral** [comment]
@sperrys I would suggest changing the title of the issue to `[expo-image] Expo Go on Android crashes when using blurhash as placeholder`.

Nevertheless, I don't think we will see an update anytime soon - with the release of SDK 49 I imagine their focus is on that. If someone else finds this issue, for now there's not much to do other than not using blurhash when `Constants.appOwnership` is `expo`.

**Comment by JPStrydom** [comment]
We're experiencing the same issue. Works fine on built apps, but keeps crashing on Expo Go. If we remove the blurhash placeholder, then it works on Expo Go.

Our library versions:
```
"expo": "^48.0.20",
"expo-image": "1.3.1",
"react-native": "0.71.8",
```
