### ISSUE TITLE
[expo-store-review]: Unable to open In-App Reviews Pop-up on android

### ISSUE THREAD

**Issue by alu0100207385** [expo/expo#22932]
### Minimal reproducible example

https://snack.expo.dev/@aaron.gaspar/surprised-sandwich

### Summary

**Actual behavior**

- The API [Expo StoreReview](https://docs.expo.dev/versions/latest/sdk/storereview/) seems not working fine on Android.
- It works fine in iOS.

**Expected behavior**

- The API [Expo StoreReview](https://docs.expo.dev/versions/latest/sdk/storereview/) should display the prompt in Android and iOS.

Tested on simulator iPhone 14 Pro - iOS 16.2 and Samsung Galaxy S10+, Android 12.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2022.02.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/aaronsg/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-33 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.9 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.4.1
    Expo Workflow: bare

**Comment by rvasseur31** [comment]
It's not an expo-store-review problem, I also see that with android java, please refer to this stackoverflow response : https://stackoverflow.com/a/65333746

In my case, it solved the problem with:

> Now go into Settings->Apps & notifications->Google Play->Storage & Cache, then do both CLEAR CACHE and CLEAR STORAGE. (This should not affect any of your installed apps).

**Comment by alu0100207385** [comment]
Hi. I have checked this on a native Android app and it works as expected. Even the in-app-review prompt is shown in debug mode (it does not happen with expo-store-review). Should I be able to see it when I'm developing an expo app in debug mode?
