### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by HadrianDeveloper** [expo/expo#22944]
### Summary

Please could you create documentation on how to setup Android Studio for WSL users? There are no concrete guidance anywhere, and the two I have tried both failed me. I am getting so desperate now, and contemplating replacing my WIndows laptop with a Linux, at huge expense! 

### Link to the related docs page

https://github.com/expo/expo/blob/main/docs/pages/workflow/android-studio-emulator.mdx

**Comment by amandeepmittal** [comment]
Hey @HadrianDeveloper, check React Native docs here: https://reactnative.dev/docs/environment-setup for installing, for more info about installation on steps in Windows.
