### ISSUE TITLE
Push notifications received when the app is killed, not navigating to the expected screen when we tap on it.

### ISSUE THREAD

**Issue by pratimawaghmare** [expo/expo#22969]
### Minimal reproducible example

``` // Push Notifications const lastNotificationResponse = Notifications.useLastNotificationResponse();    Notifications.setNotificationHandler({      handleNotification: async () => ({        shouldShowAlert: true,        shouldPlaySound: true,        shouldSetBadge: true      })    });    useEffect(() => {      if (lastNotificationResponse && lastNotificationResponse.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER     )  {   dispatch(NotificationActions.getNotifications(undefined, false));        handleNotificationData(lastNotificationResponse);        console.log('lastNotificationResponse', lastNotificationResponse);      }}, [lastNotificationResponse]);   useEffect(() => {      // when a notification is received or interacted with this two methods handle the data      // Will use there responses for future navigation      notificationListener.current = Notifications.addNotificationReceivedListener((notification) => {});      // when clicked on notification, this listner gets called      responseListener.current = Notifications.addNotificationResponseReceivedListener((response) => {       handleNotificationData(response);     });       return () => {       Notifications.removeNotificationSubscription(notificationListener);       Notifications.removeNotificationSubscription(responseListener);      };   }, []);   const handleNotificationData = (response: NotificationResponse) => {     const resp: NotificationResponse = response;     const request: NotificationRequest = resp.notification.request;     const content: NotificationContent = request.content;     const data: ContentData = content.data;    const type = data?.type;     const profile = data?.profile;     const firstName = profile?.firstName;     const lastName = profile?.lastName;     const image = profile?.image;     const type=profile.type;       // data for user contact     var contact = {       firstName: firstName,       image: image,       lastName: lastName       type: type     };     // adding contact details in redux     dispatch(ContactsActions.setCurrentContact(contact));     if (type === NotificationType.REQUEST_SENT) {       // navigation to handle sent request       navigate.navigate(strings.contact_profile_modal_scene_name, {contact});     } else if (type === NotificationType.REQUEST_ACCEPTED && state === ContactState.SHARE) {       // navigation to handle accepted request from quick add       navigate.navigate(strings.contact_share_options_scene_name, {action: navigationActions.NAV_SHARE_PRESET});     } else if (type === NotificationType.REQUEST_ACCEPTED || type === NotificationType.BIRTHDAY) {       // navigation to handle accepted request       navigate.navigate(strings.contact_profile_page_scene_name, {contact});     }   }; ```

### Summary

I have implemented functionality to handle the push notifications according to their type. Whenever the user receives a push notification and clicks on it, the listener gets triggered and according to the notification type, I am navigating the user to the different screens in the app.
This is working fine in cases when an app is in the foreground and opened in the background, I am receiving the push notifications, and navigation for it is also working correctly.

But in the case when the app is killed and I receive the notification, on click of it, it takes a user to the home/main screen in the app and not to the expected navigation screen as per the notification type.
Also, I noticed that none of the listeners added to handle the notification and its response gets triggered. And it is also not throwing any specific error.

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.12.1 - /usr/local/bin/node
npm: 8.19.2 - /usr/local/bin/npm
Watchman: 2022.12.12.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
IDEs:
Android Studio: 2021.3 AI-213.7172.25.2113.9123335
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
npmPackages:
babel-preset-expo: ~9.2.1 => 9.2.2
expo: ^47.0.0 => 47.0.14
react: 18.1.0 => 18.1.0
react-dom: 18.1.0 => 18.1.0
react-native: 0.70.5 => 0.70.5
react-native-web: ~0.18.7 => 0.18.12
npmGlobalPackages:
eas-cli: 3.13.2
expo-cli: 6.3.8
Expo Workflow: managed

**Comment by kitolog** [comment]
Same here, works in a foreground but not in a background

**Comment by federicogomezlara** [comment]
@pratimawaghmare Manage to find any solution? I have the exact same problem

**Comment by DSp4wN** [comment]
I am facing the same issue while the app is running in foreground expo go, it does call the addNotificationResponseReceivedListener but when it is in background it just opens the app and the listener never gets called.

Whereas in android production apk both of them don't work.

    "expo": "^50.0.17",
    "expo-constants": "^15.4.6",
    "expo-device": "^5.9.4",
    "expo-notifications": "^0.27.7",
    "react": "18.2.0",
    "react-native": "^0.73.6",
    
  These are my package versions

**Comment by jivanovic** [comment]
+1, not working on Android when in background or killed

**Comment by deemyboy** [comment]
same here except...

I (was forced to) upgradd from Expo SDK 48 to SDK 50 due to the recent Apple emails post submission to App Sotre Connect regarding certain API keys being required for submissions after May 1st 2024 in app.json (NSPrivacyAccessedAPICategoryDiskSpace, NSPrivacyAccessedAPICategorySystemBootTime, NSPrivacyAccessedAPICategoryFileTimestamp, NSPrivacyAccessedAPICategoryUserDefaults).

Anyway, since upgrading my app reboots after responding to a push notification in it's bubble, or if the buuble closes then by tapping the notification in the notifications bar at the top of the screen.

It was working and the app never rebooted - this is only in Expo Go/dev-client (not sure the difference there tbh) - I am able to run either by running yarn start which calls     "start": "expo start --dev-client --clear", under the hoodin package.json

Is anyone else having issues with their app rebooting after responding/tapping a notification.

I'm using this setup in m y package.json

  "dependencies": {
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0-0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0-0",
    "@babel/preset-env": "^7.1.6",
    "@expo-google-fonts/open-sans": "^0.2.3",
    "@expo/vector-icons": "^14.0.0",
    "@microsoft/fetch-event-source": "^2.0.1",
    "@react-native-community/netinfo": "11.1.0",
    "@react-native-masked-view/masked-view": "0.3.0",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/elements": "^1.3.18",
    "@react-navigation/material-bottom-tabs": "^6.2.16",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.17",
    "@rntext/more-or-less": "^2.0.1",
    "axios": "^1.4.0",
    "date-fns": "^2.30.0",
    "expo": "^50.0.17",
    "expo-application": "~5.8.4",
    "expo-build-properties": "~0.11.1",
    "expo-dev-client": "~3.3.11",
    "expo-device": "~5.9.4",
    "expo-font": "~11.10.3",
    "expo-linking": "~6.2.2",
    "expo-location": "~16.5.5",
    "expo-notifications": "~0.27.7",
    "expo-router": "~3.4.8",
    "expo-secure-store": "~12.8.1",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.4",
    "expo-task-manager": "~11.7.3",
    "expo-updates": "~0.24.12",
    "expo-web-browser": "~12.8.2",
    "i18next": "^23.11.0",
    "metro": "~0.80.4",
    "metro-react-native-babel-preset": "^0.77.0",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.43.9",
    "react-i18next": "^13.3.1",
    "react-native": "0.73.6",
    "react-native-animation-library": "^0.0.8",
    "react-native-country-flag": "^2.0.2",
    "react-native-curved-bottom-bar": "https://github.com/deemyboy/react-native-curved-bottom-bar",
    "react-native-event-source": "fatonspb/react-native-event-source",
    "react-native-gesture-handler": "2.14.0",
    "react-native-pager-view": "6.2.3",
    "react-native-paper": "^5.8.0",
    "react-native-paper-form-builder": "^2.1.2",
    "react-native-paper-tabs": "^0.7.0",
    "react-native-paper-toast": "https://github.com/kuasha420/react-native-paper-toast#3b474847a5275ed586a41d283301986f23fe8b90",
    "react-native-reanimated": "~3.6.2",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-select-dropdown": "^3.4.0",
    "react-native-svg": "14.1.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react-dom": "~18.0.10",
    "@types/react-native-event-source": "^1.1.2",
    "@types/react-native-vector-icons": "^6.4.18",
    "@typescript-eslint/eslint-plugin": "^5.59.6",
    "@typescript-eslint/parser": "^5.0.0",
    "babel-preset-expo": "^10.0.2",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-config-standard-with-typescript": "^34.0.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.7.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.32.2",
    "jest": "^29.6.3",
    "jest-expo": "~50.0.4",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "private": true,
  "packageManager": "yarn@4.2.1"
  
  and these are my listeners in my 

notifications-context file


  useEffect(() => {
    const notificationListener = Notifications.addNotificationReceivedListener(handleNotificationReceived);

    const responseListener = Notifications.addNotificationResponseReceivedListener((response) => {
      console.log('🚀  |  file: notifications-context.tsx:129  |  responseListener  |  response:', response);
      setLastNotificationResponse(response);
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener);
      Notifications.removeNotificationSubscription(responseListener);
    };
  }, []);
