### ISSUE TITLE
Building Exponent (Expo Go) leads to unexplained rabbit hole of conflicting dependencies, linking error, and etc. Is there an official way to build the project?

### ISSUE THREAD

**Issue by rafi16jan** [expo/expo#22960]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/ios/Exponent.xcworkspace

### Summary

Building Exponent (Expo Go) leads to unexplained rabbit hole of conflicting dependencies, linking error, and etc. Is there an official way to build the project?

I tried to change the bundle id to what is available and setup all the project dependencies with yarn and cocoapods. In the end it compiles but the Debug version of the app complains about cannot conect to https://exp.host/@exponent/home and the Release version just outright crash

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.5
      Shell: 5.1.4 - /opt/homebrew/bin/bash
    Binaries:
      Node: 20.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - /opt/homebrew/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.3.8
    Expo Workflow: managed (this is from the home directory (Expo Go UI))

**Comment by youssef-devx** [comment]
Try EAS Build: https://docs.expo.dev/build/introduction/

**Comment by alanjhughes** [comment]
@rafi16jan - Why do you want to build from source?

**Comment by rafi16jan** [comment]
> @rafi16jan - Why do you want to build from source?

Because I used to sideload Expo Go in Big Sur and those workflow can't be beaten, I remember having 3 projects done in one day at that time. I wish Apple didn't block sideloading or at least not this restrictive. But you guys can just enable the app for apple silicon macbooks though in App Store that way I didn't have to build it from source

**Comment by rafi16jan** [comment]
> Try EAS Build: https://docs.expo.dev/build/introduction/

Should I do the eas build cli from ios/Exponent.xcworkspace or home/ ? I don't think building regular exponpr

**Comment by rafi16jan** [comment]
> > @rafi16jan - Why do you want to build from source?
> 
> Because I used to sideload Expo Go in Big Sur and those workflow can't be beaten, I remember having 3 projects done in one day at that time. I wish Apple didn't block sideloading or at least not this restrictive. But you guys can just enable the app for apple silicon macbooks though in App Store that way I didn't have to build it from source

Keep in mind using Expo Go in iOS Simulator is not an option for me. I do a lot of camera things like Barcode reader and stuff and iOS simulator doesn't have a real camera while if I installed it on the host macbook (or compile the ios prebuild directly to the machine) it will use the macbook's webcam, pretty neat.

**Comment by alanjhughes** [comment]
@rafi16jan - you can do this with prebuild. It's not necessary to use expo go.

**Comment by rafi16jan** [comment]
> @rafi16jan - you can do this with prebuild. It's not necessary to use expo go.

No, prebuild takes a long time. npm install takes like 10 minutes and then pod install is like 1 hour. Not to mention you have to set the Apple Development account in XCode and make sure the bundleId is available. Plus another 15 minute to build a new clean project. Doing this with multiple project every once in a while is tiring

**Comment by alanjhughes** [comment]
@rafi16jan - I've never seen times like that for prebuild. Honestly, I'm not sure there's anything to be done here but I'll defer to @brentvatne

**Comment by rafi16jan** [comment]
> @rafi16jan - I've never seen times like that for prebuild. Honestly, I'm not sure there's anything to be done here but I'll defer to @brentvatne

We are from a 3rd world country, so it is obvious... And even worse my company is on the rural side of the country so no Gigabit Internet here...

**Comment by rafi16jan** [comment]
And other reason would be project size. Each of prebuild project (or ejected project that I have from older expo) range about 3.5 to 5+ gigs depending of the amount of native modules that it uses. Managed expo projects is barely 1gb, and please don't recommend eas build for M1 as a device target, I would like to develop locally and even sometimes offline

**Comment by brentvatne** [comment]
we're currently working on our sdk 49 beta release, and the current state of the project on the main branch may not be the most stable while this is happening. expo go for sdk 49 should run natively on apple silicon thanks to work by @aleqsio.

you can check out the sdk-48 branch and build from there if you like.

**Comment by rafi16jan** [comment]
> you can check out the sdk-48 branch and build from there if you like.

I already checked out the sdk-48 branch and try building from it. But from what I observe the main issue is I think there is bridging layer that doesn't exist in the xcworkspace project, and that bridge supposed to do for example bridging ABI_48_EXConstants to EXConstants (when compiling there is an error complaining that EXConstants.h is missing, which I fix it with adding new pod on Podfile that point to path ../packages/expo-constants/ios and that may not link properly) after contemplating I remember that Expo Go can run multiple SDK version on the app and I realize that that's why there are so many different ABIs and my bandaid fix is will not go nowhere. But I'm glad that you decided to make it available to Apple Silicon Macbooks, problem solved :)

**Comment by brentvatne** [comment]
> But I'm glad that you decided to make it available to Apple Silicon Macbooks, problem solved :)

we wanted to do this earlier but because we supported some third party apis that weren't compatible yet, we had to wait.

**Comment by rafi16jan** [comment]
@brentvatne when is the new Expo Go for iOS will be released?

**Comment by rafi16jan** [comment]
```
2.29.2 Jul 5, 2023
This version contains minor improvements and adds support for SDK 49.
```

I see this changelog for the new SDK 49 but it is still not available for Apple Silicon Macbooks
