### ISSUE TITLE
Expo Web Build Missing Loaders

### ISSUE THREAD

**Issue by danielshiplett** [expo/expo#22989]
### Minimal reproducible example

https://github.com/danielshiplett/expo-loader-issue

### Summary

When creating a new Expo application using the Typescript template, and then adding AWS Amplify Auth, the Expo application throws an error when loading in a web browser.  The error does not occur when loading the Android version of the application.

Unfortunately, I don't know if this is an Expo error, React Native error, or AWS Amplify error.  So I came here first.

I also don't know much about Babel, Metro, Webpack, etc.  So it may be a simple fix.  However, as a relatively experience developer, I could not find a solution after two days of searching.  Following basic Expo and AWS Amplify tutorials should either cover this situation or automatically configure the tooling to not produce this error in my opinion.

I've included a link to a repo that reproduces the error.  Specifically, when trying to run the web application locally using `npm run web` I get the following:

```
Logs for your project will appear below. Press Ctrl+C to exit.
ERROR in ./node_modules/@aws-amplify/ui-react-native/dist/Authenticator/Authenticator.js 40:26
Module parse failed: Unexpected token (40:26)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|     const typedFields = getRouteTypedFields({ fields, route });
|     if (isAuthenticatedRoute(route)) {
>         return children ? <>{children}</> : null;
|     }
|     return (<SafeAreaProvider>

ERROR in ./node_modules/@aws-amplify/ui-react-native/dist/Authenticator/withAuthenticator.js 5:16
Module parse failed: Unexpected token (5:16)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export default function withAuthenticator(Component, options = {}) {
|     return function WrappedWithAuthenticator(props) {
>         return (<Authenticator.Provider>
|         <Authenticator {...options}>
|           <Component {...props}/>

ERROR in ./node_modules/@aws-amplify/ui-react-native/dist/InAppMessaging/components/InAppMessageDisplay/InAppMessageDisplay.js 23:11
Module parse failed: Unexpected token (23:11)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|         onMessageAction,
|     });
>     return <Component {...props}/>;
| }
| InAppMessageDisplay.BannerMessage = BannerMessage;

ERROR in ./node_modules/@aws-amplify/ui-react-native/dist/InAppMessaging/components/withInAppMessaging/withInAppMessaging.js 6:16
Module parse failed: Unexpected token (6:16)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export default function withInAppMessaging(Component, options) {
|     return function WrappedWithInAppMessaging(props) {
>         return (<InAppMessagingProvider>
|         <InAppMessageDisplay {...options}/>
|         <Component {...props}/>

ERROR in ./node_modules/@aws-amplify/ui-react-native/dist/theme/ThemeProvider.js 6:12
Module parse failed: Unexpected token (6:12)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export const ThemeProvider = ({ children, theme, colorMode, }) => {
|     const value = React.useMemo(() => ({ theme: createTheme(theme, colorMode) }), [theme, colorMode]);
>     return (<ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>);
| };
| 

web compiled with 5 errors
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.0 
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

**Comment by whcherng** [comment]
Hi @danielshiplett, I encountered the same issue as well, do you have any solution yet?

**Comment by danielshiplett** [comment]
> Hi @danielshiplett, I encountered the same issue as well, do you have any solution yet?

No.  I'm still waiting for feedback here.

**Comment by NickFritz1982** [comment]
I am also getting this error, following the AWS tutorial at: https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native/#add-the-amplify-ui-authenticator-component

**Comment by yahlers** [comment]
Hi, I got this issue with amplify a couple month ago.

According to this issue #18485  I created a new entry point file `index.js` in root folder and replaced the `main`- field in `package.json` with the `index.js` (default: `node_modules/expo/AppEntry.js`)

The code in the `index.js` is as follows:

```js
import "expo/build/Expo.fx"
import registerRootComponent from "expo/build/launch/registerRootComponent"
import { createRoot } from "react-dom/client"
import { createElement } from "react"
import { Platform } from "react-native"
import App from "./App"

if ("web" === Platform.OS) {
    const rootTag = createRoot(
        document.getElementById("root") ?? document.getElementById("main")
    )
    rootTag.render(createElement(App))
} else {
    registerRootComponent(App)
}
```

Further on, I had to tweak the `app.json`:

```json
"web": {
  "build": {
    "babel": {
      "include": [
        "@aws-amplify/ui-react-native"
       ]
    }
  }
}
```

I have checked out your example repo, adapted all above and could see the login form again.

This approach is good enough for Expo SDK 48 and webpack but I'm struggling right now get it to work with SDK 49 and the metro bundler. Keep in mind that you might have to work on this again.

I hope this helps

**Comment by danielshiplett** [comment]
@yahlers That does help.  Thank you.

It turns out that all I needed to do was add the `web.build...` section you mentioned.  The changes to the entry point were no needed to correct the issue.

Since I don't really understand anything about the default Expo build setup or Babel transcompiling, can you explain to me what that change is actually doing?  I went to the Expo docs to look for that parameter and it doesn't seem to be listed.

[https://docs.expo.dev/versions/v48.0.0/config/app/#web](https://docs.expo.dev/versions/v48.0.0/config/app/#web)

**Comment by yahlers** [comment]
Thank you @danielshiplett for the info on the part with the entry point. I think that part was related to the react v18 changes.

I had an issue which is discussed [here](https://stackoverflow.com/a/73320743) on stackoverflow which leads to this issue #6157. 

As EvanBacon states in the last comment, the `app.json` approach is not the most stable solution and should be deprecated by now. I think including modules in the webpack/metro config is way smarter

**Comment by danielshiplett** [comment]
OK.  That seems to make sense.  Following those links I ended up at [this Expo documentation](https://github.com/expo/expo-cli/tree/master/packages/webpack-config#include-modules) that explained how to modify the Babel preset to include additional packages for transpilation.

My final solution was to create a new webpack.config.js using `npx expo customize webpack.config.js` (because I didn't already have the file).  Then to update the file to look like:

```javascript
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  return await createExpoWebpackConfigAsync(
      {
        ...env,
        babel: {
          dangerouslyAddModulePathsToTranspile: [
            // Add additional problem packages to the transpiler
            '@aws-amplify/ui-react-native',
          ],
        },
      },
      argv
  );
};
```

The Amplify Authentication module is now working as expected and I didn't need to modify the `app.json` or any other files.

Thanks again for your guidance @yahlers.

**Comment by cmionGrappa** [comment]
> Further on, I had to tweak the `app.json`:
> 
> ```json
> "web": {
>   "build": {
>     "babel": {
>       "include": [
>         "@aws-amplify/ui-react-native"
>        ]
>     }
>   }
> }
> ```




The above is what solved it for me, my app.json now looks like this:

`{
  "name": "my-app",
  "slug": "my-app",
  "web": {
    "build": {
      "babel": {
        "include": ["dripsy"]
      }
    }
  }
}
`
