### ISSUE TITLE
expo-web-browser doesn't throw error when attempting to open an invalid URL, instead causes crash

### ISSUE THREAD

**Issue by gkasdorf** [expo/expo#22986]
### Minimal reproducible example

https://snack.expo.dev/gsmhKTR6W

### Summary

When using expo-web-browser's `openBrowserAsync`, an improper URL passed to the browser may cause a crash instead of properly handling and throwing an error. In the example, a link with `%5B` in front of `https://` causes a crash.

Expected result would be to receive an error stating that the link was invalid or could not be opened.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.7 => 0.18.12 
    Expo Workflow: managed

**Comment by hirbod** [comment]
I have validated the issue and have fix for that in a bit

**Comment by hirbod** [comment]
Here we go: https://github.com/expo/expo/pull/23084

**Comment by gkasdorf** [comment]
Awesome! Thanks for the fix.
