### ISSUE TITLE
iOS push notifications are removing icon badge if you don't provide a badge param 

### ISSUE THREAD

**Issue by feliperaul** [expo/expo#2299]
### Environment

Environment:
  OS: macOS 10.14
  Node: 10.10.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: 29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

TARGET: Standalone iOS App, but the bug is reproducible using Expo app on iOS during development as well. 

### Steps to Reproduce

I noticed that when sending Push Notifications to iOS 12 (we use expo-server-sdk-ruby), the badge number set on the icon disappears imediatelly.

After looking through [the docs](https://docs.expo.io/versions/latest/guides/push-notifications), I found out that the badge number should only disappear if I provide a `badge` value of `0`, but in my tests this happens if you don't pass any `badge` value at all in the payload.

This shouldn't be the case, since Apple's payload docs also state that:

> Include this key when you want the system to modify the badge of your app icon. **If this key is not included in the dictionary, the badge is not changed**. To remove the badge, set the value of this key to 0.

So, by not passing any badge value, the icon should retain the previous badge number, but it's not, it's clearing it. 

Just to be extra sure, if I pass any value of `badge` in my payload, the icon badge DOES change, and if I pass `0` or don't pass a key at all (removing the `badge` from the payload), it resets.

Lastly, I have a `console.log` in my handleNotification handler, and I'm pretty sure my app is not at fault here because the badge disappears before clicking in the notification, so the isn't even aware of the notification yet; the reset also happens when, having the badge on the Expo app, I force quit Expo (it still resets as soon as the notification arrives), which makes me pretty confident that there's something wrong in the way expo is passing the `badge` key to Apple. 

### Expected Behavior

It should keep the previous icon badge count unless `badge` key is provided with a value, and only clear the badge if the value is `0`.

### Actual Behavior

Icon badge imediatelly disappears.

**Comment by ide** [comment]
Thanks for the report; we found the serialization library we use with our iOS push service was defaulting unset int fields to zero, causing this bug. We'll deploy a fix shortly in a few minutes.
