### ISSUE TITLE
[expo-intent-launcher] App crashes when coming back from app notifications permissions intent

### ISSUE THREAD

**Issue by sbouchard-stratejia** [expo/expo#22995]
### Minimal reproducible example
The bug doesnt happen in the snack(it seems to run in expo go) but feel free to take that code and run it in your own development build
https://snack.expo.dev/@sbouchard-stratejia/93f203

`startActivityAsync(ActivityAction.APP_NOTIFICATION_SETTINGS, {
        extra: {
          'android.provider.extra.APP_PACKAGE': Constants?.manifest?.android?.package,
          app_package: Constants?.manifest?.android?.package,
        },
      })`

### Summary

Hi guys, I am having trouble with the expo-intent-launcher library. When I launch an intent to modify the user's notification permissions the app crash when going back from the notifications dashboard, but only when we disable the notifications permission. When it is disabled and we enable it then go back to the app, everything goes smoothly.  Ive linked the code used to start the activity with the intent, a video of the behavior and the stack of the adb debugger when the crash occurs. It is to be noted that this bug doenst happen when we run the app through Expo Go, here is the problematic code : `startActivityAsync(ActivityAction.APP_NOTIFICATION_SETTINGS, {
        extra: {
          'android.provider.extra.APP_PACKAGE': Constants?.manifest?.android?.package,
          app_package: Constants?.manifest?.android?.package,
        },
      })`

https://github.com/expo/expo/assets/113033390/ad2e809f-315f-48d4-aece-8661cd06375b

Here is the Log I get when running the development build:
<img width="877" alt="image" src="https://github.com/expo/expo/assets/113033390/44b099f9-2f05-422d-bc02-e2b951c91ec3">

And here is the adb logcat I get when running the preview APK :

![image](https://github.com/expo/expo/assets/113033390/7f20c234-fb3f-46a2-94db-6198f47d46d8)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    Expo Workflow: managed

Expo SDK : 48.0.0

**Comment by NorseGaud** [comment]
Works fine for me on latest expo

```
       await IntentLauncher.startActivityAsync(
            IntentLauncher.ActivityAction.APP_NOTIFICATION_SETTINGS,
            { extra: { 'android.provider.extra.APP_PACKAGE': Application.applicationId } }
        )
        ```
