### ISSUE TITLE
Wrongly parsed query parameters in URL by Linking.parse() for published app in Expo Go

### ISSUE THREAD

**Issue by drnow4u** [expo/expo#22996]
### Minimal reproducible example

https://snack.expo.dev/@marnow/d89d11?platform=ios

### Summary

On iOS URL `exp://u.expo.dev/88888888-633f-4b80-806a-2e8a1f9aaaaa?channel-name=preview&runtime-version=exposdk:47.0.0/--/callback/test.html?state=acdda33c-81a1-4041-ad20-1730523aaaaa&session_state=22d7e21f-6acf-49ea-a70a-848488888888&code=a8e3b8fd-d11f-4c04-9572-e2bb88888888.22d7e21f-6acf-49ea-a70a-8484e2cf8ff3.eb43ee71-9840-45bf-b48e-4f9e8888888`
is parsed by `Linking.parse()` to query parameters:

```
{
"channel-name": "preview", 
"code": "a8e3b8fd-d11f-4c04-9572-e2bb88888888.22d7e21f-6acf-49ea-a70a-8484e2cf8ff3.eb43ee71-9840-45bf-b48e-4f9e8888888", 
"runtime-version": "exposdk:47.0.0/--/callback/test.html?state=acdda33c-81a1-4041-ad20-1730523aaaaa",
"session_state": "22d7e21f-6acf-49ea-a70a-848488888888"
}
```

The value of `"runtime-version"` is not what is expected.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
      Watchman: 2023.04.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
    npmGlobalPackages:
      eas-cli: 3.10.0
      expo-cli: 6.3.2
    Expo Workflow: bare

**Comment by MarcinNowak-codes** [comment]
This bug also prevent Expo Go from opening application e.g. by QR code or redirecting from web/app to Expo Go.

![image](https://github.com/expo/expo/assets/4015708/c31dc55a-d03b-48ad-a7e7-c58720d84fda)

**Comment by drnow4u** [comment]
Deed link  `exp://exp.host/@yourname/your-app/--/path` is working again :-)
