### ISSUE TITLE
Can't record video using expo-camera

### ISSUE THREAD

**Issue by KauL1n** [expo/expo#23013]
### Minimal reproducible example

https://github.com/KauL1n/Cant-record-video-using-expo-camera

### Summary

I'm designing an app in react-native using expo. Now I'm trying to record a short video sequence using expo-camera. On most devices(Android, any Galaxy S type) the function works without problems. But for example on a test device(Samsung Galaxy A71) the video preview works, but no video is recorded and the following error message appears:
~~~
Call to function 'ExponentCamera.record' has been rejected.
-> Caused by: java.lang.RuntimeException: Error retrieving camcorder profile params
~~~
I am in despair. On all Galaxy S devices, which I have tested, it works without problems. On the Samsung A71 I mentioned, only the preview appears and when I try to record a video, this message appears.

The code looks like:
~~~js
import { Camera} from 'expo-camera'

useEffect(() => {
        (async () => {
            MediaLibrary.requestPermissionsAsync();
            const cameraStatus = await Camera.requestCameraPermissionsAsync();
            const soundStatus = await Camera.requestMicrophonePermissionsAsync();
            setHasPermission(cameraStatus.granted === true && soundStatus.granted === true);
        })();
    }, [])

if(hasPermission === false){
    return <Text>No access to camera</Text>
}
const takeVideo = async () => {
    if(cameraRef){
        try{
            const data = await cameraRef.current.recordAsync();
            setSequence(data.uri)
        } catch(e){
            console.error(e);
        }
    }
}
...
<Camera
                style={styles.camera}
                type={Camera.Constants.Type.front}
                flashMode={Camera.Constants.FlashMode.off}
                ref={cameraRef}
            >
</Camera>
<Pressable 
    onPress={() => {
        takeVideo();
    }}
    style={styles.video}>
</Pressable>
~~~
I hope someone can help me. Thanks for your time :)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~48.0.11 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

**Comment by hirbod** [comment]
I think the issue comes from `CameraRecordingOptions` defaults, which might not be available for that specific device.

**Possible workaround:**
Did you try to pass different options to `recordAsync` and try a different quality for example?

**Possible native fix idea:**
Add an `ensureRecordingOptions` that it checks if an profile for a specific device exists and maybe fallback to a lower quality.

**Comment by KauL1n** [comment]
> I think the issue comes from `CameraRecordingOptions` defaults, which might not be available for that specific device.
> 
> **Possible workaround:** Did you try to pass different options to `recordAsync` and try a different quality for example?
> 
> **Possible native fix idea:** Add an `ensureRecordingOptions` that it checks if an profile for a specific device exists and maybe fallback to a lower quality.

Thank you for your reply. Your assumption was correct and we are currently looking for a solution so that the bug no longer occurs on any device :)

**Comment by hirbod** [comment]
I still believe you have a valid issue here that should be reopened. You attempted to record with _defaults_, and expo-camera failed, which it shouldn't have. I think the native side is capable of detecting the failure (if no recording options have been set) and should default to the best possible quality option if it fails with the defaults.

I've done some prototyping, and implementing this seems quite straightforward. I'm waiting for the Expo team's input and might open a PR for this.

**Comment by whollacsek** [comment]
Is there any workaround while we wait for the fix?

**Comment by KauL1n** [comment]
> Is there any workaround while we wait for the fix?

Yes, we use this:
~~~js
const takeVideo = async () => {
    if(cameraRef){
        try{
            const data = await cameraRef.recordAsync({quality: "4:3"});
            setSequence(data.uri)
        } catch(e){
            console.error(e);
        }
    }
}
~~~
instead of:
~~~js
const takeVideo = async () => {
    if(cameraRef){
        try{
            const data = await cameraRef.current.recordAsync();
            setSequence(data.uri)
        } catch(e){
            console.error(e);
        }
    }
}
~~~
This worked for us.

**Comment by whollacsek** [comment]
Thanks I ended up doing something similar using 720p

**Comment by DnEgorWeb** [comment]
While adding `quality` property works for some devices, for other devices (that were initially working fine) it now stopped working. Please check the related bug https://github.com/expo/expo/issues/13759

**Comment by DnEgorWeb** [comment]
unstale

**Comment by ste00martin** [comment]
I'm able to record on expo-camera version `14.0.4` however when upgrading to `14.0.5` I'm no longer able to record video, this is for both expo-camera and expo-camera/next

**Comment by shashikumarverma1** [comment]
i am getting this error again and again 
Error recording video: [Error: Video recording failed: Recording was stopped before any data
