### ISSUE TITLE
GroupViewManagerWrapper.createViewInstance crash (expo-image)

### ISSUE THREAD

**Issue by Rag0n** [expo/expo#23011]
### Minimal reproducible example

I don't have an example because I cannot reproduce this crash.

### Summary

This is reopen for [original issue](https://github.com/expo/expo/issues/22710).

```
Fatal Exception: java.lang.ClassCastException
android.view.View cannot be cast to android.view.ViewGroup

expo.modules.kotlin.views.GroupViewManagerWrapper.createViewInstance (GroupViewManagerWrapper.kt:18)
```

We started getting a lot of crash reports after switching to expo. We only use expo-image and expo-linear-gradient. In the original issue, another guy reported that they have the same issue and they only use expo-image, so I think the problem is somewhere in expo-image. We didn't have this problem before upgrading to expo, so it's 100% expo related. Previously, we were using FastImage.

The crash happens after opening app.

<img width="1028" alt="CleanShot 2023-06-21 at 14 27 16@2x" src="https://github.com/expo/expo/assets/1951128/d02f85a2-3477-493b-8b7d-a50610188d82">

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 3.5.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 16.14.2 - ~/.local/share/nvm/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.local/share/nvm/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.local/share/nvm/v16.14.2/bin/npm
      Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/alex_guschin/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.17 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: bare

**Comment by thespacemanatee** [comment]
+1, this also happened after we added `expo-image` to our project.

**Comment by norbertfogarasi** [comment]
Also happening to me, I am using `"expo-image": "^1.2.3",`

**Comment by Rag0n** [comment]
I just replaced expo-image with FastImage and no crashes anymore, so LinearGradient works fine.

**Comment by thespacemanatee** [comment]
![Screenshot 2023-06-26 at 9 39 04 AM](https://github.com/expo/expo/assets/6837599/085faca2-5b24-4037-9e8e-87c93f561331)

@lukmccall More than 500 crashes on prod, and it's our top issue. Could we get an acknowledgement at least that this issue exists?

**Comment by BrodaNoel** [comment]
Just so you know, this issue usually (99%) happens when the app is in Background

**Comment by tsapeta** [comment]
@BrodaNoel Fix for this issue has already been released, which version do you use?

**Comment by deggertsen** [comment]
I'm getting this issue on V1.3.2

**Comment by TheEhsanSarshar** [comment]
@tsapeta 
The issue still exist with the latest version

**Comment by tsapeta** [comment]
@deggertsen Which version of the `expo` package do you have? The root cause turned out to be in the core code, not expo-image itself, so you should upgrade `expo` instead.

**Comment by deggertsen** [comment]
Yes, it seems updating to expo 49.0.8 did resolve this issue. Sorry for the confusion.
