### ISSUE TITLE
[image-picker][android] Crash on new photo picker on older android devices

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#23020]
### Minimal reproducible example

https://github.com/thespacemanatee/image-picker-repro

### Summary

On the latest version of `expo-image-picker@14.3.0`, the new Android Photo Picker was introduced in #22658. We are getting the following event on crashlytics:

<img width="1000" alt="Screenshot 2023-06-22 at 12 34 59 PM" src="https://github.com/expo/expo/assets/6837599/f43caaf7-0311-4079-862f-bb2bcecb99f9">

<img width="300" alt="Screenshot 2023-06-22 at 12 36 27 PM" src="https://github.com/expo/expo/assets/6837599/90ded970-f6c2-416a-959d-e9926444a64b">

This is what the backported image picker looks like on Android 10 and below:

<img src="https://github.com/expo/expo/assets/6837599/313b7659-c2ce-46e3-9de2-7e38e73e6b98" width=200 />

Selecting an image with this picker will trigger the crash above. For some reason, the `Intent` provided in `ImageLibraryContract.parseResults` is null in such cases. My uneducated guess is that bumping `androidx.activity:activity-ktx` and `androidx.fragment:fragment-ktx:1.5.7` has something to do with this.

### Environment

<img width="335" alt="Screenshot 2023-06-22 at 12 44 20 PM" src="https://github.com/expo/expo/assets/6837599/03dd2e3a-ae1f-485c-a7db-df123c4e366f">

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.asdf/installs/nodejs/16.15.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.15.0/bin/yarn
      npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/honeycomb/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Hedgehog 2023.1.1 Canary 9 Hedgehog 2023.1.1 Canary 9
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.11 => 0.71.11 
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.7
    Expo Workflow: bare
```

**Comment by thespacemanatee** [comment]
@brentvatne @lukmccall I believe this issue should be looked at. We've already done the due diligence and tested this for y'all so the least we can get is some form of acknowledgement. This will certainly affect many users once SDK 49 hits.

**Comment by fobos531** [comment]
Hey @thespacemanatee 

Based on the screenshot you sent, it seems that the intent is indeed not null, but where the code may be failing is the `.data` part - it also looks like the `data` is missing from the intent that you sent from the crash report. Unfortunately I currently do not have the bandwidth to look at this, but my guess is it may have to do with image library or general file system permissions, or how storage is handled on < Android 10. Hopefully this helps in troubleshooting for the Expo team

**Comment by thespacemanatee** [comment]
> Hey @thespacemanatee 
> 
> Based on the screenshot you sent, it seems that the intent is indeed not null, but where the code may be failing is the `.data` part - it also looks like the `data` is missing from the intent that you sent from the crash report. Unfortunately I currently do not have the bandwidth to look at this, but my guess is it may have to do with image library or general file system permissions, or how storage is handled on <= Android 10. Hopefully this helps in troubleshooting for the Expo team.

I stepped through the debugger on Android Studio and found the Intent to be null. The line of code that fails is `requireNotNull(intent)`. This has nothing to do with permissions because the library has been working fine and dandy before this PR was merged. I think more testing should have been done before merging this.

**Comment by thespacemanatee** [comment]
> Hey @thespacemanatee 
> 
> Based on the screenshot you sent, it seems that the intent is indeed not null, but where the code may be failing is the `.data` part - it also looks like the `data` is missing from the intent that you sent from the crash report. Unfortunately I currently do not have the bandwidth to look at this, but my guess is it may have to do with image library or general file system permissions, or how storage is handled on <= Android 10. Hopefully this helps in troubleshooting for the Expo team.

@fobos531 

I stepped through the debugger on Android Studio and found the Intent to be null. The line of code that fails is `requireNotNull(intent)`. This has nothing to do with permissions because the library has been working fine and dandy before this PR was merged. I think more testing should have been done before merging this.

**Comment by thespacemanatee** [comment]
> @thespacemanatee 
> I've tested your reproduction on Android emulator API 29 (Android 10) and it works for me – do you have any details on the devices impacted or how to reproduce?

@aleqsio Thanks for testing it. Could you try it with the emulator I used? Pixel 4 API 28. It only crashes on the back ported image picker and not the document picker fallback. Was the picker you used the same as the image in OP?

**Comment by aleqsio** [comment]
Tbh I just run your repro, clicked the button and was able to select a picture. Need to read into how the backported picker is supposed to work.

I can try on API28 – it was definitely the document picker fallback 😕

**Comment by thespacemanatee** [comment]
> Tbh I just run your repro, clicked the button and was able to select a picture. Need to read into how the backported picker is supposed to work.
> 
> I can try on API28 – it was definitely the document picker fallback 😕 

@aleqsio I see. The backported picker is downloaded using Google Services and it will show up after you restart the app once it's downloaded, might need to restart once or twice from experience. It should look like the one in OP and will crash upon selecting an image.

**Comment by aleqsio** [comment]
I'd like to repro but unfortunately I'm unable to run the emulator in this version:
`Error while waiting for device: The emulator process for AVD Pixel_4_API_28 has terminated.`

I've opened API_27 on Pixel 4 with Google Services and it's still the document picker.

**Comment by thespacemanatee** [comment]
> I'd like to repro but unfortunately I'm unable to run the emulator in this version:
> `Error while waiting for device: The emulator process for AVD Pixel_4_API_28 has terminated.`
> 
> I've opened API_27 on Pixel 4 with Google Services and it's still the document picker.
> 

@aleqsio thanks for trying to repro. The problem is there if you can get the backported picker to show up. I can only hope someone from the expo team will keep trying to repro this, or at least revert the PR and release a new version while we investigate.

**Comment by thespacemanatee** [comment]
@fobos531 that would be a decent work around. We can use `isPhotoPickerAvailable` and fallback if needed. We should still sufficiently test that solution before releasing it. In the meantime, we can just patch the library.

**Comment by thespacemanatee** [comment]
@aleqsio @fobos531 I created a [PR](https://github.com/expo/expo/pull/23224/files) for this workaround. Correct me if I'm wrong but this regression will cause a lot of trouble once SDK 49 is out to the public. I'm quite surprised that there isn't a stringent requirement to backtest this on older Android versions.

**Comment by fobos531** [comment]
Hey @thespacemanatee 

This is great, thank you for the PR! I hope it will serve as a good interim workaround while the root issue is thoroughly resolved. I wholeheartedly apologize for all the headache this has caused you - I might have needed to explicitly mention that I didn't test the backported picker well enough so the PR would have not be merged "as quickly". Anyways, looking forward to the resolution of this ahead of SDK 49.

**Comment by AndreiCalazans** [comment]
This doesn't seem to be fully fixed

We are on version `14.3.1` and Expo SDK 49. We see the same crash where Intent is provided by the image picker fails on the require not null on intent data:


<img width="1279" alt="Screenshot 2024-01-16 at 13 30 56" src="https://github.com/expo/expo/assets/20777666/838642b6-fe5e-4221-93e2-745b220a20ac">


I'll upgrade to expo-image-picker@14.3.2 to see if it fixes the issue since @alanjhughes seems to have done some improvements around the Intent data parsing part in https://github.com/expo/expo/pull/23617.
