### ISSUE TITLE
Manifest string is not a valid JSONObject or JSONArray Error, After run expo eject

### ISSUE THREAD

**Issue by Sadi01** [expo/expo#2302]
### Environment

Environment:
  OS: Linux 4.15 (**Ubuntu 18.04**)
  Node: 8.10.0
  Yarn: Not Found
  npm: 6.3.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found (**but i have Android Studio 3.1.4 AI-173.4907809**)
  Device: Nexus 5 API 23 (Android 6.0, API 23)

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

### Steps to Reproduce

1.Create expo app (expo init myapp)
2.Eject from expo (expo eject)
3.expo start
4.Open android folder by Android Studio & press Run (Build completely successfully)

### Expected Behavior

Run my app in emulator without error!!

### Actual Behavior

![screenshot from 2018-09-27 12-20-31](https://user-images.githubusercontent.com/8774917/46134719-73c0fd80-c250-11e8-9deb-6a28224204bd.png)
![screenshot from 2018-09-27 12-20-47](https://user-images.githubusercontent.com/8774917/46134731-7885b180-c250-11e8-9423-f1eefacf3016.png)

Thanks.

**Comment by esamelson** [comment]
Hi @Sadi01 - it sounds like your expo CLI server is returning HTML when it should be returning JSON. Could you verify by using a web browser to visit the URL printed out by `expo start` while it's running (replacing the scheme with `http://` - e.g. `http://192.168.0.0:19000`)? You should see a plain JSON object, but if you see an HTML page instead, it may have more information such as error output.

**Comment by Sadi01** [comment]
Hi @esamelson - thanks for your attention, my steps:
1. run expo start
2. open http://192.168.1.50:19000 in web browser,
output is a plain JSON object:
```json
{"name":"oops","description":"This project is really great.","slug":"oops","privacy":"public","sdkVersion":"30.0.0","platforms":["ios","android"],"version":"1.0.0","orientation":"portrait","icon":"./assets/icon.png","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"http://192.168.1.50:19001/assets/./assets/splash.png"},"updates":{"fallbackToCacheTimeout":0},"assetBundlePatterns":["**/*"],"ios":{"supportsTablet":true,"bundleIdentifier":"com.mycompany.oops"},"android":{"package":"com.mycompany.oops","publishBundlePath":"android/app/src/main/assets/shell-app.bundle","publishManifestPath":"android/app/src/main/assets/shell-app-manifest.json"},"isDetached":true,"detach":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.8.1-sdk30.0.0-271c32ab-0715-4dfb-8270-ecead3679bb4.tar.gz"},"scheme":"expf41f99b0db384e47b530e8d11e279657","xde":true,"developer":{"tool":"expo-cli","projectRoot":"/home/sadi/Desktop/react_native/oops"},"packagerOpts":{"hostType":"lan","lanType":"ip","dev":true,"minify":false,"urlRandomness":"5g-g85"},"env":{},"bundleUrl":"http://192.168.1.50:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2Fhome%2Fsadi%2FDesktop%2Freact_native%2Foops%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles","debuggerHost":"192.168.1.50:19001","mainModuleName":"node_modules/expo/AppEntry","logUrl":"http://192.168.1.50:19000/logs","hostUri":"192.168.1.50:19000","iconUrl":"http://192.168.1.50:19001/assets/./assets/icon.png"}
```

**Comment by esamelson** [comment]
Hi @Sadi01 - a couple more things to try:

- first, what happens if you try to visit that URL in a web browser in your android emulator? Do you see the same thing? If not, it seems like there is an issue with your emulator connecting to local URLs.
- can you check that the value of `DEVELOPMENT_URL` in `android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java` matches that URL?

**Comment by Sadi01** [comment]
Hi @esamelson 

1. Yes, i see the same thing(a plain JSON object).
2. DEVELOPMENT_URL = "exp1d5d978395b643dbb4e3f536bca7542e://192.168.1.50:19000"

Thank you.

**Comment by sostenesg7** [comment]
I solve this by disabling firewall on lubuntu.

**Comment by articice** [comment]
If anyone is struggling with this issue, the problem is not in firewall.
I had nginx/apache running, and `android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java` had the wrong URL for bundler after eject.

in my case it was
```
public static final String DEVELOPMENT_URL = "xxxxxxx://192.168.0.106:80"
```

when it should have been
```
public static final String DEVELOPMENT_URL = "xxxxxxxx://192.168.0.106:19000"
```

My guess there's an auto-detection of this URL and it puts the wrong port (80) from a webserver running locally.
