### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'

### ISSUE THREAD

**Issue by eridr** [expo/expo#23032]
### Summary

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > An issue was found when checking AAR metadata:
     
       1.  Dependency 'androidx.browser:browser:1.6.0-beta01' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :app is currently compiled against android-33.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.1 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

### SDK Version

48.0.19

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
      Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.14.0
    Expo Workflow: managed

### Minimal reproducible example

```
eas build  --platform android
```

EAS Build crashes with the error shown in the summary.

**Comment by MaximCoppieters** [comment]
We are experiencing the same problem with similar packages installed.

**Comment by markl-vesper** [comment]
We found same build issue this morning and determined that react native inappbrowser dependency was causing the beta version of browser package to be pulled down

run gradlew app:dependencies
scan output for androidx.browser:

in this case we see that inappbrowser uses 1+ which means 1.6.0-beta(01) satisfies and it gets implemented

```
+--- project :react-native-inappbrowser-reborn
|    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.71.6 (*)
|    +--- org.greenrobot:eventbus:3.+ -> 3.3.1
|    |    \--- org.greenrobot:eventbus-java:3.3.1
|    +--- androidx.annotation:annotation:1.+ -> 1.7.0-alpha02 (*)
|    \--- androidx.browser:browser:1.+ -> 1.6.0-beta01 (*)
```

By changing the dependencies section of android/build.gradle file to 1.5+ it stops the beta version and the build works fine

```
dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  implementation 'com.facebook.react:react-native:+'
  implementation 'org.greenrobot:eventbus:3.+'
  def supportLibVersion = safeExtGet('supportLibVersion', safeExtGet('supportVersion', null))
  def androidXVersion = safeExtGet('androidXVersion', null)
  if (supportLibVersion && androidXVersion == null) {
    implementation "com.android.support:support-annotations:$supportLibVersion"
    implementation "com.android.support:customtabs:$supportLibVersion"
  } else {
    def defaultAndroidXVersion = "1.5+"
    if (androidXVersion == null) {
      androidXVersion = defaultAndroidXVersion
    }
    def androidXAnnotation = safeExtGet('androidXAnnotation', androidXVersion)
    def androidXBrowser = safeExtGet('androidXBrowser', androidXVersion)
    implementation "androidx.annotation:annotation:$androidXAnnotation"
    implementation "androidx.browser:browser:$androidXBrowser"
  }
}
```

I think a yarn install would undo this so some node patching might be required to make it stable

**Comment by eridr** [comment]
Thanks @markl-vesper, seem like it should soon be adressed.

https://github.com/proyecto26/react-native-inappbrowser/issues/423

**Comment by kubmir** [comment]
I have the same issue with same packages but I do not use `react-native-inappbrowser`. Any ideas about different use-case when this may be broken ?

**Comment by markl-vesper** [comment]
run gradlew app:dependencies
scan output for androidx.browser: 

it will show you all the packages using androidx.browser:

**Comment by Gautham495** [comment]
If you use inapp browser package use this in dependencies   

implementation ("androidx.browser:browser:1.3.0"){
        force = true
    }

**Comment by kubmir** [comment]
For me it was `react-natine-iap` lib

**Comment by gorip1** [comment]
Do you modify android/build.gradle in the node module folder ? I did and it is still not working :/ Eas build doesn't seem to care

I have the same issue with react-native-inappbrowser-reborn, spent the last 8 hours trying to fix :D happy to find this thread !

**Comment by SophieJung7** [comment]
I have the same issue happening...:(

**Comment by next6leo** [comment]
DO this plugin support expo react native?

**Comment by jeffairsonn** [comment]
> We found same build issue this morning and determined that react native inappbrowser dependency was causing the beta version of browser package to be pulled down
> 
> run gradlew app:dependencies scan output for androidx.browser:
> 
> in this case we see that inappbrowser uses 1+ which means 1.6.0-beta(01) satisfies and it gets implemented
> 
> ```
> +--- project :react-native-inappbrowser-reborn
> |    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.71.6 (*)
> |    +--- org.greenrobot:eventbus:3.+ -> 3.3.1
> |    |    \--- org.greenrobot:eventbus-java:3.3.1
> |    +--- androidx.annotation:annotation:1.+ -> 1.7.0-alpha02 (*)
> |    \--- androidx.browser:browser:1.+ -> 1.6.0-beta01 (*)
> ```
> 
> By changing the dependencies section of android/build.gradle file to 1.5+ it stops the beta version and the build works fine
> 
> ```
> dependencies {
>   implementation fileTree(dir: 'libs', include: ['*.jar'])
>   implementation 'com.facebook.react:react-native:+'
>   implementation 'org.greenrobot:eventbus:3.+'
>   def supportLibVersion = safeExtGet('supportLibVersion', safeExtGet('supportVersion', null))
>   def androidXVersion = safeExtGet('androidXVersion', null)
>   if (supportLibVersion && androidXVersion == null) {
>     implementation "com.android.support:support-annotations:$supportLibVersion"
>     implementation "com.android.support:customtabs:$supportLibVersion"
>   } else {
>     def defaultAndroidXVersion = "1.5+"
>     if (androidXVersion == null) {
>       androidXVersion = defaultAndroidXVersion
>     }
>     def androidXAnnotation = safeExtGet('androidXAnnotation', androidXVersion)
>     def androidXBrowser = safeExtGet('androidXBrowser', androidXVersion)
>     implementation "androidx.annotation:annotation:$androidXAnnotation"
>     implementation "androidx.browser:browser:$androidXBrowser"
>   }
> }
> ```
> 
> I think a yarn install would undo this so some node patching might be required to make it stable

Tanks you very much ! remove inappbrowser dependency resolve my problem !

**Comment by jatinhemnani01** [comment]
> For me it was `react-native-iap` lib

hey how did you fix it? @kubmir

**Comment by lucasbastianik** [comment]
> > For me it was `react-native-iap` lib
> 
> hey how did you fix it? @kubmir

+1
