### ISSUE TITLE
signInWithCredential is deprecated . Pls use signIngAndRetrieveDataWithCredential

### ISSUE THREAD

**Issue by timeturnback** [expo/expo#2307]
I use signInWithCredential to login with facebook like the docs
```
async function loginWithFacebook() {
  const { type, token } = await Expo.Facebook.logInWithReadPermissionsAsync(
    '<APP_ID>',
    { permissions: ['public_profile'] }
  );

  if (type === 'success') {
    // Build Firebase credential with the Facebook access token.
    const credential = firebase.auth.FacebookAuthProvider.credential(token);

    // Sign in with credential from the Facebook user.
    firebase.auth().signInWithCredential(credential).catch((error) => {
      // Handle Errors here.
    });
  }
}
```

But I get this warning : 
![screen shot 2018-09-27 at 20 34 13](https://user-images.githubusercontent.com/6651194/46149524-b86e8800-c294-11e8-956c-2a32e1b5b08b.png)

Trying to use signInAndRetrieveDataWithCredential return error : 
`Reference.child failed: First argument was an invalid path: undefined. Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"`

**Comment by esamelson** [comment]
Hi @timeturnback - unfortunately we do not provide support for here for firebase modules & methods as they are not officially part of our SDK. From the second error message you posted, it looks like you may be using the `signInAndRetrieveDataWithCredential` method incorrectly (perhaps not passing the right type of arguments), but you'll need to look at Firebase's docs to figure this out, or open an issue on their repo instead. Sorry 😞

**Comment by timeturnback** [comment]
thank you for reviewing . I will try to find for the solution for the firebase site
