### ISSUE TITLE
Expo-media-library - Error "unable to copy file into external storage"

### ISSUE THREAD

**Issue by FrSenpai** [expo/expo#23088]
### Minimal reproducible example

const imageSaved = await MediaLibrary.saveToLibraryAsync(uri);

### Summary

Hey all! 

I saw many times this issue when I was looking for a solution with my own problem, but it seems that the solution of adding: 
`
android:requestLegacyExternalStorage="true"
`
in the manifest isn't working on some Android 10 devices (Samsung A52S)
Permissions added to manifest: 
`
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
  <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
  <uses-permission android:name="com.android.vending.BILLING" />
  ` 

It's working on another devices in production mode, but not this one.
Any ideas ?

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~48.0.15 => 48.0.15
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: bare

**Comment by ZhangShuRui** [comment]
Step 1: 

 ```xml
<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
```

Step 2: 
you have to add android:requestLegacyExternalStorage="true" to AndroidManifest.xml

```xml
<manifest ... >
    <application android:requestLegacyExternalStorage="true" ... >
      ...
    </application>
</manifest>
```

**Comment by MaxTheTurtle0** [comment]
> Step 1:
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
> ```
> 
> Step 2: you have to add android:requestLegacyExternalStorage="true" to AndroidManifest.xml
> 
> ```
> <manifest ... >
>     <application android:requestLegacyExternalStorage="true" ... >
>       ...
>     </application>
> </manifest>
> ```

I also run into the same issue even though I added this
