### ISSUE TITLE
npx create-expo-module fails in Installing Dependencies in the example app

### ISSUE THREAD

**Issue by gur22-09** [expo/expo#23097]
### Summary

Creating a module with npx create-expo-module fails in Installing dependencies in the example app

### SDK Version

48.0.18

### Environment

    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
    Expo Workflow: bare

### Minimal reproducible example

create a new module with an example project `npx create-expo-module my-module`

```
✔ Downloaded module template from npm
✔ Created the module from template files
✔ Installed module dependencies
✔ Compiled TypeScript files
✔ Initialized the example app
✔ Configured the example app
✔ Prebuilt the example app
✖ Installing dependencies in the example app
Error: pod install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/mac/.npm/_npx/62900f925a4b91dc/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/mac/.npm/_npx/62900f925a4b91dc/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at podInstall (/Users/mac/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/createExampleApp.js:140:37)
    at /Users/mac/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/createExampleApp.js:61:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async newStep (/Users/mac/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/utils.js:21:16)
    at async createExampleApp (/Users/mac/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/createExampleApp.js:58:5)
    at async Command.main (/Users/mac/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:111:13) {
  pid: 48214,
  output: [
    '',
    '/Users/mac/diptab/expo-core/example/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:51: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.\n' +
      '/Users/mac/diptab/expo-core/example/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:51: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.\n'
  ],
  stdout: '',
  stderr: '/Users/mac/diptab/expo-core/example/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:51: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.\n' +
    '/Users/mac/diptab/expo-core/example/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:51: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.\n',
  status: 1,
  signal: null
}
```

**Comment by brentvatne** [comment]
go into the `example/ios` directory and run `pod install` - share the error msg here

**Comment by brentvatne** [comment]
also, i recommend using `npx create-expo-module@latest` or `yarn create expo-module` (the latter always uses the latest version)

**Comment by gur22-09** [comment]
re-installing pod fixed the issue

**Comment by ibmmt** [comment]
this setps work for me


The problem was related to Cocoapods when building an example project.

You went to your project's directory using cd xxxx.

You opened Xcode with 

`npm run open:ios.`

You found the "example" folder in your project.

Inside the example project folder, you ran pod install.

`pod install`

after that  **encountered an real issue**  my case it was  ActiveSupport deprecated 

To solve the problem, you uninstalled ActiveSupport with 

`gem uninstall activesupport.`

Then, you installed a specific version (7.0.8) with 

`gem install activesupport-7.0.8.`

After this update, your project worked fine without errors.

**Comment by ibmmt** [comment]
pod install --project-directory="example/ios"

**Comment by amrhassab** [comment]
Steps that fixed this issue for me on Mac:

Please note that there are two steps that can fail - this fixed both for me:

1) Failure at the "Installing module dependencies" step
2) Failure at the "Installing dependencies in the example app" step

The example app is created automatically by the expo module bootstrapper

**Steps I took that fixed issue 1:**

1) `rm /Users/mac/package.json`
2) `rm /Users/mac/yarn.lock`
3) `cd ~`
4) `yarn set version classic`
5) `cd Documents`
6) `yarn create expo-module my-module` (don't use npx ... not sure why this is how I made it work)

**Steps I took that fixed issue 2:**

1) Install XCode (The XCode CLI tool kit is sadly not enough on its own)

2) Open XCode > Preferences > Location if no path is shown under Command Line tools just reselect the path
