### ISSUE TITLE
Understanding app publishing and standalone apps

### ISSUE THREAD

**Issue by ahmed-wagdi** [expo/expo#231]
I'm in the process of deploying my first expo app and just wanted to clarify a few things. I built both the android and ios standalone apps but they were done through 2 separate expo accounts(because i didnt have the apple developer account to do it myself): 

- Android was done 100% through expo and is working fine
- For ios i had to detach to expokit before building the ipa for several reasons

i'm running into the following error when opening the ios standalone app:
![e176be32-b336-47e5-89ae-a8fd7dad54f3](https://cloud.githubusercontent.com/assets/8686483/26802908/9846d580-4a42-11e7-9e2c-e5f712440f48.jpeg)

When i go to the url pointing to the published app: https://expo.io/@my_username/app_slug
i get _"404: Experience Not Found!"_. 

If i'm not mistaken this means that in order to build a standalone app you need to publish the app through expo first or else it won't work. I'm guessing that the ios version isn't working because i'm using 2 separate expo accounts and the app wasn't published for the ios account. What i'm having trouble understanding is:

1. Shouldn't `exp start` publish your app or does this not work after detaching?
2. Even if exp start doesn't publish your app on detached projects, shouldn't detached projects be completely independent from expo?

**Comment by dikaiosune** [comment]
Hi! Good questions.

> I'm in the process of deploying my first expo app

yay!

> in order to build a standalone app you need to publish the app through expo first or else it won't work

Correct, although running `exp build:ios` should publish the app as part of that process.

> Shouldn't exp start publish your app or does this not work after detaching?

`exp start` runs the packager server locally, but you still need to run `exp publish` separately to have your JS bundle hosted.

> Even if exp start doesn't publish your app on detached projects, shouldn't detached projects be completely independent from expo?

The publish is still necessary to enable using our infrastructure for "over-the-air" updates of your JavaScript. You can definitely replace the JavaScript loader to pull from any URL you want though, since you're compiling everything locally.

Hopefully that answers your questions! If not feel free to reply here or come over to https://slack.expo.io and we'll do our best to help.

**Comment by ahmed-wagdi** [comment]
Sounds good. I think the importance of publishing your app should be made clearer in the docs though, up until this point i always thought that publishing through expo was purely done to distribute your app through the expo client for testing, i didnt know that it was required for production in standalone apps as well.

So maybe:

1. **Explain the importance of publishing your app**
2. **Highlight the publish step when deploying detached apps**, i think this is very important since [the steps listed for building the app](https://docs.expo.io/versions/v17.0.0/guides/expokit.html#3-ios-configure-build-and-run) only include running `exp start` and building on xcode. Which works for running the app on a connected device for testing, so when deploying the app people might assume (like i did) that there are no additional steps except for generating the ipa through xcode.

**Comment by dikaiosune** [comment]
cc @terribleben see this feedback about ExpoKit docs ^

**Comment by acomito** [comment]
I'm working on a guide but it is incomplete

https://github.com/acomito/expo-to-appstore-checklist

**Comment by ahmed-wagdi** [comment]
> You can definitely replace the JavaScript loader to pull from any URL you want though, since you're compiling everything locally.

How do i do this on a detached project?

**Comment by terribleben** [comment]
This is configured in [EXShell.plist or MainActivity.java](https://docs.expo.io/versions/v17.0.0/guides/detach.html#6-distribute-your-app).

**Comment by terribleben** [comment]
Followed up with [this docs change](https://github.com/expo/expo-docs/commit/a7fafd3a6b2be29c6058a66cf03f57567a0edabb).
