### ISSUE TITLE
BundleIdentifier replaced with exp

### ISSUE THREAD

**Issue by kenzic** [expo/expo#2311]
I have a standalone app using ExpoKit.

When opening a url containing the bundleIdentifier it’s replaced with “exp”.

For example, if my bundleIdentifier is “com.test.myapp” and I run xcrun simctl openurl booted "com.test.myapp://welcome" the URI becomes exp://welcome

The URI should be com.test.myapp://welcome. It’s breaking my auth0 implementation.

Environment:
OS: macOS High Sierra 10.13.6
Node: 10.8.0
Yarn: 1.9.4
npm: 6.2.0
Watchman: Not Found
Xcode: Xcode 10.0 Build version 10A255
Android Studio: Not Found

Packages: (wanted => installed)
expo: ^30.0.0 => 30.0.1
react: 16.3.1 => 16.3.1
react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

target iOS with Standalone using ExpoKit

Steps to Reproduce
(Write your steps here:)

Run app
run command in terminal: xcrun simctl openurl booted "com.test.myapp://welcome
Notice the url in the event (Linking.addeventlistener) is exp://welcome
Expected Behavior
uri should be com.test.myapp://welcome

Actual Behavior
uri is exp://welcome

**Comment by esamelson** [comment]
Hi @kenzic - I think you may be confusing the `bundleIdentifier` with the `scheme`, which is the value that should be used in Linking URLs. Have you tried setting your `scheme` to the same value (com.test.myapp)? https://docs.expo.io/versions/v30.0.0/expokit/advanced-expokit-topics#changing-the-deep-link-scheme

**Comment by kenzic** [comment]
Hi @esamelson - [react-native-auth0](https://github.com/auth0/react-native-auth0/) uses the bundle identifier for the [redirect url](https://github.com/auth0/react-native-auth0/blob/master/webauth/index.js#L58). Whether the schema value in the app.json is `myapp` or `com.test.myapp`, the url react-native-auth0 gets back has a schema of `exp`. This causes it to fail [here](https://github.com/auth0/react-native-auth0/blob/master/webauth/index.js#L72-L80)

I added the following code
```JavaScript
Linking.addEventListener("url", console.log)
```

I run:
```Bash
xcrun simctl openurl booted "com.test.myapp://welcome"
```
```Javascript
>> exp://welcome
```
```Bash
xcrun simctl openurl booted "myapp://welcome"
```
```Javascript
>> myapp://welcome
```

**Comment by kenzic** [comment]
Hi @esamelson - I released I had the ordering wrong, and now when react-native-auth0 uses the bundle identifier ("com.test.myapp") to redirect it works. Unfortunately, now my deep linking with URIs using myapp://welcome are broken and now replacing the scheme with `exp`.

**Comment by kenzic** [comment]
@esamelson - Please, let me know what other information you need me to provide.

**Comment by puttputt** [comment]
@kenzic Did you ever get this resolved? I'm encountering the same issue.
