### ISSUE TITLE
[Android] unable to run build on API 21

### ISSUE THREAD

**Issue by hunwalk** [expo/expo#23129]
### Minimal reproducible example

Create a barebone expo project and run on API 21

### Summary

The following log is spitted out by logcat 

java.lang.NoSuchFieldException: accessFlags

Found a similar issue at Detox: https://github.com/wix/Detox/issues/2527

The following file affects the code: `expo/android/src/main/java/expo/modules/ReactActivityDelegateWrapper.kt`
found here: https://github.com/expo/expo/blob/b29c181acb7fca194d6e9f9a4cdd3fc359451e91/packages/expo/android/src/main/java/expo/modules/ReactActivityDelegateWrapper.kt#L4

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.20.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.19.4 - /usr/bin/npm
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.0 
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.3.8
    Expo Workflow: bare

**Comment by hunwalk** [comment]
@brentvatne if API 21 is not supported please close this issue and refresh the supported android versions found here:
https://docs.expo.dev/versions/latest/

**Comment by hunwalk** [comment]
@brentvatne please

**Comment by lukmccall** [comment]
Hello @hunwalk, thank you for your report. Unfortunately, I was unable to replicate the behavior that was reported. However, I did discover that Flipper is incompatible with API 21. If you have that installed, it may lead to issues.

I'll close that issue for now, but feel free to create a new one with more information to help us reproduce it. It may only affect some Android devices.
