### ISSUE TITLE
[Android] Recording video with `{mute: true}` option without audio permission throws exception

### ISSUE THREAD

**Issue by graszka22** [expo/expo#23127]
### Minimal reproducible example

https://snack.expo.dev/@blimpapp/basic-camera-usage

### Summary

I'm trying to record a video without audio using `expo-camera` like this:
`cameraRef.current.recordAsync({mute: true})` 

Expected behaviour:
Recording starts without exception - I shouldn't need audio permission because I'm not recording audio

Actual behaviour:
Call throws an exception:
```
Unhandled promise rejection Error: "Call to function 'ExponentCamera.record' has been rejected.
→ Caused by: Missing permissions: android.permission.RECORD_AUDIO" in Error: Call to function 'ExponentCamera.record' has been rejected. << → Caused by: Missing permissions: android.permission.RECORD_AUDIO <<     at construct (native) <<     at apply (native)
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/Projects/blimp-reactnative/node_modules/.bin/yarn
      npm: 9.6.7 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/angelikaserwa/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.11 => 0.71.11
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.0
    Expo Workflow: bare

**Comment by hirbod** [comment]
Actually, the fix for this is quite simple.

https://github.com/expo/expo/blob/main/packages/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt#L85-L87

Changing that to

```kotlin
AsyncFunction("record") { options: RecordingOptions, viewTag: Int, promise: Promise ->
      if (!options.muteValue && !permissionsManager.hasGrantedPermissions(Manifest.permission.RECORD_AUDIO)) {
        throw Exceptions.MissingPermissions(Manifest.permission.RECORD_AUDIO)
      }
      ...
}
```

should do the trick. Let me test that real quick

**Comment by alanjhughes** [comment]
@hirbod Yes that will work. You'll also need to change the field name in `RecordingOptions` to `mute`

**Comment by hirbod** [comment]
Yeah, just figured that. I've compared the `record` function in ExpoCameraView.kt and it was named `options.muteValue`, was a bit confused

**Comment by hirbod** [comment]
https://github.com/expo/expo/blob/main/packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.kt#L168

I might miss something, but why is it called muteValue here?

**Comment by alanjhughes** [comment]
I'd prefer it to be named `recordAudio` so we wouldn't need to negate it passing it to the cameraView 🤷‍♂️

**Comment by hirbod** [comment]
If I get this right, this should be a bug right now.
Docs state this value is called [mute](https://docs.expo.dev/versions/latest/sdk/camera/#camerarecordingoptions) but we're looking for `muteValue`, which doesn't seem to be set anywhere. So that flag should actually not even work right now, right?

Also agree with the negate part, but that would be a BC.

**Comment by alanjhughes** [comment]
Yes it's a bug. It should have always been `mute` unless renamed through the annotation. Probably one of the earliest modules that was migrated

**Comment by hirbod** [comment]
Ok, preparing PR

**Comment by hirbod** [comment]
Here we go https://github.com/expo/expo/pull/23145
