### ISSUE TITLE
[iOS] Preview flickering and darkened videos on iOS when recording video

### ISSUE THREAD

**Issue by graszka22** [expo/expo#23130]
### Minimal reproducible example

https://snack.expo.dev/@blimpapp/black-frames-example

### Summary

When starting a video recording the preview flickers black and sometimes the first frames of the result video are darkened or even black. I've found the similar issue here: https://github.com/expo/expo/issues/1057 but none of the workarounds work for me. I also tried patching with this PR: https://github.com/expo/expo/pull/16290/files but this didn't work too. 

I've tried debugging it a bit and it is possible that the flickering happens here:
```
- (void)setupMovieFileCapture
{
  AVCaptureMovieFileOutput *movieFileOutput = [[AVCaptureMovieFileOutput alloc] init];

  if ([_session canAddOutput:movieFileOutput]) {
    [_session addOutput:movieFileOutput];
    _movieFileOutput = movieFileOutput;
  }
}
```
Maybe this function should be called earlier, not just before starting the recording? `react-native-visual-camera` calls this when setting props, not starting the recording.

Expected behaviour:
- the preview doesn't flicker black
- the first frames of the resulting video are not darkened

Actual behaviour: 
- the preview flickers black when starting the video
- the first frames of the resulting video are sometimes darkened or even black

I'm also attaching a result video. You can see that the first frames are darkened.

https://github.com/expo/expo/assets/6280457/f7e5f39f-6ae2-4e4b-b2aa-488dd252c145

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/Projects/blimp-reactnative/node_modules/.bin/yarn
      npm: 9.6.7 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/angelikaserwa/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.11 => 0.71.11
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.0
    Expo Workflow: bare

**Comment by Kieraano** [comment]
Links to previous discussions reporting this issue:
https://github.com/expo/expo/issues/1057
https://github.com/expo/expo/issues/17884
https://github.com/expo/expo/issues/18202
https://github.com/expo/expo/issues/18234

Seems like the video recording of Expo Camera has been glitched on iOS since 2017.
