### ISSUE TITLE
nestedScrollEnabled

### ISSUE THREAD

**Issue by machester4** [expo/expo#2313]
Is this ScrollView property working?

Example
https://snack.expo.io/rJ6Ah6st7

**Comment by EvanBacon** [comment]
The `ScrollView` prop [`nestedScrollEnabled`](https://docs.expo.io/versions/v30.0.0/react-native/scrollview#nestedscrollenabled)

> Enables nested scrolling for Android API level 21+. Nested scrolling is supported by default on iOS.

This means it is **Android only** and that Android device must be running API 21+

**Source:**
https://github.com/facebook/react-native/blob/4ac500a337572996c4a822c3433da3e4297cf138/Libraries/Components/ScrollView/ScrollView.js#L270-L275
