### ISSUE TITLE
[iOS][expo-screen-orientation] EXDefaultScreenOrientationMask not applied in EAS Development Build with DEFAULT plugin config

### ISSUE THREAD

**Issue by ryl** [expo/expo#23141]
### Minimal reproducible example

https://github.com/ryl/orientation-test

### Summary

# Expected Behavior

In an iOS project, adding `expo-screen-orientation` with `"initialOrientation": "DEFAULT"` and running `npx expo run:ios` should update orientation when a device or simulator is rotated.

# Actual Behavior

In an EAS developer build the screen does not update as the device is rotated.

# Details

Adding `expo-screen-orientation` to an iOS project and adding the [documented configuration](https://docs.expo.dev/versions/latest/sdk/screen-orientation/#example-appjson-with-config-plugin) along with `"orientation": "default"` (or totally removing that line) in `app.json` works with Expo Go, but fails in an EAS development build.

Adding this [documented manual configuration](https://github.com/expo/expo/tree/sdk-48/packages/expo-screen-orientation#configure-for-ios) to `Info.plist` fixes the problem seen in the EAS Build.

```
<key>EXDefaultScreenOrientationMask</key>
<string>UIInterfaceOrientationMaskAllButUpsideDown</string>
```

However, having to manually add this configuration seems counter to the [prebuild strategy of using configuration plugins](https://docs.expo.dev/workflow/prebuild/#usage).

> This creates the android and ios directories for running your React code. If you modify the generated directories
> manually then you risk losing your changes the next time you run npx expo prebuild --clean. Instead, you should create
> config plugins — functions that perform modifications on native projects during prebuild.

This is especially problematic if you follow the [advice of adding `ios` and `android` to `.gitignore`](https://docs.expo.dev/workflow/prebuild/#clean).

> The purpose of the prompt is to encourage managed workflow users to
> `add the android and ios directories to the project's .gitignore`,
> ensuring that the project is always managed. However, this can make
> custom config plugins harder to develop so we  haven't introduced any
> mechanism to enforce this behavior.

# Possible Cause

It looks like the configuration plugin completely removes the `EXDefaultScreenOrientationMask` key when `"initialOrientation": "DEFAULT"` is used, despite the key appearing to be necessary for EAS developer builds to work.

https://github.com/expo/expo/blob/sdk-48/packages/expo-screen-orientation/plugin/src/withScreenOrientation.ts#L63-L64

```
  if (initialOrientation === 'DEFAULT') {
    delete infoPlist[INITIAL_ORIENTATION_KEY];
```

Without the `EXDefaultScreenOrientationMask` key things like `ScreenOrientation.addOrientationChangeListener` never fire their callbacks.

This may affect https://github.com/expo/expo/issues/15009

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/ryl/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0
        System Images: android-26 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.12.0
    Expo Workflow: managed
```

**Comment by jimmihagenTrifecta** [comment]
I can confirm that this happens, I don't want to talk about the time wasted trying to get it working. Would LOVE to see this fixed! Thank you for the excellent bug report and workaround. 

			"infoPlist": {
				"EXDefaultScreenOrientationMask": "UIInterfaceOrientationMaskAllButUpsideDown"
			}
			
this added to our app.json works around the issue, but we would never have thought to do this, of course...

**Comment by jimmihagenTrifecta** [comment]
> I can confirm that this happens, I don't want to talk about the time wasted trying to get it working. Would LOVE to see this fixed! Thank you for the excellent bug report and workaround.
> 
> ```
> 		"infoPlist": {
> 			"EXDefaultScreenOrientationMask": "UIInterfaceOrientationMaskAllButUpsideDown"
> 		}
> ```
> 
> this added to our app.json works around the issue, but we would never have thought to do this, of course...

to update, we're not finding the workaround to be usable in our Expo managed project - the info.plist entry just isn't made unless you do it manually in a bare project, from what we can tell

**Comment by jimmihagenTrifecta** [comment]
workaround above works great in simulator, but doesn't seem to hold when done to managed projects, unless we're just not doing it quite right.

**Comment by ryl** [comment]
@jimmihagenTrifecta I tried the `infoPlist` property, too, but it didn't seem to work for me. Whenever I use `"initialOrientation": "DEFAULT"` it seems to scour that property from the Plist, even if its been added to `intoPlist` in app.json. I'm mostly running my app via the `npx expo run:ios` command.

**Comment by behenate** [comment]
@ryl Thanks for an excellent bug report! The config plugin has been fixed in the PR above 🙂
