### ISSUE TITLE
Expo cli iOS run issue

### ISSUE THREAD

**Issue by thatsbrandon** [expo/expo#23159]
### Summary

Unable to compile my application without the following error. This comes down to a cache problem which i've been pulling my hair out for hours trying to solve.

On Apple M1 Pro
```
could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/brandon/Library/Developer/Xcode/DerivedData/mobile-fweweeiutbaxeggaxnyoseycnuft/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
```

### What platform(s) does this occur on?

iOS

### SDK Version

48.0.18

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.7 => 0.18.12 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 6.3.8
    Expo Workflow: bare

### Minimal reproducible example

Ran these following steps after I added a new package that needed a full rebuild, but now I am running into a `ExpoModulesCore` error, which I've never seen before.

```
watchman watch-del-all
rm -rf yarn.lock package-lock.json node_modules
rm -rf android/app/build
rm ios/Pods ios/Podfile.lock 
rm -rf ~/Library/Developer/Xcode/DerivedData
npm install && cd ios && pod update && cd ..
npm run ios
```

**Comment by Mohamed-kassim** [comment]
@Red3nzo did you find any solution?
