### ISSUE TITLE
When using metro bundler for web the endpoint /json stops working

### ISSUE THREAD

**Issue by TNAJanssen** [expo/expo#23188]
### Summary

When you enable the Metro bundler for Expo web, it disables the /json endpoint that tools like Flipper use to start the debugger.

This makes it hard to debug React Native applications.

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
      Yarn: 3.6.0 - ~/.nvm/versions/node/v20.0.0/bin/yarn
      npm: 9.6.5 - ~/.nvm/versions/node/v20.0.0/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: * => 0.7.1
      expo: * => 48.0.19
      react: * => 18.2.0
      react-dom: * => 18.2.0
      react-native: * => 0.71.8
      react-native-web: * => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.7
    Expo Workflow: managed

### Minimal reproducible example

Create a new expo app, set the bundler to "metro", run npx expo start, go to http://localhost:8081/json and see the initial page instead of the json of devices.

**Comment by Kudo** [comment]
#23197 should resolve the issue
