### ISSUE TITLE
[expo-modules][Android] - Single expo-modules library increases Android boot time by 2-2.5s

### ISSUE THREAD

**Issue by hirbod** [expo/expo#23189]
### Minimal reproducible example

https://github.com/intergalacticspacehighway/android-perf-test

### Summary

We have been debugging the slow startup performance of our Android app. Essentially, we maintained a single View and uninstalled numerous packages. Eventually, we discovered that the use of just a single library with expo-modules is enough to cause a boot delay on Android of at least _2-2.5 seconds._ **No impact on iOS**

How to reproduce:

Checkout the repo

```bash
yarn && yarn run android --variant Release
```

Measure the boot, then remove expo-blur and generate a new release. The startup performance should improve after removing expo-blur. The issue appears to be coming from the new expo modules API, as similar problems have been observed with other expo-* packages as well

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 3.5.0 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: bare
```

**Comment by Kudo** [comment]
thanks for this great issue report and repro. i'll keep the investigation. in the meantime, as far as i know, @lukmccall did some module lazy loading improvement after sdk 48, so it would be good to try out sdk 49 and see whether it helps.

**Comment by hirbod** [comment]
@Kudo SDK49 doesn't seem to change the change the delay, seems like it improves mount performance though. Looking through the code the lazy changes seem to happen at a later stage, not at boot time. Correct me if I am wrong.

**Comment by Kudo** [comment]
may i ask how you measure the boot time?

**Comment by hirbod** [comment]
Just with a stop-clock. (and video recordings, comparing side-by-side after pressing the button)

**Comment by hirbod** [comment]
@Kudo here is a video recorded on a 695 snapdragon and 8GB of ram
<video src="https://github.com/expo/expo/assets/504909/d1f0ed45-7cad-437d-9345-0ab470c79c89" width="1920" height="1080"></video>

So with this more decent device, the difference is more like 1.5s, but on worse devices like a Samsung A13 or Redmi 7, the difference is more 2-2.5s.

We tested with SDK 48 and 49, there is no difference.

**Comment by Kudo** [comment]
thanks @hirbod for the great info and videos. i could differentiate the performance and have some thought of bottleneck. will discuss this with the team further.

**Comment by matt-42** [comment]
In case it helps, here is a bit of benchmark I did tonight. It shows a 10x slowdown between expo45 and expo49. I attached a video showing expo 45-46-47-48-49(beta5) apps side by side starting the blank template on a huawei p20 with the following packages installed: 

```
npx expo install expo-application expo-asset expo-av expo-build-properties expo-constants expo-dev-client expo-document-picker expo-file-system expo-font expo-gl expo-graphics expo-haptics expo-image expo-image-manipulator expo-keep-awake expo-linear-gradient expo-linking expo-location expo-screen-orientation expo-sharing expo-splash-screen expo-status-bar expo-three```

(only 47 and 48 have expo-image installed)

Here are the times the apps take to display the text:
expo45: 0.28s
expo46: 0.64s
expo47: 0.56s
expo48: 0.92s (~3x slower than expo45)
expo49: 2.96s (10x slower than expo45)

https://github.com/expo/expo/assets/846584/89c64f4f-06e8-4e1b-b2c1-c3f8c7f1aa76

**Comment by hirbod** [comment]
Shall I open a new issue for the status bar finding @lukmccall. See my video and messages before

**Comment by brentvatne** [comment]
@hirbod - yes please
