### ISSUE TITLE
Can not view image on android 8.1

### ISSUE THREAD

**Issue by mkloar** [expo/expo#2319]
Hey!

I'm developing my app with expo (exp start). My images is stored in projectFolder/appKit/*...
When I opened application in my android emulator android 6.0 my images is visible, but when I switch to emulator with android 8.1 I don't see these images.

The problem is, I don't see specific image, other images is visible in both versions of android. 

How I import these image which I can not see. I don't see image "appGradientSmall", Artboard1@4xwithout.png is visible...
```
<ImageBackground
                style={{width: '100%',height: 180,zIndex:-1,justifyContent: 'center',opacity: 1
              }}
                source={require('../../appKit/appGradientSmall.png')}>
              
             
                <View style={{flexDirection: 'row', opacity: 5}}>
                  <Text adjustsFontSizeToFit minimumFontScale={.3} style={styles.notificationText}>Some info</Text>
                  <Image 
                    style={{width: 120,height: 120,marginLeft: 'auto',marginRight: 'auto', opacity: 1}}
                    source={require('../../appKit/Artboard1@4xwithout.png')} />
                </View>
               
           
              
              
</ImageBackground>]
```

### Environment

Environment:
  OS: Windows 10
  Node: 10.4.1
  Yarn: 1.9.4
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/egsnotko-7d886cf4-e8b1-4e44-af43-c3eae67c952b.tar.gz

app.json;

"sdkVersion": "27.0.0",

### Actual Behavior

Can not see background image...

![Uploading InkedScreenshot_1538133195_LI.jpg…]()

### Reproducible Demo
It's working in reproducible demo but on simulator and real device it does not...

https://snack.expo.io/Sy3FcFitX

**Comment by EvanBacon** [comment]
What does "It's working in reproducible demo but on simulator and real device it does not..." mean? Is this error only reproducible on your emulator? 🤔

**Comment by mkloar** [comment]
I think the problem is react native version...

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
