### ISSUE TITLE
[SDK 49 beta] expo cli not working great with pnpm

### ISSUE THREAD

**Issue by rvasseur31** [expo/expo#23193]
### Minimal reproducible example

https://github.com/rvasseur31/expo-pnpm

### Summary

Hi !
Thank you for the work you do !

Since the symlinks are available with metro, my team and I want to use pnpm for all projects (monorepo).

My steps: 
- Create a new project or upgrade the project to expo 49 
- Delete yarn.lock / node_modules folder
- Run command `pnpm install`
- Run the command `pnpm dlx expo-doctor` or `npx expo-doctor` => the command failed, here is the result :

```
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✖ Checking dependency versions for compatibility with the installed Expo SDK failed
Issues:
  
Advice:
  • Use npx expo install --check to review and upgrade your dependencies.
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.
```

Note :
The command `npx expo install --check` return `Error: expo must be installed` but the command `pnpm dlx expo install --check` return `Dependencies are up to date`

I don't know if it's normal that npx expo install --check` return `Error: expo must be installed` but `pnpm dlx expo-doctor` or `npx expo-doctor` return the same result

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
        Android NDK: 23.1.7779620
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0-beta.0 => 49.0.0-beta.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.3.2
    Expo Workflow: bare

**Comment by byCedric** [comment]
Might be (partially) fixed by #23220

**Comment by rvasseur31** [comment]
Thanks @byCedric, I will try it when the fix will be published

**Comment by byCedric** [comment]
Also, be aware that full `pnpm` support still needs more fixes. I created [this test repository](https://github.com/byCedric/expo-pnpm-tests/blob/main/ISSUES.md) just to test what we need to fix in order to support `pnpm` fully (with its default `node_modules` structure)

**Comment by byCedric** [comment]
Fix #23220 is released in `expo@49.0.0-beta.4`

**Comment by rvasseur31** [comment]
Thank you for the job you've done !
It's working perfectly now !

Do you have any roadmap on the full pnpm support at expo ?

Should I follow this [repo](https://github.com/byCedric/expo-pnpm-tests/tree/main) to have any updates on the subject ?

**Comment by byCedric** [comment]
@rvasseur31 awesome, great to hear its working on your end! We'll probably announce when we have full pnpm support. But, we need some time to carefully make the fixes required, especially around `expo-modules-autolinking`. (I kind-of yolo'd my way through the issues in the repo I linked).

**Comment by rvasseur31** [comment]
Thanks for the informations !

I'll be delighted to test it out once you announce it. In the meantime, my team and I will continue to use yarn

**Comment by edgarkhanzadian** [comment]
@byCedric hello! First of all, thank you for your work on expo! Are there any updates on pnpm support for expo?

**Comment by sehyeona** [comment]
I attempted to use [expo@50.0.0-alpha] since bug fixes related to pnpm isolation were implemented in the expo alpha version. However, I faced an issue during `pod install` with the message `CocoaPods could not find compatible versions for pod "ExpoApplication"`. 
I'm hopeful that these fixes will be released in a stable version soon. Thank you for your efforts.
