### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Gonsis** [expo/expo#2320]
C:\Users\Dell>npm install -g expo-cli
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! path C:\Users\Dell\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Dell\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\Dell\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\Dell\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\Users\\Dell\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinApi.dll' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\Dell\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinApi.dll\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\Dell\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinApi.dll',
npm ERR!   parent: 'expo-cli' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2018-09-28T11_56_37_770Z-debug.log

**Comment by esamelson** [comment]
Hi @Gonsis - you'll need to open an issue in the [expo-cli repo](https://github.com/expo/expo-cli) instead, and please fill out the template there to the best of your ability. Thanks!
