### ISSUE TITLE
[SDK 49 beta 2] The system cannot find the path specified.

### ISSUE THREAD

**Issue by arasrezaei** [expo/expo#23217]
### Minimal reproducible example

i'm using windows and with starter template i have problem calling expo

### Summary

hi,
after trying sdk 49 beta i got this error calling `expo`,
not matter command, calling expo instance will bump this error:
`The system cannot find the path specified`.

sdk 48 is fine.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20220821.200817.0 - E:\Software\Watchman\bin\watchman.EXE
    npmPackages:
      expo: ^49.0.0-beta.2 => 49.0.0-beta.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
    Expo Workflow: managed

**Comment by jmatsushita** [comment]
I think it's because I'm using openjdk19:
```
> java --version
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment Zulu19.30+11-CA (build 19.0.1+10)
OpenJDK 64-Bit Server VM Zulu19.30+11-CA (build 19.0.1+10, mixed mode, sharing)

> ./gradlew --version

------------------------------------------------------------
Gradle 8.0.1
------------------------------------------------------------

Build time:   2023-02-17 20:09:48 UTC
Revision:     68959bf76cef4d28c678f2e2085ee84e8647b77a

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.1 (Azul Systems, Inc. 19.0.1+10)
OS:           Mac OS X 13.4.1 aarch64

```

[This issue recommends downgrading to jdk 17](https://github.com/react-native-community/cli/issues/1719) but also suggests that in theory react-native should support jdk19 from 0.71 onwards.

**Comment by keith-kurak** [comment]
@arasrezaei Hi - can you confirm what shell you're using (e.g., cmd, PowerShell) and copy/ paste the entire contents of your terminal (including the command run and the output). I am also experiencing an issue on Windows, but the message is quite a bit different. Thanks!

**Comment by arasrezaei** [comment]
> @arasrezaei Hi - can you confirm what shell you're using (e.g., cmd, PowerShell) and copy/ paste the entire contents of your terminal (including the command run and the output). I am also experiencing an issue on Windows, but the message is quite a bit different. Thanks!

Only that message appears.
PowerShell
But no difference

**Comment by valeshgopal** [comment]
same issue
