### ISSUE TITLE
Metro build issues in React Native bare flow

### ISSUE THREAD

**Issue by timothyerwin** [expo/expo#23213]
### Minimal reproducible example

https://github.com/expo/expo/issues/22744

### Summary

This bug has already been reproduced but the solution posted only works specifically for `expo-router` but it is not working in my code.

```
"expo": "^48.0.19",
"expo-blur": "^12.3.0",
"expo-clipboard": "^4.1.2",
"expo-contacts": "^12.0.1",
"expo-crypto": "^12.2.2",
"expo-haptics": "^12.2.1",
"expo-image-manipulator": "^11.1.1",
"expo-image-picker": "^14.1.1",
"expo-in-app-purchases": "^14.1.1",
"expo-location": "^15.1.1",
"expo-modules-autolinking": "^1.2.0",
"expo-sms": "^11.2.1",
"expo-standard-web-crypto": "^1.5.0",
```

```
● Validation Warning:

  Unknown option "serializer.isThirdPartyModule" with value (module) =>
      /(?:^|[/\\])node_modules[/\\]/.test(module.path) was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "symbolicator.customizeStack" with value async (stack, _) => stack was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "unstable_perfLoggerFactory" with value () => {
  class Logger {
    start() {}
    end() {}
    annotate() {}
    point() {}
    subSpan() {
      return this;
    }
  }
  return new Logger();
} was found.
  This is probably a typing mistake. Fixing it will remove this message.

```

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 9.6.4 - /usr/local/bin/npm
      Watchman: 2023.01.23.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/gold/.rvm/rubies/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.2 => 9.3.2
      expo: ^48.0.19 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.11 => 0.71.11
    Expo Workflow: bare

**Comment by brentvatne** [comment]
the error that you encountered here is quite different from the thread you linked to. we can help with a minimal reproducible example :)

**Comment by timothyerwin** [comment]
the warnings confused me...the error was actually something else. I just assumed it was caused by this. issue is closed. thanks.

**Comment by Duell10111** [comment]
@timothyerwin What was the issue on your side?

**Comment by shoonne** [comment]
Need help with this as well

**Comment by Lightining20** [comment]
i had same error     i solved with upgrading react-native    ,   i dont know i used some audit command and my react-native version automatically change   so yahh try to change REAC-NATIVE VERSION.

**Comment by sbhakat1** [comment]
● Validation Warning:

  Unknown option "serializer.isThirdPartyModule" with value (module) =>
      /(?:^|[/\\])node_modules[/\\]/.test(module.path) was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "symbolicator.customizeStack" with value async (stack, _) => stack was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "watcher" with value {"additionalExts": ["cjs", "mjs"], "healthCheck": {"enabled": false, "filePrefix": ".metro-health-check", "interval": 30000, "timeout": 5000}, "unstable_workerThreads": false, "watchman": {"deferStates": ["hg.update"]}} was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "unstable_perfLoggerFactory" with value () => {
  class Logger {
    start() {}
    end() {}
    annotate() {}
    point() {}
    subSpan() {
      return this;
    }
  }
  return new Logger();
} was found.
  This is probably a typing mistake. Fixing it will remove this message.


Can anyone help me to figure out this error to start metro for React Native CLI
