### ISSUE TITLE
Inheriting map components supporting China

### ISSUE THREAD

**Issue by XcXerxes** [expo/expo#2322]
I am a front-end developer in China. I really like expo. It brings me a lot of convenience in developing react-native. I have a request, I hope to consider Chinese developers, can I integrate a map component in China? ? For example, [AMap](https://lbs.amap.com)， I hope it will make more people like it.

**Comment by esamelson** [comment]
Hi @XcXerxes - we track feature requests on [canny](https://expo.canny.io/feature-requests) rather than here. Could you open one there instead? Thanks!
