### ISSUE TITLE
[SDK 49 beta] "No 'projectId' found..." in getExpoPushTokenAsync

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#23225]
### Minimal reproducible example

More than happy to create one, if you think this is a bug and you need a repro

### Summary

I just managed to build my Android app with the beta 49 SDK release.

I call the following lines inside my project.

```
import * as Notifications from 'expo-notifications';
...
Notifications.getExpoPushTokenAsync()
```

Sentry logs the following error message here _Error: No 'projectId' found. If 'projectId' can't be inferred from the manifest (eg. in bare workflow), you have to pass it in yourself._.

I see that [this commit ](https://github.com/expo/expo/commit/47dabd7c6bdfbc318c551fd96a42f3217a608f92#diff-e1445eb35a4ae3d0ce89c49c2437b81ea26b54de97e51a3c48857b74d16125b6)from @wschurman changes the way the projectId is grabbed. 

I inserted a console.log before I call that method:
```
  console.log(Constants.easConfig?.projectId);  // --> undefined
  console.log(Constants.expoConfig?.extra?.eas.projectId);  // --> my project id
```

so it seems like the new Constants.easConfig does not grab the projectId the same way the old approach did. If this is a bug and you need to have a reproducible example, I'll create one. 

I'm aware that I just can pass the projectId to getExpoPushTokenAsync myself - however, its more convenient if expo does it :-).

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.5.0 => 9.5.0 
      expo: ^49.0.0-beta => 49.0.0-beta.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.3.9
    Expo Workflow: bare

**Comment by jamesloper** [comment]
I'm getting the same issue when registering for push notifications.

I think most people will currently have their projectId at `expo.extra.eas.projectId`, is there a new place to put it?

**Comment by wschurman** [comment]
My recommendation is to pass it to `getExpoPushTokenAsync` manually for now. This code is historically very fragile (as you found). You are correct that this isn't enumerating all the cases where the projectId may be in the config. 

I think the code in the module should probably be:
```
const projectId = options.projectId || Constants.easConfig?.projectId || Constants.expoConfig.extra?.eas?.projectId;
```

Will keep this open until I get around to putting up a fix PR, where we should probably audit all uses of `Constants.easConfig` for the same issue.

**Comment by jamesloper** [comment]
This works:

```javascript
const res = await Notifications.getExpoPushTokenAsync({
	'projectId': Constants.expoConfig.extra.eas.projectId,
});
```

**Comment by wschurman** [comment]
Taking another look at this, I'm hesitant to change the code to look in `extra` within `expoConfig`. For managed workflow, local development, and served updates, the project ID is put in `Constants.easConfig?.projectId`. It being in `Constants.expoConfig.extra.eas.projectId` is an implementation detail for EAS CLI but not necessarily a well-typed location of the field. Getting it from there could cause more confusion if it is the incorrect value. Therefore, I think I'll stick to the current implementation. 

The error message `No 'projectId' found. If 'projectId' can't be inferred from the manifest (eg. in bare workflow), you have to pass it in yourself` is accurate for bare workflows. All other cases should have `Constants.easConfig?.projectId`. If one doesn't, then that's a bug.

@RRaideRR - it looks like you are using the bare workflow, so the project ID should be passed in manually. (@jamesloper's solution works or can just hardcode it as well, the project ID is a constant)

**Comment by RRaideRR** [comment]
Hey @wschurman ,

for local development I'm using `npx expo run:ios`. However, for my prod builds, I'm using an EAS build which is - if I'm not mistaken - managed.

If I understand you correctly, I should open up a new issue if in my "managed" environment, `Constants.easConfig?.projectId` is `undefined` - even though I have defined it - right?

**Comment by wschurman** [comment]
@RRaideRR - in this issue summary Environment report it says `Expo Workflow: bare`. EAS Build can build any project, including bare projects. What bare means is that the `android`/`ios` directories have been ejected/prebuilt. 

That being said, the bug still may exist even for managed. If it is able to be repro'd on a blank project (create project, `eas init`, add expo-notifications, `eas build`) then we should re-open this issue. I can try this in a bit, or if you are able to try it that would help, too.

**Comment by RRaideRR** [comment]
Still not 100% sure what bare means tbh. (I _really_ want to understand). 

The [expo docs](https://docs.expo.dev/bare/hello-world/) are saying: A bare React Native app is a project where developers make direct changes to their native android and ios project directories rather than continuously generating them on demand using the [app config (app.json) and prebuild](https://docs.expo.dev/workflow/prebuild/).

I'm using `npx expo prebuild` (which is according to the above definition not `bare`). According to your definition it is `bare`because I prebuilt. Apparently, also `npx expo-env-info` defines it as bare, when it finds an iOS and Android folder.

😕 (<-- this is me being confused)

I try to give you a repro tomorrow or the day afterwards.

**Comment by yerevin** [comment]
@RRaideRR 
`bare` - you pass `android` and `ios` directories to EAS build, so it then skip `prebuild` step in build process (you can check it in progress logs)
![image](https://github.com/expo/expo/assets/14888704/ba1a82cb-5203-4d81-b529-24383904ca21)

`managed` - you don't pass own `android` and `ios` directories to EAS build and they are generated with `prebuild` in build process base on your configuration in app config

**Comment by RRaideRR** [comment]
Thanks @yerevin for the heads up - I appreciate that :-).

So I am using a managed workflow - I also checked my corresponding EAS logs - definitely managed.

However, I cannot reproduce this with a freshly created project which uses just expo-constants (and not expo-notifications). 

I'll upgrade my project in 3-4 weeks to SDK49 and then I'll see if the error still occurs. If it does, I'll try to track it down further. For now - this can be stay closed :-).

**Comment by nandorojo** [comment]
Is anyone else getting this on SDK 49 with `expo` v49.0.3?

**Comment by webdevmario** [comment]
Yes, happening on 49.0.6 for me.

**Comment by nandorojo** [comment]
> This works:
> 
> 
> 
> ```javascript
> 
> const res = await Notifications.getExpoPushTokenAsync({
> 
> 	'projectId': Constants.expoConfig.extra.eas.projectId,
> 
> });
> 
> ```

This worked for me (after putting my project ID manually in my app.config.js file 🤷‍♂️)

**Comment by BrodaNoel** [comment]
Question: Does this "error" creates any problem/bug?

**Comment by jamesloper** [comment]
Hahahaha yes if you manage to push to production with this error still happening your push tokens will just stop registering. It's critical to use the workaround if you want to keep using expo notifications

**Comment by cameronmurphy** [comment]
Hit this problem too. Why is this issue closed? The docs don't say to pass `{ projectId: Constants.expoConfig.extra.eas.projectId }` to `Notifications.getExpoPushTokenAsync` but that seems like the only workaround right now?

**Comment by bassg0navy** [comment]
> Hit this problem too. Why is this issue closed? The docs don't say to pass `{ projectId: Constants.expoConfig.extra.eas.projectId }` to `Notifications.getExpoPushTokenAsync` but that seems like the only workaround right now?

That was the only thing that worked for me. At a minimum, it seems documentation should reflect _projectId_ as a required parameter now with SDK 49+.

**Comment by Asekon** [comment]
i thought this issue would only impact bare workflows. but my notifications stopped functioning when i pushed to production with the new sdk. It was working fine on development though (expo go)

**Comment by wschurman** [comment]
> I'm developing a local app NOT deployed using EAS. I'm also using SDK49. I received this error attempting to implement push notifications. I've never been aware of or configured a projectId. I don't see one listed in manifest (app.json). Should this be a default value I can grab somewhere? I didn't see a projectId key when checking values exposed at Constants.manifest2 either.

The EAS project ID is required if it cannot be inferred. When not using EAS build or EAS update, the project ID is the value that is found at https://expo.dev/accounts/[account]/projects/[project] . If you haven't ever created a project, one will need to be created using `eas init` (which will put it in your app.json).

For other bare projects I recommend just either hardcoding the ID (putting the UUID directly in the code) or passing `{ projectId: Constants.expoConfig.extra.eas.projectId }` as others have mentioned if your config has it from having run `eas init`. 

The reason for all of this is that Expo Push Notifications needs to know how to identify your project. Historically we allowed identification using `accountName/projectSlug` which could be inferred but wasn't durable (can be mutated), so we switched to requiring projectId over the course of a few SDK versions. So, the requirement is that an app must identify itself to Expo Notifications (EAS) by using the EAS project ID.

**Comment by bassg0navy** [comment]
Thanks @wschurman, I was unaware of that change and the reason behind it. 
This was 100% the fix for my issue. I didn't even have eas-cli installed, but all is well now 👍🏽

**Comment by CCB-cerivera** [comment]
In my case I use SDk49 with "expo-notifications": "~0.20.1", in android it works very well, but in iOS it doesn't work, does anyone have an idea? It does not generate any error, it just stays in the await without doing anything.

**Comment by CCB-cerivera** [comment]
> 

did you manage to solve it?

**Comment by vladivanciu** [comment]
> In my case I use SDk49 with "expo-notifications": "~0.20.1", in android it works very well, but in iOS it doesn't work, does anyone have an idea? It does not generate any error, it just stays in the await without doing anything.

Same issue here

**Comment by BrodaNoel** [comment]
```
const tokenResponse = await Notifications.getExpoPushTokenAsync({
  projectId: Constants.expoConfig.extra.eas.projectId,
});
```

Then, in app.json, define:
```json
{
  "expo": {
    "extra": {
      "eas": {
        "projectId": "xxxxxxxxxx-xxxx-xxxxx-xxxxxxx-xxxxxxx"
      }
    },
  }
}
```

**Comment by vladivanciu** [comment]
> ```
> const tokenResponse = await Notifications.getExpoPushTokenAsync({
>   projectId: Constants.expoConfig.extra.eas.projectId,
> });
> ```
> 
> Then, in app.json, define:
> 
> ```json
> {
>   "expo": {
>     "extra": {
>       "eas": {
>         "projectId": "xxxxxxxxxx-xxxx-xxxxx-xxxxxxx-xxxxxxx"
>       }
>     },
>   }
> }
> ```

It's implemented but still not working.
Working fine on Android but on iOS getExpoPushTokenAsync is not responding.

**Comment by CCB-cerivera** [comment]
> > ```
> > const tokenResponse = await Notifications.getExpoPushTokenAsync({
> >   projectId: Constants.expoConfig.extra.eas.projectId,
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, in app.json, define:
> > ```json
> > {
> >   "expo": {
> >     "extra": {
> >       "eas": {
> >         "projectId": "xxxxxxxxxx-xxxx-xxxxx-xxxxxxx-xxxxxxx"
> >       }
> >     },
> >   }
> > }
> > ```
> 
> It's implemented but still not working. Working fine on Android but on iOS getExpoPushTokenAsync is not responding.
> 
> This is happening after upgrading expo.

The only option that worked for me was to use RNFirebase combined with EXPO, however, I want to ask you, have you found a solution?

**Comment by vladivanciu** [comment]
> > > ```
> > > const tokenResponse = await Notifications.getExpoPushTokenAsync({
> > >   projectId: Constants.expoConfig.extra.eas.projectId,
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then, in app.json, define:
> > > ```json
> > > {
> > >   "expo": {
> > >     "extra": {
> > >       "eas": {
> > >         "projectId": "xxxxxxxxxx-xxxx-xxxxx-xxxxxxx-xxxxxxx"
> > >       }
> > >     },
> > >   }
> > > }
> > > ```
> > 
> > 
> > It's implemented but still not working. Working fine on Android but on iOS getExpoPushTokenAsync is not responding.
> > This is happening after upgrading expo.
> 
> The only option that worked for me was to use RNFirebase combined with EXPO, however, I want to ask you, have you found a solution?

Not yet. As a workaround, I'm building the application for Android with SDK 49 and for iOS I'm still using SDK 46 in order to keep the notifications working.

**Comment by CCB-cerivera** [comment]
> 

I am trying an option with android, since with iOS I solve it with RNFirebase, however android is corrupted when using the @react-native-firebase/messaging library "and on android it worked for me with expo", if you like to solve it I will share it for those who have the problem with expo SDK49. Now in your case, if you do not have native development you could apply an eject or prebuild to see if it solves your problem, if you have native code do not do it because this deletes and reconfigures the android and ios folders.

**Comment by christopherwalter** [comment]
@vladivanciu can you let me know which version of `expo-notifications` you're running? 

If you're using SDK 49 (`"expo": "~49.0.10"` in package.json) then the compatible version of `expo-notifications` should be `~0.20.1`. 

Let me know if that's the case, and if you're still seeing issues when calling `getPushTokenAsync`.

**Comment by gladder82** [comment]
Seems like this is not a bug - it's intentional: https://github.com/expo/expo/blob/0ed37ab9c18ce3165ae542c50f6b7d5ef1ba5790/packages/expo-notifications/src/getExpoPushTokenAsync.ts#L59

**Comment by nandorojo** [comment]
Is it documented?

**Comment by gladder82** [comment]
@nandorojo the documentation (https://docs.expo.dev/versions/latest/sdk/notifications/) states that setting this value is recommended (not required):
[...]
When using EAS Build, this value is automatically set. However, it is recommended to set it manually.
[...]
So maybe they did not update the documentation after releasing SDK 49 where setting this value now seems to be required from code perspective.

**Comment by brimby** [comment]
Why does this seem like such an absurd fumble, and yet being handled in such a blasé manner? We've got a) a critical failure of a nearly universal feature (notifications), b) it's sneaky in that it only fails in production, c) it was seemingly caused by a depreciation that was never announced, d) the docs don't reflect anything about it, e) the source of the bug is EAS (an expo product) putting the projectId in a place expo doesn't look for, and yet apparently that's intended because it's not going to be fixed?

> Taking another look at this, I'm hesitant to change the code to look in extra within expoConfig.

I mean sure, I'll do the workaround. But this just makes me paranoid that at any given moment my notifications are going to bone out on me in some unannounced, undocumented, prod-only way.

**Comment by jamesloper** [comment]
It's a common practice. The expo team is busy working on the biggest issues they think will move the needle. And this issue has a workaround. It makes perfect sense to me that they would choose to work on something else. The reality is that issues like this are often ignored for long times. I wrote an [article on this phenomenon](https://jamesloper.com/iteration).

**Comment by rboy0509** [comment]
try "eas init" and reload project

**Comment by pagecow** [comment]
If you revert back to expo-notifications version 0.18.1, this error goes away. 

I think for the versions after that, the Expo team accidentally took out the internal { projectId: Constants.expoConfig.extra.eas.projectId } functionality and now you have to manually put it in. In version 0.18.1, it did it automatically.

**Comment by JovanSr** [comment]
I've been developing an app from expo SDK 41 in bare workflow.
I get undefined for Constants.easConfig?.projected || Constants.expoConfig.extra?.eas?.projected
How do I manually find which projectId should the function use?

**Comment by wschurman** [comment]
Going to close out this issue as the recommended approach of hard-coding the EAS project ID in the `projectId` param of `getExpoPushTokenAsync` (as is documented: https://docs.expo.dev/versions/latest/sdk/notifications/) is the official way that this should be accomplished and the supported method (for those experiencing issues with it being inferred). While other solutions may work for some, they don't seem to work for all across the board, so the hardcoding is the only method that is guaranteed to work for everyone and is why it is documented.

The project ID can be retrieved from the Expo website on the project page: https://expo.dev/accounts/[account]/projects/[project]/

See my previous comments as well for more context: https://github.com/expo/expo/issues/23225#issuecomment-1696196935

I apologize for any thrash this may have caused.

**Comment by mattkrebs2000** [comment]
> This works:
> 
> ```js
> const res = await Notifications.getExpoPushTokenAsync({
> 	'projectId': Constants.expoConfig.extra.eas.projectId,
> });
> ```

Does this snippet go in App.js?

**Comment by gladder82** [comment]
@mattkrebs2000 yes, or any other place in your app where you want to get the token. This is valid for managed workflow, Not Sure for bare workflows because i do only use managed Workflow

**Comment by jameswilddev** [comment]
I found that `Constants.expoConfig` was always null, both in Expo Go builds and EAS builds.  I ended up just copying the project ID in here as a constant.  Not ideal, but I need notifications to work unfortunately.  Not sure why this was marked as closed, seems people are still having widespread issues with this!

**Comment by serranoarevalo** [comment]
Not sure why the documentation isn't more clear on this.

Here's how to get a "projectId":

1) Create an account at: https://expo.dev/signup
2) `npm install -g eas-cli`
3) `eas login`
4) `eas init`
5) "projectId" will appear in your app.json

**Comment by bradjones1** [comment]
I have opened https://github.com/expo/expo/pull/33359 to make the fallback handle the most common location for this ID, even if it "should" be provided directly. There's no particular reason why this should fail so insidiously for most users who depended on it working out of the box in prior SDK versions.

**Comment by bradjones1** [comment]
https://github.com/expo/expo/pull/33359 was merged into `main` and should avoid this WTF for many users.

**Comment by sharabhh** [comment]
Had the same issue in expo-go app working with SDK 52, I just had to install `eas-cli` and run `eas init` and it fixed my bug. I was using a expo managed workflow
