### ISSUE TITLE
[SDK 49 Beta] expo-image 1.3.1 EAS build error

### ISSUE THREAD

**Issue by kdenz** [expo/expo#23231]
### Minimal reproducible example

install SDK 49 and expo-image, then run eas build --ios --local

### Summary

It's giving me this error during pod install step
```
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "SDWebImageAVIFCoder":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     ExpoImage (from `../node_modules/expo-image/ios`) was resolved to 1.3.1, which depends on
[INSTALL_PODS]       SDWebImageAVIFCoder (~> 0.10.0)
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `SDWebImageAVIFCoder (~> 0.10.0)`.
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 3.3.1 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 9.7.1 - ~/.nvm/versions/node/v18.13.0/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/kmac/.rvm/rubies/ruby-2.6.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0-beta.2 => 49.0.0-beta.2
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.0 => 0.72.0
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.14.0
    Expo Workflow: managed

**Comment by winterOmii** [comment]
me too,but CocoaPods could not find compatible versions for pod "SocketRocket"
