### ISSUE TITLE
[Android][SDK 49 beta] Could not set unknown property 'classifier'

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#23248]
### Minimal reproducible example

https://github.com/mariomurrent-softwaresolutions/expo-sdk-49-beta-dynamic-app-icon-issue

### Summary

The following error is thrown during EAS build: Could not set unknown property 'classifier' for task ':expo-dynamic-app-icon:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

I guess this can only be solved from the library creator right?

### Environment

 npx expo-env info actually delivers no information. Just an empty line

**Comment by Kudo** [comment]
hi there! please help to report the issue to expo-dynamic-app-icon for the gradle8 migration: https://expo.fyi/expo-modules-gradle8-migration. or you could also use patch-package to fix it locally. thanks!

**Comment by mariomurrent-softwaresolutions** [comment]
@Kudo I actually followed the migration guide, but I'm getting the following error when changing the build gradle:
` It is too late to modify singleVariants`
