### ISSUE TITLE
[Android][SDK 49 beta] Could not set unknown property 'classifier' 

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#23246]
### Minimal reproducible example

I can provide one if necessary

### Summary

The following error is thrown during EAS build: ` Could not set unknown property 'classifier' for task ':expo-dynamic-app-icon:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.
`

I guess this can only be solved from the library creator right?

### Environment

Since SDK49 this command does not detect the app.json configuration file

**Comment by swalih-mohammed** [comment]
[stderr] 
FAILURE: Build completed with 2 failures.

[stderr] 
1: Task failed with an exception.

[stderr] 
-----------

[stderr] 
* Where:

[stderr] 
Build file '/home/expo/workingdir/build/node_modules/expo-device/android/build.gradle' line: 40

[stderr] 
* What went wrong:

[stderr] 
A problem occurred evaluating project ':expo-device'.

[stderr] 
> Could not set unknown property 'classifier' for task ':expo-device:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

i am getting this after updating to SDK 49

**Comment by bkamrani** [comment]
Thank you for opening this. I have a similar issue with the following error. There is also the build link for Expo team. 

[Link to a build](https://expo.dev/accounts/onrun/projects/onruncurrent/builds/3e5c76d1-9a70-4e54-bf67-026a93042714)

`[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr]-----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/node_modules/expo-analytics-amplitude/android/build.gradle' line: 40
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':expo-analytics-amplitude'.
[stderr] 
[stderr] Could not set unknown property 'classifier' for task ':expo-analytics-amplitude:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.`

**Comment by mariomurrent-softwaresolutions** [comment]
I think expo-analytics-amplitude should not be used anymore. The repo is archived.

Check out https://docs.expo.dev/guides/using-analytics/ On how to use amplitude analytics
