### ISSUE TITLE
`ios.splash.dark` not working 

### ISSUE THREAD

**Issue by cip123** [expo/expo#23254]
### Minimal reproducible example

https://github.com/cip123/expo-dark-splash-screen-bug

### Summary

I have installed `npx expo install expo-system-ui`, changed the iOS simulator do dark mode  and configured the `app.config.js` as following:

```
 ios: {
      splash: {
        image: "./assets/splash.png",
        resizeMode: "contain",
        backgroundColor: "#ffffff",
        dark: {
          image: "./assets/logo.png",
          resizeMode: "contain",
          backgroundColor: "#000000",
        },
      },
    }
```

but only the light splashscreen is showing. 

I am surprised I didn't find a bug filled for it yet since it looks like it affects lots of people. 

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 Linux Mint 21.1 (Vera)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.3/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v14.21.3/bin/npm
```

**Comment by byCedric** [comment]
Hi @cip123! In Expo Go, the splash screen seems limited to light mode. But, when using `expo-dev-client` or a plain React Native build, it should pick up dark mode as you describe it.

> I noticed your example repo does not contain the `ios.splash.dark` settings.

Your `app.json` should contain the following code, with all other settings of course.

```json
{
  "expo": {
    "userInterfaceStyle": "automatic",
    "ios": {
      "splash": {
        "backgroundColor": "#ffffff",
        "image": "./assets/splash.png",
        "resizeMode": "contain",
        "dark": {
          "backgroundColor": "#000000",
          "image": "./assets/splash.png",
          "resizeMode": "contain"
        }
      }
    }
  }
}
```

> This example uses the default splash screen image, which is transparent and works for both dark and light backgrounds. But, you can change the actual image displayed based on dark/light modes.

Once you run the following steps, your dark mode splash screen should pop up:
- _Set device in dark mode_
- `$ yarn create expo ./expo-dark-splash -t blank@beta`
- `$ cd ./expo-dark-splash`
- _Update **app.json** to include above content_
- `$ yarn expo prebuild -p ios`
- `$ yarn expo run:ios`

Hope this helps!
