### ISSUE TITLE
[SDK 49 beta][docs] Migration guide for Kotlin 8 

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/expo#23257]
### Summary

Could it be, that the `publishing` option should be in the android section of the build.gradle?
I tried it, but it does not work if I put it in the section (afterEvaluate) like it is described in your migration guide.

I moved the `publishing` option to the root android section and everything works as expected.

### Link to the related docs page

https://github.com/expo/fyi/blob/main/expo-modules-gradle8-migration.md

**Comment by Kudo** [comment]
hi there! is it possible to share your whole build.gradle file?

**Comment by mariomurrent-softwaresolutions** [comment]
Hi, sure you can find it here: https://github.com/outsung/expo-dynamic-app-icon/pull/10/files#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65a

**Comment by Kudo** [comment]
hi @mariomurrent-softwaresolutions, thanks for the sharing. yes, the `publishing` should be inside the android section. from the migration guide, it is in the new diff section though.

```diff
--- a/modules/tester/android/build.gradle
+++ b/modules/tester/android/build.gradle
@@ -35,19 +35,11 @@ buildscript {
   }
 }

-// Creating sources with comments
-task androidSourcesJar(type: Jar) {
-  classifier = 'sources'
-  from android.sourceSets.main.java.srcDirs
-}
-
 afterEvaluate {
   publishing {
     publications {
       release(MavenPublication) {
         from components.release
-        // Add additional sourcesJar to artifacts
-        artifact(androidSourcesJar)
       }
     }
     repositories {
@@ -79,6 +71,11 @@ android {
   lintOptions {
     abortOnError false
   }
+  publishing {
+    singleVariant("release") {
+      withSourcesJar()
+    }
+  }
 }

 repositories {
```

do you have any recommendations that make the guide to be clear?

**Comment by mariomurrent-softwaresolutions** [comment]
Thx, I’ll think about it. I mean it is clear, it was just the wrong section.

**Comment by Kudo** [comment]
```diff
--- a/modules/tester/android/build.gradle
+++ b/modules/tester/android/build.gradle
-// Creating sources with comments
-task androidSourcesJar(type: Jar) {
-  classifier = 'sources'
-  from android.sourceSets.main.java.srcDirs
-}
-
 afterEvaluate {
   publishing {
     publications {
       release(MavenPublication) {
         from components.release
-        // Add additional sourcesJar to artifacts
-        artifact(androidSourcesJar)
       }
     }
     repositories {
```

```diff
--- a/modules/tester/android/build.gradle
+++ b/modules/tester/android/build.gradle
 android {
   lintOptions {
     abortOnError false
   }
+  publishing {
+    singleVariant("release") {
+      withSourcesJar()
+    }
+  }
 }
```

if separates the sections, does it make it clear?

**Comment by mariomurrent-softwaresolutions** [comment]
Definitely. 
Maybe you can also write something like: Make sure you put the publishing part in the root android section.

**Comment by brentvatne** [comment]
@mariomurrent-softwaresolutions - can you send a pr with your suggested changes to the fyi repo? thank you!

**Comment by mariomurrent-softwaresolutions** [comment]
Sure 👍
