### ISSUE TITLE
Couldn't start project on Android: Error running adb: Error running app. Have you installed the app already using Android Studio? Since you are detached you must build manually.

### ISSUE THREAD

**Issue by liuhuanhui** [expo/expo#2325]
After Expo eject, the module of Android is added to run.

![image](https://user-images.githubusercontent.com/10370625/46244168-90eefb00-c40d-11e8-873c-b06a1f5b212c.png)

error:
Couldn't start project on Android: Error running adb: Error running app. Have you installed the app already using Android Studio? Since you are detached you must build manually.

**Comment by EvanBacon** [comment]
well....

> Have you installed the app already using Android Studio? Since you are detached you must build manually.

**Comment by hyphaene** [comment]
![capture du 2018-10-30 16-57-27](https://user-images.githubusercontent.com/15718919/47731894-5f17c100-dc65-11e8-8014-2d03897177a0.png)
You need to select you device by clicking on the icon I indicated in red.
Everything should be okay after that.

Couldn't find this step in the documentation ( expo SDK v30 )

**Comment by hyphaene** [comment]
@liuhuanhui could I be helpful or are you still experiencing the problem ?

**Comment by liuhuanhui** [comment]
> @liuhuanhui我有帮助还是你还在遇到这个问题？

Sorry, I have changed another way.

**Comment by hyphaene** [comment]
@liuhuanhui 

Hi, thanks for your answer.
Would you have the kindness to share it here ?

**Comment by liuhuanhui** [comment]
Sorry, I gave up Expo, because Expo often produces false prompts without any reason.

@hyphaene
