### ISSUE TITLE
[SDK 49 Beta 4] useLocalSearchParams generics typing error with TypeScript

### ISSUE THREAD

**Issue by danilopolani** [expo/expo#23269]
### Minimal reproducible example

N/A

### Summary

Using generics on `useLocalSearchParams` with Expo router v2 "throws" a TS error:

```ts
// Route: /user/[userId]

// Type '{ userId: string; }' does not satisfy the constraint 'DynamicRouteTemplate | StaticRoutes | RelativePathString'.
const { userId } = useLocalSearchParams<{ userId: string }>();
```

Not sure if somehow related to [this issue of TypeScript](https://github.com/microsoft/TypeScript/issues/34771) linked here #22380 .

<img width="1074" alt="image" src="https://github.com/expo/expo/assets/6277291/eed724fd-3b67-4075-ac9b-046826a068e9">

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0-beta.4 => 49.0.0-beta.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.14.0
    Expo Workflow: managed

**Comment by oliviercperrier** [comment]
👍

**Comment by EvanBacon** [comment]
Related ENG-9256

**Comment by AJTJ** [comment]
I can confirm this. And it is related to general issues I'm having with Expo Router here: https://github.com/expo/expo/issues/23404

**Comment by marklawlor** [comment]
This should be resolved by updating to the latest version of SDK 49
