### ISSUE TITLE
[SDK 49 Beta 4] Dotenv files not being found by eas local build

### ISSUE THREAD

**Issue by danilopolani** [expo/expo#23274]
### Minimal reproducible example

N/A

### Summary

First of all, my goal: create locally an `apk` from the development profile, but both `NODE_ENV` and `--profile` are not finding the correct env file when running `eas build --local`.   

I've created a `.env.development` file with an env `EXPO_PUBLIC_API_URL=xxx` defined.  
Running `eas build --platform android --local --profile development` is not finding the file and returning `Loaded "env" configuration for the "development" profile: no environment variables specified.`  

I've also tried with `NODE_ENV=development eas build --platform android --local --profile development` but nothing changes; the only way to make it work is to use the `env` key inside the `eas.json` file.  

My eas file:

```json
{
  "cli": {
    "version": ">= 3.14.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      }
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0-beta.4 => 49.0.0-beta.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.0 => 0.72.0 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: bare

**Comment by muuvmuuv** [comment]
Hey did you come up with a solution for that? I have the same issue...
