### ISSUE TITLE
expo-camera crash when <Camera> is used in web

### ISSUE THREAD

**Issue by whollacsek** [expo/expo#23273]
### Minimal reproducible example

https://github.com/whollacsek/camera-crash

### Summary

Expo camera works on Android device but not on web.

The minimal repro is created with create-expo-app using expo-camera and react-native-web. Then I added a component that uses `<Camera>`, it crash on web with `Invalid hook call` error:
<img width="457" alt="image" src="https://github.com/expo/expo/assets/825424/44f9e982-d07e-4ec7-88c2-772a20290a9b">

The component that uses `<Camera>`:
```jsx
import {
  Camera, CameraType,
  PermissionStatus,
} from "expo-camera";
import { useEffect, useState } from "react";
import { Text } from "react-native";

export default function Recording() {
  const [cameraPermission, setCameraPermission] = useState(
    PermissionStatus.UNDETERMINED
  );

  const getPermission = async () => {
    const response =
      await Camera.requestCameraPermissionsAsync();
    setCameraPermission(response.status);
  };

  useEffect(() => {
    getPermission();
  }, []);

  if (cameraPermission === PermissionStatus.UNDETERMINED) {
    return <Text>Requesting camera permission</Text>;
  } else if (cameraPermission === PermissionStatus.GRANTED) {
    return <Camera type={CameraType.front} style={{width: '100%', height: '100%'}}/>;
  } else {
    return <Text>No access to camera</Text>;
  }
}

```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.18.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Flamingo 2022.2.1 Patch 1 Flamingo 2022.2.1 Patch 1
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.0 
      expo: ~48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

**Comment by gabrieldonadel** [comment]
Hi @whollacsek, I just tested the repo you've linked and I'm not able to reproduce this issue. The one thing I noticed in your minimal reproducible example is that `react-dom` is not installed, you can do so by running `npx expo install react-dom@18.2.0`

**Comment by whollacsek** [comment]
Hi @gabrieldonadel thanks for taking a look. Could you share an example repo where expo-camera works on the web? I've tried everything including aliasing react in webpack config but it doesn't seem to work. I'll try adding react-dom later

**Comment by gabrieldonadel** [comment]
Hi @whollacsek, https://github.com/whollacsek/camera-crash works on the web if you run `npx expo install react-dom@18.2.0`

**Comment by whollacsek** [comment]
@gabrieldonadel I just tried adding react-dom without success. And there are some error messages on launch:

```
WARNING in ./node_modules/expo-camera/node_modules/@koale/useworker/dist/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/private/tmp/camera-crash/node_modules/expo-camera/node_modules/@koale/useworker/dist/index.mjs.map' file: Error: ENOENT: no such file or directory, open '/private/tmp/camera-crash/node_modules/expo-camera/node_modules/@koale/useworker/dist/index.mjs.map'

web compiled with 1 warning


```

**Comment by whollacsek** [comment]
Seems to be related to https://github.com/expo/expo/issues/17846

**Comment by whollacsek** [comment]
Current workaround is to use yarn instead of npm. If npm is not support it would be great that the documentation mention it.

**Comment by BoavistaLudwig** [comment]
> #17846

How have you fixed this with yarn?

I get this error only since I upgraded to SDK49. I had no issues prior to this.

Web Bundling failed 7704ms
Unable to resolve "@koale/useworker" from "node_modules/expo-camera/build/useWebQRScanner.js"

**Comment by totallytotallyamazing** [comment]
@whollacsek How have you fixed this with yarn?

*I'm currently on Expo SDK 48 and considering going back to SDK 47

**Comment by whollacsek** [comment]
> @whollacsek How have you fixed this with yarn?
> 
> *I'm currently on Expo SDK 48 and considering going back to SDK 47

When I switched to yarn it didn't crash, I'm on yarn v1

**Comment by AchrafBn** [comment]
@BoavistaLudwig  did you find the solution ? I have the same error

**Comment by joshua-revolutions** [comment]
I have the same issue. However it works if I change the bundler to webpack (from metro).

Check app.json

If you have
```
    "web": {
      "bundler": "metro"
    }
```

Remove it to use webpack bundler instead of metro.

**Comment by bglowney** [comment]
I was able to fix this by upgrading to expo sdk 49 (and associated dependencies). For me it did not require using yarn.

**Comment by totallytotallyamazing** [comment]
@bglowney are you able to use expo go for andriod/ios with sdk 49.?
