### ISSUE TITLE
[SDK 49 Beta]: Unable to generate build after upgrading the expo to 49 beta .

### ISSUE THREAD

**Issue by agrittiwari** [expo/expo#23285]
### Minimal reproducible example

Upgrade an existing project: Install the beta version of the Expo package: npm install expo@next or yarn add expo@next Upgrade all dependencies to match SDK 49: npx expo install --fix

### Summary

› Building app... Configuration on demand is an incubating feature. FAILURE: Build failed with an exception. * Where: Settings file 'D:\vms-frontend\vms-mobile\android\settings.gradle' line: 10 * What went wrong: A problem occurred evaluating settings 'VMS'. > path may not be null or empty string. path='null' * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 7s Error: D:\vms-frontend\vms-mobile\android\gradlew.bat exited with non-zero code: 1 Error: D:\vms-frontend\vms-mobile\android\gradlew.bat exited with non-zero code: 1 at ChildProcess.completionListener (D:\vms-frontend\vms-mobile\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23) at Object.onceWrapper (node:events:628:26) at ChildProcess.emit (node:events:513:28) at ChildProcess.cp.emit (D:\vms-frontend\vms-mobile\node_modules\cross-spawn\lib\enoent.js:34:29) at maybeClose (node:internal/child_process:1093:16) at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) ... at Object.spawnAsync [as default] (D:\vms-frontend\vms-mobile\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21) at spawnGradleAsync (D:\vms-frontend\vms-mobile\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46) at Object.assembleAsync (D:\vms-frontend\vms-mobile\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18) at runAndroidAsync (D:\vms-frontend\vms-mobile\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:35:24) at processTicksAndRejections (node:internal/process/task_queues:96:5) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738

**Comment by Stringsaeed** [comment]
you just need to run prebuild again it would fix it
