### ISSUE TITLE
[SDK 49 Beta]: Unable to generate build after upgrading the expo to 49 beta .

### ISSUE THREAD

**Issue by agrittiwari** [expo/expo#23286]
### Minimal reproducible example

Followed the new article to test it out: Upgrade an existing project: Install the beta version of the Expo package: npm install expo@next or yarn add expo@next Upgrade all dependencies to match SDK 49: npx expo install --fix

### Summary

Expected behavior: It ran once,  build successfully completed. but broke after running `npx expo prebuild` , so redid the upgrade, but it is not building afterwards.

What is happening is build is failing, and as I debugged, `settings.gradle ` file has this which was there already before the upgrade and it was working without build fail
```
/*settings.gradle*/




include ':app'
includeBuild(new File(["node", "--print", "require.resolve('react-native-gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())

```
```



› Building app... Configuration on demand is an incubating feature. FAILURE: Build failed with an exception. * Where: Settings file 'D:\vms-frontend\vms-mobile\android\settings.gradle' line: 10 * What went wrong: A problem occurred evaluating settings 'VMS'. > path may not be null or empty string. path='null' * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 7s Error: D:\vms-frontend\vms-mobile\android\gradlew.bat exited with non-zero code: 1 Error: D:\vms-frontend\vms-mobile\android\gradlew.bat exited with non-zero code: 1 at ChildProcess.completionListener (D:\vms-frontend\vms-mobile\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23) at Object.onceWrapper (node:events:628:26) at ChildProcess.emit (node:events:513:28) at ChildProcess.cp.emit (D:\vms-frontend\vms-mobile\node_modules\cross-spawn\lib\enoent.js:34:29) at maybeClose (node:internal/child_process:1093:16) at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) ... at Object.spawnAsync [as default] (D:\vms-frontend\vms-mobile\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21) at spawnGradleAsync (D:\vms-frontend\vms-mobile\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46) at Object.assembleAsync (D:\vms-frontend\vms-mobile\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18) at runAndroidAsync (D:\vms-frontend\vms-mobile\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:35:24) at processTicksAndRejections (node:internal/process/task_queues:96:5) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738

**Comment by MahmoudNafiseh** [comment]
Did you figure out how to fix this?

**Comment by dafrica1** [comment]
I have the same issue when trying to build for Android. iOS works fine.

**Comment by dafrica1** [comment]
Potential fix:

1. Open the project's android directory in Android Studio and attempt to build
2. In the error, it gave me the name of an npm package that was referenced but it was unable to find
3. I manually added that npm package back to the project

The build started working again and works without issues now

**Comment by genesisxyz** [comment]
Following the [Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.71.11&to=0.72.1) you need to modify the settings.gradle from

`includeBuild(new File(["node", "--print", "require.resolve('react-native-gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())`

to

`includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile())`

and then run Gradle Sync from Android Studio
