### ISSUE TITLE
Can't attach remote JS debugger on 49 beta 4

### ISSUE THREAD

**Issue by natew** [expo/expo#23281]
### Minimal reproducible example

https://github.com/tamagui/tamagui/pull/1375

It crashes the app entirely once you enable the JS debugger.

Not sure if relevant (or why its cut off like this):

<img width="684" alt="CleanShot 2023-07-03 at 20 26 11@2x" src="https://github.com/expo/expo/assets/12100/cc237806-377c-4644-ac66-fab871789931">

### Summary

<img width="564" alt="CleanShot 2023-07-03 at 20 23 32@2x" src="https://github.com/expo/expo/assets/12100/53b29dfa-84ca-4b00-9c87-e690606e5ada">

Reproduction:

https://github.com/tamagui/tamagui/pull/1375

```
yarn
cd apps/kitchen-sink
yarn ios
```

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.8 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 18.16.0 - ~/Library/Caches/fnm_multishells/69747_1653603955297/bin/node
      Yarn: 3.5.0 - ~/Library/Caches/fnm_multishells/69747_1653603955297/bin/yarn
      npm: 9.5.1 - ~/Library/Caches/fnm_multishells/69747_1653603955297/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    Expo Workflow: bare
```

**Comment by Kudo** [comment]
hi @natew, the remote debugging is deprecated in sdk 49, could you test upon hermes and use the hermes inspector instead?

**Comment by natew** [comment]
Ah ok, that does work
