### ISSUE TITLE
Missing "Orientation" tag in ImagePicker result EXIF data; ImageManipulator "crop" util has inconsistent behaviour for different local uris, when processing image with EXIF Orientation different from 1

### ISSUE THREAD

**Issue by serhiipalash** [expo/expo#2329]
### Environment

| software         | version
| ---------------- | -------
| expo | 30.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz
| device    | iPhone 6s

`exp diagnostics` output

<img width="977" alt="screen shot 2018-09-29 at 7 10 17 pm" src="https://user-images.githubusercontent.com/14208343/46247947-70c63880-c41b-11e8-982e-d63f50b5dea3.png">

App's target are iOS and Android standalone apps

### Steps to Reproduce

```
git clone https://github.com/serhiipalash/photo-orientation-test
cd photo-orientation-test
npm install
expo start -i
```

You'll see on start screen JPEG image with EXIF orientation 3 https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_3.jpg and `Pick image`, `Get library photos`, `Crop top-left corner` and `Save to library` buttons.

#### Missing "Orientation" tag in ImagePicker result EXIF data;

Press `Pick image` button and select any image from your Photos. This runs the code
```
const result = await ImagePicker.launchImageLibraryAsync({
    allowsEditing: false,
    exif: true,
})

this.setState({ info: JSON.stringify(result.exif, null, 4) })
```
You'll see EXIF data of picked image on the screen, but there will not be "Orientation" tag in it. 

If you want to check if EXIF "Orientation" tag exists in image you picked, press "Get library photos" button and see last 9 photos from your library. This runs the code 
```
const result = await MediaLibrary.getAssetsAsync({ first: 9 })

this.setState({ assets: result.assets })
```
Then press particular photo. This runs the code 
```
_assetPressed = async assetId => {
  try {
    const info = await MediaLibrary.getAssetInfoAsync(assetId)

    this.setState({
      activeAssetId: assetId,
      info: JSON.stringify(info, null, 4),
    })
  } catch (err) {
    console.log('err', err)
  }
}
```
You'll see this asset info and "Orientation" in it.

Demo: https://drive.google.com/file/d/1Indxlg8SOHEzooub2XcuCq26whJm4Hli/view

#### ImageManipulator "crop" util has inconsistent behaviour for different local uris, when processing image with EXIF Orientation different from 1

1. Reload the app and you will see default image with EXIF "Orientation" 3. This image is required from module.

2. Press "Crop top-left corner". This runs the code
```
const asset = Asset.fromModule(require('./Landscape_3.jpg'))

await asset.downloadAsync()

const result = await ImageManipulator.manipulate(asset.localUri, [
  {
    crop: {
      originX: 0,
      originY: 0,
      width: 600,
      height: 600,
    },
  },
])

this.setState({
  originalImageUri: asset.localUri,
  croppedImage: result,
})
```
You'll see that crop result is not top-left corner of visible image, but bottom-right. That is because image EXIF "Orientation" is 3.

4. Press "Save to library". This will save default image to your Photos.

5. Press "Get library photos"

6. Press saved image to select it

7. Press "Crop top-left corner" button
You'll see that in this case crop result is top-left corner of the image, even if EXIF "Orientation" is different from 1. That is because in first case you passed in `ImageManipulator.manipulate(...)` actual local uri (absolute path), but in second - it was something like `assets-library://asset/asset.JPG?id=15DCB5AC-21EB-4537-86A1-8E1CEE733C7F&ext=JPG`.

This is inconsistent behaviour. `ImageManipulator` crop util result differs for the same image, depending on what type of uri you have passed into it.

Demo: https://drive.google.com/file/d/1TFagw5q8gDIyFxoCXvFZBf0OGS91FqtN/view

### Expected Behavior

1. `ImagePicker` should return "Orientation" tag in EXIF data.
2. `ImageManipulator` crop util behavior should be consistent. It should return the same result for the same image independent from type of passed uri.

### Actual Behavior

1. `ImagePicker` never returns "Orientation" tag in EXIF data.
2. `ImageManipulator` crop util works differently, depending on what kind of uri you have passed into it.

### Reproducible Demo

https://github.com/serhiipalash/photo-orientation-test

Few words why we need this. In our app user can pick an image from his library using `Expo.ImagePicker`, see it, move active area rectangle on top of it and then press "Crop" button, that crops picked image to active area. Everything works fine if picked image has "Orientation" 1. The problems come with images with "Orientation" different from 1. React Native `Image` component displays these images correctly (rotates or flips them), user moves active area rectangle on top of it and expects to get crop result visible in active area, but he gets completely different image because `Expo.ImagePicker` returns image with uri as absolute path, and if you pass this kind of uri in `Expo.ImageManipulator` it returns "mirrored" or "flipped" crop. As `Expo.ImagePicker` doesn't return "Orientation" in its result we can't fix it recalculating options for `Expo.ImageManipulator.manipulate(...)`. This is a very common case for users as they all have front-camera and make selfie on it. When user picks such photo and selects active area to crop, the result will be "flipped" because the images taken with front-camera have "Orientation" 6. Try it with my demo app - crop top-left corner of your selfie in case you picked it with `Expo.ImagePicker` and with selecting it in "Get library photos" result. 

The only possible solution for now is don't use  `Expo.ImagePicker` at all and build our own "image picker" with `Expo.MediaLibrary` - its `getAssetInfoAsync()` returns EXIF "Orientation". We don't want to do it cause it is reinventing the wheel.

What Expo can do? You can add "Orientation" tag in `Expo.ImagePicker` result EXIF data. I think it is a good idea to have it there anyway. Also you can make `ImageManipulator` crop util work more consistently, it should either always preserve EXIF "Orientation" of given image or never, or you can make it as an option "preserveExifOrientation" (default value should be `true`). 

ping @nicknovitski

**Comment by serhiipalash** [comment]
Getting EXIF "Orientation" from raw image data seems like impossible as React Native fetch Api doesn't support `arrayBuffer()` at the moment https://forums.expo.io/t/blob-object-how-can-i-access-the-blobs-raw-data-as-an-arraybuffer/9717.

**Comment by drumsoft** [comment]
I'was struggling with this missing "Orientation" problem too. So, I specified the "quality: 1" option to recompressed the image, and received the images with corrected direction (They can be assumed as "Orientation: 0").
However, recompressing is not good for image quality, so I hope the problem will be fixed.

**Comment by osdnk** [comment]
Kindly ping, @bbarthec

**Comment by serhiipalash** [comment]
@bbarthec can you please add "Orientation" tag in ImagePicker result exif data? We will implement recalculation of crop params based on it by ourself. It is not possible to release working crop feature without it. Users have many photos taken on front camera or taken with phone orientation horizontal and all these photos cropping results look ugly.

**Comment by bbarthec** [comment]
@serhiipalash sorry for this long delay. PR is already waiting for being merged, so fixes addressing both scenarios will be available alongside next sdk release.

**Comment by serhiipalash** [comment]
Thank you very much @bbarthec ! This is great! :ghost:
