### ISSUE TITLE
Failed to parse source map from node_modules/@koale/useworker/dist/index.mjs.map' file: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by arishZype** [expo/expo#23296]
### Minimal reproducible example

https://github.com/arish-panjwani/ExpoLatestAppRnD.git

### Summary

The below issue is happening in react-native-web using expo (expo-web).

I was using `"expo": "47.0.0"`, which required expo-camera version as 
`"expo-camera": "13.1.0"` 
and webPack as 
`"@expo/webpack-config": "0.17.2"`

Then, I upgraded expo to `"expo": "48.0.18"` which then asked me to upgrade expo-camera as
`"expo-camera": "13.2.1"`
and
`"@expo/webpack-config": "18.1.0"`

After this If I run, I start getting the warning as follows:

> WARNING in ./node_modules/@koale/useworker/dist/index.mjs
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/Users/Workspace/ExpoLatestAppRnD/node_modules/@koale/useworker/dist/index.mjs.map' file: Error: ENOENT: no such file or directory, open '/Users/Workspace/ExpoLatestAppRnD/node_modules/@koale/useworker/dist/index.mjs.map'
> 
> web compiled with 1 warning

In the above warning, the issue is with the package **`@koale/useworker`** which is a dependency of expo-camera.

Also, note that the warning comes once you import something from expo-camera as follows:

> import { Camera, PermissionStatus } from "expo-camera"; 

Now, if I keep expo as 48.0.18 but i downgrade webpack-config to the older one used for expo 47, which was 
`"@expo/webpack-config": "0.17.2"`, the warning gets resolved.

I have tried using expo-camera 13.2.1 as well as 13.1.0.

So, apparently it appears that expo-camera (or @koale/useworker used by expo-camera) doesn't support webpack-config 18.1.0 and is giving this warning related to source map parsing.

Please look into this warning and let me know if any solution exists.

Thanks!

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.8.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
      Watchman: 2022.09.05.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 18.1.0 => 18.1.0 
      expo: 48.0.18 => 48.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.11 => 0.71.11 
      react-native-web: 0.18.12 => 0.18.12 
    Expo Workflow: managed

**Comment by SwapnilkRespo** [comment]
i'm also facing the same issue. Any solutions?

**Comment by Pratish149** [comment]
After upgrading expo & expo-camera, I'm also getting the same warning. Is there any solution to get rid of this ? 
<img width="1173" alt="tmp_3d6b27e8-8169-45bc-9e9c-9413b811444b" src="https://github.com/expo/expo/assets/112325275/f86581e0-ff55-47c2-b77c-a5bfe073664a">

**Comment by npjoge** [comment]
Even I have the same issue after upgrade the version of EXPO from "47.*.*" to "48.*.*".
Any solutions???

**Comment by danishazmat** [comment]
same issue any solution?

**Comment by whollacsek** [comment]
This is the reason https://github.com/expo/expo/issues/17846 it's been a year old already

**Comment by marklawlor** [comment]
The webpack config was changed to use existing sourcemaps if present in the `node_module`. `@koale/useworker` is published to NPM with code comments indicating that it has souremaps, but the sourcemap files are not published to the NPM registery. More information here https://github.com/alewin/useWorker/issues/138

**Comment by EvanBacon** [comment]
Working on a fix. In the meantime, you can set the environment variable `GENERATE_SOURCEMAP=1` to disable source maps.

**Comment by arishZype** [comment]
Hi @EvanBacon , I have tried using GENERATE_SOURCEMAP=1 in my .env but it didn't disable the source maps..

**Comment by totallytotallyamazing** [comment]
@EvanBacon Hi Even, I'm having the exact same problem as @arishZype and your suggested temporary fix is not working for me either, GENERATE_SOURCEMAP=1 in .env

**Comment by upcodes1** [comment]
I tried to upgrade to v49 and started getting this issue. Is there a fix for this?
