### ISSUE TITLE
node_modules/@koale/useworker/dist/index.mjs.map' file: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by arishZype** [expo/expo#23290]
### Minimal reproducible example

Steps to reproduce: Use "expo-camera": "13.2.1" and "@expo/webpack-config": "18.1.0" in a blank expo project having expo version 48.0.18. This warning will appear when running for expo-web.

### Summary

The below issue is happening in react-native-web using expo (expo-web).

I was using `"expo": "47.0.0"` which required expo-camera version as 
`"expo-camera": "13.1.0"` 
and webPack as 
`"@expo/webpack-config": "0.17.2"`

Then I upgraded expo to `"expo": "48.0.18"` which then asked me to upgrade expo-camera as
`"expo-camera": "13.2.1"`
and
`"@expo/webpack-config": "18.1.0"`

After this If I run, I started getting the warning as follows:

> WARNING in ./node_modules/@koale/useworker/dist/index.mjs
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '/Users/apple/Workspace/ZypeWebAppExpoUpgrade/node_modules/@koale/useworker/dist/index.mjs.map' file: Error: ENOENT: no such file or directory, open '/Users/apple/Workspace/ZypeWebAppExpoUpgrade/node_modules/@koale/useworker/dist/index.mjs.map'
> 
> web compiled with 1 warning

In the above warning, the issue is with the package **`@koale/useworker`** which is a dependency of expo-camera.

Now, if I keep expo as 48.0.18 but i downgrade webpack-config to the older one used for expo 47, which was 
`"@expo/webpack-config": "0.17.2"`, the warning gets resolved.

So, apparently it appears that expo-camera (or @koale/useworker used by expo-camera) doesn't support webpack-config 18.1.0 and is giving this warning related to source map parsing.

Please look into this issue and let me know if any solution is possible.

Thanks!

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.8.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
      Watchman: 2022.09.05.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 18.1.0 => 18.1.0 
      expo: 48.0.18 => 48.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.11 => 0.71.11 
      react-native-web: 0.18.12 => 0.18.12 
    Expo Workflow: managed

**Comment by totallytotallyamazing** [comment]
@arishZype May I ask what specific command you used to downgrade webpack-config to the older one, "@expo/webpack-config": "0.17.2"?
