### ISSUE TITLE
Error Failed to build the app: No package name found

### ISSUE THREAD

**Issue by edwardlarsson94** [expo/expo#23316]
### Minimal reproducible example

The error occurs when I run the command "eas build --platform ios" for a react native project using expo, it does not let me compile and does not go beyond the install pod.

### Summary

Cuando ejecute el comando  "eas build --platform ios" este me debe generar el compilado para ios para subirlo a la app store pero hace horas ese mismo codigo me funcionaba y ahora ya no me deja compilar me genera el siguiente error:

Using Expo modules
[Expo] Enabling modular headers for pod ExpoModulesCore
[Expo] Enabling modular headers for pod ReactCommon
[Expo] Enabling modular headers for pod EXImageLoader
Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/expo/.nvm/versions/node/v16.18.1/bin/node
[stderr] 
error Failed to build the app: No package name found. Found errors in /Users/expo/workingdir/build/node_modules/expo-intent-launcher/android/src/main/AndroidManifest.xml.
[!] Invalid `Podfile` file: unexpected token at 'info Run CLI with --verbose flag for more details.
'.
 #  from /Users/expo/workingdir/build/ios/Podfile:15
 #  -------------------------------------------
 #    use_expo_modules!
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
Error: Unknown error. See logs for more information.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.17 - ~/node_modules/.bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.7 => 0.18.12 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.0.8
    Expo Workflow: bare

**Comment by VictorioMolina** [comment]
Same here.

**Comment by JacobDel** [comment]
+1, please reopen this issue

**Comment by tiagopazhs** [comment]
+ 1
