### ISSUE TITLE
 Unable to resolve "expo-core" from "node_modules\expo-location\src\Location.js" after upgrading to version 30.0.0

### ISSUE THREAD

**Issue by ferdintel** [expo/expo#2331]
Everything was working perfectly until I upgraded to version 30.0.0

This is my package.json
`{
    "main": "node_modules/expo/AppEntry.js",
    "private": true,
    "dependencies": {
        "axios": "^0.18.0",
        "expo": "^30.0.0",
        "parse": "^1.11.1",
        "react": "16.3.1",
        "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
        "react-native-timer-countdown": "^1.1.3",
        "react-native-underline-tabbar": "^1.3.6",
        "react-navigation": "^2.13.0",
        "react-redux": "^5.0.7",
        "redux": "^4.0.0"
    }
}`

**Comment by EvanBacon** [comment]
You'll need to fill out the issue template. Can't help with the provided information.

**Comment by tushgup** [comment]
Facing the same error after trying to upgrade to 30.0.0. My app doesn't even use 'expo-location' as a dependency... reverting back to 29.0.0 until I can figure out how to fix this.

**Comment by kodamirmo** [comment]
Same here

**Comment by EvanBacon** [comment]
@tushgup have you tried `yarn upgrade` or `rm -rf node_modules/ rm package-lock.json npm install`. Did that work for you?

**Comment by tushgup** [comment]
Fixed. Thanks, everyone!

**Comment by ferdintel** [comment]
Excuse me for the delay. The problem was solved after doing  `rm -rf node_modules/ rm package-lock.json npm install`

**Comment by nickjuntilla** [comment]
I ended up making a new install and then copying over the dependencies.

**Comment by Aziaev** [comment]
I have the same issue:
```Unable to resolve "expo-core" from "node_modules/expo-gl/src/GLView.js"```

**rm -rf node_modules/***
***rm package-lock.json
***npm install**
doesn't help in my case. My package.json:
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^28.0.0",
    "expo-graphics": "^1.0.3",
    "expo-three": "^3.0.0-alpha.8",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
    "react-navigation": "~2.3.1"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^28.0.0"
  },
  "private": true
}
```

What should I do?

**Comment by Aziaev** [comment]
Now I have an issue with "React Native version mismatch"
JS version 0.55.4
NAtive version 0.57.1

**Comment by Aziaev** [comment]
I found a solution!
SDK version in package.json and app.json should be the same! Amazing!

**Comment by Xerus2000** [comment]
Getting a similar issue for SDK 33:
`Unable to resolve "expo-errors" from "node_modules/expo/build/ErrorRecovery/ErrorRecovery.js"`

So I added a dependency on expo-errors in my buildscript, now I get the following error:
`Unable to resolve "./ExponentScreenOrientation" from "node_modules/expo/build/ScreenOrientation/ScreenOrientation.js"`

dependencies:
```
  "dependencies": {
    "apisauce": "^1.0.2",
    "color": "^3.1.0",
    "create-react-context": "^0.2.3",
    "expo": "^33",
    "expo-errors": "^3.0.0",
    "geolib": "^2.0.24",
    "react": "^16.8.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-collapsible": "^1.4.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-maps": "^0.23.0",
    "react-native-snap-carousel": "^3.7.5",
    "react-navigation": "^3.3.2"
  },
  "devDependencies": {
    "@types/expo": "^32",
    "@types/jest": "^24.0.13",
    "@types/react": "^16.8.19",
    "@types/react-native": "^0.57.60",
    "@types/react-test-renderer": "^16.8.1",
    "react-native-typescript-transformer": "^1.2.12",
    "rimraf": "latest",
    "schedule": "^0.5.0",
    "typescript": "^3.5.1"
  },
```

I have tried `rimraf package-lock.json && rimraf node_modules`, but to no avail.

**Comment by Louis345** [comment]
Did you ever solve your issue?
