### ISSUE TITLE
I got this   :  WARN  Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.

### ISSUE THREAD

**Issue by Rvicii** [expo/expo#23317]
### Minimal reproducible example

Happened while setting up the react native environment 

### Summary

I received this after a QR code for expo go for the simulator and the device IOS 

### Environment

![WhatsApp Image 2023-07-06 at 5 25 20 AM](https://github.com/expo/expo/assets/138740958/1c72858c-2517-44d6-89e1-c42a8f4da865)

**Comment by brentvatne** [comment]
this is resolved in sdk 49. https://blog.expo.dev/expo-sdk-49-c6d398cdf740
