### ISSUE TITLE
`npx expo config --json -t public` should return valid JSON

### ISSUE THREAD

**Issue by Ben2HellAndBack** [expo/expo#23325]
### Summary

Running `npx expo config --json -t public` with env files in your project directy it prefix's the JSON output with environment about the env eg `env: load .env.local .env.development`. Which means it no longer returns valid JSON.  This breaks the [GitHub action](https://github.com/expo/expo-github-action/blob/main/src/project.ts#L11) . 

To fix this we should pass silent along to the `.load` function when we are expecting JSON output.
```ts
// https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/config/configAsync.ts#L36
require('@expo/env').load(projectRoot, { silent: opts.json });
```

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

49.0.0

### Environment
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/Library/Caches/fnm_multishells/96692_1688559825007/bin/node
      npm: 9.5.1 - ~/Library/Caches/fnm_multishells/96692_1688559825007/bin/npm
      Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/[USER]/.rbenv/shims/pod
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.9
    Expo Workflow: managed
```
### Minimal reproducible example

Run  `npx expo config --json -t public`  with a `.env` file in your project root. You will see the JSON prefixed with `env: load .env.local .env.development`.

**Comment by brentvatne** [comment]
@byCedric - maybe we should change how we parse the result in the github action to support the case where there is some text output before json. `jq` for example will ignore any text prior to json output, we might want to do the same

**Comment by Noitham** [comment]
There's a workaround suggested [here](https://github.com/expo/expo-github-action/issues/221):

https://github.com/expo/expo-github-action/compare/main...nderscore:expo-github-action:workaround

**Comment by lsarni** [comment]
Would it be possible to make a new release with this fix? I'm currently experiencing the issue described on https://github.com/expo/expo-github-action/issues/221
