### ISSUE TITLE
SDK 49 Error: Cannot find module 'metro-cache'

### ISSUE THREAD

**Issue by Pcpkomputer** [expo/expo#23320]
### Summary

I upgraded my expo SDK from 48 to 49, build is successfully for production and development-build, but when I try run the project with npx expo start --dev-client it show this error 

Error: Cannot find module 'metro-cache'
Require stack:
- /Users/yudhacode/node_modules/@expo/metro-config/build/transform-worker/postcss.js
- /Users/yudhacode/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/src/start/server/metro/resolveFromProject.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/src/utils/analytics/getMetroProperties.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/src/start/startAsync.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/src/start/index.js
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/@expo/cli/build/bin/cli
- /Users/yudhacode/Desktop/prodiginow_mobile/production/pws-employee-dashboard-mobile/node_modules/expo/bin/cli

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

{
  "dependencies": {
    "@expo/config-plugins": "~7.2.2",
    "@gorhom/bottom-sheet": "^5.0.0-alpha.0",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-native-masked-view/masked-view": "0.2.9",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.2",
    "@shopify/flash-list": "1.4.3",
    "axios": "^1.2.2",
    "crypto-js": "^4.1.1",
    "expo": "^49.0.0",
    "expo-asset": "~8.10.1",
    "expo-dev-client": "~2.4.4",
    "expo-device": "~5.4.0",
    "expo-document-picker": "~11.5.2",
    "expo-file-system": "~15.4.2",
    "expo-font": "~11.4.0",
    "expo-image": "~1.3.1",
    "expo-image-picker": "~14.3.1",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-location": "~16.0.0",
    "expo-navigation-bar": "~2.3.0",
    "expo-notifications": "~0.20.1",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.8",
    "expo-web-browser": "~12.3.2",
    "geolib": "^3.3.3",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.39.2",
    "react-native": "0.72.1",
    "react-native-calendars": "^1.1290.0",
    "react-native-collapsible": "^1.6.0",
    "react-native-country-flag": "^1.1.9",
    "react-native-extended-stylesheet": "^0.12.0",
    "react-native-freshchat-sdk": "^4.2.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-indicators": "^0.17.0",
    "react-native-mmkv": "^2.6.2",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-shimmer-placeholder": "^2.0.9",
    "react-native-svg": "13.9.0",
    "react-native-view-pdf": "^0.14.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.2.2",
    "react-query": "^3.39.2",
    "zustand": "^4.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@types/react": "~18.0.27",
    "@types/react-native": "~0.70.6",
    "expo-community-flipper": "^47.0.0",
    "react-native-flipper": "^0.164.0",
    "typescript": "^5.1.3"
  },
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "version": "1.0.0",
  "private": true,
  "name": "pws-employee-dashboard-mobile"
}

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Reproducible demo

- npx create-react-native-app
- upgrade manual sdk to 49

**Comment by FleetAdmiralJakob** [comment]
Did you figure it out? I'm facing the same problem right now.

**Comment by qoobes** [comment]
Me too

**Comment by AprilNEA** [comment]
The following command solved my problem in my monorepo project.
```bash
EXPO_USE_METRO_WORKSPACE_ROOT=1 expo export
```

**Comment by daankennes** [comment]
For what it's worth, I got this error after uninstalling @react-native/metro-config. Reinstalled it (and imported from that package instead of @expo/metro-config in metro.config.js) and the error went away.

**Comment by FleetAdmiralJakob** [comment]
> For what it's worth, I got this error after uninstalling @react-native/metro-config. Reinstalled it (and imported from that package instead of @expo/metro-config in metro.config.js) and the error went away.

So you switched from react-native/metro-config to expo/metro-config or from expo/metro-config to react-native/metro-config ?

**Comment by daankennes** [comment]
@FleetAdmiralJakob the error appeared when I tried switching from react-native/metro-config to expo/metro-config. I reverted that and it started working again.
