### ISSUE TITLE
Expo SDK 49 web (with metro) not working with react-hook-form

### ISSUE THREAD

**Issue by fuelkoy** [expo/expo#23322]
### Minimal reproducible example

Had before. I seemly deleted it after some point
### Summary

Template project from "https://docs.expo.dev/routing/installation/" and upgrading app according to "https://blog.expo.dev/expo-sdk-49-c6d398cdf740".

npm run web > blank page with following error in terminal:
1. `Unable to resolve "react-hook-form" from "app\(tabs)\index.tsx"`,

and in chrome console: 
1. `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
4. `Refused to execute script from 'http://localhost:8081/index.ts.bundle?platform=web&dev=true&hot=false&lazy=true' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: managed

**Comment by Briseus** [comment]
just hit the same issue while upgrading from 48 to 49

**Comment by lenmazzone** [comment]
I added the following line to my metro.config.ts to resolve this:

`
config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
`

The whole thing:

`// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

// Remove all console logs in production...
config.transformer.minifierConfig.compress.drop_console = true;
config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
module.exports = config;`

**Comment by fuelkoy** [comment]
@lenmazzone works perfectly! Thank you for sharing. I don't know how Expo team should take account of this, but at least now they have the knowledge of the problem (and react-hook-form could be pretty well used package) and also the solution

**Comment by robertherber** [comment]
Related issue for urql: https://github.com/expo/expo/issues/23322

The same metro.config.js trick fixed this for urql 👍 I guess it would make sense to make this part of the default metro.config.js?

**Comment by gorbypark** [comment]
> I added the following line to my metro.config.ts to resolve this:
> 
> `config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];`
> 
> The whole thing:
> 
> ```
> // Learn more https://docs.expo.io/guides/customizing-metro
> const { getDefaultConfig } = require("expo/metro-config");
> 
> const config = getDefaultConfig(__dirname);
> 
> // Remove all console logs in production...
> config.transformer.minifierConfig.compress.drop_console = true;
> config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
> module.exports = config;
> ```

This got me past the react-hook-forms error, but now I'm getting a new error about GestureHandler and the Drawer.  This is only happening on web.  I'm not quite sure what's going on tbh, possibly the above fix is not handling platform specific extensions?  It's hard to say what's happening behind the scenes with all the transpiration and etc...

```
Web Bundling failed 1120ms
Unable to resolve "react-native-web/dist/exports/DrawerLayoutAndroid" from "node_modules/react-native-gesture-handler/lib/module/components/GestureComponents.web.js"
```

**Comment by andreiascendia** [comment]
> > I added the following line to my metro.config.ts to resolve this:
> > `config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];`
> > The whole thing:
> > ```
> > // Learn more https://docs.expo.io/guides/customizing-metro
> > const { getDefaultConfig } = require("expo/metro-config");
> > 
> > const config = getDefaultConfig(__dirname);
> > 
> > // Remove all console logs in production...
> > config.transformer.minifierConfig.compress.drop_console = true;
> > config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
> > module.exports = config;
> > ```
> 
> This got me past the react-hook-forms error, but now I'm getting a new error about GestureHandler and the Drawer. This is only happening on web. I'm not quite sure what's going on tbh, possibly the above fix is not handling platform specific extensions? It's hard to say what's happening behind the scenes with all the transpiling and etc...
> 
> ```
> Web Bundling failed 1120ms
> Unable to resolve "react-native-web/dist/exports/DrawerLayoutAndroid" from "node_modules/react-native-gesture-handler/lib/module/components/GestureComponents.web.js"
> ```
> 
> **EDIT** This seems to be a separate problem

Any success with he hook problem?

**Comment by nasir733** [comment]
just ran into the same issue

**Comment by ysheep-js** [comment]
> > I added the following line to my metro.config.ts to resolve this:
> > `config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];`
> > The whole thing:
> > ```
> > // Learn more https://docs.expo.io/guides/customizing-metro
> > const { getDefaultConfig } = require("expo/metro-config");
> > 
> > const config = getDefaultConfig(__dirname);
> > 
> > // Remove all console logs in production...
> > config.transformer.minifierConfig.compress.drop_console = true;
> > config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
> > module.exports = config;
> > ```
> 
> This got me past the react-hook-forms error, but now I'm getting a new error about GestureHandler and the Drawer. This is only happening on web. I'm not quite sure what's going on tbh, possibly the above fix is not handling platform specific extensions? It's hard to say what's happening behind the scenes with all the transpiling and etc...
> 
> ```
> Web Bundling failed 1120ms
> Unable to resolve "react-native-web/dist/exports/DrawerLayoutAndroid" from "node_modules/react-native-gesture-handler/lib/module/components/GestureComponents.web.js"
> ```
> 
> **EDIT** This seems to be a separate problem

Just the same issue

**Comment by gorbypark** [comment]
> > > I added the following line to my metro.config.ts to resolve this:
> > > `config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];`
> > > The whole thing:
> > > ```
> > > // Learn more https://docs.expo.io/guides/customizing-metro
> > > const { getDefaultConfig } = require("expo/metro-config");
> > > 
> > > const config = getDefaultConfig(__dirname);
> > > 
> > > // Remove all console logs in production...
> > > config.transformer.minifierConfig.compress.drop_console = true;
> > > config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
> > > module.exports = config;
> > > ```
> > 
> > 
> > This got me past the react-hook-forms error, but now I'm getting a new error about GestureHandler and the Drawer. This is only happening on web. I'm not quite sure what's going on tbh, possibly the above fix is not handling platform specific extensions? It's hard to say what's happening behind the scenes with all the transpiling and etc...
> > ```
> > Web Bundling failed 1120ms
> > Unable to resolve "react-native-web/dist/exports/DrawerLayoutAndroid" from "node_modules/react-native-gesture-handler/lib/module/components/GestureComponents.web.js"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **EDIT** This seems to be a separate problem
> 
> Just the same issue

This is an unrelated issue, but all I had to do was `npx expo install react-native-gesture-handler`.

**Comment by dben89x** [comment]
> > I added the following line to my metro.config.ts to resolve this:
> > `config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];`
> > The whole thing:
> > ```
> > // Learn more https://docs.expo.io/guides/customizing-metro
> > const { getDefaultConfig } = require("expo/metro-config");
> > 
> > const config = getDefaultConfig(__dirname);
> > 
> > // Remove all console logs in production...
> > config.transformer.minifierConfig.compress.drop_console = true;
> > config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
> > module.exports = config;
> > ```
> 
> This got me past the react-hook-forms error, but now I'm getting a new error about GestureHandler and the Drawer. This is only happening on web. I'm not quite sure what's going on tbh, possibly the above fix is not handling platform specific extensions? It's hard to say what's happening behind the scenes with all the transpiling and etc...
> 
> ```
> Web Bundling failed 1120ms
> Unable to resolve "react-native-web/dist/exports/DrawerLayoutAndroid" from "node_modules/react-native-gesture-handler/lib/module/components/GestureComponents.web.js"
> ```
> 
> **EDIT** This seems to be a separate problem

@gorbypark any success with the DrawerLayoutAndroid issue? I'm getting almost an identical error:
> Unable to resolve "react-native-web/dist/exports/DrawerLayoutAndroid" from "node_modules/react-native-gesture-handler/src/components/GestureComponents.tsx"

Only difference is `GestureComponents.tsx` vs `GestureComponents.web.js`.

**Comment by balgamat** [comment]
I had "mjs" and "cjs" extensions in metro config already so I haven't noticed any problems... that is until I tried to bundle for the web: 
<img width="898" alt="image" src="https://github.com/expo/expo/assets/6381607/56bd204b-a00c-4396-b46e-f2bc8844fbeb">

I simply cannot get hook form going for the web...

**Comment by LinusU** [comment]
I believe that this is the problem: https://github.com/expo/expo/commit/6a750d0620da88294f9f1c7bada2cb5b6d7df3ff#r121599931

Adding `mjs` and `cjs` to `watcher.additionalExts` seems to resolve the issue

**Comment by noledev** [comment]
Thanks! Adding the extensions worked for me as well.

For those experiencing the `DrawerLayoutAndroid` issue, I also got this when updating to Expo 49. `react-native-web@0.19.0` removed this component, but my version of `react-native-gesture-handler` was still referencing it. Updating to the latest (v2.12.1) resolved that error for me.

**Comment by luiz7727** [comment]
> I added the following line to my metro.config.ts to resolve this:
> 
> `config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];`
> 
> The whole thing:
> 
> ```
> // Learn more https://docs.expo.io/guides/customizing-metro
> const { getDefaultConfig } = require("expo/metro-config");
> 
> const config = getDefaultConfig(__dirname);
> 
> // Remove all console logs in production...
> config.transformer.minifierConfig.compress.drop_console = true;
> config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];
> module.exports = config;
> ```

Resolved the error but the page doesn't render without any error in console.

**Comment by Ernest2026** [comment]
> [balgamat](/balgamat)

Hi balgamat, have you found a solution for this yet, I'm having similar issue, and I'll need to access the web to write test. Let me know if you have a workaround or you've found the solution, thanks in advance...

**Comment by OneHatRepo** [comment]
I've got the same issue as @balgamat, and it's preventing me from using React Hook Form and Metro together on the web. This consequently prevents me from using Expo Router, which depends upon Metro!

package.json:
```
{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "web": "npx expo start --clear --web -p 8083",
    "build": "npx expo export -p web",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios"
  },
  "dependencies": {
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.49.2",
    "react-native": "0.72.6",
    "react-native-safe-area-context": "4.6.3",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

```


metro.config.js:
```
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, {
	// Enable CSS support.
	isCSSEnabled: true,
});

config.resolver.sourceExts.push('mjs', 'cjs');
config.resolver.assetExts.push('mjs', 'cjs');
config.watcher.additionalExts.push('mjs', 'cjs');

module.exports = config;
```

Error:
> Uncaught TypeError: (0 , _reactHookForm.useForm) is not a function

**Comment by Ernest2026** [comment]
> I've got the same issue as @balgamat, and it's preventing me from using React Hook Form and Metro together on the web. This consequently prevents me from using Expo Router, which depends upon Metro!
> 
> package.json:
> 
> ```
> {
>   "name": "my-app",
>   "version": "1.0.0",
>   "main": "node_modules/expo/AppEntry.js",
>   "scripts": {
>     "web": "npx expo start --clear --web -p 8083",
>     "build": "npx expo export -p web",
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios"
>   },
>   "dependencies": {
>     "expo": "~49.0.15",
>     "expo-status-bar": "~1.6.0",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-hook-form": "^7.49.2",
>     "react-native": "0.72.6",
>     "react-native-safe-area-context": "4.6.3",
>     "react-native-safe-area-view": "^1.1.1",
>     "react-native-web": "~0.19.6"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.20.0"
>   },
>   "private": true
> }
> ```
> 
> metro.config.js:
> 
> ```
> const { getDefaultConfig } = require('expo/metro-config');
> 
> /** @type {import('expo/metro-config').MetroConfig} */
> const config = getDefaultConfig(__dirname, {
> 	// Enable CSS support.
> 	isCSSEnabled: true,
> });
> 
> config.resolver.sourceExts.push('mjs', 'cjs');
> config.resolver.assetExts.push('mjs', 'cjs');
> config.watcher.additionalExts.push('mjs', 'cjs');
> 
> module.exports = config;
> ```
> 
> Error:
> 
> > Uncaught TypeError: (0 , _reactHookForm.useForm) is not a function

I had similar issues, I was able to fix it by just adding webpack bundler, I think expo 49 is not really compatible with react-hook-form most especially on the web

**Comment by OneHatRepo** [comment]
I have them working together fine on iOS & Android, but not on web.

**Comment by Hiba-Bazerbashi** [comment]
I have same issue with  expo 49 managed 
"expo": ^49.0.21,
"react-hook-form": ^7.49.2,
"@hookform/error-message": ^2.0.1,
"@hookform/resolvers": ^3.3.3,

metro.config.ts

`
const { getDefaultConfig } = require("expo/metro-config");

module.exports = (() => {
  const config = getDefaultConfig(__dirname );
  const { transformer, resolver } = config;
  config.transformer = {
    ...transformer,
    babelTransformerPath: require.resolve("react-native-svg-transformer")
  };
  config.resolver = {
    ...resolver,
    assetExts: resolver.assetExts.filter((ext:any) => ext !== "svg"),
    sourceExts: [...resolver.sourceExts, "svg"]
  };
  config.resolver.sourceExts.push('cjs');
  config.resolver.sourceExts.push('mjs');
  return config;
})();
`
on web I got this error 

  **Unable to resolve "react-hook-form" from "src\screens\authScreens\signUpScreen\SignUpScreen.tsx"**

`import { ErrorMessage } from "@hookform/error-message";`  give that error :
**Unable to resolve "react-hook-form" from "node_modules\@hookform\error-message\dist\index.esm.js"**

`import { yupResolver } from '@hookform/resolvers/yup';`
**Unable to resolve "react-hook-form" from "node_modules\@hookform\resolvers\yup\dist\yup.module.js"**
on android just stuck in splash screen

**Comment by OneHatRepo** [comment]
I was able to get them working together on web by switching to webpack bundler instead of metro. There seems to be a fundamental incompatibility between metro for web and react-hook-form.

**Comment by EvanBacon** [comment]
We have added mjs support in Expo SDK 50, this should resolve the issue.

**Comment by hadiDanial** [comment]
Is there a fix for this for React Native Web?
It's working for native, but it won't compile for web, giving the error: 
"Web Bundling failed 
Unable to resolve "react-hook-form" from "path\to\file\SignInScreen.tsx" "

I can't upgrade to Expo SDK 50 right now since it caused other issues in the project.

Were you able to fix this, @Hiba-Bazerbashi ?

**Comment by Hiba-Bazerbashi** [comment]
@hadiDanial .there's no way to get it to work on web with metro, it's kind
of wasting time  , but if you want to switch to webpack it works as answers
above, but i didnt do that it's not advisable to switch to webpack ,so
eaither to use another 3d party library or to upgrade to expo 50 ,  the
latter was my choice and expo 50 working fine with no issues right now ,
try to get it from npm  website not from expo docs

**Comment by gorbypark** [comment]
> Is there a fix for this for React Native Web? It's working for native, but it won't compile for web, giving the error: "Web Bundling failed Unable to resolve "react-hook-form" from "path\to\file\SignInScreen.tsx" "
> 
> I can't upgrade to Expo SDK 50 right now since it caused other issues in the project.
> 
> Were you able to fix this, @Hiba-Bazerbashi ?

@Hiba-Bazerbashi  @hadiDanial Can you post your metro.config.js?  I have a project on SDK49 and using expo web (expo-router/metro based) and the solution provided at the top of this issue works for me.  Here is my metro.config.js, there's a number of ways to accomplish it, but you just have to make sure you are adding the mjs extension so metro knows to bundle them.  You will also have to make sure to restart metro and clear the cache after making changes.
```js
/* eslint-disable no-undef */
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

module.exports = (async () => {
  const {
    resolver: { sourceExts },
  } = config;

  return {
    ...config,
    resolver: {
      ...config.resolver,
      sourceExts: [...sourceExts, 'mjs'],
    },
  };
})();
```

**Comment by hadiDanial** [comment]
@gorbypark That worked!
I'm not familiar with Metro, and I had the config in a .ts file, and you said .js, so I just checked and according to [metrobundler.dev](https://metrobundler.dev/docs/configuration/):

> A Metro config can be created in these three ways (ordered by priority):
> 
> metro.config.js
> metro.config.json
> The metro field in package.json 

Chuck it up to a beginner mistake. Your config works perfectly, thanks mate ^^
