### ISSUE TITLE
[expo-image][expo-web] Expo image cache policy warning

### ISSUE THREAD

**Issue by devoren** [expo/expo#23328]
### Minimal reproducible example

https://snack.expo.dev/@devoren/image-example

### Summary

After updating to SDK 49, the following issue appears:

<img width="458" alt="image" src="https://github.com/expo/expo/assets/99968085/3f17290e-e5f7-4559-b518-6a095f1ae30c">

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD    
    IDEs:
      Android Studio: AI-221.6008.13.2211.9477386
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: bare
```

**Comment by TomasSestak** [comment]
Shouldnt the example work on web? Im getting:
`Unable to resolve module 'react-native/Libraries/Image/AssetRegistry.js'
  Evaluating react-native/Libraries/Image/AssetRegistry.js
  Evaluating expo-image.js
  Evaluating App.js
  Loading App.js`

in the provided snack

**Comment by devoren** [comment]
@TomasSestak You can try now but "expo go" is still sdk 48 and doesn't show error

**Comment by aleqsio** [comment]
@TomasSestak these are two unrelated errors to be honest – the above is just a no-op warning that we need to hide, not a crash. For me, the provided snack works – what is your browser environment?

**Comment by TomasSestak** [comment]
@aleqsio it works now in the snack, i think @devoren changed version of the package in demo.

**Comment by TomasSestak** [comment]
@aleqsio is expo-image supported in next js?
