### ISSUE TITLE
Expo app not optimized for iPhone Xs Max

### ISSUE THREAD

**Issue by IanCStewart** [expo/expo#2332]
### Environment
Expo iOS version 2.8.2

### Steps to Reproduce
1. Open the app
2. See content outside of safe area bounding

### Expected Behavior
Expected the content to stay inside the safe area just as with the iPhone X

### Actual Behavior
Content such as the header and tab navigation at the bottom live within the safe area.

<img src="https://user-images.githubusercontent.com/14125280/46291467-da1a8880-c58e-11e8-9ac7-649082f33d71.jpg" alt="photo_2018-10-01_15-26-47" width="50%" />

**Comment by brentvatne** [comment]
fixed in https://github.com/expo/expo/commit/03220c86e2c07a88aeec6b40f2fac193cbcebfa4

will be released with SDK 31

**Comment by IanCStewart** [comment]
@brentvatne I'm not sure if the latest app store release should have fixed this as well. But the downloading bundle status bar still lives within the safe area.

<img src="https://user-images.githubusercontent.com/14125280/49225476-7a9cf580-f3e4-11e8-807c-1e72d154ab6f.PNG" alt="img_0300" width="50%" />
