### ISSUE TITLE
[SDK 49] Compatible dependencies check not run

### ISSUE THREAD

**Issue by ChromeQ** [expo/expo#23338]
### Summary

SDK 48 warns of potentially incompatible dependencies when running `expo start`:
![image](https://github.com/expo/expo/assets/625203/c74b47f4-e8b2-409d-98de-0f08a7f37e5c)

SDK 49 does not do this check so it is possible there are incompatible dependencies.

### Minimal reproducible example

- Use an existing sdk 48 project
- Delibrately update a dependency to the `@latest` - using `npm/yarn outdated` to check which have updates
- Run `expo start`
- Witness the expo-doctor version check warnings in the terminal before the QR code
- Upgrade to SDK 49 (`yarn upgrade expo@latest`)
- Do not update other dependencies
- Run `expo start`
- See metro starts and no dependency warning shown

### Environment

❯ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    SDKs:
      Android SDK:
        Android NDK: 25.2.9519653
    npmPackages:
      expo: 48.0.19 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: 0.18.12 => 0.18.12 
    Expo Workflow: managed

**Comment by ChromeQ** [comment]
I have investigated and found that expo start script calls `validateDependenciesVersionsAsync` in [startAsync](https://github.com/expo/expo/blob/dfb87e117b521c8531bdf42a42be12fbebe8b707/packages/%40expo/cli/src/start/startAsync.ts#L125)

The difference between sdk48 and sdk49 is the `options.devClient`.
In v48 the option is set on a simple check of whether the args contain `--dev-client` https://github.com/expo/expo/blob/5c53875b7ea538a9732dfe614212200685d89f2c/packages/%40expo/cli/src/start/resolveOptions.ts#L59
In v49 the option is a little more complex and tries to get the `--dev-client` or `--go` args, but if both missing it will always be `true` when you have `expo-dev-client` in your package.json dependencies. https://github.com/expo/expo/blob/dfb87e117b521c8531bdf42a42be12fbebe8b707/packages/%40expo/cli/src/start/resolveOptions.ts#L49-L52

This causes `options.devClient` to be true, which then fails the conditional check in my first link, meaning you don't see the warnings.

I would expect the `expo start` script should show the dependencies warnings regardless of whether I am running a dev client or not, unless I am missing a reason it is like that and not aware as it is not applicable to my use case.

The fix should be as simple as:
```
// expo/packages/@expo/cli/src/start/startAsync.ts:L125
-    if (!settings.webOnly && !options.devClient) {
+    if (!settings.webOnly) {
```

**Comment by ChromeQ** [comment]
Not steal

**Comment by ChromeQ** [comment]
Not stale

**Comment by ChromeQ** [comment]
Not stale

**Comment by keith-kurak** [comment]
Hi @ChromeQ , apologies for this getting lost in the shuffle. I'm going to do some follow-up on this.

I think the current behavior is intended, as the default in SDK 49 is to assume you're on a dev client if you have `expo-dev-client` installed; thus, the version recommendations are not as universally hard-and-fast, as not updating wouldn't result in your JavaScript becoming incompatible with your native runtime (as you built the native runtime with those versions). So, warning about versions when you're running a development build could result in false positives that could introduce bugs if you updated them (without the corresponding new dev build).

That said, not all of these version recommendations are created equal. It's generally recommended to keep both up-to-date with the latest patch versions of Expo packages, as these can provide bugfixes, building a new native runtime as your release schedule allows. These version checks were initially developed when Expo Go was the primary mechanism for testing in a local development mode, and now that's no longer the case. How to provide more contextual advice on what to upgrade and when is definitely something we're looking into. For the time being, you can still always get all of the version warnings (regardless of whether you're running a dev client or Expo Go) by running `npx expo-doctor@latest`.
