### ISSUE TITLE
DetachBuildConstants.java Causing Build Problems

### ISSUE THREAD

**Issue by redreceipt** [expo/expo#2333]
We detached from Expo but are running into some issues on Android. How does the DetachBuildConstants.java file get generated? It’s used in MainActivity.java to set the development URL but it needs to be ignored from my repo because that URL is different locally and I need to set up the file correctly in my CI when it builds.

**Comment by esamelson** [comment]
Hi @redreceipt - that file is generated at build time, as part of the `generate-dynamic-macros` step of the Android project. Since your development URL will change depending on your local IP address, it should be ignored. (Note that the contents of that file do not matter for production builds, only debug.) What errors are you running into with it?

**Comment by redreceipt** [comment]
I can’t add it to my `.gitignore` because it’s not generated, it’s simply updated in place. So when it doesn’t exist on someone’s machine, the build throws a compile error. And because I have to have it in my repo, it shows up modified every time I build. Very frustrating. I’m open to suggestions.

**Comment by redreceipt** [comment]
This image illustrates what I mean. An example of a brand new machine with `DetachBuildConstants.java` ignore from the repo:
<img width="681" alt="screen shot 2018-10-04 at 8 53 38 pm" src="https://user-images.githubusercontent.com/2659478/46510555-b8800200-c817-11e8-8ff2-4ceeed47b22b.png">

**Comment by esamelson** [comment]
@redreceipt ah, I see. Instead of ignoring it, you could try using the git `--assume-unchanged` flag: https://stackoverflow.com/a/3320183/6806464 .

Sorry, we understand this workflow is inherently a bit clunky. If you have an idea for how to improve it we would gladly accept a PR!

**Comment by redreceipt** [comment]
Excellent, that should work!

As far as a suggestion to improve, I'm brainstorming here but couldn't `exp prepare-detached-build` (which is what is getting called during the build process) simply create if the file doesn't exist?

**Comment by brettdh** [comment]
Running into this recently as well. I’m planning to add a prebuilt step that writes the file with dummy contents, so the file always exists but can still be gitignored - but I’d be interested to know if anyone else has a better workaround.

**Comment by tsapeta** [comment]
With SDK38 release we officially removed support for ExpoKit (it's the last SDK providing ExpoKit that you can upgrade to). Taking this into account, I'm closing this issue and recommend everyone to eject to bare workflow instead of ExpoKit.
