### ISSUE TITLE
Recording in the background not work on Android 

### ISSUE THREAD

**Issue by amibug** [expo/expo#23337]
### Minimal reproducible example

-

### Summary

Recording in the background for longer than 15 seconds is not possible in newer versions of Android. This is because Android's newer versions require a foreground service. Is it possible to add foreground service support to expo-av?

SDK Version: 48
Platforms: Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.10.0/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
      Watchman: 2023.05.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/xx/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.1.0 => 18.1.0
      expo: ^48.0.19 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
      react-native-web: ~0.18.7 => 0.18.12
    Expo Workflow: bare

**Comment by Emmanueldmlr** [comment]
I successfully implemented this without ejecting from Expo and wrote an article detailing the step-by-step process.
Here is the link: https://drebakare.medium.com/enabling-background-recording-on-android-with-expo-the-missing-piece-41a24b108f6d
