### ISSUE TITLE
[SDK 49][expo-updates][android] gradle plugin error on build when running on Windows

### ISSUE THREAD

**Issue by yerevin** [expo/expo#23344]
### Minimal reproducible example

https://github.com/yerevin/expo-updates-node-issue

### Summary

Hi,

After upgrade from Expo 48 to Expo 49 I ran into issue with `expo-updates` gradle plugin, it throws below error related to attached line.

It is related to project with flavors as when I tried to reproduce it on simple bare-template it wasn't an error, but after I added extra flavors it started to fail. (without multiple flavors gradle plugin doesn't reach line with error).

I think it can be worth mention I'm on Windows 11.

### Line causing error: 
https://github.com/expo/expo/blob/sdk-49/packages/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt#L78

### Error:
```
> Task :app:createDevelopmentDebugExpoManifest FAILED
'[node' is not recognized as an internal or external command,
operable program or batch file.
```

---

### Off topic side note:
I think it can be worth to add multi flavor (Android) / bundle id (iOS) template to templates projects for beta testing as I think in last update from Expo 47 to Expo 48 also there was issue caught after SDK release related to projects with flavors and having multi flavor is quiet common thing. (I'm not adding it to be offensive in any way, just a tip)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9862592
    npmPackages:
      expo: 49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
    Expo Workflow: bare

**Comment by yerevin** [comment]
Patch fix for this issue
```patch
diff --git a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
index 2d81db9..fa5454b 100644
--- a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
+++ b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
@@ -75,7 +75,7 @@ abstract class ExpoUpdatesPlugin : Plugin<Project> {
         }
 
         if (Os.isFamily(Os.FAMILY_WINDOWS)) {
-          it.commandLine("cmd", "/c", args)
+          it.commandLine("cmd", "/c", *args.toTypedArray())
         } else {
           it.commandLine(args)
         }
```

**Comment by RicardoBrito1938** [comment]
Hey guys, i got build failed but it happened with this message 

"> Task :app:createBundleReleaseJsAndAssets FAILED
Unknown or unexpected option: --platform"

**Comment by yerevin** [comment]
@RicardoBrito1938 
Can you paste the command you are running?
It looks like issue is in what command you are running than some build level error

**Comment by RicardoBrito1938** [comment]
> @RicardoBrito1938 
> Can you paste the command you are running?
> It looks like issue is in command you are running than some build level error

Yes , sure, here it it

npx expo prebuild --clean

cd android 

./gradlew clean 

./gradlew assembleRelease --stacktrace --debug 


These are the local commands I run to get the same error eas is triggering

**Comment by emilyseibert** [comment]
I'm also running into a build level error - https://github.com/expo/expo/issues/23488

`./gradlew :app:assembleDebug :app:assembleAndroidTest -DtestBuildType=debug`

**Comment by ElSierra** [comment]
I get this error on a fresh project initialization on sdk 49, prebuild

![image](https://github.com/expo/expo/assets/25958179/53fe08a6-f879-40a3-9287-26e80868da12)

> Task :expo-modules-core:configureCMakeDebug[arm64-v8a] FAILED

FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using E:\Desktop\Projects\bare-expo\node_modules\expo-modules-core\android\CMakeLists.txt: -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'

**Comment by jogle1205** [comment]
I am experiencing a similar error with expo-updates, after upgrading to v49 from 48. The eas build finishes with no errors. But the finished build is immediately closed on the device on open. When I run adb logcat it shows expo updates issues:

java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. null

**Comment by weykon** [comment]
> Patch fix for this issue
> 
> ```diff
> diff --git a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
> index 2d81db9..fa5454b 100644
> --- a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
> +++ b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
> @@ -75,7 +75,7 @@ abstract class ExpoUpdatesPlugin : Plugin<Project> {
>          }
>  
>          if (Os.isFamily(Os.FAMILY_WINDOWS)) {
> -          it.commandLine("cmd", "/c", args)
> +          it.commandLine("cmd", "/c", *args.toTypedArray())
>          } else {
>            it.commandLine(args)
>          }
> ```

it worked with #23983 code !

**Comment by yerevin** [comment]
I removed my above patch fix, removed node_modules, updated to expo-update@0.18.2, did `gradlew clean` and did fresh
`expo run:android --variant prodDebug` and I'm still getting
```
Task :app:createProdDebugExpoManifest FAILED
'[node' is not recognized as an internal or external command, operable program or batch file.
``` 

After reviewing the PR fix code the fix is on other line than my previous patch fix - issue looks like is on https://github.com/expo/expo/blob/ca41be93e1c9ff0c24e7cf05874638162655218e/packages/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt#L78 instead on lines 90 - 95

**Comment by yerevin** [comment]
It looks like for me PR https://github.com/expo/expo/pull/23983 brought regression and I have to patch fix also line 92
Current patch fix for `expo-updates@0.18.2` which I used to successfully build local development build

```patch
diff --git a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
index 6cd4226..b010ebb 100644
--- a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
+++ b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
@@ -75,7 +75,7 @@ abstract class ExpoUpdatesPlugin : Plugin<Project> {
         }
 
         if (Os.isFamily(Os.FAMILY_WINDOWS)) {
-          it.commandLine("cmd", "/c", args)
+          it.commandLine("cmd", "/c", *args.toTypedArray())
         } else {
           it.commandLine(args)
         }
@@ -89,7 +89,7 @@ abstract class ExpoUpdatesPlugin : Plugin<Project> {
       project.exec {
         val args = listOf(*nodeExecutableAndArgs.get().toTypedArray(), "-e", "console.log(require('path').dirname(require.resolve('expo-updates/package.json')));")
         if (Os.isFamily(Os.FAMILY_WINDOWS)) {
-          it.commandLine("cmd", "/c", args)
+          it.commandLine("cmd", "/c", *args.toTypedArray())
         } else {
           it.commandLine(args)
         }
```

@weykon were you able to build successfully without patch fix on line 92 after upgrade to expo-update@0.18.2?

**Comment by weykon** [comment]
// 很抱歉是我的遗漏，在78行和92行都需要修改`args-> *args.toTypedArray()`才能打包成功
I apologize for the oversight. To successfully build release on it, need to modify `args -> *args.toTypedArray()` on both line 78 and line 92.

**Comment by weykon** [comment]
I apologize for the confusion. What I meant to say is that the code from #23983 needs to be combined with your code in order for it to run successfully. 
I just happened to use *args.toTypedArray() for all the args modifications, and it worked successfully. Cheers to that!

**Comment by KodyKendall** [comment]
I am running into this same issue on Mac after upgrading to Expo SDK 49. > Configure project :app
 ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.12)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot query the value of extension 'react' property 'entryFile' because it has no value available.

**Comment by ediabal** [comment]
> I am running into a similar issue on Mac after upgrading to Expo SDK 49 and react-native 0.72.4:
> 
> ```
>  ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.12)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Cannot query the value of extension 'react' property 'entryFile' because it has no value available.
> ```
> 
> This issue doesn't occur if I use expo-updates: "~0.16.4", however then all my expo packages don't seem to be linking correctly and they can't compile.
> 
> I am using gradle-7.5.1 in gradle-wrapper.properties, because I was having similar compilation issues with expo 49 and gradle, and this was the only way I could get gradle to run.
> 
> distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip

By using `istributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip` are you able to get your project to build on EAS? I'm running into the exact same issue on my end.

**Comment by glairnarra31** [comment]
> I am running into a similar issue on Mac after upgrading to Expo SDK 49 and react-native 0.72.4:
> 
> ```
>  ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.12)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Cannot query the value of extension 'react' property 'entryFile' because it has no value available.
> ```
> 
> This issue doesn't occur if I use expo-updates: "~0.16.4", however then all my expo packages don't seem to be linking correctly and they can't compile.
> 
> I am using gradle-7.5.1 in gradle-wrapper.properties, because I was having similar compilation issues with expo 49 and gradle, and this was the only way I could get gradle to run.
> 
> distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip

What worked for me was explicitly defining by uncommenting `entryFile` in `android/app/build.gradle` and then replacing it with the path of the index file which has the `registerRootComponent` expo method.
```
    entryFile = file("../../index.js")
```

**Comment by KodyKendall** [comment]
> > I am running into a similar issue on Mac after upgrading to Expo SDK 49 and react-native 0.72.4:
> > ```
> >  ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.12)
> > 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > A problem occurred configuring project ':app'.
> > > Cannot query the value of extension 'react' property 'entryFile' because it has no value available.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This issue doesn't occur if I use expo-updates: "~0.16.4", however then all my expo packages don't seem to be linking correctly and they can't compile.
> > I am using gradle-7.5.1 in gradle-wrapper.properties, because I was having similar compilation issues with expo 49 and gradle, and this was the only way I could get gradle to run.
> > distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip
> 
> @KodyKendall, by using `distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip` are you able to get your project to build on EAS? I'm running into the exact same issue on my end.

I had to switch over to distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip
to get my project to build, and I ended up removing a lot of the expo libraries since they were having build issues. Painful, but I couldn't wait any longer.

**Comment by glairnarra31** [comment]
> > > I am running into a similar issue on Mac after upgrading to Expo SDK 49 and react-native 0.72.4:
> > > ```
> > >  ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.12)
> > > 
> > > FAILURE: Build failed with an exception.
> > > 
> > > * What went wrong:
> > > A problem occurred configuring project ':app'.
> > > > Cannot query the value of extension 'react' property 'entryFile' because it has no value available.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This issue doesn't occur if I use expo-updates: "~0.16.4", however then all my expo packages don't seem to be linking correctly and they can't compile.
> > > I am using gradle-7.5.1 in gradle-wrapper.properties, because I was having similar compilation issues with expo 49 and gradle, and this was the only way I could get gradle to run.
> > > distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip
> > 
> > 
> > @KodyKendall, by using `distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip` are you able to get your project to build on EAS? I'm running into the exact same issue on my end.
> 
> I had to switch over to distributionUrl=https://services.gradle.org/distributions/gradle-8.0.1-all.zip to get my project to build, and I ended up removing a lot of the expo libraries since they were having build issues. Painful, but I couldn't wait any longer.

Yup, that should be the distributionUrl as well for latest react-native 0.72.4 as shown here: https://react-native-community.github.io/upgrade-helper/?from=0.71.13&to=0.72.4#RnDiffApp-android-gradle-wrapper-gradle-wrapper.properties

**Comment by amit13091992** [comment]
even after installing expo-updates still getting same error. Can anyone update on this?

**Comment by amit13091992** [comment]
> > Patch fix for this issue
> > ```diff
> > diff --git a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
> > index 2d81db9..fa5454b 100644
> > --- a/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
> > +++ b/node_modules/expo-updates/expo-updates-gradle-plugin/src/main/kotlin/expo/modules/updates/ExpoUpdatesPlugin.kt
> > @@ -75,7 +75,7 @@ abstract class ExpoUpdatesPlugin : Plugin<Project> {
> >          }
> >  
> >          if (Os.isFamily(Os.FAMILY_WINDOWS)) {
> > -          it.commandLine("cmd", "/c", args)
> > +          it.commandLine("cmd", "/c", *args.toTypedArray())
> >          } else {
> >            it.commandLine(args)
> >          }
> > ```
> 
> it worked with #23983 code !


even after installing expo-updates still getting same error. Tried this solution as well. Can anyone update on this?
