### ISSUE TITLE
[docs] Unclear instructions on how to get Google Maps working for MapView module

### ISSUE THREAD

**Issue by sreuter** [expo/expo#23347]
### Summary

When using Expo 49 and following the [instructions](https://docs.expo.dev/versions/latest/sdk/map-view/#ios) for deploying an app with Google Maps support in iOS, the resulting app throws a runtime error.

```
ERROR  react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.
```

Several discussions exist around this issue, but none of them includes a straight answer.

https://github.com/react-native-maps/react-native-maps/discussions/4661
https://cuneyt.aliustaoglu.biz/en/using-google-maps-as-provider-in-ios-with-react-native/

Some users suggest manually adding pods, while others suggest adding something to the build phases. As manual changes to anything within `ios/` would only be local (not having any effect during EAS builds) and would be overwritten whenever the `ios` folder is getting recreated, I don't think these are great solutions to the issue.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps

**Comment by brentvatne** [comment]
the setup should be handled by the config plugin: https://github.com/expo/expo/blob/6aad17b56b4c3fc317253e86909726805697d789/packages/%40expo/config-plugins/src/ios/Maps.ts

if you are using [CNG](https://docs.expo.dev/workflow/continuous-native-generation/) you may need to run `npx expo prebuild -p ios --clean` to automatically configure it. if you have a bare project, you will need to follow the instructions in the react-native-maps docs.

**Comment by sreuter** [comment]
Thanks @brentvatne for the hint of trying out `--clean`, I usually just bust the `.ios` folder and build again. Unfortunately, this still didn't resolve it. Is the config plugin not working with the latest versions of Expo + React Native Maps?

**Comment by daavidwlf** [comment]
Having the same issue, anything new wich could help solve the problem?

**Comment by kpamidov** [comment]
@keith-kurak are you investigating the problem or you are already resolving it? Is there any quick fix for this one to be able to run google maps on IOS with EAS development build?

**Comment by djnewage** [comment]
i am still having error issues
react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.

**Comment by daavidwlf** [comment]
@djnewage you need to add the API-Keys from you Google Cloud Manager to your app.json. After you've done this just rebuild the app and everything should work fine.

Here's the documentation:
https://docs.expo.dev/versions/latest/sdk/map-view/#iosand

**Comment by TimoVie** [comment]
I'm also having this issue, still after adding the api key to my app.json. Any other idea?

**Comment by djnewage** [comment]
got it to work!!! follow this video it helped! 

https://www.youtube.com/watch?v=jgi_I7nk3kE&list=PLeIJUF3PiXDfOoCWgD4uibjkGQMT7a78v

**Comment by nielmendegorin** [comment]
I'm also having this issue. Any fixes?

**Comment by daavidwlf** [comment]
You need to add the API-Keys which you can find in your Google Cloud Console to your app.json

reference: https://docs.expo.dev/versions/latest/sdk/map-view/#deploy-app-with-google-maps
