### ISSUE TITLE
[docs] MapView docs suggest support for web, which doesn't seem to be a thing

### ISSUE THREAD

**Issue by sreuter** [expo/expo#23346]
### Summary

The bottom section of the [MapView docs](https://github.com/expo/expo/blob/main/docs/pages/versions/unversioned/sdk/map-view.mdx) suggests that there is experimental support for web.

Including `react-native-maps` is a web-build causes the following error with SDK 48 but also earlier versions: 

```
../node_modules/react-native/Libraries/Animated/components/AnimatedImage.js:13
Module not found: Can't resolve '../../Image/Image'
  11 | import type {AnimatedComponentType} from '../createAnimatedComponent';
  12 |
> 13 | import Image from '../../Image/Image';
  14 | import createAnimatedComponent from '../createAnimatedComponent';
  15 | import * as React from 'react';
  16 |
```

Even if it would compile successfully, [this](https://github.com/react-native-maps/react-native-maps/blob/master/src/MapView.web.ts) suggests that the component would only show a `Not Implemented` view.

@amandeepmittal @EvanBacon As contributors to this section in the docs, could you maybe shed some light on the situation? I assume this was supported at some point but then got removed?

There seems to be an [alternative](https://github.com/teovillanueva/react-native-web-maps) from @teovillanueva, but it doesn't seem to be in feature parity yet, e.g. some MapView configuration items don't seem to be supported.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/map-view/

**Comment by brentvatne** [comment]
thanks, it seems that maybe this has regressed in react-native-maps (as tends to happen with experimental features), so i have removed it from the docs: https://github.com/expo/expo/commit/9d00348f59919727293fbd32a8fdff64d7e207b8
