### ISSUE TITLE
Unhandled Crash on Android due to Dev App Bug Triggering React-Native Unhandled Type Cast

### ISSUE THREAD

**Issue by ghost** [expo/expo#23348]
### Minimal reproducible example

https://snack.expo.dev/txe40cJ5i

### Summary

This is a report of a bug cascade of potentially 3 separate bugs on 3 separate layers, each triggering the next.

I'm not exactly sure if any part of this bug is affecting the Expo SDK itself, but I'm hoping you'll narrow it down. At any rate, I'm guessing a part of this bug ought to be reported to the React-Native Team. I'm hoping you'll bump this up to them as well, but in case you need me to report to them myself, I'm hoping you can indicate to me what exactly to report.

Setting a style attribute such as 'flex' to a string such as '0', '1', '0 0 auto', etc. is the trigger bug on the Dev App level.

This triggers java.lang.String cannot be cast to java.lang.Double in react native Android Java implementation.

This further triggers the 3rd potential unhandled crash of the Expo Go app on Android.

![Expo Go Screenshot on Android](https://github.com/expo/expo/assets/138805646/9600c0be-8bb5-4b02-a83a-812c627e488a)

Expected results: The bugs should be gracefully handled at each level.

Additionally the expo cli command, when running an app, reports: 'Some dependencies are incompatible with the installed expo version:'. However, the reported expected versions ARE the ones specified in package.json. However, npm automatically upgrades to non-breaking-change updated versions. Wish the cli could detect this in a better manner.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.3.1 - \NODE\20.3.1\x64\node.EXE
      npm: 9.7.2 - \NODE\20.3.1\x64\npm.CMD
    npmPackages:
      expo: ~48.0.18 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

**Comment by brentvatne** [comment]
can you try to reproduce this in sdk 49? this may be handled better now

**Comment by ThejXM** [comment]
@brentvatne:
Still reproducible with SDK 49.
I can't provide MRE on snack as snack doesn't yet have 49.
However, you can create an empty project with npx create-expo-app, and change `flex: 1,` near the bottom of App.js to `flex: '1',`, and run to see the result.

![SSA_002](https://github.com/expo/expo/assets/138805646/3066893b-771f-4c1a-8fe7-f0ec0a7f47ac)
