### ISSUE TITLE
[iOS][expo-camera] camera.getAvailablePictureSizesAsync() returns undefined

### ISSUE THREAD

**Issue by ericmatte** [expo/expo#23342]
### Minimal reproducible example

https://snack.expo.dev/@ericmatte/camera-ios-getavailablepicturesizesasync-undefined

### Summary

Tested on an iPhone and an iPad 10th generation.

Calling `camera.getAvailablePictureSizesAsync()` returns `undefined`.

What I don't understand is that the list on iOS seems to be hardcoded, so I should receive something:
https://github.com/expo/expo/blob/main/packages/expo-camera/ios/EXCamera/CameraViewModule.swift#L331-L341

On Android, it is working if I pass a ratio.

| iOS | Android |
|--------|--------|
| ![CleanShot 2023-07-06 at 11 21 06@2x](https://github.com/expo/expo/assets/9013072/46f1cb3f-161a-4f20-b85a-1d0a65bd7f97) | ![image](https://github.com/expo/expo/assets/9013072/733afb4a-e3e4-433a-a415-79c6308f6924) |

---

Also, even if I pass a hardcoded value from the list to `<Camera pictureSize="1280x720" />`, I still receive a larger picture of `1726x1296`. See https://github.com/expo/expo/issues/2874#issuecomment-1623857898.

### Environment

<details><summary>Show environment</summary>
<p>

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 18.16.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - /opt/homebrew/bin/npm
      Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /Users/usr/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 33.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 4 Arctic Fox 2020.3.1 Patch 4
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.4 => 18.0.4 
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.12.0
    Expo Workflow: bare
```

</p>
</details>

**Comment by cjthompson** [comment]
Interesting because when I call it on Android (SDK 49), I get:

```
[Error: Call to function 'ExponentCamera.getAvailablePictureSizes' has been rejected.
→ Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference]
```

**Comment by Maher-Bouzid** [comment]
> Interesting because when I call it on Android (SDK 49), I get:
> 
> ```
> [Error: Call to function 'ExponentCamera.getAvailablePictureSizes' has been rejected.
> → Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference]
> ```

To fix that error you need to provide a ratio(16:9 or 4:3) and that fixed it for me

**Comment by maxsl89** [comment]
Did you figure out how to solve the issue?

**Comment by ericmatte** [comment]
@maxsl89 no: The problem is still present.

So I ended up making my own wrapper over the `expo-camera`, and instead I use expo-image-manipulator to change the image size to my desired size:

```tsx
const DESIRED_PICTURE_HEIGHT = 960;
const expoCameraRef = useRef<ExpoCamera>(null);

const takePictureAsync = async () => {
  if (!expoCameraRef.current) throw new Error('Camera ref is not initialized');

  const picture = await expoCameraRef.current.takePictureAsync(CAMERA_OPTIONS);
  const height = Math.min(picture.height, DESIRED_PICTURE_HEIGHT);

  const result = await ImageManipulator.manipulateAsync(picture.uri, [
    { resize: { [picture.width < picture.height ? 'width' : 'height']: height } },
  ]);

  return result;
};
```

**Comment by PavelPolyakov** [comment]
Still returns `undefined` to me, `"expo": "~49.0.15",`.
