### ISSUE TITLE
[expo-image] ImageAnalyzer is unavailable in Mac Catalyst

### ISSUE THREAD

**Issue by zubakskees** [expo/expo#23354]
### Minimal reproducible example

Installed expo-image, added a Mac Catalyst destination in Xcode

### Summary

Got this:

<img width="270" alt="Screenshot 2023-07-07 at 3 16 53 AM" src="https://github.com/expo/expo/assets/135639154/e95083af-9eed-4040-9b49-759dc0232533">

I realize Mac Catalyst isn't yet supported, but since a goal of Expo is to fit within existing bare workflows (I'm using a prebuild/ejected workflow) it'd be good to remove this compile error.

The [ImageView file](https://github.com/expo/expo/blob/42df119b2b00077b66778bdce9fbe9968b12eeb6/packages/expo-image/ios/ImageView.swift#L396-L445) already has `@available` markers and `#available` guards for the `ImageAnalyzer` API calls to check for an iOS version, so may not be hard to add a `maccatalyst` check.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.asdf/installs/nodejs/18.16.1/bin/node
      npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/admin/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    Expo Workflow: bare
```

**Comment by brentvatne** [comment]
we don't explicitly support mac catalyst at the moment. if you'd like to submit a pr to resolve this, it'd be welcome!

**Comment by kesha-antonov** [comment]
Fix here https://github.com/expo/expo/pull/24880
