### ISSUE TITLE
WARN  Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property.

### ISSUE THREAD

**Issue by ThejXM** [expo/expo#23359]
### Minimal reproducible example

https://github.com/ThejXM/Expo-Hello

### Summary

WARN  Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.

On starting empty App created with npx create-expo-app, by running cli command expo start --clear --tunnel --port 19000, and opening app in Expo Go (2.29.2) on iOS (16.5.1, iPhone 11 Pro).

![SSI_001](https://github.com/expo/expo/assets/138805646/91576e95-5387-4ad4-bd72-449e2cb0321a)

Expected behaviour: Empty app (Hello, World!) should not show any errors or warnings.

I did even try deleting everything including empty app, all installed node_modules, package.json, .lock, npm-cache, and Node.js installation as well, and reinstalling latest versions and recreating a fresh Hello App, but got same warning.

If this API was supposed to be removed in 45, why:

    "node_modules/expo": {
      "version": "48.0.20",
      "resolved": "https://registry.npmjs.org/expo/-/expo-48.0.20.tgz",
      "integrity": "sha512-SDRlLRINWWqf/OIPaUr/BsFZLhR5oEj1u9Cn06h1mPeo8pqv6ei/QTSZql4e0ixHIu3PWMPrUx9k/47nnTyTpg==",
      "dependencies": {
        "@babel/runtime": "^7.20.0",
        "@expo/cli": "0.7.3",
        "@expo/config": "8.0.5",
        "@expo/config-plugins": "6.0.2",
        "@expo/vector-icons": "^13.0.0",
        "babel-preset-expo": "~9.3.2",
        "cross-spawn": "^6.0.5",
        "expo-application": "~5.1.1",
        "expo-asset": "~8.9.1",
        "expo-constants": "~14.2.1",
        "expo-file-system": "~15.2.2",
        "expo-font": "~11.1.1",
        "expo-keep-awake": "~12.0.1",
        "expo-modules-autolinking": "1.2.0",
        "expo-modules-core": "1.2.7",
        "fbemitter": "^3.0.0",
        "getenv": "^1.0.0",
        "invariant": "^2.2.4",
        "md5-file": "^3.2.3",
        "node-fetch": "^2.6.7",
        "pretty-format": "^26.5.2",
        "uuid": "^3.4.0"
      },
      "bin": {
        "expo": "bin/cli.js"
      }
    },
    "node_modules/expo-application": {
      "version": "5.1.1",
      "resolved": "https://registry.npmjs.org/expo-application/-/expo-application-5.1.1.tgz",
      "integrity": "sha512-aDatTcTTCdTbHw8h4/Tq2ilc6InM5ntF9xWCJdOcnUEcglxxGphVI/lzJKBaBF6mJECA8mEOjpVg2EGxOctTwg==",
      "peerDependencies": {
        "expo": "*"
      }
    },
    "node_modules/expo-asset": {
      "version": "8.9.2",
      "resolved": "https://registry.npmjs.org/expo-asset/-/expo-asset-8.9.2.tgz",
      "integrity": "sha512-aHMaZkIG5/UoguINEHm2ln/KviU2m/yuryslnhCKR3KXRxiLnMhxmrONLGbknuNE0O1iCaprrl1w3y71u01Rpw==",
      "dependencies": {
        "blueimp-md5": "^2.10.0",
        "expo-constants": "~14.3.0",
        "expo-file-system": "~15.3.0",
        "invariant": "^2.2.4",
        "md5-file": "^3.2.3",
        "path-browserify": "^1.0.0",
        "url-parse": "^1.5.9"
      }
    }

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.4.0 - \NODE\20.4.0\x64\node.EXE
      npm: 9.8.0 - \NODE\20.4.0\x64\npm.CMD
    npmPackages:
      metro: ^0.77.0 => 0.77.0
    Expo Workflow: managed

**Comment by brentvatne** [comment]
this is resolved in sdk 49. https://blog.expo.dev/expo-sdk-49-c6d398cdf740

**Comment by asawyers** [comment]
Is there another workaround besides upgrading?

**Comment by rentonhead** [comment]
i have same issue, Is there a temporary solution to this problem?

**Comment by omatsola619** [comment]
please who has been able to resolve this issue ?

**Comment by Jokotoye18** [comment]
> i have same issue, Is there a temporary solution to this problem?

+1

**Comment by omatsola619** [comment]
i just deleted my node modules and package-lock.json file and re installed npm and mine was resolved

**Comment by brentvatne** [comment]
this is resolved in sdk 49

**Comment by redheet** [comment]
try use `expo-cli upgrade` this working for me

**Comment by Luke-lsm** [comment]
Had this warning crop up on a few of our apps and we are not able to upgrade yet, so a **temporary** workaround, for anyone looking, was to force the resolution of expo constants in our `package.json`

```
  "resolutions": {
    "expo-constants": "14.2.1"
  },
```

The warning cropped up as there we're two differing versions being included from expo asset and expo sdk. 

This is not a fix, just a temporary workaround

**Comment by KGMalith** [comment]
` "resolutions": {
    "expo-constants": "14.2.1"
  },`

@Luke-lsm Thanks. It worked for me
