### ISSUE TITLE
Screen Orientation "default" not changing on device rotate on iOS Expo Go on initial load

### ISSUE THREAD

**Issue by ThejXM** [expo/expo#23368]
### Minimal reproducible example

https://snack.expo.dev/Fy1keGnRx

### Summary

On Expo Go on iOS Device (iPhone 11 Pro), with App expo.orientation set to "default" in app.json, app does not reorient on device rotate initially, after fresh app load. However, after the Expo Menu has been triggered and shown (with 3 finger touch or shake) and closed, or app reloaded, the reorientation starts working again. On subsequent reloads from menu, the reorientation still works. However, if you go back to Home and load the app afresh, it again fails to reorient initially, on device rotate.

P.S.: I have two other issues reported and tagged "needs review", possibly due to attached screenshots, for your attention.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.4.0 - \NODE\20.4.0\x64\node.EXE
      npm: 9.8.0 - \NODE\20.4.0\x64\npm.CMD
    Expo Workflow: managed

**Comment by supryan** [comment]
I might have a similar issue. `orientation` is set to `portrait` for me and orientation used to work with `ScreenOrientation.unlockAsync()`. However Expo Go app will not rotate to landscape and `ScreenOrientation.addOrientationChangeListener` doesn't seem to be firing.

**Comment by ThejXM** [comment]
@supryan, Your issue may not be related. Check expo > orientation in app.json. You should either remove that line or set the value of “orientation” to “default”. I think that will solve your issue. I think my issue is specifically different.

**Comment by supryan** [comment]
@ThejXM I want to prevent landscape orientation initially. Removing that line or setting to default will allow orientation to change to landscape. I used to be able to unlock the orientation and then listen for the change with `addOrientationChangeListener` but that no longer seems to be working as of yesterday? I also have tried:


```
[
  'expo-screen-orientation',
  {
    initialOrientation: 'PORTRAIT_UP',
  },
]
```

But doesn't appear to do anything. Did something break relating to orientation with Expo Go yesterday?

**Comment by ThejXM** [comment]
@supryan, Ah, I understand your specific requirement now.

If you like, you can try the following simple but dirty workaround:

You could try to remove or set to default in app.json but at the same time, set the initialOrientation to PORTRAIT_UP and also do a lockAsync() globally at the start. You can unlock later any time as required.

That’s not the cleanest solution, but it may get you through until someone fixes the issue properly.

**Comment by supryan** [comment]
@ThejXM thank you for taking the time to help! It's weird, your suggestion does seem to work on iOS Simulator but can't get `expo-screen-orientation` to work with that behavior on a physical device anymore since yesterday (Portrait lock is off in system settings).

**Comment by ThejXM** [comment]
Related: [Issue 23373](https://github.com/expo/expo/issues/23373)

@supryan, Just posted this. It's something I've been trying to diagnose myself, but my behaviour was manifest as changed (or rather unchanging) element height. Now I see that issue is in reality similar to yours.

**Comment by supryan** [comment]
@ThejXM yup, just ran your example and that's exactly what I'm experiencing. Thank you for making putting that up. Will keep an eye out for a fix.

**Comment by behenate** [comment]
Ignore the reference to #23456 it was referenced by accident (similar issues) 😅

**Comment by behenate** [comment]
The issue has been fixed in https://github.com/expo/expo/pull/23581

**Comment by ycldz** [comment]
Expo: "~48.0.15"
expo-screen-orientation: "~5.1.1"
IOS Simulator: Iphone 14 Pro Max / v16.4
Real Device: Iphone 11 / v16.6

app.json in orientation deleted

app.json plugins in  added
[
   "expo-screen-orientation",
   {
        "initialOrientation": "DEFAULT"
   }
],

await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE);

It works fine on the simulator but not on the real device, has anyone solved this problem?
