### ISSUE TITLE
Convert modules to TypeScript and rework APIs

### ISSUE THREAD

**Issue by ide** [expo/expo#2336]
The main SDK is mostly converted to TypeScript but we need to convert the modules that have been split out as well. This is also a good time to rework APIs that aren't coherent or don't follow the Expo conventions or are too clever.

These are the modules to convert:

- [x] expo-ads-admob
- [x] expo-analytics-segment
- [x] expo-app-auth
- [x] expo-asset
- [x] expo-barcode-scanner
- [x] expo-camera
- [x] expo-constants
- [x] expo-contacts
- [x] expo-core
- [x] expo-face-detector
- [x] expo-file-system
- [x] expo-firebase-*
- [x] expo-font
- [x] expo-font-interface
- [x] expo-gl
- [x] expo-google-sign-in
- [x] expo-local-authentication
- [x] expo-location
- [x] expo-media-library
- [x] expo-module-template
- [ ] expo-payments-stripe
- [x] expo-permissions
- [x] expo-print
- [x] expo-react-native-adapter
- [x] expo-sensors
- [x] expo-sms

**Comment by AlistairClark7** [comment]
Would this be why I'm getting the following error:

```error TS2339: Property 'SMS' does not exist on type 'typeof import("C:/dev/MateDates/src/app/node_modules/@types/expo/index")'.

const isAvailable = await Expo.SMS.isAvailableAsync();```

**Comment by ide** [comment]
@AlistairClark7 That error is coming from the `@types/expo` package, which is not maintained by the Expo team.

**Comment by ide** [comment]
Closing this since everything that was Flow-typed is now TypeScript.
