### ISSUE TITLE
Getting `TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation` while triggering push notification from server.

### ISSUE THREAD

**Issue by jtibrewal09** [expo/expo#23365]
### Minimal reproducible example

https://github.com/jtibrewal09/expo-notifications/tree/main

### Summary

I'm trying to run expo-node-server-sdk package in my webapp made using react.
When I call sendNotification function I get the below-mentioned error.

> TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
> at Expo. (ExpoClient.ts:238:1)
> at Generator.next ()
> at events.js:497:1
> at new Promise ()
> at webpack_modules../node_modules/expo-server-sdk/build/ExpoClient.js.__awaiter (events.js:497:1)
> at Expo.requestAsync (ExpoClient.ts:213:1)
> at Expo. (ExpoClient.ts:86:1)
> at Generator.next ()
> at events.js:497:1
> at new Promise ()

I tried to search everywhere but can't find any relevant solution. I'm very new to mobile app development and is stuck with this error from long time. Any help is appreciated. Thank you.

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.2
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.12.1 - /usr/local/bin/node
npm: 9.1.3 - /usr/local/bin/npm
Managers:
CocoaPods: 1.12.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
IDEs:
Android Studio: 2021.3 AI-213.7172.25.2113.9123335
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
npmPackages:
react: ^18.2.0 => 18.2.0
react-dom: ^18.2.0 => 18.2.0
npmGlobalPackages:
eas-cli: 3.13.3
Expo Workflow: managed

**Comment by brentvatne** [comment]
i believe that you may be the first person that has attempted to use this library in the context of a server rendered react component (if that is the context here? i only took a quick look) this is not an environment where the library is supported. you should use a full node environment for it, such as in an api route.

**Comment by jtibrewal09** [comment]
ohh, so all this time i was wrong :(
If you know any other good library compatible with Expo, can you please suggest?
