### ISSUE TITLE
Screen Orientation Effect not updating on device rotate only on iOS

### ISSUE THREAD

**Issue by ThejXM** [expo/expo#23373]
### Minimal reproducible example

https://snack.expo.dev/Pid6pmGue

### Summary

This was only tested on Expo Go on iOS (16.5.1, iPhone 11 Pro).

Faulty result: The Screen-Orientation value remains unchanged at 1, on device rotation.

Expected result: The Screen-Orientation value should show as 1 for portrait and 4 for landscape.

On device rotate, orientationChangeListener added using addOrientationChangeListener isn't updating the orientation value.

Works fine on Android, as demonstrated and testable using the provided snack.

Related: [Issue 23368](https://github.com/expo/expo/issues/23368)

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: Windows 10 10.0.22621
Binaries:
Node: 20.4.0 - \NODE\20.4.0\x64\node.EXE
npm: 9.8.0 - \NODE\20.4.0\x64\npm.CMD
Expo Workflow: managed

**Comment by supryan** [comment]
+1

**Comment by brentvatne** [comment]
which sdk version?

**Comment by supryan** [comment]
@brentvatne SDK 48

**Comment by brentvatne** [comment]
@supryan - try updating to 49, expo-screen-orientation has been largely rewritten for ios in this release
