### ISSUE TITLE
Monorepo's root .gitignore not used for "expo-env.d.ts"

### ISSUE THREAD

**Issue by 0xAsimetriq** [expo/expo#23371]
### Summary

When `expo-env.d.ts` file gets generated or re-generated a new `.gitignore` is always created. If expo app happens to be part of monorepo, contents of this file could be moved to monorepo's global `.gitignore`. However doing that and deleting local one still regenerates this file and doesn't use global .gitignore.

It would be good to have cli check all .gitignore files and choose upper-most one in these cases, or perhaps we can have an option to specify root .gitignore file to use?

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

49

### Environment
```zsh
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.1 - /opt/homebrew/bin/node
      npm: 9.6.7 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed
```

### Minimal reproducible example

N/A

**Comment by EvanBacon** [comment]
We use nested gitignores across expo tooling, e.g. prebuild generates ‘ios/.gitignore’. We recommend using this structure. In the past we investigated evaluating gitignores to condense how much code is generated but it never worked reliably and caused bad ergonomics.
