### ISSUE TITLE
Not a valid URL when call createSourceWithParams on Expo client

### ISSUE THREAD

**Issue by iagorm** [expo/expo#2337]
## Description

When I call a method createSourceWithParamsAsync, It returns me an error **Not a valid URL** and if I add in params type 'card', it says that '**card**' is not a valid value. Follow the code example calling the method:
        
```JS
const cardSource = await Stripe. createSourceWithParamsAsync({
    type: 'card',
    amount: 1099,
    currency: 'EUR'
});
```

## Expected Behavior

Open stripe source page and create a source with type **card** and be able to not add **returnURL** like in the [documentation](https://docs.expo.io/versions/latest/sdk/payments#creating-source-android-ios).

## Observed Behavior

The method throws a error:
```
ERROR: Failed params type: Invalid params `type` of value **`card`** supplied to `Stripe.createSourceWithParams`, expected one of ["bancontact","bitcoin","giropay","ideal","sepaDebit","sofort","threeDSecure","alipay"].
```
## Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/rebellion-2e21c6c7-7df4-442d-8115-bd2589e604cd.tar.gz

Devices tested:

* Nexus 5 API 26 (emulator device)
* Moto g6 (physical device)

**Comment by EvanBacon** [comment]
Looks like card arg is documented but not in the implementation. Also noticed a few new types that the current API doesn't have:

- createP24Params
- createAlipayReusableParams
- createSourceFromTokenParams
- createEPSParams
- createMultibancoParams
- createCardParams
- createVisaCheckoutParams
- createMasterpassParams

Will need to remove extra key `card` from `type` field [here](https://docs.expo.io/versions/latest/sdk/payments#creating-source-android-ios)

Error roots from original library https://github.com/tipsi/tipsi-stripe/issues/232

**Comment by iagorm** [comment]
@EvanBacon Sorry, yeah I mean **createSourceWithParamsAsync**, guys from [tipsi-stripe](https://github.com/tipsi/tipsi-stripe) have a open [PR](https://github.com/tipsi/tipsi-stripe/pull/261) which maybe solves that problem.

**Comment by EvanBacon** [comment]
we'll wait for them
