### ISSUE TITLE
Expo SDK 49 JS Debugger - Network Inspector

### ISSUE THREAD

**Issue by MaxRobertsDear** [expo/expo#23383]
### Summary

Network inspector registers the call to api but does not show response data
<img width="1306" alt="Screenshot 2023-07-08 at 00 13 16" src="https://github.com/expo/expo/assets/44136333/51101032-8081-4bc1-bfb0-19862cf5342a">

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"dependencies": {
    "@types/react": "~18.0.27",
    "expo": "^49.0.0",
    "expo-build-properties": "~0.8.3",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.4",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6",
    "typescript": "^5.1.3",
    "expo-updates": "~0.18.8"
  },

### Environment

System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.volta/tools/image/node/18.14.1/bin/node
      Yarn: 1.22.1 - ~/.volta/tools/image/yarn/4.0.0-rc.37/bin/yarn
      npm: 9.6.6 - ~/.volta/tools/image/npm/9.6.6/bin/npm
      Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/maxroberts-dear/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-29 | ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs ATD ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    Expo Workflow: managed

### Reproducible demo

new boilerplate expo project. 

Only additional code (beyond the installed package.json dependencies listed above) is this sample query added to the `app/index.tsx`: 

```
  React.useEffect(() => {
    const query = async () => {
      const response = await fetch("https://api.publicapis.org/entries");
      const res = await response.json();
      console.warn(res);
    };
    query();
  }, []);
```

**Comment by islamouzou** [comment]
For me it doesn't even show console logs

**Comment by byCedric** [comment]
> For me it doesn't even show console logs

@islamouzou That's a different issue. Logs are supposed to go through a different system unrelated to the inspector protocol. If you think this is an issue on our end, please open a new issue with all the content we ask.

**Comment by islamouzou** [comment]
> > For me it doesn't even show console logs
> 
> @islamouzou That's a different issue. Logs are supposed to go through a different system unrelated to the inspector protocol. If you think this is an issue on our end, please open a new issue with all the content we ask.

Thanks , i did .

**Comment by bryanltobing** [comment]
in my case using expo prebuild, network inspector doesn't work at all. but no issue with expo go

**Comment by adityawarrier** [comment]
> in my case using expo prebuild, network inspector doesn't work at all. but no issue with expo go

Noticing the same with expo prebuild. Inspector was working fine within expo go, the issue started the moment I did prebuild. Did you find any workaround for this?

**Comment by Rafael-Martins** [comment]
> > in my case using expo prebuild, network inspector doesn't work at all. but no issue with expo go
> 
> Noticing the same with expo prebuild. Inspector was working fine within expo go, the issue started the moment I did prebuild. Did you find any workaround for this?

Quite the same here, I can see the requests but the response content is kinda encoded
