### ISSUE TITLE
How to create file based routing(with-router) using typescript?

### ISSUE THREAD

**Issue by learncodingforweb** [expo/expo#23399]
### Summary

if using ``npx create-expo-app@latest -e with-router``
Getting any javascript based. how can i get typescript based file system routing?

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

48.0.18

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 33
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2
    npmPackages:
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: bare
```

### Minimal reproducible example

can you provide typescript based file system routing?

**Comment by alanjhughes** [comment]
Add a ts file and when you run `npx expo start` the cli will detect it and ask you to install the typescript dependencies and generate a tsconfig.

**Comment by learncodingforweb** [comment]
Yes, it works.
