### ISSUE TITLE
[SDK49] Debugger doesn't show console logs

### ISSUE THREAD

**Issue by islamouzou** [expo/expo#23394]
### Minimal reproducible example

https://github.com/islamouzou/expo-updates-demo

### Summary

Like any  SDK release , i like to test new features on new projects . pressing j opens debugger , but console logs are only shown in terminal and not on the Chrome debugger .

Steps to reproduce : 

Run "npx expo run:android" on a physical phone or an emulator , then press "j" , click on the button that is supposed to console log , nothing gets shown . i'm on a Mac .

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.7.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.05.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      Android SDK:
        API Levels: 19, 27, 28, 31, 32, 33, 34
        Build Tools: 27.0.0, 27.0.3, 28.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.9
    Expo Workflow: bare

**Comment by byCedric** [comment]
Thanks for reporting the issue, unfortunately, this is an upstream issue in React Native. See https://github.com/facebook/react-native/issues/38204

The issue has been identified, and a fix should be out soon. I'll keep this issue open until we've updated to the fixed React Native version.

**Comment by jomarmontuya** [comment]
I have similar issue any workarounds on this?

**Comment by islamouzou** [comment]
Fixed in the new react native version

**Comment by 20chad16** [comment]
i'm on react native 0.72.3. Any fix for this? I'm using jsc not hermes

**Comment by JovanSr** [comment]
Have this issue also, bare workflow. 
react-native: "0.72.5",
expo: "~49.0.6",

**Comment by marcel-mintouge** [comment]
Any update on this?

**Comment by dhcmega** [comment]
Hi, should be possible to debug redux, network, state, console log, etc with SDK49? All this was possible with SDK48. Thanks.

**Comment by Pranavpatel428** [comment]
Hi, I am facing the same issue. SDK 49 and react-native: 0.72.7. Can anyone help me with any solution or workaround that will be great!
Thank you so much!

**Comment by marcel-mintouge** [comment]
@dhcmega @Pranavpatel428 If you don't mind upgrading to expo 50, here's how I solved my issue: https://github.com/expo/expo/issues/26254

**Comment by NiccoloCase** [comment]
I'm having the same issue on SDK 48. I can not update to a new sdk due to a bug on react-native-reanimated

**Comment by bearkillerPT** [comment]
I'm not sure it's related but I was successfully using Expo SDK 49 and, without changing any dependencies, now I can't get logs. Now here's the funny part:
- ```yarn start``` doesn't give me logs
  - The scripts executes ```expo start --dev-client```
- when I run ```expo start --dev-client``` directly I do get logs!

> @dhcmega @Pranavpatel428 If you don't mind upgrading to expo 50, here's how I solved my issue: #26254
Do you think it's related? I've tried upgrading to Expo 50.0.6 (>50.0.4) and compile a dev client. When the bundling was done the app crashed and since there are no logs I don't know....

**Comment by dhcmega** [comment]
Hi, I don't have any "resolutions" forcing certain versions.
SDK50 seems to work ok so far.
I'm still missing react native debugger which was full of features all in one.
Thanks

**Comment by olehbdev** [comment]
if you have `"@types/react-native"` in yours `devDependencies` - delete it, this package has been deprecated, react-native provides its own type definitions, so you do not need this installed. it helped me

**Comment by xiimiik** [comment]
if you have "@types/react-native" in yours devDependencies - delete it, this package has been deprecated, react-native provides its own type definitions, so you do not need this installed. it helped me
