### ISSUE TITLE
Sending `expoDidUpdateDimensions` with no listeners registered.

### ISSUE THREAD

**Issue by ghost** [expo/expo#23395]
### Minimal reproducible example

https://github.com/ThejXM/Expo-Hello

### Summary

MRE is an empty "Hello, World!" project.

On device rotate, warnings triggered. Tested on Expo Go, on iOS. SDK 49. Latest compatible release (stable) versions of packages.

Expected: No warning should be triggered, but operation should complete successfully.

![SSI_002](https://github.com/expo/expo/assets/138805646/ec9be700-3395-47e0-be05-95b8a65cda89)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.4.0 - C:\0\A\NODE\20.4.0\x64\node.EXE
      npm: 9.8.0 - C:\0\A\NODE\20.4.0\x64\npm.CMD
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: ^18.2.0 => 18.2.0
      react-native: ^0.72.1 => 0.72.1
    Expo Workflow: managed

**Comment by alioguzhan** [comment]
I got the same warning when upgraded my app from `48` to `49` today.  The warning appears when I changed the orientation. Here is the environment info: 

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 NixOS 23.05 (Stoat) 23.05 (Stoat)
      Shell: 5.2.15 - /nix/store/5d0bgm1j7nwan9z0gkv7lfsm5chz0jwq-bash-interactive-5.2-p15/bin/bash
    Binaries:
      Node: 18.16.0 - /nix/store/hdwy8j1jvj2d68p449vvpf5j4mrgzldi-nodejs-18.16.0/bin/node
      Yarn: 1.22.19 - /nix/store/j3pdx0wz2y8i3yzs6fnf817lyr11wv09-yarn-1.22.19/bin/yarn
      npm: 9.5.1 - /nix/store/hdwy8j1jvj2d68p449vvpf5j4mrgzldi-nodejs-18.16.0/bin/npm
      Watchman: 2023.01.30.00 - /run/current-system/sw/bin/watchman
    npmPackages:
      expo: ^49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed
```

**Comment by alioguzhan** [comment]
Here is where I stand after some digging:

The `expo-screen-orientation` package somehow expects us to use the `orientationChange` listener. It shouldn't, but it does. I don't know why.  Here is the line sending this warning:

https://github.com/expo/expo/blob/63c81890e71ea4c672425bb8f54061127a5633e8/ios/versioned-react-native/ABI49_0_0/ReactNative/React/Modules/ABI49_0_0RCTEventEmitter.m#L70

There is also this in another file which supposes to silence this warning (which doesn't, obviously)

https://github.com/expo/expo/blob/63c81890e71ea4c672425bb8f54061127a5633e8/ios/versioned/sdk49/EXNotifications/EXNotifications/Notifications/Emitter/ABI49_0_0EXNotificationsEmitter.m#L93


Anyway, I use this package only to change the phone's orientation based on navigating to/from a screen.

For a **workaround**, until a fix comes up,  I added the below line to where I used the plugin. 

```js
Orientation.addOrientationChangeListener(() => false);
```
Now the warning is gone.

**Comment by alphacodedev99** [comment]
Hello to all, 

i got also same warn, can we fixed this ? 
but in my project i used useWindowDimension() hook to follow my dimension when i rotate device and update my styling..

 thanks in advance

<img width="388" alt="Screenshot 2023-07-24 at 23 20 59" src="https://github.com/expo/expo/assets/30984729/a5a7968a-20a3-4e23-8839-6548cf66859c">

**Comment by Themrpie** [comment]
Same thing happening in Speech, and it's not working:
<img width="664" alt="Captura de pantalla 2023-08-29 a la(s) 12 27 17" src="https://github.com/expo/expo/assets/73369706/1795e11b-498f-4dc9-a662-45c8fb144d7a">
