### ISSUE TITLE
snack expo version and snack react-native version

### ISSUE THREAD

**Issue by davidgithub1980** [expo/expo#2339]
Hi. How can I use a specific expo SDK version (for example the latest v30) as well as specific react-native version when creating a snack? I am not allowed to add it to the snack's package json as it says: _The package "expo" can be imported without adding to "dependencies"_

**Comment by raajnadar** [comment]
Snack uses expo forked react-native  package so you can't

https://github.com/expo/react-native

The reason is obvious they cherry pick commits from the original react-native repo and convert them in such a way that it works properly with the expo client.
