### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener`, `removeListeners` method.

### ISSUE THREAD

**Issue by ghost** [expo/expo#23392]
### Minimal reproducible example

https://github.com/ThejXM/Expo-Debug.git

### Summary

This occurs on Android Expo Go, not on iOS, after upgrading to SDK 49.

I'm not using `new NativeEventEmitter()` directly in my code, but check useOrientation.js for possible indirect usage.

My own code looks fine, and it used to work fine before upgrade, and it still doesn't trigger this particular issue on iOS Expo Go.

![SSA_003](https://github.com/expo/expo/assets/138805646/fcdc9dcb-13a5-4d08-8558-62af13cff71e)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.4.0 - C:\0\A\NODE\20.4.0\x64\node.EXE
      npm: 9.8.0 - C:\0\A\NODE\20.4.0\x64\npm.CMD
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

**Comment by AlbertCardi** [comment]
I have the same issue but mine is coming from 'expo-localization'

**Comment by Kaosc** [comment]
Warning accours on expo-screen-orientation version 5.2.0 and above with SDK 49. You can roll back to 5.1.1 as a workaround if don't wanna see warnings until it got fixed.

**Comment by rbrki07** [comment]
I have the same issue. Mine is coming from 'expo-brightness'.

**Comment by m2hd1** [comment]
same issue with `expo-brightness` android only 

![image](https://github.com/expo/expo/assets/16073350/b08af6cd-5976-485c-9713-da66b14c4cff)

**Comment by borgogelli** [comment]
For me, from expo-screen-orientation

**Comment by Onytgvx** [comment]
> For me, from expo-screen-orientation

Same here

**Comment by erichou668** [comment]
any updates about the issue

**Comment by asafratzon** [comment]
Also occurring on expo bare on android.

**Comment by mnassabain** [comment]
Same issue, seems to be coming from expo-screen-orientation as well

**Comment by jonjamz** [comment]
Same here, with expo-screen-capture on android. I don't get the warning on iOS.

**Comment by MTaylor124** [comment]
Mine is also coming from expo-screen-orientation even after trying a fresh expo upgrade and updating the package

**Comment by fa2id** [comment]
Same from orientation

**Comment by karelric** [comment]
Same here coming from `expo-localization`.

**Comment by mattatti** [comment]
same for me... expo-screen-orientation

**Comment by sk-phan** [comment]
@mattatti  I tried to install this version: ` "expo-screen-orientation": "5.1.1"` and I have not gotten any error. It works perfectly on Android and IOS

**Comment by mattatti** [comment]
@sk-phan You're correct, but it's just a workaround as now expo will throw you this warning:
Some dependencies are incompatible with the installed expo version:
  expo-screen-orientation@5.1.1 - expected version: ~6.0.5
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix

**Comment by sk-phan** [comment]
You're right 😅. Have you found any solution for it? @mattatti

**Comment by martindebrunne** [comment]
I'm here to keep track of this issue.

**Comment by Aoi-Takahashi** [comment]
Me too. Do you have any good solutions?

**Comment by coolersham** [comment]
@Kudo or @EvanBacon this could easily be fixed by adding the required `addListener` and `removeListeners` functions into the `ScreenOrientationModule.kt`. I am not aware if you are already handling that in a later version of `expo-screen-orientation`, but if you or someone from the community wants to silence these annoying warnings, then just add the following lines to the stated file (the following also matches with `react-native` documentation; tested with `6.2.0`). 

```
AsyncFunction("supportsOrientationLockAsync") { orientationLock: Int ->
  return@AsyncFunction OrientationLock.supportsOrientationLock(orientationLock)
}

// Required to silence NativeEventEmitter warning
Function("addListener") { eventName: String ->
  return@Function
}

// Required to silence NativeEventEmitter warning
Function("removeListeners") { count: Int ->
  return@Function
}
    
OnCreate {
  uiManager.registerLifecycleEventListener(this@ScreenOrientationModule)
}
```

**Comment by sk-phan** [comment]
I am using expo-screen-orientation 6.0.5, and I got the same error. The error happened only for Android. So what I did is creating a patch-package to modify the ScreenOrientation.js file in node modules and it seems to work quite well in production.

I create this patch file

`diff --git a/node_modules/expo-screen-orientation/build/ScreenOrientation.js b/node_modules/expo-screen-orientation/build/ScreenOrientation.js
index f131114..34124cc 100644
--- a/node_modules/expo-screen-orientation/build/ScreenOrientation.js
+++ b/node_modules/expo-screen-orientation/build/ScreenOrientation.js
@@ -1,8 +1,12 @@
 import { EventEmitter, Platform, UnavailabilityError } from 'expo-modules-core';
 import ExpoScreenOrientation from './ExpoScreenOrientation';
+import { NativeEventEmitter, NativeModules } from 'react-native';
+
 import { Orientation, OrientationLock, WebOrientationLock, WebOrientation, SizeClassIOS, } from './ScreenOrientation.types';
 export { Orientation, OrientationLock, WebOrientationLock, WebOrientation, SizeClassIOS, };
-const _orientationChangeEmitter =sieEmitter(ExpoScreenOrientation);
+const _orientationChangeEmitter = Platform.OS === 'ios' || Platform.OS === 'web'
+? new EventEmitter(ExpoScreenOrientation)
+: new NativeEventEmitter();;
 let _orientationChangeSubscribers = [];
 let _lastOrientationLock = OrientationLock.UNKNOWN;
 // @needsAudit
`

**Comment by brentvatne** [comment]
@alanjhughes - it looks like this is happening on android with expo-brightness (verified on my end) and possibly also with expo-screen-orientation

**Comment by MTaylor124** [comment]
I cleared my cache and updated screen-orientation and the same error persists. Not sure why this was closed, error is still there. 

npx expo install --fix
updated both react native and screen orientation

**Comment by rvasseur31** [comment]
> I cleared my cache and updated screen-orientation and the same error persists. Not sure why this was closed, error is still there. 
> 
> 
> 
> npx expo install --fix
> 
> updated both react native and screen orientation

Have you tried version 6.0.6 ?

**Comment by MTaylor124** [comment]
It is version 6.0.6

**Comment by alanjhughes** [comment]
@MTaylor124 - are you using expo go?

**Comment by MTaylor124** [comment]
Yes I am using expo go on my android mobile device: Pixel 4XL. I updated the packages and cleared the cache and I am still getting the exact same error (same as title of thread) pointing to screen-orientation:

 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 
 This error still shows up on every single app load on any android device. My packages:
 
   "dependencies": {
    "@expo/config-plugins": "~7.2.2",
    "@expo/ngrok": "^2.5.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.3.17",
    "expo": "~49.0.8",
    "expo-av": "~13.4.1",
    "expo-constants": "~14.4.2",
    "expo-device": "~5.4.0",
    "expo-font": "~11.4.0",
    "expo-image": "~1.3.4",
    "expo-linear-gradient": "~12.3.0",
    "expo-navigation-bar": "~2.3.0",
    "expo-notifications": "~0.20.1",
    "expo-screen-orientation": "~6.0.6",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.16",
    "expo-web-browser": "~12.3.2",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-webview": "13.2.2"
  },
  
  
  I get zero other warnings or errors when I load my app on expo go on any other device.

**Comment by alanjhughes** [comment]
@MTaylor124 - Yes because expo go has not had an update so it won't have received this fix. To get the latest fixes you need to be using a development client

**Comment by MTaylor124** [comment]
@alanjhughes Perfect! Thank you for letting me know.

**Comment by ajin9527** [comment]
me too,"expo-screen-orientation": "~6.0.6",

**Comment by abanobboles** [comment]
i also get exactly the same error twice
with: `"expo": "~50.0.0-preview.7",` dev-client

One is looking like from Expo Router (`"expo-router": "~3.4.1"`,)
and the other from expo-av Sound (using setOnPlaybackStatusUpdate) ` "expo-av": "~13.10.1",`

i also tried `bun expo install --fix`

**Comment by oza-27** [comment]
What is the solution? I am facing same issue

**Comment by Lum-ona** [comment]
I'm also getting the same warning and it coming from 'expo-av', anyone with a solution around it?

**Comment by EOMZON** [comment]
when I install  "expo-speech": "~11.3.0", I met the same question. Who know how to fix it ?

**Comment by buraks** [comment]
```
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
    at ContextNavigator (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:148711:24)
    at ExpoRoot (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:148667:28)
    at App
    at ErrorToastContainer (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:222591:24)
    at ErrorOverlay
    at withDevTools(ErrorOverlay) (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:222341:27)
    at RCTView
    at View (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:40632:43)
    at RCTView
    at View (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:40632:43)
    at AppContainer (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:40443:36)
    at main(RootComponent) (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp:124824:28)
    ```
    
    I am getting this with `expo-router@3.4.2`
    
    @alanjhughes  I think some other people are still experiencing the problem. Could you kindly re-open the issue please?

**Comment by alanjhughes** [comment]
Just to note, this is a dev mode only warning and won't be seen in the deployed version of your app or cause any problems. These will be fixed and is annoying, just adding this incase anyone is worried about releasing there app while this is present.

**Comment by mankybansal** [comment]
Having the same issue: 

<img width="642" alt="Screenshot 2024-01-18 at 2 20 41 PM" src="https://github.com/expo/expo/assets/12834184/0ddceea4-af1c-4649-b107-8e162201595c">

**Comment by datoybi** [comment]
I have same issue from `expo-notifications`

**Comment by arvl130** [comment]
@alanjhughes I'm hitting the same issue, but with `expo-task-manager`. Should I create a separate issue for that?

**Comment by victormamede** [comment]
I am facing this issue with `expo-av` `~13.10.3`

**Comment by munyanezaarmel** [comment]
same issue with expo-sqlite

**Comment by alanjhughes** [comment]
Please stop commenting on closed issues. We do not have the bandwidth to track them. This was related to `expo-screen-orientation` and was resolved. If you have a problem in another library please open a new issue and fill in the template.
