### ISSUE TITLE
Huge app data

### ISSUE THREAD

**Issue by mkloar** [expo/expo#2340]
Hey.

My apk size is 27MB when I build it with exp build:android.My application store only 3 different data into AsyncStorage. 

Problem:
When apk is installed on phone and when I store some data, my application on phone has 20MB+, on some phones is ~40MB of app data. How is this possible? I don't want that to happen. 

### Environment

Environment:
  OS: Windows 10
  Node: 10.4.1
  Yarn: 1.9.4
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  expo: ^27.0.2 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

Standalone

**Comment by raajnadar** [comment]
Read this post

https://forums.expo.io/t/android-application-size-is-extremely-too-big/1077/4
