### ISSUE TITLE
Expo-AV Recording doesn't save durationMillis on Web

### ISSUE THREAD

**Issue by jaxoncreed** [expo/expo#23423]
### Minimal reproducible example

https://snack.expo.dev/@otherjackson/av-doesnt-have-duration

### Summary

In a web browser, wyhen using the Recording functionality of expo-av, the duration of the recording (from `status.durationMillis`) is recorded while the recording is taken, but once `getURI()` is called, the recording's duration value becomes Infinity upon playback.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2022.11.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-33 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.1 
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by brentvatne** [comment]
@amandeepmittal - let's document this functionality and label expo-av recording for web as experimental

**Comment by jaxoncreed** [comment]
Apparently this is a larger problem than just expo. Browsers that record WebMs (like chrome and firefox) do not include the duration in their recording when using the `MediaRecorder` API. @yusitnikov made a library to fix this here (https://github.com/yusitnikov/fix-webm-duration).
