### ISSUE TITLE
[SDK 49] expo-document-picker returns assets.length === 0 on Web

### ISSUE THREAD

**Issue by fuelkoy** [expo/expo#23424]
### Minimal reproducible example

https://github.com/fuelkoy/expo49expoDocumentPicker

### Summary

On web expo-document-picker returned correct results in SDK 48 in uri, name and in other keys. Library should still return correct results in SDK 49 in assets array as other keys than canceled and assets are deprecated in SDK 49. The assets array length is 0 so no results are returned

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi - this will be resolved by [23135](https://github.com/expo/expo/pull/23135) when it is published.

**Comment by brentvatne** [comment]
fixed by #23135

**Comment by fuelkoy** [comment]
@alanjhughes @brentvatne Amazing work guys! Thank you!
