### ISSUE TITLE
CommandError: The bundled native module list from the Expo API is empty 

### ISSUE THREAD

**Issue by meabed** [expo/expo#23448]
### Summary

When Prebuild cli v49.0.2 I get this error `CommandError: The bundled native module list from the Expo API is empty`

Digging and looking at the cause found that this API return empty 

https://api.expo.dev/v2/sdks/49.0.2/native-modules

vs 49.0.0 return list of modules 

https://api.expo.dev/v2/sdks/49.0.0/native-modules

---

### SDK Version

49.0.2

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.2 => 49.0.2
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
    Expo Workflow: bare

### Minimal reproducible example

Install expo 49.0.2 and run command `expo prebuild --clean`

**Comment by brentvatne** [comment]
are you using the local expo-cli? `npx expo prebuild --clean`. if so, please share a reproducible example

the global cli (installed globally with `npm i -g expo-cli`) is deprecated and may not work as expected.

one other thing to consider - do you have `sdkVersion` set in your app.json? maybe you set it to `49.0.2`? you should not set `sdkVersion` in app.json, it's set automatically from the expo package

**Comment by meabed** [comment]
Thanks @brentvatne 
I'm using the cli bundled in the npm package json no global expo cli or npx 

I have the expo sdk version set to 49.0.2 

The error is not related to the environment, it's related to fetch on this file https://github.com/expo/expo/blob/main/packages/expo/cli/src/api/getNativeModuleVersions.ts#L48C1 and lead to this error.

This link I believe should respond with the packages bundled for each expo version, maybe it was not published for 49.0.2?

**Comment by meabed** [comment]
Thank you @brentvatne I had sdkVersion manually set, I have removed it and it's working now 👍
