### ISSUE TITLE
expo sqlite / expo-file-system not bundling

### ISSUE THREAD

**Issue by mgooch1** [expo/expo#23455]
### Minimal reproducible example

https://github.com/mgooch1/expo-sqllite-repro/tree/main

### Summary

I have followed the instructions to copy a local database from (https://docs.expo.dev/versions/latest/sdk/sqlite/) this works on android and Ios in development but once I build it it does not load on iOS. works fine on android builds.
the error on iOS is
Error: Unable to download
file: Error Domain=NSURLErrorDomain
Code=-1002 "unsupported URL"
UserInfo={NSErrorFailingURLStringKey =file:///Users/matthewgooch/Library/
Developer/CoreSimulator/Devices/

Im pretty new to expo but i think the database is not being bundled. I have tried a fresh install and upgrade to latest SDK but I can't get it to work

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - /opt/homebrew/bin/node
      npm: 9.7.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.0

**Comment by alanjhughes** [comment]
Hi @mgooch1 - You are not loading the database correctly. I got your repro working by changing your load function. You can move this outside your component.

```javascript
async function loadDatabase() {
  if (
    !(await FileSystem.getInfoAsync(FileSystem.documentDirectory + "SQLite"))
      .exists
  ) {
    await FileSystem.makeDirectoryAsync(
      FileSystem.documentDirectory + "SQLite"
    );
  }
  await FileSystem.downloadAsync(
    Asset.fromModule(require("./main.db")).uri, // set to path of DB in package
    FileSystem.documentDirectory + "SQLite/main.db"
  );

  return SQLite.openDatabase("main.db");
}
```

Load it in your component like this 
```javascript
 const [db, setDb] = useState(null);

  useEffect(() => {
    async function loadDB() {
      const result = await loadDatabase();
      setDb(result);
    }
    loadDB();
  }, []);

  useEffect(() => {
    if (db) {
      db.transactionAsync(async transaction => {
        const result = await transaction.executeSqlAsync(
          "SELECT * FROM sample"
        );
        console.log(result);
      });
    }
  }, [db]);
```

**Comment by alanjhughes** [comment]
Also you should change your bundleIdentifier. A string  of numbers are invalid and will cause metro to crash. You can open this issue again if this doesn't work.

**Comment by MobileMon** [comment]
I'm having the same issue, did you ever figure this out? @mgooch1
