### ISSUE TITLE
Error: GraphQL request failed.

### ISSUE THREAD

**Issue by MariuzM** [expo/expo#23467]
### Summary

Getting this error when trying to push to expo

```
✖ Failed to publish updates
[Network] upstream connect error or disconnect/reset before headers. reset reason: connection termination
    Error: GraphQL request failed.
 ELIFECYCLE  Command failed with exit code 1.
```

### SDK Version

~48.0.18

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Minimal reproducible example

Run the command `npx eas-cli update --platform ios`

**Comment by MariuzM** [comment]
I get this error once i start `⠼ Publishing...` step

**Comment by leymytel** [comment]
> I get this error once i start `⠼ Publishing...` step

I had the same issue and it works fine now.
There were some issues with the EAS service earlier today and yesterday.
https://status.expo.dev/

**Comment by Tefris** [comment]
Now I have encountered this problem, how can I solve it?

**Comment by noahboekelman** [comment]
Did you find a solution? Sitting with the same problem at the moment. I've tried everything..

**Comment by textual** [comment]
I recently tried to upgrade from 48, to 49, to 50, and my builds are failing when trying to buildDeps. It hangs for a while then presents the error 

[Network] request to https://api.expo.dev/graphql failed, reason: connect ETIMEDOUT 2606:4700::6812:468:443
    Error: GraphQL request failed.

I was hoping it was a residual package from expo trying to phone home.

**Comment by CarlMenke** [comment]
Same issue here, went from 48 to 49 to 50 now when I try to build or connect it times out, but only on  my home wifi not my work wifi, any ideas?

**Comment by textual** [comment]
I ended up upgrading node in my nvm, reinstalled expo and expo-cli using latest, and now issue is better. there are some residual errors, like it keeps telling me to upgrade expo-cli and eas-cli yet i've run the install command multiple times. i get a warning about punycode(?) that im not sure about. and i cant get expo/eas and apple to communicate due to a cookie in my host domain error.

**Comment by IceeeAge** [comment]
This is working 

import { gql, request } from 'graphql-request/build/entrypoints/main';

**Comment by mnaderian** [comment]
In such times it's better to use ``npx eas-cli@latest`` instead of ``eas``.

**Comment by jdu211171** [comment]
> In such times it's better to use `npx eas-cli@latest` instead of `eas`.

It actually helped

**Comment by esmael-Abdlkadr** [comment]
I encountered the same issue (getaddrinfo EAI_AGAIN api.expo.dev) when running eas init. After multiple retries, it worked for me. Here’s what helped:
-Retry the command multiple times – the issue seemed to be temporary.
-Check your internet connection – make sure it’s stable.
-if it is persistent try eas-cli@latest instead of eas init

**Comment by jdu211171** [comment]
> I encountered the same issue After multiple retries, it worked for me. Here’s what helped: -Retry the command multiple times – the issue seemed to be temporary. -Check your internet connection – make sure it’s stable. -if it is persistent try eas-cli@latest instead of eas init

best advice ever. I'm trying `npx eas-cli@latest` instead of `eas` multiple times, like this:
`npx eas-cli@latest build --platform android --local`

and it's sometimes it works. Sometime's I would have to try multiple times and then it works.

**Comment by dragonmaster784** [comment]
Adding this as it hasn't been mentioned at all and was the case for me:

* If you are using a VPN, turn it off and try again.
