### ISSUE TITLE
expo prepare-detached-build Doesn't Generate Files

### ISSUE THREAD

**Issue by redreceipt** [expo/expo#2346]
### Environment

Environment:
  OS: macOS 10.14
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Target:
  iOS
  Android
  ExpoKit
  AppCenter

### Steps to Reproduce

I need to be able to include detached generated files in my `.gitignore` because the URL changes for every developer. So I remove the files, but obviously, the project won't build after that.

(Write your steps here:)

1. Delete `DetachBuildConstants.java`
2. `yarn start`
3. Build in Android Fails (Missing Package)

### Expected Behavior

I expected the `prepare-detached-build` step to generate that file for me.

### Actual Behavior

`DetachBuildConstants.java` was not generated

![screen shot 2018-10-02 at 5 08 44 pm](https://user-images.githubusercontent.com/2659478/46377157-d73e9700-c665-11e8-9e49-5d526d9cfb6a.png)

**Comment by ide** [comment]
SDK 25 was from almost half a year ago and the latest dev tools might not work with it. I'd recommend seeing if you can repro with SDK 30.

**Comment by tsapeta** [comment]
As James said above, it's been a long time since then so I believe it's no longer an issue. I'm closing this issue as there was no response for previous message. Feel free to create a new issue if this still happens for you though.
