### ISSUE TITLE
IOS build fails after upgrade to Expo 49 with fastline expo-updates error.

### ISSUE THREAD

**Issue by veliseev93** [expo/expo#23482]
### Summary

After upgrade to Expo 49 fastline fails with errors after command - Executing expo-updates Pods/EXUpdates » [CP-User] Generate app.manifest for expo-updates;

<img width="1094" alt="Снимок экрана 2023-07-12 в 09 28 44" src="https://github.com/expo/expo/assets/115105148/afe9c5d1-b4b4-437c-b155-e3bf4664cbd4">

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

Fastline fails with errors after command - Executing expo-updates Pods/EXUpdates » [CP-User] Generate app.manifest for expo-updates;

package.json {
"dependencies": {
    "@braze/expo-plugin": "^1.1.1",
    "@braze/react-native-sdk": "^4.1.0",
    "@config-plugins/react-native-blob-util": "^5.0.0",
    "@config-plugins/react-native-pdf": "^5.0.0",
    "@eva-design/eva": "2.1.1",
    "@expo/metro-config": "^0.10.6",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@hookform/resolvers": "^3.0.1",
    "@intercom/intercom-react-native": "^4.0.1",
    "@pinwheel/react-native-pinwheel": "^2.3.16",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/hooks": "^3.0.0",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-masked-view/masked-view": "0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "@reduxjs/toolkit": "^1.9.5",
    "@sentry/react-native": "5.5.0",
    "@shopify/flash-list": "1.4.3",
    "@ui-kitten/components": "^5.3.1",
    "ahooks": "^3.7.6",
    "axios": "^1.3.5",
    "axios-observable": "^2.0.0",
    "class-transformer": "^0.5.1",
    "config-plugin-react-native-intercom": "^1.10.1",
    "core-js": "^3.30.0",
    "currency-symbol-map": "^5.1.0",
    "expo": "^49.0.2",
    "expo-application": "~5.3.0",
    "expo-asset": "~8.10.1",
    "expo-build-properties": "~0.6.0",
    "expo-camera": "~13.4.2",
    "expo-clipboard": "~4.3.0",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.2.1",
    "expo-device": "~5.4.0",
    "expo-file-system": "~15.4.2",
    "expo-image": "~1.0.1",
    "expo-image-picker": "~14.3.1",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-local-authentication": "~13.4.1",
    "expo-localization": "~14.3.0",
    "expo-location": "~16.0.0",
    "expo-navigation-bar": "~2.3.0",
    "expo-notifications": "~0.20.1",
    "expo-permissions": "~14.2.1",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-updates": "~0.18.9",
    "http-status-codes": "^2.2.0",
    "i18n-js": "^4.3.0",
    "immer": "^9.0.21",
    "initials": "^3.1.2",
    "jwt-check-expiry": "^1.0.10",
    "lodash": "^4.17.21",
    "luxon": "^3.3.0",
    "mixpanel-react-native": "^2.2.1",
    "moti": "^0.24.2",
    "numeral": "^2.0.6",
    "patch-package": "^6.5.1",
    "qs": "^6.11.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.43.9",
    "react-native": "0.72.1",
    "react-native-animated-pagination-dots": "^0.1.73",
    "react-native-auth0": "^2.17.4",
    "react-native-blob-util": "^0.18.3",
    "react-native-compressor": "^1.6.1",
    "react-native-email-link": "^1.14.5",
    "react-native-extended-stylesheet": "^0.12.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-maps": "1.7.1",
    "react-native-mask-input": "^1.2.3",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^15.0.0",
    "react-native-pdf": "^6.6.2",
    "react-native-persona": "^2.4.4",
    "react-native-plaid-link-sdk": "^10.1.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "^3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-skeleton-placeholder": "^5.2.4",
    "react-native-svg": "13.9.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-toast-message": "^2.1.6",
    "react-native-use-idle": "^1.14.0",
    "react-native-webview": "11.26.0",
    "react-redux": "^8.0.5",
    "redux-observable": "^2.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.0",
    "sentry-expo": "~7.0.0",
    "text-mask-addons": "^3.8.0",
    "victory-native": "^36.6.8",
    "yup": "^0.32.11",
    "yup-phone": "^1.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.21.4",
    "@config-plugins/detox": "^5.0.1",
    "@faker-js/faker": "^8.0.2",
    "@types/detox": "^18.1.0",
    "@types/jest": "^29.5.1",
    "@types/lodash": "^4.14.192",
    "@types/luxon": "^3.3.0",
    "@types/numeral": "^2.0.2",
    "@types/qs": "^6.9.7",
    "@types/react": "~18.0.24",
    "@types/react-native": "~0.70.6",
    "@types/react-native-auth0": "^2.17.3",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.58.0",
    "@typescript-eslint/parser": "^5.58.0",
    "cross-env": "^7.0.3",
    "cross-fetch": "^3.1.5",
    "detox": "^20.9.1",
    "dpdm": "^3.13.0",
    "eslint": "^8.38.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-import-resolver-typescript": "^3.5.5",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-native": "^4.0.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^8.0.3",
    "jest": "^29.5.0",
    "jest-expo": "^48.0.2",
    "lint-staged": "^13.0.3",
    "mailslurp-client": "^15.17.1",
    "prettier": "^2.8.7",
    "react-native-flipper": "^0.189.0",
    "redux-flipper": "^2.0.2",
    "regex-to-strings": "^2.1.0",
    "type-fest": "^3.8.0",
    "typescript": "^4.9.3"
  }

eas.json :
  {
      "channel": "development",
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
       }
     }

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.6 => 0.7.1 
      expo: ^49.0.2 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.10.0
    Expo Workflow: managed

### Reproducible demo

eas build

**Comment by LucasLFurini** [comment]
Hey, how did you fix this issue?

**Comment by matziol** [comment]
@veliseev93 could you share the solution, please?
