### ISSUE TITLE
Expo.Constants not working on published app to Expo website

### ISSUE THREAD

**Issue by incorelabs** [expo/expo#2348]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

Environment:
  OS: Windows 10
  Node: 8.12.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/incorelabs-226d9de3-0949-468b-ba53-f99671bcbd3c.tar.gz

Android, iOS
### Steps to Reproduce

This issue occurs when I,

1. import Expo from "expo"
2. Then inside a function, I call Expo.Constants and try to get the { manifest } property
3. The only time this issue occurs is when I publish my project to the Expo Website.

### Expected Behavior

What I thought would happen is that if the Expo variable was available I would have used it to try and find if the app was running in DEV mode or not. If it was, I would use a local url for the API endpoint else I would a production one.

### Actual Behavior

Instead, I get a blank screen as soon the function runs (The function runs after login is a success) to get data from the API. The API never gets a hit. It does not even give an error nor crash. Just a blank white screen after the login.

The app works perfectly in development mode as well as in the production mode using the expo cli. But once published it just fails to work with Expo.Constants. When I remove Expo.Constants it works perfectly fine on the published version also.

Is the "Expo.Constants" not available in the published version? Or is import Expo from "expo" not available?

### Reproducible Demo

https://expo.io/@incorelabs/my-app

Demo Login Credentials:

test@test.com
123456

Code:

```
import Expo from 'expo';
import { Alert } from 'react-native';

export default function getDataFromLocalDb(resource) {
  let api = 'www.mocky.io/v2';

  Alert.alert(`Just before the dreaded issue`);

  if (Expo && Expo.Constants) {
    const { manifest } = Expo.Constants;

    if (manifest && manifest.packagerOpts.dev) {
      api = manifest.debuggerHost
        .split(':')
        .shift()
        .concat(':3000');
    }
  }

  Alert.alert(`URL:: http://${api}/${resource}`);

  return fetch(`http://${api}/${resource}`)
    .then(response => response.json())
    .catch(error => {
      Alert.alert(`ERROR caught in fetch:: ${JSON.stringify(error)}`);
      throw Error('Error has occured');
    });
}
```

**Comment by EvanBacon** [comment]
Use `global.__DEV__` instead https://stackoverflow.com/a/33264515/4047926
Also you can run `expo start --no-dev --minify` to debug your error locally.
