### ISSUE TITLE
[SDK 49]

### ISSUE THREAD

**Issue by RicardoBrito1938** [expo/expo#23483]
### Minimal reproducible example

build on eas for android is breaking even locally 

### Summary

Hello Team, after upgrade from SDK48 to SDK 49, i got the following error on android build

> Task :app:createBundleReleaseJsAndAssets FAILED
Unknown or unexpected option: --platform

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 3.2.2 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.10

**Comment by tplorts** [comment]
@RicardoBrito1938 did you end up solving this problem? I'm running into the same error message after an expo upgrade from 49 to 51 and finding it hard to debug.
```
> Task :app:createBundleReleaseJsAndAssets FAILED
unknown or unexpected option: --platform
```
- only happening on a release android build

I ran a build with the debug option to see where that `--platform` option is being passed in and I think it's this line:
```
[INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'node''. Working directory: .../mobile Command: node .../node_modules/@expo/cli/build/bin/cli bundle --platform android --dev false --reset-cache --entry-file .../mobile/index.js --bundle-output .../mobile/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle --assets-dest .../mobile/android/app/build/generated/res/createBundleReleaseJsAndAssets --sourcemap-output .../mobile/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map --minify false --verbose
```

so far I haven't found anything that documents a change in accepted options to the expo cli.

**Comment by RicardoBrito1938** [comment]
Yes, what did to resolve

1) upgrade expo cli
2) upgrade expo
3) pre build
4) doctor

The game changer was updating the cli before doing anything else



> @RicardoBrito1938 did you end up solving this problem? I'm running into the same error message after an expo upgrade from 49 to 51 and finding it hard to debug.
> ```
> > Task :app:createBundleReleaseJsAndAssets FAILED
> unknown or unexpected option: --platform
> ```
> - only happening on a release android build
> 
> I ran a build with the debug option to see where that `--platform` option is being passed in and I think it's this line:
> ```
> [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'node''. Working directory: .../mobile Command: node .../node_modules/@expo/cli/build/bin/cli bundle --platform android --dev false --reset-cache --entry-file .../mobile/index.js --bundle-output .../mobile/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle --assets-dest .../mobile/android/app/build/generated/res/createBundleReleaseJsAndAssets --sourcemap-output .../mobile/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map --minify false --verbose
> ```
> 
> so far I haven't found anything that documents a change in accepted options to the expo cli.
