### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by boogerjosh** [expo/expo#23481]
### Summary

I get error for building failed to eas build --platform android. Anyone know why?

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.5",
    "axios": "^1.4.0",
    "expo": "^48.0.7",
    "expo-asset": "~8.9.1",
    "expo-constants": "~14.2.1",
    "expo-device": "~5.2.1",
    "expo-font": "~11.1.1",
    "expo-image-manipulator": "^11.3.0",
    "expo-image-picker": "~14.1.1",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.2.0",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.16.4",
    "firebase": "^10.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.8",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-web": "~0.18.7",
    "react-redux": "^8.1.1",
    "redux": "^4.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@types/react-redux": "^7.1.25"
  },
  "resolutions": {
    "metro": "^0.73.7",
    "metro-resolver": "^0.73.7"
  },
  "overrides": {
    "metro": "^0.73.7",
    "metro-resolver": "^0.73.7"
  },
  "name": "josua_simatupang_apptest",
  "version": "1.0.0",
  "private": true
}

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.7 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.10
    Expo Workflow: bare

### Reproducible demo

<img width="735" alt="Screenshot 2023-07-12 at 09 14 27" src="https://github.com/expo/expo/assets/94213206/c3245027-c7d1-41bb-aa3c-4641a0d1ac37">

**Comment by emilyseibert** [comment]
Same here, though my error with is ":app:checkDebugAarMetadata" as described here: https://github.com/expo/expo/issues/23487

**Comment by RicardoBrito1938** [comment]
just correcting my error

` Task :app:createBundleReleaseJsAndAssets FAILED
Unknown or unexpected option: --platform
`

**Comment by Duell10111** [comment]
I run into the same issue.
<img width="1647" alt="image" src="https://github.com/expo/expo/assets/1345122/d4c9a4f4-b179-4149-977c-ab6c8c673eff">

**Comment by brentvatne** [comment]
please refer to: https://docs.expo.dev/build-reference/troubleshooting/

it seems that folks here are all encountering different issues. if you follow that guide and get to the end and haven't resolved it yet, it explains [how to ask a good question](https://docs.expo.dev/build-reference/troubleshooting/#how-to-ask-a-good-question)

**Comment by samixp02** [comment]
> just correcting my error
> 
> `Task :app:createBundleReleaseJsAndAssets FAILED Unknown or unexpected option: --platform`

I have the same issue with expo sdk 49 after downgraded to expo sdk 48 problem solved
