### ISSUE TITLE
FileSystem.pauseAsync will crash on iOS 12

### ISSUE THREAD

**Issue by amowu** [expo/expo#2349]
### Environment

```
Environment:
  OS: macOS 10.14
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/hahow-e01c845a-0899-4235-a484-eabd8aa7e8be.tar.gz
```

We have tested several iOS 12 related devices and found the same problem (iOS 11 device does not have this issue).

### Steps to Reproduce

1. Open example code on [Snak](https://snack.expo.io/@amowu/filesystemexample) -> Run on your device -> QR Code
2. Scan QR Code with **iOS 12** device
3. Click "Download" button and click "Pause" immediately when "downloadProgress" has started downloading

### Expected Behavior

"downloadProgress" should be paused, and should not crash

### Actual Behavior

Will crash on iOS 12

Screenshot:

![screenshot](https://user-images.githubusercontent.com/559351/46395709-d23e1e00-c71f-11e8-8bbf-76340bb611d3.gif)

### Reproducible Demo

https://snack.expo.io/@amowu/filesystemexample

**Comment by sjchmiela** [comment]
Hey, thanks for the issue! I've just submitted a fixing PR — https://github.com/expo/expo/pull/2404. It should land with the release of SDK 31. 🙂
