### ISSUE TITLE
[ios] swiping back before page mount freezes the app

### ISSUE THREAD

**Issue by isik-dev** [expo/expo#23492]
### Minimal reproducible example

https://github.com/isik-dev/ios-swipe-back-bug

### 🐛 Bug Description
- Navigating to and **immediately** out(using ios native swipe back action) of a page freezes the app.
- ❗**Important**: `swipe back` action should be done when the target page is mounting
  - Let's say you have Page1 and from there you can navigate to an inner Page2. In this case, your target page is Page2.
- With Expo SDK 49, when you put the app to the background and reopen it app, the bug somehow goes away (you can see it in the attached video or reproduce it with the given example)
- But with Expo SDK 48, you should kill the app and reopen it in order for the bug to go away.

### 📜 History
- Initially, I discovered the bug in one of my projects (expo managed workflow). Medium sized.
 - Thought it was caused by one the custom components used in the page. 
 - But even after stripping the whole page and just leaving the bare react-native components, we were able to reproduce the bug:
    ```ts
    import { View } from 'react-native';
    
    const OrderStringing = () => {
      return (
        <View
          style={{
            flex: 1,
            justifyContent: 'flex-start'
          }}
        ></View>
      );
    };
    
    export default OrderStringing;
    ```
  - ✅  I did research quite a while and seen some similar issues both here and in software-mansion.
  -  However,  was not able to find a suitable work-around as most of them covered unique react-native cli cases.
  - TBH, I don't know if the issue belongs here and/or should be opened separately within react-native project, but
  - As the bug appears to be easily reproducible even with a fresh `npx create-expo-app` project, I decided to open it here first.

### ♻️ How to reproduce
- I provided a link to a minimal reproducible example. You can refer to the README.md inside the repo and follow the steps to set up your environment.
- Make sure to use a physical device. 
  - (In my case, I used: `iPhone 13 Pro, iOS 16.5.1` and upgraded my Expo Go to the latest version that supports `SDK 49`)
1. Start the app. You should see a HomeScreen with a title: `Overview` and two buttons in the middle.
2. Click on `Go to Extro` button which should take you to the Detail Page.
3. From there, swipe back to navigate back to the HomeScreen. ⚠️ Do not use back button on the header!
   - #### @@@ Make sure to swipe back while the Detail Page is sliding from the right  @@@
---
- With this, you should be able to reproduce the bug 🐞.
- I will also attach a visual example below (just to make it easier and faster for you to understand and reproduce 😎)
- Feel free to ask for any help with reproduction and/or bug 😉: 
[reproduction_video.mp4.zip](https://github.com/expo/expo/files/12029214/reproduction_video.mp4.zip)

### Environment

```shell
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.0 - ~/Desktop/node_modules/.bin/npm
      Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 30, 31, 32
        Build Tools: 30.0.2, 32.0.0, 32.1.0
        System Images: android-29 | Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-UpsideDownCake | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.2 => 49.0.2
      react: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
    npmGlobalPackages:
      eas-cli: 3.15.1
    Expo Workflow: managed
```

**Comment by hirbod** [comment]
Since you're using the native stack navigator, this issue belongs to https://github.com/software-mansion/react-native-screens

**Comment by brentvatne** [comment]
thanks for the report! as @hirbod suggests, please repost this on the react-native-screens repository

**Comment by isik-dev** [comment]
@hirbod @brentvatne 
Thanks, I will report it there then!
