### ISSUE TITLE
[SDK49][expo-dev-client] Problem loading the project - `RCTFatal` in main

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/expo#23493]
### Summary

After upgrading to SDK49 and rebuilding the iOS dev client my app stopped working with the following error:

![simulator_screenshot_AEFDDA70-2150-4CD4-B3F1-18620FE39667](https://github.com/expo/expo/assets/3532342/4d6d1d88-f722-4186-ac5c-7cb96e230905)

Even with a completely fresh Expo App (`npx create-expo-app@latest --template blank@sdk-49`) for which I only really configured EAS and ran a simulator build through `eas build` I'm getting just the same error (console doesn't show me any errors).

I'm getting the same error on my physical device for my production app as well, but since the build process there involves `expo prebuild` and self-signing the build the quickest reproduction for me was through the simulator build.

You can find my reproduction down below, all you need to change is the EAS projectId.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "~49.0.2",
"expo-dev-client": "~2.4.5",
"expo-status-bar": "~1.6.0",
"react": "18.2.0",
"react-native": "0.72.1"

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.1 - /usr/local/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.2 => 49.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
    npmGlobalPackages:
      eas-cli: 3.15.1
    Expo Workflow: managed

### Reproducible demo

https://github.com/stefan-schweiger/expo-49-dev-client

**Comment by sjbuysse** [comment]
I have the same with a brand new expo project & SDK 49
Expo Go runs, but as soon as I make a dev-client, I get the problem above.

**Comment by brentvatne** [comment]
please update to expo@49.0.3, we have resolved the issue. i tested this against the reproducible example that you provided and after upgrading it works as expected :)

sorry for the hassle!
