### ISSUE TITLE
Remove transitive dependency on sqlite3

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#235]
websql depends on sqlite3 to use sqlite in node, but we don't actually need that. We should maybe fork https://github.com/nolanlawson/node-websql and remove the parts that we don't need, maybe even pulling them into expo-sdk because there's actually not much code that we need.

Related: https://github.com/react-community/create-react-native-app/issues/246

**Comment by nikki93** [comment]
Done for version >=18.0.0 coming out soon.
