### ISSUE TITLE
[SDK49.0.2][expo-blur][Android 13] - `ScrollView.overScrollMode` and `NativeStackNavigator` animations not working when using `BlurView`

### ISSUE THREAD

**Issue by crank-chips** [expo/expo#23504]
### Minimal reproducible example

https://snack.expo.dev/@crank-chips/android-expo-blur-snack

### Summary

Platform: Android 13
By default, `overScrollMode` is set to `auto` on the Android platform for ScrollView. So when the scroll reaches the end it has stretching effect of the view.
When using BlurView on the screen and `intensity` is > 0, that effect stops working.
The same happens for `NativeStackNavigator` animations from `react-navigation` package. Once BlurView intercity > 0 effect like `fade` stops working.

Attaching the screen recording:
https://github.com/expo/expo/assets/17419029/4a0ac3a4-bb32-40e3-9274-6485362f344a

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.8.0 - ~/.npm-global/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 32.0.0, 33.0.0, 34.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-32 | Google APIs Intel x86_64 Atom, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
        Android NDK: 25.2.9519653
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.2 => 49.0.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

**Comment by reft** [comment]
+1

**Comment by crank-chips** [comment]
@Kudo I see you actively worked on blur implementation for Android. Would this issue be interesting for you?

**Comment by crank-chips** [comment]
@expo-bot 
I'm wondering why it's still not accepted

**Comment by crank-chips** [comment]
@brentvatne this issue is on `needs review` status since July. This issue is really pulling back `expo-blur` integration. Could you please rewiev it if possible?

**Comment by brentvatne** [comment]
hi @crank-chips - we decided that releasing blur view support on android without it being flagged as experimental was actually a mistake, and we updated that in https://github.com/expo/expo/pull/24709

as far as we know, there is no generalizable approach to implementing blur views on android that supports a wide range of android versions and use cases. so, we will instead expose various approaches through the `experimentalBlurMethod` prop.

**Comment by crank-chips** [comment]
Thank you @brentvatne for the updates. I hope you can figure this out guys.

In meanwhile I'm using temporary solution using the WebView on Android.
So if anyone is facing same issue as me here is a code snippet that I use. It's not ideal but with this solution `overScroll` is working and screen stretches when swiping.
```
<WebView
  style={{position: "absolute", top: 0, bottom: 0, left: 0, right: 0}}
  source={{
    html: `
    <div style="position: absolute;
            top: 0;
            right:0;
            bottom: 0;
            left: 0;
            background: rgba(255, 255, 255, 0);
            -webkit-backdrop-filter: blur(100px);
            backdrop-filter: blur(100px);"
     />`,
  }}
/>
```

Usage:
```
<View style={{height: 100, width:100, overflow: "hidden" }}>
  <BlurContainer />
</View>
