### ISSUE TITLE
[iOS][expo-router] RCTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO

### ISSUE THREAD

**Issue by dylancom** [expo/expo#23503]
### Minimal reproducible example

npx create-expo-app@latest --template tabs@49

Demo video (smooth status bar transition upon opening, delayed upon closing): 
https://user-images.githubusercontent.com/47904203/152635313-b044f2fa-fcee-41c3-98b4-612d879e407d.mp4

### Summary

Dismissing a modal in the new example using "expo-router" has a delayed status bar style update.
This has been reported in the past in "react-native-screens": https://github.com/software-mansion/react-native-screens/issues/1305 and the advice has been to add the following to your app.json(ios key):
```
"infoPlist": {
  "UIViewControllerBasedStatusBarAppearance": true
},
```

This currently causes the app to crash with the error: `RCTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO`.
This exact same error has been reported before in Expo and had been fixed: https://github.com/expo/expo/pull/20104.

But since the new "expo-router" this is re-introduced again as `ExpoRoot.tsx` forces the use of "expo-status-bar".
I'm currently using the following patch (disabling expo-status-bar) as a quick hack to resolve the crash and have a smooth status bar transition (upon closing the modal):
```
diff --git a/node_modules/expo-router/src/ExpoRoot.tsx b/node_modules/expo-router/src/ExpoRoot.tsx
index 263a3a1..e1eabab 100644
--- a/node_modules/expo-router/src/ExpoRoot.tsx
+++ b/node_modules/expo-router/src/ExpoRoot.tsx
@@ -1,4 +1,4 @@
-import { StatusBar } from "expo-status-bar";
+// import { StatusBar } from "expo-status-bar";
 import React, { FunctionComponent, ReactNode, Fragment } from "react";
 import { Platform } from "react-native";
 import { SafeAreaProvider } from "react-native-safe-area-context";
@@ -64,7 +64,7 @@ export function ExpoRoot({
             {children}
 
             {/* Users can override this by adding another StatusBar element anywhere higher in the component tree. */}
-            <StatusBar style="auto" />
+            {/* <StatusBar style="auto" /> */}
           </SafeAreaProvider>
         </GestureHandlerRootView>
       </ParentWrapper>

```

### Environment

    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.02.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/dylancompanjen/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.2 => 49.0.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by dylancom** [comment]
Closing this in favor of the issue reported in expo/router: https://github.com/expo/router/issues/772

**Comment by a-eid** [comment]
I'm still facing this issue for some reason, I'm unable to tell where it's coming from exactly. 

![Screenshot 2024-06-22 at 9 04 33 PM](https://github.com/expo/expo/assets/19273413/96e88f3e-2459-46a4-b0bd-703c64676529)

**Comment by marklawlor** [comment]
@a-eid If you create a new issue with a reproduction repo then we can help debug your issue.

**Comment by mojindri** [comment]
no update on the ticket, i am facing issue,,simply by using expo status bar or react native statusbar!

**Comment by Lonka-Pardhu** [comment]
any fix for this yet.?

**Comment by a-eid** [comment]
FYI I am no longer facing this. @Lonka-Pardhu are you using the latest expo-router version ?

**Comment by DanielAraldi** [comment]
Hey guys, is there any update about the bug? I'm using Expo SDK `52.0.46`, and my expo-router is `4.0.20`. I made the following passes:

My Info.plist:
```plist
// ...
<dict>
  <key>UIViewControllerBasedStatusBarAppearance</key>
  <true/>
</dict>
```

My app.json:
```json
{
  "expo": {
    "ios": {
      "infoPlist": {
        "UIViewControllerBasedStatusBarAppearance": true
      }
    }
  }
}
```

My navigation structure:
```tsx
<Stack
  screenOptions={{
    headerShown: false,
    animation: 'slide_from_right',
    animationDuration: 400,
    statusBarTranslucent: true,
    statusBarStyle: 'light'
  }}
>
  <Stack.Screen name="(authentication)" options={{ headerShown: false }} />
  <Stack.Screen name="(tabs)" options={{ headerShown: false, statusBarStyle: 'dark' }} />
  <Stack.Screen name="(dashboard)" options={{ headerShown: false, statusBarStyle: 'dark' }} />
 </Stack>
```

For me, the `RCTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO` is shown and status bar is changed, but even so the Info.plist message persists in being displayed when my app start. Some update?
