### ISSUE TITLE
[iOS][Fabric] RN Screens crash on startup on Expo bare project

### ISSUE THREAD

**Issue by graszka22** [expo/expo#23512]
### Minimal reproducible example

https://github.com/graszka22/expo-screens-crash-reproduce

### Summary

To reproduce:
- create a new SDK 49 bare expo project with `npx create-expo-app@latest --template bare-minimum@sdk-49`
- switch to fabric architecture by adding `"newArchEnabled": "true"` to `Podfile.properties.json`
- add react-navigation and react-native-screens with `expo install`
- add code from basic react-navigation example
- `pod install`, clean and build the app
I've provided a repo with all steps above done.

Expected behaviour:
The app runs fine

Actual behaviour:
The app crashes on iOS with the following message:
```
Thread 1: "A view can only be associated with at most one view controller at a time! View <RNSScreenView: 0x16009c600; frame = (0 0; 0 0); layer = <CALayer: 0x600003b418e0>> is associated with <RNSScreen: 0x16084ed80>. Clear this association before associating this view with <RNSScreen: 0x16084f160>."
```

Also the app runs fine when it's created with react-native template (`npx react-native@latest init AwesomeProject`)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - /opt/homebrew/bin/npm
      Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/angelikaserwa/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.2 => 49.0.2
      react: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.0
    Expo Workflow: bare

**Comment by kvbalib** [comment]
same here with expo-router, just adding the <Stack> component crashes the app

**Comment by mars-peng-lb** [comment]
Same issue here and I also created a reproducible repo in [react-native-screens](https://github.com/software-mansion/react-native-screens/issues/1809#issuecomment-1680649713).
The react-native-screens team says this should be an Expo issue too.

**Comment by numandev1** [comment]
getting same issue

**Comment by numandev1** [comment]
![Screenshot 2023-08-17 at 1 09 47 PM](https://github.com/expo/expo/assets/36044436/1451ed7c-6aa5-490f-afc1-4790de8048f3)

**Comment by alexhernandez** [comment]
This issue also impacts other Software Mansion packages like React-Native-Reanimated w/ Expo Bate Modules

See issue here:
https://github.com/expo/expo/issues/23994
