### ISSUE TITLE
Hello everyone, I'm stuck on expo eas project, It can't install my own plugin that I forked

### ISSUE THREAD

**Issue by mickytroxxy** [expo/expo#23524]
### Minimal reproducible example

eas build -p android

### Summary

`Running "yarn install" in /home/expo/workingdir/build directory

yarn install v1.22.17

[1/4] Resolving packages...

[2/4] Fetching packages...

[stderr] 
error Command failed.

[stderr] 
Exit code: 128

[stderr] 
Command: git

[stderr] 
Arguments: ls-remote --tags --heads ssh://git@github.com/mickytroxxy/react-native-parallax-scroll-view.git

[stderr] 
Directory: /home/expo/workingdir/build

[stderr] 
Output:

[stderr] 
Host key verification failed.

[stderr] 
fatal: Could not read from remote repository.

[stderr] 

[stderr] 
Please make sure you have the correct access rights

[stderr] 
and the repository exists.

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

yarn exited with non-zero code: 128`

I ran eas build -p android with no lucky, but I have been uploading many apps with that plugin before. This has never happened before, please help me to resolve this, I want to upload my app today. I upgraded my eas-cli but nothing worked

Thank you

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.4.2 - /usr/local/bin/npm
      Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/lameckndhlovu/.rvm/rubies/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.9
    Expo Workflow: managed

**Comment by lutestringamend** [comment]
I have also experienced the same thing

**Comment by mickytroxxy** [comment]
How did you resolve this?

I'm still stuck
