### ISSUE TITLE
[Android][expo-file-system] createDownloadResumable finished but file size is 0KB on Android

### ISSUE THREAD

**Issue by chinamcafee** [expo/expo#23522]
### Minimal reproducible example

https://github.com/chinamcafee/file-system-test

### Summary

Minimal reproducible example shows createDownloadResumable can finished successfully，but when I inspect the file size on my Android device, I found that the size of the downloaded file is 0Kb.

The screenshot is as follows:
![image](https://github.com/expo/expo/assets/3439961/d4c2db1c-36a9-4843-b804-b2aaabe4dd15)

But [FileSystem.downloadAsync(uri, fileUri, options)] can works well and file size is as expected

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
      npm: 9.7.2 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    Expo Workflow: bare

**Comment by LunatiqueCoder** [comment]
I managed to reproduce this with `expo-dev-client@2.4.6`. Removing it seems to fix the issue for my side.

**Comment by jparkrr** [comment]
I'm seeing the same issue. 0 byte file is created from `createDownloadResumable`.

For now I've switched to using another library, [react-native-fs](https://github.com/itinance/react-native-fs). This is working.

> I managed to reproduce this with expo-dev-client@2.4.6. Removing it seems to fix the issue for my side.

Removing expo-dev-client didn't seem to fix it for me.

**Comment by LunatiqueCoder** [comment]
Be sure to reinstall pods or to recreate ios folder.

**Comment by woesbros** [comment]
> Be sure to reinstall the app (recreating android folder might also help)

but I need expo-dev-client to run my development build... did you perhaps mean downgrade the version? or what?

**Comment by SmartASCII** [comment]
Also running into this issue and likewise have had to resort to using react-native-fs for downloading.

**Comment by mediazard** [comment]
another thread same issue .. https://github.com/expo/expo/issues/24005

is anyone going to look into it ?

**Comment by AdeelCyber** [comment]
![image](https://github.com/expo/expo/assets/67343485/94085ea2-a425-428e-9c53-d8e7641f24e3)

Im trying to download files using createDownloadResumable but it is throwing an error
![image](https://github.com/expo/expo/assets/67343485/af2b629a-ab9a-4196-a9aa-a8f6e781c2bf)
