### ISSUE TITLE
[SDK 49.0.3] Expo Go doesn't open development project

### ISSUE THREAD

**Issue by SvetlozarValchev** [expo/expo#23529]
### Minimal reproducible example

n/a

### Summary

After updating to SDK 49, the project doesn't open neither in Android, nor in iOS. I've reinstalled the apps, but still the same. The project shows in 'Development Servers', but clicking it does nothing. If I downgrade to SDK 48, it works fine.

### Environment

$ npx expo-env-info
npm WARN exec The following package was not found and will be installed: expo-env-info@1.0.5

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ^49.0.3 => 49.0.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: managed

**Comment by kubmir** [comment]
@SvetlozarValchev did you find any solution for this ? It is the same for me + updates cannot be opened in Expo Go.

**Comment by SvetlozarValchev** [comment]
> @SvetlozarValchev did you find any solution for this ? It is the same for me + updates cannot be opened in Expo Go.

Tested the barebones template using `npx create-expo-app@latest --template blank@sdk-49` and it was working, so I replicated the package.json from it, removed node_modules and reinstalled everything from scratch. I'm not sure what was the issue, but it seems to be working now.
