### ISSUE TITLE
Expo image picker not working on Android 10 

### ISSUE THREAD

**Issue by reverend-insanity** [expo/expo#23533]
### Minimal reproducible example

Using the example method on the expo image picker docs

### Summary

It causes the whole app to crash on emulator and restart on a physical device. When using adb logcat I found an error about Bitmap recycling. I should mention this works well on Android 7.

### Environment

SDK 48
Expo image picker 14.1.1
Android 10

**Comment by Monik09** [comment]
@reverend-insanity was this issue fixed? I am facing the same issue...

**Comment by reverend-insanity** [comment]
> @reverend-insanity was this issue fixed? I am facing the same issue...
> 

Nah, but I fixed it by rewriting my navigation context. Also if you build you'll see it works fine on a physical device.
