### ISSUE TITLE
Inconsistency in dev menu button ordering between Expo Go dev menu and development builds' dev menu

### ISSUE THREAD

**Issue by josh-** [expo/expo#23538]
### Minimal reproducible example

N/A

### Summary

The ordering of buttons in the Expo Go dev menu is different to that of the dev menu for development builds:

|Expo Go|Development Build|
|-|-|
|<img src="https://github.com/expo/expo/assets/712727/7ffca527-9c2b-48db-96ec-53ab66e11acf" width="250" />|<img src="https://github.com/expo/expo/assets/712727/32066926-6919-48ef-85cc-ab58c764075e" width="250" />|

(eg. note "Reload" on the left in Expo vs on the right in development builds)

As someone who frequently switches between Expo Go and development builds, it would be great if the Reload button, and the element inspector, etc buttons were in the same order between these two different builds.

If this issues is accepted I'd be happy to open a pull request making the order consistent. Thanks ✨ 

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 3.4.1 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9787799
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.14.0
    Expo Workflow: bare
```

**Comment by josh-** [comment]
@kadikraman noticed that you changed the design of the dev menu in https://github.com/expo/expo/pull/24426 - is there a chance that the new dev menu design can be ported to the Expo Go dev menu too? (so they can both be made consistent)

I believe the separate Expo Go dev menu is defined here: https://github.com/expo/expo/blob/388eb71cd8491a13c40fddce725beed70b4dd0ce/home/menu/DevMenuView.tsx#L174-L197

**Comment by kadikraman** [comment]
Thanks for reporting this @josh-: agreed that consistency between the dev menus is would make for a nicer experience. We'll update the Expo Go menu to match.

**Comment by josh-** [comment]
Fantastic! Thank you so much @kadikraman! 🙌
