### ISSUE TITLE
[Android][expo-modules-core] Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute()

### ISSUE THREAD

**Issue by thefranfran** [expo/expo#23537]
### Minimal reproducible example

https://github.com/thefranfran/expo-modules-example

### Summary

I work on a bare react native project with the Expo SDK 49.0.0, everything works fine on IOS but not on Android.

I use this packages from expo:

"expo": "~49.0.3",
"expo-font": "~11.4.0",
"expo-haptics": "~12.4.0",
"expo-linear-gradient": "~12.3.0",
"expo-splash-screen": "~0.20.4",
"expo-status-bar": "~1.6.0",
"expo-system-ui": "~2.4.0",

### Android Configuration
android/build.gradle

dependencies {
        classpath("com.android.tools.build:gradle:7.4.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.google.gms:google-services:4.3.15")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10")
    }

distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip

### Trace Stack

Script '/Users/francoiscipriani/Desktop/poke/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 356

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > Failed to notify project evaluation listener.
      > Could not create task ':expo-modules-core:compileDebugAndroidTestKotlin'.
         > Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
      > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.

### Environment

System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.7.2 - /opt/homebrew/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by Guiladg** [comment]
Same here

**Comment by Sannijiv** [comment]
+1

**Comment by ryanBuzzni** [comment]
same here!!
please check this issue !!!~!~!~!~!~!~!  😭

**Comment by burakgokcinarr** [comment]
Hello, I think I found the solution.

I had created a project via Expo (expo prebuild). The app.json content of my project is as follows.

"dependencies": {
     "expo": "~49.0.5",
     "expo-splash-screen": "~0.20.4",
     "expo-status-bar": "~1.6.0",
     "react": "18.2.0",
     "react-native": "0.72.3"
   },


There is no problem for the iOS part. But I was getting the following error for Android.

![image](https://github.com/expo/expo/assets/18294228/2fcbfe54-eb2d-4ec5-8380-1323b23c6f34)

The default gradle 8.0.1 is used and I think there is a problem with the kotlin version (1.8.10) for this version. I did not have a problem by making the following change.

In the build.grandle file;

kotlinVersion = findProperty('android.kotlinVersion') ?: '1.8.10'

in its place

kotlinVersion = '1.9.0'

and then by doing "sync gradle project file" there was no problem.

**Comment by igorskiter** [comment]
I have same issue.I used `expo-build-properties` and set  `"kotlinVersion": "1.9.0"` but in gradle.properties set `android.kotlinVersion=1.6.10`. Anyone have a solution?

**Comment by xkelxmc** [comment]
same problem with kotlinVersion 1.8.10, 1.8.22, 1.9.0

**Comment by 7dp** [comment]
Having the same problem too.
But thanks to @burakgokcinarr , my Android app now builds by setting the Kotlin version to `1.9.0`.
Something like:

```gradle
ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"

        kotlinVersion = "1.9.0" //  <--- Add this line.
    }
```

Have a nice day! 🙌
