### ISSUE TITLE
[SDK 49 - App Orientation Lock - iOS] Device orientation is not locked as expected

### ISSUE THREAD

**Issue by jivanovic** [expo/expo#23541]
### Minimal reproducible example

/

### Summary

A lot of changes have been made to `expo-screen-orientation` in SDK 49. However I have noticed that setting the `orientation` value `app.json` has no effect on iOS devices (using 16.5.1). Setting the value of `plugins` > `initialOrientation` inside the `app.json` also has no effect. It works as expected on Android devices.

What this means is that that rotating the app actually changes the orientation even if you want to lock it to  a specific orientation.

**QUICKFIX** - use the orientation API and lock to the desired orientation inside `App.tsx`:

`useEffect(() => {
 async function lockOrientation() {
        await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);
    }
    lockOrientation();
  }, []);`

### Environment

  expo-env-info 1.0.5 environment info:

    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh

    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman

    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod

    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1

    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild

    npmPackages:
      expo: ^49.0.3 => 49.0.3 
      expo-screen-orientation: ~6.0.3 => 6.0.3
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 

    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.0.1

    Expo Workflow: managed (dev client)

**Comment by RyanTG** [comment]
Seems like it should be easy to make a minimal reproducible example of this one. All you need is SDK 49 and orientation: 'portrait" in the config!
