### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by nasir733** [expo/expo#23555]
### Minimal reproducible example

I dont think this has anything to do with my code because this error was not happening on expo router v1 and expo sdk 48 started happening after i upgraded to sdk 49

### Summary

I'm getting this error in my project after upgrading to expo SDK 49 . this error happens after some time of running and working on the project 
<--- Last few GCs --->

[50690:0x130078000]   696599 ms: Mark-sweep (reduce) 3961.5 (4055.3) -> 3961.3 (4055.5) MB, 621.6 / 0.0 ms  (average mu = 0.133, current mu = 0.027) allocation failure; GC in old space requested
[50690:0x130078000]   697138 ms: Mark-sweep (reduce) 3961.3 (4055.5) -> 3961.3 (4055.0) MB, 522.0 / 0.0 ms  (average mu = 0.086, current mu = 0.030) allocation failure; GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100ca6200 node::Abort() [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 2: 0x100ca63f0 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 3: 0x100dec8ec v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 4: 0x100f97654 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 5: 0x100f9b25c v8::internal::Heap::CollectSharedGarbage(v8::internal::GarbageCollectionReason) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 6: 0x100f98250 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 7: 0x100f956a8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 8: 0x100f8a3e0 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
 9: 0x100f6fd98 v8::internal::Factory::CodeBuilder::AllocateCode(bool) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
10: 0x100f6f6b8 v8::internal::Factory::CodeBuilder::BuildInternal(bool) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
11: 0x100e3e8bc v8::internal::baseline::BaselineCompiler::Build(v8::internal::LocalIsolate*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
12: 0x100e590b8 v8::internal::GenerateBaselineCode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
13: 0x100e9ddf8 v8::internal::Compiler::CompileSharedWithBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
14: 0x100e9e1d0 v8::internal::Compiler::CompileBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
15: 0x100e39da0 v8::internal::baseline::BaselineBatchCompiler::CompileBatch(v8::internal::Handle<v8::internal::JSFunction>) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
16: 0x100e39ca8 v8::internal::baseline::BaselineBatchCompiler::EnqueueFunction(v8::internal::Handle<v8::internal::JSFunction>) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
17: 0x100f42e44 v8::internal::TieringManager::OnInterruptTick(v8::internal::Handle<v8::internal::JSFunction>) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
18: 0x1013006e8 v8::internal::Runtime_BytecodeBudgetInterruptWithStackCheck(int, unsigned long*, v8::internal::Isolate*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
19: 0x10164d04c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
20: 0x1016e8768 Builtins_JumpLoopHandler [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
21: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
22: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
23: 0x10df2227c 
24: 0x10df253b4 
25: 0x10df23908 
26: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
27: 0x10df2227c 
28: 0x10df253b4 
29: 0x10df23908 
30: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
31: 0x10df2227c 
32: 0x10df253b4 
33: 0x10df23908 
34: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
35: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
36: 0x10df2227c 
37: 0x10df253b4 
38: 0x10df23908 
39: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
40: 0x10df2227c 
41: 0x10df253b4 
42: 0x10df23908 
43: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
44: 0x10df2227c 
45: 0x10df253b4 
46: 0x10df23908 
47: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
48: 0x10df2227c 
49: 0x10df253b4 
50: 0x10df23908 
51: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
52: 0x10df2227c 
53: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
54: 0x10df23908 
55: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
56: 0x10df2227c 
57: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
58: 0x10df23908 
59: 0x1015d8198 Builtins_InterpreterEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
60: 0x1060326a8 
61: 0x1070a3a1c 
62: 0x1070a3d54 
63: 0x107251d60 
64: 0x101609ef4 Builtins_AsyncFunctionAwaitResolveClosure [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
65: 0x1016986f8 Builtins_PromiseFulfillReactionJob [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
66: 0x1015fbc4c Builtins_RunMicrotasks [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
67: 0x1015d63a4 Builtins_JSRunMicrotasksEntry [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
68: 0x100f18e7c v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
69: 0x100f1936c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
70: 0x100f19548 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
71: 0x100f3fc18 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
72: 0x100f404b0 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
73: 0x1015d9a34 Builtins_CallApiCallback [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
74: 0x10df20f34 
75: 0x1015d64d0 Builtins_JSEntryTrampoline [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
76: 0x1015d6164 Builtins_JSEntry [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
77: 0x100f18eac v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
78: 0x100f183e0 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
79: 0x100e08914 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
80: 0x100bf0d00 node::InternalCallbackScope::Close() [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
81: 0x100bf0fc8 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
82: 0x100c058ec node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
83: 0x100d44edc node::(anonymous namespace)::CompressionStream<node::(anonymous namespace)::ZlibContext>::AfterThreadPoolWork(int) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
84: 0x1015b4d28 uv__work_done [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
85: 0x1015b84c4 uv__async_io [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
86: 0x1015ca210 uv__io_poll [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
87: 0x1015b8954 uv_run [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
88: 0x100bf16d4 node::SpinEventLoop(node::Environment*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
89: 0x100ce1128 node::NodeMainInstance::Run() [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
90: 0x100c74ec8 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
91: 0x100c75190 node::Start(int, char**) [/Users/nasiriqbal/.nvm/versions/node/v18.12.1/bin/node]
92: 0x182601058 start [/usr/lib/dyld]
[1]    50689 abort      npx expo run:ios

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v18.12.1/bin/npm
      Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-Tiramisu | Google Play ARM 64 v8a, android-UpsideDownCake-ext5 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by Tehnix** [comment]
Recently ran into this as well, it was caused by me accidentally having created a infinitely recursive component. 

This then caused Expo to hang when it was trying to pre-generate the routes, and it wouldn't react to `Ctrl-C` but had to either kill the expo process or wait a couple of minutes until Expo went OOM and outputted the same error as the issue here.

It essentially looked like this (minimal repro):

```tsx
export function ThemeSwitcher() {
  return (
    <View>
      {/* Oh no, recursive rendering causing an infinite loop! */}
      <ThemeSwitcher />
    </View>
  );
}
```

I wasted enough time hunting this down that I made myself a quick eslint rule to prevent it from ever happening again 😅 


The rule logic:

```js
export default {
  meta: {
    type: 'problem',
    docs: { description: 'Disallow components rendering themselves' },
  },
  create(context) {
    const componentStack = [];

    const enter = (node) => {
      const name = node.id?.name || node.parent?.id?.name;
      if (name?.[0]?.toUpperCase() === name?.[0]) componentStack.push(name);
    };
    const exit = () => componentStack.pop();

    return {
      FunctionDeclaration: enter,
      'FunctionDeclaration:exit': exit,
      FunctionExpression: enter,
      'FunctionExpression:exit': exit,
      ArrowFunctionExpression: enter,
      'ArrowFunctionExpression:exit': exit,

      JSXIdentifier(node) {
        if (node.parent.type === 'JSXOpeningElement' && componentStack.includes(node.name)) {
          context.report({
            node,
            message: `Component <${node.name}> is recursively rendering itself. This can lead to infinite loops, freezes, and performance issues.`,
          });
        }
      },
    };
  },
};
```

Then in your config add it:

```js
// ...
import noRecursiveComponent from './lint/no-recursive-components.js';

export default defineConfig([
  // ..your other eslint config
  {
    plugins: {
      custom: { rules: { 'no-recursive-component': noRecursiveComponent } },
    },
    rules: { 'custom/no-recursive-component': 'error' },
  }
]);
```
