### ISSUE TITLE
React native build fails when the _JAVA_OPTIONS environment variable is set

### ISSUE THREAD

**Issue by tomhense** [expo/expo#23553]
### Minimal reproducible example

https://github.com/Codedotexe/expo-java-options-issue

### Summary

Having the java environment variable _JAVA_OPTIONS set will cause a react native build for android with the expo modules installed to fail.

###### Part of the error message:
```
* What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeDebug[arm64-v8a]'.
```

### Reproducibility
It can be reproduced by running the example repository I provided or by running the following command to create a example for yourself:

###### Initialize a example project and install expo modules
```bash
npx react-native@latest init AwesomeProject
cd AwesomeProject
npx install-expo-modules@latest
```

###### Set java options (any option will cause the build to fail even an empty string)
```bash
export _JAVA_OPTIONS="-Xmx2048m"
```

###### Start the app (android)
```bash
npm start
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.4 Arch Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.8.0 - ~/.local/share/npm/bin/npm
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ^49.0.0 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by M-ismail-ramzan** [comment]
`unset _JAVA_OPTIONS`  to fix building temporary
