### ISSUE TITLE
Audit components that should respect native view lifecycle

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2355]
With the introduction of react-native-screens into react-navigation, it's possible for us to natively respond to a screen becoming inactive. We should make sure that Camera, BarCodeScanner, Lottie, MapView, Video, GLView, and potentially other native components respond appropriately to native lifecycle events. For example, when a BarCodeScanner is not on an active screen it shouldn't continue scanning, and the preview should stop.

**Comment by ide** [comment]
What do you think about having a standard event that we fire when one of these singleton views gets paused or resumed? Generally speaking, developers probably wouldn't need to use these events but they seem helpful for debugging and writing tests (e.g. mount Camera 1, mount Camera 2, expect Camera 1 to pause, mount Camera 3, expect Camera 2 to pause, unmount Camera 2, unmount Camera 3, expect Camera 1 to resume).

**Comment by FiberJW** [comment]
Is there any movement in regards to this issue? Or is it stale/closable?
