### ISSUE TITLE
Android no longer scrolls to input on initial focus

### ISSUE THREAD

**Issue by Jackman3005** [expo/expo#23564]
### Summary

Hello, we have been upgrading from SDK 47 to 49 and have noticed a regression in behavior with Android and how it behaves when you click on a TextInput towards the bottom of the screen. The keyboard comes up and covers the input now (at least initially). If I make repeated focus changes the follow-up ones will actually scroll to the input if the keyboard will cover it, **but for multi-line inputs it now only scrolls to show the top of the input, not the full input like it used to.**

I have tried many combinations of changing the React Native `KeyboardAvoidingView` (`KAV` in the table below) behavior (including disabling it) and the Android's Keyboard layout setting defined in the App Config: (`softwareKeyboardLayoutMode: 'pan'`). Each of the possible combinations resulted in the regression or other regressions.

| `KAV` Behavior | `'pan'` layout | `'resize'` layout |
| -- | -- | -- |
| `position` | [keyboardLayout-pan-kav-position.webm](https://github.com/expo/expo/assets/1906988/c4a36d72-6f58-4cb0-9bc7-736ea210f571) | [keyboardLayout-resize-kav-position.webm](https://github.com/expo/expo/assets/1906988/4b65640f-7b69-4cbf-bed1-b060d46ff043) | 
| `padding` | [keyboardLayout-pan-kav-padding.webm](https://github.com/expo/expo/assets/1906988/dd946142-aaf3-4420-9f96-a57fcc7c0810)| [keyboardLayout-resize-kav-padding.webm](https://github.com/expo/expo/assets/1906988/d33c7e33-cd82-4e90-8981-78b0b0ee7853) | 
| `height` | [keyboardLayout-pan-kav-height.webm](https://github.com/expo/expo/assets/1906988/25c9b833-b59a-4243-aa48-64d2c514bf5b)| [keyboardLayout-resize-kav-height.webm](https://github.com/expo/expo/assets/1906988/fdfeacc3-4c40-4438-ab10-c136e1bacf53)| 
| `disabled` | [keyboardLayout-pan-kav-disabled.webm](https://github.com/expo/expo/assets/1906988/e3f48905-5529-40ac-9718-69b372520a7a) | [keyboardLayout-resize-kav-disabled.webm](https://github.com/expo/expo/assets/1906988/acb38772-e33d-4fc1-8ad8-220d12784c99) | 

Unfortunately I was not having any success building our app with Expo 48, so I cannot definitively say if this was introduced going from 47 to 48 or 48 to 49 . **Edit: @louislatreille confirmed [below](https://github.com/expo/expo/issues/23564#issuecomment-1682881219) that it happens when upgrading from Expo 48 to 49**

### Minimal reproducible example

https://snack.expo.dev/@jcoy/belligerent-stroopwafels
> Note: I have provided a Snack,but the Expo snack UI seems to be crashing on Android right now for both physical device and the device they  offer.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/workspace/qm-universe/node_modules/.bin/yarn
      npm: 9.6.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.10
    Expo Workflow: bare
```

**Comment by Taktime-L** [comment]
+1

**Comment by Jackman3005** [comment]
Who would be best to take a look at this?

**Comment by louislatreille** [comment]
I'm getting the same error after upgrading to SDK 49. I can confirm that the issue has been introduced by SDK 49, as I was on 48 before.

The snack @Jackman3005 has provided is on expo 47. I've re-used most of it and upgraded to SDK 49 and could easily reproduce the issue. Made a reproduction repo: https://github.com/louislatreille/keyboardIssueExpo49

**Comment by Jackman3005** [comment]
@louislatreille Thank you for creating a legitimate reproduction! This is stopping us from upgrading to Expo 49 for the time being.

**Comment by keith-kurak** [comment]
Hi all!

I tried the code in the repro's App.js in SDK's 47, 48, 49, and found it scrolled correctly to a `TextInput` below keyboard height in 47 and 48, but not 49. ([repro with a branch for each one](https://github.com/keith-kurak/sdk-49-keyboard-scrolling)). 

ScrollView/ Keyboard interaction is a pretty core-level thing that wouldn't likely be affected by a new SDK directly, but new Expo SDK's generally ship with updated versions of `react-native`. To that end, I found this issue and its associated PR here, which shipped in RN 72.4 (SDK 49 is currently on 72.3): https://github.com/facebook/react-native/issues/38152

I then created a project with the RNC CLI (`npx react-native@latest init ProjectName`), ran it on Android, and they scroll interaction worked. I then downgraded it to RN 72.3 and it behaved just like the SDK 49 project. Thus, I think it was an RN regression that was later fixed.

I've accepted this issue and will raise it internally so we can see if it would work to up the `react-native` version.

In terms of fast workaround, the actual PR that fixed this is quite small (https://github.com/facebook/react-native/pull/38728), and I think it would be straightforward to apply with patch-package, and then you could get that fix right away with a development build or in your production code (just not in Expo Go).

I would also recommend trying to reproduce the issue on the latest RN, just in case there's a scenario that it doesn't cover, so another issue can be opened on the RN repo.

**Comment by louislatreille** [comment]
Big thanks @keith-kurak for going to the bottom of that issue!

I can confirm that after upgrading to RN 72.4, my keyboard works as expected.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
it seems that the issue has been resolved, so I'm going to close this.
Thank you 🙂
