### ISSUE TITLE
Updates.checkForUpdatesAsync causes crash on ExpoGo

### ISSUE THREAD

**Issue by Chantall647** [expo/expo#23567]
### Minimal reproducible example

`
const checkForUpdates = async () => {

    try {
      const updates = await Updates.checkForUpdateAsync()
      if (updates.isAvailable) {
        showModal({
          title: i.t('AppUpdate Title'),
          body: i.t('AppUpdate Description'),
          primary: {
            text: i.t('AppUpdate Confirm'),
            onPress: () => {
              Updates.fetchUpdateAsync().then(value => {
                if (value.isNew) {
                  Updates.reloadAsync()
                }
              })
            },
          },
        })
      }

    } catch (e) {
      console.log(e)
    }
  }
`

### Summary

Updates.checkForUpdateAsync() is causing a crash on IOS in ExpoGo, Android works fine.  
I have the latest version of Expo Go.

If I comment out the function that checks for updates, it does not crash. 

Using v.0.15.6 of expo-updates.

We seem to experience the same issues as in this bug report https://github.com/expo/expo/issues/12604 .

Managed or bare workflow? If you have ios/ or android/ directories in your project, the answer is bare!
managed

What platform(s) does this occur on?
iOS

SDK Version (managed workflow only)
47.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
      Yarn: 1.22.17 - ~/Desktop/appBofrost/bofrost-expo-app/node_modules/.bin/yarn
      npm: 9.7.1 - ~/.nvm/versions/node/v14.21.3/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.15.1
    Expo Workflow: managed

**Comment by douglowder** [comment]
We would recommend that you upgrade to SDK 49, or at least SDK 48, as SDK 47 will be dropped in the next Expo Go release.

That said, please provide an example app that reproduces the issue (so we can see what modules you are including, your Expo config (app.json), etc.) and we will take a look.
