### ISSUE TITLE
unable to get app context in Expo modules

### ISSUE THREAD

**Issue by gur22-09** [expo/expo#23566]
### Minimal reproducible example

1. run `npx create-expo-module my-module` 
2.  navigate to MyModule.kt file inside `android` directory 
3. try to access the app context inside the module   

### Summary

when tried to run the app build it fails with the error `the module wasn't created! you can't access the app context`.

below is the code for the module 
```
class MyModule : Module() {
  // Each module class must implement the definition function. The definition consists of components
  // that describes the module's functionality and behavior.
  // See https://docs.expo.dev/modules/module-api for more details about available components.
  val context: Context
  get() = appContext.reactContext ?: throw Exceptions.ReactContextLost()
  

  override fun definition() = ModuleDefinition { 
    Name("MyModule")
  }
```

<img width="348" alt="Screenshot 2023-07-17 at 10 58 20 AM" src="https://github.com/expo/expo/assets/59470020/bee1c7ac-e446-45b2-a5bf-1196085863d2">

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - ~/diptab/expo-core/node_modules/.bin/npm
      Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
    Expo Workflow: bare

**Comment by lukmccall** [comment]
Hi, @gur22-09, thanks for your report. 
It is incorrect to access the `AppContext` in the module constructor. The `AppContext` is added to the module before the `ModuleDefinition` is evaluated, but after the constructor is invoked. Therefore, you can only use it in the `ModuleDefinition` block.

However, you can still define getters like this:
```kotlin
val context: Context
  get() = appContext.reactContext ?: throw Exceptions.ReactContextLost()
 ``` 
But you can use them only inside of the definition block.
