### ISSUE TITLE
The Android application I built with EAS crashes. (Expo 48)

### ISSUE THREAD

**Issue by ardasnturk** [expo/expo#23594]
### Summary

Hello everyone. In the last 2 weeks, has there been an update for eas? I am building my application with eas. 2 weeks ago I created a build and it was running smoothly. I created a new build today with the same codes, but the application crashes before opening on android. Everything is the same, I just increased the versionCode of android. There is no other change in the code. Also when I run the `npx expo run:android -d --variant Release` command, the application runs smoothly but crashes when I do eas build.

Expo: 48.0.18
ReactNative: 0.71.8
EAS: eas-cli/3.15.1
Expo Cli: 6.3.10

[Discord](https://discord.com/channels/695411232856997968/943205994123657246/1130814830681530379)

### What platform(s) does this occur on?

Android

### SDK Version

48.0.18

### Environment

```
System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.10
```

### Minimal reproducible example

```
> yarn rm -rf android; rm -rf ios; rm -rf node_modules; yarn; npx expo prebuild --clean --no-install
> eas.json :
"build": {
    "production": {
      "node": "16.13.0",
      "yarn": "1.22.19",
      "releaseChannel": "production",
      "android": {
        "buildType": "apk"
      }
    },
   ...
   }
}
> eas build --platform android --local or eas build --platform android
> app open and crash! 💥

**Comment by jonhassall** [comment]
Can you get your ADB error logs?

**Comment by jonhassall** [comment]
Try this @ardasnturk [https://kb.vmware.com/s/article/2960948](https://kb.vmware.com/s/article/2960948)
I recommend filtering by Error or you get a lot of noise.

**Comment by jonhassall** [comment]
@ardasnturk you may want to try https://github.com/expo/expo/issues/23599#issuecomment-1641777296

**Comment by ardasnturk** [comment]
I've tried filtering, but I haven't been very successful, but I think I've captured something that might help. App's packageName `de.int.development.smartvillage.app`
<img width="1347" alt="image" src="https://github.com/expo/expo/assets/11755668/1e4ba7b4-ff34-41ba-83a9-37bec715ef9b">
<img width="1284" alt="image" src="https://github.com/expo/expo/assets/11755668/7298c58f-146a-41e3-a6f7-6980abc37fde">

**Comment by jonhassall** [comment]
Looks like the same error I had. Try removing expo-updates and sentry-expo packages

**Comment by ardasnturk** [comment]
I will try, but why did it happen now when there was no such problem before? Any ideas?

**Comment by jonhassall** [comment]
See [https://github.com/expo/expo/issues/23599#issuecomment-1641151807](https://github.com/expo/expo/issues/23599#issuecomment-1641151807)

**Comment by ardasnturk** [comment]
Thank you very much. 🙏 I tried your method and it worked. But I need the sentry. Do you use any alternative? When I install sentry, it automatically uses the expo-updates package. They are connected to each other. How can I solve this? Did you just delete it in your application or did you do something else?

**Comment by jonhassall** [comment]
I just deleted it to get the release out. Perhaps you could raise a bug on sentry-expo's GitHub issues?

**Comment by ardasnturk** [comment]
This is how I solved the problem, please see the comment here. We need to configure the `expo-updates` package even if we don't use it.

I added the following code to `app.json` and the problem is solved:

 `"updates": { "url": "https://u.expo.dev/...” }`

https://forums.expo.dev/t/app-crashes-on-launch-with-manifest-error/72703/11?u=ardasnturk
