### ISSUE TITLE
Calling Expo.DangerZone.Branch.setIdentity crashes app

### ISSUE THREAD

**Issue by raphaelrk** [expo/expo#2360]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.10.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/raphaelrk-a471fb78-32dd-4337-809f-a8e16de1599a.tar.gz

Target: iOS Simulator Expo Client

### Steps to Reproduce

1. Call Branch.setIdentity

### Expected Behavior

App does not crash

### Actual Behavior

App crashes

### Reproducible Demo

[Example snack](https://snack.expo.io/@raphaelrk/branch-setidentity-bug)

In my actual app, I also call Branch.subscribe in componentDidMount in App.js, and I set `expo.ios.config.branch.apiKey` in `app.json`.

Parallel issue I made in the `react-native-branch-deep-linking` repo: [link](https://github.com/BranchMetrics/react-native-branch-deep-linking/issues/382)

**Comment by raphaelrk** [comment]
@veedeo that helped fix it for me. 

Does it work only in 'standalone' or also in 'guest'? Would be nice if Expo.DangerZone.Branch gave a warning that Branch only works in standalone builds - tough issue to track down since it crashes the app immediately.

**Comment by rahamin1** [comment]
@raphaelrk How did this help?

What does 'guest' mode mean? My app is crashing on an apk, which I thought means standalone build. I am also checking that Constants.appOwnership is 'standalone'...

Can you look at https://github.com/expo/expo/issues/3546 : perhaps you can help.

**Comment by raphaelrk** [comment]
@rahamin1 Guest mode is when your app is opened by another app: [https://docs.expo.io/versions/v32.0.0/sdk/constants/](https://docs.expo.io/versions/v32.0.0/sdk/constants/)

**Comment by rahamin1** [comment]
Thanks. Unfortunately, this doesn't solve my problem...

**Comment by sjchmiela** [comment]
In standalone apps on SDK34 with use of `expo-branch` the issue has been solved (as per https://github.com/expo/expo/issues/5349).
