### ISSUE TITLE
Styling of <Link> component in expo-router: 2.0.0

### ISSUE THREAD

**Issue by sayemon10** [expo/expo#23619]
### Summary

styling issue of <Link> component happening in IOS & Android.
in IOS it's working as expected, not in Android
package.json and index.tsx provided to recreate the issue.

![Screenshot 2023-07-19 at 3 09 20 PM](https://github.com/expo/expo/assets/35277447/d2578566-d479-44bf-ba55-ab42deea17bd)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

```
"dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~49.0.3",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.1.3"
  },
  ```

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.8
    Expo Workflow: managed

### Reproducible demo

app/index.tsx

```
import React from "react";
import { View, Text } from "@/components/Themed";
import { Link, SplashScreen } from "expo-router";
import { useColorScheme } from "react-native";
import { Ionicons } from "@expo/vector-icons";

SplashScreen.preventAutoHideAsync();

export default function App() {
  const [isReady, setReady] = React.useState(false);
  React.useEffect(() => {
    // Perform some sort of async data or asset fetching.
    setTimeout(() => {
      // When all loading is setup, unmount the splash screen component.
      SplashScreen.hideAsync();
      setReady(true);
    }, 1000);
  }, []);

  const colorMode = useColorScheme();
  const iconColor = colorMode === "dark" ? "white" : "black";

  return (
    <>
      <View className="w-full h-full flex items-center justify-center px-4">
        <Link href="/calender" className="w-full">
          <View className="flex w-full dark:bg-gray-900 flex-row p-3 dark:text-white border dark:border-white items-center justify-between">
            <Text className="text-xl">Select Date</Text>
            <Ionicons
              name="calendar-outline"
              size={24}
              // style={{ marginLeft: "auto" }}
              color={iconColor}
            />
          </View>
        </Link>
      </View>
    </>
  );
}
```

**Comment by sayemon10** [comment]
found the solution for this issue.

# **put all the content inside a <Pressable> component to solve problem.**

```
return (
    <>
      <View className="w-full h-full flex items-center justify-center px-4">
        <Link href="/calender" className="w-full">
          <Pressable>
            <View className="flex w-full dark:bg-gray-900 flex-row p-3 dark:text-white border dark:border-white items-center justify-between">
              <Text className="text-xl">Select Date</Text>
              <Ionicons
              name="calendar-outline"
              size={24}
              // style={{ marginLeft: "auto" }}
              color={iconColor}
            />
            </View>
          </Pressable>
        </Link>
      </View>
    </>
  );
}
```

Thanks to @amandeepmittal 🥂

**Comment by exoer** [comment]
I'm having some issues with the `Link` component too. I use Nativewind. It appears that the `Link`-component is not "neutral/transparent". It behaves as a `Text` that can accept string (text) as children.

The styleProps of the `<Link />` is of type `StyleProp<TextStyle>`

So i guess the use-case for Link it so replace a text. 

For Buttons with background color and width and touch-properties i guess it is better to fallback to `router.push(/destination)`?

**Comment by amandeepmittal** [comment]
@exoer, by default, the `Link` component wraps children in a `Text` component. You can use the `asChild` attribute on `Link` to customize it as mentioned in the docs: https://docs.expo.dev/routing/navigating-pages/#buttons

**Comment by welschmoor** [comment]
I still don't understand how to fix this. Using asChild makes the Link unclickable, plus the constant log message `ERROR  Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
`

**Comment by amandeepmittal** [comment]
Hey @welschmoor, the `asChild`  is meant to be used as a prop on the `Link` component. Please share a minimal reproducible example and I'll take a look.

>ERROR  Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? 

 In that case, you can use the syntax as per [React docs](https://react.dev/reference/react/forwardRef#forwardref).

**Comment by welschmoor** [comment]
The `<Link asChild href="/home">` becomes unclickable after adding asChild. My Code was identical to https://docs.expo.dev/router/navigating-pages/#buttons

 I replaced the link with a `<Pressable onPress={()=> { router.push("/home") } ... `  and solved it that way.

**Comment by amandeepmittal** [comment]
No problem! just tested `<Link asChild href="/home">` in an example and it is working for me. Which Expo Router version are you using?

Yeah, you can also use `router.push()`.

**Comment by welschmoor** [comment]
I created a new expo app about 2 weeks ago the standard way (docs, chose router).
    "expo": "~50.0.7",
    "expo-router": "~3.4.7",

**Comment by lorsk** [comment]
I know this is closed but for anyone in the future, asChild simply uses the child (Pressable) to trigger the href of the parent (Link) so that you can do something like this: 

```
<Link href="/link" asChild>
   <Pressable style={{...}}> // no onClick needed here, only styling
   </Pressable>
</Link>
```

This way you define the style in the Pressable as well as maintain any onpress styling that Pressable has, while still going to `/home`
