### ISSUE TITLE
Expo Image Web Bug

### ISSUE THREAD

**Issue by megantaylor** [expo/expo#23625]
### Minimal reproducible example

expo image isn't available on Snack

### Summary

I was excited to start using Expo Image for its caching features, but when I started switching things over in my app, I realized that on Web the images had the following CSS (native seems to be fine):

```
width: '100%',
height: '100%',
position: 'absolute',
left: 0,
right: 0,
objectPosition,
filter: tintColor ? `url(#tint-${tintColor})` : '',
...style,
...(isHash ? hashPlaceholderStyle : {}),
```

this shoves the image down inside a container with `overflow:hidden` on it and now the image is invisible. 

I think this issue is actually fixed by the refactor by @aleqsio in https://github.com/expo/expo/pull/23465, which changes the CSS to

```
objectPosition,
...absoluteFilledPosition,
...getTintColorStyle(tintColor),
...(isHash ? hashPlaceholderStyle : {}),
...style,
```
and `absoluteFilledPosition` has `top: 0`, which fixed the issue in my experiments.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.1.1 => 18.1.1 
      babel-preset-expo: ^9.3.0 => 9.5.0 
      expo: ^49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.0
    Expo Workflow: bare

**Comment by dylanrandle** [comment]
When using `<Image />` from `expo-image` on web (SDK 48) I also find that the image is missing (in some scenarios, not always). I do not have the problem on ios/android.
