### ISSUE TITLE
Cannot find native module 'ExpoImage'

### ISSUE THREAD

**Issue by stesvis** [expo/expo#23639]
### Minimal reproducible example

https://snack.expo.dev/@stesvis/expoimage-error

### Summary

I am trying to use `espo-image` to render an image from URL:

```
import { Image } from "expo-image";

<Image source={"https://fastly.picsum.photos/id/5/5000/3334.jpg"} />
```

but when I run the app it fails with:

>  WARN  The native view manager required by name (ExpoImage) from NativeViewManagerAdapter isn't exported by expo-modules-core. Views of this type may not render correctly. Exported view managers: [ExpoLinearGradient, ExpoBarCodeScannerView, ExpoVideoView, ExponentGLView, ExponentCamera].
>  ERROR  Error: Cannot find native module 'ExpoImage'
>  ERROR  Error: Requiring module "node_modules\expo-image\build\index.js", which threw an exception: Error: Cannot find native module 'ExpoImage'

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9862592
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^47.0.13 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
    Expo Workflow: managed

**Comment by brentvatne** [comment]
snack uses sdk 47 right now by default. @byCedric plans to switch this to sdk 48 soon!

expo-image is supported in expo go in sdk 48+

https://snack.expo.dev/@brents/expoimage-error
