### ISSUE TITLE
build.gradle extractReactNativeAAR error with RN 0.71+

### ISSUE THREAD

**Issue by maxximee** [expo/expo#23644]
### Minimal reproducible example

not needed

### Summary

The expo-gl-cpp **build.gradle** tries to extract the react-native aar, which doesn't exist anymore:

`def extractReactNativeAAR = { buildType ->
  def suffix = buildType == 'Debug' ? '-debug' : '-release'
  def rnAARs = fileTree(RN_AAR_DIR).matching { include "**/react-native/**/*${suffix}.aar" }
  if (rnAARs.isEmpty()) {
    rnAARs = fileTree(RN_AAR_DIR).matching { include "**/react-native/**/*.aar" }
  }
  if (rnAARs.any()) {
    // node_modules/react-native has a .aar, extract headers
    if (rnAARs.size() > 1) {
      logger.error("More than one React Native AAR file has been found:")
      rnAARs.each {println(it) }
      throw new GradleException("Multiple React Native AARs found:\n${rnAARs.join("\n")}" +
          "\nRemove the old ones and try again")
    }
  }
  def rnAAR = rnAARs.singleFile
  def file = rnAAR.absoluteFile
  def packageName = file.name.tokenize('-')[0]
  copy {
    from zipTree(file)
    into "$buildDir/$file.name"
    include "jni/**/*"
  }
}`

Since react-native 0.71, that folder is empty with a readme file saying:

Starting from React Native 0.71, we're not shipping the `/android` folder inside the React Native NPM package
anymore due to sizing constraints on NPM. The Android artifacts are distributed via Maven Central.
You can read more about it in this RFC:
https://github.com/react-native-community/discussions-and-proposals/pull/508

If you're a library author and you're manipulating the React Native .aar files, to extract headers,
extract `.so` files or do anything with it, you're probably doing something wrong. React Native
0.71 ships with all the necessary logic to let you consume it transparently by just using

implementation("com.facebook.react:react-android")
// or to keep backward compatibility with older versions of React Native:
implementation("com.facebook.react:react-native:+")

Therefore we logically get error:

Where:
Build file 'C:\Users\gheysenm\IdeaProjects\klimEditor\node_modules\expo-gl-cpp\android\build.gradle' line: 154

What went wrong:
Execution failed for task ':expo-gl-cpp:extractReactNativeAARRelease'.
Expected directory 'C:\Users\blabla\node_modules\react-native/android' to contain exactly one file, however, it contains no files.

As info, versions used (current latest):

    "expo": "^49.0.0",
    "expo-gl-cpp": "^11.4.0",
    "gl-react": "^5.2.0",
    "gl-react-native": "^5.2.1",
    "patch-package": "^7.0.2",
    "react": "18.2.0",
    "react-native": "0.72.0",

### Environment

  expo-env-info 1.0.5 environment info:                                        
    System:                                                                    
      OS: Windows 10 10.0.19045                                                
    Binaries:                                                                  
      Node: 18.16.1 - C:\Program Files\nodejs\node.EXE                         
      Yarn: 1.22.19 - C:\work\jrepo-local\tools\node\node-v16.13.2-x64\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD                             
    IDEs:                                                                      
      Android Studio: AI-221.6008.13.2211.9619390

**Comment by Kudo** [comment]
hi there! expo-gl-cpp is deprecated. please just use expo-gl directly. thanks!
