### ISSUE TITLE
TextInput component in Android starts freezing after several text inputs and cleanings with back button.

### ISSUE THREAD

**Issue by stas-kravchuk** [expo/expo#2365]
Hello!

React Native component TextInput have bug with inputs in Android. After several (around 10-15, depends on device) text inputs and cleanings it starts to work more slowly until it became fully freezing. You can see this behavior only when you change 'value' property of TextInput with onChangeText. You can reproduce it with snack below.

### **Reproducible Demo**

https://snack.expo.io/@tigorn/text-input-bug

### **Steps to Reproduce**

1. Run Expo snack on your Android device
2. Write something in first Input.
3. Clean TextInput field with back button.
4. Repeat steps '3'-'4' 10-15 times.

After several repeating you will see that TextInput starts to work more slowly and after more than 15 repeating it became totally unusable.  
Also, if you try to reproduce this bug with second text input where is no setting of 'value' property everything will work correctly.

### **Expected Behavior**
TextInput works as always without any changes in performance. 

### **Actual Behavior**
TextInput became slowly until freezing.

**Comment by ide** [comment]
This sounds related to a regression in React Native (https://github.com/facebook/react-native/pull/19645#issuecomment-400507673) that will be fixed in SDK 31.
