### ISSUE TITLE
Constants.expoConfig.extra is undefined in web

### ISSUE THREAD

**Issue by OneOfOne** [expo/expo#23659]
### Minimal reproducible example

https://snack.expo.dev/@oooalpine/d2cafe

### Summary

Constants.expoConfig.extra is undefined in web

Related: https://github.com/expo/expo/issues/12430

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.4 Arch Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.1 - /bin/node
      Yarn: 1.22.19 - /bin/yarn
      npm: 9.8.0 - /bin/npm
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ^49.0.3 => 49.0.3 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: ^0.72.3 => 0.72.3 
      react-native-web: ^0.19.6 => 0.19.6 
    Expo Workflow: managed
 ```

**Comment by kirtikapadiya** [comment]
same issue found after upgrade expo SDK 48 to 49

**Comment by Kudo** [comment]
hi there! your **app.config.js** doesn't look right. you just return the object without exporting. you should export like this:
```js
module.exports = {
  something: 1,
  extra: {
    why: "is it not working",
  },
};

```

**Comment by adrianbartyczak** [comment]
I tried getting the project ID in React Native Expo, and Constants.expoConfig.extra.projectId is undefined. It looks like adding JSON ` "extra": { "eas": { "projectId": "004df6ce-f1f3-49d9-8a54-7a564e0d1cac", }, },` in app.json worked. Additionally, I was able to get the projectId with Constants.easConfig.projectId.

**Comment by danya0365** [comment]
Just run with clean cache

`npx expo start --clear`
