### ISSUE TITLE
[docs] openDatabase now returns SQLiteDatabase, which is not reflected in the docs

### ISSUE THREAD

**Issue by WillTwait** [expo/expo#23667]
### Summary

After updating to SDK 49, I'm seeing that openDatabase() now returns a SQLiteDatabase, which was previously a WebSQLiteDatabase. The [Expo docs](https://docs.expo.dev/versions/latest/sdk/sqlite/#sqliteopendatabasename-version-description-size-callback) still show the return being a WebSQLiteDatabase.

This new object seems to have different methods attached and is throwing me some errors with my current implementation. 

[Checked the source and see this](https://github.com/expo/expo/blob/0c3b792a1c3f0b2c89478601d0e525770088f3a3/packages/expo-sqlite/src/SQLite.types.ts#L138C1-L140C77), but can't find documentation anywhere for SQLiteDatabase: 
```typescript
/** @deprecated Use `SQLiteDatabase` instead. */
export interface WebSQLDatabase extends Database {
  exec(queries: Query[], readOnly: boolean, callback: SQLiteCallback): void;
``` 

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/sqlite/#sqliteopendatabasename-version-description-size-callback

**Comment by RodriCabrera** [comment]
I'm getting this error and it seems related to this issue: 

```ts
  import * as SQLite from "expo-sqlite";


  const openDatabase = () => SQLite.openDatabase("example.db");
  const db = openDatabase();

    db.transaction((tx) => {
      tx.executeSql(
        "create table if not exists items (id integer primary key not null, done int, value text);"
      );

```
The error:

```ts
Property 'transaction' does not exist on type 'SQLiteDatabase'.
```
Type of the db
```
const db: SQLite.SQLiteDatabase
```
Installed version of expo-sqlite:
```
    "expo-sqlite": "^11.3.1",
```

**Comment by leofernandesbh** [comment]
After updating to **SDK 49**, I encountered the same issue. Now, since it returns an SQLiteDatabase instead of WebSQLiteDatabase, the `transaction` method no longer exists. From what I've seen, it would be necessary to change the entire codebase to start using the `transactionAsync` method and so on.

**Comment by jmurphy4** [comment]
This has gotta be a mistake, right? Just completely change the entire package without making any sort of announcement or warning? Or even update the docs

**Comment by Kudo** [comment]
the above expo-bot comment is wrong. please upgrade expo-sqlite@11.3.2 to fix the problem.
