### ISSUE TITLE
java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1)

### ISSUE THREAD

**Issue by ldevLucasl** [expo/expo#23660]
### Minimal reproducible example

https://snack.expo.dev/@egend/flatlisterror

### Summary

I have a FlatList that is populated by a data that is a useState, and when the component mounts I fetch the data in my API using a useEffect, when the data changes from a filter and I need to call my useEffect again, I end up taking this java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 1 (child count is 1) crash.

I tried several solutions but without success, until I finally tried to change the FlatList import from react-native to gesture-handler and vuala, it worked.

im using expo@^49.0.3 e react-native@0.72.3 and Android 11.0 simulator, this error only occurs on android, on iOS with FlatList from RN everything works normal.

On the Snack error not occurred, but is like this on my code.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
      Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: ^0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.1.0
    Expo Workflow: managed

**Comment by ldevLucasl** [comment]
the error was in an animated view that I had an effect.

**Comment by gabrielfurini** [comment]
@ldevLucasl Would you mind elaborating more about how you solved the issue, please?
I'm facing the same exception here and don't know if could be related to your solution or not. TY!
