### ISSUE TITLE
[expo-image] static iOS assets images doesn't work

### ISSUE THREAD

**Issue by robert-lk** [expo/expo#23665]
### Minimal reproducible example

https://github.com/robert-lk/expo-image-static-repo

### Summary

Seems to displaying images from iOS asset bundle doesn't work.
Android drawable and React Native Image works fine.

sample usage:
```
<Image
  source={{
    uri: 'test_image',
  }}
/>
```
errors:
js: 
`{"error": "The requested URL was not found on this server.", "target": 2533}`

iOS:
```
ExpoImageTest[1543:1468021] Task <1B633644-AEAC-4BD4-8F1D-C87F86ABF39A>.<1> finished with error [-1100] Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSErrorFailingURLStringKey=file:///test_image, NSErrorFailingURLKey=file:///test_image, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1B633644-AEAC-4BD4-8F1D-C87F86ABF39A>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1B633644-AEAC-4BD4-8F1D-C87F86ABF39A>.<1>, NSUnderlyingError=0x60000093a940 {Error Domain=kCFErrorDomainCFNetwork Code=-1100 "(null)"}}
```

![Screenshot_1689935221](https://github.com/expo/expo/assets/138470351/a89b22e7-2edb-4392-873f-66e41b90cee1)
![Simulator Screenshot - iPhone 14 Pro - 2023-07-21 at 12 34 02](https://github.com/expo/expo/assets/138470351/c0ece21f-ee65-4301-9826-55902db7b9a0)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.2 => 49.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    Expo Workflow: bare

**Comment by miodrage** [comment]
+1

**Comment by isthaison** [comment]
I also got the same field as you when I build on mac, but if using windows it wont happen, I guess it was an error while exporting large size images

**Comment by SamuelBrucksch** [comment]
I have the same issue, when using expo-image on iOS:
```
 ERROR  {"error": "Die angeforderte URL wurde auf diesem Server nicht gefunden.", "target": 935}
```

Code is like this:
```
<Image source={{ uri: 'icon_name' }}>
```
If i replace exactly that with react natibe Image, it works. Also when using remote URLs instead of ImageSource, it works. So looks like the icons are wrongly looked up somehow...
