### ISSUE TITLE
expo in wsl cannot open JS debugger. ( because spawn powershell returns ENOENT )

### ISSUE THREAD

**Issue by matart15** [expo/expo#23678]
### Summary

I have Chrome and Edge installed on my windows

↓ my powershell result 
![image](https://github.com/expo/expo/assets/17027219/bc68de57-a273-4fbe-8272-a1b59204c8a9)

![image](https://github.com/expo/expo/assets/17027219/d393058d-348c-4704-9037-32d045b449ff)

But if i run `expo start` and click `› Press j │ open debugger`, I get this error
`Error: [LaunchBrowser] Unable to find a browser on the host to open the inspector. Supported browsers: Google Chrome, Microsoft Edge`

I wrote console.log on few places and found out that this line is returning `ENOENT` error
https://github.com/expo/expo/blob/main/packages/%40expo/dev-server/build/LaunchBrowserImplWindows.js#L123

![image](https://github.com/expo/expo/assets/17027219/e67d02b3-9fc4-4d5b-ba01-85a0db6a934f)

My `child_process.spawn` and `powershell.exe` seems to be working. because this line got the result before reaching `line 123`
https://github.com/expo/expo/blob/main/packages/%40expo/dev-server/build/LaunchBrowserImplWindows.js#L142

I have no idea how`powershell` works, My guess is that env we are passing is wrong.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

49

### Environment

```sh


  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed

```

### Minimal reproducible example

```

npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

cd <foldername>/app/expo
pnpm expo start

# press J
```

**Comment by matart15** [comment]
PS: I also checked my wsl have powershell.exe working

![image](https://github.com/expo/expo/assets/17027219/4572fe8c-ea2d-4eda-8e70-0da584eb987d)

**Comment by matart15** [comment]
Just in case I installed powershell 7. problem remains

![image](https://github.com/expo/expo/assets/17027219/6bca6e1e-7e26-4b6b-921c-d367516bd164)

**Comment by younes0** [comment]
can confirm the same issue with same environment

**Comment by welshy557** [comment]
I'm also having this issue

**Comment by welshy557** [comment]
I found a workaround for anyone experiencing this issue.

 Instead of trying to launch a Windows browser from WSL, you can launch a browser directly within WSL.

First, install Google Chrome in your WSL distro.
You should be able to enter google-chrome and get a Chrome browser running directly from WSL.

![image](https://github.com/expo/expo/assets/98999473/763eea14-22db-4881-9836-84673724dddb)

Next go to node_modules/@expo/dev-server/build/LaunchBrowser.js

On line 72, remove IS_WSL from the if statement.

![image](https://github.com/expo/expo/assets/98999473/4a0749e7-2828-4ed0-96ac-83f3c558e3be)


This causes the proceeding if statement to run, which checks for Linux OS, thus opening the browser in Linux.

**Comment by matart15** [comment]
@welshy557 thank you for workaround. 
I gave up on WSL and installed ubuntu as dual boot.
my startup time and few apps UX sucks. But At least my expo development is less painful.
:)

**Comment by younes0** [comment]
@matart15 to me, there are only 2 things that are "painful" running Expo (Metro) under WSL
- LAN port forwarding which is actually easily solved, [see my Gist](https://gist.github.com/younes0/de8ff1386a5868e77e9907728f93645e)
- This issue

**Comment by younes0** [comment]
@Kudo FYI Windows users are nowadays mostly under WSL and aren't able to use the JS debugger

**Comment by welshy557** [comment]
> @welshy557 thank you for workaround. I gave up on WSL and installed ubuntu as dual boot. my startup time and few apps UX sucks. But At least my expo development is less painful. :)

I also decided to duel boot recently. This is one of many issues I've had to deal with and it was just a waste of time.

**Comment by ShaneKeney** [comment]
> I found a workaround for anyone experiencing this issue.
> 
> Instead of trying to launch a Windows browser from WSL, you can launch a browser directly within WSL.
> 
> First, install Google Chrome in your WSL distro. You should be able to enter google-chrome and get a Chrome browser running directly from WSL.
> 
> ![image](https://private-user-images.githubusercontent.com/98999473/264367244-763eea14-22db-4881-9836-84673724dddb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU0MzYsIm5iZiI6MTcwNTU4NTEzNiwicGF0aCI6Ii85ODk5OTQ3My8yNjQzNjcyNDQtNzYzZWVhMTQtMjJkYi00ODgxLTk4MzYtODQ2NzM3MjRkZGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzMzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZGEwYjkyOWYzZTg2ODgyNTlmNTI4NDYzYTI1ZjA2OTFmMTUyZmMwNjJjOTQ1MGM4YWNmMmRlM2UzMDRmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C2t12hprZgBETCPYjkZ178SAWwCc4yb4TVrN_oOV6vo)
> 
> Next go to node_modules/@expo/dev-server/build/LaunchBrowser.js
> 
> On line 72, remove IS_WSL from the if statement.
> 
> ![image](https://private-user-images.githubusercontent.com/98999473/264367872-4a0749e7-2828-4ed0-96ac-83f3c558e3be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODU0MzYsIm5iZiI6MTcwNTU4NTEzNiwicGF0aCI6Ii85ODk5OTQ3My8yNjQzNjc4NzItNGEwNzQ5ZTctMjgyOC00ZWQwLTk2YWMtODNmM2M1NThlM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzMzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYmU4NjQ3MTljMTk4ODBjOTMxZjhkMDQ2ZDlkMjFjZTg4ZTI0MjQxODk1NGExZTE0ZDVjZjEzMDU4MmUzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1rjDt8b2O9yMEBFtd_jCAGvzRGm35UT5W9sqDttst88)
> 
> This causes the proceeding if statement to run, which checks for Linux OS, thus opening the browser in Linux.

This was the exact issue for me as well.  Removing `IS_WSL` fixed the issue.

**Comment by ShaneKeney** [comment]
This seems to be an issue again and the above patch doesn't seem to work as `@expo/dev-server` is no longer in the same location.  Anyone know where this is being run now in `@expo`?

**Comment by Valetek** [comment]
@TzviCons It's seems the folder `/inspector` doesn't exist

**Comment by TzviCons** [comment]
@Valetek On version 50.0.6 and 50.0/7 the file is at that location. I added version number and a github link to my previous post.

**Comment by Valetek** [comment]
Do you also know the location of this file for version 49 ?

**Comment by TzviCons** [comment]
@Valetek I haven't looked for it there but you should be able to use your code editor to globally search or IS_WSL.

Or on the command prompt `grep -nr IS_WSL node_modules/`.

**Comment by Valetek** [comment]
usefull command, okay didn't follow that the first command on this post was about the new location for version 50+, thanks for your answer !

**Comment by TzviCons** [comment]
@Valetek I looks like this post did start with version 49 as you had assumed. I had been responding to a comment about the file being moved in subsequent versions. Hopefully the grep command will be helpful to others as `expo` continues to evolve.

Good luck!

**Comment by lorenzo-dallamuta** [comment]
I'm not sure if this is being worked on, I did some logging and I figured I could at least note down what I found.

I forced `isSupportedBrowser` (currently located in `node_modules/@expo/cli/build/src/start/server/middleware/inspector/LaunchBrowserImplWindows.js`) to execute the powershell `Get-Package` command without the `env` option.

This results in a positive match for the browsers I have installed Windows side. (On my system, `env` would be set to `{ PSModulePath: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules' }`).

Also, when `openWithSystemRootEnvironment` (located in the same module) tries to access the system root environment variable before invoking `open` both `process.env.SYSTEMROOT` and its fallback `process.env.SystemRoot` are undefined.

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 22.2.0 - /usr/bin/node
      npm: 10.7.0 - /usr/bin/npm
    npmPackages:
      expo: ~51.0.6 => 51.0.6
      expo-router: ~3.5.12 => 3.5.12
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    Expo Workflow: managed
```

**Comment by AnkushSarkar10** [comment]
PLS FIX THIS SOMEONE I DONT WANT TO START DUAL BOOTING 😭

**Comment by keith-kurak** [comment]
Hey all- with #32266, with the right WSL settings, debugging in WSL should work out of the box in the upcoming SDK 52, using React Native DevTools.

The [WSL guide](https://expo.fyi/wsl) has been updated with these settings. WSL setup has been streamlined significantly with some of the newer network settings MS has added, so I definitely recommend checking them out if its been a while since you got Expo running in WSL.

This guide also includes a reference to the workaround documented in this thread, as well as how to enable React Native DevTools in SDK 51, which wasn't quite ready to be the default then, but still should work for a lot of debugging purposes.

**Comment by pinguluk** [comment]
> Hey all- with [#32266](https://github.com/expo/expo/pull/32266), with the right WSL settings, debugging in WSL should work out of the box in the upcoming SDK 52, using React Native DevTools.
> 
> The [WSL guide](https://expo.fyi/wsl) has been updated with these settings. WSL setup has been streamlined significantly with some of the newer network settings MS has added, so I definitely recommend checking them out if its been a while since you got Expo running in WSL.
> 
> This guide also includes a reference to the workaround documented in this thread, as well as how to enable React Native DevTools in SDK 51, which wasn't quite ready to be the default then, but still should work for a lot of debugging purposes.

while it opens the Developer Tools from Linux, the network requests are not present in Network tab
