### ISSUE TITLE
FileSystem.downloadAsync timeout

### ISSUE THREAD

**Issue by nebmesemaou** [expo/expo#2368]
downloadAsync method timeout

source URL which geting error
[http://h.tr.mediaplayer.allocine.fr/tr/medias/nmedia/90/18/07/18/12/19549932_m_013.mp4](url) (9.6MB)

working URL's
[http://h.tr.mediaplayer.allocine.fr/tr/medias/nmedia/90/18/09/04/09/19550289_m_013.mp4](url) (16.8 MB)
[https://www.climate.gov/sites/default/files/ClimDiv_12MonthSeries_wLegend_720p.mp4](url) (15 MB)

it's a little bit take a while loading

i try 
`var downloadInfo = await FileSystem.downloadAsync(url, targetUrl);`

also try
`var downloadResumable = FileSystem.createDownloadResumable(url, targetUrl);`
 `var downloadInfo = await downloadResumable.downloadAsync();`

i always get this :

[Unhandled promise rejection: Error: timeout]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:121:42 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:78:57 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:398:4 in __invokeCallback
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:137:28 in <unknown>
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:6 in __guardSafe
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:136:17 in invokeCallbackAndReturnFlushedQueue

**Comment by tcdavis** [comment]
I'm not able to reproduce on android or ios: https://snack.expo.io/@thetc/download-async
Can you share a snack that demonstrates the issue?

**Comment by nebmesemaou** [comment]
nothing changed but it works now anyway thx
