### ISSUE TITLE
React-native-reanimated flickers after expo update to sdk 49 inside SafeAreaView

### ISSUE THREAD

**Issue by NiccoloCase** [expo/expo#23681]
### Minimal reproducible example

https://github.com/NiccoloCase/reanimated-bug-test

### Summary

I have just updated my React Native app to the latest version of Expo SDK. The app uses native code and dev clients. As part of the update process, I deleted the iOS and android folders to ensure a clean installation. During the Expo update, react-native-reanimated was updated from version 2.14.4 to version 3.3.0.

However, after the update, I'm experiencing various issues with animations. Specifically, the animations lag significantly only the first time they are executed. Subsequent executions seem to work fine.

I have uploaded videos to show the problem.

https://res.cloudinary.com/dynsmaeo3/video/upload/ac_none,e_volume:-100/v1689971871/SPOTLIVE-STATIC/2_-_SD_480p_mjausq.mov
https://res.cloudinary.com/dynsmaeo3/video/upload/ac_none/v1689971822/SPOTLIVE-STATIC/stackoveflow_-_SD_480p_fr1zlg.mov

After several tests I managed to find that if I don't use the react-native SafeAreaView component the problem goes away.
I created a blank app with a fresh install of expo to make the problem replicable. 

How can I fix this bug?

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/niccolocaselli/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by lukmccall** [comment]
Connected with https://github.com/software-mansion/react-native-reanimated/issues/4798.
