### ISSUE TITLE
Minimum deployment target issue while prebuilding.

### ISSUE THREAD

**Issue by AJTJ** [expo/expo#23684]
### Minimal reproducible example

https://expo.dev/accounts/aaronjanke/projects/free_app/builds/b57ea3c8-1374-4027-89b2-6fc2665c74ee

### Summary

I'm attempting to get 

while trying to run `npx expo run:ios`

I get this error:
```
   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ compiling for iOS 12.4, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.0: /Users/ajtj/Library/Developer/Xcode/DerivedData/freeapp-atsdcihlpdelxfgorfpcgbtpqqdd/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
   9 | import EXAV
  10 | import EXConstants
  11 | import ExpoHead
```

Side question: why does my project say that my `Expo Workflow` is bare, when I'm still in managed?

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.24.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2023.07.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: bare

**Comment by johnmccants002** [comment]
Anyone got a good answer for this error? I'm currently getting a similar error message after running npx expo run:ios

> 1 | import ExpoModulesCore
    |        ^ compiling for iOS 13.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.4:
