### ISSUE TITLE
[expo-print][ios] Expo SDK 49: Background CSS property not applied when printing HTML

### ISSUE THREAD

**Issue by michaelheckmann** [expo/expo#23686]
### Minimal reproducible example

https://github.com/michaelheckmann/expo-49-print-css-ios-issue

### Summary

With the new Expo SDK 49, I noticed that on iOS, the background property (and related properties like background-image) are not applied. It worked with SDK 48 and I could not reproduce the issue on Android with the latest SDK.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.6.0 - ~/.nvm/versions/node/v19.6.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v19.6.0/bin/yarn
      npm: 9.4.0 - ~/.nvm/versions/node/v19.6.0/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.4 => 49.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.16.0
      expo-cli: 6.3.9
    Expo Workflow: managed

**Comment by gustavosorati** [comment]
Hi, try this on ios, it works on your example
```css
<style>
      * { print-color-adjust:exact !important; }
</style>
```

**Comment by michaelheckmann** [comment]
Nice, worked perfectly. Thanks so much @gustavosorati !

**Comment by awp-joe** [comment]
Thank you @gustavosorati

**Comment by ViniTeider** [comment]
that saved my life, thanks @gustavosorati

**Comment by harshithvemulas** [comment]
It worked, searching for this from 5 days. Thank you so much

**Comment by vfaith37** [comment]
I've noticed background color is not working on "expo": "~50.0.8", even after the suggestion above

**Comment by mmaldonado-zennovia** [comment]
> Hi, try this on ios, it works on your example
> 
> ```css
> <style>
>       * { print-color-adjust:exact !important; }
> </style>
> ```



> Hi, try this on ios, it works on your example
> 
> ```css
> <style>
>       * { print-color-adjust:exact !important; }
> </style>
> ```

Incredible. I've been struggling with this error for days and the solution was so simple.

**Comment by tunayangir** [comment]
I have been trying for a week. Thanks for the solution.

**Comment by omaryasirm** [comment]
Thank you @gustavosorati

**Comment by leGenti** [comment]
> Hi, try this on ios, it works on your example
> 
> <style>
>       * { print-color-adjust:exact !important; }
> </style>

@gustavosorati, you're a hero!

**Comment by mohamadm890** [comment]
Thanks Guys!

**Comment by Jacfger** [comment]
@gustavosorati, you're a life safer!!!
