### ISSUE TITLE
Question - Roadmap for Audio

### ISSUE THREAD

**Issue by ecerroni** [expo/expo#237]
In the docs https://docs.expo.io/versions/v17.0.0/sdk/audio.html

`Note that Expo does not yet support backgrounding, so audio is not available to play in the background of your experience. Audio also automatically stops if headphones / bluetooth audio devices are disconnected.`

However I see `playsInSilentLockedModeIOS` as an option for iOS, though not Android.

Is this on the roadmap? If yes, is there any ETA?

Thanks

**Comment by gkufera** [comment]
Hi @ecerroni--

Yes, playing audio on the lock screen in Android, and in the background in general, is on the roadmap, but we do not currently have an ETA.

See here to upvote the Expo feature request:
https://expo.canny.io/feature-requests/p/audio-playback-in-background

Thanks!

Greg
