### ISSUE TITLE
expo-doctor vs expo-doctor@latest. Different result

### ISSUE THREAD

**Issue by TimurKazakov** [expo/expo#23707]
### Summary

![image](https://github.com/expo/expo/assets/32258765/8e957dc7-b5d5-4cce-abe2-7ecafe754ec4)
Different result on same project.
When i try to build - build has failed.
![image](https://github.com/expo/expo/assets/32258765/078c4d72-fe2f-488f-8362-f45f459a2423)
![image](https://github.com/expo/expo/assets/32258765/b9444341-eb64-438a-ac2d-e59ecb90f404)

### What platform(s) does this occur on?

Android

### SDK Version

49

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ^49.0.5 => 49.0.5
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    Expo Workflow: managed

### Minimal reproducible example

{
  "name": "vashinvestor",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "npx expo start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@alessiocancian/react-native-actionsheet": "^3.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-community/slider": "^4.2.1",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.0",
    "@react-navigation/stack": "^6.0.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "date-fns": "^2.23.0",
    "expo": "^49.0.5",
    "expo-build-properties": "~0.8.3",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.6",
    "expo-font": "~11.4.0",
    "expo-linear-gradient": "~12.3.0",
    "expo-local-authentication": "~13.4.1",
    "expo-location": "~16.1.0",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "geolib": "^3.3.1",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "5.1.6",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-document-picker": "^8.0.0",
    "react-native-geolocation-service": "^5.3.0-beta.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-image-picker": "^4.0.6",
    "react-native-image-resizer": "^1.4.5",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-keychain": "^8.0.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-maps": "1.7.1",
    "react-native-modal": "^13.0.0",
    "react-native-modal-selector": "file:./custom_node_modules/react-native-modal-selector",
    "react-native-reanimated": "~3.3.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swiper": "^1.6.0",
    "react-native-toast-notifications": "^3.3.1",
    "react-native-walkthrough-tooltip": "^1.5.0",
    "react-native-webview": "13.2.2",
    "react-native-yamap": "4.0.7",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-saga": "^1.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^29.5.0",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "main": "index.js",
}

**Comment by TimurKazakov** [comment]
![image](https://github.com/expo/expo/assets/32258765/1a0b8dc1-ff87-4df8-b666-b91a0c048b2c)
on --check 
Dependencies are up to date

**Comment by brentvatne** [comment]
`npx` doesn't always use the latest package version unfortunately. we recommend using `@latest` to ensure that you have the latest version of expo-doctor
