### ISSUE TITLE
[expo-dev-launcher][iOS] Dev launcher breaks with reanimated 3.4.0

### ISSUE THREAD

**Issue by hirbod** [expo/expo#23719]
### Minimal reproducible example

https://snack.expo.dev/@hirbod/laughing-stroopwafels

### Summary

expo-dev-client / expo-dev-launcher is not compatible with the new react-native-reanimated version 3.4.0

Failing here:
https://github.com/expo/expo/blob/342980234003cca50904000834af098be907407d/packages/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm#L60-L64

It's trying to use a class, REAInitializer, which doesn't exist in the reanimated namespace (anymore)

![9fEcleXO](https://github.com/expo/expo/assets/504909/5d4d23c7-0149-4b90-84c5-db57cb8f9af3)

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 3.5.0 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.2
    Expo Workflow: bare
```

**Comment by hirbod** [comment]
Dear @expo-bot - yes its working :)

**Comment by robertherber** [comment]
Seems like nailing the expo-dev-client to 2.4.7 fixes this for dev clients, but for production builds it seems like a expo-dev-launcher needs to be similarly upgraded to 2.4.9 for production builds. A bit confused about why it's included in the production build though.. :)

**Comment by hirbod** [comment]
dev-launcher / dev-client is usually stripped from production, only a couple header files should remain. We have no issues in production (PS: we only have expo-dev-client installed, not expo-dev-launcher)

```
✗ yarn why expo-dev-launcher
├─ expo-dev-client@npm:2.4.7
│  └─ expo-dev-launcher@npm:2.4.9 (via npm:2.4.9)
│
└─ expo-dev-client@npm:2.4.7 [94b1d]
   └─ expo-dev-launcher@npm:2.4.9 [6e4cf] (via npm:2.4.9 [6e4cf])
```

**Comment by dakshshah96** [comment]
@lukmccall / @hirbod I believe this issue should be re-opened?

iOS builds still failed with this error on the latest versions `expo-dev-client: 2.4.8` and `react-native-reanimated: 3.4.2`:

```
❌  (node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm:63:15)

  61 | {
  62 | #if __has_include(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
> 63 |   reanimated::REAInitializer(bridge);
     |               ^ no type named 'REAInitializer' in namespace 'reanimated'
  64 | #endif // __has_inclide(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
  65 | 
  66 |   return [super jsExecutorFactoryForBridge:bridge];
```

**Comment by abretonc7s** [comment]
Same issue here with reanimated 3.4.2

**Comment by izakfilmalter** [comment]
Same issue.

**Comment by darwinshameran** [comment]
Same.

**Comment by hirbod** [comment]
I believe this was fixed in 3.5.0

**Comment by hlspablo** [comment]
Guys, Always use npx expo install react-native-reanimated, it will ensure that the correct version is installed, at the current momento on SDK 49 the right version is 3.3.0

**Comment by ijasxyz** [comment]
`https://github.com/expo/expo/issues/23719#issuecomment-1696853574` 

If anyone needs to use this fix without updating, make the changes in the file and use `patch-update` to create a patch.
