### ISSUE TITLE
expo-secure-store Cancelled the development build  

### ISSUE THREAD

**Issue by TankPOOJA** [expo/expo#23717]
### Summary

when i created the build i got the error==============

Using Expo modules

[Expo] Enabling modular headers for pod ExpoModulesCore

Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/expo/.nvm/versions/node/v16.18.1/bin/node

[stderr] 
error Failed to build the app: No package name found. Found errors in /Users/expo/workingdir/build/node_modules/expo-secure-store/android/src/main/AndroidManifest.xml.

[!] Invalid `Podfile` file: unexpected token at 'info Run CLI with --verbose flag for more details.

'.

 #  from /Users/expo/workingdir/build/ios/Podfile:14

 #  -------------------------------------------

 #    use_expo_modules!

 >    config = use_native_modules!

 #  

 #  -------------------------------------------

Error: Unknown error. See logs for more information.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo-secure-store latest version

### Environment

npx: installed 2 in 5.42s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2023.02.20.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 23, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.15.0
      expo-cli: 6.3.7
    Expo Workflow: bare

### Reproducible demo

import * as SecureStore from 'expo-secure-store';

async function save(key, value) {
  await SecureStore.setItemAsync(key, value);
}

async function getValueFor(key) {
  let result = await SecureStore.getItemAsync(key);
  if (result) {
    alert("🔐 Here's your value 🔐 \n" + result);
  } else {
    alert('No values stored under that key.');
  }
}

### Stacktrace (if a crash is involved)

<img width="997" alt="Screenshot 2023-07-25 at 5 16 31 PM" src="https://github.com/expo/expo/assets/40266663/318f9942-5538-42e1-bde2-709527603002">

**Comment by feifanz** [comment]
Got the same issue.

**Comment by TankPOOJA** [comment]
any solution for this issue ?

**Comment by jferrettiboke** [comment]
The same here.

**Comment by jferrettiboke** [comment]
Read this for more info. It worked for me. https://github.com/expo/expo/issues/23409#issuecomment-1627732575

**Comment by jferrettiboke** [comment]
@TankPOOJA Could you provide more info?

1. How does your `package.json` look like?
2. What do you get if you run Expo doctor?

**Comment by TankPOOJA** [comment]
@jferrettiboke this is my package.json 
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
  },
  "dependencies": {
    "@expo-google-fonts/courier-prime": "^0.2.0",
    "@expo-google-fonts/nunito": "^0.2.0",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-native-community/netinfo": "9.3.5",
    "@react-native-community/slider": "4.2.4",
    "@react-native-picker/picker": "2.4.8",
    "@react-navigation/bottom-tabs": "^6.0.0-next.22",
    "@react-navigation/drawer": "^6.0.0-next.21",
    "@react-navigation/elements": "^1.0.0-next.0",
    "@react-navigation/native": "^6.0.0-next.17",
    "@react-navigation/native-stack": "^6.0.0-next.11",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "@sentry/react-native": "4.9.0",
    "deprecated-react-native-prop-types": "^2.3.0",
    "expo": "^47.0.0",
    "expo-app-loading": "~2.1.0",
    "expo-application": "~5.0.1",
    "expo-asset": "~8.7.0",
    "expo-barcode-scanner": "~12.1.0",
    "expo-checkbox": "~2.2.2",
    "expo-clipboard": "~4.0.1",
    "expo-constants": "~14.0.2",
    "expo-device": "~5.0.0",
    "expo-font": "~11.0.1",
    "expo-image-picker": "~14.0.2",
    "expo-linear-gradient": "~12.0.1",
    "expo-linking": "^3.3.1",
    "expo-local-authentication": "~13.0.2",
    "expo-localization": "~14.0.0",
    "expo-notifications": "^0.17.0",
    "expo-splash-screen": "^0.17.5",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.15.6",
    "expo-web-browser": "~12.0.0",
    "i18n-js": "^4.2.0",
    "lodash": "^4.17.21",
    "lottie-ios": "^3.4.0",
    "lottie-react-native": "^5.1.4",
    "moment": "^2.29.1",
    "native-base": "^3.4.25",
    "pusher-js": "^8.0.2",
    "radio-buttons-react-native": "^1.0.4",
    "react": "18.1.0",
    "react-content-loader": "^6.2.1",
    "react-dom": "18.1.0",
    "react-infinite-scroll-component": "^6.1.0",
    "react-native": "0.70.8",
    "react-native-animatable": "^1.3.3",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-btr": "^2.2.0",
    "react-native-chart-kit": "^6.12.0",
    "react-native-common-date-picker": "^2.3.4",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modal-datetime-picker": "^13.0.0",
    "react-native-otp-textinput": "^0.0.9",
    "react-native-picker-select": "^8.0.4",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-pressable-scale": "^1.0.6",
    "react-native-progress": "^5.0.0",
    "react-native-pure-chart": "0.0.24",
    "react-native-qrcode-svg": "^6.1.2",
    "react-native-reanimated": "^2.12.0",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-responsive-linechart": "^5.7.1",
    "react-native-root-siblings": "^4.1.1",
    "react-native-root-toast": "^3.4.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-sms-verifycode": "^2.4.3",
    "react-native-static-safe-area-insets": "^2.2.0",
    "react-native-svg": "^13.5.0",
    "react-native-wagmi-charts": "^2.3.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.1",
    "react-redux": "^8.0",
    "redux": "^4.1.0",
    "sentry-expo": "~6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~18.0.27",
    "@types/react-dom": "18.2.1",
    "@types/react-native": "^0.64.32",
    "typescript": "^4.9.4"
  },
  "private": true
}

**Comment by jferrettiboke** [comment]
@TankPOOJA What do you get if you run `npx expo-doctor`?
