### ISSUE TITLE
Expo 49 - Android Gradle Release failure - app:lintVitalAnalyzeRelease

### ISSUE THREAD

**Issue by emilyseibert** [expo/expo#23720]
### Summary

`eas build --local --non-interactive --json --clear-cache --platform android --profile release --output test.zip`

Fails with the following error:
![image](https://github.com/expo/expo/assets/16102717/bfa97034-ecd3-4720-8078-d545b6171ee6)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@config-plugins/detox": "^5.0.1",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "expo": "^49.0.0",
    "expo-application": "~5.3.0",
    "expo-build-properties": "~0.8.3",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "intl": "^1.2.5",
    "lottie-react-native": "5.1.6",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-inappbrowser-reborn": "3.7.0",
    "react-native-navigation-bar-color": "2.0.2",
    "react-native-safe-area-context": "4.6.3",
    "react-native-svg": "13.9.0",
    "expo-gradle-ext-vars": "^0.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0, 34.0.0
        System Images: android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a
        Android NDK: 25.2.9519653
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: managed

### Reproducible demo

[repro-android-release.zip](https://github.com/expo/expo/files/12166304/repro-android-release.3.zip)

**Comment by Kudo** [comment]
hi there! you are using `@config-plugins/detox` without `detox` in dependencies.
1. if you don't want to use detox: you should remove `@config-plugins/detox` from **app.config.js** and **package.json**.
2. otherwise, if you want to use detox: please update dependencies by `yarn add detox @config-plugins/detox`

**Comment by rranjan14** [comment]
Hi @Kudo I am still getting the same issue with expo 49.0.6. I am not using detox.

**Comment by Kudo** [comment]
@rranjan14 the error may vary case by case. could you share a repro?

**Comment by rranjan14** [comment]
@Kudo upgrading metro worked for me.
