### ISSUE TITLE
Expo-image doesn't play an animation of a .apng file on Android

### ISSUE THREAD

**Issue by Ionnia** [expo/expo#23753]
### Minimal reproducible example

https://github.com/Ionnia/expo-image-apng-bug

### Summary

expo-image doesn't play an animation of a .apng file on android (physical device and emulator)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 9.5.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.5 => 49.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.10.1
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by brentvatne** [comment]
which platform are you encountering this issue on?

**Comment by Ionnia** [comment]
> which platform are you encountering this issue on?

On android

**Comment by lukmccall** [comment]
Hi @Ionnia, I wasn't able to reproduce it.

https://github.com/expo/expo/assets/9578601/4f47e03a-736d-4e74-af75-33fd5503e87b

Could you provide more information about devices you used to test it?

**Comment by Ionnia** [comment]
Yeah, sure. 
I tried it in emulators with API Level 33 and API Level 22. And I tried it on a physical device Xioami Mi 9T Pro with android version 10 QKQ1.190825.002.
<img width="282" alt="image" src="https://github.com/expo/expo/assets/10923019/64613d00-88d1-4dde-bb36-846b55924925">
And I even tried another laptop to run Expo Go. Without any success.

**Comment by Ionnia** [comment]
The animation is playing okay in development build though.

**Comment by lukmccall** [comment]
I ran your example on a different set of devices in release mode, and everything worked as expected. The `apng` files might take a little bit longer to load, but other than that, everything was fine. I'll close that issue for now because you're using an older version of `expo-image`. Feel free to open another issue if you encounter the same problem with a newer version of our package.

**Comment by ludovicthomas** [comment]
> The animation is playing okay in development build though.

Did you find the issue @Ionnia?
Because we have the same issue and it's only visible on the release build, the debug build are ok.

**Comment by j6u** [comment]
Running into similar issue. @Ionnia did you resolve this issue?
