### ISSUE TITLE
Error: build command failed with EAS Build

### ISSUE THREAD

**Issue by IntiRraptor** [expo/expo#23766]
### Minimal reproducible example

 eas build --platform android --profile production Loaded "env" configuration for the "production" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/variables/ ✔ Using remote Android credentials (Expo server) ✔ Using Keystore from configuration: Build Credentials qnbsIN1vmj (default)  Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive ✔ Compressed project files 1s (35.8 MB) ✔ Uploaded to EAS 13s Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.     Error: build command failed.

### Summary

---
name: Bug report
about: Report a bug in the Expo platform

---

**Summary:**

I'm having trouble building my application using `eas-cli`. Every time I attempt to run `eas build --platform android --profile production`, I receive the error `Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.`

**Environment:**

- `eas-cli` version: 3.17.1
- Node version: 16.20.0
- Npm version: 8.19.4
- OS: Windows 11
- Expo SDK version: 49.0.0

**Steps to Reproduce:**

1. Run `eas build --platform android --profile production`
2. The above error message appears

**Expected Behavior:**

I expect the build to start and eventually complete without error.

**Actual Behavior:**

The build fails immediately with the error message `Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.`

**Additional Context:**

This error started appearing suddenly. I successfully built my application just before this started happening, and I have not made any significant changes to my environment or project configuration since then.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9862592
    npmPackages:
      expo: ^49.0.0 => 49.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: bare

**Comment by samuelzxu** [comment]
Encountering the same thing on OSX building for ios with `eas build -p ios`. I'm getting the message 
`Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.`.

**Comment by samuelzxu** [comment]
@IntiRraptor looks like Expo is experiencing a major outage.
https://status.expo.dev/
