### ISSUE TITLE
no ios folder when running expo prebuild command 

### ISSUE THREAD

**Issue by FouadMagdy01** [expo/expo#23762]
### Minimal reproducible example

When i run expo prebuild command only the android folder is generated and there is no ios folder

### Summary

The prebuild command should produce the native android and ios folder but what i get is only the android native folder 

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.2
      expo: ~49.0.5 => 49.0.5
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: bare

**Comment by yutankaifa** [comment]
Generating iOS folders requires running on macOS or Linux，You can run "npx expo prebuild -- platform ios" to get this error.
