### ISSUE TITLE
[docs] Incompatibility Issue: React Native Library "react-native-get-random-values"

### ISSUE THREAD

**Issue by wesvh** [expo/expo#23764]
### Summary

Description:
The "react-native-get-random-values" library has been successfully adapted for SDK version 48 and is currently set to "~1.9.0". However, there is a compatibility problem as Expo is still requesting version "~1.8.0" of the same library. This inconsistency is causing an error when running expo-doctor.

Steps to Reproduce:

Install or update Expo to SDK version 48.
Add the "react-native-get-random-values" library to the project.
Run expo-doctor.
Expected Behavior:
expo-doctor should run without any errors, as the "react-native-get-random-values" library has been adapted to SDK 48, and version "~1.9.0" is specified.

Current Behavior:
expo-doctor throws an error due to the request for "react-native-get-random-values" version "~1.8.0", which has not been adapted for SDK 48.

Additional Information:
As of the current Expo SDK version 48, the library "react-native-get-random-values" at version "~1.9.0" is confirmed to be compatible. However, Expo's dependency resolution is still seeking "~1.8.0", leading to the mentioned issue. This issue should be addressed to ensure smooth compatibility and usage for projects relying on SDK 48.

Please note that the latest version of the library compatible with SDK 48 is "~1.9.0", and any changes or updates to Expo's dependency resolution should consider this version for a seamless development experience.

### Link to the related docs page

https://github.com/LinusU/react-native-get-random-values/releases/tag/v1.9.0

**Comment by brentvatne** [comment]
thanks! i wasn't aware that this library had released a new version for sdk 48. i have updated our validations to point to ~1.9.0
