### ISSUE TITLE
The "Run fastlane" step failed with an unknown error

### ISSUE THREAD

**Issue by emmanuelOpara777** [expo/expo#23777]
### Minimal reproducible example

❌  (node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2289:9)

### Summary

I get this error message at the point of building my expo project with this command:

Command 
eas build --platform ios

Error
❌  (node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2289:9)

And after I got this error, I went to the file to change | -> || but when I ran the build command again, it stills return same error and this | -> ||
❌  (node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2289:9)

![Screen Shot 2023-07-31 at 01 08 03](https://github.com/expo/expo/assets/32057585/e4e6949a-e779-49fe-b9e6-e391318df73c)

Please anyone with an idea of what I need to do should help me.
Thank you in advance

### Environment

"expo": "^44.0.0",
"react-native": "0.64.3",
"react": "17.0.1",

**Comment by Kudo** [comment]
hi there! that error is a known issue for xcode 14.3. unfortunately, [the fix](https://github.com/facebook/react-native/pull/36759) does not backport to react-native 0.64. please downgrade your xcode or use [`macos-monterey-12.6-xcode-14.2` eas image](https://docs.expo.dev/build-reference/infrastructure/#macos-monterey-126-xcode-142-latest-for-intel-builders) instead.
