### ISSUE TITLE
AuthSession doesn't redirect back to app on Android standalone APK.

### ISSUE THREAD

**Issue by smartsoul** [expo/expo#2378]
My code works on expo client, but it doesn't work on android standalone APK. (I didn't test it on ios ipa testflight).
I log the redirect_url and apk shows same url with expo client's such as 'https://auth.expo.io/@cus******/custo******'

I read the expo document https://docs.expo.io/versions/latest/sdk/auth-session#usage-in-standalone-apps and set a scheme to a string 'demo'. Is it right? I don't find other document about the scheme.

### Environment

Device android version: 7.1.1
react-native: 0.55.4
expo: 30.0.1
expo sdkversion: 30.0.0
expo client: 2.8.0

### Steps to Reproduce

main code: 

```
const redirectURI = AuthSession.getRedirectUrl();

const AUTH_URL = `${serviceURI.OAUTH_SERVICE}/auth?response_type=code
&client_id=${CLIENT_ID}
&redirect_uri=${encodeURIComponent(redirectURI)}
&scope=${SCOPE}&state=${STATE}`;

const result = await AuthSession.startAsync({ authUrl: AUTH_URL });
```

### Expected Behavior
Redirect back to app and login successfully
### Actual Behavior
Stop to 'Return to the app' page. Nothing happened when press the button.
![image](https://user-images.githubusercontent.com/13044219/46643656-9091f500-cbaf-11e8-8281-6829ef73f884.png)

**Comment by smartsoul** [comment]
Resoved by 
`
const result = await AuthSession.startAsync({ authUrl: AUTH_URL, returnUrl: 'scheme://' });
`

**Comment by msevestre** [comment]
@smartsoul How did you figure that out? shouldn't that be in the docs at least?

**Comment by msevestre** [comment]
@smartsoul What about that here
>In order to be able to deep link back into your app, you will need to set a scheme in your project app.json

Did you define a schema in your app?

**Comment by brian-lesschwab** [comment]
I resolved it with 
`const result = await AuthSession.startAsync({ authUrl: AUTH_URL })`
and `"scheme: "exp"` in my app.json
and adding `exp://exp.host/@<USERNAME>/vbay_native` to my allowed redirect urls of my Oauth provider

**Comment by mcshiz** [comment]
I resolved it by adding 
`const result = await AuthSession.startAsync({ authUrl: authUrl });`
and `"scheme": "exp"` to app.json
and adding `exp://exp.host/@<USERNAME>vbay_native` to my allowed redirect urls in my oAuth provider

**Comment by JaydenR** [comment]
@mcshiz Does that solution work for you when publishing on expo? 
This issue has been occurring for me since updating to expo v.32 on the Android emulator that solution didn't work for me.
