### ISSUE TITLE
[SDK 49 - Linux] Debugging connection was closed. Reason: WebSocket disconnected

### ISSUE THREAD

**Issue by mgscreativa** [expo/expo#23787]
### Summary

I’m using Linux Mint 21.2 and having a hard time to get hermes debugging working. My workspace is as follows:

    Linux mint 21.2
    WebStorm 2023.1.4
    Using expo sdk v49 (49.0.6)
    Expo Go on iPhone 12 Pro Max and iOS 16.5.1

For testing hermes debugging I have created a complete new and clean app with `npx create-expo-app@latest --template tabs`, I have also uploaded the app to GitHub here [GitHub - mgscreativa/heremes-test-expo-go: heremes-test-expo-go 1](https://github.com/mgscreativa/heremes-test-expo-go)

Accessing chrome://inspect I can see the hermes instance running but I can’t see anything to debug in there. Have attached a video showing the process I’m following

![Peek 2023-07-31 17-23](https://github.com/expo/expo/assets/1286632/37d6de0d-294b-4201-9bf1-bb7f0892b60d)

Pressing j after project starts it's a no joy too...
![imagen](https://github.com/expo/expo/assets/1286632/2999494f-e145-42e4-81b7-90f69d263fed)

What Am I doing wrong? Should I configure anything else?

PS: Flipper 0.209.0 not even shows my iPhone at all

### What platform(s) does this occur on?

iOS

### SDK Version

49

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.2 (Victoria)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 20230430.125247.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86_64 Atom, android-32 | Google APIs Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.7
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/mgscreativa/heremes-test-expo-go

**Comment by Kudo** [comment]
hi there! sorry that i don't have linux lint but i tested your repro from ubuntu 22.04 and it works for me. i believe that would be some environmental or network problems.

one way to troubleshoot the problem is that when opening the chrome devtools (when you seeing the "Debugging connection was closed" prompt), you could press F12 to open the inspector for the page. then to use network inspector to check websocket connection works or not.

**Comment by mgscreativa** [comment]
Thanks @Kudo! Is it possible to tell metro that the debugger should use ip v4 instead ip v6? Seems that my box can't even ping ipv6 localhost ::1!

`sdk.js:1 WebSocket connection to 'ws://[::1]:8081/inspector/debug?device=0&page=-1' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE`

`$ ping6 localhost`

`ping ipv6 address Address family for hostname not supported`

`$ ping6 ::1`

`ping6: connect: Network unreachable`

**Comment by mgscreativa** [comment]
Finally found the issue. It seems that I have created a conf file in sysctl.d **/etc/sysctl.d/99-disable-ipv6.conf**, inside I had set

```
# Disable ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

So reverting net.ipv6.conf.lo.disable_ipv6 to 0 solved the issue at startup!

Thanks for the help!

**Comment by shubhambajoria1993** [comment]
Where to find sysctl.d /etc/sysctl.d/99-disable-ipv6.conf, ?

> Finally found the issue. It seems that I have created a conf file in sysctl.d **/etc/sysctl.d/99-disable-ipv6.conf**, inside I had set
> 
> ```
> # Disable ipv6
> net.ipv6.conf.all.disable_ipv6 = 1
> net.ipv6.conf.default.disable_ipv6 = 1
> net.ipv6.conf.lo.disable_ipv6 = 1
> ```
> 
> So reverting net.ipv6.conf.lo.disable_ipv6 to 0 solved the issue at startup!
> 
> Thanks for the help!

**Comment by mgscreativa** [comment]
Hi! that was a file I created manually following some internet tutorials because I wanted to disable IP v6, but that conflicted with expo and RN, so I have reverted that changes in my box

**Comment by shubhambajoria1993** [comment]
> Hi! that was a file I created manually following some internet tutorials because I wanted to disable IP v6, but that conflicted with expo and RN, so I have reverted that changes in my box

So, how did you resolved the websSocket disconnected issue when connecting flipper hermes debugger?

**Comment by ednaaaj** [comment]
@mgscreativa I'm getting the same issue, and can't able to find the same file where you disabled or enabled this ipv6. Do you know where to create this same config in osx?

**Comment by mgscreativa** [comment]
In my case the issue was on Linux Mint, no MacOS

**Comment by sp0033212000** [comment]
I'm also facing this issue.
The websocket always lost connection after every reload.
When I click the "Reconnect DevTools" button, the cli window will appear `Error: Device with ID "1" not found.`

**Comment by nickbuc1** [comment]
I am having the same issue. I get the same error message: "Error: Device with ID "N" not found."
I am running the latest expo 49 on a mac.

**Comment by Sir-hennihau** [comment]
any update on this? this makes hermes nearly unusable for me, its nearly impossible to properly debug initial requests and things like that
