### ISSUE TITLE
expo-clipboard permissions are auto-rejected

### ISSUE THREAD

**Issue by jjenzz** [expo/expo#23793]
### Minimal reproducible example

https://snack.expo.dev/@fungiblejen/tenacious-cereal

### Summary

when clicking a pressable that tries to paste from clipboard, the native paste permissions alert will appear and then sometimes instantly close itself, rejecting permissions in the process.

in order to reproduce it consistently in the snack, you can reorder the `React.useState` lines each time you want to test it (i'm not sure why this makes a difference).

### Environment

i am testing this on an iPhone 14 Pro.

```sh
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
      Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.9.3
      expo-cli: 6.0.8
    Expo Workflow: bare
```

### Video showing permissions auto-closing

notice none of the permissions options were pressed here bcos we would see the pressable bg colour change if so.

https://github.com/expo/expo/assets/175330/214dcfc8-399e-4231-8581-acf49edde27e

**Comment by i1skn** [comment]
I'm experiencing the same issue. When you call it first it's almost always immediately closes the "Allow paste" modal and returns an empty string. But the second call usually work as expected.
