### ISSUE TITLE
dlopen failed: library "libexpo-av.so" not found

### ISSUE THREAD

**Issue by xha123** [expo/expo#23790]
### Minimal reproducible example

package.json

`{
  "main": "index.js",
  "name": "ezsoft",
  "private": true,
  "scripts": {
    "start": "react-native start -- --reset-cache",
    "bs": "expo start --config app.eject.json",
    "test": "jest",
    "eslint": "eslint ./app/",
    "build-android": "cd android && ./gradlew installDevKernelDebug",
    "build-androidDevKernelDebug": "cd android && ./gradlew installDebug",
    "clean-android": "cd android && ./gradlew clean",
    "build-ios": "react-native run-ios",
    "rn": "react-native start",
    "prepare": "patch-package",
    "format": "prettier-eslint --write \"app/**/*.js\"",
    "precommit": "lint-staged",
    "build-js": "rm -rf dist && expo export --public-url https://192.168.1.122:9999/ez6app/",
    "serve": "cd dist && python -m SimpleHTTPServer 9999",
    "bundle-ios": "react-native bundle --entry-file App.js --platform ios --dev false --bundle-output ./ios/Exponent/Supporting/kernel.ios.bundle --assets-dest ./ios/Exponent/Supporting/",
    "bundle-android": "react-native bundle --entry-file App.js --platform android --dev false --bundle-output ./android/app/src/main/assets/main.android.bundle --assets-dest ./android/app/src/main/res/"
  },
  "dependencies": {
    "@ant-design/react-native": "^5.0.4",
    "@expo/vector-icons": "^13.0.0",
    "@ez6/common": "^1.1.578",
    "@ez6/common-rn": "^1.0.142",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-camera-roll/camera-roll": "^5.1.0",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/image-editor": "^2.3.0",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-community/segmented-control": "^2.2.2",
    "@react-native-community/slider": "4.4.2",
    "@react-native-community/viewpager": "5.0.11",
    "aliyun-oss-react-native": "./packages/aliyun-oss-react-native",
    "array-flat-polyfill": "^1.0.1",
    "build-url": "6.0.1",
    "china-division": "^2.3.1",
    "coordtransform": "^2.1.2",
    "dayjs": "^1.11.9",
    "dva-core": "2.0.2",
    "dva-loading": "^3.0.20",
    "expo": "^49.0.6",
    "expo-av": "~13.4.1",
    "expo-barcode-scanner": "~12.3.2",
    "expo-camera": "~13.2.1",
    "expo-constants": "~14.4.2",
    "expo-device": "~5.2.1",
    "expo-font": "~11.1.1",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-keep-awake": "~12.0.1",
    "expo-linking": "~4.0.1",
    "expo-local-authentication": "~13.3.0",
    "expo-location": "~15.1.1",
    "expo-media-library": "~15.2.3",
    "expo-screen-orientation": "~5.1.1",
    "expo-secure-store": "~12.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "expo-video-player": "^1.5.8",
    "file-type": "8.1.0",
    "global": "^4.4.0",
    "jcore-react-native": "^1.8.0",
    "jpush-react-native": "^2.8.1",
    "lodash": "^4.17.15",
    "moment": "^2.25.3",
    "nzh": "^1.0.4",
    "pinyin": "^2.9.1",
    "qs": "^6.9.4",
    "rc-form": "2.4.11",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-action-button": "^2.8.5",
    "react-native-actionsheet": "^2.4.2",
    "react-native-agora": "^4.2.1",
    "react-native-animatable": "^1.3.3",
    "react-native-atoz-list": "^1.0.5",
    "react-native-baidu-map-yjj": "^1.0.5",
    "react-native-baidumap-sdk": "^0.6.0",
    "react-native-barcode-builder": "^2.0.0",
    "react-native-doc-viewer": "git+https://github.com/TaroofSun/react-native-doc-viewer.git",
    "react-native-document-picker": "^8.0.0",
    "react-native-draggable-flatlist": "^2.3.2",
    "react-native-easy-gestures": "^2.2.4",
    "react-native-elements": "^2.0.0",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-highlight-words": "^1.0.1",
    "react-native-image-marker": "^0.6.3",
    "react-native-image-resizer": "^1.4.0",
    "react-native-image-view": "^2.1.9",
    "react-native-image-zoom-viewer": "^3.0.0",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-largelist-v3": "^3.0.15",
    "react-native-modal": "^11.6.1",
    "react-native-modalbox": "^2.0.0",
    "react-native-pdf": "6.1.2",
    "react-native-photo-view": "./packages/react-native-photo-view",
    "react-native-pickers": "^2.0.0",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-qrcode-svg": "^6.0.6",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "^2.2.0",
    "react-native-render-html": "^6.3.4",
    "react-native-root-siblings": "^4.0.6",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-scrollable-tab-view": "1.0.0",
    "react-native-section-list-get-item-layout": "^2.2.3",
    "react-native-signature-canvas": "^4.3.0",
    "react-native-smart-tip": "^2.3.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sortable-list": "^0.0.24",
    "react-native-spring-scrollview": "3.0.2",
    "react-native-svg": "13.4.0",
    "react-native-swipe-list-view": "^3.1.0",
    "react-native-swiper-animated": "^1.5.3",
    "react-native-system-setting": "^1.7.3",
    "react-native-tab-view": "^2.14.0",
    "react-native-tree-select": "^2.0.9",
    "react-native-tus-client": "^1.1.0",
    "react-native-vector-icons": "^7.1.0",
    "react-native-version-check": "^3.4.1",
    "react-native-video": "^5.1.0-alpha8",
    "react-native-video-controls": "^2.7.1",
    "react-native-view-shot": "3.5.0",
    "react-native-webview": "13.3.1",
    "react-navigation": "^4.3.9",
    "react-navigation-redux-helpers": "4.0.1",
    "react-navigation-stack": "^2.5.1",
    "react-navigation-tabs": "^2.11.2",
    "react-redux": "7.2.0",
    "redux": "^4.0.5",
    "rmc-cascader": "^5.0.3",
    "rmc-date-picker": "^6.0.10",
    "rn-android-picker-dialog": "^1.1.1",
    "rn-draw": "^0.0.6",
    "rn-fetch-blob": "0.12.0",
    "rn-topview": "^0.1.6",
    "rn-tree-select": "^1.1.0",
    "sentry-expo": "~6.2.0",
    "trtc-react-native": "^2.4.1",
    "tus-js-client": "^2.3.0",
    "yarn": "^1.22.4",
    "yup": "^0.28.5"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-preset-expo": "^9.3.0",
    "babel-preset-react-native": "^4.0.1",
    "eslint": "^7.0.0",
    "eslint-cli": "^1.1.1",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-config-umi": "^1.5.0",
    "eslint-plugin-flowtype": "^3.2.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-react": "~7.13.0",
    "eslint-plugin-react-hooks": "^1.6.0",
    "jest": "^29.2.1",
    "jest-expo": "^48.0.0",
    "lint-staged": "8.0.5",
    "patch-package": "^6.4.7",
    "prettier": "1.15.2",
    "prettier-eslint-cli": "4.7.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "resolutions": {
    "@react-native-community/cli-debugger-ui": "4.7.0",
    "@react-native-community/viewpager": "^2.0.1"
  }
}
`

build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  ext {
    buildToolsVersion = "33.0.1"
    minSdkVersion = 21
    compileSdkVersion = 33
    targetSdkVersion = 33

    applicationId = 'cn.enotary.ez6.ezsoft'
    versionCode = 600000800 // MAXINT（2147483647）
    versionName = '6.5.8.0'
    androidXCore = "1.6.0"
    kotlinVersion = '1.8.10'
  }
  repositories {
    google()
    jcenter()
    mavenCentral()
  }
  dependencies {
    classpath("com.android.tools.build:gradle:7.4.2")
    classpath("com.facebook.react:react-native-gradle-plugin")

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
  }
}

allprojects {
  repositories {
    mavenLocal()
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url("$rootDir/../node_modules/react-native/android")
    }
    maven {
      // Android JSC is installed from npm
      url("$rootDir/../node_modules/jsc-android/dist")
    }
    maven {
      url "$rootDir/../node_modules/expo-camera/android/maven"
    }
    google()
    jcenter()
    mavenCentral()
    maven { url 'https://www.jitpack.io' }
  }
}

app/build.gradle

apply plugin: "com.android.application"
apply plugin: "com.facebook.react"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
  enableHermes: false
]

//apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
  compileSdkVersion rootProject.ext.compileSdkVersion

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  defaultConfig {
    applicationId rootProject.ext.applicationId
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    versionCode rootProject.ext.versionCode
    versionName rootProject.ext.versionName
    
    multiDexEnabled true
    ndk {
      abiFilters 'armeabi-v7a'
    }
  }
  splits {
    abi {
      reset()
      enable enableSeparateBuildPerCPUArchitecture
      universalApk false  // If true, also generate a universal APK
      include "armeabi-v7a"
    }
  }

  flavorDimensions 'remoteKernel'
  productFlavors {
    devKernel {
      dimension 'remoteKernel'
    }
    prodKernel {
      dimension 'remoteKernel'
    }
  }
  

  buildTypes {
    debug {
      debuggable true
      ext.enableCrashlytics = false
      signingConfig signingConfigs.release
    }
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      signingConfig signingConfigs.release
    }
  }

  sourceSets {
    main {
      jniLibs.srcDirs = ['libs']
    }
  }

  // applicationVariants are e.g. debug, release
  applicationVariants.all { variant ->
    variant.outputs.each { output ->
      // For each separate APK per architecture, set a unique version code as described here:
      // https://developer.android.com/studio/build/configure-apk-splits.html
      def versionCodes = ["armeabi-v7a": 1]
      def abi = output.getFilter(OutputFile.ABI)
      if (abi != null) {
        // null for the universal-debug, universal-release variants
        output.versionCodeOverride =
          versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
      }

    }
  }

  lintOptions {
    abortOnError false
  }

  packagingOptions {
    pickFirst "**"
    pickFirst '**/libc++_shared.so'
    doNotStrip "*/armeabi/libYTCommon.so"
    doNotStrip "*/armeabi-v7a/libYTCommon.so"
    doNotStrip "*/x86/libYTCommon.so"
    doNotStrip "*/arm64-v8a/libYTCommon.so"
  }

  compileOptions {
    sourceCompatibility 1.8
    targetCompatibility 1.8
  }
}

dependencies {
  implementation 'com.tencent.bugly:crashreport:latest.release'
  implementation 'com.tencent.bugly:nativecrashreport:latest.release'
  implementation 'online.osslab:CircleProgress:1.0.0'
  implementation 'com.github.pqpo:Log4a:1.4.2'

  implementation fileTree(dir: "libs", include: ["*.jar"])
  //noinspection GradleDynamicVersion
//  implementation "com.facebook.react:react-native:+"  // From node_modules
  implementation "com.facebook.react:react-android"
  implementation "com.facebook.react:hermes-android"
  implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
  implementation project(path: ':ocridcardlibrary')
  debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.fbjni'
  }
  debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.flipper'
    exclude group: 'com.squareup.okhttp3', module: 'okhttp'
  }
  debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
    exclude group: 'com.facebook.flipper'
  }
  // addUnimodulesDependencies()

  if (enableHermes) {
    def hermesPath = "../../node_modules/hermes-engine/android/";
    debugImplementation files(hermesPath + "hermes-debug.aar")
    releaseImplementation files(hermesPath + "hermes-release.aar")
  } else {
    implementation jscFlavor
  }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.implementation
  into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesAppBuildGradle(project)

### Summary

 java.lang.UnsatisfiedLinkError: dlopen failed: library "libexpo-av.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1656)
                                                                                                    	at expo.modules.av.AVManager.<clinit>(AVManager.java:57)
                                                                                                    	at expo.modules.av.AVPackage.createInternalModules(AVPackage.java:19)
                                                                                                    	at expo.modules.adapters.react.ReactModuleRegistryProvider.get(ReactModuleRegistryProvider.java:51)
                                                                                                    	at expo.modules.adapters.react.ModuleRegistryAdapter.getOrCreateNativeModulesProxy(ModuleRegistryAdapter.java:123)
                                                                                                    	at expo.modules.adapters.react.ModuleRegistryAdapter.createNativeModules(ModuleRegistryAdapter.java:53)
                                                                                                    	at expo.modules.ExpoModulesPackage.createNativeModules(ExpoModulesPackage.kt:35)
                                                                                                    	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
                                                                                                    	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
                                                                                                    	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1467)
                                                                                                    	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1438)
                                                                                                    	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1340)
                                                                                                    	at com.facebook.react.ReactInstanceManager.-$$Nest$mcreateReactContext(Unknown Source:0)
                                                                                                    	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)

![image](https://github.com/expo/expo/assets/25577710/82587654-2c67-4dcd-b258-5d81c15638a5)

### Environment

OS:Android
node:v16.20.1
yarn:1.22.19
metro:v0.76.7
react-native:0.72.3
expo:^49.0.6
expo-av:~13.4.1

**Comment by xha123** [comment]
I found that expo-av only compiles Task :expo-av:buildCMakeDebug[arm64-v8a], is armeabi-v7a not supported?

**Comment by buster95** [comment]
I found a solution for this problem I have to Install Android NDK in Android SDK, ensure is placed on this path
`~/Library/Android/sdk/ndk/<version>` not under `~/Library/Android/sdk/ndk/<version>/<version name>` jus copy out of the second path to the first
