### ISSUE TITLE
Expo document picker multiple file selection not working

### ISSUE THREAD

**Issue by maheenur13** [expo/expo#23799]
### Minimal reproducible example

 const result = await DocumentPicker.getDocumentAsync({ type: '*/*', multiple: true, copyToCacheDirectory: true });

### Summary

Here when i try to select multiple file but it select only  a single file and it returns a single object.

### Environment

npx expo-env-info

**Comment by davidwico** [comment]
@lukmccall @alanjhughes seems like I have the same issue, can anyone check that?

**Comment by No1Joon** [comment]
I have the same issue..
