### ISSUE TITLE
Options for live streaming other than WebRTC

### ISSUE THREAD

**Issue by idrakimuhamad** [expo/expo#2379]
I'm using the expo `video` component to play a live stream video from our service provider. The stream format is in `.m3u8`. It played well and fine. However, I noticed that when it buffered and then continue playing, it didn't get pick up at the current stream tick/time. Instead it continue where it left off. Which makes it no longer look like a live stream. I think that it make sense since its just a video player sort of serving the video like you stream a movie.

I'm wondering what else can be done to achieve this in current Expo environment other than detaching the app?

**Comment by tcdavis** [comment]
There isn't anything that I'm aware of at least.  You can make a request for us to improve the functionality here: https://expo.canny.io/feature-requests
