### ISSUE TITLE
Imagepicker crashing on detached project

### ISSUE THREAD

**Issue by ahmed-wagdi** [expo/expo#238]
On detached projects, the imagepicker component crashes the app as soon as i open the imagepicker, I've only tried this on ios. To make sure that it wasn't a problem with my code I created completely new project using create-react-native-app and detached to expokit, it still happens. 

Here's the screenshot of the error i'm getting on xcode:
<img width="1398" alt="screen shot 2017-06-07 at 1 12 18 pm" src="https://user-images.githubusercontent.com/8686483/26875941-50ec6c20-4b84-11e7-884c-84856c875ab7.png">

**Comment by nikki93** [comment]
This happens due to lack of authorization as specified in your project metadata. See here: https://stackoverflow.com/a/38241350 There is a similar key for camera usage.

Let me know if reflecting this fixes your issue and I will close this.

**Comment by ahmed-wagdi** [comment]
Great thanks 👍
