### ISSUE TITLE
Fonts hook doesn't return true when using Clerk on the web

### ISSUE THREAD

**Issue by altworowsky** [expo/expo#23802]
### Minimal reproducible example

https://github.com/altworowsky/expo-clerk-issue

### Summary

When using Expo with Clerk and the Metro bundler for the web, the ```useFonts``` hook never returns true for ```loading```.

Steps to reproduce:
1. Clone the repo and install dependencies with yarn
2. Run yarn start which will clear the cache and start expo with the web target
3. The page should render "Hello world!" but doesn't because ```loading``` is never true

If you remove Clerk or remove the custom font, the page will render correctly.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.17.0/bin/npm
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    Expo Workflow: managed

**Comment by altworowsky** [comment]
I managed to resolve the issue by adding the following resolution to my `package.json`.

` "resolutions": {
    "@clerk/clerk-expo/react-native-url-polyfill": "^2.0.0"
  }`

It looks like somehow the project ends up with an incompatible version `punycode`.

**Comment by aleqsio** [comment]
Glad to hear this is fixed, sounds like the fix should be implemented on Clerk's side so closing this issue :)
