### ISSUE TITLE
[docs] expo.dev registration failed, error message: n is not a function

### ISSUE THREAD

**Issue by lengziyu** [expo/expo#23817]
### Summary

Hello, I have tried many times to register an account, but I keep getting an error. Could you please check it for me? Here is the screenshot. Thank you.
![image](https://github.com/expo/expo/assets/9267469/400bff24-448f-4572-96de-10e3e621a2e5)

### Link to the related docs page

https://expo.dev/signup

**Comment by brentvatne** [comment]
i suspect this is related to a browser extension that you are using. please try incognito mode and let us know if the issue persists
