### ISSUE TITLE
SDK 49 - Constants.expoConfig is an empty object in Web 

### ISSUE THREAD

**Issue by tanmontgomeryf** [expo/expo#23819]
### Minimal reproducible example

https://github.com/tanmontgomeryf/expo-sdk-49-minimal-web

### Summary

Constants.expoConfig is an empty object in Web (metro bundler)

![Screenshot 2023-08-04 at 8 00 33 PM](https://github.com/expo/expo/assets/64457052/9e76df40-214c-449e-b5aa-41feab1d4524)
![Screenshot 2023-08-04 at 8 00 41 PM](https://github.com/expo/expo/assets/64457052/907a77e2-6f4e-4bdf-968c-54df65b1a3c7)
![Screenshot 2023-08-04 at 8 01 21 PM](https://github.com/expo/expo/assets/64457052/64521d4a-1ec3-48a8-836b-538244303a8e)

### Environment

System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7
      expo: ~49.0.5 => 49.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    npmGlobalPackages:
      eas-cli: 3.16.0
      expo-cli: 6.1.0
    Expo Workflow: managed

**Comment by events-jonas-chrisw** [comment]
Same problem here, not working on Metro web

**Comment by dan-doyon-endear** [comment]
Would like to know timeframe for this fix. It's kind of a blocker. Decoupling from webpack would solve a number of issues, Storybook has been painful to keep up to date with current Expo versions so we are not using it. It might be that we need a monorepo instead of a single repo, but we're not ready for that complexity (yet). We've created a hello world Expo 49/Storybook project which does work fine when metro is being used. Have noticed that the expo cli crashes sometimes on hot reload, not sure why but would be good to remove webpack as a variable.

Anyway, if we could get a timeframe that would be great. 

Thanks

**Comment by Slapbox** [comment]
I'm not using web but it does seem this issue is in need of an update from the devs.

**Comment by EvanBacon** [comment]
As a temporary workaround, you can install expo router and use the expo router babel plugin to instantiate the manifest. You don't have to use expo-router for runtime navigation, just the transform. Otherwise, this'll be fixed in SDK 50.

**Comment by VilleMiekkoja** [comment]
> As a temporary workaround, you can install expo router and use the expo router babel plugin to instantiate the manifest. You don't have to use expo-router for runtime navigation, just the transform. Otherwise, this'll be fixed in SDK 50.

Can you provide guide and documentation of how to do this?

**Comment by VilleMiekkoja** [comment]
Tried to fix with expo router and babel plugin, but got this error:

> error: node_modules/expo-router/_ctx.web.tsx: node_modules/expo-router/_ctx.web.tsx:Invalid call at line <unknown>: process.env.EXPO_ROUTER_APP_ROOT
First argument of `require.context` should be a string denoting the directory to require.

**Comment by andrewchester1** [comment]
I am running into this same issue on expo 50. ExpoConfig is returning an empty object on web, but works as expected on android and iOS(I am not using expo router). Is the expo router babel plugin still needed in expo 50? If it is required still, some documentation or example of the work around would be appreciated!

**Comment by makkarMeenu** [comment]
I'm using Expo Router v3 and have configured extras within my app.json file. Although it functions correctly on iOS and Android, I'm facing an inconsistency on the web platform where it returns as undefined. Can anyone please help?

**Comment by rszymula** [comment]
I'm getting the same as above. @EvanBacon  noted that it will be fixed in v50 but it is not

This is a blocker to getting an app deployed in multiple environments, and released to prod 

My company is trying to release a product right now, and cannot
Unless theres a quick solution, we will be dropping Expo because of this

**Comment by EvanBacon** [comment]
@rszymula I just bootstrapped a new project (SDK 50), added web support and ran:

```js
import Constants from "expo-constants";
export default function App() {
  console.log(">", Constants.expoConfig);
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

It prints as expected:

<img width="809" alt="Screenshot 2024-03-25 at 7 56 04 PM" src="https://github.com/expo/expo/assets/9664363/7be07d48-78eb-4bd5-96d1-62ed48bbd5da">


Note that you will need to clear the bundler cache when you change the app json, this is a limitation of metro that we're planning to fix in the future.
