### ISSUE TITLE
Strange hermes debug jumps and var state

### ISSUE THREAD

**Issue by mgscreativa** [expo/expo#23820]
### Minimal reproducible example

https://github.com/mgscreativa/heremes-test-expo-go

### Summary

I’m using hermes debugging working, but the debugger behavior is really strange. My workspace is as follows:

- Linux Mint 21.2
- WebStorm 2023.1.4
- Using expo sdk v49 (49.0.6)
- Expo Go on iPhone 12 Pro Max and iOS 16.5.1

For testing hermes debugging I have created a complete new and clean app with `npx create-expo-app@latest --template tabs`, I have also uploaded the app to GitHub here [GitHub - mgscreativa/heremes-test-expo-go: heremes-test-expo-go 1](https://github.com/mgscreativa/heremes-test-expo-go)

Accessing chrome debugger by pressing **j** in terminal I can see the hermes instance running and also can browse the project files and set some breakpoints in code but the debugger behavior is really strange, ie:

- Defined variables displays **undefined** when already defined in code
- Watched vars already defined in code, sometimes display **undefined** as values and sometimes displays their actual values

I have tested the same result in:
- Linux with expo go in Android 13 device, iOS iPhone XS Max, and Android emulator API 33
- Macos Android 13 device, iOS iPhone XS Max

Have attached a two videos showing the process I’m following
#### Linux, Android Emu API 33
![Peek 2023-08-04 12-16](https://github.com/expo/expo/assets/1286632/84230ff3-4006-42c9-93be-d9dd0977917f)

#### Linux, iOS expo go
![Peek 2023-08-04 12-21ios](https://github.com/expo/expo/assets/1286632/02a226fb-ac04-4102-9ce2-51503dc51072)

What Am I doing wrong? Should I configure anything else?

PS: Flipper 0.210.0 has the same behavior, tested on macos

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.2 (Victoria)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 20230430.125247.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86_64 Atom, android-32 | Google APIs Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 3.18.3
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by mgscreativa** [comment]
I'm uploading this third video showing the behavior I get using a more complex project that I'm working on. I'll describe the strange behavior:

- The debugger jumps directly to the code at line 58 without stopping on first breakpoint at line 52!
- Strangely, it jumps to line 64 but that line should not be executed as it's an else statement that was not hit by the condition of the if statement at line 58
- After hitting the Resume button, the code jumps to line 52 and it doesn't hit line 58 anymore
- Sometimes after hitting the Resume button the app crashes

![Peek 2023-08-04 12-53-3](https://github.com/expo/expo/assets/1286632/87633830-c271-4cc8-8837-efe2886fc887)

**Comment by mgscreativa** [comment]
Hi! any comments?

**Comment by brentvatne** [comment]
I believe this is due to a limitation of Hermes itself at the moment, and the Hermes team is working on improving it. cc @byCedric

**Comment by mgscreativa** [comment]
Thanks @brentvatne At least now I know that I'm not crazy!

**Comment by brentvatne** [comment]
> At least now I know that I'm not crazy!

well, at least not on account of this behavior 😄

**Comment by mgscreativa** [comment]
Hey @brentvatne, where can I post this issue? does hermes has a GH repo? Should I report this to RN repo?

**Comment by brentvatne** [comment]
the hermes repo is likely the correct place for this

**Comment by mgscreativa** [comment]
Done https://github.com/facebook/hermes/issues/1087

**Comment by byCedric** [comment]
Left a comment on https://github.com/facebook/hermes/issues/1087, and thanks for the detailed issue report! Unfortunately, there isn't a lot we can do from expo's end. We are working with Meta to resolve some weird debugging behaviors.

For now, the best you can do if you run into weird issues like this, is restarting everything. Close the bundler / CLI, close the app, close the debugger, and start everything again.

Hope this helps!

**Comment by nn1900** [comment]
The chrome devtools debugging does not work very well with break points and source maps. Setting break points directly in dev tools makes the debugger breaks at incorrect places, as a result all local/scope variables are incorrect. Looking forward to future improvements. Basically I prefer Chrome DevTools to Flipper which I previously used for debugging purposes. It seems that Flipper worked more precisely previously from my experience.
