### ISSUE TITLE
[docs] Update Progressive Web App page for Metro / Expo SDK 49

### ISSUE THREAD

**Issue by hbcondo** [expo/expo#23823]
### Summary

The current [Progressive Web App page](https://github.com/expo/expo/blob/6887043aa15d81d8d1def5ef419d9d19e06bb033/docs/pages/guides/progressive-web-apps.mdx) shows using `@expo/webpack-config` for generating a PWA but Expo 49 says _Metro is now recommended for web_. Can this web page be updated to show how a PWA can be created using Metro? Thank you.

![image](https://github.com/expo/expo/assets/306958/fa5cd9b1-4326-4780-8d59-55ffaa5eb70e)
Source: https://blog.expo.dev/expo-sdk-49-c6d398cdf740

### Link to the related docs page

https://docs.expo.dev/guides/progressive-web-apps/

**Comment by rickithadi** [comment]
any update from the expo team?

**Comment by hbcondo** [comment]
Just saw the expo team did a [PR](https://github.com/expo/expo/pull/24026) a couple days ago that updated the PWA doc. It would be nice if the [enable-service-workers](https://github.com/expo/fyi/blob/main/enabling-web-service-workers.md) page was updated too.

**Comment by anhphamminh** [comment]
@hbcondo so is it possible implement Progressive Web App page for Metro now?

**Comment by abulka** [comment]
Am also using Metro as recommended, and the PWA doco https://docs.expo.dev/guides/progressive-web-apps/ says to run
```
npx workbox-cli wizard
```
to configure service worker stuff, but I get 
```
Error: Cannot find module '@babel/core'
```
using Node.js v18.16.0.  Is the doco broken? The whole PWA service worker expo metro stuff is confusing me. 

And it seems that a service worker is needed to be able to update iOS PWA apps with newer versions of themselves e.g. this [SO post](https://stackoverflow.com/questions/52221805/any-way-yet-to-auto-update-or-just-clear-the-cache-on-a-pwa-on-ios) - but how to create one in expo metro?
