### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by rumaiz-ahmed** [expo/expo#23821]
### Summary

The Build has failed with the following error as shown below 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~49.0.3",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "firebase": "^10.0.0",
    "moment": "^2.29.4",
    "native-base": "^3.4.28",
    "pullstate": "^1.25.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.45.2",
    "react-native": "0.72.3",
    "react-native-element-dropdown": "^2.9.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-modal-datetime-picker": "^17.0.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6",
    "expo-notifications": "~0.20.1",
    "expo-device": "~5.4.0",
    "expo-permissions": "~14.2.1"
  },

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22616
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.3 => 49.0.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: managed

### Reproducible demo

w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

336 actionable tasks: 336 executed

[stderr] 
FAILURE: Build failed with an exception.

[stderr] 
* What went wrong:

[stderr] 
Execution failed for task ':expo-splash-screen:compileReleaseKotlin'.

[stderr] 
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

[stderr] 
   > Compilation error. See log for more details

[stderr] 
* Try:

[stderr] 
> Run with --stacktrace option to get the stack trace.

[stderr] 
> Run with --info or --debug option to get more log output.

[stderr] 
> Run with --scan to get full insights.

[stderr] 
* Get more help at https://help.gradle.org

[stderr] 
BUILD FAILED in 5m 41s

Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by sunjungAn** [comment]
I have resolved this problem by updating to expo ~49.0.6.
