### ISSUE TITLE
Error: Font doesn't support automatic scaling (SDK30 and iOS <12 only)

### ISSUE THREAD

**Issue by kelvinlawson** [expo/expo#2382]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 7.6.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Tested on iPhone SE Simulator and iPhone 6S in Expo client, not standalone. adjustsFontScaling only supported on iOS so haven't tested Android.

### Steps to Reproduce

(Write your steps here:)

1. Add TTF font asset.
2. Use adjustsFontSizeToFit={true} in a <Text> tag.

### Expected Behavior

Should auto-scale font (and does work fine on earlier SDKs)

### Actual Behavior

Get the error "Font ''Lato doesn't support automatic scaling" when running on SDK30.

Get the same error for other fonts tested, e.g. Google's Roboto-Regular.ttf.

![simulator screen shot - iphone se - 2018-10-09 at 17 02 41](https://user-images.githubusercontent.com/118135/46683056-1da47080-cbe7-11e8-9c85-06f79ceb1c6d.png)

This worked fine on SDK29 and earlier.

Note that it works in Snack but not when exported to an XDE project, does this indicate something wrong with the bundling?

### Reproducible Demo

Snack project which works fine running on iPhone SE Simulator or on iPhone 6S: https://snack.expo.io/SkXRWIc57

Exact same Snack project exported to a project from Snack and served from macOS, which does not work: 
[loading-fonts.zip](https://github.com/expo/expo/files/2461265/loading-fonts.zip)

**Comment by kyhnlbyrk** [comment]
any fixes? I am having the same issue right now..

**Comment by kelvinlawson** [comment]
Thanks, it looks like I should try a later version of Node.

Would be great if @kyhnlbyrk could paste his diagnostics as well to see if there is any pattern.

**Comment by sjchmiela** [comment]
Frankly speaking it would be strange for Node version to affect this anyhow… 🤔

**Comment by sjchmiela** [comment]
Huh, I could try running the app on a non-iOS 12 device/simulator, maybe then issue would occur…

Is the app detached or are you using latest Expo Client App Store to run the experience?

**Comment by kelvinlawson** [comment]
It's a normal standalone build. It's also the latest Expo client, including just now when I created a fresh iPhone SE simulator (iOS 11.4).

**Comment by kyhnlbyrk** [comment]
Hi here is my diagnostics: 

OS: macOS High Sierra 10.13.2
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

**Comment by kelvinlawson** [comment]
OK tested on another MBP with a later Xcode installed.

The project runs fine on iOS 12 but does not work on 10.2, 10.3, 11.2.6 or 11.4.

**Comment by kelvinlawson** [comment]
It would be great if a fix could make it into SDK31. We can't upgrade to SDK30 because we use our own font, and it would be a shame if we couldn't upgrade to SDK31 either. Thanks a lot.

**Comment by sjchmiela** [comment]
I've found the issue causing this bug, thanks for your patience. I'll close this issue once it's resolved.

**Comment by kyhnlbyrk** [comment]
Hi, @sjchmiela what can I do to get this fix? Because I still have the same issue

**Comment by sjchmiela** [comment]
Hey! Just upgrade your application to SDK31 following upgrade steps outlined in https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49. 🙂
