### ISSUE TITLE
expo-contacts on Pixel 6 Pro emulator Error: Insert into content://com.android.contacts/data returned no result

### ISSUE THREAD

**Issue by CoreyCole** [expo/expo#23828]
### Minimal reproducible example

https://snack.expo.dev/@corey_ciremi/contacts-phone-and-email-android-issue

### Summary

Calling `addContactAsync()` does not work on my pixel devices when providing a phone number & email. I've reproduced the error message on both my physical `pixel 4a` and my emulated `pixel 6 pro api 33`.

As shown in this test below, it works for a contact without phone number or email, but with either email or phone number, we get the error:

```
 LOG  contactIdWorks:  1636
 ERROR  err:  [Error: Insert into content://com.android.contacts/data returned no result]
```

```typescript
export async function testExpoContacts() {
    try {
        if (!await getContactsPermission()) throw "permission denied";
        const phoneNum: Contacts.PhoneNumber = {
            number: "123-456-7890",
            label: "mobile",
            isPrimary: true,
            id: "",
        };
        const emailEntry: Contacts.Email = {
            email: "bob@testing.com",
            label: "email",
            isPrimary: true,
            id: "",
        };
        const cleanContact: ExpoContact = {
            [Contacts.Fields.FirstName]: "Bob",
            [Contacts.Fields.LastName]: "Tester",
            [Contacts.Fields.Company]: "Testing Inc",
            [Contacts.Fields.JobTitle]: "CEO",
            [Contacts.Fields.Note]: "bob tester note",
            id: "",
            contactType: Contacts.ContactTypes.Person,
            name: "Bob Tester",
        };
        const badContact = {
            ...cleanContact,
            [Contacts.Fields.PhoneNumbers]: [
                phoneNum,
            ],
            [Contacts.Fields.Emails]: [
                emailEntry,
            ],
        };
        const contactIdWorks = await Contacts.addContactAsync(cleanContact);
        console.log("contactIdWorks: ", contactIdWorks);
        const contactId = await Contacts.addContactAsync(badContact);
        console.log("contactId: ", contactId);
    } catch (err) {
        console.error("err: ", err);
    }
}
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.3.1 - /usr/local/bin/npm
      Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.6 => 0.10.7 
      expo: ^49.0.6 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.17.1
    Expo Workflow: bare

**Comment by behenate** [comment]
Hi! Thanks for the report. We are working on a fix, for now you can easily work around the issue by passing phone number and emails, which have `id` set to `null`. The `id`  shouldn't be set when adding a new value (it should be auto-assigned natively), but our documentation doesn't make that clear and we don't block this option, which leads to the issue. 

```
const phoneNum: Contacts.PhoneNumber = {
            number: "123-456-7890",
            label: "mobile",
            isPrimary: true,
            id: null,
        };
        const emailEntry: Contacts.Email = {
            email: "bob@testing.com",
            label: "email",
            isPrimary: true,
            id: null,
        };
 ```
