### ISSUE TITLE
[Android][expo-router] url schemes like content: should not be handled by expo-router

### ISSUE THREAD

**Issue by G-Ray** [expo/expo#23838]
### Minimal reproducible example

https://github.com/G-Ray/expo-router-content-link-issue

### Summary

in `app.json`, defining an intentFiler to handle `content` scheme
```json
"intentFilters": [
  {
    "action": "VIEW",
    "data": [
      {
        "scheme": "content",
        "mimeType": "text/plain"
      }
    ],
    "category": [
      "BROWSABLE",
      "DEFAULT"
    ]
  }
],
```

Creating a development build, and opening a `*.txt` file from a file browser, the app is routed to an unknown route.

I would expect for `expo-router` to not handle `content:` scheme as a deep link.

Of course, this is not limited to the `content` scheme. 

Should `expo-router` be configured to handle certain `intentFilters` as deep links and not other ? It seems we could ignore incoming unwanted protocols in url here: https://github.com/expo/expo/blob/ee9ef118cc3ddf1ae2ed311b4a50e770ce55f6db/packages/expo-router/src/fork/useLinking.native.ts#L166

### Environment

```sh
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.3 Fedora Linux 38 (Container Image)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 18.16.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.5.1 - /usr/bin/npm
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 3.13.3
    Expo Workflow: managed
```

**Comment by EvanBacon** [comment]
Philosophically, we want Expo Router to handle any sort of event that can lead to the app being launched, this includes quick actions, notifications, widgets, share sheets, etc. Anything that launches the app will end up somewhere in the app. For example, "doing nothing" is essentially the same as aliasing all `content://*` URLs to `/` (`app/index.js`).

So it's possibly a question of how we should represent the incoming request based on the launch context.

**Comment by marklawlor** [comment]
SDK51 now allows you to rewrite deeplinks and other intent paths. We will have a blog post about this soon.

You can create a new file called `+native-intent` in your `app` folder. It should export a single function `redirectSystemPath`

```
// +native-intent.ts
export function redirectSystemPath({ path, initial }) {
  const url = new URL(path, 'http://myapp.com')
  if (url.protocol === "content:") {
    return null
  }
  
  return path;
}
```
