### ISSUE TITLE
Dead link in Docs

### ISSUE THREAD

**Issue by spedy** [expo/expo#2383]
When opening cameraroll docs, returning response is 404.

https://docs.expo.io/versions/latest/react-native/cameraroll.md

**Comment by tcdavis** [comment]
Thanks!
I'm seeing the dead link at https://docs.expo.io/versions/latest/react-native/images#local-filesystem-images

**Comment by FiberJW** [comment]
This seems to be resolved, so I’ll close this for now. If you notice any related bugs in the future, please open a new issue :)
