### ISSUE TITLE
SMS.sendSMSAsync doesn't return correct `result` on Android phones

### ISSUE THREAD

**Issue by kylebebak** [expo/expo#2384]
### Environment

~~~
[13:29:44] Generating diagnostics report...
[13:29:44] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS Sierra 10.12.2
  Node: 8.11.4
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 8.3.2 Build version 8E2002
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
|[13:29:47] Request failed with status code 500
[13:29:47] Set EXPO_DEBUG=true in your env to view the stack trace.
~~~

Target: Various Android phones (same broken behavior on all of them)

### Steps to Reproduce

1. Create an app and give it permission to send SMS messages, e.g. using `Permissions.getAsync(Permissions.SMS)`
2. Send an SMS message using `const { result } = await SMS.sendSMSAsync(phone, message)`
3. Observe that whether or not user actually sends message, the value of `result` is not `"sent"`

### Expected Behavior

If user actually sends message, `result` should be `"sent"`, as is documented here: <https://docs.expo.io/versions/latest/sdk/sms#exposmssendsmsasyncaddresses-message>.

### Actual Behavior

Whether or not user actually sends message, the value of `result` is not `"sent"`. This is **not** the case when using this API on iOS phones.

### Reproducible Demo

The explanation is about as clear as it can be, and it most definitely is an issue.

If it isn't possible to return an informative value for `result` on Android phones, or on certain devices, then this should be documented.

Nevertheless, I'll make a Snack when I have some time. It probably won't tell you anything you don't know already from this description.

**Comment by coderavel** [comment]
i have same problem.
