### ISSUE TITLE
android cannot receive notification

### ISSUE THREAD

**Issue by plau1129** [expo/expo#23856]
### Minimal reproducible example

install expo-notification -> eas build android -> push notification through php sdk

### Summary

when I build production apps published on app store and google pay, expo notification works on ios but not on android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.2
    Expo Workflow: bare

**Comment by Justin-Jingcheng-Peng** [comment]
Hello, are you able to fix this?

**Comment by plau1129** [comment]
turned out I need to send another notification through FCM on top of the expo push sdk

**Comment by Justin-Jingcheng-Peng** [comment]
Even for local expo go testing?

**Comment by Justin-Jingcheng-Peng** [comment]
I am testing this locally on expo go. IOS has no issues but android cannot receive push notifications

**Comment by plau1129** [comment]
Expo go: android and ios works well
Standalone app: ios ok but android cannot receive any notification. Finally I pushed through fcm on top of the expo sdk.

**Comment by plau1129** [comment]
Even that, some android device cannot receive it when the app is in the foreground.

**Comment by Justin-Jingcheng-Peng** [comment]
thanks

**Comment by Justin-Jingcheng-Peng** [comment]
Btw, do you need FCM firebase configuration for expo go android push notifications?
