### ISSUE TITLE
launchImageLibraryAsync() asks for permission after photos is selected

### ISSUE THREAD

**Issue by Justin-Jingcheng-Peng** [expo/expo#23852]
### Minimal reproducible example

let result = await ImagePicker.launchImageLibraryAsync({       mediaTypes: ImagePicker.MediaTypeOptions.Images,       allowsEditing: true,       aspect: [4, 3],       quality: 1,     });

### Summary

![Screenshot 2023-08-08 at 12 10 50 AM](https://github.com/expo/expo/assets/68234802/ddb71547-3ea3-445e-b85f-3a949c636f48)

I am trying to let the user upload a picture from the library. But for some reason, after this function call, the iPhone will show such an alert as below:

![IMG_8146](https://github.com/expo/expo/assets/68234802/7f85ab22-8a3e-4e81-b51d-2e17a2ca7954)

### Environment

npx expo start

**Comment by mcottingham** [comment]
Did you request media library permission before calling `launchImageLibraryAsync`?

https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickerrequestmedialibrarypermissionsasyncwriteonly

**Comment by Justin-Jingcheng-Peng** [comment]
Thanks for your response. Yes I did have this code before calling the function:

let permissionResult =
      await ImagePicker.requestMediaLibraryPermissionsAsync();

    if (permissionResult.granted === false) {
      alert("Permission to access the media library is required!");
      return;
    }
