### ISSUE TITLE
Expo modules build failed with Gradle version 8 in Bare workflow

### ISSUE THREAD

**Issue by marsakt** [expo/expo#23869]
### Minimal reproducible example

 // Creating sources with comments  task androidSourcesJar(type: Jar) { -  classifier = 'sources' +  archiveClassifier.set("sources")    from android.sourceSets.main.java.srcDirs  }

### Summary

I installed expo modules in my react native bare workflow as per the documentation ([Install Expo modules](https://docs.expo.dev/bare/installing-expo-modules/)) to use some expo packages.

**After upgrading my project to React Native [v0.72.0](https://github.com/facebook/react-native/releases/tag/v0.72.0) which is released recently and came with the Gradle version 8. The following packages are failing with this error while syncing the project when we run yarn android.**

Could not set unknown property 'classifier' for task ':expo-application:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar

**List of affected packages are**
**- expo-gl-cpp**

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.17.1 - C:\Tools\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Tools\Yarn\bin\yarn.CMD
      npm: 8.15.0 - C:\Tools\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    Expo Workflow: bare

**Comment by Esarhaddon** [comment]
I'm seeing this as well. I ran into a similar issue with another package and found an explanation [here](https://stackoverflow.com/a/75701687). Running `yarn patch [package name]` and renaming `classifier` -> `archiveClassifier` in `build.gradle` seemed to work for me in that case. Planning to try that for `expo-av` and report back.

**Comment by Kudo** [comment]
hi there! `expo-gl-cpp` is deprecated in sdk 49. using the `expo-gl` is enough. thanks!
