### ISSUE TITLE
[expo-linear-gradient][Android] renders very slow

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#23861]
### Minimal reproducible example

https://github.com/RRaideRR/expo-slow-gradient

### Summary

I debugged my app lately to investigate slow Android startup-times. It turns out this is caused by using a gradient. Not quite sure if this is just something I must live with because its so computationally expensive like the latest BlurView version. However, it feels wrong, that this causes approximately 1.5s in additional render time. Maybe related to [#23189](https://github.com/expo/expo/issues/23189). 

I tested it with SDK 48 and SKD 49 - no notable difference. Test device was a Motorola G8 Power with Android 11.

SDK 49 with Gradient.
https://github.com/expo/expo/assets/3411292/da656f37-dbca-4a23-8f29-2439acb72c5b

SDK 49 without Gradient (package installed but usage commented out in App.js)
https://github.com/expo/expo/assets/3411292/a89c5697-a932-4c2a-b19c-c5bef9f0e061

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 4.0.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by RRaideRR** [comment]
side by side comparison

https://github.com/expo/expo/assets/3411292/3aac8a49-5ea2-481b-84b9-ccbad934db56

**Comment by RRaideRR** [comment]
Dear bot. This issue is not stale.

**Comment by RRaideRR** [comment]
Dear bot. This issue is not stale.

**Comment by RRaideRR** [comment]
Dear bot. This issue is not stale.

**Comment by RRaideRR** [comment]
@lukmccall  - you are right. Sorry I didn't follow the other issue there. Just tested it out side by side a minute ago with SDK50 and it was indeed fixed. My apologies 🙇

**Comment by ningacoding** [comment]
Linear Gradient is still very slow when rendering on large lists with FlatList while scrolling.

this causes UI freeze while scrolling.
