### ISSUE TITLE
Expo splash screen removal

### ISSUE THREAD

**Issue by AakashRainaClairvoyant** [expo/expo#2388]
I have a fully detached app(detached with expokit) and on running the app I'm getting a white splash screen on launch(Expo's splash screen). I want to remove expo's splash screen entirely from the app. I already have my splash screen in place. Any methods of how I can achieve this? Thanks in advance.

**Comment by tcdavis** [comment]
Can you direct questions about usage to forums.expo.io?
You may want to check https://docs.expo.io/versions/latest/guides/splash-screens#detached-expokit-apps to see if it helps

**Comment by Luckygirlllll** [comment]
Nothing says there about how to remove the Splash screen, only how to modify it!

**Comment by Luckygirlllll** [comment]
This issue should be open, not closed!

**Comment by raikk** [comment]
same issue here..

**Comment by Erlix322** [comment]
I'd like to push this too
