### ISSUE TITLE
Expo 49 Sqlite Typescript errors

### ISSUE THREAD

**Issue by rp121** [expo/expo#23884]
### Minimal reproducible example

https://github.com/Plinthify/expo-sqlite.git

### Summary

On a fresh install of Expo SDK 49 (using typescript) and `expo-sqlite` (v11.3.2) installed:
There are typescript type errors when attempting to access ResultSet properties from `tx.executeSqlAsync` function .

**Example:**
```
const dbtest = (): Promise<any> => {
  return new Promise((resolve, reject) => {
    DB.transactionAsync( async (tx) => {
        try {
            //  'rows' throws typescript error here.
            let { rows }  = await tx.executeSqlAsync(
                "SELECT id FROM test_table",
                []
            )
            resolve(rows)
        } catch (err) {
            console.log(err, 'my channel error')
            reject(err)
        }
    })
  })
}
```
Errors:
`Error: Property 'rows' does not exist on type 'ResultSetError | ResultSet'.`
This is also the same when attempting to access the 'error' property of ResultSetError .

This happens whenever attempting to access the 'rows' property from the result set .

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /opt/homebrew/bin/node
      npm: 9.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.6 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by Kudo** [comment]
hi! i think that's valid point. from #23751, i've changed the return type to `Promise<ResultSetError | ResultSet>`. maybe we should keep them as:

```ts
// `tx` is from `db.transactionAsync()`
tx.executeSqlAsync(...): Promise<ResultSet>

// low-level execAsync
db.execAsync(...): Promise<(ResultSetError | ResultSet)[]>
```

that would align to the synchronous versions. does that make sense?

**Comment by rp121** [comment]
> hi! i think that's valid point. from #23751, i've changed the return type to `Promise<ResultSetError | ResultSet>`. maybe we should keep them as:
> 
> ```ts
> // `tx` is from `db.transactionAsync()`
> tx.executeSqlAsync(...): Promise<ResultSet>
> 
> // low-level execAsync
> db.execAsync(...): Promise<(ResultSetError | ResultSet)[]>
> ```
> 
> that would align to the synchronous versions. does that make sense?

Changing these back seems to fix the errors I was having.
