### ISSUE TITLE
Android - Deep link isn't working if the app was opened before with deep link.

### ISSUE THREAD

**Issue by Jose2x** [expo/expo#2389]
### Environment
 OS: macOS High Sierra 10.13.6
 Node: 10.8.0
 Yarn: 1.9.4
 npm: 6.4.1
 Watchman: 4.9.0
 Xcode: Xcode 9.4.1 Build version 9F2000
 Android Studio: Not Found

Packages: (wanted => installed)
 expo: ^30.0.0 => 30.0.1
 react: 16.3.1 => Not Found
 react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Target: Android.

### Issue

I am developing a deep link in my app using Linking from react-native.

If the app is opened from the icon, every deep link (and doesn't matter how many times I click on it) gets registered.

If the app is opened from a deep link, next time I will click on the deep link it will not register.

I found a related android issue with a provided solution to use singleTop\task, but I can't fix without detaching.
https://stackoverflow.com/questions/35931028/android-deep-link-does-not-work-if-the-app-is-opened-by-deep-link-already

Please advice,
Thanks.

**Comment by esamelson** [comment]
Hi @Jose2x - sorry you're running into this 😞  Could you provide a way to reproduce this issue? An [MCVE](https://stackoverflow.com/help/mcve) would be really helpful, even if it's a [snack](https://snack.expo.io) that needs to be built into a standalone app in order to repro. Thanks very much!

**Comment by Jose2x** [comment]
hi, thanks.
I created a github repo with the complete example code.
just clone it and follow the instructions on the readme file.

git clone https://github.com/Jose2x/expoDeeplinkBug.git

repo:
https://github.com/Jose2x/expoDeeplinkBug

thanks again.

**Comment by Jose2x** [comment]
> Hi @Jose2x - sorry you're running into this 😞 Could you provide a way to reproduce this issue? An [MCVE](https://stackoverflow.com/help/mcve) would be really helpful, even if it's a [snack](https://snack.expo.io) that needs to be built into a standalone app in order to repro. Thanks very much!

reproduced above.

**Comment by Szymon20000** [comment]
I cannot reproduce the issue. Everything seems to work fine.  I tried on sdk 32. Probably the issue was eliminated between sdk 31 and sdk 32. Could you update to the latest sdk?
