### ISSUE TITLE
Support WebRTC

### ISSUE THREAD

**Issue by dangnelson** [expo/expo#239]
I know there's video & audio support currently, would this make WebRTC support possible?

[https://github.com/oney/react-native-webrtc](https://github.com/oney/react-native-webrtc)

**Comment by gkufera** [comment]
Hi @dangnelson!

We don't currently support WebRTC, and react-native-webrtc would not work with Expo right now unless you detached to ExpoKit and imported it there. We intend to implement WebRTC support on Expo, so stay tuned!

Thanks!

Greg

cc: @nikki93

**Comment by gkufera** [comment]
See here to upvote the WebRTC feature request for expo:
https://expo.canny.io/feature-requests/p/webrtc
