### ISSUE TITLE
Android 13 notification permissions starts off with "denied" status instead of "undetermined"

### ISSUE THREAD

**Issue by itsramiel** [expo/expo#23908]
### Minimal reproducible example

https://github.com/itsramiel/expo-notifications-android-permission

### Summary

I am getting the notification permissions on Android 13 and I am expecting the status initially to be `undetermined`, but instead it is `denied`, but the user never really denied any permission.

You can check this by running the example repo

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 9.7.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2023.04.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/ramiel/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    npmGlobalPackages:
      eas-cli: 3.17.0
      expo-cli: 6.3.10
    Expo Workflow: managed
    ````

**Comment by yubarajoli77** [comment]
Facing the same issue on `expo: 48.0.18`.

**Comment by id0Sch** [comment]
I'm facing the same issue using expo 49.
looking at the code seems that `managerCompat.areNotificationsEnabled` returns false, but we can actually ask for permissions and then send notifications.

**Comment by sraut1** [comment]
@itsramiel  were you able to resolve this? I am facing the same issue.

**Comment by shinework** [comment]
Same issue :)

**Comment by t0ma5h** [comment]
Same issue, reopen this

**Comment by armenavanesi** [comment]
Same issue

**Comment by appsgenie** [comment]
Has anyone found a good workaround for this?
My UI depends on the status and if we start with DENIED it yields a bad user experience via OS settings and back into the app.
Like @id0Sch mentioned, requesting permissions still works in this initial DENIED state but how do we actually check to know we can do this initially vs after a real denial.
Is there some kind of "canAsk" property to use?

**Comment by f-bog** [comment]
Same issue.

**Comment by appsgenie** [comment]
Is there a way to get this on Expo's radar?
It seems that the `canAskAgain` boolean is also `false`  in the initial state and we would have to rely on that to show a "try again" button even if the status is denied.
It's really a bad user onboarding flow and would mean less users will signup to notifications :(

**Comment by ktanoooo** [comment]
Same issue

**Comment by jurawrssic** [comment]
Same issue for the love of g0d

**Comment by dirkpostma** [comment]
Still an issue, can this ticket be reopened?

**Comment by coyksdev** [comment]
Same issue. Have you found a solution, @itsramiel ?

**Comment by SimonaKondelaTakeda** [comment]
I’m experiencing the same issue.  Please, have you found a solution, @itsramiel?

**Comment by awHamer** [comment]
I can see the same issue on expo 54.
Anyways it still allows you to request notification access
