### ISSUE TITLE
[expo-secure-store][iOS] - `User interaction is not allowed` after upgrading to SDK 49

### ISSUE THREAD

**Issue by AronBe** [expo/expo#23924]
### Minimal reproducible example

sorry, I haven't been able to reproduce it in the dev env

### Summary

Sentry is reporting quite many errors regarding setting and getting values via `expo-secure-store`. I have started notice those since upgrade to SDK 49 when going from `12.1.1` to `12.3.1`. Seems like Keychain does not allow interaction, but not sure why. I haven't changed any privileges  via secure store keychain config and calling it in the app as simply as  `await SecureStore.setItemAsync(REFRESH_TOKEN_KEY, token)`

```
Calling the 'setValueWithKeyAsync' function has failed → Caused by: User interaction is not allowed.

Calling the 'getValueWithKeyAsync' function has failed
→ Caused by: User interaction is not allowed.
```

I wonder if anyone else is experiencing this

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-32 | Desktop ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-33-ext5 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    Expo Workflow: bare

**Comment by leymytel** [comment]
Hi @AronBe !
I am experiencing the same issue. Did you have any luck with fixing this issue?

**Comment by AronBe** [comment]
Yeah, for set/get/delete actions I have added `AFTER_FIRST_UNLOCK`. I wonder if the default changed when the library got refactored to Expo Modules, hard to tell from the git history. But seems it is now working ok.

```
const defaultOptions: SecureStore.SecureStoreOptions = {
  keychainAccessible: SecureStore.AFTER_FIRST_UNLOCK,
}
```

**Comment by mmmguitar** [comment]
Yeah so looking at the new module I see [a default being set here](https://github.com/expo/expo/blob/cf94ec81b80892e360f413fc59f1dcbf245e65a0/packages/expo-secure-store/ios/SecureStoreModule.swift#L150-L151) to when unlocked but then again I see a similar default in the [being set in the old modules](https://github.com/expo/expo/blob/e68cb072a211aaf8ae709d8bfa88acca885b24e8/ios/versioned/sdk48/EXSecureStore/EXSecureStore/ABI48_0_0EXSecureStore.m#L154-L155)

Looking into the old module [quickly I see this](https://github.com/expo/expo/blob/0e2870dda14a04943f4e4ad5124c94e24fcbb380/packages/expo-secure-store/ios/EXSecureStore/EXSecureStore.m#L138C9-L138C9)

**Comment by mmmguitar** [comment]
Yeah so looking at the new module I see [a default being set here](https://github.com/expo/expo/blob/cf94ec81b80892e360f413fc59f1dcbf245e65a0/packages/expo-secure-store/ios/SecureStoreModule.swift#L150-L151) to when unlocked but then again I see a similar default in the [being set in the old modules](https://github.com/expo/expo/blob/e68cb072a211aaf8ae709d8bfa88acca885b24e8/ios/versioned/sdk48/EXSecureStore/EXSecureStore/ABI48_0_0EXSecureStore.m#L154-L155)

Looking into the old module [quickly I see this](https://github.com/expo/expo/blob/0e2870dda14a04943f4e4ad5124c94e24fcbb380/packages/expo-secure-store/ios/EXSecureStore/EXSecureStore.m#L138C9-L138C9).  Never done objective C but I think it may be masquarading an unset value to 0 here which would turn into after first unlock [according to the enumerations in the header file](https://github.com/expo/expo/blob/0e2870dda14a04943f4e4ad5124c94e24fcbb380/packages/expo-secure-store/ios/EXSecureStore/EXSecureStore.h#L7C3-L7C42)

I see in expo 48 and 49 there is [a documented intention](https://github.com/expo/expo/blob/0e2870dda14a04943f4e4ad5124c94e24fcbb380/packages/expo-secure-store/src/SecureStore.ts#L85) in the JS to default to 'WHEN_UNLOCKED'.

It looks like this may have been a bug in expo 48 where they intended to default to WHEN_UNLOCKED but inadvertently defaulted to AFTER_FIRST_UNLOCK given the way objective c handles unset ints in switches.  Then when they rewrote the module in swift in expo 49 swift works differently in the way it doesnt convert nil to 0, rather it triggers the default case as originally intended.

I never programmed swift or objective C so pinch of salt...  But yeah it seems the default behaviour was inadvertently broken then inadvertently fixed...

**Comment by Bardiamist** [comment]
I use `SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY`.
My users see this error as `Calling the 'setValueWithKeyAsync' function has failed → → Caused by: No keychain is available. You may need to restart your computer.`

Would be good to merge https://github.com/expo/expo/pull/24831 into `expo-secure-store` in SDK 49 branch and release new version.
For now I'll use patch [expo-secure-store+12.5.0.patch](https://github.com/expo/expo/files/13347304/expo-secure-store%2B12.5.0.patch).

**Comment by landabaso** [comment]
I am also experiencing some related weird behaviour.

Using `"expo-secure-store": "~12.8.1"` and `"expo": "^50.0.4"`, this will throw:

```typescript
import {  AFTER_FIRST_UNLOCK } from 'expo-secure-store';
if (AFTER_FIRST_UNLOCK === undefined)
  throw new Error('AFTER_FIRST_UNLOCK not defined');
```

The weird thing is typescript linter does not report any error. In fact it reports AFTER_FIRST_UNLOCK to be a number.
But in the runtime it is `undefined` for some reason.

**Comment by statico** [comment]
FWIW, we had to use `SecureStore.AFTER_FIRST_UNLOCK` to get past this error.

**Comment by AlexCatch** [comment]
This is still occurring even after specifying `SecureStore.AFTER_FIRST_UNLOCK`

```typescript
const saveToSecureStore = (key: string, value: string): Promise<void> => {
  return SecureStore.setItemAsync(key, value, {
    keychainAccessible: SecureStore.AFTER_FIRST_UNLOCK,
  });
};
```

**Comment by statico** [comment]
@AlexCatch We had to instruct some users to uninstall the app and reinstall it in order for `AFTER_FIRST_UNLOCK` to start working.

**Comment by QuintenJustus** [comment]
@statico even with a new build, clean installs, this error still occurs when the app has gone to the background, was really hoping your solution would be the one! Thank you nonetheless.

@behenate can you clarify anything regarding this issue?

**Comment by behenate** [comment]
@QuintenJustus You might need to create a list of all possible keys and loop through them calling `deleteItemAsync` if you are unable to read them.  This is because iOS will actually often keep the keychain data between app installs (see [this](https://forums.developer.apple.com/forums/thread/36442) thread).

**Comment by QuintenJustus** [comment]
@behenate thank you for the quick reply, however with clean install I also meant that a different phone with a different (iCloud) account was used. No chance of data contamination.

I can't seem to find anything that suggests it was changed, SecureStoreModule.swift::12 has the correct value as does SecureStoreAccessible.swift::4. It does default to .whenUnlocked.

**Comment by arapocket** [comment]
Mine doesn't work even if i have `SecureStore.ALWAYS`

**Comment by wsdt** [comment]
same here, crashing with SecureStore.ALWAYS

**Comment by captncanary** [comment]
I'm experiencing this same issue after upgrading to expo-50 and expo-secure-store 13.0.2. The problem occurs when trying to access values while the phone is locked.
Error: Calling the 'getValueWithKeyAsync' function has failed
→ Caused by: User interaction is not allowed.
Fresh install does not help. We are using keychainAccessible: SecureStore.AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY

**Comment by juanvelozo** [comment]
Any update about this? 
I'm getting the following error in sentry: 
```
Error: Calling the 'setValueWithKeyAsync' function has failed
→ Caused by: User interaction is not allowed.
```
The error appears exclusively on iOS devices.

These are my current versions: 
```
"expo-secure-store": "~12.8.1",
"expo": "~50.0.20",
```

**Comment by leymytel** [comment]
Have you tried to migrate to a new key store?
Maybe my use case was a bit different, but after adding this code to migrate from the old keychain settings to the new one, I didn't have any issues.

```typescript

import 'react-native-get-random-values';
import * as SecureStore from 'expo-secure-store';

enum STORE_KEY_OLD {
  DEVICE_ID = 'DEVICE_ID',
  JWT_STORAGE = 'JWT',
}

enum STORE_KEY {
  DEVICE_ID = 'DEVICE_ID_V2',
  JWT_STORAGE = 'JWT_V2',
}

const STORE_KEY_TO_STORE_KEY_OLD: Record<STORE_KEY, STORE_KEY_OLD> = {
  [STORE_KEY.DEVICE_ID]: STORE_KEY_OLD.DEVICE_ID,
  [STORE_KEY.JWT_STORAGE]: STORE_KEY_OLD.JWT_STORAGE,
};

const secureStoreOptions: SecureStore.SecureStoreOptions = {
  keychainAccessible: SecureStore.AFTER_FIRST_UNLOCK,
};

/**
 * Fetches a value from SecureStore with error handling.
 */
export const getSecureStoreItemAsync = async (
  key: STORE_KEY | STORE_KEY_OLD,
  options?: SecureStore.SecureStoreOptions,
) => {
  try {
    return await SecureStore.getItemAsync(key, options);
  } catch (error) {
      console.error(`Error fetching key "${key}":`, error);
      return null;
  }
};

/**
 * Wrapper to handle key migration from old to new keys.
 */
export const getSecureStoreItemAsyncWrapper = async (key: STORE_KEY) => {
  // Attempt to fetch the value using the current key
  const value = await getSecureStoreItemAsync(key, secureStoreOptions);

  if (value) {
    return value;
  }

  // Fallback to the old key if it exists
  const oldKey = STORE_KEY_TO_STORE_KEY_OLD[key];

  if (!oldKey) {
    return;
  }

  const oldValue = await getSecureStoreItemAsync(oldKey);

  if (oldValue) {
    // Migrate the value to the new key and clean up the old key
    await SecureStore.setItemAsync(key, oldValue, secureStoreOptions);
    await SecureStore.deleteItemAsync(oldKey);

    return oldValue;
  }
};

// Access token methods
export const getAccessToken = async () =>  
 getSecureStoreItemAsyncWrapper(STORE_KEY.JWT_STORAGE);
export const setAccessToken = (accessToken) =>
  SecureStore.setItemAsync(STORE_KEY.JWT_STORAGE, accessToken, secureStoreOptions);
export const deleteAccessToken = () =>
  SecureStore.deleteItemAsync(STORE_KEY.JWT_STORAGE, secureStoreOptions);

```
