### ISSUE TITLE
unsupported Swift architecture

### ISSUE THREAD

**Issue by fruity4pie** [expo/expo#23939]
### Summary

<img width="1162" alt="image" src="https://github.com/expo/expo/assets/15814446/3ea685dc-0bbe-4813-9d20-087371c86df7">

### What platform(s) does this occur on?

By running **npx expo run:ios**.

Running **npx expo prebuild --clean** works fine. I'm able to up the project after this script.

### SDK Version

49

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
      Yarn: 3.6.1 - ~/.nvm/versions/node/v20.5.0/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.0/bin/npm
      Watchman: 2023.07.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.6 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    npmGlobalPackages:
      eas-cli: 3.16.0
    Expo Workflow: bare

### Minimal reproducible example

Upgraded from 48 to 49. Faced the issue.

My deps:

  "dependencies": {
    "@expo-google-fonts/andika": "^0.2.3",
    "@expo/vector-icons": "^13.0.0",
    "@reduxjs/toolkit": "^1.9.5",
    "@tamagui/animations-moti": "^1.52.2",
    "@tamagui/animations-react-native": "^1.52.2",
    "@tamagui/config": "^1.52.2",
    "@tamagui/shorthands": "^1.52.2",
    "@tamagui/themes": "^1.52.2",
    "expo": "~49.0.6",
    "expo-constants": "~14.4.2",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-location": "~16.1.0",
    "expo-router": "2.0.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "immer": "^10.0.2",
    "lodash-es": "^4.17.21",
    "ramda": "^0.28.0",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-maps": "1.7.1",
    "react-native-mmkv": "^2.10.1",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-redux": "^8.1.2",
    "redux-persist": "^6.0.0",
    "tamagui": "^1.52.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@tamagui/babel-plugin": "^1.52.2",
    "@types/lodash-es": "^4.17.7",
    "@types/ramda": "^0.28.23",
    "@types/react": "~18.2.14",
    "@types/uuid": "^9.0.1",
    "@typescript-eslint/eslint-plugin": "^6.3.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "eslint": "^8.45.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-import-resolver-typescript": "^3.6.0",
    "eslint-plugin-import": "^2.28.0",
    "eslint-plugin-prettier": "5.0.0",
    "eslint-plugin-react": "^7.33.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "expo-dev-client": "^2.4.6",
    "prettier": "^3.0.0",
    "react-devtools": "^4.27.2",
    "typescript": "^5.1.3"
  }

**Comment by fruity4pie** [comment]
after initializing a new project by `npx create-expo-app` and moving the codebase got this during `yarn ios`:

<img width="1012" alt="image" src="https://github.com/expo/expo/assets/15814446/1d240184-f1f0-46ad-a883-58b01d421d69">

**Comment by Kudo** [comment]
hi there! could you try to create a minimal reproducible example and upload to some git repositories?

as the `could not find module 'ExpoModulesCore' for the target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator` message, i'm wondering that's some xcode setting issue. would like to help investigation if you could share your example.

**Comment by yhostc** [comment]
I also encountered this problem. The default architecture in Expo is i386. Since the simulator is arm64 architecture, there is a conflict. You can open xcode and add arm64 next to i386 architecture.

**Comment by JACA26** [comment]
i also have this problem when i run  "npx expo run:ios", any solutions?

**Comment by smalik02** [comment]
@JACA26 did you come across any solutions?

**Comment by JACA26** [comment]
> @JACA26 did you come across any solutions?

yes, at least work for me

1) create a file in root project (ej: ios-build-plugin.js)
2) paste this fix https://github.com/expo/expo/issues/15800#issuecomment-1537149496
3) in your app.json add the path
<img width="276" alt="image" src="https://github.com/expo/expo/assets/63484827/4267572f-7789-461f-ad3f-370113be52f5">
4) delete the ios/ folder en re run "npx expo run:ios"
