### ISSUE TITLE
[docs] explanation for cache in FileSystem.DownloadOptions missing

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#23944]
### Summary

What is the purpose of the `cache` property there? I'm happy to submit a PR but I'm not sure what this does.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/filesystem/#downloadoptions

**Comment by RRaideRR** [comment]
The docs are still not updated

**Comment by RRaideRR** [comment]
The docs are not updated yet

**Comment by RRaideRR** [comment]
The docs are not updated yet

**Comment by bentburton** [comment]
Any progress here? I am wondering what this does also
