### ISSUE TITLE
Audio `sound.unloadAsync()` not unload the audio on IOS system

### ISSUE THREAD

**Issue by anasalaqeel** [expo/expo#23945]
### Minimal reproducible example

https://snack.expo.dev/@anasalaqeel/audio-test?platform=ios

### Summary

Hi 

I'm using Expo SDK 49 with the latest Audio package `expo-av` but the sounds not working properly when it comes to unloading the audio subscription using `await sound.unloadAsync()` on IOS. 

the problem is whenever there is any other app on the device playing sounds e.g. Youtube Music and I play sound at the expo app at the same time e.g Notification sound and then minimized the expo app, the Youtube Music sound suddenly stopped for no reason, all device playable audio stops suddenly in general.

Here is a full working example
```js
import { Text, SafeAreaView, StyleSheet, Button } from 'react-native';
import React, { useState, useEffect, useRef } from 'react';
import { Audio, InterruptionModeIOS } from 'expo-av';
import { Card } from 'react-native-paper';

const sound = new Audio.Sound();

export default function App() {
  const [isSoundFinish, setIsSoundFinish] = useState(false);

  useEffect(() => {
    (async function () {
      if (isSoundFinish) {
        try {
          await sound.unloadAsync();
          console.log("unloaded");
        } catch (error) {
          console.log(error);
        }
        setIsSoundFinish(false);
      }
    })();
  }, [isSoundFinish]);

  async function playSound() {
    try {
      await Audio.setAudioModeAsync({
        interruptionModeIOS: InterruptionModeIOS.DuckOthers,
        playsInSilentModeIOS: true,
        staysActiveInBackground: false,
        allowsRecordingIOS: false,
      });
      await sound.loadAsync(require("./assets/finish-bell-notification.mp3"));
      sound.setOnPlaybackStatusUpdate((status) => {
        if (status.isLoaded && status.didJustFinish) {
          setIsSoundFinish(true);
        }
      });

      await sound.playAsync();
    } catch (error) {
      console.log(error);
    }
  }

  function handlePressPlay() {
    playSound();
  }

  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.paragraph}>Click the button to play sound</Text>
      <Card>
        <Button title="Play sound" onPress={handlePressPlay} />
      </Card>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: managed

**Comment by mikekreeki** [comment]
Confirming the issue. When the app is backgrounded any time later after playing a sound with `expo-av`, it stops background music (in my case, Spotify). I have just a one-second audio bell after some action and it's a bit annoying (several users reported the issue in my app).

**Comment by anasalaqeel** [comment]
This issue still exists, the latest merge does not solve it

**Comment by anasalaqeel** [comment]
@alanjhughes This issue still exists, the latest merge does not solve it

**Comment by alanjhughes** [comment]
Are you testing on a dev build or expo go?

**Comment by anasalaqeel** [comment]
I'm on expo go

**Comment by alanjhughes** [comment]
Expo go doesn't receive these types of fixes. You'll need a dev client to use the latest package releases

**Comment by anasalaqeel** [comment]
@alanjhughes Thank you for your efforts. I tested it after the build and it works but with a slight bug, which is when using `interruptionModeIOS: InterruptionModeIOS.DuckOthers` attribute it ducks other apps forever unless I send the app to the background and then to the foreground again

I'm using this code:
```js
await Audio.setAudioModeAsync({
        interruptionModeIOS: InterruptionModeIOS.DuckOthers,
        playsInSilentModeIOS: true,
        staysActiveInBackground: false,
        allowsRecordingIOS: false,
      });
```

**Comment by ngm01** [comment]
**Minimal reproducible example:**
https://snack.expo.dev/@ngm01/a8fe08

So this issue does not appear to be resolved. Just to re-iterate what the problem is: when an Expo app plays a sound with `expo-av`, and then the user backgrounds the app, any other app playing sound in the background (e.g. Spotify playing music) has its sound paused. The issue is present in both managed and bare workflows. Time elapsed between Expo app playing sound and being backgrounded doesn't affect behavior. 
Running the snack linked above through Expo Go will reproduce the issue. For sake of completeness here's the env info for my actual project:

`"expo-av": "~13.0.3"`

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      expo: ~47.0.14 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: bare
``` 

Thanks!

**Comment by alanjhughes** [comment]
Hi @ngm01 - can you use `13.6.0` and try again?

**Comment by ngm01** [comment]
Hi @alanjhughes, thanks for your response. I updated expo-av to `13.6.0` in this snack: https://snack.expo.dev/@ngm01/a8fe08, ran it through Expo Go, unfortunately no change in behavior. 

Side note, the update also produced a warning in package.json that `'expo-av@~13.6.0' is not the recommended version for SDK 49.0.0` and a recommendation to use `~13.4.1`. Warning is present regardless of which SDK I select.

**Comment by alanjhughes** [comment]
Hi @ngm01 - this change won't be available in expo go. Expo go is not updated frequently as it's not a recommended tool to develop your entire project with that. You'll need to use a dev client.

**Comment by anasalaqeel** [comment]
@ngm01 if you use the update 13.6.0 with Expo Go, the issue will still exist but after the build, the problem will be resolved. regarding the warning `expo-av@~13.6.0' is not the recommended version for SDK 49.0.0` I just skipped it, everything working fine, it's just because the expo team didn't update the compatibility of the `expo-av`

**Comment by ngm01** [comment]
@alanjhughes Sorry for the delayed response, ran into some build problems, but yes, using dev client, updating `expo-av` to `13.6.0` did resolve the sound cut off issue. Thanks again for your help.
