### ISSUE TITLE
SplashScreen auto-hides when using Expo Router

### ISSUE THREAD

**Issue by thewalrusisben** [expo/expo#23958]
### Minimal reproducible example

https://github.com/thewalrusisben/expo-router-splash-reproduction

### Summary

When following the example for preventing auto-hide on a splash screen found [here](https://docs.expo.dev/versions/latest/sdk/splash-screen/), the example works as expected. When the application uses expo router and loads the application from the App directory, however, the SplashScreen is automatically hidden. I have tried this in the way that's shown in the linked reproduction, and also by changing the index.js file so ExpoRoot is used, which I thought might give me more control over calling preventAuthHideAsync from within that root index.js file.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 3.5.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.16.1 - ~/.local/share/nvm/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.node_modules/bin/yarn
      npm: 9.5.1 - ~/.local/share/nvm/v18.16.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.3 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed

**Comment by zRelux** [comment]
You need to use splash screen from expo router https://docs.expo.dev/routing/appearance/

**Comment by JoshBot-Debug** [comment]
```ts
import { SplashScreen } from "expo-router";
```
That should solve your problem

**Comment by marklawlor** [comment]
As others have mentioned, `expo-router` uses its own `SplashScreen` and you should export it from the `expo-router` package.

**Comment by nguyenduy7474** [comment]
> ```ts
> import { SplashScreen } from "expo-router";
> ```
> 
> That should solve your problem

Correct answer for who use expo-router
