### ISSUE TITLE
POCO X3 NFC cannot run Expo Go

### ISSUE THREAD

**Issue by KangLeian** [expo/expo#23953]
### Minimal reproducible example

Facing Apps Expo Go on My Android not working

### Summary

 Hi, Can anyone help me with my expo go or should I use another environment?
 
 
![6a120d20-d95b-4485-9b0c-0bb1298ba322](https://github.com/expo/expo/assets/62584211/4fff18c3-5b19-4ef8-8ede-52565b15d669)

As like in the image. My Expo just stuck there.
There is no such menu showing up on my Expo.

Here are my Expo details,
![32e402a8-bf70-4401-b1b3-cf70679fe45c](https://github.com/expo/expo/assets/62584211/352a2940-6f73-4354-9c6a-f267655790f3)
![218b9788-744b-4d1f-89af-ebb3fea7f481](https://github.com/expo/expo/assets/62584211/17c6f150-9fc1-42c0-8550-1ee43c8a0693)

I'm using Xiaomi Poco NFC X3. Is there any trouble with my device? Should I change the method The way I'm working with? Or is there any help to make it work on my phone? or is there pricing for using the mobile Expo Go?

### Environment

It's a Non-Development issue. just Reporting It's not working on my device and asking what should I do.

**Comment by behenate** [comment]
"Restrict data usage" option seems to be on, can you try turning it off and re-launching expo go?

**Comment by KangLeian** [comment]
still not working,
It seems "Restrict data usage" on my phone has an inverted UI.
![181902a5-c82f-4337-be79-1637d4800d9f](https://github.com/expo/expo/assets/62584211/727f5cb2-fd54-4ea6-88ce-d819d0ffc1a6)

And when uncheck the list it said "Don't Allow"
![cfa7c92a-bdb5-48c4-bb98-da25e08a3e6d](https://github.com/expo/expo/assets/62584211/bc1be18e-26d5-44b6-9bc0-c020f295b9d7)

It ends up like this
![fcb349f2-1361-48da-a67f-258a2c16065e](https://github.com/expo/expo/assets/62584211/a7ca02e5-227b-4b2b-a946-6ddd767f9c77)

**Comment by brentvatne** [comment]
what do you see if you press "View error log"?

**Comment by KangLeian** [comment]
This message appears
<code>Fatal Error: Expo requires an internet connection</code>
![fa0758e7-83fd-4dea-bc1c-0d5efd2ee0d4](https://github.com/expo/expo/assets/62584211/7eed0683-f425-4f07-ae01-5e350262780e)
