### ISSUE TITLE
Expo Camera not working on web

### ISSUE THREAD

**Issue by Malivuca** [expo/expo#23966]
### Minimal reproducible example

1. Run: npx create-expo-app@latest --template tabs@49 ---- 2. Run npx expo install expo-camera --- 3. Import Camera from "expo-camera" and render the camera in /app/(tabs)/index.tsx 4. Run npm run web

## Expected behavior 
Web app should run with no problems

## Actual behavior
Web bundling error: Unable to resolve "@koale/useworker" from "node_modules/expo-camera/build/useWebQRScanner.js"

![image](https://github.com/expo/expo/assets/48441789/fe85d81d-62df-4b01-afa3-ea7f45a5eb87)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    npmPackages:
      expo: ~49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: managed

**Comment by HugDoggyDogg** [comment]
I do encounter this issue as well while upgrading to SDK49.
expo-camera v13.4.2

**Comment by HugDoggyDogg** [comment]
@Malivuca, I believe the issue will be resolved soon, as they removed the dependency in that PR merged tonight : https://github.com/expo/expo/pull/23967
I don't know how long it takes to come into production after it was merged on their `main` branch tho.
