### ISSUE TITLE
expo-sqlite has inconsistent SQLite versions across iOS and Android 

### ISSUE THREAD

**Issue by derekstavis** [expo/expo#23970]
### Minimal reproducible example

https://snack.expo.dev/@derekstavis/expo-sqlite-version-inconsistency

### Summary

`expo-sqlite` uses a [hardcoded version](https://github.com/expo/expo/blob/main/packages/expo-sqlite/ios/ExpoSQLite.podspec#L18C38-L18C38) of SQLite on iOS, while on Android it uses the version bundled with Android.

This results in inconsistencies across platforms, where certain features that are seemingly supported on iOS cause an error on Android.

Run the reproduction Snack on both platforms, and:
1. the `sqlite_version()` query will return a different version on iOS and Android
2. the `unixepoch()` query will return a successful result on iOS
3. the `unixepoch()` query will return an error on Android

### Expectation

I expected both platforms to have consistent SQLite version, and thus result in consistent features and behavior across platforms.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
      Watchman: 2023.05.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/lib/ruby/gems/3.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
we're moving away from using the system version in sdk 50 (and in the alpha package released from `main`) so this should be solvable now

**Comment by peterferguson** [comment]
> we're moving away from using the system version in sdk 50 (and in the alpha package released from `main`) so this should be solvable now

interested in the thought process behind moving off the system version ... is there anywhere I can read about it?

**Comment by brentvatne** [comment]
@derekstavis - not yet, @alanjhughes is working on the android side at the moment

@peterferguson - the system version is fairly out of date and doesn't support sqlite extensions - https://github.com/expo/expo/pull/23791

**Comment by derekstavis** [comment]
For anyone interested in the `patch-package` patch, here it goes. Literally a copy and paste from #23993:

```patch
diff --git a/node_modules/expo-sqlite/android/build.gradle b/node_modules/expo-sqlite/android/build.gradle
index 60b1031..02b61ac 100644
--- a/node_modules/expo-sqlite/android/build.gradle
+++ b/node_modules/expo-sqlite/android/build.gradle
@@ -81,6 +81,7 @@ android {
 
 dependencies {
   implementation project(':expo-modules-core')
-
+  implementation 'com.github.requery:sqlite-android:3.39.2'
+  implementation "androidx.sqlite:sqlite-ktx:2.3.1"
   implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${getKotlinVersion()}"
 }
diff --git a/node_modules/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt b/node_modules/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt
index 49953bc..4472c56 100644
--- a/node_modules/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt
+++ b/node_modules/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt
@@ -3,7 +3,7 @@ package expo.modules.sqlite
 
 import android.content.Context
 import android.database.Cursor
-import android.database.sqlite.SQLiteDatabase
+import io.requery.android.database.sqlite.SQLiteDatabase
 import expo.modules.kotlin.exception.Exceptions
 import expo.modules.kotlin.modules.Module
 import expo.modules.kotlin.modules.ModuleDefinition
@@ -77,7 +77,7 @@ class SQLiteModule : Module() {
           if (bindArgs[i - 1] == null) {
             statement.bindNull(i)
           } else {
-            statement.bindString(i, bindArgs[i - 1])
+            statement.bindString(i, bindArgs[i - 1]!!)
           }
         }
       }
```
