### ISSUE TITLE
Tunnel not starting with no reasons...

### ISSUE THREAD

**Issue by elcitrovmtgrande** [expo/expo#2397]
Hi guys,

I am doing the expo start on my new project. And everything is working, but it is impossible to connect my phone to the project by the Expo app (i get a timeout) because it seems as the tunnel doesnt start...

![image](https://user-images.githubusercontent.com/39875237/46762004-3c356500-ccd6-11e8-98b6-354e157c7d5c.png)

Do you have an idea ? Please...

**Comment by adonandal** [comment]
Hi,

Make sure you are one the same network on your mobile as your pc. 

From the image you attached, it looks like you are on LAN and not Tunnel.

**Comment by sjchmiela** [comment]
Good catch, @adonandal! If you cannot connect the phone to the same Wi-Fi network as your computer you should be able to change the connection type to <kbd>Tunnel</kbd> by clicking that button in the left sidebar or by running `expo start --tunnel`. 🙂

**Comment by elcitrovmtgrande** [comment]
Hi,

First thank you for helping. But it seems that it doesnt solve anything...
As you can see, I am in Tunnel, and Metro is giving an error...
![image](https://user-images.githubusercontent.com/39875237/46817487-7575df80-cd7f-11e8-941c-abcfc6bdbf75.png)

![image](https://user-images.githubusercontent.com/39875237/46817526-7eff4780-cd7f-11e8-8f32-9eee085a78b7.png)

**Comment by sjchmiela** [comment]
After a bit of debugging I found it may be caused by the user (i. e. you or me) being not logged in. Try running `expo whoami` to find out whether you're logged in and if you're not, run `expo login` and log in! `expo start --tunnel` should work properly then.

**Comment by citrovsandbox** [comment]
> After a bit of debugging I found it may be caused by the user (i. e. you or me) being not logged in. Try running `expo whoami` to find out whether you're logged in and if you're not, run `expo login` and log in! `expo start --tunnel` should work properly then.

@sjchmiela Ty so much ! You were right ! That was the reason and now it is working ! Thank you mate !

**Comment by sjchmiela** [comment]
Glad to hear it! 🙂
