### ISSUE TITLE
web platform - chrome debugger reports wrong variable names and current line number

### ISSUE THREAD

**Issue by OneHatRepo** [expo/expo#23990]
### Minimal reproducible example

git@github.com:OneHatRepo/test-debugger.git

### Summary

When debugging an Expo for Web app, the Chrome debugger highlights the incorrect line in source code, and messes up the variable names. See screenshot.

Line 11 should be highlighted as the current row with the **debugger;** statement. Instead, line 14 is highlighted.
Also, the variable names are all messed up. Somehow variable "c" is shown as "const" and variable "e" is shown as "style".

<img width="1724" alt="Screenshot 2023-08-16 at 1 13 39 PM" src="https://github.com/expo/expo/assets/13893545/08181524-0aa3-45d9-ae2f-2ccd5115ac58">

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
      npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: managed

**Comment by OneHatRepo** [comment]
I did a little more digging, and by adding the following as a devDependency:

    "@expo/metro-config": "^0.7.1"

which reverts metro-config to an older version, the problems go away. 

<img width="1720" alt="Screenshot 2023-08-17 at 6 02 30 AM" src="https://github.com/expo/expo/assets/13893545/50c592b4-fd7d-4405-90fa-ed4f1fe4cab3">

**Comment by EzioLi01** [comment]
Same issue in other platforms debugging.

**Comment by EvanBacon** [comment]
If I were to guess, it's [due to this](https://github.com/expo/expo/blob/fd82a25129144c7ace033db6b0f90570e5a5d304/packages/%40expo/metro-config/src/serializer/environmentVariableSerializerPlugin.ts#L105).

**Comment by OneHatRepo** [comment]
Still an issue, and I'm having to use the downgraded metro config in order to keep working.

**Comment by DiasNetoJ** [comment]
Same problem here.

**Comment by TheEhsanSarshar** [comment]
is there any update on this?

**Comment by appsgenie** [comment]
HI, looking for an update on this as well, as currently am unable to normally debug an expo SDK 49 managed app with hermes :(

**Comment by appsgenie** [comment]
Keeping this alive as it's still an issue with SDK 50 for me.
Unable to reliably debug with Chrome Dev tools (but even with VS Code).
Both iOS and Android are showing undefined variables, while breakpoints appear disabled.
