### ISSUE TITLE
expo-updates functions are not "enabled"

### ISSUE THREAD

**Issue by sylvaindubus** [expo/expo#23999]
### Minimal reproducible example

https://github.com/sylvaindubus/expo-minimal-repro-eas-update

### Summary

Hello,

After upgrading from Expo 46 to Expo 49, I'm struggling with a strange crash occurring while trying to access to `expo-updates` functions, such as `checkForUpdateAsync` or `fetchUpdateAsync`.

I've wrapped these calls in a try/catch like this:
```jsx
    try {
      await checkForUpdateAsync()
    } catch (e) {
      Alert.alert(e.message)
      return false
    }
```

And it gives me the following message: `checkForUpdateAsync() is not enabled`.

Of course, it doesn't occur in development because I don't call these functions in this case.
But an interesting fact: it **works on Android**. It **crashes only on iOS**.

I've managed to shrink my project to the maximum, you can check this repo: https://github.com/sylvaindubus/expo-minimal-repro-eas-update.

Here is the custom hook I'm using to manage updates:
```jsx
import { createContext, ReactNode, useState } from "react"
import { Alert } from "react-native"
import { checkForUpdateAsync, fetchUpdateAsync, reloadAsync } from "expo-updates"
import Constants from "expo-constants"

export enum UpdateStatus {
  Unchecked = "unchecked",
  CannotCheckUpdate = "cannotCheckUpdate",
  NeedManualUpdate = "needManualUpdate",
  NeedAutoUpdate = "needAutoUpdate",
  UpToDate = "upToDate",
}

type ContextType = {
  status: UpdateStatus
  check: () => Promise<boolean>
}

const Context = createContext<ContextType>({
  status: UpdateStatus.Unchecked,
  check: async () => true,
})

export const ContextProvider = ({ children }: { children: ReactNode }) => {
  const [status, setStatus] = useState(UpdateStatus.Unchecked)

  const check = async () => {
    if (__DEV__) return true

    const config = { min_version: "1.0.0" }
    const minVersion = config?.min_version
    const currentVersion = Constants?.expoConfig?.version
    if (!minVersion || !currentVersion) {
      setStatus(UpdateStatus.CannotCheckUpdate)
      return false
    }

    if (currentVersion < minVersion) {
      setStatus(UpdateStatus.NeedManualUpdate)
      return false
    }

    try {
      await checkForUpdateAsync()
    } catch (e) {
      Alert.alert(e.message)
      return false
    }

    const { isAvailable } = await checkForUpdateAsync()
    if (isAvailable) {
      setStatus(UpdateStatus.NeedAutoUpdate)

      fetchUpdateAsync().finally(() => {
        reloadAsync()
      })

      return false
    }

    setStatus(UpdateStatus.UpToDate)
    return true
  }

  return <Context.Provider value={{ status, check }}>{children}</Context.Provider>
}

export const ContextConsumer = Context.Consumer

export default Context
```

Any help would be quite appreciated. 🙏 

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.10.7 => 0.10.7 
      expo: ~49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.15.1
    Expo Workflow: managed

**Comment by douglowder** [comment]
Hmm you should not see the "is not enabled" error unless you are attempting to run this code in Expo Go.

Thanks for the repro, we will take a look.

**Comment by sylvaindubus** [comment]
Hello @douglowder,

Indeed, it happens when I run the code in Expo Go.

Basically, these are the steps:
* Run `ENV=kenny eas update` (the ENV variable is used to retrieve several variables, not sure it's meaningful here but I've let it in the minimal repo anyway)
* Go to expo.dev using the provided link
*  Scan the QR code using the real device's camera

**Comment by douglowder** [comment]
Sadly the `checkForUpdateAsync` and `fetchUpdateAsync` APIs are not available in Expo Go for iOS.

**Comment by sylvaindubus** [comment]
@douglowder Alright, that makes sense anyway, thanks for clarifying it.

But it was perfectly working on Expo <= 46.
How and when did this change? I might have missed it in breaking changes notes.
