### ISSUE TITLE
splash.resizeMode = 'cover' in app.json causes app not to adjust when Galaxy S8/9 hide navigation bar feature is used

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#2399]
### Environment

Environment:
  OS: macOS 10.14
  Node: 8.12.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/llamaluvr-20ae7943-0e96-4949-97ab-d749dcb35bad.tar.gz

App target:
- standard Expo or Expokit
- Android
- Galaxy S8 / other phones that have the ability to hide the Android navigation bar (the bar at the bottom with back/ home/ multitask buttons). This includes at least the Galaxy S9.

### Background
This dot on the left side of the navigation bar on the Galaxy S8 and S9 (and maybe others) can be double-tapped to hide the nav bar. Then you swipe up to temporarily show the nav bar. If you double-tap the dot again, the nav bar will go back to the default "anchored" position on the screen. To my knowledge, there is no way to disable this dot on a per-app basis. I can't even find a way to hide the dot to keep me from accidentally pressing it. In short, it's the new reality for some of the most popular phones in the world.
![screen shot 2018-10-10 at 10 18 56 pm](https://user-images.githubusercontent.com/8053974/46776670-ac45ea00-ccda-11e8-868f-84f111f7dd4f.png)

Depending on the splash.resizeMode setting in app.json, double-tapping this dot can leave a blank space at the bottom of the screen or hide part of your app's UI. Additionally, if you use a keyboard spacer to move the UI out of the way when the keyboard is up, the spacer can't tell how large the keyboard is when the nav bar is hidden. (Long story about why keyboard spacers are used, but it boils down to `android:windowSoftInputMode="adjustResize"` not working with translucent status bars and the correct usage of `KeyboardAvoidingView` being a total mystery to us mere mortals).

### Steps to Reproduce

1. Create an Expo app. App should have splash.resizeMode = 'cover' and a translucent status bar (e.g., no status bar color on Android). No matter what else is in your code, this should reproduce the issues where the app does not expand/ shrink as the navigation bar is hidden or anchored.
2. If you'd like to see how this affects adjusting an app as the keyboard is displayed, code should have the ability to pop up the keyboard and a spacer that occupies the keyboard's space when the keyboard is open (e.g., react-native-keyboard-spacer). Using react-native-gifted-chat for the rest of the UI is recommended because it's a great example of something at the bottom of the screen that should hug the top of the keyboard.
3. Build a standalone app. This issue cannot be reproduced in the Expo client!
4. Run the app on a Galaxy S8/9
5. Double-tap the dot on left of the navigation bar to hide it. (the app will not take up the additional space left behind after the navigation bar is hidden).
6. Close the app and reopen it (app should take up additional space now).
7. Open the keyboard (e.g., tap on a textinput). Some of the UI will be covered despite the keyboard spacer.
8. Swipe up from the bottom, double-tap the dot on the left of the navigation bar to anchor it. (the navigation bar will now cover some of the UI)

### Expected Behavior

When hiding the navigation bar, the app should automatically expand to take up the extra space.
When anchoring the navigation bar after it was hidden, the app should automatically shrink to adjust to the shorter space.
In all cases, the keyboard spacer should take up only the space occupied by the keyboard.

### Actual Behavior

- When hiding the navigation bar, the app does not take up the extra space. A bar below the app the size of the navigation bar remains (the color matches the splash background color).
- If you close and reopen the app, the app will then take up the extra space, but the keyboard spacer is only as tall as the keyboard itself, and thus some of the UI is hidden behind the keyboard, as the keyboard popping up also causes the navigation bar to reappear.
- If you then anchor the navigation bar again after opening the app the second time, the navigation bar just covers the bottom of the app.

Simply changing the splash.resizeMode to 'contain' in app.json causes the actual behavior to match the expected behavior.

Note that the part about react-native-keyboard-spacer is more about illustrating that the issue goes beyond an app just getting out-of-whack until the next restart than debugging the particulars of that library. It could probably do some things better, but the library's method of determining keyboard height seems sound, and this bug is throwing off that calculation. Basically, it takes the top Y coordinate of the keyboard and subtracts it from `Dimensions.get('window').height` to determine the space taken by the keyboard. In "cover" mode, the window height value isn't getting larger when the nav bar is hidden.

When splash.resizeMode = cover (doesn't work as expected): 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8053974/46776110-2b85ee80-ccd8-11e8-94e2-fcebe6b0a31f.gif)

When splash.resizeMode = contain (works as expected):
![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/8053974/46776223-aea74480-ccd8-11e8-97a9-e607c83d1069.gif)

### Reproducible Demo

Example repo reproducing the issue: https://github.com/llamaluvr/demo-galaxys-hidenavbar-issue (run `yarn; expo publish; expo build:android`)

APK with the cover setting (has issue): https://expo.io/artifacts/d511042e-df8b-4fb1-990b-cc04a4ae9663

APK with the contain setting (no issue): https://expo.io/artifacts/3f0af51a-cd7a-42f6-84ad-3bc49d163fb5

**Comment by tsapeta** [comment]
I'm closing it as it seems to be fixed already: https://twitter.com/llamaluvr/status/1475520209029156869
