### ISSUE TITLE
[expo-keep-awake] does not keep screen awake

### ISSUE THREAD

**Issue by cmejet** [expo/expo#24007]
### Minimal reproducible example

https://github.com/cmejet/rn-keep-awake-repro

### Summary

When implementing expo-keep-awake using the `useKeepAwake` hook, or the functions for `activateKeepAwakeAsync` and `deactivateKeepAwake` I expect that my screen will stay on and not go to sleep.

This is a fresh init of react native, simply added expo and expo-keep-awake. When ran in release mode I expect the screen to stay on, but it does not.
This is true for both iOS and Android.

When testing I used an iPhone with iOS 16.6 as well as Android device with os version 13.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    npmGlobalPackages:
      eas-cli: 3.15.1
    Expo Workflow: bare

**Comment by alanjhughes** [comment]
Hi @cmejet - your project has not been set up to run expo modules correctly. I've pulled your repro and running `npx install-expo-modules@latest` will result in the correct behavior.

**Comment by cmejet** [comment]
> Hi @cmejet - your project has not been set up to run expo modules correctly. I've pulled your repro and running `npx install-expo-modules@latest` will result in the correct behavior.

Thank you! I will give that a try, def used to working on projects starting with expo which is a much better experience. Feel like a noob just having done `yarn add expo`
