### ISSUE TITLE
expo gives the issue of certificate path not found only on Android, javax.net.ssl.SSLHandshakeException(java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.)

### ISSUE THREAD

**Issue by ameyarumbleon** [expo/expo#24001]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by linonetwo** [comment]
Hitting same issue, how to bypass?

**Comment by linonetwo** [comment]
This works https://github.com/expo/expo/issues/16451#issuecomment-1151096831
