### ISSUE TITLE
Expo build release, but  i get a constant white screen in Android tv. 

### ISSUE THREAD

**Issue by 1021683053** [expo/expo#2400]
1, Expo build release apk run in Android tv, I get a constant white screen.

Android TV : 
 ```shell
adb devices -l
List of devices attached
emulator-5554          device product:sdk_google_atv_x86 model:sdk_google_atv_x86 device:generic_x86 transport_id:6
```
2, Release apk run in Mi note3 is good。

problem like this
https://stackoverflow.com/questions/51707841/android-tv-app-shows-white-screen

App.json
```json
{
  "expo": {
    "name": "YouTube-TV",
    "description": "This project is really great.",
    "slug": "android-tv",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "platforms": [
      "android"
    ],
    "version": "0.0.1",
    "orientation": "landscape",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "yes",
      "publishBundlePath": "ios/youtube-tv/Supporting/shell-app.bundle",
      "publishManifestPath": "ios/youtube-tv/Supporting/shell-app-manifest.json"
    },
    "android": {
      "package": "expo.io",
      "permissions": [],
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    },
    "isDetached": true,
    "detach": {
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.8.4-sdk30.0.0-3de13133-1adc-4ba1-8569-a84011e570b4.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.8.1-sdk30.0.0-271c32ab-0715-4dfb-8270-ecead3679bb4.tar.gz"
    },
    "scheme": "exp1874d5c58a6749699b5f7c889130fc79"
  }
}
```

**Comment by quinlanj** [comment]
hi @1021683053 , we will need more information to solve this problem. Could you make a simple project with this white screen problem, and provide the apk and the source code for it? Also, a step by step guide on how we can see the white screen problem will be very helpful. Thanks.

**Comment by nebmesemaou** [comment]
same here

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to create a clearer picture for our team about what is still actionable, we are going through older and inactive issues that were missing the necessary information for us to attempt to debug (see: `Needs more info` label). 

If anyone is still encountering this issue on a presently supported SDK version (30-34) and has Minimal, Complete and Verifiable Example ([MCVE](https://stackoverflow.com/help/minimal-reproducible-example)) and better yet, the root cause identified, we encourage you to create a new issue with said information!

Cheers,
Adam
