### ISSUE TITLE
[expo-linear-gradient] Unable to make it works with Animated

### ISSUE THREAD

**Issue by Ionys320** [expo/expo#24013]
### Minimal reproducible example

https://snack.expo.dev/@ionys320/36324e

### Summary

I'm experiencing an issue with `expo-linear-gradient` and the `Animated` system.
I would like to make a gradient going progressively from the top to the bottom, without using any scaling trick, only the `locations` attribute of the `LinearGradient` component.

The issue is that after implementing the `Animated` system, my gradient is not showing up anymore. 

- This is not working: `locations={[0, linearAnim]}`
- This is working: `locations={[0, 1]}`

Of course, I checked if the animation was correctly executed, and it is, I put a demonstration in my reproducible example.

The errors provided by React are:
```
 ERROR  Cannot set prop 'locations' on view 'class expo.modules.lineargradient.LinearGradientView'
→ Caused by: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.Double
 ERROR  TypeError: Cannot add new property '_tracking'
```
I checked on Internet, and it should occured because I didn't use `Animated.createAnimatedComponent(LinearGradient);`, but I did, and use the created component `AnimatedLinearGradient` (this is also is my reproducible example).

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 31, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0, 34.0.0, 34.0.0, 34.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996

**Comment by brentvatne** [comment]
here's an example: https://github.com/expo/expo/blob/eb6aeb3b3ab537c1512357af6398422a8bd2845e/apps/native-component-list/src/screens/LinearGradientScreen.tsx
