### ISSUE TITLE
Issue with image uri path between dev and deployed versions.

### ISSUE THREAD

**Issue by viking11** [expo/expo#24011]
### Minimal reproducible example

https://snack.expo.dev/@kasperandersen/no-img-apk-example2. APK: https://file.io/DLNBEDxD0Q51

### Summary

SDK Version: 48.0.18
Platform: iOS and Android

Hi, there seems to be an issue with the uri path of images between a dev build and a deployed build.

I'm currently working on an app that generates a pdf from html using expo-print's printToFileAsync function. This pdf needs a logo in the top left corner. I get the image uri from expo-asset using `await Asset.fromModule(require('../assets/Banana-Single.png'))` as shown in the reproducible example. 

This works perfectly in my dev enviroment (or in the reproducible example), the pdf is generated and the image is shown. 
But when i test it in the apk on my android (or through testflight for iOS) the pdf is generated, but i get a missing image texture.

When i alert the image uri, i see that the path in the dev build looks fine, but when i alert that exact same path in the apk, i simply get "assets_ImageName" (pictures below). 

I have tried every other expo api that gets you an image uri, all of them has the same problem of just showing "assets_ImageName" in the apk.

You can download the apk from here if you want to test it on your own android device: https://file.io/DLNBEDxD0Q51
(its the same link as in the reproducible example. I dont have one for iOS, sorry). I made the apk using 
`eas build --platform android --profile preview` using the eas.json found in the reproducible example

The only clue i've found is that it **might** have something to do with the metro bundler from this post: 
https://github.com/facebook/react-native/issues/18216#issuecomment-412050360 from @windev92 (the comment isminimized so you might have to expand it).

Let me know if anybody needs more information, i'll try to give as much as i can, but i am pretty new to app development.

![image](https://github.com/expo/expo/assets/17760759/bcb79caa-b179-4c33-994c-cf6d05320451)
^^^^^^^^^^^^^^^^^^^^^**DEV**^^^^^^^^^^^^^^^^^^^

![image](https://github.com/expo/expo/assets/17760759/943bc72e-ee99-460d-b135-140647061906) 
^^^^^^^^^^^^^^^^^^^^^**APK**^^^^^^^^^^^^^^^^^^^

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD    
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390     
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    Expo Workflow: managed

**Comment by viking11** [comment]
please, does nobody have any idea why this is happening?

**Comment by saiqiong** [comment]
Had the same issue, after searching here and there the below solution works , btw, the transfer to base64 may not be necessary in your case:
```
const isAndroidRelease = isAndroid && !__DEV__;
  let iconUri: string;
  const asset = Asset.fromModule(
    /* eslint-disable-next-line */
    require('../../../assets/jpg/logo-xxx-primary.jpg')
  );
  if (!asset.localUri) {
    await asset.downloadAsync();
  }

  if (isAndroidRelease) {
    // Copy to cache
    const localUri = `${FileSystem.cacheDirectory}copied_icon.jpg}`;
    await FileSystem.copyAsync({
      from: asset.localUri || asset.uri,
      to: localUri,
    });

    // Load the copied asset
    const copiedAsset = Asset.fromURI(localUri);
    copiedAsset.localUri = localUri; // Need to set the localUri for loadAsync() to work
    const [copy] = await Asset.loadAsync(
      copiedAsset.localUri || copiedAsset.uri
    );
    iconUri = copy.localUri ?? copy.uri;
  } else {
    iconUri = asset.localUri ?? asset.uri;
  }
  const titleBase64Image = await manipulateAsync(iconUri, undefined, {
    compress: 0.9,
    format: SaveFormat.JPEG,
    base64: true,
  });
```

**Comment by meabed** [comment]
I had this issue where the code will work on ios and android locally, but when building android I get asset_name as local uri, going thro the code I was able to transform it back to URI for `readAsStringAsync` and it works 🚀 

```
export async function readAssetFile({ fileName }: { fileName: string }) {
  const [{ localUri, name, hash, type }] = await Asset.loadAsync(fileName);
  let uri = localUri ?? '';
  if (!uri?.startsWith('file://')) {
    if (Platform.OS === 'android') {
      uri = `${cacheDirectory}ExponentAsset-${hash}.${type}`;
    }
  }
  return readAsStringAsync(uri, { encoding: 'base64' });
}

const imgRequire = require('./assets/test-image.png');
const imgBase64 = await readAssetFile(imgRequire);

```

Hope this solve your issue.
