### ISSUE TITLE
React Native CLI failed to determine Android project configuration

### ISSUE THREAD

**Issue by ntalamdotcom** [expo/expo#24029]
### Summary

After running
npx expo run:android

The terminal stuck in "config syncing".

I have to cancel it and run it again.
then I have to manually change the namespace in Android/app/build.gradle,
because it doesnt generate it properly:

com.backtorise -> com.ntalamdotcom.backtorise

which is another fail in this framework... and I got this:

`› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\GitHub\back-to-rise-mobile\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 432

* What went wrong:
A problem occurred evaluating script.
> React Native CLI failed to determine Android project configuration. 
This is likely due to misconfiguration. Config output:
  [root:E:\GitHub\back-to-rise-mobile, reactNativePath:E:\GitHub\back-to-rise-mobile\node_modules\react-native, reactNativeVersion:0.72, dependencies:[:], commands:[], healthChecks:[], platforms:[:], project:[:]]`

App.json:

`{
  "expo": {
    "name": "backtorise",
    "slug": "backtorise",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "package": "com.ntalamdotcom.backtorise",
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "plugins": [
      "@react-native-google-signin/google-signin"
    ],
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "89bd4264-3da1-4172-8fae-a28478e23f6f"
      }
    }
  }
}
`

package.json
`{
  "name": "backtorise",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "web": "expo start --web",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@react-native-google-signin/google-signin": "^10.0.1",
    "expo": "~49.0.7",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "sharp-cli": "^2.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.14",
    "typescript": "^5.1.3"
  },
  "private": true
}
`

### What platform(s) does this occur on?

Android

### SDK Version

0.10.11

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.5.1 - E:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.2.0 - E:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: bare

### Minimal reproducible example

any project from scratch

**Comment by Kudo** [comment]
duplicated from #24028
