### ISSUE TITLE
Unable to open simple app using Expo Go after installing `expo-dev-client`

### ISSUE THREAD

**Issue by esorinas** [expo/expo#24023]
### Summary

So I was tracking down an error that is preventing an app of mine to build on android, and I went to the most basic: I created an empty project and started installing dependencies. Then I encountered that simply installing `expo-dev-client` is preventing me to open the app (on both iOS and Android). Here are the steps:

1.  `yarn create expo-app reproduce-bug-app` & `cd reproduce-bug-app`
2. At this point, `yarn expo start` works fine on both iOS and Android; Expo Go will open the app
3. `npx install expo-dev-client`
4. At this point, `yarn expo start` loads the QR code, but neither iOS nor Android are able to open the app.
-  From the Expo Go app, the local development server appears, but clicking it does nothing (both iOS and Android). I am using the latest version of the Expo Go app.
- From the QR code on iOS, the Camera app says that it is unable to use the data from the QR (I attach a screenshot) 
![image](https://github.com/expo/expo/assets/43247096/03b4b5d6-682b-45bc-9d43-e69e31ba177c)
- From the QR code on Android (from the Expo Go app), it gets captured and it redirects me to the Expo Go landing page (and nothing else happens).

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

{
    "expo": "~49.0.7",
    "expo-dev-client": "~2.4.6",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.3"
}

### Environment

    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ~49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    Expo Workflow: managed

### Reproducible demo

https://github.com/esorinas/reproduce-bug-app

**Comment by seyadeodin** [comment]
That's because you're running on development build, press s to switch to expo go, as the CLI suggests.

**Comment by esorinas** [comment]
You are totally right, thank you!! (and sorry for missing such an obvious thing, I am kinda new to this 😅)

**Comment by Levik931** [comment]
@esorinas @seyadeodin yes but like if you have google auth, it's not gonna work with EXPO GO, you will need development server, which gives me problems when opening with EXPO app. ( Expo app literally says Development Build ) but it does not work

**Comment by akpor-kofi** [comment]
Yes me too please have you found a fix yet?

**Comment by Victor-Sun** [comment]
This seems to be happening for me as well after switching from Expo 48 -> 49. Now on Android whenever I click on the development server it doesn't do anything and I have to scan the QR code.

**Comment by Henrisoho** [comment]
Any fixes to this?

**Comment by jmaofficial** [comment]
i just got the same issue, from nowhere...

**Comment by jmaofficial** [comment]
> Any fixes to this?

did you find a fix?

**Comment by congtuan2608** [comment]
> @ansmlc

I also had the same problem

**Comment by awatso207** [comment]
same issue here

**Comment by sawako094** [comment]
same problem here

**Comment by alumezi** [comment]
Its probably because of your router configuration, not much you can do except use a tunnel connection:
https://docs.expo.dev/get-started/start-developing/#having-problems

**Comment by keehui9292** [comment]
same issue here, tried tunnel but still nothing happen when tapping dev server.

**Comment by shakedlokits** [comment]
I have the same exact issue:
1. Running `expo start --tunnel`
2. Seeing the button of the development server on the app
3. Can't click it. And if I hold the button it allows me to copy two links.
Might be a problem with the URI/linking on iOS?

Versions:
iOS: v17.5.1
Model: iPhone 13 mini
Expo CLI: v0.18.13
Expo Go App: v2.31.5
SDK: v51

**Comment by ICGVIP** [comment]
This is happening with me too. I am using eas build for a few services in a bare workflow with expo-dev-client too. My app was working perfectly fine a few days ago but now it isn't even loading when I try to connect to dev server running on my computer.

**Comment by walterairs** [comment]
# Possible workaround

I deleted my android emulator and created a new one, installed the expo go and my application by switching to expo go and pressing `a` to launch on android.

After the launch I got the following error message about my app:
https://stackoverflow.com/questions/72104175/compiling-js-failed-react-native-expected-buffer-size

I deleted few of my last changes in my code, reloaded with `r` and then it suddenly started working.

So i would like to deduce the workaround as follows:
- Backtrack your code

**Comment by Sithabo** [comment]
I had the exact same problem where after installing `npm install -g eas-cli` i couldnt open the dev build.

Its really stupid, but I fixed it by following the dev build process until the end. To get the dev build guideline go to this link : [eas tutorial](https://docs.expo.dev/tutorial/eas/introduction/);

after having reached the step where I had to build the app using this command: `eas build --platform android --profile development`, I followed it through to the point where i installed this on my phone and also on the emulator app I had running (therefore meaning the dev build app was now showing on the respective devices apps), I clicked on the development build server, and it launched and was fully working!

I do believe that this was the issue most of you may have also encountered as it is a very common problem amongst beginners (like me too!).

I hope this helps!

**Comment by MvRemmerden** [comment]
If you are on iOS, also make sure that the Expo Go app has 
the permission for Local Network, that fixed it for me!

**Comment by PwntasticKev** [comment]
My issue was resolved by switching to expo go mode vs dev mode. 

```
start your server
press `s` to switch modes
scan your code
```

**Comment by ningacoding** [comment]
whats the diff between expo go and dev mode?

**Comment by walterairs** [comment]
> what's the diff between expo go and dev mode?

I like to think that expo go is a fast developing tool with expo, which means you can use it to develop the app up to a certain extent because it does not build the app, rather runs it live inside the emulator.

The dev build is an actual build which contains all the libraries (even the ones for react native) and works as the intended app works.

Expo recommends using the dev build in the development phase of the application(on building a product that's meant for production) because it works similar to the end product. 

For me, some problems were not prominent in the expo go during development that's why I switched to development build.

I hope this helps, please correct my misinformations if there is any.

**Comment by thongminhtran** [comment]
any update on this?

**Comment by Pastoray** [comment]
pretty sure the expo go qr code just says "Something went wrong" and the development build doesn't redirect anywhere, although the exact same setup with the same exact code worked yesterday, i don't know why so many people rely on this super inconsistent tool and it's basically a standard although it's extremely unstable.

**Comment by Pastoray** [comment]
> pretty sure the expo go qr code just says "Something went wrong" and the development build doesn't redirect anywhere, although the exact same setup with the same exact code worked yesterday, i don't know why so many people rely on this super inconsistent tool and it's basically a standard although it's extremely unstable.

It does seem you actually need to build it in eas, download it using the provided qr code, and THEN you can scan the expo dev build qr code, very st8 forward 👍

**Comment by shahsuvarli** [comment]
I think many people who have fixed the problem by simply running `npx expo start --tunnel`, are not using the packages which require development build. Those who use libraries such as @react-native-firebase/app which need native code still face the bug

**Comment by stasiadanilova** [comment]
I had same issue after installing expo-dev-client, my work around was locally deleting record "expo-dev-client": "~4.0.28", from package.json file, and after that project was build with previous settings and I was able to open app with Expo go

**Comment by marktanrj** [comment]
I had the same problem even after pressing 's' to switch to expo go mode.
Solved it by removing "expo-dev-client": "~5.0.20" line in package.json and doing `npm install`

**Comment by JagritGumber** [comment]
For me it was a weird reason, I use hamachi to connect to our office lan, which was causing the issue, glad I realized that exp:// ip in console was not mine

**Comment by emarhin** [comment]
Just uninstall expo client it will work. it worked for me!!!!!!

**Comment by Sofiullah-Iqbal-Kiron** [comment]
> That's because you're running on development build, press s to switch to expo go, as the CLI suggests.

Thank bro.

**Comment by zekageri** [comment]
I have the same problem.

### Steps I did
- `npx create-expo-app test-app`
- cd into folder
- `npx expo start`
- cmd says "Using Expo Go"
- Downloaded exo go on android
- scanned the qr code
- loading screen for 5 min
- expo go app error log: "Uncaught Error: java.io.IOException: Failed to download remote update"

I have no "expo-dev-client" in "package.json" and it is not running in dev mode. I tried `npm install` still not working.

**Comment by Valerio-Tonelli** [comment]
Uninstalling `expo-dev-client` worked for me.
Is there any explanation?

**Comment by Pula99** [comment]
Here’s what fixed the issue for me:

1. Uninstalled `expo-dev-client`.
2. Set the React Native packager hostname to my Wi-Fi IP:

setx /M REACT_NATIVE_PACKAGER_HOSTNAME <YOUR_LOCAL_IP>
(Run this in PowerShell as Administrator)

3. Closed the IDE, and started the project:

Scanned the QR code using Expo Go — app connected successfully.

If it still doesn’t work:
Change your network profile from Public  -> Private:
