### ISSUE TITLE
this is going no where: npx expo run:android

### ISSUE THREAD

**Issue by ntalamdotcom** [expo/expo#24028]
### Summary

app.json:

```
{
  "expo": {
    "name": "backtorise",
    "slug": "backtorise",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "package": "com.ntalamdotcom.backtorise",
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "plugins": [
      "@react-native-google-signin/google-signin"
    ],
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "89bd4264-3da1-4172-8fae-a28478e23f6f"
      }
    }
  }
}
```
package.json:

```
{
  "name": "backtorise",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "web": "expo start --web",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@react-native-google-signin/google-signin": "^10.0.1",
    "expo": "~49.0.7",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "sharp-cli": "^2.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.14",
    "typescript": "^5.1.3"
  },
  "private": true
}
```

After running  npx expo run:android

`PS E:\GitHub\back-to-rise-mobile> npx expo run:android
√ Created native project | gitignore skipped
› Using current versions instead of recommended react-native@0.72.3.  
√ Updated package.json and added index.js entry point for iOS and Android
› Installing using npm
> npm install
- Config syncing`

it stays there. forever

### What platform(s) does this occur on?

Android

### SDK Version

0.10.11

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.5.1 - E:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.2.0 - E:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: bare

### Minimal reproducible example

just a minimum project. I started many times from scratch

**Comment by Kudo** [comment]
hi there! could you try to run the command and share the output?
`EXPO_DEBUG=1 npx expo prebuild -p android --clean`

**Comment by brentvatne** [comment]
closing until we have more information
