### ISSUE TITLE
[expo-notifications] Background Notifications Not Received When App Is In Foreground

### ISSUE THREAD

**Issue by nickcherry** [expo/expo#24024]
### Minimal reproducible example

https://github.com/warpcast/background-push-demo

### Summary

When sending a background push notification (i.e. with `content-available: 1`) when the app is in the foreground, I would expect at least one event handler (e.g. `setNotificationHandler#handleNotification`, `addNotificationReceivedListener`) to be triggered, but it is not.

## Steps to Reproduce in Demo App
1. In `app.json` and `Info.plist`, replace the bundle identifier (`com.merkle-manufactory.background-push-demo`) with a unique value.
2. Run `yarn install` to install dependencies.
3. Plug in a physical iPhone via USB.
4. Run `yarn ios`, and choose the physical device to build the app.
5. Visit [App Store Connect](https://appstoreconnect.apple.com/apps) and create a new iOS app with the new bundle ID. Be sure to enable the Push Notification capability.
6. Run `yarn ios` to rebuild the app.
7. Enable push notifications via the app's UI.
8. Long-press the device token and copy to clipboard.
9. Visit the [Apple Push Notification Console](https://icloud.developer.apple.com/dashboard/notifications), and navigate to the new push notification form.
10. Paste the copied device token, and with the app **foregrounded**, send a normal **alert** notification.
11. Observe `setNotificationHandler#handleNotification`, `addNotificationReceivedListener`, and `setNotificationHandler#handleSuccess` in the console logs, indicating that the app is receiving the notification.
12. Start a new test push form in the Apple Push Notification Console. Paste the device token, and with the app **backgrounded**, send a **background** notification (i.e. change the `apns-push-type` to `background`, which will add `content-available: 1` to the payload).
13.  Observe `backgroundNotificationTask` in the console logs, indicating that the app is receiving the notification.
14. Return once more to the Apple Push Notification Console to create a new push notification. Send a **background** notification to the device, but this time with the app in the **foreground**.
15. Observe that there are no logs from `setNotificationHandler#handleNotification`, `addNotificationReceivedListener`, `addNotificationResponseReceivedListener`, or `backgroundNotificationTask`. **Expected behavior is that one or more of the previously mentioned event handlers would be triggered**

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.volta/tools/image/node/16.20.2/bin/node
      Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 8.19.4 - ~/.volta/tools/image/node/16.20.2/bin/npm
      Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    Expo Workflow: managed
```

**Comment by Klin-Coders** [comment]
+1

**Comment by edkimmel** [comment]
It's [this line](https://github.com/expo/expo/blob/main/packages/expo-notifications/ios/EXNotifications/Notifications/Background/EXBackgroundRemoteNotificationConsumer.m#L31) that is dropping the background notification when the app is active.  
```
- (void)didBecomeReadyToExecuteWithData:(NSDictionary *)data
{
  if ([[UIApplication sharedApplication] applicationState] != UIApplicationStateActive) {
    [_task executeWithData:data withError:nil];
  }
}
```
Seems intentional on expo's part, but it is different than [Android's counterpart ](https://github.com/expo/expo/blob/main/packages/expo-notifications/android/src/main/java/expo/modules/notifications/service/delegates/ExpoHandlingDelegate.kt#L108)which sends all notifications to javascript.
```
  override fun handleNotification(notification: Notification) {
    if (isAppInForeground()) {
      getListeners().forEach {
        it.onNotificationReceived(notification)
      }
    } else if (notification.shouldPresent()) {
      NotificationsService.present(context, notification)
    }
  }
```
