### ISSUE TITLE
Android Google Play target SDK 33 - error

### ISSUE THREAD

**Issue by claudiofus** [expo/expo#24032]
### Minimal reproducible example

I've updated my working app to SDK 49, removing expo-updates due to problems from dependencies. App in Play Store shows target SDK 33

### Summary

I've updated my working apps to SDK 49, removing expo-updates due to problems from dependencies. App in Play Store shows target SDK 33 but I received an email from Google: "We found that 12 of your apps target an older version of Android. To provide users with a safe and secure experience, Google Play requires all apps to meet the target API level requirements before August 31, 2023."

I've just 2 build left on my account for this month so could you please check for a solution?

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
      npm: 9.8.1 - ~/.nvm/versions/node/v19.1.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      babel-preset-expo: ^9.5.1 => 9.5.1 
      expo: ^49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed

**Comment by AnteroSalonen** [comment]
This is an issue for us too. I cannot find any proper documentation anywhere how to configure the Google Play Console "API levels" in the Expo configuration.

I also tried to update SDK from 48 --> SDK 49, trusting the latest version would have bumped the API level from 21+ to 22+ but it apparently doesn't do this (just tested it by building a production build and attempting to upload it to Google Play).

If the SDK 49 doesn't automatically update the API level to 22+, how can this be done manually? Help appreciated!

**Comment by claudiofus** [comment]
I asked Google support and they told me that, in my case, the problem is linked to old bundles active in open or internal tests. I've updated these bundles with the last one (SDK 49) and the error disappeared.

**Comment by AnteroSalonen** [comment]
Ok,cool. For me, adding the `minSdkVersion: 22` under the app config `expo-build-properties` did the trick.

**Comment by AnteroSalonen** [comment]
Ah, just read your problem description more thoughtfully. Your case was different than mine. For me, Google play complained that our Expo app supported API versions 21+ which Google will stop supporting at 31 Aug 2023.
