### ISSUE TITLE
exp.host responds with 403

### ISSUE THREAD

**Issue by yousefelgoharyx** [expo/expo#24036]
### Summary

I uploaded my backend to a vm from Hetzner and whenever I send requests to https://exp.host/ I get the following response
```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/</code> from this server.</h2>
<h2></h2>
</body></html>
```
Sending requests work on my machine though

### What platform(s) does this occur on?

Web

### SDK Version

Expo Node SDK

### Environment

Server Location: Finland

### Minimal reproducible example

https://github.com/expo/expo-server-sdk-node

**Comment by Kudo** [comment]
hi there! please share your relevant `expo-server-sdk` code.

also would be good to test the `curl --verbose -X POST https://exp.host/--/api/v2/push/send` on your Hetzner vm. it should receive http 400 in this case.

**Comment by yousefelgoharyx** [comment]
I run `curl exp.host` on the VM and it still gives me 403
Why could that be

`curl https://exp.host/ --verbose -I
*   Trying 34.110.201.56:443...
* Connected to exp.host (34.110.201.56) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=exp.host
*  start date: Sep  7 13:54:47 2023 GMT
*  expire date: Dec  6 14:46:40 2023 GMT
*  subjectAltName: host "exp.host" matched cert's "exp.host"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1D4
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x562bcd07e560)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> HEAD / HTTP/2
> Host: exp.host
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
< HTTP/2 403
HTTP/2 403
< strict-transport-security: max-age=31536000; includeSubDomains
strict-transport-security: max-age=31536000; includeSubDomains
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

<
* Connection #0 to host exp.host left intact`

**Comment by Kudo** [comment]
could it be some ipv6 related? https://www.reddit.com/r/hetzner/comments/13q9p0n/i_have_a_remote_desktop_server_in_helsinki_ip/?rdt=43725

**Comment by svbackend** [comment]
Hello @yousefelgoharyx, did you manage to figure out cause of this issue?  Can you share any information if you fixed it?

**Comment by yousefelgoharyx** [comment]
Tbh, we just ditched expo altogether

**Comment by svbackend** [comment]
Thanks for the reply, in my case I'm also using hetzner and getting the same error, and not only for expo.host but for mixpanel api as well (same 403 response), so I think this might be not an expo problem
