### ISSUE TITLE
expo-dev-client breaks gestures on ios

### ISSUE THREAD

**Issue by itsramiel** [expo/expo#24042]
### Minimal reproducible example

https://github.com/itsramiel/gesture-x-dev-client

### Summary

I am using react-native-reanimated and react-native-gesture-handler for animations and gestures, but when I upgraded react-native-reanimated to 3.4.2, there was an issue with expo-dev-client so I upgraded expo-dev-client to 2.4.7.

However now gestures are broken on ios and they can't update shared values in reanimated. If you remove `expo-dev-client` as a dependency, everything works as normal.

Note that when you first build the dev client, everything works fine as can be experienced by the repro, however if you close the app and open it again, things break as shown in the video

https://github.com/expo/expo/assets/80689446/9798dfcc-1e93-4ee4-bc1b-158e2c48b25b

After things break, if you reload the app from the developer menu, things go back to normal.
Please let me know if you need any more details

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.04.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/ramiel/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed

**Comment by Kudo** [comment]
hi there! this issue should be resolved by https://github.com/software-mansion/react-native-reanimated/pull/4926.
