### ISSUE TITLE
dashed blank splash screen (can't remove splash screen)

### ISSUE THREAD

**Issue by faustoct** [expo/expo#2405]
Expo 30sdk always shows a blank splash screen with dashed square. How to remove splash screen ?!?

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/v30.0.0/guides/splash-screens

**Comment by faustoct** [comment]
@brentvatne already read the documentation it does not have how to remove/disable splash screen.

**Comment by faustoct** [comment]
it offers `isSplashScreenDisabled: YES` which does not solve at all. looking for something in app.json..

**Comment by faustoct** [comment]
also the doc says how to create.. instead I'm trying to remove/disable it.. does have straight way to remove splash screen?!?

**Comment by brentvatne** [comment]
`isSplashScreenDisabled: YES` is for ejected apps. if you want to remove the default splash screen just create a blank one or use an empty image or remove the splash from app.json

**Comment by faustoct** [comment]
@brentvatne got it. just can't replace the default `dashed square blank` splash.. already tried what u suggested!

**Comment by brentvatne** [comment]
did you try closing and reopening the expo client?

**Comment by faustoct** [comment]
just can't get away from this screen..

**Comment by faustoct** [comment]
@brentvatne do u need any piece of code I can share?!? maybe can help figure out what's going on..

**Comment by faustoct** [comment]
I tried both
````
    "splash": {
      "image": "./assets/icon.png"
    }
//    .... (both)
    "splash": {
      "backgroundColor": "#ffffff"
    },
````

**Comment by brentvatne** [comment]
<img width="485" alt="screen shot 2018-10-11 at 1 40 21 pm" src="https://user-images.githubusercontent.com/90494/46832565-3c2b7880-cd5b-11e8-8cd3-e05eafe1c8e0.png">

if I remove the splash image from app.json then

<img width="485" alt="screen shot 2018-10-11 at 1 43 12 pm" src="https://user-images.githubusercontent.com/90494/46832733-a93f0e00-cd5b-11e8-8851-4cb4acb6fa6c.png">

https://github.com/brentvatne/lol-splash-thing

**Comment by faustoct** [comment]
@brentvatne I don't know on ios project. I have to check it later but on android at `res/drawable` folder, the file splash_background.xml points to shell_launch_background_image.. Might it not be replaced anyway?!?

**Comment by faustoct** [comment]
Hum! I don't know actually. Might it be detach project?

**Comment by faustoct** [comment]
````
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splashBackground"/>
    <item><bitmap android:gravity="center" android:src="@drawable/shell_launch_background_image" /></item>
</layer-list>
````

**Comment by brentvatne** [comment]
ok in that case you just need to read a guide about how to do this on native ios and android, once you're detached it's up to you

**Comment by faustoct** [comment]
ok. thank you.. could u share the guide with me?

**Comment by faustoct** [comment]
The splash screen is linked with Expo.Splash somehow..

````
    <activity
      android:name=".MainActivity"
      android:launchMode="singleTask"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:theme="@style/Theme.Exponent.Splash"
      android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <data android:scheme="exp4d5f0e068b6b4bf79dca48bbdfe92476"/>

        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>

        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <!-- ADD DETACH APP SPECIFIC INTENT FILTERS -->
    </activity>

    <activity
      android:name=".experience.ShellAppActivity"
      android:launchMode="singleTask"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:theme="@style/Theme.Exponent.Splash"
      android:windowSoftInputMode="adjustResize">
      <!-- ADD SHELL INTENT FILTERS HERE -->
      <!-- ADD SHELL APP SPECIFIC INTENT FILTERS -->
    </activity>

    <activity
      android:name=".experience.HomeActivity"
      android:label="@string/app_name"
      android:launchMode="singleTask"
      android:screenOrientation="portrait"
      android:theme="@style/Theme.Exponent.Light">
    </activity>
````
