### ISSUE TITLE
Refreshing the page after navigating to a screen takes me back to the main navigator

### ISSUE THREAD

**Issue by hatim85f** [expo/expo#24055]
### Minimal reproducible example

https://github.com/hatim85f/nav.git

### Summary

I am using expo for web, and using react-navigation for navigating between screens
whenever I save any new updates to my code the nav taking me back to the fist navigator, I did try to use expo-router but I found it very complicated and I couldn't migrate
I was trying to presist the state as per react-navigation docs so keep url path the same but with no change to success

`const PERSISTENCE_KEY = "NAVIGATION_STATE_V1";
`
```
const AppNavigator = () => {
  const [initialState, setInitialState] = useState();

  const navigationContext = useContext(NavigationContext);
  const linking = {
    prefixes: [
      "nav://",
      "https://nav.com",
      "https://nav/intro",
      "https://nav/auth",
      "https://nav/home",
      "https://nav/profile",
    ],
    config: {
      screens: {
        Intro: "intro",
        Login: "auth",
        Profile: "profile",
        Home: "",
      },
    },
  };

  useEffect(() => {
    const restoreState = async () => {
      const savedStateString = await AsyncStorage.getItem(PERSISTENCE_KEY);
      const state = savedStateString ? JSON.parse(savedStateString) : undefined;
      console.log(savedStateString);
      if (state !== undefined) {
        setInitialState(state);
      }
    };

    restoreState();
  }, []);

  console.log(initialState);

  // if (!isReady) {
  //   return <Loader />;
  // }

  return (
    <NavigationContainer
      linking={linking}
      fallback={<Text>Loading...</Text>}
      context={navigationContext}
      initialState={initialState}
      onStateChange={(state) => setInitialState(state)}
    >
      <FullAppNavigator />
    </NavigationContainer>
  );
};

export default AppNavigator;
```

```
export default function App(props) {
  const navigationContext = {};

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <SafeAreaProvider>
        <NavigationContext.Provider value={navigationContext}>
          <AppNavigator />
        </NavigationContext.Provider>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  );
}
```

### Environment

  System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.5.0 - ~\AppData\Roaming\npm\node.CMD
      npm: 9.8.1 - ~\AppData\Roaming\npm\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30
        Build Tools: 29.0.2, 30.0.3, 33.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.2 
      expo: ^48.0.17 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

**Comment by Kudo** [comment]
hi there! this issue should relate to react-navigation. please try to report the issue to https://github.com/react-navigation/react-navigation/issues.
