### ISSUE TITLE
fontVariant crashes expo when applying to <Text>

### ISSUE THREAD

**Issue by jtangas** [expo/expo#2407]
### Environment

Environment:
  OS: macOS 10.14
  Node: 10.11.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.1
  react: ^16.5.2 => 16.5.2
  react-native: ~0.55.4 => 0.55.4

iOS, Snack

### Steps to Reproduce

1. Create New Application
2. Create A Text component
3. Apply style `{{ fontVariant: 'small-caps' }}` to Text component
```jsx
<Text style={{ fontVariant: 'small-caps' }}>small caps</Text>
```
4. Watch Expo crash

Alternative:
Run the following snack in browser or on your device: https://snack.expo.io/@jtangas/frowning-popsicle

### Expected Behavior

I should see Text printed to screen in small caps

### Actual Behavior

Expo crashes to home screen or black screen then crashes to home screen

### Reproducible Demo

https://snack.expo.io/@jtangas/frowning-popsicle

**Comment by tcdavis** [comment]
Thanks for the clear report!
`fontVariant` expects an array of values, not a single value so you'll need to do this: https://snack.expo.io/@thetc/font-variant

https://facebook.github.io/react-native/docs/text-style-props#fontvariant
