### ISSUE TITLE
Web publishing JS files renders 404 - also assets path are not correct

### ISSUE THREAD

**Issue by arun-spar** [expo/expo#24073]
### Summary

Created expo router app using `npx create-expo-app@latest --template tabs@49`. After web publishing using `npx expo export -p web`, running it locally using `npx serve dist` returns 404 when access the expo router entry js file. I tried without router, then i am not seeing this issue.

Please help. Thank you.

 HTTP  8/22/2023 7:26:49 PM ::1 GET /
 HTTP  8/22/2023 7:26:49 PM ::1 Returned 304 in 1 ms
 HTTP  8/22/2023 7:26:49 PM ::1 GET /_expo/static/js/web/node_modules%5Cexpo-router%5Centry-4d3ee3ac1dee2ccae600db09a0f66c57.js
 HTTP  8/22/2023 7:26:49 PM ::1 Returned 404 in 3 ms

### What platform(s) does this occur on?

Web

### SDK Version

49

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ~49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/spar-dev/expotabapp.git

**Comment by arun-spar** [comment]
Looks like `npx expo export -p web` is not building path correctly for expo router entry js path. For example, the path _expo/static/js/web/node_modules%5Cexpo-router%5Centry-4d3ee3ac1dee2ccae600db09a0f66c57.js is not correct
if i changed to _expo/static/js/web**/node_modules/expo-router/**entry-4d3ee3ac1dee2ccae600db09a0f66c57.js, i am able to serve this js.

**Comment by arun-spar** [comment]
if i hosted the web under subfolder then i am unable to get that subfolder added to the path for assets like below

assets/assets/fonts/SpaceMono-Regular.ttf?platform=web&hash=49a79d66bdea2debf1832bf4d7aca127
assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome.ttf?platform=web&hash=b06871f281fee6b241d60582ae9369b9

but the real path is
/feapp/assets/assets/fonts/SpaceMono-Regular.ttf?platform=web&hash=49a79d66bdea2debf1832bf4d7aca127
/feapp/assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome.ttf?platform=web&hash=b06871f281fee6b241d60582ae9369b9

**Comment by arun-spar** [comment]
![forexpo](https://github.com/expo/expo/assets/121198022/45464273-acc7-4ba1-a819-4a3a6c2aa165)

**Comment by hienhtn** [comment]
can someone fix or quickly fix this, i can't deploy my site

**Comment by tronghieu60s** [comment]
can someone fix or quickly fix this, i can't deploy my site

**Comment by Hotrod369** [comment]
> Looks like `npx expo export -p web` is not building path correctly for expo router entry js path. For example, the path _expo/static/js/web/node_modules%5Cexpo-router%5Centry-4d3ee3ac1dee2ccae600db09a0f66c57.js is not correct if i changed to _expo/static/js/web/node_modules/expo-router/entry-4d3ee3ac1dee2ccae600db09a0f66c57.js, then i am able to see the entry js file served correctly on browser.

I can confirm this. I'm getting the same error that you are. I tried your workaround but I'm still getting the 404 not found error with the updated file path.

**Comment by arun-spar** [comment]
> > Looks like `npx expo export -p web` is not building path correctly for expo router entry js path. For example, the path _expo/static/js/web/node_modules%5Cexpo-router%5Centry-4d3ee3ac1dee2ccae600db09a0f66c57.js is not correct if i changed to _expo/static/js/web/node_modules/expo-router/entry-4d3ee3ac1dee2ccae600db09a0f66c57.js, then i am able to see the entry js file served correctly on browser.
> 
> I can confirm this. I'm getting the same error that you are. I tried your workaround but I'm still getting the 404 not found error with the updated file path.

Just to be sure, Did you changed the path on all the files(index.html, missing.html...) that is referencing this JS file?

**Comment by Hotrod369** [comment]
> > > Looks like `npx expo export -p web` is not building path correctly for expo router entry js path. For example, the path _expo/static/js/web/node_modules%5Cexpo-router%5Centry-4d3ee3ac1dee2ccae600db09a0f66c57.js is not correct if i changed to _expo/static/js/web/node_modules/expo-router/entry-4d3ee3ac1dee2ccae600db09a0f66c57.js, then i am able to see the entry js file served correctly on browser.
> > 
> > 
> > I can confirm this. I'm getting the same error that you are. I tried your workaround but I'm still getting the 404 not found error with the updated file path.
> 
> Just to be sure, Did you changed the path on all the files(index.html, missing.html...) that is referencing this JS file?

I tried your workaround and changed the path just like you did. My app has 5 or so HTML files that I had to edit, but I'm still getting the black screen with 404 error not found on the .js file.

**Comment by ifiokjr** [comment]
I'm bumping into the same issue.

**Comment by arun-spar** [comment]
Please help, how can i get these fixes to my app.

**Comment by lortschi** [comment]
Getting with `npx expo export -p web` also a duplicated assets folder inside dist.
<img width="194" alt="image" src="https://github.com/expo/expo/assets/9847212/dabcef16-c2c7-4f38-85a1-31c7ad3660ce">

**Comment by arun-spar** [comment]
![image](https://github.com/expo/expo/assets/121198022/692b4dd6-3d08-4ae8-bf3e-bfd4c56aed8c)

**Comment by arun-spar** [comment]
![expo_assets](https://github.com/expo/expo/assets/121198022/c094fc5b-d554-42ff-be4c-7da5f76fc6eb)

**Comment by julian-hecker** [comment]
Still seeing some issues on Windows which I think are associated with this. All these errors are happening when using expo 49 with expo-router v2 with app.json expo.web.output = 'static'. It all works perfectly fine with output = 'single', or without expo-router.

`npx expo export -p web` generates a javascript bundle with the following path: `dist\_expo\static\js\web\node_modules%5Cexpo-router%5Centry-5656cb2cd48dddfadacde359b7eaec75.js`

Note the `%5C` in the path. This results in a 404 when serving the page.

In the file name, replacing the %5C with backslashes makes it work, even without changing the script src in the generated html files.

Also fails when running `npx expo start --web --no-dev`, except the error message is `Refused to execute script from 'http://localhost:8081/_expo/static/js/web/node_modules%5Cexpo-router%5Centry-e62ad1b0c047c48d8822a4cab05e3eeb.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`. Navigating to the script results in a 404.

**Comment by marklawlor** [comment]
Hey @arun-spar @julian-hecker can you please create a new issues, its the best way for it to get visibility and assigned to a team member.

**Comment by dzinreach** [comment]
I am running into this issue on Windows using expo@49.0.21.

What is the best workaround for now?

**Comment by marklawlor** [comment]
@dzinreach The reported issues have been resolved. If you are still experiencing this issue then it may be something new and unreported to us. If you'd like a resolution the best way is to simply create a new issue so we can assist you.
