### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by f4z3k4s** [expo/expo#24084]
### Summary

We've found it difficult to implement Google OAuth authentication to Firebase with the Firebase JS SDK that works inside Expo Go. The documentation of Expo (and the links pointing to relevant sections of the Firebase docs) is incomplete regarding this matter.

Based on this [stackoverflow question](https://stackoverflow.com/questions/75924863/expo-go-react-native-application-that-uses-google-authentication-in-firebase/76961872#76961872) others were struggling with it as well.

We've created a [blog post](https://scriptide.tech/blog/autheticate-to-firebase-with-google-oauth-login-with-expo-go-in-managed-expo-workflow-react-native-app) on our website that is a step-by-step guide to implementing this correctly. We think it would be a time saver for others to include it in the official Expo documentation.

Please let us know how we can be of any help regarding this issue.

### Link to the related docs page

https://docs.expo.dev/guides/using-firebase/

**Comment by brentvatne** [comment]
Once you start to implement authentication in your app, I'd recommend moving off of Expo Go. It's too limited of an environment, eg: you can't set up custom deep linking schemes.

**Comment by f4z3k4s** [comment]
@brentvatne Thanks for your reply. I understand that one can move off of Expo Go but as the authentication is doable inside the boundaries of Expo Go, wouldn't it be reasonable to update the docs with the missing parts regarding that? Or if you think that it is anti-pattern to use the JS SDK and stay within Expo Go for a specific reason, that also should be reflected in the docs so people won't burn time on that.

**Comment by brentvatne** [comment]
right, I believe it is an anti-pattern to use Expo Go for longer than necessary on a project. I'm working on some documentation updates to make this more clear!
