### ISSUE TITLE
Is there a way to change UI for biometric authentication in expo-local-authentication

### ISSUE THREAD

**Issue by chetnaag95** [expo/expo#24086]
### Summary

I'm using expo-local-authentication and I need to modify the look and feel of the bio authen modal.

This is what I would like to modify- 

- Change the position of the modal (such as move it to the center of the screen)
- Change the labels Touch the fingerprint sensor
- Change the color of the fingerprint

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/local-authentication/#localauthenticationoptions

**Comment by Gloriouspete** [comment]
@chetnaag95  The color of the fingerprint is not customizable , Nor is the position as this is mostly controlled by the device itself.

But you can change the label, I guess you already knew that but if you don't

```function App() { 
const handleBiometricAuth = async () => { 
const authOptions = { 
promptMessage: 'Custom touch message',  cancelLabel: 'Custom cancel label',
}; try { 
const result = await LocalAuthentication.authenticateAsync(authOptions)} 
catch (error) { 
console.log(error)
 } };
```

**Comment by chetnaag95** [comment]
Can we change this text 
<img width="361" alt="Screenshot 2023-08-23 at 11 49 30 PM" src="https://github.com/expo/expo/assets/82748928/d291399a-cbea-4244-b346-53586c46edd3">

**Comment by Gloriouspete** [comment]
Yes, it's the prompt message I provided.
