### ISSUE TITLE
[docs] ExtraIosPodDependency must be specified in app.config

### ISSUE THREAD

**Issue by robert-nash** [expo/expo#24099]
### Summary

My understanding of Expo Plugins is very fresh so sorry if I am missing the point here.

The documentation for Expo BuildProperties explains how extra iOS Pod dependencies can be added using the expo-build-properties plugin.

My understanding is that it is an intended pattern for plugins to call other plugins. The comments for withBuildProperties seem to anticipate it being used in such a way: https://github.com/expo/expo/blob/b51b5139f2caa2a9495e4132437d7ca612276158/packages/expo-build-properties/src/withBuildProperties.ts#L25

So I tried to use the plugin like this:

```
import { ConfigPlugin } from "expo/config-plugins";
import { withBuildProperties } from "expo-build-properties";

const withMyPlugin: ConfigPlugin = (config) => {
    config = withBuildProperties(config, {
        ios: {
            extraPods: [
                {
                    name: "MyPod",
                    source: "ssh://git@github.com/private-repository/Specs.git",
                },
            ],
        },
    });
    return config;
};

export default withMyPlugin;
```

However this did not seem to have any effect.

Inspecting the source for expo-modules-autolinking it seems that it is only looking in app.config for expo-build-properties and it's configuration and doesn't get the configuration from any calls to withBuildProperties in plugins listed in app.config - https://github.com/expo/expo/blob/b5cd7dc75c50c76aeabef6e39283c67ffc8aab13/packages/expo-modules-autolinking/src/autolinking/extraDependencies.ts#L36

As far as I can tell (please let me know if I am mistaken!) this is atypical behaviour for a plugin and consequently should be added to the documentation for Expo BuildProperties if this is indeed the intended behaviour.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/build-properties/#extraiospoddependency

**Comment by JasonHenson** [comment]
easier way to do this:
https://docs.expo.dev/versions/latest/sdk/build-properties/
npx expo install expo-build-properties
{
  "expo": {
	...
    "plugins": [
      [
        "expo-build-properties",
          "ios": {
            "extraPods": [
              {
                "name": "MyPod",
                "git": "ssh://git@github.com/private-repository/Specs.gi",
              }
            ]
          }
        }
      ]
    ]
  }
}

**Comment by robert-nash** [comment]
@JasonHenson Thank you, that's what I ended up doing in the end. The reason I was trying to do it through a plugin is because this Pod is needed for a expo module I've created so I wanted to encapsulate it all in a plugin packaged with the module but as you point out it is possible to work around this.

**Comment by Kudo** [comment]
hi there! the `extraPods` is slightly different to other properties and unfortunately not supported by `withBuildProperties` in custom plugins. not sure whether [podspec.dependency](https://guides.cocoapods.org/syntax/podspec.html#dependency)? would be good know your use case like fetching pod from private cocoapods repository.

**Comment by robert-nash** [comment]
Thanks @Kudo, I'm glad to know that I'm not missing something. Unless I have missed it, perhaps this could be included in the documentation?

Yes fetching a pod from a private repository is exactly what I am trying to do. I am trying to create a plugin which is private but which I an easily distribute (within a limited circulation). My understanding is that I can only specify the version in podspec.dependency. I don't know if you know of a better way of achieving this?
