### ISSUE TITLE
Is there a way to change text for biometric authentication in expo-local-authentication

### ISSUE THREAD

**Issue by chetnaag95** [expo/expo#24098]
### Summary

Can we change the text touch the fingerprint sensor as shown in the below screen
<img width="396" alt="Screenshot 2023-08-24 at 1 46 11 PM" src="https://github.com/expo/expo/assets/82748928/8aecece9-7524-40bc-85c2-f94a6256d01c">

I have used the option promptMessage to add 'Login with biometric'. Is there any way I can change the text also Not recognised text when wrong fingerprint is scanned

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/local-authentication/#localauthenticationoptions

**Comment by Big-Cheung** [comment]
Hello,

The issues page is used for reporting issues, not asking for help. If you have a question about Expo or related tools, you can visit https://forums.expo.dev/ or join the Discord at https://chat.expo.dev/

To answer your question,

You can keep track of the most recent `LocalAuthenticationResult` in a state. if `LocalAuthentication.authenticateAsync` returns false, then you know that the wrong fingerprint was scanned. You then change the text of `promptMessage` according to state.

`const [rejected, setRejected] = useState(false)`
`let result = LocalAuthentication.authenticateAsync({promptMessage: rejected ? "Not Recognized" : "Login with Biometric"})`
`if (result === false) {` 
`  setRejected(true);`
`  result = LocalAuthentication.authenticateAsync({promptMessage: rejected ? "Not Recognized" : "Login with Biometric"})`
`}` 

Don't forget to close this issue. Thank you!
