### ISSUE TITLE
[sdk 49] Self-signed connection broke in SDK 49

### ISSUE THREAD

**Issue by idrakimuhamad** [expo/expo#24096]
### Summary

I'm using library `react-native-ssl-pinning` and `rn-fetch-blob` as workaround development to connect with a dev server that have a self signed certification. Been using this in Expo 48 and dev-client ~2.2.1.

I recently try to upgrade to SDK 49, and I'm getting certificate error now.

I've tested with react-native-ssl-pinning and rn-fetch-blob, both will received error as below

> The certificate for this server is invalid. You might be connecting to a server that is pretending to be “X.X.X.X” which could put your confidential information at risk.

This doesn't happen when I'm on SDK 48.x as listed below.

```
"expo": "48.0.0",
"expo-dev-client": "^2.2.1",
"expo-splash-screen": "^0.18.2",
"expo-status-bar": "~1.4.4",
"react": "18.2.0",
"react-native": "0.71.8",
"rn-fetch-blob": "^0.12.0"
```

After installing my dependencies one by one, I figure that it is caused by `expo-dev-client`, although I do not know which part of it causing it.

This is the environment used in the reproduction repo.

```
"expo": "~49.0.5",
"expo-dev-client": "~2.4.6",
"expo-status-bar": "~1.6.0",
"react": "18.2.0",
"react-native": "0.72.3",
"rn-fetch-blob": "^0.12.0",
"expo-splash-screen": "~0.20.4"
```

I'm on `bare` workflow which I generate with `prebuild`, not sure why the expo-env-info returning as `manage`. This happened on both iOS and Android, but my reproduction is only on iOS.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android, iOS

### Package versions

"expo-dev-client": "~2.4.6",
"expo-status-bar": "~1.6.0",
"rn-fetch-blob": "^0.12.0",
"expo-splash-screen": "~0.20.4"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/idraki/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 15.0/15A5195k - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.5 => 49.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: managed

### Reproducible demo

https://github.com/idrakimuhamad/repro-expo-ssl-self-sign

**Comment by idrakimuhamad** [comment]
Just to update; I'm able to use SDK 49 by upgrading all the dependencies **except** expo-dev-client and expo-updates. I'm not using expo-updates anyway, and it seems to be the only one related to the dev client somehow. So I remove expo-updates, and pin dev client to 2.2.1, and able to run the app, and having no problem with the invalid SSL (using the SSL fetch)

**Comment by quaos** [comment]
Hi.

Also run into this issue. Here is my [reproduction repo](https://github.com/quaos/test-expo-ssl-pinning-1/tree/with-expo-dev-client-updates) with Expo SDK 49.0 + expo-dev-client v2.4.12

I just tried downgrading expo-dev-client to v2.2.1, and it worked on iOS concerning SSL pinning.

However, there are incompatibilities in Android. I have to do some Android patches on some expo packages' `build.gradle` until it can be built successfully. But eventually the app got crashed on init:

```
Android Bundling complete 399ms
 ERROR  Your app just crashed. See the error below.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quaos.testexposslpinning1/expo.modules.devmenu.DevMenuActivity}: kotlin.UninitializedPropertyAccessException: lateinit property rootView has not been initialized
  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
  android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
  ...
```

**Comment by idrakimuhamad** [comment]
> Hi.
> 
> 
> 
> Also run into this issue. Here is my [reproduction repo](https://github.com/quaos/test-expo-ssl-pinning-1/tree/with-expo-dev-client-updates) with Expo SDK 49.0 + expo-dev-client v2.4.12
> 
> 
> 
> I just tried downgrading expo-dev-client to v2.2.1, and it worked on iOS concerning SSL pinning.
> 
> 
> 
> However, there are incompatibilities in Android. I have to do some Android patches on some expo packages' `build.gradle` until it can be built successfully. But eventually the app got crashed on init:
> 
> 
> 
> ```
> 
> Android Bundling complete 399ms
> 
>  ERROR  Your app just crashed. See the error below.
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quaos.testexposslpinning1/expo.modules.devmenu.DevMenuActivity}: kotlin.UninitializedPropertyAccessException: lateinit property rootView has not been initialized
> 
>   android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
> 
>   android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
> 
>   ...
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> 

Yeah for Android you gotta bump the Android target. I do not have the same error as yours for this one. 

But I didn't proceed with the 49 and still stuck with the 48, as I'm not certain it is stable enough with the dev client being pinned to one version, other modules might require it to be on the latest version in the future.

**Comment by quaos** [comment]
> > Hi.
> > Also run into this issue. Here is my [reproduction repo](https://github.com/quaos/test-expo-ssl-pinning-1/tree/with-expo-dev-client-updates) with Expo SDK 49.0 + expo-dev-client v2.4.12
> > I just tried downgrading expo-dev-client to v2.2.1, and it worked on iOS concerning SSL pinning.
> > However, there are incompatibilities in Android. I have to do some Android patches on some expo packages' `build.gradle` until it can be built successfully. But eventually the app got crashed on init:
> > ```
> > 
> > Android Bundling complete 399ms
> > 
> >  ERROR  Your app just crashed. See the error below.
> > 
> > java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quaos.testexposslpinning1/expo.modules.devmenu.DevMenuActivity}: kotlin.UninitializedPropertyAccessException: lateinit property rootView has not been initialized
> > 
> >   android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
> > 
> >   android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
> > 
> >   ...
> > ```
> 
> Yeah for Android you gotta bump the Android target. I do not have the same error as yours for this one.
> 
> But I didn't proceed with the 49 and still stuck with the 48, as I'm not certain it is stable enough with the dev client being pinned to one version, other modules might require it to be on the latest version in the future.

Did you mean bumping Android Target API version in `targetSdkVersion`? Mine is set to 33. Which version do you set yours to?

**Comment by idrakimuhamad** [comment]
@Kudo I looked at the RN SSL public key pinning library, it seems affecting them too. I can't use that library due to my dev env are only on IP (don't ask me why) and mixing multi fetch aren't probably the best, so we stick we RN SSL pinning, but seems the maintainer found the possible issue that relates to the expo-dev-client intercepting the request and disregard any pinning configuration. Should be working on production, but for us it's hampering our development.

https://github.com/frw/react-native-ssl-public-key-pinning/issues/223#issuecomment-1921513813

**Comment by idrakimuhamad** [comment]
I've found sort of workaround, at least on SDK 50. I tried upgrading my project to SDK 50, after much effort, I got my self-signed API connected using the same setup I had in SDK 48. All you gotta do is to disable the expo's dev client network inspector and build, and it's working.

This is very early but I haven't tests on Android. Will update soon.
