### ISSUE TITLE
Custom buttons on dev-menu only appear after second app start on android

### ISSUE THREAD

**Issue by clementDours** [expo/expo#24104]
### Summary

**What I'm trying to do** : I wanted to add a custom button to the dev-menu in my app. 

<img width="539" alt="image" src="https://github.com/expo/expo/assets/49022267/294b2072-97f7-456c-b8ee-48b9c1c4685e">

**What I did** : I followed this doc https://docs.expo.dev/develop/development-builds/development-workflows/#extensions. 
I tried a minimal exemple on a fresh app. It works fine on IOS (see reproducible exemple below).

**What my problem is** : On android, the button will only appear after I kill the app and start it again.

**What I tried** :
 - Putting it in the background and opening it again does not work. 
 - Reloading the app through a dev server does not work, I really need to restart it entirely. 
 - I tried on both emulator and real device.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

expo-dev-client : 3.1.10
expo: 49.0.0
expo-dev-client: 2.4.8
eas-cli : 4.1.2
expo-updates: 0.18.8

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/Library/Caches/fnm_multishells/29553_1692626477236/bin/node
      Yarn: 3.6.1 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - ~/Library/Caches/fnm_multishells/29553_1692626477236/bin/npm
      Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: bare

### Reproducible demo

```
import { registerDevMenuItems } from 'expo-dev-menu';
import { useEffect } from 'react';
import { View } from 'react-native';

const AppContent = () => {
  return (
    <View style={{ width: '100%', height: '100%', backgroundColor: 'grey' }} />
  );
};

const App = () => {
  useEffect(() => {
    console.log('entered the useEffect');
    const devMenuItems = [
      {
        name: `My custom button`,
        callback: () => {
          console.log('toto');
        },
      },
    ];
    registerDevMenuItems(devMenuItems);
  }, []);

  return <AppContent />;
};

export default App;
```

**Comment by rikur** [comment]
Still have to close the app and re-open it to see the DevMenu on Android. Have not tested on SDK 50

**Comment by altick** [comment]
I am experiencing the same issue with Expo 50 on Android. The items are not added to the DevMenu when running the development build. I have to close the build and reopen it to have the items visible in the DevMenu.

**Comment by rikur** [comment]
Still an issue. It's cumbersome when we run automated Maestro tests, because at the start of every test run we have to kill the app and re-run it.

**Comment by kutsan** [comment]
This should be re-opened, it still exists.

**Comment by rikur** [comment]
@expo-bot re-open :P

**Comment by trajano** [comment]
Yup I can confirm this does not work correctly on Android on my not-so-MVCE

https://github.com/trajano/expo-experiments/blob/e59b614bab857e18d111d10423b062ac85f747fc/packages/my-app/src/app/_layout.tsx#L29-L47

**Comment by Watchara242540** [comment]
ขอปิดการใช้งานทุกระบบ

ในวันที่ พฤ. 31 ต.ค. 2024 02:45 น. Archimedes Trajano <
***@***.***> เขียนว่า:

**Comment by Watchara242540** [comment]
ขอปิดการใช้งานทุกระบบ

ในวันที่ พฤ. 28 พ.ย. 2024 03:39 น. wat noii4 ***@***.***>
เขียนว่า:
