### ISSUE TITLE
[SDK49][Linking] `createURL` does not create links according to documentation when using EAS Update

### ISSUE THREAD

**Issue by blimmer** [expo/expo#24114]
### Minimal reproducible example

https://github.com/blimmer/expo-createurl-bug/pull/1

## Context

I'm currently working to transition my app from Classic Updates to EAS Update, and I'm running into a problem with how the Linking `createURL` function works with EAS updates.

I use [AWS Cognito](https://aws.amazon.com/cognito/) for my authentication solution. Cognito does not allow wildcards in callback URLs used during the sign-in process. Therefore, I create a fixed set of Expo release channels that I safelist with Cognito. With classic updates, these URLs looked like this:

```
exp://exp.host/@blimmer_hb/createurl-bug/--/?release-channel=channel-0
exp://exp.host/@blimmer_hb/createurl-bug/--/?release-channel=channel-1
...
exp://exp.host/@blimmer_hb/createurl-bug/--/?release-channel=channel-9
```

This was great because I could allow auth with Expo Go against these fairly static URLs. If you scan the Expo Go QR code on my sample repo's PR (https://github.com/blimmer/expo-createurl-bug/pull/2), you'll see that the link is properly generated.

![IMG_A5244C319340-1](https://github.com/expo/expo/assets/630449/fe7d55fa-e84c-475e-b748-0b2522a593db)

By "properly generated", I mean that calling `createURL` in my app returns the URL with the release channel embedded.

## EAS Update

With EAS Update, this link is much more variable, which is problematic for Cognito. It also does not match the current [documentation](https://docs.expo.dev/guides/linking/#creating-urls) of how `createURL()` should work.

According to the current version of those docs, `createURL()` for Expo Go should produce URLs that look like this:

```
exp://u.expo.dev/[project-id]?channel-name=[channel-name]&runtime-version=[runtime-version]
```

However, this is not the behavior I'm observing. You can see this in my sample repo PR: https://github.com/blimmer/expo-createurl-bug/pull/1 .

This repo is the result of `create-expo-app` and a simple App.tsx file that just prints out a URL produced by `createURL()`:

```tsx
import { createURL } from 'expo-linking';
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  const link = createURL('/')

  return (
    <View style={styles.container}>
      <Text>The link is {link}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

### PR Preview QR Code

When you scan the QR code produced by the `expo/expo-github-action/preview@v8` GitHub action, the URL looks like this:

![IMG_B8872B9D1135-1](https://github.com/expo/expo/assets/630449/5afdee78-6dfd-4d15-a9db-8013a5e6158b)

```
exp://u.expo.dev/[project-id]/group/[group-id]//--/
```

This is particularly bad for Cogntio because the group-id changes with each EAS update, making it impossible to safelist redirect URLs. Most importantly, it doesn't match the docs.

### Manually Crafted URL

If I manually craft a URL like the one specified in the docs (`exp://u.expo.dev/b11987c7-69e6-441c-bdac-6f1b68f0f4fb?channel-name=preview&runtime-version=1.0.0`), it will open the preview app in Expo Go, as expected.

However, `createURL()` again produces a URL that's different from the documentation.

![IMG_C9BBE781AB92-1](https://github.com/expo/expo/assets/630449/91105952-b017-4ddf-9ba1-5b511f40edb4)

This time it's closer, but the required `channel-name=[channel-name]&runtime-version=[runtime-version]` parameters are not included.

## Summary

I saw in https://github.com/expo/expo/issues/24084#issuecomment-1690751805 that there's a tendency toward "auth doesn't necessarily work in Expo Go", you should start using development builds.

However, that's a bummer for us because we're losing functionality by moving to the more expensive EAS Update process.

Either way, the documentation is currently incorrect. From the gist of the linking docs, it feels like the `createURL()` should create a stable URL. I think in all cases, the `createURL()` should return a URL as specified in the documentation, even if access through the Pull Request QR code (e.g., `exp://u.expo.dev/[project-id]?channel-name=[channel-name]&runtime-version=[runtime-version]`).

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.16.0/bin/yarn
      npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: managed
```

**Comment by blimmer** [comment]
Additionally, the Expo Go link format including a path into the app doesn't work either:

![Screenshot 2023-08-25 at 11 29 01](https://github.com/expo/expo/assets/630449/8014c7b7-230d-4857-aaab-3a45b51b28e2)

If I open a link like:

```
exp://u.expo.dev/b11987c7-69e6-441c-bdac-6f1b68f0f4fb?channel-name=preview&runtime-version=1.0.0/--/test
```

I get an error because the URL isn't parsed correctly.

![IMG_45DD84A1F078-1](https://github.com/expo/expo/assets/630449/b3953310-b553-4d23-b040-e7b005473ba0)

It doesn't throw this error if I put the query parameters at the end of the URL, e.g.,

```
exp://u.expo.dev/b11987c7-69e6-441c-bdac-6f1b68f0f4fb/--/test?channel-name=preview&runtime-version=1.0.0
```

But, again, this doesn't match the docs.

**Comment by wschurman** [comment]
Looking into this now.

**Comment by wschurman** [comment]
It looks like the URL in this documentation/guide was [auto-find-replaced in this blame PR](https://github.com/expo/expo/pull/18262), so the documentation is incorrect, which is a good find. I'll update the docs.

As for a path forward, deep linking into Expo Go is a pretty tough thing to consistently do. We've also deprecated auth session which suffered from a similar issue: https://blog.expo.dev/security-advisory-for-developers-using-authsessions-useproxy-options-and-auth-expo-io-e470fe9346df. What we recommend is to use a development client and your custom deep link scheme: https://docs.expo.dev/guides/linking/#linking-to-your-app
