### ISSUE TITLE
![image](https://github.com/expo/expo/assets/5756752/bccb55ff-c0a8-489d-aaab-21bffa61ae36)

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [expo/expo#24115]
![image](https://github.com/expo/expo/assets/5756752/bccb55ff-c0a8-489d-aaab-21bffa61ae36)
[[screen-orientation][ios] Screen Orientation module audit](https://github.com/expo/expo/pull/22152#top) doesn't work on expo 49 either.

_Originally posted by @Darkhorse-Fraternity in https://github.com/expo/expo/issues/22152#issuecomment-1692710281_

**Comment by behenate** [comment]
Hi!
Could you please add a proper title and description to the issue? Make sure that the report is in line with our issue template.
