### ISSUE TITLE
Failed to upload the project tarball to EAS Build

### ISSUE THREAD

**Issue by 1623311678** [expo/expo#24128]
### Summary

<img width="658" alt="image" src="https://github.com/expo/expo/assets/41052302/2345669f-4dfe-443d-81e1-9d7949a48c81">

Failed to upload the project tarball to EAS Build

Reason: request to https://storage.googleapis.com/turtle-v2-projects/production/7d986165-0e82-4ff4-a727-b8db7f25a3bf/44f08583-bb2d-4960-a505-bfff92b5a027?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=www-production%40exponentjs.iam.gserviceaccount.com%2F20230827%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230827T122602Z&X-Goog-Expires=3601&X-Goog-SignedHeaders=host%3Bx-goog-content-length-range&X-Goog-Signature=440fc8b7b54e18a81fff9b4f5a8bc6da7a5bb1a86f3b7c40eca8c41d9205e11e53aa9ff3146b12e95e511cc97146f27cf257a69bbff924899f800cce6b18fbfeb0df90d812c0e9794bb0fff4c1fe152dd2cea68c762b0518c26e6eae124bc003ab7c40e5458259138ee11822863debdb19b9365fdb19e0c0012351337ffd73fbeeefed011c8fa2fc32acca428d8970ed7972b2631700b16c4114db28d5981aa090fa3dfd511dde549f691f78d43ac6dc03cb744e39591a321095dcd8e0cd10f5beaff5ff93202e6edd0a0f8f90ed29674811b0421a7f133390b918c8a782d7bf95553cec58824d68c3b88907ab9619b80293402715d99e2fb7868c4c93c054e6 failed, reason: read ECONNRESET

### SDK Version

48

### Environment

<img width="647" alt="image" src="https://github.com/expo/expo/assets/41052302/5077d9ab-9c0e-4a00-ad9d-f0ff4c57a01a">

### Minimal reproducible example

1 git clone

2 npm install 

3 eas build -p android --profile preview

4 will found error:
Failed to upload the project tarball to EAS Build

Reason: request to https://storage.googleapis.com/turtle-v2-projects/production/7d986165-0e82-4ff4-a727-b8db7f25a3bf/44f08583-bb2d-4960-a505-bfff92b5a027?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=www-production%40exponentjs.iam.gserviceaccount.com%2F20230827%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230827T122602Z&X-Goog-Expires=3601&X-Goog-SignedHeaders=host%3Bx-goog-content-length-range&X-Goog-Signature=440fc8b7b54e18a81fff9b4f5a8bc6da7a5bb1a86f3b7c40eca8c41d9205e11e53aa9ff3146b12e95e511cc97146f27cf257a69bbff924899f800cce6b18fbfeb0df90d812c0e9794bb0fff4c1fe152dd2cea68c762b0518c26e6eae124bc003ab7c40e5458259138ee11822863debdb19b9365fdb19e0c0012351337ffd73fbeeefed011c8fa2fc32acca428d8970ed7972b2631700b16c4114db28d5981aa090fa3dfd511dde549f691f78d43ac6dc03cb744e39591a321095dcd8e0cd10f5beaff5ff93202e6edd0a0f8f90ed29674811b0421a7f133390b918c8a782d7bf95553cec58824d68c3b88907ab9619b80293402715d99e2fb7868c4c93c054e6 failed, reason: read ECONNRESET

**Comment by 1623311678** [comment]
we need a vpn ,for China,if we want to eas publish sucess

**Comment by 1623311678** [comment]
但是我的疑惑是为什么我们之前可以用eas发布，现在不行，大概是切换到了谷歌云吧，期望eas可以做一下兼容，让中国的用户不用vpn也可以发布eas

**Comment by panlei0922** [comment]
你解决了吗？翻墙打包也报这个错

**Comment by 1623311678** [comment]
解决了。翻墙没问题。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 19:48 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [expo/expo] Failed to upload the project tarball to EAS Build(Issue #24128)




 
你解决了吗？翻墙打包也报这个错

**Comment by 1623311678** [comment]
先看下翻墙之后能不能访问谷歌云，能访问应该就行。估计用了谷歌云



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 19:48 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [expo/expo] Failed to upload the project tarball to EAS Build(Issue #24128)




 
你解决了吗？翻墙打包也报这个错

**Comment by panlei0922** [comment]
奇怪了，我能访问https://cloud.google.com网址，你说的是这个地址能否访问吗？但打包还是提示Failed to upload the project tarball to EAS Build

**Comment by 1623311678** [comment]
等我明天上班再试试吧，



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 20:25 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [expo/expo] Failed to upload the project tarball to EAS Build(Issue #24128)




 
奇怪了，我能访问https://cloud.google.com网址，你说的是这个地址能否访问吗？但打包还是提示Failed to upload the project tarball to EAS Build

**Comment by 1623311678** [comment]
你可能需要升级到最新的eas-cli然后再试一下，他们之前貌似要升级来的。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 20:25 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [expo/expo] Failed to upload the project tarball to EAS Build(Issue #24128)




 
奇怪了，我能访问https://cloud.google.com网址，你说的是这个地址能否访问吗？但打包还是提示Failed to upload the project tarball to EAS Build

**Comment by panlei0922** [comment]
好的，谢谢

**Comment by 1623311678** [comment]
升级到最新的eas-cli



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 20:32 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [expo/expo] Failed to upload the project tarball to EAS Build(Issue #24128)




 
好的，谢谢

**Comment by panlei0922** [comment]
eas-cli已经是最新的

**Comment by 1623311678** [comment]
> eas-cli已经是最新的

刚试了一下，我是可以eas发布的

**Comment by 1623311678** [comment]
刚试了一下eas我是可以的，



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 20:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [expo/expo] Failed to upload the project tarball to EAS Build(Issue #24128)




 
eas-cli已经是最新的

**Comment by Tefris** [comment]
![image](https://github.com/expo/expo/assets/67229482/55bea1cf-eb19-45e8-a389-951820a0defd)

**Comment by Tefris** [comment]
我现在一直在报这个错，谷歌云我也能访问，vpn服务也开了，但还是报这个错

**Comment by 1623311678** [comment]
> 我现在一直在报这个错，谷歌云我也能访问，vpn服务也开了，但还是报这个错

 如果还没解决，可以加我微信a1623311678 帮你看下

**Comment by 1623311678** [comment]
统一回复，如果还没解决的兄弟，可以加我微信a1623311678 帮你看下

**Comment by xuergo** [comment]
开全局代理不成的兄弟，需要将终端也也代理一下 export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890 这是clashX的

**Comment by panlei09** [comment]
我的clashX默认没有勾选TUN模式，把TUN模式选上解决了问题。

**Comment by LynasTing** [comment]
@xuergo 好使哦水儿。
