### ISSUE TITLE
[media-library] Android 13 Permissions

### ISSUE THREAD

**Issue by iM-GeeKy** [expo/expo#24122]
### Summary

When invoking [`await MediaLibrary.requestPermissionsAsync()`](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibraryrequestpermissionsasyncwriteonly) on Android 13, two permission prompts appear asking for music/audio followed by photos/videos. According to the android developer docs in Android 13 or higher they have introduced more [granular permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions). I'm interested in only presenting the user with a single prompt (as I don't need to ask for music/audio) which appears would be [`READ_MEDIA_IMAGES`](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES), but adding that permission doesn't seem to do the trick. I also don't see that permission in the list of [available permissions](https://docs.expo.dev/versions/latest/config/app/#permissions). Lastly it looks like this was [addressed](https://github.com/expo/expo/pull/20907) in the past, but perhaps I'm missing something. 

**Screenshots**
<img src="https://github.com/expo/expo/assets/7604441/290f8bd9-f380-4384-968f-67a66c889b22" width="200"/>
<img src="https://github.com/expo/expo/assets/7604441/8599599c-80ff-469e-9956-aeafe903ed6f" width="200"/>
<img src="https://github.com/expo/expo/assets/7604441/9ae1af49-4999-4eea-97ee-c2967711e786" width="200"/>

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

```json
"expo": "~49.0.8",
"expo-dev-client": "~2.4.8",
"expo-media-library": "~15.4.1",
"expo-status-bar": "~1.6.0",
"expo-updates": "~0.18.12",
"react": "18.2.0",
"react-native": "0.72.4"
```

### Environment

```
expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 13.5
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  npmPackages:
    expo: ~49.0.8 => 49.0.8 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.4 => 0.72.4 
  npmGlobalPackages:
    eas-cli: 4.1.2
    expo-cli: 6.3.10
  Expo Workflow: managed
```

### Reproducible demo

https://github.com/iM-GeeKy/media-permissions

**Comment by Kudo** [comment]
hi there! as you mentioned, the granular permissions is done by #20907, the double prompts are expected since we requested `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` at the same time. as for your use case that you don't need audios, what if we add separately `MediaLibrary.requestAudioPermissionsAsync` and `MediaLibrary.requestVideoPermissionsAsync` functions? not promise anything, we still look over the api and consistency between android and ios.

**Comment by iM-GeeKy** [comment]
> hi there! as you mentioned, the granular permissions is done by #20907, the double prompts are expected since we requested `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` at the same time. as for your use case that you don't need audios, what if we add separately `MediaLibrary.requestAudioPermissionsAsync` and `MediaLibrary.requestVideoPermissionsAsync` functions? not promise anything, we still look over the api and consistency between android and ios.

I think that would make sense. My use case, which seems fairly common, is having the user upload a profile picture and as an end user it would seem bizarre for an application to ask for music and audio pictures just to upload an image. Another concern I also have is the app potentially getting rejected to do over extending your permissions when those permissions are not being used elsewhere in the application.

Thank you for looking into this though!

**Comment by rosenbobev** [comment]
Hey I'm trying to have only add images to gallery permission. But no result yet. I tried to remove permissions and block some. But it is always asking for sound and photos permission. And the photo permissions are working. However my app has function to save view as image to your gallery so I don't need the prompt to be with select photos option it will scare the user. I want to be like "This app would like to add to your photos" - I made it on iOS with a help of another library but on Android no result yet - any ideas ?

**Comment by witheroux** [comment]
As a temporary solution, you could just create a patch using `patch-package` to remove the request for audio permissions. This obviously doesn't fix it in Expo Go, but the result is as expected following a build. Here's the [gist for this patch](https://gist.github.com/witheroux/ca22fe1a36d4315021c7311445b334b0) which I am using in a project.

**Comment by iM-GeeKy** [comment]
It would be nice to get some resolution on this. Commenting to keep from closing.

**Comment by omerjamshed8** [comment]
The issue is Medialibrary.requestPermissions async is working fine in android version <=12 but on on >=13 its not asking for permissions from the user. If anyone could help please provide the solution.

**Comment by Hosam-hsm** [comment]
I'm facing the same issue. I only need to get the images and videos from user's device (MEDIA AUDIO) is not required. But when I use MediaLibrary.requestPermissionsAsync() it is first asking permission to read audio files from device which is not what I'm expecting. How to specify that it should only ask permission for reading image and video?
