### ISSUE TITLE
Snack autosave causes editing to be reverted starting at 11th of October (Now also prevents hot-reload)

### ISSUE THREAD

**Issue by omrihaim** [expo/expo#2413]
After online version upgrade of Snack on 11th of October afternoon, cursor stopped moving as expected and editing goes back to previous version once in a while when autosaved occurs.

Try developing on Snack, and you will notice your edits are constantly erased every few minutes when autosave happens, forcing you to rewrite your code.

This is critical back after version upgrade, and I would recommend a revert if possible.

**Comment by tcdavis** [comment]
Thanks Omri, and sorry for the regression!
Can you confirm that this has been fixed after upgrading to the latest version?

**Comment by omrihaim** [comment]
Hey. Thank you for the fast change, and completely understand the complexity and appreciate the agility. It seems to solve the editing, but also think the autosave work not as good as before, and I've just done reload and lost few minutes of development. Still better then before.

**Comment by omrihaim** [comment]
It seems the auto save used to be done more frequently, but i think the most important current issue is that hot reloading stopped to work in the new auto-save version. 
When working with Snack and Expo App, I constantly have two versions of the app I am working on, and the hot-reload dont work as I am running one version and the new saved (and auto-saved) version runs on the other application.

**Comment by omrihaim** [comment]
Working on one project using Snack. When running an instance over my phone, making a change and want to test is, because hot reload stopped working, I close the expo app and reopen it, and get 2 projects online and recently in development, one in original name and second one in temporary name. Each of them represent the same project, and if I am not mistaken only one of the them the latest version.
Please let me know if I can supply more details.

**Comment by tcdavis** [comment]
Thanks, I see.
We definitely need to reduce the lifetime of the development sessions, but I don't think there's a bug here.  What is happening is one of the development sessions (and presumably the one you connected to) isn't connected to the active editor so it will load the last thing that was saved but won't receive any changes.
If you can connect by scanning the QR code or changing the name so you can be confident you're getting the active session you should be back in business.

Thanks for helping me understand how confusing that can be though!
