### ISSUE TITLE
Android Fetch and Graphql requests hang for several minutes

### ISSUE THREAD

**Issue by JKKholmatov** [expo/expo#24144]
### Minimal reproducible example

https://github.com/JKKholmatov/my-app/tree/master

### Summary

in a Android Expo project Fetch and Graphql requests sometimes hang for several minutes before being sent, even after APK build,

I tried to fetch jsonplaceholder.typicode.com and hanging still occurs:
1 - I created app via npx create-expo-app my-app
2 - Added a TouchabpleOpacity button that calls fetchJson function
3 - Open via Expo Go
4 - Leave the phone for 5 minutes
5 - Press button
6 - Loading for ~2 minutes (if not again leave for 5 minutes)

Here is Logs:
LOG 12:53:17 Fetch start
LOG {"completed": false, "id": 1, "title": "delectus aut autem", "userId": 1}
LOG 12:55:39 Fetch End

Sometimes it takes 2 seconds to get response, sometimes it waits ~2 minutes to send request,
And this happens with every web requests

### Environment

System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: managed

**Comment by JKKholmatov** [comment]
> https://google.com

Hi, thanks for an attention, I tested with `https://github.com/` and `https://google.com/` unfortunately the issue still occurs.
Did you tested on Android via Expo Go and leave the phone for 5 minutes without any interraction as I mentioned above? because that's the way to reproduce the issue for me.

I tested on iPhone and it works as expected, and tested on Android via VPN and it works as expected, without VPN it hangs for 2 minutes again.
I found almost the same issue but there is not provided any solution:
https://github.com/expo/expo/issues/2756

**Comment by Kudo** [comment]
hi! yes i did wait 5 minutes on a pixel 6 android 12 device and it works. i understand that is a pain for this problem, but we cannot reproduce the problem and further investigate for you.
some thought in my mind may help for the troubleshooting:
  - you could probably use some tools like [mitmproxy](https://mitmproxy.org/) or [Charles proxy](https://www.charlesproxy.com/) to intercept the http requests from your devices. 
  - does it happen on a [development build](https://docs.expo.dev/develop/development-builds/introduction/)?
    - for development builds, you could also set java breakpoints at [ExpoNetworkInspectOkHttpInterceptors](https://github.com/expo/expo/blob/284bb8887638b6c52273aea5d234288478ffff66/packages/expo-modules-core/android/src/main/java/expo/modules/kotlin/devtools/ExpoNetworkInspectOkHttpInterceptors.kt) and see whether the request is sending out.
  - does it happen on a bare react-native project?
  - does it happen on a pure android app?

**Comment by JKKholmatov** [comment]
> * you could probably use some tools like [mitmproxy](https://mitmproxy.org/) or [Charles proxy](https://www.charlesproxy.com/) to intercept the http requests from your devices.

I added [NetInfo](https://github.com/react-native-netinfo/react-native-netinfo) library to fetch network state at the time when fetching starts and did some investigation into `node_modules/react-native/Libraries/Network/XMLHttpRequest.js` file.
I added `console.log`s into `XMLHttpRequest.open` and `XMLHttpRequest.send.doSend` to track fetch logs:
Then I caught the hang, here is logs:
 ```
 LOG  12:29:02 Fetch start
 LOG  12:29:02 Connection details {"carrier": "Beeline UZ", "cellularGeneration": "4g", "isConnectionExpensive": true}
 LOG  12:29:02 Is connected true
 LOG  12:29:02 Is reachabel true
 LOG  12:29:02 XMLHttpRequest.open https://jsonplaceholder.typicode.com/todos/1
 LOG  12:29:02 XMLHttpRequest.doSend https://jsonplaceholder.typicode.com/todos/1
 LOG  12:31:19 Response {"completed": false, "id": 1, "title": "delectus aut autem", "userId": 1}
 LOG  12:31:19 Fetch End
```
I see hang occurs after XMLHttpRequest.send method, does this give you any additional information for you to direct me for further investigations?

**Comment by JKKholmatov** [comment]
@Kudo I assume I am having this issue [Android fetch hangs indefinitely with IPv6 hosts on some devices (Happy Eyeballs)](https://github.com/facebook/react-native/issues/32730#top). Is there any way to apply OkHTTP 5.0.0-alpha.11 version in Expo project?

**Comment by Kudo** [comment]
nice finding for okhttp issue. you could use the config-plugin to add the gradle resolution to override the okhttp version.

```patch
--- a/app.json
+++ b/app.json
@@ -25,6 +25,9 @@
     },
     "web": {
       "favicon": "./assets/favicon.png"
-    }
+    },
+    "plugins": [
+      "./withOkHttp5"
+    ]
   }
 }
--- /dev/null
+++ b/withOkHttp5.js
@@ -0,0 +1,21 @@
+const { withProjectBuildGradle } = require('expo/config-plugins');
+
+const withOkHttp5 = (config) => {
+  return withProjectBuildGradle(config, (config) => {
+    const block = `\
+allprojects {
+  configurations.all {
+    resolutionStrategy {
+      force('com.squareup.okhttp3:okhttp:5.0.0-alpha.11')
+      force('com.squareup.okhttp3:okhttp-urlconnection:5.0.0-alpha.11')
+    }
+  }
+}`;
+    if (config.modResults.contents.search(block) === -1) {
+      config.modResults.contents += `\n${block}`;
+    }
+    return config;
+  });
+};
+
+module.exports = withOkHttp5;
```

we don't officially support okhttp 5, there is one build error from expo-file-system, you should use patch-package to workaround it

`patches/expo-file-system+15.4.3.patch`
```patch
diff --git a/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.kt b/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.kt
index 3b764b6..e6412db 100644
--- a/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.kt
+++ b/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.kt
@@ -177,7 +177,7 @@ open class FileSystemModule : Module() {
 
       // TODO:Bacon: Add more encoding types to match iOS
       val encoding = options.encoding
-      var contents: String?
+      var contents: String? = null
       if (encoding == EncodingType.BASE64) {
         getInputStream(uri).use { inputStream ->
           contents = if (options.length != null && options.position != null) {

```
