### ISSUE TITLE
[Expo-AV] Recording not prepared

### ISSUE THREAD

**Issue by pecabum** [expo/expo#24143]
### Minimal reproducible example

https://snack.expo.dev/USG7rtZvD

### Summary

I've used the code from official documentation for recording. Code of the recording function is in the snack link. 
I'm getting `Error: Prepare encountered an error: recorder not prepared.`

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.asdf/installs/nodejs/16.17.1/bin/node
      npm: 9.7.2 - ~/.asdf/installs/nodejs/16.17.1/.npm/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/petarpetrov/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 25, 28, 30, 31, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1
        System Images: android-33 | Google APIs ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.4 => 0.17.4 
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ^49.0.0 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: bare

**Comment by Kudo** [comment]
hi there! your snack example code has some error and i tried to resolve by the following code.

```ts
import { useEffect } from 'react';
import { View } from 'react-native';
import { Audio, InterruptionModeIOS, InterruptionModeAndroid } from 'expo-av';

export default function App() {
  useEffect(() => {
    startRecording();
  }, []);
  return (
    <View></View>
  );
}

async function startRecording() {
  try {
    console.log('Requesting permissions..');
    await Audio.requestPermissionsAsync();
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: true,
      interruptionModeIOS: InterruptionModeIOS.DoNotMix,
      playsInSilentModeIOS: true,
      shouldDuckAndroid: true,
      interruptionModeAndroid: InterruptionModeAndroid.DoNotMix,
      playThroughEarpieceAndroid: false,
      staysActiveInBackground: true,
    });

    console.log('Starting recording..');
    const { recording } = await Audio.Recording.createAsync(Audio.RecordingOptionsPresets.HIGH_QUALITY);
    // this.recording = recording;
    console.log('Recording started');
  } catch (err) {
    console.error('Failed to start recording', err);
  }
}
```

it works for me on ios expo-go
```
 LOG  Requesting permissions..
 LOG  Starting recording..
 LOG  Recording started
```

could you upload a minimal reproducible example to some git repository and we would like to further investigate for you? thanks!

**Comment by pecabum** [comment]
> hi there! your snack example code has some error and i tried to resolve by the following code.
> 
> ```ts
> import { useEffect } from 'react';
> import { View } from 'react-native';
> import { Audio, InterruptionModeIOS, InterruptionModeAndroid } from 'expo-av';
> 
> export default function App() {
>   useEffect(() => {
>     startRecording();
>   }, []);
>   return (
>     <View></View>
>   );
> }
> 
> async function startRecording() {
>   try {
>     console.log('Requesting permissions..');
>     await Audio.requestPermissionsAsync();
>     await Audio.setAudioModeAsync({
>       allowsRecordingIOS: true,
>       interruptionModeIOS: InterruptionModeIOS.DoNotMix,
>       playsInSilentModeIOS: true,
>       shouldDuckAndroid: true,
>       interruptionModeAndroid: InterruptionModeAndroid.DoNotMix,
>       playThroughEarpieceAndroid: false,
>       staysActiveInBackground: true,
>     });
> 
>     console.log('Starting recording..');
>     const { recording } = await Audio.Recording.createAsync(Audio.RecordingOptionsPresets.HIGH_QUALITY);
>     // this.recording = recording;
>     console.log('Recording started');
>   } catch (err) {
>     console.error('Failed to start recording', err);
>   }
> }
> ```
> 
> it works for me on ios expo-go
> ```
>  LOG  Requesting permissions..
>  LOG  Starting recording..
>  LOG  Recording started
> ```
> 
> could you upload a minimal reproducible example to some git repository and we would like to further investigate for you? thanks!

It doesn't work on a real device.

**Comment by Kudo** [comment]
i did test on iphone 11 (ios 16.6) with expo go and it still works 🤔

**Comment by pecabum** [comment]
@Kudo i am using the bare workflow, with expo go it work for me but as a standalone app it doesn't.
