### ISSUE TITLE
[docs] documentation out dated in working together page

### ISSUE THREAD

**Issue by muneebahmedayub** [expo/expo#24156]
### Summary

The documentation says you can add members from your personal and organisation account. But as far as I experienced you cannot add members in personal account and also the [team account type documentation](https://docs.expo.dev/accounts/account-types/#teams) also says it is deprecated.

> For all new accounts where you want to share access, we recommend you to [create a new Organization](https://docs.expo.dev/accounts/account-types#organizations) Account. It allows more flexibility in role assignments. Creating a Team Account is deprecated.

And when inviting members from personal account it says 404 page not found, it only allows to invite members form organisation account. You can check it through [here](https://expo.dev/accounts/[account]/settings/members).

### Link to the related docs page

https://docs.expo.dev/accounts/working-together

**Comment by Simek** [comment]
Hello @muneebahmedayub, you should be able to invite people into your personal account, we did not drop this functionality. It should possible from the members page:
* https://expo.dev/accounts/[account]/settings/members

<img width="1256" alt="Screenshot 2023-08-30 at 12 34 35" src="https://github.com/expo/expo/assets/719641/1ac0feb1-dace-4f08-96a0-c36919fb8caa">

If you do not see the button, and you are sure that you are on your personal account please include the URL and a screenshot of what you see.

**Comment by muneebahmedayub** [comment]
Thanks for your feedback, it is good to know this functionality still exists. Seems like there is a problem on my end, I am seeing a 404 page on personal account but working fine or organisation account. Here is an attach screenshot that also include URL. Let me know if you want to see any other thing.
<img width="1680" alt="image" src="https://github.com/expo/expo/assets/65030135/d068609b-b4ad-4cf6-9df6-62818ed7444c">

**Comment by amandeepmittal** [comment]
Hey @muneebahmedayub, is your issue resolved or are you still facing it?

**Comment by muneebahmedayub** [comment]
@amandeepmittal I am able to access the members page now but as for new UI for expo website I am not able to invite members to my personal account. It looks like now I would have to create organisation account or convert my current account into organisation account.

**Comment by Simek** [comment]
>I am not able to invite members to my personal account. 

Can you share the screenshot, or report a problem thorough the feedback form in the dashboard (right bottom corner)?

In general, you should be able to invite anyone into your personal account members. Button to trigger invitation form should be located in the top right corner of the Members page.

<img width="704" alt="Screenshot 2024-01-09 115237" src="https://github.com/expo/expo/assets/719641/68073327-839a-41de-b50a-c2fe73d65edd">

**Comment by muneebahmedayub** [comment]
@Simek Here is an attached screenshot of my accounts member page
![Screenshot 2024-01-09 at 4 05 38 PM](https://github.com/expo/expo/assets/65030135/600494c7-27f7-47d4-9db4-710c69df549a)

**Comment by Simek** [comment]
I see, then the why is to create organization instead, they are free and offers better permission and members management. 

You can also transfers projects from you personal account, to newly created organization. The action is avaible in given project settings:
* https://expo.dev/accounts/[account]/projects/[project]/settings

**Comment by muneebahmedayub** [comment]
Great, I will check the organisations account, I also think it will be a better choice. Thanks alot for guidance.
