### ISSUE TITLE
TypeError: getCrypto().randomUUID is not a function on ios safari

### ISSUE THREAD

**Issue by itsramiel** [expo/expo#24158]
### Minimal reproducible example

https://github.com/itsramiel/expo-crypto-random-ios-safari

### Summary

I am trying to generate a random UUID using expo-crypto randomUUID. It seems to work everywhere except on ios simulator safari and ios device.
Iphone 14 pro simulator:
<img width="1729" alt="image" src="https://github.com/expo/expo/assets/80689446/8f39af6d-bf35-42b0-9f8d-72b75eaf75b7">
iphone 8 plus device:
<img width="1768" alt="image" src="https://github.com/expo/expo/assets/80689446/cdda3bf6-c507-4029-b5e3-bcae2cdb610e">

<details>
  <summary>Full error</summary>
```
[Error] TypeError: getCrypto().randomUUID is not a function. (In 'getCrypto().randomUUID()', 'getCrypto().randomUUID' is undefined)
	randomUUID (bundle.js:1165)
	App (bundle.js:32:84)
	renderWithHooks (bundle.js:37152)
	mountIndeterminateComponent (bundle.js:40916)
	callCallback (bundle.js:25011)
	dispatchEvent
	invokeGuardedCallbackDev (bundle.js:25060)
	invokeGuardedCallback (bundle.js:25124)
	beginWork$1 (bundle.js:48293)
	performUnitOfWork (bundle.js:47402)
	workLoopSync (bundle.js:47308)
	renderRootSync (bundle.js:47276)
	performConcurrentWorkOnRoot (bundle.js:46580:89)
	performConcurrentWorkOnRoot
	workLoop (bundle.js:51064)
	flushWork (bundle.js:51037)
	performWorkUntilDeadline (bundle.js:51331)
	```
</details>

### Environment

```
❯ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.04.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/ramiel/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0
      expo: ~49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed
    ```

**Comment by aleqsio** [comment]
It works for me on 16.4 on mobile safari 🤔

Assuming you're running `yarn web` in the clean repro project (after `yarn install`)?

**Comment by itsramiel** [comment]
Hey @aleqsio. I am running `npx expo start --web`.

It is actually weird. I deployed it to netlify and it works on the simulator but it does not work on my iphone 8 plus device. I really am not sure how to further debug this.

Let me know if I can do anything to help you further investigate. At the moment, I turned to using `nanoid` with `react-native-get-random-values`, however I would love to keep my packages withing the expo ecosystem as I am using a managed expo app.

**Comment by aleqsio** [comment]
Is it possible your iphone8 is on an older version of ios? https://caniuse.com/mdn-api_crypto_randomuuid

**Comment by bisalwa** [comment]
The Web Crypto API requires a secure context (https vs http). From your screen shot it appears you accessing the page over unsecure http. That is the cause of the error. Please refer to https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

**Comment by aleqsio** [comment]
Thanks @bisalwa, good catch!
