### ISSUE TITLE
Audio.Sound.createAsync from expo-av intermittently hangs indefinitely

### ISSUE THREAD

**Issue by lordprana** [expo/expo#24164]
z### Minimal reproducible example

Because it is intermittent, I can't give you a MRE

### Summary

In my application, sometimes our login hangs indefinitely. We preload sounds in our login logic. I've tracked down the error to this line of our code:

    const { sound } = await Audio.Sound.createAsync(asset, {
      volume,
    })

This only happens occasionally. Rebooting the device causes the sound creation to be successful if it was previously hanging.

So far we are only aware of it happening on iOS. I have been able to reproduce on my iOS simulator on iOS 16.2. It has also effected users in the wild. 

I'm on version 13.4.1 of the expo-av library.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.16.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.npm-global/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/matthewgaba/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.6 => 49.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.8
    Expo Workflow: bare

**Comment by pisacode** [comment]
@lordprana did you solve the issue? i am facing the same issue when trying to play base64. It was all fine before ios 17

**Comment by lordprana** [comment]
Also, a MRE isn't relevant in this context, because it is a heisenbug.

**Comment by cjhines** [comment]
Also happening for me on iOS 17

**Comment by mattbeaudin** [comment]
> Unfortunately, no. I switched audio libraries.

Sorry for bumping almost three months later but what library did you switch to? Having the same issue but on Android for some reason.

**Comment by dtomaszewski** [comment]
Hi, It is still a problem, it's problematic to reproduce because it happens occasionally but still quite often. Any chance @lordprana to get name of library you switched to ?

**Comment by NoahSaberhagen** [comment]
Having a similar issue - when we unload a sound and try to load the same sound createAsync() hangs indefinitely

**Comment by djimonlee** [comment]
yupp facing the same problem. It resolves on its own occasionally but I cannot figure out what is happening and why. Its really annoying since I am also loading sounds on the app startup and this makes the app unaccessible.

**Comment by mcewball13** [comment]
I have the same issue. I noticed it happens on several devices all at the same time. I'm using firebase to host an audio file and using storage to the pull the url. I fixed it by replacing the file with the same file with a new name in firebase. This was the first time it happened to me so i'll keep my eye out to see if I can replicate it purposefully.

**Comment by jwc-bootalk** [comment]
> I have the same issue. I noticed it happens on several devices all at the same time. I'm using firebase to host an audio file and using storage to the pull the url. I fixed it by replacing the file with the same file with a new name in firebase. This was the first time it happened to me so i'll keep my eye out to see if I can replicate it purposefully.

Exactly same case here. Some other urls work fine, but my firebase cloud storage files' url not workin
