### ISSUE TITLE
[android][expo-image-picker] content:// URIs are not usable in `ExponentImagePicker.launchImageLibraryAsync`

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#24172]
### Minimal reproducible example

I don't have Android. I have no idea what is an `uri` with `content://`

### Summary

"expo-image-picker": "~14.3.2",

Exactly as it's happening here https://github.com/expo/expo/issues/9354, I'm getting an error in `ExponentImagePicker.launchImageLibraryAsync`

```
Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000043213
```

For some reason, after upgrading to Expo 49, seems like the image picker totally changed (the UI) in Android, and it seems like it allows the user to pick photos that the URI are `content://xxxx`

As you can see here, it's only happening since some days ago (when I published SDK 49 upgrade).

<img width="323" alt="Screen Shot 2023-08-29 at 21 59 44" src="https://github.com/expo/expo/assets/1837969/9aef3e41-0f95-4725-b2a6-adea4533eb63">

Is there a workaround for this? Maybe some available flag to switch back to the old UI version, where files with `content://` uris were not visible.

Current code:
```js
    const options = {
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: false,
      exif: true,
      quality: 0.91,
    };

    ImagePicker.launchImageLibraryAsync(options)
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.7 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed
```

"expo-image-picker": "~14.3.2",

**Comment by BrodaNoel** [comment]
This SO question seems to be related, but there is no answer: https://stackoverflow.com/questions/75421073/expo-image-picker-android-error-with-content-uri

**Comment by mcottingham** [comment]
@BrodaNoel I had this error.  The solution was to downgrade whatwg-fetch to 3.6.2.

**Comment by BrodaNoel** [comment]
@mcottingham are you sure? I have 3.6.2

```
=> Found "whatwg-fetch@3.6.2"
info Reasons this module exists
   - "react-native" depends on it
   - Hoisted from "react-native#whatwg-fetch"
```

**Comment by mcottingham** [comment]
@BrodaNoel https://forums.expo.dev/t/fetching-loacal-files-is-causing-staus-0-error/72898/4

**Comment by BrodaNoel** [comment]
@mcottingham In my case, that's not the error I'm getting.

As far as I know, Android is now allowing the user to pick photos that are not local files, but files in "other sites" (like in Whatsapp), and that's why it's failing.

I just asked ChtGPT:


In Android, both `content://` and `file://` are URI (Uniform Resource Identifier) schemes used to reference resources, but they are typically used for different purposes:

1. **content://**:
The `content://` scheme is used to access data provided by Content Providers in Android. Content Providers are a way for different apps to share data with each other. They encapsulate the data and provide a standardized way to interact with it. Content Providers can be used to share data like contacts, media files, and other structured data between apps. When you use a `content://` URI, you are essentially requesting data from a Content Provider.

Example:
```
content://com.example.provider/contacts
```

2. **file://**:
The `file://` scheme is used to reference local files on the device's storage. This scheme is used when you want to work with files directly on the device's file system. However, starting from Android 7.0 (Nougat) and above, there are restrictions on using file URIs to access files outside your app's private directory. This is due to security concerns, as accessing arbitrary files could potentially lead to data leaks and unauthorized access.

Example:
```
file:///storage/emulated/0/Documents/example.txt
```

**Comment by BrodaNoel** [comment]
So... The problem now is that Expo is actually allowing user to select photos from some Content Provider, and I think it shouldn't (or it should understand how to handle them)

**Comment by alanjhughes** [comment]
Hi @BrodaNoel - I'm having trouble reproducing this. Can you provide any other details? Devices, OS versions etc? That would be very helpful.

**Comment by BrodaNoel** [comment]
A user sent me a video where you can see how she selects a photo, and then nothings happens.

https://youtube.com/shorts/FM16Bm0c2k8?si=rrRVynqv_JlgPI1F

**Comment by BrodaNoel** [comment]
Here I'm gonna paste more info about my `package.json` file and `app.json`

```json
{
  "name": "no-filter-app",
  "version": "19.39.0",
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@google-cloud/translate": "^6.1.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^8.22.0",
    "eslint-plugin-react": "^7.31.0",
    "eslint-plugin-react-native": "^4.0.0",
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0"
  },
  "main": "./node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start --dev-client",
    "generate-i18n": "node ./generate-i18n.js",
    "update-changelogs": "node ./update-changelogs.js",
    "postinstall": "patch-package",
    "build:develop": "eas build --profile development -p ios"
  },
  "dependencies": {
    "@amplitude/analytics-react-native": "^1.4.3",
    "@expo/react-native-action-sheet": "^4.0.1",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/analytics": "^18.3.0",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@sentry/react-native": "5.5.0",
    "duix": "^3.0.3",
    "expo": "^49.0.8",
    "expo-apple-authentication": "~6.1.0",
    "expo-application": "~5.3.0",
    "expo-background-fetch": "~11.3.0",
    "expo-build-properties": "~0.8.3",
    "expo-clipboard": "~4.3.1",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.8",
    "expo-device": "~5.4.0",
    "expo-file-system": "~15.4.3",
    "expo-font": "~11.4.0",
    "expo-image": "~1.3.2",
    "expo-image-manipulator": "~11.3.0",
    "expo-image-picker": "~14.3.2",
    "expo-linking": "~5.0.2",
    "expo-localization": "~14.3.0",
    "expo-location": "~16.1.0",
    "expo-media-library": "~15.4.1",
    "expo-notifications": "~0.20.1",
    "expo-splash-screen": "~0.20.5",
    "expo-store-review": "~6.4.0",
    "expo-task-manager": "~11.3.0",
    "expo-updates": "~0.18.12",
    "i18n-js": "^3.7.1",
    "lodash": "^4.17.21",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-fbsdk-next": "^12.1.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-maps": "1.7.1",
    "react-native-purchases": "^5.16.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "4.0.0-alpha.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-svg": "13.9.0",
    "react-native-uuid": "^2.0.1",
    "rn-prompt": "^1.0.4",
    "sanitize-html": "^2.10.0",
    "sentry-expo": "~7.0.0",
    "sunrise-sunset-js": "^2.2.1",
    "use-interval": "^1.4.0"
  }
}
```

**Comment by alanjhughes** [comment]
Thanks! 🤔 I'm testing on android 13 and not seeing anything but I would have expected it to happen older devices as the new picker is built for 13 and above.

**Comment by alanjhughes** [comment]
So is the picker dismissing but the image that was selected isn't showing up?

**Comment by BrodaNoel** [comment]
@alanjhughes Exactly. The `ExponentImagePicker.launchImageLibraryAsync()` promise is handled by the `catch`.

```
    const options = {
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: false,
      exif: true,
      quality: 0.91,
    };

    ImagePicker.launchImageLibraryAsync(options)
    .then(() => {})
    .catch(() => {
        // here
    })
```

So, it nevers shows up because the logic behind showing the photo is handled in the `then`

**Comment by alanjhughes** [comment]
Thanks for the information. I'll keep investigating 👍

**Comment by BrodaNoel** [comment]
@alanjhughes I remember that some time ago, you (or somebody in Expo) made some dark magic in order to get the `exif` data from some assets.

Check that I'm setting `exif: true`, so, maaaaybe you can't reproduce it because you are missing the `exif: true`.
But I'm not sure. I'm just thinking out loud

**Comment by BrodaNoel** [comment]
Exif magic I'm talking about: https://github.com/expo/expo/issues/17399

**Comment by BrodaNoel** [comment]
Here you can see it's not an isolated but. It's happening in most of the Android users (yeah, 27 users is "mosts of the users" in my project hehe)

<img width="365" alt="Screen Shot 2023-08-30 at 14 19 52" src="https://github.com/expo/expo/assets/1837969/1597da03-36ee-47e7-a31a-8bf51791e893">

**Comment by fobos531** [comment]
Hey @BrodaNoel 

If this is a very urgent issue for you and you need an interim solution while this is worked out on expo's side, I can confirm that `react-native-image-picker@5.0.2` works fine.

**Comment by BrodaNoel** [comment]
@fobos531 thank you! Yes, it is an urgent issue.

I'll wait a couple of hours in order to see if there is some update here, but if not, I'll take a look at it. Thanks!

**Comment by alanjhughes** [comment]
@BrodaNoel - It's a permissions issue. Because `media-library` is also used and has it's permissions granted, it causes a `SecurityException` from Glide when you pick an image. Working on a fix now

**Comment by alanjhughes** [comment]
The exception you see is the second one but there is actually one thrown before that from glide that is causing it. The content uri isn't the problem

**Comment by BrodaNoel** [comment]
@alanjhughes let me know if you want me to try some patch, or whatever. I'm here available to help you test it out.

I'm willing to try and deploy to production. It's already broken, so, it won't be a problem if we keep breaking it hahaha

**Comment by BrodaNoel** [comment]
@alanjhughes I just ran `yarn add expo@latest` and `npx expo install --fix`, and nothing seems to have changed.
Will this be fixed in Expo 50?

**Comment by alanjhughes** [comment]
@BrodaNoel - it hasn't been published yet. Will let you know when it is

**Comment by BrodaNoel** [comment]
I can see `expo-image-loader@4.4.0` released, and `expo-image-picker@14.5.0` released (which includes expo-image-loader@4.4.0).

If it's safe, I can upgrade from `expo-image-picker@14.3.2` to `expo-image-picker@14.5.0` and this it out in production. Let me know

**Comment by alanjhughes** [comment]
@BrodaNoel yes, please give it a try and let us know

**Comment by alanjhughes** [comment]
@richardkuiper - What version of OS, device etc? Without information, it's hard to debug

**Comment by richardkuiper** [comment]
Apologies.

Device: Google Pixel 5.
OS: Android 13
Expo SDK 49.

**Comment by TeChn4K** [comment]
I confirm the exact same issue with the version expo-image-picker@14.5.0


Device: Google Pixel 6a
OS: Android 14
Expo SDK 49

`expo-doctor` report is all good (except for `expo-image-picker`)
```
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000008850
Error: Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000008850
    at construct (native)
    at apply (native)
    at _construct (http://192.168.1.84:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:4471:28)
    at Wrapper (http://192.168.1.84:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:4433:25)
    at construct (native)
    at _createSuperInternal (http://192.168.1.84:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:125109:322)
    at call (native)
    at CodedError (http://192.168.1.84:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:125122:26)
```

**Comment by TeChn4K** [comment]
I tried again after completely uninstalling `expo-media-library` but this issue persists. 
It doesn't seem to be related with this package, like you mentioned here https://github.com/expo/expo/issues/24172#issuecomment-1699768378

**Comment by alanjhughes** [comment]
@TeChn4K - did you completely delete the app to reset the permissions after removing media library?

**Comment by TeChn4K** [comment]
Apologies, you were right.

The issue occurred through Expo Go. When I removed Expo Go from my device and reinstalled it, the issue no longer occurs !

**Comment by alanjhughes** [comment]
@TeChn4K - yes, expo go doesn't get updated regularly so doesn't receive bug fixes unless it's critical.

**Comment by BrodaNoel** [comment]
@alanjhughes  It look like it's still there.

```
Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000008735
```

```
"dependencies": {
    "@amplitude/analytics-react-native": "^1.4.3",
    "@expo/react-native-action-sheet": "^4.0.1",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/analytics": "^18.3.0",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@sentry/react-native": "5.5.0",
    "duix": "^3.0.3",
    "expo": "^49.0.9",
    "expo-apple-authentication": "~6.1.0",
    "expo-application": "~5.3.0",
    "expo-background-fetch": "~11.3.0",
    "expo-build-properties": "~0.8.3",
    "expo-clipboard": "~4.3.1",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.8",
    "expo-device": "~5.4.0",
    "expo-file-system": "~15.4.3",
    "expo-font": "~11.4.0",
    "expo-image": "~1.3.2",
    "expo-image-manipulator": "~11.3.0",
    "expo-image-picker": "14.5.0",
    "expo-linking": "~5.0.2",
    "expo-localization": "~14.3.0",
    "expo-location": "~16.1.0",
    "expo-media-library": "~15.4.1",
    "expo-notifications": "~0.20.1",
    "expo-splash-screen": "~0.20.5",
    "expo-store-review": "~6.4.0",
    "expo-task-manager": "~11.3.0",
    "expo-updates": "~0.18.12",
    "i18n-js": "^3.7.1",
    "lodash": "^4.17.21",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-fbsdk-next": "^12.1.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-maps": "1.7.1",
    "react-native-purchases": "^5.16.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "4.0.0-alpha.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-svg": "13.9.0",
    "react-native-uuid": "^2.0.1",
    "rn-prompt": "^1.0.4",
    "sanitize-html": "^2.10.0",
    "sentry-expo": "~7.0.0",
    "sunrise-sunset-js": "^2.2.1",
    "use-interval": "^1.4.0"
  }
```

**Comment by alanjhughes** [comment]
@BrodaNoel are you sure it's on devices that have the latest update? You went through store review etc?

**Comment by BrodaNoel** [comment]
@alanjhughes Yes.

The issue is present in App version 19.44.0. I don't use "expo updates".

<img width="863" alt="Screen Shot 2023-09-06 at 14 40 18" src="https://github.com/expo/expo/assets/1837969/12452159-8c80-4c89-be33-3ba439b754d7">

And I did the change in app version 19.44.0
```
# Changelog

### 19.44.0

- Update `expo-image-picker`
```

**Comment by alanjhughes** [comment]
Amy change in occurrences or type of device? That's a Xiaomi isn't it?

**Comment by BrodaNoel** [comment]
@alanjhughes it's a Xiaomi Mi 10T Pro

What is weird, is that this user who throw the error in the last version, is literally my most active user. This user has been uploading photos since 3 years ago. Around 10 photos per week. So, the fact that right now it doesn't work, is prove enough that before SDK 49 worked properly and now it doesn't work (so, it's not a problem is his device/android-version)

**Comment by BrodaNoel** [comment]
He has `android 12`.
<img width="443" alt="Screen Shot 2023-09-06 at 15 18 32" src="https://github.com/expo/expo/assets/1837969/1bad989b-f7d8-40bb-aeee-1d08d0358c4b">

<img width="884" alt="Screen Shot 2023-09-06 at 15 18 59" src="https://github.com/expo/expo/assets/1837969/3d98d484-6ad2-4ea2-8d89-b3885a8e809d">

Let me know if you need more info. Just tell me what I can do in order to help

**Comment by BrodaNoel** [comment]
In my app I have 2 analytics events: `UPLOAD_PHOTO_FLOW_START` and `UPLOAD_PHOTO_FLOW_ENDS_OK`.

As far as I can see, in the new version of my app (which contains the last version of `expo-image-picker`), there were 5 events of "START" and zero of "ENDS_OK"

**Comment by alanjhughes** [comment]
Unfortunately device and os version is very much a concern on android as seen early in this thread. Someone experiencing this issue in expo go (using the older version of image picker) has the problem resolved with this change. I'll try to reproduce again.

**Comment by BrodaNoel** [comment]
Seems like `expo-image-maniulator@11.5.0` is using the last version of `expo-image-loader`.

I'm updating that dependency now.

**Comment by alanjhughes** [comment]
No, it won't be an issue with image manipulator. It'll use the latest version of image loader. On android, something working well on a pixel may not work on a Samsung galaxy. Anyway, reproducing again will be a start.

**Comment by BrodaNoel** [comment]
I'm going to force users to update to the last version, so I can get more information about the devices are getting this error.

(I have an endpoint who check if the app should be updated).

Let me first deploy the new app version with the last version of `expo-image-manipulator`, just in case.

**Comment by alanjhughes** [comment]
I'm not sure I understand how you are handling updates. Can you explain?

**Comment by BrodaNoel** [comment]
100% old school.

1. I make a change in the app
2. I create a new version (package json, and app.json)
3. I build `eas build -p android --local`
4. I submit it `eas submit -p android`
5. I push it from `internal testing` to `production` in Google Play Console Developers

Period.

Then, some times, only few times when it's really necessary, I go to change a value I have in a database which is the "last app version recommeded".

Every time the app is open in a device, it check this value in the database. If the user is opening an app version `18.0.0`, and the recommededn in the database is `19.0.0`, I show to the user a text saying: "This all is too old, update it, click here" (which opens the App Store so they can click in "Update")

**Comment by BrodaNoel** [comment]
This is the code I run when the user clicks on "This app is too old, update it":

```
  onOutdatedClick = () => {
    Linking.openURL(
      Platform.select({
        ios: `itms-apps://apps.apple.com/app/id1445583976`,
        android: `https://play.google.com/store/apps/details?id=app.no_filter.nofilter`,
      })
    );
  };
```

This will open the App/Play store in the device.

**Comment by alanjhughes** [comment]
I see. Can you repro locally?

**Comment by alanjhughes** [comment]
A repro from the app that is seeing the issue will be more useful than me trying in out test app

**Comment by BrodaNoel** [comment]
@alanjhughes I have a physical device with Android 9, where I can not reproduce this error.
I'll try an emaulator with Android 12, but, I don't understand what is "an asset with URL content://".

If I go to Google.com and I download a photo in my emulator, will this photo be `content://...`?

**Comment by alanjhughes** [comment]
All photos that come back from the photo picker come as `content` Uris. We convert them to file Uri so they can be accessed. 

I suspect the error you are seeing is misleading. It's the last exception that was thrown but not the root cause. Do you have a full stacktrace actually?

**Comment by BrodaNoel** [comment]
I'm gonna try the emulator in few minutes.

Here the full stack from Sentry:

```
Error: Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000008735
  at → Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: (app:///index.android.bundle)
  at construct(app:///index.android.bundle)
  at apply(app:///index.android.bundle)
  at _construct(node_modules/@babel/runtime/helpers/construct.js:19:26)
  at Wrapper(node_modules/@babel/runtime/helpers/wrapNativeSuper.js:26:23)
  at construct(app:///index.android.bundle)
  at _createSuperInternal(app:///index.android.bundle:6:38)
  at call(app:///index.android.bundle)
  at constructor(node_modules/expo-modules-core/build/errors/CodedError.js:10:9)
```

**Comment by BrodaNoel** [comment]
I don't see any errors on my end, in the emulator (Pixel 2).

Is there something alternative I could do in order to get more information about this error? The stack I sent before doesn't seem to be quite useful.

<img width="569" alt="Screen Shot 2023-09-06 at 17 55 01" src="https://github.com/expo/expo/assets/1837969/8d8767b3-6993-44d2-8c61-efbca376bc2b">

**Comment by BrodaNoel** [comment]
@alanjhughes FINALLY! I could reproduce it in an emulator.

I tried a couple of different emulators, and the error is not reproduce in the old Image Picker UI. It only happens in the new one (screenshot below).

<img width="457" alt="Screen Shot 2023-09-06 at 19 11 09" src="https://github.com/expo/expo/assets/1837969/15ea1de8-eae6-4b02-bd5f-c4219adefa35">

After picking the file I downloaded, I get the error.
<img width="448" alt="Screen Shot 2023-09-06 at 19 11 30" src="https://github.com/expo/expo/assets/1837969/38822856-b353-428a-ae64-7cbd1feac8b0">


I created in the virtual devices from Android Studio, the following emulator: `Pixel_6_API_33_android_13`.

I opened Chrome in the emulator and downloaded this photo: https://getnofilter.com/es/spot/neuschwanstein-castle-from-west-side-of-bridge-in-germany

Then I selected it in the app, and I got the error.

This is the APK file I installed in the emulator: https://wetransfer.com/downloads/6b0dbdddac76655eb2194f5f0d6959b420230906221918/37e970ebed1a9b7ed190a818ce4e396b20230906221937/5387a3?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

What would you need from my side? Should

**Comment by alanjhughes** [comment]
@BrodaNoel Great work! Unfortunately following your steps does not reproduce on the same device for me. I can pick the image and display it without issue 🤔 What did you name the file? Can you post it here?

**Comment by BrodaNoel** [comment]
Emulator details:

Properties
avd.ini.displayname              Pixel 6 API 33 android 13
avd.ini.encoding                 UTF-8
AvdId                            Pixel_6_API_33_android_13
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     2
hw.device.hash2                  MD5:3db3250dab5d0d93b29353040181c7e9
hw.device.manufacturer           Google
hw.device.name                   pixel_6
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   420
hw.lcd.height                    2400
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         33
image.sysdir.1                   system-images/android-33/google_apis/x86_64/
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.id                           google_apis
vm.heapSize                      228

**Comment by BrodaNoel** [comment]
@alanjhughes 

<img width="530" alt="Screen Shot 2023-09-06 at 19 31 40" src="https://github.com/expo/expo/assets/1837969/5efbb365-e885-435e-b7c3-9a6e5de018c6">

I'm creating a video... one sec.

**Comment by BrodaNoel** [comment]
@alanjhughes  Here is a video showing step by step: https://youtu.be/6ehjky3y84s

**Comment by BrodaNoel** [comment]
Here the APK file, from Google Drive: https://drive.google.com/file/d/1XJsjJc6_koXqgkNu9yUwDAHs7QNI8ERW/view?usp=sharing

**Comment by alanjhughes** [comment]
That's all extremely helpful thank you! I'm not sure why but I can download several images from that site and none are causing any problems on the exact same device. I can see the issue only when running your apk which is great but I don't have access to the logs 🤔 It has to be something or some combination of things that is unique to your app

**Comment by alanjhughes** [comment]
Switching tabs and then going back will allow you to recover from the error and choose again 🤔

**Comment by BrodaNoel** [comment]
Now I'm out, but tomorrow I could remove dependencies from the app and build again, until see if some of the other dependencies are breaking something.

The local build creates a `.abb` file. Do you know how to get a .apk file? Thanks!

**Comment by alanjhughes** [comment]
I've accessed the logs now. It's the same as what you are seeing. I will look into this further in the morning. Appreciate your help 👍

**Comment by TeChn4K** [comment]
Just to let you know that I no longer have any issue after a fresh build. Tested on Android and iOS with `expo-image-picker@14.5.0` and `expo-media-library@15.4.1`

Thanks a lot @alanjhughes for your time, and good luck for the debug with @BrodaNoel

**Comment by alanjhughes** [comment]
Thank you for the update @TeChn4K glad it is resolved for you 👍

**Comment by alanjhughes** [comment]
@BrodaNoel - I've been looking at the logs from your apk and the issue is the exact same one that the bump to image loader fixed. Your building locally IIRC. Did you delete the Android folder before creating a new build? I suspect the native code is out of date.

**Comment by BrodaNoel** [comment]
@alanjhughes what Android folder? I don't have any Android folder in my end.

I'm gonna do a build but directly on `eas` servers, just to check...

**Comment by BrodaNoel** [comment]
@alanjhughes the build made in `eas` servers seems to be working well.

I uploaded `eas submit` the `abb` build to Google Play Store, and then I went to the build details and downloaded the `.apk` file, and installed it in the Pixel 6 simulator. The app did not crashed this time.

Now... Could you please enlighten me? what could be happening in my local environment? Is there maybe a cache that I should clean before building? I don't see any `android` or `ios` folder (as we had previously while building with `expo build`)

**Comment by alanjhughes** [comment]
There is a local gradle cache, likely a hidden folder in your home directory. I would not recommend building locally unless absolutely necessary to avoid these types of issues. A build on eas will always build from scratch

**Comment by BrodaNoel** [comment]
@alanjhughes building on `eas` is not an option anymore for people from developing countries. It now costs 3 USD to build 1 ios and 1 android. 20 builds are 60 USD. That's a regular salary in my country (Argentina) (yes, 60 usd)

So, yes, I need to build locally now. Seems like `rm -rf ~/.gradle/caches` should works. I'll take a look.

Thank you a lot for all the effort helping me with this! A lot of time spend. Thanks a lot!

**Comment by 20chad16** [comment]
> @alanjhughes building on `eas` is not an option anymore for people from developing countries. It now costs 3 USD to build 1 ios and 1 android. 20 builds are 60 USD. That's a regular salary in my country (Argentina) (yes, 60 usd)
> 
> So, yes, I need to build locally now. Seems like `rm -rf ~/.gradle/caches` should works. I'll take a look.
> 
> Thank you a lot for all the effort helping me with this! A lot of time spend. Thanks a lot!

After upgrading media library and image picker and clearing the gradle cache (I am running a bare workflow), I am still receiving the error on my android builds. iOS is working fine. Any ideas?

Error:
Error opening image picker: Error: Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000000019

npx expo run:android

physical device:
Pixel 4
Android 13

package.json
{
  "name": "xxxxx",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/metro-config": "^0.10.7",
    "@expo/react-native-action-sheet": "^4.0.1",
    "@expo/vector-icons": "^13.0.0",
    "@openspacelabs/react-native-zoomable-view": "^2.1.1",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/analytics": "^18.3.0",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/crashlytics": "^18.3.0",
    "@react-native-segmented-control/segmented-control": "2.4.1",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.5",
    "@ronradtke/react-native-markdown-display": "^8.0.0",
    "axios": "^1.4.0",
    "expo": "~49.0.7",
    "expo-apple-authentication": "^6.1.0",
    "expo-auth-session": "^5.0.2",
    "expo-build-properties": "^0.8.3",
    "expo-camera": "^13.4.2",
    "expo-constants": "~14.4.2",
    "expo-crop-image": "^0.2.1",
    "expo-crypto": "^12.4.1",
    "expo-file-system": "^15.4.3",
    "expo-image-manipulator": "^11.3.0",
    "expo-image-picker": "~14.5.0",
    "expo-local-authentication": "^13.4.1",
    "expo-media-library": "~15.4.1",
    "expo-notifications": "^0.20.1",
    "expo-permissions": "^14.2.1",
    "expo-sharing": "^11.5.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-store-review": "^6.4.0",
    "expo-web-browser": "^12.3.2",
    "firebase": "^10.1.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-hook-form": "^7.45.4",
    "react-native": "0.72.4",
    "react-native-autocomplete-input": "^5.3.2",
    "react-native-dialog": "^9.3.0",
    "react-native-dotenv": "^3.4.9",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-heroicons": "^3.2.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.8.2",
    "react-native-mask-input": "^1.2.3",
    "react-native-modal-datetime-picker": "^17.0.0",
    "react-native-new-snap-carousel": "^3.9.3",
    "react-native-picker-select": "^8.0.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-select-dropdown": "^3.3.4",
    "react-native-smooth-picker": "^1.1.5",
    "react-native-table-component": "^1.2.2",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^10.0.0",
    "react-native-view-shot": "^3.7.0",
    "react-navigation-shared-element": "^3.1.3",
    "react-redux": "^8.1.2",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "expo-device": "~5.4.0"
  },
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.20.0"
  }
}

**Comment by BrodaNoel** [comment]
@20chad16 try "expo-image-manipulator": "11.5.0"

**Comment by BrodaNoel** [comment]
I would also run `yarn why expo-image-loader` and check if any other dependency is using it.

**Comment by 20chad16** [comment]
That worked. Thank you Broda and Alan!

**Comment by jsheffers** [comment]
I'm getting this as well. Here is the breakdown of expo packages I have:

`
$ expo run:android --device
✔ Select a device/emulator › Pixel_4_API_33 (emulator)
› Using --device Pixel_4_API_33
› Building app...
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
Configuration on demand is an incubating feature.

> Configure project :expo

Using expo modules
  - expo-application (5.3.0)
  - expo-constants (14.4.2)
  - expo-file-system (15.4.3)
  - expo-font (11.4.0)
  - expo-image-loader (4.3.0)
  - expo-image-manipulator (11.3.0)
  - expo-image-picker (14.5.0)
  - expo-intent-launcher (10.7.0)
  - expo-keep-awake (12.3.0)
  - expo-media-library (15.4.1)
  - expo-modules-core (1.5.9)
  - expo-modules-core$android-annotation-processor (1.5.9)
  - expo-modules-core$android-annotation (1.5.9)
  - expo-sensors (12.3.0)
  - expo-splash-screen (0.20.5)
  - expo-store-review (6.4.0)
`

I'm building locally.  I've cleared all of the caches, but I still get this error.  Interestingly enough if I delete the app and re-install it the first image chosen works properly.  Every subsequent image (after allowing permissions) fails with this error.

**Comment by alanjhughes** [comment]
@jsheffers can you provide a minimal reproduction? Also can you run a build on eas and verify it still occurs?

**Comment by alanjhughes** [comment]
I'm going to lock this as it has gotten too long. Please create a new issue with a minimal reproduction and verify the issue occurs when built on eas
