### ISSUE TITLE
GLView worklet error "GLView.getWorkletContext is not a function"

### ISSUE THREAD

**Issue by ReactorCSA** [expo/expo#24176]
### Minimal reproducible example

https://snack.expo.dev/@alexjs/gnarly-popcorn

### Summary

When trying to bypass JS Thread -> UIThread -> canvas render loop with a help of this tutorial
https://docs.expo.dev/versions/latest/sdk/gl-view/#integration-with-reanimated-worklets
I get the following error: 
```
GLView.getWorkletContext is not a function (it is undefined)
-> at anonymous Javascript
-> at apply (native
```
Meanwhile trying to render context by changing `runOnUI` to `runOnJS` makes app working as expected. But it seems to be a plain render loop through JS Thread.
<img width="523" alt="Screenshot 2023-08-30 at 12 26 06 PM" src="https://github.com/expo/expo/assets/81511054/659332ca-1248-40b0-885e-7cd068800098">

Also found a little difference with `enableExperimentalWorkletSupport`, which is included in code in a short example but in the real example id doesn't exist.

P.S. Snack in Minimal reproducible example throws error. Error is not reproduced in my local bundle. Maybe it's an env. trouble.

### Environment

**Env:**
 ```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.1 - ~/.nvm/versions/node/v18.9.1/bin/node
      npm: 9.6.6 - ~/.nvm/versions/node/v18.9.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed
```
    
**package.json**
```
    "@react-spring/three": "9.7.3",
    "@react-three/drei": "^9.80.8",
    "@react-three/fiber": "^8.13.7",
    "expo": "~49.0.8",
    "expo-file-system": "~15.4.3",
    "expo-gl": "~13.0.1",
    "expo-status-bar": "~1.6.0",
    "expo-three": "7.0.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "3.3.0",
    "three": "0.145.0",
    "zustand": "^4.4.1"
```

**Comment by ReactorCSA** [comment]
Good evening!
Any updates? Feature is suppper coool and it would be really good if it worked just a little bit :)

**Comment by ReactorCSA** [comment]
It seems like this error is somehow related to this pr https://github.com/expo/expo/pull/22634

**Comment by ReactorCSA** [comment]
Also trying to log GLView in UIThread throws {}
<img width="891" alt="Screenshot 2023-09-01 at 12 55 03 AM" src="https://github.com/expo/expo/assets/81511054/90be5af0-fc44-4218-96da-ea57f5d7be4b">

**Comment by TowhidKashem** [comment]
I'm also running into the same issue, in my case I am just trying to run the sample code from the docs:

```
  function render(gl) {
    'worklet';
    // add your WebGL code here
  }

  function onContextCreate(gl) {
    runOnUI((contextId: number) => {
      'worklet';
      const gl = GLView.getWorkletContext(contextId);
      render(gl);
    })(gl.contextId);
  }

  return (
      <GLView
        style={{ width: 300, height: 300 }}
        enableExperimentalWorkletSupport
        onContextCreate={onContextCreate}
      />
  );
```

if not trying to run it in reanimated my app crashes if I call `const renderer = new Renderer({ gl });` inside `onContextCreate`. I put this in my podfile `$ExpoUseSources = ["expo-gl-cpp"]` per one of the issue threads but no luck.

Normally expo packages work like a breeze but this one has been tough to get working...

```
    "expo": "~49.0.0",
    "expo-gl": "~13.0.1",
    "expo-gl-cpp": "^11.4.0",
    "three": "^0.156.1",
```

**Comment by TowhidKashem** [comment]
same issue:

https://github.com/expo/expo/issues/23969

**Comment by ReactorCSA** [comment]
Hi @TowidKashem!
I had an idea passing GLView into useSharedValue, but currently I’m on a trip and cannot prove my theory, maybe it would work ☺️

**Comment by tuanlongn** [comment]
@ReactorCSA there seems to be an issue with build js. You can try create new instance workletContextManager to get native WorkletContext on runOnUI:
```
...
import { runOnUI } from "react-native-reanimated";
import { ExpoWebGLRenderingContext, GLView } from "expo-gl";
import { createWorkletContextManager } from "node_modules/expo-gl/src/GLWorkletContextManager";

const getWorkletContext = createWorkletContextManager().getContext;

const onContextCreate = (gl: ExpoWebGLRenderingContext) => {
    runOnUI((contextId: number) => {
      "worklet";
      const workletGL = getWorkletContext(contextId);
      if (workletGL) {
        // add your WebGL code here
      }
    })(gl.contextId);
  };
```
I hope this work on your case.

**Comment by ReactorCSA** [comment]
Thaaaanks!!! it really worked for me <3

**Comment by hannojg** [comment]
@ReactorCSA do you mind reopening the issue? I think the problem with the shipped JS should be still fixed in this repo 😊
