### ISSUE TITLE
Environment variables not supported in Snack

### ISSUE THREAD

**Issue by JorensM** [expo/expo#24180]
### Minimal reproducible example

https://snack.expo.dev/@jorensm/env-vars-not-working

### Summary

Environment variables don't get added to my app for some reason.

![export env vars](https://github.com/expo/expo/assets/17122123/6ca0d444-767a-48ff-bf06-479a69533fad)

As you can see in the screenshot above, the console says that the env vars do get loaded. But when I try to access them from my app (on web), they return undefined.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 30.0.2, 30.0.3
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      @expo/webpack-config: ^18.1.2 => 18.1.2
      expo: ~49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.7
    Expo Workflow: managed

**Comment by EvanBacon** [comment]
Environment variables are not supported in snack

**Comment by JorensM** [comment]
> Environment variables are not supported in snack

The problem is present in a regular expo app, I just used Snack as an example. Here is the project where they don't work: https://github.com/JorensM/local-jobs (also you should probably revert the issue title back to original)

**Comment by EvanBacon** [comment]
There is no `.env` file in the repo you provided. If I create one and start the project, then all environment variables that are prefixed with `EXPO_PUBLIC_` show up in the application as expected.

After searching all the code, I see you log out the entire object [here](https://github.com/JorensM/local-jobs/blob/f762349fc05cc94c331641d047876727256422fc/src/pages/NewListingPage.tsx#L70) which isn't supported. As [mentioned in the docs](https://docs.expo.dev/guides/environment-variables/#how-variables-are-loaded) environment variables are inlined for security purposes, meaning you cannot arbitrarily access them. This is standard practice in React frameworks.

> Every variable must be referenced as a static property in order for it to be inlined. For example, the expression process.env.EXPO_PUBLIC_KEY will be rewritten, but process.env['EXPO_PUBLIC_KEY'] will not.

**Comment by JorensM** [comment]
@EvanBacon the .env file was .gitignored, forgot to mention that. I had also tried logging the variable itself and not the object, and it still returned undefined. Since you say that the env variables show up for you, I guess it's an issue with my environment. I suggest that you re-open this issue as its still present for me and might be present for others as well. Thanks.
