### ISSUE TITLE
ExpoFontLoader undefined

### ISSUE THREAD

**Issue by hew** [expo/expo#2419]
### Environment

```
Environment:
  OS: macOS 10.14
  Node: 10.9.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/tahini-87eab9ac-84d5-43e7-918f-4075a73c19b9.tar.gz
```

```
  Targeting Android.
```

### Steps to Reproduce

1. clone `https://github.com/hew/expo-font-bug`
2. `expo start`

### Expected Behavior

Expects [`ExpoFontLoader`](https://github.com/expo/expo/blob/master/packages/expo-font/src/Font.js#L5) to have a value

### Actual Behavior

Promise [rejects on function call](https://github.com/expo/expo/blob/master/packages/expo-font/src/Font.js#L141). 

### Reproducible Demo

clone `https://github.com/hew/expo-font-bug`

**Comment by hew** [comment]
Testing on iOS, we get this:


<img width="401" alt="image" src="https://user-images.githubusercontent.com/3103241/46912736-d265c700-cf32-11e8-80fe-3fbc36359e64.png">

**Comment by sjchmiela** [comment]
Hey! I just cloned the project and it loaded without any problems or errors… Do you have latest Expo Client installed on your iOS device? 🤔

**Comment by hew** [comment]
I was running the simulator above, so I updated the Expo CLI (to latest) and it cleared the problem up. I thought I had tried doing that already, but I must not have.

Thanks for the help!
