### ISSUE TITLE
Double tapping R to reload

### ISSUE THREAD

**Issue by ahjorth** [expo/expo#242]
Live reloading is all well and fine, but it's very temperamental for me. Often times it just doesn't work, and some IDE's auto save often which can lead to bad code being pushed.

My preferred way of developing is to have live reloading off, but rather manually reload when I need to.

However this seems unnecessarily complex with Expo.

Being a linux user, having to click CTRL+M and then manually clicking reload seems like a step back from when I was using the `react-native init` with the android studio emulator.

Now that I have to use genymotion, I would love to see the same functionality of "Double Tap R" in expo. I mean the error messages still say "R + R" for the reload hint.

But maybe this is just a problem for me?

**Comment by brentvatne** [comment]
I agree this seems useful. @satya164 - maybe something you can do?

**Comment by ahjorth** [comment]
One interesting note is that when you do get the big red error message, and it shows the (R+R) to reload prompt, double tapping actually works, but once you're back into expo the functionality is gone.

**Comment by dikaiosune** [comment]
Support for this has been merged and should be available in the next release. Thanks!

**Comment by ahjorth** [comment]
Amazing, great job guys :)
