### ISSUE TITLE
`expo prebuild` is replacing my `package.json`

### ISSUE THREAD

**Issue by SohelIslamImran** [expo/expo#24222]
### Summary

I'm using different configuration files for different environments. So using `env` variables with commands. e.g. `npx cross-env APP_ENV=development expo run:ios`. But when running `expo prebuild` command, every time it replaces `ios` and `android` scripts in `package.json` with `expo run:ios` and `expo run:android`. This is really problematic for us, we can't use `expo run:ios` directly without setting `env`. It is also very annoying, every time I run `expo prebuild`, I need to revert the change in `package.json` before pushing to GitHub... Why I can't use custom commands in `ios` and `android` scripts in `package.json` if I use `expo prebuild`?

### What platform(s) does this occur on?

Android, iOS

### SDK Version

^49.0.8

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: bare

### Minimal reproducible example

I want to use these commands:
![image](https://github.com/expo/expo/assets/76745339/8bb331e3-9130-4be7-a19f-10042000a204)

Every time I run `expo prebuild`, it replaces those two commands with these:
![image](https://github.com/expo/expo/assets/76745339/cff9f187-8ed3-49aa-9703-6a1063662438)

Also,`expo prebuild` force to have `name` and `version` properties in `package.json` and auto add folder name as name, `"1.0.0"` as version. I don't need them. Why should it force them?
![image](https://github.com/expo/expo/assets/76745339/f4b228b2-e189-426c-9036-8bb4c9e2b68a)

I can see here it is adding `name` and `version`.. Please remove this line!
https://github.com/expo/expo/blob/086aab5f14bed7a4e560b6f3e8eb4b8942203c51/packages/%40expo/config/src/Config.ts#L324

**Comment by SohelIslamImran** [comment]
I'm too lazy to report bugs... But I was forced to create this issue after being annoyed over this problem for year.. Please resolved

**Comment by aleqsio** [comment]
You could also name these scripts in package.json something different than `ios` and `android` – these are reserved by expo prebuild for default run commands.

**Comment by SohelIslamImran** [comment]
@aleqsio This doesn't make sense. My project script, I should able whatever I want to put there. Creating projects with `npx create-expo-app` or something, there may be some default scripts. But after that, I should able to keep or change them as my preference

**Comment by EvanBacon** [comment]
This issue appears to be describing the documented functionality of expo prebuild and list it as an issue due to preference. You can patch the expo/cli package in your project to abide by your personal preference, otherwise this doesn't appear to be a valid bug report. We also recommend you use `NODE_ENV` instead of `APP_ENV`. The package.json name and version are updated to support monorepos iirc, we don't plan to remove this modification.

**Comment by trippingtarballs** [comment]
For anyone else who might come across this issue, this is the solution we have settled upon:

```json
// package.json
  "scripts": {
    "build": "expo prebuild",
    "postbuild": "x=$(cat package.json) && jq 'del(.scripts[\"android\", \"ios\"])' <<<$x >package.json",
```

After the `prebuild` command has run the `"android"` and `"ios"` run-scripts are removed from the project's `package.json`. 

⚠️ This solution assumes [`jq`](https://jqlang.github.io/jq/) is installed and available on your system's `PATH`. ⚠️ 

Sorry @EvanBacon, but this solution will not help you as the current behaviour of the `prebuild` command is to replace the `"android"` and `"ios"` run-scripts. In my case, I do not want to have `"android"` and `"ios"` run-scripts at all.

**Comment by alfonsocj** [comment]
If you would like to make it always work when running `expo prebuild`, you could create an expo plugin for this.

You can create a mod for the project's package.json:
```typescript
export type PackageJson = {
  name?: string;
  version?: string;
  description?: string;
  scripts?: Record<string, string>;
  [key: string]: unknown;
};

export function withPackageJson(
  expoConfig: ExpoConfig,
  contentModifier: (packageJson: PackageJson) => PackageJson,
) {
  // eslint-disable-next-line no-underscore-dangle
  const expoInternal = expoConfig._internal;

  if (!expoInternal?.projectRoot || typeof expoInternal.projectRoot !== 'string') {
    throw new Error('Could not determine the project root from expo config');
  }

  const packageJsonPath = path.join(expoInternal.projectRoot, 'package.json');
  const packageJsonContent = fs.readFileSync(packageJsonPath, 'utf8');
  const currentPackageJson = JSON.parse(packageJsonContent) as PackageJson;

  const result = contentModifier(currentPackageJson);
  fs.writeFileSync(packageJsonPath, `${JSON.stringify(result, null, 2)}\n`);

  return expoConfig;
}
```

Then you could create a new plugin for the specific need of removing those scripts:
```typescript
export function withoutPackageJsonExpoScripts(expoConfig: ExpoConfig) {
  return withPackageJson(expoConfig, (packageJson) => {
    if (packageJson.scripts) {
      // eslint-disable-next-line no-param-reassign
      delete packageJson.scripts.android;
      // eslint-disable-next-line no-param-reassign
      delete packageJson.scripts.ios;
    }

    return packageJson;
  });
}
```

You can then include `withoutPackageJsonExpoScripts` in the plugins section of `app.json` (or `app.config.js|ts` if you use that).

Keep in mind that I have `withPackageJson` because I have other plugins that leverage this mod but you can include that logic in `withoutPackageJsonExpoScripts` if that's all you care about.
