### ISSUE TITLE
EXPO_PUBLIC variables are not available in process.env

### ISSUE THREAD

**Issue by cjmling** [expo/expo#24236]
### Minimal reproducible example

EXPO_PUBLIC_API_URL=http://localhost:3000

### Summary

So I just upgraded to expo 49 in order to use .env variable.

I created .env file with following content

```
EXPO_PUBLIC_API_URL=http://localhost:3000
EXPO_PUBLIC_API_URL_STAGING=https://xxxxxxxxxxxxxxxx.vercel.app
```

When I run `npm run web`

I do see

```
> expo start --web

Starting project at C:\Users\xxx\Documents\xxxx
env: load .env.local .env
env: export EXPO_PUBLIC_API_URL EXPO_PUBLIC_API_URL_STAGING
Starting Metro Bundler
env: load .env.local .env
env: export EXPO_PUBLIC_API_URL EXPO_PUBLIC_API_URL_STAGING
```

But when I `console.log(process.env)` in one of my .ts file , I don't see any `EXPO_PUBLIC_` variable available in the object.

Any thing else is required?

Same when I run on expo go iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ^49.0.0 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    Expo Workflow: managed

**Comment by ah0y** [comment]
I'm also experiencing this

**Comment by crbrasfield** [comment]
@cjmling I also had this issue.

Resolved by updating the following dependencies:
```
    "@expo/config-plugins": "~7.2.5",
    "@expo/metro-config": "^0.10.7",
```

**Comment by finnmerlett** [comment]
FYI I fixed my version of this issue, turns out I was trying to access the environment variables through a zod validator that was trying to validate the whole process.env object. I understand now that env vars are surely subbed in during the build process via a simple find-and-replace (probably a built-in babel plugin), because switching to accessing the env vars directly worked perfectly.

To summarise:

    env = process.env; env.EXPO_PUBLIC_MY_ENV_VAR fails
    process.env.EXPO_PUBLIC_MY_ENV_VAR succeeds

**Comment by adamspotlite** [comment]
can second @finnmerlett's comment - removing zod validator worked and accessing directly worked.
