### ISSUE TITLE
expo-image-picker crash on android

### ISSUE THREAD

**Issue by Cassianosch** [expo/expo#24238]
### Minimal reproducible example

https://snack.expo.dev/@cassianoscheidemantel/error-camera---android

### Summary

The library crashes in some androids. Ios working fine.
The app refreshes at the Motorola G30 Android 12 (video below) once the image is selected.
An older Motorola with a different Android version works fine.
In a Samsung J5 with Android 6 works fine.
We also saw this problem happen in some Samsung and Huawei phones.
There is no log only the refreshments.

If happens in
^48.0.0
~49.0.8

https://github.com/expo/expo/assets/28737079/7215b08f-1a22-4062-80cb-2bb47413401d

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.1/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.0.2
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by Klin-Coders** [comment]
happens with picking media too, any fix so far this is a big issue

**Comment by lawrence-envoi** [comment]
Our team is experiencing a very similar issue.  Not being able to select an image with the image picker a major issue.

**Comment by ansh** [comment]
We've been experiencing this too.

**Comment by wen-kai** [comment]
seems related to https://github.com/expo/expo/issues/20482

we've noticed when an android video file is edited then selected via image-picker it crashes with `FailedToDeduceTypeException`. if the file is edited and "save as copy" is selected then the video file works. I'm able to reproduce every time with my Samsung s23.

<img width="304" alt="image" src="https://github.com/expo/expo/assets/1305459/85b26968-aedc-47cd-9d24-d0155b4e32b3">

<img width="316" alt="image" src="https://github.com/expo/expo/assets/1305459/bbfb46a0-c925-4f5d-90fa-37c9462e85f4">

**Comment by wen-kai** [comment]
As a workaround we are using DocumentPicker for android until this is resolved. not as nice of a UEX but better than crashes:

```
      let pickerResponse;
      if (Platform.OS === 'android') {
        pickerResponse = await DocumentPicker.getDocumentAsync({
          type: videosOnly ? 'video/*' : '*/*',
          copyToCacheDirectory: true,
        });
      } else {
        pickerResponse = await ImagePicker.launchImageLibraryAsync({
          allowsEditing: true,
          mediaTypes: ImagePicker.MediaTypeOptions.Videos,
          videoExportPreset: ImagePicker.VideoExportPreset.H264_1280x720,
        });
      }
```
