### ISSUE TITLE
@react-native-google-signin/google-signin not work in expo run:ios

### ISSUE THREAD

**Issue by jumptidus** [expo/expo#24237]
### Minimal reproducible example

https://github.com/jumptidus/test-google-signin.git

### Summary

```
npx create-expo-app

npx expo install @react-native-google-signin/google-signin

npx expo run:ios
```

pod install fail

It took me a lot of time to find it...

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.0.2
    Expo Workflow: bare

**Comment by BrodaNoel** [comment]
I've implemented it on getnofilter.com and it's working properly.

Have you read https://github.com/react-native-google-signin/google-signin#expo-installation ? This documentation ask you to add a plugin in `app.json`, and seems like you didn't do it.

**Comment by budwol** [comment]
Same issue android. Worked perfectly but now, the redirect or something seems to be broken. Cannot sign in anymore

**Comment by jumptidus** [comment]
> I've implemented it on [NoFilter app](https://getnofilter.com) and it's working properly.
> 
> Have you read https://github.com/react-native-google-signin/google-signin#expo-installation ? This documentation ask you to add a plugin in `app.json`, and seems like you didn't do it.

yeah,i do. still pod install fail

**Comment by jumptidus** [comment]
Sorry,it's my cocoapods issue
