### ISSUE TITLE
Files downloaded through expo-file-system are not showing in SDK 49/50 on Android

### ISSUE THREAD

**Issue by gloredo** [expo/expo#24239]
### Minimal reproducible example

https://github.com/gloredo/expo-sdk-49-downloaded-file-issue/tree/main

### Summary

After updating SDK 48 to 49, the `.mp4` and `.pdf` files downloaded through the `expo-file-system` are not displayed on Android, **but work on iOS**.

`<Video />` error:
```shell 
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FragmentedMp4Extractor, Mp4Extractor, FlvExtractor, FlacExtractor, WavExtractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
```

`<Pdf />` errors:
```shell
cannot create document: File not in PDF format or corrupted.
``` 
```shell
Error: File is empty
```

### Unsuccessful tries (on Android, same error):
- New Architecture with SDK 49
- [SDK 50 Beta (under development) - `expo-file-system@15.7.0`](https://github.com/gloredo/expo-sdk-49-downloaded-file-issue/tree/sdk-50-beta)

### Android screenshot
![image](https://github.com/expo/expo/assets/20311005/2d54bf95-1249-4258-b1d1-bb8238a1240e)

### iOS screenshot
![Simulator Screenshot - iPhone 14 Pro - 2023-09-03 at 21 14 28](https://github.com/expo/expo/assets/20311005/76bb10c0-d514-4876-92bd-74dcd7cc0284)

### Environment

```shell
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.1
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~49.0.8 => 49.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: managed
```

**Comment by gloredo** [comment]
I appreciate any information about it, we are unable to release a new version.

**Comment by trentcowden** [comment]
For me, `mp3` files aren't working either. When I use `readDirectoryAsync(documentDirectory)` from `expo-file-system`, the downloaded files show up in my downloads. However, I am unable to load them. I am getting the same error as @gloredo.

Our app is an audio-based app which is totally dependent on loading mp3 files. Any help with this is appreciated!

**Comment by trentcowden** [comment]
@gloredo, have you had success loading files in any other formats?

**Comment by gloredo** [comment]
> @gloredo, have you had success loading files in any other formats?

I did not try. But note that PDF uses rn-blob-util to load the file, so the problem is probably with the download from the expo-file-system.

**Comment by trentcowden** [comment]
Just tested this using `expo-file-system` version `15.6.0` and it appears to still be broken. Any updates on this?

**Comment by trentcowden** [comment]
@gloredo Have you been able to get this fixed? Did you install a newer version of `expo-file-system`?

**Comment by trentcowden** [comment]
It seems that the next update to `expo-file-system` is `15.5.0`. I've tried installing that in my project but I get an error related to `expoModulesCore.uuid` not being a function which I assume is just an incompatibility issue between different expo modules. Unfortunately it seems like I'll just have to wait until SDK 50 is released to get this fix?

**Comment by watadarkstar** [comment]
I'm having the same issues. Files downloaded on android are not working and are empty and the progress callback never hits 100.
