### ISSUE TITLE
[ios] after downloading new build from App Store, app occasionally reverts to using old JS bundle

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2424]
We've had a few reports of apps reverting to an older version of the JS bundle after updating to a new build through the App Store. It seems like this is an occasional issue when the app has been installed on the user's device for a long time. My guess is that this is an issue with the legacy naming of embedded bundles, meaning it won't affect new apps installed now for the first time, but may affect devices that have had the app installed since before May.

https://forums.expo.io/t/expo-uses-old-code-even-though-new-code-has-been-deployed/14764

**Comment by sibe7691** [comment]
I can confirm this issue, and I can also confirm that it can happen on fresh installs. 
I have had a few users just downloading the app, firing it up and it runs obvious old code (like "30~ publishes ago" old)

**Comment by esamelson** [comment]
@sibe7691 if this happens when the app is installed from the App Store for the very first time, that's a separate issue. But note that if you haven't built and released a new IPA recently and are using the default settings for OTA updates, the (old) code that is bundled inside of the IPA will run first, while fetching a newer version in the background -- this is expected behavior. Is it possible that's what those users are seeing?

**Comment by sibe7691** [comment]
@esamelson Thanks, It sounds possible indeed. Is there a link to the documentation where what you mentioned is stated? 
My settings are:
```
 "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD"
    }
```

**Comment by sibe7691** [comment]
@esamelson Note that in my case I'm running a detached app.

**Comment by esamelson** [comment]
@cantide5ga - thanks for bringing that up. Looks like that is actually a separate cause which won't be addressed by the fix I have already, so I'm going to track it in a new issue here: https://github.com/expo/expo/issues/2468
