### ISSUE TITLE
Building pre-release apk of expo managed app failed

### ISSUE THREAD

**Issue by OlammieAO** [expo/expo#24240]
### Summary

react: 18.2.0
react-native: 0.71.8
expo SDK : 48.0.18
project: expo managed
OS: windows

I was trying to build an apk and share an expo pre-release build of my app by using the "eas build -p android --profile preview" but the build was never successful. Expo doesn't handle the android and ios directory for build which eliminates the part of editing or modifying gradle settings in expo managed project. The build error has to do with "Deperecated Gradle" for react-native-reacnimated and I fix that by upgrading my gradle to version 8.3 and I got that fixed as the error wasn't showing again; another error occured again back to incompatibility between Gradle and Kotlin. I got frustrated and deleted the android folder to remove the gradle settings I have modified since I read everywhere that expo handles build settings. 

After exploring the internet, I found a package called react-native-gradle-plugin(https://github.com/facebook/react-native/issues/36642) that claims to managed the Gradle setting for react native build and I followed the steps but still got an error. At the react-native-gradle-plugin(https://github.com/facebook/react-native/issues/36642) url, the steps mentioned that we shoud edit "bundle.gradle" and "settings.gradle" file and I created a folder called "android" manually and created the two files with the contents as instructed on the url and with this i got react-native-reanimated error that I first resolved by upgrading gradle to 8.3. 

I have been facing this issue for over XMRbuild done since expo manages the build automatically but the build could not complete becuse of some android setting that expo is meant to handle?

Thank you

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

react: 18.2.0
react-native: 0.71.8
expo SDK : 48.0.18
project: expo managed
OS: windows

### Minimal reproducible example

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

**Comment by Kudo** [comment]
hi there! since gradle 8 introduces some breaking changes, sdk 48 does not support gradle 8. if you want to have gradle 8, please try to upgrade sdk 49. please check the [blog post](https://blog.expo.dev/expo-sdk-49-c6d398cdf740) for what new features coming in sdk 49 and the upgrade guide.
