### ISSUE TITLE
[expo-speech][ios] Expo speech 11.2.0 and above don't trigger events like onDone, onStart, etc. in iOS

### ISSUE THREAD

**Issue by ivanfuzuli** [expo/expo#24243]
### Minimal reproducible example

https://github.com/ivanfuzuli/expo-speech-bug

### Summary

Expo speech version [11.1.1](https://www.npmjs.com/package/expo-speech/v/11.1.1) worked perfectly on iOS. But in the newer version, there are a lot of warnings, and I need help to bind onStart, onDone, etc. events.

In 1.2.0 and above in initial load throws below warnings:
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

When I try to bind onStart and onDone events. But events don't fire. Instead, it throws the following warning to the console:
 WARN  Sending `Exponent.speakingStarted` with no listeners registered.
 WARN  Sending `Exponent.speakingWillSayNextString` with no listeners registered.
 WARN  Sending `Exponent.speakingDone` with no listeners registered.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Fixed in #24221

**Comment by ivanfuzuli** [comment]
> Fixed in #24221

Thanks. When will it be published on npm?

**Comment by alanjhughes** [comment]
It should be available now

**Comment by nightness** [comment]
Working for me...
"expo-speech": "~11.5.0"

**Comment by magician11** [comment]
11.5.0 also worked for me. Then I just downloaded the latest iOS simulator 17.0 and no longer get any speech at all. And no error messages.

**Comment by CyrisXD** [comment]
I'm trying to use 11.5.0 with iOS 17 in the simulator but have no speech. I am getting the following warnings, though: 

```
WARN  Sending `Exponent.speakingStarted` with no listeners registered.
WARN  Sending `Exponent.speakingStopped` with no listeners registered.
 ```

**Comment by trungpham10** [comment]
`npx expo install expo-speech` still results in 11.3.0
`npm i expo-speech` results in 11.5.0, but `Speech.speak` doesn't work. I'm using Expo managed workflow

**Comment by Aris-ngoy** [comment]
VoiceProvider: Could not start synthesis for request SSML Length: 19, Voice:
[AVSpeechSynthesisProviderVoice 0x6000022e8410] Name: Samantha, Identifier:
com.apple.voice.compact.en-US.Samantha, Supported Languages (
"en-US"

**Comment by CyrisXD** [comment]
I got it all working by using the following versions:

```
"expo": "^49.0.21",
"expo-speech": "^11.5.0",
```

iOS version 16.4
It seems iOS version 17 has problems in the simulator with Expo speech.

**Comment by EOMZON** [comment]
> 我通过使用以下版本使一切正常工作：
> 
> ```
> "expo": "^49.0.21",
> "expo-speech": "^11.5.0",
> ```
> 
> iOS 版本 16.4 似乎 iOS 版本 17 在使用 Expo 语音的模拟器中存在问题。

I have successfully resolved some of the tips using a version similar to yours, but there are new tips，Do you also have this tips?

`Some dependencies are incompatible with the installed expo version:
  expo-speech@11.5.0 - expected version: ~11.3.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix`

my version
`"expo": "~49.0.15",
  "expo-speech": "~11.5.0",`
  iOS 版本 16.4

**Comment by CyrisXD** [comment]
> I have successfully resolved some of the tips using a version similar to yours, but there are new tips，Do you also have this tips?
> 
> `Some dependencies are incompatible with the installed expo version: expo-speech@11.5.0 - expected version: ~11.3.0 Your project may not work correctly until you install the correct versions of the packages. Fix with: npx expo install --fix`
> 
> my version `"expo": "~49.0.15", "expo-speech": "~11.5.0",` iOS 版本 16.4

I have not come across this error, but I did also run the proposed fix after updating Expo
```
npm install expo@latest
npx expo install --fix
```

[Source](https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/)

**Comment by Jankaz2** [comment]
I have got the same bug on both ios emulator and real device. I am using `expo 50.0.17` and `expo-speech 11.7.0`.

```
[Speech] Received an error while accessing com.apple.speech.localspeechrecognition service: Error Domain=kAFAssistantErrorDomain Code=1101 "(null)"
[Speech] Received an error while accessing com.apple.speech.localspeechrecognition service: Error Domain=kAFAssistantErrorDomain Code=1101 "(null)"
[Speech] Received an error while accessing com.apple.speech.localspeechrecognition service: Error Domain=kAFAssistantErrorDomain Code=1101 "(null)"
[AudioToolbox]            AQMEIO_HAL.cpp:2791  iOSSimulatorAudioDevice-21377-3: Abandoning I/O cycle because reconfig pending (1).
[CoreAudio]      HALC_ProxySystem.cpp:163    HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj)
[CoreAudio]       HALC_ShellObject.mm:213    HALC_ShellObject::HasProperty: there is no proxy object
[CoreAudio] AudioHardware-mac-imp.cpp:1224   AudioObjectRemovePropertyListener: no object with given ID 177
[CoreAudio] AudioHardware-mac-imp.cpp:1224   AudioObjectRemovePropertyListener: no object with given ID 177
[CoreAudio] AudioHardware-mac-imp.cpp:1224   AudioObjectRemovePropertyListener: no object with given ID 177
[CoreAudio] AudioHardware-mac-imp.cpp:1224   AudioObjectRemovePropertyListener: no object with given ID 177
[CoreAudio] AudioHardware-mac-imp.cpp:1224   AudioObjectRemovePropertyListener: no object with given ID 177
 WARN  Sending `Exponent.speakingStarted` with no listeners registered.
```
