### ISSUE TITLE
Inapp browser libraries 

### ISSUE THREAD

**Issue by sarvold** [expo/expo#24251]
### Minimal reproducible example

https://github.com/sarvold/inappBrowser-expo-app

### Summary

Expected behaviour: open inapp browser for authentication flow. App should not break. In particular, I need inapp browsing for getting a code from redirectUrl after authenticated, but did not succeed to get to the redirectUrl in any way.
Actual behaviour: Authentication flow never happens because dependencies that open the inapp browser (e.g.: 'react-native-inappbrowser-reborn' and 'react-native-app-auth') fail with errors:
`[TypeError: Cannot read property 'isAvailable' of null]` and `[TypeError: Cannot read property 'authorize' of null]` respectively. 
Both dependencies are properly installed and when logged, they are actual objects containing those functions. When those functions get invoked, that kind of error is thrown. Maybe they are incompatible with expo?

Relates to:
https://stackoverflow.com/questions/77012102/how-to-use-an-inapp-browser-for-authentication-in-react-native-0-72-3-or-higher
https://github.com/proyecto26/react-native-inappbrowser/issues/434

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by catrius** [comment]
I ran into the same problem. After spending some hours searching for a solution, I ended up using Expo's in app browser https://docs.expo.dev/guides/linking/#in-app-browsers.
