### ISSUE TITLE
[docs] Broken link to "configured Expo modules"

### ISSUE THREAD

**Issue by terrysahaidak** [expo/expo#24258]
### Summary

When I was integrating expo-image, the link in the expo-image docs "[these additional installation instructions](https://github.com/expo/expo/tree/sdk-49/packages/expo-image)." navigated me to the github readme, then noticed that the link to "configured Expo modules" is broken and it took me a while to find the proper page on the expo docs website.

Not sure, but could be a problem in other places.

But maybe the link in expo-image docs should navigate straight to https://docs.expo.dev/bare/installing-expo-modules/ instead of taking me to the github?

### Link to the related docs page

https://github.com/expo/expo/tree/sdk-49/packages/expo-image#installation

**Comment by amandeepmittal** [comment]
Hey @terrysahaidak, sorry for the inconvenience. We'll fix the link and check for other docs to resolve this.

**Comment by terrysahaidak** [comment]
I would send the PR but I couldn't find the proper links, and in general wasn't sure how it should work.

But I think links in docs should take me to other parts of the docs instead of linking me to github pages where I would again navigate back to it.

I would really want that page with expo modules installation to be more accessible, I always search for it and only would find it after like 1m of searching because expo modules term in search takes me to the new expo modules API, not to the integration of expo packages into bare app.

**Comment by tarunrajput** [comment]
@amandeepmittal, this is already fixed in main branch

**Comment by amandeepmittal** [comment]
@tarunrajput, can you please point me towards which fix are you referring to?

**Comment by tarunrajput** [comment]
@amandeepmittal Sure, here https://github.com/expo/expo/commit/f0a3b6873ef7bb9386e2b286e08ac10f8c7e1645
