### ISSUE TITLE
Fix the missing icon to be able to install Progressive Web App (PWA) on Chrome 

### ISSUE THREAD

**Issue by jeanniton-mnr** [expo/expo#24250]
### Summary

As per expo [documentation](https://docs.expo.dev/guides/progressive-web-apps/), at the bottom, " ... the build step will still attempt to generate and append Chrome icons to your manifest.json."

The icon are not generated to be able to install the PWA. The following is the `manifest.json` code generated by `npx expo export:web`:
```
{
  "background_color": "#000",
  "display": "standalone",
  "lang": "en",
  "name": "AppName",
  "short_name": "AppName",
  "start_url": "/?utm_source=web_app_manifest",
  "orientation": "portrait"
}
```

The expected `manifest.json` generated should be something like:
```
{
  "background_color": "#000",
  "display": "standalone",
  "lang": "en",
  "name": "PayBooks",
  "short_name": "PayBooks",
  "start_url": "/?utm_source=web_app_manifest",
  "orientation": "portrait",
  "icons": [
    {
      "src": "./icon.png",
      "sizes": "144x144",
      "type": "image/png"
    }
  ]
}
```

### What platform(s) does this occur on?

Web

### SDK Version

48.0.6

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.7
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.2 
      expo: ~48.0.6 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ^0.18.12 => 0.18.12 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

1. `expo init app-name --typescript`
2. `cd ./app-name`
3. `npm install`
4. `npx expo export:web`
5. `cd ./web-build`
6. `serve`
7. Try to open the serving address on Chrome browser.
<img width="1213" alt="Screen Shot 2023-09-03 at 11 40 17 AM" src="https://github.com/expo/expo/assets/11714176/2e26847a-925f-4ba8-98d0-f4c9926884d9">

**Comment by jeanniton-mnr** [comment]
Now, I am posting a quick work-around to fix this issue:

1. Install **expo-pwa**: `npm install -g expo-pwa`
2. Inside your project, run: `expo-pwa manifest`
3. Inside the generated `./web/manifest.json`, add:
```
{
 ...
  "icons": [
    {
      "src": "./icon.png",
      "sizes": "144x144",
      "type": "image/png"
    }
  ]
}
```
4. Add custom npm script:
`npx expo export:web && cp ./pathToYour/icon.png ./web-build/icon.png`

**Comment by orta** [comment]
I'm guessing because I don't have access to a macOS Sonoma install ATM, but it's likely that this is making icons on there not work also

**Comment by Panda-ref** [comment]
Not stale

**Comment by Panda-ref** [comment]
Not stale x2

**Comment by Panda-ref** [comment]
Not stale x3
