### ISSUE TITLE
[Expo-AV] Audio recording with LOW_QUALITY preset making 10mb per minute recordings

### ISSUE THREAD

**Issue by jvgeee** [expo/expo#24257]
### Minimal reproducible example

https://snack.expo.dev/@jvggoodwork/expo-av-demo

### Summary

In IOS on the simulator, I'm recording audio with this code:

```
async function startRecording() {
    if (onStart) onStart()
    try {
      await Audio.requestPermissionsAsync()

      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
        interruptionModeIOS: 1,
        shouldDuckAndroid: true,
        interruptionModeAndroid: 1,
        playThroughEarpieceAndroid: false,
      })

      const { recording: newRecording, status } = await Audio.Recording.createAsync(
        RecordingOptionsPresets.LOW_QUALITY,
        onRecordingStatusUpdate,
      )

      setFinalRecording(newRecording)

      if (onChange) onChange({ isRecording: true })
    } catch (err) {
      console.error("Failed to start recording", err)
    }
  }
```

If I do a 1 minute recording, when I look at the CAF file it's created it's 10mb. If I do avinfo on the file, it returns this:

```
 AV afinfo recording-3538557C-FE13-426D-9939-E1EAC8DA6BC7.caf
File:           recording-3538557C-FE13-426D-9939-E1EAC8DA6BC7.caf
File type ID:   caff
Num Tracks:     1
----
Data format:     2 ch,  44100 Hz, Int16, interleaved
                no channel layout.
estimated duration: 54.214694 sec
audio bytes: 9563472
audio packets: 2390868
bit rate: 1411200 bits per second
packet size upper bound: 4
maximum packet size: 4
audio data file offset: 4096
optimized
audio 2390868 valid frames + 0 priming + 0 remainder = 2390868
source bit depth: I16
```

Why are the filesizes so high? Estimates tell me that it should be about 1MB per minute, e.g.:

```
Bit rate: 128,000 bits per second (128 kbps)
Sample rate: 44,100 Hz
Number of channels: 2 (Stereo)
Now, let's calculate the estimated file size for a 1-minute recording:

Total bits recorded in 1 minute:
Total bits = Bit rate * 60 seconds = 128,000 bps * 60 seconds = 7,680,000 bits

Convert total bits to bytes (1 byte = 8 bits):
Total bytes = Total bits / 8 = 7,680,000 bits / 8 = 960,000 bytes

Convert total bytes to kilobytes (KB):
Total KB = Total bytes / 1024 = 960,000 bytes / 1024 = 937.5 KB (approximately)

So, with the provided LOW_QUALITY preset settings, a 1-minute audio recording using Expo-AV could be estimated to be approximately 937.5 kilobytes (KB) in size. This is roughly 0.92 megabytes (MB).
```

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.5.1
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9619390
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
npmGlobalPackages:
expo-cli: 6.3.10

Using "expo-av": "~13.2.1",

**Comment by jvgeee** [comment]
@behenate Awesome, thank you! Do you have a workaround for the options I can pass in for now, until the PR is merged?

**Comment by behenate** [comment]
@jvgeee To be honest switching to `HIGH_QUALITY` preset seems to be the simplest solution. When testing it produced files that are around 800KB per minute. If this is not good enough for you you can use `patch-package` and apply the changes from the PR into your project.
