### ISSUE TITLE
expo-image-picker randomly shows blank screen when media is picked in production

### ISSUE THREAD

**Issue by Klin-Coders** [expo/expo#24264]
### Minimal reproducible example

Using the example method on the expo image picker docs

### Summary

expo image picker is erratic, once i pick an image first time it works, but second time shows a blank white screen

https://github.com/expo/expo/assets/49831574/27f33ae2-f3d8-4b18-b6d8-f951e8815c84

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      npm: 9.5.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      expo: ^49.0.6 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 3.17.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by Klin-Coders** [comment]
managed to fix it

**Comment by Remrem08007** [comment]
@1finedev im having the same issue. How’d you fix it?

**Comment by 1finedev** [comment]
I think what fixed it for me was moving the file state into the local component.

i was using zustand and was save the file into a global sort of state, so i used a useState directly inside of my upload component and with other refactors i did, things were fixed

Hopefully this helps
but i tried a ton of things and cant say for sure which works 

> @1finedev im having the same issue. How’d you fix it?
