### ISSUE TITLE
Error: Cannot prompt to authenticate until the request has finished loading in React Native with Firebase and Expo Auth Session

### ISSUE THREAD

**Issue by ajdnakljdkjasdnasdad** [expo/expo#24266]
### Minimal reproducible example

const LoginScreen = ({ route }) => { const { setInfoEntered, promptAsyncGoogle, setLoading, setUser } = route.params  //..  <TouchableOpacity style={styles.googleButton} onPress={() => { promptAsyncGoogle()}}>       <View style={styles.buttonIcon}>         <AntDesign name="google" style={styles.googleIcon} />       </View>       <Text style={styles.googleText}>Logga in med Google</Text> </TouchableOpacity>

### Summary

I'm encountering an issue in my React Native application when trying to implement Google authentication using Firebase and Expo Auth Session. When I attempt to log in with Google, I receive the following error message:

Copy code Error: Cannot prompt to authenticate until the request has finished loading. Problem Description:

I have two main components in my application, App and LoginScreen, both of which utilize the promptAsyncGoogle function to initiate the Google authentication process.

In the App component, I'm initializing the promptAsyncGoogle function using the Google.useAuthRequest hook. This function is used to initiate Google authentication when the app starts.

In the LoginScreen component, I'm using the same promptAsyncGoogle function to initiate Google authentication when the user clicks the "Logga in med Google" button.

Issue Details:

The error occurs when I press the "Logga in med Google" button in the LoginScreen component. However, if I press the "Logga in med Google" button in the CreateAccount component first (which also uses promptAsyncGoogle), it starts working, and I can log in with Google successfully.

Here is the relevant code from my App component:

```
// Code from App.js  
// ...  
useEffect(() => {   
const { request, response, promptAsyncGoogle } = Google.useAuthRequest({     
useProxy: true,     
expoClientId: '',     
androidClientId: '',   
});    
// ...    
useEffect(() => {     
if (response?.type === "success") {       
// Handle successful authentication     
} else if (response?.type === "dismiss" || response?.type === "error") {      
// Handle dismissal or error     
}        
}, [response]);    // ...  }, []); 
```

And here is the relevant code from my LoginScreen: 

```
const LoginScreen = ({ route }) => {
const { setInfoEntered, promptAsyncGoogle, setLoading, setUser } = route.params

//..

<TouchableOpacity style={styles.googleButton} onPress={() => { promptAsyncGoogle()}}>
      <View style={styles.buttonIcon}>
        <AntDesign name="google" style={styles.googleIcon} />
      </View>
      <Text style={styles.googleText}>Logga in med Google</Text>
</TouchableOpacity>
```

Question:

What could be causing the "Cannot prompt to authenticate until the request has finished loading" error in the LoginScreen component?

Why does the Google authentication work in the LoginScreen component only after using it in the CreateAccount component first?

How can I ensure that the promptAsyncGoogle function in the LoginScreen component works correctly from the beginning, without requiring prior usage in another component?

Any insights, suggestions, or solutions would be greatly appreciated. Thank you!

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - ~\OneDrive\Dokument\VisulaStudio Projects\FoodCheck\node_modules\.bin\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.2
      expo: ~48.0.18 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: bare

**Comment by oursland** [comment]
I am also encountering this issue.
