### ISSUE TITLE
[android] Expo client behaves badly with dev=false

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2426]
If `dev=false` in development, then this leads the client to think we're in prod anyway and to use the OTA updates configuration in app.json (which should be ignored for dev). Also, if there is an error with the bundler, it either says nothing in the client and silently loads the previous bundle or shows "Error reading multipart response". Additionally, it doesn't show the bundle/download progress indicator.

**Comment by ide** [comment]
@esamelson has this old issue been taken care of with expo-updates? (It seems like it would depend on how expo-updates determines whether an update is served from a development server or not.)

**Comment by esamelson** [comment]
yes, this has been fixed -- we now have separate checks for `isDevelopmentMode` and `isUsingDeveloperTool` which are used in the correct places. This issue was caused by the old updates code conflating those two checks.
