### ISSUE TITLE
[docs] How do I add Flipper plugins

### ISSUE THREAD

**Issue by gelmio** [expo/expo#24276]
### Summary

I've followed the [using Flipper](https://docs.expo.dev/guides/using-flipper/) guide in the docs and it is all up and running fine, however only a handful of the Flipper plugins are available out of the box (see screenshot) and the documentation doesn't make any mention of how to add the others. Any advice / updated docs on this topic would be much appreciated.

![image](https://github.com/expo/expo/assets/23208546/00ca80bf-2f3b-4937-b1ab-280fe2f9a692)

### Link to the related docs page

https://docs.expo.dev/guides/using-flipper/

**Comment by Kudo** [comment]
hi there! you may go to https://fbflipper.com/docs/ for more detailed doc. to install more plugins, maybe ["alongside other available Flipper plugins, by clicking on 'Manage Plugins...' in the bottom of the left sidebar and selecting the 'Install Plugins' tab"](https://fbflipper.com/docs/tutorial/js-publishing/#installing-plugins) is what you looking for.

if you just look for react devtools, we also have react devtools integration inside expo-cli from sdk 49. may worth to try out: https://docs.expo.dev/debugging/tools/#debugging-with-react-devtools
