### ISSUE TITLE
[sqlite] RETURNING clause not working on Android

### ISSUE THREAD

**Issue by kevin-dp** [expo/expo#24283]
### Minimal reproducible example

https://snack.expo.dev/@k_dp/android-sqlite-returning?platform=android

### Summary

On Android, expo-sqlite fails when using a `RETURNING` clause in an insert statement (did not test it with other statements) and returns an error. Consider this example:

```typescript
import { openDatabase } from 'expo-sqlite';
const db = openDatabase('test.db');

// Regular insert statement works:
const res = await db.execAsync([
  {
    sql: "INSERT INTO items (value) VALUES ('0a0e4e84-3096-4802-b3bc-562b0f987223')",
    args: []
  }
], false)
console.log(res) // prints [{"insertId": 0, "rows": [], "rowsAffected": 1}]

// Insert statement with returning clause fails
const res2 = await db.execAsync([
  {
    sql: "INSERT INTO items (value) VALUES ('0a0e4e84-3096-4802-b3bc-562b0f987224') RETURNING value",
    args: []
  }
], false)
console.log(res2) // prints [{"error": [Error: unknown error (code 0 SQLITE_OK): Queries can be performed using SQLiteDatabase query or rawQuery methods only.]}]
```

Note the error for the second insert statement:
> Error: unknown error (code 0 SQLITE_OK): Queries can be performed using SQLiteDatabase query or rawQuery methods only.

The same error occurs with `db.exec()` and with `tx.executeSql()`. 

This can also be observed in this snack: [https://snack.expo.dev/@k_dp/android-sqlite-returning?platform=android](https://snack.expo.dev/@k_dp/android-sqlite-returning?platform=android).
Looking at the output we notice that the results of the third SQL statement (the one that uses a `RETURNING` clause) is an error but that the 4th one (which is the same SQL statement but without `RETURNING`) succeeds.
For some reason, the error message in the snack is missing and is just the empty object whereas on my machine i get the error described above.

Note that on my machine, `RETURNING` clauses work fine when emulated on an iOS device.
The problem is only with emulated Android device (have not tested it on an actual device as i don't own one).

### Suspected cause

I believe that the problem is that expo-sqlite ["parses" the SQL statement to see if it is a select](https://github.com/expo/expo/blob/main/packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt#L32) (i.e. returns a result) or an insert/update/delete (which is assumed not to return a result?). For reads [it uses Android's `SQLiteDatabase.rawQuery()`](https://github.com/expo/expo/blob/main/packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt#L113) but [for inserts it uses `SQLiteStatement.executeInsert()`](https://github.com/expo/expo/blob/main/packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt#L92) which i guess is not happy with the returning clause.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.8 
      react: ^18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
The issue here is the Android bindings. On iOS, we have full access to the SQLite C api so we can use everything that is supported by the currently installed version (3.39.2 at the moment). On Android, we use a third party lib to update to a newer version of SQLite. For the most part this library is just using the standard provided Android bindings with some modifications, but these are extremely out of date. Android uses [Room](https://developer.android.com/jetpack/androidx/releases/room) now so these bindings are likely to continue to receive no attention.

As a solution, we could introduce a new API. Something like `executeRawQuery()` which should allow you to run any valid SQLite query. There may be a slight performance hit when using this but I don't think it'll be an issue.
cc @brentvatne

**Comment by kevin-dp** [comment]
@alanjhughes Introducing `executeRawQuery()` would indeed solve our issue here.
Thanks for the fast reply!
