### ISSUE TITLE
Impossible to use swift in C++ with expo 49

### ISSUE THREAD

**Issue by matthieuMay** [expo/expo#24285]
### Minimal reproducible example

https://github.com/matthieuMay/rn72

### Summary

I try to upgrade from RN71 + expo48 to RN72 + expo49. I face a problem that occurs when you try to use swift code in CPP.

To reproduce the problem : 
 - create a bare RN72 repo (1st commit of repro repository)
 - add expo modules with `npx install-expo-modules@latest`(2nd commit)
 - create a dummy swift class and try to use it in the appDelegate.mm file

This will fail the compilation with error 

rn72.build/Debug-iphonesimulator/rn72.build/DerivedSources/rn72-Swift.h:287:34: error: cannot find interface declaration for 'ModulesProvider', superclass of 'ExpoModulesProvider'

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
      Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-30 | Intel x86_64 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-Tiramisu | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: bare

**Comment by Kudo** [comment]
this patch should work for you

```patch
--- a/ios/Hello.swift
+++ b/ios/Hello.swift
@@ -8,7 +8,7 @@
 import Foundation

 @objc
-class HelloWord: NSObject {
+public class HelloWord: NSObject {

   public override init() {}

diff --git a/ios/rn72/AppDelegate.mm b/ios/rn72/AppDelegate.mm
index cd12783..b57e959 100644
--- a/ios/rn72/AppDelegate.mm
+++ b/ios/rn72/AppDelegate.mm
@@ -2,6 +2,7 @@

 #import <React/RCTBundleURLProvider.h>

+#import <ExpoModulesCore-Swift.h>
 #import <rn72-Swift.h>

 @implementation AppDelegate
```

**Comment by vladimirivanoviliev** [comment]
Thank you very much for the solution - it solved my issue.

For future readers - this issue is also discussed [here](https://github.com/expo/expo/issues/17705).
