### ISSUE TITLE
Status bar on android app doesn't get updated after, we navigate back to the screen 

### ISSUE THREAD

**Issue by iammeetpatel** [expo/expo#24281]
### Minimal reproducible example

https://github.com/iammeetpatel/epxo-routes-example/tree/main/app/(tabs)

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

On the index screen, we set a dark style for the status bar using `<StatusBar translucent style='dark' />`. On the third screen, we use `<StatusBar translucent style='light' />`.

Both styles work fine initially. However, after navigating to the third screen and then navigating back to the index screen, the status bar style does not change back to 'dark'.

https://github.com/expo/expo/assets/102008189/97fb9d8e-cead-4fe1-a119-fa8489b3bdb9

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /Users/meetpatel/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.6 => 0.19.8 
    Expo Workflow: managed



```

**Comment by marklawlor** [comment]
The React Navigation `<Tabs />` navigator does not unmount a tab when not visible. So when you go from Tab1->Tab3->Tab1. Tab1 is *not* unmounted and rendered again.

A better approach would be to use `useFocusEffect` to invoke a callback when that route is focused. You can then use the imperative APIs to control the status bar https://docs.expo.dev/versions/latest/sdk/status-bar/#methods
