### ISSUE TITLE
Expo router with bottom tabs navigation with a briefly blank screen being shown

### ISSUE THREAD

**Issue by nelsonprsousa** [expo/expo#24295]
### Minimal reproducible example

https://github.com/nelsonprsousa/expo-router-nested-nav

### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

While using expo-router with bottom tabs navigation, there's an empty blank screen between the transition of Splashscreen and the tabs. This is happening on the minimal reproducible example I provided, but also by following the [quick start from documentation](https://docs.expo.dev/routing/installation/#quick-start).

`npx create-expo-app@latest --template tabs@49`

`npx expo start`

If you mess around with the player, right before the tabs are actually rendered, you can see that there's 1 or 2 frames with a blank screen (it's not super easy to detect without messing around with the controlers).

https://github.com/expo/expo/assets/8364345/5828be4a-62a0-4e6f-af40-b72c0c2fd62b

### Environment

    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.03.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 23.0.1, 25.0.1, 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    Expo Workflow: managed

**Comment by janusqa** [comment]
I have the same issue but have not yet tracked down what causes it.

**Comment by claudesortwell** [comment]
Yep same issue, though seems to last up a few seconds. So might not be related

**Comment by EvanBacon** [comment]
This is due to the fact that the [splash screen is being dismissed](https://github.com/nelsonprsousa/expo-router-nested-nav/blob/ca25c7c2f8c0937097ce398c32d1279f3cbb6d1f/app/_layout.tsx#L34) before the navigation is mounted. You can alternatively move the logic to a layout group so the splash screen is hidden when the navigation is mounted:

```
app/
  _layout.js -> Render app `<Slot />`
  (root)
    _layout.js -> Load assets and hide splash screen.
```

In the newer authentication guide, we recommend using this pattern as it works more reliably with a smaller knowledge requirement of how native navigation works.

**Comment by jduhking** [comment]
> This is due to the fact that the [splash screen is being dismissed](https://github.com/nelsonprsousa/expo-router-nested-nav/blob/ca25c7c2f8c0937097ce398c32d1279f3cbb6d1f/app/_layout.tsx#L34) before the navigation is mounted. You can alternatively move the logic to a layout group so the splash screen is hidden when the navigation is mounted:
> 
> ```
> app/
>   _layout.js -> Render app `<Slot />`
>   (root)
>     _layout.js -> Load assets and hide splash screen.
> ```
> 
> In the newer authentication guide, we recommend using this pattern as it works more reliably with a smaller knowledge requirement of how native navigation works.

Where can I find this so called authentication guide?

**Comment by rafakwolf** [comment]
same here, was this solved?

**Comment by harrisrobin** [comment]
> ts and hide splash screen.

@EvanBacon this didn't help in my case. I simply stopped hiding the splash screen myself for now.
