### ISSUE TITLE
Hot Reloading Unavailable

### ISSUE THREAD

**Issue by Rafaell416** [expo/expo#243]
## Description

Hey guys, your product expo is awesome! thanks a lot.
but i'm writing this for asking help with something.
I'm rendering the same app in the Expo IOS and Android client. in Android I can use hot reloading  but in IOS I can't.

## Expected Behavior

I shake my Iphone and the config screen appear but when I try to click the Hot reloading button to enable it. It is Disabled with te text: Hot Reloading Unavailable. I want to be able to use hot reloading in both platforms. Android and IOS
![screen](https://user-images.githubusercontent.com/18080929/26969274-cc660522-4cca-11e7-9500-7e8ae1a8b8a0.jpg)

I would be grateful if you would help me. Thanks a lot.

**Comment by terribleben** [comment]
Hi! Please disable live reload first. They are mutually exclusive.

We could make this message and behavior much more clear. I'll see what I can do about that. Thanks for bringing it up.

Let me know if that solution doesn't work for you.

**Comment by mariotacke** [comment]
Hi, just ran into this as well. It was not clear to me, coming from the regular react-native environment, to first disable live reload. Maybe we can disable live reload and enable hot module reload with a single click?

**Comment by mck-** [comment]
Using standard boilerplate from Expo, I'm getting this error when I enable it:

`locals[0]` does not appear to be a `module` object with Hot Module replacement API enabled.

**Comment by ITsolution-git** [comment]
Hello. I see that the live reload and hot reloading both unavailable on ios.
Is there any one who can help me. Thanks.

I am using expo `23.0.4`
Here's my package.json
`
"create-react-class": "^15.6.2",
    "expo": "23.0.4",
    "immutable": "^3.8.2",
    "key-mirror": "^1.0.1",
    "lodash": "^4.17.4",
    "moment": "^2.20.1",
    "native-base": "^2.3.7",
    "prop-types": "^15.6.0",
    "react": "16.0.0",
    "react-addons-pure-render-mixin": "^15.5.0",
    "react-mixin": "^4.0.0",
    "react-native": "0.50.0",
`

**Comment by alexpessoajr** [comment]
@ITsolution-git stop the remote debugging.

**Comment by frayhan32** [comment]
Ya the solution for disable live reload helps me.
