### ISSUE TITLE
DeviceMotion: orientation returns 0 despite rotating phone while ScreenOrientation is locked

### ISSUE THREAD

**Issue by jesouhaite08** [expo/expo#2430]
### Environment

Environment:
  OS: OS X Yosemite 10.10.5
  Node: 8.2.1
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

Target: Android

### Steps to Reproduce

1. Lock your app orientation to portrait by setting the following in your componentWillMount function:
```
componentWillMount() {
  Expo.ScreenOrientation.allow(Expo.ScreenOrientation.Orientation.PORTRAIT)
}
```
2. Subscribe for updates to DeviceMotion

```
import React from 'react';
import { Text, View } from 'react-native';
import { DangerZone, ScreenOrientation } from 'expo';

export default class DeviceOrientationExample extends React.Component {
  state = {
    deviceMotionData: {},
  }

  componentWillMount() {
    ScreenOrientation.allow(ScreenOrientation.Orientation.PORTRAIT)
  }

  componentDidMount() {
    this._toggle();
  }

  componentWillUnmount() {
    this._unsubscribe();
  }

  _toggle = () => {
    if (this._subscription) {
      this._unsubscribe();
    } else {
      this._subscribe();
    }
  }

  _subscribe = () => {
    this._subscription = DangerZone.DeviceMotion.addListener(deviceMotionData => {
      this.setState({ deviceMotionData })
    });
  }

  _unsubscribe = () => {
    this._subscription && this._subscription.remove();
    this._subscription = null;
  }

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center',alignItems: 'center'}}>
        <Text>DeviceMotion orientation: {this.state.deviceMotionData.orientation}</Text>
      </View>
    );
  }
}
```

### Expected Behavior

The DeviceMotion orientation (this.state.deviceMotionData.orientation) should return 90 when rotating the phone to landscape.

### Actual Behavior

The DeviceMotion orientation (this.state.deviceMotionData.orientation) returns 0 when rotating the phone to landscape.

### Reproducible Demo

https://snack.expo.io/S1a6RaGi7

It looks as though react-native-orientation solved this: https://github.com/yamill/react-native-orientation/issues/63

**Comment by quinlanj** [comment]
hi, so when i run your snack and i print out the console output like so:
``` 
 _subscribe = () => {
    this._subscription = DangerZone.DeviceMotion.addListener(deviceMotionData => {
      console.log("Updated device to " + JSON.stringify(deviceMotionData));
      this.setState({ deviceMotionData })
    });
  }
```
the listener is getting called, and as i rotate my phone, the `x`, `y` and `z` axis coordinates seem to be getting updated correctly. I might be missing something here, but since we've locked the phone orientation to `PORTRAIT`, shouldn't we expect the orientation to be locked as well (hence the constant `0`)?

**Comment by jesouhaite08** [comment]
Hi, @quinlanj . I would like to allow a user to take a landscape photo in portrait mode, so that they aren't slowed down by the animation that happens from portrait to landscape (Instagram does this). I plan to accomplish this by checking if the orientation is in landscape and if so, rotating appropriately.

**Comment by jesouhaite08** [comment]
You are correct that the listener is called. I would just like to see it return the correct orientation, regardless if the phone is locked or not.

**Comment by jesouhaite08** [comment]
It's OK if this API doesn't return the phone's position, but there doesn't appear to be any way to get that info at the moment.

**Comment by quinlanj** [comment]
hi @jesouhaite08, makes sense. Thanks for reporting this issue, and we shall look into it :)

**Comment by palodelincak** [comment]
Hi, is there any progress with this issue?

**Comment by brentvatne** [comment]
@palodelincak - there hasn't, if you'd like to investigate it would be much appreciated, you can look into it in https://github.com/expo/expo/tree/master/packages/expo-sensors

**Comment by jesouhaite08** [comment]
@brentvatne Are there any plans of fixing this in a future release? Thanks :)

**Comment by Fausto-Payano-Axomic** [comment]
Figured I'd share a very rough work-around I did due to Android not returning true device orientation if you lock the orientation either via config settings or via ScreenOrientation

```
orientationCalculation(gamma, beta) {
        let ABSOLUTE_GAMMA = Math.abs(gamma);
        let ABSOLUTE_BETA = Math.abs(beta);
        let isGammaNegative = Math.sign(gamma) == '-1';
        let orientation = 0;

        if (ABSOLUTE_GAMMA <= 0.04 && ABSOLUTE_BETA <= 0.24) {
            //Portrait mode, on a flat surface.
            orientation = 0;
        } else if (
            (ABSOLUTE_GAMMA <= 1.0 || ABSOLUTE_GAMMA >= 2.3) &&
            ABSOLUTE_BETA >= 0.5
        ) {
            //General Portrait mode, accounting for forward and back tilt on the top of the phone.
            orientation = 0;
        } else {
            if (isGammaNegative) {
                //Landscape mode with the top of the phone to the left.
                orientation = -90;
            } else {
                //Landscape mode with the top of the phone to the right.
                orientation = 90;
            }
        }
        return orientation;
    }
```

I call the above as follows:

```
orientation = this.orientationCalculation(
                                Number(deviceMotionData.rotation.gamma).toFixed(
                                    2
                                ),
                                Number(deviceMotionData.rotation.beta).toFixed(
                                    2
                                )
                            );

```

This may not be the best solution or even the best code... but its the one I came up with and it seemed to work decently well in production. Hopefully it helps someone out there stuck on this issue as well.

**Comment by gang544043963** [comment]
I met the same problem. The latest DeviceMotion didn't solve this problem.

The status as bellow:
iOS: whether locked the screen into portrait or not(in app.json: "orientation": "portrait"), it can get  correct orientation in DeviceMotion.addListener.
Android: can not get correct orientation when screen is locked in 'portrait', always '0'.

If you need to rotate the specified page, and other pages still 'portrait', you can do this as bellow:

```
import { ScreenOrientation } from 'expo';
import { DeviceMotion } from 'expo-sensors';

componentDidMount() {
        ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.ALL)
        .catch(error => { });

        DeviceMotion.isAvailableAsync().then((result) => {
            if (result == true) {
                DeviceMotion.addListener((object) => {
                    
                    let orientation = object.orientation;
                    if (orientation == 0 || orientation == 180) {
                        //
                    } else {
                        //
                    }
                })
                .catch(error => {
                });
            }
        })
        .catch(error => {
        });
    }
```

NOTE:
Enable screen rotate: ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.ALL)

This way solved my problem.
