### ISSUE TITLE
iOS 17 support for calendar permissions scope: `requestAccessToEntityType` deprecated in favor of `requestFullAccessToEventsWithCompletion`

### ISSUE THREAD

**Issue by cmlarsen** [expo/expo#24343]
### Minimal reproducible example

https://snack.expo.dev/hpDQeKGu7

### Summary

In iOS 17, they have broken out the permissions scope to include Read, write, and full access where previously it was only full access.  As a result the current `Calendar.requestCalendarPermissionsAsync()` throws the following error when run on iOS 17, but works on iOS 16.

`Error: -requestAccessToEntityType:completion: has been deprecated-calling this method is no longer allowed. Instead, use -requestFullAccessToEventsWithCompletion:, -requestWriteOnlyAccessToEventsWithCompletion:, or -requestFullAccessToRemindersWithCompletion:.`

See deprecation  notice for  `requestAccessToEntityType`  here: https://developer.apple.com/documentation/eventkit/ekeventstore/1507547-requestaccesstoentitytype

See here for more info: https://developer.apple.com/documentation/eventkit/ekeventstore/4162272-requestfullaccesstoeventswithcom

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nodenv/versions/16.19.0/bin/node
      Yarn: 1.22.19 - ~/.nodenv/versions/16.19.0/bin/yarn
      npm: 8.19.3 - ~/.nodenv/versions/16.19.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
      Android SDK:
        API Levels: 24, 26, 28, 29
        Build Tools: 23.0.2, 24.0.1, 26.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 15.0/15A5195m - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.0.8

**Comment by alexanderblackh** [comment]
Can confirm this is also happening on my iOS and iPadOS 17 device with the same error. As soon as I run it on an iOS 16 device, it works. Seems this is almost certainly from it being deprecated. Pressing issue since iOS 17 is expected to launch in a couple of weeks.

**Comment by cmlarsen** [comment]
iOS17 is likely dropping tomorrow (September 12).

**Comment by alexanderblackh** [comment]
iOS 17 entered RC the other day, and it's releasing tomorrow, the 18th and this issue is still a problem with the RC. It outright prevents using Expo Calendar in iOS 17.

**Comment by sascha-schieferdecker** [comment]
Can confirm the Issue

**Comment by alexanderblackh** [comment]
@alanjhughes @Kudo , could we please get some help on this one please? Expo Calendar appears to be entirely unusable on  iOS 17.

**Comment by alexanderblackh** [comment]
Thanks so much @alanjhughes, really appreciate the fast work. Unfortunately, it's still presenting the same error with ` "expo": "^49.0.11",
    "expo-calendar": "^12.0.0",` 

Is this because Expo Modules API hasn't been merged yet, or is the issue simply persisting?

**Comment by alanjhughes** [comment]
Hi @alexanderblackh - this change hasn't been published yet. Will let you know when it's available 👍

**Comment by alanjhughes** [comment]
@alexanderblackh Can you try version `12.0.1` and let us know how it goes 👍

**Comment by alanjhughes** [comment]
🤔 it should be. Can you try `npx expo install expo-calendar@next`?

**Comment by Fouppy** [comment]
With that it installs the `~11.3.1` version. `yarn outdated` outputs `12.0.0` still.

**Comment by sascha-schieferdecker** [comment]
expo-calendar@next resolves to 11.3.1:

https://www.npmjs.com/package/expo-calendar/v/next

**Comment by alexanderblackh** [comment]
Sorry @alanjhughes  just saw this. I can confirm what the others are saying; both `@latest` and `@next` install `11.3.1` regardless of using `expo install` or `yarn add`, and specifying the version via yarn doesn't show `12.0.1` as an option just as @Fouppy said.

**Comment by alanjhughes** [comment]
@alexanderblackh can you try `npx expo install expo-calendar` and just run a build with Xcode 15 on whatever version is installed?

**Comment by brentvatne** [comment]
@alanjhughes' suggestion will pull in `expo-calendar@11.3.1` on sdk 49, [which includes his fix](https://github.com/expo/expo/blob/98cece365f44c39b3d9e708633343d2a18a67635/packages/expo-calendar/CHANGELOG.md#1131--2023-09-25).

**Comment by alanjhughes** [comment]
@alexanderblackh also the config plugin has been updated so you'll need to run `npx expo prebuild --clean` to get those changes too. I will update the documentation tomorrow but you don't need to do anything. It has default values as before.

**Comment by alexanderblackh** [comment]
@alanjhughes, Afraid I'm still seeing the issue. Is there a separate step I need to do since this is a bare rn project? Didn't run `prebuild` due to this

**Comment by alanjhughes** [comment]
You'll need to add new keys to your `info.plist` https://developer.apple.com/documentation/bundleresources/information_property_list/nscalendarsfullaccessusagedescription and https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersfullaccessusagedescription

**Comment by alexanderblackh** [comment]
I had those already, still not working.

Here's my versions in my package.json: 
```
    "expo": "^49.0.13",
    "expo-calendar": "~11.3.1",
```

**Comment by alanjhughes** [comment]
What error are you getting?

**Comment by alanjhughes** [comment]
Those are the necessary changes. We need to add another is version check. I'll be adding it today.

**Comment by alanjhughes** [comment]
@alexanderblackh 11.3.2 has been published. Can you give it a try?

**Comment by sascha-schieferdecker** [comment]
Looks good 👍 

I have built a version and tested it on my iPhone running iOS 17.0.2 and ran it in a simulator with iOS 16. Thank you so much!!! 

Let's just hope Apple does not complain that we can only request full access, writing would suffice in the case of my app. It is an event calendar, which offers the option to add the event to one of your own calendars.

**Comment by alanjhughes** [comment]
@sascha-schieferdecker - we're evaluating the rest of the changes and hope to support them in SDK 50. I don't think apple will have an issue though. They'd break a lot of apps if they did.

**Comment by alexanderblackh** [comment]
Excellent work @alanjhughes, thank you! Working now on both iOS and iPadOS 17.

**Comment by Fouppy** [comment]
Thank you, it's working 👍

**Comment by bashalla** [comment]
I can't receive calendar access prompt on iOS 17.03 and expo 50 anymore. Is this issue known already ?

**Comment by ianisme** [comment]
Thank you, it's working 👍

**Comment by jjdlp** [comment]
@alanjhughes any update on this: "we're evaluating the rest of the changes and hope to support them in SDK 50" ? Will there be any way to request only granular permissions and not access to the full calendar?
