### ISSUE TITLE
Install Pods step in EAS does not respect generated app config or env vars

### ISSUE THREAD

**Issue by tomrom-pomelo** [expo/expo#24341]
### Summary

When building our app for iOS, we are seeing the following error:

```
Configuring Xcode project

Assigning provisioning profile '*[expo] com.pomelocare.patient AppStore 2022-06-06T19:28:33.639Z' (Apple Team ID: T77K2WU9P2) to target 'PomeloCare'

Could not find target 'PomeloCare' in project.pbxproj
```

This only occurred when upgrading to expo 49, which is unusual. We traced down the issue to the Install Pods step, where we see references to the incorrect target:

```
Auto-linking React Native modules for target `PomeloCareDev`: RNCAsyncStorage, RNGestureHandler, RNSVG, RNScreens, RNSentry, react-native-document-picker, react-native-netinfo, react-native-safe-area-context, segment-analytics-react-native, and sovran-react-native
```

Notice it says `PomeloCareDev`, not `PomeloCare`.

This is unusual because the generated app.json in the `Read app config` step has all the correct values:
```
"name": "Pomelo Care",
"slug": "pomelo-care",
"owner": "pomelocare",
```

We do use a environment variable to dynamically generate the app config, and by default it sets the app name to `Pomelo Care (Dev)`. However, the environment variable is set in the `Set up build environment` step, and the generated app config clearly shows this.

This seems to point to the `Install pods` step incorrectly reading the app config and/or incorrectly reading environment variables.

### What platform(s) does this occur on?

iOS

### SDK Version

49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.volta/tools/image/node/16.17.0/bin/node
      npm: 8.15.0 - ~/.volta/tools/image/npm/8.15.0/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 34.0.0
        System Images: android-29 | ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.5.2 => 0.5.2
      babel-preset-expo: 9.3.0 => 9.3.0
      expo: 49.0.9 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 2.2.0
      expo-cli: 6.0.6
    Expo Workflow: managed

### Minimal reproducible example

eas build --platform ios

**Comment by brentvatne** [comment]
do you commit any `.env` files to your source control? i suspect that is what is happening here, and one of those is being loaded when you run prebuild. you can ignore those with **.easignore** or exclude them from git with **.gitignore**. https://expo.fyi/eas-build-archive

currently the "Read app config" step does not factor in any **.env** configuration, we'll deploy a fix for that soon

**Comment by tomrom-pomelo** [comment]
yep we have a .env file - adding it to .easignore should solve our problem - thank you.

**Comment by brentvatne** [comment]
> currently the "Read app config" step does not factor in any **.env** configuration, we'll deploy a fix for that soon

this is now fixed
