### ISSUE TITLE
Cannot navigate to index file of a Stack nested inside a Tab

### ISSUE THREAD

**Issue by lsps9150414** [expo/expo#24368]
### Minimal reproducible example

https://github.com/lsps9150414/expo-router-nest-index-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

![Simulator Screenshot - iPhone 13 Pro Max - 2023-09-11 at 18 32 26](https://github.com/expo/expo/assets/5022617/da304cd3-a244-47a1-8a7d-ce546dd724fc)

![Screenshot 2023-09-11 at 6 26 08 PM](https://github.com/expo/expo/assets/5022617/74070a1a-6286-4d38-b40b-c97702be3693)

- Navigating to the `/(rootTabs)/account/` route lands in the `/index.tsx` file instead of the `/(rootTabs)/account/index.tsx` file after tab is switched.

- If the tab has never been switched. the navigating works as expected.
- If I rename `/(rootTabs)/account/index.tsx` to something else, then everything works as expected but I want the route to be `/account` instead of `/account/something`

## Steps to reproduce
1. Go to the Account tab
2. Come back to this Home tab
3. Go to the Account tab again => BROKEN!,  results in the start page instead of the Account tab

### Environment

System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.9 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed

**Comment by marklawlor** [comment]
The issue in your MVP is fixed in `2.0.8`, can you please upgrade and test. If your still encountering the issue, just update your MVP and we can reopen the issue.
