### ISSUE TITLE
[expo-image-picker] Android ignores selectionLimit prop in launchImageLibraryAsync

### ISSUE THREAD

**Issue by elias96** [expo/expo#24367]
### Minimal reproducible example

https://snack.expo.dev/@elias96/expo-image-picker-ignores-selectionlimit

### Summary

The image picker in android ignores the selectionLimit property, however it works fine on iPhone.

Im using Samsung Galaxy S20 to test this. I've made a snack that demonstrates this.

https://snack.expo.dev/@elias96/expo-image-picker-ignores-selectionlimit

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 31, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.11 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.13.0
    Expo Workflow: bare
```

**Comment by alanjhughes** [comment]
Hi @elias96 - What version of Android are you testing on? The selection limit is not supported below android 11.

**Comment by elias96** [comment]
> Hi @elias96 - What version of Android are you testing on? The selection limit is not supported below android 11.

The phone i'm testing on has version 12.

**Comment by alanjhughes** [comment]
Are you testing in expo go?

**Comment by elias96** [comment]
The project im working on is using a development build, and i can re-create the issue it there aswell as in expo go.

**Comment by alanjhughes** [comment]
There was an update to expo go last week, have you installed it? Without it the issue will still exist in go.

**Comment by alanjhughes** [comment]
I'll investigate some more but so far have not been able to reproduce. I'm getting an crash when I try to open your snack.

**Comment by elias96** [comment]
> There was an update to expo go this week, have you installed it? Without it the issue will still exist in go.

I'll try again with the new update.

**Comment by BrodaNoel** [comment]
As I mentioned in https://github.com/expo/expo/issues/24526, this is still broken

**Comment by elias96** [comment]
> As I mentioned in #24526, this is still broken

Yeah i can also reproduce this. Expo 48 & Expo 49.

**Comment by alanjhughes** [comment]
Snack doesn't have google plays apis to use this feature so it falls back to older behaviour that ignores the selection limit. This is also true on devices without support of the backported picker. Can someone provide a repo with an example of it not working?

**Comment by alanjhughes** [comment]
Worth noting, SDK 48 did not contain the new picker.

**Comment by bzozoo** [comment]
Try this

`launchImageLibrary({
    selectionLimit: 0
  }, response => {
     
  }
)`
