### ISSUE TITLE
Provisioning Profiles and secure store access along time

### ISSUE THREAD

**Issue by dhcmega** [expo/expo#24377]
Hi @Eyesonly88, there is no native iOS hook provided to run any code or perform any actions when the user uninstalls an app (with or without Expo). I believe the iOS keychain uses the provisioning profile that was used to install the app in order to retrieve secrets; if you reinstall the app with the same provisioning, the keychain will be the same. Further, since Apple syncs data in iCloud, they don't automatically clear data when the app is removed from a single device. So as mentioned in the previous comment, we're just using the system behavior that applies to all iOS apps here.

_Originally posted by @terribleben in https://github.com/expo/expo/issues/1436#issuecomment-394867639_

Hi, according to documentation, the provisioning profile expires after 12 month. So the secure store will became unavailable?

`
Provisioning Profiles
Each profile is app-specific, meaning you will have a provisioning profile for every app you submit to the App Store. These provisioning profiles are associated with your distribution certificate, so if that is revoked or expired, you'll need to regenerate the app's provisioning profile, as well. Similar to the distribution certificate, revoking your app's provisioning profile will not have any effect on apps already on the App Store.

Provisioning profiles expire after 12 months, but this won't affect apps in production. You will just need to create a new one the next time you build your app by running eas build -p ios, or manually with eas credentials.
`

**Comment by brentvatne** [comment]
this will not impact secure store: https://stackoverflow.com/a/13315432/659988
