### ISSUE TITLE
EAS CLI local build is missing json files

### ISSUE THREAD

**Issue by hukpo** [expo/expo#24384]
### Summary

Realm library has a json config file in project root.
When I build in expo cloud it works fine, but locally it fails.
I was able to track it down using EAS_LOCAL_BUILD_SKIP_CLEANUP=1 and checking the build folder node_modules and I can see no json file with realm config although it exists in my project root node_modules directory

Build command:
`EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build --profile preview --platform ios --local --clear-cache`

Root node_modules
<img width="365" alt="image" src="https://github.com/expo/expo/assets/40897161/129a851e-bff5-4e8d-ab2d-520a669bff92">

Build folder node_modules
<img width="358" alt="image" src="https://github.com/expo/expo/assets/40897161/e63274e5-4d54-4b1c-9bdf-da48ea5ac6dc">

### What platform(s) does this occur on?

Android, iOS

### SDK Version

49.0.10

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/pavlohuk/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: bare
```

### Minimal reproducible example

https://github.com/hukpo/realm-json-bug

**Comment by brentvatne** [comment]
hi there! my guess is that this json file is generated when you run something in realm. this is not specific to eas build, i'd suggest opening an issue on the realm repository

**Comment by brentvatne** [comment]
I see, it looks like realm actually generates this file in a postinstall analytics script: https://github.com/realm/realm-js/blob/ca1d2b96012ceb5d3236d6b6b278bbf47c6d69e3/packages/realm/scripts/submit-analytics.mjs#L150-L159

so this is somehow not working properly in this context, which likely seems to be a problem with the script on realm's end.

**Comment by hukpo** [comment]
> I see, it looks like realm actually generates this file in a postinstall analytics script: https://github.com/realm/realm-js/blob/ca1d2b96012ceb5d3236d6b6b278bbf47c6d69e3/packages/realm/scripts/submit-analytics.mjs#L150-L159
> 
> 
> 
> so this is somehow not working properly in this context, which likely seems to be a problem with the script on realm's end.

Interesting, but it works in EAS cloud somewhy

**Comment by brentvatne** [comment]
is it shipped in the library? it seems to be generated during the postinstall

**Comment by hukpo** [comment]
Yeah, sorry, you're right. I've downloaded their archive directly from npm and there is no json file.
I'm going to close this issue until I find why it's not there
