### ISSUE TITLE
expo [v49] starts slow and quits slow, and after resuming from the sleep, every response takes like 30secs to be received

### ISSUE THREAD

**Issue by Albert-Gao** [expo/expo#24387]
### Minimal reproducible example

private repo

## When I start the app, it takes more than several minutes to pass the stage:
![image](https://github.com/expo/expo/assets/18282328/79978fa2-077f-42df-adcd-c4a7510e5f94)

## When I quit the CLI (ctrl+c), it stucks at the "Stopping server" step for like 5 minutes
![image](https://github.com/expo/expo/assets/18282328/96ed0340-7215-4357-973e-c62e63dd43f8)

## Running this command costs 10minutes:
`npx expo-env-info`

I think it might be something wrong with my machine. but how to resolve it, please? anyone points out what i am missing here plz?

thanks :)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/albertgao/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.9 => 49.0.9 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.7 => 0.19.8 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: bare

**Comment by brentvatne** [comment]
i would try removing the TAMAGUI_TARGET / disabling the optimizing compiler. i have seen a number issues related to it, eg: builds timing out
