### ISSUE TITLE
EXP Convert Terminal Freeze

### ISSUE THREAD

**Issue by andkhong** [expo/expo#244]
I am trying to use EXP Convert CLI but when I run it inside the directory of an existing RN project, I am prompted to authenticate. 

My terminal gives me the options to choose the authentication but once I select either options (create new account or login with existing), my terminal freezes and I am unable to even cancel out of the prompts.

<img width="572" alt="screen shot 2017-06-09 at 10 03 03 am" src="https://user-images.githubusercontent.com/10818651/26986071-de90cdf6-4cfa-11e7-8333-889d697df32e.png">

**Comment by ide** [comment]
What OS and version of Node are you using?

**Comment by andkhong** [comment]
Mac OS Sierra

Node v 8.1.0

**Comment by ide** [comment]
Since you're using Node 8 you probably are also using npm 5, which we've found especially buggy. Could you try uninstalling "exp", installing Yarn or npm 4, and then reinstalling exp with one of those?

**Comment by andkhong** [comment]
I uninstall exp and and yarn global added it back; It's still the same issues for me :(

**Comment by ide** [comment]
Hmm let's try to simplify and reduce the number of possible causes. Try:

- Restarting your computer
- Making sure you have enough disk space (if you have only a couple MB left, your computer will have problems)
- Try using Node 7, which we've tested with. And npm 4 or Yarn.
- Using the built-in Terminal.app
- Use bash

Then if that works you can add back each complication one at a time.

**Comment by andkhong** [comment]
It doesn't work with Node v8.0.0 - v8.1.0

But it does work with v8.1.2!
