### ISSUE TITLE
Metro error: (0 , _expoModulesCore.uuidv4) is not a function

### ISSUE THREAD

**Issue by Savinvadim1312** [expo/expo#24409]
### Minimal reproducible example

npx create-expo-app@latest Test -t tabs

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Running the tabs template on the web throws:

```
Metro error: (0 , _expoModulesCore.uuidv4) is not a function

  2 | import { ExecutionEnvironment, } from './Constants.types';
  3 | const ID_KEY = 'EXPO_CONSTANTS_INSTALLATION_ID';
> 4 | const _sessionId = uuidv4();
    |                          ^
  5 | function getBrowserName() {
  6 |     if (Platform.isDOMAvailable) {
  7 |         const agent = navigator.userAgent.toLowerCase();

Call Stack
  <global> (node_modules/expo-constants/build/ExponentConstants.web.js:4:26)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:342:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:240:12)
  metroRequire (node_modules/metro-runtime/src/polyfills/require.js:127:7)
  <global> (node_modules/expo-constants/build/Constants.js:4)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:342:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:240:12)
  metroRequire (node_modules/metro-runtime/src/polyfills/require.js:127:7)
  <global> (node_modules/expo-router/src/link/linking.ts:1)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:342:5)
```

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 3.6.1 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 32.0.0, 33.0.0, 33.0.1
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.10 => 49.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed

**Comment by dccarmo** [comment]
I'm seeing the exact same issue. I wonder if it was a recent change that caused it?

**Comment by dccarmo** [comment]
@Savinvadim1312 we fixed this by running `npm i expo-modules-core@next`. It seems there's an issue with the latest release of that package (it's under 'next' instead of 'latest')

**Comment by lancej1022** [comment]
Im experiencing the same issue in a brand new Expo project so thank you for the temporary workaround @dccarmo

**Comment by j0j032** [comment]
> @Savinvadim1312 we fixed this by running `npm i expo-modules-core@next`. It seems there's an issue with the latest release of that package (it's under 'next' instead of 'latest')

Thks! fix worked for me ✨

**Comment by ansh** [comment]
I am facing this issue too after upgrading all the packages

**Comment by ansh** [comment]
Running `npx expo install --fix` will fix this issue. There seems to be some mismatch between the expo packages and their versioning.

**Comment by rozsival** [comment]
@ansh In my case, the mismatch was caused by my package manager pulling `expo-linking@6` while it is not compatible with SDK 49.

When I explicitly required `expo-linking@5.0.2` in my `package.json` and reinstalled all modules the issue was gone.

@dccarmo Using `expo-modules-core@1.8` completely broke my app's build, unfortunately. Glad it helped others though.

**Comment by hieucd04** [comment]
I'm experiencing the same issue and none of the workaround here works for me.
For now, I'm stuck at `expo-auth-session@5.0.2` :(

**Comment by Henriquehlr** [comment]
> npm i expo-modules-core@next


for min it didn't work the error is occurring when I use the expo-file-system library

**Comment by jagalsan** [comment]
Same error when use @clerk/clerk-expo

**Comment by jagalsan** [comment]
@janwirth No!, cannot be fixed.  I run the app without expo go. Example execute npm run android or ios. The web execute dont work with expo clerk.
- https://clerk.com/docs/quickstarts/expo
<img width="703" alt="image" src="https://github.com/expo/expo/assets/50619352/070c7eb2-a382-494b-88b1-fb232b113c70">

**Comment by janwirth** [comment]
Thank you for your reply! I just managed to fix it by using `expo install --fix`.

I did NOT need to run `npm run ios`. NO ios folder necessary.
It was enough to run `eas build --platform ios --profile development-simulator --local --clear-cache`
Then install the build on your device (unzip and drop into simulator)
Then you run the expo-dev-server and open the ios build! (not expo-go)

We are using a managed build but NOT expo go.
Perhaps you can try the same? I'm jannibeu on discord if you want to exchange more info.

**Comment by Leslie-Wong-H** [comment]
Fixed by removing the separate `expo-file-system` from package.json. The `expo` package already includes `expo-file-system`. 

![image](https://github.com/expo/expo/assets/27696701/4d407af4-6181-4342-b90d-23ae139c71c9)
https://docs.expo.dev/bare/installing-expo-modules/#expo-modules-included-in-the-expo-package

**Comment by flyaflya** [comment]
> npm i expo-modules-core@next

Vadim:  Thanks for all your videos.  Did you ever solve this particular issue?  None of the solutions above are working for me.

**Comment by rap0so** [comment]
What **worked** for me was:

`npm i expo-modules-core`


(make sure the dependencies are like `"expo-modules-core": "^1.11.7",`...

and ignoring the warning:
![Screenshot 2024-01-20 at 01 02 40](https://github.com/expo/expo/assets/18194524/440431aa-1279-49de-894d-804071b26ce2)

**Comment by StrixSC** [comment]
I'm having the same issue, I feel like it might be a dependency issue.

package.json:


```json
    "dependencies": {
        "@clerk/clerk-expo": "^0.18.12",
        "@expo-google-fonts/inter": "^0.2.3",
        "@gorhom/bottom-sheet": "^4.5.1",
        "@react-native-async-storage/async-storage": "1.18.2",
        "@react-navigation/bottom-tabs": "^6.5.11",
        "@stripe/stripe-react-native": "0.28.0",
        "@supabase/auth-helpers-react": "^0.4.2",
        "@supabase/supabase-js": "^2.39.1",
        "axios": "^1.6.2",
        "envalid": "^8.0.0",
        "expo": "~49.0.15",
        "expo-checkbox": "~2.4.0",
        "expo-constants": "~14.4.2",
        "expo-dev-client": "~2.4.12",
        "expo-font": "~11.4.0",
        "expo-linking": "~5.0.2",
        "expo-secure-store": "12.3.1",
        "expo-router": "^2.0.15",
        "expo-splash-screen": "~0.20.5",
        "expo-status-bar": "~1.6.0",
        "fidel-react-native": "^2.1.1",
        "http-status-codes": "^2.3.0",
        "react": "18.2.0",
        "react-native": "0.72.6",
        "react-native-circular-progress": "^1.3.9",
        "react-native-confirmation-code-field": "^7.3.2",
        "react-native-elements": "^3.4.3",
        "react-native-error-boundary": "^1.2.4",
        "react-native-gesture-handler": "~2.12.0",
        "react-native-reanimated": "~3.3.0",
        "react-native-safe-area-context": "4.6.3",
        "react-native-screens": "~3.22.0",
        "react-native-svg": "13.9.0",
        "react-native-url-polyfill": "^2.0.0",
        "styled-components": "^6.1.8"
    },
    "devDependencies": {
        "@babel/core": "^7.20.0",
        "@types/react": "~18.2.14",
        "typescript": "^5.1.3"
    },
```

The issue happens the moment I include @clerk/clerk-expo's ClerkProvider on the root of the App.tsx:

```html
        <ClerkProvider tokenCache={tokenCache} publishableKey={process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY!}>
            [...]
        </ClerkProvider>
```

Some more info; I use expo prebuild, so I always run the android build and never the expo go build. 

Output of `npx expo-doctor`:

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@7.8.4
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.

One or more checks failed, indicating possible issues with the project.
```

I don't believe the error from expo-doctor is the issue, because I have the same output for expo-doctor when I run it on the clerk-expo start app (https://github.com/clerk/clerk-expo-starter), and yet I don't have any problems on there. Eitherway, I already tried to install @expo/config-plugins@~7.2.2 to see if it would fix the problem. The problem did not get fixed.

I also tried to clear cache, delete node_modules and reinstalling, installing expo-core-modules manually, running `npx expo install --fix` none of that worked.

I really can't understand where the issue is...
