### ISSUE TITLE
[docs] Parallel Installation page is missing

### ISSUE THREAD

**Issue by visto9259** [expo/expo#24404]
### Summary

In the https://docs.expo.dev/develop/development-builds/share-with-your-team/ page, there is a link at the Next Steps section to instructions on how to perform a parallel install of dev and production builds:
The link https://docs.expo.dev/develop/development-builds/parallel-installation/ is not found in the documation site.

### Link to the related docs page

https://docs.expo.dev/develop/development-builds/share-with-your-team/

**Comment by amandeepmittal** [comment]
Hey @visto9259, thanks for reporting this issue and apologies that our docs were not up to date and caused inconvenience. The correct doc link for parallel installation is: https://docs.expo.dev/build-reference/variants/.

We will fix the issue.

**Comment by visto9259** [comment]
@amandeepmittal,
Thanks for the link.  It provided the info I was looking for.
Regards
Eric

**Comment by amandeepmittal** [comment]
We've also fixed the link issue. Thank you!
