### ISSUE TITLE
Error "Cannot read property 'FIELD' of undefined" when use @apollo/client

### ISSUE THREAD

**Issue by lucasdevf** [expo/expo#24408]
### Minimal reproducible example

https://github.com/lucasdevf/expo-apollo-client

### Summary

**The problem:**
When I try to query a graphql API using @apollo/client, my application does not run and displays the error below:
https://cdn.discordapp.com/attachments/695411232856997971/1151206955889737748/IMG_2207.png

**Expected:**
Perform the query in the graphql api and console.log the data

**Versions:**
"@apollo/client": "^3.8.3",
"expo": "~49.0.10",
 "expo-status-bar": "~1.6.0",
"graphql": "^16.8.0",
"react": "18.2.0",
"react-native": "0.72.4"

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04 LTS 22.04 (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    npmPackages:
      expo: ~49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: managed

**Comment by brentvatne** [comment]
hi there! you should open this on the apollo repo!
