### ISSUE TITLE
MediaLibrary : createAssetAsync throws permissions error when supplying URI not generated by Expo.Camera (ExpoKit)

### ISSUE THREAD

**Issue by afenrir** [expo/expo#2441]
Environment:
  OS: macOS 10.14
  Node: 10.10.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Target: iOS 12, ExpoKit

I am trying to create a MediaLibrary asset using a URI generated by RNCamera. However, each time it fails with the following error:

```
Error: File 'file:///var/mobile/Containers/Data/Application/430EC48C-7AA7-4722-954D-077435AB78D7/Library/Caches/Camera/A1F0923C-2AC7-4063-B1B3-3EC87BEF1754.jpg' isn't readable.
```

Sample code that will produce the error:

```javascript
'use strict';
import React, { Component } from 'react';
import { Button } from 'react-native';
import { RNCamera } from 'react-native-camera';

import { MediaLibrary, Permissions } from 'expo';

class CameraScreen extends Component {
    componentDidMount() {
        Permissions.askAsync(Permissions.CAMERA, Permissions.CAMERA_ROLL);
    }

    takePicture = async () => {
        if (this.camera) {
            const { uri } = await this.camera.takePictureAsync();
            const asset = await MediaLibrary.createAssetAsync(uri);
            console.log(asset);
        }
    };

    render() {
        return (
            <RNCamera
                ref={ref => (this.camera = ref)}
                style={{ flex: 1, justifyContent: 'center' }}
            >
                <Button onPress={this.takePicture} title="Take Photo" />
            </RNCamera>
        );
    }
}

export default CameraScreen;
```

This seems to be a problem with how MediaLibrary evaluates permissions associated with a local image URI generated by something other than Expo.Camera. This is the MediaLibrary source code that appears to cause the problem:

```swift
if (!([_fileSystem permissionsForURI:assetUrl] & EXFileSystemPermissionRead)) {
    reject(@"E_FILESYSTEM_PERMISSIONS", [NSString stringWithFormat:@"File '%@' isn't readable.", assetUrl], nil);
    return;
  }
```

https://github.com/expo/expo/blob/master/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L102

I know that this is a problem with MediaLibrary rather than an actual permissions issue for two reasons: 

1. I can manipulate that file using other libraries and I am able to render the URI in an image element.
2. Commenting out that if statement in the source code fixes the problem - MediaLibrary will successfully create a media asset.

Furthermore, the bug does not occur when using Expo.Camera.

**Comment by Pitchlab** [comment]
I have the exact same issue. Is there a workaround I can try while awaiting a fix?

**Comment by AlexCarrithers** [comment]
The only convenient way around it i could find was to edit the source code in node_modules, which is obviously problematic for a number of reasons and I really wouldn't encourage it. 

My ultimate solution was to go and learn Swift so I could write my application in native code. I realise that probably isn't very helpful, but I kept bumping up against this same type of problem again and again (not just with Expo).

**Comment by Pitchlab** [comment]
I have attempted to work around it by using the FileSystem. 

```
const image = Asset.fromModule(require('../assets/images/splash.png')); // images['blank-canvas']);
await image.downloadAsync();            
console.log(image);
await MediaLibrary.createAssetAsync(image.localUri);
```
creates the asset correctly, and it is saved to the medialibrary. But that was again an asset that was generated by Expo. 

Trying to read that same localUri with FileSystem fails (slightly different error, same situation):

```
const fileString = await FileSystem.readAsStringAsync(image.localUri)
```

So the problem seems to be accessing localUri paths.

**Comment by Pitchlab** [comment]
Workaround: use react-native's CameraRoll: 
```
CameraRoll.saveToCameraRoll(uri);
```

**Comment by AlexCarrithers** [comment]
Sorry, yes. I had assumed you did not want to use the CameraRoll. I switched away from that as when I tried it there were problems with it saving incorrect orientations when shooting in landscape. Pairing RNCamera with Expo MediaLibrary was already a workaround for me.

**Comment by tsapeta** [comment]
Hey everyone here!
I'm sorry I've missed this issue somehow 😅 If I remember correctly we've fixed that in the filesystem module, so this permission check will be returning `true` in ejected apps. 
Sorry for the inconvenience you're having! Fix for this will land in the upcoming release 😉 I'll close this issue once I confirm the fix works in this case.

**Comment by Pitchlab** [comment]
Would be great as I really would like to create albums :) Thanks!

**Comment by emreozdincer** [comment]
@Pitchlab did you find a work-around until the patch?

I need to use MediaLibrary because it enables album based saves, and it works perfectly on Android.

**Comment by tsapeta** [comment]
Can someone confirm if this issue is still valid in SDK 32?

**Comment by serhiipalash** [comment]
Hi @tsapeta! 
This works for us in Expo v32 in our production without any concerns 
```
const { uri } = await this.camera.takePictureAsync();
const asset = await MediaLibrary.createAssetAsync(uri);
```

But there is one similar to this thread original issue with [`Expo.takeSnapshotAsync`](https://docs.expo.io/versions/latest/sdk/take-snapshot-async/) util. After Expo updated `react-native-view-shot` library a few month ago, on iOS `Expo.takeSnapshotAsync` returns local uri without `file://` protocol, something like this `/private/var/mobile/Containers/Data/Application/...` and this doesn't work
```
try {
  const localUri = await takeSnapshotAsync(this._content, {
    format: 'png',
    result: 'tmpfile',
    quality: 1.0,
  })

  await MediaLibrary.createAssetAsync(localUri)

  console.log('Success!')
} catch(err) {
  console.log(err) // Error: File '/private/var/mobile/Containers/Data/Application/' isn't readable.
}
```

Luckily, we found a workaround for this bug
```
try {
  let localUri = await takeSnapshotAsync(this._content, {
    format: 'png',
    result: 'tmpfile',
    quality: 1.0,
  })

  if (uri.startsWith('/')) {
    localUri = 'file://' + uri
  }

  await MediaLibrary.createAssetAsync(localUri)

  console.log('Success!')
} catch(err) {
  console.log(err)
}
```

**Comment by tsapeta** [comment]
Closing this issue as it has been fixed in SDK32.
@serhiipalash I'll open a separate issue for the problem you described in the comment above 🙂
