### ISSUE TITLE
Android expo-image-picker content:// url bug with example

### ISSUE THREAD

**Issue by jsheffers** [expo/expo#24413]
### Minimal reproducible example

https://github.com/jsheffers/expo-image-picker-bug

### Summary

The bug here is related to this [previous issue](https://github.com/expo/expo/issues/24172), which was locked by the maintainers. He asked in that issue to create a new issue with a reproducible example, so that is what I'm attempting to do here.  All of the context needed is in that issue, but I will provide a brief description.

This looks like an incompatibility between expo-image-picker and expo-media-library.  If I take the permissions request out of the picture, expo-image-picker works just fine.  If I use expo-media-library's usePermissions() hook (choosing allow to all) expo-image-picker starts trying to get the URI from `content://` and not `file://`.  Hopefully this repository will show a perfect example of this.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/Library/Caches/fnm_multishells/15284_1694527818099/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/Library/Caches/fnm_multishells/15284_1694527818099/bin/npm
      Watchman: 2023.04.17.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/shane/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0/15A5219j - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.10 => 49.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed

**Comment by jsheffers** [comment]
I built the app locally and with eas.  Same issue.

**Comment by alanjhughes** [comment]
Hi @jsheffers  I've pulled a run your repro and it runs without issue. What device are you testing this on?

**Comment by alanjhughes** [comment]
Steps I follwed

1. Pull the repo
2. Run `yarn`
3. Run `npx expo run:android`

I can pick images without issue and the permissions logged are correct

**Comment by jsheffers** [comment]
Pixel_4_API_33

**Comment by ushu** [comment]
Hello all, here is a *very crude patch* (I am no Kotlin coder...) that kinda does the job for me:

```diff
diff --git a/node_modules/expo-image-loader/android/src/main/java/expo/modules/imageloader/ImageLoaderModule.kt b/node_modules/expo-image-loader/android/src/main/java/expo/modules/imageloader/ImageLoaderModule.kt
index 681341f..d30c014 100644
--- a/node_modules/expo-image-loader/android/src/main/java/expo/modules/imageloader/ImageLoaderModule.kt
+++ b/node_modules/expo-image-loader/android/src/main/java/expo/modules/imageloader/ImageLoaderModule.kt
@@ -3,6 +3,8 @@ package expo.modules.imageloader
 import android.content.Context
 import android.graphics.Bitmap
 import android.graphics.drawable.Drawable
+import android.net.Uri
+import android.provider.ContactsContract
 import com.bumptech.glide.Glide
 import com.bumptech.glide.load.engine.DiskCacheStrategy
 import com.bumptech.glide.request.target.CustomTarget
@@ -99,6 +101,13 @@ class ImageLoaderModule(val context: Context) : InternalModule, ImageLoaderInter
     var actualUrl = url
     if (url.startsWith("asset:///")) {
       actualUrl = "file:///android_asset/" + url.split("/").last()
+    } else if (url.startsWith("content://")) {
+        var cursor = context.contentResolver.query( Uri.parse(url), null, null, null, null)
+        if (cursor != null && cursor.count > 0) {
+            cursor.moveToFirst()
+            actualUrl = "file://" + cursor.getString(1)
+            cursor.close()
+        }
     }
     return actualUrl
   }
```

I use `patch-package` to apply it (saved un `patches/expo-image-loader+4.3.0.patch`) on install.

Basically, the error seemed caused by the `normalizeAssetsUrl` function inside the `ImageLoaderModule`: it converts assets URLs before passing them to the `Glide` library for processing. This patch adds a case for content URIs.

**Comment by jsheffers** [comment]
@alanjhughes Can I give an APK?

**Comment by jsheffers** [comment]
I boiled this down last night and I think I have the culprit.

expo-image-manipulator 11.3.0 is the issue for me.  After tons of testing upgrading to 11.5.0 for that package works for me.  My guess is if you lock my example repo to 11.3.0 (clear all caches) and make 100% sure that's what's getting built locally you'll run into the issue.

**Comment by alanjhughes** [comment]
Yes, that makes sense. Image picker and image manipulator both use image loader which is the root cause and so both need to be updated.
