### ISSUE TITLE
Duplicated `NSUserActivityTypes` expo.index_route on every prebuild

### ISSUE THREAD

**Issue by chef-jojo** [expo/expo#24414]
### Minimal reproducible example

na

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When using prebuild without gitignore ios dir, prebuild will push a new `$(PRODUCT_BUNDLE_IDENTIFIER).expo.index_route` everytime
https://github.com/expo/expo/blob/f8937e91a13e29ecccf2784684b7cd48f6600896/packages/expo-router/plugin/src/index.ts#L15-L18

### Environment

expo-router@2.0.5

**Comment by brentvatne** [comment]
we recommend using `npx expo prebuild --clean` in most cases, because, for a number of reasons, it's usually not safe to apply prebuild on top of an existing dirty project. we'll likely change this to the default behavior for prebuild in sdk 50, and you can opt out of it with a dangerous flag.

**Comment by yigithanyucedag** [comment]
> we recommend using `npx expo prebuild --clean` in most cases, because, for a number of reasons, it's usually not safe to apply prebuild on top of an existing dirty project. we'll likely change this to the default behavior for prebuild in sdk 50, and you can opt out of it with a dangerous flag.

The problem persists. My project is a fresh project created with an expo, so it is not dirty. This problem needs to be fixed. Using the --clean option every time is not a sensible suggestion.

**Comment by sergeichestakov** [comment]
FYI looks like this has been fixed in https://github.com/expo/expo/pull/25114, just needs to be published in the next `expo-router` release
