### ISSUE TITLE
[expo-av] opacity behaves differently on iOS vs Android

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#24420]
### Minimal reproducible example

https://github.com/RRaideRR/expo-video-opacity

### Summary

If a video becomes transparent on Android (or the parent view of the video), it will always look dark and black - no matter what the background color is. On iOS it works as expected.

https://github.com/expo/expo/assets/3411292/345d2f4b-c147-4015-b0d6-3e69c823daf4

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by RRaideRR** [comment]
ah sorry - haven't searched good enough. this is a duplicate of #24091

**Comment by alperpacin** [comment]
Hey @RRaideRR, did you find any workaound for that?
