### ISSUE TITLE
Expo Router installation template crashes on web

### ISSUE THREAD

**Issue by Frallan1** [expo/expo#24433]
### Minimal reproducible example

npx create-expo-app@latest --template tabs@49; npm run web crashes

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

following Expo Router installation guide (https://docs.expo.dev/routing/installation/)
the follow stacktrace is thrown after 'npm run web'

![image](https://github.com/expo/expo/assets/52696468/f9a4e9db-c437-49af-8bee-7c98907eb738)

### Environment

System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.17.0 
      npm: 8.15.0 
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    Expo Workflow: managed

**Comment by brentvatne** [comment]
thank you for the report! this was due to npm peer dependency auto-installation behavior, a new alpha version of expo-constants, and a peer dependency in the expo-head library being a bit too unconstrained. this is now resolved
