### ISSUE TITLE
Expo Barcode Scanner Fails to Decode QR Codes with vCard Data on Android

### ISSUE THREAD

**Issue by habrahamyanmabbly** [expo/expo#24444]
### Minimal reproducible example

https://snack.expo.dev/@hrant.mabbly/vcard-android-does-not-work

### Summary

The Expo Barcode Scanner, a critical component for many mobile applications, is experiencing issues on **Android** when attempting to decode QR codes that contain vCard data. This problem arises when users try to scan QR codes generated with vCard information attached. 

Two Snacks which could be used to do the test
Link: [QR code with VCard data ](https://snack.expo.dev/@hrant.mabbly/vcard-android-does-not-work)
Link:  [Expo Barcode Scanner (USE ANDROID)](https://snack.expo.dev/@hrant.mabbly/barcode-scanner?platform=android) 

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/mabbly/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 3.4.1
    Expo Workflow: managed
```

**Comment by habrahamyanmabbly** [comment]
I have replied in the github issue with video and code example

**Comment by habrahamyanmabbly** [comment]
@alanjhughes [Video URL](https://www.loom.com/share/1a6dda612b5849e1bb5d87add8d3894f?sid=2e8ff6b5-4b2a-4bfd-8488-51a6f588a27d)



```
export const useVCard = () => {
	const { user, profile } = useMe();

	return useMemo(() => {
		const createVCardString = () => {
			const vCardString = [];

			vCardString.push(`BEGIN:VCARD`);
			vCardString.push(`VERSION:3.0`);
			vCardString.push(`FN:${user.firstName} ${user.lastName}`);
			vCardString.push(`UID:${profile.id}`);
			vCardString.push(`URL:${associatedDomains}/profiles/${profile.id}`);

			profile.phones.forEach((item) => {
				if (item.visibleToAll) {
					vCardString.push(`TEL;TYPE=${item.type}:${item.tel}`);
				}
			});

			profile.emails.forEach((item) => {
				if (item.visibleToAll) {
					vCardString.push(`EMAIL;TYPE=${item.type}:${item.email}`);
				}
			});

			vCardString.push(`END:VCARD`);

			return vCardString.join('\n');
		};

		return createVCardString();
	}, [user, profile]);
};
```

### vcard's data is 

```
 BEGIN:VCARD
VERSION:3.0
FN:T21C Chair2
UID:6d156605-4e6c-ae27-c113f35036b4
URL:https://dev.connect.tiger21.com/profiles/6d156605-4e6c-ae27-c113f35036b4
TEL;TYPE=mobile:+1123457897
END:VCARD
```
### QR is rendered via [react-native-qrcode-svg](https://www.npmjs.com/package/react-native-qrcode-svg)

```
const AccountQRCode = () => {
	const vcard = useVCard();
	return <QRCode size={125} value={vcard} />;
};
```

### Qr is scanned with this function


#### iOS returns correct data with all fields in it, Android returns only the First Name in the vcard data
```

	const handleBarCodeScanned = ({ type, data }: BarCodeEvent) => {
	console.log(data,`: qr data for ${Platform.OS}`)
		const uidPattern = /UID:([\w-]+)/;
		const uidMatch = data.match(uidPattern);
		if (uidMatch) {
			Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
			const extractedValue = uidMatch[1];
			setQRValid(true);
			setScannedProfileId(extractedValue);
		}
	};
```

**Comment by habrahamyanmabbly** [comment]
@alanjhughes I have tested your [Merge Request](https://github.com/expo/expo/pull/24791/files). I thought it might be the solution to the issue, but it still is reproducible. FYI version is : `"expo-barcode-scanner": "~12.5.3"`

* I have copied your code to the corresponding file `MLKitBarCodeScanner`.
* Re-ran the project. 
* 

The response is identical to what it was on Android.

**Comment by alanjhughes** [comment]
Hi @habrahamyanmabbly - could you provide an image of the QR code you are testing with?

**Comment by alanjhughes** [comment]
@habrahamyanmabbly - I recreated your example using `react-native-qrcode-svg` and I got the expected result after the changes in #24791 How are you applying the changes?

**Comment by habrahamyanmabbly** [comment]
@alanjhughes I was not building the native module. I guess that's the reason it did not work.

**Comment by alanjhughes** [comment]
@habrahamyanmabbly no problem. I believe this change will fix your issue

**Comment by habrahamyanmabbly** [comment]
@alanjhughes thank you !

**Comment by therajumandapati** [comment]
@alanjhughes Appreciate your help on this. What is the path to getting a release for this module that includes this fix?

**Comment by habrahamyanmabbly** [comment]
@alanjhughes For your info, I have forked expo made the changes in the package, and pushed it. Eventually, I changed the location of the module to my forked package and tried to scan the QR. 
Is there anything that I miss in those steps?

**Comment by alanjhughes** [comment]
@habrahamyanmabbly - If you were doing that, you would need to fork the entire repository. Just barcode scanner. I'd need details on how you are building the app. Are you running locally through Android studio or creating builds with eas?

**Comment by alanjhughes** [comment]
@habrahamyanmabbly just looking at your video again, are you using expo go?

**Comment by habrahamyanmabbly** [comment]
@alanjhughes I am running locally using expo go. Then I am using a real Android device to scan the QR.

**Comment by habrahamyanmabbly** [comment]
@alanjhughes I have forked the whole expo repo. 
The file that I did the changes on: [expo-barcode-scanner](https://github.com/habrahamyanmabbly/expo/blob/main/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/MLKitBarCodeScanner.kt)

**Comment by alanjhughes** [comment]
@habrahamyanmabbly expo go won't have these changes and unless you are building it from source, you cannot change it yourself. You need to build a dev client if you want to modify the code. The native code in expo go is the same regardless of what dependency you specify.

**Comment by habrahamyanmabbly** [comment]
@alanjhughes okay, thanks !

**Comment by therajumandapati** [comment]
@alanjhughes Just to clarify: will these changes only be included in the next Expo SDK release? Or is there another way we can get these changes into our EAS builds?

**Comment by alanjhughes** [comment]
@therajumandapati generally yes but we may publish sooner. I'll ask and get back to you

**Comment by therajumandapati** [comment]
Thank you @alanjhughes 🙏🏽
