### ISSUE TITLE
Firebase Device Tokens from expo-notifications invalid

### ISSUE THREAD

**Issue by darnfish** [expo/expo#24443]
### Minimal reproducible example

Create new project, add android.googleServicesFile to config, use expo-notifications to call getDevicePushTokenAsync, send notification, encounter error

### Summary

After migrating from Expo Bare to Expo Managed, removing the `ios/` and `android/` folders and moving to using config plugins, push notifications via FCM on Android have stopped working for users

When trying to send a push notification to a token, I get the following error from FCM: `The registration token is not a valid FCM registration token`

The token is not being encoded on our end in any way. Any investigation here would be appreciated as we're on the $99/y Production plan and are encountering a user-impacting issue that we just can't seem to solve, and after talking to other members of the community seems to be not just on our end (I hope not)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 3.6.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.6.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.8.1 - /opt/homebrew/bin/npm
      Watchman: 2022.02.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/darnfish/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0/15A5229m - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.8
    Expo Workflow: managed\

**Comment by cpvdeveloper** [comment]
@darnfish did you ever figure this out? I am currently experiencing the same issue
