### ISSUE TITLE
Facebook API Analytics not working properly for Android

### ISSUE THREAD

**Issue by AdamJNavarro** [expo/expo#2444]
Relevant Forum post with multiple reporters experiencing the same behavior: https://forums.expo.io/t/facebook-login-and-facebook-analytics/14373

**Comment by heyaj19** [comment]
@AdamJNavarro will this fix the issue of logging in events on facebook? I have been trying to do that and can't get to log events.

**Comment by DonGabo** [comment]
Any leads on a way to fix this? I have some free time, but have no idea on how to procede.

**Comment by brentvatne** [comment]
@DonGabo - the source for this is in https://github.com/expo/expo/tree/master/packages/expo-facebook - you can install that in a bare project and test it there and modify as needed while referring to the fbsdk docs

**Comment by cruzach** [comment]
@heyaj19 & @DonGabo are either of you still seeing this issue?
