### ISSUE TITLE
[expo-camera] useCamera2Api crash on some android devices

### ISSUE THREAD

**Issue by Filippo39** [expo/expo#24459]
### Minimal reproducible example

```
    <Camera
      style={{
        width: Dimensions.get('screen').width,
        height: Dimensions.get('window').height,
      }}
      type={CameraType.back}
      useCamera2Api={true}
    />
```

[Minimal reproducible repo](https://github.com/Filippo39/expoCameraFix)

### Summary

There are models of Android devices in which the crash described in the photo occurs when the camera is opened with the `useCamera2Api` flag set to true.
![Screenshot_2023-09-15-12-03-33-336_com expocamerafix](https://github.com/expo/expo/assets/33987920/ba809a09-6644-4367-a1ff-153ab13722c3)
![2023-09-15_17-06](https://github.com/expo/expo/assets/33987920/cec05ad3-c3d8-44a0-b852-452300f611b8)

The models affected by this crash are as follows:
- Redmi Note 9 Pro
- Poco X3 NFC
- Poco F2 Pro
- Redmi Note 12
- Mi 10T
- Redmi 10 5G
- Redmi Note 11
- Xiaomi 11 Lite 5G NE
- Mi 11 Lite
- Poco F5
- Mi 11 Lite 5G
- Moto G42
- Moto G32
- Motorola Edge 30 Neo
- Moto G52
- A78 5G
- Oppo Reno7 5G/Find X5 Lite
- HCT Mobile - FIH Foxconn
- BV4900Pro

Is there a way to know if a device fully supports camera2 or not? If so, could this control be introduced into the library?

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 EndeavourOS
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 34.0.0
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ^49.0.0 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: bare

**Comment by Filippo39** [comment]
Any update?

**Comment by nonam4** [comment]
+1

**Comment by chj-damon** [comment]
+1
