### ISSUE TITLE
Build failed - "main.jsbundle does not exist" error when building iOS version with Expo SDK 49

### ISSUE THREAD

**Issue by tej-thambi** [expo/expo#24454]
### Summary

Build failing with Expo and React Native, there was a similar issue with the same title under SDK 48, but nothing from that has helped. Getting the following problem when doing eas build -p ios

❌  error: File /Users/expo/Library/Developer/Xcode/DerivedData/freeapp-celtkelekabrvocesclaslgcuhcp/Build/Intermediates.noindex/ArchiveIntermediates/freeapp/BuildProductsPath/Release-iphoneos/freeapp.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

It comes up during Run fastlane. My project does not have ios/ or android/ directories, or an index.js or metro config. I just used expo to start up the project in js.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Environment

npx: installed 2 in 2.036s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.2/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
      Watchman: 2023.01.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo

https://github.com/expo/expo/issues/21542

**Comment by brentvatne** [comment]
https://docs.expo.dev/build-reference/troubleshooting/
