### ISSUE TITLE
Pedometer - Already managing a googleapiclient with id 0 react native

### ISSUE THREAD

**Issue by kiwicopple** [expo/expo#2445]
@AdamJNavarro asked me to move [this issue](https://forums.expo.io/t/pedometer-already-managing-a-googleapiclient-with-id-0-react-native-again/14644) onto github, so copy/pasting the details below

------

This is a duplicate of the following two issues (which have been closed so I can't reply):
https://forums.expo.io/t/pedometer-already-managing-a-googleapiclient-error/7639
https://forums.expo.io/t/already-managing-a-googleapiclient-with-id-0-react-native/11199

There isn't much to add to what these issues already point out.

**Steps to replicate**

1. Use an android device
1. Create a Pedometer app using the [documentation](https://docs.expo.io/versions/latest/sdk/pedometer.html) code
1. Start your app via the Expo app on the android device
1. Make a change to your code and save - the app will reload on your phone
1. The error will appear

**Additional info**

* Error code: `Already managing a GoogleApiClient with id 0`
* Only happens on Android phones
* Only happens when using the expo client during development. Works the first time, then when you save the client reloads the app on the phone and the error occurs
* I'm using a Xiaomi Note 5A
* Closing and reopening the app on my phone will solve this (i.e. this is only a development bug, but a frustrating one)

Any pointers to overcome this would be great

**Comment by Szymon20000** [comment]
The bug shouldn't occur in sdk31.

**Comment by tsapeta** [comment]
Hey @kiwicopple, I'm closing this issue as it was fixed in SDK 31. Could you confirm it works now?
