### ISSUE TITLE
Enable full ARM Support for Development

### ISSUE THREAD

**Issue by ebellumat** [expo/expo#24450]
### Minimal reproducible example

Try to use ExpoModulesCore.Swiftmodule with only ARM 64 arch

### Summary

Impossible to run without Rosetta on Xcode 15 RC. 

![image](https://github.com/expo/expo/assets/26942680/3da455f8-8da1-46b2-8917-55c4a77d36e8)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => ^48.0.0
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    Expo Workflow: bare

(base) ebellumat@Erasmos-MacBook-Air customer-app %

**Comment by brentvatne** [comment]
we don't support xcode 15 yet but we will soon!

**Comment by thespacemanatee** [comment]
@brentvatne xcode 15 support is crucial because it supports a lot of new features like the new WidgetKit, lagging behind in xcode support is quite impactful to the development process and preventing us from switching fully to EAS.

**Comment by brentvatne** [comment]
@thespacemanatee - xcode 15 isn't yet supported in react-native core yet. we'll have xcode 15 support likely on monday on eas build. we're revisiting our xcode version strategy and we'll likely start including beta releases in the future under a next tag.
