### ISSUE TITLE
Expo SDK 49 Local builds using EAS not reading values from .env located at the project root

### ISSUE THREAD

**Issue by rranjan14** [expo/expo#24469]
### Minimal reproducible example

Create a new project with SDK 49, and create a `.env` file and build a local build for iOS or Android.

### Summary

I tried building the app binaries in both preview and production environment with a `.env` file located at the root of the project. In both of the environments, it prints in the beginning that no environment variables present for the given environment. I do not have any env variables added in `eas.json`. Attaching my `eas.json` for reference.

```
{
  "build": {
    "production": {
      "android": {
        "buildType": "app-bundle",
        "autoIncrement": true
      },
      "ios": {
        "autoIncrement": true
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "simulator": true
      }
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "autoIncrement": true
      },
      "android": {
        "buildType": "apk",
        "autoIncrement": true
      }
    }
  },
  "submit": {
    "production": {}
  },
  "cli": {
    "version": ">=3.17.0"
  }
}
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 3.6.3 - /opt/homebrew/opt/node@18/bin/yarn
      npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 34.0.0
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed

**Comment by finnmerlett** [comment]
I also have this issue, and can't get any env values into my application even with the eas.json `build > development > env set up exactly the same as my .env file

**Comment by finnmerlett** [comment]
FYI I fixed my issue, turns out I was trying to access the environment variables through a zod validator that was trying to validate the whole `process.env` object. I understand now that env vars are surely subbed in during the build process via a simple find-and-replace (probably a built-in babel plugin), because switching to accessing the env vars directly worked perfectly.

To summarise:
- `env = process.env; env.EXPO_PUBLIC_MY_ENV_VAR` fails
- `process.env.EXPO_PUBLIC_MY_ENV_VAR` succeeds
