### ISSUE TITLE
Task :app:processDebugMainManifest FAILED with EAS Build

### ISSUE THREAD

**Issue by superyarik** [expo/expo#24467]
### Summary

Getting error while building app via EAS Build, have no idea how to fix

```
> Task :app:processDebugMainManifest FAILED

package="EDITED" found in source AndroidManifest.xml: /home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml.

Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.

Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace

This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

> Task :expo-location:parseDebugLocalResources

[stderr] 

/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml:30:13-56 Error:

[stderr] 

	Attribute activity#androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity@theme value=(@style/WhiteBackgroundTheme) from [androidx.test:core:1.5.0] AndroidManifest.xml:30:13-56

[stderr] 

	is also present at [com.github.CanHub:Android-Image-Cropper:4.3.0] AndroidManifest.xml:41:13-49 value=(@android:style/Theme).

[stderr] 

	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:27:9-34:20 to override.

[stderr] 

/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml:38:13-56 Error:

[stderr] 

	Attribute activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity@theme value=(@style/WhiteBackgroundTheme) from [androidx.test:core:1.5.0] AndroidManifest.xml:38:13-56

[stderr] 

	is also present at [com.github.CanHub:Android-Image-Cropper:4.3.0] AndroidManifest.xml:49:13-49 value=(@android:style/Theme).

[stderr] 

	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:35:9-42:20 to override.

[stderr] 

/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml:46:13-62 Error:

[stderr] 

	Attribute activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity@theme value=(@style/WhiteBackgroundDialogTheme) from [androidx.test:core:1.5.0] AndroidManifest.xml:46:13-62

[stderr] 

	is also present at [com.github.CanHub:Android-Image-Cropper:4.3.0] AndroidManifest.xml:57:13-56 value=(@android:style/Theme.Dialog).

[stderr] 

	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:43:9-50:20 to override.

> Task :expo-linear-gradient:generateDebugRFile

> Task :expo-location:generateDebugRFile

> Task :amplitude_analytics-react-native:compileDebugKotlin

w: /home/expo/workingdir/build/node_modules/@amplitude/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt: (66, 46): 'getPackageInfo(String, Int): PackageInfo!' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/@amplitude/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt: (118, 30): 'toUpperCase(Locale): String' is deprecated. Use uppercase() instead.

w: /home/expo/workingdir/build/node_modules/@amplitude/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt: (138, 32): 'locale: Locale!' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/@amplitude/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt: (212, 13): Condition 'limitAdTrackingEnabled != null' is always 'true'

w: /home/expo/workingdir/build/node_modules/@amplitude/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt: (240, 16): Condition 'status != null' is always 'true'

w: /home/expo/workingdir/build/node_modules/@amplitude/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidLogger.kt: (6, 22): Parameter 'i' is never used

[stderr] 

FAILURE: Build completed with 2 failures.

[stderr] 

1: Task failed with an exception.

[stderr] 

-----------

[stderr] 

* What went wrong:

[stderr] 

Execution failed for task ':app:processDebugMainManifest'.

[stderr] 

> Manifest merger failed with multiple errors, see logs

[stderr] 

* Try:

[stderr] 

> Run with --stacktrace option to get the stack trace.

[stderr] 

> Run with --info or --debug option to get more log output.

[stderr] 

> Run with --scan to get full insights.

[stderr] 

==============================================================================

[stderr] 

2: Task failed with an exception.

[stderr] 

-----------

[stderr] 

* What went wrong:

[stderr] 

java.lang.StackOverflowError (no error message)

[stderr] 

* Try:

[stderr] 

> Run with --stacktrace option to get the stack trace.

[stderr] 

> Run with --info or --debug option to get more log output.

[stderr] 

> Run with --scan to get full insights.

[stderr] 

==============================================================================

[stderr] 

* Get more help at https://help.gradle.org

[stderr] 

BUILD FAILED in 4m 53s
```

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.9
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 14.21.3 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.18 - /usr/local/opt/node@14/bin/npm
      Watchman: 2023.04.10.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 28, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2
        System Images: android-32 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.2 
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-navigation: github:superyarik/react-navigation#react-navigation-v4.4.4-gitpkg => 4.4.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

installed packages

"devDependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@types/lodash": "^4.14.176",
    "@types/react": "~18.0.27",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.1.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-preset-expo": "^9.3.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-native": "^4.0.0",
    "flux-standard-action": "^2.1.1",
    "jest-expo": "^48.0.0",
    "less": "^3.11.1",
    "metro-react-native-babel-transformer": "^0.73.9",
    "prettier": "^2.0.4",
    "react-native-less-transformer": "1.3.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "16.13.1",
    "typescript": "^4.9.4",
    "@babel/core": "^7.20.0"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "clean": "watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro*",
    "reset": "watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro* && rm -rf node_modules/ && yarn cache clean && yarn install",
  },
  "dependencies": {
    "@amplitude/analytics-react-native": "^1.4.4",
    "@config-plugins/react-native-branch": "^6.0.0",
    "@pixi/core": "^6.0.0",
    "@pixi/extensions": "^6.0.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-picker/picker": "2.4.8",
    "@redux-offline/redux-offline": "^2.6.0-native.1",
    "@sentry/react-native": "4.15.2",
    "axios": "^0.21.1",
    "bem-react-native": "^1.1.1",
    "circular-json": "^0.5.3",
    "color": "^3.0.0",
    "crypto-js": "^3.1.9-1",
    "deprecated-react-native-prop-types": "^4.2.1",
    "dotenv": "^16.3.1",
    "expo": "~48.0.18",
    "expo-analytics-amplitude": "~11.3.0",
    "expo-application": "~5.1.1",
    "expo-asset": "~8.9.1",
    "expo-av": "~13.2.1",
    "expo-barcode-scanner": "~12.3.2",
    "expo-blur": "~12.2.2",
    "expo-camera": "~13.2.1",
    "expo-clipboard": "~4.1.2",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-device": "~5.2.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-gl": "~12.4.0",
    "expo-image-manipulator": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-intent-launcher": "~10.5.2",
    "expo-keep-awake": "~12.0.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-location": "~15.1.1",
    "expo-media-library": "~15.2.3",
    "expo-notifications": "~0.18.1",
    "expo-permissions": "~14.1.1",
    "expo-pixi": "^2.1.0",
    "expo-screen-orientation": "~5.1.1",
    "expo-sharing": "~11.2.2",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-task-manager": "~11.1.1",
    "expo-updates": "~0.16.4",
    "expo-video-thumbnails": "~7.2.1",
    "expo-web-browser": "~12.1.1",
    "i18next": "^19.4.2",
    "libphonenumber-js": "^1.2.14",
    "lodash": "^4.17.15",
    "lottie-react-native": "5.1.4",
    "moment": "^2.24.0",
    "moment-precise-range-plugin": "^1.3.0",
    "pixi-filters": "3.1.1",
    "prop-types": "^15.7.2",
    "react": "18.2.0",
    "react-devtools": "^4.19.1",
    "react-i18next": "^9.0.10",
    "react-native": "0.71.8",
    "react-native-branch": "^5.4.0",
    "react-native-calendars": "^1.265.0",
    "react-native-collapsible": "^1.5.2",
    "react-native-confirmation-code-field": "^7.3.0",
    "react-native-device-info": "^6.0.1",
    "react-native-easy-toast": "^2.3.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-get-random-values": "~1.8.0",
    "react-native-gifted-chat": "^2.1.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-lightbox": "^0.8.1",
    "react-native-maps": "1.3.2",
    "react-native-offline": "^6.0.0",
    "react-native-open-maps": "^0.3.5",
    "react-native-pell-rich-editor": "^1.8.8",
    "react-native-platform-touchable": "^1.1.1",
    "react-native-popup-menu": "^0.15.7",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-tab-view": "^2.14.0",
    "react-native-view-shot": "3.5.0",
    "react-native-webview": "11.26.0",
    "react-navigation": "github:superyarik/react-navigation#react-navigation-v4.4.4-gitpkg",
    "react-navigation-drawer": "github:superyarik/react-navigation#react-navigation-drawer-v2.7.2-gitpkg",
    "react-navigation-redux-helpers": "4.0.1",
    "react-navigation-stack": "^2.10.4",
    "react-navigation-tabs": "github:superyarik/react-navigation#react-navigation-tabs-v2.11.2-gitpkg",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-form": "^8.3.5",
    "redux-persist": "^4.6.0",
    "redux-persist-expo-fs-storage": "^2.0.0",
    "redux-persist-transform-filter": "0.0.20",
    "redux-saga": "1.0.2",
    "reselect": "^4.0.0",
    "rn-pdf-reader-js": "^4.1.1",
    "sentry-expo": "~6.2.0",
    "urijs": "^1.19.2",
    "uuid": "^8.3.2"
  }

also plugins
"plugins": [
      [
        "expo-updates",
        {
          "username": "EDITED"
        }
      ],
      "sentry-expo",
      [
        "@config-plugins/react-native-branch",
        {
          "apiKey": "EDITED"
        }
      ]
    ],

**Comment by superyarik** [comment]
when i removing deps
"@config-plugins/react-native-branch": "^6.0.0",
"react-native-branch": "^5.4.0",
and react-native-branch with apiKey from app.json config - build is completed successfully.

**Comment by Kudo** [comment]
hi there!

for sdk 48, you probably need react-native-branch@5.7.0 and @config-plugins/react-native-branch@5.0.0 according to https://github.com/expo/config-plugins/tree/main/packages/react-native-branch#versioning

**Comment by farazirfan47** [comment]
Getting the same issue after integrating react-native-branch, I am on SDK 46

**Comment by Kudo** [comment]
hi there! i'd like to close the issue first. will still help to further investigate the problem and reopen it if it's confirmed as an issue. in the meantime, would be great if you could share a minimal reproducible example, that would help for the investigation.

**Comment by 3026546679** [comment]
> when i removing deps "@config-plugins/react-native-branch": "^6.0.0", "react-native-branch": "^5.4.0", and react-native-branch with apiKey from app.json config - build is completed successfully.

How can I get the apiKey?

**Comment by Timothy-Anders0n** [comment]
I needed to remove `react-native-app-auth` rather than `react-native-branch` for my build to succeed.
Thanks for the quick fix!
