### ISSUE TITLE
Not able to require() image using a function call.

### ISSUE THREAD

**Issue by ahmetskilinc** [expo/expo#24476]
### Minimal reproducible example

https://snack.expo.dev/@ahmetskilinc/weather-image

### Summary

I'm trying to load a png image using expo/image, with the require function by calling a function which has a switch statement inside it and it returns the name of the image. i.e. is it is 1000 then it returns sunny.png

However I keep getting errors when trying this, you can see the error in the snack I have linked. App.tsx line 39

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi @ahmetskilinc - That's a limitation of `require()`. Assets must be statically known. You can't use template strings in a `require()` call

**Comment by ahmetskilinc** [comment]
@alanjhughes is there any other way I could achieve what I'm trying to do?

**Comment by alanjhughes** [comment]
You could create an object for your images 
```typescript
const images = {
  someImage: require("some/image.png"),
 // more images
}
```

**Comment by ahmetskilinc** [comment]
Wow okay that worked. I done the following. Thanks for your help @alanjhughes 

```Javascript
export const getWeatherIcon = (weather: number) => {
	const images = {
		sunny: require("../images/sunny.png"),
		cloudy: require("../images/cloudy.png"),
		cloudyRainy: require("../images/cloudy-rainy.png"),
	};

	switch (weather) {
		case 1003:
		case 1006:
		case 1009:
			return images["cloudy"];
		case 1063:
			return images["cloudyRainy"];
		case 1000:
			return images["sunny"];
		default:
			return images["sunny"];
	}
};

<Image source={getWeatherIcon(code)} />
```

**Comment by alanjhughes** [comment]
Great, no problem 👍
