### ISSUE TITLE
[expo-router] Unable to resolve "@expo/metro-runtime" from "node_modules\expo-router\entry.js"

### ISSUE THREAD

**Issue by devoren** [expo/expo#24475]
### Minimal reproducible example

NA

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

`node_modules/expo-router/entry.js`:
```
// `@expo/metro-runtime` MUST be the first import to ensure Fast Refresh works
// on web.
import "@expo/metro-runtime"; <--- unable to resolve in the latest version 2.0.6

// This file should only import and register the root. No components or exports
// should be added here.
import { renderRootComponent } from "expo-router/src/renderRootComponent";

import { App } from "./_app";

renderRootComponent(App);
```
`import "@expo/metro-runtime";` <--- unable to resolve in the latest version 2.0.6
In `2.0.4 version` works fine

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9477386
    npmPackages:
      expo: ~49.0.11 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    Expo Workflow: bare
```

**Comment by devoren** [comment]
@expo-bot please open it again

**Comment by devoren** [comment]
I used npx create-expo-app@latest --template tabs@49 command

**Comment by Brunowilliang** [comment]
Hi @devoren did you solve it? because I have the same error

**Comment by Kraktoos** [comment]
Hey @Brunowilliang have you solved it? I'm also having the same issue here and don't want to create a new project... Thanks.

**Comment by devoren** [comment]
@Brunowilliang Hey! The problem disappears after updating version 2.0.8.
