### ISSUE TITLE
[expo-web] How to add OG meta tags to expo-web app if output is single and bundler is metro?

### ISSUE THREAD

**Issue by devoren** [expo/expo#24473]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by hyochan** [comment]
https://forums.expo.dev/t/expo-web-how-to-add-og-meta-tags-to-expo-web-app-if-output-is-single-and-bundler-is-metro/74195

Any updates? The forums is statle.

**Comment by devoren** [comment]
@hyochan Hey, unfortunately I didn't find a solution :c

**Comment by hyochan** [comment]
@devoren I ended up injecting meta tags in github ci.

```
      - name: Inject Meta Tags
        run: |
          sed -i '/<\/head>/i \
          <meta property="og:image" content="https://app.dooboo.io/dooboo.png" />\n\
          <meta property="og:title" content="dooboo" />\n\
challenge, networking and growth" />\n' ./dist/index.html
```

Hope it helps. I've not had time to dive in `expo` project to see what causes the problem

**Comment by devoren** [comment]
@hyochan Thank you! I will try
