### ISSUE TITLE
How to enhance schedule notification in php api

### ISSUE THREAD

**Issue by stutzenmaha** [expo/expo#24488]
### Minimal reproducible example

How to enhance schedule notification in php api

### Summary

How to enhance schedule notification in php api

### Environment

[expo-server-sdk-php](https://github.com/ctwillie/expo-server-sdk-php)

**Comment by Kudo** [comment]
hi there! it is not clear what you want to enhance for the schedule notification. assuming you want to send a notification every monday, you may probably need a cronjob for php: https://stackoverflow.com/questions/18737407/how-to-create-cron-job-using-php

**Comment by stutzenmaha** [comment]
how to schedule notification in expo via php api
