### ISSUE TITLE
renderRouter breaks typescript compilation

### ISSUE THREAD

**Issue by NiklasEi** [expo/expo#24480]
### Minimal reproducible example

https://github.com/NiklasEi/test-expo-router

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When using `renderRouter` the typescript compiler complains about around 60 issues inside `node_modules/expo-router/src/` that do not show up when not importing `renderRouter`.

You can reproduce this by running `npm i` followed by `tsc` in the reproduction project. When removing `app.integration.spec.ts` the compile errors no longer show up.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    npmPackages:
      expo: 49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    Expo Workflow: managed

**Comment by marklawlor** [comment]
@NiklasEi Your `tsconfig.json` including `**/*.ts`, which is all `.ts` files, including your `node_modules`. This is causing type conflicts, which result in the errors your seeing.

I recommend adjusting your `tsconfig.json` like so, and including `skipLibCheck` which is a recommended setting

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "baseUrl": "./",
    "strict": true,
    "skipLibCheck": true,
    "noUncheckedIndexedAccess": true,
    "types": [
      "jest",
      "node"
    ]
  },
  "include": [
    "./app/**/*.ts",
    "./app/**/*.tsx"
  ]
}
```

**Comment by NiklasEi** [comment]
This change only works, because it removes the spec file from the checked files. This is OK as a workaround, but not a solution, since I want to type check my test files. With
```json
  "include": [
    "./app/**/*.ts",
    "./app/**/*.tsx",
    "app.integration.spec.ts"
  ]
```
the errors are back.


`skipLibCheck` should already be true since we extend `expo/tsconfig.base` which sets it. But I tried setting it again and it did not change anything. As soon a the test with the `renderRouter` import is checked, the compiler will follow the import into the `node_modules` and will find all these issues in there.

**Comment by NiklasEi** [comment]
@marklawlor could you please open this issue again based on my response above?
