### ISSUE TITLE
[android] Calendar.deleteEventAsync deletes all calendar events android

### ISSUE THREAD

**Issue by Nikhil-Curefit** [expo/expo#2449]
### Environment

OS: macOS High Sierra 10.13.6
  Node: 8.9.4
  Yarn: 1.7.0
  npm: 6.4.1
  Watchman: 4.7.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.0 AI-171.4443003

Android

### Steps to Reproduce
***Only on Android***
1. Get Calendar Permission from user
2. Create Calendar
3. Create a daily recurring calendar event "A1" using Expo.Calendar.createEventAsync()
4. Create a daily recurring calendar event "A2" using Expo.Calendar.createEventAsync()
5. Delete calendar event "A1" using Expo.Calendar.deleteEventAsync()

### Expected Behavior
Only event "A1" should be deleted from google calendar
### Actual Behavior
Both events "A1" and "A2" are deleted from the google calendar
(Write what happened. Add screenshots!)

### Reproducible Demo
-->Snack
https://snack.expo.io/@drako999/delete-event

--->
<div data-snack-id="@drako999/delete-event" data-snack-platform="ios" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#fafafa;border:1px solid rgba(0,0,0,.08);border-radius:4px;height:505px;width:100%"></div><script async src="https://snack.expo.io/embed.js"></script>
-->

**Comment by Nikhil-Curefit** [comment]
Hi, can someone acknowledge this and let me know if a fix is planned

**Comment by esamelson** [comment]
Hi, acknowledging we've seen this. We hope to have a fix soon but cannot promise one on any given timeline at this point.

**Comment by RikTheunis** [comment]
Hi @esamelson, any updates on this one?

**Comment by esamelson** [comment]
Sorry, no updates at this time. If you'd like to look into this yourself, we'd love to accept a PR that fixes this issue and adds test coverage! 🙂

**Comment by RikTheunis** [comment]
@esamelson, I would really like to do this, unfortunately I'm currently in my exam period. Maybe I can look into this in a couple of weeks.

**Comment by vivianzzhu91** [comment]
Hi, so the solution for this is to include `isSynced` to be true when you call `Calendar.createCalendarAsync(details)`. In your snack example, you didn't include it, so the calendar might not be synced and the events are not stored on the device even though it's been deleted successfully. Check [`here`](https://developer.android.com/reference/android/provider/CalendarContract.CalendarColumns.html#SYNC_EVENTS) for more information. It's better to always set this value to be true.
