### ISSUE TITLE
HMR Not working for Web in mono repo setup

### ISSUE THREAD

**Issue by claudesortwell** [expo/expo#24508]
### Minimal reproducible example

https://github.com/claudesortwell/expo-49-mono-issue

### Summary

When setting up an expo app in a mono repo set the HMR reload does not update the web page (it shows a reloading popup on web but doesn't actually update the page). 

When updating a expo router page app/(tabs)/index, the page title `<Text style={styles.title}>Tab One</Text>` to `<Text style={styles.title}>Tabww One</Text>` if in a mono repo nothing happens on the web, the text does not update.

Dev server was started with `yarn start --clear`.

In my repo example, ive setup 2 expo starters with Navigation Typescript template. One inside a yarn workspaces and then one at the root of the project (/apps/my-app and /my-app). /my-app works as expected, /apps/my-app is broken.

### Environment

    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.6 => 0.19.8 
    Expo Workflow: managed

**Comment by claudesortwell** [comment]
Seems to be similar to this issue https://github.com/expo/expo/issues/23104

**Comment by marklawlor** [comment]
Closing in favour of https://github.com/expo/expo/issues/23104
