### ISSUE TITLE
[expo-video]

### ISSUE THREAD

**Issue by hamdij0maa** [expo/expo#24509]
### Minimal reproducible example

https://github.com/expo/expo/blob/main/packages/expo-video/src/VideoView.tsx

### Summary

error: Error: Unable to resolve module @unimodules/core from /Users/h0mdi/Desktop/iRevealApp/node_modules/expo-video/node_modules/expo-av/build/ExponentAV.js: @unimodules/core could not be found within the project or in these directories:
  node_modules/expo-video/node_modules
  node_modules
> 1 | import { NativeModulesProxy } from '@unimodules/core';
    |                                     ^
   
   
  

### Environment

RN Bare + expo-modules

**Comment by Kudo** [comment]
hi there! please help to share a repro example based on your problem. `@unimodules/core` had been deprecated for a while. it could be something that you have outdated `expo-av` package. by sharing a repro example, we could really help to investigate your problem. thanks!

**Comment by hamdij0maa** [comment]
I'll retry testing it on a clean rn project.
