### ISSUE TITLE
expo-image in bare react-native project cannot display image on android devices

### ISSUE THREAD

**Issue by chj-damon** [expo/expo#24512]
### Minimal reproducible example

https://github.com/thundersdata-frontend/rn-template

### Summary

I'm using `expo-image` in bare react-native project, it works fine on IOS devices, but it doesn't display any images on android devices, no matter local images or remote images. 

I also tested it in a expo project, it works fine on android devices though. So I think it may be something wrong only when `expo-image` is used in bare react-native project.

there's no error message reported, it's just blank.

you can try to run my project, and navigate to `homepage/pictures/demo1` and `homepage/pictures/demo2` to see the souce code.

can you help with this problem? Thank you very much.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/damon/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: bare

**Comment by chj-damon** [comment]
please can anyone review this issue?

**Comment by chj-damon** [comment]
my problem, fixed it.

**Comment by salmanullahkhan15** [comment]
> my problem, fixed it.

What was the issue?
