### ISSUE TITLE
EAS Update bricks app if triggered via GH Action, but NOT if triggered locally from developer machine

### ISSUE THREAD

**Issue by pax-k** [expo/expo#24518]
### Summary

- If running `eas update` from my machine, the update feature works as expected.
- If running `eas update` from Github Action, the update is delivered, but when the app receives it, it gets stuck in the splash screen. There are no errors or Sentry events to debug. 

I tried both automatic and on demand approaches:
- automatic: closing/reopening the app until the update is fetched > then gets stuck in splash
- manual: using [imperative approach](https://docs.expo.dev/versions/latest/sdk/updates/) > the update is seen > fetched > app reload > then gets stuck in splash

Also tried deleting previous builds, branches, channels, updates, then recreating them.

### What platform(s) does this occur on?

iOS

### SDK Version

49.0.11

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 3.5.1 - ~/.nvm/versions/node/v18.14.0/bin/yarn
      npm: 9.8.1 - ~/Documents/Repos/hyphen-wallet/node_modules/.bin/npm
      Watchman: 2023.07.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Minimal reproducible example

- app.config.js: https://gist.github.com/pax-k/19ee4d646b4f55b5fe5de87a441468a0
- eas.json: https://gist.github.com/pax-k/02c5981721c081e59a811c930ecf5518
- babel.config.js: https://gist.github.com/pax-k/866d2809e204b9c318976bc54ffc28cc
- metro.config.js: https://gist.github.com/pax-k/b5f1b00aaa84eecbe3b24cf5c087970c
- index.js: https://gist.github.com/pax-k/62374fe89c1722d9ce8a2749212c8fd0
- App.tsx: https://gist.github.com/pax-k/76b4fac314da60040f171074b88ca9af
- polyfills.js: https://gist.github.com/pax-k/d75a5379af90cab4e98f744e40df6b61
- package.json: https://gist.github.com/pax-k/7330916592176b43b98cb123f3d20c17
- eas-update-preview.yml: https://gist.github.com/pax-k/d1631208b53d387a616337c46f8a106b

WORKS:
- `run eas update --channel preview --non-interactive --message "updated preview manually"`
- update is delivered to devices
- devices get updated and work as expected

DOESNT'T WORK:
- pushing code to the `preview` branch
- the GH Action executes `eas update --branch preview --non-interactive --message "update preview to ${{ steps.get_tag_name.outputs.VERSION }}"`
- update is delivered to devices
- devices get updated but are stuck in the splash screen

**Comment by douglowder** [comment]
Why are you passing in `--channel` manually, but `--branch` in the GH action?

It appears that your `App.tsx` is part of a larger app. Please provide a repro that includes the entire project.

**Comment by brentvatne** [comment]
my guess is that there is some difference between the environments that you didn't account for, such as different environment variables or perhaps you don't have everything committed to git in a way that re-creates your local environment faithfully.

if you are getting stuck on the splash screen that may indicate that your code is calling `SplashScreen.hideAsync()` somewhere that is never reached, eg:

```
try {
  await doSomethingThatMightThrowAsync();
  SplashScreen.hideAsync();
} catch() {
  // we never call hideAsync();
}
```

https://github.com/expo/fyi/blob/main/splash-screen-hanging.md
