### ISSUE TITLE
[expo-image-picker] [only android] Multiple selection does not work on SDK 49

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#24526]
### Minimal reproducible example

https://snack.expo.dev/@brodanoel/trusting-yellow-ice-cream

### Summary

Open the Snack and you'll see that you won't be able to do multiple selections on Android, since SDK 49.

I tested it on read device with the new UI layout, and it's also broken (not sure why in the Snack the layout is the old one).

```
"expo-image-picker": "14.5.0",
"expo-image-manipulator": "11.5.0",
"expo-media-library": "~15.4.1",
"expo": "^49.0.9",
```

### SDK 48
<img width="386" alt="Screen Shot 2023-09-19 at 20 36 55" src="https://github.com/expo/expo/assets/1837969/75a25880-a079-49cd-a84a-466d73a3f1d8">

### SDK 49
<img width="390" alt="Screen Shot 2023-09-19 at 20 37 37" src="https://github.com/expo/expo/assets/1837969/168db459-14ef-423f-9301-d27cbd472225">

### Environment

```
➜  no-filter-app git:(master) ✗ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.8
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.9 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by BrodaNoel** [comment]
This may be related to https://github.com/expo/expo/issues/24367

**Comment by alanjhughes** [comment]
Hi @BrodaNoel - Support for `selectionLimit` was only added to Android with the new picker. Prior to that it was available on iOS only. On some devices, when the device is not capable of using the new picker it will fallback to the old picker, where again the limit is not supported.

**Comment by BrodaNoel** [comment]
@alanjhughes `selectionLimit` is not the problem of this issue. The problem here is that "Multiple Selection" is not possible.

Forget about `selectionLimit`. Multiple selection is not possible. If you check the Snack, the `selectionLimit` is not even used:

<img width="491" alt="Screen Shot 2023-09-21 at 17 45 52" src="https://github.com/expo/expo/assets/1837969/849b4a4e-bd0f-4aeb-b636-b665b65fbef6">


The problem here is that `allowsMultipleSelection` is not even working

**Comment by alanjhughes** [comment]
This is from your snack. It works fine. You need to hold the image to select it

![Screenshot 2023-09-21 at 21 50 10](https://github.com/expo/expo/assets/30924086/c29410bc-ccc1-4aad-9e8c-279ffe9b720e)

**Comment by alanjhughes** [comment]
Also, you said it was related to #24367 so presumed you also had a problem with `selectionLimit`

**Comment by alanjhughes** [comment]
If it's resolved I'll close this? @BrodaNoel

**Comment by BrodaNoel** [comment]
@alanjhughes no, why? This is not resolved.

If you add `allowsMultipleSelection: true,` in SDK 49 you will NOT be able to select multiples photos on Android

**Comment by BrodaNoel** [comment]
@alanjhughes check the title of this issue: "Multiple selection does not work on SDK 49".

This is not a report for `selectionLimit` behavior. This is a report for `allowsMultipleSelection` not working (and it still not working. Check the Snack)

**Comment by alanjhughes** [comment]
@BrodaNoel I am using the snack you provided on SDK 49 and it works. see https://github.com/expo/expo/issues/24526#issuecomment-1730282344

**Comment by BrodaNoel** [comment]
@alanjhughes what is the expected behavior in Android 9?

This is how it's working:

https://github.com/expo/expo/assets/1837969/501d78e4-6b6d-4594-a3e1-1a91e5350728

**Comment by BrodaNoel** [comment]
Why in SDK 48 you can "tap to select" and you have to "hold to select" in SDK 49?
Feels like nobody is going to know that you have to tap and hold in order to select multiples items.

**Comment by alanjhughes** [comment]
On a device that doesn't support google play services ie. Huawei it is the legacy behaviour that google provide, which is single selection. Android users will know because it's not unusual for their to be differences on that platform. Either way, we can't account for those variances. Android is open source. They change it how they see fit.

**Comment by BrodaNoel** [comment]
Oh! I thought that the way of selecting them was a change on expo-image-picker. My bad.

So... I think it's OK to close it. Sorry for that!

**Comment by alanjhughes** [comment]
No, we don't control that UI at all. It's provided by google, we pass it whatever configuration the user provides and present it. After that, they decide how to deal with it based on OS versions, services availability etc. No problem 👍

**Comment by Quaid5050** [comment]
same issue multiple selection is not working in sdk 49

**Comment by HenZzz-999** [comment]
Hello, I think my solution to this problem that also happened to me would be to use the expo library 'expo-media-library' and create our own screen where we will show all the images of the device with 'flash-list' (for a better optimization) and where the user could select the images they want, the advantage of this method is that we can program how we want the screen and what maximum number of images the user can select, fully configurable, here are the library pages:

https://docs.expo.dev/versions/latest/sdk/media-library/
https://shopify.github.io/flash-list/

The final result would be like the screen for creating a new Instagram post where it allows you to select images and like the one on Pinterest:
![capture_instagram](https://github.com/expo/expo/assets/72719294/c0945509-2c31-475d-b350-73151e7f9691)

A pleasure and I hope I have helped :)

**Comment by Quaid5050** [comment]
Thank you so much 💕
Stay blessed

**Comment by pernillelorup** [comment]
If someone still encounters this issue, I just added `quality: 1` to the options object and now everything works perfectly on IOS, Android and Web 😎 

```javascript
const mediaTypes = ImagePicker.MediaTypeOptions.Images
const options = { mediaTypes, allowsMultipleSelection: true, base64: true, quality: 1 }
const result = await ImagePicker.launchImageLibraryAsync(options)
```

**Comment by Stephan-MDD** [comment]
> If someone still encounters this issue, I just added `quality: 1` to the options object and now everything works perfectly on IOS, Android and Web 😎
> 
> ```js
> const mediaTypes = ImagePicker.MediaTypeOptions.Images
> const options = { mediaTypes, allowsMultipleSelection: true, base64: true, quality: 1 }
> const result = await ImagePicker.launchImageLibraryAsync(options)
> ```

Wow I have been looking for a solution to this mess for way too long - and a simple `quality: 1` solved the issue😃

**Thank you - Here is a coffee ☕**

![test](https://i.kym-cdn.com/photos/images/newsfeed/001/513/012/625.jpg)

**Comment by BrodaNoel** [comment]
Naaaa... I don't believe you. You must be kidding me.

**Comment by BrodaNoel** [comment]
@alanjhughes do you have any information about this? Was this already known that it could have been fixed with a quality:1?

**Comment by bzozoo** [comment]
> If someone still encounters this issue, I just added `quality: 1` to the options object and now everything works perfectly on IOS, Android and Web 😎
> 
> ```js
> const mediaTypes = ImagePicker.MediaTypeOptions.Images
> const options = { mediaTypes, allowsMultipleSelection: true, base64: true, quality: 1 }
> const result = await ImagePicker.launchImageLibraryAsync(options)
> ```

It is not work for me

**Comment by mleister97** [comment]
Not working for me on Android 10. Why is this issue closed?

**Comment by Ademola101** [comment]
Why is this closed?

**Comment by webabbey247** [comment]
Mutlple selection not working for SDK 51
