### ISSUE TITLE
Suddenly: CommandError: No development build (org.name.YachtWave) for this project is installed

### ISSUE THREAD

**Issue by jeokeefe** [expo/expo#24523]
### Summary

Please help. All of a sudden (today) my expo app will not run on either simulators. This is an app i have been developing for almost a year with Expo and never had a simulator issue. I don't understand why this just started to happen. 

### SDK Version

49.0.11

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed

### Minimal reproducible example

Here is how it happens - i have no code changes (that I am away of) and it now wont run on the simulators:

1) npx expo start -c
2) Press 'i' for ios simulator (or 'a' for android)
3) instantly get the error:

CommandError: No development build (org.name.YachtWave) for this project is installed. Please make and install a development build on the device first.
Learn more: https://docs.expo.dev/development/build/

**Comment by jeokeefe** [comment]
well no response, but it seems Expo added (or defaults differently) the ability to switch between Expo Go and Development builds. Mine was set to Development builds.

**Comment by seyaobey-dev** [comment]
@jeokeefe I'm facing the same issue. Can you elaborate on your answer? I don't understand when you say "Expo added the ability to switch between Expo Go and Development builds. Mine was set to Development builds." 
What should I do exactly to fix this problem? Is there some particular config setting I should enable, disable or change?
Thank you for further helping.

**Comment by bogris** [comment]
for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual. 

this happened after making the setup for building the app on EAS

**Comment by apicgg** [comment]
> for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> 
> this happened after making the setup for building the app on EAS

In this case 

- Remove the `expo-dev-client` dependency from your project's package.json.
- Delete `node_modules` and install with `npm i`.
- Start fresh with `npx expo start --clear`.

**Comment by AlbertoAquinoDev** [comment]
> > for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> > this happened after making the setup for building the app on EAS
> 
> In this case
> 
> * Remove the `expo-dev-client` dependency from your project's package.json.
> * Delete `node_modules` and run `npm i`.
> * Start fresh with `npx expo start --clear`.

Hello, thank you for your reply, could you please elaborate more on why are these things related? It happened exactly the same to me and I would like to know why...

**Comment by apicgg** [comment]
> > > for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> > > this happened after making the setup for building the app on EAS
> > 
> > 
> > In this case
> > 
> > * Remove the `expo-dev-client` dependency from your project's package.json.
> > * Delete `node_modules` and run `npm i`.
> > * Start fresh with `npx expo start --clear`.
> 
> Hello, thank you for your reply, could you please elaborate more on why are these things related? It happened exactly the same to me and I would like to know why...

Found a great read from expo official docs - [https://docs.expo.dev/develop/development-builds/introduction/](expo docs about dev build). Maybe this will help.

**Comment by cseelus** [comment]
Those dev clients are a bit weird. 

You need to run your iOS devices in developer mode, which Apple warns is inherently unsafe. Wouldn't do it, if it can be avoided.

**Comment by BaslaelWorkineh** [comment]
just use "npx expo start" instead of "npm start"

**Comment by tundeeratek** [comment]
> for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> 
> this happened after making the setup for building the app on EAS

As simple as it is, this solutions works

**Comment by AnimeFlix007** [comment]
> for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> 
> this happened after making the setup for building the app on EAS

Love you brother.. thank you for your help

**Comment by gadhiyamanan** [comment]
> > for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> > this happened after making the setup for building the app on EAS
> 
> In this case
> 
> * Remove the `expo-dev-client` dependency from your project's package.json.
> * Delete `node_modules` and run `npm i`.
> * Start fresh with `npx expo start --clear`.

Works For me, Thanks a lot!

**Comment by Ahmad-Hanki** [comment]
> for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> 
> this happened after making the setup for building the app on EAS


yup, that worked

**Comment by nanzeeba** [comment]
Running "npx expo start --tunnel" worked for me

**Comment by van5dang2005** [comment]
> * `npx expo start --clear`.

Thanks so much

**Comment by ThePredators** [comment]
> for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> 
> this happened after making the setup for building the app on EAS

Bravo my friend !

**Comment by DoXX2** [comment]
If anybody comes across this issue and actually wants to have a development build (including expo-dev-client) on an iOS simulator:

Just open the Simulator app manually first. I quit the simulator app and started getting this error, which was really confusing. After opening it manually and executing `npx expo run:ios --device` again, it worked

**Comment by LionTara** [comment]
> for me, when I run expo start, it wants to start a development buil. I first press "S" to switch to expo and them it open the emulator as usual.
> 
> this happened after making the setup for building the app on EAS

This worked for me thank you
