### ISSUE TITLE
[expo-barcode-scanner] [Android] [iOS] Problem reading the barcode

### ISSUE THREAD

**Issue by ppo50** [expo/expo#24522]
### Minimal reproducible example

https://snack.expo.dev/@poliveira50/problem-reading-the-barcode-scanner

### Summary

I'm having trouble reading the barcode on some types of devices
I looked at device logs (Motorola One Vision, iPhone 14 and iPhone 14 pro), where they have the problem of reading the barcode (the cell phone is pointed at the code and nothing happens).
All of them (Motorola One Vision, iPhone 14 and iPhone 14 pro) the tests were carried out by X Code and Android Studio and also running through the terminal and none of these means showed error logs.
There are devices that just point the camera at the barcode to read it (Samsung S20 and Motorola Fusion).
I investigated the logs of each device mentioned above and even in those where the camera does not read, no error log appears.
An error was also found where the cell phone can read the bill but reads it with missing numbers in the middle of the code.

For example:

The typeable line is `123456 6 123456`
The device reads: `123456 123456`

Disappearing with the number `6` that was left between the spaces.

This happens with both app debugging and app production.

```JS
{
  "dependencies": {
    "expo": "^49.0.8",
    "expo-barcode-scanner": "~12.5.3",
    "expo-camera": "~13.4.2",
    "react": "18.2.0",
    "react-native": "0.72.3"
  }
}
```
**The Android studio log of the camera that does not read the barcode**
![Screen Shot 2023-09-18 at 17 53 18](https://github.com/expo/expo/assets/122992649/76f79a11-c2be-413b-9a55-74dde1f0e0a3)

### Environment

 ``` JS
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - /usr/local/bin/node
      Yarn: 3.3.0 - /opt/homebrew/bin/yarn
      npm: 8.19.3 - /usr/local/bin/npm
      Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.1.0
    Expo Workflow: managed

**Comment by brentvatne** [comment]
can you share the barcode that you are scanning please?

**Comment by ppo50** [comment]
@brentvatne sure! :) 
[Fatura.pdf](https://github.com/expo/expo/files/12769698/Fatura.pdf)

**Comment by ppo50** [comment]
Hi @brentvatne, were you able to reproduce the problem :)?
Is there anything else I can provide to help with the investigation?

**Comment by alanjhughes** [comment]
Hi @ppo50 - I can't access your snack. Could you try sharing another one or showing me how you are using the component?

**Comment by ppo50** [comment]
Hi @alanjhughes, sorry..
I just fixed my broken snake link, now it is working again 😄

**Comment by alanjhughes** [comment]
Thank you! A couple of us have tried to reproduce on different devices using the barcode you provided but so far have not been able to. I would expect some variance on Android but seeing it on iPhones too is unusual. When there is no error it means that the device doesn't see the code, either because it's not in the `barCodeTypes` prop or it just isn't supported. I'm not sure why these devices would be having issues.

**Comment by alanjhughes** [comment]
Thank you! A couple of us have tried to reproduce on different devices using the barcode you provided but so far have not been able to. I would expect some variance on Android but seeing it on iPhones too is unusual. When there is no error it means that the device doesn't see the code, either because it's not in the `barCodeTypes` prop or it just isn't supported. I'm not sure why these devices would be having issues.

**Comment by ppo50** [comment]
@alanjhughes In some cases, some of the cell phones mentioned read but read by "cutting" numbers from the bardcode.
For example:
The barcode has the numbers 12345 6 78910
It reads but in the reading log the numbers read were
12345 78910

The number 6 appears as if it did not exist in the middle of reading.

**Comment by alanjhughes** [comment]
Very strange. Is this all from user reports or you have reproduced this yourself?

**Comment by ppo50** [comment]
@alanjhughes I just wanted to let you know that I reproduced here to see why I can't read the bardcode.
At the company we have api`s logs and in one of the logs where the bardcode was able to be read, the api input was missing numbers.

I'll try to get more barcodes with reading problems to make them available here :)

**Comment by ppo50** [comment]
@alanjhughes hello..
here are more bills that I can't pay on either iOS (14 Pro) or Samsung S20
![image (3)](https://github.com/expo/expo/assets/122992649/f9b7ac1d-a2cc-4b6c-a196-21f520e78a45)
[boleto_02_45_36.pdf](https://github.com/expo/expo/files/12920352/boleto_02_45_36.pdf)
[16-10-2023 14_29 Microsoft Lens.pdf](https://github.com/expo/expo/files/12920355/16-10-2023.14_29.Microsoft.Lens.pdf)
[16-10-2023 14_30 Microsoft Lens.pdf](https://github.com/expo/expo/files/12920359/16-10-2023.14_30.Microsoft.Lens.pdf)
[16-10-2023 14_50 Microsoft Lens.pdf](https://github.com/expo/expo/files/12920362/16-10-2023.14_50.Microsoft.Lens.pdf)
![IMG_6285](https://github.com/expo/expo/assets/122992649/4e327eac-27d3-4d89-852b-d644b7d7dc0a)
