### ISSUE TITLE
[docs] Broken link to "Already used React Native" in "Manage VS Bare" page

### ISSUE THREAD

**Issue by theFreedomBanana** [expo/expo#24534]
### Summary

As mentionned in the title, the "Already used React Native" [link](https://docs.expo.dev/workflow/already-used-react-native) is broken in the manage VS Bare [page](https://docs.expo.dev/archive/managed-vs-bare/) (might be used elsewhere idk)

### Link to the related docs page

https://docs.expo.dev/archive/managed-vs-bare/

**Comment by brentvatne** [comment]
thanks, fixed in https://github.com/expo/expo
