### ISSUE TITLE
[Camera vs BarCodeScanner] - Difference in X and Y return values.

### ISSUE THREAD

**Issue by iatanasov37** [expo/expo#24540]
### Minimal reproducible example

https://snack.expo.dev/@sellercloud/camera-vs-barcodescanner-barcode-result

### Summary

The provided snack is not perfect, but it goes to show that there are noticeable differences, between the data that `onBarcodeScanned` emits.

Here are a few key differences:

1. X and Y representation:
`BarCodeScanner` - returns actual pixel values
`Camera` - returns a relative value

2. On Android and iOS for both components, there is a difference in the type.
Android DataMatrix returns: 16
iOS Datamatrix returns: org.Iso.DataMatrix

Is there a possibility to sync the return types?
Alternatively, could you shed more light as to how the relative x and y values emitted by the Camera component can be translated to actual pixel values? (What factors are at play in the calculations?)

example image:
![image](https://github.com/expo/expo/assets/69120211/74a4edc8-724a-4388-9e33-b67f4ea99bab)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.0.8
    Expo Workflow: managed

**Comment by smisaacs** [comment]
+1

**Comment by WeZinc** [comment]
+1

**Comment by WeZinc** [comment]
+1

**Comment by iatanasov37** [comment]
@tamagokun Sadly, the BarCodeScanner is being deprecated, but the issue persists in both `expo-camera` and `expo-camera/next`, which are supposed to be replacements for the Barcode Scanner as of SDK 51.

**Comment by Itsdarkhere** [comment]
What's the current status for this? Just migrated to SDK51 and expo-camera and the bounds are very much different to expo-barcode-scanner
