### ISSUE TITLE
[expo-router 2.0.7] "TypeError: cyclical structure in JSON object"

### ISSUE THREAD

**Issue by Oui-Dev** [expo/expo#24541]
### Minimal reproducible example

https://github.com/Oui-Dev/debug-router

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I just updated expo-router (2.0.6 -> 2.0.7), and when I go to certain pages of my application, it gives me this error: "TypeError: cyclical structure in JSON object". If i downgrade to 2.0.6, my app work again.

To reproduce this issue, just run the app. As you can see the bottom tab navigation works but if you click on an item the error occurs.

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.5.2
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.5.0 - /opt/homebrew/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 9.8.0 - /opt/homebrew/bin/npm
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
IDEs:
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
Expo Workflow: managed

**Comment by marklawlor** [comment]
Should be fixed `2.0.8`
