### ISSUE TITLE
Expo-router 2.0.7 breaks catch-all routes such as '/project/[id]'

### ISSUE THREAD

**Issue by ljukas** [expo/expo#24552]
### Minimal reproducible example

https://github.com/ljukas/expo-router-bugs

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

With the newest release 2.0.7 that fixes replace from nested navigators, some route setups using catch-all routes such as `/project/[id]` results in cyclical errors and crashes the app. What seems to happen is that in the route state the params for the project page ends up like this:

```js
params :{
   id: '...',
   params: {
      id: '...'
      params: {
          id: '...'
          ....
```

Check repro repo for example.
App runs in expo-go and you just have to press the text in the middle that tries to link to `/project/1` and app will crash

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
      Yarn: 3.6.1 - ~/.nvm/versions/node/v18.9.0/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/lukas/.gem/ruby/3.1.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.11 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by rskvazh** [comment]
[fixed in 2.0.8](https://github.com/expo/expo/issues/24541#issuecomment-1728563365). Checked - now its worked.
