### ISSUE TITLE
Expo Web does not run on SDK 49

### ISSUE THREAD

**Issue by nanyaDev** [expo/expo#24554]
### Minimal reproducible example

https://github.com/nanyaDev/bug-repro

### Summary

Issue #23412 is closely related to my issue, however it was closed. Others in that thread continued to experience issues, and one of the maintainers had asked for a reproduction to help resolve the issue. I replied with a reproduction, but I'm assuming it went unnoticed because the issue was closed. So, I'm creating a new issue to track this problem. I've copy-pasted my original reply below.

---

> If you still having issues can you either create a new issue or reply with a repo that reproduces the issue for us. Screenshots provide very little value in helping us troubleshoot issues

@marklawlor I've created a minimal [repo](https://github.com/nanyaDev/bug-repro) that reproduces the error:

The exact commands I ran to set up the repro can be seen in the commit messages. The linked repo fails on `npm run web` with the following error:

```
Web Bundling failed 1005ms
Unable to resolve "@fortawesome/fontawesome-svg-core" from "node_modules/@fortawesome/react-native-fontawesome/dist/components/FontAwesomeIcon.js"
```

I confirmed that the issue resolves itself when downgrading to SDK 48. I was also able to fix the issue by creating a `metro.config.js` with the following contents:

```javascript
const { getDefaultConfig } = require('@expo/metro-config');

const config = getDefaultConfig(__dirname);
config.resolver.sourceExts.push('cjs', 'mjs');

module.exports = config;
```

(taken from [this](https://github.com/expo/expo/issues/23412#issuecomment-1634916708) comment by @rozsival)

As [previously mentioned](https://github.com/expo/expo/issues/23412#issuecomment-1653179239) by @rozsival, both issues relating to this error have been closed. Now that a minimal repro exists, could one of the issues be re-opened? (alternatively I can file a new issue)

**Comment by marklawlor** [comment]
I believe these issues were resolved in `@expo/metro-config@0.13.1`. You can upgrade by simply installing that version as a dependency. You will get a warning about using an incompatible version, but it should will work & hopefully fix your issue.

**Comment by rozsival** [comment]
I can confirm using `@expo/metro-config` at `v0.13.1` fixes the issue.

**Comment by brentvatne** [comment]
@rozsival - hopefully this helps: https://expo.fyi/splash-screen-hanging

**Comment by hyochan** [comment]
> @rozsival - hopefully this helps: https://expo.fyi/splash-screen-hanging

@brentvatne Thanks for the link but I think this isn't helping. I also experience the same thing and downgrading `@expo/metro-config` to `0.10.1` works on `iOS`. However, I need to upgrade this to fix the `stylis` issue on `web` 🤔

**Comment by rozsival** [comment]
With SDK 49, still the best option is to manually add .mjs extension to metro config. Other suggested fixes either do not help, or create other compatibility issues depending on which expo packages the app uses.

**Comment by marklawlor** [comment]
Please create a new issue if upgrading causes compatibility issues. We would love to fix these issues but we can only fix what is reported!

**Comment by RonaldChicaVera** [comment]
downgrading @expo/metro-config to 0.10.1 worked for me
