### ISSUE TITLE
Expo router 2.0.7 - <Slot /> intercepts navigation.setOptions

### ISSUE THREAD

**Issue by ljukas** [expo/expo#24553]
### Minimal reproducible example

[ljukas/expo-router-bugs](https://github.com/ljukas/expo-router-bugs)

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

My understanding of <Slot /> is limited but this structure should work

- _layout.tsx - Stack
- dir
   - _layout - with <Slot />, for example that implements auth
   - screen - rendered within the dir and inside the _layout
   
 With this structure, the screen is routable and accessible with `/dir/screen`, but we cannot access the correct navigation options anymore from within the screen using `useNavigation`-hook.

So for example within `screen` this does not change the title of the header

```js
const navigation = useNavigation()

useFocusEffect(useCallback(() => {
   navigation.setOptions({
      title: 'test'
     }), [navigation])
   )
```

However this does work if we remove the _layout file that returns the <Slot />, which seems to indicate that the <Slot /> component intercepts the navigation state handling making it impossible to control from within the <Slot />

Side note: 
this also throws the warning: `[Layout children]: No route named "slotIssue/header" exists in nested children: ["project/[id]", "slotIssue"]`

but everything works regarding reaching the screen etc via `router.push('/slotIssue/header')

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
      Yarn: 3.6.1 - ~/.nvm/versions/node/v18.9.0/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/lukas/.gem/ruby/3.1.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.11 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by Arnaud-J** [comment]
I am experiencing the same issue using `<Stack.Screen options={{ title: 'test' }} />`, the title does not change as long as a `<Slot />` sits between the `<Stack />` declaration and the attempt to change options (either through `Stack.Screen` or `navigation.setOptions`) in the components tree.

This is problematic because I have to rely on `Slot` for multiple guards in my app, like authentication for example.

I would like to help tackle the (presumed) bug but it is hard to know where to start.

**Comment by EvanBacon** [comment]
You can access different navigators by passing the route id to `useNavigation`, e.g. `useNavigation('/')` returns the root layout's navigation context.

**Comment by DeluxeOwl** [comment]
Did this actually get solved? Still doesnt work for me with expo router 3.0. Trying to change it from a component rendered in Slot doesnt work

**Comment by marklawlor** [comment]
@DeluxeOwl Please create a new issue with a reproduction of what your trying to achieve.

**Comment by ljukas** [comment]
Ill remake the issue later today
