### ISSUE TITLE
AuthSession: authUrl query param of form state={state-param} classified as invalid

### ISSUE THREAD

**Issue by AlfredOdling** [expo/expo#2455]
### Expected Behavior
I would like to proceed to login.

### Actual Behavior
I get an error message:
ValidationError: child "authUrl" fails because ["authUrl" must be a valid uri]

I have tried with Google and Github sign in, but get the same message.

### Reproducible Demo
https://snack.expo.io/@alfredodling/social-auth

**Comment by n-sviridenko** [comment]
Have another issue. We use our own identity broker which has multiple providers such as facebook. The thing is that we redirect to the broker first and expo triggers the same issue for this. The url is `<our base url>/login/openid?isWebView=1&redirectUri=${encodeURIComponent(AuthSession.getRedirectUrl())}`

**Comment by EvanBacon** [comment]
I can confirm that this is fixed in the new AuthSession API which supports PKCE, and state out of the box.
