### ISSUE TITLE
Error validating credentials when building iOS app

### ISSUE THREAD

**Issue by andrewreal** [expo/expo#2456]
### Environment

`Environment:
  OS: Windows 10
  Node: 8.12.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4`

Build for Android works but build for iOS fails with the error message below.

### Steps to Reproduce

`expo build:ios`
Set Expo to handle credentials.
Enter Apple ID and password.

### Expected Behavior

Build process to start or more questions.

### Actual Behavior

`[14:31:32] Validating Credentials...
Error: spawn C:\Windows\system32\bash.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

### Reproducible Demo

https://expo.io/@andrewreal/OKCBD

Gitlab access can be granted if required - currently a private repo.

**Comment by andrewreal** [comment]
Update:

I am also getting the error message about WSL is not enabled, however WSL has been used on this machine since shortly after it became available and I have run the `Enable-WindowsOptionalFeature` script several times.

I've since tried building the demo app for iOS and getting the same error so I'm sure it's a problem with my environment rather than the app code or configuration.

**Comment by waqaramjad** [comment]
facing same issue window 8

**Comment by tsapeta** [comment]
As this issue is pretty old and a lot of things have changed since this report, I'm closing it. If you're still encountering this in the most recent version of `expo-cli`, please submit a new issue in https://github.com/expo/expo-cli repo.
