### ISSUE TITLE
[Android] Build failed ':expo-modules-core:compileDebugKotlin' : Expo 49.0.11 & Expo-Router 2.0.0

### ISSUE THREAD

**Issue by bouncydragon** [expo/expo#24567]
### Summary

I'm new in using Expo and I'm getting this error after running `./gradlew assembleDebug` inside my `android` folder. I generated my android folder using: `npx expo run:android`.

I'm planning to create an apk without using eas-cli.

![image](https://github.com/expo/expo/assets/9712523/2e6b88e1-6200-45e5-93ef-bf7961bf08e6)

Here are other information:

![image](https://github.com/expo/expo/assets/9712523/8fe03a74-0b5d-4f6e-ae11-8e074680ff68)
![image](https://github.com/expo/expo/assets/9712523/12f2af87-ef53-4c44-b395-cab8c2b642e8)

### What platform(s) does this occur on?

Windows

### SDK Version

49

### Environment

![image](https://github.com/expo/expo/assets/9712523/7cb84292-e278-4e27-bfce-723fc2fc5a92)

### Minimal reproducible example

https://github.com/bouncydragon/sample-android-app

**Comment by brentvatne** [comment]
make sure you have JDK 11 installed, you have 19 right now: https://docs.expo.dev/guides/local-app-development/#android
