### ISSUE TITLE
expo-image-picker's launchCameraAsync() always opens up 'front' camera on Android.

### ISSUE THREAD

**Issue by sungsong88** [expo/expo#24564]
### Minimal reproducible example

https://snack.expo.dev/@itemtopiadeveloper/android-camera-type-bug

### Summary

On iOS, the `ImagePicker.launchCameraAsync()` function operates smoothly as expected. However, on Android, there is an issue where the camera consistently starts with the front-facing camera. According to the documentation, `launchCameraAsync` has `cameraType` set to 'back' by default, so it should work without the need to explicitly set `cameraType: ImagePicker.CameraType.back`. Nevertheless, this default behavior is not being observed.

While it's possible to manually switch the camera after entering camera mode, this behavior is inconvenient and undesirable. I would greatly appreciate assistance in resolving this issue on Android to ensure that the camera starts with the rear-facing camera by default. Thank you for your help.
```jsx
import * as ImagePicker from 'expo-image-picker';

ImagePicker.launchCameraAsync({
      quality: 1,
      exif: true,
      cameraType: ImagePicker.CameraType.back
})
```

### Environment

```
"expo": "~49.0.11"
"expo-image-picker": "~14.3.2"
```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.9.1/bin/yarn
      npm: 8.7.0 - ~/.nvm/versions/node/v16.9.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/opt/rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by kadikraman** [comment]
Hi @sungsong88 I tried the snack you provided on my Pixel 7 and I was unable to reproduce the issue you were having. The default camera always opens the back camera for me.

It seems most likely an app or device specific setting on the phone which has set the "default" to be the front facing camera instead of the back. I suggest double checking at the camera app settings and clearing the camera app cache on the phone.
