### ISSUE TITLE
Compiling for iOS 12.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.0

### ISSUE THREAD

**Issue by benjamin-benoit** [expo/expo#24578]
### Minimal reproducible example

"react-native-skeleton-content": "1.0.28"

### Summary

I use expo 49.0.7, all react-native dependencies:

```
    "react-native": "0.71.8",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "2.8.2",
    "react-native-pager-view": "6.1.2",
    "react-native-phone-input": "^1.3.4",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-skeleton-content": "1.0.28",
    "react-native-skeleton-placeholder": "^5.0.0",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-web": "~0.18.10",
    "react-native-webview": "11.26.0",
```

When I run `npm run ios` or I run on xCode after `npx expo prebuild` I get this error:
<img width="817" alt="Capture d’écran 2023-09-22 à 20 09 32" src="https://github.com/expo/expo/assets/43535322/336c3a22-434a-4635-a88f-d0b259d2db71">

expo-linear-gradient used:
<img width="558" alt="Capture d’écran 2023-09-22 à 20 14 34" src="https://github.com/expo/expo/assets/43535322/a243a96e-ab86-46b2-ae43-113d58d1cc6a">

### Environment

iOS

**Comment by alanjhughes** [comment]
The issue is with the library. They need to update their dependencies

**Comment by johnmccants002** [comment]
How was this fixed?

**Comment by oscadev** [comment]
> How was this fixed?

In my case, I did two things. First, in your xcode settings, change the min target to 13 in both the project and in target -> yourApp. I also added this line 
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

in the podfile underneath
installer.aggregate_targets.first.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
