### ISSUE TITLE
Styling with the Link 

### ISSUE THREAD

**Issue by mashwishi** [expo/expo#24584]
### Minimal reproducible example

Creating a style and making them uinform will have different output from Link

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

No matter what I do, I can't make it the same as the TouchableOpacity design. Even you switch the Link inside and View in the outside the output will be the same.

```js
export default function Support() {
    const navigation = useNavigation();

    
  return (
    <SafeAreaView style={styles.container}> 
        <View style={{ ...styles.spacey }}>
          <TouchableOpacity style={{ ...styles.button, backgroundColor: '#3266CC'}} onPress={null}>
            <Text style={{ ...styles.buttonText, color: 'white'}}>Contact Support</Text>
          </TouchableOpacity>
        </View>

        <Link style={{ ...styles.spacey }} href={'/settings/delete-account'} >
          <View style={{ ...styles.button, backgroundColor: '#3266CC' }}>
            <Text style={{ ...styles.buttonText, color: 'white'}}>Account Deletion</Text>
          </View>
        </Link>

    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    flexDirection: 'column',
  },
  spacey: {
    borderWidth: 3,
    marginVertical: 8, 
    marginHorizontal: 20,
  },
  button: {
    padding: 20,
    width: '100%',
    alignSelf: 'center',
  },
  buttonText: {
    fontSize: 20,
    alignSelf: 'center',
  },
});
```

Output:
![image](https://github.com/expo/expo/assets/62344860/04b42325-d4b8-4048-a3f0-fcc4bbfd493c)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.10.0/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.5 => 49.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ^0.19.7 => 0.19.8 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
You need to use the `asChild` prop   https://docs.expo.dev/routing/navigating-pages/#buttons

**Comment by mashwishi** [comment]
Will look into this next Saturday. Thanks!

**Comment by alanjhughes** [comment]
Ok, I'll close for now 👍

**Comment by thalesaguiar** [comment]
@mashwishi Were you able to solve this problem?

**Comment by thalesaguiar** [comment]
@mashwishi  Why did you declare: const navigation = useNavigation(); in this file? I ask because you're already using Link to navigate between screens, right?
