### ISSUE TITLE
sendSMSAsync do not send the message

### ISSUE THREAD

**Issue by njarmoluk** [expo/expo#24586]
### Minimal reproducible example

const { result } = await SMS.sendSMSAsync(   [ '+5491158776699'],   'My sample HelloWorld message');

### Summary

sendSMSAsync open the sms app, show the message but remains pending to the user press the send button.
![Screenshot_20230923-121632](https://github.com/expo/expo/assets/143952826/0b100e02-1989-4706-b313-c4c762805004)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.0.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.10 => 49.0.10
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi, this is expected behaviour. We cannot send a message on the users behalf. They need to hit send to confirm.
