### ISSUE TITLE
audio-av: ERR_UNEXPECTED when playing audio in background

### ISSUE THREAD

**Issue by pdandradeb** [expo/expo#24581]
### Minimal reproducible example

https://github.com/appjusto/courier-app

### Summary

After updating to `expo-av@13.6.0` from `expo-av@13.4.1`, playing a sound in background started to yield `ERR_UNEXPECTED`. Reverting it fixed.
I suspect it has something to do with this: https://github.com/expo/expo/pull/24198.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.11 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.6
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi, your repro isn't minimal. Can you strip it back to a single screen that triggers the issue please or provide exact steps?

**Comment by leethree** [comment]
I think it might be related to the issue I reported: #24515

There is a version incompatibility issue with expo-av 13.6 and expo 49

**Comment by VictorioMolina** [comment]
I am also experiencing https://github.com/expo/expo/issues/24515 and https://github.com/expo/expo/issues/24629

**Comment by skfaisal93** [comment]
Can anyone able to manage play audio in background with notification control ?
