### ISSUE TITLE
prebuild does not support fully private npm repos

### ISSUE THREAD

**Issue by samuel-gay** [expo/expo#24599]
### Summary

I work in a large enterprise that has strict security requirements, for proxy network access to the internet, and one of those requirements is that everything must use the internal npm registry which is proxied to the internet registries.

Unfortunately this has caused problems before, and while upgrading to the latest Expo SDKs, the way prebuild works has changed.

I have tracked down the issue to the downloading of the template package from the registry, but not using npm, but node-fetch to connect and download the tar. This might have seemed like a good idea as a developer, but it has created problems, because it is using yet another mechanism which could potentially create inconsistencies in how packages are accessed, especially those that require authentication.

I found the ticket [eas-cli#918](https://github.com/expo/eas-cli/issues/918), to which the 'resolution' was just use scoped packages for private packages, I don't have that option.

I have figured out a fix for the @expo/cli package, but since eas-cli bundles and reinstalls the packages, it wipes out my local changes (obviously). They are two very small changes.

@expo/cli/build/src/utils/npm.js line 96
```
    const response = await cachedFetch(url, {headers: {authorization: process.env.REGISTRY_TOKEN ? `Bearer ${process.env.REGISTRY_TOKEN}`: undefined}});
```

@expo/cli/build/src/api/rest/client.js line 53
```
        if (token && !resolvedHeaders.authorization) {
```

Then a developer can just create an environment variable (REGISTRY_TOKEN) with their authentication token, and it will be used when not using npm to fetch a package. I've tested this using `expo prebuild` and it seems to work

For reference this is the error I am getting from eas build (android):
```
[PREBUILD] - Creating native project directories (./ios and ./android) and updating .gitignore
[PREBUILD] 2023-09-25T02:12:44.991Z expo:utils:npm Run: npm view expo-template-bare-minimum@sdk-49 dist.tarball --json
[PREBUILD] 2023-09-25T02:12:44.991Z expo:utils:npm Fetch from URL: https://artifactory.internal:443/artifactory/api/npm/npm/expo-template-bare-minimum/-/expo-template-bare-minimum-49.0.19.tgz
[PREBUILD] 2023-09-25T02:12:44.993Z expo:api:fetch:base fetch: https://artifactory.internal:443/artifactory/api/npm/npm/expo-template-bare-minimum/-/expo-template-bare-minimum-49.0.19.tgz
[PREBUILD] Props Authentication Token not found
[PREBUILD] - Creating native project directories (./ios and ./android) and updating .gitignore
[PREBUILD] ✖ Failed to create the native project.
```

### What platform(s) does this occur on?

Android

### SDK Version

49

### Environment

.

### Minimal reproducible example

create an expo demo app
.npmrc/.yarnrc to a full private npm repo, that requires authentication for everything, but also proxies to the public repos
expo prebuild or eas build

**Comment by samuel-gay** [comment]
@wkozyra95 is this something you can help with, since you commented on the other ticket I mentioned? https://github.com/expo/eas-cli/issues/918

**Comment by michaelchen-cb** [comment]
We are having the exactly same issue

**Comment by michaelchen-cb** [comment]
Installing the iOS17 runtime in xcode solved my issue. I think this is not really related to private npm repos, but expo could provide more useful error messages.

**Comment by Jojocaster** [comment]
we're having the same issue - running `expo prebuild` always errors with `Props Authentication Token not found` on CI (which seems to be related to JFrog). Weirdly enough, we install private deps in the previous step and that works just fine. 
We've generated a `.npmrc` file, and even tried to run `expo prebuild --no-install` but we keep running into the same issue.
Why would `expo prebuild --no-install` still try to use `npm i` ?

**Comment by frankcalise** [comment]
@Jojocaster you can run prebuild following this guide to circumvent this for now: https://github.com/expo/fyi/pull/139

Prebuild has a step that is looking for a tarball (for the native template files) to be hosted within the registry (jfrog in this case) but perhaps isn't there. You can point to it locally or externally by design and the rest of your packages should install just fine

**Comment by Jojocaster** [comment]
@frankcalise thanks for getting back to me so quickly - just tried that earlier, and while it works fine locally, our CI returns:
```
2024-01-03T14:33:32.615Z expo:api:fetch:base fetch: https://api.github.com/repos/expo/expo/contents/templates/expo-template-bare-minimum/package.json?ref=main
✖ Could not locate the repository for "https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum". Please check that the repository exists and try again.
```
Not sure why that's only happening on CI, everything else works just fine.

**Comment by keith-kurak** [comment]
> @frankcalise thanks for getting back to me so quickly - just tried that earlier, and while it works fine locally with node 16, our CI returns:
> 
> ```
> 2024-01-03T14:33:32.615Z expo:api:fetch:base fetch: https://api.github.com/repos/expo/expo/contents/templates/expo-template-bare-minimum/package.json?ref=main
> ✖ Could not locate the repository for "https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum". Please check that the repository exists and try again.
> ```
> 
> Not sure why that's only happening on CI, everything else works just fine. Also, while it works fine locally with node 16, I get the same error as above with node 20 🥲

Hi @Jojocaster ! Can you confirm the command you're running that returns this output? Thanks!

**Comment by Jojocaster** [comment]
@keith-kurak I'm just running `expo prebuild`.
I've also been trying to pass a template like so: `expo prebuild --template https://github.com/expo/expo/tree/sdk-49/templates/expo-template-bare-minimum` - interestingly enough, it works 50% of the time 😄 
Sometimes it works and I can eject and build just fine, sometimes it just can't fetch the template.
