### ISSUE TITLE
Directly Save Files to Specific Album in Expo Media Library

### ISSUE THREAD

**Issue by temurih** [expo/expo#24591]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by jacobsood** [comment]
If you haven't resolved this yet, or those that are facing this issue, adding the `android.permission.MANAGE_MEDIA` permission into your `app.json` file for Android should partially solve this issue. The next step would be to notify the user to navigate to the Media management apps screen in system settings, from where they can grant your app the 'Special app access'.

https://developer.android.com/training/data-storage/shared/media#management-permission

**Comment by AkhilRamani** [comment]
I have same issue. I do not have issues with additional pop of asking permission for modify media (Which is delete). But have major issue is that, when user denies in that popup, app crashes even if I wrapped method in try catch block. Any solution to this issue?

Thus, right now only usable method is to save to DCIM. Or else there is possibilities of app crash.

**Comment by Hosam-hsm** [comment]
Anyone got a solution without asking extra permission?
