### ISSUE TITLE
Navigating to another tab nested route breaks the Tab

### ISSUE THREAD

**Issue by jaslloyd** [expo/expo#24597]
### Minimal reproducible example

[Reproducible example](https://github.com/jaslloyd/expo-router-broken)

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

TLDR; Navigating (aka using link component) from one tab (e.g home / pathname: (tabs)) to another tab (e.g play) nested route aka pathname:  '/(tabs)/play/[game_id]', breaks the play tab (aka you can never load the play tab only the child nested route). Also seeing inconsistent behaviours with the 'back' buttons

This is very hard to explain so see video.

I have worked off the tabs example in the docs and modified it a tiny bit to have a structure I want, Here is my directory structure / routing layout:

```sh
├── (tabs)
│   ├── _layout.tsx
│   ├── index.tsx
│   └── play
│       ├── [game_id]
│       │   ├── index.tsx
│       │   └── lobby.tsx
│       ├── _layout.tsx
│       └── index.tsx
├── +html.tsx
├── [...missing].tsx
├── _layout.tsx
├── assets
│   ├── favicon.png
│   ├── icon.png
│   └── splash.png
└── modal.tsx
```

(tabs)/index.ts looks like this:

```tsx
    <View style={styles.container}>
      <Text style={styles.title}>Home</Text>
      <View style={styles.separator} lightColor="#eee" darkColor="rgba(255,255,255,0.1)" />

      <Link
        href={{
          pathname: '/(tabs)/play/[game_id]',
          params: { game_id: '123' },
        }}
      >
        <Text>Click to go to Game details</Text>
      </Link>
    </View>
```

Have a link into the 'Play' tab into the "game" id screen, when I first load the app (or reload) if i click the link straight away it brings me to the correct screen [game_id]/index.tsx inside the 'play' tab (without back button) if I tab back to 'Home' and then tab back to 'Play' the play screen no longer loads, its stuck on the [game_id] screen. I tried clicking the tab multiple times but i cannot get to the play screen. (Please see video)

https://github.com/expo/expo/assets/3710874/3f9f2847-136d-4a96-a9de-487a39ee70b1

Now another thing, if I reload the app click on the 'Play' tab then click back on 'Home' then click the Link to 'Go to game details' it t brings me to the correct screen [game_id]/index.tsx inside the 'play' tab this time with the back button (to play) but also double tapping the 'Play' tab also goes back to the 'play' route. (aka working perfectly)

Video below

https://github.com/expo/expo/assets/3710874/3927ca2e-a218-4fa1-a152-5230f7250a50

I am pretty new to expo-router and I am trying to understand what I am doing wrong.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by marklawlor** [comment]
Please comment when you have pushed the reproduction and I'll investigate the issue :+1:

**Comment by jaslloyd** [comment]
@marklawlor should be there now!

**Comment by marklawlor** [comment]
@jaslloyd It doesn't appear that the repo is updated. But can you please try `2.0.8` as it contains fixes that may resolve this issue

**Comment by jaslloyd** [comment]
I am going to close this issue, I had to nuke my machine and I had the reproducible example on it and honestly its a bit of pain to recreate, if i run into it again when i get around to recreating a similar version i will open a new ticket.
