### ISSUE TITLE
Web hosted throws unknown error

### ISSUE THREAD

**Issue by alexborton** [expo/expo#24596]
### Minimal reproducible example

https://github.com/alexborton/expo-router-basic

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

After exporting to a production build for web, it errors when hosted. I have tried this on Firebase and Amplify (the linked repo is Amplify) and both just show the "something went wrong" error. 

Not sure best way to debug this issue. The linked repo is straight out the create app setup for getting started; all i have added the amplify yml. 

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Can you please link your hosted site so we can inspect the error.

**Comment by alexborton** [comment]
> Can you please link your hosted site so we can inspect the error.

Of course; https://main.d3cr97bre6d4ws.amplifyapp.com/

**Comment by EvanBacon** [comment]
If I build this locally and host it with `npx expo export -p web && npx serve dist -l 3000` then everything seems fine. This makes me think it's an issue with whatever you're doing to deploy to Amplify. Perhaps the amplify configuration is somehow ignoring the assets under `dist/assets/node_modules/`.

**Comment by alexborton** [comment]
> If I build this locally and host it with `npx expo export -p web && npx serve dist -l 3000` then everything seems fine. This makes me think it's an issue with whatever you're doing to deploy to Amplify. Perhaps the amplify configuration is somehow ignoring the assets under `dist/assets/node_modules/`.

I had wondered the same thing, which is why i tried to deploy on both Amplify and Firebase hosting, but both had the same result (Error as seen in the link above).

If that is the case, is there some [additional steps from the documentation](https://docs.expo.dev/distribution/publishing-websites/) that need to be taken in order to resolve this?

**Comment by alexborton** [comment]
In fact, @EvanBacon you are exactly right - although it's not clear from the documentation (or the error messaging) that this is the case. 

A standard `.gitignore` ignores `node_modules/` which also means the `dist/assets/node_modules/` is ignored. Fine tuning the `.gitignore` should fix this for all. 

In my case, this is now fixed - thanks! 🎉  

Maybe a little document update, or boilerplate `.gitignore` needs to be tweaked?

**Comment by EvanBacon** [comment]
@alexborton would you be willing to open a PR to update the publishing websites doc? https://docs.expo.dev/distribution/publishing-websites/ otherwise I don't think there's any bug here that we can fix at the moment.
