### ISSUE TITLE
Replace BlurView with react-native-blur

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2459]
This is more commonly used by the community and would make interop with other libraries easier, for example it's the only dependency of https://github.com/wix/react-native-ui-lib. Alternatively we could add another babel alias so that react-native-blur is remapped to a shim over Expo BlurView.

**Comment by ide** [comment]
We did this and looking at r-n-blur's implementation, I think we should revert. We need the API to be kept stable and for the implementation to meet our quality bar and support web as well.

**Comment by moxorama** [comment]
I think it would be good to have both implementations, and mark old as [deprecated]

**Comment by ide** [comment]
@moxorama To work efficiently we're supporting just one API (and three implementations: iOS, Android, web), which is the original expo-blur.

**Comment by ide** [comment]
Closing this out since expo-blur supports TypeScript, is tri-platform, and is part of the Foundation Unimodules.

**Comment by moxorama** [comment]
The real problem is opacity instead of blur on Android on current Expo component

**Comment by brentvatne** [comment]
i agree, we should add that at some point - https://expo.canny.io/feature-requests/p/blurview-on-android

**Comment by moxorama** [comment]
Native Android implementation: https://github.com/500px/500px-android-blur
