### ISSUE TITLE
[Expo 49, Expo Updates, Android] `./gradlew assembleRelease` fails with an error "Cannot query the value of extension 'react' property 'entryFile' because it has no value available."

### ISSUE THREAD

**Issue by 7dp** [expo/expo#24590]
### Minimal reproducible example

https://github.com/7dp/ExpoUpdates

### Summary

**Problem:**

Generating apk fails, due to the error:
```groovy
> Configure project :app
 ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.13)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot query the value of extension 'react' property 'entryFile' because it has no value available.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 10s
10 actionable tasks: 10 executed
```

**Steps to reproduce:**

1. init new **bare** RN project (npx react-native@latest init ExpoUpdates)
2. add & configure release keystore
3. i test it with running `./gradlew assembleRelease`, and it generate apk succesfully
4. install expo modules by running `npx install-expo-modules@latest`
5. i test it again with `./gradlew assembleRelease`, and it generate apk succesfully
--
6. install & configure expo-updates according to the docs
7. i test it again with `./gradlew assembleRelease`, and now build apk fails with the error mentioned above

**Expectation:**
It should generate the apk.

**Deps:**
```json
"dependencies": {
    "expo": "^49.0.0",
    "expo-updates": "~0.18.13",
    "react": "18.2.0",
    "react-native": "0.72.4"
  },
```

Any help from the Expo team would me much appreciated😊, and sorry for my English🙏.

### Environment

```bash
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.08.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: bare
```

**Comment by Kudo** [comment]
hi there!

applying this patch should work for you

```diff
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -1,11 +1,14 @@
 apply plugin: "com.android.application"
 apply plugin: "com.facebook.react"

+def projectRoot = rootDir.getAbsoluteFile().getParentFile().getAbsolutePath()
+
 /**
  * This is the configuration block to customize your React Native Android app.
  * By default you don't need to apply any configuration, just uncomment the lines you need.
  */
 react {
+    entryFile = file(["node", "-e", "require('expo/scripts/resolveAppEntry')", projectRoot, "android", "absolute"].execute(null, rootDir).text.trim())
     /* Folders */
     //   The root of your project, i.e. where "package.json" lives. Default is '..'
     // root = file("../")
@@ -85,6 +88,7 @@ android {
         targetSdkVersion rootProject.ext.targetSdkVersion
         versionCode 1
         versionName "1.0"
+        buildConfigField("boolean", "REACT_NATIVE_UNSTABLE_USE_RUNTIME_SCHEDULER_ALWAYS", (findProperty("reactNative.unstable_useRuntimeSchedulerAlways") ?: true).toString())
     }
     signingConfigs {
         debug {
--- a/metro.config.js
+++ b/metro.config.js
@@ -1,4 +1,5 @@
-const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
+const {mergeConfig} = require('@react-native/metro-config');
+const {getDefaultConfig} = require('expo/metro-config');

 /**
  * Metro configuration
```

however, for expo-updates, we highly recommend to create the project from `yarn create expo`. because expo-updates used to rely on some cli features or need further configurations.

**Comment by 7dp** [comment]
Your patch works good, thanks for your help Kudo!

**Comment by 7dp** [comment]
Hi Kudo and the Expo team.

**Problem:**
I have a new problem when i have expo-updates and above patch implemented in my code. When I build Android apk by running `cd android; ./gradlew assembleRelease; cd ..` the apk is generated successfully, buuut.. the image resource is not appear on the welcome screen.

Note: when i run the app directly to my device the image resource is appear.

Then, I tried to remove both `expo-updates` lib and above patch then build the apk again. The apk generated successfully and my image resource is appear on the welcome screen.

**Expectation:**
My image resource should appear on the screen when using `expo-updates` and above patch on the generated apk (`cd android; ./gradlew assembleRelease; cd ..`).

**Repro:**
The repro still in the same repo like my initial comment. I create a new branch `no-expo-updates` where i remove both `expo-updates` lib and the above patch.


Any help from Expo team is very appreciated. Thanks.

**Comment by Kudo** [comment]
@7dp sorry that expo-updates typically requires more integration and good for `yarn create expo` project (generated from our template). for what i can tell, please try to do the following steps:
1. remove `index.js`
2. update package.json
```diff
diff --git a/package.json b/package.json
index 504595f..d236abd 100644
--- a/package.json
+++ b/package.json
@@ -2,6 +2,7 @@
   "name": "ExpoUpdates",
   "version": "0.0.1",
   "private": true,
+  "main": "node_modules/expo/AppEntry.js",
   "scripts": {
     "android": "react-native run-android",
     "ios": "react-native run-ios",
```

**Comment by 7dp** [comment]
Thx Kudo for the reply.
I remove index.js file and update package.json, along with your previous patch implemented, but the generated apk is now crashing on launch. Can you help me further with that?

**Comment by 7dp** [comment]
Hi @Kudo and the Expo team. 
Is there any solid solution about the last issue yet?
If there's no solution, i think it would be better to reopen this.

**Comment by Kudo** [comment]
@7dp sorry for the late response. here is a working project based on your repro: https://github.com/7dp/ExpoUpdates/compare/main...Kudo:ExpoRepro-Updates:main

i don't know what's the exact root cause but i tend to run `npx expo prebuild -p android --clean` to sync the template difference. hopes that work for you.

**Comment by 7dp** [comment]
Thank you so much Kudo! Appreciate that.
