### ISSUE TITLE
Building for iOS with Xcode 15 on SDK 48

### ISSUE THREAD

**Issue by hbiede** [expo/expo#24608]
### Summary

Unable to build SDK 48 with XCode 15 using `expo run:ios`. This has been fixed by React Native, but it requires Expo to update from RN 0.71.8 to ~0.71.11. Currently it yields this result if you attempt:

```
❌  (ios/Pods/boost/boost/container_hash/hash.hpp:131:33)

  129 | #else
  130 |         template <typename T>
> 131 |         struct hash_base : std::unary_function<T, std::size_t> {};
      |                                 ^ no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  132 | #endif
  133 | 
  134 |         struct enable_hash_value { typedef std::size_t type; };
```

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 3.6.1 - /usr/local/bin/fish
    Binaries:
      Node: 18.16.1 - /usr/local/opt/node@18/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/opt/node@18/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.2, 30.0.3, 33.0.0, 33.0.2, 34.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    Expo Workflow: managed
```

### Minimal reproducible example

The `blank@48` template. This works fine on Expo 49 already

**Comment by Kudo** [comment]
hi there! we will have another react-native 0.71 bump once 0.71.14 released. because there was a ios <= 14 runtime crash when building on xcode 15.
if you only want fix the build failure, please patch locally as this https://github.com/facebook/react-native/commit/5bd1a4256e0f55bada2b3c277e1dc8aba67a57ce

**Comment by ngima** [comment]
> hi there! we will have another react-native 0.71 bump once 0.71.14 released. because there was a ios <= 14 runtime crash when building on xcode 15. if you only want fix the build failure, please patch locally as this [facebook/react-native@5bd1a42](https://github.com/facebook/react-native/commit/5bd1a4256e0f55bada2b3c277e1dc8aba67a57ce)

Hi @Kudo thanks for info. Could you tell me, how can we do in the expo managed flow?

**Comment by ngima** [comment]
seems like the patch is already included in ```0.71.13```

**Comment by ngima** [comment]
I just had to change the `image: latest` to `image: default`

**Comment by bmewada** [comment]
@ngima  you able to find any solution

**Comment by Kudo** [comment]
we've published new templates for sdk-48 with react-native@0.71.14. that should fix the issue. running `npx expo prebuild -p ios --clean` to pull in updated template should fix the problem. thanks!
