### ISSUE TITLE
[Android] Add support for app shortcuts

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#2461]
### Proposal

Let's add support for [`app shortcuts`](https://developer.android.com/guide/topics/ui/shortcuts) on Android devices.
Here's [some library](https://github.com/lokyoung/react-native-app-shortcuts) for react-native already.

**Comment by EvanBacon** [comment]
Tracking on canny https://expo.canny.io/feature-requests/p/app-shortcuts
