### ISSUE TITLE
expo image place holder

### ISSUE THREAD

**Issue by MohamedWageh19** [expo/expo#24621]
### Summary

content fit doesn't apply on placeholder image no effect on the placeholder by style

### What platform(s) does this occur on?

Android, iOS

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD    
    npmPackages:
      expo: ^49.0.11 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Minimal reproducible example

<Image
                      placeholder={require("../../assets/blankthumbnail.png")}
                      contentFit="cover"
                      style={globalStyles.requestDescriptionCardImage}
/>

**Comment by delandchen** [comment]
I have the same issue. 'contentFit', the deprecated 'resizeMode' and regular CSS styling has no affect on the placeholder. My temporary solution is to just do a simple check:

`<Image
  style={styles.accountProfileImage}
  source={image ? { uri: image } : placeholderImage}
  contentFit={"cover"}
/>`

**Comment by behenate** [comment]
Hi, this issue seems to be caused by our documentation being unclear. For placeholder you should use `placeholderContentFit` prop.
