### ISSUE TITLE
[Expo-AV][Android] Can't recording

### ISSUE THREAD

**Issue by thanhloc-17** [expo/expo#24629]
### Minimal reproducible example

none

### Summary

Hi,

This issue occurr when I use **createAsync** or **prepareToRecordAsync**:

```javascript
[Error: Call to function 'ExponentAV.prepareAudioRecorder' has been rejected.
→ Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String expo.modules.core.arguments.ReadableArguments.getString(java.lang.String)' on a null object reference]
```

There's my code, I make sure that I allow all the permission necessary.
```javascript
import {Audio} from 'expo-av';

...

await Audio.setAudioModeAsync({
  allowsRecordingIOS: true,
  playsInSilentModeIOS: true,
});
const audioRecord = await Audio.Recording.createAsync(Audio.RecordingOptionsPresets.HIGH_QUALITY);
```

This packages.json:
```
"expo": "^50.0.0-alpha.5",
"expo-asset": "^8.12.1",
"expo-av": "^13.7.0",
"expo-font": "^11.7.0",
"expo-image": "^1.5.2",
"expo-keep-awake": "^12.6.0",
"expo-location": "^16.3.0",
"expo-media-library": "^15.6.0",
"expo-splash-screen": "^0.23.1",
"react-native": "0.72.5",
...
```

### Environment

System:
  OS: macOS 14.0
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.13.0
  Yarn: 1.22.19
  npm: 8.19.3
  Watchman: 2023.02.20.00
Managers:
  CocoaPods: 1.12.0
  Ruby: 2.7.6
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9477386
  Xcode: 15.0/15A5195m - /usr/bin/xcodebuild
npmPackages:
  babel-preset-expo: ^9.5.2 => 9.5.2 
  expo: ^50.0.0-alpha.5 => 50.0.0-alpha.5 
  react: 18.2.0 => 18.2.0 
  react-native: 0.72.5 => 0.72.5 
npmGlobalPackages:
  expo-cli: 6.3.8
Expo Workflow: bare

**Comment by thanhloc-17** [comment]
up, it's obviously bug

**Comment by VictorioMolina** [comment]
same problem here

**Comment by jobpaardekooper** [comment]
Can confirm this issue. Reverting to `13.4.1` like mentioned by @VictorioMolina also works for now.

Understandable that expo wants a reproduction repository with the issue but automatically closing everything is not the way to go in my opinion. Especially "closed as completed". This is a genuine issue. One of the main features of the `expo-av` package is just completely broken on its latest version and the issue just gets auto closed.

Would also be nice to have at lease some thing on these features to prevent such obvious issue in the future.

@thanhloc-17 Do you have time to add a repo to this so it will be reopened and someone at expo might actually see it?

Also maybe change the title to for example:
```
[expo-av][Android] prepareToRecordAsync consistently throws native NullPointerException 
```

**Comment by nemoneph** [comment]
I also confirm the issue.
Very annonying.

Reverting to 13.4.1 works and confirm the regression.

**Comment by crystalarcus** [comment]
Any updates on this ? I just got this error in Android 13 phone :
```
 ERROR  Failed to start recording [Error: Call to function 'ExponentAV.setAudioMode' has been rejected.
→ Caused by: The 1st argument cannot be cast to type expo.modules.core.arguments.ReadableArguments (received Map) 
→ Caused by: Cannot find type converter for 'expo.modules.core.arguments.ReadableArguments'.]
```

Firstly I thought this was due to permission being denied, so I checked app's permission to microphone, but its allowed. I reinstalled the app, but same. 

SURPRISINGLY, this error didn't occur on my old Android 9 phone. It's same development build used on Android 13 device.
Its running well in Expo Go app.
