### ISSUE TITLE
<img width="861" alt="screen shot 2561-05-11 at 08 49 17" src="https://user-images.githubusercontent.com/30209508/39902484-654ebcf8-54f8-11e8-89f2-33890160cd81.png">

### ISSUE THREAD

**Issue by orsospatrick** [expo/expo#2463]
Hi @dsokal , i am using the latest version ie 53.1.0 exp publish but still having the above problem.

_Originally posted by @vtn-dev2016 in https://github.com/expo/expo/issues/1715#issuecomment-388235864_

I have same problem,did you solved this ?

**Comment by quinlanj** [comment]
Hi, we use expo/expo issues to track bugs in our sdk. Could you please post your problem in https://forums.expo.io and tell us the steps you took to get this error? Make sure you are running the newest version of expo-cli (it is no longer exp). You can download this by running `npm install -g expo-cli` and then running `expo publish <extra args>`

**Comment by orsospatrick** [comment]
Thank you, I solved it. 

Trimis din Yahoo Mail pe Android 
 
  Pe vin., oct. 19, 2018 la 21:09, quinlanj<notifications@github.com> a scris:   
Hi, we use expo/expo issues to track bugs in our sdk. Could you please post your problem in https://forums.expo.io and tell us the steps you took to get this error? Make sure you are running the newest version of expo-cli (it is no longer exp). You can download this by running npm install -g expo-cli and then running expo publish <extra args>
