### ISSUE TITLE
expo-image-picker: missing mimeType and name

### ISSUE THREAD

**Issue by hirbod** [expo/expo#24630]
### Minimal reproducible example

https://snack.expo.dev/@hirbod/crabby-orange-peach

### Summary

`expo-image-picker` and `expo-documents-picker` share an almost identical result API. The main difference between the two is that `expo-documents-picker` provides a file mime-type and name (file name), while `expo-image-picker` does not. Although this could be considered a feature request, I believe adding mimeType support to `expo-image-picker` would be beneficial. This is also the case for web, which makes uploading difficult, since it only contains uri with base64 and forces me to detect the type and generate a name and an extension.

On native, expo-image-picker does return the fileName though. (but does not on web)

We are building a UI with optimistic updates and making decisions based on mimeType. Right now, I have to estimate or simulate those for data obtained through `expo-image-picker` (both from the camera and selected files). In contrast, `expo-documents-picker` returns the mimeType and the file name, which simplifies the process.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 3.5.0 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.15.1
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by hirbod** [comment]
Well that was crazy fast, thanks @alanjhughes

**Comment by alanjhughes** [comment]
No problem @hirbod 👍

**Comment by dhcmega** [comment]
Hi! how can I get this commit in my SDK49 app? Do I have to update or would I need to generate a patch? Thanks!

**Comment by pgeimer** [comment]
@dhcmega You have to install version `14.6.0` of `expo-image-picker`.

**Comment by dhcmega** [comment]
@pgeimer thank you. I have 14.3.2, which is the "official" version for SDK49.
how do I upgrade it to the latest version compatible with sdk49, and btw, is there a way to update all expo packages at once?
thanks a lot

**Comment by pgeimer** [comment]
I just manually updated the package: 

`yarn add expo-image-picker@14.6.0`

And yes, I get the warning that this version of `expo-image-picker` is not compatible with version 49 of the SDK. For now, you have to live with the warning. Updating all the packages at once is just happening on the expo version upgrade.

**Comment by dhcmega** [comment]
ok perfect! thank you. I'm getting the same warning, but will ignore it.
For reference:

`
Some dependencies are incompatible with the installed expo version:
[RUN_EXPO_DOCTOR]   expo-image-picker@14.6.0 - expected version: ~14.3.2
`

**Comment by hirbod** [comment]
@alanjhughes, sorry for pinging you on this old thread, but would you consider making both result APIs even closer to each other? I figured that expo-documents-picker returns `size`, while expo-image-picker returns `fileSize`. This requires additional code adjustments. I think both naming conventions should be as close as possible.

**Comment by alanjhughes** [comment]
@hirbod - that makes sense. I'll take a look at aligning them as much as possible. Initially, this will mean some duplication and deprecation warnings for one SDK cycle.

**Comment by jamiechong** [comment]
@alanjhughes  I'm using expo-image-picker@14.6.0, but `mimeType` is undefined. This must not be available in Expo SDK49? (I'm on 49.0.21).

**Comment by alanjhughes** [comment]
@jamiechong - are you using expo go?

**Comment by jamiechong** [comment]
@alanjhughes yes I am. And I guess that makes sense as to why it’s not working!

**Comment by sirshad01** [comment]
@alanjhughes mimeType and fileName both are undefined when using Expo Go on iOS. Can we expect it to be working on real device?
