### ISSUE TITLE
[docs] Native Modules, Native Views and Swift Integration Tutorial Updates

### ISSUE THREAD

**Issue by uhrohraggy** [expo/expo#24644]
### Summary

What I found confusing (for now focusing on iOS) building a native module using Swift... I'd like to update the template generator and docs on these topics and open a PR for it, but need some buy-in/discussion from the community on the best direction to take.

- The tutorial for Native Views implements an iframe WebView, which conflates a Native View as just used for WebViews instead of a general SwiftUI `View`. Most of the time Web Views are rejected during App Store review, so some other example may be better suited
- There is a note on future support for SwiftUI View into UIKit UIView using `UIHostingController` without context, which assumes a longer knowledge of iOS development. A lot of expo developers may be experiencing native development for the first time, so it's high hurdle especially given Apple's (IMO terrible) developer docs and I myself found myself struggling to get the Native View to appear within my app (it was behind other Stacks, simple if you've developed in iOS but way confusing otherwise)
- Full end-to-end examples of events dispatching from iOS to RN and from RN to iOS
- More complex examples of passing parameters to Native Modules, Native Views, and (more likely) a model `class`
- Reviewing current `expo` packages that provide a native view in Swift is hard to find, most of them use C or a built in Apple controller like `AVPlayerViewController`
- In our particular case, we need to have two different Views emitted from within the same pod, we tried within the same Module, which didn't work, so then added a separate Module with a new `Name(..)` defined, a separate View field, updated index.ts to ensure it's exported, but unfortunately the new Module wasn't exported to the NativeViewManager, so was not accessible. Obviously, creating separate pods worked, but I'd like to share modeling between the views that my pod should care about. Are multiple Views within the same Module (or same emitted pod) supported?

### Link to the related docs page

https://docs.expo.dev/modules/native-view-tutorial/

### Anything else?

I'm really looking for support or rejection whether this is worthwhile to explore futher.

**Comment by alaughlin** [comment]
@uhrohraggy are you able to share a simple example of how you managed to get some SwiftUI into an Expo app? I am struggling myself just trying to get a SwiftUI button onto the screen with a custom native module with errors like:

```The native view manager required by name (NativeButton) from NativeViewManagerAdapter isn't exported by expo-modules-core.```

Also I know this thread was closed but +1'ing it anyways.
