### ISSUE TITLE
Calendar permission and notification not working on ios 17 and expo 49

### ISSUE THREAD

**Issue by shanoysinc** [expo/expo#24648]
### Minimal reproducible example

whenever i try to request calendar permission i get this error

### Summary

![Simulator Screenshot - iPhone 11 Pro - 2023-09-27 at 09 36 26](https://github.com/expo/expo/assets/10425073/e61b8536-4ec0-4c8f-b6e7-809edf9c97f1)
<img width="1440" alt="Screenshot 2023-09-27 at 7 05 41 PM" src="https://github.com/expo/expo/assets/10425073/5160cedf-046a-4941-9184-8a75a14a4e1c">

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.13 => 49.0.13
      react: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
This will be resolved when we release a version of `expo-calendar` with this change #24655

**Comment by shanoysinc** [comment]
@alanjhughes any idea when the new version will be released?

**Comment by alanjhughes** [comment]
`11.3.2` should be available now
