### ISSUE TITLE
Hi guys. I have a similar error.

### ISSUE THREAD

**Issue by orsospatrick** [expo/expo#2464]
Can you please help me?

![screenshot_5](https://user-images.githubusercontent.com/7090093/44351967-b94d1680-a4ab-11e8-9f07-a909141d2605.png)

_Originally posted by @javadoffuad in https://github.com/expo/expo/issues/1715#issuecomment-414371123_

**Comment by quinlanj** [comment]
Hi, we use expo/expo issues to track bugs in our sdk. Could you please post your problem in https://forums.expo.io and tell us the steps you took to get this error? Make sure you are running the newest version of expo-cli (it is no longer `exp`). You can download this by running `npm install -g expo-cli` and then running `expo build:ios`
