### ISSUE TITLE
Hi @sergioalvz,,Did you solved this problem? How?

### ISSUE THREAD

**Issue by orsospatrick** [expo/expo#2465]
Could you please tell me which version of `exp` are you using (exp --version)? If it's not the latest (53.1.0), could you upgrade it and check if the error still exists?

_Originally posted by @dsokal in https://github.com/expo/expo/issues/1715#issuecomment-385904553_

**Comment by quinlanj** [comment]
Hi, https://github.com/expo/expo/issues/1715 looks like it has been solved and the linked comment sufficiently answered. Closing this issue - if there are any additional problems please follow the template format and we will try our best to address the problem.
