### ISSUE TITLE
I already Update my SDK to 48 but mi API level is 21 

### ISSUE THREAD

**Issue by Imontecinosv** [expo/expo#24651]
### Minimal reproducible example

Yesterday I make the update of my SDK from 36 to 38, but when I create the new build for android and update this on google play store the API level is 21 

### Summary

The problem is that I have a warning in the Google Play Store
![image](https://github.com/expo/expo/assets/97743117/facca1ae-e1f8-4401-b100-581c970f9f25)

 because the API level of my build is 21 and now I need to update this to the 31 level or more, I was researching how I can update the API level and I found that I only need to update my SDK, but this doesn't work because the API level of my new build is still 21 
![image](https://github.com/expo/expo/assets/97743117/8d6dac74-56a3-4578-806e-823d5c35994e)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 5.3.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi @Imontecinosv - The target being 33 is all that is required to meet the criteria. Upgrading to 48 should pass their review. Submit a new build with 48. The warning won't disappear immediately. You need to release the new version for it to clear

**Comment by Imontecinosv** [comment]
Hi @alanjhughes, Yesterday I uploaded and published my new build, I verified today at morning and now I don't have a warning from the Google Play Store.
Thank you so much!

**Comment by alanjhughes** [comment]
Great 👍
