### ISSUE TITLE
[expo-image-picker] [android] EXIF GPS location broken in some Android devices

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#24652]
### Minimal reproducible example

https://snack.expo.dev/@brodanoel/spunky-indigo-truffles

### Summary

The snack provided should be enough to reproduce it, but I'm not able to upload the 3 files I will provide below, in order to pick them up with `expo-image-picker`.

Also, this error seem to be related to the device + android version, and I'm not able to switch those values on Snack.

### The context
A user of my app (we'll call him `mornad`) uploads ~10 photos per week, since 3 years ago.

Some weeks ago, he uploaded 3 photos, using a Xiaomi with Android 12. Those 3 photos has EXIF GPS information, and my app could get those values.

Some days ago, after struggling a lot some some issues (https://github.com/expo/expo/issues/24125), I upgraded `expo-image-picker` to `14.5.0`.

After this new upgrade, `mornad` is not able to upload photos to my app (in my app, you can't upload images if there are no GPS information inside its EXIF) (yes, of course, if the photos doesn't have that info I allow the user to pick the place in a map, but forget about that).

I told `mornad`: "Try to upload some of the old photos that we know they were working before". He did it.

Here are 3 photos, where you can see the EXIF GPS info inside, that currently ARE NOT WORKING on his device (`Xiaomi Mi 10T Pro`, `android 12`)

[mornad.zip](https://github.com/expo/expo/files/12744989/mornad.zip)

Inside that zip you will find 3 photos and 1 .txt file, with the current EXIF information that my app is getting for those 3 photos, which is this content:

```
// photo 1
{
  "exif": {
    "ApertureValue": 1.514,
    "ExifVersion": "0220",
    "GPSLatitude": 0,
    "Compression": 6,
    "JPEGInterchangeFormat": 1126,
    "GPSAltitude": 0,
    "ExposureProgram": 2,
    "GPSAltitudeRef": 0,
    "GPSProcessingMethod": "",
    "ColorSpace": 1,
    "GPSTimeStamp": "00:00:00",
    "DateTime": "2023:08:12 10:09:08",
    "BrightnessValue": 6.36,
    "YResolution": 72,
    "SubSecTimeOriginal": "510",
    "ExposureMode": 0,
    "ImageWidth": 3240,
    "ExposureTime": 0.0009,
    "SubSecTime": "510",
    "FNumber": 1.69,
    "GPSLongitudeRef": "",
    "FocalLengthIn35mmFilm": 24,
    "Make": "Xiaomi",
    "Orientation": 0,
    "InteroperabilityIndex": "R98",
    "DateTimeDigitized": "2023:08:12 10:09:08",
    "XResolution": 72,
    "FocalLength": 6.72,
    "MeteringMode": 2,
    "SceneCaptureType": 0,
    "SubjectDistanceRange": 3,
    "SceneType": "1",
    "ExposureBiasValue": 0,
    "SubjectDistance": 3.203,
    "MaxApertureValue": 1.514,
    "ImageLength": 5760,
    "GPSDateStamp": "",
    "FlashpixVersion": "0100",
    "DateTimeOriginal": "2023:08:12 10:09:08",
    "WhiteBalance": 0,
    "GPSLatitudeRef": "",
    "YCbCrPositioning": 1,
    "Flash": 16,
    "ISOSpeedRatings": 50,
    "JPEGInterchangeFormatLength": 9652,
    "ComponentsConfiguration": "???",
    "GPSLongitude": 0,
    "SubSecTimeDigitized": "510",
    "DigitalZoomRatio": 1.576,
    "ShutterSpeedValue": 10.1372,
    "Model": "M2007J3SG",
    "ResolutionUnit": 2,
    "LightSource": 21,
    "SensingMethod": 1,
    "assetData": {}
  }
}

// photo 2
{
  "exif": {
    "ApertureValue": 2.5261,
    "ExifVersion": "0220",
    "GPSLatitude": 0,
    "Compression": 6,
    "JPEGInterchangeFormat": 1126,
    "GPSAltitude": 0,
    "ExposureProgram": 2,
    "GPSAltitudeRef": 0,
    "GPSProcessingMethod": "",
    "ColorSpace": 1,
    "GPSTimeStamp": "00:00:00",
    "DateTime": "2023:07:16 14:35:44",
    "BrightnessValue": 7.79,
    "YResolution": 72,
    "SubSecTimeOriginal": "179",
    "ExposureMode": 0,
    "ImageWidth": 4096,
    "ExposureTime": 0.0018,
    "SubSecTime": "179",
    "FNumber": 2.4,
    "GPSLongitudeRef": "",
    "FocalLengthIn35mmFilm": 8,
    "Make": "Xiaomi",
    "Orientation": 0,
    "InteroperabilityIndex": "R98",
    "DateTimeDigitized": "2023:07:16 14:35:44",
    "XResolution": 72,
    "FocalLength": 2.13,
    "MeteringMode": 2,
    "SceneCaptureType": 0,
    "SubjectDistanceRange": 1,
    "SceneType": "1",
    "ExposureBiasValue": 0,
    "SubjectDistance": 0.1,
    "MaxApertureValue": 1.514,
    "ImageLength": 2304,
    "GPSDateStamp": "",
    "FlashpixVersion": "0100",
    "DateTimeOriginal": "2023:07:16 14:35:44",
    "WhiteBalance": 0,
    "GPSLatitudeRef": "",
    "YCbCrPositioning": 1,
    "Flash": 16,
    "ISOSpeedRatings": 50,
    "JPEGInterchangeFormatLength": 11925,
    "ComponentsConfiguration": "???",
    "GPSLongitude": 0,
    "SubSecTimeDigitized": "179",
    "DigitalZoomRatio": 2.8923,
    "ShutterSpeedValue": 9.15,
    "Model": "M2007J3SG",
    "ResolutionUnit": 2,
    "LightSource": 21,
    "SensingMethod": 1,
    "assetData": {}
  },
}

// photo 3
{
  "exif": {
    "ApertureValue": 1.514,
    "ExifVersion": "0220",
    "GPSLatitude": 0,
    "Compression": 6,
    "JPEGInterchangeFormat": 1126,
    "GPSAltitude": 0,
    "ExposureProgram": 2,
    "GPSAltitudeRef": 0,
    "GPSProcessingMethod": "",
    "ColorSpace": 1,
    "GPSTimeStamp": "00:00:00",
    "DateTime": "2023:09:15 11:28:43",
    "BrightnessValue": 7.17,
    "YResolution": 72,
    "SubSecTimeOriginal": "407",
    "ExposureMode": 0,
    "ImageWidth": 5760,
    "ExposureTime": 0.0004,
    "SubSecTime": "407",
    "FNumber": 1.69,
    "GPSLongitudeRef": "",
    "FocalLengthIn35mmFilm": 24,
    "Make": "Xiaomi",
    "Orientation": 0,
    "InteroperabilityIndex": "R98",
    "DateTimeDigitized": "2023:09:15 11:28:43",
    "XResolution": 72,
    "FocalLength": 6.72,
    "MeteringMode": 2,
    "SceneCaptureType": 0,
    "SubjectDistanceRange": 3,
    "SceneType": "1",
    "ExposureBiasValue": 0,
    "SubjectDistance": 3.028,
    "MaxApertureValue": 1.514,
    "ImageLength": 3240,
    "GPSDateStamp": "",
    "FlashpixVersion": "0100",
    "DateTimeOriginal": "2023:09:15 11:28:43",
    "WhiteBalance": 0,
    "GPSLatitudeRef": "",
    "YCbCrPositioning": 1,
    "Flash": 16,
    "ISOSpeedRatings": 50,
    "JPEGInterchangeFormatLength": 12283,
    "ComponentsConfiguration": "???",
    "GPSLongitude": 0,
    "SubSecTimeDigitized": "407",
    "DigitalZoomRatio": 1.2954,
    "ShutterSpeedValue": 11.4379,
    "Model": "M2007J3SG",
    "ResolutionUnit": 2,
    "LightSource": 21,
    "SensingMethod": 1,
    "assetData": {},
  },
}
```

As you can see, `GPSLatitude` and `GPSLongitude` is always `0`. 

Something important: If you try to upload those files on iOS, they work. The app can find the real `GPSLatitude` and `GPSLongitude` in the photos (I tested it on my iPhone)

### The error
Well... The GPS info is not working anymore :(

Do you have any idea how can I help to reproduce this? BrowserStack doesn't have any Xiaomi, and Snack does not allow me to switch devices.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.7
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.9 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    npmGlobalPackages:
      eas-cli: 5.3.0
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by BrodaNoel** [comment]
Any news here? This seems to be affecting more Android devices as I was expecting.
The amount of users uploading photos in my app, from Android, decreased in ~80%

**Comment by BrodaNoel** [comment]
As @alanjhughes reported in Discord, this issue is actually an expected behavior from Google: https://issuetracker.google.com/issues/243294058?pli=1

(which... I can't believe)

**Comment by BrodaNoel** [comment]
If somebody have an idea about how to create a workaround for this, please let me know.

1. Can we switch back to the old picker? What are we going to lose in that case?
2. Is there a way where I create my own File Picker? Will this fix the problem? What are we going to lose in this case?

Thanks!

**Comment by BrodaNoel** [comment]
As far as I see, the new picker was implemented on [14.3.0 — 2023-06-13](https://github.com/expo/expo/blob/main/packages/expo-image-picker/CHANGELOG.md#1430--2023-06-13).

What if we rollback to the previous version?

**Comment by alanjhughes** [comment]
@BrodaNoel its not as straight forward as that. There are changes in Android 14 that require new permissions that would mean asking the user every time they want to select a photo because they can change their decision at any time. It’s a poor UX and an intentional decision from google to get people to move to the new picker that doesn’t require doing this.

**Comment by marco2216** [comment]
I don't know if switching to the old picker is the solution, but I think there's more issues with this new picker: see e.g. the discussion in this thread: https://github.com/expo/expo/issues/20482
We have 1.3k events from 183 users over the last few months of this FailedToDeduceTypeException error. I think it has something to do with the new picker as it started happening after our upgrade to Expo 49.

**Comment by BrodaNoel** [comment]
@alanjhughes in my case, the poor UX is even worst without EXIF>location, because if the photo has not location, I have to show a map, with a searcher, and force the user to manually select the position from a map (they have to select the RIGHT place they took the photo, not just the city. And they can't be wrong for more than 10 meters)...

So... I prefer the bad UX for picking the photos, but being able to get the EXIF, rather than showing a map.

Do you know any library that already implemented an alternative picker? or do you know some code where I can copy/get some ideas?

**Comment by BrodaNoel** [comment]
No no. Get out of here. This problem still there, and I'm trying to find some alternatives (I'm just in holidays for some days)

**Comment by adamita** [comment]
I have the same problem. Zero insted of GPS data in the picked photo's exif.

**Comment by AlimovSV** [comment]
This can be reproduced on an emulator running Android 14. Any news? Returns for me:
```
{ ... "GPSLatitude": 0, "GPSLatitudeRef": "", "GPSLongitude": 0, "GPSLongitudeRef": "", ... }
```

**Comment by marco2216** [comment]
@TomFranklin Because they are not using the [Photo Picker](https://developer.android.com/training/data-storage/shared/photopicker), they are using their own custom picker

**Comment by marco2216** [comment]
Yes, I haven't tested it, but I believe you can pick images with the legacy image picker, try passing `legacy: true` to the [ImagePickerOptions](https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickeroptions)

**Comment by marco2216** [comment]
@TomFranklin Are you on the latest version? It was merged only 2 days ago https://github.com/expo/expo/pull/28514

**Comment by BrodaNoel** [comment]
@TomFranklin sorry for this question. I'm far away my computer. Are you using multiselection? Or only 1 photo?

If multi selection is disabled, I may have to switch it to Android: legacy, iOS: non legacy.

**Comment by AlimovSV** [comment]
I think this issue should not be closed. The problem with exif data on 13/14 android still actual, and I didn't find a solution.

**Comment by BrodaNoel** [comment]
I hate those bots with all my soul. They are ruining every single project.

**Comment by ungaaaabungaaa** [comment]
please can we addresss this issues it works like a charm for ios but for android its always stripped data 
@BrodaNoel  did you find any other alternatives for this

**Comment by only1-adams** [comment]
This problem seems to occur on devices running Android 13 and above. The newer Android versions introduce a different image picker UI, and images selected through this interface do not include the embedded location metadata.

**I managed to find a workaround:**

By setting the `legacy` option to `true` in the `launchImageLibraryAsync` function, you can access the older picker UI, which includes the location metadata.

In the new interface, there's a three-dot menu next to the "Photos" or "Albums" button. Selecting this menu and choosing the "Browse" option directs users to the traditional picker. Images selected through this method retain their location tags, allowing for successful retrieval of EXIF data.


```javascript
async function showGallery() {
  const result = await launchImageLibraryAsync({
    allowsMultipleSelection: false,
    exif: true,
    allowsEditing: false,
    mediaTypes: ["images"],
    legacy: true,
  });

  if (result.canceled) {
    return;
  } else {
    try {
      const savedAssets = await Promise.all(
        result.assets.map(async (asset) => {
          const localAsset = await createAssetAsync(asset.uri);
          const assetInfo = await getAssetInfoAsync(localAsset);
          return assetInfo;
        })
      );

      setSiteImages((prev) => [...prev, ...savedAssets]);
    } catch (error) {
      console.log(error);
    }
  }
}
```


This works for us in our case, as it is an enterprise application. We know the users utilizing this feature, so we just had to inform them about the limitation so they can use the workaround. In cases where the app might be served to anonymous users, adding an explanation of this limitation may or may not be effective.

**Comment by SirCameron** [comment]
Please reopen this.. this is still an issue.

**Comment by Kyyza** [comment]
Still an issue...

**Comment by eddie4510** [comment]
Found a workaround to use the **expo-document-picker** and **expo-document-picker** instead of the expo-image-picker to pick up files from the original storage.
The exif metadata can be obtained with exif-parser.
```
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system';
import ExifParser from 'exif-parser';

const base64ToArrayBuffer = (base64: string) => {
    const binaryString = atob(base64);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes.buffer;
};

const handleImagePick = async () => {
    const res = await DocumentPicker.getDocumentAsync({
        type: 'image/*',
        copyToCacheDirectory: true,
    });

    if (res.canceled) return;

    const pickedFile = res.assets[0];
    const fileUri = pickedFile.uri;
    console.log(pickedFile);
    if (!pickedFile) return;

    setPhotoUri(fileUri);
    setFile({
        uri: pickedFile.uri,
        type: pickedFile.mimeType,
        name: pickedFile.name,
        size: pickedFile.size,
    });
    setPhotoSrc(fileUri as ImageSource);

    try {
        const fileInfo = await FileSystem.readAsStringAsync(fileUri, {
            encoding: FileSystem.EncodingType.Base64,
        });

        const arrayBuffer = base64ToArrayBuffer(fileInfo);
        const parser = ExifParser.create(arrayBuffer);
        const result = parser.parse();

        console.log("Result:", result);

        const exif = result.tags;
        if (!exif) {
            console.error("No EXIF data found");
            return;
        }

    } catch (err) {
        console.error("EXIF parsing failed", err);
    }
};
```

**Comment by arealesramirez** [comment]
This is still a problem...

While expo-document-picker and expo-file-system alternatives work, the user experience is not the same as if using the image picker.

Can we reopen this issue?

**Comment by stharvey** [comment]
Is there any further advice on this?  I've tried the suggestions on this thread but I still can't figure out how to get GPS location data from photos that do have GPS data associated with them (can be viewed via online EXIF viewers).

Expo 54, Android Pixel 9 Pro - When I look at `media.exif` data provided by `ImagePicker.launchImageLibraryAsync` I see:

`"GPSAltitude": 0, "GPSAltitudeRef": 0, "GPSDateStamp": "", "GPSLatitude": 0, "GPSLatitudeRef": "", "GPSLongitude": 0, "GPSLongitudeRef": "", "GPSTimeStamp": "00:00:00", "GPSVersionID": ""`

I'd love to hear if anyone has any advice on a way to reliably get this data.

**Comment by ungaaaabungaaa** [comment]
@stharvey : use a file picker to pick the images and you can get the location easily

**Comment by stharvey** [comment]
Thanks for replying so quickly @ungaaaabungaaa - do you mean using a library such as expo-document-picker ? I can't see any documentation on how to access exif/gps metadata when picking files using that method.  The object returned looks like:

`{"assets": [{"lastModified": 1766265878000, "mimeType": "image/jpeg", "name": "PXL_20251220_212434296.PORTRAIT.ORIGINAL.jpg", "size": 2031621, "uri": "file:///data/user/0/com.xxxxxx.app/cache/DocumentPicker/69ded304-4e40-4e79-825a-773368ba5686.jpg"}], "canceled": false}
`

**Comment by AlimovSV** [comment]
I think the idea is to use some library to get exif from the selected file - something like https://www.npmjs.com/package/@lodev09/react-native-exify

**Comment by ungaaaabungaaa** [comment]
@stharvey | @AlimovSV (Your Right ) - If you use expo image picker & Exif library the image pickers already would have stripped the meta data tags for location 

so the idea is use the file picker to pick the images with all there meta data and use a library like exif reader along with it to get the latitude and longitude

**Comment by stharvey** [comment]
Thanks @AlimovSV and @ungaaaabungaaa - ok great, I'll give that a go - although I don't think this will be a viable solution for production because it appears that users would need to navigate through the filesystem to find their camera photos (at least that's how it appears to me) instead of being taken directly to their photo gallery - though maybe I've missed something.

Thanks again for your advice.

**Comment by AlimovSV** [comment]
@stharvey Try to use this one https://www.npmjs.com/package/react-native-image-crop-picker I remember a year ago I had the similar problems with getting the location from the selected image and this package helped me a lot. But for that time I used expo@51 & react-native-image-crop-picker@0.41.2

**Comment by stharvey** [comment]
Thanks for the tips and advice. I've tried with `react-native-image-crop-picker` and `@lodev09/react-native-exify` but I can't see how to get the path to query the exif of the original file.  The path provided by `react-native-image-crop-picker` is a temporary file within my app path (`"path": "file:///storage/emulated/0/Android/data/com.MYAPP.app/cache/temp/1766489390927.jpg"`) which returns empty GPS data with `@lodev09/react-native-exify`.

`{"ApertureValue": 1.5, "BrightnessValue": -0.59, "ColorSpace": 1, "ComponentsConfiguration": [365, 4], "Compression": 6, "Contrast": 0, "CustomRendered": 1, "DateTime": "2025:12:20 20:34:48", "DateTimeDigitized": "2025:12:20 20:34:48", "DateTimeOriginal": "2025:12:20 20:34:48", "DigitalZoomRatio": 3, "ExifVersion": [293, 4], "ExposureBiasValue": 0, "ExposureMode": 0, "ExposureProgram": 2, "ExposureTime": 0.020002, "FNumber": 1.68, "Flash": 16, "FlashpixVersion": [521, 4], "FocalLength": 6.9, "FocalLengthIn35mmFilm": 24, "GPSAltitudeRef": 0, "GPSTimeStamp": "00:00:00", "GPSVersionID": "", "ISOSpeedRatings": [281, 2], "ImageLength": 2268, "ImageWidth": 4032, "InteroperabilityIndex": "R98", "JPEGInterchangeFormat": 1259, "JPEGInterchangeFormatLength": 10276, "LensMake": "Google", "LensModel": "Pixel 9 Pro back camera 6.9mm f/1.68", "LightSource": 0, "Make": "Google", "MaxApertureValue": 1.5, "MeteringMode": 2, "Model": "Pixel 9 Pro", "Orientation": 1, "PixelXDimension": 4032, "PixelYDimension": 2268, "ResolutionUnit": 2, "Saturation": 0, "SceneCaptureType": 0, "SceneType": "?", "SensingMethod": 2, "Sharpness": 0, "ShutterSpeedValue": 5.64, "Software": "HDR+ 1.0.839895461zpb", "SubSecTime": "352", "SubSecTimeDigitized": "352", "SubSecTimeOriginal": "352", "SubjectDistance": 25.942, "SubjectDistanceRange": 3, "WhiteBalance": 0, "XResolution": 72, "YCbCrPositioning": 1, "YResolution": 72}`

**Comment by adrianarandac** [comment]
Is there any solution to this? When I scroll down a photo I see google gives me its location but theres no way for me to see where that info is coming from. Even with document selector + exify, Im not getting any usable location metadata

**Comment by stharvey** [comment]
@adrianarandac unfortunately not - this is quite an issue for me - if anyone has any solutions to reliably getting EXIF location data from picked photos I'd be really grateful.

**Comment by stharvey** [comment]
Hello again,

After spending a LOT of time and energy on this I’ve managed to come up with a workaround of sorts... so posting in case it helps anyone else.

This is not a proper fix, it's a bit clunky, but the approach is:
 
- Request media library access, including `ACCESS_MEDIA_LOCATION`.
- Pick the image as normal.
- Query the local media library using `MediaLibrary.getAssetsAsync` from `expo-media-library`, sorted by creation time.
- Match the picked image back to the original asset by comparing dimensions; if more than one matches, use the closest creationTime to the picked image's EXIF DateTime. Matched asset must be within max of 60 seconds difference.
- Call `MediaLibrary.getAssetInfoAsync(matchedAsset.id)` on the matched asset - this returns the un-redacted location.

In my testing, by making an informed guess to locate the media file and then querying the original media asset can still provide the location when accessed through `expo-media-library`.

This method won't work for images picked from Google Photos if they no longer exist locally on the device.

For Android, this is the closest I’ve got to a production-usable workaround while still keeping the normal image picker experience.

This feels like quite a roundabout way to get location info so I'd be very glad to hear if anyone else has come up with anything more robust.

I hope that helps.

**Comment by dev-khoi** [comment]
hi @stharvey , have you tested out for iOS? I'm currently running into this issue. 

I want to create an IOS app, but my main goal was to ship a demo on Android first, but this is the last and such a huge blocker for me

**Comment by stharvey** [comment]
hello @dev-khoi - as far as I’m aware this issue only affects Android devices. I haven’t noticed any similar problems on iOS, so I haven’t changed the method used in my iOS app.

On iOS I’m still using the normal expo-image-picker flow, and it has been returning the GPS data correctly in my testing.

**Comment by stharvey** [comment]
Yes, I initially thought the same, but now I don't think this is actually an Expo limitation.

From what I've read, the location data is being stripped by Android's system Photo Picker for privacy reasons, so expo-image-picker can only return what Android provides. 

We really need a cleaner solution, but I think this issue is down to Android rather than Expo.
