### ISSUE TITLE
[ios] app reverts to old bundle after recovering from an error

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2468]
https://forums.expo.io/t/random-reports-of-expo-reverting-downgrading-to-an-earlier-ota-version/14973

> It’s also worth noting that we see a strong correlation between a version downgrade and a fatal app error (like the camera bugging out) - on reload the app is at a very old version. Not always consistent on how far back it goes.

**Comment by nicolasrouanne** [comment]
We are seing a somewhat similar issue (`expo` SDK v32)
- a user on **iOS** has a standalone app, the latest one downloaded from TestFlight. After opening it twice (to get the latest OTA build) he is running with the correct and latest OTA 👌 
- he stops using it for a few minutes / hours (without killing it)
- he reopens the app, the splash screen appears (meaning the app was killed by the OS), it then displays the JS build bundled with the app (very old build indeed) 💥 

It's noteworthy that **_manually killing the app_, doesn't produce this weird behaviour**, it displays the up-to-date OTA bundle. 🤷‍♂

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. We've made a number of fixes and improvements to the OTA update storage logic since this issue was opened. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.

**Comment by nicolasrouanne** [comment]
We haven't seen this issue in most recent releases of the SDK versions (i.e. 34 and 35), so I consider it solved as well.
