### ISSUE TITLE
Generated APK starts and briefly goes back to splash screen and gets stuck

### ISSUE THREAD

**Issue by Elue-dev** [expo/expo#24690]
### Summary

I generated an apk build for my app using this command:

`eas build --platform android --profile preview`

It built successfully, but when i download the apk and run it on my android device, it briefly loads up, then immediately goes back to the splash screen and gets stuck.

I decided to remove the splash screen and build again, but same issue happens, it loads for a split second then gets stuck on a blank screen. I cant debug this because it all works fine in development, even when i build using `eas update`, it works fine, for both ios and android.

I don't know what to do or how to debug this.

This is the link to my repo: [https://github.com/Elue-dev/TrendSpot-Mobile-App](Repo Link)

I have the latest version of expo-cli or eas-cli as well.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-updates": "~0.18.14",

### Environment

expo-env-info@1.0.5
Ok to proceed? (y) 

I went ahead to press y and installed it

### Reproducible demo

this is my App.tsx, this may be useful in trying to help debug the issue:

import React, { useEffect, useState } from "react";
import { ActivityIndicator, View, LogBox } from "react-native";
import { BottomSheetProvider } from "./src/context/bottom_sheet/BottomSheetContext";
import * as Font from "expo-font";
import { NavigationContainer } from "@react-navigation/native";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { AuthProvider } from "./src/context/auth/AuthContext";
import { ModalProvider } from "./src/context/modal/ModalCotext";
import { AlertProvider } from "./src/context/alert/AlertContext";
import RouteNavigator from "./src/navigation/RouteNavigator";
import CustomStatusBar from "./src/components/status_bar";
import Modal from "./src/components/modal/Modal";
import Alert from "./src/components/alert/Alert";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import * as SplashScreen from "expo-splash-screen";

LogBox.ignoreAllLogs();

export default function App() {
  const [fontLoaded, setFontLoaded] = useState(false);

  async function loadFonts() {
    try {
      await Font.loadAsync({
        SSReg: require("./src/assets/fonts/SourceSans3-Regular.ttf"),
        SSBold: require("./src/assets/fonts/SourceSans3-Bold.ttf"),
        SSRSemiB: require("./src/assets/fonts/SourceSans3-SemiBold.ttf"),
        SSLight: require("./src/assets/fonts/SourceSans3-Light.ttf"),
        rubikB: require("./src/assets/fonts/Rubik-Bold.ttf"),
        rubikL: require("./src/assets/fonts/Rubik-Light.ttf"),
        rubikMD: require("./src/assets/fonts/Rubik-Medium.ttf"),
        rubikSB: require("./src/assets/fonts/Rubik-SemiBold.ttf"),
        rubikREG: require("./src/assets/fonts/Rubik-Regular.ttf"),
      });
      setFontLoaded(true);
    } catch (error) {
      console.error("Error loading fonts:", error);
    }
  }

  useEffect(() => {
    async function loadApp() {
      await loadFonts();
      SplashScreen.preventAutoHideAsync()
        .then(() => {
          if (fontLoaded) {
            SplashScreen.hideAsync();
          }
        })
        .catch((error) => {
          console.error("Error preventing auto hide:", error);
        });
    }

    loadApp();
  }, []);

  const queryClient = new QueryClient();

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      {fontLoaded ? (
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <BottomSheetProvider>
              <ModalProvider>
                <AlertProvider>
                  <NavigationContainer>
                    <RouteNavigator />
                    <CustomStatusBar />
                    <Modal />
                    <Alert />
                  </NavigationContainer>
                </AlertProvider>
              </ModalProvider>
            </BottomSheetProvider>
          </AuthProvider>
        </QueryClientProvider>
      ) : (
        <View
          style={{ flex: 1, justifyContent: "center", alignItems: "center" }}
        >
          <ActivityIndicator color="#000" size="large" />
        </View>
      )}
    </GestureHandlerRootView>
  );
}

### Stacktrace (if a crash is involved)

Got some of these in my build logs on expo when building the apk (although it built successfully,  and i saw in the Expo Docs that it most likely didn't cause issues like this)

[stderr] 

Note: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.

[stderr] 

Note: Recompile with -Xlint:deprecation for details.

[stderr] 

Note: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.

[stderr] 

Note: Recompile with -Xlint:unchecked for details.

> Task :expo-json-utils:compileReleaseJavaWithJavac

> Task :expo-modules-core:javaPreCompileRelease

> Task :react-native-picker_picker:compileReleaseJavaWithJavac

[stderr] 

Note: Some input files use or override a deprecated API.

[stderr] 

Note: Recompile with -Xlint:deprecation for details.

[stderr] 

/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:2723:18: warning: the variable "DebuggerInternal" was not declared in function "__shouldPauseOnThrow"

[stderr] 

          typeof DebuggerInternal !== 'undefined' &&

[stderr] 

                 ^~~~~~~~~~~~~~~~

[stderr] 

/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:11484:7: warning: the variable "setTimeout" was not declared in function "logCapturedError"

[stderr] 

      setTimeout(function () {

[stderr] 

      ^~~~~~~~~~

[stderr] 

/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:9444:108: warning: the variable "nativeFabricUIManager" was not declared in function "onChange"

[stderr] 

...lInstanceHandle ? (from && nativeFabricUIManager.setIsJSResponder(from.sta...

[stderr] 

                              ^~~~~~~~~~~~~~~~~~~~~

[stderr] 

/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:10065:21: warning: the variable "clearTimeout" was not declared in anonymous function " 264#"

[stderr] 

    cancelTimeout = clearTimeout;

[stderr] 

                    ^~~~~~~~~~~~

**Comment by brentvatne** [comment]
hi there!

check out the following guides:

- https://expo.fyi/splash-screen-hanging
- https://docs.expo.dev/build-reference/troubleshooting/
