### ISSUE TITLE
[expo-av] Base64 audio is not playing on iOS 17, showing error 'ABI49_0_0EXAV'

### ISSUE THREAD

**Issue by AlissonEnz** [expo/expo#24711]
### Minimal reproducible example

https://snack.expo.dev/@alissonenz/expo-av-base64-audio

### Summary

When attempting to play a base64 encoded audio file using Expo-av on iOS 17, the audio fails to play. The same functionality works as expected on web, Android, and iOS 16 and previous versions. The issue is accompanied by an unrecognizable error code ABI49_0_0EXAV, which doesn't yield any relevant results when searched on Google.

Expo SDK version: 48 and 49 (I didn’t test with older versions)
Platform: iOS 17
Device: iPhone 14 Pro
Reproducible Snack: [Expo Snack](https://snack.expo.dev/@alissonenz/expo-av-base64-audio)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by jennyckaplan** [comment]
I'm running into a similar issue with attempting to play a base64 encoded audio file using expo-av on iOS 17, but am getting the following error:

```
[Error: This media format is not supported. - The AVPlayerItem instance has failed with the error code -11828 and domain "AVFoundationErrorDomain".]
```
The same code works fine on iOS 16. I've tried upgrading to expo version 49.0.13 with no luck.

**Comment by AlissonEnz** [comment]
To anyone facing this issue in the future, we were able to resolve it by saving the `base64` audio into a file using `expo-file-system` and then playing this local file. Here is a simple code snippet:

```typescript
import * as FileSystem from 'expo-file-system';
import { getAudioTypeFromDataURL } from './get-audio-type-from-data-url';

export async function saveAudioToLocalCache(
  audioUrl: string,
  soundName: string
): Promise<string> {
  const audioFileType = getAudioTypeFromDataURL(audioUrl);
  const cacheDir = FileSystem.cacheDirectory;
  
  const newAudioUrl = createAudioUrl(cacheDir, soundName, audioFileType);
  const base64AudioData = extractBase64Data(audioUrl, audioFileType);
  
  await writeAudioDataToFile(newAudioUrl, base64AudioData);
  
  return newAudioUrl;
}

function createAudioUrl(cacheDir: string, soundName: string, audioFileType: string): string {
  return `${cacheDir}${soundName}.${audioFileType}`;
}

function extractBase64Data(audioUrl: string, audioFileType: string): string {
  return audioUrl.replace(`data:audio/${audioFileType};base64,`, '');
}

async function writeAudioDataToFile(newAudioUrl: string, base64AudioData: string): Promise<void> {
  await FileSystem.writeAsStringAsync(newAudioUrl, base64AudioData, {
    encoding: FileSystem.EncodingType.Base64,
  });
}
```
And then:
```typescript
const uri = await saveAudioToLocalCache(base64Audio, soundName);
const { sound } = await Audio.Sound.createAsync({ uri });
```

**Comment by TowhidKashem** [comment]
hey @behenate I noticed you merged a fix for this but I am still encounterng it on iOS 17.1.2 on an iPhone 11 (real device) using SDK 49 fyi

**Comment by behenate** [comment]
@TowhidKashem Hi, for now the changes are published under the [`next`](https://www.npmjs.com/package/expo-av/v/13.10.1?activeTab=versions) tag on npm (meant for SDK 50, which we will release soon). If you are not using Expo Go you can try upgrading to that version even under SDK49, although I can't guarantee that everything will work (as far as I know we didn't introduce any major changes to `expo-av` so it will most likely work just fine under SDK49)

**Comment by TowhidKashem** [comment]
> @TowhidKashem Hi, for now the changes are published under the [`next`](https://www.npmjs.com/package/expo-av/v/13.10.1?activeTab=versions) tag on npm (meant for SDK 50, which we will release soon). If you are not using Expo Go you can try upgrading to that version even under SDK49, although I can't guarantee that everything will work (as far as I know we didn't introduce any major changes to `expo-av` so it will most likely work just fine under SDK49)

Ah that's why, ok cool thanks! will try upgrading to the next tag then. I'm on the managed flow using dev client so no expo go.

**Comment by berkaygemici** [comment]
Hey, I am still facing this issue altough it is mentioned that it was fixed. My versions are following : 
"expo": "~51.0.7",
"expo-av": "^14.0.5", 
I am still having problems playing the base64 sounds on some devices, especially in ios17. What am I missing actually here ?

**Comment by AlissonEnz** [comment]
Hi @berkaygemici, Did you try my solution for storing the audio? It worked for us
