### ISSUE TITLE
[expo-location] checkLocationSettings in resolveUserSettingsForRequest failing due to ClassCastException

### ISSUE THREAD

**Issue by smbryar** [expo/expo#24729]
### Minimal reproducible example

 I have not been able to replicate this issue. I have seen it reported in crashlytics.

### Summary

I am using expo-location in my app and have seen a small number of users have repetitive crashes with the following stack trace:

```
Fatal Exception: java.lang.ClassCastException: com.google.android.gms.common.api.ApiException cannot be cast to com.google.android.gms.common.api.ResolvableApiException
       at expo.modules.location.LocationModule.lambda$resolveUserSettingsForRequest$16$expo-modules-location-LocationModule(LocationModule.java:668)
       at expo.modules.location.LocationModule$$ExternalSyntheticLambda12.onFailure(:4)
       at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

I have not been able to replicate this issue.

# Potential cause

The code it references at expo-location LocationModule.java:668 is very similar to that in this issue: https://issuetracker.google.com/issues/255798723

```
Task<LocationSettingsResponse> task = client.checkLocationSettings(builder.build());

    task.addOnSuccessListener(locationSettingsResponse -> {
      // All location settings requirements are satisfied.
      executePendingRequests(Activity.RESULT_OK);
    });

    task.addOnFailureListener(e -> {
      int statusCode = ((ApiException) e).getStatusCode();

      if (statusCode == CommonStatusCodes.RESOLUTION_REQUIRED) {
        // Location settings are not satisfied, but this can be fixed by showing the user a dialog.
        // Show the dialog by calling startResolutionForResult(), and check the result in onActivityResult().

        try {
          ResolvableApiException resolvable = (ResolvableApiException) e;

          mUIManager.registerActivityEventListener(LocationModule.this);
          resolvable.startResolutionForResult(activity, CHECK_SETTINGS_REQUEST_CODE);
        } catch (IntentSender.SendIntentException sendEx) {
          // Ignore the error.
          executePendingRequests(Activity.RESULT_CANCELED);
        }
      } else {// Location settings are not satisfied. However, we have no way to fix the settings so we won't show the dialog.
        executePendingRequests(Activity.RESULT_CANCELED);
      }
```

* What was the expected result?  
if `exception.statusCode = LocationSettingsStatusCodes.RESOLUTION_REQUIRED`  
will be cast `exception as ResolvableApiException`  

* What was the actual result?
exception is not `ResolvableApiException`

# Dependency versions
* "expo": "49.0.10"
* "expo-location": "16.1.0"

Expo-location has an explicit dependency on 'com.google.android.gms:play-services-location:20.0.0' and so I would expect not to see this problem, as my understanding is that the bug was introduced in "play-services-location:21.0.0"

Have I missed something?
Is it possible for users' devices to be running "play-services-location:21.0.0" despite the explicit dependency, and that cause the issue?

I am cross-posting this to Google Issue Tracker: https://issuetracker.google.com/issues/303285489

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.09.25.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    Expo Workflow: managed

**Comment by superyarik** [comment]
Facing same error on expo 48

**Comment by alexttyip** [comment]
@superyarik I work with @smbryar and have been looking into this issue. We raised a bug ticket with Google and they suggested the we try `play-service-location:21.0.1` to see if that fixes the issue. `expo-location@16.5.0` was recently released and uses the newer version of `play-service-location`.
