### ISSUE TITLE
[Expo 49, Router v2] Drawers Missing Dynamic Routing Like Tabs

### ISSUE THREAD

**Issue by kennethstarkrl** [expo/expo#24732]
### Minimal reproducible example

https://github.com/kennethstarkrl/expo-49-router-v2-drawer-missing-dynamic-routing

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Drawers are missing the ability to use dynamic routing like tabs do. 
We should be able to pass the same href object in the options to Drawer.Screen like Tab.Screen as defined in the docs here https://docs.expo.dev/router/advanced/tabs/#dynamic-routes

There is a workaround for this which is to pass in custom drawer item components and control the routing that way, but we shouldn't have to do that.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.13 => 49.0.13
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

**Comment by kennethstarkrl** [comment]
@EvanBacon Thanks for clarifying, gonna go with the user-space workaround for now.

**Comment by Slokh** [comment]
hey @kennethstarkrl any pointers on the workaround? been trying to get this working and have some wonky solution but wondering if you're solution is better

**Comment by kennethstarkrl** [comment]
> hey @kennethstarkrl any pointers on the workaround? been trying to get this working and have some wonky solution but wondering if your solution is better

I ended up building my own drawer and manually controlling the router from the custom DrawerItems component

_layout
```js
    return (
      <GestureHandlerRootView style={{ flex: 1 }}>
        <Drawer 
          drawerContent={(props) => <DrawerItems {...props}/>} //DrawerItems is just a component with Pressables using route.push()
          backBehavior={'history'}
          }}
          >
            <Drawer.Screen
              name="index"
              options={{
                path:'index',
                drawerLabel: "Home",
                drawerIcon:()=>{return <MaterialCommunityIcons name="home" size={20} color={colors.text} />},
              }}
            />
            ...
```

**Comment by dlindenkreuz** [comment]
Still valid, ping to keep this open
