### ISSUE TITLE
[Android] Add `onNewIntent` to `expo.core.interfaces.ActivityEventListener`

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#2474]
Initial events, or events that cause the app to open do not work:
* [FirebaseNotifications](https://github.com/expo/expo/blob/a3ee8cb0f04958f97ec8304a1ffbb4b6ffecdf46/packages/expo-firebase-notifications/android/src/main/java/expo/modules/firebase/notifications/FirebaseNotificationsModule.java#L226-L244) specifically opening notifications
* [FirebaseInvites](https://github.com/expo/expo/blob/88d09a529fe688a272c56235e64e4c59ca2a8877/packages/expo-firebase-invites/android/src/main/java/expo/modules/firebase/invites/FirebaseInvitesModule.java#L202-L244)
* [FirebaseLinks](https://github.com/expo/expo/blob/88d09a529fe688a272c56235e64e4c59ca2a8877/packages/expo-firebase-links/android/src/main/java/expo/modules/firebase/links/FirebaseLinksModule.java#L166-L191)

**Comment by sjchmiela** [comment]
Closed in https://github.com/expo/expo/commit/afab3265a50607ff6604fd692c4cd7f5ce84457c.
