### ISSUE TITLE
Location.requestForegroundPermissionsAsync() - Android - Asks for permission twice

### ISSUE THREAD

**Issue by katrinjacobsen** [expo/expo#24755]
### Minimal reproducible example

https://snack.expo.dev/@kjacobsen/intrigued-yellow-pretzels?platform=android

### Summary

On Android, the user gets prompted twice when calling Location.requestForegroundPermissionsAsync() if they deny permissions.

expo-location version: ~15.1.1

### Environment

System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^48.0.20 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.11 => 0.18.12
    Expo Workflow: managed

**Comment by gabrieldonadel** [comment]
Hi @katrinjacobsen, the problem in your example is that you're calling `checkPermissions` at render time, so every time your component rerenders you're asking for permissions again, causing the prompt to show multiple times.

Here is an example on how to fix that using an useEffect  https://snack.expo.dev/@gabrieldonadel/49765a?platform=android

**Comment by katrinjacobsen** [comment]
Hi @gabrieldonadel I tested your example, but I'm still getting asked twice on Android in your Snack. That said, I was able to fix the issue in my app using a similar solution :) thanks!
