### ISSUE TITLE
[expo-image-picker][iOS] Unable to pick images without `allowsEditing`

### ISSUE THREAD

**Issue by cavasinf** [expo/expo#24754]
### Minimal reproducible example

https://snack.expo.dev/@allsoftwareflorian/ios-image-picker

### Summary

When calling `launchImageLibraryAsync()` in an iPhone X (iOS 16), 
the iPhone cannot load images through its own interface.

| ![IMG_0015](https://github.com/expo/expo/assets/25293190/d209e741-e365-45e9-9e29-949c26ce0226) | ![IMG_0016](https://github.com/expo/expo/assets/25293190/46e848c2-53d6-49d3-995b-eb75aaf65d7c) |
|---|---|

But if you set `allowsEditing` to true, there's no problem.
<img src="https://github.com/expo/expo/assets/25293190/1958aa0a-a03d-4239-9098-29e30befb482" height="600px"/>

### Environment

See snack.

**Comment by alanjhughes** [comment]
Hi - I've tried your snack and it seems to work with `allowsEditing` set to either value. Can you provide an example project that produces the issue?

**Comment by cavasinf** [comment]
> Not sure what you mean, I request the normal image picker permissions.

I mean what are your current ExpoGo permissions on your device (see screenshots below)

-------------------

From a client return, it seems to come from the iOS 16 version,
I've tested on 17 and it works as expected.

### iOS 16

https://github.com/expo/expo/assets/25293190/eddc64fd-3591-4d81-8542-d9ef4a8892a5

<img src="https://github.com/expo/expo/assets/25293190/174ff12f-5e92-4d3d-ab0e-d85654430833" height="600px"/>

### iOS 17

https://github.com/expo/expo/assets/25293190/c55a387e-1fb0-4c39-8110-88763fbcb7c9

<img src="https://github.com/expo/expo/assets/25293190/71a1a08c-ed76-4014-9cd9-e681c80bf7df" height="600px"/>

**Comment by alanjhughes** [comment]
@cavasinf - This isn't related to the OS version. This can happen for a variety of reasons unrelated to this library. Network connectivity, local storage capacity, icloud storage capacity, can all cause this to happen. I'll need a repro that consistently causes the problem to investigate further.

**Comment by cavasinf** [comment]
Hi @alanjhughes, sorry for the late reply.

I don't understand what you're waiting for on my end.
A repo? I can give you one, but it will be exactly the same as the `snack.expo`.
Why doesn't the snack satisfy you?

I can reproduce the same case on the client application OR the snack expo.

**Comment by alanjhughes** [comment]
@cavasinf - The issue is I cannot reproduce and the snack you have provided does not display any problems. It works as expected. We ask for repros so we can quickly see a problem and get working on a fix. As it stands, I have nothing to go on here. The snack displays no error so I've created an app locally, run it on both iOS 16 and 17, on expo go and a development build, and cannot reproduce the problem. There's not much more I can do without code the reliable produces the issue.

**Comment by cavasinf** [comment]
So is it device related (not version)? 🤔 
Have you run your tests on an emulator? Our case is on a real device.
It's not a real solution, but I can see if uninstalling the app solves the problem (on our client device). 
Sounds like a permission issue.

I don't know if I can legally give you access to a working client project (with real data).
