### ISSUE TITLE
[expo-screen-orientation] : Unable to get back to original position(PORTRAIT) once orientation changed to LANDSCAPE in iOS

### ISSUE THREAD

**Issue by Yandamuri** [expo/expo#24768]
### Summary

I change only screen's orientation to `LANDSCAPE` which is working as expected.

`await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE_RIGHT);`

once the task is done then I change the orientation back to `PORTRAIT`, but it's not changing back to `PORTRAIT`

`await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);`

Issue is occurring in `iOS` only. In `Android` working as expected.

### What platform(s) does this occur on?

iOS

### SDK Version

45.0.8

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
```

### Minimal reproducible example

This can be reproduced by yourself just by running code I have mentioned in the summary section.

**Comment by alanjhughes** [comment]
Hi, I've tested this and it is working as expected. Feel free to open again with a repro that demonstrates the issue.

https://github.com/expo/expo/assets/30924086/5b7d43d9-371a-41a3-b8d7-917741e9015f
