### ISSUE TITLE
expo wrongly reports incompatible dependencies

### ISSUE THREAD

**Issue by juliusmarminge** [expo/expo#24765]
### Summary

Expo tells me I have incompatible dependencies when I don't. For example, it complains about react-native@0.72.4 when I'm using 0.72.5:

![CleanShot 2023-10-06 at 09 51 02@2x](https://github.com/expo/expo/assets/51714798/21f64895-f5d8-4bc3-9aba-29bdfcc32e2f)

I'm not sure if it's to do with the monorepo setup, or that I'm using ppm as package manager, but it hasn't been like this before

### What platform(s) does this occur on?

iOS

### SDK Version

49.0.13

### Environment

```bash
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/Library/Caches/fnm_multishells/41643_1696571613379/bin/node
      npm: 9.8.1 - ~/Library/Caches/fnm_multishells/41643_1696571613379/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7
      expo: ^49.0.13 => 49.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.4
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/t3-oss/create-t3-turbo

**Comment by brentvatne** [comment]
looking at the results of what you pasted with `npx expo-env-info`:

```
npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7
      expo: ^49.0.13 => 49.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.4
```

this uses the very popular [envinfo](https://www.npmjs.com/package/envinfo) package. [this source file](https://github.com/tabrindle/envinfo/blob/main/src/packages.js) is how it's resolved. do you have any ideas what would need to change to support the t3 repo in this context? it seems like it may be doing something that is non-standard

**Comment by juliusmarminge** [comment]
Hmm might have been a bad cache... nuked all node_modules and reinstalled and the react version mismatch went away.. now I only see expected ones. sorry for the misconception

**Comment by juliusmarminge** [comment]
Actually it seems to come back whenever I change version for any dependency - I have to clean the node modules then reinstall to get it to recognize the correct version.

**Comment by juliusmarminge** [comment]
> do you have any ideas what would need to change to support the t3 repo in this context? it seems like it may be doing something that is non-standard

I don't know what that would be. I'm using the node-linker hoisted which previously have made Expo / Metro happy, but other than that it's a pretty normal pnpm monorepo

**Comment by byCedric** [comment]
Hi @juliusmarminge! I know that pnpm installs the [lowest possible version](https://github.com/pnpm/pnpm/issues/6463) of dependencies. It could be that one of the (nested) dependencies in the monorepo adds `react-native@0.72.4` for some reason.

Unfortunately, I couldn't reproduce this, I've tried:
- Changing dependency version in `apps/expo/package.json` (`expo@^49.0.13` → `expo@^49.0.14`)
- Reinstalling from latest `main` without any cache
- Deleting `pnpm-lock.yaml` and reinstalling

If you still can reproduce this, can you commit the lockfile to a branch and send it over? With that, we might be able to track down why pnpm installs `react-native@0.72.4` instead of `.5`.
