### ISSUE TITLE
FaceDetector Module: Camera's classifications not working on Android

### ISSUE THREAD

**Issue by serranoarevalo** [expo/expo#2476]
Hi! I'm trying to make an app that takes a photo when you smile, pretty simple concept.

On the camera component I have a face detector configuration object that has `runClassifications: FaceDetector.Constants.Classifications.all` and `detectLandmarks: FaceDetector.Constants.Landmarks.all`

It works on iOS but it does not work on Android, I get no classifcation whatsoever on it, I only get the size and bound of face.

To reproduce:

https://github.com/serranoarevalo/smile-cam

I also tried with useCamera2Api and I got the same result.

Android Result:

![screen shot 2018-10-21 at 8 48 48 pm](https://user-images.githubusercontent.com/3612017/47266516-c56c5780-d572-11e8-8b95-7dff56ebe57f.png)

iOS Result:

![screen shot 2018-10-21 at 8 49 38 pm](https://user-images.githubusercontent.com/3612017/47266529-e03ecc00-d572-11e8-84b5-b7870383524b.png)

**Comment by serranoarevalo** [comment]
Any ETA for this?

**Comment by sjchmiela** [comment]
It should have been fixed in https://github.com/expo/expo/pull/2308. Will be released in SDK31. 🙂

**Comment by serranoarevalo** [comment]
I understand that. Thanks a lot for all the work you do!
