### ISSUE TITLE
Expo Router v2 sitemap is missing full paths to routes

### ISSUE THREAD

**Issue by statico** [expo/expo#24788]
### Minimal reproducible example

https://github.com/statico/repro-expo-router-bugs

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When the app has a path like `(foo)/test/[param1]/[param2]/[param3]/details.tsx`, the Expo Router generated sitemap will only show the last parameter of the route, like `[param3]/_layout.tsx`. Shouldn't this have the full path, like `[param1]/[param2]/[param3]/_layout.tsx`?

![CleanShot 2023-10-08 at 18 03 28](https://github.com/expo/expo/assets/137158/c75451e9-7fdf-448e-8801-4a084191ea5b)

See repro at https://github.com/statico/repro-expo-router-bugs

1. Run the project
2. Tap "View Sitemap"
3. See the issue above

Simulator builds available at https://expo.dev/accounts/statico/projects/repro-expo-router-bugs/builds

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.19.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 19.0.0 => 19.0.0 
      expo: 49.0.13 => 49.0.13 
      metro: 0.79.1 => 0.79.1 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Reopening, this will be fixed in the next v3 patch

**Comment by marklawlor** [comment]
This is fixed in the latest version
