### ISSUE TITLE
Relative links don't work when using parameterized routes in Expo Router v2

### ISSUE THREAD

**Issue by statico** [expo/expo#24787]
### Minimal reproducible example

https://github.com/statico/repro-expo-router-bugs/tree/665dcc5779196067c0a7ecd98b250fe99bd709c2

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

If I am in a parameterized route like `/(foo)/test/[param1]/[param2]/[param3]/a.tsx`, and within that page I use `<Link href="./b">` to link to `b.tsx` within that directory, the app throws an error:

```
ERROR  Error: No pattern found for route "(foo)/test/[param1]/[param2]/[param3]". Options are: ., js engine: hermes
```

Instead, I would expect this to successfully navigate to `b.tsx` without complaint.

This code used to work fine before we upgraded to Expo v49 and Expo Router v2.

You can reproduce this with my minimal repro here: https://github.com/statico/repro-expo-router-bugs/tree/665dcc5779196067c0a7ecd98b250fe99bd709c2

1. Run the project
2. Tap "Test 1"
3. Tap "Go to other page (relative)"

![CleanShot 2023-10-08 at 17 49 53](https://github.com/expo/expo/assets/137158/03c02a7f-3bdc-481a-8ad2-521c7764cac2)

iOS simulator builds should be available here: https://expo.dev/accounts/statico/projects/repro-expo-router-bugs/builds

Screenshot:

![CleanShot 2023-10-08 at 17 48 11](https://github.com/expo/expo/assets/137158/d648f43b-33dc-4374-81fc-0fe14ee16465)

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.19.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 19.0.0 => 19.0.0 
      expo: 49.0.13 => 49.0.13 
      metro: 0.79.1 => 0.79.1 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed
```

**Comment by WKampel** [comment]
I'm having the same issue in the latest versions.

**Comment by carltallon** [comment]
Me too.

**Comment by statico** [comment]
FWIW, we're working around this by always using full URLs in these situations :(
