### ISSUE TITLE
Expo client doesn't support firebase analytics.

### ISSUE THREAD

**Issue by proworkdev** [expo/expo#2478]
Hi I am using expo client but having issue with firebase analytics integration. Please help me to solve this.

**Comment by raajnadar** [comment]
"Please help me to solve this" Please explain your issue with code sample

**Comment by brentvatne** [comment]
hi there! this belongs on https://expo.canny.io/feature-requests

@EvanBacon is working on adding react-native-firebase to expo: https://expo.canny.io/feature-requests/p/adding-react-native-firebase-to-expo

**Comment by EvanBacon** [comment]
Hey @proworkdev currently you will need to detach to add Firebase analytics. We are working to add them to the native build but until then
Here is an example project: https://github.com/EvanBacon/expo-native-firebase/
And here is a tutorial for ejecting and adding `expo-firebase-analytics` https://www.youtube.com/watch?v=XYTKeFVy7xg
