### ISSUE TITLE
[Expo-SDK-48] App crashes when calling ImagePicker.launchCameraAsync

### ISSUE THREAD

**Issue by MuflahNasir** [expo/expo#24799]
### Minimal reproducible example

https://snack.expo.dev/@muflah_n/expo-image-picker

### Summary

I am trying to launch the camera on a real device (android working well, issue only with iOS). The app exits when hits the function.
It is working fine using Expo Go. But crashes on eas build.

What platform(s) does this occur on?
iOS

SDK Version (managed workflow only)
48

This is a crash report from an Apple developer account.

<img width="500" alt="Screenshot 2023-10-10 at 9 11 36 AM" src="https://github.com/expo/expo/assets/53937186/47115201-891f-4f9e-85a1-3495a322c22c">

I submitted the code for the crashing sample I created.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.7
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.09.25.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 33
        Build Tools: 33.0.0
        System Images: android-33-ext4 | Google Play Intel x86_64 Atom
    npm Packages:
        expo: ~48.0.20
        react: 18.2.0
        react-dom: 18.2.0
        react-native: 0.71.8
        react-native-web: ~0.18.10
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    Expo Workflow: managed

**Comment by Kudo** [comment]
hi there! i tested the snack code on sdk 48, eas build on an ios 17 device and it works for me. could you share a minimal reproducible example project to some git repository? i am happy to investigate and reopen the issue as long as i can repro the problem. thanks!

**Comment by Kudo** [comment]
btw, did you run the app in debug or release build?

**Comment by veeramarni** [comment]
Release build

**Comment by veeramarni** [comment]
@Kudo  It was crashing on iOS 16.6

**Comment by Kudo** [comment]
from the stacktrace, it looks like unhandled javascript exception. wondering how it acting from debug build?

**Comment by hootan09** [comment]
Also, the method "launchCameraAsync" from the "expo-image-picker": "^14.5.0" library crashes only in the EAS production build. It works fine on Expo Go and even on Expo development builds.
It's important to note that this method works fine on iPad and Mac M series.

Sample Code:

```javascript
  const pickImage = async ({key, text}) => {
    openBottomSheet(false);
    // No permissions request is necessary for launching the image library
    const pickerOption = {
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: false,
      allowsMultipleSelection: false,
      selectionLimit: 1,
      base64: false,
      presentationStyle: ImagePicker.UIImagePickerPresentationStyle.AUTOMATIC,
      aspect: [4, 3],
      quality: 1,
    }

      switch (key) {
        case '2':
        {
            let result = await ImagePicker.launchCameraAsync();
            if (!result.canceled) {
              addImageToState(result.assets[0].uri);
            }
            break;
        }
        case '1': 
        {
            let result = await ImagePicker.launchImageLibraryAsync(pickerOption);
          if (!result.canceled) {
            addImageToState(result.assets[0].uri);
          }
          break;
        }
      }
  };
```
