### ISSUE TITLE
Expo Fingerprint API not working properly in Android devices.

### ISSUE THREAD

**Issue by gujral1997** [expo/expo#2479]
I am trying to implement finger-print scan functionality in `react-native` app and using the code below. It is working fine on iOS device but when I try the same code on any android device, It stops scanning if fingerprint authentication fails. My aim is to make the device scan until it receives correct finger print. 

```
scanBiometrics = async () => {
    let result = await Expo.Fingerprint.authenticateAsync('Biometric Scan.');
    if (result.success) {
      // code
      );
    } else {
      //code
    }
  };
```

**Comment by brentvatne** [comment]
in your else block you can call `this.scanBiometrics()` again

```
scanBiometrics = async () => {
    let result = await Expo.Fingerprint.authenticateAsync('Biometric Scan.');
    if (result.success) {
      // code
      );
    } else {
      Alert.alert(
  'Failed to authenticate',
  'Couldn't match your fingerprint, try again?',
  [
    {text: 'Yes', onPress: () => this.scanBiometrics()},
    {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
  ],
)
    }
  };
```

**Comment by brentvatne** [comment]
if that doesn't work then please open a new issue with more information about why not :)

**Comment by gujral1997** [comment]
I want to start it automatically on failure rather than starting it manually by pressing button. Can you tell me how to do that? That's what I want

**Comment by brentvatne** [comment]
just remove the prompt and call it again... there are differences in how these APIs behave on iOS and Android - on iOS you have a prompt where you can disable it, on Android there is no UI. this is in the documentation. because there is no built-in UI you need to return from it when it fails as there is no other API to cancel fingerprints.

**Comment by gujral1997** [comment]
Could you please send me the implementation code. You are right but I am
not able to implement it neither your API's documentation is available.
