### ISSUE TITLE
Using a TypeScript metro.config.ts with Expo Router v2 in a monorepo fails with 'Unable to resolve "expo-router/entry" from "index.js"'

### ISSUE THREAD

**Issue by statico** [expo/expo#24790]
### Minimal reproducible example

https://github.com/statico/repro-expo-router-bugs/tree/typescript-metro-config (make sure to use the `typescript-metro-config` branch)

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Trying to use a TypeScript `metro.config.ts` file in a monorepo with Expo v49 and Expo Router v2 fails with this error:

```
iOS Bundling failed 201ms
Unable to resolve "expo-router/entry" from "index.js"
```

![CleanShot 2023-10-08 at 19 59 42](https://github.com/expo/expo/assets/137158/ec221d3b-fa18-44f0-9fda-2a5428242c45)

To reproduce:
1. Check out https://github.com/statico/repro-expo-router-bugs/tree/typescript-metro-config
2. `pnpm install`
3. `cd packages/mobile`
4. `expo start --ios`

To resolve this issue, rename `metro.config.ts` to `metro.config.js` and the project will work fine.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.19.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.4.0
```

**Comment by byCedric** [comment]
Hi @statico! Thanks for the detailed issue description and repro. Unfortunately, Metro does not support config extensions such as `metro.config.mjs` or `metro.config.ts` (See facebook/metro#916, and the [Metro docs](https://facebook.github.io/metro/docs/configuration/)).

> Recently, the `metro.config.cjs` was added by @huntie in facebook/metro#1027, but that's not (yet) reflected in the docs.

Renaming `metro.config.js` to `metro.config.ts` would cause Metro to "not find" this config file, and would be the equivalent of just deleting the config. Meaning that the error is actually expected, as your monorepo configuration would be lost.

I'm not sure how much we can deviate from the default Metro config behavior in Expo. Maybe pinging the Metro team about this feature would be the best next step.

Hope this helps!

**Comment by statico** [comment]
Got it. Thanks!
