### ISSUE TITLE
Warn when "Developer mode" is not enabled with Windows 10 Creator's update

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#248]
See: https://github.com/expo/xde/issues/74

**Comment by brentvatne** [comment]
is this.. still a problem? @charlesvinette

**Comment by charlesvinette** [comment]
Hey @brentvatne, this is indeed not a problem anymore. This issue came up when Npm5 was released, linking modules with symlinks would fail if not running Developer's Mode. Closing this!
