### ISSUE TITLE
[ci] Look into store_test_results

### ISSUE THREAD

**Issue by ide** [expo/expo#2481]
IIRC Jest can generate JUnit XML output, which CircleCI can process:

https://circleci.com/docs/2.0/configuration-reference/#store_test_results

**Comment by FiberJW** [comment]
Any movement on this? Is this still desired?

**Comment by ide** [comment]
Yeah, seems useful if it's easy to maintain.

**Comment by tsapeta** [comment]
As we've moved from CircleCI to GitHub Actions, I think it's no longer desired or at least not with the `store_test_results` step on CircleCI.
