### ISSUE TITLE
[expo-gl] Crash when calling GLView.createContext on production build with proguard enabled

### ISSUE THREAD

**Issue by frdteknikelektro** [expo/expo#24813]
### Minimal reproducible example

Build on version expo-gl@11.4.0 and expo-gl-cpp@11.4.0

### Summary

When executing GLView.createContext it run successful on dev mode, but crash on production mode. After go through some debugging turns out it happen when minify/proguard is enabled.
I'm not really understand how to solve it, but I think It worth reporting.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
      Watchman: 2022.06.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.27 
      expo: ~44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.67.5 => 0.67.5 
      react-native-web: ^0.16.3 => 0.16.5 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by evoactivity** [comment]
I've just run into this, was sent on a wild goose chase as the crash logs where complaining about 
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor" on path: DexPathList[[zip file "/system/priv-app/MetricsApi/MetricsApi.apk", zip file "/data/app/com.amazon.webview.chromium-1/base.apk"],nativeLibraryDirectories=[/data/app/com.amazon.webview.chromium-1/lib/arm, /data/app/com.amazon.webview.chromium-1/base.apk!/lib/armeabi-v7a, /system/priv-app/MetricsApi/MetricsApi.apk!/lib/armeabi-v7a, /system/priv-app/MetricsApi/lib/arm, /system/priv-app/MetricsApi/MetricsApi.apk!/lib/armeabi, /system/lib, /vendor/lib]]
```

but turning proguard off made my app actually work.
