### ISSUE TITLE
Type generator command fails with "Invalid files" error

### ISSUE THREAD

**Issue by la55u** [expo/expo#24817]
### Minimal reproducible example

-

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Use case: need to run type checking in CI with `tsc --noEmit`.
According to the [docs](https://docs.expo.dev/router/reference/typed-routes/#type-generation) types are generated on the fly when running the dev server but there is a command to trigger it manually: `npx expo customize tsconfig.json`. However upon trying to run this command I get the following error: 
```
CommandError: Invalid files: tsconfig.json. Allowed: babel.config.js, webpack.config.js, metro.config.js, web/serve.json, web/index.html
```

### Reproduction:
1. create a new project with `npx create-expo-app --template` and select the navigation (TS) template
2. run the command: `npx expo customize tsconfig.json`
3. you should see the error above

### Environment

    System:
      OS: Linux 6.5 Fedora Linux 38 (Workstation Edition)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 3.3.1 - ~/.nvm/versions/node/v18.12.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed

**Comment by johnjensenish** [comment]
Duplicate of #24818
