### ISSUE TITLE
@expo "app.config.ts" does not immediately recognize newly added environment variables.

### ISSUE THREAD

**Issue by deutschkihun** [expo/expo#24825]
### Summary

I added new environment variables to the `.env` file and tried to configure them in `app.config.ts` as follows. 

```tsx
// app.config.ts
export default ({config}: ConfigContext): ExpoConfig => ({

 extra: {
    airtableToken: process.env.airtableToken,
  },

```

after that I made `config.ts` to export variables 

```tsx
// config.ts
import Constants from 'expo-constants';

const extra = Constants?.expoConfig?.extra;

export const airtableToken = extra?.airtableToken;
```

However, the configured settings are not applied immediately. When I log the values (ex.`airtableToken`), it appears as `undefined`. The issue persists even if I restart the terminal. However, rebooting the computer resolves this problem.

### What platform(s) does this occur on?

Web

### SDK Version

49

### Environment

```tsx
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 3.6.0 - /usr/local/bin/yarn
      npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 31, 32, 33, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.2
        System Images: android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.3.10
```

### Minimal reproducible example

https://github.com/deutschkihun/expo-app-config-reproduce

**Comment by brentvatne** [comment]
the repository shared includes ~100 dependencies, if you can share another minimal repro that would be helpful. also see this docs page for a better approach for env vars: https://docs.expo.dev/guides/environment-variables/
