### ISSUE TITLE
Expo Fingerprint API not working properly in Android devices.

### ISSUE THREAD

**Issue by gujral1997** [expo/expo#2482]
I am trying to implement finger-print scan functionality in react-native app and using the code below. It is working fine on iOS device but when I try the same code on any android device, It stops scanning if 
fingerprint authentication fails. My aim is to make the device scan until it receives correct finger print.

```
scanBiometrics = async () => {
    let result = await Expo.Fingerprint.authenticateAsync('Biometric Scan.');
    if (result.success) {
      // code
      );
    } else {
      //code
    }
  };
```

If I try on android by doing some changes as shown in the code below:

```
scanBiometrics = async () => {
  let result = await Expo.Fingerprint.authenticateAsync("Biometric Scan.");
  if (result.success) {
    // code
  } else {
    Alert.alert(
      "Failed to authenticate",
      `Couldn't match your fingerprint, try again?`,
      [
        { text: "Yes", onPress: () => this.scanBiometrics() },
        {
          text: "Cancel",
          onPress: () => console.log("Cancel Pressed"),
          style: "cancel"
        }
      ]
    );
  }
};
```

I am able to scan again and again manually if authentication fails but I want that it should ask for authentication again if authentication fails in case of android phone rather than manually popping up the alert.

Same cod

**Comment by brentvatne** [comment]
```
} else {
  this.scanBiometrics()
}
```

this is a bad idea for the reasons that i explained in the other issue but if you want to do it there you go

**Comment by gujral1997** [comment]
I have already tried it. It keeps on popping the authenticator again and again in an infinite loop.
