### ISSUE TITLE
Expo-secure-store incorrectly handles WHEN_UNLOCKED_THIS_DEVICE_ONLY constraint

### ISSUE THREAD

**Issue by mmmguitar** [expo/expo#24829]
### Minimal reproducible example

https://snack.expo.dev/@rob.trevethan/smiling-violet-graham-crackers

### Summary

Expo secure store for IOS enables you to set security constraints to manage the secure access to fields saved in the secure store.  These constraints are like always vs when unlocked vs phone passcode and first unlock.

When using the specific constraint `WHEN_UNLOCKED_THIS_DEVICE_ONLY`:
-  this worked fine on expo 48
-  on expo 49  it errors when accessing the secure store on devices that do not have a passcode or biometrics set 
-  it starts to work if you then set a passcode 
-  A device passcode shouldn't be be required for this constraint and Expo 48 was working as expected 
-  the error makes it behave like the constraint `WHEN_PASSCODE_SET_THIS_DEVICE_ONLY`and there is an obvious error in the code that explains why

Code:
- after the Expo 48  the secure store module was [refactored to the new Expo module format](https://github.com/expo/expo/pull/21393) and this was released in expo 49
- You can see a [map of the constraints in the code here](https://github.com/expo/expo/blame/e68cb072a211aaf8ae709d8bfa88acca885b24e8/packages/expo-secure-store/ios/SecureStoreModule.swift#L16) that `WHEN_UNLOCKED_THIS_DEVICE_ONLY` has been mapped to `SecureStoreAccessible.whenPasscodeSetThisDeviceOnly.rawValue` i,e, with passcode which is incorrect.
- It should be mapped to `SecureStoreAccessible.whenUnlockedThisDeviceOnly.rawValue`.  
- The accessible values for `WHEN_UNLOCKED_THIS_DEVICE_ONLY` exists in the mapping for IOS in the [latest version](https://github.com/expo/expo/blob/cf94ec81b80892e360f413fc59f1dcbf245e65a0/packages/expo-secure-store/ios/SecureStoreAccessible.swift#L10) and were also present in the [old module](https://github.com/expo/expo/blob/e68cb072a211aaf8ae709d8bfa88acca885b24e8/ios/versioned/sdk48/EXSecureStore/EXSecureStore/ABI48_0_0EXSecureStore.m#L153C14-L153C58) in expo 48.

So seems this should be handled + work, its just that mapping is incorrect. It appears a minor error was introduced during the refactor of secure store to the new Expo modules.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 16.14.2 - /run/user/1000/fnm_multishells/10533_1697017000792/bin/node
      Yarn: 1.22.18 - /run/user/1000/fnm_multishells/10533_1697017000792/bin/yarn
      npm: 8.5.0 - /run/user/1000/fnm_multishells/10533_1697017000792/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      babel-preset-expo: ^9.3.0 => 9.5.1 
      expo: ^49.0.0 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: bare

**Comment by AronBe** [comment]
Yeah, I have also noticed a change after upgrading from 48 to 49. I have had issue with background handling in the secure store, I have resolved it by changing the default, but still would like to revisit it and do deeper research as you did @mmmguitar 

https://github.com/expo/expo/issues/23924#issuecomment-1683391507

**Comment by mmmguitar** [comment]
Yeah @AronBe I had a little look into that and commented in that issue thread, its definitely unrelated to this issue and seems to be more a bug in expo 48 that was inadvertently fixed by the module refactor in expo 49.
