### ISSUE TITLE
ENV NOT LOADING IN WEB

### ISSUE THREAD

**Issue by elkortby** [expo/expo#24826]
### Minimal reproducible example

npx create-expo-app@latest testapp && cd testapp && echo "EXPO_PUBLIC_API_URL=http://localhost:1337" >> .env && npx expo start --web

### Summary

EXPO_PUBLIC_API_URL is loading fine on IOS / Android but not loading in web,
See the screenshot:
<img width="1280" alt="image" src="https://github.com/expo/expo/assets/34894866/9dc4946d-efb8-44fb-ba56-73482b6d2e26">

### Environment

npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.8.1 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0
      expo: ~49.0.13 => 49.0.13
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed

**Comment by byCedric** [comment]
Hi @elkortby! It is not supported out of the box without using the Metro bundler for web. To do this, you can either:
- Clone from the tabs template, which has this enabled by default (`$ npx create-expo-app@latest ./test-app --template tabs`)
- Set the `app.json` property "`expo.web.bundler = "metro"`"

Hope this helps!
