### ISSUE TITLE
Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable? 

### ISSUE THREAD

**Issue by julianaferry** [expo/expo#2485]
Why am I having this problem?
-->Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
[15:06:42] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by EvanBacon** [comment]
I cannot reproduce this error. Feel free to reopen the issue when you have clear instructions for recreating the problem.
