### ISSUE TITLE
Location.getCurrentPositionAsync not working anymore on Android

### ISSUE THREAD

**Issue by MarcHbb** [expo/expo#24856]
### Minimal reproducible example

Error not reproduced in snack

### Summary

Location.getCurrentPositionAsync() is currently not working on android device.

Error :

```[Error: Encountered an exception while calling native method: Exception occurred while executing exported method getCurrentPositionAsync on module ExpoLocation: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~Wgqj3r99uKWvrH_B0MaJug==/com.app.dev-ZD2IwBYB-aky0AQxmxqpyA==/base.apk!classes6.dex)]```

It was working fine before. I did some research and it may be caused by the last update of google play service : ([Release Notes  |  Google Play services  |  Google for Developers](https://developers.google.com/android/guides/releases#october_13_2022))

October 13, 2022
The latest update to the play-services-location library includes the following changes:

```[FusedLocationProviderClient](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient), [ActivityRecognitionClient](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient), [GeofencingClient](https://developers.google.com/android/reference/com/google/android/gms/location/GeofencingClient) and [SettingsClient](https://developers.google.com/android/reference/com/google/android/gms/location/SettingsClient) are now interfaces instead of classes, which helps enforce correct usage and improves testability.```

As the error above says :

```Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected```

As the release says :

```FusedLocationProviderClient, ... are now interfaces instead of classes```

Any solution for this ?

### Environment

```expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.0 => 48.0.0 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.16.0
    Expo Workflow: managed```

**Comment by ymc-thzi** [comment]
Have exactly the same issue. Have you found any solution? I am thinking about patching `expo-location` so that it uses play-services-location:21.0.1 🤷🏻 
At the moment it uses play-services-location:16.0.0 😱 
Also found out that `react-native-maps` uses play-services-location:21.0.1 what explains that location detection is working with my maps

**Comment by ymc-thzi** [comment]
Created a patch, no it works again.

`diff --git a/node_modules/expo-location/android/build.gradle b/node_modules/expo-location/android/build.gradle
index d3a88f3..13ff885 100644
--- a/node_modules/expo-location/android/build.gradle
+++ b/node_modules/expo-location/android/build.gradle
@@ -77,7 +77,7 @@ dependencies {
   unimodule 'expo-modules-core'
   unimodule "unimodules-task-manager-interface"
 
-  api 'com.google.android.gms:play-services-location:16.0.0'
+  api 'com.google.android.gms:play-services-location:21.0.1'
 
   api('io.nlopez.smartlocation:library:3.2.11') {
     transitive = false
`

**Comment by MarcHbb** [comment]
> Created a patch, no it works again.
> 
> ```
> diff --git a/node_modules/expo-location/android/build.gradle b/node_modules/expo-location/android/build.gradle
> index d3a88f3..13ff885 100644
> --- a/node_modules/expo-location/android/build.gradle
> +++ b/node_modules/expo-location/android/build.gradle
> @@ -77,7 +77,7 @@ dependencies {
>    unimodule 'expo-modules-core'
>    unimodule "unimodules-task-manager-interface"
>  
> -  api 'com.google.android.gms:play-services-location:16.0.0'
> +  api 'com.google.android.gms:play-services-location:21.0.1'
>  
>    api('io.nlopez.smartlocation:library:3.2.11') {
>      transitive = false
> ```

Changed api 'com.google.android.gms:play-services-location:16.0.0' to '21.0.1' and run the patch-packager doesn't works for me. Did I miss something

**Comment by ymc-thzi** [comment]
I created a patch file with `patch-package` like normal:
- I did the change manually in the expo-locations build.gradle file
- run `npx patch-package expo-location`
- patch-package recognize the change and a patch file with the diff got created
After that I did my normal reset command containing deleting `node_modules` folder and run `npm install` and `npx patch-package` afterwards so that the changes from the patch got written to my fresh installed `node modules`
After that I rebuild the project in Android Studio and run it with successful location detection again.

**Comment by MarcHbb** [comment]
Yes I found how to create the patch but had an issue on the build step because of mismatch version ...
I finally ended up to upgrade react-native-maps to the latest version (1.8.0) then rebuild and it worked. Maybe you should try this so you don't need a patch :)

**Comment by ymc-thzi** [comment]
I already used react-native-maps 1.8.0 but if that works for everything is good 😄

**Comment by MarcHbb** [comment]
My bad, I forget I tried to patch react-native-maps when the build has failed, and didn't work so I remove it. But still have the patch for epxo-location 👍

**Comment by Hackinet** [comment]
Since `getCurrentPositionAsync` was not working we ended up with a hacky fix. Basically as soon as the map gets the user location, we extract it from the map and animate map to the user location.

```
<MapView
        onUserLocationChange={(userLocationChangeEvent) => {
            const coordinates = {
                latitude: userLocationChangeEvent.nativeEvent.coordinate.latitude,
                longitude: userLocationChangeEvent.nativeEvent.coordinate.longitude,
                latitudeDelta: 0.04, //change this
                longitudeDelta: 0.05 //change this
            };
            if(userCoordinatesRef.current === undefined){
                mapRef.current?.animateToRegion(coordinates)
            }
            userCoordinatesRef.current = coordinates;
        }}
        showsUserLocation={true}
        followsUserLocation={true}
>
//Markers here
</MapView>
```

**Comment by tknuts** [comment]
Why is this closed? I have issues with some phones not all, running Android 14. Will this not be fixed in the next SDK release ?

**Comment by tknuts** [comment]
Do any of you know if this issue is resolved in SDK50?

**Comment by Shofol** [comment]
This is not working yet. If you need a reference then check this Snack: https://snack.expo.dev/@shofol/location?platform=android. 

It goes to infinite waiting. 

<img width="339" alt="Screenshot 2024-01-31 at 5 33 16 PM" src="https://github.com/expo/expo/assets/30428153/e00c280f-f027-4f18-bcb1-8bd30a90ca5e">

**Comment by tknuts** [comment]
But your example is in an emulator. Vi only have problems with some models running Android 14, not all. That's what makes it funny.

**Comment by timbtimbtimb** [comment]
So I've changed `api 'com.google.android.gms:play-services-location:21.0.1'` to `api 'com.google.android.gms:play-services-location:21.0.1'` in `/node_modules/expo-location/android/build.gradle` in as suggested, and it works when running `npx expo run:android` on a simulator or my own device. But when I create a build with `eas build --platform android --local --profile preview`, location doesn't work at all (in fact the status bar icon doesn't even light up)
Any advice ?

**Comment by quanSadie** [comment]
@timbtimbtimb I have the exact same issue, have you found the way to fix it ? much thanks

**Comment by JJSLIoT** [comment]
Why is this issue closed??

**Comment by anguer** [comment]
Why is this issue closed???

**Comment by billomore** [comment]
Why is this issue closed????

anywhoo, maybe it will help someone else - when I used 
```javascript
await getCurrentPositionAsync({
  accuracy: LocationAccuracy.Balanced
});
```
and it hung my app indefinitely, but when I changed the accuracy to `LocationAccuracy.Highest` - it started working. Don't have a slightest clue why
