### ISSUE TITLE
app icons not working

### ISSUE THREAD

**Issue by ralyodio** [expo/expo#24859]
### Summary

I have added 1024x1024 png with alpha channenl removed as app icons....it still won't show up in expo or app stores after building.

### What platform(s) does this occur on?

iOS

### SDK Version

    "expo": "~49.0.13",

### Environment

linux

### Minimal reproducible example

```
{
  "expo": {
    "name": "Foclarity",
    "owner": "custany",
    "slug": "foclarity-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.custany.foclarityapp"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.custany.foclarityapp"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "d45110df-8563-40d7-a94a-faf610a004bb"
      }
    }
  }
}

```

**Comment by ralyodio** [comment]
anyone know what i'm doing wrong?

**Comment by iotashan** [comment]
Looks like you didn't follow the docs.

https://docs.expo.dev/develop/user-interface/app-icons/#create-an-app-icon
"Make sure the icon fills the whole square, with no rounded corners or other transparent pixels."

**Comment by ralyodio** [comment]
I don't have transparent pixels. And it's 1024x1024
