### ISSUE TITLE
SDK 30: Android ExpoKit (Detached Application) - Font / Assets / FileSystem Issues 

### ISSUE THREAD

**Issue by Daadler6** [expo/expo#2486]
### Environment
```
<!-- In your terminal run `expo diagnostics` and paste the output here. -->
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.4.0
  Yarn: 0.17.10
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/madmobile-71e5c9ad-fbe4-4ed6-8e87-399c7860d849.tar.gz
```

```
Android Standalone - ExpoKit Release Build
```
### Steps to Reproduce

(Write your steps here:)

1. Detach Android Build with SDK 30 Running
2. Build using the following buildTypes:
``` 
 buildTypes {
    debug {
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      zipAlignEnabled true
    }
```
3. Try and load an Asset or Custom Font before application loads
```
    await Promise.all([
      Expo.Font.loadAsync({ icoMoonIcons })
    ]);

```
4. Observe the following error preventing the application from loading - in my instance the splash screen stays.

```
[Unhandled promise rejection: TypeError: undefined is not a function (evaluating 'FS.getInfoAsync(fileUri, options)')]
```

### Expected Behavior

Expo modules should load. Works on IOS and Android in non minified code type (debug)

(Write what you thought would happen.)

### Actual Behavior

See step 4 above.

![screen shot 2018-10-23 at 4 47 40 pm](https://user-images.githubusercontent.com/10039096/47389669-62e69900-d6e3-11e8-8acb-ca0fe8a9c3fa.png)

### Reproducible Demo

I am more than willing to share our APK or can be reached on the Expo Slack channel to provide more context. Build configurations, expo.gradle, etc etc. Anything you guys need feel free to comment below or reach out via slack

Notes:

Removing ` minifyEnabled true` from the build config resolves the error

 I think this may have to do with modules vs files. As the following code works when minified

```   
 const result = await Promise.all([
      DangerZone.Localization.getCurrentLocaleAsync();
    ]);
```

**Comment by Daadler6** [comment]
For those who might run into the issue the future. In Expo SDK 29 or 30 Universal Modules were introduced. After doing some reading on proguard / android minify I discovered that you need to update your old proguard-rules.pro file based on Expos latest standards. 

Adding the following to the proguard-rules.pro file in Android folder fixed my issues

```##### Crashlytics #####
-keepattributes SourceFile,LineNumberTable

##### Expo Universal Modules #####

-keepclassmembers class * {
  @expo.core.interfaces.ExpoProp *;
}
-keepclassmembers class * {
  @expo.core.interfaces.ExpoMethod *;
}

-keepclassmembers class * {
  @**.expo.core.interfaces.ExpoProp *;
}
-keepclassmembers class * {
  @**.expo.core.interfaces.ExpoMethod *;
}
```

**Comment by sin2** [comment]
Could these rules be added to the docs when upgrading from <29?
