### ISSUE TITLE
[EXPO 48] TypeError: Cannot read property 'HTTP' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by enisze** [expo/expo#24863]
### Summary

I was expecting it to start the iOS and android app, but probably because of the metro config it does not work. If there is any other solution I would appreciate it. 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

  "dependencies": {
    "@aws-amplify/auth": "^4.5.10",
    "@aws-amplify/core": "^4.5.10",
    "@dreamstack/aws": "1.0.0",
    "@dreamstack/i18n": "1.0.0",
    "@dreamstack/proprate-common": "1.0.0",
    "@dreamstack/tracking": "1.0.0",
    "@dreamstack/utilities": "1.0.0",
    "@expo/vector-icons": "^13.0.0",
    "@gorhom/bottom-sheet": "^4.4.7",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-firebase/analytics": "14.11.0",
    "@react-native-firebase/app": "14.11.0",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/elements": "^1.3.6",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@tanstack/react-query": "^4.29.19",
    "@trpc/client": "^10.34.0",
    "@types/intl": "^1.2.0",
    "amazon-cognito-identity-js": "^6.3.1",
    "core-js": "^3.31.1",
    "customerio-expo-plugin": "1.0.0-beta.10",
    "customerio-reactnative": "2.4.2",
    "date-fns": "^2.30.0",
    "dotenv-flow": "^3.2.0",
    "expo": "^48.0.10",
    "expo-constants": "~14.2.1",
    "expo-font": "~11.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-localization": "~14.1.1",
    "expo-navigation-bar": "~2.1.1",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "expo-web-browser": "~12.1.1",
    "formik": "^2.2.9",
    "i18next": "^20.1.0",
    "intl": "^1.2.5",
    "intl-pluralrules": "^2.0.1",
    "jest-expo": "^47.0.0",
    "jotai": "^2.3.1",
    "lodash": "^4.17.21",
    "lottie-react-native": "5.1.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^11.8.13",
    "react-native": "0.71.13",
    "react-native-animated-dots-carousel": "^1.0.1",
    "react-native-autocomplete-dropdown": "^2.0.7",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-maps": "1.3.2",
    "react-native-masked-text": "^1.13.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.26.0",
    "react-query": "3.39.3",
    "remeda": "^1.23.0",
    "superjson": "^1.12.4",
    "twrnc": "^3.4.0",
    "uuid": "3.4.0",
    "zod": "^3.21.4",
    "zod-formik-adapter": "^1.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.22.9",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@babel/plugin-proposal-numeric-separator": "^7.18.6",
    "@testing-library/jest-native": "^5.3.0",
    "@testing-library/react-native": "^11.5.0",
    "@types/lodash": "^4.14.195",
    "@types/react": "~18.0.24",
    "@types/react-native": "~0.70.6",
    "expo-build-properties": "~0.6.0",
    "expo-dev-client": "~2.2.1",
    "jest": "29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "typescript": "4.9.4"
  },

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.18.0 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /Users/enisze/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      react-native: 0.71.13 => 0.71.13
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.8
    Expo Workflow: managed

### Reproducible demo

I had to add: 
```
config.resolver.resolverMainFields = [
  'react-native',
  'module',
  'browser',
  'main',
]
```
in my metro.config.js 
because of this [issue](https://github.com/aws/aws-sdk-js-v3/issues/4877#issuecomment-1656007484)

After adding this I got the error.

**Comment by Kudo** [comment]
hi there! i cannot install some of packages you provided, e.g. `@dreamstack/aws`. i'm happy to reopen the issue and investigate the problem if i can repro the issue. would be good if you could create a minimal reproducible example to some git repository.

in the meantime, i went though the https://github.com/aws/aws-sdk-js-v3/issues/4877 thread and have some thought:
1. if the error is `Unable to resolve module stream`. changing CJS to ESM does not actually resolve the issue, because the `stream` module is still not available in react-native environment. i feel the root cause is from aws js that it should not import/require the stream module for react-native environment.
2. adding `resolverMainFields: ['react-native', 'module', 'browser', 'main']` would enable ESM for *ALL* modules. as long as there's a module having the unsupported ESM code, it would cause problems. For example that in your `Cannot read property 'HTTP' of undefined` case. you should investigate which module tries to access `Object.HTTP` and gets undefined from ESM code.

**Comment by enisze** [comment]
Hi @Kudo thanks for having a look. I managed to fix that problem somehow by downgrading / trying to remove the depencies which caused the issues.

**Comment by Kudo** [comment]
thanks @enisze! i'm glad you found solutions and sorry i didn't help much for you.
