### ISSUE TITLE
Syntax errors (unexpected token/identifier/...) at AppEntry.bundle

### ISSUE THREAD

**Issue by WouterFlorijn** [expo/expo#2487]
### Environment

```
Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.1.0
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
\[22:58:04] Request failed with status code 500
[22:58:04] Set EXPO_DEBUG=true in your env to view the stack trace.
```

Target: Android Emulator.

### Steps to Reproduce

1. Create a new project using `expo init my-new-project`
2. Write (working) code, or just leave the project as is.
3. `npm run start`
4. Send app to Android emulator.

### Expected Behavior

The app runs normally.

### Actual Behavior

Random syntax errors are generated (different every time). The one below is just an example. Usually something like "Unexpected identifier" or "Unexpected token".

![image](https://user-images.githubusercontent.com/7816704/47389844-1ec0bc00-d716-11e8-85b1-02deca389ef4.png)

> Unexpected identifier 'token'. Expected a reference on the left hand side of an enumeration statement. (http://10.80.209.50:19001/./node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=C%3A%5Cpath%5Cto%my-new-project%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles:155555)
>
> Unexpected identifier 'token'. Expected a reference on the left hand side of an enumeration statement. (http://10.80.209.50:19001/./node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=C%3A%5Cpath%5Cto%5Cmy-new-project%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles:155555)

Sometimes, removing `node_modules` and re-running `npm install` fixes it, sometimes it doesn't. Errors are also becoming more and more frequent.

### Reproducible Demo

Not possible, as errors pop up randomly.

**Comment by brentvatne** [comment]
hello! I just followed your steps and it worked as expected. I don't know what could be wrong on your machine to do this but you might want to check that you don't have any globally installed npm packages that might be problematic (easiest to delete all global packages and install them as needed). if you did *any* steps different than what you described above then let me know.

**Comment by WouterFlorijn** [comment]
@brentvatne thanks, I'll try that. The problem is that I sometimes go a day without the error, and sometimes it happens every 10 minutes.

Regardless of what caused the issue, do you think this is something expo could catch in order to produce a readable error?

**Comment by W7PEA** [comment]
I hit this same thing after upgrading from 27 -- 30.
Weird thing is an expo build:android works.

Details in this bug I duped to this one
https://github.com/expo/expo-cli/issues/135

**Comment by W7PEA** [comment]
And for fun, I rebooted and now it all works fine. 

I wonder if something is being cached in the emulator. Next time I hit this I'll try restarting Android Studio.

**Comment by W7PEA** [comment]
I'll add one more note and stop posting. ;-)

For me, this only affects the Android Studio Emulator. If you run the Expo app on a real device and open the app remotely (QRCode) or do a full build and install the APK. This does not occur.
Don't  know if the version matters... 

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 8, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by CardboardComputers** [comment]
The AppEntry.bundle is basically just all of your code put together; as a result, the line number (in this case 155555) is not very helpful. I had a similar error for a while, when I imported a file I'd written largely without testing:

> Unexpected identifier 'response'. Expected ';' after variable declaration. (http://[ ... ]/AppEntry.bundle?[ ... ]hashAssetFiles.js:233189)

As it turns out, it was angry that somewhere in about a thousand lines I'd written

    const response = await serverFetch(url, params);
    if (!response.ok) { throw new Error(response.statusText); }
    const json = await response.json();

and specifically, it was angry about the `await` in `await response.json();`. In my case, it was because I'd left out an `async` keyword in the function declaration.

In any case, this error looks to be an indication that something may be causing weird interpreter errors (on...runtime? ish?), in cases where the interpreter isn't sure exactly what you're trying to do and so doesn't provide an intuitively helpful message. Look through any new code ("Expected a reference on the left hand side of an enumeration statement" suggests something wrong near a `for` loop); if you can't find anything, comment out everything and uncomment blocks one by one until the error shows up.
