### ISSUE TITLE
[Unmatched Route] issue when trying to navigate to the other screen in expo go app

### ISSUE THREAD

**Issue by jamespresidium** [expo/expo#24879]
### Minimal reproducible example

   const link = `/home/patient/${patient.id}/encounter/${encounter.id}/overview`;

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

![image](https://github.com/expo/expo/assets/143427959/97c9d76d-517c-46ac-a038-8cd2e33f4e1c)
![image](https://github.com/expo/expo/assets/143427959/ccd5caca-d26a-4f85-8c25-c7a1fb0a8cce)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/metro-config: ^0.10.6 => 0.10.6
      expo: ~49.0.3 => 49.0.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: bare

**Comment by marklawlor** [comment]
Please provide a full minimal reproduction, we cannot debug your issue from that one line. I'm going to close this issue, but if you provide a reproduction I'll reopen and investigate.
