### ISSUE TITLE
Error: Failed to create a worklet e Invariant Violation: "main" has not been registered. - Problemas com Reanimated

### ISSUE THREAD

**Issue by kelwinxd** [expo/expo#24873]
### Summary

Ao instalar a dependencias para rodar o navigator Drawer, ele fica dando esse problema seguinte:

![2023-10-15-15-35-54](https://github.com/expo/expo/assets/90807426/a10ea5a3-cc9d-4da2-9d63-c6dad9b2cb02)
 Já instalei os pacotes atualizados, como também tentei adequa-los ao expo instalado, já coloquei o plugin na config do babel, como demonstrado a seguir:
 
![2023-10-15-15-37-25](https://github.com/expo/expo/assets/90807426/30b08c52-1ac2-4c55-b9ec-26a82065565d)

Não sei mais o que fazer, me ajudem.

### Link to the related docs page

não-tem-link

**Comment by amandeepmittal** [comment]
Hi @kelwinxd, after adding the plugin to the `babel.config.js`, have you tried restarting the development server with `npx expo start --clear`?

**Comment by amandeepmittal** [comment]
Going to close this issue. If you are still facing it, please try the instruction from my previous message or share a minimal reproducible example.
