### ISSUE TITLE
[EXPO-49] - ERROR  Invariant Violation: No callback found with cbID....

### ISSUE THREAD

**Issue by Brunowilliang** [expo/expo#24870]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by markjpT** [comment]
trying to fix it

**Comment by Invertisment** [comment]
There was an update on my expo app on an android emulator and after performing the update the app was getting stuck on the splash screen.

I ran `expo-doctor` and it didn't say much except to install these two specific library versions:
```
+    "@expo/config-plugins": "~7.2.2",
+    "@expo/metro-config": "~0.10.0"
```
I installed them by forcefully adding them into `package.json` and now I get the same error as OP but it doesn't print into console and only shows up in the app (probably android binds later and doesn't print if it fails from the start).

These are my dependency versions:
```
  "dependencies": {
    "expo": "~49.0.21",
    "expo-status-bar": "~1.6.0",
    "react": "^18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.6",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@expo/prebuild-config": "~6.2.4",
    "@expo/webpack-config": "^19.0.0",
    "@types/jest": "^29.5.11",
    "@types/react": "~18.2.14",
    "babel-plugin-react-native-web": "^0.19.10",
    "expo-doctor": "^1.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "typescript": "^5.1.3"
  },
  "peerDependencies": {
    "expo-modules-autolinking": "~1.2.0",
    "@expo/config-plugins": "~7.2.2",
    "@expo/metro-config": "~0.10.0"
  },
```

**Comment by Invertisment** [comment]
I fixed my error by doing what this comment suggested: https://github.com/expo/expo/issues/19870#issuecomment-1310113475
I also have a "custom" `metro.config.js`.
