### ISSUE TITLE
Lottie-react-native bug causing crashes on expo-development-build

### ISSUE THREAD

**Issue by BryanMwangi** [expo/expo#24878]
### Summary

There seems to be a bug in the current supported version of lottie-react-native which currently is 5.1.6 according to expo documentation and expo supported version. When running the project on a device using both an eas build and local build, the app keeps crashing. This is the report I get from xcode:

<img width="461" alt="Screenshot 2023-10-16 at 5 16 44" src="https://github.com/expo/expo/assets/62949543/5cc8657f-b976-4ce6-ab61-769964e33481">

<img width="566" alt="Screenshot 2023-10-16 at 5 12 55" src="https://github.com/expo/expo/assets/62949543/d345ce21-e034-47c0-8982-512c23b09977">
[](url)

Currently I updated the expo sdk to now 49.0.13 but it seems support for lottie-react-native version 6.1.2 is only available on expo go and I cannot seem to make it work for my bare workflow project. This issue of memory leaks on ios seems to have been solved on later releases of lottie-react-native but the bug was persistent on 5.1.6. I hope this can be address accordingly.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

**package.json**

"expo": "^49.0.0",
    "expo-dev-client": "~2.4.11",
    "expo-doctor": "^1.1.3",
    "expo-splash-screen": "~0.20.5",
    "lottie-react-native": "5.1.6",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-native-safe-area-context": "4.6.3",
    "react-native-shared-element": "^0.8.8",
   

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
      Watchman: 2023.09.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/lib/ruby/gems/3.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 34.0.0
        System Images: android-33 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: bare

### Reproducible demo

import { View, Text } from "react-native";
import React from "react";
import LottieView from "lottie-react-native";

const LoadingSplashScreen = () => {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <LottieView
        source={require("../../../../assets/Images/Animations/yourCake Logo.json")}
        autoPlay
        loop
        style={{ height: "100%", width: "100%" }}
      />
    </View>
  );
};

export default LoadingSplashScreen;

**Comment by Kudo** [comment]
hi there! could you describe the details of the error of lottie-react-native 6.1.2 on sdk 48 project? i'm glad to reopen and investigate the issue if we can get a way to repro the problem.

**Comment by BryanMwangi** [comment]
> hi there! could you describe the details of the error of lottie-react-native 6.1.2 on sdk 48 project? i'm glad to reopen the issue and investigate the issue if we can get a way to repro the problem.

The issue is not that lottie-react-native 6.1.2 does not work, but for bare workflows using expo, for some reason expo recommends using lottie-react-native: "5.1.6" on SDK 49. There is no support for lottie-react-native 6.1.2 as far as I am concerned. Whenever I run npx expo-doctor this is what I get even with lottie-react-native 6.1.2 installed:

Some dependencies are incompatible with the installed expo version:

  lottie-react-native@6.3.1 - expected version: 5.1.6

Your project may not work correctly until you install the correct versions of the packages.

Fix with: npx expo install --fix

Found outdated dependencies

I hope support for lottie-react-native 6.1.2 may be available for bare workflows using expo SDK 49

**Comment by Kudo** [comment]
@BryanMwangi thanks for explaining the details. it's more clear to me.
for bare project or [development build](https://docs.expo.dev/develop/development-builds/introduction/), you can literally use any modules you want. the lottie-react-native@5.1.6 is just the version we were tested when releasing sdk 49. you can [suppress the warning](https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation), e.g.:

```diff
--- a/package.json
+++ b/package.json
@@ -19,5 +19,10 @@
   "devDependencies": {
     "@babel/core": "^7.20.0"
   },
+  "expo": {
+    "install": {
+      "exclude": ["lottie-react-native"]
+    }
+  },
   "private": true
 }
```

after that, running `npx expo start` or `npx expo install --check` will not show the warning anymore.

**Comment by BryanMwangi** [comment]
Ooh wow! That makes more sense. I will test this. In case any issues arise I will comment back. You're awesome @Kudo

**Comment by rumfiske** [comment]
Same problem here using expo SDK 49 and 	"lottie-react-native": "^6.4.1",

As soon as i go to a screen with lottie on it.
![qemu-system-x86_64_LSFwqq63op](https://github.com/expo/expo/assets/59709554/c9c74aa0-2687-4555-82d5-4e3a1d8ebf44)
