### ISSUE TITLE
[android] fix new JSC on arm64 builds

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2488]
Currently, the revision of JSC we are using occasionally causes crashes on arm64 builds. This is due to some JSC internals and differences on how things are handled on the different architectures. This is  not a problem currently as we don't enable arm64 builds, and Android devices with arm64 CPUs just use armv7 builds in emulation mode. However, tracking this because as we'll need to start supporting 64-bit builds next year we will eventually need to resolve this.

**Comment by tsapeta** [comment]
Closing this issue as the JSC already supports 64-bit builds - I created another to add such support to Expo client #4374
