### ISSUE TITLE
sendPushNotification function in docs returns status 400 [docs] 

### ISSUE THREAD

**Issue by nathantew14** [expo/expo#24895]
### Summary

In the minimal example given for setting up push notifications, a `sendPushNotification` function is provided in the code that sends a POST request to 'https://exp.host/--/api/v2/push/send', however, this gets me a status 400 response. 

Receiving a notification otherwise works using the Push Notification Tool.

I'm not sure if this is a documentation bug (outdated url?) or if it's something else, so I'm putting it here first.

```
// Can use this function below or use Expo's Push Notification Tool from: https://expo.dev/notifications
async function sendPushNotification(expoPushToken) {
  const message = {
    to: expoPushToken,
    sound: 'default',
    title: 'Original Title',
    body: 'And here is the body!',
    data: { someData: 'goes here' },
  };

  await fetch('https://exp.host/--/api/v2/push/send', {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Accept-encoding': 'gzip, deflate',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(message),
  });
}
```

### Link to the related docs page

https://docs.expo.dev/push-notifications/push-notifications-setup/#add-a-minimal-working-example

**Comment by nathantew14** [comment]
my bad, I was using the entire `ExpoPushToken` object rather than the `.data` part... 😅

**Comment by amandeepmittal** [comment]
Glad to know it is working on your end and you were able to find the issue! Thank you for closing it @nathantew14!
