### ISSUE TITLE
Picker backgroundColor hides caret symbol indicating dropdown

### ISSUE THREAD

**Issue by W7PEA** [expo/expo#2489]
### Environment

Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.1
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/mobilelast-d089ac86-47fc-4dde-8f2c-d95fd6a13d9e.tar.gz

Android Emulator 

### Steps to Reproduce

(Write your steps here:)
<Picker style={{backgroundColor: 'white',}}><Picker/>

### Expected Behavior
White background with default text color (dark) and the caret on the right to be that color. Ideally whatever `color` is set to.

### Actual Behavior
Caret no longer appears no matter what backgroundColor is used.

**Comment by brentvatne** [comment]
this should be posted to http://github.com/facebook/react-native where that components lives

**Comment by W7PEA** [comment]
Thanks, I'll look into that when we get an update with latest RN included.

**Comment by W7PEA** [comment]
https://github.com/facebook/react-native/issues/9434
