### ISSUE TITLE
Unsupported class file major version 64

### ISSUE THREAD

**Issue by amitsamanta996** [expo/expo#24901]
### Minimal reproducible example

expo run:android

### Summary

just did this
`npx create-expo-app --template`
then 
`expo run:android`

and this error
› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'F:\reactNative\wac\my-app\android\settings.gradle' (C:\Users\amits\.gradle\caches\8.0.1\scripts\f18w39ueglyq1mguwt76z9q3q).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.5.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33
        Build Tools: 33.0.2
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    npmPackages:
      expo: ~49.0.13 => 49.0.13
      react: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
    Expo Workflow: bare

**Comment by amitsamanta996** [comment]
sure, close all issue, better than fixing it.

**Comment by omar-bear** [comment]
@amitsamanta996 i fixed the same issue by fixing my java version to `java 11.0.2-open`
