### ISSUE TITLE
Expo proejct using react-navigation/stack crashes on prod build

### ISSUE THREAD

**Issue by ortutay** [expo/expo#24915]
### Minimal reproducible example

https://snack.expo.dev/@ortutay/ranting-blue-donuts

### Summary

The app in the repro works in local development mode, and also when I launch it through Expo Go, but it does not work when I do an eas build.

It crashes on startup.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by amandeepmittal** [comment]
I've tried reproducing this on my end with the latest SDK version and React Navigation library version. You can find this minimal reproducible example here: https://github.com/amandeepmittal/stacknav-crash-24915. I've also created a preview profile build using EAS and it is working.

Is the required dependency `react-native-gesture-handler` included in your project? Please check it.

**Comment by ortutay** [comment]
The dependency for gesture handler is not needed, and the bug continues if
I remove it

**Comment by amandeepmittal** [comment]
On checking React Navigation docs here: https://reactnavigation.org/docs/stack-navigator/#installation, it seems the react-native-gesture-handler is required (see Step 1). This is probably why it is working in Expo Go (since that library is already included in the sandbox app) but crashes when you are creating a standalone build (like preview) in your case.

**Comment by Whebcraft** [comment]
@ortutay  see this
![Screenshot 2023-10-19 at 17-41-39 Drawer Navigator React Navigation](https://github.com/expo/expo/assets/9988835/1b0de7c9-f14a-4572-9b82-1c8e6a2a09ca)

**Comment by ortutay** [comment]
Thanks, I was able to take the example from @amandeepmittal 's repo and build off of that.

I'm not sure why, but just adding the import of `react-native-gesture-handler` to my existing project did not work. There is probably some obscure dependency conflict.
