### ISSUE TITLE
Some dependencies are incompatible with the installed expo version

### ISSUE THREAD

**Issue by sh-shamsan** [expo/expo#24923]
### Summary

We're having issues with `react-native-webview`: 13.2.2 and `react-native-reanimated`: 3.3.0 and the bugs are solved in newer versions but are not compatible with our expo version. 

If we install the new versions and run `npx expo-doctor@latest` 
This check fails: Check that packages match versions required by installed Expo SDK

> Some dependencies are incompatible with the installed expo version:
>   react-native-webview@13.6.2 - expected version: 13.2.2
> Your project may not work correctly until you install the correct versions of the packages.

Can we ignore this or is there do we expect an upgrade for expo SDK? 

### What platform(s) does this occur on?

Android, iOS

### SDK Version

49.0.13

### Environment

    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.07.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ^0.19.9 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Minimal reproducible example

N/A

**Comment by okabe000** [comment]
I have sane issue, incompatible packages versions

**Comment by AdamGerthel** [comment]
I have a similar issue. `Keyframe` in react-native-reanimated is broken in ~3.6.0 which is the currently pinned version for Expo SDK 50.
