### ISSUE TITLE
EAS build - Fastlane fails

### ISSUE THREAD

**Issue by wallacerenan** [expo/expo#24929]
### Summary

Fail on build ios

`Creating Gymfile

Gymfile created

Successfully loaded '/Users/expo/workingdir/build/ios/Gymfile' 📄

+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

|                                                                  Detected Values from './Gymfile'                                                                   |

+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

| suppress_xcode_output | true                                                                                                                                        |

| clean                 | false                                                                                                                                       |

| scheme                | Sade                                                                                                                                        |

| configuration         | Release                                                                                                                                     |

| export_options        |                                                                                                                                             |

| export_xcargs         | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/tp/1f104nqx6yq986857sbfl3yh0000gn/T/turtle-v2-0a56ef4d-0844-49c7-852c-5771fa86a193.keychain" |

| disable_xcpretty      | true                                                                                                                                        |

| buildlog_path         | /Users/expo/workingdir/logs                                                                                                                 |

| output_directory      | ./build                                                                                                                                     |

+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

Resolving Swift Package Manager dependencies...

$ xcodebuild -resolvePackageDependencies -workspace ./Sade.xcworkspace -scheme Sade -configuration Release

▸ 2023-10-17 15:10:47.019 xcodebuild[4501:12936] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

▸ Command line invocation:

▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./Sade.xcworkspace -scheme Sade -configuration Release

▸ User defaults from command line:

▸     IDEPackageSupportUseBuiltinSCM = YES

▸ resolved source packages:

$ xcodebuild -showBuildSettings -workspace ./Sade.xcworkspace -scheme Sade -configuration Release

2023-10-17 15:10:48.594 xcodebuild[4505:13019] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...

2023-10-17 15:10:51.400 xcodebuild[4505:13042] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition

2023-10-17 15:10:51.679 xcodebuild[4514:13068] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

2023-10-17 15:10:52.136 xcodebuild[4514:13103] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition

Detected provisioning profile mapping: {:"com.maissaude.app"=>"7319c236-5a26-4332-9b1e-f798efb80196"}

+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

|                                                                                       Summary for gym 2.213.0                                                                                       |

+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+

| workspace                                             | ./Sade.xcworkspace                                                                                                                          |

| scheme                                                | Sade                                                                                                                                        |

| clean                                                 | false                                                                                                                                       |

| output_directory                                      | ./build                                                                                                                                     |

| output_name                                           | Sade                                                                                                                                        |

| configuration                                         | Release                                                                                                                                     |

| silent                                                | false                                                                                                                                       |

| skip_package_ipa                                      | false                                                                                                                                       |

| skip_package_pkg                                      | false                                                                                                                                       |

| export_options.method                                 | app-store                                                                                                                                   |

| export_options.provisioningProfiles.com.maissaude.app | 7319c236-5a26-4332-9b1e-f798efb80196                                                                                                        |

| export_xcargs                                         | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/tp/1f104nqx6yq986857sbfl3yh0000gn/T/turtle-v2-0a56ef4d-0844-49c7-852c-5771fa86a193.keychain" |

| build_path                                            | /Users/expo/Library/Developer/Xcode/Archives/2023-10-17                                                                                     |

| result_bundle                                         | false                                                                                                                                       |

| buildlog_path                                         | /Users/expo/workingdir/logs                                                                                                                 |

| destination                                           | generic/platform=iOS                                                                                                                        |

| suppress_xcode_output                                 | true                                                                                                                                        |

| xcodebuild_formatter                                  | xcpretty                                                                                                                                    |

| build_timing_summary                                  | false                                                                                                                                       |

| disable_xcpretty                                      | true                                                                                                                                        |

| skip_profile_detection                                | false                                                                                                                                       |

| xcodebuild_command                                    | xcodebuild                                                                                                                                  |

| skip_package_dependencies_resolution                  | false                                                                                                                                       |

| disable_package_automatic_updates                     | false                                                                                                                                       |

| use_system_scm                                        | false                                                                                                                                       |

| xcode_path                                            | /Applications/Xcode.app                                                                                                                     |

+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
....................................................................................
................................................................................................................
..................................................................................................

› Compiling expo-modules-core Pods/ExpoModulesCore » EXAppDefines.m

› Packaging expo-modules-core Pods/ExpoModulesCore » libExpoModulesCore.a

› Executing expo-modules-core Pods/ExpoModulesCore » Copy generated compatibility header

    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')

› Compiling expo Pods/Expo » Expo-dummy.m

› Compiling expo Pods/Expo » EXAppDefinesLoader.m

› Compiling expo-splash-screen Pods/EXSplashScreen » EXSplashScreenViewNativeProvider.m

› Packaging expo Pods/Expo » libExpo.a

› Compiling expo-splash-screen Pods/EXSplashScreen » EXSplashScreenViewController.m

› Compiling expo-splash-screen Pods/EXSplashScreen » EXSplashScreenService.m

› Compiling expo-splash-screen Pods/EXSplashScreen » EXSplashScreenModule.m

› Compiling expo-splash-screen Pods/EXSplashScreen » EXSplashScreen-dummy.m

› Compiling expo-image-loader Pods/EXImageLoader » EXImageLoader.m

› Compiling expo-image-loader Pods/EXImageLoader » EXImageLoader-dummy.m

› Compiling expo-font Pods/EXFont » EXFontScalersManager.m

› Packaging expo-image-loader Pods/EXImageLoader » libEXImageLoader.a

› Compiling expo-font Pods/EXFont » EXFontScaler.m

› Compiling expo-font Pods/EXFont » EXFontManager.m

› Compiling expo-font Pods/EXFont » EXFontLoaderProcessor.m

› Compiling expo-font Pods/EXFont » EXFontLoader.m

› Compiling expo-font Pods/EXFont » EXFont.m

› Compiling expo-font Pods/EXFont » EXFont-dummy.m

› Compiling expo-sharing Pods/ExpoSharing » ExpoSharing-dummy.m

› Packaging expo-sharing Pods/ExpoSharing » libExpoSharing.a

› Compiling expo-local-authentication Pods/ExpoLocalAuthentication » ExpoLocalAuthentication-dummy.m

› Compiling expo-linear-gradient Pods/ExpoLinearGradient » ExpoLinearGradient-dummy.m

› Packaging expo-local-authentication Pods/ExpoLocalAuthentication » libExpoLocalAuthentication.a

› Packaging expo-linear-gradient Pods/ExpoLinearGradient » libExpoLinearGradient.a

› Compiling expo-keep-awake Pods/ExpoKeepAwake » ExpoKeepAwake-dummy.m

› Compiling expo-head Pods/ExpoHead » ExpoHead-dummy.m

› Packaging expo-keep-awake Pods/ExpoKeepAwake » libExpoKeepAwake.a

› Packaging expo-splash-screen Pods/EXSplashScreen » libEXSplashScreen.a

› Executing expo-sharing Pods/ExpoSharing » Copy generated compatibility header

› Executing expo-local-authentication Pods/ExpoLocalAuthentication » Copy generated compatibility header

› Executing expo-linear-gradient Pods/ExpoLinearGradient » Copy generated compatibility header

› Executing Copy generated compatibility header

› Packaging expo-head Pods/ExpoHead » libExpoHead.a

› Compiling expo-document-picker Pods/ExpoDocumentPicker » ExpoDocumentPicker-dummy.m

› Executing expo-head Pods/ExpoHead » Copy generated compatibility header

› Compiling expo-file-system Pods/EXFileSystem » NSData+EXFileSystem.m

› Packaging expo-document-picker Pods/ExpoDocumentPicker » libExpoDocumentPicker.a

› Compiling expo-file-system Pods/EXFileSystem » EXTaskHandlersManager.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionUploadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionTaskDispatcher.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionResumableDownloadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionHandler.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionDownloadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXSessionCancelableUploadTaskDelegate.m

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystemLocalFileHandler.m

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystemAssetLibraryHandler.m

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystem.m

› Compiling expo-file-system Pods/EXFileSystem » EXFileSystem-dummy.m

› Compiling expo-file-system Pods/EXFileSystem » EXFilePermissionModule.m

› Compiling expo-image-picker Pods/ExpoImagePicker » ExpoImagePicker-dummy.m

› Packaging expo-image-picker Pods/ExpoImagePicker » libExpoImagePicker.a

› Executing expo-image-picker Pods/ExpoImagePicker » Copy generated compatibility header

› Executing Copy generated compatibility header

› Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest

› Compiling expo-application Pods/EXApplication » EXProvisioningProfile.m

› Compiling expo-application Pods/EXApplication » EXApplication.m

› Compiling expo-application Pods/EXApplication » EXApplication-dummy.m

› Packaging expo-file-system Pods/EXFileSystem » libEXFileSystem.a

› Packaging expo-application Pods/EXApplication » libEXApplication.a

› Compiling expo-constants Pods/EXConstants » EXConstantsService.m

› Compiling expo-constants Pods/EXConstants » EXConstantsInstallationIdProvider.m

› Compiling expo-constants Pods/EXConstants » EXConstants-dummy.m

› Packaging expo-constants Pods/EXConstants » libEXConstants.a

› Executing expo-constants Pods/EXConstants » Copy generated compatibility header

› Compiling Pods/Pods-Sade » Pods-Sade-dummy.m

› Packaging Pods/Pods-Sade » libPods-Sade.a

    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Sade' from project 'Sade')

    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Sade' from project 'Sade')

› Executing Sade » [CP] Check Pods Manifest.lock

› Executing Sade » Start Packager on http://localhost:8081

› Executing Sade » [Expo] Configure project

› Copying   ios/Sade/Supporting/Expo.plist ➜ ./Expo.plist

› Compiling Sade » SplashScreen.storyboard

› Preparing Sade » Info.plist

› Compiling Sade » main.m

› Compiling Sade » Sade_vers.c

› Compiling Sade » AppDelegate.mm

› Linking   Sade » Sade

❌  ld: library not found for -ld_classic

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	Ld /Users/expo/Library/Developer/Xcode/DerivedData/Sade-ckwtqtwlbyfhixbokyxfnoimjzdn/Build/Intermediates.noindex/ArchiveIntermediates/Sade/InstallationBuildProductsLocation/Applications/Sade.app/Sade normal (in target 'Sade' from project 'Sade')

▸ (1 failure)

2023-10-17 15:10:52.558 xcodebuild[4541:13150] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

** ARCHIVE FAILED **

The following build commands failed:

	Ld /Users/expo/Library/Developer/Xcode/DerivedData/Sade-ckwtqtwlbyfhixbokyxfnoimjzdn/Build/Intermediates.noindex/ArchiveIntermediates/Sade/InstallationBuildProductsLocation/Applications/Sade.app/Sade normal (in target 'Sade' from project 'Sade')

(1 failure)

Exit status: 65

+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.213.0                 |

| sdk         | iPhoneOS16.4.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above

Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.`

### SDK Version

49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
      npm: 9.7.1 - ~/.nvm/versions/node/v16.20.0/bin/npm
      Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: bare

### Minimal reproducible example

expo init
include all libs on my package.json
yarn install
run with expo prebuild
eas build --profile development --platform ios

**Comment by wetivity** [comment]
I'm getting the same issue. it was working a few builds ago and suddenly encounters this .
<img width="1140" alt="image" src="https://github.com/expo/expo/assets/147910822/43a00673-b4c8-4712-98de-66ec4d5016d2">

<img width="1202" alt="image" src="https://github.com/expo/expo/assets/147910822/4f9fbb33-cbb7-4edf-aa0a-9cf3f1904006">

xcode error is : ld: library not found for -ld_classic

**Comment by laimisdz** [comment]
What worked for me was removing the 'ld_classic' flag on XCode:

- Select your project
- Select Build Settings > All > Linking - General
- Remove `ld_classic` from Other Linker Flags

I'm pretty new in Expo managed workflow. Does somebody know if it's possible to automate this removal of `ld_classic` through Expo prebuild? (I mean, by adding some setting in app.json/app.config.js)

**Comment by brentvatne** [comment]
you may encounter this error if you are running xcode 15 locally and 14 on eas build. see: https://expo.dev/changelog/2023/09-28-new-xcode-ios

also see: https://github.com/facebook/react-native/issues/39713

**Comment by Resource-1** [comment]
> I'm getting the same issue. it was working a few builds ago and suddenly encounters this . <img alt="image" width="1140" src="https://user-images.githubusercontent.com/147910822/276442253-43a00673-b4c8-4712-98de-66ec4d5016d2.png">
> 
> <img alt="image" width="1202" src="https://user-images.githubusercontent.com/147910822/276442261-4f9fbb33-cbb7-4edf-aa0a-9cf3f1904006.png">
> xcode error is : ld: library not found for -ld_classic

Same issue reproduce for xcode 15 and expo 49
