### ISSUE TITLE
ExponentPushToken is undefined in production 

### ISSUE THREAD

**Issue by evertondsvieira** [expo/expo#24936]
### Minimal reproducible example

https://github.com/evertondsvieira/notification

### Summary

My ExponentPushToken is undefined when I put the application into production on Android but it is visible in development in expo go

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD    
    Expo Workflow: managed

**Comment by ViniDevBR** [comment]
Im wth this problem too. I did a repo like this just to test. And UNDEFINED in production, but works good in DEV mode
"expo-notifications": "0.20.1",

**Comment by lucaswalmor** [comment]
Estou com mesmo problema

    "expo": "~49.0.15",
    "react-native": "0.72.6",
    "react": "18.2.0",
    
    não consigo recber o token após gerar o APK, localhost funciona normalmente
