### ISSUE TITLE
Location.getCurrentPositionAsync doesnt get location on One Plus 3

### ISSUE THREAD

**Issue by cklinx** [expo/expo#2494]
Hi,
i tried to execute this [Snack Code](https://snack.expo.io/rJ0EuSAMb) on One Plus 3 - A3003 with Oxygen 5.0.6 and Android 8.0.0 and its looping infinitely so doesnt get the location.

Its not working with different SDK too.

Other devices work perfectly.

Location.getProviderStatusAsync() => everythink is enabled.

Any idea? Its bug?

Thanks in advance

**Comment by raajnadar** [comment]
Check my comment here https://github.com/expo/expo/issues/946#issuecomment-385145024

**Comment by cklinx** [comment]
Hi @raajnadar,
the phone is set to "High accuracy" so i really dont know how solve it.

The result from `Location.getProviderStatusAsync()` 

```javascript
{
    "gpsAvailable": true,
    "locationServicesEnabled": true,
    "networkAvailable": true, 
    "passiveAvailable": true,
}
```

Thanks

**Comment by vinitkumargoel** [comment]
Same for me. Working fine IOS Simulator but android expo it not working.

` _getLocationAsync = async () => {
        let { status } = await Permissions.askAsync(Permissions.LOCATION);
        if (status !== 'granted') {
          this.setState({
            errorMessage: 'Permission to access location was denied',
          });
        }
        let location = await Location.getCurrentPositionAsync({});
        this.setState({ 
            longitude: location.coords.longitude,
            latitude: location.coords.latitude,
        });
        
    };`

**Comment by omorhefere** [comment]
@vinitkumargoel I have the same issue as well

**Comment by ltankey** [comment]
I have a similar (related?) problem with iOS devices, where `getCurrentPositionAsync` hangs for about 10 seconds in high accuracy mode. Can you try setting `enableHighAccuracy: false`?

If I set the above I get lat/long details back instantly, whereas if I use the high accuracy mode, it takes about 10 seconds to resolve (which looks to some like it won't resolve at all).


The strange thing is the returned `accuracy` reading is actually _higher_ than if I make the same call with `enabledHighAccuracy: true`. This worked fine on Expo 27 and has only happened after we made the jump through to 31.
