### ISSUE TITLE
Expo BarCodeScanner API's type props do not work on SDK v49.0.0

### ISSUE THREAD

**Issue by JakeCroz1** [expo/expo#24948]
### Minimal reproducible example

https://snack.expo.dev/@kingcodeman/expo-barcode-scanner-api

### Summary

**[Issue]:** The Expo BarCodeScanner API's type and barCodeTypes props do not work with SDK v49.0.0. However, the mentioned props do work on SDK v48.0.0 and below.
       
**[Reproduce-Issue]:** Run the following code below using SDK v49.0.0. You will notice that the flip camera feature does not work implying that type prop does not work. The barCodeTypes prop is configured to only scan QR codes. If you scan barcodes other than QR codes, you will notice that the barcodes do get scanned implying that the barCodeTypes prop does not work. 

**[Test-Environment]:** 
_Expo Go_
- Client version: 1017565
- Supported SDKs: 47, 48, and 49

_Physical device_ 
- Model Name: iPhone 12 Pro
- IOS Version 16.6.1

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    Expo Workflow: managed

**Comment by animaonline** [comment]
Any updates on this?

**Comment by JakeCroz1** [comment]
> Any updates on this?

No updates yet. Seems to be stale.

**Comment by JakeCroz1** [comment]
Any updates on this?
