### ISSUE TITLE
 No signature of method: org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.kotlinVersion() is applicable for argument types: () values: []

### ISSUE THREAD

**Issue by efstathiosntonas** [expo/expo#24945]
### Minimal reproducible example

https://no-snack.com

### Summary

After the changes where `minAndroidSDK` is now 23 all modules fail to install with this error on a bare react-native project with expo-modules-core. Probably releated PR: https://github.com/expo/expo/pull/24201

```
Build file '/Users/stathis/IdeaProjects/xxxxxxx/node_modules/expo-image-loader/android/build.gradle' line: 25

A problem occurred evaluating project ':expo-image-loader'.
> No signature of method: org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.kotlinVersion() is applicable for argument types: () values: []
```

by removing the `()` -> `ext.kotlinVersion` it builds fine.

```json
    "react-native": "0.72.6",
    "expo": "49.0.15",
    "expo-asset": "8.13.0",
    "expo-clipboard": "4.7.0",
    "expo-constants": "15.2.0",
    "expo-crypto": "12.7.0",
    "expo-file-system": "15.8.0",
    "expo-font": "11.8.0",
    "expo-image-manipulator": "11.6.0",
    "expo-location": "16.4.0",
    "expo-modules-core": "1.9.0",
    "expo-network-addons": "0.4.0"
```

### Environment

```bash 
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 3.6.4 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.15 => 49.0.15 
      react: ^18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: bare
```

**Comment by efstathiosntonas** [comment]
Hey @Kudo, please take a look into this, it shouldn't be closed.

**Comment by Kudo** [comment]
@efstathiosntonas it works fine for me on a `yarn create expo -t blank@sdk-49 sdk49` project with `expo-image-loader` and `expo-build-properties` to set android.minSdkVersion=23. so please help to create a minimal reproducible example project and upload to some git repository. we are happy to reopen if we can repro the issue. thanks!

**Comment by efstathiosntonas** [comment]
@Kudo thanks for looking into it. I'm using bare react-native with modules, sorry for not mentioning it earlier. 

Will try to create a reproducer.

**Comment by josephyanks** [comment]
@efstathiosntonas were you ever able to fix this issue? we are running into the same thing now with bare RN

**Comment by efstathiosntonas** [comment]
@josephyanks just remove the `()` from `kotlinVersion()`

this is a patch I applied on `expo-modules-core`, similar patches must be applied on all expo-xx modules: 

```patch
diff --git a/node_modules/expo-modules-core/.DS_Store b/node_modules/expo-modules-core/.DS_Store
new file mode 100644
index 0000000..16d1d35
Binary files /dev/null and b/node_modules/expo-modules-core/.DS_Store differ
diff --git a/node_modules/expo-modules-core/android-annotation-processor/build.gradle b/node_modules/expo-modules-core/android-annotation-processor/build.gradle
index 411d356..e541808 100644
--- a/node_modules/expo-modules-core/android-annotation-processor/build.gradle
+++ b/node_modules/expo-modules-core/android-annotation-processor/build.gradle
@@ -20,7 +20,7 @@ buildscript {
   // Ensures backward compatibility
   ext.getKotlinVersion = {
     if (ext.has("kotlinVersion")) {
-      ext.kotlinVersion()
+      ext.kotlinVersion
     } else {
       ext.safeExtGet("kotlinVersion", "1.6.10")
     }
diff --git a/node_modules/expo-modules-core/android-annotation/build.gradle b/node_modules/expo-modules-core/android-annotation/build.gradle
index 3db0aa8..7cc9ff1 100644
--- a/node_modules/expo-modules-core/android-annotation/build.gradle
+++ b/node_modules/expo-modules-core/android-annotation/build.gradle
@@ -20,7 +20,7 @@ buildscript {
   // Ensures backward compatibility
   ext.getKotlinVersion = {
     if (ext.has("kotlinVersion")) {
-      ext.kotlinVersion()
+      ext.kotlinVersion
     } else {
       ext.safeExtGet("kotlinVersion", "1.6.10")
     }
```

**Comment by efstathiosntonas** [comment]
@josephyanks glad you sorted this out, can you share the solution? I also got too many...

**Comment by efstathiosntonas** [comment]
@Kudo is what @josephyanks describing something that should be looked at?

**Comment by josephyanks** [comment]
> @josephyanks glad you sorted this out, can you share the solution? I also got too many...

The fix is just to delete the `kotlinVersion` from `gradle.properties`. I'm not sure why it was declared there in the first place. It might be worth doing a check in the `if (ext.has("kotlinVersion")) {` block to ensure that it's not declared in the properties, since that is what is causing the `No signature of method: org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.kotlinVersion() is applicable for argument types: () values: []` error.

**Comment by efstathiosntonas** [comment]
thanks @josephyanks, I had the same thing, I can't remember either why it was in there. One pain less 😓, finally got rid of 15 patches

**Comment by amarjanica** [comment]
For those who stumble on this issue via google search, there's also a quick and ugly workaround: applying `find ./node_modules -name "build.gradle" -exec sed -i 's/kotlinVersion()/kotlinVersion/g' {} +` as a `postinstall` script.

**Comment by linonetwo** [comment]
Confirmed this works. Does this need to done on my side? Can expo do this in its postinstall?

If so, maybe this issue should be opened.

**Comment by efstathiosntonas** [comment]
@lukmccall hi Lucas, I believe this issue needs some attention 😎

**Comment by redbluenat** [comment]
In my case, I had to remove kotlinVersion=1.8.0 from `gradle.properties` and add it to build.gradle:

` kotlinVersion = { -> "1.8.0" }`

**Comment by josephyanks** [comment]
> In my case, I had to remove kotlinVersion=1.8.0 from `gradle.properties` and add it to build.gradle:
> 
> ```
> buildscript {
>     ext {
>  kotlinVersion = { -> "1.8.0" }
> ```

I think this is the correct approach most of the time. I think that any solution that does something like the aforementioned `sed` replacements at compile time is not ideal and potentially dangerous. If expo wanted to do something at a library-level, I'd recommend using a different name from `kotlinVersion` since it's so common across many libraries, and a single wrong implementation can cause these very obscure errors that are hard to track down. Maybe `findKotlinVersion()` or something.

**Comment by ChristopherGabba** [comment]
I have a non-ejected expo project (aka managed workflow) and I just experienced this issue. I can't access the main build.gradle file without using `expo-prebuild`. What is the solution to this? Patch all 20+ of my expo modules with the mentioned above patch?
