### ISSUE TITLE
Expo Speech iOS emulator does not work, there are warnings even if it works on the real device

### ISSUE THREAD

**Issue by mucahitdev** [expo/expo#24953]
### Minimal reproducible example

https://snack.expo.dev/@koksoft/speech

### Summary

I don't have a real iOS device, so I had to get a friend from me for testing.

**iOS Bundling complete 101ms
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  Sending `Exponent.speakingStarted` with no listeners registered.
 WARN  Sending `Exponent.speakingStopped` with no listeners registered.**

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed

 "expo-speech": "~11.3.0",

**Comment by exzos28** [comment]
The same

**Comment by alea12** [comment]
I've encountered a similar issue. Notably, I also face this problem on Expo when using an real iOS device. Have you found a solution?

**Comment by mucahitdev** [comment]
Unfortunately, I couldn't find it. Luckily it works on the device :D

**Comment by AliZaib-Emumba** [comment]
On simulator sometimes it also gives the error
`AVAudioSession_iOS.mm:2156 Error: category option 'defaultToSpeaker' is only applicable with category 'playAndRecord'`

**Comment by EOMZON** [comment]
I have encountered the same problem, have you solved it？

**Comment by Jankaz2** [comment]
I have the same issue on both ios emulator and real device. It works on android so it's not the problem with my code. Any solutions?

**Comment by mucahitdev** [comment]
https://github.com/expo/expo/blob/de4a9eff53ef2e0c1aa903507db985f55f07f773/packages/expo-speech/ios/ExpoSpeech.podspec#L13 check version @Jankaz2

**Comment by Jankaz2** [comment]
I have got simulator with `iOS 17.0.4` and >17 on my real device @mucahitdev
