### ISSUE TITLE
Fresh new app from bun create expo --template expo-template-tabs doesn't start

### ISSUE THREAD

**Issue by dimaportenko** [expo/expo#24959]
### Minimal reproducible example

https://github.com/dimaportenko/expo-template-tabs-issue

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I've just created a new app and tried to run it. 

1. bun create expo --template expo-template-tabs test
2. cd test
3. bunx expo start
4. i - to run iOS

See the following error 

```
iOS Bundling complete 5058ms
 ERROR  Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

![CleanShot 2023-10-20 at 10 45 42@2x](https://github.com/expo/expo/assets/6594232/de3126f0-431e-42cd-b94d-9b261868a70a)

![CleanShot 2023-10-20 at 10 45 49@2x](https://github.com/expo/expo/assets/6594232/31955e4b-bdb4-4b88-a58f-4b8eb1ef8ae6)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/dmitriyportenko/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed

**Comment by marklawlor** [comment]
It looks like bun is using a different dependency resolution for its peerDeps, which is causing two versions of `react-native-safe-area-context` to be installed. I would recommend simply upgrading  (or using resolutions/overrides) to `react-native-safe-area-context@4.7.3` to keep all on the same version. I'll investigate updating the template

**Comment by danstepanov** [comment]
@marklawlor minimum reproduction here `npx create-expo-stack myapp --expoRouter --bun`. Going to try your suggested fix.

**Comment by danstepanov** [comment]
simply passing a `^` addresses the issue, other dependency managers (npm, yarn, pnpm) don't trigger this issue 

### Before

`"react-native-safe-area-context": "4.6.3"`

### After

`"react-native-safe-area-context": "^4.6.3"`

I'll have create-expo-stack include the `^` only if it the user is using bun as you will receive the following warning when running your project if your `react-native-safe-area-context` version is higher than `v4.6.3`:

<img width="655" alt="Screenshot 2023-11-01 at 6 54 12 PM" src="https://github.com/expo/expo/assets/5482800/61aaa088-8bec-4fec-a630-c26ccfc7d4ec">

**Comment by danstepanov** [comment]
Thanks to input from @marklawlor, I simply have all of the relevant templates use the latest version of `react-native-safe-area-context` by using `"react-native-safe-area-context": "^4.6.3"` in the `package.json` as well as the following at the bottom of the `package.json`:

```
"expo": {
    "install": {
        "exclude": ["react-native-safe-area-context"]
    }
}
```

Source: https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation
