### ISSUE TITLE
"npm install -g expo-cli" doesn't update expo-cli

### ISSUE THREAD

**Issue by bzhassan** [expo/expo#24957]
### Summary

When I run my expo project using `expo start`, I am provided an error to update expo-cli. 
I run the update command `npm install -g expo-cli`. The update seems to go through successfully but when I run `expo start` again, the same error appears. 

I've provided the outputs in the terminal when running `expo start` and `npm install -g expo-cli` in the minimum reproducible example section of this report.

### SDK Version

"expo": "^47.0.13"

### Environment

```
npx: installed 2 in 1.652s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 31.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.13 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 17.0.1 => 17.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-47.0.0.tar.gz => 0.70.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Minimal reproducible example

When I run `expo start` I'm presented with the following errors:
```
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.3.10).                │
│   You are currently using expo-cli 4.2.1                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│   This version of expo-cli is not supported anymore.                      │
│   It's highly recommended to update to the newest version.                │
│                                                                           │
│   The API endpoints used in this version of expo-cli might not exist,     │
│   any interaction with Expo servers may result in unexpected behaviour.   │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘
```
After these errors the Metro builder starts running and I'm able to run my project without any issues. 

When I run `npm install -g expo-cli` it successfully completes the update. The provided output is below:
```
npm install -g expo-cli
npm WARN deprecated expo-cli@6.3.10: The global Expo CLI has been superseded by 'npx expo' and eas-cli –– Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
/Users/brendanhassan/.npm-global/bin/expo -> /Users/brendanhassan/.npm-global/lib/node_modules/expo-cli/bin/expo.js
/Users/brendanhassan/.npm-global/bin/expo-cli -> /Users/brendanhassan/.npm-global/lib/node_modules/expo-cli/bin/expo.js
npm WARN @expo/webpack-config@18.1.0 requires a peer of expo@^48.0.17 but none is installed. You must install peer dependencies yourself.
npm WARN expo-pwa@0.0.125 requires a peer of expo@* but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

+ expo-cli@6.3.10
added 5 packages from 8 contributors and updated 36 packages in 56.748s
```
After this update occurs and I run `expo start`, I get the same error as before:

```
expo start
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.3.10).                │
│   You are currently using expo-cli 4.2.1                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│   This version of expo-cli is not supported anymore.                      │
│   It's highly recommended to update to the newest version.                │
│                                                                           │
│   The API endpoints used in this version of expo-cli might not exist,     │
│   any interaction with Expo servers may result in unexpected behaviour.   │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘
```

I've tried running `npm install -g expo-cli` multiple times and even uninstalling/reinstalling. 

Would like to update my expo-cli as I'm looking at getting all security updates before I start developing new apps as I don't want any issues if I eventually build and deploy my apps into App Stores in the future.

**Comment by Kudo** [comment]
hi there!

could you share your output of the following commands?
- `which expo`
- `expo --version`
- `which expo-cli`
- `expo-cli --version`

btw, the global expo cli was deprecated, we recommend to use the [`npx expo`](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421) - the local cli instead.

**Comment by bzhassan** [comment]
> hi there!
> 
> could you share your output of the following commands?
> 
> * `which expo`
> * `expo --version`
> * `which expo-cli`
> * `expo-cli --version`
> 
> btw, the global expo cli was deprecated, we recommend to use the [`npx expo`](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421) - the local cli instead.

```
which expo
/usr/local/bin/expo
```

```
expo --version
4.2.1
```

```
which expo-cli
expo-cli not found
```

```
expo-cli --version
zsh: command not found: expo-cli
```

Interesting, it seems I don't have expo-cli installed at all when I created the project and since then always ran it using the expo-cli. When I first got this issue I deleted expo-cli and tried reinstalling it, still got the issue and just delayed finding a resolution. 

I just ran `npx expo start` and the errors don't appear now. 

Just an idea for improvement with the situation. 
It might actually be a good idea to add a warning when someone uses expo-cli to say that "as of xxxx expo CLI is deprecated. It is recommended to use `npx expo`" this will help someone who is still having issues to know the changes and what to do now.

**Comment by Kudo** [comment]
> Just an idea for improvement with the situation.
It might actually be a good idea to add a warning when someone uses expo-cli to say that "as of xxxx expo CLI is deprecated. It is recommended to use npx expo" this will help someone who is still having issues to know the changes and what to do now.

thanks for the suggestion. we actually did
![Screenshot 2023-10-25 at 1 45 29 PM](https://github.com/expo/expo/assets/46429/f6ea10fd-7374-43b3-95bc-2c794b9398d2)

the reason is that expo-cli@4.2.1 is too old to have this outdated message 😅
please clarify how your `/usr/local/bin/expo` be installed. it looks like when you run `npm install -g expo-cli`, it doesn't update the /usr/local/bin/expo for you.

**Comment by bzhassan** [comment]
> > Just an idea for improvement with the situation.
> > It might actually be a good idea to add a warning when someone uses expo-cli to say that "as of xxxx expo CLI is deprecated. It is recommended to use npx expo" this will help someone who is still having issues to know the changes and what to do now.
> 
> thanks for the suggestion. we actually did ![Screenshot 2023-10-25 at 1 45 29 PM](https://user-images.githubusercontent.com/46429/277885683-f6ea10fd-7374-43b3-95bc-2c794b9398d2.png)
> 
> the reason is that expo-cli@4.2.1 is too old to have this outdated message 😅 please clarify how your `/usr/local/bin/expo` be installed. it looks like when you run `npm install -g expo-cli`, it doesn't update the /usr/local/bin/expo for you.

Thanks for the response. I'm not sure how `/usr/local/bin/expo` was installed. I do know that I've created expo projects as was stated on the expo and react native websites before the changes with npx. I've just been using npm to install any packages as well. Looking at my package.json in my repo for the project (last commit 8mths ago before all the latest updates I made to expo & expo-cli) it says:

```
    "expo": "^47.0.13",
    "expo-cli": "^5.5.1",
```

My guess is it's a project issue as my project is really old and I didn't update expo-cli until after it was deprecated - so my version of expo-cli was old and as it's deprecated I'm unable to update to the latest expo-cli version but `npx expo` works as I've updated expo... or is there something else wrong.

If this is the case, will running `npx expo` commands have an issue because expo-cli is so out of date or as `npx expo` uses `@expo/cli` there will be no issues?

If I create new expo projects using `npx create-expo-app projectName` will there be any issues due to my expo-cli being outdated or will it use the latest version of expo as `@expo/cli` is local within the project itself?

**Comment by Kudo** [comment]
i'm glad you ask this good question. you don't have to add `expo-cli` or `@expo/cli` as project dependencies or devDependencies. with the local cli, the `expo` will include the corresponding `@expo/cli` for you. for instance,
- `expo@47.0.14` includes `@expo/cli@0.4.11`
- `expo@49.0.16` includes `@expo/cli@0.10.14`
all you need is the `expo` package. in such way we could ensure in every sdk versions, when running `npx expo`, it is supported and you would never encounter outdated expo-cli issue.

**Comment by bzhassan** [comment]
> i'm glad you ask this good question. you don't have to add `expo-cli` or `@expo/cli` as project dependencies or devDependencies. with the local cli, the `expo` will include the corresponding `@expo/cli` for you. for instance,
> 
> * `expo@47.0.14` includes `@expo/cli@0.4.11`
> * `expo@49.0.16` includes `@expo/cli@0.10.14`
> 
> all you need is the `expo` package. in such way we could ensure in every sdk versions, when running `npx expo`, it is supported and you would never encounter outdated expo-cli issue.

Okay, I think I get it. Previously `expo` and `expo-cli` were different (expo SDK and CLI). Now both is in one (`expo` has both `@expo/cli` and the SDK) - so if `expo` is updated to the latest version it means both the SDK and CLI are at the latest versions.

This means, for example if a potential employer or another developer has access to an expo project they can simply run `npx expo start` and run the developed project - as long as they have node and xcode or android studio and run `npm install`. Before someone would need to have node, install `expo` SDK and `expo-cli` then `npm install`.

In my situation, as long as I keep `expo` updated there shouldn't be any issues?

**Comment by Kudo** [comment]
yes exactly. if you encountered any issues, please let us know.
