### ISSUE TITLE
[expo-updates] [SDK 49] Presence of expo-updates causes build to crash on launch of ios app

### ISSUE THREAD

**Issue by ahmed-sharief5** [expo/expo#24958]
### Minimal reproducible example

Cannot create a snack as its in the existing project

### Summary

The presence of expo-updates causes production and simulator builds to crash on launch of ios app. I discovered this after upgrading a project to SDK 49

I have tried by creating a new test repo as suggested in #23382 by @wschurman and there was no crash. But when expo updates is been integrated in the existing project then the app is getting crashed at launch

Attaching the crash report file
[er-crash-report.log](https://github.com/expo/expo/files/13050199/er-crash-report.log)

### Environment

`eas update:configure`
`npx expo run:ios --configuration Release`

using below packages 

```
"expo": "^49.0.0",
"expo-updates": "~0.18.16",
"react-native": "0.72.6",
```

**Comment by wschurman** [comment]
What's the value of the `updates` key of your app config (`app.json`)?

**Comment by ahmed-sharief5** [comment]
Hi @wschurman 
This is my app.json file 

```
{
  "expo": {
    "name": "EmaanReviver",
    "slug": "emaan-reviver",
    "owner": "emaanreviver",
    "version": "2.0.0",
    "runtimeVersion": "2.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash-light.png",
      "backgroundColor": "#FFFFFF",
      "resizeMode": "cover"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.emaanreviver.emaanreviver",
      "usesAppleSignIn": true,
      "userInterfaceStyle": "automatic",
      "requireFullScreen": true,
      "infoPlist": {
        "UIBackgroundModes": [
          "remote-notification",
          "fetch",
          "audio"
        ],
        "UISupportedInterfaceOrientations": [
          "UIInterfaceOrientationLandscapeRight",
          "UIInterfaceOrientationLandscapeLeft",
          "UIInterfaceOrientationPortrait"
        ]
      },
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.emaanreviver.emaanreviver",
      "userInterfaceStyle": "automatic",
      "googleServicesFile": "./google-services.json"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "<project-id>"
      }
    },
    "userInterfaceStyle": "automatic",
    "scheme": "com.emaanreviver.emaanreviver",
    "currentFullName": "@emaanreviver/emaan-reviver",
    "originalFullName": "@emaanreviver/emaan-reviver",
    "plugins": [
      "@react-native-firebase/app",
      "@react-native-firebase/crashlytics",
      "expo-apple-authentication",
      "expo-screen-orientation",
      [
        "expo-updates",
        {
          "username": "emaanreviver"
        }
      ]
    ],
    "updates": {
      "url": "https://u.expo.dev/<project-id>",
      "requestHeaders": {
        "expo-channel-name": "testing"
      }
    }
  }
}

```

**Comment by ahmed-sharief5** [comment]
Attaching one more crash report which generated when i tried to re configure everything again for expo updates 
[er-crash-report-1.log](https://github.com/expo/expo/files/13059920/er-crash-report-1.log)

I have followed this document

[https://docs.expo.dev/eas-update/updating-your-app/](url)

**Comment by ahmed-sharief5** [comment]
I have further debugged and could find out where its causing the issue and found the error in below line in `AppController.swift.` It occurs in start() function 

```
precondition(!isStarted, "AppController:start should only be called once per instance")
```

and when i try to print the isStarted it prints twice. Below are the logs from debugging in xcode

```
{"code":"None","timestamp":1697879087000,"message":"AppController sharedInstance created","level":"info"}
🟢 {"timestamp":1697879087000,"message":"Updates state is reset, state = idle, context = UpdatesStateContext(isUpdateAvailable: false, isUpdatePending: false, isRollback: false, isChecking: false, isDownloading: false, isRestarting: false, latestManifest: nil, downloadedManifest: nil, checkError: nil, downloadError: nil)","code":"None","level":"info"}
🟢 {"timestamp":1697879087000,"code":"None","message":"sendUpdateStateChangeEventToBridge(): type = restart","level":"info"}
🟡 {"level":"warn","message":"EXUpdates: Could not emit event: name = Expo.nativeUpdatesStateChangeEvent, type = restart. Event will be emitted when the bridge is available","timestamp":1697879087000,"code":"JSRuntimeError"}
is started 0
is started 1
```

Below is the code i modified to debug 

```
public func start() {
    NSLog("is started %d", isStarted);
    precondition(!isStarted, "AppController:start should only be called once per instance")

    if !config.isEnabled {
      let launcherNoDatabase = AppLauncherNoDatabase()
      launcher = launcherNoDatabase
      launcherNoDatabase.launchUpdate(withConfig: config)

      delegate.let { _ in
        DispatchQueue.main.async { [weak self] in
          if let strongSelf = self {
            strongSelf.delegate?.appController(strongSelf, didStartWithSuccess: strongSelf.launchAssetUrl() != nil)
            strongSelf.sendQueuedEventsToBridge()
          }
        }
      }

      return
    }

    if config.updateUrl == nil {
      NSException(
        name: .internalInconsistencyException,
        reason: "expo-updates is enabled, but no valid URL is configured under EXUpdatesURL. If you are making a release build for the first time, make sure you have run `expo publish` at least once."
      )
      .raise()
    }

    if config.scopeKey == nil {
      NSException(
        name: .internalInconsistencyException,
        reason: "expo-updates was configured with no scope key. Make sure a valid URL is configured under EXUpdatesURL."
      )
      .raise()
    }

    isStarted = true

    purgeUpdatesLogsOlderThanOneDay()

    do {
      try initializeUpdatesDirectory()
      try initializeUpdatesDatabase()
    } catch {
      emergencyLaunch(fatalError: error as NSError)
      return
    }

    UpdatesBuildData.ensureBuildDataIsConsistentAsync(database: database, config: config)

    errorRecovery.startMonitoring()

    loaderTask = AppLoaderTask(
      withConfig: config,
      database: database,
      directory: updatesDirectory!,
      selectionPolicy: selectionPolicy(),
      delegateQueue: controllerQueue
    )
    loaderTask!.delegate = self
    loaderTask!.start()
  }

```

**Comment by wschurman** [comment]
Sounds like `start` is being called twice. I'm not aware of any known bugs that could cause this. My recommendation is to breakpoint in the start method while debugging to see what the two callsites are.

**Comment by ahmed-sharief5** [comment]
After reinstalling the expo-updates package with the below commands throwing me the below error 

**Commands:** 

```
npx expo install expo-updates
eas update:configure
npx expo prebuild 
cd ios && arch -x86_64 pod update && cd ../
```

below pods have been installed for expo-updates package 

```[Hermes] Using the release tarball from Maven Central
Downloading dependencies
Installing ASN1Decoder (1.9.0)
Installing EASClient (0.6.0)
Installing EXJSONUtils (0.7.1)
Installing EXManifests (0.7.2)
Installing EXStructuredHeaders (3.3.0)
Installing EXUpdates (0.18.16)
Installing EXUpdatesInterface (0.10.1)
Installing ReachabilitySwift (5.0.0)```

**Error:** 

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset in NSBundle main.jsbundle. Check that expo-updates is installed correctly, and verify that assets are present in the ipa file.'

*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112e4c8a8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000109c6409c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000112e4c44c -[NSException init] + 0
	3   EmaanReviver                        0x0000000104374e60 $sSq9EXUpdatesE7requireyxSSF + 448
	4   EmaanReviver                        0x000000010433e9e0 $s9EXUpdates17EmbeddedAppLoaderC13downloadAssetyyAA06UpdateF0CFyyYbcfU_ + 1552
	5   EmaanReviver                        0x0000000104380364 $sIegh_IeyBh_TR + 48
	6   libdispatch.dylib                   0x0000000112c3c0f0 _dispatch_call_block_and_release + 24
	7   libdispatch.dylib                   0x0000000112c3d93c _dispatch_client_callout + 16
	8   libdispatch.dylib                   0x0000000112c45bd8 _dispatch_lane_serial_drain + 916
	9   libdispatch.dylib                   0x0000000112c4691c _dispatch_lane_invoke + 420
	10  libdispatch.dylib                   0x0000000112c532f8 _dispatch_root_queue_drain_deferred_wlh + 324
	11  libdispatch.dylib                   0x0000000112c52754 _dispatch_workloop_worker_thread + 488
	12  libsystem_pthread.dylib             0x00000001156d7878 _pthread_wqthread + 284
	13  libsystem_pthread.dylib             0x00000001156d663c start_wqthread + 8
)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by wschurman** [comment]
This generally indicates that the JS bundle is not being included in the build. When you press build in xcode a bundler should open and the bundle should be built. Maybe something isn't working there?

**Comment by ahmed-sharief5** [comment]
I have managed to resolve the above error by changing some lines of code in AppDelegate.mm file 

//  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
//  rootViewController.view = rootView;
//  self.window.rootViewController = rootViewController;
  self.window.rootViewController.view = rootView;


Commented out the above 3 lines and added the new line

**Comment by ahmed-sharief5** [comment]
Attaching the screenshots of the breakpoints 

<img width="1471" alt="image" src="https://github.com/expo/expo/assets/19703858/4cf88753-c0bf-49d5-ab76-e351c18a1a8c">

<img width="1470" alt="image" src="https://github.com/expo/expo/assets/19703858/74c100fb-3a91-497f-b1cd-d9f53df0d942">

<img width="1463" alt="image" src="https://github.com/expo/expo/assets/19703858/17333f29-cedc-4789-8416-8bd2ce3374fa">

Are you able to figure out anything from the above screenshot references

**Comment by wschurman** [comment]
If the left hand portion of the window is made wider so the full function names can be seen that might be helpful.

**Comment by ahmed-sharief5** [comment]
Here are the screenshots 

<img width="1466" alt="image" src="https://github.com/expo/expo/assets/19703858/07b83fd4-cde8-45fe-8ccc-f876918fcaf8">


<img width="1466" alt="image" src="https://github.com/expo/expo/assets/19703858/d9ff43a8-1e27-4e10-9f00-0be9c9d34470">


<img width="1466" alt="image" src="https://github.com/expo/expo/assets/19703858/17f6773a-38bd-4f31-9a0f-3b10b5a7e7ff">


Please let me know if you need any further information

**Comment by wschurman** [comment]
My guess is that there is some extra code in your AppDelegate that was either added or forgot to be removed during a SDK/RN version upgrade. The way I would debug this is to create a blank app and run prebuild to see what a fresh AppDelegate looks like and then compare to your AppDelegate, removing things that look extraneous but keeping customizations you may have made. I can't speak to exactly how it should look since this depends on the app and native libraries you may use.

**Comment by ahmed-sharief5** [comment]
I have created a new repo and then copied all the required files and folder from my previous project and then installed expo-updates. Finally it worked. Not sure why was it not working in the existing project. Anyways now its working

**Comment by dattx1** [comment]
i'm facing this problem, does anyone have any ideas

**Comment by dattx1** [comment]
Hi @ahmed-sharief5 @wschurman 
Have you figured out the root cause yet? If you have, could you help me out by sharing it?

**Comment by ahmed-sharief5** [comment]
Hello @dattx1 
I am still trying to figure out the root cause of it. But you can create a new repo and copy the required files and start using expo-updates

**Comment by pranshuchittora** [comment]
I am also seeing the same warning with expo 51 and app updates 25
message":"EXUpdates: Could not emit event: name = Expo.nativeUpdatesStateChangeEvent, type = check. Event will be emitted when the appContext is available","timestamp":1735286736000,"code":"JSRuntimeError","level":"warn"

**Comment by harrisrobin** [comment]
Running into this as well after upgrading my bare app from SDK 50 to 52 :/

**Comment by w1ll-dev** [comment]
Hey everyone, after spending a few days troubleshooting this issue, I finally identified the root cause.

In `AppDelegate.mm`, I was mistakenly calling `[super application:application didFinishLaunchingWithOptions:launchOptions]; `twice.

To fix this, I replaced the final line in `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` with `return YES` instead of returning the super call. This resolved the double call problem.

<img width="709" alt="Image" src="https://github.com/user-attachments/assets/d8d32933-00ea-4f98-8ad3-7654f1780574" />


Hope this helps anyone facing the same issue!

**Comment by lenoirzamboni** [comment]
Hello folks! I'm facing the same problem here 😢

Here is my `.swift` code. Not sure if I'm doing something wrong. 


<details><summary>AppDelegate</summary>

```swift
// airbridge-react-native-sdk setup
import AirbridgeReactNative

// Expo Updates imports
import Expo
import EXUpdates
import ExpoModulesCore

// @react-native-firebase setup
import Firebase
import RNFBMessaging

// @react-native-community/push-notification-ios setup
import RNCPushNotificationIOS

// React Native imports
import React
import ReactAppDependencyProvider
import UIKit
import UserNotifications

// react-native-config setup
import react_native_config

@UIApplicationMain
class AppDelegate: ExpoAppDelegate, UNUserNotificationCenterDelegate {

  var launchOptions: [UIApplication.LaunchOptionsKey: Any]?

  var window: UIWindow?

  // React Native factory properties
  var reactNativeFactoryDelegate: ExpoReactNativeFactoryDelegate?
  //  var reactNativeFactory: ExpoReactNativeFactory?

  // Static shared instance for Expo Updates
  public static func shared() -> AppDelegate {
    guard let delegate = UIApplication.shared.delegate as? AppDelegate else {
      fatalError("Could not get app delegate")
    }
    return delegate
  }

  // Expo Updates controller
  var updatesController: (any InternalAppControllerInterface)?

  private func initializeReactNativeAndUpdates(
    _ launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) {

    self.launchOptions = launchOptions
    let delegate = CustomReactNativeFactoryDelegate()
    let factory = ExpoReactNativeFactory(delegate: delegate)

    delegate.dependencyProvider = RCTAppDependencyProvider()

    self.reactNativeFactoryDelegate = delegate
   //    self.reactNativeFactory = factory
    self.factory = factory

    AppController.initializeWithoutStarting()
  }

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication
      .LaunchOptionsKey: Any]?
  ) -> Bool {

    // Initialize React Native and Expo Updates
    initializeReactNativeAndUpdates(launchOptions)

    // @react-native-firebase setup
    FirebaseApp.configure()

    // @react-native-community/push-notification-ios setup
    let center = UNUserNotificationCenter.current()
    center.delegate = self

    // airbridge-react-native-sdk setup
    if let airbridgeToken = react_native_config.RNCConfig.env(
      for: "AIRBRIDGE_TOKEN")
    {
      AirbridgeReactNative.initializeSDK(
        name: "liveloads", token: airbridgeToken)
    }

    // Create custom view controller for Expo Updates
    self.window = UIWindow(frame: UIScreen.main.bounds)
    let controller = CustomViewController()
    controller.view.clipsToBounds = true
    self.window?.rootViewController = controller
    window?.makeKeyAndVisible()

    return true
  }

  // MARK: - Deep link setup

  override func application(
    _ application: UIApplication, open url: URL,
    options: [UIApplication.OpenURLOptionsKey: Any] = [:]
  ) -> Bool {
    // airbridge-react-native-sdk setup
    AirbridgeReactNative.trackDeeplink(url: url)

    // Combine Expo and RCT linking
    return super.application(application, open: url, options: options)
      || RCTLinkingManager.application(application, open: url, options: options)
  }

  override func application(
    _ application: UIApplication, continue userActivity: NSUserActivity,
    restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
  ) -> Bool {

    // airbridge-react-native-sdk setup
    AirbridgeReactNative.trackDeeplink(userActivity: userActivity)

    return RCTLinkingManager.application(
      application, continue: userActivity,
      restorationHandler: restorationHandler)
  }

  // MARK: - Push Notification Setup

  // Required for the register event.
  override func application(
    _ application: UIApplication,
    didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
  ) {
    RNCPushNotificationIOS.didRegisterForRemoteNotifications(
      withDeviceToken: deviceToken)
  }

  // Required for the notification event. You must call the completion handler after handling the remote notification.
  override func application(
    _ application: UIApplication,
    didReceiveRemoteNotification userInfo: [AnyHashable: Any],
    fetchCompletionHandler completionHandler: @escaping (
      UIBackgroundFetchResult
    ) -> Void
  ) {
    RNCPushNotificationIOS.didReceiveRemoteNotification(
      userInfo, fetchCompletionHandler: completionHandler)
  }

  // Required for the registrationError event.
  override func application(
    _ application: UIApplication,
    didFailToRegisterForRemoteNotificationsWithError error: Error
  ) {
    RNCPushNotificationIOS.didFailToRegisterForRemoteNotificationsWithError(
      error)
  }

  // Required for localNotification event
  func userNotificationCenter(
    _ center: UNUserNotificationCenter,
    didReceive response: UNNotificationResponse,
    withCompletionHandler completionHandler: @escaping () -> Void
  ) {
    RNCPushNotificationIOS.didReceive(response)
    completionHandler()
  }

  // Called when a notification is delivered to a foreground app.
  func userNotificationCenter(
    _ center: UNUserNotificationCenter,
    willPresent notification: UNNotification,
    withCompletionHandler completionHandler: @escaping (
      UNNotificationPresentationOptions
    ) -> Void
  ) {
    completionHandler([.sound, .alert, .badge])
  }
}

// MARK: - Custom React Native Factory Delegate for Expo Updates

class CustomReactNativeFactoryDelegate: ExpoReactNativeFactoryDelegate {
  let bundledUrl = Bundle.main.url(
    forResource: "main", withExtension: "jsbundle")

  override func sourceURL(for bridge: RCTBridge) -> URL? {
    // needed to return the correct URL for expo-dev-client.
    bridge.bundleURL ?? bundleURL()
  }

  override func bundleURL() -> URL? {
    #if DEBUG
      RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
    #else
      Bundle.main.url(forResource: "main", withExtension: "jsbundle")
    #endif
  }
}

```
</details> 

<details><summary>CustomViewController</summary>

```swift

// Expo Updates imports
import EXUpdates
import Expo
import ExpoModulesCore

// React imports
import React

// iOS imports
import UIKit

// MARK: - Custom view controller that handles React Native and expo-updates initialization

public class CustomViewController: UIViewController, AppControllerDelegate {
  let appDelegate = AppDelegate.shared()

  public convenience init() {
    self.init(nibName: nil, bundle: nil)

    appDelegate.updatesController = AppController.sharedInstance

    AppController.sharedInstance.delegate = self

    AppController.sharedInstance.start()
  }

  required public override init(
    nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?
  ) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
  }

  @available(*, unavailable)
  required public init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }

  public func appController(
    _ appController: AppControllerInterface,
    didStartWithSuccess success: Bool
  ) {
    createView()
  }

  private func createView() {
    guard
      let rootViewFactory: RCTRootViewFactory = appDelegate.factory?
        .rootViewFactory
    else {
      fatalError("rootViewFactory has not been initialized")
    }

    let rootView = rootViewFactory.view(
      withModuleName: "main",
      initialProperties: [:],
      launchOptions: appDelegate.launchOptions
    )

    let controller = self
    controller.view.clipsToBounds = true
    controller.view.addSubview(rootView)
    rootView.translatesAutoresizingMaskIntoConstraints = false

    NSLayoutConstraint.activate([
      rootView.topAnchor.constraint(
        equalTo: controller.view.safeAreaLayoutGuide.topAnchor),
      rootView.bottomAnchor.constraint(
        equalTo: controller.view.safeAreaLayoutGuide.bottomAnchor),
      rootView.leadingAnchor.constraint(
        equalTo: controller.view.safeAreaLayoutGuide.leadingAnchor),
      rootView.trailingAnchor.constraint(
        equalTo: controller.view.safeAreaLayoutGuide.trailingAnchor),
    ])
  }
}

```
</details> 

<details><summary>Error</summary>

<img width="1366" height="798" alt="Image" src="https://github.com/user-attachments/assets/305a2867-bfb1-4285-9845-594c34df3f83" />

</details> 

The debug version also does not work. I receive this error here:

<details><summary>Debug version error</summary>

<img width="422" height="116" alt="Image" src="https://github.com/user-attachments/assets/07463e07-9d2b-4cb6-8861-1cba2eb3459e" />

</details> 

I had to change to from ObjectiveC to Swift, but I don't understand much the syntax. I followed [this guide](https://docs.expo.dev/eas-update/integration-in-existing-native-apps/#integrating-expo-updates-with-your-react-native-bundling). If anyone see an error, pls let me know 🙏🏻

Edit: when I comment this line `AppController.sharedInstance.start()` (CustomViewController), I get a black screen only. I can see logs from firebase and airbridge.
