### ISSUE TITLE
Hide address bar on scroll (Web)

### ISSUE THREAD

**Issue by cseelus** [expo/expo#24969]
### Minimal reproducible example

https://github.com/expo/examples/tree/master/with-router

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Playing  around with the Expo Router tabs example using `<ScrollView>`s  for the content and the very interesting [Instagram layout example](https://github.com/EvanBacon/expo-router-instagram-layout) by @EvanBacon, something felt broken. When I compared it to the original Instagram example, it became clear that its that the browser chrome on mobile doesn't hide dynamically like on normal websites, but instead stays static.

It's not just with the `<Tab>` layout, even using a basic `<Stack>` layout, this doesn't work.

According to the [React Navigation docs](https://reactnavigation.org/blog/2020/05/16/web-support/#hide-address-bar-on-scroll), this should work out of the box, so I think this might be a regression.

Expo Router:
https://github.com/expo/expo/assets/3188392/ab1f78bf-a19b-4865-a2f1-60279a664b38

How it should be:
https://github.com/expo/expo/assets/3188392/c88521e0-735d-49d1-ab4a-32df4848350c

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.6.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.18.0 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.3 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed

**Comment by EvanBacon** [comment]
By default, the body height is locked on web to match React Native. This behavior can be disabled with the [Root HTML](https://docs.expo.dev/router/reference/static-rendering/#root-html) component, simply remove the `< ScrollViewStyleReset  />` element.
