### ISSUE TITLE
ReferenceError: Can't find variable: BigInt

### ISSUE THREAD

**Issue by zahir-dct** [expo/expo#24960]
### Minimal reproducible example

https://github.com/zahir-dct/reproduction

### Actual behavior
App crashes

### Steps to reproduce the behavior
Add web3 package to an expo app

### Logs
ERROR ReferenceError: Can't find variable: BigInt

ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

ERROR Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### Environment
"expo": "~47.0.12",
"react": "18.1.0",
"react-native": "0.70.8",
"web3": "^1.8.2",

### Note
I removed "^" from "^1.8.2", the app doesn't crash

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    Expo Workflow: managed

**Comment by Kudo** [comment]
hi there! react-native 0.70 (expo sdk 47) does not support BigInt. please try to update to [latest sdk](https://blog.expo.dev/expo-sdk-49-c6d398cdf740) for the BigInt support.
