### ISSUE TITLE
Expo Calendar - Calendar.AlarmMethod.ALARM not ringing

### ISSUE THREAD

**Issue by ddennis** [expo/expo#24979]
### Minimal reproducible example

https://snack.expo.dev/@ddennis/expo-calendar-test-1

### Summary

When trying to set "Calendar.AlarmMethod.ALARM" nothing happens. The event is created in the calendar but no alarm is ringing or showing. 

I am trying to set an Alarm. Based on the documentation i am expecting something like an Alarm clock sound that keeps ringing for within the timeinterval of the event.

Switching to use an Calendar.AlarmMethod.ALERT something is popping up on my device and playing a sound. 

I have tested this on an **android** devices, two Samsung tablets and a Pixel phone.

From the docs I have a hard time understanding exactly what configuration is needed and what i can do with the expo-calendar.  
Its not clear to me, if there is a difference between Calendar.getDefaultCalendarAsync() and getCalendarsAsync()

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      expo: ^49.0.9 => 49.0.13
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: bare

**Comment by behenate** [comment]
Hi! 
The  `AlarmMethod` description in our docs is a little lacking. Basically on Android it is equivalent to [`CalendarContract.RemindersColumns.method`](https://developer.android.com/reference/kotlin/android/provider/CalendarContract.RemindersColumns.html#method)
As you can see there: _"the device will only process `METHOD_DEFAULT` and `METHOD_ALERT` reminders (the other types are simply stored so we can send the same reminder info back to the server when we make changes)."_ So you should limit yourself to using `Calendar.AlarmMethod.ALERT` on Android.

When it comes to `getDefaultCalendarAsync()` and `getCalendarsAsync()`: there can be multiple calendars on the device, but only one of them is the default calendar.
