### ISSUE TITLE
[SDK49] [IOS] using img.ly localization : declaration of ‘facebook’ must be imported from module ‘yoga.yoga.YGNodePrint’ before it is required

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#24982]
### Minimal reproducible example

https://github.com/lc3t35/sdk49-imgly

### Summary

It's already detailled here : https://forums.expo.dev/t/sdk49-building-ios-declaration-of-facebook-must-be-imported-from-module-yoga-yoga-ygnodeprint-before-it-is-required/73909 

After updating to SDK49 (49.0.13), I had this error after npx expo run:ios
(pod install done before, update, clean, reinstall all … whatever)

```
❌ (/Users/xxxxx/ios/Pods/Headers/Public/ExpoModulesCore/ExpoModulesCore/EXJavaScriptObject.h:8:17)

   6 | #import <jsi/jsi.h>
   7 |
>  8 | namespace jsi = facebook::jsi;
     |                 ^ declaration of 'facebook' must be imported from module 'yoga.yoga.YGNodePrint' before it is required
   9 | #endif // __cplusplus
  10 |
  11 | @class EXJavaScriptRuntime;

❌ (/xxx/ios/Pods/Headers/Public/ExpoModulesCore/ExpoModulesCore/EXJavaScriptObject.h:8:27)

   6 | #import <jsi/jsi.h>
   7 |
>  8 | namespace jsi = facebook::jsi;
     |                           ^ missing '#include "jsi/jsi-inl.h"'; 'jsi' must be declared before it is used
   9 | #endif // __cplusplus
  10 |
  11 | @class EXJavaScriptRuntime;


❌  (/xxxx/ios/Pods/Headers/Public/React-NativeModulesApple/ReactCommon/RCTTurboModule.h:35:18)

  33 |  * ObjC++ specific TurboModule base class.
  34 |  */
> 35 | class JSI_EXPORT ObjCTurboModule : public TurboModule {
     |                  ^ variable has incomplete type 'class JSI_EXPORT'
  36 |  public:
  37 |   // TODO(T65603471): Should we unify this with a Fabric abstraction?
  38 |   struct InitParams {
```

it happens with SDK 49.0.13 when I add the needed instruction for localization of img.ly in AppDelegate.mm
(https://img.ly/docs/pesdk/react-native/guides/user-interface/localization/)

```
#import <RNPhotoEditorSDK/RNPhotoEditorSDK.h>
...
[PESDK setLocalizationDictionary: @{ ...}
```

and also these options in Xcode (as requested by img.ly support to build sdk48)

```
CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES;
....
OTHER_CPLUSPLUSFLAGS = (
   "$(inherited)",
   "-fcxx-modules",
);
```

No problem with sdk49 without localization (and it works with my current sdk48 version)
Ticket also submitted to img.ly support since 2 weeks, reproducible demo submitted 1 week ago too … 
@keith-kurak (thank you !) can reproduce and suggested to open this issue.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.9
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
      Watchman: 2023.01.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare
```

**Comment by wodin** [comment]
@keith-kurak according to the forum post you can reproduce this?

**Comment by keith-kurak** [comment]
@wodin Yes, I was able to reproduce by doing the following:
1. `npx create-expo-app`
2. `yarn add react-native-photoeditorsdk`
3.  `npx expo prebuild` 
4.  open the ios workspace in Xcode 
5.  add `#import <RNPhotoEditorSDK/RNPhotoEditorSDK.h>` at the top of **AppDelegate.mm**
6. Attempt to build in Xcode

**Comment by aswinmgdas** [comment]
Getting the same error on including expo with -fcxx-modules flag. Have you identified a solution on this?

**Comment by smalik02** [comment]
@aswinmgdas - were you able to address the issue? I'm also running into the same problem.

**Comment by lc3t35** [comment]
@smalik02 update to latest img.ly version

**Comment by aswinmgdas** [comment]
@smalik02 and @lc3t35 sorry about delay in response. We had rectified it by working with team and using avoiding the usage of semantic imports and using Swift Compatibility Headers for the library to do regular header file imports.

**Comment by smalik02** [comment]
@lc3t35 and @aswinmgdas - i wasn't using the img.ly library. The compile was failing as i was trying to import a different library using `@import` in an obj-c++ delegate file. When i added the custom c++ flags to support the import, it broke compile for another package. 

i ended up moving the import to a different file, obj-c, and then importing that header directly in the appdelegate.mm. That compiled without a need for custom c++ flags. thank you for your help!

**Comment by saadiyakazi** [comment]
Facing same issue on. expo sdk 49 . What is the solution to this ?
