### ISSUE TITLE
Problem in getting the values ​​of getStatusAsync on Audio Api in IOS

### ISSUE THREAD

**Issue by 13ArturBruno** [expo/expo#2498]
my code: 

   _newAudioPlay(playing){
        
        if (this.playbackInstance != null) {
            this.playbackInstance.unloadAsync();
            this.playbackInstance = null;
            this._newAudioPlay(false)
          }
          else{
          var source = { uri: BASEIPURL + this.state.currentAudio[0].arquive }
          const initialStatus = {
            shouldPlay: playing,
            rate: this.state.rate,
            shouldCorrectPitch: this.state.shouldCorrectPitch,
            volume: this.state.volume,
            isMuted: this.state.muted,
          };
          this.playbackInstance = sound;
          this.playbackInstance.loadAsync(source, initialStatus, this.playbackInstance._onPlaybackStatusUpdate);}

          this._updateScreenForLoading(false);

        }

        _updateScreenForLoading(isLoading) {
            if (isLoading) {
              this.setState({        
                isPlaying: false,
                isLoading: true,
              });
            } else {
              this.setState({
                isLoading: false,
                isPlaying: false    
              });
            }
          }
    
      _onPlayPausePressed = () => {
        if (this.playbackInstance != null) {
          if (this.state.isPlaying) {
            this.setState({
                isPlaying: false
            });
            this.playbackInstance.pauseAsync();
          } else {
                this.setState({
                  isPlaying: true
                });            
                this.playbackInstance.playAsync();
          }
        }
      };
    
      _onStopPressed = () => {
        if (this.playbackInstance != null) {
            this.setState({
                isPlaying: false
            });
            this.playbackInstance.stopAsync();
        }
      };
    
    
      _onSeekSliderValueChange = value => {
        if (this.playbackInstance != null && !this.isSeeking) {
          this.isSeeking = true;
          this.shouldPlayAtEndOfSeek = this.state.shouldPlay;
          this.playbackInstance.pauseAsync();
        }
      };

      _onSeekSliderSlidingComplete = async value => {
        if (this.playbackInstance != null) {
          this.isSeeking = false;
          const seekPosition = value * 2000;
          if (this.shouldPlayAtEndOfSeek) {
            this.playbackInstance.playFromPositionAsync(seekPosition);
          } else {
            this.playbackInstance.setPositionAsync(seekPosition);
          }
        }
      };

      _onPlaybackStatusUpdate = status => {
        if (status.isLoaded) {
          this.setState({
            playbackInstancePosition: status.positionMillis,
            playbackInstanceDuration: status.durationMillis,
            shouldPlay: status.shouldPlay,
            isPlaying: status.isPlaying,
            isBuffering: status.isBuffering,
            rate: status.rate,
            muted: status.isMuted,
            volume: status.volume,
            shouldCorrectPitch: status.shouldCorrectPitch,
          });
        } else {
          if (status.error) {
            console.log(`FATAL PLAYER ERROR: ${status.error}`);
          }
        }
      };

                    <Slider
                            style={styles.playbackSlider}
                            trackImage={ICON_TRACK_1.module}
                            value={0}
                            onValueChange={this._onSeekSliderValueChange}
                            onSlidingComplete={this._onSeekSliderSlidingComplete}
                            disabled={this.state.isLoading}
                        />

only slider dont working, cause value from durationMillis cant be acessed.

**Comment by DanBruns** [comment]
There seems to be an inconsistency between the android and iOS implementations:  durationMillis appears to be called playableDurationMillis on iOS.

**Comment by cruzach** [comment]
Hi! I just tested this on SDK 33, 34, and 35, and both the iOS and Android implementations return `durationMillis` (as well as `playableDurationMillis`). Thanks for reporting this, and sorry for the long response time, but it looks like this must have been fixed at some point. If you do still see this bug on a supported SDK, please open up a new issue and provide a repro, thanks!
