### ISSUE TITLE
[Expo 49, Router v2] Dynamic Slug Routes Lose History When Navigating Back and Forward 

### ISSUE THREAD

**Issue by kennethstarkrl** [expo/expo#25001]
### Minimal reproducible example

https://github.com/kennethstarkrl/expo-49-router-v2-routing-same-path-different-params-not-changing

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When using a slug path for dynamic routing, the history gets lost when trying to navigate back through the dynamic screens.
The expected behavior is that using router.push() should push every dynamic slug screen to the history stack. Using the back and forward navigation should respect each slug screen. This issue affects both Tab screens and Drawer screens.

Video Example:

https://github.com/expo/expo/assets/53270830/6b90e934-5abc-4e63-8050-70aded1a2fe4

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.15 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Related https://github.com/expo/expo/pull/24600

**Comment by kennethstarkrl** [comment]
> Related #24600

Hey @marklawlor 

I think the pushOrPop feature is good, however, I don't think it totally solves this issue. In my use case the new feature would just pop the latest screen to the top of the stack when I need it to push every route to the stack.

Doing some more research, the issue arises out of using a single file slug page (ex [slug].tsx) and how react-navigation handles routing on screens with the same name. Expo router uses the name param as the slug. This conflicts with react-navigation as react-navigation requires all screen names to be unique.

I actually recently tried my temp fix for this here https://github.com/expo/router/issues/522#issuecomment-1528232550 and it practically just started working as expected. What it does is creates unique screen names dynamically if no slug is provided, or uses a slug param passed through the screen instead of the name. So every route gets pushed to the stack. I'm going to work on this more and see if I can make a contribution to the repo.

The change still needs some work before it's ready.

**Comment by kennethstarkrl** [comment]
This patch seems to be working for me. https://github.com/expo/router/issues/758#issuecomment-1813200769

**Comment by marklawlor** [comment]
The params do not affect the screen names, Expo Router essentially uses the file path as the screen name, but that logic isn't used as the state is generated by custom `getStateFromPath` and `getPathFromState` function.

That patch will work for now, as its a simplistic version of the changes planned for v3

**Comment by kennethstarkrl** [comment]
> The params do not affect the screen names, Expo Router essentially uses the file path as the screen name, but that logic isn't used as the state is generated by custom `getStateFromPath` and `getPathFromState` function.
> 
> That patch will work for now, as its a simplistic version of the changes planned for v3

Right that's what I meant, the screen name comes from the file name, but react-navigation uses the screen name as unique identifiers so there's issues with using the same file name for multiple screens when using dynamic slugs [slug].tsx files. That is a separate issue however. Thanks for clarification and your help!

**Comment by alexandre1921** [comment]
Same issue here.

**Comment by LeonardoMartinsMoreira** [comment]
I'm having this problem too.

**Comment by kennethstarkrl** [comment]
https://github.com/expo/expo/pull/27307#issuecomment-2076183214

**Comment by kennethstarkrl** [comment]
Related https://github.com/expo/expo/issues/27183

**Comment by marklawlor** [comment]
This shoudl be fixed in SDK51

@kennethstarkrl can you please create a new issue with a reproduction. We fix some issues with nested navigators, so the behaviour you relied on before may have changed. You can read my comment in #27183 for a small explaination

**Comment by kennethstarkrl** [comment]
> This shoudl be fixed in SDK51
> 
> @kennethstarkrl can you please create a new issue with a reproduction. We fix some issues with nested navigators, so the behaviour you relied on before may have changed. You can read my comment in #27183 for a small explaination

https://github.com/expo/expo/issues/29928
