### ISSUE TITLE
Fresh create expo app build issue

### ISSUE THREAD

**Issue by lortschi** [expo/expo#25016]
### Minimal reproducible example

Linking duplicate method '+moduleName'

### Summary

after creatinhg a fresh expo app and starting the build: npx expo run:ios --configuration Release, short the build is finishing getting this warnings that sometimes also crashes the build.

› Linking   vs24 » vs24
⚠️  ld: duplicate method '+moduleName' in
┌─[category]: ExpoBridgeModule-47f9d79d3c6eaea7cf0eff4ead49baf2.o ExpoModulesCore/libExpoModulesCore.a
└─[class]: ExpoBridgeModule-34893e7a357a56d2c4b57fc83c9de11e.o ExpoModulesCore/libExpoModulesCore.a

› Linking   vs24 » vs24
⚠️  ld: duplicate method '+moduleName' in
┌─[category]: ExpoBridgeModule-47f9d79d3c6eaea7cf0eff4ead49baf2.o ExpoModulesCore/libExpoModulesCore.a
└─[class]: ExpoBridgeModule-34893e7a357a56d2c4b57fc83c9de11e.o ExpoModulesCore/libExpoModulesCore.a

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - /usr/local/opt/node@16/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.4 - /usr/local/opt/node@16/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0
      expo: ~49.0.15 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by brentvatne** [comment]
can you run `yarn why expo-modules-core` to see which versions are installed in the project?

**Comment by lortschi** [comment]
> yarn why expo-modules-core

=> Found "expo-modules-core@0.11.10"
