### ISSUE TITLE
[android][ios] update Facebook SDK

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2501]
We'll need to update the versions of Facebook SDK used in both clients to 4.37.0 or later due to a recent API deprecation on their end. Message received by partner:

```
--- currently uses Facebook SDK for Android v4.34.0 and Facebook SDK for iOS v4.36.0, both of which rely on the recently deprecated Version 2.7 of the Graph API.

As a result, there is a risk that your app will no longer function if you don't upgrade to Facebook SDK for Android v4.37.0 and Facebook SDK for iOS v4.37.0.

As an admin of this app, please upgrade to the latest SDK as soon as possible to ensure your app's continued performance and to take advantage of new features.
```

**Comment by EvanBacon** [comment]
Prolly should roll this into a redesign that surfaces sharing, invites, analytics, native auth, ect.. 

**Related**

* https://expo.canny.io/admin/board/feature-requests/p/add-facebook-app-invites
* https://expo.canny.io/admin/board/feature-requests/p/post-content-to-facebook
* https://expo.canny.io/admin/board/feature-requests/p/facebook-login-through-facebook-app
* https://expo.canny.io/admin/board/feature-requests/p/full-facebook-sdk
* https://expo.canny.io/admin/board/feature-requests/p/facebook-accountkit
