### ISSUE TITLE
Using npx eas build -p android --local command

### ISSUE THREAD

**Issue by ICardosoRamos** [expo/expo#25015]
### Summary

i can't run this command and build locally my project because the error below occurs.
my project is with maneged workflow, created just now, with literally nothing code, zero screens, nothing.

the expected behavior is to build locally my project but im encontering this cenario:
![image](https://github.com/expo/expo/assets/111356794/9d03ff0e-437e-42eb-9103-694536324c28)

### What platform(s) does this occur on?

Android

### SDK Version

49

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.4.0 - /usr/local/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.2
    Expo Workflow: managed

### Minimal reproducible example

{
  "cli": {
    "version": ">= 5.4.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal",
      "withoutCredentials": true
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

**Comment by brentvatne** [comment]
hi there,

try searching for similar folks who have encountered this error message. this is a problem with your project configuration.
