### ISSUE TITLE
Adding Expo modules to a bare React Native app disables concurrent features.

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#25024]
### Minimal reproducible example

https://github.com/ahmetbicer/expo-modules-concurrent-root-issue

### Summary

After adding Expo modules to a bare React Native app with new arch enabled, `concurrentRoot: true` disappears, and React 18 features, such as [automatic batching](https://github.com/reactwg/react-18/discussions/21), are not working. This issue is observed only in Android; iOS works as expected.

Steps to Reproduce:

- Create a new React Native app with `npx react-native@latest init ConcurrentRootTest`
- Turn `newArchEnabled` flag to `true` in gradle.properties.
- Run the app, see `concurrentRoot: true` in metro logs
- Add Expo modules to the project with `npx install-expo-modules@latest`
- Run the app, `concurrentRoot: true` disappears and react 18 features such as [automatic batching](https://github.com/reactwg/react-18/discussions/21) are not working.

![ ](https://github.com/expo/expo/assets/45371442/51619c2c-e5e3-423c-9c47-cecf70723f2d)

Expected Behavior:
The concurrentRoot: true property should persist even after Expo modules are added.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: bare

**Comment by ahmetbicer** [comment]
Hi @Kudo, did you have time to look at this issue? Thanks in advance 🙏

**Comment by FightFarewellFearless** [comment]
I think this problem still persists in react-native version 0.74 and expo sdk 51.0.0-preview.3
