### ISSUE TITLE
Eject fails on new project

### ISSUE THREAD

**Issue by JSRossiter** [expo/expo#2502]
### Environment

  Expo CLI 2.2.1 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.1
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
    npmGlobalPackages:
      expo-cli: 2.2.1

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/jsrossiter-6106ba1b-b11c-4243-a919-f46fb0c4c582.tar.gz

### Steps to Reproduce

1. expo init
2. expo eject -> ExpoKit

### Actual Behavior
ios directory and files seem to be created appropriately but then I get this output and it crashes leaving temp-android-directory
```
Moving Android project files...
Downloading Android code...
[16:30:40] spawn ../../tools-public/check-dynamic-macros-android.sh ENOENT
[16:30:40] Error: spawn ../../tools-public/check-dynamic-macros-android.sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by calweb** [comment]
I'm seeing pretty much the same thing, getting the correctly seeming `ios/` dir (am able to build), but android always flakes
<img width="569" alt="screen shot 2018-10-25 at 1 01 34 am" src="https://user-images.githubusercontent.com/115030/47477134-b6dfa380-d7f1-11e8-9658-023966a587c9.png">

**Comment by calweb** [comment]
I was able to successfully eject after the above mentioned fix!  thanks so much!

**Comment by JSRossiter** [comment]
Me too, thanks

**Comment by sjchmiela** [comment]
For the record — suggested fix for this behavior would be to upgrade `expo-cli` to `2.2.2`. Sorry for the inconvenience! 🙂

**Comment by dustturtle** [comment]
how to do this? my expo-cli is 2.2.5- macOS 10.14 . eject failed log:
Creating ExpoKit workspace at /Users/zhenweiguan/Downloads/PwarSae/ios...
Moving iOS project files...
Attempting to create project directory...
Created project directory! Copying files:
[11:16:14] undefined
[11:16:14] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by dustturtle** [comment]
I succeed ejecting but now failed on pod install... thanks

**Comment by Sofianebenabdallah** [comment]
@dustturtle I have exactly the same issue. I did it on two different Mac. 
Expo init 
Expo eject
cd iOS 
pod install (failed)

Error installing ExpoKit
[!] Failed to download 'ExpoKit': [!] /usr/bin/git clone http://github.com/expo/expo.git /var/folders/r3/8nyp04cj1c32pgmn1tcgn66w0000gn/T/d20181109-16055-1jph5ug --template= --single-branch --depth 1 --branch ios/2.9.0

**Comment by sjchmiela** [comment]
Hey, @Sofianebenabdallah! I have a feeling this may not be whole message. 🙂 Could you please provide full error message?

To clone `expo/expo` repo you will need Git LFS installed (https://git-lfs.github.com). Do you have it installed on your machines?

**Comment by Sofianebenabdallah** [comment]
thank you for your feedback @sjchmiela  

I don't think I have install it. I test it now. Thanks

**Comment by Sofianebenabdallah** [comment]
@sjchmiela it's not finished but it is downloading now. Thanks a lot.
