### ISSUE TITLE
Expo splash screen after the update is released Expo go doesn't work either

### ISSUE THREAD

**Issue by mucahitdev** [expo/expo#25038]
### Minimal reproducible example

https://github.com/burhanyilmaz/expo-splash-screen-eas-update

### Summary

Since the problem comes with the eas update, it cannot be tested in Snack.

### Summary

**Android and İOS**
When you run the **local project,** a Splash Screen appears on both the Simulators and the Device. However, the application that **was updated and uploaded to Expo** does not appear as a Splash Screen in Expo Go.

**Locally**    ..................................................................  **With Update**
![Locally](https://i.hizliresim.com/y2if4lq.gif) ![ With Update](https://i.hizliresim.com/bgwex49.gif)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed

dependencies": {
    "@expo-google-fonts/work-sans": "^0.2.3",
    "@gorhom/bottom-sheet": "^4.4.7",
    "@gorhom/portal": "^1.0.14",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-picker/picker": "2.4.8",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.5",
    "@stripe/stripe-react-native": "^0.30.0",
    "@tanstack/react-query": "^4.29.13",
    "@timwangdev/react-native-geocoder": "^1.0.0-alpha.7",
    "@types/react-native-snap-carousel": "^3.8.5",
    "axios": "^1.4.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "expo": "~48.0.18",
    "expo-apple-authentication": "^6.1.0",
    "expo-clipboard": "^4.5.0",
    "expo-constants": "^14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-device": "^5.2.1",
    "expo-image": "~1.0.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "^4.0.1",
    "expo-location": "^16.0.0",
    "expo-print": "^12.2.1",
    "expo-sharing": "^11.2.2",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "formik": "^2.4.2",
    "i18next": "^22.5.1",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.4",
    "native-base": "^3.4.28",
    "react": "18.2.0",
    "react-i18next": "^12.3.1",
    "react-native": "0.71.8",
    "react-native-chart-kit": "^6.12.0",
    "react-native-chart-kit-with-pressable-bar-graph": "^6.11.4",
    "react-native-collapsible-tab-view": "^6.2.1",
    "react-native-dotenv": "^3.4.9",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-localize": "^3.0.0",
    "react-native-maps": "^1.7.1",
    "react-native-maps-directions": "^1.9.0",
    "react-native-pager-view": "^6.2.1",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-reanimated-carousel": "^3.4.0",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "13.4.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-toast-message": "^2.1.6",
    "react-native-toggle-element": "^2.0.1",
    "react-redux": "^8.0.7",
    "yup": "^1.2.0"
  },`

**Comment by wschurman** [comment]
Thanks for the report. This is expected. I updated the docs to include a blurb about EAS updates.
