### ISSUE TITLE
Expo local notification

### ISSUE THREAD

**Issue by Elozino** [expo/expo#25049]
### Minimal reproducible example

https://github.com/Elozino/local-notification

### Summary

Hello, 

Local notification works on the development environment (expo go on physical device) but when we generate an apk build, we realize that the notification does not show at the scheduled time. The time difference from the exact time varies. However, when the app is in foreground, the schedule notification tends to be accurate but once it is in the background, it doesn't.

Issue also happened on Expo SDK 48

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    Expo Workflow: managed

**Comment by brentvatne** [comment]
hi there! did you add this permission? https://docs.expo.dev/versions/latest/sdk/notifications/#android-1

> Starting from Android 12 (API level 31), to schedule the notification that triggers at the exact time, you need to add <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/> to AndroidManifest.xml. You can read more about the [exact alarm permission](https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission).

**Comment by Elozino** [comment]
> hi there! did you add this permission? https://docs.expo.dev/versions/latest/sdk/notifications/#android-1
> 
> i don't see that in your reproducible example project
> 
> > Starting from Android 12 (API level 31), to schedule the notification that triggers at the exact time, you need to add  to AndroidManifest.xml. You can read more about the [exact alarm permission](https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission).

It's local notifications, i did everything as required on the docs but it just doesn't display notifications at the exact time if the app is closed.

**Comment by brentvatne** [comment]
@Elozino - you need to set the exact alarm permission as suggested in the doc, if you want to schedule the notification to trigger at an exact time.

so something like this in your app.json:

```
{
  "expo": {
    "android": {
      "permissions": [
        "android.permission.SCHEDULE_EXACT_ALARM"
      ]
    }
  }
}
```

**Comment by Elozino** [comment]
> @Elozino - you need to set the exact alarm permission as suggested in the doc, if you want to schedule the notification to trigger at an exact time.
> 
> so something like this in your app.json:
> 
> ```
> {
>   "expo": {
>     "android": {
>       "permissions": [
>         "android.permission.SCHEDULE_EXACT_ALARM"
>       ]
>     }
>   }
> }
> ```

Thanks for your prompt response. 
I did that and it still doesn't schedule them at their exact time.

**Comment by brentvatne** [comment]
you need to rebuild the apk after adding that

**Comment by froilansam** [comment]
Same issue to me, built and did that, not triggering at exact time.
