### ISSUE TITLE
Local Authentication does not work with Face ID

### ISSUE THREAD

**Issue by Monkhai** [expo/expo#25055]
### Minimal reproducible example

https://github.com/Monkhai/Face-ID-Test

### Summary

I am trying to call the LocalAuthentication module to use biometric authentication in my app.
I have added the expo-local-authentication plugin as well as it's configuration for Face ID. I have also added the `infoPList` `NSFaceIDUsageDescription` as mentioned in the docs.
When I try to call it and I log the response I get the following message:
> "warning": "FaceID is available but has not been configured. To enable FaceID, provide `NSFaceIDUsageDescription`.

I have tested on both a physical device and an emulator and am getting the same response. Below is the code I am using:

In App.tsx:
``` ts
export default function App() {
  const [authRes, setAuthRes] = useState<LocalAuth.LocalAuthenticationResult | null>(null);

  const callAuth = async () => {
    const res = await LocalAuth.authenticateAsync();
    setAuthRes(res);
    console.log(res);
  };

  return (
    <View style={styles.container}>
      <Button title="Authenticate" onPress={callAuth} />
      <StatusBar style="auto" />
    </View>
  );
}
```
In App.json:
```
{
  "expo": {
    "name": "Face-ID-Test",
    "slug": "Face-ID-Test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "infoPlist": {
        "NSFaceIDUsageDescription": "This app uses Face ID to validate your indentity."
      }
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-local-authentication",
        {
          "faceIDPermission": "Allow $(PRODUCT_NAME) to use Face ID."
        }
      ]
    ]
  }
}
```

### Environment

System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.2.0/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v20.2.0/bin/npm
      Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi @Monkhai - I have pulled your example and run it without issue. It uses FaceID as expected. I can generate the warning but only in expo go. Expo go instead asks for the device password. Are you using expo go?

**Comment by Monkhai** [comment]
> Hi @Monkhai - I have pulled your example and run it without issue. It uses FaceID as expected. I can generate the warning but only in expo go. Expo go instead asks for the device password. Are you using expo go?

Hey @alanjhughes - I have tried both expo go as well as the simulator. Does it require a full build to work? at the moment I am testing it via `npx expo start -i`

**Comment by alanjhughes** [comment]
It will require a dev client to add the faceID usage description. Expo go should present the passcode entry.

**Comment by Monkhai** [comment]
Ok using `expo-dev-client` and installing a development build I was able to have FaceID work as expected. Thank you very much for the quick response!
