### ISSUE TITLE
Expo does not build with private library

### ISSUE THREAD

**Issue by pedron3to** [expo/expo#25064]
### Minimal reproducible example

https://snack.expo.dev/@pedrosartor/private-library

### Summary

I am using a private library using Expo. 

I was able to install the private library through "yarn add fortis-payment-sdk --registry https://artifact.fortis.tech/repository/npm-group/". But after the command yarn start, expo throws an error:

`Validation Warning:

  Unknown option "watcher" with value {"additionalExts": ["env.development.local", "env.local", "env.development", "env"]} was found.
  This is probably a typing mistake. Fixing it will remove this message.

Starting Metro Bundler
TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function
TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function
    at Object.observeFileChanges (/Users/pedrosartor/Documents/test-inventory/node_modules/@expo/cli/build/src/start/server/metro/waitForMetroToObserveTypeScriptFile.js:44:60)
    at MetroBundlerDevServer.watchEnvironmentVariables (/Users/pedrosartor/Documents/test-inventory/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js:209:51)
    at DevServerManager.watchEnvironmentVariables (/Users/pedrosartor/Documents/test-inventory/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:193:35)
    at startAsync (/Users/pedrosartor/Documents/test-inventory/node_modules/@expo/cli/build/src/start/startAsync.js:127:32)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
error Command failed with exit code 1.`

If I remove the private library, expo starts.

my package .json
{
  "name": "test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "fortis-payment-sdk": "^1.3.1",
    "react": "18.0.0",
    "react-native": "0.69.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 15.0.0 - ~/.nvm/versions/node/v15.0.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 7.0.2 - ~/.nvm/versions/node/v15.0.0/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 5.5.1
    Expo Workflow: managed

**Comment by brentvatne** [comment]
hi there, you should refer to the maintainer of this private library for help. it's not obvious that there is anything wrong with any expo tooling here.

**Comment by pedron3to** [comment]
Thank you

**Comment by GiomScript** [comment]
Hi, I have the same issue and I am not using any private library...
Unknown option "server.unstable_serverRoot" with value  "C:\\users\\..." was found.
This is probably a typing mistake. Fixing it will remove this message.
Unknown option "watcher" with value {"additionalExts": ["env.development.local", "env.local", "env.development", "env"]} was found.
  This is probably a typing mistake. Fixing it will remove this message.

"expo": "^50.0.2",
"react-native": "^0.73.2",

My expo go stopped working due to an unsupported SDKversion, trying to upgrade to the latest version...
