### ISSUE TITLE
[expo-image] contentFit="cover" doesn't work for SVG images on Android

### ISSUE THREAD

**Issue by adrianso** [expo/expo#25069]
### Minimal reproducible example

https://snack.expo.dev/@adrianso/expo-image-bug-reproduction?platform=android

### Summary

![Screenshot 2023-10-27 at 4 01 38 PM](https://github.com/expo/expo/assets/836310/893c73c1-f798-42d6-ad10-dad48151b984)

When an SVG <Image> is larger than its container, and contentFit is set to "cover" on Android, I expect the image to cover the entire container. Note that this works as intended on iOS, and also for PNGs on Android.

See screenshot.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/Library/Caches/fnm_multishells/96654_1698372730611/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/Library/Caches/fnm_multishells/96654_1698372730611/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/adrian/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 23, 28, 29, 31, 32, 33, 34
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 32.0.0, 32.0.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-25 | Android Wear ARM EABI v7a, android-26 | ARM 64 v8a, android-27 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.16 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    Expo Workflow: managed
```

**Comment by amitchaudhary140** [comment]
@behenate When will this fix be out?

**Comment by behenate** [comment]
@amitchaudhary140 I don't know an exact date, most likely in a few weeks in the next version of `expo-image`. If you really need it right now you could use `patch-package` with the changes from the PR above.

**Comment by amitchaudhary140** [comment]
@behenate Thanks for the info. Generally, what is the release cycle? Just asking so that I can take right decision at this point of time. If it takes more than a week or two, I better convert all svg images to PNG format. But I have more than 300 images.

**Comment by behenate** [comment]
@amitchaudhary140 We should release a new version in one or two weeks
