### ISSUE TITLE
[expo prebuild] generates un-ecessary messages in terminal and scripts

### ISSUE THREAD

**Issue by xzilja** [expo/expo#25073]
### Summary

I've run `expo prebuild` on lates expo sdk (49) and expo-cli. Command works great, but it seems like it generates few unnecessary outputs:

1. it adds `"android": "expo run:android"` and `"ios": "expo run:ios"` scripts in package.json, while these are useful they are not always necessary i.e. we use just `expo start --clear --dev-client` locally. And run eas builds for on-device testing.

2. Cli outputs `Updated package.json and added index.js entry point for iOS and Android` but nothing related to this changes in package.json (unless this refers to adding those android and ios scripts?)

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

49

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - /opt/homebrew/bin/node
      npm: 10.2.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.16 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: bare
```

### Minimal reproducible example

As simple as running

```zsh
expo prebuild
```

In a project that doesn't have ios / android commands defined in package.json

**Comment by brentvatne** [comment]
> 1. it adds `"android": "expo run:android"` and `"ios": "expo run:ios"` scripts in package.json, while these are useful they are not always necessary i.e. we use just `expo start --clear --dev-client` locally. And run eas builds for on-device testing.

you may remove them if you don't want them - we add them because they are convenient shortcuts for some folks. do you think we should leave this out? the problem is that if we don't update them from the defaults, then the scripts won't be accurate. here's a diff from a new project:

```diff
-    "android": "expo start --android",
-    "ios": "expo start --ios",
+    "android": "expo run:android",
+    "ios": "expo run:ios",
```

> 2. Cli outputs `Updated package.json and added index.js entry point for iOS and Android` but nothing related to this changes in package.json (unless this refers to adding those android and ios scripts?)

good catch! in sdk 49, we added full support for the `"main"` field in **package.json** (this is not supported by react-native's built in bundling cli, we switched to using expo cli in all cases) but we neglected to update this message. care to send a PR for it?

**Comment by 0xAsimetriq** [comment]
1. Regarding this point, could this be dynamic i.e. detect if folks have `"android": "expo start --android"` (or ios equivalent) set and only add / replace these scripts then? I can manually remove these, but they still get re-generated after every prebuild.

2. Will try to find some time and figure out how to do this so I can open the PR 👍
