### ISSUE TITLE
SplashScreen still shows default when opening app

### ISSUE THREAD

**Issue by MariuzM** [expo/expo#25091]
### Minimal reproducible example

https://github.com/MariuzM/expo-starter

### Summary

When starting app fresh on iPhone for split second i still see the default splash screen (white with icon diagram) after full screen it start showing 
![SCR-20231028-nxdd](https://github.com/expo/expo/assets/36937039/5673dd69-65e4-49c8-989b-8a780ff38671)

https://github.com/expo/expo/assets/36937039/b8e9e374-9f13-420b-84e0-83474e23e9aa

Another problem is i have Red background SplashScreen component but i never see it

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.16 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.5.0
    Expo Workflow: bare

I build `ipa` file using `bunx expo prebuild && bunx pod-install && bunx eas build -p ios --profile preview --local` then i connect my iPhone and just drag the file there to be installed

**Comment by MariuzM** [comment]
Checking Xcode looks all ok here, so I'm not sure what I'm doing wrong 
<img width="1197" alt="image" src="https://github.com/expo/expo/assets/36937039/015b7ec8-4e76-4d4b-a39b-879514ef0a32">

**Comment by MariuzM** [comment]
I did just now noticed that this panel has it 
<img width="1218" alt="image" src="https://github.com/expo/expo/assets/36937039/b8ce160e-703f-44e4-a956-230f82587501">

but this one does not 
<img width="1155" alt="image" src="https://github.com/expo/expo/assets/36937039/9e367154-43bb-4f38-92ce-c344d4799ce5">

**Comment by brentvatne** [comment]
- run `bunx expo prebuild --clean` to ensure you re-generate the projects from scratch
- ios also caches splash screens, you might need to do a hard reset of the simulator / device to update it

**Comment by michaelkowalski** [comment]
> ios also caches splash screens, you might need to do a hard reset of the simulator / device to update it

@brentvatne this point saved me an additional debugging hour!

**Comment by arindambiswas1** [comment]
@brentvatne I am having a little different issue. In Expo Go, I can see the new splash screen, but after an EAS build and installing the build on a physical device, I do not see the new splash image; it shows me the old splash image. This issue is happening on both Android and iPhone. Expo version: `"expo": "~51.0.17"`.

**Comment by brentvatne** [comment]
@arindambiswas1 - can you create a new issue with a minimal repro please?

**Comment by delgiudices** [comment]
@brentvatne similar issue, the ios blank app icon splash screen is shown and after bundle is loaded my custom splash screen is displayed

**Comment by Hatta-Food-Hub** [comment]
same issue in latest sdk some kind of empty template comes when app launcg

**Comment by daochaojian** [comment]
> * ios also caches splash screens, you might need to do a hard reset of the simulator / device to update it

I don't know much about native app, does it happen in native app?  i mean installed a app with old splash then install latest app with new splash, iOS will cache splash? it doesn't make sence.

Still facing same issue on `"expo": "~51.0.28"`, tried to run `expo prebuild --clean` and remove build folder then `expo run:ios`.  None of those work.
