### ISSUE TITLE
[docs] expo-battery example causes hang

### ISSUE THREAD

**Issue by btrewern** [expo/expo#25095]
### Summary

After just copying and pasting the expo-battery example and running it (with some navigation to open and close the page) the app stops responding properly.

It seems the useEffect hook is called over and over but I'm new to react so can't follow the logic very well.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/battery/

**Comment by choeqq** [comment]
Is that issue already resolved? If not, I can pick it up 😄

**Comment by btrewern** [comment]
Nothing seems to have changed yet.

I have looked at the example app here: https://github.com/expo/expo/blob/999572cd1036529ffa3a28a0490dd7c0f6f0d731/apps/native-component-list/src/screens/ButtonScreen.tsx

this works without any hangs.

**Comment by amandeepmittal** [comment]
Hey @btrewern, can you share a minimal reproducible example so that I can test it out? I'm not able to reproduce the crash as you mentioned it on my end when using some sort of navigation.

**Comment by btrewern** [comment]
Hi,

You don't get a crash, the app just becomes less responsive.  To reproduce this I did the following:

```
$ yarn create expo battery_tester
$ cd battery_tester
$ npx expo install expo-battery
```

then change App.js to:

```javascript
import { useEffect, useState, useCallback } from 'react';
import * as Battery from 'expo-battery';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  const [batteryLevel, setBatteryLevel] = useState(null);
  const [subscription, setSubscription] = useState(null);

  const _subscribe = async () => {
    const batteryLevel = await Battery.getBatteryLevelAsync();
    setBatteryLevel(batteryLevel);

    setSubscription(
      Battery.addBatteryLevelListener(({ batteryLevel }) => {
        setBatteryLevel(batteryLevel);
        console.log('batteryLevel changed!', batteryLevel);
      })
    );
  };

  const _unsubscribe = useCallback(() => {
    subscription && subscription.remove();
    setSubscription(null);
  }, [subscription]);

  useEffect(() => {
    console.log('useEffect');
    _subscribe();
    return () => _unsubscribe();
  }, [_unsubscribe]);

  return (
    <View style={styles.container}>
      <Text>Current Battery Level: {batteryLevel}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

when I run this I get a continuous stream of "useEffect" in the console log.

**Comment by amandeepmittal** [comment]
Got it. Thank you so much for sharing the example. 

The `_unsubscribe` is causing the continuous stream. If you are using SDK 49, I'd suggest using [`useBatteryLevel`](https://docs.expo.dev/versions/v49.0.0/sdk/battery/#usebatterylevel) hook as you won't have to write the async function to get the battery level and then unsubscribe it or run a useEffect. We'll update the docs.
