### ISSUE TITLE
How to check if new version of app is available.

### ISSUE THREAD

**Issue by nsisodiya** [expo/expo#251]
I want to give this kind of pop to user.
![image](https://user-images.githubusercontent.com/333455/27002702-82293e52-4e05-11e7-8524-02317fb1e9b9.png)

I can reload the app using `Expo.Util.reload()` but When to trigger ?
Do have any API which I can constantly poll to check if new version is available.
whenever I do exp publish, Customer has to relaunch the app.
right now, I can think only for a hack.

Whenever I do a exp publish, I will store currentTimeStamp on server. Mobile app will poll is regularly to check if value of currentTimeStamp is updated. If value updated then it will call `Expo.Util.reload()`.

Need to know any better solution.

**Comment by nsisodiya** [comment]
I have implemented the PopUp - https://twitter.com/nsisodiya/status/873564163431211008/photo/1
But right now I am using a Hack. App constantly poll on a server which gives a current version of app. If It find the difference than it Prompt for reload. as shown in the tweet.

**Comment by terribleben** [comment]
Hi, polling a server to decide whether a new version is available is a good idea. It's unclear to me which part of this seems like a hack to you, since the client won't have this information otherwise. You probably don't need to poll constantly, e.g. some people choose to do this only when the app is foregrounded or when a particular screen is loaded.

Closing this since it seems like you figured out what to do.

**Comment by nsisodiya** [comment]
Unfortunately you closed the issue. When I close the Expo also check if new
version is available or not. How expo manage to do it. I want to apply same
logic in polling. Right now I am storing a variable in the cloud but
polling it. But I strongly believe that storing that variable is not
needed. All I need to know correct API to query in polling.

**Comment by brentvatne** [comment]
@nsisodiya - you can hit an endpoint like this to determine the most recently published date and compare it with the one in your `Expo.Constants.manifest`: https://expo.io/@community/native-component-list/index.exp?Exponent-Platform=ios&sdkVersion=17.0.0 (of course substitute the platform for the platform that you are using and the sdkVersion for the one that you have in the current manifest as well)

**Comment by crazyx13th** [comment]
Hi there, there isn't a android url, right? because the bundleUrl is allways ios, thx

**Comment by brentvatne** [comment]
notice that it says `Exponent-Platform=ios` -- change `ios` to `android`

**Comment by crazyx13th** [comment]
ios or android.... allways the same output, there is no apk, thx

**Comment by brentvatne** [comment]
sorry it actually uses request headers

<img width="1160" alt="screen shot 2017-07-26 at 10 59 41 am" src="https://user-images.githubusercontent.com/90494/28635997-919d769a-71f1-11e7-984a-78cd693c2989.png">
