### ISSUE TITLE
[expo-image] - rendering GIFs using Expo Image is causing FPS degradation when navigating with React Navigation.

### ISSUE THREAD

**Issue by bryanltobing** [expo/expo#25107]
### Minimal reproducible example

https://github.com/bryanltobing/expo-image-render-gif-slow

### Summary

Context: Our team decided to use `expo-image` to render all images in our app since it has many features that `Image` component by `react-native` doesn't have, such as rendering `svg`, `gif`, `contentFit` and `contentPosition` property.

When we tried to render a GIF, we noticed that when we navigate to a screen that has a GIF, it degrades the FPS of the UI thread and makes the transition look choppy.

When we switch back to `Image` component from`react-native` the issue doesn't happen and it can render smoothly without lag.

https://github.com/expo/expo/assets/46083126/750c2c29-d488-4e20-bbed-1a8e37545b87

In our real app, the fps even drops to 40 fps

https://github.com/expo/expo/assets/46083126/1b45da81-ed75-465b-8e54-30c86c9faa66

Platform: IOS

I haven't checked for android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - /opt/homebrew/bin/npm
      Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/bryan/.gem/ruby/2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed

**Comment by DylanTet** [comment]
Ill try looking into this if I have some time today, I've seen a decent amount of effort on the Android side but not iOS.

**Comment by bryanltobing** [comment]
Hi @DylanTet Thanks for the reply. Yes i haven't test in android device but in ios this is really noticeable

**Comment by DylanTet** [comment]
@bryanltobing even with work towards android side it seems like there's a noticeable performance dip with Image

**Comment by gkasdorf** [comment]
Appears to be fixed in #25008 

Comparison: 

https://github.com/expo/expo/assets/127079571/eda751ab-0653-4a3e-89f4-29c1377ab4d6

**Comment by bryanltobing** [comment]
@gkasdorf is there a way to test it so that i can confirm?

Sorry but I'm new to the Expo package, is there an ETA for the fix release? since last release was two months ago

**Comment by gkasdorf** [comment]
> @gkasdorf is there a way to test it so that i can confirm?
> 
> Sorry but I'm new to the Expo package, is there an ETA for the fix release? since last release was two months ago

I am under the impression that some changes will be published in the next few days, but I don't know that to be true. AFAIK there are also some breaking changes that they are waiting to publish until SDK 50.

As for whether you can test it: yes, it is possible. You can use https://gitpkg.vercel.app to do so if you want, but I **wouldn't recommend** doing it for anything but testing. Like I said, there are supposedly breaking changes on Android and I'm not sure when in the history they were added.

1. Use https://github.com/expo/expo/tree/7b089eb567afa51e2a0a0f2207d90524adafa40a/packages/expo-image as the commit to install from
2. GitPkg should give you `yarn add 'https://gitpkg.now.sh/expo/expo/packages/expo-image?7b089eb567afa51e2a0a0f2207d90524adafa40a'` or `npm install 'https://gitpkg.now.sh/expo/expo/packages/expo-image?7b089eb567afa51e2a0a0f2207d90524adafa40a'`, depending on what you use. Sometimes you'll end up with a 504. If you try again it should work.
3. Run another `yarn install` to make sure things are up to date then a `pod install`.
4. Rebuild your iOS app

**Comment by bryanltobing** [comment]
@gkasdorf  i can't seem to find where it being published

i tried v1.5.1.

https://github.com/expo/expo/assets/46083126/4c005cce-fe65-4f0a-858f-264ae11337c8



but the issue still there

**Comment by gkasdorf** [comment]
@bryanltobing `yarn install expo-image@next` should do the trick.

**Comment by bryanltobing** [comment]
can confirm in my app that this issue is fixed in v1.7.0

https://github.com/expo/expo/assets/46083126/bc36dc82-9e09-4782-9ef8-61bd72b6d63f

Thanks @gkasdorf @DylanTet
