### ISSUE TITLE
Error on "run fastlane" step while building with expo

### ISSUE THREAD

**Issue by andreas-moneygate** [expo/expo#25115]
### Summary

Suddenly building IOS with expo is not working. Only change was accepting new terms and conditions with Apple.

"Build failed: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs."

error: File /Users/expo/Library/Developer/Xcode/DerivedData/Moneygate-ejsypnaybrnqcndbhqaksklbolce/Build/Intermediates.noindex/ArchiveIntermediates/Moneygate/BuildProductsPath/Release-iphoneos/Moneygate.app/main.jsbundle

** ARCHIVE FAILED **

▸ The following build commands failed:

▸ PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/Moneygate-ejsypnaybrnqcndbhqaksklbolce/Build/Intermediates.noindex/ArchiveIntermediates/Moneygate/IntermediateBuildFilesPath/Moneygate.build/Release-iphoneos/Moneygate.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'Moneygate' from project 'Moneygate')

### What platform(s) does this occur on?

iOS

### SDK Version

47.0.13

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9514443
    npmPackages:
      expo: ^47.0.13 => 47.0.14
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.8 => 0.70.8
      react-native-web: ~0.18.9 => 0.18.12
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/andreas-moneygate/mobile-app

**Comment by elobredor** [comment]
i have the same error too. 
![image](https://github.com/expo/expo/assets/116308289/4d76c656-41c8-4c71-8d34-7c63667fdc99)

**Comment by elobredor** [comment]
https://github.com/facebook/react-native/issues/41229#issuecomment-1784409448
I tried this but it didn't work

**Comment by brentvatne** [comment]
hey there, check out the guide for troubleshooting build errors: https://docs.expo.dev/build-reference/troubleshooting/

at the bottom of the page there is more information on how to ask a good question after you've followed the guide if you're still stuck: https://docs.expo.dev/build-reference/troubleshooting/#how-to-ask-a-good-question

**Comment by ByronStar** [comment]
Having exactly the same environment and the same issue, I had a look at the Xcode log and found

/Users/expo/workingdir/build/node_modules/react-native/scripts/react-native-xcode.sh: line 169: /Users/expo/workingdir/build/ios/Pods/hermes-engine/destroot/bin/hermesc: No such file or directory

For me this looked quite like a react-native issue and I tried to fix it by forcing JSC engine in app.json:

{ "expo": { "jsEngine": "jsc" } }

But that didn't help ☹️

The react-native-xcode.sh: line 169 did not change lately, so my question is: why is all of a sudden HERMES involved for an iOS build based on SDK 47 explicitly requesting JSC engine?

**Comment by ByronStar** [comment]
"Fun" fact using

{ "expo": { "jsEngine": "hermes" } }

fixed the build issues - but we are not sure whether we want to or even can switch the engine right now.

**Comment by brentvatne** [comment]
here's my follow up on the original thread: https://github.com/facebook/react-native/issues/41229#issuecomment-1788088813

**Comment by AbdessamieAbdellah** [comment]
Thank you [ByronStar](https://github.com/ByronStar), your solution worked for me.

**Comment by andreas-moneygate** [comment]
Managed to build today without changing anything.

**Comment by brentvatne** [comment]
@andreas-moneygate - we reverted the recommend react-native version for sdk 47 from 0.70.14 to 0.70.8, so we no longer pull in the commit from react-native that caused this regression
