### ISSUE TITLE
Detached Expokit App: Values from AndroidManifest gets overwritten by Expo in Build process? 

### ISSUE THREAD

**Issue by normenster** [expo/expo#2511]
I have a detached Expokit App. I want to remove some permissions. I did so in the AndroidManifest.xml. 
In the final APK (generate signed APK), AndroidManifest.xml magically contains all values i removed.
Does Expo somehow overwrite the AndroidManifest File with permissions? Also, I changed `app.json` and included `"permissions:[]"`, but it didn`t had any impact. Can you give me a hint where i can change those permissions?

**Comment by ide** [comment]
At the time of detaching, `"permissions": []` should reduce the set of permissions to the minimum required: https://docs.expo.io/versions/latest/guides/configuration.html#android-602. These permissions are always required, though:
```
      •	receive data from Internet
      •	view network connections
      •	full network access
      •	change your audio settings
      •	draw over other apps
      •	prevent device from sleeping
      •	view network connections
      •	full network access
      •	change your audio settings
      •	draw over other apps
      •	prevent device from sleeping
```

If you are seeing those getting added back, that's normal.

**Comment by normenster** [comment]
No, i meant different permissions, like contacts and location etc. I found libs that added them in the merged manifest tab in android studio. I was able to remove them there.

**Comment by Morriz** [comment]
Hi @normenster, I have the same issue with "ghost" permissions being written back in, but I can't find any reference in all of the files. How did you find those? What files did you edit/remove?

**Comment by gerbus** [comment]
You might want to check [this article](https://medium.com/building-with-react-native/how-to-remove-unnecessary-android-permissions-from-react-native-apps-1x05-c5c98b6c93a8) out.

I took away that you can create a second `AndroidManifest.xml` in a `/release` folder and remove any permissions that are only required for debugging.
