### ISSUE TITLE
ImageManipulator turns portrait images into landscape images when resizing on Galaxy S phones

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#2512]
### Environment

Environment:
  OS: macOS 10.14
  Node: 8.12.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/nudge-a29cc14d-c1c1-4bae-a3d4-a72adb002b04.tar.gz

Target:
Android 7.0 and 8.1 on Galaxy S phones (have verified this issue on the Galaxy S6 running Android 7.0 and the Galaxy S8 running 8.1, specifically). Target is standard Expo and ExpoKit (confirmed on two different apps and a snack).

### Steps to Reproduce

1. Take a portrait picture or grab a picture from the photo roll with Expo.ImagePicker.
2. Resize the image to fit within a maximum height (e.g., 640px) (retaining aspect ratio), e.g., `ImageManipulator.manipulate(image.uri, { resize: { height: 640 } }, { format: 'jpeg' })`
3. Display the image on the screen using `resizeMode="contain` (so you can see its full dimensions).

### Expected Behavior

The image would be resized to fit within a 640x640px square (since the largest dimension on a portrait is its height). So, a 3:4 portrait image would have a 480x640 resolution. The image would display in its original portrait orientation. It would look like it does on iOS and non-Galaxy S phones (like this picture from a Moto G4 Play running Android 7.0):

![screenshot_20181024-150225](https://user-images.githubusercontent.com/8053974/47503066-3774c300-d837-11e8-9e9d-b32bb107c58d.png)

### Actual Behavior

The image is in landscape orientation after the resize manipulation. The resize is applied after the orientation flip, so the smaller of the two dimensions is resized while maintaining the aspect ratio. So, a 3:4 portrait image is resized to a 853x640 landscape image.

Here is an example from the Galaxy S8 running Android 8.1. This looks the same on a Galaxy S6 running Android 7.0.

![screenshot_20181024-150133_expo](https://user-images.githubusercontent.com/8053974/47503247-a3572b80-d837-11e8-8f5a-726cef7a1dab.jpg)

### Reproducible Demo

Here's a snack that demonstrates the issue: https://snack.expo.io/@llamaluvr/image-manipulator-android-orientation-issue

Some further discussion is on https://forums.expo.io/t/imagemanipulator-resize-thinks-portrait-images-are-landscape-on-galaxy-s-phones/15159. There I outline some other attempts at working around this that don't work, and one that kind of does but seems rather brittle. In short, we can generally detect if the resize failed to produce the intended results by looking at the dimensions post-resize, then looking at exif data and rotating the image accordingly before resizing again.

This has shown up in non-RN/ Expo contexts as a bug, e.g.: https://github.com/google/cameraview/issues/22#issuecomment-269321811 (they suggest pre-applying rotations based on Exif data in the native Java, but I'm not clear on how they avoid overcompensating on devices where this is not an issue).

**Comment by andymax** [comment]
The problem is a issue on Nokia 8 as well.

**Comment by andymax** [comment]
This works for me ...I'm sure I'm not compensating fore everything ...but while I'm waiting for a bug-fix :-)
`			if(result.width > 1242) {
				let isLandscape = (result.width > result.height);
				
				try {
					newResult = await ImageManipulator.manipulate(
						result.uri,
						[{resize: {width: 1242}}],
						{compress: 1, format: 'jpeg', base64: false }
					);
				} catch (error) {
					console.error(error);
				}
				
				if(isLandscape !== (newResult.width > newResult.height)) {
					try {
						result = await ImageManipulator.manipulate(
							result.uri,
							[{rotate: 90}, {resize: {width: 1242}}],
							{compress: 1, format: 'jpeg', base64: false }
						);
					} catch (error) {
						console.error(error);
					}
				} else {
					result = newResult;
				}
			}
`

**Comment by paolitaclo** [comment]
hi @andymax thanks for the code section, it works for me on Android 9.0 (tested on pixel 2XL but it breaks on IOS, did you have that problem with IOS too?

**Comment by andymax** [comment]
Hi @paolitaclo no didn't test on iOS ...it wouldn't work on rectangular images or if the phone was tilted right instead of left when taking the picture, i suppose. It's super buggy ...I really hope a bug-fix is comming soon.

**Comment by llamaluvr** [comment]
Hey good news! This appears to be resolved in Expo 31! I've updated my snack to 31 so anyone who wants to can try it again: https://snack.expo.io/@llamaluvr/image-manipulator-android-orientation-issue. This doesn't happen anymore on my S8, though.

So I will close this issue. If you have a similar issue on iOS that still occurs under Expo 31, I'd recommend opening a separate issue.

Since I had to ship an app in the meantime with Expo 30, for posterity, here is a workaround I used that's based on non-zero EXIF Orientation values being present on the phones that had the issue. It adds the corresponding image manipulation operation.
```
static async resizeImage(pickedImage) {
      const operations = [];
      // for Android only - check exif info and do pre-rotate
      // this fixes for Galaxy S and maybe others
      if (Platform.OS === 'android' && pickedImage.exif && pickedImage.exif.Orientation > 1) {
        let rotateOperation;
        let orientation = pickedImage.exif.Orientation;
        // landscape - upside down
        if (orientation === 3) {
          rotateOperation = { rotate: 180 };
        }
        // portrait - right side up
        if (orientation === 6) {
          rotateOperation = { rotate: 90 };
        }
        // portrait - upside down
        if (orientation === 8) {
          rotateOperation = { rotate: -90 };
        }
        
        if (rotateOperation) {
          operations.push(rotateOperation);
        }
      }

      // add resize op as last op
      let resizeObj = {};
      if (pickedImage.height > pickedImage.width) {
        resizeObj = { height: 640 };
      } else {
        resizeObj = { width: 640 };
      }
      operations.push({ resize: resizeObj })
      let manipResult = await ImageManipulator.manipulate(
        pickedImage.uri,
        operations,
        {
          format: 'jpeg',
        }
      );

      return {
        uri: manipResult.uri,
        name: 'photo.jpg',
        type: 'image/jpeg',
        width: manipResult.width,
        height: manipResult.height,
      };
  }
```

**Comment by joaopiopedreira** [comment]
Thank you @llamaluvr , worked like a charm 💯
