### ISSUE TITLE
[expo-contacts] [iOS] Passing an Image to `Contacts.presentFormAsync` crashes Expo Go

### ISSUE THREAD

**Issue by hueter** [expo/expo#25128]
### Minimal reproducible example

https://github.com/hueter/expo-contacts-image-bug

### Summary

Hello!

In my app I'm trying to preload a contact's image from a URI provided, but it seems to crash everything on iOS.

### Crash Video

https://github.com/expo/expo/assets/13444851/2906199c-de78-4917-9dfa-2d4dc7d3106c

### Repro

In my [minimal reproducible example](https://github.com/hueter/expo-contacts-image-bug), it's this line that breaks: 

https://github.com/hueter/expo-contacts-image-bug/blob/d80fa42892849957105e11afc00183a6205a9f7b/App.tsx#L17-L19

It also seems to break with base64-encoded images.

### Console / Crash Report

This shows up in the console:

<img width="1453" alt="Screenshot 2023-10-30 at 8 53 25 PM" src="https://github.com/expo/expo/assets/13444851/b8684288-c00e-462d-b032-4a717c8114af">

so I think it's this line that is having problems: https://github.com/expo/expo/blob/8156a6ff57353fc50f02537d0b6aefd1033c9f29/packages/expo-contacts/ios/EXContacts/EXContacts.m#L829

Here is the crash report (not sure if helpful 😅 )

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: CF3825A5-D2F2-4B7C-ADF5-23C61ADB7514
CrashReporter Key:   95002A4A-5FDC-6E4B-C74F-C8F94E6325A4
Hardware Model:      MacBookPro18,1
Process:             Expo Go [42807]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/CD326108-6523-4BC3-B958-70BC8411AFEE/data/Containers/Bundle/Application/36A89978-31A4-4D4C-A792-8652BC3635F2/Exponent-2.29.6.tar.app/Expo Go
Identifier:          host.exp.Exponent
Version:             2.29.6 (2.29.6)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [39664]
Coalition:           com.apple.CoreSimulator.SimDevice.CD326108-6523-4BC3-B958-70BC8411AFEE [44357]
Responsible Process: SimulatorTrampoline [13444]

Date/Time:           2023-10-30 20:49:36.6073 -0400
Launch Time:         2023-10-30 20:49:21.5938 -0400
OS Version:          macOS 14.0 (23A344)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: Expo Go [42807]

Triggered by Thread:  0

Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
```

### Environment

``` 
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.1/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
      Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /Users/hueter/.rvm/gems/ruby-3.2.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
I believe the intent here was that you pass in a **local image URI**, however that is missing from the documentation. You can use `FileSystem.downloadAsync` to download the remote image, then pass in that local URI to the contacts API

**Comment by hueter** [comment]
> I believe the intent here was that you pass in a **local image URI**, however that is missing from the documentation. You can use `FileSystem.downloadAsync` to download the remote image, then pass in that local URI to the contacts API

Thanks for the reply! I implemented those changes on my repro repository in [this commit](https://github.com/hueter/expo-contacts-image-bug/commit/9449b27f91c89b1c7d6dc7eb801334cb7869ec5c), and it fixed the issue in the simulator / Expo Go:

<img width="373" alt="Screenshot 2023-10-31 at 8 06 00 PM" src="https://github.com/expo/expo/assets/13444851/d78b0f19-c991-480a-b56b-142861de1150">

I also opened #25150 in case that will help avoid this crash in the future.

Feel free to close this issue if it's not an actual "bug"!
