### ISSUE TITLE
[expo-notifications][sdk 49]`date` field of `Notifications.Notification` is a number in seconds instead of milliseconds?

### ISSUE THREAD

**Issue by nathantew14** [expo/expo#25131]
### Minimal reproducible example

https://gist.github.com/nathantew14/e56b9d71cd203295314ec9e563ce9c76

### Summary

Expected the `notification.date` field to contain the date that the notification was sent (or received...?) in milliseconds, but it was in seconds instead. Not sure if this is intended behaviour as [the docs](https://docs.expo.dev/versions/latest/sdk/notifications/#notification) do not say anything about what this `date` field is supposed to be.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/development/.npm/lib/node_modules/yarn/bin/yarn
      npm: 9.6.2 - /usr/local/bin/npm
      Watchman: 2023.08.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0, 32.0.0, 32.0.0, 33.0.0, 34.0.0
        System Images: android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.5 => 49.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.6.0
    Expo Workflow: bare

**Comment by kanthi0802** [comment]
Hey, 

Is there an update on this. We were also under the impression that the notifcation.date would contain the exact datetime when the notification was created. But we realised that the date is always 1970 Jan 20 10:57 PM, which would only mean it's hardcoded.

Could somebody look into this please?

**Comment by douglowder** [comment]
I'll take a look
