### ISSUE TITLE
[docs] resourceClass for android and iOS in /eas/json

### ISSUE THREAD

**Issue by joonshakya** [expo/expo#25157]
### Summary

The link for `Android-specific resource class field` points to `https://docs.expo.dev/eas/eas-json#resourceclass-1` instead of `https://docs.expo.dev/eas/json#resourceclass-1` and similar case for `iOS-specific resource class field`

### Link to the related docs page

https://docs.expo.dev/eas/json

### Anything else?

Yes I want to fix the typo

**Comment by amandeepmittal** [comment]
This was fixed in #25158 by @joonshakya (thank you!).
