### ISSUE TITLE
Could not set unknown property 'classifier' for task ':expo-firebase-core:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

### ISSUE THREAD

**Issue by axelphunter** [expo/expo#25164]
### Minimal reproducible example

Build file '/Users/axelhunter/Development/bare/ReceiptRadar/node_modules/expo-firebase-core/android/build.gradle' line: 40

### Summary

* Where:
Build file '/Users/axelhunter/Development/bare/ReceiptRadar/node_modules/expo-firebase-core/android/build.gradle' line: 40

* What went wrong:
A problem occurred evaluating project ':expo-firebase-core'.
> Could not set unknown property 'classifier' for task ':expo-firebase-core:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.

Fix found here [https://github.com/expo/expo/issues/23023](url)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.3 - /opt/homebrew/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/axelhunter/.gem/ruby/3.2.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.5.0 => 9.5.2
      expo: ~49.0.15 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by Kudo** [comment]
hi there! expo-firebase-core had been deprecated from expo sdk 48. please refer the guide for alternative solution for react-native-firebase: https://expo.fyi/firebase-migration-guide
