### ISSUE TITLE
expo-av video player keeps updating after pausing

### ISSUE THREAD

**Issue by abanoub2amin** [expo/expo#25180]
### Summary

When we set `shouldPlay={true}` or trying to asynchronously play the video when the video gets ready the video status keeps updating after pausing the video on Android and iOS devices. 
`isPlaying` status turns from false to true and keeps updating. however, the video is actually paused and that makes the video player component keep re-rendering forever.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

"expo": ">=44.0.0-0 <45.0.0",     "expo-av": "11.1.0",

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.2.0 - /opt/homebrew/bin/npm
      Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/abanoubamin/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.5 => 0.67.5 
    Expo Workflow: bare

### Minimal reproducible example
```
const [playbackSuccessStatus, setPlaybackSuccessStatus] =
    useState<null | AVPlaybackStatusSuccess>(null);
  const [playbackError, setPlaybackError] = useState<null | string>(null);
  
  const onPlaybackStatusUpdate = (status: AVPlaybackStatus) => {
    if (status.isLoaded) {
      // This is a successful playback status
      setPlaybackSuccessStatus(status);
    } else if (status.error) {
      // This is an error playback status
      setPlaybackError(status.error);
    }
  };
```
```
<Video
        ref={videoPlayerRef}
        shouldPlay={true} // <-- this is the reason behind my issue
        isLooping={true}
        usePoster={false}
        useNativeControls={false}
        progressUpdateIntervalMillis={150}
        source={{ uri: url }}
        style={styles.videoPlayer}
        resizeMode={ResizeMode.CONTAIN}
        onReadyForDisplay={toggleShowingAndroidControls}
        onPlaybackStatusUpdate={onPlaybackStatusUpdate}
      />
```
Expo-AV video player in the previous code snippet `shouldPlay={true}` makes `onPlaybackStatusUpdate` keep updating after pausing the video on Android and iOS devices.

**Comment by behenate** [comment]
Hi, can you provide a valid minimal reproducible example? A Snack or a Github repo with a simple project that reproduces the issue makes our job a lot easier and speeds up the time it takes to resolve it.

**Comment by abanoub2amin** [comment]
> Hi, can you provide a valid minimal reproducible example? A Snack or a Github repo with a simple project that reproduces the issue makes our job a lot easier and speeds up the time it takes to resolve it.

Done

**Comment by behenate** [comment]
@abanoub2amin Hi! I still cant reproduce the issue. I just noticed that you are using an old `expo` and `expo-av` verisions. Can you try upgrading and see if the issue persists?
