### ISSUE TITLE
[SDK 49] useFrameworks: static  causes error Undefined symbol: facebook::react::LongLivedObjectCollection::add(std::__1::shared_ptr<facebook::react::LongLivedObject>) const

### ISSUE THREAD

**Issue by banesp** [expo/expo#25189]
### Minimal reproducible example

TODO

### Summary

Upgrading our Expo application to SDK 49 we are experiencing issues while building for iOS. The issue is caused by `expo-build-properties` `ios.useFrameworks: "static"`, which is necessary for using @react-native-firebase. This worked flawlessly in Expo SDK 47.

package.json dependencies :
```
"expo": "^49.0.16",
"expo-build-properties": "~0.8.3",
"expo-dev-client": "~2.4.11",
"react": "18.2.0",
"react-native": "0.72.6",
"react-native-reanimated": "~3.3.0"
```

app.config.js plugins:
```
plugins: [
    [
      "expo-build-properties",
      {
        ios: {
          newArchEnabled: false,
          useFrameworks: "static",
        },
      },
    ],
]
```

Projects seems to build fine with prebuild, but when I open the project in Xcode 15 and try to run it I get the following error:
```
Undefined symbol: facebook::react::LongLivedObjectCollection::add(std::__1::shared_ptr<facebook::react::LongLivedObject>) const

Linker command failed with exit code 1 (use -v to see invocation)
```

I noticed there has been lacking support for useFrameworks with Flipper, Hermes and Fabric previously, but from what I understand from the links below is that it should be working with react-native 0.72.x

I'll  come up with a minimal reproducible example if that is helpful..

Might be of relevance:
https://github.com/reactwg/react-native-new-architecture/discussions/129
https://github.com/reactwg/react-native-new-architecture/discussions/115
https://github.com/expo/expo/pull/23218

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.16 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    npmGlobalPackages:
      eas-cli: 5.6.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by Kudo** [comment]
hi there! i tried to create a project with the following steps and it works for me. could you try to create a minimal reproducible example and upload to some git repository? we are happy to investigate if we can repro the problem.

```sh
$ yarn create expo -t blank@sdk-49 sdk49
$ cd sdk49
$ npx expo install expo-build-properties expo-dev-client react-native-reanimated
# add newArchEnabled: false and useFrameworks: "static" to app.json
$ npx expo run:ios
```

**Comment by banesp** [comment]
Hi @Kudo , I tried creating a clean minimal reproducible example, but I couldn't reproduce the issue. Still present in my old existing project though.

**Comment by Kudo** [comment]
@banesp 100% understand that's frustrating. but we are not to further investigate if that's something we cannot reproduce inhouse.

something worth to try, if you have git to see the diff. running `npx expo prebuild -p ios --clean` to generate all the native ios folder and see whether it helps.

**Comment by wwiiddeeweb** [comment]
hi @banesp , how did u solved it? i'm struggling with the same migrating from sdk v48 to v49. thanks!

**Comment by wilmxre** [comment]
hey @wwiiddeeweb and @banesp did you manage to fix this?

**Comment by wilmxre** [comment]
thanks @banesp for the info. yeah i think this issue is indeed related to Firebase as https://github.com/mrousavy/react-native-vision-camera/issues/1126#issuecomment-1193807316 indicates that too. if it is not a big effort to you, could you share the content of your Podfile, please?

**Comment by wilmxre** [comment]
so i managed to fix this issue somehow, but i am not sure what was the working solution for this in the end.

basically i added `$FirebaseSDKVersion = '10.20.0'` to the top of Podfile, as per https://rnfirebase.io/#ios

then added `use_modular_headers!` right after the target, like: 
```rb
target '<project_name>' do
  use_expo_modules!
  use_modular_headers!
  config = use_native_modules!
  ```

but this wasn't enough, the build still failed with `Showing Recent Issues
Undefined symbol: facebook::react::LongLivedObjectCollection::add(std::__1::shared_ptr<facebook::react::LongLivedObject>) const`

after this i uncommented these:
```rb
use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
```

and it fixed the failing build, i tested my app roughly and i didn't notice any issues. i don't know what was the use of those `use_frameworks!`, but the combination of these actions made the build error disappear

**Comment by iain-neirfeno** [comment]
After spending far too long on this it seems that something is being cached somewhere on my computer. If I try and run on iOS simulator I get the error in this issue. If I then move the project to a different directory and run, it launches successfully.

Unfortunately closing issues because your not able to reproduce is akin to "It works on my machine", which we all know is completely useless.

Sad times
