### ISSUE TITLE
Feature Request: Add Geocoder with Google fallback

### ISSUE THREAD

**Issue by markacola** [expo/expo#252]
I would like to be able to use native Geocoding with a Google Geocoding fallback, as is implemented here: https://github.com/devfd/react-native-geocoder.
I am not sure how to add this as a dependency to submit a PR with this additional functionality, if I could be directed to a commit that adds and external native library that I can use as an implementation reference then I am happy to submit a PR.

**Comment by dikaiosune** [comment]
Hi! We have an open feature request for this: https://expo.canny.io/feature-requests/p/reverse-geocoding. I'll close this in favor of that but please vote on Canny and add a comment with any details we might be missing there. Thanks!
