### ISSUE TITLE
Does choosing the latest package version(having compiledSDKVersion 34 in Build.gradle) solve Android 14 Upgrade Issue?

### ISSUE THREAD

**Issue by ShaminiSaravanan** [expo/expo#25204]
### Minimal reproducible example

Upgrade your Project to support Android 14 (SDK Version 34)

### Summary

I would like to understand whether I should choose any NPM package version for my project that has compiledSDKVersion set to 34 (Android 14) when I attempt to upgrade my project's SDK version to 34. This is because I haven't found any package version that is currently released with compiledSDKVersion 34.

For example, during my SDK 33 upgrade, I encountered several new issues. To address these, I had to update the NPM version to the latest one that supports SDK 33 for the relevant packages. By doing this for a couple of packages, I was able to resolve all the issues related to SDK 33.

Let's take the 'EXPO' package as an example. In our code, we are using 'expo: “45”’, but when it's upgraded to the latest version, it becomes 'expo: “49”’.

Please refer to the screenshots below. The first screenshot displays the 'Build.gradle' file of the old version, which targets SDK version 30. The second screenshot shows the upgraded Expo dependency, and its 'Build.gradle' file targets SDK version 33. It's worth noting that the latest package version does not support compiledSDKVersion 34, which is what I'm currently upgrading to.

First ScreenShot:
<img width="413" alt="Pasted Graphic" src="https://github.com/expo/expo/assets/147727739/d1c76b9f-2b64-46a8-8dbf-18afe7071114">

Second ScreenShot:
<img width="366" alt="compileSdkVersion safeExtGet (compileSdkVersion, 33)" src="https://github.com/expo/expo/assets/147727739/26ebad17-b727-430d-8523-bbd3399abf9c">

The reason I want to clarify this issue is that after updating my project's 'Build.gradle' to support Android 14 (SDK 34), my app crashes with the following details in the bug report:
* Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but the BridgeDevSupportManager class was not found or could not be created.
* Caused by: java.lang.SecurityException: Either RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts.
* Caused by: java.lang.reflect.InvocationTargetException.
* Caused by: android.os.RemoteException: Remote stack trace.

Therefore, if I use latest package version that support compiledSDKVersion 34, there is a chance that these errors mentioned above will be resolved.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /opt/homebrew/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.21 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
    Expo Workflow: bare

**Comment by alanjhughes** [comment]
Hi, you do not need to update this yourself. The next version of React native will target SDK 34. On Android, not having it set to 34 does not mean your app cannot run on android 14 devices.

**Comment by ShaminiSaravanan** [comment]
Can you help me determine which version of React Native supports SDK 34?

I am currently using version 0.70.8, and it is crashing. I don't want to update React Native Version unless the SDK is supported in the latest version as my current version is compatible with both iOS and Android platforms

**Comment by alanjhughes** [comment]
There is no released version of React Native that targets API 34 yet. I'm not sure I understand what you are trying to do?
