### ISSUE TITLE
[expo-sqlite] There are some warnings popping up

### ISSUE THREAD

**Issue by Vvaraz** [expo/expo#25212]
### Minimal reproducible example

I have replicated the example of the to-do list from the document. https://github.com/expo/examples/blob/master/with-sqlite/App.js

### Summary

Merely invoking the “openDatabase” function without any further actions prompts wrongs in the console.
![image](https://github.com/expo/expo/assets/73987251/dbca2de3-3086-45f3-b023-636a0e0284db)
![image](https://github.com/expo/expo/assets/73987251/92a2630b-efbb-4508-b512-2aee70819bb2)

### Environment

expo-env-info 1.0.5 environment info: 
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.15.0 - E:\nodejs\node.EXE
      Yarn: 1.22.19 - E:\nodejs\yarn.CMD
      npm: 8.5.5 - E:\nodejs\npm.CMD    
    npmPackages:
      expo: ~49.0.13 => 49.0.13         
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6    
    Expo Workflow: bar

**Comment by Kudo** [comment]
hi there! i tried to create a project from the with-sqlite and it works for me. these are my steps

```sh
$ npx create-react-native-app@latest -t with-sqlite
# create a "sqliteapp" project 
$ cd sqliteapp
$ npx expo start
# press "i" to launch ios expo-go
$ press "a" to launch android expo-go

$ npx expo run:ios # test on a bare project
```

could you maybe share more details of your project?
- expo-sqlite version (through `yarn why expo-sqlite`)
- how did you start your project? did you run in expo-go or bare project?
- did you run on ios or android?
