### ISSUE TITLE
Dev client not re-requesting permissions after reinstall

### ISSUE THREAD

**Issue by ChristopherGabba** [expo/expo#25214]
### Summary

I am using various expo packages (expo video, expo contacts, expo media library, etc.) and after deleting the app, creating a new development build, and re-installing the build on the iPhone screen, it does not re-request permissions as expected. It used to do this and sometime in the past few weeks I've noticed I can't get the permissions to get asked again, even after a complete re-install of the development client app. 

Basing some screens and modals based off of this so trying to reinstall the app just for this purpose makes the app workflow difficult to test.

I do make sure that I can delete

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

See full package.json:

```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "react-native start",
    "ios": "react-native run-ios",
    "android": "react-native run-android --active-arch-only",
    "test:detox": "detox test -c ios.sim.debug",
    "build:detox": "detox build -c ios.sim.debug",
    "ci:test:detox": "detox test -c ios.sim.release -l verbose --cleanup",
    "ci:build:detox": "detox build -c ios.sim.release",
    "compile": "tsc --noEmit -p . --pretty",
    "format": "prettier --write \"app/**/*.{js,jsx,json,md,ts,tsx}\"",
    "lint": "eslint index.js App.js app test --fix --ext .js,.ts,.tsx && npm run format",
    "patch": "patch-package",
    "test": "jest",
    "test:watch": "jest --watch",
    "adb": "adb reverse tcp:9090 tcp:9090 && adb reverse tcp:3000 tcp:3000 && adb reverse tcp:9001 tcp:9001 && adb reverse tcp:8081 tcp:8081",
    "postinstall": "node ./bin/postInstall",
    "bundle:ios": "react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios",
    "bundle:android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
    "release:ios": "echo 'Not implemented yet: release:ios. Use Xcode. More info: https://reactnative.dev/docs/next/publishing-to-app-store'",
    "release:android": "cd android && rm -rf app/src/main/res/drawable-* && ./gradlew assembleRelease && cd - && echo 'APK generated in ./android/app/build/outputs/apk/release/app-release.apk'",
    "clean": "npx react-native-clean-project",
    "clean-all": "npx react-native clean-project-auto",
    "expo:start": "expo start",
    "expo:android": "expo start --android",
    "expo:ios": "expo start --ios",
    "expo:web": "expo start --web",
    "expo:build:detox": "detox build -c ios.sim.expo",
    "expo:test:detox": "./bin/downloadExpoApp.sh && detox test --configuration ios.sim.expo"
  },
  "overrides": {
    "react-native": "0.72.5",
    "react-error-overlay": "6.0.9"
  },
  "dependencies": {
    "@aws-amplify/ui-react-native": "^1.2.28",
    "@expo-google-fonts/m-plus-1p": "^0.2.3",
    "@expo-google-fonts/montserrat": "^0.2.3",
    "@expo-google-fonts/space-grotesk": "^0.2.2",
    "@expo/config-plugins": "^7.2.5",
    "@expo/metro-config": "^0.10.7",
    "@gorhom/bottom-sheet": "^4.4.7",
    "@likashefqet/react-native-image-zoom": "^2.1.1",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-clipboard/clipboard": "^1.11.2",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-picker/picker": "^2.5.1",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.0.2",
    "@shopify/flash-list": "1.4.3",
    "amazon-cognito-identity-js": "^6.3.6",
    "apisauce": "2.1.5",
    "aws-amplify": "^5.3.11",
    "aws-sdk": "^2.1472.0",
    "axios": "^1.5.0",
    "cheerio": "^1.0.0-rc.12",
    "date-fns": "^2.29.2",
    "expo": "^49.0.7",
    "expo-application": "~5.3.0",
    "expo-av": "~13.4.1",
    "expo-blur": "~12.4.1",
    "expo-clipboard": "~4.3.1",
    "expo-config-plugin-ios-share-extension": "^0.0.4",
    "expo-constants": "~14.4.2",
    "expo-contacts": "~12.2.0",
    "expo-dev-client": "~2.4.11",
    "expo-device": "~5.4.0",
    "expo-file-system": "~15.4.4",
    "expo-font": "~11.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-localization": "~14.3.0",
    "expo-media-library": "~15.4.1",
    "expo-splash-screen": "^0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-video-thumbnails": "~7.4.0",
    "firebase": "^10.3.1",
    "i18n-js": "3.9.2",
    "jsdom": "^22.1.0",
    "jsdom-jscore-rn": "^0.1.8",
    "lodash": "^4.17.21",
    "lodash.filter": "^4.6.0",
    "mobx": "6.6.0",
    "mobx-react-lite": "3.4.0",
    "mobx-state-tree": "5.1.5",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-native-animated-pagination-dots": "^0.1.73",
    "react-native-bootsplash": "^5.0.2",
    "react-native-element-dropdown": "^2.9.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-get-random-values": "^1.9.0",
    "react-native-pager-view": "6.2.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-receive-sharing-intent": "^2.0.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-share-menu": "^6.0.0",
    "react-native-static-safe-area-insets": "^2.2.0",
    "react-native-touchable-scale": "^2.2.0",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-vision-camera": "^3.6.4",
    "react-native-volume-manager": "^1.10.0",
    "react-native-webview": "13.2.2",
    "react-native-youtube-iframe": "^2.3.0",
    "reactotron-mst": "3.1.4",
    "reactotron-react-js": "^3.3.7",
    "reactotron-react-native": "5.0.3",
    "typescript": "^4.9.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/cli-platform-ios": "^8.0.2",
    "@rnx-kit/metro-config": "^1.3.5",
    "@rnx-kit/metro-resolver-symlinks": "^0.1.26",
    "@types/i18n-js": "3.8.2",
    "@types/jest": "^29.2.1",
    "@types/react": "~18.2.14",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.59.0",
    "@typescript-eslint/parser": "^5.59.0",
    "babel-jest": "^29.2.1",
    "babel-loader": "8.2.5",
    "babel-plugin-root-import": "^6.6.0",
    "eslint": "8.17.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-config-standard": "17.0.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "6.0.0",
    "eslint-plugin-react": "7.30.0",
    "eslint-plugin-react-native": "4.0.0",
    "fbjs-scripts": "3.0.1",
    "jest": "^29.2.1",
    "jest-circus": "29",
    "jest-environment-node": "29",
    "jest-expo": "^49.0.0",
    "metro-config": "0.75.1",
    "metro-react-native-babel-preset": "0.75.1",
    "metro-source-map": "0.75.1",
    "mocha": "^10.2.0",
    "patch-package": "^6.4.7",
    "postinstall-prepare": "1.0.1",
    "prettier": "2.8.8",
    "query-string": "^7.0.1",
    "react-devtools-core": "4.24.7",
    "react-dom": "18.2.0",
    "react-native-web": "~0.19.6",
    "react-test-renderer": "18.2.0",
    "reactotron-core-client": "^2.8.10",
    "regenerator-runtime": "^0.13.4",
    "ts-jest": "29",
    "typescript": "^5.1.3"
  },
  "resolutions": {
    "@types/react": "^18",
    "@types/react-dom": "^18"
  },
  "engines": {
    "node": ">=18"
  },
  "prettier": {
    "printWidth": 100,
    "semi": false,
    "singleQuote": false,
    "trailingComma": "all"
  },
  "eslintConfig": {
    "root": true,
    "parser": "@typescript-eslint/parser",
    "extends": [
      "plugin:@typescript-eslint/recommended",
      "plugin:react/recommended",
      "plugin:react-native/all",
      "standard",
      "prettier"
    ],
    "plugins": [
      "@typescript-eslint",
      "react",
      "react-native"
    ],
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      },
      "project": "./tsconfig.json"
    },
    "settings": {
      "react": {
        "pragma": "React",
        "version": "detect"
      }
    },
    "globals": {
      "__DEV__": false,
      "jasmine": false,
      "beforeAll": false,
      "afterAll": false,
      "beforeEach": false,
      "afterEach": false,
      "test": false,
      "expect": false,
      "describe": false,
      "jest": false,
      "it": false
    },
    "rules": {
      "@typescript-eslint/ban-ts-ignore": 0,
      "@typescript-eslint/ban-ts-comment": 0,
      "@typescript-eslint/explicit-function-return-type": 0,
      "@typescript-eslint/explicit-member-accessibility": 0,
      "@typescript-eslint/explicit-module-boundary-types": 0,
      "@typescript-eslint/indent": 0,
      "@typescript-eslint/member-delimiter-style": 0,
      "@typescript-eslint/no-empty-interface": 0,
      "@typescript-eslint/no-explicit-any": 0,
      "@typescript-eslint/no-object-literal-type-assertion": 0,
      "@typescript-eslint/no-var-requires": 0,
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          "argsIgnorePattern": "^_",
          "varsIgnorePattern": "^_"
        }
      ],
      "comma-dangle": 0,
      "multiline-ternary": 0,
      "no-undef": 0,
      "no-unused-vars": 0,
      "no-use-before-define": 0,
      "no-global-assign": 0,
      "quotes": 0,
      "react-native/no-raw-text": 0,
      "react/no-unescaped-entities": 0,
      "react/prop-types": 0,
      "space-before-function-paren": 0
    }
  }
}

```
and app.json:
{
  "name": "test",
  "displayName": "test",
  "expo": {
    "name": "test",
    "slug": "test",
    "scheme": "test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/app-icon-all.png",
    "splash": {
      "image": "./assets/images/splash-logo-all.png",
      "resizeMode": "contain",
      "backgroundColor": "#FFFFFF"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "jsEngine": "hermes",
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "icon": "./assets/images/app-icon-android-legacy.png",
      "package": "com.g10developers.test",
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/app-icon-android-adaptive-foreground.png",
        "backgroundImage": "./assets/images/app-icon-android-adaptive-background.png"
      },
      "splash": {
        "image": "./assets/images/splash-logo-android-universal.png",
        "resizeMode": "contain",
        "backgroundColor": "#FFFFFF"
      },
      "permissions": [
        "android.permission.READ_CONTACTS",
        "android.permission.WRITE_CONTACTS",
        "android.permission.RECORD_AUDIO",
        "android.permission.CAMERA",
        "android.permission.MODIFY_AUDIO_SETTINGS",
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.ACCESS_MEDIA_LOCATION"
      ]
    },
    "ios": {
      "icon": "./assets/images/app-icon-ios.png",
      "supportsTablet": true,
      "bundleIdentifier": "com.g10developers.test",
      "splash": {
        "image": "./assets/images/splash-logo-ios-mobile.png",
        "tabletImage": "./assets/images/splash-logo-ios-tablet.png",
        "resizeMode": "contain",
        "backgroundColor": "#F9F9F9"
      },
      "infoPlist": {
        "UIBackgroundModes": [
          "audio"
        ],
        "NSContactsUsageDescription": "'test' would like to access your contacts.",
        "NSCameraUsageDescription": "'test' needs access to your Camera.",
        "NSMicrophoneUsageDescription": "'test' needs access to your Microphone.",
        "NSPhotoLibraryUsageDescription": "Allow test to access your photos.",
        "NSPhotoLibraryAddUsageDescription": "Allow test to save photos."
      }
    },
    "web": {
      "bundler": "metro",
      "favicon": "./assets/images/app-icon-web-favicon.png",
      "splash": {
        "image": "./assets/images/splash-logo-web.png",
        "resizeMode": "contain",
        "backgroundColor": "#F9F9F9"
      }
    },
    "plugins": [
      [
        "./plugins/withAndroidShareExtension/index",
        {
          "androidIntentFilters": ["text/*", "image/*"]
        }
      ],
      [
        "expo-config-plugin-ios-share-extension",
        {
          "activationRules": {
            "NSExtensionActivationSupportsText": true,
            "NSExtensionActivationSupportsWebURLWithMaxCount": 1,
            "NSExtensionActivationSupportsWebPageWithMaxCount": 1,
            "NSExtensionActivationSupportsImageWithMaxCount": 1,
            "NSExtensionActivationSupportsMovieWithMaxCount": 1
          }
        }
      ],
      "expo-localization",
      [
        "expo-contacts",
        {
          "contactsPermission": "'test' would like to access your contacts."
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "'test' would like access to your photos."
        }
      ],
      [
        "expo-media-library",
        {
          "photosPermission": "Allow test to access your photos and videos.",
          "savePhotosPermission": "Allow test to save photos.",
          "isAccessMediaLocationEnabled": true
        }
      ],
      [
        "react-native-vision-camera",
        {
          "cameraPermissionText": "test needs access to your Camera.",
          "enableMicrophonePermission": true,
          "microphonePermissionText": "test needs access to your Microphone."
        }
      ]
    ],
    "extra": {
      "eas": {
        "projectId": "1a4a1b79-cf78-4d52-9b24-c0cf7f04b735"
      }
    },
    "owner": "christophergabba"
  }
}

```

```

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - /opt/homebrew/bin/node
      npm: 10.1.0 - /opt/homebrew/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      expo: ^49.0.7 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.6.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo

```
import * as Contacts from "expo-contacts"

 const [contactPermission, setContactPermission] = useState(false)

 const { status } = await Contacts.requestPermissionsAsync()
    if (status === "granted") {
      setContactPermission(true)
      const { data } = await Contacts.getContactsAsync({
        fields: [
          Contacts.Fields.ID,
          Contacts.Fields.Name,
          Contacts.Fields.PhoneNumbers,
          Contacts.Fields.Image,
          Contacts.Fields.ImageAvailable,
        ],
      })

```

### Stacktrace (if a crash is involved)

N/A

**Comment by brentlecomte** [comment]
Running into the same issue, some devs still get the popup others do not. Did you find any way to solve this or is this still an issue?
