### ISSUE TITLE
Application not launching in Release Mode - Android Platform

### ISSUE THREAD

**Issue by ShaminiSaravanan** [expo/expo#25223]
### Minimal reproducible example

My current code is using Expo 45, but I recently upgraded it to Expo 46. When I upgraded Expo to version 46, the React Native version was also automatically updated. However, after these upgrades, my application could not be launched in release mode. This issue is specific to the Android platform, as the iOS platform continues to work as expected in both release and debug modes. Snack link: https://snack.expo.dev/@shaminisaravanan/expo-upgrade

### Summary

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">

</head>
<body>
<p class="p1">Please refer to the changes below before and after the Expo upgrade.<span class="Apple-converted-space"> </span></p>

<p class="p1">After these changes, the application now functions correctly in both release and debug modes on the iOS platform. However, concerning the Android platform, the application launches successfully in debug mode but <b>encounters issues in release mode</b>. Upon opening the application in release mode, the app crashes. Can anyone assist me in identifying what went wrong or suggest potential solutions to resolve this issue?</p>
<p class="p2"><br></p>

Before Upgrade | After Upgrade
-- | --
"expo": ">=44.0.0-0 <45.0.0", | "expo": "^46.0.0",
"expo-image-manipulator": "~10.2.0", | "expo-image-manipulator": "~11.0.0",
"expo-intent-launcher": "~10.1.3", | "expo-intent-launcher": "~10.3.0",
"expo-location": "~14.0.1", | "expo-location": "~15.0.1",
  | "expo-modules-core": "~1.0.4 \|\| ~1.1.1",
  | "expo-keep-awake": "12.0.1",
"expo-network": "4", | "expo-location": "~15.0.1",
"expo-task-manager": "~10.1.0", | "expo-task-manager": "~11.0.1",
"react": "18.0.0", | "react": "18.1.0",
"react-native": "0.68.0", | "react-native": "0.70.8",
"react-native-image-picker": "^4.7.3", | "react-native-image-picker": "7.0.1",
"react-native-reanimated": "2.7.0", | "react-native-reanimated": "~2.12.0",
"react-native-safe-area-context": "^4.2.1", | "react-native-safe-area-context": "4.4.1",
“react-native-screens": "^3.13.1", | "react-native-screens": "~3.18.0",
"react-native-svg": "^12.1.0", | "react-native-svg": "12.3.0",
"react-native-webview": "11.18.1", | "react-native-svg": "12.3.0",

</body>
</html>

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /opt/homebrew/bin/npm
      Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.21 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
    Expo Workflow: bare

**Comment by Kudo** [comment]
hi there! could you share the crash log from the android production build? you can refer the [doc](https://docs.expo.dev/debugging/runtime-issues/#production-app-is-crashing) if you want to learn more about getting crash log.

**Comment by ShaminiSaravanan** [comment]
The bug report for the Android emulator that crashed in Release Mode has been uploaded in the below link.

Link: https://drive.google.com/file/d/1NR-QPmQpZ5HpxGzo3wZtextc1gC3xVN_/view?usp=sharing

**Comment by Kudo** [comment]
this is the critical portion
```
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime: FATAL EXCEPTION: create_react_context
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime: Process: com.aptean.tms.pod, PID: 6379
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime: java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(Unknown Source:2)
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at com.facebook.react.bridge.JSBundleLoader$1.loadScript(Unknown Source:10)
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(Unknown Source:18)
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at com.facebook.react.q.u(Unknown Source:216)
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at com.facebook.react.q.d(Unknown Source:0)
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at com.facebook.react.q$e.run(Unknown Source:69)
11-07 14:36:21.564 10182  6379  6465 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:1012)
```

since you don't provide a repro project, we cannot further help to investigate the problem for you. one direction you could do is to clarify why `index.android.bundle` is not correctly bundled into apk.

**Comment by ShaminiSaravanan** [comment]
Thank you @Kudo 

When I execute the command:

`npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle`

and attempt to run the application in release mode, it automatically generates the index.android.bundle, and the application launches successfully.

My query now is, in my package.json file, I have the following script:

"scripts": { 
"build:android": "react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/" 
}

Since running npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle works for me in release mode, I'm wondering if I need to make any changes to my build:android script or how I can handle this without having to commit the index.android.bundle changes to my project repository.

**Comment by Kudo** [comment]
i see one difference between `--entry-file index.js` and `--entry-file index.android.js`. does that possibly matter?

**Comment by ShaminiSaravanan** [comment]
Even after replacing `--entry-file index.android.js` with `--entry-file index.js` in the package.json script, when I run the application in release mode, it is crashing. :(

It works only when I run `npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle`in terminal which automatically generates the index.android.bundle, and the application launches successfully.

I'm not sure of how to make this working without committing the index.android.bundle changes

**Comment by Kudo** [comment]
from sdk 45 (react-native 0.67) to sdk 46 (react-native 0.68), react-native replaced the original [react.gradle](https://github.com/facebook/react-native/blob/0.67-stable/react.gradle) to [react-native-gradle-plugin](https://github.com/facebook/react-native/tree/0.68-stable/packages/react-native-gradle-plugin). those are where react-native put `index.android.bundle` to apk. you may miss some changes when doing the upgrade.

to do upgrade easier, we introduced the [CNG (Continuous-Native-Generation)](https://docs.expo.dev/workflow/continuous-native-generation/). you may take a look when you get a chance. specifically, if you have git to diff local changes, you may try `npx expo prebuild -p android --clean` to regenerate the android folder for sdk 46 and diff the changes.

**Comment by Kudo** [comment]
i'm closing this because this is not really a bug, but i'll try to follow up the questions.

**Comment by ShaminiSaravanan** [comment]
I downloaded the APK file to compare two flows:
* OLD APK - Simply followed the scripts in package.json without executing anything in the terminal.

```
"scripts": {
"build:android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/"
  },
```

* NEW APK - Ran the command `npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle` and then launched the application.
Upon analysing the two APK files, I observed that the OLD app did not generate an index.android.bundle under assets. In contrast, in the second flow, the index.android.bundle was generated with a size of 6.4MB."

<img width="786" alt="Pasted Graphic 3" src="https://github.com/expo/expo/assets/147727739/34431a98-8fcf-4e10-bc43-2af46c0ff28d">

**Comment by Kudo** [comment]
so the old apk without index.android.bundle did not crash?

**Comment by ShaminiSaravanan** [comment]
The old apk is crashing. The new one is not crashing as I run the index generating command every time before I launch the application

**Comment by Kudo** [comment]
please let me clarify which is the old apk, the sdk 45 one?
