### ISSUE TITLE
[expo-server-sdk-node] Property 'message' does not exist on type 'ExpoPushReceipt'.

### ISSUE THREAD

**Issue by thorwebdev** [expo/expo#25225]
### Summary

Property 'message' does not exist on type 'ExpoPushReceipt'.

Seem to be a type issue:

```ts
export declare type ExpoPushReceipt = ExpoPushSuccessReceipt | ExpoPushErrorReceipt;

export declare type ExpoPushSuccessReceipt = {
    status: 'ok';
    details?: object;
    __debug?: any;
};
export declare type ExpoPushErrorReceipt = {
    status: 'error';
    message: string;
    details?: {
        error?: 'DeviceNotRegistered' | 'InvalidCredentials' | 'MessageTooBig' | 'MessageRateExceeded';
    };
    __debug?: any;
};
```

<img width="765" alt="image" src="https://github.com/expo/expo/assets/5748289/68a9c7cc-875c-4942-8d7e-6d92da1bf989">

### Link to the related docs page

https://github.com/expo/expo-server-sdk-node

**Comment by byCedric** [comment]
Try [narrowing down the type](https://medium.com/@littlejohn.sophia/3-ways-to-narrow-object-types-with-typescript-27c34d35e75a) from the union `ExpoPushReceipt` type, e.g.

```
const receipt = receipts[receiptId]

// narrowing down by discriminated union
if (receipt.status === 'error') {
  console.log(receipt.message);
}

// narrowing down by using the "in" operator
if ('message' in receipt) {
  console.log(receipt.message);
}
```

**Comment by thorwebdev** [comment]
Hm, I don't think that's an ideal DX. E.g. in supabase-js we do this: https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L85-L99

So rather than the `message` prop not existing on `ExpoPushReceipt` you could specify it as `null`. Wdyt?
