### ISSUE TITLE
renderRouter not working on tabs@49 template app

### ISSUE THREAD

**Issue by iambharath87** [expo/expo#25237]
### Minimal reproducible example

https://github.com/iambharath87/expo-router-examples/pull/1

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I created a sample expo app with this:
```bash
npx create-expo-app@latest --template tabs@49
```

Added a sample unit test that tests the expo-router navigation according to the docs [here](https://docs.expo.dev/router/reference/testing/), but the test fails (see screenshot).

![image](https://github.com/expo/expo/assets/6663930/784f6fe0-1330-4a23-9448-362b1f7f10c9)

Please let me know if there is something i'm missing.

Thanks.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - ~/Library/Caches/fnm_multishells/73380_1699115870493/bin/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 9.7.2 - ~/Library/Caches/fnm_multishells/73380_1699115870493/bin/npm
      Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 31, 33, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
        System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Fixed by https://github.com/expo/expo/pull/25110. Should be released soon

**Comment by iambharath87** [comment]
Awesome, the tests are working now. Thank you!
