### ISSUE TITLE
OTA Bundle Updates Reversion on Android

### ISSUE THREAD

**Issue by bonham000** [expo/expo#2526]
I first published on the Expo forum [here](https://forums.expo.io/t/issues-with-ota-updates/15235) and was recommended to file an issue here.

Our assumption with OTA updates is they will match any installed app of the same SDK and release channel, so there are no other changes we need to make, necessarily, for a new OTA version (e.g. bumping `app.json` version or anything like that). If there is something we missed in our workflow, happy to learn and modify it.

**The Issue:**

Currently we have a staging build of an app running with Expo SDK 30. We publish updates automatically in a CI pipeline using `expo publish --release-channel staging`. Our `app.json` uses the default configuration for handling updates. This has been working great, however two of our testers found an issue earlier this week. This only occurred on installed Android apks (not on iOS as far as we can tell, but we not testing as thoroughly on iOS right now).

* App bundle A running on device
* Update is published (update B)
* Apps download and load update B, update B running on device
* Sometime later, apps reload an update (no update has been published), and now are running Update A again
* Cannot fetch Update B anymore
* Fixed by publishing another update (C, for instance). Now apps reload with updates A, B, and C.

The main issue is seeming unexpected reversion to a prior OTA update version after publishing a new version. I'm not 100% that an "update" occurred to cause the reversion, but the reversion definitely happened. We are pushing a lot of updates and I've only seen this reversion this one time recently.

One other relevant piece of information (maybe) is that we are trying to handle OTA updates manually in the app by allowing the user to opt in. Previously I was using `Expo.Updates.fetchUpdateAsync` and `Expo.Updates.reload` to manually reload an update in the app. After reading the documentation more carefully, I'm changing this to just `Expo.Updates.reload`. So this OTA reversion happened when we were calling the `fetchUpdateAsync` method and then reloading.

***

By the way, thanks to all the Expo teams for these amazing tools. They're very fun to work with. 👍

**Comment by brentvatne** [comment]
@esamelson - I suspect this is on the Android client side but added @quinlanj in case it's on the release channels backend of things

**Comment by esamelson** [comment]
Hi @bonham000 - thanks very much for the report. We'll look into this on our end, but afaik we have not seen this, so it would be really helpful if you have any idea if there's something that triggers Update A to load again. E.g. does it always happen after the JS experiences a fatal (or non-fatal) error? Does it happen on every device, or just some? If you can figure out any pattern that seems to reliably cause the app to revert to Update A, that would be super helpful. Thanks!!

**Comment by bonham000** [comment]
@esamelson no errors, this just happened again for us, this time it was consistent between iOS and Android. The apps had a more recent update, and then there was a new publish, and the apps updated but were on an older version (from the last few days). I'm trying to make an update to include the build id in the app so we can tell exactly which build is running at any point to investigate more closely.

**Comment by bonham000** [comment]
Actually, trying to this now - is there a way to access the `publicationId` in the app for that release? Or some id which can identify that release based on the Expo publish history?

**Comment by bonham000** [comment]
Very embarrassing to say I've discovered the issue here... Someone else on our team was independently building the app without informing us, and not always pulling the latest code... So new OTA updates were being published with older versions of the code. Very sorry!

**Comment by esamelson** [comment]
@bonham000 thanks very much for letting us know, glad you were able to figure it out!
