### ISSUE TITLE
Android Screen Goes Black on First Camera Access Due to Expo Vector Usage

### ISSUE THREAD

**Issue by ch-Arham** [expo/expo#25262]
### Minimal reproducible example

https://github.com/ch-Arham/expo-camera-issue-repro

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

# Expo Camera Issue

Following is a summary of the issue in Expo Camera and Expo Vector

## Issue Description

On Android, Expo Camera shows black screen for the first time user navigates to the camera screen but navigating back to it again solves the issue. Everything works fine on IOS.

## Expected Behavior

 - When user navigates to camera screen, Camera permission should be asked for the first time and then Camera should be opened.
 - Even if the user closes the app and open again (this time the permission was already allowed) navigating to Camera Screen should open the camera.

## Current Behavior

 - On Android, the screen goes black for the first time and navigating back to it again solves the issue.
 - On IOS it works fine.

## Versions

- Expo Camera version: 13.6.0
- Expo version: ~49.0.13
- Expo Router: ^2.0.0

## Additional Information

**Reason:** Apparently using expo vector inside the Camera tags causes this issue on Android. It works fine for IOS but on Android this needs to be fixed.

**Note:** Using `TouchableOpacity` and `View` solves the issue for Android but the UI is not consistent across IOS and Android then.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
      Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by EvanBacon** [comment]
Closing in favor of https://github.com/expo/expo/issues/25308
