### ISSUE TITLE
(expo-media-library) 

### ISSUE THREAD

**Issue by xinbocoding** [expo/expo#25263]
### Minimal reproducible example

MediaLibrary.deleteAlbumsAsync([id], false).then((res) => {           saveNotes(notes).then((res) => {             console.log(res, "delete album and update the storage");           });         });

### Summary

expo "~49.0.13",
"expo-media-library": "~15.4.1"
run on the IOS simulator.

I want to use MediaLibrary.deleteAlbumsAsync([id], false) to delete a album without deleting the photos. On iOS it doesn't delete these assets, but when I pass false of assetsRemove, it still has been asked to delete photos belonging this album.

Here is the photos when I delete the album. If I don't allow the delete this photo, there is "Unhandled Promise Rejection" so I cannot delete album.

![Screenshot 2023-11-07 at 9 33 32 PM](https://github.com/expo/expo/assets/16946691/5e021e3a-289a-4a66-bf1e-78fb639e18d5)
![Screenshot 2023-11-07 at 9 37 27 PM](https://github.com/expo/expo/assets/16946691/a4b7ad97-a708-4ccd-84ad-cf1d25aee791)

### Environment

System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/xinbo/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10

**Comment by alanjhughes** [comment]
Hi - can you provide a minimal reproducible example please?

**Comment by xinbocoding** [comment]
This is my project's repo: https://github.com/xinbocoding/photo-notes

**Comment by xinbocoding** [comment]
> Hi - can you provide a minimal reproducible example please?

Please run my project: https://github.com/xinbocoding/photo-notes in the app/(tabs)/home/notesList.
