### ISSUE TITLE
[Android] Video preview disappear after locking and unlocking phone

### ISSUE THREAD

**Issue by riwu** [expo/expo#2527]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.12.0
  Yarn: 1.9.4
  npm: Not Found
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/riwu-1db10347-a137-4ebb-9f0d-a76aaf240a41.tar.gz

Tested on Android v8.0.0 (Samsung S8+)

### Steps to Reproduce

1. Set device screen lock to "None" in settings.
2. Open snack

https://snack.expo.io/@riwu/expo-video-disappear
```
import React from 'react';
import { Video } from 'expo';

const App = () => (
  <Video
    source={{ uri: 'http://techslides.com/demos/sample-videos/small.mp4' }}
    style={{ width: 200, height: 200 }}
  />
);

export default App;
```
3. Lock phone
4. Unlock phone

### Expected Behavior

Video preview should remain visible.

### Actual Behavior

Video preview image is hidden (white screen).

**Comment by brentvatne** [comment]
I was unable to reproduce this on an old Nexus 5x running Android 8.0.0. cc @sjchmiela

**Comment by riwu** [comment]
On my S8+, the bug only occurs if screen lock type is "None". On other screen lock types, the screen seems to get some sort of reload which does not cause the disappearance.

On my other older Android device, the bug does not occur on lock and unlock. Instead, it occurs when I press home button then re-open the app.

**Comment by IjzerenHein** [comment]
I can confirm that this still happens. But only when pressing the lock button and quickly pressing again to unlock. It then appears to not perform the unlock animation and the video is not rendered.
