### ISSUE TITLE
npx expo install --fix not working correctly

### ISSUE THREAD

**Issue by zikyfranky** [expo/expo#25286]
### Summary

I recently wanted to upgrade my expo sdk from 47 to 48, after changing the expo version in package.json, I ran `npx expo install --fix` which is supposed to fix the dependencies, but it doesn't work, apparently, it tries running `yarn|npm install dependency1@v.1.1,dependency2@v.1.1`

Basically, each of the dependencies is separated by a comma, which isn't a valid yarn|npm install command.

### SDK Version

48.0.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.21 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.9 => 0.18.10 
    Expo Workflow: managed

### Minimal reproducible example

Just running `npx expo install --fix` throws the error.

![Screenshot 2023-11-09 at 1 56 55 AM](https://github.com/expo/expo/assets/36174178/5719e237-1047-431b-81a9-bc93b28fa6d2)

**Comment by brentvatne** [comment]
hey there! sorry we missed this. i imagine this is not happening anymore, but i suspect what may have occurred here is that you ran this command shortly after we published a new version of the `@expo/webpack-config` package, and it wasn't yet showing up on npm for you
