### ISSUE TITLE
Problems loading brand-new expo app (stuck at splash screen)

### ISSUE THREAD

**Issue by Tycholiz** [expo/expo#2529]
Having problems getting any Expo project to load. I have noted that this issue is specific to my phone, as everything works normally on other devices. I have tried to uninstall and reinstall Expo but no luck.

The problem started yesterday, and to my knowledge, I haven't done anything _that is general enough to have affected all projects_.
From the terminal, I run expo start. This gives me the normal: 

> [10:56:48] Starting project at /home/personal/programming/fullStack/dogsAreAwesome
> [10:56:48] Expo DevTools is running at http://localhost:19002
> [10:56:48] Opening DevTools in the browser... (press shift-d to disable)
> [10:56:54] Starting Metro Bundler on port 19001.
> [10:56:54] Metro Bundler ready.
> [10:56:54] Successfully ran `adb reverse`. Localhost URLs should work on the connected Android device.
> [10:56:56] Tunnel ready.

along with the QR code. This is followed by the browser opening. 
This is how it has always worked, and how it is working now.

However, when I go to Expo app on my Android LG phone, I scan the QR code, and my phone goes to generic splash screen of Expo (the dotted-line square), and it stays there. In the past of course, it quickly loaded to the app.

I have tried to create brand new projects, but the problems persists. I have tried to load old projects that were working as of 3 days ago, but the problem persists. 

I have checked all of the consoles for issues, but none show up. 
I have upgraded Expo, Expo CLI, react-native etc. everything that has to do with the project, but the issue persists. 

I would very much welcome any insight, as I have been at this hours with no ideas where to look for a solution.

### Environment
Running on Android with Expo

xpo CLI 2.2.4 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      expo: ^30.0.1 => 30.0.1 
      react: 16.3.1 => 16.3.1 
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4 
      react-navigation: ^2.16.0 => 2.16.0 
    npmGlobalPackages:
      expo-cli: 2.2.4

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/tycholiz-e25193a5-8ed4-4ed4-ad14-c0fda0c28e19.tar.gz

**Comment by BoktorDevelopment** [comment]
I have the same problem, turning off the firewall doesn't make sense

**Comment by Tycholiz** [comment]
update: my app randomly started loading again today. I have no idea why, as it was nothing I did purposely.

**Comment by sjchmiela** [comment]
I'm glad your app started to work, I think this issue was just a flaky connection hiccup and isn't a real bug in Expo. Feel free to reopen this issue if you encounter the problem again! 🙂
