### ISSUE TITLE
After "npx expo install --fix" I receive "ApiV2Error: Entity Not Authorized."

### ISSUE THREAD

**Issue by sidespin-admin** [expo/expo#25298]
### Summary

root ➜ /workspaces/copyview (gluestack) $ npx expo start --tunnel --no-dev
Starting project at /workspaces/copyview
Starting Metro Bundler
Tunnel connected.
Tunnel ready.

<QR CODE WAS HERE>

› Metro waiting on exp://6z22jbq.sidespin.19000.exp.direct
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
ApiV2Error: Entity Not Authorized.
ApiV2Error: Entity Not Authorized.

### What platform(s) does this occur on?

iOS

### SDK Version

 "expo": "~48.0.21",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.4 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: 18.1.0 => 18.1.0 
      expo: ~48.0.21 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

### Minimal reproducible example

{
  "name": "ui-expo-bake-off",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.2.3",
    "@expo/html-elements": "latest",
    "@expo/ngrok": "^4.1.0",
    "@expo/webpack-config": "18.1.0",
    "@gluestack-style/react": "^1.0.5",
    "@gluestack-ui/themed": "^1.0.13",
    "@legendapp/motion": "latest",
    "expo": "~48.0.21",
    "expo-app-loading": "^2.1.1",
    "expo-font": "~11.1.1",
    "expo-image": "~1.0.2",
    "expo-linear-gradient": "~12.1.2",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-system-ui": "~2.2.1",
    "expo-updates": "~0.16.4",
    "firebase": "^10.5.2",
    "install": "^0.13.0",
    "lucide-react-native": "^0.161.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.14",
    "react-native-svg": "13.4.0"
  },
  "devDependencies": {
    "firebase-tools": "^12.8.1",
    "@babel/core": "^7.20.0",
    "@babel/plugin-transform-modules-commonjs": "^7.21.5",
    "@babel/preset-env": "^7.22.4",
    "@babel/preset-react": "^7.22.3",
    "@gluestack-style/babel-plugin-styled-resolver": "^0.2.6",
    "@types/react": "~18.0.27",
    "@types/react-native": "^0.72.2",
    "babel-loader": "^9.1.2",
    "postcss-loader": "^7.3.2",
    "react-native-web": "~0.18.11",
    "typescript": "^4.9.4"
  },
  "private": true
}

**Comment by nmiz1987** [comment]
Try ''eas logout'' and then ''eas login'' again. Worked for me.
