### ISSUE TITLE
Expo app local iOS build constantly hangs at : [RUN_FASTLANE] › Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest

### ISSUE THREAD

**Issue by sanjuhs** [expo/expo#25290]
### Summary

Expo app build constantly hangs at : [RUN_FASTLANE] › Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest
So i am a new dev , but whenever i try to locally build the expo project for iOS , its get stuck on this error : [RUN_FASTLANE] › Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest

I was just trying to add the google-firebase login , which then required me to have a development build which then forced me to run this build as per the tutorial given on the website, it works properly on the Expo Cloud servers , so why is it that , its failing locally .

Can someone please clarify what i need for the ios build that is available in the cloud but not locally ?
P.S i tried to build android locally and it worked , but the ios one keeps hanging at the same line.

Can someone please help me resolve it , theres no error it just hangs and my M1 laptop goes into an infinite loop i think as the cpu keeps heating up ( even after 2x ctrl +C out of the process ) without stopping after which I have to shut down the laptop.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

├── @babel/core@7.23.2
├── @react-native-async-storage/async-storage@1.18.2
├── @react-native-google-signin/google-signin@10.1.0
├── expo-dev-client@2.4.11
├── expo-splash-screen@0.20.5
├── expo-status-bar@1.6.0
├── expo@49.0.16
├── firebase@10.5.2
├── react-native@0.72.6
└── react@18.2.0

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
      Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 34.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.6.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo

Just an empty app with a text field in app.js with npx install of expo-dev-client , firebase, google-signin and building for ios : simulator build as shown in the video tutorial on site : https://docs.expo.dev/develop/development-builds/create-a-build/  , but the build for ios is done Locally.

**Comment by qzw881130** [comment]
i ran into the same issue.
https://github.com/react-native-tvos/react-native-tvos/issues/768

no just build TV, other ios app, it was also as the same issue.

**Comment by qzw881130** [comment]
> ### Summary
> Expo app build constantly hangs at : [RUN_FASTLANE] › Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest So i am a new dev , but whenever i try to locally build the expo project for iOS , its get stuck on this error : [RUN_FASTLANE] › Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest
> 
> I was just trying to add the google-firebase login , which then required me to have a development build which then forced me to run this build as per the tutorial given on the website, it works properly on the Expo Cloud servers , so why is it that , its failing locally .
> 
> Can someone please clarify what i need for the ios build that is available in the cloud but not locally ? P.S i tried to build android locally and it worked , but the ios one keeps hanging at the same line.
> 
> Can someone please help me resolve it , theres no error it just hangs and my M1 laptop goes into an infinite loop i think as the cpu keeps heating up ( even after 2x ctrl +C out of the process ) without stopping after which I have to shut down the laptop.
> 
> ### Managed or bare workflow?
> managed
> 
> ### What platform(s) does this occur on?
> iOS
> 
> ### Package versions
> ├── @babel/core@7.23.2 ├── @react-native-async-storage/async-storage@1.18.2 ├── @react-native-google-signin/google-signin@10.1.0 ├── expo-dev-client@2.4.11 ├── expo-splash-screen@0.20.5 ├── expo-status-bar@1.6.0 ├── expo@49.0.16 ├── firebase@10.5.2 ├── react-native@0.72.6 └── react@18.2.0
> 
> ### Environment
> expo-env-info 1.0.5 environment info: System: OS: macOS 13.1 Shell: 5.8.1 - /bin/zsh Binaries: Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node Yarn: 1.22.19 - /opt/homebrew/bin/yarn npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman Managers: CocoaPods: 1.14.2 - /opt/homebrew/bin/pod SDKs: iOS SDK: Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4 Android SDK: API Levels: 31, 33, 34 Build Tools: 30.0.3, 31.0.0, 33.0.0, 34.0.0 System Images: android-31 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a IDEs: Android Studio: 2022.3 AI-223.8836.35.2231.10811636 Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild npmPackages: expo: ~49.0.15 => 49.0.16 react: 18.2.0 => 18.2.0 react-native: 0.72.6 => 0.72.6 npmGlobalPackages: eas-cli: 5.6.0 expo-cli: 6.3.10 Expo Workflow: managed
> 
> ### Reproducible demo
> Just an empty app with a text field in app.js with npx install of expo-dev-client , firebase, google-signin and building for ios : simulator build as shown in the video tutorial on site : https://docs.expo.dev/develop/development-builds/create-a-build/ , but the build for ios is done Locally.
> 
> ### Stacktrace (if a crash is involved)
> _No response_

hi, did you solve it?

**Comment by qzw881130** [comment]
i solved it.

pls read this.
[https://github.com/expo/expo/issues/15809](https://github.com/expo/expo/issues/15809)

it was caused by .bash_profile
i don't know why.
i just did so.


```
mv ~/.bash_profile ~/.bash_profile.bak
touch ~/.bash_profile
chmod a+x ~/.bash_profile
```
then, npm run ios.

it works.
![image](https://github.com/user-attachments/assets/bcfc493b-2b6a-46b5-b8eb-1d800cbb0e66)

**Comment by qzw881130** [comment]
another way.

search "bash " and "/bin/sh " in `./ios`
then, replace 
`bash ` => `bash --noprofile`
and
`/bin/sh` => `/bin/bash --noprofile`

so, executing shell won't load `~/.bash_profile`

![s1](https://github.com/user-attachments/assets/62066985-51ab-4cd2-bb1a-9f8002b8f13e)
