### ISSUE TITLE
Bun doesn't work without npm installed

### ISSUE THREAD

**Issue by angel-luis** [expo/expo#25300]
### Summary

The bun command from docs (https://docs.expo.dev/guides/using-bun/) is not working.

It throws an error:
```
✖ Something went wrong in downloading and extracting the project files: spawn npm ENOENT
Error: spawn npm ENOENT
```

### Environment

MacOS 14.0 and Bun 1.0.11

### Minimal reproducible example

`bun create expo my-app`

### Notes
I don't have *Node* or *npm* installed, as it's not necessary with *bun*. I know *Node* is a requirement as docs states, but it has no sense to use *bun* but behind the scenes use *npm*.

**Comment by sonodima** [comment]
I was able to fix this issue by installing Node alongside to Bun.

Unfortunately using Expo with Bun alone is not supported for the time being, because some processes are spawned by the CLI using Node.
