### ISSUE TITLE
tabBarIcon handler is called twice when changing the tab one time

### ISSUE THREAD

**Issue by phillihoch** [expo/expo#25319]
### Minimal reproducible example

https://github.com/phillihoch/expo-router-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have installed a basic expo router project with `npx create-expo-app@latest --template tabs@49`.

By default the template has tabs and in the tabs options there is a handler for the tabBarIcon. The props that handler provides are `focused`, `color` and `size`.

And here comes the error:
If i change the tab, the handler for the tabBarIcon is executed twice immediately after another. The first time the data (focused: true) is right. The second time focused changes to false apparently. The Tab remains active but the data from the tabBarIcon handler is kind of wrong and in my opinion should only be executed once.

### Environment

System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.2.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.0.8
    Expo Workflow: managed

**Comment by marklawlor** [comment]
This is a React Navigation quirk. It calles the `tabBarIcon` twice and caches the result. 

https://github.com/react-navigation/react-navigation/blob/858a8746a5c007a623206c920f70d55935ed39b4/packages/react-native-tab-view/src/TabBarItem.tsx#L151-L160
