### ISSUE TITLE
No way to override context in segment

### ISSUE THREAD

**Issue by n-sviridenko** [expo/expo#2531]
Hello,
In order to be compliant with GDPR, we want to anonymise ip of users using our app. To do this, we need to override `context.ip` property the following way: https://segment.com/docs/sources/website/analytics.js/#anonymizing-ip . The issue is that we are unable to do this neither using js-level (no API for this), nor expokit (context is private there).
How to do this?
And, as I'm already here, do you know the best way of getting user's ip address using expokit (without performing an http call)?
Best,
Nikita

**Comment by brentvatne** [comment]
cc @esamelson

**Comment by esamelson** [comment]
Hi @n-sviridenko - thanks for the feedback. We are really interested in making sure Expo is GDPR compliant and will work on exposing the ability to anonymize ip with Segment as soon as we can get to it.

Re: getting the device's ip address, if you're already on expokit then the quickest way would probably be to just write a small native module and get the IP address using the native methods for doing so. I don't believe Expo already exposes this to JS anywhere. Feel free to also upvote this feature request on canny: https://expo.canny.io/feature-requests/p/network-info---ip-ssid-onlineoffline

**Comment by n-sviridenko** [comment]
@esamelson already upvoted :) I assume M34 is planned to be completed in early December?

**Comment by fortydegrees** [comment]
Hi, has there been an update to this? How do you pass context to segment? I want to pass my user's device ID to send push notifications. I can grab the token, but can't put it in the 'context' field for Segment to properly read.

**Comment by fortydegrees** [comment]
I also tried this using segment's official react native package (after ejecting expo) and had the same problem. After going back and forth with segment they said it was a problem on their end and they are looking to fix it

**Comment by cruzach** [comment]
Hi! I just added this behavior, and it will be included in the next SDK release (39). You can check the [changelog](https://github.com/expo/expo/blob/master/packages/expo-analytics-segment/CHANGELOG.md#unpublished) for details
