### ISSUE TITLE
[docs] Broken link on home page

### ISSUE THREAD

**Issue by bnzone** [expo/expo#25332]
### Summary

The `Navigation` link leads to https://docs.expo.dev/guides/routing-and-navigation/ which gives 404 not found.

Screenshot for reference
<img width="400" alt="screenshot of a homepage part" src="https://github.com/expo/expo/assets/39371503/14e9808a-5823-4bed-a097-82d1c31a6507">

### Link to the related docs page

https://expo.dev/

**Comment by amandeepmittal** [comment]
Thanks for catching this @bnzone! We'll fix it!
