### ISSUE TITLE
Splash image with ` resizeMode='contain' ` not working in Android standalone version

### ISSUE THREAD

**Issue by ksairi** [expo/expo#2533]
### Environment

Environment:
  OS: Linux 4.15
  Node: 9.5.0
  Yarn: 1.10.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: 30.0.0 => 30.0.0
  react: 16.5.2 => 16.5.2
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/ksairi-67494bd4-3ef5-4251-8bbc-d11e091ad670.tar.gz

The app is targeted to iOS and Android

### Steps to Reproduce

(Write your steps here:)

1. Build for Android: exp build:android
2. Open it in an android device
3.

### Expected Behavior

The expected behavior is the the same as <Image> tag behavior with property resizeMode='contain'.
The image should be scaled up or down depending screen's dimension.

### Actual Behavior

This is related to issues #1670 and #1037 but both are closed.
This is the important part of my app.json
``"splash": {
			"image": "./assets/splash.png",
			"backgroundColor": "#000000"
		}``
.....

``"android": {
"splash": {
				"backgroundColor": "#000000",
				"resizeMode": "contain",
				"mdpi": "./assets/splash_a_X1.png",
				"hdpi": "./assets/splash_a_X1_5.png",
				"xhdpi": "./assets/splash_a_X2.png",
				"xxhdpi": "./assets/splash_a_X3.png",
				"xxxhdpi": "./assets/splash_a_X4.png"
			}
		}``

When running on the expo client or as a standalone iOS app the resizeMode": "contain" takes places but not in the android standalone app; where the splash image is not scaled up or down, it will be rendered as it is. I assume that they added the properties (mdpi, hdpi, etc) to address this issue.
My question is, should be this issue fixed in expo building process, so resources are automatically scaled up or down according to the provided splash image (like is working in iOS building process)
Otherwise we will do as it is mentioned in this [comment](https://github.com/expo/expo/issues/1037#issuecomment-398868279). We need to test with different images sizes until we reach the one fills our requirement which requires much build and .apk installation time for the sake of an image size. And all that time could be saved if only resizeMode": "contain" will work for splash images in android standalone apps.

**Comment by ksairi** [comment]
@bbarthec  any thoughts about this?

**Comment by bbarthec** [comment]
@ksairi I'll take a look at this matter and I expect to provide fix before next sdk release 👍

**Comment by ibnukipa** [comment]
is it already release on SDK 32? I'm currently using SDK 32 but still not work.

**Comment by bbarthec** [comment]
@ibnukipa please see this issue: https://github.com/expo/expo/issues/3611.

**Comment by ibnukipa** [comment]
> @ibnukipa please see this issue: #3611.

okay, thanks. great! can't wait for it
