### ISSUE TITLE
Development build with native module causes failures / app won't run

### ISSUE THREAD

**Issue by ImperviousPanda** [expo/expo#25346]
### Summary

In trying to add a native module using [this tutorial](https://docs.expo.dev/modules/native-view-tutorial/), I cannot get a development build to run successfully without erroring and freezing.  I have attempted to do this with my app but also with a newly created app using `npx create-expo-app`.

In both cases the development build works and runs fine before I add the new native View to the app.  After that in the debugger I see these errors:

```
Invariant Violation: Failed to call into JavaScript module method RCTLog.logIfNoNativeHook(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: Failed to call into JavaScript module method RCTLog.logIfNoNativeHook(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: Failed to call into JavaScript module method HMRClient.setup(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[{"app_state":"active"}]', js engine: hermes
Invariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

If you have a github repository that has a native view successfully added that runs in a development build can you please share it?  Maybe I can find a difference.  

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "expo-dev-client": "~2.4.12",
    "expo-splash-screen": "~0.20.5"

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.11.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.18
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: bare

### Reproducible demo

1. `npx create-expo-app --template` - create a blank typescript app
2. Create a native view `npx create-expo-module expo-web-view`, follow instructions in the [tutorial](https://docs.expo.dev/modules/native-view-tutorial/) to reduce the newly created files to bare templates
3. Add the new native view to App.tsx:
```
export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <WebView />
      <StatusBar style="auto" />
    </View>
  );
}
```
4. Create a index.js file with 
```
import { registerRootComponent } from 'expo';

import App from './App';
registerRootComponent(App);
```
5. Create a development build for the simulator following [this tutorial](https://docs.expo.dev/develop/development-builds/create-a-build/#create-a-build-for-emulatorsimulator)
6. Wait for your build to finish, start your server with `npx expo start --dev-client`
7. Open in IOS simulator 
8. App hangs on first screen, many errors are in the debugger console

### Stacktrace (if a crash is involved)

Invariant Violation: Failed to call into JavaScript module method RCTLog.logIfNoNativeHook(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: Failed to call into JavaScript module method RCTLog.logIfNoNativeHook(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: Failed to call into JavaScript module method HMRClient.setup(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[{"app_state":"active"}]', js engine: hermes
Invariant Violation: Failed to call into JavaScript module method RCTDeviceEventEmitter.emit(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 0): .
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Invariant Violation: No callback found with cbID 21 and callID 10 for module <unknown>. Args: '[15575]', js engine: hermes
Invariant Violation: No callback found with cbID 23 and callID 11 for module <unknown>. Args: '[15576]', js engine: hermes
Invariant Violation: No callback found with cbID 25 and callID 12 for module <unknown>. Args: '[15577]', js engine: hermes
Invariant Violation: No callback found with cbID 27 and callID 13 for module <unknown>. Args: '[15578]', js engine: hermes
Invariant Violation: No callback found with cbID 29 and callID 14 for module <unknown>. Args: '[15579]', js engine: hermes

**Comment by ImperviousPanda** [comment]
What is wrong with my issue?  I provided steps to reproduce that are accessible to anyone.

**Comment by TeChn4K** [comment]
Exact same issue on my side
Have you find anything?

**Comment by WarrenBuffering** [comment]
Same issue here, did you end up figuring this out @ImperviousPanda?

**Comment by hyochan** [comment]
Having the same problem recently in SDK50. Really hard to figure this out.

**Comment by hyochan** [comment]
I hope we could see any error logs that are useful to tackle.

**Comment by aram-wealthmore** [comment]
@hyochan I also started getting this error in SDK50, any luck?

**Comment by ChamaraWP** [comment]
@hyochan @ImperviousPanda having the same problem after upgrading to SDK50. Did you guys find any solutions?

**Comment by jingwood** [comment]
Same problem using SDK50, hope something help...

**Comment by ChamaraWP** [comment]
> I'm having a similar problem after upgrading from 49 to 50.
> 
> With Hermes turned on, the last warning on XCode points to a failed attempt to call `RCTLog.logIfNoNativeHook()` and them I see a JS error on `setImmediate` not being available (which clearly should be).
> 
> [full log output](https://gist.github.com/oidoug/cd266dc10f152d7b0c9cc980cb7883b7)
> 
> If I use JSC the warning and error on `RCTLog.logIfNoNativeHook` still show up but the message is this one:
> 
> ```
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> E0430 14:09:35.454864 1817260032 NativeToJsBridge.cpp:186] Attempting to call JS function on a bad application bundle: RCTLog.logIfNoNativeHook()
> Assertion failed: (objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object"), function ~JSCRuntime, file JSCRuntime.cpp, line 390.
> ```
> 
> And no JS error pops up.
> 
> ## additional info
> [package.json](https://gist.github.com/oidoug/2e7a09a9f948f8785d415678bd35c17d)
> 
> [yarn.lock](https://gist.github.com/oidoug/bc4f2f7c02c29a7fc7c2b290ab9219be)
> 
> I've been struggling with this for a couple of days already and would love some pointers from the Expo team.

The most likely culprit is an incorrect path to your app's main JavaScript file (index.js or similar).

**Comment by oidoug** [comment]
Thanks for the pointer @ChamaraWP. It wasn't the entry point, but your comment put me on the correct path again.

My problem was Sentry, I just needed to follow the new integration steps for Expo-50:
https://docs.expo.dev/guides/using-sentry/

I was using the `@sentry/react-native` package in Expo 49 already, so it didn't occur to me that I had to redo it 🤦‍♂️

**Comment by JordanVegas** [comment]
i have the same issue
