### ISSUE TITLE
[expo-image-picker] Photo and Video Permissions policy

### ISSUE THREAD

**Issue by nitrique** [expo/expo#25361]
### Minimal reproducible example

none

### Summary

Hi,

We recently got the following warning from Google:

```
For a more privacy preserving experience for users, we’re introducing the Photo and Video Permissions policy to reduce the number of apps permitted to request broad photo/video permissions (READ_MEDIA_IMAGES and READ_MEDIA_VIDEO). Apps may only access photos and videos for purposes directly related to app functionality. Apps that have a one-time or infrequent need to access these files are requested to use a system picker, such as the Android photo picker.

You’ll have at least 30 days from the date of this notification to comply with the following policy changes
```

We recently implemented these changes in AndroidManifest as suggested by Android Studio for API Level :

```
    <uses-permission
            android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission
            android:name="android.permission.READ_EXTERNAL_STORAGE"
            android:maxSdkVersion="32"/>
    <uses-permission
            android:name="android.permission.WRITE_EXTERNAL_STORAGE"
            android:maxSdkVersion="32"
            tools:ignore="ScopedStorage"/>
```

How can we comply with Google's policies and use system image picker ?
Maybe I mislooked the documentation but I didn't find anything about this requirement.

Best regards,
Nicolas

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 9.1.3 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2023.11.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by lucasmendesdeliver** [comment]
@nitrique This is the solution to remove these permissions, on app.config.js, inside the android object, add blockedPermissions array, with all permissions u dont want
android: {

    blockedPermissions: ['android.permission.READ_MEDIA_IMAGES', 'android.permission.READ_MEDIA_VIDEO'],
  },

**Comment by omivrex** [comment]
> @nitrique This is the solution to remove these permissions, on app.config.js, inside the android object, add blockedPermissions array, with all permissions u dont want android: {
> 
> ```
> blockedPermissions: ['android.permission.READ_MEDIA_IMAGES', 'android.permission.READ_MEDIA_VIDEO'],
> ```
> 
> },

thanks this worked for me

**Comment by sidorchukandrew** [comment]
I could be wrong, but it seems like the image picker shouldn't be requesting these permissions anymore. The Android photo picker does not require permissions. Maybe these two permissions should be removed from the manifest?

**Comment by ShivamJoker** [comment]
Had the same issue with Google Play, not sure why it's adding unnecessary permissions :/

**Comment by fabiendem** [comment]
I think those permissions are added when this `AndroidManifest.xml` gets merged in our main Manifest: https://github.com/expo/expo/blob/6723972fd995b0180a34244c448632b041038dc7/packages/expo-image-picker/android/src/main/AndroidManifest.xml#L9-L10

**Comment by thespacemanatee** [comment]
While the Expo team is working on this, we can remove them ourselves by declaring this in our own `AndroidManifest.xml` cc @brentvatne 

```xml
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" tools:node="remove" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" tools:node="remove" />
```

**Comment by markymc** [comment]
@brentvatne this seems to be closed, but does it not still need attention? I'm seeing this issue on the latest version (`15.0.7`).

**Comment by YahyaBagia** [comment]
@markymc True. I faced the same issue.

**Comment by stuckj** [comment]
If you block the permissions won't the image picker then be useless since it won't be able to actually access images (except, perhaps, images the app itself took)?

**Comment by thespacemanatee** [comment]
> If you block the permissions won't the image picker then be useless since it won't be able to actually access images (except, perhaps, images the app itself took)?

Not if you are using the built-in [Android Photo Picker](https://developer.android.com/training/data-storage/shared/photopicker). The built-in photo picker can access all photos and videos on the device and stored on Google Photos, without the app needing to access them, which is why the app itself does not need those permissions anymore.

**Comment by MonsieurBuffle** [comment]
+1
@markymc 
I'm facing the same issue.

**Comment by Charles-Johnson** [comment]
> @nitrique This is the solution to remove these permissions, on app.config.js, inside the android object, add blockedPermissions array, with all permissions u dont want android: {
> 
> ```
> blockedPermissions: ['android.permission.READ_MEDIA_IMAGES', 'android.permission.READ_MEDIA_VIDEO'],
> ```
> 
> },

I tried this but I'm still get this warning in the Google Play console.

![스크린샷 2024-11-11 20-51-33](https://github.com/user-attachments/assets/bfad962d-dda5-46c3-a4bf-d117133a184a)

**Comment by asithishantha** [comment]
> > @nitrique This is the solution to remove these permissions, on app.config.js, inside the android object, add blockedPermissions array, with all permissions u dont want android: {
> > ```
> > blockedPermissions: ['android.permission.READ_MEDIA_IMAGES', 'android.permission.READ_MEDIA_VIDEO'],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > },
> 
> I tried this but I'm still get this warning in the Google Play console.
> 
> ![스크린샷 2024-11-11 20-51-33](https://private-user-images.githubusercontent.com/20388960/384909865-bfad962d-dda5-46c3-a4bf-d117133a184a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTU3OTEsIm5iZiI6MTczMjU5NTQ5MSwicGF0aCI6Ii8yMDM4ODk2MC8zODQ5MDk4NjUtYmZhZDk2MmQtZGRhNS00NmMzLWE0YmYtZDExNzEzM2ExODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA0MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NzQyNjAzNmNjMjc2YjFmMzNmYWJkYjkzMTc2M2MyY2IyYmUxNzViNTIwYjI5NjQxOTNjNWQxY2RkYTUzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RWlhi_EKGlSeJNbPGBgLCV-tpSutJrqbi613p8NQCXA)
> 
> UPDATE: If a click "Go to declaration" I have the option to see which versions of the app actually have the permission set (View app bundles and APKs) and it turns out that it was the version that is currently live, not the version I'm about to submit.
> 
> ![스크린샷 2024-11-12 10-56-02](https://private-user-images.githubusercontent.com/20388960/385110704-bd65c774-d585-472e-9496-f6d37ded6418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTU3OTEsIm5iZiI6MTczMjU5NTQ5MSwicGF0aCI6Ii8yMDM4ODk2MC8zODUxMTA3MDQtYmQ2NWM3NzQtZDU4NS00NzJlLTk0OTYtZjZkMzdkZWQ2NDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA0MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjczYWExZWNhNTIxZTFlZGU0ZDk2MjVkYmFlMmNmMGEzOGU5MTY2MTRmMjg3ZWIxODU4ZGM1Y2QyYzMwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p_4xv2i0Y3xFYyBl76V-fmlU1pdKDDBP59v5ivip-qw)

did you able to fix this ?

**Comment by MonsieurBuffle** [comment]
@asithishantha As long as you have a version (in alpha, beta, test or in production), Google keeps warning you that there is a problem with one of your version of the app.
What @Charles-Johnson explained is that the warning actually concerned his older live version, and not the new one with the ** blockedPermissions**  attribute in app.json.
So the ** blockedPermissions** solution actually works :)

**Comment by Charles-Johnson** [comment]
@asithishantha I can confirm that the blockedPermissions solution did work

**Comment by y-k-m** [comment]
I think, this fixed on 16.0.0.

https://github.com/fobos531/expo/blob/main/packages/expo-image-picker/CHANGELOG.md#1600--2024-10-22

**Comment by appsgenie** [comment]
I just upgraded to SDK 51 (managed workflow) and the warning is still there for the newly uploaded version 🤔 
@y-k-m is that fix on 16.0.0 going for SDK 52 ? because once I upgrade to SDK 51 and it bumped me to `"expo-image-picker": "~15.0.7"` still

**Comment by nabilfreeman** [comment]
v16 is Expo 52+ only. It changes the deployment target to iOS 15.

As of the 22nd January the Google Play Store is rejecting any application that has `expo-image-picker <= v15`. This includes a lot of Expo 51 apps.

The only solution is to either manually patch v15, or fill out a declaration justifying why media access is needed (which is of course not true for anybody using this library, which uses the system picker).

@aleqsio could we please get this fixed on v15 as well? I feel that it's quite a serious problem for people who are unable to upgrade to Expo 52 yet.

Here is the patch file, implementing this commit https://github.com/expo/expo/pull/31902/files

# expo-image-picker+15.0.7.patch
```patch
diff --git a/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml b/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml
index 9ea2a9d..198e685 100644
--- a/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml
+++ b/node_modules/expo-image-picker/android/src/main/AndroidManifest.xml
@@ -6,8 +6,6 @@
   <!-- Required for picking images from camera roll -->
   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
-  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
-  <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
 
   <application>
     <service
diff --git a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
index 5b7e4d9..66e730f 100644
--- a/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
+++ b/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt
@@ -1,8 +1,6 @@
 package expo.modules.imagepicker
 
 import android.Manifest
-import android.Manifest.permission.READ_MEDIA_IMAGES
-import android.Manifest.permission.READ_MEDIA_VIDEO
 import android.content.Context
 import android.content.Intent
 import android.content.pm.PackageManager
@@ -253,10 +251,7 @@ class ImagePickerModule : Module() {
 
   private fun getMediaLibraryPermissions(writeOnly: Boolean): Array<String> =
     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
-      listOfNotNull(
-        READ_MEDIA_IMAGES,
-        READ_MEDIA_VIDEO
-      ).toTypedArray()
+      emptyArray<String>()
     } else {
       listOfNotNull(
         Manifest.permission.WRITE_EXTERNAL_STORAGE,
```

**Comment by bvangrimberge** [comment]
Having the same issue and unable to upgrade to expo 52. Would really appreciate if the above fix was implemented for V15. Will use the patch above for now.

**Comment by nabilfreeman** [comment]
Guys they did it! `expo-image-picker@15.1.0` is out!!!

Thanks! 🙏🙏🙏🙏🙏🙏

**Comment by appsgenie** [comment]
@nabilfreeman, great news! so we can stay with SDK 51 and replace my `"expo-image-picker": "~15.0.7",` with this `expo-image-picker@15.1.0` without the tilde? Do we need to change any configuration or how permissions are being requested?

I am also unable to upgrade to SDK 52 yet.

But fwiw, I was still able to submit a new version while on sdk51 with `"expo-image-picker": "~15.0.7",` six days ago but still with a warning in the play console

**Comment by appsgenie** [comment]
I tried the blockedPermissions solution with SDK 51 and `"expo-image-picker": "~15.0.7"` and during beta testing it seems that on some devices/android versions you do not get the library permission prompt from the OS.. is this expected? and what is the official solution with SDK 51 to by pass this warning from google?

I tried the blockedPermissions solution with SDK 51 and `"expo-image-picker": "~15.0.7"`  but it does not always work. on newer Android versions or devices, you can't even grant access to library anymore.. the `requestMediaLibraryPermissionsAsync` method does not show the OS prompt for permissions and when going into the app's settings screen you also can't give access since it was never asked the first time..
