### ISSUE TITLE
Expo Publish encounters issues due to inconsistencies with Hermes.

### ISSUE THREAD

**Issue by lemanrs** [expo/expo#25365]
### Summary

Experiencing issues with Expo Publish as it throws an error about JavaScript engine configuration inconsistency related to Hermes. Despite having hermesEnabled set in both app.json and Android native project files (gradle.properties and app/build.gradle), the error persists, claiming a mismatch between app.json and the native Android project. 

This is code in the files:

// app.json
"jsEngine": "hermes"

// gradle.properties
hermesEnabled=true

// app/build.gradle
if (hermesEnabled.toBoolean()) {
    implementation("com.facebook.react:hermes-android")
}

Despite these settings, the error states, "In app.json: Hermes is enabled. In Android native project: Hermes is not enabled." The function where error happens is at Object.maybeThrowFromInconsistentEngineAsync (/opt/hostedtoolcache/expo-cli/4.13.0/x64/node_modules/@expo/dev-server/src/HermesBundler.ts:112:11), which cheks hermesEnabled in gradle.properties https://github.com/expo/expo/blob/9c4d2992ebd9548b7b43883a9965f95ee78d836c/packages/%40expo/cli/src/export/exportHermes.ts#L190. My gradle proprties has hermesEnabled=true, I don't know what else to add?

### SDK Version

49

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.20.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ^49.0.0 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.5 => 0.72.5
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: bare

### Minimal reproducible example

run command expo publish

**Comment by Kudo** [comment]
hi there! the `expo publish` would [be deprecated soon](https://blog.expo.dev/sunsetting-expo-publish-and-classic-updates-6cb9cd295378). would you consider to migrate to EAS Update? we had a relevant issue but only resolved in EAS Update only #23184.
