### ISSUE TITLE
expo-modules-core build failed on android

### ISSUE THREAD

**Issue by FouadMagdy01** [expo/expo#25378]
### Minimal reproducible example

create new react-native cli app and try to install expo-modules-core and build the app

### Summary

android BUILD failed oin android.
i got this error
```
* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > Failed to notify project evaluation listener.
      > org.gradle.process.internal.ExecException: Process 'command 'path'' finished with non-zero exit value 1
      > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
```

and it's not gradle version error, i tried several gradle versions and still the same

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^49.0.18 => 49.0.18
      react: 18.2.0 => 18.2.0
      react-native: 0.72.7 => 0.72.7
    Expo Workflow: bare

**Comment by FouadMagdy01** [comment]
SOLVED

The problem was that android sdk directory was wrong
Rechanged it and everything worked correctly

**Comment by DeluxeOwl** [comment]
@FouadMagdy01 Wrong in what sense? I'm having the same problem

**Comment by FouadMagdy01** [comment]
> @FouadMagdy01 Wrong in what sense? I'm having the same problem


Can you give me the full error you get from android studio build tools?

**Comment by DeluxeOwl** [comment]
```txt
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Script '/tmp/bogdan/eas-build-local-nodejs/f43f7cd8-4471-4c5f-9b71-a5d24add9466/build/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 356
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating project ':expo'.
[RUN_GRADLEW] > A problem occurred configuring project ':expo-modules-core'.
[RUN_GRADLEW]    > Failed to notify project evaluation listener.
[RUN_GRADLEW]       > Process 'command '/home/bogdan/.local/bin/cmake'' finished with non-zero exit value 1
[RUN_GRADLEW]       > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred configuring project ':expo'.
[RUN_GRADLEW] > compileSdkVersion is not specified. Please add it to build.gradle
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 6m 19s
[RUN_GRADLEW] 10 actionable tasks: 10 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by FouadMagdy01** [comment]
> ```
> [RUN_GRADLEW] FAILURE: Build completed with 2 failures.
> [RUN_GRADLEW] 1: Task failed with an exception.
> [RUN_GRADLEW] -----------
> [RUN_GRADLEW] * Where:
> [RUN_GRADLEW] Script '/tmp/bogdan/eas-build-local-nodejs/f43f7cd8-4471-4c5f-9b71-a5d24add9466/build/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 356
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] A problem occurred evaluating project ':expo'.
> [RUN_GRADLEW] > A problem occurred configuring project ':expo-modules-core'.
> [RUN_GRADLEW]    > Failed to notify project evaluation listener.
> [RUN_GRADLEW]       > Process 'command '/home/bogdan/.local/bin/cmake'' finished with non-zero exit value 1
> [RUN_GRADLEW]       > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
> [RUN_GRADLEW] * Try:
> [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> [RUN_GRADLEW] > Run with --scan to get full insights.
> [RUN_GRADLEW] ==============================================================================
> [RUN_GRADLEW] 2: Task failed with an exception.
> [RUN_GRADLEW] -----------
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] A problem occurred configuring project ':expo'.
> [RUN_GRADLEW] > compileSdkVersion is not specified. Please add it to build.gradle
> [RUN_GRADLEW] * Try:
> [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> [RUN_GRADLEW] > Run with --scan to get full insights.
> [RUN_GRADLEW] ==============================================================================
> [RUN_GRADLEW] * Get more help at https://help.gradle.org
> [RUN_GRADLEW] BUILD FAILED in 6m 19s
> [RUN_GRADLEW] 10 actionable tasks: 10 executed
> [RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> 
> Build failed
> Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> npx exited with non-zero code: 1
>     Error: build command failed.
>  ELIFECYCLE  Command failed with exit code 1.
> ```


Try to delete the folder in this path in this section 
```
> Process 'command '/home/bogdan/.local/bin/cmake'' finished with non-zero exit value 1
```

And then rebuild the project from android studio

Also take a backup for this folder in case it didn't work

**Comment by DeluxeOwl** [comment]
Thanks! Turns out that was the problem, for some reason that cmake in `.local/bin` was a python script and I had `.local/bin` at the start of my `$PATH`

**Comment by FouadMagdy01** [comment]
> Thanks! Turns out that was the problem, for some reason that cmake in `.local/bin` was a python script and I had `.local/bin` at the start of my `$PATH`


Yes that was the exact issue i have
It was pointing to a python script that's why it was failing
Wish you a Happy code 🎉😄

**Comment by firattekinn** [comment]
**I get similar error but deleting cmake directory did not work for me**

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'C:\apps\apnea-mobile\node_modules\expo-modules-autolinking\scripts\android\autolinking_implementation.gradle' line: 356

* What went wrong:
A problem occurred evaluating project ':expo'.
      > No enum constant org.jetbrains.kotlin.gradle.plugin.PropertiesProvider.JvmTargetValidationMode.WARN�NG
      > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Comment by AliSinaYOusofi** [comment]
add local.properties file in your root android folder and add your sdk path: sdk.dir=C:\\Users\\YourUsername\\AppData\\Local\\Android\\Sdk

**Comment by gkasireddy202** [comment]
Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':expo-modules-core'.

Getting above error in react-native:0.73.2

**Comment by DnEgorWeb** [comment]
@gkasireddy202 did you figure how to fix it?

**Comment by gkasireddy202** [comment]
> @gkasireddy202 did you figure how to fix it?

@DnEgorWeb  - I closed the Android studio and sync again. The error has gone.

**Comment by bnv1223** [comment]
Hello @gkasireddy202 ,
I am still facing the issue. Please help

**Comment by AliSinaYOusofi** [comment]
> Hello @gkasireddy202 , I am still facing the issue. Please help
check if your android SDK path is correct.

**Comment by AyushSinghbharti** [comment]
I'm trying to compile app using EAS, with some error the prebuild is failed dozen of times. I tried to resolve all errors but still getting error as:

Error 1:
* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-crypto'.
   > Failed to notify project evaluation listener.
      > compileSdkVersion is not specified. Please add it to build.gradle
      > Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
* Try:
> Run with --stacktrace option to get the stack trace.

Error 2:
Task failed with an exception.
-----------
* Where:
Script '/home/expo/workingdir/build/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 85
* What went wrong:
A problem occurred configuring project ':expo'.
>
Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.


Could you please help me fix this issue!!!

**Comment by gkasireddy202** [comment]
@AliSinaYOusofi  - I closed the Android studio and synced the project again. The error has gone.
