### ISSUE TITLE
C++ Exception   thunk for closure

### ISSUE THREAD

**Issue by itsramiel** [expo/expo#25379]
### Minimal reproducible example

Not Applicable

### Summary

The issue happens in production and is captured by sentry. The error is: 
```C++ Exception thunk for closure

Ongoing
Level: Fatal
Unhandled
St13runtime_error
```
Here is the callstack(seems to be coming from expo-location):
<img width="864" alt="image" src="https://github.com/expo/expo/assets/80689446/24ae608e-188e-4a6b-b097-8f8760677d6c">

I know there isnt a reproducible example because I personally dont know how to reproduce it, but I thought to bring it to expo's attention and hopefully with the callstack it is possible to debug

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.10.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/ramiel/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.1.1 => 18.1.2
      expo: ^49.0.6 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed
    ```

**Comment by Kudo** [comment]
hi there! does your sentry report more stacktrace from the crash? would be good to know more calling paths under the `St13runtime_error`.

**Comment by fritzZz** [comment]
I have the same problem since Expo 48. not reproducible also in my case!

**Comment by itsramiel** [comment]
unfortunately that is all @Kudo

**Comment by Kudo** [comment]
would be good to see the details in the "Hide N more frames". or if you could share the raw crash log, it will be even better.

**Comment by itsramiel** [comment]
What do you mean by details in the "Hide N more frame"? The frames are already expanded. Do you know how to download the raw crash log in sentry? I cant seem to find something online. Not sure if possible

**Comment by ShmuelPickRanky** [comment]
Also facing same issue
Does anyone find anything about it?

**Comment by melvynhills** [comment]
Facing the same issue, surprised not more people are mentioning this. We're having thousands of occurrences for this one.

<img width="986" alt="Screenshot 2024-01-29 at 09 57 32" src="https://github.com/expo/expo/assets/417315/be025bf6-7475-4e33-9250-40ab46eb7233">

**Comment by aklevko** [comment]
The same problem. Expo 48.0.20, expo-location 15.1.1

**Comment by fritzZz** [comment]
Since november no answers to this issue but I still have a lot of crashes in production.
![expo-error-c++](https://github.com/expo/expo/assets/159523/8cbc6316-302d-4b6b-a5cd-a16c338abd0a)

**Comment by devpate9** [comment]
@itsramiel found any solution for this?

**Comment by SupriyaPKalghatgi** [comment]
Found same issue on production

**Comment by gvanderclay** [comment]
Our team is also facing this issue. 

I noticed that the issue only occurs when I try to select multiple ProRAW images from my image gallery. If I select multiple images with regular (i.e. jpg, or png) types or one ProRAW image, I don't get a crash.

**Comment by wodin** [comment]
@Kudo, here is someone who says they have a reproduction recipe:
https://discord.com/channels/695411232856997968/1232007477520764959/1232007477520764959

**Comment by antidiestro** [comment]
This is still a problem.

**Comment by fritzZz** [comment]
Is still the main issue I can detect on my Production application. Is someone working on this issue?

**Comment by yoann84** [comment]
Same here, a lot of crashs

**Comment by geikobogdan** [comment]
Same, a lot of crash, rn version 0.73.6, expo version 50.0.11
