### ISSUE TITLE
Metro assetPlugin URL query not working in SDK31+

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2539]
Something isn't right with Asset caching - if you load the image over the network in development it works fine. If you try to cache it with Asset.loadAsync then it does not.

**Comment by ide** [comment]
Temporarily fixed here: https://github.com/expo/expo/commit/68a46cba25408d356d2eeb119ba2bbe9d00c61fd

Longer term, we need these fixes:

- Add back the URL parameter to Metro or have RN's CLI take `assetPlugins` as a parameter that gets merged with `transformer.assetPlugins` (if specified) from rn-cli.config.js. @brentvatne can you take care of this?
- If we pass assetPlugins in as a CLI argument: have Expo CLI send the `assetPlugins` query parameter only if the project SDK version is 30.0.0 or below.

**Comment by brentvatne** [comment]
> Add back the URL parameter to Metro or have RN's CLI take assetPlugins as a parameter that gets merged with transformer.assetPlugins (if specified) from rn-cli.config.js. @brentvatne can you take care of this?

Can do sometime in late November yeah, will keep this assigned to me

**Comment by brentvatne** [comment]
we pass this in as a flag to the cli start command now https://github.com/expo/expo-cli/blob/19c7b501b88d5b26abf6b71d67a6e1db22bbd1b5/packages/xdl/src/Project.ts#L1726-L1728
