### ISSUE TITLE
CommandError: No development build for this project is installed. Please make and install a development build on the device first.

### ISSUE THREAD

**Issue by mrsants** [expo/expo#25396]
### Summary

CommandError: No development build (br.projjetoprestacaoservico.pandaparkingmobile) for this project is installed. Please make and install a development build on the device first.

### What platform(s) does this occur on?

iOS

### SDK Version

48.0.18

### Environment

mac

### Minimal reproducible example

mac

**Comment by DumplingDefender** [comment]
same here

**Comment by brandontle** [comment]
Make sure your `eas.json` is configured correctly:

```
{
  "build": {
    "development-simulator": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    }
  }
}

```

Then build the development build: `eas build --profile development-simulator --platform ios`

Then run `yarn dev`

See docs: https://docs.expo.dev/develop/development-builds/create-a-build/
