### ISSUE TITLE
rn-link should work better with CocoaPods

### ISSUE THREAD

**Issue by leo108** [expo/expo#254]
I want to add third-party native modules, according to [expokit guide](https://docs.expo.io/versions/v17.0.0/guides/expokit.html#ios) is that means I have to manually edit every native dependency's building settings? and those changes will no be tracked by git?

**Comment by terribleben** [comment]
Are you reporting a bug or asking a question?

If you're installing native deps with some other method besides CocoaPods, you'll need to accommodate CocoaPods one way or another. git will track changes to your build configuration unless you tell it not to.

**Comment by leo108** [comment]
@terribleben as the doc said

>  If you encounter build issues locating the <React/*> headers, you may need to manually add Pods/Headers/Public to the Header Search Paths configuration for your native dependency in Xcode.

I have to add Pods Path to the native dependency's `Header Search Paths` in `building settings` which stored in `{project_root}/node_modules/{third_party}/ios/{ext_name}.xcodeproj`, as we all know that file changes in the `node_modules` directory will not be tracked by git.

**Comment by cpenarrieta** [comment]
After detaching my expo app I'm getting this error too. 
```
/Users/cpenarrieta/Downloads/flofun-app-eject/node_modules/@expo/vector-icons/vendor/react-native-vector-icons/RNVectorIconsManager/RNVectorIconsManager.h:10:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^
1 error generated.


** BUILD FAILED **
```
I already ran `react-native link` and `pod install` under the ios folder.

**Comment by mohammed1955** [comment]
@terribleben  i deatch my app and install pod file,after detaching and install pod file i got error :
<img width="602" alt="screen shot 1396-04-02 at 13 59 27" src="https://user-images.githubusercontent.com/15388226/27475975-3f7c0546-581c-11e7-8d54-b7037c592633.png">
and my pod file look like this 

> **:source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'githubnote' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/1.16.2",
    :subspecs => [
      "Core",
      "CPP"
    ]

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport"
    ]
  pod 'Yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
**
what happens ??

**Comment by terribleben** [comment]
@leo108 good point about how the dependency cannot be tracked. We have somebody working on improving `react-native link` to understand more about the CocoaPods structure currently. In the meantime you may just have to reconfigure your native dependency whenever you override `node_modules`.

Renaming the issue and leaving open so we can track that.

**Comment by chenkaiC4** [comment]
my way is that:

1. react-native link package   (for android)
2. git checkout ios/*   (important! remove change of ios, because we will set it by pod)
3. vim ios/Podfile, add pop config, like

```
pod 'react-native-orientation',
      :path => "../node_modules/react-native-orientation"
```
4. pod install

works fine!

**Comment by leo108** [comment]
@chenkaiC4 Thanks! it works for me.

**Comment by dikaiosune** [comment]
Looks like https://github.com/facebook/react-native/pull/15460 will be merged soon, which should resolve this problem. Closing for now, but if that PR doesn't land we can look at other ways to handle this.
