### ISSUE TITLE
[expo-camera] Wrong image orientation on Samsung devices

### ISSUE THREAD

**Issue by robsonbbs** [expo/expo#25401]
### Minimal reproducible example

https://snack.expo.dev/@team-btime/aa8cc9

### Summary

I am considering migrating my app's camera lib from vision camera to expo-camera since vision camera doesn't handle image orientation by itself. Unfortunately, that feature seems to not work on the expo camera either, at least on 2 Samsung devices that I've tested (Galaxy M12 and Galaxy J8). I don't know how expo-camera handles orientation under the hood, but I know that a possible approach would be to use Gyroscope sensor, which both of these devices don't have.

Could you guys please check this behavior?

Thanks for all the efforts put into the expo, it's an amazing and very useful tool!

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
      Watchman: 2023.08.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/btime/.rvm/gems/ruby-2.6.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.21 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by Zoxive** [comment]
Im in a similar place, ive been playing expo-camera, and vision camera on android with not much success.

Your snack example (as is) does work on my pixel 8 pro.

However as soon as i enable `exif` via `takePictureAsync({ exif: true })` its breaks. 

(Its incorrectly rotated 90 degrees)
