### ISSUE TITLE
Add support for FacebookUrlSchemeSuffix in facebook login

### ISSUE THREAD

**Issue by zhiyi7** [expo/expo#2542]
### Environment

iOS

### Steps to Reproduce

When too or more apps share one facebook app id,  the facebook SDK uses the urlschemesuffix to determine which app should be returned. The facebookScheme should match fb+appid+suffix.

### Expected Behavior

Can set "facebookScheme" to `^fb[0-9]+[a-z0-9]*$`

### Actual Behavior

Only `^fb[0-9]+$` supported.

Edit: Maybe the unified solution is add a `schemes` key under the `ios` section in `app.json`. So that can be replaced into CFBundleURLSchemes within build stage.

**Comment by btang28** [comment]
can I ask if there's any follow up for this? or a workaround?

**Comment by esamelson** [comment]
Hi there, sorry that this slipped through the cracks for so long. I've updated the regex validation so it accepts an alpha-character suffix. Going to close this as the issue should now be resolved.
