### ISSUE TITLE
Extra console logs in app.config break autolinking in `pod install`

### ISSUE THREAD

**Issue by navignaw** [expo/expo#25455]
### Summary

Including an additional `console.log('hello')` or `console.debug('hello')` inside your `app.config.[tj]s` file breaks the autolinking step in `pod install` with the following error:

```
[!] Invalid `Podfile` file: Couldn't parse JSON coming from `expo-modules-autolinking` command:
unexpected token at 'hello
{"extraDependencies":{"androidMavenRepos":[],"iosPods":{}},"modules":[{"packageName":"expo","packageVersion":"49.0.7","pods":[{"podName":"Expo","podspecDir":"REPO_PATH/node_modules/expo"}],... // additional lines truncated
```

It seems like the autolinking code just tries to grab everything in stdout and parse that into JSON. I'm not entirely sure how the code works, but it seems like it would be cleaner to import the JS file and just take the exported object.

You can see existing error reports of this in the forums: https://forums.expo.dev/t/eas-build-failing-with-expo-router-v2-and-expo-sdk-49/72962/2

Debugging this issue would be slightly mitigated by improved tooling to support verbose mode, which I have suggested in https://github.com/expo/expo/issues/26102

### What platform(s) does this occur on?

iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2023.10.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: bare
```

### Minimal reproducible example

Construct an `app.config.ts` file with the following:

```ts
console.log('hello')
export default ({ config }) => config
```

Now run `pod install` (or `npx pod-install`) and see it fail with the exception printed above.

**Comment by wodin** [comment]
Here's another instance of this happening: https://discord.com/channels/695411232856997968/1174269809601556480/1174317082020696124

**Comment by andres-dos-santos** [comment]
In my case I had installed `react-native-email-link` but I removed it because it didn't solve my problem, but I forgot to remove the plugin in `app.json` and that caused this error, so if you are using this library.

- Remove `react-native-email-link` from plugins in `app.json` folder.
- Run the command `yarn install` and `cd ios && pod install --repo-update`
