### ISSUE TITLE
duplicate code in permissions

### ISSUE THREAD

**Issue by aniltirola** [expo/expo#2546]
https://github.com/expo/expo/blob/68a46cba25408d356d2eeb119ba2bbe9d00c61fd/packages/expo-permissions/Permissions.js#L53-L61

it seems that there is duplicate code in `Permissions.js`

**Comment by sjchmiela** [comment]
Hey! 🙂 

I don't know which parts of the code do you consider a duplicate, but if you look closely lines 55 and 59 differ, the first one passes `Permissions.getAsync` as the second argument and the second one passes `Permissions.askAsync`.

These methods also differ in behavior — `askAsync` will block and ask the user for the given permission, `getAsync` will always execute “quietly”.

[`Permissions.getAsync`](https://docs.expo.io/versions/v30.0.0/sdk/permissions#expopermissionsgetasyncpermissiontypes) vs [`Permissions.askAsync`](https://docs.expo.io/versions/v30.0.0/sdk/permissions#expopermissionsaskasynctypes)

**Comment by aniltirola** [comment]
ooo sorry ... I regret ... I watched too fast and thought too less
:no_mouth: :no_mouth: :no_mouth:
