### ISSUE TITLE
getBrightnessAsync not resolving on Android

### ISSUE THREAD

**Issue by jamesthomp** [expo/expo#25472]
### Minimal reproducible example

https://snack.expo.dev/16-pfBFPB

### Summary

Following this change https://github.com/expo/expo/pull/20316 (cc: @alanjhughes) I've noticed that on Android when you run the `Brightness.getBrightnessAsync()` method in a `setInterval`, confusingly the promise doesn't resolve by its-self.

I have a minimal repro on snack at https://snack.expo.dev/16-pfBFPB -- If you open this on iOS, the counter nicely increments, yet on Android it doesn't.

One fix seems to be removing `.runOnQueue(.main)` from `getBrightnessAsync`, which works on my Android device without any issues. So potentially that could be an easy fix, although presumably there is some reason why this method is running on the main queue? Anyway, I wanted to file this issue because it seems quite weird, and I'm worried that maybe something more fundamental is broken here. 

### Environment

Not relevant given Android repro on Snack: https://snack.expo.dev/16-pfBFPB

**Comment by lukmccall** [comment]
Fixed by https://github.com/expo/expo/pull/25757.
