### ISSUE TITLE
renderRouter breaks typescript compilation

### ISSUE THREAD

**Issue by NiklasEi** [expo/expo#25478]
### Minimal reproducible example

https://github.com/NiklasEi/test-expo-router

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When using renderRouter the typescript compiler complains about around 60 issues inside node_modules/expo-router/src/ that do not show up when not importing renderRouter.

You can reproduce this by running npm i followed by tsc in the reproduction project. When removing app.integration.spec.ts the compile errors no longer show up.

Excluding the test directory in the `tsconfig.json` is a workaround, but not a solution, since I want to typecheck my test files.

This is a revival of #24480 which was closed with a partial workaround removing the test files from the typescript project.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    SDKs:
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.3, 34.0.0
        System Images: android-27 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: 49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.8.0
    Expo Workflow: managed

**Comment by marklawlor** [comment]
@NiklasEi Version 3 is available for preview https://www.npmjs.com/package/expo-router/v/3.2.0 if you'd like to upgrade. We don't have documentation just yet, but the breaking API changes are minimal. If you have any issues with the preview, I can help you with the upgrade.

**Comment by hichemfantar** [comment]
I wrote a script that avoids expo router type errors.
https://github.com/expo/expo/issues/24933#issuecomment-1816428488

**Comment by hichemfantar** [comment]
> @NiklasEi Version 3 is available for preview https://www.npmjs.com/package/expo-router/v/3.2.0 if you'd like to upgrade. We don't have documentation just yet, but the breaking API changes are minimal. If you have any issues with the preview, I can help you with the upgrade.

is v3 compatible with sdk 48 and 49 or is sdk 50 required?

**Comment by marklawlor** [comment]
This should be fixed in v3, as we no longer ship uncompiled TS.

v3 is part of SDK 50
