### ISSUE TITLE
Slow Camera preview on low values of 'pictureSize' option

### ISSUE THREAD

**Issue by pm4r** [expo/expo#2549]
### Environment

Environment:
  OS: Linux 3.16
  Node: 10.8.0
  Yarn: 1.6.0
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Target: Android 

### Expected Behavior

Preview speed of Camera should not be affected by value of `pictureSize` property.

### Actual Behavior

When `pictureSize` on Camera component is set to low value, like "1280x720", preview slows down significantly. It is especially in case of lower light conditions (like pointing camera on the floor, but still in daylight).

Enabling torch mode fixes that for close images. Ratio doesn't matter here.
Lower preview speed also causes auto-focus to slow down which affects time of taking pictures.

Tested on:
- LG G6, Android 8.0.0 - preview speed becomes very slow and blurry for lowest values of `pictureSize` (like 1280x720 and 1920x1080)
- Samsung Galaxy Note II, Android 4.4.2 - preview speed is not affected by `pictureSize` values
- iPhone SE - preview speed slows down when `pictureSize` is set `Low`, for other values I don't see much slow down

### Reproducible Demo

1. Open https://snack.expo.io/@pmar/camera-preview-picturesize (based on camerja )
2. Change "Picture quality" to low value and observe if preview speed drops down

### Use case

My use case is to send images to remote server to do some computer vision task. The process is in the loop of: take picture, send to server for recognition, wait for result and if nothing is found repeat. So to make things faster I take and send images with low resolution. Taking picture takes currently most part of the process.

For me, ideally would by to just grab frame from preview, without taking picture. Is that somehow possible?

**Comment by CarMoreno** [comment]
Is there some update about this issue, guys?
