### ISSUE TITLE
renderRouter() import failing due to dependency requirements

### ISSUE THREAD

**Issue by mersiades** [expo/expo#25494]
### Minimal reproducible example

https://github.com/mersiades/router-mre

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Unable to import `renderRouter()` because it requires other dependencies.

Steps to reproduce:
1. Create new expo app using `npx create-expo-app [app name] --template`, choosing the Navigation (Typescript) template.
2. Create a test file and copy the example test from[ this documentation ](https://docs.expo.dev/router/reference/testing/#inline-file-system) into it.
3. Run the test.

I get this error when I run it:

```
  Test suite failed to run

    Cannot find module 'react-native-reanimated' from 'node_modules/expo-router/src/testing-library/mocks.ts'

    Require stack:
      node_modules/expo-router/src/testing-library/mocks.ts
      node_modules/expo-router/src/testing-library/index.tsx
      node_modules/expo-router/testing-library.ts
      mre.test.tsx

      1 | import React from "react";
      2 | import {View} from "react-native";
    > 3 | import { renderRouter, screen } from 'expo-router/testing-library';
        | ^
      4 |
      5 | it('my-test', async () => {
      6 |   const MockComponent = jest.fn(() => <View />);

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (node_modules/expo-router/src/testing-library/mocks.ts:4:44)
      at Object.require (node_modules/expo-router/src/testing-library/index.tsx:18:1)
      at Object.require (node_modules/expo-router/testing-library.ts:1:1)
      at Object.require (mre.test.tsx:3:1)
```

If I install the missing dependency, the next test runs fails because it's missing the next dependency.

PS. The documentation linked to above refers to an `initialRoute` key, but it's meant to be `initialUrl`. 

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
    npmPackages:
      expo: ~49.0.15 => 49.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: managed

**Comment by mersiades** [comment]
Hey, @marklawlor . Thanks so much for fixing this. Your fix looks like it will do the job for `react-native-reanimated`. 

But I think you'll find that there's still going to be a similar problem with `@testing-library/jest-native/extend-expect`:

```
Cannot find module '@testing-library/jest-native/extend-expect' from 'node_modules/expo-router/src/testing-library/mocks.ts'
```

Do you want to try and fix that here or wait for someone to raise an issue for it?

**Comment by vanGalilea** [comment]
> Hey, @marklawlor . Thanks so much for fixing this. Your fix looks like it will do the job for `react-native-reanimated`.
> 
> But I think you'll find that there's still going to be a similar problem with `@testing-library/jest-native/extend-expect`:
> 
> ```
> Cannot find module '@testing-library/jest-native/extend-expect' from 'node_modules/expo-router/src/testing-library/mocks.ts'
> ```
> 
> Do you want to try and fix that here or wait for someone to raise an issue for it?

with newer RNTL libs. indeed this import should be change to `import '@testing-library/react-native/extend-expect';`

**Comment by vanGalilea** [comment]
@mersiades in the meanwhile you can use the following in your test:
```
// mock non existing modules
jest.mock('react-native-reanimated', () => null, {
  virtual: true,
});
jest.mock('@testing-library/jest-native/extend-expect', () => null, {
  virtual: true,
});
```

**Comment by mersiades** [comment]
> @mersiades in the meanwhile you can use the following in your test:
> 
> ```
> // mock non existing modules
> jest.mock('react-native-reanimated', () => null, {
>   virtual: true,
> });
> jest.mock('@testing-library/jest-native/extend-expect', () => null, {
>   virtual: true,
> });
> ```

Thanks mate
