### ISSUE TITLE
AppLoading white screen on Android

### ISSUE THREAD

**Issue by ahjorth** [expo/expo#255]
Was wondering if this was expected behavior?

When I close expo and launch the app from scratch, I get the expo logo and spinner, with my custom `exp.json` options

However, if I render `<AppLoading />` from within a component, I only get a white screen on Android.
On an iOS device running the exact same code, I get the expected expo logo loading screen.

**Comment by ahjorth** [comment]
Turns out it was misleading that it worked on iOS. It's supposed to only work as the only component returned from a root render, but with iOS it can work from anywhere apparently.

**Comment by nathanhannig** [comment]
here is the related issue 

https://github.com/expo/expo/issues/409
