### ISSUE TITLE
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by xiaolisuccess** [expo/expo#25518]
### Summary

gradlew.bat  exited with non-zero code: 1

### What platform(s) does this occur on?

Android

### SDK Version

 "expo": "~49.0.15",

### Environment

Need to install the following packages:
  expo-env-info@1.0.5

### Minimal reproducible example

gradlew.bat  exited with non-zero code: 1

**Comment by arslanafzal077** [comment]
this issue still exist on "expo": "^50.0.0",

**Comment by kuldip-simform** [comment]
I am having this issue
