### ISSUE TITLE
AuthRequest.promptAsync redirect to app causes crash

### ISSUE THREAD

**Issue by raphaeltm** [expo/expo#25515]
### Minimal reproducible example

https://github.com/raphaeltm/expo-auth-bug-demo

### Summary

# Current Behaviour

Recently I've had an app start breaking on Android: when the user gets redirected after completing an OAuth flow initiated by `AuthRequest.promptAsync` the app crashes. This used to work fine and we haven't touched the authentication code. It still works perfectly on iOS.

# Expected  Behaviour

The OAuth flow should redirect, and the app should handle the link appropriately as used to happen and as is still happening on iOS.

# Context

The bug occurs when running  in an Expo Development Build. Here is a sample build:
https://expo.dev/accounts/ec_raphael/projects/auth-bug-demo/builds/86381e11-609f-4c2e-aca0-c54083e31ae0

# Notes

The logs below are taken from once the auth browser window is open until the crash. Basically nothing happens in the logs as I login, and these are the lines that pop up as I click "login" in Keycloak and get redirected.

I noticed this line:
```
11-20 19:08:50.533   575   594 W ziparchive: Unable to open '/data/app/~~6I--bRpI5SzF8MNiLhzfJg==/com.ec_raphael.authbugdemo-1Ird6C-qDDYBqJVTUo_VEg==/base.dm': No such file or directory
```

I checked that directory on the device and it seems to have a `base.apk` file in it. My assumption is that this is the file that _should_ be targeted. I don't know why `base.dm` is showing up here. I've never come across the `.dm` file extension and most of my google results for the format don't make sense in this context.

# Logs

```
11-20 19:08:50.256   575  2138 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=demoapp://expo-development-client/... flg=0x14000000 cmp=com.ec_raphael.authbugdemo/.MainActivity (has extras)} from uid 10130
11-20 19:08:50.264   575  2138 I ActivityTaskManager: Launching r: ActivityRecord{f05d4fd u0 com.ec_raphael.authbugdemo/.MainActivity} from background: ActivityRecord{989c136 u0 com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity} t84}. New task: false
11-20 19:08:50.344   575  2138 I ActivityTaskManager: START u0 {flg=0x10018000 cmp=com.ec_raphael.authbugdemo/expo.modules.devlauncher.launcher.DevLauncherActivity} from uid 10175
11-20 19:08:50.346   575  2138 V SplashScreenExceptionList: SplashScreen checking exception for package com.ec_raphael.authbugdemo (target sdk:33) -> false
11-20 19:08:50.367   575  2138 D CoreBackPreview: Window{53992ec u0 Splash Screen com.ec_raphael.authbugdemo}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@c33514a, mPriority=0}
11-20 19:08:50.496   575  2161 D CoreBackPreview: Window{c3d8f1c u0 com.ec_raphael.authbugdemo/expo.modules.devlauncher.launcher.DevLauncherActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@8eaa0fa, mPriority=0}
11-20 19:08:50.533   575   594 W ziparchive: Unable to open '/data/app/~~6I--bRpI5SzF8MNiLhzfJg==/com.ec_raphael.authbugdemo-1Ird6C-qDDYBqJVTUo_VEg==/base.dm': No such file or directory
11-20 19:08:50.544  1505  1505 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1919 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.ec_raphael.authbugdemo fieldId=-1 fieldName=null extras=null}, false)
11-20 19:08:50.825   575  2138 D CoreBackPreview: Window{53992ec u0 Splash Screen com.ec_raphael.authbugdemo EXITING}: Setting back callback null
11-20 19:08:50.826   575  2161 W InputManager-JNI: Input channel object '53992ec Splash Screen com.ec_raphael.authbugdemo (client)' was disposed without first being removed with the input manager!
11-20 19:08:50.946   575  2161 D CoreBackPreview: Window{d880d49 u0 com.ec_raphael.authbugdemo/com.ec_raphael.authbugdemo.MainActivity}: Setting back callback null
11-20 19:08:50.948   575  2161 W InputManager-JNI: Input channel object 'd880d49 com.ec_raphael.authbugdemo/com.ec_raphael.authbugdemo.MainActivity (client)' was disposed without first being removed with the input manager!
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.8.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.9.1

**Comment by raphaeltm** [comment]
Is no-one else having this issue? It strikes me as a pretty big problem. And it was really simple to reproduce.

**Comment by atif089** [comment]
> Is no-one else having this issue? It strikes me as a pretty big problem. And it was really simple to reproduce.

+1 I'm facing the same issue

**Comment by raphaeltm** [comment]
@atif089 I ended up reaching out to expo support and eventually they responded with this:

> I think I found the issue. What I'm seeing is it actively navigating back to the dev client launcher activity, which kills the app view.
> 
> I noticed I could reproduce this same behavior without SSO at all, by backgrounding the app and then attempting to launch the same redirect URL: `adb shell am start -a android.intent.action.VIEW -d "demoapp://expo-development-client"`
> 
> But, if I changed that url above to something like "demoapp://blah", it returns to your app instead (I couldn't test SSO end-to-end because the server configuration wouldn't allow it).
> 
> scheme://expo-development-client is actually a reserved path for navigating to a specific experience, such as when directing someone to test an EAS Update inside a development build. We document this usage for opening updates, but not where you shouldn't use it (such as when testing SSO). So, I would recommend trying a different path in there, and I'm going to try to find a place to document that. Let us know how it goes!

We already ended up re-architecting our app to avoid Expo's AuthRequest system entirely by the time I got the response, but hopefully that will help you.

I would say the issue still deserves some proper documentation updates.

**Comment by raphaeltm** [comment]
Actually, I see the docs have been updated, so I'll close this.
