### ISSUE TITLE
[Crash] Get Push Notification data when app is closed - ANDROID

### ISSUE THREAD

**Issue by danielmorine** [expo/expo#2551]
Hello!
I'm having trouble opening the notification and viewing the data. The documentation mentions that the data is passed as: "**props.exp.notification**" on app root component, I passed via props until my component sending the same via navigation. I tested it several times in the developer environment and it was a success but generating the apk is not working.

Why does running in Expo DevTools and standalone app not work?

My dependencies: 
   "dependencies": {
    "axios": "^0.18.0",
    "expo": "^29.0.0",
    "expo-cli": "^2.1.3",
    "expokit": "1.5.0",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "native-base": "^2.6.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-collapsible": "^0.13.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^0.19.1",
    "react-native-material-design-searchbar": "^1.8.0",
    "react-native-signalr": "^1.0.6",
    "react-native-sqlite-storage": "^3.3.6",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.9.3"
  }

**Comment by ide** [comment]
Could you clarify what the problem is here? You mentioned a crash in the issue title and the root component props in the description.

**Comment by sjchmiela** [comment]
I'll let myself close this issue due to inactivity. I hope you've managed to fix your original problem! 🙂
