### ISSUE TITLE
[SDK 49][0.72.7][Android] `expo-dev-client` causes NullPointerException in `DevLoadingModule` during hot-reload

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#25520]
### Summary

After bumping react native to `0.72.7`, saving the project will immediately crash the Android app.

It's definitely related to this [commit](https://github.com/facebook/react-native/commit/5dedf277cb903528659f0d8a71412274d9d32a65). The introduction of `DevLoadingModule` does not play well with `expo-dev-client`.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

```json
"dependencies": {
  "expo": "~49.0.19",
  "expo-dev-client": "~2.4.12",
  "expo-status-bar": "~1.7.1",
  "react": "18.2.0",
  "react-native": "0.72.7",
  "expo-splash-screen": "~0.22.0"
}
```

### Environment

```
expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 14.1.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.asdf/installs/nodejs/16.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/thespacemanatee/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      API Levels: 23, 26, 29, 30, 31, 33, 34
      Build Tools: 26.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0
      System Images: android-24 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-26 | Google APIs Intel x86_64 Atom, android-26 | Google Play Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-33 | Desktop ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google Play ARM 64 v8a
  IDEs:
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  npmPackages:
    expo: ~49.0.19 => 49.0.20 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.7 => 0.72.7 
  npmGlobalPackages:
    eas-cli: 5.9.1
  Expo Workflow: bare
```

### Reproducible demo

https://github.com/thespacemanatee/dev_loading_module_crash_repro

- Run the project and save any changes
- Crash

Please checkout branch [without-expo-dev-client](https://github.com/thespacemanatee/dev_loading_module_crash_repro/tree/without-expo-dev-client) to see that hot reloading works without `expo-dev-client`

### Stacktrace (if a crash is involved)

```
 ERROR  Your app just crashed. See the error below.
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.devsupport.interfaces.DevLoadingViewManager.showMessage(java.lang.String)' on a null object reference
  com.facebook.react.modules.devloading.DevLoadingModule$1.run(DevLoadingModule.java:49)
  android.os.Handler.handleCallback(Handler.java:958)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:205)
  android.os.Looper.loop(Looper.java:294)
  android.app.ActivityThread.main(ActivityThread.java:8177)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by xseignard** [comment]
I confirm it is happening too with `expo@49` and `react-native@0.72.7`

**Comment by T-Damer** [comment]
Same for me and my team on:
```
    "expo": "^49.0.20",
    "react-native": "0.72.7",
```

**Comment by Mitdd9707** [comment]
_I am having the same problem!_

`"expo": "^49.0.14",
"react-native": "0.72.7"`

**Comment by lucasbasquerotto** [comment]
This happens, with me too, although expo-doctor suggests to use `0.72.6` in the eas build:

```
Some dependencies are incompatible with the installed expo version:
  react-native@0.72.7 - expected version: 0.72.6
```

Weird that this warning doesn't show when running `expo-doctor` (`1.1.3`) locally.

**Comment by jeferagudeloc** [comment]
Hi guys,

Hi, I had the same problem, I just downgrade this dependencies to:

`"expo-dev-client": "^2.4.11",
  "react-native": "0.72.5",`
   
And that solves the problem

**Comment by RohovDmytro** [comment]
Same with expo@49.0.21

**Comment by AntQwanlity** [comment]
Same issue here, simply reverting to react-native 0.72.6 fixes it

**Comment by trajano** [comment]
Perhaps the module should start considering use of the `PanResponder` rather than RNGH

**Comment by qizf7** [comment]
Same problem!
"expo-dev-client": "~2.4.12",
"react-native": "^0.72.6",
 "expo": "^49.0.21",

**Comment by AlfayezDev** [comment]
Confirmed downgrading `react-native-gesture-handler` from `2.14.0` to `2.12.0` fixed this issue for me.

**Comment by nonam4** [comment]
I'm using `expo` in `49.0.21` version. I see this problem after updating all app's dependencies.

After running `npx expo install --check` a lot of dependencies were downgraded to expo's expected versions including:
`react-native` from `0.72.9` to `0.72.6`
`react-native-gesture-handler` from `2.14.0` to `2.12.0`

The error stoped after this.

**Comment by techgerm** [comment]
We're developing our expo app in an Nx monorepo along side other bare bones react native apps and this started happening once we upgraded `react-native` from `0.72.6` to `0.72.9`.

For us it's not feasible to downgrade back to `0.72.6` but it's making android development on our expo app unbearable.
Is there any status update on when this could be fixed?

**Comment by brentvatne** [comment]
hi there!

this issue was caused by a regression in react-native in the 0.72.7 release. the react-native APIs that expo-dev-client uses are not always stable and we're working with Meta on improving that (see: https://github.com/react-native-community/discussions-and-proposals/pull/759#discussion_r1476513390).

we'll investigate what it would take to work around this regression.

**Comment by Mahmoudkhoder01** [comment]
any solutions here? my dependecies:
` "expo": "~49.0.15",
"expo-dev-client": "~2.4.12",
"react-native": "0.72.10",
"react-native-gesture-handler": "~2.12.0",`

**Comment by viniciuspetrachin** [comment]
The solution for me was in package.json:

Expo SDK: "expo": "~49.0.13"
React Native SDK: "react-native": "0.72.6"

I also removed the option for automatic updates, fixing the version at 0.72.6. This really solved the issue, as mentioned in the previous comment.

Before applying this solution, I was encountering the following error:

`java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.devsupport.interfaces.DevLoadingViewManager.showMessage(java.lang.String)' on a null object reference`

In Crashlytics, the logged error was:

```
com.facebook.react.modules.devloading.DevLoadingModule$1.run (DevLoadingModule.java:49)
android.os.Handler.handleCallback (Handler.java:958)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:205)
android.os.Looper.loop (Looper.java:294)
android.app.ActivityThread.main (ActivityThread.java:8177)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:552)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:971)
```
