### ISSUE TITLE
More tech demos for the "Explore" tab

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2552]
Currently we have navigation playground and Expo APIs, what other demos would be good? It's useful for people to explore capabilities within Expo. One thing to note is that on iOS people can only access these in the simulator so certain features won't make much sense.

**Comment by JOEAV** [comment]
@brentvatne  soon (probably a couple of weeks) I will have a great example for you focused on working with maps , push notifications and firebase integration
ill reach you out as soon as it's done
