### ISSUE TITLE
Can not open standalone App which is built by command "gulp android-shell-app" 

### ISSUE THREAD

**Issue by deniske** [expo/expo#2553]
Hello,

I have trouble to open my app which is installed by shell-debug.apk when my local is closed 

**### Environment**

I have checked at commit point e7bb9b2c769b363c9a065dd133125bc574680873

Environment:
OS: Ubuntu 16.04.5 LTS (Xenial Xerus)"
Node: v9.11.2
Yarn: 1.10.1
npm: 5.6.0

Packages:
"expo": "29.0.0-rc.2",
"react": "^16.3.1",
"react-native": "expo/react-native#sdk-29

Tested on Android 6.0.0 (HTC One X9 dual sim)

**### Steps to reproduce**

I followed README document step

1. Publish  my directory from exp and use command line "exp start " 

![selection_228](https://user-images.githubusercontent.com/25606833/47762155-61762b80-dcf6-11e8-82bc-46cd8a726842.png)

2. cd tools-public.
3. gulp android-shell-app --url exp://192.168.42.234:19000 --sdkVersion 29 --workingDir=../.
, and installed shell-debug.apk into my real device 

**### Expected Behavior**
can use this app which is installed by shell-debug.apk when my local server is closed 

**### Actual Behavior**
When I closed my local server , this app showed "Could not load app. Are you sure XDE or exp is running? Network response timed out "

Is there possible way to use this app when I closed my local server ?  Or did I miss some steps??

Thanks for helping.

**Comment by tsapeta** [comment]
Unfortunately I don't understand what you were trying to achieve here 😞 `gulp android-shell-app` was our internal tool and I think you should have used `expo build:android` command to build your standalone app instead. I'm closing this issue as it's been a long time. Feel free to reopen this issue or create a new one if you're still having some troubles with that.
