### ISSUE TITLE
[expo-notifications] do not receive push notifications even getting success response in push notification tool

### ISSUE THREAD

**Issue by ebru** [expo/expo#25538]
### Minimal reproducible example

https://snack.expo.dev/@noecrafts/adequate-yellow-apples

### Summary

We use `expo-notifications` for push notifications, it was working fine but at some point they stopped working out of nowhere and recently we had a chance to investigate. We are able to create expo push token and when I use it in https://expo.dev/notifications tool, no error is shown. On network tab, the request returns 200 response as well. 

```
https://api.expo.dev/v2/push/send
{"data":[{"status":"ok","id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}]}
```

But no notification arrives to the devices we tried at all. We use it only for iOS devices to mention. 
What could be the problem? Is this a potential bug since all certificates, token, project id etc and 200 status are there properly as far as we check or are we missing something? 

Thanks in advance.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.20 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: bare

**Comment by samuelprogramer** [comment]
Hi, I had the same problem as you and I discovered that in my case it was the fire base FCM, I believe it could be that too.

You can go to your Fire Base - Cloud Messaging and generate and get the FCM key then go to your expo.dev>YOUR PROJECT>PROJECT SETTINGS>CREDENTIALS, add the key to your Project credentials in the accordion - FCM Server Key

Take a look at these documentations:
https://docs.expo.dev/push-notifications/sending-notifications/

And you can test using this link or by CURL
https://expo.dev/notifications


```
curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
  "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
  "title":"hello",
  "body": "world"
}'
```

**Comment by ebru** [comment]
thank you @samuelprogramer, we ended up switching to OneSignal for notifications.
