### ISSUE TITLE
[@expo/config] [docs] app.config.ts loaded before app.config.js which breaks documented ts-node shim

### ISSUE THREAD

**Issue by chriszs** [expo/expo#25546]
### Summary

The docs [say](https://docs.expo.dev/guides/typescript/#appconfigjs) that you can add a shim file for `app.config.ts` to use `ts-node` for better TS support and (critically, for me) TS imports by adding `app.config.js` with:
```
require('ts-node/register');
module.exports = require('./app.config.ts');
```

However, this doesn't work for me. Whenever I run this, it just loads the TS file and then errors. I believe that's because config looks for `app.config.ts` first, as documented [here](https://docs.expo.dev/workflow/configuration/#configuration-resolution-rules) ("If both exist, then the TypeScript config is used.") and implemented [here](https://github.com/expo/expo/blob/bc46ebb39ea83a1ae06ed2acdd99a974a1a64f98/packages/%40expo/config/src/Config.ts#L219).

It does work when I name `app.config.ts` to something else, like say, `app-config.ts` and change `module.exports = require('./app.config.ts');` to `module.exports = require('./app-config.ts');` in `app.config.js` because config doesn't find the TS file and proceeds to load the JS file as documented.

Seems like either that first doc page should change, or the order of resolution should change (and then the second doc page should change). Having TS imports would be useful to me. I'm using locally defined config plugins, which I hope to convert to TS. So I'd vote for changing the order of resolution, but I'm not sure whether that'd cause other issues.

### Link to the related docs page

https://docs.expo.dev/guides/typescript/#appconfigjs

**Comment by kei95** [comment]
Hey! I've stumbled upon this issue and opened a PR for the change based on your suggestion. Let's hope we get some attention from reviewers 🤞 I don't think many devs make both `app.config.js` and `app.config.ts` in a project unless it's intentional like in your case.
