### ISSUE TITLE
Error: Missing package "@react-native-community/cli-server-api" in Expo Project

### ISSUE THREAD

**Issue by pfcodes** [expo/expo#25551]
### Summary

Expo should start without issues. But it does not. Instead I get a message about missing package: "@react-native-community/cli-server-api"

### What platform(s) does this occur on?

iOS

### SDK Version

49.0.20

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.20 => 49.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed

### Minimal reproducible example

With `yarn.lock` and `node_modules` deleted. Run `yarn install` then run `expo start`

I'm wondering if these issues are related due to some package dependency resolution issue.

**Comment by pfcodes** [comment]
Update: Switching to Bun resolved this issue. Clearing my Yarn cache and trying to use npm did not.

Also, around the time this issue started happening EAS Updates stopped working on my expo-dev-client. The app hangs on the splash screen.

**Comment by caioquirino** [comment]
@pfcodes can you try this workaround please?

```bash
yarn add @react-native-community/cli @react-native-community/cli-server-api
```
