### ISSUE TITLE
[docs]  Environment variables in Expo - Enforce process.env.EXPO_PUBLIC_[NAME] declaration

### ISSUE THREAD

**Issue by 87brandonn** [expo/expo#25555]
### Summary

It is obvious on the docs [here](https://docs.expo.dev/guides/environment-variables/) that the declaration of the env in application code should be in form of process.env.EXPO_PUBLIC_[NAME]

However, as a typescript (or javascript) developer in general, i assume that this would work in this case:

/constants/env.ts:
export const {
  EXPO_PUBLIC_API_URL: API_URL,
  EXPO_PUBLIC_SENTRY_DSN: SENTRY_DSN,
} = process.env;

App.tsx:
import { SENTRY_DSN } from '@/constants/env';

Sentry.init({
  dsn: SENTRY_DSN,
});

Actually, **this works fine in development profile**. However, after debugging for a whole day on what might gone wrong with the implementation in production profile, turns out that the root cause that this form of env declaration as i state above is not working. It should be declared directly like this:

App.tsx:
import { SENTRY_DSN } from '@/constants/env';

Sentry.init({
  dsn: process.env.EXPO_PUBLIC_SENTRY_DSN,
});

Although the docs might somewhere have stated about this, i personally think that **this somehow would need more clarification**, such as **adding Alert box with warning or danger theme that enforce this usage of process.env.EXPO_PUBLIC_[NAME]**. Because, in any circumstances, it is still possible there is someone out there encounter the same issues and figuring out what went wrong while actually the root cause is just this minor changes that they thought is working fine.

### Link to the related docs page

https://docs.expo.dev/guides/environment-variables/

**Comment by byCedric** [comment]
Hi @87brandonn! Thanks for reporting this issue. I'll flag this internally to see how we can improve the docs around the environment variables.

Right now, we have a section in our docs that briefly touches on why `const { EXPO_ENV } = process.env` (or other dynamic versions such as <code>process.env[`EXPO_${name}`]</code> are not supported.

![image](https://github.com/expo/expo/assets/1203991/7ebc9922-511f-4e28-906d-03f7c73ead61)

This works roughly similar to other popular tooling, such as [Next](https://nextjs.org/docs/pages/api-reference/next-config-js/env):

![image](https://github.com/expo/expo/assets/1203991/a37181d8-3400-4185-b927-957fc7b887cc)

Hope this helps for now!
