### ISSUE TITLE
[IOS][PRODUCTION] getExpoPushTokenAsync infinite loop

### ISSUE THREAD

**Issue by Fantasim** [expo/expo#2555]
Hi,

I'm trying to enable Notifications feature on my iOS app using Expo.
It works pretty well in developement mode using the expo client on my iPhone 7.
But when I upload the app on the store, and I test it using Testflight it doesn't work at all.

I struggled to find the source of the error but with some Alert placed in my code I found the origin.
And it comes from this line : 

`const pushToken = await Notifications.getExpoPushTokenAsync() `

Function is blocked, waiting for a token which never comes.

Someone has the same issue or I did something wrong ?
(I tell it again, it works perfectly in developement mode)

Version of my device : 
iPhone 7
Version 11.2.6

**Comment by outaTiME** [comment]
Same here, but with standalone android something wrong with expo server? 
using Expo SDK 30,

https://forums.expo.io/t/android-standalone-app-doesnt-get-expo-push-notification/15260

**Comment by emadjumaah** [comment]
same issue "sdkVersion": "32.0.0" the token on IOS production app never come from
const token = await Notifications.getExpoPushTokenAsync();

**Comment by MagdyMedhat** [comment]
me too ..
same issue "sdkVersion": "32.0.0" the token on IOS production app never come from
const token = await Notifications.getExpoPushTokenAsync();

**Comment by MikeMaya** [comment]
Same for me, "sdkVersion": "31.0.0" the token in ios production app (Test Flight) is never generated. It works well for Expo Client.

**Comment by emadjumaah** [comment]
Ok, 
here is how I did it,
I revoke the following 
 - iOS Distribution
 - Expo Push Notifications Key
and deleted the Provisioning Profile
basically clean all certificated and profile related to app then run 
`expo build:ios -c`
and let expo handle everything for me.
after that when I upload to app store,  apple send me an email that my app uses push notification service without Push Notifications Certificate,
so I edit ap ID and add push notification certificate - production one and then I remove the current Provisioning Profile and run 
`expo build:ios --clear-provisioning-profile`
then I upload a new binary and it works.

**Comment by emadjumaah** [comment]
another words, you need to create push notification certificate on app ID and build your project with `expo build:ios -c` and it should works.
