### ISSUE TITLE
SecureStore fails storing strings longer than 4072 characters on some Android devices

### ISSUE THREAD

**Issue by blakek** [expo/expo#2556]
This is not a duplicate of #1765 because that fails when fetching stored values; this occurs when saving.  #814 seems to be the closest issue, but it was resolved in SDK 23; we're on 30.

`SecureStore.setItemAsync()` is failing on some Android devices when saving longer strings.  If I replace with React Native's `AsyncStorage`, the same logic works as expected.  This seems to occur even after deleting/reinstalling the Expo app and clearing app data.

Further, this seems limited to _some_ (unsure which or how many) Android devices.  I can reliably reproduce in a Pixel 2 simulator (API 27; avd).  Unfortunately, I don't have a physical Pixel 2 to test on.  If there are issues reproducing, I'll try to round up several people with Android devices to test more thoroughly.

I've looked for documentation for this string length but have found none.  Since the limit is so close to 2^12, I'm wondering if the stored value should be split but isn't.

### Environment

  OS: macOS High Sierra 10.13.6
  Node: 11.0.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/gsandf-a75a3b7c-3ca9-4ab4-bae7-d51efb23026a.tar.gz

### Steps to Reproduce

Try to save any string _over_ 4072 characters long using `SecureStore.setItemAsync()`

### Expected Behavior

The value should be stored and able to be read again using `SecureStore.getItemAsync()`

### Actual Behavior

An error is thrown:

```
Error: "Could not encrypt the value for SecureStore"
```

### Reproducible Demo

The following Snack has a `TextInput` where you type the string size to store.  Submitting (on the keyboard) creates a string containing several `a`s as an example.  Typing 4072 works.  Any larger value fails.

https://snack.expo.io/@gsandf/securestore-android-string-limit

**Comment by ide** [comment]
We can test on a physical Pixel 2 to investigate this more. We have some tests for storing long-ish strings but not in the 4KiB+ range. Android's crypto implementations do differ across versions of Android and devices, though, so there will likely always be some edge cases with SecureStore on Android.

Also I'd recommend seeing if you can avoid sending 4KiB across the bridge from JS to native. That is a lot of data and can slow down your app if you are doing it a lot. If there's part of that 4KiB that you want to store extra securely, like a session token, and then can store the rest of the data using SQL or AsyncStorage, that'd probably work well.

**Comment by blakek** [comment]
Thanks.  I was afraid it'd be Android version/device dependent.

I mainly wanted to open this to make sure the size of data we do need (normally 1–2KiB) should typically work.  If there is a hard limit on some devices, I'd be up for adding some documentation so it's more clear that storing above that limit may not work.  Alternatively, I may hack on [`SecureStoreModule`](https://github.com/expo/expo/blob/41458d1de91544c41097818db21e44e9aa84688c/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/SecureStoreModule.java#L141) and see if I can find out more.
