### ISSUE TITLE
[android] add .jsbundle extension to cached-bundle-experience files

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2558]
https://forums.expo.io/t/bugsnag-and-minified-file-names/15375

This may involve some code to handle legacy named files.

**Comment by ide** [comment]
Since the files are just JS it might make sense to name them `.bundle.js`.

**Comment by esamelson** [comment]
Since we're working on a new Updates module, we're not going to work on this now in order to reduce unnecessary churn. The new Updates module will have all bundle files saved under the `.js` extension.
