### ISSUE TITLE
[docs] Sign in with Google

### ISSUE THREAD

**Issue by YuriOsokin** [expo/expo#25596]
### Summary

In the page [react-native-google-signin package ](https://docs.expo.dev/guides/google-authentication/) the links are broken. I was not able to use this module, since the package documentation is for sale only. Also, after a day of wondering through docs, I found that both Google One Tap and Google Sign-In for Android are depricated.

I suggest either to fix the documentaion with complete guide or give another simple way to sign in with Google.

### Link to the related docs page

https://docs.expo.dev/guides/google-authentication/

**Comment by MohammadIsmaill** [comment]
> ### Summary
> In the page [react-native-google-signin package ](https://docs.expo.dev/guides/google-authentication/) the links are broken. I was not able to use this module, since the package documentation is for sale only. Also, after a day of wondering through docs, I found that both Google One Tap and Google Sign-In for Android are depricated.
> 
> I suggest either to fix the documentaion with complete guide or give another simple way to sign in with Google.
> 
> ### Link to the related docs page
> https://docs.expo.dev/guides/google-authentication/
> 
> ### Anything else?
> _No response_

<img width="516" alt="image" src="https://github.com/expo/expo/assets/62969043/732b9293-c474-440c-be0f-bff83898f835">

just enable custom uri scheme and it will work fine

**Comment by waynetunmyint** [comment]
> https://docs.expo.dev/guides/google-authentication/

that work but after login. , it redirect to google.com

**Comment by jeonilshin** [comment]
yes when i also enabled the "Enable custom URI scheme" the login works but it redirects to https://google.com. please help....

**Comment by felipe-gustavo** [comment]
@jeonilshin, @waynetunmyint . You should define the `expo.scheme` with the slug of the app (`expo.slug`) in your `app.json`:
https://docs.expo.dev/versions/latest/config/app/#scheme

**Comment by rongart1** [comment]
> @jeonilshin, @waynetunmyint . You should define the `expo.scheme` with the slug of the app (`expo.slug`) in your `app.json`: https://docs.expo.dev/versions/latest/config/app/#scheme



> yes when i also enabled the "Enable custom URI scheme" the login works but it redirects to https://google.com. please help....

i same problem, have u found a solution??

**Comment by abhi210agni** [comment]
from where can I turn on custom URI scheme

**Comment by peefg** [comment]
> from where can I turn on custom URI scheme

in Google console, under credentials, but you might not want to do that.

> Important: Custom URI schemes are no longer supported on new Chrome apps and are disabled by default on new Android clients due to the risk of app impersonation.

[see more](https://developers.google.com/identity/protocols/oauth2/native-app#redirect-uri_custom-scheme)

**Comment by youssefdaoud133** [comment]
> > [@jeonilshin](https://github.com/jeonilshin), [@waynetunmyint](https://github.com/waynetunmyint) . You should define the `expo.scheme` with the slug of the app (`expo.slug`) in your `app.json`: https://docs.expo.dev/versions/latest/config/app/#scheme
> 
> > yes when i also enabled the "Enable custom URI scheme" the login works but it redirects to https://google.com. please help....
> 
> i same the problem, have u found a solution?? 🙏🙏
have u found bro?
