### ISSUE TITLE
takePictureAsync Orientation Issue

### ISSUE THREAD

**Issue by FabulouSebas** [expo/expo#2559]
### Environment

The problem occurs only on Android, as far as i know. I use Expo, non-ejected build.

### Steps to Reproduce

With the Huawei P20, when i take a picture in landscape mode with the Expo Camera component and its takePictureAsync method, the picture doesn't stay in landscape mode. Therefore, the picture is rotated to be in portrait mode. If i could just rotate the picture with ImageManipulator, it wouldnt be an issue, but takePictureAsync with the {exif: true} params does not include the exif in its response. Perhaps both problems are related. However, on an iPhone 8, i get the exif, and the picture stays in landscape mode. This picture is accessed with the photo uri given in the response of 
takePictureAsync.

### Expected Behavior

The exif should be available on any phone .
**and/or** 
The picture should stay in its original orientation for any phone.

### Actual Behavior

The exif is not available and the photo doesn't keep its original orientation. However, i have it on an iPhone 8 and it keeps its original orientation when i access the photo uri. 

(Write what happened. Add screenshots!)

### Reproducible Demo

The behavior might happen on more Android phones or iOS phones. As far i know, its only an Android issue.

My code: 

```
render() {
    return (
      <Container appBackground safe>
        <EXPOCamera
          ref={ref => {
            if (ref) { this.camera = ref; }
          }}
          style={{ flex: 1 }}
          type={EXPOCamera.Constants.Type.back}
          whiteBalance={EXPOCamera.Constants.WhiteBalance.auto}
          flashMode={this.state.flashMode}
          ratio={this.state.ratio}
          onCameraReady={ref => this._getSupportedRatiosAsync(ref)}>
          <CameraFooter
            onCameraIconPress={() => this._snap()} />
        </EXPOCamera>
      </Container>
    );
  }

  _snap() {
    if (this.camera) {
      this.camera.takePictureAsync({
        quality: 1,
        base64: true,
        exif: true
      })
        .then(photo => {
          if (this.state.pictureBeingSaved) {
            photo.externalPhotoUrl = photo.uri;
            this.props.navigation.push('PhotoUploadInfo', { photos: [photo] });
          }
        })
        .catch(this.onTakePictureError);
    }
  }
```

**Comment by thekrol01** [comment]
Having the same issue with SDK 32. Apple landscape orientation works as aspected (recoding video en taking pictures). Testing the same code on android, landscape orientation is not recognized both taking pictures and recording video 's.

**Comment by borgogelli** [comment]
Did you try to add the following (android only) option ?
`skipProcessing : true`
like it's documented here: https://docs.expo.io/versions/latest/sdk/camera/

**Comment by MalikNaser** [comment]
> Did you try to add the following (android only) option ?
> `skipProcessing : true`
> like it's documented here: https://docs.expo.io/versions/latest/sdk/camera/

didn't work for me.. any solution?

**Comment by univers3** [comment]
Same here!
I think it' the combination of a portrait only app and the need to take landscape photos.
On iOS works like a charm.
On android when you take a landscape photo (horizontal phone) you will get a portrait one.
Even the exif is wrong.

I think the only workaround possible is to read the device physical orientation when a user will take the photo. With https://docs.expo.io/versions/latest/sdk/devicemotion/

But I think that a fix under the hood can be pretty simple.
@FabulouSebas did you find a solution?

**Comment by esamelson** [comment]
Hey all -- apologies this continues to be an issue 😞 Here is an up-to-date snack that reproduces the issue: https://snack.expo.io/NTNZeDNC5 . We reproduced the issue on both a Pixel 2 and a OnePlus 6T but in both cases, using `skipProcessing: true` fixed the orientation. Anyone for whom `skipProcessing: true` does NOT work, what kind of device are you testing on?

**Comment by lucianoacsilva** [comment]
Hello, same issue here! Tried `skipProcessing: true`, but it did not work either.

**Comment by lucianoacsilva** [comment]
If someone finds a solution, call me. Trying to find a workaround here too.

**Comment by innergap** [comment]
anyone find a solution for this? having the same issue.

**Comment by impactcolor** [comment]
Same problem here.  I run skipProcessing: true on Samsung Android phone and it stays the same.
I appreciate Expo but I think it's kind of whack how often questions like this get left hanging.

**Comment by innergap** [comment]
This worked for me with expo-image-manipulator, however the quality is not so great. Wondering whether it's because of the rotation or whether it's a different issue all together.



     let photo = await this.camera.takePictureAsync({quality: 1}); 
     photo = await ImageManipulator.manipulateAsync(photo.uri, [{
          rotate: 0
      }, {
          resize: {
            width: props.width, // also resizing here, which is just an additional thing I'm doing
            height: props.height
          }
      }], {
          compress: 1
      });

**Comment by impactcolor** [comment]
I tried device motion as suggested and it listener.orientation returns 0 no matter what way I have the phone.  Neither landscape or portrait changes it

**Comment by impactcolor** [comment]
On SDK 36, Samsung phone rotate: 0 didn't work for me.

**Comment by innergap** [comment]
@impactcolor sorry, should have mentioned I only used rotate: 0 on iOS and it worked for me. If it doesn't work on Android I would try other values for rotate like 90, -90, etc.

**Comment by impactcolor** [comment]
@innergap Hi, thank you! It doesn't work.  It's the same issue for me as mentioned when I take a picture on android it doesn't set the right orientation.  I tried to solve it by rotating only if the width is larger than the height but it also causes the same issue since it doesn't detect the right width or height.  It's not recognizing landscape for some reason.  I'm using SDK 36

**Comment by impactcolor** [comment]
@esamelson Samsung Galaxy Note 8

**Comment by Nikoms** [comment]
Same problem on a Pixel3.

Here is my workaround : 

```
const picture = await cameraRef.current.takePictureAsync({ exif: true });
if (picture.width === picture.exif.ImageWidth) { 
   setSelectedImage(new Media(picture));
} else {
   const manipResult = await ImageManipulator.manipulateAsync(picture.uri, [{ rotate: -90 }],   { compress: 1 });
   setSelectedImage(new Media({ ...manipResult, exif: picture.exif })); //Of course, the exif will not contain the good size here.. But I can live with it as I only need datetime in my app 
}

```

**Comment by impactcolor** [comment]
On two devices, Android, it also does not respect the EXIF.
The exif displays the same size when holding the phone landscape or portrait for me.

**Comment by nachozullo** [comment]
Same issue here SDK 38

**Comment by JoeDuncko** [comment]
Also experiencing this with a Pixel 3a on SDK 39. Not sure how to solve it yet.

**Comment by conor909** [comment]
on my iPad, in landscape orientation, the camera image is rotated 90 degrees.  But if I move the iPad to portrait, and then back to landscape, the image doesn't get rotated anymore.

**Comment by Francisco-Slope** [comment]
In SDK 52 this has been my solution, only check width and height.

```
    const takePicture = async () => {
        if (cameraRef.current) {
            const photo = await cameraRef.current.takePictureAsync()
            let imgUri = photo.uri

            const imageContext = await ImageManipulator.manipulate(imgUri)
            // Manipulate to make it look like it was taken
            if ("front" === cameraFacing) {
                await imageContext
                    .rotate(180)
                    .flip("vertical")
            } else {
                if (photo.width > photo.height) {
                    await imageContext
                        .rotate(90)
                }
            }

            const renderedImage = await imageContext.renderAsync()
            const invertedImage = await renderedImage.saveAsync()

            imgUri = invertedImage.uri

            setImageUri(imgUri)
        }
    }

```
