### ISSUE TITLE
packager error: Error starting tunnel 

### ISSUE THREAD

**Issue by axlider** [expo/expo#256]
I get following error after i started packager in xde:

```
Error starting tunnel: Error: Error: panic: runtime error: invalid memory address or nil pointer dereference

github.com/inconshreveable/olive/recover.go:40
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
:30
:132
github.com/inconshreveable/olive/recover.go:29
runtime/asm_amd64.s:479
runtime/panic.go:458
github.com/inconshreveable/olive/error.go:37
runtime/asm_amd64.s:479
runtime/panic.go:458
runtime/panic.go:62
runtime/signal_windows.go:161
lib/tunnel/client/reconnecting.go:39
lib/tunnel/client/session.go:97
ngrok/tunnel_session.go:138
ngrok/web_api.go:95
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/error.go:41
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/recover.go:32
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/logger.go:17
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:250
github.com/go-martini/martini/router.go:120
ngrok/src/ngrok/web.go:27
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
github.com/go-martini/martini/martini.go:173
github.com/go-martini/martini/martini.go:69
```

Thank you!

**Comment by hmenzagh** [comment]
Same issue here, worked yesterday !

**Comment by dikaiosune** [comment]
@axlider @hmenzagh is this still happening for you? This is usually the case when ngrok experiences some downtime.

**Comment by axlider** [comment]
@dikaiosune this is still happening.

**Comment by axlider** [comment]
Now i also tried without using xde:

I get different errors here:
- At first I got error message: "Could not start intent..."
- Then I fiddled around in "android-apk-cache" and downloaded and copied "Exponent-1.17.0.apk" manually to "android-apk-cache"
- Now i am stuck with a blue screen and the error message on genymotion "could not load exp://10.127.221.127:19000. Can't connect to internet. Please try again."

As i am on a corporate network with internet proxy, it seems to me I have to configure internet proxy also for expo? Could that be the problem? But where to do that?

**Comment by ide** [comment]
The error "Couldn't connect to server, check your internet connection" means that CRNA couldn't download the native IPA to install on your simulator. The IPA is hosted on S3 -- make sure that your computer can download files from S3 (perhaps you have some kind of HTTP proxy in the way?).

The error about starting a tunnel is about the exp.direct network tunnel, which allows your phone to load your project from your computer even if they are on different networks. If your phone and computer are on the same WiFi network then you don't need the tunnel and can tell XDE to use your LAN IP instead (click the gear icon next to the URL bar in XDE).

If your Expo app is still crashing on your Android device, can you send us information about which version of the Expo client you have and the ADB logs?

**Comment by axlider** [comment]
@ide 
Yes that's exactly the problem. Network proxy!
I temporarily managed to switched to open wlan in our company (no proxy) and now obviously the IPA has been downloaded.) Now i get "Could not connect to the server code -10041".

Unfortunately, normally i have to work in corportate wlan with http proxy:
- Do you know what is the correct way to configure network proxy for CRNA? (It would be great if it would take over proxy configuration from .npmrc). 
- Is there a way to configure network proxy for the "exp.direct" network tunnel?

What does "Could not connect to the server code -10041" mean? Does it refer to Expo server?

Gear icon is interesting! Unfortunately i get same error no matter what i choose (localhost/tunnel/lan). I am connected via WLAN. Unfortunately there's no option for WLAN. But nevertheless packager and simulator are running on same machine in my scenario. Therefore localhost would be the correct option.

Thank you!

**Comment by ide** [comment]
You can set the `http_proxy` and `https_proxy` env vars and XDE will use them.

**Comment by axlider** [comment]
Have set proxy on command line (windows style) and started xde from same command line.

C:\Program Files\Expo XDE>set HTTPS_PROXY=http://myDomain\user:pwd@my-proxy:8000
C:\Program Files\Expo XDE>set HTTP_PROXY=http://myDomain\user:pwd@my-proxy:8000

still same problem. Think it's time to stop and search for a different solution.

Thanks anyway!

**Comment by ide** [comment]
Okay, sorry this ended up not working for you.
