### ISSUE TITLE
Which kind of Google Maps API Key should we use in MapView?

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#2561]
Hi guys!
I just posted this question in StackOverflow ([here](https://stackoverflow.com/questions/53092683/how-google-maps-pricing-works)) and I'm also talking with Google Cloud customer services, but I also want to ask you about it.

Google Maps Cloud services have a lot of kind of Google Maps API Key.
* JavaScript APIKey
* Android APIKey
* iOS APIKey

In the [MapView documentation](https://docs.expo.io/versions/latest/sdk/map-view) I don't see an explanation about which kind of API Key we should use for development time in iOS or Android.

Do you know which kind of APIKey do we have to use?
Currently, in my `app.json` file I have this:
```JSON
{
  "expo": {
    "sdkVersion": "30.0.0"
  },
  "ios": {
    "config": {
      "googleMapsApiKey": "xxxxxx"
    }
  }
}
```

Should that APIKey be an iOS API Key? Should I also create an Android API Key and define it in the `app.json` file?

The weird thing is that the current API Key that I'm using is a JavaScript API Key, and it's counting "1 usage" per each device where I test the app (instead of for each time that I use the Map).
But, I'm also using the same kind of API Key in a browser, and it's counting as "1 usage" every time that I refresh the page. Weird.

So, do some of you really knows which kind of API Key should be implemented in the App, for iOS and Android? And should it be implemented? And why it's counting 1 usage per device instead of 1 usage per each time I restart the App?

**Comment by ide** [comment]
You should use the iOS and Android API keys. Expo Maps uses the native Google Maps libraries (from the perspective of the Google Maps code, it doesn't know that you're using JS with Expo).

**Comment by BrodaNoel** [comment]
@ide how can I define a key for iOS and another one for Android?
Something like this?:

```JSON
{
  "expo": {
    "sdkVersion": "30.0.0"
  },
  "ios": {
    "config": {
      "googleMapsApiKey": "xxxxxx"
    }
  },
  "android": {
    "config": {
      "googleMapsApiKey": "xxxxxx"
    }
  }
}
```

**Comment by ide** [comment]
See the docs for app.json: https://docs.expo.io/versions/latest/workflow/configuration
