### ISSUE TITLE
[sqlite] `expo-sqlite/next` attach command `SQLiteErrorException: unable to open database`

### ISSUE THREAD

**Issue by peterferguson** [expo/expo#25618]
### Minimal reproducible example

https://github.com/peterferguson/sqlite-hook-test

### Summary

Attempting to attach another db to the connection fails to open the database

![image](https://github.com/expo/expo/assets/7002211/aa21b3e2-b1c1-4c85-b18a-11c4a4437b3c)

However, if I run the same command on the database from an editor it works

![image](https://github.com/expo/expo/assets/7002211/27acc503-9fc3-4565-81ea-1d06b9271b4d)

The [last commit](https://github.com/peterferguson/sqlite-hook-test/commit/afd4c09fb73218da233233b8e7b7c96ea1bc2773) in the above (mostly minimal) repo just adds the attach command which then fails 

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-alpha.7 => 50.0.0-alpha.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: bare

**Comment by Kudo** [comment]
hi @peterferguson! since expo-file-system will have `file://` scheme, that's the correct fix for attaching database:

```diff
--- a/App.jsx
+++ b/App.jsx
@@ -55,10 +55,14 @@ const Child = () => {
   const refreshRows = () => setRows( database.allSync( 'SELECT * FROM test' ) )

   useEffect( () => {
-    database.execSync( `ATTACH '${FileSystem.documentDirectory}/SQLite/${attachDbName}' as attached` )
+    const dbPath = `${FileSystem.documentDirectory}/SQLite/${attachDbName}`.replace(/file:\/\//, '');
+    database.execSync( `ATTACH '${dbPath}' as attached` )
     // database.execSync( `ATTACH '${attachDbName}' as attached` )

     console.log( 'database list - ', database.allSync( 'PRAGMA database_list' ) )
+    return () => {
+      database.execSync( `DETACH DATABASE attached` )
+    };
   }, [] )

   useEffect( () => {
```

however, getting the `${FileSystem.documentDirectory}/SQLite/` prefix is not clear, thanks for looking into the implementations. i'm open to recommendations for a proper way to attach databases.

also seeing some error when testing your example and that would be resolved by #25637

**Comment by peterferguson** [comment]
Hey thanks for getting to this & sorting the issue so quickly! (also I really should have noticed that 🫣)

On the prefix being unclear, it helped that I had already done some digging into the source when I was building out the drizzle connector that we use. Not sure how best to make it clear to users that are new to the library. Probably if it is documented well in the future it shouldn't really matter as it will be unseen by the majority of users?

In terms of how best to use the `attach` command, I am not sure. I have seen some libraries provide an explicit function to do it (which would help with the indirection caused by the `SQLite` folder). 

In our case, we know what we need to attach at init time, so having an option on the context to attach those in the same `useEffect` as the `main` db itself would be nice. I am not sure that this is the majority of use-cases though. The worry here is that if use-cases like this keep getting added to the context options they may get a bit unwieldy.

A third option could be to just expose the `dbPath` as parameter on the client. Then those users that want to attach other dbs can just base their path of it. This is my least favourite option but it at least provides the user a way to know where the attached databases should reside without having to dig into source code.

**Comment by peterferguson** [comment]
Oh also while on the topic of `attach` will there be an option to use `sqlite3_limit` & `SQLITE_LIMIT_ATTACHED` to increase the number of allowed attached databases?

**Comment by DarylBeattie** [comment]
> ```diff
> +    const dbPath = `${FileSystem.documentDirectory}/SQLite/${attachDbName}`.replace(/file:\/\//, '');
> ```

Just something I noticed; `FileSystem.documentDirectory`'s documentation says it ends in a trailing slash, so no need to add another one before `SQLite`.

**Comment by Kudo** [comment]
thanks everyone. will further follow up to add these features

also a head-up that i just landed a change from #25657 that would bring breaking changes to the expo-sqlite/next API. the pr should describes migration. let me know if you have any unclear part and i'm glad to answer the questions. thanks and sorry to bring the breaking changes.

**Comment by Kudo** [comment]
we also landed the expo-sqlite/next doc at https://docs.expo.dev/versions/v50.0.0/sdk/sqlite-next/

**Comment by brentvatne** [comment]
hi there! as far as i know, this issue should be resolved in the latest version of expo-sqlite (formerly known as expo-sqlite/next)

**Comment by Kudo** [comment]
that's correct. thanks to #31278, the `databasePath` is now composed from js. people can now use [`db.databasePath`](https://github.com/expo/expo/blob/bf7654a252a4370c178b0616d20f3e8d38283bc4/packages/expo-sqlite/src/SQLiteDatabase.ts#L24) to retrieve the path of the database.
for example, to attach the existing database

```ts
const existingDb = await SQLite.openDatabaseAsync('existingDb');
const memDb = await SQLite.openDatabaseAsync(':memory:');
await memDb.execAsync(`ATTACH '${existingDb.databasePath}' at attached`);
```
