### ISSUE TITLE
Tab not getting hidden when using material tabs from react navigation

### ISSUE THREAD

**Issue by VivekNeel** [expo/expo#25635]
### Minimal reproducible example

https://github.com/VivekNeel/expo-router-material-tabs

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I am using latest expo router and material bottom tabs from react navigation. I have been trying to hide the tab using `href:null `as the document suggests, but it does not work. However it does work with the default `Tabs` from expo-router

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.0 - ~/.nvm/versions/node/v20.6.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v20.6.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.18 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Hiding tabs based upon `href` is specific to the `Tabs` component that comes with Expo Router. You can see our implementation and filtering logic here, you may be able to adapt it for 3rd party libraries

https://github.com/expo/expo/blob/main/packages/expo-router/src/layouts/Tabs.tsx
