### ISSUE TITLE
[IOS] TaskManager taskExecutor call with delay when get background push notification.

### ISSUE THREAD

**Issue by juliayojji** [expo/expo#25634]
### Minimal reproducible example

https://snack.expo.dev/@julia_predantseva/taskmanager

### Summary

TaskExecutor that was passed to TaskManager.defineTask() call with a delay.

**How to reproduce:**
Application is launched in the background. App receive push notifications. 
See that code that passed in TaskManager.defineTask calls with a delay.

**Expected behaviour:** 
TaskExecutor call immediately every time when app receive Push Notification.

**Current behaviour:** 
App receive Push Notification and taskExecutor call with a delay (in can be 4 minutes or 10 minutes).Time to time taskExecutor call immediately when when receive Push Notification. But in more cases it calls with a delay.

Tested in app builded with eas build.
Tested with IOS 17.2 and 16.5.1.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
      Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: managed
```

**Comment by therajumandapati** [comment]
@Simek Thanks for adding the label to this bug. When will we find out which SDK this bug fix is going to be in?
