### ISSUE TITLE
[iOS][expo-camera] Camera is very blurry on iPhone 15 Pro

### ISSUE THREAD

**Issue by marlonschlosshauer** [expo/expo#25641]
### Minimal reproducible example

https://snack.expo.dev/@marlonschlosshauer/basic-camera-usage

### Summary

Expo-camera on an iPhone 15 Pro is completely blurry and won't focus properly. 

Here is a screenshot of the Expo Camera example snack, running on an iPhone 15 Pro: 

<img src="https://github.com/expo/expo/assets/24259317/83665917-b185-4fa0-9112-38ab2b216188" width="300px"/>

The same snack runs fine on a normal iPhone 15. The linked snack is using expo-camera 13.4.4, but the issue also appears on 13.9.0. 

This seeems to be an issue with the iPhone 15 Pro and third-party apps in general:
[Reddit: iPhone 15 pro camera won’t focus on anything close on any 3rd party app (Snapchat, etc)](https://www.reddit.com/r/iphone/comments/175r2yk/iphone_15_pro_camera_wont_focus_on_anything_close/)
[MacRumors: 
iPhone 15 PRO Camera Closeup on 3rd Party Apps](https://forums.macrumors.com/threads/iphone-15-pro-camera-closeup-on-3rd-party-apps.2407951/)
[Discussion Apple: iPhone 15 Pro / Max camera blurry and won't focus](https://discussions.apple.com/thread/255193005)

There appeared to be a similiar issue with iPhone 13 Pros and 14 Pros about a year ago: #19472, but no solution for Expo-Camera was found. People in the issue recommended switching cameras (on the back), but I couldn't find an option to do so.  

Is this a known issue? Any ideas on how I could fix this?

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.7.0 - ~/.nvm/versions/node/v20.7.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.7.0/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/msc/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    Expo Workflow: managed
```

**Comment by ogmzh** [comment]
I can report same thing happening

**Comment by staylorwr** [comment]
We've seen the same thing happening with iPhone 15s

**Comment by DelapriaDouglas** [comment]
I am using expo-camera version 13.2.1
I'm having the same problem on the iPhone 14 Pro 17.1.2 and it also occurs on the iphone 14 Pro Max.
In the versions of the Iphone 12 below is apparently working.

Have you found any solution to this problem @expo-bot?

**Comment by bryanltobing** [comment]
still happening on ios 17 iphone 14 pro max

**Comment by DelapriaDouglas** [comment]
I managed to solve focus problem by adding properties
"autoFocus={true}" and useCamera2Add to the Camera component.
expo-camera version 13.2.1
```
<Camera
ref={cameraRef}
type={CameraType.front}
useCamera2Api 
autoFocus
/>
```

In my case the main impact was with the useCamera2Api which helps to work better with newer devices.
I hope it helps you too.
@bryanltobing

**Comment by davidpsanders** [comment]
Have made a patch for this in a duplicate issue
https://github.com/expo/expo/issues/26869#issuecomment-1976694433

**Comment by seba9999** [comment]
I'm still experiencing blurry image with an iphone 14 pro and expo-camera@15.0.16 ... 

```
  const [autoFocus, setAutoFocus] = useState('on'); // I've tried "on" and "off" without any changes
  const [useModernScanner, setUseModernScanner] = useState(false); // To try modernScan on iOS but doesn't change anything !

<CameraView
      ref={cameraRef}
      style={ {
           height: '100%',
           width: '100%'
       }}
      facing="back"
      ratio="1:1"
      autofocus={autoFocus}
      barcodeScannerSettings={{
        barcodeTypes: ['qr'],
      }}
      onModernBarcodeScanned={isiOS && useModernScanner ? onScan : undefined}
      onBarcodeScanned={!isiOS || !useModernScanner ? onScan : undefined}
 />
```
