### ISSUE TITLE
Issue with Implementing CLLocationManagerDelegate in AppDelegate.h for Expo Projects

### ISSUE THREAD

**Issue by ytatsuno** [expo/expo#25656]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by dydent** [comment]
We are currently facing the same issue. Adding changes to the `AppDelegate.mm` works just fine with `withAppDelegate` but there is no "easy" way to also update the` AppDelegate.h` file.
