### ISSUE TITLE
Cannot build bundle for production due to babel 7.0.0 error

### ISSUE THREAD

**Issue by sebasgarcep** [expo/expo#2566]
I'm running Expo v30 (and using the corresponding Expo React Native bundle). Builds were working properly until today, when I tried to publish existing code into a new release channel. When the bundle was building I got an error that was something like this:

```
500 - "{\"type\":\"TransformError\",\"lineNumber\":0,\"errors\":[{\"description\":\".../node_modules/expo-print/index.js: Requires Babel \\\"^7.0.0-0\\\", but was loaded with \\\"6.26.3\\\". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention \\\"@babel/core\\\" or \\\"babel-core\\\" to see what is calling Babel. (While processing preset: \\\".../node_modules/expo-print/node_modules/babel-preset-expo/index.js\\\")\",\"lineNumber\":0}],
```

Because no code was changed since the last time I published, I figured that the error had to something to do with the `expo-print` dependency mentioned in the message. In fact it was updated in the last day to depend on `babel-preset-expo` v5.0.0 which uses `babel` v7.0.0 which conflicts with `babel` v6.x.x used by `babel-preset-expo` v4.0.0. The problem is that the new version of `expo-print` has semantic version of `1.1.0` which matches the dependency requirements for it inside `expo`'s package.json (`^1.0.0`). That means that whenever I install `expo` v30.0.0 I get `expo-print` v1.1.0 which creates incompatibility issues due to the `babel` conflict.

This can be fixed by either reverting `expo-print`'s dependency to something that is compatible with `babel` v6.0.0 or by pulling out `expo-print` v1.1.0 from npm and pushing it with an updated major number i.e. v2.0.0.

If anyone else encounters this issue I worked around it by using [selective dependency resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) with yarn.

**Comment by LantosTG** [comment]
Same error here with Expo v31.0.0 dropping to expo v30.0.1 solved it. In your case update to v30.0.1
In expo v31.0.0 there is a dependancy on an older async or an incompatible one that has a dependancy babel-core rather than @babel/core.

**Comment by ide** [comment]
Sorry about breaking your build for you. We'll roll back expo-print 1.1.0 and publish it as 2.0.0.

@tsapeta @sjchmiela we should probably bump the major version number of all modules with each new SDK release. That would help us completely avoid issues like this one.

**Comment by ide** [comment]
What we ended up doing for now is:

- Published the SDK 30 version of expo-print as 1.2.0
- `expo` SDK 30 will pick it up since it depends on `expo-print@^1.0.0`
- `expo` SDK 31 won't pick it up since it depends on `expo-print@~1.1.0`
- Sorry this is confusing

**Comment by sebasgarcep** [comment]
@ide Thanks for the fix! While it works I'm curious, why did you pick this solution instead of updating the major number?

**Comment by sjchmiela** [comment]
We've upgraded `babel-preset-expo` as one of the last steps of the release process and we didn't give it enough thought. It was a mindless mistake, sorry for that! 😞

**Comment by ide** [comment]
@sebasgarcep `expo` SDK 31 depends on `expo-print@~1.1.0` so upgrading the major version number of `expo-print` to 2.0.0 would not work without republishing `expo` and having everyone upgrade.

**Comment by EnginYilmaz** [comment]
> I'm running Expo v30 (and using the corresponding Expo React Native bundle). Builds were working properly until today, when I tried to publish existing code into a new release channel. When the bundle was building I got an error that was something like this:
> 
> ```
> 500 - "{\"type\":\"TransformError\",\"lineNumber\":0,\"errors\":[{\"description\":\".../node_modules/expo-print/index.js: Requires Babel \\\"^7.0.0-0\\\", but was loaded with \\\"6.26.3\\\". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention \\\"@babel/core\\\" or \\\"babel-core\\\" to see what is calling Babel. (While processing preset: \\\".../node_modules/expo-print/node_modules/babel-preset-expo/index.js\\\")\",\"lineNumber\":0}],
> ```
> Because no code was changed since the last time I published, I figured that the error had to something to do with the `expo-print` dependency mentioned in the message. In fact it was updated in the last day to depend on `babel-preset-expo` v5.0.0 which uses `babel` v7.0.0 which conflicts with `babel` v6.x.x used by `babel-preset-expo` v4.0.0. The problem is that the new version of `expo-print` has semantic version of `1.1.0` which matches the dependency requirements for it inside `expo`'s package.json (`^1.0.0`). That means that whenever I install `expo` v30.0.0 I get `expo-print` v1.1.0 which creates incompatibility issues due to the `babel` conflict.
> 
> This can be fixed by either reverting `expo-print`'s dependency to something that is compatible with `babel` v6.0.0 or by pulling out `expo-print` v1.1.0 from npm and pushing it with an updated major number i.e. v2.0.0.
> 
> If anyone else encounters this issue I worked around it by using [selective dependency resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) with yarn.

Hello, I am having similar issues building my project. Could you please share your package.json

**Comment by idsingh** [comment]
@EnginYilmaz Simply put expo-print : 1.0.0 in your package.json. It will work with SDK 30.

**Comment by nickjuntilla** [comment]
Is there a way to get this working while staying with SDK 31?

**Comment by nickjuntilla** [comment]
I tried downgrading to expo 30.0.1, but now I get this:

```
ERROR
14:06
Building JavaScript bundle: error
ERROR
14:06
/Users/***/Documents/ReceiptChain-dev/src/App.js: [BABEL] /Users/***/Documents/ReceiptChain-dev/src/App.js: Unknown option: /Users/***/Documents/ReceiptChain-dev/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`
```

My config file looks like this:

```
{
  presets: ['babel-preset-expo'],
  env: {
    development: {
      presets: [
        "react-app"
      ]
    },
  },
}
```

**Comment by jetobe95** [comment]
Thaks

> Same error here with Expo v31.0.0 dropping to expo v30.0.1 solved it. In your case update to v30.0.1
> In expo v31.0.0 there is a dependancy on an older async or an incompatible one that has a dependancy babel-core rather than @babel/core.

Thanks a lot!!!!👍🏻
