### ISSUE TITLE
[Android][expo-media-library] After calling the deleteAssetsAsync, the application crashes when the "Deny" button is pressed

### ISSUE THREAD

**Issue by yevheniiburkovskyi** [expo/expo#25667]
### Summary

**Expected behavior**: after pressing the cancel button, the application works as before
**Actually happening**: crashes when the "Deny" button is pressed

https://github.com/expo/expo/assets/109791286/18317163-a650-4026-b6d7-a841d0525dfd

It looks like the delete function is running before the user has given permission to delete asset.

### What platform(s) does this occur on?

Android 12+

### SDK Version

49.0.21

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.21 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.7 => 0.72.7 
      expo-image-picker: 14.5.0
      expo-media-library: 15.6.0
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/yevheniiburkovskyi/AwesomeProject

**Comment by vishal778** [comment]
Hi, Is there any update the this?

**Comment by yevheniiburkovskyi** [comment]
> Hi, Is there any update on this?

no :(

**Comment by devatrox** [comment]
Same issue! On calling `deleteAssetsAsync` it asks for permission (with a missing preview). On hitting Deny it crashes with

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7463, result=0, data=null} to activity {com.dbweichesetupfe.dev/com.dbweichesetupfe.dev.MainActivity}: expo.modules.medialibrary.PermissionsException: User didn't grant write permission to requested files.
```

The photo is deleted anyways and `deleteAssetsAsync` returns `true`

**Comment by giorgiPapava** [comment]
Same issue here, is there any workaround?

**Comment by mathieupost** [comment]
Having the same issue...

I'm trying to work around this by using `react-native-exception-handler` to catch the exception. But unfortunately, without success so far.

**Comment by dunkman32** [comment]
> Having the same issue...
> 
> Full stack trace
> I'm trying to work around this by using `react-native-exception-handler` to catch the exception. But unfortunately, without success so far.

same here...

**Comment by mathieupost** [comment]
Just found out that if you can't wait for the new release which includes https://github.com/expo/expo/pull/28212, then you can use the [`patch-package`](https://www.npmjs.com/package/patch-package) npm package to apply the change yourself 🎉

**Comment by yevheniiburkovskyi** [comment]
> Just found out that if you can't wait for the new release which includes https://github.com/expo/expo/pull/28212, then you can use the [`patch-package`](https://www.npmjs.com/package/patch-package) npm package to apply the change yourself 🎉
 
thank you, you helped a lot🥳☺️👍

**Comment by hotaryuzaki** [comment]
> Just found out that if you can't wait for the new release which includes #28212, then you can use the [`patch-package`](https://www.npmjs.com/package/patch-package) npm package to apply the change yourself 🎉

There is an issue, file already deleted before choose allow or deny.
so "deny" is not useful here.

**Comment by hotaryuzaki** [comment]
> > Just found out that if you can't wait for the new release which includes #28212, then you can use the [`patch-package`](https://www.npmjs.com/package/patch-package) npm package to apply the change yourself 🎉
> 
> There is an issue, file already deleted before choose allow or deny. so "deny" is not useful here.

this patch fixes the issue, https://github.com/expo/expo/pull/28323
