### ISSUE TITLE
Hello. I have a question that If I made a project through expo start and then at the middle I require some codes to be run on Android and iOS folders. Then what to do? And after that will, the expo modules work again? And after changing into the iOS and Android I again want to go to the expo and start development again. Then what to do?  Also If I eject using Expo eject and after that do I have to write the native codes in Android and iOS exclusively or writing the codes again in JS work? And after ejecting the project and adding something to the JS code again then how will that save to the expo project. And if I had changed something in the Android and iOS folders will that reflect in the main project too?

### ISSUE THREAD

**Issue by LetsNurtureGit** [expo/expo#2567]
Hello. I have a question that If I made a project through expo start and then at the middle I require some codes to be run on Android and iOS folders. Then what to do? And after that will, the expo modules work again? And after changing into the iOS and Android I again want to go to the expo and start development again. Then what to do?

Also If I eject using Expo eject and after that do I have to write the native codes in Android and iOS exclusively or writing the codes again in JS work?
And after ejecting the project and adding something to the JS code again then how will that save to the expo project.
And if I had changed something in the Android and iOS folders will that reflect in the main project too?

**Comment by cgomezmendez** [comment]
Hello @LetsNurtureGit , I would really suggest you to edit your title it's pretty long and hard to read, it would make others that can reply you to understand what you're really asking for.

**Comment by ide** [comment]
The way to write custom native code with Expo is to use ExpoKit. Currently you can use ExpoKit by running `expo eject` in your project. Most Expo modules will work with the exception of notifications.

You still write most of your app in JS. Using ExpoKit allows you to write both native code to expose APIs to JS, and to write most of your app in JS using those APIs you implemented.

Read these guides carefully and try using ExpoKit in a small sample project to learn how to write native code with Expo:

- ExpoKit overview: https://docs.expo.io/versions/latest/expokit
- Setting up ExpoKit: https://docs.expo.io/versions/latest/expokit/eject
- Developing with ExpoKit: https://docs.expo.io/versions/latest/expokit/expokit
- More on ExpoKit: https://docs.expo.io/versions/latest/expokit/advanced-expokit-topics
