### ISSUE TITLE
Update dependency sharp to 0.21.0 in turtle-cli to enable alpine docker images

### ISSUE THREAD

**Issue by fwal** [expo/expo#2568]
### Environment

Environment:
  OS: alpine
  Node: 10.9.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: 4.7.0

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

### Steps to Reproduce

1. Try to run `turtle-cli setup:android` in an `alpine` based docker image
 
### Expected Behavior

The command completes without error.

### Actual Behavior

The program crashes due to dependency `sharp` not being able to find `libvips`.
This is due to a faulty behaviour that's fixed in sharp version 0.21.0 (https://github.com/lovell/sharp/issues/1423)
This affects both turtle-cli and its shell apps.

**Comment by ide** [comment]
@dsokal Can you look at this and see whether it makes sense to support running Turtle CLI within Alpine Linux? I'm not sure if there are other dependencies that would make it much harder to support Alpine that Debian or Ubuntu.

**Comment by dsokal** [comment]
@fwal I upgraded `sharp` to the latest version and released `turtle-cli@0.3.1`.

**Comment by dsokal** [comment]
@fwal what do you mean by saying it fails? Aren't there any error logs? I just tried to run the same command on this Docker image - https://github.com/dsokal/expo-turtle-android/blob/master/Dockerfile - and it works well for me.

**Comment by fwal** [comment]
That doesn't seem to be an alpine-based docker image. 😉
It tries to install the outdated version of `sharp` in the `.turtle/workingdir/android/sdk31/node_modules` folder...

Seems to be `@expo/expo-tools-public` that's [the culprint](https://github.com/expo/expo/blob/master/tools-public/package.json#L28)

**Comment by dsokal** [comment]
I know it's not an alpine-based docker image, but I wanted to say that there aren't any issues on another Docker image. 
Ok, so I'll upgrade `sharp` in `tools-public` as well, but it's a little more complicated than the upgrade in `turtle-cli`. It should be fixed tomorrow.

**Comment by fwal** [comment]
Awesome, thanks again for the help!

**Comment by dsokal** [comment]
@fwal `turtle-cli@0.3.3` has been released, please let me know if the new version fixes the issue you're experiencing.

**Comment by fwal** [comment]
@dsokal Yes that fixed it, thanks! 👍
