### ISSUE TITLE
Support More Advanced Audio Recording

### ISSUE THREAD

**Issue by MrLoh** [expo/expo#257]
Hi, I needed to eject from Expo, because the Audio Recording is so basic and buggy under Android. I at least need to be able to set basic things like a sample rate. 

Also an audio bit stream would be really great, even though it might have some overhead. But there doesn't seem to be any react native library that supports that yet. 

Maybe it would make more sense to just use one of the more established audio libraries inside expo though. 

https://github.com/futurice/react-native-audio-toolkit
https://github.com/jsierles/react-native-audio

**Comment by terribleben** [comment]
Thanks for the feedback. Can you be more specific about the features which you would like to see (e.g. setting sample rate) and the bugs which are blocking you? Some things may be fixed in our upcoming SDK, and it would be good to enumerate the things we don't already know about.

**Comment by MrLoh** [comment]
The most important one for us was currently sample rate. The react-native-audio-toolkit also provides settings for bitrate, channels, format, encoder, and quality. All those make a lot of sense to keep controllable. See [here][](https://github.com/futurice/react-native-audio-toolkit/blob/master/docs/API.md#recorder-methods):

```js
recorderOptions:
{
  // Set bitrate for the recorder, in bits per second
  bitrate : Number (default: 128000)

  // Set number of channels
  channels : Number (default: 2)

  // Set how many samples per second
  sampleRate : Number (default: 44100)

  // Override format. Possible values:
  // Cross-platform:  'mp4', 'aac'
  // Android only:    'ogg', 'webm', 'amr'
  format : String (default: based on filename extension)

  // Override encoder. Android only.
  // Possible values:
  // 'aac', 'mp4', 'webm', 'ogg', 'amr'
  encoder : String (default: based on filename extension)

  // Quality of the recording, iOS only.
  // Possible values: 'min', 'low', 'medium', 'high', 'max'
  quality : String (default: 'medium')
}
```

But the killer feature would be to provide a bit stream from native to the js-thread. We are workin on a shazam like audio fingerprinting, so we need a stream of the recorded audio to match it (in our case the matching happens on device). Currently we are basically hacking it by just writing a file every few seconds and then reading it in, as described here https://github.com/jsierles/react-native-audio/issues/172#issuecomment-307791866. Works for now, but we will have to optimize the performance, once we get past the MVP stage. 

A performant implementation of streaming the recording will be tricky, because there's a lot of data to pass through the bridge, but I don't currently see any way around it except for doing everything on the native side. 

We are also looking into open sourcing our audio fingerprinting solution, once it get's more stable.

**Comment by MrLoh** [comment]
This cordova plugin might provide a good starting point for streaming audio from the native side to the js side. 
https://github.com/edimuj/cordova-plugin-audioinput

**Comment by dikaiosune** [comment]
Hi! We're trying to keep feature requests on Canny so we can track them in a single place. I've created two based on this issue:

https://expo.canny.io/feature-requests/p/configure-audio-recording-with-sample-rate-bitrate-channels-format-encoder-quali
https://expo.canny.io/feature-requests/p/expose-audio-recording-bitstream-to-js

Please create more if I haven't covered the important topics here. Thanks!
