### ISSUE TITLE
expo-doctor: check for common project setup issues

### ISSUE THREAD

**Issue by WildesPiva** [expo/expo#25700]
### Summary

Error in command expo-doctor:

npx expo-doctor@1.1.3      
   
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

but my project is "bare" workflow, how to fix that?

### SDK Version

49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.8 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: bare

### Minimal reproducible example

This did not happen in version expo-doctor@1.0.7, this happens: expo-doctor@1.1.3

**Comment by MihirP24** [comment]
I am also having the same issue, are you able to fix it?

**Comment by iagolucas2020** [comment]
@WildesPiva, Did you manage to solve this problem? I'm going through the same situation.

**Comment by keith-kurak** [comment]
Hi all! Apologies for the issue. 

If you're bare workflow and intend to be, you can ignore this warning. You can also work around this warning by removing or commenting out any config plugins in your app config (these have no effect when you're in bare).

We're working on making this warning more precise, explaining what fields in app config are being ignored because your app is bare. The original intent was because we have found several users who have inadvertently opted out of using Prebuild, and one of the hints is an app config that is arranged to use prebuild features.

**Comment by MihirP24** [comment]
> Hi all! Apologies for the issue.
> 
> If you're bare workflow and intend to be, you can ignore this warning. You can also work around this warning by removing or commenting out any config plugins in your app config (these have no effect when you're in bare).
> 
> We're working on making this warning more precise, explaining what fields in app config are being ignored because your app is bare. The original intent was because we have found several users who have inadvertently opted out of using Prebuild, and one of the hints is an app config that is arranged to use prebuild features.

Hello, mine is manage workflow, and I am getting another error which says missing build profile in eas.json. I tried several things but getting the same error when I try to run eas build --profile development-simulator --platform ios this command to install the development build
