### ISSUE TITLE
Passing props from layout to Slot

### ISSUE THREAD

**Issue by pbandjs** [expo/expo#25720]
### Minimal reproducible example

https://github.com/pbandjs/expo-router-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have a simple layout setup using the basic set up documented here: https://docs.expo.dev/router/layouts/

I am trying to pass on props to the 'Slot', but the props value is always undefined in the component rendered in the slot.  I am unable to find info on how to do this or if this is even possible.

FYI, the reason I need to do this is I have some dynamic elements in my layout which are affected by elements in the child component (such as its scroll). 

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v18.7.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
      Watchman: 2023.11.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 31, 34
        Build Tools: 28.0.3, 29.0.2, 31.0.0, 34.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ~49.0.15 => 49.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed

**Comment by VolkerLieber** [comment]
You can use `createContext` (https://react.dev/reference/react/createContext) to pass down the data until there is a better solution.

**Comment by marklawlor** [comment]
Slot doesn't accept any props, but this is something I'm willing to think about.

In the mean time, `createContext` is the best way to achieve your desired result

**Comment by sohammondal** [comment]
I agree. We should do this.
