### ISSUE TITLE
Error on setting prop on LinearGradient

### ISSUE THREAD

**Issue by spi971** [expo/expo#25739]
### Minimal reproducible example

Cannot set prop 'colors' on view 'class abi49_0_0.expo.modules.lineargradient.LinearGradientView' → Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Double.intValue()' on a null object reference

### Summary

hi!
I had that error , on an android phone (realme 7), using the expo app

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 20.9.0 - ~/n/bin/node
      Yarn: 1.22.19 - ~/n/bin/yarn
      npm: 10.1.0 - ~/n/bin/npm
    npmPackages:
      expo: ~49.0.18 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.9.0
    Expo Workflow: managed

**Comment by TheUntoldFable** [comment]
Have you managed to solve this? @spi971
