### ISSUE TITLE
Expo 31.x.x Upgrade

### ISSUE THREAD

**Issue by bonbonio** [expo/expo#2574]
Hi,
Using an App made with the create command line; I get the following error after an upgrade; couldn't find any threads on the topic at all... I don't think I have made any changes to anything involving the core of the App from a standard setup.

**`/Apps/ExampleApp/app/app.js: Plugin/Preset files are not allowed to export objects, only functions. In /Apps/ExampleApp/node_modules/babel-preset-react-native/index.js`**

This are my devDependencies

```
"devDependencies": {
"babel-jest": "19.0.0",
"babel-preset-react-native": "1.9.1",
"eslint": "⁵.7.0",
"eslint-config-prettier": "³.1.0",
"eslint-config-react-native": "³.0.2",
"eslint-config-standard": "¹².0.0",
"eslint-plugin-import": "².14.0",
"eslint-plugin-node": "⁷.0.1",
"eslint-plugin-prettier": "³.0.0",
"eslint-plugin-promise": "⁴.0.1",
"eslint-plugin-standard": "⁴.0.0",
"jest": "22.0.0",
"onchange": "⁵.0.2",
"prettier": "1.14.3",
"react-test-renderer": "16.0.0-alpha.6"
},
```

This is my babelrc file
```
{
  "presets": ["react-native"]
}

```

**Comment by sjchmiela** [comment]
Hey! Latest `expo` release uses `react-native^0.57.1` which uses Babel 7. `babel-preset-react-native` (which you're using) isn't compatible with the latest version of Babel, as explained [here](https://www.npmjs.com/package/babel-preset-react-native). It has been replaced with [metro-react-native-babel-preset](https://github.com/facebook/metro/tree/master/packages/metro-react-native-babel-preset).

If you're using Expo I would encourage you to use `babel-preset-expo` Babel preset, which always includes proper preset for your project to work. So, to fix your issue I would:
- remove `babel-preset-react-native` from among `devDependencies`,
- add `babel-preset-expo@^5.0.0` to `devDependencies`,
- remove `.babelrc` file
- add a new `babel.config.js` file containing
    ```js
    module.exports = function(api) {
      api.cache(true);
      return {
        presets: ['babel-preset-expo'],
      };
    };
    ```

**Comment by bonbonio** [comment]
Many Thanks @sjchmiela

**Comment by artyorsh** [comment]
For those who are trying to configure expo-31:
Check our [boilerplate](https://github.com/akveo/akveo-react-native-boilerplate/tree/typescript). This repo contains all initial configurations to make things working with new expo-31, babel 7, typescript and jest.
