### ISSUE TITLE
expo tool - error spawn ENOENT

### ISSUE THREAD

**Issue by davidgithub1980** [expo/expo#2577]
Hi, I am running the latest expo (SDK v30) and the expo commant line tool (v. 2.2.0.)  under Windows 7 Professional.
**_expo build:android_** works fine, but **_expo build:ios_** generates the following error after trying to enter apple id password:
![ioserr](https://user-images.githubusercontent.com/6930312/47950306-b6ad7980-df50-11e8-91a5-204f0ca6d181.PNG)

Is there a bug in the command line tool as only building an Android app works fine?

**Comment by ide** [comment]
See the warning above -- you must enable WSL. Without WSL it makes sense that bash would be missing on your machine.
