### ISSUE TITLE
Loading Assets are so slow after update sdk to 31.0.0

### ISSUE THREAD

**Issue by x86kernel** [expo/expo#2578]
Assets are load after the below warnings are completely shown after update sdk version to 31.0.0

`Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.`

It seems like cause of metro bundler
I have found this [issue](https://github.com/facebook/metro/issues/287)

is there any method ignore all warnings?

**Comment by YannzizTay** [comment]
`
adding the following in App.js worked for me so far
import {YellowBox} from 'react-native'
...
componentDidMount(){
YellowBox.ignoreWarnings([
  'Require cycle:', 
])
}
`

**Comment by serhiipalash** [comment]
Please update `react-native-gesture-handler` in next Expo release. It has fixed the bug with require cycle

https://github.com/kmagiera/react-native-gesture-handler/pull/323

**Comment by gerardo15** [comment]
> Please update `react-native-gesture-handler` in next Expo release. It has fixed the bug with require cycle
> 
> [kmagiera/react-native-gesture-handler#323](https://github.com/kmagiera/react-native-gesture-handler/pull/323)

How can i fix this warnings while waiting for next expo release?

**Comment by serhiipalash** [comment]
@gerardo15 I am trying to find general fix for these warnings, will let you know if it is possible.

But if you have only one warning for `react-native-gesture-handler` in theory you can manually apply this diff  https://github.com/kmagiera/react-native-gesture-handler/pull/323/files on `node_modules/react-native-gesture-handler/` directory content.

**Comment by otaviogaiao** [comment]
My app stopped working on remote debugger due to these warnings. This is what I get on the console: 
![screen shot 2018-11-04 at 09 56 36](https://user-images.githubusercontent.com/3965485/47963803-0c008e00-e018-11e8-9578-23f2e3f7ab57.png)

It happens after I upgraded to SDK 31

**Comment by danikane** [comment]
Guys, I did the same research as @serhiipalash, saw the same issue on the package in question, the same PR  so I applied the commit's changes in my node_modules/react-native-gesture-handler and it's working fine.

**Comment by redpandatronicsuk** [comment]
As a temporary fix to disable the warning and have assets load quicker, you can comment out line 109 in `node_modules/metro/src/lib/polyfills/require.js`.

**Comment by serhiipalash** [comment]
I have created pull request to fix this bug. I think it will be released soon in Expo minor release `31.0.3` or later. Until that you can manually apply this fix by changing `/node_modules/expo/build/environment/logging.js`. You should remove slash before "node_modules" string in console.warn patch regex

before
<img width="941" alt="screen shot 2018-11-05 at 12 35 58 am" src="https://user-images.githubusercontent.com/14208343/47970823-101dc180-e093-11e8-8561-2555f20ab24e.png">

after
<img width="930" alt="screen shot 2018-11-05 at 12 36 34 am" src="https://user-images.githubusercontent.com/14208343/47970826-1744cf80-e093-11e8-8bb8-c2bb1b171894.png">

**Comment by serhiipalash** [comment]
Expo 31.0.3 was released and the fix is in it.

**Comment by gerardo15** [comment]
excelent @serhiipalash one question, where can i see this Expo releases? can't seem to find them

**Comment by danikane** [comment]
I can only track them here:
https://www.npmjs.com/package/expo

**Comment by serhiipalash** [comment]
> where can i see this Expo releases? can't seem to find them

@gerardo15 if you have in your `package.json` Expo dependency defined like this `"expo": "^31.0.0"` all you need to do is remove `node_modules` and `npm install`, than you will have `expo@31.0.3` in your `node_modules`.

**Comment by ide** [comment]
@serhiipalash's suggestion works -- though be sure to remove any lock files too. You can also update your package.json to include `"expo": "^31.0.3"` to really ensure you'll get the new package.
