### ISSUE TITLE
Video resizeMode cover in native component list is ignored on Android

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2582]
![img_8546](https://user-images.githubusercontent.com/90494/47957483-cdb19300-df73-11e8-96b6-bf535acaedf8.jpg)
![img_8545](https://user-images.githubusercontent.com/90494/47957485-ce4a2980-df73-11e8-8ab7-afbd7198d9bf.jpg)

this is in the latest version of native-component-list

**Comment by R-D-P** [comment]
I am still facing this issue in Expo version 31.
How do I go about fixing it? 
Thanks.

**Comment by istvan-szilagyi** [comment]
Me too, have you found a solution?

**Comment by R-D-P** [comment]
It only seems to happen in the expo client app , it works alright in the standalone app.

**Comment by istvan-szilagyi** [comment]
Just upgrade expo to 32.0.0, and will work in the expo client app as well!
