### ISSUE TITLE
Cannot find module 'metro-core

### ISSUE THREAD

**Issue by spyshower** [expo/expo#25838]
### Summary

eas update doesn't work, but it used to work with the exact commads and code
`eas update -p android --channel=preview`

error:

[expo-cli] node:internal/modules/cjs/loader:1028
[expo-cli]   const err = new Error(message);
[expo-cli]               ^
[expo-cli] 
[expo-cli] Error: Cannot find module 'metro-core'
[expo-cli] Require stack:
[expo-cli] - /Users/d/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js
[expo-cli] - /Users/d/node_modules/@expo/cli/build/src/export/createBundles.js
[expo-cli] - /Users/d/node_modules/@expo/cli/build/src/export/exportApp.js
[expo-cli] - /Users/d/node_modules/@expo/cli/build/src/export/exportAsync.js
[expo-cli] - /Users/d/node_modules/@expo/cli/build/src/export/index.js
[expo-cli] - /Users/d/node_modules/@expo/cli/build/bin/cli
[expo-cli]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
[expo-cli]     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
[expo-cli]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[expo-cli]     at require (node:internal/modules/cjs/helpers:119:18)
[expo-cli]     at Object.<anonymous> (/Users/d/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:10:18)
[expo-cli]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[expo-cli]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[expo-cli]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[expo-cli]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[expo-cli]     at Module.require (node:internal/modules/cjs/loader:1100:19) {
[expo-cli]   code: 'MODULE_NOT_FOUND',
[expo-cli]   requireStack: [
[expo-cli]     '/Users/d/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js',
[expo-cli]     '/Users/d/node_modules/@expo/cli/build/src/export/createBundles.js',
[expo-cli]     '/Users/d/node_modules/@expo/cli/build/src/export/exportApp.js',
[expo-cli]     '/Users/d/node_modules/@expo/cli/build/src/export/exportAsync.js',
[expo-cli]     '/Users/d/node_modules/@expo/cli/build/src/export/index.js',
[expo-cli]     '/Users/d/node_modules/@expo/cli/build/bin/cli'
[expo-cli]   ]
[expo-cli] }
✖ Export failed
/Users/d/node_modules/expo/bin/cli.js exited with non-zero code: 1
    Error: update command failed.

### What platform(s) does this occur on?

Android

### SDK Version

49.0.8

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
      npm: 9.4.2 - ~/node_modules/.bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      expo: ^49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

eas.json

{
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "channel": "development"
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "channel": "preview"
    },
    "production": {
      "android": {
        "buildType": "apk"
      },
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}

**Comment by spyshower** [comment]
What kind of fucking code am I supposed to provide for the f cli?

**Comment by SpectorHacked** [comment]
Also happening to me when upgrading from SDK 46 until 49 SDK.
