### ISSUE TITLE
[expo-image][Android] tintColor is not working

### ISSUE THREAD

**Issue by dancamdev** [expo/expo#25836]
### Minimal reproducible example

```html
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.33333 18.6667L7.43286 27.0648C7.49191 27.301 7.52143 27.4191 7.55636 27.5222C7.89755 28.5295 8.80469 29.2378 9.86469 29.3245C9.9732 29.3333 10.0949 29.3333 10.3384 29.3333C10.6433 29.3333 10.7957 29.3333 10.9241 29.3209C12.1933 29.1978 13.1978 28.1933 13.3209 26.9241C13.3333 26.7957 13.3333 26.6433 13.3333 26.3384V7.33334M24.6667 18C27.244 18 29.3333 15.9107 29.3333 13.3333C29.3333 10.756 27.244 8.66667 24.6667 8.66667M13.6667 7.33334H8.66666C5.35295 7.33334 2.66666 10.0196 2.66666 13.3333C2.66667 16.647 5.35296 19.3333 8.66666 19.3333H13.6667C16.0219 19.3333 18.903 20.5959 21.1257 21.8075C22.4224 22.5144 23.0708 22.8678 23.4954 22.8158C23.8892 22.7676 24.1869 22.5908 24.4178 22.2682C24.6667 21.9202 24.6667 21.224 24.6667 19.8316V6.83505C24.6667 5.44266 24.6667 4.74647 24.4178 4.39852C24.1869 4.07587 23.8892 3.89907 23.4954 3.85084C23.0708 3.79883 22.4224 4.15227 21.1257 4.85914C18.903 6.07082 16.0219 7.33334 13.6667 7.33334Z" stroke="#846F57" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

```Js
<Image 
    source={require('../assets/icons/announcement.svg')}                 
    tintColor={'#846F57'}                 
    style={{tintColor:  '#846f57'}} />
```

### Summary

The tint color isn't applied, testing with the latest expo-image version at the time of writing 1.5.1

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
      Watchman: 2023.10.23.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 33.0.1, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    npmPackages:
      expo: ^49.0.0 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.8 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed

**Comment by dancamdev** [comment]
Tested with `expo-image@1.8.1` as well and the issue persists.

**Comment by lukmccall** [comment]
I wasn't able to reproduce this issue. 
<img width="866" alt="image" src="https://github.com/expo/expo/assets/9578601/49d498a3-02fc-45d5-b96b-5008be2e1bc2">
I've tried both `expo-image@1.8.1,` and the new canary release - the tint color was applied correctly. If you still face that problem, can you create a fresh issue with a minimal reproducible example? That would help in understanding and fixing the problem.
