### ISSUE TITLE
IOS build won't load on IOS simulator

### ISSUE THREAD

**Issue by francisleigh** [expo/expo#25837]
### Summary

Hello there! 

Recently started a new expo app (typescript, bare workflow) 

I created a dev-client build but when installing onto my emulator (via expo orbit) i get the following error: 
```
Some other error occurred while running xcrun command.
xcrun simctl install 8879C670-B16A-4FB3-B426-5D1750868717 /var/folders/k6/7_y8fc8x0f1g8j1v3cz7jgbc0000gn/T/expo-orbit-nodejs/6339895e-3cb4-48df-b44b-d564dca3e4f0/Payload/NOD.app exited with non-zero code: 4
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=4):
“NOD” Needs To Be Updated
This app needs to be updated by the developer to work on this version of iOS.
Failed to find matching arch for input file: /Users/francisleigh/Library/Developer/CoreSimulator/Devices/8879C670-B16A-4FB3-B426-5D1750868717/data/Library/Caches/com.apple.mobile.installd.staging/temp.esGmuB/extracted/NOD.app/NOD
Underlying error (domain=MIInstallerErrorDomain, code=15):
Failed to find matching arch for input file: /Users/francisleigh/Library/Developer/CoreSimulator/Devices/8879C670-B16A-4FB3-B426-5D1750868717/data/Library/Caches/com.apple.mobile.installd.staging/temp.esGmuB/extracted/NOD.app/NOD
```

I hope this helps! 

Thanks 
- Frank

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

```
IOS Simulator: IPhone 14 Pro Max (IOS 16.2)

_______

"expo": "~49.0.15",
"expo-build-properties": "~0.8.3",
"expo-dev-client": "~2.4.12",

_______

MacOS Monterey
Version 12.5.1

XCode Version 14.2 (14C18)
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo

run
```
eas build --profile development
```
And try to load the built 'client app onto a simulator with the above spec.

**Comment by francisleigh** [comment]
Appreciate the closing of this ticket BUT i can't add anything to expo forums at the mo as it's "Read only" at this time.

**Comment by francisleigh** [comment]
https://github.com/francisleigh/NOD <-- repo

**Comment by francisleigh** [comment]
Update, Opened my work Silicone M1 Pro Max (Sonoma)
Tried opening a completely fresh create-expo-app build (typescript bare) setup with v basic dev client and get the following error when I select "Open with expo orbit"

```Some other error occurred while running xcrun command.
xcrun simctl launch C3F9C60F-8ABB-4AC6-A1B9-9BF8BE8D6646 com.francisleigh.devclienttest exited with non-zero code: 1
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
Simulator device returned an error for the requested operation.
The request was denied by service delegate (SBMainWorkspace).
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.francisleigh.devclienttest" failed.
The request was denied by service delegate (SBMainWorkspace).```

**Comment by keith-kurak** [comment]
@francisleigh Hi! I tried to reproduce this issue with the reproduction and was unable to. The example project doesn't have a "simulator" profile, so I couldn't run it on a simulator via `eas build --profile development` as-is. I added: `{ "ios" : { "simulator": true } }` to the development profile just to try it out, and was able to run it in Orbit.

You might check if you have the latest version of Orbit, and you can compare what happens when you open the build with Orbit vs if you download it and drag it to the device. This would help isolate if the issue is with your build, Orbit, or your Xcode configuration.

If you're able to isolate this further, when making the minimal reproduction, it's good to start with something like `create-expo-app` and only add what is needed to cause the issue, as opposed to sharing your own project. When other things are added to the reproduction, it can be hard to tell what is causing the issue.

**Comment by francisleigh** [comment]
@keith-kurak i appreciate you taking the time to look into this. Bare with me let me try adding simulator to the dev profile.

**Comment by francisleigh** [comment]
@keith-kurak OK, i can confirm that worked...for my M1 machine running Sanoma & XCode v15.0.1

For my older machine, it's the same issue. I imagine I need to be on a specific version of Expo/eas that is compatible with my older machine... e.g
```
Monterey 12.5.1
Xcode v14.2
```

Or there may be a setting in the `eas.json` that defines versions you want to be able to go down to?

**Comment by francisleigh** [comment]
Hold up.... wait a minute...

```shell
Waiting for build to complete. You can press Ctrl+C to exit.
✔ Build finished

🍏 iOS app:
xyz.tar.gz

✔ Install and run the iOS build on a simulator? … yes

✔ Successfully downloaded app archive 4s

Installing your app on the simulator...
✔ Successfully installed your app on the simulator!

Launching your app...
✔ Successfully launched your app!

```

Launching the app through the command line worked 😊

**Comment by francisleigh** [comment]
So i can confirm,
