### ISSUE TITLE
undefined is not an object (evaluating 'Platform.OS') when scanning Expo app with QR code

### ISSUE THREAD

**Issue by AryanJ-NYC** [expo/expo#2583]
1. `npm install`
2. `npm start`
3. Scan QR Code on OnePlus 3T running Android 8.0.0 

### Expected Behavior

The application should render to the screen.

### Actual Behavior
![screenshot_20181103-175209](https://user-images.githubusercontent.com/8263430/47957731-f183d180-df91-11e8-8f4a-7fb89df7d493.jpg)

### Reproducible Demo
https://github.com/AryanJ-NYC/kings-cup

**Comment by brentvatne** [comment]
can you reproduce this without react-native-web and the other dependencies there? it's helpful for reproducible examples to minimal - https://stackoverflow.com/help/mcve. i can't reproduce this on my machine on another expo sdk 31 project

**Comment by AryanJ-NYC** [comment]
Thank you for the tip in creating helpful, reproducible and minimal examples. It indeed _did_ help in isolating the issue. The issue lied in using `react-native-web` with my application.

I appreciate your quick response.
