### ISSUE TITLE
BOOST_VERSION has been removed from `$REACT_NATIVE_DIR/ReactAndroid/gradle.properties`

### ISSUE THREAD

**Issue by achingbrain** [expo/expo#25847]
### Minimal reproducible example

...

### Summary

The `downloadBoost` function in the default `build.gradle` file spat out by `npx expo run:android` tries to work out the boost version from `BOOST_VERSION` which comes from `reactProperties.getProperty("BOOST_VERSION")` which in turn is loaded from `$REACT_NATIVE_DIR/ReactAndroid/gradle.properties` - as of `react-native@0.73.0` this property has been removed:

- v0.72.0 - https://unpkg.com/react-native@0.72.0/ReactAndroid/gradle.properties
- v0.73.0 - https://unpkg.com/react-native@0.73.0/ReactAndroid/gradle.properties

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.8.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /Users/alex/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.72.0 => 0.72.7 
    Expo Workflow: bare

**Comment by piraces** [comment]
Facing the same issue here... you can reproduce this by initialising a react native app with any 0.72.x version and then perform an upgrade to 0.73.0. As @achingbrain stated, the `BOOST_VERSION` has been removed and it no longer works when running expo with android.

**Comment by hollanderbart** [comment]
Why is this issue closed? This is a real issue that is resulting in non-working RN apps with version 0.73.1.

**Comment by achingbrain** [comment]
It was auto-closed because I didn't include a reproducible example.

Anyway the solution is to downgrade to 0.72.x and wait for the next expo release, which seems to be coming soon - see the [beta announcement here](https://expo.dev/changelog/2023/12-12-sdk-50-beta).

**Comment by hollanderbart** [comment]
How will that work? First wait until Expo has been released, followed by the next RN inclusion with it?

**Comment by umairb-pedal** [comment]
Honestly the problems with react native upgrades and expo are just ridiculous. So RN team decides to remove a property which fails android builds with expo almost immediately. No consultation, no testing, just push to main.

I would understand if this was a relatively small package but expo? Come on.

And now we have to wait for a major version update of expo to wait for the fix... wow
