### ISSUE TITLE
Too many screens defined. Route is extraneous

### ISSUE THREAD

**Issue by OzanBoran** [expo/expo#25869]
### Minimal reproducible example

https://snack.expo.dev/@ozanboran/indexrouting

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

**Issue Description:**

I am attempting to add multiple `Stack.Screen` components to my layout using the `expo-router` library. Everything was going smoothly until I added `index4`. Although everything works well, when I attempt to navigate to `index4` in the app, I encounter the following error:

[Layout children]: Too many screens defined. Route "index4" is extraneous.

You can find the related files under the `(home)` directory in the given Minimal Reproducible Example

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11076708
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

**Comment by trevorpfiz** [comment]
why was this closed? @OzanBoran

**Comment by OzanBoran** [comment]
It was my mistake. I had a typo somewhere and I could find that out only
after days. Sorry for bothering.
Have a great day!

Trevor Pfizenmaier ***@***.***>, 19 Ara 2023 Sal, 09:34
tarihinde şunu yazdı:

**Comment by trevorpfiz** [comment]
this issue will help other people know they made a mistake like I did!

**Comment by ruzicic** [comment]
>  this issue will help other people know they made a mistake like I did!

It did help me indeed!

**Comment by CoryWritesCode** [comment]
For those who didn't get it from just looking at the snack, I got this error when I created the file for a new tab but it was still empty.

**Comment by Emmytobs** [comment]
> For those who didn't get it from just looking at the snack, I got this error when I created the file for a new tab but it was still empty.

Exactly the same thing that happened to me. The error message could be made a little more specific.

**Comment by ondrapalan** [comment]
> For those who didn't get it from just looking at the snack, I got this error when I created the file for a new tab but it was still empty.

Thank you!

**Comment by sfrank18** [comment]
able to solve this by re-running the dev project (expo start) from the cli. Maybe the newly declared tabs are not yet recognized re-running you project might help..

**Comment by sparkle666** [comment]
I was getting this error because my route files were empty. So i used the terminal to create a couple of "profile.tsx, settings.tsx" and then linked their names to the "_layout.tsx" without creating any component on the files so it threw this error.
Once I created and exported the components in "profile and settings" it worked.

So for others check your file if its not empty and exporting the right component names.

**Comment by jvm-Monster** [comment]
> For those who didn't get it from just looking at the snack, I got this error when I created the file for a new tab but it was still empty.

Thanks, when you I read this and saw "created the file for a new tab" I remembered that I had remembered I   create a new tab called "Create" but was empty. true anyone who finds this issue will make them know they made a mistake somewhere

**Comment by leonardoprimieri** [comment]
in my case i was missing the `export default`, solved the issue

**Comment by ryanwaite28** [comment]
One more thing to add, make sure the file is exporting the component as a `default` export, not a regular export:
```javascript
// incorrect
export function Screen(props) {
  //
}

// correct
export default function Screen(props) {
  //
}
```

**Comment by Sabryxyz** [comment]
For me it was an extra stack with index as the name but there was no index file

**Comment by yalcinozer** [comment]
For me, Ctrl+save didn't solve it. I had to refresh whole app (by pressing double R on emulator or pressing R on metro bundler terminal ). I have always used RN CLI and will see how things work in Expo.

**Comment by PepeTonin** [comment]
> in my case i was missing the `export default`, solved the issue

@leonardoprimieri thank you a lot, more than an hour on that and is just that lol

**Comment by dominictobias-bullish** [comment]
Thanks for me I refactored and missed the `default` on the export too. The error is very misleading.

**Comment by k-kuzmenko** [comment]
> able to solve this by re-running the dev project (expo start)again from the CLI. Maybe the newly declared tabs are not yet recognized re-running you project might help..

I had components with default exports, yet for some reason "reloading" didn't help, but the full stop and `expo start` did, thanks
