### ISSUE TITLE
Audio is less audible on physical ios devices

### ISSUE THREAD

**Issue by DeviprasadOni** [expo/expo#25862]
### Summary

I have been using expo av for music player screen where the issue is that the audio is less audible in ios devices but the audio is working fine with andriod devices. So volume level even after we make it 100% then we hear audio that too very low volume

### SDK Version

~49.0.15

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - /usr/local/bin/node
      npm: 10.1.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

import React, { useEffect, useState } from 'react';
import { Text, TouchableOpacity, View, Slider } from 'react-native';
import { Audio } from 'expo-av';

export default function App() {
  const [sound, setSound] = useState();
  const [volume, setVolume] = useState(1.0);

  useEffect(() => {
    async function loadSound() {
      const { sound } = await Audio.Sound.createAsync(
        require('./assets/sound.mp3')
      );
      setSound(sound);
    }

    loadSound();

    // Clean up sound on unmount
    return () => {
      if (sound) {
        sound.unloadAsync();
      }
    };
  }, []);

  const playSound = async () => {
    if (sound) {
      await sound.playAsync();
      await sound.setVolumeAsync(volume); // Set initial volume
    }
  };

  const onVolumeChange = (value) => {
    setVolume(value);
    if (sound) {
      sound.setVolumeAsync(value);
    }
  };

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <TouchableOpacity onPress={playSound}>
        <Text>Play Sound</Text>
      </TouchableOpacity>
      <Slider
        style={{ width: 200, height: 40 }}
        minimumValue={0.0}
        maximumValue={1.0}
        value={volume}
        onValueChange={onVolumeChange}
      />
      <Text>Volume: {volume.toFixed(2)}</Text>
    </View>
  );
}

**Comment by DeviprasadOni** [comment]
expo av ver 13.4.1 was used

**Comment by jeveloper** [comment]
Just chiming in. IOS devices have a setting to normalize audio.
Considering checking how it sounds when its ON and OFF

https://support.apple.com/en-ca/109331
