### ISSUE TITLE
CodePush Install Mode ON_NEXT_RESUME not working on Android with ReactNativeHostWrapper

### ISSUE THREAD

**Issue by dhivyafalcon** [expo/expo#25865]
### Summary

When I try to get the instanceManager from reactnativehost CodePush Install Mode ON_NEXT_RESUME is not working.
 Wherein when I directly try to get the instanceManager without wrapping  `ReactNativeHostWrapper` and from locally created host class it is working fine. But in my case I wanted it to work with ReactNativeHostWrapper being wrapped for ReactNativeHost. Below code is not working.
   `ReactNativeHost reactNativeHost = new ReactNativeHostWrapper(context, host)); 
ReactInstanceManager reactInstanceManager = reactNativeHost.get().getReactInstanceManager();`

In this case it is working
`ReactInstanceManager reactInstanceManager = host.getReactInstanceManager();`

My host class contains the following being wrapped.
<img width="875" alt="Screenshot 2023-12-12 at 5 34 34 PM" src="https://github.com/expo/expo/assets/42573349/0248436d-3c15-43d2-a5e1-b0cae913dbfd">

### Environment

expo: 45.0.8 => 45.0.8 
      metro: ~0.67.0 => 0.67.0 
      react: 17.0.2 => 17.0.2 
      react-native: ~0.68.5 => 0.68.5

**Comment by Kudo** [comment]
hi there! sorry that i don't have much insight of how codepush was set up. could you try to create a minimal reproducible example for further investigation?
