### ISSUE TITLE
Attempted to Authentication in Expo Router with Expo docs from: https://docs.expo.dev/router/reference/authentication/

### ISSUE THREAD

**Issue by MuhammadNabeelNisarWorkspace** [expo/expo#25895]
### Minimal reproducible example

https://github.com/MuhammadNabeelNisarWorkspace/expo-error

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

In my endeavor to incorporate a fundamental authentication flow with dynamic redirects, I've turned to the latest documentation on Expo's routing capabilities: https://docs.expo.dev/router/reference/authentication/.

Upon executing my code, however, I encounter a challenging issue flagged by the warning message: **"Maximum update depth exceeded."** Regrettably, this hiccup leads to the failure or outright crash of my application.

Interestingly, I've observed that when I strategically comment out the following code block:

```jsx
if (isLoading) {
  return <Text>Loading...</Text>;
}
```

Magically, my application functions seamlessly. However, the trade-off is the necessity to repeatedly log in. Striking the right balance between a smoothly running application and a persistent authentication state appears to be the key challenge in my current GitHub community quest. Any insights or suggestions would be greatly appreciated!

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.11005911
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Hey, sorry you encountered this. This is a bug when using nested `ErrorBoundary` within `_layout` files.

You can either remove these lines https://github.com/MuhammadNabeelNisarWorkspace/expo-error/blob/2ed7a833595a5c8b2e1411b69743963b10178e3e/app/(app)/_layout.tsx#L6-L9

Or upgrade to the v3 Beta https://blog.expo.dev/expo-router-v3-beta-is-now-available-eab52baf1e3e
