### ISSUE TITLE
Enabling static rendering on web results in "EXPO_ROUTER_APP_ROOT" issue

### ISSUE THREAD

**Issue by andreaslydemann** [expo/expo#25893]
### Minimal reproducible example

sorry

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I'm running the Expo SDK 50 beta including Expo Router v3. I want to enable static rendering for web, so I've added
`web: {
    bundler: 'metro',
    output: 'static'
  },` to my `app.config.ts`file. But doing so, results in this error when I open the site in the browser:

<img width="684" alt="Skærmbillede 2023-12-13 kl  00 45 57" src="https://github.com/expo/expo/assets/15194614/521065c3-8739-4a40-84da-ff27ea6b615d">

The app runs fine on iOS, though. However, my project is a monorepo so the expo project is inside an `apps/client` folder (project was originally based on Solito) and I had to add an `index.ts` with the following content to work:

```
import { registerRootComponent } from 'expo';
import { ExpoRoot } from 'expo-router';

// Must be exported or Fast Refresh won't update the context
export function App() {
  const ctx = require.context('./src/app');
  return <ExpoRoot context={ctx} />;
}

registerRootComponent(App);
```

and my `metro.config.js` also has modifications to support the monorepo structure:

```
// Learn more https://docs.expo.io/guides/customizing-metro
/**
 * @type {import('expo/metro-config')}
 */
const { getDefaultConfig } = require('expo/metro-config');

const path = require('path');
const projectRoot = __dirname;
const workspaceRoot = path.resolve(__dirname, '../..');

const config = getDefaultConfig(projectRoot, {
  isCSSEnabled: true,
});

config.watchFolders = [workspaceRoot];

config.resolver.assetExts.push("cjs");
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];
config.resolver.sourceExts.push("svg");
config.resolver.sourceExts.push("mjs");

config.resolver.assetExts = config.resolver.assetExts.filter(
  (ext) => !config.resolver.sourceExts.includes(ext)
);

config.transformer.babelTransformerPath = require.resolve(
  "./metro.transformer.js"
);

module.exports = config;
```

I don't know exactly what the error message means. Have I missed anything?

### Environment
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Passing a custom `require.context` is not recommended. Please follow the instructions on how to set a custom directory in v3

https://docs.expo.dev/router/reference/src-directory/#custom-directory

If you have any issues, please reply back with full reproduction so we can assist you further. Its very hard to troubleshoot monorepo issues via code snippets

**Comment by macrozone** [comment]
@andreaslydemann did you solve this issue?

i ran into the same problem with a freshly installed expo app in a monorepo setup.

i am using expo router v4

**Comment by macrozone** [comment]
> Passing a custom `require.context` is not recommended. Please follow the instructions on how to set a custom directory in v3
> 
> https://docs.expo.dev/router/reference/src-directory/#custom-directory
> 
> If you have any issues, please reply back with full reproduction so we can assist you further. Its very hard to troubleshoot monorepo issues via code snippets

expo's resolution for EXPO_ROUTER_APP_ROOT does not work properly when its a monorepo, even if you are following the guidelines. I assume that is why @andreaslydemann used require.context

**Comment by drazik** [comment]
I had the same error (albeit not in the exact same use case) which led me to this issue. The only way I could find to make expo-router work with my yarn workspaces setup was to patch the `expo-router` using `yarn patch`. Here is what I did:

1. run `yarn patch expo-router`
2. open the temporary directory created by `yarn patch` in my editor
3. edit the `_ctx.android.js` file and replace its content with:

```js
export const ctx = require.context(
  "../../app",
  true,
  /^(?:\.\/)(?!(?:(?:(?:.*\+api)|(?:\+html)))\.[tj]sx?$).*\.[tj]sx?$/,
  "sync",
);
```

4. If you need other platforms, edit other platforms `_ctx.platform.js` files.
5. Save and exit editor
6. Run `yarn patch-commit -s /tmp/...` (replace `/tmp/...` with the temporary directory path)
7. Run `yarn install`

I don't think it is a long-term solution, but for now it solves the issue for me.

I hope it helps someone.

**Comment by danielriddellsh** [comment]
> I had the same error (albeit not in the exact same use case) which led me to this issue. The only way I could find to make expo-router work with my yarn workspaces setup was to patch the `expo-router` using `yarn patch`. Here is what I did:
> 
> 1. run `yarn patch expo-router`
> 2. open the temporary directory created by `yarn patch` in my editor
> 3. edit the `_ctx.android.js` file and replace its content with:
> 
> ```js
> export const ctx = require.context(
>   "../../app",
>   true,
>   /^(?:\.\/)(?!(?:(?:(?:.*\+api)|(?:\+html)))\.[tj]sx?$).*\.[tj]sx?$/,
>   "sync",
> );
> ```
> 
>  4. If you need other platforms, edit other platforms `_ctx.platform.js` files.
> 5. Save and exit editor
> 6. Run `yarn patch-commit -s /tmp/...` (replace `/tmp/...` with the temporary directory path)
> 7. Run `yarn install`
> 
> I don't think it is a long-term solution, but for now it solves the issue for me.
> 
> I hope it helps someone.

I attempted this but it doesn't render my App. It just shows a black screen
