### ISSUE TITLE
Could not resolve async-storage peer dependency error with Expo-recommended version and RN 0.73

### ISSUE THREAD

**Issue by chriszs** [expo/expo#25902]
### Minimal reproducible example

https://github.com/chriszs/test-app/compare/async-storage-compat-demo?expand=1

### Summary

The currently Expo recommended version of `@react-native-async-storage/async-storage` is `1.18.2`, which has a peer dependency on React Native `0.0.0-0 || 0.60 - 0.72 || 1000.0.0`, so `npx expo install @react-native-async-storage/async-storage` gives me the following error on the SDK 50 beta with React Native 0.73:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @statnews/mobile@2.4.2
npm ERR! Found: react-native@0.73.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.73.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.0.0-0 || 0.60 - 0.72 || 1000.0.0" from @react-native-async-storage/async-storage@1.18.
```

The async-storage peer dep was widened to include React Native 0.73 in version `1.19.6`. The [latest version](https://github.com/react-native-async-storage/async-storage/releases) is `1.21.0`.

When I upgrade I get a `The following packages should be updated for best compatibility with the installed expo version:` with a recommendation for a downgrade to 1.18.2.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.asdf/installs/nodejs/18.17.1/bin/node
      npm: 10.2.5 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/admin/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0-preview.1 => 50.0.0-preview.1 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.73.0 => 0.73.0 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: bare
```

**Comment by brentvatne** [comment]
thanks, fixed!
