### ISSUE TITLE
When exported to web it only exports static assets and not actual js bundle (SDK 50 beta)

### ISSUE THREAD

**Issue by MVNihalNarayanRao** [expo/expo#25915]
### Minimal reproducible example

see video

### Summary

See video, I run the command npx expo export -p web and it only exports static assets, the web bundle is not exported to build folder. It used to work fine in SDK v49

https://github.com/expo/expo/assets/70365929/3fa836e4-19ba-42b9-a6f8-9745f5f559ce

I am using **metro bundler**

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 25, 27, 28, 29, 30, 31, 33
        Build Tools: 28.0.0, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0
      expo: ^50.0.0-preview.1 => 50.0.0-preview.1
      react: ^18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.0 => 0.73.0
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

**Comment by marklawlor** [comment]
It is very difficult to understand/troubleshoot issue like this though video. Can you please provide a full reproduction.

I understand that this might be a private project, but we don't need the contents of your `app` folder to test exporting. You can copy/paste the `app` folder from `npx create-expo-app --template tabs`
