### ISSUE TITLE
Cannot find module 'babel-plugin-module-resolver' (SDK 50 beta)

### ISSUE THREAD

**Issue by benjaminkomen** [expo/expo#25923]
### Minimal reproducible example

See https://github.com/benjaminkomen/expo-babel-mvp and video

### Summary

After upgrading to Expo SDK 50 using `yarn add expo@next` and fixing any versions with `npx expo install --fix` and creating a new local development build for iOS, running the app in my Simulator results in the following stack trace:
```
iOS Bundling failed 207ms (app/App.tsx)
error: app/App.tsx: Cannot find module 'babel-plugin-module-resolver'
Require stack:
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/node_modules/@babel/core/lib/config/files/index.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/node_modules/@babel/core/lib/index.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/build/babel-core.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/build/transformSync.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/build/babel-transformer.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/build/transform-worker/metro-transform-worker.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/@expo/metro-config/build/transform-worker/transform-worker.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/metro/src/DeltaBundler/Worker.flow.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/<USER_NAME>/github/<APP_NAME>/node_modules/jest-worker/build/workers/processChild.js

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.
```

I solved it by running `yarn add --dev babel-plugin-module-resolver`, but I saw no mention of this in the release notes.

See also this video:

https://github.com/expo/expo/assets/12815582/e823a099-0ae5-478a-b79a-37bc0795dfad

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 34.0.0
        System Images: android-30 | ARM 64 v8a, android-30 | Intel x86_64 Atom, android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0-preview.1 => 50.0.0-preview.1
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.0 => 0.73.0
      react-native-web: 0.19.9 => 0.19.9
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
It appears you have manually specified that plugin yourself https://github.com/benjaminkomen/expo-babel-mvp/blob/ecd8c8703a4a15888026589b95d2ccd22ef38ba1/babel.config.js#L8

That plugin shouldn't be required as SDK 50 supports [Path aliases by default](https://docs.expo.dev/guides/typescript/#path-aliases)

**Comment by marklawlor** [comment]
To clarify a bit further, in SDK 49 `babel-plugin-module-resolver` used to alias `react-native-vector-icons`. In SDK 50, that alias was removed and so dependency was as well. You can see the [changelog](https://github.com/expo/expo/blob/main/packages/babel-preset-expo/CHANGELOG.md#-breaking-changes-1).

Use of the `babel-plugin-module-resolver` for general aliasing wasn't a feature of the SDK (we built Path Aliases to cover that functionality). As so, we didn't add its removal to the changelog.

Sorry for the confusion, I hoped that clears things up.

**Comment by benjaminkomen** [comment]
Ah ok, thanks for the explanation. My understanding is (but correct me if I'm wrong): in SDK 49 I could use `babel-plugin-module-resolver` without an explicit dependency, because it was a transitive dependency from SDK 49, but now you removed it, so the solution to still use it, is to add an explicit dependency on `babel-plugin-module-resolver`.

**Comment by ottob** [comment]
for the archives. I had almost the same error:
```
Failed to construct transformer:  Error: Cannot find module 'metro-react-native-babel-transformer'
Require stack:
- /myproject/node_modules/react-native-svg-transformer/index.js
- /myproject/node_modules/@expo/metro-config/build/transform-worker/metro-transform-worker.js

**Comment by Y3KC3** [comment]
@benjaminkomen yes, **babel-plugin-module-resolver** now to be able to use **ALIAS** in react-native expo with SDK 50 you must install it manually **npm install babel-plugin-module-resolver -D**

**Comment by evgenyshenets91** [comment]
> @benjaminkomen yes, **babel-plugin-module-resolver** now to be able to use **ALIAS** in react-native expo with SDK 50 you must install it manually `npx expo install babel-plugin-module-resolver`

didn't help me. I am using expo 50.
below my babel config
```
module.exports = function (api) {
  const alias = {};

  // NOTE: Mocking @react-native-firebase/analytics for local builds, since ExpoGo doesn't contain native part for Firebase
  // Follow official guide https://docs.expo.dev/guides/using-firebase/#using-react-native-firebase
  // we need to use expo-dev-client for running local app when `React Native Firebase` library is used, because
  // there some native parts used. To avoid this and run project as usual we will enable firebase analytics
  // only for production
  if (api.env() === 'development') {
    alias['@react-native-firebase/analytics'] = './__mocks__/@react-native-firebase/analytics.js';
  }

  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          extensions: [
            '.js',
            '.jsx',
            '.ts',
            '.tsx',
            '.android.js',
            '.android.tsx',
            '.ios.js',
            '.ios.tsx',
          ],
          alias,
        },
      ],
      'react-native-reanimated/plugin', // Reanimated plugin has to be listed last.
    ],
  };
};

```
I was trying to remove  'module-resolver' at all - didn't help.
Was trying to remove and install babel-plugin-module-resolver as a dependency - didn't help.


Locally it works with suggested solutions from video, like add this dependency.
Any suggestions?

**Comment by evgenyshenets** [comment]
So this is fixed. I forgot to add manually in my monorepo mobile app package.json this deps. But appeared another issue: 

error: Cannot resolve @babel/runtime/helpers/interopRequireDefault

**Comment by benjaminkomen** [comment]
@evgenyshenets , this issue is closed, it was not a bug in Expo. Maybe you can ask for help in [Discord](https://discord.com/invite/expo) for your specific issue.

**Comment by zero19124** [comment]
below worked to me 
remove       "expo-router/babel" in babel config file
and install npx expo install babel-plugin-module-resolver
npx expo start

**Comment by ChamaraWP** [comment]
> To clarify a bit further, in SDK 49 `babel-plugin-module-resolver` used to alias `react-native-vector-icons`. In SDK 50, that alias was removed and so dependency was as well. You can see the [changelog](https://github.com/expo/expo/blob/main/packages/babel-preset-expo/CHANGELOG.md#-breaking-changes-1).
> 
> Use of the `babel-plugin-module-resolver` for general aliasing wasn't a feature of the SDK (we built Path Aliases to cover that functionality). As so, we didn't add its removal to the changelog.
> 
> Sorry for the confusion, I hoped that clears things up.

Do we still need to manually install `module-resolver` if we use path aliases in `babel.config.js`? If I remove `module-resolver` from `babel.config`, my app doesn't work even though it says it supports default path aliases in `tsconfig` on SDK50. Are these path default path aliases and `babel.config.js` config path aliases considered as two different things?

**Comment by veer-anonymous** [comment]
npm install --save-dev @babel/plugin-transform-private-property-in-object
