### ISSUE TITLE
  java.lang.UnsupportedOperationException: Type not found: class expo.modules.barcodescanner.BarCodeScannerView$orientationListener$1

### ISSUE THREAD

**Issue by Shhreyas** [expo/expo#25941]
### Minimal reproducible example

when I enable proguard-rules. the realse app as well as debug app gone crash. I have attched code and used version below please check it.

### Dependency's  version :-

    "react": "^18.2.0",
    "react-native": "^0.71.11",
    "expo": "^48.0.19",
    "expo-av": "^13.2.1",
    "expo-barcode-scanner": "^12.7.0",
    "expo-camera": "13.2.0",
    "expo-file-system": "15.2.2",
    "expo-image-picker": "^14.1.1",
    "expo-keep-awake": "^12.0.1",
    "expo-localization": "^14.1.1",
    "expo-media-library": "^15.6.0",
    "expo-notifications": "^0.18.1",
    "expo-permissions": "^14.1.1",
    "expo-secure-store": "^12.1.1",
    "expo-sharing": "^11.2.2",
    "expo-task-manager": "^11.1.1",
    
    
###     proguard-rules :-
    
Keep the classes related to MultiDex
-keep class androidx.multidex.** { *; }

 Keep the class MainApplication and its methods
-keep class come.package.MainApplication { *; }

If you have other custom classes or packages, keep them as well
-keep class come.package.MainActivity { *; }

Keep the ReactApplication interface and its methods
-keep interface com.facebook.react.ReactApplication { *; }

 Keep all classes implementing ReactApplication
-keep class * implements com.facebook.react.ReactApplication { *; }

 Keep the native methods in React Native classes
-keepclassmembers class * {
    native <methods>;
}

Keep R class for resources
-keepclassmembers class **.R$* {
    public static <fields>;
}

Keep the default constructors for activities and services
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.content.Intent);
}

 Keep the entry point for the application
-keep class com.facebook.react.** { *; }

 Keep React Native related classes
-keep class com.facebook.react.** { *; }
-keep class com.swmansion.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }

 Keep your models, if you have any
-keep class come.package.models.** { *; }
 Keep native modules
-keep class * implements com.facebook.react.bridge.NativeModule
-keepclassmembers class * { @com.facebook.react.bridge.ReactMethod <methods>; }

 Keep names of classes/members used by React Native
-keepnames class * { *; }
-keepnames interface * { *; }

 Don't optimize JavaScript code
-dontoptimize
-dontwarn com.facebook.react.**
-dontwarn javax.annotation.**

-keep class com.facebook.react.devsupport.** { *; }
-dontwarn com.facebook.react.devsupport.**

React Native
Keep our interfaces so they can be used by other ProGuard rules.
 See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation interface com.facebook.common.internal.DoNotStrip

Flipper
-keep class com.facebook.flipper.** { *; }
-dontwarn com.facebook.flipper.**

 Add any additional Flipper plugins you are using
-keep class com.facebook.flipper.plugins.network.** { *; }
-dontwarn com.facebook.flipper.plugins.network.**

expo 
-keep class expo.modules.** { *; }

![Screenshot 2023-12-14 at 4 19 39 PM](https://github.com/expo/expo/assets/109290706/ca270689-8dbd-460b-b579-f9a0ae3c6c3a)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.19 => 48.0.20 
      react: ^18.2.0 => 18.2.0 
      react-native: ^0.71.11 => 0.71.13 
    npmGlobalPackages:
      eas-cli: 5.1.0
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by brentvatne** [comment]
hi there! be sure to share a minimal reproducible example and test on the latest sdk release as well
