### ISSUE TITLE
Static export web SDK 50

### ISSUE THREAD

**Issue by revolution42** [expo/expo#25952]
### Minimal reproducible example

https://github.com/revolution42/expo-export-error

### Summary

Exporting using expo export -p web when static export is set does not copy any javascript.

### Environment

I recieved the error
Error: Command failed: wmic os get Caption
ERROR:
Description = Invalid namespace

**Comment by brentvatne** [comment]
@revolution42 - can you make a more minimal reproducible example? this example includes a bunch of libraries that are unrelated to this repository

**Comment by revolution42** [comment]
I have removed the extra packages

**Comment by marklawlor** [comment]
@revolution42 Can you please follow the issue template and run `npx expo-env-info`

When I test your repo it exports without any error, which suggests this is an environmental issue. So we really need the output of that command to understand your environment

**Comment by revolution42** [comment]
Hello Mark,

I managed to fix the error with the info (I had a windows update that was
awaiting)

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22635
    Binaries:
      Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0
      babel-preset-expo: ^10.0.0 => 10.0.0
      expo: ^50.0.0-preview.3 => 50.0.0-preview.3
      metro: ~0.76.7 => 0.76.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.0 => 0.73.0
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

Mine exports html files there is no errors reported or show however there
is no javascript in the files

**Comment by marklawlor** [comment]
Can you please attach a `.zip` of your `dist` folder. 

Given your example project, the only expected JS file should be `dist/_expo/static/js/web/_entry-<hash>.js`. All other files should be static `.html` or asset files.

**Comment by revolution42** [comment]
Here you go.

I will try and build it in ubuntu and see if i get any different result

**Comment by revolution42** [comment]
It works correctly when I use the exact same folder using Windows WSL and
Ubuntu

**Comment by kitten** [comment]
This was fixed with the changes in #26008 which are now released in SDK 50. Once upgrading `expo` to the stable version of `expo@^50.0.0` this issue is resolved and exports are written correctly on Windows ✌️ 

Let me know if that's still causing issues though or if you'd like us to take another close look at this!
