### ISSUE TITLE
expo router tab not accepting overlay 

### ISSUE THREAD

**Issue by paysnugtech** [expo/expo#25958]
### Minimal reproducible example

sdk 49

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Expo router tabs not allowing any overlay on it and there is no documentation on how to adjust it 

this is my  _layout for app->(tabs)->_layout.js

import { Tabs } from "expo-router";
import customTheme from "../../component/Theme/CustomTheme";
import Icon from "react-native-vector-icons/Feather";

const Taabs = () => {
    const theme = customTheme();
   
    return (
        <Tabs
            screenOptions={{
                tabBarStyle: {
                    height:70,
                    backgroundColor: theme.tab,
                    paddingBottom:15

                },
                tabBarLabelStyle: {
                    fontSize: 12,
                    fontWeight: "500",
                },
            }}
        >
            <Tabs.Screen name="home" 
            options={{
                
                headerShown: false,
                
                tabBarIcon: ({ color = "", size = 10 }) => (
                    <Icon name="home" color={color} size={size} style={{marginBottom:-10, }} />
                ),
                title: "Home",
                tabBarInactiveTintColor: theme.tabBarInactiveTintColor,
                tabBarActiveTintColor: theme.tabBarActiveTintColor,
                

            }} />
            <Tabs.Screen name="history" options={{
                headerShown: false,
                tabBarIcon: ({ color = "red", size = 10 }) => (
                    <Icon name="bar-chart-2" color={color} size={size}  style={{marginBottom:-10}} />
                ),
                title: "History",
                tabBarInactiveTintColor: theme.tabBarInactiveTintColor,
                tabBarActiveTintColor: theme.tabBarActiveTintColor,
            }} />

            <Tabs.Screen name="services" options={{
                headerShown: false,
                tabBarIcon: ({ color = "red", size = 10 }) => (
                    <Icon name="layers" color={color} size={size}  style={{marginBottom:-10}} />
                ),
                title: "Services",
                tabBarInactiveTintColor: theme.tabBarInactiveTintColor,
                tabBarActiveTintColor: theme.tabBarActiveTintColor,
            }} />

            <Tabs.Screen name="settings" options={{
                headerShown: false,
                tabBarIcon: ({ color = "red", size = 10 }) => (
                    <Icon name="settings" color={color} size={size}  style={{marginBottom:-10}} />
                ),
                title: "Setting",
                tabBarInactiveTintColor: theme.tabBarInactiveTintColor,
                tabBarActiveTintColor: theme.tabBarActiveTintColor,
            }} />

        </Tabs>

    )
}
export default Taabs;

my layout.js

import React,{useRef} from "react";
import { View, Text, SafeAreaView,StyleSheet,TextInput,TouchableOpacity,ScrollView,TouchableWithoutFeedback } from "react-native";
import customTheme from "../../component/Theme/CustomTheme";
import Icon1 from 'react-native-vector-icons/Ionicons'; 
import Icon3 from "react-native-vector-icons/Feather";
import { Modalize } from 'react-native-modalize';

const history = () => {
    const theme = customTheme();
    const modalizeRef = useRef(null);
    const onFilterPress = (event) => {
        event.persist();
        modalizeRef.current?.open();
    };
    
    return (
    <SafeAreaView style={{ flex: 1, backgroundColor: theme.background }}>
          <View style={[styles.container]}>
            <View style={[styles.headnote,{marginBottom:20}]}>
                <Text>Arrow Back</Text>
                <Text >center</Text>
            </View>
           
            <View style={{ flexDirection: 'row', alignItems: 'center'}}>
      <TextInput
        style={{ flex: 1, borderWidth: 1, borderRadius: 5, height:45}}
        placeholder="Type here..."
      />
     <TouchableWithoutFeedback onPress={onFilterPress}>
                    <View>
                        <Icon1 name="filter" size={35} color="red" style={{ paddingLeft: 10, marginTop: -10 }} />
                    </View>
                </TouchableWithoutFeedback>
    </View>
            <View>

            </View>
            <ScrollView contentContainerStyle={{ ...styles.scrollContainer, paddingBottom: 400 }} showsVerticalScrollIndicator={false}>

<View style={styles.transaction}>

    <View style={{ backgroundColor: theme.quickbox, borderRadius: 20, height: 75, marginBottom: 15, }}>
        <View style={[styles.headnote, { margin: 15, marginTop: 20 }]}>
            <View style={styles.trxtype}>
            <Icon3 name="arrow-up-right" size={25}  color="red"   style={[{ backgroundColor: `${theme.ciecledash}${theme.circleopacity}` }, styles.circleicon]}/>

                <View>
                    <Text style={{ marginLeft: 10, color: theme.textDefault, fontSize: 15, fontWeight: "600" }}>Transfer To Tunde</Text>
                    <Text style={{ marginLeft: 10, color: "#9E9EC6", fontSize: 11, fontWeight: "500" , marginTop:5}}>13 Dec 2023 10:35 PM</Text>
                </View>
            </View>
            <Text style={{ color: theme.textDefault, fontWeight: "600" }}>-₦20,000,000</Text>
        </View>
    </View>

    <View style={{ backgroundColor: theme.quickbox, borderRadius: 20, height: 75, marginBottom: 15, }}>
        <View style={[styles.headnote, { margin: 15, marginTop: 20 }]}>
            <View style={styles.trxtype}>
            <Icon3 name="arrow-down-left" size={25}  color="green"   style={[{ backgroundColor: `${theme.ciecledash}${theme.circleopacity}` }, styles.circleicon]}/>
                <View>
                    <Text style={{ marginLeft: 10, color: theme.textDefault, fontSize: 15, fontWeight: "600" }}>Wallet Fund</Text>
                    <Text style={{ marginLeft: 10, color: "#9E9EC6", fontSize: 11, fontWeight: "500" , marginTop:5}}>13 Dec 2023 10:35 PM</Text>
                </View>
            </View>
            <Text style={{ color: theme.textDefault, fontWeight: "600" }}>-₦20,000,000</Text>
        </View>
    </View>

    {/* Add other transaction components here */}
</View>

</ScrollView>
          </View>
          <Modalize ref={modalizeRef} modalHeight={300}  >
               
                <Text>Filter options go here</Text>
            </Modalize>
        </SafeAreaView>
    )
}

![expotab](https://github.com/expo/expo/assets/69718298/efaf0693-5d03-4017-9e3d-bd0368aa1c3c)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 21.3.0 - /usr/local/bin/node
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2023.07.03.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/mac/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.3 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
@paysnugtech I understand your struggling, but sharing code snippets in this manner is very difficult on our end and very error prone. A much simply method of sharing code is to create a repo and simply share it. If its a private project run `npx create-expo-app --template tabs` and modify the template.

I'm going to close this as an invalid reproduction, but if you provide a link to a repo I'll reopen the ticket
