### ISSUE TITLE
Need api to clear/rewrite router history.

### ISSUE THREAD

**Issue by RohitKaushal7** [expo/expo#25960]
### Minimal reproducible example

NA

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I am using expo directory based app router.

**Issue**
`expo-router` doesn't provide any function to clear or rewrite the router stack history. similar to `@react-navigation/native`
```ts
navigation.reset({
  index: 0,
  routes: [{name: 'dashboard'}],
});
```
**Use Case**
consider this navigation path  
`welcome > signup > onboarding > dashboard`
after reaching dashboard, if user pressed back button, user goes back to `onboarding`. I want to rewrite the router history at this point so user exits app or goes to a different page.

Can't user `router.replace()` instead of `push` everywhere because I need the routing features in onboarding and signup.

In the docs it says [here](https://docs.expo.dev/router/migrate/from-react-navigation/#reset-navigation-state), this will reset the router state, but it is throwing error "the action RESET was not handled by any navigator. I am using expo app directory router.

I couldn't find out the solution for this in the docs or internet if it already exists. Any help regarding this will be apreciated. 

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22631
    Binaries:
      Node: 19.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        Android NDK: 23.0.7196353-beta2
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    Expo Workflow: bare
```

**Comment by adscud** [comment]
@RohitKaushal7 Did you achieve to rewrite the history ?

**Comment by RohitKaushal7** [comment]
No I cloudn't do this.

**Comment by edwinvrgs** [comment]
It seems [this](https://github.com/expo/expo/discussions/28485) would help. I haven't tried out myself.
