### ISSUE TITLE
SDK 50 `bun create expo-app` "Error: No safe area value available."

### ISSUE THREAD

**Issue by peterferguson** [expo/expo#25961]
### Minimal reproducible example

https://github.com/peterferguson/testing-eas-hermes-ios-build-failure

### Summary

Immediately after using bun & `bun create expo-app --template tabs@beta` to create an SDK repo I get an error with the SafeAreaProvider

![image](https://github.com/expo/expo/assets/7002211/1f09062a-0910-4590-8071-ad71eaced8e4)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.0 - /opt/homebrew/bin/npm
      Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.3 => 50.0.0-preview.3 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.0 => 0.73.0 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed

**Comment by peterferguson** [comment]
Works fine with yarn v1 having trouble with yarn v2 & v3 though

**Comment by erickreutz** [comment]
Check your lockfile and ensure that only one version of react-native-safe-area-context is being installed

**Comment by likeSo** [comment]
Same problem here. I just tried this, and also no luck...
```json
  "resolutions": {
      "react-native-safe-area-context": "4.8.2"
  },
```

**Comment by likeSo** [comment]
I just realized that every `react-navigation` packages, such as `drawer`, `bottom-tab`, contains their own `node_modules` folder, and seems like `drawer` package is running code from `node_modules/@react-navigation/drawer/node_modules/react-native-safe-area-context`

I ran `rm -rf node_modules/@react-navigation/drawer/node_modules` and restarted my project, it works fine!

I don't know whose problem that is

**Comment by Liba2** [comment]
i had the same issue here @peterferguson ! did you solved ? ... @likeSo I didn't understand your "solution", its healthy working your app ? ... thanks for all in advance

**Comment by Liba2** [comment]
@likeSo another question ... after this rm -rf ... could you use useSafeAreaInsets ? without errors ?

**Comment by likeSo** [comment]
@Liba2 Of course! Just make sure there is only one react-native-safe-area-context package inside your project!
