### ISSUE TITLE
[expo-router 3] AssertionError [ERR_ASSERTION]: Chunk containing module not found:

### ISSUE THREAD

**Issue by rifaldhiaw** [expo/expo#25969]
### Minimal reproducible example

https://github.com/rifaldhiaw/expo-router-asyncRoute

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Failed to export to web platform when asyncRoutes is enabled and there are routes in a group folder `(grouped)`.
```
     [
        "expo-router",
        {
          "root": "./src/app",
          "asyncRoutes": {
            "web": true,
            "default": "development"
          }
        }
      ]
 ```

When I run `npx expo export -p web` I get an error:
```
AssertionError [ERR_ASSERTION]: Chunk containing module not found: /Documents/expo-router-asyncRoute/src/app/(admin)/login.js
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
      Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
      npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /Users/ruangguru/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.1
        System Images: android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.3 => 50.0.0-preview.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.0 => 0.73.0
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by GustavoBonfimS** [comment]
I Faced the same issue when exporting to web.

**Comment by EvanBacon** [comment]
This happens because the async modules have parentheses in the name, I'm working on a fix for this now.
