### ISSUE TITLE
[Expo Router 3] Shows < (tabs) when navigation from a tab to a card

### ISSUE THREAD

**Issue by Kief5555** [expo/expo#25976]
### Minimal reproducible example

`yarn create expo-app -t tabs@beta issue-25976
&& cd issue-25976
&& sed -i "" "s/presentation: 'modal'/presentation: 'card'/" app/_layout.tsx`

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When using navigation (called from `useNavigation`) either from `expo-router` OR react navigation to navigate to a card, it successfully does it with a minor problem, it shows the header back title as `(tabs)`. Manually setting `headerBackTitle` in the card doesn't seem to have any effect. 

Heres an example:
![image](https://github.com/expo/expo/assets/67562560/f842187c-6f17-41ba-8cb6-8c96d444d172)

My expected result was for it to show the tab name or the string of what I set `headerBackTitle` to. In this case, nothing. Just the icon needed. 

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.23601
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.4 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ^50.0.0-preview.3 => 50.0.0-preview.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.0 => 0.73.0
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

(I'm using windows 11, no idea why it says 10)

**Comment by wodin** [comment]
According to the README in the repository mentioned above, this was tested on iOS.

I can confirm that if I run it in Expo Go on an iOS Simulator then I get the problem. I do not see the microphone icon, but if I press to the right of the text field then it navigates to Settings the modal and shows the back link as "< (tabs)"

On Android it does not show "(tabs)". It just shows a back button and the "Settings" title

On Web it works the same as on Android.

**Comment by wodin** [comment]
Here is a more minimal reproducible example:

```console
$ yarn create expo-app -t tabs@beta issue-25976
$ cd issue-25976
$ sed -i "" "s/presentation: 'modal'/presentation: 'card'/" app/_layout.tsx
```
Then open it in Expo Go in the iOS Simulator and tap the Info icon to open the modal

**Comment by Kief5555** [comment]
Just found out how to fix it for now.


```js
	useEffect(() => {
		navigation.setOptions({headerBackTitle: 'a'});
	}, []);
	
``` You can place this code within the modal.tsx

**Comment by Kief5555** [comment]
Hi,

No rush, but is there any progress? This issue is really critical for my application.

**Comment by Kief5555** [comment]
Looking at it, this may be an issue from `react-navigation/react-navigation`

**Comment by natehoffy** [comment]
Still very much experiencing this and a fix would be awesome

**Comment by marklawlor** [comment]
Expo Router shows the name of the screen. For your tabs, they are in the screen called `(tabs)`. If you wish to rename a screen you can do so via one of these methods

- Set the screen inside a navigator e.g `<Stack.Screen name="(tabs)" screenOptions={{ headerTitle: "Tabs" }}>`
- Set the name using `<Stack.Screen />` inside the `_layout`

```
export default function MyLayout() {
  return (
    <>
      <Stack.Screen options={{ headerTitle: "Tabs" }}
     <Tabs />
    </>
  )
} 
```

- Use the imperative API to set the back title (from a child screen)

```
useEffect(() => {
	navigation.setOptions({headerBackTitle: 'Tabs'});
}, []);
```

- Use the imperative API to set the title (in the layout)

```
useEffect(() => {
	navigation.setOptions({headerTitle: 'Tabs'});
}, []);
```

**Comment by Kief5555** [comment]
I believe the default and expected behavior should be to show the previous screen tab name. This was the case in other SDK version before this issue was created. For example, one of the tab name could be called `Home` when pushing a screen, the back button label should say `Home`.

**Comment by sergio-alifano** [comment]
Why is this issue closed? It seems to be a moderate level bug to me.
Has anyone found a workaround?

**Comment by jrusso1020** [comment]
I was able to do this in my stack to update the headerTitle when pressing back. I set it to '' so that there is no value shown but you can update `headerTitle` to whatever you want

```
function RootLayoutNav() {
  return (
    <>
      <Stack>
        <Stack.Screen
          name="(tabs)"
          options={{ headerShown: false, headerTitle: '' }}
        />
        <Stack.Screen name="+not-found" />
      </Stack>
      <Toast />
    </>
  );
}
```

**Comment by Kief5555** [comment]
> I was able to do this in my stack to update the headerTitle when pressing back. I set it to '' so that there is no value shown but you can update `headerTitle` to whatever you want
> 
> 
> 
> ```
> 
> function RootLayoutNav() {
> 
>   return (
> 
>     <>
> 
>       <Stack>
> 
>         <Stack.Screen
> 
>           name="(tabs)"
> 
>           options={{ headerShown: false, headerTitle: '' }}
> 
>         />
> 
>         <Stack.Screen name="+not-found" />
> 
>       </Stack>
> 
>       <Toast />
> 
>     </>
> 
>   );
> 
> }
> 
> ```

This was the proposed solution. However, it should not be the default approach to this. The ideal and default should just not show (tabs)

**Comment by Kief5555** [comment]
@marklawlor Can we please re-open this issue as I and many others believe that the solution to the issue should just be default to not show `(tabs)` 

Thanks.

**Comment by marklawlor** [comment]
Expo Router doesn't change how React Navigation's components work, there hasn't been an SDK version where we did not display another title.

In Expo Router, the filename is the screen name. Because React Navigation shows the screen name by default, that is why you see `(tabs)`.

I don't believe you suggestion of showing the previous screen as particularly useful as well, as we should still be displaying the filename (all lowercase, may contain escaped characters) and not a human-friendly title. So considering the large majority of people will change to change the title from a filename to a human readable title, I'm not sure that changing how it currently works is the best idea

What we actually need is a better way to provide screen options (such as setting the title) within route files, so you no longer need to define them in a _layout. We're currently working on this

The automatic titles work better in vanilla React Navigation because people use human-friendly screen names, but Expo Router uses filenames.
