### ISSUE TITLE
Update Reanimated version to 3.6.1

### ISSUE THREAD

**Issue by SebaMutuku** [expo/expo#25984]
### Minimal reproducible example

Current reanimated version 3.3.0 lags on Android

### Summary

See this issue https://github.com/software-mansion/react-native-reanimated/issues/5492

### Environment

Android

**Comment by Kudo** [comment]
hi there! with [development builds](https://docs.expo.dev/develop/development-builds/introduction/) you can literally install any libraries you want, even the latest reanimated@3.6.1. 
to suppress the warning when `npx expo start` or `npx expo install`, you can add reanimated to the `expo.install.exclude` of package.json like mentioned at https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation.

i hope this information helps you to try out newer reanimated. thanks!

**Comment by SebaMutuku** [comment]
@Kudo excluded it but getting the error 
`Error: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.6.1 vs 3.3.0).`
My config 
```
 "expo": {
    "install": {
      "exclude": [
        "expo-updates",
        "expo-splash-screen",
        "react-native-reanimated"
      ]
    }
  },
```

**Comment by Kudo** [comment]
hi there! first of all, installing newer reanimated on expo-go is not supported, you should use development builds instead.
if you have development builds already, you have to rebuild your app. maybe you can try `npx expo prebuild --clean` to purge all your existing android/ios folder and rebuild everything.

**Comment by Darrick-Oliver** [comment]
What if we want to deploy a newer version of `reanimated` to an app on TestFlight/App Store? I'm getting `expo doctor` errors saying "Check that packages match versions required by installed Expo SDK" anytime I try to run `eas build` in a production profile.

**Comment by SebaMutuku** [comment]
@Kudo I am getting the same errors experienced by @Darrick-Oliver . My app is in production

**Comment by imraann0** [comment]
@Darrick-Oliver @SebaMutuku did you guys manage to find a solution? did you manage to build for production for newer versions of reanimated ?

**Comment by Darrick-Oliver** [comment]
Hey @imraann0, I never found a solution. Ultimately I stopped using expo because of issues like this.
