### ISSUE TITLE
Support audio recording

### ISSUE THREAD

**Issue by ohtangza** [expo/expo#26]
Hello! I am new here. 

I always thought that there should something like Ionic in React Native, and I guess I found a charm!

Is there any plan to support audio recording?

I guess the advent of WebRTC and openness of automatic speech recognition makes the demand for audio recording (with streaming) surge thesedays.

Any road map for this?

**Comment by brentvatne** [comment]
we don't have this scheduled for any time soon but agree it will be nice to have!

**Comment by ohtangza** [comment]
Thanks for your reply. We plan to use this as a part of course in our graduate school, and the support for sensors is very important. I believe byte stream should be also supported both for audio and video :)

**Comment by terribleben** [comment]
Thanks for the suggestion! Recording audio is now in our pipeline, as a followup for [basic playback support](https://docs.getexponent.com/versions/latest/sdk/audio.html), but we don't have a confirmed release date yet.

**Comment by Rhjulskov** [comment]
Hi @terribleben, 

How's the near future regarding this issue?
Do you have any estimate of an release date? :)

Great work 👍

**Comment by terribleben** [comment]
Unless something goes terribly wrong, this is likely to be released with our upcoming SDK in mid-April. 🎉

**Comment by Rhjulskov** [comment]
Sounds perfect! 🚀 
Thank you for the quick response!

**Comment by terribleben** [comment]
This was released today with SDK 16: https://docs.expo.io/versions/v16.0.0/sdk/audio.html

**Comment by ohtangza** [comment]
@terribleben Thanks! I am using Expo for educating students with full of joy :)
