### ISSUE TITLE
MapView SDK - Warning: View.propTypes has been deprecated

### ISSUE THREAD

**Issue by Palisand** [expo/expo#260]
On your next release, can you please update your fork of **`react-native-maps`** so that the warning stated in the title of this issue will stop being reported.

How can I suppress the warning in the meantime?

**Comment by brentvatne** [comment]
See https://facebook.github.io/react-native/docs/debugging.html#warnings for information on suppressing warnings.

cc @ide re: react-native-maps update

**Comment by ide** [comment]
You can suppress warnings with this https://stackoverflow.com/a/39050160/454967 in the meantime.

**Comment by Palisand** [comment]
@brentvatne and @ide thanks guys.

**Comment by ide** [comment]
react-native-maps will be updated in Expo SDK 18.

**Comment by facuescobar** [comment]
@ide I am still getting this error on Expo v18 :/ 

```
    "expo": "^18.0.4",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
  },
```

should this issue be re opened?

**Comment by ide** [comment]
@facuescobar Thanks for the heads up. We've published expo 18.0.7 to npm, which depends on react-native-maps 0.15.3, which has the prop-types fix. I've tested in a sample app that warnings that used to be there are now gone.

**Comment by facuescobar** [comment]
thanks @ide ! I just created a new project and added v18.0.7 to test it and the Warning is gone!

**Comment by ide** [comment]
18.0.7 had some bugs in it so we rolled that release back. This warning will be fixed in some future release though.

**Comment by facuescobar** [comment]
yes, I saw that 18.0.7 wasn't in npm anymore, I hope you guys can get this fix live soon!

thanks for your time @ide!
