### ISSUE TITLE
[expo-av] looped video will keep requesting source in bare expo?

### ISSUE THREAD

**Issue by lovegaoshi** [expo/expo#26007]
### Minimal reproducible example

https://github.com/lovegaoshi/videotest/tree/e221626d55d82d0a61cc0b8558f94d548a1036d9

### Summary

I found on Android release, the expo-av module (video) will keep requesting the source when playing in loop; the screenshot below shows 8 requests but it will keep going until socket is closed. debug and httpToolkit doesnt play because of some port conflict issues so I can't tell.
![image](https://github.com/expo/expo/assets/106490582/a365d6fa-61c5-498e-8ca7-aede75098fd2)
[when using the managed workflow this behavior does not occur.](https://github.com/lovegaoshi/videotest/tree/156aed34221d8f6171dcd2b10b114bf192a52f99)
I'm also seeing the same behavior using react-native-video v6, though not in v5.2.1, if it's any relevant.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by singhayush1403** [comment]
Is there any fix for this? Happening with me as well

**Comment by lovegaoshi** [comment]
[you can introduce a simpleCache like how i did for rnv](https://github.com/react-native-video/react-native-video/pull/3514)

**Comment by lovegaoshi** [comment]
think issue still exists but im gonna close if its not being worked on
