### ISSUE TITLE
Issue using react-native-gesture-handler on SDK31 for Android on Snack

### ISSUE THREAD

**Issue by chunghe** [expo/expo#2600]
### Environment
android

### Steps to Reproduce
here's the snack:
https://snack.expo.io/@chunghe/mature-candies

If you pan on the red area, it will show 'Unsupported top level event type "onGestureHandlerStateChange" dispatched'

![screenshot_20181106-003022](https://user-images.githubusercontent.com/78242/48011692-4c1c5980-e15b-11e8-9708-1a26164cb1c5.png)

### Expected Behavior
should works properly and console.log('onHandlerStateChange')

related ticket: https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-431826221, it seems current version of react-native-gesture-handler requires `react-native` version 0.57.3(expo 31 ships 0.57.1), and react version `16.6.0-alpha.8af6728` (expo 31 ships with 16.5.0)

**Comment by brentvatne** [comment]
hi! this is a bug with snack, not with react-native-gesture-handler or expo outside of snack. you can verify this by running the "Expo APIs" example in the search tab of the expo client on android. cc @tcdavis

**Comment by brentvatne** [comment]
i created a brand new project with `expo init` and used react-native-gesture-handler in it (via react-navigation), i had no issues: https://github.com/brentvatne/lol-react-navigation-5208

**Comment by tcdavis** [comment]
And resolved in snack, sorry for the regression!

**Comment by chunghe** [comment]
you are right. appreciate your valuable feedback!
