### ISSUE TITLE
[Expo Router] No option to disable deeplinking without removing the schema from the app.json

### ISSUE THREAD

**Issue by JustJoostNL** [expo/expo#26003]
### Minimal reproducible example

Create a expo-router project using the template, and see that it is impossible to disable deeplinking for screens (or at all) without removing the schema from the app.json (which may be unwanted).

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Currently it is impossible to disable deeplinking for screens (or at all) without removing the schema from the app.json (which may be unwanted).

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22623
    Binaries:
      Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 49.0.21 => 49.0.21
      metro: ~0.80.1 => 0.80.1
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: 0.19.9 => 0.19.9
    Expo Workflow: managed
```

**Comment by los-ko** [comment]
This would be nice to have, since expo routers deep linking doesnt always work correctly.

**Comment by JustJoostNL** [comment]
Yeah this, and some (including me) may want to create custom logic, and do not want the default deeplinking to run as well since that would result in duplicate behavior.
