### ISSUE TITLE
[SDK 50][Android] - expo-notifications doesn't work - prebuild Exception in HostObject::get for prop 'NativeUnimoduleProxy': expo.modules.notifications.ModuleNotFoundException: class expo.modules.interfaces.taskManager.TaskManagerInterface module not found

### ISSUE THREAD

**Issue by ahanusek** [expo/expo#26058]
### Minimal reproducible example

https://github.com/ahanusek/expo-notifications-bug

### Summary

1. Create app via create-expo-app 2.1.1.
2. I've selected bun as package manager, but with pnpm had the same problem.
3. Install expo-notifications and add to plugin array in app.json
4. Run expo prebuild command
5. Run expo run:android

App will crash on init:

```
Android Bundling complete 5141ms (node_modules/expo/AppEntry.js)
 ERROR  Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': expo.modules.notifications.ModuleNotFoundException: class expo.modules.interfaces.taskManager.TaskManagerInterface module not found, js engine: hermes
 ```
 
 deps:
 ```
 "dependencies": {
    "expo": "~50.0.0-preview.4",
    "expo-notifications": "0.27.2",
    "expo-status-bar": "~1.11.0",
    "react": "18.2.0",
    "react-native": "0.73.0"
  },
 ``` 

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
      Watchman: 2022.01.31.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/andrzejhanusek/.rubies/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.4 => 50.0.0-preview.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.0 => 0.73.0 
    npmGlobalPackages:
      eas-cli: 5.6.0
    Expo Workflow: bare

**Comment by Raigen** [comment]
I am getting the same error.
Building a preview apk locally and installing it on my phone causes the app to crash immediately with the mentioned error in logcat.
Building a dev client for android (on eas) and installing it on my phone works at first. But once I do `expo start` and try to connect it fails and displays an error on full page with "Reload" and "Go to home" button at the bottom.
```
Unable to load script. make sure you're either running Metro (run npx 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
```
iOS simulator dev client works fine, but simulator has no notifications anyway. I might be able to test on a physical iOS device today.

**Comment by MAgungHKM** [comment]
I'm also getting the same error.
Tested on prebuild Expo SDK 50 project without `expo-notifications` and it run successfully.
Installed `expo-notifications` and rebuild/rerun, greeted with the same error after the app launched.

![Screenshot_1703150916](https://github.com/expo/expo/assets/48979952/e2e729fe-6066-455c-87db-acdbac1b8305)

**Comment by MAgungHKM** [comment]
After an hour of looking into it, this issue seems to be fixed after I install `expo-task-manager`. Why is this package not included when generating `expo` project or when installing `expo-notifications` ?

**Comment by radko93** [comment]
I also have this issues in an non expo project.

**Comment by behenate** [comment]
Hi everyone, the PR above should fix the issue. For now the easiest workaround should be installing `expo-task-manager` and rebuilding your apps
