### ISSUE TITLE
[docs] Missing imports in SQLite example

### ISSUE THREAD

**Issue by jcubic** [expo/expo#26062]
### Summary

The example in SQLite is missing imports. 

This is how the example should look like (I think, I don't get any TS errors from my editor):

```typescript
import * as FileSystem from 'expo-file-system';
import { Asset } from 'expo-asset';
import * as SQLite from 'expo-sqlite';

export async function openDatabase(pathToDatabaseFile: string): Promise<SQLite.WebSQLDatabase> {
  if (!(await FileSystem.getInfoAsync(FileSystem.documentDirectory + 'SQLite')).exists) {
    await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'SQLite');
  }
  await FileSystem.downloadAsync(
    Asset.fromModule(require(pathToDatabaseFile)).uri,
    FileSystem.documentDirectory + 'SQLite/myDatabaseName.db'
  );
  return SQLite.openDatabase('myDatabaseName.db');
};
```

The deprecated type is 

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/sqlite/

### Anything else?

It also uses a deprecated type `SQLite.WebSQLDatabase`. I'm not sure what should be used instead. I'm just learning to use SQLite with expo.

I've edited the example in: #26060

**Comment by amandeepmittal** [comment]
The PR #26060 was merged so closing this issue now. Once again, thank you for your contribution!
