### ISSUE TITLE
Clicking screen content always makes router jump back to 1st Tab

### ISSUE THREAD

**Issue by maks-io** [expo/expo#26076]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/templates/expo-template-tabs

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Whenever you click in the main screen/area in any Tab it seems to automatically make the router jump back to the very 1st Tab - i created this video to demonstrate:

[Video on YouTube](https://www.youtube.com/shorts/mmJ_Wv13eVk)

(it is based on https://github.com/expo/expo/tree/main/templates/expo-template-tabs - i used that template and did not modify anything)

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      expo-cli: 5.4.8
    Expo Workflow: managed

**Comment by marklawlor** [comment]
I'm unable to replicate this issue and it hasn't been reported (or :+1: ) by anyone else.

I'm going to close this issue simply because I cannot replicate and no more information to go on. If you can provide any more information I'll reopen the ticket.

**Comment by jongbelegen** [comment]
I'm experiencing the same issue, luckily the behavior is not present in a production build
