### ISSUE TITLE
[SDK 50] `expo-image` jest snapshot is 6000 lines long and may cause `RangeError: Invalid string length

### ISSUE THREAD

**Issue by matthieugicquel** [expo/expo#26087]
### Minimal reproducible example

https://github.com/matthieugicquel/expo-sdk-50-issue

### Summary

When using expo SDK 50 (preview 7) with the associated package versions applied by `expo install --fix`, rendering an `<Image>` component from `expo-image` (v1.10.1) results in a 6000 lines long snapshot.

In real-world tests, it can cause  `pretty-format` reaching the max allowed string length in V8/node, and the test failing with  `RangeError: Invalid string length`.

**A test generating the 6000 lines snapshot:**
```jsx
render(<Image source={backgroundImage} />);

expect(screen).toMatchSnapshot();
```

[Here's a resulting snapshot example](https://github.com/matthieugicquel/expo-sdk-50-issue/blob/main/__snapshots__/App.test.js.snap). It's hard to read, but it looks like there's something circular/repeating in there.

*Package versions where it's reproduced (all are up-to-date):*

```
    "@testing-library/react-native": "^12.4.2",
    "expo": "~50.0.0-preview.7",
    "expo-image": "^1.10.1",
    "expo-status-bar": "~1.11.1",
    "jest": "^29.7.0",
    "jest-expo": "^50.0.1",
    "react": "18.2.0",
    "react-native": "0.73.1"
```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - ~/Library/Caches/fnm_multishells/68501_1703194778649/bin/node
      Yarn: 3.6.1 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - ~/Library/Caches/fnm_multishells/68501_1703194778649/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/matthieugicquel/.gem/ruby/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 33, 33
        Build Tools: 30.0.3, 33.0.0, 33.0.2
        System Images: android-33-ext5 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: next => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    Expo Workflow: bare
```

**Comment by branstiterts** [comment]
If we want to move forward with Expo 50, we are going to have to remove all our snapshots due to this issue. Is there any plan to look into this?

**Comment by lukmccall** [comment]
Hi @matthieugicquel, thank you for your report. Unfortunately, the long snapshot for the image component is due to the `nativeViewRef` prop being present. The testing library prints all the props, and the `ref` object is large. You may wonder why the `ref` prop doesn't have the same issue. This is because the testing library handles that prop differently, and it's not serialized like other props, so it's not a part of the snapshot. Additionally, it's not possible to ignore some props during serialization automatically. From a library perspective, there is nothing we can do about it. However, I have a workaround for you. You can try replacing the serialization function to remove or replace the `nativeViewRef` prop from the snapshot:
```jsx
it("renders", () => {
  render(<Image source={backgroundImage} />);
  const orginalToJson = screen.toJSON;
  screen.toJSON = () => {
    const json = orginalToJson();

    return {
      ...json,
      props: { ...json.props, nativeViewRef: "nativeViewRef" },
    };
  };
  expect(screen.toJSON()).toMatchSnapshot();
});
```
That example only works for rendering `Image` as a root. However, it's possible to adjust the `toJson` function to replace all `nativeViewRef` occurrences in all children. Although the solution isn't the cleanest, it should resolve your problem for now. I will continue to think of a better one.

**Comment by danbim** [comment]
> If we want to move forward with Expo 50, we are going to have to remove all our snapshots due to this issue. Is there any plan to look into this?

We face the same issue. This is basically a blocker for us to migrate to Expo SDK 50, unless we remove all snapshot tests :/

**Comment by samelas** [comment]
As a temporary solution, i was able to create a custom snapshot serializer:
`const expoImageNativeViewRefSerializer: SnapshotSerializerPlugin = {
  serialize(val, config, indentation, depth, refs, printer) {
    return printer(
      { ...val, props: { ...val.props, nativeViewRef: "nativeViewRef" } },
      config,
      indentation,
      depth,
      refs
    );
  },

  test(val) {
    return (
      val &&
      Object.prototype.hasOwnProperty.call(val, "type") &&
      val.type == "ViewManagerAdapter_ExpoImage" &&
      val.props.nativeViewRef != "nativeViewRef"
    );
  },
};`
Then you can add that globally in your jest config
`snapshotSerializers: ["./test/custom-expo-image-snapshot-serializer.ts"],`
or to expect directly 
`expect.addSnapshotSerializer(expoImageNativeViewRefSerializer);`

**Comment by MarcHbb** [comment]
> expo-image.js

How you do this if you don't have a __mocks__ folder ? 
Can you do this within your jest setup file ?

**Comment by MarcHbb** [comment]
> As a workaround you use `react-native` components in tests by creating mock `expo-image.js` in root `__mocks__`
> 
> ```
> import {
>   Image as RNImage,
>   ImageBackground as RNImageBackground,
> } from 'react-native';
> 
> // TODO remove when https://github.com/expo/expo/issues/26087 is resolved
> export const ImageBackground = RNImageBackground;
> export const Image = RNImage;
> ```

How you do this if you don't have a __mocks__folder ? 
Can you do this in your jest setup file or config ?
