### ISSUE TITLE
Clarify how to set versions for App Store / Play Store on standalone builds

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#261]
Our standalone app guide should contain some information on the following fields:

https://docs.expo.io/versions/v17.0.0/guides/configuration.html#versioncode
https://docs.expo.io/versions/v17.0.0/guides/configuration.html#buildnumber

**Comment by terribleben** [comment]
https://github.com/expo/expo-docs/commit/01de3f2131468b51b173b5bf0729cf310139c03e
