### ISSUE TITLE
EXPO 50.0.3 Debug: No compatible apps connected. JavaScript Debugging c an only be used with the Hermes engine.

### ISSUE THREAD

**Issue by dimaportenko** [expo/expo#26101]
### Summary

I created a fresh new expo app with `yarn create expo-app --template blank@beta`. 
Run it with `yarn start` in iPhone simulator. Press `j` and get following error
```
Debug: No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine. Learn more: https://docs.expo.dev/guides/using-hermes/
```

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

{
  "name": "photo-calculator",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "lint": "eslint ."
  },
  "dependencies": {
    "@types/react": "~18.2.45",
    "expo": "~50.0.0-preview.7",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.1",
    "typescript": "^5.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "eslint": "^8.56.0",
    "eslint-config-universe": "^12.0.0",
    "prettier": "^3.1.1"
  },
  "private": true
}

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/dmitriyportenko/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: managed

### Reproducible demo

https://github.com/dimaportenko/photo-calculator/commit/b8d6ba71322f2631c1b71e394ea026be6a004157

**Comment by AyyazAli** [comment]
I'm having the same issue with expo ~50.0.0 although I've added hermes engine in app.json as well, cleared cache, and done everything but still unable to connect the debugger

**Comment by wovalle** [comment]
Same here, expo 50.0.2

**Comment by ashermja** [comment]
Also not working 50.0.2

**Comment by gstcarv** [comment]
same

**Comment by gstcarv** [comment]
same, v50.0.2

**Comment by reidgarner** [comment]
same, v50.0.2

**Comment by jetaggart** [comment]
This is not working in 50.0.3
