### ISSUE TITLE
Expo Drawer stucks half way to close/open

### ISSUE THREAD

**Issue by shulinnn** [expo/expo#26114]
### Minimal reproducible example

https://github.com/shulinnn/wbgl-companion-app

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Expected behaviour is that i should be able to close the drawer completely after clicking outside the drawer.
Everything works inside `dev env` , and inside `npx expo start --no-dev` everything is fine too. It happens only after building.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

**Comment by shulinnn** [comment]
So it seems like the issue isnt router nor react-navigation related. The issue is purely on phones with more than 60hz.

**Comment by rdanielmurphy** [comment]
I also have this exact problem after upgrading from 48 to 49.  Also only happens after building the app.  It worked just fine when I could useLegacyImplementation for Drawer.Navigator.  Now I can no longer do that because I'm forced to use react-native-reanimated v3.

**Comment by marklawlor** [comment]
Expo Router doesn't change the appearance of the Drawer component, we only modify its children. This appears to be an up-steam issue, but I'd assume with `react-native-safe-area-context` getting the incorrect screen dimensions (Drawer uses this to calculate its positioning)

**Comment by isaachinman** [comment]
@marklawlor Thanks for looking into it. Assuming the issue is upstream – any suggestions on how to fix it within an Expo app?

**Comment by 121Unicorns** [comment]
Encountering the same issue on some devices but not on others, I'm using Expo v49.0.11 and expo router v2. Any ideas on how to fix it?

**Comment by isaachinman** [comment]
Upgrading to v50 was the only thing that fixed the issue.

**Comment by rdanielmurphy** [comment]
Yup, upgrading to 50 fixed it for me too.  Navigation Drawer was broken on expo 49.  Something to do with the animation libraries I'm guessing.

**Comment by paulocappa** [comment]
Same issue here, but I can't upgrade to 50, any updates?
