### ISSUE TITLE
Build error when setup with API routes and nativewind v4

### ISSUE THREAD

**Issue by bidah** [expo/expo#26118]
### Minimal reproducible example

https://github.com/bidah/expo-router-v3-vercel-config-build-error/blob/main/package.json

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

```
Build error:
Server Bundling failed 7145ms (node_modules/expo-router/node/render.js)
error: node_modules/@expo/server/build/index.js: node_modules/@expo/server/build/index.js:Invalid call at line 63: import(filePath)
Web node_modules/expo-router/entry.js ▓▓▓░░░░
░░░░░░░░░ 22.9% (181/378)Error: node_modules/@expo/server/build/index.js: node_modules/@expo/server/build/index.js:Invalid call at line 63: import(filePath)
```
And since the new index.js file on `app` router folder points to the dist build the development flow gets broken.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - /usr/local/opt/nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/opt/nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.11.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/roro/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed

**Comment by kitten** [comment]
Sorry for the delay! I don't seem to be able to reproduce this issue currently.
Have you tried this again since with the stable release of Expo SDK 50? Since no lockfile is included in the reproduction, I suspect that this has been resolved and isn't causing issues anymore.

For context, I ran both:
- `expo start --web`
- and; `expo export -p web`

If, after updating, you're still having any issues, please update the reproduction and we'll get this issue reopened and your issue addressed. Cheers!

**Comment by weico-d** [comment]
same issues.

**Comment by bidah** [comment]
will try that! thanks
