### ISSUE TITLE
WSL2 networkingMode=mirrored can't connect to Android Emulator

### ISSUE THREAD

**Issue by trevorpfiz** [expo/expo#26110]
### Summary

Using WSL2 on Windows 11. I am able to connect my iPhone to expo without using tunnel with the networkingMode=mirrored, which has been great, but the Android Emulator stopped connecting.

![image](https://github.com/expo/expo-cli/assets/24904780/503e7675-3172-4564-8b03-f1be41973bde)

.wslconfig
```
[wsl2]
memory=8GB
networkingMode=mirrored
dnsTunneling=true
autoProxy=true
firewall=true
hostAddressLoopback=true

[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2023.12.04.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

WSL2. Android Emulator.

### Error output

failed to connect to /192.168.4.73 (port 8081) from /10.0.2.16 (port 49424) after 10000ms

### Reproducible demo or steps to reproduce from a blank project

Open Android Studio and run the emulator on Windows 11. Launch Expo on WSL2 with `networkingMode=mirrored`.

**Comment by trevorpfiz** [comment]
I am now able to connect to my iPhone and use an Android Emulator through WSL2.

Here is my `.wslconfig`

```
[wsl2]
memory=10GB
dnsTunneling=true
autoProxy=true
networkingMode=mirrored

[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
hostAddressLoopback=true
useWindowsDnsCache=true
bestEffortDnsParsing=true
```

Had to follow https://medium.com/@akbarimo/developing-react-native-with-expo-android-emulators-on-wsl2-linux-subsystem-ad5a8b0fa23c to allow the `Press a | open Android` to work in WSL2.

I also had to do `"main": "index.ts"` where `index.ts` is `import "expo-router/entry";` to get the Android Emulator to work.

**Comment by 0tii** [comment]
> Had to follow https://medium.com/@akbarimo/developing-react-native-with-expo-android-emulators-on-wsl2-linux-subsystem-ad5a8b0fa23c to allow the `Press a | open Android` to work in WSL2.

may i shamelessly self promote my updated methodology for WSL2+Expo? https://medium.com/@danielrauhut/running-expo-dev-builds-from-wsl-on-your-windows-virtual-devices-android-emulator-bd7cc7e29418

**Comment by Zoz24** [comment]
> I am now able to connect to my iPhone and use an Android Emulator through WSL2.
> 
> Here is my `.wslconfig`
> 
> ```
> [wsl2]
> memory=10GB
> dnsTunneling=true
> autoProxy=true
> networkingMode=mirrored
> 
> [experimental]
> autoMemoryReclaim=gradual
> sparseVhd=true
> hostAddressLoopback=true
> useWindowsDnsCache=true
> bestEffortDnsParsing=true
> ```
> 
> Had to follow https://medium.com/@akbarimo/developing-react-native-with-expo-android-emulators-on-wsl2-linux-subsystem-ad5a8b0fa23c to allow the `Press a | open Android` to work in WSL2.
> 
> I also had to do `"main": "index.ts"` where `index.ts` is `import "expo-router/entry";` to get the Android Emulator to work.

This is awesome, thanks. 
In addition, it's noteworthy to point know:

1. Microsoft nowadays recommend modify WSL settings through the GUI app called "WSL Settings":

<img width="1518" height="1014" alt="Image" src="https://github.com/user-attachments/assets/abd7fe62-d4d1-4c25-980a-c187b151622f" />

For anyone who might be running into similar issue, this might be preferred for you if you prefer to configure settings through GUI. 


2. Some of these experimental features may get deprecated by Microsoft and then become invalid config, make sure to verify the validity of these keys instead of just copy paste.
