### ISSUE TITLE
New `expo-doctor` is noisy on CI

### ISSUE THREAD

**Issue by KiwiKilian** [expo/expo#26124]
### Summary

The new `expo-doctor` command is quite noisy on GitLab CI. Compare the new `expo-doctor`:

![Bildschirm­foto 2023-03-06 um 11 32 12](https://user-images.githubusercontent.com/18724559/223086244-b3da1387-5fb1-4378-a715-a2580cf70e72.png)

With the old one `expo-cli doctor`:

![Bildschirm­foto 2023-03-06 um 11 34 18](https://user-images.githubusercontent.com/18724559/223086342-5f550abd-fb28-4a1d-8a9f-a30f8eb753c9.png)

### Environment

This is from my local machine, not GitLab CI.

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 8.19.4 - ~/Development/rrph-app/node_modules/.bin/npm
      Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 48.0.5 => 48.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

GitLab CI

### Reproducible demo or steps to reproduce from a blank project

Not sure, if this is locally reproducible. GitLab CI should show this with a `package.json` like this:

```json
{
  "dependencies": {
    "expo": "48.0.5",
    "react-native": "0.71.3"
  }
}
```

And `.gitlab-ci.yml`:
```yml
image: node:16

stages:
  - test

test:expo-doctor:
  stage: test
  script:
    - npx --yes expo-doctor
    # Old expo-cli for comparison
    - npm install expo-cli --global
    - expo-cli doctor
```

**Comment by karlhorky** [comment]
I'm guessing this is not yet resolved, right @KiwiKilian ?

**Comment by KiwiKilian** [comment]
TBH I've since removed our CI task for `expo-doctor` because it never came to use, as it checks against the Expo Go proven packages. So those reports aren't helping anyone who uses development builds as dev clients. But if anybody can confirm it's still the case with current versions, please chime in!

**Comment by keith-kurak** [comment]
Hi @KiwiKilian - apologies, I didn't see this issue before. I'm thinking (hoping?) this is better now. Doctor should now respect the `CI=1` flag, so `CI=1 npx expo-doctor@latest` should suppress all spinners, which are usually the culprit with that sort out of output. Additionally, if you want to suppress the package version checks, you can use the `EXPO_DOCTOR_SKIP_DEPENDENCY_VERSION_CHECK=1` variable.
