### ISSUE TITLE
Outdated Hebrew Language Code On Android

### ISSUE THREAD

**Issue by EladKarni** [expo/expo#26138]
### Minimal reproducible example

https://github.com/EladKarni/outdated-hebrew-languagecode

### Summary

On android, the `expo-localization` package returns an outdated ISO code for Hebrew of `iw` instead of the new one of `he`. I checked this code on iOS and it does return `he` when run on an iOS device.

In the meantime, I'm using this line of code to resolve the issue:
`getLocales()[0].languageCode === "iw" ? "he" : getLocales()[0].languageCode`

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-223.8836.35.2231.11090377    
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

**Comment by fobos531** [comment]
@EladKarni This doesn't seem to be direct issue in Expo, but rather an inconsistency in Android - see: https://stackoverflow.com/questions/8202406/locale-code-for-hebrew-reference-to-other-locale-codes

I'm not sure whether Expo should add special handling for such locales, or whether the developers should just check for both cases.

**Comment by aleqsio** [comment]
I'm really hesitant on adding custom handling to expo-localization – any complexity here will be hard to maintain 😅

**Comment by EladKarni** [comment]
> @EladKarni This doesn't seem to be direct issue in Expo, but rather an inconsistency in Android - see: https://stackoverflow.com/questions/8202406/locale-code-for-hebrew-reference-to-other-locale-codes
> 
> I'm not sure whether Expo should add special handling for such locales, or whether the developers should just check for both cases.

Thanks for pointing that out. Seems like this is actually an issue with Java as it was originally developed before the new language code `he` as created (that's my guess anyhow). 

Seems like this is a known issue with anything that uses JDK:
https://issuetracker.google.com/issues/218160601?pli=1

I guess for now, the fix for it is simple enough. Just annoying! I totally get what @aleqsio is saying though and adding an exception for this could snowball out of control if other languages or exceptions are needed so I'll defer to your expertise here.
