### ISSUE TITLE
[docs] Can't see Unit testing page

### ISSUE THREAD

**Issue by kk3939** [expo/expo#26135]
### Summary

When I tried to check [unit test page](https://docs.expo.dev/develop/unit-testing) in [Testing router page](https://docs.expo.dev/router/reference/testing/), I found that it is broken.

Mark down file and [the page](https://docs.expo.dev/develop/unit-testing/) exists. 
I'm not sure of the cause.
https://github.com/expo/expo/blob/main/docs/pages/develop/unit-testing.mdx

### Link to the related docs page

https://docs.expo.dev/develop/unit-testing

### Anything else?

When click link from sidebar in Home, I can access the page.
![スクリーンショット 2023-12-27 18 57 50](https://github.com/expo/expo/assets/45879786/040de66c-7b88-4d82-b1af-570613689d0d)

**Comment by brleinad** [comment]
It looks like it goes on an infinite redirect loop (301) but if you first navigate to https://docs.expo.dev/develop and then on the sidebar click on `unit tests` it navigates successfully. 

Not sure if that helps. I was also trying to access the page and I was about to open an issue when I saw yours 😄

**Comment by amandeepmittal** [comment]
Apologies for the inconvenience. Looks like I added a self redirect for this URL. A fix is on the way: https://github.com/expo/expo/pull/26140.
