### ISSUE TITLE
App crashes every time on iOS 17.2 when expo-av is playing video and user tries to navigate to some screen

### ISSUE THREAD

**Issue by kockar96** [expo/expo#26165]
### Minimal reproducible example

https://github.com/kockar96/expo-av-bug

### Summary

In the video below you can see that the app crashes every time since iOS 17.2 update (I believe that on 17.1 it behaves the same). It's permanent and can't be handled with try catch or error boundary. The same thing happens with bare react-navigation as with the expo router. 
Before iOS version 17.1 this was not the case.

https://github.com/expo/expo/assets/116439489/b1c8ca94-b2c4-4d8d-a682-d2e920c27a28

### Environment

 "@expo/vector-icons": "^13.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~49.0.18",
    "expo-av": "^13.6.0",
    "expo-font": "~11.4.0",
    "expo-linking": "~5.0.2",
    "expo-router": "^2.0.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6"

**Comment by prashant6768** [comment]
Try to update react-native-screen to 3.29.0

**Comment by kockar96** [comment]
> Try to update react-native-screen to 3.29.0

This solved the issue. Thanks a lot.

**Comment by kockar96** [comment]
> Try to update react-native-screen to 3.29.0

This solved the issue. Thanks a lot.

**Comment by Elue-dev** [comment]
i still encounter this error

**Comment by prashant6768** [comment]
@Elue-dev Are you using expo-av?

**Comment by Elue-dev** [comment]
> @Elue-dev Are you using expo-av?

yes i am

**Comment by prashant6768** [comment]
@Elue-dev In Expo AV don't use (comment it for a while) "useNativeControls" and run it. It will get resolved.

**Comment by Elue-dev** [comment]
> @Elue-dev In Expo AV don't use (comment it for a while) "useNativeControls" and run it. It will get resolved.

yes found that out,  but the users can't control the video

**Comment by prashant6768** [comment]
@Elue-dev I am also working on that. Please tell me if you find the solution for that.

**Comment by Elue-dev** [comment]
> @Elue-dev I am also working on that. Please tell me if you find the solution for that.

some people said updating “react-native-screens” package solves it for them, but it didn’t for me

what i did was to remove “useNativeControls” prop and it worked fine, but the controls would no longer be there on the video
