### ISSUE TITLE
`pod install` fails due to invalid verification checksum when I tried to run in iOS

### ISSUE THREAD

**Issue by taka-2120** [expo/expo#26178]
### Summary

When I tried to run a clean project in iOS using `npx expo run:ios`, I got the following error (Error 1).
I tried `pod install` separately in `ios` directory, it seems to be affected by boost library (Error 2). I also tried cleaning cache using `pod cache clean --all`, removing `Pods` directory, and removing `Podfile.lock` file, but it was not fixed.
I found a sha256 code in `node_modules/react-native/third-party-podspecs/boost.podspec` (codes are in the bottom), but I have no ideas how to do from here.

Does anyone know how to fix this issue?

---

**Error 1:**
```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
```

**Error 2:**
```
Using Expo modules
[Expo] Enabling modular headers for pod ExpoModulesCore
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the release tarball from Maven Central
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing EXApplication (5.3.1)
Installing EXConstants (14.4.2)
Installing EXFileSystem (15.4.5)
Installing EXFont (11.4.0)
Installing EXSplashScreen (0.20.5)
Installing Expo (49.0.21)
Installing ExpoKeepAwake (12.3.0)
Installing ExpoModulesCore (1.5.12)
Installing FBLazyVector (0.72.6)
Installing FBReactNativeSpec (0.72.6)
Installing RCT-Folly (2021.07.22.00)
Installing RCTRequired (0.72.6)
Installing RCTTypeSafety (0.72.6)
Installing React (0.72.6)
Installing React-Codegen (0.72.6)
Installing React-Core (0.72.6)
Installing React-CoreModules (0.72.6)
Installing React-NativeModulesApple (0.72.6)
Installing React-RCTActionSheet (0.72.6)
Installing React-RCTAnimation (0.72.6)
Installing React-RCTAppDelegate (0.72.6)
Installing React-RCTBlob (0.72.6)
Installing React-RCTImage (0.72.6)
Installing React-RCTLinking (0.72.6)
Installing React-RCTNetwork (0.72.6)
Installing React-RCTSettings (0.72.6)
Installing React-RCTText (0.72.6)
Installing React-RCTVibration (0.72.6)
Installing React-callinvoker (0.72.6)
Installing React-cxxreact (0.72.6)
Installing React-debug (0.72.6)
Installing React-hermes (0.72.6)
Installing React-jsi (0.72.6)
Installing React-jsiexecutor (0.72.6)
Installing React-jsinspector (0.72.6)
Installing React-logger (0.72.6)
Installing React-perflogger (0.72.6)
Installing React-rncore (0.72.6)
Installing React-runtimeexecutor (0.72.6)
Installing React-runtimescheduler (0.72.6)
Installing React-utils (0.72.6)
Installing ReactCommon (0.72.6)
Installing SocketRocket (0.6.1)
Installing Yoga (1.14.0)
Installing boost (1.76.0)

[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
```

**boost.podspec**
```ruby
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

Pod::Spec.new do |spec|
  spec.name = 'boost'
  spec.version = '1.76.0'
  spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" }
  spec.homepage = 'http://www.boost.org'
  spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
  spec.authors = 'Rene Rivera'
  spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
                  :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }

  # Pinning to the same version as React.podspec.
  spec.platforms = { :ios => '11.0' }
  spec.requires_arc = false

  spec.module_name = 'boost'
  spec.header_dir = 'boost'
  spec.preserve_path = 'boost'
end
```

### SDK Version

49.0.21

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 3.6.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 28, 29, 31, 32, 33
        Build Tools: 29.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-Tiramisu | Google TV ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.21 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    npmGlobalPackages:
      eas-cli: 5.5.0
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Minimal reproducible example

1. Run `npx create-expo-app xxx` to create a new project
2. Run `npm ci` to install all dependencies
3. Run `npx expo run:ios`, and I got the error

**Comment by amandeepmittal** [comment]
Hey @taka-2120, it seems that downloading boost dependency is failing for both Android and iOS due to jfrog having a downtime. You can read more about it here: https://github.com/facebook/react-native/issues/42109. For now, you can resolve this issue by creating a patch as explained this comment: https://github.com/boostorg/boost/issues/843#issuecomment-1872943124.

**Comment by taka-2120** [comment]
> Hey @taka-2120, it seems that downloading boost dependency is failing for both Android and iOS due to jfrog having a downtime. You can read more about it here: https://github.com/facebook/react-native/issues/42109. For now, you can resolve this issue by creating a patch as explained this comment: https://github.com/boostorg/boost/issues/843#issuecomment-1872943124.

Thank you for your reply. It resolved!

**Comment by st4l1nR** [comment]
This is still happening

**Comment by maniakjaniak** [comment]
Still happening for us too.

**Comment by Dssssds** [comment]
How to deal with it, is there any solution, thank you.

**Comment by Dssssds** [comment]
Same problem, same error.
![image](https://github.com/expo/expo/assets/17268259/4547ed0a-0418-4e2d-a38f-c1667d72e7d2)

**Comment by CABRERAREUBEN** [comment]
Hi have you experienced this kind of issues while running android? i have fixed the boost issue in ios.

Task :react-native-reanimated:prepareBoost FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
753 actionable tasks: 5 executed, 748 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-reanimated:prepareBoost'.
> Could not read /Users/macbook/Documents/GitHub/XureMember/node_modules/react-native-reanimated/android/build/downloads/boost_1_76_0.tar.gz.
   > Not in GZIP format

**Comment by Dssssds** [comment]
> Hi have you experienced this kind of issues while running android? i have fixed the boost issue in ios.
> 
> Task :react-native-reanimated:prepareBoost FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings 753 actionable tasks: 5 executed, 748 up-to-date
> 
> FAILURE: Build completed with 2 failures.
> 
> ## 1: Task failed with an exception.
> * What went wrong:
>   Execution failed for task ':react-native-reanimated:prepareBoost'.
> 
> > Could not read /Users/macbook/Documents/GitHub/XureMember/node_modules/react-native-reanimated/android/build/downloads/boost_1_76_0.tar.gz.
> > Not in GZIP format

This is because your package cannot be downloaded from the source. You need to manually download (boost_1_76_0.tar.gz.) to the local and then manually copy it to the directory:(/Users/macbook/Documents/GitHub/XureMember/node_modules/react-native-reanimated/android/build/downloads/)
