### ISSUE TITLE
I have an error with the creation of the Expo Project.

### ISSUE THREAD

**Issue by ayrtoncu** [expo/expo#26175]
### Summary

I can't create the project, I'm new with React Native and I'm trying to learn and I'm getting this error:
I consulted in Forums and communities but I didn't get help I'm going 2 days with this.
I reinstalled node, updated npm and the error persists.
npm : 10.2.5
Node: 20.10.0 LTS
`× Something went wrong in downloading and extracting the project files: Could not parse JSON returned from "npm.cmd pack expo-template-blank@latest --dry-run".

expo-template-blank-49.0.22.tgz

Error: Unexpected token 'e', "expo-templ"... is not valid JSON
Error: Could not parse JSON returned from "npm.cmd pack expo-template-blank@latest --dry-run".

expo-template-blank-49.0.22.tgz

Error: Unexpected token 'e', "expo-templ"... is not valid JSON`

### Environment

npx create-expo-app

### Minimal reproducible example

Error × Something went wrong in downloading and extracting the project files: Could not parse JSON returned from "npm.cmd pack expo-template-blank@latest --dry-run".

expo-template-blank-49.0.22.tgz

Error: Unexpected token 'e', "expo-templ"... is not valid JSON
Error: Could not parse JSON returned from "npm.cmd pack expo-template-blank@latest --dry-run".

expo-template-blank-49.0.22.tgz

Error: Unexpected token 'e', "expo-templ"... is not valid JSON

**Comment by ayrtoncu** [comment]
I solved it, change the project folder to the operating system drive.
Initially my project was on the D: drive, now I moved it to the C: drive on the desktop and the project was built.
It was already driving me crazy. XD

**Comment by shahrierNafis** [comment]
Use sudo in Linux
