### ISSUE TITLE
How to read file from URI | Expo | FileSystem.

### ISSUE THREAD

**Issue by Rutulpatel7077** [expo/expo#2618]
### Environment

Expo CLI 2.2.5 environment info:
System:
OS: macOS High Sierra 10.13.6
Shell: 5.3 - /bin/zsh
Binaries:
Node: 10.11.0 - /usr/local/bin/node
Yarn: 1.7.0 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.1 AI-173.4697961
Xcode: 10.1/10B61 - /usr/bin/xcodebuild
npmGlobalPackages:
expo-cli: 2.2.5

![image](https://user-images.githubusercontent.com/22271244/48026442-199b3e00-e114-11e8-90f0-ddb10ffc79d9.png)

### Actual Behavior

I have ejected expo application. I am trying to access email attachment from email to import data in my app. (As per screenshot).

After changing info.plist, now I am able to get my app in the list of "open with app list" and actually able to open that file with my expo(React native app).

But my question is, How am I able to get the data of the email attachment into my app.

in my App.js

```
Linking.getInitialURL().then((url) => {
  if (url) {
        console.log(url);
    }

}).catch(err => console.error('An error occurred', err));

```

**it's giving me URL like this** `exp:///private/var/mobile/Containers/Data/Application/7E55EB55-7C49-4C0C-B4CB-63AC4F49689E/Documents/Inbox/matters-3.csv`

So I am assuming, when I click open with my app. The URL that is passed into my app from the system is actually a copy of the document that is placed somewhere in our app’s directory.

but when I trying to access this file with` Expo.FileSystem. readAsStringAsync` it's giving me error says, file is not readable and also I am not able to write anything in the direcotry.

### Expected Behavior
I should be able to access the file as string.

### What you think ?

I am thinking just because I am develping in expo it's saving file in expo directory so I am not able to access the file from my app. Looking for solution. 

How to read file from URI.

**Comment by EvanBacon** [comment]
just btw you could add URI Schemes to the `info.plist` through the `app.json`

**Comment by Rutulpatel7077** [comment]
@EvanBacon @nikki93 Any updates?

**Comment by Rutulpatel7077** [comment]
I think when we add **document type**  in the ejected app.
it's using **exp** scheme to open that file. 

That means it's not using our app.json scheme.
