### ISSUE TITLE
[SDK 50] expo-updates + src dir breaks assets 

### ISSUE THREAD

**Issue by alexandernanberg** [expo/expo#26195]
### Minimal reproducible example

https://github.com/alexandernanberg/expo-rmissing-image-epro

### Summary

When using `expo-updates` in combination with the `src` directory all images (probably other assets too assets?) disappear in production builds. 

Steps to reproduce
1. Clone repro repo
2. Setup expo-updates with a project you can test with
3. Start dev and check that the image renders
4. Create a production build an install it, notice that now the image isn't showing anymore

<details>
<summary>Screenshots</summary>

#### Dev
![Simulator Screenshot - iPhone 15 Pro - 2024-01-04 at 08 31 08](https://github.com/expo/expo/assets/8997319/1fcacf6a-e0d5-4428-84b8-6de31db60185)

#### Prod
![Simulator Screenshot - iPhone 15 Pro - 2024-01-04 at 08 28 44](https://github.com/expo/expo/assets/8997319/5eccb957-92b7-4bf8-96ce-17c357ab90de)

</details>

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: 50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: bare
```

**Comment by aleqsio** [comment]
@alexandernanberg Hi, QQ: is this on Android or iOS?

**Comment by alexandernanberg** [comment]
Both Android and iOS. 

But I think my repro is "broken", will investigate some more if I can reproduce it outside my app. Something makes the `require` URL to be empty it seems, idk if it's because the file is missing or something else. Is there an easy way to check the built app's assets dir?

**Comment by aleqsio** [comment]
Thanks, let me know if you're able to reproduce!
There is `npx expo export` that exports all assets – keep in mind it strips extensions but you can look at metadata.json

**Comment by alexandernanberg** [comment]
@aleqsio Managed to create a proper reproduction now, turns out it had nothing to do with fonts but is caused by a combination of expo updates and the `src` dir

**Comment by kylianbrun** [comment]
Hello !
I'm getting the same problem with sdk 49.

When i building the app, install it in the emulator, launch the app, I don't have any images and fonts.

I logged, expo-updates constants and i got this : 
<img width="626" alt="image" src="https://github.com/expo/expo/assets/59508914/3947bc32-ea7b-41dd-870b-101fde01cedf">
(channel, updateId, manifest, releaseChannel, localAssets, runtimeVersion)

We can see that localAssets is empty.

But if I intercept http request to expo updates server, I can see that there is a update with assets : 
<img width="579" alt="image" src="https://github.com/expo/expo/assets/59508914/bf299b7f-55c5-4700-9a30-8edb63955a58">
-> The updateId is different (btw, the updateId in expo updates constants doesn't exists) 

Now if I do a eas update in the same channel "staging" (`eas update --branch staging --message "Trying to fix assets"`)

<img width="1144" alt="image" src="https://github.com/expo/expo/assets/59508914/53f4d2a7-9443-4f25-a2d3-0c31e986ca67">

I full restart the app, and I got a new update detected : 
<img width="1113" alt="image" src="https://github.com/expo/expo/assets/59508914/d56a71f1-1b96-463a-a6c6-f3b85063516f">

Images and fonts are not loaded anymore and expo-updates constants are unchanged : 
<img width="626" alt="image" src="https://github.com/expo/expo/assets/59508914/822ebedc-3f5b-4b51-ab85-14f63c2de1ed">

But if I full restart the app again, now expo-updates constants are updated : 
<img width="1045" alt="image" src="https://github.com/expo/expo/assets/59508914/7742612f-c7c0-4d00-8467-26dc7e831199">

And i got all my assets in the app.

I don't understand why ?
Assets are not bundled at the build?

If someone can help me, I stuck,
Thanks.

**Comment by wschurman** [comment]
Going to keep this issue narrowed to just the regression from 49 to 50 as reported. 

@kylianbrun - please file a separate issue for 49.

**Comment by wschurman** [comment]
Repro'd in SDK 50. This is now a release blocker. Thanks for the report!

Repro steps:
```
yarn create expo-app src-test-huh --template blank@beta
cd src-test-huh/
npx expo install expo-image expo-router react-native-safe-area-context react-native-screens expo-linking expo-constants expo-status-bar
// follow remaining installations instructions for expo-router https://docs.expo.dev/router/installation/
eas init
// move App.js into src/app/index.js
// Put image tag in index.js: <Image style={styles.image} source={require("../../assets/image.png")} />
npx expo prebuild
// build release app in xcode for sim, see image
npx expo install expo-updates
eas update:configure
npx expo prebuild
pod install
// build release app in xcode for sim, see image is not there
```

**Comment by wschurman** [comment]
Cherry-picked into sdk-50. Should be released into beta soon-ish.

**Comment by mihailapuste** [comment]
I'm wondering if there's been any progress on resolving the issue with bundled assets in Expo SDK 50. In my bare React Native project, I'm currently using [Expo 50.0.0-alpha.6](https://www.npmjs.com/package/expo/v/50.0.0-alpha.6) without encountering any problems. This version handles both audio and video without issue.

However, after upgrading to [Expo 50.0.0-preview.11](https://www.npmjs.com/package/expo/v/50.0.0-preview.11), I'm facing an issue where bundled assets, particularly local audio and video files, are missing, leading to errors.

Based on the following PRs I've seen (https://github.com/expo/expo/pull/25484, https://github.com/expo/expo/pull/25613, https://github.com/expo/expo/pull/26307), it appears that Expo may be moving away from supporting bundled assets in future releases. I'm not certain if this change has been fully decided upon and implemented for the stable release of Expo SDK 50.

Could anyone please confirm if this is indeed the case? Specifically, will bare React Native apps using Expo SDK 50 and beyond no longer support asset files included in the bundle?

Thanks

**Comment by wschurman** [comment]
> Based on the following PRs I've seen (#25484, #25613, #26307), it appears that Expo may be moving away from supporting bundled assets in future releases. I'm not certain if this change has been fully decided upon and implemented for the stable release of Expo SDK 50.
> 
> Could anyone please confirm if this is indeed the case? Specifically, will bare React Native apps using Expo SDK 50 and beyond no longer support asset files included in the bundle?

I don't think this is the case. These PRs to (amongst others) are mostly to remove classic-update-specific features. Unless we missed something during their removal or there's a bug, they shouldn't cause bundled assets to no longer work. If a feature was working before because it was a classic update feature and we don't offer an alternative using EAS Update, definitely let me know, for the most part there should be an equivalent feature to migrate to (with a few exceptions).

Concretely, as I understand it, a bundled asset is one that is loaded via `require('local/path/to/asset')`. I've also cc'd other contributors for clarification in case my understanding is incorrect or there are other classes of bundled assets that I don't know about.

> I'm wondering if there's been any progress on resolving the issue with bundled assets in Expo SDK 50. In my bare React Native project, I'm currently using [Expo 50.0.0-alpha.6](https://www.npmjs.com/package/expo/v/50.0.0-alpha.6) and running RN version `0.72.9` without any issues when playing local audio and video files.
> 
> However, after upgrading to [Expo 50.0.0-preview.11](https://www.npmjs.com/package/expo/v/50.0.0-preview.11), I'm facing an issue where bundled assets, particularly local audio and video files, are missing, leading to errors. I've only tested this on `iOS` so far.

If you could file a new issue (cc me) for this with a repro that'd be the best way for us to address and hopefully resolve it if there is a regression. Please detail how you are embedded the local audio and video files.

**Comment by mihailapuste** [comment]
> @wschurman

Awesome, thank you for your help. I've submitted an issue here along with a repo with a test app that you can reproduce the error in. Hope this helps! https://github.com/expo/expo/issues/26474
