### ISSUE TITLE
bottom padding on <Text> component in tabs template. only on firefox

### ISSUE THREAD

**Issue by manishmh** [expo/expo#26191]
### Summary

there is default padding or some sort of space in <Text> component in react-native app. 
only when expo app is build with tabs --template. 
I am using arch linux 

### What platform(s) does this occur on?

Web

### SDK Version

49

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.1 EndeavourOS
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.0/bin/npm
    npmPackages:
      expo: ~49.0.18 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 5.9.3
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

import { SafeAreaView } from 'react-native';
import {  Text, View } from '../../components/Themed';
import { FontAwesome5 } from '@expo/vector-icons';
import { TouchableOpacity } from 'react-native-gesture-handler';

export default function Search() {
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <View style={{paddingHorizontal: 15,height: "100%",  display: 'flex', justifyContent: 'center', }}>
        <View style={{display: 'flex', flexDirection: 'column', gap: 10}}>
          <View style={{display: 'flex', flexDirection: 'column', justifyContent: 'center',}}>
            <TouchableOpacity>
              <View style={{display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12, width: 85, backgroundColor: '#2B2B2B', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 20}}>
                <Text>Cab</Text>
                <FontAwesome5 name="angle-down" size={20} style={{color: 'white'}}/>
              </View>   
            </TouchableOpacity>
            <TouchableOpacity>
              <Text style={{backgroundColor: 'white', color: 'black', paddingHorizontal: 10, }}>Train</Text>
            </TouchableOpacity>
          </View>  
        </View>
        {/* recent  */}
        <View style={{}}></View>
      </View>
    </SafeAreaView>
  );
}
// cab is not cenred and train with bottom padding

**Comment by EvanBacon** [comment]
I can't reproduce this issue.
