### ISSUE TITLE
Firestore Query .where new Date Crashing

### ISSUE THREAD

**Issue by cryptixcoder** [expo/expo#2619]
Currently working on a project that I need to get a set of document in a firestore collection between two dates. I am using expo-firebase-firestore and my query is setup as the following:

`firebase.firestore().collection().where('user_id', '==', USERID).where('tour_start_on', '>', YESTERDAY).where('tour_start_on', '<', TODAY).get()`

For YESTERDAY and TODAY I am using new Date().

When running this query in xcode I get the following error:
`libc++abi.dylib: terminating with uncaught exception of type NSException`

Is there a specific way I should be passing the timestamp to this query?

**Comment by EvanBacon** [comment]
Behind the scenes it's just doing:
```js
   if (value instanceof Date) {
      return {
        type: 'date',
        value: value.getTime(),
      };
    }
```
You could convert the date to a number and pass it through that way

**Comment by EvanBacon** [comment]
Resolved in rc-5
