### ISSUE TITLE
Google search results don't go to the latest version of docs

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#262]
At the time of writing, the latest sdkVersion is 17.0.0, and yet:

![pasted image at 2017_06_13 05_33 am](https://user-images.githubusercontent.com/90494/27060373-46badb54-4f91-11e7-9479-a4f0d4005156.png)

**Comment by ide** [comment]
Maybe what we could do is put `rel=canonical` meta tags on the latest versioned pages (v17.0.0 right now, v18.0.0 soon) that say the canonical URL is the one with `/latest/` in it. That way Google constantly adds weight to `/latest/` pages while still letting users get versioned links. One problem with this is that users will paste versioned links everywhere and that's what gets picked up by Google.

Alternatively we could make the latest versioned links (v17.0.0) redirect to `/latest/`.  Some downsides to that but we get better SEO.

**Comment by dikaiosune** [comment]
https://www.dropbox.com/s/xipxr44xm143jld/Screenshot%202017-08-04%2017.26.05.png?dl=0
