### ISSUE TITLE
Is it possible this import is incorrect?

### ISSUE THREAD

**Issue by tncbbthositg** [expo/expo#2620]
https://github.com/expo/expo/blob/41458d1de91544c41097818db21e44e9aa84688c/ios/Exponent/Versioned/Core/Internal/EXAppState.m#L7

I don't have a great explanation for how this was working for me previously but isn't now.  I just tried to rebuild after having some issues with Mojave and I was getting an error:

```
EXCore/EXAppLifeCycleService.h
  file not found
  EXAppState.m
```

The file in EXCore is named [EXAppLifecycleService.h](https://github.com/expo/expo-core/blob/master/ios/EXCore/Protocols/EXAppLifecycleService.h).

All the other references are lowercase and have been for 5 months now, so I'm not really sure why it was working for me before. :-/

Also, when I change the casing locally, my application does compile and it runs correctly.

In any case, it seems like the casing is incorrect.  

Edit: While fixing my Mojave issue, I updated from case-sensitive HFS to case-sensitive APFS.  This may be the culprit.

Edit again: Oh, I lied to you guys.  I switched from case-insensitive HFS to case-sensitive APFS.  That's definitely the culprit.

**Comment by brentvatne** [comment]
I think this may be due to the filesystem configuration on your OS (cc @ide who proposed the theory). Regardless we should change this.
