### ISSUE TITLE
Coordinates from the expo-location are not accurate

### ISSUE THREAD

**Issue by EmilBuszylo** [expo/expo#26213]
### Minimal reproducible example

```
export async function startTracking() {
  await Location.startLocationUpdatesAsync(LOCATION_TRACKING_TASK, {
    accuracy: Location.Accuracy.BestForNavigation,
    timeInterval: 1000, //15 sec
    distanceInterval: 10,
    foregroundService: {
      notificationTitle: 'Obserwacja lokalizacji aktywna',
      notificationBody: 'Monitorowanie lokalizacji celem obliczenia długości trasy',
      notificationColor: '#333333',
    },
    activityType: LocationActivityType.AutomotiveNavigation,
    showsBackgroundLocationIndicator: true,
  });

  console.log('[tracking]', 'started background location task');
}
```

### Summary

I have a big problem with [expo-location](https://docs.expo.dev/versions/latest/sdk/location/) package accuracy. Based on this example https://github.com/byCedric/office-marathon I was trying to write an app tracking my car's position during drive. Unfortunately, location coordinates are not accurate. From time to time coordinates show the wrong point hundreds of meters from my real position. I tried to fix it by including only coordinates with the best 'accuracy' parameter (accuracy < 10), however, it doesn't matter as still the coordinates can be very inaccurate. I have all the required permissions on my Android device, and I have set accuracy as "Location.Accuracy.BestForNavigation". I tried to change some settings regarding `timaInterval` and `distanceInterval`, but without any positive effect.

Could you tell me if I can do anything with that? Maybe it is completely normal behavior and in order to get more accurate coordinates I have to use a pay solution, do you have any knowledge about it?

Platform: Android (not tested on IOS)
expo version: 49.0.21 
expo-location version: 16.1.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 20230916.105514.0 - /usr/local/bin/watchman
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ~49.0.21 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: bare

**Comment by abdelkebir7Y** [comment]
Hi @EmilBuszylo, I have the same issue here ?

**Comment by alfredvaa** [comment]
I have a similar issue, in general the position is accurate but once in a while one point is a few hundred meters away from the real path. This seems to happen only on Android for me. It seems like a bug to me but I don't know if there is just a few Android devices that has a bad gps compared to iPhone.
