### ISSUE TITLE
Unable to route between Stacks inside Tabs

### ISSUE THREAD

**Issue by p8952** [expo/expo#26211]
### Minimal reproducible example

https://github.com/VersionOneDev/expo-routing-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I have an layout which is made up of a Stack, three Tabs within the Stack, and then a Stack in each Tab.

When I route via `router.push` from one Tab to another, I am unable to navigate back up the Stack in the Tab which I have pushed to unless I have already manually navigated to the Tab which I have pushed to.

✅ This Works - Tab One -> Tab Two -> Tab Three -> Tab Two Detail -> Back Button:

https://github.com/expo/expo/assets/2962587/cbc19459-5b0b-463d-90cc-8489f6ca09e1

✅ This Works - Tab One -> Tab Two -> Tab Three -> Tab Two Detail -> `router.back()`:

https://github.com/expo/expo/assets/2962587/653ee7b6-6ff1-4837-8e3e-2c8f6fcfa601

✅ This Works - Tab One -> Tab Two -> Tab Three -> Tab Two Detail -> Swipe Back:

https://github.com/expo/expo/assets/2962587/8b74e8a0-11ac-4c92-b551-856f40f6ac9e

❌ This Doesn't Work - Tab One -> Tab Three -> Tab Two Detail -> Back Button:

I'd expect there to be a Back Button to take me to Tab Two, there is no Back Button.

https://github.com/expo/expo/assets/2962587/5e22497f-3575-4bc6-9f0f-e01eecd24e27

❌ This Doesn't Work - Tab One -> Tab Three -> Tab Two Detail -> `router.back()`:

I'd expect `router.back()` to take me to Tab Two, not Tab One.

https://github.com/expo/expo/assets/2962587/66523985-e7fc-43f6-90c4-f96d2df9441a

❌ This Doesn't Work - Tab One -> Tab Three -> Tab Two Detail -> Swipe Back:

I'd expect Swipe Back to take me to Tab Two, there is no ability to Swipe Back.

https://github.com/expo/expo/assets/2962587/05e276bb-e8d2-4819-8496-ca93025a9727

❌ This Doesn't Work - `$ npx uri-scheme open exp://127.0.0.1:8081/--/home/tabTwo/tabTwoDetail --ios`:

I'd expect there to be a Back Button to take me to Tab Two, `router.back()` to take me to Tab Two, not Tab One, and Swipe Back to take me to Tab Two.

https://github.com/expo/expo/assets/2962587/48fc0cbf-de1b-479f-b6c9-fcbfe881e63e

Once this has happened, there is no way to get back to Tab Two at all, as while `router.back()` takes me to Tab One, navigating to Tab Two via the Tabs takes me to Tab Two Detail, rather than Tab Two.

https://github.com/expo/expo/assets/2962587/8ac2f4b5-2631-48da-aa59-fa59be7544fb

I have attempted to add:

```
export const unstable_settings = {
  initialRouteName: "index",
};
```

To `app/_layout.js`, as well as `app/home/tabOne/_layout.js`, `app/home/tabTwo/_layout.js`, and `app/home/tabThree/_layout.js`, however this does not change the behaviour.

### Environment

```
$ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.7.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed
```

**Comment by kaustubnvd** [comment]
+1 I have the same question / issue

**Comment by killerchip** [comment]
The way I workaround-ed it (if I remember well), was to split the navigation into two navigation actions. 
First, navigate to the desired tab, then push the page you wish.

But indeed this is seems hacky

**Comment by p8952** [comment]
@killerchip That's also what I'm doing, unfortunately not only is it hacky, but it doesn't work with deep linking.

When you navigate via `npx uri-scheme open exp://127.0.0.1:8081/--/home/tabTwo/tabTwoDetail --ios`, or from a web page using `href="exp://127.0.0.1:8081/--/home/tabTwo/tabTwoDetail"` you still get stuck until you quit the App.

Unfortunately I've not yet found a way to work around this.

**Comment by cseelus** [comment]
@killerchip How did you trigger two navigation actions?

Similar problem here. My app consists of five tabs, each with its own stack and linking from the first tab directly to a page nested inside another tab, won't show a back button, resulting in the tab being trapped on the nested page.

**Comment by killerchip** [comment]
Just issue two commands. First one command that switches tab and then the
one that pushes to stack. You might have to put a small delay between the.
Like an await on a promise that resolved after a few ms

**Comment by kaustubnvd** [comment]
I was able to get the behavior hackily working using the `navigation` object instead of the `router` object, and using the "initial: false" option.

Something like:
```
const navigation = useNavigation()

<Pressable
    onPress={() => {
        navigation.navigate(<stackName>, {
          screen: <screenNameInStack>,
          params: { <queryParams> },
          initial: false // This renders the initial screen in the stack even when navigating to the nested screen?
        })
     }}
 >

```
I also used a custom back button to have more control over the routing

https://reactnavigation.org/docs/nesting-navigators/

**Comment by berenteb** [comment]
Any updates on this issue? Huge blocker for our march release. Shall I switch to React Native Navigation until then?

**Comment by pdandradeb** [comment]
this issue deservers much more attention.
I'm glad to found @kaustubnvd workaround. many thanks!

> I was able to get the behavior hackily working using the `navigation` object instead of the `router` object, and using the "initial: false" option.
> 
> Something like:
> 
> ```
> const navigation = useNavigation()
> 
> <Pressable
>     onPress={() => {
>         navigation.navigate(<stackName>, {
>           screen: <screenNameInStack>,
>           params: { <queryParams> },
>           initial: false // This renders the initial screen in the stack even when navigating to the nested screen?
>         })
>      }}
>  >
> ```
> 
> I also used a custom back button to have more control over the routing
> 
> https://reactnavigation.org/docs/nesting-navigators/

**Comment by david-castaneda** [comment]
Any guidance when using expo router?

**Comment by cseelus** [comment]
@david-castaneda The workaround from @kaustubnvd is for Expo router. You just have to import useNavigation like this:

```javascript
import { useNavigation } from 'expo-router'
```

**Comment by noahbrandyberry** [comment]
Hey all, it may be easier to create a patch file. That way you don't need to change all the calls from `router.navigate` to `navigation.navigate`:

```
diff --git a/node_modules/expo-router/build/global-state/routing.js b/build/global-state/routing.js
index dfd96d110aaa01e014ed4172d7333092f708243d..6a40662a213c1b6e9051199854e0a06412c36332 100644
--- a/node_modules/expo-router/build/global-state/routing.js
+++ b/node_modules/expo-router/build/global-state/routing.js
@@ -150,6 +150,9 @@ function getNavigateAction(state, parentState, type = 'NAVIGATE') {
     else if (type === 'REPLACE' && parentState.type === 'tab') {
         type = 'JUMP_TO';
     }
+
+    params.initial = false
+
     return {
         type,
         target: parentState.key,
```

**Comment by kpoelhekke** [comment]
I've patched it to be a bit more explicit.

This way you can do `router.navigate({ pathname: "/foo", params: { initial: "false" }})`

```diff
diff --git a/build/fork/getStateFromPath.js b/build/fork/getStateFromPath.js
index 35ab3dfc52b51082fe74dfdfcb5bc49e3673d57a..db84304da5566ec4f16e004b495f3e639b81f8ac 100644
--- a/build/fork/getStateFromPath.js
+++ b/build/fork/getStateFromPath.js
@@ -527,7 +527,9 @@ const createNestedStateObject = (path, routes, routeConfigs, initialRoutes) => {
                 }
             }
             if (!route.params?.[name]) {
-                route.params[name] = value;
+                if(name !== "initial"){
+                    route.params[name] = value;
+                }
                 continue;
             }
         }
diff --git a/build/global-state/routing.js b/build/global-state/routing.js
index 2fba9d17abde2af1eb2326fcbd3385bf2eb85958..cb42a9c590b3995c401697c186036bf726563342 100644
--- a/build/global-state/routing.js
+++ b/build/global-state/routing.js
@@ -152,6 +152,11 @@ function rewriteNavigationStateToParams(state, params = {}) {
     params.screen = lastRoute.name;
     // Weirdly, this always needs to be an object. If it's undefined, it won't work.
     params.params = lastRoute.params ? JSON.parse(JSON.stringify(lastRoute.params)) : {};
+
+    if(lastRoute.path?.includes("initial=false")){
+        params.initial = false;
+    }
+    
     if (lastRoute.state) {
         rewriteNavigationStateToParams(lastRoute.state, params.params);
     }
```

**Comment by MateuszRostkowski** [comment]
> Hey all, it may be easier to create a patch file. That way you don't need to change all the calls from `router.navigate` to `navigation.navigate`:
> 
> ```
> diff --git a/node_modules/expo-router/build/global-state/routing.js b/build/global-state/routing.js
> index dfd96d110aaa01e014ed4172d7333092f708243d..6a40662a213c1b6e9051199854e0a06412c36332 100644
> --- a/node_modules/expo-router/build/global-state/routing.js
> +++ b/node_modules/expo-router/build/global-state/routing.js
> @@ -150,6 +150,9 @@ function getNavigateAction(state, parentState, type = 'NAVIGATE') {
>      else if (type === 'REPLACE' && parentState.type === 'tab') {
>          type = 'JUMP_TO';
>      }
> +
> +    params.initial = false
> +
>      return {
>          type,
>          target: parentState.key,
> ```

Thank you so much, it saved me a lot of time of debugging..

In case someone will try to adapt it on expo-50:

```expo-router+3.4.8.patch
diff --git a/node_modules/expo-router/build/global-state/routing.js b/node_modules/expo-router/build/global-state/routing.js
index 2fba9d1..9cce0c9 100644
--- a/node_modules/expo-router/build/global-state/routing.js
+++ b/node_modules/expo-router/build/global-state/routing.js
@@ -173,6 +173,9 @@ function getNavigateAction(state, parentState, type = 'NAVIGATE') {
     else if (type === 'REPLACE' && parentState.type === 'tab') {
         type = 'JUMP_TO';
     }
+
+    params.initial = false
+    
     return {
         type,
         target: parentState.key,

```

**Comment by ah0y** [comment]
the patch worked for me

**Comment by kpoelhekke** [comment]
@marklawlor what can be expected from `expo-router` regarding this issue? Is this really a bug or is this expected behavior?

We have a pretty large app, and this behavior easily lead to bugs when navigating between tabs via deeper nested stacks. Also because a lot of times the `<Redirect />` component sends users to a screen in a different tab and they're not able to go back. We have some workarounds in place now, but it is definitely a big concern here and causes cognitive overhead for our developers going forward.

The `params.initial = false` also doesn't always work when working with nested Stacks.

Would be nice to know if this is on the roadmap or if this is too big of a breaking change to implement.

**Comment by kpoelhekke** [comment]
Thanks for your answer! 🙏  I'll start using the beta version and see if the problem(s) still exist. If so I'll see if I can make some time tomorrow or next week to create some example cases of issues we're experiencing and figure out if they have a different root cause than the issue at hand.

**Comment by kpoelhekke** [comment]
@marklawlor  I've created an example repo of issues we're facing. I think most of them are related to this issue although I'm not sure if they are intended behavior or not. I expect they are not.

https://github.com/kpoelhekke/expo-router-nested-stack-example

Please let me know if you think the issues are related or not and if they show expected behavior or not. If not I will create a new issue on the repo.


## Navigating to a stack which is part of the same stack and a sibling of (tabs). (probably related)

I would expect that when navigating to a deeper page in a different stack always respects the `initialRouteName: "index"` so the stack will have the same state as when you would refresh on that page.

Expected state: `[(tabs), [/settings/index, /settings/deeper]]`
Current state: `[(tabs), [/settings/deeper]]`

https://github.com/expo/expo/assets/1632377/412a8852-79b0-43c9-90c3-cb80d84f9c28

## Navigating to a different stack from a `modal` or `transparentModal`. (probably unrelated)

I would expect that when navigating from a modal screen it would close the modal. I know that you can close the modal first by `router.back()` but components inside the modal screen are unaware that they are part of a modal so the router should handle this properly and close the modal is my opinion.

https://github.com/expo/expo/assets/1632377/1539e45e-d553-4094-a8e9-ea417a0b49e5

## Redirecting to a deeper page in a stack of another tab should show the back buttons for those stacks. (probably related)

When redirecting to a nested stack in a different tab you're unable to go back to the inital routes of the stacks in that tab. I think this is the same issue as described in the issue at hand.

https://github.com/expo/expo/assets/1632377/29499646-f896-4aa7-ae25-ba091a24b8a5

**Comment by marklawlor** [comment]
@kpoelhekke Please create new issues for new conversations, otherwise you highjack someone else's support.

The default for React Navigation is to only load `initialRouteName` during deeplinking. It will not populate the history during normal navigation. I'll look into exposing some new options for the behaviour you are expecting

**Comment by jaslloyd** [comment]
@marklawlor I can confirm that this is still a bug on SDK 51 (I mean OG issue)

**Comment by laugepetersen** [comment]
Still facing the exact same issue. We cannot get back to the tab's root before visiting the tab initially. This means deeplinking or pushing a route to a tab, which has not been manually opened prior, will not work as intended.

**Comment by lishtvan** [comment]
+1 for this issue. Its a huge blocker.

**Comment by cseelus** [comment]
Really should be reopened, as it's still a problem with Expo 51

**Comment by CJMcGregor** [comment]
@marklawlor can this be reopened please? This is still a big problem.

**Comment by cbHasib** [comment]
Should be reopened. Its almost a year this issue haven't fixed yet. 
@marklawlor  please reopen this

**Comment by marklawlor** [comment]
This issue is over 6months old. If your still experiencing this issue please create a new issue and we'll address it.

**Comment by MateuszRostkowski** [comment]
I found out that right now if you are navigating to other routes you can add with anchor option 
- https://docs.expo.dev/versions/latest/sdk/router/#withanchor

Example:

```
router.push('/example/screen_in_example_tab', { withAnchor: true })
```

And this will set params.initial to true, so don't need to add this patch any more:

<img width="793" alt="Image" src="https://github.com/user-attachments/assets/1ad6111d-210c-4414-bb39-beadac0bffd2" />

**Comment by Parth-Bhanushali** [comment]
After struggling a lot, I managed to fix this weird issue.
Step 1: Define **initialRouteName** in the stack as following:

![Image](https://github.com/user-attachments/assets/4d952fa7-d4a4-49e7-bc41-d3ee28de4e98)

**Important**: When using `router.navigate(...)` or `<Link />`, it usually overrides the initialRouteName defined inside the layout file. To avoid this behavior use the `withAnchor` when using imperative api as following:

Step 2:

Imperative way:

![Image](https://github.com/user-attachments/assets/5a743c1e-4977-4059-9256-e965e7251289)

or if you use <Link />:

![Image](https://github.com/user-attachments/assets/a392127c-bb58-4fed-b944-6b1256cdd848)

Please note, that both of these steps are required and must be followed to get the correct behavior.

**Comment by RigoOnRails** [comment]
I am extremely tired of this same issue.

**Comment by osikes** [comment]
> After struggling a lot, I managed to fix this weird issue. Step 1: Define **initialRouteName** in the stack as following:
> 
> ![Image](https://github.com/user-attachments/assets/4d952fa7-d4a4-49e7-bc41-d3ee28de4e98)
> 
> **Important**: When using `router.navigate(...)` or `<Link />`, it usually overrides the initialRouteName defined inside the layout file. To avoid this behavior use the `withAnchor` when using imperative api as following:
> 
> Step 2:
> 
> Imperative way:
> 
> ![Image](https://github.com/user-attachments/assets/5a743c1e-4977-4059-9256-e965e7251289)
> 
> or if you use :
> 
> ![Image](https://github.com/user-attachments/assets/a392127c-bb58-4fed-b944-6b1256cdd848)
> 
> Please note, that both of these steps are required and must be followed to get the correct behavior.

The combination of the two steps, very much resolved it for me.
