### ISSUE TITLE
expo export -p web running into error: Missing package "@react-native-community/cli-plugin-metro

### ISSUE THREAD

**Issue by stevennhnk113** [expo/expo#26224]
### Expected:
`npx expo export -p web` to complete successfully 

### Actual:
Error occur:
```
➜  bug yarn web:build
env: load .env.production
env: export EXPO_USE_METRO_WORKSPACE_ROOT
Using src/app as the root directory for Expo Router.
Starting Metro Bundler
Web apps/frontend-expo/index.ts ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1465/1465)
Bundle             Size
─ index.web.js  2.77 MB

💡 JavaScript bundle sizes affect startup time. Learn more

Web Bundling complete 16944ms
Finished saving JS Bundles
Error: Missing package "@react-native-community/cli-plugin-metro/build/commands/bundle/saveAssets" in the project at: /Users/.../bug/apps/frontend-expo
This usually means "react-native" is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
Error: Missing package "@react-native-community/cli-plugin-metro/build/commands/bundle/saveAssets" in the project at: /Users/.../bug/apps/frontend-expo
This usually means "react-native" is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
    at resolveFromProject (/Users/.../bug/node_modules/@expo/cli/build/src/start/server/metro/resolveFromProject.js:34:15)
    at importFromProject (/Users/.../bug/node_modules/@expo/cli/build/src/start/server/metro/resolveFromProject.js:39:20)
    at Object.importCliSaveAssetsFromProject (/Users/.../bug/node_modules/@expo/cli/build/src/start/server/metro/resolveFromProject.js:72:12)
    at Object.exportAppAsync (/Users/.../bug/node_modules/@expo/cli/build/src/export/exportApp.js:128:53)
    at async exportAsync (/Users/.../bug/node_modules/@expo/cli/build/src/export/exportAsync.js:45:5)
```

### What platform(s) does this occur on?

Web

### SDK Version

49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 3.6.4 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    Expo Workflow: managed

### Demo repo: 
https://github.com/stevennhnk113/bug-demo

### Notes:
- This is a monorepos
- Need to use yarn v3 for workspace setup 
- Expo-Router and Metro are used
- the `dist` folder was generated and I can still run `npx serve dist`, however all the assets do not show up. Seems like the cli is failing to bundles assets in the `./frontend-expo/assets` folder

### Steps:
- At root level: `yarn install`
- Then: `yarn web:build` -> basically run `npx expo export -p web`

**Comment by stevennhnk113** [comment]
The problem is due to Tamagui packages.

**Comment by Ystarz** [comment]
I meet the problem too.Are you willing to share your solution?

> The problem is due to Tamagui packages.

**Comment by stevennhnk113** [comment]
> I meet the problem too.Are you willing to share your solution?I don't use Tamagui in my project

I removed all the individual packages (such as "tamagui/stack") provided by Tamagui and use the single master package and it fixed the problem.
