### ISSUE TITLE
Expo Client crashes unexpectedly after a few seconds

### ISSUE THREAD

**Issue by videni** [expo/expo#2622]
I can't see any error in console, expo client just exits in my iphone device, I don't know why, the developing experience is very bad. also , when I open expo client , the first page I see is user profile, I don't use this page much, I think it is best set the projects page as the first page.

**Comment by sjchmiela** [comment]
Hey, @videni, thanks for submitting the issue! To help you, I'll need answers for a couple of more questions:
1. Is Expo Client app updated? At the bottom of the _Projects_ tab there is a small _Client version_ info. Does it say `2.9.0.…`?
2. Does the app crash by itself, or does it crash when you open a certain experience? Sometimes it is the opened app code that may cause problems. (eg. if you try to log a whole `onLayout` event) Are you able to reproduce the crash with a Snack?
3. Is the app downloaded from the App Store, or built from `expo/expo` repo?

**Comment by sjchmiela** [comment]
I'll close this issue due to inactivity, I hope you've managed to resolve your problem! 🙂
