### ISSUE TITLE
fatal error: 'boost/preprocessor/control/expr_iif.hpp' file not found

### ISSUE THREAD

**Issue by juskek** [expo/expo#26223]
### Minimal reproducible example

https://github.com/expo/examples/tree/master/with-tv

### Summary

1. npx create-expo-app -e with-tv
2. cd into the project
3. export EXPO_TV=1
4. npx expo prebuild
5. yarn android 

Throws:
```
> Task :expo-modules-core:buildCMakeDebug[arm64-v8a]

... long stack trace ...

C/C++: /Users/justinkek/.gradle/caches/transforms-3/03658dcb6075d6cbc41f64dd0325babd/transformed/jetified-react-android-0.73.1-2-debug/prefab/modules/folly_runtime/include/folly/functional/Invoke.h:22:10: fatal error: 'boost/preprocessor/control/expr_iif.hpp' file not found
C/C++: #include <boost/preprocessor/control/expr_iif.hpp>
C/C++:          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C/C++: 1 error generated.

> Task :expo-modules-core:buildCMakeDebug[arm64-v8a] FAILED
```

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0-preview.4 => 50.0.0-preview.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native-tvos:  0.73.1-2
    Expo Workflow: bare

**Comment by joshuaben** [comment]
Confirming this.  I am experiencing it in all version from 50 - ^50.0.0-preview.7.  This is from a fresh install.

**Comment by ofurtumi** [comment]
I am facing the same problem on a similar machine MacOs 13.6, same binary versions did you find any workaround?

**Comment by geolffreym** [comment]
I have been reading about this. Seems like a solution for me:
https://github.com/expo/expo/issues/26942

**Comment by douglowder** [comment]
Agreed this seems to be the same issue as #26942 .
