### ISSUE TITLE
App crashing on first load after and OTA update with EAS

### ISSUE THREAD

**Issue by ewein** [expo/expo#26231]
### Minimal reproducible example

https://snack.expo.dev/@simplybenefits/failedeasupatecheck

### Summary

Hi, I'm having an issue where my app crashes on the first load after an OTA update. This issue happened before on a previous Expo SDK version then was fixed and is now happening again in SDK 49. The issue seems to be with expo-updates trying to auto update the app with the below code:
```
 const update = await Updates.checkForUpdateAsync();

 if (update.isAvailable) {
         await Updates.fetchUpdateAsync();
         await Updates.reloadAsync();
 }
```

My Sentry logs are saying the error is:

`f.fetchNativePackageName is not a function. (In 'f.fetchNativePackageName()', 'f.fetchNativePackageName' is undefined)
`

Any help with this would be appreciated as it's affecting my production application. 

SDK Version = 49.0.21
expo-updates version = 0.18.19
react-native version = 0.72.6
JS engine = jsc

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.5.2
      expo: ^49.0.6 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    npmGlobalPackages:
      eas-cli: 5.9.3
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by TreeOfLearning** [comment]
Hi @ewein, did you manage to resolve this? I'm seeing the same issue (although I don't believe it is an EAS updates issue and rather a sentry-expo issue).

**Comment by ewein** [comment]
@TreeOfLearning Yeah I think the issue lies with Sentry. I ended up downgrading my sentry-expo to 7.0.0 which seemed to do the trick for now.
