### ISSUE TITLE
[SDK50] expo-image doesn't work on web anymore

### ISSUE THREAD

**Issue by kvaster** [expo/expo#26247]
### Minimal reproducible example

<Image source="assets/splahs.png"/>

### Summary

expo-image no longer works on web with following error:

React does not recognize the `nativeViewRef` prop on a DOM element.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.6 Gentoo Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/bin/node
      Yarn: 4.0.2 - /usr/bin/yarn
      npm: 10.1.0 - /usr/bin/npm
      Watchman: 2023.06.19.00 - /usr/bin/watchman
    npmPackages:
      expo: ^50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

**Comment by denniske** [comment]
I got this error today with sdk 50. Here is a repro: https://github.com/denniske/skd50-expo-image-repro

**Comment by georgevicbell** [comment]
I recreated it https://github.com/expo/expo/issues/26611

**Comment by ecto** [comment]
I'm also running into this. It looks like this might be addressed by https://github.com/expo/expo/pull/25922
