### ISSUE TITLE
[SDK 50] Error on web when assigning Notifications

### ISSUE THREAD

**Issue by jparkrr** [expo/expo#26248]
### Minimal reproducible example

https://github.com/jparkrr/repro-web-notifications-crash

### Summary

The following code causes an error on web in SDK 50, where it worked before.

```js
import * as Notifications from 'expo-notifications';

// This is the line that causes the error.
const ExpoLibrary = Notifications
// Interestingly, calling methods on Notifications works.

// The reason I want to do it is because I want to use the following line
// ExpoLibrary.requestPermissionsAsync()
// where ExpoLibrary can also be something like expo-contacts
```

The error is:

```
bundle.js:1529 Uncaught Error: Cannot find native module 'ExpoNotificationCategoriesModule'
```

I can probably refactor to avoid assigning `Notifications`, but I just thought you should know, and it might be causing other issues.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - ~/.asdf/installs/nodejs/20.7.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.7.0/bin/yarn
      npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.02.13.00 - /Users/justin/code/custom-watchman/Cellar/watchman/2023.02.13.00/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ~50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

**Comment by thalida** [comment]
I also ran into this issue when importing expo-notifications on web, I wasn't doing any assignment. 

```tsx
// usePushNotifications.tsx
import * as Notifications from "expo-notifications";
```

To resolve for web, I created a mock file `usePushNotifications.web.tsx` that is a stub, and gets automagically imported by expo for web builds. I needed to create platform specific files for every place that imported notifications. It was a tad tedious, but a quick-n-easy way to get around the issue for now. 

Same temporary fix as noted on the expo-notifications web local storage issue: 
https://github.com/expo/expo/issues/23895#issuecomment-1676131183

**Comment by bnussman** [comment]
Holy cow! This issue was filed weeks before SDK 50 dropped and they still proceeded with the release 😮

**Comment by jparkrr** [comment]
I just double checked, and importing and using expo-notifications doesn't break on web for me. Just assigning as I originally mentioned. I've already worked around it, so for me this issue isn't too big of a deal.

Maybe you folks should file separate issues about notifications being broken on web? Or look more into how to minimally reproduce your particular issue, because I couldn't.
