### ISSUE TITLE
Expo's app.json does not have a direct configuration option for delaying the splash screen. V2

### ISSUE THREAD

**Issue by kolaade271** [expo/expo#26252]
### Summary

{
  "expo": {
    "icon": "./assets/iconpsg.png",
    "scheme": "acme",
    "splash": {
      "image": "./assets/splashpsg.png",
      "resizeMode": "contain",
      "backgroundColor": "#191970",
    },
    "ios": {
      "userInterfaceStyle": "automatic"
    },
    "android": {
      "softwareKeyboardLayoutMode": "pan",
      "userInterfaceStyle": "automatic",
      "package": "com.kolly271.paysnugpos"
    },
    "plugins": [
      "expo-router"
    ],
    "name": "ppp",
    "slug": "ppp",
    "extra": {
      "router": {
        "origin": false
      },
     
    }
  }
}

there is no way to delay the splash screen and no documentation for this  am using v2

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/splash-screen/

**Comment by brentvatne** [comment]
use this API: https://docs.expo.dev/versions/latest/sdk/splash-screen/#splashscreenpreventautohideasync

**Comment by kolaade271** [comment]
If I know how to use it  in the router layout app , you just close my ticket without understanding the issue
