### ISSUE TITLE
[SDK 50] EAS dev build hot reload does not work

### ISSUE THREAD

**Issue by smashboy** [expo/expo#26254]
### Minimal reproducible example

https://github.com/smashboy/expo-sdk-50-escape-char-bug

### Summary

Hello everyone! Currently for me hot reload does not work with SDK v50 on windows (android app). The app only applies the changes after manually reloading the app using the reload button in dev tools and yes i checked if hot reload is enabled, it is.

1.  npx create-expo-app -t blank@beta my-app
2.  cd my-app
3.  npx expo install expo-dev-client
4.  eas login
5.  eas build:configure
6. eas build --profile development --platform android
7.  npx expo start --dev-client

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.6.0 - C:\Program Files\nodejs\node.EXE        
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11076708
    npmPackages:
      expo: ~50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    Expo Workflow: managed

**Comment by JohnAnselmi** [comment]
Just tacking on my +1 here. I'm having this same issue exactly as @smashboy described. I'm on Ubuntu. Otherwise same expo/react versions. 

I tried spinning up a totally new expo project. Same problem there.  For what it is worth, I am using Expo Router v3.4.1

### Environment
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.19 - ~/.npm-global/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    npmPackages:
      expo: ^50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by junchenjun** [comment]
Same issue, everything works fine on iOS, hot reload stopped working on Android after the upgrade, also unable to connect my physical Android device to the dev server

**Comment by techied** [comment]
I believe facebook/metro#877 is related

**Comment by Gamote** [comment]
We experience the same behaviour, no hot-reloading and no `console.log`.

_Issue visible in this MRE: https://github.com/Gamote/expo-babel-void-optional-chain-issue_

**Comment by marcel-mintouge** [comment]
Has this fix solved the `console.log` for anyone?

**Comment by JohnAnselmi** [comment]
The full release of SDK 50 solved the issue on my end.

**Comment by Gamote** [comment]
> Has this fix solved the `console.log` for anyone?

Same for us, we can see the `console.log`s and hot-reloading is working again.

**Comment by marcel-mintouge** [comment]
@JohnAnselmi @Gamote Is it `50.0.4` the version you've installed?

**Comment by Gamote** [comment]
> @JohnAnselmi @Gamote Is it `50.0.4` the version you've installed?

Yes. Not sure how useful it is, but I have deleted the `.expo`, `node_modules`, `yarn.lock`, `ios` and `android` just to know that I've started "clean".

**Comment by marcel-mintouge** [comment]
Made it work. It seems I had old dependencies to metro from previous versions of the app, I removed those dependencies and started working :+1:

**Comment by tico86** [comment]
@marcel-mintouge could you explain what you did exactly?

**Comment by tico86** [comment]
``

> @marcel-mintouge could you explain what you did exactly?

`  "resolutions": {
    "metro": "0.76.0",
    "metro-resolver": "0.76.0",
    "react-refresh": "~0.14.0"
  },
  "overrides": {
    "metro": "0.76.0",
    "metro-resolver": "0.76.0",
    "react-refresh": "~0.14.0"
  },`
  
  i removed these deps from package.json and now everything works fine

**Comment by marcel-mintouge** [comment]
@tico86  That's exactly what I removed and solved my issue

**Comment by NiccoloCase** [comment]
I'm having the same issue on expo sdk 48. I cannot upload to a new sdk

**Comment by dealvz** [comment]
Same issue on Expo Go. 
Deleted same deps and .expo and node_modules

works fine now

**Comment by viktorvidual** [comment]
I had the same issue, but updating to SDK 50 solve it for me.

**Comment by shoko-dev** [comment]
Same issues here! Migrated from sdk 48 to 50. hot restart no longer works. I tried deleting node modules, expo doesn't help.

**Comment by shoko-dev** [comment]
> > Same issues here! Migrated from sdk 48 to 50. hot restart no longer works. I tried deleting node modules, expo doesn't help.
> 
> @shoko-dev Check for any now unnecessary resolutions in your package.json. Also, if you're using Expo Router make sure you're making the changes required to follow the SDK 50 setup instructions found here --> https://docs.expo.dev/router/installation/#quick-start
> 
> Once that is all good to go for sure, I would delete /node_modules, /.expo, yarn.lock/package-lock.json, and ios/android folders, run yarn/npm, then run expo-doctor.
> 
> If you're still having issues after that, I would try spinning up a new project folder with `npx create-expo-app` and move your source over to that new project. I don't know why, but that has helped me solve some weird SDK upgrade errors in the past.
> 
> Good luck!

Thanks for the advice. I have already tried to create a new project from scratch, alas, this did not solve my problem. This is most likely due to the fact that I use react navigation. I'll try to delete all the folders again, if it doesn't help, I'll try switching to Router. It's kind of sad. Just in case, I'm attaching my package.json
[package.json](https://github.com/expo/expo/files/14880361/package.json)

**Comment by wodin** [comment]
One thing that seems to cause hot reload to break is if you are running `npx expo start` within WSL, but the files live on the Windows filesystem. Also, it might break if your project is under the OneDrive or Dropbox directories.

If you're using WSL, see https://expo.dev/wsl

**Comment by HarunKilic** [comment]
Still having this issue on SDK 51.

**Comment by drakulic-goran** [comment]
Me too.  I try everything, check all packages, delete node_modules, package-lock.json, cache, reinstall all, and nothing helped...
Migrate from SDK 50 to 51 make this form me.

**Comment by vendramini** [comment]
Same problem here. It's so annoying when this kind of bug happens, there's no way to debug neither reproduce on sandbox. At the time being I'm stuck having to reload the entire app every time I hit save. I don't have watchman installed and my setup is a nx monorepo - this problem doesn't seem to be related to monorepos.

Does anyone has any clue?
```
"expo": "~50.0.19",
"metro": "~0.80.4",
"metro-react-native-babel-transformer": "^0.76.7",
"@expo/cli": "0.17.11",
"@expo/metro-runtime": "3.1.3",
"webpack-cli": "^5.1.4"
```
metro.config.js
```javascript
const { withNxMetro } = require('@nx/expo');
const { getDefaultConfig } = require('@expo/metro-config');
const path = require('path');
const defaultConfig = getDefaultConfig(__dirname);

module.exports = (async () => {
  defaultConfig.transformer.babelTransformerPath = require.resolve(
    'react-native-svg-transformer',
  );
  defaultConfig.resolver.assetExts = defaultConfig.resolver.assetExts.filter(
    (ext) => ext !== 'svg',
  );
  defaultConfig.resolver.sourceExts.push('svg');
  return withNxMetro(defaultConfig, {
    // Change this to true to see debugging info.
    // Useful if you have issues resolving modules
    debug: false,
    // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
    extensions: [],
    // the project root to start the metro server
    projectRoot: __dirname,
    // Specify any additional (to projectRoot) watch folders, this is used to know which files to watch
    watchFolders: [path.resolve(__dirname, '../../libs')],
  });
})();
```

**Comment by ArtRabbit** [comment]
Having this issue with expo 51 and a dev build on Android. I don't have any of the problematic entries in package.json. Is there anything I can try?

**Comment by Shilllo** [comment]
I'm having the same problem with Expo Go on my iPhone. I use both a PC and a laptop, and I perform the same actions on both devices. The app works perfectly on my laptop, but on my PC, there is no fast refresh, and even a basic reload does not apply any changes.

**Comment by wodin** [comment]
What are you running on the PC? WSL? Windows? Linux?

**Comment by Shilllo** [comment]
> What are you running on the PC? WSL? Windows? Linux?

On wsl

**Comment by vktrl** [comment]
Having the same issue.

No hot reloads or console activity:
- Expo Go app + macOS server
- Expo Go + WSL2 server

Working:
- iOS dev client
- iOS emulator
- Web

Tried versions `51.0.4`-`51.0.8`

**Comment by wodin** [comment]
> On wsl

Make sure you have nodejs and your project installed inside WSL. Do not store your files in the Windows filesystem and access them from there.
https://github.com/expo/fyi/blob/main/wsl.md#important-your-expo-project-must-be-entirely-on-the-linux-filesystem

**Comment by imadeddine000** [comment]
> Still having this issue on SDK 51.

hey brother did you find any solution to that problem

**Comment by HarunKilic** [comment]
> > Still having this issue on SDK 51.
> 
> 
> 
> hey brother did you find any solution to that problem

Yea, a temporary solution would be using http instead of https. 
But went with permanent solution, and that is something I did not expect. Its flutter 😆. Not because of this issue ofc.

**Comment by drakulic-goran** [comment]
Any solution?

**Comment by MohammedAlSafwanCNTXT** [comment]
any update?

**Comment by GHUApsynet** [comment]
On Windows + WSL, I can't upgrade to Expo 50 or 51 because of this issue. And i'm guessing Expo 52 will be the same.

**Comment by wodin** [comment]
@GHUApsynet did you set things up as per the recommendations here?
https://expo.fyi/wsl

**Comment by GHUApsynet** [comment]
> @GHUApsynet did you set things up as per the recommendations here? https://expo.fyi/wsl

Nodejs and my project are both installed in WSL. I'm using VS Code with the WSL extension. And I'm using the `--tunnel` option.

Expo 49 works fine.

But for Expo 50+, on a brand new project with `npx create-expo-app@latest`, after adding `expo-dev-client` and after building a dev client, I lose the hot-refresh and logs.

With Expo Go alone, I have the hot-refresh and logs though.

**Comment by kztera** [comment]
> > [@GHUApsynet](https://github.com/GHUApsynet) did you set things up as per the recommendations here? https://expo.fyi/wsl
> 
> Nodejs and my project are both installed in WSL. I'm using VS Code with the WSL extension. And I'm using the `--tunnel` option.
> 
> Expo 49 works fine.
> 
> But for Expo 50+, on a brand new project with `npx create-expo-app@latest`, after adding `expo-dev-client` and after building a dev client, I lose the hot-refresh and logs.
> 
> With Expo Go alone, I have the hot-refresh and logs though.

This is exactly what I am facing. There is no way out, having to reload R constantly makes me bored

**Comment by Harrylever** [comment]
I was suddenly not getting any hot reloads on my app. tapped M on terminal to toggle Menu on Mobile and
clicked `Enable Fast Refresh`.

And I got hot reload working again. Might be the same for someone else.
