### ISSUE TITLE
[SDK 50] Local custom native module doesn't compile for android

### ISSUE THREAD

**Issue by jparkrr** [expo/expo#26256]
### Minimal reproducible example

https://github.com/jparkrr/repro-module-build-error

### Summary

I have a local native module, build with the expo modules API, that isn't compiling under sdk 50. it was working before.

I have created the module with
```
npx create-expo-module@next --local
```
and just gone with all the defaults.

During the build (using EAS), I get this error and the build fails:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':my-module:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

https://expo.dev/accounts/reachvote/projects/repro-module-build-error/builds/d32df12e-5d73-4f28-81a1-c07993e3929f

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/shims/yarn
      npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.02.13.00 - /Users/justin/code/custom-watchman/Cellar/watchman/2023.02.13.00/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: managed

**Comment by jparkrr** [comment]
Anyone know what I should put in my build.cradle to work around this?

**Comment by jparkrr** [comment]
@Kudo gave the answer on discord. It seems to be working for me!

```
  def agpVersion = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION
  if (agpVersion.tokenize('.')[0].toInteger() < 8) {
    compileOptions {
      sourceCompatibility JavaVersion.VERSION_11
      targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
      jvmTarget = JavaVersion.VERSION_11.majorVersion
    }
  }
```

https://discord.com/channels/695411232856997968/1009056414028812299/1194550582107721859

**Comment by Kudo** [comment]
i've added a section of the migration guide in the [fyi page](https://expo.fyi/expo-modules-gradle8-migration#error-task-current-target-is-17-and-compilereleasekotlin-task-current-target-is-11-jvm-target-compatibility-should-be-set-to-the-same-java-version). we will also mention this migration later in our blog post in the sdk 50 official release.
i'm closing this issue. thanks for the update.

**Comment by foxysolutions** [comment]
Additionally, when using only standard modules and building Expo SDK 50 towards Android (so without an own `build.gradle` file), it will also help to upgrade the Android image used for building.

Add the following to your `eas.json` file:
```
"build": {
  "production": {
    "android": {
      "image" : "latest"
    }
  }
}
```
Reason for this can be found at [Infrastructure documentation](https://docs.expo.dev/build-reference/infrastructure/). Where the default runs on ubuntu-22.04-jdk-11-ndk-r21e (Java 11) while 'latest' runs on ubuntu-22.04-jdk-17-ndk-r21e (Java 17).

**Comment by Tony-KOTH** [comment]
> Additionally, when using only standard modules and building Expo SDK 50 towards Android (so without an own `build.gradle` file), it will also help to upgrade the Android image used for building.
> 
> Add the following to your `eas.json` file:
> 
> ```
> "build": {
>   "production": {
>     "android": {
>       "image" : "latest"
>     }
>   }
> }
> ```
> 
> Reason for this can be found at [Infrastructure documentation](https://docs.expo.dev/build-reference/infrastructure/). Where the default runs on ubuntu-22.04-jdk-11-ndk-r21e (Java 11) while 'latest' runs on ubuntu-22.04-jdk-17-ndk-r21e (Java 17).

Hi @foxysolutions I am getting similar kind of error:
```
Execution failed for task ':expo-linear-gradient:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```
I tried with the latest image and still it's not working.
```
"preview": {
      "extends": "production",
      "distribution": "internal",
      "ios": { "simulator": true },
      "android": { "buildType": "apk", "image": "latest" }
    },
```
Please help me out.

**Comment by foxysolutions** [comment]
@Tony-KOTH annoying it didn’t work. What also helped for me, was to upgrade the impeding module. Mine was ‘expo-permissions’ yours seem to be ‘expo-linear-gradient’.

Given this package to be at 12.7.1 ([link](https://www.npmjs.com/package/expo-linear-gradient)), ensure you also have this latest version installed. That won’t happen with expo update on npm install, hence specify the version explicitly and build again.

hope this will do the trick for you as well. Good luck and let me know!

**Comment by Tony-KOTH** [comment]
> @Tony-KOTH annoying it didn’t work. What also helped for me, was to upgrade the impeding module. Mine was ‘expo-permissions’ yours seem to be ‘expo-linear-gradient’.
> 
> Given this package to be at 12.7.1 ([link](https://www.npmjs.com/package/expo-linear-gradient)), ensure you also have this latest version installed. That won’t happen with expo update on npm install, hence specify the version explicitly and build again.
> 
> hope this will do the trick for you as well. Good luck and let me know!

Yeah updating it works, Thanks.

**Comment by misharexviashvili** [comment]
I was getting same error but I noticed that I was also getting : > Task :expo-permissions:compileDebugKotlin FAILED.
I installed expo-permissions and now it runs fine.

**Comment by shellatomic** [comment]
Any help for this type of issue:

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':expo-device:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 6m 31s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
841 actionable tasks: 841 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

**Comment by shellatomic** [comment]
Any help guys for this type of issue ???


FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':expo-notifications:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

**Comment by shellatomic** [comment]
> Any help guys for this type of issue ???
> 
> 
> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':expo-notifications:compileReleaseKotlin'.
> > 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

I found the solution:

- Delete yarn.lock
- Don't use yarn add, use expo install <Package-Name>

**Comment by shellatomic** [comment]
> Any help guys for this type of issue ???
> 
> 
> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':expo-notifications:compileReleaseKotlin'.
> > 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

I found the solution:

Delete yarn.lock after that Don't use yarn add, use expo install <Package-Name>

**Comment by shellatomic** [comment]
> Any help guys for this type of issue ???
> 
> 
> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':expo-notifications:compileReleaseKotlin'.
> > 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

I found the solution:

1. Delete yarn.lock
2. Don't use yarn add, use expo install Package-Name
