### ISSUE TITLE
expo-screen-orientation doesnt work on Expo48 iOS

### ISSUE THREAD

**Issue by Judy0406-CJ** [expo/expo#26264]
### Minimal reproducible example

https://snack.expo.dev/@willsfeng/orientation

### Summary

Above snack code will change the orientation to LANDSCAPE. It works on Expo49, but not for Expo48. 

### Environment

Expo Snack

**Comment by brentvatne** [comment]
please update to sdk 49, we made many improvements to expo-screen-orientation in that version. if the issue persists, create a new issue for it. thank you!
