### ISSUE TITLE
[SDK 50] [expo-image] tintColor not working in Android

### ISSUE THREAD

**Issue by alex-fournier** [expo/expo#26270]
### Minimal reproducible example

https://github.com/alex-fournier/expo-sdk-50-expo-image

### Summary

`tintColor` is not working on my Android device (Pixel 7 on Android 14), neither in props, nor in style. It works fine in iOS simulator.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2023.09.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 28, 30, 31, 32, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2
        System Images: android-21 | ARM EABI v7a, android-24 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.0-preview.7 => 50.0.0-preview.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: managed

**Comment by lukmccall** [comment]
Hello @alex-fournier, thank you for reporting the issue. I attempted to replicate the bug but was unable to do so. I tested it on a Samsung and Pixel device, as well as a few simulators. Do you have any other Android device available to verify if the issue persists on them as well?
![image](https://github.com/expo/expo/assets/9578601/720983e6-275f-4db6-9881-8a5e2b9a05c1)

**Comment by alex-fournier** [comment]
I have tested on Pixel 7, Samsung Galaxy Note 4 and Pixel 6 Pro (emulator) and I have the same result on these three devices. Is there something in my environment that can cause this bug? (OS? node version ?)

**Comment by alex-fournier** [comment]
I have also tested on a Windows PC and I have the same result :(

**Comment by lukmccall** [comment]
That's weird, but we will publish a new version of the `expo-image` soon. The new version will contain some fixes connected with the tint color on the Android. Once the update is live, I will revisit the issue.

**Comment by alex-fournier** [comment]
I have upgraded to latest `expo` and `expo-image`. Still the same result with Expo Go. BUT, if I build an apk, it works well.

**Comment by hichemfantar** [comment]
@alex-fournier can you try it with a custom dev client?

**Comment by alex-fournier** [comment]
I did, it works with a custom dev client but not in Expo Go.

**Comment by lukmccall** [comment]
The updated version of Expo Go with the latest fixes has not yet been released. However, it is expected to go live soon. As the tint color is working well when using a custom dev client, I will close the issue for now. I believe it should work in Expo Go soon too. If you encounter the same issue again, please feel free to open a new issue.

**Comment by erickreutz** [comment]
it's worth noting that I ran into an issue where tintColor was not working on Android but was on iOS. The problem was that I was using currentColor inside the SVG which seems to break the tintColor on android. Changing it to black fixed the issue.
