### ISSUE TITLE
[Question] Expo: NSAllowsArbitraryLoads

### ISSUE THREAD

**Issue by hermanthotan** [expo/expo#2627]
I have question regarding the expo cli.
I create the new project using expo-cli, it doesn't come out with ios and android folder
My question is right now i would like to use 'http' for the development.
Based on what i have searching start from ios 9, ios is required 'https'

How to add this in my reactnative prj

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
</dict>
</plist>
```

My project structure i can't find ios folder?
<img width="281" alt="screenshot 2018-11-06 at 7 17 45 pm" src="https://user-images.githubusercontent.com/39150743/48061045-ad463a80-e1f8-11e8-840e-7f8fd8e1eccd.png">

I try this below by putting on app.json, under ios it doesn't work.
`    "ios": {
      "supportsTablet": true,
      "infoPlist": {
        "NSAppTransportSecurity": {
          "NSAllowsArbitraryLoads": true
        }
      }
    },`

What is the step to make it for 'http' protocol work?

**Comment by rakibtg** [comment]
the expo team still ignoring this issue 👎

**Comment by anthonytoorie** [comment]
sad

**Comment by hyochan** [comment]
I thought the default flag in `NSAllowsArbitraryLoads` is already `true`.
[Link](https://github.com/expo/expo/blob/b63177ef09e29c495f058a21d94d8fe12fbfbe1f/ios/Exponent/Supporting/Info.plist#L87)

**Comment by esamelson** [comment]
Hi there, apologies that this got missed. "How-to" questions like this are better suited for our [forums](https://forums.expo.io) in the future. Indeed this key is set to `true` in the Expo client and in all standalone apps. I'm going to go ahead and close this issue as it's been inactive for quite some time.
