### ISSUE TITLE
 no result in Notifications.getExpoPushTokenAsync  

### ISSUE THREAD

**Issue by darbaoui** [expo/expo#2628]
Hey All,

I have an issue with `Notifications.getExpoPushTokenAsync`, i m using `FCM for Push Notifications`, but the token cannot be generated at this point.

```javascript
async function registerForPushNotificationsAsync() {

  const { status: existingStatus } = await Permissions.getAsync(
    Permissions.NOTIFICATIONS
	);
	
  let finalStatus = existingStatus;

  
  if (existingStatus !== 'granted') {
   
    const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
    finalStatus = status;
  }

  
  if (finalStatus !== 'granted') {
    return;
  }

// Token cannot be returned
let token = await Notifications.getExpoPushTokenAsync();
```
any idea or suggestions.

**Comment by darbaoui** [comment]
issu resolved by 
1. update Expo Client
2. remove `node_modules` by using this command `rm -rf node_modules`
2. i'm used `yarn` instead of `npm`.

**Comment by faustoct** [comment]
@darbaoui is that detach expo project ?

**Comment by dajohnny** [comment]
Can I know which SDK version are you using?  I meeting that same issue

**Comment by dajohnny** [comment]
@darbaoui  Can I know which SDK version are you using? I meeting that same issue
