### ISSUE TITLE
App crashes when calling ImagePicker.launchCameraAsync [Expo-SDK-49] Latest

### ISSUE THREAD

**Issue by hootan09** [expo/expo#26294]
### Minimal reproducible example

https://snack.expo.dev/@muflah_n/expo-image-picker

### Summary

I am trying to launch the camera on a real device( issue is only with iOS). The app exits when hits the function.
It is working fine using Expo Go. But crashes on eas production build.

What platform(s) does this occur on?
iOS

Also, the method "launchCameraAsync" from the "expo-image-picker": "^14.5.0" library crashes only in the EAS production build. It works fine on Expo Go and even on Expo development builds.
It's important to note that this method also works fine on iPad and Mac M series.
the issue is with some iPhones like iPhone 15 (IOS 17.1.2)

here is another sample code with above description:

```js
  const pickImage = async ({key, text}) => {
    openBottomSheet(false);
    // No permissions request is necessary for launching the image library
    const pickerOption = {
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: false,
      allowsMultipleSelection: false,
      selectionLimit: 1,
      base64: false,
      presentationStyle: ImagePicker.UIImagePickerPresentationStyle.AUTOMATIC,
      aspect: [4, 3],
      quality: 1,
    }

      switch (key) {
        case '2':
        {
            let result = await ImagePicker.launchCameraAsync();
            if (!result.canceled) {
              addImageToState(result.assets[0].uri);
            }
            break;
        }
        case '1': 
        {
            let result = await ImagePicker.launchImageLibraryAsync(pickerOption);
          if (!result.canceled) {
            addImageToState(result.assets[0].uri);
          }
          break;
        }
      }
  };
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.3.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.1.1 => 18.1.1
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.18.10 => 0.18.12
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: bare

**Comment by MadMods96** [comment]
same problem sometime it works fine and sometime when i click picture at crop stage it gets crashed

**Comment by brentvatne** [comment]
hey there! this isn't particularly actionable for us if you have not been able to actually reproduce it in the snack that you shared. please share a project that we can clone and run on a physical ios device to reproduce the crash as explained.

**Comment by hootan09** [comment]
> hey there! this isn't particularly actionable for us if you have not been able to actually reproduce it in the snack that you shared. please share a project that we can clone and run on a physical ios device to reproduce the crash as explained.

Closing the issue with just one comment is the least effective way to address it. There have already been several issues submitted for this crashing issue, all of which were closed without any reasonable response :(

**Comment by hootan09** [comment]
Hi again.
I fixed the problem of using the camera through expo-image-picker.
The issue came back to EAS cloud build caching packages. 
If we build the app with Xcode, the problem will be solved. 
Also, the EAS team needs to wipe the caches on their servers. 
Thank you

**Comment by ta-sakin** [comment]
Facing the same problem after taking a picture when I try to add it the app crashes. Happening on iOS v17.2.

**Comment by ARIARCHI-MZ** [comment]
Hi everyone I have an issue with ImagePicker.launchCameraAsync with IOS version 17 and expo SDK 50.
both getCameraPermissionsAsync and getMediaLibraryPermissionsAsync are granted but ImagePicker.launchCameraAsync doesn't execute.
The camera opens for less than a second and then closes automatically, is there any solution for it?

the sample of code

  getPermission = async () => {
    let cameraPermission = await ImagePicker.getCameraPermissionsAsync();
    if (cameraPermission.status !== "granted") {
      await ImagePicker.requestCameraPermissionsAsync();
    }
 let mediaPermission = await ImagePicker.getMediaLibraryPermissionsAsync();
    if (mediaPermission.status !== "granted") {
      await ImagePicker.requestMediaLibraryPermissionsAsync();
 }

pickImage = async (source) => {
    await this.getPermission();
    let result = {};
    if (source === "camera") {
      try {
        result = await ImagePicker.launchCameraAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.Images,
          base64: true,
          aspect: [1, 1],
          quality: 0.2,
        });
/// rest of code
  };

**Comment by ARIARCHI-MZ** [comment]
Hi everyone I have an issue with ImagePicker.launchCameraAsync with IOS version 17 and expo SDK 50.
both getCameraPermissionsAsync and getMediaLibraryPermissionsAsync are granted but ImagePicker.launchCameraAsync doesn't execute.
The camera opens for less than a second and then closes automatically, is there any solution for it?

the sample of code

getPermission = async () => {
let cameraPermission = await ImagePicker.getCameraPermissionsAsync();
if (cameraPermission.status !== "granted") {
await ImagePicker.requestCameraPermissionsAsync();
}
let mediaPermission = await ImagePicker.getMediaLibraryPermissionsAsync();
if (mediaPermission.status !== "granted") {
await ImagePicker.requestMediaLibraryPermissionsAsync();
}

pickImage = async (source) => {
await this.getPermission();
let result = {};
if (source === "camera") {
try {
result = await ImagePicker.launchCameraAsync({
mediaTypes: ImagePicker.MediaTypeOptions.Images,
base64: true,
aspect: [1, 1],
quality: 0.2,
});
/// rest of code
};
