### ISSUE TITLE
iOS device builds using the expo-dev-client and realm stall on bundling

### ISSUE THREAD

**Issue by takameyer** [expo/expo#26298]
### Summary

In dev-client projects using `realm`, when running on an actual iOS device, bundling will stall.  The bundling will occur and stop on "Bundling 100%".

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

   9   │   "dependencies": {
  10   │     "@realm/react": "^0.6.0",
  11   │     "expo": "^49.0.21",
  12   │     "expo-dev-client": "~2.4.8",
  13   │     "expo-splash-screen": "~0.20.5",
  14   │     "expo-status-bar": "~1.6.0",
  15   │     "react": "18.2.0",
  16   │     "react-native": "0.72.6",
  17   │     "react-native-get-random-values": "~1.9.0",
  18   │     "realm": "^12.5.1"
  19   │   },

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/andrew.meyer/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
      Android SDK:
        Android NDK: 23.1.7779620
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9301383
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.21 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: bare

### Reproducible demo

Repo code here:
https://github.com/takameyer/expo-ios-bug

Open the xcworkspace in Xcode and build on an actual iOS device.  Then attempt to load the bundle by connecting to the dev-client.

**Comment by jayshah123** [comment]
Can we do a patch release on 2.x versions of expo-dev-client/expo-dev-launcher?
