### ISSUE TITLE
Document picker URI on Android

### ISSUE THREAD

**Issue by ahmed-wagdi** [expo/expo#263]
I was using the DocumentPicker API to fetch and upload files to a certain server, it's working on iOS but on android the URI returned isn't the same as iOS.

**iOS URI:**
file:///private/var/mobile/Containers/Data/Application/D2D35585-A8E7-4E69-A464-B9FD772AB16F/tmp/host.exp.Exponent-Inbox/filename.docx

**android URI:**
content://com.android.providers.downloads.documents/document/9444

Here's a recreation of the problem:
https://snack.expo.io/ryfSWKRGW

I also included the ImagePicker component to show that the URI returned is correct as opposed to the DocumentPicker

**Comment by nikki93** [comment]
It wouldn't be the same URI because it's a different device... What kind of output are you expecting?

**Comment by ahmed-wagdi** [comment]
@nikki93 except that when selecting an image using expo's ImagePicker component the uri returned is exactly like the one listed above for iOS (returns the path to the file on the device).

So basically right now the URI returned from the ImagePicker and DocumentPicker on both platforms is as follows:

**iOS - ImagePicker:**
file:///private/var/mobile/Containers/Data/Application/D2D35585-A8E7-4E69-A464-B9FD772AB16F/tmp/host.exp.Exponent-Inbox/file_name.jpg


**iOS - DocumentPicker:**
file:///private/var/mobile/Containers/Data/Application/D2D35585-A8E7-4E69-A464-B9FD772AB16F/tmp/host.exp.Exponent-Inbox/filename.docx


**Android - ImagePicker:**
file:///private/var/mobile/Containers/Data/Application/D2D35585-A8E7-4E69-A464-B9FD772AB16F/tmp/host.exp.Exponent-Inbox/filename.jpg


**Android - DocumentPicker:**
content://com.android.providers.downloads.documents/document/9444

So as you can see the android DocumentPicker URI returns a weird results compared to all the others. I would also like to point out that selecting the exact same image using the ImagePicker and DocumentPicker will return a different format for each.

**Comment by satya164** [comment]
The URI depends on the app which returned it. It could be a real file URI or a content URI that's resolved by some app. If upload isn't working for `content://` URIs for you, then there's a bug in your code.

**Comment by nikki93** [comment]
cc @janicduplessis 

Is the `content://` URI not useable? What are you trying to use the URI for?

**Comment by ahmed-wagdi** [comment]
I'm trying to upload the file to our backend server. The normal file path works fine but the `content://` path always fails.

**Comment by ahmed-wagdi** [comment]
Found the solution and like you said it was a bug in my code. Wasn't setting the MIME type of the file correctly in my fetch request.

Instead of `type: fileType,` it should've been `type: "application/" + fileType`. Not entirely sure why this is an Android only problem though.

More info here:
https://github.com/facebook/react-native/issues/7306

**Comment by martinezguillaume** [comment]
But, how do you know the fileType ? I have this kind of result from `DocumentPicker`:

```js
file: {
  name: "Over the horizon"
  size: 3076096
  type: "success"
  uri: "content://com.android.providers.media.documents/document/audio%3A21"
}

**Comment by maharjanaman** [comment]
Is there way to get files in base64 yet?

**Comment by Mislavoo7** [comment]
@maharjanaman you can use  https://github.com/itinance/react-native-fs
I'm using it like:
`  runPicker() {
    DocumentPicker.show({
      filetype: ['*/*'],
    },(error,res) => {
       // get file from file system as base64
      RNFS.readFile("file://"+res.uri, 'base64')
        .then((file) => {
          let document = { 
            type: res.fileType,
            source: file,
            localLink: res.uri,
            fileName: res.fileName,
            fileSize: res.fileSize
          };
          console.log(document);
        })
    });
  }
`

**Comment by zahrakbri** [comment]
Still I'm getting a weird URI. I have checked type.
