### ISSUE TITLE
Using Insufficient Permission Validation Functions in Android [SDK-48] 

### ISSUE THREAD

**Issue by kjh0813** [expo/expo#26301]
### Minimal reproducible example

https://snack.expo.dev/@koiwaredev/android-permission

### Summary

The application is currently utilizing functions with inadequate permission validation in Android (checkCallingOrSelfPermission(), checkCallingOrselfuriPermission()). 
Is it possible to consider changing these functions in Android to checkCallingPermission() or enforceCallingPermission() to ensure that the application verifies proper permissions?

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
      npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
      Watchman: 2023.09.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/test/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.1 => 9.3.1 
      expo: ~48.0.0 => 48.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.13.2
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi @kjh0813 - Your snack is just the default provided by Snack and doesn't demonstrate any issue. Can you explain what the problem is and provide an example demonstrating it?
