### ISSUE TITLE
[expo-barcode-scanner] [Android] [iOS] Problem reading the barcode with black background

### ISSUE THREAD

**Issue by dembal1990** [expo/expo#26316]
### Minimal reproducible example

https://snack.expo.dev/@dembal1990/barcode-scanner-example

### Summary

I try to scan this white barcode with black background. 

 *  Barcode type: ean13 
 * Platform: IOS and Android

![IMG_20240102_094903](https://github.com/expo/expo/assets/12534315/96b784f9-186a-40dd-8a1a-a262b2b53b95)

### Environment

``` 
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 31, 32, 33, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.2
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ^49.0.16 => 49.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
- you didn't specify which platform you are using
- what barcode format is that?

**Comment by dembal1990** [comment]
@brentvatne 
I have updated the issue description with barcode type and platform. 
Th barcode is on the attached pitcure.

**Comment by Evil85** [comment]
@brentvatne 

Why did you close the issue ?
We gave every necessary  details in description.

**Comment by brentvatne** [comment]
thanks for providing that info! i believe what is happening here is that [the underlying barcode scanner libraries we are using do not handle white on black barcodes very well](https://stackoverflow.com/questions/41518373/zxing-library-not-scanning-qr-code-black-background-and-white-codenegative-scan). when scanning barcodes of this type, you might want to have the user take a photo and then invert the colors in the image. cc @amandeepmittal - we can update the docs about this

**Comment by amandeepmittal** [comment]
Added the known issue on BarCodeScanner API reference page in #26629.
