### ISSUE TITLE
GLView.takeSnapshotAsync crashes on Android if `framebuffer` opt is specified

### ISSUE THREAD

**Issue by steveliles** [expo/expo#2631]
When using a headless GLView via `createContextAsync`, you can grab a snapshot with `GLView.takeSnapshotAsync`, specifying a framebuffer to snapshot via opts, e.g: 

```
GLView.takeSnapshotAsync(gl, {
  framebuffer: fbo,
  format: 'jpeg',
  compress: 1.0,
  flip: true
})
```

On iOS this works well, but on Android the app crashes with:

```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at expo.modules.gl.GLContext$3.run(GLContext.java:206)
        at expo.modules.gl.GLContext$GLThread.run(GLContext.java:338)
```

This problem only occurs if you set the `framebuffer` property in opts. There is a simple workaround - bind the framebuffer you want to snapshot, then omit the `framebuffer` property from opts, e.g:

```
gl.bindFramebuffer(gl.FRAMEBUFFER, fbo);
GLView.takeSnapshotAsync(gl, {
  format: 'jpeg',
  compress: 1.0,
  flip: true
})
```

**Comment by tsapeta** [comment]
Hey @steveliles, thanks for letting us know about this issue! 😉 I'll fix it in the next release.

**Comment by steveliles** [comment]
... very similar/same crash if I set the `rect` opt too:

```
    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at expo.modules.gl.GLContext$3.run(GLContext.java:192)
        at expo.modules.gl.GLContext$GLThread.run(GLContext.java:338)
```
