### ISSUE TITLE
TypeError: (0 , _minimatch).default is not a function

### ISSUE THREAD

**Issue by mGallee** [expo/expo#26322]
### Summary

`npx expo export` throws the following error:

```
Processing asset bundle patterns:
- /Users/matthiasgallee/Developments/social-garden/frontend/apps/creator/**/*
TypeError: (0 , _minimatch).default is not a function
TypeError: (0 , _minimatch).default is not a function
    at /Users/matthiasgallee/Developments/social-garden/frontend/node_modules/@expo/cli/build/src/export/exportAssets.js:82:128
    at Array.some (<anonymous>)
    at shouldBundleAsset (/Users/matthiasgallee/Developments/social-garden/frontend/node_modules/@expo/cli/build/src/export/exportAssets.js:82:89)
    at /Users/matthiasgallee/Developments/social-garden/frontend/node_modules/@expo/cli/build/src/export/exportAssets.js:56:30
    at Array.map (<anonymous>)
    at resolveAssetBundlePatternsAsync (/Users/matthiasgallee/Developments/social-garden/frontend/node_modules/@expo/cli/build/src/export/exportAssets.js:55:37)
    at Object.exportAssetsAsync (/Users/matthiasgallee/Developments/social-garden/frontend/node_modules/@expo/cli/build/src/export/exportAssets.js:100:11)
    at async Object.exportAppAsync (/Users/matthiasgallee/Developments/social-garden/frontend/node_modules/@expo/cli/build/src/export/exportApp.js:133:25)
    at async exportAsync (/Users/matthiasgallee/Developments/social-garden/frontend/node_modules/@expo/cli/build/src/export/exportAsync.js:45:5)
```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

49.0.21

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: managed
```

### Minimal reproducible example

Run `npx expo export`

**Comment by brella-vida** [comment]
I am seeing an identical problem and didn't notice it until I had quite the git history behind me.
After combing my commits thoroughly I have pinpointed that "eas update" broke after running "npm upgrade", where only package-lock.json was changed (+816 | -24854). None of the installed dependencies changed.

This is my first time contributing to one of these forums, and I won't share my package-lock file as it holds identifiable information. I will post if I come across any useful information.

**Comment by brella-vida** [comment]
I found a solution for my case. Unconventional but I will leave it in case it helps others.

1. I copied the "package.json" text from my latest commit.
2. I restored the last working commit (which includes the lockfile from before my "npm upgrade" activities).
3. I pasted the latest "package.json" into the old commit.
4. I ran "npm install".
5. I copied the contents of the modified "package-lock.json".
6. I discarded all changes and checked out the latest commit.
7. I pasted the modified/old "package-lock.json" into the latest commit.
8. I ran "npm install".
9. "eas update" -> SUCCESS

**Comment by shubhlumber** [comment]
upper solution not working
