### ISSUE TITLE
[expo-camera] setFocusMode on tap

### ISSUE THREAD

**Issue by REEDOOX** [expo/expo#2636]
Hello, I have a special case where the phone doesn't support autofocus and the only mode available is focus on touch, In my android app (another project) I set the focusMode to 'macro' using java after a user clicks. Is there another way of doing with expo camera.

Am new to expo, in my understanding if I want to use react-native-camera because they support such mode I need to eject my project, which I don't want to do because this is the only feature I need which evolves native code in the whole project. am I right ?

Thanks in advance!

**Comment by EvanBacon** [comment]
Related: https://expo.canny.io/feature-requests/p/camera-focus-at-point-on-touch ?

**Comment by EvanBacon** [comment]
Closing in favor of the canny request
