### ISSUE TITLE
[Expo 50] Prebuild can't handle modification of Kotlin files

### ISSUE THREAD

**Issue by erickriva** [expo/expo#26377]
### Summary

Running `npx expo prebuild`, I receive an error:
`Error: [android.dangerous]: withAndroidDangerousBaseMod: ENOENT: no such file or directory, open 'C:\code\github\Javascript ou Typescript\babybloom\monorepo\apps\mobile-app\android\app\src\main\java\com\pregnancy\lulu\MainApplication.java'`

CLI can't find `MainApplication.java` because it does not exists. 
Expo SDK 50 'Hello World' project has `.kt` files instead `.java` for `MainApplication` and `MainActivity`.

Reference: https://docs.expo.dev/bare/upgrade/#androidappsrcmainjavacomhelloworldmainactivityjava

### SDK Version

50.0.0-preview.10

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 11 10.0.23615
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 31, 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-231.9392.1.2311.11255304
    Expo Workflow: bare
```

### Minimal reproducible example

- Follow https://docs.expo.dev/bare/upgrade files modifications, selecting 'from' SDK 49 'to' SDK 50.
- Run `npx expo prebuild`

**Comment by Kudo** [comment]
hi there! could you share a repro or relevant config-plugin code for us? i didn't see any config-plugin code hardcoded java. also tried the local plugin and it works for me:

```js
const { withMainApplication } = require('expo/config-plugins');

const withAndroidPlugins = (config) => {
  return withMainApplication(config, (config) => {
    console.log('contents', config.modResults);
    return config;
  });
};

module.exports = withAndroidPlugins;
```

would be good if you can share more information or error stacktrace .

**Comment by erickriva** [comment]
@Kudo I have found the problem here: `@morrowdigital/watermelondb-expo-plugin`.
Removing it from `app.json` has fixed my issue with prebuild.
Still, Expo could show a more informative error message.

**Comment by brentvatne** [comment]
@erickriva - it looks like this is an issue with the plugin itself - it uses a dangerous mod to just modify the file directly, rather than `withMainApplication` mod. we can't provide much more context around errors with generic dangerous mods because they are equivalent to basically doing an `eval` to make any sort of modifications to the files on disk

**Comment by erickriva** [comment]
> @erickriva - it looks like this is an issue with the plugin itself - it uses a dangerous mod to just modify the file directly, rather than `withMainApplication` mod. we can't provide much more context around errors with generic dangerous mods because they are equivalent to basically doing an `eval` to make any sort of modifications to the files on disk
> 
> https://github.com/morrowdigital/watermelondb-expo-plugin/blob/b5d5802e0490e79219253073e5cb5574dc8b730c/src/withWatermelon.ts#L20-L43

Cannot Expo ignore these plugins without `withMainApplication`? Is there a real use case where this dangerous behavior can be useful?

**Comment by erickriva** [comment]
Understood. Well, my specific problem was solved, I'm closing the issue.

Thanks to you all for clarifying my questions.
