### ISSUE TITLE
Expo 49: Importing a css module results in empty object

### ISSUE THREAD

**Issue by maxhudson** [expo/expo#26374]
### Minimal reproducible example

https://snack.expo.dev/rR7DJuMA7 (not currently working - was unable to get this to compile on snack - but code is relevant)

### Summary

Issue: Importing a css module in expo 49 is resulting in an empty object for me, and unstable_styles is undefined/not exported. Importing a plain css file works fine.

#### metro.config.js

```js
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname, {
  isCSSEnabled: true,
});

module.exports = config;
```

#### global.css - works fine

```css
body {
  background-color: rgba(0, 0, 0, 0.1);
}
```

#### App.module.css

```css
.Button {
  background-color: white;
}
.text {
  color: orange;
}
```

#### App.js

```js
import './global.css';
import styles from './App.module.css';

console.log(styles); //{}
```

What debugging steps can I take here/what might I be doing wrong?

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by matheuscouto** [comment]
The same thing happened on Expo 50. Do we have any updates? 

I've just updated our company's app from 47 to 50. We use SASS modules along with react-native-scss-transformer, but it won't work anymore. The Babel transformer doesn't seem to be getting the correct stringified src of the file for me to send it to react-native-scss-transformer

**Comment by marklawlor** [comment]
@matheuscouto I think you may have misunderstood the code, there is no need to override the transform.

- That code block you linked only applies if the platform is not `web`. Expo only supports CSS for the web.
- SDK 50 has out of the box partial support for sass https://docs.expo.dev/versions/latest/config/metro/#sass
- If you need anything more advanced, SDK 50 supports PostCSS which gives you full control over your CSS file.

So its there is a SASS feature that we don't support, you should be using the [PostCSS-Sass plugin](ttps://github.com/csstools/postcss-sass) and managing the transform yourself

**Comment by marklawlor** [comment]
@maxhudson I'm going to close this issue as we have had no other reports of this issue under SDK 50 (which enables CSS by default).

If your able to replicate your issue in SDK 50, can you please reply with a reproduction repo so we can troubleshoot further
