### ISSUE TITLE
Expo client should let you have some way to know what version of the manifest you have for an open app

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2639]
As a user of a published app you should be able to see, possibly on the Expo menu, what version of the Expo client you have. This will let you see if you are using a cached version. @ide considers this a pre-requisite for adding back https://github.com/expo/expo/issues/2637

**Comment by tsapeta** [comment]
I think this has been fixed with the new dev menu - it shows the SDK version from the manifest.
