### ISSUE TITLE
If user session becomes invalid, prompt user to sign in again

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#264]
@kitze ran into a problem where `exp build:android` wouldn't run, so I asked him to run `exp whoami`, which returned `[exp] Unexpected Error: Couldn't get user information`. We should provide error messages when the user session is invalid and prompt users to sign in again.

**Comment by wilzh40** [comment]
Interesting, in all commands that involve project directories there is a user session check. It prompts users to sign in again if there is no current user session. This can found be on line 97 in `exp.js.` 

```
if (!skipAuthCheck && !opts.nonInteractive && !opts.offline) {
loginOrRegisterIfLoggedOut()
}
```

**Comment by brentvatne** [comment]
will close this until we repro
