### ISSUE TITLE
[expo-updates] TypeError: Updates.checkForUpdateAsync is not a function (it is  undefined)

### ISSUE THREAD

**Issue by wfl-junior** [expo/expo#26408]
### Minimal reproducible example

https://github.com/wfl-junior/expo-updates-example

### Summary

I initialized the repository with `yarn create expo-app -t expo-template-blank-typescript`, configured `nativewind` and configured `expo-updates`  using [this documentation](https://docs.expo.dev/versions/latest/sdk/updates).

This is the `App.tsx`:

```tsx
import { StatusBar } from "expo-status-bar";
import * as Updates from "expo-updates";
import { Text, TouchableHighlight, View } from "react-native";
import colors from "tailwindcss/colors";

console.log(Updates);

async function handleFetchUpdate() {
  try {
    const update = await Updates.checkForUpdateAsync();

    if (update.isAvailable) {
      const result = await Updates.fetchUpdateAsync();
      console.log(result);
      await Updates.reloadAsync();
    }
  } catch (error) {
    alert(`Error fetching latest Expo update: ${error}`);
    console.log(error);
  }
}

export default function App() {
  return (
    <View className="flex-1 items-center justify-center bg-white p-4">
      <StatusBar style="auto" />

      <TouchableHighlight
        activeOpacity={1}
        onPress={handleFetchUpdate}
        underlayColor={colors.violet[700]}
        className="w-full rounded bg-violet-600 px-4 py-3"
      >
        <Text className="text-base text-white font-semibold text-center">
          Fetch Updates
        </Text>
      </TouchableHighlight>
    </View>
  );
}
```

When I run the app in debug mode with `yarn android` and click on the `Fetch Updates` button I get the error: `TypeError: Updates.checkForUpdateAsync is not a function (it is  undefined)`
The `console.log(Updates)` when starting the app prints `{"default": {}}` even though TypeScript recognizes the module correctly.

When I run the app in release mode with `yarn android:release` which is an alias for `expo run:android --variant release` and click on the `Fetch Updates` button I get the error in alert: `TypeError: undefined is not a function` (probably from the same functions)

Tried importing the functions separately like so:

```tsx
import { checkForUpdateAsync, fetchUpdateAsync, reloadAsync } from "expo-updates";
```

They are all `undefined`.

`expo-updates` version: `~0.18.19`
Also tried downgrading some versions and same error.

Tried updating the expo packages versions to latest, still same error.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.11005911
    npmPackages:
      expo: ~49.0.21 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: bare

**Comment by douglowder** [comment]
I'll take a look

**Comment by douglowder** [comment]
Removing tailwind and nativewind did not have any effect.

Upgrading to SDK 50 does fix the problem. So the issue seems specific to SDK 49.

**Comment by douglowder** [comment]
@wfl-junior we are investigating why this problem is occurring in SDK 49 and not in SDK 50. In the meantime, we recommend that you move to SDK 50, which is due to be released shortly.

I've added my patches to your repo here: https://github.com/wfl-junior/expo-updates-example/compare/main...douglowder:expo-updates-example:main

**Comment by wfl-junior** [comment]
> @wfl-junior we are investigating why this problem is occurring in SDK 49 and not in SDK 50. In the meantime, we recommend that you move to SDK 50, which is due to be released shortly.
> 
> I've added my patches to your repo here: [wfl-junior/expo-updates-example@main...douglowder:expo-updates-example:main](https://github.com/wfl-junior/expo-updates-example/compare/main...douglowder:expo-updates-example:main)

I did move to SDK 50, and it did fix the issue, thank you.
There is just one slight problem with it for now, that the SDK 50 is not yet stable, right?

**Comment by douglowder** [comment]
@wfl-junior SDK 50 is hopefully going to be released shortly. Once that happens, I'll post again here so you can move to the released version.

**Comment by douglowder** [comment]
Sorry @wfl-junior I came down with COVID and forgot to post here about the SDK 50 release 😷
