### ISSUE TITLE
Header is not appearing with slot. Stack content is not appearing when wrapped.

### ISSUE THREAD

**Issue by kishieel** [expo/expo#26411]
### Minimal reproducible example

https://github.com/kishieel/expo-router-bug-report-2

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I am experiencing two issues with expo router. If you run the provided example you will see that:

1) for the context with slot: the header is not appearing although the property headerShown is set to true.
2) for the context with stack: the content of screen is missing when stack is wrapped in some component. 

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.6 Arch Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.21 - /usr/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ~50.0.0-preview.9 => 50.0.0-preview.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

**Comment by PatrickPayecards** [comment]
I hate to be that guy, but any progress on this

**Comment by MariaIsabel68** [comment]
Same here

**Comment by mattwilliams0592** [comment]
@kishieel I looked at your issue before submitting my own as it seemed relevant. Here are my findings:

1. This is related to what I've logged here: https://github.com/expo/expo/issues/27894
1. Add `style={{ flex: 1 }}` to the View within your LayoutWrapper

**Comment by babucarr32** [comment]
Same here

**Comment by fecampossantos** [comment]
Almost an year an no solution? I'm going through this too

**Comment by babucarr32** [comment]
You need to put the screen that is not showing a header inside a [(group)](https://docs.expo.dev/router/layouts/#groups) layout. The group should have `_layout.tsx` file that returns a stack screen.

Example:
`(your-screen-name)/_layout.tsx`
```
import React from "react";
import { Stack } from "expo-router";

export default function Layout() {
  return (
    <Stack>
      <Stack.Screen
        name="index"
        options={{
          headerTitle: "MY HOME SCREEN",
        }}
      />
    </Stack>
  );
}
```

`(your-screen-name)/index.tsx`
```
import { Text } from "react-native";

export default function HomeScreen() {
  return (<Text>HELLO WORLD</Text>);
}
```

**Stop expo server and restart.**
