### ISSUE TITLE
expo-router: When using Drawer, routes should not be rendered in the drawer by default

### ISSUE THREAD

**Issue by JorensM** [expo/expo#26438]
### Minimal reproducible example

Any app that uses expo-router's Drawer

### Summary

When adding a fresh Drawer component in to the `_layout.tsx` file, all top level route are automatically displayed in the drawer. I think this shouldn't be the case, or at least be optional.

My proposal is to create a prop for the `Drawer` called `hideRoutesByDefault` that makes it so that routes generated by Expo for the `Drawer` component are automatically hidden.

I looked into the source code and [routeToScreen()](https://github.com/expo/expo/blob/2dc48d7130d14d475c8aa79be22bf83c2593a385/packages/expo-router/src/useScreens.tsx#L249) is the function that converts a route to a screen which then gets passed to the `Drawer` component. On line `272` you can see some code already being there for hiding routes, but it seems that this is only for 'generated' routes. As a side note, could anyone tell me what is a generated route and how is it different from a regular route? I'm assuming it's routes like `_sitemap` etc.

So what I propose is to add a `hideRoute` arg to the `routeToScreen` function and all the functions that use it to eventually add the created `Screen`s to the `Drawer` (and the other types of) component. Then use the `hideRoute` arg to conditionally assing the `output.drawerItemStyle.display` to `none` for **all routes, not just the 'generated' ones**

### Environment

Don't think this is necessary for this.

**Comment by elliothux** [comment]
A workaround here:

1. Create a 'my-drawer.tsx'
```tsx
import { createDrawerNavigator } from '@react-navigation/drawer';
import { RouteNode, useContextKey, useRouteNode } from 'expo-router/build/Route';
import { useFilterScreenChildren } from 'expo-router/build/layouts/withLayoutContext';
import { Screen } from 'expo-router/build/primitives';
import { ScreenProps, createGetIdForRoute, getQualifiedRouteComponent } from 'expo-router/build/useScreens';
import * as React from 'react';

const { Navigator } = createDrawerNavigator();

export function Drawer({ children }: { children: React.ReactNode | React.ReactNode[] }) {
  const contextKey = useContextKey();
  const { screens } = useFilterScreenChildren(children, { contextKey });

  return <Navigator>{useSortedScreens(screens)}</Navigator>;
}

function useSortedScreens(order: ScreenProps[]): React.ReactNode[] {
  const node = useRouteNode();

  const sorted = node?.children?.length ? getSortedChildren(node.children, order, node.initialRouteName) : [];
  return React.useMemo(() => sorted.map((value) => routeToScreen(value.route, value.props)), [sorted]);
}

function getSortedChildren(
  children: RouteNode[],
  order?: ScreenProps[],
  initialRouteName?: string,
): { route: RouteNode; props: Partial<ScreenProps> }[] {
  const entries = [...children];

  return order
    .map(({ name, redirect, initialParams, listeners, options, getId }) => {
      if (!entries.length) {
        console.warn(`[Layout children]: Too many screens defined. Route "${name}" is extraneous.`);
        return null;
      }
      const matchIndex = entries.findIndex((child) => child.route === name);
      if (matchIndex === -1) {
        console.warn(
          `[Layout children]: No route named "${name}" exists in nested children:`,
          children.map(({ route }) => route),
        );
        return null;
      } else {
        // Get match and remove from entries
        const match = entries[matchIndex];
        entries.splice(matchIndex, 1);

        // Ensure to return null after removing from entries.
        if (redirect) {
          if (typeof redirect === 'string') {
            throw new Error(`Redirecting to a specific route is not supported yet.`);
          }
          return null;
        }

        return {
          route: match,
          props: { initialParams, listeners, options, getId },
        };
      }
    })
    .filter(Boolean) as {
    route: RouteNode;
    props: Partial<ScreenProps>;
  }[];
}

function routeToScreen(route: RouteNode, { options, ...props }: Partial<ScreenProps> = {}) {
  return (
    <Screen
      // Users can override the screen getId function.
      getId={createGetIdForRoute(route)}
      {...props}
      name={route.route}
      key={route.route}
      options={(args) => {
        // Only eager load generated components
        const staticOptions = route.generated ? route.loadRoute()?.getNavOptions : null;
        const staticResult = typeof staticOptions === 'function' ? staticOptions(args) : staticOptions;
        const dynamicResult = typeof options === 'function' ? options?.(args) : options;
        const output = {
          ...staticResult,
          ...dynamicResult,
        };

        // Prevent generated screens from showing up in the tab bar.
        if (route.generated) {
          output.tabBarButton = () => null;
          // TODO: React Navigation doesn't provide a way to prevent rendering the drawer item.
          output.drawerItemStyle = { height: 0, display: 'none' };
        }

        return output;
      }}
      getComponent={() => getQualifiedRouteComponent(route)}
    />
  );
}
```

2. Replace `import { Drawer } from 'expo-router/drawer'` with `import { Drawer } from 'my-drawer`;

**Comment by marklawlor** [comment]
We will be revisiting the usability of the navigators in a future update, but for now this is working as expected.

The current solutions are

1. Explicitly list the Screens as the children of the Drawer. Setting `href: null` will remove that screen
2. Use a custom Drawer navigator (as demonstrated above)

**Comment by mknap** [comment]
> The current solutions are
> 
> 1. Explicitly list the Screens as the children of the Drawer. Setting `href: null` will remove that screen

I can't see that setting href: null in the Screen definition removes it from the drawer.

**Comment by jovimoura** [comment]
I did that and are working: 
`
import { DrawerContentScrollView, DrawerItemList, DrawerContentComponentProps } from "@react-navigation/drawer";

export function CustomDrawerContent(props: DrawerContentComponentProps) {
  const routes = props.state.routes.filter(route => !route.name.includes('auth'))

  const filteredState = {
    ...props.state,
    routes
  }

  return (<DrawerContentScrollView {...props}>
    <DrawerItemList state={filteredState} navigation={props.navigation} descriptors={props.descriptors} />
  </DrawerContentScrollView>)
}
`

**Comment by douglowder** [comment]
@marklawlor I found an interesting possible solution to hide a route that you don't want to be visible or accessible in the drawer. `Drawer.Screen` doesn't seem to have an `href` prop that can be set to null. However, adding `redirect` seems to disable the drawer item, and the style renders it invisible. You do still have to explicitly list it as a child of the drawer, though.

```jsx
            <Drawer.Screen
              name="routeToHide"
              redirect
              options={{
                drawerItemStyle: {
                  opacity: 0.0,
                },
              }}
            />
```

**Comment by vendramini** [comment]
There's no `href` property and the `redirect` workaround does work to hide the item from the menu, but it makes it not accessible when trying to navigate with `route.push()`.

```
"expo-router": "~3.5.16",
"expo": "~51.0.13",
```

**Comment by maciejkorsan** [comment]
I've been trying with the `drawerItemStyle: { display: 'none' }` and it works on the simulator, but it's completely ignored by the real device

**Comment by naftalimurgor** [comment]
> @marklawlor I found an interesting possible solution to hide a route that you don't want to be visible or accessible in the drawer. `Drawer.Screen` doesn't seem to have an `href` prop that can be set to null. However, adding `redirect` seems to disable the drawer item, and the style renders it invisible. You do still have to explicitly list it as a child of the drawer, though.
> 
> ```js
>             <Drawer.Screen
>               name="routeToHide"
>               redirect
>               options={{
>                 drawerItemStyle: {
>                   opacity: 0.0,
>                 },
>               }}
>             />
> ```

Redirect works but the routes become broken for some reason.

**Comment by naftalimurgor** [comment]
I've been stuck on this for days, is it possible to use the original Router implementation without relying expo-router?

**Comment by jony89** [comment]
I am not sure why we there is so much struggling hiding menu items.

My suggest is that once one is customizing the drawer with `Drawer.Screen` items then only these items will be displayed.

**Comment by DaveVaval** [comment]
> I am not sure why we there is so much struggling hiding menu items.
> 
> My suggest is that once one is customizing the drawer with `Drawer.Screen` items then only these items will be displayed.

This indeed should be the desired behavior in my opinion.  As of today using:
`"expo": "~51.0.28",`
`"@react-navigation/drawer": "^6.7.2",`

Setting the display to none on the item style does work
```
<Drawer.Screen
  name='(tabs)'
  options={{
    drawerItemStyle: {
      display: 'none'
    }
  }}
/>
```
But it would be nice to have the drawer behave properly and not have to define screens we want to hide

**Comment by pedrosalucity** [comment]
I'm having same problem.  It would be nice to add a prop to the Drawer  component if you want to show all files by default  or just the items you specificaly put into Drawer with Drawer.Screen components, thats an special problem id you have a list of elements for example: 

`
(logedUsers)
-- _layout
-- itemList
----- index
----- [itemId] <== It doesn't make sense to show that in the menu
-- userData
`

I checked than in `"@react-navigation/drawer": "^7.1.1"`, you can set `redirect={true}` to hide this link from the menu.

`<Drawer.Screen
name="path"
redirect={true}
/>`
