### ISSUE TITLE
[SDK 50] expo-dev-client: Fast refresh is not working in Android development build when expo-dev-client is installed

### ISSUE THREAD

**Issue by ArianHamdi** [expo/expo#26445]
### Minimal reproducible example

https://github.com/ArianHamdi/android-development-build

### Summary

When `expo-dev-client` is installed in SDK 50, fast refresh does not work in the development build on Android.

However, fast refresh works fine in Expo Go on both Android and iOS. It also works well on the iOS development build.

Additionally, fast refresh works fine on the Android development build in SDK 49.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - ~/Library/pnpm/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0-preview.11 => 50.0.0-preview.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    Expo Workflow: bare

**Comment by Kudo** [comment]
this is a duplicated issue as #26254 and will be resolved next expo-dev-client version.
