### ISSUE TITLE
URI Scheme is still exp:/// in standalone | Production release | Xcode Development build

### ISSUE THREAD

**Issue by Rutulpatel7077** [expo/expo#2644]
### Environment

Expo CLI 2.2.5 environment info:
System:
OS: macOS High Sierra 10.13.6
Shell: 5.3 - /bin/zsh
Binaries:
Node: 10.11.0 - /usr/local/bin/node
Yarn: 1.7.0 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.1 AI-173.4697961
Xcode: 10.1/10B61 - /usr/bin/xcodebuild
npmGlobalPackages:
expo-cli: 2.2.5

### Actual Behavior

I have ejected expo application. I am trying to access email attachment from an email to import data in my app.

After changing info.plist, now I am able to get my app in the list of "open with app list" and actually able to open that file with my expo(React native app).

in my App.js

```
Linking.getInitialURL().then((url) => {
  if (url) {
        console.log(url);
    }

}).catch(err => console.error('An error occurred', err));

```

**it's giving me URL like this** `exp:///private/var/mobile/Containers/Data/Application/7E55EB55-7C49-4C0C-B4CB-63AC4F49689E/Documents/Inbox/matters-3.csv`

So I am assuming, when I click open with my app. The URL that is passed into my app from the system is actually a copy of the document that is placed somewhere in our app’s directory.

### Expected Behavior
the URL scheme should be change as per my app.json. should not have exp:/// in Xcode release build.

### What you think?

How to Change URI.

app.json 

```
{
  "expo": {
    "name": "lorem ipsum",
    "description": "lorem ipsum",
    "slug": "ezdocket",
    "scheme": "ezdocket",
    "sdkVersion": "31.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.2",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/ez-docket-icon-splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.smashreality.ezdocket"
    },
    "android": {
      "package": "com.ezdocket.ezdocket"
    }
  }
}
```

**Comment by Rutulpatel7077** [comment]
@esamelson I appreciate you assigned this issue to your self.
Are there any updates from you? Am I doing something wrong?

As described my issue is in URI scheme. I would be happier if you help me to solve my problem.

waiting for the response.

**Comment by esamelson** [comment]
Hi @Rutulpatel7077 - I think this is a bug in Expo. If you'd like to look into it yourself, I think the relevant code is here: https://github.com/expo/expo/blob/f29d093535ede600d0f9b96abcfad01df8a94fd3/ios/Exponent/Kernel/Services/EXKernelLinkingManager.m#L203 but no promises as I haven't had a chance to really dig into this myself yet!

**Comment by nemo** [comment]
I have this issue. Any updates?

**Comment by Rutulpatel7077** [comment]
@esamelson Did you find anything?

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. We've made a number of fixes and improvements to the linking/OTA update logic since this issue was opened. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
