### ISSUE TITLE
[Feature] `expo-contacts` Add support for Contact Picker

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#2645]
# Request

https://expo.canny.io/admin/board/feature-requests/p/use-native-contact-pickers

## iOS

Implement [`CNContactPickerViewController`](https://developer.apple.com/documentation/contactsui/cncontactpickerviewcontroller)

## Android

Need to launch an intent that enables contact picking
```java
Intent mIntent = new Intent(Intent.ACTION_PICK);
mIntent.setType(ContactsContract.Contacts.CONTENT_TYPE);
if (mIntent.resolveActivity(getCurrentActivity().getPackageManager()) != null) {
  getCurrentActivity().startActivityForResult(mIntent, requestCode);
}
```

## Links

* [Package](https://github.com/expo/expo/tree/master/packages/expo-contacts)
* [Tests](https://github.com/expo/expo/blob/master/apps/test-suite/tests/Contacts.js)
* [Demo](https://github.com/expo/expo/tree/master/apps/native-component-list/screens/Contacts)

**Comment by sam-dieck** [comment]
Hey @EvanBacon, I'm very interested in this feature, I think it would be great to be able to choose a contact without having to manually make a picker by fetching all contacts and presenting them in a screen. Seems like a valuable feature for many apps.
Is this something you are currently working on? Is there any way I can help?
Thanks, I appreciate your time and effort.
Sam

**Comment by mohan-shyam** [comment]
@expjess @EvanBacon any idea if this will be worked upon anytime in the near future? Thanks!

**Comment by EvanBacon** [comment]
Closing in favor of the canny request.

**Comment by fzf** [comment]
@EvanBacon canny request?

**Comment by corysimmons** [comment]
https://expo.canny.io/feature-requests/p/use-native-contact-pickers

**Comment by trevorwhealy** [comment]
@EvanBacon followed up on the Canny request as well, but is this feature still being actively tracked at Expo?

**Comment by corysimmons** [comment]
Their public roadmap `1/1 find in page results` which is just `Save new contact`:

<img src="https://user-images.githubusercontent.com/224636/118686897-70e4f380-b7d2-11eb-9bf9-fc2cd7acc13c.png" width="500">

...so I don't think it's being worked on.

Definitely strange that it's not prioritized as you'd think _"Picking a contact from your list of contacts"_ would be an incredibly common use case for lots of mobile apps. 🤷

**Comment by trevorwhealy** [comment]
@corysimmons ahh thanks for the info, that's a shame about this feature. I completely agree with you, it's so surprising I would think this is something tons of developers needed. This is the third production RN app I'm building for the App Store and each one has needed this. I was hoping to finally use something other than a custom-styled FlatListView 😅

**Comment by kk2491** [comment]
Is this feature available now ? 

Thank you,  
KK
