### ISSUE TITLE
[SNACK] Cannot read property 'deviceConnectionMethod' of null

### ISSUE THREAD

**Issue by lojaya** [expo/expo#2646]
This is major bug, I couldn't open the page

### Steps to Reproduce

1. Directly open https://snack.expo.io in any browser

### Expected Behavior

Snack Expo is successfully opened

### Actual Behavior

![image](https://user-images.githubusercontent.com/10978695/48115041-feefd300-e293-11e8-8671-a9a19a62a9fc.png)

### Reproducible Demo

https://snack.expo.io

**Comment by myriky** [comment]
me too :(

**Comment by lojaya** [comment]
@behrends thanks for the quick workaround!

**Comment by tcdavis** [comment]
Thanks for reporting, and very sorry we didn't have a test covering this.
A fix for this has been deployed.

**Comment by behrends** [comment]
Thanks for this quick turnaround!
