### ISSUE TITLE
expo-screen-capture addScreenshotListener not firing on Android

### ISSUE THREAD

**Issue by milan-digiuseppe-level** [expo/expo#26476]
### Minimal reproducible example

https://github.com/milan-digiuseppe-level/expo-screen-capture-mvp

### Summary

`ScreenCapture.addScreenshotListener` isn't firing the callback when taking a screenshot on Android

I was able to reproduce this in a minimum reproducible project linked above. After receiving some help from an Expo partner via Slack, they suggested a patch to expo-screen-capture which is included in the project but didn't end up resolving the issue.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - /opt/homebrew/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed

**Comment by khurshidShah** [comment]
like!!!

**Comment by prutkovvv** [comment]
This pr causes crash on android 14 when firebase messaging integrated and message comes when app is in the quit state  According to the changelog, this fix is the only fix for 5.8.1. 5.8.0 works fine. We've spent almost a week to detect where the issue comes from.
Firebase version:
` "@react-native-firebase/messaging": "^19.0.1"`(same happens on 17)
The error we get: 
`Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': expo.modules.kotlin.exception.Exceptions$MissingActivity: The current activity is no longer available, js engine: hermes`

**Comment by t0ma5h** [comment]
> This pr causes crash on android 14 when firebase messaging integrated and message comes when app is in the quit state According to the changelog, this fix is the only fix for 5.8.1. 5.8.0 works fine. We've spent almost a week to detect where the issue comes from. Firebase version: ` "@react-native-firebase/messaging": "^19.0.1"`(same happens on 17) The error we get: `Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': expo.modules.kotlin.exception.Exceptions$MissingActivity: The current activity is no longer available, js engine: hermes` @alanjhughes

Same happens for me when receiving background notifications from killed state. 

I think this bug is only reproducible on Android 14.

**Comment by techgerm** [comment]
@prutkovvv we're experiencing the same crash on Android 14 - was the workaround for you simply to downgrade `expo-screen-capture` to `5.8.0`?

**Comment by t0ma5h** [comment]
@techgerm Yes. We tried versions other than 5.8.0 too like 5.7.0 and 5.6.0 , so as long as it's below 5.8.1 it should work ok.

**Comment by prutkovvv** [comment]
> @prutkovvv we're experiencing the same crash on Android 14 - was the workaround for you simply to downgrade `expo-screen-capture` to `5.8.0`?

Yes. If the issue still persists, new issue should be raised

**Comment by techgerm** [comment]
sounds good thanks for the quick response!

looks like there's an open issue here: https://github.com/expo/expo/issues/27921

**Comment by kaisaohnae** [comment]
5.8.1 -> 5.8.0 다운그레이드 하세요 그지같음
