### ISSUE TITLE
Facebook Login button android users disappear on Facebook Analytics

### ISSUE THREAD

**Issue by AlexisJamin** [expo/expo#2647]
### Environment

Expo : V30, but it was already the case with v26

### Steps to Reproduce

I'm using Expo Facebook Login button. It works for my Android and IOS users perfectly. They can Login to my app. No problem.

`_handleFacebookLogin = async () => {
    try {
      const { type, token, expires } = await Facebook.logInWithReadPermissionsAsync(
        '23*******9',
        { 
          permissions: ['public_profile', 'user_friends', 'email']
        }
      );`

`switch (type) {
        case 'success': {
          const response = await fetch(`https://graph.facebook.com/me?access_token=${token}&fields=id,name,picture.type(large),email`);
          const profile = await response.json();
          var name = profile.name.split(" ");
          var expdate = new Date(expires*1000);

          if (profile.picture) {  
            this.getImageFromFacebook(profile.picture.data.url);
          }

          let authData = {
            id: profile.id,
            access_token: token,
            expiration_date: expdate
          };
          
          Parse.FacebookUtils.logIn(authData,{
            success: function(user) {
         //Send user info to database
              } 
            },
            error: function(user, error) {
              console.log(user, error);
            }
          }) 
          break;
        }
        case 'cancel': {
          Alert.alert(
            'Connexion annulée!',
          );
          login.setState({disabled:false})
          break;
        }
        default: {
          Alert.alert(
            'Oops!',
            'Login failed!',
          );
        }
      }
    } catch (e) {
      Alert.alert(
        'Oops!',
        'Login failed!',
      );
    }
  };`
      
I also followed Expo doc to complete my app on Facebook : 

![capture d ecran 2018-11-07 a 12 55 17](https://user-images.githubusercontent.com/28752161/48130311-89cccf80-e28c-11e8-9a01-c26e500af97e.png)

### Expected Behavior

I should see Android Users. I see them with Amplitude : 

![capture d ecran 2018-11-07 a 12 35 19](https://user-images.githubusercontent.com/28752161/48130347-ab2dbb80-e28c-11e8-8089-f47d11b30d2d.png)

But on Facebook Analytics, they disappear, I only see iOS : 

![capture d ecran 2018-11-07 a 12 34 39](https://user-images.githubusercontent.com/28752161/48130385-c993b700-e28c-11e8-82b7-85d3d19d2f36.png)

![capture d ecran 2018-11-07 a 12 34 28](https://user-images.githubusercontent.com/28752161/48130403-d7e1d300-e28c-11e8-98a8-1f504ac76ecd.png)

It's also problematic when I use Facebook ads. I don't have any feedbacks on Android users. Only on iOS ...

Thanks for your help ! :)

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. This is a pretty hard issue to reproduce with the information provided. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
