### ISSUE TITLE
[docs] Dead link for screen tracking analytics

### ISSUE THREAD

**Issue by WillSmithTE** [expo/expo#26484]
### Summary

docs link: https://docs.expo.dev/versions/v46.0.0/sdk/firebase-analytics/

text: "To see an example of how this works, see Screen tracking in React Navigation documentation."

Links to: https://reactnavigation.org/docs/en/screen-tracking.html

that link is dead

code: https://github.com/expo/expo/blob/d6f69f193d700facc92ea7e1dfc2e7dbbaf61f4c/docs/pages/versions/v47.0.0/sdk/firebase-analytics.mdx#L133

### Link to the related docs page

https://docs.expo.dev/versions/v46.0.0/sdk/firebase-analytics/

**Comment by WillSmithTE** [comment]
maybe correct link: https://reactnavigation.org/docs/screen-tracking/

**Comment by amandeepmittal** [comment]
Thanks for reporting it here. This was fixed in #26499 & #26514
