### ISSUE TITLE
[expo-location] App crash when attempting to launch LocationService

### ISSUE THREAD

**Issue by NadeemKhanFh** [expo/expo#26490]
### Minimal reproducible example

https://snack.expo.dev/@leymytel/locationtaskservice

### Summary

Hi, this issue is coming on android devices only on production devices.

66% devices are android 13 and its coming in background state

here are the stack traces

[com.cheeziousrider_issue_e2670e86e099463bf7440b60ad7624b5_crash_session_65A8716A0309000123BD60E5869D959E_DNE_0_v2_stacktrace.txt](https://github.com/expo/expo/files/13974795/com.cheeziousrider_issue_e2670e86e099463bf7440b60ad7624b5_crash_session_65A8716A0309000123BD60E5869D959E_DNE_0_v2_stacktrace.txt)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.6.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.4.0 - /opt/homebrew/bin/npm
      Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.0
    Expo Workflow: bare

**Comment by mishrasatyam** [comment]
Facing similar issue . App crashing randomly for some users while using `expo-location` with `expo sdk 49`

**Comment by brentvatne** [comment]
hi there!

can you please post a link to a github repo that includes a minimal reproducible example that we can clone and run? thanks!

**Comment by NadeemKhanFh** [comment]
Hi @brentvatne 
i can make an repo for you, but apps are crashing on production. may be you can not reproduce it on local.

**Comment by brentvatne** [comment]
@NadeemKhanFh - you should be able to reproduce a production environment with `npx expo run:android --variant release`

**Comment by brentvatne** [comment]
happy to reopen when you have a minimal reproducible example that we can clone and run! or if you create a new issue when you have that ready that would work too

**Comment by efstathiosntonas** [comment]
probably related: https://github.com/expo/expo/issues/26620
