### ISSUE TITLE
[expo-splash-screen] [iOS] Defined backgroundColor in app.json is ignored in both version 0.26.2 and 0.26.3

### ISSUE THREAD

**Issue by KesoGizmoYoshi** [expo/expo#26491]
### Minimal reproducible example

https://github.com/KesoGizmoYoshi/splash-screen-test

### Summary

The backgroundColor defined for the splash-screen in app.json started to be ignored in version 0.26.2 (still the same issue in 0.26.3). Only seems to be a problem in iOS. If I revert back to 0.26.1, it works as expected. The following line is added in SplashScreen.storyboard with version 0.26.2 and up:
 `<color key="backgroundColor" systemColor="systemBackgroundColor"/>`
That's the only change I can see, and if I remove it, then the backgroundColor starts working again.

Expected behavior: The background during app launch should be red, as defined in app.json.

Real behavior: The background color is white during app launch.

Steps to reproduce:
1. npm install
2. npm run ios

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /usr/local/bin/node
      npm: 10.2.5 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.1 => 50.0.1 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    Expo Workflow: bare

**Comment by ekkusi** [comment]
Experiencing the same issue. Only solution seems to be the remove the newly generated line manually, but that would need to be done every time after running expo prebuild.

**Comment by techied** [comment]
Looks like #25971 was the breaking change here

**Comment by carbonatedcoder** [comment]
When is this fix estimated to go live? Our current EAS builds, even ones built just a few hours ago, are still ignoring the `backgroundColor` values and just showing white bars at the top/bottom. It does not occur in Expo Go, only in actual builds.
