### ISSUE TITLE
Detached app doesn't run via Xcode

### ISSUE THREAD

**Issue by paul019** [expo/expo#2649]
I am currently developing an App using ExpoKit (SDK 29). It compiles successfully via Xcode, but when I try to run it on a simulator (via Xcode) the following error message occurs:

<img width="526" alt="bildschirmfoto 2018-11-07 um 16 02 00" src="https://user-images.githubusercontent.com/39464035/48139423-bdb4ee80-e2a6-11e8-816f-3a074cf15e03.png">

It appears very weird to me, because I am not using the Expo Client App at all, so I can't update it. I also tried installing the app on a real device, but the same error occurred. I am correctly serving the app via `expo start` (version 2.2.0 of the expo-cli):

<img width="1792" alt="bildschirmfoto 2018-11-07 um 16 05 36" src="https://user-images.githubusercontent.com/39464035/48139531-fce33f80-e2a6-11e8-8712-e1921d5e072c.png">

**Comment by manspeterson** [comment]
same goes here...

**Comment by tsapeta** [comment]
Hey @paul019 @manspeterson,
What happens if you update your ExpoKit pod to be from tag `ios/2.7.8`? And after that change you ofc need to run `pod install`.

**Comment by manspeterson** [comment]
@tsapeta, then the Xcode build fails for me; a lot of unable to open file "GTMSessionFetcher"

**Comment by paul019** [comment]
@tsapeta My Xcode build doesn't fail, but the download of the JS files doesn't work anyway. Still the same error...

**Comment by paul019** [comment]
@tsapeta Now, I tried another time and got another error:

<img width="526" alt="bildschirmfoto 2018-11-07 um 19 48 41" src="https://user-images.githubusercontent.com/39464035/48153300-2eb7ce80-e2c6-11e8-8613-79c44a80e000.png">

I'm in fact serving my project via `expo start` correctly...

**Comment by tsapeta** [comment]
Hmm, can you try `expo start -c` which clears CLI cache? Also, I'd try updating `expo-cli` to the latest version. 
Anyway, I'll try setting up a blank project using your podfile that you posted in another issue and see what happens 😉

**Comment by paul019** [comment]
@tsapeta Thank you! Here is my current Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

EXPO_CPP_HEADER_DIR = 'ExpoKit'

target 'pq-app-v2' do

  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.7.8",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true
  pod 'EXGL',
    :path => "../node_modules/expo-gl/ios",
    :inhibit_warnings => true
  pod 'EXCore',
    :path => "../node_modules/expo-core/ios",
    :inhibit_warnings => true
  pod 'EXCamera',
    :path => "../node_modules/expo-camera/ios",
    :inhibit_warnings => true
  pod 'EXSensors',
    :path => "../node_modules/expo-sensors/ios",
    :inhibit_warnings => true
  pod 'EXConstants',
    :path => "../node_modules/expo-constants/ios",
    :inhibit_warnings => true
  pod 'EXFileSystem',
    :path => "../node_modules/expo-file-system/ios",
    :inhibit_warnings => true
  pod 'EXPermissions',
    :path => "../node_modules/expo-permissions/ios",
    :inhibit_warnings => true
  pod 'EXCameraInterface',
    :path => "../node_modules/expo-camera-interface/ios",
    :inhibit_warnings => true
  pod 'EXSensorsInterface',
    :path => "../node_modules/expo-sensors-interface/ios",
    :inhibit_warnings => true
  pod 'EXConstantsInterface',
    :path => "../node_modules/expo-constants-interface/ios",
    :inhibit_warnings => true
  pod 'EXReactNativeAdapter',
    :path => "../node_modules/expo-react-native-adapter/ios",
    :inhibit_warnings => true
  pod 'EXFileSystemInterface',
    :path => "../node_modules/expo-file-system-interface/ios",
    :inhibit_warnings => true
  pod 'EXPermissionsInterface',
    :path => "../node_modules/expo-permissions-interface/ios",
    :inhibit_warnings => true
  pod 'EXFaceDetectorInterface',
    :path => "../node_modules/expo-face-detector-interface/ios",
    :inhibit_warnings => true
  pod 'EXSMS',
    :path => "../node_modules/expo-sms/ios",
    :inhibit_warnings => true
  pod 'EXGL-CPP',
    :path => "../node_modules/expo-gl-cpp/cpp",
    :inhibit_warnings => true

  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'glog',
    :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec",
    :inhibit_warnings => true


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'

        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    if ['Amplitude-iOS','Analytics','AppAuth','Branch','CocoaLumberjack','FBSDKCoreKit','FBSDKLoginKit','FBSDKShareKit','GPUImage','JKBigInteger2'].include? target.pod_name
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    # Can't specify this in the React podspec because we need
    # to use those podspecs for detached projects which don't reference ExponentCPP.
    if target.pod_name.start_with?('React')
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
      end
    end
    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
```

**Comment by paul019** [comment]
I've already updated the CLI to the latest version and clearing the cache doesn't help either

**Comment by paul019** [comment]
@tsapeta I tried running the app on my physical device another time and got the same error message. But in the CLI window I could see console logs from my device (see below), that are printed by the app's start screen for debugging. So in the background the CLI in fact connects with my phone, which shows an error message anyway.

<img width="1792" alt="bildschirmfoto 2018-11-07 um 20 07 45" src="https://user-images.githubusercontent.com/39464035/48154514-172e1500-e2c9-11e8-8ebe-7646e06c7603.png">

**Comment by paul019** [comment]
@tsapeta Could you find something out by setting up a blank project using my podfile? Do you experience the same problem as I do?

**Comment by tsapeta** [comment]
Unfortunately I didn't find anything 😞 I've created blank new project, then downgraded it to SDK29 and then ejected. Works as expected.

**Comment by pgerochi** [comment]
@paul019 this happened to me and when I closed my Xcode, restarted expo, then opened Xcode again it worked. Same exact issue. I hope this helps.

**Comment by paul019** [comment]
@pgerochi Thank you for this tip. Unfortunately, it didn't work for me.

@tsapeta Thank you for trying to find the problem. How did you eject the project? Did you use `exp detach` or `expo detach`. I used `exp detach` and then switched to the new CLI tool. Maybe that's my problem. What do you think?

**Comment by tsapeta** [comment]
@paul019 yeah, `exp` is deprecated and shouldn't be used anymore. 
So a list of things I did:
- `expo init` and change directory to the new folder
- change `sdkVersion` to `29.0.0` in `app.json` and downgrade `expo` and `react-native` fork in `package.json`
- `yarn add whatwg-fetch@^2.0.4` (see #2192 for more details why)
- `expo eject`
- `cd ios && pod install`
- build and run

Let me know if this works 😉

**Comment by paul019** [comment]
@tsapeta But how should I do that? I've already detached to ExpoKit (using `exp detach`) and as far as I know you can't undo that. I could try undoing it using Git, but I would prefer another solution. Besides, I'm using `npm`.

**Comment by tsapeta** [comment]
@paul019 Yes, if you want to re-eject your project then you need to remove `ios` and `android` folder and also change `isDetached` property to `false` in your `app.json`.

**Comment by paul019** [comment]
@tsapeta I have used Git to undo the `exp detach`. Instead I've now ran a `expo eject` and everything works like it's supposed to. Thank you very much for your great help!
