### ISSUE TITLE
postExport hook is not run

### ISSUE THREAD

**Issue by scott-eurostar** [expo/expo#26495]
### Summary

I'm trying to upload source maps to Sentry with our own CLI. According to [expo-sentry](https://docs.expo.dev/guides/using-sentry/) I should be able to use a postExport hook to do this as stated [here](https://docs.expo.dev/guides/using-sentry/#source-maps). However, when I add the hook to my app.config.ts and then run `npx expo export`, the postExport hooks are not run. Are postExport hooks still supported on the cli as it doesn't seem to be picking them up or am I doing something wrong in my setup?

### SDK Version

49.0.15

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.11.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/xxxx/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

### Minimal reproducible example

1) Create a new project
2) Install sentry-expo
3) Add sentry hook or any other with postExport
4) Run `npx expo export` 
5) See expo export runs, but the hook does not get run

```
import { ExpoConfig, ConfigContext } from 'expo/config';
// dev config only to start with
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  slug: 'exampleapp',
  name: 'Example App',
  owner: 'example-owner',
  plugins: ['sentry-expo'],
  ios: {
    bundleIdentifier: 'com.example.app.dev',
    supportsTablet: true
  },
  android: {
    package: 'com.example.app.dev',
    adaptiveIcon: {
      foregroundImage: './src/assets/adaptive-icon.png',
      backgroundColor: '#ffffff'
    }
  },
  extra: {
    eas: {
      projectId: 'xxxxxxx'
    }
  },
  hooks: {
    postExport: [
      {
        file: 'sentry-expo/upload-sourcemaps',
        config: {
          organization: 'example-org',
          project: 'example-project'
        }
      }
    ]
  },
  version: '1.0.0',
  orientation: 'portrait',
  icon: './src/assets/icon.png',
  userInterfaceStyle: 'light',
  splash: {
    image: './src/assets/splash.png',
    resizeMode: 'contain',
    backgroundColor: '#ffffff'
  },
  assetBundlePatterns: ['**/*'],
  web: {
    favicon: './src/assets/favicon.png'
  },
  experiments: {
    typedRoutes: true,
    tsconfigPaths: true
  }
});
```

**Comment by brentvatne** [comment]
hi there!

this section of the docs is specific to the currently sunsetting "classic updates" service - which are published and exported through the global deprecated `expo-cli` package.

`postExport` and `postPublish` are not supported fields with EAS Update / `@expo/cli`.

for the best sentry integration experience, i recommend updating to sdk 50, where we have merged expo support into `@sentry/react-native` and greatly simplified the process of uploading sourcemaps from updates. [learn more](https://expo.dev/changelog#first-class-expo-support-in-sentry)
