### ISSUE TITLE
Facebook Ads not showing after build

### ISSUE THREAD

**Issue by elazzabi** [expo/expo#265]
Hello guys,
I'm running my first app using CRNA and wanted to test facebook ads. I did as documentation suggests (native ads part) and I can see them in dev mode.

However when I build the apk and install it on my phone, the ads aren't displayed in the app (with no crashing... the app works fine)

I'm I missing something?

**Comment by elazzabi** [comment]
Tried with a new placementid, and it seems Facebook didn't receive any hit to send the ad (from the dashboard).

**Comment by brentvatne** [comment]
@elazzabi - sorry did changing the placementid fix the issue?

**Comment by elazzabi** [comment]
@brentvatne No, same problem :/ ... Do I need to add my application for review or something in Facebook?

**Comment by elazzabi** [comment]
Hello @satya164 ,
I think I just found why. This is from the Facebook dashboard
![image](https://user-images.githubusercontent.com/12542046/27243848-684dbc1a-52d3-11e7-9c34-d4a16ec26ec1.png)
I think Facebook detects the expo runtime bundled with the app, instead of the app itself. Here is my app.json:
```
{
   "expo": {
    "name": "Maroc News",
    "icon": "./assets/logo.png",
    "version": "0.0.1",
    "slug": "maroc-news",
    "sdkVersion": "17.0.0",
      "ios": {
        "bundleIdentifier": "com.blablaapps.marocnews",
      },
      "android": {
        "package": "com.blablaapps.marocnews",
      }
    }
 }
```

**Comment by brentvatne** [comment]
@elazzabi - can you join our slack and ping me? http://slack.expo.io/ -- I'm @brentvatne on slack

**Comment by satya164** [comment]
Hello. I tried the app you sent me, but it was stuck on "Logo goes here" screen, it went past it once, but I got `NavigationButton` not defined error. So I couldn't really test.

Couple of questions,
- do you get the error in a prod build (via exp build)?
- are you using the same id for both prod and dev? can you try creating a different one for dev? if it works for you then I'll update the docs

**Comment by elazzabi** [comment]
Hello @satya164,
I forgot to push a fix for the NavigationButton problem, it's fixed now. Sorry about that.

About your questions:
* Yes, in dev mode the ads are working correclty. But when I build the .apk (using exp build) and install it on my phone, they stop showing.
* I tried using different IDs, but the same problem persists

**Comment by satya164** [comment]
@elazzabi hey, when Facebook asked for the URL to playstore in the dashboard, what did you enter? It should be your app's package name there instead of the expo's package name.

**Comment by elazzabi** [comment]
@satya164 didn't enter anything in the box. Should I add it manually?

**Comment by satya164** [comment]
As we discussed on slack, you need to publish your app on Playstore/App Store for real ads.
