### ISSUE TITLE
expo sqlite / expo-file-system unsupported url 1002 on ios bundle

### ISSUE THREAD

**Issue by Sznapsollo** [expo/expo#26502]
### Minimal reproducible example

https://github.com/Sznapsollo/expo_ios_bundle_unsupportedurl_1002

### Summary

Case: copy sqlite db3 database from app assets to documentDirectory.

While it works perfectly on android expo, android simulator bundle, android prod bundle, ios expo
It does not work on ios bundle (simulator or production) returning error below. It happens when i build locally and also when app is build using expo services.

Exception is Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" (also attached screen from catch lot on ios)

It happens when performing the following code:
```
       await FileSystem.downloadAsync(
          Asset.fromModule(require('./assets/test_database.db3')).uri,
          FileSystem.documentDirectory + 'SQLite/test_database.db3'
        );
```
db3 extensions are added and also configured in metro.config.js in assetExts

I have browsed many docs about this but nothing works so far.
I have found similar bug report - https://github.com/expo/expo/issues/23455
This report contains info how to handle this by @alanjhughes but comment is what turns out I am actually using and the result is still 1002

![image](https://github.com/expo/expo/assets/20971560/50bf795e-082f-4766-bbae-4a8eb22b0bee)

Thank you kindly for your help

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 6.0.0
    Expo Workflow: managed

**Comment by MobileMon** [comment]
I'm having the same issue? Have you found a solution?

**Comment by Sznapsollo** [comment]
Hi still searching and trying all i can find but so far nothing ;-( I am also updating repo occassionally  with newest versions i tested but even though versions change problem still persists. Hard to believe this is not problem for more people not being able to deploy app with predefined sqlite db for ios devices.

**Comment by gabrieldonadel** [comment]
Hi @Sznapsollo, given that you want to copy a sqlite db3 database from a local asset (from app assets to `documentDirectory` )it would be better to use the `copyAsync` method (https://docs.expo.dev/versions/latest/sdk/filesystem/#copyasyncoptions).

In your case it would look like this 
```
await FileSystem.copyAsync({
          from: Asset.fromModule(require("./assets/test_database.db3")).uri,
          to: FileSystem.documentDirectory + "SQLite/test_database.db3",
});
```

**Comment by Sznapsollo** [comment]
Hi @gabrieldonadel  thank you for your response. I have already tried copyAsync but disregarded it since it was not working presenting the following error  (when running on dev expo go app) - at least downloadAync works on everything except  for production ios. Is there any working example with copyAsync?

 WARN  [Error: Call to function 'ExponentFileSystem.copyAsync' has been rejected.
→ Caused by: java.io.IOException: Location 'http://192.168.0.95:8081/assets/?unstable_path=.%2Fassets%2Ftest_database.db3&platform=android&hash=dd2a0fff6b00ed3ac7ca7070d20360e3' isn't readable.]

**Comment by gabrieldonadel** [comment]
I see, are you using Expo Go for development or expo-dev-client?

**Comment by Sznapsollo** [comment]
I have tried sec ago with Expo Go on emulator with result above. But i remember had similar issue when trying this on ios emulator as well some time ago.

Almost newest versions at this moment
"expo": "~50.0.6",
    "expo-asset": "^9.0.2",
    "expo-file-system": "^16.0.4",
    "expo-sqlite": "~13.2.2",

**Comment by gabrieldonadel** [comment]
The main difference between running a production build and a dev build is that, in a dev build your bundle will be served from a server, and `Asset.fromModule(require("./assets/test_database.db3")).uri` will point to a remote URL. In a production/release build the app is bundled and `Asset.fromModule(require("./assets/test_database.db3")).uri` will point to a local internal file.

To support both cases when using Expo Go I would recommend doing something like 

```

if (__DEV__) {
        await FileSystem.downloadAsync(
          Asset.fromModule(require("./assets/test_database.db3")).uri,
          FileSystem.documentDirectory + "SQLite/test_database.db3",
          { sessionType: FileSystem.FileSystemSessionType.FOREGROUND }
        );
} else {
        await FileSystem.copyAsync({
          from: Asset.fromModule(require("./assets/test_database.db3")).uri,
          to: FileSystem.documentDirectory + "SQLite/test_database.db3",
        });
}
```

**Comment by Sznapsollo** [comment]
@gabrieldonadel using separately copyAsync (prod) and downloadAsync (dev) solved the problem on all platforms. Thanjk you very much.
