### ISSUE TITLE
[expo-file-system]: Upload fails with "resource exceeds maximum size"

### ISSUE THREAD

**Issue by jacobjonsson** [expo/expo#26508]
### Minimal reproducible example

https://github.com/jacobjonsson/expo-file-system-repo

### Summary

After upgrading to SDK 50 calling `uploadAsync` or `createUploadTask` from `expo-file-system` fails with `Error Domain=NSURLErrorDomain Code=-1103 "resource exceeds maximum size"`.

This does not happen in version `15.4.5` but does happen in version `16.0.4`.

I've included a reproducible example that is posting to a dummy URL and the same error is still happening. In my real example, we are uploading to an S3 link and getting the same error.

### Environment

 ```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.11.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    npmGlobalPackages:
      eas-cli: 6.0.0
    Expo Workflow: managed
```

**Comment by domodu-apps** [comment]
Getting the same error with SDK 50 calling uploadAsync from expo-file-system, with Error Domain=NSURLErrorDomain Code=-1103 "resource exceeds maximum size"

**Comment by jacobjonsson** [comment]
@domodu-apps it's fixed in `16.0.5`. It was just released so try upgrading.

**Comment by domodu-apps** [comment]
Ok, so "expo-file-system": "~16.0.5" fixes this, thanks

**Comment by comontes** [comment]
> After updating to `16.0.5` I'm still getting 
> 
> 
> 
> ```
> 
> [Error: Unable to upload the file: 'Error Domain=NSURLErrorDomain Code=-1103 "resource exceeds maximum size" UserInfo={NSErrorFailingURLStringKey=https://....s3.us-east-1.amazonaws.com/...,t, _NSURLErrorRelatedURLSessionTaskErrorKey=(
> 
>     "BackgroundUploadTask <D17050EE-E9B7-421E-BE7F-1A8FC4E1DF3F>.<2>",
> 
>     "LocalUploadTask <D17050EE-E9B7-421E-BE7F-1A8FC4E1DF3F>.<2>"
> 
> ), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <D17050EE-E9B7-421E-BE7F-1A8FC4E1DF3F>.<2>, NSLocalizedDescription=resource exceeds maximum size}']
> 
> ```

I also updated expo, and did a rebuild of my expo dev client app. Have you tried that?

**Comment by younes0** [comment]
I also get an error on iOS with `FileSystem.uploadAsync` with latest `expo`, `expo-dev-client`, `expo-file-system` 

```
 ERROR  [Error: Unable to upload the file: 'Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=http://192.168.200.13:4000/api/upload/profile-photo, NSErrorFailingURLKey=http://192.168.200.13:4000/api/upload/profile-photo, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <F70E9BF6-C2DC-4E13-A79D-04655CCABCAA>.<7>",
    "LocalUploadTask <F70E9BF6-C2DC-4E13-A79D-04655CCABCAA>.<7>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <F70E9BF6-C2DC-4E13-A79D-04655CCABCAA>.<7>, NSLocalizedDescription=cancelled}']
```

**Comment by landlove** [comment]
`|

Error: Unable to upload the file: 'Error Domain=NSURLErrorDomain Code=-999 "취소됨" UserInfo={NSErrorFailingURLStringKey=https://food.medieng.com/api/file/4/Cert/Test/empty/true/1920/1920/true, NSErrorFailingURLKey=https://food.medieng.com/api/file/4/Cert/Test/empty/true/1920/1920/true, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <A73C6B7B-B6A8-4142-A728-D8985141D275>.<1>",
    "LocalUploadTask <A73C6B7B-B6A8-4142-A728-D8985141D275>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <A73C6B7B-B6A8-4142-A728-D8985141D275>.<1>, NSLocalizedDescription=취소됨}']`


I also get a similar error.

**Comment by younes0** [comment]
@landlove we should open another issue with a reproducible demo. Note that this happens with MULTIFORM PART uploads only.

**Comment by ethras** [comment]
> createUploadTask

I get the same error did you find a workaround ?

**Comment by Jackman3005** [comment]
Hey @younes0  and @landlove, have either of you made another issue yet? I am getting this error when we try to upgrade to Expo 50. Nothing I change seems to alter the effect. I investigated a lot of the commits in `expo-file-system` in the last few months and didn't see anything suspicious that caught my attention. I'm pretty stumped as to what could be happening here...

Here is what I see when I print the error thrown by `uploadAsync`:
```
[Error: Unable to upload the file: 'Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://api.cloudinary.com/v1_1/questmate-testing/auto/upload, NSErrorFailingURLKey=https://api.cloudinary.com/v1_1/questmate-testing/auto/upload, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <8403A4A5-8290-4773-A91B-58832FF985F0>.<12>",
    "LocalUploadTask <8403A4A5-8290-4773-A91B-58832FF985F0>.<12>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <8403A4A5-8290-4773-A91B-58832FF985F0>.<12>, NSLocalizedDescription=cancelled}']
```

If I stringify the error it prints:
```
{"code":"ERR_FILESYSTEM_CANNOT_UPLOAD"}
```

**Comment by younes0** [comment]
@Jackman3005 we have the same error since 50 and I didn't see either expo commits that could cause this issue. Must be on the react-native level. 
I gave up on using `expo-filesystem` on iOS and used formData. I loose the background benefit of `FileSystem.uploadAsync` though.

**Comment by Jackman3005** [comment]
I created [an issue](https://github.com/expo/expo/issues/26750) to track this as we would like to keep background upload working.
