### ISSUE TITLE
CONFIGURE_EXPO_UPDATES build fail

### ISSUE THREAD

**Issue by superyarik** [expo/expo#26518]
### Summary

it working severals days ago, nothing changed in project

running  `eas build --platform android --profile=huawei --local --clear-cache ` and get error

```
[CONFIGURE_EXPO_UPDATES] 
TypeError: (0 , Updates_1.getRuntimeVersionNullable) is not a function
    at configureExpoUpdatesIfInstalledAsync (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/utils/expoUpdates.js:120:195)
    at async /Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/android.js:70:9
    at async BuildContext.runBuildPhase (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/context.js:101:28)
    at async buildAsync (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/android.js:69:5)
    at async runBuilderWithHooksAsync (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.androidBuilder (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/android.js:24:16)
    at async buildAndroidAsync (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/dist/android.js:66:12)
    at async buildAsync (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/dist/build.js:52:29)
    at async main (/Users/ww/.npm/_npx/42219/lib/node_modules/eas-cli-local-build-plugin/dist/main.js:16:9)

Build failed
Unknown error. See logs of the Configure expo-updates build phase for more information.
npx exited with non-zero code: 1
```

### What platform(s) does this occur on?

Android

### SDK Version

48

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.21.3 - /opt/homebrew/opt/node@14/bin/node
      npm: 6.14.18 - /opt/homebrew/opt/node@14/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.2 
      expo: ~48.0.21 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
      react-navigation: github:superyarik/react-navigation#react-navigation-v4.4.4-gitpkg => 4.4.4 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed

### Minimal reproducible example

none

**Comment by superyarik** [comment]
seems like it connected with new SDK50 release

**Comment by ethras** [comment]
Facing the same issue since upgrading to SDK 50

**Comment by janwiebe-jump** [comment]
Same here, looks like it happenend in this commit:
https://github.com/expo/expo/commit/f0d67e12b86ea8b5ca76cec45d2d36c752c9caf2#diff-96ba98a7415bdf34c6eff86a6ca0ac58366ea9649d29c182a5231567e51bbec4

The `getRuntimeVersionNullable` function was removed there, instead the `getRuntimeVersionNullableAsync` was introduced.
The package expo-utils hasn't been updated with this change
https://github.com/expo/eas-build/blob/742ce93d5991b29ca6ce450b109899f70fd8bcc3/packages/build-tools/src/utils/expoUpdates.ts#L140

**Comment by guilherme-vp** [comment]
Same here. Adding more context to this thread, this breaking change replacement was introduced in mid-September 2023: https://github.com/expo/expo/blob/4a6e16119d8ab143392f6fee2d6f09d2c03fe1a0/packages/%40expo/config-plugins/CHANGELOG.md?plain=1#L70-L72.

**Comment by guilherme-vp** [comment]
Proxying the issue raised in `eas-cli`: https://github.com/expo/eas-cli/issues/2190

**Comment by wodin** [comment]
@szdziedzic fixed this in `eas-cli` 7.0.0:
https://github.com/expo/eas-cli/issues/2190#issuecomment-1900575234

**Comment by Jarxi** [comment]
Still having issue when upgrade to eas-cli:7.3.0

**Comment by wodin** [comment]
Did you install it globally using `yarn`? If so, see this:
https://github.com/expo/eas-cli/issues/2190#issuecomment-1901739651

**Comment by mbiang** [comment]
I am also having this issue on Expo SDK < 50.  Expo SDK 50 seems to work without any issues.

**Comment by MhamedRamadan10** [comment]
The issue seems on local `/.npm/_npx/randomId/node_modules/@expo/build-tools/` where this function `(0 , Updates_1.getRuntimeVersionNullable)` changed to `getRuntimeVersionNullableAsync ()`
so, I presume that updating local npm might be a solution.

**Comment by dbaonguis** [comment]
I am seeing this issue after upgrading from sdk 49 to 50.

**Comment by dbaonguis** [comment]
I just fixed it by updating the"@expo/config-plugins" under "resolutions" section in package.json.

`
"resolutions": {
    "@expo/config-plugins": "7.8.4"
  },
`

**Comment by wodin** [comment]
It is best to avoid having `@expo/config-plugins` or similar in `resolutions`. Rather remove it and see if `npx expo-doctor@latest` complains about anything. Then try to fix those things. Only use `resolutions` as a last resort. Otherwise you will run into problems with your upgrades in future.

**Comment by dbaonguis** [comment]
> It is best to avoid having `@expo/config-plugins` or similar in `resolutions`. Rather remove it and see if `npx expo-doctor@latest` complains about anything. Then try to fix those things. Only use `resolutions` as a last resort. Otherwise you will run into problems with your upgrades in future.

this is a good suggestion, thanks. I will try this.
