### ISSUE TITLE
[SDK 50] [babel-preset-expo] Can't set process.env.EXPO_PUBLIC vars in Jest

### ISSUE THREAD

**Issue by chriszs** [expo/expo#26513]
### Minimal reproducible example

https://github.com/chriszs/test-expo-app/pull/1/files

### Summary

In my Expo project I'm setting values for `process.env` variables in a global Jest setup file so that I can test files which reference those variables, which seems to be an accepted pattern, and which has worked so far. However, EXPO_PUBLIC variables now appear to be undefined in Jest even after being directly set, e.g. this fails:
```js
process.env.EXPO_PUBLIC_THIS_IS_A_TEST = 'test';
expect(process.env.EXPO_PUBLIC_THIS_IS_A_TEST).toBe('test');
```
This succeeds:
```js
process.env.THIS_IS_A_TEST = 'test';
expect(process.env.THIS_IS_A_TEST).toBe('test');
```

In the actual project, this happens in the setup file, not directly in the test. I've also tried setting them in an .env file, and that appears not to work either.

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.asdf/installs/nodejs/18.17.1/bin/node
      npm: 9.6.7 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/admin/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    Expo Workflow: bare
```

**Comment by EvanBacon** [comment]
Environment variables are instantiated in Metro. You can add them to jest using a setup script and calling the env loading manually:
```js
import { load } from '@expo/env'
load(process.cwd())
```

**Comment by chriszs** [comment]
Thanks! That's helpful, but didn't resolve the issue in my testing. I wonder if something in the way Babel [deals with these](https://github.com/expo/expo/blob/8d29bbba0ccd4ecb35bac0df7b512ee129d3cde8/packages/babel-preset-expo/src/inline-env-vars.ts#L5-L32) changed.

**Comment by mikejonas** [comment]
I'm running into a similar problem. I haven't debugged why, but assigning process.env to a variable fixes it:

```js
// this is undefined
const environment process.env.EXPO_PUBLIC_APP_ENV

// this is defined
const env = process.env
const environment = env.EXPO_PUBLIC_APP_ENV as string
```

**Comment by chriszs** [comment]
Forgive me, that should have been `babel-preset-expo`. Unfortunately downgrading the Babel preset causes compiling the latest expo-router to fail, so I'm doing this temporarily:
```
    presets: [
      process.env.NODE_ENV === 'test'
        ? 'module:@react-native/babel-preset'
        : 'babel-preset-expo',
    ],
```

Testing with a different Babel preset is less than ideal, but that's all I can think of to do.

**Comment by chriszs** [comment]
Should be closed when #26766 lands. 🎉

**Comment by chriszs** [comment]
@mikejonas So it looks like the issue you mentioned is related to some [documented](https://docs.expo.dev/guides/environment-variables/#how-variables-are-loaded) behavior:
> Every environment variable must be statically referenced as a property of process.env using JavaScript's dot notation for it to be inlined. For example, the expression process.env.EXPO_PUBLIC_KEY is valid and will be inlined.
>
> Alternative versions of the expression are not supported. For example, process.env['EXPO_PUBLIC_KEY'] or const {EXPO_PUBLIC_X} = process.env is invalid and will not be inlined.

This just bit me with a crash during QA testing, because I'd done optional chaining like `process.env?.EXPO_PUBLIC...`, which breaks the inlining. That isn't entirely the behavior I'd have expected, but that seems like a separate issue.

**Comment by hanyufoodles** [comment]
I've also encountered this problem and by debugging the babel preset I find that there is an option to opt out env var inlining.

The inlining is enabled when this is `true`: https://github.com/expo/expo/blob/a05bfbc3a907177bca2dd8a2dd22073763daa895/packages/babel-preset-expo/src/index.ts#L78

And in the function: https://github.com/expo/expo/blob/a05bfbc3a907177bca2dd8a2dd22073763daa895/packages/babel-preset-expo/src/common.ts#L96-L105

However in jest tests `isNodeModule`, `isWebpack`, `isDev`, `isServer` are all `false`. The only thing we can change is `preserveEnvVars` on the caller options.

For this to work with `jest-expo` preset you need to override the transformer in `jest.config.js`:
```js
transform: {
  '\\.[jt]sx?$': ['babel-jest', { caller: { preserveEnvVars: true } }],
},
```

Personally I don't think we should inlining env vars in test I'd rather prefer to always env vars when `NODE_ENV === 'test'`. Or `jest-expo` should provide a proper way to do this without needing to override the transformer. Anyway I didn't find any doc about `preserveEnvVars` this clearly needs some documentation.

**Comment by 1ChristianAlex** [comment]
> I'm running into a similar problem. I haven't debugged why, but assigning process.env to a variable fixes it for me
> 
> ```js
> // this is undefined
> const environment = process.env.EXPO_PUBLIC_APP_ENV
> 
> // this is defined
> const env = process.env
> const environment = env.EXPO_PUBLIC_APP_ENV
> ```

By adding `import { load } from "@expo/env";
load(process.cwd());` on top of `jest.setup.ts` and doing this suggestion, a got the problem solved.

**Comment by chriszs** [comment]
Can confirm the `preserveEnvVars` approach seems to work.

**Comment by KristhDev** [comment]
The expo SDK 52 keeps giving the same problem, when I try the solution using the transform I get the following error:

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    SyntaxError: C:\Users\krist\Proyectos de Javascript\JWReports\node_modules\@react-native\js-polyfills\error-guard.js: Missing semicolon. (14:4)

      12 | let _inGuard = 0;
      13 |
    > 14 | type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         |     ^
      15 | type Fn<Args, Return> = (...Args) => Return;

Any solution?
