### ISSUE TITLE
[expo-barcode-scanner][iOS] - NSMicrophoneUsageDescription is added to Info.plist

### ISSUE THREAD

**Issue by Nodonisko** [expo/expo#26520]
### Minimal reproducible example

Add latest version of `expo-barcode-scanner` to Expo Prebuild project

### Summary

If I add package `expo-barcode-scanner@12.9.2` to my Expo managed project, it will also `NSMicrophoneUsageDescription` to Info.plist, but I don't think there is reason why code scanning library should need microphone permission. 

It's also in docs https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/#permissions but without any explanation why it's needed for iOS. For Android it seems to be fine.

Would be nice to remove this requirement from library or add option to disable it using config plugin.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/Library/Caches/fnm_multishells/4256_1705665945744/bin/node
      Yarn: 4.0.2 - ~/Library/Caches/fnm_multishells/4256_1705665945744/bin/yarn
      npm: 9.6.7 - ~/Library/Caches/fnm_multishells/4256_1705665945744/bin/npm
      Watchman: 2023.10.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by ArianHamdi** [comment]
I think it would be better to open a discussion and ask for this permission usage.
