### ISSUE TITLE
SDK 50 and LinearGradientView does not work with start and end coordinates

### ISSUE THREAD

**Issue by hnzufx** [expo/expo#26531]
### Minimal reproducible example

https://snack.expo.dev/@hnzufx/simple-linear-gradient

### Summary

In Expo SDK 50 you cannot set start and end coordinates. You will get the error:

 ERROR  Cannot set prop 'endPoint' on view 'class expo.modules.lineargradient.LinearGradientView'
→ Caused by: java.lang.IllegalArgumentException: Class declares 0 type parameters, but 2 were provided.
 ERROR  Cannot set prop 'startPoint' on view 'class expo.modules.lineargradient.LinearGradientView'
→ Caused by: java.lang.IllegalArgumentException: Class declares 0 type parameters, but 2 were provided.

You can reproduce the bug by creating a new project:

npx expo install expo-linear-gradient
cd expo-linear-gradient

and the linked snack as App.js. The snack works because it's SDK 49. In SDK 50 it doesn't work.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/opt/node@20/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/opt/node@20/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 6.0.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by hnzufx** [comment]
Forgot to mention but it looks like it's only on Android. On the web and iOS simulator it works fine.

**Comment by XChikuX** [comment]
Seems like the bug is in the Expo **android app** and not really a big issue with the SDK itself.

I was still running expo sdk 49 and was still seeing the issue. Upgraded to 50 and still there.

Has to be the app.

**Comment by hnzufx** [comment]
@XChikuX You're right! I compiled a native app and in the native Android app everything works fine. So it's in the Expo app.

@alanjhughes Thanks for the fix.

**Comment by szmarczak** [comment]
I'm seeing this issue as well and this is one of the blockers from migrating to SDK 50.

**Comment by rakss17** [comment]
I'm also experiencing this error and waiting for a possible solution

**Comment by alanjhughes** [comment]
The fix requires releasing a new version of expo go which will take a few days. You can build a development client to avoid this problem.

**Comment by psathish10** [comment]
I am also encountering this issue. Could it cause any problems with my build, and how can it be resolved?

" ERROR  Cannot set prop 'startPoint' on view 'class expo.modules.lineargradient.LinearGradientView'
→ Caused by: java.lang.IllegalArgumentException: Class declares 0 type parameters, but 2 were provided."

**Comment by hnzufx** [comment]
@psathish10 It's a bug in the Expo app. When you build a native app (Android or iOS) the problem with the gradients do not occur. In the next update for the Expo app this will be resolved.

**Comment by valentina-cyril** [comment]
i was having the same issue and then I updated my expo go app and it stopped

**Comment by psathish10** [comment]
> i was having the same issue and then I updated my expo go app and it stopped

 @valentina-cyril  Thank you,The error message is now gone, and I appreciate your help.

**Comment by josephmyalla** [comment]
@valentina-cyril , You awsome, I had same error too, many thanks

**Comment by Ndahseh** [comment]
Anyone available to help me out?

**Comment by imlogicgates** [comment]
in expo 51.0.31 linear gradient doesn't work as well
