### ISSUE TITLE
[SDK50-expo-fonts]

### ISSUE THREAD

**Issue by mzaien** [expo/expo#26530]
### Minimal reproducible example

https://github.com/mzaien/expo-50-custom-font-issue/tree/main

### Summary

I'm trying to use custom font with expo 50 it was working with me on expo 49, the example is not a CGN but even on my real pojrect that is CGN it did not work

## expo go 

![image](https://github.com/expo/expo/assets/43112535/5b93ded1-ea16-42bc-a501-ba8904692abc)

## expo CGN

<img width="1054" alt="image" src="https://github.com/expo/expo/assets/43112535/82cf06bd-64e4-47d9-952c-8b15476637b8">

### Environment

- latest mac os / xcode
- m1 arch 
- using vscode

**Comment by brentvatne** [comment]
`useFonts` is async, you need to delay rendering until the fonts are loaded if you load dynamically

```
  const [fontsLoaded] = useFonts({
    "Inter-SemiBold": require("./assets/fonts/Inter-SemiBold.ttf"),
  });


  if (!fontsLoaded) {
    return;
  }

```

learn more: https://docs.expo.dev/develop/user-interface/fonts/
