### ISSUE TITLE
Babel error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by AlexRAV** [expo/expo#2654]
### Environment

```
Expo CLI 2.3.5 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.0 => 31.0.4
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^2.0.4 => 2.18.2
    npmGlobalPackages:
      expo-cli: 2.3.5

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/alexrav-d2101839-f4ee-4823-8abd-1ecce42be675.tar.gz
```
### Steps to Reproduce

I had an application, using SDK 27, then I change SDK version to 31 and ejected my app using ExpoKit.
After that, in IOS simulator I have got the following error:

`Plugin/Preset files are not allowed to export objects, only functions.`

### Expected Behavior

App build successful

### Actual Behavior

I get the error in terminal:

`Plugin/Preset files are not allowed to export objects, only functions.`

**Comment by AlexRAV** [comment]
My babel-preset-expo version is 5.0.0

**Comment by nicknovitski** [comment]
What version of babel is your project using?  If less than 7.1, I'd suggest upgrading.

If that fixes the problem, then we need to add a peerDependency to babel-preset-expo to prevent it for other users.

**Comment by AlexRAV** [comment]
Hi, @nicknovitski in my node_modules folder there is two babel version. First  `/node_modules/babel-core/` version is 6.26.3, second `/node_modules/@babel/core/` verion is 7.1.5.

In my package.json I don't have any babel versions. I don't know how exactly babel-preset-expo choose which version of babel need to use and don't understand how I can fix this issue, except manually writing to my package.json 7 version of babel, but I'm don't sure that it will works.

**Comment by AlexRAV** [comment]
@rouaks hi!
I have just downgraded my expo SDK version to 30 version and then eject my app.
I don't know how to resolve this problem anyway.

**Comment by artyorsh** [comment]
Hi @AlexRAV 
Check our [boilerplate](https://github.com/akveo/akveo-react-native-boilerplate/tree/typescript). This repo contains all initial configurations to make things working with new expo-31, babel 7, typescript and jest.

**Comment by ide** [comment]
With SDK 31, the current SDK, you need to make sure you're using Babel 7 everywhere. You can run `yarn why babel-core` to see if Babel 6 is included and why that is.

**Comment by krini** [comment]
Did anyone succeed in getting it to work with SDK 31 or 32?

**Comment by lanklaas** [comment]
@krini this solved the issue for me: https://github.com/expo/expo/issues/2576

**Comment by ide** [comment]
Closing this since the issue appears to be related to specific projects' Babel configurations or node_modules setups.
