### ISSUE TITLE
expo-image-manipulator build fails on IOS / Expo 49 & 50

### ISSUE THREAD

**Issue by therealpurplemana** [expo/expo#26541]
### Minimal reproducible example

npx expo run:ios --device (or eas build) fails to build expo-image-manipulator for IOS

### Summary

I installed expo-image-manipulator and used it successfully on Android.  When building for iOS, it throws an error in the swift modules.  The pod install completes successfully however npx expo run:ios --device will fail to complete the build.

Expo:  Tested on 49 and 50
expo-image-manipulator: 11.8.0
iOS:  Targeting version 16.0 but don't think this matters

  (../../node_modules/expo-image-manipulator/ios/ImageManipulatorModule.swift:61:11)

  59 |       return callback(.failure(ImageLoaderNotFoundException()))
  60 |     }
> 61 |     guard FileSystemUtilities.permissions(appContext, for: url).contains(.read) else {
     |           ^ cannot find 'FileSystemUtilities' in scope
  62 |       return callback(.failure(FileSystemReadPermissionException(url.absoluteString)))
  63 |     }
  64 | 

❌  (../../node_modules/expo-image-manipulator/ios/ImageManipulatorModule.swift:61:75)

  59 |       return callback(.failure(ImageLoaderNotFoundException()))
  60 |     }
> 61 |     guard FileSystemUtilities.permissions(appContext, for: url).contains(.read) else {
     |                                                                           ^ cannot infer contextual base in reference to member 'read'
  62 |       return callback(.failure(FileSystemReadPermissionException(url.absoluteString)))
  63 |     }
  64 | 

❌  (../../node_modules/expo-image-manipulator/ios/ImageManipulatorModule.swift:100:50)

   98 |    */
   99 |   internal func saveImage(_ image: UIImage, options: ManipulateOptions) throws -> SaveImageResult {
> 100 |     guard let cachesDirectory = self.appContext?.config.cacheDirectory else {
      |                                                  ^ value of type 'AppContext' has no member 'config'
  101 |       throw FileSystemNotFoundException()
  102 |     }
  103 | 

❌  (../../node_modules/expo-image-manipulator/ios/ImageManipulatorModule.swift:108:5)

  106 |     let fileUrl = directory.appendingPathComponent(filename)
  107 | 
> 108 |     FileSystemUtilities.ensureDirExists(at: directory)
      |     ^ cannot find 'FileSystemUtilities' in scope
  109 | 
  110 |     guard let data = imageData(from: image, format: options.format, compression: options.compress) else {
  111 |       throw CorruptedImageDataException()

### Environment

OSX M3

**Comment by focux** [comment]
Did you figure out how to fix this? I've been trying to fix this for many days and still no luck.

**Comment by sidpremkumar** [comment]
+1 still seeing this
