### ISSUE TITLE
Router error on expo dev client

### ISSUE THREAD

**Issue by hyochan** [expo/expo#26542]
### Minimal reproducible example

https://github.com/hyochan/BooKoo/pull/3

### Summary

When upgrading `expo-dev-client` proj to expo SDK50 and rebuilding it, it throws below error.
```
iOS Bundling failed 9018ms (node_modules/expo-router/entry.js)
error: node_modules/expo-router/_ctx.ios.js: /Users/hyo/Github/hyochan/BooKoo/node_modules/expo-router/_ctx.ios.js: Expected `fromDir` to be of type `string`, got `undefined`
```

## Screenshot

<img src="https://github.com/expo/expo/assets/27461460/049e9ab6-6372-473a-a52e-64648bcb0c3b" width="320" />

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - ~/Github/hyochan/BooKoo/node_modules/.bin/yarn
      npm: 10.2.5 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0 => 50.0.2 
      expo-router: ~3.4.4 => 3.4.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.9 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 6.1.0
    Expo Workflow: bare

**Comment by hyochan** [comment]
Closing because this issue is related to https://github.com/kristerkari/react-native-svg-transformer/issues/329

**Comment by Shubhamm-V** [comment]
I was facing the same issue. I uninstalled expo-router and reinstalled it, which fixed the problem.
