### ISSUE TITLE
> Task :expo:checkDebugUnitTestAarMetadata FAILED after running ./gradlew build

### ISSUE THREAD

**Issue by benxoa** [expo/expo#26557]
### Summary

i got this error after i tried to run gradlew build in my android folder:

```
> Task :expo:checkDebugUnitTestAarMetadata FAILED

> Task :app:lintReportDebug                                                                                                                                            
Wrote HTML report to file:///E:/GEN/android/app/build/reports/lint-results-debug.html

FAILURE: Build failed with an exception.                                                                                                                               

* What went wrong:
Execution failed for task ':expo:checkDebugUnitTestAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 2 issues were found when checking AAR metadata:

       1.  Dependency 'androidx.core:core-ktx:1.12.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :expo is currently compiled against android-33.

           Recommended action: Update this project to use a newer compileSdk
           of at least 34, for example 34.

           Note that updating a library or application's compileSdk (which
           allows newer APIs to be used) can be done separately from updating
           targetSdk (which opts the app in to new runtime behavior) and
           minSdk (which determines which devices the app can be installed
           on).

       2.  Dependency 'androidx.core:core:1.12.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :expo is currently compiled against android-33.

           Recommended action: Update this project to use a newer compileSdk
           of at least 34, for example 34.

           Note that updating a library or application's compileSdk (which
           allows newer APIs to be used) can be done separately from updating
           targetSdk (which opts the app in to new runtime behavior) and
           minSdk (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 8s
```
### HERE IS MY REPORT
![Screenshot 2024-01-21 004125](https://github.com/expo/expo/assets/143406036/66ad5f97-db18-4236-b282-198788d80670)
![Screenshot 2024-01-21 004233](https://github.com/expo/expo/assets/143406036/9a9dc9a4-2f10-4dcf-acc8-a11e090e89b6)
![Screenshot 2024-01-21 004203](https://github.com/expo/expo/assets/143406036/cf66501e-cdf2-420b-af93-e084b3b3335d)
![Screenshot 2024-01-21 004144](https://github.com/expo/expo/assets/143406036/78f65f1f-d345-4026-a32e-096ee98d0f7d)

### What platform(s) does this occur on?

Android

### SDK Version

50.0.0

### Package.json
`{
  "name": "gen",
  "version": "2.1.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/config-plugins": "~7.8.0",
    "@expo/prebuild-config": "~6.7.0",
    "@react-native-community/cli": "^12.3.1",
    "@react-native-community/netinfo": "11.1.0",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "axios": "^1.6.5",
    "eas-cli": "^6.0.0",
    "expo": "^50.0.0",
    "expo-constants": "~15.4.5",
    "expo-dev-client": "~3.3.6",
    "expo-file-system": "~16.0.4",
    "expo-font": "~11.10.2",
    "expo-modules-core": "~1.11.7",
    "expo-sharing": "~11.10.0",
    "expo-splash-screen": "~0.26.3",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "expo-updates": "~0.24.8",
    "global": "^4.4.0",
    "missing-asset-registry-path": "^0.0.0",
    "nativewind": "^2.0.11",
    "postcss": "^8.4.33",
    "react": "18.2.0",
    "react-native": "0.73.2",
    "react-native-fs": "^2.20.0",
    "react-native-google-mobile-ads": "^12.10.0",
    "react-native-indicators": "^0.17.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-share": "^10.0.2",
    "react-native-svg-transformer": "^1.3.0",
    "sharp": "^0.33.2",
    "sharp-cli": "^4.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "metro": "^0.80.4",
    "tailwindcss": "^3.2.2"
  },
  "resolutions": {
    "glob": "7.2.0",
    "@expo/config-plugins": "~6.0.0"
  },
  "private": true
}
`
### npx react-native info

`System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12450H
  Memory: 1.27 GB / 15.68 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.21
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.6.7
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "26"
      - "28"
      - "29"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google Play Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11255304
  Visual Studio: Not Found
Languages:
  Java: 17.0.9
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 12.3.3
    wanted: ^12.3.1
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found`

### build.gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '34.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '21')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '33')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '33')
        kotlinVersion = findProperty('android.kotlinVersion') ?: '1.8.10'
        frescoVersion = findProperty('expo.frescoVersion') ?: '2.5.0'

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "25.1.8937393"
    }
    repositories {
        google()
        mavenCentral()
        jcenter()

    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.4.2')
        classpath('com.facebook.react:react-native-gradle-plugin')
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(['node', '--print', "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), '../android'))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(['node', '--print', "require.resolve('jsc-android/package.json')"].execute(null, rootDir).text.trim(), '../dist'))
        }

        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        jcenter()

    }
}

```

**Comment by Kudo** [comment]
hi there! it would be good if you could share some repro for troubleshooting. it looks like you need a higher `compilerSdkVersion` than 33. for expo sdk 50, we've bumped it to 34, you could check https://docs.expo.dev/bare/upgrade/ for the migration if you are running from a bare project. we also recommend to run your project as [CNG](https://docs.expo.dev/workflow/continuous-native-generation/) or managed project, that would make future upgrade easier.
