### ISSUE TITLE
ExternalLink adds client route

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#26566]
### Minimal reproducible example

https://github.com/rocket-meals/expo-baseUrl-reload-error

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

```
let url = "https://rocket-meals.de/demo/api/auth/..."
```

```
<ExternalLink target={"_self"} href={url} style={styles.link}>
            <Text style={styles.linkText}>{"Login with: "+provider+"\n"}</Text>
            <Text style={styles.linkText}>{"URL: "+url}</Text>
        </ExternalLink>
```

So what i get displayed is:

```
Login with: google
URL: https://rocket-meals.de/demo/api/auth/login/google?...
```

But when hovering with mouse over the link:

```
http://localhost:3000/rocket-mealshttps://rocket-meals.de/demo/api/auth/login/google...
```

It seems to add the current url of the frontend just before. This only happens in production. In dev mode it works as expected:

In production mode:
<img width="2032" alt="Bildschirmfoto 2024-01-21 um 20 00 09" src="https://github.com/expo/expo/assets/33295329/bee60947-e262-4f7f-beab-5e131abaaf0f">

Seems to be related to: https://github.com/expo/expo/issues/26565

### Environment

System:
  OS: macOS 13.4.1
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
  Yarn: 1.22.21 - /usr/local/bin/yarn
  npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Watchman: 2023.11.27.00 - /usr/local/bin/watchman
Managers:
  CocoaPods: 1.14.3 - /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
npmGlobalPackages:
  eas-cli: 6.0.0
Expo Workflow: managed

**Comment by NilsBaumgartner1994** [comment]
By adapting `ExternalLink.tsx` to print log:

```
import { Link } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import React from 'react';
import { Platform } from 'react-native';

export function ExternalLink(
  props: Omit<React.ComponentProps<typeof Link>, 'href'> & { href: string }
) {
  return (
    <Link
      target="_blank"
      {...props}
      // @ts-expect-error: External URLs are not typed.
      href={props.href}
      onPress={(e) => {
          console.log("ExternalLink onPress")
          console.log(props)
        if (Platform.OS !== 'web') {
          // Prevent the default behavior of linking to the default browser on native.
          e.preventDefault();
          // Open the link in an in-app browser.
          WebBrowser.openBrowserAsync(props.href as string);
        }
      }}
    />
  );
}
```

in production as in development it prints the correct url:

```
Object { target: "_self", href: "https://rocket-meals.de/demo/api/auth/login/google?redirect=https://rocket-meals.de/demo/api/redirect-with-token?redirect=http://localhost:3000/rocket-meals/login?directus_access_token=", style: {…}, children: (2) […] }
entry-2f42b1503a66ec7e752d377c9d307fe1.js:1916:255
```

So it seems that the href is passed correctly, indicating a deeper problem

**Comment by NilsBaumgartner1994** [comment]
Any new update?

**Comment by 6TELOIV** [comment]
I'm running into the same issue. Is the expo-router `Link` element not intended for use with external URLs? It works as you'd expect in dev environments, and without this `baseUrl` param, but having it automatically added to all `Link` href's breaks that functionality. It seems like a better behavior would be for `Link` elements to prepend `baseUrl` only if the `href` prop does not start with a protocol.

**Comment by 6TELOIV** [comment]
I think the fix for this is to modify the function at https://github.com/expo/expo/blob/main/packages/expo-router/src/fork/getPathFromState.ts#L697 to check if `path` specifies a protocol. If so, it should not be modified. Otherwise, prepend `basePath`.

potential fix:

```ts
const schemeCheck = /^[a-zA-Z\d+.-]+:/;
export function appendBaseUrl(
  path: string,
  baseUrl: string | undefined = process.env.EXPO_BASE_URL
) {
  if (process.env.NODE_ENV !== 'development' && !schemeCheck.test(path)) {
    if (baseUrl) {
      return `/${baseUrl.replace(/^\/+/, '').replace(/\/$/, '')}${path}`;
    }
  }
  return path;
}
```
