### ISSUE TITLE
Selfhosted app: not working with Update API

### ISSUE THREAD

**Issue by isthaison** [expo/expo#2656]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Steps to Reproduce

(Write your steps here:)

1. Hosting An App on Your Servers (IIS server) http://
2. configuring-ota-updates  
3. Update API  not working on IOS 

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by esamelson** [comment]
Hi @isthaison - we'll need more information than this in order to help you out. Can you explain exactly how you configured your project/build and post your app.json `updates` configuration? The more information you can provide to help us reproduce this, the better.

**Comment by isthaison** [comment]
config app.js 
 ` "updates": { "checkAutomatically": "ON_ERROR_RECOVERY" },`

function update
```
onUpdate = async () => {
    try {
      let { newversion } = this.state;
      if (newversion) {
        Updates.reloadFromCache();
      } else {
        const update = await Updates.checkForUpdateAsync();
        if (update.isAvailable) {
          this.setState(
            {
              isfetching: true,
            },
            async () => {
              await Updates.fetchUpdateAsync();
              this.setState({
                newversion: true,
                isfetching: false,
              });
            }
          );
        }
      }
    } catch (e) {
      console.log(e);
    }
  };
```

**Comment by quinlanj** [comment]
Hi @isthaison, I am trying to reproduce your problem, but the `Updates` API seems to be working for me. Here is what I did.

1. Create an expo project: `expo init`, and made my `App.js` something like this: https://snack.expo.io/@quinlanj/updates-example
2. Export app: `expo export --public-url https://quinlanj.github.io/my-test-app` (you would change your public url to your server endpoint)
3. Host the output directory at the server endpoint
4. From the Expo client development app (https://expo.io/tools#client), load in the QR code. I generated it using https://www.qr-code-generator.com/ with an url like `exps://quinlanj.github.io/my-test-app/android-index.json`
5. See the initial app load
6. Make a change to the project (I changed `Old Update` to `New Update`)
7. Run steps 2 & 3 again
8. From the expo client, press the `Update` button in the app
9. Update should be available and should reload app successfully

Note that Updates wont be available if:
1. You are running in dev mode (ie) you run `expo export --dev`
2. You didnt make any changes to your app (ie) your bundle is exactly the same

**Comment by isthaison** [comment]
I got it, i had done when run iis node on iis server.. It  working . thanks you!
