### ISSUE TITLE
App Transport Security policy error on iOS with Expo dev client in tunnel mode

### ISSUE THREAD

**Issue by tomrom-pomelo** [expo/expo#26573]
### Minimal reproducible example

https://github.com/tomrom-pomelo/expo-50-test

### Summary

After upgrading to SDK 50 and the latest expo-dev-client, we can no longer connect to our dev client with the `--tunnel` option set. 

To reproduce, first we can build a dev client for the simulator

```
eas build --profile development-simulator --platform ios
```

then install the app and run

```
npx expo start --tunnel
```

If we try to open it on the dev client, we get the error:

> Failed to load app from http://ehudf9i.tromano.8081.exp.direct with error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection

I am installing the app on a simulator running iOS 17.2. The dev client succeeds in connecting if I do not use the `--tunnel` mode. I provided a _very_ minimal reproducible example, essentially just using the bear `npx create-expo-app` result with a dev client profile set up.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.volta/tools/image/node/18.17.0/bin/node
      npm: 9.6.7 - ~/.volta/tools/image/npm/9.6.7/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 29, 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-29 | ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: managed

**Comment by tomrom-pomelo** [comment]
As an additional wrinkle, I even tried adding the following to the app.json infoPlist property and still got the same error: https://github.com/expo/expo/blob/2254329167f5172e1da087c2339f0f5a62790a29/packages/%40expo/config-plugins/src/plugins/withIosBaseMods.ts#L39-L46

**Comment by wodin** [comment]
I am not sure how `NSAllowsArbitraryLoads: true` interacts with `NSExceptionDomains`.

The exception only seems to allow HTTP for `localhost`. You would presumably need to allow it for `exp.direct` and also allow subdomains.

Something like this, but without the `NSTemporaryExceptionMinimumTLSVersion` key:
https://stackoverflow.com/a/32560433/495319

Also, you should, if possible, do this in `app.config.js` only for development builds.

I don't know how `ios.infoPlist` will interact with Expo's `withIosBaseMods`, though. Try running this before and after your changes to see what happens:

```console
$ npx expo config -t introspect --json | jq .ios.infoPlist
```

**Comment by tomrom-pomelo** [comment]
Interesting, I’ll try that as a potential mitigation, though there certainly seems like a regression somewhere

**Comment by lawnguyen** [comment]
Also have this issue after upgrading to expo sdk 50.

**Comment by tomrom-pomelo** [comment]
Yep - adding 
```
ios: {
  infoPlist: {
      CFBundleAllowMixedLocalizations: true,
      NSAppTransportSecurity: {
        NSExceptionDomains: {
          'exp.direct': {
            NSIncludesSubdomains: true,
            NSExceptionAllowsInsecureHTTPLoads: true,
          },
        },
      },
    },
}
```
to my app.config.js did indeed work

**Comment by gabriel-moresco** [comment]
After upgrade to SDK 50 I'm having this problem to run with tunnel on Android. Could this happen due to this update?

![Screenshot_20240207_111549_Favorito](https://github.com/expo/expo/assets/45923448/f90342f2-ca78-4214-8580-782a4166694a)

**Comment by Charles-Johnson** [comment]
I have this issue as well but I am using `npx expo start -d --lan` to test my app on a real iPhone connected to the same WiFi network. Using `npx expo start -d --tunnel` gives me the error 
```
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
Starting Metro Bundler
CommandError: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
Check the Ngrok status page for outages: https://status.ngrok.com/
```

**Comment by wodin** [comment]
> I'm not sure how to configure `NSExceptionDomains` to cover LAN addresses

[The documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsexceptiondomains) says this:
> Use a DNS domain name, IP address, or range of IP addresses — In iOS 17, iPadOS 17, and macOS 14, you can use an IPv4 address, for example 192.168.42.63, or an IPv6 address, for example 2001:db8:12::34. You can also use a classless inter-domain routing (CIDR) range, for example 2001:db8:12::/48. For information about how ATS handles IP addresses, see [NSAllowsLocalNetworking](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking).

So you should be able to use something like this (depending on the details for your network):
`192.168.5.0/24`

**Comment by EnkhturBaina** [comment]
Try this :)
It's worked my expo project. app.json

"infoPlist": {
        "CFBundleAllowMixedLocalizations": true,
        "NSAppTransportSecurity": {
          "NSAllowsArbitraryLoads": true,
          "NSAllowsLocalNetworking": true,
          "NSExceptionDomains": {
            "xxx.xx.xx.xxx": {
              "NSIncludesSubdomains": true,
              "NSExceptionAllowsInsecureHTTPLoads": true
            }
          }
        }
      }

**Comment by tommyvn** [comment]
For anyone else hitting this issue, installing `expo-dev-client` fixed this without any of the workarounds mentioned above.

**Comment by Yuriy-Dobryi** [comment]
[This solution](https://discuss.codecademy.com/t/react-native-expo-app-unable-to-make-http-request-to-an-api-using-axios-after-build-but-works-perfectly-with-expo-go/822388/2) helped me, works on `Expo SDK 51.0.26`

```
"ios": {
    "infoPlist": {
      "NSAppTransportSecurity": { 
        "NSAllowsArbitraryLoads": true 
      }
    }
}
```

Note that: 
> There may be a problem with uploading to the Appstore with this set to true, so if you run into problems that might be it.
