### ISSUE TITLE
Missing "Open Snack " Button in Expo Camera ( Next ) Documentation

### ISSUE THREAD

**Issue by Harish-M-2003** [expo/expo#26576]
### Summary

The documentation for Expo Camera (Next) is lacking the "Open Snack" button, hindering users from testing the example using Expo Snack.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/camera-next/#usage

**Comment by amandeepmittal** [comment]
Hey @Harish-M-2003, we are still working on updating Snack to support SDK 50. The `expo-camera/next` was released with the SDK 50.

We'll track this internally, but I'm going to close it for now as we don't have an ETA right now.
