### ISSUE TITLE
ImagePicker quality option not working and storage alway increase 4Mb -> 7Mb (version 31.0.0, 30.0.0)

### ISSUE THREAD

**Issue by tamdao** [expo/expo#2657]
Hi there,

In version 31, I tried to use `ImagePicker` (`Android`) to let user capture the image. As I read the document, it have support an option called `quality`. This option value is from 0 to 1. I understand that 1 is maximum quality. But when I set the value from 0 to 1, I always received an image that had size from 4mb to 7mb. The size and quality of image did not reduce.

Is there anyone have the issue like me? Or I did it incorrectly?

BTW, I found another issue. When the user use camera to capture image (ImagePicker) the storage(app, cache) of the app alway increase 4Mb -> 7Mb

I have tried `FileSystem` to delete the file of the ImagePicker result. I can delete the file but the size of the storage alway increase

Snack url: https://snack.expo.io/ByI5m3mi7

*Storage before use ImagePicker*
![Storage before use ImagePicker](https://user-images.githubusercontent.com/3086267/48260182-132b0000-e44d-11e8-84ca-d052e7dc1f7b.jpg)

*Storage after use ImagePicker and capture an image*
![Storage after use ImagePicker and capture an image](https://user-images.githubusercontent.com/3086267/48260186-17571d80-e44d-11e8-9c51-9056c4d61c01.jpg)

**Comment by naviet2308** [comment]
I am currently facing this issue as well. Please help

**Comment by smalldarks** [comment]
Having the same problem!!!

**Comment by tamdao** [comment]
<img width="492" alt="a screenshot from real user" src="https://user-images.githubusercontent.com/3086267/48596891-8670cc80-e98d-11e8-9147-350c81a9b34c.png">

**Comment by tamdao** [comment]
@bbarthec, @Szymon20000 Could you help me take a look this issue? It's big issue with my client. Or Can you tell me how can build and test on my device? I will try to fix it

**Comment by Szymon20000** [comment]
I fixed the issue with the quality attribute. I will try to remove unnecessary caching later.

**Comment by XeCtvi** [comment]
Hi there,
Any progress here?

Thanks.

**Comment by sjchmiela** [comment]
Hey, sorry, I got caught up in other features and fixes, a [fixing pull request](https://github.com/expo/expo/pull/2750) is almost ready to be merged, it will definitely land in SDK32. 🙂

**Comment by tamdao** [comment]
Thanks @sjchmiela

**Comment by XeCtvi** [comment]
Good news, Thanks @sjchmiela

**Comment by tamdao** [comment]
@sjchmiela How about the SDK32?

**Comment by sjchmiela** [comment]
We have some idea when we think it should be released, but it's still too early to name any dates. A rather safe possible timespan would be "first half of December". 🙂

**Comment by sjchmiela** [comment]
Hm… I think you could:
- clone the repo,
- checkout to `sdk-31` branch,
- cherry-pick https://github.com/expo/expo/commit/d1aac6bfe0bfcf5c914e593408a01433b9aa6104 and https://github.com/expo/expo/commit/e1cdf8333aefcffa5c3575ac81992c889cfa9ac9 to `sdk-31`
- go to `tools`, run `yarn` there and then `gulp update-exponent-view --abi 31.0.0` (provided you have `gulp-cli` installed)
- this will update files in `expokit-npm-package` directory — this is the package that ends up in your ejected project as `expokit` and from which native libraries are pulled
- in your ejected project point `expokit` dependency with `file` or `link` to the `expokit-npm-package`, install the dependencies
- Android project should from now on use `expokit` with this issue fixed 🎉 
- when you confirm it works you could run `npm pack` in `expokit-npm-package` to create a `.tgz` of the package. Then, copy the archive to your ejected project and point `expokit` dependency to that archive.
- now you can delete the `expo` clone 🙂

**Comment by tamdao** [comment]
@sjchmiela Thanks for your help

**Comment by tamdao** [comment]
Hi @sjchmiela I have tried to follow your comment. But It's not working. I'm stuck at `go to tools, run yarn there and then gulp update-exponent-view --abi 31.0.0 (provided you have gulp-cli installed)`

I alway got the error bellow:
```
Running rm -rf /Users/tamdao/.m2/repository/com/facebook/react
Running ./gradlew :ReactAndroid:uploadArchives
[15:59:20] 'update-exponent-view' errored after 6.8 s
[15:59:20] Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/Users/tamdao/Documents/home/projects/expo/tools/node_modules/@exponent/spawn-async/build/spawnAsync.js:39:21)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
```
How can I resolve the issue? I research two days, But I can't fix it

**Comment by tamdao** [comment]
@sjchmiela Thanks for your help. I have resolved the issue with the flow bellow:

1. Add `NDK PATH`:
```
export ANDROID_SDK=/Users/<user>/Library/Android/sdk
export ANDROID_NDK=/Users/<user>/Library/Android/sdk/ndk-bundle
export PATH="$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$ANDROID_NDK"
```
2. Run `yarn` in `tools`, `tools-public` and `expokit-npm-package`
3. Run `gulp update-exponent-view --abi 31.0.0` in `tools` folder
4. Run `npm pack` in `expokit-npm-package `
