### ISSUE TITLE
[SDK 50]: `compilerOptions.baseUrl` causes tamagui to not work once migrating from SDK 49.

### ISSUE THREAD

**Issue by reimertz** [expo/expo#26580]
### Minimal reproducible example

[Repository](https://github.com/reimertz/expo-router-baseurl-error)

### Summary

I upgraded our monorepo from SDK 49 to SDK 50 now when it's out of beta.

I followed the migration steps carefully, but it seems there might be a bug related to anyone utilizing the experimental path aliases feature where you had to set `baseUrl` for the path aliases to work properly.

With SDK 50 and this feature now being on by default, there seems to be an issue how imports are resolved causing some dependencies to not work. I saw this with [tamagui](github.com/tamagui/tamagui) throwing `createTamagui is not a function`.

Not sure if this is is a bug or known behavior now when this feature is on by default. If so, maybe a mention in the migration guide / Path Alias documentation might be helpful?

### Temporary Fix
By removing `baseUrl` I was able to get the project to run again. 

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^10.0.1 => 10.0.1
      expo: ^50.0.2 => 50.0.2
      expo-router: ^3.4.4 => 3.4.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.10 => 0.19.10
    Expo Workflow: bare
    ```

**Comment by NilsBaumgartner1994** [comment]
Could be related to: https://github.com/expo/expo/issues/26565

**Comment by Rahat47** [comment]
I am also facing the same issue. upgraded from 49 to 50 with path aliases. The app broke.

so I updated the `tsconfig.json` file to remove the path aliases and remove it from `app.config` as well. 
now the app runs smoothly. 

This issue needs a fix.

**Comment by NilsBaumgartner1994** [comment]
@Rahat47 could you post your solution please?

**Comment by Rahat47** [comment]
@NilsBaumgartner1994  

not an ideal solution, but I just did the following:

1.  removed ```experiments: {
		tsconfigPaths: true,
	},``` from app.config.ts 
2. removed the `baseUrl` property from `tsconfig.json`.
3. updated imports in the code (if necessary).
4. restarted expo with cache clearing.

It started to work again.

**Comment by Rahat47** [comment]
Nope, 
This is what my tsconfig file looks now

```
{
	"extends": "expo/tsconfig.base",
	"compilerOptions": {
		"strict": true,
		"paths": {
			"@components/*": ["./src/components/*"],
			"@/*": ["./src/*"]
		}
	},
	"include": ["**/*.ts", "**/*.tsx", "tamagui.config.ts"]
}
```

**Comment by reimertz** [comment]
`tsconfigPaths` is on by default now so my guess is that specifying `baseUrl` breaks something else.

**Comment by Rahat47** [comment]
All thanks to you. @reimertz  
It was your finding on Discord that made me do these checks. At least the app works now. 
But can't define any `baseUrl`

**Comment by EvanBacon** [comment]
@NilsBaumgartner1994 the baseUrl property for deploying websites to subdomains is different to the `tsconfig.json` baseUrl property that's used for creating import aliases.

**Comment by EvanBacon** [comment]
In SDK 50, the baseUrl property is now more complaint with TypeScript according to the docs https://www.typescriptlang.org/tsconfig#baseUrl originally it was modeled more after a Vite plugin I found / Next.js (both were incorrect and caused mismatched behavior between the bundler and vs code). I imagine tamagui makes similar assumptions.

In SDK 50, the `baseUrl` must be defined, it no longer defaults to ".". Also if the `paths` are matched and do not have a resolution, then `baseUrl` is skipped. These are the main changes we made in SDK 50 https://github.com/expo/expo/pull/25510

**Comment by jayzes** [comment]
I ran into this same issue when upgrading to SDK 50 in a monorepo app. Setting my `compilerOptions` to the following seemed to fix it, without readjusting all of my imports:

```js
    "baseUrl": ".",
    "paths": {
      "*": ["/*"]
    },
```

I did still need the metro configuration mentioned in https://docs.expo.dev/guides/monorepos/#modify-the-metro-config, but  removed the `tsconfigPaths` setting from my app config.

**Comment by Darhagonable** [comment]
@EvanBacon 

My tsconfig.json looks like this:
```json
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": [
      "DOM",
      "DOM.Iterable",
      "ESNext"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "target": "ESNext"
  },
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ]
}
```

baseUrl is set to be the `src` folder.
I can now import from `components/MyComponent` and Typescript says its fine. in SDK 49 Expo would also accept this but since updating to SDK 50 Typescript still doesn't complain but Expo fails to find "components".

**Comment by natew** [comment]
@reimertz is this still an issue? I have the Expo Router template and we do see an issue with Metro not finding a css file that's generated during the build, but other than that things work. I'm not using the experimental exports though.

I'm pretty sure Tamagui isn't the source of the bug though as it's just a library, we don't touch or have anything to do with baseUrl/typescript stuff.

All our metro plugin does is:

1. Adds `withCssInterop` from `react-native-css-interop`
2. Adds a Metro transformer that, that maybe could have an error, but I'd imagine it'd have a clear message as it'd come during the compilation step and point to a file, whereas this looks like some sort of runtime thing.

If anyone wants to set up a fork of the `npm create tamagui` expo router template with that replicated would be useful.

**Comment by reimertz** [comment]
@natew Hi there. I just initiated a new project using `npm create tamagui` and added aliases and it stopped working. 

The only way to get it to work was to remove `baseUrl` in `tsconfig.json`. 

Repository can be seen here: https://github.com/reimertz/expo-router-baseurl-error-v2

**Comment by natew** [comment]
I've found the solution somewhat, this is actually caused by Metro resolving css incorrectly I believe.

The problem is we generate a `tamagui.css` in the root folder. What happens is the expo metro config with `isCSSEnabled` true will actually resolve to `tamagui.css` when you `import { View } from 'tamagui'` incorrectly.

Likely it needs some logic to prefer a node module over a css file, which seems right. For now change your `tamagui.css` output to be a different name and it should fix.

Confusing error! Took me a minute to isolate it.

@EvanBacon I can make our metro plugin change the resolution in this specific case, but I think this is probably a Metro footgun that could be fixed upstream.

**Comment by xixixao** [comment]
This issues seems to be resolved and should be closed (there's no `baseUrl` by default).
