### ISSUE TITLE
Using Expo over VPN

### ISSUE THREAD

**Issue by triplea24** [expo/expo#2658]
If you are facing difficulties on accessing Expo over VPN check out my solutions written here:

https://medium.com/@triplea1373/react-native-and-nat-problem-4b53462cd0b9

**Comment by esamelson** [comment]
Thanks for writing this up @triplea24 ! I hope this guide will help other people running into similar issues.

**Comment by FiberJW** [comment]
This seems to be resolved, so I’ll close this for now. Thanks for the contribution :)
