### ISSUE TITLE
Not able to navigate back from a modal using router.replace

### ISSUE THREAD

**Issue by JClackett** [expo/expo#26590]
### Minimal reproducible example

https://github.com/JClackett/expo-50-modal

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

On expo-router v2, I could navigate back from a modal using router.replace which allowed me to pass params back from modals. Now it seems on expo-router v3 router.replace does some funky stuff where it pushes a new modal on top but then theres this weird flash of params on the original underlying screen which disappears if I use a gesture to close.

I want to be able to open a modal to select some values and then using params + useGlobalSearchParams, pass that back to a previous screen/modal.

Is there another way to do this?

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.18.2 - /var/folders/dt/wxhpvnj560xc4_qw5nnbsqw40000gn/T/fnm_multishells/26788_1705923489509/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /var/folders/dt/wxhpvnj560xc4_qw5nnbsqw40000gn/T/fnm_multishells/26788_1705923489509/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.1 => 50.0.2 
      expo-router: ~3.4.1 => 3.4.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 6.1.0
    Expo Workflow: managed

**Comment by JClackett** [comment]
Example just uses the latest with-router-tailwind template

**Comment by NilsBaumgartner1994** [comment]
are you using baseUrl ?

**Comment by NilsBaumgartner1994** [comment]
@JClackett 

As described in this issue: https://github.com/expo/expo/issues/26565

Are you setting in app.json

```
    "experiments": {
      "typedRoutes": true,
      "baseUrl": "/your-base-url"
    },
```

**Comment by JClackett** [comment]
Hmm that doesnt help me I dont think, but Ive now just realised that I should be using router.navigate(), this pops back but also sends the params!
