### ISSUE TITLE
PanResponder not working in web

### ISSUE THREAD

**Issue by bobOnGitHub** [expo/expo#26598]
### Minimal reproducible example

https://snack.expo.dev/5qD15gRn6VMguy3ed0ild

### Summary

Possibly a React Native issue rather than an Expo issue but their github says log the bug here if using Expo.

The code in the minimal reproducible example is taken from [the official react native PanResponder documentation](https://reactnative.dev/docs/panresponder) ( I had to save as a new snack to get a url )

If you run it under Android it does what it's supposed to - the gesture only starts if you begin inside the square. If you run on Web the gesture starts regardless where you click - i.e. it starts if you begin anywhere on the screen including outside the square - which it shouldn't.

I came across [this stackOverflow issue](https://stackoverflow.com/q/69109350/4779501) when I started looking into it so the issue's been around for a while.

### Environment

snack.expo.dev SDK 49

**Comment by brentvatne** [comment]
hi there! this API is provided by react-native-web: https://github.com/necolas/react-native-web

in general I would recommend avoiding PanResponder, and using react-native-gesture-handler instead

**Comment by bobOnGitHub** [comment]
Thanks for the steer, I'll raise it with react-native-web. Tbh it's not critical as project not intended for web.

I did try react-native-gesture-handler (along with reanimated) but hit a brick wall on issues with layout size changes. PanResponder and Animated worked so I'm sticking with those. Besides, I'd prefer not to be using 3rd party libs if possible - the whole eco system (and pretty much the world of web based development, if not most of IT) feels like a game of jenga in a crack house at this point.
