### ISSUE TITLE
[docs] `setSession` is deprecated but it's used in OAuth login example on Auth Session section

### ISSUE THREAD

**Issue by Sboonny** [expo/expo#26595]
### Summary

I have used the example in `.tsx` file, and got warning that `setSession` is deprecated. After some investigation, I found that the recommend prop to use instead of `setSession` is [`setActive`](https://clerk-docs-git-prettier-fixes.clerkpreview.com/hooks/authentication/use-sign-in#:~:text=should%20be%20used%20over%20setSession), is it possible to change the example to `setActive`?

### Link to the related docs page

https://clerk-docs-git-prettier-fixes.clerkpreview.com/quickstarts/expo#oauth-login

### Anything else?

it would be awesome to change the type to hint about `setActive` too.
![image](https://github.com/expo/expo/assets/88248797/7f6b3239-785d-4214-a5bd-0478a6942af6)

If this is an actual issue and it's open to contribution, I am happy to make a PR.

**Comment by brentvatne** [comment]
hi there!

we do not maintain the clerk documentation. you may want to create an issue on their repository.
