### ISSUE TITLE
Update to SDK 49 ExpoMetroConfig.loadAsync ERROR

### ISSUE THREAD

**Issue by daniimd** [expo/expo#26593]
### Summary

I just updated SDK 48 to SDK 49 following all the steps in the documentation: 
```
npm i -g eas-cli
npm install expo@^49.0.0
npx expo install --fix
```

I `updated react native` and installed the `@expo/metro-config` package
However, I'm still having problems starting the project with `npx expo start`

```
TypeError: ExpoMetroConfig.loadAsync is not a function
TypeError: ExpoMetroConfig.loadAsync is not a function
    at loadMetroConfigAsync (\coopercarga-app\node_modules\@expo\cli\build\src\start\server\metro\instantiateMetro.js:47:40)
    at Object.instantiateMetroAsync (\coopercarga-app\node_modules\@expo\cli\build\src\start\server\metro\instantiateMetro.js:75:63)
    at MetroBundlerDevServer.startImplementationAsync (\coopercarga-app\node_modules\@expo\cli\build\src\start\server\metro\MetroBundlerDevServer.js:203:95)
    at async MetroBundlerDevServer.startAsync (\coopercarga-app\node_modules\@expo\cli\build\src\start\server\BundlerDevServer.js:88:24)
    at async DevServerManager.startAsync (\coopercarga-app\node_modules\@expo\cli\build\src\start\server\DevServerManager.js:162:13)
    at async startAsync (\coopercarga-app\node_modules\@expo\cli\build\src\start\startAsync.js:125:5)
```

package.json: 
```
 "dependencies": {
    "@expo-google-fonts/lobster": "^0.2.2",
    "@expo-google-fonts/roboto": "^0.2.2",
    "@expo-google-fonts/ubuntu": "^0.2.2",
    "@expo/metro-config": "^0.17.3",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/material-top-tabs": "^6.5.2",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "axios": "^0.24.0",
    "date-fns": "^2.28.0",
    "expo": "^49.0.0",
    "expo-av": "~13.4.1",
    "expo-barcode-scanner": "~12.5.3",
    "expo-camera": "~13.4.4",
    "expo-checkbox": "~2.4.0",
    "expo-fast-image": "^1.1.3",
    "expo-file-system": "~15.4.5",
    "expo-image-manipulator": "~11.3.0",
    "expo-linear-gradient": "~12.3.0",
    "expo-location": "~16.1.0",
    "expo-navigation-bar": "~2.3.0",
    "expo-network": "~5.4.0",
    "expo-notifications": "~0.20.1",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-updates": "~0.18.19",
    "moment": "^2.29.1",
    "onesignal-expo-plugin": "^1.3.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.6",
    "react-native-barcode-mask": "^1.2.4",
    "react-native-blink-view": "^0.0.6",
    "react-native-countdown-circle-timer": "^3.0.9",
    "react-native-countdown-component": "^2.7.1",
    "react-native-countdown-fixed": "^2.7.1",
    "react-native-curved-bottom-bar": "^2.1.4",
    "react-native-datepicker": "^1.7.2",
    "react-native-dropdown-picker": "5.4.0",
    "react-native-flash-message": "^0.4.2",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.7.1",
    "react-native-masked-text": "^1.13.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal-filter-picker": "^2.1.0",
    "react-native-onesignal": "^4.5.2",
    "react-native-pager-view": "6.2.0",
    "react-native-paper": "^4.11.2",
    "react-native-popup-menu": "^0.15.12",
    "react-native-ratings": "^8.1.0",
    "react-native-recaptcha-that-works": "^1.3.1",
    "react-native-root-toast": "^3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-searchable-dropdown": "^1.1.3",
    "react-native-searchable-picker": "^1.0.5",
    "react-native-shadow-2": "^7.0.6",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-super-grid": "^4.2.0",
    "react-native-svg": "13.9.0",
    "react-native-tab-view": "^3.3.4",
    "react-native-vector-icons": "^9.0.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.2.2",
    "react-native-youtube-iframe": "^2.2.2",
    "reactn": "^2.2.7"
  },
```

metro.config.js: 
```
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

module.exports = defaultConfig;
```

Can someone help me please?

### What platform(s) does this occur on?

Android

### SDK Version

49

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-32 | Google Play Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
    npmPackages:
      @expo/metro-config: ^0.17.3 => 0.17.3
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: bare
```

### Minimal reproducible example

> update sdk 49 from sdk 48
> update react native to version 0.72.6
> `npm i @expo/metro-config`
> start the project with `npx expo start`
> error `ExpoMetroConfig.loadAsync is not a function`

**Comment by brandonhmaciel** [comment]
same problem here

**Comment by ljlinen** [comment]
Also getting this on a new project i started yesterday

**Comment by andrconstruction** [comment]
the same ( upgraded to 50 )

**Comment by ljlinen** [comment]
so i was able to  fix my new project by changing its version back to a previous working version, which for me was: "expo": "~49.0.15"

just went into my package.json and changed the expo version and then run the command 'npm install'

**Comment by andrconstruction** [comment]
> ~49.0.15

On upgrade previous version not working

**Comment by zavex** [comment]
Same issue over here after 

1. upgrade expo from 48 to 49
2. run `npm i @expo/metro-config`
3. run `npm i @expo/config`
4. run `npx expo customize metro.config.js`

**Comment by brentvatne** [comment]
please share the result of `npx expo-doctor@latest`

**Comment by zavex** [comment]
> please share the result of `npx expo-doctor@latest`


```
PS C:\Users\Usuario\react\kuubMovil\kuubNative> npx expo-doctor@latest
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@7.8.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/metro-config@~0.10.0
Found invalid:
  @expo/metro-config@0.17.3
  (for more info, run: npm why @expo/metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Some dependencies are incompatible with the installed expo version:
  @expo/config@8.5.4 - expected version: ~8.1.1
  @expo/metro-config@0.17.3 - expected version: ~0.10.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

```

So after running following commands now its working fine for me 

```
npm install @expo/config@8.1.1
npm install @expo/metro-config@0.10.0
```

Thanks

**Comment by JoezerSmaniotto** [comment]
I updated my skd from version 48 to version 49, but it is generating a very strange address in "Metro waiting on" my address is like "Metro waiting on exp+name-project-v2://expo-development-client/?url =http%3A%2F%2F192.167.5.90%3A8081" before it was in this pattern "exp://192.178.8.164:19000", after this SDK update the project does not show the changes when I run "npx expo start" in "develpmenet servers", is anyone experiencing this?

**Comment by dayan2222** [comment]
> > please share the result of `npx expo-doctor@latest`
> 
> ```
> PS C:\Users\Usuario\react\kuubMovil\kuubNative> npx expo-doctor@latest
> WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.
> 
> ✔ Check Expo config for common issues
> ✔ Check package.json for common issues
> ✔ Check dependencies for packages that should not be installed directly
> ✔ Check for common project setup issues
> ✔ Check npm/ yarn versions
> ✔ Check Expo config (app.json/ app.config.js) schema
> ✔ Check that native modules do not use incompatible support packages
> ✔ Check for legacy global CLI installed locally
> ✖ Check that packages match versions required by installed Expo SDK
> ✖ Check that native modules use compatible support package versions for installed Expo SDK
> 
> Detailed check results:
> 
> Expected package @expo/config-plugins@~7.2.2
> Found invalid:
>   @expo/config-plugins@7.8.4
>   (for more info, run: npm why @expo/config-plugins)
> Expected package @expo/metro-config@~0.10.0
> Found invalid:
>   @expo/metro-config@0.17.3
>   (for more info, run: npm why @expo/metro-config)
> Advice: Upgrade dependencies that are using the invalid package versions.
> 
> Some dependencies are incompatible with the installed expo version:
>   @expo/config@8.5.4 - expected version: ~8.1.1
>   @expo/metro-config@0.17.3 - expected version: ~0.10.0
> Your project may not work correctly until you install the correct versions of the packages.
> Fix with: npx expo install --fix
> Found outdated dependencies
> Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
> 
> One or more checks failed, indicating possible issues with the project.
> ```
> 
> So after running following commands now its working fine for me
> 
> ```
> npm install @expo/config@8.1.1
> npm install @expo/metro-config@0.10.0
> ```
> 
> Thanks

This Thing Work well for me.

**Comment by brentvatne** [comment]
you do not need to install `@expo/metro-config` or `@expo/config` directly in your project dependencies, they are installed automatically with the correct version by the `expo` package. you can import them through the expo package via `import x from 'expo/metro-config` or `import x from 'expo/config'`;

unless you have a very good reason and you know what you are doing, do not install those dependencies directly
