### ISSUE TITLE
react-native-svg does not load from uri

### ISSUE THREAD

**Issue by myou11** [expo/expo#26603]
### Minimal reproducible example

https://snack.expo.dev/Ac12MglTEWDhT-fN_eWLc

### Summary

`<SvgUri>` or any other Svg component based on loading a uri/xml is not working. The errors that show up in the console are in the form:
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
```
The SVG does load on mobile (ios).

I have tried using just the `<Svg>` component and that works, but I need to load SVGs from the web.

Here is a [Repro repo](https://github.com/myou11/react-native-svg-expo-error) on Expo 50 as well.

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/maxwell.you/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: bare
```

**Comment by brentvatne** [comment]
re: snack example -- this is a known issue with react-native-svg/snack: #26263

re: repro that you shared to clone - i suspect SvgUri is not implemented for web, i don't see it exported here: https://github.com/software-mansion/react-native-svg/blob/main/src/ReactNativeSVG.web.ts - you can create an issue on that repo.

it does however work on native:
<img width="537" alt="image" src="https://github.com/expo/expo/assets/90494/2ca32bd2-5898-4d09-99b3-886e406185bc">

**Comment by myou11** [comment]
After some more research, I figured out how to correctly render SVGs for both mobile and web. The main problem was my misunderstanding that react-native-svg was a universal solution for react native on both mobile and web. But as you can see in [this discussion](https://github.com/software-mansion/react-native-svg/issues/1279), you need to choose a different approach for web.

For me, I chose to go the [platform-specific extensions](https://docs.expo.dev/router/advanced/platform-specific-modules/#platform-specific-extensions) route. I just made a `.web.tsx` version of my component that uses an `<img src={urlToSvg} />` and now I can display SVGs properly on both native and web. The regular `.tsx` file is using react-native-svg still.

Just wanted to post this for anyone else having trouble with SVGs in their mobile and web React Native project
