### ISSUE TITLE
[EXPO 50] [EAS] EAS Update crashes after upgrade to expo 50

### ISSUE THREAD

**Issue by Amurmurmur** [expo/expo#26601]
### Minimal reproducible example

https://github.com/Amurmurmur/expo-router

### Summary

After an upgrade to EXPO 50, starting seeing this error bellow.
Using: 
```
eas update --dev --auto
```
To publish an update.
eas update outputs this:
```
[expo-cli] App exported to: dist
✔ Exported bundle(s)
✔ Uploaded 2 app bundles
✔ Uploading assets skipped - no new assets found
ℹ 52 iOS assets, 52 Android assets (maximum: 2000 total per update). Learn more about asset limits.
✔ Published!
```
And a link
Downgrading to EXPO 49 solves the issue 
![image](https://github.com/expo/expo/assets/8608333/baba25f4-9856-4315-861a-cef154a4994c)

On Android:
![image](https://github.com/expo/expo/assets/8608333/7b1e9691-734d-4d7c-81e3-8eb2390b26da)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.2 => 50.0.2 
      expo-router: ~3.4.4 => 3.4.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.10 => 0.19.10 
    Expo Workflow: managed

**Comment by brentvatne** [comment]
you need to load the update in a dev build for sdk 50, which includes the compatible hermes version

**Comment by brentvatne** [comment]
- please make the repo more minimal, only the least amount of code necessary to reproduce
- share the output of `npx expo-doctor@latest`
