### ISSUE TITLE
[SDK 50] Failing to bundle assets, @react-native/assets-registry not found

### ISSUE THREAD

**Issue by gretzky** [expo/expo#26606]
### Minimal reproducible example

https://github.com/gretzky/expo-asset-repro

### Summary

When building an app locally, or running `expo export`, it's expected that assets (images, fonts, etc.) are bundled automatically without extra configuration required.

Currently, when running either `expo export` or `eas build --local`, the following error is thrown:

```
Error: Unable to resolve module @react-native/assets-registry/registry from [dir] @react-native/assets-registry/registry could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  node_modules
  ../../node_modules
```

The reproducible example is in a monorepo, based off of the example @byCedric. We upgraded our app within our monorepo to SDK 50 when it was in beta, `50.0.0-preview.7` and did not see this error and had no issues building/exporting. Upgrading to `50.0.2` from preview-7 is when this error started happening.

Installing `@react-native/assets-registry` directly results in exports and builds succeeding, but once the app loads, assets still cannot be found or loaded -- `Errror: Module [number] not found in the assets registry.` is thrown.

This error is interesting, as it has been pretty flaky so far. On first setup of the reproducible example, it bundled successfully, but on build/subsequent bundle, it fails. This could just be environmental / caching -- I have been at this all day 😅 

Potentially relates to #26474, #26195 
cc @wschurman 

Thank you!

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~10.0.0 => 10.0.0
      expo: ~50.0.2 => 50.0.2
      expo-router: ~3.4.4 => 3.4.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.6
    Expo Workflow: managed

**Comment by wschurman** [comment]
Thanks for reporting! Assigning to @byCedric to investigate as it may be related to the monorepo setup.

**Comment by byCedric** [comment]
Hi @gretzky! Thanks for reporting this issue. Unfortunately, there are still a few issues left to fix in `@expo/cli` side to make Expo fully compatible with isolated modules (for both pnpm and npm).

We are slowly trying to flush out these incompatibilities. In the meantime, you have two options here.

1. Add [the **.npmrc** file](https://github.com/byCedric/expo-monorepo-example/blob/main/.npmrc) with `node-linker=hoisted` ([docs](https://pnpm.io/npmrc#node-linker))
  ![image](https://github.com/expo/expo/assets/1203991/2f287b6f-d170-4420-a85e-456676a4082c)
2. If you are looking for a fast package manager and are not tied to pnpm, try out Bun. It's faster than pnpm, even in a monorepo, but installs a "normal" `node_modules` folder structure. ([see this tweet](https://twitter.com/theFoldster/status/1749189239080632660))

Hope it helps!

**Comment by gretzky** [comment]
Hi @byCedric! Thanks for your reply. I've already tried re-adding that to our npmrc file (we had it beforehand) and blowing away caches, but the same error persists 😅

**Comment by gretzky** [comment]
Moving to bun solves the issue! Pretty strange how adding hoisting back in with pnpm didn't cut it, but my knowledge of how bun differs is slim.

Thank you for your help! I will update my repro repo (lol) to use bun -- @byCedric I really have enjoyed your monorepo example and reference it a lot 🙏

**Comment by suhaotian** [comment]
After update expo to 50 from 49, 

I have the same error: `Unable to resolve module...`

It's a monorepo of pnpm workspace, same code with expo sdk 49 is ok
```
  - Exporting...
  [expo-cli] env: load .env
  - Exporting...
  [expo-cli] env: export EXPO_PUBLIC_API_URL
  - Exporting...
  [expo-cli] Starting Metro Bundler
  - Exporting...
  [expo-cli] Android Bundling failed 131025ms (index.js)
  - Exporting...
  [expo-cli] 
  - Exporting...
  [expo-cli] Error: Unable to resolve module fe-sdk/lib/user-api-hooks from
```

**Comment by fidestechnology** [comment]
Hi. We ran into the same issue and would like to stick to pnpm. Any working solution so far?

**Comment by kuldip-simform** [comment]
I am facing this same issue.
Any local assets are not showing in app.

**Comment by kasvith** [comment]
im facing this issue with following repo https://github.com/adrianhajdin/aora.git

it seems assets are not loaded

**Comment by mahesh123pandav** [comment]
I am facing this same issue also.
Any local assets are not showing in app, assets loaded in web but not in app.

**Comment by Lenoux01** [comment]
im having the same issue event though i use bun with a monorepo setup

**Comment by lairacham** [comment]
This worked for me: `public-hoist-pattern[]=@react-native/assets-registry` in the `.npmrc` file instead of using `node-linker=hoisted`. This ensures the rest of the dependencies are still deeply linked except for @react-native/assets-registry.
