### ISSUE TITLE
expo-image web on 50 nativeViewRef error

### ISSUE THREAD

**Issue by georgevicbell** [expo/expo#26611]
### Minimal reproducible example

https://github.com/denniske/skd50-expo-image-repro

### Summary

<img width="1496" alt="image" src="https://github.com/expo/expo/assets/4380159/c024d04d-e82f-4a18-883f-b4699443a80a">

expo-image no longer works on web with following error:

React does not recognize the nativeViewRef prop on a DOM element.

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: Linux 6.6 Gentoo Linux
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.9.0 - /usr/bin/node
Yarn: 4.0.2 - /usr/bin/yarn
npm: 10.1.0 - /usr/bin/npm
Watchman: 2023.06.19.00 - /usr/bin/watchman
npmPackages:
expo: ^50.0.0-preview.7 => 50.0.0-preview.7
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.73.1 => 0.73.1
react-native-web: ~0.19.6 => 0.19.10
Expo Workflow: managed

**Comment by georgevicbell** [comment]
Note I am getting this in the most recent sdk 50...
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - /usr/local/bin/node
      npm: 10.3.0 - ~/.npm-global/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1 
      expo: ^50.0.2 => 50.0.2 
      expo-router: ~3.4.4 => 3.4.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: managed

**Comment by ecto** [comment]
I'm also running into this. It looks like this might be addressed by https://github.com/expo/expo/pull/25922

**Comment by georgevicbell** [comment]
Seems to be resolved...
