### ISSUE TITLE
Expo Router Testing: how to specify a layout component?

### ISSUE THREAD

**Issue by JorensM** [expo/expo#26616]
### Minimal reproducible example

https://gist.github.com/JorensM/5eab0851321019a7156a2fbb0fce7569

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

So I'm trying to write tests for my routes. My tests require to use Context Providers that are defined in my `_layout.tsx`. Expo router's testing function `renderRouter` doesn't seem to be rendering my `_layout.tsx` by default, so I'm trying to add it, to no avail so far.

With the code shared in the gist, this is the error I'm receiving:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

though my exports are all good.

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 30.0.2, 30.0.3
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0
      expo: ~49.0.15 => 49.0.21
      expo-router: ^2.0.0 => 2.0.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
The error is reporting there is an issue with an import or how you're rendering a component. Without any additional context we cannot help you troubleshoot this further.

**Comment by JorensM** [comment]
> The error is reporting there is an issue with an import or how you're rendering a component. Without any additional context we cannot help you troubleshoot this further.

After investigating it appears that I'm getting an `useState is undefined` error in the layout component although `useState` has been imported. I think that `jest` or `testing-library` are having trouble finding the `react` module. I know this is besides the point but do you have any idea why this might be happening? Thanks

**Comment by JorensM** [comment]
@marklawlor 

This is what my `_layout` looks like:

```
// Core
import { useEffect, useState } from 'react';
import { router, usePathname } from 'expo-router';
import Toast from 'react-native-toast-message';
import { View } from 'react-native';

// Components
import CustomDrawer from '#components/layout/CustomDrawer';

// Hooks
import useAuth from '#hooks/useAuth';

// Types
import { User } from '#types/User';

// State
import AuthContext from '#state/AuthContext';

// Constants
import toast_config from '#constants/toast_config';

// Misc
import { isGuestRoute, isUserRoute } from '#misc/route_utils';
import { StripeProvider } from '#misc/stripe';
import { toastInfo } from '#misc/toast';
import { STRIPE_PUBLISHABLE_KEY } from '#constants/env';

// import Layout from '#components/layout/Layout';

// export const unstable_settings = {
//   // Ensure any route can link back to `/`
//   initialRouteName: '/login',
// };

/**
 * Layout component that will be shown on each route
 */
export default function Layout() {

  // Auth context
  const [ user, setUser ] = useState<User | null>(null);

  // hooks
  const auth = useAuth();
  const pathname = usePathname();

  /**
   * Validates whether user/guest is allowed to be on a given route, and redirects
   * if not.
   */
  const validateSession = async () => {
    const user = await auth.fetchUser();
    let _pathname = pathname.substring(1);
    _pathname = _pathname == '' ? 'index' : _pathname;
    if (!user && isUserRoute(_pathname)) {
      console.log('Your session has expired, please log in');
      router.replace('/');
      toastInfo('Your session has expired', 'Please log in');
    } else if (user && isGuestRoute(_pathname)) {
      console.log('Already logged in, redirecting');
      router.replace('/feed');
    }
  }
  

  useEffect(() => {
    validateSession();

    const timeout = setTimeout(async () => {
      validateSession();
    }, 10 * 1000);

    return () => {
      clearTimeout(timeout);
    }
  }, [])

  useEffect(() => {
    validateSession();
  }, [pathname])

  return (
    <AuthContext.Provider 
        value={{
            user,
            setUser
        }}
    >
        <StripeProvider
            publishableKey={STRIPE_PUBLISHABLE_KEY}
        >
            <CustomDrawer />
            <Toast config={toast_config}/>
        </StripeProvider>
    </AuthContext.Provider>
  );
}
```

**Comment by marklawlor** [comment]
> > The error is reporting there is an issue with an import or how you're rendering a component. Without any additional context we cannot help you troubleshoot this further.
> 
> After investigating it appears that I'm getting an `useState is undefined` error in the layout component although `useState` has been imported. I think that `jest` or `testing-library` are having trouble finding the `react` module. I know this is besides the point but do you have any idea why this might be happening? Thanks

Ok, so we have isolated the issue to your dependencies. Which means it's not a problem with your layout code. We will need to see your entire repo to reproduce the issue

**Comment by JorensM** [comment]
Sure, here it is: https://github.com/JorensM/local-jobs

The `local-jobs` folder is the old version of the app, so ignore that, the `app` folder is the new one that uses Expo Router.

**Comment by Aycom366** [comment]
Have you gotten this to work @JorensM ?

**Comment by JorensM** [comment]
@Aycom366 I believe I solved this by passing the providers into expo router's test function's `wrapperComponent` arg. Not sure if that's what the arg was called but it should be something similar.
