### ISSUE TITLE
[metro] Metro config option requireCycleIgnorePatterns is not respected

### ISSUE THREAD

**Issue by hdwatts** [expo/expo#26613]
### Minimal reproducible example

https://github.com/hdwatts/expo-recreation-playground/tree/require-cycle-example

### Summary

I use a library that has a cyclical import, which leads to constant log pollution alerting me to refactor the imports.

Metro has support for a `requireCycleIgnorePatterns` option, which is `node_modules` by default. Unfortunately, it appears as if that configuration option gets swallowed up by expo somewhere.

In the example repo, I have created a cyclical import and access it on both an Expo Router API route and on the front end. In both cases, my very lenient metro config option is ignored:

```js
config.resolver = {
  ...config.resolver,
  requireCycleIgnorePatterns: [
    /(^|\/|\\)node_modules($|\/|\\)/,
    /.*circular.*/,
  ],
};
```

`Require cycle: components/circular/backend/circle1.ts -> components/circular/backend/circle3.ts -> components/circular/backend/circle2.ts -> components/circular/backend/circle1.ts`

`Require cycle: components/circular/frontend/circle1.ts -> components/circular/frontend/circle3.ts -> components/circular/frontend/circle2.ts -> components/circular/frontend/circle1.ts`

This appears to be **web** only, and does not occur on iOS.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.1 - ~/Library/Caches/fnm_multishells/4396_1705978127572/bin/node
      npm: 10.1.0 - ~/Library/Caches/fnm_multishells/4396_1705978127572/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2
      expo-router: ~3.4.3 => 3.4.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 5.7.0
    Expo Workflow: managed

**Comment by Kudo** [comment]
hi there! i tried your repro but it doesn't show the require cycle error for me.
```sh
$ git clone https://github.com/hdwatts/expo-recreation-playground.git
$ cd expo-recreation-playground
$ git checkout require-cycle-example
$ bun i --frozen-lockfile
$ npx expo start -i
```

after removing [the line](https://github.com/hdwatts/expo-recreation-playground/blob/0c30158385088ba5b039f5533296cfceaa457ba0/metro.config.js#L14), the error starts to appear. do i miss anything from the repro?

**Comment by hdwatts** [comment]
> Do i miss anything from the repro?

Good call out - my repro was using web not iOS.

I can confirm that on iOS the logs do not appear, but on **web** they do.

<img width="1317" alt="image" src="https://github.com/expo/expo/assets/16158417/86225928-1f66-44b2-850c-e6e1a570c592">

**Comment by Kudo** [comment]
i can confirm the issue and accept the issue. also, let us keep it as lower priority. the error seems to be coming from the api-routes server renderer that we keep working.

**Comment by javascripter** [comment]
I'm using the below pathc-package patch for now.

```
diff --git a/node_modules/metro-runtime/src/polyfills/require.js b/node_modules/metro-runtime/src/polyfills/require.js
index ce67cb4..18edd64 100644
--- a/node_modules/metro-runtime/src/polyfills/require.js
+++ b/node_modules/metro-runtime/src/polyfills/require.js
@@ -131,7 +131,9 @@ function metroRequire(moduleId) {
 // `requireCycleIgnorePatterns` configuration.
 function shouldPrintRequireCycle(modules) {
   const regExps =
-    global[__METRO_GLOBAL_PREFIX__ + "__requireCycleIgnorePatterns"];
+    global[__METRO_GLOBAL_PREFIX__ + "__requireCycleIgnorePatterns"] ||
+    // HACK: Expo SSR mode doesn't have this global. Fall back to the default.
+    [/(^|\/|\\)node_modules($|\/|\\)/];
   if (!Array.isArray(regExps)) {
     return true;
   }
```

In this function, 
```javascript
function shouldPrintRequireCycle(modules) {
  const regExps =
    global[__METRO_GLOBAL_PREFIX__ + "__requireCycleIgnorePatterns"]
```
the value does not exist in the `global` object or `globalThis` object. If you eval it like this there, the value exists, so I guess prelude code is injected in a wrong place/environment or something.
```javascript
eval(__METRO_GLOBAL_PREFIX__ + "__requireCycleIgnorePatterns"])
```

**Comment by SleeplessByte** [comment]
This is an issue when not using `api-routes`, but regular `expo-router` on web.

Workaround by https://github.com/expo/expo/issues/26613#issuecomment-1941650055 works.

**Comment by jancbeck** [comment]
Applying the patch for now. Would be great to have this fixed.
