### ISSUE TITLE
[Expo Router] Unable to set multiple cookies in response

### ISSUE THREAD

**Issue by hdwatts** [expo/expo#26612]
### Minimal reproducible example

https://github.com/hdwatts/expo-recreation-playground

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Expo Router API Routes do not properly return multiple `Set-Cookie` headers. Ideally, I can use the `headers.append` method to set multiple cookies in a single response.

### Reproduction Steps

I've also set up an express server to show how it should work. Run `npm run express-demo` to turn that on. It runs on port 8082.

Go to tab 1
<img width="440" alt="image" src="https://github.com/expo/expo/assets/16158417/e66ecb50-14ca-447c-bda1-f7aaffea7ad7">

Click Expo API Route and inspect the response in the network tab.
<img width="596" alt="image" src="https://github.com/expo/expo/assets/16158417/0750ad63-a9c4-4ac7-bb56-c4bd4530fd2e">

Click Express Route and inspect the response in the network tab
<img width="599" alt="image" src="https://github.com/expo/expo/assets/16158417/a0561a25-a1e2-42d1-adc7-640c7b362e5d">

Both of these routes are very simple and use same logic:

**Expo**
```ts
export function GET(request: ExpoRequest) {
  const headers = new Headers();
  headers.set("Set-Cookie", "a=1;");
  headers.append("Set-Cookie", "b=2;");
  console.log("Headers setting", headers);
  return ExpoResponse.json(
    { hello: "world" },
    {
      headers,
    }
  );
}
```

**Express**
```js
app.get("/cookie", (req, res) => {
  res.setHeader("Set-Cookie", "a=1;");
  res.appendHeader("Set-Cookie", "b=2;");
  res.json({ hello: "world" });
});
```

I believe this stems from the usage of an older version of `remix`, as I see a few issues in their repo about this problem. Would it be non-trivial to upgrade to v2?

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.1 - ~/Library/Caches/fnm_multishells/4396_1705978127572/bin/node
      npm: 10.1.0 - ~/Library/Caches/fnm_multishells/4396_1705978127572/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2
      expo-router: ~3.4.3 => 3.4.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 5.7.0
    Expo Workflow: managed

**Comment by hdwatts** [comment]
@EvanBacon Would appreciate your eyes on https://github.com/expo/expo/pull/26652 which I believe addresses this issue

**Comment by hdwatts** [comment]
@brentvatne thanks for accepting. I've opened a PR to address, would you mind taking a peek at it?

**Comment by brentvatne** [comment]
hi @hdwatts - i don't personally work on expo-router but someone from the expo-router team will have a look when they have time!
