### ISSUE TITLE
[SDK 49] TypeError: 0, _expoModulesCore.requireOptionalNativeModule is not a function (it is undefined), js engine: hermes

### ISSUE THREAD

**Issue by Karan-singh98** [expo/expo#26614]
### Minimal reproducible example

npm i -g eas-cli.
yarn add expo@^49.0.6
npx expo install --fix
npx react-native run-android

### Summary

I have followed the installation instruction from expo sdk 49 and started facing this runtime issue.

![Screenshot_2024-01-22-17-53-30-83_6737260896f6ee83626fbc3a8438c499 1](https://github.com/expo/expo/assets/109789562/aa846159-8e66-4c2e-a36f-35fb21b50155)

### Environment

 System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD    
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996    
    npmPackages:
      expo: ~49.0.6 => 49.0.22 
      expo-router: ^2.0.0 => 2.0.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: bare

**Comment by hoseinfo** [comment]
same here

**Comment by pierrebiver** [comment]
same here, I'm aslo using Clerk.

**Comment by airowe** [comment]
Same here, on Clerk

**Comment by read-my-code** [comment]
Same with using Clerk. Did someone fix it ?

**Comment by airowe** [comment]
> Same with using Clerk. Did someone fix it ?

I ended up blowing away my node_modules and package-lock.json, used `npx expo doctor`, fixed any issues, then did `npx expo-doctor --fix-dependencies` and `npx expo start -clear`.

Basically had to restart from almost scratch. My issue is that I had ran `npm upgrade` (thought I was in a non-expo project that I'm also working on) and that screwed up all my dependencies. At least I think that's what was going on.

**Comment by airowe** [comment]
To everyone following (not sure why this was closed) looks like there's a less comprehensive fix linked to here: https://github.com/clerk/javascript/issues/2650#issuecomment-1913658813

**Comment by monterourena** [comment]
Hi, I am experiencing this same problem when trying to use @clerk/clerk-expo. I have done all the possible fixes I have seen from both expo and clerk and I keep getting this same error. 

I am using expo managed through development builds. It is worth pointing out that I did several development builds during the process of testing the possible fixes that I tried.

So far I have done the following:

1. I performed the recommendations given by npx expo-doctor@latest :

- [x] I upgraded to "react-native": "0.72.10" 
- [x] I upgraded to "expo-dev-client": "~2.4.13".

2. I upgraded to expo-router@"^2.0.15"
3. Installed expo-modules-core@"~1.5.12".
4. Installed @expo/config-plugins
5. Verified that I had expo-constants@~14.4.2 installed.
6. I removed all my node_modules and reinstalled again.
7. I downgraded to @clerk/clerk-expo@0.19.30

Despite all of the above I still have the problem. I would appreciate any help you can provide. 🙏🏼
