### ISSUE TITLE
[expo 50] npx expo start --no-dev --minify --go is broken

### ISSUE THREAD

**Issue by MichalKrakow** [expo/expo#26637]
### Summary

Trying to run no development minified version of app in expo go client results in bundler not even starting build process, tried to clear cache, on both cli and expo go client with no luck. you'll endup on splash screen with "New update available, downloading" messge.

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

Windows, expo GO on android

### Minimal reproducible example

```
npx create-expo-app test-app
cd test-app
npx expo start --no-dev --minify --go
```

try to connect from expo Go app
you'll endup on splash screen with "New update available, downloading" messge.

**Comment by OrionPro** [comment]
I also don't have the application running if you try to do expo start --no-dev --minify --go.
Windows, expo GO on android
ps It just won't start, but hangs on the loading screen without any errors in the console
