### ISSUE TITLE
[expo-camera] [iOS] onBarcodeScanned is never called on iOS with Expo Go

### ISSUE THREAD

**Issue by jcxldn** [expo/expo#26658]
### Minimal reproducible example

https://github.com/jcxldn/expo-sdk50-cam-qr-repro

### Summary

When using Expo Go (client version 1017593) on my iOS 17.2.1 device with this minimal reproduction project, the camera loads up and appears to work as normal but `onBarcodeScanned` is never called even if a valid QR code is in focus and in frame. I have not been able to test this on a production build. 

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.6 Manjaro Linux
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 21.5.0 - /usr/bin/node
      Yarn: 1.22.21 - /usr/bin/yarn
      npm: 10.3.0 - /usr/bin/npm
    npmPackages:
      expo: ~50.0.3 => 50.0.3 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: managed
```

**Comment by rkuhcvark** [comment]
Might be a stupid suggestion, but have you tried to declare the `handleScan` method within the App scope?

**Comment by maxenceg** [comment]
I think they changed the prop name
It's now `onBarcodeScanned` instead of `onBarCodeScanned` (no uppercase 'C' on 'code')

**Comment by rkuhcvark** [comment]
> I think they changed the prop name It's now `onBarcodeScanned` instead of `onBarCodeScanned` (no uppercase 'C' on 'code')

According to the [doc](https://docs.expo.dev/versions/latest/sdk/camera/#onbarcodescanned), the prop remains as `onBarCodeScanned`

**Comment by jcxldn** [comment]
It's especially confusing as TS insists it's onBarcodeScanned while the docs say onBarCode scanned. As I recall I tried both on my project but neither worked. I will try it with this reproduction later today and report back for you all. I will also try barCodeScannerSettings/barcodeScannerSettings.

Thanks,

James

**Comment by maxenceg** [comment]
I think you're right, you're using the component `Camera` from `expo-camera`, so you should keep the capital 'C' on code
It's on `CameraView` from `expo-camera/next` that they seem to have removed the capital 'C'

**Comment by rkuhcvark** [comment]
Just for additional insurance, specify `[BarCodeScanner.Constants.BarCodeType.qr]` instead of `['qr']` in the `barCodeTypes`. I doubt that would help, but you never know...

**Comment by maxenceg** [comment]
FYI, I have the same issue of `onBarcodeScanned` never being fired, but I'm in dev client. Have you only tried in Expo Go or have you also tried dev client?

**Comment by jcxldn** [comment]
> It's especially confusing as TS insists it's `onBarcodeScanned` while the docs say `onBarCodeScanned`. As I recall I tried both on my project but neither worked. I will try it with this reproduction later today and report back for you all. I will also try barCodeScannerSettings/barcodeScannerSettings.
> 
> Thanks,
> 
> James

My apologies, I got a little mixed up here. It seems to be `onBarcodeScanned` for `expo-camera/next` and `onBarCodeScanned` for `expo-camera`. I tried both expo-camera and expo-camera/next on my own and had the same issue, but this minimal repro is for expo-camera.

**Comment by brentvatne** [comment]
hi there! it looks like you're using the API from expo-camera/next for settings.

here's the diff to fix that:

```diff
diff --git a/App.js b/App.js
index e52a868..09b6973 100644
--- a/App.js
+++ b/App.js
@@ -1,4 +1,5 @@
 import { AutoFocus, Camera } from 'expo-camera';
+import { BarCodeScanner } from 'expo-barcode-scanner';
 import { StatusBar } from 'expo-status-bar';
 import { StyleSheet, Text, View } from 'react-native';

@@ -22,7 +23,14 @@ export default function App() {
   return (
     <View style={styles.container}>
       <StatusBar style="auto" />
-      <Camera autoFocus={AutoFocus.auto} style={StyleSheet.absoluteFillObject} onBarCodeScanned={handleScan} barCodeScannerSettings={{barCodeTypes: ["qr"]}}/>
+      <Camera
+        autoFocus={AutoFocus.auto}
+        style={StyleSheet.absoluteFillObject}
+        onBarCodeScanned={handleScan}
+        barCodeScannerSettings={{
+          barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
+        }}
+      />
     </View>
   );
 }

diff --git a/package.json b/package.json
index 0a40983..7d52698 100644
--- a/package.json
+++ b/package.json
@@ -10,10 +10,11 @@
   },
   "dependencies": {
     "expo": "~50.0.3",
+    "expo-barcode-scanner": "~12.9.2",
+    "expo-camera": "~14.0.2",
     "expo-status-bar": "~1.11.1",
     "react": "18.2.0",
-    "react-native": "0.73.2",
-    "expo-camera": "~14.0.2"
+    "react-native": "0.73.2"
   },
   "devDependencies": {
     "@babel/core": "^7.20.0"
```

**Comment by jakobjohansson** [comment]
> hi there! it looks like you're using the API from expo-camera/next for settings.
> 
> here's the diff to fix that:
> 
> ```diff
> diff --git a/App.js b/App.js
> index e52a868..09b6973 100644
> --- a/App.js
> +++ b/App.js
> @@ -1,4 +1,5 @@
>  import { AutoFocus, Camera } from 'expo-camera';
> +import { BarCodeScanner } from 'expo-barcode-scanner';
>  import { StatusBar } from 'expo-status-bar';
>  import { StyleSheet, Text, View } from 'react-native';
> 
> @@ -22,7 +23,14 @@ export default function App() {
>    return (
>      <View style={styles.container}>
>        <StatusBar style="auto" />
> -      <Camera autoFocus={AutoFocus.auto} style={StyleSheet.absoluteFillObject} onBarCodeScanned={handleScan} barCodeScannerSettings={{barCodeTypes: ["qr"]}}/>
> +      <Camera
> +        autoFocus={AutoFocus.auto}
> +        style={StyleSheet.absoluteFillObject}
> +        onBarCodeScanned={handleScan}
> +        barCodeScannerSettings={{
> +          barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
> +        }}
> +      />
>      </View>
>    );
>  }
> 
> diff --git a/package.json b/package.json
> index 0a40983..7d52698 100644
> --- a/package.json
> +++ b/package.json
> @@ -10,10 +10,11 @@
>    },
>    "dependencies": {
>      "expo": "~50.0.3",
> +    "expo-barcode-scanner": "~12.9.2",
> +    "expo-camera": "~14.0.2",
>      "expo-status-bar": "~1.11.1",
>      "react": "18.2.0",
> -    "react-native": "0.73.2",
> -    "expo-camera": "~14.0.2"
> +    "react-native": "0.73.2"
>    },
>    "devDependencies": {
>      "@babel/core": "^7.20.0"
> ```

All this diff does is add expo-barcode-scanner as a dependency? And using expo-barcode-scanner yields an in app warning that the module is deprecated

**Comment by jwcheon** [comment]
Has anyone solved this issue? Same with me for 

```
<CameraView
    style={styles.camera}
    type="back"
    barcodeScannerSettings={{
      barCodeTypes: ["qr"],
    }}
    onBarcodeScanned={handleBarcodeScanned}
  >
 ```

onBarcodeScanned doesn't fire anything..

**Comment by obviouswhy** [comment]
Seems like for iOS the `barCodeTypes: ["qr"]` part is not recognizing the enum of the type for iOS correctly.
I was able to trigger `onBarcodeScanned` by setting  barCodeTypes to `BarCodeScanner.Constants.BarCodeType.qr` or `"org.iso.QRCode"` (which is the value of BarCodeScanner.Constants.BarCodeType.qr).

It would look something like: 
```
<CameraView
    style={styles.camera}
    barcodeScannerSettings={{
      barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
      // barCodeTypes: ["org.iso.QRCode"], <--- this also works
    }}
    onBarcodeScanned={handleBarcodeScanned}
  >
```

**Comment by jwcheon** [comment]
@obviouswhy Thanks! Indeed it was due to that barCodeTypes enum not working properly.

FYI to anyone with the same issue, since I'm using typescript I had to handle the type within the callback function:

```
  const handleBarcodeScanned = (result: BarcodeScanningResult) => {
    if (result) {
      const { type, data } = result;
      if (type === "org.iso.QRCode") {
        console.log(data);
      }
    }
  };

  <CameraView
    style={styles.camera}
    type="back"
    onBarcodeScanned={handleBarcodeScanned}
  >
```

**Comment by rafabarbosa** [comment]
> Has anyone solved this issue? Same with me for
> 
> ```
> import { CameraView, useCameraPermissions } from 'expo-camera/next';
> 
> <CameraView
>     style={styles.camera}
>     type="back"
>     barcodeScannerSettings={{
>       barCodeTypes: ["qr"],
>     }}
>     onBarcodeScanned={handleBarcodeScanned}
>   >
> ```
> 
> onBarcodeScanned doesn't fire anything..

This solution worked for me! :)

**Comment by felipejh** [comment]
> > Has anyone solved this issue? Same with me for
> > ```
> > import { CameraView, useCameraPermissions } from 'expo-camera/next';
> > 
> > <CameraView
> >     style={styles.camera}
> >     type="back"
> >     barcodeScannerSettings={{
> >       barCodeTypes: ["qr"],
> >     }}
> >     onBarcodeScanned={handleBarcodeScanned}
> >   >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > onBarcodeScanned doesn't fire anything..
> 
> This solution worked for me! :)
> 
> ```
> import { CameraView, BarcodeScanningResult, useCameraPermissions } from "expo-camera/next";
> 
> const handleQrcodeScanner = (scanningResult: BarcodeScanningResult) => {
>     console.log("Qrcode:", scanningResult.data);
> };
> 
> <CameraView
>     style={StyleSheet.absoluteFillObject}
>     facing="back"
>     onBarcodeScanned={handleQrcodeScanner}
>     barcodeScannerSettings={{
>       barcodeTypes: ["qr"],
>     }}
> />
> ```

I copied that code but is still not working here.

**Comment by andrconstruction** [comment]
> barcodeScannerSettings

the same problem not fired anything

**Comment by dembal1990** [comment]
I have a same problem on IOS

**Comment by iwakawamarcos** [comment]
This worked for me, keep in mind that the CameraView is imported and that it is "onBarcodeScanned"...  <CameraView
                    ref={cameraRef}
                    onBarcodeScanned={({ data }) => handleBarCodeScanned({ data })}
                    barcodeScannerSettings={{
                        barcodeTypes: ["qr"],
                    }}
                    style={styles.scanner}
                    ratio="16:9"
                >

**Comment by wallid** [comment]
This worked for me. I'm just struggling to find the barcode number in the data.
```js 
  const handleBarCodeScanned = (data) => {
    JSON.stringify(data);
    if (data.type === 'org.gs1.EAN-13') { // Make sure it's an EAN-13 barcode
      setScannedBarcode(data);
      Alert.alert("Barcode Scanned", `Type: ${data.type}\nData: ${data.data}\nRawData: ${data.rawData} ${JSON.stringify(data)}`);
    }

  }


  return (
    <View style={styles.container}>
      <CameraView
        style={styles.camera}
        onBarcodeScanned={handleBarCodeScanned}
        barcodeScannerSettings={{ barcodeTypes: ['ean13'] }}
      >
        <Text style={styles.textOverlay}>Scanning for EAN-13 Barcodes...</Text>
      </CameraView>
      {scannedBarcode && (
        <Text style={styles.barcodeText}>Scanned: {scannedBarcode}</Text>
      )}
    </View>
  );
  ```
