### ISSUE TITLE
[expo-camera] Face detection on some android devices requires turning the device upside down

### ISSUE THREAD

**Issue by refrare** [expo/expo#26656]
### Minimal reproducible example

https://snack.expo.dev/Ln2FWfGNvA0LoLC2UtUyO

### Summary

When implementing a camera using Expo-Camera on some Android devices (in my case `A303SH`), the face detection will not pass unless the device is turned upside down (i.e. camera upside down).

Simply put, Expo-camera does not take into account cases where the mounting angle of the physical camera module is the opposite of the common orientation.

note: I have uploaded the repro to snack, but understand that FaceDetector does not work with ExpoGo.
If you want to reproduce, please build locally

### Brief survey
I used the following code to determine the natural orientation of my Android device and the physical mounting orientation of the camera. I found that the natural orientation of the device is `0` and the physical orientation of the camera causing the problem (front camera in my case) is `90`.
<details>
<summary>used code</summary>

```
val windowManager = context.getSystemService(Context.WINDOW_SERVICE) as WindowManager?
val rotation = windowManager!!.defaultDisplay.rotation
println(rotation) // Surface.ROTATION_0 

val info: Camera.CameraInfo = Camera.CameraInfo()
Camera.getCameraInfo(CameraMetadata.LENS_FACING_BACK, info)
println(info.orientation) // 90
Camera.getCameraInfo(CameraMetadata.LENS_FACING_FRONT, info)
println(info.orientation) // 90
```
</details>

The [CameraInfo reference](https://developer.android.com/reference/android/hardware/Camera.CameraInfo#orientation) says this

> For example, suppose a device has a naturally tall screen. The back-facing camera sensor is mounted in landscape. You are looking at the screen. If the top side of the camera sensor is aligned with the right edge of the screen in natural orientation, the value should be 90. If the top side of a front-facing camera sensor is aligned with the right of the screen, the value should be 270.

Since my camera orientation is `90`, it seems that **the front-facing camera sensor is aligned with the left of the screen**.

Then, ExpoCameraView.onFramePreview, which flows the captured preview to face detection, calculates the correct camera angle by doing the following

`ExpoCameraView.onFramePreview`
```
val correctRotation = getCorrectCameraRotation(rotation, cameraView.facing)
```
`CameraViewHelper.getCorrectCameraRotation`
```
  fun getCorrectCameraRotation(rotation: Int, facing: Int) =
    if (facing == CameraView.FACING_FRONT) (rotation - 90 + 360) % 360
    else (-rotation + 90 + 360) % 360
```

Since the natural orientation of my device is `0` and we are talking about the front camera now, the return value of `getCorrectCameraRotation ` is `-90`.

By rotating the camera -90 degrees where it was originally mounted at the opposite angle, the `FaceDetectorTask` tries to perform face recognition on the upside-down image.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
      npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/refrare/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-31 | Google Play Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.2 => 50.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    Expo Workflow: bare

**Comment by brentvatne** [comment]
one alternative approach could be to turn your face upside down!

on a more serious note, we've deprecated the expo-face-detector module in SDK 50 and we recommend using react-native-vision-camera for this functionality instead: https://docs.expo.dev/versions/latest/sdk/facedetector/#facedetectordetectfacesasyncuri-options

as a result, we don't intend to fix any of the existing issues with it, since it will be removed in SDK 51.
