### ISSUE TITLE
Pushing an already mounted screen to the stack doesn't actually push a new screen, it just replaces the current one (e.g. no animation)

### ISSUE THREAD

**Issue by JClackett** [expo/expo#26669]
### Minimal reproducible example

https://github.com/JClackett/expo-router-tabs-stack

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Quite the elaborate tab setup, but the demo show cases shared screens/modals between many different tabs, as I was having other issues that I will share.

If you navigate to a "user item" and then to a "post item" and then keep going again into another "user item" etc. If you ever land on a screen that has been rendered before (i.e a same user id or post id) it doesnt push a new screen to the stack it just replaces the current one, which then makes going back do some funky stuff.

Expected behaviour would be that if I push a screen thats technically already in the stack, it still pushes another one anyway.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.18.2 - /var/folders/dt/wxhpvnj560xc4_qw5nnbsqw40000gn/T/fnm_multishells/56381_1706122949451/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /var/folders/dt/wxhpvnj560xc4_qw5nnbsqw40000gn/T/fnm_multishells/56381_1706122949451/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.1 => 50.0.3 
      expo-router: ~3.4.1 => 3.4.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: managed

**Comment by JClackett** [comment]
Here's a quick recording, at some point it doesn't "push" anymore

Uploading Simulator Screen Recording - iPhone 15 Pro - 2024-01-24 at 20.08.03.mp4…

**Comment by marklawlor** [comment]
Possibility related to https://github.com/expo/expo/pull/26597

**Comment by marklawlor** [comment]
Confirmed issue, tracking progress in PR #26678
