### ISSUE TITLE
Lost state when push() or navigate() so going back() founds brand new (prev) screen

### ISSUE THREAD

**Issue by abpbackup** [expo/expo#26671]
### Minimal reproducible example

na

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When doing router.push() or router.navigate() from a screen with state (React.useState) it is lost due to the fact that the components are unmounted. Then when doing router.back() there is no state as expected en the prev route. For instance, having a screen with multiple filters for a search and then show the results and going back to the filters. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
      Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.3 => 50.0.3 
      expo-router: ^3.0.0 => 3.4.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by rabbitmouse** [comment]
i have same issue.....On iOS, when I use route.back to return to the index, entering other pages will display the previous page.

**Comment by rabbitmouse** [comment]
@abpbackup Found any solution?
