### ISSUE TITLE
[SDK50] [expo-camera/next] Barcode scanner not working on iOS

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/expo#26687]
### Minimal reproducible example

https://github.com/stefan-schweiger/expo50-scanner-bug

### Summary

Just tried the new `expo-camera/next` and the barcode scanner appears to not be working on iOS. You can try the repro in Expo Go (but experiencing the same issue in my real app with a dev client) and just scan some random QR code like the one below on Android and you will get log messages with the data. On iOS though just nothing happens.

```jsx
export default function App() {
  const handleCodeScanned = (data) => {
    console.log(data);
  }

  const [permission, requestPermission] = useCameraPermissions();

  useEffect(() => {
    requestPermission();
  });

  if (!permission?.granted) {
    return null;
  }

  return (
    <View style={styles.container}>
      <CameraView style={styles.camera} barcodeScannerSettings={{ barCodeTypes: ['qr'] }} onBarcodeScanned={handleCodeScanned} />
    </View>
  );
}
```

<img width="317" alt="image" src="https://github.com/expo/expo/assets/3532342/6c1e1bc4-4004-4a00-a8b0-5b4d4a0e9312">

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.3 => 50.0.3 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    Expo Workflow: managed
```

**Comment by alanjhughes** [comment]
@stefan-schweiger - No problem! Thanks for reporting! Hopefully later today. Will let you know when it's published.

**Comment by alanjhughes** [comment]
Hi @stefan-schweiger - fix has been published in `14.0.3`.

**Comment by Ganesh1991** [comment]
Using latest package for expo-camera 14.0.3 and below is source code but still it is not working for me

`import React, { useState } from "react";
import { Text, View, StyleSheet, Button } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera/next";
import { TouchableOpacity } from "react-native-gesture-handler";

export default function CodeScanner({ handleScan, closeScanner }) {
  const [type, setType] = useState("back");
  const [scanned, setScanned] = useState(false);
  const [permission, requestPermission] = useCameraPermissions();

  if (!permission) {
    // Camera permissions are still loading
    return <View />;
  }

  if (!permission.granted) {
    // Camera permissions are not granted yet
    return (
      <View style={styles.container}>
        <Text style={{ textAlign: "center" }}>
          We need your permission to show the camera
        </Text>
        <Button onPress={requestPermission} title="grant permission" />
      </View>
    );
  }

  const handleBarCodeScanned = ({ type, data }) => {
    console.log("🚀 ~ handleBarCodeScanned ~ data");
    setScanned(true);
    console.log(
      `Bar code with type ${type} and data ${data} has been scanned!`
    );
    handleScan(data);
  };

  function toggleCameraType() {
    setType((current) =>
      current === CameraType.back ? CameraType.front : CameraType.back
    );
  }

  console.log("🚀 ~ CodeScanner ~ permission:", permission);

  return (
    <View style={styles.container}>
      <CameraView
        style={styles.camera}
        facing={type}
        ratio="16:9"
        onBarCodeScanned={handleBarCodeScanned}
        barcodeScannerSettings={{
          barCodeTypes: [
            "qr",
            "pdf417",
            "ean13",
            "code128",
            "code39",
            "upc_a",
            "upc_e",
            "ean8",
            "itf14",
            "interleaved2of5",
            "codabar",
          ],
          interval: 10,
        }}
        barCodeSize={{ width: 500, height: 500 }}
      >
        <View style={styles.buttonContainer}>
          <TouchableOpacity style={styles.button} onPress={closeScanner}>
            <Text style={styles.text}>Back</Text>
          </TouchableOpacity>
        </View>
      </CameraView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "stretch",
  },
  camera: {
    flex: 1,
    alignItems: "stretch",
  },
  buttonContainer: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "transparent",
    margin: 64,
    padding: 16,
  },
  button: {
    flex: 1,
    alignSelf: "flex-end",
    alignItems: "center",
  },
  text: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
  },
});
`

**Comment by stefan-schweiger** [comment]
@Ganesh1991 can you please try to correctly format your code?

I've tried it with 14.0.3 for QR codes and it now is working for me. Did you rebuild your development client?

**Comment by Ganesh1991** [comment]
@stefan-schweiger,
 
Did you rebuild your development client? -- Yes

Please find the source at https://gist.github.com/Ganesh1991/4fd95971e03d434065e934e672518e04

QR codes are working but barcode are not working.

**Comment by stefan-schweiger** [comment]
@Ganesh1991 What type of barcode are you trying to scan exactly? Can you provide an example?

**Comment by Ganesh1991** [comment]
@stefan-schweiger 

![barcodeSample](https://github.com/expo/expo/assets/8073475/35cee512-5418-47f4-886c-feb2b13c5137)

Type: Code128

**Comment by stefan-schweiger** [comment]
@Ganesh1991 when I change my own app to accept Code128 and scan your example it works just fine.

**Comment by stefan-schweiger** [comment]
@Ganesh1991 I think your code has some issues, because your CameraView includes the property `ratio` which does not exist anymore on `expo-camera/next` and `onBarCodeScanned` is now `onBarcodeScanned`.

**Comment by Ganesh1991** [comment]
@stefan-schweiger 
Can you share the sample code?

Also I am trying with IOS 17.2.1

Removed ratio property and replaced onBarCodeScanned with onBarcodeScanned but still not working on ios

**Comment by felipejh** [comment]
I have this code here and it doesn't work:

```
<CameraView
  style={StyleSheet.absoluteFillObject}
  facing="back"
  onBarcodeScanned={value => console.log(value)}
  barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
>
```

**Comment by xcboi2k** [comment]
![carbon](https://github.com/expo/expo/assets/72724132/25f48be3-4d77-4c76-867a-c62482ed365e)
im at sdk49, it works in expo go but not in development build, i also tried updating to sdk50 but same outcome

**Comment by alanjhughes** [comment]
@xcboi2k you are using the legacy camera with some of the props for the new camera. You need to use it like this 
```
<Camera
  barCodeScannerSettings={{
    barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
  }}
/>
```

**Comment by make4711** [comment]
Instead of "ean13" I used "org.gs1.EAN-13" now it works for me too. You can take this property from the old `expo-barcode-scanner` on `onBarCodeScanned` event shown in `type` param.
Thank you very much Alan. This hint was very helpful for me.

**Comment by jerozeek** [comment]
`import {StyleSheet, View} from "react-native";
import {useRef} from "react";
import { CameraView, BarcodeScanningResult, useCameraPermissions} from "expo-camera/next";
import theme from "../../utils/theme";


const ScanView = () => {

    let cameraRef = useRef<any>(null);
    const [permission, requestPermission] = useCameraPermissions();

    const onScanned = (scanningResult: BarcodeScanningResult) => {
        console.log(scanningResult)
    }

    return (
        <View style={{
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
        }}>
            <View style={{
                width: '80%',
                aspectRatio: 1,
                overflow: 'hidden',
                borderRadius: 10,
                marginBottom: 40,
            }}>
                <CameraView
                    style={{
                        flex: 1,
                    }}
                    ref={cameraRef}
                    facing={'back'}
                    barcodeScannerSettings={{
                        barcodeTypes: [
                            "qr",
                            "pdf417",
                            "ean13",
                            "code128",
                            "code39",
                            "upc_a",
                            "upc_e",
                            "ean8",
                            "itf14",
                            "codabar"
                        ],
                        interval: 10,
                    }}
                    onBarcodeScanned={onScanned}
                />
            </View>
        </View>

    )
}

const styles = StyleSheet.create({
    camera: {
        aspectRatio: 1
    }
});

export default ScanView
`

Can i get a fix>

**Comment by MaximeErkensPDirekt** [comment]
@Ganesh1991 change `barcodeScannerSettings` to `barCodeScannerSettings`

**Comment by PAPATIRI** [comment]
i have code for scanning barcode using expo-camera like this
` <View style={styles.cameraWrapper}>
        <CameraView
          style={styles.camera}
          facing={facing}
          mode="video"
          barcodeScannerSettings={{
            barcodeTypes: [
              "aztec",
              "ean13",
              "ean8",
              "qr",
              "pdf417",
              "upc_e",
              "datamatrix",
              "code39",
              "code93",
              "itf14",
              "codabar",
              "code128",
              "upc_a",
            ],
          }}
          onBarcodeScanned={({ data, type }) => {
            console.log("barcode data scanned", data, type);
            setScannedData(data);
            Alert.alert(
              "data scanned!",
              `type data is ${type} and the data is ${data}`
            );
          }}
        >
          <TouchableOpacity
            style={styles.flipButtonCamera}
            onPress={toggleCameraFacing}
          >
            <MaterialCommunityIcons
              name="camera-flip-outline"
              size={48}
              color={Colors.light.background}
            />
          </TouchableOpacity>
        </CameraView>
      </View>
    </SafeAreaView>`
    
    my expectation from my code above is when the camera scanned the barcode it shows log on my console and show alert on my app, but when i use my phone's camera it does nothing.
    i am using expo sdk-51 on windows 10. 
    is there any issue from my code above or i missed something that i need to add to make scanning barcode work properly?
    thanks

**Comment by gusnaughton** [comment]
Has anyone found a solution to this issue? I've noticed on iPhones model 12 and under (what I have had available to test) that the package works, but on newer models, it does not.

**Comment by Kohfeldt** [comment]
I keep getting this error:
iOS Bundling failed 3716ms index.js (863 modules)
Unable to resolve "expo-camera/next" from "ScannerScreen.js"

package.json:
"expo": "^52.0.21",
"expo-camera": "~16.0.10",

app.json:
      [
        "expo-camera",
        {
          "cameraPermission": "Allow $(PRODUCT_NAME) to access your camera",
          "microphonePermission": "Allow $(PRODUCT_NAME) to access your microphone",
          "recordAudioAndroid": true
        }
      ],
      
Any help would be much appreciated.

**Comment by bj97301** [comment]
> ![carbon](https://github.com/expo/expo/assets/72724132/25f48be3-4d77-4c76-867a-c62482ed365e) im at sdk49, it works in expo go but not in development build, i also tried updating to sdk50 but same outcome



> [@xcboi2k](https://github.com/xcboi2k) you are using the legacy camera with some of the props for the new camera. You need to use it like this
> 
> ```
> <Camera
>   barCodeScannerSettings={{
>     barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
>   }}
> />
> ```

this fixed my lack of scanning on expo 50.  odd that I cant just pass in 'qr'
