### ISSUE TITLE
[SDK50] Can't build Android app (:app:createBundleReleaseJsAndAssets FAILED)

### ISSUE THREAD

**Issue by TomCorvus** [expo/expo#26698]
### Minimal reproducible example

https://github.com/TomCorvus/ExpoMonorepo

### Summary

Hi,

Since SDK50, I can't build Android release build. I have an error:
```
> Task :app:createBundleReleaseJsAndAssets FAILED
CommandError: It looks like you're trying to use web support but don't have the required
dependencies installed.

Please install react-dom@18.2.0, @expo/metro-runtime@~3.1.1 by running:

npx expo install react-dom @expo/metro-runtime

If you're not using web, please ensure you remove the "web" string from the
platforms array in the project Expo config.


Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 44s
1057 actionable tasks: 22 executed, 1035 up-to-date
```

I have not the "web" string in Expo config file. This is a bare workflow project and app.json contains only app name.
I can build my app with debug keystore and debug mode but when I try to build it in release, it crashs.
So it's hard to give you a representative repro without giving you a release keystore.

I'm using `webpack` and `react-native-web` in my project only to generate the app storybook.
I don't know if it is the cause.

Thanks for your help.

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 4.0.2 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
      Watchman: 2023.07.10.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/nickname/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 23, 26, 28, 29, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.3 => 50.0.3 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: ^0.73.2 => 0.73.2 
      react-native-web: ^0.19.10 => 0.19.10 
    Expo Workflow: bare
```

**Comment by benjaminkomen** [comment]
I had the same issue, my workaround was to add `platforms: ['ios', 'android']` to my `app.json`, essentially explicitly excluding `web` as a platform option. I also only included `react-native-web` for storybook, but I think Expo thinks you want your app to work for web once you have that dependency.

**Comment by TomCorvus** [comment]
Thanks @benjaminkomen, your tip seems to bypass the problem.

**Comment by EvanBacon** [comment]
@TomCorvus What command are you running and in what directory?

**Comment by TomCorvus** [comment]
@brentvatne I'm using Android Studio to generate the signed bundle.
`Executing tasks: [:app:bundleRelease] in project /Users/tomcorvus/Documents/Laboratory/ExpoMonorepo/packages/project1/android`

**Comment by TomCorvus** [comment]
I don't think it is because of that I can't build Android app. I opened an issue with expo-font.
The error message evolved since I set platforms array in app.config.ts

https://github.com/expo/expo/issues/26668#issuecomment-1912052619

**Comment by benjaminkomen** [comment]
@EvanBacon , maybe I should create a separate bug issue, but [this is an example of the essence](https://github.com/benjaminkomen/expo-sdk50-web-support-error) of what I encountered.

**Comment by brentvatne** [comment]
@EvanBacon - here's how to repro:

```
yarn create expo-app test-build
cd test-build
yarn expo install react-native-web
yarn expo run:android --variant release
```

this simulates the scenario described, where you include react-native-web but only for the sake of storybook or some other similar tool

**Comment by EvanBacon** [comment]
@TomCorvus you must use `expo/metro-config` with Expo CLI btw, many issues will arise if you try to use a different bundler config.

**Comment by paulschreiber** [comment]
@EvanBacon I am still seeing this problem with our bare React Native app with Expo 50.0.6 ([run log](https://github.com/techmatters/terraso-mobile-client/actions/runs/7848701914/job/21420412005)). What needs to change to fix this? (It built cleanly with React Native 0.72.x and Expo 49.)

**Comment by brentvatne** [comment]
@paulschreiber - please create a new issue with a minimal reproducible example

**Comment by paulschreiber** [comment]
In `app/buid.gradle`, `install-expo-modules` adds these three lines:
```
    // Added by install-expo-modules
    entryFile = file(["node", "-e", "require('expo/scripts/resolveAppEntry')", rootDir.getAbsoluteFile().getParentFile().getAbsolutePath(), "android", "absolute"].execute(null, rootDir).text.trim())
    cliFile = new File(["node", "--print", "require.resolve('@expo/cli')"].execute(null, rootDir).text.trim())
    bundleCommand = "export:embed"
```

Commenting out both the `cliFile` and `bundleCommand` lines lets the build complete successfully.

**Comment by brentvatne** [comment]
@paulschreiber - that would mean that you are not using `@expo/cli` for bundling, which may be fine, but again, please just create a new issue with a minimal example and share your metro config
