### ISSUE TITLE
When updating the SDK from 48 to 48, I lost the EAS branches that are displayed in Expo Go

### ISSUE THREAD

**Issue by JoezerSmaniotto** [expo/expo#26699]
### Minimal reproducible example

update sdk 49 from sdk 48, 

### Summary

When updating SDK 48 to 49, I ended up losing the branches in Expo Go (EAS), I did NOT find a way to revert this.
In my case I had the BRANCHS(EAS): production, development and preview, they are important because we have the history of what was done, and of course each one has its specific purpose.
Now this is just development, if anyone has experienced this, could you explain how you resolved it?
Note: In the print below I omitted the name of the owner and the project...

Here are the images, one image only with the development branch (current after updating to SDK49), and another image as it was with all branches (As it was before the SDK update).

![expo2](https://github.com/expo/expo/assets/42808798/7455be98-9577-42ff-a284-e7b55e03c82a)
![expo1](https://github.com/expo/expo/assets/42808798/17fad12c-7125-47cc-8865-84cb7bbaa6e6)

Important point, I am using Expo Go. In Expo Go for testing, I chose the 'open Android' option, then uninstalled Expo Go and reinstalled it. In this case, when this happens, the lost branches reappear. However, when I go to the Play Store and update the Expo Go app, it only shows the 'development' branch again.
![expo3terminal](https://github.com/expo/expo/assets/42808798/acfdae24-9816-4951-9f24-a55db5360b7d)

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

**Comment by wschurman** [comment]
@JoezerSmaniotto - thanks for the report!

I think this behavior is expected, though a jarring UX for sure. What's happening is that each version of Expo Go only supports a small set of runtime versions (SDK versions), and Expo Go only queries for updates/branches/channels that it supports (updates that it can launch). By upgrading to the latest Expo Go, which only supports SDKs 49 and 50, it no longer queries for updates on SDK 48. You should still be able to view all your channels, branches, and updates on the Expo website.

**Comment by JoezerSmaniotto** [comment]
Could you explain why, even though I am on SDK49, when I open the app in Expo Go and choose the 'open Android' option, it displays the message 'Expo Go on SM_M526B is outdated, would you like to upgrade?' If I respond 'Yes', the app is uninstalled in Expo Go and I reinstall it. In this case, when this happens, the missing branches reappear. However, when I go to the Play Store and update the Expo Go app, it only displays the 'development' branch.
Shouldn't it always display only the 'development' branch considering that both are on SDK 49?
My goal was that, regardless of whether the SDK versions are updated or not, it should always display all branches.
![Design sem nome](https://github.com/expo/expo/assets/42808798/6875c732-d2b3-414d-9b10-737d36348b3c)

However, it seems odd to me that when I select the 'open Android' option in Expo Go, it displays the message 'Expo Go on SM_M526B is outdated, would you like to upgrade?' If I respond 'Yes', all the branches reappear even though I am on SDK version 49. This is shown in the images below, the before and after. However, the problem is that if I update the Expo Go version on the Play Store, it goes back to displaying only the 'development' branch.

![expo2](https://github.com/expo/expo/assets/42808798/a8eec970-63dd-44f6-a8f5-7dcded4c2bfd)
![expo1](https://github.com/expo/expo/assets/42808798/1ae9da30-104f-48aa-9e2a-76ebab0818a4)

**Comment by wschurman** [comment]
> Could you explain why, even though I am on SDK49, when I open the app in Expo Go and choose the 'open Android' option, it displays the message 'Expo Go on SM_M526B is outdated, would you like to upgrade?

This definitely seems like a bug on our end. I'll reopen this to investigate that piece.

> My goal was that, regardless of whether the SDK versions are updated or not, it should always display all branches.

Currently the only place to view that is the website. I created an internal task for us to look into redesigning this piece of Expo Go to show all the branches (even when they can't be launched), but I don't have an ETA on it.

**Comment by wschurman** [comment]
> Could you explain why, even though I am on SDK49, when I open the app in Expo Go and choose the 'open Android' option, it displays the message 'Expo Go on SM_M526B is outdated, would you like to upgrade?

@JoezerSmaniotto - thanks for catching this! I've drafted a fix to the messaging to indicate that it isn't necessarily outdated, but is a mismatch.

What was happening was when the project is 49, we prompt to install the version of Expo Go that best matches that SDK version. Because SDK 49 is not the latest version, this will be different than the version in the store. The version that is installed for SDK 49 also includes SDK 48, so branches/updates for both SDK 48 and 49 will be shown in that version. In the store version, only 49 and 50 are supported, so only updates compatible with those will be shown.

In the next release, our plan is that only a single SDK version will be supported in the app, so this should help reduce confusion. I've also filed a task for us internally to handle the UX better of browsing branches/updates in Expo Go, and potentially show all branches and just disable launching ones with no compatible updates.

**Comment by JoezerSmaniotto** [comment]
I believe it wasn't clear, so I will detail it better.
Note: _Analyze the chronological order of events, all the cell phone images are displaying the time in yellow, in the top left corner of the screen._

**Step 1**:
I will go to the PlayStore to check if there is an update for Expo Go, as shown in the image below..
 
![111PlayStore](https://github.com/expo/expo/assets/42808798/41627d91-da86-4061-98d5-f0f696e3697a)

Having done that, I will go to the project in Expo Go and check the branches of the project. I notice that only the "development" branch exists.
![122Expo](https://github.com/expo/expo/assets/42808798/0fed832e-0120-48cb-a997-c448a250a44b)

**Step 2**
I run the project "npx expo start --go -c", choose the 'open Android' option, and it displays the message 'Expo Go on SM_M526B is outdated, would you like to update?' If I answer 'Yes', the app is uninstalled from Expo Go and I reinstall it.
![166Terminal](https://github.com/expo/expo/assets/42808798/e23181e3-d648-48d4-a236-e9262b2b4edd)

Since the app was reinstalled, I perform the login and then the branches reappear.
![133Expo](https://github.com/expo/expo/assets/42808798/e8083981-65ad-4498-90fe-221f866391ab)

At the same moment, Expo Go in the PlayStore, which minutes ago had no update, now strangely shows an update.
![144PlayStore](https://github.com/expo/expo/assets/42808798/7782a9ab-b181-465b-b65d-d03182b90c0d)

**Step 3**
I perform the update on Expo Go, as described in step 3. When this update occurs, the listing of branches returns to showing only the "development" branch.![155Expo](https://github.com/expo/expo/assets/42808798/f5abf6ef-a5a5-47b4-878e-81b00c3e840a)

O que me leva a entender que  o Passo 1, no qual é branchs apresentado o apenas a branch "development" é igual ao Passo 3 que apresentada apenas a branch "development". Parece que acontece algo estranho no meu pronto de vista.  Atualização que acontece  neste momento  `"Rodo o projeto "npx expo start --go -c",  escolho a opção 'abrir Android', ele exibe a mensagem 'Expo Go no SM_M526B está desatualizado, gostaria de atualizar?' Se eu responder 'Sim', o aplicativo é desinstalado do Expo Go e eu o reinstalo, após isso as branchs não listadas voltam a ser apresentadas `. Esta listagem das demais branchs deveria permanecer. Mesmo Após o surgimento e atualização do Expo na PlayStore que acontece no Passo 3 OU nunca deveria ser apresentado as branchs escondidas após  ´"Rodo o projeto "npx expo start --go -c",  escolho a opção 'abrir Android', ele exibe a mensagem 'Expo Go no SM_M526B está desatualizado, gostaria de atualizar?' Se eu responder 'Sim', o aplicativo é desinstalado do Expo Go e eu o reinstalo."´

 This leads me to understand that Step 1, in which only the "development" branch is shown, is identical to Step 3, which also only shows the "development" branch. It seems that something strange is happening from my point of view. The update that occurs at the moment "`I run the project 'npx expo start --go -c', choose the 'open Android' option, and it displays the message 'Expo Go on SM_M526B is outdated, would you like to update?' If I answer 'Yes', the app is uninstalled from Expo Go and I reinstall it, after which the unlisted branches are shown again.`" This listing of other branches should remain. Even after the emergence and update of Expo in the PlayStore that occurs in Step 3 OR the hidden branches should never be shown after "`I run the project 'npx expo start --go -c', choose the 'open Android' option, and it displays the message 'Expo Go on SM_M526B is outdated, would you like to update?' If I answer 'Yes', the app is uninstalled from Expo Go and I reinstall it.`"

**Comment by wschurman** [comment]
Yep, the "outdated" is a misnomer. It should read something like "this version of Expo Go is not optimized for this SDK version" when the project being opened doesn't have a matching SDK version, and the correct Expo Go version could be older or newer than the installed version.

So, for example (in the current state of the world, version numbers below are made up for illustration purposes):
- latest version in the play store is Expo Go version 50 and the latest SDK is 50.
- if you have Expo Go version 49 and your project uses SDK 49. You will not be prompted to download Expo Go in the CLI, but you also would be using an older version than the latest version in the store. You may be prompted to download a newer version if it still supports 49 but that functionality is going away soon.
- if you have Expo Go version 48 and your project uses SDK 49, you will be prompted to download Expo Go version 49.
- if you have Expo Go version 49 and your project uses SDK 48, you will be prompted to download Expo Go version 48.

We're planning to fix the listing of other branches in the app. And I agree that it'd probably be a better UX to not require an upgrade if the current Expo Go version supports the project SDK version. We'll take a look at that too for SDK 51. Thanks for the feedback!

**Comment by JoezerSmaniotto** [comment]
Thanks.

**Comment by JoezerSmaniotto** [comment]
A question arose for me, with Expo GO, in each branch I can access that development, having access to the "build" of that branch. Considering that the branches will no longer be listed because they are in previous versions of the SDK in Expo Go, how could I access them in EXPO GO?

**Comment by wschurman** [comment]
@JoezerSmaniotto - Expo Go currently only lists branches with updates that are compatible with it. There are ways to install previous versions of Expo Go for Android: https://docs.expo.dev/get-started/expo-go/#how-can-i-install-an-older-version (which is what you found with that prompt earlier, as it was technically installing an older version)
