### ISSUE TITLE
npx create-expo-module@latest --local sets wrong expo-module.config.json

### ISSUE THREAD

**Issue by VNDRN** [expo/expo#26693]
### Summary

npx create-expo-module@latest --local sets apple instead of ios in platforms

// wrong expo-module.config.json
```json
{
  "platforms": ["apple", "android", "web"],
  "apple": {
    "modules": ["ExampleModule"]
  },
  "android": {
    "modules": ["expo.modules.example.ExampleModule"]
  }
}
```

// What it should be:  expo-module.config.json
```json
{
  "platforms": ["ios", "android", "web"],
  "ios": {
    "modules": ["ExampleModule"]
  },
  "android": {
    "modules": ["expo.modules.example.ExampleModule"]
  }
}

```

### What platform(s) does this occur on?

iOS

### SDK Version

49

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.asdf/installs/nodejs/18.18.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/shims/yarn
      npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/vndrn/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.8.0
    Expo Workflow: bare

### Minimal reproducible example

in an expo project, run npx create-expo-module@latest --local & follow the cli steps

**Comment by aleqsio** [comment]
I think that's actually expected, we renamed `ios` to `apple` in preparation for macos support. 
@VNDRN is this causing runtime issues or the module is not working for you?

**Comment by VNDRN** [comment]
Yes, the native module isn’t found on ios (error gets thrown)

**Comment by aleqsio** [comment]
Sorry for not responding earlier – this issue has been fixed for quite some time, so we can close it
