### ISSUE TITLE
[SDK50] [ios] [MediaLibrary] MediaSubtype "hdr" not returned

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#26692]
### Minimal reproducible example

https://github.com/RRaideRR/expo-50-media-subtypes

### Summary

On my iPhone 14, iOS 17.2.1, I select a HDR video captured by my iPhones camera. I expect that 

```
MediaLibrary.getAssetInfoAsync(assetId, {}).then((assetInfo) => {
  Alert.alert('Asset info', JSON.stringify(assetInfo.mediaSubtypes));
})
```

prints ['hdr']. It prints [].

Note: in the example project you first have to grant media library permission, so that `ImagePicker.launchImageLibraryAsync` also returns the `assetId`. 

I also tested it with live photos (`mediaSubtypes=['livePhoto']`) and screenshots (`mediaSubtypes=['screenshot']`) --> this worked.

It is shown as a HDR video in my iOS photos app:
  <img src="https://github.com/expo/expo/assets/3411292/7ccb315b-1394-44d5-9e22-78cd5f8b8551" width=45% />

The example flow:
https://github.com/expo/expo/assets/3411292/da4b26c7-2388-4539-9b70-25eb5b1a9f97

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.3 => 50.0.3 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 7.0.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by vonovak** [comment]
Hello @RRaideRR,
thanks for reporting this. I believe the best way to approach this in a quick manner is improve the docs - i.e. to direct people to the place where the values are actually defined and explained, which is what I did.

I'm going to follow up on whether more support for videos will be added as well.

Thank you 👍

**Comment by RRaideRR** [comment]
Totally understandable to adjust the docs in this case @vonovak - I would have done the same :). Thanks for the follow up!
