### ISSUE TITLE
Detect Screen Orientation

### ISSUE THREAD

**Issue by canfie1d** [expo/expo#267]
What is the probability of duplicating the functionality provided by [react-native-orientation](https://github.com/yamill/react-native-orientation) in Expo?

**Comment by brentvatne** [comment]
we are adding a `ScreenOrientation` api in the next release for locking orientation at run-time, and for detecting the orientation we recommend in those docs to use the `Dimensions` api to get the width/height, then you can see if width > height or height > width. the only thing this doesn't let you do is determine if the device is upside down. if this is important for you, please open an issue on https://expo.canny.io/feature-requests :)

**Comment by lebreRafael** [comment]
I need to know if the landscape is left or right so I opened a [feature request](https://expo.canny.io/feature-requests/p/react-native-orientation-getspecificorientation) as you said and I'm writing here in case of anyone that needs the same thing reaches this issue.
