### ISSUE TITLE
wants to capture image in by using expo camera

### ISSUE THREAD

**Issue by MirzaAhmadBilal** [expo/expo#2670]
hi there i m using expo camera ..i want to capture image from this component but my code captured nothing .. here is my code 
```js
export default class CameraEx extends React.Component {
    // static navigationOptions = {
    //     header: null
    // }
  state = {
    hasCameraPermission: null,
    type: Camera.Constants.Type.back,
    photo: null,
    photoId:''
  };

  async componentDidMount() {
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({ hasCameraPermission: status === 'granted' });
  }
  takePicture = async function() {this.camera.takePictureAsync({ skipProcessing: true }).then((data) => {
        this.setState({
            //takeImageText: "PICTURE TAKEN",
            photo: data.uri
        }, alert(data.uri))
    })
     
}
 render() {
    const { hasCameraPermission } = this.state;
    if (hasCameraPermission === null) {
      return <View />;
    } else if (hasCameraPermission === false) {
      return <Text>No access to camera</Text>;
    } else {
      return (
        <Container style={{ flex: 1 }}>
         {/* <Header transparent>
          <Left>
          <Button transparent onPress={() =>this.props.navigation.navigate('Home') }>
           <Icon name='arrow-back' />
          </Button>
          </Left>
         
        </Header> */}
          <Camera style={{ flex: 1 }} type={this.state.type}>
            <View
              style={{
                flex: 1,
                backgroundColor: 'transparent',
                flexDirection: 'row',
                justifyContent:'space-between',
                width:"50%"
              }}>
              <TouchableOpacity
                style={{
                  //flex: 0.1,
                  alignSelf: 'flex-end',
                  alignItems: 'center',
                }}
                onPress={() => {
                  this.setState({
                    type: this.state.type === Camera.Constants.Type.back
                      ? Camera.Constants.Type.front
                      : Camera.Constants.Type.back,
                  });
                }}>
                <Text
                  style={{ fontSize: 18, marginBottom: 10, color: 'white' }}>
                  {' '}Flip{' '}
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={{
                 // flex: 0.1,
                  alignSelf: 'flex-end',
                  alignItems: 'center',
                }}
                onPress={()=>this.takePicture()}
               >
                <Text
                  style={{ fontSize: 18, marginBottom: 10, color: 'white' }}>
                  {' '}Take Picture{' '}
                </Text>
              </TouchableOpacity>
            </View>
          </Camera>
        </Container>
      );
    }
  }
}
```

**Comment by MirzaAhmadBilal** [comment]
`import React from 'react';
import { Text, View, TouchableOpacity } from 'react-native';
import { Camera, Permissions } from 'expo';
import {
    Container,
    
    Title,
    Content,
    Header,
    Button,
    Switch,
    Left,
    Body,
    Right,
    
    List,ListItem,Thumbnail,Footer,FooterTab
  } from "native-base";
  import {Icon} from 'react-native-elements';

export default class CameraEx extends React.Component {
    // static navigationOptions = {
    //     header: null
    // }
  state = {
    hasCameraPermission: null,
    type: Camera.Constants.Type.back,
    photo: null,
    photoId:''
  };

  async componentDidMount() {
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({ hasCameraPermission: status === 'granted' });
  }
  takePicture = async function() {
    // if (this.camera) {
    //     this.camera.takePictureAsync()
    //     alert(this.camera.takePictureAsync())
    //         .then(data => {
    //             FileSystem.moveAsync({
    //                 from: data.uri,
    //                 to: `${FileSystem.documentDirectory}photos/Photo_${
    //                     this.state.photoId
    //                 }.jpg`
                    
    //             }).then(() => {
                    
    //                 this.setState({
    //                     photoId: this.state.photoId + 1
    //                 });
    //                 Vibration.vibrate();
    //             });
    //         });
    // }
    this.camera.takePictureAsync({ skipProcessing: true }).then((data) => {
        this.setState({
            //takeImageText: "PICTURE TAKEN",
            photo: data.uri
        }, alert(data.uri))
    })
     
}
  


  render() {
    const { hasCameraPermission } = this.state;
    if (hasCameraPermission === null) {
      return <View />;
    } else if (hasCameraPermission === false) {
      return <Text>No access to camera</Text>;
    } else {
      return (
          
        <Container style={{ flex: 1 }}>
         {/* <Header transparent>
          <Left>
          <Button transparent onPress={() =>this.props.navigation.navigate('Home') }>
           <Icon name='arrow-back' />
          </Button>
          </Left>
         
        </Header> */}
          <Camera style={{ flex: 1 }} type={this.state.type}>
            <View
              style={{
                flex: 1,
                backgroundColor: 'transparent',
                flexDirection: 'row',
                justifyContent:'space-between',
                width:"50%"
              }}>
              <TouchableOpacity
                style={{
                  //flex: 0.1,
                  alignSelf: 'flex-end',
                  alignItems: 'center',
                }}
                onPress={() => {
                  this.setState({
                    type: this.state.type === Camera.Constants.Type.back
                      ? Camera.Constants.Type.front
                      : Camera.Constants.Type.back,
                  });
                }}>
                <Text
                  style={{ fontSize: 18, marginBottom: 10, color: 'white' }}>
                  {' '}Flip{' '}
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={{
                 // flex: 0.1,
                  alignSelf: 'flex-end',
                  alignItems: 'center',
                }}
                onPress={()=>this.takePicture()}
               >
                <Text
                  style={{ fontSize: 18, marginBottom: 10, color: 'white' }}>
                  {' '}Take Picture{' '}
                </Text>
              </TouchableOpacity>
            </View>
          </Camera>
        </Container>
      );
    }
  }
}`

**Comment by sjchmiela** [comment]
Hey! How do you know that the picture hasn't been taken?

In this function:
```js
  takePicture = async function() {this.camera.takePictureAsync({ skipProcessing: true }).then((data) => {
        this.setState({
            //takeImageText: "PICTURE TAKEN",
            photo: data.uri
        }, alert(data.uri))
    })    
}
```
You have a small bug — `setState` accepts a function as the second argument, and you've provided a statement — `alert(data.uri)`. To fix that, replace:
```diff
-        }, alert(data.uri))
+        }, () => alert(data.uri))
```

Let me know if this helped you solve your issue! 🙂

**Comment by MirzaAhmadBilal** [comment]
@sjchmiela  i said picture has been taken i got image url but i want when my picture has been taken my component must show image which i had taken ..how i can do that ??

**Comment by MirzaAhmadBilal** [comment]
@sjchmiela this is new issue i post 
https://github.com/expo/expo/issues/2686
and here i got image url when i clicked on take picture..what shuold i do next ??how i can show my capture image?

**Comment by sjchmiela** [comment]
Since you've submitted a new issue in place of this one I'll let myself consider this issue resolved. 🙂
