### ISSUE TITLE
[Expo 31][expo-gl][Android] Expo.GLView doesn't work on Android in SDK 31

### ISSUE THREAD

**Issue by serhiipalash** [expo/expo#2671]
### Environment

| software         | version
| ---------------- | -------
| expo | 31.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz
| device    | Pixel 2 XL, Nexus 5X

`exp diagnostics` output

<img width="1013" alt="screen shot 2018-11-09 at 3 01 52 pm" src="https://user-images.githubusercontent.com/14208343/48263943-7ce8e100-e430-11e8-8c0b-a8b46a606841.png">

App's target is Android Standalone

### Steps to Reproduce

To test Expo 31
```
git clone https://github.com/serhiipalash/test-glview-expo-31
cd test-glview-expo-31
yarn
expo start --android
```
You'll see this
<img width="1578" alt="screen shot 2018-11-09 at 2 51 59 pm" src="https://user-images.githubusercontent.com/14208343/48264047-de10b480-e430-11e8-957e-42cef90a0b9f.png">

To test Expo 30
```
git checkout -b sdk-30 origin/sdk-30
rm -rf node_modules
yarn
expo start --android -c
```
You'll see this
<img width="1581" alt="screen shot 2018-11-09 at 2 48 52 pm" src="https://user-images.githubusercontent.com/14208343/48264324-c259de00-e431-11e8-8b13-9a1f26d1e9a7.png">

### Expected Behavior

`Expo.GLView` should work both Android and iOS in SDK 31

### Actual Behavior

On Android `Expo.GLView` doesn't work for any shader both in Simulator and .apk. I tested it for more complex cases in our real app.

### Reproducible Demo

https://github.com/serhiipalash/test-glview-expo-31

ping @tsapeta

**Comment by tsapeta** [comment]
Hey @serhiipalash,
I've tried your example and yes, for some reason it doesn't work as it should. However, I've also tried our GLView examples in `native-component-list` app and they seem to work fine in SDK31.
I'll try to investigate what's going on here, but probably not before Monday 😞

**Comment by serhiipalash** [comment]
Hi @tsapeta ! Thanks!
Np, it can wait. We have one more blocking issue with `gl.texImage2D(...)` - it doesn't work in Android standalone app for any sdk. I was going to submit it next week.

**Comment by serhiipalash** [comment]
> I'll try to investigate what's going on here

I guess Android JSCore update broke something.

**Comment by ide** [comment]
JSC was updated for all SDK versions in the Expo client in Google Play.

**Comment by serhiipalash** [comment]
Thank you for fixing this @bbarthec !
