### ISSUE TITLE
[Expo50] Task 'background-fetch' is not defined. You must define a task using TaskManager.defineTask before registering.

### ISSUE THREAD

**Issue by nmalzieu** [expo/expo#26717]
### Minimal reproducible example

Private repo

### Summary

After upgrading to Expo50, without changing much else, I see errors, in Android & iOS, about my task not being defined

```
Task 'background-fetch' is not defined. You must define a task using TaskManager.defineTask before registering.
```

My code 

```
// Defined at root of my app

const BACKGROUND_FETCH_TASK = "background-fetch";

TaskManager.defineTask(BACKGROUND_FETCH_TASK, async () => {
  try {
    const hadTasks = await executeLogoutTasks();
    if (hadTasks) {
      return BackgroundFetch.BackgroundFetchResult.NewData;
    } else {
      return BackgroundFetch.BackgroundFetchResult.NoData;
    }
  } catch (e) {
    return BackgroundFetch.BackgroundFetchResult.Failed;
  }
});

// Called in a useEffect when app opened

export const registerBackgroundFetchTask = () => {
  return BackgroundFetch.registerTaskAsync(BACKGROUND_FETCH_TASK, {
    minimumInterval: 60 * 15, // 15 minutes
    stopOnTerminate: false, // android only,
    startOnBoot: true, // android only
  });
};

```

![Capture d’écran 2024-01-26 à 10 43 45](https://github.com/expo/expo/assets/2102342/90120a1b-ed5e-4eac-adb6-a1ae82cf6c38)
![Capture d’écran 2024-01-26 à 10 43 31](https://github.com/expo/expo/assets/2102342/904360ea-daf6-43ec-95fe-28558a53ab22)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 3.6.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.18.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /Users/noemalzieu/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.1 => 0.17.3
      @expo/webpack-config: ~19.0.1 => 19.0.1
      expo: ~50.0.3 => 50.0.3
      expo-router: ~3.4.5 => 3.4.5
      react: ^18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.7
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: bare

**Comment by nmalzieu** [comment]
I'm checking my code, and it seems that the TaskManager lib that my code uses is:
`node_modules/expo-task-manager/...`
while  `expo-background-fetch` uses a version in `node_modules/expo-background-fetch/node_modules/expo-task-manager`
I wonder if there is a version mismatch between the version I install (through npx expo install --fix) and the one referenced in `expo-background-fetch` ?

`expo-task-manager` installed via `npx expo install --fix` is `~11.7.1`
`expo-background-fetch` installed via `npx expo install --fix` is `~11.8.0` and its package.json references `"expo-task-manager": "~11.7.0"` => it should be compatible with any 11.7.x then, but it does install version 11.7.0 in its node_modules folder!

**Comment by brentvatne** [comment]
> I'm checking my code, and it seems that the TaskManager lib that my code uses is: `node_modules/expo-task-manager/...` while `expo-background-fetch` uses a version in `node_modules/expo-background-fetch/node_modules/expo-task-manager`
> 
> `expo-task-manager` installed via `npx expo install --fix` is `~11.7.1` `expo-background-fetch` installed via `npx expo install --fix` is `~11.8.0` and its package.json references `"expo-task-manager": "~11.7.0"` => it should be compatible with any 11.7.x then, but it still installs version 11.7.0 in expo-background-fetch's sub node_modules folder!
> 
> And since the `tasks` variable is just defined in `expo-task-manager`, even if my code detects it's defined, the background-fetch module code does not detect it's defined.
> 
> Adding a `resolutions` entry `"expo-task-manager": "~11.7.1"` for now fixes the issue. Still, I wonder why Yarn would install version 11.7.0 in expo-background-fetch's node_modules because there is the `~` ? Any idea?

thanks for the investigation! you're exactly right that this is the issue. I've published a fix in `expo-background-fetch@11.8.1`

**Comment by nmalzieu** [comment]
thanks @brentvatne - would you know why it would install a subversion while ~11.7.1 should be compatible with ~11.7.0 ?

**Comment by brentvatne** [comment]
@nmalzieu - that would likely have been due to your lockfile, and it would not have happened on a fresh install

**Comment by dhcmega** [comment]
Hi, I'm having the exactly same error with expo-background-fetch 11.8.1.
Almost the same sentry error too:

![image](https://github.com/expo/expo/assets/6719578/b0d6dc3e-b4d0-474c-aa92-24bb88467698)

**Comment by BrodaNoel** [comment]
@brentvatne I have the feeling that this issue is back

**Comment by BrodaNoel** [comment]
Fixed while doing:

```bash
rm -rf node_modules
rm yarn.lock
yarn install
```

The `expo-task-manager` was installed 2 times, breaking everything. (as the comments says above)
