### ISSUE TITLE
[Android] The binary version of its metadata is 1.8.0, expected version is 1.6.0.

### ISSUE THREAD

**Issue by DarrinRobertson** [expo/expo#26713]
### Summary

After upgrading to SDK 50 from 49, my builds fails with multiple warnings about classes xxx.
An example is:
Class 'kotlin.reflect.KClass' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

The same errors happen when doing an EAS build.
And for reference an EAS iOS build succeeds.

Build Log:
> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-screens', ':stripe_stripe-react-native'

> Task :expo-modules-core$android-annotation:compileKotlin FAILED
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.10/a61b182458550492c12aee66157d7b524a63a5ec/kotlin-stdlib-common-1.8.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (3, 23): Class 'kotlin.reflect.KClass' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KClass.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (5, 2): Class 'kotlin.annotation.Retention' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/Retention.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (5, 2): Class 'kotlin.annotation.AnnotationRetention' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/AnnotationRetention.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (5, 12): Class 'kotlin.annotation.AnnotationRetention' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/AnnotationRetention.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (5, 32): Class 'kotlin.annotation.AnnotationRetention' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/AnnotationRetention.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (6, 2): Class 'kotlin.annotation.Target' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/Target.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (6, 9): Class 'kotlin.annotation.AnnotationTarget' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/AnnotationTarget.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (6, 26): Class 'kotlin.annotation.AnnotationTarget' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/AnnotationTarget.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (6, 36): Class 'kotlin.annotation.AnnotationTarget' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/AnnotationTarget.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (6, 53): Class 'kotlin.annotation.AnnotationTarget' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/annotation/AnnotationTarget.class
e: C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\expo-modules-core\android-annotation\src\main\java\expo\modules\annotation\ConverterBinder.kt: (7, 45): Class 'kotlin.reflect.KClass' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from C:/Users/darri/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/reflect/KClass.class

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-modules-core$android-annotation:compileKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
22 actionable tasks: 3 executed, 19 up-to-date
Error: C:\Source\VSTS-Northcote\app\cote-rugby-app\android\gradlew.bat exited with non-zero code: 1
Error: C:\Source\VSTS-Northcote\app\cote-rugby-app\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at cp.emit (C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at Object.spawnAsync [as default] (C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Source\VSTS-Northcote\app\cote-rugby-app\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### What platform(s) does this occur on?

Android

### SDK Version

50.0.3

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ^50.0.3 => 50.0.3
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: bare

### Minimal reproducible example

Packages
  "dependencies": {
    "@expo/config-plugins": "~7.8.0",
    "@fortawesome/fontawesome-free": "^6.3.0",
    "@fortawesome/fontawesome-svg-core": "^6.3.0",
    "@fortawesome/free-brands-svg-icons": "^6.3.0",
    "@fortawesome/free-regular-svg-icons": "^6.3.0",
    "@fortawesome/free-solid-svg-icons": "^6.3.0",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@kichiyaki/react-native-barcode-generator": "^0.6.7",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/datetimepicker": "7.6.1",
    "@react-native-community/netinfo": "11.1.0",
    "@react-native-firebase/analytics": "18.7.3",
    "@react-native-firebase/app": "18.7.3",
    "@react-native-firebase/remote-config": "18.7.3",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.3",
    "@stripe/stripe-react-native": "~0.35.1",
    "accordion-collapse-react-native": "^1.1.1",
    "axios": "^1.5.0",
    "dayjs": "^1.11.10",
    "expo": "^50.0.3",
    "expo-asset": "~9.0.2",
    "expo-av": "~13.10.4",
    "expo-build-properties": "~0.11.0",
    "expo-clipboard": "~5.0.1",
    "expo-constants": "~15.4.5",
    "expo-dev-client": "~3.3.7",
    "expo-device": "~5.9.3",
    "expo-document-picker": "~11.10.1",
    "expo-file-system": "~16.0.5",
    "expo-font": "~11.10.2",
    "expo-haptics": "~12.8.1",
    "expo-image-manipulator": "~11.8.0",
    "expo-image-picker": "~14.7.1",
    "expo-insights": "~0.6.1",
    "expo-keep-awake": "~12.8.2",
    "expo-linking": "~6.2.2",
    "expo-localization": "~14.8.3",
    "expo-media-library": "~15.9.1",
    "expo-notifications": "~0.27.5",
    "expo-sharing": "~11.10.0",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-task-manager": "~11.7.1",
    "expo-updates": "~0.24.8",
    "formik": "^2.2.9",
    "i18next": "^23.5.1",
    "jwt-decode": "^3.1.2",
    "native-base": "^3.4.28",
    "react": "18.2.0",
    "react-barcode": "^1.4.6",
    "react-i18next": "^13.2.2",
    "react-native": "0.73.2",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-auth0": "^3.0.1",
    "react-native-confetti-cannon": "^1.5.2",
    "react-native-country-codes-picker": "^2.3.3",
    "react-native-fast-image": "^8.6.3",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-gradle-plugin": "^0.71.19",
    "react-native-reanimated": "~3.6.2",
    "react-native-reanimated-image-viewer": "^1.0.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-sensitive-info": "^5.5.8",
    "react-native-shadow-2": "^7.0.7",
    "react-native-share": "^8.2.2",
    "react-native-svg": "14.1.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-table-component": "^1.2.2",
    "react-redux": "^8.0.5",
    "reanimated-masonry-list": "^1.0.1",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "stream-chat-expo": "^5.17.1",
    "yup": "^1.1.1"
  },

**Comment by Chaseshaw** [comment]
same problem

**Comment by brentvatne** [comment]
```
Android gradle plugin: 7.4.2
Gradle: 7.5.1
```

React Native 0.73 / SDK 50 should be using AGP (Android gradle plugin) 8.2.1 - be sure to follow the instructions for upgrading your native project, given that you have a bare app: https://docs.expo.dev/bare/upgrade/?fromSdk=49&toSdk=50

**Comment by DarrinRobertson** [comment]
Thanks @brentvatne 
You were right. 
@Chaseshaw  FYI - I ran npx expo prebuild -clean. I had a few issues after that because I needed to add back some plugin and module settings, but the error messages led me to the answers. 
I am all going now.

**Comment by johhansantana** [comment]
Hello

I am having the same issue even though I am using `"expo": "^49.0.0",` and `"react-native": "0.72.6",`

here's the log:

```
/Users/johhansantana/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.10/a61b182458550492c12aee66157d7b524a63a5ec/kotlin-stdlib-common-1.8.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```

**Comment by hamswaldenkv** [comment]
This worked, thanks !

> Hello
> 
> I am having the same issue even though I am using `"expo": "^49.0.0",` and `"react-native": "0.72.6",`
> 
> here's the log:
> 
> ```
> /Users/johhansantana/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.10/a61b182458550492c12aee66157d7b524a63a5ec/kotlin-stdlib-common-1.8.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
> ```
> 
> I'm also using a bare react native project instead of an expo one.
> 
> iOS is working correctly.
> 
> EDIT:
> 
> I was able to run android by manually adding:
> 
> ```
>         kotlinVersion = "1.8.0"
> ```
> 
> to the root `build.gradle` under buildscript > ext
> 
> and adding
> 
> ```
>         classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0'
> ```
> 
> to the same file under buildscript > dependencies

**Comment by yucheng-Li** [comment]
I have face the some problem, The binary version of its metadata is 2.1.0, expected version is 1.8.0, at last i use **2.0.20** to solved this problem, other version about kotlinVersion is not work.
