### ISSUE TITLE
Empty array passed to SMS Addresses argument results in error on Android

### ISSUE THREAD

**Issue by AdamJNavarro** [expo/expo#2673]
Android should be able to accept an empty array like iOS so that developers can use the API with the intended use of only providing a pre-populated message and letting their users determine what recipients they want to send the message to manually. As per this forum post: https://forums.expo.io/t/expo-31-android-sms-error-executing-exported-method-sendsmsasync-on-module-exposms/15758

Repro Snack: https://snack.expo.io/@adamjnav/YW5kcm

**Comment by esamelson** [comment]
Looks like this was fixed by the commit referenced above ^, closing
