### ISSUE TITLE
expo prebuild and run:android suddenly stopped working

### ISSUE THREAD

**Issue by troyshu** [expo/expo#26739]
### Minimal reproducible example

https://github.com/troyshu/expo-50-androidmanifest

### Summary

**Describe the bug**
`npx expo prebuild` and `npx expo run:android` commands suddenly started failing with errors for me (Expo 50). `npx expo run:ios` runs fine.

`npx expo prebuild` produces:

```
Error: [android.manifest]: withAndroidManifestBaseMod: A runtime version is set in your AndroidManifest.xml, but is missing from your app.json/app.config.js. Please either set runtimeVersion in your app.json/app.config.js or remove expo.modules.updates.EXPO_RUNTIME_VERSION from your AndroidManifest.xml.
```

`npx expo run:android` produces:

```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: /Users/troyshu/Documents/projects/.../expo-50-androidmanifest/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml:3: AAPT: error: resource color/iconBackground (aka com.expo50androidmanifest:color/iconBackground) not found.

     ERROR: /Users/troyshu/Documents/projects/.../expo-50-androidmanifest/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml:3: AAPT: error: resource color/iconBackground (aka com.expo50androidmanifest:color/iconBackground) not found.
```

**To Reproduce**
1. Clone https://github.com/troyshu/expo-50-androidmanifest
2. Run `npx expo prebuild` and `npx expo run:android`

My sample repo is simply a new Expo project created with `npx create-expo-app`.

**Expected behavior**
`npx expo prebuild` and `npx expo run:android` to run without error in a brand new Expo project.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 34
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.4 => 50.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    npmGlobalPackages:
      eas-cli: 6.1.0
    Expo Workflow: bare

**Comment by brentvatne** [comment]
hi @troyshu - thanks for the report. there was briefly a version of the prebuild template that included a patch that was accidentally brought in through a merge conflict. i published a fix for that 2 hours ago, but it's possible have it cached. try running `rm -rf ~/.expo/template-cache`

with your repository, it worked for me after running `npx expo prebuild -p android --clean` for a second time (so the new version of the template was used)

i believe this is fixed, let me know if it isn't for you and i'll reopen

**Comment by troyshu** [comment]
That did the trick @brentvatne! Thank you for the quick fix and all your hard work. Loving what you all are doing at Expo 💪

**Comment by raci-aivy** [comment]
I continue to get the error from above after upgrading to Expo SDK 51

`eas build --profile development-simulator --platform android`

Run gradlew failed with:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> Android resource linking failed
     ERROR: /home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml:11:7-37: AAPT: error: attribute 'android:pathPrefix' in <data> tag has value of '*', it must start with a leading slash '/'.
         
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org/.
BUILD FAILED in 5m 32s

Can anyone suggest me how to proceed here?!

**Comment by Gorynych** [comment]
I have the same problem.

`eas build --profile development --platform android`

```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: /home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml:3: AAPT: error: resource color/iconBackground (aka com.step:color/iconBackground) not found.
         
     ERROR: /home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml:3: AAPT: error: resource color/iconBackground (aka com.step:color/iconBackground) not found.
```

**Comment by goldfishdevs** [comment]
> I continue to get the error from above after upgrading to Expo SDK 51
> 
> `eas build --profile development-simulator --platform android`
> 
> Run gradlew failed with: Execution failed for task ':app:processDebugResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> > Android resource linking failed
> > ERROR: /home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml:11:7-37: AAPT: error: attribute 'android:pathPrefix' in  tag has value of '*', it must start with a leading slash '/'.
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org/.
> > BUILD FAILED in 5m 32s
> 
> Can anyone suggest me how to proceed here?!

I have the same problem. Can anyone suggest me how to proceed here?

**Comment by troyshu** [comment]
For the people above who seem to have the same issue but with Expo 51: please create a minimum reproducible example (i.e. start a blank new Expo 51 project) and attach it to a brand new issue. You're way more likely to get help from the Expo devs that way.

**Comment by ademhatay** [comment]
> I have the same problem.
> 
> `eas build --profile development --platform android`
> 
> ```
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
>    > Android resource linking failed
>      ERROR: /home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml:3: AAPT: error: resource color/iconBackground (aka com.step:color/iconBackground) not found.
>          
>      ERROR: /home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml:3: AAPT: error: resource color/iconBackground (aka com.step:color/iconBackground) not found.
> ```

did u find anything? same problem but no answer on anywhere

  > Android resource linking failed
ERROR: /home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml:4: AAPT: error: resource mipmap/ic_launcher_foreground (aka com.entechno.entechnomobile:mipmap/ic_launcher_foreground) not found.
         
     ERROR: /home/expo/workingdir/build/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml:4: AAPT: error: resource mipmap/ic_launcher_foreground (aka com.entechno.entechnomobile:mipmap/ic_launcher_foreground) not found.
