### ISSUE TITLE
POST does not working when using with-router expo app.

### ISSUE THREAD

**Issue by AndrianarivoAlpha** [expo/expo#26755]
### Minimal reproducible example

https://github.com/AndrianarivoAlpha/router-problem

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hello, I need a help please,
My problem is that POST does not working when I make a call when using expo-router/entry (under app folder) but it works fine in a normal app (in App.js).
 P.S: GET works fine.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ^50.0.1 => 50.0.4 
      expo-router: ~3.4.6 => 3.4.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Your reproduction is current invalid and does not demonstrate your issue. Once the repo is updated, please reply and I'll re-open the issue and investigate further

**Comment by AndrianarivoAlpha** [comment]
Hello, I resloved the problem, 
I forgot Curly braces of the object.
I post my like :
await axios
			.post(
				"http://192.168.88.14:6600/api/search",
				search,
				{
					headers: {
						"Content-Type": "application/json",
						Authorization: `Bearer ${token}`,
					},
					timeout: 5000,
				}
			)

instead of : 

await axios
			.post(
				"http://192.168.88.14:6600/api/search",
				{ search },
				{
					headers: {
						"Content-Type": "application/json",
						Authorization: `Bearer ${token}`,
					},
					timeout: 5000,
				}
			)
