### ISSUE TITLE
[Expo-Camera] Random reading barcode type-39 with Expo-Camera

### ISSUE THREAD

**Issue by odexvy** [expo/expo#26759]
### Minimal reproducible example

https://github.com/odexvy/issueExpoCameraBarcodeReading

### Summary

# Issue

To reproduce the problem, scan with Expo Camera a type-39 barcode with consecutive identical digits.
Example ```ERUUUUU3```.

https://barcode.tec-it.com/en/Code39?data=ERUUUUU3

Also tested in Excel with the ```Libre Barcode 39``` font (see in video bellow)

onBarCodeScanned data result is randomly :
* ```ERUUUUU3``` 
* ```ERUUUU3```
* ```ERUUU3```.

This only happens when a barcode with identical consecutive numbers is scanned; a barcode like ```ER123456``` works perfectly.

Tried with 2 project one with sdk48 and another with sdk50

Tested this barcode(```ERUUUUU3```) with zxing-js library and there is no problem ( on this testing web page https://zxing-js.github.io/library/examples/multi-camera/ )

# Video example

https://github.com/expo/expo/assets/12870342/5f9c9a43-df30-4476-bd0c-108f3ad6527c

### Environment

# expo-env-info 1.2.0 environment info:

    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh

    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm

    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod

    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2

    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild

    npmPackages:
      @expo/metro-config: 0.10.0 => 0.10.0 
      expo: ~50.0.3 => 50.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 

    Expo Workflow: managed

**Comment by Reggionick** [comment]
This issue is still present, also on expo-camera 16.x

@odexvy have you found any solution or similar for this?

**Comment by odexvy** [comment]
@Reggionick sadly no, the problem is still present in our application too but i think it's a bug on lower level code than expo's camera dependency. I was wondering if it would work better with the new architecture and SDK 53 but apparently not.
