### ISSUE TITLE
Error with "Expected `fromDir` to be of type `string`, got `undefined`"

### ISSUE THREAD

**Issue by C2Tx420** [expo/expo#26753]
### Minimal reproducible example

https://expo.dev/accounts/c2tx420/projects/Trekn-Native/builds/0cb1984c-9613-4375-8967-7746eb731801

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

TypeError: /home/expo/workingdir/build/node_modules/expo-router/_ctx.android.tsx: Expected `fromDir` to be of type `string`, got `undefined`
I have this issue (android + ios) but before i don't have this. Anyone know how to fix this ?

### Environment

System:
      OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.16.0/bin/yarn
      npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    npmPackages:
      expo: ^49.0.3 => 49.0.22
      expo-router: ^2.0.0 => 2.0.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    npmGlobalPackages:
      eas-cli: 7.1.1
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by trymbill** [comment]
I'm seeing the same thing after updating from SDK 49 and Expo Router 2 to SDK 50 and Expo Router 3. Did you manage to find the root cause @C2Tx420?

**Comment by AbdelhakimMhioul** [comment]
This is bugging me still, I wonder if there is a fix for this : @trymbill @C2Tx420 , thank you in advance

**Comment by trymbill** [comment]
I ended up removing Sentry from my `metro.config.js`, which revealed another error that I think Sentry was masking. So I fixed that error, re-added Sentry to my metro config and that worked.

I'd recommend making your `metro.config.js` and babel configs as basic as possible, see if that reveals any errors and then slowly adding back config changes to metro and babel.

**Comment by guillempuche** [comment]
I also have this issue and don't have Sentry

**Comment by ayonshafiul** [comment]
Facing the same issue after updating from sdk v49 to 50

**Comment by Stancobridge** [comment]
facing this error, just upgraded from `~49.0.18` to `49.0.23`

**Comment by TheoOliveira** [comment]
I don't think they are going to reopen because i have it's based on node 18 and up. I am trying to deploy this to amplify but i still got this error.

**Comment by Ezejaemmanuel** [comment]
i am getting the same error when i upgraded from node 18 to node 20 .....does it mean that my node version is causing it or what

**Comment by jaredstrong89** [comment]
I am new to expo, starting this project with the create-expo-app command. I am getting this same error on my Android and IOS virtual devices, and my physical Android device.

Developing on Mac M1 with Node version 20.12.2.

`npx create-expo-app@latest`

It seems that expo-router is the source of the issue. I am able to run a separate expo repo that does not have expo-router installed.
