### ISSUE TITLE
Inline modal restriction of slide down to dismiss

### ISSUE THREAD

**Issue by craigs** [expo/expo#26757]
### Minimal reproducible example

https://github.com/craigs/expo-modal-dismiss-slide-restriction

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

There are two mechanisms to be able to display modals. 

- The first is as a routable page (see https://docs.expo.dev/router/advanced/modals/)
- The second is as an inline modal using the React Native Modal component (see https://docs.expo.dev/tutorial/create-a-modal/)

There is a difference in behaviour in the slide to dismiss. Using a routable page with expo router allows you to fully slide down to dismiss the modal. Using the inline modal, the slide to dismiss is restricted in how far you can slide the modal down.

Demonstration

- with expo router (blue modal)
- with inline modal (green modal)

https://github.com/expo/expo/assets/229310/3ea308fa-1a67-4d69-b10f-ee96d49ad422

Is there any way to have the inline modal behave the same way as the expo router modal? I would be grateful for any clues.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.6.0 - ~/.local/share/rtx/installs/node/18.6.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 8.13.2 - ~/.local/share/rtx/installs/node/18.6.0/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.4 => 50.0.4
      expo-router: ~3.4.6 => 3.4.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
This is a restriction of the core React Native `<Modal />` component.

For reference, Expo Router uses the React Navigation modal, as its more flexible that the core component.

React Native's core components are generally simplistic (e.g `<Button />`), so it doesn't suite your needs to may have to use a 3rd party component.
