### ISSUE TITLE
Unable to determine Biometric Security Level

### ISSUE THREAD

**Issue by richmondp** [expo/expo#26777]
### Minimal reproducible example

https://snack.expo.dev/@prichmond/thankful-blue-mixed-nuts

### Summary

As per the details outlined in [this issue](https://github.com/expo/expo/issues/26615) I am aware that Android Keystore requires Strong Biometric authentication and that the current `isEnrolledAsync` function only checks for BIOMETRIC_WEAK (e.g. Face Recognition on most Android devices). 

If we are unable to determine the level of biometric enrolment before making calls to SecureStore which require strong biometrics, it makes it hard to prevent errors from occurring. 

Is it possible to update the existing `isEnrolledAsync` to allow a parameter to specify the level of biometrics you are checking, or create a new function to determine the user's current level? 

### Environment

expo-env-info 1.2.0 environment info:
System:
OS: macOS 14.2.1
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.18.0 - ~/Library/Caches/fnm_multishells/95796_1705881749006/bin/node
Yarn: 1.22.21 - /opt/homebrew/bin/yarn
npm: 9.8.1 - ~/Library/Caches/fnm_multishells/95796_1705881749006/bin/npm
Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.14.3 - /Users/peterrichmond/.rvm/gems/ruby-3.0.5/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8193401
Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
expo: ^48.0.21 => 48.0.21
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.71.14 => 0.71.14
react-native-web: ~0.18.12 => 0.18.12
Expo Workflow: managed

**Comment by behenate** [comment]
@richmondp Hi! I think this PR https://github.com/expo/expo/pull/26767 will solve your issue, it will allow to check if it is possible to save a value with `requireAuthentication` without using `expo-local-authentication` 😄
