### ISSUE TITLE
Production build fails on app open

### ISSUE THREAD

**Issue by vlepapontis** [expo/expo#26771]
### Summary

We are using expo-dev-client for almost 2 years now. From January 19th 2024, every production build we make fails immediately on app open. We are using this command for almost 2 years now `eas build --platform ios --non-interactive`, build is successful, everything looks good, but when we install app from TestFlight, it crashes immediately. It works perfectly in dev environment. We also tried with `"expo-dev-client": "~3.3.7"`, but result is the same.

After that, we created new test app with `npx create-expo-app`, installed `"expo-dev-client": "~3.3.7"` but we got the same result.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

  "dependencies": {
    "@expo/config-plugins": "~7.2.2",
    "@expo/prebuild-config": "~6.2.4",
    "@expo/vector-icons": "^13.0.0",
    "@gorhom/bottom-sheet": "^4.4.6",
    "@microsoft/signalr": "^7.0.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/checkbox": "^0.5.15",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/analytics": "^17.4.2",
    "@react-native-firebase/app": "^17.4.2",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "@react-navigation/stack": "^6.2.3",
    "@sentry/react-native": "5.10.0",
    "@shopify/flash-list": "1.4.3",
    "axios": "^0.27.2",
    "country-list-with-dial-code-and-flag": "^3.0.2",
    "dotenv": "^16.0.3",
    "eas": "^0.1.0",
    "events": "^3.3.0",
    "expo": "49.0.10",
    "expo-application": "~5.3.0",
    "expo-build-properties": "~0.8.3",
    "expo-constants": "~14.4.2",
    "expo-contacts": "~12.2.0",
    "expo-dev-client": "~2.4.12",
    "expo-device": "~5.4.0",
    "expo-font": "~11.4.0",
    "expo-haptics": "~12.4.0",
    "expo-image": "~1.3.5",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-local-authentication": "~13.4.1",
    "expo-localization": "~14.3.0",
    "expo-location": "~16.1.0",
    "expo-notifications": "~0.20.1",
    "expo-secure-store": "~12.3.1",
    "expo-sharing": "~11.5.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.17",
    "expo-web-browser": "~12.3.2",
    "lottie-react-native": "5.1.6",
    "md5": "^2.3.0",
    "mobx": "^6.6.1",
    "mobx-react": "^7.6.0",
    "mobx-react-lite": "^3.4.0",
    "moment": "^2.29.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.5",
    "react-native-appsflyer": "^6.12.2",
    "react-native-collapsible": "^1.6.0",
    "react-native-date-picker": "^4.2.8",
    "react-native-dialog": "^9.3.0",
    "react-native-element-dropdown": "^2.10.0",
    "react-native-error-boundary": "^1.2.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-modal": "^13.0.1",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-select-dropdown": "^3.1.0",
    "react-native-svg": "13.9.0",
    "react-native-ux-cam": "^5.4.11",
    "react-native-vector-icons": "^9.2.0",
    "react-native-version-check-expo": "^3.4.7",
    "react-native-view-shot": "3.7.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.2.2",
    "sentry-expo": "~7.1.0"
  }

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nodenv/versions/16.17.1/bin/node
      Yarn: 1.22.21 - ~/.nodenv/versions/16.17.1/bin/yarn
      npm: 8.15.0 - ~/.nodenv/versions/16.17.1/bin/npm
    Managers:
      CocoaPods: 1.15.0 - /.../.gem/ruby/3.2.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: 49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed
```

### Reproducible demo

Link to demo app:
[https://github.com/vlepapontis/min-expo-demo](https://github.com/vlepapontis/min-expo-demo)

### Stacktrace (if a crash is involved)

![Screenshot 2024-01-22 at 13 05 50](https://github.com/expo/expo/assets/130092131/ca434592-3245-4c2b-a024-f801fb8ad3a2)

**Comment by vlepapontis** [comment]
@expo-bot why would you close it, demo and all description is there?

**Comment by brentvatne** [comment]
@vlepapontis - the repository you shared is not a minimal reproducible example, it does not reproduce the issue

i'm also not sure what the `eas` dependency is in the package.json. that is not eas-cli: https://www.npmjs.com/package/eas

**Comment by klendi** [comment]
I think I have this exact issue too, it may be related to some native changes we need to make to pbxproj file or something

**Comment by brentvatne** [comment]
@klendi - please open an issue with a minimal reproducible example. see https://github.com/expo/expo/issues/26771#issuecomment-1915414232 for more info
