### ISSUE TITLE
[SDK 50] [expo-router] Can't find source-maps when using `pnpm` monorepo

### ISSUE THREAD

**Issue by helmturner** [expo/expo#26787]
### Minimal reproducible example

https://github.com/helmturner/Expo-bug

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

## Steps to reproduce

1. Create a `pnpm` workspace with a subdirectory containing an Expo app
2. Follow the [manual setup directions](https://docs.expo.dev/router/installation/#manual-installation) for `expo-router`
3. Follow the [directions for setting up a monorepo](https://docs.expo.dev/guides/monorepos/) in the Expo documentation
    - [Modify the Metro config](https://docs.expo.dev/guides/monorepos/#modify-the-metro-config):
        ```js
        // metro.config.js:

        const path = require("path");
        const { getDefaultConfig } = require("expo/metro-config");

        const projectRoot = __dirname;
        const workspaceRoot = path.resolve(__dirname, "../..");

        const config = getDefaultConfig(projectRoot);

        config.watchFolders = [workspaceRoot],

        config.resolver.nodeModulesPaths = [
          path.resolve(projectRoot, "node_modules"),
          path.resolve(workspaceRoot, "node_modules"),
        ]

        module.exports = config;
        ```
    - Prepend the `run` command with `EXPO_USE_METRO_WORKSPACE_ROOT=1` as described in [Change the default entrypoint](https://docs.expo.dev/guides/monorepos/#change-default-entrypoint)
        ```jsonc
        // package.json:

        {
        /* ... */
        "scripts": {
            "ios": "EXPO_USE_METRO_WORKSPACE_ROOT=1 expo run:ios",
            "android": "EXPO_USE_METRO_WORKSPACE_ROOT=1 expo run:android",
            }
        /* ... */
        }
        ```
    - Add `node-linker=hoisted` to `.npmrc` at the root of the monorepo as described in [Can I use another Monorepo tool?](https://docs.expo.dev/guides/monorepos/#can-i-use-another-monorepo-tool-instead-of-yarn-workspaces)
        ```ini
        # .npmrc:

        node-linker=hoisted
        ```
4. Install `expo-dev-client` in the Expo app
    ```sh
    cd apps/expo
    pnpm i expo-dev-client
    ```
5. run `pnpm i` in the monorepo root
6. run either `pnpm ios` or `pnpm android` to create and launch a development build
7. Open the debugger and observe the error
8. Click any of the links in the error message to see the resolution error

## Expected behavior

Source-maps (and by extension, the debugger) should just work.

## Actual behavior

The debugger gets a 404 error when trying to load the source-map.

![](https://raw.githubusercontent.com/helmturner/Expo-bug/main/screenshots/actual.png)

## Workaround

Recalling a fix for an older bug, I was able to work around the issue as follows:
 - Create an `index.ts` file in the app's root directory (or `index.js`, etc)
 - Add the following single line:
    ```ts
    import "expo-router/entry";
    ```
 - Update package.json#main to point to the new file
    ```jsonc
    {
    "main": "index.ts",
    /* ... */
    }
    ```

### Environment

```sh

expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 14.3
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK:
      API Levels: 30, 31, 33, 34
      Build Tools: 30.0.3, 31.0.0, 33.0.0, 34.0.0
      System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  npmGlobalPackages:
    eas-cli: 7.1.1
  Expo Workflow: managed
```

**Comment by LightBounded** [comment]
I'm also having this issue the workaround works wonders!

**Comment by isnolan** [comment]
+1

**Comment by AprilNEA** [comment]
Same issue and workaround works!

**Comment by brentvatne** [comment]
hey there! currently, [we only commit to supporting yarn classic for monorepos](https://docs.expo.dev/guides/monorepos/): 

> We currently have first-class support for [Yarn 1 (Classic)](https://classic.yarnpkg.com/lang/en/) workspaces. If you want to use another tool, make sure you know how to configure it.

we are working on improving support for other package managers / monorepo tools, and you can likely get them working if you're intimately familiar with them, but we can't provide hands-on assistance in debugging issues for them yet.

if you narrow down the root cause to a bug in expo tools, we would appreciate a pull request to fix it!

**Comment by ibash** [comment]
Thanks @helmturner, you're the best!

**Comment by helmturner** [comment]
> hey there! currently, [we only commit to supporting yarn classic for monorepos](https://docs.expo.dev/guides/monorepos/): 
> 
> > We currently have first-class support for [Yarn 1 (Classic)](https://classic.yarnpkg.com/lang/en/) workspaces. If you want to use another tool, make sure you know how to configure it.
> 
> we are working on improving support for other package managers / monorepo tools, and you can likely get them working if you're intimately familiar with them, but we can't provide hands-on assistance in debugging issues for them yet.
> 
> if you narrow down the root cause to a bug in expo tools, we would appreciate a pull request to fix it!

I totally get that, but to be fair, there is a section in the docs on how to use other package managers. While explicit support is out of scope, perhaps that section can be updated with this workaround? Happy to PR that change.

**Comment by ibash** [comment]
IMO this would be great to have in the monorepo docs, maybe under common issues? https://docs.expo.dev/guides/monorepos/

I'm using a bun monorepo fwiw.
