### ISSUE TITLE
[expo-location] Background location crash

### ISSUE THREAD

**Issue by MenamAfzaal** [expo/expo#26782]
### Minimal reproducible example

https://github.com/frizhub-repo/crash_reports.git

### Summary

#Steps To Reproduce

The problem is not present in debug mode; it's specifically happening in production.
Based on your Crashlytics report these are the stats

<img width="1786" alt="Screenshot 1402-11-10 at 10 26 26 AM" src="https://github.com/expo/expo/assets/122887940/637ce746-9e47-4185-a000-ac11e754102e">

<img width="1497" alt="Screenshot 1402-11-10 at 10 29 12 AM" src="https://github.com/expo/expo/assets/122887940/4e49f346-bffb-42b9-93ca-bd34f3be6560">
 
Logs show app is crashing on random places sometimes when app is mounted sometimes on other events

<img width="1388" alt="Screenshot 1402-11-10 at 10 31 18 AM" src="https://github.com/expo/expo/assets/122887940/4712e9f6-8205-4f47-ab7e-4fb3b0ae30f8">

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.6.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.22 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    Expo Workflow: bare

**Comment by brentvatne** [comment]
hi there! can you explain how to reproduce it in the repo that you provided? we need steps to follow to reliably cause the crash.

**Comment by MenamAfzaal** [comment]
@brentvatne 
The problem doesn't occur in debug mode; it's specific to the production environment. When the app is in the background state, it crashes randomly. The timing of the crashes is inconsistent — sometimes it happens immediately after going to the background, while other times it remains stable for hours.

**Comment by MenamAfzaal** [comment]
@brentvatne 
The problem occurs without any identifiable steps for reproduction. It seems to happen at random intervals, and I'm unable to determine the cause.
