### ISSUE TITLE
IOS: Google.logInAsync gives error: "Your app is missing support for the following URL schemes: com.googleusercontent.apps......."

### ISSUE THREAD

**Issue by AkshitSahani** [expo/expo#2678]
### Environment

Environment:
  OS: OS X Yosemite 10.10.5
  Node: 10.3.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^31.0.4 => 31.0.4
  react: 16.5.0 => 16.5.0
  react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/akshitsahani-0c80106a-19db-4640-b42d-8cfe18dd337d.tar.gz

App target is Expo Client. 

### Steps to Reproduce

1. Follow the steps outlined in the iOS section of https://docs.expo.io/versions/v31.0.0/sdk/google.
2. Run app and click on button to trigger Google.logInAsync.
3. This was working perfectly fine until I upgraded to Expo v31. 

### Expected Behavior

On button press, the app should bring the google login page on WebView where you are able to provide credentials and log into google to authenticate the app.

### Actual Behavior

When you tap on the button that triggers Google.logInAsync, you see a red screen with the following error: 

"Exception 'You app is missing support for the following URL schemes: com.googleusercontent.apps.{{MY_CLIENT_ID}}' was thrown while invoking logInAsync on target ExponentGoogle with params ( 
{OBJECT CONTAINING ANDROIDCLIENTID, IOSCLIENTID AND AN ARRAY OF SCOPES}
)"

### Reproducible Demo

https://snack.expo.io/@akshitsahani/ranting-edamame

NOTE: In the snack above, I have modified the androidClientId and iosClientId keys for obvious reasons (so the snack might not actually work, but will give you an idea of exactly what I am doing to trigger Google.logInAsync)

P.S. After a lot of research, I think I have an idea of what needs to be done to fix this issue. I went through a lot of different instances of this issue that native iOS developers implementing google sign in were facing and the steps are outlined at the bottom of the following link:

https://developers.google.com/identity/sign-in/ios/start-integrating

Read the Add a URL scheme to your project section. I believe those steps should take care of it, since you guys are handling the Xcode side for us.

Thanks

**Comment by EvanBacon** [comment]
I am currently in the process of rewriting this module, in the newest version of `GoogleSignIn` you need to include the reverse `CLIENT_ID` in the iOS `info.plist`. On Android you will need to define the value in a custom `GoogleService.json`. This means that native iOS Google Sign-In will only work in Standalone. 
I think you could include the URI Scheme like so: 

[Editing info.plist](https://docs.expo.io/versions/latest/distribution/app-stores#system-permissions-dialogs-on-ios)
`app.json`
```json
{
  "expo": {
    "ios": {
       "infoPlist": {
        "CFBundleURLTypes": [
         {
            "CFBundleTypeRole": "Editor",
            "CFBundleURLName": "GoogleSignIn",
            "CFBundleURLSchemes": ["YOUR_REVERSE_CLIENT_ID"]
          }
        ]
      }
    }
  }
}
```

CC @fson is this `infoPlist` approach possible?

**Comment by thehungrycoder** [comment]
Thanks @AkshitSahani for creating this issue. Based on suggestion on the forum, I came to create the issue and found  you've already created. I'm also facing same issue and looks like i already have `ios.config.googleSignIn.reservedClientId` setup but that's for standalone. Initial complain I get in expo client.

**Comment by LaszloDev** [comment]
Is this related?
https://github.com/expo/expo/issues/1053

**Comment by nturk19** [comment]
> Is this related?
> #1053

Tried the steps found there and couldn't get `Google.logInAsync` to work at all for iOS. Tried all posts above as well.

I'm specifying my `iosClientId` as shown in the Expo documentation for `Google.logInAsync` ([https://docs.expo.io/versions/latest/sdk/google.html#using-it-inside-of-the-expo-app]). In `app.json`,  I am specifying the same `iosClientId` but reversed for `ios.config.googleSignIn.reservedClientId`.

For iOS, does Google.logInAsync only work for standalone apps?

Note: Google Sign-In on Android is working perfectly fine for me.

**Comment by planetClaire** [comment]
I found that adding behavior: 'web' to the options resolved this error for the Expo app although this should be default according to docs.

**Comment by thehungrycoder** [comment]
> I found that adding behavior: 'web' to the options resolved this error for the Expo app although this should be default according to docs.

Yes it works with `web` as I posted in https://forums.expo.io/t/google-sign-in-issue-on-sdk-31/15741?u=rajuru

**Comment by AkshitSahani** [comment]
@nturk19 as the solutions provided above, for the expo client, google sign in will work if you set behavior: web in your Google.logInAsync argument object. 

And without behavior: web, currently it will only work for standalone apps.

**Comment by chrisbull** [comment]
That's great and all that `behavior: 'web'` works, but we really should have the ability to use native. Something like 'react-native-google-signin' is fantastic, but of course, has to be linked. 
Would be great if Expo could integrate this for us.

**Comment by EvanBacon** [comment]
native will only ever be available from standalone as you need to configure a custom URI scheme at build-time.
The newly merged [`expo-google-sign-in`](https://github.com/expo/expo/tree/master/packages/expo-google-sign-in) is far more robust than `react-native-google-sign-in`. After I merge the OAuth module, I will rewrite Expo.Google to use both of these modules. But regardless, native will still only be accessible from standalone. This is due to a change that Google made in their library that throws an error if the `REVERSE_CLIENT_ID` is not present as a linking URI in the iOS `info.plist`.

**Comment by mohsinnaqvi110** [comment]
> > Is this related?
> > #1053
> 
> Tried the steps found there and couldn't get `Google.logInAsync` to work at all for iOS. Tried all posts above as well.
> 
> I'm specifying my `iosClientId` as shown in the Expo documentation for `Google.logInAsync` (https://docs.expo.io/versions/latest/sdk/google.html#using-it-inside-of-the-expo-app). In `app.json`, I am specifying the same `iosClientId` but reversed for `ios.config.googleSignIn.reservedClientId`.
> 
> For iOS, does Google.logInAsync only work for standalone apps?
> 
> Note: Google Sign-In on Android is working perfectly fine for me.

Please can you share, How did you define iosClientId in app.json

I am trying like this

>     "ios": {
      "bundleIdentifier": "com.abc",
      "reservedClientId": "986416512357-bcssirf57sa2q5lkmga8t4tmnvj5va98.apps.googleusercontent.com"
    },

But does not works.

**Comment by mohsinnaqvi110** [comment]
Finally this is the proper solution

>     "ios": {
      "bundleIdentifier": "com.abc",
      "config": {
        "googleSignIn": {
          "reservedClientId": "986326213957-bcssirf57sa2q5lkmga8t4tmnvj5va98.apps.googleusercontent.com"
        }
      }
    },

**Comment by mohsinnaqvi110** [comment]
Finally this is the proper solution
 `    "ios": {
      "bundleIdentifier": "com.abc",
      "config": {
        "googleSignIn": {
          "reservedClientId": "981216523117-bcssirf57sa2q5lkmga8t4tmnvj5va98.apps.googleusercontent.com"
        }
      }
    },`

**Comment by mohsinnaqvi110** [comment]
Finally this is the proper solution

> "ios": { "bundleIdentifier": "com.abc", "config": { "googleSignIn": { "reservedClientId": "981216523117-bcssirf57sa2q5lkmga8t4tmnvj5va98.apps.googleusercontent.com" } } },

**Comment by mohsinnaqvi110** [comment]
Finally this is the proper solution

>     "ios": {
       "bundleIdentifier": "com.abc",
       "config": {
        "googleSignIn": {
          "reservedClientId": "YOUR CLIENT ID"
        }
      }
    },

**Comment by mohsinnaqvi110** [comment]
Finally this is the proper solution

>     "ios": { 
>       "bundleIdentifier": "com.abc",
>       "config": {
>        "googleSignIn": {
>         "reservedClientId": "YOUR CLIENT ID"
>        }
>      }
>    },
>

**Comment by mohsinnaqvi110** [comment]
Finally this is the proper solution

>     "ios": { 
>       "bundleIdentifier": "com.abc",
>       "config": {
>        "googleSignIn": {
>         "reservedClientId": "YOUR CLIENT ID"
>        }
>      }

**Comment by mohsinnaqvi110** [comment]
This solution doesn't work. No effect still the same.

**Comment by amsimoes** [comment]
@mohsinnaqvi110 are you testing it inside Expo or in a standalone app?

**Comment by mohsinnaqvi110** [comment]
inside Expo

**Comment by mohsinnaqvi110** [comment]
Solution is:

>       const result = await Google.logInAsync({
>         androidClientId: '986411233957-9gu0o0j9odu2f77u9afji6evrss0lpqo.apps.googleusercontent.com',
>         iosClientId: '986411233957-bcssirf57sa2q5lkmga8t4tmnvj5va98.apps.googleusercontent.com',
>         scopes: ['profile', 'email'],
>         behavior: 'web',
>       });
>

**Comment by hellohellosharp** [comment]
@EvanBacon I am using Android and getting a similar error. I don't think AppAuth is loading URLSchemes correctly (I followed your article linked above).

app.json:


```
"expo": {
    "name": "My project",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",

   ...

    "android": {
      "package": "com.xxxx.myproject",
      "googleServicesFile": "./app/google-services.json"
    }
  }
```

Code:
```
import { AppAuth } from 'expo-app-auth';
console.log(AppAuth);
    //Check URLSchemes

    const config = {
        issuer: 'https://accounts.google.com',
        clientId: GoogleWebID,
        scopes: ['profile'],
    };

    const tokenResponse = await AppAuth.authAsync(config);
    console.log(tokenResponse);
```
console.log(AppAuth) Result:
```
Object {
  "OAuthRedirect": "host.exp.exponent",
  "URLSchemes": undefined,
  "authAsync": [Function authAsync],
  "refreshAsync": [Function refreshAsync],
  "revokeAsync": [Function revokeAsync],
}
```
Executing the code redirects me to a web browser where I have the "Custom scheme URIs are not allowed". Shows the "host.exp.exponent/oauth..." redirect uri.

**Comment by cruzach** [comment]
I've tested the `Google.logInAsync` behavior across both platforms, in standalones as well as in the Expo client for SDK 35, and when following the docs exactly in regards to configuring clientIds for each case, it works without a hitch. 

Also, since it seems to be relevant to this issue- the [GoogleSignIn](https://docs.expo.io/versions/latest/sdk/google-sign-in/) library provides native Google Sign-In functionality for standalone Expo apps or bare React Native apps. The [Google](https://docs.expo.io/versions/latest/sdk/google/) library provides Google authentication integration for Expo apps using a secure system web browser with native `expo-app-auth`

Going to close this issue since it hasn't seen any activity since the relevant updates to code/docs were made. If you have any other issues with either of these libraries, please open up a new issue with a full repro, thanks!

**Comment by vclassdev1** [comment]
i also face same issue when i make a Realese apk google login redirect to Google.com
`androidClientId:'874376514949-oi63l1hpbclif4gon4dn4fe0s9ucavd4.apps.googleusercontent.com',
                androidStandaloneAppClientId:'874376514949-m5f77i8pp4dub997jm664pfljle1bu9k.apps.googleusercontent.com',

                 redirectUrl: `${AppAuth.OAuthRedirect}:/oauthredirect``

**Comment by mackbrowne** [comment]
I just had this issue.  it was due to mismatched reversed_client_id in app.json.  As soon as I used the correct reversed_client_id under ios.config.googleSignIn, it worked

**Comment by hixus** [comment]
We had same "You app is missing support for the following URL schemes..." error but this was because same clientId was also defined in GoogleSignIn.initAsync({clientId: <reversed_client_id>}) call in app entry file. Removing that fixed the issue for ios. Android worked properly with the clientId argument so only affects ios.
