### ISSUE TITLE
Sitemap route is untyped in Expo Router v3 / Expo 50

### ISSUE THREAD

**Issue by vonkanehoffen** [expo/expo#26796]
### Minimal reproducible example

https://github.com/vonkanehoffen/expo-router-sitemap-bug-repro

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

In Expo router v2:
```
<Link href="/_sitemap">Sitemap</Link>
```
was type safe when
```
"experiments": {
      "typedRoutes": true
    }
```
was enabled. In v3 however, it is not:

```
error TS2322: Type '"/_sitemap"' is not assignable to type 'StaticRoutes | RelativePathString | `${string}:${string}
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2023.11.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0, 34.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.4 => 50.0.4
      expo-router: ~3.4.6 => 3.4.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Fixed in #26578
