### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by tauren** [expo/expo#268]
I need to support peer-to-peer video and audio streaming, data channels, etc.

Are there any plans to support WebRTC without detaching and writing native modules?

**Comment by gkufera** [comment]
Hi @tauren!

Yes, we do plan on supporting WebRTC! We don't have a estimated release date for that feature, but stay tuned.

See our canny.io page to upvote the WebRTC feature request here: https://expo.canny.io/feature-requests/p/webrtc

Thanks!

Greg
