### ISSUE TITLE
[SDK 49] ScreenOrientation does not reset back to portrait when viewing a video in landscape and exiting

### ISSUE THREAD

**Issue by joshembling** [expo/expo#26803]
### Minimal reproducible example

https://github.com/joshembling/expo-video-rotation-issue

### Summary

On iOS, when playing a video and rotating the functionality works as expected - Portrait, left landscape and right landscape. 

The issue is when exiting the video, the video does not return back to it's original state e.g. `"initialOrientation": "PORTRAIT_UP"` and stays in landscape mode. I.e. screen height is roughly 320px, and layout is all over the shop.

If the user rotates the screen back to portrait before exiting, the app behaves as normal. 

By looking at the sheer number of issues here, this seems to be a problem for a lot of people. 

Anyone have a resolve?

### Environment

Copy the component to a project running expo.

**Comment by brentvatne** [comment]
hi there! we're focusing our efforts on the new `expo-video` library that we plan on releasing in sdk 51. if this is a blocking issue for your app, i'd recommend coming up with a fix and patching it directly yourself in node_modules, or switching to another library (such as `react-native-video`) where this may be handled (you'd have to verify that).
