### ISSUE TITLE
[docs] [SDK50] Debugging web version

### ISSUE THREAD

**Issue by DamianUS** [expo/expo#26818]
### Summary

I upgraded the versions of my project from SDK47 to 50. Now, I'm not able to debug the web version using Chrome DevTools, it seems no sourcemaps are generated, and no debugging is possible.

I tried to find useful information, but no luck so far. It seems I couldn't successfully migrate from webpack to metro bundling for the web version and enable debugging and sourcemap generation and linking. I checked: https://docs.expo.dev/router/migrate/from-expo-webpack/ , https://docs.expo.dev/more/expo-cli/#exporting-with-webpack , https://docs.expo.dev/debugging/tools/ , discord forums and issues.

Could you throw some light on this issue?

### Link to the related docs page

https://docs.expo.dev/router/migrate/from-expo-webpack/

**Comment by EvanBacon** [comment]
I don't understand what this means? You tried migrating a website from Webpack to Metro and couldn't see source maps? Or did you just upgrade your project while still using Webpack?

**Comment by YahyaBagia** [comment]
In a new Expo project aimed at the web platform, I'm encountering difficulty locating the source of a few files via the Chrome DevTools (Sources).

- Has there been any change in SDK 50 that could explain this?
- Could I have missed a step that led to this issue?
- Is there a guide available on debugging the app specifically for the web platform?

Here's my package.json:
```json
{
  "name": "task-tracker-fe",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/metro-runtime": "~3.1.3",
    "@react-native-async-storage/async-storage": "1.21.0",
    "expo": "~50.0.11",
    "expo-constants": "~15.4.5",
    "expo-image": "~1.10.6",
    "expo-linear-gradient": "~12.7.2",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.8",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.4",
    "react-native-paper": "^5.12.3",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-web": "~0.19.6",
    "zustand": "^4.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  "private": true
}

```

**Comment by jpeiler** [comment]
I am also facing this issue and this is also the first thread or mention I've seen about this issue. Since upgrading to Expo 50+, I can no longer find the source of any files within my app while viewing on web ( ran with the command "expo start --web" ). Sometimes I can see a small handful of screen files (e.g. (app)/index.tsx, which appears to be coming from "http:// localhost:8081/app\(app)\index.bundle//&platform=web&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=app&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true". Even still, breakpoints behave strangely there so it's not all that useful.

Package.json:
```
{
  "private": true,
  "name": "@ri_expo/portal",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "build": "echo 'Nothing to build'",
    "start": "expo start --tunnel",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "eas-build-post-install": "yarn workspaces run build"
  },
  "dependencies": {
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.4",
    "expo": "^51.0.8",
    "expo-constants": "~16.0.1",
    "expo-document-picker": "~12.0.1",
    "expo-file-system": "~17.0.1",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-notifications": "~0.28.2",
    "expo-router": "~3.5.14",
    "expo-sharing": "~12.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "intl": "^1.2.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.8.6"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/ngrok": "4.1.0",
    "@types/react": "~18.2.45",
    "typescript": "~5.3.3"
  }
}
```
