### ISSUE TITLE
Setting `userInterfaceStyle` to `dark` prevents ScreenOrientation change listener from firing

### ISSUE THREAD

**Issue by dpwilhelmsen** [expo/expo#26813]
### Minimal reproducible example

https://github.com/dpwilhelmsen/expo-orientation-listener-bug

### Summary

`addOrientationChangeListener` from `expo-screen-orientation` does not seem to fire when `userInterfaceStyle` is set to `dark` in `app.json`. If the value is set to `light` it works appropriately. This was tested with the latest version of expo and the screen orientation package, and observed in Expo Go on an iOS Simulator (specifically an iPhone 15 Pro Max). I haven't tested other emulators/simulators/devices, but changing that one config value does affect whether the listener fires or not on device rotation.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2023.06.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/dan/.rvm/gems/ruby-3.0.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: Hedgehog 2023.1.1 Hedgehog 2023.1.1
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.4 => 50.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    Expo Workflow: managed

**Comment by aleqsio** [comment]
not stale
