### ISSUE TITLE
[SDK49] [expo-splash-screen] White screen appears between splash screens on Android

### ISSUE THREAD

**Issue by AdamPD** [expo/expo#26811]
### Minimal reproducible example

https://github.com/adampd/expo-splash-screen-eas-update

### Summary

This issue is related to https://github.com/expo/expo/issues/23363 which does not appear to be properly resolved.

I have updated the reproducible example from that to use the latest packages (expo 49.0.22 and expo-splash-screen 0.20.5) which others said resolved their issue, but there is still the flicker of a white splash screen.

This is only an issue on the Android builds.

Assing a positive time for `fallbackToCacheTimeout` in the `app.json` makes the issue far more pronounced.  Indeed, if you release an update via EAS Update, the white screen remains at launch while the app is updating.  I assume that this white screen is shown while expo-updates is checking for (and downloading, if applicable) updates.

The expected behaviour is that the native splash screen shows at launch, followed by the Expo splash screen, during the entire time the app is loading, checking for updates ,etc.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    npmPackages:
      expo: ^49.0.22 => 49.0.22
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

**Comment by cupid20103** [comment]
Yes, I've had this problem before too. In development mode everything works fine, but after building using eas I get a white screen instead of my custom splash screen.
How do I solve this? I think this problem is related to eas building?

**Comment by AdamPD** [comment]
Looks like this is caused by:
https://github.com/expo/expo/pull/20273

And looks like it should have been fixed by:
https://github.com/expo/expo/pull/23747

But the latter did not indeed fix the white screen issue.  I've attached the debugger for when `SplashScreen.show` finally gets called, and the screen is white at that point.  Seems like the app is launching (and hiding the native splash screen) before the Expo splash screen gets displayed, so you get a flash of white screen in between.

Setting `EX_UPDATES_ANDROID_DELAY_LOAD_APP` (as mentioned in the first PR) to `false` appears to fix the issue by disabling the changes from the PR.  I've added, in my `eas.json`, for example:

```
"production": {
      "channel": "stable",
      "env": {
        "EX_UPDATES_ANDROID_DELAY_LOAD_APP": "false"
      }
    }
```

**Comment by brentvatne** [comment]
this is fixed in sdk 50

**Comment by Haseebshah936** [comment]
@brentvatne I am using expo sdk 50 and facing the same issue. I upgrade my expo version from 49 to 50.

**Comment by brentvatne** [comment]
@Haseebshah936 - if you believe this is a bug, create an issue and will out the issue template, including the minimal reproducible. you may want to also try https://expo.fyi/manual-debugging
