### ISSUE TITLE
`.env.test` is not loading properly in SDK50 on IOS. 

### ISSUE THREAD

**Issue by a-eid** [expo/expo#26814]
### Minimal reproducible example

https://expo.dev/accounts/brgr/projects/zeal-brgr/builds/b177b2cd-4922-4ccb-9c8d-900e88e7e909

### Summary

When building IOS with this eas profile 

```
    "test": {
      "distribution": "internal",
      "releaseChannel": "test",
      "env": { "NODE_ENV": "test", "BABEL_ENV": "release" }
    },
 ```
 
 expo doesn't load `.env.test`, resulting in undefined values, it seem to be working on android however. 
 
 when prebuilding the app it does say that they are loaded correctly however they are not.
 
![Screenshot 2024-01-31 at 9 37 25 AM](https://github.com/expo/expo/assets/19273413/ab0d0d8a-5b93-4bf5-8bcd-ad67377cb67e)

I'm not sure how to debug this further.

### Environment

```

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/n/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.2.3 - ~/n/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /Users/ahmedelshentenawy/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.4 => 50.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: managed
```

**Comment by a-eid** [comment]
it seems that this is not specific to the `test` env. it's not deterministic, I'm not sure what's causing this.

**Comment by brentvatne** [comment]
i would not recommend using `NODE_ENV` like this. `test` has a very specific meaning for `NODE_ENV` and it should only be used if you are actually running tests, or you may end up executing code that you don't expect - for example, jest automatically sets `NODE_ENV` to test.

i would recommend storing your env values directly inside **eas.json** for now. i know this complicates syncing between your EAS Build profile environment and your local environment (you need to copy/paste), but we are working on a solution for that. we'll also publish a blog post soon that helps to clarify how we think about env and provide clear recommendations

**Comment by a-eid** [comment]
@brentvatne I believe it's not allowed to use other NODE_ENV variables other than test, production and development ? 

I wanted to use `.env.staging` but it was not possible.

**Comment by brentvatne** [comment]
@a-eid - hopefully this blog post helps to clarify the situation: https://expo.dev/blog/what-are-environment-variables

**Comment by a-eid** [comment]
@brentvatne thank you.
