### ISSUE TITLE
Exception thrown while executing UI block: - [RNSVGSvgView setOnClick]: unrecognized selector sent to instance 0x01071ca460

### ISSUE THREAD

**Issue by manuelmhtr** [expo/expo#26829]
### Summary

After upgrading to SDK 50 and React Native 0.73, I'm getting the following error when running ONLY on the iOS simulator:
```
Exception thrown while executing UI block: - [RNSVGSvgView setOnClick]: unrecognized selector sent to instance 0x01071ca460
```

* No errors are printed in the console.
* It works fine when running on the device.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

* expo: `50.0.4`
* expo-dev-client: `3.3.7`
* expo-updates: `0.24.9`
* react: `18.2.0`
* react-native: `0.73.2`
* react-native-svg: `14.1.0`
* react-native-svg-transformer: `1.3.0`

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 4.0.2 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.1 => 0.17.3 
      babel-preset-expo: ^10.0.0 => 10.0.1 
      expo: ^50.0.0 => 50.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ^0.19.10 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: managed
```

### Reproducible demo

https://expo.dev/accounts/zenfi/projects/zenfi/builds/036b68e5-473e-4819-9b8e-713f5e3835da

### Stacktrace (if a crash is involved)

![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-31 at 08 58 37](https://github.com/expo/expo/assets/1031639/1e08c5a7-d29e-446f-84fb-f090ec2a33a2)

```
Exception thrown while executing UI block: - [RNSVGSvgView setOnClick]: unrecognized selector sent to instance 0x01071ca460

[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
```

**Comment by manuelmhtr** [comment]
After some debugging found the problem is either in `@ui-kitten/components` or `react-native-svg`.
More information and the solution here: https://github.com/akveo/react-native-ui-kitten/issues/1801

**Comment by faisstzera** [comment]
How did you manage to find that the problem was with the Icon component? I'm having the same error, but I don't have the faintest idea since the App crashes on IOS immediately after I open it with Expo. 

The only thing that came to my mind is that the problem is with the OnPress (since I don't use setOnClick property in my project) in the TouchableWithoutFeedback component from React Native that I use in my login screen

I already tried to downgrade react-native-svg version, but it didn't work

Here is the error message:

```
Exception thrown while executing UI block: -[RNSVGSvgView setOnClick:]: unrecognized selector sent to instance 0x10840d340

RCTSurfaceStageIsPreparing
    RCTUIManager.m:1205
RCTSurfaceStageIsPreparing
FEA36690-A000-3C55-B700-9120B05AA69B
FEA36690-A000-3C55-B700-9120B05AA69B
FEA36690-A000-3C55-B700-9120B05AA69B
_dispatch_main_queue_callback_4CF
5CDC5D9A-E506-3740-B64E-BB30867B4F1B
5CDC5D9A-E506-3740-B64E-BB30867B4F1B
CFRunLoopRunSpecific
GSEventRunModal
179501B6-0FC2-344A-B969-B4E3961EBE10
UIApplicationMain
main
CB3FF411-4762-34D2-86A4-ECA13F9FB6C3
```

**Comment by yonitou** [comment]
Hey
I had the same issue and I fixed it by removing all `onClick` props in my SVG components (in a react native/expo app)

**Comment by espinozamaria** [comment]
Had the same issue after upgrading from Expo SDK 49 -> 51 on a TouchableWithoutFeedback component, solved it by adding height + width to the child View component:
```
<TouchableWithoutFeedback onPress={onPress}>
    <View style={{ flex: 1, width: "100%", height: "100%" }}> // <-- adding height + width here
        // more content here
     </View>
</TouchableWithoutFeedback>
```

**Comment by Sparrowan** [comment]
> Had the same issue after upgrading from Expo SDK 49 -> 51 on a TouchableWithoutFeedback component, solved it by adding height + width to the child View component:
> 
> ```
> <TouchableWithoutFeedback onPress={onPress}>
>     <View style={{ flex: 1, width: "100%", height: "100%" }}> // <-- adding height + width here
>         // more content here
>      </View>
> </TouchableWithoutFeedback>
> ```

This worked for me as well. Thank you.

**Comment by laxmanJun01** [comment]
I'm using react-native bare project, not expo, and moreover screens contains 10s of child components inside the main screen., not even found anyToucahbleWithout or <svg elements anywhere too.

btw, after upgrade from rn v0.72.14 to v0.74.5 only, this is occuring on iOS build only.
