### ISSUE TITLE
Nextjs: ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by rajat693** [expo/expo#26822]
### Summary

```
 ⨯ node_modules/@expo/html-elements/build/elements/Headings.js (25:0) @ eval
 ⨯ ReferenceError: __DEV__ is not defined
```
 
 getting the above error for  "@expo/html-elements"(version)>0.7.0 , when using it in nextjs app.
 file path:- `node_modules/@expo/html-elements/build/elements/Headings.js`
 file code:- ```
if (__DEV__) {
    H1.displayName = 'H1';
    H2.displayName = 'H2';
    H3.displayName = 'H3';
    H4.displayName = 'H4';
    H5.displayName = 'H5';
    H6.displayName = 'H6';
}
```
 
 

### What platform(s) does this occur on?

Web

### SDK Version

_No response_

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
      Watchman: 2024.01.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/rajatchaudhary/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native-web: ^0.19.7 => 0.19.10 
    Expo Workflow: managed
```



### Minimal reproducible example

https://github.com/maximedeoliveira/gluestack-nextjs-repro
<img width="1090" alt="dev error" src="https://github.com/expo/expo/assets/59024657/fcc5c689-4199-4367-8796-e887042c2690">

**Comment by rajat693** [comment]
<img width="1090" alt="dev error" src="https://github.com/expo/expo/assets/59024657/8aeb049e-9ac9-4484-bb95-f5a971ddd330">

**Comment by brentvatne** [comment]
hi there! if you're using react-native packages in a nextjs app or outside of a typical react-native environment, you'll have to provide polyfills for things like `__DEV__`. you may want to follow up with gluestack about this, as it seems like they provide the nextjs integration
