### ISSUE TITLE
[Camera] takePictureAsync quality issue in Android

### ISSUE THREAD

**Issue by muZk** [expo/expo#2683]
### Environment

```
Expo CLI 2.3.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.6.0 - ~/.nvm/versions/node/v8.6.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.3.0 - ~/.nvm/versions/node/v8.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.0 => 30.0.2
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.5.5 => 2.5.5
    npmGlobalPackages:
      expo-cli: 2.3.8

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/muzk-1ac3e531-8855-4798-98d8-be344d1e488e.tar.gz
```

### Steps to Reproduce

1. Take a picture with `Camera.takePictureAsync()` in android specifying a quality < 1.
2. See the resulting image

### Expected Behavior

In the snack I used 0.99 quality, so the image should have a good quality, something like this:

![20181110_164723](https://user-images.githubusercontent.com/1679496/48305440-23081a00-e509-11e8-8e17-4cd175a3b93f.jpg)

### Actual Behavior

But the actual behaviour is strange. The image has a VERY LOW quality:

![d6dde228-3be5-4663-8099-5cb8300ce155](https://user-images.githubusercontent.com/1679496/48305448-3c10cb00-e509-11e8-8276-b734970770d7.jpg)

### Reproducible Demo

You can try with is Snack in a real android device: https://snack.expo.io/@muzk/camera-exif

1. Take a picture (using the big white button)
2. An alert will display the EXIF info. Close it
3. Dismiss the app and go to your camera Roll or gallery where you can find the taken image. The quality is very bad, even when using 0.99 quality.

### Related

- https://forums.expo.io/t/camera-takepictureasync-quality-not-working-as-expected/14022

**Comment by sjchmiela** [comment]
Hey, @kotomono! To use an updated version of native SDK, you'd have to follow instructions covered in the following comment and later ones. 
https://github.com/expo/expo/issues/2657#issuecomment-442730588

However, I would encourage you to wait for SDK32 release (which is right around the corner) and just upgrade to it. 🙂
