### ISSUE TITLE
In expo-av Video, onPlaybackStatusUpdate is not getting called while video is playing

### ISSUE THREAD

**Issue by ankithhg** [expo/expo#26844]
### Minimal reproducible example

We were having expo app in SDK 42 and updated to SDK 49 and since then having the issue. So try creating app in SDK 42 and then update to SDK 49.

### Summary

I'm using Expo SDK 49 and expo-av 13.4.1. I'm using "Video" from "expo-av". Here sometimes callback for onPlaybackStatusUpdate is getting called while video is playing and sometimes it is not getting called. It works on some androids and on some it doesn't and since it is not getting called my states are not updating to show video's current timestamps. I tried callback with and without 'async', but no success.

`
updatePlaybackCallback(status) {
console.log("time", status.positionMillis , status.durationMillis)
const durationSeconds = (status.positionMillis || status.durationMillis) / 1000;
/*.... other code for timestamps */
}
`

`
<Video
ref={this.videoRef}
source={{
uri: this.state.videoURL,
}}
rate={1.0}
volume={this.state.playbackInstanceInfo.volume}
isMuted={false}
// resizeMode="cover"
resizeMode="contain"
shouldPlay={
this.state.playbackInstanceInfo.state !== "Buffering"
}
// useNativeControls

  isLooping={false}
  style={
      this.state.playbackInstanceInfo.fullScreen
          ? {
              ...styles.fullVideo,
              width: this.state.width,
              height: this.state.height,
          }
          : styles.video
  }
  onPlaybackStatusUpdate={(status) =>
      this.updatePlaybackCallback(status)
  }
/>
`

### Environment

We were having expo app in SDK 42 and updated to SDK 49 and since then having the issue. So try creating app in SDK 42 and then update to SDK 49. We currently have:
expo sdk 49
expo-cli 6.3.10

**Comment by ankithhg** [comment]
@expo-bot how am I supposed to ask the community, if you keep on closing my issue as soon as I create them?

**Comment by joaocarlospf** [comment]
@ankithhg,  I'm having the same problem. In my case, the same device sometimes updates the status regularly (250 ms) and sometimes it takes 4 seconds to send another update when the video is playing. I'm using it to update my custom progress bar, but with this rate is simply impossible. Did you have find any work around for this issue? Thanks!
