### ISSUE TITLE
Delay when opening the app when it is in the backgrounded

### ISSUE THREAD

**Issue by JorgeMoralesLopez** [expo/expo#2684]
There is a considerable delay, about five seconds when you try to open the application when it is in the backgrounded.

### Environment
Installed on Android 7.0 Huawei phone
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
expo "sdkVersion": "30.0.0",
ubuntu 16.10

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. If this still happens in any of the currently supported SDK versions, please create a new issue with the template filled out completely (including full repro steps). Thanks
