### ISSUE TITLE
[SDK 50] expo-camera/next - await cameraRef.current.pausePreview() not available - How to pause with the next expo-camera/next

### ISSUE THREAD

**Issue by simoazzo** [expo/expo#26858]
### Minimal reproducible example

-

### Summary

The next expo-camera/next does not support await cameraRef.current.pausePreview();
How can I keep the same behaviour with expo/camera next - that I will be able to take a picture, see the photo captured (pausing the camera) and then on button action, the preview pause will be released.

### Environment

Android

**Comment by yassinexcv** [comment]
@simoazzo  Hi, i'm using the new expo camera of sdk51 and the green light indicator doesn't go away when i unmount the CameraView. I came across  pausePreview in a stackoverflow thread but i couldn't find it. Is there a way to get ride of this problem?

**Comment by lyseiha** [comment]
+1

**Comment by xiyaowong** [comment]
The bot has closed too much valid feedback 😞

**Comment by RomanBorysenkoRN** [comment]
+1

**Comment by blackirishmec** [comment]
I'm still running into this problem. Please for the love of god give an answer to this. It's totally broken.

This:
```
const takePicture = useCallback(async () => {
		if (cameraRef.current && isCameraReady) {
			const options = { quality: 0.5, base64: true, skipProcessing: true };

			const data = await cameraRef.current.takePictureAsync(options);

			console.log('cameraRef.current', cameraRef.current);

			const source = data?.uri;
			if (source) {
				cameraRef?.current?.pausePreview();

				console.log('source', source);

				setPreviewImageSource(source);

				setIsPreview(true);
			}
		}
	}, [cameraRef, isCameraReady, setIsPreview, setPreviewImageSource]);
```

... fires takePictureAsync() but throws:
```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: this._cameraRef.current?.pausePreview is not a function (it is undefined)
``` on pausePreview().
