### ISSUE TITLE
Camera focus stuck after initial focus on iOS

### ISSUE THREAD

**Issue by yoanhg421** [expo/expo#26869]
### Minimal reproducible example

https://github.com/yoanhg421/Expo-Camera-Error

### Summary

I have an app in production that was using SDK48, after upgrading to SDK 49 and 50 the Camera doesn't focus anymore.
I created a couple of different apps using the expo camera and they all have the same problem.

The camera opens and focuses but after a few seconds if you move the camera around it doesn't refocus.
I tried the camera/next, adding useCamera2Api, autoFocus, but nothing seems to work. The production app works fine but I need to make an update and this is breaking the current functionality.  

I tested on different computers as well, iPhone 12 and 15ProMax. Testing was done in Expo Go, local development app, eas build, and local build. I do most of my work on Windows so using react-native-vision-camera is not an option at the moment. 

Please help. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.5 => 50.0.5
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: managed

**Comment by villeliekari** [comment]
Same issue here. Had to upgrade from SDK48 to 50 and now auto focus is not working. Only way to focus for now seems to manually set focus off and then back on.

**Comment by yoanhg421** [comment]
Today it seems to be working fine with expo-camera/next.

**Comment by Maxime9812** [comment]
It doesn't work for me with camera/next expo SDK 50 with a iPhone 13 Pro Max. It works with camera expo SDK 49

**Comment by yoanhg421** [comment]
@Maxime9812 I have 2 internal apps in production and the focus problem is fixed in SDK50 with camera/next. 
The API is different so make sure you are using the right properties as they are not 1 to 1. 
also, clear your expo cache. 

However, passing barcode types to the camera view stops scanning altogether.

**Comment by rpatidar** [comment]
I am having similar issues after recent upgrade to expo 50 and camera 14 versions.  autofocus does changes things but after a moment it get locked, When you change focus from a far object to a near object it just get stuck and blur image is shown.

**Comment by m4xyyyyy** [comment]
@yoanhg421 is the react-native-vision-camera only usable on Mac? I got it running on WIndows but got stuck after I implemented taking pictures.

**Comment by SidMasih** [comment]
Experiencing same issue!

**Comment by davidpsanders** [comment]
I believe I've found the cause, introduced in https://github.com/expo/expo/pull/22604

The mapping of the Expo AutoFocus enum's on value to the iOS equivalent was changed. 
Before this PR it was (at https://github.com/expo/expo/blob/216bae38311f89759facbb26041fe8fbbf710d5e/packages/expo-camera/ios/EXCamera/EXCamera.h#L31)
```
EXCameraAutoFocusOn = AVCaptureFocusModeContinuousAutoFocus,
```
After the PR the conversion is handled in the function, toAvAutoFocus (at https://github.com/alanjhughes/expo/blob/265a1bd32bbde39b21cc621c913dddc130d7de68/packages/expo-camera/ios/CameraEnums.swift#L54). Where we have:
```
    case .on:
      return .autoFocus
```

The apple docs for AVCaptureDevice.FocusMode (https://developer.apple.com/documentation/avfoundation/avcapturedevice/focusmode) explain the behaviour we are seeing:
_case autoFocus 
A mode that automatically adjusts the focus one time, and then locks focus.
continuousAutoFocus 
A mode that continuously monitors focus and autofocuses when necessary._

**Comment by davidpsanders** [comment]
I'm working on a patch file based on my previous comment. No luck yet though. Can you see what I might be missing @alanjhughes ?

```
diff --git a/node_modules/expo-camera/ios/CameraEnums.swift b/node_modules/expo-camera/ios/CameraEnums.swift
index 838e8ff..b7eb578 100644
--- a/node_modules/expo-camera/ios/CameraEnums.swift
+++ b/node_modules/expo-camera/ios/CameraEnums.swift
@@ -51,11 +51,11 @@ enum CameraAutoFocus: Int, Enumerable {
   func toAvAutoFocus() -> AVCaptureDevice.FocusMode {
     switch self {
     case .on:
-      return .autoFocus
+      return .continuousAutoFocus
     case .off:
       return .locked
     default:
-      return .autoFocus
+      return .continuousAutoFocus
     }
   }
 }
diff --git a/node_modules/expo-camera/ios/CameraView.swift b/node_modules/expo-camera/ios/CameraView.swift
index 2af1c67..d3c5bc1 100644
--- a/node_modules/expo-camera/ios/CameraView.swift
+++ b/node_modules/expo-camera/ios/CameraView.swift
@@ -66,7 +66,7 @@ public class CameraView: ExpoView, EXCameraInterface, EXAppLifecycleListener,
     }
   }
 
-  var autoFocus = AVCaptureDevice.FocusMode.autoFocus {
+  var autoFocus = AVCaptureDevice.FocusMode.continuousAutoFocus {
     didSet {
       updateFocusMode()
     }

```

**Comment by Riley-livingston** [comment]
Has anyone found a solution for this issue? Im having the same problem where the camera focuses initially and then locks without refocusing on depth changes

``
  import { Camera } from "expo-camera";

  const cameraRef = useRef(null);

  const takePicture = async () => {
    if (isLoading || !cameraRef.current) return;

    const options = {
      quality: 0.9,
      base64: true,
    };
    const data = await cameraRef.current.takePictureAsync(options);

    const newImageId = `${userName}_${Date.now()}_${uuidv4()}`;
    setImageId(newImageId);
    setCapturedImage(data.base64); // Set capturedImage as base64 string

    sendImageToServer(data.base64); // This now handles the entire processing
  };

 <Camera
        style={styles.camera}
        key={key}
        type={Camera.Constants.Type.back}
        ref={cameraRef}
        autoFocus={Camera.Constants.AutoFocus.on}
        base64="true"
      >
        <CenteringLinesOverlay />
      </Camera>


``

**Comment by zhiftyDK** [comment]
Updating the autoFocus prop every 2 seconds seems to do the trick. Its not very pretty but it works:
```js
const [customAutoFocus, setCustomAutoFocus] = useState(false);

useEffect(() => {
    const interval = setInterval(() => {
        if (customAutoFocus) {
            setCustomAutoFocus(false)
        } else {
            setCustomAutoFocus(true)
        }
    }, 2000);
    return () => clearInterval(interval);
});

return (
    <Camera style={styles.container} autoFocus={customAutoFocus}>
        <StatusBar style="auto"/>
    </Camera>
);
```

**Comment by roecks** [comment]
Managed to implement a workaround (inspired by previous comments) to run "tap to autofocus" and it works for our usecase. It's an absolute positioned touchable transparent overlay in the Camera component. Then we just toggle autoFocus with a timeout.

```
const [focus. setFocus] = useState<boolean>(true);

const focusCamera = () => {
    setFocus(false);
    setTimeout(() => {
        setFocus(true);
    }, 200);
}
return (
    <Camera
        ref={cameraRef}
        autoFocus={focus}
        style={{ position: 'relative', flex: 1 }}
    >
        <TouchableOpacity
            activeOpacity={1}
            onPress={focusCamera}
            style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'transparent' }}
        />
    </Camera>
)
```

Just make sure you set the zIndex right if you also have a <View> with camera controls in the Camera component.
This worked for us, for now, as a quick fix.

**Comment by Saschamz** [comment]
I wrote a patch that can be applied with [patch-package](https://www.npmjs.com/package/patch-package) to resolve this issue for `expo-camera/next`

```
diff --git a/node_modules/expo-camera/ios/Next/CameraViewNext.swift b/node_modules/expo-camera/ios/Next/CameraViewNext.swift
index 20c115a..f5778a0 100644
--- a/node_modules/expo-camera/ios/Next/CameraViewNext.swift
+++ b/node_modules/expo-camera/ios/Next/CameraViewNext.swift
@@ -221,6 +221,23 @@ public class CameraViewNext: ExpoView, EXCameraInterface, EXAppLifecycleListener
     }
   }
 
+    private func setAutoFocus() {
+      guard let device = captureDeviceInput?.device else {
+        return
+      }
+
+      do {
+        try device.lockForConfiguration()
+      if (device.isFocusModeSupported(.continuousAutoFocus)) {
+          device.focusMode = .continuousAutoFocus
+      }
+      } catch {
+        log.info("\(#function): \(error.localizedDescription)")
+      }
+
+      device.unlockForConfiguration()
+    }
+    
   private func updateZoom() {
     guard let device = captureDeviceInput?.device else {
       return
@@ -701,11 +721,14 @@ public class CameraViewNext: ExpoView, EXCameraInterface, EXAppLifecycleListener
       do {
         let captureDeviceInput = try AVCaptureDeviceInput(device: device)
 
+          
         if self.session.canAddInput(captureDeviceInput) {
           self.session.addInput(captureDeviceInput)
           self.captureDeviceInput = captureDeviceInput
+          self.setAutoFocus()
           self.updateZoom()
         }
+          
       } catch {
         self.onMountError(["message": "Camera could not be started - \(error.localizedDescription)"])
       }
```

What it does is add a method called `setAutoFocus` to the `CameraViewNext` class in Swift.
It then calls it setting [continuousAutoFocus](https://developer.apple.com/documentation/avfoundation/avcapturedevice/focusmode/continuousautofocus) as the `AVCaptureDeviceInput` is initialized.

Haven't tried it myself but the [solution](https://github.com/expo/expo/issues/26869#issuecomment-1976694433) posted by @davidpsanders should work if you're not using the `/next` version.

**Comment by Saschamz** [comment]
@roecks Careful that with your solution your app will crash if the camera is focused and the component is unmounted within 200ms (before the `setTimeout` callback runs) since you will be attempting to set state on an unmounted component.

Here's another way to do it:
```tsx
  const [focus, setFocus] = useState<AutoFocus>(AutoFocus.on)

  const updateCameraFocus = () => setFocus(AutoFocus.off)

  // * Switch autofocus back to "on" after 50ms, this refocuses the camera
  useEffect(() => {
    if (focus !== AutoFocus.off) return
    const timeout = setTimeout(() => setFocus(AutoFocus.on), 50)
    return () => clearTimeout(timeout)
  }, [focus])

  // * Refocus camera every 2 seconds
  useEffect(() => {
    const interval = setInterval(() => updateCameraFocus(), 2000)
    return () => clearInterval(interval)
  }, [])
```

Or if you prefer to refocus when the user presses the camera
```tsx
  <TouchableWithoutFeedback onPress={updateCameraFocus}>
    <Camera />
  </TouchableWithoutFeedback>
```

**Comment by rpatidar** [comment]
> @roecks Careful that with your solution your app will crash if the camera is focused and the component is unmounted within 200ms (before the `setTimeout` callback runs) since you will be attempting to set state on an unmounted component.
> 
> Here's another way to do it:
> 
> ```tsx
>   const [focus, setFocus] = useState<AutoFocus>(AutoFocus.on)
> 
>   const updateCameraFocus = () => setFocus(AutoFocus.off)
> 
>   // * Switch autofocus back to "on" after 50ms, this refocuses the camera
>   useEffect(() => {
>     if (focus !== AutoFocus.off) return
>     const timeout = setTimeout(() => setFocus(AutoFocus.on), 50)
>     return () => clearTimeout(timeout)
>   }, [focus])
> 
>   // * Refocus camera every 2 seconds
>   useEffect(() => {
>     const interval = setInterval(() => updateCameraFocus(), 2000)
>     return () => clearInterval(interval)
>   }, [])
> ```
> 
> Or if you prefer to refocus when the user presses the camera
> 
> ```tsx
>   <TouchableWithoutFeedback onPress={updateCameraFocus}>
>     <Camera />
>   </TouchableWithoutFeedback>
> ```

i tried the solution, not changing anything for me  on tapping the camera

**Comment by lclnrd** [comment]
Looks like @davidpsanders patch is working on expo 50.0.14 on my side. Will this fix and the one for expo-camera/next be in next SDK 50 minor release ?

**Comment by arttumat** [comment]
Neither of the patches seem to work for me for some reason, tried @davidpsanders patch with
`import { Camera } from 'expo-camera';`
and @Saschamz patch with
`import { CameraView} from 'expo-camera/next';` but in both cases the focus issue persists, am I missing something? Do I need to change something else?

expo 50.0.6
expo-camera 14.0.4

```jsx
<CameraView
  onBarcodeScanned={
    onBarcodeScannedHandler() as BarCodeScannedCallback | undefined
  }
  style={[StyleSheet.absoluteFillObject, { zIndex: -1 }]}
  onLayout={event => measurePreview(event.nativeEvent.layout)}
  barcodeScannerSettings={{
    barCodeTypes: ['code128', 'ean8', 'ean13'],
  }}
/>
```

**Comment by Adam-Schlichtmann** [comment]
Is there a reason there hasn't been a PR into `expo-camera` and `expo-camera/next`? Seems like @davidpsanders's fix does the job

**Comment by nixolas1** [comment]
Would be great to get this patched in a official expo-camera update, @alanjhughes :) (If you're the right guy)

**Comment by PMalaret** [comment]
This is happening to me on several iOS and Android devices in Expo SDK 50 and expo-camera 14.1.3.
The camera's autofocus stops working after a while.

**Comment by nojas01** [comment]
@davidpsanders Your fix is correct and works for me too. Did you consider making a PR? Or is someone from the expo team picking this up? 

> I'm working on a patch file based on my previous comment. No luck yet though. Can you see what I might be missing @alanjhughes ?
> 
> ```
> diff --git a/node_modules/expo-camera/ios/CameraEnums.swift b/node_modules/expo-camera/ios/CameraEnums.swift
> index 838e8ff..b7eb578 100644
> --- a/node_modules/expo-camera/ios/CameraEnums.swift
> +++ b/node_modules/expo-camera/ios/CameraEnums.swift
> @@ -51,11 +51,11 @@ enum CameraAutoFocus: Int, Enumerable {
>    func toAvAutoFocus() -> AVCaptureDevice.FocusMode {
>      switch self {
>      case .on:
> -      return .autoFocus
> +      return .continuousAutoFocus
>      case .off:
>        return .locked
>      default:
> -      return .autoFocus
> +      return .continuousAutoFocus
>      }
>    }
>  }
> diff --git a/node_modules/expo-camera/ios/CameraView.swift b/node_modules/expo-camera/ios/CameraView.swift
> index 2af1c67..d3c5bc1 100644
> --- a/node_modules/expo-camera/ios/CameraView.swift
> +++ b/node_modules/expo-camera/ios/CameraView.swift
> @@ -66,7 +66,7 @@ public class CameraView: ExpoView, EXCameraInterface, EXAppLifecycleListener,
>      }
>    }
>  
> -  var autoFocus = AVCaptureDevice.FocusMode.autoFocus {
> +  var autoFocus = AVCaptureDevice.FocusMode.continuousAutoFocus {
>      didSet {
>        updateFocusMode()
>      }
> ```
> 
> EDIT: This is working for me after building and installing just not in expo go
