### ISSUE TITLE
[SDK 50] Regression: expo-sqlite no longer supports FTS modules

### ISSUE THREAD

**Issue by ndekross** [expo/expo#26866]
### Minimal reproducible example

https://github.com/ndekross/expo-sqlite-no-fts-module-error

### Summary

We've been using the SQlite's [FTS4 module](https://www.sqlite.org/fts3.html) in our app, which is currently running on Expo 49 and `expo-sqlite@11.3.3`. This module is crucial for providing full-text search, a core feature for our customers. However, after upgrading to Expo SDK 50 and updating `expo-sqlite` to the latest version, the FTS module has stopped functioning. When I attempt to create an FTS table, SQLite gives this error:

```
 [Error: Error code 1: no such module: fts4]
```

I also tried FTS3 and FTS5, but neither was successful. I've created a [minimal reproducible example](https://github.com/ndekross/expo-sqlite-no-fts-module-error) based on Expo's `with-sqlite` template. You can start the app and observe the error firsthand.

What we expect:
- Error-free creation of an FTS4 virtual table
- Support for FTS5, which was released nearly a decade ago

Thank you!

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.6.3 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.6 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11255304
    npmPackages:
      expo: ^50.0.4 => 50.0.5
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.8 => 0.19.8
    Expo Workflow: bare
```

**Comment by verontheservant** [comment]
I was trying also to use FTS and get the same error, it would be great to have FTS5 module enable but according some doc Android does not support it.

**Comment by ndekross** [comment]
Expo no longer uses the OS bundled version of SQLite in `expo-sqlite/next`, which might be why we've lost support for FTS. We hope they'll include the FTS5 extension when they add this feature back.

>We've also updated the SQLite version to 3.42.0 on both platforms, rather than depending on the versions bundled with the operating system.
[Source](https://expo.dev/changelog/2024/01-18-sdk-50#new-and-improved-sqlite-and-camera-apis)

**Comment by verontheservant** [comment]
expo-sqlite/next
I am having a nightmare with bulk insertions alone or in a loop to import 31200 records. Take them from the server and to insert into the table it is a nightmare.

 [Error: Call to function 'NativeDatabase.execAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: java.lang.NullPointerException]

after somme correct insertions inside a table table it suddenly give this error, some times it worked completele when I deleted the schemas to make sure that everything works and try to import data again and booom 
error 

[Error: Call to function 'NativeDatabase.execAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: java.lang.NullPointerException]

some times it does not even insert 1 record. this crazy.

I put my component as PureComponent to make sure it is not beeing disturbed by re-rendering

for this bloc 
let db = await SQLite.openDatabaseAsync('mybiblebooks');   
await db.execAsync(`
	PRAGMA journal_mode = WAL;
	${sqlRecordstxt}
	`);
	
it worked some times and sometimes gives the same error 	
[Error: Call to function 'NativeDatabase.execAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: java.lang.NullPointerException]

Note: the data during insertion sometimes are Latin chars 				  
				  
//************************************************************************************************************/				  

			try {  
					let db = await SQLite.openDatabaseAsync('mybiblebooks');   
				  //   await db.execAsync(`
				  //   PRAGMA journal_mode = WAL;
				  //   ${sqlRecordstxt}
				  //   `);
				  let qtyGo=0;
				  for await (let versbloc of response.verslist){  
					  qtyGo++;
					  try{
						  //const verslist= await this.bulkOperationOff(db, qtyGo, versbloc); 
						  //const db = await SQLite.openDatabaseAsync('mybiblebooks');  
							// PRAGMA journal_mode = WAL; 
							///setTimeout(()=>{}, 26000);
							//this2.setTimeout(()=>{}, 26000);

							await db.execAsync(`
							${versbloc}
							`);
							//const result=await db.runAsync('INSERT INTO vers VALUES (?, ?, ?, ?, ?, ?, ?)', versbloc); //succed during 108 insertions then error 
							// [Error: Call to function 'NativeDatabase.execAsync' has been rejected.
							//→ Caused by: java.lang.NullPointerException: java.lang.NullPointerException]

							console.log("__|__success INSERT operation______ in bulkOperation #", qtyGo);
							//await db.closeAsync();
						  	console.log("*******************NOTES-POSTACTION-siiiiize**********00000**********verslist2 ", qtyGo, versbloc.length);
							///  this2.setTimeout(()=>{}, 26000);
					  }catch (error00) {
						  console.log("error bulkOperationOffx0000000000000000000---00000000 -tooooooopnow setp=", qtyGo, " size=", versbloc.length);
						  //console.log("error Arr ", versbloc);
						  console.log(error00);
						  //return "error";
						  // if(error00.toString().indexOf("NullPointerException")>-1){
						  // 	db = await SQLite.openDatabaseAsync('mybiblebooks'); 
						  // 	const verslist2= await this.bulkOperationOff(db, qtyGo, versbloc); 
						  // 	console.log("*******************CATCH***ERROR-NOTES-POSTACTION-siiiiize**********00000**********verslist2 ", qtyGo, verslist2);  
						  // }
					  }
						
					  //await new Promise(resolve => setTimeout(resolve, 1000)); //26000 
				  }
	  
				console.log("success operation in bulkOperationOffx ");
				//await db.closeAsync();
	  
				//return "yes";
			  }
			  catch (error) {
				  console.log("error bulkOperationOffx tooooooopnow ");
				  console.log(error);
				  //return "error";
			  }



The errors after some succeeded insertions 

[mass-insert-31200-records.txt](https://github.com/expo/expo/files/14201743/mass-insert-31200-records.txt)

**Comment by verontheservant** [comment]
It is like if the connection has gone as in MySQL some times, Can some give me an explanation, any idea please...

I might go back to expo 49 and use the old SQLite.

**Comment by ndekross** [comment]
Adding an option to pass compile flags for developers to choose which official plugins to enable would be very helpful. One way to do this could be through a configuration plugin.

**Comment by mkhoussid** [comment]
> It is like if the connection has gone as in MySQL some times happened, Can someone give me an explanation, any idea please...
> 
> I might go back to expo 49 and use the old SQLite.

Did you manage to find a fix? I'm having the same problem after upgrading to Expo SDK 50. No errors are caught, it just... seems to hang every other request

**Comment by dylanfcsr** [comment]
> expo-sqlite/next I am having a nightmare with bulk insertions alone or in a loop to import 31200 records. Take them from the server and to insert into the table it is a nightmare.
> 
> [Error: Call to function 'NativeDatabase.execAsync' has been rejected. → Caused by: java.lang.NullPointerException: java.lang.NullPointerException]
> 
> after somme correct insertions inside a table table it suddenly give this error, some times it worked completele when I deleted the schemas to make sure that everything works and try to import data again and booom error
> 
> [Error: Call to function 'NativeDatabase.execAsync' has been rejected. → Caused by: java.lang.NullPointerException: java.lang.NullPointerException]
> 
> some times it does not even insert 1 record. this crazy.
> 
> I put my component as PureComponent to make sure it is not beeing disturbed by re-rendering
> 
> for this bloc let db = await SQLite.openDatabaseAsync('mybiblebooks'); await db.execAsync(`PRAGMA journal_mode = WAL; ${sqlRecordstxt}`);
> 
> it worked some times and sometimes gives the same error [Error: Call to function 'NativeDatabase.execAsync' has been rejected. → Caused by: java.lang.NullPointerException: java.lang.NullPointerException]
> 
> Note: the data during insertion sometimes are Latin chars
> 
> //************************************************************************************************************/
> 
> ```
> 		try {  
> 				let db = await SQLite.openDatabaseAsync('mybiblebooks');   
> 			  //   await db.execAsync(`
> 			  //   PRAGMA journal_mode = WAL;
> 			  //   ${sqlRecordstxt}
> 			  //   `);
> 			  let qtyGo=0;
> 			  for await (let versbloc of response.verslist){  
> 				  qtyGo++;
> 				  try{
> 					  //const verslist= await this.bulkOperationOff(db, qtyGo, versbloc); 
> 					  //const db = await SQLite.openDatabaseAsync('mybiblebooks');  
> 						// PRAGMA journal_mode = WAL; 
> 						///setTimeout(()=>{}, 26000);
> 						//this2.setTimeout(()=>{}, 26000);
> 
> 						await db.execAsync(`
> 						${versbloc}
> 						`);
> 						//const result=await db.runAsync('INSERT INTO vers VALUES (?, ?, ?, ?, ?, ?, ?)', versbloc); //succed during 108 insertions then error 
> 						// [Error: Call to function 'NativeDatabase.execAsync' has been rejected.
> 						//→ Caused by: java.lang.NullPointerException: java.lang.NullPointerException]
> 
> 						console.log("__|__success INSERT operation______ in bulkOperation #", qtyGo);
> 						//await db.closeAsync();
> 					  	console.log("*******************NOTES-POSTACTION-siiiiize**********00000**********verslist2 ", qtyGo, versbloc.length);
> 						///  this2.setTimeout(()=>{}, 26000);
> 				  }catch (error00) {
> 					  console.log("error bulkOperationOffx0000000000000000000---00000000 -tooooooopnow setp=", qtyGo, " size=", versbloc.length);
> 					  //console.log("error Arr ", versbloc);
> 					  console.log(error00);
> 					  //return "error";
> 					  // if(error00.toString().indexOf("NullPointerException")>-1){
> 					  // 	db = await SQLite.openDatabaseAsync('mybiblebooks'); 
> 					  // 	const verslist2= await this.bulkOperationOff(db, qtyGo, versbloc); 
> 					  // 	console.log("*******************CATCH***ERROR-NOTES-POSTACTION-siiiiize**********00000**********verslist2 ", qtyGo, verslist2);  
> 					  // }
> 				  }
> 					
> 				  //await new Promise(resolve => setTimeout(resolve, 1000)); //26000 
> 			  }
>   
> 			console.log("success operation in bulkOperationOffx ");
> 			//await db.closeAsync();
>   
> 			//return "yes";
> 		  }
> 		  catch (error) {
> 			  console.log("error bulkOperationOffx tooooooopnow ");
> 			  console.log(error);
> 			  //return "error";
> 		  }
> ```
> 
> The errors after some succeeded insertions
> 
> [mass-insert-31200-records.txt](https://github.com/expo/expo/files/14201743/mass-insert-31200-records.txt)

I have the same random issue that blocks everything. Is it a known issue?

**Comment by robdubparker** [comment]
We at least need a workaround for the FTS issue.  I'm having the same problem.  Does it make sense to just resort to using the separate [react-native-sqlite-storage package](https://www.npmjs.com/package/react-native-sqlite-storage) instead of `expo-sqlite` ?

**Comment by robdubparker** [comment]
Nice!  well, done @Kudo

**Comment by Kudo** [comment]
the issue should be fixed by `expo-sqlite@13.4.0`. please let me know whether it works for you.

**Comment by mahmoudbitar135** [comment]
I still have the same issue with expo-sqlite@13.4.0.
it happens mainly in android, on fetch/insert/update queries. it throws this error randomally:

```
 ERROR  error in fetch_data_async [Error: Call to function 'NativeDatabase.prepareAsync' has been rejected.
→ Caused by: java.lang.NullPointerException: java.lang.NullPointerException] SELECT * FROM daily_orders_wholeSales_table
```

Note that I'm using expo-sqlite/next
Any updates on this or any workaround?

**Comment by mahmoudbitar135** [comment]
This is not a good experience at all! I have an app on production and the app crashes too many times randomly because of this error.

**Comment by robdubparker** [comment]
> the issue should be fixed by `expo-sqlite@13.4.0`. please let me know whether it works for you.

This update fixed the FTS issue for me. Thanks, again!

**Comment by Kudo** [comment]
@mahmoudbitar135 the error looks not relate to FTS. please open a new issue and would be good if you could share more details of your expo-sqlite code.

**Comment by joshdickson** [comment]
Hi @Kudo. I am not seeing that this is fixed when trying to run Expo 50 & the 13.4.0 build. I made a simple clone of the latest version of the `with-sqlite` example (https://github.com/expo/examples/tree/master/with-sqlite), updated the deps to use the 13.4.0 version of expo-sqlite, and added a code block to try to create a simple FTS5 enabled virtual table which seems to reproduce the same `[Error: Error code 1: no such module: fts5]` issue reported. I see the same when trying `expo-sqlite/next` as well.

My reproducible example based on `expo-sqlite@13.4.0` is here: https://github.com/joshdickson/sqlite-fts-5-test

**Comment by Kudo** [comment]
@joshdickson thanks for sharing the repro. did you try on expo-go or development builds? we didn't resubmit a new expo-go to include expo-sqlite@13.4.0 as we are preparing new expo-go for sdk 51. in this case, please try to use a development build (either `eas build` or `npx expo run:ios`) instead.

**Comment by joshdickson** [comment]
@Kudo ah I'm sorry, I did not realize the Expo Go app worked that way -- no, I've only tried there, I had not tried a development build. That makes sense. Thank you!

**Comment by Kudo** [comment]
@joshdickson i'm sorry too for not mentioning clearly. hopefully development builds works for you. thanks!

**Comment by officialpranav** [comment]
> @joshdickson i'm sorry too for not mentioning clearly. hopefully development builds works for you. thanks!

Hi, sorry if this is not the right place for this but I have no idea how to use a development build. Could you please point me to the section of the docs that says how to run in a development build (im running expo start --android (npm run android) at the moment).

**Comment by mkhoussid** [comment]
> > @joshdickson i'm sorry too for not mentioning clearly. hopefully development builds works for you. thanks!
> 
> Hi, sorry if this is not the right place for this but I have no idea how to use a development build. Could you please point me to the section of the docs that says how to run in a development build (im running expo start --android (npm run android) at the moment).

Have you tried searching for "expo development build" on Google? First few results are from the documentation

**Comment by ezrambala** [comment]
> This is not a good experience at all! I have an app on production and the app crashes too many times randomly because of this error.

Where you anle to fix, i gave the same issue

**Comment by maximedeoliveira** [comment]
How did you fix this issue ? 

I'm still experiencing the following error `no such module: fts5 (code 1 SQLITE _ERROR)` after upgrading the `expo-sqlite` package (`14.0.6` with expo `51.0.11`)
