### ISSUE TITLE
[expo-image-picker] Crash on select edited video on Samsung phones

### ISSUE THREAD

**Issue by marco2216** [expo/expo#26875]
### Minimal reproducible example

https://snack.expo.dev/@lenus/error-camera---android

### Summary

After the new Android image picker was implemented in SDK 49, selecting a video that has been edited and saved "over" the previous version will crash the app with a `expo.modules.imagepicker.FailedToDeduceTypeException: Can not deduce type of the returned file` error.
The error can be reproduced by recording a video on a Samsung phone, editing e.g. the length of the video with the built-in video editor, and save - not as a copy. When opening the image picker, the video will not be visible in the "Recent" list, but it can be found in "Albums" -> "Camera". Upon selecting the video, the app will crash.
The issue has also been discussed in this thread https://github.com/expo/expo/issues/20482
I am not sure if this is an Expo problem, since the issue seems to be that the ContentResolver can not get the type of the file? But maybe a workaround is possible if so.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
      npm: 10.1.0 - ~/.nvm/versions/node/v20.8.1/bin/npm
      Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.5.0 => 9.5.0
    Expo Workflow: managed

**Comment by marco2216** [comment]
I know this isn't really an Expo bug, but I think this issue calls into question whether the new photo picker is mature enough to be used. From what I can see, most popular apps use either the old document picker, or a custom media picker. 
I tested it on Notion, uploading a video that has been edited also doesn't work there either (they use the new photo picker also).

@lukmccall @alanjhughes Maybe you can give some input?

**Comment by marco2216** [comment]
I believe Samsung may have fixed this issue, as it doesn't occur on my phone any more.

**Comment by alanjhughes** [comment]
Hi @marco2216 - glad to hear this is fixed. If the issue returns, we've added a way to fallback to the legacy picker on android. You can pass `legacy: true` in the `ImagePickerOptions`.
