### ISSUE TITLE
node_modules\expo\AppEntry.js: .plugins[0] must be a string, object, function

### ISSUE THREAD

**Issue by noobster97** [expo/expo#26871]
### Minimal reproducible example

https://github.com/noobster97/error-expo-sdk.git

### Summary

```
{
  "name": "GoldNow",
  "version": "2.0.0",
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@kichiyaki/react-native-barcode-generator": "^0.6.7",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/cli": "^10.2.0",
    "@react-native-community/datetimepicker": "7.6.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-picker/picker": "2.6.1",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.4.0",
    "deprecated-react-native-prop-types": "^4.0.0",
    "expo": "~50.0.5",
    "expo-asset": "~9.0.2",
    "expo-dev-client": "~3.3.8",
    "expo-document-picker": "~11.10.1",
    "expo-file-system": "~16.0.5",
    "expo-font": "~11.10.2",
    "expo-image-picker": "~14.7.1",
    "expo-linear-gradient": "~12.7.1",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "install": "^0.13.0",
    "moment": "^2.29.4",
    "patch-package": "^6.5.1",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-native": "0.73.2",
    "react-native-chart-kit": "^6.12.0",
    "react-native-cli": "^2.0.1",
    "react-native-countdown": "^0.0.3",
    "react-native-countdown-component": "^2.7.1",
    "react-native-countdown-timer-hooks": "^1.0.3",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-normalize": "^1.0.1",
    "react-native-otp-inputs": "^7.4.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-searchable-dropdown": "^1.1.3",
    "react-native-smooth-pincode-input": "^1.0.9",
    "react-native-svg": "14.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-webview": "13.6.4",
    "react-native-wizard": "^2.1.1",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "typescript": "^5.3.0"
  },
  "scripts": {
    "postinstall": "patch-package"
  }
}
```

```
{
  "expo": {
    "name": "GoldNow",
    "slug": "GoldNow",
    "version": "2.0.1",
    "orientation": "portrait",
    "icon": "./assets/Logo-Landing/App-icon-ios.png",
    "backgroundColor": "#FFFFFF",
    "splash": {
      "image": "./assets/Logo-Landing/Landing.png",
      "backgroundColor": "#DAAA00"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "zahab.gold.tomei",
      "buildNumber": "2.0",
      "infoPlist": {
        "LSApplicationQueriesSchemes": [
          "lyft"
        ],
        "CFBundleDisplayName": "GoldNow"
      }
    },
    "android": {
      "icon": "./assets/Logo-Landing/App-icon.png",
      "adaptiveIcon": {
        "backgroundImage": "./assets/Logo-Landing/App-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "zahab.gold.tomei"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "50151fee-2a98-47e6-b90b-0e9ea9464d25"
      }
    },
    "plugins": [
      "expo-font"
    ]
  }
}
```
this is babel.config.js

```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
```

I am trying to upgrade my expo version from SDK 48 to SDK 50 because already deprecated. So when I followed all the step from here https://expo.dev/changelog/2024/01-18-sdk-50 ,i got nothing error including npx expo-doctor@latest command. But then when I want to run the app using command npx expo start --clear i got this error

`error: node_modules\expo\AppEntry.js: .plugins[0] must be a string, object, function`

I also already try delete node module and package-lock.json still i got the error. If its because of dependencies, how i know which dependencies are issues?

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33, 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ~50.0.5 => 50.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    Expo Workflow: managed

**Comment by NazarIlkiv** [comment]
Hi!

How you resolve this error?

**Comment by juanopet** [comment]
having the same issue here :(

**Comment by NazarIlkiv** [comment]
> having the same issue here :(

I resolve this problem. My steps:

1. Update version of all dependecies in package.json( change number of version )

2. Delete node modules

3. Delete package-lock.json

4. Install node modules

And everything work

**Comment by noobster97** [comment]
> Hi!
> 
> How you resolve this error?

I still having this issue. I already update all dependencies and deleted node module and package-lock.json but still same error.

**Comment by sherkhane-vivek** [comment]
> > Hi!
> > How you resolve this error?
> 
> I still having this issue. I already update all dependencies and deleted node module and package-lock.json but still same error.

I resolved this issue by upgrading the metro-config package to 0.80.5

**Comment by rrikesh** [comment]
> I resolved this issue by upgrading the metro-config package to 0.80.5

For whoever else experiencing that issue: Also make sure that `metro-source-map` is updated. See [this comment](https://github.com/expo/expo/discussions/26642#discussioncomment-8322577) for details.

**Comment by Surajj-00** [comment]
I resolved this error.
Firstly check the sdk version in package.json 

"dependencies": {
    "expo": "~50.0.17"

then set the dependency in same package.json
"main": "expo-router/entry",

**Comment by brentvatne** [comment]
as others have pointed out here, this could be caused by having incompatible versions of metro or metro subpackages in your project. ensure you delete any yarn/npm resolutions you have for metro, and remove metro packages from direct dependencies in your package.json
