### ISSUE TITLE
Expo Camera don´t work in expo sdk 50

### ISSUE THREAD

**Issue by ruimarcosjoao** [expo/expo#26884]
### Minimal reproducible example

https://github.com/ruimarcosjoao/bi-scanner

### Summary

I installed the expo-camera package to create a feature to add the functionality of reading QR codes from identity documents! However, whenever I run 
![Screenshot_1](https://github.com/expo/expo/assets/69318293/db6c72ba-a3cd-43fb-be2b-eed19fedee19)
`npx expo start --clear` and open it in expo go, I get the `error: node_modules\expo-router\entryjs: Cannot find module 'babel-plugin-expo-camera'`

I can't even use run any code due to this error

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.0 => 50.0.5
      expo-router: ~3.4.6 => 3.4.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by amandeepmittal** [comment]
Hey @ruimarcosjoao, the `plugin` configuration you've added [in the `babel.config.js`](https://github.com/ruimarcosjoao/bi-scanner/blob/master/babel.config.js) is what is causing this issue. This configuration is added in `app.json`. You already have `expo-router` plugin in app.json in the example you shared: https://github.com/ruimarcosjoao/bi-scanner/blob/432d428175211afdf37a4f5f2342081be6983319/app.json#L32.

Please remove the `plugins` from `babel.config.js` and add it under `app.json`.
