### ISSUE TITLE
Unable to access env var in .env file after updating packages to expo sdk 50 (only when building with detox)

### ISSUE THREAD

**Issue by kingyx3** [expo/expo#26898]
### Minimal reproducible example

https://github.com/kingyx3/issue-expo-sdk-50-env-var

### Summary

How to reproduce:

1. Clone minimal reproducible example into directory
2. yarn install
3. yarn && yes | npx expo prebuild --clean && detox clean-framework-cache && detox build-framework-cache && detox build -c ios.sim.release && detox test -c ios.sim.release

The previous commit involves a passing test that has fewer packages in package.json.

The issue has something to do with how the expo packages interact with each other (i think). Reproducible example is a copy of test case 5 below.
Combinations of packages I have tried:
![image](https://github.com/expo/expo/assets/28263244/c4f71789-ae81-4b39-b5b3-9b73ce571a8d)

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v21.5.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.4 => 50.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare
```

**Comment by elkortby** [comment]
Same here!
