### ISSUE TITLE
[expo-image] placeholder flicker

### ISSUE THREAD

**Issue by AlirezaHadjar** [expo/expo#26903]
### Minimal reproducible example

https://github.com/AlirezaHadjar/expoImageBug

### Summary

Hi 👋
Thank you for maintaining all expo amazing libraries. I have found a bug in expo-image which happens when you have 2 lists of images (e.g. 100 images) and each image has a placeholder. now when you mount and unmount each list, you will see a flicker. for a moment you see the placeholder and after a fraction of a second, you will see the actual image.
This isn't very pleasant when you have a condition to render a list in an application and users will see this flicker each time the list is mounted.

Here is a video of what I just explained. As you can see, I have 2 lists of 100 images. I can switch rendering each one based on the value of the switch component above. each time I change the state, the flicker happens.

https://github.com/expo/expo/assets/57192409/e5ee7ce7-5f47-4b58-94e0-5c8fc1850ee1

this problem doesn't occur if I use `cachePolicy={'memory'}`. but I don't want to use `memory` since it may lead to performance issues as I might have a large number of images.

I'm not sure if this is the expected behavior or not but if it is could please guide me on how to resolve it without using memory cache.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.0/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 33, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.22 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.9.3
    Expo Workflow: managed

**Comment by oliviercperrier** [comment]
Have a similar issue, my placeholder gets reloaded on every re render, even if the main image is already displayed causing a flicker.

**Comment by ChamaraWP** [comment]
I'm having this issue too any solution

**Comment by moxorama** [comment]
Still flicker, so I'm rolling back to React Native image

**Comment by bpeck81** [comment]
Same, this is busted. I have to stick with react-native-fast-image which has no issues.

**Comment by alialkorsani** [comment]
add prop  `transition={1000}` to the Image fix the issue

**Comment by OrJDev** [comment]
Been 7 months since this has been reported. Still facing this flickering issue, currently rolled back to React Native Image

**Comment by lukmccall** [comment]
I apologize for the delayed response; we overlooked this issue. 

The flickering in the example you provided appears to be caused by a difference in the default content fit for the final image compared to the placeholder. The default content fit for the src is set to `cover`, while for placeholders, it is set to `scale-down`. Adding `placeholderContentFit` seems to resolve the problem in your example.
```
<Image
  style={{
    width: "100%",
    height: "100%",
  }}
  source={{
    uri: image.urls.regular,
  }}
  placeholder={{ uri: image.urls.thumb }}
  placeholderContentFit="cover"
/>
```

**Comment by AlirezaHadjar** [comment]
Great callout, thanks 🚀
