### ISSUE TITLE
`useLocalSearchParams` behaves incorrectly with `initialRouteName` on web

### ISSUE THREAD

**Issue by mahaveer0496** [expo/expo#26908]
### Minimal reproducible example

https://github.com/mahaveer0496/expo-localparams-repro

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

`useLocalSearchParams` returns no params on the web during some renders _if_ `initialRouteName` is present.

In the example repo I've tried to replicate my app's behavior: if no param is present throw.

Route structure is as follows:

```
app
	[account]
		_layout.tsx
		foo.tsx
		index.tsx <-- localParams aren't available here if initialRouteName is present
	_layout.tsx
	index.tsx
```

I have this code in `[account]/_layout, index, foo` files

```js
 if (!useLocalSearchParams<{ account: string }>().account)
    throw new Error("No account");
```

If `initialRouteName` is specified, only the code in `[account]/index` throws, but not the one in `_layout.tsx`, which makes me guess this is an `index` page specific issue.

Video showing bug

https://github.com/expo/expo/assets/23198481/afb79ffd-e1b7-4c74-80e4-b49ed29f7c46

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.5 => 50.0.5 
      expo-router: ~3.4.6 => 3.4.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Should be fixed in SDK 52
