### ISSUE TITLE
Expo Video component doesn't load the uri

### ISSUE THREAD

**Issue by zRelux** [expo/expo#2691]
### Environment

  Expo CLI 2.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.4 - C:\Users\Leo\AppData\Roaming\npm\yarn.CMD
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/relux-4207dfca-69ae-4d46-8af3-542cb5d3e1c9.tar.gz

Target: IOS, Android

### Expected Behavior

The Video component should load the video uri from the state and play as soon as possible, but it is not capable of doing so.

### Actual Behavior

The APP component gets stuck on `await this._video.loadAsync(source, initialStatus);` for ever and doesn't run the other functions, but if you apply the source throw the component and remove that line adding     `source={{     uri: thisEpisode.assets.hls       }}` everything works fine

### Reproducible Demo

https://snack.expo.io/@relux/expo-video-not-working

**Comment by zRelux** [comment]
Could you give me an example?

**Comment by ide** [comment]
I mean just `<Video source={{ uri: thisEpisode.assets.hls }} >`.

**Comment by RickEyre** [comment]
Can confirm. It's absolutely broken. The `loadAsync` API is just hanging. No `then` or `catch` are executed on the promise. 

It works if I pass the props through the component.

**Comment by gsunsnackv** [comment]
I'm experiencing the same issue.

**Comment by gsunsnackv** [comment]
We are facing the same painful issue. After couple videos, the player stops working forever. I was able to made a repo easily as well Code: https://github.com/gsunsnackv/expo-video-load-async-stuck Snack: https://snack.expo.io/SJkdW-gm4

I'd like to share some of my observations. It seems that Android 9 can play a few more videos compare to older versions. But the whole thing is very random, it is not clear. Another thing is that if you use `androidImplementation: 'MediaPlayer'`, then older versions works very good, almost can play forever, but with that, Android 9 will fail a lot more, most time cannot even load the first video.

Code for `androidImplementation: 'MediaPlayer'` https://github.com/gsunsnackv/expo-video-load-async-stuck/tree/use-media-play-works-for-older-android Snack: https://snack.expo.io/S16nzbxQV
I hope this may help hunt down the problem

**Comment by gsunsnackv** [comment]
We also tried to not use loadAsync but use the uri property on video. We set a different key on the component each time to cause the old component to unmount and create a new one. And we let the uir property load the video. We also manually unload the video when component get unmount. Nothing works. https://github.com/gsunsnackv/expo-video-load-async-stuck/tree/unmount-everytime

**Comment by gsunsnackv** [comment]
We also tried to not use loadAsync but use the uri property on video. We set a different key on the component each time to cause the old component to unmount and create a new one. And we let the uir property load the video. We also manually unload the video when component get unmount. Nothing works. https://github.com/gsunsnackv/expo-video-load-async-stuck/tree/unmount-everytime

**Comment by JackHowa** [comment]
is there an update for this?

**Comment by zRelux** [comment]
I think they fixed it now by adding the downloadFirst parameter didn't test yet though
