### ISSUE TITLE
URL params not passing into nested stacks. 

### ISSUE THREAD

**Issue by Icvza** [expo/expo#26916]
### Minimal reproducible example

https://github.com/Icvza/expoRouterv3

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When passing params to a nested stack I keep getting string "[object object]" This does work in v2. 

In the (tabs) stack's index page Im calling this onPress
`    router.navigate({pathname: '/(two)', params: {something: `${encodeURIComponent(payload)}`}})
`
But receive this in the (/two) stack: 
From layout {"params": "[object Object]", "screen": "index"} 

I've tried router navigate, push, JSON.Stringify, and using a URL format (/(two)?something=something) maybe I'm missing something. Maybe I hacked it to make it work in v2 but maybe not. 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
      npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.5 => 50.0.5 
      expo-router: ~3.4.6 => 3.4.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

**Comment by Icvza** [comment]
Still getting the same thing after that merge

**Comment by kennethstarkrl** [comment]
try 
```js
router.navigate(`/(two)/${encodeURIComponent(payload)}`);
```
or
```js
router.navigate(`/(two)?myParam=${encodeURIComponent(payload)}`);
```

**Comment by Icvza** [comment]
Beautiful. Thank you!
