### ISSUE TITLE
Need to specific `unstable_enablePackageExports` on `metro.config` for monorepo

### ISSUE THREAD

**Issue by Zweird-958** [expo/expo#26926]
### Minimal reproducible example

https://github.com/Zweird-958/test

### Summary

I have a monorepo with packages which uses `exports` on `package.json`
If I don't specify `config.resolver.unstable_enablePackageExports = true`, I can't import my packages
But in [react-native doc](https://reactnative.dev/blog/2023/06/21/package-exports-support), it's specified in 0.73 by default this configuration should be enabled, and I'm using expo SDK 50.

I've got this error:
![image](https://github.com/expo/expo/assets/83603824/bbfd87aa-e7e9-44d4-bbfc-d439f7a9fe2b)

`metro.config.js`
```
/* eslint-disable @typescript-eslint/no-var-requires */
/** @type {import('expo/metro-config').MetroConfig} */
const { getDefaultConfig } = require("expo/metro-config")
const { withNativeWind } = require("nativewind/metro")
const path = require("path")
const projectRoot = __dirname
const workspaceRoot = path.resolve(projectRoot, "../..")
const config = getDefaultConfig(__dirname, {
  isCSSEnabled: true,
})
config.watchFolders = [workspaceRoot]
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
]
// eslint-disable-next-line camelcase
config.resolver.unstable_enablePackageExports = true

module.exports = withNativeWind(config, {
  input: "./src/global.css",
  configPath: "./tailwind.config.ts",
})
```

One of my `package.json`:

```
{
  "name": "@airneis/schemas",
  "version": "1.0.0",
  "description": "",
  "exports": {
    ".": "./src/index.ts"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "typecheck": "tsc --noEmit"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "typescript": "^5.3.3"
  }
}
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/Library/Caches/fnm_multishells/12840_1707129443180/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/Library/Caches/fnm_multishells/12840_1707129443180/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    Expo Workflow: managed

```

**Comment by byCedric** [comment]
Hi @Zweird-958! You are right that the blogpost mentioned "aiming to remove the unstable_ prefix for this feature ... and will enable Package Exports resolution by default.".

Unfortunately, the `packageExport` feature has not (yet) been promoted to stable, and because of that, is also not enabled by default yet. So, the error you encountered is correct, and you have to enable this if you want to use it.

Hope this helps!

**Comment by Zweird-958** [comment]
> Hi @Zweird-958! You are right that the blogpost mentioned "aiming to remove the unstable_ prefix for this feature ... and will enable Package Exports resolution by default.".
> 
> Unfortunately, the `packageExport` feature has not (yet) been promoted to stable, and because of that, is also not enabled by default yet. So, the error you encountered is correct, and you have to enable this if you want to use it.
> 
> Hope this helps!

Thank you @byCedric. It is recommanded to use `main` instead of `exports` or I can use `exports` ? And I saw [t3](https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/metro.config.js) using `exports` without use `unstable_prefix` do you know how they did it ?

Thank you.

**Comment by Mirthis** [comment]
> Thank you @byCedric. It is recommanded to use `main` instead of `exports` or I can use `exports` ? And I saw [t3](https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/metro.config.js) using `exports` without use `unstable_prefix` do you know how they did it ?
> 
> Thank you.

As per [this issue](https://github.com/t3-oss/create-t3-turbo/issues/953) I opened today I'm not sure the current solution in create-t3-turbo works (definetely it does not for me).

Adding `config.resolver.unstable_enablePackageExports` to the metro config seems to break some other packages that from what I can understand from the [metro documentation](https://metrobundler.dev/docs/package-exports) is not completely unexpected.

So the only solution I currently have found is by specifying the `main` property in `package.json` for the workspace I want to import in expo. 
I haven't been able to play around with this that much but I think the limitation is that all your exports need to be in the file specified in `main` and you cannot export from additional files in the same workspace (basically you have a [single entry point](https://nodejs.org/api/packages.html#package-entry-points) for the whole workspace/package).

Have you found any solution since the original post?

**Comment by The-White-Fang** [comment]
@Mirthis were you able to figure out any solution? I am running into a similar problem.

**Comment by Zweird-958** [comment]
> @Mirthis were you able to figure out any solution? I am running into a similar problem.

My solution is to create an `index` file in root of the folder and export all files in `src`.

**Comment by Mirthis** [comment]
> > @Mirthis were you able to figure out any solution? I am running into a similar problem.
> 
> My solution is to create an `index` file in root of the folder and export all files in `src`.

Yes, that's what I'm also doing. Haven't found any other way around it.

**Comment by The-White-Fang** [comment]
That is one way to do it, but it makes the `exports` useless.

**Comment by jmunckhof** [comment]
> I'm not exactly sure why, but I managed to get it to work.
> 
> I'm using [t3](https://github.com/t3-oss/create-t3-turbo) and added [`config.unstable_enablePackageExports = true;`](https://metrobundler.dev/docs/package-exports/) in [apps/expo/metro.config.js](https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/metro.config.js). However, I encountered a warning when starting with `pnpm dev`:
> 
> ```
> Unknown option "unstable_enablePackageExports" with value true was found.
> This is probably a typing mistake. Fixing it will remove this message.
> ```
> 
> It seems `unstable_enablePackageExports` is not recognized, but why? The `metro` package version in my `node_modules` is `0.80.7`, which should be recent enough. Maybe there's an issue with Expo?
> 
> To work around this, I patched the metro package to override all instances of `unstable_enablePackageExports` with `true` using `pnpm patch metro`. Here's my patch: https://gist.github.com/oney/c684757f145c953a2656b45055c482c8
> 
> Now, I can import components like `import { Button } from "@acme/ui/button";` with the following package configuration:
> 
> ```json
> {
>   "name": "@acme/ui",
>   "private": true,
>   "type": "module",
>   "main": "src/index.ts",
>   "exports": {
>     ".": "./src/index.ts",
>     "./button": "./src/button/index.ts"
>   },
> }
> ```

You have to add it to config.resolver as mentioned in [this blog](https://reactnative.dev/blog/2023/06/21/package-exports-support#enabling-package-exports-beta)
