### ISSUE TITLE
Modal not closing on router.push()

### ISSUE THREAD

**Issue by Eli-code1** [expo/expo#26922]
### Minimal reproducible example

https://github.com/Eli-code1/router-demo-modal-bug/tree/main

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When I attempt to push to a new screen inside a modal with `router.push()`, the screen pushes but the modal doesn't close.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.5 => 50.0.5
      expo-router: ~3.4.6 => 3.4.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by api-composer** [comment]
Hello,

I tried your repo and I can not reproduce a bug. I believe it is the intended behavior. The modal doesn't close when you push to a new route from it, it adds to the stack. If you want the modal to close you have to use replace instead of push. 

![26922](https://github.com/expo/expo/assets/155705867/f6abf96a-9c7e-4183-b4b3-1d445865e96c)

Am i getting this right?

**Comment by Eli-code1** [comment]
Hi Arman,

In router v2, the modal did close when I pushed to the next screen (my code was the same in my app between my update from v2 to v3). If this was a v3 update, that would make sense. Here's a look at that behavior on iOS where I feel it's more prevalent.
![Simulator Screen Recording - iPad (10th generation) - 2024-02-06 at 16 21 15](https://github.com/expo/expo/assets/94636503/827769cc-9831-4f4b-b8e5-6c4f82d800a4)

Thanks!

Eli

**Comment by Eli-code1** [comment]
Hi Arman,

I replied on GitHub, but I'm not sure if that makes its way to you. Here is
a copy of my response, in case it didn't go through:

In router v2, the modal did close when I pushed to the next screen (my code
was the same in my app between my update from v2 to v3). If this was a v3
update, that would make sense. Here's a look at that behavior on iOS where
I feel it's more problematic.
https://github.com/expo/expo/assets/94636503/827769cc-9831-4f4b-b8e5-6c4f82d800a4

Thanks!

Eli

**Comment by Jzuni97** [comment]
Any progress on this? Getting same issue.
expo: "^50.0.7",
expo-router: "3.4.7"
react-native: "0.73.4"

**Comment by Eli-code1** [comment]
@Jzuni97 I made a workaround by basically using `router.back()` and transferring any data previously passed between screens through `router.push()` using other methods. Still would be great to get a resolution on this @expo-bot!

**Comment by caseydierking** [comment]
I can confirm this is also an issue right now.

**Comment by lyonfuture** [comment]
Facing the same issue.

**Comment by moritzlang** [comment]
Same issue here.

**Comment by AustineA** [comment]
Is there any hack to bypass this issue?

**Comment by Eli-code1** [comment]
I mean, this is what I did @AustineA :



> I made a workaround by basically using `router.back()` and transferring any data previously passed between screens through `router.push()` using other methods. 

I suppose you can probably determine if a similar solution works in your case or not.

**Comment by qoobes** [comment]
`router.dismiss()` / `router.dismissAll()` does the trick for me. I had the same issue.

**Comment by dalehornidge** [comment]
router.back() seems to work for me. The docs are so bad for the expo router.

**Comment by Eli-code1** [comment]
> `router.dismiss()` / `router.dismissAll()` does the trick for me. I had the same issue.

Yeah, but it's still weird because you can't push to a new route that way. Also, @qoobes I'm impressed you found this function because the docs for it are very poorly located!

**Comment by qoobes** [comment]
@Eli-code1 yeah the docs are in need of improvement... Btw for the params, what you can do is this awful, horrible hack. You can then make a little patch to useRouter and add `dismissAndPush` as its own function. I'm considering making a pr for either docs or a hack like this on the weekend, since this is a genuinely frustrating bug. 

```ts
  router.dismissAll();
  setTimeout(() => {
    router.push("wherever");
  }, 0);
```

**Comment by Eli-code1** [comment]
@qoobes Wow! That works like a charm! You should definitely submit that as a pr; even if it's not merged, it could help bring more attention to this frustrating bug 😀.

I'll close this for now since @qoobes's solution works, but it still would be great for something officially supported/merged into the repo.

**Comment by syukranDev** [comment]
do this instead to get data refreshed.

router.back();
router.push('whatever');

**Comment by lsps9150414** [comment]
Hey @Eli-code1 thanks for raising this, maybe we should keep this issue open since it seems like a bug still?

**Comment by Eli-code1** [comment]
@lsps9150414 My situation was resolved, so that’s why I’d closed it but please reopen if it’s still causing you an issue. I just haven’t gone to check to see if it’s been resolved officially yet.
