### ISSUE TITLE
expo-splash-screen ios bare crash

### ISSUE THREAD

**Issue by hotaryuzaki** [expo/expo#26930]
### Minimal reproducible example

create bare expo project, downgrade to 0.18.2, create splash screen from the guide

### Summary

i followed this guide [here](https://github.com/expo/expo/tree/main/packages/expo-splash-screen#-installation-in-bare-react-native-projects) for iOS, but the app will crash when showing the splash screen.

my app using expo SDK 48 and max expo-splash-screen ver 0.18.2, i think the issue occurred because of the old version.
is it okay to upgrade just the expo-splash-screen?

error log look like this:
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: BrambangDev [22928]

...

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000018029232b   x5: 0x000000016d6650b0   x6: 0x000000000000006e   x7: 0x0000000000000000
    x8: 0x0000000105488240   x9: 0xe81e6b1c250e3973  x10: 0x0000000000000200  x11: 0x000000016d664be0
   x12: 0x0000000000000000  x13: 0x0000000180292353  x14: 0x0000000000000010  x15: 0x000000008383affb
   x16: 0x0000000000000148  x17: 0x0000000000000075  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000105488240  x21: 0x0000000000000103  x22: 0x0000000105488320  x23: 0x0000000000000000
   x24: 0xffffffff02000000  x25: 0x0000000000000000  x26: 0x0000000000000001  x27: 0x00000000211200d5
   x28: 0x0000000000000000   fp: 0x000000016d665020   lr: 0x00000001062471d0
    sp: 0x000000016d665000   pc: 0x00000001053849ec cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

...


  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"BrambangDev","byPid":22928},
```

this is the error detail from iPhone emulator: 
[iphone-error-log.txt](https://github.com/expo/expo/files/14164272/iphone-error-log.txt)

### Environment

this is my env:
```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 3.6.4 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/developer/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.5.2 
      expo: ~48.0.21 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
      react-native-web: ~0.18.7 => 0.18.12 
    Expo Workflow: bare

expo-splash-screen@0.18.2
```

**Comment by hotaryuzaki** [comment]
i tried update expo-splash-screen to latest 0.26.4 and showing an error
```
Error: Cannot find native module 'ExpoSplashScreen'
```

**Comment by hotaryuzaki** [comment]
i think i found the solution,
1. i update to 0.26.0
2. change Launch Screen File to SplashScreen (remove ".storyboard").

i think the guide need to update in this part
"4. Select or enter SplashScreen as the value for located option."

and i do not know if number 1 is needed or not, will it any issue expo SDK 48 using this version?? do i need to downgrade to 0.18.2??

**Comment by MatkoMilic** [comment]
My expo sdk 49 app crashes with ios only on real device, all after adding expo splash screen library, it works on android real device and emulator and it works on ios simulator but crashes on ios, any help? i get native module expo splash screen not found error.
