### ISSUE TITLE
Inconsistent `type` in barcode scan result when using expo-camera/next

### ISSUE THREAD

**Issue by steveliles** [expo/expo#26953]
### Minimal reproducible example

https://github.com/steveliles/expo-barcode-scanning-bug/blob/main/App.js

### Summary

Steps to reproduce:
- run the app in the repro repository with `expo run ios --device` and pick a real device with a camera
- scan an ean13 barcode
- notice that the type is reported as "org.gs1.EAN-13"
- now run the app in with `expo run android --device` and pick a real device with a camera
- scan an ean13 barcode
- notice that the type is reported as 32 (the number, not a string)

I have two issues:
1. When we configure the scanner we use "ean13", but the type is reported on iOS as "org.gs1.EAN-13". Its ok I guess, but a bit surprising that the type in the result does not match the type in the config, and there should probably be a list somewhere of what these result types will be (or perhaps constants to match against)?
2. Android is returning numbers instead of strings, inconsistent with iOS and quite opaque.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        Android NDK: 19.0.5232133
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: bare

**Comment by steveliles** [comment]
FWIW, it seems this is not really a _new_ issue. The code i'm upgrading from used constants from BarCodeScanner to set the barCodeTypes array in barcodeScannerSettings, and also when matching the result type. 

On android the constant `BarCodeScanner.Constants.BarCodeType.ean13` has the value 32 (number, not string), so I was unwittingly configuring on android using an array of numbers and then matching the types in scanner results against numbers, so everything hung together, kinda, provided you used the constants.

Now BarCodeScanner is deprecated, so using the constants isn't an option unless you are ok with warnings/strikethroughs, and there doesn't seem to be a replacement. 

The docs say the configuration should be from the set of allowed strings, e.g. "ean13", but there are no constants that I can find and i'm not using typescript, so there's no compiler to catch my misspellings, and now the configuration value ("ean13") does not match the returned type (32 on android, "org.gs1.EAN-13" on iOS).

**Comment by Bonnev** [comment]
Same thing here on Android using a real device. I saw in the [docs](https://docs.expo.dev/versions/v50.0.0/sdk/camera-next/#barcodescanningresult) that `type` should be a string, but in reality I get a number.

**Comment by Bonnev** [comment]
We are expecting activity from the expo team here.

**Comment by fxlui** [comment]
We're also seeing this issue.

**Comment by SocDario** [comment]
I have also experienced this issue. 
```
"dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.22",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.9",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.18",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.3",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10",
    "expo-dev-client": "~4.0.20",
    "expo-camera": "~15.0.14"
  }
```
onBarcodeScanned returns type:
```
export type BarcodeScanningResult = {
  type: string;
  data: string;
  raw?: string;
  cornerPoints: BarcodePoint[];
  bounds: BarcodeBounds;
};
```
But when I use Samsung Galaxy s21 to scan QR codes I get this type of response:
```
{
  boundingBox: BarcodeBounds;
  cornerPoints: BarcodePoint[];
  type: string;
  data: string;
  raw?: string;
  target: number
}
```
Why is there difference in actual response type and function return type? What is causing me most of the problems is inconsistency between bounds and boundingBox.
