### ISSUE TITLE
Issue on iOS Standalone TestFlight: Permissions.getAsync(Permissions.NOTIFICATIONS) returns status as granted always.

### ISSUE THREAD

**Issue by techpanga** [expo/expo#2695]
Hi

On iOS Standalone App,

After the below statement…
const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);

the variable “existingStatus” always gets the value as “granted”

After below statement…
const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);

the variable “status” always gets the value as “granted”

I am not sure how to RESET these permissions.

Also, this issue is mentioned here https://forums.expo.io/t/expo-29-0-on-ios-is-no-longer-resolving-permissions-askasync-promise-for-notifications/12044. Is the fix included in version 31.0.0?

Any help is greatly appreciated.

-thank you, dp.

**Comment by alexpchin** [comment]
@techpanga @EvanBacon Is this issue still active? I'm currently getting this:

```js
{
      "expires": "never",
      "permissions": {
        "notifications": {
          "allowsAlert": true,
          "allowsBadge": true,
          "allowsSound": true,
          "expires": "never",
          "status": "undetermined",
        },
      },
      "status": "undetermined",
    }
```

When running this on the iOS simulator:

```js
Permissions.askAsync(Permissions.NOTIFICATIONS)
      .then(console.log)
      .catch(console.warn);
```

**Comment by lukmccall** [comment]
This bug was fixed so I'm closing this issue.

**Comment by techpanga** [comment]
I still see this issue on SDK 35.
