### ISSUE TITLE
[SDK 50] --configure-on-demand ignores custom Maven repository

### ISSUE THREAD

**Issue by nbennink** [expo/expo#26963]
### Summary

I am upgrading from SDK 48 to SDK 50. Everything is working fine except for the `expo run:android` command.

I have package installed in my node_modules which gets a private SDK from a custom Maven repository. The build.gradle of this package adds the repository like this:
```
rootProject.allprojects {
    repositories {       
        maven {
            url "MY_CUSTOM_REPOSITORY_URL"
            credentials {
                username = USERNAME
                password = PASSWORD
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
```

This worked perfectly with SDK 48 but now with SDK 50 I get this error:
```
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.myorg:mypackage:8.3.1.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/myorg/mypackage/8.3.1/mypackage-8.3.1.pom
       - https://repo.maven.apache.org/maven2/com/myorg/mypackage/8.3.1/mypackage-8.3.1.pom
       - file:/Users/myname/Documents/expo50/node_modules/jsc-android/dist/com/myorg/mypackage/8.3.1/mypackage-8.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/myorg/mypackage/8.3.1/mypackage-8.3.1.pom
       - https://www.jitpack.io/com/myorg/mypackage/8.3.1/mypackage-8.3.1.pom
       - file:/Users/myname/Documents/expo50/node_modules/react-native/android/com/myorg/mypackage/8.3.1/mypackage-8.3.1.pom
     Required by:
         project :app > project :react-native-mycustompackage
```

Meaning that this custom sdk cannot be found. When looking at the locations where it searched for this sdk it does not show the custom Maven repository defined in the packages' `build.gradle`. It seems that this is completely ignored.

The interesting thing is that my CI environment still builds the app. After digging into the CLI I noticed the only difference is the `--configure-on-demand` flag that's on `expo run:android`. Without this flag the app builds as expected.
https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/start/platforms/android/gradle.ts#L73

Can this be caused by the new Gradle version used by React Native 0.73?

### What platform(s) does this occur on?

Android

### SDK Version

50.0.6

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 3.1.1 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/nieck/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

This can be reproduced with a new Expo project where you immediately run `expo prebuild`. We have an older project but this environment comes close enough.

I sadly cannot share an exact reproduce repository here since the SDK we use here is a private repository.

**Comment by gstcarv** [comment]
I've faced the same problem. I don't know exactly, but looks like [this file is the issue.](https://github.com/facebook/react-native/blob/e70caeec108ffd49677849ecc7cdeebbde0ad6eb/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/DependencyUtils.kt). I think that somehow the `configureRepositories` method is subscribing to the maven repositories defined in `rootProject.allprojects`.

My temporary solution was removing `rootProject.allprojects` and set only `repositories { ... }` on my package's `build.gradle` and adding an extra credentials on DependencyUtils file, like:

```kt
  fun Project.mavenRepoFromUrl(url: String): MavenArtifactRepository =
      project.repositories.maven { 
        it.url = URI.create(url)      
        it.credentials.username = "username"
        it.credentials.password = "password"
   }
```

**Comment by gstcarv** [comment]
I've faced the same problem. I don't know exactly, but looks like [this file is the issue](https://github.com/facebook/react-native/blob/e70caeec108ffd49677849ecc7cdeebbde0ad6eb/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/DependencyUtils.kt). I think that somehow the `configureRepositories` method is subscribing to the maven repositories defined in `rootProject.allprojects`.

My temporary solution was removing `rootProject.allprojects` and set only `repositories { ... }` on my package's `build.gradle` and adding an extra credentials on DependencyUtils file, like:

```kt
  fun Project.mavenRepoFromUrl(url: String): MavenArtifactRepository =
      project.repositories.maven { 
        it.url = URI.create(url)      
        it.credentials.username = "username"
        it.credentials.password = "password"
   }
```

**Comment by jessicaplatter** [comment]
@nbennink @gstcarv 

I am running into this issue. My organization blocks external repositories so I cannot access anything from 
`https://oss.sonatype.org/content/repositories/snapshots/`
but it keeps defaulting to this repo instead of our internal ones.

I removed the allprojects section from my android/build.gradle but still have the buildscript repositories section
```
buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '34.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '23')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '34')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '34')
        kotlinVersion = findProperty('android.kotlinVersion') ?: '1.9.10'
        ndkVersion = "26.3.11579264"
    }
    repositories {
        google()
        mavenCentral()
        maven {
            url "example-internal-url"
        }
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath('com.facebook.react:react-native-gradle-plugin')
    }
}
```

I have a repositories section and buildscript repositories section in my android/app/build.gradle
```

buildscript {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        //// a lot of internal URLs
    }
}

// internal repos
repositories {
     //// a lot of internal URLs
}
```

It is still going to oss.sonatype.org though. Is there something I am missing? Did you find something else to do to avoid the external URL?

Any help would be appreciated.

**Comment by gstcarv** [comment]
@jessicaplatter 

Have you tried to check [this react-native file](https://github.com/facebook/react-native/blob/e70caeec108ffd49677849ecc7cdeebbde0ad6eb/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/DependencyUtils.kt#L35)? Maybe it can work if you use patch-package changing `oss.sonatype` repo to your internal sources.

**Comment by nguyen315** [comment]
> The interesting thing is that my CI environment still builds the app. After digging into the CLI I noticed the only difference is the --configure-on-demand flag that's on expo run:android. Without this flag the app builds as expected.
https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/start/platforms/android/gradle.ts#L73

Thanks for this! It saved me days of work. Since I don’t want private credentials in my `build.gradle` file, I simply removed the `--configure-on-demand` flag from the `gradle.ts` file. The build worked as expected.
