### ISSUE TITLE
Invisible characters in some datamatrix barcode data on Android only

### ISSUE THREAD

**Issue by steveliles** [expo/expo#26974]
### Minimal reproducible example

https://github.com/steveliles/expo-barcode-scanning-bug/blob/invisible-characters/App.js

### Summary

I'm building an app that needs to scan ean13 barcodes and datamatrixes that contain product info.

Scanning works well on iOS for both types.

Scanning a datamatrix on Android often results in data that contains hidden characters (specifically character code 29, "group separator"), usually as the first character, but sometimes more than once in the string.

This prevents the parsing lib we're using from being able to parse the code correctly, since the first character in the string is quite often a group separator instead of a number. Pretty hard to spot why since, to the eye, the strings look the same!

I'm not actually clear which platform is at fault here, but I consider this a bug because the platforms are not consistent. If both returned the data with the invisible characters, probably fair enough ... if both removed the invisible characters, also fair enough. But inconsistencies across platforms make for hard to catch bugs.

(note: if checking out the repro, make sure to use the correct branch "invisible-characters", as i've branched the same repo to report a couple of issues now).

To replicate:
 - check out the invisible-characters branch of the repro repo
 - scan one of the codes below on Android
 - check the log to see the comparison of the strings before/after invisible characters are removed
 - repeat on iOS, note that there is no difference in the before/after strings on that platform except for the last one which does contain 2 invisible characters, but is still inconsistent across platforms since android contains 3

Workaround:
 - remove "group separator" character with `data.replace(/\u001D/g, "")` (only necessary on Android, but not harmful on iOS)

Sample matrixes that exhibit the issue:

![matrix-1](https://github.com/expo/expo/assets/441745/d7707978-32a9-4d2c-a226-b2f988ea4be2)
android output:
```
 LOG  {"data": "010123456789012815051231", "first": "", "length": 25}
 LOG  {"data_cleaned": "010123456789012815051231", "first": "0", "length": 24}
```
iOS output:
```
 LOG  {"data": "010123456789012815051231", "first": "0", "length": 24}
 LOG  {"data_cleaned": "010123456789012815051231", "first": "0", "length": 24}
```

![matrix-2](https://github.com/expo/expo/assets/441745/1c64729a-ac2c-449e-ae5f-5d637ac8dd9c)
android output:
```
 LOG  {"data": "0100614141999996901234567890", "first": "", "length": 29}
 LOG  {"data_cleaned": "0100614141999996901234567890", "first": "0", "length": 28}
```
ios output:
```
 LOG  {"data": "0100614141999996901234567890", "first": "0", "length": 28}
 LOG  {"data_cleaned": "0100614141999996901234567890", "first": "0", "length": 28}
```

![matrix-3](https://github.com/expo/expo/assets/441745/37d974a6-5a11-49ed-b08d-5e9dfbba3d7f)
android output:
```
 LOG  {"data": "01034531200000111719112510ABCD1234", "first": "", "length": 35}
 LOG  {"data_cleaned": "01034531200000111719112510ABCD1234", "first": "0", "length": 34}
```
ios output:
```
 LOG  {"data": "01034531200000111719112510ABCD1234", "first": "0", "length": 34}
 LOG  {"data_cleaned": "01034531200000111719112510ABCD1234", "first": "0", "length": 34}
```

![matrix-5](https://github.com/expo/expo/assets/441745/21eb474d-fca3-436a-a1f0-05fdbb94272f)
android output:
```
 LOG  {"data": "01034531200000111719112510ABCD1234", "first": "", "length": 35}
 LOG  {"data_cleaned": "01034531200000111719112510ABCD1234", "first": "0", "length": 34}
```
ios output:
```
 LOG  {"data": "01034531200000111719112510ABCD1234", "first": "0", "length": 34}
 LOG  {"data_cleaned": "01034531200000111719112510ABCD1234", "first": "0", "length": 34}
```

The next one is unusual in that it also produces hidden characters on iOS, but not the one at the start of the string that causes parsing to break:

![matrix-4](https://github.com/expo/expo/assets/441745/9000b375-fb12-4507-bc93-a61db11d4096)
android output:
```
 LOG  {"data": "20011111122821000001240ActiveBarcode", "first": "", "length": 39}
 LOG  {"data_cleaned": "20011111122821000001240ActiveBarcode", "first": "2", "length": 36}
```
ios output:
```
 LOG  {"data": "20011111122821000001240ActiveBarcode", "first": "2", "length": 38}
 LOG  {"data_cleaned": "20011111122821000001240ActiveBarcode", "first": "2", "length": 36}
```

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        Android NDK: 19.0.5232133
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: bare
```

**Comment by ifguido** [comment]
I have a similar problem, but the other way around. On iOS, invisible characters are not scanned (�). On Android, they scan well in PDF-417.

**Comment by lethib** [comment]
I am facing the same problem, but on iOS. As @ifguido mentioned, the "group separator" (**GS**) hidden character (`\u001d`) is not scanned for a given version of iOS with Expo SDK 51. 

In my case, I need to find the **GS** within the datamatrix data string to find the end of a product serial number. In some cases, the **GS** appears in the data string, in other cases, it doesn't.

Here is the investigation I have done 👇
| Platform | OS Version | Expo SDK Version | Comments |
| :---: | :---: | :---: | :--- |
| iOS | 16.0.3  | 51 | The **GS** is not present in the data string at all 👉 impossible to find the end of my product serial number ❌ |
| iOS | 16.1.1 | 51  | The **GS** is only present within the data string ✅ |
| iOS | 17.X.Y | 51  | The **GS** is only present within the data string ✅ |
| iOS | 18.X.Y (beta) | 51  | The **GS** is only present within the data string ✅ |
| Android | 14 | 51  | The **GS** is only present within the data string **AND** at the start of the data string ✅ |

So I have been able to also reproduce what @steveliles is mentioning 👉 it seems that on iOS the **GS** is never present at the start of the datamatrix data string (which is not a huge problem). But for a special configuration (expo 51 and iOS 16.0.3), the **GS** is not scanned at all.

**Comment by lethib** [comment]
Here for an update. I have updated the iPhone that was with the 16.0.3 OS Version to the current latest version (17.5.1) and the **GS** in the middle of the data string has been correctly read. ✅
