### ISSUE TITLE
[expo-av] playThroughEarpieceAndroid not working correctly

### ISSUE THREAD

**Issue by mudioo** [expo/expo#26972]
### Summary

I am developing an audio player where the sound should come from the earpiece of the phone. It works without any problems on iOS. On Android, the phone switches sometimes to the speaker when I update the source of the audio file. If I pause the audio and play it again the same error happen sometimes.

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 5.3.0
    Expo Workflow: bare

### Minimal reproducible example

const [sound, setSound] = useState() 
const [audioLoading, setAudioLoading] = useState(false)
const [audiosource, setAudioSource] = useState()

     useEffect(()=> {
        if(audiosource){
           loadAudio()
        }
     },[audiosource])
  
    const loadAudio = async () => {
     setAudioLoading(true)

     if(sound){
     await  sound.unloadAsync()
    }

      try {
        await Audio.setAudioModeAsync({
          playsInSilentModeIOS: true,
          allowsRecordingIOS: true,
          interruptionModeIOS: InterruptionModeIOS.DoNotMix,
          interruptionModeAndroid: InterruptionModeAndroid.DoNotMix,
          staysActiveInBackground: true,
          playThroughEarpieceAndroid: true,
        });

        const { sound, status } = await Audio.Sound.createAsync({
          uri: audiosource,
        });

        setSound(sound);
        setAudioLoading(false);
      } catch (error) {
        console.error("Error loading audio:", error);
   
      }
    }
  };

   const playSound = async ()=> {
       await sound.playAsync()
   }

**Comment by JosDaw** [comment]
Experienced the same issue. Were you ever able to resolve the issue?
