### ISSUE TITLE
[Camera] [Android] takePictureAsync() takes a long time to resolve

### ISSUE THREAD

**Issue by gdebre** [expo/expo#26971]
### Minimal reproducible example

https://github.com/gdebre/expo_camera_test

### Summary 
When taking a picture, if the camera and the subject is not moving/shaking, the picture is taken fast (about 250ms).

**_But_** if the picture is taken while shaking/moving the camera or having a moving subject, taking the picture can take up to 2500ms max :

Basically the library behave like that : 

**If** no moving/shaking (phone or subject) then picture is taken fast (≈ 250ms)
**else if** shaking (phone or subject) then wait for no shaking then take photo
**but if** still shaking after 2500ms take the photo no matter what.

### Things to note

- This problem is solved if useCamera2Api={true} BUT the Camera2Api image feed is zoomed in which is far from ideal. Meaning useCamera2Api={false} FOV is the same as the native phone camera app, which is not the case for useCamera2Api={true}

- This happens on Android, i don't have the tools to test it on IOS

### Basic code 

 ```
const cameraRef = useRef(null);


  const takePicture = () => {
    if (cameraRef.current) {
      const start = Date.now();
      
      cameraRef.current
        ?.takePictureAsync({
          skipProcessing: true,
        })
        .then((photoData) => {

          console.log(`Delay after takePictureAsync: ${Date.now()- start} ms`);

          setImageUri(photoData.uri);
        });
    }
  };

 <Camera
          autoFocus={false}
          style={[styles.camera, { width: phoneScreenWidth, height: phoneScreenWidth * (4 / 3) }]}
          type={type}
          ratio={cameraRatio}
          ref={cameraRef}
          useCamera2Api={false}
        >
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1
      expo: ~50.0.6 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by mcrstudio** [comment]
This also seems to be the case with what I'm seeing. My issue is showing much longer times than 2.5 seconds in some cases, up to 5 seconds.

**Comment by saulojoab** [comment]
In case anyone stumbles upon this, I think this is due to the `quality` parameter on `takePictureAsync()`. I think the default setting takes a picture that is too high quality, which takes longer to process.

Lowering it to 0.3 has fixed this issue for me.
```ts
const image = await cameraRef.current?.takePictureAsync({
   base64: true,
   quality: 0.3,
});
```

**Comment by IamDushu** [comment]
Yes, This is an issue still, why is it closed? when it's not resolved yet 🤷‍♂️

**Comment by Vanclief** [comment]
@RohovDmytro did you not have issues with camera orientation by disabling `skipProcessing`?

**Comment by RohovDmytro** [comment]
> [@RohovDmytro](https://github.com/RohovDmytro) did you not have issues with camera orientation by disabling `skipProcessing`?

No, but for the reason that orientation change is disabled.
