### ISSUE TITLE
Hi, there is no bound value for onBarCodeRead

### ISSUE THREAD

**Issue by RaphaelChua** [expo/expo#2699]
Hi, how do you add the bound value for the onBarCodeRead?

**Comment by EvanBacon** [comment]
`onBarCodeRead` is deprecated. Use `onBarCodeScanned` instead. AFAIK Neither function has a [bound value](https://github.com/react-native-community/react-native-camera/blob/a5a93a73c29bdeced8620bb71c0b86ce49a86f1d/ios/RCT/RCTCameraManager.m#L989-L997). Please open a canny request. https://expo.canny.io/feature-requests

**Comment by alamothe** [comment]
Looks like TypeScript definitions don't know about `onBarCodeScanned`... What should we do?
