### ISSUE TITLE
TexInput with custom fonts crash, sometimes...

### ISSUE THREAD

**Issue by yestoall** [expo/expo#27]
yes it's really weird, it crash sometimes, other times works perfect.

![simulator screen shot 18 dec 2016 09 46 39](https://cloud.githubusercontent.com/assets/29780/21292459/e69fe382-c506-11e6-9874-80fdbbf0447a.png)

this is the error when program is compiled, after press escape the app works ok, with the font loaded.

of course i'm preloading the fonts in the good way

**Comment by brentvatne** [comment]
share the code please! :)
