### ISSUE TITLE
[docs] Expo BarCodeScanner deprecated

### ISSUE THREAD

**Issue by justinkx** [expo/expo#27015]
### Summary

In the documentation for Expo BarCodeScanner, it shows **Deprecated: This library will no longer be available from SDK 51.We recommend using [expo-camera/next](https://docs.expo.dev/versions/latest/sdk/camera-next) which has barcode scanning built-in instead**.
But in `expo-camera/next` there is no equivalent replacement method for **BarCodeScanner.scanFromURLAsync**

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/#barcodescannerscanfromurlasyncurl-barcodetypes

**Comment by justinkx** [comment]
> scanFromURLAsync

I actually need to Scan bar codes from the image given by the URL (base64). **Expo Camera (Next)** or **Expo Camera** don't provide a method to do so atm.

**Comment by ARIARCHI-MZ** [comment]
The migration to `CameraView` doesnt work in my code. 
i don't get any error. it seems the functionality of scanner doesnt work, the camera opens but it doesnt scan Qrcode from image. I followed the instruction and change the code from 
**<BarCodeScanner onBarCodeScanned={scanned ? undefined : handleBarCodeScanned} />**
to
**<CameraView
            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
           barCodeScannerSettings={{
            barCodeTypes: ["qr", 'aztec','ean13','ean8','qr','pdf417','upc_e','datamatrix','code39','code93','itf14','codabar','code128','upc_a' ],
          }}
          />**
I have to mention that scanner works well with **BarCodeScanner**. all permission is granted. nothing scanned but camera opens
is there any solution?

**Comment by victorosorioparis** [comment]
This is being handled very weirdly...

The actual expo-camera DOES NOT have barcode reading capabilities and thus asks to install barcode-scanner

It is still a functionality, apparently, of the expo-camera/next package which is not supposed to be stable (and does not come installed with the normal expo-camera install)

I don't think anything should be deprecated until there is a stable alternative around. /next is not it

**Comment by Wowso** [comment]
> The migration to `CameraView` doesnt work in my code. i don't get any error. it seems the functionality of scanner doesnt work, the camera opens but it doesnt scan Qrcode from image. I followed the instruction and change the code from **<BarCodeScanner onBarCodeScanned={scanned ? undefined : handleBarCodeScanned} />** to **<CameraView onBarCodeScanned={scanned ? undefined : handleBarCodeScanned} barCodeScannerSettings={{ barCodeTypes: ["qr", 'aztec','ean13','ean8','qr','pdf417','upc_e','datamatrix','code39','code93','itf14','codabar','code128','upc_a' ], }} />** I have to mention that scanner works well with **BarCodeScanner**. all permission is granted. nothing scanned but camera opens. **_Expo is updated to version 50 "expo-barcode-scanner": "~12.9.2", "expo-camera": "~14.0.4",_** Expo-camera is updated to the latest version is there any solution?

<CameraView
          facing="back"
          onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
          barCodeScannerSettings={{
            barCodeTypes: ["qr"],
          }}
          style={StyleSheet.absoluteFillObject}
        >

onBarCodeScanned -> onBarcodeScanned

Be careful with the spelling - I didn't, and when I checked, it was case insensitive.

**Comment by Wowso** [comment]
> The migration to `CameraView` doesnt work in my code. i don't get any error. it seems the functionality of scanner doesnt work, the camera opens but it doesnt scan Qrcode from image. I followed the instruction and change the code from **<BarCodeScanner onBarCodeScanned={scanned ? undefined : handleBarCodeScanned} />** to **<CameraView onBarCodeScanned={scanned ? undefined : handleBarCodeScanned} barCodeScannerSettings={{ barCodeTypes: ["qr", 'aztec','ean13','ean8','qr','pdf417','upc_e','datamatrix','code39','code93','itf14','codabar','code128','upc_a' ], }} />** I have to mention that scanner works well with **BarCodeScanner**. all permission is granted. nothing scanned but camera opens. **_Expo is updated to version 50 "expo-barcode-scanner": "~12.9.2", "expo-camera": "~14.0.4",_** Expo-camera is updated to the latest version is there any solution?

#https://github.com/expo/expo/blob/9a304666693684fa5429b1b11773b0e07bdea3ce/packages/expo-camera/src/next/Camera.types.ts#L392

Be careful with your spelling. It was not case sensitive.

The official documentation and the actual function are spelled differently.

**Comment by ARIARCHI-MZ** [comment]
Thank you so much for answering me

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JmarkMunda** [comment]
I missed that! Thank you @Wowso

**Comment by viiicky** [comment]
+1

How do I scan a barcode from an image using expo-camera?

**Comment by vanntrong** [comment]
> +1
> 
> How do I scan a barcode from an image using expo-camera?

I have the same question with you

**Comment by justinkx** [comment]
In the latest documentation , It adds support to **scanFromURLAsync** method
https://docs.expo.dev/versions/latest/sdk/camera/#camerascanfromurlasyncurl-barcodetypes

**Comment by eugenegalaxy** [comment]
I did migration from expo-barcode-scanner to expo-camera and could not scan a single QR-code.

FOUND A FIX:

Have to add 'barcodeScannerEnabled' prop to <CameraView/> that was not mentioned in the official guide: https://github.com/expo/fyi/blob/main/barcode-scanner-to-expo-camera.md

My component:

<CameraView
      barcodeScannerEnabled
      onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
/>
