### ISSUE TITLE
Local URIs for Assets are being URL-Encoded Twice

### ISSUE THREAD

**Issue by juancarlosfarah** [expo/expo#2701]
### Environment

```
Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/opt/node@8/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 31.0.5 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: 2.18.2 => 2.18.2
    npmGlobalPackages:
      expo-cli: 2.3.8

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/react-epfl-c994e2d3-5131-4821-b4db-df6e6dd3284f.tar.gz
```

Running on the iOS simulator.

### Steps to Reproduce

I recently updated to Expo SDK 31 and it looks to me like `Asset` local URIs are being url-encoded twice. Therefore I see paths like the following:

```
.../Library/Caches/ExponentExperienceData/%2540react-epfl%252Fgraasp/ExponentAsset-00643c1d9e497681ceda68f702582183.html
```
Where `%2540` is double-encoding of `%40` and `%252F` of `%2F`.

When saving the `Asset` the path with `%40` and `%2F` does exist locally, but not the one that has been double-encoded.

My code, which was working with SDK 30, does the following:

1. Create an `html`-type `Asset` from a web resource.
2. Load the `Asset` in a `WebView` using its `localUri`.

### Expected Behaviour

When I pass the `localUri` of an `Asset` to a `WebView` for rendering, the `WebView` should render fine.

### Actual Behaviour

The `localUri` of the `Asset` seems to be encoded twice, resulting in the file not being found when the `WebView` tries to retrieve it.

I get a warning like the following:

```
[15:18:50] [Unhandled promise rejection: Error: Unable to open URL: file:///.../Library/Caches/ExponentExperienceData/%2540react-epfl%252Fgraasp/ExponentAsset-6c8f176f808f51a7e8596966172f5d1d.html]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:146:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:55 in <unknown>
- ... 5 more stack frames from framework internals
```

### Reproducible Demo

Here is a reproducible demo:

https://snack.expo.io/@juancarlosfarah/issue-with-asset-encoding

You can see in the logs how the `localUri` is being url-encoded twice.

Note that although in both the `html`-type `Asset` case and the `jpg`-type `Asset` case the `localUri` is being encoded twice, it does not affect an `Image` component from rendering, but it does affect a `WebView` component from rendering. Maybe because in some cases there is double decoding going on.

Also note that if you change the `WebView` to use the `uri` as a `source` instead of the `localUri`, the `WebView` renders immediately, but otherwise in the example as is, the `WebView` keeps on trying to load.

Locally I get a big yellow warning, but that does not happen on the Snack.

**Comment by juancarlosfarah** [comment]
I just dug deeper and it turns out that the issue with the `WebView` is due to this issue in ReactNative:

https://github.com/facebook/react-native/issues/20835

The `WebView` is now loading fine.

The double-encoding is clearly still happening, so I'm not sure if I should keep this issue open or go ahead and close it.

**Comment by peterkuiper** [comment]
This also happens in SDK 30
