### ISSUE TITLE
TypeError: res.appendHeader is not a function

### ISSUE THREAD

**Issue by oliviercperrier** [expo/expo#27028]
### Summary

Getting the following error when trying to run the default project from the doc for expo SDK 50:

TypeError: res.appendHeader is not a function
    at respond (/Users/oliviercastro-perrier/Desktop/my-app-failing/node_modules/@expo/server/src/vendor/http.ts:94:11)
    at /Users/oliviercastro-perrier/Desktop/my-app-failing/node_modules/@expo/server/src/vendor/http.ts:38:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### What platform(s) does this occur on?

Web

### SDK Version

50

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 3.16.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

npx create-expo-app@latest --template tabs@50

**Comment by BlueSkyCaps** [comment]
Please upgrade your node.js version, as I did before, your version is v16.16.0. I upgraded it to v20.11.0, restarted the project and everything became ok!

**Comment by oliviercperrier** [comment]
@BlueSkyCaps Did work. Completely forgot to upgrade my node.. Thanks Closing this
