### ISSUE TITLE
[docs] Bundle analysis with hermes

### ISSUE THREAD

**Issue by jmatsushita** [expo/expo#27022]
### Summary

https://docs.expo.dev/guides/analyzing-bundles/ provides instructions to use `source-map-explorer` with both native and web JS bundles. However it doesn't specify that the instructions will only work on native if the `jsc` engine is selected. By default, with Hermes, the location `'dist/_expo/static/js/ios/*.js` only contains `hbc` and `hbc.map` files.

### Link to the related docs page

https://docs.expo.dev/guides/analyzing-bundles/ 

### Anything else?

Is there an alternative with Hermes? Do the results produced by switching to `jsc` and running source-map-explorer apply to the hermes bundle?

**Comment by fuelkoy** [comment]
This is an important one.

Is there a way to analyze bundles on the files generated through eas update? It would be really good to see and analyze of what the bundle consists of

**Comment by jedahu** [comment]
You need to add the `--no-bytecode` option to `expo export`.

It's easy to miss in the documentation because it's mentioned only once in a code block comment.
