### ISSUE TITLE
FileSystem.readAsStringAsync base64 result is huge

### ISSUE THREAD

**Issue by clems36** [expo/expo#2703]
### Environment

Expo CLI 2.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.1 - C:\Users\Student\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Users\Student\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  2.3.0.0 AI-162.4069837

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/emixis-82436675-9e02-4a6f-bb66-5660cf37149b.tar.gz

### Steps to Reproduce

Call `DocumentPicker.getDocumentAsync` then `FileSystem.readAsStringAsync` to read the file as `base64`

``` javascript
const response: IDocumentPickerResponse = await DocumentPicker.getDocumentAsync({
    copyToCacheDirectory: false,
    type: '*/*',
});

const base64: string = await FileSystem.readAsStringAsync(
    response.uri,
    {
        encoding: FileSystem.EncodingTypes.Base64,
    });

console.log(base64.length);
```

### Expected Behavior

My goal is to send the base64 to a server using webservices. I expected the base64 to be light enough to achieve that.

### Actual Behavior

The base64 of a file that weights approx 3.9 Mo is 5 250 000 chars long (i can't even log it). When I try sending this to the server the request fails because the payload is too long. 

Moreover, I'm getting this warning when saving it to redux:

![chrome_2018-11-13_18-00-23](https://user-images.githubusercontent.com/6041593/48429777-10dae580-e76e-11e8-808c-a07240bd9111.png)

The app even crashes when the size of the file exceeds approx 8 Mo. Logcat's stack trace can be found here https://justpaste.it/6ss56

Is there a way to reduce the base64's size ?

**Comment by clems36** [comment]
I guess paging the data could be an option but that would mean changing the back-end and I currently don't have hands on that. 

I can't seem to make it work using the Blob API, would you mind giving a quick example ?

**Comment by clems36** [comment]
@EvanBacon can you help ?

**Comment by EvanBacon** [comment]
Works for me: https://snack.expo.io/@bacon/documentpicker-to-blob

**Comment by clems36** [comment]
I ran your snack on my device and the result is the same:
![cmd_2018-12-04_08-35-14](https://user-images.githubusercontent.com/6041593/49426068-ac74da00-f79f-11e8-904c-2146d012856a.png)

**Comment by clems36** [comment]
Thanks for referencing this @atrauzzi i was able to fix this using @sjchmiela's workaround: https://github.com/expo/expo/issues/2402#issuecomment-443726662

**Comment by atrauzzi** [comment]
@clems36 - Let me know if you have any issues accessing the underlying data.  I'm finding that it didn't quite work...

**Comment by clems36** [comment]
I was able to make it work as intended, here's how I used it:

``` js
const blob: Blob = await new Promise((resolve: Function, reject: Function): void => {
    const xhr: XMLHttpRequest = new XMLHttpRequest();
    xhr.onload = (): void => {
        resolve(xhr.response);
    };
    xhr.onerror = (): void => {
        reject(new TypeError('Network request failed'));
    };
    xhr.responseType = 'blob';
    xhr.open('GET', uri, true);
    xhr.send(null);
});
let base64: string;
const reader: FileReader = new FileReader();
reader.readAsDataURL(blob);
reader.onloadend = (): void => {
    const toString: string = reader.result.toString();
    base64 = toString.substring(toString.indexOf(',') + 1);
    this.sendAttachment(base64, name, size); // api call
};
```

**Comment by atrauzzi** [comment]
Ah, so you're still using base64.

My focus is avoiding the hop from base64 which basically results in loading your entire file into the JavaScript VM (expensive!).

I suspect there's power and performance issues with this.  It also causes your data over the wire to bloat considerably.

**Comment by clems36** [comment]
Ah ok i didn't get that. Yep this is surely not the best way of doing it but for my needs this'll do for now... If you come across something better though i'm interested.

**Comment by atrauzzi** [comment]
Maybe! 😄 
I guess it would depend on what your `sendAttachment` method does, but if you don't need to do any processing on the broken Blob (I presume you can't because we can't get bytes! 😠 ), passing it back to `fetch` seems to preserve binary data transfer without requiring any conversion to base64:

```typescript
await fetch(uploadUri, {
    method: "PUT",
    body: file, // This is the broken Blob instance
    headers: {
        "content-type": file.type,
    },
});
```

I added a summary of what I think is happening in my linked ticket, feel free to shoot me a 👍 over there..  I hope the RN team has the time and the will to fix this, it's a pretty glaring breakage.  I have standard libraries built on top of axios for data access in my organization.  They're basically out of the question for binary data transfer until this is resolved.
My hope is I don't have to struggle too much to convey the importance over remaining compatible with the fetch and Blob specs.
