### ISSUE TITLE
[Web] Images do not render when exporting as static or single page html

### ISSUE THREAD

**Issue by mduthilleul** [expo/expo#27037]
### Summary

Starting from the `Navigation (TypeScript)` template I have not managed to show images when exporting as static or single HTML page.
I use `<Image resizeMode='contain' src={require('../../assets/images/icon.png')} style={{width: 200, height: 200}} />` to display the image.
It works well when serving locally via metro.

### SDK Version

50

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.0.0 - ~/.nvm/versions/node/v21.0.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - ~/.nvm/versions/node/v21.0.0/bin/npm
      Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0, 34.0.0, 34.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/mduthilleul/expo-bug-demo

Image defined in `app/(tabs)/index.tsx`
npm run web:static to build and serve the page.
Image does not appear on the page.

**Comment by EvanBacon** [comment]
`<Image resizeMode='contain' src={require('../../assets/images/icon.png')} style={{width: 200, height: 200}} />` use `source={require('../../assets/images/icon.png')}` instead of `src={}`. The difference is that `src` expects a string URL, whereas Metro is converting `require()` to a asset ID. When you use `source={}` the React Native Web image component knows to lookup the ID for the hosted image URL.
