### ISSUE TITLE
iOS: access gallery through DocumentPicker

### ISSUE THREAD

**Issue by clems36** [expo/expo#2704]
Target: standalone

### Steps to Reproduce

Call DocumentPicker.getDocumentAsync on iOS standalone app.

``` javascript
const response: IDocumentPickerResponse = await DocumentPicker.getDocumentAsync({
    copyToCacheDirectory: false,
    type: '*/*',
});
```

### Expected Behavior

I would expect it to behave the same way as Android and allow me to pick any kind of file at once.

### Actual Behavior

I can only search through files that are saved in clouds (iCloud, Dropbox,...). Say I want to add a video from the gallery, I can't.

![img_0438](https://user-images.githubusercontent.com/6041593/48431697-9791c180-e772-11e8-8df7-512d787f45b9.PNG)

I don't know if this is just how things work with iOS (in which case there's nothing we can do about it) or if there's a way to group all the different formats as `DocumentPicker` does with Android.

Thanks in advance and sorry if this is the wanted behavior.

**Comment by EvanBacon** [comment]
On iOS this method binds a string `type` to the `allowedUTIs` value of method:
```objc
- (instancetype)initWithDocumentTypes:(NSArray <NSString *> *)allowedUTIs inMode:(UIDocumentPickerMode)mode NS_DESIGNATED_INITIALIZER;
```
So if it is possible in the OS than nothing in the module is holding you back. But I don't think this is possible. Please see `ImagePicker` API for accessing the gallery

**Comment by clems36** [comment]
So I went through a few apps and it just seems like iOS always offers the possibility to choose the adequate app according to which type of file you want to pick. There is natively no centralized place as there is on Android. My solution will be to prompt the user for which type of file they want to pick and use `DocumentPicker` or `ImagePicker` accordingly. 
Thanks!
