### ISSUE TITLE
In expo-app package is working on web until expo@49 but showing resolver error for Worker when expo is upgraded to 50

### ISSUE THREAD

**Issue by amars29** [expo/expo#27051]
### Minimal reproducible example

Create a new expo app with Navigation (typescript) and add expo-camera package and render it in them App,

### Summary

The error is below

```
Metro error: Worker is not defined

  44 |     }
  45 |     const blob = new Blob(stringifiedFn, { type: 'text/javascript' });
> 46 |     const worker = new Worker(URL.createObjectURL(blob));
     |                    ^
  47 |     // First-In First-Out queue of promises
  48 |     const promises = [];
  49 |     worker.onmessage = (e) => promises.shift()?.resolve(e.data);

Call Stack
  createWorkerAsyncFunction (node_modules/expo-camera/build/useWebQRScanner.js:46:20)
  factory (node_modules/expo-camera/build/useWebQRScanner.js:57:16)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:342:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:240:12)
  _$$_REQUIRE (node_modules/metro-runtime/src/polyfills/require.js:127:7)
  factory (node_modules/expo-camera/build/ExpoCamera.web.js:10)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:342:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:240:12)
  _$$_REQUIRE (node_modules/metro-runtime/src/polyfills/require.js:127:7)
  <unknown> (node_modules/expo-camera/build/Camera.js:4)
Web Bundled 1527ms (node_modules/expo-router/_error.js)
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
      Yarn: 1.22.10 - ~/node_modules/.bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
      Watchman: 2023.07.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by mptorz** [comment]
@amars29 did you solve this? I have the same problem
