### ISSUE TITLE
SDK 30 contains TextInput bug where `value` prop is ignored

### ISSUE THREAD

**Issue by blakek** [expo/expo#2705]
There are several issues on React Native where trying to use TextInput as a controlled component fails from (as far as I can tell) versions `0.54.0` to `0.56.x` (it's fixed in `0.57.0`).  From quick searching, it seems to be resolved by facebook/react-native#18278.

This is fixed in SDK 31 (which uses the later version of React Native).  However, SDK 31 removes Android 4.4 and iOS 9 support, so it'd be nice to have this for SDK 30.  This is likely also happening on other SDK versions.

Also, I'm assuming this should be for [expo/react-native](https://github.com/expo/react-native), but that repo doesn't have issues enabled.  If there's a different place more appropriate for this, please let me know. Thanks!

### Environment

```
  Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14
      Shell: 4.4.18 - /usr/local/bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/gsandf-1f360a82-16ad-4413-9357-77f886caf9a6.tar.gz
```

### Steps to Reproduce

Use latest current SDK 30.

Add a controlled TextInput to a project:

```javascript
<TextInput value="This text should not be changed by typing." />
```

Type in the input.

### Expected Behavior

The native component's value should match the `value` prop. A flash of the props not matching is expected.

### Actual Behavior

TextInput acts as if `value` is `defaultValue`.  `value` seems to be (mostly) ignored after typing.

### Reproducible Demo

https://snack.expo.io/@gsandf/textinput-value-bug-for-sdk-30

**Comment by blakek** [comment]
Just a gentle bump.  I know you guys just released v32. Is there a chance this bug fix will be backported to v30?

If there's anything I can do to help get this in the last version to support older iOS/Android versions, I'd be very interested in helping any way I can.

Thanks!

**Comment by esamelson** [comment]
Hi @blakek - thanks for the report. Unfortunately we simply don't have the bandwidth to deal with this right now -- it's much less trivial for us to backport fixes to RN than fixes to our own module code. Sorry about that 😞 However, since it looks like the fix is iOS only, you may be able to fix this yourself pretty easily by ejecting and applying the fix manually to the affected RN files.

**Comment by FiberJW** [comment]
Hi, we’re closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks :)
