### ISSUE TITLE
[docs] update instructions from 49 to 50 to include sentry

### ISSUE THREAD

**Issue by ScopeSV** [expo/expo#27050]
### Summary

When upgrading from 49 to 50, I got a bizarre error: 
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM length]: unrecognized selector sent to instance 0x28058bd80'
```
and
```
Argument 0 ((
    123,
    34,
    114,
    101,
    97,
   <…>
))
```
It was not possible to debug via macOS console, or sentry. The application would crash on upstart.
After debugging and removing code, I found Sentry to be the culprit. 
Digging through the documentation, I found a new page for sentry with expo regarding v50. 

This should probably go into the blog post as well.

### Link to the related docs page

https://expo.dev/changelog/2024/01-18-sdk-50

**Comment by kmalyshev** [comment]
I had the same issue with sentry-expo, went through the same process of decompiling, debugging and removing pieces of code.
The problem went away after switching to @sentry/react-native

**Comment by hanford** [comment]
I also ran into this, calling this out in the docs would have saved me some time and stress!

**Comment by gerryfletch** [comment]
Despite using Sentry, I didn't notice these crashes 🤦🏼 670 crashes for 200 users later I came across this GitHub issue, thank you for flagging it!
