### ISSUE TITLE
ScreenOrientation.addOrientationChangeListener Does not work for iOS devices

### ISSUE THREAD

**Issue by CAglarBilkent** [expo/expo#27064]
### Minimal reproducible example

https://github.com/CAglarBilkent/orientationtest

### Summary

I have been working on an application and I have the logic below:

 const [orientation, setOrientation] = useState(1);

  useEffect(() => {
    ScreenOrientation.unlockAsync();
    ScreenOrientation.addOrientationChangeListener(({ orientationInfo }) => {
      console.log('orientationInfo.orientation', orientationInfo.orientation);
      setOrientation(orientationInfo.orientation);
    });

    return () => {
      ScreenOrientation.removeOrientationChangeListeners();
      ScreenOrientation.lockAsync(
        ScreenOrientation.OrientationLock.PORTRAIT_UP
      );
    };
  }, []);
  
  Based on the orientation change, I perform certain things. Mostly layout changes. It was working well until last Friday. After the Expo Go update on iOS, this feature stopped working. I have been trying to make it work but I am not able to. I have created a new app from scratch but it also does not work. Not only that but when I try to test the boilerplate app, some of the iOS devices crash without an error. I don't know how to solve this issue and I am trying to finalize a project. 
  In the code above, line "console.log('orientationInfo.orientation', orientationInfo.orientation);" is not executed at all. So it seems like addOrientationChangeListener is not doing anything. It works well on android devices. It is just the iOS devices. I am not sure if it is the Expo Go iOS app or the SDK issue.
  
  
  
  

### Environment

I tried both on Windows and Mac

expo-env-info 1.2.0 environment info:
System:
OS: Windows 11 10.0.22621
Binaries:
Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: AI-231.9392.1.2311.11255304
npmPackages:
expo: ~50.0.4 => 50.0.6
react: 18.2.0 => 18.2.0
react-native: 0.73.4 => 0.73.4
Expo Workflow: managed

Mac:
expo-env-info 1.2.0 environment info:
System:
  OS: macOS 14.3
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.3.1 - /usr/local/bin/node
  Yarn: 1.22.21 - /usr/local/bin/yarn
  npm: 9.7.2 - /usr/local/bin/npm
Managers:
  CocoaPods: 1.14.2 - /Users/kenanacer/.rvm/rubies/ruby-2.7.4/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
  expo: ~50.0.4 => 50.0.6 
  react: 18.2.0 => 18.2.0 
  react-native: 0.73.4 => 0.73.4 
npmGlobalPackages:
  expo-cli: 6.3.10
Expo Workflow: managed

**Comment by CAglarBilkent** [comment]
By the way since Last friday, when I create a new project running "npx create-expo-app my-app", the project comes with issues:
![Screenshot 2024-02-12 212823](https://github.com/expo/expo/assets/69230821/d70e7e62-a36e-4f36-b5d7-4ec09e26c9d7)

**Comment by behenate** [comment]
@CAglarBilkent Hi, I've tried your code in Expo Go on iOS 16 and 17 devices and simulators and couldn't reproduce the issue (I'm getting the correct orientation logs).I'd suggest making sure that your `expo` and `expo-screen-orientation` packages are up to date, but the ones in `package.json` of your test project are fine, you can remove node_modules and run `yarn install` just to be sure.

If you keep having issues you can try creating a [development-build](https://docs.expo.dev/develop/development-builds/create-a-build/).

**Comment by CAglarBilkent** [comment]
@behenate ,
Thanks for the help but I am still facing the same issue. I have exactly the same code in 2 different projects, and one of them is working while the other one is not working. I have been trying to isolate the issue and I went back to this example again. I tried your suggestions as well. However, for some reason, this time, it is working well on both android and iOS simulators/emulators. However, on physical iPhone, it does not work. I am so confused about it.

**Comment by vuksharu93** [comment]
+1

**Comment by vuksharu93** [comment]
@CAglarBilkent 
Hi, I'm also facing the same issue on my expo app ("expo": "^50.0.14", "expo-screen-orientation": "~6.4.1")
I have tried your code on a physical device (iPhone SE / 17 version), but it's not working either

I hope we'll find a solution

**Comment by behenate** [comment]
@CAglarBilkent @vuksharu93 I will try a few more times to reproduce it on a physical device. If you have any details that could make it easier to reproduce please let me know :)

**Comment by vuksharu93** [comment]
@CAglarBilkent @behenate 
I had success with only using Dimensions.
It's not a perfect solution, but it works just fine

![image](https://github.com/expo/expo/assets/135835333/d6509e10-64cf-4c0f-97cb-cedfd7d2574e)

**Comment by hrdyjan1** [comment]
Hey there!
I see you're having trouble with screen orientation in your React Native app. It's a common issue, but fortunately, there are several ways to tackle it. Let's break down your options:

### 1. `addOrientationChangeListener` from `expo-screen-orientation`:

Using this method from `expo-screen-orientation` is a reliable way to manage screen orientation, especially if you're already using Expo in your project. Here's how you can implement it:

```javascript
import { ScreenOrientation } from 'expo';

ScreenOrientation.addOrientationChangeListener((event) => {
  // Handle orientation change here
});
```

### 2. `Dimensions.addEventListener` hacky solution:

While this solution might feel a bit hacky, it can work in a pinch. You can listen for changes in dimensions and infer orientation based on width and height:

```javascript
import { Dimensions } from 'react-native';

Dimensions.addEventListener('change', ({ window: { width, height } }) => {
  const isLandscape = width > height;
  // Handle orientation change here
});
```

### 3. `useDeviceOrientation` from `@react-native-community/hooks`:

This hook provides a convenient way to access the device's orientation. It abstracts away the complexity and provides a clean interface:

```javascript
import { useDeviceOrientation } from '@react-native-community/hooks';

const { landscape } = useDeviceOrientation();
// Use landscape to determine orientation
```

### 4. Turn off device lock in iOS settings:

Sometimes, the issue might not be with your code but with the device settings. Make sure the device lock is turned off in iOS settings to allow the app to control the orientation freely.

---

**Comment by kot331107** [comment]
same issue here.

**Comment by kot331107** [comment]
Upd: I reiterated an attempt to integrate `expo-screen-orientation` and now it works partially on iOS("expo": "52.0.27",  "expo-screen-orientation": "8.0.4"). Now It fires the orientation change event but only until I lock the orientation with `ScreenOrientation.lockAsync`. Which prob makes sense. 
Prob I should use the [DeviceMotion](https://docs.expo.dev/versions/latest/sdk/devicemotion/) to get the physical orientation and unlock the screen orientation back.
