### ISSUE TITLE
Android will reload everytime is sendt to background and opened from icon click again.

### ISSUE THREAD

**Issue by MrCox007** [expo/expo#27073]
### Summary

When creating a new application and adding package expo-dev-client the app will reload everytime the app has been in background and opened from icon on android. 
The last version which this doesn't happen is expo-dev-client@3.2.0.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@types/react": "~18.2.45",
    "expo": "~50.0.6",
    "expo-dev-client": "^3.3.8",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "typescript": "^5.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ~50.0.6 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: bare

### Reproducible demo

https://github.com/MrCox007/expo.git

**Comment by Adam-Schlichtmann** [comment]
@lukmccall Is there any progress on this?

**Comment by nop33** [comment]
I experience the same issue

**Comment by krystianhub** [comment]
Please check my comment: https://github.com/expo/expo/issues/28685#issuecomment-2102589889
