### ISSUE TITLE
[expo-camera/next]: Camera does not correctly unmount on Android

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/expo#27074]
### Minimal reproducible example

https://github.com/stefan-schweiger/expo-camera-next-bug

### Summary

When you remove the `CameraView` component the camera does not get unmounted correctly on Android. On iOS the green indicator light disappears on Android the camera icon in the status bar does not go away (and phone keeps getting warmer because camera is still running in the background).

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: managed
```

**Comment by alanjhughes** [comment]
Thanks for reporting @stefan-schweiger I will get this fixed

**Comment by seanquinn** [comment]
Still experiencing this in Expo 51 on RN 0.74.6. Any ideas @alanjhughes?
