### ISSUE TITLE
PRODUCT_BUNDLE_IDENTIFIER keeps adding line to Info.plist

### ISSUE THREAD

**Issue by MariuzM** [expo/expo#27091]
### Minimal reproducible example

https://github.com/MariuzM/expo-starter

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Not sure how but i keep seeing this line being added more and more to Info.plst. This started happening with Router V3, before i was not using any router just plain navigation with expo. 

<img width="668" alt="image" src="https://github.com/expo/expo/assets/36937039/570214d1-1fb8-4f14-b326-ac422b2b735a">

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/dev/node-v20.11.0/bin/node
      npm: 10.2.4 - ~/dev/node-v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 7.2.0

**Comment by brentvatne** [comment]
to clarify, you see this when you run `npx expo prebuild`, right? you should run `npx expo prebuild --clean` unless you have a particular reason for not doing so
