### ISSUE TITLE
Permissions.askAsync(Permissions.CAMERA) returns rejected

### ISSUE THREAD

**Issue by kristoferlund** [expo/expo#2709]
### Environment

```
  Expo CLI 2.3.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.5 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.2
    npmGlobalPackages:      expo-cli: 2.3.8
```
Diagnostics report:    
https://exp-xde-diagnostics.s3.amazonaws.com/fmckl-bf59ce5e-6a3c-4cee-854c-d673fb0d0d94.tar.gz

### Steps to Reproduce

1. This concerns an ejected project running on Android, code works fine on iOS
2. First time `Permissions.askAsync` is called, user is asked to grant camera permissions
3. Press OK
4. Promise returns `User rejected permissions`

Following runs: no dialog, rejected Promise.

```
  snapPhoto = async () => {
    await Permissions.askAsync(Permissions.CAMERA, Permissions.CAMERA_ROLL);
    const result = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [4, 3]
    });
    if (!result.cancelled && result.type === 'image') {
      this.props.dispatch(
        ...
      );
    }
  };
```

```
[10:19:13] [Unhandled promise rejection: Error: User rejected permissions]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:146:31 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:30 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:397:12 in MessageQueue.__invokeCallback
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:11 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:8 in MessageQueue.__guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:9 in MessageQueue.invokeCallbackAndReturnFlushedQueue
* null:null in t
```

App info shows permission has been granted: 

![skarmavbild 2018-11-14 kl 10 32 47](https://user-images.githubusercontent.com/9698363/48473418-b5096e80-e7f8-11e8-9922-b265d669b446.png)

**Comment by kristoferlund** [comment]
Seems I found a way to fix it, manually editing `AndroidManifest.xml`.

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove"/>
```

to: 

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by kristoferlund** [comment]
Isn’t this edit supposed to happen automatically when ejecting or when doing `expo publish` based on the permissions settings in app.json? In any case, editing manually worked fine in this instance, took me ages though to realise to try this seemingly simple fix. If the intention is to edit the manifest manually, possibly a clarification in the docs would be helpful?

**Comment by alexpopa-work** [comment]
I have the same problem with an expo app on android. I get the prompt, the user accepts the camera permission, but it resolves to 'denied' every time...
Works fine when tested within the expo app, doesn't work with the generated apk.
In the settings -> Apps -> MyApp -> Permissions there's the camera permission and is active, like in @kristoferlund's first post.

**Comment by kristoferlund** [comment]
@alexpopa-work is you app ejected? In that case try manually editing `AndroidManifest.xml` as mentioned above. 

If not, make sure you ask for both `CAMERA` and `CAMERA_ROLL` permissions:

```
await Permissions.askAsync(Permissions.CAMERA, Permissions.CAMERA_ROLL);
```

**Comment by Szymon20000** [comment]
Probably before ejecting you need to specify permissions for Android in app.json.
[link](https://docs.expo.io/versions/v31.0.0/workflow/configuration.html#android).

**Comment by alexpopa-work** [comment]
Thanks @kristoferlund, seems that you need to add WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE also to make it work (probably the camera needs to store the photos somewhere). Adding them to app.json seem to have solved the problem.
Thanks for the issue description and solution, your manifest pushed me in the right direction, even if my app isn't detached.

**Comment by kristoferlund** [comment]
@Szymon20000 yes, I believe that's it. The process of changing permissions of an ejected app - after ejecting - probably needs clarificaton in the docs somewhere.

To tie things together, is manually editing AndroidManifest.xml the intended/correct way to change permissions for an ejected app?

**Comment by kristoferlund** [comment]
@Szymon20000 https://github.com/expo/expo-docs/pull/415

**Comment by sjchmiela** [comment]
The docs PR has been merged, we hope it will let others not bump into this issue again. I'll let myself close this issue, feel free to reopen it if the issue persists. 🙂
