### ISSUE TITLE
Modal screen white flash on Android with Expo Router 3

### ISSUE THREAD

**Issue by SKempin** [expo/expo#27099]
### Minimal reproducible example

https://github.com/SKempin/expo50-modal-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Expo router 3 appears to have introduced a render issue when opening a modal on Android. When opening a modal on Android (both on simulator and a real device) there is a white flash before the modal screen is rendered.

 Tested this with Expo 49 and expo router 2 and this issue is not present there. See the videos below. \

expo router 3:

https://github.com/expo/expo/assets/10877466/405037f4-50a8-44f3-a315-7c2d47aa547c

expo router 2:

https://github.com/expo/expo/assets/10877466/5b56ae88-cf26-4fdb-b752-ac44df5b06b2

This is reproducible using the quick start command as per https://docs.expo.dev/router/installation/#quick-start.

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

```

**Comment by hamzalakrati** [comment]
I am experiencing the same issue:

```
"expo": "^50.0.7",
"expo-router": "~3.4.7",
```

**Comment by hichemfantar** [comment]
This is a known issue even with regular react-naigation
https://github.com/react-navigation/react-navigation/issues/10951

**Comment by nabilfreeman** [comment]
If I understand correctly, this modal animation is the default one that Expo Router / React Navigation uses on Android.

This solution won't work if you *actually* want this animation, but:

Adding `{ animation: "ios" }` to the `screenOptions` object removed this white flash for us and resulted in a much closer experience to the iOS app with a nice fast slide and navbar transition.

**Comment by KorigamiK** [comment]
Issue is still relevant, but the ios animation workaround works

**Comment by Code-Victor** [comment]
I had the same issue, but after examining the React-conf app, I was able to identify the problem. You need to adjust your system UI background color to avoid the white flash that occurs due to the background color being white. I created a custom hook to address this in my case. The hook also manages the status bar and handles specific routes with different colors.

```tsx
import { color } from "@/constant/tokens";
import {
  useNavigationContainerRef,
  useSegments,
  usePathname,
} from "expo-router";
import { setBackgroundColorAsync } from "expo-system-ui";
import React, { useEffect, useState } from "react";
import { setStatusBarStyle } from "expo-status-bar";

export const useRootBackgroundColor = () => {
  const pathname = usePathname();
  const segments = useSegments();

  // checking that navigation is all good;
  const [isNavigationReady, setNavigationReady] = useState(false);
  const rootNavigation = useNavigationContainerRef();

  useEffect(() => {
    const unsubscribe = rootNavigation?.addListener("state", (_event) => {
      setNavigationReady(true);
    });
    return function cleanup() {
      if (unsubscribe) {
        unsubscribe();
      }
    };
  }, [rootNavigation]);

  React.useEffect(() => {
    if (!isNavigationReady) {
      return;
    }
    const isRootAuth = pathname.includes("welcome");
    const inAuthGroup = segments[0] === "(auth)";
    if (isRootAuth) {
      setStatusBarStyle("light", true);
      setBackgroundColorAsync("#020008");
    } else if (!inAuthGroup) {
      setStatusBarStyle("light", true);
      setBackgroundColorAsync(color["dark.2"]);
    } else if (inAuthGroup) {
      setStatusBarStyle("dark", true);
      setBackgroundColorAsync("#f2f2f2");
    }
  }, [segments, isNavigationReady, pathname]);
};

```

**Comment by csulit** [comment]
This issue only occurs on Android; it works flawlessly on iOS.

**Comment by vlummien** [comment]
For my project (Expo 52) only this helped:
Wrapping the whole project with
`<ThemeProvider value={DarkTheme}>`

(import { DarkTheme, ThemeProvider } from '@react-navigation/native')

**Comment by pedrocarlos-ti** [comment]
Same issue here, I tried to wrap with `ThemeProvider` but didn't work.

**Comment by krsteve** [comment]
> For my project (Expo 52) only this helped: Wrapping the whole project with `<ThemeProvider value={DarkTheme}>`
> 
> (import { DarkTheme, ThemeProvider } from '@react-navigation/native')

You, sir, saved my day. Thanks!

(Yes, this worked in my Expo 52 project.)

**Comment by voigtito** [comment]
@pedrocarlos-ti try this from @vlummien example

```
<ThemeProvider value={{
      ...DarkTheme,
      colors: {
        ...DarkTheme.colors,
        background: "#1E2433",
      }
    }}>
```

change the background according to your app.

**Comment by chartliex** [comment]
> ios

thanks, this solution is good!
expo router 4.0.17 and expo 52.0.35 (react native 0.77.1)

**Comment by zaynOm** [comment]
still having the same issue

using the default expo-router starter with `expo: ~53.0.9`,  `expo-router: ~5.0.6`

I have `ThemeProvider` setup

**Comment by Ammarahmed1263** [comment]
try adding these two lines to your root file it has solved similar issue for me.

```code
import * as SystemUI from "expo-system-ui";

SystemUI.setBackgroundColorAsync("transparent");
```

**Comment by tlmader** [comment]
@vlummien and @voigtito 's approaches worked for me. Example using Tamagui:

```tsx
/* eslint-disable no-restricted-imports */
import { DarkTheme, ThemeProvider } from '@react-navigation/native';
import { useTheme } from 'tamagui';

import { useAppColorScheme } from '@app/core/theme/use-app-color-scheme';

/**
 * Solves white flash during Android navigation animations.
 *
 * @see https://github.com/react-navigation/react-navigation/issues/10719
 */
export const NavigationTheme = (props: { children: React.ReactNode }) => {
  const theme = useTheme();
  const colorScheme = useAppColorScheme();
  return (
    <ThemeProvider
      value={{
        dark: colorScheme === 'dark',
        colors: {
          primary: theme.$accent11?.val,
          background: theme.$color1?.val,
          card: theme.$color3?.val,
          text: theme.$color12?.val,
          border: theme.$color7?.val,
          notification: theme.$color11?.val,
        },
        fonts: DarkTheme.fonts,
      }}
    >
      {props.children}
    </ThemeProvider>
  );
};
```

Expo Team, please fix these table-stakes issues!

**Comment by devtm1123** [comment]
> try adding these two lines to your root file it has solved similar issue for me.
> 
> ```
> import * as SystemUI from "expo-system-ui";
> 
> SystemUI.setBackgroundColorAsync("transparent");
> ```

It solved the issue for me.

**Comment by kbrattli** [comment]
> try adding these two lines to your root file it has solved similar issue for me.
> 
> ```
> import * as SystemUI from "expo-system-ui";
> 
> SystemUI.setBackgroundColorAsync("transparent");
> ```

Just wanted to say it solved it for me too. This is the way to go to stop the flashing white in expo-router

**Comment by chimaris** [comment]
> try adding these two lines to your root file it has solved similar issue for me.

Thanks so much for this. it works for me too

**Comment by knnthdn** [comment]
> try adding these two lines to your root file it has solved similar issue for me.
> 
> ```
> import * as SystemUI from "expo-system-ui";
> 
> SystemUI.setBackgroundColorAsync("transparent");
> ```
Worked for me too. Thanks.
