### ISSUE TITLE
running create-expo-module fails at start on Ubuntu v22

### ISSUE THREAD

**Issue by nikocraft** [expo/expo#27093]
### Summary

following this tutorial https://docs.expo.dev/modules/native-module-tutorial/
I'm expected to run this command "npx create-expo-module", once I do I get 

**Error: Invalid URL.**  and can't proceed to learn how to create native module, since create-expo-module is failing to work in Ubuntu environment.

_(I have no issues running the same command on Win 11 Pro, there is no "Error: Invalid URL" with same input values, but there another issue comes at the very end of seting up the module. )_

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash

### Minimal reproducible example

Just run npx create-expo-module 
 
 What is the name of the npm package? … expo-settings
✔ What is the native module name? … ExpoSettings
✔ How would you describe the module? … My new module
✔ What is the Android package name? … expo.modules.settings
✔ What is the name of the package author? … nikocraft
✔ What is the email address of the author? … whatever@gmail.com
✔ What is the URL to the author's GitHub profile? … https://github.com/nikocraft
✔ What is the URL for the repository? … https://github.com/nikocraft/expo-settings

✖ Downloading module template from npm
Error: Invalid URL
    at module.exports (/home/nikostar/.npm/_npx/df6d79204f77d516/node_modules/normalize-url/index.js:60:9)
    at /home/nikostar/.npm/_npx/df6d79204f77d516/node_modules/cacheable-request/src/index.js:43:16
    at get (/home/nikostar/.npm/_npx/df6d79204f77d516/node_modules/got/index.js:98:20)
    at /home/nikostar/.npm/_npx/df6d79204f77d516/node_modules/got/index.js:266:5

**Comment by nikocraft** [comment]
Solved...

**Comment by pixelknitter** [comment]
> Solved...

how did you solve it?

**Comment by frankfuu** [comment]
Would also like to know how you solved it. Getting the same error.

**Comment by nikocraft** [comment]
Guys I'm sorry I'm stupid I forgot, I should have posted my solution here when I solved it. I'll try to remember and also look in my terminal history. If I find it I'll post it here for you. If you figure it out, post it here for future visitors.
