### ISSUE TITLE
expo-camera/next BarCodeType ts type is wrong

### ISSUE THREAD

**Issue by janwittkamp** [expo/expo#27103]
### Minimal reproducible example

https://github.com/janwittkamp/expo-barcode-test

### Summary

The docs suggest using [BarcodeType](https://docs.expo.dev/versions/latest/sdk/camera-next/#barcodetype) but the suggested type doesn't work, this also effected the ts type BarCodeType.

`  barcodeScannerSettings={{ barCodeTypes: ["qr"] }}`

This work
`  barcodeScannerSettings={{ barCodeTypes: ["org.iso.QRCode"] }}`

This issue can be reproduced in the attached repository.

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
Hi @janwittkamp - this has already been fixed in #26704 and the type casing errors were fixed in #26888, this has not been published yet though. You need to use `barcodeTypes` in the camera settings and not `barCodeTypes`.
