### ISSUE TITLE
Failed to upload the project tarball to EAS Build  Reason: EPERM: operation not permitted, rmdir

### ISSUE THREAD

**Issue by JoezerSmaniotto** [expo/expo#27113]
### Summary

When running the command `npx eas-cli build --auto-submit --clear-cache` to generate the build, I was surprised by a test error
![Design sem nome (3)](https://github.com/expo/expo/assets/42808798/c7737303-d89e-4e6a-adf6-d950b6b7ea9b)

what I already found on the internet, I already tried to do but without success, such as checking if git was started in the repository, checking permissions, disabling antivirus....
NOTE: Everything with permission, for the system and for my user, in addition I ran VsCode as administered.

### SDK Version

48

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ~48.0.18 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
    Expo Workflow: managed

### Minimal reproducible example

When running the command `npx eas-cli build --auto-submit --clear-cache` to generate the build, I was surprised by a test error
![Design sem nome (3)](https://github.com/expo/expo/assets/42808798/cd578431-5ee6-4def-862f-cdac07026fef)

**Comment by brentvatne** [comment]
hi there! it looks like there may be something wrong with the user permissions on your windows machine. when you trigger a build with eas cli, [we do a shallow clone of the repo into your system temp directory and compress it into a tarball](https://expo.fyi/eas-build-archive) then upload that tarball. it seems that you do not have access to your own temp directory?

i'm not super familiar with windows so you may know better than i do what could cause that, but i googled the error and found this: https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows

let me know if this resolves your issue and if so we can try to handle this error and provide guidance

**Comment by JoezerSmaniotto** [comment]
solved like this: adding "requireCommit": true in the eas.json file
![Captura de tela 2024-02-16 152451](https://github.com/expo/expo/assets/42808798/20b0751b-c981-4ad6-b289-2eb3a78c66c1)

**Comment by JoezerSmaniotto** [comment]
solved like this: adding "requireCommit": true in the eas.json file
![Captura de tela 2024-02-16 152451](https://github.com/expo/expo/assets/42808798/20b0751b-c981-4ad6-b289-2eb3a78c66c1)

**Comment by UdumiziSolomon** [comment]
`Creating a new git instance for the project should fix the problem too.`

**Comment by mahevstark** [comment]
> solved like this: adding "requireCommit": true in the eas.json file ![Captura de tela 2024-02-16 152451](https://private-user-images.githubusercontent.com/42808798/305523684-20b0751b-c981-4ad6-b289-2eb3a78c66c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTk0MzcsIm5iZiI6MTcyMDUxOTEzNywicGF0aCI6Ii80MjgwODc5OC8zMDU1MjM2ODQtMjBiMDc1MWItYzk4MS00YWQ2LWIyODktMmViM2E3OGM2NmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA5NTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMmI2MTlkNjM0YjE3ZDhmOGU2ZGJiODA1MzQyMTM5ZDAwMWU1ZmMwMzVmMDVhMGE0ZTQ4NmRiNWE4MWQ4Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xw0OXM5R_kMC1qToVMbNIC0s-v7HG1zH4fvFEa2r4cs)

How did you even know?

**Comment by louamlemjid** [comment]
what solved it for me was : running the cmd as administrator

**Comment by adekingsley** [comment]
> Creating a new git instance for the project should fix the problem too.
> 
> `git init` `git add .` `git commit -m "first commit"`
> 
> Run the build command again

thanks this worked well for me

**Comment by NitayMG** [comment]
Worked for me to change the eas.json from this:
"cli": {
    "version": ">= 12.5.1",
    "appVersionSource": "remote"
 }


to this:
"cli": {
    "version": ">= 12.5.1",
    "appVersionSource": "remote",
    "requireCommit": true
 }

**Comment by Pratik-mali** [comment]
"cli": {
"version": ">= 12.5.1",
"appVersionSource": "remote",
"requireCommit": true
}

 _**and run terminal as administrator.**_

**Comment by sapphire-haeward** [comment]
Thanks!! It worked for me :) <3

**Comment by szheleshchenko** [comment]
I tried all of the above advice, but only updating the Node version helped. I upgraded from 20 to 22.

**Comment by aldensully** [comment]
this can also happen if you are out of disk space on your machine

**Comment by Pratik-mali** [comment]
> @Pratik-mali
>  Hi , I wanna build my react native project with expo but I get this error :
> 
> 
> 
> Failed to upload metadata to EAS Build
> 
> Reason: Request failed: 403 (Forbidden)
> ✖ Uploading to EAS Build (32.5 MB / 32.5 MB)
> Failed to upload the project tarball to EAS Build
> 
> Reason: Request failed: 403 (Forbidden)
>     Error: build command failed.
> 
> 
> 
> and I set this :
> 
>  "cli": {
>     "version": "16.2.1",
>     "appVersionSource": "remote",
>     "requireCommit": true
>   },
> 
> 
> I sure that I login in my account, I guess this is related to our region , How can I resolve this problem ?
> 
> thank you
> 

Run terminal as a Administrator

**Comment by hagesake** [comment]
Hello there! I'm having the same issue here, getting the 403 Forbidden error message. I have tried to include the requireCommit property in the eas.json as an alternative seen here but does not work for me. I'm working on a Linux machine. Could the issue be related to file permissions or something like that?

**Comment by ArsaCore** [comment]
> [@Pratik-mali](https://github.com/Pratik-mali) Hi , I wanna build my react native project with expo but I get this error :
> 
> Failed to upload metadata to EAS Build
> 
> Reason: Request failed: 403 (Forbidden) ✖ Uploading to EAS Build (32.5 MB / 32.5 MB) Failed to upload the project tarball to EAS Build
> 
> Reason: Request failed: 403 (Forbidden) Error: build command failed.
> 
> and I set this :
> 
> "cli": { "version": "16.2.1", "appVersionSource": "remote", "requireCommit": true },
> 
> I sure that I login in my account, I guess this is related to our region , How can I resolve this problem ?
> 
> thank you

Using a DNS will solve your problem, without having to set requireCommit to true.

**Comment by uncle-ov** [comment]
Run the following commands:
* `git config core.ignorecase false`
* `git add -A`
* `git commit -m "...untracked files..."`
* `git push`
* `npx eas build`

Source -> https://github.com/expo/fyi/blob/main/macos-ignorecase.md

**Comment by Axolem** [comment]
`git config --global --add safe.directory C:/apps/notmine/dot-env-talent/.git`

solved it for me, `C:/apps/notmine/dot-env-talent/.git` being the path of my git repo

**Comment by enmfarooq85** [comment]
1) Creating a new git instance for the project should fix the problem too.

```
git init 
git add .
git commit -m "first commit"
```

2) Run the build command again
3) **thanks this worked well for me**
