### ISSUE TITLE
The migration to `CameraView` doesnt work in my code.

### ISSUE THREAD

**Issue by ARIARCHI-MZ** [expo/expo#27130]
The migration to `CameraView` doesnt work in my code. 
i don't get any error. it seems the functionality of scanner doesnt work, the camera opens but it doesnt scan Qrcode from image. I followed the instruction and change the code from 
**<BarCodeScanner onBarCodeScanned={scanned ? undefined : handleBarCodeScanned} />**
to
**<CameraView
            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
           barCodeScannerSettings={{
            barCodeTypes: ["qr", 'aztec','ean13','ean8','qr','pdf417','upc_e','datamatrix','code39','code93','itf14','codabar','code128','upc_a' ],
          }}
          />**
I have to mention that scanner works well with **BarCodeScanner**. all permission is granted. nothing scanned but camera opens. 
**_Expo is updated to version 50
"expo-barcode-scanner": "~12.9.2",
        "expo-camera": "~14.0.4",_**
Expo-camera is updated to the latest version
is there any solution?

_Originally posted by @ARIARCHI-MZ in https://github.com/expo/expo/issues/27015#issuecomment-1948629490_

**Comment by alanjhughes** [comment]
Hi - The latest version is 14.0.5 and fixes the prop casing errors here.

**Comment by ARIARCHI-MZ** [comment]
Thank you for explaining. yes I am using Expo go with SDK 50
It is written that in the next version of expo, it is not possible the BarCodeScanner.
May I ask in further development of expo go with version 51, do you want to ignore the functionality of scanner or Expo go will update with dev client in SDK 51?

> Hi - The latest version is 14.0.5 and fixes the prop casing errors here. I will reopen if this is a still a problem. Also note, you will need a dev client to use the latest changes, not expo go

**Comment by eugenegalaxy** [comment]
expo-camera version 15.0.9

I did migration from expo-barcode-scanner to expo-camera and could not scan a single QR-code.

FOUND A FIX:

Have to add 'barcodeScannerEnabled' prop to that was not mentioned in the official guide, but can be seen as a prop here: https://github.com/expo/expo/blob/9a304666693684fa5429b1b11773b0e07bdea3ce/packages/expo-camera/src/next/Camera.types.ts#L392

My component:

<CameraView
barcodeScannerEnabled
onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
/>

**Comment by mlanzamolina** [comment]
@eugenegalaxy solution worked. This should be placed in the [Expo Camera documentation](https://docs.expo.dev/versions/latest/sdk/camera/).

**Comment by alanjhughes** [comment]
`barcodeScannerEnabled` is not in the public api because it is set based on the presence of `onBarcodeScanned` https://github.com/expo/expo/blob/4541793ff822d29186b6910adaaa511908c2a2ea/packages/expo-camera/src/utils/props.ts#L36

**Comment by eugenegalaxy** [comment]
> `barcodeScannerEnabled` is not in the public api because it is set based on the presence of `onBarcodeScanned`
> 
> https://github.com/expo/expo/blob/4541793ff822d29186b6910adaaa511908c2a2ea/packages/expo-camera/src/utils/props.ts#L36

Makes full sense to me in the context of users using expo-camera as a regular camera.

However, the tutorial for the migration from 'expo-barcode-scanner' is still misleading. :)

**Comment by ioness** [comment]
> expo-camera version 15.0.9
> 
> I did migration from expo-barcode-scanner to expo-camera and could not scan a single QR-code.
> 
> **FOUND A FIX**
> 
> Have to add 'barcodeScannerEnabled' prop to that was not mentioned in the official guide, but can be seen as a prop here:
> 
> https://github.com/expo/expo/blob/9a304666693684fa5429b1b11773b0e07bdea3ce/packages/expo-camera/src/next/Camera.types.ts#L400
> 
> My component:
> 
> <CameraView barcodeScannerEnabled onBarcodeScanned={scanned ? undefined : handleBarCodeScanned} />

Hey, 

If I am not mistaken:

expo-camera/legacy
expo-barcode-scanner

Uses "onBarCodeScanned" instead of "onBarcodeScanned",

And that would have been your initial error,

Therefor, your solution seem to have nothing to do with "barcodeScannerEnabled".

After some struggle... 

Cheers!

**Comment by eugenegalaxy** [comment]
> > expo-camera version 15.0.9
> > I did migration from expo-barcode-scanner to expo-camera and could not scan a single QR-code.
> > **FOUND A FIX**
> > Have to add 'barcodeScannerEnabled' prop to that was not mentioned in the official guide, but can be seen as a prop here:
> > https://github.com/expo/expo/blob/9a304666693684fa5429b1b11773b0e07bdea3ce/packages/expo-camera/src/next/Camera.types.ts#L400
> > 
> > My component:
> > <CameraView barcodeScannerEnabled onBarcodeScanned={scanned ? undefined : handleBarCodeScanned} />
> 
> Hey,
> 
> If I am not mistaken:
> 
> expo-camera/legacy expo-barcode-scanner
> 
> Uses "onBarCodeScanned" instead of "onBarcodeScanned",
> 
> That seems to be "ARIARCHI-MZ" error on his initial post...
> 
> Therefor, your solution may have nothing to do with "barcodeScannerEnabled".
> 
> After some struggle, the code works for me without "barcodeScannerEnabled"...
> 
> Cheers!

Hey,

I've retested the scanner with 'barcodeScannerEnabled' **removed** and it worked.
Hence, my old answer is not correct (anymore?). However, I am not sure what has changed but I clearly remember it used to not work without that fix. Judging by affirmative responses from other developers, that was the fix in that moment.

Cheers!
