### ISSUE TITLE
Hello, I want to share the social software with expo

### ISSUE THREAD

**Issue by liuhuanhui** [expo/expo#2713]
Hello, I want to use expo to share social software, such as fb, tw, wechat, QQ, is there a ready-made plugin? There are also statistical analysis, such as umeng (umeng)

**Comment by EvanBacon** [comment]
Take a look at the docs https://docs.expo.io/versions/v31.0.0/react-native/share

**Comment by liuhuanhui** [comment]
This sharing seems to be different from what I want. Do not configure the shared media appid, appkey?
