### ISSUE TITLE
Expo fails to correctly bundle project w/ agora lib

### ISSUE THREAD

**Issue by davisuga** [expo/expo#27131]
### Minimal reproducible example

https://github.com/davisuga/expo-agora-bug-repro

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Upgrading to Expo 50 causes the bundler to not properly load the Agora library.
```
iOS Bundling failed 4213ms (index.js)
error: node_modules/react-native-agora/src/specs/AgoraRtcSurfaceViewNativeComponent.tsx: /Users/davi/gits/eknme/node_modules/react-native-agora/src/specs/AgoraRtcSurfaceViewNativeComponent.tsx: Unable to parse file '/Users/davi/gits/eknme/node_modules/react-native-agora/src/specs/AgoraRtcSurfaceViewNativeComponent.tsx'. Unsupported filename extension.
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 6.0.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by brentvatne** [comment]
i would suggest creating this issue on the agora repository. if you find that the problem is somehow caused by expo tooling in a way that you would consider to be a bug, come back here and let us know exactly what that is :)

**Comment by brentvatne** [comment]
it looks like this is the related issue on that repo: https://github.com/AgoraIO-Extensions/react-native-agora/issues/763

**Comment by andriy-baranskyy** [comment]
If you are still hitting the issue: it looks like Expo 50 changed how Metro bundler handles TypeScript files in node_modules. The Agora SDK has `.tsx` files in `/src/specs/` that Metro can't parse without explicit configuration.

**Potential Workaround (metro.config.js):**
```javascript
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

config.resolver.sourceExts.push('tsx');
config.resolver.assetExts = config.resolver.assetExts.filter(ext => ext !== 'tsx');

module.exports = config;
```

**If that doesn't work:**

Add to `metro.config.js`:
```javascript
config.resolver.resolverMainFields = ['react-native', 'browser', 'main'];
```

**Alternative Approaches:**

If you're evaluating alternatives and don't strictly need Expo's managed workflow, LiveSwitch works well (TypeScript support, no Expo-specific issues). You lose some Expo conveniences but gain more control over native modules.

Other options:
- Daily.co - Web-first (minimal native dependencies)
- 100ms - Actively maintained for Expo

**Full disclosure:** I work for LiveSwitch. We don't have official Expo support, but our TypeScript SDK works. The Metro workaround above should fix your Agora issue though.
