### ISSUE TITLE
Issue with okhttp3 on Android

### ISSUE THREAD

**Issue by EgidioCaprino** [expo/expo#2714]
Hi all,

We upgraded our Expo-ejected app to ExpoKit 31 and the upgrade guides says to add

```
implementation('host.exp.exponent:expoview:31.0.0@aar') {
  transitive = true
  exclude group: 'com.squareup.okhttp3', module: 'okhttp'
  exclude group: 'com.squareup.okhttp3', module: 'okhttp-urlconnection'
}
```

When building the app we get the following error:

```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDevMinSdkDevKernelDebug FAILED
D8: Program type already present: okhttp3.internal.ws.RealWebSocket
```

Do you know how we can fix that?

**Comment by esamelson** [comment]
Hi @EgidioCaprino - could you please post your full android/app/build.gradle? Which Expo SDK version did you upgrade from?

**Comment by esamelson** [comment]
Hi @EgidioCaprino - thanks for bringing this to our attention! It looks like we missed including some upgrade instructions. Could you try replacing these lines:
```
  implementation 'com.squareup.okhttp3:okhttp:3.4.1'
  implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
  implementation 'com.squareup.okhttp3:okhttp-ws:3.4.1'
```
in your android/app/build.gradle with:
```
  implementation 'com.squareup.okhttp3:okhttp:3.10.0'
  implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0'
```
and let us know if that fixes the problem for you?

**Comment by EgidioCaprino** [comment]
Hi @esamelson 

Thank you for your answer.

Do you we need to upgrade to `okhttp3` version `3.10`? Because we fixed by removing `implementation 'com.squareup.okhttp3:okhttp-ws:3.4.1'` dependency.

**Comment by esamelson** [comment]
Hi @EgidioCaprino - thanks for your response! You should be good to go just removing the old dependency. :+1:
