### ISSUE TITLE
Expo-router static export - web: getting initial flicker of index route on every other route on page reload

### ISSUE THREAD

**Issue by singh-jay** [expo/expo#27144]
### Minimal reproducible example

https://github.com/singh-jay/expo-universal-app

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Created a starter project using - bunx create-expo-app -e with-router-tailwind

added a new route /about 
export the web app - bunx expo export --platform web
bunx serve -s dist 

navigate to http://localhost:3000/about
you will get the initial flicker of - http://localhost:3000 index page
index.js part is also getting loaded on about page
added a video for the reference.

https://github.com/expo/expo/assets/36124459/3e9fc9e8-b7e9-4c4c-9c22-5318cb3e0a91

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /opt/homebrew/bin/node
      npm: 10.2.4 - /opt/homebrew/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.7 => 50.0.7 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.10 => 0.19.10 
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Please adjust your `app.json`

```diff
    "plugins": [
      [
        "expo-router",
        {
-        "origin": "https://n",
+        "root": "src/app",
          "asyncRoutes": {
            "web": true,
            "default": "development"
          }
        }
      ]
    ],

```

**Comment by singh-jay** [comment]
> ```diff
> "root": "src/app",
> ```

Changed app.json, but still getting the same isssue.
