### ISSUE TITLE
cli: should default to TypeScript (so, JavaScript should be opt-in, not the other way around) when creating ReactNative app

### ISSUE THREAD

**Issue by knocte** [expo/expo#27145]
### Summary

Steps to reproduce:
1. npx create-expo-app StickerSmash

Current results:
It creates JavaScript app.
(If you want TypeScript you gotta add `-t expo-template-blank-typescript`)

Expected results:
It should create TypeScript app, and if you want JavaScript you should need to add a `-t` param.

In the same way that ReactNative official docs' code-snippets (e.g. https://reactnative.dev/docs/intro-react ) default to TypeScript (instead of JavaScript), Expo should also default to TS instead of JS.

### What platform(s) does this occur on?

All?

### SDK Version

Last

### Environment

All

### Minimal reproducible example

See steps to reproduce above.

**Comment by EvanBacon** [comment]
TypeScript is always enabled in Expo CLI, also TS code is transpiled from the bundle all the time. Expo CLI automatically installs the versioned typescript dependencies when you convert any file from `.js` to `.ts` or `.tsx`, and creates the `tsconfig.json` automatically without needing to restart the dev server. You can also add typescript by running `npx expo customize tsconfig.json`. 

This is more than reasonable for bootstrapping a project using the most beginner friendly template we have available. Use the `tabs` template if you want TypeScript with no option for JavaScript.
