### ISSUE TITLE
[Expo 49] Logs shown in production on Android only.

### ISSUE THREAD

**Issue by nicksosa2** [expo/expo#27151]
### Minimal reproducible example

https://github.com/nicksosa2/my-app

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### SDK Version

49

### Summary

I'm using Expo 49 and for some reason, logs and errors are still visible in production mode on Android devices/emulators, specifically those running Android API levels 26 to 30. Additionally, when I log the __DEV__ variable, it returns true, indicating the app is in development mode, despite being in production. This issue is exclusive to Android on iOS devices/emulators, everything works as expected, with no such problems.

Command: `npx expo start --no-dev --minify`

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.23 => 49.0.23 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
    Expo Workflow: bare
```

**Comment by reizhafajrian** [comment]
any update on this issue?
