### ISSUE TITLE
expo-camera/next "qualities cannot be empty" crash

### ISSUE THREAD

**Issue by strycz** [expo/expo#27165]
### Minimal reproducible example

https://github.com/strycz/camera-next-crash

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I've installed expo-camera in Expo 50 project with minimum configuration
The app crashes with following error (screenshot from Flipper Crash Reporter):
<img width="692" alt="Screenshot 2024-02-19 at 11 42 53" src="https://github.com/expo/expo/assets/6389051/b7dfeae2-0696-44db-a135-95a35dd9e986">

### Environment

System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.0/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/lib/ruby/gems/3.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.7 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by dhcmega** [comment]
Hi
Thanks, can I somehow use it on SDK50?
Meanwhile this is how I think I have solved it

`node_modules/expo-camera/src/Camera.tsx`
 adding at line 49
`else {
    recordingOptions.quality = '720p';
  }`

```
function ensureRecordingOptions(options?: CameraRecordingOptions): CameraRecordingOptions {
  let recordingOptions = options || {};

  if (!recordingOptions || typeof recordingOptions !== 'object') {
    recordingOptions = {};
  } else if (typeof recordingOptions.quality === 'string') {
    recordingOptions.quality = Camera.Constants.VideoQuality[recordingOptions.quality];
  } else {
    recordingOptions.quality = '720p';
  }

  return recordingOptions;
}
```

**Comment by justindannguyen** [comment]
I don't want to use legacy Camera hence for time being, use this canary instead `0.0.1-canary-20240228-7cee619`

**Comment by robinalexandre** [comment]
> I don't want to use legacy Camera hence for time being, use this canary version instead `0.0.1-canary-20240228-7cee619`

Even using the canary version, it's still not working for me with the exact same error ...
Any idea ?

**Comment by justindannguyen** [comment]
The issue is fixed when I use canary version because I actually can see this patch in my node_modules [27126](https://github.com/expo/expo/pull/27126).

`14.1.1` included above changes as per its `CHANGELOG.md` however I can't see the changes in `node_modules` and still see old implementation
```
val qualitySelector = QualitySelector.fromOrderedList(filteredQualities)
```
instead of 
```
val qualitySelector = QualitySelector.from(preferredQuality, fallbackStrategy)
```

**Comment by gfranko** [comment]
Just like @justindannguyen, I also don't see these changes on `14.1.2`
