### ISSUE TITLE
`expo export:embed` ignores `--reset-cache` and `--minify`

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/expo#27168]
### Summary

**NOTE:** Originally I thought the problem was the command ignoring NODE_ENV altogether. I have changed the issue description after more investigation to the current version.

When running `npx expo export:embed` twice with a different `NODE_ENV` and different `.env` files the output will still be the same. Probably because of some caching. Adding the `--reset-cache` (also `--reset-cache true`) argument does not help. If I run `npx expo start -c` inbetween the cache gets correctly cleaned and the output picks up the new `NODE_ENV`/envvars.

In addition to this it seems like the command also ignores the `--minify` option and the code is not actually minified, but still quite readable and contains comments and new lines.

So first of all. I think if the NODE_ENV or the .env files change the cache should be invalidated no matter what. But besides that it seems like some arguments get ignored altogether.

### SDK Version

50

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.3 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.7 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/stefan-schweiger/ExpoBuildTest

1. run `NODE_ENV=test npx expo export:embed --platform=android --entry-file index.js --bundle-output ./index.android.bundle --dev false --reset-cache`
2. then envvar replacement in `index.android.bundle` file
3. run `NODE_ENV=production npx expo export:embed --platform=android --entry-file index.js --bundle-output ./index.android.bundle --dev false --reset-cache`
4. check `index.android.bundle` again and see that file didn't change

**Comment by stefan-schweiger** [comment]
I'm wondering if maybe the changes in this PR could be related to at least the `--minify` behavior https://github.com/expo/expo/pull/26471 @kitten @EvanBacon ?

**Comment by stefan-schweiger** [comment]
Node env is overwritten here again depending on the value of `--dev`

https://github.com/expo/expo/blob/e051b737e760fb82c692a6a75b6a33837680ba27/packages/%40expo/cli/src/export/embed/exportEmbedAsync.ts#L47C3-L47C13

**Comment by stefan-schweiger** [comment]
After more testing it seems like actually the problem for NODE_ENV is that the cache is actually not cleared between runs. The option `--reset-cache` also does not help. I have to run `npx expo start -c` inbetween then the change of `NODE_ENV` and the resultung envvars are correctly picked up. I still consider this a bug and huge PITA.

**Comment by EvanBacon** [comment]
Fixed in:
- https://github.com/expo/expo/pull/27114
