### ISSUE TITLE
Custom linking prop for NavigationContainer

### ISSUE THREAD

**Issue by youssdevx** [expo/expo#27163]
### Minimal reproducible example

https://github.com/youssdevx/expo-router-deeplink

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

## Context
I'm working with Expo SDK 50 and Expo Router version 3. 
For my marketing campaigns, I'm using a deep linking feature provided by Adjust (https://help.adjust.com/en/article/deep-links). 
The deeplinks from Adjust have the format `q***.adj.st`.

## Problem
I need to convert the Adjust deeplink before I can use it to navigate to the appropriate screen within my app. 
However, with the introduction of Expo Router, I no longer have direct access to the `linking` prop of the `NavigationContainer` and to the methods `getInitialURL` and `subscribe`.
I've tried using `Linking.useURL()`, but I can't intercept the incoming deep link before it's processed and the app navigates to the targeted screen.

## Question
How can I access the `linking` configuration to use customs `getInitialURL` and `subscribe` with Expo Router without having to patch `node_modules/expo-router/build/link/linking.js`?

<img width="1829" alt="image" src="https://github.com/expo/expo/assets/21293851/13949eaf-b3e8-457d-bda5-b49c23999979">

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 30, 31, 33, 34
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0 => 50.0.6
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: bare

**Comment by marklawlor** [comment]
Every page in Expo Router automatically configured for deep-linking, so your deep link should point directly at the target page and shouldn't need to be redirected.

If you migrating an existing app which has links that don't match your Expo Router page paths, you can use the root `_layout` file in a "middleware" pattern to perform top-level redirects.

```
// _layout.tsx
export default function () {
  const pathname = usePathname();
  
  if (<pathname-condition>) {
    return <Redirect href="/<page>" />;
  } else {
    return <Stack />
  } 
}
```

We're looking at improving redirects/rewrites in the future

If this doesn't answer your question, can you reply with more detail about you need to achieve or with a sample of your `getInitialURL` code.

**Comment by youssdevx** [comment]
Thanks for your answer @marklawlor.

I already tried to redirect using this "middleware" before opening the issue, but it was not useful.

There are several use cases for which we need to manipulate the incoming deeplink:
1. In the use case with Adjust explained in the context of the issue, I need to convert the deeplink using `AdjustSDK.convertUniversalLink` as described in the documentation and then redirect to the correct screen.
2. Check whether the path can be accessed by a user. For example, if a non-premium user wants to access a certain screen, it must be possible to redirect him to another screen.
3. Give the deeplink to another SDK for a particular use...

We need access to the `getInitialURL` and `subscribe` methods to perform custom actions. The fact that this is no longer possible with Expo router is a problem.

Thanks for your help.

**Comment by marklawlor** [comment]
1. That should be possible via the `middleware`
2. I would not perform this logic during `getInitialUrl`. I would add it to the `_layout` of the protected routes, this way your routes are always protected, not just during deep linking scenarios and/or your not rewriting auth logic just for deeplinking
3. The deeplink url/pathname/parameters are available via the Expo Router hooks. If you need to setup a SDK context provider, that these are all available in the `_layout` files.

I get the feeling your not going to find those answers partially helpful, but without an example I don't understand what "custom actions" are or "deeplink to another SDK" means.

I can't see why Expo Router can't handle this scenario. Its just that the previous approach you were using isn't possible.

**Comment by GibbyBox** [comment]
> 1. That should be possible via the middleware

Every MMP I've evaluated so far has our apps open with a custom shortened link on an associated domain which expect our application to hand this _full_ link to their SDK's to process and receive what the real long link to navigate to should be. The pathname alone does not cut it.

Think url shorteners. If we receive `https://bit.ly/randomString` that is configured to navigate to `/person/1`, the pathname we'll receive is `randomString`. We can't honestly determine from that alone if that is a link we should pass to these third party SDKs to get `person/1` or if that was a genuine attempt to navigate to `randomString` and thus show a 404 message.

This is something that was highlighted all the way back in v1
https://github.com/expo/router/discussions/656.

**Comment by jp1987** [comment]
@youssdevx did you ever find a work around for this? I am running into a similar issue trying to implement Appcues, see https://github.com/appcues/appcues-react-native-module/issues/147

**Comment by youssdevx** [comment]
@jp1987 Not yet unfortunately...

**Comment by jp1987** [comment]
> @jp1987 Not yet unfortunately...

Shame. I am actually considering migrating to React Navigation to get access to the linking configuration. But seems massively counter productive.

**Comment by marklawlor** [comment]
We are current experimenting with exposing a subset of the linking configuration https://github.com/expo/expo/pull/27757

**Comment by youssdevx** [comment]
Thanks @marklawlor, please let us know if it is successful or if you need us to test your implementation 🙏🏽

**Comment by vonkanehoffen** [comment]
@marklawlor so I see in the Expo 51 changelog:

> Support to handle rewriting deeplinked URLs.

Guessing that could be related to this issue? Any clues how that works? 🙏

**Comment by mersiades** [comment]
> Every page in Expo Router automatically configured for deep-linking, so your deep link should point directly at the target page and shouldn't need to be redirected.
> 
> If you migrating an existing app which has links that don't match your Expo Router page paths, you can use the root `_layout` file in a "middleware" pattern to perform top-level redirects.
> 
> ```
> // _layout.tsx
> export default function () {
>   const pathname = usePathname();
>   
>   if (<pathname-condition>) {
>     return <Redirect href="/<page>" />;
>   } else {
>     return <Stack />
>   } 
> }
> ```
> 
> We're looking at improving redirects/rewrites in the future
> 
> If this doesn't answer your question, can you reply with more detail about you need to achieve or with a sample of your `getInitialURL` code.

Is there a recommended place to put this 'middleware', @marklawlor ? When I put it in my root `_layout.ts`, I get `[Error: Attempted to navigate before mounting the Root Layout component. Ensure the Root Layout component is rendering a Slot, or other navigator on the first render.]`, which makes sense, I guess.

Also, do you have an updated timeline for when we might see some documentation around "Support to handle rewriting deeplinked URLs"? Even just a code snippet would be helpful at this stage.

Thanks.

**Comment by w4t3r-45** [comment]
same issue guys , i cannot intercept the deeplinks to perform custom actions , what are the suggestions please ?

**Comment by mersiades** [comment]
> same issue guys , i cannot intercept the deeplinks to perform custom actions , what are the suggestions please ?

@w4t3r-45 @vonkanehoffen I'm told the documentation is 'on the way', but this (kinda) works for me:

1. Create a file called +native-intent.ts in your /app directory.
2. Add this method to it:
```
export const redirectSystemPath = ({
  path,
  initial,
}: {
  path: string;
  initial: boolean;
}) => {
  // Make any changes to path here

  return path;
};
```

There's also a `subscribe()` method, but I haven't figured out how to use that yet.

**Comment by lsarni** [comment]
@mersiades did you find a way of testing this locally?

**Comment by mersiades** [comment]
@lsarni Thanks. Do you mean did I get it to work, or did I find a way to write tests for it?

If the former, it sorta works, but I had to give up on `expo-router` until [this issue](https://github.com/expo/expo/issues/30038) is addressed.

For the latter, no, I have not tried to write any tests for it.

**Comment by SohelIslamImran** [comment]
Here is a solution to use the subscribe method like [React Navigation](https://reactnavigation.org/docs/5.x/deep-linking/#third-party-integrations)

Add this patch
[expo-router+3.5.23.patch](https://github.com/user-attachments/files/17099916/expo-router%2B3.5.23.patch)

Then export a function inside `+native-intent.tsx`

```tsx
export async function redirectSystemPath({
  path,
  initial,
}: {
  path: string;
  initial: boolean;
}) {
  if (initial) {
    const params = await branch.getLatestReferringParams(true);
    if (params?.$deeplink_path) return params?.$deeplink_path;
    return path;
  }
  return path;
}

export function subscribe(listener: (url: string) => void) {
  return branch.subscribe(({ error, params, uri }) => {
    if (error && !error.includes("Session initialization already happened")) {
      sendReport(new Error(error));
      return;
    }

    if (params?.$deeplink_path) listener(params?.$deeplink_path as string);
  });
}

```
