### ISSUE TITLE
(Expo 50) Bare minimum project iOS build failure

### ISSUE THREAD

**Issue by strycz** [expo/expo#27170]
### Minimal reproducible example

https://github.com/strycz/ios-build-fail

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Steps:
1. Created new project with  "npx create-expo-app"
2. Run project with "npx expo run:ios"

Result:
iOS build is failing

Error output from command:

> note: Run script build phase '[Expo] Configure project' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'expo50iosbuildfail' from project 'expo50iosbuildfail')
> note: Run script build phase 'Bundle React Native code and images' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'expo50iosbuildfail' from project 'expo50iosbuildfail')
> warning: Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
> warning: Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')
> 
> 
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:iOS Simulator, id:3007E991-AA4D-4701-915B-A374901FFFEC, OS:17.2, name:iPhone 15 Pro }
> { platform:iOS Simulator, id:3007E991-AA4D-4701-915B-A374901FFFEC, OS:17.2, name:iPhone 15 Pro }
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/pawel/Library/Developer/Xcode/DerivedData/expo50iosbuildfail-degygirqgjhyvyhhcjfdknmwlztf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00017CC0.sh (in target 'React-rncore' from project 'Pods')
> (1 failure)
> Build logs written to /Users/pawel/Workspace/vscode repos cloned from github/expo-50-ios-build-fail/.expo/xcodebuild.log`
> 

### Environment

System:
OS: macOS 14.2.1
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.0/bin/yarn
npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.12.1 - /opt/homebrew/lib/ruby/gems/3.2.0/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
Android Studio: 2022.3 AI-223.8836.35.2231.10811636
Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
expo: ~50.0.7 => 50.0.7
react: 18.2.0 => 18.2.0
react-native: 0.73.4 => 0.73.4
npmGlobalPackages:
eas-cli: 7.1.2
Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
hi there! i tested with your repo and it works for me. i think that's more about environment issue. could you share your log here for more details, `Build logs written to /Users/pawel/Workspace/vscode repos cloned from github/expo-50-ios-build-fail/.expo/xcodebuild.log`?

**Comment by strycz** [comment]
[xcodebuild.log](https://github.com/expo/expo/files/14341200/xcodebuild.log)
Sure, thanks for help - attaching my log file.

**Comment by Kudo** [comment]
thanks for sharing the information. `/bin/sh: /Users/pawel/Workspace/vscode: No such file or directory` that's the error.

i guess react-native's codegen integration doesn't well support path with spaces. please try to rename your path from `/Users/pawel/Workspace/vscode repos cloned from github/expo-50-ios-build-fail/` to `/Users/pawel/Workspace/repos/expo-50-ios-build-fail/`

**Comment by strycz** [comment]
Thanks, wasn't aware of that.
Renaming solved the issue for me.

**Comment by Aarchi-Ayoub** [comment]
[xcodebuild.log](https://github.com/user-attachments/files/16032939/xcodebuild.log)
<img width="948" alt="Screenshot 2024-06-28 at 16 43 40" src="https://github.com/expo/expo/assets/61331286/0ef2dcde-3ef7-475c-818a-fa23399cad32">

Hey, i'm probably facing the same error. But for my case the log file look like this

**Comment by ZaharGusyatin** [comment]
any solution?
