### ISSUE TITLE
React Native Svg Linear Gradient Not loading when redirecting to bottom navigation tab

### ISSUE THREAD

**Issue by oliviercperrier** [expo/expo#27177]
### Minimal reproducible example

```
1. git clone https://github.com/oliviercperrier/react-native-svg-linear-gradient-repro
2. npm install
3. npm run web
4. Load the app from the root `localhost:8081/`
5. Go to page one
6. SVG should be loading (but its not)
```

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Not sure if this is an expo router bug, but ill put that here as well as in react-native-svg repo (https://github.com/software-mansion/react-native-svg/issues/2225)

I have a SVG with a Linear Gradient Bg, when i use a flat color bg everything is fine.

I have this router:
- Tab Nav
     - Page One
     - Page Two 

Some Details:
- The SVG is on Page One.
- The root of my app is redirecting the user to page Two in the Tab Nav (First page that should be shown). 

If i open my app from the root (localhost:8081/), i get to Page Two and when i get to page one (by click in the tab nav), the SVG doesn't load, but the SVG element is in the DOM.

if i open my app from page two (localhost:8081/two) and then go to page one, the SVG load correctly.

I Added a video here: [Screen Recording 2024-02-19 at 2.01.11 PM.zip](https://github.com/expo/expo/files/14336057/Screen.Recording.2024-02-19.at.2.01.11.PM.zip)

In the video i first:

- Load the app from root and show the svg not loading,
- Then i load the app from page two and show that the svg is loading correctly

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.7 => 50.0.7
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by EvanBacon** [comment]
This is not related to Expo Router.
