### ISSUE TITLE
Clicking tab icon doesn't always pop back to root view

### ISSUE THREAD

**Issue by JClackett** [expo/expo#27183]
### Minimal reproducible example

https://github.com/JClackett/expo-router-tabs-stack

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I noticed that if you have a folder as one of the tabs and have nested screens inside, that tab won't pop back to the root when clicking the icon in the tab bar.

In the screen shot below you can see that the `account` directory is a folder, whereas `feed` and `index` are files. When pushing screens to feed or index, clicking the tab icon always pops back to the root view, whereas account doesn't do anything.

<img width="321" alt="Screenshot 2024-02-20 at 12 49 18" src="https://github.com/expo/expo/assets/12549124/994b140e-be05-40d4-9880-680365092830">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.18.2 - /var/folders/dt/wxhpvnj560xc4_qw5nnbsqw40000gn/T/fnm_multishells/84382_1708429051952/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /var/folders/dt/wxhpvnj560xc4_qw5nnbsqw40000gn/T/fnm_multishells/84382_1708429051952/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.7 => 50.0.7 
      expo-router: 3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.2.0
    Expo Workflow: managed

**Comment by JClackett** [comment]
Any idea if this is being worked on?

**Comment by marklawlor** [comment]
> I noticed that if you have a folder as one of the tabs and have nested screens inside, that tab won't pop back to the root when clicking the icon in the tab bar.

Clicking the icon doesn't say "go to this URL", it simply tells the underlying navigator that it should display that tab. Your "tab" folders are creating nested navigators, which have their own sub navigation.

To clear up what is happening:

- Home: Using tab navigator. Pushing within this tab will add to the tab navigator history
- Feed: Same as home
- Account: Using a sub navigator (Stack). Navigating within this tab is pushing to the stack history (not the tab history). Clicking on the Account tab again, it will do nothing as the tab navigator only "sees" one route (the route with the Stack)

**Comment by JClackett** [comment]
Is this only available in the expo-router 3.5?

**Comment by JClackett** [comment]
So I noticed a few things:
1. you need to check which tab segment you're on before calling the dismissAll function, otherwise clicking a tab icon will pop back to first screen when navigating back to that tab, where the expected behaviour is to remain on the screen you left it on. Only when youre on the tab should it pop back to root.
2. I noticed the dismissAll is still not popping back to the root in some cases, if I have multiple nested stacks in a tab, it pops back to the previous stack but you need to keep clicking the tab for it to go back to the very root, any ideas why?

**Comment by harshit-khandelwal-pi** [comment]
> you need to check which tab segment you're on before calling the dismissAll function, otherwise clicking a tab icon will pop back to first screen when navigating back to that tab, where the expected behaviour is to remain on the screen you left it on. Only when youre on the tab should it pop back to root.

What is the code for this?

**Comment by JClackett** [comment]
@harshit-khandelwal-pi 

```tsx
// useTabSegment

import { useSegments } from "expo-router"

type Group<T extends string> = `(${T})`

type SharedSegment = Group<"index"> | Group<"account"> | Group<"users"> | Group<"spots"> | Group<"trips">

type Home = Group<"home">

export type TabSegment = `${Home}/${SharedSegment}`

export function useTabSegment() {
  return useSegments().slice(0, 2).join("/") as TabSegment
}



// Tabs
const tab = useTabSegment()


// render
<Tabs.Screen
        name="(account)"
        listeners={{
          tabPress: () => {
            if (tab === "(home)/(account)" && router.canDismiss()) {
              router.dismissAll()
            }
          },
        }}
/>
```
