### ISSUE TITLE
Expo Image onLayout not working on web

### ISSUE THREAD

**Issue by FredrikErikJohansson** [expo/expo#27198]
### Minimal reproducible example

https://github.com/FredrikErikJohansson/expo-image-onlayout

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

The onLayout callback of expo-image is ignored on web and this is the output in the console:

![Screenshot from 2024-02-21 11-13-39](https://github.com/expo/expo/assets/24506304/92588d32-247b-4224-91bc-b8162176c10e)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    npmPackages:
      expo: ~50.0.7 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.2.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by SirMorfield** [comment]
+1

**Comment by FredrikErikJohansson** [comment]
@aleqsio I'm still experiencing the same issue on v1.12.15. I updated the packages for the minimal reproducible example.
