### ISSUE TITLE
Relay fetchQuery error: No data return for operation

### ISSUE THREAD

**Issue by jamesallain** [expo/expo#272]
Hey, I'm trying to get my createRelayEnvironment going. This is my fetchQuery...

```
function fetchQuery (operation, variables, cacheConfig, uploadables) {
  return fetch('http://192.168.1.129:3080/graphql', {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      query: operation.text, // GraphQL text from input
      variables
    })
  }).then(response => {
    console.log("fetchQuery response:",reponse);
    return response.json()
  }).catch((err) => {
     console.log("fetchQuery error:", err);
     return err; 
  })
}
```
This is the error I get in my Expo logs...
```
{"line":115109,"column":48,"sourceURL":"http://localhost:19002/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles"}
```
I get this error from my console.log...
```
No data return for operation
```
My endpoint works great in Graphiql. Relay-compiler generated it's schema. The app works, but there's just no data coming in.

Thanks for any help! I'm pretty stuck.

**Comment by dikaiosune** [comment]
Hi! Sorry that you're having issues with this. Unfortunately we're not able to help with issues for Relay, as it's a separate project. I would recommend checking that you can reach the URL on the second line from your phone's web browser. If you can, but Expo still isn't able to see the URL, please report back and I'll reopen this issue. If your phone's browser can't reach that URL, I'd recommend troubleshooting your network and making sure that your phone can see your computer.
