### ISSUE TITLE
Initial camera orientation is portrait even when device's orientation is landscape

### ISSUE THREAD

**Issue by ManuelBahamonde** [expo/expo#27218]
### Summary

After upgrading from SDK 49 to SDK 50, Camera doesn't seem to respect the device's orientation at first. Basically, when device's orientation is landscape and Camera component is rendered, camera's orientation is portrait.

When changing the device's orientation, the camera's changes correctly, so this can be fixed if the device's orientation is manually changed to Portrait and then to Landscape, but there seems to be some issue that prevents the Camera component from detecting the device's initial orientation (seems to always detect it as Portrait).

I was able to reproduce this issue using both Expo Go app and debug/production builds in an iPad 8th Gen. I wasn't able to reproduce it in my Android phone.

### What platform(s) does this occur on?

iOS

### SDK Version

50

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.1 - C:\Extras\NodeJS\node.EXE     
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.1 - C:\Extras\NodeJS\npm.CMD        
    npmPackages:
      babel-preset-expo: ^10.0.0 => 10.0.1
      expo: ^50.0.0 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/ManuelBahamonde/Expo-Camera-Orientation-Issue

Steps to reproduce are in README.md

**Comment by joshuayoes** [comment]
I am also experiencing this on a client app

**Comment by dellasys** [comment]
I’m having this issue as well. SDK50.

**Comment by alexander-schranz** [comment]
Does this maybe have todo with the [responsiveOrientationWhenOrientationLocked](https://docs.expo.dev/versions/latest/sdk/camera-next/#responsiveorientationwhenorientationlocked) setting 🤔 Sadly the docs don't tell what is default.

**Comment by alexander-schranz** [comment]
Nice to see this fixed 🎉 . Thank you! I'm not familiar with the release cycle of expo packages, when are the next bugfix releases planned?

**Comment by alexander-schranz** [comment]
It looks like expo would have canary releases but the expo-camera seems not be triggered yet with the latest changes: https://www.npmjs.com/package/expo-camera?activeTab=versions is it possible that somebody triggers that?

**Comment by joshuayoes** [comment]
@alexander-schranz it appears this went out in `14.1.0`

**Comment by alexander-schranz** [comment]
Can confirm that fixed the issue!

**Comment by joshuayoes** [comment]
@ManuelBahamonde your reproduction will work correctly on my test device on the initial render, but after subsequent renders, it will default to the original behavior of showing the camera preview in portrait when the device is in landscape.

**Comment by CPedrini** [comment]
Hi @joshuayoes, do you thing that something should be changed in Manuel's code or shall this issue be reopen?

**Comment by lxfz** [comment]
Can confirm this.

**Comment by lxfz** [comment]
> Hi everyone! I'm not sure this issue was correctly fixed. I tested both `14.1.0` and `14.1.1` expo-camera versions, and neither seem to work properly.
> 
> I did this test in the [minimal reproducible example app](https://github.com/ManuelBahamonde/Expo-Camera-Orientation-Issue) after updating the packages version using `npx expo install`. I sent a new commit with the updated versions in `package.json` so you can check them too.

Can confirm this.

**Comment by ManuelBahamonde** [comment]
Hi @alanjhughes, just wanted to let you know that it seems this issue was not fixed with your changes. 

If you check the [minimal reproducible example app](https://github.com/ManuelBahamonde/Expo-Camera-Orientation-Issue), you'll see that the initial camera's orientation is still being forced to portrait even when the device is in landscape.

**Comment by alanjhughes** [comment]
Hi @ManuelBahamonde - I've just pulled your repro and it still does not reproduce. If you can change it to display the incorrect behaviour I will be able to investigate

**Comment by ManuelBahamonde** [comment]
> Hi @ManuelBahamonde - I've just pulled your repro and it still does not reproduce. If you can change it to display the incorrect behaviour I will be able to investigate
> 
> Also, you are not using the `responsiveOrientationWhenOrientationLocked` prop

That's strange. I can easily reproduce it on my device, both when I use that prop and when I don't. I'm not sure why you can't reproduce it on your end, but I've uploaded a video to Google Drive to better showcase the issue and the reproduction steps: https://drive.google.com/file/d/1IC-0T9RMbJ17eLZEfOSQswaSonnnwzU6/view

The steps I followed to reproduce the issue are written in README.md file in the repro, and I'm using an iPad 8th gen. 
Please let me know if there's anything I can do to help.

**Comment by CPedrini** [comment]
Hi @alanjhughes, sorry to bother. Were you able to confirm if it was related to the device?

**Comment by alanjhughes** [comment]
Hi everyone, apologies for the late response. So I have looked into this again and the problem is still not reproducing for me since the original fix. See attached video. The is running on an iPad pro using the provided repro. The test app is locked to landscape and the preview renders that way. You can see I hit save to make a JS change which also has no impact. I even rotate the device to see can I trigger any unusual behaviour but it works as expected. 

I made some modifications to the repro. It was using legacy camera which we will no longer be supporting. Here is my `App` component. 

```typescript
export default function App() {
  const [shouldRenderCamera, setShouldRenderCamera] = useState(false);
  const [permission, requestPermission] = useCameraPermissions();

  useEffect(() => {
    if (!permission?.granted) {
      requestPermission();
    }
  }, [permission]);

  const toggleCamera = () => setShouldRenderCamera((prevState) => !prevState);

  return (
    <View style={styles.container}>
      {shouldRenderCamera && (
        <CameraView
          style={styles.camera}
          mode="picture"
          facing="back"
          responsiveOrientationWhenOrientationLocked
        />
      )}
      <Button title="Toggle Camera Test" onPress={toggleCamera} />
      <StatusBar style="auto" />
    </View>
  );
}
```

https://github.com/expo/expo/assets/30924086/820dcc5b-4c4b-4d6f-b9e7-a4f8dfed7891

**Comment by MCervenka** [comment]
i reproduced the issue with ManuelBahamonde repository. Indeed. After toggling video when  I hold the phone in landscape, the preview is 90 degree rotated. I have to rotate the phone 90 degrees and back to get the correct rotation of preview.

**Comment by MCervenka** [comment]
Since I always use the camera in my app in landscape I created this patch which seems to work good.
[expo-camera+14.1.3.patch](https://github.com/expo/expo/files/15110817/expo-camera%2B14.1.3.patch)

**Comment by MCervenka** [comment]
I managed to made a prop isLandscape that would fix it to landscapeRight.
[expo-camera+14.1.3.patch](https://github.com/expo/expo/files/15155398/expo-camera%2B14.1.3.patch)

**Comment by marcosrjjunior** [comment]
I was have the orientation issue as well running on `"expo-camera": "~15.0.13"`.
iOS 17.5.1 9th gen (iPad)

The issue is fixed after applying the patch above.
@MCervenka 

`git apply expo-camera+14.1.3.patch` (file path)

https://github.com/expo/expo/blob/72b3295ce4d2030f6e5fe1d3391236d9e6c0bdd6/packages/expo-camera/ios/Current/CameraView.swift#L124

Not really sure if that is a proper fix, but it is working.

**Comment by myou11** [comment]
I am using `expo-camera: 14.1.3` and this is an issue even after the patch. My use case is that I am conditionally rendering the camera based on some state. The initial render of the camera is in the correct orientation. However, once I press my button to hide the camera, then press again to un-hide, the camera orientation is exactly like what is shown in @ManuelBahamonde videos.

This is only an issue when device orientation is locked. If I turn off my ipad's orientation lock, the camera seems to display fine upon hiding/un-hiding
