### ISSUE TITLE
expo-sqlite never returns on SQL error on Android

### ISSUE THREAD

**Issue by wtracy** [expo/expo#27219]
### Minimal reproducible example

https://github.com/wtracy/sqliteerrordemo

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When a call to expo-sqlite triggers an SQL error, the call never completes on Android. On iOS, it raises an exception, as expected. This behavior seems consistent whether the error is a constraint violation in an INSERT, creation of a table that already exists, or an attempt to transact while another transaction is already ongoing.

See the transactionAsync() call in App.tsx.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.7 => 50.0.7 
      react: ^18.2.0 => 18.2.0 
      react-native: ^0.73.4 => 0.73.4 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
hi there! can you please try this with expo-sqlite/next? https://docs.expo.dev/versions/latest/sdk/sqlite-next/ - this will be replacing the expo-sqlite implementation in sdk 51

**Comment by wtracy** [comment]
My example program works as expected when ported to sqlite-next.

Is the old API being retired completely? I'm not looking forward to rewriting my program against a new API, but you do what you gotta do.

**Comment by brentvatne** [comment]
yes, the plan is to deprecate the old expo-sqlite api in sdk 51. we'll prepare a migration guide at that time, and i expect for most apps it should be relatively painless and a matter of changing function names. the new api is much improved and should be worth the trouble, but nonetheless, sorry for the thrash!
