### ISSUE TITLE
"Main" has not been registred. 

### ISSUE THREAD

**Issue by lukaszduszenko89** [expo/expo#27220]
### Summary

Hello everyone. After 2 days of using the Expo app, I can't deal with an error that wasn't there before. I have set up a work environment, I have development and production versions on my Expo.dev account. After literally 2 days of use, an error occurred Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes. 
and I can't find out how to fix this error. The strange thing is that for a total of 1 day everything worked fine. 
Later this problem appeared and you can't enter your application at all. Please help!

### What platform(s) does this occur on?

Android

### SDK Version

50.0.0

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ~50.0.7 => 50.0.7
      expo-router: ^3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: managed

### Minimal reproducible example

 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

**Comment by phollaki** [comment]
+1

**Comment by lukaszduszenko89** [comment]
> +1

?

**Comment by byCedric** [comment]
The `Invariant Violation: "main" has not been registered` can unfortunately happen because of various reasons. Some of them include:

- The `package.json` entry points to an incorrect bundle entry
- There are compilation issues that "breaks" the bundled JS code, e.g. through faulty babel plugins
- There are issues with the Metro configuration or setup

In order for us to help you, we would need a reproducible example of the project that causes this error, preferably in form of a repository. I'd be more than happy to dive in a see what's causing this issue.

Hope this helps!

---

PS. Responding with `+1` or `Same issue here` doesn't help figuring out what the issue is. Instead of replying with that, please reply with a repository that we can use to debug this. 😄

**Comment by lukaszduszenko89** [comment]
![Zrzut ekranu 2024-02-24 004614](https://github.com/expo/expo/assets/131206984/c23f475c-cc56-4ace-ae7d-08cc1b9ddd67)
This is what my App.tsx and current dependencies look like, including the NAME of my application. In its current form, where in App.tsx there is only a simple text "Welcome to the app!!" after entering the command: npx expo start --dev-client, the application opens normally on my phone. The problem occurs when I want the component visible in the photo to be displayed instead of the App.tsx screen: index.tsx, which is actually my first page after opening the application. Whenever I modified App.tsx so that it could be accessed via "navigation" to the component's Dashboard.tsx, an error appeared as in the topic

**Comment by lukaszduszenko89** [comment]
sorry for long brake. Here i send a PrtSc with error 
![Zrzut ekranu 2024-03-08 200732](https://github.com/expo/expo/assets/131206984/7b379a90-5b6c-425b-b2f4-ed9e194bb70b)

**Comment by phollaki** [comment]
For me Android Studio device was the root cause of the error. After setting up my environment as described in the Expo documentation, the error disappeared. 
You should attempt to configure and recreate your Android emulator device as instructed here: https://docs.expo.dev/workflow/android-studio-emulator/

**Comment by lukaszduszenko89** [comment]
I'll try to do that. But what if I use my phone as a device to display applications during production? I mean that I use Expo Go --dev-client and I wanted to display the application I am creating on a mobile device and not using an emulator?

**Comment by bhirmbani** [comment]
I think this error somehow related to this https://docs.expo.dev/workflow/common-development-errors/#module-appregistry-is-not-a-registered-callable-module-calling-runapplication error

Im doing fresh install using expo cli today (ver 50) and got the same error, after doing recommended step from page above which is
```
npx expo start --no-dev --minify
```
the error was no longer there

**Comment by DrNapNap** [comment]
my code works fine on the web version but as soon as i get on android it all falls apart

I've had it for a day now clean install clean everything And it doesn't work Do you have any ideas what I can do

![image](https://github.com/expo/expo/assets/54890080/7ff1faa7-bc79-4335-99ef-c23fe793bcc0)

**Comment by purple-blanket** [comment]
@DrNapNap , I had the same issue multiple times here are my suggested solutions:
1. Make sure your expo cli is the latest. Try `npm install expo@latest` or `yarn add expo@latest`
2. Make sure your dependencies are have no version issues. Try using expo doctor to fix : `npx expo-doctor`, try suggested fixes until all your issues are solved and try running it again. 
3. If all doesn't work, delete your `node-modules` folder and run `npm install` -- if you get dependency errors try using peer dependencies. After trying it all if your app still crashes, try disabling components to find out which package was causing the issues. Some dependencies wont work after the latest updates you need to identify which ones are causing problems. 

I hope it helps.

**Comment by krolow** [comment]
Facing that same issue after upgrade to latest expo SDK 51 app was working fine with SDK 50 I didn't come to a solution yet

**Comment by MutlucanKarinca** [comment]
I have the same problem. I use react native, expo, firebase. When I add Firebase messaging it gives this error.

```
import { getMessaging } from "firebase/messaging";

export const messaging = getMessaging(app);
```

When I add this block of code

  _ERROR TypeError: Cannot read property 'addEventListener' of undefined, js engine: hermes
  ERROR Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is running from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes_

gives this error.

**Comment by purple-blanket** [comment]
@krolow After the update, I started having issues with many libraries. I had to find out which ones were the problematic ones. Try my suggested solution to see where the dependencies of your libraries give errors and try removing / adding them while testing. This would help you find where the problem is. Some of my issues were due to `react-native-snap-carousel` and `react-native-deck-swiper` .

**Comment by purple-blanket** [comment]
@MutlucanKarinca Did you initialize the app? it should look something like this:
```
import { initializeApp } from "firebase/app";
import { getMessaging } from "firebase/messaging";

const  app = initializeApp(firebaseConfig); // make sure you have the firebase Config
const messsaging = getMessaging(app);

export {messaging}
```


> I have the same problem. I use react native, expo, firebase. When I add Firebase messaging it gives this error.
> 
> ```
> import { getMessaging } from "firebase/messaging";
> 
> export const messaging = getMessaging(app);
> ```
> 
> When I add this block of code
> 
> _ERROR TypeError: Cannot read property 'addEventListener' of undefined, js engine: hermes ERROR Invariant Violation: "main" has not been registered. This can happen if:
> 
> * Metro (the local dev server) is running from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes_
> 
> gives this error.

**Comment by DrNapNap** [comment]
I changed all my code to typeScript/tsx and everything works 

> @DrNapNap , I had the same issue multiple times here are my suggested solutions:
> 
> 1. Make sure your expo cli is the latest. Try `npm install expo@latest` or `yarn add expo@latest`
> 2. Make sure your dependencies are have no version issues. Try using expo doctor to fix : `npx expo-doctor`, try suggested fixes until all your issues are solved and try running it again.
> 3. If all doesn't work, delete your `node-modules` folder and run `npm install` -- if you get dependency errors try using peer dependencies. After trying it all if your app still crashes, try disabling components to find out which package was causing the issues. Some dependencies wont work after the latest updates you need to identify which ones are causing problems.
> 
> I hope it helps.

I changed all my code to type Script and everything works and now my app runs perfectly

**Comment by DrNapNap** [comment]
> @krolow After the update, I started having issues with many libraries. I had to find out which ones were the problematic ones. Try my suggested solution to see where the dependencies of your libraries give errors and try removing / adding them while testing. This would help you find where the problem is. Some of my issues were due to `react-native-snap-carousel` and `react-native-deck-swiper` .



> @krolow After the update, I started having issues with many libraries. I had to find out which ones were the problematic ones. Try my suggested solution to see where the dependencies of your libraries give errors and try removing / adding them while testing. This would help you find where the problem is. Some of my issues were due to `react-native-snap-carousel` and `react-native-deck-swiper` .

switch all to Type scripts and that is Create a new project Move all your stuff Make it type safe Of course, make a backup of everything before

**Comment by MutlucanKarinca** [comment]
> @MutlucanKarinca Did you initialize the app? it should look something like this:
> 
> ```
> import { initializeApp } from "firebase/app";
> import { getMessaging } from "firebase/messaging";
> 
> const  app = initializeApp(firebaseConfig); // make sure you have the firebase Config
> const messsaging = getMessaging(app);
> 
> export {messaging}
> ```
> 
> > I have the same problem. I use react native, expo, firebase. When I add Firebase messaging it gives this error.
> > ```
> > import { getMessaging } from "firebase/messaging";
> > 
> > export const messaging = getMessaging(app);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I add this block of code
> > _ERROR TypeError: Cannot read property 'addEventListener' of undefined, js engine: hermes ERROR Invariant Violation: "main" has not been registered. This can happen if:
> > 
> > * Metro (the local dev server) is running from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> > * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes_
> > 
> > gives this error.

Yes. My code is same as your code

**Comment by abeni16** [comment]
I have got the same problem ,please help!
![image](https://github.com/expo/expo/assets/59653585/8c55afa6-02bd-4a2e-b8d7-58569c97f216)

**Comment by Talha12Shiekh** [comment]
When i upgraded to sdk 51 from 50 i am getting this error again and it is not resolving can anyone tell how to fix it

**Comment by toficofi** [comment]
Getting this error with a brand new project on 51.

**Comment by yuma1217** [comment]
Me too.

**Comment by DrNapNap** [comment]
> Me too.
> 
> ```
>  ERROR  Invariant Violation: No callback found with cbID 2 and callID 1 for module <unknown>. Args: '[{"app_state":"active"}]', js engine: hermes
>  ERROR  Invariant Violation: No callback found with cbID 20 and callID 10 for module <unknown>. Args: '[{"app_state":"active"}]', js engine: hermes
>  ERROR  Invariant Violation: No callback found with cbID 41 and callID 20 for module <unknown>. Args: '[17]', js engine: hermes
>  ERROR  Invariant Violation: "main" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> ```

Just create a new project with the latest version

**Comment by LMarcinkowski** [comment]
Same error after upgrading from 50 to 51.

**Comment by chakravarthi-bb** [comment]
I am trying to migrate from Bare React Native to Expo and this is happening

**Comment by infas03** [comment]
in Android and iOS simulator are working fine. but in Expo Go its throwing same error

the error:
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

**Do any one have correct _fix_?**

**Comment by LadyEpona** [comment]
For me it helped to make a new dev build since I'm using `expo-dev-client` and not Expo Go app.

**Comment by jetroni** [comment]
I was facing the same issue as I had to upgrade from Expo 49 to 51. The fix for me was downgrading `react-native` from `0.74.2` to `0.73.8`. That is all I did, hope this helps others aswell!

**Comment by sirusbaladi** [comment]
> I was facing the same issue as I had to upgrade from Expo 49 to 51. The fix for me was downgrading `react-native` from `0.74.2` to `0.73.8`. That is all I did, hope this helps others aswell!

did you make a new build after downgrading?

**Comment by Ruwiseturtle** [comment]
https://github.com/Ruwiseturtle/React_native-firstProject I have such an error. Please take a look

**Comment by coderDancer** [comment]
> react-native

I tried all possible solutions
and finally
the issue was resolved by downgrading the React Native version from 0.74.3 to 0.73.8

@expbot  I hope the official team can resolve this issue

**Comment by Alan-Graton** [comment]
Having the same problem. Fresh new project with Expo SDK 51 and react-native on ^0.74.3. Was not able to solve it by downgrading react-native to 0.73.8.

Another co-worker had the same issue, but out of nowhere the problem solved itself for her. I still got the same error and not able to execute my expo projects ;-;

**Comment by Ruwiseturtle** [comment]
я в ехпо зарегистрировалась и зашла под своим логином. Так что проблема
решилась сама по себе, но, может, это и помогло. я в .env прописала файлы,
где есть секретные данные

пн, 15 июл. 2024 г. в 22:15, Alan Graton Lourenço de Brito <
***@***.***>:

**Comment by jetroni** [comment]
I see most of you guys use `react-native-snap-carousel`, that’s causing the issue at the moment since it’s still using ViewPropTypes. Just migrate to `react-native-reanimated-carousel` because the other library seems dead at this point.

**Comment by Punith-goud** [comment]
@jetroni  OMG, thank you so much for this man, I removed that package and it really worked.

**Comment by Inalegwu** [comment]
I have just migrated to SDK 51 to work with the latest Expo Go app and I also have this issue.
I tried creating a new project also with SDK 51 and the issue also exists there so I can conclude none of my dependencies are an issue. My project is also already in typescript.

**Comment by Talha12Shiekh** [comment]
The people who are facing error when they are upgrading there expo project from sdk older version to the latest version can fix it by this way
Do not upgrade the sdk to the latest version instead download the specific version of expo go app for that sdk version in which your project is built from the expo.dev website

**Comment by ide** [comment]
**"main" has not been registered** is an error message that occurs when another error has occurred earlier in the the app.

What's happening is:

1. Your app launches and an error is thrown (the true root cause you need to debug).
2. This causes the JavaScript code to stop running and it never reaches `AppRegistry.registerComponent('main', rootComponent)`.
3. The native code in your app attempts to render your main root React component by invoking `AppRegistry.runApplication('main', props)` but since `AppRegistry.registerComponent('main', ...)` was never called successfully, it throws an error saying "main" has not been registered.

Ideally, react-native would not attempt to call `AppRegistry.runApplication` when an error occurs earlier on.

## How to debug this
Read the native error logs through `adb logcat` for Android and the macOS Console app for iOS. This is usually the best place to find information about the error that caused the JS not to reach the `AppRegistry.registerComponent` call. Fixing all of the launch errors in your app will fix the "'main' has not been registered" error.

**Comment by the-kamol** [comment]
> I was facing the same issue as I had to upgrade from Expo 49 to 51. The fix for me was downgrading `react-native` from `0.74.2` to `0.73.8`. That is all I did, hope this helps others aswell!

That worked for me, thanks a lot! 🫡

**Comment by shiner527** [comment]
> I was facing the same issue as I had to upgrade from Expo 49 to 51. The fix for me was downgrading `react-native` from `0.74.2` to `0.73.8`. That is all I did, hope this helps others aswell!

It is also worked for me, thank you!

**Comment by spenavajr** [comment]
Changing `react-native` to `0.73.8` by itself didn't do it for me; however, once I manually deleted the app from my iOS simulator, it was good to go. Hope this helps someone.

**Comment by MujeebAyokunle** [comment]
I faced this issue and discovered that it was a package called "react-native-swipeout" that uses uses ViewPropTypes. I uninstalled it and it fixed my issue.

Note: If yours is not the package above, you can discover the package causing it by running 

`grep -r "ViewPropTypes" node_modules/`

It searches for the package using ViewPropTypes so you can do the needful with it. I hope this helps.

**Comment by timothydillan** [comment]
> I was facing the same issue as I had to upgrade from Expo 49 to 51. The fix for me was downgrading `react-native` from `0.74.2` to `0.73.8`. That is all I did, hope this helps others aswell!

As of the latest Expo version, to my understanding, the react native version required is 0.74 and above, therefore causing the same "main" has not been registered issue, again. Does anyone know how we can fix this, or at least use 0.73.8 with the latest expo version for eas builds?

**Comment by schimin** [comment]
Same to me.

`"dependencies": {
    "@react-native-firebase/analytics": "^20.4.0",
    "@react-native-firebase/app": "^20.4.0",
    "@react-native-firebase/auth": "^20.4.0",
    "@react-native-firebase/firestore": "^20.4.0",
    "@react-native-firebase/messaging": "^20.4.0",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@react-navigation/stack": "^6.4.1",
    "@types/react": "~18.2.79",
    "axios": "^1.7.4",
    "expo": "^51.0.29",
    "expo-application": "^5.9.1",
    "expo-build-properties": "^0.12.5",
    "expo-dev-client": "~4.0.23",
    "expo-font": "^12.0.9",
    "expo-network": "^6.0.1",
    "expo-status-bar": "^1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-encrypted-storage": "^4.0.3",
    "react-native-exit-app": "^2.0.0",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-paper": "^5.12.5",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-svg-transformer": "^1.5.0",
    "react-native-webview": "13.8.6",
    "typescript": "~5.3.3",
    "victory-native": "^41.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "@types/react-native": "^0.73.0"
  },`

Using NPM or YARN, problem.

**NPM**: ```
 Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSkiaModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","SourceCode","Timing","AppState","BlobModule","WebSocketModule","DevSettings","DevToolsSettingsManager","Networking","Appearance","DevLoadingView","HeadlessJsTaskSupport","DeviceInfo","UIManager","ImageLoader","SoundManager","IntentAndroid","DeviceEventManager","RNCSafeAreaContext","NativeAnimatedModule","I18nManager","RNExitApp","RNCWebView"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","LinkingManager","NativeReactNativeFeatureFlagsCxx","RNSModule","RNSkiaModule"]}, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**YARN**: Unable to resolve "../../src/private/specs/modules/NativeModalManager" from "node_modules\react-native\Libraries\Modal\NativeModalManager.js"

**Comment by VuongNhatHien** [comment]
> @DrNapNap , I had the same issue multiple times here are my suggested solutions:
> 
> 1. Make sure your expo cli is the latest. Try `npm install expo@latest` or `yarn add expo@latest`
> 2. Make sure your dependencies are have no version issues. Try using expo doctor to fix : `npx expo-doctor`, try suggested fixes until all your issues are solved and try running it again.
> 3. If all doesn't work, delete your `node-modules` folder and run `npm install` -- if you get dependency errors try using peer dependencies. After trying it all if your app still crashes, try disabling components to find out which package was causing the issues. Some dependencies wont work after the latest updates you need to identify which ones are causing problems.
> 
> I hope it helps.

Thank you it worked for me

**Comment by FlorianCassayre** [comment]
**Don't**:
```
npm install react-native-reanimated-carousel react-native-gesture-handler react-native-reanimated
```
**Do**:
```
npx expo install react-native-reanimated-carousel react-native-gesture-handler react-native-reanimated
```

**Comment by oiver555** [comment]
Hey guys just want to say after reading this entire forum and trying many things that were mentioned, what **finally** worked for me was following the advice in the docs where it says to use this 

```js
import { registerRootComponent } from 'expo';
import App from './App';
registerRootComponent(App);
```

in the entry file (index.js).

**Comment by kotsh23** [comment]
EXPO UPGRADE HELL
really is HELL
i hope if expo never ever release any more new versions 
because its like Killing old apps :D

anyone have fix for this ?

**Comment by Jerere** [comment]
Faced this issue with Android emulators and physical device when upgraded Expo version from 50 to 51.

What resolved the issue for us, was to **build and install new development build**. Not sure if this had something to do with this but also updated Android Studio version from old 4.1.1 to the latest 2024 version.

**Comment by BhavyaPatel305** [comment]
Personally for me, I was getting that error for days(Main not registered), almost tried everything but the main thing to consider here was to have not a single warning or error when you run: npx expo-doctor and if you get any errors then run: npx expo install --check

npx expo-doctor should show: Didn't find any issues with the project!

Personally for me this solved all the errors.

Hope this helps!

**Comment by lucasdallabeneta** [comment]
Faced this issue a couple times recently.

It happens to me when I compile my app on one computer and try to connect the app in another computer to continue the development. Creating a new build fixes it.

**Comment by w16342** [comment]
> 我的代码在网页版上运行良好，但一到安卓版就崩溃了
> 
> 我已经用了一天了，清理了所有东西，但它不起作用，你知道我该怎么办吗
> 
> ![图像](https://private-user-images.githubusercontent.com/54890080/327945749-7ff1faa7-bc79-4335-99ef-c23fe793bcc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODE4MTQsIm5iZiI6MTczMTM4MTUxNCwicGF0aCI6Ii81NDg5MDA4MC8zMjc5NDU3NDktN2ZmMWZhYTctYmM3OS00MzM1LTk5ZWYtYzIzZmU3OTNiY2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAzMTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDk2M2QwZjI3YjBlY2Q2MGM4YjA0OGI5MDNjZmI2M2RkNjJkODc4ZTk0MjJlNjc1NTEzOWExMzFiYWU0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h9KDVQjUn1xSt0q3-DuupvSEQdP7yGXazh1p3Ds0Ddw)

I also encountered the same problem，And I tried several solutions provided by everyone, but none of them could solve my problem

**Comment by ide** [comment]
**This error will be displayed less frequently in SDK 52 in favor of showing the underlying cause instead.** A default "main" component will be automatically registered before most of your application JS runs and it will show a more precise error if one occurs, unless something is very wrong with the primordial stage of your app's lifecycle and the new default "main" component cannot be registered.

**Comment by sagarkawad** [comment]
> I'll try to do that. But what if I use my phone as a device to display applications during production? I mean that I use Expo Go --dev-client and I wanted to display the application I am creating on a mobile device and not using an emulator?

Try to close all the opened tabs on your device and re-run the application using expo.

In my case, I closed all the opened tabs in the virtual device and relaunched the application. It worked fine. I think expo sometimes open another instance of the expo go on the device running the application and hence the error occurs. I hope it resolves your issue too.

**Comment by sagarkawad** [comment]
> my code works fine on the web version but as soon as i get on android it all falls apart
> 
> I've had it for a day now clean install clean everything And it doesn't work Do you have any ideas what I can do
> 
> ![image](https://private-user-images.githubusercontent.com/54890080/327945749-7ff1faa7-bc79-4335-99ef-c23fe793bcc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNDAyNjEsIm5iZiI6MTczNjMzOTk2MSwicGF0aCI6Ii81NDg5MDA4MC8zMjc5NDU3NDktN2ZmMWZhYTctYmM3OS00MzM1LTk5ZWYtYzIzZmU3OTNiY2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDEyMzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYmE0NjdmMTVjNjUwNDBhNWZmZDEzNTQ0YzQ3OGViNDdmOGIzZTczNDI4YjZmMjgzM2U1ZDY5M2QzZDc2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tnfT4WgHhJy6XM2W_T2ueyuQJk0PTEYQqfSeVINbz3M)

Just close all the opened tabs in your device and re-run the application.

**Comment by alexcraviotto** [comment]
> expo start --no-dev --minify

That's the solution, thanks!
