### ISSUE TITLE
[docs] expo router manual installation missing instruction: add "expo-router" to "plugins" property in `app.json` file

### ISSUE THREAD

**Issue by kevinjanada** [expo/expo#27221]
### Summary

Without "expo-router" in the "plugins" property in `app.json` file, the app breaks when you try to assign to `global` variable.

After manually installing `expo-router`, i came across this issue in my app.

![image](https://github.com/expo/expo/assets/20879857/bcfd30d2-360e-4e08-9f5a-9291e187c8f3)

after digging around i find that the issue is because i have this line in the root layout.

```ts
import "node-libs-expo/globals";
```

where inside it assigns to the global variable:
```ts
global.Buffer = require('buffer').Buffer;
global.process = require('process');

// Needed so that 'stream-http' chooses the right default protocol.
global.location = {
  protocol: 'file:',
  href: ''
};

// Some modules expect userAgent to be a string
global.navigator.userAgent = 'React Native';
```

after comparing my project with a fresh project generated by `npx create-expo-app@latest --template tabs@50`. The missing part was 

```json
// app.json
{
  "expo": {
    ...
    "plugins": [
      [
        "expo-router"
      ]
    ]
  }
}

```

which i think should be added to the docs.

would be happy to create a pull request if its the correct solution.

### Link to the related docs page

https://docs.expo.dev/router/installation/

**Comment by amandeepmittal** [comment]
@kevinjanada, I'm unable to reproduce the issue you mentioned. When following the manual steps from the documentation, I create a new project and install dependencies (as mentioned here: https://docs.expo.dev/router/installation/#install-dependencies), the config plugin is automatically added to `app.json`. 

There is also a confirmation message in the CLI:

![CleanShot 2024-02-22 at 13 34 06@2x](https://github.com/expo/expo/assets/10234615/327adbcc-7d21-4f2a-a158-e9ea0cfdb03f)

Installing `expo-router` should add the config plugin on its own if you create your project initially with `npx create-expo-app`.

Can you help me retrace your steps?

**Comment by kevinjanada** [comment]
just tried the install again, and the `expo-router` was indeed added automatically.

My bad, i was messing around with the configs while installing, i was probably unaware that i deleted it myself.
Sorry for false alarm.

Closing this issue
