### ISSUE TITLE
[docs] Video code does not run when copy-pasted

### ISSUE THREAD

**Issue by whyboris** [expo/expo#27237]
### Summary

Go to: https://docs.expo.dev/versions/latest/sdk/video/

Copy the code, try to run it, and your app shows up with nothing except the text "Play" but it is not clickable - nothing works.

When you click on `Open in Snack`  the code includes the following:

```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
  video: {
    alignSelf: 'center',
    width: 320,
    height: 200,
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```

Which is apparently necessary for the app to render the video thumbnail.

🤯  my mind is blown why you would hurt your newbie visitors like this -- they will copy paste the code you have in the documentation, **it will not work** and they will either spend like an hour trying to get it to work or just leave.

**PLEASE INCLUDE THE NECCESSARY CODE SO WHEN YOU COPY / PASTE IT WORKS RIGHT AWAY**

ps - even with the styling included, clicking on the video does not play the video - so I currently gave up trying to get _Expo_ to work until this issue is resolved 😠 

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/video/

### Anything else?

Please remember - many in your audience has no clue how anything works - so if a simple copy/paste from the official documentation page doesn't work, they will leave.

**Comment by ui-mo** [comment]
hey @whyboris  ,the code mentioned in the documentation may be wrong but that does not mean that the whole expo community is not doing anything , the issue everyone is so busy doing their own thing people not get enough time to change the code . Hope the expo community  understand this .

**Comment by alanjhughes** [comment]
Hi @whyboris - I just copied the code directly into a snack and ran on my device without issue. I also copied everything into a new project and it also works. If you manually highlight the code, and copy it yourself, then that won't work. The styles are omitted for brevity, that's why the copy functionality is there.

**Comment by amandeepmittal** [comment]
Hi again @whyboris, we've improved how we render large code snippets in our docs (especially, in API references) and include complete code snippets. A single click to the "Copy" button or manually copying the code from the code block should work.

Here's a short video demo about this improvement:

https://github.com/expo/expo/assets/10234615/fda56ace-b8b6-4b0b-87fe-ea4168fa8ec9

If you are still unable to run the Video example from the Usage section, please share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a new issue.

Closing this issue as the subject matter of it was around code blocks in our docs.
