### ISSUE TITLE
The experience you requested is not viable by you. You will need to log in or ask the owner to grant you access.

### ISSUE THREAD

**Issue by adnxy** [expo/expo#2724]
I have pushed and published my IOS app to Expo using CLI and got my link for hosting. When I try to open the app, everything is ok.

When others try to open an app from the expo site, they get this error:

The experience you requested is not viable by you. You will need to log in or ask the owner to grant you access.

Problem is that user is already logged in with Expo app on IOS.

My project is public and here is my app.json:

```
{
  "expo": {
    "name": "Workout",
    "description": "Simple react native developer playground app",
    "slug": "ExpoClinicQr",
    "privacy": "public",
    "sdkVersion": "31.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  },
  "infoPlist": {
    "NSCameraUsageDescription": "This app uses the camera to scan barcodes."
  }
}
```

**Comment by sjchmiela** [comment]
This is caused by a limitation we had to put on Expo Client to match Apple Review Guidelines. Read more about it here — [Upcoming Limitations to iOS Expo Client – Exposition](https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a). Unfortunately we can't do much about it. 😞

**Comment by Enalmada** [comment]
@sjchmiela The error message says "You will need to log in or ask the owner to grant you access."  I have shared my expo url with users that want to test my app.  They have logged in with their own accounts and still get the error so now they are asking for "the owner to grant them access".  How does the owner grant another user access?

**Comment by sjchmiela** [comment]
Hey, @Enalmada! You've got a very good intuition—the message suggests that the author of an experience could allow access to the experience to other users. This error message has been changed quite recently, in https://github.com/expo/expo/commit/9a7f140a30412c326c26c8cedfba484f4d45526e.

This commit anticipates some changes we are currently implementing, discussed at length in [Expo for Professionals](https://blog.expo.io/expo-for-professionals-218b7937fafb) blog post, one of which is “Team accounts”. This feature isn't ready yet, but once it will be, the error message will make much more sense. (Which shouldn't bee that far in the future.)

Thank you for the comment! 🙂

**Comment by Enalmada** [comment]
I urge you change your error message to reflect the current behavior and functionality of the app.   It is totally unacceptable to have an error message offering solutions that you know won't work.  You need to flat out state in the error message something like this..."The experience you requested is only visible to the author. Please login as the author or read this link for further information"

**Comment by 0x80** [comment]
@Enalmada 	I totally agree. As a first time Expo user I wasted quite a bit of my (and my clients) time trying to share the project. It is really not clear from the interface and error messages what the current limitations are for iOS.

**Comment by jasdeepsingh** [comment]
I also strongly suggest that if users visit or open these QR codes from iOS devices they be given some sort of error message that lets them know they can view the app/(experience?) in Android only.

![image](https://user-images.githubusercontent.com/603900/52979234-b4a5e400-33a2-11e9-804c-8510cf16c361.png)

Because these links are not working on iOS at all.

**Comment by juliofalbo** [comment]
There is a workaround to resolve this.

Create an account that you can share login and password with your clients and publish your app in this account.

It's not the best solution, but in critical moments (my case) solves your problem!

When you logged in into a account who is owner of app, the Expo Client for iOs open the app perfectly!
