### ISSUE TITLE
A notification forces a full reload of JS bundle on Android

### ISSUE THREAD

**Issue by marecikl** [expo/expo#27240]
### Summary

I have an Android app in a development mode, built with Expo 50 and its new default flag "launchModeExperimental": "most-recent". If my app works in foreground, receives a notification (with expo-notifications lib) and a user clicks the popup, then the JS bundle is fully reloaded.

This situation does not occur with Expo 49 or a non-development mode or if I change the flag "launchModeExperimental" to "launcher".

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

The newest versions of expo, expo-dev-client, expo-notifications:

expo: 50.0.7
expo-dev-client: 3.3.8
expo-notifications: 0.27.6

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    npmPackages:
      expo: ^50.0.0 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

### Reproducible demo

none

**Comment by Knaackee** [comment]
Hey @marecikl 👋

Did you found a solution?

**Comment by marecikl** [comment]
> This situation does not occur with Expo 49 or a non-development mode or if I change the flag "launchModeExperimental" to "launcher".

I disabled a new launch feature with:

`
   [
        "expo-dev-launcher",
        {
          "launchModeExperimental": "launcher"
        }
      ]
`

added to "plugins" list of app.json.
