### ISSUE TITLE
Expo router status bar doesn't respect the theme

### ISSUE THREAD

**Issue by risoni** [expo/expo#27278]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/templates/expo-template-tabs

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I'm running `expo-template-tabs` without any changes using Expo Go on Android but the status bar and gesture bar don't work correctly. When light mode is selected, the status bar is light when it should be dark and the gesture bar is dark when it should be white. When dark mode is enabled, the bars looks the same, that is, the status bar is light and the gesture bar is dark. Using `StatusBar` doesn't change anything.

<img src="https://github.com/expo/expo/assets/80122270/eb2c9420-54e8-4631-874e-ed25919ccd97" alt="Screenshot_20240224-225528" width="250" />
<img src="https://github.com/expo/expo/assets/80122270/45917341-82d8-4866-a046-89ebc2326515" alt="Screenshot_20240224-225609" width="250" />

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ~50.0.7 => 50.0.7
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
I cannot replicate this issue, so it may be device specific. I've tested in the simulator and on physical devices.

There's a number of reasons why this could have occurred in your environment, such as
- unusual device
- simulator is in an usual state (I've experienced this before, resetting the device fixed the issue for me)
- mismatched `node_modules`

I'm going to close this issue as it appears you have a fix. But if you can provide any more information that we can use to reliably replicate the issue (e.g simulator version/setttings/etc) then I can reopen.

**Comment by ed-cscosta** [comment]
I have the same problem with the first code, but with the second code it works. I have the problem in IOS and Android.

```typescript
export default function RootLayout() {
  useEffect(() => {
    SplashScreen.hideAsync();
  }, []);

  return <RootLayoutNav />;
}

function RootLayoutNav() {
  const colorScheme = useColorScheme();
  const [theme, setTheme] = useState<'light' | 'dark'>('dark');

  return (
    <ThemeProvider value={colorScheme === 'dark' ? DarkTheme : DefaultTheme}>
      <StatusBar style={theme} animated />
      <SafeAreaView>
        <Pressable
          onPress={() => {
            setTheme((prev) => (prev === 'dark' ? 'light' : 'dark'));
          }}
        >
          <Text>Changee Theme</Text>
        </Pressable>
        <View
          style={
            theme === 'light'
              ? { backgroundColor: 'red' }
              : { backgroundColor: 'purple' }
          }
        >
          <Text>
            {colorScheme}-{theme}
          </Text>
        </View>
      </SafeAreaView>
    </ThemeProvider>
  );
}
```

```typescript
export default function RootLayout() {
  const [loaded, error] = useFonts({
    SpaceMono: require('@/assets/fonts/SpaceMono-Regular.ttf'),
    ...FontAwesome.font,
  });

  //Expo Router uses Error Boundaries to catch errors in the navigation tree.
  useEffect(() => {
    if (error) throw error;
  }, [error]);

  useEffect(() => {
    SplashScreen.hideAsync();
  }, []);

  if (!loaded) {
    console.log('not loaded');
    return null;
  }

  return <RootLayoutNav />;
}

function RootLayoutNav() {
  const colorScheme = useColorScheme();
  const [theme, setTheme] = useState<'light' | 'dark'>('dark');

  return (
    <ThemeProvider value={colorScheme === 'dark' ? DarkTheme : DefaultTheme}>
      <StatusBar style={theme} animated />
      <SafeAreaView>
        <Pressable
          onPress={() => {
            setTheme((prev) => (prev === 'dark' ? 'light' : 'dark'));
          }}
        >
          <Text>Changee Theme</Text>
        </Pressable>
        <View
          style={
            theme === 'light'
              ? { backgroundColor: 'red' }
              : { backgroundColor: 'purple' }
          }
        >
          <Text>
            {colorScheme}-{theme}
          </Text>
        </View>
      </SafeAreaView>
    </ThemeProvider>
  );
}
´´´
