### ISSUE TITLE
state no updating in layout route when using Jotai

### ISSUE THREAD

**Issue by BubbleTrouble14** [expo/expo#27276]
### Minimal reproducible example

https://github.com/BubbleTrouble14/ExpoRouterBug

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I followed the authentication example for expo router, but instead of using react context I want to use jotai as my state management library. But for some reason the count atom only causes a re-render in the root layout and in the oboarding screen itself. But not inside the "app./(apps)/_layout" route which checks if the count changes and then should render the index.ts route. Not sure if I am just missing something here, but look multiple times and dont think I am doing anything incorrectly.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /var/folders/zf/tp2yq1lx7qq46q7pdmwlp5kh0000gn/T/yarn--1708810583392-0.6709411875114404/node
      Yarn: 1.22.19 - /var/folders/zf/tp2yq1lx7qq46q7pdmwlp5kh0000gn/T/yarn--1708810583392-0.6709411875114404/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        Android NDK: 23.1.7779620
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.7 => 50.0.7 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: bare

**Comment by marklawlor** [comment]
React Navigation wraps each screen in `memo()`, so they will not re-render because the parent re-rendered.

The pattern you are using here isn't a good fit for navigation. The navigation history should be the source of truth of the current screen (not Jotai).  You should use `router.replace(<URL>)` to change the currently viewed screen.

**Comment by BubbleTrouble14** [comment]
> React Navigation wraps each screen in `memo()`, so they will not re-render because the parent re-rendered.
> 
> The pattern you are using here isn't a good fit for navigation. The navigation history should be the source of truth of the current screen (not Jotai). You should use `router.replace(<URL>)` to change the currently viewed screen.

Makes sense. Thanks for the clarification!

**Comment by louisnw01** [comment]
> React Navigation wraps each screen in `memo()`, so they will not re-render because the parent re-rendered.
> 
> The pattern you are using here isn't a good fit for navigation. The navigation history should be the source of truth of the current screen (not Jotai). You should use `router.replace(<URL>)` to change the currently viewed screen.

Thanks @marklawlor; do you have any recommendations of a replacement for Jotai/state manager?
