### ISSUE TITLE
Enable inline requires by default

### ISSUE THREAD

**Issue by rickhanlonii** [expo/expo#27279]
### Summary

Inline requires in React Native have been [enabled by default since 0.64](https://reactnative.dev/blog/2021/03/12/version-0.64#inline-requires-enabled-by-default) (March 2021), and they are enabled by default in the default Metro config, but the [default Expo config](https://github.com/expo/expo/blob/main/packages/%40expo/metro-config/build/ExpoMetroConfig.js#L226) still has them off by default. This is [confusing to React Native users](https://x.com/dan_abramov2/status/1761508553712407033?s=20) who use Expo for React Native.

Notably, there also don't seem to be any Expo docs with instructions on how to turn them on, and there are no React Native docs because they're "on by default".

### Link to the related docs page

https://docs.expo.dev/versions/latest/config/metro/

**Comment by brentvatne** [comment]
we tried to do this and reverted: https://github.com/expo/expo/pull/25680

> The inline requires feature doesn't work as-is because it does not respect module side-effects. Due to the way inline requires is computed in the transformer, it has no ability to determine if a module should be automatically skipped to prevent breaking the expected order of instantiation.

@EvanBacon - does something need to change in the implementation of inline requires for us to be comfortable with adopting it by default, or do we need to change our own code with side effects?

**Comment by rickhanlonii** [comment]
I think the missing piece context is that if your modules have side-effects, then they will break anyway when you move them to dynamic imports like with React.lazy or when they're executed only on the server like RSC (especially for shared imports). So we really shouldn't support them at the bundler level except to maybe block them entirely. See [thread](https://x.com/dan_abramov2/status/1761529723241304462?s=20) here.

Since the rest of the RN ecosystem has already converted to inlines by default, libraries would need to have been updated to support this in order to run in both Expo and non-Expo apps. Because of this, I'm skeptical that this is a real issue in practice (outside if Expo core, and if that's the case you'd need to remove the side effects for RSC support anyway).

**Comment by EvanBacon** [comment]
@rickhanlonii moving code behind a function that indicates it will be bundle split or loaded asynchronously (such as `React.lazy` or `await import()`) is a well-defined system that will reasonably and consistently change the behavior of side-effects. 

Metro's current implementation of inline requires does not work in an expected way because you lose control of module execution. This is akin to how `var` hoisting caused JavaScript to execute in unexpected ways and throw unexpected errors. 

I'm in favor of Metro updating the inline requires behavior such that any module that depends on a side-effect is left in-place to ensure execution order remains generally consistent. Until this is the case, I think that users should opt-in to the behavior so they can familiarize themselves with the other inlineRequire options that disable the feature on a per-module basis.

> you'd need to remove the side effects for RSC support anyway

My understanding is that React doesn't explicitly indicate how client boundaries should be bundled for production environments, so I'm not familiar with any rule that states side-effects cannot be supported within the context of a client boundary.

If a client boundary pulls in a library that depends on some globally polyfilled function, then the polyfill will still need to be instantiated in that boundary in an expected order.

**Comment by EvanBacon** [comment]
For those with access to the discord, here are some relevant reports about issues with inlineRequires:
- https://discord.com/channels/514829729862516747/1179589502524723270/1179763101948715131
- https://discord.com/channels/514829729862516747/514832110595604510/1179859550552211476

For those who don't—It's reported that inlineRequires are applied at unexpected times which can cause the execution order of code to change based on the import syntax used.

It was also noted that inlineRequires could potentially be easier to work with if they were only applied to user code (not node modules), this wouldn't be possible without forking the Metro transformer or exposing additional options in Metro.

**Comment by rickhanlonii** [comment]
@EvanBacon the issue there seems to be that default or wildcard imports don't get inlined, which is a different problem from losing control of module execution right? The former is something that should get fixed in the transform (and a fix was linked), the later is more of a fundamental limitation. Do you have examples of the module execution being broken?

> My understanding is that React doesn't explicitly indicate how client boundaries should be bundled for production environments, so I'm not familiar with any rule that states side-effects cannot be supported within the context of a client boundary.

If a module is imported from a server component (either as a server-only module, or a shared component which is where this is more relevant because it impacts importing existing code) and there are side effects, then the behavior is indeterminate. If that module uses client globals as side-effects, then it can be broken in subtle ways. It also doesn't even really make sense to have side effects since it's single render, single request, not setting up an environment like on the client.

**Comment by rickhanlonii** [comment]
> I think that users should opt-in to the behavior so they can familiarize themselves with the other inlineRequire options that disable the feature on a per-module basis.

Just noting that this was the case for a couple of years. The benefits of inline requires was attractive enough for most of the community to migrate to support it, at which point the CLI was upgraded to use it by default, with an option to opt-out. If this was a new decision, I'd probably agree that it should be better designed. But given the context that libraries should have mostly migrated to support it already, I don't see the practical concern with enabling it by default.

**Comment by rickhanlonii** [comment]
Like, the bluesky app, with [200+ dependencies](https://github.com/bluesky-social/social-app/blob/main/package.json#L46) including 20+ expo libraries just flipped the flag to true and it worked. That's huge signal to me that it's safe in practice.

**Comment by rickhanlonii** [comment]
## Update
I had a chance to sync with @motiz88 and @robhogan from the Metro team. It turns out my information was out of date here. While I was on parental leave last year, we were able to identify some blockers to rolling this out further until we address them. 

I want to summarize the current problem of inline requires, why it doesn't make sense to change the defaults in either RN or Expo, and what we can do to document the current state instead.

## The problems 
There a are two main problems with inline-requires today.

### We don't have full support to inline import/export

One big problem is that the current transform doesn't inline default or wildcard import/exports. 

For example, the transform will change named imports from:

```js
import {foo} from './bar';
function baz() { foo(); }
```

to

```js
function baz() { require('./bar').foo(); }
```
But for default exports, the babel will change default exports to call `_interopRequireDefault`. Since that's an inline function call, the inline requires transform can only inline the require to the `_interopRequireDefault` function call at the model level, breaking the lining. 

That means, if you import the default export, the transform will change the imports from:

```js
import foo from './bar';
function baz() { foo(); }
```

to

```js
const foo = _interopRequireDefault(require('./bar'));
function baz() { foo(); }
```

This is problematic because a) you lose the benefit of the inline requires since they're not inlined and b) changing a named export to a default export will suddenly change the module execution order in a way that's opaque to users. If something breaks only after you've changed the type of import, it's not clear how or why changing the import type broke your app.

## We don't intelligently detect side effects in modules

The current inline requires transform simply transforms every require to be inline (with some common modules like React skipped to reduce bundle size). This is a problem because there's currently no restriction of module side effects being applied. So while module side effects may be a bad idea (for the reasons I listed above), people can still do them and there's nothing that catches it. 

One way to solve this is by adding a `sideEffect` setting like [webpack](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) has. The trouble with that, is that's it's an opt-in setting, which would reduce the benefit of inline-requires until the ecosystem updates the setting. What we need is something like what @EvanBacon said, which is a way to detect side effects so that any module that depends on a side-effect is left in-place to ensure execution order remains generally consistent, but that doesn't exist today.

Another solution is for users to opt-into to lazy loading subgraphs of the module tree using dynamic imports, and React.lazy. This works today, is supported across platforms and bundlers, integrates into suspense, works with RCS, and gives the user more control of the 'boundaries' of when modules are executed.

## The defaults
Given these problems, what should we do about the defaults?

## Why not change the default in RN?

In hindsight, it was probably the wrong move to enable inline requires by default in RN, but changing the default back now would be a breaking change. Going from inline-requires back to no-inlining is much risker than going the other way, and would be a performance regression for apps inline-requires are already working in.

So we'll keep the inline require default in place until we're able address the problems above.

## Why not enable inline-requires by in Expo?

Despite the problems above, it's still the case that many apps can enable inline requires and see huge startup wins, so the question is why not enable it by default in Expo. 

The Metro team has a few ideas for how they can improve the transform, but no matter what the fix is, it might have breaking changes when switching from inline-requires to a new type of optimization. Because of this, we're recommending that Expo does not enable inline requires by default, so that Expo apps will be able to take advantage of a more intelligent optimization in the future with minimal breaking changes.

## What now 

So for now, we're going to be in a state where the metro config defaults to `inlineReqires: true` and Expo defaults to `inlineRequires: false`. This is somewhat confusing for users, but I think we can address this with better docs and an explanation of tradeoffs.

### Recommending lazy loading

An additional insight here that @EvanBacon, @motiz88, and @robhogan shared is that the safe and idiomatic way to defer loading modules during initialization is to use dynamic `import()` and `React.lazy()`. Metro actually added support for this last year, and it works with Suspense for React components.

This allows user to opt-in to deferring modules on a per-module level, which is more control than a blanket transform, and is future compatible with React features like RSCs. We're going to add docs for this on the React Native site that the Expo docs can link to.

### Update the React Native docs for inline-requires

We're also going to update the React Native docs to add a section than explains the state of inline requires in React Native, the issues that you may see, the tradeoffs, and how to turn them off if needed. This section will also explain how frameworks like Expo may not have this setting on by default due to these tradeoffs. 

### Update the Expo docs inline-requires

The new ask here is to update the Expo docs to explain that `inlineRequires` are off by default. Since it is possible for large apps to see big performance wins by enabling inline requires, like the bluesky case, the docs should also include instructions for enabling them, along with information on the tradeoffs (or linking to the RN docs about the tradeoffs) and recommending using dynamic imports and React.lazy().

**Comment by brentvatne** [comment]
@rickhanlonii - thanks for the comprehensive summary! we can definitely follow up with better docs. let us know when the react-native docs around this are ready and we'll ensure we provide similar guidance contextualized to expo users

**Comment by motiz88** [comment]
The new docs page is up and will be part of the docs cut for 0.74: https://reactnative.dev/docs/next/optimizing-javascript-loading. Old links to the "inline requires" page should redirect to this new one once we deploy the 0.74 docs.

There's a specific mention of Expo [here](https://reactnative.dev/docs/next/optimizing-javascript-loading#:~:text=In%20particular%2C%20in-,Expo,-projects%2C%20require). Eventually I want that paragraph to link directly to the Expo docs, e.g.:

> Some React Native frameworks disable this behavior. In particular, in Expo projects, `require` calls are not inlined by default. You can enable this optimization by [following these instructions from Expo](.).
