### ISSUE TITLE
iOS: Adding reanimated with expo using new arch make the app crash

### ISSUE THREAD

**Issue by laurentlubino** [expo/expo#27271]
### Minimal reproducible example

https://github.com/laurentlubino/test-reanimated

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Using the new architecture and adding reanimated make the app unable to boot.

The app i'm developing is not crashing after loading the bundle when reanimated has been installed. (I could give you access to the real app as well)
The reproduction doesn't work as well, slightly differently, but still not working, following those steps:
- `npx create-expo-app@latest -e with-new-arch1`
- `npx expo install react-native-reanimated`
- `yarn ios`

On my app I have this issue when building:
```
duplicate symbol '__ZN8facebook5react12CoreFeatures14useNativeStateE' in
┌─ libRNReanimated.a[12](NativeReanimatedModule.o)
└─ libReact-utils.a[2](CoreFeatures.o)
```

On my the reproduction test I got this warning when building iOS:
```
ld: duplicate symbol 'facebook::react::CoreFeatures::useNativeState' in
┌─ libRNReanimated.a(NativeReanimatedModule.o)
└─ libReact-utils.a(CoreFeatures.o)
```

Adding the different error I'm getting:
My App error screen: 
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-24 at 19 18 08](https://github.com/expo/expo/assets/88761770/045bc60e-9e93-49a0-92ec-f42329595272)

Reproduction error screen:
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-24 at 19 28 59](https://github.com/expo/expo/assets/88761770/7abf2000-ce0a-4ccd-9dbe-a87fa482cf8d)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 10.2.3 - ~/n/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 29, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.1 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      eas-cli: 3.11.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

The following packages should be updated for best compatibility with the installed expo version:
  react-native@0.73.2 - expected version: 0.73.4
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies

**Comment by brentvatne** [comment]
hi there! the reanimated team is working on better new architecture support. we're hoping that react-native 0.74 will be the first release that will have good support for a broad set of community packages like reanimated and more. i'll close this issue because support for the new arch is being tracked on the reanimated repo itself and being worked on actively by @WoLewicki

**Comment by laurentlubino** [comment]
I'm mentioning it here because it works on bare react native with rn version "0.73.2" so I thought it might be an expo issue.
I think I did read that the 0.51 would aim for those improvement, is there a way to track the release?
