### ISSUE TITLE
eas build failed both iOS and Android after upgrading to v50

### ISSUE THREAD

**Issue by kdong007** [expo/expo#27286]
### Minimal reproducible example

private repo

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

we just upgraded to expo V50. but eas build failed for both iOS and Android.

iOS log
```
Creating Gymfile
Gymfile created
Successfully loaded '/Users/expo/workingdir/build/ios/Gymfile' 📄
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                  Detected Values from './Gymfile'                                                                   |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| suppress_xcode_output | true                                                                                                                                        |
| clean                 | false                                                                                                                                       |
| scheme                | VideoMatch                                                                                                                                  |
| configuration         | Release                                                                                                                                     |
| export_options        |                                                                                                                                             |
| export_xcargs         | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/p2/2788nfhd7xq3pnnk81v00sf00000gn/T/turtle-v2-31c7961b-6bd5-47fe-8c91-21efccd21bc8.keychain" |
| disable_xcpretty      | true                                                                                                                                        |
| buildlog_path         | /Users/expo/workingdir/logs                                                                                                                 |
| output_directory      | ./build                                                                                                                                     |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
Resolving Swift Package Manager dependencies...
$ xcodebuild -resolvePackageDependencies -workspace ./VideoMatch.xcworkspace -scheme VideoMatch -configuration Release
▸ Command line invocation:
▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./VideoMatch.xcworkspace -scheme VideoMatch -configuration Release
▸ User defaults from command line:
▸     IDEPackageSupportUseBuiltinSCM = YES
▸ resolved source packages:
$ xcodebuild -showBuildSettings -workspace ./VideoMatch.xcworkspace -scheme VideoMatch -configuration Release 2>&1
Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
Detected provisioning profile mapping: {:"com.videomatch.mobile"=>"ba9abcc0-7d6b-4d09-b69c-c49788615680"}

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                         Summary for gym 2.219.0                                                                                         |
+-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| workspace                                                 | ./VideoMatch.xcworkspace                                                                                                                    |
| scheme                                                    | VideoMatch                                                                                                                                  |
| clean                                                     | false                                                                                                                                       |
| output_directory                                          | ./build                                                                                                                                     |
| output_name                                               | VideoMatch                                                                                                                                  |
| configuration                                             | Release                                                                                                                                     |
| silent                                                    | false                                                                                                                                       |
| skip_package_ipa                                          | false                                                                                                                                       |
| skip_package_pkg                                          | false                                                                                                                                       |
| export_options.method                                     | app-store                                                                                                                                   |
| export_options.provisioningProfiles.com.videomatch.mobile | ba9abcc0-7d6b-4d09-b69c-c49788615680                                                                                                        |
| export_xcargs                                             | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/p2/2788nfhd7xq3pnnk81v00sf00000gn/T/turtle-v2-31c7961b-6bd5-47fe-8c91-21efccd21bc8.keychain" |
| build_path                                                | /Users/expo/Library/Developer/Xcode/Archives/2024-02-25                                                                                     |
| result_bundle                                             | false                                                                                                                                       |
| buildlog_path                                             | /Users/expo/workingdir/logs                                                                                                                 |
| destination                                               | generic/platform=iOS                                                                                                                        |
| suppress_xcode_output                                     | true                                                                                                                                        |
| xcodebuild_formatter                                      | xcpretty                                                                                                                                    |
| build_timing_summary                                      | false                                                                                                                                       |
| disable_xcpretty                                          | true                                                                                                                                        |
| skip_profile_detection                                    | false                                                                                                                                       |
| xcodebuild_command                                        | xcodebuild                                                                                                                                  |
| skip_package_dependencies_resolution                      | false                                                                                                                                       |
| disable_package_automatic_updates                         | false                                                                                                                                       |
| use_system_scm                                            | false                                                                                                                                       |
| xcode_path                                                | /Applications/Xcode.app                                                                                                                     |
+-----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
$ set -o pipefail && xcodebuild -workspace ./VideoMatch.xcworkspace -scheme VideoMatch -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/expo/Library/Developer/Xcode/Archives/2024-02-25/VideoMatch\ 2024-02-25\ 22.06.26.xcarchive archive | tee /Users/expo/workingdir/logs/VideoMatch-VideoMatch.log > /dev/null
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » VideoMatch/VideoMatch » Build Phases » '[CP-User] [RNFB] Core Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » VideoMatch/VideoMatch » Build Phases » '[CP-User] [RNFB] Crashlytics Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

▸ ** ARCHIVE FAILED **
** ARCHIVE FAILED **
Exit status: 65

+---------------------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.219.0                 |
| sdk         | iPhoneOS17.2.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[!] Error building the application - see the log above
Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.```


Android log (last 300 lines)
```
Writing bundle output to: /home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
Writing sourcemap output to: /home/expo/workingdir/build/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
Copying 51 asset files
Done writing bundle output
Done writing sourcemap output
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:3430:16: warning: the variable "SharedArrayBuffer" was not declared in function "from"
    if (typeof SharedArrayBuffer !== 'undefined' && (isInstance(value, Shared...
               ^~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:8213:18: warning: the variable "DebuggerInternal" was not declared in function "__shouldPauseOnThrow"
          typeof DebuggerInternal !== 'undefined' &&
                 ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:19035:7: warning: the variable "setTimeout" was not declared in function "logCapturedError"
      setTimeout(function () {
      ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:16995:108: warning: the variable "nativeFabricUIManager" was not declared in function "onChange"
...lInstanceHandle ? (from && nativeFabricUIManager.setIsJSResponder(from.sta...
                              ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:17616:21: warning: the variable "clearTimeout" was not declared in anonymous function " 345#"
    cancelTimeout = clearTimeout;
                    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:21366:30: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in anonymous function " 345#"
  if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:22915:5: warning: the variable "setImmediate" was not declared in function "handleResolved"
    setImmediate(function () {
    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:26934:5: warning: the variable "fetch" was not declared in anonymous function " 558#"
    fetch,
    ^~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:26935:5: warning: the variable "Headers" was not declared in anonymous function " 558#"
    Headers,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:26936:5: warning: the variable "Request" was not declared in anonymous function " 558#"
    Request,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:26937:5: warning: the variable "Response" was not declared in anonymous function " 558#"
    Response
    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27087:24: warning: the variable "FileReader" was not declared in function "readBlobAsArrayBuffer"
      var reader = new FileReader();
                       ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27134:36: warning: the variable "Blob" was not declared in anonymous function " 569#"
        } else if (support.blob && Blob.prototype.isPrototypeOf(body)) {
                                   ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27136:40: warning: the variable "FormData" was not declared in anonymous function " 569#"
        } else if (support.formData && FormData.prototype.isPrototypeOf(body)) {
                                       ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27138:44: warning: the variable "URLSearchParams" was not declared in anonymous function " 569#"
...e if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body...
                                 ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27376:23: warning: the variable "XMLHttpRequest" was not declared in anonymous function " 578#"
        var xhr = new XMLHttpRequest();
                      ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:26946:76: warning: the variable "self" was not declared in anonymous function " 561#"
...undefined' && globalThis || typeof self !== 'undefined' && self || typeof ...
                                      ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:31633:27: warning: the variable "performance" was not declared in anonymous function " 751#"
  if ("object" === typeof performance && "function" === typeof performance.no...
                          ^~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:31656:26: warning: the variable "navigator" was not declared in anonymous function " 751#"
  "undefined" !== typeof navigator && undefined !== navigator.scheduling && u...
                         ^~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:31766:37: warning: the variable "MessageChannel" was not declared in anonymous function " 751#"
  };else if ("undefined" !== typeof MessageChannel) {
^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:31781:34: warning: the variable "nativeRuntimeScheduler" was not declared in anonymous function " 751#"
... = "undefined" !== typeof nativeRuntimeScheduler ? nativeRuntimeScheduler....
^~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:43775:34: warning: the variable "requestAnimationFrame" was not declared in function "start 9#"
...    this._animationFrame = requestAnimationFrame(this.onUpdate.bind(this));
                              ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:65852:19: warning: the variable "_getAnimationTimestamp" was not declared in function "handleAndFlushAnimationFrame 1#"
        var now = _getAnimationTimestamp();
                  ^~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:66232:100: warning: the variable "location" was not declared in function "registerSensor 1#"
...(0, _PlatformChecker.isWeb)() && location.protocol !== 'https:' ? ' Make s...
                                    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:66873:26: warning: Direct call to eval(), but lexical scope is not supported.
            workletFun = eval('(' + initData.code + '\n)');
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:67185:20: warning: the variable "_makeShareableClone" was not declared in function "cloneRecursive"
            return _makeShareableClone(value);
                   ^~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:67618:11: warning: the variable "queueMicrotask" was not declared in anonymous function " 1661#"
          queueMicrotask(function () {
          ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:67717:33: warning: the variable "_WORKLET" was not declared in function "runOnJS"
      if (SHOULD_BE_USE_WEB || !_WORKLET) {
                                ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:67750:9: warning: the variable "_scheduleOnJS" was not declared in anonymous function " 1673#"
        _scheduleOnJS(fun, args.length > 0 ?
        ^~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:67948:13: warning: the variable "_updateDataSynchronously" was not declared in function "set _value 1#"
            _updateDataSynchronously(syncDataHolder, (0, _shareables.makeShar...
            ^~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:68501:18: warning: the variable "_scheduleOnRuntime" was not declared in anonymous function " 1700#"
          return _scheduleOnRuntime(workletRuntime, (0, _shareables.makeShare...
                 ^~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:68561:9: warning: the variable "_notifyAboutProgress" was not declared in anonymous function " 1706#"
        _notifyAboutProgress(tag, sharedValue.value, isSharedTransition);
        ^~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:68579:7: warning: the variable "_notifyAboutEnd" was not declared in function "stopObservingProgress"
      _notifyAboutEnd(tag, removeView);
      ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:81477:7: warning: the variable "_removeFromPropsRegistry" was not declared in function "removeFromPropsRegistryOnUI"
      _removeFromPropsRegistry(viewTags);
      ^~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:82223:11: warning: the variable "_updatePropsFabric" was not declared in function "flush 1#"
          _updatePropsFabric(operations);
          ^~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:82252:11: warning: the variable "_updatePropsPaper" was not declared in function "flush 2#"
          _updatePropsPaper(operations);
          ^~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:85705:7: warning: the variable "_dispatchCommandFabric" was not declared in function "dispatchCommandFabric"
      _dispatchCommandFabric(shadowNodeWrapper, commandName, args);
      ^~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:85723:7: warning: the variable "_dispatchCommandPaper" was not declared in function "dispatchCommandPaper"
      _dispatchCommandPaper(viewTag, commandName, args);
      ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:85796:22: warning: the variable "_measureFabric" was not declared in function "measureFabric"
var measured = _measureFabric(viewTag);
                     ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:85830:22: warning: the variable "_measurePaper" was not declared in function "measurePaper"
      var measured = _measurePaper(viewTag);
                     ^~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:85921:7: warning: the variable "_scrollToPaper" was not declared in function "scrollToPaper"
      _scrollToPaper(viewTag, x, y, animated);
      ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:85970:7: warning: the variable "_setGestureState" was not declared in function "setGestureStateNative"
      _setGestureState(handlerTag, newState);
      ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:86263:18: warning: the variable "message" was not declared in function "message"
          return message;
                 ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:86295:5: warning: the variable "jest" was not declared in function "beforeTest"
    jest.useFakeTimers();
    ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:88565:26: warning: the variable "structuredClone" was not declared in function "createAnimationWithExistingTransform"
      newAnimationData = structuredClone(_config.AnimationsData[animationName]);
                         ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:88752:9: warning: the variable "document" was not declared in function "configureWebLayoutAnimations"
    if (document.getElementById(WEB_ANIMATIONS_ID) !== null) {
        ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:110061:30: warning: the variable "AbortController" was not declared in function "get signal"
            controller = new AbortController();
                             ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:135592:76: warning: the variable "Buffer" was not declared in function "convertValue"
... 'function' ? new Blob([value]) : Buffer.from(value);
                                     ^~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:136808:56: warning: the variable "btoa" was not declared in function "dispatchXhrRequest"
...rs.set('Authorization', 'Basic ' + btoa(username + ':' + password));
                                      ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:144915:25: warning: the variable "Atomics" was not declared in anonymous function " 4221#"
    '%Atomics%': typeof Atomics === 'undefined' ? undefined : Atomics,
                        ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:144932:38: warning: the variable "FinalizationRegistry" was not declared in anonymous function " 4221#"
...lizationRegistry%': typeof FinalizationRegistry === 'undefined' ? undefine...
                              ^~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:144971:25: warning: the variable "WeakRef" was not declared in anonymous function " 4221#"
    '%WeakRef%': typeof WeakRef === 'undefined' ? undefined : WeakRef,
                        ^~~~~~~
ASM Instrumentation process wasn't able to resolve some classes, this means that
the instrumented classes might contain corrupt stack frames. Make sure the
dependencies that contain these classes are on the runtime or the provided
classpath. Otherwise, the jvm might fail to load the corrupt classes at runtime
when running in a jvm environment like unit tests.
Classes that weren't resolved:
> com.huawei.hms.ads.installreferrer.api.InstallReferrerClient
> com.samsung.android.sdk.sinstallreferrer.api.InstallReferrerClient
> com.miui.referrer.api.GetAppsReferrerClient
> com.android.billingclient.api.ProductDetails$SubscriptionOfferDetails
> com.android.billingclient.api.ProductDetails$PricingPhases
> com.android.billingclient.api.ProductDetails$OneTimePurchaseOfferDetails
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':config-plugins-react-native-branch:compileReleaseKotlin'.
>
'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 6m 15s
730 actionable tasks: 730 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

### Environment


  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v16.20.2/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.7 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: managed



### Expo Doctor Diagnostics

Running 11 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by michaelpomogajko** [comment]
I'm having the same issue for a couple of weeks now. I could build in eas cloud, but this also started to fail with no apparent reason

**Comment by codexjoshy** [comment]
I'm having same issue, any solution to this. ?

**Comment by kdong007** [comment]
@michaelpomogajko @codexjoshy actually my issue was due to branch-io was still in the old version that was only compatible with expo 49. So double  check your dependencies, expecially the ones with expo plugins

**Comment by abduraufsherkulov** [comment]
```
FAILURE:
Build failed with an exception.
* Where:
Build file '/home/expo/workingdir/build/android/app/build.gradle' line: 1
* What went wrong:
A problem occurred evaluating project ':app'.
>
Failed to apply plugin 'com.android.internal.application'.
>
Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
Your current JDK is located in /usr/lib/jvm/java-11-openjdk-amd64
      You can try some of the following options:
- changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

I am also getting the following error.

**Comment by abduraufsherkulov** [comment]
@michaelpomogajko I am using eas build which means it is being built on expo servers...

**Comment by CamBowes** [comment]
+1 on this

**Comment by hrdyjan1** [comment]
@abduraufsherkulov This image might be suitable for your needs:
https://docs.expo.dev/build-reference/infrastructure/#ubuntu-2204-jdk-17-ndk-r21e-latest-sdk-50

Consider updating your eas.json file with the following:

```
  "android": {
    "image" : "latest"
  }
```

**Comment by kalashovkerim** [comment]
updates?
