### ISSUE TITLE
Expo Video - Video not reproduce in Android SDK 50

### ISSUE THREAD

**Issue by joaolenosi** [expo/expo#27297]
### Minimal reproducible example

https://github.com/joaolenosi/simulate-issue-video-android

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When using the Expo Video component on Android devices, we are encountering an issue where the screen goes blank and the video does not appear during attempts to load certain specific MP4 video files. This problem does not occur with all videos but is present with certain files, completely preventing their playback. No error messages are displayed, just the absence of the video, leaving the user interface without the expected content. This behavior has been observed exclusively in the Android environment, affecting various versions of the operating system and different devices. It is important to note that, on iOS, all videos function correctly, indicating that the problem is isolated to the Android platform.
![8f05d731-5747-4b13-87a6-40f8a3a2d600](https://github.com/expo/expo/assets/13546199/dd5c759d-1a9f-493a-b16d-20d5c174aa8c)
![IMG_4962](https://github.com/expo/expo/assets/13546199/7340d89f-3c40-4b42-876b-bc232f3d17ca)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 21.5.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.1
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~50.0.7 => 50.0.7
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by mbiang** [comment]
For what it's worth, we are experiencing a similar issue on Android.  Videos seemingly just don't render.   The behavior is intermittent.  Sometimes a given video will render, other times it won't.   All load callbacks, etc are firing as expected.

**Comment by lukmccall** [comment]
Hi @joaolenosi! I wasn't able to reproduce this bug. I've tried both: our new package (`expo-video`) and also `expo-av`. Can you try to reproduce the same behavior using `expo-video`? We're going to deprecate the `expo-av` soon, so migration to the new solution is a good idea anyway.

If you are still experiencing the issue, please provide us with the native logs from your device so that we can diagnose the problem.
