### ISSUE TITLE
expo-modules-autolinking is wanted as a peer dependency but is failing expo-doctor

### ISSUE THREAD

**Issue by ChromeQ** [expo/expo#27290]
### Summary

With a new or existing expo app notice there are no warnings with yarn install.
![image](https://github.com/expo/expo/assets/625203/9f312736-4af3-49fc-adf0-2047c074e73b)

Add `expo-splash-screen` as a dependency. Notice the warning about missing peer dependency.
![image](https://github.com/expo/expo/assets/625203/6823235e-fda2-4669-9f81-d11f63155e9b)

Expo doctor is happy so far.
![image](https://github.com/expo/expo/assets/625203/980f8480-78c9-4326-ab1c-73ad708546a5)

Add `expo-modules-autolinking` as a dependency. Notice the warning about missing peer dependency is gone.
![image](https://github.com/expo/expo/assets/625203/c3f4f249-6ad5-4e8c-8b56-143ee54f88c4)

Expo doctor is no longer happy and breaks my CI.
![image](https://github.com/expo/expo/assets/625203/8d73379f-e2ef-4e02-bba2-77a0b1af2f58)

Yes I know I can live with a warning as it doesn't seem to break anything, but it would be nice to get this resolved if possible.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    SDKs:
      Android SDK:
        Android NDK: 26.1.10909125
    npmPackages:
      expo: 50.0.7 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: 0.19.10 => 0.19.10 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

This issue is about expo-doctor showing an error.

**Comment by brentvatne** [comment]
hi there! you can ignore that peer dependency warning and take the advice from `expo-doctor`. the `expo-modules-autolinking` package is automatically installed by the `expo` package, but you see this warning because peer dependencies can't technically be met transitively -- even though, in this particular case, in practice, it will work.

we can likely remove the peer dependency here. perhaps it's worth us re-exporting the expo-modules-autolinking package from the expo package to clean this up, cc @tsapeta

**Comment by ChromeQ** [comment]
Thanks @brentvatne, yes I am aware that I can ignore it, and I will have to continue doing so in this case.
I just thought I would actually read them for once and try to solve them rather than being blind to them as I was going through the effort of updating dependencies for expo 50.
But it would be nice to fix warnings so that there is less noise and avoids the warning blindness many developers accrue.

**Comment by ChromeQ** [comment]
Not stale

**Comment by ChromeQ** [comment]
Not stale

**Comment by ChromeQ** [comment]
Not stale, but I will upgrade to expo SDK 52 soon to check if this is still the case. If it is fixed there then I will close this issue.

**Comment by tsapeta** [comment]
Hey @ChromeQ, I believe #32554 has solved this problem as it removes the peer dependency. I forgot to include this issue in the PR to automatically close it, so let me close it now. Feel free to reopen if this is still the case after upgrading to SDK 52.

**Comment by ChromeQ** [comment]
Amazing, thanks @tsapeta that is good to know, I have not noticed it but it's so easy to ignore the warnings when things still work. Happy for it to be closed.

**Comment by ChromeQ** [comment]
I have upgraded a branch to the latest expo sdk v52 and can confirm it is fixed. Thanks again
