### ISSUE TITLE
expo router does not work in a monrepo

### ISSUE THREAD

**Issue by macrozone** [expo/expo#27299]
### Minimal reproducible example

not yet there

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When using expo router in a monorepo with yarn, you will get the following error on start:

```
error: node_modules/expo-router/_ctx.ios.js: node_modules/expo-router/_ctx.ios.js:Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT
First argument of `require.context` should be a string denoting the directory to require.
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 4.0.1 - ~/.nvm/versions/node/v18.19.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo-router: ~3.4.7 => 3.4.7
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: managed

**Comment by sntlln93** [comment]
Same issue here but it was working yesterday so it's unlikely it's a mono repo related issue but i still don't know what is the problem. The only change I made between yesterday and today was installing React-Query but I doubt it's related.

```bash
Logs for your project will appear below. Press Ctrl+C to exit.
Android Bundling failed 12684ms (apps/client/node_modules/expo-router/entry.js)
error: node_modules/expo-router/_ctx.android.js: node_modules/expo-router/_ctx.android.js:Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT
First argument of `require.context` should be a string denoting the directory to require.
› Reloading apps
Android Bundling failed 6124ms (apps/client/node_modules/expo-router/entry.js)
error: node_modules/expo-router/_ctx.android.js: node_modules/expo-router/_ctx.android.js:Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT
First argument of `require.context` should be a string denoting the directory to require.
```

**Comment by sntlln93** [comment]
> Same issue here but it was working yesterday so it's unlikely it's a mono repo related issue but i still don't know what is the problem. The only change I made between yesterday and today was installing React-Query but I doubt it's related.
> 
> ```shell
> Logs for your project will appear below. Press Ctrl+C to exit.
> Android Bundling failed 12684ms (apps/client/node_modules/expo-router/entry.js)
> error: node_modules/expo-router/_ctx.android.js: node_modules/expo-router/_ctx.android.js:Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT
> First argument of `require.context` should be a string denoting the directory to require.
> › Reloading apps
> Android Bundling failed 6124ms (apps/client/node_modules/expo-router/entry.js)
> error: node_modules/expo-router/_ctx.android.js: node_modules/expo-router/_ctx.android.js:Invalid call at line 2: process.env.EXPO_ROUTER_APP_ROOT
> First argument of `require.context` should be a string denoting the directory to require.
> ```

Downgrading Expo SDK from 50.0.14 to 50.0.13 worked for me.

**Comment by nathan-charles** [comment]
I'm having this same problem after upgrading from expo 50.0.15 -> 50.0.17 had to revert back

**Comment by FedeRBeije** [comment]
Hy guys. Any other idea on how to solve it? i've tried everything but nothing worked.

**Comment by fuelkoy** [comment]
I read through the following issue in expo-router repo [41](https://github.com/expo/router/issues/41). 
I updated my package.json
`"main": "index.js",`
I changed my index.js to be the following
```
import { registerRootComponent } from "expo";
import { ExpoRoot } from "expo-router";

// Must be exported or Fast Refresh won't update the context
export function App() {
	const ctx = require.context("./src/app");
	return <ExpoRoot context={ctx} />;
}

registerRootComponent(App);
```

And I also deleted the .expo folder in the directory. Then starting with -c or building with -c worked

**Comment by brentvatne** [comment]
@fuelkoy @FedeRBeije - can you please create a new issue with a minimal reproducible example? I cannot reproduce. https://stackoverflow.com/help/minimal-reproducible-example
