### ISSUE TITLE
Replace and Redirect doesn't work with new architecture

### ISSUE THREAD

**Issue by patrikduksin** [expo/expo#27309]
### Minimal reproducible example

https://github.com/patrikduksin/expo-router-replace-bug

### Which package manager are you using? (Yarn is recommended)

same bug with bun and npm
### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When I try to use `<Redirect />` component or `router.replace` method instead of getting to right screen I see blank screen. Seems like bug in view controller hierarchy. In terminal I don't see any logs or errors 
<img width="676" alt="image" src="https://github.com/expo/expo/assets/61261093/9ea8a152-39c1-45e0-9da2-150991461eb0">

https://github.com/expo/expo/assets/61261093/d51c6a67-79ee-43e2-916e-d48ed5a9270b 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.local/share/mise/installs/node/lts/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.local/share/mise/installs/node/lts/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/patrikduksin/.local/share/mise/installs/cocoapods/latest/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare

**Comment by marklawlor** [comment]
Are you able to replicate this on iOS & android? Or just iOS?

Can you please reply with your  `package-lock.json` (attach it as a file upload, its too big for a code snippet)

**Comment by patrikduksin** [comment]
Hello @marklawlor, android work as expected. Here is my package-lock.json,
[package-lock.json](https://github.com/expo/expo/files/14422988/package-lock.json)

**Comment by EvanBacon** [comment]
React Native Screens does not support the new architecture yet https://github.com/software-mansion/react-native-screens/pull/2047

**Comment by baumatch-dev** [comment]
Any news about this? I have the same issue with Expo 50.0.8 and RN 0.73.4

**Comment by EvanBacon** [comment]
@WoLewicki while it does technically compile, the implementation appears to be buggy. Issue above doesn't appear fixable inside Expo Router afaict.

**Comment by LucasTrombim** [comment]
Same problem here. I'm using RN 0.72.6 and expo sdk 49.

**Comment by jyling** [comment]
Has this been resolved for expo 50 ?
