### ISSUE TITLE
CLI prints src dir related debug messages to console

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo#27321]
### Minimal reproducible example

https://github.com/philiplindberg/expo-router-cli-repro

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When moving the `app` directory to `src/app` and restarting the dev server, the following message is printed multiple times to the console: `Using src/app as the root directory for Expo Router.` While I can see this as being potentially useful for debugging, the fact that it prints the same message multiple times and for every device running the app quickly becomes distracting.

In the repro, notice how the following gets printed to the console after running `npm start`:
```
> expo-router-cli-repro@1.0.0 start
> expo start

Starting project at /Users/philiplindberg/Code/philiplindberg/expo-router-cli-repro
Starting Metro Bundler
Using src/app as the root directory for Expo Router.
Using src/app as the root directory for Expo Router.
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.14.3 - /Users/philiplindberg/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/pull/27013
