### ISSUE TITLE
Error using React `cache` in Expo API Routes

### ISSUE THREAD

**Issue by ProchaLu** [expo/expo#27320]
### Minimal reproducible example

https://github.com/ProchaLu/expo-cache-repro

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

I encountered an issue while attempting to use the new Expo API Routes with PostgreSQL for a project. Creating a DB query function with `React/cache` throws following error: 
```
Metro error: (0 , _react.cache) is not a function

  3 | import { sql } from './connect';
  4 |
> 5 | export const getUsers = cache(async () => {
    |                              ^
  6 |   const users = await sql<User[]>`
  7 |     SELECT
  8 |       *

Call Stack
  factory (database/users.ts:5:30)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:273:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:180:12)
  _$$_REQUIRE (node_modules/metro-runtime/src/polyfills/require.js:89:7)
  factory (app/login+api.ts:2)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:273:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:180:12)
  metroRequire (node_modules/metro-runtime/src/polyfills/require.js:89:7)
  Object.<anonymous> (http://localhost:8081/app/login+api.bundle)
  Module._compile (node:internal/modules/cjs/loader)
```
### Context

- I'm using the `React/cache` function to cache the results of a database query for improved performance
- The error occurs when attempting to run the application

### Expected Behavior:

The application should successfully execute without any errors related to the cache function from React or Metro.

### Actual Behavior:

Metro throws an error stating `"(0 , _react.cache) is not a function"` when executing the application.

---------------
Working version of the project without `React/cache` 
- https://github.com/ProchaLu/expo-api-routes-postgres

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/opt/node@20/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.7 => 50.0.7 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
can you make the example more minimal? it should include no superfluous code, eg: no database connection, no eslint config, etc. it's best to create a new app and reproduce from scratch

**Comment by ProchaLu** [comment]
@brentvatne, made a [minimal example repro](https://github.com/ProchaLu/expo-cache-repro) 

There is the same error trying to `import { cache } from 'react';`

```
 ERROR  TypeError: 0, _react.cache is not a function (it is undefined)

This error is located at:
    in App (at withDevTools.js:18)
    in withDevTools(App) (at renderApplication.js:57)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:127)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:155)
    in AppContainer (at renderApplication.js:50)
    in main(RootComponent) (at renderApplication.js:67), js engine: hermes
```

<img width="507" alt="Screenshot 2024-02-28 at 16 16 27" src="https://github.com/expo/expo/assets/80746311/ed0e3c08-2ac9-4000-9b10-4cb85140ca17">

**Comment by ProchaLu** [comment]
Updating to either the latest React Canary version `"18.3.0-canary-fb10a2c66-20240228"` or the most recent React Experimental version `"0.0.0-experimental-01ab35a9a-20240228"` did not resolve the encountered error: `ERROR TypeError: 0, _react.cache is not a function (it is undefined)`

**Comment by brentvatne** [comment]
react-native only supports a fixed version of react for each release. if you update to a canary version, you'll also need to update the internal version used by react-native and there is not a publicly documented process for doing this. i would reach out to folks on the react-native team if you have questions about how to do this
