### ISSUE TITLE
Error with `server-only` in Expo API Routes

### ISSUE THREAD

**Issue by ProchaLu** [expo/expo#27322]
### Minimal reproducible example

https://github.com/ProchaLu/expo-server-only

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

I encountered an error when using the `import 'server-only'` in my project using Expo API Routes with PostgreSQL. I created a `database/connect.ts` file using `server-only`, leading to the following error: 
```
Metro error: This module cannot be imported from a Client Component module. It should only be used from a Server Component.

> 1 | throw new Error(
    |       ^
  2 |   "This module cannot be imported from a Client Component module. " +
  3 |     "It should only be used from a Server Component."
  4 | );

Call Stack
  factory (node_modules/server-only/index.js:1:7)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:273:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:180:12)
  _$$_REQUIRE (node_modules/metro-runtime/src/polyfills/require.js:89:7)
  factory (database/connect.ts:1)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:273:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:180:12)
  _$$_REQUIRE (node_modules/metro-runtime/src/polyfills/require.js:89:7)
  factory (database/users.ts:2)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:273:5)
› Reloading apps
Android Bundled 64ms (index.tsx)
```

### Context

- I'm using the `server-only` to identify code that should only be executed on the `server-side` in a React Native application using Expo API Routes with PostgreSQL
- The error occurs when the application attempts to import the `database/connect.ts` file, which is marked as `server-only`, from a client-side component

### Expected Behavior

The application should successfully import and use the `database/connect.ts` file only within `server-side` components

### Actual Behavior

Metro throws an error showing that the `server-only` module cannot be imported from a client component

-------------------
Working version of the project without React/cache

https://github.com/ProchaLu/expo-api-routes-postgres

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/opt/node@20/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by EvanBacon** [comment]
API Routes run in a generic server environment. `server-only` is designed for use in "react-server" environments. 
```json
{
  "name": "server-only",
  "description": "This is a marker package to indicate that a module can only be used in Server Components.",
  "keywords": [
    "react"
  ],
  "version": "0.0.1",
  "homepage": "https://reactjs.org/",
  "bugs": "https://github.com/facebook/react/issues",
  "license": "MIT",
  "files": ["index.js", "empty.js"],
  "main": "index.js",
  "exports": {
    ".": {
      "react-server": "./empty.js",
      "default": "./index.js"
    }
  }
}
``` 

`react-server` will be supported with Server Actions and React Server Components, but not in Node.js environments. Related https://github.com/expo/expo/pull/27264

**Comment by EvanBacon** [comment]
You can work around this issue with postgreSQL by shimming the server-only module to empty, ref https://docs.expo.dev/versions/latest/config/metro/#mocking-modules

```js
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (context.customResolverOptions.environment === 'node' && moduleName === 'server-only') {
    return {
      type: 'empty',
    };
  }

  // Ensure you call the default resolver.
  return context.resolveRequest(context, moduleName, platform);
};
```

**Comment by ProchaLu** [comment]
## Workaround

To fix the error with `server-only`, remove the `import server-only` statement from the top of the file. This will prevent the error from happening.
