### ISSUE TITLE
`eas build` - how to use a different root directory then git repository root (my expo app lives in a subdirectory of git repository, and expo sends too many files).

### ISSUE THREAD

**Issue by GreenTea124** [expo/expo#27338]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by ZackOfAllTrades** [comment]
the issue is the readme https://github.com/expo/fyi/blob/main/eas-build-archive.md should link to reference or describe how to change the project root
