### ISSUE TITLE
Android 14 foreground service permission causes app crash in SDK 50

### ISSUE THREAD

**Issue by alterx** [expo/expo#27336]
### Minimal reproducible example

https://github.com/alterx/foreground-location-expo-50

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

I'm getting this
```
Fatal Exception: java.lang.SecurityException
Starting FGS with type location callerApp=ProcessRecord{6ce728d 8641:xxx.xxxx.xxxxx/u0a382} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION] and the app must be in the eligible state/exemptions to access the foreground only permission
```
error. Our app hasn't changed and the only thing we did was updating to SDK 50. We don't use the foreground location service explicitly, so the only thing I can think of is that Android 14 (SDK34) included some changes that makes it so the app tries to use it underneath?

I've tried blocking the permission and I'm on the latest version of `expo-location` to no avail. Before this, I didn't have any issues without that permission. App was being built and submitted, and worked as expected. 

I created a new build with `requestForegroundPermissionsAsync` and then `getCurrentPositionAsync` so the culprit might be one of the two. 

To reproduce:

In the provided repo, if you checkout the commit 6edb43863c47f8f4f6564dcaeef702cf6ed5c30e (the initial expo commit) and create an android apk everything works as expected. As soon as you checkout 1a8bcbd5f7110f36ea187fc95bce5e59ad41b4ee and create a new build, it crashes upon opening the installed apk on device.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
@alterx - it shouldn't be needed unless you're getting the location when your app is backgrounded. the foreground service, somewhat confusingly, allows you to get location when your app is not foregrounded.

**Comment by alterx** [comment]
Yeah, that's how I understand it. Just wanted to confirm. For background location updates we use the background location service so we should be fine. Thanks @brentvatne

**Comment by brentvatne** [comment]
@alterx - i released this ~30 mins ago, you can run `npx expo install --fix` to get it

**Comment by brentvatne** [comment]
> For background location updates we use the background location service so we should be fine.

as far as I understand this, you also need to use the foreground service in this case. the background service is for when the app is not running at all, while the foreground service is when it's backgrounded or foregrounded. we enable the foreground service permission by default when you enable background location: https://github.com/expo/expo/pull/27359

**Comment by alterx** [comment]
We use the background service precisely for when the app is not running at all. And then we have specific updates that the user triggers when the app is running and they're interacting with it, or when users trigger a geofence.

That's why this is confusing: this was not the case before. And that's why I'm asking if this is due to the recent changes. We have this app in production and available and the code related to location hasn't changed. We never ask for the foreground location service permission, it's not even in our permissions array. The only change was upgrading to SDK 50.

**Comment by brentvatne** [comment]
@alterx - the change was on google's end with android 14, we didn't make any changes here except updating the target sdk version. cc @alanjhughes who has more context

**Comment by alterx** [comment]
Oh, absolutely! Just wanted to be sure that this was the case (that the change was due to the update in the target SDK and Android 14), sorry if it came across in a different way.

Just want to figure out if, after this fix, our current code will work in the same way or if we now need to add the foreground permission too @brentvatne

**Comment by brentvatne** [comment]
@alterx - my understanding is that it is needed, but i may be incorrect, so i would try it for your use case without the foreground service permission and verify if it works. i'm very interested in hearing the answer! i'm not an expert on the android location apis

**Comment by alterx** [comment]
Interestingly enough I updated the the repo I submitted as a reproducible example to the latest `"expo-location": "~16.5.5"`, created a new build and the app still crashes @brentvatne

**Comment by brentvatne** [comment]
@alterx - you rebuilt the native app after updating the version i assume?

**Comment by alterx** [comment]
@brentvatne 
Yeah, cleaned everything, fresh install, fresh build. Twice. Let me see if I can get that stacktrace.

Going back to this: 

> we enable the foreground service permission by default when you enable background location: https://github.com/expo/expo/pull/27359

If I do:

```
 "plugins": [
      [
        "expo-location",
        {
          ...,
          "isAndroidBackgroundLocationEnabled": true,
          "isAndroidForegroundServiceEnabled": false
        }
      ]
    ],
]
```
It should disable it, right? Cause this is how the repo has it right now.

What worries me is that, according to [Google](https://developer.android.com/about/versions/14/changes/fgs-types-required#system-runtime-checks):

> The system checks for proper use of foreground service types and confirms that the app has requested the proper runtime permissions or uses the required APIs. For instance, the system expects apps that use the foreground service type [FOREGROUND_SERVICE_TYPE_LOCATION](https://developer.android.com/reference/android/content/pm/ServiceInfo#FOREGROUND_SERVICE_TYPE_LOCATION) type to request either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION.

> This implies that apps must follow a very specific order of operations when requesting permissions from the user and starting foreground services. Permissions must be requested and granted before the app attempts to call startForeground(). Apps that request the appropriate permissions after the foreground service has been started must change this order of operations and request the permission before starting the foreground service.

If expo enables it by default, dev will have this issue where they aren't even requesting these permissions and because of that their app crashes immediately. Seems a bit counter-intuitive to enable this one by default, unless i'm missing something

**Comment by alterx** [comment]
I did a third build to try and get that stacktrace. Cleaned up cache and storage, uninstalled from phone and installed again and it worked so it seems like there was some kind of caching issue there
