### ISSUE TITLE
[expo-notifications][iOS][Snack] scheduleNotificationAsync() not working in Expo Go

### ISSUE THREAD

**Issue by scd8418** [expo/expo#27334]
### Minimal reproducible example

https://snack.expo.dev/@scd8418/push-notifications

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

The expo example highlighted in the documentation with a link to a snack fails on two different iphones when you select SDK 50. If you downgrade to SDK 49, the snack example works.

https://docs.expo.dev/versions/latest/sdk/notifications/#usage

I have the same problem in my own app with code that worked in earlier SDKs. I never receive a call to handleNotification.

The environment submissions are for my own app and may be be relevant to the failing snack example.

### Environment

expo-env-info 1.2.0 environment info:
System:
OS: macOS 13.6.2
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
expo: ^50.0.2 => 50.0.2
react: 18.2.0 => 18.2.0
react-native: 0.73.2 => 0.73.2
Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

The package "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

The following packages should be updated for best compatibility with the installed expo version:
expo@50.0.2 - expected version: ~50.0.8
expo-camera@14.0.1 - expected version: ~14.0.5
expo-file-system@16.0.6 - expected version: ~16.0.7
expo-image@1.10.4 - expected version: ~1.10.6
expo-location@16.5.2 - expected version: ~16.5.4
expo-notifications@0.27.3 - expected version: ~0.27.6
expo-splash-screen@0.26.3 - expected version: ~0.26.4
react-native@0.73.2 - expected version: 0.73.4
react-native-maps@1.8.0 - expected version: 1.10.0
react-native-reanimated@3.6.1 - expected version: ~3.6.2
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

**Comment by christopherwalter** [comment]
@scd8418 just to be sure, does this still occur when you bump expo-notifications to the latest version?

**Comment by scd8418** [comment]
This is most easily reproducted using the example linked in the documentation at 

https://docs.expo.dev/versions/latest/sdk/notifications/#usage

If you selected "SDK 50 latest" in the left as the reference version and run the example on snack, it fails. If you selected SDK 49, it works. The only difference that I can see is the dependencies in package.json:

[package.json for SDK 50 latest]
{
  "dependencies": {
    "expo-device": "~5.9.3",
    "expo-permissions": "*",
    "expo-notifications": "~0.27.6"
  }
}

[oackage.json for SDK 49]
{
  "dependencies": {
    "expo-device": "~5.4.0",
    "expo-permissions": "~14.2.1",
    "expo-notifications": "~0.20.1"
  }
}

**Comment by douglowder** [comment]
I set up a Snack against SDK 50 to try to reproduce this issue here: https://snack.expo.dev/@douglowderexpo/brave-yellow-edamame

The most important difference between this and your code is that my project ID is extracted from the real project ID in the Expo config.

Running this snack on Expo Go on my device, I see that the "Press to schedule a notification" button doesn't seem to work. I'm investigating that. It did work fine when I built the same code into an EAS device build.

I do see that if you manually push a notification to the device using our web tool at https://expo.dev/notifications , the notifications are received and displayed as expected.

My conclusion: there is a possible issue in SDK 50 with `Notifications.scheduleNotificationAsync()` that is specific to Expo Go, but does not occur in standalone native builds. Otherwise, everything seems to work normally.

**Comment by douglowder** [comment]
Testing a similar snack in SDK 49 with Expo Go, I do see that the scheduleNotificationAsync() API works there, so we need to figure out what changed.

**Comment by douglowder** [comment]
I created a test project at https://github.com/douglowder/NotificationsTest , with similar app code.

Installed that project, ran `yarn start`, and typed `s` to switch to Expo Go mode.

When I run that in Expo Go, everything works as expected, including scheduled notifications. So the issue we are seeing here is specific to Snack, and specific to SDK 50.

**Comment by douglowder** [comment]
Closing this. The problem will be tracked in the Snack repo in https://github.com/expo/snack/issues/21

**Comment by scd8418** [comment]
This is consistent with what I'm seeing in my app. Push notifications in
foreground mode work normally in my production build, but they don't work
in Expo Go on my phone.

**Comment by douglowder** [comment]
@scd8418 They will work in Expo Go, but you have to be serving the app from a project you create on your local dev machine -- the breakage is only happening with apps run out of the Snack service.
