### ISSUE TITLE
Expo-Task-Manager + Expo-Notifications fails running on Android 14

### ISSUE THREAD

**Issue by philipehsing** [expo/expo#27345]
### Minimal reproducible example

https://github.com/philipehsing/expo-android-bug

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

# Summary
Main goal is to run a task via expo-task-manager every 6h and schedule reminders for the next 24hours that have been configured by the user.

I tried multiple ways to achieve this:
- Expo Background Fetch
- Expo Notifications, send a data-only/background/silent push notification to users device that trigger our task.

## Expo Notifications
Data-only/background/silent notifications doesn't arrive to the phone while app is **terminated**.
- Tested different priorities with no success (normal, high) ❌ 
- Normal push notification do arrive (when including body and title) ✅ 
- When app is in foreground data-only/background/silent notifications do arrive ✅ 

## Expo Task Manager + Expo Background Fetch
I have defined a task `BACKGROUND-NOTIFICATIONS-TASK` that gets triggered by expo-task-manager. 
- Schedule a job running each 1 hour ✅ 
- App State (expo-task-manager):
  - Foreground: Works fine ✅ 
  - Background: Task gets triggered, but as soon as the task hit a **promise** or **inner promise** the code stops. ❌ 
  - Terminated: Task gets triggered, but as soon as the task hit a **promise** or **inner promise** the code stops. ❌

## Device
Worth to mention, the different solutions that ive tried works perfectly fine on IOS (all of them).
- Android 13 ❌ 
- Android 14 ❌ 
- IOS ✅ 

## Simplified Code Example
```
TaskManager.defineTask(
  BACKGROUND_NOTIFICATIONS_TASK,
  async ({ data = {} }: { data: BackgroundNotificationPayload | object }) => {
    console.log('Start');
    const test = async function () {
      console.log('async func call');
    };
    await test();
    console.log('Is this ever reached');
  },
);
```

## Result
App in foreground:
```
 LOG  Start
 LOG  async func call
 LOG  Is this ever reached
```

App in background:
```
 LOG  Start
 LOG  async func call
```

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 3.5.1 - /usr/local/bin/yarn
      npm: 9.8.1 - ~/HYPHEN/hyphen-app/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1 
      expo: ~50.0.7 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.7
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by Volland** [comment]
i faced with same issue

**Comment by simonwh** [comment]
I've also seen this :/ Would love to hear if anyone has a fix?

**Comment by AaronH2001** [comment]
Hello everyone, after a long search I found out that background tasks now require extra authorisation in Android 14. When I start the app in the emulator the tasks etc work but when I build them it doesn't work. Have you found out what could be the reason for this and how we can fix it?

![image](https://github.com/expo/expo/assets/74665685/94547112-7f0e-4af9-90d5-912054e4e3bc)

https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions

Best regards

**Comment by pax-k** [comment]
Same issue here @expo-bot

**Comment by AaronH2001** [comment]
Hello everyone,

I was able to rectify the error.

Go to your app.json and add the following under "plugins":
- expo-location : "isAndroidBackgroundLocationEnabled": true,
          "isAndroidForegroundServiceEnabled": true
          
![image](https://github.com/expo/expo/assets/74665685/4b6327f0-91ee-4930-a27f-83f970d22365)

After that, everything worked for me. This is because new authorisations have been added to android 14. You can find the info in the documentation here: https://docs.expo.dev/versions/latest/sdk/location/#configurable-properties

**Comment by demchuk-alex** [comment]
Same issue here @expo-bot 
This only happens on a physical device in terminated and background mode for, on top of it on some of the phones it survives the background. 

Simulator all modes just fine 👍 

the code is fairly simple like in `App.js`

just put this code after imports:

```javascript
const BACKGROUND_NOTIFICATIONS_TASK = 'BACKGROUND-NOTIFICATIONS-TASK';

TaskManager.defineTask(BACKGROUND_NOTIFICATIONS_TASK, async () => {
    console.log('Start');
    const test = async function () {
        console.log('async func call');
    };
    await test();
    console.log('Is this ever reached');

    return BackgroundFetch.BackgroundFetchResult.NewData;
});

BackgroundFetch.registerTaskAsync(BACKGROUND_NOTIFICATIONS_TASK, {
    minimumInterval: 10, // 15 minutes
    stopOnTerminate: false,
    startOnBoot: true,
}).then();
``` 

So ```console.log('Is this ever reached');``` is never reached on the physical device in the terminated state.
This is so weird because scheduling works fine in terminated mode, here is logcat logs

```
Handling intent with task name 'BACKGROUND-NOTIFICATIONS-TASK' and app scoping identifier 'xxxxx'.
Handling job with task name 'BACKGROUND-NOTIFICATIONS-TASK 
```

**Comment by philipehsing** [comment]
Issue was not related to expo, another external lib was clashing (web3).

**Comment by Rohit-Parte** [comment]
> Same issue here @expo-bot This only happens on a physical device in terminated and background mode for, on top of it on some of the phones it survives the background.
> 
> Simulator all modes just fine 👍
> 
> the code is fairly simple like in `App.js`
> 
> just put this code after imports:
> 
> ```js
> const BACKGROUND_NOTIFICATIONS_TASK = 'BACKGROUND-NOTIFICATIONS-TASK';
> 
> TaskManager.defineTask(BACKGROUND_NOTIFICATIONS_TASK, async () => {
>     console.log('Start');
>     const test = async function () {
>         console.log('async func call');
>     };
>     await test();
>     console.log('Is this ever reached');
> 
>     return BackgroundFetch.BackgroundFetchResult.NewData;
> });
> 
> BackgroundFetch.registerTaskAsync(BACKGROUND_NOTIFICATIONS_TASK, {
>     minimumInterval: 10, // 15 minutes
>     stopOnTerminate: false,
>     startOnBoot: true,
> }).then();
> ```
> 
> So `console.log('Is this ever reached');` is never reached on the physical device in the terminated state. This is so weird because scheduling works fine in terminated mode, here is logcat logs
> 
> ```
> Handling intent with task name 'BACKGROUND-NOTIFICATIONS-TASK' and app scoping identifier 'xxxxx'.
> Handling job with task name 'BACKGROUND-NOTIFICATIONS-TASK 
> ```

Are you able to resolve it? Seems expo-task-manager not working on android 14
