### ISSUE TITLE
Expo v50.0.8 Go - Certificate Not Valid

### ISSUE THREAD

**Issue by cmchenry-pythius** [expo/expo#27360]
### Summary

My Expo Go app was working, then all of a sudden I started receiving this error. I assume my IP changed, but I checked my IP and it aligns. I also set the env variable

I'm on Mac, I ran this command: `export REACT_NATIVE_PACKAGER_HOSTNAME=10.83.7.182`

<img width="648" alt="Screenshot 2024-02-28 at 8 11 07 PM" src="https://github.com/expo/expo/assets/149111109/9d3b27b6-b55c-460b-803e-27ca7c3008e7">

### What platform(s) does this occur on?

iOS

### SDK Version

50.0.8

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.8 => 50.0.8 
      expo-router: ~3.4.1 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: managed

### Minimal reproducible example

Package.json

```
"dependencies": {
    "@react-native-async-storage/async-storage": "1.22.2",
    "axios": "^1.6.7",
    "expo": "^50.0.8",
    "expo-auth-session": "~5.4.0",
    "expo-constants": "~15.4.2",
    "expo-linear-gradient": "~12.7.2",
    "expo-linking": "~6.2.1",
    "expo-router": "~3.4.1",
    "expo-splash-screen": "~0.26.1",
    "expo-status-bar": "~1.11.1",
    "firebase": "^10.6.0",
    "formik": "^2.4.5",
    "lucide-react-native": "^0.338.0",
    "nativewind": "^4.0.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.5",
    "react-native-reanimated": "~3.6.0",
    "react-native-safe-area-context": "4.9.0",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "^14.1.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-web": "~0.19.6",
    "tailwindcss": "^3.4.0",
    "yup": "^1.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.59",
    "typescript": "^5.3.0"
  },
  "overrides": {
    "undici": "^6.6.2",
    "semver": "^7.6.0"
  },
  ```

**Comment by justin-medeiros** [comment]
I also just encountered this issue +1

**Comment by redkean** [comment]
+1

**Comment by plcharriere** [comment]
Also encountering this issue since a few minutes ago.

**Comment by SidMasih** [comment]
+1 here 

verified that its also happening for snack (all snacks)

**Comment by SidMasih** [comment]
Someone probs refreshed their certs incorrectly ;) it happens

**Comment by MikeRyan05** [comment]
+1

**Comment by sahiljaidka224** [comment]
+1

**Comment by jendan-nikolai** [comment]
+1

**Comment by sokunsamnang** [comment]
+1

**Comment by babe269** [comment]
+1

**Comment by HarshDev2** [comment]
+1

**Comment by raphaelMrci** [comment]
+1

**Comment by Miigaarino** [comment]
+1

**Comment by initialed85** [comment]
+1

**Comment by Bennacci** [comment]
+1

**Comment by janmaywevolt** [comment]
+1

**Comment by phacts** [comment]
+1

**Comment by MaitreeShakya** [comment]
+1

**Comment by nasanjargal127** [comment]
Temporary solution is comment out `extra.eas.projectId`

**Comment by noahkurz** [comment]
+1

**Comment by maxwell-oroark** [comment]
+1

**Comment by racheljlam** [comment]
+1

**Comment by noahkurz** [comment]
> Temporary solution is comment out `extra.eas.projectId`

This works

**Comment by billyfranklim1** [comment]
I'm having the same problem

![image](https://github.com/expo/expo/assets/44212595/12b48597-7bdc-41c2-b3de-f96e75ea0f97)

**Comment by arjayosma** [comment]
> Temporary solution is comment out `extra.eas.projectId`

This works, however for apps requiring this information (push notification, and etc.) this will throw an `undefined` error.

**Comment by rpatidar** [comment]
please stop commenting +1 as it spamming the thread  use emoji in orignal question to thumbs up.

**Comment by joachimjose** [comment]
The same in  "expo": "~49.0.18", certificate not valid

**Comment by sahiljaidka224** [comment]
It's working now

**Comment by alanjhughes** [comment]
https://status.expo.dev/incidents/slnvd5h31nw5

**Comment by serendipity1137** [comment]
![Screenshot_20240323_214912_Expo Go](https://github.com/expo/expo/assets/132065865/0db5232c-dba8-4cf6-a024-2d671a5eee96)
Not working, anybody has ideas?
Expo says the uptime is well.

**Comment by vijaystroup** [comment]
Just upgraded to SDK 50.0.17 and rebuilt the development build for dev-client and upon running `npx expo start --dev-client --tunnel`, trying to open the app I get the error of "Failed to load app from https://xxxxxxx-8081.exp.direct with error: An SSL error has occurred and a secure connection to the server cannot be made".

Currently only tested for iOS.

Currently have not found any solutions.
