### ISSUE TITLE
[CLI] [Android] rootProject.allprojects is not copied into build.gradle

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#27373]
### Summary

I understand not a lot about the native side. So maybe this is considered to be the right behavior - feel free to close this issue then. 

I have a package "react-native-smartlook-analytics" that has the following in its build.gradle:
```
rootProject.allprojects {
  repositories {
    google()
    mavenCentral()
    maven {
      url "https://sdk.smartlook.com/android/release"
    }
  }
}
```

I would expect that this change would propagate through to the final projects android/build.gradle. It doesn't. The final android/build.gradle looks like this:
```
allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(['node', '--print', "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), '../android'))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(['node', '--print', "require.resolve('jsc-android/package.json', { paths: [require.resolve('react-native/package.json')] })"].execute(null, rootDir).text.trim(), '../dist'))
        }

        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}
```

This results in an error during `npx expo run:android`:

```
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.smartlook.android:smartlook-analytics:2.3.4.
     Searched in the following locations:
       - file:/Users/raider/WebstormProjects/smartlook-bug/smartlook-bug/node_modules/react-native/android/com/smartlook/android/smartlook-analytics/2.3.4/smartlook-analytics-2.3.4.pom
       - file:/Users/raider/WebstormProjects/smartlook-bug/smartlook-bug/node_modules/jsc-android/dist/com/smartlook/android/smartlook-analytics/2.3.4/smartlook-analytics-2.3.4.pom
       - https://dl.google.com/dl/android/maven2/com/smartlook/android/smartlook-analytics/2.3.4/smartlook-analytics-2.3.4.pom
       - https://repo.maven.apache.org/maven2/com/smartlook/android/smartlook-analytics/2.3.4/smartlook-analytics-2.3.4.pom
       - https://www.jitpack.io/com/smartlook/android/smartlook-analytics/2.3.4/smartlook-analytics-2.3.4.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/smartlook/android/smartlook-analytics/2.3.4/smartlook-analytics-2.3.4.pom
     Required by:
         project :app > project :react-native-smartlook-analytics

```

### What platform(s) does this occur on?

Android

### SDK Version

Tried it with 49 and 50

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: 50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.3.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/RRaideRR/smartlook-bug

1. `yarn install`
2. `npx expo run:android`

**Comment by RRaideRR** [comment]
Hey @MattRoelle ,

very interesting. The smartlook support gave me the impression that I'm the only one with this problem. Plus: I also know some expo projects where this is running fine. I cannot explain this fact that its running for some but not for us - that's why I suspected it has something to do with the CLI.

However, I wrote a custom config plugin "withModifyBuildGradle.js" that copies the repository into the build.gradle:

```
const { withProjectBuildGradle } = require('@expo/config-plugins');

const smartlook_allprojects_block = `
// SMARTLOOK CONFIGURATION - START
allprojects {
    repositories {
        maven { url "https://sdk.smartlook.com/android/release" }
    }
}
// SMARTLOOK CONFIGURATION - END
`;

module.exports = (config) => {
  return withProjectBuildGradle(config, (config) => {
    config.modResults.contents += smartlook_allprojects_block;

    return config;
  });
};
```

Be sure to include it in your plugins in your app.json like this: ` ['./plugins/withModifyBuildGradle'],` (if its located in the plugins-folder). Hope this helps :)

**Comment by kimdanielarthur-cowlabs** [comment]
Great thanks @RRaideRR that worked for me to! Was getting the error when building locally, but not when building on EAS servers.

**Comment by Kudo** [comment]
hi there!

mutating allproject.repositories inside a subproject is not recommended by gradle and won't work occasionally. the recommended way is using a config-plugin to do that as commented above. we also did that for [expo-camera](https://github.com/expo/expo/blob/650a7b5b089ef517489f16fe429afab3eb372072/packages/expo-camera/plugin/src/withCamera.ts#L27-L79).

**Comment by t0ma5h** [comment]
Ran into this with the latest sdk too. 
`
Could not determine the dependencies of task ':app:processDebugResources'.> 
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'> 
Could not find com.smartlook.android:smartlook-analytics:2.3.20.`

To anyone running into this in the future, with `expo-build-properties` there's no need for a plugin. Just do this in `app.config.js` or `app.json` : 

```
expo {
    ......
    plugins: [
      [
        'expo-build-properties',
        {
          ios: {
            ......
          },
          android: {
          .....
            extraMavenRepos: [
              'https://sdk.smartlook.com/android/release',
            ],
          },
        },
      ]
   ]
}

**Comment by wodin** [comment]
> To anyone running into this in the future, with `expo-build-properties` there's no need for a plugin. Just do this in `app.config.js` or `app.json` :

Yes, you're right. You only need a config plugin if you're writing a module that you want to release on `npm` and you don't want to have to tell people to add something like that to `app.json`
