### ISSUE TITLE
Generating dynamic tabs

### ISSUE THREAD

**Issue by Noitham** [expo/expo#27377]
### Minimal reproducible example

https://github.com/Noitham/expo-dynamic-tabs

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hello,

Migrating to using the `expo-router` from the `react-navigation` package I've encountered an issue when attempting to generate dynamic routes based on an array.

I've created a repo showing the issue: https://github.com/Noitham/expo-dynamic-tabs

Basically, given an array, f. ex:

```
  const nestedTabs: NestedTab[] = [
    {
      id: "1",
      title: "Nested tab 1",
      description: "Hello, I'm the nested tab 1",
    },
    {
      id: "2",
      title: "Nested tab 2",
      description: "Hello, I'm the nested tab 2",
    },
    {
      id: "3",
      title: "Nested tab 3",
      description: "Hello, I'm the nested tab 3",
    }
  ]
  ```
  
I'm trying to generate a `Tab` navigator creating a tab for each of the items:
  
```
...
...
  return (
    <Tabs>
      {nestedTabs.map(tab => {
        return (
          <Tabs.Screen
            key={tab.id}
            name={tab.id}
            options={{
              href: {
                pathname: "/[id]",
                params: {
                  id: tab.id,
                },
              },
              title: tab.title,
            }}
          />
        )
      })}
    </Tabs>
  )
```

Unfortunately, I haven't been able to achieve so, nor I haven't been able to find specific docs regarding this.
There are various other issues, but there isn't a clear answer to it:

https://github.com/expo/expo/issues/26187
https://github.com/expo/router/issues/522

Using the `react-navigation`, we're able to simply pass in a children component to the `Tab.Screen`, but that's not possible when using `expo-router`.

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.local/share/rtx/installs/nodejs/18.17.1/bin/node
      Yarn: 1.22.19 - ~/.local/share/rtx/installs/nodejs/18.17.1/bin/yarn
      npm: 10.1.0 - ~/.local/share/rtx/installs/nodejs/18.17.1/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/danielgonzalez/.local/share/rtx/installs/ruby/2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
This currently isn't possible as each TabBar item needs a unique name, yet all those "Tabs" have the same screen name of `[id]`. We're still working on the feature set of the navigators, and we haven't yet worked on edge cases like this.

However, you can replicate the functionality you want using the `<Slot />` component and simply designing your own TabBar.

**Comment by EvanBacon** [comment]
Here's an example of creating a custom "Tab Slot" where you can add your own buttons and styles https://github.com/EvanBacon/evanbacon.dev/blob/40eefcdc227a1e968e02645ab657973454046844/src/app/(main)/_layout.tsx#L4-L7

**Comment by jowparks** [comment]
I found this was a more helpful example from @EvanBacon for anyone else looking:
https://github.com/expo/router/issues/522#issuecomment-2267170882
