### ISSUE TITLE
expo-camera/next unable to record video

### ISSUE THREAD

**Issue by ste00martin** [expo/expo#27380]
### Minimal reproducible example
When using the latest version of expo-camera, 14.0.5 the expo-camera/next library isn't able to record a video. The older, expo-camera library works but not the new library.

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Expo camera works, but expo camera next does not for recording a video. The beginning of recording a video happens but no uri is ever returned when calling `stopRecording()`

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      npm: 10.3.0 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/stefan/.rvm/gems/ruby-2.7.8/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8
      expo-router: ~3.4.7 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

❯ npx expo-doctor@latest
Need to install the following packages:
expo-doctor@1.4.0
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by DLawla** [comment]
@ste00martin In case you made the same mistake as I did at first, I didn't catch the change from `expo-camera` to `expo-camera/next` you have to assign the `mode` on the `CameraView` when you switch between photo and video.

Previously, you could just call the photo capture and video record functions at will, but now you have to first set the mode, then call the respective functions.

**Comment by vanjaoljaca** [comment]
it is a bit annoying that the api silently fails to record if mode is not set to video...
