### ISSUE TITLE
torch mode only turns on the flash briefly

### ISSUE THREAD

**Issue by heaversm** [expo/expo#2738]
### Environment

```
Expo CLI 2.2.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.2.1 - /usr/local/bin/yarn
      npm: 6.0.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.2
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.18.2 => 2.18.2
    npmGlobalPackages:
      expo-cli: 2.2.5
```

Testing on iPhone XS Model MTAH2LL/A (A1920)  v 12.1

### Steps to Reproduce

Load the [snack](https://snack.expo.io/r1qOWipa7) in your mobile device. You should see your camera, and the torch / flashlight should be consistently on. Instead, it is either not on at all, or flashes just briefly when the camera first comes on.

### Reproducible Demo

[https://snack.expo.io/r1qOWipa7](https://snack.expo.io/r1qOWipa7)

**Comment by heaversm** [comment]
Realized I need a delay after cam is shown before activating torch. Closing.

**Comment by iKrushYou** [comment]
@heaversm can you share how you achieved this? Also, this doesn't seem like a solution, more of a patch.. I feel like the Expo API shouldn't require you to code in your own delay to make it work

**Comment by duckbrain** [comment]
I agree with iKrushYou. Can this issue be re-opened? This is still an issue in Expo 34. Android behaves as expected.

**Comment by cruzach** [comment]
Opened a new issue with full repro here https://github.com/expo/expo/issues/6086
