### ISSUE TITLE
FontAwesome6 icons don't work

### ISSUE THREAD

**Issue by hbiede** [expo/expo#27388]
### Minimal reproducible example

https://icons.expo.fyi/Index

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

A large number of the icons in the FA6 library don't render. Visible on the icons index website

### Environment

N/A

### Expo Doctor Diagnostics

N/A

**Comment by hbiede** [comment]
Well, there was a minimal reproducible example...

**Comment by amandeepmittal** [comment]
It was reported a while back in `expo/vector-icons` repo so going to mark this as duplicate of that: https://github.com/expo/vector-icons/issues/286.

**Comment by hbiede** [comment]
> Hey @hbiede, do you mean icons like highlighted in the following screenshot?
> 
> 
> 
> ![CleanShot 2024-03-02 at 02 43 34@2x](https://github.com/expo/expo/assets/10234615/15fb784b-cef9-4192-beff-dab18a1c06ce)
> 
> 

Oh, yep
