### ISSUE TITLE
[expo-camera/next]: Flash Mode is not working

### ISSUE THREAD

**Issue by lodev09** [expo/expo#27392]
### Minimal reproducible example

https://github.com/lodev09/expo-camera-issue

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Flash mode prop is not working. It looks like it's always set to `auto`.
Tested on IOS device.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /opt/homebrew/bin/npm
      Watchman: 2023.11.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by benedettix** [comment]
guys, try changing from 'flash' prop to 'flashMode'

**Comment by yoann84** [comment]
Still have the problem on android. On iOS it works just fine.

**Comment by osvaldoski** [comment]
try with 
enableTorch={true}
https://docs.expo.dev/versions/latest/sdk/camera/#enabletorch

**Comment by PAULbigBA** [comment]
> try with enableTorch={true} https://docs.expo.dev/versions/latest/sdk/camera/#enabletorch
In Android, it will turn on the torch, but before taking any pictures, it will keep the torch on no matter if I am taking the picture or not. I want the flash to turn on at the moment I take the photo.
