### ISSUE TITLE
[3.4.8] Unable to run Redux RTK inside route

### ISSUE THREAD

**Issue by Engazan** [expo/expo#27395]
### Minimal reproducible example

https://github.com/Engazan/expo-router-rtk-error

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

i cant use Redux RTK methods inside rroute screens

how to reproduce:
1. open app
2. you get error `cannot read property 'reducer' of undefined`

problem  part is `src/app/AuthDataLoadingRoute.tsx` when i call RTK query `const useGetSelectedCompanyQueryResult = useGetSelectedCompanyQuery({});` ( whne you comment it and reload app everything works, also when you uncommentt it when app is open it also works )

it looks like its somehow preloaded and called before "_layout.tsx" where Redux setup is

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 21.6.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^50.0.8 => 50.0.8
      expo-router: ~3.4.1 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
The error you are receiving is this error

```
λ  WARN  Require cycle: src/redux/slices/ApiSlice.ts -> src/redux/store.ts -> src/redux/slices/ApiSlice.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle. 
  factory (src/redux/store.ts:13:1)
  factory (src/redux/slices/ApiSlice.ts:1:1)

Metro error: Cannot read properties of undefined (reading 'reducer')

  20 |
  21 | const reducers = combineReducers({
> 22 |     api: ApiSlice.reducer, // dynamic API reducer
     |                   ^
  23 | })
  24 | const rootReducer = (state: any, action: any) => {
  25 |     if (action.type === 'USER_LOGOUT') {
```

Due to your require cycle, `ApiSlice` is undefined and causes the error
