### ISSUE TITLE
Touch ID for IOS support

### ISSUE THREAD

**Issue by LeiZeng** [expo/expo#274]
Hi guys, can we please support IOS Touch ID from another awesome project?

https://github.com/naoufal/react-native-touch-id

**Comment by ide** [comment]
Hi, Expo has an experimental API here: https://forums.expo.io/t/touchid-fingerprint-exposed-through-sdk/577 that might meet your use case?

**Comment by brentvatne** [comment]
we got the message ;)

https://expo.canny.io/feature-requests/p/touch-id-support
https://expo.canny.io/feature-requests/p/touch-id-for-ios-support

**Comment by LeiZeng** [comment]
You guys are awesome!!

**Comment by shankie-san** [comment]
Hey guys, the fingerprint support works well, but it's a bit of a partial solution unless we give the ability to fall back to passcode, as not all devices have a fingerprint ID hardware.

**Comment by ChelseaDan** [comment]
Was there an answer to falling back to passcode? Facing this issue too.

**Comment by jack1012t** [comment]
I am trying to find out if "Touch ID for Expo" message can be configured.  I found only one post that mentions this directly, and the answer was NO.  

Also are there any other configs?  The only one I know of is the additional **promptMessage** which adds an additional message below "Touch ID for Expo"

**Comment by shankie-san** [comment]
> Was there an answer to falling back to passcode? Facing this issue too.

Yes, I believe that the newer versions of the SDK include `LocalAuthentication`, which falls back to passcode if TouchID isn't enrolled. Seems to work well for me.
