### ISSUE TITLE
[Unhandled promise rejection: Error: Audio mode attempted to be set without the required keys: ["playThroughEarpieceAndroid"]]

### ISSUE THREAD

**Issue by rodrigowpl** [expo/expo#2740]
### Environment

```
  Expo CLI 2.4.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.5 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: ^2.18.0 => 2.18.2
    npmGlobalPackages:
      expo-cli: 2.4.0
```

### Steps to Reproduce

Just import and use expo/Video

### Expected Behavior

Don't show warning

### Actual Behavior

I'm using **expo/video** and a warning is a show

![captura de tela 2018-11-17 as 19 59 26](https://user-images.githubusercontent.com/18172307/48666160-67fcf500-eaa3-11e8-9f16-b1eff5265ce7.png)

my code (is the same used in example in docs, and happens in all device)

```
<Video
  source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
  rate={1.0}
  volume={1.0}
  isMuted={false}
  resizeMode="cover"
  shouldPlay
  isLooping
  style={{ width: 300, height: 300 }}
/>
```

**Comment by ariksc** [comment]
Did you figure this out?

**Comment by react1130** [comment]
Hello rodigowpl.. How are you?
Now I have the issue like you.
Package.json file structure:
"@expo/videoplayer": "^0.4.0",
"expo": "^32.0.0",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
 "react-native-alphabet": "^1.0.0",

And my code is:
<View style={styles.videoContainer}>
									<VideoPlayer
										videoProps={{
											shouldPlay: true,
											resizeMode: Video.RESIZE_MODE_CONTAIN,
											source: this.isSelectedLearnModule() ? {
													uri: this.convertVideoUrl(currentLearn.VideoFilename)
												} : this.convertVideoUrl(learnModules[0].VideoFilename),
											style: { width: '100%', height: 190 },
											ref: ref => (this.videoRef = ref),
											onFullscreenUpdate: this.handleVideoFullscreenUpdate,
											onPlaybackStatusUpdate: this.handlePlaybackStatusUpdate
										}}
										isPortrait={true}
										playFromPositionMillis={0}
										switchToPortrait={this.switchToPortrait}
										switchToLandscape={this.switchToLandscape}
										thumbImage={this.isSelectedLearnModule() ? (
												require('../images/home_screen/Video2-Networking.png')
											) : (
												require('../images/home_screen/Video1-MagneticOnlineProfile.png')
											)
										}
									/>

								</View>




How do you fix this issue?
Please help me.
Thanks.

**Comment by kolawoletech** [comment]
@react1130 There is just a line you need to change in the index.js of https://github.com/expo/videoplayer . Check https://github.com/expo/videoplayer/pull/38/files/ce44a1abc7addf350f8a4fab7672f52bb3d4e1f8 or this pull https://github.com/expo/videoplayer/pull/38

**Comment by mtaylor769** [comment]
@kolawoletech Thanks! this was a pesky message, the `playThroughEarpieceAndroid: true,` option fixed it.

> @react1130 There is just a line you need to change in the index.js of https://github.com/expo/videoplayer . Check https://github.com/expo/videoplayer/pull/38/files/ce44a1abc7addf350f8a4fab7672f52bb3d4e1f8 or this pull [expo/videoplayer#38](https://github.com/expo/videoplayer/pull/38)

**Comment by AleksandarSavic95** [comment]
Adding line:
```
playThroughEarpieceAndroid: true,
```
fixed the issue for iPhone, but there was no sound on Android, so I imported `Platform` from `react-native` and changed the above line to this:
```
...(Platform.OS === 'ios' && { playThroughEarpieceAndroid: true })
```
this will add the `playThroughEarpieceAndroid: true` key value pair only if we are on iOS.
