### ISSUE TITLE
How to implement Deep Link in Expo Router

### ISSUE THREAD

**Issue by razamsalem** [expo/expo#27429]
### Minimal reproducible example

https://github.com/expo/router/issues/818

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I want to implement deep linking in router expo but the documentation is not clearly explained and there is not much information on the internet about it.

In react native navigation there was something like this:
```
import * as Linking from 'expo-linking';

const prefix = Linking.createURL('/');

function App() {
  const linking = {
    prefixes: [prefix],
  };

  return (
    <NavigationContainer linking={linking} fallback={<Text>Loading...</Text>}>
      {/* content */}
    </NavigationContainer>
  );
}
```

How can I do it in expo router?

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      @expo/metro-config: ~0.17.1 => 0.17.4 
      @expo/webpack-config: ^19.0.0 => 19.0.1 
      expo: ~50.0.5 => 50.0.7 
      expo-router: ~3.4.7 => 3.4.7 
      react: ^18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.9 => 0.19.10 
    Expo Workflow: managed

**Comment by brentvatne** [comment]
hi there!

i responded to your email with:

> Deep linking is built into Expo Router - because everything is already based on paths based on your project structure, you have URLs by default. No configuration is needed. You don't need to add a prefix, that's handled automatically by Expo Router as well. Just make sure you've set a scheme in your app.json / app.config.js: https://docs.expo.dev/router/installation/#modify-project-configuration

**Comment by oussamachah2020** [comment]
m using deep linking , when i share a post i get a url from which i can go to the app. The issue is once i open the app via the link i got an infinite loop

**Comment by TomasSestak** [comment]
how to send parameters as deep link?

**Comment by andres-dos-santos** [comment]
Expo router doesn't need extra configuration like react-navigation linking, just get the URL prefix (scheme) and test it with npx uri-scheme open `<scheme>/<page>` and if you want to pass parameters to the page just add a `/<param>`.

Imagine you have a product page that needs the id to load the product data, just define the route in the stack, create the page and test it with `npx uri-scheme open <scheme>/<page>/<param>`.

**Comment by kartoone** [comment]
Yeah but then how do you access the param??

**Comment by andres-dos-santos** [comment]
Your page will probably be created as a dynamic route, i.e. `route/[id-of-something]`, so within the page you can access it with `useLocalSearchParams`.

**Comment by markwitt1** [comment]
Any update on this?

**Comment by kartoone** [comment]
For my code, it was enough to add the code below inside a useEffect() to grab the querystring param named code once I had my custom url scheme mbtclient:// registered ... for the emulator you just had to add npx uri-scheme add "mbtclient" --android but it was quite a bit of a headache to get the --ios emulator to register the custom scheme involving things you have to do on the actual server hosting the deep link. They go into all the details on the expo deep linking page. I followed them and after a few tries got it to work on the ios emulator as well with no changes to the react expo coding. 
```
loadStoredValues();

    const handleUrl = (event: { url: any }) => {
      const { url } = event;
      if (url.startsWith('mbtclient://axios')) {
        const code = new URL(url).searchParams.get('code');
        if (code) {
          // Handle the authorization code
          console.log('Authorization code:', code);
          setAuthorizationCode(code);
          // Navigate to another screen or perform other actions
          router.replace({ pathname: '/axios', params: { code } });
        }
      }
    };

    Linking.addEventListener('url', handleUrl);

    return () => {
      Linking.removeAllListeners('url');
    };
```

**Comment by omardlhz** [comment]
> @brentvatne I am having the same issue described in [expo/router#818](https://github.com/expo/router/issues/818) using expo router 3.4.8
> 
> A deep link brings opens an from the background but does take me to the route. It works if the app is in the not running state.
> 
> The warning I get:
> 
> ` WARN The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/configuring-links for more details on how to specify a linking configuration.`


@magiusdarrigo where you able to solve this issue? Im not facing the same. I was able to workaround it by using the workaround in the other thread, but still would like to find a solution.

Workaround in your root _layout.tsx:

```typescript
useEffect(function linkingWorkaround() {
    Linking.addEventListener("url", ({ url }) => {
      const match = url.match(new RegExp(`^myapp://(.*)`));
      if (match) {
        router.navigate(`/${match[1]}`);
      }
    });
  }, []);
```
