### ISSUE TITLE
[expo-sqlite] database stucks with select returns too much rows (data)

### ISSUE THREAD

**Issue by GaelCO** [expo/expo#27430]
### Minimal reproducible example

https://github.com/GaelCO/sqlite-stuck

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Hi,

"expo-sqlite" version: "13.2.2",

When I request with executeSql method in a readTransaction a select with lot of rows, the callbak or errorCallback never throws.
Moreover, all the database is stucked, until I restart the app.
This issue depends on device (not reproducted on my own phone with API Level 34), but I reproduct on a emulator with API Level 31. Perhaps, it's a memory issue

I have made a minimal reproductible sample. In the getStucks method, you can set a limit to verify the mecanism works with less rows. On my emulator, works with a 25000 limit, but not with 30000.

NB : In my project, I have never encountered this issue, until I update the expo-sqlite version. Previous prod version : 10.3.0 
I do not noticed this issue on iOS, but I don't make a lot of test on it.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 20221126.133621.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      expo-cli: 6.3.8
    Expo Workflow: managed

### Expo Doctor Diagnostics

Didn't find any issues with the project!

**Comment by GaelCO** [comment]
I didn't specify. The problem seems to occur during the query itself and not on the return of results.
Indeed, if I set a high offset (30000) with a low limit (100), the problem also occurs.

**Comment by Kudo** [comment]
hi there! could you share a repro for the sql queries? the newer expo-sqlite version re-implemented the code and try to align the implementation with ios. would be interesting how the change impacts to sql queries. that would be super helpful if you could share the queries you tried.

**Comment by GaelCO** [comment]
Hi,

The query is a simple select, but return lot of data. For example, if I don't return all column, the request is ok.

You can reproduce this issue with the repro project in the bug declaration. To reproduct, don't use an emulator or device with a recent android version or very large heap. I think it's link to the available memory for an app.

**Comment by NazarDevsMedia** [comment]
repo link is invalid / privat ? @GaelCO

**Comment by pavattt** [comment]
I'm experiencing a similar issue after upgrading from sdk 49 to 50. The issue is only present on Android. The first query runs, db hangs and no success or error callbacks are called. Tried dowgrading to expo-sqlite 11 on expo sdk 50, but no difference. iOS works fine.

**Comment by GaelCO** [comment]
Sorry for my reaction time, I just made the reprod repo public.
I update the expo-sqlite lib to 13.4.0. This issue still happen on an emulator with API Level 31.

**Comment by gpurbia** [comment]
Experiencing same issue on android with expo 50. Any findings ?

**Comment by thestretivibity** [comment]
You can actually solve this by executing this query right after you initialize your db
` 'PRAGMA cache_size=16384; PRAGMA encoding="UTF-8"; PRAGMA synchronous=NORMAL; PRAGMA temp_store=FILE;'`

You play with other parameters https://www.sqlite.org/pragma.html

**Comment by iuvabo** [comment]
In my case the suggested fix does not. I can reproduce the behaviour, when having large or nested requests in Expo 51. I tried changing the cache (the other settings are already set), but it's no difference. Does the suggested fix 

`'PRAGMA cache_size=16384; PRAGMA encoding="UTF-8"; PRAGMA synchronous=NORMAL; PRAGMA temp_store=FILE;'` 

work? I have some nested and large requests and use typeorm, so I'm not shure, if the problem is somewhere else. But in Expo 49 everything was working fine, on iOS and newer Android devices everything is ok. Older devices (Redmi Note) are just hanging/waiting forever.

**Comment by GaelCO** [comment]
Hi,
I have updated the repro example with latest expo-sqlite version : 14.0.3.
I still use the legacy implementation and this issue is still present.

For my own project, I workaround this issue with a limitation on the number of visible results (offset).
