### ISSUE TITLE
SHA-1 for file ..\node_modules\expo\AppEntry.js is not computed

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#2743]
### Environment

  Expo CLI 2.4.0 environment info:
    System:
      OS: Windows 7
      Terminal: Powershell & Command Prompt produce the same results

    Binaries:
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\PortableApps\Watchman\watchman.EXE

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/slapbox-57a5ea49-bace-412a-b2ab-abae4f1676c0.tar.gz

### Steps to Reproduce

`expo start` on the project results in:

```
SHA-1 for file ..\node_modules\expo\AppEntry.js is not computed
```

`yarn start` results in:

```
$ expo start
This command requires Expo CLI.
Do you want to install it globally [Y/n]?
```

But Expo CLI 2.4.0 is already installed.

### Expected Behavior

Application is packaged and served by my machine.

### Actual Behavior

Error message shown above.

### How to reproduce

No idea. This doesn't affect all of my Expo projects, and even the ones that are affected are not affected all of the time. **My projects that work 100% of the time are all Expo 30 and below, and the problem ones all use Expo 31, so that may be a key.**

**Comment by Slapbox** [comment]
Removing the `watchman` executable from my `path` may have resolved this. 

Because the issue is spotty in nature, I can't say for sure. I can say though that restarting Windows and reinstalling all node_modules did not resolve it.

**Comment by rupeshk** [comment]
I am facing the same issue. Removing watchman from the path solves this. However, this is not an ideal solution as react native requires watchman.

**Comment by vjpr** [comment]
Maybe related and with workaround: https://github.com/facebook/metro/issues/330
