### ISSUE TITLE
(Question) How to write file to internal storage ?

### ISSUE THREAD

**Issue by ardyfeb** [expo/expo#2744]
How to write file to internal storage such as `Download`, `DCIM`, `Pictures`, `Whatsapp`
The documentation only show how to write on app directory `/data/data/com.package.name`

I already post this question into forum but no answers https://forums.expo.io/t/can-i-write-file-to-internal-storage-android/16061

**Comment by sjchmiela** [comment]
Hey, @ardyfeb! I don't think it's currently possible to do. Judging by quick Internet search I think there are two problems:
- we don't use or expose `Environment` class which allows developers to get the external directories paths ([WhatsApp folder](https://stackoverflow.com/a/45657862/1123156), [DCIM folder](https://stackoverflow.com/questions/41782162/how-to-write-file-into-dcim-directory-exactly-where-camera-does), [Downloads folder](https://stackoverflow.com/a/7908446/1123156))
- we knowingly scope your apps permissions only to `cacheDir` and `filesDir` ([`FileSystemModule.permissionsForPath`](https://github.com/expo/expo/blob/7b68507eb02e400550e0b42122861ff11ea64406/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java#L134-L155)). I think we could relax these permissions when in standalone/ejected environment.

Thanks for submitting the issue! We'll keep track of it and try to implement in a not-so-distant future. 🙂

**Comment by ardyfeb** [comment]
> Hey, @ardyfeb! I don't think it's currently possible to do. Judging by quick Internet search I think there are two problems:
> 
> * we don't use or expose `Environment` class which allows developers to get the external directories paths ([WhatsApp folder](https://stackoverflow.com/a/45657862/1123156), [DCIM folder](https://stackoverflow.com/questions/41782162/how-to-write-file-into-dcim-directory-exactly-where-camera-does), [Downloads folder](https://stackoverflow.com/a/7908446/1123156))
> * we knowingly scope your apps permissions only to `cacheDir` and `filesDir` ([`FileSystemModule.permissionsForPath`](https://github.com/expo/expo/blob/7b68507eb02e400550e0b42122861ff11ea64406/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java#L134-L155)). I think we could relax these permissions when in standalone/ejected environment.
> 
> Thanks for submitting the issue! We'll keep track of it and try to implement in a not-so-distant future.

Thanks for you reply, i hope this feature will come in as soon as possible
