### ISSUE TITLE
Expo tries to pick up Android Emulator Info as an AVD device

### ISSUE THREAD

**Issue by atif089** [expo/expo#27440]
### Summary

On Windows 10, Expo tries to pick up Android Emulator Info as an AVD device.

This is what happens when I try to `run:android`

```
PS C:\Users\Atif\Desktop\voyago\infra\client> npx expo run:android         
env: load .env
env: export API_URL
› Opening emulator INFO    | Storing crashdata in: C:\Users\Atif\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.18.db, detection is enabled for process: 2512
Error: The emulator (INFO    | Storing crashdata in: C:\Users\Atif\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.18.db, detection is enabled for process: 2512) quit before it finished opening. You can try starting the emulator manually from the terminal with: C:\Users\Atif\AppData\Local\Android\Sdk/emulator/emulator @INFO    | Storing crashdata 
in: C:\Users\Atif\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.18.db, detection is enabled for process: 2512
Error: The emulator (INFO    | Storing crashdata in: C:\Users\Atif\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.18.db, detection is enabled for process: 2512) quit before it finished opening. You can try starting the emulator manually from the terminal with: C:\Users\Atif\AppData\Local\Android\Sdk/emulator/emulator @INFO    | Storing crashdata 
in: C:\Users\Atif\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.18.db, detection is enabled for process: 2512
    at stopWaitingAndReject (C:\Users\Atif\Desktop\voyago\infra\client\node_modules\@expo\cli\build\src\start\platforms\android\emulator.js:110:20)
    at ChildProcess.<anonymous> (C:\Users\Atif\Desktop\voyago\infra\client\node_modules\@expo\cli\build\src\start\platforms\android\emulator.js:121:13)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
````

This is what happens when I try to pick an android device

```
PS C:\Users\Atif\Desktop\voyago\infra\client> npx expo run:android -d
env: load .env
env: export API_URL
? Select a device/emulator »
>   INFO    | Storing crashdata in: C:\Users\Atif\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.18.db, detection is enabled for process: 6428 (emulator)
    Medium_Phone_API_33 (emulator)
```

Here is the output from my list avd command

```
C:\Users\Atif\AppData\Local\Android\Sdk\emulator>emulator.exe -list-avds
INFO    | Storing crashdata in: C:\Users\Atif\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.18.db, detection is enabled for process: 18092
Medium_Phone_API_33
```

It looks like expo is picking up an INFO message as a valid device. This error only started 2 days ago, so I'm not sure if that INFO message showed up previously or did it only start appearing in a new version of Android Emulator

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE        
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10227.8.2321.11479570
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.1
      expo: ~50.0.8 => 50.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: bare
```

### Minimal reproducible example

Hard to reproduce because it could be related to my own PC with a simple `npx run:android` command. I shared all the details in the summary above.

**Comment by ANTOSzbk** [comment]
Same issue here, fresh Android Studio and Expo installation on Macbook M3

**Comment by NorseGaud** [comment]
This exists for non-expo too. Seems like something Android team deployed has broken and forced us all to upgrade to it.

**Comment by NorseGaud** [comment]
Solution posted here: https://stackoverflow.com/a/78111618/1875932

**Comment by thomasamaddeo-genie** [comment]
> Solution posted here: https://stackoverflow.com/a/78111618/1875932

That did not work for me unfortunately :(

**Comment by NorseGaud** [comment]
@thomasamaddeo-genie , try back a few more versions. I installed a really old emulator version, then walked up each version until I saw the INFO log line again. I then reverted only by one version and the INFO log was gone again.

**Comment by thomasamaddeo-genie** [comment]
> @thomasamaddeo-genie , try back a few more versions. I installed a really old emulator version, then walked up each version until I saw the INFO log line again. I then reverted only by one version and the INFO log was gone again.

that worked. I went back to the latest `stable` emulator version (33.1.24) and no more info log when running `emulator -list-avds`.

hopefully a stable version 34 of the emulator will be released soon 👍 

if it helps anybody, [here's the link](https://developer.android.com/studio/emulator_archive#:~:text=To%20manually%20install%20a%20select%20version%20of%20emulator%20on%20Studio,in%20the%20package.xml%20file.) to the steps to follow to revert to an older emulator 👍

**Comment by atif089** [comment]
Thanks for sharing the solution, everyone. Here's a nice little `.bat` script (written by Mistral) that does the job. The script assumes that the SDK is saved at its default location `%LOCALAPPDATA%/Android/Sdk`

```bat
@echo off
setlocal

:: Change to the specified directory
cd /D "%LOCALAPPDATA%/Android/Sdk"

:: Rename emulator to emulator_original
ren "emulator" "emulator_original"

:: Download the zip file and display a message
powershell -Command "& { $source = 'https://redirector.gvt1.com/edgedl/android/repository/emulator-windows_x64-11237101.zip'; $destination = 'emulator.zip'; Write-Host 'Downloading emulator update...'; Start-BitsTransfer -Source $source -Destination $destination; Write-Host 'Download complete.' }"

:: Extract the zip file
powershell -Command "Expand-Archive -Path 'emulator.zip' -DestinationPath '.'"

:: Delete the zip file
del "emulator.zip"

endlocal
```

**Comment by zeldaababil19** [comment]
> Thanks for sharing the solution, everyone. Here's a nice little `.bat` script (written by Mistral) that does the job (using Android Emulator (33.1.24) Stable Dec 2023). The script assumes that the SDK is saved at its default location `%LOCALAPPDATA%/Android/Sdk`
> 
> ```batchfile
> @echo off
> setlocal
> 
> :: Change to the specified directory
> cd /D "%LOCALAPPDATA%/Android/Sdk"
> 
> :: Rename emulator to emulator_original
> ren "emulator" "emulator_original"
> 
> :: Download the zip file and display a message
> powershell -Command "& { $source = 'https://redirector.gvt1.com/edgedl/android/repository/emulator-windows_x64-11237101.zip'; $destination = 'emulator.zip'; Write-Host 'Downloading emulator update...'; Start-BitsTransfer -Source $source -Destination $destination; Write-Host 'Download complete.' }"
> 
> :: Extract the zip file
> powershell -Command "Expand-Archive -Path 'emulator.zip' -DestinationPath '.'"
> 
> :: Delete the zip file
> del "emulator.zip"
> 
> endlocal
> ```

thank youu very much

**Comment by niu-dali** [comment]
https://github.com/facebook/react-native/issues/43320#issuecomment-2011072921

这个方法很好用，下载这个压缩包之后，把压缩包解压到你的 \android\sdk 目录里，替换掉原来的emulator文件夹，然后重启电脑就可以了。👍👍👍

This method is very easy to use, after downloading this package, extract the package into your \android\sdk directory, replace the original emulator folder, and then restart the computer.👍👍👍

**Comment by esnosy** [comment]
Thanks!
https://developer.android.com/studio/emulator_archive

**Comment by esnosy** [comment]
btw is there away to "pin" the android emulator version and prevent updating it?

**Comment by atif089** [comment]
It looks like this change made it through stable builds and I'm not sure if they plan to revert it. Would it make sense to ignore the  "INFO    | Storing crashdata line" while parsing stdout in order to get the default emulator device?

**Comment by Sebastianmueller22** [comment]
Happens for me on API 34 downloaded via SDKmanager on windows 10. Quite a pain honestly

**Comment by atif089** [comment]
@Sebastianmueller22 started happening to me again. Just append `-d` in your expo command (`expo run:android -d`) and it will give you a choice to select the emulator.

**Comment by duraz0rz** [comment]
For those running across this, I filed an issue on Google's Issue Tracker: https://issuetracker.google.com/issues/359420116

In the meantime, `npx expo run:android -d` is a good workaround if you don't want to downgrade. Or hit `shift+a` if you already have a dev server running.
