### ISSUE TITLE
Expo Dev Client Notification Issue

### ISSUE THREAD

**Issue by Knaackee** [expo/expo#27451]
### Summary

I've been experiencing an issue exclusively in the development client where tapping on any notification, whether local or remote, causes the entire app to reload. This behavior does not occur in Expo Go or in full builds, which function as expected.

Detailed Issue Description:
In the development client, every time I tap a notification, the app undergoes a full reload instead of simply handling the notification and directing me to the relevant screen or action. The console logs the following message during this process:

> Android Bundled 86ms (.... path ....).

This suggests that the app is re-bundling or somehow restarting upon notification interaction, which disrupts the development workflow and testing processes.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~3.3.9"

"expo-updates" not installed.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.1, 34.0.0
        System Images: android-33 | Google Play Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ~50.0.8 => 50.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: managed

### Reproducible demo

https://github.com/Knaackee/expo-dev-client-push-notification-issue

**Comment by Knaackee** [comment]
@marecikl @ https://github.com/expo/expo/issues/27240#issuecomment-1978435177

```
I disabled a new launch feature with:

[ "expo-dev-launcher", { "launchModeExperimental": "launcher" } ]

added to "plugins" list of app.json.
```

**Comment by sraut1** [comment]
Also facing the same issue on Android

**Comment by last-core** [comment]
I have the same issue, is this still not fixed?

**Comment by kokezab** [comment]
Expo often seems to be introducing more issues than solutions...

**Comment by samvoults** [comment]
Same problem here.

**Comment by rawr-code** [comment]
Same problem here...

**Comment by antidiestro** [comment]
Same here.

**Comment by dpuckett** [comment]
Glad i'm not the only one and this is a new issue! Please fix!

**Comment by michalko** [comment]
+1

**Comment by mithun-bostontech** [comment]
Iam also facing same issue ,no logs anyone know any workaround

**Comment by marecikl** [comment]
The solution is up there, add to "plugins" field of app.json:

`[ "expo-dev-launcher", { "launchModeExperimental": "launcher" } ]`
