### ISSUE TITLE
SEO Injection

### ISSUE THREAD

**Issue by pavankumar5571** [expo/expo#27463]
### Minimal reproducible example

https://github.com/pavankumar5571/sample.git

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Hi, I'm trying to build a website with Static Rendering which contains dynamic meta data, while building the application generated HTML pages have the static meta tags.When i tried to update the meta tags dynamically data is not intejecting to source code.

### Environment

yarn install

npx expo export -p web

npx serve@latest dist

**Comment by marklawlor** [comment]
I'm am unable to replicate your issue, but I might be misunderstanding it as well.

When I run `npx expo export -p web` under `dist/index.html` and `dist/second.html` I can correctly see that the meta tags have been injected.

When I run the application, if I disable JavaScript `http://localhost:3000` has the title "Home" and when I re-enable JavaScript, after the first render the title is changed to "Pavan Title".

Note that `useEffect` and state updates do not run during static-rendering, this maybe the source of your confusion. I'm going to close this issue and if I have misunderstood please respond with an updated issue description.

**Comment by marklawlor** [comment]
If you are asynchronously fetching the routes title with static rendering, you should be performing that logic with `generateStaticParams` and not `useEffect()`

https://docs.expo.dev/router/reference/static-rendering/#generatestaticparams
