### ISSUE TITLE
Expo-av 

### ISSUE THREAD

**Issue by misael1976** [expo/expo#27478]
### Summary

I am trying to play an mp3 file and immediately when it ends create an alert.
in the link attached below the alert is shown several seconds after the audio finished.
I can see here that: 
Audio file when ended does not change the boolean value of didJustFinish or isPlaying, after several seconds depending on the size of the mp3 file  the didJustFinish and isPlaying  conditions are set to true for didJustFinish and false for is playing.
there is like a gap where the audio is still loaded.

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.2 - /opt/homebrew/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.4.0 - ~/node_modules/.bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/misaeljimenez/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.3.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/misael1976/StickerSmash

**Comment by ritikakhelwar** [comment]
here's the code for _onPlaybackStatusUpdate , you can check it's working fine

async function playSound() {
    setSoundIsPlaying("Loading audio")
    const { sound} = await Audio.Sound.createAsync(
      { uri: itemData?.media },
      { shouldPlay: true },
      _onPlaybackStatusUpdate  
    )
    setSound(sound);
console.log("soundsoundsoundsoundsound",sound);

    await sound.playAsync();
    setSoundIsPlaying("Playing sound")
  }

  const _onPlaybackStatusUpdate = status => {
    console.log("statusstatusstatus",status);
    if(status?.isPlaying){
      setSoundStatus(status);
    }
    if (status.isLoaded) {
      setSoundStatus(status);
      if (status.didJustFinish && !status.isLooping) {
        setSoundStatus({status:null,icon:"play"})
       console.log("Sound is finished");
       setSoundIsPlaying("Play audio")
      }
    } else {
      if (status.error) {
        console.log(`FATAL PLAYER ERROR: ${status.error}`);
      }
    }
  };
