### ISSUE TITLE
Expo Router renderRouter override fake timers

### ISSUE THREAD

**Issue by HiroNonoyama** [expo/expo#27484]
### Summary

https://github.com/expo/expo/blob/29048b76e6c5fedde7b9cf38ef32861706c4b4f0/packages/expo-router/src/testing-library/index.tsx#L75

`jest.useFakeTimers()` override previously defined fake timers
This breaks test cases which depends on Components that calls `new Date()`

### Environment

```
expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 13.0
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
    Yarn: 3.5.0 - ~/.volta/tools/image/yarn/3.5.0/bin/yarn
    npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
    Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  npmPackages:
    babel-preset-expo: ^9.5.0 => 9.7.0
    expo: ^49.0.0 => 49.0.11
    expo-router: ^2.0.0 => 2.0.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-native: 0.72.6 => 0.72.6
    react-native-web: ~0.19.6 => 0.19.9
  Expo Workflow: managed
```

**Comment by marklawlor** [comment]
@HiroNonoyama I need to revert this change. When testing on React Native 0.74-rc, multiple React Navigation navigators are logging errors in Jest about performing a state update after the test has ended. I'm not sure why this is happening, it might require an upstream change, but for now we're going to re-add the fakeTimers back in.

**Comment by HiroNonoyama** [comment]
@marklawlor 
Understood. Thank you for your consideration.

**Comment by sgrowe** [comment]
@marklawlor would you mind re-opening this issue then please if the fix was reverted?

**Comment by miso-belica** [comment]
This is really crazy. I am migrating to expo-router and it took me a few hours to find out why all tests are stuck and no promises are resolving. I have to do this as a workaround:
```ts
  try {
    return renderRouter('./src/app', {...renderOptions, initialUrl: route.name});
  } finally {
    jest.useRealTimers(); // https://github.com/expo/expo/issues/27484
  }
```

**Comment by dotnich-io** [comment]
@marklawlor is there any update on what's causing this? We got bit by this exact issue today and it caused *so* much head-scratching until we realised Expo was overriding our mocked system time when we called `renderRouter`

**Comment by miso-belica** [comment]
@dotnich-io In the end I had to remove it via https://github.com/ds300/patch-package because nothing else was effective against it.

**Comment by matthieugicquel** [comment]
Many codebases already have fake timers enabled, with `now` set to some known value, and maybe other configs. I just spent an hour debugging why `Date.now()` was not the value I expected 😬.

@marklawlor Would you consider adding a check on whether fake timers are already enabled before overriding the config?

Something like:

```ts
if(!Date.isFake /* jest sets this property */) {
  jest.useFakeTimers()
}
```

I can open a PR if that's helpful :) 

_Side note: In my opinion `renderRouter` should not mess at all with fake timers, which have wide implications, and it would be better to just document the requirement and log a warning if they're not enabled, but I can understand if you want to keep things "just working" magically..._

**Comment by tlmader** [comment]
If you are trying to use `jest.setSystemTime()`: https://github.com/expo/expo/pull/34388#issuecomment-2788206476

**Comment by sumnerwarren** [comment]
This issue should be reopened. Like others above, I just spent about an hour trying to figure out why my known fake time was being overwritten. I'm now fixing the issue with `patch-package`. Would love to see #34388 merged.
