### ISSUE TITLE
Include transitive deps in autolinking

### ISSUE THREAD

**Issue by iketw** [expo/expo#27481]
### Summary

I have a package that has a peer dependency (I can also be a dependency) of a native package, say react-native-mmkv.

When I run `npx expo install my-package` I want the mmkv package to also be autolinked in the app without devs having to explicitly add the `react-native-mmkv` package as a dependency.

I defined an `expo-module.config.js` file in my-package to include both platforms but when installing `my-package` I still bet an error about mmkv not found.

### What platform(s) does this occur on?

Android, iOS

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/dalmendraytw/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 29, 30, 31, 32, 33, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-29 | ARM 64 v8a, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 3.8.0
    Expo Workflow: bare

### Minimal reproducible example

You can run `npx expo install @thirdweb-dev/react-native@0.0.0-dev-3bf4dc1-20240306220642` in an android app. I'd expect all peer dependencies to be installed in the app

**Comment by brentvatne** [comment]
autolinking of libraries like react-native-mmkv is provided by [react-native-community autolinking](https://github.com/react-native-community/cli/blob/main/docs/autolinking.md), and expo modules autolinking is for expo modules. i would suggest opening this feature request on https://github.com/react-native-community/cli

i agree this would be a valuable feature!

**Comment by iketw** [comment]
> autolinking of libraries like react-native-mmkv is provided by [react-native-community autolinking](https://github.com/react-native-community/cli/blob/main/docs/autolinking.md), and expo modules autolinking is for expo modules. i would suggest opening this feature request on https://github.com/react-native-community/cli
> 
> i agree this would be a valuable feature!

@brentvatne thanks for your reply. There's already a discussion going on in their repo: https://github.com/react-native-community/cli/pull/2054

About expo modules, if I build an expo-module which has the mmkv package as a dependency and a dev runs `npx expo install my-package` will it also link the mmkv package?

**Comment by brentvatne** [comment]
it won't because it only links expo modules. if mmkv were built as an expo module, then it would be linked transitively

**Comment by iketw** [comment]
> it won't because it only links expo modules. if mmkv were built as an expo module, then it would be linked transitively

@brentvatne thanks for your response. How does expo manages to transitively link expo modules?

If I have an npm package A that has expo native modules as dependencies and I install package A in a mobile app, then the expo modules are auto-linked, how is this transitive auto-linking done?

**Comment by santoriggio** [comment]
Has anyone found a solution? I'm encountering the same issue with dependencies in my packages that needs to be installed from the user to be linked after the installation of the package:
```bash
npx expo install <...dependencies>
```
I've noticed that even Expo-router has dependencies outside of the Expo module ecosystem, such as react-navigation. How do they automatically link react-navigation?

I would like to autolink the dependencies of my packages in my projects without the command:
```
npx expo install react-native-mmkv expo-localization
```
