### ISSUE TITLE
Expo image blinking on navigation

### ISSUE THREAD

**Issue by arasrezaei** [expo/expo#27482]
### Minimal reproducible example

https://snack.expo.dev/@arasrezaie/expo-image-blinking

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Hi there,
when navigating back from the screen which has expo image, there is a blinking ,overlay component disapear and expo image is still there, while this is not the case when using RN Image, the overlay and image disapear togheter
i found out issue happens when you set ZIndex to OverLay component
simply play the snack and test it your self.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20220821.200817.0 - E:\Software\Watchman\bin\watchman.EXE
    npmPackages:
      expo: ^50.0.7 => 50.0.7
      react: 18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ^0.19.10 => 0.19.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check Expo config (app.json/ app.config.js) schema
Unexpected error while running 'Check Expo config (app.json/ app.config.js) schema' check:
FetchError: invalid json response body at https://exp.host/--/api/v2/project/configuration/schema/50.0.0 reason: Unexpected token '<', "
<html><hea"... is not valid JSON
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.8.0
Found invalid:
  @expo/config-plugins@7.7.0
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/metro-config@~0.17.1
Found invalid:
  @expo/metro-config@0.17.0
  (for more info, run: npm why @expo/metro-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

The following packages should be updated for best compatibility with the installed expo version:
  expo@50.0.7 - expected version: ~50.0.8
  expo-dev-client@3.3.8 - expected version: ~3.3.9
  expo-router@3.4.7 - expected version: ~3.4.8
  react-native-gesture-handler@2.15.0 - expected version: ~2.14.0
  react-native-reanimated@3.7.1 - expected version: ~3.6.2
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

**Comment by lukmccall** [comment]
Hi @arasrezaei, I believe the behavior you described is actually expected. Based on my findings, it occurs in both implementations and is not related to image packages. The blinking is caused by the order in which views are deallocated when navigating between screens.

I have created a short screen recording of the Android emulator to demonstrate that the overlay disappears for both expo-image and react native.

https://github.com/expo/expo/assets/9578601/69023144-12c0-4f0a-b278-ee49923ed62f

You can easily change that by moving the overlay in the view hierarchy below the image component.

Replace:
```jsx
<View style={{ flex: 1 }}>
  <Overlay />
  <RNImage source={SOURCE} style={{ width: "100%", height: 300 }} />
</View>
```
with:
```jsx
<View style={{ flex: 1 }}>
  <RNImage source={SOURCE} style={{ width: "100%", height: 300 }} />
  <Overlay />
</View>
``` 

After changing the order, everything should work as expected:

https://github.com/expo/expo/assets/9578601/81e4fada-8cea-42f6-9c9a-085a50860b8e

**Comment by arasrezaei** [comment]
Thanks
