### ISSUE TITLE
Password input is not masked

### ISSUE THREAD

**Issue by pietrodicaprio** [expo/expo#27480]
### Summary

Running `npx expo start` without a prior `npx expo login` (on a new system installation, for example) leads you to insert a non masked password:
![image](https://github.com/expo/expo/assets/37634431/ecce7828-02c9-4612-8478-c76290627369)
the password is masked executing `npx expo login` instead.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.8 => 50.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: managed

### Minimal reproducible example

run `npx expo start` in an environment where there is no valid expo session available

**Comment by brentvatne** [comment]
hi @pietrodicaprio! this may be an issue with your shell. it is properly masked for me: 

<img width="1136" alt="image" src="https://github.com/expo/expo/assets/90494/d85fe62f-7617-4bb3-8a7d-c6cc5ad9ed1d">
