### ISSUE TITLE
[Android][expo-web-browser] Signing in via another app will not redirect back to the initial app

### ISSUE THREAD

**Issue by theunreadable** [expo/expo#27499]
### Minimal reproducible example

```
await WebBrowser.openAuthSessionAsync(
    "the_auth_link", 
    "the_redirect_to_main_app_link"
);
```

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hi, there's a misbehaviour with the `expo-web-browser` that we noticed that it happens on Android only whenever the user is trying to sign in in our app using a 3rd party provider that is installed as an app on the same device. To reproduce this, the user will require to have both apps installed on its android device:

1. InitialApp - the main app the user will use
2. AuthApp - the mobile app of the 3rd party provider

On the login page of the main app, there is an 'Login with 3rd party' button which should allow the user to authenticate and start its session. When the user tries to login using the 3rd party provider and the AuthApp is installed on the same device, instead of opening an in app browser window, the 3rd party app will open and when the user submits the form, it won't get redirected back to the initial app, but remain in the AuthApp.

This is only happening on Android because on iOS, the auth page will be open in the browser of the app. As implementation, we are using this:

```
await WebBrowser.openAuthSessionAsync(
    "the_auth_link", 
    "the_redirect_to_main_app_link"
);
```

Ideally, we would like to open the auth page in the browser of the app instead of using the AuthApp, just like it is happening on the iOS.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1
      expo: ^50.0.7 => 50.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.9
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare

**Comment by Ignaciomendezp** [comment]
Any updates? Same issue

**Comment by theunreadable** [comment]
@Ignaciomendezp yes, check this https://github.com/expo/expo/issues/27500
