### ISSUE TITLE
Facebook Login for Android Not Working for Detached Expo App

### ISSUE THREAD

**Issue by voyage11** [expo/expo#275]
Hi,
My current react native project is using ExpoKit (exp detach), I have trouble making the Facebook Login working for Android. It is working fine on iOS. 

I have added the Facebook login using the following code:-

```
    Expo.Facebook.logInWithReadPermissionsAsync(FACEBOOK_APP_ID, {
      permissions: ['email', 'public_profile'],
    }).then((res) => {
    });
```
There isn't much information on the documentation (https://docs.expo.io/versions/v17.0.0/sdk/facebook.html) related to the configurations of the **build.gradle**, **MainApplication.java**, **MainActivity.java**, **AndroidManifest.xml** for the Detached expo app. 

I tried a few methods by settings the Android Java code by following other libraries (eg: https://github.com/magus/react-native-facebook-login/blob/master/android/README.md) But nothing works so far. 

Any help would be appreciated. Thanks.

**Comment by nikki93** [comment]
@voyage11 wanna jump on slack.expo.io and have a conversation about this? I'm "nikki" on that slack.

**Comment by voyage11** [comment]
I actually have solved the issue myself about a week ago. I added some codes in `AndroidManifest.xml` and `string.xml`. I believe it was a permission issue. 

It would be helpful if the documentation for the Expo Facebook Login includes the step by step on how to setup the Facebook permission on both the iOS and Android.

**Comment by TheMightyPenguin** [comment]
hey @voyage11 what did you add to those files?
