### ISSUE TITLE
npx create-expo-app AwesomeProject

### ISSUE THREAD

**Issue by TheCocasio** [expo/expo#27501]
### Summary

Hello, when I try to create a project I get an error and I can't launch the test project.

To repeat the error:
npx create-expo-app AwesomeProject

Logs:

root@student:/home/student# npx create-expo-app AwesomeProject

cd AwesomeProject
npx expo start
Need to install the following packages:
create-expo-app@2.1.1
Ok to proceed? (y) y
(node:19069) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Downloaded and extracted project files.
> npm install
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

added 1159 packages, and audited 1160 packages in 1m

65 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd AwesomeProject
- npm run android
- npm run ios # you need to use macOS to build the iOS project - use the Expo app if you need to do iOS development without a Mac
- npm run web
Starting project at /home/student/AwesomeProject
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RegExpStringIterator.next (<anonymous>)
    at Function.from (<anonymous>)
    at _searchLast (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:5:25)
    at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:12:40)
    at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:38:12)
    at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:38:12)
root@student:/home/student/AwesomeProject#

### What platform(s) does this occur on?

Web

### SDK Version

2.1.1

### Environment

root@student:/home/student/AwesomeProject# npx expo-env-info
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 21.7.0 - /home/student/node_modules/.bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.5.0 - /home/student/node_modules/.bin/npm
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: managed

root@student:/home/student/AwesomeProject#

### Minimal reproducible example

To repeat the error:
npx create-expo-app AwesomeProject

**Comment by brentvatne** [comment]
```
Starting project at /home/student/AwesomeProject
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at RegExpStringIterator.next ()
at Function.from ()
at _searchLast (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:5:25)
at _interpolate (/home/student/AwesomeProject/node_modules/dotenv-expand/lib/main.js:12:40
```

this looks like there might be some issue with a .env file on your machine. it's hard to say without a reproducible example or more information. i can confirm that using the same version of node/npm, i am able to run a new project just fine.

can you try running `EXPO_DEBUG=* npm run web` and sharing that output?
