### ISSUE TITLE
Expo Calendar Recurrence Rule not being created

### ISSUE THREAD

**Issue by nathanKramer** [expo/expo#27513]
### Minimal reproducible example

https://github.com/nathanKramer/expo-calendar-bug-report

### What platform(s) does this occur on?

ios simulator (haven't tried others)

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm trying to create a calendar event with a recurrence rule.

#### Expected

I expected a recurring event to be created.

#### Outcome

* The calendar event is created ✅ 
* The calendar event does not have a recurrence rule / does not recur ❌ 

#### Notes

The recurrence rule API doesn't seem to work, I have followed the documentation and am using typescript with valid types.
My reproduction example is in javascript but the types are correct.

It seems possible that this is user error however I have followed the documentation and there is nothing to indicate I am doing anything wrong.

If I am missing something in my event payload perhaps the documentation should be updated?

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/nathankramer/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
Running 12 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by behenate** [comment]
Hi! In [this](https://github.com/nathanKramer/expo-calendar-bug-report/blob/54fdc0371751db8db8d4d0f2afdbd6020d332636/App.js#L24) spot you should use `Calendar.Frequency.WEEKLY` instead of "WEEKLY" string. 
This should've been caught by Typescript, but there were some type-safety issues which will be resolved in https://github.com/expo/expo/pull/27777.

**Comment by nathanKramer** [comment]
Ahh, thank you!
