### ISSUE TITLE
Unexpected end of stream on <dev-client server>

### ISSUE THREAD

**Issue by linonetwo** [expo/expo#27536]
### Summary

Basically same as https://github.com/expo/expo/issues/22668

See it for minimal repo

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~3.3.9"
"expo": "50.0.11",
    "expo-application": "5.8.3",
    "expo-background-fetch": "11.8.1",
    "expo-barcode-scanner": "12.9.3",
    "expo-camera": "14.0.6",
    "expo-clipboard": "5.0.1",
    "expo-device": "5.9.3",
    "expo-file-system": "16.0.8",
    "expo-haptics": "12.8.1",
    "expo-localization": "14.8.3",
    "expo-notifications": "0.27.6",
    "expo-share-intent": "^1.0.1",
    "expo-sharing": "11.10.0",
    "expo-sqlite": "13.3.0",
    "expo-status-bar": "1.11.1",
    "expo-task-manager": "11.7.2",

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22635
    Binaries:
      Node: 20.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: 50.0.11 => 50.0.11
      react: 18.2.0 => 18.2.0
      react-native: 0.73.5 => 0.73.5
    Expo Workflow: bare

### Reproducible demo

https://github.com/expo/expo/issues/22668

**Comment by keerthi133-sudo** [comment]
Need validation

**Comment by brentvatne** [comment]
it looks like the other issue was marked as completed: https://github.com/expo/expo/issues/22668#issuecomment-1566743288

this issue isn't actionable in its current form, i'm inclined to believe this is either related to your network or configuration in some way. try using a tunnel connection.
