### ISSUE TITLE
Android .apk files always use the `production` environment-variables.

### ISSUE THREAD

**Issue by 7dp** [expo/expo#27540]
### Minimal reproducible example

https://github.com/7dp/expo-env-vars

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Hi.
I have a brand new Expo project bootstrapped using `npx create-expo-app` command.
I have added Development and Production environment-variables to it (`.env`, `.env.development`, and `.env.production` files).
Then i try to run it on my Android device, both Development and Production env loaded on the app perfectly.
Then i try to build an apk of my Development environment. I try to run:
```bash
cd android; NODE_ENV=development ./gradlew assembleRelease; cd ..;
```
The apk is generated succesfully and i installed it to my Android device. 
I opened it, But why the app is using the Production environment, and not the Development environment?

Are my assembleRelease command wrong?
Could you enlighten me on this?

Thank you, and any help would be appreciated.

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.08.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/wicakradityo/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment]
hi there! i recommend reading this post for more information: https://expo.dev/blog/what-are-environment-variables

other questions like this are well suited for https://chat.expo.dev/

**Comment by 7dp** [comment]
Thanks for replying Brent!
I have carefully read the Kadi's article you mentioned above, but for my specific use case there's no explanation about the thing that i was looking for 😔.

All i want is to have separated Production and Development envs that i can switch between the two flexibly, either when i running it to a device or compiling it as .apk or .ipa .

I appreciate further help from the Expo team. Thanks.

**Comment by 7dp** [comment]
Some question, do `eas.json` file is required for running my Expo app (that uses multi-variants) on Android?
Expo docs is good but it sometimes overwhelming, because basic things i expect is not covered enough.
Sorry for pinging you here @brentvatne , but could you enlighten me on this?

**Comment by brentvatne** [comment]
@7dp - you should re-generate the android directory with prebuild using the env vars of your choice.

**Comment by benomzn** [comment]
> @7dp - you should re-generate the android directory with prebuild using the env vars of your choice.
> 
> so if you use `APP_VARIANT` and define that in **eas.json** and use that in **app.config.js**, then that will generate the build for the appropriate variant as outlined on https://docs.expo.dev/build-reference/variants/
> 
> if you want to run locally with `npx expo prebuild` / `npx expo run` then be sure to set the `APP_VARIANT` env var before running prebuild/run

I have a question, why if I set the NODE_ENV variable before run "npx expo run:android --variant Release", it has no effect until I run "npx expo prebuild -c", but for iOS I don't need run "npx expo prebuild -c" before, I just run "NODE_ENV=production/development npx expo run:ios --configuration Release" and it works perfect. 

When I run the iOS command, I always see this log: "Bundler cache is empty, rebuilding (this may take a minute)", even If I didn't clean cache (npx expo start -c for example), but in Android, after the first build, this log never appears again.
