### ISSUE TITLE
Expo Router stuck at Splash Screen

### ISSUE THREAD

**Issue by shoooe** [expo/expo#27543]
### Minimal reproducible example

https://github.com/shoooe/expo-router-splash-screen-issue

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Simply created a project using `bunx create-expo-app@latest --template tabs@50`
and then run `bun run start -c`.

This is the result:
<img width="596" alt="Screenshot 2024-03-09 at 17 24 28" src="https://github.com/expo/expo/assets/733227/7e752fb2-f00c-4c6d-8dba-a352539336e7">

No errors in the logs:
<img width="755" alt="Screenshot 2024-03-09 at 17 25 30" src="https://github.com/expo/expo/assets/733227/85ebb339-1ad7-4544-a819-dbfd727bd6dd">

The same exact thing happens if I open via QRCode on an Android device.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.5 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 6.2.1
    Expo Workflow: managed

**Comment by marklawlor** [comment]
I'm unable to replicate your issue and we have not received any other reports of this issue (an issue of this scale would definitely have many reports). Is there any more information that you can provide?

Couple of possible cases off the top of my head:

- This could be a dependency issue, does this occur with other package managers? 
- Is this isolated to Expo Router apps, do the other Expo templates work correctly? 
- Do you have special characters in your folder structure (including your home directory). For example does your home folder include any unicode?
- Do you get an errors when tryin got run on `web` or when exporting?

**Comment by shoooe** [comment]
> This could be a dependency issue, does this occur with other package managers?
It seems a Bun specific issue.

> Is this isolated to Expo Router apps, do the other Expo templates work correctly?
Yup, it works correctly (even in Bun) without using expo router.

> Do you have special characters in your folder structure (including your home directory). For example does your home folder include any unicode?
Nope. I just have an `app/index.tsx` file in my specific case.

> Do you get an errors when tryin got run on web or when exporting?
Nope.

> I'm unable to replicate your issue and we have not received any other reports of this issue (an issue of this scale would definitely have many reports)
Were you not able to replicate the issue using the latest version of Bun? It might be an M1 Mac specific issue then maybe.

**Comment by shoooe** [comment]
Funnily enough, this template instead works just fine: `bunx create-expo-app -e with-router-tailwind`

**Comment by shoooe** [comment]
Ok, so removing `node_modules` and just running `bun install` and `bun run start -c` solved the issue for me. I could have sworn I had tried that before but apparently not.
Sorry for opening this ticket and wasting everybody's time. 🙏
