### ISSUE TITLE
[expo-image-picker] Cropped image returns null for fileName and filesize 

### ISSUE THREAD

**Issue by AounNaqvi173** [expo/expo#27554]
### Minimal reproducible example

https://github.com/AounNaqvi173/image-picker-example

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

expo-image-picker returns null value against fileName and filesize for the edited image. When the allowsEditing is false it works as expected and returns the proper value, I have tested it on Android both a real device and the simulator. See the video for quick demo

https://github.com/expo/expo/assets/75715090/95d96ac0-a200-4a65-b797-71279c1f5619

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11076708
    npmPackages:
      expo: ~50.0.11 => 50.0.11
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    Expo Workflow: managed

### Expo Doctor Diagnostics

 Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by edwardAgileLab** [comment]
they got it fixed here https://github.com/expo/expo/pull/27293, stay tuned

**Comment by AounNaqvi173** [comment]
> they got it fixed here #27293, stay tuned
They only fixed the inconsistent naming in that PR. I think this issue is different I am getting values against them when allowsEditing is false and null when it's true. But let's just wait for the next release

**Comment by nimeshmaharjan1** [comment]
bro this is a huge issue and its already been a month ? hello

**Comment by AounNaqvi173** [comment]
this issue has been resolved , upgrade to the latest expo version
