### ISSUE TITLE
Now I'm required to change build number

### ISSUE THREAD

**Issue by MariuzM** [expo/expo#27553]
### Summary

Before i was ignoring this one because i have noticed that when building locally and pushing via EAS my build numbers always increment, but now all of the sudden I'm getting error that i need to change build number. 

So there is option in EAS json to autoIncrement but i can't use that option because i have app.config.ts.

### SDK Version

50

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/dev/node-v20.11.0/bin/node
      Yarn: 1.22.21 - ~/dev/node-v20.11.0/bin/yarn
      npm: 10.2.4 - ~/dev/node-v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.4.0
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/MariuzM/expo-starter

**Comment by brentvatne** [comment]
use the remote version source: https://docs.expo.dev/build-reference/app-versions/#remote-version-source - this doesn't require changing the value in your app.json and generally is much better because it is one global value that is stored on EAS so it works well across branches
