### ISSUE TITLE
dev-client crashing: java.lang.IllegalStateException: DevelopmentClientController was initialized. 

### ISSUE THREAD

**Issue by HugoLiconV** [expo/expo#27559]
### Summary

Out of nowhere, I started getting errors when opening the development client on my Android devices, the installation works without any issue but when I open the app it crashes. 
The crash only happens on the dev client, when I build the APK and run it it works perfectly.

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~2.2.1",
"react-native": "0.71.14",
"expo": "~48.0.18",
"expo-updates": "~0.16.4",

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ~48.0.18 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
    npmGlobalPackages:
      eas-cli: 7.3.0
      expo-cli: 6.1.0
    Expo Workflow: bare

### Reproducible demo

AndroidManifest.xml
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="mx.qr.reader">
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.NFC"/>
  <queries>
    <intent>
      <action android:name="android.intent.action.VIEW"/>
      <category android:name="android.intent.category.BROWSABLE"/>
      <data android:scheme="https"/>
    </intent>
  </queries>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="true" android:theme="@style/AppTheme" android:usesCleartextTraffic="true">
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>
    <meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="@string/expo_runtime_version"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://u.expo.dev/..."/>
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:exported="true" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="mx.qr.reader"/>
        <data android:scheme="exp+qr-reader"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false"/>
  </application>
</manifest>
```
app.config.js
```javascript
import 'dotenv/config';

const environmentVariables = {
  apiUrl: process.env.API_URL,
  posthogApiKey: process.env.POSTHOG_API_KEY,
  appEnv: process.env.APP_ENV ?? 'development',
  apiKey: process.env.API_KEY,
};

export default {
  expo: {
    name: 'qr-reader',
    slug: 'qr-reader',
    owner: 'hugo',
    version: '1.0.0',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'light',
    updates: {
      url: 'https://u.expo.dev/...',
      enabled: false,
    },
    plugins: [
      ['expo-updates'],
      [
        'expo-barcode-scanner',
        {
          cameraPermission: 'Allow $(PRODUCT_NAME) to access camera.',
        },
      ],
      [
        'expo-location',
        {
          locationAlwaysAndWhenInUsePermission:
            'Allow $(PRODUCT_NAME) to use your location.',
        },
      ],
      'expo-localization',
      'sentry-expo',
    ],
    splash: {
      image: './assets/splash.png',
      resizeMode: 'contain',
      backgroundColor: '#ffffff',
    },
    assetBundlePatterns: ['**/*'],
    ios: {
      supportsTablet: true,
    },
    android: {
      runtimeVersion: '1.0.0',
      package: 'mx.qr.reader',
      versionCode: 1,
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: '#ffffff',
      },
    },
    web: {
      favicon: './assets/favicon.png',
    },
    hooks: {
      postPublish: [
        {
          file: 'sentry-expo/upload-sourcemaps',
          config: {
            organization: 'hugo',
            project: 'qr-reader',
            authToken: process.env['SENTRY_AUTH_TOKEN'],
          },
        },
      ],
    },
    extra: {
      eas: {
        projectId: '...',
      },
      ...environmentVariables,
    },
  },
};

```

### Stacktrace (if a crash is involved)

```
03-12 00:07:09.795 14180 14180 E AndroidRuntime: FATAL EXCEPTION: main
03-12 00:07:09.795 14180 14180 E AndroidRuntime: Process: mx.qr.reader, PID: 14180
03-12 00:07:09.795 14180 14180 E AndroidRuntime: java.lang.RuntimeException: Unable to create application mx.qr.reader.MainApplication: java.
lang.IllegalStateException: DevelopmentClientController was initialized. 
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6749)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:248)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7880)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
03-12 00:07:09.795 14180 14180 E AndroidRuntime: Caused by: java.lang.IllegalStateException: DevelopmentClientController was initialized.
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at expo.modules.devlauncher.DevLauncherController$Companion.initialize(DevLauncherContro
ller.kt:359)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at expo.modules.devlauncher.DevLauncherPackageDelegate$createApplicationLifecycleListene
rs$1.onCreate(DevLauncherPackageDelegate.kt:53)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at expo.modules.ApplicationLifecycleDispatcher.onApplicationCreate(ApplicationLifecycleD
ispatcher.kt:20)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at mx.qr.reader.MainApplication.onCreate(MainApplication.java:75)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
03-12 00:07:09.795 14180 14180 E AndroidRuntime:        ... 9 more
03-12 00:07:09.807 14180 14180 E DevLauncher: DevLauncher tries to handle uncaught exception.

```

**Comment by axelmy318** [comment]
Same issue

**Comment by axelmy318** [comment]
I add accidently hit "Make module" in the build section of android studio. It messed up stuff in my project.
`npx expo prebuild --clean`
`rm -rf node_modules/`
`npm i`
fixed it for me.

**Comment by mafikes** [comment]
Same issue too

**Comment by 0000005** [comment]
Same issue too

**Comment by sshodges** [comment]
getting the same error, anyone found a fix?

**Comment by 8128** [comment]
Same issue here

**Comment by sshodges** [comment]
> I add accidently hit "Make module" in the build section of android studio. It messed up stuff in my project. `npx expo prebuild --clean` `rm -rf node_modules/` `npm i` fixed it for me.

This ended up working for me 🙏

**Comment by mafikes** [comment]
> > I add accidently hit "Make module" in the build section of android studio. It messed up stuff in my project. `npx expo prebuild --clean` `rm -rf node_modules/` `npm i` fixed it for me.
> 
> This ended up working for me 🙏

It works for me too,  but after some time of building, the issue is back again and again.

**Comment by sshodges** [comment]
@mafikes try using yarn instead of npm, that worked for me

**Comment by CoderCharlie** [comment]
I had the same error, and found duplicate DevLauncherPackage in the generate code file *ExpoModulesPackageList*. This led to crash and I tried to debug gradle without luck as the source code of expo auto linking package was not in my dev env. Can anyone shed some light on how this being generated?

`    static final List<Package> packagesList = Arrays.<Package>asList(
      new expo.modules.adapters.react.ReactAdapterPackage(),
      new expo.modules.constants.ConstantsPackage(),
      new expo.modules.core.BasePackage(),
      new expo.modules.devlauncher.DevLauncherPackage(),
      new expo.modules.devlauncher.DevLauncherPackage(),
      new expo.modules.devmenu.DevMenuPackage(),
      new expo.modules.filesystem.FileSystemPackage(),
      new expo.modules.keepawake.KeepAwakePackage(),
      new expo.modules.localization.LocalizationPackage(),
      new expo.modules.splashscreen.SplashScreenPackage(),
      new expo.modules.splashscreen.SplashScreenPackage()
    );
`

**Comment by CoderCharlie** [comment]
`expo prebuild --clean rm -rf node_modules/ npm i` unfortunately, this didn't work for me as I am not using prebuild.
I've tried to delete node_modules, and reinstall everything with `yarn`. Ran `npx react-native clean` as well, nothing helps so far, not sure if there is any command for deep cleaning or resetting in expo, this is clearly something messed up in expo due to unknown reasons.

**Comment by bpeltonc** [comment]
> I had the same error, and found duplicate DevLauncherPackage in the generate code file _ExpoModulesPackageList_. This led to crash and I tried to debug gradle without luck as the source code of expo auto linking package was not in my dev env. Can anyone shed some light on how this being generated?
> 
> ```
>     static final List<Package> packagesList = Arrays.<Package>asList(
>       new expo.modules.adapters.react.ReactAdapterPackage(),
>       new expo.modules.constants.ConstantsPackage(),
>       new expo.modules.core.BasePackage(),
>       new expo.modules.devlauncher.DevLauncherPackage(),
>       new expo.modules.devlauncher.DevLauncherPackage(),
>       new expo.modules.devmenu.DevMenuPackage(),
>       new expo.modules.filesystem.FileSystemPackage(),
>       new expo.modules.keepawake.KeepAwakePackage(),
>       new expo.modules.localization.LocalizationPackage(),
>       new expo.modules.splashscreen.SplashScreenPackage(),
>       new expo.modules.splashscreen.SplashScreenPackage()
>     );
> ```

You're not by chance using a Yarn v1 monorepo, are you?

**Comment by cstayyab** [comment]
A small tip that might help someone: 
* Use `npx expo-doctor@latest` if you encounter any weird issues

**Comment by AftabUfaq** [comment]
same issue. tried every thing but no thing worked

**Comment by mafikes** [comment]
> [@mafikes](https://github.com/mafikes) try using yarn instead of npm, that worked for me

Iam using pnpm.

**Comment by AftabUfaq** [comment]
it was workig yesterday. suddenyl it has some issue. tred all things but smae issue

**Comment by retore404** [comment]
I had same issue.
In my case
```
rm -rf node_modules package-lock.json
npm install
```
worked for me.
