### ISSUE TITLE
Issues Compiling expo-image-manipulator on iOS After Xcode Update

### ISSUE THREAD

**Issue by emernuness** [expo/expo#27556]
### Minimal reproducible example

#

### Did you reproduce this issue in a development build?

Yes

### Description

After updating Xcode, I am encountering compile-time errors related to the `expo-image-manipulator` module in my Expo project. Specifically, the compiler cannot find references to `FileSystemUtilities` within the `ImageManipulatorModule.swift` file, among other related issues.

### Errors

The compilation errors are as follows:

1. `cannot find 'FileSystemUtilities' in scope`
2. `cannot infer contextual base in reference to member 'read'`
3. `value of type 'AppContext' has no member 'config'`
4. `cannot find 'FileSystemUtilities' in scope`

These errors prevent the iOS app from building successfully.

### Steps to Reproduce

1. Update Xcode to the latest version.
2. Run `yarn ios` or `expo run:ios` in the project directory.
3. Encounter the above compile-time errors related to `expo-image-manipulator`.

### Environment

- Expo SDK version: 48.0.21
- `expo-image-manipulator` version: 11.1.1
- React Native version: 0.71.14
- Xcode version: 15.3

### Attempts to Resolve

- I have tried updating Expo and all related dependencies to their latest versions.
- I have cleaned and reinstalled iOS pods with `pod install`.
- I have cleared the Metro bundler cache.

Unfortunately, these attempts have not resolved the compilation issues.

### Code Snippet

Here is a snippet from `ImageManipulatorModule.swift` where the errors are occurring:

```swift
guard FileSystemUtilities.permissions(appContext, for: url).contains(.read) else {
    return callback(.failure(FileSystemReadPermissionException(url.absoluteString)))
}
...
guard let cachesDirectory = self.appContext?.config.cacheDirectory else {
    throw FileSystemNotFoundException()
}
...
FileSystemUtilities.ensureDirExists(at: directory)


### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.3.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/emerson/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.21 => 48.0.21
      metro: ^0.76.1 => 0.76.9
      react: 18.2.0 => 18.2.0
      react-native: 0.71.14 => 0.71.14
    npmGlobalPackages:
      eas-cli: 7.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Error: Problem validating fields in /Users/emerson/Desktop/workspace/jaspi-expo/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: ios - should NOT have additional property 'useFrameworks'.

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

One or more checks failed, indicating possible issues with the project.

**Comment by jerom98** [comment]
@emernuness  did you solve it, i'm getting the same error.

**Comment by mikapotato** [comment]
I am having the same issue.

Xcode version: 15.4
React Native version: 0.71.8
Cocoapods version: 1.14.3
Expo SDK version: 51.0.8
Expo image manipulator version: 11.8.0
Target iOS version: 13.4

Probably need to come up with the minimal reproducible example, otherwise the issue is closed automatically...

**Comment by JacobDel** [comment]
+1

**Comment by JacobDel** [comment]
fixed for me when updating to:
```
    "react-native": "0.74.1",
    "expo": "^51.0.8",
    "expo-file-system": "^17.0.1",
    "expo-image-manipulator": "^11.8.0",
    "expo-image-picker": "^14.7.1",
```
