### ISSUE TITLE
expo-tracking-transparency not displaying prompt on TestFlight

### ISSUE THREAD

**Issue by ReMuSoMeGA93** [expo/expo#27558]
### Minimal reproducible example

see code

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

The ATT Request shows up in development Mode, but when I publish to TestFlight it does not display. My app is being rejected. I've read that adding a timeout helps. It does not.

This is the code I'm using in my App.tsx page

`  useEffect(() => {
    (async () => {
      setTimeout(async () => {
        const { status } = await requestTrackingPermissionsAsync();
        if (status === 'granted') {
          console.log('Yay! I have user permission to track data');
        }
      }, 500);
    })();
  }, []);`

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 34
        Build Tools: 30.0.3, 33.0.0, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
    npmGlobalPackages:
      eas-cli: 7.1.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by AgenteDog** [comment]
Getting the same issue here.

**Comment by jurmadani** [comment]
Same here

**Comment by jaslloyd** [comment]
Did any of you manage to solve this??

**Comment by brentvatne** [comment]
hey folks, a good solution here is to move the prompt outside of the initial startup, either a couple seconds later or when it is actually needed. it seems that ios wants you to have a bit of a delay between the app starting up and presenting this prompt. related - [it's generally recommended to not prompt users for permissions immediately when an app launches](https://www.nngroup.com/articles/permission-requests/).
