### ISSUE TITLE
[docs] bare workflow AKA native project AKA elejected: upgrade documentation 42 > now

### ISSUE THREAD

**Issue by russmenum** [expo/expo#27568]
### Summary

The https://docs.expo.dev/bare/upgrade/ tool only shows changes back to SDK 45, there is no documentation on how to get from 42 to 45 so this tool can be used. 

### Link to the related docs page

https://docs.expo.dev/bare/upgrade/

**Comment by amandeepmittal** [comment]
Hi @russmenum, if your project uses Expo SDK 42, I'd suggest going through our older SDK release blog posts. 
- https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541
- https://blog.expo.dev/expo-sdk-44-4c4b8306584a
- https://blog.expo.dev/expo-sdk-45-f4e332954a68

Each of these blog posts contains instructions on Bare workflow. For example, [Bare workflow section in SDK 43 blog post](https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541#:~:text=submission%20to%20stores.-,Bare%20workflow,-The%20bare%20workflow). The instructions from upgrading from each to the next SDK are unique.

The SDK 43 introduces Expo modules which has instructions in this [expo.fyi guide](https://github.com/expo/fyi/blob/main/expo-modules-migration.md) (this is also mentioned in SDK 43 Bare workflow section).

**Comment by russmenum** [comment]
@amandeepmittal to be clear this lacks the documentation of what files to change and so on, instead it is a BLIND faith in a deprecated ```expo upgrade``` to actually work, and work on Apple Silicone. 

The https://github.com/expo/fyi/blob/main/expo-modules-migration.md or [expo.fyi guide](https://github.com/expo/fyi/blob/main/expo-modules-migration.md) you link to seems to have part of this for 42 to 43.

But the KEY file ```package.json```changes is HIDDEN or missing.

Where is the index of [expo.fyi guide](https://github.com/expo/fyi/blob/main/expo-modules-migration.md) for

-  42 > 43
-  43 > 44
-  44 > 45 

hidden?

With https://docs.expo.dev/bare/upgrade/ properly docmenting back to 45, if the other files can be changed up to 45, while not ideal could probably be a get there from here...

**Comment by brentvatne** [comment]
@russmenum - you may be better off initializing a new project and copying your changes over if you're unsure how to proceed. if you'd like to see the diffs from sdk 42 to 50, you can clone the expo repo and diff the `templates/expo-template-bare-minimum` branch between the `sdk-42` branch and the `sdk-50` branch. alternatively, initialize a project with `npx create-expo-app --template bare-minimum@sdk-42` and also `npx create-expo-app --template bare-minimum@sdk-50` and compare / diff as needed. 

> Where is the index of [expo.fyi guide](https://github.com/expo/fyi/blob/main/expo-modules-migration.md) for ...

there isn't one. this migration between react-native-modules and expo-modules-core only took place during a single sdk version, and we typically recommend upgrading one sdk version at a time.

good luck with the upgrade!

**Comment by russmenum** [comment]
@brentvatne on this particular project, that is a problematic option. Most of the other apps were clean migrated to 46 a bit ago, and they were per the provided doc easy enough to migrate up to XCODE 15 for next month.

As you state "one ver at a time is preferred" part of why I am trying to go 42 >43 >44 >45... and so on.

- It would be BEYOND HELPFUL for this workflow if the  ```package.json``` had always been documented. It seems the core issue here is they were not until recently.  


## For this app so far I  have done: 

- the 42 > 43 documented: Follow the “[Migrating to Expo modules](https://expo.fyi/expo-modules-migration)” guide file changes, which wanted a ```noop-file.swift```; and I remember for XCODE 13 or 14 change over nothing would work until we created a ```ios/File.swift``` file.
- the 43 > 44 file changes, seemed to be IF there remove... Basically a very wordy way of saying modify ```package.json``` for those dependencies, and run ```npm install``` and ```cd ios``` then  ```pod install```
-  Currently I am trying to get through 44 > 45 so I can use doc

On the Apply any relevant changes from the [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.68.1). step.

It says a ```RnDiffApp.bundle/config``` file was added which seems to deal with RUBY, but I can not find that file in our other projects so not sure if it was removed later or does not apply? Any ideas?

-  the same with ```RnDiffApp.flowconfig``` in that none of the apps have that
- and a few others

This puts me in the place of BLINDLY assuming from incomplete documentation I will have a ```package.json``` that is other than VER number the correct list of dependencies for when I get to the 45 > 46 well documented changes, and that all other changes will be present. 

With some luck I will get to SDK 47 and like the other apps XCODE 15 will be happy and all will be good... but I won't know if steps from EXPO black box are missing until that point... 




## WHAT I KNOW SO FAR
XCODE 15 is not happy with anything less than 47 + tweaks, and XCODE 13 is long since EOL; so following some of this doc is problematic... 

### The tweak is 
```hass.hpp``` was incorect, XCODE 15 suggested:
```
struct hash_base : std::__unary_function<T, std::size_t> {};
```
let it change
```unary_function``` to ```__unary_function```
and then it is happy

Android Studio Iguana | 2023.2.1 on Apple Silicone and Gradle have endless ```CMAKE``` and  ```expo-modules-core``` problems. But outside documentation implies those are resolved RN 72+ which it looks like SdK 49+ adopted. This was not a problem on the older Android Studio nor Intel or Apple Silcone + Roseta2. 

This ongoing problem is the love-hate with EXPO, you can't use all of RN unless you go BARE (or whatever it is rebranded as today, sorry remember when it was "eject"), and then you can't always update EXPO until EXPO is ready to update RN, because the EXPO solution is just remove all those things you use that will break and there is no 1:1 EXPO replacement for. 

It is nice that EXPO is now targeting current Android rather than waiting until Aug deadlines so we can update both sides of apps at the same time XCODE mandates updates. Hopefully that will continue so going forward those of us this side can be at most 3 ver behind due to the pro/con of needed dependencies.
