### ISSUE TITLE
[expo-font] - config plugin not working on web

### ISSUE THREAD

**Issue by LukaRusadze** [expo/expo#27562]
### Minimal reproducible example

https://github.com/LukaRusadze/expo-font-web-test

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

Yes

### Summary

`expo-font`'s config plugin works great on Android and IOS, since we no longer have to wait for the fonts to load during the runtime but on Web it doesn't seem to work at all, needing to use `useFonts` for web, leading to either compromising loading times on mobile, platform specific implementation or sacrificing fonts on web.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by kylianbrun** [comment]
Hello !
Same here 👋

**Comment by brentvatne** [comment]
the expo-font config plugin embeds the font into the application binary for android and ios, but there is no equivalent to this for web, so we can't provide the same functionality.

**Comment by LukaRusadze** [comment]
Would be great if documentation showed that the config plugin doesn't work on web. Currently its pretty misleading.

Also when it comes to static rendering on web, useFonts already gets [optimized](https://docs.expo.dev/router/reference/static-rendering/#fonts). Can the same not be done with the config plugin? Would pretty much be equivalent to bundling fonts in application binaries

**Comment by Merott** [comment]
I agree it would be nice if the Expo docs at least pointed this out.

Even better if there was some documentation on the recommended way to set up fonts in universal apps. As it stands, I had to figure it out through trial and error.

In case it helps anyone, this is how I've set it up:

```js
// app.json

{
  "expo": {
    "plugins": [
      [
        "expo-font",
        {
          "fonts": [
            "assets/fonts/CustomFont-Black.otf",
            "assets/fonts/CustomFont-BlackItalic.otf",
            "assets/fonts/CustomFont-Bold.otf",
            "assets/fonts/CustomFont-BoldItalic.otf",
            "assets/fonts/CustomFont-Medium.otf",
            "assets/fonts/CustomFont-MediumItalic.otf",
            "assets/fonts/CustomFont-Regular.otf",
            "assets/fonts/CustomFont-RegularItalic.otf"
          ]
        }
      ]
    ]
  }
}

```

```tsx
// _layout.tsx

import '@/global.css'
import { Slot } from 'expo-router'
import { WebFontsLoader, WebSplashScreen } from '@/modules/core/components'
import { Platform, View } from 'react-native'

export default function RootLayout() {
  return (
    <View>
      {Platform.OS === 'web' ? (
        <WebFontsLoader fallback={<WebSplashScreen />}>
          <Slot />
        </WebFontsLoader>
      ) : (
        <Slot />
      )}
    </View>
  )
}
```

```tsx
// WebFontsLoader.tsx

import { useFonts } from 'expo-font'
import { useEffect, useState } from 'react'

const MIN_FALLBACK_DURATION = 500

/**
 * For web only: include this to load woff2 fonts.
 * For native platforms, otf files are bundled via app.json.
 */
export function WebFontsLoader({
  children,
  fallback,
}: {
  children?: React.ReactNode
  fallback?: React.ReactNode
}) {
  const hasFallback = !!fallback
  const [forceFallback, setForceFallback] = useState(hasFallback)

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setForceFallback(false)
    }, MIN_FALLBACK_DURATION)

    return () => {
      clearTimeout(timeoutId)
    }
  }, [])

  const [loaded, error] = useFonts({
    'CustomFont-Regular': require('assets/fonts/CustomFont-Regular.woff2'),
    'CustomFont-RegularItalic': require('assets/fonts/CustomFont-RegularItalic.woff2'),
    'CustomFont-Medium': require('assets/fonts/CustomFont-Medium.woff2'),
    'CustomFont-MediumItalic': require('assets/fonts/CustomFont-MediumItalic.woff2'),
    'CustomFont-Bold': require('assets/fonts/CustomFont-Bold.woff2'),
    'CustomFont-BoldItalic': require('assets/fonts/CustomFont-BoldItalic.woff2'),
    'CustomFont-Black': require('assets/fonts/CustomFont-Black.woff2'),
    'CustomFont-BlackItalic': require('assets/fonts/CustomFont-BlackItalic.woff2'),
  })

  return (loaded || error) && !forceFallback ? children : fallback
}
```
