### ISSUE TITLE
[docs] EAS Server Location

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#27560]
### Summary

The information about the location of the Server for the EAS Feature seems to be missing.

### Link to the related docs page

https://expo.dev/privacy

**Comment by amandeepmittal** [comment]
Hi @NilsBaumgartner1994, could you clarify whether your query is about requesting the geographical location or Build server infrastructure IP addresses? We are self-certified under the Data Privacy Framework.

If it is the IP address list you are looking for, you can find it in our docs: https://docs.expo.dev/build-reference/infrastructure/#builder-ip-addresses.

**Comment by amandeepmittal** [comment]
Hey @NilsBaumgartner1994, I'm closing this issue, but let me know if the previous comment satisfies the information you were looking for.
