### ISSUE TITLE
Prebuild won't install pods

### ISSUE THREAD

**Issue by MaciDE** [expo/expo#27561]
### Summary

When running expo prebuild -p iOS no pods will be installed by cocoapods and therefore no xcode workspace is generated.

Maybe it's not connected to this issue but I also noticed that the podfile.properties.json is missing environment variables set via the expo-build-properties config plugin. 

### What platform(s) does this occur on?

iOS

### SDK Version

50

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.1 - /opt/homebrew/bin/node
      npm: 10.5.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.2, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ^0.19.6 => 0.19.6 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare

### Minimal reproducible example

1. Run `npx create-expo-app my-app`
2. Run `npx expo prebuild -p iOS` inside my-app
3. Check iOS folder for pods folder and generated .xcworkspace

**Comment by MaciDE** [comment]
Why should I create a additional repo if I am able to reproduce the issue with the template generated by npx create-expo-app my-app?

**Comment by Rickynunez123** [comment]
Did you solve the problem? I am having the same issue, and when trying to install pods in the IOS folder directly I get the glog (0.3.5) error

**Comment by MaciDE** [comment]
> Did you solve the problem? I am having the same issue, and when trying to install pods in the IOS folder directly I get the glog (0.3.5) error

I don't know why, but it just started to work again a few weeks after opening this issue. For a short time I also used to specify iOS as the target platform via the -p flag.
