### ISSUE TITLE
Print.printAsync remains stuck and printing is impossible till the app is restarted

### ISSUE THREAD

**Issue by 70X** [expo/expo#27570]
### Minimal reproducible example

https://snack.expo.dev/FOpFnVaIFAdxIYms2lanN

### What platform(s) does this occur on?

iOS (Version 17.1.1)

### Did you reproduce this issue in a development build?

Yes

### Summary
In certain cases when you provide a non existing printer url and try to print a document, the process will be stuck forever. Beside that, even if you try to print the document with a different and valid printer url, you will get the error message "Another print request is already in progress" till the app is restarted.

### Reproducible Demo
https://snack.expo.dev/FOpFnVaIFAdxIYms2lanN
- Click on the `Print` button the first time
- See the ["attempt"] log
- from now on, if you tap on the button again, you'll get in the log queue the following: ["attempt", "Another print request is already in progress", "end"]

### Expected Behavior
It would be nice to have an option to abort/reset the process from the outside but if that wouldn't be possible, having a sort of internal timeout to avoid a permanent hanging should be considered a requirement

### Environment

System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/soniavolpe/.rvm/gems/ruby-2.7.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      babel-preset-expo: ^9.3.0 => 9.3.2 
      expo: ^48.0.15 => 48.0.15 
      react: ^18 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.18.10 => 0.18.10 
    Expo Workflow: bare

**Comment by DanushRenjith** [comment]
Yes, I have also faced the same issue in Android(version 14), using  "expo-print": "~12.4.2" .that is "Another print request is already in progress", but this issue occurs intermittently, but once this issue occurs it won't allow any consequent prints, need to manually close the application and it would work. So is there any way to clear the  print queue or unmount the expo print when this issue occurs

**Comment by DanushRenjith** [comment]
I have checked through the package code, we can add a timeout by modifying the code like this

 export async function printAsync(options: PrintOptions): Promise<void> {
  if (Platform.OS === 'web') {
    return await ExponentPrint.print(options);
  }
  if (!options.uri && !options.html && Platform.OS === 'ios' && !options.markupFormatterIOS) {
    throw new Error('Must provide either `html` or `uri` to print');
  }
  if (options.uri && options.html) {
    throw new Error('Must provide exactly one of `html` and `uri` but both were specified');
  }
  if (options.markupFormatterIOS !== undefined) {
    console.warn('The markupFormatterIOS option is deprecated. Use useMarkupFormatter instead.');
  }
  if (isPrinting) {
    throw new Error('Another print request is already in progress');
  }

  isPrinting = true;


  try {
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(() => {
        reject(new Error('Print operation timed out'));
      }, 20000);      // can make the timeout dynamic 
    });
    const printPromise = ExponentPrint.print(options);
    return await Promise.race([printPromise, timeoutPromise]);
    // return await ExponentPrint.print(options);
  } finally {
    isPrinting = false;
  }
}
this might not be a good solution, but its a possible fix.

**Comment by Xmurtaza** [comment]
> Yes, I have also faced the same issue in Android(version 14), using "expo-print": "~12.4.2" .that is "Another print request is already in progress", but this issue occurs intermittently, but once this issue occurs it won't allow any consequent prints, need to manually close the application and it would work. So is there any way to clear the print queue or unmount the expo print when this issue occurs

Did you find the fix for this?
