### ISSUE TITLE
[expo-media-library] [ios] MediaLibrary.deleteAlbumsAsync always tries to delete the album assets, regardless of the assetRemove flag

### ISSUE THREAD

**Issue by stevengoldberg** [expo/expo#27575]
### Minimal reproducible example

https://github.com/stevengoldberg/expo-media-library-delete-bug/

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

[MediaLibrary.deleteAlbumsAsync](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibrarydeletealbumsasyncalbums-assetremove) should delete an album without deleting the album's assets when its second parameter is `false` or `undefined`. But it always tries to delete the album's assets.

## Steps to reproduce
1. Create at least one photo album on the device or simulator
2. Run the project and grant permission
3. Press "Delete" in one of the album rows
4. Press "Delete" in the native alert asking to confirm album deletion:
<img width="314" alt="image" src="https://github.com/stevengoldberg/expo-media-library-delete-bug/assets/2230992/3bad82c0-3b0d-4ca5-ba2d-6521f4f8e76b">

**Expected behavior**:
The promise will resolve `true` and the album will be deleted without deleting its assets.

**Actual behavior**:
A second native alert is triggered asking to confirm asset deletion:

<img width="320" alt="image" src="https://github.com/stevengoldberg/expo-media-library-delete-bug/assets/2230992/02073762-68aa-4573-9405-fc3a437dc2d3">

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 10.2.5 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/stevengoldberg/.gem/ruby/3.1.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by behenate** [comment]
@stevengoldberg Hi, thanks for filing the issue! It has been fixed by @alanjhughes in https://github.com/expo/expo/pull/25587 🙂
