### ISSUE TITLE
Asyncstorage slow

### ISSUE THREAD

**Issue by joshg111** [expo/expo#2758]
When the app is launched from expo platform eg. expo is running in the background asyncstorage loads instantly. When I load the app from a shortcut on the home page, asyncstorage load can take more than 20 seconds. Also, the emulator is instant regardless. 

Running on android.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
