### ISSUE TITLE
Getting ERROR Warning: Maximum update depth exceeded.

### ISSUE THREAD

**Issue by ananduremanan** [expo/expo#27582]
### Minimal reproducible example

https://github.com/ananduremanan/expo-router-issue

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I followed Expo 's documentation on [Authentication in Expo Router](https://docs.expo.dev/router/reference/authentication) and created context and useStorage hook. But Whenevere I call signOut() I'm getting `ERROR  Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.`  How to fix this?

Though the code is same as the documentation, I'm still pasting it here for more context.

ctx.tsx

```
import React, { useEffect } from "react";
import { useStorageState } from "./useStorageState";

const AuthContext = React.createContext<{
  signIn: () => void;
  signOut: () => void;
  session?: string | null;
  isLoading: boolean;
}>({
  signIn: () => null,
  signOut: () => null,
  session: null,
  isLoading: false,
});

// This hook can be used to access the user info.
export function useSession() {
  const value = React.useContext(AuthContext);
  if (process.env.NODE_ENV !== "production") {
    if (!value) {
      throw new Error("useSession must be wrapped in a <SessionProvider />");
    }
  }

  return value;
}

export function SessionProvider(props: React.PropsWithChildren) {
  const [[isLoading, session], setSession] = useStorageState("session");

  return (
    <AuthContext.Provider
      value={{
        signIn: () => {
          // Perform sign-in logic here
          setSession("xxx");
        },
        signOut: () => {
          setSession(null);
        },
        session,
        isLoading,
      }}
    >
      {props.children}
    </AuthContext.Provider>
  );
}
```

useStorageState.ts

```
import * as SecureStore from "expo-secure-store";
import * as React from "react";
import { Platform } from "react-native";

type UseStateHook<T> = [[boolean, T | null], (value: T | null) => void];

function useAsyncState<T>(
  initialValue: [boolean, T | null] = [true, null]
): UseStateHook<T> {
  return React.useReducer(
    (
      state: [boolean, T | null],
      action: T | null = null
    ): [boolean, T | null] => [false, action],
    initialValue
  ) as UseStateHook<T>;
}

export async function setStorageItemAsync(key: string, value: string | null) {
  if (Platform.OS === "web") {
    try {
      if (value === null) {
        localStorage.removeItem(key);
      } else {
        localStorage.setItem(key, value);
      }
    } catch (e) {
      console.error("Local storage is unavailable:", e);
    }
  } else {
    if (value == null) {
      await SecureStore.deleteItemAsync(key);
    } else {
      await SecureStore.setItemAsync(key, value);
    }
  }
}

export function useStorageState(key: string): UseStateHook<string> {
  // Public
  const [state, setState] = useAsyncState<string>();

  // Get
  React.useEffect(() => {
    if (Platform.OS === "web") {
      try {
        if (typeof localStorage !== "undefined") {
          setState(localStorage.getItem(key));
        }
      } catch (e) {
        console.error("Local storage is unavailable:", e);
      }
    } else {
      SecureStore.getItemAsync(key).then((value) => {
        setState(value);
      });
    }
  }, [key]);

  // Set
  const setValue = React.useCallback(
    (value: string | null) => {
      setState(value);
      setStorageItemAsync(key, value);
    },
    [key]
  );

  return [state, setValue];
}
```

Settings.tsx

```
import React from "react";
import { Button, View, useTheme } from "tamagui";
import { useSession } from "../ctx";

export default function ModalScreen() {
  const { signOut } = useSession();
  const theme = useTheme();
  const background = theme.background.get();

  return (
    <View
      backgroundColor={background}
      flex={1}
      alignItems="center"
      justifyContent="center"
    >
      <Button
        onPress={() => {
          signOut();
        }}
      >
        LogOut
      </Button>
    </View>
  );
}

```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 4.0.2 - ~\AppData\Roaming\npm\yarn.CMD    
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD    
    npmPackages:
      babel-preset-expo: ^10.0.1 => 10.0.1 
      expo: ~50.0.11 => 50.0.12 
      expo-router: ~3.4.8 => 3.4.8
      react: ^18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ^0.19.9 => 0.19.10
    Expo Workflow: managed

**Comment by ananduremanan** [comment]
Thank You @marklawlor

**Comment by UddhavSJadhav** [comment]
I was facing the same issue. I found that I was redirecting to "/" index page (which was previous created but removed) from not-found page.

**Comment by UddhavSJadhav** [comment]
I encountered the same issue and discovered that I was being redirected to the "/" index page (which had been created earlier but was later removed) from the not-found page.

**Comment by nitinsaroha** [comment]
I'm facing the same issue when I tried to upgrade to expo 51. Everything works fine in expo 50. Any help is appreciated.

Redirect goes in infinite loop.

Here's my `src/app/(app)/_layout.tsx`

```tsx
export const unstable_settings = {
  // Ensure that reloading on `/modal` keeps a back button present.
  initialRouteName: "(tabs)",
};

// Prevent the splash screen from auto-hiding before asset loading is complete.
SplashScreen.preventAutoHideAsync();

export default function AppLayout() {
  const { session, isLoading } = useSession();
  const [loaded, error] = useFonts({
    ...FontAwesome.font,
  });

  useEffect(() => {
    if (error) throw error;
  }, [error]);

  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return null;
  }

  if (isLoading) {
    return (
      <View>
        <Text>Loading....</Text>
      </View>
    );
  }

  if (!session) {
    return <Redirect href={"/sign-in"} />;
  }

  return <AppLayoutNav />;
}

function AppLayoutNav() {
  const colorScheme = useColorScheme();

  return (
    <ThemeProvider value={colorScheme === "dark" ? DarkTheme : DefaultTheme}>
      <Stack>
        <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
        <Stack.Screen name="modal" options={{ presentation: "modal" }} />
      </Stack>
    </ThemeProvider>
  );
}

```

**Comment by ryandever** [comment]
I have the same issue as you, just update to Expo 51 today and getting this bug @nitinsaroha

**Comment by nitinsaroha** [comment]
> I encountered the same issue and discovered that I was being redirected to the "/" index page (which had been created earlier but was later removed) from the not-found page.

@ryandever Above comment helped me solve this issue. 

- I created a minimal app and was able to reproduce this in a new app created with Expo 51.
- The reason of the infinite loop seems to be the incorrect location of `+not-found.tsx`. It should be at the root of the `src/app` directory.
- Previous incorrect location: `src/app/(app)/+not-found.tsx`
- New correct location: `src/app/+not-found.tsx`

**Comment by ryandever** [comment]
Thanks @nitinsaroha so much, you saved my day!

**Comment by claudesortwell** [comment]
Thanks @nitinsaroha 

@marklawlor Is this intended? as the docs state 

```
Expo Router provides a special file +not-found.tsx which is used to handle routes that are 404s. This route file matches all unmatched routes from a nested level.
```

Which makes me think nested not-found routes should still be possible?

**Comment by davidcort** [comment]
I get the same error but I am not using Expo Route, i have the same issue with React Navigation in Expo SDK 51 :(

**Comment by FloareDor** [comment]
Thank you so much @nitinsaroha.

That works perfectly!

**Comment by vitdanylov** [comment]
Hello, unfortunately didn't work for me :(
Tried to move +not-found.tsx in the root: `/app/+not-found.tsx`, and remove it in general and still Infinite loop.

**Comment by Ashin2052** [comment]
How is this solved, I still have the same issue @nitinsaroha ?

**Comment by ishaan1995** [comment]
I faced the same issue.
This is the correct solve for it: https://github.com/expo/expo/issues/27582#issuecomment-2322373926
Moving +not-found to root fixed the issue.

**Comment by tiganabryan** [comment]
I'm having this issue as well and my +not-found is in the root. Also made sure there was no period before the slash in redirects.

**Comment by henriqueantonio** [comment]
+1

- I'm not using +not-found in my project
- My redirect it's "/sign-in"

Still getting this error.

**Comment by aaronksaunders** [comment]
just spent three hours trying to figure out why my code isn't working after following the instructions in the documentation and then I found this thread. I rolled back to the previous version of expo router and my code now magically works.

I am running fine on 3.4.8 but failing on 3.5.23 - I would recommend rolling back on version an see if  that changes anything for those others who end up here

**Comment by nayaabkhan** [comment]
Solution from @aaronksaunders worked in my case. Not using `+not-found` in my project, but the upgrade was the reason.

**Comment by jajjage** [comment]
I get the same error but I am not using Expo Route, i have the same issue with React Navigation in Expo SDK 51 :(


@davidcort Did you find solutions to this because I have spent hours on this, but in my case I change the logout screen and it work there

**Comment by jony89** [comment]
same issue here with "expo-router": "^4.0.21" + "expo": "52.0.45",

@marklawlor
