### ISSUE TITLE
It looks like <Link asChild> has a problem with functional child components

### ISSUE THREAD

**Issue by hbel** [expo/expo#27593]
### Minimal reproducible example

-

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have a custom button component that I want to use within expo routers link. When using it there, I get a lot of runtime errors of the form:

```
 ERROR  Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `SlotClone`.
    in Button (at RegisterConsent.tsx:56)
    in SlotClone (created by Slot)
    in Slot (at Link.js:133)
    in ExpoRouterLink (at RegisterConsent.tsx:55)
    in RCTView (at View.js:116)
    in View (at RegisterConsent.tsx:54)
    in RCTScrollContentView (at ScrollView.js:1732)
    in RCTScrollView (at ScrollView.js:1855)
    in ScrollView (at ScrollView.js:1925)
    in ScrollView (at RegisterConsent.tsx:20)
    in RNCSafeAreaView (at SafeAreaView.tsx:49)
    in Unknown (at RegisterConsent.tsx:19)
    in RegisterConsent (at useScreens.js:112)
    in Unknown (at useScreens.js:116)
    in Suspense (at useScreens.js:115)
    in Route (at useScreens.js:131)
    in Route(register/RegisterConsent) (at SceneView.tsx:132)
    in StaticContainer
```

My link structure does not contain anything special:

```
<Link href="/register/RegisterConfirmation" asChild>
  <Button
	  variant="primary"
	  label="button-continue"
	  disabled={disabled}
  />
</Link>
```

My Button component implements all props mentioned in Expo router's documentation. And it also works. It just throws lot's of errors.

### Environment

Expo SDK 50

**Comment by kkempsky** [comment]
Got similar problem with TouchableOpacity, wrapped function with forwardRef and it worked.

**Comment by jason-yolabs** [comment]
I'm also seeing this same issue on latest expo + react-native-elements's Button

```
import { Link } from 'expo-router';
import { Button } from 'react-native-elements'

// ...

<Link href="/hello" asChild>
  <Button title="Hello" />
</Link>
```

**Comment by Phenelo** [comment]
> I'm also seeing this same "Check the render method of `SlotClone`" on latest expo + react-native-elements's Button
> 
> ```
> import { Link } from 'expo-router';
> import { Button } from 'react-native-elements'
> 
> // ...
> 
> <Link href="/hello" asChild>
>   <Button title="Hello" />
> </Link>
> ```

Was also using react-native-element `Button`. I got rid of the warning by wrapping the `Button` with `Pressable`, then wrap them both in a single component with `forwardRef`:

```
export default forwardRef(function Button(props, ref: React.LegacyRef<View>) {
  return (
    <Pressable ref={ref}>
      <RNEButton>
        {props.children}
      </RNEButton>
    </Pressable>
  );
});

// using Link

<Link
  href="/path"
  asChild
>
  <Button>
    Get Started
  </Button>
</Link>
```

**Comment by alistertb** [comment]
> I'm also seeing this same "Check the render method of `SlotClone`" on latest expo + react-native-elements's Button
> 
> ```
> import { Link } from 'expo-router';
> import { Button } from 'react-native-elements'
> 
> // ...
> 
> <Link href="/hello" asChild>
>   <Button title="Hello" />
> </Link>
> ```

I'm running into the same problem too. Can we re-open this issue?

**Comment by erquhart** [comment]
This is not a bug - it's documented that you need to provide `onPress`/`onClick` when using the `asChild` prop with `<Link/>`:

> The child component must support the onPress and onClick props, href and role will also be passed down.

Source: https://docs.expo.dev/router/navigating-pages/#buttons

**Comment by ngdbao** [comment]
Me too, not only button, wrap Text also run into problem

**Comment by kasvith** [comment]
Happening with me too, in my case the `<Button>` is already using `forwardRef` 

it works, but styles are not applying

**Comment by cstayyab** [comment]
If it might help someone, wrapping the component into `forwardRef` like this fixed it for me:

```tsx
export default forwardRef<typeof Button, ButtonProps>((props, _ref) => (
  <Button {...props} />
));
```
