### ISSUE TITLE
Improve clarity of use of Preloading & Caching Assets

### ISSUE THREAD

**Issue by magician11** [expo/expo#276]
This page https://docs.expo.io/versions/v17.0.0/guides/preloading-and-caching-assets.html describes how to cache images.

It wasn't immediately clear to me that to use those cached images, to reference them as per normal

`<Image source={require('../images/sky-night-space-trees.jpeg')} />`

So maybe update the docs to explicitly show how to use an Image once it's been cached.

**Comment by brentvatne** [comment]
this is a common confusion, thanks for creating the issue!

**Comment by nikki93** [comment]
Reflected in https://github.com/expo/expo-docs/commit/9755dbb5f37227b2980dff3e069599e5d15d2a25, will be visible on next website deploy.

**Comment by brentvatne** [comment]
@magician11 - does @nikki93's change make it clear for you?

**Comment by magician11** [comment]
> Continue referencing the image normally, eg. with `<Image source={require('path/to/image.png')} />`.

It's better, and I think could be made a little clearer. I'd probably say something more explicit:

> To reference one of the cached images in your code, declare an Image component as per normal. eg. `<Image source={require('path/to/image.png')} />`.
