### ISSUE TITLE
react native 0.74-rc3 ios build issues

### ISSUE THREAD

**Issue by joeyhotz** [expo/expo#27615]
### Minimal reproducible example

https://github.com/joeyhotz/rn-0.74-flipper-build-issue

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

when I try and build for iOS using the react native 0.74 rc 3, I get this error:

```
✔ Cleared ios code
✔ Created native directory
› Using current versions instead of recommended react-native@0.73.4.
✔ Updated package.json | no changes
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: uninitialized constant Pod::Podfile::FlipperConfiguration.

 #  from /Users/joey.hotz/eucdev/rn-0.74/ios/Podfile:27
 #  -------------------------------------------
 #  # ```
 >  flipper_config = FlipperConfiguration.disabled
 #  if ENV['NO_FLIPPER'] == '1' then
 #  -------------------------------------------
```

I know it's not officially supported, but hoping to maybe get some insight/make the team aware of this issue.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11
      react: 18.2.0 => 18.2.0
      react-native: ^0.74.0-rc.3 => 0.74.0-rc.3
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

n/a

**Comment by brentvatne** [comment]
we add support for new versions of react-native with each sdk release. if you'd like to use react-native@0.74-rc, you can try the canary release: https://docs.expo.dev/versions/latest/#using-pre-release-versions
