### ISSUE TITLE
No podspec found for EXLocation on "../node_modules/expo-location/ios"

### ISSUE THREAD

**Issue by brianha289** [expo/expo#2761]
Hello guys, I use a completely fresh expo detached project, using pod install in ios directory.
And it showed me

No podspec found for `EXLocation ` in `../node_modules/expo-location/ios`
If I comment out this line pod and run Xcode project, see error
`
Native module not found
<unknown>
Location.js:8:46
<unknown>
Expo.js:5
`

How can I solve the issue?
Thank you so much

**Comment by sjchmiela** [comment]
Hey, @brianha289! If not a podspec, what is in your `node_modules/expo-location/ios`? 🤔

**Comment by sjchmiela** [comment]
I'll close this issue tentatively due to inactivity, I hope you've managed to fix the problem yourself! 🙂
