### ISSUE TITLE
Webview WebKit Live Reload Multiple Instances Crashes Expo App During Development 

### ISSUE THREAD

**Issue by deanmraz** [expo/expo#2762]
### Environment
- iOS 
- Expo v31 

### Steps to Reproduce

```js
import React from 'react';
import { StyleSheet, Text, View, WebView } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <WebView
        useWebKit={true}
        source={{uri: 'https://docs.expo.io/versions/v31.0.0/react-native/webview'}}
        style={{marginTop: 20}}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
[Example Project Repo](https://github.com/deanmraz/react-native-learning/tree/hotfix/webview-reload)

1. expo start
2. run ios simulator 
3. open safari > Develop > Simulator - <Your Device/Version>
4. Observe the available webviews
5. Reload command + R
6. Observe more webviews 
7. Repeat until crash 

### Expected Behavior
- If you remove the useWebkit={true} option it does not generate multiple instances of the webview. This is expected behavior 

### Actual Behavior
- Multiple instances of the webview is heavy and ultimately freezes the expo app to the point where you cannot interact with the app. 

![](http://prodtype.imgix.net/github/Screenshot%202018-11-20%2019.26.00.png?auto=compress)

### Reproducible Demo
- https://github.com/deanmraz/react-native-learning/tree/hotfix/webview-reload

**Comment by esamelson** [comment]
Hi @deanmraz - thanks for the report! We'll look into this but cannot promise a fix on any given timeline. The `WebView` library is currently maintained at https://github.com/react-native-community/react-native-webview , so you might consider making an issue there as well.

**Comment by deanmraz** [comment]
@esamelson thanks, I will recreate the issue with a plain react native project and see if its still an issue.

**Comment by kashifghaffarasim** [comment]
Hi @esamelson . I used expo sdk 31.0.0 and webView not working. Please help me.

**Comment by kashifghaffarasim** [comment]
[<WebView
        useWebKit={true}
        source={{uri: 'https://docs.expo.io/versions/v31.0.0/react-native/webview'}}
        style={{marginTop: 20}}
      />]
Not working with expo.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
