### ISSUE TITLE
expo-font doesn't respect font-family and font-weight

### ISSUE THREAD

**Issue by ambarc** [expo/expo#27647]
### Minimal reproducible example

https://gist.github.com/ambarc/b9ff0b8a7b5968f1f4a96a57930a0add

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Expo doesn't appear to support the combined usage of `font-family` and `font-weight` in iOS. The bare metal version of our app does (on RN 69.6, Expo 46). 

See the gist for a simple example. 

Case 1: Font weight in the font family (i.e. GothamSSm-Bold)
Case 2: Font family with separate variations of font-weights (i.e. font-family: "Gotham SSm" + font-weight: 700).
It appears that by default, Expo is doing Case 1 and avoiding Case 2 which is where we’re seeing failures.

We currently have a legacy code base with both of these cases working. Migrating to expo breaks because the fonts don't render as we'd want them to.

This is likely a similar issue to [this one](https://github.com/expo/expo/issues/20048).

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/ambar/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.21 => 46.0.21 
      react: 18.0.0 => 18.0.0 
      react-dom: 16.2.0 => 16.2.0 
      react-native: 0.69.9 => 0.69.9 
      react-native-web: ~0.18.7 => 0.18.12 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check for legacy global CLI installed locally

Detailed check results:

Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  @expo/config-plugins@7.8.4
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

Error: Problem validating fields in /Users/ambar/projects/member-app/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: android/versionCode - must be integer.

Some dependencies are incompatible with the installed expo version:
  @react-native-async-storage/async-storage@1.22.3 - expected version: ~1.17.3
  @react-native-community/datetimepicker@3.0.1 - expected version: 6.2.0
  @react-native-community/netinfo@5.9.10 - expected version: 9.3.0
  @react-native-community/slider@4.5.0 - expected version: 4.2.3
  @react-native-firebase/app@14.11.1 - expected version: ~15.4.0
  @react-native-picker/picker@2.4.1 - expected version: 2.4.2
  @shopify/react-native-skia@0.1.183 - expected version: 0.1.141
  @stripe/stripe-react-native@0.26.0 - expected version: 0.13.1
  expo-font@11.1.1 - expected version: ~10.2.0
  react-dom@16.2.0 - expected version: 18.0.0
  react-native-safe-area-context@3.3.2 - expected version: 4.3.1
  react-native-screens@3.20.0 - expected version: ~3.15.0
  react-native-svg@12.1.0 - expected version: 12.3.0
  react-native-webview@12.0.0 - expected version: 11.23.0
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install @react-native-async-storage/async-storage@~1.17.3 @react-native-community/datetimepicker@6.2.0 @react-native-community/netinfo@9.3.0 @react-native-community/slider@4.2.3 @react-native-firebase/app@~15.4.0 @react-native-picker/picker@2.4.2 @shopify/react-native-skia@0.1.141 @stripe/stripe-react-native@0.13.1 expo-font@~10.2.0 react-dom@18.0.0 react-native-safe-area-context@4.3.1 react-native-screens@~3.15.0 react-native-svg@12.3.0 react-native-webview@11.23.0
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by lucasvnborges** [comment]
a setting in this format would be bad for you?

`
   let [fontsLoaded] = useFonts({
    regular: Inter_400Regular,
    medium: Inter_500Medium,
    semibold: Inter_600SemiBold,
    bold: Inter_700Bold,
    extra: Inter_800ExtraBold,
    black: Inter_900Black,
  })
  
  <Text style={{ fontFamily: 'regular' }}>
`

**Comment by ambarc** [comment]
At the moment it would mean having to migrate a bunch of "legal" legacy code (which uses both `font-family` and `font-weight`) from the bare-metal React Native app we're on. I could think about shims, migrations, and other styling-code changes, but I'm not sure that I should have to for fonts.

**Comment by ambarc** [comment]
[This issue](https://github.com/expo/expo/issues/9149) probably captures what I'm seeing.

**Comment by dellyn** [comment]
@ambarc just in case you need to migrate bunch of legacy I would reccomend using jscodeshift. Using it together with GPT4 I have migrated 250 less files with thousands of less variables to css variables, including multiple variations of syntax aka, calc(), media(), transform() just in one day.

**Comment by SuhitAgarwal** [comment]
```typescript
interface TxtProps extends TextProps {}

type PrimaryFontFamily =
  | 'Inter-Thin'
  | 'Inter-ExtraLight'
  | 'Inter-Light'
  | 'Inter-Regular'
  | 'Inter-Medium'
  | 'Inter-SemiBold'
  | 'Inter-Bold'
  | 'Inter-Black';

const fontFamilyForWeight: Record<
  NonNullable<TextStyle['fontWeight']>,
  PrimaryFontFamily
> = {
  '100': 'Inter-Thin',
  '200': 'Inter-ExtraLight',
  '300': 'Inter-Light',
  '400': 'Inter-Regular',
  '500': 'Inter-Medium',
  '600': 'Inter-SemiBold',
  '700': 'Inter-Bold',
  '800': 'Inter-ExtraBold',
  '900': 'Inter-Black',
  normal: 'Inter-Regular',
  bold: 'Inter-Bold',
};

export const Txt: React.FC<TxtProps> = ({style, ...props}) => {
  const flattenedStyle = StyleSheet.flatten<TextStyle>(style);
  const {fontWeight, color, ...otherStyles} = flattenedStyle || {};

  return (
    <Text
      {...props}
      style={{
        ...otherStyles,
        fontFamily: fontFamilyForWeight[fontWeight ?? '400'],
        color: color || DARK_GRAY,
      }}
    />
  );
};

```
This is how I did it on my app, linked the assets using `react-native-asset`. The good thing about expo is you can do a dev build, so the `react-native-asset` will hook up your font files to the iOS and Android folders. 

Ideally,`expo-font` should just let me configure the weights and `normal` + `bold` in a similar fashion and hook it up to maybe an `Text` component imported from `expo` or something

**Comment by quememo** [comment]
> ```ts
> interface TxtProps extends TextProps {}
> 
> type PrimaryFontFamily =
>   | 'Inter-Thin'
>   | 'Inter-ExtraLight'
>   | 'Inter-Light'
>   | 'Inter-Regular'
>   | 'Inter-Medium'
>   | 'Inter-SemiBold'
>   | 'Inter-Bold'
>   | 'Inter-Black';
> 
> const fontFamilyForWeight: Record<
>   NonNullable<TextStyle['fontWeight']>,
>   PrimaryFontFamily
> > = {
>   '100': 'Inter-Thin',
>   '200': 'Inter-ExtraLight',
>   '300': 'Inter-Light',
>   '400': 'Inter-Regular',
>   '500': 'Inter-Medium',
>   '600': 'Inter-SemiBold',
>   '700': 'Inter-Bold',
>   '800': 'Inter-ExtraBold',
>   '900': 'Inter-Black',
>   normal: 'Inter-Regular',
>   bold: 'Inter-Bold',
> };
> 
> export const Txt: React.FC<TxtProps> = ({style, ...props}) => {
>   const flattenedStyle = StyleSheet.flatten<TextStyle>(style);
>   const {fontWeight, color, ...otherStyles} = flattenedStyle || {};
> 
>   return (
>     <Text
>       {...props}
>       style={{
>         ...otherStyles,
>         fontFamily: fontFamilyForWeight[fontWeight ?? '400'],
>         color: color || 'black',
>       }}
>     />
>   );
> };
> ```
> 
> @ambarc This is how I did it on my app, linked the assets using `react-native-asset`. The good thing about expo is you can do a dev build, so the `react-native-asset` will hook up your font files to the iOS and Android folders.
> 
> Ideally,`expo-font` should just let me configure the weights and `normal` + `bold` in a similar fashion and hook it up to maybe an `Text` component imported from `expo` or something

Great workaround, thanks!

**Comment by jongbelegen** [comment]
Font weights on iOS do work when you include them in the runtime by using the [app.config configuration](https://docs.expo.dev/versions/latest/sdk/font/#configuration-in-appjsonappconfigjs).

If you want to use font weights on Android as well you can use https://www.npmjs.com/package/expo-font-weights (till https://github.com/expo/expo/pull/26082 is merged)

**Comment by eserbina652** [comment]
You're welcome:

interface IProps {
  children: ReactNode
  style?: StyleProp<TextStyle>
  variant?: keyof typeof typographyVariantsConfig
}

const getFontFamilyByWeight = (weight: TFontWeights): string =>
  typographyFontsConfig[weight]

export const Typography = memo(function Typography({
  children,
  style,
  variant = 'h5',
}: IProps) {
  const [fontsLoaded] = useFonts({
    'SimplonNorm-Light-WebS': require('@fonts/SimplonNorm-Light-WebS.otf'),
    'SimplonNorm-Regular': require('@fonts/SimplonNorm-Regular.otf'),
    'SimplonNorm-Medium-WebS': require('@fonts/SimplonNorm-Medium-WebS.otf'),
    'SimplonNorm-Bold-WebS': require('@fonts/SimplonNorm-Bold-WebS.otf'),
  })

  const fontFamily = useMemo(() => {
    let fontWeight = undefined

    if (style && typeof style === 'object') {
      fontWeight = (style as TextStyle).fontWeight
    }

    return getFontFamilyByWeight(fontWeight as TFontWeights)
  }, [style])

  if (!fontsLoaded) {
    return null
  }

  return (
    <Text
      style={[
        {
          fontFamily,
          ...typographyVariantsConfig[variant],
        },
        style,
      ]}
    >
      {children}
    </Text>
  )
})

**Comment by eserbina652** [comment]
You're welcome:

`import { useFonts } from 'expo-font'
import { memo, ReactNode, useMemo } from 'react'
import { Text, StyleProp, TextStyle } from 'react-native'

import { TFontWeights } from './types'
import {
  typographyFontsConfig,
  typographyVariantsConfig,
} from './typography-style-config'

interface IProps {
  children: ReactNode
  style?: StyleProp<TextStyle>
  variant?: keyof typeof typographyVariantsConfig
}

const getFontFamilyByWeight = (weight: TFontWeights): string =>
  typographyFontsConfig[weight]

export const Typography = memo(function Typography({
  children,
  style,
  variant = 'h5',
}: IProps) {
  const [fontsLoaded] = useFonts({
    'SimplonNorm-Light-WebS': require('@fonts/SimplonNorm-Light-WebS.otf'),
    'SimplonNorm-Regular': require('@fonts/SimplonNorm-Regular.otf'),
    'SimplonNorm-Medium-WebS': require('@fonts/SimplonNorm-Medium-WebS.otf'),
    'SimplonNorm-Bold-WebS': require('@fonts/SimplonNorm-Bold-WebS.otf'),
  })

  const fontFamily = useMemo(() => {
    let fontWeight = undefined

    if (style && typeof style === 'object') {
      fontWeight = (style as TextStyle).fontWeight
    }

    return getFontFamilyByWeight(fontWeight as TFontWeights)
  }, [style])

  if (!fontsLoaded) {
    return null
  }

  return (
    <Text
      style={[
        {
          fontFamily,
          ...typographyVariantsConfig[variant],
        },
        style,
      ]}
    >
      {children}
    </Text>
  )
})
`

**Comment by eserbina652** [comment]
Here you are

`
interface IProps {
  children: ReactNode
  style?: StyleProp<TextStyle>
  variant?: keyof typeof typographyVariantsConfig
}

const getFontFamilyByWeight = (weight: TFontWeights): string =>
  typographyFontsConfig[weight]

export const Typography = memo(function Typography({
  children,
  style,
  variant = 'h5',
}: IProps) {
  const [fontsLoaded] = useFonts({
    'SimplonNorm-Light-WebS': require('@fonts/SimplonNorm-Light-WebS.otf'),
    'SimplonNorm-Regular': require('@fonts/SimplonNorm-Regular.otf'),
    'SimplonNorm-Medium-WebS': require('@fonts/SimplonNorm-Medium-WebS.otf'),
    'SimplonNorm-Bold-WebS': require('@fonts/SimplonNorm-Bold-WebS.otf'),
  })

  const fontFamily = useMemo(() => {
    let fontWeight = undefined

    if (style && typeof style === 'object') {
      fontWeight = (style as TextStyle).fontWeight
    }

    return getFontFamilyByWeight(fontWeight as TFontWeights)
  }, [style])

  if (!fontsLoaded) {
    return null
  }

  return (
    <Text style={[{ fontFamily, ...typographyVariantsConfig[variant] }, style ]} >
      {children}
    </Text>
  )
})
`
