### ISSUE TITLE
NSPrivacyAccessedAPICategoryFileTimestamp & NSPrivacyAccessedAPICategoryDiskSpace

### ISSUE THREAD

**Issue by jeokeefe** [expo/expo#27677]
### Minimal reproducible example

My app contains the "Appsflyer SDK" if that is causing this.

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Starting today (3/14/2024) apple is sending an email when publishing a new versions that complains about the NSPrivacyAccessedAPICategoryDiskSpace & NSPrivacyAccessedAPICategoryFileTimestamp - ITMS-91053: Missing API declaration. How can we set this with Expo? They will no longer accept the builds after May 1st.

ITMS-91053: Missing API declaration - Your app’s code in the “YachtWave” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “YachtWave” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.6 => 0.17.6
      expo: ^50.0.13 => 50.0.13
      metro: ^0.80.6 => 0.80.6
      react: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by SaladDays831** [comment]
I'm also running into this
It seems like the Appsflyer docs state that they use 3 of the 4 APIs that Apple is complaining to me about
https://support.appsflyer.com/hc/en-us/articles/21677433322641-Privacy-Manifest

I assume the Appsflyer doc needs to be updated to also include `NSPrivacyAccessedAPICategoryDiskSpace`

**Comment by phil-hudson** [comment]
Also getting this and not using AppsFlyer - I assume this is a general Expo issue?

**Comment by mluiten** [comment]
Seems like a duplicate of https://github.com/expo/expo/issues/27678, although not specifically about Appsflyer.

Expo team (and component authors) say they working on it and should have a fix before the deadline. Although if it's Appsflyer that has a react-native / expo package, it might be up to them to add a privacy manifest to their pods?

**Comment by SaladDays831** [comment]
Oh lol I thought this was an issue  in the AppsFlyer GitHub 😅

It's true that they have to add the xcprivacy file to their SDK and they mentioned 2w ago that it's gonna be included in the next release, can't find the issue I saw this under though

**Comment by butri71** [comment]
Did a release yesterday on SDK 49 and getting the same warning message. I'm curious to see what fix for expo will look like since it'd be too late to include it in a new SDK since deadline is May 2024

**Comment by VadymBezsmertnyi** [comment]
I also received the 'happiness letter'; did anyone find a solution for Expo?

**Comment by timknapp12** [comment]
I too am using EAS build and got an email from Apple on my last build stating that in May I will need to correct the issues with: NSPrivacyAccessedAPICategoryUserDefaults, NSPrivacyAccessedAPICategorySystemBootTime, NSPrivacyAccessedAPICategoryDiskSpace, NSPrivacyAccessedAPICategoryFileTimestamp. I would love to not have to eject from expo to comply with this

**Comment by timknapp12** [comment]
Looks like this issue has more details: https://github.com/expo/expo/issues/27796
