### ISSUE TITLE
The expo-linking package does not open an external application

### ISSUE THREAD

**Issue by TsplayerT** [expo/expo#27688]
### Minimal reproducible example

https://snack.expo.dev/@tsplayert/example

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

The openURL function cannot find the newly downloaded image file 😔
`openURL` generates a **Toast** message saying `media not found`

```typescript
import * as FileSystem from "expo-file-system";
import * as Linking from "expo-linking";

// imageAPI -> https://cdn2.thecatapi.com/images/tOGSsMx5J.jpg

async function showImageAsync(imageAPI: string): Promise<void> {
    try {
      const fileName = imageAPI.substring(imageAPI.lastIndexOf('/') + 1);
      // filePath -> tOGSsMx5J.jpg
      
      const filePath = `${FileSystem.documentDirectory}/${fileName}`;
      // filePath -> file:///data/user/0/com.package.test/files/tOGSsMx5J.jpg

      const fileDownloaded = await FileSystem.downloadAsync(imageAPI, filePath);

      const fileContent = await FileSystem.getContentUriAsync(fileDownloaded.uri);
      // fileContent -> content://com.package.test.FileSystemFileProvider/expo_files/tOGSsMx5J.jpg
      
      const canOpenURL = await Linking.canOpenURL(fileContent);
      // canOpenURL -> true

      if (canOpenURL) {
        await Linking.openURL(fileContent);
      }
    } catch (error) {
      console.log("showImageAsync", error);
    }
}
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.11 => 50.0.13
      react: 18.2.0 => 18.2.0
      react-native: 0.73.5 => 0.73.5
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by aleqsio** [comment]
Hi @TsplayerT, the `FileSystem.documentDirectory` is private to your application, so the image viewer is unable to find the media file you save there. You could use SAF or maybe intents to achieve this behavior.
