### ISSUE TITLE
Splash image not shown with white screen instead (without expo-splash-screen installed)

### ISSUE THREAD

**Issue by alickcai** [expo/expo#27692]
### Minimal reproducible example

https://github.com/alickcai/exporpc.git

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

This issue happens only on build version Android (not in Expo Go and iOS).
When App is started in device, splash image is not shown with white screen.

And this happens after SDK 50 upgrade...

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22631
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^50.0.13 => 50.0.13
      react: ^18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by lucasvnborges** [comment]
you tested using a splash screen file other than standard?

**Comment by alickcai** [comment]
yes, it's 1024*1024 image and correctly shown in iOS devices

**Comment by JoezerSmaniotto** [comment]
I have the same problem, this only happens on ANDROID.

**Comment by JoezerSmaniotto** [comment]
the last comment says that as of version 50.0.3 it has been resolved
https://github.com/expo/expo/issues/26491

**Comment by alickcai** [comment]
Seems not...my version is 50.0.13

**Comment by alickcai** [comment]
any update from Expo? 3 weeks already...

**Comment by JoezerSmaniotto** [comment]
A palliative solution would be this one.
https://github.com/expo/expo/issues/26811

** "env": {
        "EX_UPDATES_ANDROID_DELAY_LOAD_APP": "false"
      }**

**Comment by alickcai** [comment]
This doesn't work in my case...

**Comment by Kudo** [comment]
hi there! from sdk-50, expo-splash-screen is not implicitly installed by default. please try `npx expo install expo-splash-screen` and see whether it works for you.

sorry we didn't mention this breaking chance clearly in sdk 50 release. will try to address this.

**Comment by alickcai** [comment]
npx expo install expo-splash-screen

this works and has solved the issue, thanks @Kudo

**Comment by Kudo** [comment]
@alickcai cool, thanks for the confirmation. i'm closing this issue. if there are any other issues, please let me know.
