### ISSUE TITLE
Expo -> How can I use i18n on different page

### ISSUE THREAD

**Issue by ycldz** [expo/expo#27695]
### Summary

"expo": "^49.0.0"
"expo-localisation": "~14.3.0"
"i18n-js": "4.2.2" --> (current version gives error for "make-plural" library)

https://docs.expo.dev/guides/localization/#other-translation-libraries

I installed the i18n library according to the instructions at the address above

I added the following code into my "_layout.tsx" file in the "app" folder and the "welcome" message works properly. 

```
import { getLocales } from 'expo-localization';
import { I18n } from 'i18n-js';

const i18n = new I18n({
  en: { welcome: 'Welcome' },
  en: { welcome: 'Hello' },
});

i18n.locale = getLocales()[0].languageCode;
i18n.enableFallback = true;

console.log(i18n.t('welcome'));
```

But I don't know how to use it in my other subpages. For example, I add the following code to my "app -> (tabs) -> home -> main.tsx" file, but "TypeError: _i18nJs.I18n.t is not a function (it is undefined)" error.

```
import { I18n } from 'i18n-js'
<Text>{I18n.t('welcome')}</Text>
```

How can I fix this problem.

### Link to the related docs page

https://docs.expo.dev/guides/localization/#other-translation-libraries

**Comment by lucasvnborges** [comment]
try using the https://react.i18next.com/latest/using-with-hooks

**Comment by ycldz** [comment]
https://stackoverflow.com/questions/78166917/how-can-i-use-i18n-on-different-page-with-expo

Thank you for the answers, I solved the problem as in the link above.
