### ISSUE TITLE
router.push and router.dismiss comments should be swapped

### ISSUE THREAD

**Issue by ljukas** [expo/expo#27691]
### Minimal reproducible example

Not needed

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

The comments for the router.push and router.dismiss functions seems the inverted, se screenshot

![image](https://github.com/expo/expo/assets/11976354/06a85c20-f404-4551-a371-7f159f60f14f)

### Environment

Not needed

**Comment by lucasvnborges** [comment]
could explain how you found this file?

**Comment by ljukas** [comment]
https://github.com/expo/expo/assets/11976354/d7c796c4-7570-4bc9-a3a9-c685b9d72286

I just ctrl+click `router.navigate`, se video. expo-router 3.4.8

**Comment by marklawlor** [comment]
Fixed in #27412, should be in the next release
