### ISSUE TITLE
Expo keeps rebuilding infinitely after hitting a warning

### ISSUE THREAD

**Issue by DanielEdrisian** [expo/expo#27707]
### Summary

Whenever I run my expo app, if it hits a warning it starts rebuilding infinitely:

<img width="827" alt="Screenshot 2024-03-15 at 11 23 25 AM" src="https://github.com/expo/expo/assets/11810973/d918c729-ce84-4f98-b586-9a06dd31bc87">

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.1 => 50.0.8
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Minimal reproducible example

I cannot reproduce outside of my work project.

**Comment by brentvatne** [comment]
hi there! it'll be impossible for us to guess what might be wrong without a reproducible example. see the [manual debugging guide](https://github.com/expo/fyi/blob/main/manual-debugging.md) for tips on how to isolate the issue and potentially reproduce in a minimal way (or possibly find the underlying issue in your particular project)
