### ISSUE TITLE
Preview and production builds break on multiple screen density assets, eg @2x @3x.

### ISSUE THREAD

**Issue by chris-hud** [expo/expo#27731]
### Summary

Please see the git repo included and update eas company/project details as I stripped mine out.

When I create a Preview or Production build, any assets that have support for multiple screen densities fail. This occurs on the preview or production builds, it does not occur on development or simulator builds or when I build locally. I'm also able to get the assets to load on preview/production builds by sending up an eas update following the original build.

The Repo included has 
- a return icon with only one density supported, return.png. 
- a snooze icon with multiple densities.
- a checkbox component provided by a third party lib that has multiple densities for the check within node-modules.

The repo puts all these assets on one screen. You'll notice the return icon shows up, but the snooze icon and the check within the checkbox do not load.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

    "expo-dev-client": "~3.3.8",
    "expo-updates": "~0.24.11",
    "react-native": "0.73.4",

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.1 - /opt/homebrew/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 9.8.0 - /opt/homebrew/bin/npm
      Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.7 => 50.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.5.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo

https://github.com/chris-hud/test-app

**Comment by douglowder** [comment]
Your issue is being caused by the presence of an image with a fractional size, specifically `snooze@1.5x.png`. The updates asset map does not support fractional sizes. If you remove that image, the problem is resolved.

Note that Apple only recommends `@1x`, `@2x`, and `@3x`. See https://developer.apple.com/design/human-interface-guidelines/images
