### ISSUE TITLE
Unable to find a specification for `EXCore` depended upon by `EXFirebaseCrashlytics`

### ISSUE THREAD

**Issue by jorgefernandes** [expo/expo#2774]
### Environment

Expo CLI 2.4.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.4.0

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/jorgefernandes-cca4bf06-05f8-4dc4-b20d-7e4dc83d9856.tar.gz

IOS
Android
Detached
Expo SDK 26.0.0

### Steps to Reproduce

1. Install expo-firebase-app and expo-firebase-crashlytics via yarn
2. Add each one Cocoapods dependency
3. Run pod install

### Expected Behavior

Expect instalation complete

### Actual Behavior

Instalation stop and terminal prints Unable to find a specification for `EXCore` depended upon by `EXFirebaseCrashlytics`

**Comment by sjchmiela** [comment]
Hey, @jorgefernandes! `expo-firebase-crashlytics` is a universal module. We've introduced this concept in SDK29 and unfortunately you'll need to upgrade to at least SDK29 to be able to use this library. 😕 

[Instructions](https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf#f233) helping developers upgrade their ExpoKit projects to SDK29 mention that you'll need to update your `Podfile` to look similar to [this gist](https://gist.github.com/brentvatne/6bc4b24031e187d2c760d28de3ed4f97). Notice `EXCore` pod definition there — this will allow `expo-firebase-crashlytics` install without complaints. 🙂 

I'll close this issue tentatively, feel free to reopen it or submit a new issue with another problem if you encounter any!
