### ISSUE TITLE
Changes to app.json not reflected in subsequent Android builds

### ISSUE THREAD

**Issue by GertSallaerts** [expo/expo#27746]
### Minimal reproducible example

https://github.com/ambassify/expo-constants-sync-bug

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

After you make changes to the app.json file and run `npx expo run:android`, the changes aren't reflected in the output of `expo-constants`. This isn't resolved if you run `npx expo prebuild` first either. Only `npx expo prebuild --clean` resolves the issue. On iOS, on the other hand, changes are immediately reflected after running `npx expo run:ios`.

It isn't reproducible with `expo-dev-client` because it has a different way of loading the manifest, it doesn't use the `app.json` embedded in the native build.

### Environment

```
expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 14.3.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
  IDEs:
    Android Studio: 2023.2 AI-232.10227.8.2321.11479570
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by Kudo** [comment]
hi there! we would recommend to run with `prebuild --clean` whenever you change app.json. not all config-plugins could support incremental change under the hood.

for this specific case, this is an optimization of android gradle to cache the building result. if you need incremental changes, you could try to run `./gradlew clean` before run:android.
