### ISSUE TITLE
Text prop `adjustsFontSizeToFit` doesn't work on IOS and WEB

### ISSUE THREAD

**Issue by vlanemcev** [expo/expo#27747]
### Minimal reproducible example

https://snack.expo.dev/jWTRElQs9?platform=ios

### What platform(s) does this occur on?

iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

`adjustsFontSizeToFit` parameter in Text component does not rescale text inside Text component on IOS and WEB platforms.

This issue is duplication of React Native repository issue: 
https://github.com/facebook/react-native/issues/34138#issuecomment-1895549453

Here's the expo snacks for reproduce (thanks @MrSquaare for providing them).

https://snack.expo.dev/jWTRElQs9?platform=ios
https://snack.expo.dev/jWTRElQs9?platform=web

### Environment

It's reproducible on the latest Expo SDK 49 and 50 as well with default settings. 

Environment: iOS Simulator, IPhone 11 Pro device, WEB. 

### Expo Doctor Diagnostics

There are no doctor errors or warnings regarding this issue.

**Comment by Kudo** [comment]
hi there!

since this is coming from react-native core, i would recommend to open the issue from the core.
fwiw, i tested this on react-native 0.74 and it's not work as well. after adding `numberOfLines={1}` it could work somehow.

**Comment by vlanemcev** [comment]
@Kudo Okay, thanks!
