### ISSUE TITLE
error build android apk the catalog file 'libs.versions.toml' doesnt exist

### ISSUE THREAD

**Issue by poedihippo** [expo/expo#27758]
### Minimal reproducible example

eas build android

### Did you reproduce this issue in a development build?

Yes

### Summary

FAILURE:
Build failed with an exception.
* What went wrong:
org.gradle.api.InvalidUserDataException: Invalid catalog definition:
  - Problem: In version catalog reactAndroidLibs, import of external catalog file failed.
    
    Reason: File '/home/expo/workingdir/build/packages/melandas-app/node_modules/react-native/gradle/libs.versions.toml' doesn't exist.
    
    Possible solution: Make sure that the catalog file 'libs.versions.toml' exists before importing it.
    
    For more information, please refer to https://docs.gradle.org/8.3/userguide/version_catalog_problems.html#catalog_file_does_not_exist in the Gradle documentation.
> Invalid catalog definition:
    - Problem: In version catalog reactAndroidLibs, import of external catalog file failed.
      
      Reason: File '/home/expo/workingdir/build/packages/melandas-app/node_modules/react-native/gradle/libs.versions.toml' doesn't exist.
Possible solution: Make sure that the catalog file 'libs.versions.toml' exists before importing it.
For more information, please refer to https://docs.gradle.org/8.3/userguide/version_catalog_problems.html#catalog_file_does_not_exist in the Gradle documentation.
* Try:

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 21.6.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 30, 31, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-28 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7 
      expo: ^49.0.0 => 49.0.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~6.2.4
Found invalid:
  @expo/prebuild-config@5.0.7
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

**Comment by carelmeyer** [comment]
was there a resolution to this issue?

**Comment by zsoro2** [comment]
> was there a resolution to this issue?

It happened with me today. Updated from expo 49 to 51, and got this 'libs.versions.toml' doesn't exist error.

I run this and fixed my problem, now build works. 

`npx expo install --check`

**Comment by motogod** [comment]
@zsoro2 
I got the same issue when upgrade to expo 49.

What the result print when you type `npx expo install --check`

I get `Dependencies are up to date`, can't find any problem.
