### ISSUE TITLE
Expo Black Bar When StatusBar is Hidden

### ISSUE THREAD

**Issue by chadders404** [expo/expo#27767]
### Minimal reproducible example

https://github.com/chadders404/Expo-Black-Bar/

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

If StatusBar 'hidden' prop is set to true `<StatusBar hidden={true}`, a black bar appears where the status bar usually is (instead of disappearing). 

This only occurs on android devices with a punchole camera or notch. **Android devices without a notch or punch hole camera are uneffected.** 

See photo below:
![Demo photo](https://github.com/expo/expo/assets/99815730/a69bf0f7-09f3-4959-b382-458f9282961d)

3 android phones pictured. TCL, Samsung and Oppo.
2 phones on the left both have a notch or a punchole camera: the status bar turns black. 
1 phone on the right does not have a punch hole camera: the status bar is hidden as intended.

Expo Snack:
https://snack.expo.dev/@chadders404/blessed-blue-kiwi
Be sure to open it on an android device with a punch hole camera/ notch

It is possible to style things to render in the black area using `absolute` positioning, but they are behind the black bar so you can't see them.

Styling the status bar to be translucent/ transparent `<StatusBar hidden={true} backgroundColor={"transparent"} translucent />` does not change the behaviour.

The issue still persists once the app is compiled into an apk.

This bug has been around since I first experienced it in 2021, there are closed github threads about it with no solution. 

I really mean this: if there is ANYTHING I can do to help someone fix this, please let me know because it's been 2.5 years and it has effected a huge number of projects I've worked on. I really hope somebody is able to finally figure this bug out.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
i'm closing this since it's duplicated at #27771

**Comment by shubhamguptadream11** [comment]
Raised a PR to fix this issue: https://github.com/facebook/react-native/pull/46086
