### ISSUE TITLE
error when publising expo app bundle to itunes ios

### ISSUE THREAD

**Issue by foxdreamstudio** [expo/expo#2776]
hi , I have a problem when uploading my apps to iTunes using application loader, the error is look like this 

ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/ExpoKitApp.app/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit.”

I’m build the apps  using expo build:os, the build process is ok, bet the error show when i publish the apps on itunes using application loader, can anyone help?

    "expo": "^29.0.0",
    "react": "16.3.1",
    "react-native": "~0.55.2",

![image](https://user-images.githubusercontent.com/37882679/48931781-ab83b300-ef2a-11e8-841d-c9473d91f7fa.png)

**Comment by sjchmiela** [comment]
Hey, @foxdreamstudio! To fix the issue you'll have to upgrade your Xcode to v10. When releasing SDK31 we've upgraded all the machines to this version and it looks like apps built with Xcode 10 can't be uploaded with any older version of Xcode. About two weeks ago (after publishing) we've added information about this to release notes. Sorry for the inconvenience!

<img width="1248" alt="zrzut ekranu 2018-11-23 o 08 54 42" src="https://user-images.githubusercontent.com/1151041/48932702-8b89ca80-eefd-11e8-997b-c1f9e3c7bd16.png">
