### ISSUE TITLE
Black Bar when StatusBar hidden prop is true

### ISSUE THREAD

**Issue by chadders404** [expo/expo#27771]
### Summary

If the StatusBar 'hidden' prop is set to true `<StatusBar hidden={true}/>`, the status bar is replaced by a black bar instead of being hidden.

**This only occurs on android devices with a punchole camera or notch.** Android devices _without_ a notch or punch hole camera are uneffected.

See photo below:
![Demo photo](https://github.com/expo/expo/assets/99815730/8a066bf1-8940-4ac8-8aaf-4c631e7cc770)
All of these phones are android...
The two phones on the left both have front-facing cameras in the screen: the status bar is replaced by a black bar the same height as the camera notch.
The phone on the right does not have a front facing camera on the screen: the status bar is hidden normally. No black bar.

Expo Snack:
https://snack.expo.dev/@chadders404/blessed-blue-kiwi
Be sure to open it on an android device with a punch hole camera/ notch

It is possible to style things to render in the black area using absolute positioning, but they are behind the black bar so you can't see them.

Styling the status bar to be translucent/ transparent `<StatusBar hidden={true} backgroundColor={"transparent"} translucent />` does not change the behaviour.

`<SafeAreaContext>` does not change the behaviour. Changing the `androidStatusBar` property in App.json does not change the behaviour.

The issue still persists once the app is compiled into an apk.

This bug has been around since I first experienced it in 2021, there are closed github threads about it with no solution.

I really mean this: if there is ANYTHING I can do to help someone fix this, please let me know because it's been at least two and a half years and it has effected a huge number of projects I've worked on. I really hope somebody is able to figure this bug out.

### What platform(s) does this occur on?

Android

### SDK Version

47, 48, 49, 50.0.14

### Environment

expo-env-info 1.2.0 environment info:
System:
OS: macOS 13.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.13.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 9.8.0 - /usr/local/bin/npm
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9477386
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
expo: ^50.0.14 => 50.0.14
react: 18.2.0 => 18.2.0
react-native: 0.73.5 => 0.73.5
npmGlobalPackages:
eas-cli: 5.9.1
Expo Workflow: managed

### Minimal reproducible example

Github Repo:
https://snack.expo.dev/@chadders404/blessed-blue-kiwi

Expo Snack:
https://github.com/chadders404/Expo-Black-Bar/

be sure to open on an android device with a punch hole camera or notch

**Comment by Kudo** [comment]
hi there!

to hide the status bar entirely, according to [our doc](https://docs.expo.dev/guides/configuring-statusbar/#configure-the-status-bar-while-app-is-loading-android-only), rather than using the `<StatusBar>` component. you should use the app.json. after these steps, it should work for you:
1. remove the <StatusBar> from App.js
2. add the following property to app.json
```
    "androidStatusBar": {
      "translucent": true
    },
```

**Comment by Kudo** [comment]
it did work!
<img src="https://github.com/expo/expo/assets/46429/ff37d785-f68e-4559-8d88-e11f38dcc24a" width="50%"/>

some notes
- snack doesn't support customized app.json, so this is not supported on snack
- trying to restart the server by `npx expo start -c`
- this is my patch upon your repro project

```patch
diff --git a/App.js b/App.js
index 3416407..1549ef3 100644
--- a/App.js
+++ b/App.js
@@ -4,7 +4,6 @@ import { Text, SafeAreaView, StyleSheet, StatusBar } from "react-native";
 export default function App() {
   return (
     <SafeAreaView style={styles.container}>
-      <StatusBar hidden={true} backgroundColor={"transparent"} translucent />
       <Text style={styles.paragraph}>
         Open this snack on an android device with a punchole camera or notch to
         see the black bar where the status bar would usually be at the top of
diff --git a/app.json b/app.json
index 7cb7733..cd446a4 100644
--- a/app.json
+++ b/app.json
@@ -23,8 +23,11 @@
         "backgroundColor": "#ffffff"
       }
     },
+    "androidStatusBar": {
+      "translucent": true
+    },
     "web": {
       "favicon": "./assets/favicon.png"
     }
   }
-}
\ No newline at end of file
+}
```

**Comment by chadders404** [comment]
> it did work! <img alt="" width="50%" src="https://private-user-images.githubusercontent.com/46429/316897546-ff37d785-f68e-4559-8d88-e11f38dcc24a.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDMzNDUsIm5iZiI6MTcxMTY0MzA0NSwicGF0aCI6Ii80NjQyOS8zMTY4OTc1NDYtZmYzN2Q3ODUtZjY4ZS00NTU5LThkODgtZTExZjM4ZGNjMjRhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE2MjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOTRiYWU3Zjk1MzQ1N2JlNzkwM2YyNzkwMGE0NDc1OTk2MWI4YWE5OTIzNWUyYWVmZDljZGFhNjllNmY4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEm5OZ2WlTKt3Svq6igOaCbNvFYCZgL4bgyQ7fbJuGw">
> 
> some notes
> 
> * snack doesn't support customized app.json, so this is not supported on snack
> * trying to restart the server by `npx expo start -c`
> * this is my patch upon your repro project
> 
> ```diff
> diff --git a/App.js b/App.js
> index 3416407..1549ef3 100644
> --- a/App.js
> +++ b/App.js
> @@ -4,7 +4,6 @@ import { Text, SafeAreaView, StyleSheet, StatusBar } from "react-native";
>  export default function App() {
>    return (
>      <SafeAreaView style={styles.container}>
> -      <StatusBar hidden={true} backgroundColor={"transparent"} translucent />
>        <Text style={styles.paragraph}>
>          Open this snack on an android device with a punchole camera or notch to
>          see the black bar where the status bar would usually be at the top of
> diff --git a/app.json b/app.json
> index 7cb7733..cd446a4 100644
> --- a/app.json
> +++ b/app.json
> @@ -23,8 +23,11 @@
>          "backgroundColor": "#ffffff"
>        }
>      },
> +    "androidStatusBar": {
> +      "translucent": true
> +    },
>      "web": {
>        "favicon": "./assets/favicon.png"
>      }
>    }
> -}
> \ No newline at end of file
> +}
> ```

I don't mean to be rude but the status bar is still _clearly visible_ in your photo. **The idea of hiding the status bar is that the status bar does not render at all**. Your changes make the background of the status bar transparent, but the status bar is not hidden.

I think you may have misunderstood the problem and I apologise if I was not clear. Please reopen the thread.

**Comment by Kudo** [comment]
i'm sorry to misinterpret your message. what you need an android new feature called [display cutout](https://developer.android.com/develop/ui/views/layout/display-cutout), which requires minimum api v28. if you want to use this feature in your app, you could try either writing native modules to mutate the current window state or just use the following config-plugin to apply to whole activity.

the patch is based on your Expo-Black-Bar repro but adding a config-plugin to add the style

```diff
diff --git a/app.json b/app.json
index 7cb7733..5f30af7 100644
--- a/app.json
+++ b/app.json
@@ -25,6 +25,7 @@
     },
     "web": {
       "favicon": "./assets/favicon.png"
-    }
+    },
+    "plugins": ["./withAndroidDisplayCutout"]
   }
 }
\ No newline at end of file
diff --git a/withAndroidDisplayCutout.js b/withAndroidDisplayCutout.js
new file mode 100644
index 0000000..6a0d5c7
--- /dev/null
+++ b/withAndroidDisplayCutout.js
@@ -0,0 +1,51 @@
+const { withDangerousMod, AndroidConfig } = require('expo/config-plugins');
+const fs = require('fs/promises');
+const path = require('path');
+
+const withAndroidDisplayCutout = (config) => {
+  return withDangerousMod(config, [
+    'android',
+    async (config) => {
+      const resDir = await AndroidConfig.Paths.getResourceFolderAsync(
+        config.modRequest.projectRoot
+      );
+      const valuesV27Path = path.join(resDir, 'values-v27');
+      const stylesFilePath = path.resolve(valuesV27Path, 'styles.xml');
+
+      if (!(await pathExistsAsync(valuesV27Path))) {
+        await fs.mkdir(valuesV27Path, { recursive: true });
+      }
+
+      let stylesContent;
+      if (await pathExistsAsync(stylesFilePath)) {
+        stylesContent = await fs.readFile(stylesFilePath, 'utf8');
+      } else {
+        stylesContent = `<?xml version="1.0" encoding="utf-8"?>
+<resources>
+    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
+        <!-- Items will be added here -->
+    </style>
+</resources>`;
+      }
+
+      if (
+        !stylesContent.includes(
+          'name="android:windowLayoutInDisplayCutoutMode"'
+        )
+      ) {
+        const replacement = `  <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>\n    </style>`;
+        stylesContent = stylesContent.replace('</style>', replacement);
+      }
+
+      await fs.writeFile(stylesFilePath, stylesContent);
+
+      return config;
+    },
+  ]);
+};
+
+async function pathExistsAsync(file) {
+  return !!(await fs.stat(file).catch(() => null)) ?? false;
+}
+
+module.exports = withAndroidDisplayCutout;

```

after applying the patch, you could run `npx expo run:android` to prebuild & run your app.

**Comment by chadders404** [comment]
> npx expo run:android

Thank you so much for writing this patch. Of course it won't work in Expo Go, but it works in Prebuild which is plenty good enough for me.

I have updated my Github repo to include instructions on this fix for anyone in the future viewing this thread: 
https://github.com/chadders404/Expo-Black-Bar/blob/main/README.md

Thanks once again :)

**Comment by Fgabz** [comment]
Confirm works well !

**Comment by gameveloster** [comment]
Any solution to fix this issue with iphones?

**Comment by shubhamguptadream11** [comment]
Raised a PR to fix this issue here: https://github.com/facebook/react-native/pull/46086
