### ISSUE TITLE
how can i change the local language from English to Chinese?

### ISSUE THREAD

**Issue by NameNull** [expo/expo#2777]
that happens just in ios system. 
the current situation is: (like below images)
![image](https://user-images.githubusercontent.com/11754843/48932761-8302b580-ef38-11e8-95f8-3e1abd60910f.png)
![image](https://user-images.githubusercontent.com/11754843/48932784-96ae1c00-ef38-11e8-953d-9d81d8ce5046.png)
![image](https://user-images.githubusercontent.com/11754843/48932794-a75e9200-ef38-11e8-81dd-10cecc2ce6fa.png)

I want to change these english text to chinese ,  i had search a lot of docs and found that that can solved by 
Detaching Expo project into a JS-and-native ExpoKit project. but i don't want to do that（now that i choose expo rather than react-native）

**Comment by esamelson** [comment]
Hi @NameNull - as of now I believe you'll need to detach and follow these instructions in order to achieve this: https://stackoverflow.com/questions/25871815/changing-the-development-language-in-xcode/36926728#36926728 . Apologies for the inconvenience 😞

**Comment by NameNull** [comment]
Do you plan to add this feature to the future expo versions?
