### ISSUE TITLE
How to  open my designed for asking permissions of Camera and Camera Roll?

### ISSUE THREAD

**Issue by tudip-technologies** [expo/expo#2778]
Actually, I need to take photos using my app I went through the Permissions SDK of the expo. There I found that when we use the askAsync function of it. It opens the pop-up fo the device only for asking permission. But I want to my open my customize pop up for asking permissions. Is there any way to implement that or any other way using which I can set the permissions manually.

Thanks in advance.

**Comment by sjchmiela** [comment]
Hey, @tudip-technologies! What do you mean by _customizing the pop up_?

When it comes to iOS, you can customize the message that is displayed in the pop up by adding the `infoPlist` object to `app.json` — see [Deploying to App Stores, section System permissions dialogs on iOS](https://docs.expo.io/versions/v31.0.0/distribution/app-stores#system-permissions-dialogs-on-ios).

When it comes to Android, it seems you can't customize the dialog in any way. 😕 [Source](https://stackoverflow.com/a/33266342/1123156)
