### ISSUE TITLE
Wrong script src on export -p web --dev

### ISSUE THREAD

**Issue by jparksecurity** [expo/expo#27803]
### Summary

**what the expected behavior is**

When running `yarn expo export --platform web --dev`, it should generate `dist/index.html` with the correct App entry path.

**what is actually happening**

`dist/index.html` is generated with `<script src="//Users/**/index-src/node_modules/expo/AppEntry.js" defer></script>`

The path has one more `/` in the beginning.

* `**` is the location of the `index-src`.

### What platform(s) does this occur on?

Web

### SDK Version

50

### Environment

```
  expo-env-info 1.2.0 environment info:
   System:
     OS: macOS 14.4
     Shell: 5.9 - /bin/zsh
   Binaries:
     Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
     Yarn: 4.0.1 - ~/.nvm/versions/node/v20.11.1/bin/yarn
     npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
   SDKs:
     iOS SDK:
       Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
   IDEs:
     Android Studio: 2023.1 AI-231.9392.1.2311.11330709
     Xcode: 15.1/15C65 - /usr/bin/xcodebuild
   npmPackages:
     babel-preset-expo: ^10.0.0 => 10.0.1 
     expo: ~50.0.11 => 50.0.11 
     react: 18.2.0 => 18.2.0 
     react-dom: 18.2.0 => 18.2.0 
     react-native: 0.73.4 => 0.73.4 
     react-native-web: ^0.19.10 => 0.19.10 
   Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/jparksecurity/index-src

Run `yarn export --platform web --dev`, then check `script` tag in `dist/index.html`.

**Comment by minuitagency** [comment]
same here, can't build for Tauri because of it

**Comment by jparksecurity** [comment]
@minuitagency You can manually update `index.html` after building the bundle for now. Update the `src` in the `script` tag.

**Comment by jparksecurity** [comment]
@keith-kurak FYI

**Comment by minuitagency** [comment]
yeah thanks @jparksecurity but if i try to replace manually, i have the same issues with the fonts: 
<img width="1090" alt="image" src="https://github.com/expo/expo/assets/38316888/c5f91348-5e08-40bb-9130-56933d700d45">
But we app works well when deployed on Vercel... any idea? I need the local build to bundle the macOS app with Tauri,
 
Thanks, 

Théo

**Comment by kbqdev** [comment]
+1 same issues

**Comment by jparksecurity** [comment]
@minuitagency Are you bundling your app with `--dev` option? My issue is coming from using `--dev`. Everything works when I just bundle without `--dev`.

**Comment by jparksecurity** [comment]
@minuitagency Unfortunately, that isn't my case. I think it's a different issue.

Wanna open a new issue with a reproducible example?
