### ISSUE TITLE
[expo-av]: fullscreen video overrides navigation bar properties

### ISSUE THREAD

**Issue by ParkerMJones** [expo/expo#27802]
### Minimal reproducible example

https://snack.expo.dev/@parkerjones/expo-av-fullscreen-navigation-bar-issue

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Opening full screen mode in Expo-AV `Video` component overrides any attributes set on the Navigation Bar.

I'm trying to create a Youtube-like UX in the video player, i.e. when a user goes fullscreen, change the navigation bar visibility to `sticky-immersive`.  When I open a video to fullscreen, the Navigation Bar always renders with it's default properties. This applies not only to `visibility` but `backgroundColor` as well. Expected behavior is that in fullscreen the navigation bar respects the properties I've set for it. I'm using a Samsung Galaxy S22. Happens in both Expo Go and development builds.

I've tried several different methods to resolve this, including using different Navigation Bar libraries, using fixed values like `"visiblility": "hidden"` in `app.json` with no `onFullscreenUpdate` changes, using the video's ref to open fullscreen instead of native controls. Each approach results in the settings for Navigation Bar being overridden once the video enters fullscreen mode on Android.

You can see most clearly with no `app.json` settings. Try setting `NavigationBar.setVisibilityAsync("hidden")` in the`onFullscreenUpdate` prop of the `<Video>` player, when `PLAYER_WILL_PRESENT` or `PLAYER_DID_PRESENT`. You'll see that the requested changes don't take effect until the fullscreen view is collapsed.

I'm following the suggested approach from the [fyi/android-navigation-bar-visible-deprecated.md](https://github.com/expo/fyi/blob/main/android-navigation-bar-visible-deprecated.md).

https://github.com/expo/expo/assets/80937296/a8b86c23-81d9-46d9-ac77-3332e795101e

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.5.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

Didn't find any issues with the project!

**Comment by elliotdickison** [comment]
@ParkerMJones I'm experiencing this as well. What was the reason for closing this issue? Did you find a workaround?

**Comment by ParkerMJones** [comment]
> @ParkerMJones I'm experiencing this as well. What was the reason for closing this issue? Did you find a workaround?

@elliotdickison I did not find a workaround. Ended up building a custom video solution with react-native-video. It became unclear whether or not this was expected behavior. Given the fullscreen api description:

> Note that even if `useNativeControls` is set to `false`, native controls will be visible in fullscreen mode.
 
and the fact that the [React Native modal ignores Android navigation bar properties](https://github.com/expo/expo/issues/7799)

and that [react-native-video doesn't provide a truly fullscreen method for android yet](https://github.com/react-native-video/react-native-video/issues/323)

I started to think maybe Expo is rendering the fullscreen mode themselves within a Modal, or something like that. I wasn't able to verify that idea. But regardless, with this issue and the lack of custom controls in fullscreen, it became clear this library wouldn't be robust enough for my needs. Can reopen if you think it's worth further investigation.

**Comment by elliotdickison** [comment]
@ParkerMJones Thanks for the details. I think it makes sense to leave the issue open even if you've worked around it with another library.

**Comment by GusBTB** [comment]
Hi, I'm facing this issue too, any fix will happen? or some solution? I tried to use react-native-video but it seems it conficts with expo evironment

**Comment by JKKholmatov** [comment]
Hi, having the same issue, any updates?
