### ISSUE TITLE
ExpoMetroConfig.loadAsync is not a function

### ISSUE THREAD

**Issue by AliSinaYOusofi** [expo/expo#27837]
### Minimal reproducible example

https://github.com

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

when i run expo start --localhost --android it gives the following output: ExpoMetroConfig.loadAsync is not a function
I have tried deleting node_modules and reinstalling them. 
The project is built using expo.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.4.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9514443
    npmPackages:
      @expo/metro-config: ^0.17.6 => 0.17.6
      expo: ^50.0.0 => 50.0.14
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    Expo Workflow: bare

### Expo Doctor Diagnostics

npx expo-doctor
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by miteshdevg** [comment]
> ### Minimal reproducible example
> https://github.com
> 
> ### What platform(s) does this occur on?
> Android
> 
> ### Did you reproduce this issue in a development build?
> Yes
> 
> ### Summary
> when i run expo start --localhost --android it gives the following output: ExpoMetroConfig.loadAsync is not a function I have tried deleting node_modules and reinstalling them. The project is built using expo.
> 
> ### Environment
> expo-env-info 1.2.0 environment info: System: OS: Windows 11 10.0.22631 Binaries: Node: 20.10.0 - C:\Program Files\nodejs\node.EXE Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD npm: 9.4.2 - C:\Program Files\nodejs\npm.CMD IDEs: Android Studio: AI-221.6008.13.2211.9514443 npmPackages: @expo/metro-config: ^0.17.6 => 0.17.6 expo: ^50.0.0 => 50.0.14 react: 18.2.0 => 18.2.0 react-native: 0.73.6 => 0.73.6 Expo Workflow: bare
> 
> ### Expo Doctor Diagnostics
> npx expo-doctor WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.
> 
> ✔ Check Expo config for common issues ✔ Check package.json for common issues ✔ Check dependencies for packages that should not be installed directly ✔ Check for common project setup issues ✔ Check npm/ yarn versions ✔ Check for issues with metro config ✔ Check Expo config (app.json/ app.config.js) schema ✔ Check that native modules do not use incompatible support packages ✔ Check for legacy global CLI installed locally ✔ Check that packages match versions required by installed Expo SDK ✔ Check that native modules use compatible support package versions for installed Expo SDK
> 
> Didn't find any issues with the project!

Hello 
have you found any solution ?

**Comment by RichardBoyewa** [comment]
Here is a fix that works, and according to the comment [here](https://github.com/expo/expo/issues/26593#issuecomment-1908642033) installing `@expo/config` or `@expo/metro-config` is not necessary.
Instead of starting your app with the normal 

```bash
expo start
```

Do this instead

```bash
npx expo start
```

That should resolve this issue.

**Comment by anthony0000** [comment]
run `npm uninstall -g expo-cli --save` in your main terminal, not VS code terminal, then run `npx expo start` in your terminal

**Comment by miteshdevg** [comment]
```
npm install @expo/config@8.1.1
npm install @expo/metro-config@0.10.0
```

install above and after start metro
