### ISSUE TITLE
Expo Router Hide Drawer Screen

### ISSUE THREAD

**Issue by andrewchester1** [expo/expo#27851]
### Minimal reproducible example

Any app that uses expo router

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I am currently converting an app from react-navigation to expo-router. This is a white labeled app, that uses ternary operators to toggle screen off/on in a drawer navigator. In the drawer unit with expo router, the screen name shows up if the screen is toggled off. 

I noticed that the Tabs have an href param to "hide" a specific tab(https://docs.expo.dev/router/advanced/tabs/#hiding-a-tab). This is the same functionality I am looking for in the Drawer navigator. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9477386
    npmPackages:
      expo: ~50.0.7 => 50.0.13
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by delacrucen** [comment]
That would be cool, and I understand the struggle on this one...

In the meanwhile, I've found this:
https://react-navigation.canny.io/feature-requests/p/add-option-to-hide-item-from-a-drawer
