### ISSUE TITLE
What a shame : default example doesn't work on IOS 17 ! and new projects too from Expo 50 !

### ISSUE THREAD

**Issue by codeourson** [expo/expo#27886]
### Minimal reproducible example

just generate a default project template in expo sdk 50

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Hi !

I use Iphone 12 with IOS 17.4.1. When i want to upgrade my project, **the screen's interactions don't work at all**. In my other device in IOS 16, it is ok.

So i try the default project template with IOS 17.4.1 and Expo Go : **i can't push buttons or interact with elements.**

When i modify text elements in the project, **changes happens but still not interactions screen available IOS 17 systems**

#You can also use the --template option with the create-expo-app command. Run npx create-expo-app --template to see the list of available templates.

Here is the package.json file obtenaited by your command-lines : 
`{
  "name": "demo",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~50.0.14",
    "expo-font": "~11.10.3",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.8",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "expo-web-browser": "~12.8.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.6",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "jest": "^29.2.1",
    "jest-expo": "~50.0.4",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  "private": true
}`

![file](https://github.com/expo/expo/assets/109912890/4eb438ce-1333-481b-a34c-83b60ee5ce33)

Thanks for the investigations.
In a friendly manner

### Environment

 System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

No errors :

Check Expo config for common issues
Check package.json for common issues
Check native tooling versions
Check dependencies for packages that should not be installed directly
Check for common project setup issues
Check npm/ yarn versions
Check for issues with metro config
Check Expo config (app.json/ app.config.js) schema
Check that native modules do not use incompatible support packages
Check for legacy global CLI installed locally
Check that packages match versions required by installed Expo SDK
Check that native modules use compatible support package versions for installed Expo SDK*

Didn't find any issues with the project!

**Comment by codeourson** [comment]
Hi again,

I answer to myself because of lack of your support.
My frien try to publish the project despite of issue with the simulator. The project works like a charm.
So it is a several bug with your simulator.

We think the issue is the Iphone 12 device. Because with Iphone 13, no issue with the Simulator.

**Comment by andreyBatov94** [comment]
Its because toogle menu dont render on your phone in Expo Go. 
You need shake your phone, and tabs start work.
You need disable toogle menu in expo go)
