### ISSUE TITLE
Expo Grouped Routes - Drawer No History

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#27889]
### Minimal reproducible example

https://github.com/NilsBaumgartner1994/expo-groups-drawer-history-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Maybe i missunderstood something but i have the following setup:
- A group (app) which holds a drawer. (https://docs.expo.dev/router/layouts/#groups)
- The drawer in (app) has 4 screens: foods, foods/id, buildings, building/id
- In m understanding, when navigating between those screens the history should be keeped right?
- Each screen has a pressable to show the current navigation history:

```
const navigation = useNavigation()
...
let historyObj = navigation.getState().history;
let historyStr = "";
for (let i = 0; i < historyObj.length; i++) {
	historyStr += historyObj[i].key + " ";
}
```

So when trying to recieve the history, i always only get the current route but not the other ones. What am i missing here?
Some variable to set like "keepDrawerHistory"?

### Environment

 ```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.11 => 50.0.11
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.4.0
    Expo Workflow: managed
```

**Comment by alanjhughes** [comment]
Hi - the setting the `backBehavior` prop to `backBehavior="history"` should be what you are looking for

**Comment by NilsBaumgartner1994** [comment]
So without that property the whole history is not even saved?

**Comment by NilsBaumgartner1994** [comment]
Wow that realy fixed that. Can believe that this is not default, nor any documentation in expo about that :D

**Comment by NilsBaumgartner1994** [comment]
Thank you very much.
