### ISSUE TITLE
Element Inspector shows behind an open modal making it impossible to inspect the elements of a modal

### ISSUE THREAD

**Issue by Valetek** [expo/expo#27927]
### Summary

When using dev client to test the application, if a modal is open the dev menu will appear behind the modal, making it impossible to debug the modal 

This is a duplication of https://github.com/expo/expo/issues/7989 that was closed and not reopened as outdated

Also using the latest update of expo go at the current date

### What platform(s) does this occur on?

Android

### SDK Version

49.0.21

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.5.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.8.0 - /usr/bin/npm
    npmPackages:
      expo: ^49.0.21 => 49.0.23 
      expo-router: ^2.0.14 => 2.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
    Expo Workflow: managed

### Minimal reproducible example

Opening a modal on this sdk version will make the bug happen

**Comment by brentvatne** [comment]
hi @Valetek - can you share a minimal reproducible example and a video recording of this? we're happy to investigate! 

<img width="512" alt="image" src="https://github.com/expo/expo/assets/90494/18142c99-576f-4e8e-839c-040a6102938a">
<img width="514" alt="image" src="https://github.com/expo/expo/assets/90494/e6eeb816-afae-432f-b417-8ee2fd32cc35">

**Comment by Valetek** [comment]
https://github.com/expo/expo/assets/34715110/c807df59-6b15-46fa-a8ca-a90b2ca25ef6

I made the modal transparent to make it explicite

The modal is clickable but the dev menu is not as behind de modal

**Comment by brentvatne** [comment]
@Valetek - if you can share a minimal reproducible repository on the latest sdk version then we would be happy to investigate!

**Comment by Valetek** [comment]
My case is not on the latest version and I can't migrate my project on it, will it be fixed if it's on the 49 sdk ?
