### ISSUE TITLE
[expo-screen-capture][Android 14][SDK 50] app crashes: The current activity is no longer available

### ISSUE THREAD

**Issue by pickle636** [expo/expo#27921]
### Minimal reproducible example

https://github.com/pickle636/ExampleApp

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Exception seems to occur only on Android 14 and only if you target Android SDK 34. I tested it on Android 13, and everything works as expected on that version.
The place where the exception occurs: https://github.com/expo/expo/blob/sdk-50/packages/expo-screen-capture/android/src/main/java/expo/modules/screencapture/ScreenCaptureModule.kt#L21

**Step-by-step instructions to reproduce this bug**:
1. Install `expo-screen-capture`.
2. Build the app (cd android && ./gradlew clean assembleRelease) and install (make sure your device is running Android 14).
3. Open the app and observe the log:
```xml
FATAL EXCEPTION: mqt_native_modules
  Process: com.anonymous.ExampleApp, PID: 3787
  com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': expo.modules.kotlin.exception.Exceptions$MissingActivity: The current activity is no longer available, js engine: hermes, stack:
  anonymous@1:631498
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16469
  metroRequire@1:16091
  anonymous@1:85735
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16469
  metroRequire@1:16091
  anonymous@1:82641
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16469
  metroRequire@1:16091
  anonymous@1:82293
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16469
  metroRequire@1:16091
  anonymous@1:81912
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16469
  metroRequire@1:16091
  anonymous@1:23481
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16469
  metroRequire@1:16091
  anonymous@1:23365
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16469
  metroRequire@1:16091
  anonymous@1:23182
  loadModuleImplementation@1:16921
  guardedLoadModule@1:16426
  metroRequire@1:16091
  global@1:15643
                                                                                                    
           at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
           at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
           at com.facebook.jni.NativeRunnable.run(Native Method)
           at android.os.Handler.handleCallback(Handler.java:958)
           at android.os.Handler.dispatchMessage(Handler.java:99)
           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
           at android.os.Looper.loopOnce(Looper.java:205)
           at android.os.Looper.loop(Looper.java:294)
           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
           at java.lang.Thread.run(Thread.java:1012)
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      • OS: Windows 11 10.0.22631
    Binaries:
      • Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
      • npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      • Android Studio: AI-232.10300.40.2321.11567975
    npmPackages:
      • expo: ~50.0.14 => 50.0.14
      • react: 18.2.0 => 18.2.0
      • react-native: 0.73.6 => 0.73.6
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by techgerm** [comment]
we're experiencing the exact same issue after updating the Expo SDK to 50 and the rest of our expo modules which includes `expo-screen-capture`.

@pickle636 were you able to find a workaround?

![Screenshot 2024-04-22 at 10 53 02 AM](https://github.com/expo/expo/assets/38846104/695a1c7e-b4ab-4f3e-bb92-ae1ef3509a75)
![Screenshot 2024-04-22 at 10 52 09 AM](https://github.com/expo/expo/assets/38846104/b262f1b8-da37-46eb-a49e-c0974b5207ba)

**Comment by techgerm** [comment]
After downgrading `expo-screen-capture` to `5.8.0` we're no longer seeing these crashes in production

**Comment by pickle636** [comment]
@techgerm Thanks!
And here's the [fix](https://github.com/expo/expo/pull/28338) (I hope). Apparently, it will be included in Expo SDK 51.

**Comment by techgerm** [comment]
@pickle636 good to know thanks for the info!

**Comment by lukmccall** [comment]
It should be fixed by https://github.com/expo/expo/pull/28244. That fix is included in SDK 51. If you are still facing the same issue on SDK 51, feel free to open a new ticket.

**Comment by jetaix** [comment]
thx @techgerm, working on my side.
