### ISSUE TITLE
[DOCS] How to enable the new architecture in bare workflow?

### ISSUE THREAD

**Issue by ceopaludetto** [expo/expo#27920]
### Summary

Currently in the docs, there's no mention on how to enable the new architecture on bare minimum template. I've tried `newArchEnabled = true` in `Podfile.properties.json` and also `RCT_NEW_ARCH_ENABLED=1` but none of them worked. To check, I've used the following piece of code:

```tsx
useEffect(() => {
  const uiManager = global?.nativeFabricUIManager ? 'Fabric' : 'Paper';
  console.log(`Using ${uiManager}`);
}, [])
```

I think the docs should include how to enable and also how to check if is enabled, since the expo cli supress the metro log (I think)
![image](https://github.com/expo/expo/assets/30508218/c36dfad2-05f6-48eb-9d6d-53e4f01591c0)

### Link to the related docs page

https://docs.expo.dev/guides/new-architecture/

**Comment by castdrian** [comment]
https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeios

**Comment by ceopaludetto** [comment]
> https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeios

Build properties plugin is only available when using expo prebuild. I'm talking about projects created by `bunx create-expo-app --template bare-minimum`

I've managed to enable by setting(in `Podfile.properties.json`): 
```json
"newArchEnabled": "true"
```

Instead of:
```json
"newArchEnabled": true
```

**Comment by brentvatne** [comment]
we include this information in the docs - we just delegate to the react native docs for how to enable it in the bare app context

<img width="917" alt="image" src="https://github.com/expo/expo/assets/90494/3d8365fa-2954-463a-ac37-7527c6251ba8">

that brings you to https://github.com/reactwg/react-native-new-architecture#guides

that said, the approach you used works well too!

**Comment by karlhorky** [comment]
> To check, I've used the following piece of code:
> 
> ```tsx
> useEffect(() => {
>   const uiManager = global?.nativeFabricUIManager ? 'Fabric' : 'Paper';
>   console.log(`Using ${uiManager}`);
> }, [])
> ```
> 
> I think the docs should include how to enable and also how to check if is enabled, since the expo cli supress the metro log (I think) ![image](https://private-user-images.githubusercontent.com/30508218/317795389-c36dfad2-05f6-48eb-9d6d-53e4f01591c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTI1ODUsIm5iZiI6MTcxODgxMjI4NSwicGF0aCI6Ii8zMDUwODIxOC8zMTc3OTUzODktYzM2ZGZhZDItMDVmNi00OGViLTlkNmQtNTNlNGYwMTU5MWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1NTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNWIxODk2ZWJkNzk0ZDU0YTllOTU4Zjk5NzNiMWFmODJjODQ5MzRmNjk3OWE4OWJjYjhlYzc5ZTAzZWM4ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Byoukxoe9aOS8MCLijU13q-NMp4SwG80TuHudNV1LQ0)

@brentvatne hi! 👋

What do you think about reopening this one to document how to check if the New Architecture is enabled in Expo managed apps?

@ProchaLu is having troubles with getting `global?.nativeFabricUIManager` to return truthy when following [Enable the New Architecture in an existing project](https://docs.expo.dev/guides/new-architecture/#enable-the-new-architecture-in-an-existing-project)

**Comment by karlhorky** [comment]
Oh, maybe a way to check / verify if the New Architecture is enabled is to run `expo run:ios` and check for the `(NOBRIDGE) LOG  Bridgeless mode is enabled` message...? 🤔

```bash
$ pnpm expo run:ios
...
› Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundled 1755ms node_modules/expo/AppEntry.js (614 modules)
 (NOBRIDGE) LOG  Bridgeless mode is enabled
```

Considering that [Bridgeless mode](https://github.com/reactwg/react-native-new-architecture/discussions/154) is a component of the New Architecture...
