### ISSUE TITLE
Error: Cannot find native module 'ExpoPushTokenManager', js engine: hermes

### ISSUE THREAD

**Issue by ukgrafix** [expo/expo#27937]
### Summary

After installing expo-notifications, this error pop up on the console
"expo react native"

Android Bundled 9601ms (C:\Users\admin\Downloads\app\appExpo\node_modules\expo\AppEntry.js)
 ERROR  Error: Cannot find native module 'ExpoPushTokenManager', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

The App works fine if expo-notifications imports and code is commented

Build: eas development build

Appreciate any help!

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"dependencies": {
    "@ant-design/react-native": "^5.0.5",
    "@emotion/react": "^11.11.3",
    "@emotion/styled": "^11.11.0",
    "@expo/metro-runtime": "~3.1.3",
    "@homielab/react-native-auto-scroll": "^0.0.10",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-community/netinfo": "^11.3.1",
    "@react-native-firebase/app": "^18.8.0",
    "@react-native-firebase/auth": "^18.8.0",
    "@react-native-firebase/database": "^18.8.0",
    "@react-native-firebase/firestore": "^18.8.0",
    "@react-native-firebase/storage": "^18.8.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.21",
    "antd": "^5.14.0",
    "expo": "~50.0.5",
    "expo-blur": "~12.9.1",
    "expo-checkbox": "^2.7.0",
    "expo-constants": "^15.4.5",
    "expo-dev-client": "~3.3.8",
    "expo-device": "~5.9.3",
    "expo-font": "~11.10.2",
    "expo-image-picker": "^14.7.1",
    "expo-notifications": "^0.27.6",
    "expo-splash-screen": "^0.26.4",
    "expo-status-bar": "~1.11.1",
    "firebase": "^10.8.0",
    "notix-rn": "^0.1.64",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "^0.73.4",
    "react-native-elements": "^3.4.3",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-gifted-charts": "^1.4.7",
    "react-native-google-mobile-ads": "^13.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-reanimated": "^3.6.2",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "^14.1.0",
    "react-native-web": "~0.19.6",
    "react-redux": "^9.1.0",
    "redux": "^5.0.1",
    "redux-thunk": "^3.1.0"
  },

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD  
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ~50.0.5 => 50.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: ^0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: bare

### Reproducible demo

App.js
`return (
    <AppContext.Provider value={{currentUser, setCurrentUser,}}>
      <NavigationContainer independent>
        <StackNav/>
      </NavigationContainer>
      <StatusBar style='dark'/>
      <PushNotifications/>
    </AppContext.Provider>
  );`

Push Notifications.js

`import { useState, useEffect, useRef } from 'react';
import { Text, View, Button, Platform } from 'react-native';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function PushNotifications() {
  const [expoPushToken, setExpoPushToken] = useState('');
  const [notification, setNotification] = useState(false);
  const notificationListener = useRef();
  const responseListener = useRef();

  useEffect(() => {
    registerForPushNotificationsAsync().then((token) => {
        console.log(token);
        setExpoPushToken(token)
    }).catch((err) => {
        console.log(err);
    });

    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });

    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      console.log(response);
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener.current);
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <Text>Your expo push token: {expoPushToken}</Text>
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
      <Button
        title="Press to schedule a notification"
        onPress={async () => {
          await schedulePushNotification();
        }}
      />
    </View>
  );
}

async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail! 📬",
      body: 'Here is the notification body',
      data: { data: 'goes here' },
    },
    trigger: { seconds: 2 },
  });
}

async function registerForPushNotificationsAsync() {
  let token;

  if (Platform.OS === 'android') {
    await Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  if (Device.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    // Learn more about projectId:
    // https://docs.expo.dev/push-notifications/push-notifications-setup/#configure-projectid
    token = (await Notifications.getExpoPushTokenAsync({ projectId: Constants.expoConfig.extra.eas.projectId })).data;
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  return token;
}
`

**Comment by vivipolli** [comment]
I'm having the same error

**Comment by JamesZhao2022** [comment]
I'm having the same error, is there any solution?

**Comment by raahimkhan** [comment]
I am having the same issue.

**Comment by vivipolli** [comment]
Uninstalling the app, cleaning the cache, solved to me

**Comment by vivipolli** [comment]
Uninstalling the app, and cleaning the cache, solved for me

**Comment by raahimkhan** [comment]
> Uninstalling the app, cleaning the cache, solved to me

Thanks! This worked for me too.

**Comment by Anzzy07** [comment]
> Uninstalling the app, cleaning the cache, solved to me
can you specify which app and how to clean cache?

**Comment by raahimkhan** [comment]
> > Uninstalling the app, cleaning the cache, solved to me
> > can you specify which app and how to clean cache?

The apk that is inside the emulator. Delete/uninstall that apk within the emulator and cache would automatically be deleted as well. Then rebuild the apk.

**Comment by Anzzy07** [comment]
> > > Uninstalling the app, cleaning the cache, solved to me
> > > can you specify which app and how to clean cache?
> 
> The apk that is inside the emulator. Delete/uninstall that apk within the emulator and cache would automatically be deleted as well. Then rebuild the apk.

Thank you brother.
