### ISSUE TITLE
【Web】Camera (Next) facing is not working

### ISSUE THREAD

**Issue by rabbitmouse** [expo/expo#27934]
### Minimal reproducible example

no example project，please see summary

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

Even if facing is set to back, the front camera is still used when opening the camera on the web.

```
<CameraView
    ref={cameraRef}
    facing="back"
    style={StyleSheet.absoluteFillObject}
    {
        ...Platform.select({
          native: {
            onBarcodeScanned: onBarcodeScanned,
            barcodeScannerSettings: {
              barcodeTypes: ["qr"],
              interval: 100, // not working actually
            }
          },
          web: {
            onBarCodeScanned: onBarcodeScanned,
            barCodeScannerSettings: {
              barCodeTypes: ["qr"],
              interval: 100,
            }
          }
      })
    }
/>
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/zhuzhiqin/.rvm/gems/ruby-2.7.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 50.0.7 => 50.0.7
    Expo Workflow: bare

### Expo Doctor Diagnostics

The package "expo-modules-core" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.

(node:42474) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  @expo/vector-icons@13.0.0 - expected version: ^14.0.0
  @sentry/react-native@5.20.0 - expected version: 5.19.1
  expo@50.0.7 - expected version: ~50.0.14
  expo-camera@14.0.6 - expected version: ~14.1.1
  expo-modules-core@1.11.9 - expected version: ~1.11.12
  react-native@0.73.3 - expected version: 0.73.6
  react-native-webview@13.8.1 - expected version: 13.6.4
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies

**Comment by CodySwannGT** [comment]
Having these exact same issue.

**Comment by fbatiga** [comment]
@rabbitmouse @CodySwannGT i was able to reproduce the issue. it's related to the props expected. The doc says `facing` but the real prop is actually  `type` (as in the current camera implementation)

**Comment by landabaso** [comment]
Yeah, I believe this issue should be reopened. The web implementation of the latest expo-camera still uses old props: `onBarCodeScanned` (note the uppercase "C"), `type`, and `barCodeScannerSettings` (where `interval` can be passed on Web - not on Android/iOS), etc. This is not documented.

Additionally, `getAvailableCameraTypesAsync` is no longer exposed (cannot be found in the docs). This function was useful for deciding whether to show the "flip camera" button or not, for example. While it can still be accessed using `/legacy`, it will be removed in the next version.

This is a great package, but unfortunately, the web part has a few issues. I'm leaving this message here in case someone else encounters the same problems.

**Comment by edulecca** [comment]
@landabaso appreciate it, save me hours of debugging

**Comment by viljark** [comment]
Please reopen, here is the minimal repro:
https://snack.expo.dev/@viljarremato/hot-green-french-fries

**Comment by gdaitis** [comment]
still having this issue too

**Comment by gdaitis** [comment]
I can't even get the workaround working, this is pretty frustrating
