### ISSUE TITLE
“npx expo export --platform web” command does not terminate automatically upon completion

### ISSUE THREAD

**Issue by lucaskraus** [expo/expo#27938]
### Minimal reproducible example

https://github.com/lucaskraus/expo-exportweb-issue

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

Hey, everyone! Hope everything is good.

After that I upgrade my SDK version to 50 from 49, the command "npx expo export --platform web" not finish automatically. The output "App exported to: dist" is showed but the terminal waits for a hard kill (CTRL + C in Linux case) to exit the process.

If I hard kill the process and run "npx serve dist" all my changes looks properly exported so I guess the export is working but the only problem is the command is not finishing auto. 

I also tried to run the command "EXPO_DEBUG=true npx expo export --platform web" and no errors is show. All looks normal.

Can you help me to solve this?
![Screenshot 2024-03-29 103325](https://github.com/expo/expo/assets/72233741/66748e97-d3ab-45ea-9326-14aaf0b8dc61)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.10 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
      npm: 10.2.5 - ~/.nvm/versions/node/v21.5.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1 
      expo: ^50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: managed

### Expo Doctor Diagnostics

npx expo-doctor@latest
(node:20419) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by byCedric** [comment]
Hi @lucaskraus! Is it reliably doing this? If so, can you try running `EXPO_NO_TELEMETRY=true npx expo export --platform web` and see if that helps?

**Comment by lucaskraus** [comment]
Hi @byCedric! Yes! I mean, since that I update to SDK 50 this is the only breaking change that I'm facing. All except this is working fine. Like I said, if I execute "CTRL + C" after the message "App exported to: dist" and run "npx serve dist" all works fine in the exported version.

Btw, your suggested command seems result the same problem. The command still not letting the terminal available again after conclusion:

![image](https://github.com/expo/expo/assets/72233741/377da349-b6dd-40a2-95bd-857fd288ccb2)

**Comment by lsw-1** [comment]
I'm experiencing the same issue

**Comment by byCedric** [comment]
Since this isn't reliably reproducible on our end, it only happens in rare cases, I flagged the whole CLI team to watch out for this. We'll investigate more when it happens on our end.

@lucaskraus, the original repro isn't usable for us, unfortunately. It seems to be part of your original app, without all the components. Meaning we can't run or export the app.

If others are experiencing this issue, the best thing to do is provide another repro where you can reliably reproduce this.

You could help track this issue down as well. If this happens, you can follow these steps:
- Force-close the CLI process
- `$ node --inspect-brk ./node_modules/.bin/expo export ...` (add your flags)
- Open the Node inspector through Chrome (or other supported browsers -- [docs](https://nodejs.org/en/learn/getting-started/debugging))
- Once it gets to the state where it's not exiting as expected, find the open handles and try to trace their origins:
  - In debug console, run: `process._getActiveHandles()`.
  - Trace these processes/streams to their origins.
  - Report findings in this thread.

Hope we can find the root cause asap!

**Comment by mwilliams1188** [comment]
Getting this as well for what it's worth. Using Turborepo, SDK 50, pnpm

**Comment by murphycj** [comment]
I also get this issue. For me, I only got it after I added Sentry as a dependency, but the issue goes away if I remove `"output": "static",` from the `web` settings in `app.json`... but doing so seems to cause other issues so I'd rather avoid doing that.

Here is a test repo that I used to reproduce it (with sentry dsn, names, etc remove): https://github.com/murphycj/test-expo-app

**Comment by KDederichs** [comment]
Getting the same error locally (Mac book) and worse on a linux server (Ubuntu 20) while trying to deploy the app via script.
No Sentry in our case though so I doubt that's related.
It also NEVER seems to terminate, ever (20 minutes or something and still hanging)

**Comment by skmcloughlin** [comment]
I just started having this issue. I'm still early in the process so there is little more than default boilerplate in my project and it worked without issue last week. I did try a suggestion from another issue and got the same logs as [this user](https://github.com/expo/eas-cli/issues/1907#issuecomment-1625991974). Interestingly the export process does not hang if I set the expo.web.output to single in app.config.js.

**Comment by jongbelegen** [comment]
I have the same issue after installing Sentry. `"@sentry/react-native": "5.19.1"`

When i run `process._getActiveHandles()`

The result is 1 readstream and 2 write streams (fd: 0, fd: 1, fd: 2).

After investigating the heap snapshot i came across this:

![image](https://github.com/expo/expo/assets/11552802/4e7db051-0695-458c-9f29-ceac68517fd8)

Removing the routingInstrumentation fixed the issue for me:
```
+++ b/src/utils/sentry.ts
@@ -1,17 +1,8 @@
 import * as Sentry from "@sentry/react-native";

-export const routingInstrumentation =
-  new Sentry.ReactNavigationInstrumentation();
-
 Sentry.init({
   dsn: "__REDACTED__",
   enabled: !__DEV__,
-  integrations: [
-    new Sentry.ReactNativeTracing({
-      routingInstrumentation,
-      shouldCreateSpanForRequest: (url) => !__DEV__ || !url.endsWith(`/logs`),
-    }),
-  ],

   normalizeDepth: 8,
 });
 ```

**Comment by byCedric** [comment]
@jongbelegen Dankjewel! That's extremely helpful. For now, we'll add a workaround that will close the process better. I'll also start talking with Sentry about this, preferably libraries should not block the process when statically rendering.

**Comment by krystofwoldrich** [comment]
@jongbelegen @byCedric We have also noticed this. The [fix](https://github.com/getsentry/sentry-react-native/pull/3730) was released in https://github.com/getsentry/sentry-react-native/releases/tag/5.21.0. Since this version Sentry doesn't run during the static route generation.

Make sure you are using the `getSentryExpoConfig` function for the fix to work correctly.
```js
// const { getDefaultConfig } = require("expo/metro-config");
const {getSentryExpoConfig} = require('@sentry/react-native/metro');
```

**Comment by SleeplessByte** [comment]
I do think there may be an issue remaining. Whilst the sentry fix made my Windows builds work again, they do (still) hand on Gitlab CI. I also tested that with the telemetry turned off. 

When I get the chance I'll try to ssh into it, but so far I haven't found a real fix.

**Comment by krystofwoldrich** [comment]
@SleeplessByte What version of the Expo CLI are you using? Besides the Sentry fix this was also fixed in Expo CLI 0.18.11 and newer.

**Comment by SleeplessByte** [comment]
Would it be using the local expo package for that? That's at 50.0.19. on the ci it uses the latest eas-cli, and no expo-cli is globally installed.

**Comment by SleeplessByte** [comment]
Yep. 

```yarn
"expo@npm:~50.0.19":
  version: 50.0.19
  resolution: "expo@npm:50.0.19"
  dependencies:
    "@babel/runtime": "npm:^7.20.0"
    "@expo/cli": "npm:0.17.12"
    [...]
```

`expo@npm:~50.0.19` is stuck on `@expo/cli": "npm:0.17.12"`
