### ISSUE TITLE
Hermes Error: "couldn't find DSO to load: libjscexecutor.so" in New Expo Project (Bare Workflow)

### ISSUE THREAD

**Issue by annouri** [expo/expo#27941]
### Minimal reproducible example

https://github.com/annouri/expo-hermes-bug.git

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

Expected Behavior:

The app should build and run successfully using Hermes for JavaScript execution.

Actual Behavior:

The app launch, and the logcat shows the "couldn't find DSO to load: libjscexecutor.so" error.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /usr/local/bin/node
      npm: 10.2.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 3.16.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
hi there! that's known from react-native. the default resolver will [try jsc first than hermes](https://github.com/facebook/react-native/blob/2477fbc6005c4cbdc0ca3460413ce52e2e1e8bb5/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java#L364-L397). however, since hermes is default engine now. maybe we could do better. would create a pr for that and would be available from sdk 51.

**Comment by annouri** [comment]
> hi there! that's known from react-native. the default resolver will [try jsc first than hermes](https://github.com/facebook/react-native/blob/2477fbc6005c4cbdc0ca3460413ce52e2e1e8bb5/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java#L364-L397). however, since hermes is default engine now. maybe we could do better. would create a pr for that and would be available from sdk 51.

Hi @Kudo ,
Thank you for the update. I understand that Expo SDK 51 and later will fix this issue, which is great news!
In the meantime, is there a way to explicitly choose Hermes for JavaScript execution in current Expo versions (SDK 50) to avoid the issue.  If so, could you please share any instructions on how to achieve this?

Thanks again for your help in resolving this issue.

**Comment by Kudo** [comment]
thanks for further asking the question. i noticed that the issue was actually resolve on latest main already. i'm going to accept the issue and would have a fix to sdk 50.

**Comment by annouri** [comment]
Thank you for addressing the issue! How can I update my project to include the fix? Currently using Expo SDK 50.0.14.

**Comment by Kudo** [comment]
@annouri thanks for mentioning the issue and gave me a chance to revisit our implementation. we've published expo@50.0.15 and that should include the fix.
