### ISSUE TITLE
[expo-modules] error.code is lost or overwritten in most cases

### ISSUE THREAD

**Issue by cltnschlosser** [expo/expo#27959]
### Minimal reproducible example

https://github.com/expo/expo/pull/27960 (`apps/test-suite/` test showing the failure)

### What platform(s) does this occur on?

- iOS
- Android? (Haven't tested there yet - or looked at the code)

### Did you reproduce this issue in a development build?

Yes

### Summary

NativeModules support returning a code, description, and additional error payload object. This issue focuses just on the `code`. In certain cases (most cases) when an exception is thrown from an expo module the code is overwritten (either lost or replaced with `ERR_FUNCTION_CALL`).

To test this I've created a very simple expo module:
```swift
private let codedException = Exception(name: "TestException",
                                       description: "This is a test Exception with a code",
                                       code: "E_TEST_CODE")

public class ExpoModulesExceptionTestModule: Module {
    public func definition() -> ModuleDefinition {
        Name("ExpoModulesExceptionTest")

        Function("codedException") {
            throw codedException
        }

        AsyncFunction("codedExceptionRejectAsync") { (promise: Promise) in
            promise.reject(codedException)
        }

        AsyncFunction("codedExceptionThrowAsync") { () in
            throw codedException
        }

        AsyncFunction("codedExceptionConcurrentAsync") { () async throws in
            throw codedException
        }
    }
}
```
Then the tests look like this (one example):
```js
t.it('synchronous function', () => {
  try {
    ExpoModulesExceptionTest.codedException();
    t.expect(true).toBe(false);
  } catch (error) {
    t.expect(error.code).toBe('E_TEST_CODE');
  }
});
```

And we get the following result:
<img width="396" alt="image" src="https://github.com/expo/expo/assets/1498529/b073268d-8b40-4d7b-952b-90b4c7dc94a4">

#### Other platforms
At this time I haven't tested Android to confirm if it's happening there too.

### Solutions

I see a couple different paths forward:
1. Overwrite the code for `FunctionCallException` (this is a potentially breaking change if anyone is relying on the current functionality). This also may be an incomplete fix, because `FunctionCallException` will overwrite the description (the original description should be in the cause though).
2. Create a new `CustomException` (or `CustomCodedException`, `UnwrappedException`, `RawException`, `JSException`, etc.). Something to signify that it won't be wrapped. Then we update the expo modules code to be return the exception directly instead of wrapping it:
```swift
// start: New code
} catch let customError as CustomException {
  promise.reject(customError)
// end: New code
} catch let error as Exception {
  promise.reject(FunctionCallException(name).causedBy(error))
  return
} catch {
  promise.reject(UnexpectedException(error))
  return
}
```

### Environment

`expo-env-info: command not found`

### Expo Doctor Diagnostics

<details>
  <summary>expo-doctor output</summary>
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check for common project setup issues
✖ Check Expo config (app.json/ app.config.js) schema
Unexpected error while running 'Check Expo config (app.json/ app.config.js) schema' check:
TypeError: Cannot read properties of undefined (reading 'schema')
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@1.18.2 - expected version: 1.21.0
  @react-native-community/datetimepicker@7.6.3 - expected version: 7.6.1
  react-native@0.74.0-rc.5 - expected version: 0.74.0-rc.4
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```
</details>

### Contribution Help Needed

I'm willing to contribution this solution, if there is agreement on an api. Also I'd like to include the test module, but I need some pointers on what I've done that might not fit existing patterns (ex: local path import).

**Comment by tsapeta** [comment]
Hey! Sorry for not responding, there are so many things happening right now so it's hard to take it all in.

I agree that returning the `ERR_FUNCTION_CALL` code is quite unfortunate. In general, an API for exceptions/errors is not complete yet. We had some ideas like mapping the chain of native exceptions to a chain of JS errors, using [Error `cause` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause), but this doesn't play nicely with the idea of exposing the error code (not a JS standard) as you would always get the code of the outermost exception and the message concatenated from all chained exceptions, as it is right now.

We'll be exploring this area more in SDK 52 to find out what would be the best solution for both: native module authors and app developers.

Until then I would propose something else as a temporary solution. Here is the line that passes error's code and message to the promise rejecter from RN: https://github.com/expo/expo/blob/cdfd9c1a0b8d8860b542edea45cb452f3eea5269/packages/expo-modules-core/ios/Core/Functions/AsyncFunctionDefinition.swift#L128
What if instead of `error.code` we return a code of the outermost error that is not a `FunctionCallException`? Something like
```swift
if let error = error as? FunctionCallException, let cause = error.cause {
  return cause.code
} else {
  return error.code
}
```

This could work for async functions. For sync functions I'll need to think a bit more as right now we don't even pass the code to JS because we can only throw a simple `JSError` from JSI which is an abstraction, i.e. it's not a JS object on which we could set `code` property before going back to JS.

**Comment by cltnschlosser** [comment]
Thanks for the thorough response! I’ll take a look at this angle. For my needs I’m also going to need to be able to set that NSError that is hardcoded to nil in that snippet. But I think this approach works nicely with putting a `userInfo: NSError?` in Exception or a separate protocol.
Also I hadn’t realized synchronous errors were different, I haven’t used synchronous stuff yet because I’m still using non-JSI modules.

**Comment by cltnschlosser** [comment]
Take a look at this, made some good progress here:
https://github.com/expo/expo/pull/27960/commits/c479d70ce3ed8b9e7e13e1c278f8b1beaa62e06b
<img width="389" alt="image" src="https://github.com/expo/expo/assets/1498529/4b90f72c-52d1-4942-bc1c-74a6cb007a6b">

**Comment by tsapeta** [comment]
Nice @cltnschlosser! Do you plan to open a PR with this?

**Comment by cltnschlosser** [comment]
@tsapeta should I make a PR with just the expo-modules-core changes, or can you give me pointers on what I need to do to make the test module ready to be merged as well?

**Comment by cltnschlosser** [comment]
Test module + error.code changes are https://github.com/expo/expo/pull/27960
