### ISSUE TITLE
[Expo AV]: Video can not scale because of borderRadius style property

### ISSUE THREAD

**Issue by Glazzes** [expo/expo#27954]
### Minimal reproducible example

https://snack.expo.dev/@glazzes/video-scale-android-7-issue

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

In Android 7 applying `borderRadius` style property to a `Video` component will prevent this one from being scaled properly.

 I tested this with Android 6 and Android 11 and at least for me, this issue is not present on those versions.

 | with `borderRadius`   | without `borderRadius`   |
 |--------------------------------|------------------------------------ |
 | <video src="https://github.com/expo/expo/assets/52082794/24f6b151-e88f-495c-99c8-9df2f763d181" width="100%" controls />  |   <video src="https://github.com/expo/expo/assets/52082794/a143b54c-e5af-414d-9199-464edfa4d11f" width="100%" controls />   |

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Fedora Linux 37 (KDE Plasma)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 18.18.2 - /usr/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.3.0 - /usr/local/bin/npm
      Watchman: 20221218.010722.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-33 | Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 5.9.3
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by brentvatne** [comment]
hi there! can you try this out with `expo-video`? this is our upcoming replacement for `expo-av`. you can try it out by running:

```
# initialize app from the canary release
npx create-expo-app -t blank@canary
# add expo-video package
npx expo install expo-video
```

see the docs for info on expo-video: https://docs.expo.dev/versions/unversioned/sdk/video/
we intend to recommend folks migrate to expo-video in upcoming sdk cycles, and do not plan to improve expo-av in the meantime.

**Comment by Glazzes** [comment]
Thank you for your reply, the error is still present in this new library, however assigning `borderRadius` does not round the corners of the view, so I decided to wrap it a `View` with both `borderRadius` and `overflow` property set to hidden, and it will produce the same error as it did in the expo-av.

As you will see controls are not scaled properly either, as they seem to scale properly in the x axis, but not at all in the y axis.

https://github.com/expo/expo/assets/52082794/153f7e53-3b30-4a50-b9c2-ec9249eb6185

**Comment by Glazzes** [comment]
After a lot of testing with other applications, I have found this problem is actually a bug on the Android version itself, applying transformations to an element using `borderRadius` property will cause strange displaying issues.

As not being an issue related to Expo AV I'll better close it.
