### ISSUE TITLE
[docs] Question about arrays in  shared routes

### ISSUE THREAD

**Issue by francosion042** [expo/expo#27957]
### Summary

Can someone please explain this 
<img width="910" alt="Screenshot 2024-03-31 at 4 25 07 PM" src="https://github.com/expo/expo/assets/45284758/560e3dc8-7889-47b3-bbb3-0b98baf48a1b">

I've searched everywhere and even asked questions on discord, it's been over a year of expo-router and yet there's no clear documentation on the shared route. 

### Link to the related docs page

https://docs.expo.dev/router/advanced/shared-routes/#arrays

**Comment by amandeepmittal** [comment]
Hey @francosion042, can you please elaborate on your question? I'm not sure I understand by looking at the reference doc link you shared.

**Comment by francosion042** [comment]
@amandeepmittal i wanna know what the file structure should look like, i created a group folder and put the shared file in it, but when i navigate to it from any tab, it moves away from that tab.
