### ISSUE TITLE
Bug with splash, it doesn't appear in the build

### ISSUE THREAD

**Issue by t-heu** [expo/expo#27961]
### Minimal reproducible example

https://github.com/t-heu/hangman-app

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Guys, In Expo Go development mode, the splash screen works normally, after running the app build in .apk the splash screen does not appear.

What I've tried so far.
I tried clearing cache.
I tried using Expo's own splash.
I tried to create my own splash.
I tried updating the libs.
I tried to create a new project just to generate Build.

In every attempt I had the same problem, no error was generated and the splash did not appear.

EX:

https://github.com/expo/expo/assets/25287877/5ffb3409-7602-4b53-a230-fc15133442ea

Code:
app.json
``
{
  "expo": {
    "name": "Hangman",
    "slug": "Hangman",
    "version": "1.0.7",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splashscreen.png",
      "resizeMode": "contain",
      "backgroundColor": "#262632"
    },
    "androidStatusBar": {
      "backgroundColor": "#262632",
      "translucent": false
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.matheud.Hangman"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#262632"
      },
      "package": "com.matheud.Hangman"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-font",
        {
          "fonts": [
            "./assets/fonts/yanone/YanoneKaffeesatz-Bold.ttf",
            "./assets/fonts/sourceCodePro/SourceCodePro-SemiBold.ttf"
          ]
        }
      ],
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ],
    "extra": {
      "eas": {
        "projectId": ""
      }
    }
  }
}``

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 21.6.0 - ~/.nvm/versions/node/v21.6.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v21.6.0/bin/yarn
      npm: 10.3.0 - ~/.nvm/versions/node/v21.6.0/bin/npm
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check native tooling versions
✔ Check npm/ yarn versions
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.

One or more checks failed, indicating possible issues with the project.

**Comment by Kudo** [comment]
hi there! could you share how to run your repro? running into the `Unable to resolve "../../env" from "src/api/firebase.ts"` error when `npx expo run:android`.

**Comment by t-heu** [comment]
> hi there! could you share how to run your repro? running into the `Unable to resolve "../../env" from "src/api/firebase.ts"` error when `npx expo run:android`.

I put the .env sensitive variables in firebase.ts and comment the import .env. A temporary solution.

**Comment by Kudo** [comment]
commenting out the firebase initialization and splash screen shown in my case. i tried both `npx expo run:android` and `npx expo run:android --variant release`. how did you build and run your project?

fyi my src/api/firebase.ts 
```tsx
import * as firebase from 'firebase/app';
import { getDatabase, ref, set, onValue, update, get, child, onDisconnect, remove } from "firebase/database";

// import config from "../../env"
// const {API_KEY, AUTH_DOMAIN, DATABASE_URL, PROJECT_ID, STORAGE_BUCKET, MESSAGING_SENDER_ID} = config

// const firebaseConfig = {
//   apiKey: API_KEY,
//   authDomain: AUTH_DOMAIN,
//   databaseURL: DATABASE_URL,
//   projectId: PROJECT_ID,
//   storageBucket: STORAGE_BUCKET,
//   messagingSenderId: MESSAGING_SENDER_ID
// };
//
// const app = firebase.initializeApp(firebaseConfig);
// const database = getDatabase(app);

const database = null;

export { firebase, database, ref, set, onValue, update, get, child, onDisconnect, remove };
```
