### ISSUE TITLE
[expo-camera/next]: iOS prompts for microphone access without requesting it

### ISSUE THREAD

**Issue by WilliamABradley** [expo/expo#27984]
### Minimal reproducible example

https://github.com/WilliamABradley/expo-camera-next-bug-ios-mic

### What platform(s) does this occur on?

iOS - (iPhone 11 on iOS 17.3.1)

### Did you reproduce this issue in a development build?

Yes

### Summary

During the port of our app to Expo 50, we encountered several snags:

- The app would crash if we tried to use the non `/next` version of the module with barcode scanning configured, forcing us to update to `expo-camera/next`
- The app would crash expo go in the simulator when using the `expo-camera/next` `CameraView`, so we had to add an isDevice guard.
- iOS now requires `barcodeTypes: ["qr"]` in `barcodeScannerSettings`
- The cause for this issue: `microphone` access is requested on iOS without using [useMicrophonePermissions](https://docs.expo.dev/versions/latest/sdk/camera-next/#usemicrophonepermissionsoptions)

Since we are building a QR Code scanner here, this is an issue, and it also would mean getting held up at App Store review, as it is an unnecessary permission.

If you block microphone access, the app crashes with:
```
[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration
```

![image](https://github.com/expo/expo/assets/6026537/10df6b83-57f5-4156-8bd9-8e97c4588427)

## Solution

We managed to find a solution to the issue, which was to set `mute={true}` on the `CameraView`, this should be inferred by default as the view is using the default `picture` mode, and pictures, they uh, don't have sound 😅 

This solution was inferred from this code block, which I think might be the culprit: https://github.com/expo/expo/blob/9a7c4af456e7d66b4460a1bdf5bd258e60f8a028/packages/expo-camera/ios/Next/CameraViewNext.swift#L592-L622

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.local/share/powershell/Modules/nvm/2.5.1/vs/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.local/share/powershell/Modules/nvm/2.5.1/vs/v20.11.1/bin/yarn
      npm: 10.5.0 - ~/.local/share/powershell/Modules/nvm/2.5.1/vs/v20.11.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by alanjhughes** [comment]
Hi @WilliamABradley 
> this should be inferred by default as the view is using the default picture mode, and pictures, they uh, don't have sound 😅

This can't be inferred and has to be called, you can freely switch between video and picture modes so clean up has to happen when the switch occurs because it's the same device instance just with different inputs added or removed. Picture mode means nothing to the capture device, we just use it for ease of use in the JS api but it exists only there. The native object only sees inputs and output. The issue should be resolved here #27988

**Comment by MuhammadMuzammilQadri** [comment]
Okay but then this should atleast be mentioned in the documentation that not setting `mute` property to `true` will result in a crash if `NSMicrophoneUsageDescription` key is not provided in the `Info.plist`

**Comment by stefan-schweiger** [comment]
@alanjhughes I think the handling is not 100% correct now since as already mentioned you aren't able to use a muted video stream without `NSMicrophoneUsageDescription`. Which for example crashes existing apps like Expo Go...

**Comment by alanjhughes** [comment]
@stefan-schweiger I'm not sure I understand. Expo go always has `NSMicrophoneUsageDescription` added. There is nothing a user can do to remove that.

I just created a sample app to test all of this. I am not experiencing any crashes and I can record muted video just fine. If the user doesn't grant you microphone permission then you do the same as you would with any permission and use it to determine what to pass to the mute value. If they have denied the permission, then as long as `mute` is set to true, there will be no crash. The internal default of video is unmuted because that is what most people would expect. If the default was muted, then there you would have issues about having to explicitly pass `mute={false}` being a bad default.

If you are using a dev client and want to remove the `NSMicrophoneUsageDescription` that is fine, you can always pass `mute={true}` to the camera component because you know ahead of time you will never provide unmuted video.

**Comment by alanjhughes** [comment]
@stefan-schweiger If I don't pass anything for the mute value and the user has denied microphone permissions then there will be a crash but that is the same as any time you use something without being granted the permissions to do so.

**Comment by alanjhughes** [comment]
> Okay but then this should atleast be mentioned in the documentation that not setting `mute` property to `true` will result in a crash if `NSMicrophoneUsageDescription` key is not provided in the `Info.plist`

This is correct. We should document this.

**Comment by stefan-schweiger** [comment]
@alanjhughes I have the following situation I'm using an application build with `expo-camera@14.1.1` with this I didn't have to set `mute` or anything and I didn't have to specify `NSMicrophoneUsageDescription`. I have updated `expo-camera` to 14.1.12 and pushed an `expo-update`. Suddenly the camera needs the microphone permission which the iOS app doesn't have. On Android there is no change to the behavior and everything works as usual.

**Comment by alanjhughes** [comment]
@stefan-schweiger  We had a report of the same issue with `expo-camera@14.1.1` and it was resolved in `expo-camera@14.1.2` 🤔 In that instance we had been exporting the incorrect permission functions in `14.1.1`. Do you remove `NSMicrophoneUsageDescription` yourself? I've opened this that should fix these problems https://github.com/expo/expo/pull/28156

**Comment by alanjhughes** [comment]
@stefan-schweiger there was native changes in the bump from `14.1.1` to `14.1.2`, don't think it's safe to update it over the air

**Comment by BoavistaLudwig** [comment]
v 14.0.6 still works 🥳

**Comment by BoavistaLudwig** [comment]
With this timeout its working for me. I read about it at [https://github.com/expo/expo/issues/27528](https://github.com/expo/expo/issues/url)
Without setting mute, and without the timeout, my app crashes.

    useEffect(() => {
      if (currentAction === "video") {
        setTimeout(() => {
          setMute(false);
        }, 250);
      } else {
        setMute(true);
      }
    }, [currentAction]);

    return (
      <CameraView
        ref={cameraRef}
        style={styles.camera}
        facing={facing}
        flash={flash}
        mode={currentAction === "video" ? "video" : "picture"}
        mute={mute}
        enableTorch={torchMode}
      />
    ); ``
