### ISSUE TITLE
Dynamic route works on `npm start` but not in web builds

### ISSUE THREAD

**Issue by Ethan925** [expo/expo#27995]
### Minimal reproducible example

https://github.com/bruthurs-inc/dynamicroutebug/tree/master

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I created a new app with the **Navigation (TypeScript)** template.

In my `app` folder of routes, I added a folder `foo` with a dynamic route `[bar].tsx` within it.

When I run the app locally via `npm start` and access it from the web, I can access `http://localhost:8081/foo/myslug`

However, on deployed instances (and locally when I run `npm run build && npx serve dist` instead of `npm start`) the page 404s. `npm run build` runs `expo export -p web`

<img width="1668" alt="image" src="https://github.com/expo/expo/assets/7635143/a1160dc7-5cd4-4e5a-95d6-820be93d5e9d">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 31
        Build Tools: 30.0.2, 31.0.0, 32.0.0
        System Images: android-24 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

**Comment by marklawlor** [comment]
In your `app.json` your `web.output` is set to `static`. This means your website is rendered and served as static `.html` files. If the file doesn't exist, then you will get a 404.

To use dynamic routes with static rendering, you need to tell the bundler what the possible values of `[bar]` could be. This way it will generate the necessary `.html` files. https://docs.expo.dev/router/reference/static-rendering/#dynamic-routes

The alternative to static rendering is running your app as a Single Page Application. You can enable this by simply removing `output: 'static'` from your `app.json`. Now only a `index.html` file will be generated. You'll need to run your application via `npx serve -s dist` (`-s` enables single page mode) and ensure you setup the correct redirect rules in your deployment.

**Comment by Ethan925** [comment]
Thank you! The second option (removing `output: 'static'` and changing to `npx serve dist -s`) did the trick for our use case. 

(Pre-defining the dynamic routes wouldn't work for us because the dynamic route will be for `[user].tsx` pages, and new users can be created after the build)
