### ISSUE TITLE
Dynamic route params are not preserved during tab navigation

### ISSUE THREAD

**Issue by vonkanehoffen** [expo/expo#27992]
### Minimal reproducible example

https://github.com/vonkanehoffen/expo-dynamic-route-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When navigating to a tab nested inside a dynamic route, only the initial tab receives the route param. Clicking on another tab in the same navigator does not preserve the param for that view. 

i.e. in the attached minimal repro, if I use the `<Link>`s to navigate to either:
```
/(tabs)/things/12345/
/(tabs)/things/12345/status
```
I can get `12345` via `useLocalSearchParams` in either route. However if I navigate to `status` via pressing the tab in the navigator defined at `app/(tabs)/things/[thingId]/_layout.tsx`, following navigation via `<Link>`to `/(tabs)/things/12345/` , no params are passed.

This is also an issue with `MaterialTopTabs` . 

Wondering if this relates to https://github.com/expo/expo/issues/27472 or https://github.com/expo/expo/pull/27486 maybe?

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0, 34.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: managed

**Comment by vonkanehoffen** [comment]
Also worth noting I figured out a rather hacky workaround here: https://github.com/vonkanehoffen/expo-dynamic-route-bug/compare/master...hacky-fix ...however it's far from ideal 😅 

```
listeners={{
  tabPress: (e) => {
    e.preventDefault();
    router.push(`/(tabs)/things/${thingId}/status`);
  },
}}
```

**Comment by marklawlor** [comment]
This is indeed the same issue as the linked issues. Unfortunately React Navigation's tabs component wasn't built for this use case, and trying to retrofit it resulted in to many cascading renders. Your fix should work fine, alternatively you could built your own custom navigator.

I'm going to close this issue as a duplicate, but I'll crosspost your workaround.
