### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by alukos** [expo/expo#28]
Now for pinch gesture show the exponent menu. I want use pinch to zoom on my app. Is this possible? Maybe you could use a 3 finger pinch instead.

**Comment by terribleben** [comment]
Thanks for the feedback, we agree. We'll be changing to a different gesture in the upcoming SDK release later this month.

**Comment by terribleben** [comment]
Hello, this won't be an issue any more because we changed the way the menu works. Read more [here](https://blog.expo.io/new-developer-menu-in-expo-for-ios-80d6ba8217f5).
