### ISSUE TITLE
Enable `--clear-credentials` for Android

### ISSUE THREAD

**Issue by davidbonnet** [expo/expo#280]
Unless I'm missing something, since Android credentials can be downloaded, `--clear-credentials` for `exp build:android` could be enabled again [here](https://github.com/expo/exp/blob/master/src/commands/build.js#L29).

**Comment by dikaiosune** [comment]
Yep! We still want to put a small warning there to force users to have downloaded them, as it can be a bit catastrophic if you clear them without downloading them.

**Comment by terribleben** [comment]
Looks like this was fixed/merged - closing
