### ISSUE TITLE
expo-blur doesn't calculate transform rotation correctly on Android

### ISSUE THREAD

**Issue by ravanscafi** [expo/expo#28001]
### Minimal reproducible example

https://snack.expo.dev/@ravanscafi/7e2bbc?platform=android

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When using the [BlurView](https://docs.expo.dev/versions/latest/sdk/blur-view/) in Android, if the View is rotated, the background should stay the same.
However, it is being rotated as well.

Minimal code:
```tsx
<BlurView
  intensity={5}
  experimentalBlurMethod="dimezisBlurView"
  style={{ transform: [{ rotate: '90deg' }] }}
/>
```

## iOS (and Web as well):
![iosblur](https://github.com/expo/expo/assets/6104262/54562588-a6f5-441f-991f-d7ecc3919518)

## Android:
![androidblur](https://github.com/expo/expo/assets/6104262/c9d5de79-4723-4d6d-8c0e-46a9e53bbede)

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.03.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.10 => 0.19.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment]
hey there! blurview on android is in an experimental state, and you may encounter issues like this. there is no reliable blur view implementation on the android platform for us to build on top of, unfortunately. if you'd like to submit a pr to help with this, we could review! but it's not high priority for us to work on this because blurview on android is generally not very good
