### ISSUE TITLE
Not able to login to EXPO Go on iphone 13

### ISSUE THREAD

**Issue by jtvanni** [expo/expo#28024]
### Summary

I am not being able to login to expo go on iphone 13. Not able to login on 3 different ways

- safari browser
- chrome browser
- expo go app directly

Tried either with wifi and phone 5G connection. Both not working.

Credentials are fine and working on web access via computer.

![expo-bug](https://github.com/expo/expo/assets/135655390/de9c4f3f-e0a7-4ca5-9246-deafdceef3b3)

### What platform(s) does this occur on?

iOS

### Environment

not related to development but the EXPO app itself.

### Minimal reproducible example

not related to development but the EXPO app itself.

**Comment by brentvatne** [comment]
hi there! perhaps your phone has a vpn or proxy set up? if you're unable to sign in from that particular device, but you can from other devices, i suspect there is something wrong with your device/the network configuration and there isn't much we can do to help with that

**Comment by scottanglr** [comment]
I also encountered this issue when running Safari on my iPhone. It's running iOS 15.8.2. I checked cookie restrictions and I have no VPN. I also had an infinite spinner when going to the register device page to download the provisioning profile. I was also unable to interact with much of the page, such as the expandable footer nav items.

I used the simulator iOS 17.0.1 and I was able to login and also see the provisioning profile.

My guess is that it's a JS issue for older Safari browsers. I had a persistent JS error on each page.

```
[Error] SyntaxError: Unexpected token '{'
	(anonymous function) (_app-9085fa68ef75ef0a.js:2)
```

**Comment by jtvanni** [comment]
I have no VPN or Proxy setup... phone is up to date and clean of any kind of network related software...

The error generated is so generic I cant even manage to try and solve it without internal help from expo support.

**Comment by hoanganh1506** [comment]
I hope the expo team will fix it as soon as possible. I use IoS 14.4.2 and have the same error.

**Comment by jacoblsdev** [comment]
hi, this issue is still not solved. happening to me in all iphones. tried in 3.

**Comment by thanhtrung07** [comment]
Hi, this issue is still not fixed. I'm using IoS 15.8.5, not able to log in using safari, expo go app, chrome and firefox

**Comment by laszlotar** [comment]
Why is this issue closed? It is still not fixed. I'm using iOS 15.8.5, not able to log in using the Expo Go app. (Client version 1017756)

**Comment by justinfink** [comment]
Are there any workarounds here? Struggling with the same issue on an iPhone 13, with iOS 15.8.6
