### ISSUE TITLE
Bug in start app with Expo Go

### ISSUE THREAD

**Issue by vicdeveloperr** [expo/expo#28048]
### Minimal reproducible example

https://github.com/vicdeveloperr/ExpoBugReport

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I recently update the Expo version of my project. And, then the bug appear.

I can start my app from Expo Go perfectly, before the update. 

After update, when I start my app in Expo Go, my code compile perfectly with none error log in my console. But, in Expo Go I get the next warning:
![expo-bug](https://github.com/expo/expo/assets/105018884/8e8bbc74-020f-4431-a44a-64d143714e10)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.2 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 20.11.1 - ~/nvm/current/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 10.2.4 - ~/nvm/current/bin/npm

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
hi there! please remove any extraneous packages from your package.json in the repro. it should include only the minimum required code to reproduce the problem

**Comment by vicdeveloperr** [comment]
> hi there! please remove any extraneous packages from your package.json in the repro. it should include only the minimum required code to reproduce the problem

Hi, bro! Thanks for respond. 

I do that recently. Please, check again.

**Comment by vicdeveloperr** [comment]
I recently edit my repo to create the minimun reproducible example. Can reopen the issue now? I continue haved this error.

Thanks for any help!
