### ISSUE TITLE
EAS build failed: Unresolved reference: UPSIDE_DOWN_CAKE

### ISSUE THREAD

**Issue by Aidasvenc** [expo/expo#28047]
### Minimal reproducible example

> Task :expo-location:compileReleaseKotlin e: file:///home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.kt:734:63 Unresolved reference: UPSIDE_DOWN_CAKE e: file:///home/expo/workingdir/build/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.kt:735:95 Unresolved reference: FOREGROUND_SERVICE_LOCATION > Task :expo-location:compileReleaseKotlin FAILED

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I am having a build error solely on Android after updating expo SDK 49 -> 50. The build error happens for expo-location task. The build on iOS succeeds and is working as expected.

`package.json`:

[package.json](https://github.com/expo/expo/files/14876426/package.json)

Full output of run gradlew:

[run_gradlew.txt](https://github.com/expo/expo/files/14876383/run_gradlew.txt)

### Environment

System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

Detailed check results:

The package "expo-modules-autolinking" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.
The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

One or more checks failed, indicating possible issues with the project.

**Comment by brentvatne** [comment]
hi there,

- please fix the doctor warnings in your project
- this could be due to the targetSdkVersion / compileSdkVersion if you have that defined in your app config. sdk 50 targets android sdk 34.
- ensure you are using jdk 17.
