### ISSUE TITLE
[expo-updates]AppController.sharedInstance Thread 1: Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by meftunca** [expo/expo#28049]
### Minimal reproducible example

no-link

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I switched to expo because of the problems I had with codepush. when I get production build in expo-updates ios I get "Swift runtime failure: Unexpectedly found nil while unwrapping an" error. Generally my project is working. I am only having problems with the production version in IOS.

I can't completely switch to expo right now, so I need to work with react-native

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/mapletechnologies/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

(node:8984) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/netinfo@11.3.1 - expected version: 11.1.0
  @shopify/flash-list@1.6.4 - expected version: 1.6.3
  @shopify/react-native-skia@0.1.241 - expected version: 0.1.221
  lottie-react-native@6.7.0 - expected version: 6.5.1
  react-native-gesture-handler@2.16.0 - expected version: ~2.14.0
  react-native-maps@1.13.0 - expected version: 1.10.0
  react-native-pager-view@6.3.0 - expected version: 6.2.3
  react-native-reanimated@3.8.1 - expected version: ~3.6.2
  react-native-safe-area-context@4.9.0 - expected version: 4.8.2
  react-native-screens@3.30.1 - expected version: ~3.29.0
  react-native-svg@15.1.0 - expected version: 14.1.0
  react-native-webview@13.8.4 - expected version: 13.6.4
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by meftunca** [comment]
I added the repo, you can open the issue

**Comment by AhmedHeikal** [comment]
I'm facing the same issue preventing me from releasing

@brentvatne  can you please take a look and reopen this?

**Comment by quannguyen291** [comment]
Facing the same issue here, trying to integrate expo-updates to my existing RN Project.

**Comment by meftunca** [comment]
If you are migrating from a bare react-native, please rebuild it with expo prebuild by renaming (backup) the android and ios directories.

This is how I solved my problem after 3 days of trying
@quannguyen291  @AhmedHeikal

**Comment by AhmedHeikal** [comment]
@meftunca Can you elaborate more please .. what you did exactly?

**Comment by AhmedHeikal** [comment]
Thanks man, really appreciated @meftunca 

BTW, What did you use to build your app?

like in the terminal `npx expo start` or  `npx react-native run-ios` ?

**Comment by meftunca** [comment]
First you need to build with xcode and after starting with "npx expo start" you can activate the developer console by pressing "s". The reason is probably that it runs as a standard react native project other than the Expo go application.

**Comment by meftunca** [comment]
Unfortunately, expo metro config settings with "npx react-native run-ios" does not work properly. Use "npx expo start" instead

**Comment by AhmedHeikal** [comment]
Thanks bro .. really appreciated, you saved a lot of time for me ))

**Comment by meftunca** [comment]
Don't mention it, man :) Anyway, this problem is like a bottomless pit. I worked for 3 days and recreated the native folders of the project by saying fuck it ⚔️ 
Project owners should ensure that this solution is automatically implemented when they have time

Good improvements my friend  @AhmedHeikal :)

**Comment by carl0shd** [comment]
i am using a managed project and still have the same problem :(
