### ISSUE TITLE
[docs] Expo should drop Yarn 1 recommendation

### ISSUE THREAD

**Issue by GlenTiki** [expo/expo#28057]
### Summary

Yarn 1, while not explicitly deprecated, is frozen for development and fixes, and from what I can understand, it is pretty much deprecated. It's unclear how it's treated for security fixes at this time. [I have reached out to check here](https://github.com/yarnpkg/yarn/issues/8583#issuecomment-2039797514). There hasn't been a patch made against it in 2+ years.

If you look at the [yarn 1 repo](https://github.com/yarnpkg/yarn), it says 

> If you hit bugs or issues with Yarn 1.x, we strongly suggest you migrate to the latest release - at this point they have been maintained longer than 1.x, and many classes of problems have already been addressed there. By using the nodeLinker setting you'll also have the choice of how you want to install your packages: node_modules like npm, symlinks like pnpm, or manifest files via Yarn PnP.

With this in mind - can expo move on from explicitly recommending it as a package manager?

### Link to the related docs page

https://docs.expo.dev/get-started/installation/

### Anything else?

A more modern recommendation is required if the yarn 1 suggestion is removed. `npm` is shipped with node, so it feels correct, right now. [Even React Natives docs use npm](https://reactnative.dev/docs/environment-setup?guide=native)

**Comment by brentvatne** [comment]
hi there! we would love to do so, but we still feel that the safest option is to use yarn v1.

- none of the new linking approaches like pnp or isolated modules work 100% with react-native yet. @byCedric has been working hard to improve compatibility in the ecosystem, but i'm sure he'd appreciate help if you want to work on this too!
- many library authors still don't do a great job of maintaining their peer dependencies lists, and as a result of the behavior where npm installs peer dependencies automatically if they aren't satisfied, this can occasionally lead to issues that are difficult for beginners to debug
- i personally don't like having to recommend using a yarnrc that forces the node-linker compat mode when recommending yarn v2+
- yarn v1 still works great for our use cases.

> [Even React Natives docs use npm](https://reactnative.dev/docs/environment-setup?guide=native)

in react-native 0.74, @react-native-community/cli will always use yarn v3 - it ships with a yarnrc to force usage of the node-linker. so in the next release, when you run `npx react-native init` it will use yarn. i personally don't like this approach, but just sharing for context.

**Comment by hongbo-miao** [comment]
Maybe just simply getting rid of yarn v1, so switch from "yarn v1 + npm" to "npm" only?
![image](https://github.com/user-attachments/assets/ea9e7ded-7eb8-4554-a2a9-2b2ad6a695df)

This screenshot left side is yarn 1 (4 years ago version), right side is npm 7 (4 years ago version). And today newer npm 10 is even faster.
