### ISSUE TITLE
[expo-updates]AppController.sharedInstance Thread 1: Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value #28049

### ISSUE THREAD

**Issue by meftunca** [expo/expo#28055]
### Minimal reproducible example

https://github.com/meftunca/expo-updates-crash

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I switched to expo because of the problems I had with codepush. when I get production build in expo-updates ios I get "Swift runtime failure: Unexpectedly found nil while unwrapping an" error. Generally my project is working. I am only having problems with the production version in IOS.

I can't completely switch to expo right now, so I need to work with react-native

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/mapletechnologies/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

(node:8984) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/netinfo@11.3.1 - expected version: 11.1.0
  @shopify/flash-list@1.6.4 - expected version: 1.6.3
  @shopify/react-native-skia@0.1.241 - expected version: 0.1.221
  lottie-react-native@6.7.0 - expected version: 6.5.1
  react-native-gesture-handler@2.16.0 - expected version: ~2.14.0
  react-native-maps@1.13.0 - expected version: 1.10.0
  react-native-pager-view@6.3.0 - expected version: 6.2.3
  react-native-reanimated@3.8.1 - expected version: ~3.6.2
  react-native-safe-area-context@4.9.0 - expected version: 4.8.2
  react-native-screens@3.30.1 - expected version: ~3.29.0
  react-native-svg@15.1.0 - expected version: 14.1.0
  react-native-webview@13.8.4 - expected version: 13.6.4
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
![Screenshot 2024-04-05 at 11 42 18](https://github.com/expo/expo/assets/19187204/a9ded7c5-76d3-41be-8e9e-a6bdab4d0cb4)

**Comment by meftunca** [comment]
I have a similar problem.

**Comment by stianko** [comment]
I think I have a similar issue [https://github.com/expo/expo/issues/28046#issuecomment-2039360942](https://github.com/expo/expo/issues/28046#issuecomment-2039360942)

**Comment by meftunca** [comment]
@stianko Are you getting an error in the project you created with 'react-native init'?

**Comment by stianko** [comment]
No, this is an "old" expo project.

**Comment by brentvatne** [comment]
@meftunca - can you share a video recording of you walking through the steps of reproducing this issue in the repository that you shared?

**Comment by meftunca** [comment]
Sorry I can't share right now. I couldn't solve the problem and rebuilt with "npx expo prebuild --clean". Problem solved now

**Comment by CCB-cerivera** [comment]
Hello, I have the same problem, but I have not been able to solve it with prebuild, or any other command that I can execute, anyone who is going through the same thing, or has solved it, I have the latest version of react-native and expo. It was verified with expo-doctor and no, however, the problem continues on iOS
`
Thread 1: Assertion failed: AppController.sharedInstace was called before the module was initialized`

**Comment by shjimb** [comment]
My app started crashing on launch after installing the expo-updates package, but I could solve the issue by replacing `@interface AppDelegate : RCTAppDelegate` with `@interface AppDelegate : EXAppDelegateWrapper` in AppDelegate.h.

Ref: https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-ios

**Comment by carl0shd** [comment]
I have the same problem with a managed project, Expo Updates is broken with SDK 50.

**Comment by CCB-cerivera** [comment]
> My iOS app started crashing on launch after installing the expo-updates package, but the issue has been solved by replacing `@interface AppDelegate : RCTAppDelegate` with `@interface AppDelegate : EXAppDelegateWrapper` in AppDelegate.h.
> 
> Ref: https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-ios

In my case, it didn't work to do it as indicated in the documentation you posted (I had already tried it before), the only way to continue the project was to downgrade to `"expo-updates": "^0.22.0"`, which works for `android and iOS` with `SDK50 and RN version 0.73.7`

**Comment by shjimb** [comment]
I realized that my iOS app was still crushing in release mode, but it turned out I needed to add Expo.plist on Xcode (project.pbxproj) manually.

> Add the Supporting directory containing `Expo.plist` to your project in Xcode with the following content, to match the content in app.json:

ref: https://docs.expo.dev/bare/installing-updates/#ios
ref: https://github.com/expo/expo/issues/19444#issuecomment-1358874778

|Xcode|
| --- |
| <img width="973" alt="xcode" src="https://github.com/expo/expo/assets/13975783/2c271ed5-9894-4d3c-813b-64200f391889"> |

After adding the `Supporting` Group and `Expo.plist` on Xcode, the crashing issue was resolved in both debug and release mode.
```bash
$ npx expo run:ios --configuration Release
$ eas build -p ios --profile production --auto-submit --non-interactive
```

---------
Packages Versions:
- expo: 50.0.15
- expo-updates: 0.24.12
- react: 18.2.0
- react-native: 0.73.5

Local environment:
- node: 18.16.1
- cocoapods: 1.15.2
- xcode: 15.2
