### ISSUE TITLE
Expo Router: Swipe gesture to navigate back to previous route in stack is not working

### ISSUE THREAD

**Issue by marcelo-schroeder** [expo/expo#28052]
### Minimal reproducible example

https://github.com/marcelo-schroeder/expo-router-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Steps to reproduce:

1. launch app on the iOS simulator (it's Expo Go)
2. Press the "Navigate to screen two" button
3. Use the "swipe back" gesture to navigate back

Actual result:

The gesture is not recognised. The only way to go back to the previous screen is to tap the back button on the nav bar.

Expected result:

The "swipe back" gesture should navigate back to the previous screen. Please note that this behaviour is correct when using React Navigation v6 (without Expo and Expo Router).

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/marceloschroeder/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14
      expo-router: ~3.4.8 => 3.4.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by marcelo-schroeder** [comment]
I have also tried to add:

```
import "react-native-gesture-handler";
```

to the top of the top level `_layout.tsx` to no avail.

**Comment by marcelo-schroeder** [comment]
Update on this: the swipe back gesture is working in release builds. So, the issue could be related to either running it on the simulator or in debug mode.

**Comment by alexandreandriesse** [comment]
I have the same behavior. Plus the swipe back does not work in production. 

I don't encounter this UIKitCore error, though.

**Comment by stuttskl** [comment]
Any update on this? I am facing the same issue in the iOS simulator and the device (thru TestFlight)

**Comment by kolaade271** [comment]
Am experiencing the same issue, 
in fact this is very bad

**Comment by brunobely** [comment]
Still happening

**Comment by heondo** [comment]
can we reopen this? Not seeing a way to go back. Maybe its the way my stacks are configured but would appreciate insight

**Comment by Jekiwijaya** [comment]
so I also get this same issue, but when i use
```
<Stack
  screenOptions={{
    fullScreenGestureEnabled: true,
  }}
>
```
it works
