### ISSUE TITLE
Nested Navigating

### ISSUE THREAD

**Issue by kamalmplus** [expo/expo#28066]
### Minimal reproducible example

its a concept issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Having a root (tabs) navigator containing several /routes/

_layout.tsx are basically Stack />
Tabs: 
profile/
-- orders/
----- _layout.tsx
----- index.tsx
----- [id].tsx

cart/
---- _layout.tsx
---- successfully-ordered.tsx

navigating using router.navigate, or navigate.replace or navigate.push from successfully-ordered to (tabs)/profile/orders/123 
makes the profile tab stuck on that nested screen, with no ability to get back to anything
expected behavior: going back from /123 to /orders and from there to /profile

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
      Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 31, 33, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.2, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0 => 50.0.4 
      expo-router: ~3.4.5 => 3.4.6 
      react: ^18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 6.0.0
      expo-cli: 6.3.7
    Expo Workflow: managed

**Comment by Code-Victor** [comment]
were you able to solve this issue?
