### ISSUE TITLE
 Error: Module "7" is missing from the asset registry [Expo 50, Expo-Router]

### ISSUE THREAD

**Issue by agrittiwari** [expo/expo#28070]
### Minimal reproducible example

https://github.com/agrittiwari/devStory

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

App simply does not load font, I changing the Icons pack I am using to Ionicons instead of FontAwesom,  and installed asset registry packages and what not, cleaned the iOS  folder and re-installed the packages multiple times. It does not load icons and stuck on this error.
![image](https://github.com/expo/expo/assets/51356497/034cdb0a-dca7-4792-b620-273020382396)

### Environment

 ```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.5 => 50.0.14 
      expo-router: ~3.4.7 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: bare
```

**Comment by marklawlor** [comment]
@agrittiwari I'm closing this issue because your reproduction is simply too large. Can you please reproduce your issue in a minimal repo so we can troubleshoot effectively.

**Comment by agrittiwari** [comment]
okay, I'll do so.

**Comment by tmitchel2** [comment]
This is due to expo-font not being compatible with new architecture... i have this issue myself and trying to find a solution.

**Comment by ycldz** [comment]
I get this error
Module "4" is missing from the asset registry

**Comment by rebebop** [comment]
@tmitchel2 Did you find a solution for this?

**Comment by stavthal** [comment]
> I get this error Module "4" is missing from the asset registry
> 
> edit: gave error due to expo-font. I uninstalled it and it fixed it.

Not only it stopped the logging of this, but for some reason it was the cause of my local images (the ones stored in the project files) not rendering on both android and ios. Huge thumbs up for this, as it gave closure to an issue that I have been facing for almost a week!

**Comment by agrittiwari** [comment]
hey, Idk, but I was stuck at this for very long time , as @stavthal and @ycldz  says it's related to expo-font and icons. 
A fix I got and solved by adding resolution in package.json. [https://github.com/expo/vector-icons/issues/290#issuecomment-2148840592](https://github.com/expo/vector-icons/issues/290#issuecomment-2148840592)
