### ISSUE TITLE
`eas update` in SDK 49 doesn't use Config.js, nor EAS eas.json env resulting app.config.ts not having proper ENV.

### ISSUE THREAD

**Issue by pencilcheck** [expo/expo#28077]
### Summary

https://docs.expo.dev/eas-update/environment-variables/

None of the things specified here are true. I tested it and print out what's in process.env.VARIABLE in app.config.ts and it doesn't show up anything.

I don't understand why `eas update` doesn't use existing eas.json env and let us specify the profile as well. Why make a separate channel and can't load those ENV already defined there?

I tried Config.js and that file never get loaded, as I verified by console.log in the file.

I wish eas update is usable, I really wanted it to work. But at this momoent it is very frustrating and require duplicating tons of ENV variable and make things very hard to manage when making EAS update.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

    "expo": "49",
    "expo-dev-client": "~2.4.12",
    "expo-updates": "~0.18.19",

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 3.6.4 - /opt/homebrew/bin/fish
    Binaries:
      Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v21.5.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 30, 32, 33, 33, 34
        Build Tools: 30.0.2, 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86_64 Atom, android-31 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86_64 Atom, android-UpsideDownCake | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: managed

### Reproducible demo

[demo-eas-update-bug.zip](https://github.com/expo/expo/files/14899319/demo-eas-update-bug.zip)

The problem is that eas.json ENV isn't shared with `eas update` command channel.

**Comment by brentvatne** [comment]
> The problem is that eas.json ENV isn't shared with eas update command channel.

this is the current behavior, see https://expo.dev/blog/what-are-environment-variables#synchronizing-between-environment-variables-in-eas-update-and-eas-build for more information
