### ISSUE TITLE
Expo start : Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by auchaphon** [expo/expo#2807]
expo start in terminal : TypeError: Cannot read property 'compile' of undefined

please help

expo version : 2.4.0
node version : 10.13.0
macos Mojave : 10.14.1

**Comment by ankraj077** [comment]
Same here

`TypeError: Cannot read property 'compile' of undefined`

This is so frustrating

Wasting hours of time to solve this types of errors instead of doing some real work on app features. 

This is completely demotivating me to work on my stuff. Expo has bunch of such issues. Not good.

**Comment by ministerface** [comment]
Me too !
TypeError: Cannot read property 'compile' of undefined

**Comment by sjchmiela** [comment]
Hey all, try upgrading to `expo-cli@2.4.1`, the issue has been solved there. See https://github.com/expo/expo-cli/issues/213
