### ISSUE TITLE
Default exporting unnamed function in layout causes navigation state loss on hot-reloading

### ISSUE THREAD

**Issue by marlonschlosshauer** [expo/expo#28071]
### Minimal reproducible example

https://github.com/marlonschlosshauer/expo-router-named-default-exports

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I noticed while developing that when I navigated from route A to route B and saved my code (even in a totally unrelated file), that the app would lose navigation state, meaning I would end up on the initial route A again. 

Did some digging and found that I was default exporting an anonymous function inside of my layout like this:
```ts
export default function () {
    // ...
}
```

Giving that function a name fixed the issue:
```ts
export default function Test() {
    // ...
}
```

Here are two videos that utilize the Expo Router example setup to showcase what I was experiencing:

https://github.com/expo/expo/assets/24259317/6d6985b0-d9a4-496c-9c1c-7243eff0cef1

1.  Export default function is named
2. Navigate to "Tab Two"
3. Make code change 
4. App hot reloads 
5. Still on "Tab Two" route

https://github.com/expo/expo/assets/24259317/e12837b3-10d4-42b4-8b81-d92663039dd2

1. Removing the name from the exported function
2. Navigate to "Tab Two"
3. Make code change
4. App hot reloads
5. Now on "Tab One" route

The linked repo has two commits:
1. Output of `npx create-expo-app@latest --template tabs@50`
2. Removing the name from the default exported function

Having now found a fix for this, I'm opening this ticket more to document this behavior. Feel free to close this if this isn't an issue with the Expo Router directly. 

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.2.0
      expo-cli: 6.3.8
    Expo Workflow: managed

```

**Comment by marklawlor** [comment]
It is a known issue that using anonymous components with React will cause fast refresh issues. As layouts are React components, they should be named as well. Naming React components goes beyond Fast Refresh, and ensures tools like the React Inspector and even React's error messages will work correctly.
