### ISSUE TITLE
Expo store review not working on android emulator 

### ISSUE THREAD

**Issue by lucabc2000** [expo/expo#28080]
### Minimal reproducible example

https://github.com/lucabc2000/StoreReviewIssue

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

**Expected Behavior:** When using the expo-store-review module, invoking StoreReview.requestReview() after a button press is expected to trigger the native store review flow on both iOS and Android platforms. This flow should allow users to leave a review directly within the app interface.

**Actual Behavior:** While the expected behavior is observed on iOS, with the review prompt appearing as intended when the button is pressed, the review prompt does not appear on Android devices. This discrepancy occurs despite similar testing conditions and configurations on both platforms.

**Affected Platforms:** The issue is specific to Android devices; iOS devices are not affected and behave as expected.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alanjhughes** [comment]
Hi @lucabc2000 - Have you published a version of your app? This api does not work on android unless the app has already been published or is available on one of the test tracks

**Comment by lucabc2000** [comment]
Hello @alanjhughes - The app has been published and is available on the Google Play Store.

**Comment by alanjhughes** [comment]
Have you tried on a physical device? The emulator will need to have google play services installed. Not all of them do

**Comment by lucabc2000** [comment]
@alanjhughes - Yes I tried on a 2 different physical android devices, but on both the devices the modal didn't show up.

**Comment by alanjhughes** [comment]
@lucabc2000 - I just ran your repro and it works fine for me. Google also have this note in their documentation

> Note: In some circumstances the review flow will not be shown to the user, e.g. they have already seen it recently, so do not assume that calling this method will always display the review dialog.

![Screenshot_20240408-120417](https://github.com/expo/expo/assets/30924086/c6dc7da1-4349-4742-b3cd-3491020ddcda)
