### ISSUE TITLE
Pause and Resume recording a video is not continue

### ISSUE THREAD

**Issue by nghiata** [expo/expo#2809]
I am building a camera app (android target)
My problem is during recording a video. I look forward after pause and resume a video It should record continue but it's freezed after I save my record video.
This is my code:

```
    if (!this.state.isStartRecordVideo) {
            this.props.pauseRecordVideo();
    }
    else {
            this.props.resumeRecordVideo();
    }
```

```
    <FooterCamera
            ref={(footer) => this.footer_camera = footer}
            imageUri={this.state.imageUri}
            takePicture={(timer, quality) => this.takePicture(timer, quality)}
            startRecordVideo={() => this.startRecordVideo()}
            stopRecordVideo={() => this.stopRecordVideo()}
            pauseRecordVideo={() => this.camera.pausePreview()}
            resumeRecordVideo={() => this.camera.resumePreview()}
            stopCountDownAnimate={() => this.stopCountDownAnimate()}
    />
```

expo version: 2.1.3
Device: android

**Comment by tcdavis** [comment]
Thanks for the report.  Could you provide a repro case in a snack (snack.expo.io) so we can track down the issue more quickly?

**Comment by nghiata** [comment]
My problem is at 2 methods `pausePreview` and `resumePreview`. When I paused and resumed again It doesn't recording continue.
I have no plans to show my project on snack but I will provide a small demo to clearly.

**Comment by nghiata** [comment]
https://expo.io/@john_snow/MyApp

You can see a repo case above. After stop a recorded video. It saved to camera roll on device.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. This repro is not usable on the current Expo client, and we can't upgrade it since we don't have the source code. Please create a new issue with a full repro case (ideally a [snack](https://snack.expo.io)) if this still happens in any of the currently supported SDK versions. Thanks!
