### ISSUE TITLE
Code Signing issue when build standalone IOS app locally

### ISSUE THREAD

**Issue by LeiZeng** [expo/expo#281]
HI guys,

I have followed the instruction section to build the app locally after adding some native code change. Everything is fine until I was going to sign the .app into .ipa to Testflight.
I got the following error when I use xcodebuild to manually code signing:
`xcrun xcodebuild -exportArchive -exportOptionsPlist exportPlist.plist -archivePath ./Exponent.xcarchive -exportPath ~/Exponent.ipa`

Key error:
```
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found development
```
I also tried to fix it and I found the documentation: https://developer.apple.com/library/content/technotes/tn2215/_index.html

Where I found my xcarchive is a "generic Xcode archive"...

Do you guys have any idea or any experience like this?

Thanks!

**Comment by terribleben** [comment]
Hi, just to double check my understanding, it sounds like you ran `exp detach` to create a local xcode project which uses ExpoKit.

Expo doesn't do anything extra to manage your codesigning beyond this point. It is just a normal Xcode project. So you should be able to build/archive/sign binaries however you want.

So far, we haven't had anybody else report the same behavior you are seeing. Based on reading that link you pasted, maybe it has something to do with extra libraries you added to your project?

**Comment by LeiZeng** [comment]
I am not detaching the project, but trying to bundle the expo client it self.

**Comment by terribleben** [comment]
You're building github.com/expo/expo from source? Are you sure you need to do that? Using `ExpoKit` is almost the same thing, except we do most of the work for you.

**Comment by LeiZeng** [comment]
Ok, I can try detach to ExpoKit to see if it works to me.

Thanks

**Comment by xavier-villelegier** [comment]
@LeiZeng What did you finally do ? I have the same issue, I'm trying to build the app from my side, but the archive generated is recognized as a “Generic Xcode Archive”, not as a “iOS App Archive”, so I can't extract any `.ipa` 🤔
