### ISSUE TITLE
[expo-camera/next]: changing back camera to front camera doesn't work in sdk 50

### ISSUE THREAD

**Issue by Aycom366** [expo/expo#28119]
### Minimal reproducible example

https://github.com/Aycom366/expo-nuggets/blob/main/app/camera-swap-scroll/index.tsx

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I copied exactly what was in the example to use the camera from camera/next. However, the flipping of the camera did not work. 
I also set the facing prop to be front, but instead, it still defaults to the back camera. This was tested on Expo Go on Android.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2023.05.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by alanjhughes** [comment]
Hi @Aycom366, your usage is incorrect. The type is a string union, not an enum. You should also not be importing anything from a build folder. Your example is not minimal, includes firebase etc. If you still have a problem after changing to the correct usage, create a minimal example that exhibits this issue only and ping me, I will reopen.

**Comment by Aycom366** [comment]
I was actually using a string before, and it didn't work before I resorted to using enum.

So the enum shouldn't be the issue why it's not flipping @alanjhughes

**Comment by alanjhughes** [comment]
@Aycom366 - I just created a new project, used your example and changed to the correct usage and it works on both platforms in expo go

**Comment by Aycom366** [comment]
@alanjhughes 

Hmm, that's weird, so what could be wrong?
by the way, I also created a new project which can be found here [https://github.com/Aycom366/expo-camera-next](Minimal) and I'm still having the same issue.
I'm testing on expo go, xiaomi redmi note 11s and please find the screen record that I did.

https://github.com/expo/expo/assets/42998943/64e2132b-717f-4da3-b50f-35db85ed57fb

**Comment by alanjhughes** [comment]
Just tried your example. It still works. I also don't see the error related to the plugin. Not sure what's the problem on that device, it is supported https://developer.android.com/media/camera/camerax/devices
