### ISSUE TITLE
Placing a Svg element crashes the app, sdk v.31

### ISSUE THREAD

**Issue by giacomocerquone** [expo/expo#2811]
### Environment

diagnostics fail with status code 500

Node 10, npm 6.4.1, windows 10

Target: Android

### Steps to Reproduce

1. Use an Svg component
2. Watch your app crash

### Expected Behavior

it shouldn't crash the app

### Actual Behavior

The app crashes

### Reproducible Demo

https://snack.expo.io/H1VGh_tCQ

This is the reproducible snack, sdk v31. trying to start it on my smartphone (or in an emulator) crashes the app.

**Comment by tcdavis** [comment]
You'll need to specify a height and width to avoid a crash on android
https://snack.expo.io/@thetc/YXdrd2
