### ISSUE TITLE
`componentWillUnmount` Is Not Called When Reloading In Development

### ISSUE THREAD

**Issue by SteveAquino** [expo/expo#2812]
### Environment

Environment:
  OS: macOS 10.14
  Node: 8.11.4
  Yarn: 1.7.0
  npm: 6.4.0
  Watchman: 4.7.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/saquino88-db09691a-3af2-4e37-ac3e-baf00168eeb3.tar.gz

Targeting iOS and Android.

### Steps to Reproduce

1. Open the app in development mode using the Expo app
2. Shake the device to open the developer menu and click "Debug Remote JS"
3. In the browser console, open the options and select "Preserve Logs"
4. Shake the device to open the developer menu and click "Reload"

### Expected Behavior

There should be a console log statement in the browser console that says "unmount".

### Actual Behavior

The component mounts each time, but never unmounts.  Instead, "mount" is printed twice, indicating that the setup code runs each time but the tear down code does not.

### Reproducible Demo

Snack:

https://snack.expo.io/@saquino88/mount-unmount-test

Code:

```javascript
import * as React from 'react';
import { AppState, Text, View, StyleSheet } from 'react-native';

export default class App extends React.Component {
  componentDidMount() {
    console.log('mount');

    AppState.addEventListener('change', (state) => {
      console.log('state change', state);
    });
  }

  componentWillUnmount() {
    console.log('unmount');
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          Reload the App to test.
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  paragraph: {
    fontSize: 18,
    textAlign: 'center',
  },
});

```

### More Info

This is a problem in my case because it results in a bunch of unclosed WebSocket connections, and there's no way to close them properly in development.  If `componentWillUnmount` will not or can not be called, Expo should provide another callback when the app is refreshed in development.

**Comment by tcdavis** [comment]
Hi Steve,
componentWillUnmount is not actually guaranteed to be called.  In the web context you can do something like an onBeforeUnload listener, but I'm not sure there's a way to do the same thing in RN.  Not a bad idea, but we would need to think through how that should work.
For now, you could try storing information about the websocket connections you create to asyncStorage, and reconnect on mount rather than establishing new connections every time.

**Comment by FiberJW** [comment]
This seems to be resolved, so I’ll close this for now. If you need further support, please make a topic on our [forums](https://forums.expo.io) :)
