### ISSUE TITLE
[docs] "Use ESLint and Prettier": eslint@9.0.0 is not compatible with eslint-config-universe

### ISSUE THREAD

**Issue by iwaynee** [expo/expo#28144]
### Problem

On the page https://docs.expo.dev/guides/using-eslint/ the install uses just "eslint".

ESLint has now officially moved to Version 9.0.0

eslint-config-universe is not compatible with eslint 9.0.0 because of https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getscope() which is in itself no issue but please mention to download the right version of eslint since this guide no longer works.

### Solution

Change the install to eslint@8.57.0 and mention that eslint-config-universe is not compatible with eslint@9.0.0

### Link to the related docs page

https://docs.expo.dev/guides/using-eslint/

**Comment by byCedric** [comment]
Hi @iwaynee! You are right, unfortunately, ESLint v9 brought many breaking changes, including the [flat config](https://eslint.org/docs/latest/use/configure/migration-guide) and API breaking changes.

Although `eslint-config-universe` is mostly our internal (not necessarily external, but more news on that soon) styling rules. Work is already in progress to move over to the [new flat config format](https://github.com/expo/expo/compare/main...%40bycedric/eslint-config-universe/flat-config). 

We are tracking the issue around `context.getScope` through https://github.com/jsx-eslint/eslint-plugin-react/issues/3699. So we might not be able to move to ESLint v9 until that's solved.

We can definitely pin ESLint to v8 for now.

**Comment by dani-mp** [comment]
@byCedric so just to be sure, if we want to use `eslint-config-expo`, we need to use eslint 8 for now, right?

**Comment by jerone** [comment]
ESLint v8.x end of life was October 5, 2024. It might be time to prioritize this issue.

https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/

**Comment by adrian-gierakowski** [comment]
> We are tracking the issue around `context.getScope` through [jsx-eslint/eslint-plugin-react#3699](https://github.com/jsx-eslint/eslint-plugin-react/issues/3699). So we might not be able to move to ESLint v9 until that's solved.

this issue has now been resolved 

@byCedric  are there any other blockers to moving to v9, apart from someone having to do the work?

**Comment by iainbeeston** [comment]
Is it possible to reopen this issue? Having to use ESLint 8 for a new project in 2025 (for expo compatibility) seems really odd. As @adrian-gierakowski mentioned the original reason eslint-config-universe couldn't upgrade to ESLint 9 was fixed in July 2024

**Comment by adrian-gierakowski** [comment]
I just hit this again as in a process of upgrading to eslint 9 in a large monorepo and our mobile app is the only package which will stay behind because of expo

**Comment by diegoleondev** [comment]
Hi, any update on the topic?

**Comment by TasseDeCafe** [comment]
I agree with the last posts here, there should be an official update to eslint 9.

**Comment by Mikelangelo64** [comment]
Hey everyone, I probably found a solution to use flat config with expo.

We can use '[@eslint/eslintrc](https://github.com/eslint/eslintrc#usage)' package to define necessary for expo config in flat config using old style.

My eslint.config.mjs file (I'm still using eslint v8 because it was installed with expo by default):
`import path from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

export default [
  ...compat.config({
    extends: 'expo',
    ignorePatterns: ['/dist/*', '/app-example/*'],
  }),
];`

It works fine for me (at least now while I don't add more config rules). Also I don't know very much about **context.getScope** issue. Please let me know if my solution helps anyone or if I'm doing something wrong.

[Official eslint doc page about "Using eslintrc Configs in Flat Config"](https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config)

**Comment by jerone** [comment]
Work is in progress: 

#28713
#34371 
#34653

No idea which one is leading

**Comment by ide** [comment]
ESLint v9 and the flat config format are supported as of SDK 53 with eslint-config-expo, which is our recommended linter configuration for projects outside of this repo: https://docs.expo.dev/guides/using-eslint/#migration-to-flat-config

ESLint v9 is also supported with eslint-config-universe: https://github.com/expo/expo/blob/51a6c3c7136c8bd14012b43c3c6d4a3244985196/packages/eslint-config-universe/package.json#L64

**Comment by Noitham** [comment]
We have issues with new initialized `expo-modules`:

```
$ expo-module lint

Oops! Something went wrong! :(

ESLint: 9.28.0

ESLint couldn't find an eslint.config.(js|mjs|cjs) file.

From ESLint v9.0.0, the default configuration file is now eslint.config.js.
If you are using a .eslintrc.* file, please follow the migration guide
to update your configuration file to the new format:

https://eslint.org/docs/latest/use/configure/migration-guide

If you still have problems after following the migration guide, please stop by
https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Mikelangelo64** [comment]
> ```
> $ expo-module lint
> ```

@Noitham hey, try `expo-module eslint . ` instead  `expo-module lint`
