### ISSUE TITLE
The build crashes after the expo 50 update

### ISSUE THREAD

**Issue by ritchann** [expo/expo#28171]
### Minimal reproducible example

Expo SDK 50.0.15

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I have updated the libraries and now my package.json looks like this:

{
  "name": "ssc-mobile",
  "version": "1.0.0",
  "scripts": {
    "tunnel": "expo start --tunnel",
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/cli": "^0.10.14",
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/free-solid-svg-icons": "^6.4.2",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/datetimepicker": "7.6.1",
    "@react-native-community/viewpager": "^5.0.11",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/elements": "^1.3.30",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.20",
    "@types/react": "~18.0.27",
    "acorn": "^8.11.2",
    "axios": "^1.6.1",
    "date-fns": "2.30.0",
    "expo": "^50.0.15",
    "expo-cellular": "~5.7.1",
    "expo-device": "~5.9.3",
    "expo-file-system": "~16.0.8",
    "expo-local-authentication": "~13.8.0",
    "expo-localization": "~14.8.3",
    "expo-notifications": "~0.27.6",
    "expo-secure-store": "~12.8.1",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-updates": "~0.24.12",
    "i18next": "^21.6.14",
    "native-base": "^3.4.28",
    "query-string": "^8.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^11.16.1",
    "react-native": "0.73.6",
    "react-native-calendars": "^1.1302.0",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.6.4",
    "typescript": "^4.9.4",
    "yup": "1.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.23.3",
    "@expo/ngrok": "^4.1.1",
    "@types/react": "~18.2.45",
    "@types/react-dom": "~18.0.10",
    "@types/yup": "0.29.14",
    "@typescript-eslint/eslint-plugin": "6.10.0",
    "@typescript-eslint/parser": "6.10.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.53.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-import": "^2.29.0",
    "eslint-plugin-jsx-a11y": "^6.8.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "3.0.3",
    "prettier-loader": "3.3.0",
    "typescript": "^5.3.0",
    "webpack": "^5.89.0"
  },
  "overrides": {
    "@expo/config-plugins": "~7.8.0",
    "@expo/prebuild-config": "~6.7.0",
    "@expo/metro-config": "~0.17.1"
  },
  "private": true
}

After this update, I had a build error:

Error: Cannot find module '@expo/cli/build/src/export/metroAssetLocalPath'
Require stack:
- /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js'
  ]
}

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 
    Binaries:
      Node: 18.20.1 
      npm: 10.5.0 
    npmPackages:
      expo: ^50.0.15 => 50.0.15
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by jkstrawn** [comment]
For anyone who runs into this issue, the solution for me was to update my `@expo/cli` package from `^0.10.11` to the current latest (`^0.17.10`)

**Comment by osmanbaskaya** [comment]
The same issue is happening to me with iOS. I managed to build the app with `run-ios` in my local machine, but I am getting the error on the eas to build (production). I also have 0.17.10 in my local. @jkstrawn - do you have any idea?
