### ISSUE TITLE
TypeError: body used already for: https://api.expo.dev/v2/auth/loginAsync when using npx expo login

### ISSUE THREAD

**Issue by kangah-codes** [expo/expo#28179]
### Summary

When starting a newly created expo project which was created with `npx expo-create-app new_app`, I get the error: `Unable to reach well-known versions endpoint. Using local dependency map expo/bundledNativeModules.json for version validation
CommandError: Unexpected response when fetching version info from Expo servers: Unauthorized.` which seems to be an authorization error. After trying to authenticate using `npx expo login` I then get the error `TypeError: body used already for: https://api.expo.dev/v2/auth/loginAsync`

### SDK Version

50.0.14

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.0.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.8.1
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/kangah-codes/expo-error

**Comment by Kudo** [comment]
hi there! not sure if that help for cleanup local auth and cache files. `mv $HOME/.expo $HOME/.expo.bak` is the command to rename the folder. if that works you could later entirely remove `$HOME/.expo.bak`.

**Comment by kangah-codes** [comment]
> hi there! not sure if that help for cleanup local auth and cache files. `mv $HOME/.expo $HOME/.expo.bak` is the command to rename the folder. if that works you could later entirely remove `$HOME/.expo.bak`.

Unfortunately after doing that expo login still fails with the same error

**Comment by Kudo** [comment]
thanks for sharing the info.
i feel it has some kind of environment issue. could you help to check for more info?
- what happens if `npx expo login` with a incorrect username/password?
- does it help for bumping `expo` version to latest 50.0.15 and reinstalling node_modules?
- do you use one-time password or single sign-on when login?
- could you login on browsers?

**Comment by kangah-codes** [comment]
> thanks for sharing the info. i feel it has some kind of environment issue. could you help to check for more info?
> 
> * what happens if `npx expo login` with a incorrect username/password?
> * does it help for bumping `expo` version to latest 50.0.15 and reinstalling node_modules?
> * do you use one-time password or single sign-on when login?
> * could you login on browsers?

`npx expo login` still fails regardless of whether the username/password is incorrect. After deleting node_modules  bumping expo to 50.0.15  and reinstalling node_modules the issue still persists. I am able to login to expo.dev in my browser, and I don't login with SSO or a one-time password, just my regular email/password pair.

**Comment by brentvatne** [comment]
are you able to open https://exp.host/--/api/v2/versions in your browser and see a json response that beings with the following?

```json
{
  "iosUrl": "https://dpq5q02fu5f55.cloudfront.net/Exponent-2.25.1.tar.gz",
  "templates": [
    {
      "id": "blank",
      "url": "https://d306o6r76fnu7o.cloudfront.net/blank-17.0.1.tar.gz",
      "name": "Blank",
      "iconUrl": "https://d306o6r76fnu7o.cloudfront.net/template_icon_blank.png",
      "version": "17.0.1",
      "description": "The Blank project template includes the minimum dependencies to run and an empty root component."
    },
    {
      "id": "tabs",
      "url": "https://d306o6r76fnu7o.cloudfront.net/tabs-17.0.1.tar.gz",
      "name": "Tab Navigation",
      "iconUrl": "https://d306o6r76fnu7o.cloudfront.net/template_icon_tabs.png",
      "version": "17.0.1",
      "description": "The Tab Navigation project template includes several example screens."
    }
  ],
```

**Comment by kangah-codes** [comment]
> are you able to open https://exp.host/--/api/v2/versions in your browser and see a json response that beings with the following?
> 
> ```json
> {
>   "iosUrl": "https://dpq5q02fu5f55.cloudfront.net/Exponent-2.25.1.tar.gz",
>   "templates": [
>     {
>       "id": "blank",
>       "url": "https://d306o6r76fnu7o.cloudfront.net/blank-17.0.1.tar.gz",
>       "name": "Blank",
>       "iconUrl": "https://d306o6r76fnu7o.cloudfront.net/template_icon_blank.png",
>       "version": "17.0.1",
>       "description": "The Blank project template includes the minimum dependencies to run and an empty root component."
>     },
>     {
>       "id": "tabs",
>       "url": "https://d306o6r76fnu7o.cloudfront.net/tabs-17.0.1.tar.gz",
>       "name": "Tab Navigation",
>       "iconUrl": "https://d306o6r76fnu7o.cloudfront.net/template_icon_tabs.png",
>       "version": "17.0.1",
>       "description": "The Tab Navigation project template includes several example screens."
>     }
>   ],
> ```

Yes, I see the json that begins with this

**Comment by brentvatne** [comment]
what is the output of `npx expo-doctor@latest` for you?

**Comment by kangah-codes** [comment]
> what is the output of `npx expo-doctor@latest` for you?

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✖ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

Unable to reach well-known versions endpoint. Using local dependency map expo/bundledNativeModules.json for version validation
CommandError: Unexpected response when fetching version info from Expo servers: Unauthorized.
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by leonardoprimieri** [comment]
any updated on that? having the same error running expo login on gitlab

**Comment by kangah-codes** [comment]
> any updated on that? having the same error running expo login on gitlab

Still happening unfortunately
