### ISSUE TITLE
[expo-image] Animated images don't animate at small sizes 

### ISSUE THREAD

**Issue by bensaine** [expo/expo#28183]
### Minimal reproducible example

https://github.com/bensaine/expo-gif-bug-mre

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

GIFs below a certain size will not animate on IOS, even if animation is started explicitly. See very simple repro. This 'cutoff' size seems to vary from GIF to GIF and device to device, but is a very problematic bug.

```js
export default function App() {
	const GIF_URL = "https://media1.tenor.com/m/ba6u_c1Mcb0AAAAC/futurenostlgia-laughing.gif"

	return (
		<View style={styles.container}>
			<Text>Normal remote GIF</Text>
			<Image autoplay={true} width={170} height={170} source={GIF_URL} />
			<Text>Same GIF at a smaller size (broken)</Text>
			<Image autoplay={true} width={150} height={150} source={GIF_URL} />
			<Text>Same GIF at a smaller size, local source (broken)</Text>
			<Image autoplay={true} width={150} height={150} source={require("./assets/tenor.gif")} />
		</View>
	)
}
```

https://github.com/expo/expo/assets/34781348/a436cd89-adf5-48c0-b9e2-e6cdfa45bf69

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.8.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by RRaideRR** [comment]
I think I occasionally experienced that in my project as well. Never had the time to reproduce it. Thanks for your efforts there :)

**Comment by terrysahaidak** [comment]
Using `allowDownsampling={false}` fixes the issue for most of the gifs, but we also noticed that certain `contentFit` also causes gifs to not play. Using `contentFit="none"` fixes the rest of the gifs.

Looks like a pretty big bug, @tsapeta

**Comment by ah0y** [comment]
can confirm @terrysahaidak's fix works

**Comment by fobos531** [comment]
Hello @terrysahaidak @bensaine @ah0y 

would you be able to try out the patch provided in https://github.com/expo/expo/pull/28335 and see if it resolves the issue for you?

**Comment by bensaine** [comment]
@fobos531 @tsapeta The patch seems to include a regression! The GIF now plays but at a very accelerated speed.

**Comment by tsapeta** [comment]
@bensaine thanks for letting us know. So I was too hurry to merge it 🙈
I'll try to repro it myself in a moment.

**Comment by tsapeta** [comment]
Alright, I can repro it with the GIF that we have in the tester app. Now the problem is with the duration that we pass here: https://github.com/expo/expo/blob/c9b0dc7aa4762a80ad24bf0cda49b104acf72d9e/packages/expo-image/ios/ImageUtils.swift#L148
It's passing zero for these GIFs, so I guess the platform just plays them as fast as possible (60 or 120 fps). I'm now wondering if this isn't an issue on the SDWebImage side - I'm investigating.

**Comment by tsapeta** [comment]
@bensaine @fobos531 I opened a PR #28371 that hopefully fixes this regression 😉

**Comment by bensaine** [comment]
Nice work !
