### ISSUE TITLE
Expo Router - Nested routes (Tabs inside Drawer) working on iOS but not Android

### ISSUE THREAD

**Issue by AkbarBakhshi** [expo/expo#28194]
### Minimal reproducible example

https://github.com/AkbarBakhshi/RN-Journey

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have created a very minimal example of nested routes using Expo router ( Nativewind also included but most probably irrelevant). Screenshot below shows the folder/file structure:
![Screenshot 2024-04-13 at 10 14 27 PM](https://github.com/expo/expo/assets/46682991/edc974ac-0f9d-47a9-b6ef-f0db0168db7b)

This is working as expected on iOS:
![simulator_screenshot_7849F3EE-9170-4F97-A9D9-A80DB79725F0](https://github.com/expo/expo/assets/46682991/45cbd017-d91b-479c-9d4f-5b1dcb7346f7)

But I see a blank screen on Android:
![Screenshot_1713060990](https://github.com/expo/expo/assets/46682991/24b00c5f-395f-4f5f-8633-b4dc3a856526)

Anyone has any idea why this is happening?

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      npm: 10.5.0 - /usr/local/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.15 => 50.0.15 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.6.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Surprisingly this is a NativeWind issue. On Android `react-native-gesture-handler` uses a special View which doesn't work with the `className` prop isn't working. You can resolve you issue by using an inline style `<GestureHandlerRootView style={{ flex: 1 }}>`
