### ISSUE TITLE
Drawer position is not correct in Expo 49

### ISSUE THREAD

**Issue by zainkhas** [expo/expo#28196]
### Minimal reproducible example

https://snack.expo.dev/@zainkhas/react-native-web---drawer-issue

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

The position of drawer using react-navigation with Expo 49 is not correct when drawerType is `slide`. In Android & iOS the drawer is not visible at all and on Web it shows up in middle of the screen. It is caused by the CSS `transform` property having invalid value. 

Dependencies versions:
"expo": "^49.0.0"
"react-native-web": "0.17.7"
"@react-navigation/drawer": "^6.1.8"
"@react-navigation/native": "^6.0.8"
"react-native-web": "~0.19.6"
"react-native-safe-area-context": "4.6.3"
"react-native-reanimated": "~3.3.0"

<img width="838" alt="image" src="https://github.com/expo/expo/assets/54834436/c436bdd3-7f84-4ad5-8730-dfd4d73c580b">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.0/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.1 
      expo: ^49.0.0 => 49.0.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✖ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

You have an app.json file in your project, but your app.config.js is not using the values from it. Remove the static app.json, or use its values in your dynamic app.config.js. Learn more: https://docs.expo.dev/workflow/configuration

One or more checks failed, indicating possible issues with the project.

**Comment by brentvatne** [comment]
hi there! you can create issues for react-navigation here: https://github.com/react-navigation/react-navigation/issues

this issue tracker is specifically for issues in expo packages. if you believe the issue is specific to some code in this repository, please reproduce the problem without any third party libraries. https://stackoverflow.com/help/minimal-reproducible-example
