### ISSUE TITLE
app.config.ts value is IGNORED: googleServicesFile's value is different than what i pass on app.config.ts

### ISSUE THREAD

**Issue by elyran** [expo/expo#28192]
### Summary

the issue: cannot set a dynamic `google-services.json` location. something is changing it to a random path.

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 20.11.1 - ~/.local/share/pnpm/node
      Yarn: 1.22.21 - ~/.local/share/pnpm/yarn
      npm: 10.2.4 - ~/.local/share/pnpm/npm
      Watchman: 20240322.093209.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-232.10227.8.2321.11479570
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: bare

### Minimal reproducible example

1. init a new Expo project
2. create `app.config.ts` and paste the following:
```
const path = require("path")
import { ExpoConfig, ConfigContext } from 'expo/config';

export default ({ config }: ConfigContext): Partial<ExpoConfig> => {
    if (config.android)
        config.android.googleServicesFile = path.resolve('./tmp/google-services.json')
    return config
}
```
3. exec: `expo prebuild && npx eas-cli build --local --profile development --platform android`
4. getting this output, before it fails:
```
[READ_APP_CONFIG] Using app configuration:
[READ_APP_CONFIG] {
  "name": "expo-6-test",
  "slug": "expo-6-test",
  "version": "1.0.0",
  "android": {
    "adaptiveIcon": {
      "foregroundImage": "./src/assets/images/adaptive-icon.png",
      "backgroundColor": "#ffffff"
    },
    "package": "aaa",
    "googleServicesFile": "/tmp/user1/eas-build-local-nodejs/8abdf489-aaa-zzz/build/tmp/google-services.json"
```
5. notice `googleServicesFile`'s value? some random path instead the one set in `app.config.ts`.
6. when i place an absolute path in `googleServicesFile` the value doesn't change, and the app builds.
7. therefore it seems there's some sort of interference in between, than breaks it. if it's being generated by the EAS server (could definitely be wrong), then it might be a place to look.
8. the error message: `Error: [android.dangerous]: withAndroidDangerousBaseMod: Cannot copy google-services.json from /tmp/user1/eas-build-local-nodejs/8abdf489-ccd1-4da8-ba24-zzz/build/tmp/google-services.json to /tmp/user1/eas-build-local-nodejs/8abdf489-ccd1-4da8-ba24-zzz/build/android/app/google-services.json. Please make sure the source and destination paths exist`

**Comment by elyran** [comment]
All the output, attached.
[build-output-1.txt](https://github.com/expo/expo/files/14972195/build-output-1.txt)
notice the `"googleServicesFile": "/tmp/user1/eas-build-local-nodejs/8324e9f6-df66-4e6c-accb-7e215ec0c478/build/tmp/google-services.json" line. who generated the `/tmp/user1/eas-build-local-nodejs/8324e9f6....` path?

**Comment by brentvatne** [comment]
this is expected. you are running the build on a remote worker, the path that your build is running at is *not* on your local machine it is a machine in our cluster.

https://docs.expo.dev/guides/google-authentication/#upload-google-servicesjson-and-googleservice-infoplist-to-eas
