### ISSUE TITLE
Pressing TextInput Inside Modal Crashes App (Expo File-Based Router)

### ISSUE THREAD

**Issue by topherjamesknoll** [expo/expo#28197]
### Minimal reproducible example

https://gitlab.com/bessssssa/bessa

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I'm trying to use a TextInput inside an Expo Router-generated modal. After navigating to a modal and pressing the input, I should be able to enter text into the field without the app freezing. It seems to only be an issue on a deployed production version of the app.

In my /app/_layout.js file I have something like:

```javascript
<Stack
screenOptions={{
headerShown: false,
}}
>
<Stack.Screen
name={"post"}
options={{ presentation: "modal" }}
/>
```

And, in my /app/post.js file I have something like this:

```javascript
<View style="styles.container">
<TextInput
value={description}
onChangeText={(nextValue) => setDescription(nextValue)}
/>
</View>
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
      npm: 10.2.5 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.8.1
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Hi, I'm marking this is invalid as the reproduction app is in a private Gitlab repo. Can you please make the repo public so we can help resolve your issue.

Additionally some extra information would be appreciated. 

>  It seems to only be an issue on a deployed production version of the app.

Its going to be hard for me to replicate the issue if I need to deployed. Does the issue still occur if you do a production build locally?

**Comment by topherjamesknoll** [comment]
@marklawlor Hmm; that's discouraging anyway would love to get this resolved. I feel like having a TextInput inside an Expo modal isn't an uncommon scenario.

This is my first issue posting, so I might need some clarification on the repo. I can share my repository so you can replicate it, but I'm not sure you want to to go through everything to get to the modal. LOL! Or do you want a barebones Expo app with a modal and I can drop my code in the appropriate places? Other than those two options, I feel like the code in the body of my comment should suffice. Let me know!

As for the issue, I've done what some other folks have done running into this. I pulled out the input into a function, added a momoization so the keyboard sticks, and called that function inside the JSX. Still no luck though.

```javascript
  const InputComponent = () => {
    try {
      return (
        <TextInput
          value={description}
          onChangeText={(nextValue) => setDescription(nextValue)}
        />
      );
    } catch (error) {
      console.error(error);

      return null;
    }
  };

```

```   {InputComponent()}```

**Comment by marklawlor** [comment]
I've love to resolve this issue as well!

> This is my first issue posting, so I might need some clarification on the repo

No problem! The comment above should have all the information you need. We would prefer a barebone Expo app (commonly referred to as a Minimal Reproduction).

> TextInput inside an Expo modal isn't an uncommon scenario

Everytime I have seen this issue its due to an bug in the users code. I'm not saying that its not a bug, but the first step of troubleshooting is isolating the issue - and I cannot isolate without any code. 

> discouraging anyway would love to get this resolved

I hope you understand that without the required information, we cannot afford the time to guess what people's issue are. The template is there so we can resolve your issue in a timely manner.

I'd also appreciate if you answered my question asking if you can reproduce this locally in a production build, or only once deployed.

**Comment by topherjamesknoll** [comment]
I made a repository with an extremely simplified version of what I'm trying to do at [https://github.com/topherjamesknoll/expo-modal-textinput-crash](https://github.com/topherjamesknoll/expo-modal-textinput-crash). You should be able to clone and run it. But, yes, it does only happen in TestFlight or a production build from the app store.

**Comment by topherjamesknoll** [comment]
this is wild any textinput inside a modal freezes the app both in production and in test flight but not on dev builds or simulators. it's been a couple days now trying to figure this out. definitely setting some records. is really no one else experiencing this??? I've commented out so much code and made so many various builds but can't seem to narrow it down and am especially perplexed by it only working in dev build.

**Comment by marklawlor** [comment]
Your example repository is private.

> is really no one else experiencing this

Our issues are public. I'm not aware of a similar reported issue.

**Comment by gtwilliams03** [comment]
I am having a similar issue. TextInput inside a BottomSheet (using react-native-elements which builds on a RN Modal). Suddenly started freezing once you tap inside it. I am still figuring it out and am in the process of trying to reduce this to a basic example since my BottomSheet/Modal stack is a custom component and I need to rule that out as an issue.

**Comment by topherjamesknoll** [comment]
hey @gtwilliams03 that super stinks. i tried everything including tweaking packages and features that were installed and running. i eventually gave up and started building out new features, and behold! i must have changed something that helped. i also kept updating my packages so maybe react native or expo found something and fixed it. who knows what? regardless, I'm sorry I don't have a solution. One thing I did try throughout this puzzling nightmare was removing various KeyboardAvoidingView's throughout the app. perhaps it was one that was living inside a _layout.js. i also tried to tinker with react-native-gesture-handler which I think is used for modals. lastly, there is sentry or logrocket. i tried both to see what was triggering the issue. there were a couple of cryptic things about memory of course and other things that didn't help (lol!) but it might be worth it to you.

**Comment by mmdevs** [comment]
Same issue here. 
Works fine on Android, Expo Go and development build. Only fails in Production.
Debugging with Console shows the error:
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations

I suspect it has to do with Focus on Input Fields. I'm using TextInput as PaperTextInput, KeyboardAvoidingView and ScrollView.
Will try to simplify now.
