### ISSUE TITLE
[expo-firebase-auth] Having issues accessing the currentUser object in second app

### ISSUE THREAD

**Issue by cryptixcoder** [expo/expo#2819]
So I am developing an app that also requires a service provider app, so essentially I'm building two React Native apps one for the customer and the other for the provider. The idea is that I wanted to use the same firebase account. I'm not sure if the usage of the same credentials for both apps is the issue but here's what's happening. On the customer side, user authentication works perfectly, but when trying to log in on the provider side I get a null when logging out:

    firebase.auth().currentUser

Note I am using the same exact authentication code to login on both apps:
handleLogin() {
    const { email, password } = this.state;

    if (email !== "" && password !== "") {
      this.setState({ loggingIn: true });
      firebase
        .auth()
        .signInWithEmailAndPassword(email, password)
        .then(() => {
          this.setState({ loggingIn: false });
        })
        .catch(err => {
          Toastr.showToast(err.message);
          this.setState({ loggingIn: false });
        });
    } else {
      this.setState({ error: "You must enter an email and password." });
    }
    }

**Comment by EvanBacon** [comment]
This should be fixed in rc-5
