### ISSUE TITLE
Using CameraView in the Android emulator should cause the app to crash

### ISSUE THREAD

**Issue by wumo1016** [expo/expo#28203]
### Minimal reproducible example

1

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Using CameraView in the Android emulator should cause the app to crash，but it's normal in the real world
Below is the crash log：
![image](https://github.com/expo/expo/assets/47590453/40584b37-c602-41b3-b14e-7b58693424c2).
Code:
```
import { StyleSheet, View } from 'react-native'
import { CameraView, useCameraPermissions } from 'expo-camera/next'
import { CameraType } from 'expo-camera'

export default function Home() {
  const [permission, requestPermission] = useCameraPermissions()

  if (!permission) {
  }
  if (!permission?.granted) {
  }

  return (
    <View style={styles.container}>
      <View style={styles.cameraBox}>
        <CameraView
          facing={CameraType.back}
          style={{ flex: 1 }}
          onBarcodeScanned={data => {
            console.log(12345, data)
          }}
        ></CameraView>
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  cameraBox: {
    width: 300,
    height: 300
  }
})

```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 4.1.0 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-34 | Google Play Intel x86_64 Atom
    npmPackages:
      expo: ~50.0.14 => 50.0.15 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

**Comment by sefrijn** [comment]
Same issue here. Android emulator crashes when using <CameraView /> from 'expo-camera/next'.
Works fine on iOS simulator
