### ISSUE TITLE
[expo-camera] Not reading Barcode on DevBuild but works fine on Expo Go

### ISSUE THREAD

**Issue by SamJbori** [expo/expo#28215]
### Minimal reproducible example

https://github.com/SamJbori/testerApp

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

The bar scan doesn't work on Dev Build but works fine on Expo Go

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.5.2 - ~/.nvm/versions/node/v20.12.2/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
    npmPackages:
      expo: ~50.0.14 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.8.1
    Expo Workflow: bare
```

iOS dev build using expo EAS

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check native tooling versions
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.
```

**Comment by SamJbori** [comment]
Anoth issue, `CameraView` from `expo-camera/next` keep crashing my iOS app, but works fine on Android, and on iOS Expo Go it doesn't work on iOS

**Comment by alanjhughes** [comment]
Hi @SamJbori - Couple of things happening here. You seem to be mixing up the old and new package and also not passing an barcode settings. 
> Anoth issue, CameraView from expo-camera/next keep crashing my iOS app, but works fine on Android, and on iOS Expo Go it doesn't work on iOS
This will be resolved in 14.1.3 which should be published later today

**Comment by SamJbori** [comment]
> Hi @SamJbori - Couple of things happening here. You seem to be mixing up the old and new package and also not passing an barcode settings.
> 
> > Anoth issue, CameraView from expo-camera/next keep crashing my iOS app, but works fine on Android, and on iOS Expo Go it doesn't work on iOS
> 
> This will be resolved in 14.1.3 which should be published later today

I did remove the barcode settings while I was testing but it was there and didn't work, however if the second issue is going to be resolved do you want me to go ahead and close this issue?

**Comment by SamJbori** [comment]
@alanjhughes I just finished creating the new build after updating the `expo-camera` package to `14.1.3` and it's working just fine!

I will go ahead and close the issue as I see no benefit of keeping it open!

**Comment by Carlos-VQZ** [comment]
si cierto
