### ISSUE TITLE
expo start logs "{project name}/main.js: Cannot read property '1' of undefined"

### ISSUE THREAD

**Issue by jorgefernandes** [expo/expo#2821]
### Environment

  Expo CLI 2.4.3 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.4.3

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/jorgefernandes-ece66803-af9c-4d6a-9045-82145c11be44.tar.gz

### Steps to Reproduce

I just updated my ExpoSdk to v. 31.0.0 and the build looks ok. But when i run expo start my terminal logs "{project name}/main.js: Cannot read property '1' of undefined". I haven't made any changes, just updated my SDK.

**Comment by tcdavis** [comment]
SDK 31 included an upgrade to babel 7, your issue might be related to that.  You might need to upgrade babel-preset-expo to 5.

If that doesn't work, please share a small project that reproduces the issue so we can investigate.

**Comment by shubhamdeol** [comment]
I can feel your pain

**Comment by jorgefernandes** [comment]
@tcdavis i haven't used babel-preset-expo so far, so i added to my project babel-preset-expo 5 but it doesn't worked :( 

I'll prepare a compact version of my project so you guys can investigate

**Comment by jorgefernandes** [comment]
@tcdavis where can i share my example project?

**Comment by shubhamdeol** [comment]
@jorgefernandes  babel preset is used by Expo, follow this issue raised by me, which I recently closed. 

[https://github.com/expo/expo/issues/2834](url)

or try this yarn add babel-plugin-module-resolver@latest

**Comment by tcdavis** [comment]
Thanks @shubhamdeol!
@jorgefernandes A git repo is probably easiest if that doesn't resolve it for you.

**Comment by jorgefernandes** [comment]
@shubhamdeol in my case it changed the error: main.js: Cannot read property 'filename' of undefined

i think this has to be with .babelrc or something

**Comment by jorgefernandes** [comment]
Found the solution here: https://github.com/expo/expo/issues/2576#issuecomment-435569256

**Comment by jorgefernandes** [comment]
Well, i had to follow @shubhamdeol instructions and the comment referenced above. Everything is working now. So im gonna close this issue.
