### ISSUE TITLE
WebBrowser.openAuthSessionAsync called after LocalAuthentication.authenticateAsync does not return on iOS 17.4.1

### ISSUE THREAD

**Issue by sonuchandra** [expo/expo#28221]
### Minimal reproducible example

https://snack.expo.dev/@blackline/webbrowser-openauthsessionasync

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

With the iOS 17.4.1 rollout

If LocalAuthentication.authenticateAsync() is called before WebBrowser.openAuthSessionAsync(authUrl), 
the call does not return
The browser window with the authUrl is not shown

On calling the API again (like when user retries login) an error is seen:
Calling the 'openAuthSessionAsync' function has failed
→ Caused by: Another web browser is already open

This functionality has been working fine on previous iOS versions as well as on Android

The snack
https://snack.expo.dev/@blackline/webbrowser-openauthsessionasync

Has 2 functions:
onIssue - shows the issue - LocalAuthentication.authenticateAsync() called before WebBrowser.openAuthSessionAsync(authUrl)
onPress - shows the auth working when LocalAuthentication.authenticateAsync() is not called

PLEASE run the snack on PHONE running iOS 17.4.1 to see the issue

### Environment

Used snack
Expo 49

### Expo Doctor Diagnostics

Used snack

**Comment by williamrobertson13** [comment]
This is still an issue - can we re-open this?

**Comment by williamrobertson13** [comment]
Can we re-open this? This is still an issue and breaking critical functionality in our Expo app 😢
