### ISSUE TITLE
Compatible versions for Stripe

### ISSUE THREAD

**Issue by jessk77** [expo/expo#2823]
Hello!

I got some problems with expo and stripe in ios

After I modify my Podfile to have stripe on ios I get the following:

```
[!] CocoaPods could not find compatible versions for pod "ExpoKit/CPP":
  In Podfile:
    ExpoKit/CPP (from `http://github.com/expo/expo.git`, tag `ios/2.8.4`)

None of your spec sources contain a spec satisfying the dependency: `ExpoKit/CPP (from `http://github.com/expo/expo.git`, tag `ios/2.8.4`)`.

```

My Podfile looks like:

```
platform :ios, '10.0'

target 'myapp' do
  pod 'Stripe', '~> 13.0.3'
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.8.4",
    :subspecs => [
      "Core",
      "CPP", # Add a comma here!
      "Payments" # Add this line here!
    ],
    :inhibit_warnings => true
```

Hope someone could help me :(

**Comment by tcdavis** [comment]
Hi Jess,
You might have a happier time using the Expo payments module.  Instructions for how to use it in your project are available here: https://docs.expo.io/versions/latest/sdk/payments#adding-the-payments-module-on-ios

**Comment by jessk77** [comment]
Thanks!! now I'm having this :(
<img width="375" alt="image" src="https://user-images.githubusercontent.com/29874403/49261523-3d4a5f00-f408-11e8-8cf0-dbeefb6fd052.png">
 Sorry Im beginner at react native
