### ISSUE TITLE
Expo SDK 50 - expo-camera recordAsync produces upside-down video on iOS.

### ISSUE THREAD

**Issue by gbernobic** [expo/expo#28232]
### Minimal reproducible example

https://github.com/gbernobic/expo-camera-rotated-videos

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

After upgrading to Expo SDK to 50, expo-camera package started producing upside-down videos (180deg rotated) when device is positioned in landscape mode. Issue is present only on iOS in landscape mode - tested with Expo Go & Dev builds.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~50.0.14 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
hi there! can you reproduce this with expo-camera/next? https://docs.expo.dev/versions/latest/sdk/camera-next/

**Comment by gbernobic** [comment]
> hi there! can you reproduce this with expo-camera/next? https://docs.expo.dev/versions/latest/sdk/camera-next/

Unfortunately with expo-camera/next promise returned from recordAsync is never resolved so I'm not even able to record a video (expo go - android/ios).

**Comment by alanjhughes** [comment]
@gbernobic - You can record a video but just not the way you have it implemented currently. Using long press to trigger video recording is problematic because the camera needs a gap between reconfiguring for video and starting the recording. Not allowing this causes issue like dead frames at the start of recordings. This was removed from camera/next so now you need to pass the `mode` prop to start using video. 

Aside from that, I cannot reproduce the problem using your repro. The camera records the video in the correct orientation.

**Comment by gbernobic** [comment]
@alanjhughes @brentvatne I can confirm the issue both on expo-camera & expo-camera/next (next branch). Will attach videos.

Issue can be reproduced on following device:
iOS version: 16.13.1
Model Name: iPhone 11
Model Number: MHDA3SE/A


https://github.com/expo/expo/assets/133200331/b5257ba3-92d9-40de-bcee-2baadfd7805e

https://github.com/expo/expo/assets/133200331/3d510243-a1ca-47df-a8aa-0c5e07af8d41

**Comment by alanjhughes** [comment]
Hi @gbernobic - Is your example up to date?

**Comment by gbernobic** [comment]
@alanjhughes no changes after adding the prop.

`<CameraView
            style={styles.camera}
            facing={facing}
            ref={cameraRef}
            onCameraReady={onCameraReady}
            mute={true}
            mode="video"
            onMountError={(error) => {
              console.log("camera error", error);
            }}
            responsiveOrientationWhenOrientationLocked={true}
            onResponsiveOrientationChanged={Alert.alert("Orientation changed")}
          >`

**Comment by alanjhughes** [comment]
@gbernobic expo go has missed out on a number of fixes since it's last release. There will be a new version out soon. In the meantime can you use a development build?

**Comment by gbernobic** [comment]
> @gbernobic expo go has missed out on a number of fixes since it's last release. There will be a new version out soon. In the meantime can you use a development build?

@alanjhughes I can confirm the issue with camera-expo package and the development build, for camera-expo/next I'll let you know as soon as I'm able to to test it.

**Comment by gbernobic** [comment]
@alanjhughes I can confirm that the issue is gone on development build using expo-camera/next v14.1.3.

**Comment by alanjhughes** [comment]
@gbernobic great! There will be a new version of expo go available soon that will also resolve the issue there
