### ISSUE TITLE
[Calendar] - Android calendar is returning isPrimary with wrong value

### ISSUE THREAD

**Issue by joaogabrieldasilva** [expo/expo#28268]
### Minimal reproducible example

https://github.com/joaogabrieldasilva/expo-calendar-repro

### Steps to reproduce

`yarn/npm install`

##### Expo Go
`yarn start`

##### Dev Build
`npx expo run:android`

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I was trying to save an event in the user's primary calendar in Android when I noticed "isPrimary" was returning false in every calendar, so I decided to go to the Android docs and see what was the rule behind it and I found out that if the ACCOUNT_NAME and OWNER_ACCOUNT are the same, it means the calendar is the primary.

![image](https://github.com/expo/expo/assets/73562417/6f407592-7f59-4dbd-a1cf-42e0149c97c1)

But even in the calendar that "ownerAccount" and "source.name" (which refers to ACCOUNT_NAME) were the same "isPrimary" was returning false.
When I tried to change this if condition from "1" (String) to 1 (Number) the correct "isPrimary" is returned

CalendarModule.kt
![image](https://github.com/expo/expo/assets/73562417/6d5a7830-f66c-4a2b-b3f8-f991cc84ebe6)

![image](https://github.com/expo/expo/assets/73562417/b00adb70-2069-4a1b-b149-802ced15f09e)

API 23 With IS_PRIMARY === "1"
![image](https://github.com/expo/expo/assets/73562417/c18a126a-ef3d-4632-9416-2fad99fe922c)

API 23 With IS_PRIMARY === 1
![image](https://github.com/expo/expo/assets/73562417/64631d83-0e0b-41ce-8316-7ab2cc7e997b)

So I want to know if this is really a bug or a made a mistake, if this is a bug I'll be happy to submit a PR

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.n/bin/node
      Yarn: 1.22.22 - ~/.n/bin/yarn
      npm: 10.5.0 - ~/.n/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    npmPackages:
      expo: ~50.0.14 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✖ Check native tooling versions
✖ Check Expo config (app.json/ app.config.js) schema
Unexpected error while running 'Check Expo config (app.json/ app.config.js) schema' check:
FetchError: request to https://exp.host/--/api/v2/project/configuration/schema/50.0.0 failed, reason: getaddrinfo EAI_AGAIN exp.host
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.

One or more checks failed, indicating possible issues with the project.
```

**Comment by guss189** [comment]
same problem

**Comment by joaogabrieldasilva** [comment]
> same problem (with expo sdk 51)

It's not a big issue actually, you can handle this in JavaScript side probably, I am interested in fixing this but still waiting for expo team response

**Comment by sanchaz** [comment]
@joaogabrieldasilva I think that if you have 2 google accounts added to the phone this doesn't hold true
I have both of them with accountOwner == source.name, so I have no way to know which is primary. I mean they're both primary in their respective accounts... but other than that I have no way to know which is the main account on the phone.

**Comment by sanchaz** [comment]
open pr here as I need this fixed: https://github.com/expo/expo/pull/33285

**Comment by sanchaz** [comment]
actually all of them now have isPrimary. there doesn't seem to be a way to distinguish between the main account
