### ISSUE TITLE
Issue with react native 0.70.15

### ISSUE THREAD

**Issue by atrofimenko** [expo/expo#28263]
### Summary

Faced with an issue on iOS 17+ with DateTimePickerIOS, updated react native from 0.70.5 to 0.70.15 and faced with an issue with hermes(which disabled in my project) on prod build. On Dev works OK. Can't upgrade expo to fresh and react-native, need some advice how to avoid this issue with hermes embedding. My current expo version is 47.0.12(can't upgrade minor version because it depends on react native 0.70.8, but I need a fix which was inside 0.70.12:))
![Screenshot 2024-04-17 at 20 35 38](https://github.com/expo/expo/assets/62396722/6255663e-f1c3-4291-a1cd-2c105d6f2fad)

### What platform(s) does this occur on?

iOS

### SDK Version

47.0.12

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 34.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.1 => 9.2.2 
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.15 => 0.70.15 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 5.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Minimal reproducible example

install react native 0.70.15 and expo 47.0.12 and try to build iOS app

**Comment by brentvatne** [comment]
i would try googling that hermes error string. it's possible that this issue is related to a monorepo setup, if you are using one

**Comment by atrofimenko** [comment]
@brentvatne I tried, no success. It's connected somehow with incompatibility of versions react-native and expo, but i think it might be fixed by a little patch, but no idea yet how)
