### ISSUE TITLE
App crash after sentry  implementation

### ISSUE THREAD

**Issue by techamit95ch** [expo/expo#28266]
### Minimal reproducible example

When I am retrying to archive  create .ipa  it's happening... It' happening After I followed https://docs.sentry.io/platforms/react-native/manual-setup/expo/

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

For  a bug appp crash which is happening after I publish app to test flight in iOS I had to add Sentry... https://docs.sentry.io/platforms/react-native/manual-setup/expo/
and 
https://docs.expo.dev/guides/using-sentry/

I followed exact ly this I seems in dev build everything was working...  no app crash too but After I installed sentry and followed  this steps mentioned... I could run and build app in simulator for development buut I can not archivee this

it's giving me this error

File ~/Library/Developer/Xcode/DerivedData/[MyApp-location]/Build/Intermediates.noindex/ArchiveIntermediates/[MyApp]/BuildProductsPath/Release-iphoneos/[MyApp].app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

can build it...

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - /usr/local/bin/node
      Yarn: 4.1.1 - ~/node_modules/.bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/amitchakraborty/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 23, 27, 29, 30, 31, 32, 33, 34
        Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.23 
      expo-router: ^2.0.4 => 2.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.7.0
    Expo Workflow: bare

**Comment by brentvatne** [comment]
hi there! it sounds like your bundling your app failed. check out your build logs if you used eas build for more info, otherwise try creating another build locally or wherever and inspect those logs for more information
