### ISSUE TITLE
[expo-location] requestForegroundPermissionsAsync() is never resolved on native iOS

### ISSUE THREAD

**Issue by krisgerhard** [expo/expo#28284]
### Minimal reproducible example

Reading from comments in the code this is a known problem but could not find a issue for it

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

* Reset application to no permissions granted.
* Call Location.requestForegroundPermissionsAsync()
* Grant permission (same behaviour with "Only once" or "While in use".
* Location.requestForegroundPermissionsAsync() is never resolved.
* Reload app
* Call Location.requestForegroundPermissionsAsync() 
* ☝️ resolves immediately (without displaying permissions modal) as permissions are already granted.

These issues are well documented in the code [here](https://github.com/expo/expo/blob/main/packages/expo-location/ios/EXLocation/Requesters/EXBaseLocationRequester.m#L84) and [here](https://github.com/expo/expo/blob/main/packages/expo-location/ios/EXLocation/Requesters/EXBaseLocationRequester.m#L113)

Is there are workaround or possible fix planned?

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\.yarn\bin\yarn.CMD
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.17 => 50.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by krisgerhard** [comment]
@byCedric Could you take a look please?

**Comment by DTupalov** [comment]
@krisgerhard  I’ve created a workaround:

```tsx
import * as ExpoLocation from 'expo-location';
import { Platform } from 'react-native';

const requestForegroundPermissionsForIOSAsync =
  (): Promise<ExpoLocation.LocationPermissionResponse> => {
    let wasResolved = false;

    const permissionPromise = (async () => {
      const result = await ExpoLocation.requestForegroundPermissionsAsync();
      wasResolved = true;
      return result;
    })();

    const timeoutPromise = (async () => {
      await new Promise((resolve) => setTimeout(resolve, 1000));
      if (wasResolved) {
        return permissionPromise;
      }
      return requestForegroundPermissionsForIOSAsync();
    })();

    return Promise.race([permissionPromise, timeoutPromise]);
  };

export const requestForegroundPermissionsAsync = Platform.select({
  ios: requestForegroundPermissionsForIOSAsync,
  default: ExpoLocation.requestForegroundPermissionsAsync,
});
```

**Comment by krisgerhard** [comment]
I'm using a different workaround which takes advantage of app state being updated after user returns from granting permission view on iOS.

```
  const [locationPermissionStatus, requestLocationPermission] =
    Location.useForegroundPermissions();

useEffect(() => {
    if (
      Platform.OS === 'android' ||
      (locationPermissionStatus !== null &&
        locationPermissionStatus?.status !== 'undetermined')
    ) {
      return;
    }
    const subscription = AppState.addEventListener('change', nextAppState => {
      if (nextAppState === 'active') {
        requestLocationPermission();
      }
    });

    return () => {
      subscription.remove();
    };
  }, [locationPermissionStatus, requestLocationPermission]);
```
Then if you call `requestLocationPermission` this event listener will refetch the status after app state is active.

@byCedric Can this issue be reopened?
