### ISSUE TITLE
[sdk] Implement SVGImage component that renders an SVG file/source

### ISSUE THREAD

**Issue by esamelson** [expo/expo#2828]
We'd like to add a new universal module that can take the contents of an SVG file (either a string or a required asset using `expo-asset`) and render it natively. The API should look something like this:

`<SVGImage source={{require('blah.svg')}} />`
`<SVGImage source={{ uri: 'data:image/svg+xml,%3Csvg%3EHello%2C%20World!%3C%2Fsvg%3E' }} />`

This should not use the current `react-native-svg` implementation but instead should use a standard native SVG implementation, such as [SVGKit](https://github.com/SVGKit/SVGKit) on iOS. Eventually we'd like to rewrite the current `Svg` module to just pass full SVG strings over to the native side, rather than rendering each separate SVG component as a UIView; though that isn't part of this ticket, it's good to keep in mind here.

This module should work across iOS, Android, and web platforms. It's fine to add native libraries to the iOS and Android clients to render SVGs if they are well-maintained and relatively lightweight. You can use the `expo generate universal` to create a new universal module template.

**Comment by FiberJW** [comment]
Is there any movement on this? I know that a lot of people would love a feature like this :)

**Comment by esamelson** [comment]
Not currently! Is this something you'd be interested in taking on/owning @FiberJW ?

**Comment by EvanBacon** [comment]
Implemented in `expo-image`
