### ISSUE TITLE
Expo SDK 50 - SQLite causes issues on Android

### ISSUE THREAD

**Issue by pavattt** [expo/expo#28297]
### Minimal reproducible example

https://github.com/pavattt/expo-50-android-bug

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

On Android after upgrade from Expo sdk 49 to 50, Sqlite doesn't call success or error callbacks. Also it causes SecureStore.getItemAsync not to resolve or reject promise.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.17 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by LabLamb** [comment]
I have the same problem.

**Comment by gpurbia** [comment]
having same issue for android, @pavattt are is this working at your end or found any solution ?

**Comment by LabLamb** [comment]
I changed to using `expo SQLite next` but the function calls are different.

**Comment by andrewding** [comment]
I have the same issue, currently convert all my sql to sql/next

**Comment by pavattt** [comment]
@gpurbia I'm just avoiding opening/closing the database more than once. I added something like this in my code:

```javascript

let db = null;

export default async function getDb() {
    if (null === db) {
        connection = SQLite.openDatabase('db_name.db');
    }
    return connection;
}
```

And then anywhere I need db I just call

```javascript
const db = await getDb();
```

**Comment by AlexPanich** [comment]
Executing a transactionAsync in parallel results in a hang. I use queue for patching this method
```
let db;
let transactionAsyncOriginal: (
	asyncCallback: SQLite.SQLTransactionAsyncCallback,
	readOnly?: boolean,
) => Promise<void>;

const queue = new Queue<() => Promise<void>>();
export function getDB() {
	if (!db) {
		db = SQLite.openDatabase('db_name.db');
	}
	if (Platform.OS !== 'android') {
		return db;
	}
	if (!transactionAsyncOriginal) {
		transactionAsyncOriginal = db.transactionAsync;
	}
	db.transactionAsync = (transaction, readOnly) =>
		new Promise((resolve) =>
			queue.add(async () => {
				await transactionAsyncOriginal(transaction, readOnly);
				resolve();
			}),
		);
	return db;
}
```

where simple queue 
```
export default class Queue<T extends () => Promise<void>> {
	private queue: T[] = [];
	private lock = false;

	add(task: T) {
		this.queue.push(task);
		if (!this.lock) {
			this.lock = true;
			this.run();
		}
	}

	run = async () => {
		const nextTask = this.queue.shift();
		if (nextTask) {
			await nextTask();
		}

		if (this.queue.length) {
			this.run();
		} else {
			this.lock = false;
		}
	};
}
```

**Comment by gpurbia** [comment]
@pavattt with singleton approach (initialise DB only one time), working as expected in both IOS and android.

**Comment by vaibhavzignuts** [comment]
i have same issue with expo-asset , please answer how to resolve 
A problem occurred evaluating project ':expo-asset'.
> Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-asset' of type org.gradle.api.Project.

**Comment by vaibhavzignuts** [comment]
@pavattt

**Comment by Elue-dev** [comment]
same issue here, who got it to work?

**Comment by danb4r** [comment]
Since Expo SDK 50, it is not showing the database on Android Studio App Inspector either.

**Comment by Vel1khan** [comment]
+1 I am facing this issue, tried to only initialize the DB once/use a singleton, but it didn't work. Only solution that worked was refactoring to use the new API. I am **very** disappointed.
