### ISSUE TITLE
[Unhandled promise rejection: Error: The Expo push notification service is supported only for Expo projects. Ensure you are logged in to your Expo developer account on the computer from which you are loading your project.]

### ISSUE THREAD

**Issue by auchaphon** [expo/expo#2829]
Expo version 2.4.3
Macos Mojave 10.14.1
Platform : IOS

Notifications.getExpoPushTokenAsync();

[Unhandled promise rejection: Error: The Expo push notification service is supported only for Expo projects. Ensure you are logged in to your Expo developer account on the computer from which you are loading your project.]

I tried this step not work
- rm -rf nodemodules
- yarn install

Please Help.

**Comment by ide** [comment]
It's hard to tell from your bug report what the issue is. You'll need to investigate and debug further so we can help. Be sure you are logged into your Expo account with Expo CLI when developing your project.

**Comment by auchaphon** [comment]
> It's hard to tell from your bug report what the issue is. You'll need to investigate and debug further so we can help. Be sure you are logged into your Expo account with Expo CLI when developing your project.

Thanks. I tried log out and login again in Expo Application & Expo CLI
It work Thanks
