### ISSUE TITLE
Error starting tunnel: Error: Error: failed to start tunnel

### ISSUE THREAD

**Issue by mariotacke** [expo/expo#283]
I've been happily developing all day through the Expo tunnel feature until I restarted my project. I receive a valid `exp://` link, but the device says "No experience can be found at ...". I have restarted my Expo XDE and tried starting through the `exp` CLI. I tried clearing the Expo XDE cache to no avail.

```
λ exp start --tunnel --dev
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Using project at <my project path>
[exp] Starting React Native packager...
[exp] Scanning 676 folders for symlinks in <my project path>\node_modules (17ms)
[exp] Loading dependency graph.
[exp] Running packager on port 19001.
[exp] Expo is ready.
[exp] You can scan this QR code:

<omitted>

[exp] Your URL is

exp://<my random url>.mariotacke.mobile.exp.direct:80

[exp] Logs for your project will appear below. Press Ctrl+C to exit.
[exp] Dependency graph loaded. 
```

The Expo XDE client log shows:
```
5:00:20 PM Starting React Native packager...
5:00:21 PM Scanning 676 folders for symlinks in <my project path>\node_modules (23ms)
5:00:22 PM Loading dependency graph.
5:00:22 PM Running packager on port 19001.
5:00:22 PM
5:00:26 PM Error starting tunnel: Error: Error: failed to start tunnel
5:00:26 PM Project opened! You can now use the "Share" or "Device" buttons to view your project.
5:00:34 PM Dependency graph loaded.
```

Any idea how to further debug this? It looks like the packager starts properly and the tunnel URL gets created.

I ran a `netstat` to look for any orphaned process that blocks the port, but I got nothing.

System: Windows 10
SDK: 17.0

**Comment by ide** [comment]
The tunnel software we use is ngrok (https://ngrok.com) so I'd try testing ngrok out to make sure it works on your computer before spending more time. (XDE and exp have a LAN option where your project URLs contain LAN IP addresses instead of the exp.direct tunnel URLs.)

If ngrok works I'd recommend a few things while debugging:

1. Close your project in XDE and open it again.
2. Try to load the URL in your browser on your computer (switch out `exp://` for `http://`). If that works, the development server is up and running.
3. Try to load the URL from your phone's browser to make sure your phone can reach your development server.
4. Lastly, open the URL in the Expo client.

**Comment by mariotacke** [comment]
Thanks for your help, James. I tried running ngrok and it works without issues. When I try to load the URL from the Expo client through the browser, I get `Tunnel <my random url>.mariotacke.mobile.exp.direct not found`. I just got home, so I can develop against the LAN option for now.

Could there be communication issues with `mobile.exp.direct`? I suppose this is a sort of tunneling service from Expo?

**Comment by ide** [comment]
@mariotacke Is your Expo username mariotacke.mobile? I'm wondering if it has a dot in it and if that's messing up the subdomain....

**Comment by mariotacke** [comment]
Nope, it is only `mariotacke`. I registered through the GitHub integration and am logging in with `mariotacke` + password.

**Comment by mariotacke** [comment]
I switched back and forth between `Tunnel` and `LAN` options and both stopped working now. After some time (~1m) I get this stack trace in the Expo XDE client:

```
6:45:54 PM
Error starting tunnel: Error: Error: panic: runtime error: invalid memory address or nil pointer dereference

github.com/inconshreveable/olive/recover.go:40
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
<autogenerated>:132
github.com/inconshreveable/olive/recover.go:29
runtime/asm_amd64.s:479
runtime/panic.go:458
github.com/inconshreveable/olive/error.go:37
runtime/asm_amd64.s:479
runtime/panic.go:458
runtime/panic.go:62
runtime/signal_windows.go:161
lib/tunnel/client/reconnecting.go:39
lib/tunnel/client/session.go:97
ngrok/tunnel_session.go:138
ngrok/web_api.go:95
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/error.go:41
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/recover.go:32
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/logger.go:17
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:250
github.com/go-martini/martini/router.go:120
ngrok/src/ngrok/web.go:27
runtime/asm_amd64.s:480
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
github.com/go-martini/martini/martini.go:173
github.com/go-martini/martini/martini.go:69
```

**Comment by ide** [comment]
`exp.direct` is the domain we tell ngrok to use for tunneling. The entire tunneling implementation (including the stack trace above) is ngrok. Aside from trying to restart all the things, in XDE you could try hitting `Ctrl+Shift+I` to bring up the devtools and see if there are any errors in the console.

**Comment by mariotacke** [comment]
Interesting. I wonder where the `mobile` part comes from in the domain. For whatever reason, it is working again today (the tunnel proxy). Thanks for all of your help.

Not sure if this could be related to the `exp.direct` service not liking me for a few hours... I guess we can close this issue.

**Comment by ide** [comment]
Is your project slug called "mobile"? I think that might be where it came from.

Glad to hear it is working for you now and sorry about the temporary unavailability. Will close this issue now.

**Comment by mariotacke** [comment]
No, my project slug is "manifest" (product name), my actual project folder is "mobile" (git). Who knows what happened, I'm glad it is back to normal. :)

**Comment by brunont** [comment]
I also had this problem today. It looks like sometimes ngrok can't create the tunnel. But changing the `Expo XDE Host` to `LAN` instead of `Tunnel` solved it... Tks @ide

**Comment by dangbh1002** [comment]
Expo and react-devtools conflict!!! If you are using react-devtools, you must uninstall it:
`npm uninstall react-devtools --save-dev`

**Comment by RyanPWalker** [comment]
Neither the tunneling nor LAN have been working all day, but without even changing anything tonight the tunneling suddenly works again.  Any idea why this happens?

**Comment by umar1921** [comment]
Worked for me.............
![capture](https://user-images.githubusercontent.com/32916640/31748772-eea43402-b48e-11e7-947f-196d9e430b01.PNG)

**Comment by umar1921** [comment]
This worked for me...

![capture](https://user-images.githubusercontent.com/32916640/31748856-6df7610c-b48f-11e7-8655-a054b847a240.PNG)

**Comment by gregbenner** [comment]
`npm uninstall react-devtools -g` after 6 hours of trying everything...

**Comment by BalajiTheo** [comment]
running ngrok.exe in the background, appears to be the workaround

**Comment by acomito** [comment]
wow......  I needed this so bad. Might be worth adding a warning?

**Comment by Husak93** [comment]
@gregbenner delete devtools works for me

**Comment by jojomickymack** [comment]
I believe there are multiple causes for the 'Error: failed to start tunnel' notification is shown - for me (on windows 10), I realized that the error didn't come up and tunnel url was successful when a physical android was plugged in for debugging. My attempts to deploy to 'genymotion' continued to get the 'failed to start tunnel' notification until I added the android 'platform-tools' directory to my path. It must be looking for adb and can't find it unless this is done.

Not having the 'platform-tools' added to my path is what was causing the error on my system.

**Comment by vikulkumar123** [comment]
We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN.
 any idea to solve this error.

**Comment by vikulkumar123** [comment]
"We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN."

please help me solve this error.

**Comment by brunont** [comment]
Hi @vikulkumar123, have you tried restarting the project, switching host to lan and all other tips above?

**Comment by varuntyagi001** [comment]
I was somehow able to identify the problem. You just need to do ipconfig /all (windows) or ifconfig (unix) and check for Wireless LAN adapter WIFI IPV4 Address and replace the host in exp URL with it.

exp://192.168.84.161:19000 (This published URL on expo start was using ethernet IPV4 adress instead of Wireless LanIPV4 192.168.0.10)

Changing the host and directly hitting it on safari opens a expo app and loads the react app successfully

Hope this will help everyone facing this problem.
 replaced it with

**Comment by pencilcheck** [comment]
Start getting `Tunnel URL not found, falled back to LAN URL.`, how do I solve this? Changed network, downloaded ngrok (and it worked) and not sure what to do.
