### ISSUE TITLE
I can't build my android apk, It seems that the node command cannot be found

### ISSUE THREAD

**Issue by FrankFeng1116** [expo/expo#28309]
### Minimal reproducible example

https://github.com/Portkey-Wallet/portkey-wallet

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-constants:createDebugExpoConfig'.
> A problem occurred starting process 'command 'node''

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':expo-constants:createDebugExpoConfig'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:420)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:342)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'node''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'node'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
	... 3 more
Caused by: java.io.IOException: Cannot run program "node" (in directory "/Users/fengfeiyang/aelf/portkey/portkey-wallet/packages/rn-sdk/app_android"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 7 more

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 29s

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.13 => 49.0.23
      react: ~18.2.0 => 18.2.0
      react-native: 0.72.8 => 0.72.8
    npmGlobalPackages:
      eas-cli: 7.6.2
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✖ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check for issues with metro config
✖ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  @expo/config-plugins@7.8.4
  @expo/config-plugins@7.8.4
  @expo/config-plugins@7.8.4
  @expo/config-plugins@7.8.4
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config. This can lead to unexpected and hard to debug issues. Learn more.
Advice: Update your custom metro.config.js to extend @expo/metro-config.

WARNING: The legacy expo-cli does not support Node +17. Migrate to the new local Expo CLI: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.

  error: unknown option `--check'
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by FrankFeng1116** [comment]
![image](https://github.com/expo/expo/assets/149366454/2944c711-272c-4c75-a9ac-309cff5eccbf)
if I replace this config  to my local node path, it can run well. But,  when I run `npm install`, the config will reset.

**Comment by exzos28** [comment]
Anyone looking for how to solve this problem you should change the Gradle JDK here (screenshot) or edit your environment.

Android Studio settings:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/3013bdd8-8bc0-47bc-a02a-696a891a12c5">

```
-> java --version
openjdk 17.0.10 2024-01-16 LTS
OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)
```


https://reactnative.dev/docs/set-up-your-environment?platform=android#installing-dependencies

**Comment by quan-nh-torus** [comment]
@exzos28 thanks a lot, that really helpful

**Comment by mahircatori** [comment]
@exzos28 Thanks man, appreciate it!

**Comment by delphinebugner** [comment]
Joining the others, thanks @exzos28 for pointing this!

**Comment by ildaneta** [comment]
Thanks a lot @exzos28 ✨

**Comment by msobalvarro** [comment]
> Anyone looking for how to solve this problem you should change the Gradle JDK here (screenshot) or edit your environment.
> 
> Android Studio settings: <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/39951413/375464723-3013bdd8-8bc0-47bc-a02a-696a891a12c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NTk5MTMsIm5iZiI6MTczNjQ1OTYxMywicGF0aCI6Ii8zOTk1MTQxMy8zNzU0NjQ3MjMtMzAxM2JkZDgtOGJjMC00N2JjLWEwMmEtNjk2YTg5MWExMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDIxNTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDkyYzFlZGU1ZTUzMzMyYWUyMzVjZDM2ZDA4N2MyNDQ1NzVlOWQ0MGIyODZkNGRiMjAwMWQxOTBhNDM3NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tmX8xXOGvkKePWjaVQDYAkWHGxvquNuAgttjMGIP920">
> 
> ```
> -> java --version
> openjdk 17.0.10 2024-01-16 LTS
> OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
> OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)
> ```
> 
> https://reactnative.dev/docs/set-up-your-environment?platform=android#installing-dependencies

you are the best!

**Comment by fmg-jyoti** [comment]
> Anyone looking for how to solve this problem you should change the Gradle JDK here (screenshot) or edit your environment.
> 
> Android Studio settings: <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/39951413/375464723-3013bdd8-8bc0-47bc-a02a-696a891a12c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE3NzU3OTcsIm5iZiI6MTc0MTc3NTQ5NywicGF0aCI6Ii8zOTk1MTQxMy8zNzU0NjQ3MjMtMzAxM2JkZDgtOGJjMC00N2JjLWEwMmEtNjk2YTg5MWExMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEyVDEwMzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOGIzZTJiOTdiNmVmMDBhNGVmYTkyYTZjM2ViNGE3OGY0ZWUyMTRkN2Y1ZGRhNjA1OGY0NTM1Y2Y3N2YxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QfBm6GM5APW8jKS8Wu-qaVoNM536FJdke5BwPZ1YTak">
> 
> ```
> -> java --version
> openjdk 17.0.10 2024-01-16 LTS
> OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
> OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)
> ```
> 
> https://reactnative.dev/docs/set-up-your-environment?platform=android#installing-dependencies

Thanks alot bro.. after spending 4 hours get this answer.

**Comment by serdardev2** [comment]
> Anyone looking for how to solve this problem you should change the Gradle JDK here (screenshot) or edit your environment.
> 
> Android Studio settings: <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/39951413/375464723-3013bdd8-8bc0-47bc-a02a-696a891a12c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIxNTkxNTYsIm5iZiI6MTc0MjE1ODg1NiwicGF0aCI6Ii8zOTk1MTQxMy8zNzU0NjQ3MjMtMzAxM2JkZDgtOGJjMC00N2JjLWEwMmEtNjk2YTg5MWExMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE2VDIxMDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZDE3YmYwNjMyZDY1NTI5NjNhYjMyM2FlZWQzNzc5YzA3NTQ5ODMwYzZlNWNjNWRlZThhMmEzMjUwMzRiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VGqH3On8aXiE4s8AwLr2vCzfGdoj_XWTJ0su93xRhR4">
> 
> ```
> -> java --version
> openjdk 17.0.10 2024-01-16 LTS
> OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
> OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)
> ```
> 
> https://reactnative.dev/docs/set-up-your-environment?platform=android#installing-dependencies

thx

**Comment by adam0x01** [comment]
If you tried many ways still can't work, pls reboot your macOS.

**Comment by jose920405** [comment]
I'm not sure, but I think that changing that configuration sounds incorrect. In my case, I solved it differently.

I looked for a way to let Android Studio know what Node version I'm using.

Seems like that can be solved by simply calling `open -a "Android Studio"` from your `android` folder in the terminal. At least that worked for me.

**Comment by adey69** [comment]
> I'm not sure, but I think that changing that configuration sounds incorrect. In my case, I solved it differently.
> 
> I looked for a way to let Android Studio know what Node version I'm using.
> 
> Seems like that can be solved by simply calling `open -a "Android Studio"` from your `android` folder in the terminal. At least that worked for me.

Great save, man! This worked for me as well.

**Comment by TinhHuynh** [comment]
> Anyone looking for how to solve this problem you should change the Gradle JDK here (screenshot) or edit your environment.
> 
> Android Studio settings: <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/39951413/375464723-3013bdd8-8bc0-47bc-a02a-696a891a12c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc4ODU0MTIsIm5iZiI6MTc0Nzg4NTExMiwicGF0aCI6Ii8zOTk1MTQxMy8zNzU0NjQ3MjMtMzAxM2JkZDgtOGJjMC00N2JjLWEwMmEtNjk2YTg5MWExMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTIyVDAzMzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZmI0ODRkMzMyNWM0NDE0NmY2ZGZjNTk3NDVjYmE1ODFiMDFiODdhZjkxMTYyZGQ4YzdhMGYxMDQ2Y2MwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gRALr4CsnF4-lnhMwQJ8Wx9TRteNTScsiNILO-GKfMk">
> 
> ```
> -> java --version
> openjdk 17.0.10 2024-01-16 LTS
> OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
> OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)
> ```
> 
> https://reactnative.dev/docs/set-up-your-environment?platform=android#installing-dependencies

My man <3

**Comment by pengVc** [comment]
> I'm not sure, but I think that changing that configuration sounds incorrect. In my case, I solved it differently.
> 
> I looked for a way to let Android Studio know what Node version I'm using.
> 
> Seems like that can be solved by simply calling `open -a "Android Studio"` from your `android` folder in the terminal. At least that worked for me.
> 
> Steps are
> 
> ```
> ./gradlew --stop
> nvm use 
> ```
> 
> and then run
> 
> open -a "Android Studio"
> or
> 
> open -a /Applications/Android\ Studio.app

Thx a lot, the solution saved me time. 

can't believe that, one year after this issue, I still encounter this problem in expo53.
Expo should write this into the official documentation.

**Comment by MilesLuo** [comment]
@exzos28 Thanks man, appreciate it!

**Comment by lovelytingy** [comment]
@exzos28  Thanks man, appreciate it

**Comment by babarbahadur** [comment]
@exzos28 Thank you very much!!

**Comment by alosslessdev** [comment]
> Anyone looking for how to solve this problem you should change the Gradle JDK here (screenshot) or edit your environment.
> 
> Android Studio settings: <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/39951413/375464723-3013bdd8-8bc0-47bc-a02a-696a891a12c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQwODkxNzEsIm5iZiI6MTc1NDA4ODg3MSwicGF0aCI6Ii8zOTk1MTQxMy8zNzU0NjQ3MjMtMzAxM2JkZDgtOGJjMC00N2JjLWEwMmEtNjk2YTg5MWExMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAxVDIyNTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MjE5NDBiZTA2Mzg2NzNiOTM3ZWEzZGE3MzQwZjI5MThjZjNlYzgzYTdlOWJkOWE5MTZlMWRiYTk0ZTAxMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ECalpSRM78Ze9vZDBS6Qo2pDp3UKO0xdR1KGDOkG_4g">
> 
> ```
> -> java --version
> openjdk 17.0.10 2024-01-16 LTS
> OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
> OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)
> ```
> 
> https://reactnative.dev/docs/set-up-your-environment?platform=android#installing-dependencies

I don't have this option. Does anyone know what do do? It seems this is not defined in the build.gradle file expo creates. I believe it's a permission issue so maybe you need to install node globally on your system?

**Comment by jose920405** [comment]
> > Anyone looking for how to solve this problem you should change the Gradle JDK here (screenshot) or edit your environment.
> > Android Studio settings: <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/39951413/375464723-3013bdd8-8bc0-47bc-a02a-696a891a12c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQwODkxNzEsIm5iZiI6MTc1NDA4ODg3MSwicGF0aCI6Ii8zOTk1MTQxMy8zNzU0NjQ3MjMtMzAxM2JkZDgtOGJjMC00N2JjLWEwMmEtNjk2YTg5MWExMmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAxVDIyNTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MjE5NDBiZTA2Mzg2NzNiOTM3ZWEzZGE3MzQwZjI5MThjZjNlYzgzYTdlOWJkOWE5MTZlMWRiYTk0ZTAxMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ECalpSRM78Ze9vZDBS6Qo2pDp3UKO0xdR1KGDOkG_4g">
> > ```
> > -> java --version
> > openjdk 17.0.10 2024-01-16 LTS
> > OpenJDK Runtime Environment Zulu17.48+15-CA (build 17.0.10+7-LTS)
> > OpenJDK 64-Bit Server VM Zulu17.48+15-CA (build 17.0.10+7-LTS, mixed mode, sharing)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://reactnative.dev/docs/set-up-your-environment?platform=android#installing-dependencies
> 
> I don't have this option. Does anyone know what do do? It seems this is not defined in the build.gradle file expo creates. I believe it's a permission issue so maybe you need to install node globally on your system?

Try this option I shared also in this same post

https://github.com/expo/expo/issues/28309#issuecomment-2779106717

**Comment by exzos28** [comment]
@alosslessdev you have to set up java environment or manage it using [jenv](https://github.com/jenv/jenv) or similar tools or use Android Studio to install it. However, setting up the environment through Android Studio does not guarantee that it will be available in your SHELL, and if it is available, it will not necessarily be the one you selected.
