### ISSUE TITLE
Individual ./gradlew assembleRelease do not load .env enviroment variables automatically

### ISSUE THREAD

**Issue by brianangulo** [expo/expo#28334]
### Minimal reproducible example

https://github.com/brianangulo/expo-env-gradlew-issue

### Did you reproduce this issue in a development build?

Yes

### Summary

After pre-building the android folder with `npx expo prebuild --platform android --clean` and try to manually build android by running `cd android && ./gradlew assembleRelease` it will start building but any EXPO_PUBLIC_* environment variables found within the app.config.js/.ts will be undefined compared to when being ran via `npx expo run:android` that behaves as expected.

Steps to reproduce this:

- Clone repo
- Run: `npm i`
- Run `npx expo prebuild --platform android --clean`
- Run: `cd android`
- Run: `./gradlew assembleRelease`
- Observe look for a file within your root folder named `test.txt`
- Confirm whether the file contains the value of the enviroment variable: `foobar` if defined or `did not get defined` if undefined. You may also try to run console.log inside app.config.js but that don't work too well.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /Users/bangul01/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.1 => 19.0.1 
      expo: ~49.0.23 => 49.0.23 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by brianangulo** [comment]
For anyone running into this, a workaround is to load the env at the top of app.config.* like this:

```
import { load } from "@expo/env"

// reloading env variables on every parse to prevent missing them
load(__dirname, { silent: true })
```

**Comment by byCedric** [comment]
Hi @brianangulo! Expo's dotenv support is initialized in the Expo CLI itself. If you build the app outside of Expo, it's expected that the dotenv support isn't initialized.

Your workaround seems good to me. Generally, it shouldn't be a problem if the dotenv is double-initialized. But, if you use something like this `SOME_VAR=${OTHER_VAR}` you might run into some inconsistencies.

Hope this helps!

**Comment by adrian-gierakowski** [comment]
Is there a better way to handle this?

**Comment by adrian-gierakowski** [comment]
@brianangulo  this doesn't seem to work:

```ts
// can't have stdout on config files
const { load } = require('@expo/env')
const logRef = console.log

console.log = () => {}
// reloading env variables on every parse to prevent missing them
load(__dirname, { silent: true })

console.log = logRef

module.exports = ({ config }) => {
  return config
}
```

I ran:
DEBUG=expo:env

```sh
yarn expo prebuild -p android
cd android
./gradlew assembleRelease
adb install app/build/outputs/apk/release/app-release.apk
```

but when I run the app no only process.env.NODE_ENV is set (to `"production"`) and my app crashes at startup with:

```
12-19 20:20:31.831  4612  4631 E ReactNativeJS: TypeError: Invalid URL: undefined
12-19 20:20:31.832  4612  4631 E ReactNativeJS: TypeError: Cannot read property 'ErrorBoundary' of undefined
12-19 20:20:31.832  4612  4631 E ReactNativeJS: 
12-19 20:20:31.832  4612  4631 E ReactNativeJS: This error is located at:
12-19 20:20:31.832  4612  4631 E ReactNativeJS:     in ContextNavigator
12-19 20:20:31.832  4612  4631 E ReactNativeJS:     in ExpoRoot
12-19 20:20:31.832  4612  4631 E ReactNativeJS:     in App
12-19 20:20:31.832  4612  4631 E ReactNativeJS:     in RCTView
12-19 20:20:31.832  4612  4631 E ReactNativeJS:     in Unknown
12-19 20:20:31.832  4612  4631 E ReactNativeJS:     in Unknown
12-19 20:20:31.832  4612  4631 E ReactNativeJS:     in AppContainer
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: ReactHost{0}.handleHostException(message = "TypeError: Invalid URL: undefined, stack:
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: URLImpl@1:1103258
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: setup@1:1094710
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: URL@1:1095738
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: anonymous@1:2011111
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: loadModuleImplementation@1:141519
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: guardedLoadModule@1:141049
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: metroRequire@1:140679
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: anonymous@1:1813817
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: loadModuleImplementation@1:141519
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: guardedLoadModule@1:141049
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: metroRequire@1:140679
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: anonymous@1:1793327
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: loadModuleImplementation@1:141519
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: guardedLoadModule@1:141049
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: metroRequire@1:140679
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: anonymous@1:1792840
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: loadModuleImplementation@1:141519
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: guardedLoadModule@1:141049
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: metroRequire@1:140679
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: anonymous@1:4941379
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: loadModuleImplementation@1:141519
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: guardedLoadModule@1:141006
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: metroRequire@1:140679
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: get@1:1272419
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: metroContext@1:1272097
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: loadRoute@1:1731806
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: getLayoutNode@1:1733891
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: _loop@1:1731702
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: getDirectoryTree@1:1730818
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: getRoutes@1:1730527
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: getRoutes@1:1729752
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: initialize@1:1697318
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: anonymous@1:1695897
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: useMemo@1:412169
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: anonymous@1:274541
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: useInitializeExpoRouter@1:1695816
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: ContextNavigator@1:1751009
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: renderWithHooks@1:368104
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: beginWork@1:385556
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: performUnitOfWork@1:403041
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: workLoopSync@1:402171
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: renderRootSync@1:402003
12-19 20:20:31.832  4612  4632 W unknown:BridgelessReact: performConcurrentWorkOnRoot@1:399626
```

**Comment by adrian-gierakowski** [comment]
btw. when I run `DEBUG=expo:env ./gradlew assembleRelease` I can see env being loaded, even without the above `app.config.js`

**Comment by adrian-gierakowski** [comment]
hmm, having the same problem when running `yarn expo run:android  --variant release`

I do see the following in the terminal:

```
env: load .env.local .env.production .env
env: export EXPO_PUBLIC_MY_ENV_VAR ...
```

however none of the env vars are loaded at runtime 

expo cli also outputs:
```
Writing bundle output to: /tmp/spgoy6hmddn/index.js
```

but the env var values do not seem to be bundled in it

what am I missing?

**Comment by adrian-gierakowski** [comment]
seems like I'm having the same issue as reported [here](https://github.com/expo/eas-cli/issues/2195#issuecomment-2159861228)
