### ISSUE TITLE
XMLHttpRequest will randomly throw network error in TestFlight Production Environment

### ISSUE THREAD

**Issue by ChristopherGabba** [expo/expo#28349]
### Minimal reproducible example

TBD. Occurring in Production Environment

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Months ago, I submitted a bug request with the `amplify-js` team with AWS over a very frustrating bug that has been occurring periodically in our production app. Essentially when a user is on a relatively poor network connection (10ish MB/s upload speed or slower), the `XMLHttpRequest` will throw a `Network Error` and fail the upload to S3. After a few months of tracing, the issue is stemming directly from the XMLHttpRequest object, and not from Amplify itself. 

Here is a reference to the issue: https://github.com/aws-amplify/amplify-js/issues/12912

You will find the entire error trace system within this github thread and ultimately determining where it's stemming from towards the end. Because it's occurring in production environment, I have not been able to make a perfectly reproducible example. 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - /opt/homebrew/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.1 => 0.17.6 
      expo: ~50.0.14 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.8.2
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

Complete.

**Comment by brentvatne** [comment]
hi there! if you believe you have found a bug in the `XMLHttpRequest` implementation in react-native, the best place to report it is here: https://github.com/facebook/react-native/issues
