### ISSUE TITLE
[expo-firebase-notifications][Android] Headless notifications are not working

### ISSUE THREAD

**Issue by x86kernel** [expo/expo#2835]
below code not trigger even when received notification

```
this.notificationListener = firebase
  .notifications()
  .onNotification((notification) => {
    console.log('not working')
    // NOT WORKING....
})
```
i also tried .onMessage in messaging but it doesn't work.
is there any problem in this package?

expo-firebase-notifications: 1.0.0
react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz
expo: 31.0.5

@EvanBacon  Take a look at this!

**Comment by EvanBacon** [comment]
is this using `expo-firebase-notifications:1.0.0-rc.5`?

**Comment by EvanBacon** [comment]
Related: https://github.com/EvanBacon/expo-native-firebase/issues/11
