### ISSUE TITLE
Unmatched route issue in ios/android build but doesn't show in expo go app. 

### ISSUE THREAD

**Issue by MohammadHarisZia** [expo/expo#28367]
### Minimal reproducible example

It is a private repo

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

<img width="393" alt="Screenshot 2024-04-22 at 6 49 35 PM" src="https://github.com/expo/expo/assets/63912301/08d2c931-92e1-4e02-9dc1-8424b463216a">
<img width="416" alt="Screenshot 2024-04-22 at 6 50 12 PM" src="https://github.com/expo/expo/assets/63912301/209a0093-835d-439e-876a-650c14cefa11">
<img width="416" alt="Screenshot 2024-04-22 at 6 50 12 PM" 
 src="https://github.com/expo/expo/assets/63912301/36b1318d-ef1b-40a0-8237-25654155fd8c">
 
 
 FYI: I am using unstable settings in my root layout

`export const unstable_settings = {
  initialRouteName: '(main)',
};`

![image](https://github.com/expo/expo/assets/63912301/18c141e7-3a07-4697-bdcf-a18c355d7e6a)

### Environment

NA

**Comment by marklawlor** [comment]
I understand its a private repo, but we don't need your entire code base to reproduce an issue. If you can isolate the issue or reproduce it in a minimal repo that will assist with troubleshooting.

Troubleshooting a code issue, without being able to run the code, is very difficult.
