### ISSUE TITLE
[Android][Expo Go] Image request headers seem not to be set

### ISSUE THREAD

**Issue by sanak** [expo/expo#28362]
### Minimal reproducible example

https://snack.expo.dev/@nagase/expo-go-android-image-request-header

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

In Android Expo Go, image request header like the following seems not to be set.
```js
import { Base64 } from 'js-base64';
:
      <Image style={styles.logo} source={{
        uri: 'https://sanak.sakura.ne.jp/expo-example/snack-icon.png',
        method: 'GET',
        headers: {
          Authorization: `Basic ${Base64.btoa('expo-example:expo-example')}`
        }
      }} />
```
In iPhone Expo Go and production builds are no problem.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.asdf/installs/nodejs/18.18.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.18.0/bin/yarn
      npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

**Comment by sanak** [comment]
Hi,
The issue still persists, so I hope that this issue will be solved.
If someone know how to debug Expo Go itself in Android device, please let me know about it. :bow:

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Your example uses `import { Text, View, StyleSheet, Image } from 'react-native';`

In other words, it's using Image from react native core, and you need to report the issue there.

Instead, I recommend you take a look at the `expo-image` component: https://docs.expo.dev/versions/latest/sdk/image/
Thank you 🙂
