### ISSUE TITLE
API routes with a "." prefix are not able to be exported

### ISSUE THREAD

**Issue by k2on** [expo/expo#28364]
### Minimal reproducible example

https://github.com/k2on/expo-route-dot-prefix

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I am trying to add feature flag support, and you need an API route at `.well-known/vercel/flags`. However, because `.well-known` gets ignored. Is there anyway to tell metro to include it.
 
https://vercel.com/docs/workflow-collaboration/feature-flags/vercel-flags

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.6.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.17 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.4.0
    Expo Workflow: managed

**Comment by byCedric** [comment]
Hi @k2on! Thanks for the issue report. Interestingly, it seems only to be ignored for API Routes, normal routes are picked up as expected.

**Comment by byCedric** [comment]
@k2on I just opened a PR that should fix this 😄
