### ISSUE TITLE
Automatic Signing Forced on iOS

### ISSUE THREAD

**Issue by dawidvdh** [expo/expo#28363]
### Summary

When setting the code sign style to manual and providing provisioning profiles in Xcode it will always be reset to automatic signing when running expo.

I have reviewed the docs and even gone as far as building a config plugin to force the xcode project to be set to manual signing with certain provisioning profiles:

```ts
import {ConfigPlugin, IOSConfig, withXcodeProject} from '@expo/config-plugins'

const withManualSigning: ConfigPlugin = config => {
  return withXcodeProject(config, async config => {
    const project = config.modResults
    const targets = IOSConfig.Target.findSignableTargets(project)

    targets.forEach(([nativeTargetId, nativeTarget]) => {
      IOSConfig.XcodeUtils.getBuildConfigurationsForListId(
        project,
        nativeTarget.buildConfigurationList
      ).forEach(config => {
        const [, item] = config
        item.buildSettings.CODE_SIGN_STYLE = 'Manual'
        item.buildSettings.DEVELOPMENT_TEAM = '""'
        item.buildSettings.PROVISIONING_PROFILE_SPECIFIER =
          '"match Development com.app.sample"'
      })

      Object.entries(IOSConfig.XcodeUtils.getProjectSection(project))
        .filter(IOSConfig.XcodeUtils.isNotComment)
        .forEach(([, item]) => {
          if (!item.attributes.TargetAttributes[nativeTargetId]) {
            item.attributes.TargetAttributes[nativeTargetId] = {}
          }
          item.attributes.TargetAttributes[nativeTargetId].ProvisioningStyle =
            'Manual'
          item.attributes.TargetAttributes[nativeTargetId].DevelopmentTeam =
            '""'
        })
    })

    return config
  })
}

export default withManualSigning
```

However without fail whenever I run `expo run ios` it will always set the signing back to Automatic, which I believe is a symptom of the [setAutoCodeSigningInfoForPbxproj method](https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/run/ios/codeSigning/xcodeCodeSigning.ts#L109) that appears to be [called whenever all the targets have a team](https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/run/ios/codeSigning/configureCodeSigning.ts#L25).

Can this be overridden in anyway? we have recently started migrating to expo and this is a bit of a blocker for us to continue with our migration and I would love to know if there is something I am missing to avoid this.

### What platform(s) does this occur on?

iOS

### SDK Version

50.0.17

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - ~/.cache/fnm_multishells/98231_1713774848055/bin/node
      Yarn: 3.6.3 - ~/.cache/fnm_multishells/98231_1713774848055/bin/yarn
      npm: 10.1.0 - ~/.cache/fnm_multishells/98231_1713774848055/bin/npm
      Watchman: 2024.03.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/dawid/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.17 => 50.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    Expo Workflow: bare

### Minimal reproducible example

I am happy to supply a minimal reproducible example if thats required but I think the problem is relatively evident in the code and the previous explanation.

**Comment by dawidvdh** [comment]
The Answer here was seemingly setting the team id, even though the CLI will report `Auto signing app using team(s):  XXXXX` it will actually still be set to manual, it would be great if this could just be configured through the app config.

**Comment by iketw** [comment]
@dawidvdh where did you set the team id to get this working? I'm facing the same issue where building the app from the CLI switches signing to automatic

**Comment by dawidvdh** [comment]
Hey @iketw I actually created a expo plugin to ensure the team Id is always set for xcode, you can however do this manually in xcode, just uncheck the automated signing and ensure the profiles are set and the team id, then consequent prebuilds should keep your preferences however if you do a clean prebuild it will overwrite it and you will have to set it again.

I will likely open source the plugin I made although its really simple this should likely be fixed by the expo team in the shape of a config flag.

**Comment by DanielDanaee** [comment]
@dawidvdh Unsetting the automatically manage signing in Xcode will be turned off again when I run `expo run:ios --device 'MY-DEVICE'`. Could you please explain more in detail how your plugin fixes the issue?

**Comment by skyplor** [comment]
> @dawidvdh where did you set the team id to get this working? I'm facing the same issue where building the app from the CLI switches signing to automatic

@iketw you can do this by following the steps below:

1.  Go into Xcode
2. Select the **first** target
3. Choose `Build Settings`
4. Under `Signing`, search for `Development Team`
5. Set your team and make sure it is set for all the sub fields e.g Debug, Release, etc.
6. Repeat steps 3 - 5 for all other **Targets** you have in your project
