### ISSUE TITLE
androidNavigationBar not working after create build APK

### ISSUE THREAD

**Issue by DavidFilipeG** [expo/expo#28394]
### Summary

I want to create an app where the user cannot exit through the andriod navigation bar, I am adding the androidNavigationBar to the app.json file and saying that visible = 'immersive'. When I'm developing using npx expo start I get what I want but when I create an apk the navigation bar is always visible

### What platform(s) does this occur on?

Android

### SDK Version

50.0.17

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^50.0.17 => 50.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
    Expo Workflow: bare

### Minimal reproducible example

![image](https://github.com/expo/expo/assets/100479324/39164aa5-48b3-4e92-aa1d-161f84815b3a)

supposedly the android navigation bar shouldn't be showing

**Comment by alanjhughes** [comment]
Hi @DavidFilipeG - The android navigation bar cannot be completely hidden and you cannot stop the user from using it to leave the app. The `immersive` setting will hide the bar but when when the user interacts with the screen, it will return. It's intended use it if you have some content like a video where you want to remove everything from the screen but that element. It is not a way to prevent the user from using the nav bar.
