### ISSUE TITLE
Error encountered while fetching Expo token: TypeError: Cannot read property 'prototype' of undefined.

### ISSUE THREAD

**Issue by YassineOujaa77** [expo/expo#28401]
### Minimal reproducible example

token = (await Notifications.getExpoPushTokenAsync({ projectId: Constants.expoConfig?.extra?.eas.projectId })).data;

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm expecting to get expoToken from 
` token = (await Notifications.getExpoPushTokenAsync({ projectId: Constants.expoConfig?.extra?.eas.projectId })).data; `

but instead I get this error : Error encountered while fetching Expo token: TypeError: Cannot read property 'prototype' of undefined.

### Environment

`expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /usr/local/bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2023.08.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/mac/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 30, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.15 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.5.0
      expo-cli: 6.3.7
    Expo Workflow: managed`

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by pdandradeb** [comment]
Exact same thing here. Same code does work on SDK 49 but it's failing on SDK 50.

**Comment by pdandradeb** [comment]
hey @YassineOujaa77, I found what was happening here. do you have a `metro.config.js` at your project's root? try deleting it and building again. it worked for me.

**Comment by YassineOujaa77** [comment]
> hey @YassineOujaa77, I found what was happening here. do you have a `metro.config.js` at your project's root? try deleting it and building again. it worked for me.

I downgraded to Expo 48 because of deadline emergency , I will upgrade again and test this solution , I think the problem is with the fetch API because all of the libraries which are using this API is not working e.g : react-native-svg (when using svgUri) .

Thanks for your time !

**Comment by Polad10** [comment]
@pdandradeb Man, I spent weeks on this!! Thank you!
