### ISSUE TITLE
Error: The method or property expo-crypto.getRandomBytes is not available on android, are you sure you've linked all the native dependencies properly?

### ISSUE THREAD

**Issue by junaidsarwarred** [expo/expo#28432]
### Minimal reproducible example

Use expo-auth-session AuthSession.makeRedirectUri

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I have upgraded my react native project to expo 50 and after fixing all of the issues I am stuck on this issue which appears on the emulator after app building and bundling. After some investigation I found expo-crypto is a peer-dependency of expo-auth-session and I have used expo-auth-session in my project.

### Environment

npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.1 => 0.17.7 
      expo: ~50.0.17 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 7.6.1
    Expo Workflow: bare

### Expo Doctor Diagnostics

 npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by jacobo-jaramillo** [comment]
I'm having this exact same issue expo-random.getRandomBytes is not available on android and it's happening on the screen where I'm using expo-auth-session
