### ISSUE TITLE
can't copy object  JS Debugger (DevTools)  on SDK 50

### ISSUE THREAD

**Issue by boblitex** [expo/expo#28446]
### Minimal reproducible example

https://github.com/boblitex/CiaoChow

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

PS: PLEASE IGNORE THE MINIMAL REPRODUCIBLE LINk, IT'S A RANDOM REPO, AS I DON'T NEED ONE FOR THIS ISSUE

when I open the DevTools and log Objects, there's a neat little 'copy object' on right click that makes debugging a breeze 
and used to work well on older SDKs (49) but only copies the first object curly braces now and calls it a day.

<img width="671" alt="image" src="https://github.com/expo/expo/assets/39277975/a4d72b44-4de7-4a5f-bb82-3d96cd051aee">

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
      Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /var/folders/ng/hbd0mdbd7b12jqs2pcgcry3r0000gn/T/frum_72693_1713872443406/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 31, 32, 33, 33, 34
        Build Tools: 30.0.3, 31.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.17 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 7.8.2
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
repro'd this with the following in sdk 50:

```
import { StatusBar } from 'expo-status-bar';
import { Button, StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Button title="Click me" onPress={() => console.log({ my: 'object', example: 'value ' })} />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

<img width="730" alt="image" src="https://github.com/expo/expo/assets/90494/afee188a-74bc-44e6-a1db-7ea94848a5bb">

i also repro'd on sdk 51

**Comment by byCedric** [comment]
This is an issue upstream in React Native, see https://github.com/facebook/react-native/issues/43258. (cc @brentvatne)

**Comment by brentvatne** [comment]
thanks for the heads up @byCedric!

**Comment by brentvatne** [comment]
this is resolved in sdk 51 (currently in beta, to be released soon)
