### ISSUE TITLE
New expo and react native project events do not work

### ISSUE THREAD

**Issue by BosatzuKannon** [expo/expo#28464]
### Minimal reproducible example

https://github.com/BosatzuKannon/prueba

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I have created a new react native expo project with the command "npx create-expo-app appTest".

With node version 18.20.2 on Windows 10.

Just modify the new project's app.js to test the onpress event as follows:

```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';

export default function App() {

  const prueba = () => {
    console.log(`mierda`)
  }

  return (
    <TouchableOpacity style={styles.container} onPress={prueba}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

The package.js is like this:

```
{
  "name": "appblomifinal",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~50.0.14",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

```

When I run the project with npx expo start and read the QR with expo go(2.30.11) on my physical android device samsung galaxy s20fe and on xiaomi phones, I press several times on the text and it shows me the log, only for 2 seconds and then it stops working. Nothing appears in the console, no error or warning, but it doesn't work.

I don't understand how a new expo project just doesn't work.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~50.0.14 => 50.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    Expo Workflow: managed

### Expo Doctor Diagnostics

Running 12 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
it sounds like this could be an issue with your network. it may be the logging that stops working. you can try running it in an emulator to isolate the issue. replace `console.log('...')` with `alert('hi')` to see the event work as expected
