### ISSUE TITLE
build error (in target 'EXUpdates' from project 'Pods')

### ISSUE THREAD

**Issue by sevketaydogdu** [expo/expo#28479]
### Summary

PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/Politicca-fprhmrwkmnczyzabqmmsirgtncml/Build/Intermediates.noindex/ArchiveIntermediates/Politicca/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00034F70.sh (in target 'EXUpdates' from project 'Pods')

### What platform(s) does this occur on?

iOS

### SDK Version

49

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      expo: ^49.0.6 => 49.0.23 
      expo-router: ^2.0.14 => 2.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
    npmGlobalPackages:
      eas-cli: 7.8.4
    Expo Workflow: bare

### Minimal reproducible example

i dont have reproducible example

**Comment by mrevanzak** [comment]
same issue
