### ISSUE TITLE
[SDK 51 beta] Build failing when not using Expo CLI integration in bare app

### ISSUE THREAD

**Issue by NadeemKhanFh** [expo/expo#28489]
### Minimal reproducible example

https://github.com/Nadimkhan120/expo-update

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

<img width="1225" alt="Screenshot 2024-04-27 at 2 22 07 AM" src="https://github.com/expo/expo/assets/124039561/ccce2698-904e-4108-b5a3-2402e6ebb85c">

 After installing expo-update i am not able to run the project  on android. i also was trying to make a release build using eas, but it failed, i am using project made with npx react native init

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.0.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 7.8.5
      expo-cli: 6.3.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

 "dependencies": {
    "expo": ">=51.0.0-0 <52.0.0",
    "expo-updates": "~0.25.5",
    "react": "18.2.0",
    "react-native": "0.74.0"
  },

**Comment by brentvatne** [comment]
i couldn't reproduce this. i created a proejct with `npx react-native init` and then ran `npx install-expo-modules@next` to get sdk 51 beta set up, and after that i ran `eas update:configure` and ran both debug and release builds successfully. https://github.com/brentvatne/nadeem

**Comment by NadeemKhanFh** [comment]
@brentvatne  issue was with metro.config

**Comment by NadeemKhanFh** [comment]
@brentvatne  
 When i make an apk using eas  it crashes 
 https://expo.dev/artifacts/eas/geRmR3mTaC2q4wnPGgx9Ug.apk

its saying routes found, may its issue from expo-router, but i am not using expo-router

**Comment by brentvatne** [comment]
@NadeemKhanFh - try using expo-router 3.5.3 - we had to roll back from 3.5.4 because of a regression: https://github.com/expo/expo/commit/f460768310d45aaf333ae6884da56af24d34fb32

**Comment by NadeemKhanFh** [comment]
@brentvatne i am not using expo-router, i am using react native cli bare workflow

**Comment by NadeemKhanFh** [comment]
when i use expo-cli, issue is not happening, it just appears when using react native cli

**Comment by brentvatne** [comment]
ah i see. did you skip the expo cli integration with `install-expo-modules`?

**Comment by brentvatne** [comment]
btw, there is not really a "react native cli" - there is a "react native community cli" that will soon be removed from the react-native package: https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0759-react-native-frameworks.md. i always recommend using expo cli instead, learn more here: https://docs.expo.dev/bare/using-expo-cli/

that said, as long as this is an optional part of using expo modules, we should support using any cli here so i'm still curious about your answer to my previous question

**Comment by NadeemKhanFh** [comment]
> ah i see. did you skip the expo cli integration with `install-expo-modules`?

yes, when i skip this, the issue occurs when i make release build using eas. if i dont skip, then its working fine.
