### ISSUE TITLE
[docs] @example tags are not rendered correctly

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#28480]
### Summary

I noticed that the "@example" tags in the TS files are not rendered correctly anymore. They are missing in the rendered documentation. 

<img width="989" alt="Bildschirmfoto 2024-04-26 um 14 47 22" src="https://github.com/expo/expo/assets/3411292/5159eb00-7a8e-4cfb-90ac-ed2788e52a73">
 
<img width="1048" alt="Bildschirmfoto 2024-04-26 um 14 48 00" src="https://github.com/expo/expo/assets/3411292/17c6d8f4-22d4-4d2c-9dbd-c25236d15980">

This occurs on multiple cases in the documentation (not only expo-av but also e.g. [expo-contacts](https://docs.expo.dev/versions/latest/sdk/contacts/#phonenumber)). So it seems to be an issue with the underlying "documentation rendering engine"

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/audio/#recordingoptionsandroid

**Comment by amandeepmittal** [comment]
Hi @RRaideRR, we did fix them in #27498 (for expo-av, expo-contacts, expo-screen-capture, etc.). The fixed examples are in SDK 51. For example, for [`sampleRate`](https://docs.expo.dev/versions/v51.0.0/sdk/audio/#:~:text=all%20valid%20values.-,sampleRate,-(optional)) in expo-av. They weren't backported to SDK 50.
