### ISSUE TITLE
i get this massive error when i try to install expo, npm installs successfully 

### ISSUE THREAD

**Issue by Chawki726** [expo/expo#2848]
> C:\Users\Chawki>npm install expo-cli --global

`npm ERR! path C:\Users\Chawki\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinUsbApi.dll
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Chawki\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinUsbApi.dll'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\Chawki\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinUsbApi.dll']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\Chawki\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinUsbApi.dll'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\Chawki\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinUsbApi.dll' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\Chawki\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinUsbApi.dll\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\Chawki\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinUsbApi.dll',
npm ERR!   parent: 'expo-cli' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chawki\AppData\Roaming\npm-cache\_logs\2018-11-29T05_34_05_913Z-debug.log`

**Comment by Chawki726** [comment]
restarting the pc fix this

**Comment by sjchmiela** [comment]
Glad to hear that! 😊

**Comment by JanAmbrozic** [comment]
I have to thank @Chawki726, I had the same error and restarting PC does indeed solve the problem immediately. I've tried bunch of other things before restarting and nothing else worked (trying to run the command as admin, deleting the files manually, etc...)

**Comment by clabough** [comment]
The problem may have to do with file locking. Restarting cleared the file lock. I was getting this error, then did an `iisreset` on my machine and the error message went away.

**Comment by josuper** [comment]
someone solved ? how ? @clabough

**Comment by Chawki726** [comment]
> someone solved ? how ? @clabough

try restarting your pc

**Comment by paulsoniat** [comment]
Restarting didn't work for me

**Comment by zaytrix** [comment]
If you don't want to restart, kill the process adb.exe

**Comment by Tehsurfer** [comment]
`npm login` fixed this error for me. Albeit at the expense of making me feel a bit silly.

**Comment by Onyimatics** [comment]
> npm login

This worked for me straight up....thank you!

**Comment by KLD** [comment]
I had pending windows 10 updates. The restart fix did it for me too.

**Comment by courageDeveloper** [comment]
> `npm login` fixed this error for me, albeit at the expense of making me feel a bit silly.

This worked for me as well. Thanks a lot.

**Comment by MarcosRugerio** [comment]
> `npm login` fixed this error for me, albeit at the expense of making me feel a bit silly.

👍 .... Works for me....but Why?

**Comment by krishnaUIDev** [comment]
Restart PC it works fine. I got the same issue

**Comment by johnjamesmarsh** [comment]
npm login worked for me too. I had just restarted and adb.exe wasn't running (or at least didn't show up in task manager)

**Comment by Manish-Basnet** [comment]
what is npm  login??

**Comment by Tehsurfer** [comment]
> what is npm login??

If you have an npm account you can log in via the CLI to publish and update your npm packages.

**Comment by Shincham** [comment]
I already tried almost all solutions in internet and nothing worked. Someone have more tips on this error ?

I'm using windows 10 64-bit.

Already tried restarting, clean cache, change properties of the folder, downgrading version, npm login and another things ... I think I already tried everything... someone knows what's this error ?

**Comment by gradientz** [comment]
> 
> 
> I already tried almost all solutions in internet and nothing worked. Someone have more tips on this error ?
> 
> I'm using windows 10 64-bit.
> 
> Already tried restarting, clean cache, change properties of the folder, downgrading version, npm login and another things ... I think I already tried everything... someone knows what's this error ?

same here when i try to install any package globally in my windows 7 32bits setup.

In case i forget something:

>turn off firewall (i don't use antivirus since 2010 or so)
>change properties of the folder
>deleting npm and npm cache folder
>run cmd.exe as administrator
>npm cache clean -f
>npm login
>npm i -g _package_

No matter what, i get this massive error prompt with the silly "the operation was rejected by your operating system." message.

switch between nodejs/npm versions doesn't change anything (i tried with 10 different versions). I also thought it was something related with my windows so i installed ubuntu and surprise, i had the exact same error prompt.

The cool thing is that apparently on unix based system you can bypass this issue executing your command's as superuser (i have tried on ubuntu, openbsd, and arch so far). I think windows have a similar command named runas but i barely use those and can't get it work.

**Comment by Shincham** [comment]
> > I already tried almost all solutions in internet and nothing worked. Someone have more tips on this error ?
> > I'm using windows 10 64-bit.
> > Already tried restarting, clean cache, change properties of the folder, downgrading version, npm login and another things ... I think I already tried everything... someone knows what's this error ?
> 
> same here when i try to install any package globally in my windows 7 32bits setup.
> 
> In case i forget something:
> 
> > turn off firewall (i don't use antivirus since 2010 or so)
> > change properties of the folder
> > deleting npm and npm cache folder
> > run cmd.exe as administrator
> > npm cache clean -f
> > npm login
> > npm i -g _package_
> 
> No matter what, i get this massive error prompt with the silly "the operation was rejected by your operating system." message.
> 
> switch between nodejs/npm versions doesn't change anything (i tried with 10 different versions). I also thought it was something related with my windows so i installed ubuntu and surprise, i had the exact same error prompt.
> 
> The cool thing is that apparently on unix based system you can bypass this issue executing your command's as superuser (i have tried on ubuntu, openbsd, and arch so far). I think windows have a similar command named runas but i barely use those and can't get it work.

To solve the problem, I had to migrate to WSL (solved this one but got other errors related to network), and finally I made dual boot on my pc and started to use Ubuntu 18.04 LTS. I didn't have the error anymore. Couldn't solve the problem on windows 10 though.

**Comment by gradientz** [comment]
> 
> 
> > > I already tried almost all solutions in internet and nothing worked. Someone have more tips on this error ?
> > > I'm using windows 10 64-bit.
> > > Already tried restarting, clean cache, change properties of the folder, downgrading version, npm login and another things ... I think I already tried everything... someone knows what's this error ?
> > 
> > 
> > same here when i try to install any package globally in my windows 7 32bits setup.
> > In case i forget something:
> > > turn off firewall (i don't use antivirus since 2010 or so)
> > > change properties of the folder
> > > deleting npm and npm cache folder
> > > run cmd.exe as administrator
> > > npm cache clean -f
> > > npm login
> > > npm i -g _package_
> > 
> > 
> > No matter what, i get this massive error prompt with the silly "the operation was rejected by your operating system." message.
> > switch between nodejs/npm versions doesn't change anything (i tried with 10 different versions). I also thought it was something related with my windows so i installed ubuntu and surprise, i had the exact same error prompt.
> > The cool thing is that apparently on unix based system you can bypass this issue executing your command's as superuser (i have tried on ubuntu, openbsd, and arch so far). I think windows have a similar command named runas but i barely use those and can't get it work.
> 
> To solve the problem, I had to migrate to WSL (solved this one but got other errors related to network), and finally I made dual boot on my pc and started to use Ubuntu 18.04 LTS. I didn't have the error anymore. Couldn't solve the problem on windows 10 though.

im gonna stick with my ubuntu as well, but if you  want to keep your windows workflow take a look to yarn, worked for me.

**Comment by gradientz** [comment]
> 
> 
> > > I already tried almost all solutions in internet and nothing worked. Someone have more tips on this error ?
> > > I'm using windows 10 64-bit.
> > > Already tried restarting, clean cache, change properties of the folder, downgrading version, npm login and another things ... I think I already tried everything... someone knows what's this error ?
> > 
> > 
> > same here when i try to install any package globally in my windows 7 32bits setup.
> > In case i forget something:
> > > turn off firewall (i don't use antivirus since 2010 or so)
> > > change properties of the folder
> > > deleting npm and npm cache folder
> > > run cmd.exe as administrator
> > > npm cache clean -f
> > > npm login
> > > npm i -g _package_
> > 
> > 
> > No matter what, i get this massive error prompt with the silly "the operation was rejected by your operating system." message.
> > switch between nodejs/npm versions doesn't change anything (i tried with 10 different versions). I also thought it was something related with my windows so i installed ubuntu and surprise, i had the exact same error prompt.
> > The cool thing is that apparently on unix based system you can bypass this issue executing your command's as superuser (i have tried on ubuntu, openbsd, and arch so far). I think windows have a similar command named runas but i barely use those and can't get it work.
> 
> To solve the problem, I had to migrate to WSL (solved this one but got other errors related to network), and finally I made dual boot on my pc and started to use Ubuntu 18.04 LTS. I didn't have the error anymore. Couldn't solve the problem on windows 10 though.

im gonna stick with my ubuntu as well, but if you  want to keep your windows workflow take a look to yarn, worked for me.

**Comment by Meenachinmay** [comment]
just reinstall the node js with lower version. i downgraded from version 12 to 8.
but i think 10 should also work.

it works.

**Comment by bigal2331** [comment]
Seems to be an NPM issue. The following worked for me:
1. npm cache clean --force
2. npm install -g npm@latest --force
3. npm cache clean --force

If you get a 'Metro Bundler process exited with code 1' afterwards, change file \node_modules\metro-config\src\defaults\blacklist.js to:

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

**Comment by Muhammad-Sarfaraz** [comment]
From this morning I have tried all the solution available on the internet.None of them worked for me
Npm cache clean/New installation/Restart/install the new version/old version/Npm login etc.
After trying numerous time with all the possible solution,I read the errors carefully to find out what is really going on.I find out ("If you believe this might be a permissions issue") that I should use run as administrator.

If you are fetching this problem Try to run 

->run cmd.exe as administrator
->then Run npm command
In my case :
->run cmd.exe as administrator
->npm install -g json-sever
And its worked for.I hope It will also work for you.

**Comment by saille** [comment]
Run As Administrator on cmd.exe (or git bash) worked for me. After npm i succeeded as Administrator, I was able to return to non-Admin user and npm i worked again from there.

**Comment by MarioAzulay** [comment]
Restarting the pc helped 😂😂😂

**Comment by Rafay3198** [comment]
go to task manager 
find adb and click end task
then install expo
Happy coding :)

**Comment by peppyday** [comment]
> > npm login
> 
> This worked for me straight up....thank you!

Yes it worked for me too.. Thanks

**Comment by skritichauhan** [comment]
go to npm, make an account. And then use command: npm login before npm install. It worked finally!!

**Comment by YuvrajRaghuvanshi1** [comment]
restarting worked for me too ,thanks!

**Comment by kharbouch1** [comment]
restarting worked for me ,thanks

**Comment by janukeesh** [comment]
Try to install in directory other that C . It worked for me .None of above methods worked.

**Comment by Ashok1602** [comment]
Thanks restarting pc worked for me

**Comment by rameshd100** [comment]
You can either restart the pc or try killing the adb.exe process.

**Comment by Sashuv** [comment]
npm login worked !!! YAY

**Comment by asgaraliyev** [comment]
npm login worked !!! YAY

**Comment by Manish-Basnet** [comment]
How I m here , from where did u got my email?

**Comment by brentvatne** [comment]
@Manish-Basnet:

![Screen Shot 2020-10-24 at 5 59 49 PM](https://user-images.githubusercontent.com/90494/97096535-b79ab280-1622-11eb-874f-859d35c0d12f.png)

https://github.com/expo/expo/issues/2848#issuecomment-525558709

**Comment by sgaurang82** [comment]
I got it resolved by deleting .npmrc file from the Users folder

**Comment by kajoban** [comment]
Restarting your PC still fixes this problem in 2021! haha

**Comment by ArchVision** [comment]
Literally nothing has worked for me nothing, I have tried everything here, nothing.

**Comment by brentvatne** [comment]
@ArchVision - what is your error? can you open a new issue and provide more information?

**Comment by muchirijane** [comment]
The issue was I didn't run the console emulator as an ADMIN.  Hahaha, that was a mistake from my side.
