### ISSUE TITLE
Issue when running yarn test - Expo SDK 51

### ISSUE THREAD

**Issue by oscklm** [expo/expo#28495]
### Minimal reproducible example

https://github.com/oscklm/jest-issue-exposdk51-repro

### Did you reproduce this issue in a development build?

Yes

### Summary

So just installed a fresh SDK 51 beta project using the `yarn create expo-app --template default@beta
`
## Steps to reproduce:
1. yarn create expo-app --template default@beta
2. yarn test
3. jest will encounter a unexpected token in `components/__tests__/ThemedText-test.tsx`

I did a bit of research to see if i could fix this on my own, but without luck. What i did find is this issue, which might be related: https://github.com/facebook/react-native/issues/33426

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.5.2 - ~/.nvm/versions/node/v20.12.2/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.0-preview.7 => 51.0.0-preview.7
      expo-router: 3.5.3 => 3.5.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.0 => 0.74.0
      react-native-web: ~0.19.10 => 0.19.11
    npmGlobalPackages:
      eas-cli: 7.8.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by aleqsio** [comment]
After some testing, this seems to be fixed on the latest version of the [`expo-template-default`](https://www.npmjs.com/package/expo-template-default?activeTab=versions).

Please use `sdk51` or latest instead of the `beta` tag :)
