### ISSUE TITLE
Fix @provides warnings

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#285]
<img width="1280" alt="slack-imgs" src="https://user-images.githubusercontent.com/90494/27413495-91fe872a-56b0-11e7-802c-83a2e6b792fc.png">

happened when running new-project-template after installing with yarn (universe version)

**Comment by ide** [comment]
@brentvatne I'm trying to repro this but first running into a bigger error -- when I run yarn in new-project-template (in universe, not __internal__), yarn installs several copies of react-native. It's like it is installing devDependencies for some reason. Going to try npm 4 for now.
