### ISSUE TITLE
[Expo 51 Beta][iOS] Expo Go app crashes when switching back to previous tab

### ISSUE THREAD

**Issue by nam-aalto** [expo/expo#28508]
### Minimal reproducible example

https://github.com/ntgn81/expo51-router-crash

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

#### Problem

Expo Go app crashes when navigating back to Tab 1 on iOS Simulator

#### Steps

- `npx expo start`
- Open app in iOS simulator
- Click on Tab 2
- Click on Tab 1
- App crashes

#### Extra finding

The app does not crash if `react-native-reanimated` is imported.

Uncommenting the `import "react-native-reanimated"` in `app/_layout.tsx` will make the tab switch work without crashing.

### Environment
```
expo-env-info 1.2.0 environment info:
System:
  OS: macOS 14.4
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
  npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
Managers:
  CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode: 15.3/15E204a - /usr/bin/xcodebuild
npmPackages:
  expo: ~51.0.0-preview.7 => 51.0.0-preview.7 
  expo-router: 3.5.3 => 3.5.3 
  react: 18.2.0 => 18.2.0 
  react-dom: 18.2.0 => 18.2.0 
  react-native: 0.74.0 => 0.74.0 
  react-native-web: ~0.19.10 => 0.19.11 
npmGlobalPackages:
  eas-cli: 7.6.1
Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Upstream `react-native-reanimated` issue: https://github.com/software-mansion/react-native-reanimated/issues/5947

**Comment by nam-aalto** [comment]
Hmm, is it reanimated problem? The reproducible code does not include reanimated. Including reanimated _fixes_ the crash for me.

**Comment by brentvatne** [comment]
@nam-aalto - react-native-screens calls into reanimated in some places

**Comment by marklawlor** [comment]
I'm going to close this issue and move the conversation to https://github.com/expo/expo/issues/28618

We're unsure if a fix for this will be ready at the launch of SDK51. A work around is detailed in the new issue
