### ISSUE TITLE
Is there any way to submit Expo Custom Dev Client to Play Store Internal testing?

### ISSUE THREAD

**Issue by lmcuong25** [expo/expo#28501]
### Summary

Expo Custom Dev Client can only be deployed to the Android Simulator or to .apk Packages that are cumbersome to maintain and hard to install or update. It would be much easier to be able to deploy Expo Dev Client Apps through Play Store Internal testing: everyone on the team could install them very easily on all their devices and updates would run in the background or can be triggered by the press of a button.

Out of the box Expo dev client apps can't be distributed through Play Store Internal testing: in the eas.json adding "developmentClient" properties to "true" in a build profile, that will generate an .apk; 
but to upload to Play Store Internal testing need an Android App Bundle (AAB/.aab)

Is there any way to submit Expo Custom Dev Client to Play Store Internal testing?

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~3.3.11"

### Environment

expo-env-info 1.2.0 environment info:  
    System:  
      OS: macOS 14.4.1  
      Shell: 5.9 - /bin/zsh  
    Binaries:  
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node  
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn  
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm  
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman  
    Managers:  
      CocoaPods: 1.15.2 - /Users/lublue/.rvm/gems/ruby-3.0.0/bin/pod  
    SDKs:  
      iOS SDK:  
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4  
    IDEs:  
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975  
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild  
    npmPackages:  
      expo: ~50.0.14 => 50.0.17   
      react: 18.2.0 => 18.2.0   
      react-native: 0.73.6 => 0.73.6   
    Expo Workflow: managed  

### eas.json
`
...
"development": {
      "releaseChannel": "development",
      "developmentClient": true,
      "distribution": "store",
      "env": {
        "APP_VARIANT": "development"
      },
      "ios": {
        "image": "latest"
      },
      "android": {
        "distribution": "store",
        "buildType": "app-bundle"
      }
    },
...
`

### build app:
`npx eas build --platform android --profile development --local --output ./builds/android/my-expo-dev-client-app.aab`

### Stacktrace (if a crash is involved)

<img width="1190" alt="Screenshot 2024-04-28 at 19 00 32" src="https://github.com/expo/expo/assets/7894594/f6204577-7b86-41cb-922b-303768a178d7">

**Comment by brentvatne** [comment]
hi there! it's not supported at the moment. learn more: https://docs.expo.dev/review/overview/#app-store-testing-tracks

> When distributing apps through app store testing tracks, you can only use release builds. You cannot use this method to distribute development builds. An alternative approach is to use ["Internal distribution"](https://docs.expo.dev/review/overview/#internal-distribution), which works with both release and development builds.

**Comment by moxorama** [comment]
It would be very cool have ability to upload dev-client builds to TestFlight / Google Play for our team. Upgrading dev client ad-hoc build to all team members is painful.
