### ISSUE TITLE
Unmatched route issue in ios/android build but doesn't show in expo go app.

### ISSUE THREAD

**Issue by MohammadHarisZia** [expo/expo#28515]
### Minimal reproducible example

https://github.com/MohammadHarisZia/expo_sample_project

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

<img width="393" alt="Screenshot 2024-04-22 at 6 49 35 PM" src="https://github.com/expo/expo/assets/63912301/08d2c931-92e1-4e02-9dc1-8424b463216a">
<img width="416" alt="Screenshot 2024-04-22 at 6 50 12 PM" src="https://github.com/expo/expo/assets/63912301/209a0093-835d-439e-876a-650c14cefa11">
<img width="416" alt="Screenshot 2024-04-22 at 6 50 12 PM" 
 src="https://github.com/expo/expo/assets/63912301/36b1318d-ef1b-40a0-8237-25654155fd8c">
 
 
 FYI: I am using unstable settings in my root layout

`export const unstable_settings = {
  initialRouteName: '(main)',
};`

![image](https://github.com/expo/expo/assets/63912301/18c141e7-3a07-4697-bdcf-a18c355d7e6a)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      npm: 8.19.4 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.17 => 50.0.17 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.10 => 0.19.10 
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Hi, I'd like the investigate this further but I'm struggling to understand your issue.

Your minimal reproduction is very large and the 1 line of text description provided appears to be pointing to a route that doesn't exist (do you have a `(main)` group?

I would appreciate if you read the comment by @expo-bot and try and create a minimal example that clearly demonstrates your issue. That way I can assist you further

**Comment by MohammadHarisZia** [comment]
@marklawlor Hey! Thanks for getting back to me, okay so if you do `pnpm install` and do `pnpm start`, press `s` to switch from development mode to expo go version you won't see the unmatched route issue but if you build for ios/android like `pnpm ios` or `pnpm android` you will see the issue, I want to investigate if it is a code issue, if yes can you spot it. My understanding is if it was a code issue it should break on expo go as well
