### ISSUE TITLE
Hitting file watchers limit because Expo is watching the node_modules folder

### ISSUE THREAD

**Issue by tbukfrc** [expo/expo#28525]
### Summary

Hello, I am trying to develop an app with Expo but I keep hitting the inotify file watchers limit because Expo is watching the node_modules folder, which contains thousands of files. Running the command `npx expo start` very quickly fails with the following error:
```
Error: ENOSPC: System limit for number of file watchers reached, watch '/root/rekon/node_modules/@babel/core/lib/gensync-utils'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2467:36)
    at NodeWatcher._watchdir (/root/rekon/node_modules/metro-file-map/src/watchers/NodeWatcher.js:89:24)
    at /root/rekon/node_modules/metro-file-map/src/watchers/NodeWatcher.js:26:14
    at Walker.<anonymous> (/root/rekon/node_modules/metro-file-map/src/watchers/common.js:81:31)
    at Walker.emit (node:events:520:28)
    at /root/rekon/node_modules/walker/lib/walker.js:69:16
    at FSReqCallback.oncomplete (node:fs:188:23)
```

I acknowledge that this is an issue that people have ran into before, but the provided solutions I could find were not ideal. The only real solution to the problem I could find was to simply increase the inotify limit, but not only is that a bad idea for performance reasons, I also do not have the ability to change that value on my development machine and therefore cannot raise the limit. Is there a way to tell Expo to not watch the node_modules folder instead of raising the limit?

### What platform(s) does this occur on?

Android

### SDK Version

50.0.15

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 4.14 Ubuntu Jammy Jellyfish (development branch) 22.04 (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 22.0.0 - /bin/node
      npm: 10.5.1 - /bin/npm
      Watchman: 4.9.0 - /bin/watchman
    npmPackages:
      expo: ~50.0.14 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: managed

### Minimal reproducible example

Create a blank expo app with npx create-expo-app and run `expo start` with the default user watches limit of 8192. The above error will occur after a few seconds of the metro bundler starting.

**Comment by EvanBacon** [comment]
This appears to be a regression in Metro bundler

**Comment by tbukfrc** [comment]
Yeah, I unfortunately have no way of raising the limit (i don't have root access) and installing watchman didn't do anything. Either way, given this isn't an Expo bug, I can close this issue.

**Comment by brentvatne** [comment]
@tbukfrc - that's odd that installing watchman didn't help - Metro should be using it for file watching if it is installed. you might be able to find more information on ensuring watchman is setup correctly here: https://facebook.github.io/watchman/docs/install

**Comment by tbukfrc** [comment]
Yeah, it's weird. You can see in my environment info that it's installed, and when running `watchman version` I get the following output:

```
{
    "version": "4.9.0"
}
```

I even tried using the .watchmanconfig file to exclude the node_modules folder but it didn't help, it still fails with the same error and every time it's a file in the node_modules folder.

**Comment by Amirulmuuminin** [comment]
> @tbukfrc - that's odd that installing watchman didn't help - Metro should be using it for file watching if it is installed. you might be able to find more information on ensuring watchman is setup correctly here: https://facebook.github.io/watchman/docs/install

how can you setup watchman correctly? even their documentation is correct by now.

**Comment by Amirulmuuminin** [comment]
> ### Summary
> Hello, I am trying to develop an app with Expo but I keep hitting the inotify file watchers limit because Expo is watching the node_modules folder, which contains thousands of files. Running the command `npx expo start` very quickly fails with the following error:
> 
> ```
> Error: ENOSPC: System limit for number of file watchers reached, watch '/root/rekon/node_modules/@babel/core/lib/gensync-utils'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2467:36)
>     at NodeWatcher._watchdir (/root/rekon/node_modules/metro-file-map/src/watchers/NodeWatcher.js:89:24)
>     at /root/rekon/node_modules/metro-file-map/src/watchers/NodeWatcher.js:26:14
>     at Walker.<anonymous> (/root/rekon/node_modules/metro-file-map/src/watchers/common.js:81:31)
>     at Walker.emit (node:events:520:28)
>     at /root/rekon/node_modules/walker/lib/walker.js:69:16
>     at FSReqCallback.oncomplete (node:fs:188:23)
> ```
> 
> I acknowledge that this is an issue that people have ran into before, but the provided solutions I could find were not ideal. The only real solution to the problem I could find was to simply increase the inotify limit, but not only is that a bad idea for performance reasons, I also do not have the ability to change that value on my development machine and therefore cannot raise the limit. Is there a way to tell Expo to not watch the node_modules folder instead of raising the limit?
> 
> ### What platform(s) does this occur on?
> Android
> 
> ### SDK Version
> 50.0.15
> 
> ### Environment
> expo-env-info 1.2.0 environment info: System: OS: Linux 4.14 Ubuntu Jammy Jellyfish (development branch) 22.04 (Jammy Jellyfish) Shell: 5.1.16 - /bin/bash Binaries: Node: 22.0.0 - /bin/node npm: 10.5.1 - /bin/npm Watchman: 4.9.0 - /bin/watchman npmPackages: expo: ~50.0.14 => 50.0.15 react: 18.2.0 => 18.2.0 react-native: 0.73.6 => 0.73.6 Expo Workflow: managed
> 
> ### Minimal reproducible example
> Create a blank expo app with npx create-expo-app and run `expo start` with the default user watches limit of 8192. The above error will occur after a few seconds of the metro bundler starting.

any solution sir? i face exactly the same issue.

**Comment by rowend36** [comment]
There is a temporary hack around this issue [here
](https://github.com/termux/termux-packages/issues/21478#issuecomment-2408932645).
