### ISSUE TITLE
EXPO-UPDATES - Blank screen (Unable to pause activity) after change the activity to an activity-alias on android

### ISSUE THREAD

**Issue by kibolho** [expo/expo#28534]
### Minimal reproducible example

https://github.com/kibolho/expo-dynamic-app-icon

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I added [expo-dynamic-app-icon](https://www.npmjs.com/package/expo-dynamic-app-icon) and [expo-updates](https://www.npmjs.com/package/expo-updates) to my project and then I started to get a blank screen on android and a Sentry error: 

```bash
Unable to pause activity {com.package.android/com.package.android.MainActivity}: java.lang.reflect.InvocationTargetException
```

Then I removed [expo-updates](https://www.npmjs.com/package/expo-updates) and the error was gone, so I suspect that since [expo-dynamic-app-icon](https://www.npmjs.com/package/expo-dynamic-app-icon) change the activity to an activity-alias [expo-updates](https://www.npmjs.com/package/expo-updates) gets lost while referencing the new activity... but I really don't know why this is happening in just some Android devices.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /Users/abilioazevedo/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.17 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by kibolho** [comment]
Issue in the original repo: https://github.com/outsung/expo-dynamic-app-icon/issues/23

**Comment by brentvatne** [comment]
the example you shared doesn't include expo-updates :) please share a minimal reproducible example video and a screen recording of you reproducing the issue in that repo and we can reopen and investigate! thank you!

**Comment by kibolho** [comment]
Hey @brentvatne sorry for that! Now the repo is updated, but I couldn't reproduce the but in any android emulator...
From sentry it seems to be happening just with some Android Devices.

Here is a [video](https://drive.google.com/file/d/1Nvv4dev1Zo_F6sBnZh_Wkq58jnQqmZis/view?pli=1
) from an user:
- Open the app
- Login
- Identify the custom icon
- Switch to the activity-alias
- Close the app
- Open again
- Try to fetch the remote update
- Blank Screen

And here is the Sentry Error:
![Screenshot 2024-05-02 at 15 12 38](https://github.com/expo/expo/assets/1197923/fb646f4b-546b-4616-84eb-4329c365683d)

And here is some possible related issues:
https://github.com/expo/expo/issues/27364
https://github.com/expo/expo/issues/15298

**Comment by anirudhsama** [comment]
We are also seeing lots of crashes related to this, around 15 per day.

**Comment by mathieupost** [comment]
I had the same issue. Are you using bottom tabs? Setting `<Tabs detachInactiveScreens={false} >` fixed if for me (from https://github.com/react-navigation/react-navigation/issues/11720)

**Comment by kibolho** [comment]
Actually I am not using Tabs but I saw this **detachInactiveScreens** can be used in the Stack Navigator as well, I am wondering if you are using [expo-dynamic-app-icon](https://www.npmjs.com/package/expo-dynamic-app-icon) as well @mathieupost ?

**Comment by anirudhsama** [comment]
Yes, I'm using Bottom Tabs. Will try with that config. Thanks for the suggestions @mathieupost!

**Comment by mathieupost** [comment]
> Actually I am not using Tabs but I saw this **detachInactiveScreens** can be used in the Stack Navigator as well, I am wondering if you are using [expo-dynamic-app-icon](https://www.npmjs.com/package/expo-dynamic-app-icon) as well @mathieupost ?

@kibolho Makes sense that `Tabs` inherits this from `Stack`! I'm not using `expo-dynamic-app-icon`.

**Comment by mianala** [comment]
> I had the same issue. Are you using bottom tabs? Setting `<Tabs detachInactiveScreens={false}>` fixed if for me (from [react-navigation/react-navigation#11720](https://github.com/react-navigation/react-navigation/issues/11720))

Solved it for me, shouldn't this be a default behaviour for BottomTabs?

**Comment by mathieupost** [comment]
Actually removed this yesterday because it made the inactive tab screens have a height of 0 on Android for some reason and I forgot that this was the reason I even set it and wasn't using expo-updates anyway 🤷‍♂️
