### ISSUE TITLE
Android build after Upgrade SDK 50 to 51.0.0-preview.8 fails with [CXX1201] ABIs [armeabi] are not supported for platform

### ISSUE THREAD

**Issue by killerchip** [expo/expo#28541]
### Minimal reproducible example

https://github.com/killerchip/vanilla-sdk-50

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

- I created an vanilla repo with `npx create-expo-app@latest --template` and chose Basic Typescript template.
- run with `npx expo run:android` to confirm working OK on physical device
- upgraded with `npm install expo@next` and `npx expo install --fix`
- run with `npm run android` (with physical device connected)

Build fails with the following:

```
* Where:
Script '****/vanilla-sdk-50/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 408

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-modules-core'.
   > com.android.builder.errors.EvalIssueException: [CXX1201] ABIs [armeabi] are not supported for platform. Supported ABIs are [arm64-v8a, armeabi-v7a, x86, x86_64].
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 30, 31, 33, 33, 34
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-26 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86_64 Atom, android-34 | Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0-preview.8 => 51.0.0-preview.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.0 => 0.74.0 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by byCedric** [comment]
Hi @killerchip, thanks for reporting this issue. Can we ask the device you were trying to run on? It seems that this device has a specific instruction set that doesn't somehow resolve to [the generally accepted architectures](https://developer.android.com/ndk/guides/abis). Specifically:

<img width="439" alt="image" src="https://github.com/expo/expo/assets/1203991/1f1a98ca-3dc2-4127-b7ea-8f20e8df48aa">

For now, you can use `$ npx expo run:android --all-archs` to disable this behavior and continue as usual.
