### ISSUE TITLE
expo-doctor has a non fatal error in 51.*.*

### ISSUE THREAD

**Issue by kziemski** [expo/expo#28545]
### Summary

npx
> expo-doctor

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
...
✖ Check that native modules do not use incompatible support packages
Unexpected error while running 'Check that native modules do not use incompatible support packages' check:
Error: Failed to find dependency tree for @unimodules/core: npm explain @unimodules/core --json exited with non-zero code: 1
✖ Check for legacy global CLI installed locally
Unexpected error while running 'Check for legacy global CLI installed locally' check:
Error: Failed to find dependency tree for expo-cli: npm explain expo-cli --json exited with non-zero code: 1
✔ Check that native modules use compatible support package versions for installed Expo SDK

running those individual commands gives the following:
npm error No dependencies found matching @unimodules/core
{
  "error": {
    "code": null,
    "summary": "No dependencies found matching @unimodules/core",
    "detail": ""
  }
}

npm error No dependencies found matching expo-cli
{
  "error": {
    "code": null,
    "summary": "No dependencies found matching expo-cli",
    "detail": ""
  }
}

### What platform(s) does this occur on?

Web

### SDK Version

51.0.0-preview.8

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 4.1.1 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.6.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
    npmGlobalPackages:
      eas-cli: 7.8.5
    Expo Workflow: managed

### Minimal reproducible example

running npx expo-doctor. i don't have a minimal reproducable project as this happens for any project regardless .

**Comment by brentvatne** [comment]
i can't reproduce this. it's possible that you're using an old version of expo-doctor. try `npx expo-doctor@latest`

**Comment by kziemski** [comment]
i just created an sample application using 
npx create-expo-app@latest doctor-example 
cd doctor-example
npx expo-doctor@latest 
the error file is below 
[error.txt](https://github.com/expo/expo/files/15168618/error.txt)

here is the url that was created https://github.com/kziemski/doctor-example

**Comment by outaTiME** [comment]
same here @brentvatne but with Expo 50, I even tried to delete the dependencies and install them again, and I still get the same error.

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✖ Check that native modules do not use incompatible support packages
Unexpected error while running 'Check that native modules do not use incompatible support packages' check:
Error: Failed to find dependency tree for @unimodules/core: npm explain @unimodules/core --json exited with non-zero code: 1
✖ Check for legacy global CLI installed locally
Unexpected error while running 'Check for legacy global CLI installed locally' check:
Error: Failed to find dependency tree for expo-cli: npm explain expo-cli --json exited with non-zero code: 1
✔ Check that native modules use compatible support package versions for installed Expo SDK
One or more checks failed, indicating possible issues with the project.
```

I leave a screenshot and expo dependencies:

![CleanShot 2024-04-30 at 14 41 18@2x](https://github.com/expo/expo/assets/140472/ee06fdf9-a1ee-4f8c-b8c3-c126c3ce1183)

```
"expo": "^50.0.18",
"expo-application": "~5.8.4",
"expo-asset": "~9.0.2",
"expo-build-properties": "~0.11.1",
"expo-constants": "~15.4.6",
"expo-dev-client": "~3.3.11",
"expo-device": "~5.9.4",
"expo-file-system": "~16.0.9",
"expo-font": "~11.10.3",
"expo-image": "~1.10.6",
"expo-image-manipulator": "~11.8.0",
"expo-image-picker": "~14.7.1",
"expo-localization": "~14.8.4",
"expo-location": "~16.5.5",
"expo-notifications": "~0.27.7",
"expo-secure-store": "~12.8.1",
"expo-sharing": "~11.10.0",
"expo-splash-screen": "~0.26.5",
"expo-status-bar": "~1.11.1",
"expo-system-ui": "~2.9.4",
"expo-updates": "~0.24.12",
```

**Comment by brentvatne** [comment]
thanks, @keith-kurak will check this out

**Comment by keith-kurak** [comment]
I'm having trouble reproducing this locally, as well.

@outaTiME would you be able to confirm your local environment with `npx expo-env-info`?

@outaTiME and/or @kziemski , could you try one of the underlying commands manually from your terminal, e.g., `npm explain expo-cli --json`? It seems like that is erroring out, but it's not exposing the error. 

At first I thought it was maybe a Node 20/ NPM 10 thing, but I switched to that and still couldn't reproduce.

**Comment by kziemski** [comment]
@outaTiME i included it in the original post
running those individual commands gives the following:

npm explain @unimodules/core --json 
npm error No dependencies found matching @unimodules/core
{
"error": {
"code": null,
"summary": "No dependencies found matching @unimodules/core",
"detail": ""
}
}

npm explain expo-cli --json
npm error No dependencies found matching expo-cli
{
"error": {
"code": null,
"summary": "No dependencies found matching expo-cli",
"detail": ""
}
}

**Comment by outaTiME** [comment]
> I'm having trouble reproducing this locally, as well.
> 
> @outaTiME would you be able to confirm your local environment with `npx expo-env-info`?
> 
> @outaTiME and/or @kziemski , could you try one of the underlying commands manually from your terminal, e.g., `npm explain expo-cli --json`? It seems like that is erroring out, but it's not exposing the error.
> 
> At first I thought it was maybe a Node 20/ NPM 10 thing, but I switched to that and still couldn't reproduce.

Yes, for sure, here is the output of the `npx expo-env-info`:

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/Library/Caches/fnm_multishells/59574_1714494219098/bin/node
      Yarn: 4.1.1 - ~/Library/Caches/fnm_multishells/59574_1714494219098/bin/yarn
      npm: 10.6.0 - ~/Library/Caches/fnm_multishells/59574_1714494219098/bin/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.18 => 50.0.18 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.8.5
    Expo Workflow: managed
```

and on the other hand, here is the output of `npm explain expo-cli -json`:

```
npm error No dependencies found matching expo-cli
{
  "error": {
    "code": null,
    "summary": "No dependencies found matching expo-cli",
    "detail": ""
  }
}

npm error A complete log of this run can be found in: /Users/outaTiME/.npm/_logs/2024-04-30T22_11_36_429Z-debug-0.log
```

I hope it will be useful 🙏

**Comment by keith-kurak** [comment]
@kziemski ah, sorry I missed that before! Thanks for providing it again, and thanks for your output, as well, @outaTiME !

It looks like we try to match on `"npm ERR!"`, but your `npm explain` is returning `"npm error"`. We could match on both, but I'm going to try to look around to figure out what could cause that output to change.

**Comment by kziemski** [comment]
oh then its definitely npm@10.6.0. i regularly run nvm install-latest-npm so i probably caught a later version.

**Comment by kziemski** [comment]
👍
Confirm Fixed.

npx expo-doctor@latest 
Need to install the following packages:
expo-doctor@1.6.0
Ok to proceed? (y) y

> @cmat-cmon-app/site@1.0.0 npx
> expo-doctor

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
...
..
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by kziemski** [comment]
@keith-kurak if you're possibly on the discord can you check my related issue to this? I don't know if this is an expo problem i need to report or if its the package owner's issue.  Tried to follow the code for "--check" and doctor but not sure where it get thats info.

**Comment by Josemario17** [comment]
npx expo-doctor
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: orientation, icon, userInterfaceStyle, splash, ios, android, plugins, androidStatusBar.

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: firebase, react-native-feather, swr
Advice:
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
PS C:\Users\josem\Desktop\Monizza-App\Monizza-App> npx expo-doctor@latest
Need to install the following packages:
expo-doctor@1.12.5
Ok to proceed? (y) y
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check that native modules do not use incompatible support packages
✔ Check if the project meets version requirements for submission to app stores
✔ Check for legacy global CLI installed locally
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: orientation, icon, userInterfaceStyle, splash, ios, android, plugins, androidStatusBar.

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: firebase, react-native-feather, swr
Advice:
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
