### ISSUE TITLE
npx expo prebuild fails iOS due to privacy manifests

### ISSUE THREAD

**Issue by stevekuznetsov** [expo/expo#28554]
### Summary

After updating to Expo 50.0.17, we can no longer build for iOS:

```
$ npx expo --version
0.17.10
$ npx expo prebuild --no-install --platform ios
✔ Created native directory | reusing /ios
✔ Updated package.json | no changes
✖ Prebuild failed
TypeError: Cannot read properties of undefined (reading 'withPrivacyInfo')
TypeError: Cannot read properties of undefined (reading 'withPrivacyInfo')
    at withIosExpoPlugins (/home/stevekuznetsov/code/nwacus/avy/src/github.com/nwacus/avy/node_modules/@expo/cli/node_modules/@expo/prebuild-config/build/plugins/withDefaultPlugins.js:141:71)
    at getPrebuildConfig (/home/stevekuznetsov/code/nwacus/avy/src/github.com/nwacus/avy/node_modules/@expo/cli/node_modules/@expo/prebuild-config/build/getPrebuildConfig.js:66:59)
    at Object.getPrebuildConfigAsync (/home/stevekuznetsov/code/nwacus/avy/src/github.com/nwacus/avy/node_modules/@expo/cli/node_modules/@expo/prebuild-config/build/getPrebuildConfig.js:30:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async configureProjectAsync (/home/stevekuznetsov/code/nwacus/avy/src/github.com/nwacus/avy/node_modules/@expo/cli/build/src/prebuild/configureProjectAs
```

### What platform(s) does this occur on?

iOS

### SDK Version

50.0.17

### Environment

```
$ npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.6 Fedora Linux 39 (Workstation Edition)
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 20.10.0 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 10.2.3 - /usr/bin/npm
    npmPackages:
      expo: ~50.0.17 => 50.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.8 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.0.8
    Expo Workflow: bare
```

### Minimal reproducible example

I understand the value of providing such reproducible examples, but I am woefully unprepared to do this. I don't understand Expo (or `yarn`) well enough to really get what is going on here. All I know is that I ran the `npx expo install --fix` on my project, upgrading between minor z-stream versions, and it looks like the latest Expo CLI is broken.

Please see the [update commit](https://github.com/NWACus/avy/commit/1ce1c477a173ed291cba114003993e3321e7249a) for the small set of packages that we updated.

**Comment by stevekuznetsov** [comment]
I believe this is related to https://github.com/expo/expo/pull/28005 @aleqsio

**Comment by stevekuznetsov** [comment]
Ah, sorry ... looks like this was mentioned: https://github.com/expo/expo/issues/27796#issuecomment-2078601497

Using `npx expo@latest` works to do the prebuild. If it's possible, getting the error message to be more coherent would probably help a lot here for messaging! I understand we're all doing a lot under these short timelines from Apple.

**Comment by stevekuznetsov** [comment]
In case anyone else ends up here from Google (none of my searches for that error message got me anywhere...)

I found the issue with:

```
$ npx expo-doctor@latest
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@^7.8.0
Found invalid:
  @expo/config-plugins@7.2.5
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

One or more checks failed, indicating possible issues with the project.
```

Then with `npm why`:

```
@expo/config-plugins@7.2.5
node_modules/@bothrs/expo-mixpanel-analytics/node_modules/@expo/config-plugins
  @expo/config-plugins@"~7.2.0" from @expo/config@8.1.2
  node_modules/@bothrs/expo-mixpanel-analytics/node_modules/@expo/config
    @expo/config@"~8.1.0" from expo-constants@14.4.2
    node_modules/@bothrs/expo-mixpanel-analytics/node_modules/expo-constants
      expo-constants@"^14.0.2" from @bothrs/expo-mixpanel-analytics@2.0.3
      node_modules/@bothrs/expo-mixpanel-analytics
        @bothrs/expo-mixpanel-analytics@"^2.0.3" from the root project
```

**Comment by JoseCWise** [comment]
Hello, i have the same problem but both my npx expo-doctor@latest is clean and the install --fix too.

Still i can't do the build with that same exact error

**Comment by stevekuznetsov** [comment]
You might find more info in the long comment thread on #27796, I don't know enough to help, sorry :(

**Comment by chunghn** [comment]
> Hello, i have the same problem but both my npx expo-doctor@latest is clean and the install --fix too.
> 
> Still i can't do the build with that same exact error

Same. How did you fix it?

**Comment by alterx** [comment]
Same issue here, @chunghn @JoseCWise, make sure that you don't have any resolutions for the `expo/config-plugins` package. Also, make sure that it's not a direct dependency or devDependency in your project. After checking that the error was gone for me.

**Comment by chunghn** [comment]
This is how I solve it.

Run `yarn why @expo/config-plugins` and check if there are other version in use.

If this is your case, add `"resolutions": {
    "@expo/config-plugins": "~8.0.4"
  }` in `package.json` force all package to use updated version.

 My `package.json`
```json
 "dependencies": {
    "@expo/config-plugins": "~8.0.0",
    "expo": "~51.0.8",
...
  },
  "resolutions": {
    "@expo/config-plugins": "~8.0.4"
  }

```

**Comment by d4v3d4vE** [comment]
Similar solution here, fixed it like this:

already had this resolution in my `package.json`: 
```
"resolutions": {
    "@expo/config-plugins": "~7.8.0"
}
```
and need to change it to this for Expo SDK 50:
```
"resolutions": {
    "@expo/config-plugins": "^7.8.4"
}
```
#

**Comment by matheuscouto** [comment]
> Similar solution here, fixed it like this:
> 
> already had this resolution in my `package.json`:
> 
> ```
> "resolutions": {
>     "@expo/config-plugins": "~7.8.0"
> }
> ```
> 
> and need to change it to this for Expo SDK 50:
> 
> ```
> "resolutions": {
>     "@expo/config-plugins": "^7.8.4"
> }
> ```

I was also struggling with this on expo 50 and your resolution worked for me!
