### ISSUE TITLE
[SDK 51] expo-camera in iOS produces upside-down photos and videos in landscape

### ISSUE THREAD

**Issue by omarhabib11** [expo/expo#28573]
### Minimal reproducible example

https://gist.github.com/omarhabib11/6ab06fa32335abcf1be5483f39590753

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

To reproduce this issue, I attempted to take a photo and video in portrait and landscape on iOS and Android. The landscape photos and videos in iOS only come out up-side-down. It happens in landscape left and landscape right. I used [onResponsiveOrientationChanged](https://docs.expo.dev/versions/latest/sdk/camera-next/#onresponsiveorientationchanged) to determine if it is reading the orientation correctly, and it does report back the appropriate values.

Additionally, portrait lock in iOS seems to further disorient the orientation, and the camera ended up sideways when forcing landscape via ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE_RIGHT), even with responsiveOrientationWhenOrientationLocked={true}.

The code provided includes a modal displaying the photo/video on capture.

### Environment

Windows 10 using Expo Go. The output is messed up for some reason.

":"Expo <support@expo.dev>","license":"MIT","bugs":{"url":"https://github.com/expo/expo/issues"},"homepage":"https://github.com/expo/expo/tree/main/packages/expo-env-info#readme","devDependencies":{"@types/envinfo":"^7.8.1","expo-module-scripts":"^3.3.0"},"engines":{"node":"^12.20.0 || ^14.13.1 || >=16.0.0"},"dependencies":{"envinfo":"^7.8.1"},"gitHead":"1a7c4e8ffed182e00cf1cf654ca2401441a7377a"}')}};var E={};function __nccwpck_require__(_){var k=E[_];if(k!==undefined){return k.exports}var N=E[_]={exports:{}};var D=true;try{j[_](N,N.exports,__nccwpck_require__);D=false}finally{if(D)delete E[_]}return N.exports}(()=>{__nccwpck_require__.n=_=>{var j=_&&_.__esModule?()=>_["default"]:()=>_;__nccwpck_require__.d(j,{a:j});return j}})();(()=>{__nccwpck_require__.d=(_,j)=>{for(var E in j){if(__nccwpck_require__.o(j,E)&&!__nccwpck_require__.o(_,E)){Object.defineProperty(_,E,{enumerable:true,get:j[E]})}}}})();(()=>{__nccwpck_require__.o=(_,j)=>Object.prototype.hasOwnProperty.call(_,j)})();if(typeof __nccwpck_require__!=="undefined")__nccwpck_require__.ab=new URL(".",import.meta.url).pathname.slice(import.meta.url.match(/^file:\/\/\/\w:/)?1:0,-1)+"/";var k={};(()=>{var _=__nccwpck_require__(147);var j=__nccwpck_require__(17);var E=__nccwpck_require__.n(j);var k=__nccwpck_require__(152);var N=__nccwpck_require__.n(k);async function*walk(j){for await(const k of await _.promises.readdir(j,{withFileTypes:true})){const _=E().join(j,k.name);if(k.isDirectory()||k.isSymbolicLink()){yield _;yield*walk(_)}else if(k.isFile()){yield _}}}async function findFile(j,k){return _.promises.access(j,_.constants.F_OK).then((async()=>{for await(const _ of walk(j)){if(E().extname(_)===k)return true}return false})).catch((()=>false))}const D=__nccwpck_require__(598);function getEnvironmentInfoAsync(){return N().run({System:["OS","Shell"],Binaries:["Node","Yarn","npm","Watchman"],IDEs:["Xcode","Android Studio"],Managers:["CocoaPods"],SDKs:["iOS SDK","Android SDK"],npmPackages:["expo","expo-router","react","react-dom","react-native","react-native-web","react-navigation","@expo/webpack-config","@expo/metro-config","babel-preset-expo","metro"],npmGlobalPackages:["expo-cli","eas-cli"]},{title:`expo-env-info ${D.version} environment info`})}async function isInsideProjectAsync(j){try{await _.promises.access(E().join(j||process.cwd(),"./package.json"),_.constants.F_OK);return true}catch{return false}}async function isBareWorkflowProject(_){const j=await findFile(E().join(_,"ios"),".xcodeproj");const k=await findFile(E().join(_,"android"),".gradle");return j||k}async function actionAsync(_){process.chdir(_??process.cwd());const j=await getEnvironmentInfoAsync();const E=j.split("\n");if(await isInsideProjectAsync(_)){const j=await isBareWorkflowProject(_)?"bare":"managed";E.pop();E.push(`    Expo Workflow: ${j}`)}console.log(E.join("\n")+"\n")}const packageJson=()=>__nccwpck_require__(598);async function run(){const j=process.argv.slice(2);if(j.some((_=>["-V","-v","--version"].includes(_)))){logVersionAndExit()}if(j.some((_=>["-h","--help"].includes(_)))){logHelpAndExit()}const k=E().resolve(process.cwd(),j[0]??process.cwd());await _.promises.access(k,_.constants.F_OK).catch((_=>{if(_){console.error(`Project directory ${k} does not exist`);process.exit(1)}}));await actionAsync(k)}function logVersionAndExit(){console.log(packageJson().version);process.exit(0)}function logHelpAndExit(){console.log(`\n  Usage: npx expo-env-info [path] [options]\n\n  Log environment info to the console\n\n  Options:\n\n    -h, --help       output usage information\n    -v, --version    output the version number`);process.exit(0)}run()})();

Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

### Expo Doctor Diagnostics

Need to install the following packages:
expo-doctor@1.6.0
Ok to proceed? (y) y
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alanjhughes** [comment]
This library currently has issues in expo go only. I suggest using a development build. A new version of expo go will release soon

**Comment by omarhabib11** [comment]
@alanjhughes I saw the same issue in the iOS testflight app as well. I will give it a try and update you.

**Comment by omarhabib11** [comment]
@alanjhughes The issue persists in development builds as well. I am trying expo-camera 15.0.3.

**Comment by alanjhughes** [comment]
@omarhabib11 - Why is `responsiveOrientationWhenOrientationLocked` in your example?

**Comment by alanjhughes** [comment]
@omarhabib11 - The issue is happening because you are displaying the images in React Natives Modal component which will only display using the interface style set in your app.json.

**Comment by omarhabib11** [comment]
@alanjhughes responsiveOrientationWhenOrientationLocked is commented out because we want to lock photos to landscape for this use case. This photos are oriented correctly in android, it's only an issue in iOS, where the landscape photo is taken, just up-side-down. The images in S3 are also upside down for iOS its not just the image display. Do you mean the camera component should not be in a modal?

**Comment by omarhabib11** [comment]
@alanjhughes Can we reopen this ticket?

**Comment by omarhabib11** [comment]
![IMG_0070](https://github.com/expo/expo/assets/75780393/d0c35d2a-2278-4a0b-bb2e-282c142d43c7)
![IMG_0071](https://github.com/expo/expo/assets/75780393/e39472e3-ad5a-4226-9157-56c940470936)

**Comment by CPedrini** [comment]
@alanjhughes, I can confirm that this is also happening for us in iPadOS, doing a full fledged build with SDK51. Can this issue be reopened?

**Comment by omarhabib11** [comment]
Thx @CPedrini

**Comment by davidhdpro** [comment]
@alanjhughes on Android all landscape taken pictures and videos are returned as PORTRAIT.
   for example  
const pic = await cameraRef.current.takePictureAsync({
			imageType: "jpg",
			quality: 1,
		});

pic object's width and height are always return as portrait (W is always < H)

tested via development and production builds
installed packages

    "expo": "~51.0.8",
    "expo-camera": "~15.0.9",

**Comment by alanjhughes** [comment]
@davidhdpro  This was fixed by #28929 but the changelog was incorrect and this has not been published yet
