### ISSUE TITLE
Native module not found, expo-router v3 doesn't work for bare react-native flow

### ISSUE THREAD

**Issue by CoSNaYe** [expo/expo#28574]
### Issue 1
Native module is not found while using `expo run:ios`, but it works if using Xcode build.
```
# example error:
No native ExponentConstants module found, are you sure the expo-constants's module is linked properly
```

### Issue 2
I followed all the steps listed in the [official doc ](https://docs.expo.dev/router/installation/). 
But it doesn't work
```
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

### What platform(s) does this occur on?

iOS

### SDK Version

50.0.17

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/iancosnaye/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0 => 50.0.17
      expo-router: ~3.4.10 => 3.4.10
      react: 18.2.0 => 18.2.0
      react-native: 0.73.8 => 0.73.8
    npmGlobalPackages:
      eas-cli: 7.8.5
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/CoSNaYe/expo-bare-flow

1st commit: 
init the project with `npx react-native@0.73.8 init wuapp --version 0.73.8`

2nd commit: c237978148
runs `npx install-expo-modules@0.9.1`
this shows the issue 1: native module not found while using `expo run:ios`

3rd commit: 05900a609607
this shows the issue 2: expo-router v3 doesn't work

**Comment by nerixim** [comment]
@CoSNaYe 
Hey, I had the same error as you and I've managed to solve it. Probably my answer wouldn't benefit you but maybe it  would help some other people coming from google search.

You need to set the `moduleName = @"main"` in `AppDelegate.mm`.
https://github.com/CoSNaYe/expo-bare-flow/blob/05900a6096075c1cf880b293241377b31d30b240/ios/wuapp/AppDelegate.mm#L9

P.S.  I'm not sure why you need to do that change manually as Expo guides you to change all other variables in `AppDelegate.mm` except the `moduleName` 🤔

**Comment by DigYang** [comment]
> @CoSNaYe Hey, I had the same error as you and I've managed to solve it. Probably my answer wouldn't benefit you but maybe it would help some other people coming from google search.嘿，我和你有同样的错误，我已经解决了。也许我的回答不会让你受益，但也许它会对其他一些来自谷歌搜索的人有所帮助。
> 
> You need to set the `moduleName = @"main"` in `AppDelegate.mm`.您需要在`AppDelegate.mm`中设置`moduleName = @"main"` 。 https://github.com/CoSNaYe/expo-bare-flow/blob/05900a6096075c1cf880b293241377b31d30b240/ios/wuapp/AppDelegate.mm#L9
> 
> P.S. I'm not sure why you need to do that change manually as Expo guides you to change all other variables in `AppDelegate.mm` except the `moduleName` 🤔PS 我不知道为什么你需要手动进行更改，因为 Expo 会指导你更改`AppDelegate.mm`中除`moduleName`之外的所有其他变量 🤔

you are right, thank you guy
