### ISSUE TITLE
expo-asset not usable vanilla projects

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2858]
In projects created with `react-native init`, `expo-asset` doesn't work. I haven't taken time to unpack why this is exactly, but here's an example of a project in development mode that errors despite being correct:

<img width="432" alt="screen shot 2018-11-29 at 11 23 58 am" src="https://user-images.githubusercontent.com/90494/49246271-5849ae80-f3c9-11e8-936d-71f79a17c9eb.png">

```js
import React from 'react';
import { View, Image } from 'react-native';
import { Asset } from 'expo-asset';

export default class App extends React.Component {
  state = {
    loaded: false,
  };

  async componentDidMount() {
    await Asset.fromModule(require('./quin.png')).downloadAsync();
    this.setState({ loaded: true });
  }

  render() {
    if (!this.state.loaded) {
      return <View />;
    }

    return (
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <Image source={require('./quin.png')} />
      </View>
    );
  }
}
```

**Comment by tsapeta** [comment]
I guess that it works as expected now 😉

**Comment by brentvatne** [comment]
indeed it does :)

for anyone who comes across this, see https://github.com/unimodules/react-native-unimodules to see how to get everything working
