### ISSUE TITLE
ImagePicker Crashes

### ISSUE THREAD

**Issue by tsmrafee-bs** [expo/expo#286]
App crashes after opening the image library and after the camera also.

I tried to use imagepicker like this:

    let result = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [4, 3],
      quality: 0.4,
      base64: false,
      exif: false,
    })

    if (!result.cancelled) {
      this.props.navigation.navigate("UploadImage", { image: result })
    }

it works perfectly in android. But in IOS it opens the image library and close the library and crash. whats wrong with this?

**Comment by terribleben** [comment]
Are you in a detached app with ExpoKit? In that case you need to add the appropriate `UsageDescription` keys to your app's native `Info.plist`.

**Comment by dikaiosune** [comment]
@tsmrafee-bs I'll close this on the assumption that @terribleben's fix works. If it doesn't please post back and we can reopen. Thanks!

**Comment by pinchez254** [comment]
experiencing the same problem on stand alone apps  this my code ` <Container>
        <Text
          style={{
            paddingBottom: 10,
            paddingLeft: 10,
            fontSize: 20,
          }}>
          You need to provide atleast one image for your offer ad to look
          attractive to your target customers!
        </Text>
        <View
          style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
          <View
            style={{
              alignItems: 'center',
              justifyContent: 'center',
            }}>
            <Button iconLeft transparent primary onPress={this._pickImage}>
              <Ionicons size ={35} name="ios-images" />
              <Text style={{ paddingLeft: 10 }}>
                Pick an image from camera roll
              </Text>
            </Button>
          </View>
          <View style={{ alignItems: 'center', justifyContent: 'center' }}>
            <Text>Or</Text>
            <Button iconLeft transparent primary onPress={this._takePhoto}>
              <Ionicons size ={35} name="ios-camera-outline" />
              <Text style={{ paddingLeft: 10 }}> Take a photo</Text>
            </Button>
          </View>

          {image && (
            <View>
              <Image
                source={{ uri: image }}
                style={{ width: 200, height: 200 }}
              />
              <Button
                iconRight
                transparent
                primary
               // onPress={() => this._handleImagePicked(image)}
               >
                <Text>If this is ok proceed to next step</Text>
                <Icon name="arrow-forward" />
              </Button>
            </View>
          )}
        </View>
      </Container>
    );
  }

  _takePhoto = async () => {
    const { status: cameraPerm } = await Permissions.askAsync(
      Permissions.CAMERA
    );

    const { status: cameraRollPerm } = await Permissions.askAsync(
      Permissions.CAMERA_ROLL
    );

    // only if user allows permission to camera AND camera roll
    if (cameraPerm === 'granted' && cameraRollPerm === 'granted') {
      let pickerResult = await ImagePicker.launchCameraAsync({
        allowsEditing: true,
        aspect: [3, 4],
      });
      this.setState({ image: pickerResult.uri });

      // this._handleImagePicked(pickerResult);
    }
  };

  _pickImage = async () => {
    const { status: cameraRollPerm } = await Permissions.askAsync(
      Permissions.CAMERA_ROLL
    );

    // only if user allows permission to camera roll
    if (cameraRollPerm === 'granted') {
      let pickerResult = await ImagePicker.launchImageLibraryAsync({
        allowsEditing: true,
        aspect: [4, 3],
      });
       console.log(pickerResult);
      this.setState({ image: pickerResult.uri });
      this.setState({ result: pickerResult });
      // this._handleImagePicked(pickerResult);
    }
  };`
