### ISSUE TITLE
Could not find host.exp.exponent:expoview:31.0.0

### ISSUE THREAD

**Issue by jorgefernandes** [expo/expo#2860]
### Environment

 Expo CLI 2.4.3 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.4.3

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/jorgefernandes-fd652a69-19c0-4133-a28b-c568e9608a27.tar.gz

### Problem

I'm trying to update my ExpoSdk to the latest version but Android Studio keeps logging Could not find host.exp.exponent:expoview:31.0.0. Tryied everything :(
I'm using gradle 4.4, android plugin 3.1.4

Apparently it is searching in the wrong place

Searched in the following locations:
    file:/Users/jorgefernandes/Library/Android/sdk/extras/m2repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/Library/Android/sdk/extras/m2repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Library/Android/sdk/extras/google/m2repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/Library/Android/sdk/extras/google/m2repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Library/Android/sdk/extras/android/m2repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/Library/Android/sdk/extras/android/m2repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Projetos/rook/android/maven/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/Projetos/rook/android/maven/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Projetos/rook/android/maven-test/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/Projetos/rook/android/maven-test/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Projetos/rook/node_modules/jsc-android/dist/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/Projetos/rook/node_modules/jsc-android/dist/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Projetos/rook/android/app/libs/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Projetos/rook/android/app/libs/expoview.aar
    https://dl.google.com/dl/android/maven2/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    https://dl.google.com/dl/android/maven2/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    https://jcenter.bintray.com/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    https://jcenter.bintray.com/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    https://jitpack.io/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    https://jitpack.io/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/Projetos/rook/node_modules/expokit/maven/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/Projetos/rook/node_modules/expokit/maven/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    file:/Users/jorgefernandes/.m2/repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    file:/Users/jorgefernandes/.m2/repository/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    https://repo.maven.apache.org/maven2/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    https://repo.maven.apache.org/maven2/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar
    https://maven.fabric.io/public/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.pom
    https://maven.fabric.io/public/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar

**Comment by sjchmiela** [comment]
Hey, @jorgefernandes!

You're upgrading your project from an old SDK! 😉 Since then we've moved the packaged native Android code from `expo` package to a separate, `expokit` package. This makes `expo` lighter and lets us release native code updates separately. 🙂 

Try installing `expokit@^31.0.2` in your project. This should let Gradle find the `expoview-31.0.0.aar` in `/Users/jorgefernandes/Projetos/rook/node_modules/expokit/maven/host/exp/exponent/expoview/31.0.0/expoview-31.0.0.aar`.

For the record, these instructions are also included in [Upgrading ExpoKit on Android](https://docs.expo.io/versions/latest/expokit/expokit#android-1) guide.

Let me know if this advice helped you resolve your issue! 🙂

**Comment by jorgefernandes** [comment]
Hey, @sjchmiela it really was, had not seen that. Thanks!
