### ISSUE TITLE
"Unmatched route" when starting Android app

### ISSUE THREAD

**Issue by rubenwardy** [expo/expo#28621]
### Minimal reproducible example

https://github.com/rubenwardy/expo-router-mre

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Expected behaviour:

* I build my app using `npx expo run:android`
* When run:android opens the app or I tap the app on the pixel launcher
* I see the index page

Actual behaviour

* When I open the app, I see "Unmatched Route - page could not be found"
* Clicking "go back" correctly goes to the index page

The app index is correctly shown when using Expo Go

![image](https://github.com/expo/expo/assets/2122943/75bcc115-fab1-4877-9ecd-a2af1ec79a65)

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.8 EndeavourOS
      Shell: 5.2.26 - /bin/bash
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.22 - /usr/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    npmPackages:
      expo: ~50.0.17 => 50.0.17 
      expo-router: ~3.4.10 => 3.4.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    Expo Workflow: bare

**Comment by rubenwardy** [comment]
This still happens if I move the app folder from `src/app` to `app`.

Possibly related to #28515 and #28367

**Comment by rubenwardy** [comment]
Possibly related: https://github.com/expo/router/issues/457

**Comment by rubenwardy** [comment]
As a workaround, I've created a `src/app/com.rubenwardy.expo_rater_mre:.tsx` file. But I shouldn't need to do this

```
import { Redirect } from "expo-router";

export default function RedirectToHome() {
	return (<Redirect href="/" />);
}
```

**Comment by raajnadar** [comment]
I am facing the same issue, with the project where I get the QR code from the GitHub action for a PR, I will try to reproduce the bug in a public repo to display the error

**Comment by marklawlor** [comment]
@raajnadar This is fixed in `3.5.0`, which is available as part of the SDK51 beta

**Comment by marklawlor** [comment]
@rubenwardy Can you please provide more description about your issue

> I run the app

Can you provide more information about where you are running the app from? It appears you are opening a deeplink, how was this link generated (or which QR code are you using)

**Comment by raajnadar** [comment]
> I am facing the same issue, with the project where I get the QR code from the GitHub action for a PR, I will try to reproduce the bug in a public repo to display the error

I can confirm this bug is solved in Expo SDK 51 & expo router `3.5.0+`

**Comment by rubenwardy** [comment]
> Can you provide more information about where you are running the app from? It appears you are opening a deeplink, how was this link generated (or which QR code are you using)

I tap the app from the android homescreen. I'm not using deep links at all

**Comment by rubenwardy** [comment]
Turns out the issue was that the scheme contained `_` rather than using `-`. Replacing all the `_` with `-` fixes the issue. I would suggest adding a compiler error for this, `npx expo-doctor@latest` is too hidden

**Comment by rubenwardy** [comment]
Have you checked your scheme?

**Comment by prince272** [comment]
> Turns out the issue was that the scheme contained `_` rather than using `-`. Replacing all the `_` with `-` fixes the issue. I would suggest adding a compiler error for this, `npx expo-doctor@latest` is too hidden
> 
> ```diff
> --- a/app.json
> +++ b/app.json
> @@ -6,7 +6,7 @@
>      "orientation": "portrait",
>      "icon": "./assets/icon.png",
>      "userInterfaceStyle": "light",
> -    "scheme": "com.rubenwardy.expo_router_mre",
> +    "scheme": "com.rubenwardy.expo-router-mre",
>      "splash": {
>        "image": "./assets/splash.png",
>        "resizeMode": "contain",
> ```

I believe there should have been a warning of some form to help avoid these issues with Expo.

**Comment by bbalan** [comment]
@prince272 This solved my problem, thank you. I also had an underscore in my `scheme`.
