### ISSUE TITLE
[android][expo-sqlite/next] android build error: Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-sqlite' of type org.gradle.api.Project

### ISSUE THREAD

**Issue by gpurbia** [expo/expo#28632]
### Minimal reproducible example

N/A

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

I have upgrade to expo sdk 50, and i am using sqlite to my project. Initially i upgrade sqlite version expo-sqlite@13.3.0, but it broke the android build. It was not working with android build and issue for this already open [here](https://github.com/expo/expo/issues/28297).

After some analysis i upgrade sqlite to the expo-sqlite/next (npm i expo-sqlite@14.0.3) and make the necessary code changes. Now IOS build is working here also, but EAS android build is failing with the following errors:

`> Configure project :
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :gradle-plugin:inspectClassesForKotlinIC
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* Where:
Build file '/home/expo/workingdir/build/node_modules/expo-sqlite/android/build.gradle' line: 13
* What went wrong:
A problem occurred evaluating project ':expo-sqlite'.
> Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-sqlite' of type org.gradle.api.Project.
* Try:
> Run with
--stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
>
Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/home/expo/workingdir/build/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 65
* What went wrong:
A problem occurred configuring project ':expo'.
> Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.`

**Note: It is working fine locally in android. But it is breaking android build. IOS build is working fine and getting success. I am using monorepo architecture.**

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed

**My Package.json**

```
{
  "name": "abc",
  "dependencies": {
    "@expo/config-plugins": "^7.8.0",
    "@gorhom/bottom-sheet": "^4.4.6",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/netinfo": "11.1.0",
    "@react-native-masked-view/masked-view": "0.3.0",
    "@react-native-picker/picker": "2.6.1",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "6.6.2",
    "expo": "~50.0.17",
    "expo-application": "~5.8.4",
    "expo-secure-store": "~12.8.1",
    "expo-build-properties": "~0.11.1",
    "expo-cached-image": "50.0.6",
    "expo-splash-screen": "~0.26.5",
    "expo-status-bar": "~1.11.1",
    "firebase": "8.2.3",
    "next": "10.2.0",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^8.0.0",
    "onesignal-expo-plugin": "^1.3.2",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-get-random-values": "~1.8.0",
    "react-native-logs": "^5.1.0",
    "react-native-onesignal": "^4.5.1",
    "react-native-pager-view": "6.2.3",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-web": "~0.19.6",
    "@expo/match-media": "^0.4.0",
    "@gorhom/bottom-sheet": "^4.4.6",
    "@react-native-picker/picker": "2.6.1",
    "expo-av": "~13.10.6",
    "expo-camera": "~14.1.3",
    "expo-document-picker": "~11.10.1",
    "expo-file-system": "~16.0.9",
    "expo-image-manipulator": "~11.8.0",
    "expo-image-picker": "~14.7.1",
    "expo-images-picker": "^2.5.1",
    "expo-linear-gradient": "~12.7.2",
    "expo-location": "~16.5.5",
    "expo-media-library": "~15.9.2",
    "expo-screen-orientation": "~6.4.1",
    "expo-sensors": "~12.9.1",
    "expo-video-thumbnails": "~7.9.0",
    "libphonenumber-js": "^1.10.31",
    "moment": "^2.29.4",
    "react-native-autoheight-webview": "1.6.5",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-image-slider-show": "^1.0.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modern-datepicker": "^1.0.0-beta.91",
    "react-native-pager-view": "6.2.3",
    "react-native-paper": "^4.11.2",
    "react-native-picker-select": "^8.0.4",
    "react-native-raw-bottom-sheet": "2.2.0",
    "react-native-render-html": "^6.3.4",
    "react-native-swiper-flatlist": "3.2.3",
    "react-native-webview": "13.6.4",
    "react-responsive": "8.2.0",
    "react-tooltip": "^5.21.1",
    "rn-placeholder": "^3.0.3",
    "rn-tooltip": "^3.0.1",
    "xmldom": "^0.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@types/react": "~18.2.14",
    "css-minimizer-webpack-plugin": "^3.0.1",
    "typescript": "^5.3.0",
     "@babel/preset-env": "^7.22.4",
    "@babel/preset-typescript": "^7.21.5",
    "@storybook/addon-actions": "7.0.18",
    "@storybook/addon-essentials": "7.0.18",
    "@storybook/addon-links": "7.0.18",
    "@storybook/react": "7.0.18",
    "@storybook/react-webpack5": "7.0.18",
    "@testing-library/react-native": "^9.0.0",
    "@types/react": "~18.2.14",
    "copy-webpack-plugin": "^10.2.0",
    "react-dom": "^18.2.0",
    "@babel/core": "^7.19.3",
    "@testing-library/react-native": "^8.0.0",
    "@types/jest": "^27.0.1",
    "@typescript-eslint/eslint-plugin": "^4.30.0",
    "@typescript-eslint/parser": "^4.30.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.32.0",
    "eslint-config-airbnb-typescript": "^14.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.25.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "handlebars": "^4.7.7",
    "husky": "7.0.2",
    "jest": "^29.2.1",
    "jest-expo": "~50.0.4",
    "lint-staged": ">=10",
    "metro-minify-terser": "^0.76.5",
    "metro-react-native-babel-preset": "^0.76.5",
    "nodemon": "^2.0.15",
    "prettier": "2.3.2",
    "prompts": "^2.4.2",
    "react-native-walkthrough-tooltip": "1.4.0",
    "react-test-renderer": "^18.2.0",
    "ts-jest": "^27.0.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.0",
    "yup": "^0.32.11"
    "react-responsive": "8.2.0",
    "storybook": "7.0.18"
  }
}

```

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by Shubh-Rajawat** [comment]
@gpurbia Did you find the solution ???

**Comment by gpurbia** [comment]
@Shubh-Rajawat not yet, i am going with expo-sqlite again for now, will check with expo 51 if its resolved or not.

**Comment by Shubh-Rajawat** [comment]
@gpurbia  I am getting this same error but with `expo-document-picker` tried so many things but not getting any solution. Still Trying

**Comment by gpurbia** [comment]
https://github.com/expo/expo/blob/sdk-51/packages/expo-document-picker/android/build.gradle

@Shubh-Rajawat yeah, because the same method is there also in gradle file, check above link. There may be something we are missing with dependencies here. Or you can try with expo 51 which was released today only.

**Comment by paulayo93** [comment]
Please am having the same error in expo-blur

` Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-blur' of type org.gradle.api.Project.`

**Comment by paulayo93** [comment]
> Please am having the same error in expo-blur
> 
> ` Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-blur' of type org.gradle.api.Project.`

Got it fixed running this command :

`npx expo install --fix`

https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/

**Comment by adamspotlite** [comment]
is this related to the release of Expo 51? we're on 50 but maybe something snuck into the build pipeline?

had this happen for the first time after really minimal code changes an hour ago.

**Comment by Shubh-Rajawat** [comment]
`npx expo install --fix`   it worked.. Thanks to both of you @paulayo93 and @gpurbia . This was my first React native project, Now I have downloaded the file from expo.dev and the extension is `.aab` I don't know how to use it as `apk `in  mobile. I am still figuiring this out.

**Comment by Shubh-Rajawat** [comment]
> `npx expo install --fix` it worked.. Thanks to both of you @paulayo93 and @gpurbia . This was my first React native project, Now I have downloaded the file from expo.dev and the extension is `.aab` I don't know how to use it as `apk `in mobile. I am still figuiring this out.

Found this too .-- [https://docs.expo.dev/build-reference/apk/](https://docs.expo.dev/build-reference/apk/)
So finally this issue is closed now.

**Comment by bigxalx** [comment]
Have the same problem thrown by `expo-constants`. 
`npx expo install --fix` did not fix it.

**Comment by gpurbia** [comment]
@bigxalx it should work with expo 51, i upgraded with 51, and it start working.

**Comment by jcheso** [comment]
> Have the same problem thrown by `expo-constants`. `npx expo install --fix` did not fix it.

I'm getting the same issue with Expo 50.0.18 when running `npx expo run:android`

`> Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-constants' of type org.gradle.api.Project.`

I use React Native Firebase which doesn't seem to support the new architecture yet based off this [spreadsheet](https://docs.google.com/spreadsheets/d/1F1tI9PQLl_uab3HNYNwgjPVL2r0hJ9VymXcgDp5etdg) - does anyone know of an alternative fix in the meantime?

**Comment by bigxalx** [comment]
> @bigxalx it should work with expo 51, i upgraded with 51, and it start working.

That worked, thanks! 

This might be useful to anyone who updated to expo 51 in day one: I got some errors, so reverted back to 50. If you experienced the same, try upgrading to 51 again as 51.0.2 seemed to fix the bugs I got.

**Comment by rumrum28** [comment]
> FAILURE: Build failed with an exception. * Where: Build file 'C:\Code\React Native\projectFolder\node_modules\expo\android\build.gradle' line: 9 * What went wrong: A problem occurred evaluating project ':expo'. > Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo' of type org.gradle.api.Project.

help still not fill with npx expo install --fix

**Comment by Mitrandir-main** [comment]
> > FAILURE: Build failed with an exception. * Where: Build file 'C:\Code\React Native\projectFolder\node_modules\expo\android\build.gradle' line: 9 * What went wrong: A problem occurred evaluating project ':expo'. > Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo' of type org.gradle.api.Project.
> 
> help still not fix* with npx expo install --fix

Not working for me as well for :expo-blur

**Comment by rumrum28** [comment]
> > FAILURE: Build failed with an exception. * Where: Build file 'C:\Code\React Native\projectFolder\node_modules\expo\android\build.gradle' line: 9 * What went wrong: A problem occurred evaluating project ':expo'. > Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo' of type org.gradle.api.Project.
> 
> help still not fix* with npx expo install --fix

for some reason i fix it by just removing this "react-native-swiper-flatlist"

**Comment by costaDZ** [comment]
having the same issue with expo 50 , **Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-system-ui' .**

I didn't want to upgrade to expo 51 because it doesn't support some modules i uses in my project , like **expo-background-fetch**

**Comment by ldallalio** [comment]
I was on Expo 50 and tried npx expo install --fix with no luck then upgraded to expo@51 and then ran npx expo install --fix with success, I was having a problem with expo-crypto.

**Comment by buildnewapp** [comment]
> Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-system-ui' of type org.gradle.api.Project.

`
npx expo install --fix
`

work for me,I guess I'm using Expo version 50, and the new package defaults to version 51

**Comment by Lucass2021** [comment]
npx expo install --fix did'nt work here.

My error:
* What went wrong:
A problem occurred evaluating project ':expo-asset'.
> Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-asset' of type org.gradle.api.Project.

**Comment by ma-mendoza** [comment]
> npx expo install --fix did'nt work here.
> 
> My error:
> 
> * What went wrong:
>   A problem occurred evaluating project ':expo-asset'.
> 
> > Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-asset' of type org.gradle.api.Project.

I also got the same error. I am using Expo 50

**Comment by Evaristo-Perez-Lopez** [comment]
I ran this `npx expo install --check` so it can seek any incompatibly with the expo version and packages installed. Then I accepted the fixes it suggested.
I was using  expo@50.0.15 and upgraded to ~50.0.19. 
It worked for me. 
Hope it helps someone.

**Comment by suehtemorp** [comment]
> Have the same problem thrown by `expo-constants`. `npx expo install --fix` did not fix it.

In case anyone else here has this problem with specifically `expo-constants` under `expo@~50.0.19`, I had it fixed by overriding the dependency version to 15.4.6 via the `package.json` file.

I observed this worked while working on a college assigment when one branch built and another one didn't. They both had the exact same dependency list on `package.json`, although our app's source code was different.

**Comment by mustafaquaidZ** [comment]
> npx expo install --fix did'nt work here.
> 
> My error:
> 
> * What went wrong:
>   A problem occurred evaluating project ':expo-asset'.
> 
> > Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-asset' of type org.gradle.api.Project.

I Solved it by editing node_modules/expo-asset/expo-module.config to
```
{
  "platforms": ["ios", "android"]
}
```

**Comment by Lucass2021** [comment]
> ###
> **[mustafaquaidZ](/mustafaquaidZ) ** commented [Jun 11, 2024](#issuecomment-2160760386) •

It worked here. Thank you so much.


Now i will try to find out which library use expo-asset as a dependencie, most likely this will be fixed soon.

**Comment by vaibhavzignuts** [comment]
hello bro getting the same error of expo-asset that you encountering , so please provide solution , if you got

**Comment by mustafaquaidZ** [comment]
> hello bro getting the same error of expo-asset that you encountering , and i have no such file like expo-module.config , in my nodemodules so please provide solution , if you got !! @Lucass2021
<img width="1007" alt="Screenshot 2024-06-18 at 8 48 55 PM" src="https://github.com/expo/expo/assets/128475394/61cd853f-23c9-4654-ae40-d6e14f24bdf0">

it is inside the expo-asset module. if you cannot find it there then create one.

**Comment by Itja** [comment]
For us, it was an override in the `package.json` for `expo-modules-core`. You want that package updated to at least 1.12.15 (see `npm ls expo-modules-core`. It is the package that brings the `ext.useDefaultAndroidSdkVersions` definition in `node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle`.

**Comment by samskinner-joann** [comment]
> > Have the same problem thrown by `expo-constants`. `npx expo install --fix` did not fix it.
> 
> In case anyone else here has this problem with specifically `expo-constants` under `expo@~50.0.19`, I had it fixed by overriding the dependency version to 15.4.6 via the `package.json` file.
> 
> I observed this worked while working on a college assigment when one branch built and another one didn't. They both had the exact same dependency list on `package.json`, although our app's source code was different.

Thank you, this worked for me. I was on 50.0.19 and just added `"expo-constants": "15.4.6",` to package.json and all good :)

**Comment by ARIARCHI-MZ** [comment]
fot this type of errors check the dependencies that mentioned in the log of failure logs and uninstall it. for me it was expo permission that is expired and I didn't need it but forgot to uninstall it.

**Comment by arrehman0r** [comment]
npx expo install --fix
thanks this woks for me too

**Comment by Luiyit** [comment]
```bash
yarn expo install --fix
```
Worked for me. Thanks!!

**Comment by SourceCipher** [comment]
Expo and react native - fix your compiling errors for 80% of the time and enjoy developing 20%! That should be their motto. None of the above works. These errors come out of nowhere. 1 time you run your project and it will work fine, the other you will waste whole day trying to figure out whats causing this random error to appear.

**Comment by imraann0** [comment]
guys im still stuck on this ive tried everything above if anyone can let me know what to do 

my dep  - 
{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/config-plugins": "^8.0.8",
    "@expo/vector-icons": "^14.0.2",
    "@gorhom/bottom-sheet": "^4",
    "@gorhom/portal": "^1.0.12",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/netinfo": "11.3.1",
    "@react-native-community/slider": "4.5.2",
    "@react-native-firebase/app": "19.2.2",
    "@react-native-firebase/auth": "19.2.2",
    "@react-native-firebase/database": "19.2.2",
    "@react-native-firebase/storage": "19.2.2",
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/material-bottom-tabs": "^6.2.29",
    "@react-navigation/material-top-tabs": "^6.6.14",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.5.0",
    "@react-navigation/stack": "^5.14.4",
    "@shopify/flash-list": "1.6.4",
    "axios": "^0.26.1",
    "dayjs": "^1.11.10",
    "expo": "^51.0.22",
    "expo-av": "~14.0.6",
    "expo-barcode-scanner": "~13.0.1",
    "expo-blur": "~13.0.2",
    "expo-build-properties": "~0.12.3",
    "expo-camera": "~15.0.14",
    "expo-clipboard": "~6.0.3",
    "expo-constants": "~16.0.2",
    "expo-crypto": "~13.0.2",
    "expo-dev-client": "~4.0.20",
    "expo-device": "~6.0.2",
    "expo-file-system": "~17.0.1",
    "expo-font": "~12.0.9",
    "expo-google-app-auth": "~8.3.0",
    "expo-image-picker": "~15.0.7",
    "expo-keep-awake": "~13.0.2",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-location": "~17.0.1",
    "expo-media-library": "~16.0.4",
    "expo-notifications": "~0.28.12",
    "expo-router": "~3.5.18",
    "expo-sensors": "~13.0.9",
    "expo-sharing": "~12.0.1",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-store-review": "~7.0.2",
    "expo-system-ui": "~3.0.7",
    "expo-task-manager": "~11.8.2",
    "expo-updates": "~0.25.21",
    "expo-web-browser": "~13.0.3",
    "firebase": "10.0.0",
    "formik": "^2.2.8",
    "geolib": "^3.3.3",
    "i": "^0.3.7",
    "lottie-react-native": "6.7.0",
    "moment": "^2.29.3",
    "native-notify": "^3.0.4",
    "react": "18.2.0",
    "react-content-loader": "^7.0.2",
    "react-dom": "18.2.0",
    "react-modal": "^3.14.4",
    "react-native": "0.74.3",
    "react-native-animatable": "^1.3.3",
    "react-native-calendars": "^1.1297.0",
    "react-native-dropdown-picker": "^5.3.0",
    "react-native-elements": "^3.4.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "6.3.0",
    "react-native-paper": "^5.12.3",
    "react-native-purchases": "^7.4.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-toast-message": "^2.1.2",
    "react-native-vector-icons": "^10.1.0",
    "react-native-web": "~0.19.10",
    "uuid": "^10.0.0",
    "uuid-random": "^1.3.2",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0"
  },
  "resolutions": {
    "@expo/config-plugins": "~8.0.8",
    "@expo/prebuild-config": "~7.0.0",
    "expo-modules-autolinking": "~1.11.0"
  },
  "private": true,
  "name": "mm",
  "version": "1.0.0"
}


--

FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* Where:
Build file '/home/expo/workingdir/build/node_modules/expo-app-auth/android/build.gradle' line: 25
* What went wrong:
A problem occurred evaluating project ':expo-app-auth'.
> Could not set unknown property 'classifier' for task ':expo-app-auth:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.
* Try:
> Run with --stacktrace option to get the stack trace.

**Comment by imraann0** [comment]
so for me i had expo-google-app-auth package installed which has now been deprecated. what a waste of my 24hrs

**Comment by JWesorick** [comment]
You have installed a newer expo package than your apps expo version. Use `yarn dlx expo-doctor` or `npx expo-doctor` to see what version of the package you should use with your apps expo version.

**Comment by AntonioUnitaskr** [comment]
I got same eror again and again, even if I did try all the solutions here. I am on expo 50 with RN 0.73 so all should be compatible. works on ios, not on android with this error: 
> Configure project :app
 ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@3.6.10)
 ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.24.13)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/Users/antoniounitaskr/shout/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 377

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-av'.
   > Failed to notify project evaluation listener.
      > compileSdkVersion is not specified. Please add it to build.gradle
      > Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> Failed to notify project evaluation listener.
   > compileSdkVersion is not specified. Please add it to build.gradle
   > Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 22s
15 actionable tasks: 15 executed
error Command failed with exit code 1.

**Comment by wahas-mughal** [comment]
The issue was the incompatible version of the expo package at my end, fixed it by **npx expo install --fix**

**Comment by bglowney** [comment]
In case it helps anyone, I got this same issue (on expo 50) when I installed expo-splash-screen by mistake with `npm install`. Uninstalling and reinstalling with `expo install expo-splash-screen` solved it.

**Comment by Rodrigojuniorj** [comment]
> > npx expo install --fix não funcionou aqui.
> > Meu erro:
> > 
> > * O que deu errado: 
> >   Ocorreu um problema ao avaliar o projeto ':expo-asset'.
> > 
> > > Não foi possível encontrar o método useDefaultAndroidSdkVersions() para argumentos [] no projeto ':expo-asset' do tipo org.gradle.api.Project.
> 
> Resolvi editando node_modules/expo-asset/expo-module.config para
> 
> ```
> {
>   "platforms": ["ios", "android"]
> }
> ```
> 
> e meu app.json para
> 
> ```
> {
>   "expo": {
>     "name": "ProjectName",
>     "slug": "ProjectName",
>     "version": "1.0.0",
>     "assetBundlePatterns": [
>       "**/*"
>     ],
>     "platforms": ["ios", "android"]
>   }
> }
> ```

Esse foi podem usar
