### ISSUE TITLE
[expo-notifications] setBadgeCountAsync(0) also clears notifications

### ISSUE THREAD

**Issue by kaitlyn-lighthouse** [expo/expo#28641]
### Minimal reproducible example

see steps in summary

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm using expo-notifications on iOS only. If I call `setBadgeCountAsync` with any positive integer, the badge count is updated, and any notifications currently in the iOS notification center remain unchanged. However if I call `setBadgeCountAsync(0)`, the badge disappears correctly, but all notifications are also dismissed.

**Expected behavior**

Calling `setBadgeCountAsync(0)` removes the badge but leaves any existing push notifications visible in the notification center.

**Actual behavior**

Calling `setBadgeCountAsync(0)` removes the badge and all existing push notifications.

**Steps to reproduce**

1. Create the default expo app using the CLI and install expo-notifications
2. Ask the user for push notification permission, and send them one or more push notifications using expo.dev/notifications.
3. Call `setBadgeCountAsync(0)` and see that the notifications disappear from the notification center

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      npm: 10.2.4 - ~/Documents/bloom/ui-mobile/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7 
      @expo/webpack-config: ^19.0.1 => 19.0.1 
      expo: ^49.0.21 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
      react-native-web: ~0.19.10 => 0.19.10 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Some dependencies are incompatible with the installed expo version:
  @sentry/react-native@5.22.0 - expected version: 5.10.0
  sentry-expo@7.2.0 - expected version: ~7.1.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
Found outdated dependencies

**Comment by brentvatne** [comment]
What you are encountering is an expected behavior of iOS for the API used - if you look at the implementation of setBadgeAsync, it is quite straightforward: https://github.com/expo/expo/blob/949423c523306cee61c3bc453b574c688d9e3826/packages/expo-notifications/ios/EXNotifications/EXBadgeModule.m#L19-L34 - it calls `setApplicationIconBadgeNumber`, [which has the side effect that you describe](http://www.openradar.appspot.com/32972838).

One thing you could try is setting the value to -1 ([source: StackOverflow](https://stackoverflow.com/a/18961736/659988)). It also looks like iOS 16 may have introduced a new API that doesn't have this quirk ([source: also StackOverflow](https://stackoverflow.com/a/77967195/659988)).

cc @douglowder

**Comment by kaitlyn-lighthouse** [comment]
Setting the value to -1 does seem to work, thank you! It would be great to add a note in the docs if possible so that others don't have the same issue

**Comment by brentvatne** [comment]
@kaitlyn-lighthouse - makes sense! can you send a pull request for that?
