### ISSUE TITLE
[experiments.baseUrl] External URL -> Duplicate folder structure 

### ISSUE THREAD

**Issue by biller-aivy** [expo/expo#28649]
### Summary

The new metro web bundler has a bug: 

When basePath is specified as an external URL, the assets are created in a subFolders. 
As a result, when the script is executed on an external website, the external page searches for https://content.app/assets/... but the content is actually at https://content.app/contentapp/assets.... hosted. 

### What platform(s) does this occur on?

Web

### SDK Version

50

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.17 => 50.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: ~0.19.6 => 0.19.11
    Expo Workflow: managed

### Minimal reproducible example

Just create a example expo app and add 

```
"experiments": {
      "baseUrl": "https://develop.some.app"
 }
```

@EvanBacon

**Comment by EvanBacon** [comment]
It seems like you're attempting to use baseUrl as an asset prefix for hosting on a CDN, this is not how it's intended to be used. We'll need to introduce a second option for configuring external asset prefixes.

**Comment by biller-aivy** [comment]
> It seems like you're attempting to use baseUrl as an asset prefix for hosting on a CDN, this is not how it's intended to be used. We'll need to introduce a second option for configuring external asset prefixes.

Yes, we offer our partner to add our app on their own pages. As example, https://webapp.aivy.app so there you can see the current webpack build but with the links as src in the scripts to our s3 hosted script.

**Comment by kouloughli-hemza** [comment]
> It seems like you're attempting to use baseUrl as an asset prefix for hosting on a CDN, this is not how it's intended to be used. We'll need to introduce a second option for configuring external asset prefixes.

Really need that functionality

**Comment by biller-aivy** [comment]
@EvanBacon maybe you can give me some advice, than I could try to develop it my myself.

**Comment by kouloughli-hemza** [comment]
any update on this one 🥲  @EvanBacon

**Comment by kouloughli-hemza** [comment]
any update for this @marklawlor please?

**Comment by raci-aivy** [comment]
Any update on this @EvanBacon? 

Would investigate to do a pull request. If you have tips where to start please share this with us.

**Comment by raci-aivy** [comment]
> It seems like you're attempting to use baseUrl as an asset prefix for hosting on a CDN, this is not how it's intended to be used. We'll need to introduce a second option for configuring external asset prefixes.

@EvanBacon  To be sure, is it planned that the second option will come? Are there any hints as to where we can provide support for a PR in the repository?

**Comment by jtomaszewski** [comment]
Anybody knows whether it's still true that the second option never really came? And thus serving an expo app with web SSR AND having assets placed on a CDN is impossible?
