### ISSUE TITLE
Expo SDK 51: Missing "Deprecations, renamings, and removals" section

### ISSUE THREAD

**Issue by fernandasecinaro** [expo/expo#28667]
### Summary

Hello, 

I read the Expo SDK 51 changelog and it mentions "Refer to the "Deprecations, renamings, and removals" section above for breaking changes that are most likely to impact your app." but i don't see any section with that name in the article :)

### Link to the related docs page

https://expo.dev/changelog/2024/05-07-sdk-51

**Comment by hevi08** [comment]
https://expo.dev/changelog/2024/05-07-sdk-51#deprecations-renamings-and-removals
