### ISSUE TITLE
Module '"../../node_modules/@types/expo"' has no exported member 'Icon'.

### ISSUE THREAD

**Issue by Xerus2000** [expo/expo#2867]
### Environment
```
  Expo CLI 2.6.0 environment info:
    System:
      OS: Linux 4.11 KDE neon 5.14
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    npmPackages:
      expo: ^31.0.5 => 31.0.5 
      react: ^16.6.3 => 16.6.3 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: ^2.18.3 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.6.0
```

### Steps to Reproduce

1. `git clone https://github.com/Xerus2000/react-native-typescript-template`
2. `git checkout expo-issue`
3. `tsc`

### Expected Behavior

Everything compiles fine

### Actual Behavior

The type definitions of expo do not declare icon, thus it fails: 
```
src/components/TabBarIcon.tsx:2:10 - error TS2305: Module '"../../node_modules/@types/expo"' has no exported member 'Icon'.

2 import { Icon } from 'expo'
           ~~~~


Found 1 error.
```

**Comment by ide** [comment]
The `@types/expo` package isn't maintained by the Expo team. Can you please bring this up or submit a quality PR to the people who've worked on this over on the DefinitelyTyped repo?

**Comment by wcandillon** [comment]
@ide Is it still on the case on expo SDK 33? Same error happens.

**Comment by ide** [comment]
With SDK 33 all of the APIs that are authored by Expo have types. For libraries like Icons, there might not be type definitions.

**Comment by wcandillon** [comment]
@ide thks a lot, I'm not able to build my TS project with expo 33, will file a separate issue.
