### ISSUE TITLE
expo-camera 15.0.4 does not return 'data' in BarcodeScanningResult

### ISSUE THREAD

**Issue by jordanSSI** [expo/expo#28671]
### Minimal reproducible example

https://github.com/jordandreassen/camera-test

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

barcodeScanningResult from CameraView does not return any 'data', just the barcode type, bounds etc.

<CameraView
          style={styles.camera}
          facing='back'
          onBarcodeScanned={(result) => {
            setShowScanner(false);
            console.log(result)
          }}
          barcodeScannerSettings={{
            barcodeTypes: ['ean13'],
          }}
        >
        </CameraView>
        
console.log outputs:
       
`       {"bounds": {"origin": {"x": 0.503399133682251, "y": 0.2688171863555908}, "size": {"height": 0.39584094285964966, "width": 0.12417763471603394}}, "cornerPoints": [{"x": 0.5033991402520154, "y": 0.6502986846868529}, {"x": 0.5957219076605399, "y": 0.664658125031103}, {"x": 0.6275767591372067, "y": 0.28813123145347164}, {"x": 0.5033991235769288, "y": 0.26881718620701023}], "target": 1299, "type": "org.gs1.EAN-13"}`
       
       
       
       

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      npm: 9.6.7 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.0 => 51.0.0 
      expo-router: ~3.5.10 => 3.5.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

N/A

**Comment by MSetnik** [comment]
+1

**Comment by MSetnik** [comment]
Still not working on expo: 51.0.1 and expo-camera: 15.0.5

**Comment by JoaoGFdev** [comment]
I'm encountering the same issue while using expo v51.0.0 and expo-camera v15.0.5.

**Comment by alanjhughes** [comment]
Please open a new issue, provide an example barcode which displays the problem and a minimal reproducible example. Closed issues are not monitored. Also note, if you are using expo go, it won't have received this change yet.

**Comment by wallid** [comment]
This is an example for me I was hoping to get the value of the ean13 in the data. Thanks for your time highly appreciated.
```js
import { CameraView, useCameraPermissions } from 'expo-camera';
import { useState } from 'react';
import { Button, StyleSheet, Text, View, Alert } from 'react-native';

// .... 

   const handleBarCodeScanned = (data) => {
    JSON.stringify(data);
    if (data.type === 'org.gs1.EAN-13') {
      setScannedBarcode(data);
      Alert.alert("Barcode Scanned", `${JSON.stringify(data)}`);
    }

  }


  return (
    <View style={styles.container}>
      <CameraView
        style={styles.camera}
        onBarcodeScanned={handleBarCodeScanned}
        barcodeScannerSettings={{ barcodeTypes: ['ean13'] }}
      >
        <Text style={styles.textOverlay}>Scanning for EAN-13 Barcodes...</Text>
      </CameraView>
      {scannedBarcode && (
        <Text style={styles.barcodeText}>Scanned: {scannedBarcode}</Text>
      )}
    </View>
  );
```

Barcode
![IMG_5368](https://github.com/expo/expo/assets/42964551/3583b786-8779-4b9e-84e5-938426e1d253)

App Screen
![Screenshot 2024-05-14 at 09 04 54](https://github.com/expo/expo/assets/42964551/ce1b4bb4-5a00-4996-b430-3770448f67e2)

**Comment by ezoharSB** [comment]
Same issue for me with expo v51.0.0 and expo-camera v15.0.9. Not sure what target is and no "data" param is coming through.
