### ISSUE TITLE
Expo Font : getting "Unrecognized font family" error

### ISSUE THREAD

**Issue by davidjtorres** [expo/expo#2868]
Loading a font this way:

import { Font } from 'expo';

...

  async componentDidMount() {
        
        await Font.loadAsync({
            'Sailec': require('assets/fonts/Sailec-Regular.ttf')
        });

        this.setState({ fontLoaded: true });
    }

Then in Text component:

                    <Text style={{fontFamily: 'Sailec'}>....</Text>

I'm getting "Unrecognized font family 'Sailec' "  

I'm using SDK 31.0.0

**Comment by watanabeyu** [comment]
@davidjtorres You use `Font.loadAsync` before `<Text>` mounted.  
So change below.

```jsx
...
async componentDidMount() {
  await Font.loadAsync({
      'Sailec': require('assets/fonts/Sailec-Regular.ttf')
  });

  this.setState({ fontLoaded: true });
}

render(){
  if (!this.state.fontLoaded){
    return null;
  }

  return (
    <Text style={{fontFamily: 'Sailec'}>....</Text>
  )
}
```

**Comment by davidjtorres** [comment]
@watanabeyu  Sorry i didn't post the complete code, i actually have it like:

`render(){
       return this.state.fontLoaded ? (<App>) : null
}`

**Comment by EvanBacon** [comment]
Almost every project does this without a problem. Please ensure the fonts are not being used before they are loaded: https://snack.expo.io/Hy9HFJG4X

**Comment by quinlanj** [comment]
hi @davidjtorres , can you let us know if the proposed solutions work for you? If not, please provide a demo (snack.expo.io) where we can reproduce your problem. Thanks!

**Comment by davidjtorres** [comment]
hi @quinlanj , no, still having the issue.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Please create a new issue with a full repro case (ideally a [snack](https://snack.expo.io)) if this still happens in any of the currently supported SDK versions. Thanks!
