### ISSUE TITLE
Expo-Speech @ 51 fails on web with error: _ExponentSpeech.default.listenerCount is not a function

### ISSUE THREAD

**Issue by alyxb** [expo/expo#28694]
### Minimal reproducible example

https://github.com/alyxb/expo-speech-bug

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Get a Speech.speak() error in Expo 51 when running a simple speak command on Web (Chrome Version 124.0.6367.119 (Official Build) (arm64)):

```
   import * as Speech from "expo-speech";

   //...//

   const thingToSay = "1";
   Speech.speak(thingToSay);
```

This error is present in `expo-speech@12.0.1`, but not in `expo-speech@11.7.0`. 

12.0.1 is the default in Expo 51.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.0 => 51.0.0
      expo-router: ~3.5.10 => 3.5.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

**Comment by brentvatne** [comment]
this is fixed in the latest version of expo-speech, get it with `npx expo install --fix`
