### ISSUE TITLE
React native maps / Location API (?) : longitude and latitude values are objects instead of numbers

### ISSUE THREAD

**Issue by paschaldev** [expo/expo#2869]
I have a map view from expo and I need to pass Longitude and Latitude to the `MapView.Circle` component but the app crashes if I try to set it from the values in a variable destructured from the state.

I have already gotten my logic to get the current location which looks like this: 

```
Object { "latitude": 7.856788887819656, "latitudeDelta": 0.010894236067775509, "longitude": 8.419568594545126, "longitudeDelta": 0.0076499953866009385, }
```

Now when I set the `LatLng` variable like this: 

```
let LatLng = {

            latitude: location.latitude,
            longitude: location.longitude
}
```

Then I pass this value to `MapView.Circle` like this: 

```
<MapView.Circle 
                    key={ (region.longitude + region.latitude).toString() }
                    center={LatLng} 
                    fillColor="rgba(169,218,255, 0.3)"
                    strokeColor="rgba(169,218,255, 0.8)"
                    radius={200}
                />
```

Unfortunately, the app crashes with this error 

![image](https://user-images.githubusercontent.com/13323281/49312089-507e2d00-f4e3-11e8-8d97-815101ba21ac.png)

However when I set the `LatLng` variable with the numbers directly, it works and doesn't crash: 

```
let LatLng = {

            latitude: 7.856788887819656,
            longitude: 8.419568594545126
}
```

**Comment by paschaldev** [comment]
Further investigation, I checked the value of `longitude` using the `typeof` operator and it's returning an object instead of a number that was shown in the console log.

Here is how I bypassed the issue... 

```
let latlng = {

            latitude: parseFloat( region.latitude.toString() ) || 0,
            longitude: parseFloat( region.longitude.toString() ) || 0
        }
```

Can somebody please explain to me why it's an object however the log is showing a number???

**Comment by quinlanj** [comment]
hi @paschaldev , could you elaborate where the `object` longitude/latitude values are coming from? I am trying to reproduce your problem here https://snack.expo.io/@quinlanj/location.getcurrentpositionasync-example and it is returning type `number` for me.

**Comment by quinlanj** [comment]
a snack repro would be helpful! :)

**Comment by paschaldev** [comment]
I think I found the problem. It was an error from my end.
