### ISSUE TITLE
[ios] FontAwesome5 does not import properly with SDK 51

### ISSUE THREAD

**Issue by anthonyn60** [expo/expo#28693]
### Minimal reproducible example

https://github.com/anthonyn60/font-repro

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Fonts and icons don't load when imported from `FontAwesome5`. The font falls back to the default, while the icon will show a square with a question mark in it.

<img width="405" alt="Screenshot 2024-05-08 at 4 40 49 PM" src="https://github.com/expo/expo/assets/6720451/46a728ef-1c42-4a4a-a3d2-a9e3b08b3274">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v21.6.1/bin/yarn
      npm: 10.6.0 - ~/.nvm/versions/node/v21.6.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/opt/rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.0 => 51.0.0
      expo-router: ~3.5.10 => 3.5.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    npmGlobalPackages:
      eas-cli: 7.8.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

Anthonys-MacBook-Pro-2:font-repro anthonynguyen$ npx expo-doctor@latest

> font-repro@1.0.0 npx
> expo-doctor

(node:93133) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions

Didn't find any issues with the project!

**Comment by joonaathaan** [comment]
Same issue as well, sdk 51

**Comment by brentvatne** [comment]
i don't see any code related to FontAwesome5 in the repo you shared. i tried to reproduce this myself and it worked as expected

<img width="1238" alt="image" src="https://github.com/expo/expo/assets/90494/a1d633a1-a44e-482a-b06b-ce0cb82cbd57">


make sure that you are using a valid fontawesome5 icon name. if you typescript, it will validate that for you. check https://icons.expo.fyi/ for icons

**Comment by anthonyn60** [comment]
@brentvatne so I got your example working and am able to render the icons directly. I also was able to render the icon directly in my repro repo on the homepage.

However, there might be something going on with it handling dynamic props? The tab bar icon component still doesn't want to show the proper icon.

If it helps at all, the repro repo is the exact create expo app boilerplate on SDK 51 but swaps out the `Ionicons` icon pack for `FontAwesome5`.

**Comment by efstathiosntonas** [comment]
just linking this here: https://github.com/oblador/react-native-vector-icons/issues/1616

**Comment by efstathiosntonas** [comment]
@brentvatne after some investigation it seems that caching the `.ttf` breaks it.

If I remove this code everything works as it should: 

```tsx
function cacheFonts(fonts: any[]) {
  return fonts.map((font) => Font.loadAsync(font));
}

/* Load icons and fonts prior rendering the app */
async function loadResourcesAndDataAsync() {
  try {
    const fontAssets = cacheFonts([
      {
        "FontAwesome6Pro-Regular": require("../assets/fonts/FontAwesome6_Pro_Regular.ttf"),
        "FontAwesome6Pro-Light": require("../assets/fonts/FontAwesome6_Pro_Light.ttf"),
        "FontAwesome6Pro-Solid": require("../assets/fonts/FontAwesome6_Pro_Solid.ttf")
      }
    ]);

    await Promise.allSettled([...fontAssets]);
  } catch (e) {
    console.log(e);
  }
}
```

**Comment by tsapeta** [comment]
After some investigation, I also found out that loading only one font from FontAwesome5 works fine, i.e. this works

```ts
useFonts({
  'FontAwesome5Free-Solid': FontAwesome5.font['FontAwesome5Free-Solid'],
});
```

but this doesn't

```ts
useFonts({
  ...FontAwesome5.font,
});
```

The latter also tries to use some other variants like `FontAwesome5Free-Brand`, `FontAwesome5Free-Regular`, `FontAwesome5Free-Light`.

**Comment by tsapeta** [comment]
Quick update: we gave this issue a high priority and are investigating it intensively, but the problem looks a bit more complex than we thought initially 😅

**Comment by efstathiosntonas** [comment]
@tsapeta thank you! keep it up

**Comment by tsapeta** [comment]
I published the fix in `expo-font@12.0.5` 🎉 Please let me know if that solved the problem entirely in your projects 🙂

**Comment by pavelbabenko** [comment]
Note: to update `expo-font` to `12.0.5` you should run  `yarn add expo-font@next` for now

**Comment by brentvatne** [comment]
a new version of Expo Go with this fix is available for the iOS simulator, it'll be installed automatically when you launch your app to it through Expo CLI. the new version is waiting in review on the App Store, but you can get it from TestFlight external beta if you like: https://testflight.apple.com/join/GZJxxfUU

**Comment by fpinatares** [comment]
Thank you @tsapeta @brentvatne!!! Icons are back!! ❤️

**Comment by anthonyn60** [comment]
Thank you for the fix!

**Comment by anthonyn60** [comment]
As a heads up (an aside): Expo Go is still being a little funny with imported fonts (i.e. handling boldness when it's a bold and non-bold font imported) but it works fine in my development build.

**Comment by brentvatne** [comment]
@anthonyn60 - can you share a minimal reproducible example of that?

**Comment by csulit** [comment]
Still having issue with android.

**Comment by brentvatne** [comment]
@csulit - please share a minimal reproducible example and create a new issue

**Comment by anthonyn60** [comment]
Feel free to dismiss what I've mentioned as it's technically inside of some Tamagui classes I've been using and I'm unable to isolate it at this point

Setting boldness using a font style class works fine for me as well on both Expo Go and a development build

**Comment by csulit** [comment]
> @csulit - please share a minimal reproducible example and create a new issue, that appears to be something different than the topic of this issue

No significant changes were made to my source code. I used yarn to create my project with the expo-router template.

No problem when using the development build but we need expo go.

```
  const [loaded, error] = useFonts({
    SpaceMono: require('@/assets/fonts/SpaceMono-Regular.ttf'),
    PoppinsRegular: require('@/assets/fonts/Poppins-Regular.ttf'),
    PoppinsMedium: require('@/assets/fonts/Poppins-Medium.ttf'),
    PoppinsSemiBold: require('@/assets/fonts/Poppins-SemiBold.ttf'),
    PoppinsBold: require('@/assets/fonts/Poppins-Bold.ttf'),
    PoppinsExtraBold: require('@/assets/fonts/Poppins-ExtraBold.ttf'),
    ...FontAwesome.font,
  });
```

```
"expo-font": "^12.0.5",
"expo": "~51.0.2",
"react-native": "0.74.1",
```

FontAwesome5 importing from FontAwesome6?
![image](https://github.com/expo/expo/assets/31933946/484ff61b-0ad1-4d83-b7f8-9cdc3d08c0ea)

**Comment by brentvatne** [comment]
@csulit - did you perhaps not import FontAwesome5 properly? which version of `@expo/vector-icons` are you using? please share a project with a minimal reproducible example to reproduce that warning.

> No problem when using the development build but we need expo go.

as already mentioned in this thread:

> a new version of Expo Go with this fix is available for the iOS simulator, it'll be installed automatically when you launch your app to it through Expo CLI. the new version is waiting in review on the App Store, but you can get it from TestFlight external beta if you like: https://testflight.apple.com/join/GZJxxfUU

**Comment by csulit** [comment]
> @csulit - did you perhaps not import FontAwesome5 properly? which version of `@expo/vector-icons` are you using? please share a project with a minimal reproducible example to reproduce that warning.
> 
> > No problem when using the development build but we need expo go.
> 
> as already mentioned in this thread:
> 
> > a new version of Expo Go with this fix is available for the iOS simulator, it'll be installed automatically when you launch your app to it through Expo CLI. the new version is waiting in review on the App Store, but you can get it from TestFlight external beta if you like: https://testflight.apple.com/join/GZJxxfUU

This is when I try to import FontAwesome5 by pressing control + space. Instead of pointing to FontAwesome5, it points to FontAwesome6. I am not sure if that makes sense.

`"@expo/vector-icons": "^14.0.2",`

![image](https://github.com/expo/expo/assets/31933946/6335ce75-3c24-4174-9cbf-e1574965b840)

**Comment by csulit** [comment]
> > @csulit - did you perhaps not import FontAwesome5 properly? which version of `@expo/vector-icons` are you using? please share a project with a minimal reproducible example to reproduce that warning.
> > > No problem when using the development build but we need expo go.
> > 
> > 
> > as already mentioned in this thread:
> > > a new version of Expo Go with this fix is available for the iOS simulator, it'll be installed automatically when you launch your app to it through Expo CLI. the new version is waiting in review on the App Store, but you can get it from TestFlight external beta if you like: https://testflight.apple.com/join/GZJxxfUU
> 
> This is when I try to import FontAwesome5 by pressing control + space. Instead of pointing to FontAwesome5, it points to FontAwesome6. I am not sure if that makes sense.
> 
> `"@expo/vector-icons": "^14.0.2",`
> 
> ![image](https://private-user-images.githubusercontent.com/31933946/329890512-6335ce75-3c24-4174-9cbf-e1574965b840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjA0ODMsIm5iZiI6MTcxNTU2MDE4MywicGF0aCI6Ii8zMTkzMzk0Ni8zMjk4OTA1MTItNjMzNWNlNzUtM2MyNC00MTc0LTljYmYtZTE1NzQ5NjViODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAwMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OWFlMGU2NDM2ZDRmM2FkNGE5YWMzOTU5MWI0OTJiNmI2MzdmY2Q1OWI2NGJjYjZhNDk2YzNmMzk3N2EwNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QI0JpgwOrlQYTKjWQ6Ao_yMbGSRIp2MFQ_qwOccByks)

Ooops after upgrading from 14.0.0 to 14.0.2 import issue was fixed. Kindly disregard @brentvatne thank you

**Comment by efstathiosntonas** [comment]
@brentvatne I'm using these versions on a bare react-native-module:

```json
    "expo-font": "12.0.5",
    "expo": "51.0.4",
    "expo-asset": "10.0.6",
    "expo-modules-core": "1.12.10",
    "react-native-vector-icons": "10.1.0"
```

And when the app is going to foreground from background I get a crash:

![Screenshot 2024-05-13 at 15 11 22](https://github.com/expo/expo/assets/717975/586a3e96-add2-4b90-a7d7-563d98be7166)

Let me know if you want any additional traces.

**Comment by tsapeta** [comment]
@efstathiosntonas I'm not able to reproduce it, can you provide a repro? Also, for me the patch you posted before doesn't solve the original problem 😅

**Comment by brentvatne** [comment]
An updated version of Expo Go is now available on the App Store, version 2.31.5. This includes the expo-font fix from #28747 and resolves this issue.

**Comment by efstathiosntonas** [comment]
@tsapeta @brentvatne 

I just realized that it crashes when I use this in App.tsx:


```tsx
function cacheFonts(fonts: any[]) {
  return fonts.map((font) => Font.loadAsync(font));
}

/* Load fonts prior rendering the app */
async function loadResourcesAndDataAsync() {
  try {
    const fontAssets = cacheFonts([
      {
        "FontAwesome6Pro-Regular": require("../assets/fonts/FontAwesome6_Pro_Regular.ttf"),
        "FontAwesome6Pro-Light": require("../assets/fonts/FontAwesome6_Pro_Light.ttf"),
        "FontAwesome6Pro-Solid": require("../assets/fonts/FontAwesome6_Pro_Solid.ttf")
      }
    ]);

    await Promise.allSettled([...fontAssets]);
  } catch (e) {
    notify(e, "error", "error while loading resources on initialize app");
    console.log(e);
  }
}
```


```tsx
  useAsync(async () => {
    await loadResourcesAndDataAsync().catch();
  }, []);
```
If I comment out ` await loadResourcesAndDataAsync().catch();` then it won't crash.

**Comment by ShaoGongBra** [comment]
I encountered the same problem on RN0.75.2 expo font 12.0.10 expo 51.0.32

**Comment by gpawlik1** [comment]
@ShaoGongBra do you have any update on this?
