### ISSUE TITLE
After update to expo version 18, android expo client stopped working 

### ISSUE THREAD

**Issue by Shamash2014** [expo/expo#287]
After updating to latest expo (expo 18), got this error on Android expo client:

```
Networking.sendRequest got 9 agruments, expected 8

```

Android client expo version is 1.17.0
Android version 6.0
Kernel version 3.18.19+

**Comment by dikaiosune** [comment]
Hi! Please make sure to update the client app from the play store, as it needs to be >=1.18.0 to support SDK 18. Thanks!

(please report back if that doesn't resolve your issue, and we'll reopen)
