### ISSUE TITLE
WebBrowser Module: reloads entire WebView on dismiss with useWebKit prop

### ISSUE THREAD

**Issue by nelsonchen5** [expo/expo#2870]
### Steps to Reproduce

In Expo31, when opening a link using Expo's WebBrowser over a WKWebview, when the WebBrowser is dismissed, it reloads the entire WebView. 

1. Application opens in a WKWebview
2. A link is opened using Expo's WebBrower
3. On dismiss, the entire Webview is reloaded
4. This only happens on WKWebview, when removing the 'useWebKit' prop, it behaves as expected

### Expected Behavior

The expected behavior was that Expo's WebBrowser would open on top of the WKWebview, then when the WebBrowser is dismissed, you can resume on the page you were at in the WKWebview

![](https://media.giphy.com/media/POJ76ikmc4luZoJpAp/giphy.gif)

### Actual Behavior

When the Expo WebBrowser is dismissed, the entire WebView is reloaded
![](https://media.giphy.com/media/41xwqQwONyIrImG9hI/giphy.gif)

### Reproducible Demo
https://snack.expo.io/@nelsonchenruntriz/smiling-candy

**Comment by ndamofli** [comment]
Any ideas on how to solve this ?

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
