### ISSUE TITLE
[sdk 51] react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.

### ISSUE THREAD

**Issue by joonaathaan** [expo/expo#28705]
### Minimal reproducible example

https://github.com/joonaathaan/expo-mapview

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

the issue started happening right after i migrated to the latest sdk so i set up a new environment with these steps
- npx create-expo-app@latest
- yarn set version berry
- yarn
- yarn expo install react-native-maps
- set up your googleMapsApiKey in app.json with the required bundleIdentifier

note that im using vscode

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 4.2.1 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.1 => 51.0.1 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by samugit83** [comment]
I've the same problem, the version 50 was ok.

**Comment by janis-ax** [comment]
> I've the same problem, the version 50 was ok.

Same.

**Comment by TadeoJG** [comment]
Same! +1

**Comment by elisabeth0bangoura** [comment]
Same +1

**Comment by vinceprofeta** [comment]
same +1

**Comment by vecchp** [comment]
Same +1

**Comment by brentvatne** [comment]
Hi there! **Google Maps is no longer supported in Expo Go for iOS.** You can use Apple Maps in Expo Go instead (remove the prop `provider={PROVIDER_GOOGLE}` from your `<MapView /> ` components) or switch to a development build (recommended). If you have already configured Google Maps for your production releases, no additional configuration will be necessary. [Learn how to set up a development build](https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build).

A few things to note about Expo Go:

- Expo Go is intended to be a sandbox environment, and we recommend using development builds for any real app. The ["Set up your environment" guide](https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=physical&mode=development-build) will help you get set up with a development build. We also have a full [EAS tutorial](https://docs.expo.dev/tutorial/eas/introduction/) if you want to learn more, and [a concise video course](https://egghead.io/courses/build-and-deploy-react-native-apps-with-expo-eas-85ab521e) that you can pick and choose lessons from as they are relevant to your use case.
- Development builds give you full control over the native runtime (you can write native code or include any library you like), they are much closer to your production environment, and you can update SDK versions at whichever pace works for you.
- You can still install Expo Go for any SDK version on Android emulators, Android devices, and iOS simulators. We've made the process for doing this as easy as possible on https://expo.dev/go.

**Comment by edgarscr** [comment]
I disable the provider, but onMapLoaded never call the function 

```
<MapView
                                        ref={mapRef}
                                        initialRegion={
                                            selectedRouteIsEvent
                                                ? {
                                                      latitude: newPosition.latitude
                                                          ? Number(newPosition.latitude)
                                                          : 27.504044,
                                                      longitude: newPosition.longitude
                                                          ? Number(newPosition.longitude)
                                                          : -89.0982994,
                                                      latitudeDelta: LATITUDE_DELTA,
                                                      longitudeDelta: LONGITUDE_DELTA,
                                                  }
                                                : preRoutes.find(
                                                      route => route.routeId == selectedRouteId,
                                                  )?.initialRegion || {
                                                      latitude: newPosition.latitude
                                                          ? Number(newPosition.latitude)
                                                          : 27.504044,
                                                      longitude: newPosition.longitude
                                                          ? Number(newPosition.longitude)
                                                          : -89.0982994,
                                                      latitudeDelta: LATITUDE_DELTA,
                                                      longitudeDelta: LONGITUDE_DELTA,
                                                  }
                                        }
                                        mapType="standard"
                                        //provider={PROVIDER_GOOGLE}
                                        style={MapViewStyle.mapView}
                                        onMapLoaded={() => {
                                            console.log('onMapLoaded')
                                            if (!mapDataLoaded) {
                                                setMapDataLoaded(true)
                                                //animateMap(newPosition.latitude, newPosition.longitude);
                                            }
                                        }}
                                        onRegionChangeComplete={onRegionChangeComplete}
                                        onPanDrag={() => {
                                            mapPositionFixed.current = false
                                        }}
                                        showsUserLocation={true}
                                        showsMyLocationButton={true}
                                        showsTraffic={true}
                                        loadingEnabled={true}
                                        zoomEnabled={true}
                                        zoomControlEnabled={false}
                                        showsScale={false}
                                        showsCompass={false}
                                        userInterfaceStyle="light">
```

**Comment by WahidN** [comment]
> Hi there! **Google Maps is no longer supported in Expo Go for iOS.** You can use Apple Maps in Expo Go instead (remove the prop `provider={PROVIDER_GOOGLE}` from your `<MapView /> ` components) or switch to a development build (recommended). If you have already configured Google Maps for your production releases, no additional configuration will be necessary. [Learn how to set up a development build](https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build).
> 
> A few things to note about Expo Go:
> 
> * Expo Go is intended to be a sandbox environment, and we recommend using development builds for any real app. The ["Set up your environment" guide](https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=physical&mode=development-build) will help you get set up with a development build. We also have a full [EAS tutorial](https://docs.expo.dev/tutorial/eas/introduction/) if you want to learn more, and [a concise video course](https://egghead.io/courses/build-and-deploy-react-native-apps-with-expo-eas-85ab521e) that you can pick and choose lessons from as they are relevant to your use case.
> * Development builds give you full control over the native runtime (you can write native code or include any library you like), they are much closer to your production environment, and you can update SDK versions at whichever pace works for you.
> * You can still install Expo Go for any SDK version on Android emulators, Android devices, and iOS simulators. We've made the process for doing this as easy as possible on https://expo.dev/go.

I've done these steps and I followed these steps https://docs.expo.dev/versions/latest/sdk/map-view/ but I'm still this error

**Comment by quotentiroler** [comment]
I cannot confirm that Expo Go is only a sandbox. Does the development build also allow to see changes instantly?

**Comment by Tadeo-Guerstein** [comment]
> I cannot confirm that Expo Go is only a sandbox. Does the development build also allow to see changes instantly?

Yes it does, but if you want to add a new library you have to recompile the dev build

**Comment by komirellipavan** [comment]
> > Hi there! **Google Maps is no longer supported in Expo Go for iOS.** You can use Apple Maps in Expo Go instead (remove the prop `provider={PROVIDER_GOOGLE}` from your `<MapView /> ` components) or switch to a development build (recommended). If you have already configured Google Maps for your production releases, no additional configuration will be necessary. [Learn how to set up a development build](https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build).
> > A few things to note about Expo Go:
> > 
> > * Expo Go is intended to be a sandbox environment, and we recommend using development builds for any real app. The ["Set up your environment" guide](https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=physical&mode=development-build) will help you get set up with a development build. We also have a full [EAS tutorial](https://docs.expo.dev/tutorial/eas/introduction/) if you want to learn more, and [a concise video course](https://egghead.io/courses/build-and-deploy-react-native-apps-with-expo-eas-85ab521e) that you can pick and choose lessons from as they are relevant to your use case.
> > * Development builds give you full control over the native runtime (you can write native code or include any library you like), they are much closer to your production environment, and you can update SDK versions at whichever pace works for you.
> > * You can still install Expo Go for any SDK version on Android emulators, Android devices, and iOS simulators. We've made the process for doing this as easy as possible on https://expo.dev/go.
> 
> I've done these steps and I followed these steps https://docs.expo.dev/versions/latest/sdk/map-view/ but I'm still this error

Did you find the solution ?

**Comment by WahidN** [comment]
No, I went with Expo 50 and that works

**Comment by quotentiroler** [comment]
> > I cannot confirm that Expo Go is only a sandbox. Does the development build also allow to see changes instantly?
> 
> Yes it does, but if you want to add a new library you have to recompile the dev build

 Maybe I did something wrong, but I was not able to work on my code and see changes in real time using a development build.

**Comment by petemusicpancake** [comment]
Just faced with the same issue. "AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS".  in Release version. Version 51.0.28. 
Expo version - 50 works

**Comment by davidtiede** [comment]
**Environment:**
- Expo SDK: 51.0.14 to 51.0.28
- react-native-maps: 1.14.0 and 1.17.3
- `app.config.js` has the Google Maps API key set `ios.config.googleMapsApiKey`

**Steps:**
1. Delete `node_modules`
2. Run `npx expo prebuild --clean`
3. Run `npx expo run:ios -d`

**Issue:**
Same issue here. I’ve been using Expo 51 without problems until today. I regularly delete `node_modules`, run `prebuild --clean`, and run a development build on simulators and real devices. Today, Google Maps stopped working with the error: `react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS`. It seems like something external has changed, but I’m not sure what yet.

**Comment by techied** [comment]
Also seeing this error with a development build. I just updated from 51.0.26 to 51.0.28 and started seeing this

**Comment by besim10** [comment]
same here +1

**Comment by TarikMalek** [comment]
Same here +1

**Comment by ilyasssan2** [comment]
I am getting this error too, i didn't have it first when I upgraded to Expo 51, but after upgrading to "@shopify/flash-list": "^1.7.1" and generating a new development build I started getting this error

**Comment by ian** [comment]
I think the people want this feature back 🙋🏻

From a DX perspective, if you install `react-native-maps` the expectation is that it will behave the same on Expo Go as it does in production.

Not sure why this was removed but please consider fixing it. The above thread should be more than enough justification.

**Comment by besim10** [comment]
> I am getting this error too, i didn't have it first when I upgraded to Expo 51, but after upgrading to "@shopify/flash-list": "^1.7.1" and generating a new development build I started getting this error

I dont think that flashlist have to do something with this error, but i will try

**Comment by besim10** [comment]
> I think the people want this feature back 🙋🏻
> 
> From a DX perspective, if you install `react-native-maps` the expectation is that it will behave the same on Expo Go as it does in production.
> 
> Not sure why this was removed but please consider fixing it. The above thread should be more than enough justification.

It gives error on production and development build

**Comment by ilyasssan2** [comment]
> > I am getting this error too, i didn't have it first when I upgraded to Expo 51, but after upgrading to "@shopify/flash-list": "^1.7.1" and generating a new development build I started getting this error
> 
> I dont think that flashlist have to do something with this error, but i will try

Obviously

**Comment by ilyasssan2** [comment]
I just found a workaround that uses expo plugins to fix this issue
you need to copy this code
https://gist.github.com/lucasrose/d6c5355c3bead9c42bf9bb9c03a0f66d
and got to your app.json/app.config.ts and add ["./plugins/withReactNativeMapsWorkaround"] to your plugins array, then generate new dev build

**Comment by turi4200** [comment]
> I just found a workaround that uses expo plugins to fix this issue you need to copy this code https://gist.github.com/lucasrose/d6c5355c3bead9c42bf9bb9c03a0f66d and go to your app.json/app.config.ts and add ["./plugins/withReactNativeMapsWorkaround"] to your plugins array, then generate a new dev build

thanks a lot it worked!

**Comment by Kudo** [comment]
i'm sorry for introducing the breaking change. i've published #31036 to the latest template. now `npx prebuild` with react-native-maps should not have the problem.

**Comment by besim10** [comment]
@Kudo, what about us that we made build from expo, what should we do to get this error fixed?, i just upgraded expo from "expo": "^51.0.26", to "expo": "^51.0.28" (latest version) and i still get the same error ? TY in advice

**Comment by ilyasssan2** [comment]
> @Kudo, what about us that we made build from expo, what should we do to get this error fixed?, i just upgraded expo from "expo": "^51.0.26", to "expo": "^51.0.28" (latest version) and i still get the same error ? TY in advice

use this workaround https://github.com/expo/expo/issues/28705#issuecomment-2293775550

**Comment by besim10** [comment]
@ilyasssan2 it worked, thank u ✅

**Comment by TarikMalek** [comment]
> I just found a workaround that uses expo plugins to fix this issue
> 
> you need to copy this code
> 
> https://gist.github.com/lucasrose/d6c5355c3bead9c42bf9bb9c03a0f66d
> 
> and go to your app.json/app.config.ts and add ["./plugins/withReactNativeMapsWorkaround"] to your plugins array, then generate a new dev build

Thanks a lot !
This worked for me on iOS development simulator build.

**Comment by Thanemul-Islam** [comment]
@ilyasssan2 anyway can be more specific where I put the code and how to add the line of code you gave very new to this stuff so confusing

**Comment by ilyasssan2** [comment]
> @ilyasssan2 anyway can be more specific where I put the code and how to add the line of code you gave very new to this stuff so confusing

You can go to app.json or app.config. {js/ts} If you have one inside the expo object add   ["./plugins/withReactNativeMapsWorkaround"]  to your "plugins" array after that create the plugins folder in the root of your project, then download this code https://gist.github.com/lucasrose/d6c5355c3bead9c42bf9bb9c03a0f66d and place it inside the folder and rerun a new build using eas

**Comment by KrastanD** [comment]
I don't think this should have been closed bc it still doesn't work correctly. 
You shouldn't have to add a workaround plugin. Expo has a built in config plugin that is supposed to do this: https://github.com/expo/expo/blob/bc997e4f985fff0cbf0812f46df81b970f2cf8d7/packages/%40expo/config-plugins/src/ios/Maps.ts. 
After running the workaround plugin you can look in the Podfile and see the following: 
```  
  use_expo_modules!
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated begin react-native-maps - expo prebuild (DO NOT MODIFY) sync-e9cc66c360abe50bc66d89fffb3c55b034d7d369
  pod 'react-native-google-maps', path: File.dirname(`node --print "require.resolve('react-native-maps/package.json')"`)
# @generated end react-native-maps
  config = use_native_modules!
```
Line 2 above is the line added by the workaround plugin, then you can see the same line on line 4 that was generated by expo prebuild.

**Comment by jpangelle** [comment]
These suggested fixes did not work for me. I tried running `npx expo prebuild --clean` and adding the workaround plugin. I am on expo `~51.0.38`.
