### ISSUE TITLE
Self-hosted assets not bundled properly if not also published to expo cdn

### ISSUE THREAD

**Issue by tacomanator** [expo/expo#2871]
I am trying to self-host assets using `--public-url=...` to get around the expo cdn asset file size limit. I build locally with `turtle-cli,` but assets which are not also published to expo cdn have their contents replaced with XML such as:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

Example:

![asset_1143cae09b2a870a7df48e2312ef29b6](https://user-images.githubusercontent.com/63794/49322642-1d797080-f4c6-11e8-9fe6-159f9f5168a6.png)

Seems like this is coming from aws, as the build still tries to fetch assets from the expo cdn instead of the `--public-url` provided.

* expo: 2.6.0
* turtle: 0.3.6

## Steps to reproduce

* expo init and publish new project
* add a new asset (but don't publish)
* expo export --public-url=...
* upload assets to ...
* use turtle-cli to build with --public-url=...
* build succeeds
* unzip build file and inspect asset—it should be 243 bytes with XML above

**Comment by dsokal** [comment]
Hello @tacomanator,
this should be fixed in `turtle-cli@0.3.7`. Let me know if you're still experiencing the issue.
Thanks for finding this bug!

**Comment by tacomanator** [comment]
As a follow-up question, is it possible to have turtle use local assets (produced by expo export)?

Current process is:

* export assets with `export export --public-url ...`
* upload exported assets to remote
* `turtle build:...`, which re-downloaded the assets just uploaded

It would make the build go a lot faster if able to use the assets just exported directly, but I couldn't find an option.

**Comment by dsokal** [comment]
@tacomanator unfortunately it's not possible at the moment. However, it sounds like a great feature. I'll add it to our to-do list.
