### ISSUE TITLE
[sdk 51] useFonts is not found 

### ISSUE THREAD

**Issue by TatuninoDev12** [expo/expo#28718]
### Minimal reproducible example

all time

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

![image](https://github.com/expo/expo/assets/33699141/2d59d989-af85-4e47-a7db-644851e37722)

At the moment of loading the fonts, the useFonts gives the error message that can be seen in the following image

![image](https://github.com/expo/expo/assets/33699141/36cade82-9476-4dbc-8e0c-e6dec1bf6e94)

### Environment

![image](https://github.com/expo/expo/assets/33699141/4eef3dde-c10a-44d7-a1bc-8e6050708a4a)

### Expo Doctor Diagnostics

![image](https://github.com/expo/expo/assets/33699141/3f165dfb-9760-43b1-852c-f8b86c65d03d)

**Comment by raajnadar** [comment]
Did you add `expo-fonts` to `plugins` array in app.json before creating the dev build, we are using expo SDK 51 and everything is good for us.

**Comment by TatuninoDev12** [comment]
Yes, I have it added in the app.js

![image](https://github.com/expo/expo/assets/33699141/7a37ab00-73c1-4c2f-a040-a692b4505ed3)

**Comment by diceros-soojungkim** [comment]
anyone found an answer to this problem? I get the same problem.
