### ISSUE TITLE
[docs] Is it possible to create a native module with Java instead of Kotlin?

### ISSUE THREAD

**Issue by filippozanfini** [expo/expo#28710]
### Summary

The documentation doesn't explain how to create a native module with Java. I was wondering if it's possible to do this.

Thank you!

### Link to the related docs page

https://docs.expo.dev/modules/get-started/

**Comment by alanjhughes** [comment]
Hi @filippozanfini - It's not possible to create the module definition with Java but you can call other java code from your definition.
