### ISSUE TITLE
New template is not used in create-expo-app

### ISSUE THREAD

**Issue by Arctomachine** [expo/expo#28723]
### Summary

According to recent 51 announcement, new template should be used in `create-expo-app` (https://expo.dev/changelog/2024/05-07-sdk-51#new-default-project-template-and-%22getting-started%22-flow).
However old minimal template is still used when running this command.
I tried to clear package cache, use @latest, but still same old template.
![image](https://github.com/expo/expo/assets/29041820/d0ebaafd-e92a-44f0-a66b-c452efd64279)
![image](https://github.com/expo/expo/assets/29041820/24e0df00-d848-45bf-912c-8ee05388c6d4)

### SDK Version

51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD

### Minimal reproducible example

Just run `create-expo-app@latest`, it will reproduce

**Comment by brentvatne** [comment]
```
npx create-expo-app@latest --version
2.3.5
```

please share this output

**Comment by Arctomachine** [comment]
2.3.5 for npx, 2.1.1 for bunx which I used. I see where this issue comes from. I will inquire about this on bun side

**Comment by brentvatne** [comment]
sounds like an issue with bun caching the package then :) thanks for the follow up
