### ISSUE TITLE
[Android][expo-print] Text zoom option is needed for expo print

### ISSUE THREAD

**Issue by BatDroid** [expo/expo#28729]
### Minimal reproducible example

https://snack.expo.dev/2vdfwLlkCRjW8dPa8A75H

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

If the user use the android's accessibility in settings to increase font size through out the device, the output of expo-print is also scaled!

I'm using this tag inside the html and it works fine in IOS:

`<meta name="viewport" content="width=595, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />`

however on android, it doesn't work and the only workaround I could reach was adding the below code in [this line](https://github.com/expo/expo/blob/46dc5b3f02fdeb125a178875210404f23d83e150/packages/expo-print/android/src/main/java/expo/modules/print/PrintPDFRenderTask.kt#L43):

`webView.getSettings().setTextZoom(100);`

I believe we should have a `textZoom` option for android to be passed for android platform to prevent or control such a thing.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.6.1 - ~/.nvm/versions/node/v19.6.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v19.6.1/bin/yarn
      npm: 9.4.0 - ~/.nvm/versions/node/v19.6.1/bin/npm
      Watchman: 2023.11.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 28, 33, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.2
        System Images: android-22 | Google APIs ARM 64 v8a, android-23 | ARM 64 v8a, android-28 | ARM 64 v8a, android-UpsideDownCake-ext5 | Google APIs ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.5.0 => 9.5.1
      expo: ^49.0.0 => 49.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
      react-native-web: ~0.19.6 => 0.19.7
    npmGlobalPackages:
      eas-cli: 7.2.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by brentvatne** [comment]
@BatDroid - hey there! we usually keep feature requests to https://expo.canny.io/feature-requests -- this issue tracker is meant for bug reports. if you'd like to open a pull request to add this feature it'd be great!
