### ISSUE TITLE
Modal presentation opens as a stack push on Android

### ISSUE THREAD

**Issue by diemer** [expo/expo#28731]
### Minimal reproducible example

https://github.com/diemer/expo-router-modal-android-issue

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When implementing the base level of functionality the code examples provided in the [documentation](https://docs.expo.dev/router/advanced/modals/), the modal screen appears to just open as a new screen pushed on to the stack instead of being presented modally.

The only changes to the documented examples were changing the name `home` to `index` so the app wouldn't complain about an unknown route.

Video example:

https://github.com/expo/expo/assets/321477/66371446-ce1d-49e3-9c67-8e4ddba78c9c

### Environment

    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.0.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /var/folders/bg/7clh_l5s0s7_tt1v85ybq8hw0000gn/T/frum_76579_1715286046056/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2
      expo-router: ~3.5.11 => 3.5.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    npmGlobalPackages:
      eas-cli: 7.1.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by brentvatne** [comment]
this is the expected behavior as per react-native-screens/react-navigation: https://github.com/software-mansion/react-native-screens/issues/1650

you may want to use a bottom sheet library to accomplish this sort of behavior: https://github.com/gorhom/react-native-bottom-sheet

**Comment by diemer** [comment]
Makes sense now that I know. I wonder if the documentation should be updated to mention that a modal is only a modal on iOS, given that nothing there really drives you to the react navigation docs if you (like me) weren't already aware.

**Comment by evelant** [comment]
I'm glad I stumbled across this while looking for clues to https://github.com/expo/expo/issues/29273 because I just started setting up some modal routes while testing on iOS and had no idea they wouldn't work the same on Android. The docs could use an update!
