### ISSUE TITLE
crash on launch on ios since upgraded to Expo 50

### ISSUE THREAD

**Issue by Mobu34** [expo/expo#28733]
### Minimal reproducible example

can't because issue happens only in TestFlight

### Did you reproduce this issue in a development build?

Yes

### Summary

Upgraded my app from Expo SDK 49 to 50 and then submitted to AppStore, wanted to test it like usual using TestFlight but it immediately crashes (no issue on Android).

I just followed this process to upgrade it [](https://expo.dev/changelog/2024/01-18-sdk-50#%E2%9E%A1%EF%B8%8F-upgrading-your-app)
Here is my dependencies and devDependencies from my package.json : 
`"dependencies": {
    "@expo-google-fonts/montserrat-alternates": "^0.2.3",
    "@expo-google-fonts/righteous": "^0.2.3",
    "@expo/vector-icons": "^14.0.0",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-masked-view/masked-view": "0.3.0",
    "@react-native-picker/picker": "2.6.1",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@reduxjs/toolkit": "^1.9.5",
    "configcat-js": "^9.4.0",
    "date-fns": "^2.30.0",
    "expo": "^50.0.18",
    "expo-barcode-scanner": "~12.9.3",
    "expo-camera": "^14.1.3",
    "expo-constants": "~15.4.6",
    "expo-device": "~5.9.4",
    "expo-font": "^11.10.3",
    "expo-linear-gradient": "~12.7.2",
    "expo-status-bar": "~1.11.1",
    "firebase": "^10.4.0",
    "lottie-react-native": "6.5.1",
    "react": "18.2.0",
    "react-hook-form": "^7.47.0",
    "react-native": "0.73.6",
    "react-native-modal": "^13.0.1",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-toast-message": "^2.2.0",
    "react-native-uuid": "^2.0.1",
    "react-native-webview": "13.6.4",
    "react-redux": "^8.1.2",
    "reactotron-react-native": "^5.0.3",
    "reactotron-redux": "^3.1.3",
    "redux-persist": "^6.0.0",
    "styled-components": "^6.0.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "@types/react-redux": "^7.1.26",
    "@types/styled-components": "^5.1.27",
    "typescript": "^5.3.0"
  },`

I have no clue where the issue comes from, it works again when I downgrade my app back to SDK 49.
I don't have any issue using Expo Go or in dev build mode.

Have you ever faced this ?

### Environment

System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.18 => 50.0.18 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.5.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by lhguerra** [comment]
Having the same issue

**Comment by DengpaoHuai** [comment]
Same issue

**Comment by Mobu34** [comment]
Hello @lhguerra @DengpaoHuai 
Do you use reactotron and redux ?
Because in my case, the issue was caused by those, it looks like the configuration for reactotron with redux has changed since Expo 50.
I simply removed everything that concerns reactotron for now, I will try to re-setup a new configuration later.
