### ISSUE TITLE
Expo SDK 51.0.1  CameraView onBarcodeScanned BarcodeScanningResult.data returns 'undefined' for  type 'org.gs1.EAN-13'

### ISSUE THREAD

**Issue by makknife** [expo/expo#28741]
### Minimal reproducible example

close it then i guess

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I upgraded expo from SDK 49.0.0to SDK 51.0.1 and my iOS phone on 17.4.1 no longer is able to scan EAN13 barcodes.

onBarcodeScanned BarcodeScanningResult.data returns undefined when scanning a EAN13 barcode
However, I am able to scan other barcodes i.e. UPCA

 LOG  11:57:56 PM | DEBUG : type: org.gs1.EAN-13
 LOG  11:57:56 PM | DEBUG : data: undefined

I do not have the issue on my Android 14.0 phone

Here are some snipets

```

export default function App() {
....
  const handleBarCodeScanned = ({ type, data }) => {
    log.debug('scanned!')
    log.debug(`type: ${type}`)
    log.debug(`data: ${data}`)
...
  return (
    <View style={styles.container}>
      <CameraView
        style={StyleSheet.absoluteFillObject}
        facing={facing}
        barCodeScannerSettings={{
          barCodeTypes: [
            BarCodeScanner.Constants.BarCodeType.upc_a,
            BarCodeScanner.Constants.BarCodeType.ean13,
            BarCodeScanner.Constants.BarCodeType.ean8,
            BarCodeScanner.Constants.BarCodeType.upc_e,
            BarCodeScanner.Constants.BarCodeType.qr
          ],
        }}
        onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
      >

```

Also,

what is onModernBarcodeScanned for iOS used for?
onModernBarcodeScanned={scanned ? undefined : handleBarCodeScanned}

setting onModernBarcodeScanned instead of onBarcodeScanned does not do anything in my case

Thanks

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.2 - /opt/homebrew/bin/node
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.3/15E5202a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.2 => 51.0.2
      react: ^18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: ^0.74.1 => 0.74.1
      react-native-web: ^0.19.11 => 0.19.11
    npmGlobalPackages:
      eas-cli: 9.0.2
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

(node:76196) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by andrconstruction** [comment]
Yes , have same problem on IOS ean13 scan returns undefined
