### ISSUE TITLE
Setting pictureSize on the Camera doesn't really affect the size of the image taken

### ISSUE THREAD

**Issue by bberak** [expo/expo#2874]
### Environment

```  
Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      npm: 5.6.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.2 AI-145.3537739
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.1
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.18.0 => 2.18.0
    npmGlobalPackages:
      expo-cli: 2.3.8

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/bberak-d7a0d137-25a7-43ea-9878-51ff2b1ff551.tar.gz
```

```iOS - using iPhone SE with iOS 12.1```

### Steps to Reproduce

1. Run the following snack on a physical device: https://snack.expo.io/@bberak/photo-size-bug .The snack is a copy + paste of the camerja example - with a simple alert for printing the size of the take photo.
2. Open the photo size menu (```...```  on the bottom left).
3. Select various photo size and take a snap. 
4. After each snap, you will see an alert box that prints the widht and height of the photo. 

### Expected Behavior

I expect the size output from the alert box to correlate somewhat with the selected photo size in the menu. Eg, taking a '1280x720' shot would result in a photo that is 720 in width and 1280 in height (in portrait mode).

### Actual Behavior

The size of the photo is always 2304 x 4090 (approx) in portrait mode - regardless of the selected photo size in the menu. If you take the photo in landscape mode, the photo is always 4090 x 2304 (approx).

### Reproducible Demo

https://snack.expo.io/@bberak/photo-size-bug

### Huge Thanks

Huge thanks for creating a great platform - and let me know if I can provide any more info.

**Comment by sjchmiela** [comment]
Hey, @bberak! Thank you for submitting this issue! I've just reproduced the problem, you're absolutely right. Sorry for the inconvenience!

Until we get to fixing this bug you could use `ImageManipulator` to resize the image to requested size. 🙂

**Comment by bberak** [comment]
All good @sjchmiela, thanks for the quick response. 

I'll check out the ```ImageManipulator``` - looks like that should do the trick in the mean time!

Cheers!

**Comment by ricardovf** [comment]
The pictureSize prop is not respected too on Android when useCamera2Api is true.

**Comment by impactcolor** [comment]
Has this been fixed?

**Comment by jonasb** [comment]
Can reproduce on Android and iOS with expo 36. (Only tested in portrait)

**Comment by kevintbradbury** [comment]
pictureSize appears to affect the preview resolution of the camera within the app, at least in iOS, but does not change the captured image size.

**Comment by puuuudding** [comment]
The issue still exists. I need to use `ImageManipulator` to process the image taken on iOS

**Comment by RdC1965** [comment]
The issue still exists in iOS. I get a narrow format in landscape mode (1272x4032), difficult to crop with `ImageManipulator` to 4:3 ratio without leaving out a substantial part of the picture.

`iOS 14.8 on an iPhone 6s`

**Comment by lindboe** [comment]
Issue still exists.

**Comment by Uture** [comment]
Same issue on web. The size of the taken picture via mobile (brower) and on MacBook Pro is always 640x480 for me, the devices support 4k though. Will this be addressed?

**Comment by ericlifs** [comment]
After two years, this issue is still happening on both iOS and android with camera2Api set to true.

The way I fixed it on iOS is to set the Camera component's width and height to the same aspect ratio I want the output to have. For example if I want to have a 1:1 image as an output then I set the Camera's width and height to be the width of the viewport:

```
if (mode === CameraMode.portrait) {
  return {
    width,
    height: (width * 3) / 2,
  };
}

if (mode === CameraMode.square) {
  return {
    width,
    height: width,
  };
}
```

Even though my iPhone X has a 400ish viewport width, the captured image has a 2376x2376 size so somehow magically it matches the aspect ratio I set.

And for Android I had to set the camera2Api to false because otherwise I'm getting an empty array as the result of calling `camera.getSupportedRatiosAsync()`. Idk if I'm missing something but the Camera doesn't seem to work very well on Android honestly.

Hope this helps someone.

Eric.

**Comment by natsukiai** [comment]
> Same issue on web. The size of the taken picture via mobile (brower) and on MacBook Pro is always 640x480 for me, the devices support 4k though. Will this be addressed?

Hey @Uture, I have the same issue. Did you found a solution or a workaround since ?

**Comment by Uture** [comment]
Hi! Sadly no, I switched to ReactJs...

Natalie Rouvière ***@***.***> schrieb am Fr., 18. Feb. 2022,
12:36:

**Comment by natsukiai** [comment]
> Hi! Sadly no, I switched to ReactJs...

Thanks for the answer, I might switch too. :-(

**Comment by natsukiai** [comment]
I tried to directly call the ImageCapture API on `Platform.OS === 'web'`.
I discovered that the `640x480px` resolution was the same resolution returned by `ImageCapture.grabFrame()` and not `ImageCapture.takePhoto()` returning a full res jpeg Blob.

```js
log([`Awaiting picture to be taken...`]);

if (Platform.OS === 'web') {
  const mediaStream = await navigator.mediaDevices.getUserMedia({
    video: { facingMode: 'environment' },
  });

  const track = mediaStream.getVideoTracks()[0];
  const imageCapture = new ImageCapture(track);

  const blob = await imageCapture.takePhoto();

  log([`ImageCapture 'takePhoto' has fulfilled with blob:`, blob]);

  return blob;
}

const picture = await camera.takePictureAsync(options);

log([`Camera 'takePictureAsync' has fulfilled with picture:`, picture]);

return picture;
```

I've search in the package if maybe the takePicture method was using `grabFrame` on the web, but I've found nothing. Maybe it will be good to get a look on how pictures are taken from media stream. We can't just grab a frame to make a full res picture.

**Comment by Cleymi** [comment]
The problem still persists

**Comment by ymsstudios** [comment]
Any update on this? Was it ever fixed?

**Comment by ericmatte** [comment]
The problem is still present on iOS with `expo-camera ~13.2.1`.

**Comment by RodrigoBLISS** [comment]
Still present with expo-camera ~13.4.4 (Verified on iOS)

**Comment by ingfdoaguirre** [comment]
Hi, is still happening in expo camera 13.4.4, but for me, it happens randomly, not on all photos

I have sometime like this, I dont have usecameraAPi2 activated:

```
<Camera
      ....
      ratio={'16:9'}
      pictureSize="1280x720"
 />
```

And randomly I got photos in the max resolution that is 3840 x 2160

**Comment by luigijunge** [comment]
Same problem still on iOS.
Taken pictures are always the size I set the Camera components style width and height.
pictureSize doesn't do anything.
getAvailablePictureSizesAsync always returns undefined.

**Comment by brentvatne** [comment]
hey folks, fyi this is is resolved in expo-camera/next (sdk 50) and expo-camera (sdk 51): https://snack.expo.dev/@brents/photosize
