### ISSUE TITLE
[expo sdk 51]  update to react native 0.74.1 and expo 51 fails when running react-native run-ios

### ISSUE THREAD

**Issue by CostinBiserica** [expo/expo#28748]
### Minimal reproducible example

Not possible

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

After upgrading to RN 0.74.1 and Expo 51.0.0 the `react-native run-ios` command fails with some error generated by ExpoModulesCore. I tried to run the build directly from XCode and the build fails with the error:

> .../node_modules/expo-modules-core/ios/Core/Modules/CoreModule.swift:44:7 Cannot find 'RCTTriggerReloadCommandListeners' in scope

### Environment

 System:
      OS: macOS 14.3.1
      Shell: 5.9 
    Binaries:
      Node: 21.6.1
      Yarn: 1.22.22 
      npm: 10.2.4 
      Watchman: 2024.01.22.00 
    Managers:
      CocoaPods: 1.15.2 
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b 
    npmPackages:
      expo: ^51.0.0 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-navigation: 4.1.1 => 4.1.1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

-

**Comment by nicolascavallin** [comment]
Were you able to solve?

**Comment by kiet-ap** [comment]
+1
Cannot find 'RCTTriggerReloadCommandListeners' in scope

**Comment by kiet-ap** [comment]
did anyone solve this problem? 😿
@CostinBiserica
