### ISSUE TITLE
Expo Camera - requestPermission from useCameraPermissions does not work when the user manually turned off permission in iOS Settings.

### ISSUE THREAD

**Issue by robinderozario** [expo/expo#28757]
### Minimal reproducible example

https://github.com/robinderozario/CameraExample

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Steps to reproduce (with the minimal reproducible example).

0. After a fresh install of the app, accept the native permission prompt.
1. Turn off the camera permissions for the App in Settings.
2. Return to the app, run the callback "requestPermission" from the useCameraPermissions hook (e.g. using a Button).

Notice how permission.granted remains false.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.8.0 - /usr/local/bin/node
      npm: 10.2.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 7.7.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alanjhughes** [comment]
This is because if the user does this, iOS will not allow you to request them again. The user needs to enable from settings again. You can present a modal if `canAskAgain` is false to inform them

**Comment by alanjhughes** [comment]
Also, you should not pass children to the CameraView.

**Comment by robinderozario** [comment]
Re: ask again, that is totally clear. Thanks for explaining it to me!

Re: No children in CameraView. I'm just following the example on the expo
docs: https://docs.expo.dev/versions/latest/sdk/camera/. You might want to
consider updating this then.

**Comment by alanjhughes** [comment]
🤔 I'll check that out

**Comment by alanjhughes** [comment]
Can confirm the issue is caused by passing the children. I will get the docs updated
