### ISSUE TITLE
Expo Camera - BarCodeSettings interval has no effect

### ISSUE THREAD

**Issue by robinderozario** [expo/expo#28755]
### Minimal reproducible example

https://github.com/robinderozario/CameraExample

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Adjusting the `interval` parameter in the `BarcodeScannerOptions` does not affect the rate at which "onBarcodeScanned" callback is fired. In the following example, setting the interval to 1 or 1000 does not affect the scanning rate.

`const onBarcodeScanned = () => {console.log(Date.now());};`

	return (
		<View style={styles.container}>
			<CameraView
				style={styles.camera}
				facing={"back"}
				onBarcodeScanned={onBarcodeScanned}
				barcodeScannerSettings={{
					barcodeTypes: ["ean13", "ean8", "upc_a"],
					interval: 1000,
				}}
			></CameraView>
		</View>
	);

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.8.0 - /usr/local/bin/node
      npm: 10.2.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 7.7.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alanjhughes** [comment]
@robinderozario - Sorry, this property shouldn't have been included and will be removed.

**Comment by robinderozario** [comment]
Okay, good to know!

**Comment by MaxiARG** [comment]
is the "setTimeout" the way to go to replace this feature?

**Comment by Zhashkha** [comment]
Okay, interval is obsolete. Any suggestions on how to achieve the same effect?
