### ISSUE TITLE
Expo camera - permission status from useCameraPermissions is not updated when user gives permission in the native iOS prompt.

### ISSUE THREAD

**Issue by robinderozario** [expo/expo#28756]
### Minimal reproducible example

https://github.com/robinderozario/CameraExample

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

When the CameraView is mounted for the first time after a fresh install, the iOS prompts the user to give permission. If the user does give permission, the `permission` variable from `useCameraPermissions` is not updated. This can lead to situations where the "no permission" view is still shown even though the user just granted permission. 

See the minimal reproducible example for a case in which this happens. Ensure the app is installed fresh and check the logs.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.8.0 - /usr/local/bin/node
      npm: 10.2.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 7.7.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alanjhughes** [comment]
Hi - I've pulled your repro and I'm not seeing any problem. The granted property is set.

<img width="886" alt="Screenshot 2024-05-10 at 17 34 42" src="https://github.com/expo/expo/assets/30924086/db99c4d0-6e27-4bd6-8bad-cdffd2281233">

**Comment by robinderozario** [comment]
Hi - That is certainly interesting. When I reinstall the development build (fresh clone from the repo), I get the result as shown in the video below. Accepting the native prompt does not cause the permissions variable to update, as is evidenced by the "No access to camera" text in the middle of the screen. Could there be a difference between our development builds perhaps?


https://github.com/expo/expo/assets/66564342/1110f7f4-57fd-438f-9e40-4539c9f3beda

**Comment by alanjhughes** [comment]
The CameraView does not accept children. Can you move that outside and see if it's the same result?

**Comment by alanjhughes** [comment]
Have confirmed that removing the children from the CameraView fixes the problem. I will update the docs example
