### ISSUE TITLE
[expo-media-library][iOS] No suitable URL request handler found Expo 51

### ISSUE THREAD

**Issue by iM-GeeKy** [expo/expo#28772]
### Minimal reproducible example

https://github.com/iM-GeeKy/image-bug

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Starting in Expo 51 and on iOS only (Expo Go and Development Builds), it appears `MediaLibrary.getAssetsAsync` returns assets with a `uri` that contain `ph://` which conflicts with the documentation that says `URI that points to the asset. assets://* (iOS), file://* (Android)` and causes downstream issues as demonstrated in the sample repository provided, where it gets the first asset from your photos and tries to call `ImageManipulator.manipulateAsync` resulting in a the attached error (see below). 

Previously in Expo 50 this code worked as expected which is what should be expected in Expo 51. There appears to be an [old related issue](https://github.com/expo/expo/issues/15664), but considering this has worked for me up until Expo 51, it seems to be an issue.

<img src="https://github.com/expo/expo/assets/7604441/4a599ead-820c-4b7a-bbe1-f9ab5ee256ed" width="400"/>

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by AnatolyKostarev** [comment]
Have the same problem. Couldn’t resolve the problem

**Comment by alanjhughes** [comment]
Hi @iM-GeeKy - The issue is react native's Image component can't handle these urls. I will try to find a workaround but in the meantime expo image will accept these

**Comment by iM-GeeKy** [comment]
> Hi @iM-GeeKy - The issue is react native's Image component can't handle these urls. I will try to find a workaround but in the meantime expo image will accept these

Hey, I'm using `expo-image` in my app, but I'm using `ImageManipulator.manipulateAsync` beforehand to compress images before passing setting the `source` which is where it seems to blow up. Based on this [old issue](https://github.com/expo/expo/issues/15664) using [`getAssetInfoAsync`](https://docs.expo.dev/versions/latest/sdk/media-library/#medialibrarygetassetinfoasyncasset-options) seemed to work on iOS to get the `localUri` which seems to be in the old format, but then it creates problems on Android because it gets the location for that image which requires a permission and I didn't want to go that route.

**Comment by nagisaando** [comment]
Hello, I already upgraded `expo-image-manipulator` to use 12.0.5 but I still have the same problem. Is it something I have to wait until expo 52 is released?

**Comment by khushal87** [comment]
Hey @alanjhughes, this doesn't work on `12.0.5` and is still an issue. Do you have any insights?

**Comment by alanjhughes** [comment]
@khushal87 please provide a minimal example project that demonstrates the issue still exists and is the same problem as what this issue refers to.

**Comment by khushal87** [comment]
Hey @alanjhughes, This seems to be a bug with expo-media-library. PFA a minimum repro example repo - https://github.com/khushal87/expo-media-library-bug

I can raise a separate issue for the same as well.

**Comment by alanjhughes** [comment]
@khushal87 ok, it's a separate issue then, could you open a new issue for it and we can look into it 👍

**Comment by khushal87** [comment]
https://github.com/expo/expo/issues/29741

**Comment by fadihanna123** [comment]
Same issue.

**Comment by zfogg** [comment]
this issue still exists in 2025 😓
