### ISSUE TITLE
expo-font 12.0.5

### ISSUE THREAD

**Issue by rodrix** [expo/expo#28771]
### Minimal reproducible example

Install expo-font with the last published version 12.0.5

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

After upgrading to Expo SDK 51 and expo-font 12.0.5, the runtime starting to show some warning about font loading problems, as follow:

```
 WARN  fontFamily "entypo" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "material-community" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "material-community" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "feather" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "feather" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "octicons" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "octicons" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "octicons" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "octicons" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "material-community" is not a system font and has not been loaded through expo-font.
```
 
 The fonts are related to the @expo/vector-icons.
 
Downgrading to expo-font 12.0.4 solve the warning issues, but the metro bundler show another warning about version incompatibility:
 
```
 The following packages should be updated for best compatibility with the installed expo version:
  expo-font@12.0.4 - expected version: ~12.0.5
  Your project may not work correctly until you install the expected versions of the packages.
```

- [ ] 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 34.0.0
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.5 
      expo: 51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ^0.19.11 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 9.0.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by adolfalfred** [comment]
I'm getting the same issue after upgrading to SDK 51 and expo-font 12.0.5

**Comment by frykher** [comment]
I am getting the same issue as well. I've ran `npx expo install --fix` as well.

**Comment by pablobarreraf** [comment]
same issue as well after upgrading to expo 51

**Comment by sword-fish333** [comment]
yup, same issue here, and tried with Font.loadAsync and useFonts as the example in docs and the error still appears.
 WARN  fontFamily "Montserrat-Bold" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "Montserrat-Bold" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "Montserrat-Regular" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "Montserrat-Bold" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "Montserrat-Regular" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "Montserrat-Bold" is not a system font and has not been loaded through expo-font.
 WARN  fontFamily "Montserrat-Regular" is not a system font and has not been loaded through expo-font.

**Comment by charlestbell** [comment]
Same issue when upgrading to Expo 51. 

My code that worked in 50:

```
const fontImports = (() => {
  if (Constants.expoConfig.extra.APP_NAME === 'app1') {
    return {
      'title-font': require('./assets/fonts/Oswald-Regular.ttf'),
      'title-font-bold': require('./assets/fonts/Oswald-Bold.ttf'),
    };
  }

  if (Constants.expoConfig.extra.APP_NAME === 'app2') {
    return {
      'title-font': require('./assets/fonts/AbhayaLibre-Regular.ttf'),
      'title-font-bold': require('./assets/fonts/AbhayaLibre-Bold.ttf'),
    };
  }
})();

  // Load Fonts
  useEffect(() => {
    async function prepare() {
      try {
        // Pre-load fonts, make any API calls you need to do here
        await Font.loadAsync(fontImports);
      } catch (e) {
        console.log('Error', e);
      } finally {
        // Tell the application to render
        setAppIsReady(true);
      }
    }

    prepare();
  }, [])
  
  ```

**Comment by sword-fish333** [comment]
yes mate, this integration worked indeed, and its strage i had something very similar, but i used an iife. You put all the logic in a function and immediately invoked it. I dont know why it worked at you and at me it did not, but thank you very much

**Comment by pablobarreraf** [comment]
When Im debugging and previewing with expo go, sometimes the fonts do not load what helps is to delete all the data and cache from the app installed and after some time the fonts work again, it seems very random when and how they work, on dev builds they work without any problem but its very tedious to make a dev build everytime to test, that's why I debug on the expo go, maybe im ignoring something.

**Comment by sword-fish333** [comment]
try @charlestbell solution. Before this i always got the warning...font is not loaded(WARN  fontFamily "Montserrat-Regular" is not a system font and has not been loaded through expo-font.), and i tried multiple solution including downgrading expo-font to 11, and clearing cache.. but it still did not work. Now when the Font.loadAsync(fontImports) method is encapsulated within a function and subsequently invoked immediately, the issue is resolved.

**Comment by brentvatne** [comment]
hey folks, please run `npx expo install --fix` and ensure you are using expo go 2.31.5 on ios (assuming this is where you are experiencing the issue)

we just released the update version of expo go with this fix yesterday, it took a few days to be approved.

if you can still reproduce this, please share a minimal reproducible example. 

- i tried repro in a blank new app and i could not ([example App.js here](https://gist.github.com/brentvatne/f87304cd16701a390d363a3805dc66da))
- i tried to repro in the with-custom-font-example and noticed that the issue was because we were loading a font from a web url that doesn't exist anymore, so i removed that.

**Comment by GaeDLLD** [comment]
Issue since I update my project to Expo 51 with react-native 0.74 and expo-font 12.04... My custom .otf font is loading and displaying as requested on the first dev build on iOS (but with a dismissible error: CTFontManagerErrorDomain), and when I fast-reload my app, the text loose the custom font family and all others text styles... On Android, it doesn't work at all !

**Comment by mrnzdev** [comment]
When will be the Expo Go `2.31.5` version on android?, I am getting the same error even after running `npx expo install --fix`

**Comment by pablobarreraf** [comment]
it worked for me 2 days ago and now im seeing the same problem as @GaeDLLD

**Comment by pablobarreraf** [comment]
it was failing yesterday* and today its working fine again

**Comment by pablobarreraf** [comment]
3 days working failed again today

**Comment by nmclauchlan** [comment]
expo 51 broke this for me, but running `npx expo install --fix` fixed it.

**Comment by GaeDLLD** [comment]
> expo 51 broke this for me, but running `npx expo install --fix` fixed it.

I agree, all issues seem to be solved with `npx expo install --fix` and the update of expo@51.0.9 and expo-font@12.0.6

**Comment by oviirup** [comment]
In my case the error does not appear out of the blue. I installed `react-native-svg-transformer@1.4.0` and `react-native-svg@15.2.0`, and here is the `metro.config.js`

```js

const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

const { transformer, resolver } = config;

config.transformer = {
  ...transformer,
  babelTransformerPath: require.resolve('react-native-svg-transformer'),
};
config.resolver = {
  ...resolver,
  assetExts: resolver.assetExts.filter((ext) => ext !== 'svg'),
  sourceExts: [...resolver.sourceExts, 'svg'],
};

module.exports = withNativeWind(config, { input: './src/app/global.css' });

```

I am also using `nativewind@4`.

**Comment by rodrix** [comment]
The problem come back again after updating the expo-font package to expo-font to **12.0.10**

**Comment by Kyuorhan** [comment]
I have the same problem with the expo-font 12.0.10 version with SDK 51
