### ISSUE TITLE
Response in network tab is blob instead of json

### ISSUE THREAD

**Issue by Legend999** [expo/expo#28774]
### Minimal reproducible example

https://github.com/Legend999/expo-network-issue

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I've added the following code in `/app/index.tsx` to the fresh expo app to reproduce the issue:
```
useEffect(() => {
  const intervalId = setInterval(() => {
    fetch('https://jsonplaceholder.typicode.com/users/1').then((response) => {
      console.log(response);
      return response.json();
    }).then((data) => console.log(data));
  }, 5000);

  return () => clearInterval(intervalId);
}, []);
```
`console.log` outputs:
1. `console.log(response)`:
```
LOG  {"_bodyBlob": {"_data": {"__collector": [Object], "blobId": "6bf61669-7a86-4a6e-b09f-496702569a78", "offset": 0, "size": 509}}, "_bodyInit": {"_data": {"__collector": [Object], "blobId": "6bf61669-7a86-4a6e-b09f-496702569a78", "offset": 0, "size": 509}}, "bodyUsed": false, "headers": {"map": {"access-control-allow-credentials": "true", "age": "221", "alt-svc": "h3=\":443\"; ma=86400", "cache-control": "max-age=43200", "cf-cache-status": "HIT", "cf-ray": "88283673e94870bf-WAW", "content-type": "application/json; charset=utf-8", "date": "Sun, 12 May 2024 06:04:40 GMT", "etag": "W/\"1fd-+2Y3G3w049iSZtw5t1mzSnunngE\"", "expires": "-1", "nel": "{\"report_to\":\"heroku-nel\",\"max_age\":3600,\"success_fraction\":0.005,\"failure_fraction\":0.05,\"response_headers\":[\"Via\"]}", "pragma": "no-cache", "report-to": "{\"group\":\"heroku-nel\",\"max_age\":3600,\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?ts=1713690015&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=29gerBrApvQRq%2B0itdtaqYVc4anoxW0Q%2BIdX%2FMyDmlI%3D\"}]}", "reporting-endpoints": "heroku-nel=https://nel.heroku.com/reports?ts=1713690015&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=29gerBrApvQRq%2B0itdtaqYVc4anoxW0Q%2BIdX%2FMyDmlI%3D", "server": "cloudflare", "vary": "Origin, Accept-Encoding", "via": "1.1 vegur", "x-content-type-options": "nosniff", "x-powered-by": "Express", "x-ratelimit-limit": "1000", "x-ratelimit-remaining": "999", "x-ratelimit-reset": "1713690052"}}, "ok": true, "status": 200, "statusText": "", "type": "default", "url": "https://jsonplaceholder.typicode.com/users/1"}
```
2. `console.log(data)`:
```
LOG  {"address": {"city": "Gwenborough", "geo": {"lat": "-37.3159", "lng": "81.1496"}, "street": "Kulas Light", "suite": "Apt. 556", "zipcode": "92998-3874"}, "company": {"bs": "harness real-time e-markets", "catchPhrase": "Multi-layered client-server neural-net", "name": "Romaguera-Crona"}, "email": "Sincere@april.biz", "id": 1, "name": "Leanne Graham", "phone": "1-770-736-8031 x56442", "username": "Bret", "website": "hildegard.org"}
```
  
### Current behavior:

In expo go app after entering dev menu, opening inspector and selecting network tab, the response section shows the same thing as `response._bodyBlob` or `response._bodyInit` (blob type)

![438271606_1256594888650252_3230710465441643859_n](https://github.com/expo/expo/assets/28870018/ea523f78-975e-454b-b341-cbbcfab443ea)

### Expected behavior:

It should show the result of `console.log(data)` (= `response.json()`)

Please take a look at this or advise me on how to configure the project to get the proper response in the inspector.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.6 Ubuntu 23.10 23.10 (Mantic Minotaur)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      expo-router: ~3.5.11 => 3.5.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by byCedric** [comment]
Hi @Legend999, thanks for the issue report. Unfortunately, this built-in network inspector is rather old and likely has other issues. We are actively working on the more-up-to-date way of debugging, through the Chrome Devtools Protocol. You have more insights in the network tab there.

You can open this by starting your app as usual. After everything is running, you can press `j` in the terminal where you started Expo. This should open the debugger, including the network tab.

See [our docs](https://docs.expo.dev/debugging/tools/#inspecting-network-requests), [React Native docs](https://reactnative.dev/docs/debugging?js-debugger=hermes#opening-the-debugger).

Hope this helps!
