### ISSUE TITLE
[expo-51] Build error with PrivacyInfo.xcprivacy after upgrading to SDK 51

### ISSUE THREAD

**Issue by relez** [expo/expo#28780]
### Minimal reproducible example

npx expo run:ios

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

After upgrading to expo SDK 51 and re-building the ios folder, I am getting this error:

❌  error: Multiple commands produce '/Users/relvis/Library/Developer/Xcode/DerivedData/MyAppName-cfarerevlohcfbcondzqvmfzfczn/Build/Products/Debug-iphonesimulator/MyAppName.app/PrivacyInfo.xcprivacy'

I have added the "privacyManifests" object inside the app.json file and the PrivacyInfo.xcprivacy file resides inside the ios/MyAppName instead of ios/ folder. Is that OK?

Thanks in advance.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/lib/ruby/gems/3.3.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 32, 33, 34
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86_64 Atom, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64, android-33 | Android TV ARM 64 v8a, android-33 | Android TV Intel x86 Atom, android-33 | Google TV ARM 64 v8a, android-33 | Google TV Intel x86 Atom, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86 Atom_64, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.2 => 51.0.2
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ^0.19.11 => 0.19.11
    npmGlobalPackages:
      eas-cli: 9.0.3
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

**Comment by zachTrio** [comment]
Did you resolve this?

**Comment by ryan-reichenberg** [comment]
For me, one of my dependencies was missing a policy manfiest declaration:
https://docs.expo.dev/guides/apple-privacy/

Removing the dependency or updating should fix the build

**Comment by kukadiyaAni** [comment]
+1

**Comment by a-eid** [comment]
@ryan-reichenberg which dependency ?
