### ISSUE TITLE
expo-camera doesn't work 

### ISSUE THREAD

**Issue by yamadaOliva** [expo/expo#28792]
### Minimal reproducible example

sorry this privata project

### Did you reproduce this issue in a development build?

Yes

### Summary

2 months ago, my code runned exactly, now it can not show camera screen
// App.tsx
import { StatusBar } from "expo-status-bar";
import { StyleSheet, View } from "react-native";
import { useEffect, useState } from "react";
import { Camera, CameraType } from "expo-camera";
import { getProductBySku } from "@/services/product.service";
import { router } from "expo-router";
export default function App() {
  const [permission, setPermission] = useState<{
    isGranted: boolean;
    isChecked: boolean;
  }>({
    isGranted: false,
    isChecked: false,
  });
  useEffect(() => {
    Camera.getCameraPermissionsAsync().then(({ status }) => {
      console.log(status);
      setPermission({
        isGranted: status === "granted",
        isChecked: true,
      });
    });
  }, []);
  const getIdProduct = async (sku: string) => {
    const data = await getProductBySku(1, 1, sku);
    if (data && data.length > 0) {
      router.push({
        pathname: "/product/[slug]",
        params: { slug: data[0].id },
      });
    }
  };
  return (
    <View style={styles.container}>
      {permission.isGranted && (
        <Camera
          type={CameraType.back}
          ratio={"16:9"}
          style={styles.camera}
          onBarCodeScanned={async (scannerResult) => {
            await getIdProduct(scannerResult.data);
          }}
        />
      )}
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
});

### Environment

{
  "expo": {
    "name": "Việt Lạc Salerep",
    "slug": "vilapa-sale",
    "scheme": "myapp",
    "version": "1.1.2",
    "orientation": "portrait",
    "icon": "./assets/images/icon-test.png",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.vietlac.salerep",
      "buildNumber": "1.0.2",
      "runtimeVersion": {
        "policy": "appVersion"
      }
    },
    "android": {
      "versionCode": 2,
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon-android.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.vietlac.salerep",
      "permissions": [
        "android.permission.CAMERA",
        "android.permission.RECORD_AUDIO"
      ],
      "runtimeVersion": "1.0.0"
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      [
        "expo-camera",
        {
          "cameraPermission": "Allow $(PRODUCT_NAME) to access your camera",
          "microphonePermission": "Allow $(PRODUCT_NAME) to access your microphone",
          "recordAudioAndroid": true
        }
      ],
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 31,
            "targetSdkVersion": 31,
            "buildToolsVersion": "31.0.0"
          },
          "ios": {
            "deploymentTarget": "13.4"
          }
        }
      ]
    ],
    "experiments": {
      "typedRoutes": true
    },
    "extra": {
      "router": {
        "origin": false
      },
      "eas": {
        "projectId": "da8f4ae2-0dd3-4e49-bd98-7cbac3f55243"
      }
    },
    "updates": {
      "url": "https://u.expo.dev/7170736a-9fb4-412b-88ff-37b343854938"
    }
  }
}

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by conwayanderson** [comment]
Did you update to 51? Camera is now CameraView in 51 along with some other changes.
