### ISSUE TITLE
Expo Camera No Longer Captures Sound

### ISSUE THREAD

**Issue by DomGarza** [expo/expo#28796]
### Minimal reproducible example

https://github.com/DomGarza/expo-camera-next

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Expo no longers captures sound while recording after Expo SDK 51. Yes I changed the imports. I capture video, no sound, download video to my phone and it has no sound still. 

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 21.7.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD 
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD  
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    npmPackages:
      expo: ~51.0.4 => 51.0.4
      expo-router: ~3.5.12 => 3.5.12
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by alanjhughes** [comment]
Hi @DomGarza this was already fixed as part of this PR #28783. You can also explicitly set `mute={false}`
