### ISSUE TITLE
Static output for web not respecting public/index.html

### ISSUE THREAD

**Issue by sudhanshug16** [expo/expo#28807]
### Minimal reproducible example

https://github.com/sudhanshug16/expo-static-bug

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

Yes

### Summary

When `expo.web.output` is set to `static` in app.json with an ejected(using `yarn expo customize`) `public/index.html`, `expo export -p web` does not respect the ejected index.html file.

Observations during the build:
Initially the `public/index.html` is copied to the `dist` directory. When the build finishes this file is replaced with the statically generated file.

My use case is to change the meta viewport tag, lmk if there is an alternative way to do this. Thanks in advance!

### Environment

```  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.0 - ~/.asdf/installs/nodejs/20.12.0/bin/node
      Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.12.0/.npm/bin/yarn
      npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed```

### Expo Doctor Diagnostics

```✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/netinfo@11.3.1 - expected version: 11.1.0
  @sentry/react-native@5.22.2 - expected version: ~5.20.0
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.```

**Comment by byCedric** [comment]
Hi @sudhanshug16! Thanks for the issue report. The `expo customize public/index.html` was created way before Expo Router came to life. With Expo Router, customizing the HTML page is done through the [root **app/+html.(js|tsx)** file](https://docs.expo.dev/router/reference/static-rendering/#root-html) -- [this file in your repro](https://github.com/sudhanshug16/expo-static-bug/blob/main/app/%2Bhtml.tsx).

Hope this helps!

**Comment by sudhanshug16** [comment]
Thanks for the prompt response. That worked!
