### ISSUE TITLE
ImageManipulator.manipulate is deprecated warning

### ISSUE THREAD

**Issue by imasif** [expo/expo#2881]
I am getting:

> ImageManipulator.manipulate is deprecated in favor of manipulateAsync, which has the same API except for the method name

But when I try with `manipulateAsync.manipulate` i am getting this:

> TypeError: Cannot read property 'manipulate' of undefined

What's the problem?

I am using expo `camera` and `takePictureAsync`

**Comment by sjchmiela** [comment]
Try `ImageManipulator.manipulateAsync(args)` instead of `ImageManipulator.manipulateAsync.manipulate(args)` (if I understand correctly that's what you're using now). 🙂

**Comment by imasif** [comment]
Yes it was, thank you for pointing it out, I'm closing the issue

**Comment by vijay2330** [comment]
@sjchmiela  Thanks ..... Its works and issue resolved🙂🙂🙂🙂🙂

**Comment by yasso1am** [comment]
Unfortunately, the docs still suggest ImageManipulator.manipulate, with no depreciation discussion. I would love to make fixing this my first pull request, any good resources for how to go about doing that?

**Comment by wcandillon** [comment]
It looks like the documentation is not up to date regarding ImageManipulator right?

**Comment by yasso1am** [comment]
> It looks like the documentation is not up to date regarding ImageManipulator right?

that is correct. I am willing to re-write and submit pull request, I'm just not familiar with the process, or if that's what I should do.  Just trying to offer a solution instead of only complaining about an issue!

Thanks.

**Comment by sjchmiela** [comment]
It should be fixed on docs.expo.io now. 🙂

**Comment by yasso1am** [comment]
Thank you!
