### ISSUE TITLE
[docs] inconsistency on whether to add SafeAreaProvider in Expo Router docs

### ISSUE THREAD

**Issue by chriszs** [expo/expo#28818]
### Summary

I'm a little confused. When I followed the documentation to integrate Expo Router, I followed the existing [instruction](https://docs.expo.dev/router/migrate/from-react-navigation/#delete-unused-or-managed-code) to delete my use of `SafeAreaProvider`, but now ~when I test my app using the new architecture, the screens on which I use `SafeAreaView` aren't rendering with a safe area and~ I see this new [instruction](https://docs.expo.dev/router/appearance/#supporting-safe-areas) on the Appearance Elements page to add the `SafeAreaProvider` in my root layout and use the `useSafeAreaInsets` hook.

Digging further, I see that this was added in #26501, the motivation for which is an issue titled "[Document that safe area view isn’t needed as safe area context is available](https://linear.app/expo/issue/ENG-8402/document-that-safe-area-view-isnt-needed-as-safe-area-context-is)."

Is the context available, or do I have to add it? The React Navigation migration doc still says to delete the provider because Expo Router calls it implicitly.

### Link to the related docs page

* https://docs.expo.dev/router/appearance/#supporting-safe-areas
* https://docs.expo.dev/router/migrate/from-react-navigation/#delete-unused-or-managed-code

**Comment by brentvatne** [comment]
@chriszs - can you share a minimal reproducible example of this issue on the new architecture?

**Comment by chriszs** [comment]
@brentvatne I can try, though it's just as likely to be a safe-area-context-provider bug. On the other hand, I don't see anyone else reporting it, so I don't know what's going on there. I'm reporting it as a docs inconsistency, because the instruction to re-add the provider confused me (when I remove it now, `useSafeAreaInsets` still seems to work okay, so it may not be necessary), as well as the motivation for recommending `useSafeAreaInsets` (in the past, safe-area-context recommended avoiding it because `SafeAreaView` was a native component that was more synchronous, avoiding a nasty post-render visual jump, but that may or may not be true under new arch).

**Comment by chriszs** [comment]
Here's the minimal repro: https://github.com/chriszs/test-expo-app/pull/4

Before:

<img width="987" alt="Screenshot 2024-05-14 at 4 10 43 PM" src="https://github.com/expo/expo/assets/1103467/d697fbfd-99b0-4548-9ed1-9bae12ab200f">

After:

<img width="868" alt="Screenshot 2024-05-14 at 4 17 36 PM" src="https://github.com/expo/expo/assets/1103467/dcecac95-9a44-4e1e-ada9-5458c827c690">

The obvious next step is to try to repro this in a bare React Native project to suss out whether it belongs upstream, which it probably does.

**Comment by Shakahs** [comment]
I'm running into this as well, SafeAreaView does not work but useSafeAreaInsets() does. It [appears to be an upstream bug](https://github.com/th3rdwave/react-native-safe-area-context/issues/496#issuecomment-2130053527).  
Expo 51 on New Architecture.

**Comment by Aleks86** [comment]
I have run into exact same issue. `SafeAreaView` does not add paddings, while `useSafeAreaInsets()` is working properly.

**Comment by chriszs** [comment]
Yeah, I agree with that. I can reframe and reopen the issue, but I suspect at this point the best path would be to propose a PR.

**Comment by pmmmwh** [comment]
I would be open to help with a PR but I'm uncertain which behavior is the wanted one 😅

**Comment by Shakahs** [comment]
Also Expo is not using the updated upstream package, so SafeAreaView is still broken in Expo apps.

**Comment by brentvatne** [comment]
@Shakahs - can you elaborate on your point here? you can use any version of react-native-safe-area-context that you like. we have a recommended version based on what we tested with sdk 51 on release, but you aren't limited to that. https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation

**Comment by amandeepmittal** [comment]
Hey @chriszs and @pmmmwh, thanks for letting us know about the inconsistency in the docs that caused the confusion. If your project has Expo Router installed or is created using the `default` template, there's no need to add `SafeAreaProvider` in the Root layout. You can directly use `SafeAreaView` or `useSafeAreaInsets()` hook.

The PR #30494 will fix these instructions.
