### ISSUE TITLE
expo export hangs when using css import from nativewind

### ISSUE THREAD

**Issue by lachied522** [expo/expo#28816]
### Minimal reproducible example

https://github.com/lachied522/eas-update-test-app

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I am wanting to publish an update for my expo app, but running eas update gets stuck on "Exporting..." indefinitely. I saw somewhere that I should run npx expo  export --output-dir dist --dump-sourcemap --dump-assetmap --platform=all, which results in the metro bundler getting stuck part way through.

Edit: Should also mention that building app is no problem. Only encountered this when attempting to publish update.

eas update gets stuck like this:
√ No branches found. Provide a branch name: ... master
√ Provide an update message: ... initial commit
[expo-cli] Starting Metro Bundler
[expo-cli]
[expo-cli] tailwindcss(native) rebuilding...
[expo-cli] done
| Exporting...

npx expo  export --output-dir dist --dump-sourcemap --dump-assetmap --platform=all gets stuck like this:
Starting Metro Bundler
done
iOS node_modules\expo-router/entry.js ▓▓▓▓▓▓▓▓▓▓▓▓░░░░ 80.4% (687/766)
Android node_modules\expo-router/entry.js ░░░░░░░░░░░░░░░░  0.0% (0/1)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10300.40.2321.11668458
    npmPackages:
      expo: ~51.0.4 => 51.0.5
      expo-router: ~3.5.12 => 3.5.12
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.6 => 0.19.11
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
@marklawlor - from the README in the repo that was shared:

> Note: Issue seems to be the import "../global.css" (see https://www.nativewind.dev/v4/getting-started/expo-router) line in app/layout.tsx. Removing this line resolves the issues.

**Comment by lachied522** [comment]
Changing '../global.css' to '../node_modules/.cache/nativewind/global.css' resolved issue 

[github.com/markgithub.com/marklawlor/nativewind/issues/610lawlor/nativewind/issues/610](https://github.com/marklawlor/nativewind/issues/610)
