### ISSUE TITLE
After upgrade from 50.0.17 to 51.0.4 getting on Apple submission ITMS-90078: Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by oferraanan** [expo/expo#28811]
### Minimal reproducible example

not relevant as its related to submission

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

After upgrade from 50.0.17 to 51.0.4 getting on Apple submission 
ITMS-90078: Missing Push Notification Entitlement
Not using notifications at all

### Environment

PS C:\workspaces\DOXI\AirMap> npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ^51.0.4 => 51.0.4
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: managed

### Expo Doctor Diagnostics

PS C:\workspaces\DOXI\AirMap> npx expo-doctor@latest
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.4 - expected version: ~51.0.5
  expo-sensors@13.0.5 - expected version: ~13.0.6
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
PS C:\workspaces\DOXI\AirMap>

**Comment by oferraanan** [comment]
Its related to submission
package.json
{
  "name": "airmap",
  "version": "2.0.2",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "ahrs": "^1.3.3",
    "expo": "^51.0.4",
    "expo-checkbox": "~3.0.0",
    "expo-dev-client": "~4.0.13",
    "expo-document-picker": "~12.0.1",
    "expo-file-system": "~17.0.1",
    "expo-keep-awake": "~13.0.1",
    "expo-location": "~17.0.1",
    "expo-screen-orientation": "~7.0.4",
    "expo-sensors": "~13.0.5",
    "expo-sharing": "~12.0.1",
    "expo-speech": "~12.0.2",
    "expo-status-bar": "~1.12.1",
    "fast-xml-parser": "^4.3.6",
    "kalmanjs": "^1.1.0",
    "metar-taf-parser": "^8.0.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-geolocation": "^1.0.4",
    "react-native": "0.74.1",
    "react-native-alertbox": "^0.2.11",
    "react-native-async-storage": "0.0.1",
    "react-native-dropdown-select-list": "^2.0.5",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-maps": "1.14.0",
    "react-native-paper": "^5.12.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "15.2.0",
    "react-native-vector-icons": "^10.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0"
  },
  "private": true
}

**Comment by Rhym** [comment]
I'm having the same issue.

**Comment by Rhym** [comment]
@oferraanan You'll need to create a new issue. I'm also having the same one.

**Comment by andreyukD** [comment]
I'm having the same issue,
Probably it comes from **"Notifications entitlement is no longer always added to iOS projects during rebuild"**
https://expo.dev/changelog/2024/05-07-sdk-51#deprecations-renamings-and-removals

SDK 51 removed entitlement, which was present in previous versions. I'm not sure, if should we add it manually to the app config, if our app doesn't use push notifications

**Comment by oferraanan** [comment]
Thanks Dima
If you find something please share
My APP was approved  by Apple despite this warning "Air Map Israel"

**Comment by oferraanan** [comment]
Hi

Update I added to app.json
"ios": {

    "entitlements": {
      "aps-environment": "development"
    },
...
}

And now I did not get this warning mail from Apple
My APP was released to APP Store

Thanks

**Comment by gkasireddy202** [comment]
I am getting a warning message from App Store Connect.I did not use the push notification in my app.
ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see

react-native:0.73.7
iOS:17
expo: "50.0.17",
expo-local-authentication: "13.8.0",
