### ISSUE TITLE
use react-native-bluetooth-escpos-printer. build Task :app:compileReleaseKotlin FAILED

### ISSUE THREAD

**Issue by detanx** [expo/expo#28821]
### Minimal reproducible example

https://github.com/detanx/expo-react-native-bluetooth-escpos-printer/tree/main

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

 "expo": "~51.0.5",
"react-dom": "18.2.0",
"react-native": "0.74.1",
 "react-native-bluetooth-escpos-printer": "^0.0.5",
[react-native-bluetooth-escpos-printer+0.0.5.patch](https://github.com/expo/expo/files/15304183/react-native-bluetooth-escpos-printer%2B0.0.5.patch)

other config
[react-native-bluetooth-escpos-printer github](https://github.com/januslo/react-native-bluetooth-escpos-printer)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 21.7.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 27, 30, 31, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
    IDEs:
      Android Studio: AI-232.10300.40.2321.11567975

### Expo Doctor Diagnostics

![image](https://github.com/expo/expo/assets/22371912/b433935d-7174-4097-9190-648d9fcefd4a)

**Comment by pvinis** [comment]
Could you paste the whole log? Are you building on eas or locally?

**Comment by detanx** [comment]
I used eas to build it. The complete log of the error part is as follows:
You can use the code from this [repository ](https://github.com/detanx/expo-react-native-bluetooth-escpos-printer/tree/main) to test.
Thank you.

![image](https://github.com/expo/expo/assets/22371912/04ff8e2e-dbc1-4853-8e08-740f361955d8)

**Comment by detanx** [comment]
@pvinis I uploaded the full error log file [here](https://github.com/detanx/expo-react-native-bluetooth-escpos-printer/blob/main/eas-build-error-log.text)

**Comment by AlexisKenAlvarez** [comment]
I'm having the same issue!

**Comment by detanx** [comment]
I have it running on the latest expo version, you can take a look [here](https://github.com/detanx/react-native-bluetooth-escpos-printer). If your project can't run, you can try to use this [demo](https://github.com/detanx/expo-react-native-bluetooth-escpos-printer)
