### ISSUE TITLE
Detached iOS app: loads manifest from exp...:// LAN Url instead of manifestUrl on Release

### ISSUE THREAD

**Issue by nemo** [expo/expo#2883]
Hey folks,

Trying to build a TestFlight build and every time I do (Using fastlane with configuration set to `Release`), the build keeps pointing to a LAN Url instead of using a local bundled JS or using manifestUrl from ExShell.

### Environment

Target is a detached iOS app.

```
  Expo CLI 2.6.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.2```

### Steps to Reproduce

<!--
  How would you describe your issue to someone who doesn’t know you or your project?
  Try to write a sequence of steps that anybody can repeat to see the issue.
  Be specific! If the bug cannot be reproduced, your issue may be closed.
-->

(Write your steps here:)

1. Build a release build from generated detached iOS xcodeworkplace
2. Load release build on device -> app attempts to load exp..://... JS bundle instead of local and/or from manifestUrl

### Expected Behavior

<!--
  How did you expect your project to behave?
  It’s fine if you’re not sure your understanding is correct.
  Just write down what you thought would happen.
-->

Expect the JS to be automatically bundled OR loaded from published Expo manifestUrl.


### Actual Behavior

<!--
  Did something go wrong?
  Is something broken, or not behaving as you expected?
  Describe this section in detail, and attach screenshots if possible.
  Don't just say "it doesn't work"!
-->

App attempts to load JS bundle from LAN Url (exp...://....)

**Comment by nemo** [comment]
Been debugging and I think the problem may be here:

``` NSString *configPath = [[NSBundle mainBundle] pathForResource:@"EXShell" ofType:@"plist"];
```

In the `ExEnviornment.m` file.

**Comment by quinlanj** [comment]
hi @nemo , can you clarify the redacted `exp...://....` address please? The `exp` protocol is expected and isnt indicative of a LAN url. A LAN url would be something like `exp://192.168.1.x`, on a release build it should be something like `exp://exp.host`.

**Comment by quinlanj** [comment]
<img width="1296" alt="release" src="https://user-images.githubusercontent.com/6380927/49541671-52037880-f888-11e8-8795-820c9e51d8ab.png">

Also, are you building this in XCode? To build in XCode with Release configurations, you need to go to the `Product->Scheme->Edit Scheme` option and choose Release instead of Debug

**Comment by nemo** [comment]
It's rather confusing because the way I solved this problem this week myself was to (still having set Release as the target), go in and manually edit [this line](https://github.com/expo/expo/blob/master/ios/Exponent/Kernel/Environment/EXEnvironment.m#L91) and always set it to YES right before building an Archive build.

I've been trying to figure out why that line is *ever* called because I checked multiple times and it's a Release build...

**Comment by quinlanj** [comment]
oh hm... that's weird. And just to make sure, your `Build Scheme` in XCode is set to Release (instead of Debug)?

**Comment by nemo** [comment]
Yup -> https://d.pr/i/7PJnDU and after running -> https://d.pr/i/8tKekd

**Comment by Davidzhu001** [comment]
@nemo any solution?

**Comment by cruzach** [comment]
@Davidzhu001 are you seeing this issue on a more recent SDK? I haven't been able to repro, so if you are could you provide the steps you're taking? If not, will probably close this issue for inactivity

**Comment by Davidzhu001** [comment]
@cruzach No, everything is fine now, Thanks.
