### ISSUE TITLE
[expo-image][jest] ExpoImage spitting console error on Expo 51 while testing

### ISSUE THREAD

**Issue by lodev09** [expo/expo#28831]
### Minimal reproducible example

https://github.com/lodev09/expaw

### What platform(s) does this occur on?

Jest

### Did you reproduce this issue in a development build?

Yes

### Summary

`expo-image` is spitting `console.error` during tests with jest after upgrading to Expo 51. Although tests pass, it's kinda annoying with all the red texts 🥲

```sh
yarn run v1.22.22
$ jest
  console.error
    Warning: Unexpected ref object provided for ExpoImage. Use either a ref-setter function or React.createRef().
        at NativeComponent (/Users/lodev09/Projects/github/expaw/node_modules/expo-modules-core/src/NativeViewManagerAdapter.native.tsx:79:25)
        at ExpoImage (/Users/lodev09/Projects/github/expaw/node_modules/expo-image/src/ExpoImage.tsx:30:17)
        at Image (/Users/lodev09/Projects/github/expaw/node_modules/expo-image/src/Image.tsx:15:20)
        at style (/Users/lodev09/Projects/github/expaw/src/components/PreviewImage.tsx:5:11)

       6 | describe('PreviewImage', () => {
       7 |   it('should render', () => {
    >  8 |     render(<PreviewImage source={{ uri: 'somefile.jpg' }} />)
         |           ^
       9 |     expect(screen.queryByRole('image'))
      10 |   })
      11 | })
...
```

To reproduce, checkout [this repo](https://github.com/lodev09/expaw)

```sh
yarn && yarn test
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2024.03.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.5 => 51.0.5 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by nijk** [comment]
I'm also seeing this

**Comment by killerchip** [comment]
I am also seeing this even when I use `renderRouter`

**Comment by alxjrvs** [comment]
Also seeing this!

**Comment by Echzio** [comment]
+ also seeing this

**Comment by landorid** [comment]
I can also confirm there is a problem!

**Comment by ehcorrea** [comment]
I have a simple use for `Image` from `expo-image`, so I maked a work around for this, using mocks and `react-native ` Image component.

```
jest.mock('expo-image', () => {
  const actualExpoImage = jest.requireActual('expo-image');
  const { Image } = jest.requireActual('react-native');

  return { ...actualExpoImage, Image };
});
```

### Before Mock

<img width="1097" alt="image" src="https://github.com/expo/expo/assets/37821900/fad8a958-e4c0-43db-96d5-7e7081036e42">

### Afert Mock

<img width="1097" alt="image" src="https://github.com/expo/expo/assets/37821900/28f2dfc6-f606-43aa-bc24-b4e68316303e">

**Comment by hanyufoodles** [comment]
Still seeing this with:
expo: 51.0.23
expo-image: 1.12.13
jest-expo: 51.0.3

Is there any plan on a release of the fix? I don't see any version containing the fix commit.

**Comment by MarcHbb** [comment]
Still seeing this on expo SDK 51
"expo": "~51.0.22",
"expo-image": "~1.12.13",

**Comment by OskarPrzydatek** [comment]
> I have a simple use for `Image` from `expo-image`, so I did a work around for this, using mocks and `react-native ` Image component.
> 
> ```
> jest.mock('expo-image', () => {
>   const actualExpoImage = jest.requireActual('expo-image');
>   const { Image } = jest.requireActual('react-native');
> 
>   return { ...actualExpoImage, Image };
> });
> ```
> 
> ### Before Mock
> <img alt="image" width="1097" src="https://private-user-images.githubusercontent.com/37821900/344240087-fad8a958-e4c0-43db-96d5-7e7081036e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODY2MTUsIm5iZiI6MTcyMzk4NjMxNSwicGF0aCI6Ii8zNzgyMTkwMC8zNDQyNDAwODctZmFkOGE5NTgtZTRjMC00M2RiLTk2ZDUtN2U3MDgxMDM2ZTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEzMDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTIwY2IyNzE1NTY3ZDQ3ZGVmMjEyN2NkZDZhYjNjNjg0ZGMyMDAzNzllMDVlZmM0ZTdmMGQ2NzEwZmUwYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJq2rvtcIaAXSBiHzG3a05rXUt0qoSFfNrVHk0ZVQ8M">
> ### Afert Mock
> <img alt="image" width="1097" src="https://private-user-images.githubusercontent.com/37821900/344240209-28f2dfc6-f606-43aa-bc24-b4e68316303e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODY2MTUsIm5iZiI6MTcyMzk4NjMxNSwicGF0aCI6Ii8zNzgyMTkwMC8zNDQyNDAyMDktMjhmMmRmYzYtZjYwNi00M2FhLWJjMjQtYjRlNjgzMTYzMDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEzMDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMDBiODJjNzcxOGMxZTQwNGJlNDIyYjA3ZDk4YWY5OGU5ZDA0MjNiNWFiN2EwNDU3NjQ3ZmZjZjM1ZmRlODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E8dmEmNXrvEI4xeS2FcoywRXjJTr3p81EWe-hZWwEvo">

This is the solution which rocks!
