### ISSUE TITLE
Turtle CLI: android build is very slow (it's not a bug)

### ISSUE THREAD

**Issue by borgogelli** [expo/expo#2884]
Turtle-CLI downloads the Android Sdk and configures it for every build. It is an operation that takes a long time. 
Is it possible for the user to cache some folders, so that Turtle-CLI avoids to reconfigure it every time ?

**Comment by borgogelli** [comment]
If I have the android sdk installed and configured, why I can't use it with Turtle-CLI ?

**Comment by dsokal** [comment]
Hello @borgogelli,
it's not true. `turtle-cli` downloads Android SDK only if it's not already present in `$HOME_DIR/.turtle/androidDependencies/sdk` directory. You should generally cache `$HOME_DIR/.turtle` directory if you would like to speed up your builds. 
Please check example CI configuration files, it's all there (caching `~/.turtle` directory too!) - https://docs.expo.io/versions/v31.0.0/distribution/turtle-cli

**Comment by borgogelli** [comment]
Thank you @dsokal . I'm using a docker image to build an apk with expo-cli and turtle-cli. 
I will follow your advice but I have a couple of questions:
Is the sdk downloaded inside the .turtle folder ? Can I configure the path of that folder to point to another path ?

**Comment by dsokal** [comment]
Yes, `turtle-cli` downloads Android SDK to `~/.turtle/androidDependencies/sdk` directory. 
Unfortunately setting your own path is not supported at the moment.

**Comment by borgogelli** [comment]
It would be very useful when Turtle-CLI is used inside a CI pipeline, where the environment is always cleaned and there is the need to cache a folder outside the container or the virtual machine.

**Comment by dsokal** [comment]
@borgogelli have you seen our docs? https://docs.expo.io/versions/v31.0.0/distribution/turtle-cli#ci-configuration-file-examples
There are two example ci configurations. In both cases `~/.turtle` is cached.
