### ISSUE TITLE
npx expo lint gives a maximum call stack size exceeded isn't solved yet

### ISSUE THREAD

**Issue by oamr-abdelaziz** [expo/expo#28841]
### Summary

This is regarding issue #28799, I upgraded to the latest expo after you merged a fix for it and I tried also with a new project but the issue isn't solved yet.

Is there something else that I should do so I don't face the issue or it isn't solved yet?

### Environment

expo-env-info 1.2.0 environment info:
System:
OS: Windows 11 10.0.22631
Binaries:
Node: 20.0.0 - C:\Program Files\nodejs\node.EXE
npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: AI-233.14808.21.2331.11709847
npmPackages:
expo: ~51.0.2 => 51.0.2
expo-router: ~3.5.11 => 3.5.11
react: 18.2.0 => 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.74.1 => 0.74.1
react-native-web: ~0.19.10 => 0.19.11
Expo Workflow: managed

### Minimal reproducible example

https://github.com/oamr-abdelaziz/Generate-AI-Image

type in terminal, npx expo lint

**Comment by brentvatne** [comment]
hi there - commits aren't deployed immediately after being merged. i've deployed it now, and it should be resolved in expo@51.0.6

**Comment by oamr-abdelaziz** [comment]
Awesome, it works now.
Thanks for the fast response @brentvatne
