### ISSUE TITLE
Facedetection is not working on V31.0.0 after built

### ISSUE THREAD

**Issue by Davidzhu001** [expo/expo#2887]
### Environment

```
Expo CLI 2.6.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.6.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.6.0
```
### Steps to Reproduce

I updated my expo to newest, and when i pack for ios. Facedetection is not working anymore? It works well on expo cli ios.

**Comment by EvanBacon** [comment]
Perhaps this has to do with how Google has made FaceDetector a bigger part of Firebase. We should look into updating the version and adding tests. [Current Version](https://github.com/expo/expo/blob/8abee6cc315b3f92906546b6beaedbdc5053ced0/packages/expo-face-detector/ios/EXFaceDetector.podspec#L21-L22)

**Comment by Davidzhu001** [comment]
@EvanBacon Should I downgrade my version. it works fine with previous version. or should i try to wait for solution and help you guys to debug it ?

**Comment by EvanBacon** [comment]
Closing as Face detector has been changed a lot in the latest 6 versions. If someone continues to encounter problems please feel free to open a new issue.
