### ISSUE TITLE
Babel error after updating to EXPO 51

### ISSUE THREAD

**Issue by vintvgx** [expo/expo#28877]
### Minimal reproducible example

https://github.com/vintvgx/SCOUT/tree/expo.v51

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

After updating to EXPO v51, my app keeps crashing with the error after running "npm start" : error: index.js: [BABEL] /Users/vintvgx/Desktop/bandit.studios/studio.code/RN/dpd.stats/index.js: Unknown option: .name. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.

When I try to use "npx expo run:ios", the build fails with this error : 

`
› Skipping dev server
› Planning build
› Executing react-native Pods/hermes-engine » [CP-User] [Hermes] Replace Hermes for the right configuration, if needed
› Executing react-native Pods/React-Fabric » [CP-User] [RN]Check rncore
› Compiling react-native Pods/React-RCTAppDelegate » RCTRootViewFactory.mm
› Compiling react-native Pods/React-RCTAppDelegate » React-RCTAppDelegate-dummy.m

❌  (ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap:1:8)

> 1 | module ReactCommon {
    |        ^ redefinition of module 'ReactCommon'
  2 |   umbrella header "ReactCommon-umbrella.h"
  3 |   exclude header "React-RuntimeApple-umbrella.h"
  4 | 

› Compiling react-native Pods/React-RCTAppDelegate » RCTAppSetupUtils.mm
› Compiling react-native Pods/React-RCTAppDelegate » RCTAppDelegate.mm
› Compiling react-native Pods/React-RCTBlob » RCTBlobManager.mm
› Compiling react-native Pods/React-RCTBlob » RCTBlobCollector.mm
› Compiling react-native Pods/React-RCTFabric » RCTModalHostViewComponentView.mm
› Compiling react-native Pods/React-RCTFabric » RCTParagraphComponentView.mm
› Compiling react-native Pods/React-RCTFabric » RCTInputAccessoryComponentView.mm
› Compiling react-native Pods/React-RCTFabric » RCTAccessibilityElement.mm
› Compiling react-native Pods/React-RCTFabric » RCTFabricComponentsPlugins.mm
› Compiling react-native Pods/React-RCTFabric » RCTImageComponentView.mm
› Compiling react-native Pods/React-RCTFabric » RCTFabricSurface.mm
› Compiling react-native Pods/React-RCTFabric » RCTEnhancedScrollView.mm
› Compiling react-native Pods/React-RCTFabric » RCTDebuggingOverlayComponentView.mm
› Compiling react-native Pods/React-RCTFabric » RCTComponentViewRegistry.mm
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » dpdstats/dpdstats » Build Phases » 'Upload Debug Symbols to Sentry'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » dpdstats/dpdstats » Build Phases » '[CP-User] [RNFB] Core Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

› 1 error(s), and 2 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
`

These are the steps I used to update to v51:

npm install expo@latest
npm install --fix
npx expo install --fix

.babelrc
`
{
    "presets": [
    "module:metro-react-native-babel-preset",
    "module:react-native-dotenv"
    ]
    }
`

package.json
`
{
  "name": "scout",
  "version": "1.1.8",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@babel/plugin-transform-optional-chaining": "^7.24.5",
    "@react-native-community/cli-platform-ios": "3.0.0",
    "@react-native-firebase/app": "^19.0.1",
    "@react-native-firebase/messaging": "^19.0.1",
    "@react-navigation/bottom-tabs": "^6.5.17",
    "@react-navigation/material-top-tabs": "^6.6.13",
    "@react-navigation/native": "^6.1.15",
    "@react-navigation/native-stack": "^6.9.23",
    "@react-navigation/stack": "^6.3.26",
    "@reduxjs/toolkit": "^2.2.2",
    "@sentry/react-native": "~5.22.0",
    "axios": "^1.6.7",
    "bottleneck": "^2.19.5",
    "dotenv": "^16.4.5",
    "expo": "~51.0.6",
    "expo-build-properties": "~0.12.1",
    "expo-dev-client": "~4.0.13",
    "expo-device": "~6.0.2",
    "expo-notifications": "~0.28.1",
    "expo-secure-store": "~13.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "firebase": "^10.9.0",
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^4.8.0",
    "pretty-format": "^29.7.0",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-dotenv": "^3.4.11",
    "react-native-maps": "1.14.0",
    "react-native-pager-view": "6.3.0",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.3",
    "react-redux": "^9.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.5",
    "@types/react": "~18.2.45",
    "@types/react-native-dotenv": "^0.2.2",
    "@types/react-native-vector-icons": "^6.4.18",
    "typescript": "~5.3.3"
  },
  "private": true
}
`

Please help me resolve this error. I am two additions away from completing my project !

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      npm: 10.2.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.6 => 51.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.3
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by gstcarv** [comment]
<img width="1197" alt="image" src="https://github.com/expo/expo/assets/30243834/1579e053-671a-4837-b965-007f74f99579">

same issue here

**Comment by gstcarv** [comment]
<img width="1197" alt="image" src="https://github.com/expo/expo/assets/30243834/e0a709b0-c29e-466b-b4c9-1590ca989ad3">

same issue here when trying to run web

**Comment by byCedric** [comment]
Hi @vintvgx, thanks for the issue report. It seems that your project has multiple babel configurations, both of them invalid.

- The [**.babelrc** config](https://github.com/vintvgx/SCOUT/blob/236bce0165b67cd3ca491d264e247fe6fa9960d0/.babelrc) does not use `babel-preset-expo`, causing various transpilation issues.
- The [**babel.config.js** config](https://github.com/vintvgx/SCOUT/blob/c87b9e85470768f8105c1d67dca055a9fd9f91bf/babel.config.js) does not use the recommended config format ([see here](https://github.com/expo/expo/blob/main/templates/expo-template-bare-minimum/babel.config.js))

After dropping **.babelrc** and updating the **babel.config.js** files, Babel does seem to work in your project.

Hope this helps!

**Comment by vintvgx** [comment]
That worked! Thank you so much

**Comment by JoPoTe** [comment]
Anyone still having this issue one thing which resolved my babel/runtime errors among other package errors after updating to expo 51 the following commands resolved it for me. 
npm cache verify
npm cache clean --force
rm -rf node_modules/
rm package-lock.json
npm install
npx expo start -c

**Comment by blue86321** [comment]
> Anyone still having this issue running the following commands resolved my babel/runtime errors among other package errors after updating to expo 51: npm cache verify npm cache clean --force rm -rf node_modules/ rm package-lock.json npm install npx expo start -c

It works, thank you.
We are using `yarn`, we faced similar babel issue:
`node_modules/expo/AppEntry.js:
[BABEL] xxxx/node_modules/expo/AppEntry.js: Cannot find module 'babel-plugin-polyfill-corejs2'`

Here is the solution script for `yarn`
```bash
yarn cache clean
rm -rf node_modules
rm yarn.lock
yarn install
npx expo start --clear
```
