### ISSUE TITLE
[expo 50] My Expo apps only work in dev mode, stuck on splash screen, showing 'New update available, downloading...'

### ISSUE THREAD

**Issue by Yavae** [expo/expo#28886]
### Minimal reproducible example

https://github.com/Yavae/bugExpo-waitingDownloads.git

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I created an android build for my project with eas build (apk) and when I tested my app it got stuck in the spalshscreen with the message ‘New update available, downloading...’, 
My app is going well when npx expo start, but running npx expo start --no-dev --minify algo goes to infinite ‘New update available, downloading...’, the SDK was expo 50 I also tried to change the version with expo 51 (latest now), also and it's the same, I tried to do everything that said the other 20 Issues equal to this but no way.

Even creating a new app goes same way

Minimal reproducible example:
npx create-expo-app test-app/
cd test-app
npx expo start --no-dev --minify

i also tried with: npx create-expo-app -t expo-template-blank-typescript testApp, same thing
I couldn't check this on apple
It works fine in web

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 21.7.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9862592
    npmPackages:
      expo: ~50.0.14 => 51.0.6
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.74.1
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by Rina196** [comment]
Please suggest any solution. I've been facing the same issue last 3 days.

**Comment by Yavae** [comment]
Update

> Pixel_3a_API_33_x86_64 (emulator) //not working
    Pixel_6_Pro_API_33 (emulator)

Now I try again npx expo start --no-dev --minify emulator on the device where I was doing it before: > Pixel_3a_API_33_x86_64 (emulator) and the same thing happens, it gets stuck on ‘New update available, downloading...’, but I change emulated device and suddenly Pixel_6_Pro_API_33 (emulator) works all perfect, and also now I do the build with eas and yes it goes, no sense (no change from when I did the build where it didn't work) now I try the apk build on my mobile and it doesn't get stuck. The problem is still there but I don't know why it doesn't happen now, I discarded all the changes so theoretically I didn't change anything.

**Comment by Yavae** [comment]
with Sentry I have been seeing things going wrong and have been correcting them, problems with supabase
@Rina196 here is sentry docs with expo [https://docs.sentry.io/platforms/react-native/manual-setup/expo] it might help you.
