### ISSUE TITLE
[expo-router] initialRouteName has no effect

### ISSUE THREAD

**Issue by Aximem** [expo/expo#28898]
### Minimal reproducible example

https://github.com/Aximem/expo-route-initial-route-name/

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

In the following repository, I try to set a different initialRouteName than "index".

In `app/_layout.tsx`, I do:  
```
import { Stack } from "expo-router/stack";

export const unstable_settings = {
  initialRouteName: "test",
};

export default function Layout() {
  return (
    <Stack initialRouteName="test">
      <Stack.Screen name="index" options={{}} />
      <Stack.Screen name="test" options={{}} />
    </Stack>
  );
}
```   

But, every time I reload the application, it opens the "index" screen, not the "test" screen.  
It seems that "initialRouteName" has no effect here.   

Am I doing something wrong ? How can I set a different initialRouteName than index ?  
Thanks

Btw, I already checked #27005 but in my case this is not related to multiple url matching, it just ignores the initialRouteName on app opening. i don't see a way to open my app on "test" screen.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
      Watchman: 2024.03.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/maxime/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.6 => 51.0.6 
      expo-router: ~3.5.12 => 3.5.12 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 9.0.3
    Expo Workflow: managed

**Comment by marklawlor** [comment]
`initialRouteName` is only applied during deeplinking. This is the default behaviour of React Navigation. We are looking to change this behaviour in an upcoming versino of Expo Router (so its applied by default, you you will need to opt out of it being applied)

**Comment by Aximem** [comment]
@marklawlor Thanks for your answer and your reactivity. I will check if I can find a workaround.

Just to clarify, this is not the default behaviour of React Navigation, if you do this, app will always launch on TestScreen:

```
import * as React from 'react';
import {View, Text} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';

function IndexScreen() {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Home Screen</Text>
    </View>
  );
}

function TestScreen() {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Test Screen</Text>
    </View>
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="test">
        <Stack.Screen name="index" component={IndexScreen} />
        <Stack.Screen name="test" component={TestScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```
