### ISSUE TITLE
[eas-build-local] Metro errors with SHA-1 for file ... index.js ... is not computed when using "index.js" as package main

### ISSUE THREAD

**Issue by fabiovieira1901** [expo/expo#28890]
### Minimal reproducible example

https://github.com/fabiovieira1901/app.git

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

With Expo version 49, I was able to run the command "eas build --platform ios --local" without any issues. After updating to version 51, this command now consistently results in an error:

error: SHA-1 for file /var/folders/gc/f5p8tj751dvgf363hqcj5d500000gn/T/eas-build-local-nodejs/cf95be6e-e9e7-49d5-ba6e-53c60e47c9d5/build/apps/app-milene-martins/index.js (/var/folders/gc/f5p8tj751dvgf363hqcj5d500000gn/T/eas-build-local-nodejs/cf95be6e-e9e7-49d5-ba6e-53c60e47c9d5/build/apps/app-milene-martins/index.js) is not computed.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.6 => 51.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.5
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by msoltow** [comment]
I experienced this as well.  Per https://github.com/expo/expo/issues/28209#issuecomment-2106153742, the fix seems to be to change the value of `main` in `package.json` to `expo/AppEntry.js` (essentially removing the `node_modules` bit).

@brentvatne I know you mentioned [here](https://github.com/expo/expo/issues/28209#issuecomment-2106417525) that this shouldn't be an issue, but I was also able to verify that the above fix worked.

**Comment by fabiovieira1901** [comment]
@msoltow I removed the "main" from the package.json and it already fixed the problem. Thank you very much for the help.

**Comment by brentvatne** [comment]
@byCedric - do you have any ideas why `"main": "node_modules/expo/AppEntry.js"` would have different behavior from `"main": "expo/AppEntry.js"` here?

**Comment by imranbarbhuiya** [comment]
I've `index.ts` as entrypoint and inside index.ts, I've 
```ts
import 'expo-dev-client';

import 'expo-router/entry';
```
and I'm also having the same issue

**Comment by dannyhw** [comment]
also using index.js here with the same issue

**Comment by brentvatne** [comment]
here's a minimal repro: https://github.com/brentvatne/repro-28890

- i was able to reproduce this with `eas build --local` (specifically, i ran `eas build -p ios --profile preview ---local`)
- i was not able to reproduce it with `eas build`
- i was not able to reproduce it with `npx expo run:ios --configuration Release`

**Comment by byCedric** [comment]
The issue seems to be around absolute vs relative paths, used in the embed bundle command. Running `EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build -p ios --profile preview --local` helps us figure out what's going wrong with the local build specifically.

When replacing the absolute path from the `--entry-file` argument with the relative or current CWD path, the issue seems to go away.

<details><summary>The bundle command</summary>

```bash
# Using absolute path for the entry file (doesn't work)
npx expo export:embed --entry-file /var/folders/qw/kq2qkfj10rs4zfbnt69l3fwr0000gn/T/eas-build-local-nodejs/c20fa43a-65f9-4ac3-8b84-160364abc962/build/index.js --platform ios --dev false --reset-cache --bundle-output /var/folders/qw/kq2qkfj10rs4zfbnt69l3fwr0000gn/T/eas-build-local-nodejs/c20fa43a-65f9-4ac3-8b84-160364abc962/build/ios/build/Build/Products/Release-iphonesimulator/main.jsbundle --assets-dest /var/folders/qw/kq2qkfj10rs4zfbnt69l3fwr0000gn/T/eas-build-local-nodejs/c20fa43a-65f9-4ac3-8b84-160364abc962/build/ios/build/Build/Products/Release-iphonesimulator/fabio.app --minify false

# Using relative path for the entry file (works)
npx expo export:embed --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /var/folders/qw/kq2qkfj10rs4zfbnt69l3fwr0000gn/T/eas-build-local-nodejs/c20fa43a-65f9-4ac3-8b84-160364abc962/build/ios/build/Build/Products/Release-iphonesimulator/main.jsbundle --assets-dest /var/folders/qw/kq2qkfj10rs4zfbnt69l3fwr0000gn/T/eas-build-local-nodejs/c20fa43a-65f9-4ac3-8b84-160364abc962/build/ios/build/Build/Products/Release-iphonesimulator/fabio.app --minify false
```

</details>

Will update when I have more.

**Comment by brentvatne** [comment]
confirmed that @byCedric's fix resolved the issue for me in https://github.com/brentvatne/repro-28890

update to expo@~51.0.8
