### ISSUE TITLE
Expected metro@~0.80.8 package after SDK 51 update was installed.

### ISSUE THREAD

**Issue by codeOlam** [expo/expo#28895]
### Minimal reproducible example

private repo

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

After updating from expo sdk 50 to sdk 51. App crashes on production only on ios.

But after checking the build logs on my eas dashboard i found out that, there was an issue with the version of metro expected versus the metro sdk 51 current came pre-installed with.

### Environment

n/a

### Expo Doctor Diagnostics

<img width="997" alt="image" src="https://github.com/expo/expo/assets/66900587/084f4e8e-91a0-4c48-ad75-23367fccd0fd">

<img width="1083" alt="image" src="https://github.com/expo/expo/assets/66900587/bcddb9fa-6f52-4539-93b6-37275b562b43">

**Comment by brentvatne** [comment]
if you run `npm why metro@0.80.6` it will tell you where that dependency comes from. perhaps you have a resolution set to force it, or you have a library that you are using that is installing it on your behalf (and shouldn't be)

**Comment by stevekuznetsov** [comment]
```
  metro@"0.80.5" from metro-config@0.80.5
  node_modules/metro-config
    metro-config@"^0.80.3" from @react-native/community-cli-plugin@0.74.83
    node_modules/@react-native/community-cli-plugin
      @react-native/community-cli-plugin@"0.74.83" from react-native@0.74.1
      node_modules/react-native
        react-native@"0.74.1" from the root project
```

For us it seems like it's coming from the version of `react-native` that `expo` installed with the new SDK?

**Comment by stevekuznetsov** [comment]
@brentvatne we also don't have anything else that brings it in and nothing in package.json for metro other than

```
$ grep metro package.json 
    "metro-react-native-babel-preset": "^0.77.0",
```

**Comment by brentvatne** [comment]
> ```
>   metro@"0.80.5" from metro-config@0.80.5
>   node_modules/metro-config
>     metro-config@"^0.80.3" from @react-native/community-cli-plugin@0.74.83
>     node_modules/@react-native/community-cli-plugin
>       @react-native/community-cli-plugin@"0.74.83" from react-native@0.74.1
>       node_modules/react-native
>         react-native@"0.74.1" from the root project
> ```
> 
> For us it seems like it's coming from the version of `react-native` that `expo` installed with the new SDK?

this output doesn't match what i saw in your doctor results - where it was saying you had metro@0.80.6 rather than 0.80.5, so that's strange to me.

can you share the full output of `npm why metro@0.80.6`?

i'm not totally clear on what is happening here but it may be a result of some strange lockfile behavior, so you're somehow ending up with metro@0.80.5 or 0.80.6 because it was previously installed. you could try clearing your node_modules and lockfile.

**Comment by stevekuznetsov** [comment]
Sorry, I am not the original reporter, I just have a similar issue. You can see my work in https://github.com/NWACus/avy/pull/743

```
$ npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.80.5
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.5
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.5
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

One or more checks failed, indicating possible issues with the project.
```

The `why` output with peer dependencies removed:

```
$ npm why metro
metro@0.80.5
node_modules/metro
  metro@"0.80.5" from metro-config@0.80.5
  node_modules/metro-config
    metro-config@"0.80.5" from metro@0.80.5
    metro-config@"^0.80.3" from @react-native/community-cli-plugin@0.74.83
    node_modules/@react-native/community-cli-plugin
      @react-native/community-cli-plugin@"0.74.83" from react-native@0.74.1
      node_modules/react-native
        react-native@"0.74.1" from the root project
  metro@"0.80.5" from metro-transform-worker@0.80.5
  node_modules/metro-transform-worker
    metro-transform-worker@"0.80.5" from metro@0.80.5
  metro@"^0.80.3" from @react-native/community-cli-plugin@0.74.83
  node_modules/@react-native/community-cli-plugin
    @react-native/community-cli-plugin@"0.74.83" from react-native@0.74.1
    node_modules/react-native
      react-native@"0.74.1" from the root project
```

<details>
<summary> the entire output of <code>npm why metro</code>, long!</summary>

<code>
$ npm why metro
metro@0.80.5
node_modules/metro
  metro@"0.80.5" from metro-config@0.80.5
  node_modules/metro-config
    metro-config@"0.80.5" from metro@0.80.5
    metro-config@"^0.80.3" from @react-native/community-cli-plugin@0.74.83
    node_modules/@react-native/community-cli-plugin
      @react-native/community-cli-plugin@"0.74.83" from react-native@0.74.1
      node_modules/react-native
        react-native@"0.74.1" from the root project
        peer react-native@"*" from react-native-collapsible@1.6.0
        node_modules/react-native-collapsible
          react-native-collapsible@"^1.6.0" from the root project
        peer react-native@"*" from react-native-gesture-handler@2.16.2
        node_modules/react-native-gesture-handler
          react-native-gesture-handler@"~2.16.1" from the root project
          peer react-native-gesture-handler@">=1.4.0" from react-native-responsive-linechart@5.7.1
          node_modules/react-native-responsive-linechart
            react-native-responsive-linechart@"^5.7.1" from the root project
        peer react-native@">=0.61.3" from react-native-image-viewing@0.2.2
        node_modules/react-native-image-viewing
          react-native-image-viewing@"^0.2.2" from the root project
        peer react-native@">= 0.64.3" from react-native-maps@1.14.0
        node_modules/react-native-maps
          react-native-maps@"1.14.0" from the root project
        peer react-native@">=0.18.0" from react-native-public-ip@1.0.2
        node_modules/react-native-public-ip
          react-native-public-ip@"^1.0.2" from the root project
        peer react-native@"*" from react-native-render-html@6.3.4
        node_modules/react-native-render-html
          react-native-render-html@"^6.3.4" from the root project
        peer react-native@"*" from react-native-reanimated@3.10.1
        node_modules/react-native-reanimated
          react-native-reanimated@"~3.10.1" from the root project
        peer react-native@"*" from react-native-responsive-linechart@5.7.1
        node_modules/react-native-responsive-linechart
          react-native-responsive-linechart@"^5.7.1" from the root project
        peer react-native@"*" from react-native-safe-area-context@4.10.1
        node_modules/react-native-safe-area-context
          react-native-safe-area-context@"4.10.1" from the root project
          peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/bottom-tabs@6.5.5
          node_modules/@react-navigation/bottom-tabs
            @react-navigation/bottom-tabs@"^6.4.0" from the root project
          peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/elements@1.3.15
          node_modules/@react-navigation/elements
            @react-navigation/elements@"^1.3.15" from @react-navigation/bottom-tabs@6.5.5
            node_modules/@react-navigation/bottom-tabs
              @react-navigation/bottom-tabs@"^6.4.0" from the root project
            @react-navigation/elements@"^1.3.15" from @react-navigation/native-stack@6.9.10
            node_modules/@react-navigation/native-stack
              @react-navigation/native-stack@"^6.7.0" from the root project
          peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/native-stack@6.9.10
          node_modules/@react-navigation/native-stack
            @react-navigation/native-stack@"^6.7.0" from the root project
        peer react-native@"*" from react-native-screens@3.31.1
        node_modules/react-native-screens
          react-native-screens@"3.31.1" from the root project
          peer react-native-screens@">= 3.0.0" from @react-navigation/bottom-tabs@6.5.5
          node_modules/@react-navigation/bottom-tabs
            @react-navigation/bottom-tabs@"^6.4.0" from the root project
          peer react-native-screens@">= 3.0.0" from @react-navigation/native-stack@6.9.10
          node_modules/@react-navigation/native-stack
            @react-navigation/native-stack@"^6.7.0" from the root project
        peer react-native@"*" from react-native-svg@15.2.0
        node_modules/react-native-svg
          react-native-svg@"15.2.0" from the root project
          peer react-native-svg@">=7.0.0" from react-native-responsive-linechart@5.7.1
          node_modules/react-native-responsive-linechart
            react-native-responsive-linechart@"^5.7.1" from the root project
          peer react-native-svg@">=12.0.0" from react-native-svg-transformer@1.3.0
          node_modules/react-native-svg-transformer
            dev react-native-svg-transformer@"^1.3.0" from the root project
        peer react-native@">=0.59.0" from react-native-svg-transformer@1.3.0
        node_modules/react-native-svg-transformer
          dev react-native-svg-transformer@"^1.3.0" from the root project
        peer react-native@"*" from react-native-toast-message@2.1.6
        node_modules/react-native-toast-message
          react-native-toast-message@"^2.1.6" from the root project
        peer react-native@"*" from @gorhom/portal@1.0.14
        node_modules/@gorhom/portal
          @gorhom/portal@"1.0.14" from @mobile-reality/react-native-select-pro@2.2.2
          node_modules/@mobile-reality/react-native-select-pro
            @mobile-reality/react-native-select-pro@"^2.2.2" from the root project
        peer react-native@"*" from @jsamr/react-native-li@2.3.1
        node_modules/@jsamr/react-native-li
          @jsamr/react-native-li@"^2.3.0" from react-native-render-html@6.3.4
          node_modules/react-native-render-html
            react-native-render-html@"^6.3.4" from the root project
        peer react-native@">=0.63" from @mobile-reality/react-native-select-pro@2.2.2
        node_modules/@mobile-reality/react-native-select-pro
          @mobile-reality/react-native-select-pro@"^2.2.2" from the root project
        peer react-native@"^*" from @native-html/transient-render-engine@11.2.3
        node_modules/@native-html/transient-render-engine
          @native-html/transient-render-engine@"11.2.3" from react-native-render-html@6.3.4
          node_modules/react-native-render-html
            react-native-render-html@"^6.3.4" from the root project
        peer react-native@"*" from @react-native/virtualized-lists@0.74.83
        node_modules/@react-native/virtualized-lists
          @react-native/virtualized-lists@"0.74.83" from react-native@0.74.1
        peer react-native@">=0.59" from @react-native-camera-roll/camera-roll@5.2.4
        node_modules/@react-native-camera-roll/camera-roll
          @react-native-camera-roll/camera-roll@"^5.2.0" from the root project
        peer react-native@"^0.0.0-0 || >=0.60 <1.0" from @react-native-async-storage/async-storage@1.23.1
        node_modules/@react-native-async-storage/async-storage
          @react-native-async-storage/async-storage@"1.23.1" from the root project
          @react-native-async-storage/async-storage@"^1.21.0" from mixpanel-react-native@3.0.2
          node_modules/mixpanel-react-native
            mixpanel-react-native@"^3.0.2" from the root project
          peerOptional @react-native-async-storage/async-storage@">=1.0.0" from posthog-react-native@2.8.1
          node_modules/posthog-react-native
            posthog-react-native@"^2.8.1" from the root project
        peer react-native@"*" from @react-native-community/datetimepicker@8.0.1
        node_modules/@react-native-community/datetimepicker
          @react-native-community/datetimepicker@"8.0.1" from the root project
        peer react-native@">=0.65" from @react-native-community/hooks@3.0.0
        node_modules/@react-native-community/hooks
          @react-native-community/hooks@"^3.0.0" from the root project
        peer react-native@">=0.59" from @react-native-community/netinfo@11.3.1
        node_modules/@react-native-community/netinfo
          @react-native-community/netinfo@"11.3.1" from the root project
        peer react-native@">=0.62" from @react-native-community/segmented-control@2.2.2
        node_modules/@react-native-community/segmented-control
          @react-native-community/segmented-control@"^2.2.2" from the root project
        peer react-native@"*" from @react-native-picker/picker@2.7.5
        node_modules/@react-native-picker/picker
          @react-native-picker/picker@"2.7.5" from the root project
        peer react-native@">=0.62" from @react-native-segmented-control/segmented-control@2.5.2
        node_modules/@react-native-segmented-control/segmented-control
          @react-native-segmented-control/segmented-control@"2.5.2" from the root project
        peer react-native@"*" from @react-navigation/bottom-tabs@6.5.5
        node_modules/@react-navigation/bottom-tabs
          @react-navigation/bottom-tabs@"^6.4.0" from the root project
        peer react-native@"*" from @react-navigation/elements@1.3.15
        node_modules/@react-navigation/elements
          @react-navigation/elements@"^1.3.15" from @react-navigation/bottom-tabs@6.5.5
          node_modules/@react-navigation/bottom-tabs
            @react-navigation/bottom-tabs@"^6.4.0" from the root project
          @react-navigation/elements@"^1.3.15" from @react-navigation/native-stack@6.9.10
          node_modules/@react-navigation/native-stack
            @react-navigation/native-stack@"^6.7.0" from the root project
        peer react-native@"*" from @react-navigation/native@6.1.4
        node_modules/@react-navigation/native
          @react-navigation/native@"^6.0.11" from the root project
          peerOptional @react-navigation/native@">= 5.0.10" from posthog-react-native@2.8.1
          node_modules/posthog-react-native
            posthog-react-native@"^2.8.1" from the root project
          peer @react-navigation/native@"^6.0.0" from @react-navigation/bottom-tabs@6.5.5
          node_modules/@react-navigation/bottom-tabs
            @react-navigation/bottom-tabs@"^6.4.0" from the root project
          peer @react-navigation/native@"^6.0.0" from @react-navigation/elements@1.3.15
          node_modules/@react-navigation/elements
            @react-navigation/elements@"^1.3.15" from @react-navigation/bottom-tabs@6.5.5
            node_modules/@react-navigation/bottom-tabs
              @react-navigation/bottom-tabs@"^6.4.0" from the root project
            @react-navigation/elements@"^1.3.15" from @react-navigation/native-stack@6.9.10
            node_modules/@react-navigation/native-stack
              @react-navigation/native-stack@"^6.7.0" from the root project
          peer @react-navigation/native@"^6.0.0" from @react-navigation/native-stack@6.9.10
          node_modules/@react-navigation/native-stack
            @react-navigation/native-stack@"^6.7.0" from the root project
        peer react-native@"*" from @react-navigation/native-stack@6.9.10
        node_modules/@react-navigation/native-stack
          @react-navigation/native-stack@"^6.7.0" from the root project
        peer react-native@">=0.65.0" from @sentry/react-native@5.22.2
        node_modules/@sentry/react-native
          @sentry/react-native@"~5.22.0" from the root project
        peerOptional react-native@"*" from @tanstack/react-query@4.24.9
        node_modules/@tanstack/react-query
          @tanstack/react-query@"^4.24.9" from the root project
          peer @tanstack/react-query@"4.24.9" from @tanstack/react-query-persist-client@4.24.9
          node_modules/@tanstack/react-query-persist-client
            @tanstack/react-query-persist-client@"^4.24.9" from the root project
        peer react-native@">=0.59" from @testing-library/jest-native@5.4.2
        node_modules/@testing-library/jest-native
          dev @testing-library/jest-native@"^5.4.2" from the root project
        peer react-native@">=0.59" from @testing-library/react-native@11.5.2
        node_modules/@testing-library/react-native
          dev @testing-library/react-native@"^11.5.0" from the root project
  metro@"0.80.5" from metro-transform-worker@0.80.5
  node_modules/metro-transform-worker
    metro-transform-worker@"0.80.5" from metro@0.80.5
  metro@"^0.80.3" from @react-native/community-cli-plugin@0.74.83
  node_modules/@react-native/community-cli-plugin
    @react-native/community-cli-plugin@"0.74.83" from react-native@0.74.1
    node_modules/react-native
      react-native@"0.74.1" from the root project
      peer react-native@"*" from react-native-collapsible@1.6.0
      node_modules/react-native-collapsible
        react-native-collapsible@"^1.6.0" from the root project
      peer react-native@"*" from react-native-gesture-handler@2.16.2
      node_modules/react-native-gesture-handler
        react-native-gesture-handler@"~2.16.1" from the root project
        peer react-native-gesture-handler@">=1.4.0" from react-native-responsive-linechart@5.7.1
        node_modules/react-native-responsive-linechart
          react-native-responsive-linechart@"^5.7.1" from the root project
      peer react-native@">=0.61.3" from react-native-image-viewing@0.2.2
      node_modules/react-native-image-viewing
        react-native-image-viewing@"^0.2.2" from the root project
      peer react-native@">= 0.64.3" from react-native-maps@1.14.0
      node_modules/react-native-maps
        react-native-maps@"1.14.0" from the root project
      peer react-native@">=0.18.0" from react-native-public-ip@1.0.2
      node_modules/react-native-public-ip
        react-native-public-ip@"^1.0.2" from the root project
      peer react-native@"*" from react-native-render-html@6.3.4
      node_modules/react-native-render-html
        react-native-render-html@"^6.3.4" from the root project
      peer react-native@"*" from react-native-reanimated@3.10.1
      node_modules/react-native-reanimated
        react-native-reanimated@"~3.10.1" from the root project
      peer react-native@"*" from react-native-responsive-linechart@5.7.1
      node_modules/react-native-responsive-linechart
        react-native-responsive-linechart@"^5.7.1" from the root project
      peer react-native@"*" from react-native-safe-area-context@4.10.1
      node_modules/react-native-safe-area-context
        react-native-safe-area-context@"4.10.1" from the root project
        peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/bottom-tabs@6.5.5
        node_modules/@react-navigation/bottom-tabs
          @react-navigation/bottom-tabs@"^6.4.0" from the root project
        peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/elements@1.3.15
        node_modules/@react-navigation/elements
          @react-navigation/elements@"^1.3.15" from @react-navigation/bottom-tabs@6.5.5
          node_modules/@react-navigation/bottom-tabs
            @react-navigation/bottom-tabs@"^6.4.0" from the root project
          @react-navigation/elements@"^1.3.15" from @react-navigation/native-stack@6.9.10
          node_modules/@react-navigation/native-stack
            @react-navigation/native-stack@"^6.7.0" from the root project
        peer react-native-safe-area-context@">= 3.0.0" from @react-navigation/native-stack@6.9.10
        node_modules/@react-navigation/native-stack
          @react-navigation/native-stack@"^6.7.0" from the root project
      peer react-native@"*" from react-native-screens@3.31.1
      node_modules/react-native-screens
        react-native-screens@"3.31.1" from the root project
        peer react-native-screens@">= 3.0.0" from @react-navigation/bottom-tabs@6.5.5
        node_modules/@react-navigation/bottom-tabs
          @react-navigation/bottom-tabs@"^6.4.0" from the root project
        peer react-native-screens@">= 3.0.0" from @react-navigation/native-stack@6.9.10
        node_modules/@react-navigation/native-stack
          @react-navigation/native-stack@"^6.7.0" from the root project
      peer react-native@"*" from react-native-svg@15.2.0
      node_modules/react-native-svg
        react-native-svg@"15.2.0" from the root project
        peer react-native-svg@">=7.0.0" from react-native-responsive-linechart@5.7.1
        node_modules/react-native-responsive-linechart
          react-native-responsive-linechart@"^5.7.1" from the root project
        peer react-native-svg@">=12.0.0" from react-native-svg-transformer@1.3.0
        node_modules/react-native-svg-transformer
          dev react-native-svg-transformer@"^1.3.0" from the root project
      peer react-native@">=0.59.0" from react-native-svg-transformer@1.3.0
      node_modules/react-native-svg-transformer
        dev react-native-svg-transformer@"^1.3.0" from the root project
      peer react-native@"*" from react-native-toast-message@2.1.6
      node_modules/react-native-toast-message
        react-native-toast-message@"^2.1.6" from the root project
      peer react-native@"*" from @gorhom/portal@1.0.14
      node_modules/@gorhom/portal
        @gorhom/portal@"1.0.14" from @mobile-reality/react-native-select-pro@2.2.2
        node_modules/@mobile-reality/react-native-select-pro
          @mobile-reality/react-native-select-pro@"^2.2.2" from the root project
      peer react-native@"*" from @jsamr/react-native-li@2.3.1
      node_modules/@jsamr/react-native-li
        @jsamr/react-native-li@"^2.3.0" from react-native-render-html@6.3.4
        node_modules/react-native-render-html
          react-native-render-html@"^6.3.4" from the root project
      peer react-native@">=0.63" from @mobile-reality/react-native-select-pro@2.2.2
      node_modules/@mobile-reality/react-native-select-pro
        @mobile-reality/react-native-select-pro@"^2.2.2" from the root project
      peer react-native@"^*" from @native-html/transient-render-engine@11.2.3
      node_modules/@native-html/transient-render-engine
        @native-html/transient-render-engine@"11.2.3" from react-native-render-html@6.3.4
        node_modules/react-native-render-html
          react-native-render-html@"^6.3.4" from the root project
      peer react-native@"*" from @react-native/virtualized-lists@0.74.83
      node_modules/@react-native/virtualized-lists
        @react-native/virtualized-lists@"0.74.83" from react-native@0.74.1
      peer react-native@">=0.59" from @react-native-camera-roll/camera-roll@5.2.4
      node_modules/@react-native-camera-roll/camera-roll
        @react-native-camera-roll/camera-roll@"^5.2.0" from the root project
      peer react-native@"^0.0.0-0 || >=0.60 <1.0" from @react-native-async-storage/async-storage@1.23.1
      node_modules/@react-native-async-storage/async-storage
        @react-native-async-storage/async-storage@"1.23.1" from the root project
        @react-native-async-storage/async-storage@"^1.21.0" from mixpanel-react-native@3.0.2
        node_modules/mixpanel-react-native
          mixpanel-react-native@"^3.0.2" from the root project
        peerOptional @react-native-async-storage/async-storage@">=1.0.0" from posthog-react-native@2.8.1
        node_modules/posthog-react-native
          posthog-react-native@"^2.8.1" from the root project
      peer react-native@"*" from @react-native-community/datetimepicker@8.0.1
      node_modules/@react-native-community/datetimepicker
        @react-native-community/datetimepicker@"8.0.1" from the root project
      peer react-native@">=0.65" from @react-native-community/hooks@3.0.0
      node_modules/@react-native-community/hooks
        @react-native-community/hooks@"^3.0.0" from the root project
      peer react-native@">=0.59" from @react-native-community/netinfo@11.3.1
      node_modules/@react-native-community/netinfo
        @react-native-community/netinfo@"11.3.1" from the root project
      peer react-native@">=0.62" from @react-native-community/segmented-control@2.2.2
      node_modules/@react-native-community/segmented-control
        @react-native-community/segmented-control@"^2.2.2" from the root project
      peer react-native@"*" from @react-native-picker/picker@2.7.5
      node_modules/@react-native-picker/picker
        @react-native-picker/picker@"2.7.5" from the root project
      peer react-native@">=0.62" from @react-native-segmented-control/segmented-control@2.5.2
      node_modules/@react-native-segmented-control/segmented-control
        @react-native-segmented-control/segmented-control@"2.5.2" from the root project
      peer react-native@"*" from @react-navigation/bottom-tabs@6.5.5
      node_modules/@react-navigation/bottom-tabs
        @react-navigation/bottom-tabs@"^6.4.0" from the root project
      peer react-native@"*" from @react-navigation/elements@1.3.15
      node_modules/@react-navigation/elements
        @react-navigation/elements@"^1.3.15" from @react-navigation/bottom-tabs@6.5.5
        node_modules/@react-navigation/bottom-tabs
          @react-navigation/bottom-tabs@"^6.4.0" from the root project
        @react-navigation/elements@"^1.3.15" from @react-navigation/native-stack@6.9.10
        node_modules/@react-navigation/native-stack
          @react-navigation/native-stack@"^6.7.0" from the root project
      peer react-native@"*" from @react-navigation/native@6.1.4
      node_modules/@react-navigation/native
        @react-navigation/native@"^6.0.11" from the root project
        peerOptional @react-navigation/native@">= 5.0.10" from posthog-react-native@2.8.1
        node_modules/posthog-react-native
          posthog-react-native@"^2.8.1" from the root project
        peer @react-navigation/native@"^6.0.0" from @react-navigation/bottom-tabs@6.5.5
        node_modules/@react-navigation/bottom-tabs
          @react-navigation/bottom-tabs@"^6.4.0" from the root project
        peer @react-navigation/native@"^6.0.0" from @react-navigation/elements@1.3.15
        node_modules/@react-navigation/elements
          @react-navigation/elements@"^1.3.15" from @react-navigation/bottom-tabs@6.5.5
          node_modules/@react-navigation/bottom-tabs
            @react-navigation/bottom-tabs@"^6.4.0" from the root project
          @react-navigation/elements@"^1.3.15" from @react-navigation/native-stack@6.9.10
          node_modules/@react-navigation/native-stack
            @react-navigation/native-stack@"^6.7.0" from the root project
        peer @react-navigation/native@"^6.0.0" from @react-navigation/native-stack@6.9.10
        node_modules/@react-navigation/native-stack
          @react-navigation/native-stack@"^6.7.0" from the root project
      peer react-native@"*" from @react-navigation/native-stack@6.9.10
      node_modules/@react-navigation/native-stack
        @react-navigation/native-stack@"^6.7.0" from the root project
      peer react-native@">=0.65.0" from @sentry/react-native@5.22.2
      node_modules/@sentry/react-native
        @sentry/react-native@"~5.22.0" from the root project
      peerOptional react-native@"*" from @tanstack/react-query@4.24.9
      node_modules/@tanstack/react-query
        @tanstack/react-query@"^4.24.9" from the root project
        peer @tanstack/react-query@"4.24.9" from @tanstack/react-query-persist-client@4.24.9
        node_modules/@tanstack/react-query-persist-client
          @tanstack/react-query-persist-client@"^4.24.9" from the root project
      peer react-native@">=0.59" from @testing-library/jest-native@5.4.2
      node_modules/@testing-library/jest-native
        dev @testing-library/jest-native@"^5.4.2" from the root project
      peer react-native@">=0.59" from @testing-library/react-native@11.5.2
      node_modules/@testing-library/react-native
        dev @testing-library/react-native@"^11.5.0" from the root project
</code>

</details>

**Comment by brentvatne** [comment]
@stevekuznetsov - thank you! could you try clearing your yarn.lock and running yarn install again to see if it you end up with the latest metro version? my guess is that because the dependency version range uses `^`, yarn somehow ended up not grabbing the latest version of metro packages due to the state of existing packages.

**Comment by brentvatne** [comment]
i also noticed in your project you install `@expo/config` as a dependency - i recommend importing it from the `expo` package instead, with `expo/config`

**Comment by codeOlam** [comment]
> @stevekuznetsov - thank you! could you try clearing your yarn.lock and running yarn install again to see if it you end up with the latest metro version? my guess is that because the dependency version range uses `^`, yarn somehow ended up not grabbing the latest version of metro packages due to the state of existing packages.

I am going to try this to see if it will fix the issue.

**Comment by stevekuznetsov** [comment]
@brentvatne thanks, your first suggestion to remove `yarn.lock` and refresh everything worked! I also saw the `^` constraint and couldn't figure out why the older version was sticky ... 

Thank you!

**Comment by maks-io** [comment]
Hey everyone, i would like to add that i ran into the exact same problem. The `yarn.lock` removal and reinstall also worked for me, so thanks very much for the hint! Can somebody explain maybe how one can end up in such a scenario in the first place?

**Comment by WillSmithTE** [comment]
Likewise here, I don't love removing lock files without good reason

**Comment by brentvatne** [comment]
@WillSmithTE - your package manager likely supports a command to bump a single transitive dependency version to the latest semver compatible one

**Comment by Nicomalacho** [comment]
Removing the lock files worked for me. thanks

**Comment by Dm-R** [comment]
> @stevekuznetsov - thank you! could you try clearing your yarn.lock and running yarn install again to see if it you end up with the latest metro version? my guess is that because the dependency version range uses `^`, yarn somehow ended up not grabbing the latest version of metro packages due to the state of existing packages.

Also worked for me. Thanks!

**Comment by christinachimi** [comment]
For anyone who ends up here - I have a yarn 4 monorepo and just running `yarn up metro` did not work - `yarn up metro -R` (and the same for metro-config, metro-resolver, and metro-core) seemed to do the trick.

**Comment by Willibaur** [comment]
it seems that `metro-core` is the one causing the problem sometimes so by doing `yarn update metro-core -R` fixes the problem in our case without removing yarn.lock
