### ISSUE TITLE
Dev tools: offline mode requires internet. Can't develop on an airplane 😢

### ISSUE THREAD

**Issue by jaredly** [expo/expo#2889]
### Environment

<details>
<pre>
  Expo CLI 2.4.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.2
    npmGlobalPackages:
      expo-cli: 2.4.0
</pre>
</details>

Targeting Android

### Steps to Reproduce

1. be on an airplane (or just turn off wifi/data on phone, and turn off wifi on laptop)
2. connect android device to computer w/ USB
3. run `expo start --offline`
4. in the expo UI, change connection type from "LAN" to "Local"
5. click "Run on Android device/emulator"

### Expected Behavior

it would run

### Actual Behavior

after the expo bundler & stuff work just fine, the expo app on android gives me a blue screen with "expo requires an internet connection"

### Reproducible Demo

This happens with the stock boilerplate, no special code needed.

**Comment by esamelson** [comment]
This is fixed as of SDK 35/expo-cli. Closing this now, if this is a problem in the future please open a new issue on the [expo-cli repo](https://github.com/expo/expo-cli). Thanks!
