### ISSUE TITLE
XDE freezes regularly on OSX - have to kill and restart

### ISSUE THREAD

**Issue by edwardsilhol** [expo/expo#289]
Unfortunately, I haven't been able to find a workflow to reproduce systematically. It happens quite frequently. The XDE UI stops responding, and on the simulator I can't refresh the app.

I'm on OSX Sierra, 10.12.5. XDE is 2.18.0.

**Comment by dikaiosune** [comment]
Hi! Does this happen when XDE has been in the background for a while? Does it still happen after updating XDE to 2.19.2 or newer?

**Comment by danieltr10** [comment]
It happens to me too on Sierra 10.12.1.
Really annoying :/
