### ISSUE TITLE
iOS Expo client accessibility: Elements of previous screens are still visible to Voiceover, making it unuseable

### ISSUE THREAD

**Issue by Neurrone** [expo/expo#2890]
### Environment

```
  Expo CLI 2.6.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

### Steps to Reproduce

1. Install the Expo Client on an iOS device (in my case, an iPhone 7+). Activate Voiceover, the built-in screen reader.
2. Start an expo project (any will do, but I picked the blank template, since I'm still working my way through the quickstart tutorial.
3. Launch the app with `npm start`, and load it onto the client.
4. Use voiceover to explore the screen.

### Expected Behavior

In addition to the visible Expo-related elements on the screen, Voiceover should only find one other element, text reading "Open up App.js to start working on your app!", which corresponds to the contents of `app.js`.

### Actual Behavior

When swiping left and right with one finger, or moving your fingers across the screen, elements "underneath" the current screen are visible and being read out by voiceover, even though they shouldn't be. 

Although the elements from my app itself do show up on Voiceover, having so much clutter from these invisible elements showing up makes it virtually impossible to get anything done, as I can't replicate how I would navigate around in my app. This is even worse when you cause a stack trace to occur, and it still reads even after dismissing it.

This appears to be an issue for the entire client application, not just these specific screens.

### Reproducible Demo

Use `expo init`, and select the blank template.

---

Please let me know if I can provide more information. 
I really hope this gets fixed, since Expo won't be a viable development platform for blind developers otherwise.

**Comment by EvanBacon** [comment]
Please look into `react-native-screens` which is part of `react-navigation` https://github.com/kmagiera/react-native-screens

Currently you are just presenting views on top of other views. Really you should be enabling screens which let the system know that only the upper-most screen should be read.

You can do this like so:
1. Use `react-navigation`

2. Enable screens
```js
import { useScreens } from 'react-native-screens';
useScreens();
```

**Comment by Neurrone** [comment]
@EvanBacon thanks for the explanation; I'll try it.

However, these problems still occur internally for various screens of the expo client, and it would be good if that's fixed.

I think the documentation and templates should also be updated so that it uses a screen by default, unless there are disadvantages of doing so.

**Comment by brentvatne** [comment]
this fix will be included in our next release of the expo client! not sure when exactly that will be though
