### ISSUE TITLE
Error on Android build after SDK 51: compileSdkVersion is not specified

### ISSUE THREAD

**Issue by ampopdev** [expo/expo#28915]
### Minimal reproducible example

https://github.com/ampopdev/demo-my-app-expo

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Just run: `yarn && npx react-native run-android` on the minimal reproducible example. Then getting error:
```
Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build completed with 2 failures. 1: Task failed with an exception.
-----------
* Where:
Script '*/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 408 * What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-application'. > Failed to notify project evaluation listener. > com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle > Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer. * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
============================================================================== 2: Task failed with an exception.
-----------
* Where:
Script '*/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 85 * What went wrong:
A problem occurred configuring project ':expo'.
> Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer. * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
============================================================================== BUILD FAILED in 12s.
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.1/bin/yarn
      npm: 10.7.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by yourjhay** [comment]
I have similar issue as well, well might be different but I believe it's related to this.

![Screenshot 2024-05-15 at 11 48 42 PM](https://github.com/expo/expo/assets/25504356/1a9effb5-58e3-48de-bb3e-5a398ab9cd58)

The build also failed but related to expo-file-system

If anyone has the same problem as me, I hope you can give me an insight related to this one..

**Comment by brentvatne** [comment]
hi there! please provide a minimal reproducible example. your repo has over 100 dependencies!

**Comment by brentvatne** [comment]
also, if you're seeing that error in expo-application compiling, try running` npm why expo-application` - you probably have a package that is installing an old version of it

**Comment by ampopdev** [comment]
@brentvatne removed the extra dependencies and after running `npm why expo-application` I noticed the expo-notifications needed to be upgrade from 27 -> 28. So that error was removed, but I now I have error:

```
MainApplication.kt:41:9 Unresolved reference: BuildConfig
```

Tried adding `android.defaults.buildfeatures.buildconfig=true` in `gradle.properties`, but didn't help. So something might be necessary to be updated on expo-notifications. Opened a new issue [here](https://github.com/expo/expo/issues/28943)

**Comment by JacobDel** [comment]
my dirty fix is adding `compileSdkVersion 34` to all the `build.gradle` files of the expo packages in node_modules (expo-image-loader, expo-image-manipulator and expo-image-picker in my case).
Looks like this:
```
android {
  // Remove this if and it's contents, when support for SDK49 is dropped
  compileSdkVersion 34 // ADDED
  if (!safeExtGet("expoProvidesDefaultConfig", false)) {
    // compileSdkVersion safeExtGet("compileSdkVersion", 34) // REMOVED

    defaultConfig {
      minSdkVersion safeExtGet("minSdkVersion", 23)
      targetSdkVersion safeExtGet("targetSdkVersion", 34)
    }
...

```
But hoping for a cleaner fix..

**Comment by hellfreezes** [comment]
Just upgrade my project from sdk 50 to sdk 51
I have lastest expo-notifications (0.28.5)
```
expo-application@5.9.1
node_modules/expo-application
  expo-application@"~5.9.0" from expo-notifications@0.28.5
  node_modules/expo-notifications
    expo-notifications@"~0.28.5" from the root project
```

But still the same errors:
```
[RUN_GRADLEW] ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.25.15)
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1:
[RUN_GRADLEW] Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Script '/private/var/folders/nz/sdkcbvxj1cl6yb6lny06rxh40000gn/T/eas-build-local-nodejs/820d9ae0-b3d1-4fb7-9a76-2422028c3502/build/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 408
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Script '/private/var/folders/nz/sdkcbvxj1cl6yb6lny06rxh40000gn/T/eas-build-local-nodejs/820d9ae0-b3d1-4fb7-9a76-2422028c3502/build/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 85
```

Any ideas what to do?

**Comment by brentvatne** [comment]
@hellfreezes - can you share a minimal reproducible example? i'm not sure how to reproduce this

**Comment by hellfreezes** [comment]
> @hellfreezes - can you share a minimal reproducible example? i'm not sure how to reproduce this

Thanks for quick answer.
I'm already find the issue. In my case it was the required version of NDK was not installed (v. 26.1.10909125).

**Comment by geovane7881** [comment]
@hellfreezes thanks too much

**Comment by prawee** [comment]
@JacobDel Thanks!
another way to configure with app.json
it's work for me
`
[
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 34,
            "targetSdkVersion": 34,
            "buildToolsVersion": "34.0.0"
          },
          "ios": {
            "deploymentTarget": "13.4"
          }
        }
      ],
`

**Comment by yourjhay** [comment]
> I have similar issue as well, well might be different but I believe it's related to this.
> 
> ![Screenshot 2024-05-15 at 11 48 42 PM](https://private-user-images.githubusercontent.com/25504356/331233954-1a9effb5-58e3-48de-bb3e-5a398ab9cd58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTkzMzYsIm5iZiI6MTcxODMxOTAzNiwicGF0aCI6Ii8yNTUwNDM1Ni8zMzEyMzM5NTQtMWE5ZWZmYjUtNThlMy00OGRlLWJiM2UtNWEzOThhYjljZDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDIyNTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMWJlYWFhOTYyOTBiZDBmNTNlYjYwNDMyNTk4YTY5ZDQ1MmE1ODY3M2M1OTc1MDM2OGZlMzAxZWRkYmU5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jLfcZAk0dyg8JqQcfuC1KHZOhJFln2W3z8wweA3bYcA)
> 
> The build also failed but related to expo-file-system
> 
> If anyone has the same problem as me, I hope you can give me an insight related to this one..

SOLUTION:
For this case similar to mine. **npx expo install --fix** doesn't seem to update the expo-file-system to the correct version, I then install the version 17 and the build succeeded.

**Comment by astoiccoder** [comment]
Had the same error and it was fixed after I did the following (didn't try it in between, so I can't say which step resolved it):

- replaced deprecated `sentry-expo` dependency with `@sentry/react-native`
- updated android sdks to newest versions
- removed `eas-cli` dependency from my `package.json` [since it is strongly discouraged to have it in the project dependencies](https://github.com/expo/eas-cli?tab=readme-ov-file#enforcing-eas-cli-version-for-your-project). While I had the dependency in the `package.json` `expo-doctor` kept complaining about version conflicts as indicated in the linked readme. After removing the dependency, `expo-doctor` ran through without complaining.

**Comment by wajahat9876** [comment]
i have solved this error by doing this in react native expo code :
first goto node-module -> expo-camera -> android -> build.gradle file and add these lines:
android {
   // Remove this if and it's contents, when support for SDK49 is dropped
+  compileSdkVersion 34
   if (!safeExtGet("expoProvidesDefaultConfig", false)) {
-    compileSdkVersion safeExtGet("compileSdkVersion", 34)

     defaultConfig {
       minSdkVersion safeExtGet("minSdkVersion",23)
       targetSdkVersion safeExtGet("targetSdkVersion", 34)
     }
 
     publishing {
-      singleVariant("release")
 {
+      {
         withSourcesJar()
       }
     }
else dont change anythings: the + sign show that these lines added and - sign shows that i removed these lines.

**Comment by fristicool** [comment]
I deleted some packages that I installed and didn't use (Solved the problem).
Probably incompatible with SDK 51.
In my case I had the luck that the incompatible packages where the packages I didn't need. 
This might not be the case for every one.

`npm uninstall supercluster react-native-star-rating react-native-star-rating react-native-ratings react-native-linear-gradient react-native-fast-image react-native-expo-image-cache @types/supercluster`

These were the packages that I uninstalled.

**Comment by arapocket** [comment]
Why on earth is this closed

**Comment by arapocket** [comment]
Update: I saw in another issue to delete node_modules and reinstall. After doing this i no longer got this message. The two errors i got afterwards were easier to follow (had to update a package and set `minSdkVersion` in app.config.

**Comment by lafest** [comment]
https://github.com/expo/expo/blob/sdk-50/packages/expo-modules-core/android/ExpoModulesCorePlugin.gradle#L6
https://github.com/expo/expo/blob/sdk-50/packages/expo/android/build.gradle#L93

because `expoProvidesDefaultConfig` is true, and so, https://github.com/expo/expo/blob/sdk-50/packages/expo/android/build.gradle#L94-L109 did not executed. I think this is why error occured in sdk 50.

But I have no idea why this occurs in sdk 51.

https://github.com/expo/expo/blob/sdk-51/packages/expo-application/android/build.gradle#L10
https://github.com/expo/expo/blob/sdk-51/packages/expo-modules-core/android/ExpoModulesCorePlugin.gradle#L52-L66
according to these references, in sdk 51, it seems that the way to setup default compileSdkVersion is changed well..

**Comment by rudiss** [comment]
This is still happing in sdk51 why is close ?

**Comment by tamagutchi** [comment]
+1

**Comment by csille00** [comment]
+1

**Comment by jukkamarttinen** [comment]
+1

**Comment by netojose** [comment]
+1

**Comment by thomashagstrom** [comment]
Still an issue in expo `52.0.17`

**Comment by theblondealex** [comment]
This is still an issue for me in expo 52

**Comment by Padma-Dev-E** [comment]
> my dirty fix is adding `compileSdkVersion 34` to all the `build.gradle` files of the expo packages in node_modules (expo-image-loader, expo-image-manipulator and expo-image-picker in my case). Looks like this:
> 
> ```
> android {
>   // Remove this if and it's contents, when support for SDK49 is dropped
>   compileSdkVersion 34 // ADDED
>   if (!safeExtGet("expoProvidesDefaultConfig", false)) {
>     // compileSdkVersion safeExtGet("compileSdkVersion", 34) // REMOVED
> 
>     defaultConfig {
>       minSdkVersion safeExtGet("minSdkVersion", 23)
>       targetSdkVersion safeExtGet("targetSdkVersion", 34)
>     }
> ...
> ```
> 
> But hoping for a cleaner fix..

This worked along with i created post patch for expo-device also
and install proper version of few
expo install expo-intent-launcher

**Comment by skarensmoll** [comment]
+1

**Comment by skarensmoll** [comment]
this issue should be reoppened

**Comment by song06971** [comment]
I fixed the issue by running

npx expo-doctor@latest
npx expo install --check

also added to app.json

"expo-build-properties",
{
...
"android": {
"compileSdkVersion": 34,
"targetSdkVersion": 34,
"buildToolsVersion": "34.0.0",
...
}
}

Copied a lot of incompatible packages from an earlier expo sdk 50 project.

**Comment by sebastianp95** [comment]
I tried everything, and it turns out I had a deprecated dependency I couldn't work around, so I had to remove it. Lucky me, I didn’t have to refactor much, but yes, this is most likely a dependency discrepancy error.

**Comment by AngeloD2** [comment]
I had Firebase on my project, so this may not work for everyone.
Changes to the top level build.gradle won't take effect in android/app/build.grade until you've run this command for Expo: **npx expo prebuild --clean**

 _Some react-native-firebase modules require custom native config steps, add them first as a plugin to the app.config file, then run **npx expo prebuild --clean** to apply native changes before the run commands._

You can specify specific platforms as well by adding the --platform flag. (ex. **npx expo prebuild --clean --platform=android**

**Comment by EsdrasAlbino** [comment]
+1

**Comment by Misterdjack** [comment]
For anyone else who may need it. Change the ^ compatible versioning on all Expo packages to exact or ~ approximate versions and it may fix this error.  I found this solution here: https://www.reddit.com/r/expo/comments/1k1opo0/npx_expo_runandroid_fails_plugin_id/
