### ISSUE TITLE
Both "expo prebuild" and "expo run:android" commands fail due to invalid URL string

### ISSUE THREAD

**Issue by elektromob** [expo/expo#28916]
### Summary

Upon invoking `expo prebuild` or `expo run:android`, following is printed:

```
Could not parse JSON returned from "npm view expo-template-bare-minimum@sdk-51 dist.tarball --json".
https://registry.npmjs.org/expo-template-bare-minimum/-/expo-template-bare-minimum-51.0.26.tgz
Error: Unexpected token 'h', "https://re/"... is not valid JSON
✖ Failed to create the native directories
You may want to delete the ./ios and/or ./android directories before trying again.
```
This may be due to the fact that `npm view expo-template-bare-minimum@sdk-51 dist.tarball --json` doesn't *return* JSON, and instead returns a string with value `https://registry.npmjs.org/expo-template-bare-minimum/-/expo-template-bare-minimum-51.0.26.tgz`. Removing `dist.tarball` from the `npm view ...` command results in a JSON file being returned.

### What platform(s) does this occur on?

Arch Linux.
Output of `uname -a`: `Linux vivo 6.8.9-zen1-2-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000 x86_64 GNU/Linux`

### SDK Version

51.0.26

### Environment

    System:
      OS: Linux 6.8 Arch Linux
      Shell: 5.2.26 - /usr/bin/bash
    Binaries:
      Node: 22.0.0 - /usr/bin/node
      npm: 10.8.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 26, 34
        Build Tools: 33.0.1, 34.0.0, 35.0.0
        System Images: android-26 | Intel x86 Atom
    IDEs:
      Android Studio: AI-233.14808.21.2331.11709847
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/elektromob/ExpoError/tree/main

**Comment by elektromob** [comment]
## Update

Following is a temporary fix:

`npx expo prebuild --template https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum`

**Comment by byCedric** [comment]
Hi @elektromob, thanks for the report. It's interesting what's going on here, my best guess is that either Linux or npm decided to change its output. Basically, how this works is that it should be parsing the string, _with_ the quotes. Meaning that it's technically just a valid JSON string, e.g.

<img width="936" alt="image" src="https://github.com/expo/expo/assets/1203991/d5351118-2ec2-4dde-b5aa-470710e9a4a4">

But, we can make that less brittle.

**Comment by elektromob** [comment]
@byCedric I would like to add that running `npx expo prebuild --template https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum` only *once* makes *all* further `npx expo prebuild` and `npx expo run:android` commands work without a problem.

I would also like to add that the same problem happens when `npx eas-cli build --local --platform android --profile $PROFILE` is invoked as well, where `$PROFILE` is either `preview` or `development`. This wasn't specified in the initial body of the issue, so I apologize.

**Comment by byCedric** [comment]
Yep, I just found the issue. It's Node 22.2.0 returning a different response than Node <22.0.0

<img width="694" alt="image" src="https://github.com/expo/expo/assets/1203991/b3cde45f-c194-4f6f-a232-3893ec8fb580">

**Comment by byCedric** [comment]
Forwarded this issue https://github.com/npm/cli/issues/7537, I'll also backport & release the fix ASAP.

**Comment by byCedric** [comment]
Heads up, `npm@10.8.1` will likely (not released yet) ship with a fix. See https://github.com/npm/cli/issues/7537

For now, only SDK 51 has been patched. We will likely hold off on backporting this to older versions, as npm seems to fix it soon-ish.

**Comment by sainjay** [comment]
If you have a corporate or private npm registry configured, make sure you login into it before proceeding. After login, the issue got resolved for me.
