### ISSUE TITLE
`openDrawer` and close are missing from `useNavigation` from `expo-router`

### ISSUE THREAD

**Issue by pvinis** [expo/expo#28925]
### Minimal reproducible example

https://snack.expo.dev/@pvinis/react-navigation-playground

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

It seems the `useNavigation` hook has different types in expo-router than react navigation.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.0 - ~/.local/share/mise/installs/node/20/bin/node
      Yarn: 1.22.19 - ~/.local/share/mise/installs/yarn/1/bin/yarn
      npm: 10.5.2 - ~/.local/share/mise/installs/node/20/bin/npm
    Managers:
      CocoaPods: 1.14.2 - /Users/pvinis/.local/share/mise/installs/ruby/3.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.7 => 51.0.7
      expo-router: ~3.5.14 => 3.5.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.11 => 0.19.11
    Expo Workflow: managed

**Comment by masarbazi** [comment]
Many other properties missing from `useNavigation` and typescript keeps throwing errors. This issue should be reopened.
`toggleDrawer`, `openDrawer`, `closeDrawer`, `jumpTo`, ...

**Comment by Cancercookie** [comment]
+1
