### ISSUE TITLE
[SDK 51] Fonts with spaces fail to load on Android

### ISSUE THREAD

**Issue by Mookiies** [expo/expo#28937]
### Minimal reproducible example

https://github.com/Mookiies/expo51-font-repo

Made with `npx create-expo-app@latest -t bare-minimum`

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Loading a font with a space in the file name, e.g. `Helvetica Now Display.otf` , fails to load on android.

The error is:
```
Error: Call to function 'ExpoAsset.downloadAsync' has been rejected.
→ Caused by: The 1st argument cannot be cast to type java.net.URI (received class java.lang.String)
→ Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 72: http://localhost:8081/assets/?unstable_path=.%2Fassets%2Ffonts/Helvetica Now Display.otf?platform=android&hash=59bb1b1be854c3f7c9ca3e8d0e62cdd4] 
    at App (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.fontdemo&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:129996:44)
    at withDevTools(App) (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.fontdemo&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:129781:27)
    at RCTView
    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.fontdemo&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:73605:43)
    at RCTView
    at View (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.fontdemo&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:73605:43)
    at AppContainer (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.fontdemo&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:73448:25)
    at main(RootComponent) (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.fontdemo&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:116956:28
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.asdf/installs/nodejs/18.20.2/bin/node
      Yarn: 1.22.10 - ~/.asdf/shims/yarn
      npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/<user>/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions

Detailed check results:

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

One or more checks failed, indicating possible issues with the project.

**Comment by Mookiies** [comment]
These fonts have spaces in their PostScript names, so while removing spaces from the file name gets it to load, having those be the same is important as recommended by the [expo-font docs](https://docs.expo.dev/develop/user-interface/fonts/#use-a-custom-font)

**Comment by jludwiggreenaction** [comment]
Your repro link is throwing 404. Is this still an issue?

**Comment by Mookiies** [comment]
@jludwiggreenaction Yes this is still an issue. I upgraded my example to expo@latest and expo-font@latest and it's still occurring.

The [repro](https://github.com/Mookiies/expo51-font-repo) was accidentally set to private. It should work now.

**Comment by NiccoloCase** [comment]
same issue from today

**Comment by yoinker57** [comment]
I have the same issue today

**Comment by NiccoloCase** [comment]
in my case the problem was that I was resolving a specific version of 
expo-asset in package.json

> I have the same issue today

**Comment by jake-carpenter** [comment]
> in my case the problem was that I was resolving a specific version of expo-asset in package.json

Which version fixed it for you? I'm about to update 0.25.19 => 0.25.21 as suggested by expo-doctor, but I'm not exactly hopeful it will fix my issue.

**Comment by NiccoloCase** [comment]
> > in my case the problem was that I was resolving a specific version of expo-asset in package.json
> 
> Which version fixed it for you? I'm on the latest expo-asset suggested by expo-doctor, and am about to update expo-updates 0.25.19 => 0.25.21, but I'm not exactly hopeful it will fix my issue.

I was on Expo 48 with this resolution for expo-asset (I don't remember why I had it)
```
"resolutions": {
    "@types/react": "~17.0.47",
    "expo/expo-asset": "8.9.1"
  },
```
and I switched to expo 51. Removing the resolution did the trick

**Comment by AboodyAlaze** [comment]
Hey 
i fix this Issue By Remove The Space of font.ttf I Mean If You Have Font His Name Like This => (font git.ttf) make it like this
(fontgit.ttf) just Remove The Space And it Will Work 
if You Eject The Project for Android Add The Font in
android/app/src/main/assets/fonts/fontgit.ttf
i Hope This Will Help
