### ISSUE TITLE
Expo App not building on windows system

### ISSUE THREAD

**Issue by nayan-dey** [expo/expo#28939]
### Summary

I'm trying out the new [react-conf-app](https://github.com/expo/react-conf-app) and try to build it on my local machine using 
this command called `npx expo run:android --variant debug` but every time i run it i get this error of `expo-file-system`
![Screenshot 2024-05-17 073232](https://github.com/expo/expo/assets/133354699/dc746d64-ed0e-47e0-801a-05b53a1a99af)

The same command I ran on my friends mac machine it ran perfectly fine without any configuration
he just added the local.properties on his newly created android folder with prebuild 

i want to know is there any other commands to run/create a development build on my local machine without using eas

if yes please help me with this
i cannot clone or run any expo project i get the same error on every project

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

  "expo-dev-client": "~4.0.14",
 "expo-updates": "~0.25.14",

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10300.40.2321.11668458
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      expo-router: ~3.5.14 => 3.5.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: bare

### Reproducible demo

https://github.com/expo/react-conf-app

**Comment by alanjhughes** [comment]
Hi @nayan-dey - What version of Java are you using?
