### ISSUE TITLE
Unresolved reference: BuildConfig on expo-notifications 28

### ISSUE THREAD

**Issue by ampopdev** [expo/expo#28943]
### Minimal reproducible example

https://github.com/ampopdev/demo-my-app-expo

### Did you reproduce this issue in a development build?

Yes

### Summary

Just run: yarn && npx react-native run-android on the minimal reproducible example. Then getting error:

```
MainApplication.kt:41:9 Unresolved reference: BuildConfig FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':app:compileDebugKotlin'
```

Tried adding `android.defaults.buildfeatures.buildconfig=true` in `gradle.properties` and `buildConfig = true` in build.gradle but didn't help as suggested [here](https://stackoverflow.com/questions/60942575/unresolved-reference-buildconfig-in-kotlin). 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.1/bin/yarn
      npm: 10.7.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by AlexisKenAlvarez** [comment]
Im also having the issue on a newly created expo app
![image](https://github.com/expo/expo/assets/80466376/15b3a249-a77a-4bc3-922c-e75fe2b043c6)

**Comment by ampopdev** [comment]
@brentvatne are you able to reproduce the issue in the min reproducible example?

**Comment by brentvatne** [comment]
hey @ampopdev - that is not actually a minimal reproducible example, there are many extraneous dependencies. try creating a new project and adding pieces of that project to it until you are able to repro.

> Minimal
> The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:
>
> Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
> Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ampopdev** [comment]
@brentvatne no problem, opened again [here](https://github.com/expo/expo/issues/29190)
