### ISSUE TITLE
[expo-firebase] Add a default module for using firebase

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#2894]
## Why

Currently a dev needs to install 14 libraries at a time. We should add a singular `expo-firebase` module which depends on all the firebase libraries (like how [firebase JS SDK](https://github.com/firebase/firebase-js-sdk) works).

This will provide a better structure for adding web support. 

```js
// ✅
import firebase from 'expo-firebase';
import firebase from 'expo-firebase/app';

// ❌ This should still be possible, but not the default method.
import firebase from 'expo-firebase-app';
```

## Using services

```js
// ✅
import firebase from 'expo-firebase/app';
import 'expo-firebase/notifications';

console.assert(firebase.notifications.Notification);
```

```js
// ✅
import firebase from 'expo-firebase';

console.assert(firebase.notifications.Notification);
```

```js
// ✅
import firebase from 'expo-firebase';
import { Notification } from 'expo-firebase/notifications';

console.assert(firebase.notifications.Notification === Notification);
```

## Native Linking

TBD, this should be easier.

**Comment by sjchmiela** [comment]
Fixed in https://github.com/expo/expo/commit/8d9877506e46c6918ee9e00ec8ef73d42889b498.
