### ISSUE TITLE
EAS Build variants not reflected in expo plugins

### ISSUE THREAD

**Issue by daankennes** [expo/expo#28942]
### Minimal reproducible example

https://github.com/daankennes/expo-app-variant-constants-demo

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Following the [documentation on app variants](https://docs.expo.dev/build-reference/variants/), I introduced an environment variable in eas.json and use this variable in app.config.js like so:

`const IS_OTHER = process.env.APP_VARIANT === "OTHER";
`
and so:
`scheme: IS_OTHER ? "myotherapp" : "myapp",`
and so:
`
android: {
      adaptiveIcon: {
        foregroundImage: "./assets/images/adaptive-icon.png",
        backgroundColor: "#ffffff",
      },
      package: IS_OTHER ? "be.test.other" : "be.test.regular",
    },
`

When I build the app variant on EAS (using the profile with the env variable), that works fine. The resulting app package identifier is be.test.other. However, Expo plugins are not aware of the changes made by environment variables. I tested this for expo-constants and expo-linking:

- Constants.expoConfig.android.package returns be.test.regular instead of be.test.other. 
- Linking.createURL("") returns myapp:// instead of myotherapp://.

In my production app, I seem to run into the same problem when using Expo notifications. Notifications won't open correctly when using the app variant. When I open a notification, either the app reloads itself (when using a development build) or does nothing (when using a production build). I did not include this in the example to keep it simple.

I only tested this on Android. Not sure if iOS or web are also impacted.

I'm also not sure if plugins like expo-linking are using expo-constants under the hood, meaning expo-constants is actually the root of the problem.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      expo-router: ~3.5.14 => 3.5.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.11
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by daankennes** [comment]
Notifications issue might have to do with #28656 : "handlers are being called when app is foregrounded, but app resets itself (seen in development build, unconfirmed in production)"

**Comment by brentvatne** [comment]
you will need to run `APP_VARIANT=your-variant npx expo start` to run the dev server with your target app variant configuration. i leave an empty `APP_VARIANT` to mean development so i don't have to set this unless almost ever, i'm explicitly testing out another environment locally.

**Comment by daankennes** [comment]
Ah, I understand. I did try setting the environment variable via a .env file but that did not work, and I somehow wrongly figured that was not the culprit. I now use cross-env to set the variable and it works! Thank you!
