### ISSUE TITLE
ReferenceError: Property 'Platform' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by RonaldChicaVera** [expo/expo#28950]
### Minimal reproducible example

https://gitlab.com/rootstack/lovable/lovable-app/-/tree/update?ref_type=heads

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Hey everyone,

I been updating my project recently from SDK 49 to SDK 51 and have been getting this error:
ReferenceError: Property 'Platform' doesn't exist, js engine: hermes

![image](https://github.com/expo/expo/assets/89930700/05d912e0-8296-48fb-9051-08632e9e70fa)

everytime I start my app. it throws the error
Here are my configs and setting may help.

![image](https://github.com/expo/expo/assets/89930700/b295ca3a-faa0-4496-a8b6-74761efd39e9)

### Environment

![image](https://github.com/expo/expo/assets/89930700/b952230a-3f4a-473b-b516-74ce86a07c93)

### Expo Doctor Diagnostics

![image](https://github.com/expo/expo/assets/89930700/b85ecb22-51e3-4ae6-ba64-93e80f60c0eb)

**Comment by mike-ganz** [comment]
@RonaldChicaVera Did you end up solving this? I have the same issue

**Comment by RonaldChicaVera** [comment]
I havent, i changed my metro config so i cant start my developmental server but doesnt work when you try to publish it to expo
with eas update

this is how i changed my metro config
const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");
const blacklist = require("metro-config/src/defaults/exclusionList");

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  resolver: {
    assetExts: ["bin", "txt", "jpg", "png", "ttf"],
    sourceExts: ["js", "json", "ts", "tsx", "jsx"],
    blacklistRE: blacklist([/platform_node/]),
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);

**Comment by ngandusikazwe** [comment]
I had the same issue after upgrading my SDK SDK 49 to SDK 51. I realized that there was a file where I used Platform but hadn't imported it from react native. In particular when i was setting the Status bar. Maybe search for all the places you have used it and make sure its been imported "import { Platform } from "react-native";"

**Comment by RonaldChicaVera** [comment]
Thank You @ngandusikazwe that fixed my problem!

**Comment by jdanosborne** [comment]
I had the same issue moving to SDK50 and this sorted it - many thanks @ngandusikazwe

**Comment by rainvillem** [comment]
I had the same issue moving to SDK50 and importing from react-native fixed the problem for me too - many thanks to @ngandusikazwe 

I am pretty new to expo and do not have much experience with it.  This fix now looks very obvious, but leave a question:
**Why it is not an issue when if using SDK49?**

I understand that moving on does not require to understand it, but to improve my upgrade skills, understanding why would help me find out futur issues.

**Comment by SFaraji** [comment]
@ngandusikazwe I still have the same issue, even that I have included `import { Platform } from "react-native"`everywhere that I use Platform.

I'm upgrading from SDK 49 to 51.

expo-doctor passed fine.

**Comment by Libero793** [comment]
Needing to do this shift for all my VIEW imports now - why the fuck is it not logging where the Error comes from?

**Comment by mskperera** [comment]
I had the same issue.

**Comment by zerolethanh** [comment]
I solved this issue by update metro `devDependencies`
```json
    "metro": "^0.82.3",
    "metro-core": "^0.82.3",
```
and at `metro.config.js` add this line
```js
config.transformer.getTransformOptions = async () => ({
    transform: {
        experimentalImportSupport: true,
        inlineRequires: true,
    },
});
```
