### ISSUE TITLE
Location.startLocationUpdatesAsync task callback does not receive any location updates on Android

### ISSUE THREAD

**Issue by Bashin** [expo/expo#28959]
### Minimal reproducible example

https://github.com/santibernas/expo-issue-28767

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When using Location.startLocationUpdatesAsync to register a TaskManager task the task is registered successfully (verified by TaskManager.getRegisteredTasksAsync) but the callback does not ever get called with location data or even an error on Android.

Here are some Logcat insights.

Initially:
Registered task with name 'LocationTask' for app with scoping identifier 'test.app'.

Thereafter every second:
Handling intent with task name 'LocationTask' and app scoping identifier 'test.app'.
Handling job with task name 'LocationTask' for app with scoping identifier 'test.app'.

After a few minutes (usually less than 15) the app runs out of memory and restarts.

On IOS everything works fine and in SDK 50 with the respective package versions of expo-task-manager and expo-location everything was working on Android as well.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.6.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-233.14808.21.2331.11709847
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: bare

### Expo Doctor Diagnostics

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by Bashin** [comment]
Please also note the same problem being reported in the comments of this issue:
https://github.com/expo/expo/issues/28767

This issue was created on request of @brentvatne and the sample app is by @santibernas

**Comment by shuo-hiwintech** [comment]
Same question.

**Comment by behenate** [comment]
@Bashin Hi, are you using the new architecture? Also does the location never work for you or only on the first launch like in this issue? https://github.com/expo/expo/issues/26373

**Comment by Bashin** [comment]
Hi @behenate I am not using the new architecture and I have no issues at all on iOS (unlike the issue you mentioned). However, I am unable to receive any location on Android, neither in a dev build nor in production.

**Comment by fbinz** [comment]
Can also confirm. Position updates are processed on SDK 50, but not on 51.
Regarding the new architecture: The documentation suggests that the expo-location is not supported, so I'm not using it ofc: https://docs.expo.dev/guides/new-architecture/#troubleshooting

**Comment by tknuts** [comment]
Prioritize based on severity :-) All Android devices on SDK 51, can't use Location services.

**Comment by behenate** [comment]
@tknuts It's a major issue, we'll resolve it asap 🫡

**Comment by managervcf** [comment]
+1

**Comment by behenate** [comment]
Issue fixed in the PR above, after we merge it will be published under SDK 51 in a few days (probably sometime after App.js)

**Comment by aeminkyr** [comment]
Any news? Still foreground location is not working.

**Comment by behenate** [comment]
@aeminkyr The fix has been published in `expo-task-manager` `11.8.2`. Are you using that version and the updates are still not working for you?

**Comment by shuo-hiwintech** [comment]
> Any news? Still foreground location is not working.

"expo": "^51.0.14",
"expo-location": "~17.0.1",
"expo-task-manager": "^11.8.2",

This could work for me.

**Comment by federicogomezlara** [comment]
Our app is never tracking user's location in the background on production and it's heavily impacting us since it's vital to our product, the plugin is configured properly

````
"expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "For safety purposes we ask you to enable your location. We will use it to know your current position only within the facility; your position will be monitored in the background. You can revoke the access at any time through your profile settings",
          "locationWhenInUsePermission": "For safety purposes, we ask you to enable your location. We will use it to know your current position only within the facility. You can revoke access at any time through your profile settings",
          "isIosBackgroundLocationEnabled": true,
          "isAndroidBackgroundLocationEnabled": true,
          "isAndroidForegroundLocationEnabled": true
        }
 ````
 
 And the thing is we are on Expo 50, not 51 so we obviously can't roll back to 50
 ````
 "expo": "^50.0.17"
 "expo-location": "~16.5.5"
 "expo-task-manager": "~11.7.3"
 ````
 As others have mentioned, the service is being started as I can see the permanent notification that location is being used on every Android device we have tested it on, including my personal one

**Comment by aeminkyr** [comment]
> Our app is never tracking user's location in the background on production and it's heavily impacting us since it's vital to our product, the plugin is configured properly
> 
> ```
> "expo-location",
>         {
>           "locationAlwaysAndWhenInUsePermission": "For safety purposes we ask you to enable your location. We will use it to know your current position only within the facility; your position will be monitored in the background. You can revoke the access at any time through your profile settings",
>           "locationWhenInUsePermission": "For safety purposes, we ask you to enable your location. We will use it to know your current position only within the facility. You can revoke access at any time through your profile settings",
>           "isIosBackgroundLocationEnabled": true,
>           "isAndroidBackgroundLocationEnabled": true,
>           "isAndroidForegroundLocationEnabled": true
>         }
> ```
> 
> And the thing is we are on Expo 50, not 51 so we obviously can't roll back to 50
> 
> ```
> "expo": "^50.0.17"
> "expo-location": "~16.5.5"
> "expo-task-manager": "~11.7.3"
> ```
> 
> As others have mentioned, the service is being started as I can see the permanent notification that location is being used on every Android device we have tested it on, including my personal one

Thanks. Its working on my debug version but not release apk. Have you experienced such a problem?

**Comment by federicogomezlara** [comment]
@aeminkyr It did work last time I checked in development but I'm pretty sure it's not working on production, we have another app which is on it's way to be discontinued now that we updated til I think 48 or 49 and everything works decently there. 

Even iOS has started giving us issues now, I'm gonna try updating to 51 now that a while has passed and hopefully the issues are resolved, trying to get my company to move to [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) or at least try it out but so far no luck

**Comment by aeminkyr** [comment]
`"enableProguardInReleaseBuilds": false`
After a long time I found a solution. Proguard is causing this problem, after disabling it the task is registered and runs as expected.

**Comment by tknuts** [comment]
@aeminkyr  Can  you share your "plugins" section ?

**Comment by aeminkyr** [comment]
> @aeminkyr Can you share your "plugins" section ?

` "plugins": [
      "expo-font",
      "expo-updates",
      [
        "expo-notifications"
      ],
      [
        "expo-build-properties",
        {
          "android": {
            "enableProguardInReleaseBuilds": false
          }
        }
      ],
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow *** to use your location.",
          "isAndroidBackgroundLocationEnabled": true,
          "isIosBackgroundLocationEnabled": true,
          "isAndroidForegroundServiceEnabled": true
        }
      ],
      "expo-localization",
      [
        "@sentry/react-native/expo",
        {
          "organization": "***",
          "project": "***",
          "url": "https://sentry.io/"
        }
      ]
    ]`

**Comment by thisisamandang** [comment]
> Our app is never tracking user's location in the background on production and it's heavily impacting us since it's vital to our product, the plugin is configured properly
> 
> ```
> "expo-location",
>         {
>           "locationAlwaysAndWhenInUsePermission": "For safety purposes we ask you to enable your location. We will use it to know your current position only within the facility; your position will be monitored in the background. You can revoke the access at any time through your profile settings",
>           "locationWhenInUsePermission": "For safety purposes, we ask you to enable your location. We will use it to know your current position only within the facility. You can revoke access at any time through your profile settings",
>           "isIosBackgroundLocationEnabled": true,
>           "isAndroidBackgroundLocationEnabled": true,
>           "isAndroidForegroundLocationEnabled": true
>         }
> ```
> 
> And the thing is we are on Expo 50, not 51 so we obviously can't roll back to 50
> 
> ```
> "expo": "^50.0.17"
> "expo-location": "~16.5.5"
> "expo-task-manager": "~11.7.3"
> ```
> 
> As others have mentioned, the service is being started as I can see the permanent notification that location is being used on every Android device we have tested it on, including my personal one



were you ever able to solve this?

**Comment by geikobogdan** [comment]
still faicing this issue, lcoation tracking doesn't work in background with foreground service:

 await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
            accuracy: Location.Accuracy.Balanced,
            activityType: Location.ActivityType.AutomotiveNavigation,
            distanceInterval: 10,
            showsBackgroundLocationIndicator: true,
            foregroundService: {
              notificationTitle: 'You are on duty',
              notificationBody:
                'Tow4Tech Operator app is tracking your location (only when you are on duty)',
              notificationColor: '#2C63B6',
            },
            pausesUpdatesAutomatically: false,
          })

**Comment by 3ph** [comment]
I'm still having issues as well - permission are granted but the `startLocationUpdatesAsync` callback is not called during the first run. The app needs to be killed and started again for the task to trigger. Any ideas?

**Comment by IggsGrey** [comment]
I disabled proguard in release builds and it started to work for me.

```
...
"plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "enableProguardInReleaseBuilds": false
          }
        }
      ],
      
```

**Comment by lrosasarias05** [comment]
> I disabled proguard in release builds and it started to work for me.
> 
> ```
> ...
> "plugins": [
>       [
>         "expo-build-properties",
>         {
>           "android": {
>             "enableProguardInReleaseBuilds": false
>           }
>         }
>       ],
>       
> ```

This has also worked for me 👍

**Comment by carloscurcino** [comment]
@Bashin did you solve this?? your first problem described very similar is mine. I'm racking my brain with this

**Comment by EnigmaByte7** [comment]
opening google maps and using "Locate Me" option does solve the issue , but i cant seem to find an optimal solution

**Comment by EvgeniiaVak** [comment]
updating the `LocationTaskOptions` (the second param to `startLocationUpdatesAsync`) to have  `{ accuracy: LocationAccuracy.Highest }` solved it for me
