### ISSUE TITLE
Cannot find native module 'ExpoVideo'

### ISSUE THREAD

**Issue by tagener-noisu** [expo/expo#28960]
### Minimal reproducible example

https://github.com/tagener-noisu/expo-video-bug

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Just clone and install. Tested on SDK versions 50 and 51.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by mrakesh0608** [comment]
`expo-video` is not available in Expo Go

> We expect to update this library frequently during the SDK 51 cycle, and so it will not yet be available in Expo Go (yet another reason to use [Development Builds](https://docs.expo.dev/develop/development-builds/introduction/)).

Ref : https://expo.dev/changelog/2024/05-07-sdk-51#other-highlights

**Comment by alanjhughes** [comment]
@mrakesh0608 is correct, it is not currently supported in expo go

**Comment by Malickmimd** [comment]
@mrakesh0608 even in development build my app didn't run using expo video

**Comment by thep-dr** [comment]
I have the same problem as @Malickmimd.

After installing `expo-video` there is no changes to my `Podfile.lock`, which I assume there should be?

**Comment by mrakesh0608** [comment]
@thep-dr You have to rebuild the development client after installing any package that contains native code.

Ref: https://docs.expo.dev/develop/development-builds/use-development-builds/#rebuild-a-development-build

**Comment by thep-dr** [comment]
What if I do not use development clients yet?

**Comment by mrakesh0608** [comment]
you have to use 
```
npx expo prebuild --clean
```

**Comment by thep-dr** [comment]
Also if I already have an `ios` and `android` folder checked into git?

**Comment by mrakesh0608** [comment]
are you using managed or bare expo ?

**Comment by thep-dr** [comment]
Bare

**Comment by mrakesh0608** [comment]
Use 

```
npx expo prebuild --clean
```

Note: If you have manually changed the native directories, they will be lost

>Also if I already have an ios and android folder checked into git?

Since your using CNG, you can add these folders to .gitignore [see here](https://docs.expo.dev/workflow/prebuild/#clean)

**Comment by thep-dr** [comment]
Sorry, there might be some confusion. I am not using CNG yet

**Comment by mrakesh0608** [comment]
ok.

try running this the cmd & then run the app
```
npx pod-install
```

**Comment by thep-dr** [comment]
I have already tried that - it does not help 😢

I will try to create one tomorrow! Thank you so much for your help and time!

Just for my understanding - I should see a ExpoVideo entry in my `Podfile.lock` right?

**Comment by mrakesh0608** [comment]
>I should see a ExpoVideo entry in my Podfile.lock right?

yes

**Comment by tomhopkins** [comment]
I think the challenge here is that ExpoVideo only works with Expo SDK52. You need Expo-av before that.

**Comment by shane98x** [comment]
guys would be great if you put this in the advice section : make a new development build - it seems to fix most of these 'native module expo-tbd" not found

**Comment by dnrico1** [comment]
I am having this same problem, and none of the suggestions from this thread have worked..

**Comment by jab-r** [comment]
I'm on expo 52.0.33 and getting this error with expo-video 2.0.5 or 1.2.7

**Comment by Daraujo26** [comment]
> ERROR Error: Cannot find native module 'ExpoVideo', js engine: hermes this is what i am getting even after trying everything

I have this issue now. Were you able to find a fix?

**Comment by aashish00021** [comment]
> > ERROR Error: Cannot find native module 'ExpoVideo', js engine: hermes this is what i am getting even after trying everything
> 
> I have this issue now. Were you able to find a fix?

Yea remove node modules and ios or android which ever you working on then do npm I after that install expo video again then prebuild it again after this error will disappear this is what worked for me
