### ISSUE TITLE
expo router tab switch doesn't works in nested tabs and shared routes

### ISSUE THREAD

**Issue by DavideSegullo** [expo/expo#28978]
### Minimal reproducible example

https://github.com/DavideSegullo/expo-router-nested-mre

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

After upgrading from expo 50 to expo 51, there is a bug with the tabbed navigation, practically the status updates as if I had changed the tab but the correct screen is not displayed and the index page is always shown.
Perhaps this has something to do with the use of shared routes.

https://github.com/expo/expo/assets/17269969/a05dca18-3385-4848-ba45-ffcda42f194a

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      expo-router: ~3.5.14 => 3.5.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 9.0.7
    Expo Workflow: bare

**Comment by saulamsal** [comment]
+1 same issue after upgrading to Expo 51.

**Comment by evelant** [comment]
Possibly related https://github.com/expo/expo/issues/29273
