### ISSUE TITLE
App crashes after start with no information

### ISSUE THREAD

**Issue by xixixao** [expo/expo#28993]
### Summary

After upgrading Expo Go to the latest version that fixed the crash on navigation bug, the app now crashes instantly after building the bundle.

### What platform(s) does this occur on?

iOS

### SDK Version

51.0.8

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 3.5.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 22.1.0 - ~/Library/Caches/fnm_multishells/7348_1716210169256/bin/node
      Yarn: 1.22.22 - ~/Library/Caches/fnm_multishells/29356_1708205083806/bin/yarn
      npm: 10.7.0 - ~/Library/Caches/fnm_multishells/7348_1716210169256/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/get-convex/turbo-expo-nextjs-clerk-convex-monorepo/tree/srb/upgrade-to-latest

```
git clone https://github.com/get-convex/turbo-expo-nextjs-clerk-convex-monorepo -b srb/upgrade-to-latest repro-insta-crash
cd repro-insta-crash
yarn
npm run dev
```
Then open the Expo Go app via the iOS camera

**Comment by EseosaOwen** [comment]
I am facing something similar as well, and it just happened today. The app works perfectly on android. The moment I build the bundle app on ios it crashes. I am using expo go and so i thought it was the app, I uninstalled and installed back, still the same, I removed my vpn and anything what could affect it, still the same, so i uninstalled and installed the app 3 more times again, still the same, I checked the codes and i can't see any significant change between now and when it was working.

**Comment by codeOlam** [comment]
> I am facing something similar as well, and it just happened today. The app works perfectly on android. The moment I build the bundle app on ios it crashes. I am using expo go and so i thought it was the app, I uninstalled and installed back, still the same, I removed my vpn and anything what could affect it, still the same, so i uninstalled and installed the app 3 more times again, still the same, I checked the codes and i can't see any significant change between now and when it was working.

Still facing similar experience.

Some of the things I did was;

- Upgraded the expo sdk v51.0.8

- Deleted `node_modules` and `yarn.lock`
- installed expo by running `yarn add expo@51.0.8`
- run `npx expo install --fix`
- added `import "react-native-reanimated";` to `app/_layout.tsx`
- added `import "react-native-reanimated";` to `app/index.tsx`

This works well no problem in Simulator and Emulators

I deployed to testflight using eas cli. But it crashed on ios when you open the app from background and press on any thing.

I ran `yarn cache clean --force` and build again and submitted to testflight using eas. same problem on ios

All of these no error or warning logs on both my cli and eas build logs

**Comment by serfgy** [comment]
same issue with above, upgraded to 51 and dependencies, expo go starts but crashes after a few presses

suspect react navigation issues but no idea how to confirm as the crash is random but reproducibly random

**Comment by codeOlam** [comment]
Yes. my team has to revert to sdk 50.0.17. we also noticed other things with sdk 51, like blur hash in expo-image not working properly etc. But the crashing, made our app on unusable on production. We hope the next released will focus on making it stable as v50 currently is.

**Comment by xixixao** [comment]
@brentvatne any chance you can have a look? The repro is in the original post.

**Comment by brentvatne** [comment]
@xixixao - happy to look if you can provide a **minimal** repro. there's a lot going on in that repository. https://stackoverflow.com/help/minimal-reproducible-example

**Comment by VictorioMolina** [comment]
Not sure if this is the same error, but I have been experiencing an unexpected error on production/preview profiles (not in development on my physical device and simulator).

After debugging with the Mac console, I found the log “Undefined is not a function located at Image”. I am using last version of expo-image.

After removing this line and rebuilding using EAS, the crash on production disappears.

```
<Image
   source={{ uri: “https://…” }}
   priority=“high”
   style={{ aspectRatio: 1, width: ”100%” }}
 />
```

**Comment by brentvatne** [comment]
@VictorioMolina - can you share a minimal reproducible example?

**Comment by VictorioMolina** [comment]
@brentvatne In my case, it was just a dependencies incompatibility issue. I was getting createSnapshotFriendlyRef is undefined when using expo-image. Upgrading everything fixed it 😄

**Comment by xixixao** [comment]
Cannot repro.

**Comment by frazras** [comment]
Commenting out code out of your main return stateemnt and restoring till I found the issue worked for me
