### ISSUE TITLE
Text to Speech

### ISSUE THREAD

**Issue by tysoncadenhead** [expo/expo#290]
There are several React Native libraries available such as
https://github.com/naoufal/react-native-speech and https://www.npmjs.com/package/react-native-tts that allow you to use the device voice to speak your text. I've gotten pretty far on my current app without needing to detach from Expo, but all of the libraries I've found for this require native components and thus linking. I know this is a little bit of an edge case, but I thought I'd ask if this was a possibility before detaching.

**Comment by aalices** [comment]
@tysoncadenhead in progress! ;)

**Comment by tysoncadenhead** [comment]
@aalices thank you so much! Do you have an eta on when it will be available?

**Comment by aalices** [comment]
@tysoncadenhead the PR is on its way, so we will se ;)

**Comment by terribleben** [comment]
This is [shipping](https://github.com/expo/expo/pull/311) in SDK 19.
