### ISSUE TITLE
Camera Module : no yawAngle

### ISSUE THREAD

**Issue by imasif** [expo/expo#2900]
I'm trying to get the yaw angle from Expo camera in `v31.0.0`. But always getting 0. I'm using the following code:

> renderFace({ bounds, faceID, rollAngle, yawAngle, smilingProbability }) {
>     return (
>       <View
>         key={faceID}
>         transform={[
>           { perspective: 600 },
>           { rotateZ: `${rollAngle.toFixed(0)}deg` },
>           { rotateY: `${yawAngle.toFixed(0)}deg` },
>         ]}
>         style={[
>           styles.face,
>           {
>             ...bounds.size,
>             left: bounds.origin.x,
>             top: bounds.origin.y,
>           },
>           {
>             borderWidth:2,
>             borderColor:'#fff',
>             borderStyle: 'solid'
>           }
>         ]}>
>         <Text style={styles.faceText}>yawAngle: {yawAngle.toFixed(0)}</Text>
>       </View>
>     );
>   }

Above method is being called here:

>   renderFaces() {
>     return (
>       <View style={styles.facesContainer} pointerEvents="none">
>         {this.state.faces.map(this.renderFace.bind(this))}
>       </View>
>     );
>   }

being called in the main render:
> {this.renderFaces()}

Also facial landmarks are not available. I've used code from here: [https://snack.expo.io/B1ys-bfHM](https://snack.expo.io/B1ys-bfHM)

**Comment by sjchmiela** [comment]
Hey, @imasif! In SDK31 we've changed how does one provide settings to face detector. Instead of passing `faceDetectionLandmarks`, `faceDetectionClassifications`, etc., `Camera` expects you to provide a `faceDetectionSettings` property in which you would set values for keys `landmarks`, `classifications`, etc.

```jsx
import { FaceDetector } from 'expo';

<Camera
  // ... other props
  onFacesDetected={this.handleFacesDetected}
  faceDetectorSettings={{
    mode: FaceDetector.Constants.Mode.fast,
    detectLandmarks: FaceDetector.Constants.Mode.none,
    runClassifications: FaceDetector.Constants.Mode.none,
  }}
/>
```

Check out this section in docs: https://docs.expo.io/versions/v31.0.0/sdk/facedetector#settings. 🙂

**Comment by sjchmiela** [comment]
I'll let myself close this thread due to inactivity, if you have any more questions feel free to reopen the issue! 🙂

**Comment by imasif** [comment]
Sorry for the late response, I will let you know If I get the same error again
