### ISSUE TITLE
Native module ExpoDevMenuExtensions tried to override DevMenuExtension

### ISSUE THREAD

**Issue by kashyapvelani** [expo/expo#29010]
### Summary

I am getting this error after I upgrade from expo sdk50 to expo sdk51. The app is build successfully but when it opens on the device it is showing this error.

**There was a problem loading the project.**

**This development build encountered the following error.**

Native module ExpoDevMenuExtensions tried to override DevMenuExtension. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExisting Module=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
![expo error](https://github.com/expo/expo/assets/128171599/2f420cf4-b70e-4a65-8f4f-cdd6ec03eb16)

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

My package.json

{
  "name": "flyshorts",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@apollo/client": "^3.9.11",
    "@expo/config-plugins": "~8.0.0",
    "@expo/vector-icons": "^14.0.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/netinfo": "11.3.1",
    "@react-native-firebase/analytics": "^19.3.0",
    "@react-native-firebase/app": "^19.3.0",
    "@react-native-firebase/messaging": "^19.3.0",
    "@react-navigation/native": "^6.0.2",
    "deprecated-react-native-prop-types": "^2.2.0",
    "expo": "^51.0.0",
    "expo-asset": "~10.0.6",
    "expo-build-properties": "~0.12.1",
    "expo-constants": "~16.0.1",
    "expo-dev-client": "~4.0.14",
    "expo-device": "~6.0.2",
    "expo-file-system": "~17.0.1",
    "expo-font": "~12.0.5",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-router": "^3.5.14",
    "expo-splash-screen": "^0.27.4",
    "expo-sqlite": "~14.0.3",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.4",
    "expo-web-browser": "~13.0.3",
    "graphql": "^16.8.1",
    "graphql-tag": "^2.12.6",
    "moment": "^2.30.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
    "react-native-device-info": "^10.13.2",
    "react-native-render-html": "^6.3.4",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-share": "^10.2.0",
    "react-native-swiper": "^1.6.0",
    "react-native-view-shot": "3.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.24.5",
    "@types/ramda": "^0.29.12",
    "@types/react": "~18.2.45",
    "jest": "^29.7.0",
    "jest-expo": "~51.0.2",
    "react-test-renderer": "^18.2.0",
    "tailwindcss": "^3.3.2",
    "typescript": "~5.3.3"
  },
  "private": true
}

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 34
        Build Tools: 30.0.3, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-231.9392.1.2311.11076708
    npmPackages:
      expo: ^51.0.0 => 51.0.8
      expo-router: ^3.5.14 => 3.5.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: bare

### Reproducible demo

I don't know how can you reproduce this issue.

**Comment by madmeatballs** [comment]
This also happened to our project, we updated our sdk to 51 from 50 aswell.

**Comment by Raajakishore20** [comment]
> This also happened to our project, we updated our sdk to 51 from 50 aswell. iOS works fine, but not on android.
> 
> this version "expo-dev-client": "~4.0.15" was causing it. I rolled back to 4.0.14 it works fine.
> 
> Just by using 4.0.15 was consistently causing the issue for me on android only.

My expo-dev-client is in v3.3.12. But this issue is still happening.

**Comment by lukmccall** [comment]
Should be fixed by https://github.com/expo/expo/pull/29611.

**Comment by Raajakishore20** [comment]
@lukmccall Thanks for the help! When will this be available and also on which version?

**Comment by Danielatonge** [comment]
I'm currently facing this issue, what should I do?

**Comment by geneshairzan** [comment]
me to, suddenly facing this issue, any update? 

> Should be fixed by #29611.

this one seems not the fixed

**Comment by rchavik** [comment]
we're still on sdk50 and getting this issue on android.  the 2 above workaround did not work for us.

for now, we workaround this by `yarn remove expo-dev-client`, and remove `import 'expo-dev-client';` from our `bootstrap.native.js` so the default react-native client took over.

**Comment by tolypash** [comment]
I'm experiencing this issue as well! Using:
`    "expo-dev-client": "~4.0.25",`

**Comment by snzow** [comment]
I am still having this issue as well. `Npm remove expo-dev-client` did end up working as a workaround though

**Comment by madmeatballs** [comment]
experiencing this on android with 
`"expo-dev-client": "~4.0.26",`
