### ISSUE TITLE
expo-updates conflicts with 3rd party library

### ISSUE THREAD

**Issue by lucalanca** [expo/expo#29026]
### Minimal reproducible example

https://github.com/lucalanca/expo-updates-veriff

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm using a third party library ([@veriff/react-native-sdk](https://www.npmjs.com/package/@veriff/react-native-sdk)) which depends on  `org.bouncycastle.bcprov-jdk18on`.

I've created a config-plugin (you can see in the  reproducible example repo) that makes this library work with expo without "ejecting" (I know this is an older term).

On an empty expo project (created with `create-expo-app`) I can build for android with no problems (with `npx eas-cli build --profile development --platform android --local`). However, once I add `expo-updates` to my project, I start get  bunch of Duplicate class errors like follows:

```
Duplicate class org.bouncycastle.* found in modules bcprov-jdk15to18-1.70.jar -> jetified-bcprov-jdk15to18-1.70 (org.bouncycastle:bcprov-jdk15to18:1.70) and bcprov-jdk18on-1.76.jar -> jetified-bcprov-jdk18on-1.76 (org.bouncycastle:bcprov-jdk18on:1.76)
```

### Environment

System:
  OS: macOS 14.1
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 21.4.0 - ~/.nvm/versions/node/v21.4.0/bin/node
  Yarn: 1.22.21 - ~/.nvm/versions/node/v21.4.0/bin/yarn
  npm: 10.2.4 - ~/.nvm/versions/node/v21.4.0/bin/npm
  Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
Managers:
  CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
npmPackages:
  expo: ~51.0.8 => 51.0.8
  expo-router: ~3.5.14 => 3.5.14
  react: 18.2.0 => 18.2.0
  react-dom: 18.2.0 => 18.2.0
  react-native: 0.74.1 => 0.74.1
  react-native-web: ~0.19.10 => 0.19.11
Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by CallumHemsley** [comment]
Hello Luca. I'm currently working on something similar and am receiving the same error. I managed to do a temp fix by introducing an additional plugin to deal with this dependency issue:

```const { createRunOncePlugin, withAppBuildGradle } = require('@expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');

const withFixedBouncyCastleAndroidVersion = (config) => {
    return withAppBuildGradle(config, config => {
        config.modResults.contents = setBouncyCastleVersion(config.modResults.contents)
        return config;
    });
}

const TAG = "expo-bouncy-castle-fix"

const setBouncyCastleVersion = (src) => {

    const configurationFix = `
    configurations.all {
      c -> c.resolutionStrategy.eachDependency {
          DependencyResolveDetails dependency ->
              println dependency.requested.group
              if (dependency.requested.group == 'org.bouncycastle') {
                  dependency.useTarget 'org.bouncycastle:bcprov-jdk18on:1.76'
              }
      }
    }`

    var mergeResults = mergeContents({
        tag: TAG,
        src: src,
        newSrc: configurationFix,
        anchor: /android {/gm,
        offset: 1,
        comment: `// `
    });

    return mergeResults.contents;
}

module.exports = createRunOncePlugin(
    withFixedBouncyCastleAndroidVersion,
    'withFixedBouncyCastleAndroidVersion',
    '1.0.0'
);```

(This was inspired by the conversation happening over here: https://github.com/thebergamo/react-native-fbsdk-next/issues/323#issuecomment-1280044535)
