### ISSUE TITLE
Expo background fetch isnt working

### ISSUE THREAD

**Issue by aymanMFD** [expo/expo#29021]
### Minimal reproducible example

https://github.com/aymanMFD/Monitoring-System.git

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

This is my task manager define
```js
TaskManager.defineTask('backgroundTask', async () => {
    const now = Date.now();
  
    console.log(`Got background fetch call at date: ${new Date(now).toISOString()}`);
      return BackgroundFetch.BackgroundFetchResult.NewData;
  });
```
And those for registering and unregistering
```js
const toggleBg = async () => {
        
        await BackgroundFetch.registerTaskAsync('backgroundTask', {
            minimumInterval: 0,
            stopOnTerminate: false,
            startOnBoot: true
        }).then(() => {console.log("Registered task")})
        
    }

    const unregister = async () => {
        await BackgroundFetch.unregisterTaskAsync('backgroundTask');
        console.log("Unregistered task!");
    }
```

And these are basic components for testing
```js
            <TouchableOpacity onPress={toggleBg}>
                <Text>Click me</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={unregister}>
                <Text>unregister</Text>
            </TouchableOpacity>
```

Despite registering and checking if the task was well registered, the task doesn't seem to be able to run,

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by behenate** [comment]
Hi, this issue seems to be related to this one: https://github.com/expo/expo/issues/28959 - the event is not getting broadcasted correctly so you cant see the console.log.
On a branch with the fix (https://github.com/expo/expo/pull/29024) after backgrounding the app I can periodically see a console.log

**Comment by aymanMFD** [comment]
@behenate Sorry for being a burden but I am new to this and I was wondering how can I implement this to fix my issue?

**Comment by behenate** [comment]
@aymanMFD Hi you will have to wait until this change is published (which should be in a few days) and then update the `task-mangaer` package in your project to the newest version

**Comment by aymanMFD** [comment]
@behenate Alright thank you man

**Comment by behenate** [comment]
@Beckmann0o The PR wit get "published" label after it's published, you can check the code on npm for the change from the PR

**Comment by tkrafael** [comment]
tested with latest version, working correctly:
```
"expo": "51.0.9",
"expo-background-fetch": "12.0.1",
"expo-task-manager": "11.8.2",
"expo-modules-core": "1.12.12",
"unimodules-app-loader": "4.6.0",
```

**Comment by w7br** [comment]
Cada dispositivo Android um local diferente, oque funcionou para mim inclusive com a tela desligada foi  desabilitar a economia de bateria para aplicações nativas do gps, afinal, de nada vale a aplicação estar configurada para funcionar em segundo plano com a localização, se na hora que tela estiver desligada o gps também hibernar, isso resolveu meu problema, agora funciona com a aplicação encerrada e a tela desligada por inúmeras horas sem parar.

Utilizando aqui expo-location + expo-task-manager ... em uma aplicação react-native com o expo ejetado

**Comment by w7br** [comment]
Ainda assim não dá pra se considerar como uma solução para o cliente final, uma vez que sabemos o quão chato cada cliente pagante pode ser e dependeria de configurar manualmente isso em dispositivo por dispositivo, mas pelo exaustivo tempo que tive para descobrir isso, vi que nada resolvia, e a única saída foi localizar nas configurações gerais do aparelho onde o gps estava sendo desabilitado pelo modo economia de bateria e desabilita-lo .... ai vua-la .... o esperado aconteceu, funciona o tempo todo até mesmo com a aplicação encerrada e a tela desligada e bloqueada .... mas há de pensarmos em como fazer isso em nossas aplicação para que os clientes não tenham que penar atrás destas configurações .... alguém tem alguma sugestão?

**Comment by behenate** [comment]
@w7br Hi, we would appreciate if you could translate your comments to english before posting them, as it will be easier for everyone to understand 😄 When it comes to the location, it might be difficult to do anything on expo's side if the OS decides to stop allowing the task to use the GPS. Maybe using a foreground service would solve your issue?

**Comment by Hosam-hsm** [comment]
@behenate Is to possible to run the task manager in background for something not related to location?

**Comment by Hosam-hsm** [comment]
> @Hosam-hsm Can you provide more details? What platform are you using and how are you registering the task?

I'm using a real iOS device to test a new expo dev client app with task manager and background fetch installed using the expo documents. I don't want to get the location updates, instead I want to run a function while the app is in background. So I'm using the task manager to test it using console.log for now. But I'm not seeing the log or the alert inside the app even though I kept the app in background for 5 minutes. 

Package versions I'm using: 
 ```
   "expo": "~51.0.14",
    "expo-dev-client": "~4.0.18",
    "expo-background-fetch": "~12.0.1",
    "expo-task-manager": "~11.8.2"
```
I am seeing this log and alert when I test the background function using the Instruments app as mentioned in the expo docs. 

```
TaskManager.defineTask(BACKGROUND_FETCH_TASK, async () => {
  const now = Date.now();
  Alert.alert("fetched");
  console.warn(
    `Got background fetch call at date: ${new Date(now).toISOString()}`
  );
  return BackgroundFetch.BackgroundFetchResult.NewData;
});
```

My problem is that this never gets logged nor the alert is shown without manually triggering it when the app is backgrounded.

**Comment by Cosmin-Ciolacu** [comment]
I have the same issue on IOS. On Android it works well.

**Comment by trevor-james-nangosha** [comment]
@Hosam-hsm Did you find a solution to your problem, 'cause I seem to find myself in a similar situation? Only difference is that I am using an android device.

**Comment by Hosam-hsm** [comment]
> @Hosam-hsm Did you find a solution to your problem, 'cause I seem to find myself in a similar situation? Only difference is that I am using an android device.

No, I couldn’t find a solution.

**Comment by Akuma-U1** [comment]
@Hosam-hsm Any updates on if you were able to get any of this working?

**Comment by AhsanHussain12** [comment]
i am using background fetch to check for order status in firestore and generate a local notification but the task manager is not intialized or working i dont know , please help

**Comment by parsediya** [comment]
@AhsanHussain12 did you find any solution for this. I am getting this error too.

**Comment by MHKCoder** [comment]
Did anyone find a solution to this i am having almost the same issue the only difference is it is getting registered except it isnt getting executed at a specific time - I am running a real android device on a development build. Would appreciate if anyone could help me on this one, Thanks.

**Comment by MHKCoder** [comment]
Interesting, In my case i am using the background fetch to fetch from an api every 21 hours it seems to register but it doesnt seem to trigger it - No idea why.

**Comment by AhsanHussain12** [comment]
> Interesting, In my case i am using the background fetch to fetch from an api every 21 hours it seems to register but it doesnt seem to fire the background fetch - No idea why.

try debugging it manually by using local notifications to understand the problem better

**Comment by MHKCoder** [comment]
Thanks for the reply, I'll give that a try.

**Comment by tkrafael** [comment]
I had a big headache on background fetch and notifications.
After struggling two days with no avail, I found that if proguard or obfuscation is enabled in android build config, it removes some essential kotlin and Java classes.

So, for background fetch to work, is very simple:
1. Make sure you call define task as soon as possible, outside your screens. I made an index.tsx on in root folder (app's parent folder), called those just after the imports.
2. In this tsx file I created a default exports that returns App object from expo. This is needed so it starts navigation in apps folder.

3. Inside regular screen files, I call register task as needed.

Some things to take into account:
1. Background fetch does not run when you want. If your app is in foreground, it does not trigger registered tasks.
2. I observed you can trigger background tasks by putting phone to sleep and start charging it by cable or wireless.
3. You cannot use any hooks inside task's code. This is because this code does not have screens, it runs inside a broadcast receiver thread (headless thread)

I suggest you to take a look in Doze mode documentation for android. Maybe you get some answers there.

**Comment by MHKCoder** [comment]
> I had a big headache on background fetch and notifications. After struggling two days with no avail, I found that if proguard or obfuscation is enabled in android build config, it removes some essential kotlin and Java classes.
> 
> So, for background fetch to work, is very simple:
> 
>     1. Make sure you call define task as soon as possible, outside your screens. I made an index.tsx on in root folder (app's parent folder), called those just after the imports.
> 
>     2. In this tsx file I created a default exports that returns App object from expo. This is needed so it starts navigation in apps folder.
> 
>     3. Inside regular screen files, I call register task as needed.
> 
> 
> Some things to take into account:
> 
>     1. Background fetch does not run when you want. If your app is in foreground, it does not trigger registered tasks.
> 
>     2. I observed you can trigger background tasks by putting phone to sleep and start charging it by cable or wireless.
> 
>     3. You cannot use any hooks inside task's code. This is because this code does not have screens, it runs inside a broadcast receiver thread (headless thread)
> 
> 
> I suggest you to take a look in Doze mode documentation for android. Maybe you get some answers there.

Many Thanks @tkrafael I appreciate all the tips, especially regarding the foreground task issue and force triggering background tasks by putting it to sleep and charging - I will make sure to check out the Doze mode documentation for android as well.

**Comment by ikbal-nayem** [comment]
Try using `XMLHttpRequest` instead of `fetch` for background network calling.
`XMLHttpRequest` often works where `fetch` fails in Android background due to lower-level native binding.

**Comment by MHKCoder** [comment]
@ikbal-nayem - Thank you so much for the suggestion - I will give that a try. Again Many Thanks.
