### ISSUE TITLE
android:windowSoftInputMode="adjustNothing"

### ISSUE THREAD

**Issue by isaachinman** [expo/expo#29025]
### Minimal reproducible example

https://github.com/expo/examples/tree/master/blank

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Keyboard avoiding handling has been a mess in RN since I began using the framework in 2017.

Over time, we have developed our own strategies for keyboard handling. In short, we manually manage keyboard events and animate the layout via reanimated.

This works well on iOS.

For Android, we need to disable pan or resize behaviour, to rely on our own implementation.

We need to be able to set `android:windowSoftInputMode="adjustNothing"`

However, Expo only supports pan or resize, strictly.

### Environment

-----

### Expo Doctor Diagnostics

-----

**Comment by RohovDmytro** [comment]
Same issue. Is there any specific reason we are limited to resize and pan values?

````
Determines how the software keyboard will impact the layout of your application. This maps to the android:windowSoftInputMode property. Defaults to resize. Valid values: resize, pan.
````

**Comment by jeanregisser** [comment]
For folks still looking to achieve this (and not using Expo Go), it can be done with a config plugin:

```ts
import { AndroidConfig, ConfigPlugin, withAndroidManifest } from '@expo/config-plugins'

/**
 * This plugin sets the `android:windowSoftInputMode` to `adjustNothing` in the Android manifest.
 * This is so it behaves like on iOS (appearing on top of the window content and require KeyboardAvoidingView or similar).
 */
export const withAndroidWindowSoftInputModeAdjustNothing: ConfigPlugin = (config) => {
  return withAndroidManifest(config, (config) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(config.modResults)

    activity.$['android:windowSoftInputMode'] = 'adjustNothing'

    return config
  })
}
```
