### ISSUE TITLE
[Calendar] — iOS expo-calendar does not seem to work with Expo SDK 51

### ISSUE THREAD

**Issue by PrinceD96** [expo/expo#29035]
### Minimal reproducible example

https://github.com/PrinceD96/expo-calendar-repro

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

The operation couldn't be completed. (ExpoCalendar.MissingCalendarPListValueException error 1.)

![Screenshot 2024-05-21 at 1 54 34 PM](https://github.com/expo/expo/assets/53633741/c9434f96-4cfa-470e-8a3f-f1dbe5e975bd)

### Environment

   ```
 System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 3.6.4 - ~/.nvm/versions/node/v18.16.0/bin/yarn
      npm: 9.6.5 - ~/.nvm/versions/node/v18.16.0/bin/npm
      Watchman: 2024.05.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/daniel/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: bare
    
```

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by kot331107** [comment]
@PrinceD96  have a look at your Info.plist if it has the following entries. You have to define ones containing "FullAccess" to run your app on iOS 17.0+. And other two are to run on earlier versions. There's a lack of information in Expo Calendar docs for now I guess

```
    <key>NSCalendarsFullAccessUsageDescription</key>
    <string>Allow $(PRODUCT_NAME) to access your calendar</string>
    <key>NSCalendarsUsageDescription</key>
    <string>Allow $(PRODUCT_NAME) to access your calendar</string>
    <key>NSRemindersFullAccessUsageDescription</key>
    <string>Allow $(PRODUCT_NAME) to access your reminders</string>
    <key>NSRemindersUsageDescription</key>
    <string>Allow $(PRODUCT_NAME) to access your reminders</string>
    <key>NSUserActivityTypes</key>
```

**Comment by PrinceD96** [comment]
> @PrinceD96 have a look at your Info.plist if it has the following entries. You have to define ones containing "FullAccess" to run your app on iOS 17.0+. And other two are to run on earlier versions. There's a lack of information in Expo Calendar docs for now I guess
> 
> ```
>     <key>NSCalendarsFullAccessUsageDescription</key>
>     <string>Allow $(PRODUCT_NAME) to access your calendar</string>
>     <key>NSCalendarsUsageDescription</key>
>     <string>Allow $(PRODUCT_NAME) to access your calendar</string>
>     <key>NSRemindersFullAccessUsageDescription</key>
>     <string>Allow $(PRODUCT_NAME) to access your reminders</string>
>     <key>NSRemindersUsageDescription</key>
>     <string>Allow $(PRODUCT_NAME) to access your reminders</string>
>     <key>NSUserActivityTypes</key>
> ```

That worked! Thank you!
