### ISSUE TITLE
Reanimated babel error after migrating to Expo Router

### ISSUE THREAD

**Issue by dawsonbooth** [expo/expo#29038]
### Minimal reproducible example

https://github.com/dawsonbooth/expo-router-babel-reanimated-crash

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Getting this error when loading the app: `/node_modules/react-native-gesture-handler/src/handlers/gestures/hoverGesture.ts: [Reanimated] Babel plugin exception: Error: [BABEL]: You appear to be using a native ECMAScript module plugin, which is only supported when running Babel asynchronously. (While processing: /node_modules/@babel/plugin-transform-shorthand-properties/lib/index.js)`

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.1 - ~/.asdf/installs/nodejs/20.3.1/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.3.1/bin/yarn
      npm: 9.6.7 - ~/.asdf/plugins/nodejs/shims/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.8 
      expo-router: ~3.5.9 => 3.5.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.6 => 0.19.11 
    Expo Workflow: managed

**Comment by dawsonbooth** [comment]
With some more exploration I was able to find that other instances of using `react-native-animated` trigger the error, but typically importing `react-native-gesture-handler` is the earliest so it takes precedent.

I believe this is an issue caused by Expo Router and not by the other libraries/bun since it didn't occur until I migrated to Expo Router from the old webpack setup.

**Comment by GollyJer** [comment]
+1
Glad to find someone else having this issue; because I fully thought it was on my side of the keyboard. It started of us two days ago and have been trying to figure it out since.

**Comment by GollyJer** [comment]
and we use Yarn

**Comment by GollyJer** [comment]
This is how it manifests in our project.
![image](https://github.com/expo/expo/assets/689204/47072ec0-0554-49a9-bfc0-9712e558f54a)

**Comment by GollyJer** [comment]
Turns out the issue on my end was a babel plugin `@legendapp/state/babel`. 
Once I remove it the app starts loading again. 

Might be worth checking the plugins in your `babel.config.js` file @dawsonbooth

**Comment by dawsonbooth** [comment]
Ah, glad you could get it working.

The only plugin I'm using (as well as the minimal reproducible example) is `babel-preset-expo`, so it can't be resolved that way for me unfortunately.

**Comment by Osomasi** [comment]
@dawsonbooth I have     
 
 'expo-router/babel',

and I still get 

iOS Bundling failed 48ms node_modules/expo-router/entry.js (1 module)
error: node_modules/expo-router/entry.js: You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.
