### ISSUE TITLE
[expo-video] Unable to set playbackRate on iOS

### ISSUE THREAD

**Issue by tslater** [expo/expo#29036]
### Minimal reproducible example

https://github.com/tslater/reproduce-expo-video-playbackrate-error

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Anytime I set the playbackRate like this: `player.playbackRate = 0.7;` I get the following error:
```
ERROR  Error: FunctionCallException: Calling the 'set' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:87)
→ Caused by: ArgumentCastException: The 2nd argument cannot be cast to type Float (at ExpoModulesCore/JavaScriptUtils.swift:40)
→ Caused by: CastingException<Float>: Cannot cast 'Optional(0.9)' to Float (at ExpoModulesCore/DynamicRawType.swift:27)
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.2/bin/yarn
      npm: 10.8.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/sl8r/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 29, 30, 31, 32, 33, 34
        Build Tools: 30.0.3, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-22 | Intel x86_64 Atom, android-32 | Google APIs ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.8
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by timoisalive** [comment]
I'm still getting this error, when trying to set the volume to 0.7 for example.
I'm on
```
"expo": "~51.0.26",
"expo-video": "^1.2.7",
```

**Comment by flyingL123** [comment]
> I'm still getting this error, when trying to set the volume to 0.7 for example. I'm on
> 
> ```
> "expo": "~51.0.26",
> "expo-video": "^1.2.7",
> ```

@timoisalive same here. Trying to set `player.volume = 0.3` and getting the same error.
