### ISSUE TITLE
Cannot find native module 'ExpoSQLiteNext', js engine: hermes

### ISSUE THREAD

**Issue by lemonada02** [expo/expo#29066]
### Minimal reproducible example

https://github.com/lemonada02/tfg-galaxias

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary
I´m using expo react-native with the latests versions
When running `npm install expo-sqlite`  and making import `import * as SQLite from 'expo-sqlite';` it continues to appear this error ```
Error: Cannot find native module 'ExpoSQLiteNext', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```


### Environment

System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-233.14808.21.2331.11842104
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by lemonada02** [comment]
it occurs even using SDK 50 and expo-sqlite@13

**Comment by raijv-p** [comment]
I have the same issue

expo-sqlite: 14.0.3
SDK: 51

**Comment by carlo-rsd** [comment]
I am having the same issue, 

"expo": "~51.0.12",
"expo-sqlite": "~14.0.5"

Were you able to fix it?

**Comment by depasca** [comment]
same issue when trying to open a db with
  `const db = await SQLite.openDatabaseAsync('db.db')`

it fails with : "_ExpoSQLiteNext.default.NativeDatabase is not a constructor"

expo@51.0.24
expo-sqlite@14.0.6

**Comment by ms-chavan** [comment]
I have the same issue. any update on this?

**Comment by vijal-patel** [comment]
Also have the same issue

    "expo": "~51.0.31",
    "expo-sqlite": "~14.0.6",

**Comment by ms-chavan** [comment]
Don't know what worked for me the next day. I reinstall expo-sqlite and restarted server. Didn't see the error again.

**Comment by vijal-patel** [comment]
my solution was to run

`eas build --platform android --profile development`

**Comment by ms-chavan** [comment]
@vijal-patel Kudos!!

**Comment by nard-lee** [comment]
_  const db = SQLite.openDatabaseSync('healthy_recipe.db');
ExpoSQLiteNext.default.NativeDatabase is not a constructor
doesnt work

**Comment by ngounthengos** [comment]
After I rebuilt the android debug apk, it work.

**Comment by baaszunnaiyyer** [comment]
Try rebuilding the App, I believe Reinstalling will Bundle our SQLite in its bundle and It will start to work fine.
