### ISSUE TITLE
Github Pages Dynamic Route Not Feasable

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [expo/expo#29063]
### Minimal reproducible example

https://github.com/rocket-meals/expo-github-pages-dynamic-route-error

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

# Problem

Consider this, we would like to create dynamic routes for our github pages app. Our example is live here: https://rocket-meals.github.io/expo-github-pages-dynamic-route-error/

As we visit our path /test everything works fine: https://rocket-meals.github.io/expo-github-pages-dynamic-route-error/test
As our web.output is `static` and the route gets generated.

But calling now the route with a dynamic value for example: https://rocket-meals.github.io/expo-github-pages-dynamic-route-error/test/NilsBaumgartner1994
Brings the 404 error from github as this route is not found.

# Related Issues and Information

As this problem is already mentioned in #27995 (https://github.com/expo/expo/issues/27995) but was resolved by enabling `single page mode`, which is as far as i know not possible for github pages?
```npx serve -s dist (-s enables single page mode)```

As mentioned in: https://docs.expo.dev/router/reference/static-rendering/#dynamic-routes
The static output will generate HTML files for each route. This means dynamic routes (app/[id].tsx) will not work out of the box. You can generate known routes ahead of time using the generateStaticParams function.

Since for example for a "username" we cannot just simply generate all possible usernames ahead, which means that this is not feasable

# Possible Solution

A possible solution for this could be HashedRouting, altough this would have the drawback of good SEO search ranking.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.8
      expo-router: ~3.5.10 => 3.5.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.6 => 0.19.12
    npmGlobalPackages:
      eas-cli: 7.4.0
    Expo Workflow: managed

**Comment by marklawlor** [comment]
This is an interesting subject, on one hand Github is a limited hosting service which has not implemented a basic hosting feature, and on the other, I understand the need for this feature - I like Github Pages myself.

There are multiple other free hosting services that support Expo Router's dynamic routes and building a feature for only 1 hosting platform takes time and effort away from other features that everyone can benefit from. As such, I'm going to close this issue as 'Won't fix". Our stance on this might change in the future, but for now I'm going to close this to reflect our stance.

I would recommend creating a feature request on [Canny](https://expo.canny.io/feature-requests). If it get enough support we'll evaluate this again.

In the mean time, if you have no choice in hosting providers and much use Github Pages - previously other frameworks have used `404` page hacks. This is an old repo that details the progress in a generic manner, you might be able to achieve something similar. Alternatively, you can avoid using path params and simply use query params.
