### ISSUE TITLE
Expo 51: expo-sensors: DeviceMotion.addListener crashes on Android in eventsToMap (DeviceMotionModule.kt)

### ISSUE THREAD

**Issue by paulschreiber** [expo/expo#29078]
### Minimal reproducible example

https://github.com/paulschreiber/expo-51-sensors-crash/tree/main

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Previously reported as https://github.com/expo/expo/issues/28820 and https://github.com/expo/expo/issues/28879. Partially fixed with https://github.com/expo/expo/pull/28839.

Now, this crash occurs:
```
java.lang.NullPointerException: null
    at expo.modules.sensors.modules.DeviceMotionModule.eventsToMap(DeviceMotionModule.kt:200)
    at expo.modules.sensors.modules.DeviceMotionModule.access$eventsToMap(DeviceMotionModule.kt:28)
    at expo.modules.sensors.modules.DeviceMotionModule$DispatchEventRunnable.run(DeviceMotionModule.kt:165)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
    at java.lang.Thread.run(Thread.java:1012)
```
![Screenshot (May 23, 2024 2_25_16 PM)](https://github.com/expo/expo/assets/86784/1d9c3abd-8040-4830-be9b-7a344d33a9d3)

- Crash only on physical Android devices
  - observed on Pixel 3a with Android 12, Pixel 7 with Android 14 and Pixel7a with Android 14
- Crash does not occur on Android emulator (Android Studio 2023.2)
- Crash does not occur on iOS

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.13.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/paul/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 27, 29, 30, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.74.1 => 0.74.1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by jkaufman** [comment]
This appears to be an oversight in [my PR](https://github.com/expo/expo/pull/28761) adding timestamps. We should be pulling the timestamp off of `rotationRateEvent`, not `rotationEvent`.

**Comment by zcsEason** [comment]
get  the same issue

**Comment by paulschreiber** [comment]
This was fixed by https://github.com/expo/expo/pull/29022.
