### ISSUE TITLE
Unable to resolve import of file after upgrading from SDK 48 to 51 in monorepo

### ISSUE THREAD

**Issue by jesuscovam** [expo/expo#29074]
### Minimal reproducible example

see summary for reference

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I'm trying to upgrade two expo apps inside a yarn monorepo, the apps were on the SDK 48 and after upgrading to 51 they won't start, they are trying to import a file from within expo from the root of the monorepo but I'm not sure why or which dependency should be update to include it

<img width="305" alt="Screenshot 2024-05-23 at 8 52 11 a m" src="https://github.com/expo/expo/assets/46403187/cc56edec-4acc-4cf8-bb5d-576288371728">
<img width="1334" alt="Screenshot 2024-05-23 at 8 52 37 a m" src="https://github.com/expo/expo/assets/46403187/5041e105-ce91-42b0-a212-eebc22e56caa">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 33, 33, 34
        Build Tools: 30.0.3, 33.0.2
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 9.0.6
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

<img width="1366" alt="Screenshot 2024-05-23 at 8 50 07 a m" src="https://github.com/expo/expo/assets/46403187/e7991dd9-d143-4828-a68a-f0c6f665cf22">

**Comment by gopidon** [comment]
Same here. I upgraded from 49 to 50. Expo is unable to resolve file paths. For example:

In my App.js , I refer to local files using absolute path like import xyzzy from 'gst/apollo/client', where 'gst' is the main directory in which all my expo code exists. All these imports are failing at bundle time.

**Comment by gopidon** [comment]
Solution for me:

1. npm i babel-plugin-module-resolver
2. modify babel.config.js

plugins: [
      ['module-resolver',
        {
          alias: {
            gst: '.',
          },
        }
      ]
    ],

**Comment by jesuscovam** [comment]
> Solution for me:
> 
> 1. npm i babel-plugin-module-resolver
> 2. modify babel.config.js
> 
> plugins: [ ['module-resolver', { alias: { gst: '.', }, } ] ],

Thanks for the help!  But this wasn't for me 😢

What I'm understanding is that 'expo-modules-core' shouldn't be something I install in my managed expo apps, its like main package for expo installing expo packages in react-native (not managed) apps, but its also a inner dependency of the new expo 51 SDK.
<img width="743" alt="Screenshot 2024-05-26 at 10 24 49 a m" src="https://github.com/expo/expo/assets/46403187/e42f4684-ac73-4b47-9a2f-565e0035c179">
