### ISSUE TITLE
Send parameters to nested navigators

### ISSUE THREAD

**Issue by Jancera** [expo/expo#29088]
### Minimal reproducible example

https://github.com/Jancera/expo-playground

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have a router structure that looks like this:

```
(private)
     (tabs)
          _layout (Tabs)
          index
     _layout (Stack)
(public)
     sign-in
_layout (Stack)
```

What I want to do is to navigate from `(public)/sign-in` to tabs home `(private)/(tabs)` and send parameters. The navigation can be done without problems, but all params that is sent together are not received by `(private)/(tabs)`.

To navigate I am using the router from `useRouter` with `push` method.

I created a fresh expo project and reproduced the error in it, the code is in my minimal reproducible example link.

### Environment

    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996
    npmPackages:
      expo: ~51.0.8 => 51.0.8
      expo-router: ~3.5.14 => 3.5.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Change your `pathname` to be a pathname

```diff
  const handlePress = () => {
    router.push({
-      pathname: "(private)/(tabs)",
+      pathname: "/(private)/(tabs)",
      params: {
        redirect: "route_to_redirect",
      },
    });
  };
```

I'll add a development error to catch this behaviour
