### ISSUE TITLE
Error Cannot find native module ExpoFontLoader

### ISSUE THREAD

**Issue by husenLogicwind** [expo/expo#29087]
### Minimal reproducible example

https://github.com/react-native-tvos/react-native-tvos

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I have created new react-native-tv-os project and added [react-native-vector-icons](https://www.npmjs.com/package/react-native-vector-icons) and try to use below code at that time this issue occurs

```
import { createIconSetFromIcoMoon } from 'react-native-vector-icons';
const IconMoonIcons = createIconSetFromIcoMoon(icoMoonConfig, 'icomoon', 'icomoon.ttf');
```

![Screenshot_1716542666](https://github.com/expo/expo/assets/63497035/cf20b713-523e-47a5-8cdf-20e7ce14492a)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.14 => 50.0.18 
      react: 18.2.0 => 18.2.0 
      react-native-tvos:  0.74.0-0rc1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check for issues with metro config
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

Error: Problem validating fields in /Users/st-lt-mb-lw017/projects/ott/thinqTv/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config. This can lead to unexpected and hard to debug issues. Learn more: https://docs.expo.dev/guides/customizing-metro/
Advice: Update your custom metro.config.js to extend @expo/metro-config.

The following packages should be updated for best compatibility with the installed expo version:
  @sentry/react-native@5.22.0 - expected version: ~5.20.0
  react-native@0.74.0-0rc1 - expected version: 0.73.6
  react-native-reanimated@3.11.0 - expected version: ~3.6.2
  react-native-safe-area-context@4.10.1 - expected version: 4.8.2
  react-native-screens@3.31.1 - expected version: ~3.29.0
  react-native-svg@13.14.0 - expected version: 14.1.0
  @types/react@18.3.3 - expected version: ~18.2.45
  typescript@5.0.4 - expected version: ^5.3.0
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

**Comment by brentvatne** [comment]
hey there! please resolve the issues that were surfaced by expo doctor. if the issue persists, please create a minimal reproducible example, thanks

also cc @douglowder

**Comment by husenLogicwind** [comment]
@douglowder here the minimal reproducible example [Example](https://github.com/husenLogicwind/TestAppMinimal)

also i have fixed almost all expo doctor warning.
i couldn't fix react native warning because it shows react native version and i have react native tv os version.

<img width="723" alt="Screenshot 2024-05-25 at 10 04 00 AM" src="https://github.com/expo/expo/assets/63497035/813604df-292e-4e32-aa51-63f7697ebcdd">

**Comment by brentvatne** [comment]
hi @husenLogicwind - it looks like perhaps the issue here is that you haven't configured the your Podfile for autolinking expo modules: https://github.com/husenLogicwind/TestAppMinimal/blob/main/ios/Podfile - https://docs.expo.dev/brownfield/installing-expo-modules/

you can compare your Podfile to one in a new tvos project:

```
npx create-expo-app MyTVProject -e with-tv
cd MyTVProject
export EXPO_TV=1
npx expo prebuild -p ios
```

now look at `ios/Podfile`

**Comment by brentvatne** [comment]
got it. you can verify the same thing based on the expo module installation instructions for android

**Comment by Aswanth-c** [comment]
> Author

I'm having same issues did you find any fix

**Comment by fredrikburmester** [comment]
I'd also like to know if there is a fix.

**Comment by yzhe554** [comment]
Why was this closed? Can we reopen it?

**Comment by to-dy** [comment]
Hello @brentvatne,
I'm encountering this issue where our React Native app fails to find the native module ExpoFontLoader on some Android devices, specifically those running Android 9 (e.g., Samsung Galaxy S10,  Redmi Y2). The issue does not occur on all devices, and it seems to be related to the device-specific environment.

Expo SDK version: Expo 51
Android Version: 9 (Samsung Galaxy S10 and other devices)
JavaScript Engine: Happens on both Hermes and V8
`expo-font": "~12.0.10"`

```
     0     0 ? (none)  : --------- beginning of crash
10-16 01:23:35.315 29884 31732 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-16 01:23:35.315 29884 31732 E AndroidRuntime: Process: com.kametventures.qoqoon.familyApp, PID: 29884
10-16 01:23:35.315 29884 31732 E AndroidRuntime: com.facebook.react.common.JavascriptException: Error: Cannot find native module 'ExpoFontLoader', js engine: v8, stack:
10-16 01:23:35.315 29884 31732 E AndroidRuntime: <unknown>@678:149
10-16 01:23:35.315 29884 31732 E AndroidRuntime: <unknown>@698:144
10-16 01:23:35.315 29884 31732 E AndroidRuntime: h@2:1774
10-16 01:23:35.315 29884 31732 E AndroidRuntime: d@2:1248
10-16 01:23:35.315 29884 31732 E AndroidRuntime: i@2:499
10-16 01:23:35.315 29884 31732 E AndroidRuntime: <unknown>@671:926
10-16 01:23:35.315 29884 31732 E AndroidRuntime: h@2:1774
10-16 01:23:35.315 29884 31732 E AndroidRuntime: d@2:1248
10-16 01:23:35.315 29884 31732 E AndroidRuntime: i@2:499
10-16 01:23:35.315 29884 31732 E AndroidRuntime: <unknown>@670:190
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
10-16 01:23:35.315 29884 31732 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
10-16 01:23:35.316 29884 31732 D MonitoringInstr: Handling an uncaught exception thrown on the thread mqt_native_modules.
10-16 01:23:35.316 29884 31732 D MonitoringInstr: com.facebook.react.common.JavascriptException: Error: Cannot find native module 'ExpoFontLoader', js engine: v8, stack:
10-16 01:23:35.316 29884 31732 D MonitoringInstr: <unknown>@678:149
10-16 01:23:35.316 29884 31732 D MonitoringInstr: <unknown>@698:144
10-16 01:23:35.316 29884 31732 D MonitoringInstr: h@2:1774
10-16 01:23:35.316 29884 31732 D MonitoringInstr: d@2:1248
10-16 01:23:35.316 29884 31732 D MonitoringInstr: i@2:499
10-16 01:23:35.316 29884 31732 D MonitoringInstr: <unknown>@671:926
10-16 01:23:35.316 29884 31732 D MonitoringInstr: h@2:1774
10-16 01:23:35.316 29884 31732 D MonitoringInstr: d@2:1248
10-16 01:23:35.316 29884 31732 D MonitoringInstr: i@2:499
10-16 01:23:35.316 29884 31732 D MonitoringInstr: <unknown>@670:190
```

**Comment by MatiasMinian** [comment]
I'm also having this issue it's happening on Expo SDK 50 and apparently only on release builds. Sentry is reporting a lot of occurrences but it's really hard for us te reproduce.
This is causing the app on Android to stop working and getting closed and a blank screen on iOS.
Worth noting that if you open the app again on Android, now it works and if you destroy the app on iOS and open again it works. So this happens from time to time only and then everything works just fine.

Expo Workflow: bare
expo-font: 11.10.3
@expo/vector-icons: 14.0.2
expo: 50.0.19
react-native: 0.73.6

Neither @expo/vector-icons nor expo-font are being used in our code, they are just there because they are deps from the expo package. Excluding them on the app.json still throws the same error.

```
ExpoModulesCore ❌ Cannot install JSI interop: java.lang.IllegalArgumentException: The module wasn't created! You can't access the app context.
    java.lang.IllegalArgumentException: The module wasn't created! You can't access the app context.
    at expo.modules.kotlin.modules.Module.getAppContext(Module.kt:21)
    at expo.modules.kotlin.ModuleHolder$jsObject$2.invoke(ModuleHolder.kt:28)
    at expo.modules.kotlin.ModuleHolder$jsObject$2.invoke(ModuleHolder.kt:26)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at expo.modules.kotlin.ModuleHolder.getJsObject(ModuleHolder.kt:26)
    at expo.modules.kotlin.jni.JSIInteropModuleRegistry.getCoreModuleObject(JSIInteropModuleRegistry.kt:116)
    at expo.modules.kotlin.jni.JSIInteropModuleRegistry.installJSI(Native Method)
    at expo.modules.kotlin.AppContext.installJSIInterop(AppContext.kt:155)
    at expo.modules.kotlin.KotlinInteropModuleRegistry.installJSIInterop(KotlinInteropModuleRegistry.kt:128)
    at expo.modules.adapters.react.NativeModulesProxy.getConstants(NativeModulesProxy.java:103)
    at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:127)
    at com.facebook.jni.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)

ReactNativeJS E  Error: Cannot find native module 'ExpoFontLoader', js engine: hermes

ReactNativeJS E  Invariant Violation: "main" has not been registered. This can happen if:
    * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
    * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

AndroidRuntime  E  FATAL EXCEPTION: mqt_native_modules
    Process: , PID: 16037
    com.facebook.react.common.JavascriptException: Error: Cannot find native module 'ExpoFontLoader', js engine: hermes, stack:
    requireNativeModule@1:744086
    anonymous@1:771499
    loadModuleImplementation@1:123891
    guardedLoadModule@1:123439
    metroRequire@1:123061
    anonymous@1:769413
    loadModuleImplementation@1:123891
    guardedLoadModule@1:123439
    metroRequire@1:123061
    anonymous@1:768903
    loadModuleImplementation@1:123891
    guardedLoadModule@1:123439
    metroRequire@1:123061
    anonymous@1:131536
    loadModuleImplementation@1:123891
    guardedLoadModule@1:123439
    metroRequire@1:123061
    anonymous@1:131322
    loadModuleImplementation@1:123891
    guardedLoadModule@1:123439
    metroRequire@1:123061
    anonymous@1:130167
    loadModuleImplementation@1:123891
    guardedLoadModule@1:123396
    metroRequire@1:123061
    global@1:122613

    at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
    at com.facebook.jni.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
    at java.lang.Thread.run(Thread.java:1012)app.kuna.mobile
```

@to-dy Do you guys manage to find a solution for this?

**Comment by to-dy** [comment]
@MatiasMinian  In our case, the issue was caused by the V8 Js engine.

**Comment by MatiasMinian** [comment]
@to-dy We are using hermes so it's not that for us 😭. I see you are using SDK 51, so we'll try that. Thanks for the reply anyway!

**Comment by Yemisrach15** [comment]
> [@to-dy](https://github.com/to-dy) We are using hermes so it's not that for us 😭. I see you are using SDK 51, so we'll try that. Thanks for the reply anyway!

I'm using sdk 51 and the issue still persists. Is this also the case for you?

**Comment by MatiasMinian** [comment]
@Yemisrach15 We, the same thing is happening to us. Whatever we try, expo-font is still somehow running and failing. We don't use it either. 
We just finished upgrading to SDK 52 and RN 0.76. More than 50% of our users are already in our latest release and so far we haven't seen this error, hopefully this fixes it. We are waiting for at least 1/2 weeks to be sure that these upgrades did the trick

**Comment by Yemisrach15** [comment]
> [@Yemisrach15](https://github.com/Yemisrach15) We, the same thing is happening to us. Whatever we try, expo-font is still somehow running and failing. We don't use it either. We just finished upgrading to SDK 52 and RN 0.76. More than 50% of our users are already in our latest release and so far we haven't seen this error, hopefully this fixes it. We are waiting for at least 1/2 weeks to be sure that these upgrades did the trick

Do you by any chance have `react-native-vector-icons` installed? The expo sdk itself includes `@expo/vector-icons` which is a wrapper around `react-native-vector-icons` by default, if I'm not mistaken. I think these two packages are conflicting. Somehow `@expo/vector-icons` must be using `expo-font` to load the icons' fonts. 

@brentvatne Is there any way to exclude `@expo/vector-icons`?

**Comment by MatiasMinian** [comment]
> Do you by any chance have react-native-vector-icons installed? The expo sdk itself includes @expo/vector-icons which is a wrapper around react-native-vector-icons by default, if I'm not mistaken. I think these two packages are conflicting. Somehow @expo/vector-icons must be using expo-font to load the icons' fonts.

We do have `react-native-vector-icons` installed. I think we tried excluding `@expo/vector-icons` but no luck with that. I don't recall exactly all the things we try and/or if you can exclude it directly in the app.json. You can try that.

We can confirm now that SDK 52 with RN 0.76 fixes this issue. Looking at Sentry, with our new release with these versions, we don't have this error anymore

**Comment by brentvatne** [comment]
hey folks, i'm not sure how to repro this issue. @Yemisrach15 @MatiasMinian - could you share a minimal repro? this does look like the expo-font native module isn't linked for some reason, which would be hard to understand without a repro. if the error that you are seeing is coming from react-native-vector-icons, it could be from the latest version that adds support for dynamic font loading: https://github.com/oblador/react-native-vector-icons/blob/bce85bf5422a3a1b152fb8f7196e002d8ad848d0/packages/common/src/dynamicLoading/dynamic-font-loading.ts#L16-L39 - in this case, again it would be due to expo-font being missing. did you possibly exclude expo-font from your linked modules?

**Comment by endruuu** [comment]
We were upgrading to Expo 51 using `npx expo install expo@^51.0.0 --fix`
The expo-font, being the dependency of other library, was set to `~12.0.10`.

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/fc719bc7-263a-4f28-a69c-62bb4d79d828" />

After setting it explicitly to `12.0.9` in package.json, it worked well.

**Comment by endruuu** [comment]
It might be due to incompatibility issue.
I was upgrading to Expo 51.
I don't have `expo-font` in my package.json.
Somehow, in my package-lock.json, there's `expo-font` 13.0.4. Maybe it is a dependency of other library.

Looks like Expo 51 requires `expo-font` 12.0.10.
After putting `expo-font` explicitly to 12.0.10 in package.json, it worked well.

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/fc1ff60f-831b-40bd-8954-15f73d7db1d0" />
