### ISSUE TITLE
Watchman install not recommended for iOS development [docs] 

### ISSUE THREAD

**Issue by christinachimi** [expo/expo#29096]
### Summary

The docs used to recommend Watchman install for both iOS and Android development, but I think a recent change leaves it out for iOS (see https://github.com/expo/expo/pull/28988/files). Is this intentional? If not, could that be added back in? I am onboarding new devs, trying to stick as close as possible to the docs, and was surprised when it was no longer required.

### Link to the related docs page

https://docs.expo.dev/guides/local-app-development/#ios

**Comment by amandeepmittal** [comment]
Hi @christinachimi, it is recommend in React Native documentation and we'll update our documentation too to include in Set up your environment guide: https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=physical.

Thanks for reporting this.

**Comment by amandeepmittal** [comment]
Thanks for your input @evelant. It seems React Native docs still recommend using Watchman. I think opening an issue in React Native repo to have discussion with core maintainers would be ideal for this scenario. Our goal here is to align the instructions with React Native docs for now to not create confusion (especially for new developers to the React Native community).
