### ISSUE TITLE
Download Profile Button Not Activating on iPhone 11 During Internal Distribution Setup

### ISSUE THREAD

**Issue by burnout909** [expo/expo#29104]
### Summary

![downloadprofile](https://github.com/expo/expo/assets/159466423/a9cf6105-3bae-4d88-bcd4-dd7e7337ff91)

Hello,

I'm facing an issue with the EAS build for internal distribution where the "Download Profile" button is not activating. This problem occurs specifically for two beta testers who both use iPhone 11 devices. I'm not sure if the fact that they are using iPhone 11 is directly causing the issue.

Has anyone encountered a similar problem or can offer any advice on how to resolve this?

Thank you for your help!

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

    "expo-dev-client": "~3.3.11"

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.3 - /opt/homebrew/bin/node
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.15 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: bare

### Reproducible demo

we follow this process : https://docs.expo.dev/build/internal-distribution/
=> we use this command `eas device:create`
=> output of 'eas device:create': https://expo.dev/register-device/~~

**Comment by brentvatne** [comment]
hi there! can you show a video demonstrating this? which ios version is being used?

note that you can work around this by finding the device udid and inputting it manually. https://help.apple.com/xcode/mac/current/#/dev93ef696c6

**Comment by burnout909** [comment]
> hi there! can you show a video demonstrating this? which ios version is being used?
> 
> note that you can work around this by finding the device udid and inputting it manually. https://help.apple.com/xcode/mac/current/#/dev93ef696c6

thanks a lot! Thanks to you I solved the problem
