### ISSUE TITLE
AV -- didJustFinish not eventually-true on Android -- looping problem?

### ISSUE THREAD

**Issue by deklanw** [expo/expo#2910]
### Environment

  Expo CLI 2.6.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

iOS and Android

### Steps to Reproduce

(Write your steps here:)

1. Create some AV that isLooping
2. Observe that didJustFinish isn't eventually true on Android

### Expected Behavior

For didJustFinish to be eventually true on Android.

### Actual Behavior

didJustFinish sometimes isn't eventually true on Android.

### Reproducible Demo

Here's the demo of the issue:
https://snack.expo.io/SkSNbFNkN

On iOS and Android, the "Simple" play option behaves the same. On Android, the "Finite Looping" play option never has `didJustFinish` as `true` so it loops infinitely. And, on Android, the "Infinite Looping" example also never has `didJustFinish` as `true`.

You can observe this difference easily by hitting the buttons on iOS, looking at the logs, then trying the same in Android.

I found someone else posting about something similar,
https://forums.expo.io/t/expo-video-if-playbackstatus-didjustfinish/15734/2

Here is their Snack (it also involves looping):
https://snack.expo.io/ryku4JzTQ

**Comment by sjchmiela** [comment]
Thanks, I put up a PR fixing this behavior, it should get merged into SDK32. 🙂
