### ISSUE TITLE
Expo Router entry-point + monorepo `node_modules` resolution issue

### ISSUE THREAD

**Issue by leggomuhgreggo** [expo/expo#29139]
### Minimal reproducible example

https://github.com/leggomuhgreggo/nx-expo-router-repro-2024-05-25

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Expected Behavior 
The app should start

### What's actually happening

When starting web, the browser opens with the following errors in the console"
```
GET http://localhost:8081/node_modules/expo-router/entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp net::ERR_ABORTED 500 (Internal Server Error)
localhost/:1

Refused to execute script from 'http://localhost:8081/node_modules/expo-router/entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.engine=hermes&transform.routerRoot=src%2Fapp' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
```

![image](https://github.com/expo/expo/assets/2213636/8157a9db-9f35-4a28-ab24-67349b267310)

Here's a screenshot of the debug output

![image](https://github.com/expo/expo/assets/2213636/49c64b59-49ac-4565-9939-90c720e9afed)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.6 => 0.17.7 
      babel-preset-expo: ~10.0.1 => 10.0.2 
      expo: ~50.0.14 => 50.0.19 
      expo-router: ~3.4.10 => 3.4.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
    
    
# Additional Comments

Best I can figure, the current logic assumes the `package.json` with `"main": "expo-router/entry"` and `node_modules` are in the same directory.

But with a folder structure like this, with only a root-level `node_modules`, and no project-level `node_modules`...
```
nx-monporepo
├── apps
│  └── my-test-app
│     ├── src
│     │  └── app
│     │     └── index.tsx
│     ├── app.json
│     ├── eas.json
│     ├── index.js
│     ├── metro.config.js
│     └── package.json
├── node_modules
│  └── expo-router
│     └── entry.js
├── package.json
└── yarn.lock
 ```  
...figure the bundled URL should maybe look like this:
```diff 
- transform.routerRoot=src/app
+ transform.routerRoot=apps/my-test-app/src/app
```

Was pokin around a bit and figurin it must be somethin to do with [`rewriteRequestUrl`](https://github.com/expo/expo/blob/b7238c682ae31c27e63e0e3eeb882d8483d26813/packages/%40expo/metro-config/src/rewriteRequestUrl.ts#L51-L116) in `@expo/metro-config` or maybe [`getExpoRouterAppRoot`](https://github.com/expo/expo/blob/main/packages/babel-preset-expo/src/expo-router-plugin.ts#L14-L22) in `babel-preset-expo`

Had originally suspected babel just because this issue didn't show up prior to the recent `babel-preset-expo` consolidation — but that might be a coincidence.

**Comment by leggomuhgreggo** [comment]
Possibly related to #28940 #24577

**Comment by YuriiLutsykSPRO** [comment]
Add main point to the package json -   "main": "src/index.ts",

index.tsx content - import "expo-router/entry";

**Comment by leggomuhgreggo** [comment]
@YuriiLutsykSPRO thanks for the suggestion! 

I did try a few combinations of the "custom main / entry-point" approach — and I think that helps with some related issues — but it didn't seem to solve the "root-level `node_modules` + project-level entry-point path resolution" issue.

I could try again with the latest versions if there's been a fix, but when I checked last, it didn't seem like there was any recent commits which would have addressed the related logic.

Happy to give it another go if there's been a potential fix.

**Comment by aidankinzett** [comment]
I have this same issue using the [t3-turbo](https://github.com/t3-oss/create-t3-turbo) template

**Comment by evelant** [comment]
The whole contents of `expo-router/entry` is this:

```ts
// `@expo/metro-runtime` MUST be the first import to ensure Fast Refresh works
// on web.
import '@expo/metro-runtime';

import { App } from 'expo-router/build/qualified-entry';
import { renderRootComponent } from 'expo-router/build/renderRootComponent';

// This file should only import and register the root. No components or exports
// should be added here.
renderRootComponent(App);
```

Just paste that into a file and point your package.json `main` to it. Monorepos are super common, almost standard these days, yet unfortunately this issue where libraries use/recomment hard coded paths instead of resolving them are still pretty common.

**Comment by thebiltheory** [comment]
This issue only occurs on **Android**. 
iOS works perfectly in a monorepo setup with `expo-router/entry` as `main`'s value. 

I use **Turborepo** with **pnpm**. Although each project has its own node_modules, most of the main packages are located at the root of the monorepo. Without digging too much into it, I assume this is due to how Android resolves node_modules directories in a monorepo setup. It seems like Android starts by looking for dependencies from the project’s root directory and looks up the hierarchy.

I discovered this issue by running `EXPO_DEBUG=true expo start`. The only error I received was:
```JSON
Request failed with status code 404
```

### Solution Steps
1.  **Create `index.ts`**:  Ensure you have an index.ts file at the root of your application, and import the router like bellow:
```diff
// monorepo/apps/expo-app/index.ts
+import "expo-router/entry";
```

2. **Update`package.json`**': Modify the `main` property in your app's `package.json` to point to the new `index.ts` file.
```diff
{
  "name": "expo-app",
- "main": "expo-router/entry",
+ "main": "index.ts",
   // ...
  }
```

**Comment by leggomuhgreggo** [comment]
Updated the repro, and gave the "custom main + entry proxy" fix another try — success! 

_Can see fix [here](https://github.com/leggomuhgreggo/nx-expo-router-repro-2024-05-25/pull/1)_


Very cool that it works with SVP style monorepos now. 


Thanks to everyone who reported here!
