### ISSUE TITLE
remove tsx file

### ISSUE THREAD

**Issue by MadhavanVelsamy** [expo/expo#29151]
### Summary

I am using Expo 50.while running my app system direct to upgrade Expo 51. so i upgraded to 51.but the environment very different from the older one. Here there is no App.js file it contains only .tsx file how can i use it and how i get App.js

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

npm run android

### Minimal reproducible example

import { Text, View } from "react-native";

export default function index() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Text>Hai & Hello Rahul</Text>
    </View>
  );
}

**Comment by Max-Lovell** [comment]
@MadhavanVelsamy this was closed but what was the answer?
