### ISSUE TITLE
Expo app not starting when upgrading to SDK 51

### ISSUE THREAD

**Issue by Talha12Shiekh** [expo/expo#29159]
### Minimal reproducible example

1) "main" has not been registered . This can happen if Metro is run from the wrong folder Check if the Metro is running , stop it and restart it in the current project A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called  2) Cannot read property 'resizeMode' of undefined 

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I was working on an expo project for a long time it is fairly long project it was all working fine but one day when I tried to start It gave me a warning on a blue screen that you should upgrade to a latest version of sdk or you should download expo go for sdk 50 then what i did is that i installed the latest sdk version i my project and then when i started the project it gives me two errors 

1) "main" has not been registered . This can happen if Metro is run from the wrong folder Check if the Metro is running , stop it and restart it in the current project
A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called

2) Cannot read property 'resizeMode' of undefined 

I tried very much to remove these errors and searched them alot but still it is not fixing can anyone tell how to fix it

![WhatsApp Image 2024-05-26 at 10 01 28 AM (1)](https://github.com/expo/expo/assets/137197166/e424874a-2879-47d4-9ae9-1ad1a8beb2a7)

![WhatsApp Image 2024-05-26 at 10 01 28 AM](https://github.com/expo/expo/assets/137197166/286b50d0-a5c3-4679-92e0-7421e3cd467e)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.17134
    Binaries:
      Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^51.0.8 => 51.0.8
      react: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: managed

### Expo Doctor Diagnostics

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check for issues with metro config
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Error: Problems validating fields in C:\Users\Hp\Documents\reactnativeultimateprojects\app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'debug'.
 • Field: android - should NOT have additional property 'enableHermes'.

One or more checks failed, indicating possible issues with the project.

**Comment by brentvatne** [comment]
also see: https://expo.fyi/no-registered-application

this seems related to `Cannot read property 'resizeMode' of undefined` - you probably have some code that is trying to access `resizeMode` on an object that is now undefined
