### ISSUE TITLE
[Android][expo-web-browser][expo-auth-session] Web based auth session is closed when user returns to the app by clicking the app icon

### ISSUE THREAD

**Issue by MarchewkaMatthew** [expo/expo#29153]
### Minimal reproducible example

https://github.com/MarchewkaMatthew/expo-web-browser-bug-repro

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

In our managed workflow expo app we are using **expo-auth-session** for authenticating the user. During the process user needs to type in the code from the SMS message, most of the users manage to enter the code from the popup but some of them need to minimize our app to open the SMS app to copy the code. It works fine in the iOS app, but on Android when user opens the app by clicking the app icon, the auth flow is closed and the app returns to the initial state.

It works correctly on Android when the user opens the app via the recently opened apps tab.

After some investigation, I found out that the same issue appears in the **expo-web-browser openBrowserAsync flow.** In this comment: https://github.com/expo/expo/issues/8072#issuecomment-1983421803 I posted the potential source of the problem.

Here is the video of the unexpected behavior: https://drive.google.com/file/d/1iW2jDldOgW3URTKAeH-GjYHE4f9vXLtu/view?usp=sharing copied from this ticket: https://github.com/expo/expo/issues/18948

**Expected behavior:**
The authentication flow is not canceled when the user re-opens the minimized app by clicking the app icon. We would like to keep the same auth session until the user either manually cancels it via the close button, or finalizes the process and redirects back to the app.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2023.09.25.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      expo-router: ~3.5.14 => 3.5.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 7.8.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

<img width="509" alt="image" src="https://github.com/expo/expo/assets/56259093/56861e3f-6f47-4e70-a9aa-48dad45183e6">

**Comment by MarchewkaMatthew** [comment]
Hi @brentvatne, thanks for the response. Unfortunately changing these options, doesn't help. When I come back to the app via the app icon, the app is reset to the initial state (from before opening a link), the only difference is that the web auth flow is still open in the recent apps, but I'm afraid that some of the users may not notice that.

**Comment by MarchewkaMatthew** [comment]
Hi @brentvatne, is there anything else you would recommend to solve this problem? Do you consider this as a bug in the `expo-auth-session` or maybe it works as intended, and we should look for an alternative solution? Thanks in advance, for any support.

**Comment by martinzilak** [comment]
@MarchewkaMatthew I've spent some time playing around with `expo-web-browser` and `expo-auth-session` and came to the conclusion that this happens somwhere "deeper" in the Android application. When I tried patching `_onAppStateChangeAndroid` in `expo-web-browser`'s **WebBrowser**, the Chrome custom tab still closed after reopening the app via the launcher icon, Expo libraries just didn't detect it as closed and prevented re-opening it because it got stuck in a locked state.

Then I found [this comment](https://github.com/stripe/stripe-react-native/issues/355#issuecomment-1701323254):

> Basically, instead of just having one MainActivity where deeplink support requires you to give the MainActivity a launchMode of "singleTask", you split the application into two activites. One that is responsible for launching the app from the android launcher, and one that is then started by that 'launcher activity' and retains the singleTask launchmode.

From there I got to this [very well described fix](https://github.com/stripe/stripe-react-native/blob/master/docs/android-chrome-tab-closes-on-background.md), but since I didn't want to eject from managed mode, I had to write a config plugin to do these changes in the native code from within Expo. I don't like the approach too much, but it seems to work well.

In the root of my project, I've created this file structure:
```
├── plugins
│   └── withCustomAndroidActivityAndManifest
│       ├── native
│       │   └── android
│       │       └── LaunchActivity.kt
│       └── withCustomAndroidActivityAndManifest.config.js
```

and linked it from **app.config.js**
```js
{
  expo: {
    ..,
    plugins: [
      ...,
      './plugins/withCustomAndroidActivityAndManifest/withCustomAndroidActivityAndManifest.config.js',
    ],
  }
}
```

**LaunchActivity.kt** looks like this (basically just what guide instructs but rewritten into Kotlin):
```kt
package expo.android.package // CHANGE THIS

import android.app.Activity
import android.content.Intent
import android.os.Bundle

class LaunchActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val application = getApplication() as MainApplication
        if (!application.isActivityInBackStack(MainActivity::class.java)) {
            val intent = Intent(this, MainActivity::class.java)
            startActivity(intent)
        }
        finish()
    }
}
```

And then finally, the part I'm not too happy about, **withCustomAndroidActivityAndManifest.config.js**:
```js
const { withAndroidManifest, withMainActivity, createRunOncePlugin, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const mergeContents = (originalContent, newContent, anchor, offset = 1) => {
  const lines = originalContent.split('\n');
  const anchorIndex = lines.findIndex(line => line.includes(anchor));
  if (anchorIndex === -1) {
    throw new Error(`Anchor "${anchor}" not found in the provided content.`);
  }
  const insertIndex = anchorIndex + offset;
  const newLines = newContent.split('\n');
  lines.splice(insertIndex, 0, ...newLines);
  return lines.join('\n');
};

const withCustomAndroidActivityAndManifestConfig = config => {
  // Modify AndroidManifest.xml
  config = withAndroidManifest(config, config => {
    const manifest = config.modResults;

    // Define the new launcher activity
    const newLauncherActivity = {
      $: {
        'android:name': '.LaunchActivity',
        'android:exported': 'true',
      },
      'intent-filter': [
        {
          action: [
            {
              $: {
                'android:name': 'android.intent.action.MAIN',
              },
            },
          ],
          category: [
            {
              $: {
                'android:name': 'android.intent.category.LAUNCHER',
              },
            },
          ],
        },
      ],
    };

    // Add the new launcher activity
    manifest.manifest.application[0].activity.push(newLauncherActivity);

    // Remove MAIN and LAUNCHER intent filters from MainActivity
    const mainActivity = manifest.manifest.application[0].activity.filter(
      activity => activity.$['android:name'] === '.MainActivity'
    );

    if (mainActivity.length > 0) {
      delete mainActivity[0]['intent-filter'];
    }

    return config;
  });

  // Modify MainApplication.kt
  config = withDangerousMod(config, [
    'android',
    async config => {
      const mainApplicationPath = path.join(
        config.modRequest.platformProjectRoot,
        'app/src/main/java/EXPO/ANDROID/PACKAGE/MainApplication.kt'
      ); // CHANGE THIS
      const mainApplicationContent = await fs.promises.readFile(mainApplicationPath, 'utf8');

      const newMainApplicationMethods = `
      private val runningActivities = ArrayList<Class<*>>()
  
      fun addActivityToStack(cls: Class<*>) {
          if (!runningActivities.contains(cls)) runningActivities.add(cls)
      }
  
      fun removeActivityFromStack(cls: Class<*>) {
          if (runningActivities.contains(cls)) runningActivities.remove(cls)
      }
  
      fun isActivityInBackStack(cls: Class<*>): Boolean {
          return runningActivities.contains(cls)
      }`;

      const modifiedMainApplicationContent = mergeContents(
        mainApplicationContent,
        newMainApplicationMethods,
        'class MainApplication',
        1
      );
      await fs.promises.writeFile(mainApplicationPath, modifiedMainApplicationContent, 'utf8');
      return config;
    },
  ]);

  // Modify MainActivity.kt
  config = withDangerousMod(config, [
    'android',
    async config => {
      const mainActivityPath = path.join(
        config.modRequest.platformProjectRoot,
        'app/src/main/java/EXPO/ANDROID/PACKAGE/MainActivity.kt'
      ); // CHANGE THIS
      const mainActivityContent = await fs.promises.readFile(mainActivityPath, 'utf8');

      // Insert the new code within the existing onCreate method
      const newOnCreateContent = `
      (application as MainApplication).addActivityToStack(this.javaClass)`;
      const partiallyModifiedMainActivityContent = mergeContents(
        mainActivityContent,
        newOnCreateContent,
        'super.onCreate(null)',
        1
      );

      // Add the onDestroy method
      const newOnDestroyMethod = `
      override fun onDestroy() {
          super.onDestroy()
          (application as MainApplication).removeActivityFromStack(this.javaClass)
      }`;
      const modifiedMainActivityContent = mergeContents(
        partiallyModifiedMainActivityContent,
        newOnDestroyMethod,
        'class MainActivity',
        1
      );

      await fs.promises.writeFile(mainActivityPath, modifiedMainActivityContent, 'utf8');
      return config;
    },
  ]);

  // Copy LaunchActivity.kt
  config = withMainActivity(config, async config => {
    const launcherActivityPath = path.join(
      config.modRequest.platformProjectRoot,
      'app/src/main/java/EXPO/ANDROID/PACKAGE/LaunchActivity.kt'
    ); // CHANGE THIS
    const customLauncherActivityPath = path.resolve(__dirname, './native/android/LaunchActivity.kt');

    await fs.promises.copyFile(customLauncherActivityPath, launcherActivityPath);
    return config;
  });

  return config;
};

module.exports = createRunOncePlugin(
  withCustomAndroidActivityAndManifestConfig,
  'withCustomAndroidActivityAndManifestConfig',
  '1.0.0'
);

```

Be careful to replace the `package` in **LaunchActivity.kt** and fix file paths as needed, if you need to verify your Android project structure you can always run the `preview` target (and then remove the `android` and `ios` generated folders after).

Lastly, I've noticed [this comment](https://github.com/proyecto26/react-native-inappbrowser/issues/213#issuecomment-2165493514) which would simplify this quite a lot, but I haven't had time to verify whether it works.

**Comment by martinzilak** [comment]
I've noticed an issue with my solution posted above - when editing the **AndroidManifest.xml**, I was unintentionally removing all intent filters from the `MainActivity`, not only the one responsible for launching the app from launcher. The second intent filter it had was responsible for handling deeplinks. I'm providing an updated version that should handle this properly and won't break deeplinking:

```js
// Modify AndroidManifest.xml
  config = withAndroidManifest(config, config => {
    const manifest = config.modResults;
    const mainActivity = manifest.manifest.application[0].activity.find(
      activity => activity.$['android:name'] === '.MainActivity'
    );

    if (mainActivity) {
      // Remove MAIN and LAUNCHER intent-filter from MainActivity
      mainActivity['intent-filter'] = mainActivity['intent-filter'].filter(
        filter =>
          !(
            filter.action.some(action => action.$['android:name'] === 'android.intent.action.MAIN') &&
            filter.category.some(category => category.$['android:name'] === 'android.intent.category.LAUNCHER')
          )
      );

      // Make sure that launch mode is SINGLE TASK
      mainActivity.$['android:launchMode'] = 'singleTask';
    }

    // Add LaunchActivity with MAIN and LAUNCHER intent-filter
    manifest.manifest.application[0].activity.push({
      $: { 'android:name': '.LaunchActivity', 'android:exported': 'true' },
      'intent-filter': [
        {
          action: [{ $: { 'android:name': 'android.intent.action.MAIN' } }],
          category: [{ $: { 'android:name': 'android.intent.category.LAUNCHER' } }],
        },
      ],
    });

    return config;
  });
```

**Comment by Bardiamist** [comment]
Another issue which probably overlaps with this:
Some Android users have `MissingCurrentActivityException` from `expo-store-review`.
I think it maybe because I added `LaunchActivity` as [here](https://github.com/proyecto26/react-native-inappbrowser/issues/213#issuecomment-2165493514).

**Comment by z1haze** [comment]
This issue isn't fixed. The bot automatically closing issues as stale simply because the expo team doesn't look at the issues isn't beneficial.
