### ISSUE TITLE
Expo Android app crashing right after launch, iOS working, new NativeEventEmitter() was called

### ISSUE THREAD

**Issue by jankamon** [expo/expo#29174]
### Minimal reproducible example

https://github.com/jankamon/my-app

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I build app using Expo and discovered that the Android version of my app is crashing right after launch (iOS version is working). I reproduced this by launching "npx expo start --no-dev --minify" but in normal dev mode app is working.
Console is silent, only warning which I see in Expo Go is "`new NativeEventEmitter()` was called..." but I can't read it all, it's cut in half and it's not possible to open this warning and see details.

I updated dependencies (below) and tried debug with Sentry but it seems that bug occurs before App.tsx is launched because I didn't log anything.

On fresh created project by "npx create-expo-app@latest" I have the same problem but here even in dev mode Android is throwing the same error.

Can you help me what is going on and why Expo isn't logging any errors?

### Environment

expo-env-info 1.2.0 environment info:
    System:
    OS: Windows 10 10.0.19045
    Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
    expo: ~51.0.8 => 51.0.8
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-native: 0.74.1 => 0.74.1
    react-native-web: ~0.19.12 => 0.19.12
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
    ✔ Check package.json for common issues
    ✔ Check native tooling versions
    ✔ Check dependencies for packages that should not be installed directly
    ✔ Check for common project setup issues
    ✔ Check npm/ yarn versions
    ✔ Check for issues with metro config
    ✔ Check Expo config (app.json/ app.config.js) schema
    ✔ Check for legacy global CLI installed locally
    ✔ Check that native modules do not use incompatible support packages
    ✔ Check that packages match versions required by installed Expo SDK
    ✔ Check that native modules use compatible support package versions for installed Expo SDK
Didn't find any issues with the project!

**Comment by brentvatne** [comment]
i tried to reproduce this using the information given and i was unable to do so
