### ISSUE TITLE
`expo-video` listener events not triggered on the web (+ expo snacks fails to run `expo-video` on android)

### ISSUE THREAD

**Issue by kimchouard** [expo/expo#29186]
### Minimal reproducible example

https://snack.expo.dev/@kimik/765825

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

## `player.addListener` not called on Web

Calling the `player.addListener(...)` would trigger the function on native, but the events are not fired on Web.

See [this snack](https://snack.expo.dev/@kimik/765825), based on the [doc example](https://docs.expo.dev/versions/v51.0.0/sdk/video/#usage): does not `console.log` on isPlaying change on web, but it works on iOS.

![CleanShot 2024-05-29 at 10 21 01@2x](https://github.com/expo/expo/assets/2856923/5c37bd53-427a-490d-b93b-7aafa43e4894)

![CleanShot 2024-05-29 at 10 20 05@2x](https://github.com/expo/expo/assets/2856923/a750b80a-7abb-4b4c-bfc4-bc0b513b103c)

## `expo-video` doesn't run on Expo snacks

I couldn't really test this on Android since the Expo Snack is failing the doc example at build-time:
![CleanShot 2024-05-29 at 10 23 24@2x](https://github.com/expo/expo/assets/2856923/65061226-a87d-4060-aaa2-816c927b4e75)

## `player.duration` or `player.currentTime` not accessible on `useVideoPlayer` callback (Web-only)

When trying to access those 2 parameters on the `useVideoPlayer` callback, it throws an odd `player is undefined error, whereas this error is not thrown when `player.duration` and such are called in `useEffect` (only on Web, works fine on iOS):

![CleanShot 2024-05-29 at 10 38 03@2x](https://github.com/expo/expo/assets/2856923/5bf77afc-831f-4925-982d-119e6ac7f468)

Un-comment line 18 and 19 on the expo snack to see for yourself 🤓

I've had a more detailed error message when ran locally, which seems to point [line 115 of the `VideoPlayer.web.tsx` file](https://github.com/expo/expo/blob/28aea768db84be0b81ef9675c2e91d3a726c6372/packages/expo-video/src/VideoPlayer.web.tsx#L115), as if the `_mountedVideos` array was empty 🤔

## API Feedback/Doc improvements

Also, a few questions to better understand the API, so that I can put together a PR to improve the current doc:
- [ ] `player.duration` seems to be available, would it be okay to add it to the [VideoPlayer properties](https://docs.expo.dev/versions/v51.0.0/sdk/video/#videoplayer) in the docs?
- [ ] What is the use of passed a `ref` value to the `VideoView`? Is that just a requirement with no added value, or is there anything we can do with the ref? If it can be used, it'll be interesting to document it (currently not listed in the [`VideoView` props list](https://docs.expo.dev/versions/v51.0.0/sdk/video/#videoview). If it's needed to function, could that be done on the Expo side so we get rid of this parameter and simplify the API?
- [ ] High level question: why for all the time variable, it was chosen to use a `float` with `seconds` instead of an `integer` with `ms`? Seems like the norm with timestamp is usually `ms`, so this kind of break the patern. :)
- [ ] Any plan to add audio panning support [like in the expo-av lib](https://docs.expo.dev/versions/v51.0.0/sdk/video-av/#audiopan)?

Thanks @alanjhughes for modernizing the video library though! 🙌🏻🫶

### Environment

Web (+ android failing on Expo Snacks)

### Expo Doctor Diagnostics

N/A (expo snacks)

**Comment by kimchouard** [comment]
any luck on this @alanjhughes ? 🙏  Not having event listeners on Web is a BIG blocker 😬

**Comment by alanjhughes** [comment]
Hi @kimchouard! Sorry for the late response, @behenate is primarily working on this package so he will look in to this

**Comment by kimchouard** [comment]
okay great, thanks for the redirect! 🤙

@behenate thanks in advance for your help here 🙌

**Comment by behenate** [comment]
@kimchouard Hi! Expo-video is still in beta, therefore it's not supported in Expo Go and Snack, so this is expected behaviour. You can create a development build to run expo-video in your projects.

As for the events, this is a valid and known issue, due to timing related with releasing SDK 51, we couldn't land them in time (also we focused mostly on Android and iOS version for SDK 51). They should be implemented soon and probably released with SDK 52 :) 

Let's keep this issue open until a PR with event listeners for web is up

**Comment by kimchouard** [comment]
Okay thanks for the heads up @behenate. What's the rough timing for SDK 52 again? :) 

Also re: Expo Go/Snack, most of the example screenshots are just a reproduction of what it would be in a local build. It's just the Android error that's related to Expo Snack, but not a real problem for now tbh. The event listener on Web issue is the real monster 👹

**Comment by behenate** [comment]
The monster 👹 has been tackled in https://github.com/expo/expo/pull/29742 😅
I'll discuss if we want to backport it to SDK 51, so you can use it before SDK 52 releases 😄

**Comment by kimchouard** [comment]
MY MAN @behenate !!!!! 🚀🙌🏻

Thanks a bunch for fixing this. Hoping it can be backported to 51 since we plan to go live early next-month, but would understand if it's a big overhead and have to wait for SDK 52. I have a (very dirty) workaround that's working for now. 😬

**Comment by kimchouard** [comment]
Hi @behenate, hope you're well :) We're still stuck with this and hoping to unify behavior from Web and Mobile for our launch. 
=> Since v52 won't be here before October, **do you have any news on whether this is going to be backported to v51 or not?**

Thanks !!

FYI @jeandes-code

**Comment by behenate** [comment]
@kimchouard It should already be backported :) For expo-video we are backporting everything that can be backpoted.

**Comment by kimchouard** [comment]
I can validate it's now working, thanks! 🙌 

I've also listed some feedback points above, any thoughts on those? @alanjhughes 
- [ ] `player.duration` seems to be available, would it be okay to add it to the [VideoPlayer properties](https://docs.expo.dev/versions/v51.0.0/sdk/video/#videoplayer) in the docs? (I can do a PR for it)
- [ ] What is the use of passed a `ref` value to the `VideoView`? Is that just a requirement with no added value, or is there anything we can do with the ref? If it can be used, it'll be interesting to document it (currently not listed in the [`VideoView` props list](https://docs.expo.dev/versions/v51.0.0/sdk/video/#videoview). If it's needed to function, could that be done on the Expo side so we get rid of this parameter and simplify the API?
- [ ] High level question: why for all the time variable, it was chosen to use a `float` with `seconds` instead of an `integer` with `ms`? Seems like the norm with timestamp is usually `ms`, so this kind of break the pattern. :)
- [ ] Any plan to add audio panning support [like in the expo-av lib](https://docs.expo.dev/versions/v51.0.0/sdk/video-av/#audiopan)?

**Comment by behenate** [comment]
@kimchouard 
- `player.duration` [is visible](https://docs.expo.dev/versions/v51.0.0/sdk/video/#duration) in the docs for me 
- You can use the ref to call the functions of the video view such as entering/exiting fullscreen and picture in picture. You can leave it empty if you won't be using any of the [View's functions](https://docs.expo.dev/versions/v51.0.0/sdk/video/#component-methods)
- We are trying to be as close as possible to the web `<video>` tag in terms of usability/API, and it uses seconds as the duration. Also even though `milliseconds` are more popular using base SI units seems a bit nicer to us 😄 
- It's quite low on the priority list. If you can't wait we are open to PR's 😉

**Comment by kimchouard** [comment]
Dope, thanks @behenate for the answers ;)

Closing this issue then. Keep up the great work! 🙌
