### ISSUE TITLE
expo-camera `enableTorch` prop does nothing if set to true

### ISSUE THREAD

**Issue by Adam-Schlichtmann** [expo/expo#29182]
### Minimal reproducible example

https://snack.expo.dev/@mada1113/enabletorch-example

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

When using the new `enableTorch` prop for the `CameraView` from `expo-camera` if you set the value to always be `true`. The torch is never turning on.

In the reproducible example I do have a workaround using `setTimeout` to toggle the `enableTorch` value, but it is not ideal. 

### Environment

Expo Snack running 
Expo v51
"expo-camera": "~15.0.9"

### Expo Doctor Diagnostics

Expo Snack

**Comment by Harishhrk** [comment]
facing the same issue

**Comment by yohavrotsztein** [comment]
Same here. And the torch is really the center of my app. Any news about this?

**Comment by alanjhughes** [comment]
@yohavrotsztein see referenced PR

**Comment by bamba0799** [comment]
enableTorch= {true} a reglé mon probleme

**Comment by bennettfrazier** [comment]
What version will this be released in for the SDK? Is there a version of 51 that works with torchMode enabled?

**Comment by totolicious** [comment]
Found a messy workaround, but for me it works - I enable the torch after 500ms after I'm rendering the CameraView.
I'm doing this because i was suspecting that something needed to be initialized (related to the CameraView component) before using the torch.

It might be something else, but it works :D

**Comment by totolicious** [comment]
try this

```
const [isFlashEnabled, setIsFlashEnabled] = useState(false);
const [isCameraReady, setIsCameraReady] = useState(false);

const handleCameraReady = async () => {
    try {
      const value = await AsyncStorage.getItem(FLASH_PREFERENCE_KEY);
      if (value === 'true') {
        setTimeout(() => {
          setIsFlashEnabled(true);
          setIsCameraReady(true);
        }, 1000);
      } else {
        setIsCameraReady(true);
      }
      
    } catch (error) {
      console.error('Failed to load flash preference:', error);
    }
  };
```

and then later
```
      <CameraView
        ref={cameraRef}
        facing="back"
        enableTorch={isFlashEnabled}
        onCameraReady={handleCameraReady}
      >
        {isCameraReady && (
          <>
            {/* Flash toggle button */}
            <View style={styles.flashButton}>
              <Button
                circular
                size="$3"
                onPress={toggleFlash}
                backgroundColor={isFlashEnabled ? '$yellow8' : 'transparent'}
                borderColor="white"
                borderWidth={1}
              >
                <Ionicons
                  name={isFlashEnabled ? 'flash' : 'flash-off'}
                  size={24}
                  color="white"
                />
              </Button>
            </View>

            {/* Capture button */}
            <View>
              <Circle
                size={80}
                pressStyle={{ scale: 0.9 }}
                onPress={takePhoto}
              />
            </View>
          </>
        )}
      </CameraView>
```
