### ISSUE TITLE
[expo-contacts] presentFormAsync conflicts with presentContactPickerAsync

### ISSUE THREAD

**Issue by jp1987** [expo/expo#29195]
### Minimal reproducible example

https://github.com/jp1987/expo-contact-ios-state/tree/main

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I can not reproduce this on the simulator, only on a physical device.

Steps to reproduce:

- Call `Contacts.presentFormAsync` to add a new contact
- Cancel the process
- Call `Contacts.presentContactPickerAsync` to pick a contact
- Cancel the process
- Background app
- Foreground app
- Call `Contacts.presentContactPickerAsync` to pick a contact

Now we're in a "unsaved draft" state from the first `presentFormAsync` call, that we have to dismiss first.

https://github.com/expo/expo/assets/1288101/0a8a8a9d-f6d7-4cfe-976f-81d25b25fa7e

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 9.1.2 - /usr/local/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/jesperpaardekooper/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.7
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by jp1987** [comment]
Sadly, considering https://github.com/expo/expo/issues/29191 and https://github.com/expo/expo/issues/28951 as well, the contact picker feature seems quite unstable at the moment.

**Comment by jp1987** [comment]
I have noticed that only calling `Contacts.presentFormAsync` once, backgrounding the app, then going to the iOS native dialer, also gives the same "unsaved draft" popup.

So either `Contacts.presentFormAsync` doesn't fully cancel the entire process, or this is an iOS bug?

https://github.com/expo/expo/assets/1288101/6e9dce15-9add-4fc6-a665-910f1e0022d5

**Comment by alanjhughes** [comment]
@jp1987 did your PRs resolve this or is this a separate issue?

**Comment by jp1987** [comment]
> @jp1987 did your PRs resolve this or is this a separate issue?

@alanjhughes it's a separate issue

**Comment by alanjhughes** [comment]
Hi @jp1987 I've investigated this and it is a bug in iOS. I've created a native project and can reproduce the same behaviour. Looks using the cancel button and confirming with "Discard Changes" does not actually result in the changes being discarded. I've also seen that the `CNContactViewController` does not let us alter the navigation bar which is another issue so the `cancelButtonTitle` has no effect. I will report it to Apple but there's not much else we can do unfortunately.

**Comment by jp1987** [comment]
> Hi @jp1987 I've investigated this and it is a bug in iOS. I've created a native project and can reproduce the same behaviour. Looks using the cancel button and confirming with "Discard Changes" does not actually result in the changes being discarded. I've also seen that the `CNContactViewController` does not let us alter the navigation bar which is another issue so the `cancelButtonTitle` has no effect. I will report it to Apple but there's not much else we can do unfortunately.

Thanks for looking into that. If you do report it, could you share the link?

**Comment by alanjhughes** [comment]
Will do 👍
