### ISSUE TITLE
Unresolved reference: BuildConfig on expo-notifications 28

### ISSUE THREAD

**Issue by ampopdev** [expo/expo#29190]
### Minimal reproducible example

https://github.com/ampopdev/demo-my-app-expo

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Just run: yarn && npx react-native run-android on the minimal reproducible example. Then getting error:

```
MainApplication.kt:41:9 Unresolved reference: BuildConfig FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':app:compileDebugKotlin'
```

Tried adding `android.defaults.buildfeatures.buildconfig=true` in `gradle.properties` and `buildConfig = true` in build.gradle but didn't help as suggested [here](https://stackoverflow.com/questions/60942575/unresolved-reference-buildconfig-in-kotlin). 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.1/bin/yarn
      npm: 10.7.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.8 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by douglowder** [comment]
This does not seem to have any relation to notifications. The errors I'm seeing are in MainActivity.kt and MainApplication.kt.

Can you write down the steps you used to generate this project? Is there some specific reason you do not want to start with an Expo project?

**Comment by ampopdev** [comment]
@douglowder yes there is a problem with the expo dependencies connected with the new BuildConfig, more info [here](https://stackoverflow.com/questions/60942575/unresolved-reference-buildconfig-in-kotlin). This is a bare RN project using expo and was generated as [doc](https://docs.expo.dev/bare/installing-expo-modules/) and was working fine until new version 50.

**Comment by ampopdev** [comment]
Is there any updates on this issue @douglowder @brentvatne?
