### ISSUE TITLE
exp.json isRemoteJSEnabled not working

### ISSUE THREAD

**Issue by voyage11** [expo/expo#292]
According to the documentation (https://docs.expo.io/versions/v16.0.0/guides/configuration.html), 

> **isRemoteJSEnabled**
> If set to false, your standalone app will never download any code, and will only use code bundled locally on the device. In that case, all updates to your app must be submitted through Apple review. Defaults to true.

I have set `"isRemoteJSEnabled": false,` in exp.json but I still couldn't remove the dependency of Expo server. Every time I kill and re-open the app, the app will check and download the latest JS code from expo server. 

There was one similar issue: https://github.com/expo/expo/issues/228 @terribleben mentioned that `"The very first load cannot be offline."`

I found out that it is not true. This is how I found out:-
1. I published app with Version 1.0.0 with Build 1 via Expo XDE. 
2. I achieved app with Version 1.0.0 with Build 1 to TestFlight.
3. I downloaded the app Version 1.0.0 with Build 1 from TestFlight and opened for the First time (First load).
4. I changed the app to Version 1.0.0 with Build 2 and at the same time I added a new Google event tracking. I published this new app via Expo XDE. 
5. I killed the app that I previously downloaded from TestFlight and re-launched it, I checked the version and it was Version 1.0.0 with Build 2. The new Google tracking was there as well.

It means that even if I set `"isRemoteJSEnabled": false,` the app still downloads the latest code from the Expo server. 

I would like to remove the dependency from Expo server because some of our users complained that they couldn't load the app. It must be related to the First loading and Expo server. 

The Expo server must be located far away from from south east asia (eg: Singapore)?

Any help would be appreciated related to remove the dependency on the Expo Server for the First loading. Thanks.

**Comment by btk** [comment]
Is it just a typo or are you trying it with the `expo.json` instead `exp.json`. You write multiple times the file name as `expo.json` so its probably your coffee time.

Check the name of the file explicitly: https://docs.expo.io/versions/v16.0.0/guides/configuration.html

**Comment by voyage11** [comment]
Yes, it is just a type. should be `exp.json`. I just edited it.

**Comment by dikaiosune** [comment]
@voyage11 from the steps you listed, this is happening on iOS, correct? Is it also happening on Android?

**Comment by voyage11** [comment]
@dikaiosune So far I only tested in iOS since the majority users of my apps are using iOS. I haven't test on Android yet.

**Comment by terribleben** [comment]
Are you using ExpoKit? (based on a separate support thread, I believe you are.)

**Comment by voyage11** [comment]
Yes, I am using ExpoKit.

**Comment by terribleben** [comment]
I think we solved this on slack for now - the long term solution is for Expo to implement [this](https://expo.canny.io/feature-requests/p/preload-app-js-for-expokit-projects), so I'll close the issue in favor of that request.

**Comment by voyage11** [comment]
"Solved this on slack"? I am not on Expo Slack. 

As for the long term solution that you suggestion, I actually tried this method before.
> Manually preload your app's JS and manifest in shell-app-manifest.json and shell-app.bundle (there's no tool for this, you'd need to roll your own),

But the First load is still slow. Sometimes when our mobile connectivity is slow (within a building with no wifi connection), we will see blank page on the First load. There are some users complained to us about this issue as well.

Due to this issue, we have been thinking to move away from Expo if there is no solution in the short term. 

So, I believe this issue should be given a higher priority.

**Comment by voyage11** [comment]
Just an update. We have removed expo from our app for a few months now. It has been much better in term of loading speed. We didn't receive any user complains about the slowness nor the blank page ever since.

**Comment by idealtechno** [comment]
I am having this issue on android as well. 
Not able to install and see changes, when I install a new version over the previous version. 
When I launch the app second time it haves the changes for the new version. 
It is loading from the internet. New JS code.

**Comment by terribleben** [comment]
Just an update on this very old thread:

- ExpoKit iOS projects do preload your JS and manifest now, so your code is present even with no internet connection. (they didn't do that when the thread was originally opened.)
- `ios.isRemoteJSEnabled: false` will prevent your iOS app from fetching any new JS. (there is no equivalent Android key.)
- We're still working on supporting bundled assets to enable [first-load-offline](https://expo.canny.io/feature-requests/p/allow-standalone-apps-to-load-and-function-with-no-internet-connection), though we expect to launch this very soon.

**Comment by idealtechno** [comment]
My android app shows this. And it's not the first load. And I have built it using command
'exp build:android' 
Why does this appears if it's not loading the code from Exponent Server.
![screenshot_20171215-185734](https://user-images.githubusercontent.com/34381255/34101493-b6cf04d2-e407-11e7-8945-8ce76cd9dd2e.png)

**Comment by terribleben** [comment]
Hey there! Like I mentioned in the previous comment, you are using an iOS-only key, `ios. isRemoteJSEnabled`, which doesn't do anything on Android.

**Comment by trsh** [comment]
@terribleben we need an Andriod solution ASAP. This is not serious :/

**Comment by nurpax** [comment]
I noticed in https://github.com/expo/expo/issues/1486 that isRemoteJSEnabled:false seems to prevent updating the application JS code, but the contents of app.json (as read by Expo.Constants.manifest) do NOT seem to be bundled into the app that is uploaded to the App Store.  Old builds on the App Store seem to report a newer build number.
