### ISSUE TITLE
The application works on Expo Go, but when I open it as APK on my phone, it closes like this. Where could the problem be?

### ISSUE THREAD

**Issue by emrekizilkaya** [expo/expo#29200]
### Summary

**my eas.json:**
{
  "cli": {
    "version": ">= 7.8.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "android": {
        "buildType": "apk",
        "distribution": "internal"
      }
    },
    "production": {
      "android": {
        "buildType": "apk"
      }
    }
  },
  "submit": {
    "production": {}
  }
}

**my app.json file** 
{
  "expo": {
    "name": "Dotogo",
    "slug": "dotogo",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/dotogologo.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/dotogologo.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/dotogologo.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.emrekizilkaya.Dotogo"
    },
    "web": {
      "favicon": "./assets/dotogologo.png"
    },
    "extra": {
      "eas": {
        "projectId": "bec73fde-769b-44d8-a544-d3d46af26a62"
      }
    },
    "owner": "chaosalior"
  }
}

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
      Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.9 => 51.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.1.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/expo/expo/assets/56641245/6d2652f0-6228-41ba-80dc-a37e15cd9ae5

![CleanShot 2024-05-29 at 22 42 50](https://github.com/expo/expo/assets/56641245/f106fa75-75d1-4e1f-b4d9-2ceffb946561)

**Comment by jankamon** [comment]
Have you tried launch APK from fresh clear expo app? If yes and you also have this error that means we have the same issue: https://github.com/expo/expo/issues/29174

**Comment by brentvatne** [comment]
https://docs.expo.dev/build-reference/troubleshooting/

also, we recommend using dev builds for real apps! https://docs.expo.dev/get-started/set-up-your-environment/
