### ISSUE TITLE
[docs] Need to create channel to make update work

### ISSUE THREAD

**Issue by NoriyukiIchijo** [expo/expo#29205]
### Summary

Follow what is written in the page below to demonstrate EAS update.
Even though [this section](https://docs.expo.dev/eas-update/build-locally/#publish-an-update) is completed, no change appears regardless of how many times you close and reopen the app.
This may because no "channel" is made so far despite "main branch" was made.
So, by the command
```
eas channel:create main
```
"main channel" is made and bound to "main branch" by default as described [here](https://docs.expo.dev/eas-update/how-it-works/#matching-updates-and-builds), and the update is applied as expected like a charm.

### Link to the related docs page

https://docs.expo.dev/eas-update/build-locally/

**Comment by wschurman** [comment]
Yep, nice catch. We used to auto-create the channel but I think we switched to only auto-creating channels upon building on EAS, so we should definitely document that one needs to be created manually in this case.
