### ISSUE TITLE
use expo-notifications for device push message 

### ISSUE THREAD

**Issue by Jidahan** [expo/expo#29206]
### Summary

ERROR  TypeError: Cannot read property 'NativeModule' of undefined, js engine: hermes
 LOG  Running "greenhouse" with {"rootTag":501,"initialProps":{}}
 ERROR  Invariant Violation: "greenhouse" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### What platform(s) does this occur on?

Android, iOS

### SDK Version

 "expo": "^51.0.9",     "expo-modules-core": "^1.12.12",     "expo-notifications": "~0.28.4",     "expo-permissions": "^14.4.0",

### Environment

Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.9 => 51.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.7 => 0.72.7 
    Expo Workflow: bare

### Minimal reproducible example

/**
 * Welcome to the main entry point of the app. In this file, we'll
 * be kicking off our app.
 *
 * Most of this file is boilerplate and you shouldn't need to modify
 * it very often. But take some time to look through and understand
 * what is going on here.
 *
 * The app navigation resides in ./app/navigators, so head over there
 * if you're interested in adding screens and navigators.
 */
import 'react-native-gesture-handler';
import React, {useState, useEffect, useRef} from 'react';
import {
  SafeAreaProvider,
  initialWindowMetrics,
} from 'react-native-safe-area-context';
import {initFonts} from './theme/fonts';
import * as storage from './utils/storage';
import {AppNavigator, useNavigationPersistence} from './navigators';
import {RootStore, RootStoreProvider, setupRootStore} from './models';
import {ErrorBoundary} from './screens';
import * as eva from '@eva-design/eva';
import * as Notifications from 'expo-notifications';
import * as Permissions from 'expo-permissions';
import Constants from 'expo-constants';
import {ApplicationProvider, IconRegistry} from '@ui-kitten/components';
import {EvaIconsPack} from '@ui-kitten/eva-icons';
import {
  View,
  Text,
  Image,
  StyleSheet,
  NativeModules,
  Platform,
  Alert,
} from 'react-native';
import {requestBleAuth} from './models/device/ble-auth';
import {useTranslation} from 'react-i18next';
import {saveString, loadString} from './utils/storage';
import Devicelanguage from './utils/device-language';
// This puts screens in a native ViewController or Activity. If you want fully native
// stack navigation, use `createNativeStackNavigator` in place of `createStackNavigator`:
// https://github.com/kmagiera/react-native-screens#using-native-stack-navigator

export const NAVIGATION_PERSISTENCE_KEY = 'NAVIGATION_STATE';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: false,
  }),
});

/**
 * This is the root component of our app.
 */
function App() {
  const {t, i18n} = useTranslation();

  const notificationListener = useRef();
  const responseListener = useRef();
  const [rootStore, setRootStore] = useState<RootStore | undefined>(undefined);
  const {
    initialNavigationState,
    onNavigationStateChange2,
    isRestored: isNavigationStateRestored,
  } = useNavigationPersistence(storage, NAVIGATION_PERSISTENCE_KEY);
  storage.saveString('NAVIGATION_STATE', '');

  // Kick off initial async loading actions, like loading fonts and RootStore
  useEffect(() => {
    (async () => {
      await initFonts(); // expo
      setupRootStore().then(setRootStore);
    })();
    requestBleAuth();
  }, []);

  // 获取本机语言，更改app语言
  useEffect(() => {
    handleRefreshAppLanguge(Devicelanguage);
  }, []);

  useEffect(() => {
    registerForPushNotificationsAsync().then(token => {console.log(token);
    });

    notificationListener.current =
      Notifications.addNotificationReceivedListener(notification => {
        setNotification(notification);
      });
    responseListener.current =
      Notifications.addNotificationResponseReceivedListener(response => {
        console.log(response);
      });
    return () => {
      Notifications.removeNotificationSubscription(
        notificationListener.current,
      );
      Notifications.removeNotificationSubscription(responseListener.current);
    };
  }, []);

  const registerForPushNotificationsAsync = async () => {
    let token;
    if (Constants.isDevice) {
      const {status: existingStatus} = await Permissions.getAsync(
        Permissions.NOTIFICATIONS,
      );

      let finalStatus = existingStatus;
      if (existingStatus !== 'granted') {
        const {status} = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        finalStatus = status;
      }
      if (finalStatus !== 'granted') {
        console.log('Failed to get push token for push notification!');
        return;
      }
      token = (await Notifications.getExpoPushTokenAsync()).data;
      console.log(token);
    } else {
      console.log('Must use physical device for Push Notifications');
    }

    if (Platform.OS === 'android') {
      Notifications.setNotificationChannelAsync('default', {
        name: 'default',
        importance: Notifications.AndroidImportance.MAX,
        vibrationPattern: [0, 250, 250, 250],
        lightColor: '#FF231F7C',
      });
    }

    return token;
  };
 
  // Before we show the app, we have to wait for our state to be ready.
  // In the meantime, don't render anything. This will be the background
  // color set in native by rootView's background color.
  // In iOS: application:didFinishLaunchingWithOptions:
  // In Android: https://stackoverflow.com/a/45838109/204044
  // You can replace with your own loading component if you wish.

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    img: {
      width: '100%',
      height: 132,
    },
    subContainer: {
      height: 200,
      justifyContent: 'center',
      alignItems: 'center',
    },
    text: {
      color: '#cbcbcb',
      fontSize: 10,
    },
  });

  // otherwise, we're ready to render the app
  return (
    <ApplicationProvider {...eva} theme={eva.light}>
      <IconRegistry icons={EvaIconsPack} />
      <RootStoreProvider value={rootStore}>
        <SafeAreaProvider initialMetrics={initialWindowMetrics}>
          <ErrorBoundary catchErrors={'always'}>
            <AppNavigator
              initialState={initialNavigationState}
              onStateChange={onNavigationStateChange2}
            />
          </ErrorBoundary>
        </SafeAreaProvider>
      </RootStoreProvider>
    </ApplicationProvider>
  );
}

export default App;

**Comment by brentvatne** [comment]
https://expo.fyi/no-registered-application
