### ISSUE TITLE
[Expo SDK 51] [Android] [expo-dev-client] - Hot reload not working

### ISSUE THREAD

**Issue by HarunKilic** [expo/expo#29212]
### Summary

Expected behaviour:
- When editing a file, the app should reload

Current behaviour:
- App does not reload when changing basic thing as text. Nor does the metro timeout when stopping the service. 
- Works totally fine if expo is downgraded to SDK 50.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

expo-dev-client: 4.0.15

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.12.2 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0
        Android NDK: 26.1.10909125
    npmPackages:
      expo: ~51.0.9 => 51.0.9 
      expo-router: ~3.5.14 => 3.5.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.0.7
    Expo Workflow: manage

### Reproducible demo

- Install bare project with Expo 51
- Build custom dev using expo-dev-client
- Install on a device
- Start project with `npm start -- --tunnel`
- Connect with mobile device
- See hot reload not working

**Comment by RohovDmytro** [comment]
I can confirm that Hot Reloading is not working when --tunnel is present.

**Comment by RohovDmytro** [comment]
I've found it's related to http vs https.

The workaround is to use http. For example:

````
yarn dlx uri-scheme open "exp+***://expo-development-client/?url=http%3A%2F%****-****-8081.exp.direct" --android
````

**Comment by HarunKilic** [comment]
> I've found it's related to http vs https.
> 
> The workaround is to use http. For example:
> 
> ```
> yarn dlx uri-scheme open "exp+***://expo-development-client/?url=http%3A%2F%****-****-8081.exp.direct" --android
> ```

Its so weird. It didn't work with http for me, neither with https. But it worked suddenly after some time with https. 
Not quite sure how and why it worked. IT in a nutshell I guess.
