### ISSUE TITLE
imagePicker Crashing with Expo 31.0.0 Android 8.1

### ISSUE THREAD

**Issue by nickjuntilla** [expo/expo#2925]
### Environment

  Expo CLI 2.4.1 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.4.0 - ~/.nvm/versions/node/v9.4.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v9.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: 1.5.11 => 1.5.11 
    npmGlobalPackages:
      expo-cli: 2.4.1

The device crashing is a Moto X4 Android 8.1

### Steps to Reproduce

You can try the project here: https://expo.io/@receiptcoin/receiptchain

Taking a photo using the camera doesn't crashes the app.

Here is the code I'm using 
```
async componentDidMount() {
    console.log('camera screen mounted');
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    const cameraRollPermission = await Permissions.askAsync(Permissions.CAMERA_ROLL);
    const status_roll = cameraRollPermission.status;
    console.log('status and status camera is ' , status)
    console.log('status and status roll is ' , status_roll)
    if (status !== 'granted') {
      alert('Please grant app access to the camera so you can upload your photo.');
    }
    if (status_roll !== 'granted') {
      alert('Please grant app access to the camera roll so you can upload your photo.');
    }
    //this.takePhoto();
  }

  takePhoto = async () => {
    console.log('take photo called')
    const pickerResult = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [4, 4],
      exif: true,
    });
    console.log('picker result is ' , pickerResult);
    this.handleImagePicked(pickerResult);
```

Both permissions are granted on the user's moto X4, but the app still crashes upon the ImagePicker.launchCameraAsync call.

**Comment by sjchmiela** [comment]
Hey, @nickjuntilla!

Could you please check if the following Snack crashes on your Moto X4? https://snack.expo.io/@sjchmiela/lonely-cookies

I tried reproducing your issue with the code you provided and I couldn't make the app crash. 😕

**Comment by vknez** [comment]
The same thing happens both in the "lonely-cookies" snack and in my app on Nexus 5X (Android 8.1.0), no matter whether I run my app locally via expo-cli, or publish it to the Expo server. My version of Expo is 31.0.6.

**Comment by nickjuntilla** [comment]
Thanks for helping out. Yes, his phone (MotoX4 Android 8.1) does crash on the snack as well. It crashes right after the cropping happens.

- Open link
- shows camera
- take photo
- shows trash or checkmark icon page, click checkmark
**- App crashes. Opens again white screen then camera**
- Take photo and get trash or checkmark page
- Click check and opens crop page
- click crop and shows Hello there page

Both permissions are granted. The code does work for other versions of android, but I haven't tested any other phones with Android 8.1. I don't have access to any.

**Comment by JegoYann** [comment]
Hello there,
I do reproduce this issue on my app with my Moto G5S plus.

**Comment by sjchmiela** [comment]
Could you please try reproducing this issue on SDK32? The problem may have been fixed in-between. 🙃

**Comment by IntegralTeam** [comment]
We have this problem as well. Any updates?

**Comment by schie** [comment]
having the same issue in an application of mine. We recently update to v32 hoping that it would've fixed the issue, but no dice. Any updates?

**Comment by Latgals** [comment]
Same problem with **launchImageLibraryAsync**. The test was performed on the LG-H324 with Android 5.0 and Meizu M6 with Android 7.0. The code has not been changed and is taken from [https://docs.expo.io/versions/v32.0.0/sdk/imagepicker/](https://docs.expo.io/versions/v32.0.0/sdk/imagepicker/) and from [https://snack.expo.io/](https://snack.expo.io/S19Ge5k2g?session_id=snack-session-2fhTqTazO)
The application is closed and restarted sometimes after editing and cropping a photo, sometimes immediately after selecting a photo.

**Comment by realioseb** [comment]
I've noticed restarting device helps this problem temporarily.
I mean, if app starts crashing on taking picture I restart device and then it works normally for few times

Can It be an insufficient RAM issue?

**Comment by avinashlng1080** [comment]
Guys, do we have an update on this ? The problem persists.

**Comment by jp-agustin** [comment]
Hi, are there any updates on this? I am currently using SDK 33, the app still crashes (cen't even catch the error when using either the **launchImageLibraryAsync** and **launchCameraAsync**. Thank you!

**Comment by jp-agustin** [comment]
Hi, are there any updates on this? I am currently using SDK 33, both permissions are granted, and the app still crashes (can't even catch the error) when using either the launchImageLibraryAsync and launchCameraAsync. Thank you!

Using Android 8.1 by the way.

**Comment by virtualLast** [comment]
Still having this issue using Latest version 9 of android SDK on simulator.

**Comment by thanh90** [comment]
I got this _ImagePicker.launchImageLibraryAsync-TypeError: undefined is not an object (evaluating 'n.ImagePicker.launchImageLibraryAsync')_

**Comment by mujtabaaslam93** [comment]
Any update on this issue?

**Comment by thanh90** [comment]
not sure but after using `expo publish` my app can work

**Comment by oliverkuchies** [comment]
Issue continues to persist for me.

**Comment by danghatam** [comment]
I have the same problem on sdk 33 :(

**Comment by AhmSaeed** [comment]
I have the same problem on sdk 34 with physical Nokia 3.1 and Android 7.1 Nougat.

**Comment by danghatam** [comment]
I don't know reason why, when we use ImagePicker to take a photo, android kills the app for memory issue.
My solution: i only use ImagePicker to pick image, use expo-camera to take picture instead of ImagePicker

**Comment by lukmccall** [comment]
Hi everyone, could someone check if this happens on SDK 35? Today, I've checked Nokia 5.1 and Nexus 5X. Everything worked fine.

**Comment by stephenfairchild** [comment]
I was previously on SDK 34 and was experiencing this issue with the Galaxy S9 simulator. I updated to SDK 35 and everything now seems to work.

**Comment by anan474** [comment]
Same problem on Xiaomi Redmi 6A with android 8.1. I'm using SDK 35 and client version 2.13. Sometime i can take and show the picture but mostly being reloaded without giving error. launchImageLibraryAsync does fine tho.
Any update on this?

**Comment by isocra** [comment]
I have the same problem in both SDK33 and SDK35 on my test Samsung SM-T725. Most of the time `ImagePicker.launchCameraAsync` works fine, but 1 time in 10 or so I get a silent crash and the app reloads. I _think_ it's when I press OK to accept the image, but before any of my code is called because I don't get any logging.

I'm trying to write an app we can provide to our clients so I need it to be robust. Is there likely to be a fix or should I look at ejecting it? Or is Expo just not production ready?

**Comment by SimenB** [comment]
We have a user experiencing what I _think_ is the same issue, although we've been unable to reproduce using a similar device. For the people able to reproduce this, any chance of hooking up adb and providing the stack trace here? Might help the Expo developers track down the issue even if unable to reproduce it

**Comment by isocra** [comment]
@SimenB: after all we think we've tracked it down to being a memory issue. We watched the device logs (using `adb logcat` and filtering on the process id) and tracked the amount of free memory reported by the garbage collector. We saw we had a memory leak and when the memory was very low, trying to take a photo just seemed to push the system over the edge and our app was being killed (hence no error to catch). We think we've identified the memory leak (in our code) and our app seems much more stable now. Fingers crossed!

**Comment by lukmccall** [comment]
I've created [PR](https://github.com/expo/expo/pull/6303) which optimize `ImagePicker`. However, I doubt that will help in this case. 

I'm still struggling with reproducing this bug.
Could someone provide logs from a device?  It will help a lot. 

To do this:
- Enable USB debugging in your device.
- Connect the device to the computer
- Use these commands:
  -  `adb devices` (to get your device id)
  - `adb -s <id> logcat --pid=$(adb shell pidof -s <your package name>)`
 (Expo client package name: `host.exp.exponent`)

**Comment by SimenB** [comment]
@lukmccall I've now gotten a log from the user that is experiencing crashes. Do you have an email address I can forward it to?

**Comment by gesposito** [comment]
I can attach crash logs as well (see #7946)

**Comment by lukmccall** [comment]
@SimenB, please post them using `gist` or something like this ;) And do it under https://github.com/expo/expo/issues/7946.
