### ISSUE TITLE
Navigating to a shared route doesn't stay within the current group

### ISSUE THREAD

**Issue by abmenzel** [expo/expo#29273]
### Minimal reproducible example

https://github.com/abmenzel/shared-routes

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I'm trying to set up tabs navigation, where each tab has a nested stack navigator. These will include shared routes that should be accessible from each tab, settings, user etc.
I've following the documentation on [Shared Routes](https://docs.expo.dev/router/advanced/shared-routes/).

#### Setup:
I've used `npx create-expo-app@latest`, then setup the following file-routing structure:

```
(tabs)
-- (home)
---- _layout.tsx
---- index.tsx
---- shared.tsx
-- (profile)
---- _layout.tsx
---- index.tsx
---- shared.tsx
-- _layout.tsx
_layout.tsx
```

From `(home)/index.tsx` and `(profile)/index.tsx` i've set up a `<Link href="/shared">` to navigate to the shared route.

#### Expectation:
When inside a stack navigator (home) or (profile) nested inside (tabs) I expect the links to the shared route to remain in the same stack navigator (home) or (profile).

#### Behaviour:
When on the `(profile)/index` route, clicking the `<Link>` takes you to `(home)/shared.tsx` instead of `(profile)/shared.tsx`.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.9 => 51.0.9
      expo-router: ~3.5.14 => 3.5.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 5.9.0
    Expo Workflow: managed

**Comment by evelant** [comment]
I think I'm also seeing this. Just started trying to add routing to my app with expo router v3. When I use the array syntax for a shared route such as `/src/app/(root)/(foo,bar,baz)/profile/[userId].tsx` it appears that expo router only picks up the _first alphabetical_ member for the shared route, `bar` in this case. If I inspect the routes at `(root)` I only see `(bar)/profile/[userId]` -- `(foo)/profile/[userId]` and `(baz)/profile/[userId]` are missing. @marklawlor I suspect there's a bug wherever shared routes get enumerated such that expo router only picks up the first one by alphabetical order and ignores the rest.

**Comment by evelant** [comment]
This looks like a likely place where a bug might have crept in https://github.com/expo/expo/pull/29232/

**Comment by evelant** [comment]
I've figured out a workaround but I'm still unsure about the root of the problem. If I ensure that I have defined every route (via `<Stack.Screen`) instead of allowing some of them to be picked up by filesystem path everything works correctly. When I allow any routes to be picked up by filesystem path without defining a `<Stack.Screen name=` the router state appears to get all messed up. I'm not sure if this is a bug or just a documentation issue -- I've carefully read the expo router and react navigation docs several times and they're not very clear about the effects of defining screens vs picking them up from the filesystem.

**Comment by evelant** [comment]
Scratch that, not a workaround. It still always seems to navigate to the first alphabetical match for a shared route defined with array syntax. For example with `/app/(root)/(gameheader,dialogs)/profile/[id].tsx` if I am on `/app/(root)/(gameheader)/foo` and do ```route.push(`profile/${id}`)``` I end up at the route `/app/(root)/(dialogs)/profile/[id]`. @marklawlor any ideas about how this might happen?

**Comment by saulamsal** [comment]
Any feedback on this? It keeps landing on the index.tsx (home) tab when I click on other tabs. Expo 49 works fine, though. It seems to be an issue with Expo 51.
<img width="461" alt="image" src="https://github.com/user-attachments/assets/c16d0e6c-0b75-4c8d-a523-9802484f767b">
