### ISSUE TITLE
npm version issue on XDE

### ISSUE THREAD

**Issue by jalalat** [expo/expo#293]
When i try to run the app using XDE (latest upgrade to 2.19.0):

Error: You are using npm version 5.0.1. Please use an npm version that is >= 3.0.0 and < 5.0.0

**Comment by btroia** [comment]
Yes, I also got this message. From @brentvatne 's blog post:

> **Added validation for npm version because npm 5 is currently unstable and often does not work well with Expo projects.** Since npm 5 was released and was installed automatically with Node 8, Expo users have run into a lot of problems with it, so we now automatically suggest to users that they install npm 4 instead.

Running:

`npm install -g npm@1.4.3`

solved it for me.

**Comment by dikaiosune** [comment]
2.19.2 of XDE turned this into a warning rather than an error. That said, we can't support npm 5 yet so you should make sure that your project is set up with npm 4 or yarn for the time being. Thanks!

**Comment by mixelpixel** [comment]
Hello, I tried `npm install npm@4.6.1` within the RN project directory. The package.json file was updated but after running `npm i` I still get 5.3.0 returned from a `npm --version` query and Expo XDE still gives me the warning to use npm4.6.1.

I can't revert to 4.6.1 globally, so how do I specify the the 4.6.1 version for just the RN project and Expo?

Thank you

**Comment by ide** [comment]
The simplest approach is probably just to use Yarn.

You also could use nvm which lets you install different versions of Node, then downgrade npm just for that one version of Node, and use something like direnv+.envrc to automatically switch to that version of Node+npm when you're inside your Expo project directory.

**Comment by mixelpixel** [comment]
Thank you @ide 😄 

I pretty new to RN/npm/node/nvm/yarn but I think I can figure out how to implement your suggestion. I really appreciate the quick response and am looking fwd to working with these incredible tools!

**Comment by mixelpixel** [comment]
ah! just found this: https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352

**Comment by ryanhomer** [comment]
I am using nvm and running node 7.6.0 with npm 4.6.1 but Expo keeps giving me the warning about 5.4.2. Any idea why?

If I switch to yarn, how would I tell Expo to stop checking the npm version?

**Comment by ide** [comment]
You might need to run `nvm alias default 7` (or whatever version you want to use) to make `nvm` set up Node 7.x to be the default when you launch a shell. Expo will run your .bashrc, .bash_profile, etc. so make sure you also have nvm's config scripts in there as well (nvm tells you what to do when you set it up, I think their docs also might tell you what to put in your shell rc).

**Comment by ryanhomer** [comment]
Thanks @ide. I did have 7 set as the alias default. I'll go over my scripts as you have suggested and see if that helps.
