### ISSUE TITLE
Expo Camera (v51): When recording, switching from front facing to back facing gives "Video recording Failed: Unknown error"

### ISSUE THREAD

**Issue by jvgeee** [expo/expo#29367]
### Minimal reproducible example

https://github.com/jvgeee/expo-camera-bugs

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When using Expo V51's `<CameraView mode="video" facing={facing} />` to record a video, if you switch `facing` from `"front"` to `"back"` (or the other way around), recording stops and it gives this vague error:

`LOG  Recording error: [Error: Video recording Failed: Unknown error]`

NB this is with `"expo-camera": "^15.0.10"`

### Environment
```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.12.2/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.9 => 51.0.9
      expo-router: ~3.5.14 => 3.5.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 9.0.8
    Expo Workflow: managed
```
### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by davidhdpro** [comment]
@alanjhughes Please look at this too 

packages installed:
    "expo": "~51.0.12",
    "expo-camera": "~15.0.10",

I can confirm that on iOS both Pictures and Video landscape are fixed!
However on Android Picture orientation is fixed, but video orientation for landscape still returns portrait (-90 deg)

when calling

vid = await cameraRef.current.recordAsync({
maxDuration: 120
});

On android video recording stops immediately (workaround is to set maxDuration: 120000)
a) On ios it is working as expected according documentation (120 second)
b) On android duration must be set in milliseconds to make it work (120000 millisecond)

On android pictureSize prop is ignored when calling takePictureAsync():
When getting available picture sizes with getAvailablePictureSizesAsync() then setting one of the stings to pictureSize
prop it is being ignored.

<CameraView
...
pictureSize = {"1920x1080"} // <- This prop is ignored when taking pictures
...
/>

Tested on stand alone production apk as well as development client apk, iOS via testFlight

**Comment by alanjhughes** [comment]
@davidhdpro please stop commenting on other issues and PRs. If you have an issue you would like investigated, open a new issue with a minimal example.

**Comment by jvgeee** [comment]
Update: I can see that Expo has (recently?) added this line into [the Camera docs](https://docs.expo.dev/versions/latest/sdk/camera/#recordasyncoptions):

`Flipping camera during a recording results in stopping it.`

I wasn't able to find _any_ information about this when trying to implement it or debug the error returned from Expo Camera, so this issue might be the only discussion about it. If you're like me and require the ability to flip during recording, try [React Native Vision Camera](https://github.com/mrousavy/react-native-vision-camera). 

According to [this issue](https://github.com/mrousavy/react-native-vision-camera/issues/1805) it supports flipping from front <=> back cameras during recording, although I haven't implemented it yet to verify.

**Comment by alanjhughes** [comment]
Hi @jvgeee I'll be investigating adding support for this. The reason it's not there now is the new package uses CameraX on Android instead of Camera2 and this use case was not supported until recently.

**Comment by jvgeee** [comment]
@alanjhughes That would be amazing if you can, it's a requirement for the app I'm working on and a standard feature in a lot of camera-based apps so I'd love to keep using Expo Camera for it.

**Comment by pratik-cognologix** [comment]
> @alanjhughes That would be amazing if you can, it's a requirement for the app I'm working on and a standard feature in a lot of camera-based apps so I'd love to keep using Expo Camera for it.

This is very standard functionality and this bug supposed to fix on priority. Why no one is looking into this?
@jvgeee @alanjhughes Is there any other forum that we can raise this?
