### ISSUE TITLE
Couldn't find Android manifest at /home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml

### ISSUE THREAD

**Issue by ellowwwteam** [expo/expo#29368]
We try the npx expo prebuild "expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" added on AndroidManifest.xml. 

I'm trying to crate the production build following error return

**Added Code On AndroidManifest.xml**
`<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-channel-name&quot;:&quot;production&quot;}"/>`

**Error:**
Setting the update request headers in 'AndroidManifest.xml' to '{"expo-channel-name":"production"}'
Couldn't find Android manifest at /home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml

_Originally posted by @ellowwwteam in https://github.com/expo/expo/issues/21111#issuecomment-2135120489_

**Comment by brentvatne** [comment]
hi there! try running `npx expo prebuild --clean`. you may have an invalid `android` directory

**Comment by ellowwwteam** [comment]
@brentvatne 
I tried the npx expo prebuild --clean. But, still same error at the time of creating production build. Please check the screenshot.

![image](https://github.com/expo/expo/assets/96511857/4a6e5ede-8e8c-4f91-bd75-79c77943b0de)

![image](https://github.com/expo/expo/assets/96511857/27c1afe5-d51f-42c7-af7c-330397907b53)
