### ISSUE TITLE
React Nav / Dev tools (?): undefined is not function (near '...(0,reactNavigation.TabNavigator)...')

### ISSUE THREAD

**Issue by xiaochao** [expo/expo#2938]
![image](https://user-images.githubusercontent.com/1953662/49638429-1365ed80-fa43-11e8-94ad-57da6205ec84.png)

Platform: Mac 
Node:v10.12.0
packege.json
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "556": "^1.0.0",
    "react": "16.6.1",
    "react-devtools": "^3.4.3",
    "react-native": "0.57.7",
    "react-native-lahk-marquee-label": "^1.1.4",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-swiper": "^1.5.14",
    "react-navigation": "^3.0.6",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.7"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.50.0",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

the code i used:

https://www.reactnavigation.org.cn/docs/tabnavigator

**Comment by brentvatne** [comment]
that doc is out of date, I recommend reading the chinese version of the official react-navigation docs: https://reactnavigation.org/docs/zh-Hans/tab-based-navigation.html
