### ISSUE TITLE
Unable to get it work after update (SDK 18)

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#294]
Hi guys, today update the expo sdk to 18 and unable to get it work ... someone else with the same problem ?

<img width="733" alt="screen shot 2017-06-23 at 12 18 17 pm" src="https://user-images.githubusercontent.com/140472/27488667-36e1226c-580e-11e7-96b9-a99b0e6f880c.png">

**Comment by brentvatne** [comment]
can you paste your exp.json (or app.json) and package.json?

**Comment by outaTiME** [comment]
yup, here are:

package.json
```
{
  "name": "skillcase",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "main.js",
  "dependencies": {
    "expo": "^18.0.2",
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-native-elements": "^0.13.0",
    "react-native-elevated-view": "0.0.4",
    "react-native-smart-corner-label": "^1.1.2"
  }
}
```

app.json

```
{
  "expo": {
    "name": "skillcase",
    "description": "An empty new project",
    "slug": "skillcase",
    "privacy": "public",
    "sdkVersion": "18.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true
    }
  }
}
```

**Comment by sriram-dev** [comment]
I have had the same problem. I deleted node_modules , ran npm install and  did a npm start -- --reset-cache and it went away. Now I have a different issue. When app loads and i get this error in console.

>  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'this[a]["@@" + t]')
U@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:51090:62
http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:61103:41
arrayFilter@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:58146:20
http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:61102:25
http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:61110:37
baseGetAllKeys@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:59342:70
getAllKeysIn@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:61021:28
pickBy@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:63095:40
getConcreteStyle@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:100147:18
getFinalStyle@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:100209:34
Styled(Text)@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:100185:45
http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:25782:31
measureLifeCyclePerf@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:25602:14
_constructComponentWithoutOwner@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:25781:36
_constructComponent@http://172.16.0.2:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&mi

**Comment by outaTiME** [comment]
The `npm start -- --reset-cache` command doesn't work for me, in which path you run this? btw, im create a new expo project from scratch and works i really understand why the old project fails, im remove `node_modules`, i downgrade npm@5 to 4.6.1, i use yarn a nothing

**Comment by brentvatne** [comment]
@outaTiME - use `exp start -c` or press the "Restart" button in XDE to clear the cache

**Comment by outaTiME** [comment]
@brentvatne yup, i perform both operations and nothing same error its really strange

**Comment by yellowspaceboots** [comment]
I am also getting the same `Possible Unhandled Promise Rejection (id: 0):` that @sriram-dev mentions above.

**Comment by yellowspaceboots** [comment]
Hey just so yo guys know. I new version of XDE must have been released today as I was prompted to update when i restarted XDE. This update solved my issue. Thanks!

**Comment by sriram-dev** [comment]
I can confirm that my issues were due to another library i was using "native-base". It was breaking after i updated to SDK 18 in expo.

**Comment by dikaiosune** [comment]
This has been raised a few times, so I'm giving this a close. However, if you're seeing this, make sure to:

* remove node_modules entirely (`rm -rf node_modules`)
* stop watchman (`watchman watch-del-all` and `watchman shutdown-server`)
* delete the entire packager temp directory (`rm -rf $TMPDIR/react-*`)
* install your dependencies again (`yarn` or `npm i`)
* start your project again
