### ISSUE TITLE
Statusbar , Android: when backgroundcolor is added in app.json, a margin to every view is added too

### ISSUE THREAD

**Issue by giacomocerquone** [expo/expo#2940]
### Environment

```
  Expo CLI 2.6.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Users\Giacomo\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

My app target is Android and iOS

### Steps to Reproduce

I think we should shed some light on the differences when using the combination of the available APIs to handle the android statusbar.

I'm opening an issue that might be a documentation issue or a tecnical one.
What I want is just to add a precise background color to the android statusbar and I'm trying to do it in my app.json file.
The point is that I'm using react navigation too in my project and putting navigators here and there, set automatically the top margin in order to let the status bar not overlap the view.

Now the problem is that adding the background color in app.json, seems to double the margin, but nothing is said about this in the doc. Is this a correct behaviour? And if so, how can I JUST change the color of the statusbar without adding more margin?

1. Use react-navigation stack navigator on a component
2. Set the backgroundcolor of the statusbar inside app.json
3. Watch the doubled margin

### Expected Behavior

I thougth that just the backgroundColor would be changed.

### Actual Behavior

The margin has doubled

### Reproducible Demo

I set up this snack with react navigation https://snack.expo.io/@giacomocerquone/statusbar-doubled-margin
But I don't know how to edit the app.json on snack, maybe we just can't.

UPDATE: 

Adding just the statusbar component doesn't work, but adding first this in the app.json:

```
    "androidStatusBar": {
      "backgroundColor": "#ffffff",
      "barStyle": "dark-content"
    }
```

And then putting the statusbar in a render method of whichever component, the last is applied (and this should be documented) and the margin removed:

```
      <StatusBar
        backgroundColor="#ffffff"
        barStyle="dark-content"
        translucent
      />
```

Too much confusion. This stuff shouldn't only be documented, but fixed I believe... there are too much api overlapping

**Comment by quinlanj** [comment]
hi @giacomocerquone , i am trying to reproduce this on the android pixel but am having trouble.

i followed your instructions and made a new project using expo-cli, except i changed the color to #ff0000 (red) which is easier to see where the status bar is compared to #ffffff (white) in `App.js`. Here is what I got:

![dkueuou](https://user-images.githubusercontent.com/6380927/49695017-3a0e4c00-fb49-11e8-82c9-30d682c117d5.png)

The margin looks normal in the screenshot above. Could you elaborate more about the doubled margin you are seeing (with a screenshot) or let us know more about your test env (ie) what device you are using?

**Comment by brentvatne** [comment]
what is happening here is that setting the background color of the status bar changes it from translucent to opaque. translucent is default and it makes it so content is rendered underneath the status bar. opaque forces content to be rendered below the status bar.

there is no good api built into react-native for determining whether the status bar is translucent or opaque on android and so i just assume that if someone is using react-navigation with expo that they are using translucent. if you are using an opaque status bar with react-navigation, you need to do this:

```
import { SafeAreaView } from 'react-navigation';
import { Platform } from 'react-native';

if (Platform.OS === 'android') {
  SafeAreaView.setStatusBarHeight(0);
}
```

I'm waiting for this to land upstream and then we can handle this case automatically: https://github.com/facebook/react-native/pull/20999

**Comment by giacomocerquone** [comment]
Thank you very much brent for your clarifications. Thumb up for that PR, hoping to see it anytime soon :)
