### ISSUE TITLE
Android resource linking failed ERROR: /home/expo/workingdir/build/android/app/src/main/res/drawable/splashscreen.xml resource color/splashscreen_background (aka appname/splashscreen_background) not found.

### ISSUE THREAD

**Issue by gabrielbaldeon** [expo/expo#29413]
### Minimal reproducible example

not able to do this

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

When I run eas build --platform android --profile preview 
The build fails and I got:
Android resource linking failed ERROR: /home/expo/workingdir/build/android/app/src/main/res/drawable/splashscreen.xml resource color/splashscreen_background (aka appname/splashscreen_background) not found.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 22.1.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^51.0.0 => 51.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.6 => 0.19.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by CaiJingLong** [comment]
The problem is exists.

Looks like the template of android:

We just add code`<color name="splashscreen_background">#ffffff</color>` to `android/app/src/main/res/values/colors.xml` file.
