### ISSUE TITLE
[Android] Video Player does not load Videos in Playlist (but works on iOS)

### ISSUE THREAD

**Issue by natterstefan** [expo/expo#2941]
### Continuing

- https://github.com/expo/expo/issues/2028
- and https://github.com/expo/expo/issues/958

### Environment

```
  Expo CLI 2.3.5 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 31.0.6 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.3.5
```

App's target (iOS, Android, Client, Standalone, ExpoKit)

- iOS
- Android

### Steps to Reproduce

We have prepared a demo based on the playlist example from expo. Note, we updated the source to the [SDK `"sdkVersion": "31.0.0",` version](https://github.com/expo/expo/blob/master/CHANGELOG.md#3100--partial-changelog).

You can clone it here https://github.com/natterstefan/playlist-example (`git clone git@github.com:natterstefan/playlist-example.git`) and check out the prepared example branch: `git checkout example/android-video-bug`.

FYI, the video file is always the same. We installed a proxy. It points to the same video source, but allows different urls.

Steps to reproduce:

1. Now start the app with `npm start`
2. Open it in Android
3. and play (at least start) video after video.
4. take a look at the console.logs, as at one point the last log will be `ON LOAD START` and the VideoPlayer is just gone and won't react. If the video works `ONLOAD` would be logged.

We also tried uncommenting 

```
// // UNCOMMENT THIS TO TEST THE OLD androidImplementation:
// androidImplementation: 'MediaPlayer',
```

as suggested [here](https://github.com/expo/expo/issues/2028#issuecomment-407885365) but it did not help. The video did not play at all then.

### Expected Behavior

As we are working on a similar use case in our app (playlist like feature) we would expect Android to be capable of playing n videos in the list, similar to iOS. But instead, it "stops/breaks" after a random number of videos played.

### Actual Behavior

As described, the Player just disappears, meaning the user sees the app's background. We were also not capable of catching an error, to try it again. Just check out the example provided above please.

What we discovered so far

- it is not related to the video source url. We tried Vimeo and our own domain/urls.
- it is not related to our tested video files. We tried different videos.
- on iOS there seems not issue at all, also mentioned here https://github.com/expo/expo/issues/2028#issue-344415833. 
- in the example `unloadAsync` and `loadAsync` is used and in our own project as of now we just render the `<Video />` component with the `source` prop. (eg. `source={{uri: videoUrl}}`. Both ways ran into the same issue. :/
- there was no difference in running the Android app with the debugger tools on the local machine (with expo-cli) _or_ in production mode after publishing it on expo (with expo publish).

I stumbled upon https://github.com/expo/expo/issues/2691 as well, but I am not sure yet if this is related. Because he said in the issue

> The APP component gets stuck on await this._video.loadAsync(source, initialStatus); for ever and doesn't run the other functions,

Maybe it is related and helps finding a solution for both issues.

#### Screenshots

This is what the log says. As you can see at the bottom it stops and does not properly continue.

![image](https://user-images.githubusercontent.com/1043668/49684958-9fc3ef00-fadb-11e8-99d5-062a1d2fc34d.png)

This is what we see in the app then, the player is just gone:

![image](https://user-images.githubusercontent.com/1043668/49684984-eade0200-fadb-11e8-9136-bee83973bb0d.png)

Device Details

![image](https://user-images.githubusercontent.com/1043668/49685013-6049d280-fadc-11e8-84e9-eef355ff3453.png)

### Reproducible Demo

- https://github.com/natterstefan/playlist-example
- check out the prepared example branch: `git checkout example/android-video-bug`
- FYI, the video file is always the same. We installed a proxy. It points to the same video source, but allows different urls.

## NOTE

We also had issues, if we did not wrap [this part of the code in the playlist example](https://github.com/natterstefan/playlist-example/blob/496097a0304e7d05061dc09ee0834c18ebd51a76/App.js#L324-L338) with the if statement:

```js
this.playbackInstance.setOnPlaybackStatusUpdate(null);

// ... some stuff in between

this._video.setOnPlaybackStatusUpdate(this._onPlaybackStatusUpdate);
```

In both cases `this._video` and `this.playbackInstance` is undefined. Not sure what this is and if it is related. Because `this._onPlaybackStatusUpdate` still works though.

Please keep in mind, that the urls provided above for the demo videos will not stay online forever. Maybe we'll remove it when the issue is resolved. Thank you.

**Comment by chris35469** [comment]
Any update on this? I am running into the exact same issue.

**Comment by sftgf** [comment]
I'm facing the same issue, would even be happy with any sort of workaround for this.

**Comment by natterstefan** [comment]
Hi @sjchmiela, I assume you have lots of tasks to check off because of the latest release (docs etc.), but I wanted to check in quickly if you had time to take a look at this issue.

We are stuck and do not know how to proceed with Android right now. Please, let me know how I can be of help.

Thank you for your great work! 👍

**Comment by sjchmiela** [comment]
Hey all, sorry for being not responsive… I haven't had time yet to look into this. I guess the underlying cause may be some ignored native exception, sorry. 😕 We'll come back to fix it as soon as we're able to!

**Comment by gsunsnackv** [comment]
We are facing the same painful issue. After couple videos, the player stops working forever. I was able to made a repo easily as well Code: https://github.com/gsunsnackv/expo-video-load-async-stuck Snack: https://snack.expo.io/SJkdW-gm4

I'd like to share some of my observations. It seems that Android 9 can play a few more videos compare to older versions. But the whole thing is very random, it is not clear. Another thing is that if you use `androidImplementation: 'MediaPlayer'`, then older versions works very good, almost can play forever, but with that, Android 9 will fail a lot more, most time cannot even load the first video.

Code for `androidImplementation: 'MediaPlayer'` https://github.com/gsunsnackv/expo-video-load-async-stuck/tree/use-media-play-works-for-older-android Snack: https://snack.expo.io/S16nzbxQV
I hope this may help hunt down the problem

**Comment by gsunsnackv** [comment]
We also tried to not use loadAsync but use the uri property on video. We set a different key on the component each time to cause the old component to unmount and create a new one. And we let the uir property load the video. We also manually unload the video when component get unmount. Nothing works. https://github.com/gsunsnackv/expo-video-load-async-stuck/tree/unmount-everytime

**Comment by gsunsnackv** [comment]
@sjchmiela Any updates? This is killing us. Please help
We also tried to have our own timeout and check the video status after a few seconds. If it got stuck, we try to unload and reload the video. It does not work. Code https://github.com/gsunsnackv/expo-video-load-async-stuck/tree/reload-after-timeout

We noticed from the status that playableDurationMillis is 0 .

```
[14:59:30] Object {
[14:59:30]   "androidImplementation": "SimpleExoPlayer",
[14:59:30]   "didJustFinish": false,
[14:59:30]   "durationMillis": 1,
[14:59:30]   "isBuffering": true,
[14:59:30]   "isLoaded": true,
[14:59:30]   "isLooping": false,
[14:59:30]   "isMuted": false,
[14:59:30]   "isPlaying": false,
[14:59:30]   "playableDurationMillis": 0,
[14:59:30]   "positionMillis": 0,
[14:59:30]   "progressUpdateIntervalMillis": 500,
[14:59:30]   "rate": 1,
[14:59:30]   "shouldCorrectPitch": false,
[14:59:30]   "shouldPlay": true,
[14:59:30]   "uri": "/5d1b000b0154f68c982de394cb32908a_video-file.mp4",
[14:59:30]   "volume": 1,
[14:59:30] }
```

**Comment by gsunsnackv** [comment]
We also tried to remount the whole component. Not working either. Basically SimpleExoPlayer entered a stuck status that is just not recoverable. https://github.com/gsunsnackv/expo-video-load-async-stuck/tree/remount-if-not-playing

**Comment by mg-cj** [comment]
We have facing exactly the same issue as loadasyc failed after 3 rounds. Any response or guide to fix will be great!

**Comment by thekrol01** [comment]
I have a similar experience when loading video 's in a flatlist. All works fine on IOS. On Android however the video 's only load when i navigate to the screen with the flatlist for the first time after login. When I leave the screen and come back again the video 's are black.

**Comment by yanagassi** [comment]
Hello, we are not able to run a video on android, only on IOS. We are very dissatisfied because we chose the exhibition because of the confidence we have. We have a project stuck in its execution because of a flaw.

` <Video 
                    source={{uri: this.state.currentSource}}
                    rate={this.state.fastLearn}
                    volume={1.0}
                    isMuted={false}
                    useNativeControls={false} 
                    onPlaybackStatusUpdate={this.setProgress.bind(this)} 
                    onLoad={this.setDuration.bind(this)}
                    ref={(ref)=>this.player = ref}
                    style={StyleSheet.absoluteFill} />
`

**Comment by gsunsnackv** [comment]
@sjchmiela Even if you cannot fix this immediately, can you join the conversation and tell us what do you think is happening? Could there be a workaround?

**Comment by sjchmiela** [comment]
Hey all, sorry, I wasn't able to get to this problem recently. In the past such problem was occurring due to leaking of `SimpleExoPlayer` instances, which at that time was fixed. Maybe the issue came back, I can't tell anything without debugging. If the regular `unloadAsync`/unmounting don't work, I don't think there is any workaround, unfortunately. 🙁

**Comment by tomburg188** [comment]
@sjchmiela can you start debugging please? 
We have a a couple thousand app users and have recently lost about 400 b/c of this issue. Your help is much appreciated!

**Comment by gsunsnackv** [comment]
We tried to workaround it by eject the app and use react-native-video directly. But that workaround is also stuck because of https://github.com/expo/expo/issues/2941 . For some reason expo want to use its own expolib_v1.okhttp3 library that is causing many many conflicts with other project.

**Comment by thekrol01** [comment]
Perhaps the only solution for now is to create a react native project from scratch and use react native modules only. We are also stuck with the video en camera Expo components because Android behaviour is totally different (does not work correctly) then IOS behaviour.

**Comment by thekrol01** [comment]
@gsunsnackv we are experiencing the same issue. If you have any any updates on this subject can you please let us know. Meanwhile we are also trying to find a workaround for this.

**Comment by Szymon20000** [comment]
@natterstefan 
I tried to reproduce the issue on Android 6.0.1 and 8.0 but I couldn’t. I played 10 videos on both and nothing happened. I used your repo. Do I need to do any specific actions in order to reproduce the issue?

**Comment by natterstefan** [comment]
Hi @Szymon20000, I need to test it again with my friend (he was the one with the Android phone during our tests with the mentioned repo). As far as I remember the error did not occur in a certain pattern. Sometimes he was able to load 20+ videos and sometimes it failed after 6 or 8. I'll ask him again to check out the repo and test it again. Where you able to run into the error after 10+ videos?

**Comment by gsunsnackv** [comment]
@Szymon20000 For me it happens consistently on Android 9.0

**Comment by gsunsnackv** [comment]
Just corrected the link in my previous post. The workaround was stuck because of https://github.com/expo/expo/issues/2298

**Comment by gsunsnackv** [comment]
I ejected my app and run it from Android Studio, after the player got stuck, I waited a long time and got the following logs. However I do not understand them
```
I/ReactNativeJS: componentDidUpdate loadasync called
I/ExoPlayerImpl: Init a3342a0 [ExoPlayerLib/2.6.1] [generic_x86, Android SDK built for x86, Google, 28]
D/ScopedContext: WARNING: getPackageName called on ScopedContext
V/StudioProfiler: Transformed class: android/app/job/JobService
V/StudioProfiler: Transformed class: android/app/AlarmManager
V/StudioProfiler: Transformed class: android/location/LocationManager
V/StudioProfiler: Transformed class: android/app/IntentService
V/StudioProfiler: Transformed class: android/app/job/JobServiceEngine$JobHandler
V/StudioProfiler: Transformed class: android/location/LocationManager$ListenerTransport
V/StudioProfiler: Transformed class: android/app/JobSchedulerImpl
V/StudioProfiler: Transformed class: android/app/AlarmManager$ListenerWrapper
V/StudioProfiler: Transformed class: android/os/PowerManager
V/StudioProfiler: Transformed class: android/os/PowerManager$WakeLock
V/StudioProfiler: Transformed class: android/app/PendingIntent
V/StudioProfiler: Transformed class: android/os/Debug
V/StudioProfiler: Transformed class: android/app/ActivityThread
V/StudioProfiler: Transformed class: android/app/Instrumentation
V/StudioProfiler: Transformed class: java/net/URL
V/StudioProfiler: Transformed class: android/support/v4/app/Fragment
V/StudioProfiler: Transformed class: okhttp3/OkHttpClient
W/v.snack.androi: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
I/chatty: uid=10098(com.snackv.snack.android) identical 15 lines
W/v.snack.androi: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
W/v.snack.androi: Class android.os.PowerManager$WakeLock failed lock verification and will run slower.
    Common causes for lock verification issues are non-optimized dex code
    and incorrect proguard optimizations.
V/StudioProfiler: JNIEnv not attached
I/Choreographer: Skipped 326 frames!  The application may be doing too much work on its main thread.
V/StudioProfiler: Memory control stream started.
V/StudioProfiler: Perfa connected to Perfd.
V/StudioProfiler: Acquiring Application for Events
V/StudioProfiler: Live memory tracking disabled.
V/StudioProfiler: Live memory tracking enabled.
    JNIEnv not attached
V/StudioProfiler: Loaded classes: 16204
V/StudioProfiler: New JNI table set
V/StudioProfiler: Tracking initialization took: 1921998000ns
I/v.snack.androi: Background concurrent copying GC freed 63586(3MB) AllocSpace objects, 0(0B) LOS objects, 29% free, 14MB/20MB, paused 699us total 224.006ms
I/ExoPlayerImpl: Release a3342a0 [ExoPlayerLib/2.6.1] [generic_x86, Android SDK built for x86, Google, 28] [goog.exo.core, goog.exo.okhttp]
I/ReactNativeJS: componentDidUpdate loadasync failed
I/ReactNativeJS: { [Error: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: expolib_v1.okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR]
      line: 3212,
      column: 26,
      sourceURL: 'http://10.11.106.209:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fgordon%2Fworkspace%2Fsnackv%2Freact-native%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js',
      framesToPop: 1,
      code: 'E_VIDEO_NOTCREATED' }
```

**Comment by gsunsnackv** [comment]
@sjchmiela Please have a look at my comment above. Is there a workaround, some android configurations maybe to reduce the time that the error throws from 5 minute 30 seconds to something much shorter? Then we can catch it and retry.

**Comment by tomburg188** [comment]
Is there any news or an estimate when this issue might be tackled? This is getting awfully painful for us

**Comment by gsunsnackv** [comment]
@tomburg188 We had to abandon Expo and use pure react native

**Comment by tomburg188** [comment]
@sjchmiela any news on this? else we'll be forced to abandon alike

**Comment by gsunsnackv** [comment]
@tomburg188 How painful the abandon process is depends on how many Expo things you are using. We found the most painful part was the FB and Google login

**Comment by danhixon** [comment]
This bug is affecting my product as well. (Upvoting)

**Comment by Hannibal2** [comment]
Is there any updates here? This bug is affecting my product as well(

**Comment by sjchmiela** [comment]
@Szymon20000 is working on a fix — https://github.com/expo/expo/pull/3539 (ExoPlayer upgrade). 🙂

**Comment by natterstefan** [comment]
Thank you @sjchmiela! Awesome news!
