### ISSUE TITLE
Not able to run npx expo run:android

### ISSUE THREAD

**Issue by sammingasainath** [expo/expo#29414]
### Summary

I am trying to run my expo app on my android emulator/ android device ( connected with usb debuggin on ) but I am unable to run ,
The error that occurs reptitively is : 'Error: The system cannot find the path specified.
Error: The system cannot find the path specified.
    at notFoundError (F:\React_Native_Projects\my-app\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (F:\React_Native_Projects\my-app\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (F:\React_Native_Projects\my-app\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
PS F:\React_Native_Projects\my-app> npx expo-env-info'

![image](https://github.com/expo/expo/assets/105980835/86e41756-b761-4dbf-b260-a50f00d73073)

### What platform(s) does this occur on?

Android

### SDK Version

50

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11255304
    npmPackages:
      expo: ^50.0.19 => 50.0.19
      expo-router: ~3.5.14 => 3.5.15
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/sammingasainath/testrepo.git

**Comment by Kudo** [comment]
hi there!
please refer to https://docs.expo.dev/get-started/set-up-your-environment/?platform=android&device=simulated&mode=development-build and makes sure you have the `ANDROID_HOME` environment variable setup to your system.
