### ISSUE TITLE
UPGRADE EXPO-CLI and GET THIS ERROR

### ISSUE THREAD

**Issue by abdymm** [expo/expo#2942]
after i upgrade to EXPO-CLI 2.6.8 i got this error when i execute npm start or expo start 

![yrhfbdq](https://user-images.githubusercontent.com/1695466/49693577-678ae200-fba9-11e8-89b1-f24d571ec7e3.png)

now i just revert  my EXPO-CLI version to 2.1.3, and its work

what should i do? i want upgrade my expo-cli, any solution?

this is my env
```
Environment:
  OS: macOS 10.14
  Node: 8.9.4
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  expo: ^31.0.6 => 31.0.6
  react: 16.5.0 => 16.5.0
  react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
```

**Comment by ccheever** [comment]
What is the error?

**Comment by abdymm** [comment]
sorry @ccheever , i forgot upload the error, this is the error
![yrhfbdq](https://user-images.githubusercontent.com/1695466/49693583-7b364880-fba9-11e8-8572-1f3bee5a4d60.png)

**Comment by quinlanj** [comment]
@abdymm from the error message, it looks like you've not run `npm install` yet. what happens when you run `npm install` and then `expo start`?

**Comment by RinaldoC** [comment]
Same problem here, also with new project: i uninstall expo-cli, react-native, re-installed, create new blank project (expo init my-new-project) and always "Error: React Native is not installed. Please run `npm install` in your project directory." (also after "npm install" inside project dir)

Expo CLI 2.6.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.6.8

**Comment by RinaldoC** [comment]
Other info: after global uninstall react-native e re-install this packege, now i get this new error
"Cannot find module 'expo/tools/LogReporter'"

**Comment by Johnsonzhangc** [comment]
@quinlanj it's more like an expo-cli problem where it wont visit github.

**Comment by brentvatne** [comment]
@abdymm - I think @quinlanj is correct, you probably need to run `npm install` in the project directory

**Comment by abdymm** [comment]
@quinlanj @brentvatne , actually I already did it, and the error was still same, not just that, I even rm node_modules and `npm install` and still same.

**Comment by jmporchet** [comment]
I guess you will find more info in the debug.log file @abdymm, what does it say?
Did you install it with sudo?

**Comment by cruzach** [comment]
@abdymm are you still seeing this issue? If you managed to fix it, let me know what ended up being the source of the problem

**Comment by abdymm** [comment]
sorry, I forgot what happened, i just reinstall my npm and react-native
