### ISSUE TITLE
[expo-image] Blurhash doesn't work on web in expo-image 1.12.9

### ISSUE THREAD

**Issue by duogenesis** [expo/expo#29425]
### Minimal reproducible example

https://github.com/expo/expo

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

Yes

### Summary

Either blurhash is broken on web (most likely) or the documentation is out of date. Following [the example](https://docs.expo.dev/versions/latest/sdk/image/#usage) on expo.dev results in no blurhash image being displayed. I've reproduced the example here for posterity:

```typescript
import { Image } from 'expo-image';
import { StyleSheet, View } from 'react-native';

const blurhash =
  '|rF?hV%2WCj[ayj[a|j[az_NaeWBj@ayfRayfQfQM{M|azj[azf6fQfQfQIpWXofj[ayj[j[fQayWCoeoeaya}j[ayfQa{oLj?j[WVj[ayayj[fQoff7azayj[ayj[j[ayofayayayj[fQj[ayayj[ayfjj[j[ayjuayj[';

export default function App() {
  return (
    <View style={styles.container}>
      <Image
        style={styles.image}
        source="https://picsum.photos/seed/696/3000/2000"
        placeholder={{ blurhash }}
        contentFit="cover"
        transition={1000}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    flex: 1,
    width: '100%',
    backgroundColor: '#0553',
  },
});
```

Instead of displaying the blurhash, the app attempts to make a HTTP request, as mentioned in [this](https://github.com/expo/expo/issues/21677#issuecomment-2103804267) comment. Thumbhash works just fine.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ~51.0.9 => 51.0.9 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare

### Expo Doctor Diagnostics

N/A

**Comment by duogenesis** [comment]
I fixed the failing network operation by changing `expo-image/src/utils/blurhash/useBlurhash.ts`. Actually I modified the built source code directly and generated a patch with `patch-package`. Patch file is:

```patch
diff --git a/node_modules/expo-image/build/utils/blurhash/decode.js b/node_modules/expo-image/build/utils/blurhash/decode.js
index 8ef8741..dec2519 100644
--- a/node_modules/expo-image/build/utils/blurhash/decode.js
+++ b/node_modules/expo-image/build/utils/blurhash/decode.js
@@ -43,6 +43,7 @@ const decodeAC = (value, maximumValue) => {
     return rgb;
 };
 const decode = (blurhash, width, height, punch) => {
+    blurhash = blurhash.replace(/^blurhash:\//, '').split('/')[0];
     validateBlurhash(blurhash);
     punch = (punch || 1) | 1;
     const sizeFlag = decode83(blurhash[0]);
diff --git a/node_modules/expo-image/build/utils/blurhash/useBlurhash.js b/node_modules/expo-image/build/utils/blurhash/useBlurhash.js
index 39c7f1e..173d1e9 100644
--- a/node_modules/expo-image/build/utils/blurhash/useBlurhash.js
+++ b/node_modules/expo-image/build/utils/blurhash/useBlurhash.js
@@ -12,10 +12,11 @@ const DEFAULT_SIZE = {
 const scaleRatio = 10;
 export function useBlurhash(blurhash, punch = 1) {
     punch = punch || 1;
+    const isBlurhashString_ = blurhash && blurhash.uri && isBlurhashString(blurhash.uri);
     const [uri, setUri] = useState(null);
     useEffect(() => {
         let isCanceled = false;
-        if (!blurhash || !blurhash.uri || !isBlurhashString(blurhash.uri))
+        if (!isBlurhashString_)
             return;
         const pixels = decode(blurhash.uri, blurhash?.width ?? DEFAULT_SIZE.width, blurhash?.height ?? DEFAULT_SIZE.height, punch);
         const canvas = document.createElement('canvas');
@@ -59,6 +60,6 @@ export function useBlurhash(blurhash, punch = 1) {
             });
         };
     }, [blurhash?.uri, blurhash?.height, blurhash?.width, punch]);
-    return useMemo(() => (uri ? { uri } : null), [uri]);
+    return useMemo(() => (isBlurhashString_ ? { uri } : null) , [uri]);
 }
 //# sourceMappingURL=useBlurhash.js.map
diff --git a/node_modules/expo-image/build/utils/resolveHashString.web.js b/node_modules/expo-image/build/utils/resolveHashString.web.js
index 43b7a13..b423448 100644
--- a/node_modules/expo-image/build/utils/resolveHashString.web.js
+++ b/node_modules/expo-image/build/utils/resolveHashString.web.js
@@ -9,7 +9,7 @@
 export function resolveBlurhashString(str) {
     const [blurhash, width, height] = str.replace(/^blurhash:\//, '').split('/');
     return {
-        uri: blurhash,
+        uri: 'blurhash:/' + blurhash,
         width: parseInt(width, 10) || 16,
         height: parseInt(height, 10) || 16,
     };
```

I'm probably not going to raise a PR any time soon, but hopefully this provides a would-be contributor with steps to raise their own.

**Comment by focux** [comment]
I'm having this same problem and tried to use the patch and got `offset is out of bonds`. It seems to happen when setting the pixels into the canvas: `imageData.data.set(pixels);`.

My blurhash looks like this: `LCI;CX^*Cm5Utdj?nhIrGZNarDwK`

**Comment by duogenesis** [comment]
@focux What browser are you using?

**Comment by focux** [comment]
I'm using Arc, which is a chromium-based browser.

**Comment by duogenesis** [comment]
This was fixed by https://github.com/expo/expo/pull/27587. Thanks, @aleqsio!
