### ISSUE TITLE
Firebase: Firestore crashes when saving timestamp

### ISSUE THREAD

**Issue by JamesMcIntosh** [expo/expo#2943]
When saving FireStore data on iOS which contains a TimeStamp the application crashes.

@EvanBacon could you please add some insight.

For example:
```
firestore.set(
	{ collection: 'TestData', doc: 'abc123' },
	{ created: firestore.FieldValue.serverTimestamp() }
)
```

It crashes at the following line 421 of [EXFirebaseFirestoreDocumentReference.m](https://github.com/expo/expo/blob/master/packages/expo-firebase-firestore/ios/EXFirebaseFirestore/EXFirebaseFirestoreDocumentReference.m#L421) because of an incorrect type. The value of string is expected to be `NSString` but is actually `__NSDictionaryM` consisting of `{ type = @"timestamp" }`

To get my app to work I have changed the string variable to

```
NSString *string = (NSString *) value[typeKey];
```

**Comment by EvanBacon** [comment]
I'm not hitting this error in rc-5. Could you do a thorough update (yarn upgrade & pod repo update) and try it again? If not I'll consider this resolved

**Comment by JamesMcIntosh** [comment]
@EvanBacon, I gave it another test and I am is still having the same behaviour.

When I stringify the value of the server timestamp in RN as follows I get
```
console.log(`${JSON.stringify(firestore.FieldValue.serverTimestamp())}`);

{"_type":"timestamp"}
```
When looking through the stack trace in iOS at `EXFirebaseFirestoreDocumentReference.set()` the data has been deserialised to be
```
{ // _NSDictionaryM
    "created" =     {
        type = fieldvalue;
        value = { // _NSDictionaryM
            type = timestamp;
        };
    };
}
```

**Comment by JamesMcIntosh** [comment]
It looks like this code is mission handling for FieldValue.arrayUnion and FieldValue.arrayRemove too.
