### ISSUE TITLE
expo-image-picker and expo-media-library provide incomplete EXIF information

### ISSUE THREAD

**Issue by Hooper93** [expo/expo#29442]
### Minimal reproducible example

https://github.com/Hooper93/expo-bug-report

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

When I use the two tool libraries `expo-image-picker` and `expo-media-library` 
to obtain the photos I took with a Sony camera, the exif information they provide is incomplete. 

```js
{"BrightnessValue": 8.0171875, "ColorSpace": 1, "ComponentsConfiguration": [1, 2, 3, 0], "CompressedBitsPerPixel": 3, "Contrast": 0, "CustomRendered": 0, "DateTimeDigitized": "2024:04:06 09:15:26", "DateTimeOriginal": "2024:04:06 09:15:26", "DigitalZoomRatio": 1, "ExifVersion": [2, 3, 1], "ExposureBiasValue": 0, "ExposureMode": 1, "ExposureProgram": 1, "ExposureTime": 0.004, "FNumber": 4, "FileSource": 3, "Flash": 16, "FlashPixVersion": [1, 0], "FocalLenIn35mmFilm": 87, "FocalLength": 87, "ISOSpeedRatings": [200], "LensModel": "FE 24-105mm F4 G OSS", "LensSpecification": [24, 105, 4, 4], "LightSource": 10, "MaxApertureValue": 4, "MeteringMode": 2, "OffsetTime": "+08:00", "OffsetTimeDigitized": "+08:00", "OffsetTimeOriginal": "+08:00", "Orientation": 1, "PixelXDimension": 6240, "PixelYDimension": 4160, "RecommendedExposureIndex": 200, "Saturation": 0, "SceneCaptureType": 0, "SceneType": 1, "SensitivityType": 2, "Sharpness": 0, "WhiteBalance": 1}
```
↑ this is the exif of picture by Sony a7r4, Model tag is missing, but LensModel can read out, GPS information is lost too.

When I use lightroom or other software to view the exif information of these photos, it is completable. 
![image](https://github.com/expo/expo/assets/48215196/faa40e93-5c7e-4242-a27c-4d2300c8092a)
↑ the same photo can read the Make or Model exif on https://exifmeta.com

this is the photo:
![DSC02727](https://github.com/expo/expo/assets/48215196/7ec43e7d-de04-43d0-b409-bb86b9e8fae7)

The lost information is very random, such as the camera's device model, geographic location, lens information, etc. 

The loss of this information also shows a correlation with the shooting device. 
For example, the photos taken by my SONY camera can read the lens information, but the camera model cannot be obtained; For another example, I can only read out IOS, shutter and other information from the photos taken by the DJI drone, and the device model and lens information cannot be read, but this information exists in EXIF, and I can use other software to read it out.

```js
{"ApertureValue": 2.97, "BodySerialNumber": "6GVFL6C11109T3", "ColorSpace": 1, "ComponentsConfiguration": [1, 2, 3, 0], "Contrast": 0, "CustomRendered": 0, "DateTimeDigitized": "2023:10:04 11:34:02", "DateTimeOriginal": "2023:10:04 11:34:02", "DigitalZoomRatio": 1, "ExifVersion": [2, 3], "ExposureBiasValue": 0, "ExposureMode": 0, "ExposureProgram": 2, "ExposureTime": 0.004166666666666667, "FNumber": 2.8, "FileSource": 3, "Flash": 0, "FlashPixVersion": [1, 0], "FocalLenIn35mmFilm": 70, "FocalLength": 19.35, "GPSAltitude": 737.037, "GPSAltitudeRef": 0, "GPSGPSVersion": [2, 3, 0, 0], "GPSLatitude": 51.33297, "GPSLatitudeRef": "N", "GPSLongitude": 120.67776666666667, "GPSLongitudeRef": "E", "GPSMapDatum": "WGS-84", "GPSStatus": "A", "GainControl": 0, "ISOSpeedRatings": [100], "LensSpecification": [70, 70, 2.799999952316284, 2.799999952316284], "LightSource": 2, "MaxApertureValue": 2.97, "MeteringMode": 2, "Orientation": 1, "PixelXDimension": 4032, "PixelYDimension": 2268, "Saturation": 0, "SceneCaptureType": 0, "SceneType": 1, "SensitivityType": 2, "Sharpness": 0, "ShutterSpeedValue": 7.9069, "SubjectDistance": 0, "WhiteBalance": 0}
```
↑ photo by DJI, can only read GPS information, Model / Make / LensModel are all lost

![image](https://github.com/expo/expo/assets/48215196/fa9a59e7-196d-46b1-8d25-ac2be3d366d8)
↑ the same photo can read the exif on https://exifmeta.com

Is this a system limitation of IOS? Or do I need to enable some advanced permissions to see these additional exif information?

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.1.0 - /usr/local/bin/node
      Yarn: 3.6.1 - /usr/local/bin/yarn
      npm: 8.19.3 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.9 => 51.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by Hooper93** [comment]
[IMG_5012.JPG.zip](https://github.com/user-attachments/files/15572631/IMG_5012.JPG.zip)
the photo by DJI

**Comment by joequery** [comment]
Hello there!

I was not able to reproduce the first issue using your repro repo. Here is the result from the console log using the provided image taken by the SONY camera.

```json
 {"BrightnessValue": 4.37265625, "ColorSpace": 1, "ComponentsConfiguration": "???", "CompressedBitsPerPixel": 2, "Compression": 6, "Contrast": 0, "CustomRendered": 0, "DateTime": "2024:05:05 15:07:15", "DateTimeDigitized": "2024:05:05 15:07:15", "DateTimeOriginal": "2024:05:05 15:07:15", "DigitalZoomRatio": 1, "ExifVersion": "0231", "ExposureBiasValue": 0, "ExposureMode": 1, "ExposureProgram": 1, "ExposureTime": 0.00625, "FNumber": 4, "FileSource": "?", "Flash": 16, "FlashpixVersion": "0100", "FocalLength": 32, "FocalLengthIn35mmFilm": 32, "ISOSpeedRatings": 2000, "ImageLength": 4160, "ImageWidth": 6240, "InteroperabilityIndex": "R98", "JPEGInterchangeFormat": 38986, "JPEGInterchangeFormatLength": 9566, "LightSource": 0, "Make": "SONY", "MakerNote": "SONY DSC ", "MaxApertureValue": 4, "MeteringMode": 2, "Model": "ILCE-7RM4A", "Orientation": 1, "PixelXDimension": 6240, "PixelYDimension": 4160, "ResolutionUnit": 2, "Saturation": 0, "SceneCaptureType": 0, "SceneType": "?", "Sharpness": 0, "Software": "ILCE-7RM4A v1.10", "UserComment": "", "WhiteBalance": 0, "XResolution": 350, "YCbCrPositioning": 2, "YResolution": 350}
```

Here is my expo-env-info. I even used nvm to switch to your provided version of node.

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
      npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.9 => 51.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: managed
```

**Comment by joequery** [comment]
I also was not able to reproduce for the jpg provided in the zip file.

Console log output:

```
{"ApertureValue": 2.97, "ColorSpace": 1, "ComponentsConfiguration": "???", "Compression": 7, "Contrast": 0, "CustomRendered": 0, "DateTime": "2023:10:04 11:34:02", "DateTimeDigitized": "2023:10:04 11:34:02", "DateTimeOriginal": "2023:10:04 11:34:02", "DeviceSettingDescription": "", "DigitalZoomRatio": 1, "ExifVersion": "0230", "ExposureBiasValue": 0, "ExposureMode": 0, "ExposureProgram": 2, "ExposureTime": 0.004166666666666667, "FNumber": 2.8, "FileSource": "?", "Flash": 0, "FlashpixVersion": "0100", "FocalLength": 19.35, "FocalLengthIn35mmFilm": 70, "GPSAltitude": 0, "GPSAltitudeRef": 0, "GPSLatitude": 0, "GPSLatitudeRef": "", "GPSLongitude": 0, "GPSLongitudeRef": "", "GPSMapDatum": "", "GPSStatus": "", "GPSVersionID": "", "GainControl": 0, "ISOSpeedRatings": 100, "ImageDescription": "default", "ImageLength": 2268, "ImageWidth": 4032, "InteroperabilityIndex": "R98", "JPEGInterchangeFormat": 1372, "JPEGInterchangeFormatLength": 25144, "LightSource": 2, "Make": "DJI", "MakerNote": "?", "MaxApertureValue": 2.97, "MeteringMode": 2, "Model": "FC8284", "Orientation": 1, "PixelXDimension": 4032, "PixelYDimension": 2268, "ResolutionUnit": 2, "Saturation": 0, "SceneCaptureType": 0, "SceneType": "?", "Sharpness": 0, "ShutterSpeedValue": 7.9069, "Software": "10.02.00.09", "SubjectDistance": 0, "WhiteBalance": 0, "XResolution": 72, "YCbCrPositioning": 1, "YResolution": 72}
```

Note that I did not see the LensModel for this file even in exiv2 output

[5012-exif.txt](https://github.com/user-attachments/files/15585809/5012-exif.txt)

**Comment by Hooper93** [comment]
It seems like your Android is fine?

The problems I reported occurred on my iOS device, iPhone 15 Pro max, and the iOS version is 17.4.1. 

Can you find an iOS device to try it out? This is 100% sure to happen here.

**Comment by Hooper93** [comment]
I used the EXPO GO app for testing. Is this related to this? The app version is already the latest version

**Comment by joequery** [comment]
Unfortunately I don't have an iOS device to help here. Hopefully a contributor can help you out.

**Comment by Hooper93** [comment]
> Hello there!
> 
> I was not able to reproduce the first issue using your repro repo on Android. Here is the result from the console log using the provided image taken by the SONY camera.
> 
> My testing device was a Motorola g power 2022.
> 
> ```json
>  {"BrightnessValue": 4.37265625, "ColorSpace": 1, "ComponentsConfiguration": "???", "CompressedBitsPerPixel": 2, "Compression": 6, "Contrast": 0, "CustomRendered": 0, "DateTime": "2024:05:05 15:07:15", "DateTimeDigitized": "2024:05:05 15:07:15", "DateTimeOriginal": "2024:05:05 15:07:15", "DigitalZoomRatio": 1, "ExifVersion": "0231", "ExposureBiasValue": 0, "ExposureMode": 1, "ExposureProgram": 1, "ExposureTime": 0.00625, "FNumber": 4, "FileSource": "?", "Flash": 16, "FlashpixVersion": "0100", "FocalLength": 32, "FocalLengthIn35mmFilm": 32, "ISOSpeedRatings": 2000, "ImageLength": 4160, "ImageWidth": 6240, "InteroperabilityIndex": "R98", "JPEGInterchangeFormat": 38986, "JPEGInterchangeFormatLength": 9566, "LightSource": 0, "Make": "SONY", "MakerNote": "SONY DSC ", "MaxApertureValue": 4, "MeteringMode": 2, "Model": "ILCE-7RM4A", "Orientation": 1, "PixelXDimension": 6240, "PixelYDimension": 4160, "ResolutionUnit": 2, "Saturation": 0, "SceneCaptureType": 0, "SceneType": "?", "Sharpness": 0, "Software": "ILCE-7RM4A v1.10", "UserComment": "", "WhiteBalance": 0, "XResolution": 350, "YCbCrPositioning": 2, "YResolution": 350}
> ```
@joequery  Hi  there! 

I found an Android device and after verification, it also lacked information, and the tags returned were inconsistent with iOS. 

For example, the EXIF ​​you provided here recognized Make and Model, 
but lost GPS information and LensModel, which can be recognized on iOS devices:
<img width="370" alt="image" src="https://github.com/expo/expo/assets/48215196/26d0ea48-c461-454b-9de5-5c3dfb004b88">

So `expo-image-picker` is indeed different on iOS and Android, and the EXIF information returned is incomplete, and the developer needs to confirm it
