### ISSUE TITLE
Prebuild command should not add "ios" and "android" scripts to package.json

### ISSUE THREAD

**Issue by wvteijlingen** [expo/expo#29446]
### Summary

Every time I run `npx expo prebuild`, two new scripts `ios` and `android` scripts gets added to the package.json.

I've purposely removed them because I like to use a different set of scripts. Now every time I run `prebuild` I have to go in and remove the script entries again. I don't think the `prebuild` command should add these scripts. It's fine to have them in a new project template, but developers should be allowed to change them as they see fit.

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

51

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.2.0 - ~/.asdf/installs/nodejs/20.2.0/bin/node
      npm: 9.6.6 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.14.3 - /Users/ward/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.7 => 51.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: managed
```

### Minimal reproducible example

1.  Create a fresh expo project
2. Remove the `ios` and `android` scripts from package.json
3. Run `npx expo prebuild`

**Comment by joequery** [comment]
Not commenting to provide an opinion on the behavior here, but I did just want to point out that the behavior here does appear deliberate.

https://github.com/expo/expo/blob/0f999166f4bc882b5d1c08474dcf0d6a9750bffd/packages/%40expo/cli/src/prebuild/updatePackageJson.ts#L245-L259

It does appear to operate specifically by looking for the string "run" in the "android"/"ios" options. 

So as a workaround (sorry project maintainers if this doesn't vibe with you), you can append `echo 'run'` to your command. I've tested and this workaround does prevent the prebuild script from overwriting the commands.

```
  "scripts": {
    "start": "expo start",
    "web": "expo start --web",
    "android": "<your command> && echo 'run' ",
    "ios": "<your command> && echo 'run'"
  },
```

**Comment by wvteijlingen** [comment]
Interesting, I'm wondering what the purpose of this behaviour would be.

The workaround kinda works but I personally don't want to have scripts with those names at all, since I'm using different names completely (`run:ios-sim, run:ios-device` etc.)

**Comment by joequery** [comment]
I understand. The best way you could leverage the workaround for your use case, in my opinion, would be something like

```
  "scripts": {
    ...
    "android": "echo 'use npm run:android-sim or npm run:android-device",
    "ios": "echo 'use npm run:ios-sim or npm run:ios-device"
  },
```

**Comment by brentvatne** [comment]
we should update our checks so that we only update these scripts if they are the default value for new projects. if you've changed them, then we should leave them alone
