### ISSUE TITLE
paramsSerializer not support multiple same key

### ISSUE THREAD

**Issue by hasanaktas** [expo/expo#29457]
### Minimal reproducible example

https://github.com/hasanaktas/expo-router-search-params-bug

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I have a project where I am trying to reflect the url structure on my site.

Unfortunately, the expo router does not support the following example structures.

```
?color=red&color=yellow&color=blue

//useLocalSearchParams result
//color='blue'

```

Expected Behavior

```
?color=red&color=yellow&color=blue

//useLocalSearchParams result
//color=['blue','red','yellow']
```

When working with URLs, there is the same problem on both web and mobile.

We also need to be able to set multiple values ​​to the same key. It currently only accepts string.string array should also accept

```
const router = useRouter()
router.setParams({
  color:'red'
})
    
//useLocalSearchParams result
color='red'

//newUrlSearch
?color=red
```

```
const router = useRouter()
router.setParams({
  color:['red','green','blue']
})
    
//useLocalSearchParams result
color=['red','green','blue']

//newUrlSearch
?color=red&color=green&color=blue
```

### Environment

  System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.10 => 51.0.10 
      expo-router: ~3.5.15 => 3.5.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

**Comment by hasanaktas** [comment]
Will there be any work on this issue or will we not stick to web standards?

I would appreciate it if you could at least convey your ideas.

**Comment by marklawlor** [comment]
This is something were discussing. I believe there isn't standard for this, and the implementation is framework specific (if I'm wrong please link me the spec!). Most frameworks seem to settle on either 

1. `?color=red&color=green&color=blue` 
2. `?color[]=red,green,blue`
3. `?color[]=red&color[]=green&color[]=blue` 

Right now we're simply using the JavaScript `URL` constructor, which does not allow arrays

```ts
const url = new URL("http://localhost?color=red&color=blue")
console.log(url.searchParams.get("color")) // "red"

url.searchParams.set("color", ["red", "blue"])
console.log(url.toString()) // http://localhost/?color=red%2Cblue
```

**Comment by hasanaktas** [comment]
It seems logical to consider set and append separately.

likewise get and getAll.

const url = new URL("http://localhost?color=red&color=blue")

console.log(url.searchParams.get("color")) // "red"
console.log(url.searchParams.getAll("color")) // ["red","blue"]
console.log(url.toString()) // http://localhost/?color=red&color=blue

url.searchParams.append("color","green")

console.log(url.searchParams.get("color")) // "red"
console.log(url.searchParams.getAll("color")) // ["red","blue","green"]
console.log(url.toString()) // http://localhost/?color=red&color=blue&color=green

url.searchParams.set("color","yellow")
console.log(url.searchParams.get("color")) // "yellow"
console.log(url.searchParams.getAll("color")) // ["yellow"]
console.log(url.toString()) // http://localhost/?color=yellow
