### ISSUE TITLE
SplashScreen on Android breaks with expo-font plugin

### ISSUE THREAD

**Issue by HishamOmran** [expo/expo#29461]
### Minimal reproducible example

https://github.com/HishamOmran/splash-screen-test

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

There seems to be an issue on Android with `expo-splash-screen` when loading a font using the `expo-font` config plugin. When building a release build, the SplashScreen doesn't respect the `SplashScreen.preventAutoHideAsync()` function and immediately disappears on Android. 

When loading the font using the `useFonts()` hook, the SplashScreen seems to work okay and respects the `SplashScreen.preventAutoHideAsync()` function.

### Environment

❯ npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/user/.rvm/gems/ruby-3.2.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.10 => 51.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    Expo Workflow: managed

### Expo Doctor Diagnostics

❯ npx expo-doctor@latest  
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
hi there! the repo you shared seems to have the expected behavior - it stays forever on the splash screen in both debug and release builds on android, because you never hide it but you prevent hiding it.

<img width="453" alt="image" src="https://github.com/expo/expo/assets/90494/9a453210-5c16-4ee3-9eb0-691e52f92387">

**Comment by HishamOmran** [comment]
@brentvatne if you run `npx expo run:android --variant release --device` you'll see that the SplashScreen disappears on load (Only on Android)
![Android Screenshot](https://github.com/expo/expo/assets/72177894/2002d2d5-290e-4161-87ad-2fb5d746330d)

**Comment by brentvatne** [comment]
hi @HishamOmran - i just ran this on my android device and emulator using a debug and release variant and it worked as expected.

**Comment by dan-doyon-endear** [comment]
version 51.0.9 had introduced an issue for us on existing code. The fonts would not load and therefore the splash screen would not hide (using the same pattern most use). We backed off to version 51.0.8 and it works fine.

**Comment by brentvatne** [comment]
hey @dan-doyon-endear - we don't know how to reproduce this issue. please create a new issue with a minimal reproducible example and we can help you to investigate!
