### ISSUE TITLE
Web build crashes after upgrade to expo 50

### ISSUE THREAD

**Issue by boutmansb** [expo/expo#29503]
### Minimal reproducible example

https://github.com/boutmansb/my-app

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

After upgrading to expo 50 our web build won't build anymore. We have also tried it in expo 51, same result, the example uses expo 50 since this is closer to our actual production build that we are trying to fix.

 The crash is caused by the following line: `const drawer = createDrawerNavigator();` (see line 10 in index.tsx in example repo). Which is just the basis drawer navigator of react-native, but our main navigation is in a drawer so we need it to work on the web as well.

Our IOS/android builds were not affected by the upgrade, they are still working as expected.

After some digging I think to problem is with our metro config. Currently it sets 
```
config.transformer.getTransformOptions = async () => ({
    transform: {
      experimentalImportSupport: true,
    },
  });
```
When it is on `true` (how it used to be when our web build still worked) we now get the error `RNRENDERER not found...` when we set it to false we get the error that import statements should be at the top of the file (which they are...).

The example repo is just the default app created by `npx create-expo-app@latest` but downgraded to version 50 and with `@react-navigation/drawer` added so we can test the crashing line of code. So it should be a very minimal example. Any help would be greatly appreciated.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
      Yarn: 3.2.4 - ~/.nvm/versions/node/v18.12.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0 => 50.0.19 
      expo-router: ~3.4.10 => 3.4.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by TacticsJan** [comment]
Is there any news on this?
