### ISSUE TITLE
No Bundle URL Error On Physical iOS Device with standard project

### ISSUE THREAD

**Issue by Hookyhook** [expo/expo#29512]
### Summary

Using the standard project and a physical iOS device (problem does not occur in the simulator) running the command:
```shell
npx expo run:ios --device
``` 
creates this error
![IMG_4101](https://github.com/expo/expo/assets/108137850/2102dee8-5917-448e-93d0-e14cf99462e1)

Important: Expo Dev Tools are **not installed**

### What platform(s) does this occur on?

iOS

### SDK Version

CLI Version: 0.18.15 SDK: 51.0.10

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.2.0 - /usr/local/bin/node
      npm: 10.2.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.10 => 51.0.10 
      expo-router: ~3.5.15 => 3.5.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Minimal reproducible example

1. Create Standard Project
````shell
npx create-expo-app@latest
````
2. Enter Project Folder (e.g test)
````shell
cd test
````
3. Install Dependencies
````shell
npm i
````
4. Attach a physical iOS device with Developer Mode enabled 
5. Install and run the app in development mode (Insert any unique bundleIdentifier and Select your physical device)
````shell
npx expo run:ios --device 
````
(Including a repo does not really makes sense as the first command creates everything basic)

**Comment by Kudo** [comment]
hi there! since device and your host may cross different lan, you could try to start the server by `npx expo start --tunnel` and scan the qr code from your iphone.

**Comment by abduaddis1** [comment]
Is there any update on this? I have a project that also uses AWS Amplify and as a result is limited with using expo go; is there a way to fix this issue with native builds running on a physical device?

**Comment by jonathans199** [comment]
Hey guys, so I had the same issue, but I figured out that basically my computer and IPHONE were on a different WIFI. 

I have 2 WIFIs at home one 2.4 and another 5.0 with a different name. 

***Make sure they are on the same WIFI and you should be good to go. ***

At least that was my fix, and right away it started working.
