### ISSUE TITLE
Flipper Integration issue After updating Expo SDK 50 to Expo SDK 51

### ISSUE THREAD

**Issue by souravzversal** [expo/expo#29525]
### Minimal reproducible example

NA

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

My application works fine in development mode with Expo 51. However, when attempting to generate a build, I encounter an unexpected error related to Flipper integration. Strangely, I haven't integrated Flipper into my app at all.

Additionally, while Expo 50 generating build successfully, I've noticed a compatibility issue with Expo Go available on the Play Store, which doesn't fully support Expo 50. As a result, users might face limitations when trying to run the app through Expo Go.

If anyone has encountered similar challenges or has insights on resolving either the build issue for Expo 51 or the development issue for Expo 50, I'd greatly appreciate your input. Feel free to reach out or share your thoughts in the comments. Thank you!

![image](https://github.com/expo/expo/assets/155941676/8acdbb0c-e1d7-4c65-8c53-82f147e40f3c)

### Environment

 expo-env-info 1.2.0 environment info:
   
    npmPackages:
      expo: ^51.0.9 => 50.0.19
      react: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.73.6
    Expo Workflow: bare

### Expo Doctor Diagnostics

    ErrorCaptureStackTrace(err);
    ^

Error: spawn tasklist ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn tasklist',
  path: 'tasklist',
  spawnargs: [ '/nh', '/fo', 'csv', '/fi', 'PID eq 1196' ],
  cmd: 'tasklist /nh /fo csv /fi PID eq 1196',
  stdout: '',
  stderr: ''
}

**Comment by hassankhan** [comment]
> My application works fine in development mode with Expo 51. However, when attempting to generate a build, I encounter an unexpected error related to Flipper integration. Strangely, I haven't integrated Flipper into my app at all.

Do you happen to have any logs for this?

> Additionally, while Expo 50 generating build successfully, I've noticed a compatibility issue with Expo Go available on the Play Store, which doesn't fully support Expo 50. As a result, users might face limitations when trying to run the app through Expo Go.

I think this is because Expo Go now only supports the latest version of the Expo SDK: https://expo.dev/changelog/2024/05-07-sdk-51#-expo-go-dropped-sdk-49-and-50

**Comment by lukmccall** [comment]
In Expo 51, we're using React Native 0.74, which removed the default flipper integration: https://reactnative.dev/blog/2024/04/22/release-0.74#removal-of-flipper-react-native-plugin. You might want to remove it from your app or ensure that you follow all the new integration steps.

**Comment by Kudo** [comment]
hi there! flipper is deprecated. you could refer https://docs.expo.dev/bare/upgrade/?fromSdk=50&toSdk=51 to migrate your project off from flipper.
