### ISSUE TITLE
MapView ref takeSnapshot throws error on Android

### ISSUE THREAD

**Issue by mayteio** [expo/expo#2953]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
   
    Expo CLI 2.6.11 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.0.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.11

### Steps to Reproduce

1. import MapView from 'expo'
2. Try to take a snapshot per [instructions](https://github.com/react-native-community/react-native-maps#take-snapshot-of-map)

```
takeSnapshot = () => {
    this.map
      .takeSnapshot({
        width: 1000,
        height: 1000
      })
      .then(res => console.log(res));
  };
```

### Expected Behavior

The function should return a blob or base64 file of map snapshot

### Actual Behavior

Error is displayed `Undefined is not an object (evaluating '_reactNative.NativeModules.AirMapModule.takeSnapshot')`

![screenshot 2018-12-11 11 34 04](https://user-images.githubusercontent.com/43975092/49770487-b024d580-fd38-11e8-9bf5-bef4ea930df7.png)

### Reproducible Demo

Simple reproducible demo code available here: https://snack.expo.io/@mayteio/airmapmodule-issue
Unfortunately, snack doesn't have react-native-maps as a possible dependancy. 

I have also pushed to a repository here: https://github.com/mayteio/react-native-airmapmodule-issue

**Comment by brentvatne** [comment]
indeed it appears to be an issue on Android, but works on iOS. you can use `takeSnapshotAsync` for now to work around this: https://snack.expo.io/@notbrent/airmapmodule-issue

**Comment by brentvatne** [comment]
I think it's likely that this is an upstream issue, can you try installing react-native-maps on a brand new `react-native init` project and see if you still have this issue on Android?

**Comment by JensSam** [comment]
Has there been any work done on this? I can't get it to work on Android and I've built a brand new project today (2019-09-28)

Rgds,
Jens

**Comment by cruzach** [comment]
@JensSam it looks like this is [an issue with `react-native-maps`](https://github.com/react-native-community/react-native-maps/issues/2623), and not specific to Expo.
