### ISSUE TITLE
[expo-module] `Plugin with id 'com.android.library' not found.` on Android Studio

### ISSUE THREAD

**Issue by jrafaaael** [expo/expo#29569]
### Minimal reproducible example

https://github.com/jrafaaael/mymodule

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I just wanna create a new Expo Module for Android apps. I've installed Android Studio and created a new Expo Module. The example project works fine and changes on Kotlin side compile fine too. However, when I try to edit the code of `MyModule.kt` on Android Studio I get the error from Gradle sync:
```
Build file '/home/jrafael/code/my-module/android/build.gradle' line: 1

A problem occurred evaluating root project 'android'.
> Plugin with id 'com.android.library' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 2s
```

and the warning `Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly.`

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.2 (Victoria)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-233.14808.21.2331.11842104
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

On the root of the Expo Module I get:
```
ConfigError: Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
    at getExpoSDKVersionFromPackage (/home/jrafael/.npm/_npx/89957a0324271eeb/node_modules/expo-doctor/build/index.js:53:477155)
    at getExpoSDKVersion (/home/jrafael/.npm/_npx/89957a0324271eeb/node_modules/expo-doctor/build/index.js:53:477008)
    at ensureConfigHasDefaultValues (/home/jrafael/.npm/_npx/89957a0324271eeb/node_modules/expo-doctor/build/index.js:53:468539)
    at fillAndReturnConfig (/home/jrafael/.npm/_npx/89957a0324271eeb/node_modules/expo-doctor/build/index.js:53:465378)
    at getConfig (/home/jrafael/.npm/_npx/89957a0324271eeb/node_modules/expo-doctor/build/index.js:53:466626)
    at actionAsync (/home/jrafael/.npm/_npx/89957a0324271eeb/node_modules/expo-doctor/build/index.js:59:100143)
    at async run (/home/jrafael/.npm/_npx/89957a0324271eeb/node_modules/expo-doctor/build/index.js:59:101815) {
  isConfigError: true,
  code: 'MODULE_NOT_FOUND',
  cause: undefined
```

**Comment by jrafaaael** [comment]
For future reference: I need to open the Expo Module folder instead of just the `android/` folder

**Comment by PineAppleGrits** [comment]
Any fix ? 

> What do you mean by open the `Expo Module folder` ?
> 
> I tried to open the 3 without success
> 
> ![image](https://private-user-images.githubusercontent.com/83060543/385780456-a371ea4a-9f5c-4484-b05c-ef81b45554b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MDYxNjUsIm5iZiI6MTczNTUwNTg2NSwicGF0aCI6Ii84MzA2MDU0My8zODU3ODA0NTYtYTM3MWVhNGEtOWY1Yy00NDg0LWIwNWMtZWY4MWI0NTU1NGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDIwNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYTkxYjQyYjI0NjA4OTQ2NTQ1ZjQ1NWI3MWQ4OTRjYmM3MzNmZWFkOTE1ZWE2ZDk1MmQxMDY5MTk0MGI0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kd_a7Y6aKUAYsFake7Kwx-84G27e9gq_bl44VAKe6xU)

Did you fix it ?

**Comment by shinjith-dev** [comment]
I think we have to open the android folder generated from expo development build (`/android`) and edit module.

> Open the android directory (that is generated by npx expo prebuild in step 1) from your project in Android Studio. It may take a while for Gradle to finish syncing the native directory project.

From [expo docs](https://docs.expo.dev/modules/get-started/#edit-the-module)
