### ISSUE TITLE
[Android] Update `compileSdkVersion` to 28 and introduce `AndroidX`

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#2956]
Android had introduced `sdk 28` with supporting libraries replaced by `androidx`. Many maintained libraries, like `com.theartofdev.edmodo:android-image-cropper` that we're using have already made this migration. Unfortunately we're unable to use them because of dependency hell that happens when we're having different `compileSdkVersion`.

Proposal: update `compileSdkVersion` to 28 and replace all deprecated `android-support-*` libraries with `androidX`. Moreover some cleanup is advisable in `gradle` files as well.

**Comment by SimenB** [comment]
Did this happen/is there some other tracking issue I can follow? Or is it dependent on https://github.com/facebook/react-native/issues/23112 and nothing for expo itself to do?

**Comment by SimenB** [comment]
RN 0.60 has moved to `AndroidX` - does that mean Expo will as well whenever the RN bump happens?

https://facebook.github.io/react-native/blog/2019/07/03/version-60#androidx-support

**Comment by bbarthec** [comment]
@SimenB, `AndroidX` would be introduced alongside migration to `react-native@0.60`. That would happen in `SDK35` or `SDK36`.

**Comment by SimenB** [comment]
Great, thanks!

**Comment by tsapeta** [comment]
I'm closing this issue as it's been solved already - we've migrated to AndroidX on master a few days ago: #5521, so the next SDK will use it 🙂
