### ISSUE TITLE
Fork the react-native's babel preset and remove peer dependencies and use this in the expo preset

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2958]
Currently when you initialize a new project there are a bunch of warnings about missing peer dependencies. This is not very useful and it's easy to fix.

**Comment by DianaKoenraadt** [comment]
Chiming in to mention the actual warnings

```
npm WARN expo-google-sign-in@2.0.0 requires a peer of react-native@^0.55.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

Also mentioned here by someone else, who has these errors with every package they try to install: https://stackoverflow.com/questions/54135379/unable-to-install-react-navigation-package-using-npm

**Comment by FiberJW** [comment]
This seems to be resolved, so I’ll close this for now. I tested by initializing a new Expo project and I didn't run into any messy peer dependency warnings using yarn. If it is not the case that this is fixed, feel free to reopen or create a new issue :)
