### ISSUE TITLE
createExpoConfig does not 

### ISSUE THREAD

**Issue by Cyberax** [expo/expo#29594]
### Minimal reproducible example

https://github.com/Cyberax/app-config-repro

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Expo build process does not update the generated `app.config` during the build. Steps to reproduce:

1. `npm install` then `npm run start`
2. Press `a` to build an Android app.
3. Observe the `Scheme: repro` text field in the emulator. 
4. Try to change the `scheme` setting in `app.json` to anything else (e.g. `repro2`). The change will NOT be picked up, even if you restart the Metro server and rebuild the app.

Workaround: manually delete the generated file `node_modules/expo-constants/android/build/generated/assets/expo-constants/app.config`

I traced the issue to https://github.com/expo/expo/blob/main/packages/expo-constants/scripts/get-app-config-android.gradle . It can't detect that the config changes, so the `app.config` never gets rebuilt.

Suggested solution: run the `createExpoConfig` target unconditionally during every build.

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.2.26 - /opt/homebrew/bin/bash
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 3.6.4 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.11
      react: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by Kudo** [comment]
hi there! sorry for this hassle but after changing app.json you should better to run prebuild again or at least try clean build. it is the same when you run `./gradlew :app:assembleRelease`, changing your App.tsx and re-run `./gradlew :app:assembleRelease` will still have the old cached bundle without the updated js changes.

**Comment by Cyberax** [comment]
Can you document this in the expo-constants docs perhaps? This took me a day to debug, and it's definitely not friendly to new users.

**Comment by Kudo** [comment]
it's not just expo-constants. changing scheme from your example, it will actually pull different value to AndroidManfiest.xml and create different intent-filters. that's why i recommended to re-run prebuild.

we are open for contributions. feel free to create a pr to revise the doc that makes sense to you. much appreciated!

**Comment by Cyberax** [comment]
I think I'm missing something here. I'm using React.Native app, not an Expo app, so it's not using prebuild.

I'm trying to document the steps required, and as I see it, there's no way to signal that the config needs regeneration. Other than by blowing away the entire `node_modules` directory and repopulating it from scratch.
