### ISSUE TITLE
Upgrade expo, can not scan QR code to test on IOS/Android devices

### ISSUE THREAD

**Issue by huynhquocmy** [expo/expo#296]
Hi guys,

After I upgrade expo version, both client on mobile app and expo XDE, I can not scan QR code, always get this error message:
```No experience found at exp://jv-k2w.myname.....```
I did not change anything on my code till last success test.
I tried to uninstall and reinstall both mobile app and desktop exp app.
Please help.

**Comment by brentvatne** [comment]
hi there! are you on a different wifi connection than before? or perhaps tethering? I ran into a similar problem earlier today while tethering but haven't been able to reproduce outside of that situation

**Comment by huynhquocmy** [comment]
Thanks @brentvatne, I tried switch wifi and it's working now. Still not sure what was problem.
Thanks again.

**Comment by dikaiosune** [comment]
Glad this worked out!
