### ISSUE TITLE
[ios][sensors] Setting NSMotionUsageDescription even if not required

### ISSUE THREAD

**Issue by jkaufman** [expo/expo#29618]
### Minimal reproducible example

https://github.com/jkaufman/expo-sensors-nsmotionusagedescription

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Expo-Sensors config plugin adds NSMotionUsageDescription and the documentation describes it as required. However, per [Apple's documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/nsmotionusagedescription):

This key is required if your app uses APIs that access the device’s motion data, including [CMSensorRecorder](https://developer.apple.com/documentation/coremotion/cmsensorrecorder), [CMPedometer](https://developer.apple.com/documentation/coremotion/cmpedometer), [CMMotionActivityManager](https://developer.apple.com/documentation/coremotion/cmmotionactivitymanager), and [CMMovementDisorderManager](https://developer.apple.com/documentation/coremotion/cmmovementdisordermanager).

Of Expo-Sensors' capabilities, only pedometer and barometer access these APIs.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/username/.rvm/gems/ruby-3.2.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0, 34.0.0
        System Images: android-28 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.11 => 51.0.11
      react: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
hi there! this is currently required because if the code includes certain symbols that require this permission usage description, then the store will reject your submissions if you do not include it. similarly, if you call that code without the permission then it will crash the app. we could take an approach similar to https://github.com/expo/expo/pull/28006 to resolve this

**Comment by jkaufman** [comment]
Good call out, than you. Yes, that's ideal.

**Comment by jkaufman** [comment]
Now this is interesting. I tried removing the string from my app config and omitting the config plugin. When I submitted to TestFlight, it did not complain that the build contained symbols that require a usage description.
