### ISSUE TITLE
expo-notifications background task with registerTaskAsync not working as expected

### ISSUE THREAD

**Issue by mgscreativa** [expo/expo#29622]
### Minimal reproducible example

https://github.com/mgscreativa/expo-notifications-test/

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

As suggested here https://github.com/expo/expo/issues/28656#issuecomment-2159040149 @brentvatne, @douglowder, @codelica, @nakedgun I'm opening a new issue for this background task behaviour, hope it can be smashed as the one mentioned before.

Well, as I suspected, I think the **registerTaskAsync** is working weirdly!, Just updated my test repo here https://github.com/mgscreativa/expo-notifications-test/ to re enable background notifications (without need to tap notification popup as documented here https://github.com/expo/expo/tree/main/packages/expo-notifications#handling-incoming-notifications-when-the-app-is-not-in-the-foreground-not-supported-in-expo-go).

As stated here https://github.com/mgscreativa/expo-notifications-test/blob/24ac789df7c7b27dff469871f1668f1c44e2b18e/App.tsx#L141, if the app is in background It should console log the received notification, if not, just inform that the app is not in background state.

Testing it a bit, if the app is in foreground and I send a notification, I get the correct skipping message :

```
06-10 13:59:36.104  9480 10005 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: App in active state.
06-10 13:59:36.105  9480 10005 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: App not in background state, skipping task.
```

But if app is in background and I send a notification, nothing happens nor gets logged, **but** it should at least log
```
I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: App in background state.
```

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.3 (Virginia)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ~51.0.11 => 51.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 9.2.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by douglowder** [comment]
Tracking this in ENG-12467.

**Comment by douglowder** [comment]
Testing today indicates that this is working as expected, using expo 51.0.11, expo-task-manager 11.8.2, expo-notifications 0.28.9.

My test code:

```tsx
import { defineTask } from 'expo-task-manager';
import { registerTaskAsync } from 'expo-notifications';

// Background task
// https://github.com/expo/expo/tree/main/packages/expo-notifications#handling-incoming-notifications-when-the-app-is-not-in-the-foreground-not-supported-in-expo-go
const BACKGROUND_NOTIFICATION_TASK = 'BACKGROUND-NOTIFICATION-TASK';
defineTask(BACKGROUND_NOTIFICATION_TASK, ({ data, error }) => {
  console.log(
    `${Platform.OS} BACKGROUND-NOTIFICATION-TASK: App in ${AppState.currentState} state.`,
  );

  if (error) {
    console.log(
      `${Platform.OS} BACKGROUND-NOTIFICATION-TASK: Error! ${JSON.stringify(
        error,
      )}`,
    );

    return;
  }

  if (AppState.currentState.match(/inactive|background/) === null) {
    console.log(
      `${Platform.OS} BACKGROUND-NOTIFICATION-TASK: App not in background state, skipping task.`,
    );

    return;
  }

  console.log(
    `${
      Platform.OS
    } BACKGROUND-NOTIFICATION-TASK: Received a notification in the background! ${JSON.stringify(
      data,
      null,
      2,
    )}`,
  );
});

registerTaskAsync(BACKGROUND_NOTIFICATION_TASK)
  .then(() => {
    console.log(
      `Notifications.registerTaskAsync success: ${BACKGROUND_NOTIFICATION_TASK}`,
    );
  })
  .catch((reason) => {
    console.log(`Notifications registerTaskAsync failed: ${reason}`);
  });

```

Logcat results on the client when app is in foreground and then in background:

```
06-12 12:46:56.689 26375 26588 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: App in active state.
06-12 12:46:56.689 26375 26588 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: App not in background state, skipping task.
06-12 12:46:56.699 26375 26588 I ReactNativeJS: android saw notification 
06-12 12:46:59.609 26375 26588 I ReactNativeJS: { dataIsReady: true }
06-12 12:46:59.973 26375 26588 I ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
06-12 12:47:04.477 26375 26588 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: App in background state.
06-12 12:47:04.478 26375 26588 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: Received a notification in the background! {
06-12 12:47:04.478 26375 26588 I ReactNativeJS:   "notification": {
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "originalPriority": 2,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "sentTime": 1718221624586,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "notification": null,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "data": {
06-12 12:47:04.478 26375 26588 I ReactNativeJS:       "message": "",
06-12 12:47:04.478 26375 26588 I ReactNativeJS:       "title": "",
06-12 12:47:04.478 26375 26588 I ReactNativeJS:       "body": "{\"someLocalData\":\"goes here\"}",
06-12 12:47:04.478 26375 26588 I ReactNativeJS:       "scopeKey": "@brents/microfoam",
06-12 12:47:04.478 26375 26588 I ReactNativeJS:       "experienceId": "@brents/microfoam",
06-12 12:47:04.478 26375 26588 I ReactNativeJS:       "projectId": "f19296df-44bd-482a-90bb-2af254c6ac42"
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     },
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "to": null,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "ttl": 0,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "collapseKey": null,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "messageType": null,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "priority": 2,
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "from": "697867774365",
06-12 12:47:04.478 26375 26588 I ReactNativeJS:     "messageId": "0:1718221624594356%b46fc6eaf9fd7ecd"
06-12 12:47:04.478 26375 26588 I ReactNativeJS:   }
06-12 12:47:04.478 26375 26588 I ReactNativeJS: }
```

**Comment by mgscreativa** [comment]
Great, will test and let you know

**Comment by milk717** [comment]
I'm experiencing the same problem. I'm using Android 14 version to test background work. Looking at the [official Android document](https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions), it looks like the background work has changed since Android 14 version. I'm guessing this might not work. I'm a web developer and I don't know much about Android and RN, so I just made a prediction, so please know my hypothesis might be wrong.

**Comment by douglowder** [comment]
@milk717 I'm testing with Android 14 (Samsung phone) and background tasks are working for me with expo-notifications 0.28.9.

**Comment by milk717** [comment]
> @milk717 I'm testing with Android 14 (Samsung phone) and background tasks are working for me with expo-notifications 0.28.9.

I've been struggling with an issue for 3 weeks and need some assistance.

### Issue Summary:
- I have completed all push notification settings. All logic for obtaining permissions from users, receiving Expo push tokens, and sending push notifications to those tokens have been tested successfully.

- I registered a background task using the Task Manager. I used the code provided above for registering the task.

- I ran the app using prebuild to work as a standalone app, not on top of Expo Go. I observed the changes through Logcat in Android Studio.

However, despite these settings, the background task only works in the foreground. Below is a Logcat history from when I received a push notification while the app was on, to when I shut down the app and sent a push notification. The Task Manager seems to only work in the foreground.

```csharp
2024-06-13 21:33:38.502 26545-26821 FirebaseMessaging       com.sampleapp.android             W  Unable to log event: analytics library is missing
2024-06-13 21:33:38.504 26545-26821 FirebaseMessaging       com.sampleapp.android             W  Unable to log event: analytics library is missing
2024-06-13 21:33:38.516 26545-26545 TaskService             com.sampleapp.android             I  Handling job with task name 'BACKGROUND-NOTIFICATION-TASK' for app with scoping identifier 'com.sampleapp.android'.
2024-06-13 21:33:38.524 26545-26659 ReactNativeJS           com.sampleapp.android             I  android BACKGROUND-NOTIFICATION-TASK: App in active state.
2024-06-13 21:33:38.524 26545-26659 ReactNativeJS           com.sampleapp.android             I  android BACKGROUND-NOTIFICATION-TASK: App not in background state, skipping task.
2024-06-13 21:33:38.526 26545-26655 TaskService             com.sampleapp.android             I  Finished task 'BACKGROUND-NOTIFICATION-TASK' with eventId '68be647d-a423-4ccf-a84d-3eac889a396a'.
2024-06-13 21:33:39.741 26545-26545 ViewRootIm...nActivity] com.sampleapp.android             I  MSG_WINDOW_FOCUS_CHANGED 0 1
2024-06-13 21:33:40.122 26545-26545 SensorManager           com.sampleapp.android             D  unregisterListener
2024-06-13 21:33:40.130 26545-26659 ReactNativeJNI          com.sampleapp.android             I  Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
2024-06-13 21:33:40.131 26545-26545 ViewRootIm...nActivity] com.sampleapp.android             I  handleAppVisibility mAppVisible=true visible=false
2024-06-13 21:33:40.132 26545-26545 ViewRootIm...nActivity] com.sampleapp.android             I  stopped(true) old=false
2024-06-13 21:33:40.138 26545-26545 InputTransport          com.sampleapp.android             D  Input channel destroyed: 'ClientS', fd=207
2024-06-13 21:33:40.159 26545-26616 OpenGLRenderer          com.sampleapp.android             D  setSurface called with nullptr
2024-06-13 21:33:40.159 26545-26616 OpenGLRenderer          com.sampleapp.android             D  setSurface() destroyed EGLSurface
2024-06-13 21:33:40.159 26545-26616 OpenGLRenderer          com.sampleapp.android             D  destroyEglSurface
2024-06-13 21:33:40.167 26545-26545 ViewRootIm...nActivity] com.sampleapp.android             I  Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=4 res=0x5 s={false 0} ch=false fn=-1
2024-06-13 21:33:40.171  2055-3285  WindowManager           system_server                        E  win=Window{126a786 u0 com.sampleapp.android/com.sampleapp.android.MainActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5867 com.android.server.wm.ActivityRecord.destroySurfaces:5848 com.android.server.wm.ActivityRecord.notifyAppStopped:5912 com.android.server.wm.ActivityRecord.activityStopped:6554 com.android.server.wm.ActivityClientController.activityStopped:254 android.app.IActivityClientController$Stub.onTransact:596 com.android.server.wm.ActivityClientController.onTransact:130
---------------------------- PROCESS ENDED (26545) for package com.sampleapp.android ----------------------------
2024-06-13 21:33:43.810 26910-26910 USNET                   pid-26910                            E  USNET: appName: com.sampleapp.android
---------------------------- PROCESS STARTED (26910) for package com.sampleapp.android ----------------------------
2024-06-13 21:33:44.347 26910-26910 NetworkSecurityConfig   com.sampleapp.android             D  No Network Security Config specified, using platform default
2024-06-13 21:33:44.576 26910-26910 FirebaseApp             com.sampleapp.android             I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
2024-06-13 21:33:44.607 26910-26910 FirebaseInitProvider    com.sampleapp.android             I  FirebaseApp initialization successful
2024-06-13 21:33:44.608 26910-26910 ReactNativeFirebaseApp  com.sampleapp.android             D  received application context.
2024-06-13 21:33:44.632 26910-26910 ActivityThread          com.sampleapp.android             D  handleBindApplication() --
2024-06-13 21:33:44.641 26910-26910 app.android             com.sampleapp.android             W  Accessing hidden method Ldalvik/system/BaseDexClassLoader;->getLdLibraryPath()Ljava/lang/String; (unsupported,core-platform-api, reflection, allowed)
2024-06-13 21:33:44.729 26910-26910 SoLoader                com.sampleapp.android             V  Init SoLoader delegate
2024-06-13 21:33:44.758 26910-26948 FirebaseMessaging       com.sampleapp.android             W  Unable to log event: analytics library is missing
2024-06-13 21:33:44.767 26910-26948 FirebaseMessaging       com.sampleapp.android             W  Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
2024-06-13 21:33:44.778 26910-26948 Compatibil...geReporter com.sampleapp.android             D  Compat change id reported: 160794467; UID 10345; state: ENABLED
```
Do I need to change the native code or modify the AndroidManifest.xml file for background operation? I've read the official documentation, but I haven't found anything like that.
Is there anything I missed? I'd appreciate it if you could let me know.

**Comment by mgscreativa** [comment]
Hi @douglowder sorry but as stated by @milk717 my tests failed too.

The line `06-13 12:40:01.055 11390 11439 I ReactNativeJS: android Response received through responseListener [NotificationResponseReceivedListener] {` indicates that I tapped the notification popup, but after waiting a little while to see if the background task got fired.

Just updated my test repo here https://github.com/mgscreativa/expo-notifications-test/ with updated expo and expo-dev-client packages 

```
06-13 12:39:39.679 11390 11439 I ReactNativeJS: Running "main
06-13 12:39:39.690 11390 11439 I ReactNativeJS: android Getting Expo Token with registerForPushNotificationsAsync
06-13 12:39:39.690 11390 11439 I ReactNativeJS: android Set channel default setNotificationChannelAsync
06-13 12:39:39.691 11390 11439 I ReactNativeJS: android Creating notificationListener
06-13 12:39:39.691 11390 11439 I ReactNativeJS: android Creating responseListener
06-13 12:39:39.691 11390 11439 I ReactNativeJS: android added listeners
06-13 12:39:39.691 11390 11439 I ReactNativeJS: android lastNotificationResponse is undefined or null [useLastNotificationResponse] undefined
06-13 12:39:39.692 11390 11439 I ReactNativeJS: android Notifications.registerTaskAsync success: BACKGROUND-NOTIFICATION-TASK
06-13 12:39:39.693 11390 11439 I ReactNativeJS: android App state changed to active
06-13 12:39:39.741 11390 11439 I ReactNativeJS: android lastNotificationResponse is undefined or null [useLastNotificationResponse] null
06-13 12:39:40.091 11390 11439 I ReactNativeJS: android Got Expo push token ExponentPushToken[_fqw17FiJrxi5FGkbkFo7o]
06-13 12:39:45.694 11390 11439 I ReactNativeJS: android App state changed to background
06-13 12:39:46.272 11390 11439 I ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
06-13 12:39:56.624 11390 11506 W FirebaseMessaging: Unable to log event: analytics library is missing
06-13 12:40:01.055 11390 11439 I ReactNativeJS: android Response received through responseListener [NotificationResponseReceivedListener] {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:   "notification": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:     "request": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       "trigger": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "channelId": null,
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "type": "push"
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       "content": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "title": "📱 Test Background",
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "body": "Test for app in Background state",
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "data": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:           "msgId": "0db795c654e9e79cfdd751e633ff9416",
06-13 12:40:01.055 11390 11439 I ReactNativeJS:           "link": "https://www.google.com.ar/"
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         }
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       "identifier": "0:1718293196575438%3a7b0fdf3a7b0fdf"
06-13 12:40:01.055 11390 11439 I ReactNativeJS:     },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:     "date": 1718293196566
06-13 12:40:01.055 11390 11439 I ReactNativeJS:   },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:   "actionIdentifier": "expo.modules.notifications.actions.DEFAULT"
06-13 12:40:01.055 11390 11439 I ReactNativeJS: }
06-13 12:40:01.055 11390 11439 I ReactNativeJS: android Got notification from lastNotificationResponse [useLastNotificationResponse] {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:   "notification": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:     "request": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       "trigger": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "channelId": null,
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "type": "push"
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       "content": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "title": "📱 Test Background",
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "body": "Test for app in Background state",
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         "data": {
06-13 12:40:01.055 11390 11439 I ReactNativeJS:           "msgId": "0db795c654e9e79cfdd751e633ff9416",
06-13 12:40:01.055 11390 11439 I ReactNativeJS:           "link": "https://www.google.com.ar/"
06-13 12:40:01.055 11390 11439 I ReactNativeJS:         }
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:       "identifier": "0:1718293196575438%3a7b0fdf3a7b0fdf"
06-13 12:40:01.055 11390 11439 I ReactNativeJS:     },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:     "date": 1718293196566
06-13 12:40:01.055 11390 11439 I ReactNativeJS:   },
06-13 12:40:01.055 11390 11439 I ReactNativeJS:   "actionIdentifier": "expo.modules.notifications.actions.DEFAULT"
06-13 12:40:01.055 11390 11439 I ReactNativeJS: }
06-13 12:40:01.058 11390 11439 I ReactNativeJS: android App state changed to active
```

**Comment by mgscreativa** [comment]
In Android 14 virtual device got the same

```
06-13 16:03:35.684  5982  6018 I ReactNativeJS: Running "main
06-13 16:03:35.705  5982  6018 I ReactNativeJS: android Getting Expo Token with registerForPushNotificationsAsync
06-13 16:03:35.706  5982  6018 I ReactNativeJS: android Set channel default setNotificationChannelAsync
06-13 16:03:35.707  5982  6018 I ReactNativeJS: android Creating notificationListener
06-13 16:03:35.707  5982  6018 I ReactNativeJS: android Creating responseListener
06-13 16:03:35.707  5982  6018 I ReactNativeJS: android added listeners
06-13 16:03:35.708  5982  6018 I ReactNativeJS: android lastNotificationResponse is undefined or null [useLastNotificationResponse] undefined
06-13 16:03:35.709  5982  6018 I ReactNativeJS: android Notifications.registerTaskAsync success: BACKGROUND-NOTIFICATION-TASK
06-13 16:03:35.710  5982  6018 I ReactNativeJS: android App state changed to active
06-13 16:03:35.720  5982  6018 I ReactNativeJS: android lastNotificationResponse is undefined or null [useLastNotificationResponse] null
06-13 16:03:36.122  5982  6018 I ReactNativeJS: android Got Expo push token ExponentPushToken[PL2EzCDZFb5fhetXswRz9y]
06-13 16:03:36.985  5982  6018 I ReactNativeJS: android App state changed to background
06-13 16:03:37.006  5982  6018 I ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
06-13 16:03:49.812  5982  6064 W FirebaseMessaging: Unable to log event: analytics library is missing
06-13 16:04:09.507  5982  6018 I ReactNativeJS: android Response received through responseListener [NotificationResponseReceivedListener] {

```

**Comment by douglowder** [comment]
You are sending a "data-only" notification to get the background task to work? I found that if you send a "normal" notification with title, etc., it will not trigger the background task. 

https://docs.expo.dev/versions/latest/sdk/notifications/#background-notifications

Here is the code I'm using that does work to send the data-only notifications. The request body only has the `to:` and `data:` fields.

```ts
async function sendPushNotification(print: GluegunPrint, config: Config) {
  const expoPushToken = config.data.pushTokens[0]
  const message = {
    to: expoPushToken,
    data: { someLocalData: 'goes here' },
  }
  const useFCMv1 = config.data.useFcmV1

  const request = useFCMv1 ? 'true' : 'false'

  print.debug(`Sending message ${JSON.stringify(message, null, 2)}`)

  const response = await fetch(
    `https://exp.host/--/api/v2/push/send?useFcmV1=${request}`,
    {
      method: 'POST',
      headers: {
        // Authorization: 'Bearer 80261fd9-9e7d-45c7-b8aa-9ddcb0ca782d',
        Accept: 'application/json',
        'Accept-encoding': 'gzip, deflate',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(message),
    }
  )

  const readResponse = (response: Response) => response.json()
  const json = await readResponse(response)
  print.debug(`Response JSON: ${JSON.stringify(json, null, 2)}`)
}
```

**Comment by mgscreativa** [comment]
Great!, this is my payload so I guess that's the bug needed to fix, _getting normal notifications in background tasks_

```
    messages.push({
        to: pushToken,
        title: '\ud83d\udcf1 Test Background',
        body: 'Test for app in Background state',
        data: {
            msgId: '0db795c654e9e79cfdd751e633ff9416',
            link: 'https:\/\/www.google.com.ar\/',
        },
        sound: 'default',
    });
```

Succedded with data only notification

06-13 14:05:56.930 19530 19600 I ReactNativeJS: Running "main
06-13 14:05:56.943 19530 19600 I ReactNativeJS: android Getting Expo Token with registerForPushNotificationsAsync
06-13 14:05:56.943 19530 19600 I ReactNativeJS: android Set channel default setNotificationChannelAsync
06-13 14:05:56.944 19530 19600 I ReactNativeJS: android Creating notificationListener
06-13 14:05:56.945 19530 19600 I ReactNativeJS: android Creating responseListener
06-13 14:05:56.945 19530 19600 I ReactNativeJS: android added listeners
06-13 14:05:56.946 19530 19600 I ReactNativeJS: android lastNotificationResponse is undefined or null [useLastNotificationResponse] undefined
06-13 14:05:56.947 19530 19600 I ReactNativeJS: android Notifications.registerTaskAsync success: BACKGROUND-NOTIFICATION-TASK
06-13 14:05:56.950 19530 19600 I ReactNativeJS: android App state changed to active
06-13 14:05:57.001 19530 19600 I ReactNativeJS: android lastNotificationResponse is undefined or null [useLastNotificationResponse] null
06-13 14:05:57.463 19530 19600 I ReactNativeJS: android Got Expo push token ExponentPushToken[_fqw17FiJrxi5FGkbkFo7o]
06-13 14:05:59.689 19530 19600 I ReactNativeJS: android App state changed to background
06-13 14:06:00.252 19530 19600 I ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
06-13 14:06:06.658 19530 19600 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: App in background state.
06-13 14:06:06.659 19530 19600 I ReactNativeJS: android BACKGROUND-NOTIFICATION-TASK: Received a notification in the background! {
06-13 14:06:06.659 19530 19600 I ReactNativeJS:   "notification": {
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "originalPriority": 2,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "sentTime": 1718298366314,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "notification": null,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "data": {
06-13 14:06:06.659 19530 19600 I ReactNativeJS:       "message": "",
06-13 14:06:06.659 19530 19600 I ReactNativeJS:       "title": "",
06-13 14:06:06.659 19530 19600 I ReactNativeJS:       "body": "{\"someLocalData\":\"goes here\"}",
06-13 14:06:06.659 19530 19600 I ReactNativeJS:       "scopeKey": "@mgscreativa/expo-notifications-test",
06-13 14:06:06.659 19530 19600 I ReactNativeJS:       "experienceId": "@mgscreativa/expo-notifications-test",
06-13 14:06:06.659 19530 19600 I ReactNativeJS:       "projectId": "7adfdc0f-6331-4225-9ee5-9a55084c3ad3"
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     },
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "to": null,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "ttl": 0,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "collapseKey": null,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "messageType": null,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "priority": 2,
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "from": "678546989030",
06-13 14:06:06.659 19530 19600 I ReactNativeJS:     "messageId": "0:1718298366326791%3a7b0fdff9fd7ecd"
06-13 14:06:06.659 19530 19600 I ReactNativeJS:   }
06-13 14:06:06.659 19530 19600 I ReactNativeJS: }

**Comment by douglowder** [comment]
@mgscreativa I had thought that this was the intended behavior. I will check with @christopherwalter on that. If it turns out to be a bug, I will open a separate issue to fix it.

**Comment by douglowder** [comment]
@mgscreativa I agree that that is how things should work, but Firebase docs seem to indicate that data-only notifications are handled differently. https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages

**Comment by mgscreativa** [comment]
Ok, if there's a fancy requirement by firebase that block processing a notification in background with more data than the body, no problem, but if not, I think the notification payload should be processed as in any other app state, but again, only if it's possible.

**Comment by douglowder** [comment]
Thanks @mgscreativa -- further testing indicates that our native code for the background task only gets triggered for these special data-only payloads 😞 . So I'm not sure that there is much we can do on the Expo side.

As I recall, the special notifications for background tasks are specifically intended to wake up the app so it can make network requests to check for new data from a backend, and not intended to be user facing in any way (won't show up in the notification tray, for example).

**Comment by mgscreativa** [comment]
Ok, if that's the case, then that's the way it should be. I think that must be stated clearly in the documentation [here](https://github.com/expo/expo/tree/main/packages/expo-notifications#handling-incoming-notifications-when-the-app-is-not-in-the-foreground-not-supported-in-expo-go), because as it is today, it doesn't mention anything about the data only notification on Android.

**EXTRA**: Can you double check with the expo notification server maintainer the correct use of **"content-available": 1** for iOS background notifications? I mean, how we must send that variable in the payload, because there's a little confusion about that parameter. Currently I'm using:

```
  {
    "_contentAvailable": true
    "to": "ExponentPushToken[xxxxxxxxxxxxxxxx]",
    "title": "\ud83d\udcf1 Test Foreground",
    "body": "Test for app in foreground state",
    "data": {
      "msgId": "9e266ab5680ac2c7ae4aeb131f6f97eb",
      "link": "https:\/\/www.google.com.ar\/"
    },
    "priority": "default",
    "sound": "default",
    "channelId": "default",
    "mutableContent": false,
  }
```

But I don't know if it should be **"contentAvailable": true** (without the underscore) or **"content-available": 1**

**Comment by mgscreativa** [comment]
@douglowder Sorry to bother, but ¿can you double check with the expo notification server maintainer the correct use of **content-available**: 1 for **iOS** background notifications? I mean, how we must send that variable in the payload, because there's a little confusion about that parameter. Currently I'm using:

  {
    "_contentAvailable": true
    "to": "ExponentPushToken[xxxxxxxxxxxxxxxx]",
    "title": "\ud83d\udcf1 Test Foreground",
    "body": "Test for app in foreground state",
    "data": {
      "msgId": "9e266ab5680ac2c7ae4aeb131f6f97eb",
      "link": "https:\/\/www.google.com.ar\/"
    },
    "priority": "default",
    "sound": "default",
    "channelId": "default",
    "mutableContent": false,
  }

But I don't know if it should be **contentAvailable**: true (without the underscore) or **content-available**: 1

**Comment by douglowder** [comment]
@mgscreativa if sending to Expo server, you should use `"_contentAvailable": true` . I did some testing yesterday to confirm that.

**Comment by mgscreativa** [comment]
Can you add that in the docs somehow?

**Comment by kotsh23** [comment]
we can run custom music when background notification arrived

**Comment by jakemadash** [comment]
> @mgscreativa if sending to Expo server, you should use `"_contentAvailable": true` . I did some testing yesterday to confirm that.

I see that the SDK 50 docs still say "content-available": 1. Should I use that if I'm on Expo 50 or still "_contentAvailable": true?
