### ISSUE TITLE
[BUG] Expo Sqlite with typeorm BUG

### ISSUE THREAD

**Issue by JRBARROZ** [expo/expo#29621]
I'm using Typeorm With expo-sqlite, and i'm having a problem when i try to save, edit, delete any crud operations with typeorm, using  expo-sqlite as sdk, even if i enable Pragma Foreign Keys On, doesn't trigger and the app become unresponsive once try to use the database again:

In the minimum reproducible example:

- You will use yarn & yarn start and open on android
- After that you will be on Home, Profile and Settings menu main page, you go to *Profile*
- There will be a button "Press Me To Bug SQLITE WITH TYPEORM", once you press u can check the logs.

Modeling :

```jsx
@Entity("category")
export class Category {
@PrimaryColumn("uuid")
id!: string;

@Column("text")
name!: string;
}

@Entity("post")
export class Post {
@PrimaryColumn("uuid")
id!: string;

@Column("text")
title!: string;

@Column("text")
text!: string;

@Column("uuid", {
nullable: true,
})
category_id!: number;

@ManyToOne(() => Category, {})
@JoinTable({
joinColumn: "category_id",
})
categories!: Category[];
}
```

```jsx
console.log("PASSED_FROM_SAVE_0");
var post = await PostRepo.find();
console.log(post, "PASSED_FROM_FIND_1");

```

I'm trying to save inside the database without id, category_id, and other constraints not null.
but once i try it the insert is executed, but the find doesn't because the app stops on insert and throw errors. Does anyone knows how to know that ?

**Comment by danb4r** [comment]
For who ever bump into this bug, it is a TypeORM bug reported here: https://github.com/typeorm/typeorm/issues/10924

I had the same issue and executed the direct SQL code using expo-sqlite and it worked as expected:

```js
const db = SQLite.openDatabaseSync("money");
db.execSync("PRAGMA foreign_keys = ON");
console.log(db.runSync("PRAGMA foreign_keys"));
const result = db.runSync("DELETE FROM my_related_table WHERE id = ?", 2);
```

```sh
[Error: Call to function 'NativeStatement.finalizeSync' has been rejected.
→ Caused by: Error code ‼: FOREIGN KEY constraint failed]
```

I executed the same query with TypeORM query builder and also straight with my repo query object and both failed:

```js
const queryString = "DELETE FROM my_related_table WHERE id = 2";
const result = await this._repo.query(queryString);
```

Both ways DO NOT throw the FOREIGN KEY constraint violation error and any further request to the database using the current connection fails without any error. Very odd.
