### ISSUE TITLE
[notifications] badge does not "reset" when calling `setBadgeCountAsync(0)` on Android

### ISSUE THREAD

**Issue by haileyok** [expo/expo#29634]
### Minimal reproducible example

https://github.com/haileyok/expo-notifications-badge-repro

### What platform(s) does this occur on?

Android - Samsung models, have not tested on others yet

### Did you reproduce this issue in a development build?

Yes

### Summary

On Android - at least on some devices, tested on Samsung - calling `setBadgeCountAsync(0)` does not reset the badge. Calling `setBadgeCountAsync()` and supplying any other positive number updates the badge correctly, but resetting it does not.

I tried using both `applyCount` and `resetCount` from `ShortcutBadger` but neither worked - even though they both return `true` (or simply does not throw when using the `applyCountOrThrow` that this package currently uses).

https://github.com/expo/expo/assets/153161762/635e546d-0ee7-4c25-ae85-d62d6d0087f6

I managed to get this to work with a little patch, although I don't know if it's a viable solution. I'm fine with PRing if it is, though I don't know what other consequences it might come with.

```diff
diff --git a/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/badge/BadgeHelper.kt b/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/badge/BadgeHelper.kt
index 63a46c5..22322f3 100644
--- a/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/badge/BadgeHelper.kt
+++ b/node_modules/expo-notifications/android/src/main/java/expo/modules/notifications/badge/BadgeHelper.kt
@@ -12,7 +12,12 @@ object BadgeHelper {
 
   fun setBadgeCount(context: Context, badgeCount: Int): Boolean {
     return try {
-      ShortcutBadger.applyCountOrThrow(context.applicationContext, badgeCount)
+      if (badgeCount == 0) {
+        val notificationManager = context.getSystemService(Context.NOTIFICATION_SERVICE) as android.app.NotificationManager
+        notificationManager.cancelAll()
+      } else {
+        ShortcutBadger.applyCountOrThrow(context.applicationContext, badgeCount)
+      }
       BadgeHelper.badgeCount = badgeCount
       true
     } catch (e: ShortcutBadgeException) {
```

https://github.com/expo/expo/assets/153161762/4e3d217f-42fe-48c6-aa03-0c9a0e302fab

### Repro Steps

- Checkout the repro and prebuild
- Run on Android
- Request permissions, and schedule a notification. As soon as you press the schedule button, minimize the app.
- After two seconds the notification should have badged the app. Return to the app and press the clear badge button.
- Note that the badge is not cleared.

To see the patch working, remove `.disabled` from the patch in `./patches` and do the same, except note that after pressing the clear badge button, the badge does in fact reset.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.1/bin/yarn
      npm: 10.4.0 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/hailey/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.12 => 51.0.12 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by iM-GeeKy** [comment]
@haileyok I think this is related to https://github.com/expo/expo/issues/13311#issuecomment-2032549885. I had the same issue and had to apply a workaround similar to the comment.
