### ISSUE TITLE
[expo-updates] CommandError: Must specify --private-key-path argument to sign development manifest for requested code signing key

### ISSUE THREAD

**Issue by momenthana** [expo/expo#29630]
### Minimal reproducible example

https://github.com/expo/custom-expo-updates-server

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

After the migration from expo 50 to 51, operating the example on https://github.com/expo/custom-expo-updates-server results in an error.

```json
    "updates": {
      "url": "http://localhost:3000/api/manifest",
      "enabled": true,
      "fallbackToCacheTimeout": 30000,
      "codeSigningCertificate": "./code-signing/certificate.pem",
      "codeSigningMetadata": {
        "keyid": "main",
        "alg": "rsa-v1_5-sha256"
      }
    },
```
It works when you disable it in the updates setting and remove the codeSigningCertificate field.
If you change enabled to false, the same error is displayed if the key field remains.
```json
    "updates": {
      "url": "http://localhost:3000/api/manifest",
      "enabled": false,
      "fallbackToCacheTimeout": 30000,
      "codeSigningMetadata": {
        "keyid": "main",
        "alg": "rsa-v1_5-sha256"
      }
    },
```

![](https://github.com/expo/expo/assets/59823089/da5f08d3-e46e-46b5-a0db-d77f800de15a)

Both the ios project and the Android project have confirmed that the settings reflect well. The problem only occurs with expo51.
![](https://github.com/expo/expo/assets/59823089/f3d999e7-7802-4ad0-bebd-3125605d34bc)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - ~/Library/pnpm/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 29, 33, 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.12 => 51.0.12 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

**Comment by momenthana** [comment]
This issue is not reproduced in the clean build. I'm trying to see if this issue conflicts with other modules.

**Comment by momenthana** [comment]
@wschurman observed this problem. The problem only occurs in an environment that is installed with the expo-dev-client.

**Comment by momenthana** [comment]
@wschurman observed this problem. The problem only occurs in an environment that is installed with the expo-dev-client.

**Comment by momenthana** [comment]
```
    "android": "expo run:android",
    "ios": "expo run:ios --scheme",
```

@wschurman - Thank you for preparing for the investigation, what I used triggered the instructions in the package to work on a simulator or physical device. If this happens again, I'll try to reopen or track it.

**Comment by thtTNT** [comment]
@wschurman Kindly ask how to fix this, I met the same issue with SDK 51. Thank you!!!

**Comment by wschurman** [comment]
@thtTNT - can you please create a new issue with a minimal reproducible example? thanks!

**Comment by ludal** [comment]
@momenthana have you tried to add your code-signing/private-key.pem
and run : 
`npx expo start --private-key-path code-signing/private-key.pem`

**Comment by momenthana** [comment]
@ludal It hasn't been solved by previous attempts.
However, I solved it by building the ios project in the clean state, and separately, in the ARM Macbook, I changed the build only architecture setting of the pods dependency of the xcode to "no".
You are utilizing custom servers, disabling and using RSA encryption.
When used in an inactive state, the reproduction of the problem is completely resolved.

**Comment by chanphiromsok** [comment]
> [@momenthana](https://github.com/momenthana) have you tried to add your code-signing/private-key.pem and run : `npx expo start --private-key-path code-signing/private-key.pem`

this one work for me allow me to running in development
