### ISSUE TITLE
Failed to link source maps because the source map URL "index.android.bundle.packager.map" is corrupt: TypeError: Invalid URL

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#29656]
### Minimal reproducible example

https://github.com/thespacemanatee/source-map-repro

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

After updating to `expo@51.0.12` which depends on `@expo/metro-config@18.5.0`, we faced the following error:

```
Failed to link source maps because the source map URL "index.android.bundle.packager.map" is corrupt: TypeError: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:637:13)
    at Chunk.getAdjustedSourceMapUrl (/Users/thespacemanatee/Documents/GitHub/source-map-repro/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:335:22)
    at Chunk.serializeToCode (/Users/thespacemanatee/Documents/GitHub/source-map-repro/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:357:26)
    at Chunk.serializeToAssetsAsync (/Users/thespacemanatee/Documents/GitHub/source-map-repro/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:386:25)
    at /Users/thespacemanatee/Documents/GitHub/source-map-repro/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:615:25
    at Array.map (<anonymous>)
    at serializeChunksAsync (/Users/thespacemanatee/Documents/GitHub/source-map-repro/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:613:17)
    at graphToSerialAssetsAsync (/Users/thespacemanatee/Documents/GitHub/source-map-repro/node_modules/@expo/metro-config/src/serializer/serializeChunks.ts:150:26)
    at /Users/thespacemanatee/Documents/GitHub/source-map-repro/node_modules/@expo/metro-config/src/serializer/withExpoSerializers.ts:263:50 {
  input: '/_expo/static/js/android/AppEntry-c48a6064bd4fa39bfab2eb477ae36e82.js.map',
  code: 'ERR_INVALID_URL'
}
```

I believe this issue is due to this #29463. It doesn't seem to account for build flavours.

Please look at the repro for an easy reproduction with a new expo project.

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.asdf/installs/nodejs/18.18.0/bin/node
      Yarn: 1.22.21 - ~/.asdf/installs/nodejs/18.18.0/bin/yarn
      npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/thespacemanatee/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 23, 26, 29, 30, 31, 32, 33, 34
        Build Tools: 26.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0
        System Images: android-26 | Google APIs ARM 64 v8a, android-26 | Google APIs Intel x86_64 Atom, android-26 | Google Play Intel x86 Atom, android-27 | ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-33 | Desktop ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-34 | Google Play Tablet ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.12 => 51.0.12 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by razzfox** [comment]
I upgraded to `expo@51.0.12` using `expo@latest` and I see this error when running local eas build for Android. The local eas build hangs indefinitely.

**Comment by brentvatne** [comment]
@thespacemanatee @razzfox - can you try the latest version of the expo pkg and see if that resolves your issue? I've reverted https://github.com/expo/expo/pull/29463 in expo@51.0.13

**Comment by foyarash** [comment]
I can confirm that build is working on latest expo

**Comment by sajorahasan** [comment]
I am facing the same issue with the latest expo version 50.0.13

I had cleared node modules and cache but still facing the issue so reverted back to 50.0.11 temporarily to generate the build.

Screenshot of the error:
![Screenshot 2024-06-12 at 4 23 41 PM](https://github.com/expo/expo/assets/19198921/2746af6a-627b-4350-b7f8-406cb961fb33)

**Comment by reak998** [comment]
Same error here after upgrading to 50.0.13. debug build fine but this error show on the release build.

**Comment by razzfox** [comment]
> @thespacemanatee @razzfox - can you try the latest version of the expo pkg and see if that resolves your issue? I've reverted #29463 in expo@51.0.13

Same error after running `npx expo install expo@latest --fix` or `npx expo install expo@51.0.13 --fix`, cleaning `node_modules` between installs.

**Comment by rehwinkel** [comment]
I also just encountered this error while running `npx expo run android --variant release`. Using expo `51.0.13`.

**Comment by chhornponleu** [comment]
I got same error. The issue also caused Xcode Archive freeze. Upgrade to expo **51.0.14** finally got it fixed

**Comment by mym0404** [comment]
I can confirm that `51.0.14` would fix this.

**Comment by EvanBacon** [comment]
@chhornponleu the warning/issue will not cause any builds to fail or freeze as far as I can reproduce. It's a benign warning. Could you please provide more info regarding your project freezing so we don't accidentally reintroduce the bug.

**Comment by thespacemanatee** [comment]
@EvanBacon the repro is in the original issue. I also had builds freeze on my company project, but in the repro I provided, the build did not freeze even though the error did show up.

**Comment by dominictobias-bullish** [comment]
I have no idea what this error means. What URL is invalid?

```
% npx expo-doctor
TypeError: Error reading Expo config at <...>/app.config.ts:

Invalid URL
```
