### ISSUE TITLE
New arch + bridgeless crash: -[EXVideoView contentView]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by chrisnojima** [expo/expo#29665]
### Minimal reproducible example

sorry

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

Hi,
I don't have a small repro (yet) but I can 100% this crash. On a bare workflow on iOS I have a flatlist (chat thread) with some expo-av videos. If i scroll up fast it will crash out on me. Only happens on new arch / bridgeless
![Screenshot 2024-06-11 at 5 20 55 PM](https://github.com/expo/expo/assets/516435/137ecd2a-a226-4eb7-98cc-7a0c0f5d1d0a)

![Screenshot 2024-06-11 at 5 21 14 PM](https://github.com/expo/expo/assets/516435/f112ffa5-98d1-4242-bf70-cfd3d6cea3c9)
![Screenshot 2024-06-11 at 5 21 23 PM](https://github.com/expo/expo/assets/516435/0972cd7a-a282-452c-b9d9-4295d83b6d58)
![Screenshot 2024-06-11 at 5 21 33 PM](https://github.com/expo/expo/assets/516435/eeb1893d-c087-403d-87bc-6656dca39d55)

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.2.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.7.0 - /usr/local/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        Android NDK: 23.1.7779620
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: 51.0.12 => 51.0.12 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: 0.19.12 => 0.19.12 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✖ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following scripts in package.json conflict with the contents of node_modules/.bin: prettier, tsc.

(node:46439) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/netinfo@11.3.2 - expected version: 11.3.1
  @react-native-picker/picker@2.7.7 - expected version: 2.7.5
  lottie-react-native@6.7.2 - expected version: 6.7.0
  react-native-reanimated@3.13.0-rc.1 - expected version: ~3.10.1
  react-native-safe-area-context@4.10.4 - expected version: 4.10.1
  react-native-webview@13.10.3 - expected version: 13.8.6
  @types/react@18.3.3 - expected version: ~18.2.79
  @types/react-dom@18.3.0 - expected version: ~18.2.25
  typescript@5.4.5 - expected version: ~5.3.3

**Comment by brentvatne** [comment]
thanks for the report! please create an issue when you've had a chance to create a minimal reproducible example and we'll get right on investigating

**Comment by djMax** [comment]
(this is happening to us too. I'm trying to switch to expo-video from expo-av, but that is failing for different reasons)

**Comment by janicduplessis** [comment]
Opened https://github.com/expo/expo/issues/29996 with a repo

**Comment by naytun** [comment]
In my case, I need to rebuild iOS app with `npx expo run:ios --device`.  It is fixed after that.
