### ISSUE TITLE
Expo Camera Component returns a zoomed preview on iOS?

### ISSUE THREAD

**Issue by jesse-wang** [expo/expo#2967]
Does anyone else find that the Expo Camera component's preview is more zoomed than the system's native Camera's? It shows like a 1.1 or 1.2x zoomed in preview.

**Comment by joehdodd** [comment]
I'm having the same issue on iOS using Expo `32.0.0`.

**Comment by lc3t35** [comment]
any update in sdk35 ?

**Comment by ksairi** [comment]
@lc3t35 still broken in sdk 35

**Comment by brentvatne** [comment]
consolidating into https://github.com/expo/expo/issues/5437
