### ISSUE TITLE
Keep getting Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

### ISSUE THREAD

**Issue by kejedi** [expo/expo#29674]
### Summary

I keep getting this warning in the terminal when the app bundles/rebundles:

> Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

### What platform(s) does this occur on?

iOS

### SDK Version

51.0.12

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.2.0 - /opt/homebrew/bin/node
      npm: 10.7.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.12 => 51.0.12 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Minimal reproducible example

im running expo on my m1 macbook pro through vscode terminal

i am using the latest version of npm, expo, watchman etc. 

i have also updated all my brew packages before doing this.

**Comment by Jankaz2** [comment]
Hi, any solution for that?

**Comment by PedroFigueiraRuivo** [comment]
Hi Jankaz2. Lower the node version. Version ˆ22 generates this error

**Comment by taufiq-dev** [comment]
What if I use bun?
