### ISSUE TITLE
SDK Upgrade hiccups on android device

### ISSUE THREAD

**Issue by ipr0310** [expo/expo#29693]
### Minimal reproducible example
It is an open source project
https://github.com/signum-network/signum-mobile-wallet

**This is the branch of the app, updated to version 51:**
https://github.com/signum-network/signum-mobile-wallet/tree/task/update-sdk-51

**How to reproduce the warning**

1. This is an open source app, you do not need any third party dependencies, just install dependencies, then run the development client
2. Open the app, accept the terms of service
3. Set the app pin
4. Once you are on the account wizard screen, you'll see the warning

![image](https://github.com/expo/expo/assets/35440957/211e0bc2-ddb5-4121-93ca-dfa17e94d513)

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I just try to upgrade the SDK from 50 to 51

![image](https://github.com/expo/expo/assets/35440957/52aeb635-9482-4ad4-9470-f5c3875eb447)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11330709
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by ipr0310** [comment]
Ok, let me explain in a more simpliefied way:

This is an **open source** app, you do not need any third party dependencies

1- Clone the repository, specifically from this branch: 
https://github.com/signum-network/signum-mobile-wallet/tree/task/update-sdk-51
`This branch contains the app updated to expo SDK 51`

2- Install dependencies

3- Run the development client

4- Once the app is open, you must accept the terms of service

5- Set any random PIN

6- Once you set the PIN, you will be transitioned to the account wizard screen, you'll see the warning as i shared on the screenshot before

@brentvatne @aleqsio If you need help with anything, I will gladly help

**Comment by ipr0310** [comment]
That's exactly the steps i took in order to get the warning

**Comment by brentvatne** [comment]
hey @ipr0310 - please reproduce the issue in a new project. your project has a large number of unrelated files, code, and dependencies. there are ~80 direct dependencies listed in your project.

**Comment by ipr0310** [comment]
hey @brentvatne, thanks for sharing these resources, applied the `divide and conquer` method

I found out the warning is shown because of the Expo vector-icon component

The expo icons works nicely on SDK 50, but on SDK 51 it shows the warning

The icon is not even rendered at all on Android:

This is the picture, where the app is on `Expo SDK 51.0.14`
If i remove the icon, the warning does not appear anymore

![image](https://github.com/expo/expo/assets/35440957/983191da-619b-43ba-a3e2-d6c457d40fb6)

---

This is the picture, where the app is on `Expo SDK 50.0.19`

![image](https://github.com/expo/expo/assets/35440957/35053370-4cc6-4bdc-98cc-686d695aef8e)

On Expo SDK 50, the warning is never shown

**Comment by ipr0310** [comment]
@brentvatne @aleqsio I'm tagging here because you may forget this ticket, which is currently closed
I hope this example serves well as a reference on why the warning is showing

**Comment by aleqsio** [comment]
Hi @ipr0310! Can you try to make a minimal reproduction? If I can reproduce your issue by cloning and running a project with a minimal set of dependencies (ideally only the vector icons package in this case) I can try to fix the issue quickly.

**Comment by ipr0310** [comment]
Sharing progress... i started an expo app from scratch with expo router, SQLite, drizzle, reanimated
The icon was shown successfully, looks like the issue may be on the way the app is bundling the multiple dependencies, will share any news if it is related to an expo dependency.
