### ISSUE TITLE
sh: expo: command not found

### ISSUE THREAD

**Issue by ezrra** [expo/expo#29706]
### Summary

I can't run my app using `npx expo start` command in the project root folder in a new environment.
```
sh: expo: command not found
```

I'm using Expo 50 version in my app, yarn, and nvm with Node 18 version.
I removed Expo-Cli globally deprecated version https://www.npmjs.com/package/expo-cli in my development environment.

This is my scripts in `package.json`:
```
"scripts": {
    "start": "expo start",
    "eas-build-pre-install": "chmod +x ./pre-install.sh && ./pre-install.sh",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "husky:install": "husky install",
    "format": "lint-staged",
    "lint": "eslint *.js **/*.js src/**/*.js --fix",
    "test": "jest",
    "test:watch": "jest --watch"
  },
```

Did I forget to add something to run my application?

### SDK Version

50

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.3/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^10.0.0 => 10.0.2 
      expo: ^50.0.19 => 50.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.12 
    Expo Workflow: managed

### Minimal reproducible example

```
sh: expo: command not found
```

<img width="1053" alt="Screenshot 2024-06-12 at 10 57 53 a m" src="https://github.com/expo/expo/assets/3309297/dcd177cf-17c3-43d1-b877-ad26c4aa7a2a">

**Comment by ezrra** [comment]
I can run the project using:

Added
```
export PATH="./node_modules/.bin:$PATH"
```
In my `.zshrc` file.

The problem was: My environment couldn't find the expo command in `node_modules/.bin/expo`.

**Comment by onyedikachi23** [comment]
**Update PATH Environment Variable**: Ensure that your PATH environment variable includes the directory where npm installs global packages. You can check the npm global install path with:
```bash
npm config get prefix
```

For example, this is how I did it in mine:

1. **Edit the Bash Configuration File**:

```bash
nano ~/.bashrc
```

2. **Make Your Changes**: Add the following line to the file to update your PATH:

```bash
export PATH=$PATH:/home/onyedikachi23/.npm-global/bin
```

3. **Save and Exit**:
press `Ctrl + O` to save the file, then `Ctrl + X` to exit.

4. **Reload the Configuration**: Apply the changes by running:
source ~/.bashrc

Then run again:

```bash
npx expo start
```
