### ISSUE TITLE
Wrong files used in workspace with multiple expo apps

### ISSUE THREAD

**Issue by RWOverdijk** [expo/expo#29700]
### Minimal reproducible example

https://github.com/RWOverdijk/monorepo-issue/tree/main

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I have a bun workspace project with 2 expo apps. apps/customer and apps/company. Completely fresh expo projects, nothing goofy. When running the apps/company project it is using files from apps/customer instead. The hot reload kicks in when I change files in either project, but the only files used, for both projects, is the customer one.

The repro repo is very bare. Default everything, just a workspace with 2 apps.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
      npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/spiderclam/.rvm/rubies/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    Expo Workflow: managed

**Comment by RWOverdijk** [comment]
After some poor attempt at debugging I think I found the problem to be somewhere in metro. There's something called a metroContext that returns the wrong files. I tried messing with the metro config but I don't fully understand it and so anything I come up with is bound to be wrong anyway.

I also tried using the second metro config as [documented here](https://docs.expo.dev/guides/monorepos/#common-issues) but this makes it so it no longer loads any app files and shows the screen that says:

> Welcome to [Expo](https://github.com/expo/expo-router/)
Start by creating a file
in the app directory.

The only way for it to load anything (albeit the wrong directory) seems to be by including the monorepo root in watchFolders.

I have no idea if any of this is useful information but I tried 😅

**Comment by RWOverdijk** [comment]
I am now 99% sure the problem is cache related.

Simply adding -c to the end of the run command (`EXPO_USE_METRO_WORKSPACE_ROOT=1 expo start --web -c`) makes it work, albeit super slowly because it needs to clear a cache. So whatever it is, the cache key seems to be the monorepo root and not the app root.

**Comment by RWOverdijk** [comment]
@byCedric Oh good! I found the correct issue then 😄 Well, sort of. Not as well as you did haha. Thanks for confirming I am not losing my mind <3

**Comment by byCedric** [comment]
I had a head start of debugging Expo/Metro-related things 😄

And yeah, Atlas is great, it helps us track these issues down fast!

**Comment by RWOverdijk** [comment]
@byCedric I am curious about one thing though. If the solution is to trigger an invalidation, wouldn't it always be very slow? And if so, wouldn't it be better to make the cache key relative to the app instead?

Maybe it's a silly question but I had to ask 😅

**Comment by byCedric** [comment]
> wouldn't it be better to make the cache key relative to the app instead?

That's exactly what we are doing now in the fix: https://github.com/expo/expo/pull/29733. It's adding a `_expoRelativeProjectRoot` key, that's an empty string for normal projects, but uses **apps/what-ever** for monorepos.

We likely need to change how we generate/store the `require.context` modules though. I think it might be better to make this an actual true virtual module, that's not interacting with the transformer cache at all.

**Comment by RWOverdijk** [comment]
Oh I see, so it's not invalidating, as much as it is not hitting the cache because it's more explicit of a key? If so, that's good actually, because then the apps can still share caches from the node modules and shared packages in the same monorepo keeping the cache smaller while still being exclusive to the apps.

**Comment by byCedric** [comment]
Yep, exactly! I'm also adding an e2e test to prevent this from happening again, specific for monorepos in #29735. But it might take a bit for that to land.
