### ISSUE TITLE
Build Failure with Expo SDK 51 on Android

### ISSUE THREAD

**Issue by YuriiLutsykSPRO** [expo/expo#29705]
### Minimal reproducible example

Unfortunally 

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

Android build fails with errors. This occurs when running npx expo prebuild.

Script '/Users/macbook/projects/finity/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 408

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-file-system'.
   > Failed to notify project evaluation listener.
      > compileSdkVersion is not specified. Please add it to build.gradle
      > Could not get unknown property 'release' for SoftwareComponent container of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
      Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo-router: ~3.5.16 => 3.4.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.1 
    Expo Workflow: bare

### Expo Doctor Diagnostics

Didn't find any issues with the project!

**Comment by supagu** [comment]
I hit the same problem building android on my mac. I have avoided upgrading to expo 51 for now.

**Comment by arapocket** [comment]
Same problem, why is the expo team silent on this?

**Comment by arapocket** [comment]
Was able to get rid of that message by deleting node_modules and reinstalling.
