### ISSUE TITLE
blocker: SHA-1 for file .expo/__generated__/AppEntry.js is not computed

### ISSUE THREAD

**Issue by zetaron** [expo/expo#2970]
### Environment

```plain
Expo CLI 2.6.12 evironment info:
  System:
    OS: macOS 10.14.1
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 8.5.0 - /var/folders/2k/xv2xh80s2xgdcygqs21trrx00000gn/T/yarn--1544616660972-0.5345639070895056/node
    Yarn: 1.12.3 - /var/folders/2k/xv2xh80s2xgdcygqs21trrx00000gn/T/yarn--1544616660972-0.5345639070895056/yarn
    npm: 5.3.0 - ~/.cache/nvm/versions/node/v8.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    expo: ^31.0.2 => 31.0.6
    react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
```

Our app's target is: **iOS**

### Steps to Reproduce / Reproducible Demo

1. `brew install git yarn nvm watchman`
2. `git clone https://github.com/aidminutes/error-reproduction-demo.git`
3. `yarn install`
4. `cd applications/demo-app`
5. `yarn ios`
6. 💥💥 BOOM!!! 💥💥 Error

    Your Terminal should contain the following log output:

```plain
[11:18:57] SHA-1 for file /Users/fst/src/github.com/aidminutes/error-reproduction-demo/applications/demo-app/.expo/__generated__/AppEntry.js is not computed
Building JavaScript bundle [                                                                                                    ] 0%
```

> If you want to take a look at a more indepth reproduction including our execution logs and steps we took to try and solve this on our own, head over to [the reproduction repo](https://github.com/aidminutes/error-reproduction-demo).

### Expected Behavior

We expceted that the App would render either inside the iOS Simulator or inside the Expo App on an iPad.

### Actual Behavior

The dev-server process logs the following and the App would render the attached error screen.

```plain
[11:18:57] SHA-1 for file /Users/fst/src/github.com/aidminutes/error-reproduction-demo/applications/demo-app/.expo/__generated__/AppEntry.js is not computed
Building JavaScript bundle [                                                                                                    ] 0%
```

<img width="709" alt="screenshot 2018-12-12 at 13 54 16" src="https://user-images.githubusercontent.com/419419/49871133-afae3c80-fe15-11e8-8dd6-3aac0d98f641.png">

**Comment by ide** [comment]
Do you have the generated entry point file? It sounds like starting there might prove fruitful.

expo-yarn-workspaces is supported only in the expo/expo repo because it requires careful setup and React Native and Metro are fragile to debug. If you are interested in simulating that setup, you’ll need to be comfortable debugging it as your dependencies like RN change over time.

As a pointer, I’d recommend checking out the expo/expo repo, making sure you can load an app under “apps” (try the sandbox app), and working backwards to remove files.

**Comment by ide** [comment]
Do you have the RN submodule checked out? You need to do that first before running `yarn install` -- that could be the potential cause of that error you pasted.

**Comment by zetaron** [comment]
No I did not check that out 🤦, will try again first thing in the morning.




Get Outlook for Android







On Wed, Dec 12, 2018 at 11:56 PM +0100, "James Ide" <notifications@github.com> wrote:












Do you have the RN submodule checked out? You need to do that first before running yarn install -- that could be the potential cause of that error you pasted.

**Comment by vjpr** [comment]
Maybe related and with workaround: https://github.com/facebook/metro/issues/330

**Comment by ide** [comment]
I'm closing this issue since it sounds like it's happening because of something due to Metro and using a non-standard setup.
