### ISSUE TITLE
Relative Paths in "index" not working as expected with shared routes (doesn't stay within Stack)

### ISSUE THREAD

**Issue by samskinner32** [expo/expo#29708]
### Minimal reproducible example

https://github.com/samskinner32/sam-expo-router

### Which package manager are you using? (Yarn is recommended)

npm

### Summary

As far as I can tell, relative paths in expo-router are not working as I'd expect when placed within the `index` file and using shared routes. I have a fairly simple router layout where I have three tabs:
1. The starter expo page in tab 1
2. A "shop" stack in tab 2
3. An "account" stack in tab 3

Most screens will be intended to be shared between the "shop" and "account" tabs (e.g. you could view a Product via both screens), so they exist in a shared `(account,shop)` group. Screenshot of this folder layout below:
<img width="253" alt="image" src="https://github.com/expo/expo/assets/53786564/a240a62b-23df-4f1d-ba66-a0a707a38e6f">

The issue I am running into is that when I attempt to Link to a relative path from within the `(shop)/index` file (e.g. `<Link href="./category">Relative Category</Link>`, it is sending me to `(account)/category` instead of `(shop)/category`. I believe this is related to alphabetical ordering and it deciding on account vs shop.

I would expect the relative path link to stay within the current stack.

If I instead go a step deeper into my stack and do the relative path link from there, it works as expected. For example, if I am on `(shop)/category` to begin with and attempt to link to `./product`, it keeps me within the `(shop)` tab as I expect. So it seems to be an issue specifically with `index` files.

Please let me know if there's anything else I can provide, or if I am making a mistake somewhere.

Thanks!

**TO REPRODUCE**
Simply run the app (it's a basic expo starter project), navigate to the "Shop" tab and press each of the "Relative Category" and "Absolute Category" links and you will see different behavior between the two.

**RELEVANT CODE** in `/app/(tabs)/(shop)/index.tsx`
`<Link href="./category">Relative Category</Link>`
`<Link href="/(shop)/category">Absolute Category</Link>`

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.2 - /opt/homebrew/bin/node
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.11 => 51.0.11 
      expo-router: ~3.5.15 => 3.5.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.2.0
    Expo Workflow: managed

**Comment by samskinner32** [comment]
Just wanted to see if there are any thoughts on this from the team. Is this expected and there's a way I can work around it? Thanks so much.

Please do let me know if I can clarify anything further!

**Comment by tkrafael** [comment]
When using groups, navigation works correctly. My setup:
```
/app
/app/(tabs)/_layout.tsx // << bottom tabs, contains tab buttons, among them, there's (settings) group
/app/(tabs)/(settings)/_layout.tsx // << contains stack with two screens: index and (addresses)
/app/(tabs)/(settings)/(addresses)/_layout.tsx // << contains stack with screens to list, /configure and add addresses 

```
