### ISSUE TITLE
useLocalSearchParams() not working correctly when using experimental baseUrl functionality

### ISSUE THREAD

**Issue by mykhailodanilenko** [expo/expo#29716]
### Minimal reproducible example

https://github.com/mykhailodanilenko/router-issue-repro

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

There is a problem when using local search params together with the experimental `baseUrl` property on the web.
The issue manifests itself when you open a link with query params added, not if you navigate from another page.
Compare [https://mykhailodanilenko.github.io/router-issue-repro/explore?foo=bar](https://mykhailodanilenko.github.io/router-issue-repro/explore?foo=bar) and [https://no-baseurl--gorgeous-sherbet-c139f2.netlify.app/explore?foo=bar](https://no-baseurl--gorgeous-sherbet-c139f2.netlify.app/explore?foo=bar), in the first link the `baseUrl` is used since it is deployed to GH pages, in the second link a branch with no `baseUrl` is deployed. As seen in the console, the first link throws a typeError when trying to get params.

The issue seems to be located in the `useLinking` hook fork, specifically in the part where it `fast-deep-equal`'s the `focusedRoute` and `route` object. In case when there is no `baseUrl` the object reference is the same so the `a === b` condition in the `fast-deep-equal` package is true and there is no error.

However, when there is a `baseUrl` then the two objects do not share the same reference and `a === b` is false so the `fast-deep-equal` function goes on to a condition where it checks `a.valueOf()` against `b.valueOf()` where it throws a `TypeError` since `valueOf` is not a function for the `focusedRoute` object.

This patch temporarily resolved the issue in the project I am working on, however I do believe this is a band-aid and the issue is not in the `fast-deep-equal` package:
```
diff --git a/node_modules/fast-deep-equal/index.js b/node_modules/fast-deep-equal/index.js
index 30dd1ba..ed32125 100644
--- a/node_modules/fast-deep-equal/index.js
+++ b/node_modules/fast-deep-equal/index.js
@@ -22,7 +22,7 @@ module.exports = function equal(a, b) {


     if (a.constructor === RegExp) return a.source === b.source && a.flags === b.flags;
-    if (a.valueOf !== Object.prototype.valueOf) return a.valueOf() === b.valueOf();
+    if (a.valueOf !== Object.prototype.valueOf) return a.valueOf?.() === b.valueOf?.();
```

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 22.2.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.7.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
```

**Comment by NilsBaumgartner1994** [comment]
might be related to: https://github.com/expo/expo/issues/29297
and https://github.com/expo/expo/issues/29274
