### ISSUE TITLE
Presenting SMS modal pushes alert dialog to top left corner on iOS

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#2971]
Repro: https://snack.expo.io/@bacon/sms-video-tutorial

**Comment by bbarthec** [comment]
@EvanBacon your snack has no dialog-like component? What's your point here?

**Comment by EvanBacon** [comment]
<img width="1440" alt="screen shot 2018-12-14 at 12 32 16 am" src="https://user-images.githubusercontent.com/9664363/49992025-bcc34c80-ff37-11e8-86ac-84ed81ee7c81.png">

**Comment by esamelson** [comment]
original snack was missing some code, this has a better repro: https://snack.expo.io/@esamelson/sms-video-tutorial . It's possible it's still an issue on iOS 12 -- if someone can repro let's reopen. I wasn't able to repro this on iOS 13 so I'm going to close this.
