### ISSUE TITLE
Custom Local Fonts are not loaded with no internet connection

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#2972]
### Environment

```
[00:26:12] Generating diagnostics report...
[00:26:12] You can join our slack here: https://slack.expo.io/.

  Expo CLI 2.2.5 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.10.1 - ~/.nvm/versions/node/v9.10.1/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v9.10.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.0 => 31.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.2.5

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/brodanoel-690ff3a8-a733-493d-879f-eb0ed95a9aea.tar.gz
```
App Target: iOS and Android

```json
{
  "expo": {
    "name": "xxxx",
    "icon": "./src/styles/imgs/nofilter-icon.png",
    "splash": {
      "backgroundColor": "#000",
      "resizeMode": "cover",
      "image": "./src/styles/imgs/splash-screen-ph.png"
    },
    "version": "xxx",
    "slug": "xxxx",
    "sdkVersion": "31.0.0",
    "ios": {
      "buildNumber": "xxxx",
      "bundleIdentifier": "xxxxx",
      "config": {
        "googleMapsApiKey": "xxxxx-xxxx"
      },
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "xxxx"
      }
    },
    "android": {
      "versionCode": x,
      "package": "xxx",
      "config": {
        "googleMaps": {
          "apiKey": "xxx"
        }
      },
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
      ]
    }
  }
}
```

```json
{
  "name": "xxxx",
  "version": "xxxx",
  "private": true,
  "devDependencies": {
    "jest-expo": "^31.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^1.1.2",
    "@turf/center-median": "^6.0.1",
    "@turf/clusters": "^6.0.1",
    "@turf/clusters-dbscan": "^6.0.1",
    "expo": "^31.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz"
  }
}

```

### Steps to Reproduce
1. Download Montserrat font: https://fonts.google.com/specimen/Montserrat
2. Add Montserrat files into your app.
3. Load the fonts in your app. Example:
```js
Font.loadAsync({
  'montserrat-regular': require('./src/styles/fonts/Montserrat/Montserrat-Regular.ttf'),
  'montserrat-bold': require('./src/styles/fonts/Montserrat/Montserrat-Bold.ttf'),
  'montserrat-medium': require('./src/styles/fonts/Montserrat/Montserrat-Medium.ttf'),
});
```
4. Build the app. (If you already have this app created, built and installed in your phone, REMOVE IT, and build again)
5. Install the app (DO NOT OPEN IT!)
6. Swith your phone to "Airplane mode"
7. Open the App.
8. You'll see that fonts are not opened, and the `loadAsync` promise fails
9. Kill the app
10. Switch to "no airplane mode" again :)
11. Open your app with Internet connection
12. You gonna see fonts working well.
13. Restart app with no internet, and font's are going to still working well

### Expected Behavior
I'm not sure if this behavior is the expected behavior of every TTF fonts. I'm not sure. But, my expected behavior is to see the local font loaded

### Actual Behavior
Font is not loaded. It even fails the promise.

### Reproducible Demo
It's hard to get a reproducible demo, due to we nede to use the Airplane mode, and add local fonts.

Youtube video showing error:
https://www.youtube.com/watch?v=cxkJPCeWy7s
Steps made:
1. Remove app
2. Download app
3. Switch to airplane mode
4. Open app and show that fonts are not loaded (Don't check the SplashPage. Check the Navigation bar and the titles in Collection page)
5. kill app
6. Switch back to normal mode
7. Open app. Font's are there.

**Comment by ThibautGeriz** [comment]
Hi, I am facing the issue too. The app doesn't work offline event with the offline cache. Is there a known workaround?

**Comment by ThibautGeriz** [comment]
I am not sure if I had the same issue as BrodaNoel but I fixed mine.
Every asset is actually uploaded on Cloudfront as stated [here](https://blog.expo.io/under-the-hood-offline-assets-in-expo-98614adcf9e5). 
You need to add the path of your font in your`expo.assetBundlePatterns` as stated [here](https://docs.expo.io/versions/latest/workflow/configuration#assetbundlepatterns) and [here](https://docs.expo.io/versions/latest/guides/offline-support.html)

**Comment by BrodaNoel** [comment]
You are right, man. I didn't check the Offline Support.

Thanks!
