### ISSUE TITLE
[expo-media-library] No suitable URI request handler found for ph://

### ISSUE THREAD

**Issue by khushal87** [expo/expo#29741]
### Minimal reproducible example

https://github.com/khushal87/expo-media-library-bug

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

On iOS, when you load the assets using the `expo-media-library` and try to show them on the UI using React Native's `Image` component, the following error is thrown on expo `51`.

This issue is reproducible on versions `>=16.0.0` of `expo-media-library` and not below it with Expo 51.
![simulator_screenshot_111A0F24-6256-4ACA-93F3-D8017ACD89D0](https://github.com/expo/expo/assets/39884168/6c4386b7-cd3f-4d38-83e6-f146284f86cf)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/khushalagarwal/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14
      expo-router: ~3.5.16 => 3.5.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 7.6.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by khushal87** [comment]
Hey, @alanjhughes, here you go. 👋🏻

**Comment by aleqsio** [comment]
This seems like an Image issue instead of media library issue.

I can reproduce this, and can also fix it by using `expo-image` instead of react-native's Image.

**Comment by khushal87** [comment]
But they were working on <16.0.0 version of expo-media-library with ph:// links.

Although there is a slight difference:

The previous version 15.9.1 that I used returned URL as, ph://B84E8479-475C-4727-A4A4-B77AA9980897 while the version 16.0.3 is returning it as ph://B84E8479-475C-4727-A4A4-B77AA9980897/L0/001 which doesn't seem to work.

**Comment by khushal87** [comment]
I have a case where I cannot use expo-image, so making it work with default Image is the goal.

**Comment by nagisaando** [comment]
I might be missing something but actually I still see the error... 

`uri` that is generated by ` MediaLibrary.getAssetsAsync` is not accepted by `<Image>` from `React-native`

As a workaround, I needed to use `localUri` from `MediaLibrary.getAssetInfoAsync` (reference: https://github.com/facebook/react-native/issues/36136#issuecomment-2181326761)

However, I never needed to use `MediaLibrary.getAssetInfoAsync` before upgrading to Expo 51. 

This is the repo and it shows error and workaround https://github.com/nagisaando/image-bug

Environment 
```

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.74.2 => 0.74.2 
    Expo Workflow: managed
```

packages 

```
  "dependencies": {
    "expo": "~51.0.2",
    "expo-image-manipulator": "^12.0.5",
    "expo-media-library": "^16.0.4",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "^0.74.2"
  },
```

**Comment by alanjhughes** [comment]
@nagisaando if you are using expo go this won't work as it needs a new release

**Comment by nagisaando** [comment]
@alanjhughes Oh! thought I need to just upgrade expo-media-libary and expo-image-manipulator. Sorry for misunderstanding and thanks for clarifying! I will wait for the release!

**Comment by khushal87** [comment]
Hey @alanjhughes, this issue pops up again if I enable the new architecture for an expo app.


PFA the branch with new architecture code using expo-media-library version `16.0.4`, which supposedly fixed the issue for old architecture but still breaks for new architecture - https://github.com/khushal87/expo-media-library-bug/tree/new-architecture

**Comment by khushal87** [comment]
New issue for the above raised at #30116

**Comment by fadihanna123** [comment]
Same issue here and no fix yet after more than 6 months.

**Comment by coolsoftwaretyler** [comment]
@fadihanna123 - what version are you on? It looks like #33097 landed in `17.0.3`: https://github.com/expo/expo/blob/main/packages/expo-media-library/CHANGELOG.md#1703--2024-11-22

That should have fixed the problem, but if not, please let me know.

**Comment by fadihanna123** [comment]
> @fadihanna123 - what version are you on? It looks like #33097 landed in `17.0.3`: https://github.com/expo/expo/blob/main/packages/expo-media-library/CHANGELOG.md#1703--2024-11-22
> 
> That should have fixed the problem, but if not, please let me know.

After upgrading Expo to 52.0.23 and Expo Media Library to 17.0.4 got new warnings and errors:
```
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 INFO 
 💡 JavaScript logs will be removed from Metro in React Native 0.77! Please use React Native DevTools as your default tool. Tip: Type j in the terminal to open (requires Google Chrome or Microsoft Edge).
 (NOBRIDGE) ERROR  TypeError: Cannot read property 'ReactCurrentOwner' of undefined
 (NOBRIDGE) ERROR  TypeError: Cannot read property 'render' of undefined
```

**Comment by coolsoftwaretyler** [comment]
@fadihanna123 - what's the output of `npx expo-doctor`?

**Comment by fadihanna123** [comment]
This is the output:
```
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: @babel/core, @manypkg/cli, @typescript-eslint/eslint-plugin, @typescript-eslint/parser, eslint, husky, typescript
Advice:
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by coolsoftwaretyler** [comment]
@fadihanna123 - try running `npx expo install --fix`, then run a new development build and see if that fixes things up?

**Comment by fadihanna123** [comment]
After your suggested command.
This is the output after npx expo doctor:
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.80.5
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.5
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.5
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

One or more checks failed, indicating possible issues with the project.

**Comment by itshenryx** [comment]
This issue is still prevalent. Its quite weird actually, ( I'm using expo go ) , it will give me the error, and then it lets me pick images, granted the images are all invisible, and only become visible after they've been added as attachments

**Comment by FahadSarfraz** [comment]
> This issue is still prevalent. Its quite weird actually, ( I'm using expo go ) , it will give me the error, and then it lets me pick images, granted the images are all invisible, and only become visible after they've been added as attachments

Having same issue, did you solved the problem ?
