### ISSUE TITLE
useWindowDimensions does not work for Expo 51

### ISSUE THREAD

**Issue by GHEAD1802** [expo/expo#29746]
### Summary

I have create new app using epxo 51 Template and i am trying to implement usewindowDimensions to keep my container inside screen responsive when screen rotates, but it does not work 

### SDK Version

51

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 9.1.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/GHEAD1802/Test-APP.git

**Comment by gerwld** [comment]
Same issue here. On 50.0 it works

**Comment by jtmaddux** [comment]
Since we still see this problem and I cannot re-open this issue, I opened a new one to try and get developer help as i presume they don't track comments in closed issues:
https://github.com/expo/expo/issues/32024
