### ISSUE TITLE
FileSystem.downloadAsync/FileSystem.createDownloadResumable.downloadAsync doesn't close requests on Android/Snack

### ISSUE THREAD

**Issue by JeffBobbo** [expo/expo#2976]
### Environment

  Expo CLI 2.3.12 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
    npmPackages:
      expo: ^31.0.2 => 31.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.3.12

### Steps to Reproduce

On Android and in Snack, requests made using FileSystem.downloadAsync aren't closed when the download is complete and hang around. If the remote server then blocks requests because too many are open, the app red screens in native code, or crashes with no information (only observed on Android).

1. Setup to download multiple files from a remote server, can be multiple simultaneous or sequential downloads
2. Watch the requests build on the remote server (e.g., by using `netstat -nputwc`
3. Wait until the requests eventually close (Snack?) or kill expo (Android).

### Expected Behavior

Requests closed when the download is complete.

### Actual Behavior

On Android (OnePlus 6) multiple requests were left open in the TIME_WAIT status (netstat), on iPhone (iPhone 6S) the requests are closed properly (no more than a few over the maximum parallel downloads observed).
![image](https://user-images.githubusercontent.com/5425481/49934708-0162cf80-fec7-11e8-966b-dcbeaae767a4.png)
Image is of output when run on physical Android device.
### Reproducible Demo

The demo uses 100 text files with random characters in, split into 5 queues. On iPhone running from expo the number of requests at once will hover around 6-8, but on Android the number of requests is excessive (see above screenshot).
https://snack.expo.io/@innershed/YW5kcm

**Comment by zetxy** [comment]
I am experiencing the same issue. Application on my android phone / emulator crashes when downloading larger amount of files.

**Comment by JeffBobbo** [comment]
Some testing again today shows that this is also an issue with `createDownloadResumable`. Same Snack, just with this:
```js
      const resumable = FileSystem.createDownloadResumable(url + file, destination);
      await resumable.downloadAsync();
      //const res = await FileSystem.downloadAsync(url + file, destination);
```

**Comment by Irvollo** [comment]
I'm experiencing the same issue. It's on `createDownloadResumable` and `downloadAsync` .
I had a very few successful downloads, when trying to download +300 files from firebase. But It looks that almost every time it crashes or takes an insanely amount of time to download the files.

**Comment by dipesh** [comment]
Is there any work around for this?

**Comment by JeffBobbo** [comment]
I implemented a version with the same function signature but just used axios and Buffer. Still relies on `Expo.FileSystem` for writing to file. This has only been tested with images, though, as that was my use case.

```js
import axios from 'axios';

import {FileSystem} from 'expo';

var md5 = require('md5');
var Buffer = require('buffer/').Buffer;

async function downloadAsync(uri, fileUri, options = {'md5': false}) {
    let response = await axios.get(uri, {responseType: 'arraybuffer'});
    await FileSystem.writeAsStringAsync(
        fileUri,
        Buffer.from(response.data, 'binary').toString('base64'),
        {encoding: FileSystem.EncodingTypes.Base64}
    );

    let ret = {
        uri: fileUri,
        status: response.status,
        headers: response.headers,
    };
    if (options.md5)
        ret.md5 = md5(response.data);
    return ret;
}

export {downloadAsync};
```
