### ISSUE TITLE
[docs] Missing ratio prop in expo-camera

### ISSUE THREAD

**Issue by 0x6D70** [expo/expo#29761]
### Summary

The docs of the the ``expo-camera`` module mention that on Android it is essential to set the ratio prop (description of the ``takePictureAsync`` function).
But the ``CameraPictureOptions`` don't have a ratio prop. Where should this ratio prop be set?

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/camera/

**Comment by amandeepmittal** [comment]
Hi @0x6D70, the ratio prop has been removed so the description of `takePictureAsync` is outdated and inaccurate. It'll be fixed  https://github.com/expo/expo/pull/29802.
