### ISSUE TITLE
Undocumented behavioral difference with flex 

### ISSUE THREAD

**Issue by devklick** [expo/expo#29776]
### Minimal reproducible example

https://github.com/devklick/test-react-native-expo-flex

### What platform(s) does this occur on?

Android, Web

### Did you reproduce this issue in a development build?

Yes

### Summary

I have observed unexpected behavior while working with the flex layout. This does not appear to be documented, and I cannot be certain whether it is a bug in the docs or the SDK (I'm assuming the latter).

In the following examples, note the position (or absence) of the `X`, which is a flex item. This flex item, and its sibling (the Field Name box), are positioned within an outer flex box. 

[This CodeSandbox](https://codesandbox.io/p/sandbox/react-typescript-forked-qkkghc) demonstrates how this flex example works in CSS on the web:

![image](https://github.com/expo/expo/assets/58235000/8e11668d-7574-476a-b022-ebf1fe39b118)

The [linked Github MRP]() demonstrates how this same example behaves in react-native

**Android**
![image](https://github.com/expo/expo/assets/58235000/f81910d2-7009-4830-ac17-2b21fe0f9efd)

**Web**
![image](https://github.com/expo/expo/assets/58235000/f5a8c7d3-8653-4b3e-9456-32d9b0bc823a)

As per [the docs](https://reactnative.dev/docs/flexbox):
>Flexbox works the same way in React Native as it does in CSS on the web, with a few exceptions:
>- `flexDirection` defaulting to `column` instead of `row`
>- `alignContent` defaulting to `flex-start` instead of `stretch`
>- `flexShrink` defaulting to `0` instead of `1`
>- the `flex` parameter only supporting a single number

As such, the only differences in CSS between my CodeSandbox link and the MRP expo project:
- where CodeSandbox example has no `alignContent` property, expo example has `alignContent: "stretch"` to apply the the default
- where CodeSandbox example has no `flexShrink` property, expo example has `flexShrink: 1` to apply the the default
- `boxSizing` removed in expo example as not required in react-native

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.1 (Vera)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by Kudo** [comment]
hi there! thanks for having this issue. this is more toward Yoga's problem. could you open the issue to https://github.com/facebook/yoga/issues?

as far as i can tell, it looks more about `width: 100%` definition. in react-native, it respects to parent's 100%, but it turns out chrome will only count for remaining space. if you could have the information for css spec to define this clearly, that might help meta to have a roadmap to fix the problem. thanks!
