### ISSUE TITLE
TaskManager not working on iOS

### ISSUE THREAD

**Issue by kiorq** [expo/expo#29783]
### Summary

I have an expo app with expo-router, and after endless testing and documentation reading, i don't see a way to to registerTasks in the background. TaskManager docs mention that it doesn't load views and i have a hunch that includes all the files in app/*, including the the layout.ts

I've tried defining tasks for both background fetch and remote notifications, and not seem to pick up on the builds i've testing on my iOS iphone.

Could we get docs added showing how to work around this? At least showing us what get's loading in the background and how can we inject our defineTask calls while using expo router.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/task-manager/#taskmanagerdefinetaskttaskname-taskexecutor

**Comment by kiorq** [comment]
Closing, as i added more details in #29792

**Comment by kiorq** [comment]
Re-opening, something is wrong here and i'm not sure what

**Comment by Cosmin-Ciolacu** [comment]
Still not work in IOS, But on android it works well. 
I have the following scenario:

- An user creates some data on my app. He can creates that objects without internet connection.
- In the background task I check if the user has internet connection and if it has, I send data created offline to my API.  
this feature it s very important for me to work on IOS. Again, on Android it works perfectly.
I will appreciate any help.
