### ISSUE TITLE
Modal presentation not working?

### ISSUE THREAD

**Issue by stesvis** [expo/expo#29797]
### Minimal reproducible example

https://github.com/stesvis/expo-router-sample

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I just created a brand new expo app with navigation, this is just out of the box without any modifications.
There is one page that should open as a modal: `<Stack.Screen name="modal" options={{ presentation: 'modal' }} />` but instead it just opens like a regular page.

I would expect that the page would present as a modal, like claimed here
https://docs.expo.dev/router/advanced/modals/

[expo-modal.webm](https://github.com/expo/expo/assets/6062684/b44d03f1-9ca9-4058-974c-7685dd3530ff)

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9862592
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
```

**Comment by hollanderbart** [comment]
Because the example shows an iOS device, and you're testing it on an Android, is the reason for the difference in behaviour. For Android there is no real concept of modals, as in iOS. I do see they are working to implement a similar behaviour for Android: https://github.com/software-mansion/react-native-screens/issues/1650
