### ISSUE TITLE
autolinking exclude is not working properly and addin unnecessary permissions in android manifest

### ISSUE THREAD

**Issue by dhruv-00** [expo/expo#29795]
### Minimal reproducible example

https://github.com/dhruv-00/expo-autolinking-issue

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I tried creating new expo project there is this depedency expo-file-system which is included automatically and it is adding permissions which are not required in the app
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

I followed the steps mentioned here 
https://docs.expo.dev/bare/installing-expo-modules/#excluding-specific-modules-from-autolinking

but after adding in the exclude and running clean bun install and clean prebuild it is still not excluding the depencies and the android manifest is still including those permissions

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
      npm: 10.2.5 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/myapple/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14
      expo-router: ~3.5.16 => 3.5.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
hi there! if you mean `INTERNET`, `READ_EXTERNAL_STORAGE`, or `WRITE_EXTERNAL_STORAGE` permissions, they are pulled by the default template (not from expo-file-system). i believe autolinking exclusion works fine still.
to exclude these permissions from the default template, you could use the [`blockedPermissions` in app.json](https://docs.expo.dev/guides/permissions/#android) to remove them. thanks!
