### ISSUE TITLE
TaskManager not compatible with expo-router

### ISSUE THREAD

**Issue by kiorq** [expo/expo#29792]
### Minimal reproducible example

https://github.com/kiorq/expo-router-task-manager

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I’ve tried implementing background fetch and remote (data-only) notifications in my Expo app using the expo router, but neither seems to work. While push notifications with title and body display fine, data-only notifications don’t trigger the TaskManager. Background fetch tasks also don’t run. I suspect this is because the routing setup doesn’t load the layout files in the background, preventing task definition. I also can't seem to find away to load code, like defining tasks, in the entry of app. I suspect this would make it work if could do so.

I’ve tried defining tasks globally and in useEffect, but no luck. 

I've added a simple expo example that tests this out only using background fetch.  What i observed is, trigging the task in a simulator, using Time Profile, successfully executes the task. However, making a build and testing on my iOS iphone 14 pro, seems to not work at all.

### Environment

Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.0
    Expo Workflow: bare

**Comment by kiorq** [comment]
further debugging, i've attempted to override the "entry" property in package js, with a local main.ts file, that import the expo-router/entry, along with defining functions at this level as well.

```
// main.ts
import "expo-router/entry";
...
// call TaskManager.define here
```

I haven't got much success with BackgroundFetch yet, but it's only been 30 minutes so far, despite configuring the task to run every 15 minutes. From the docs, it seems like iOS truly decides how and when this happens, so i'll wait a bit longer and even task with remote notification as well.

**Comment by kiorq** [comment]
After 4 hours of app running in the background, nothing happens. I'm back to square 0 with this.

**Comment by kiorq** [comment]
Okay, i think TaskManager for iOS may not be working at all for me. The below repo is does not use expo router, just has a App.js file with all the code inside of it. Tested it last night and did not work. I must be doing something wrong but I can't tell, this seems correct based on the documents?

https://github.com/kiorq/expo-task-manager

**Comment by Miloshinjo** [comment]
did you find any solution for this? 
I had a case where it worked (talking about IOS) all night and morning, and then stopped in the afternoon, no tasks were logged in the background... Especially after making a build and uploading to Firebase.
