### ISSUE TITLE
@expo/fingerprint fails to source Expo Config that uses ts-node/register

### ISSUE THREAD

**Issue by a-gierczak** [expo/expo#29793]
### Minimal reproducible example

https://github.com/a-gierczak/expo-fingerprint-tsnode-bug-repro

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Hi! First of all, thanks for this tool. This will save us a lot of headaches when figuring out native deps!

In our project, we use app.config.js that calls `require('ts-node/register')` and then imports the actual config from `app.config.ts`.

 Now, when you run `npx @expo/fingerprint <path_to_project>` it will fail to source the Expo config of that project, resulting in the following error:
```
Cannot get Expo config from an Expo project - node /some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/fingerprint/build/sourcer/ExpoConfigLoader.js /some/path/projects/expo-fingerprint-tsnode-bug-repro /var/folders/15/kgpd_b2939s94bmr_7rkdwl80000gn/T/.fingerprintignore exited with non-zero code: 1:  Error: node /some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/fingerprint/build/sourcer/ExpoConfigLoader.js /some/path/projects/expo-fingerprint-tsnode-bug-repro /var/folders/15/kgpd_b2939s94bmr_7rkdwl80000gn/T/.fingerprintignore exited with non-zero code: 1
    at ChildProcess.completionListener (/some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:652:26)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:537:28)
    at Pipe.<anonymous> (node:net:747:14)
    ...
    at spawnAsync (/some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at getExpoConfigSourcesAsync (/some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/fingerprint/build/sourcer/Expo.js:28:60)
    at async Promise.all (index 2)
    at async getHashSourcesAsync (/some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/fingerprint/build/sourcer/Sourcer.js:15:21)
    at async Object.createFingerprintAsync (/some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/fingerprint/build/Fingerprint.js:14:21)
    at async /some/path/.npm/_npx/63a736e22ce36c79/node_modules/@expo/fingerprint/bin/cli.js:44:27
```

It doesn't show the actual error, which is related to TS module resolution, but when you look into the source, it seems like [this line](https://github.com/expo/expo/blob/main/packages/%40expo/fingerprint/src/sourcer/Expo.ts#L34) might be the culprit. `ExpoConfigLoader` is spawned with `cwd` set to the sourcer's path. Because of this `ts-node` cannot find `tsconfig.json`, resulting in TS errors when trying to load the config.

Changing the `cwd` to the project root sounds like an obvious fix, but I'm not sure what the full consequences would be, so I'd appreciate any guidance here. If you think this might be the solution, then I can prepare a PR, lmk!

### Environment

  ```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.1
        System Images: android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.13 => 51.0.13
      expo-router: ~3.5.16 => 3.5.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 7.6.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
hi there! changing cwd to the projectRoot sounds good to me. please help to send me a pr if you feel comfortable about that. thanks for investigating the issue.

**Comment by a-gierczak** [comment]
hey @Kudo, here's the PR, thanks! https://github.com/expo/expo/pull/29810

**Comment by Kudo** [comment]
close via #29810. thanks @a-gierczak again for having that pr.
