### ISSUE TITLE
Detect exp.json

### ISSUE THREAD

**Issue by morenoh149** [expo/expo#298]
I've added an exp.json file next to my package.json like so
```
{
  "name": "Name",
  "slug": "name",
  "sdkVersion": "17.0.0",
  "orientation": "portrait"
}
```
but my app still rotates. Thoughts? I'm developing on an Android.

**Comment by btk** [comment]
It recently changed to `app.json`. If you are using the v18 `exp.json` changed into `app.json`. Try changing the name of it, also you should update the sdkVersion property in that file. 

See: https://blog.expo.io/expo-sdk-v18-0-0-is-now-available-38e62305283

**Comment by morenoh149** [comment]
will the docs be updated?

**Comment by btk** [comment]
As I see, v18 docs are updated as it is. https://docs.expo.io/versions/v18.0.0/guides/configuration.html#content

If you think its unclear I think you should pull request it.

**Comment by morenoh149** [comment]
oh I see the docs were updated with the v18 release.
Is there any place I can track releases?
https://github.com/expo/expo/releases doesn't seem like a good place to track releases

**Comment by btk** [comment]
@morenoh149 Your best bet is to follow their medium blog i guess. https://blog.expo.io/
