### ISSUE TITLE
DEV mode never turns on even if it is set to be on, and another issue

### ISSUE THREAD

**Issue by dogsiskela** [expo/expo#2980]
First, whenever i set development mode with 'p' key or through DevTools, on the app the features aren't present. I cant shake for the Dev options to open and it doesn't update.

Second, I created another project and when i run it with expo start // npm start it uses the code of the first project for some reason?

> [00:46:55] Error: 'assets/fonts/SpaceMono-Regular.ttf' could not be found, because 'assets/fonts' is not a subdirectory of any of the roots  ('C:\Users\aleks\xx', 'C:\Users\aleks\xx')
[00:46:55]     at C:\Users\aleks\xx\node_modules\metro\src\Assets.js:189:11
[00:46:55]     at Generator.next (<anonymous>)
[00:46:55]     at step (C:\Users\aleks\xx\node_modules\metro\src\Assets.js:326:347)
[00:46:55]     at C:\Users\aleks\xx\node_modules\metro\src\Assets.js:326:507

I am new so It is really confusing.

**Comment by dogsiskela** [comment]
@YoshiYo
The problem is that i am launching the second project which uses different code without the font. But for some reason it builds the app.js file from the first project.

**Comment by YoshiYo** [comment]
@dogsiskela 

Which version of the SDK do you use ? 

Can you try this ?
- Install or upgrade with `npm install -g expo-cli`
- Start your project just with the command `expo start`
- The browser will be opened with an interface.

If the problem persists, after `expo start` in your console, go back in your terminal and press `Shift+r`
This will restart and clean the cache. 
Then, go on IOS or Android to see if you have still the problem.

**Comment by dogsiskela** [comment]
@YoshiYo 

Did that, it is not working. Could it be some code error in package.json
Or could the first project that is named "app" changed some settings or something? I can not create a blank project. The first "app" i used a template.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Questions like this are better suited for our [forums](https://forums.expo.io) -- please post there if you need help in situations like this. Thanks!
