### ISSUE TITLE
TaskManager does not work on iOS

### ISSUE THREAD

**Issue by kiorq** [expo/expo#29814]
### Minimal reproducible example

https://github.com/kiorq/expo-task-manager/blob/main/App.js

### Did you reproduce this issue in a development build?

Yes

### Summary

I've been trying to get BackgroundFetch and Background Notifications to work on my iphone. I am not able to succeeded, i've tried doing research but on both the forum and discord i've only found ignored or unresolved issue relating to this matter.

I made another issue a few days ago but it was related to expo-router, but now i think it may just be broken? https://github.com/expo/expo/issues/29792

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    npmGlobalPackages:
      eas-cli: 10.0.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

Need to install the following packages:
expo-doctor@1.6.1
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by cross19xx** [comment]
This is a duplicate of #29558 , and judging from the version of expo you have, that holds

**Comment by kiorq** [comment]
I may have completely missed this, closing and watching https://github.com/expo/expo/issues/29558 instead

**Comment by kiorq** [comment]
I've been trying all day to get remote-notifications to work, i'm not sure what next steps to take at this point

**Comment by kiorq** [comment]
Update: left it running all night again and for the 3rd night it rose!.

I'm guessing iOS does a lot of throttling with background tasks even cause by push notifications?
