### ISSUE TITLE
Inconsistent RefreshControl between Expo Go and dev build

### ISSUE THREAD

**Issue by chris-sark** [expo/expo#29843]
### Minimal reproducible example

https://github.com/chris-sark/Min-reproducible-bug

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Hello, 
I am struggling with getting RefreshControl's tintColor and progressViewOffset to work properly on a development build, both on a simulator and device. The only place where tintColor and progressViewOffset works correctly is expo go, and I am unsure why. You can see in the attached video first I open expo go and everything works as expected, then I move to my dev build and the refresh control's styling are not applied.

package.json is visible in the repo.

https://github.com/expo/expo/assets/155602878/88bb51e8-1175-439a-bce0-30297186316b

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /opt/homebrew/bin/node
      npm: 10.8.1 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Error: Problem validating asset fields in /Users/csarkissian/Documents/Work/Test/Min-reproducible-bug/app.json. Learn more: https://docs.expo.dev/
 • Field: Android.adaptiveIcon.foregroundImage - cannot access file at './/assets/images/adaptive-icon.png'.
 • Field: icon - cannot access file at './assets/images/icon.png'.
 • Field: Splash.image - cannot access file at './assets/images/splash.png'.

**Comment by jacob-greco** [comment]
Having this issue as well

**Comment by burhanyilmaz** [comment]
hi @chris-sark , did you find any solution?
