### ISSUE TITLE
Build failure: Cannot find 'RCTTriggerReloadCommandListeners' in scope

### ISSUE THREAD

**Issue by turkonjavladimir** [expo/expo#29859]
### Minimal reproducible example

https://github.com/turkonjavladimir/RNBareExpo

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

This is a RN base project that integrates expo modules. After upgrading to the latest RN version (0.74.x) and expo SDK to 51, both iOS and android fails to build with the following error messages:

```
❌  …/projects/personal/RNBareExpo/node_modules/expo-modules-core/ios/Core/Modules/CoreModule.swift:44:7: cannot find 'RCTTriggerReloadCommandListeners' in scope

      RCTTriggerReloadCommandListeners(reason)
```

The same project running SDK 50 and RN 0.73.7 works as expected. The error itself seems to be related to:

```  
 AsyncFunction("reloadAppAsync") { (reason: String) in
      RCTTriggerReloadCommandListeners(reason)
    }
```

I can't make much sense of it at this point, so any input would be highly appreciated
 

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-32 | Intel x86_64 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.14 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ^

### Expo Doctor Diagnostics

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.8.4
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

Error: Problem validating fields in /Users/vladimir.turkonja/Desktop/projects/personal/RNBareExpo/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

One or more checks failed, indicating possible issues with the project.

The diagnostic should have nothing to do with the issue indicated above

**Comment by marksyzm** [comment]
I get this using `ffmpeg-kit-react-native` - I'll try with different versions to see if any of that matters.

**Comment by marksyzm** [comment]
Ah cool! Might try it as a patch somehow

**Comment by turkonjavladimir** [comment]
Just wanted to follow up. Did a quick patch following what @Kudo has done and the iOS app does build!

<img width="336" alt="Screenshot 2024-06-26 at 11 33 25 AM" src="https://github.com/expo/expo/assets/25246005/15455f07-d063-4f01-bbaa-c1f3c44db830">

I'll give android a go and try the same changes in the main app in order to confirm.

Thanks @Kudo for looking into this 🙏

**Comment by marksyzm** [comment]
Cool! What did you use to patch with?

**Comment by turkonjavladimir** [comment]
> I'll give android a go and try the same changes in the main app in order to confirm.

https://www.npmjs.com/package/patch-package

You basically make the changes in node_modules and do `npx patch-package [module-name]`

**Comment by Kudo** [comment]
@turkonjavladimir thanks for verifying the fix. what's the android error you had? since `RCTTriggerReloadCommandListeners` is ios only code.

**Comment by turkonjavladimir** [comment]
@Kudo yeah, I don't remember exactly since it's been a some time since I ran android, I'll try and have a look today and report back

**Comment by marksyzm** [comment]
Android is all fine for me. I'm confident this is all that's needed; works perfectly here.

**Comment by turkonjavladimir** [comment]
Hey guys, me again. Didn't wanna open another thread so thought I'd post here.

Managed to find some time and retest everything in the actual app I'm working on

So far the build succeeds with no issue on iOS but, but when the app stars I get the following error

`error: src/main.tsx: [project]/src/main.tsx: Duplicate __self prop found. You are most likely using the deprecated transform-react-jsx-self Babel plugin. Both __source and __self are automatically set when using the automatic runtime. Please remove transform-react-jsx-source and transform-react-jsx-self from your Babel config.
  17 | const logger = setupLogger({ environment: env.APP_ENV, sentryDsn: env.SENTRY_DSN });
  18 |
> 19 | let AppComponent: FC = () => <App logger={logger} />;
     |                              ^^^^^^^^^^^^^^^^^^^^^^^
  20 |
  21 | if (__DEV__) {
  22 |  // eslint-disable-next-line @typescript-eslint/no-var-requires`

I've read through quite a few posts that I could find including https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#babel-package-renames

But to no avail :(

The project is setup with NX and i Have the following accross multiple babel files
`"test": {
			"presets": ["module:metro-react-native-babel-preset"]
		}`

What I tried was replacing `metro-react-native-babel-preset` with `@react-native/babel-preset` but that didn't help

Curious if @Kudo might have an idea or if anyone has come across a similar issue.

Not sure if this is diretly related to expo at this point though
