### ISSUE TITLE
Expo Go: Splash screen logo position shift on Android

### ISSUE THREAD

**Issue by hichemfantar** [expo/expo#29880]
### Summary

This is not about development builds, it's about the Expo app provided in the play store.

https://github.com/expo/expo/assets/34947993/e3335434-57b9-48cb-8907-b9f4e03ebd89

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Environment

Expo app on android playstore
tested on OxygenOS 11 and MIUI 13

### Reproducible demo

1. Install the expo from the android playstore
2. launch
3. notice the expo logo changes position and goes up a few pixels

**Comment by alanjhughes** [comment]
Hi @hichemfantar - We will make an internal task to fix this. I will close as this has no impact on end users and is just a UI glitch in our own app.

**Comment by hichemfantar** [comment]
Sounds good

**Comment by milhous** [comment]
Hi @alanjhughes, Has this issue been fixed?

**Comment by piscopancer** [comment]
somebody please explain why this happens
