### ISSUE TITLE
[expo-symbols] symbols are stretched

### ISSUE THREAD

**Issue by dasistkeintest** [expo/expo#29889]
### Minimal reproducible example

https://github.com/dasistkeintest/expo-symbols-stretched

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Maybe I am missing something, but it seems like expo-symbols assumes that all SF Symbols have equal width and height, which is not true. This results in many stretched symbols. For example, without manually adjusting width and height, the lens on the `camera` symbol is oval.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 21.5.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11076708
    npmPackages:
      expo: ~51.0.14 => 51.0.14
      react: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by dlindenkreuz** [comment]
FYI, the docs currently show a non-existing default value for `resizeMode` "scaleToAspectFit": https://docs.expo.dev/versions/latest/sdk/symbols/#resizemode

Also, it would be better to have `scaleAspectFit` as the actual default (currently is `scaleToFill` in Swift), because we usually don't know the exact pixel dimensions when we use SF Symbols.
