### ISSUE TITLE
Grouped routes throwing 404s when deployed (Netlify, etc.)

### ISSUE THREAD

**Issue by kimchouard** [expo/expo#29883]
### Minimal reproducible example

https://github.com/kimchouard/grouped-route-bug

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When deploying an Expo Router app with `output: server` on Netlify, all grouped routes (e.g. `(tabs)/index`) will throw a plain `Not Found` black page 404 error.

## Steps to Reproduce

1. Create a new template app `npx create-expo-app@latest` and change the `app.json` settings to have `output: server`
2. Follow the [instructions on the API routes docs](https://docs.expo.dev/router/reference/api-routes/#netlify) to deploy to Netlify
3. Your root page will now throw a 404 error. 

👉 Example here deployed on Netlify from the [reproduction GH repo](https://github.com/kimchouard/grouped-route-bug): [grouped-route-bug.netlify.app](https://grouped-route-bug.netlify.app/)

## Origin of the Bug

This is due to the fact that your `index.html` route is in a `(tabs)` folder and that the Expo-Router server doesn't map to it. 😬 This issue is true for **any routes under a `(group)` folder**.

![CleanShot 2024-06-19 at 18 45 08@2x](https://github.com/expo/expo/assets/2856923/ff1bfe8c-b8ae-4d1b-ab45-29e79ae62a45)

## Notes

- Now, if you access the [`grouped-route-bug.netlify.app/(tabs)` route](https://grouped-route-bug.netlify.app/(tabs)) directly, it will work and eventually redirect you to the proper root `/` path (after a brief `+not-found.tsx` rendering :P) 
- If you ever create a route that's not behind a grouped folder, say `/ungrouped-modal`, then it will render directly with no issues: [grouped-route-bug.netlify.app/ungrouped-modal](https://grouped-route-bug.netlify.app/ungrouped-modal)

## Expected Behavior

- When building the `dist/` code OR through the `createRequestHandler` util used in the Netlify function, Expo Router should ensure that a proper path-mapping is done (e.g. `/` would render `/(tabs)`), using the `dist/server/_expo/routes.json` file for example.
- When a route is not found, instead of rendering a dark `404` page, it should redirect/render the `+not-found.tsx` file.

<img width="400" alt="CleanShot 2024-06-19 at 18 55 48@2x" src="https://github.com/expo/expo/assets/2856923/1bfc4257-ebf3-401e-87e8-2164c3e8514b">

_(👆 this is a bit plain for a 404 page in a production website 😅)_

## Starting point for a fix

After looking at the `@expo/server/build/vendor/netlify.js` helper, I thought that maybe we could do a smarter mapping of the URLs using the `routes.json` file in the `convertRequest` function, when getting the request URL? (see [line 75](https://github.com/expo/expo/blob/4a6a52c22be3522edbecab67c1c2dd6234470c58/packages/%40expo/server/build/vendor/netlify.js#L75))

I'm not too familiar with it yet, so any help here would be much much appreciated. This is blocking our app go to production, and probably others. 😞 

### Environment

Web, using  `output: server` to support API routes.

**Comment by kimchouard** [comment]
This is a show-stopping bug that might affect a lot of folks. It was hard to spot, so glad I could reproduce it.

Would be keen to get your thougths on it @EvanBacon @marklawlor 🧐🙃🙏

**Comment by EvanBacon** [comment]
Really sorry that this got through / wasn't caught sooner. I've added E2E testing to ensure this doesn't break again.

**Comment by kimchouard** [comment]
Great, thanks @EvanBacon !! 🙌 

Is this pushed to the latest version of Expo yet? I've updated my prod app and some seems to be fixed, while others are not. 🤔 

In my [repro repo](https://github.com/kimchouard/grouped-route-bug) though (updated with Expo v51.0.17), none of the grouped routes work. 🤷🏼‍♂️

Minor detail still happening too, not sure if there could be a fix in Expo 52 or not: when loading a grouped route (one that works for now), it's blinking on the `+not-found.tsx` route for a split second (enough for your brain to process it) before it lands on the proper route.
👉 See the white page (still the default 404 in my repo) blinking before the proper UI loads:

![CleanShot 2024-07-02 at 09 37 56](https://github.com/expo/expo/assets/2856923/e1d57f14-e73b-4fe0-857b-5f733a19db30)

Merci!
