### ISSUE TITLE
[media-library] deleteAssetsAsync does not work on Android

### ISSUE THREAD

**Issue by mathieupost** [expo/expo#29896]
### Minimal reproducible example

https://github.com/mathieupost/expo-media-library-example

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

`deleteAssetsAsync` does not work on Android (R and above).

Using the debugger in Android Studio I noticed that the `assetUri` in `MediaLibraryUtils.deleteAssets` is not correct. When deleting an image for example the URI is `content://media/external/file/1000000021`, but this must be `content://media/external/images/media/1000000021`. Other mime types have other URIs.

This can be reproduced using the provided example repo in this issue using these steps:
1. Take a photo to be deleted.
2. Run the example.
3. Allow all requested media permissions.
4. Click the button.
5. Allow to modify the image.
6. Check in your gallery/photos app that the photo is still there.

If updating `expo-media-library` to the latest master version, an error will be thrown because of #29777, but on v16.0.3 it silently fails.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /run/current-system/sw/bin/zsh
    Binaries:
      Node: 18.19.1 - /etc/profiles/per-user/mathieu/bin/node
      npm: 10.2.4 - /etc/profiles/per-user/mathieu/bin/npm
      Watchman: 2024.03.11.00 - /nix/store/aw1bpalb6d1a0flmhg550rbv1dzqrcks-watchman-2024.03.11.00/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 26, 31, 33, 34
        Build Tools: 26.0.3, 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-26 | Google APIs Intel x86_64 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare

### Expo Doctor Diagnostics

Running 12 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by hotaryuzaki** [comment]
i face this issue too.

**Comment by cesarjhony** [comment]
I have the same issue.

**Comment by cesarjhony** [comment]
Is there any workaround?

**Comment by lux22333** [comment]
I tested last night Medialibrary. DeleteAssetsAsync this method in the latest version of the SDK 51 have successfully deleted photos, but is not working in sdk50

**Comment by lux22333** [comment]
I found something to do with the Android version

**Comment by lux22333** [comment]
> I found something to do with the Android version
  This method doesn't work on older versions of Android, but it does on lower versions

**Comment by lux22333** [comment]
Are there any solutions？

**Comment by mathieupost** [comment]
I only need image support, so I've used this patch for now (using [patch-package](https://github.com/ds300/patch-package)):

`patches/expo-media-library+16.0.4.patch`
```diff
diff --git a/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt b/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt
index a6e6d39..39a3349 100644
--- a/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt
+++ b/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt
@@ -92,8 +92,11 @@ object MediaLibraryUtils {
             if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
               val columnId = filesToDelete.getColumnIndex(MediaStore.MediaColumns._ID)
               val id = filesToDelete.getLong(columnId)
-              val assetUri = ContentUris.withAppendedId(EXTERNAL_CONTENT_URI, id)
-              context.contentResolver.delete(assetUri, null)
+              val assetUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id)
+              val rowsDeleted = context.contentResolver.delete(assetUri, null)
+              if (rowsDeleted == 0) {
+                throw AssetFileException("Could not delete file.")
+              }
             } else {
               val dataColumnIndex = filesToDelete.getColumnIndex(MediaStore.MediaColumns.DATA)
               val filePath = filesToDelete.getString(dataColumnIndex)
```

**Comment by davidd8** [comment]
Any update on getting this to work for all media types and integrate into the official release of Expo Media Library?

**Comment by cesarjhony** [comment]
Yes, but it is just my homemade workaroud, I used the same method of @mathieupost for patch.
 ```
 diff --git a/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt b/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt
index a6e6d39..c28704e 100644
--- a/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt
+++ b/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.kt
@@ -92,8 +92,14 @@ object MediaLibraryUtils {
             if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
               val columnId = filesToDelete.getColumnIndex(MediaStore.MediaColumns._ID)
               val id = filesToDelete.getLong(columnId)
-              val assetUri = ContentUris.withAppendedId(EXTERNAL_CONTENT_URI, id)
-              context.contentResolver.delete(assetUri, null)
+              //val assetUri = ContentUris.withAppendedId(EXTERNAL_CONTENT_URI, id)
+              //context.contentResolver.delete(assetUri, null)
+              val assetUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id)
+              val assetUri2 = ContentUris.withAppendedId(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, id)
+             val rowsDeleted = context.contentResolver.delete(assetUri, null) + context.contentResolver.delete(assetUri2, null)
+              if (rowsDeleted == 0) {
+                throw AssetFileException("Could not delete file.")
+              }
             } else {
               val dataColumnIndex = filesToDelete.getColumnIndex(MediaStore.MediaColumns.DATA)
               val filePath = filesToDelete.getString(dataColumnIndex)

 ```

**Comment by davidd8** [comment]
Thanks @cesarjhony, but I'd also like to understand what the timeline is for the Expo team to rollout this fix?

**Comment by lux22333** [comment]
I tried to modify the source code like this, but it doesn't work on my Android device. 

`
           val assetUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id);

            val rowsDeleted = context.contentResolver.delete(assetUri, null);
            if (rowsDeleted == 0) {
                   throw AssetFileException("Could not delete file.")
            }
`

**Comment by lux22333** [comment]
I tried to modify the source code like this, but it doesn't work on my Android device.

```
+              val assetUri = ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, id)
+              val rowsDeleted = context.contentResolver.delete(assetUri, null)
+              if (rowsDeleted == 0) {
+                throw AssetFileException("Could not delete file.")
+              }

```

**Comment by cesarjhony** [comment]
@lux22333 did you use the patch-package as as @mathieupost said? Please make sure you have been implement the steps in the patch-package readme.

**Comment by mathieupost** [comment]
Hahah nice solution @cesarjhony, thanks. I'll probably use that when I add video support for my app as long as it's not fixed in expo

**Comment by lux22333** [comment]
> @lux22333 did you use the patch-package as as @mathieupost said? Please make sure you have been implement the steps in the patch-package readme.

The deletion in expo go is invalid, I tried to package it into apk and found it worked, thank you

**Comment by amalp12** [comment]
Any fix for this issue out yet? i am still facing this issue.

**Comment by Zeeshan404** [comment]
> Any fix for this issue out yet? i am still facing this issue.

Check out this PR https://github.com/expo/expo/pull/33211. Not sure when this is going to merge.

**Comment by amalp12** [comment]
@Zeeshan404 thanks, will keep on the lookout. For now wrote a delete method in kotlin android and exposed it to react.
