### ISSUE TITLE
Missing `slug` key on app.json yields extraneous error messages

### ISSUE THREAD

**Issue by jjant** [expo/expo#299]
I started a new App with CRNA, and I kept getting an error saying "Unable to execute JS call: __fbBatchedbridge is undefined", and just a warning on my terminal saying that the `slug` key was missing on my app.json.
After setting that up, the error disappeared.

It would be awesome if there was a better error message than that cryptic "__fbBatchedBridge is undefined" error. And if that key is so important in the app.json file, don't just throw a warning, crash the app with a nicer explanation.

E: Using `expo 18.0.0`

**Comment by dikaiosune** [comment]
Hi! Sorry to hear you had a poor experience here. Where did the batched bridge error appear? As a red screen? In your terminal? Can you provide a bit more context?

FWIW the slug field should be optional, which is potentially concerning.

**Comment by jjant** [comment]
Hi, this appeared as a reed screen on my simulator. It _might_ have been a coincidence, but I tried to get the thing working for a few hours, until I saw the warning about the slug field, added it and everything started working...

Also, the [documentation](https://docs.expo.io/versions/v18.0.0/guides/configuration.html) says the slug key is required, which is also a reason that led me to this conclusion.

Again, it might've been a coincidence, and I apologize if that's the case.

**Comment by dikaiosune** [comment]
Interesting. The documentation says that it's required as a quirk of how it's generated from a schema (it's required for the schema, but we will infer it before verification if it doesn't already exist, cc @brentvatne), sorry about that.

OK, I'll close this since you got things working, but if anyone else gets a strange batchedBridge error related to the slug field, please comment here and I'll investigate!

**Comment by rahls7** [comment]
Hey, this happened to me while working on my app. I get the same error on ios Simulator but it is working perfectly fine on my Android  Device. I am using Expo XDE and the only error I can use in my console is related to WebSocket Connection. 
It only started occurring after I started working with the React Navigation Library. 
I tried restarting the expo XDE a couple of times, but it seems to be not working.

**Comment by dikaiosune** [comment]
@rahls7 take a look at https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352

**Comment by uqee** [comment]
Same symptoms and resolution here.

**Comment by Stophface** [comment]
same here...
