### ISSUE TITLE
Back Button not visible when coming from deeplink in the closed app

### ISSUE THREAD

**Issue by roshangm1** [expo/expo#29914]
### Minimal reproducible example

na

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

The back button is not rendering when navigating from deeplink when the app is closed. I seem to be passing valid initial route name in the settings. I do have one level extra nested structure though. 
![image](https://github.com/expo/expo/assets/5866078/2b92d52c-cd50-4668-adb2-904c1bec6993)

`(app)` is authenticated route (has several other groups too) and `(auth)` is unauthenticated one.
I have 
```
export const unstable_settings = {
      initialRouteName: '(app)',
}
```
 in the root level `_layout.tsx`. 
 

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/penguin/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.8 => 51.0.8 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare


```

**Comment by roshangm1** [comment]
Okay so never mind. I had to add `unstable_settings` inside `app/(app)` too with initial route name (tabs). Everything looks perfect now :)

**Comment by martinezguillaume** [comment]
Thanks ! I didn't see this [doc](https://docs.expo.dev/router/advanced/router-settings/), very important !
