### ISSUE TITLE
[expo-sqlite] Expo Sqlite with Typeorm don't trigger constraint errors.

### ISSUE THREAD

**Issue by JRBARROZ** [expo/expo#29920]
### Minimal Reproducible Example

https://github.com/JRBARROZ/expo-issue-producible

### Which package manager are you using? (Yarn is recommended)

Yarn

### Summary

I'm trying to understand why expo sqlite and typeorm once i try to insert data that broke constraint rules, the typeorm with expo doesn't triggetr the error and stop all database interaction in the line that executed. Others finds, inserts any interaction with the database doesn't work and i need to reset the application. Refreshing with "R"on terminal doesn't work too.

### Steps to Reproduce

* Go to the link with template project -> https://github.com/JRBARROZ/expo-issue-producible
* Start the application with yarn & yarn start
* Go to the bottom menu on "Profile"
* Touch on the button called "PRESS ME TO BUG SQLITE WITH TYPEORM"
* Look down the console.log

### Expected Behavior

After touch the button, i expect to the console.log() in that code that makes a find inside the database after insert shows on console.
### Notes
 I also tested on expo 51 but the typeorm database tries to open with OpenDatabase and not with OpenDatabaseAsync

### What platform(s) does this occur on?

Android

### SDK Version

50.0.19 

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.19 => 50.0.19 
      expo-router: ~3.4.10 => 3.4.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 3.17.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/JRBARROZ/expo-issue-producible

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Can you simplify your reproduction so that it doesn't rely on typeorm?
If there's an issue in expo-sqlite, you should be able to reproduce it without any ORM and it'll make resolving the issue easier for us. If you're only able to see the problem once you deploy an ORM then investigating the issue will be more complicated and harder for us to prioritize.
Thank you 🙂

**Comment by JRBARROZ** [comment]
@vonovak , i tried without typeorm but with another ORM called drizzle, and works well, without problems, you think that maybe the typeorm causing the problem ?

**Comment by vonovak** [comment]
> @vonovak , i tried without typeorm but with another ORM called drizzle, and works well, without problems, you think that maybe the typeorm causing the problem ?

If it works as expected with Drizzle, it's more likely that the error is in TypeORM. We still cannot rule out that the issue in expo-sqlite though. Can you reproduce the problem without any ORM whatsoever, only with expo-sqlite?

**Comment by JRBARROZ** [comment]
> > @vonovak , i tried without typeorm but with another ORM called drizzle, and works well, without problems, you think that maybe the typeorm causing the problem ?
> 
> If it works as expected with Drizzle, it's more likely that the error is in TypeORM. We still cannot rule out that the issue in expo-sqlite though. Can you reproduce the problem without any ORM whatsoever, only with expo-sqlite?

no, because with expo works very well, once i put sequelize this starts to happen, i'm migrating to drizzle to se if happens frequently.
