### ISSUE TITLE
Delay opening when app backgrounded

### ISSUE THREAD

**Issue by ardyfeb** [expo/expo#2993]
Standalone app get delayed when app is already running on background on

### Environment
- Android 7 (MIUI)

### Steps to Reproduce
1. Open app
2. Close to background
3. And open app again through app icon

### Expected Behavior
App normally launch with app icon when app is backgrounded

### Actual Behavior
App get delayed opening

### Reproducible Demo
- Github repository : https://github.com/ardyfeb/islamku
- Video : https://streamable.com/o7nlo

**Comment by ide** [comment]
If you can help pinpoint the root cause that'd be helpful since we can't really tell what's going on other than that reopening your app is slow.

**Comment by ardyfeb** [comment]
Closed, because the `await setupDatabase ()` called when app open, i need change the strategy to load database
