### ISSUE TITLE
Environment variables undefined, causing app to crash

### ISSUE THREAD

**Issue by ThasheelI** [expo/expo#29939]
### Minimal reproducible example

https://github.com/ThasheelI/expo-env-problem/tree/main

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

We are experiencing an issue where the variables defined in eas.json are not being correctly pulled through during the production build process on Expo using SDK 51. Despite being properly configured and working in development builds, these environment variables are missing or not accessible when performing a production build. This discrepancy is causing functionality that depends on these variables to fail in the production environment.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.11005911
    npmPackages:
      expo: ~51.0.14 => 51.0.14
      expo-router: ~3.5.16 => 3.5.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed

### Expo Doctor Diagnostics

Running "expo doctor"
Running 12 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
Didn't find any issues with the project!

**Comment by Kudo** [comment]
hi there! could you try to use exact `process.env.EXPO_PUBLIC_APP_URL`?
```diff
--- a/components/WebsiteWebView.tsx
+++ b/components/WebsiteWebView.tsx
@@ -2,7 +2,7 @@ import { useState } from "react";
 import WebView from "react-native-webview";

 export const WebsiteWebView = () => {
-    const appUrl = (process.env as any).EXPO_PUBLIC_APP_URL;
+    const appUrl = process.env.EXPO_PUBLIC_APP_URL;
     const [date] = useState(new Date().toLocaleDateString());

     return (
```

i guess our env plugin is not flexible enough to have something in between the statement.
