### ISSUE TITLE
Android emulator: Localization.locale always reports 'en-US'

### ISSUE THREAD

**Issue by Morriz** [expo/expo#2994]
### Environment

  Expo CLI 2.6.8 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - ~/.nvm/versions/node/v11.2.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v11.2.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.2.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.6 => 31.0.6
      react: ^16.6.3 => 16.6.3
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.7 => 3.0.7
    npmGlobalPackages:
      expo-cli: 2.6.8

Android emulator: Pixel 2 with app store, android 9.0

### Steps to Reproduce

run snack: https://snack.expo.io/@morriz/android-always-reporting-locale-'en-us'

### Expected Behavior

See the locale as deduced from the play store location (the Netherlands)

### Actual Behavior

I get the 'en-US' local.
Nowhere do I read about emulator not reporting the locale as found in the play store.

### Reproducible Demo

https://snack.expo.io/@morriz/android-always-reporting-locale-'en-us'

**Comment by sjchmiela** [comment]
What is the system language of the simulator? AFAIK `locale` will return first/primary locale specified by the user in settings. I just checked — on a device with primary language set to `Polish`, `Localization.locale` returns `pl-PL`, as it should. 🙂 

https://github.com/expo/expo/blob/03ee971ca96afe4ff0e6ae5861e41caaffadc2c2/packages/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.java#L70

https://github.com/expo/expo/blob/03ee971ca96afe4ff0e6ae5861e41caaffadc2c2/packages/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.java#L65-L66

https://github.com/expo/expo/blob/03ee971ca96afe4ff0e6ae5861e41caaffadc2c2/packages/expo-localization/android/src/main/java/expo/modules/localization/LocalizationModule.java#L88-L106

**Comment by Morriz** [comment]
I use english but am talking about locale. On my iPhone I use English with Dutch locale, so 'en-NL'.

I just bought the android to be able to add in-app purchases (doh!) but am not android savvy yet. Is there a way to choose locale settings somewhere?

**Comment by Morriz** [comment]
It's impossible to find such information on Google. Then I assume it's not possible? That would be so ugly

**Comment by Morriz** [comment]
No it's not. It seems android is still only for geeks: https://www.ctrl.blog/entry/android-en150-localization

**Comment by Morriz** [comment]
Closing this as it’s a deficiency of the android os, nothing expo related.
