### ISSUE TITLE
[expo-video] Component crashing on unmount

### ISSUE THREAD

**Issue by mihailapuste** [expo/expo#29950]
### Minimal reproducible example

Cannot provide min repo as expo video seems to crash the snack as shown in
https://snack.expo.dev/@kimik/765825

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I'm looking to swap out the existing expo-av video component with the new `expo-video` one, and everything seems to be fine, however my app crashes whenever I unmount the video player.

The issue seems to appear to be with the `release()` functionality, which is called on unmount. I initially thought I should try to release before unmounting as well, but that actually triggered the same issue.

This is code from expo
``` 
/// useReleasingSharedObject()
    useEffect(() => {
        isFastRefresh.current = false;
        return () => {
            // This will be called on every fast refresh and on unmount, but we only want to release the object on unmount.
            if (!isFastRefresh.current && objectRef.current) {
                objectRef.current?.release(); // <--- commenting this out makes it work fine!
            }
        };
    }, []);
    return object;
    ```

The error encoutered is quite non-descriptive, but consistent.

Error: Exception in HostFunction: failed to define internal native state property

```


```
So from what I was able to gather, the` release()` seems to be causing trouble.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - /opt/homebrew/bin/npm
      Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/mihailapuste/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.0.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✖ Check package.json for common issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✖ Check for issues with metro config
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.9.1
  (for more info, run: npm why @expo/config-plugins)
Expected package metro@~0.80.8
Found invalid:
  metro@0.80.5
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.5
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.5
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

Error: Problem validating fields in /Users/mihailapuste/fit52/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

The following scripts in package.json conflict with the contents of node_modules/.bin: lint-staged, tsc.

It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config. This can lead to unexpected and hard to debug issues. Learn more: https://docs.expo.dev/guides/customizing-metro/
Advice: Update your custom metro.config.js to extend @expo/metro-config.

(node:46223) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@7.6.4 - expected version: 8.0.1
  @react-native-community/netinfo@11.2.1 - expected version: 11.3.1
  @react-native-picker/picker@2.6.1 - expected version: 2.7.5
  expo-notifications@0.27.7 - expected version: ~0.28.9
  react-native-gesture-handler@2.14.1 - expected version: ~2.16.1
  react-native-get-random-values@1.10.0 - expected version: ~1.11.0
  react-native-pager-view@6.2.3 - expected version: 6.3.0
  react-native-reanimated@3.6.2 - expected version: ~3.10.1
  react-native-safe-area-context@4.8.2 - expected version: 4.10.1
  react-native-screens@3.29.0 - expected version: 3.31.1
  react-native-svg@14.1.0 - expected version: 15.2.0
  @babel/core@7.23.9 - expected version: ^7.24.0
  @types/react@18.2.48 - expected version: ~18.2.79
  typescript@5.0.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

**Comment by mihailapuste** [comment]
@behenate 


I upgraded to `1.2.3` and the issue persists. It is also present on `android` as well as `ios`. 
I believe you found a separate issue in https://github.com/expo/expo/pull/30022, and not the one mentioned above.

To reproduce, simply unmounting the video player causes the following error
```
Error: Exception in HostFunction: failed to define internal native state property
```

and as mentioned, its occurring on `ios` and `android`.


as mentioned earlier, the issue seems to be related to the calling of the `release()` in the `useReleasingSharedObject` hook.
From testing, removing that call solves the issue. Im sure there are other implications there, but hopefully this somewhat helpful to debug.

Thank you!

**Comment by behenate** [comment]
@mihailapuste Sorry to hear that! After merging the PR with the fix it seemed to work every time on my setup. I'll take another look. It's most likely a similar issue in a different spot.

**Comment by behenate** [comment]
@mihailapuste Could you make a github repo with a minimal reproducible example? I want to make sure this time it works in your case

**Comment by mihailapuste** [comment]
> @mihailapuste Could you make a github repo with a minimal reproducible example? I can't seem to get it to crash while in my app

Hi @behenate sorry for the late reply.

After more debugging, i realized the video component is fine on unmounting, the issue instead appears due to my usage of the mobx store.

I set the video player object in the store (works perfectly fine) to pause and manipulate the video from the store methods.

But when unmounting the screen, the crash seems to occur, likely due to some odd referencing issue.

I'm not aware of any good ways to "clear" the video reference, but some ability to do that would be greatly appreciated

My repo that is able to repro the issue can be found here: https://github.com/mihailapuste/ExpoVideoTest

and the repro steps are 
- go to video player screen
- swipe back to home screen

**Comment by behenate** [comment]
@mihailapuste I'm guessing mobx keeps a reference to the video, while it's automatically released when you leave the screen. 

I'm guessing you are trying to use the same player across multiple screens in the original app and that's why you keep in the store. We can try a bit of a quick workaround 
```
import { Platform, requireNativeModule } from 'expo-modules-core';
import {
  useVideoPlayer,
  VideoView,
  VideoSource,
  VideoPlayerEvents,
  VideoPlayer as VideoPlayerType,
} from 'expo-video';

const VideoPlayer = requireNativeModule('ExpoVideo').VideoPlayer as VideoPlayerType;

export default function VideoScreen() {
[...]
  //@ts-ignore
  const dangerousPlayer = new VideoPlayer(bigBuckBunnySource);
[...]

// Use the player in a video view
}
```

This will create the VideoPlayer while bypassing the auto-releasing hook. Now you have to manage the lifecycle of the player completely on your own - the most important part is releasing the player after it will no longer be used - so calling release() just after you remove it from the mobx store.

Can you check if this helps? I'll try to take a deeper look why the crash occurs in the example, but I'm currently a bit swamped with other video features 😅

**Comment by mihailapuste** [comment]
> @ts-ignore

@behenate thank you! this is a good start for a work around - and I have it working preliminarily. Thank you. Will update with a more complete solution when I have it for anyone else experiencing this.

**Comment by mihailapuste** [comment]
> > @ts-ignore
> 
> @behenate thank you! this is a good start for a work around - and I have it working preliminarily. Thank you. Will update with a more complete solution when I have it for anyone else experiencing this.

@behenate since my project is using mobx-state-tree, and my main goal was to integrate the new video player object with the store to have easier store level control, I've created the following store model instead of a custom hook and it does the trick.

```ts
import { requireNativeModule } from 'expo-modules-core';
import {
  VideoSource,
  VideoPlayer as VideoPlayerType,
  VideoPlayerStatus,
  PlayerError,
} from 'expo-video';
import { IReactionDisposer, reaction } from 'mobx';

import { types, Instance } from 'mobx-state-tree';

import { addRootStoreView } from '@stores/storeHelpers';
import { IWorkoutStore } from '@stores/workoutStore';

import { log, warn } from '@services/logger';
import { trackEvent } from '@utilities/analytics';

const VideoPlayer = requireNativeModule('ExpoVideo')
  .VideoPlayer as VideoPlayerType;

// eslint-disable-next-line no-use-before-define
export type IVideoPlayerModel = Instance<typeof VideoPlayerModel>;

type SubscriptionType = ReturnType<VideoPlayerType['addListener']>;

const VideoPlayerModel = types
  .model('VideoPlayerModel', {
    videoPlayerObject: types.maybeNull(types.frozen<VideoPlayerType>()),
    shouldLogEvents: false,
    isLoading: true,
  })
  .views(addRootStoreView)
  .actions((self) => {
    let nonObservedVideoPlayerObject: VideoPlayerType | null = null;

    let videoSourceReactionDisposer: IReactionDisposer | null = null;

    let videoIntervalDisposer: NodeJS.Timeout | null = null;

    let statusChangeSubscriptionDisposer: SubscriptionType;

    let playToEndSubscriptionDisposer: SubscriptionType;

    return {
      beforeDestroy() {
        videoSourceReactionDisposer?.();
        videoSourceReactionDisposer = null;

        clearInterval(videoIntervalDisposer as NodeJS.Timeout);

        (self as IVideoPlayerModel).release();
      },

      initializeVideoPlayerReactions(): void {
        if (!self.videoPlayerObject) {
          return;
        }

        videoSourceReactionDisposer?.();
        videoSourceReactionDisposer = null;

        // listen for changes in video source and update the video player accordingly
        videoSourceReactionDisposer = reaction(
          () => [
            // listen for changes in source in another store value
          ],
          ([source]) => {
            if (!source || !self.videoPlayerObject) {
              return;
            }

            (self as IVideoPlayerModel).setSource(
              source as unknown as VideoSource,
            );
          },
        );

        statusChangeSubscriptionDisposer?.remove();
        statusChangeSubscriptionDisposer = self.videoPlayerObject.addListener(
          'statusChange',
          (
            newStatus: VideoPlayerStatus,
            __: VideoPlayerStatus,
            error: PlayerError,
          ) => {
            if (newStatus === 'readyToPlay') {
              if (self.shouldLogEvents) {
                log('Video onReadyForDisplay called');
              }

              (self as IVideoPlayerModel).setIsLoading(false);

              return;
            }

            if (newStatus === 'error' && error) {
              warn(`VideoPlayer onError called: ${error?.message}`);
            }
          },
        );

        playToEndSubscriptionDisposer?.remove();
        playToEndSubscriptionDisposer = self.videoPlayerObject.addListener(
          'playToEnd',
          () => {
            if (self.shouldLogEvents) {
              log('Video onEnd called');
            }

            // do something
          },
        );

          videoIntervalDisposer = setInterval(() => {
            if (!self.videoPlayerObject) {
              return;
            }

            // do something on an interval
        
          }, 1000);
        
      },

      initializeWithSource({
        source,
        isLooping = false,
        isMuted = false,
        initialPlaybackPosition,
        setupPlayer,
      }: {
        source: VideoSource;
        isLooping?: boolean;
        isMuted?: boolean;
        initialPlaybackPosition?: number;
        setupPlayer?: () => void;
      }): void {
        log('Initializing video player model...');

        try {
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-expect-error
          nonObservedVideoPlayerObject = new VideoPlayer(source);

          if (!nonObservedVideoPlayerObject) {
            throw new Error('Could not create video player object');
          }

          nonObservedVideoPlayerObject.loop = isLooping;
          nonObservedVideoPlayerObject.muted = isMuted;
          nonObservedVideoPlayerObject.currentTime =
            initialPlaybackPosition || 0;

          (self as IVideoPlayerModel).setVideoPlayerObject(
            nonObservedVideoPlayerObject,
          );

          setupPlayer?.();

          (self as IVideoPlayerModel).play();

          (self as IVideoPlayerModel).initializeVideoPlayerReactions();
        } catch (error) {
          warn('Error initializing video player model', error);
        }
      },

      setVideoPlayerObject(videoPlayer: VideoPlayerType): void {
        self.videoPlayerObject = videoPlayer;
      },

      setShouldLogEvents(shouldLog: boolean): void {
        self.shouldLogEvents = shouldLog;
      },

      setIsLoading(isLoading: boolean): void {
        self.isLoading = isLoading;
      },

      setSource(source: VideoSource): void {
        if (!self.videoPlayerObject) {
          return;
        }

        self.videoPlayerObject?.replace(source);

        self.videoPlayerObject.loop = true;

        (self as IVideoPlayerModel).play();
      },

      play(): void {
        if (!self.videoPlayerObject) {
          return;
        }

        self.videoPlayerObject?.play();
      },

      pause(): void {
        if (!self.videoPlayerObject) {
          return;
        }

        self.videoPlayerObject?.pause();
      },

      release(): void {
        if (nonObservedVideoPlayerObject) {
          // TODO: Still unable to reliably release the video player object. So far no side effects observed, however it is still a potential memory leak.
          // nonObservedVideoPlayerObject?.release?.();
          nonObservedVideoPlayerObject = null;
        }

        self.videoPlayerObject = null;
      },

      setPlaybackPosition(positionInMs?: number): void {
        if (!self.videoPlayerObject || positionInMs === undefined) {
          return;
        }

        const positionInSeconds = positionInMs / 1000;
        self.videoPlayerObject.currentTime = Math.max(positionInSeconds, 0);

        // do someting
      },
    };
  });

export default VideoPlayerModel;
```

This implementation works well, however the only thing I still havent been able to get right is the usage of the `release`. From testing, I don't seem to need it, as running multiple videos for extended periods doesn't seem to have any problem. However im worried that in the case of more intensive usage, it might be necessary to avoid possible memory leaks, and other  possible negative side effects. 

@behenate I'm wondering if you could try to document the `release` function for the player a little more as to outline some guidelines for its usage, as there are probably some caveats im unaware of, and the minimal docs provided in the code don't outline these cases.

Additionally, the old AV player had a progress update interval that the new player doesnt seem to have. I've had to create one myself using reactions, but it would be a nice to have perhaps in a future release of expo-video.

Please let me know if theres anything I can help you with, and thank you so much for your time and patience, you guys are rockstars over at expo 🚀
