### ISSUE TITLE
Using await FileSystem.deleteAsync(localUri); failed

### ISSUE THREAD

**Issue by XeCtvi** [expo/expo#2996]
### Environment

Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: 1.12.3
  npm: 6.0.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^31.0.4 => 31.0.6
  react: 16.5.0 => 16.5.0
  react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1

Android

### Steps to Reproduce
1. `await MediaLibrary.getAssetsAsync` to got uri
2. `await FileSystem.deleteAsync(localUri)`

### Expected Behavior

Delete successfully

### Actual Behavior

`[Unhandled promise rejection: Error: Location 'file:///storage/emulated/0/标准化施工/4aa78aa7-8705-4312-8707-191726740dce.jpg' isn't deletable.]
`

**Comment by ardyfeb** [comment]
If want to delete camera roll file, use `Expo.MediaLibrary.deleteAssetsAsync(assets` instead. Read https://docs.expo.io/versions/latest/sdk/media-library#expomedialibrarydeleteassetsasyncassets

**Comment by XeCtvi** [comment]
Hi @ardyfeb ,

Thanks, let me try it. But why can't I use "FileSystem" instead? All I have to do is using `uri` address to delete the pic. But using MediaLibrary I need to prepare an asset object. Not convenience.

**Comment by ardyfeb** [comment]
> Hi @ardyfeb ,
> 
> Thanks, let me try it. But why can't I use "FileSystem" instead? All I have to do is using `uri` address to delete the pic. But using MediaLibrary I need to prepare an asset object. Not convenience.

I don't know exactly how this works, `Expo.FileSystem` working on `file://data/data/com.package.name` and `Expo.MediaLibrary` working on camera roll path

**Comment by XeCtvi** [comment]
@ardyfeb 

Yes, it makes no sense. Because I think uri is also a valid address.

**Comment by esamelson** [comment]
Hi there, I believe this is an underlying limitation of the Android OS -- apps are only allowed direct control over files in their own sandbox, i.e. `file://data/data/com.package.name`. You'll need to use the `MediaLibrary` functions to work with files in the camera roll.
