### ISSUE TITLE
getPermissionsAsync returns denied instead of undetermined on Android

### ISSUE THREAD

**Issue by armenavanesi** [expo/expo#29979]
### Minimal reproducible example

https://gist.github.com/armenavanesi/cb2257a3b9590f0a5217d81950d6d4fe

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

On Android, using `getPermissionsAsync` always returns `denied`, even on a fresh install. I'm using a development build. The expected behaviour is for it to return `undetermined`, like it does on iOS. This is reproducible with the official example code [here](https://docs.expo.dev/versions/latest/sdk/notifications/).

Here is what I've tried:
- Created a Firebase app, generated a new private key, added it to "FCM V1 service account key" in expo.dev
- Added `google-services.json` to the root directory, and used `android.googleServicesFile` in `app.json`, then rebuild with EAS.
- Also tried uploading the google-services.json file to EAS and then pointing to it in an `app.config.ts` and `process.env`, then rebuild with EAS

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/n/bin/node
      Yarn: 1.22.19 - ~/n/bin/yarn
      npm: 10.2.3 - ~/n/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo-router: ~3.4.8 => 3.4.8
    npmGlobalPackages:
      eas-cli: 7.8.2
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by jurawrssic** [comment]
Thos EXACT issue is happening to me! Please anyone???

**Comment by vu1511** [comment]
This happens to me as well, but using getPermissionsAsync still prompts the notification permission.

**Comment by gsimplicio-emed** [comment]
Anyone? I've run into the same issue and can't find a solution

**Comment by con-moore** [comment]
I am encountering this exact issue.

**Comment by jhogervorst** [comment]
Same here, with Expo SDK 53.
