### ISSUE TITLE
Expo fonts only loading first font on development build on iOS

### ISSUE THREAD

**Issue by Lewitje** [expo/expo#29989]
### Minimal reproducible example

https://github.com/Lewitje/expo-fonts-issue

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Expo fonts seems to only be loading the first font in "useFonts"
If I switch the order of the fonts you can see it'll only load the first one.
- On web everything loads fine
- I didn't test Android

I've tried changing the names of the fonts, using strings and not string for the names e.g:
- Satoshi900: require("@/assets/fonts/Satoshi900.ttf"),
- "Satoshi-Black": require("@/assets/fonts/Satoshi-Black.ttf"),

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      npm: 10.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by iM-GeeKy** [comment]
Potentially related to https://github.com/expo/google-fonts/issues/109

**Comment by haydencrain** [comment]
I'm able to reproduce this issue

**Comment by haydencrain** [comment]
@Lewitje were you ever able to resolve this?
