### ISSUE TITLE
chromeOS support

### ISSUE THREAD

**Issue by acornejo** [expo/expo#30]
This issue is to track adding a chromeOS app for exponent, relying on the recent addition of the android runtime component.

This would not only add another platform where extant apps can be run (iOS, Android or ChromeOS), but it would also allow developers to develop+test their applications using a chromebook instead of a physical device or a simulator (which traditionally are more resource intensive than simulators).

ChromeOS officially supports android apps on a subset of chromebooks, and quite a few android apps already support this (evernote, vine, skype, adobe lightroom, snapchat, etc).

When running in deverloper mode, all chromebooks (not restricted to a supported hardware subset) can run android apps, and can use ARC welder to convert android APK's into chromeOS apps (https://chrome.google.com/webstore/detail/arc-welder/emfinbmielocnlhgmfkkmkngdoccbadn).

I tried converting exponent APK to a chromeOS app using ARC welder, but there were issues after the splash screen. I suspect this may have to do with exponent trying to access some device not available on my laptop (for instance, GPS), but didn't dig any further.

**Comment by dikaiosune** [comment]
Hi! We're moving feature requests to Canny. I [created one](https://expo.canny.io/feature-requests/p/chrome-os-support) for this there. Thanks!
