### ISSUE TITLE
Websocket [ws] browser error on mobile apps

### ISSUE THREAD

**Issue by SuhitAgarwal** [expo/expo#30007]
### Minimal reproducible example

https://github.com/SuhitAgarwal/websocket-expo-bug

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

On bare React Native, the Websocket from [ws](https://github.com/websockets/ws) is the standard. You can see it in the `devDependencies` in the `package.json` for [React Native](github.com/facebook/react-native):
https://github.com/facebook/react-native/blob/main/package.json#L103

But for some reason in spite of removing all traces of the expo project being capable of running on web, I see this error:
```
 ERROR  Error: ws does not work in the browser. Browser clients must use the native WebSocket object

This error is located at:
    in HomeScreen
    .
    . // shortened to make it easier to read
    .
    in main(RootComponent), js engine: hermes
```

So the summary of issues here:
1. I am not using a browser client
2. My [Websocket implementation](https://github.com/SuhitAgarwal/websocket-expo-bug/blob/eb7bbb7eaa61c0ea4a6caf3f4693fced28fc2412/app/(tabs)/index.tsx#L10-L41) works fine on bare React Native without any imports from `ws` (like I had to add in this expo project)

The expected behavior: 
The app should work with this WebSocket implementation without any imports/errors (like it does on bare React Native)

also `ws` should be upgraded in this `expo-cli` because they recently had a [high severity event](https://github.com/websockets/ws/security/advisories/GHSA-3h5v-q93c-6h6q): #29819 

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.3.0 - /opt/homebrew/bin/node
      npm: 10.8.1 - /opt/homebrew/bin/npm
      Watchman: 2024.06.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
(node:73033) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by SuhitAgarwal** [comment]
I had discussed it extensively on [Discord](https://discord.com/channels/695411232856997968/1251279081815670866) too. And essentially, my server expects the WebSocket to be in the format I specified in my minimal example:
```typescript
const ws = new WebSocket("wss://echo.websocket.events", undefined, {
  headers: {
    Authorization: `Bearer-token-here`,
  },
});
```
Expo expects me to use the implementation for [WebSockets from MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket), but I want to use the implementation [here](https://github.com/websockets/ws/blob/0d1b5e6c4acad16a6b1a1904426eb266a5ba2f72/lib/websocket.js#L741-L746)

**Comment by keith-kurak** [comment]
Hi @SuhitAgarwal - looking closer at this, it looks like the `ws` library explicitly only supports Node.js environments, which is does not match the JS environment on a device. React Native documentation shows you should be able to use the build-in `WebSocket` implementation. It may also be the case that you could use `isomophic-ws` as described in the `ws` docs, which supports Non-node environments.

**Comment by SuhitAgarwal** [comment]
Yeah, I'm just confused as to why it works on a bare RN project (without imports) vs in an Expo managed project (even with the `ws` import). Feels like Expo might be missing a project import/dev dependency which React Native [seems to have](https://github.com/facebook/react-native/blob/main/package.json#L103)

**Comment by SuhitAgarwal** [comment]
I'd suggest to look more into this. i have a feeling that adding `ws` unde `devDependencies` might just fix this, but the isomorphic-ws works fine for now

**Comment by keith-kurak** [comment]
`ws` may be used by `react-native` in a node script used during the development process. Since it's in `devDependencies`, it's not going to be built with the package itself; it's not intended to be available at runtime in a React Native app. The error you see comes from `ws`, as the developer does not intend for it to be used in non-node contexts.

**Comment by keith-kurak** [comment]
Closing as `ws` doesn't appear to be intended to be used in RN. If you can reproduce an issue with regular `WebSocket`, we can take a closer look with that in a new issue.
