### ISSUE TITLE
expo-video breaks on Android (Error: Cannot find native module 'ExpoVideo' #29994)

### ISSUE THREAD

**Issue by sebastianrueckerai** [expo/expo#30006]
### Minimal reproducible example

https://github.com/sebastianrueckerai/ExpoVideoAndroidBug

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

I have an app that is working via expo go on iOS. 
I now want to make it work on android.

When scanning the QR code to run expo on my android phone I see the apps splash screen followed by this error:

```
Android Bundled 38ms node_modules/expo/AppEntry.js (1 module)
 ERROR  Error: Cannot find native module 'ExpoVideo', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
› Stopped server
```

I can't make sense of this error. I am using the "expo-av" and "expo-video" packages in my project, built a search for "ExpoVideo" returns no hits. Researching this error led me to believe that this happens when using non expo packages? But I may be wrong.
Any help on fixing or further investigating this would be welcome!

PS: Development builds are working on iOS but on Android I am stuck on the loading screen when trying to run them. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.1/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 10.0.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by cornejobarraza** [comment]
It looks like `expo-video` is not supported in Expo Go, check closed issue https://github.com/expo/expo/issues/28960.

Have you tried debugging why your Android app is stuck? Like checking if any errors come back or something similar?

If it works on iOS development builds, then maybe something specific needs to be updated in your code for Android

**Comment by sebastianrueckerai** [comment]
@cornejobarraza, thanks a lot for you help!

The development build works iOS. On Android I just see a white screen with "New update available, downloading..." in the bottom which appears to be stuck, waiting does not help. I am unsure where I could look for further error messages on this!

The minimal example and my project both run on Expo Go when I use iOS. So the problem seems to be specifically with Expo Go & Android.
For the sake of the next person debugging this for hours I would add a warning message when using expo-video and maybe also add it to the docs of this module.

**Comment by behenate** [comment]
@cornejobarraza is right, we don't offer support for expo-video in expo-go as of now. I'll add an appropriate warning to the docs.

Regarding your loading issue, have you tried running `adb reverse tcp:8081 tcp:8081`?

**Comment by Malickmimd** [comment]
Same issue @sebastianrueckerai but mine isn't working for both environment development build and expo go on android using expo video. Weird behavior ! likely it worked in development buil environment

**Comment by behenate** [comment]
@Malickmimd Are you using SDK 51?

**Comment by Malickmimd** [comment]
yes !

**Comment by Jasim-BinUmar** [comment]
I upgraded to SDK 52 after expo-video started working.
