### ISSUE TITLE
Orientation setting in app.json does not fully lock orientation (ex: status bar)

### ISSUE THREAD

**Issue by baryla** [expo/expo#3001]
I have a clean installation of an expo app and I noticed some weird behaviour. While testing the App on the Expo App on iOS 11, I turned the phone landscape and saw the status bar move with the orientation even though the orientation is set to **portrait** in `app.json`. Also because of this, the tab navigation shrinks too.

### Environment

```
System:
    OS: macOS 10.14
    Shell: 3.2.57 - /bin/bash
Binaries:
    Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
    npm: 6.5.0 - ~/.nvm/versions/node/v11.4.0/bin/npm
IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
npmPackages:
    expo: ^31.0.3 => 31.0.6 
    react: 16.6.3 => 16.6.3 
    react-native: ^0.57.8 => 0.57.8 
    react-navigation: ^3.0.8 => 3.0.8
App:
    iOS: 11
```
### Steps to Reproduce

1. Turn the device landscape

### Expected Behavior

The status bar should stay in a portrait orientation if the device is moved into a landscape orientation.

### Actual Behavior

The status bar changes orientation to landscape.

**Comment by ide** [comment]
We probably need to thread through the app.json settings all the way into the orientation module. In the meantime, try using the ScreenOrientation API and applying the portrait lock at runtime too: https://docs.expo.io/versions/latest/sdk/screen-orientation

**Comment by Okipa** [comment]
The orientation module does not lock the status bar orientation on iOS (tested on iPhone XR). The screen is locked but not the status bar, which still follows the device orientation.

**Comment by ppulwey** [comment]
Same issue here. This leads to unwanted behavior on Expo Camera module.

**Comment by mlshv** [comment]
Same for me. I tried to use `ScreenOrientation.allowAsync` method, but it didn't work. Tested on iPhone SE running iOS 12.3

**Comment by 100phel** [comment]
"sdkVersion": "32.0.0"
iPhone SE running iOS 12.2

Same issue. ScreenOrientation.allowAsync doesn't help.

**Comment by brentvatne** [comment]
can someone please post a video of what you're seeing? i'm not sure i understand

**Comment by 100phel** [comment]
> can someone please post a video of what you're seeing? i'm not sure i understand

https://drive.google.com/open?id=1EYlBiiNpc9YwmSP-69ryS9sSUYbREd33

**Comment by 100phel** [comment]
Any update on this ?

**Comment by jfenner** [comment]
I've tried locking with

`await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);`

But it still won't lock on Apple iPad Air 2.  Any update on this issue?

**Comment by shawwal** [comment]
> We probably need to thread through the app.json settings all the way into the orientation module. In the meantime, try using the ScreenOrientation API and applying the portrait lock at runtime too: https://docs.expo.io/versions/latest/sdk/screen-orientation

I tried but it's still not locking the splash screen when you open the app in landscape mode (tested in android and ios)

**Comment by IDEDOnline** [comment]
I am experiencing this issue also, the orientation is locked on android but refuses to lock on ios, tested on real device using app.json to set orientation and screenorientation api and neither have any effect on the devices ability to switch orientations this is using SDK 35

**Comment by Pitchlab** [comment]
Setting the orientation in app.json has no effect on iOS (13.3) with expo 36.

**Comment by lukmccall** [comment]
@Pitchlab, please check https://github.com/expo/expo/issues/5188#issuecomment-571578424.

**Comment by nferrara100** [comment]
I just encountered this myself. Weirdly, it only appears to happen when running in the client.
