### ISSUE TITLE
Expo Client iOS opening port 80

### ISSUE THREAD

**Issue by hamidfzm** [expo/expo#3002]
### Environment

```
  Expo CLI 2.6.13 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.6.13
```

In Expo client version 2.9.0

### Steps to Reproduce

Expo generates a QR code which points to exp://192.168.1.21:19000 but after scanning QR code from my iPhone and opening it in Expo Cli expo tries opening exp://192.168.1.21:80/node_modules

BTW it's a blank expo app.
![photo_2018-12-16_16-47-33](https://user-images.githubusercontent.com/5591800/50053996-5108fb80-0152-11e9-87ae-de4fd0a3533b.jpg)
![photo_2018-12-16_16-49-12](https://user-images.githubusercontent.com/5591800/50054026-8dd4f280-0152-11e9-9a6e-285f8aff1f38.jpg)

**Comment by ide** [comment]
Not sure what this could be. Maybe try clearing your caches (force quit the phone app, reinstall node_modules`, run `expo start -c`). Also the simpler your network configuration the better (proxies and non-standard WiFi routers might cause issues?).

**Comment by Maxwell2022** [comment]
It's also happening on Android. Not sure why the iOS and Android build are generating the bundle url targeting the port **80** whereas the `expo start` is running on port **19000**. I believe this should be a bug.

Apparently `clean project` and rebuild while the bundler is running on port `19000` is fixing this. Some say that Android Studio needs to be closed when starting the metro bundler and only opening it once started, maybe it's the same for iOS.

To Fix this, If your app is detached but you are using the expo SDK, you can run:

```
expo prepare-detached-build
```

it will update the `DEVELOPMENT_URL` in both iOS and Android project with the correct host / port. Just make sure the Metro bundler is running while you are doing this.

**Comment by cruzach** [comment]
Hey @hamidfzm- are you still running into this problem? If not, lmk what you ended up doing to resolve it 👍

**Comment by extrin** [comment]
I suffer from this bug too. Things suggested by @Maxwell2022 didn't help. 
I have the correct setting 'DEVELOPMENT_URL' but Android Studio always tries to go to port 80 instead of port 19000. Hope there is a solution...

**Comment by mrlambchop** [comment]
This happens for me on both iOS and Android constantly. Expo start is enough to update this file some times (and others, it doesn't touch it - super inconsistent!)

**Comment by cruzach** [comment]
If either of you can provide a way to repro this and what `expo-cli` and SDK versions you're using, that would go a long way in helping us troubleshoot this issue

**Comment by mrlambchop** [comment]
I managed to reproduce - over a few days now I was observing things:

- the development URL reset happens when a network interface changes state from disconnected to connected
- it "appears" that this only happens when a network interface changes IP address as well as changing state
- for me, it happens when going from a 10.1.0.x network to a 192.168.1.x network (and back again) ONLY if "expo start" is running at the time

expo --version == 3.0.10
sdk 34

**Comment by Chepman32** [comment]
I'm still suffer with this terrible bug, that not allows me to start develop with React Native

**Comment by audaxland** [comment]
I got around this by reinstalling npm via nvm instead of apt (https://github.com/nvm-sh/nvm)
I ran 
`sudo apt remove node npm`
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash`
`sudo npm update -g expo-cli`
and it worked for me

**Comment by z4nD4R** [comment]
Hi,

I have the same problem. The `exp:` URL is generated with port `:19000` but the EXPO APP is trying to reach port `:80`.

IP:19000 is reachable via Phone - pasting into URL I get JSON about my app..

```
  Expo CLI 3.19.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 12.16.2 - /usr/bin/node
      npm: 6.14.4 - /usr/bin/npm
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.19.2

```
