### ISSUE TITLE
@expo/fingerprint changes hash after setting runtime version

### ISSUE THREAD

**Issue by vonkanehoffen** [expo/expo#30024]
### Minimal reproducible example

https://github.com/vonkanehoffen/fingerprint-bug-repro

### What platform(s) does this occur on?

Android, iOS, Web

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

When I set `expo.runtimeVersion` in `app.json` to a hash generated by `@expo/fingerprint@0.9.0`, that in itself changes the next fingerprint hash the lib generates, meaning I can't use the lib to safely validate Expo Update compatibility. 

This didn't seem to be an issue for 0.6.0, however that (and using the EAS `"policy": "fingerprint"`) have other issues for me, so I'm a bit stuck!

To reproduce the issue, in the example repo:
1. `npm run fingerprint:validate` - note it doesn't match
2. `npm run fingerprint:set` then validate again - it does match.
3. Update `runtimeVersion` with that new hash (or any value)
4. `npm run fingerprint:validate` - note it doesn't match again

Any suggestions?  

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.14.0/bin/npm
      Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
hi there!
there's a breaking change from 0.9.0 where runtimeVersion is not skipping by default. please add `fingerprint.config.js` if you want to keep the behavior:

https://github.com/expo/expo/blob/main/packages/%40expo/fingerprint/CHANGELOG.md#090--2024-06-05

**Comment by vonkanehoffen** [comment]
Ah awesome I didn't spot that at all @Kudo ! Thanks very much! 😁

**Comment by Kudo** [comment]
the breaking change was supposed not included in sdk 51's expo-updates. but i managed to publish some fingerprint fixes for expo-updates based on the pr and introduced the breaking change. sorry again for the surprise. feel free to let me know if you have any questions or need assistance to add the `fingerprint.config.js`.  thanks!

**Comment by marcato15** [comment]
@Kudo can you point me to documentation about how to add a `fingerprint.config.js` file to our repo so we can use this functionality? I couldn't find anything about what the object is supposed to look like in that file.

**Comment by Kudo** [comment]
@marcato15 sorry late for the response. right now fingerprint documentation is inside its README https://github.com/expo/expo/blob/main/packages/%40expo/fingerprint/README.md#fingerprintconfigjs. let me know if you have any unclear questions.
