### ISSUE TITLE
[expo] Allow expo to be devDependency for local development. Autolinking Error:  ':expo-modules-core' could not be found in project ':expo'

### ISSUE THREAD

**Issue by savanakbari** [expo/expo#30055]
#### Summary:

 Allow `expo` to be `devDependency` for apps that only need them for local development and testing. It seems like expo is not able to [autolink](https://github.com/expo/expo/blob/main/packages/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle) when it is specified as a devDependency, but build works when `expo` is specified as direct `dependency`.  (I am also aware that expo should be direct dependency but we have case which I have described below which requires expo to be `devDependency`)

I found one related issue [expo-cli/96](https://github.com/expo/expo-cli/issues/96) which also tries to add `expo` as `devDependency` but it seems like fixing `expo doctor`

#### Description:
We have child packages that only publishes JS files needed for React native and this packages in turn get installed by parent app. Parent app governs what version of `expo/react-native` to use. 

Parent app is also React Native app and it has final say on what expo version needs to be used. We don't want to add expo as a dependency in child app since this expo is used only for local development/testing. So we want to add `expo` as a devDependency to child app. 

What **works** for child app 
```
  "dependencies": {
    "expo": "^51.0.0",
  },
  "devDependencies": {
    "expo-constants": "^16.0.2",
    "react": "18.2.0",
    "react-native": "0.74.2",
     .....
  },
```

What **does not work** for child app  (This is desired package.json setup for child apps)
```
  "dependencies": {
  },
  "devDependencies": {
    "expo": "^51.0.0",
    "expo-constants": "^16.0.2",
    "react": "18.2.0",
    "react-native": "0.74.2",
     .....
  },
```

Adding `expo` to `devDependency` gives following error when we try to run `npm run android`

```
* Where:
Build file '/Users/<username>/testexpodevdependency/node_modules/expo/android/build.gradle' line: 6 * What went wrong:
A problem occurred evaluating project ':expo'.
> Project with path ':expo-modules-core' could not be found in project ':expo'. * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
============================================================================== 2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> compileSdkVersion is not specified. Please add it to build.gradle * Try:
> Run with --stacktrace option to get the stack trace.
```

### What platform(s) does this occur on?

Android

### SDK Version

51.0.14

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 4.1.1 - /usr/local/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 23, 28, 29, 30, 31, 32, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-30 | Google Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google Play ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    Expo Workflow: bare

### Expo doctor output 

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check for issues with metro config
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions

### Minimal reproducible example

https://github.com/savanakbari/testexpodevdependency

#### Steps used in creating above repo.

Above create bare react native project using using below command and has expo added using following command

1. npx react-native init testexpodevdependency --version latest
2. npm install
3. npx install-expo-modules@latest 
     3a. move the `expo` dependency added in above command to `devDependency` section. Additionally move `react-native` and `react` to devDependency
4. npm i -D expo-constants.
5. npm run android

App should run but gives expo-modules-core not found error.

**Comment by savanakbari** [comment]
@Kudo - Appreciate any help with auto linking for expo here. Thank you.

**Comment by savanakbari** [comment]
https://github.com/expo/expo/blob/main/packages/expo-modules-autolinking/src/index.ts#L55-L60

Seems like only direct dependency are considereed when running auto link as it only considers `--only-project-deps` flag.
```
    .option(
      '--only-project-deps',
      'For a monorepo, include only modules that are the project dependencies.',
      true
    )
    .option('--no-only-project-deps', 'Opposite of --only-project-deps', false)
 ```

**Comment by Kudo** [comment]
hi there! could you check whether adding `args.contact(['--no-only-project-deps'])` works for you?

i tested the repro and it seems fine for me even without the `--no-only-project-deps`. i guess it's because other problems. my npm version is `10.7.0`. could you check whether update npm works for you?
also the path should exist `/path/to/testexpodevdependency/node_modules/expo-modules-core`. could you also check that?

**Comment by savanakbari** [comment]
Adding `args.concat(['--no-only-project-deps'])` for iOS and  `args += '--no-only-project-deps'` for Android works. Updating to npm version `10.7.0` does not work for me.  We also tested same with latest yarn version `4.2.2` and we are seeing same error `expo-modules-core' could not be found in project`

We are also experiencing inconsistent behavior when adding Expo as a devDependency. It seems to function correctly only for one of my co-workers, in the same way it does for you. However, in tests conducted with around 4-5 other people, adding Expo as a devDependency does not work.
