### ISSUE TITLE
CommandError: Timeout waiting for 'metro' dev server to close with EXPO_USE_FAST_RESOLVER=1

### ISSUE THREAD

**Issue by sync** [expo/expo#30056]
### Summary

When you kill metro with ctrl-c we get a: 

```
CommandError: Timeout waiting for 'metro' dev server to close
```

### What platform(s) does this occur on?

Android, iOS

### SDK Version

51

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.local/state/fnm_multishells/12898_1719532242888/bin/node
      Yarn: 1.22.22 - ~/.local/state/fnm_multishells/12898_1719532242888/bin/yarn
      npm: 10.2.4 - ~/.local/state/fnm_multishells/12898_1719532242888/bin/npm
      Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/anthonymittaz/.gem/ruby/2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.16 => 51.0.16 
      expo-router: ~3.5.17 => 3.5.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.3
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/sync/canaries

**Comment by byCedric** [comment]
@brentvatne this has been fixed, and backported to `sdk-51` through https://github.com/expo/expo/pull/30067. It's ready for deployment.

**Comment by brentvatne** [comment]
@byCedric 🥇

**Comment by byCedric** [comment]
This is released in `@expo/cli@0.18.21`, used in `expo@51.0.17` 😄

**Comment by BuscarRural** [comment]
I'm having the same problem, and my expo version is already 51.0.20, and expo-cli 0.18.25, any ideas ???

**Comment by Lucas20000903** [comment]
The same problem is happening in

- expo 51.0.21
- expo-cli 0.18.25

**Comment by albertorg** [comment]
Same error

**Comment by jpangan** [comment]
I have the same error with
- `expo: 6.3.10`
- `expo-cli: 6.3.10`

**Comment by Xuexue-Jiang** [comment]
killing any process run on the same 8081 port solved it for me. 

`lsof -i :8081`
`kill -9 <PID>
