### ISSUE TITLE
Android AVD SystemImage API 35 - Error - DETECT_SCREEN_CAPTURE

### ISSUE THREAD

**Issue by HatmanStack** [expo/expo#30053]
### Minimal reproducible example

https://github.com/expo/expo

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

This is the log output when loading an app on an AVD With:
Android Virtual Device Image API 35  
Expo Go 2.30.11
Expo 50.0.0

Issue is Resolved With:
Expo Go 2.31.2
Expo ~51.0.14

ERROR  Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': java.lang.SecurityException: Permission Denial: registerScreenCaptureObserver from pid=4735, uid=10197 requires android.permission.DETECT_SCREEN_CAPTURE, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838

### Expo Doctor Diagnostics

Expo Go 2.31.2
Expo ~51.0.14

**Comment by vonovak** [comment]
Hello and thanks for asking,
Your app is missing `DETECT_SCREEN_CAPTURE`.

If you're using https://docs.expo.dev/versions/latest/sdk/screen-capture/ make sure to rebuild your app after installing the package.

Thank you 🙂
