### ISSUE TITLE
Dependency incompatibility between expo-camera and @tensorflow/tfjs-react-native in Expo SDK 51

### ISSUE THREAD

**Issue by EmePin** [expo/expo#30060]
### Summary

I'm having trouble building my TensorFlow object detection app with Expo SDK 51. I need the @tensorflow/tfjs-react-native library to process images correctly, but this library requires expo-camera. When I try to install expo-camera using npx expo install expo-camera, I get a warn message about an overriding peer dependency. Specifically, @tensorflow/tfjs-react-native@1.0.0 looks for expo-camera@"^13.4.4. I tried installing expo-camera@"^13.4.4, but it didn't work for me.

 Anyway it works if I install expo-camera at the end  or if I use npm i --force.

The problem is that I want to get the apk and I am doing it with eas build, when I build with eas build -p android --profile preview, I get an npm error in the Install dependencies part and I can't build the APK correctly. In fact, to reproduce a minimal reproducible example, you should use npm install --force for the same reason.

![Captura de pantalla 2024-06-27 214028](https://github.com/expo/expo/assets/57578552/290ceae5-0198-48f8-b735-85dfd712fd27)
![Captura de pantalla 2024-06-27 222727](https://github.com/expo/expo/assets/57578552/6b44b7cd-505e-4ade-8767-fff516943636)

### What platform(s) does this occur on?

Android, iOS

### SDK Version

51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - D:\Aimee\Descargas\programas\node 20.10.0\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.3 - D:\Aimee\Descargas\programas\node 20.10.0\npm.CMD
    npmPackages:
      expo: ~51.0.14 => 51.0.16
      react: ^18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: ^0.74.2 => 0.74.2
      react-native-web: ^0.19.12 => 0.19.12
    Expo Workflow: managed

### Minimal reproducible example

[Minimal reproducible example](https://github.com/EmePin/TensorFlowExpo.git)

**Comment by byCedric** [comment]
Hi @EmePin! Unfortunately, it seems that `@tensorflow/tfjs-react-native` has not been updated to support SDK 51. Meaning that it likely won't work properly when disabling the peer dependency resolution of npm. But, you can still try:

https://stackoverflow.com/a/66620869

There is an active issue about this on the Tensorflow repo: https://github.com/tensorflow/tfjs/issues/8292. Since this is a third-party library, there is not much we can do to help resolve this.

Hope this helps!

**Comment by EmePin** [comment]
But isn't there a way for eas build to run npm i --force? or npm config set legacy-peer-deps true or npm install --save --legacy-peer-deps?

**Comment by YangMun** [comment]
I also encountered this issue and used expo-camera version 13.4.4 but faced another issue because the CameraView package was not available.
