### ISSUE TITLE
Expo build apk issue

### ISSUE THREAD

**Issue by mikias21** [expo/expo#30073]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by mikias21** [comment]
Hi Everyone, when running the app I'm working on using expo app no errors show and it works as expected, afterwards I generated apk file and install on android phone then app crushes. 
I used this command to see the source of the issue `adb logcat *:S ReactNative:V ReactNativeJS:V`   Then I get the following errors:

`
06-29 04:44:58.009 22021 22102 E ReactNativeJS: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCDatePicker' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["HeadlessJsTaskSupport","PlatformConstants","SourceCode","DeviceInfo","UIManager","DeviceEventManager","RNCSafeAreaContext","NativeAnimatedModule","SoundManager","I18nManager","Timing","ReanimatedModule","ImageLoader","RNGestureHandlerModule","StatusBarManager","StatusBarManager"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","NativeReactNativeFeatureFlagsCxx","RNSModule","FrameRateLogger","KeyboardObserver","ModalManager","RNCDatePicker"]}, js engine: hermes
06-29 04:44:58.011 22021 22102 I ReactNativeJS: Running "main
06-29 04:44:58.012 22021 22102 E ReactNativeJS: Invariant Violation: "main" has not been registered. This can happen if:
06-29 04:44:58.012 22021 22102 E ReactNativeJS: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
06-29 04:44:58.012 22021 22102 E ReactNativeJS: * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
`

Can someone please help how to fix this issue ? It has been days trying to fix but I couldn't.

I tried using this command 
`eas build:configure && eas update:configure && npx expo-doctor && npx expo prebuild && eas build --profile preview --platform android --clear-cache`

And the build failed with the following error
`
★ eas-cli@10.0.3 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

:bulb: The following process will configure your iOS and/or Android project to be compatible with EAS Build. These changes only apply to your local project files and you can safely revert them at any time.

√ Which platforms would you like to configure for EAS Build? » All

:tada: Your project is ready to build.

- Run eas build when you are ready to create your first build.
- Once the build is completed, run eas submit to upload the app to app stores.
- Learn more about other capabilities of EAS Build: https://docs.expo.dev/build/introduction
★ eas-cli@10.0.3 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

:bulb: The following process will configure your project to use EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
√ Configured eas.json.

:tada: Your app is configured to use EAS Update!

- Learn more about other capabilities of EAS Update: https://docs.expo.dev/eas-update/introduction/       
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
√ Created native directory
√ Updated package.json | no changes
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
√ Finished prebuild
★ eas-cli@10.0.3 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

Loaded "env" configuration for the "preview" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/variables/
Specified value for "android.package" in app.json is ignored because an android directory was detected in 
the project.
EAS Build will use the value found in the native code.

√ Created a new channel on project @mikias0x00/fintrack
Name  preview
ID    057729a5-84dd-4fd0-b0bf-1c9d5b67b834

√ We also went ahead and made a branch with the same name and have pointed the channel at it.
Name  preview
ID    5cefc2e0-4d46-4ecd-9d92-309b452033bf
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials Gypfjl9CB9 (default)

C:\Users\zardoz\Desktop\fintrack>eas build:configure && eas update:configure && npx expo-doctor && npx expo prebuild && eas build --profile preview --platform android --clear-cache
★ eas-cli@10.0.3 is now available.     
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.      

:bulb: The following process will configure your iOS and/or Android project to be compatible with EAS Build. These changes only apply to your local project files and you can safely revert them at any time.

√ Which platforms would you like to configure for EAS Build? » Android

:tada: Your project is ready to build.

- Run eas build when you are ready to create your first build.
- Once the build is completed, run eas submit to upload the app to app stores.
- Learn more about other capabilities of EAS Build: https://docs.expo.dev/build/introduction
★ eas-cli@10.0.3 is now available.     
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.      

:bulb: The following process will configure your project to use EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
√ Configured eas.json.

:tada: Your app is configured to use EAS Update!

- Learn more about other capabilities of EAS Update: https://docs.expo.dev/eas-update/introduction/       
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
√ Created native directory
√ Updated package.json | no changes
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
√ Finished prebuild
★ eas-cli@10.0.3 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

Loaded "env" configuration for the "preview" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/variables/
Specified value for "android.package" in app.json is ignored because an android directory was detected in 
the project.
EAS Build will use the value found in the native code.
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials Gypfjl9CB9 (default)

Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
✔ Compressed project files 1s (815 KB)
✔ Uploaded to EAS 1s

Build details: https://expo.dev/accounts/mikias0x00/projects/fintrack/builds/b35d45a7-9cb3-40e1-89bb-2f63405439cd

Waiting for build to complete. You can press Ctrl+C to exit.
✖ Build failed

:robot: Android build failed:
Unknown error. See logs of the Calculate expo-updates runtime version build phase for more information.  
`

**Comment by AlastairTaft** [comment]
I was getting Android crashes too, I had to upgrade from SDK 50 to 51 to fix it. I think 3 days Expo released a non backwards compatible update.
