### ISSUE TITLE
[Android] App glitches when opening

### ISSUE THREAD

**Issue by MariuzM** [expo/expo#30089]
### Minimal reproducible example

https://github.com/MariuzM/expo-starter/tree/main

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When i start opening app or do refresh in terminal i notice that app glitches for a second, the header kinda going on and off and elements keep moving. 

This example does have varying difference of colors but thats to show the problem. I have made a video also 

https://github.com/expo/expo/assets/36937039/83e3e09b-6fb5-4272-8f47-a28e8aea0bbe

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/dev/node-v20.11.0/bin/node
      Yarn: 1.22.22 - ~/dev/node-v20.11.0/bin/yarn
      npm: 10.2.4 - ~/dev/node-v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 10.0.2

**Comment by marklawlor** [comment]
Expo Router uses the React Navigation default components, which unfortunately suffer from this behaviour. I would suggest looking at the React Navigation issues and discussions for various work arounds, but common ones are either setting explicit heights or keeping the Splash Screen up until the app has loaded.

Creating new custom layouts for Expo Router is on the roadmap, but until then these issue should be raised on the React Navigation repo
