### ISSUE TITLE
Custom AppEntry not detected.

### ISSUE THREAD

**Issue by padsbanger** [expo/expo#3009]
Hello,

 I am trying to change the directory structure of my project to look like this:

![screenshot 2018-12-17 13 34 27](https://user-images.githubusercontent.com/471029/50087489-85d38c00-0200-11e9-8c95-e7b0b8770c77.png)

However I am unable to force Expo to use my custom AppEntry.js file, it still uses the old one that I have removed.

![screenshot 2018-12-17 13 35 46](https://user-images.githubusercontent.com/471029/50087544-ad2a5900-0200-11e9-880f-f599555653f6.png)

I have changed `package.json` to point to new AppEntry file:

```{
  "main": "./src/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
```

My `AppEntry` file looks like this:

```
import { KeepAwake, registerRootComponent } from 'expo';
import App from './components/App';

if (__DEV__) {
  KeepAwake.activate();
}

registerRootComponent(App);
```

And my `App.js` looks like this:

```import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Test123</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Expo diagnostics: 
![screenshot 2018-12-17 13 37 54](https://user-images.githubusercontent.com/471029/50087622-f7abd580-0200-11e9-9950-4f512ac7bb91.png)

**Comment by ide** [comment]
You might need to clear the cache (RN & Metro have lots of caches), run `expo start --clear` and see if it works?

**Comment by padsbanger** [comment]
Thank you, it works :)
