### ISSUE TITLE
Native facebook login on iOS

### ISSUE THREAD

**Issue by budziam** [expo/expo#3011]
### Environment
```
  Expo CLI 2.6.13 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.14.0 - /usr/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    npmPackages:
      @types/expo: ^30.0.0 => 30.0.0 
      @types/react: ^16.7.6 => 16.7.6 
      @types/react-native: ^0.57.9 => 0.57.9 
      @types/react-navigation: ^2.13.2 => 2.13.2 
      expo: ^31.0.2 => 31.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.0 => 3.0.0 
    npmGlobalPackages:
      expo-cli: 2.6.13
```
App target: iOS

### Steps to Reproduce

1. Open snack: https://snack.expo.io/SJXWW4re4 on iOS device
2. Click on asset image
3. On popup "Expo wants to use facebook to sign in" click Continue
4. Click "Log in with the Facebook app"
5. Click Open
6. Click Continue
7. You should see a white screen with a blue bar with Cancel button

### Expected Behavior

Step 7 should not happen. I would like to be redirected back to the app.

### Actual Behavior

Client is stucked on the white screen of death
![img_0330](https://user-images.githubusercontent.com/10908895/50093390-d226c800-0210-11e9-9417-126624b8b46a.PNG)

### Reproducible Demo

https://snack.expo.io/SJXWW4re4

**Comment by budziam** [comment]
No, i did not try to reproduce it in a standalone app. I needed it for my development process.
I cannot find the quote you pasted. I can only see sth like this

![image](https://user-images.githubusercontent.com/10908895/50158605-d9afa500-02d4-11e9-9e99-2f679d4b2b52.png)

**Comment by ide** [comment]
The docs must have changed recently - here is the previous version: https://docs.expo.io/versions/v30.0.0/sdk/facebook. In any case, the native FB app will work only with standalone apps. If there's a bug in Expo.Facebook you can do something like:

```js
if (Constants.appOwnership === 'standalone') {
  // 'native'
} else {
  // 'browser'
}
```

**Comment by budziam** [comment]
Okay, thanks for your help

**Comment by HossamSamir** [comment]
I have the same problem with the latest expo version `"expo": "32.0.0"`
tried the app on expo client, app store standalone version and testFlight version, and I confirm that the same white screen of death happens on all of them :skull:
android is working fine though..
the only workaround for now is to use the `behaviour:'web'`

**Comment by HossamSamir** [comment]
`behavior: 
    Platform.OS == "ios" ? 
     Expo.Constants.statusBarHeight < 40 ?
         "web" 
          : 
         "native" 
    :
     "native"`

**Comment by lovesharma1995** [comment]
> `behavior: Platform.OS == "ios" ? Expo.Constants.statusBarHeight < 40 ? "web" : "native" : "native"`

@HossamSamir it works for me but I have to log in every time again and again. I want it to keep myself logged in. Any suggestions?

**Comment by IAmAbhishekTomar** [comment]
I have the same... 

Details: https://www.reddit.com/r/reactnative/comments/bxtp4w/fiarbase_facebook_auth_with_expo/?utm_source=share&utm_medium=ios_app

Video: https://www.reddit.com/r/reactnative/comments/bylc13/firebase_facebook_auth_react_native_expo/?utm_source=share&utm_medium=

My app is working if I add a red highlighted line of code but this is launch auth page in web view and I don't want web view I want native Facebook auth... Check this link for code.

Code: https://www.reddit.com/r/reactnative/comments/bynbny/firebase_facebook_auth_redirection_issue_with/?utm_source=share&utm_medium=ios_app

**Comment by lovesharma1995** [comment]
> I have the same... #4511
> 
> Details: https://www.reddit.com/r/reactnative/comments/bxtp4w/fiarbase_facebook_auth_with_expo/?utm_source=share&utm_medium=ios_app
> 
> Video: https://www.reddit.com/r/reactnative/comments/bylc13/firebase_facebook_auth_react_native_expo/?utm_source=share&utm_medium=
> 
> My app is working if I add a red highlighted line of code but this is launch auth page in web view and I don't want web view I want native Facebook auth... Check this link for code.
> 
> Code: https://www.reddit.com/r/reactnative/comments/bynbny/firebase_facebook_auth_redirection_issue_with/?utm_source=share&utm_medium=ios_app


I have done it by using a secure store, these are the steps I have used:
-first i used onLoad in constructor and call login function like this, this.onLoad = this.login()
-then in try block I used if else statement in which if condition works when a secure store is set in which it is redirecting to me on the log in page and in else it stores the access token value in secure store(this is for the first time log in).
ps: I used behaviour as web i.e. behavior: "web",

**Comment by btang28** [comment]
'web' behavior is such a hassle to users, of having to type up credentials, which is the entire purpose of adding a facebook login button. 

Is there no better solution for this?

**Comment by lovesharma1995** [comment]
> 'web' behavior is such a hassle to users, of having to type up credentials, which is the entire purpose of adding a facebook login button.
> 
> Is there no better solution for this?

The other behavior only works in android, not in ios

**Comment by esamelson** [comment]
Hi there -- in SDK 35, the only supported login mode is `'browser'`. This is a limitation of the underlying native Facebook SDK. I'm going to go ahead and close this as it is outdated and no longer applicable. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
