### ISSUE TITLE
[expo-media-library] No suitable URI request handler found for ph:// after enabling new architecture

### ISSUE THREAD

**Issue by khushal87** [expo/expo#30116]
### Minimal reproducible example

https://github.com/khushal87/expo-media-library-bug/tree/new-architecture

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

This issue was fixed in #29747 but is still not working when new architecture is enabled. The same issue as the old arch that was fixed pops up with the new architecture.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/khushalagarwal/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31, 33, 34
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.17 => 51.0.17
      expo-router: ~3.5.17 => 3.5.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 7.6.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with the metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match the versions required by the installed Expo SDK

**Comment by khushal87** [comment]
Hey @alanjhughes, can you give it a look? Thanks 😄

**Comment by tiagotwistag** [comment]
I have the same issue, any progress?

**Comment by coolsoftwaretyler** [comment]
Hey folks, I was poking around to see if I could help, and I am going to explore what react-native-cameraroll did in https://github.com/react-native-cameraroll/react-native-cameraroll/pull/632

In the meantime, the workaround with `localUri` definitely works. @khushal87 - I pulled your reproduction project and made this change to the main app file and have things working:

```patch
diff --git a/app/(tabs)/index.tsx b/app/(tabs)/index.tsx
index 18dbb98..920d0b8 100644
--- a/app/(tabs)/index.tsx
+++ b/app/(tabs)/index.tsx
@@ -1,18 +1,16 @@
-import { useState, useEffect } from "react";
+import { useState } from "react";
 import {
   Button,
-  Text,
   SafeAreaView,
   ScrollView,
   StyleSheet,
   Image,
-  View,
   Platform,
 } from "react-native";
 import * as MediaLibrary from "expo-media-library";
 
 export default function App() {
-  const [photos, setPhotos] = useState<MediaLibrary.Asset[]>([]);
+  const [photos, setPhotos] = useState<string[]>([]);
   const [permissionResponse, requestPermission] = MediaLibrary.usePermissions();
 
   async function getPhotos() {
@@ -23,7 +21,17 @@ export default function App() {
       mediaType: [MediaLibrary.MediaType.photo, MediaLibrary.MediaType.video],
       sortBy: [MediaLibrary.SortBy.modificationTime],
     });
-    setPhotos(fetchedPhotos.assets);
+
+    const localUris = (await Promise.all(
+      fetchedPhotos.assets.map(async (asset) => {
+        const assetInfo = await MediaLibrary.getAssetInfoAsync(asset);
+        return assetInfo.localUri;
+      })
+    )) as string[];
+
+    const filteredLocalUris = localUris.filter((uri) => uri !== undefined);
+
+    setPhotos(filteredLocalUris);
   }
 
   return (
@@ -32,7 +40,7 @@ export default function App() {
       <ScrollView>
         {photos &&
           photos.map((photo) => (
-            <Image source={{ uri: photo.uri }} width={50} height={50} />
+            <Image source={{ uri: photo }} width={50} height={50} />
           ))}
       </ScrollView>
     </SafeAreaView>
```

Seen working here:

https://github.com/user-attachments/assets/f05df9e3-ef37-46d5-b4f8-fe440d8a23bf

**Comment by coolsoftwaretyler** [comment]
Oh yeah, I think it'll be as simple as adding the codegen config they're using in `react-native-cameraroll`:

https://github.com/react-native-cameraroll/react-native-cameraroll/blob/447365b308f21d91f968bd60b114ee5875d67b08/package.json#L118-L126

I've got your reproducer app working on new architecture with just that change. I'll put together a PR.
