### ISSUE TITLE
Migration from SDK 50 to 51 breaks loading local assets (png, mp3, jpg,...)

### ISSUE THREAD

**Issue by christophemenager** [expo/expo#30123]
### Summary

After completing a migration to SDK 50 to SDK 51.0.17, no local asset can be loaded (images are grey, sounds are not loaded)

This sounds like a metro issue because using the default react-native config file fixes the issue.

This BREAKS:
```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

module.exports = config;
```

This WORKS:
```
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
````

Do you have any ideas where this issue might come from?

I read some stackoverflow mentioning dependencies version mismatch but it's not my case (the versions I use are compatible with expo doctor)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

 "@faker-js/faker": "8.4.1",
    "@gorhom/bottom-sheet": "4.6.3",
    "@react-native-clipboard/clipboard": "1.14.1",
    "@react-native-community/blur": "4.4.0",
    "@react-native-community/geolocation": "3.2.1",
    "@react-native-community/netinfo": "11.3.2",
    "@react-native-voice/voice": "3.2.4",
    "@react-navigation/bottom-tabs": "6.5.20",
    "@react-navigation/native": "6.1.17",
    "@react-navigation/native-stack": "6.9.26",
    "@sentry/react-native": "5.24.1",
    "@shopify/flash-list": "1.6.4",
    "@shopify/react-native-skia": "1.3.7",
    "@shopify/restyle": "2.4.4",
    "@supabase/supabase-js": "2.44.2",
    "@tanstack/query-sync-storage-persister": "5.49.0",
    "@tanstack/react-query": "5.49.0",
    "@tanstack/react-query-persist-client": "5.49.0",
    "app-icon-badge": "0.0.15",
    "date-fns": "3.6.0",
    "expo": "51.0.17",
    "expo-application": "5.9.1",
    "expo-av": "14.0.6",
    "expo-battery": "8.0.1",
    "expo-constants": "16.0.2",
    "expo-dev-client": "4.0.19",
    "expo-device": "6.0.2",
    "expo-font": "12.0.7",
    "expo-haptics": "13.0.1",
    "expo-image": "1.12.12",
    "expo-keep-awake": "13.0.2",
    "expo-linear-gradient": "13.0.2",
    "expo-location": "17.0.1",
    "expo-navigation-bar": "3.0.6",
    "expo-speech": "12.0.2",
    "expo-splash-screen": "0.27.5",
    "expo-status-bar": "1.12.1",
    "expo-system-ui": "3.0.6",
    "fuse.js": "7.0.0",
    "geolib": "3.3.4",
    "i18next": "23.11.5",
    "lodash.groupby": "4.6.0",
    "mixpanel-react-native": "2.4.1",
    "moti": "0.29.0",
    "react": "18.2.0",
    "react-hook-form": "7.52.0",
    "react-i18next": "14.1.2",
    "react-native": "0.74.2",
    "react-native-calendars": "1.1305.0",
    "react-native-compass-heading": "1.5.0",
    "react-native-gesture-handler": "2.17.1",
    "react-native-get-random-values": "1.11.0",
    "react-native-keyboard-controller": "1.12.4",
    "react-native-map-link": "3.5.0",
    "react-native-maps": "1.15.6",
    "react-native-mmkv": "2.12.2",
    "react-native-modal": "13.0.1",
    "react-native-pager-view": "6.3.3",
    "react-native-permissions": "4.1.5",
    "react-native-progress": "5.0.1",
    "react-native-reanimated": "3.12.1",
    "react-native-reanimated-carousel": "3.5.1",
    "react-native-render-html": "6.3.4",
    "react-native-safe-area-context": "4.10.7",
    "react-native-screens": "3.32.0",
    "react-native-store-review": "0.4.3",
    "react-native-svg": "15.3.0",
    "react-native-vision-camera": "4.3.2",
    "react-native-volume-manager": "1.10.0",
    "react-native-webview": "13.10.4",
    "react-native-worklets-core": "1.3.3",
    "react-query-kit": "3.3.0",
    "rive-react-native": "7.3.0",
    "semver": "7.6.2",
    "uuid": "10.0.0",
    "zod": "3.23.8",
    "zustand": "4.5.4"

### Environment

Note:  Expo Workflow is `bare` because I am building with xcode and android studio but, android and ios folders have not been modified manually

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/Projects/eskap-mobile/node_modules/.bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.8.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
      Watchman: 2024.03.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/christophemenager/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: 51.0.17 => 51.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: bare

### Reproducible demo

Simply loading an image from local file does not work (grey background)
```
 <Image
        style={{
          position: 'absolute',
          bottom: 0,
          right: 0,
        }}
        source={require('./path-to-asset')}
      />
```

**Comment by LouisLec** [comment]
Hi @christophemenager , I have the same problem with images and fonts not loading. Have you found a solution?

**Comment by christophemenager** [comment]
I spent 2 days on this issue and finally gave up, so unfortunately no!

I tried a lot of different setups, and the only interesting thing I found is that using `metro` from `react-native` and not expo is fixing the issue.

Other issues on Stackoverflow mention dependency mismatches that can be fixed with `expo-doctor`, but that was not my case.

**Comment by christophemenager** [comment]
@LouisLec did you find a solution?

**Comment by frncs-eu** [comment]
I just faced this issue myself.

@christophemenager check if you have anything inside your dependencies that's causing the react-native dependency to be installed twice, as this messes things up.
In our case it was:
```bash
yarn why react-native
├─ @types/react-native-calendars@npm:1.1264.7
│  └─ react-native@npm:0.74.5 [11fe9] (via npm:* [11fe9])
│
└─ company@workspace:.
   └─ react-native@npm:0.74.3 [f48a4] (via npm:0.74.3 [f48a4])
```
so apparently a definitely typed dependency was causing this mess due to importing react-native as a dependency (instead of assuming it as a peer) 

We solved this via yarn resolutions, setting the same version as the one reccomended by the expo sdk

**Comment by christophemenager** [comment]
@frncs-eu super interesting, I will have a look tomorrow, thanks!

**Comment by MikhailR1337** [comment]
@christophemenager I had the same issue. I used  npx expo-doctor@latest and then the command that was recommended by doctor -> npx expo install --check probably

**Comment by christophemenager** [comment]
Thanks everyone for your help! My issue was with react-native-clipboard, which was installing react-native 0.73, I fixed it by using clipboard from expo and removing this lib
