### ISSUE TITLE
Using `renderRouter` in any test causes timeout

### ISSUE THREAD

**Issue by jakejdavis** [expo/expo#30137]
### Minimal reproducible example

https://github.com/jakejdavis/expo-router-testing-reprod

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Whenever I use `renderRouter` in a test case, there is a timeout:
```

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

    > 1 | import { renderRouter, screen } from "expo-router/testing-library";
        | ^
      2 | import { Text } from "react-native";
      3 |
```

This may be due to the fact that I am using @nx/jest, as shown in https://github.com/jakejdavis/expo-router-testing-reprod

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 4.2.2 - ~/.nvm/versions/node/v20.10.0/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.8 => 0.18.8
      babel-preset-expo: ^11.0.11 => 11.0.11
      expo: ~51.0.17 => 51.0.17
      expo-router: ^3.5.17 => 3.5.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: 0.19.12 => 0.19.12
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Your `jest.config.js` is using `"@nx/jest/preset"`. If you log the values of `"@nx/jest/preset"`, you can see that it setting some values that are incompatible with React Native (such as setting the test environment to `js-dom`).

When I remove the preset, the tests pass fine. I'm assuming there are some properties of the preset that you desire (the resolver?), I would consult the `nx` documentation and pick those values from the preset.
