### ISSUE TITLE
Sqlite bug when inserting values greater than 7 digits

### ISSUE THREAD

**Issue by KakarN** [expo/expo#3013]
### Environment

  Expo CLI 2.6.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.6.0

target (iOS, Android, Client, Standalone)

### Steps to Reproduce

1. Create or open a Sqlite database.
`Eg. const db = SQLite.openDatabase("real_sqlite")`

2. Create a table with a Real datatype column.
`Eg. CREATE TABLE if not exists expenditures (id integer primary key, max_amount real not null);`

3. Insert greater than 7 digit value to the Real datatype,
`Eg. INSERT INTO expenditures (max_amount) values (50000123);`

4. And get the result back, you will notice the column value is changed to 50000124.
```
Eg. SELECT * FROM expenditures;
[
{id:1,,max_amount:50000124}
]
```

### Expected Behavior

I expected to get back the inserted values into the column values, (Eg. 50000123). 

### Actual Behavior

But instead, I got a different value (Eg. 50000124).

### Reproducible Demo

[Snack link to the Demo](https://snack.expo.io/@kakarn/sqlite-test)

**Comment by ide** [comment]
The Snack works fine on iOS; perhaps somewhere on Android a number is getting treated as a 32-bit float.

On a tangent because the test column is called "expenditures", you might want to read this: https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html
