### ISSUE TITLE
Characters entered in TextInput in wrong order on older iOS device

### ISSUE THREAD

**Issue by CodingItWrong** [expo/expo#30144]
### Minimal reproducible example

https://github.com/CodingItWrong/expo-text-input-sandbox

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

EXPECTED: when you type into a `TextInput` on any device, characters are always entered in the order they are typed. On slower devices they may be entered slowly; it might even be satisfactory to drop characters. But any characters that appear should be in the order they were typed.

ACTUAL: when typing quickly into a `TextInput` on a 2014 iPad running iOS 15 using the on-screen keyboard, some characters are entered out of order. It is as if the character is placed after the insertion point. YouTube screen recording: https://youtube.com/shorts/E7zfsvkKZlw?feature=share

NOTE: this may very well be an issue in React Native core rather than in Expo per se. I wasn't sure where best to put this issue, but following the [React Native bug report template](https://github.com/facebook/react-native/issues/new/choose) it said "If you're using Expo and you're noticing a bug, [report it here](https://github.com/expo/expo/issues)."

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.0/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.15.0/bin/npm
      Watchman: 2024.06.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/josh.justice2/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.17 => 51.0.17
      expo-router: ~3.5.17 => 3.5.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 10.0.3
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by gorbypark** [comment]
I've noticed this before and it seems to happen on high end devices as well, just not as often.  I don't know the root cause, but the issue is generally having the TextInput's onChangeText hooked into useState, which causes a re-render on every key stroke.  I haven't found a good solution besides moving to an uncontrolled input (eg: don't set state, but set a ref, and then get the value of the ref when needed, like on the submit button, etc) or using something like react-hook-forms or other form state libraries.

**Comment by CodingItWrong** [comment]
Thank you @gorbypark - upon an initial try, using `react-hook-form` does seem to work as a workaround.

I do think this is something for the Expo/React Native teams to ideally look into, though. Since the RN docs currently [show TextInput value stored in useState](https://reactnative.dev/docs/textinput), it would be good if this is fixed if that is the intended behavior. Or, if it's not recommended to use `useState`, that would be good to be in the docs.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
In this case, this would be a bug report for react native core.

Controlling the textinput state is tricky. I'd recommend using the `defaultValue` prop https://reactnative.dev/docs/next/textinput#defaultvalue together with a change listener, if possible.

Thank you 🙂
