### ISSUE TITLE
Camera images always have a ratio of 1:1 on Android

### ISSUE THREAD

**Issue by 0x6D70** [expo/expo#30154]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/apps/bare-expo

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

In the ``bare-expo`` app the resulting image of the camera always has a ratio of 1:1. This bug is only reproducible in a development build on a physical android device (it works in the emulator).
The ratio should be ``4:3`` as specified in the ``ratio`` prop of the ``CameraView`` and according to the documentation the ratio should be ``4:3`` or ``16:9`` but not ``1:1``.

Here is what the image looks like:
![image](https://github.com/expo/expo/assets/43414123/4b22ddf9-8632-41c4-9356-bb822e4bcaa4)

### Environment

reproducible in bare-expo

### Expo Doctor Diagnostics

reproducible in bare-expo

**Comment by alanjhughes** [comment]
Hi @0x6D70 - How are you testing this? This change has not been published yet

**Comment by 0x6D70** [comment]
I have tested it on the main branch.
But I have exactly the same issue (that the image is always has a ratio of ``1:1``) in my own app which is using expo-camera version 15.0.12

**Comment by alanjhughes** [comment]
I've looked into this and you need to remove the `pictureSize` prop or set it to an empty string. You cannot set both `pictureSize` and `ratio` on the native side Android will throw an exception. If `pictureSize` is set, that is all we set. The aspect ratio is determined by the selected size.

**Comment by alanjhughes** [comment]
Updated docs in  #30195
