### ISSUE TITLE
How is `Constants.manifest.env` supposed to work?

### ISSUE THREAD

**Issue by koenpunt** [expo/expo#3015]
### Environment

```
$ expo diagnostics

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.1 - ~/.nodenv/versions/10.14.1/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nodenv/versions/10.14.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.0.12 => 4.0.12
      @types/expo: ^31.0.1 => 31.0.1
      @types/react: ^16.7.13 => 16.7.13
      @types/react-native: ^0.57.17 => 0.57.17
      @types/react-navigation: ^2.13.7 => 2.13.7
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.6 => 3.0.6
    npmGlobalPackages:
      expo-cli: 2.6.14
```

According to the source `Constants.manifest.env` is merged into `process.env`, and thus gives me reason to believe there should be a way to use this to configure an application.

https://github.com/expo/expo/blob/3b6a24fbd50e7747a900d23f09684710d8af7d67/packages/expo/src/Expo.ts#L10-L12

But I tried adding an `env` property to `app.json`, but that doesn't seem to work;

```
[23:33:18] Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v31.0.0/guides/configuration.html
[23:33:18]  • should NOT have additional property 'env'.
```

Or if this is not the case, what's the recommended way to add a configuration file, which every other person working on the project can override without changing the shared config file.

**Comment by ide** [comment]
`Constants.manifest.env` will be populated with environment variables that start with `EXPO_` or `REACT_NATIVE_`. See: https://github.com/expo/expo-cli/blob/4b41fc5333d22c8475572aaac6486f600306252f/packages/xdl/src/Project.js#L1658

**Comment by koenpunt** [comment]
Alright, thanks!
I couldn't find that when searching for combinations of "expo" "environment" and "configuration" anywhere though..
Is it supposed to be an undocumented feature?

**Comment by Asday** [comment]
Doesn't appear to work any more.  On my project, devs run an API locally however they may choose, and the app must know where to find it.  The correct way of doing that in every other software project is the developer setting the environment variable `API_HOST` to match their environment, which the app can then consume.

I have both `API_HOST` and `EXPO_API_HOST` set, and not only do they not turn up in `Constants.manifest.env`, there isn't even an `env` property in `Constants.manifest`.  I tried adding `"env: {},"` to `app.json`, and the `env` property appeared on `Constants.manifest`, but is empty.

Obviously I could tell the developers to make the change to that file but not commit it, but we all know how that ends - and we shouldn't have to do that anyway.
