### ISSUE TITLE
Standalone Android causes Uncaught Error: TypeError: TypeError: undefined is not a function (evaluating '_navigationStore2.default.getStateForAction(action,state)')

### ISSUE THREAD

**Issue by futrespec** [expo/expo#3016]
Lost a few days to this error and cant seem to figure out why this error occurs only for standalone apk install.

### Environment
Android

### Steps to Reproduce

(Write your steps here:)

1. Run App within Expo. DrawerItem opens just fine. Fully functional with no issues.
2. Build APK using exp build:android
3. Install and run app on android. Opening Drawer leads to Blue Error Screen "Something went Wrong"
4. Inspecting logs shows the following 

Uncaught Error: TypeError: TypeError: undefined is not a function (evaluating '_navigationStore2.default.getStateForAction(action,state)')

The error is located at:
in NavigationContainer
in App
in Unknown
in App
in News
in Sceneview
in RCTView
in RCTView
in RCTView

reducer@cached-bundle-experience ...
21:50:22 Fatal Error

### Expected Behavior

Drawer should have loaded as with Expo Client

Uncaught Error: TypeError: TypeError: undefined is not a function (evaluating '_navigationStore2.default.getStateForAction(action,state)')

The error is located at:
in NavigationContainer
in App
in Unknown
in App
in News
in Sceneview
in RCTView
in RCTView
in RCTView

reducer@cached-bundle-experience ...
21:50:22 Fatal Error

Here is the expo app.json file

{
  "expo": {
    "name": "Apollo Universal Starter Kit",
    "icon": "../../app.png",
    "version": "1.0.0",
    "slug": "apollo-universal-starter-kit",
    "sdkVersion": "27.0.0",
    "ios": {
      "bundleIdentifier": "com.sysgears.apollokit"
    },
    "android": {
      "package": "com.sysgears.apollokit"
    }
  }
}

Based on the Classes in the logs it seems this is an issue with react-navigation and how those libraries are packaged by expo.

Thanks for looking over the issue.
Any help is greatly appreciated

**Comment by ide** [comment]
This issue looks specific to your app -- can you debug further and if the root cause is inside of Expo let us know about it?

**Comment by futrespec** [comment]
Whats really concerning here is the inconsistent behavior between expo client and standalone apk behavior. Its very difficult to identify the next debug steps when its not really clear what is different between these two deployments that could possibly cause this issue. 

Also this does not seem unique to just this app, it seems to happen with other apps and libraries as well. For examples - #2693, #2533, #2078 and others. In some cases its mis-match of sdk version, and forces use of different component libraries so the real question is what does the exp build process do incorrectly that causes the difference in behavior between the exp client and standalone app?
