### ISSUE TITLE
[EAS Build] SecureStore Data Empty After Updating using TestFlight From SDK 41 to SDK 51

### ISSUE THREAD

**Issue by DB1703** [expo/expo#30174]
### Minimal reproducible example

project is private

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I currently have a production build of an iOS app in the app store using SDK 41. Recently I updated to SDK 51 to take advantage of latest dependencies and future support

After upgrading the app to SDK 51 and building using EAS Build I published my app to TestFlight for internal testing. However, the user data from SecureStore does not transfer between the versions. The EAS built app no longer has any access to the previous information stored in SecureStore.
I have been trying to see information and found out that there´s been a change during SDK 41 for the way EAS Build handles the key-access-groups.

As descripted [on this issue](https://github.com/expo/expo/issues/20400) I tried adding manually the:
`"entitlements": {
        "keychain-access-groups": ["XXXXXXXX.*", "com.apple.token"]
      } `
      
      And still not working.
      Here's the entitlements for the production app with SDK 41
![2 0 38](https://github.com/expo/expo/assets/100162483/61b5c36a-ef68-40bd-8fa8-5530b3de18d2)
And here they are the entitlements for the build from TestFlight with SDK 51

![2 2 26](https://github.com/expo/expo/assets/100162483/0a012909-f9fe-482b-9e51-0433d6b901da)

As you can see in both images, the keychain-access-groups is the same one, and still the data does not appears.

### Environment

`expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-233.14808.21.2331.11842104
    npmPackages:
      expo: ~51.0.17 => 51.0.17
      react: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    Expo Workflow: managed`

### Expo Doctor Diagnostics

`✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!`

**Comment by bruscantini** [comment]
@DB1703 Was there a solution here? I tried adding to keychain-access-groups but that didn't help:
```
    "expo": {
        "ios": {
          "entitlements": {
            "keychain-access-groups": ["<TEAM-ID>.*", "com.apple.token"]
          }
        },
    }
```

**Comment by DB1703** [comment]
@bruscantini I could not find a solution to this problem. We were forced to publish a new app, because we weren't entirely sure of what could happen on production. Although, if TestFlight is not capable of inheriting the data I see it almost impossible to happen. 😔
I even called Apple and they didn't give me a solution either
