### ISSUE TITLE
expo-apple-authentication: Switch must be exhaustive

### ISSUE THREAD

**Issue by ItzNimaB** [expo/expo#30179]
### Minimal reproducible example

Build expo app with expo-apple-authentication on xcode 16

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

When building with xcode i got 2 errors.
The first was with sentry, which i resolved by updating to the latest version.

The second problem was with expo-apple-authentication, and i had to make slight changes to the package to fix it.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - /usr/local/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - /usr/local/bin/npm
      Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.1 => 0.18.8 
      expo: ~51.0.17 => 51.0.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  @expo/vector-icons@14.0.0 - expected version: ^14.0.2
  @sentry/react-native@5.24.1 - expected version: ~5.22.0
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by billyjacoby** [comment]
What was the change that had to be made here? I'm seeing the same error.

**Comment by haveamission** [comment]
Seeing the same problem, anyone know the fix?

**Comment by interstellrau** [comment]
We've got our apps successfully building by editing the expo-apple-authentication/ios/AppleAuthenticationExceptions.swift file

All that needs to be added is a default case for the exceptionForAuthorizationError function.


`func exceptionForAuthorizationError(_ error: ASAuthorizationError) -> Exception {
  switch error.code {
  case .unknown:
    return RequestUnknownException()
  case .canceled:
    return RequestCanceledException()
  case .invalidResponse:
    return InvalidResponseException()
  case .notHandled:
    return RequestNotHandledException()
  case .failed:
    return RequestFailedException()
  case .notInteractive:
    return RequestNotInteractiveException()
  default:
    return RequestUnknownException()
  }
}
`

**Comment by syntheticencounters** [comment]
Same issue with us. As @interstellrau mentioned, you'll need to add the rest of the cases for the switch to be exhaustive. Xcode should be able to autofill those for you. You can use patch-package to persist the change through future installs until the issue is fixed upstream.
