### ISSUE TITLE
SQLite doesn't allow INSERT with Special Characters

### ISSUE THREAD

**Issue by 19TT94** [expo/expo#30177]
### Summary

I'm trying to use the `expo-sqlite` package to store json data locally for use when the app is offline. When I went to insert these json strings to the database I got the error `Calling the 'prepareAsync' function has failed -> Caused by: Error code 1: unregonized token`. I thought this was because the json was not escaped properly, but after investigation I found that certain characters are unaccepted even as text strings (ex: °F, Ω, ÷, ×, x). Is this a bug or is there a correct way to escape/encode those characters? Note: It is not going to be practical for me to identify and replace these characters in the json object which is something I started to try before coming to the issues.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

"expo": "~51.0.18","expo-sqlite": "~14.0.4"

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
      Watchman: 2024.06.10.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.18 => 51.0.18
      react: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: managed

### Reproducible demo

https://github.com/Hero-Services/sqlite-json-issue

**Comment by 19TT94** [comment]
@brentvatne @Kudo is anyone able to look at this? I'm still experiencing issues and I'm going to need to pivot if I can't resolve this soon.

**Comment by brentvatne** [comment]
@19TT94 - @Kudo is currently ooo on holiday, he'll be able to look at it when he's back in a week. if you want to investigate it on your own and send a pr, that'd be very welcome!

you can also use an alternative react-native sqlite library if you need. unless you have a particular reason for needing expo-sqlite instead of others, they all provide the core features of sqlite.

**Comment by j1h23** [comment]
I am also seeing the issue, but only on iOS. I have found 2 temporary workaround:

1. Don't use runAsync, use execAsync instead. The runAsync method includes the prepareAsync call, which can be avoided if you use execAsync. You should read the documentation about the drawbacks of using execAsync.
2. Add a line break at the end of your query. This seems to allow the statements to work with special characters. Not sure why...

**Comment by j1h23** [comment]
Shares similar characteristics as the below issue, except I did not encounter this issue in Android, only on iOS.

https://github.com/expo/expo/issues/30492
