### ISSUE TITLE
[docs] Request: Expand and clarify expo-router documentation

### ISSUE THREAD

**Issue by evelant** [expo/expo#30171]
### Summary

I'm working on implementing expo-router in my app and I have encountered a number of confusing behaviors that the docs don't clarify. If someone knowledgeable about the internals of expo-router could update the docs to clarify these things I think it would probably help a lot of people and reduce the number of issues filed here. Specifically here are some of the points of confusion I ran into in no particular order:

1. With filesystem based routing is `index.tsx` required in every directory? Routes don't seem to get picked up as expected without it in some cases.
2. When organizing files with (groups) what is the behavior of and caveats of nesting groups such as `/app/(root)/(authenticated)/tasks/index.tsx`? 
3. When organizing files with (groups) how should paths be constructed for navigating? With the example above `router.push("/(root)/(authenticated)/tasks")`, `router.push("/tasks")`, and `router.push("/(root)/(authenticated)/tasks/index")` will all behave in a similar manner but the docs aren't very clear about any differences.
4. How does `<Slot />` interact with route definitions? It appears that it creates an implicit stack router (`type: "stack"`) when inspecting router state. The docs aren't clear about how using layouts and slots impacts the structure and definition of routes.
5. How does defining screens in a router affect the structure of the router vs allowing routes to be picked up via filesystem path? There seems to be some inconsistency between the two and the docs don't clarify or make recommendations about using one or the other.
6. How does adding a layout impact configuration of routes? It appears that if I have some sub-directories of a stack I can configure the route via `<Stack.Screen name="sub-dir/other-dir/my-route"` but _only_ if `sub-dir` and `other-dir` do not contain a `_layout.tsx`. If there is a layout it appears to create a new router at that directory level. Related to question 4.
7. Related to 4 and 6, what's the proper way to work with nested layouts? I had to discover through trial and error that I needed to add an explicit `<Stack` to most of my `_layout` files and explicitly configure a `<Stack.Screen` for each subdirectory otherwise routes did not get picked up correctly if I used `<Slot`.
8. When using shared routes what's the proper syntax for arrays when one or more of the members is a group? For example with `/app/(root)/foo` and `/app/(misc)/bar` do I use `/app/(root,misc)/baz` or `/app/((root),(misc))/baz`? Either way the behavior of shared routes seems to be buggy or underdefined https://github.com/expo/expo/issues/29273

I'd be happy to make a PR for the docs if @marklawlor or @EvanBacon could offer some insight into the above questions. Thanks!

### Link to the related docs page

https://docs.expo.dev/router/layouts/

**Comment by fobos531** [comment]
Just wanted to add that I share many of the same concerns and that I would also very much appreciate if the documentation would be expanded.

**Comment by DavidAmyot** [comment]
Agree, would also really appreciate different up to date repo examples of using expo-router v3 in the doc.

**Comment by marklawlor** [comment]
Hi everyone, the feedback has been received and we'll have an update this week

**Comment by RajeshPandey057** [comment]
Thanks @evelant for the questions. Great and much needed questions. 
I want to add one more,  if I have a <Slot/> based route, how do I set screen options for that to show/hide header ?
I don't want to use tab or stack as header will be dynamic based on screen content so screen option inside route file will be better.

**Comment by snios** [comment]
The current documentation is still not very clear and i get a feeling it is not completly written for the current version of the router? 
Since it was supposedly updated in July with regards to @marklawlor  comment i wanted to add that i still think that is not very clear. It should perhaps include more complex samples as well?

**Comment by HunderlineK** [comment]
As it stands, the OP helps more with clarifying the nuances than the docs themselves 🤷 e.g. without having a Stack defined in the grouped routes, the name of the route will be set to the name of the group. The only way to access the name of the route within the group is via a CHILD_ROUTE symbol on the route object, which doesn't seem to be documented

**Comment by gregfenton** [comment]
Based on my limited experience thus far, `<Slot>` should have its own explicit page.  It seems that it is quite important to understand the nature of rendering in Expo Router and how `<Slot>` plays into that.  In particular when it comes to "wrapping" your routes with Context Providers -- which almost always involve asynchronous activities that need completion before children can be successfully rendered.

Either that or a page dedicated to this particular pattern and how to do is "the right way" in Expo Router as it seems to differ from standard client-side ReactJS.

**Comment by marklawlor** [comment]
We've been improving the docs steady and there will be a number of improvements with SDK 52. If you'd like to see particular feedback on a topic, please use the "Share your feedback" button at the bottom of the page. This way the feedback will go directly to the docs team and won't be lost in an issue.
