### ISSUE TITLE
Failed to download remote update from url

### ISSUE THREAD

**Issue by bd1354** [expo/expo#30188]
### Minimal reproducible example

https://github.com/bd1354/expooau/blob/main/app.jsx

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

I successfully installed expo, expo modules and expo over the air updates in my Bare app. I followed the documentation completely. I ran the eas update command and it was successful.
![image](https://github.com/expo/expo/assets/83255385/fbc95948-26e8-4145-9ad4-480e7e080e0c)
Everything went smoothly so far, but when I open the application and click on the fetch update button, I get an error like this:
![image](https://github.com/expo/expo/assets/83255385/f1aa7e84-e4fc-4c85-a884-cc6268a87ccc)
When I searched on the internet to see if anyone had a similar problem, I couldn't find it, so I'm writing it here, I hope you can help, thank you.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.7.0 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      expo: ^50.0.0 => 50.0.19
      react: 18.2.0 => 18.2.0
      react-native: 0.73.7 => 0.73.7
    Expo Workflow: bare

### Expo Doctor Diagnostics

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName"
Learn more: https://expo.fyi/root-expo-object
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/netinfo@11.3.1 - expected version: 11.1.0
  react-native@0.73.7 - expected version: 0.73.6
  react-native-gesture-handler@2.16.1 - expected version: ~2.14.0
  react-native-maps@1.14.0 - expected version: 1.10.0
  react-native-reanimated@3.10.0 - expected version: ~3.6.2
  react-native-safe-area-context@4.10.1 - expected version: 4.8.2
  react-native-screens@3.31.1 - expected version: ~3.29.0
  react-native-svg@15.2.0 - expected version: 14.1.0
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by wfl-junior** [comment]
I am having the same issue with sdk 50

**Comment by wfl-junior** [comment]
Any updates? I tried updating to sdk 51, but didn't solve the issue.
Can't get more details, only the message `Failed to download remote update from URL: https://u.expo.dev/:projectId`

**Comment by bd1354** [comment]
> Any updates? I tried updating to sdk 51, but didn't solve the issue. Can't get more details, only the message `Failed to download remote update from URL: https://u.expo.dev/:projectId`

No it still doesn't work

**Comment by QuentinOber** [comment]
Same issue here, it seems to happen for around 10% of my users.

**Comment by DogukanSakin** [comment]
In my case, I discovered that it works fine when I add requestHeaders to the url section as an extra and add expo-runtime-version and expo-channel-name parameters to requestHeaders.

Like this:

` runtimeVersion: '1.0.0',
   updates: {
          url: 'https://u.expo.dev/project-id',
          requestHeaders:{
            "expo-runtime-version":"1.0.0",
            "expo-channel-name":"production"
          }
     },
 `
 
After doing this, I ran the **eas update:configure** and **eas build:configure** commands, respectively.

After running the commands, I saw that the following metadata was automatically added to my AndroidManifest.xml file:

`
<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-runtime-version&quot;:&quot;1.0.0&quot;,&quot;expo-channel-name&quot;:&quot;production&quot;}"/>
`

[In](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/in) [this](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/this) [way](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/way), expo-updates worked [as](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/as) expected [on](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/on) [the](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/the) [Android](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/android) [side](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/side). [I](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/i) [hope](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/hope) [it](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/it) [works](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/works) [in](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/in) [your](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/your) [case](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/case) [as](https://dictionary.cambridge.org/tr/s%C3%B6zl%C3%BCk/ingilizce-t%C3%BCrk%C3%A7e/as) well.

**Comment by DogukanSakin** [comment]
In my case, I discovered that it works fine when I add requestHeaders to the url section as an extra and add expo-runtime-version and expo-channel-name parameters to requestHeaders.

Like this:
`
 runtimeVersion: '1.0.0',
  updates: { 
    url: 'https://u.expo.dev/project-id', 
    requestHeaders:{ 
      "expo-runtime-version":"1.0.0", 
       "expo-channel-name":"production" 
    } 
  }
`
After doing this, I ran the **eas update:configure** and **eas build:configure** commands, respectively.

After running the commands, I saw that the following metadata was automatically added to my AndroidManifest.xml file:

`<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-runtime-version&quot;:&quot;1.0.0&quot;,&quot;expo-channel-name&quot;:&quot;production&quot;}"/>`

In this way, expo-updates worked as expected on the Android side. I hope it works in your case as well.

**Comment by DogukanSakin** [comment]
In my case, I discovered that it works fine when I add requestHeaders to the url section as an extra and add expo-runtime-version and expo-channel-name parameters to requestHeaders.

Like this:
> 

     runtimeVersion: '1.0.0',
     updates: {
          url: 'https://u.expo.dev/project-id',
          requestHeaders:{
            "expo-runtime-version":"1.0.0",
            "expo-channel-name":"production"
          }
      },

After doing this, I ran the **eas update:configure** and **eas build:configure** commands, respectively.

After running the commands, I saw that the following metadata was automatically added to my AndroidManifest.xml file:

`<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-runtime-version&quot;:&quot;1.0.0&quot;,&quot;expo-channel-name&quot;:&quot;production&quot;}"/>`

In this way, expo-updates worked as expected on the Android side. I hope it works in your case as well.

**Comment by wfl-junior** [comment]
> In my case, I discovered that it works fine when I add requestHeaders to the url section as an extra and add expo-runtime-version and expo-channel-name parameters to requestHeaders.
> 
> Like this:
> 
> > 
> 
> ```
>  runtimeVersion: '1.0.0',
>  updates: {
>       url: 'https://u.expo.dev/project-id',
>       requestHeaders:{
>         "expo-runtime-version":"1.0.0",
>         "expo-channel-name":"production"
>       }
>   },
> ```
> 
> After doing this, I ran the **eas update:configure** and **eas build:configure** commands, respectively.
> 
> After running the commands, I saw that the following metadata was automatically added to my AndroidManifest.xml file:
> 
> `<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-runtime-version&quot;:&quot;1.0.0&quot;,&quot;expo-channel-name&quot;:&quot;production&quot;}"/>`
> 
> In this way, expo-updates worked as expected on the Android side. I hope it works in your case as well.

That did not work for me

**Comment by wfl-junior** [comment]
I managed to make it work by switching from `expo-channel-name` header to `channel-name` query param.
But then everytime I run eas update it changes the updates url in the app.json or if it is app.config.js it crashes.

One weird thing is that, after that, I tried the header again and now it works 😶

**Comment by bd1354** [comment]
> I managed to make it work by switching from `expo-channel-name` header to `channel-name` query param.

It works. Teşekkür ederim Doğukan bey

**Comment by bharathy-kannan** [comment]
> > In my case, I discovered that it works fine when I add requestHeaders to the url section as an extra and add expo-runtime-version and expo-channel-name parameters to requestHeaders.
> > Like this:
> > > 
> > 
> > 
> > ```
> >  runtimeVersion: '1.0.0',
> >  updates: {
> >       url: 'https://u.expo.dev/project-id',
> >       requestHeaders:{
> >         "expo-runtime-version":"1.0.0",
> >         "expo-channel-name":"production"
> >       }
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After doing this, I ran the **eas update:configure** and **eas build:configure** commands, respectively.
> > After running the commands, I saw that the following metadata was automatically added to my AndroidManifest.xml file:
> > `<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-runtime-version&quot;:&quot;1.0.0&quot;,&quot;expo-channel-name&quot;:&quot;production&quot;}"/>`
> > In this way, expo-updates worked as expected on the Android side. I hope it works in your case as well.
> 
> That did not work for me

Thanks a lot. This worked for me. I am also moving away from codepush to eas updates. Took me a good 15 days to get it done. This was a life saviour. I am in expo 51 and react-native 0.74. For me checkAutomatically ON_LOAD works. For some reason if I have it as ALWAYS it fails to build. Wonder why.

**Comment by G0phix** [comment]
> > In my case, I discovered that it works fine when I add requestHeaders to the url section as an extra and add expo-runtime-version and expo-channel-name parameters to requestHeaders.
> > Like this:
> > > 
> > 
> > 
> > ```
> >  runtimeVersion: '1.0.0',
> >  updates: {
> >       url: 'https://u.expo.dev/project-id',
> >       requestHeaders:{
> >         "expo-runtime-version":"1.0.0",
> >         "expo-channel-name":"production"
> >       }
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After doing this, I ran the **eas update:configure** and **eas build:configure** commands, respectively.
> > After running the commands, I saw that the following metadata was automatically added to my AndroidManifest.xml file:
> > `<meta-data android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY" android:value="{&quot;expo-runtime-version&quot;:&quot;1.0.0&quot;,&quot;expo-channel-name&quot;:&quot;production&quot;}"/>`
> > In this way, expo-updates worked as expected on the Android side. I hope it works in your case as well.
> 
> That did not work for me

In which file do i add this?

**Comment by thisAbdU** [comment]
using npx expo start --tunnel worked for me

**Comment by haiduc2511** [comment]
Using npx expo start --tunnel or turning off my firewall workes for me

**Comment by fajarhardeka** [comment]
thanks, this worked to me!

**Comment by solokhind** [comment]
This issue can occur when using expo prebuild and assembling the APK manually (without using expo's EAS build service). In such cases, the native metadata (including the update URL and runtimeVersion) gets injected via expo prebuild, but the channel information isn’t automatically injected.

Manually adding a requestHeaders entry (e.g. "expo-channel-name": "production") in the app config can serve as a workaround to force the channel value into the native metadata. However, this approach is static and hardcodes the channel value. If you’re using Expo channels with EAS Build—which automatically injects the correct channel based on your build profile—overriding the header manually can lead to inconsistencies across different build environments (staging, production, etc.), potentially causing the app to fetch updates from the wrong channel or fail to receive updates altogether.

**Comment by JWW87** [comment]
> This issue can occur when using expo prebuild and assembling the APK manually (without using expo's EAS build service). In such cases, the native metadata (including the update URL and runtimeVersion) gets injected via expo prebuild, but the channel information isn’t automatically injected.
> 
> Manually adding a requestHeaders entry (e.g. "expo-channel-name": "production") in the app config can serve as a workaround to force the channel value into the native metadata. However, this approach is static and hardcodes the channel value. If you’re using Expo channels with EAS Build—which automatically injects the correct channel based on your build profile—overriding the header manually can lead to inconsistencies across different build environments (staging, production, etc.), potentially causing the app to fetch updates from the wrong channel or fail to receive updates altogether.

This worked for me! I am not using the EAS build service, but I wanted to try to get EAS updates to work. Everything I tried resulted in an `Remote update request not successful` error. Manually adding `"expo-channel-name": "production"` to `expo:updates` in app.json solved this issue. In my case this is a perfectly acceptable workaround. Thanks!

**Comment by Yemisrach15** [comment]
I'm setting up expo-updates in a bare react native project. It turned out to be that I had to create the channel on expo.dev which links it to a branch with the same name. I had published an update on the branch before but the channel was not created.
