### ISSUE TITLE
expo-camera Android stretched preview

### ISSUE THREAD

**Issue by oudomsieng** [expo/expo#3018]
Expo-camera on Android previews in stretched.

https://expo.io/@oudomsieng/try-me

**Comment by tufailra97** [comment]
As per docs,

> Android only. A string representing aspect ratio of the preview, eg. 4:3, 16:9, 1:1. To check if a ratio is supported by the device use getSupportedRatiosAsync. Default: 4:3

try to set the ratio to 4:3 this should fix your problem

**Comment by oudomsieng** [comment]
Thank you @tufailra97 you're very helpful
