### ISSUE TITLE
Expo-camera does not allow to use 'back' camera when using iPhone/Android web version from Chrome/Safari

### ISSUE THREAD

**Issue by NazarKozak** [expo/expo#30206]
### Minimal reproducible example

https://docs.expo.dev/versions/latest/sdk/camera/#basic-example

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

Is expected to render back camera view when defaulting to 'back' CameraType or flipping from 'front' to 'back'

### Environment

expo-camera: 15.0.3
react-native: 0.74.1
react-native-web: 0.19.6

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by conwayanderson** [comment]
Also experience this issue with not being able to flip cameras using the Expo sample app in mobile web. Expected this to not work on desktop web but work on mobile web.
