### ISSUE TITLE
[metro-config/serializer] serializeChunks.js hash doesn't take moduleId into account

### ISSUE THREAD

**Issue by Nsquik** [expo/expo#30203]
### Minimal reproducible example

https://snack.expo.dev/Hcat4MMu8oLrHzUK1Geii?platform=web

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

Let's consider an example of implementing lazy loading in our application:

Example: [Snack Expo Lazy Loading Example](https://snack.expo.dev/Hcat4MMu8oLrHzUK1Geii?platform=web)

```js
const LazyComponent = React.lazy(() => import("./components/AssetExample"));

export default function App() {
  return (
    <React.Suspense fallback={<div>Loading...</div>}>
      <Card>
        <LazyComponent />
      </Card>
    </React.Suspense>
  );
}
```

When we bundle our JavaScript using Metro (`expo export -p web`), the code is split into two files:

1. `AppEntry-aaa.js` – requires a chunk with `moduleId: "123"`
2. `index-bbb.js` (the lazy loaded component) – the chunk is assigned `moduleId: "123"`

### Actual Behavior Leading to a Bug:

1. The user opens and downloads our web app.
2. `AppEntry-aaa.js` and `index-bbb.js` are cached in Firebase, CloudFlare, or the browser.
3. We update the code, excluding changes to `LazyComponent`.
4. Metro generates a new hash for `AppEntry`: `AppEntry-ccc.js`. The index-bbb.js hash remains unchanged. The `moduleId` of the index's chunk changes to `456` due to the addition of a lot of new files!
5. The user revisits the site and requests the new `AppEntry-ccc.js`, which is downloaded from the server because of the new hash.
6. `AppEntry-ccc.js` requires `moduleId: 456` from `index-aaa.js`.
7. `index-aaa.js` retains the same hash and is fetched from the cache.
8. The cached version of the index does not include `moduleId: 456`; it still has `moduleId: 123`.
9. The user sees a blank page, and we receive a Sentry notification: `Error: Requiring unknown module "456"`.

### Expected Behavior:

When generating chunk hashes, the process should account for `moduleId` changes, as `moduleIds` are neither stable nor consistent.

### Solution:

A potential solution is to add the `skipWrapping: false` option to the `getStableChunkSource` function used to generate filenames with hashes:

```js
private getStableChunkSource(serializerConfig: Partial<SerializerConfigT>) {
  return this.options.dev
    ? ''
    : this.serializeToCodeWithTemplates(serializerConfig, {
        serializerOptions: {
          includeSourceMaps: false,
        },
        sourceMapUrl: undefined,
        debugId: undefined,
        skipWrapping: false,
      }).code;
}
```

Alternatively, we could disable skipWrapping in the serializeToCodeWithTemplates function. These adjustments would consider the entire content of index.js, including the moduleId wrappers while hashing.

Request for Expert Advice:
@EvanBacon, your expertise would be greatly appreciated. Why doesn't the current process consider the complete content of the file, including the "wrapping," when hashing chunks?
[Expo Metro Config - serializeChunks.ts](https://github.com/expo/expo/blob/main/packages/%40expo/metro-config/src/serializer/serializeChunks.ts#L385)

### Environment

    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.1/15C5028h - /usr/bin/xcodebuild
    npmPackages:
      expo: 51.0.17 => 50.0.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.73.8 
      react-native-web: 0.19.12 => 0.18.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.8.4
  @expo/config-plugins@7.9.2
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~7.0.0
Found invalid:
  @expo/prebuild-config@6.7.3
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions0.

The following packages should be updated for best compatibility with the installed expo version:
  expo-image-picker@15.0.6 - expected version: ~15.0.7
  react-native@0.74.2 - expected version: 0.74.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies

**Comment by sohcah** [comment]
Have just hit this issue in production for one of our projects. Currently planning to work around by patching `@expo/metro-config` with the fix in PR https://github.com/expo/expo/pull/30224, but would be great to see this issue fixed.
