### ISSUE TITLE
"Image could not be captured" errors from takePictureAsync.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [expo/expo#3020]
### Environment

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 4.4.23 - /usr/local/bin/bash
    Binaries:
      Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.14.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: 30.0.0 => 30.0.0
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.18.2 => 2.18.2
```

App target: iOS and Android

### Steps to Reproduce

Our app uses `takePictureAsync` to capture pictures from the camera. ~5% of the time we're getting `Image could not be captured` errors for iOS. It doesn't appear to come up for Android. My guess is that the error is coming [from here](https://github.com/expo/expo/blob/master/ios/versioned-react-native/ABI27_0_0/Expo/Core/Api/Components/Camera/ABI27_0_0EXCamera.m#L360) but it's not clear what can cause the error in the first place.

Here's a stack trace:

![image](https://user-images.githubusercontent.com/5187404/50182197-8e40cb00-02c3-11e9-93f1-84d29040c876.png)

Has anyone else bumped into this issue before? I can't find anything reproducible because it happens so inconsistently on different devices...

**Comment by AndrewSouthpaw** [comment]
Okay, I finally a decent repro setup. See this [Expo Snack](https://snack.expo.io/HypPGQhl4).

**Repro**

Once app is opened, leave it (go to home). Open app back up. *As it opens*, start pressing the shutter snap button. Generally it's possible to trigger a snap before the camera remounts (or something) and it triggers an error. In order to trigger the error, you need to press it before the camera screen flickers and starts showing a fresh stream of the camera view. Getting it to error this way is a bit tricky and probably harder on faster phones.

The other way to trigger the error is to take a few pictures in rapid succession and then leave the app before the shutter sound fires and the loading indicator goes away. When you return to the screen, the error appears. Similar, it's probably easier to trigger this on a slower phone. I'm using an iPhone 6S (not that slow, but still a lot slower than the latest models).

**Comment by AndrewSouthpaw** [comment]
Any thoughts on this? Do others experience it as well?

**Comment by bbarthec** [comment]
@AndrewSouthpaw sorry that this issue wasn't handled before! 🙇
Regarding this issue I've created PR that would help with handling one issue you've reported.
Additionally regarding your two cases:
- 1 - there's `camera#onCameraReady` callback that is being called when native camera component is ready for handling any request
- 2 - I couldn't reproduce having `taking photo` process took more than a couple milliseconds 😞, but I'll give it another shot and try programatically delay taking photo process 😉

**Comment by bbarthec** [comment]
@AndrewSouthpaw I've succeeded in obtaining scenario when camera component starts taking a photo and during this process camera view is unmounted (before taking photo process is completed). This scenario should result in a promise rejection and I've fixed it to do so.
