### ISSUE TITLE
Implicit declaration of function 'EX_ENSURE_STRONGIFY' is invalid in C99

### ISSUE THREAD

**Issue by d7laungani** [expo/expo#3022]
### Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.0 => 30.0.2
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
    npmGlobalPackages:
      expo-cli: 2.6.14

IOS with Expo Kit from SDK 30
### Steps to Reproduce

(Write your steps here:)

1. Old Project from SDK 25. Upgraded to SDK 30. 
2. Detach Project
3. Android works fine but IOS project gives multiple errors including:

 "Implicit declaration of function 'EX_ENSURE_STRONGIFY' is invalid in C99"
" Implicit declaration of function 'EX_WEAKIFY' is invalid in C99"

which stems from multiple expo modules but in the first case being EXBarCodeScanner.

### Expected Behavior

I expected it to build.
### Actual Behavior

It gives build errors.

**Comment by ide** [comment]
Your upgrade process is probably missing some dependencies since those macros are defined in EXDefines.h. If you make a new project and eject right away, does it build for you?

**Comment by d7laungani** [comment]
The latest create react app I am assuming has the latest sdk so I wouldn't be able to test with a true sdk 30 environment.. You are saying I am missing dependencies so would that mean in my podfile or in my project package.json. The reason I ask that is because to prevent that I ejected after the project from sdk 25 was upgraded to sdk 30. Thanks for your help !.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions. Thanks!
