### ISSUE TITLE
Expo-camera does not allow to use 'back' camera when using iPhone/Android web version from Chrome/Safari

### ISSUE THREAD

**Issue by NazarKozak** [expo/expo#30222]
### Minimal reproducible example

https://github.com/NazarKozak/Expo-camera-bug

### What platform(s) does this occur on?

Web

### Did you reproduce this issue in a development build?

No (web-only issue)

### Summary

Is expected to render back camera view when defaulting to 'back' CameraType or flipping from 'front' to 'back'

### Environment

expo-camera: 15.0.3
react-native: 0.74.1
react-native-web: 0.19.6

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by conwayanderson** [comment]
I've also experienced this issue.

**Comment by Le0Developer** [comment]
Looks like it might be using the wrong constraints. https://github.com/expo/expo/blob/6a0c6e17cd3e3304d5d15d8b3bad4822266c5ca5/packages/expo-camera/src/web/WebCameraUtils.ts#L169-L179
It should be `user` for front and `environment` for back.

**Comment by Le0Developer** [comment]
Sorry for the previous comment. So the issue seems to be that here:
https://github.com/expo/expo/blob/6a0c6e17cd3e3304d5d15d8b3bad4822266c5ca5/packages/expo-camera/src/ExpoCamera.web.tsx#L35
It reads `type` instead of `facing` and it doesn't throw a type error because it's importing the legacy types.

Breakpointing in the caller after this line and setting `nativeProps.type = "back"` makes it work: https://github.com/expo/expo/blob/6a0c6e17cd3e3304d5d15d8b3bad4822266c5ca5/packages/expo-camera/src/CameraView.tsx#L257

**Comment by NazarKozak** [comment]
> Sorry for the previous comment. So the issue seems to be that here:
> 
> https://github.com/expo/expo/blob/6a0c6e17cd3e3304d5d15d8b3bad4822266c5ca5/packages/expo-camera/src/ExpoCamera.web.tsx#L35
> 
> 
> It reads `type` instead of `facing` and it doesn't throw a type error because it's importing the legacy types.
> Breakpointing in the caller after this line and setting `nativeProps.type = "back"` makes it work:
> 
> https://github.com/expo/expo/blob/6a0c6e17cd3e3304d5d15d8b3bad4822266c5ca5/packages/expo-camera/src/CameraView.tsx#L257
> 
> We needed this fixed asap, so we used patch-package with the following patch:
> 
> ```diff
> diff --git a/node_modules/expo-camera/build/ExpoCamera.web.js b/node_modules/expo-camera/build/ExpoCamera.web.js
> index 272e2e7..d37c532 100644
> --- a/node_modules/expo-camera/build/ExpoCamera.web.js
> +++ b/node_modules/expo-camera/build/ExpoCamera.web.js
> @@ -10,7 +10,7 @@ import { useWebCameraStream } from './web/useWebCameraStream';
>  import { useWebQRScanner } from './web/useWebQRScanner';
>  const ExponentCamera = React.forwardRef(({ type, poster, ...props }, ref) => {
>      const video = React.useRef(null);
> -    const native = useWebCameraStream(video, type, props, {
> +    const native = useWebCameraStream(video, props.facing, props, {
>          onCameraReady() {
>              if (props.onCameraReady) {
>                  props.onCameraReady();
> ```
> 
> And it works beautifully.

It works. Thanks a lot!
