### ISSUE TITLE
Expo Build Error Gradlew

### ISSUE THREAD

**Issue by nickzsche** [expo/expo#30253]
### Minimal reproducible example

https://github.com/nickzsche/idealmobil

### Did you reproduce this issue in a development build?

Yes

### Summary

Hello, the application is running in my local, but it gives such an error when building. 

[https://expo.dev/accounts/sahanhasret/projects/IdealMobil/builds/d1ed026e-58ef-4b79-bb2c-c65c0ec0ad29#run-gradlew](Error)

My Package.json

{
  "name": "idealmobil",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/netinfo": "11.3.1",
    "@react-native-firebase/app": "^18.6.1",
    "@react-native-firebase/auth": "^18.6.1",
    "@react-native-firebase/firestore": "^18.6.1",
    "@react-native-firebase/messaging": "^18.6.1",
    "@react-native-picker/picker": "2.7.5",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "expo": "^51.0.18",
    "expo-build-properties": "~0.12.3",
    "expo-constants": "~16.0.2",
    "expo-dev-client": "~4.0.19",
    "expo-device": "~6.0.2",
    "expo-navigation-bar": "~3.0.7",
    "expo-notifications": "^0.28.9",
    "expo-permissions": "^14.4.0",
    "expo-splash-screen": "^0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "~0.25.18",
    "expo-web-browser": "~13.0.3",
    "firebase": "^10.5.2",
    "native-notify": "^3.2.4",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-awesome-alerts": "^2.0.0",
    "react-native-modalbox": "^2.0.2",
    "react-native-navigation-bar-color": "^2.0.2",
    "react-native-push-notification": "^8.1.1",
    "react-native-text-effects": "^1.0.0",
    "react-native-vector-icons": "^10.0.1",
    "react-native-webview": "13.8.6",
    "sqlite3": "^5.1.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

How can I fix the error?

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      expo: ^51.0.18 => 51.0.18
      react: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
    Expo Workflow: managed

### Expo Doctor Diagnostics

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.9.2
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

Error: Problem validating fields in C:\Users\Agartha\Desktop\AcentemMobil\app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: android - should NOT have additional property 'favicon'.

The package  "expo-permissions" was deprecated in SDK 41 and should be removed from your project because it may no longer compile on the latest SDK. It was replaced by permissions methods directly on modules, eg: MediaLibrary.requestPermissionsAsync().

One or more checks failed, indicating possible issues with the project.

**Comment by geryit** [comment]
Seeing the same as well. When I uninstall `@react-native-firebase/messaging`, I can build again
