### ISSUE TITLE
metro config to drop console not applied in production release

### ISSUE THREAD

**Issue by chhornponleu** [expo/expo#30265]
### Summary

I follow this doc to remove console https://docs.expo.dev/guides/minify/#remove-console-logs, but in my production build apk, I can see console.log by running

>npx react-native log-android

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment
```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - /usr/local/opt/node@20/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 10.7.0 - /usr/local/opt/node@20/bin/npm
      Watchman: 2024.06.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/ponleu/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34
        Build Tools: 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-27 | Google APIs Intel x86 Atom, android-33 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.14 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 5.9.0
    Expo Workflow: bare
```
### Minimal reproducible example

- create a new expo
- add `configs.transformer.minifierConfig.compress.drop_console = true;` to metro.config.js
- add console.log('Hello world')
- build release mode and install on device / emulator
- run >npx react-native log-android
- start app

Then it displays the log "Hello world" in terminal.

**Comment by ikbalmoh** [comment]
I got an error from the editor:
`Cannot assign to 'minifierConfig' because it is a read-only property.`
