### ISSUE TITLE
IOS crashes when sending FormData API call.  

### ISSUE THREAD

**Issue by James-Whitfield** [expo/expo#30270]
### Summary

When using fetch to send a FormData Object with a large number of key/value pairs the entire application crashes. This only occurs on IOS devices (simulator and physical).

In any documentation there does not appear to be a limit on the number of key/value pairs supported. The same functionality works for Web and android. 

```tsx
    // Build a large FormData object
    const formData = new FormData();
    //! Select the size of formData
    const numberOfKeyValuePairs = 300;
    for (let i = 0; i < numberOfKeyValuePairs; i++) {
      formData.append(i.toString(), i.toString());
    }
    // Try and send a request with the formData
    fetch("https://anyurl.com", {
      method: "post",
      body: formData,
    })
      .then((a) => console.log("It sent"))
      .catch((a) => console.log(a));
```

![crash-error-1](https://github.com/expo/expo/assets/25319773/efc425f9-4ba2-4ee3-8569-75ee6a64b166)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

Used `npx create-expo-app@latest` SDK 51

### Environment

npx expo-env-info     

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.18 => 51.0.18 
      expo-router: ~3.5.17 => 3.5.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.1

### Reproducible demo

https://github.com/James-Whitfield/rn-formdata-issue?tab=readme-ov-file

### Stacktrace (if a crash is involved)

![crash-error-1](https://github.com/expo/expo/assets/25319773/b3aa390e-d3c7-4678-8898-8cfbdcdf096c)

**Comment by JackCMckenzie** [comment]
Same here, absolutely no problems on android but iOS crashes consistently.

**Comment by deepakAmey** [comment]
I experienced this same bug on the iOS application, where it repeatedly fails, while it works perfectly fine on both Android and the web without any issues.
