### ISSUE TITLE
[docs]  Fix deduped section in docs/pages/eas-update/debug-advanced.mdx

### ISSUE THREAD

**Issue by timwm** [expo/expo#30284]
### Summary

Remove duplicated section ("Viewing network requests") under "Debugging EAS Update" in docs/pages/eas-update/debug-advanced.mdx

### Link to the related docs page

https://github.com/expo/expo/blob/main/docs/pages/eas-update/debug-advanced.mdx

**Comment by amandeepmittal** [comment]
Good catch! We'll fix it soon. Thanks for letting us know!
