### ISSUE TITLE
Image popup for picking image is not opening in android.

### ISSUE THREAD

**Issue by Yawan-1** [expo/expo#30286]
### Minimal reproducible example

https://snack.expo.dev/@expouseryanspace/healthy-blue-apple?platform=android

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

Hi,

I am trying to add a image picker in my app in my expo app but when I click on "pickImage" then it is not doing anything, expo app notification just disappears for a second then re-appears after and not other action performs. `launchCameraAsync` is working fine as it is opening camera and selecting/cropping image after capture but only `launchImageLibraryAsync` is not working.

Working in snack but I don'y why not working with the expo version 49 I am using.

My android device: 10

### Environment

    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^49.0.23 => 49.0.23
      react: ^18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.72.10 => 0.72.10
      react-native-web: ^0.19.12 => 0.19.12
    Expo Workflow: bare

### Expo Doctor Diagnostics

Didn't find any issues with the project!

**Comment by Yawan-1** [comment]
I can't, because I have only option is to provide the app in sandbox which is working. I even tried changing the expo version in `snack` but it is working online and not in my android. Does it have anything do to with Android's **Developer Options** or **Animation**?

**Comment by vonovak** [comment]
Hello 👋 ,
You're saying it doesn't work on your device. Can you share the code that doesn't work? So far you only shared code that _does_ work. It's hard to help if I'm not able to see the problem.

Thank you! 🙂

**Comment by Yawan-1** [comment]
Thanks for the reply, here it is that is actual code which is not working,

````
  const pickImage = async () => {
    result = await ImagePicker.launchImageLibraryAsync({
      base64: true,
      allowsEditing: true,
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      quality: 1,
    });

    if (!result.canceled) {
      console.log(result);
      setImage(result.assets[0].uri);
    }
  };
````

and in onPress event

````
<Button
    mode="contained"
    onPress={() => pickImage()}
>
    Upload Image
</Button>
````

First I thought it might be the case that I have multiple wrappers around the App for different functionalities so here it is


````
<GestureHandlerRootView>
    <BottomSheetModalProvider>
         <PaperProvider>
              <NavigationContainer>
                 <Provider store={store}>
                      <App>
````

**Comment by vonovak** [comment]
Hello 👋 ,
Can you please create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that we can see the issue with? Unfortunately, this is not actionable otherwise.

Thank you! 🙂

**Comment by Yawan-1** [comment]
@vonovak Look Vonovak, I already told you that `launchImageLibraryAsync` is the problem which is not working otherwise camera is launcing properly so I want you to tell me what may be causing the issue because there is not error in the console which can be sign of "Nothing wrong in my app".

I again created a snack which you call **Minimal, Reproducible Example** [Here](https://snack.expo.dev/@expouseryanspace/authentic-violet-orange). In this I used the version which I am using in my actual app but it is working and not in my android real device.

**Comment by Yawan-1** [comment]
@vonovak It is still not working, Is there a case that I may be conflicting the versions like if the library is using some other dependency like `reanimated` and I may be using some other version?

**Comment by Yawan-1** [comment]
It was the device problem as It was not working in `Android 10` but I just tested in `Android 14` and it is working in new device.
