### ISSUE TITLE
RN 0.74.3 breaks expo-av

### ISSUE THREAD

**Issue by FelipeSSantos1** [expo/expo#30282]
### Minimal reproducible example

https://snack.expo.dev/BsgeZxELxb8lc2mNqK15D?platform=web

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Using the version 74.3 of RN breaks the expo-av to play a sound, if I downgrade it to RN 74.2 it works.

the error is at code block
```
const { sound: expoSound } = await Audio.Sound.createAsync( require('./assets/Hello.mp3'));
```

 it says: `Error: Module "20" is missing from the asset registry`

at the snack you should upgrade the RN to 0.74.3 to be able to reproduce the issue

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 28, 30, 31, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-30 | Google APIs ATD ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google TV ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Intel x86_64 Atom, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Intel x86_64 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: 51.0.18 => 51.0.18 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

bare flow

**Comment by brentvatne** [comment]
please include doctor diagnostics, they are relevant regardless of whether you use bare workflow or not.

i expect that you have multiple versions of `@react-native/assets-registry` installed. if you update your packages with `npx expo install --fix` it'll correct that.

**Comment by FelipeSSantos1** [comment]
You are the man @brentvatne , the problem was on `"expo-image": "1.12.9"` that uses `0.74.84` of `@react-native/assets-registry` upgrading `"expo-image": "1.12.12"` fix the problem.
Now everything uses `@react-native/assets-registry 0.74.85` we also added a resolution in our package.json to run safer
Thank you
