### ISSUE TITLE
Is "main": "src/main.tsx" deprecated? 

### ISSUE THREAD

**Issue by MariuzM** [expo/expo#30295]
### Minimal reproducible example

https://github.com/MariuzM/expo-build-issue/tree/main

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

When i use `main": "src/main.tsx` and i run `eas build --profile production --local -p ios` i get build issue on last step. 
But if i switch to "main": "expo-router/entry",` then everything build.

I don’t have issue doing `expo start:ios` or building / archiving from xcode

My current project has `src/main.tsx` right now i have no plan to move to expo router, project is to big. So wanted to check is this intentional or bug? 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/dev/node-v20.11.0/bin/node
      Yarn: 1.22.22 - ~/dev/node-v20.11.0/bin/yarn
      npm: 10.2.4 - ~/dev/node-v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.18 => 51.0.18 
      expo-router: ^3.5.17 => 3.5.17 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 10.1.1
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by byCedric** [comment]
Hi @MariuzM, thanks for the report! I believe this is a bug, specifically a bug in `expo export:embed`. Will dig in to find out what's causing it!

**Comment by tristian-azuara-sh** [comment]
We're also experiencing this after upgraded, from some of our early testing to circumvent this issue removing `main: index.js` from package.json seems to prevent it.
