### ISSUE TITLE
Web attempts to bundle native dependencies even when not referenced

### ISSUE THREAD

**Issue by calebpanza** [expo/expo#30324]
### Minimal reproducible example

https://github.com/DayMoonDevelopment/expo-navigation-testing

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Problem
I have a project that should have platform-specific functionality. To accomplish this, I'll have a route that should have some kind of native-specific code and I break out my route directories using platform-specific extensions:

```
index.js
index.native.js
index.web.js
```

Per the [documentation](https://docs.expo.dev/router/advanced/platform-specific-modules/), I expect that I should be able to import and develop functionality on my `index.native.js` that would otherwise not **run** or **bundle** on web because the bundle is explicitly split between platforms for the given route.

### Expected Outcome
If I want to split off of my main bundle for a specific platform (ex. `index.web.js`), the bundler should entirely ignore the other platform extensions (`.ios.js, .android.js, native.js, .js`) so that I can keep the individual platform unique. This should allow for me to develop code that is shared in routing and components while still allowing for platform-specific functionality.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.04.29.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/calebpanza/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.16 => 51.0.16 
      expo-router: ~3.5.17 => 3.5.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

**Comment by EvanBacon** [comment]
Expo Router doesn’t support platform specific routes, only platform specific layout routes are supported (since v3.5) as they don’t change the overall routing structure. This is documented here https://docs.expo.dev/router/advanced/platform-specific-modules/

**Comment by calebpanza** [comment]
Really appreciate the clarification. If anyone else comes across a similar issue, just store the screen layout in a different directory _outside of_ `app` and use platform-specific modules, there

**Comment by calebpanza** [comment]
Probs gonna open up a PR suggesting an update to the documentation. I though that the alert on the top of that page was instructing that the _entire_ guide for the page was no longer relevant as of `3.5.0` when in fact it's just the **Platform module** section which is no longer needed.

![2024 07 10 13](https://github.com/expo/expo/assets/45076058/66e93bf3-fa53-432c-a2de-b036242c13fb)
