### ISSUE TITLE
Update bundled @shopify/flash-list to 1.7.0

### ISSUE THREAD

**Issue by gtwilliams03** [expo/expo#30329]
### Minimal reproducible example

N/A

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

No (only happens in a standalone build)

### Summary

Since moving our app over to the new architecture, we have been having some weird errors with flash-list (overlapping items, etc.) that only crop up in production builds. @shopify just came out with a new version last week (1.7.0) in which the release notes (linked below) say that it now supports the new architecture.  Is it possible to update expo to use the latest version? 

[https://github.com/Shopify/flash-list/releases/tag/v1.7.0](https://github.com/Shopify/flash-list/releases/tag/v1.7.0)

### Environment

N/A

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by vonovak** [comment]
Hello and thanks for asking,
Judging by the fact that you're trying out the new architecture, you're probably using [development build](https://docs.expo.dev/develop/development-builds/create-a-build/). In that case you're free to use the new version of `@shopify/flash-list`. You need to install it, run `npx expo prebuild`, and then rebuild your app.

Again, if you're using custom dev build, you can use it. For people using Expo Go, they need to wait until we update the native dependency there.

[For use cases other than prototyping](https://docs.expo.dev/develop/development-builds/create-a-build/), we recommend using [development client](https://docs.expo.dev/develop/development-builds/create-a-build/).

Thank you 🙂

**Comment by gtwilliams03** [comment]
Thank you so much for the quick and detailed response. I am still using Expo Go (I managed to convert to the new architecture without setting up development build first - not my favorite move). But this makes sense and I'll look for the next Expo update to get flash-list latest.

**Comment by vonovak** [comment]
Hello,
Thanks for your reply. Expo Go does not support the New Architecture at the moment. Did you follow some resource that made it seem like it does?

Would you also mind expanding a bit on why setting up development build is not your favorite move?

Thank you 🙂

**Comment by gtwilliams03** [comment]
I misspoke a bit - I was referring to moving to the new architecture without completely testing the features in our app.  That wasn't my best move. I am trying a development build with flash-list 1.7.0.  expo-doctor is throwing a warning, but eas build is still completing. 

```
The following packages should be updated for best compatibility with the installed expo version:
  @shopify/flash-list@1.7.0 - expected version: 1.6.4
```

**Comment by gtwilliams03** [comment]
I can confirm in testing that moving to flash-list `1.7.0` fixed the issue I was having with the Masonry layout in iOS.
