### ISSUE TITLE
[expo-router] ErrorBoundary Regression

### ISSUE THREAD

**Issue by LouisJS** [expo/expo#30322]
### Minimal reproducible example

https://github.com/LouisJS/expo-error-boundary

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I've created a fresh new app with `npx create-expo-app@latest`
I'm adding 

```
export function ErrorBoundary(props: ErrorBoundaryProps) {
  return (
    <View style={{ flex: 1, backgroundColor: "red" }}>
      <Text>{props.error.message}</Text>
      <Text onPress={props.retry}>Try Again?</Text>
    </View>
  );
}
```
in `app/_layout.tsx`

On another screen, i'm doing

```
function throwError() {
    throw new Error("An error occurred");
  }
  
  ....
  
  <TouchableOpacity onPress={() => throwError()}>
     <Text>Crash this App</Text>
  </TouchableOpacity>
```

When i'm pressing the button. I do have a red logbox. But `ErrorBoundary` is not displayed

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.14.0/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/louis/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.18 => 51.0.18 
      expo-router: ~3.5.17 => 3.5.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

**Comment by marklawlor** [comment]
ErrorBoundaries only catch rendering errors. Errors from effects still need to be manually handed https://legacy.reactjs.org/docs/error-boundaries.html

> Error boundaries do not catch errors for:
>
> Event handlers ([learn more](https://legacy.reactjs.org/docs/error-boundaries.html#how-about-event-handlers))
> Asynchronous code (e.g. setTimeout or requestAnimationFrame callbacks)
> Server side rendering
E> rrors thrown in the error boundary itself (rather than its children)
