### ISSUE TITLE
Problems with the installation process.

### ISSUE THREAD

**Issue by aprezcuba24** [expo/expo#3033]
I want to create an Expo app, but I can't.
### Environment
If I execute `expo diagnostics`. I get this data:
```
Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.0.0 - ~/.nvm/versions/node/v10.0.0/bin/node
      Yarn: 1.6.0 - ~/.nvm/versions/node/v10.0.0/bin/yarn
      npm: 6.2.0 - ~/.nvm/versions/node/v10.0.0/bin/npm
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.6.14
```

### Steps to Reproduce
1- npm install expo-cli --global
2- expo init my-new-project 
  * In this step, I choose the blank template
  * I use yarn to install dependencies

3- cd my-new-project
4- expo start

### Expected Behavior

After I do these steps, I expected that the app runs.

### Actual Behavior

After that, I try to access with the Expo client, and I get a screen red, with this message:
```
The Expo SDK requires Expo to run. It appears the native Expo modules are unnavailable and this code is not running on Expo. Visit https://docs.expo.io to lear more about developing an Expo project.
```

**Comment by aprezcuba24** [comment]
Have anybody an answer for this issue?

**Comment by dobrysmak** [comment]
I have exact same problem but with latest SDK 32
```
Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.2 - ~/n/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^31.0.7 => 31.0.7
      @types/react: ^16.7.13 => 16.7.18
      @types/react-native: ^0.57.26 => 0.57.26
      @types/react-navigation: ^2.13.4 => 2.13.9
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.6.14
```

**Comment by aprezcuba24** [comment]
In my case to solve the problem, I had to change the expo to 29.0.0 version, and the app runs now.

**Comment by dobrysmak** [comment]
@aprezcuba24 if You still run into the problem. I've removed node_modules and reinstalled the Expo app on the device/simulator.

**Comment by aprezcuba24** [comment]
@dobrysmak  I did what you propose, but I still have the same problem. Now, I created an app with expo version 32.0.0 and Expo client version is "2.10.3".

**Comment by tsapeta** [comment]
A lot of time has passed and a lot of changes have been made since this report, so I'm closing it. Feel free to open a new report if you're still experiencing it in the latest SDK version 🙂
