### ISSUE TITLE
Reading of big binary file selected by expo-document-picker.getDocumentAsync({copyToCacheDirectory: false})

### ISSUE THREAD

**Issue by HustCoderHu** [expo/expo#30342]
### Minimal reproducible example

https://github.com/HustCoderHu/min_to_report_bug

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

My goal is to handle big binary file such as videos, size of which may be bigger than 1000 MB.

steps to reproduce this error.
1. clone the repo
2. install dep
3. npx expo start
4. click the only blue button
5. select any file (any picture of doc is ok)
6. read log in terminal

got errors as following if a picture is selected
```
Error: Call to function 'ExponentFileSystem.readAsStringAsync' has been rejected.
Caused by: java.io.IOException: Unsupported scheme for location 'content://com.android.providers.media.documents/document/image%3A10039'.]
```

refer to <https://docs.expo.dev/versions/latest/sdk/filesystem/#supported-uri-schemes>

`For example, if you have an URI, which begins with content://, you cannot use FileSystem.readAsStringAsync()`

but in following function, it seems that `content://com.android.providers` is not rejected.

https://github.com/expo/expo/blob/926b41d3c8d309b8cc10117665583e53c487d016/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.kt#L172

Is it a bug?

### Environment

expo-env-info 1.2.0 environment info:
System:
  OS: Windows 10 10.0.19044
Binaries:
  Node: 20.12.0 - D:\softwares\coding\nodejs\node-v20.12.0-win-x64\node.EXE
  Yarn: 1.22.22 - D:\softwares\coding\nodejs\node_global\yarn.CMD
  npm: 10.5.0 - D:\softwares\coding\nodejs\node-v20.12.0-win-x64\npm.CMD
npmPackages:
  expo: ^51.0.11 => 51.0.11
  expo-router: ~3.5.16 => 3.5.16
  react: 18.2.0 => 18.2.0
  react-dom: 18.2.0 => 18.2.0
  react-native: 0.74.2 => 0.74.2
  react-native-web: ~0.19.10 => 0.19.12
Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by vonovak** [comment]
Hello and thanks for asking,
This is the expected behavior. As you pointed out, `content` uris are not supported with `readAsStringAsync`. The error you're seeing comes from [here](https://github.com/expo/expo/blob/926b41d3c8d309b8cc10117665583e53c487d016/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.kt#L197).
You will need to specify `copyToCacheDirectory: true` to be able to read the file.

Thank you 🙂
