### ISSUE TITLE
devices that have had EXPO.io app and have swapped to the native iOS app using Expo SDK 31 don't get notifications

### ISSUE THREAD

**Issue by svrpeakers** [expo/expo#3035]
URL sending notifications to
https://exp.host/--/api/v2/push/send

body
{
	"to":"ExponentPushToken[*****************]", //redacted token
	"body": "Another Attempt, call Sjoerd"
}
headers
{
	"Content-Type":"application/json",
}
response
{
    "data": {
        "status": "ok",
        "id": "a5f256f5-01ff-493b-bd4b-722f3b40dd1e"
    }
}

device: iPhone 10 - iOS 12.1
Notifications are ENABLED
device provides us with this ID every time. when we ask for another token gives same token.

**Comment by ide** [comment]
I don't understand the issue. Can you please explain it more clearly?

**Comment by ide** [comment]
Did you look up the receipt with ID a5f256f5-01ff-493b-bd4b-722f3b40dd1e (or whatever receipt ID you get back when trying to send a notification)?

**Comment by svrpeakers** [comment]
Yes,
so every receipt Id I get states.
{
    "data": {
        "fa38d7bb-5033-4e47-b0ca-3d5686d45a8f": {
            "status": "error",
            "message": "The Apple Push Notification service unexpectedly dropped the connection. Retry sending the notification later.",
            "details": {
                "sentAt": 1546972927
            },
            "__debug": {
                "internalError": "stream ended unexpectedly"
            }
        }
    }

Every message I send to the specified ExponentPushToken is giving me the same error status receipt
I don't know why it does this and I'm not sure if this is Apple or Expo problem.

**Comment by nickjuntilla** [comment]
If the original poster is talking about the standalone app vs. the 'inside expo' app I am getting the same issue. The app running in expo receives the notifications and the stand alone app does not. This is after retrieving token from scratch in the stand alone app. I am using expo 31.0.2. The message is sent ok from my node backend, but the app never receives it.

**Comment by cruzach** [comment]
Hey @svrpeakers , sorry you're seeing this discrepancy between the Expo Client app and standalones. Are you still seeing this behavior? This could be a credential issue, could you try building with a p8 key?

also curious if sending a notification via our [Push Tool](https://expo.io/dashboard/notifications) works? 

@nickjuntilla I see from [this github thread](https://github.com/expo/expo/issues/2185) that you solved your, issue. Glad to hear it!

**Comment by cruzach** [comment]
Closing this issue in favor of the one I linked above
