### ISSUE TITLE
Option to have multiple initialRouteNames

### ISSUE THREAD

**Issue by andreweinhorn** [expo/expo#30352]
### Minimal reproducible example

https://gitlab.com/andreweinhorn/universal

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When I use a universal link to open my app, it takes me to the desired screen correctly.  But I have implemented that screen with a back button that uses router.back() to route to the previous screen.  The problem is that with a universal link, there is no stack history, so the back button either crashes the app, or takes you to the route defined by initialRouteName.

The problem is that when you have multiple tabs, you might want the back buttons to take you back to the root screen of each tab.  But there does not appear to be a way to define multiple initial route names with expo-router (unless I have missed this somewhere in the docs?)

I wouldn't define this as a bug as such, but rather a desirable feature.  Unless I have missed something and there is a way to handle routing back from a universal link screen to the root of the tab.

The workaround I am using is as follows:

```
while(router.canGoBack()){
    router.back()
}
router.replace('tabs/icecreams')
```

But the above code seems like a bit of a hack, and the UI doesn't look great (because the screen does not slide out to the left as you would expect when hitting the back button).  

*** Minimum reproducible example ***

This [video](https://www.youtube.com/shorts/uiHL6KDjFQc) illustrates the problem that arises from the code structure below (see associated gitlab repository containing the actual code).  The user universal links to tabs/icecreams/recipes/2 but when they hit the back button, they get taken to tabs/burgers.  To further worsen the situation, when next they click on the icecream tab, they do not see the root screen of that tab but the nested screen that was initially shown after clicking the universal link.  

```
├── _layout.tsx
├── index.tsx
├── signin.tsx
├── signup.tsx
├── tabs
│   ├── _layout.tsx
│   ├── burgers
│   │   ├── _layout.tsx
│   │   ├── index.tsx
│   │   └── recipes
│   │       ├── [recipe]
│   │       │   ├── _layout.tsx
│   │       │   └── index.tsx
│   │       └── _layout.tsx
│   └── icecreams
│       ├── _layout.tsx
│       ├── index.tsx
│       └── recipes
│           ├── [recipe]
│           │   ├── _layout.tsx
│           │   └── index.tsx
│           └── _layout.tsx
└── welcome.tsx
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.18 => 51.0.18 
      expo-router: ~3.5.17 => 3.5.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed

**Comment by kruzikruz** [comment]
did you manage to solve the problem? Because I have the same error.

**Comment by andreweinhorn** [comment]
Nope. Still hoping to get some clarity on whether this is possible, or if there is some kind of appropriate workaround. Universal links seem like an increasingly important feature of app routing, so fingers crossed

**Comment by marklawlor** [comment]
Can you please provide a github repo for the code used in the video example.  Expo Router has experimental syntax for group specific initialRouteNames, but I don't believe thats exactly what your looking for

**Comment by andreweinhorn** [comment]
@marklawlor see code here [https://gitlab.com/andreweinhorn/universal](https://gitlab.com/andreweinhorn/universal)

**Comment by marklawlor** [comment]
You will need to customise the navigator for your specific functionality. By default, `Tabs` to back to the `firstRoute` when back is pressed. From your description, it seems like you'd like to change that behaviour to `initialRoute` https://reactnavigation.org/docs/bottom-tab-navigator/#backbehavior

After you have changed it to `initialRoute`, can you customise a different `initialRoute` per tab by using groups and setting a different `initialRoute` per group.

Docs:
- https://docs.expo.dev/router/advanced/shared-routes/
- https://docs.expo.dev/router/advanced/router-settings/
