### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by shuo-hiwintech** [expo/expo#30378]
### Minimal reproducible example

https://github.com/shuo-hiwintech/AwesomeProject

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

Dear Expo developers, Hello, I've run into a problem.

After installing Expo using the React Native CLI project, I get a warning: “Unsupported Swift Version” when I open the project through Xcode, but I don't get this warning when I open the project through Xcode without installing Expo.

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/52896eb2-e337-447a-84c3-e3d16aaeae90">

Steps:
1. create a react native cli project, via "npx @react-native-community/cli@latest init AwesomeProject".
2. Install the Expo module via "npx install-expo-modules@latest".
3. Open the project via Xcode and get the Xcode warning.

Same question: https://github.com/expo/expo/issues/30337#issuecomment-2223156381

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 3.6.4 - /usr/local/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
      Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 10.0.2
      expo-cli: 6.3.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check for issues with metro config
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Thank you for providing a reproduction.

The issue is that out of the box, swift version is not set in the settings. The fix for now is to specify the version manually, as seen in the screenshot:

<img width="1171" alt="Screenshot 2024-07-15 at 11 30 59" src="https://github.com/user-attachments/assets/1ae15043-d2e0-4b7a-87eb-414c80946893">

I'm going to look into fixing this on our end.

Let me know if this works for you.
Thank you 🙂

**Comment by shuo-hiwintech** [comment]
> Hello and thanks for reporting, Thank you for providing a reproduction.
> 
> The issue is that out of the box, swift version is not set in the Build settings. The fix for now is to specify the version manually, as seen in the screenshot:
> 
> <img alt="Screenshot 2024-07-15 at 11 30 59" width="1171" src="https://private-user-images.githubusercontent.com/1566403/348658536-1ae15043-d2e0-4b7a-87eb-414c80946893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzkxMTksIm5iZiI6MTcyMTAzODgxOSwicGF0aCI6Ii8xNTY2NDAzLzM0ODY1ODUzNi0xYWUxNTA0My1kMmUwLTRiN2EtODdlYi00MTRjODA5NDY4OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMTAyMDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDMzMWJkZjlmMjBmNWEzMWFlZWE1MzI4OTFkNjhjOGQ3NmJiMjdmYjMyZWEwMjlmODFiMWM2YTEzNGY5MmZiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2IdGZoHkZF5pJIiFN4tR8HRr_fl5LGA2JlJu4zxKqmo">
> I'm going to look into fixing this on our end.
> 
> Let me know if this works for you. Thank you 🙂

Yes, just change it manually. Thank you.

**Comment by gkasireddy202** [comment]
@vonovak - Thanks for your reply.
It is working now.
