### ISSUE TITLE
Expo-av do not record in background for Android 

### ISSUE THREAD

**Issue by meteorSD** [expo/expo#30371]
### Minimal reproducible example

https://gitlab.com/rubendjan/audio-record-background

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

I am using expo-av to record audio from the microphone. When the app goes to the background or when i lock the screen, the recording stops. 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 3.6.4 - /usr/local/bin/yarn
      npm: 2.15.12 - ~/node_modules/.bin/npm
      Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 29, 30, 31, 33, 34
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-25 | Google APIs ARM 64 v8a, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-31 | Google Play ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.20 => 51.0.20 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.1.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that native modules do not use incompatible support packages
Unexpected error while running 'Check that native modules do not use incompatible support packages' check:
Error: Dependency tree validation for react-native-unimodules failed. This validation is only available on Node 16+ / npm 8.
✖ Check for legacy global CLI installed locally
Unexpected error while running 'Check for legacy global CLI installed locally' check:
Error: Dependency tree validation for expo-cli failed. This validation is only available on Node 16+ / npm 8.
✔ Check npm/ yarn versions
✖ Check that native modules use compatible support package versions for installed Expo SDK
Unexpected error while running 'Check that native modules use compatible support package versions for installed Expo SDK' check:
Error: Dependency tree validation for metro failed. This validation is only available on Node 16+ / npm 8.
✔ Check that packages match versions required by installed Expo SDK
One or more checks failed, indicating possible issues with the project.

**Comment by meteorSD** [comment]
After a few research, I noticed that app the issue appeaers in expo 50 with the support of react native 0.73.X and Android 14.

**Comment by meteorSD** [comment]
If it can help anyone, i managed to solve this issue. 

Here's how : 

First you need to use prebuild to generate native folders. 

Then, install a library that can help you handle ForegroundService (I used @supersami/rn-foreground-service) and follow every steps in the installation process. 

Right after launching the recording of the audio, launch a foreground service using the library. 

Finally, edit the Manifest.xml and replace this : 
    <service android:name="com.supersami.foregroundservice.ForegroundService"
             android:stopWithTask="true" />
    <service android:name="com.supersami.foregroundservice.ForegroundServiceTask" android:stopWithTask="true" />

with this : 

    <service android:name="com.supersami.foregroundservice.ForegroundService"
             android:stopWithTask="true"
             android:foregroundServiceType="microphone" />
    <service android:name="com.supersami.foregroundservice.ForegroundServiceTask" android:stopWithTask="true"  android:foregroundServiceType="microphone"/>

There you go ! 

I am planning of write an article on this issue, let me know if it could help anyone.

**Comment by meteorSD** [comment]
If this can help anyone, I managed to solve the issue.

Here’s how:

First, you need to use `expo prebuild` to generate native folders.

Then, install a library that can help you handle ForegroundService (I used `@supersami/rn-foreground-service`) and follow every step in the installation process.

Right after launching the audio recording, start a foreground service using the library.

Finally, edit the `Manifest.xml` and replace this:

```xml
<service android:name="com.supersami.foregroundservice.ForegroundService"
         android:stopWithTask="true" />
<service android:name="com.supersami.foregroundservice.ForegroundServiceTask" android:stopWithTask="true" />
```

with this:

```xml
<service android:name="com.supersami.foregroundservice.ForegroundService"
         android:stopWithTask="true"
         android:foregroundServiceType="microphone" />
<service android:name="com.supersami.foregroundservice.ForegroundServiceTask" android:stopWithTask="true"  android:foregroundServiceType="microphone"/>
```

There you go!

I am planning to write an article on this issue, let me know if it could help anyone.

**Comment by jogyfelix** [comment]
@meteorSD I am also running into the same problem.Foreground service solves the background problem but when I clear the app from memory while recording and the next time when I start the recording it throws an error. 
`Error: Only one Recording object can be prepared at a given time.`
Looks like the old reference is not deallocated from the memory if the app is closed midway. Foreground service is cleared though
