### ISSUE TITLE
Using native and react components

### ISSUE THREAD

**Issue by fzf** [expo/expo#30387]
### Minimal reproducible example

https://github.com/fzf/StreamExample

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I am hoping there is a better solution to this problem. Basically, I wanted to use the https://github.com/GetStream/stream-chat-react-native library for ios and android and the https://github.com/GetStream/stream-chat-react for web. I ran into some issues where it seems that libraries are loaded from "index.js" file even if it is overridden with a `.ios` or `.web` extension. This means that I have to create a semi-blank `index.js` as well as an `index.ios.js` and `index.web.js`. I got it working and I understand this is possibly an edge case I just wanted to make sure there is not a cleaner way to implement this that I am just ignorant of.

I had to make some modifications to my `metro.config.js` to get things running.

```
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

const config = getDefaultConfig(__dirname);
config.resolver.unstable_enablePackageExports = true
config.resolver.extraNodeModules = {
  crypto: require.resolve('expo-crypto'),
};
// https://github.com/facebook/metro/issues/1272
config.resolver.unstable_conditionNames = [
  'browser',
  'require',
  'react-native',
]

module.exports = config;
```

Basically before expo@51 I was able to get this to work with this `webpack.config.js`:
```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const path = require('path')

module.exports = async function(env, argv) {
    const config = await createExpoWebpackConfigAsync(env, argv);
    config.resolve.alias['stream-chat-expo'] = 'stream-chat-react';
    config.resolve.fallback = {
      ...config.resolve.fallback,
      crypto: require.resolve('expo-crypto'),
    };
    return config;
};
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.3.0 - ~/.asdf/installs/nodejs/21.3.0/bin/node
      Yarn: 1.22.21 - ~/.asdf/installs/nodejs/21.3.0/bin/yarn
      npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/fzf/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.20 => 51.0.20
      expo-router: ~3.5.18 => 3.5.18
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 10.1.1
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Currently this is expected behaviour. The best solution is to seperate this out into platform specific components (not routes)
