### ISSUE TITLE
run:android gets stuck

### ISSUE THREAD

**Issue by raisfeld-ori** [expo/expo#30401]
### Summary

recently I tried to run ```npm run android``` in my expo project (usually I just run ```npx expo```) in order to link a new package in my project, but after waiting for an hour (yes, an actual HOUR) it kept being stuck with no text
![image](https://github.com/user-attachments/assets/5365f3d0-88c8-4525-ad20-109fc6aebf55)
at first I thought the error was missing, so I Tried running ```npx expo run:android```
![image](https://github.com/user-attachments/assets/f3ca21dd-0bf7-42ca-89c7-1893e0a7e715)
but that as well kept being stuck this way.

I tried simply making a new project and installing the packages I had in the project (google-signin and expo-image-picker) and I got the same error. it seems like ```npx expo run:android``` just gets stuck for no reason? I'd love to get an explanation

### What platform(s) does this occur on?

Android

### SDK Version

0.18.25

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 34.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-233.14808.21.2331.11709847
    npmPackages:
      expo: ~51.0.20 => 51.0.20
      react: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
    Expo Workflow: bare

### Minimal reproducible example

by running:
```
npx create-expo-app testing --template blank
npx expo run:android
```
I already got the issue this way, but I also had some packages installed in the project(you don't have to run these commands, but it could help understanding what's happening):
```
yarn add @react-native-google-signin/google-signin
npx expo install expo-image-picker
```

**Comment by raisfeld-ori** [comment]
figured it out!

it seems that the command ```npx react-native run-android``` had an error right at the start, and for some reason expo didn't register it, so it kept on waiting for an output even after the task failed. after using ```npx react-native doctor``` and finding out the issues in my machine (my java version was 22) I managed to fix the error and now the ```npm run android``` works

**Comment by ynshung** [comment]
If anyone is facing a similar issue, you can try opening Task Manager, end `adb.exe` and run the command again

**Comment by AlexTLeo** [comment]
@ynshung that did it for me, thanks!

**Comment by galbenyosef** [comment]
@ynshung same for me, looks like adb.exe being stacked and stuck in memory somehow
