### ISSUE TITLE
Unclear format for ios.associatedDomains

### ISSUE THREAD

**Issue by JohnPhoto** [expo/expo#3040]
It is a bit unclear on which format to supply the associated domains values, a short example would be nice, something like this perhaps:

The items in the array needs to be on the format: `applinks:www.mydomain.com` as documented here [Support Universal Links](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html)

**Comment by alexpopa-work** [comment]
What's the right format though? applinks:www.mydomain.com?

**Comment by FiberJW** [comment]
This seems to be resolved, so I'll close this for now. If you have any further related problems, please open another issue. Thanks :)
