### ISSUE TITLE
Better document the format of output from Permission module

### ISSUE THREAD

**Issue by carsonwah** [expo/expo#3042]
[About the Permission module](https://github.com/expo/expo-docs/blob/master/versions/v23.0.0/sdk/permissions.md)

Now it just said it returns `status, expiration and scope`. Should we write them out clearly instead of developers guessing around?

I'm not sure about expiration and scope. As far as I know, status includes `undetermined, denied and granted`, but I can't be certain enough to make a pull request because there is no exact doc talking about that.

Could someone familiar with the API write these out clearly?

**Comment by alexpchin** [comment]
@carsonwah Please update the link in your issue.

**Comment by FiberJW** [comment]
This seems to be resolved in the latest version of the `Permissions` API docs, so I’ll close this for now. If you notice any places where our docs can be clearer in the future, feel free to open a new PR or issue :)
