### ISSUE TITLE
Auto linking fails to link android when using build.gradle.kts

### ISSUE THREAD

**Issue by amrfarid140** [expo/expo#30447]
### Minimal reproducible example

https://github.com/amrfarid140/gradle-kts-issue-reproducer

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Create a new native module using `npx create-expo-module` and try to rewrite `android/build.gradle` from Groovy to Kotlin and changing its extension to `.gradle.kts`

`.gradle.kts` is a valid Android build configuration file but Expo auto linking fails to link the native module [because it is hardcoded](https://github.com/expo/expo/blob/0797cb28e98e5fe34f04e97fc9a24fc5f8740545/packages/expo-modules-autolinking/src/platforms/android.ts#L28) to detect `build.gradle` only.

In the reproduction sample provided, I expect Android compilation to fail since `modules/my-module/android/build.gradle.kts` has invalid syntax but when you build Android you can see that compilation succeeds and `my-module` isn't detected at all by the auto-linking logic.

### Environment

N/A

### Expo Doctor Diagnostics

N/A

**Comment by amandeepmittal** [comment]
Seems like this was fixed by #30448. Closing it for now.
