### ISSUE TITLE
[expo-notifications] Push notification icon not working on some Android devices

### ISSUE THREAD

**Issue by lethib** [expo/expo#30451]
### Minimal reproducible example

https://github.com/lethib/android-notif-icon

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Intro 

I have created this new issue because the original one has been closed: https://github.com/expo/expo/issues/24844
However, I am still experiencing this issue for some Android devices despite the proposed solutions in the issue.

### The issue

While testing my app notifications, I saw that the app icon was not showing for my device. I did some tests with iOS devices and they correctly have the icon displaying in the push notification. 

I have been able to reproduce this in the minimal reproducible example and here is the result I have on my Pixel phone 👇

![share_1853017256972883034](https://github.com/user-attachments/assets/b35573a8-150d-4581-8030-90445719bf07)

The notification at the top is the some sent directly from the minimal app and the second one, using [expo's push notifications tool](https://expo.dev/notifications).
I have a blank square instead of the app icon which is the following one:
<img width="353" alt="image" src="https://github.com/user-attachments/assets/c22541ac-2e0a-4480-a9c7-faeb707ffcf9">

Here is the result for another Android device 👇

<img width="853" alt="Screenshot 2024-07-17 at 12 23 00" src="https://github.com/user-attachments/assets/747fc425-84c0-46f4-869c-9bf1e84db71c">

On this one, the app icon appears correctly (_it may not be that easy to see_) in the push notification.

### Devices used

| Device | Platform | OS Version | App icon showing ? |
| :---: |     :---:      | :---: | :---: |
| Huawei P30 Lite | Android | 9 | ✅ |
| Google Pixel 8 | Android | 14 | ❌ |
| Samsung A41 | Android | 12  | ❌ |

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.21 => 51.0.21
      expo-router: ~3.5.18 => 3.5.18
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 9.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by etothepowerofitimespiequalsminusone** [comment]
I found out the hard way (carelessly read the docs) that the notification icon has to be all-white transparent, despite some users in the [original report ](https://github.com/expo/expo/issues/24844) claiming otherwise.

`Local path to an image to use as the icon for push notifications. 96x96 all-white png with transparency.` - notice the **all white** part, which I believe the icon in the example is not.

Documentation: https://docs.expo.dev/versions/latest/sdk/notifications/#configurable-properties

**Comment by lethib** [comment]
@etothepowerofitimespiequalsminusone Thanks for your comment ! That solved my issue. I was a bit skeptical about this solution at first but by looking at my other app notification icons, I saw that every icon was all white with a custom background color !
