### ISSUE TITLE
Deploying Expo API Routes without building for Web Platform

### ISSUE THREAD

**Issue by ProchaLu** [expo/expo#30450]
### Minimal reproducible example

https://github.com/ProchaLu/expo-api-routes-mobile

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I would like to deploy my Expo API Routes without building and deploying the web platform. In the [Expo documentation](https://docs.expo.dev/router/reference/api-routes/#deployment), it is necessary to build the web application using `npx expo export -p web`. However, my focus is only on the mobile application with Expo API Routes, and I do not want deploy the web version. This can be a limitation for developers who do not need a web version of their application but want to take advantage of the Expo API Routes for their mobile applications. 

Additionally, @kockar96 raised a similar concern in this [discussion thread](https://github.com/expo/expo/discussions/28743) a few months ago.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - /opt/homebrew/opt/node@20/bin/node
      npm: 10.7.0 - /opt/homebrew/opt/node@20/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.21 => 51.0.21 
      expo-router: ^3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ^0.19.12 => 0.19.12 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

**Comment by marklawlor** [comment]
The API routes feature is still experimental and during this stage there are no plans to introduce a different export command for them. We are still working on better server support / deployment support, so its hard to provide a command for something that is a work-in-progress. This will be resolved before the feature is stabilised.

If you have a components that "break" the web build, I would commend creating platform specific stubs for them. As your not actually running the code, these components can turn `null`.

**Comment by jancbeck** [comment]
+1 since I ran into an [issue with NativeWind](https://github.com/nativewind/nativewind/issues/591) where the web export failed but I only needed the API endpoint anyways. The suggested workaround by @marklawlor would not have worked since the error came from the global.css included in the _layout.tsx file. Simply disabling the web export for non-API endpoints would have saved me quite the headache.
