### ISSUE TITLE
Expo-sqlite iOS bug when inserting values that contains "–" (Em-Dash)

### ISSUE THREAD

**Issue by j1h23** [expo/expo#30492]
### Minimal reproducible example

https://github.com/j1h23/expo-sqlite-emdash-bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

In iOS, when running an insert statement in expo sqlite, whose value includes "–" (Em-Dash), the insert statement will fail. The expected behavior is that this insert statement should work. This does not seem to be an error when running on Android. The error message is "Calling the 'prepareAsync' function has failed."

An odd behavior I observed is that if I add a line break at the end of the insert statement, I am able to run the insert statement successfully.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-33 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.21 => 51.0.21 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by j1h23** [comment]
Shares similar characteristics as the below issue, except I did not encounter this issue in android.

https://github.com/expo/expo/issues/30177

**Comment by j1h23** [comment]
I have found 2 temporary workaround:

1. Don't use runAsync, use execAsync instead. The runAsync method includes the prepareAsync call, which can be avoided if you use execAsync. You should read the documentation about the drawbacks of using execAsync.
2. Add a line break at the end of your query. This seems to allow the statements to work with special characters. Not sure why...

**Comment by ryzencool** [comment]
when on ios, some strange error ocurred, such as “更新日志😯” is ok but “dinox更新日志😯” not work, everything is ok on android
