### ISSUE TITLE
StatusBar not working with expo-router

### ISSUE THREAD

**Issue by ryhuz** [expo/expo#30497]
### Minimal reproducible example

https://github.com/ryhuz/expo-router-status-bar-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When trying to alter the status bar either with `StatusBar` from `react-native` or from `expo-status-bar`, the effects of `backgroundColor` and `barStyle` are not applied.

A similar issue was reported [here](https://github.com/expo/router/issues/754)

Steps to reproduce:
1. Initialise a new expo app
2. `useFonts` was not needed so removed that, as well as the `loaded` check.
`StatusBar` works if this `loaded` check is done. Probably due to the page rendering after the stock `StatusBar` from `ExpoRoot` from `expo-router` is loaded (see linked issue for more details)
3. Add in `StatusBar`, doesn't matter if in `_layout` or on a screen
4. If it is a fresh start (both expo go or dev build), or the app is reloaded, `StatusBar` properties are not applied (both android and ios; only `barStyle` on ios).
If the app is already loaded, then the `StatusBar` is added and the app fast-refreshes, it works.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /usr/local/bin/node
      npm: 9.8.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/shawn.wee/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.21 => 51.0.21 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

**Comment by evelant** [comment]
I'm also seeing that on expo 51.0.14, expo-router 3.5.16, expo-status-bar 12.12.1. No matter where I put the `<StatusBar` component it seems to have no effect since I added expo-router to my project.

**Comment by arasrezaei** [comment]
problem still exists... only imperative methods inside use effect work.

**Comment by arsalannury** [comment]
I tried many solutions but until now, only @arasrezaei use effect suggestion works

**Comment by timheilman** [comment]
I'm seeing this issue at expo 51.0.22, expo-router 3.5.18, expo-status-bar 1.12.1.

**Comment by zackify** [comment]
I'm not sure why this was ever closed: https://github.com/expo/router/issues/754

for now you have to run yarn patch-package expo-router after commenting out line 60 in expo-router/build/ExpoRoot.js

**Comment by sivercone** [comment]
**Steps to patch expo-router (~3.5.23):**

1. Install packages `npm install patch-package postinstall-postinstall --save-dev`
2. Navigate to `node_modules/expo-router/build/ExpoRoot.js`
3. Comment out the line 60 by adding `//` at the beginning of the line.
4. run `npx patch-package expo-router`
5. Add a `postinstall` script to your `package.json` to ensure your patches are applied automatically after every install:
```
"scripts": {
  "postinstall": "patch-package"
}
```
6. To test if your patch works as expected, reinstall your packages: `npm install`

Now you should be able to use `<StatusBar style={colorTheme === 'dark' ? 'light' : 'dark'} />` (expo-status-bar) in the `_layout.tsx`

**Comment by ryhuz** [comment]
just to confirm, the suggestions to patch package by @zackify and @sivercone work.

would be great to have an official fix though

**Comment by karlhorky** [comment]
The `<StatusBar>` component can be used again starting in [Expo Router v4.0.0-preview.0](https://github.com/expo/expo/blob/main/packages/expo-router/CHANGELOG.md#400-preview0--2024-10-22) 🎉

> Render the default StatusBar before screens are rendered. (https://github.com/expo/expo/pull/31624 by [@marklawlor](https://github.com/marklawlor))

References:

- https://github.com/expo/expo/issues/30497
- https://github.com/expo/expo/pull/31624

**Comment by sebestyn168** [comment]
...
"expo-router": "5.1.6",
"expo-status-bar": "2.2.3",
only the system theme is applyed on ios (works on android)
