### ISSUE TITLE
Error: Not a valid base64 encoded string length

### ISSUE THREAD

**Issue by ivaylonikolov7** [expo/expo#30503]
### Minimal reproducible example

https://github.com/ivaylonikolov7/hedera-expo-issue

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

Currently when you open the app from the GitHub repository I provided in the Android simulator, it shows a warning bubble and throws an error:

> ERROR Error during transaction: [Error: Not a valid base64 encoded string length]

This wasn't an issue in previous versions of expo but as of right now it's a problem. You can reproduce it by running the following steps:

- clone the repository I provided
- npm install --force
- npx expo start --clear
- run it in Android simulator on Android API 35. I have ran my app on Pixel Fold but I think it's reproducible on all devices. 
- you will see a warning and when you open it you will see "Possible unhandled promise rejection. Error: not a valid base64 encoded string length". This is triggered when I ran the follow code:
```javascript
      const privateKey = PrivateKey.generateECDSA();

      const response = await new AccountCreateTransaction()
        .setKey(privateKey)
        .execute(client);
```

It's not a problem with the `@hashgraph/sdk` package. I've already tested and saw that the execution from this code is successful and isn't the issue. Also it's not an issue in previous version too. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
      npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
      Watchman: 2024.07.08.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.21 => 51.0.21 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by vonovak** [comment]
Hello and thanks for reporting,
your minimal repro cannot run because this part of the code:

```
  const OPERATOR_KEY = PrivateKey.fromStringECDSA(
    process.env.EXPO_PUBLIC_PRIVATE_KEY ?? ""
  );
```

because there is no env variable provided in the repo.

I did not run the code but I suspect that it's related to [this issue](https://github.com/facebook/hermes/issues/1379) in Hermes JS engine. As a workaround I'd suggest using different `atob` implementation, e.g. from [here](https://github.com/craftzdog/react-native-quick-base64) until the fix is available.

Also, let me point out that `EXPO_PUBLIC_PRIVATE_KEY` sounds like you're exposing a private key as part of the application bundle. This could be a serious security risk so please make sure you know what you're doing.

Thank you 🙂

**Comment by DanielRivers** [comment]
I am experiencing the same when trying to work with a valid JWT token, seems to only affect android

**Comment by brentvatne** [comment]
@ivaylonikolov7 @DanielRivers - can either of you please provide a minimal reproducible example without any external dependencies? if this is indeed an issue on the expo side and not related to `@hashgraph/sdk` then it should be reproducible without it

**Comment by rubixvi** [comment]
> Hello and thanks for reporting,
> your minimal repro cannot run because this part of the code:
> 
> ```
>   const OPERATOR_KEY = PrivateKey.fromStringECDSA(
>     process.env.EXPO_PUBLIC_PRIVATE_KEY ?? ""
>   );
> ```
> 
> because there is no env variable provided in the repo.
> 
> I did not run the code but I suspect that it's related to [this issue](https://github.com/facebook/hermes/issues/1379) in Hermes JS engine. As a workaround I'd suggest using different `atob` implementation, e.g. from [here](https://github.com/craftzdog/react-native-quick-base64) until the fix is available.
> 
> Also, let me point out that `EXPO_PUBLIC_PRIVATE_KEY` sounds like you're exposing a private key as part of the application bundle. This could be a serious security risk so please make sure you know what you're doing. Feel free to read more about this in this comprehensive article [on our blog](https://expo.dev/blog/what-are-environment-variables).
> 
> Thank you 🙂

This is not correct, regardless of the public key. The code won't run with any key. It is reproduced in Android, unrelated to the env. This can be verified hard coded, the key should be replaced with a secure stored key, however for testing purposes it was passed through as such. The way the code is ran, EXPO_PUBLIC will naturally pull the set information.

The work around doesn't solve the issue.
