### ISSUE TITLE
websocket connection fail between appwrite realtime service and expo web

### ISSUE THREAD

**Issue by bilelBoulhia** [expo/expo#30516]
### Minimal reproducible example

https://github.com/bilelBoulhia/expo-bug-report

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

in Expo Go

### Summary

**expected behavior :** 
When initializing a client and subscribing to an event using the Appwrite Realtime service, a WebSocket connection should be established between the Appwrite cloud and the Expo web application. 

**code below for demo :**

```
export default function App() {
  const PROJECT_ID = 'project_id';  //an appwrite project need to be created at cloud.appwrite.io/console
  const ENDPOINT = 'https://cloud.appwrite.io/v1';// Set universal endpoint

  useEffect(() => {

    const client = new Client();
    client.setEndpoint(ENDPOINT); 
    client.setProject(PROJECT_ID); 





    const unsubscribe = client.subscribe('files', response => {
      console.log(response);
    });

   
    return () => unsubscribe();
  }, []);

  return (
    <View style={styles.container}>
      <Text>Check console for output</Text>
      <StatusBar style="auto" />
    </View>
  );
}
```

**the actual behavior :**
`websocket connection fails , check the error below `

![errCapture](https://github.com/user-attachments/assets/6e1e7a1f-cedf-4daa-85ef-9bfc7deedf6a)

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.21 => 51.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ^0.19.12 => 0.19.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by byCedric** [comment]
Hi @bilelBoulhia! Expo web has support for (what I assume) is websockets, it just uses the platform native websockets available. When running on web, this uses [the WebSocket spec](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). Internally in Expo, we also use it for fast refresh and other update-related things.

Since this is a 3rd party library, I'd recommend opening an issue on their repository. WebSockets in general should work in Expo, and looking at the logs, it seems to connect to appwrite but then close for some reason.

Hope this helps!

**Comment by bilelBoulhia** [comment]
@byCedric that's exactly what i did , i submitted a report to  appwrite and  they explicitly told me that the problem is on expo's end hence why i submitted  this issue , thank you anyways

**Comment by stnguyen90** [comment]
@byCedric, according to [React Native's source code](https://github.com/facebook/react-native/blob/9af63956d2a767538dbbf5be6a38e27a55625fde/packages/react-native/Libraries/WebSocket/WebSocket.js#L98), the WebSocket constructor is:

```javascript
constructor(
    url: string,
    protocols: ?string | ?Array<string>,
    options: ?{headers?: {origin?: string, ...}, ...},
  )
```

This works in Android and iOS, but it looks like it has a problem in web. For example, you can reproduce the problem by adding this `useEffect`:

```javascript
  useEffect(() => {
    console.log('connecting');

    // doesn't work
    const s = new WebSocket('wss://echo.websocket.org', undefined, {
      headers: {
        Origin: 'RN',
      },
    });
    // works
    // const s = new WebSocket('wss://echo.websocket.org', undefined);

    s.addEventListener('message', (m) => console.log('message', m));
    s.addEventListener('close', (e) => console.log('close', e));
  }, []);
```

**Comment by stnguyen90** [comment]
@byCedric, have you had a chance to review my last message?
