### ISSUE TITLE
a bit of confusion on expo export --public-url (distribution/hosting-your-app.md)

### ISSUE THREAD

**Issue by ryh** [expo/expo#3052]
the URL.1 for the QR Code is `exp://host/path/platform-index.json` 
And the user will have to generate two different QR Codes for both iOS and Android , just exp://host/path/ would be nice.
  (open another issue on Expo Client github.com/expo/expo ?)

and the URL.2 following  expo export --public-url is `scheme://host/path` without the file name
(`<path-to-android-index.json>` in the Doc, I miss-typed with `scheme://host/path/ios-index.json` for the first time )
And since the example URL in Doc `https://quinlanj.github.io/self-host/android-index.json` is 404
it would be nice to use a real URL or `example.com` instead of `quinlanj.github.io`

**Comment by tsapeta** [comment]
It seems to be already fixed in the docs.
