### ISSUE TITLE
Android/IOS Store build fail when using alias path

### ISSUE THREAD

**Issue by mduc-dev** [expo/expo#30528]
### Summary

I can not build production with eas when using alias path 

### What platform(s) does this occur on?

Android, iOS

### SDK Version

51

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 11.7.10
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/macos/.rvm/rubies/ruby-2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.17 => 51.0.18 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 10.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Minimal reproducible example

I can not provide my repo, below is some screenshot for my config

<img width="612" alt="Screen Shot 2024-07-19 at 21 42 26" src="https://github.com/user-attachments/assets/7531086c-028f-4ec4-bf4d-643cc7f8a98c">
<img width="468" alt="Screen Shot 2024-07-19 at 21 42 43" src="https://github.com/user-attachments/assets/8ef514fd-ef5f-484d-a2b4-9d39eba775b9">
<img width="669" alt="Screen Shot 2024-07-19 at 21 43 07" src="https://github.com/user-attachments/assets/25614b92-d019-40d1-a661-ea6f44de2d12">

<img width="588" alt="Screen Shot 2024-07-19 at 21 43 19" src="https://github.com/user-attachments/assets/8eb5fc5d-4dbe-468d-b222-6d9f96184c72">

**Comment by mduc-dev** [comment]
<img width="925" alt="Screen Shot 2024-07-19 at 21 44 40" src="https://github.com/user-attachments/assets/49a75b70-021c-43a3-bc4b-af025abd6ee5">

and there is error seeing on EAS, i tried many ways but not working

**Comment by byCedric** [comment]
Hi @mduc-dev! Expo has support for typescript paths, but I see you also added the babel module resolver plugin. That plugin is missing the `@hooks` alias, meaning that might be the cause Metro is not able to find it.

We'd need a full repro in order to figure out exactly what's going on.

Hope this helps!

**Comment by mduc-dev** [comment]
> Hi @mduc-dev! Expo has support for typescript paths, but I see you also added the babel module resolver plugin. That plugin is missing the `@hooks` alias, meaning that might be the cause Metro is not able to find it.
> 
> We'd need a full repro in order to figure out exactly what's going on.
> 
> Hope this helps! 

Hi @byCedric, i see the documents but in development channel is build successfully with that config, also i was follow expo for config but still not working for me 😅
