### ISSUE TITLE
Localization.locale returns 2-char code

### ISSUE THREAD

**Issue by ckknight** [expo/expo#3053]
As per https://docs.expo.io/versions/latest/sdk/localization, it specifies

`Localization.locale: string`
Native device language, returned in standard format. ex: `en-US`, `es-US`.

On Expo SDK 31, this returns `'en'` for me instead of `'en-US'` (on iOS, haven't tested Android).

`locales` also returns `['en']`

**Comment by ide** [comment]
Both "en" and "en-US" are valid, standard locale strings. Will update the docs to reflect this.
