### ISSUE TITLE
How do I find if the calendar is default Calendar , so that I can create event on it. 

### ISSUE THREAD

**Issue by swati-kholiya** [expo/expo#3054]
Expo.Calendar.getCalendarsAsync() returns me array of entities . Not sure I find which one is default one.

**Comment by FiberJW** [comment]
This is resolved in SDK 35. You can find the related docs here: https://docs.expo.io/versions/v35.0.0/sdk/calendar/#calendargetdefaultcalendarasync Thanks :)
