### ISSUE TITLE
expo-camera not working

### ISSUE THREAD

**Issue by shankarabhishek28** [expo/expo#30549]
### Minimal reproducible example

https://github.com/shankarabhishek28/reproducible/blob/new/components/Authenticated.tsx

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None
**### ISSUE**
**### //when i am rendering <Camera></Camera> its saying
"JSX element type 'Camera' does not have any construct or call signatures.ts"

//also Camera.Constants.Type thowing error
Property 'Constants' does not exist on type '{ getCameraPermissionsAsync: () => Promise<PermissionResponse>; requestCameraPermissionsAsync: () => Promise<PermissionResponse>; getMicrophonePermissionsAsync: () => Promise<...>; requestMicrophonePermissionsAsync: () => Promise<...>; scanFromURLAsync: (url: string, barcodeTypes?: BarcodeType[] | undefined) => Prom...'**

### Summary

import React, { useState, useRef, useEffect } from 'react';
import { StyleSheet ,Text, View, Button,} from 'react-native';
import { Camera } from 'expo-camera';
import { Video } from 'expo-av';

const Authenticated: React.FC = () => {
  const [hasAudioPermission, setHasAudioPermission] = useState<boolean>();
  const [hasCameraPermission, setHasCameraPermission] =useState<boolean>();
  const [camera, setCamera] = useState(null);
  const [record, setRecord] = useState(null);
  const [type, setType] = useState(Camera.Constants.Type.back);
  useEffect(()=>{
(async()=>{
  const cameraPersmission = await Camera.requestCameraPermissionsAsync();
  const microphonePermission  = await Camera.requestMicrophonePermissionsAsync();

  setHasCameraPermission(cameraPersmission.status === "granted")
  setHasAudioPermission(cameraPersmission.status === "granted")

})();
  },[])
if(hasCameraPermission === undefined || hasAudioPermission === undefined){
  return <Text>Requesting Permissions</Text>
}
else if(!hasCameraPermission){
  return <Text>Permission to cam not grantyed</Text>
}
  return (
   <Camera>
    <Text>ei</Text>
   </Camera>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  buttonContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    margin: 20,
  },
  button: {
    flex: 1,
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  text: {
    fontSize: 18,
    color: 'white',
  },
});

export default Authenticated;

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.2 - ~\Desktop\Originbluy\originbluy_task\node_modules\.bin\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 31, 32, 33, 34
        Build Tools: 29.0.2, 30.0.3, 33.0.0, 34.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~51.0.20 => 51.0.21
      expo-router: ~3.5.18 => 3.5.18
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed

**Comment by alanjhughes** [comment]
@shankarabhishek28 the component is called `CameraView` not `Camera` https://docs.expo.dev/versions/latest/sdk/camera/
