### ISSUE TITLE
[expo-local-authentication] Android: crash when setting disableDeviceFallback to true (unless cancelLabel is set)

### ISSUE THREAD

**Issue by cclacq** [expo/expo#30556]
### Minimal reproducible example

github.com

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Setting `disableDeviceFallback` to true leads to a crash when calling `authenticateAsync`. Workaround for this is to set the `cancelLabel`.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.0.0 - /opt/homebrew/bin/node
      npm: 10.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /Users/uhw/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31, 32, 33, 34
        Build Tools: 30.0.3, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.21 => 51.0.21 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ^0.19.12 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

(node:54546) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

(node:54658) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  react-native-safe-area-context@4.10.1 - expected version: 4.10.5
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by cross19xx** [comment]
@cclacq, can you provide a minimum reproducible example?

**Comment by behenate** [comment]
Fixed by @dcangulo in https://github.com/expo/expo/pull/32076

**Comment by MisterCommit** [comment]
const biometric = await authenticateAsync({
biometricsSecurityLevel: "strong",
disableDeviceFallback: true,
cancelLabel: "Cancel",
});
just add cancelLabel: "Cancel",
