### ISSUE TITLE
Link in docs is not working

### ISSUE THREAD

**Issue by dzienisz** [expo/expo#3056]
`add an App Transport Security exception.` link is not working :( [Link](https://docs.expo.io/versions/latest/react-native/integration-with-existing-apps.md#test-your-integration)

![image](https://user-images.githubusercontent.com/3521624/49380685-7a696680-f712-11e8-9ffc-464f245aa480.png)

**Comment by cruzach** [comment]
Looks like this was fixed in [this commit](https://github.com/expo/expo/commit/b64b297bf9df2f46302ad9f8f8390e45d018ed6b#diff-754aee6b88ba32558d9a58f4ebb8136d)
