### ISSUE TITLE
Motion permission on IOS has status granted but is not granted

### ISSUE THREAD

**Issue by sirusbaladi** [expo/expo#30571]
### Minimal reproducible example

https://snack.expo.dev/@sirusbaladi/permissions-motion-ios-granted-false

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When requesting motion permissions **await DeviceMotion.requestPermissionsAsync();** the status says granted and granted is true even if the user never receives the IOS permission request modal. 
Also something very weird happens. When I shake the device and hit reload, the app will reload and weirdly the IOS motion permission request shows. In other words, the motion permission dialog will show delayed at app reload. 

The expected behavior would be for the user to receive the IOS permission request and for status to correctly reflect the user input ( denied or allowed). 

I'm having no issues with all the other permissions: Location & Notification. 
 "expo-sensors": "~12.1.1",

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-221.6008.13.2211.9477386     
    npmPackages:
      expo: ^48.0.21 => 48.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.14 => 0.71.14
      react-native-web: ~0.18.7 => 0.18.12
    Expo Workflow: managed

### Expo Doctor Diagnostics

Didn't find any issues with the project!

**Comment by sirusbaladi** [comment]
any help

**Comment by brentvatne** [comment]
hi there! please update to the latest sdk version and try to reproduce it there. if you still encounter the issue, let me know here and share a reproducible example using that version.

**Comment by mcevoypeter** [comment]
@brentvatne, I'm seeing identical behavior to what @sirusbaladi on the latest verison of the SDK.

## Reproducible Example

```javascript copy
import { Button } from 'react-native';

const Button = () => (
  <Button
    title="Request sensor permissions"
    onPress={async () => {
      const response = await DeviceMotion.requestPermissionsAsync();
      console.log('response', response);
    }}
  />
);
```

When loading the app the first time, the permissions modal is not presented when I press the button, and `response` is:

```json copy
{"canAskAgain": true, "expires": "never", "granted": true, "status": "granted"}
```

When I reload the app, the modal permissions modal is shown immediately without pressing the button.

## Environment
Package | Version
-|-
`expo` | `51.0.21`
`expo-sensors` |  `13.0.9`

**Comment by dougschurman** [comment]
Bump. Having the same issue, even with a production build on testflight.

**Comment by cizar** [comment]
I'm seeing the same issue in expo-sensors 14.0.2. My app checks permissions on startup to prompt the user to request pending permissions. Location and notifications returns the current permission status but DeviceMotion always returns granted but it is not.
