### ISSUE TITLE
Expo image picker increases the image size of the normal image more than 10 times

### ISSUE THREAD

**Issue by RishavKumar-3796** [expo/expo#3058]
0

I am using expo image picker for selecting images and uploading them to firebase.

I am facing a issue that the image which is picked is even greater than its original size. Say, if a image is 10 kb and when its picked and after getting its size in console the size it shows is 90 kb. I don't know how to resolve this issue.

**//The code for picking image is :**

[async _pickImage() {
    const { CAMERA, CAMERA_ROLL } = Permissions;
    const permissions = {
      [CAMERA]: await Permissions.askAsync(CAMERA),
      [CAMERA_ROLL]: await Permissions.askAsync(CAMERA_ROLL)
    };

if (
  permissions[CAMERA].status === "granted" &&
  permissions[CAMERA_ROLL].status === "granted"
) {
  var pickerResult = await ImagePicker.launchImageLibraryAsync({
    base64: false,
    quality: 0.1
  });

  if (!pickerResult.cancelled) {
    console.log(pickerResult);
    this.setState({
      itemImage: pickerResult.uri
    });
    this.getFileSize(pickerResult.uri);](url)

The original image size is only 10 kb but the size of the image which I get in console after picking the image is : 84 kb.

**File uri is something like this!**
"uri": "file:///Users/rishav.kumar/Library/Developer/CoreSimulator/Devices/9038FD49-F921-43DB-A91A-C6A14DE249A3/data/Containers/Data/Application/7A90A3A2-65CF-42B4-B918-20060C410BF6/Library/Caches/ExponentExperienceData/%2540anonymous%252FGithub_eCommBasket-7858de5c-77be-4f6f-80da-dec89f3ac26b/ImagePicker/99D30C71-E9DC-416C-9799-E19C85F9E6F2.jpg",

**Comment by RishavKumar-3796** [comment]
@EvanBacon Any updates yet? 
Please help I am fed up with this issue
nothing works
@brentvatne

**Comment by Szymon20000** [comment]
Which Expo SDK version did you used? What was the format of original image?

**Comment by RishavKumar-3796** [comment]
SDK 31 and format was JPEG

**Comment by t009s** [comment]
@RishavKumar-3796  Bro how you are getting the image size? Actually I am using ImagePicker and it outputs only width, height, uri and type. I want to know the size of that image... Please help

**Comment by gogogous88** [comment]
hello, is there any update?

**Comment by gogogous88** [comment]
what I did is used manipulateAsync also, but have problem in Android saying:
[Unhandled promise rejection: Error: unexpected url: file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540markmoo%252Fexpomobile/ImageManipulator/b914cbed-0749-488c-8eb2-394cb52805e7.png]

**Comment by lukmccall** [comment]
We think of removing the `quality` attribute because it doesn't work and we can't provide a good implementation for this future. I'm suggesting stop using it. 
Without this property, your output image size will be the same as the original one.

**Comment by lukmccall** [comment]
For now, I'm closing this issue. Unfortunately, we can't ensure compression effectivity, when the photo was compressed before.
