### ISSUE TITLE
Different orientations (iPhone / iPad)

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#306]
Hi, in Xcode I can set different orientations varying by device type (for example landscape for iPad, portrait for iPhone).

<img width="666" alt="screen shot 2017-06-26 at 7 36 31 pm" src="https://user-images.githubusercontent.com/140472/27564423-e6f3b416-5aad-11e7-918d-dac660c43fa7.png">

<img width="662" alt="screen shot 2017-06-26 at 7 36 11 pm" src="https://user-images.githubusercontent.com/140472/27564422-e6bd7388-5aad-11e7-9292-78069a6b7d1c.png">

How can I achieve the same with Expo? I see the documentation states a single orientation for all device types (https://docs.expo.io/versions/v18.0.0/guides/configuration.html#orientation)

Thanks

**Comment by janicduplessis** [comment]
I think the best way to achieve this is using the new ScreenOrientation module available in sdk 18 and https://docs.expo.io/versions/v18.0.0/sdk/constants.html#userinterfaceidiom to check if it is an ipad or not.

**Comment by outaTiME** [comment]
Great @janicduplessis it is understood, but can you give me an example, which is the best place to put `Expo.ScreenOrientation.allow` to force an specific orientation? in `componentWillMount` method?

Thanks !!!
