### ISSUE TITLE
Expo 51 SDK + 'expo-dev-client' in 'package.json' + New Architecture enabled prevents app startup on iOS

### ISSUE THREAD

**Issue by bglgwyng** [expo/expo#30612]
### Summary

Expo 51 SDK + 'expo-dev-client' in 'package.json' + New Architecture enabled prevents app startup on iOS.
The Expo splash screen doesn't disappear and the dev server is not connected.
When you remove 'expo-dev-client', then the problem is resolved.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

expo: 51.0.21
expo-dev-client: 4.0.20

### Environment

expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 14.5
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
    Watchman: 2024.07.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.4/15F31d - /usr/bin/xcodebuild
  npmPackages:
    expo: ~51.0.21 => 51.0.21 
    expo-router: ~3.5.18 => 3.5.18 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.74.3 => 0.74.3 
    react-native-web: ~0.19.10 => 0.19.12 
  Expo Workflow: bare

### Reproducible demo

https://github.com/bglgwyng/expo51-sandbox

This repo is scaffolled by expo CLI and New Architecture enabled after. Also 'expo-dev-client' is added in the dependencies.
When you observed the reported behavior, then remove 'expo-dev-client' from the dependencies and see the problem disappeared.

**Comment by brentvatne** [comment]
i cannot reproduce this, i tried creating a new project from scratch:

```
yarn create expo-app my-app
cd my-app
yarn expo install expo-dev-client expo-build-properties
```

then updated app.json:

```
    "plugins": [
      "expo-router",
      [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": true
          },
          "android": {
            "newArchEnabled": true
          }
        }
      ]
    ],
```

then ran:
- `yarn expo run:ios` -> app loaded successfully
- `yarn expo run:android` -> app loaded successfully

**Comment by bglgwyng** [comment]
@brentvatne  I made a new repo. https://github.com/bglgwyng/expo51-new-arch-sandbox
```shell
npx create-expo-app@latest -e with-new-arch
npx expo install expo-dev-client
npx expo run:ios # add '-d iPhone' to use real device
```
You can get the same result with this command. If the behavior is not reproduced, I suppose it depends environment such as  device, XCode version, etc.

**Comment by bglgwyng** [comment]
I tried https://github.com/brentvatne/bglgwyng and observed that the message 'Connect to Metro to develop JavaScript' does not disappear. Can you observe the same thing? The reason I'm asking is that this behavior is a sign of the app hanging on start-up.

I missed noting a subtle observation about the relationship between the 'Connect to Metro to develop JavaScript' message not disappearing and the app hanging on start-up. I've tested various configurations, and some don't consistently produce the app hanging. Sometimes they hang, but sometimes they don't. However, none of them hide the 'Connect to Metro to develop JavaScript' message after loading, so I suppose those are related.

With the repo you provided, I haven't reproduced the app hanging problem yet. But it already shows the sign. Do you see the same thing?

**Comment by brentvatne** [comment]
> observed that the message 'Connect to Metro to develop JavaScript' does not disappear. Can you observe the same thing?

https://github.com/user-attachments/assets/e1e916f4-7e3b-43b4-aec4-3b0ebcf97bac

it does eventually disappear... but takes a while. i made a task for this internally and we'll follow up on that!

**Comment by bglgwyng** [comment]
I observed the same thing! I waited longer and I saw it disappear eventually.
I believe you will observe the app hanging too.

**Comment by alextbogdanov** [comment]
Same issue here, any fixes?

**Comment by brentvatne** [comment]
@alextbogdanov @bglgwyng - this is resolved in `expo-dev-client@4.0.21`, run `npx expo install --fix` to get it. the fix landed in https://github.com/expo/expo/pull/30663

**Comment by bglgwyng** [comment]
@brentvatne, have you also observed the app hanging issue while investigating?

**Comment by brentvatne** [comment]
@bglgwyng - i haven't, no

**Comment by robdubparker** [comment]
I seem to be experiencing this issue as well, even after updating to expo-dev-client@4.0.21.  Splash screen just hangs, then after a while I see a timeout error: "failed to connect to http://x.x.x..."

**Comment by bglgwyng** [comment]
@robdubparker I haven't found a way to consistently reproduce splash screen hanging behavior. Could you share your reproducer?

**Comment by robdubparker** [comment]
> @robdubparker I haven't found a way to consistently reproduce splash screen hanging behavior. Could you share your reproducer?

Looks like in my case the issue was due to metro.config file misconfig.  I needed to update my watchman folder path.  Thanks for the quick response.

```
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');
const workspaceRoot = path.resolve(__dirname, '../');
const projectRoot = __dirname;

const config = getDefaultConfig(projectRoot);

// Needed to add this
config.watchFolders = [workspaceRoot];

// ...
```
