### ISSUE TITLE
[docs] Expo Asset

### ISSUE THREAD

**Issue by mikkimichaelis** [expo/expo#30613]
### Summary

I'm using expo ~51.0.17

I am attempting to follow [docA](https://docs.expo.dev/develop/user-interface/assets/#serve-an-asset-locally).  Specifically "Install the expo-asset library and add the config plugin to the app config file. This plugin will embed the asset file in your native project."

Which produces on build

`PluginError: Plugin is an unexpected type: object`

I went specifically to the [doc](https://docs.expo.dev/versions/latest/sdk/asset/) for Expo Asset where I also found the invalid app.json config

```json
{
  "expo": {
    "plugins": [
      [
        "expo-asset",
        {
          "assets": ["path/to/file.png", "path/to/directory"]
        }
      ]
    ]
  }
}
```

I would happily update the documentation if I were provided with the current specifications for Expo Asset

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/asset/

### Anything else?

Thank you for your hard work!

**Comment by brentvatne** [comment]
hi @mikkimichaelis! can you run `npm why expo-asset` in your project to see if you perhaps have multiple versions, including an old version? you should have only `~10.0.0` (eg: 10.0.1, 10.0.2, etc) versions of expo-asset in your project.
