### ISSUE TITLE
[docs] Add page around "getting started" to help assess whether Expo is right for your project

### ISSUE THREAD

**Issue by ide** [expo/expo#3063]
Provide direction for people to de-risk their projects early.

**Comment by cruzach** [comment]
I think [getting to know Expo](https://docs.expo.io/versions/v35.0.0/), the [FAQ](https://docs.expo.io/versions/v35.0.0/introduction/faq/), and [why not Expo?](https://docs.expo.io/versions/v35.0.0/introduction/why-not-expo/) cover this pretty well, and this issue may have just been forgotten in the shuffle
