### ISSUE TITLE
Native-specific functions cannot be built on the web even if they are conditionally branched in Platform.os.

### ISSUE THREAD

**Issue by ko-key** [expo/expo#30636]
### Minimal reproducible example

https://github.com/ko-key/issue

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

in a development build

### Summary

useStripe does not work on the web, but it does not work with conditional branching as in the code

`Web Bundling failed 201ms node_modules/expo/AppEntry.js (1 module)
Unable to resolve "../../Utilities/Platform" from "node_modules/react-native/Libraries/Components/TextInput/TextInputState.js"`

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nodebrew/current/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nodebrew/current/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/koki/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.0 => 0.10.0 
      expo: ~51.0.21 => 51.0.22 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: ^0.74.3 => 0.74.3 
      react-native-web: ^0.19.12 => 0.19.12 
      react-navigation: ^5.0.0 => 5.0.0 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check native tooling versions
✖ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

**Comment by brentvatne** [comment]
hello, this is expected behavior from metro at the moment. you can get around this by splitting up logic into `.web.js` and `.native.js` files to avoid importing that particular code on web
