### ISSUE TITLE
expo-print bad quality on ios

### ISSUE THREAD

**Issue by markom983** [expo/expo#30638]
### Minimal reproducible example

https://github.com/markom983/sample/tree/main

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Hi,

I am developing an application for printing labels on which I print QR code and text, I use the brother ql820nwb printer and I have a problem with the print quality on the iPhone. I tried to find a solution, but so far I haven't succeeded. Has anyone had a similar problem and managed to solve it?

Image on the right is from iPhone

![print](https://github.com/user-attachments/assets/dd08c4f3-c714-4142-bc51-b84d970fa40c)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2023.11.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/markomilutinovic/.rvm/gems/ruby-2.7.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 33.0.0, 34.0.0
        System Images: android-26 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.5 => 51.0.5 
      expo-router: ~3.5.12 => 3.5.12 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.10 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 7.7.0
    Expo Workflow: managed

### Expo Doctor Diagnostics

npx expo-doctor@latest  
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by behenate** [comment]
@markom983 Have you tried to print the test print with the label printer from the native iOS tools eg. the pdf viewer? We don't have any label printers to test with, but expo-print generates a PDF, which is later printed using a system API. You can preview the PDF before printing and, the PDF generated based on your html by looks sharp, therefore I suspect that it is an issue with the iOS printer driver and not `expo-print`.
