### ISSUE TITLE
* What went wrong: Value 'C:Program FilesJavajdk-17.0.12' given for org.gradle.java.home Gradle property is invalid (Java home supplied is invalid)

### ISSUE THREAD

**Issue by vitorl1maa** [expo/expo#30644]
### Minimal reproducible example

Without reproduction examples

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I am facing a problem when creating an Android development build. After updating the distributionUrl in **gradle-wrapper.properties** from `distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-all.zip`, I started receiving the following error:

```
Build failed with an exception.
* What went wrong:
Value 'C:Program FilesJavajdk-17.0.12' given for org.gradle.java.home Gradle property is invalid (Java home supplied is invalid)
```
The error occurs even after I set the environment variables `JAVA_HOME` and `Path` as you can see in the images below:
![Captura de tela 2024-07-26 095742](https://github.com/user-attachments/assets/7fee81b7-0c44-4d1f-bd7b-6947b9fdfade)
![Captura de tela 2024-07-26 100130](https://github.com/user-attachments/assets/256f7684-c3de-40ea-928c-6feea94b3006)

Within **android/gradle.properties** I am specifying the location of my JAVA_HOME with the directory path:
![code](https://github.com/user-attachments/assets/2a9e5781-22d7-4085-a09d-4755d552183a)

Any suggestions to resolve this?

### Environment

`eas build --profile production --platform android`

### Expo Doctor Diagnostics

npx expo-doctor:
 Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK
![Captura de tela 2024-07-26 100707](https://github.com/user-attachments/assets/e35a8365-5988-402c-8ef6-70819619e117)

**Comment by brentvatne** [comment]
hi there, you should use **local.properties** for any configuration that is specific to your machine. further, you should ensure that you do not commit **local.properties** to git.

https://stackoverflow.com/a/25318217/659988
