### ISSUE TITLE
[expo-splash-screen] SplashScreen automatically dismissed on Android (only on EAS build)

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#30643]
### Minimal reproducible example

https://github.com/outaTiME/SplashScreenIssue

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

Hello there, 
it seems that `SplashScreen.preventAutoHideAsync()` / `SplashScreen.hideAsync()` are not working correctly.

If I run the following example either from Expo Go or from a custom client in development mode, the `SplashScreen` disappears after 5 seconds (this is the test value set in the `setTimeout`) which is expected.

However, if I create a build with EAS, this `SplashScreen` timeout is not respected on Android and disappears automatically, on iOS, it works perfectly.

```js
import * as SplashScreen from 'expo-splash-screen';
import { StatusBar } from 'expo-status-bar';
import { useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';

const start_time = Date.now();
// Keep the splash screen visible while we fetch resources
SplashScreen.preventAutoHideAsync();

export default function App() {
  useEffect(() => {
    // Wait 5 seconds to remove the splash screen
    new Promise((resolve) => setTimeout(resolve, 5 * 1000)).then(() => {
      console.log(
        `👌 Application loading is completed in ${Date.now() - start_time}ms`,
      );
      SplashScreen.hideAsync();
    });
  }, []);
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

(just in case) I leave the package.json:

```json
{
  "name": "splashscreenissue",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~51.0.22",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.3 - ~/.local/state/fnm_multishells/17490_1721941765854/bin/node
      Yarn: 1.22.22 - ~/.local/state/fnm_multishells/17490_1721941765854/bin/yarn
      npm: 10.8.2 - ~/.local/state/fnm_multishells/17490_1721941765854/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.22 => 51.0.22 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 10.2.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment]
@alanjhughes - i believe that with the new implementation for sdk 52 this won't be an issue, just assigned you here to validate that

**Comment by alanjhughes** [comment]
@brentvatne no this won't happen in sdk 52. It is odd the build with EAS would cause an issue like this 🤔

**Comment by brentvatne** [comment]
hm, i can't repro this on sdk 51. works as expected for me using the example provided above. see this APK @outaTiME: https://www.dropbox.com/scl/fi/sygl5jsmnljuexrlqhh2b/issue-30643.apk?rlkey=ch8txj2lbugrev8z2e0ri2reb&st=hf7lyjik&dl=0

https://github.com/user-attachments/assets/0bd577b3-12f7-4978-8ad1-51e98d21be42

**Comment by outaTiME** [comment]
Hi @brentvatne, the APK you passed me works perfectly. What dependencies did you use to generate yours? 

I generated my APK using the git repository I shared in the issue and using a local build as follows:
`eas build --profile preview --platform android --clear-cache -local`.

This is the result of that build:

https://github.com/user-attachments/assets/ee7c63e3-e136-4d81-9d2d-5408c323b377

**Comment by brentvatne** [comment]
new project created with `npx create-expo-app --template blank@sdk-51`

**package.json**

```
{
  "name": "splash-prevent",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~51.0.24",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

**App.js**
import * as SplashScreen from 'expo-splash-screen';
import { StatusBar } from 'expo-status-bar';
import { useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';

const start_time = Date.now();
// Keep the splash screen visible while we fetch resources

console.log(
  `⏰ Waiting for ${5 * 1000}ms to remove the splash screen...`,
);

SplashScreen.preventAutoHideAsync().catch((err) => {
  console.log(`🥵 Splash screen is prevented from auto-hiding`);
  console.log(err);
});

export default function App() {
  useEffect(() => {
    // Wait 5 seconds to remove the splash screen
    new Promise((resolve) => setTimeout(resolve, 5 * 1000)).then(() => {
      console.log(
        `👌 Application loading is completed in ${Date.now() - start_time}ms`,
      );
      SplashScreen.hideAsync();
    });
  }, []);
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by outaTiME** [comment]
@brentvatne I think I might have detected when the problem occurs.

If I run your APK again (having killed the app) and the app loads instantly ignoring the `SplashScreen.preventAutoHideAsync();`, no matter how much I uninstall it or clean its data it doesn't respect the deferred loading anymore.

I leave a video about it:

https://github.com/user-attachments/assets/7195bc5d-09d4-4931-9c59-8d42e4fe997c

**Comment by brentvatne** [comment]
> @brentvatne I think I might have detected when the problem occurs.
> 
> If I run your APK again (having killed the app) the app loads instantly ignoring the `SplashScreen.preventAutoHideAsync()`, even if I uninstall it or clean its data and restart the phone it doesn't respect the deferred loading anymore.
> 
> I leave a video about it:
> 
>  CleanShot.2024-07-31.at.20.16.38.mp4

i can't reproduce that on my end, closing and reopening works fine

https://github.com/user-attachments/assets/535f1f30-b9ff-44bb-b4c9-a56c1189d875

could there be an issue with your emulator perhaps? could try another emulator or a physical dviece?

**Comment by outaTiME** [comment]
Super weird. 

I tried it on a physical phone, and it works fine. 

But I installed a new image `Google Play ARM 64 v8a System Image` with the Android 33 API (to replicate your emulator) for Android Emulator 34.2.16 from Android Studio 2024.1.1, and I still have the issue, sometimes the loading screen is displayed using the delay, and most of the time it disappears instantly (ignoring the delay).

What is the emulator, and what image do you use for your tests?

**Comment by brentvatne** [comment]
> Super weird.
> 
> I tried it on a physical phone, and it works fine.
> 
> But I installed a new image `Google Play ARM 64 v8a System Image` with the Android 33 API (to replicate your emulator) for Android Emulator 34.2.16 from Android Studio 2024.1.1, and I still have the issue, sometimes the loading screen is displayed using the delay, and most of the time it disappears instantly (ignoring the delay).
> 
> What is the emulator, and what image do you use for your tests?

i've been using a pixel 3a / api 34 image

<img width="932" alt="image" src="https://github.com/user-attachments/assets/e4b89419-6d92-4e8e-95dc-25099c914d8d">

<img width="555" alt="image" src="https://github.com/user-attachments/assets/4db63438-62da-4e33-8026-1942b8204bfd">

**Comment by outaTiME** [comment]
I set up an emulator using your configuration (or similar because I have some newer versions), and I still get the same behavior. 

There are some differences in versions, but I don't think that's the problem. 

I leave some screenshots (in case they are useful):

![CleanShot 2024-07-31 at 21 37 53@2x](https://github.com/user-attachments/assets/372d606c-9206-4787-8080-c9ebee007606)

![CleanShot 2024-07-31 at 21 38 02@2x](https://github.com/user-attachments/assets/f0f032d3-b7c2-45bf-9f2a-c5161ebfc8dc)

**Comment by outaTiME** [comment]
Taking this to another scale, something similar happens to my productive app, there are times when the 5 second delay works (as seen in the third and fourth executions) and others when the `SplashScreen.preventAutoHideAsync()` seems to be ignored.

https://github.com/user-attachments/assets/56c49dfd-a3d8-4c32-b5a3-10b04d6b9266

The app code does not do anything much different than the reduced example I attached in this issue:

https://github.com/outaTiME/ambito-dolar/blob/master/packages/client/App.js#L48

**Comment by brentvatne** [comment]
hey @outaTiME - i'm not really sure what is happening here, i can't reproduce it. @alanjhughes is working on a much improved version of this api, we'll try to get a canary release soon and i will let you know so you can try it out to verify.

**Comment by Hosam-hsm** [comment]
@outaTiME  Were you able to solve this issue?

**Comment by lhr000lhr** [comment]
it's working in debug mode only.

**Comment by dnlsilva** [comment]
I was having the same problem, I tried a few approaches but none of the solutions worked.
I had to migrate to the `react-native-bootsplas` lib.

**Comment by Hosam-hsm** [comment]
I was having this issue when using expo router and was able to solve it by patching the expo-router package.

```
diff --git a/node_modules/expo-router/build/qualified-entry.js b/node_modules/expo-router/build/qualified-entry.js
index 0122839..31d57b9 100644
--- a/node_modules/expo-router/build/qualified-entry.js
+++ b/node_modules/expo-router/build/qualified-entry.js
@@ -14,6 +14,8 @@ const _ctx_1 = require("expo-router/_ctx");
 const react_1 = __importDefault(require("react"));
 const ExpoRoot_1 = require("./ExpoRoot");
 const head_1 = require("./head");
+const Splash_1 = require("./views/Splash");
+Splash_1.SplashScreen.preventAutoHideAsync();
 // Must be exported or Fast Refresh won't update the context
 function App() {
     return (<head_1.Head.Provider>

```
