### ISSUE TITLE
I have the latest updated expo to "^31.0.4", my file looks like below, still broken(slow to load assets)

### ISSUE THREAD

**Issue by OshaFoster** [expo/expo#3064]
I have created pull request to fix this bug. I think it will be released soon in Expo minor release `31.0.3` or later. Until that you can manually apply this fix by changing `/node_modules/expo/build/environment/logging.js`. You should remove slash before "node_modules" string in `console.warn` patch regex

before
<img width="941" alt="screen shot 2018-11-05 at 12 35 58 am" src="https://user-images.githubusercontent.com/14208343/47970823-101dc180-e093-11e8-8561-2555f20ab24e.png">

after
<img width="930" alt="screen shot 2018-11-05 at 12 36 34 am" src="https://user-images.githubusercontent.com/14208343/47970826-1744cf80-e093-11e8-8bb8-c2bb1b171894.png">

_Originally posted by @serhiipalash in https://github.com/expo/expo/issues/2578#issuecomment-435714956_

**Comment by serhiipalash** [comment]
@OshaFoster  clean your npm or yarn cache. The fix is there, you can check it in sources https://github.com/expo/expo/blob/master/packages/expo/src/environment/logging.ts#L25

**Comment by OshaFoster** [comment]
Thanks for your swift reply, I do see the fix in my code. I have cleared my cache, it is still slow to load.

**Comment by serhiipalash** [comment]
> it is still slow to load.

then you have another reason why this bug happens

Check all your warning logs, some of them should differ from "Require cycle...". 

We used a library with deprecated default import from `expo` and saw warnings "The syntax is deprecated...". These logs slow down assets too.

**Comment by OshaFoster** [comment]
Thanks, realized my require cycle warning was different, changed regex to this:

        /^Require cycle: .*/

That worked for now, working on correcting the issue.

**Comment by esamelson** [comment]
I believe this has been fixed so going to go ahead and close this. If not, please open a new issue and fill out the template fully. Thanks!
