### ISSUE TITLE
expo publish

### ISSUE THREAD

**Issue by NameNull** [expo/expo#3067]
![image](https://user-images.githubusercontent.com/11754843/50417819-53123f00-0863-11e9-9929-8ada53496600.png)
Amazon CloudFront is not suitable for us chinese sometimes, can i upload these assets to my CDN? if yes, how can i configure that?

**Comment by ardyfeb** [comment]
If you build standalone app, assets will bundled on app binary

**Comment by brentvatne** [comment]
indeed https://docs.expo.io/versions/v31.0.0/workflow/configuration#assetbundlepatterns lets you specify what to bundle in the binary

**Comment by brentvatne** [comment]
also you can use `expo export` to upload them to wherever you like https://docs.expo.io/versions/v31.0.0/distribution/hosting-your-app
