### ISSUE TITLE
[expo-font] Using a font via appconfig (app.json, app.config.ts) doesn't work

### ISSUE THREAD

**Issue by AlexanderHott** [expo/expo#30672]
### Minimal reproducible example

https://github.com/AlexanderHOtt/expo-font-appconfig

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

When using "expo-font" to include in the `plugins` section of `app.json`, the font isn't made available in the app.

```
 WARN  fontFamily "GeistMono-Medium" is not a system font and has not been loaded through expo-font. 
```

When including the font via `useFonts`, it does work.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 21.4.0 - /run/user/1000/fnm_multishells/4566_1722199331075/bin/node
      Yarn: 1.22.22 - ~/.local/share/pnpm/yarn
      npm: 10.2.5 - /run/user/1000/fnm_multishells/4566_1722199331075/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 26, 30, 33, 34
        Build Tools: 26.0.3, 30.0.3, 33.0.1, 34.0.0, 35.0.0
        System Images: android-26 | Google APIs Intel x86_64 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    npmPackages:
      expo: ~51.0.22 => 51.0.22 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema

Didn't find any issues with the project!

**Comment by alanjhughes** [comment]
Hi @AlexanderHott - I just pulled your repro and don't see any issue
![Simulator Screenshot - iPhone 15 Pro - 2024-07-29 at 09 46 31](https://github.com/user-attachments/assets/f0604427-e660-4b96-8a2e-e05a995ddfa9)
If you are trying to do this in expo go, it's not possible, expo go is prebuilt so config plugins cannot change it

**Comment by AlexanderHott** [comment]
> If you are trying to do this in expo go, it's not possible, expo go is prebuilt so config plugins cannot change it

That is true. I was using a development client for my project where this popped up. I think it could have been an issue of my prebuild step not working because when I ran `pnpx expo prebuild`, I got issues about font assets not existing (from testing). I will confirm next time I rebuild my dev client.
