### ISSUE TITLE
CameraView no ratio Expo SDK 51

### ISSUE THREAD

**Issue by DanTol-cloud** [expo/expo#30684]
### Minimal reproducible example

https://github.com/DudeFactory/expo-sdk51-camera

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Until the last update, we used the Ratio attribute to establish the aspect ratios of the camera. After the new version was released, this attribute disappeared and our cameras, in which we scan the cuar code, began to get outside the modal window, an example of the code is available from the link to the repotizory

export default function App() {
  const [showModal, setShowModal] = useState(false);
  const [permission, requestPermission] = useCameraPermissions();

  if (!permission) {
    return <View />;
  }

  return (
    <SafeAreaProvider>
      <NativeBaseProvider>
        <SafeAreaView style={{ flex: 1 }}>
          <Box
            style={{
              flex: 1,
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Heading color={'white'}>Hello</Heading>

            <HStack
              space="4"
              justifyContent="center"
              alignItems="center"
            >
              <Button
                onPress={() => {
                  setShowModal(true);
                }}
              >
                Open Modal
              </Button>
            </HStack>
          </Box>
          <ModalMy
            setShowModal={setShowModal}
            showModal={showModal}
          >
            <CameraView
              facing="back"
              barcodeScannerSettings={{
                barcodeTypes: ['qr'],
              }}
              style={{
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
              }}
            ></CameraView>
          </ModalMy>
        </SafeAreaView>
      </NativeBaseProvider>
    </SafeAreaProvider>
  );
}

const ModalMy = ({ children, showModal, setShowModal }) => {
  return (
    <Modal
      p={5}
      isOpen={showModal}
      onClose={setShowModal}
      size={'full'}
    >
      <Modal.Content>
        <Modal.CloseButton onPress={() => setShowModal(false)} />
        <Modal.Header>Test Modal</Modal.Header>
        <Modal.Body height={'xs'}>{children}</Modal.Body>
      </Modal.Content>
    </Modal>
  );
};

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.7.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /Users/daniiltolmachov/.gem/ruby/2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: 51.0.2 => 51.0.2 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ^0.19.10 => 0.19.10 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

(node:11989) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.2 - expected version: ~51.0.22
  expo-asset@10.0.6 - expected version: ~10.0.10
  expo-av@14.0.5 - expected version: ~14.0.6
  expo-camera@15.0.10 - expected version: ~15.0.14
  expo-dev-client@4.0.15 - expected version: ~4.0.20
  expo-notifications@0.28.6 - expected version: ~0.28.12
  expo-splash-screen@0.27.4 - expected version: ~0.27.5
  expo-updates@0.25.15 - expected version: ~0.25.21
  react-native@0.74.1 - expected version: 0.74.3
  react-native-safe-area-context@4.10.1 - expected version: 4.10.5
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

**Comment by alanjhughes** [comment]
This has already been implemented in #29822.

**Comment by DanTol-cloud** [comment]
@alanjhughes our problem is that camera ratio dependes on screen size not on modal size and that`s why camera gets out of modal window

**Comment by brentvatne** [comment]
support for the `ratio` prop was merged to main, it'll ship in sdk 52! you can manually apply it to your project using [`patch-package`](https://expo.fyi/eas-patch-package) if you like. otherwise, you can use the legacy camera implementation still until then

**Comment by DanTol-cloud** [comment]
@brentvatne i did patch for expo-camera but it did not work. here is the commit where you can see patch, can you check is everything is ok. And maybe you know why it is not work [commit](https://github.com/DudeFactory/expo-sdk51-camera/pull/2)

**Comment by landabaso** [comment]
> @brentvatne i did patch for expo-camera but it did not work. here is the commit where you can see patch, can you check is everything is ok. And maybe you know why it is not work [commit](https://github.com/DudeFactory/expo-sdk51-camera/pull/2)

Hay @DanTol-cloud did you manage to make the patch work? I am having exactly the same problem using a Camara within a Modal...
