### ISSUE TITLE
ignore Component folder

### ISSUE THREAD

**Issue by xtayaitak** [expo/expo#30680]
### Minimal reproducible example

npx create-expo-app@latest

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I have a component folder for some ui control.but tab control treat it as router.
I serach official document and not find a answer.
![15a884f3100d2420efb6cdc70295588](https://github.com/user-attachments/assets/66fe081f-3e48-4a9d-8ce2-b9a5e45f8058)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838  
    npmPackages:
      expo: ~51.0.22 => 51.0.22
      expo-router: ~3.5.18 => 3.5.18
      react: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
    Expo Workflow: managed

**Comment by itaalobraga** [comment]
Today it is not possible to do this, you will have to move all your components out of the “app” folder, otherwise they will continue to be considered as routes

**Comment by marklawlor** [comment]
This is not supported, please move your components into a folder outside the `app` directory
