### ISSUE TITLE
Sentry.init is undefined

### ISSUE THREAD

**Issue by Morriz** [expo/expo#3068]
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - ~/.nvm/versions/node/v11.2.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v11.2.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.2.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.6 => 31.0.6
      react: ^16.5.0 => 16.6.3
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.8 => 3.0.8
    npmGlobalPackages:
      expo-cli: 2.6.14
   
### Steps to Reproduce

Immediately in my App.js I bootstrap Sentry with
```
Sentry.config({...}).install()
Sentry.init({
    beforeSend(event) {
        ...
    }
})
```
And when running the app it errs with
```
undefined is not a function (near '..._sentryExpo.default.init...')
```

### Expected Behavior

Sentry.init to be available. 

But writing this I guess that is done behind the scenes with the app.json declarative part for Sentry.

### Actual Behavior

Sentry.init is not available.

**Comment by Morriz** [comment]
So my need is to intercept and strip sensitive information client side. Is that functionality somehow exposed now that init is not available? Sentry's docs all point to the init hooks.

**Comment by brentvatne** [comment]
here is the source code: https://github.com/expo/sentry-expo/blob/master/index.js - we just re-export the Sentry object. It should be available, perhaps your import is incorrect? I don't know because you didn't post the code

**Comment by Morriz** [comment]
Thanks, again a case of me lacking investigation more thorough.
