### ISSUE TITLE
[expo-video] statusChange behaves differently on iOS <--> Android

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#30683]
### Minimal reproducible example

https://github.com/RRaideRR/expo-video-player-status

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I'm trying to work around #30275 and to mount the video in my project only if its fully visible.

I noticed, that on iOS, `statusChange='readyToPlay'` occurs even if the video view is not mounted whereas on Android, the event only occurs after the video view is mounted.

Follow up question: Does this mean that on Android, the video is buffered only when its mounted vs iOS where it starts buffering even though its not mounted?

iOS:

https://github.com/user-attachments/assets/dfab2d8a-a67b-46dd-9b80-544ca040137d

Android:
 

https://github.com/user-attachments/assets/319a473e-cf78-46b5-abbc-907ae081567b

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.04.29.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/opt/ruby/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.22 => 51.0.22 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 10.2.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by behenate** [comment]
@RRaideRR  Hi, this should be fixed in https://github.com/expo/expo/pull/30626. Right now your theory is correct - android wasn't buffering the video when unmounted. When this PR is merged (it might take some time as we will have to make some changes to `expo-modules-core` as there are some limitations that make the API worse) the videos will buffer even when the player is unmounted.
