### ISSUE TITLE
Does this not support low version xcode?  The minimum required version for Xcode is 14?

### ISSUE THREAD

**Issue by IOLOII** [expo/expo#30704]
### Summary

I had tried cli version above @3.* @next @2.* @2.1.1 @1.* , but no one support my machine which mbp with m1 pro but macos is Monterey

<img width="542" alt="image" src="https://github.com/user-attachments/assets/5afe723a-05b3-4cf0-ab9e-248816f871a5">

No unexpected incidents, all require me to install the latest Xcode

Hope to support apple silicon serise machine but not only lastest software or hardware!

It's not necessarily the latest version that's the best. Isn't it possible to develop on a stable system?

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.7
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 26, 28, 30, 32
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 32.0.0
        System Images: android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.23 => 51.0.23 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    Expo Workflow: managed

### Minimal reproducible example

npx create-expo-app@next

**Comment by alanjhughes** [comment]
Hi @IOLOII - this is not a restriction imposed by us. You can see [here](https://developer.apple.com/news/upcoming-requirements/?id=04292024a#:~:text=Apps%20uploaded%20to%20App%20Store,10%20starting%20April%2029%2C%202024.). Apple will no longer accept apps built on Xcode 14 or lower

**Comment by IOLOII** [comment]
Oops , OK !

> Hi @IOLOII - this is not a restriction imposed by us. You can see [here](https://developer.apple.com/news/upcoming-requirements/?id=04292024a#:~:text=Apps%20uploaded%20to%20App%20Store,10%20starting%20April%2029%2C%202024.). Apple will no longer accept apps built on Xcode 14 or lower

**Comment by IOLOII** [comment]
Hi @alanjhughes ！
Today, during the break, I suddenly wanted to ask again. In my experience, I think different versions of Xcode have different expos. Don’t we have a specific version in this project, or an old branch node that can provide support for the old system? Because I almost tried, the latest small version of cli: 1.x, 2.x, 3.x.)

Because as a Swift developer, in fact, I may not have the ability to publish apps (because it takes money to buy Apple‘s developer program), and I just want to learn about this framework. If our project only supports the development of the latest version, I think it’s a pity ( Based on the need to update the system and equipment). And Apple‘s regulation was stipulated in 2024, so there should be a corresponding version before 2024, and it can be used normally for old Xcode, right?
