### ISSUE TITLE
New images are missing in Expo build

### ISSUE THREAD

**Issue by DianaMakarevich** [expo/expo#3070]
# New images are missing in expo build

Hello! I'm developing react native application with expo and I have very strange bug. When I add new images, they are showing in my simulator and real device when I open it local, but when I'm publish project in expo.io, and after that when I open it in expo, new images are missing. But old images are showing! I use Image and Animation.Image from react-native. When I add new svg images in SvgUri component, it's reproduce too..

example of my code:

it's worked:
`<Animated.Image       
        style={{
          opacity: logoAnim,
          width: logoWidth,
          height: logoHeight
        }}
        source={require('../../../assets/oldImage.png')}
        key='oldImage'
        showWebviewLoader={false}
      />
      </View>`

example of my code:

it's dont work:
`<Animated.Image       
        style={{
          opacity: logoAnim,
          width: logoWidth,
          height: logoHeight
        }}
        source={require('../../../assets/newImage.png')}
        key='newImage'
        showWebviewLoader={false}
      />
      </View>`

Please, help me
Thanks a lot

**Comment by DianaMakarevich** [comment]
my app.json

```
{
  "expo": {
    "name": "app",
    "slug": "app",
    "privacy": "public",
    "sdkVersion": "31.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "ios": {
      "supportsTablet": true
    },
    "description": ""
  }
}
```

**Comment by ardyfeb** [comment]
If you want to add new asset, you must rebuild app binary. Read https://docs.expo.io/versions/latest/guides/publishing.html#limitations

**Comment by spyshower** [comment]
You need to use `expo build:android` not `expo publish` in that case.
