### ISSUE TITLE
 ERROR  Error: Cannot find native module 'ExpoAsset', js engine: hermes 

### ISSUE THREAD

**Issue by RushitaRn25** [expo/expo#30715]
### Summary

 ERROR  Error: Cannot find native module 'ExpoAsset', js engine: hermes 
![Screenshot_1722227775](https://github.com/user-attachments/assets/2c2229c5-bb91-40e2-a343-7eca397e08e6)

### Environment

react-native-cli

### Minimal reproducible example

getting this error while using audio from expo-av

**Comment by brentvatne** [comment]
hello! this may occur if you haven't installed expo modules in your project correctly: https://docs.expo.dev/bare/installing-expo-modules/
