### ISSUE TITLE
Android Build Error with `npx expo prebuild --clean`

### ISSUE THREAD

**Issue by bahadiraraz** [expo/expo#30725]
#### Description
I am experiencing an error when running `npx expo prebuild --clean` for my Android project. After initiating this command, my build process fails, and I receive the following error:

```
> Task :app:processDebugMainManifest FAILED
[androidx.versionedparcelable:versionedparcelable:1.1.1] /Users/bahadir/.gradle/caches/transforms-4/2ce0032ccb31eebf8bef327c4969c555/transformed/versionedparcelable-1.1.1/AndroidManifest.xml Warning:
        Namespace 'androidx.versionedparcelable' is used in multiple modules and/or libraries: androidx.versionedparcelable:versionedparcelable:1.1.1, com.android.support:versionedparcelable:28.0.0. Please ensure that all modules and libraries have a unique namespace. For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace
/Users/bahadir/Desktop/last-main/learnity-mobil/android/app/src/debug/AndroidManifest.xml:28:18-86 Error:
        Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.12.0] AndroidManifest.xml:28:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-162 to override.

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs
```

I have not changed anything in my project, and this issue started occurring suddenly. It might be related to the latest update.

#### Steps to Reproduce
1. Run `npx expo prebuild --clean`.
2. Attempt to build the Android project.

#### Additional Context
To resolve some issues, I added the following lines to the `gradle.properties` file:

```properties
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Enable AAPT2 PNG crunching
android.enablePngCrunchInReleaseBuilds=true
```

Despite this, the build process still crashes with the above error. It seems there is a conflict between `androidx.versionedparcelable:versionedparcelable:1.1.1` and `com.android.support:versionedparcelable:28.0.0`.

#### Suggested Solution
Keep `android.enableJetifier=true`.

#### Environment
- Expo CLI: 0.18.26
- Node: v20.11.1
- Operating System: Mac OS 14.3.1

Please provide guidance on resolving this issue. Thank you for your assistance.
What platform(s) does this occur on?
Android

SDK Version
51.0.21

Environment
```
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.1 => 0.18.4 
      expo: ~51.0.21 => 51.0.23 
      expo-router: ~3.5.18 => 3.5.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.1
    Expo Workflow: bare

**Comment by bahadiraraz** [comment]
@brentvatne

**Comment by brentvatne** [comment]
@bahadiraraz - how do I reproduce this on a new project?

**Comment by brentvatne** [comment]
also:

> To resolve some issues, I added the following lines to the gradle.properties file

can you elaborate on which issues?

**Comment by brentvatne** [comment]
good catch re: jetifier config, sorry that was clobbered in a merge. i've republished the template with the config added back

**Comment by bahadiraraz** [comment]
> good catch re: jetifier config, sorry that was clobbered in a merge. i've republished the template with the config added back

While developing for Android, I immediately noticed the issue. Thank you for your quick response! 😊

**Comment by brentvatne** [comment]
> despite this, the build process still crashes with the above error. It seems there is a conflict between androidx.versionedparcelable:versionedparcelable:1.1.1 and com.android.support:versionedparcelable:28.0.0.

i'm not sure that any changes here are related, could this be specific to your project?

**Comment by bahadiraraz** [comment]
> > despite this, the build process still crashes with the above error. It seems there is a conflict between androidx.versionedparcelable:versionedparcelable:1.1.1 and com.android.support:versionedparcelable:28.0.0.
> 
> i'm not sure that any changes here are related, could this be specific to your project?

I was certain that the issue was due to these two lines conflict:

```
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Enable AAPT2 PNG crunching
android.enablePngCrunchInReleaseBuilds=true
```

However, I also considered that it could be caused by the other option, so I wanted to mention both.

**Comment by jamsch** [comment]
In the meantime, pinning to 51.0.23 works okay

**Comment by brentvatne** [comment]
@bahadiraraz - to clarify, when you enabled those options that error went away?

**Comment by brentvatne** [comment]
> In the meantime, pinning to 51.0.23 works okay

can you elaborate on what error you are seeing specifically?

**Comment by bahadiraraz** [comment]
> @bahadiraraz - to clarify, when you enabled those options that error went away?

yes

**Comment by jamsch** [comment]
> > In the meantime, pinning to 51.0.23 works okay
> 
> can you elaborate on what error you are seeing specifically?

These are the last lines of the build log, it's likely related to Jetifier.

<details>
 <summary>Run gradlew</summary>
 ```
> Task :app:processDebugMainManifest FAILED
[androidx.versionedparcelable:versionedparcelable:1.1.1] /home/expo/.gradle/caches/transforms-4/2ceb62a08e9445ddf1a7687689a58767/transformed/versionedparcelable-1.1.1/AndroidManifest.xml Warning:
	Namespace 'androidx.versionedparcelable' is used in multiple modules and/or libraries: androidx.versionedparcelable:versionedparcelable:1.1.1, com.android.support:versionedparcelable:28.0.0. Please ensure that all modules and libraries have a unique namespace. For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace
See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.
/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml:28:18-86 Error:
	Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.12.0] AndroidManifest.xml:28:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-162 to override.
> Task :expo-modules-core:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :react-native-masked-view_masked-view:compileDebugJavaWithJavac
> Task :react-native-gesture-handler:compileDebugKotlin
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/RNGestureHandlerPackage.kt:69:42 'constructor ReactModuleInfo(String!, String!, Boolean, Boolean, Boolean, Boolean, Boolean)' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/FlingGestureHandler.kt:25:26 Parameter 'event' is never used
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 4m 34s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
507 actionable tasks: 507 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```
</details>

**Comment by jamsch** [comment]
Could be this commit last week:  https://github.com/expo/expo/commit/3774717917aeb37e66bc53902abd73fefaa867a7#diff-c1abe9eea32a8e683dbea2f18a322cc0b8c5a4ce1a8da1719c6a9ddf29f79e3fL28

**Comment by brentvatne** [comment]
@jamsch - can you try running `npx expo prebuild --clean` again with the latest expo package version? this should be resolved now, as i mentioned above.

**Comment by jamsch** [comment]
@brentvatne Yep, seems to work okay on a local dev build. Thank you for the prompt fix!

**Comment by brentvatne** [comment]
do either of you happen to know how to repro the issue? it sounds like removing `android.enableJetifier=true` is one step, but what other libraries do i need in my project to reproduce? it'd be great if one of you were able to narrow this down so we can understand how widespread this problem would potentially be if we follow along with https://github.com/facebook/react-native/pull/44876

**Comment by jamsch** [comment]
@brentvatne I'll investigate this soon!

**Comment by jamsch** [comment]
@brentvatne 
For our app, it seems to be caused by a third party dep, `react-native-iap@12.15.1`

```
+--- project :react-native-iap
|    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.74.3 (*)
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.9.23 (*)
|    +--- com.android.support:support-annotations:28.0.0
|    +--- com.android.support:customtabs:28.0.0
|    |    +--- com.android.support:support-compat:28.0.0
|    |    |    +--- com.android.support:support-annotations:28.0.0
|    |    |    +--- com.android.support:collections:28.0.0
|    |    |    |    \--- com.android.support:support-annotations:28.0.0
|    |    |    +--- android.arch.lifecycle:runtime:1.1.1
|    |    |    |    +--- android.arch.lifecycle:common:1.1.1
|    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    |    +--- android.arch.core:common:1.1.1
|    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    |    \--- com.android.support:versionedparcelable:28.0.0
|    |    |         +--- com.android.support:support-annotations:28.0.0
|    |    |         \--- com.android.support:collections:28.0.0 (*)
|    |    +--- com.android.support:support-annotations:28.0.0
|    |    +--- com.android.support:interpolator:28.0.0
|    |    |    \--- com.android.support:support-annotations:28.0.0
|    |    +--- com.android.support:collections:28.0.0 (*)
|    |    \--- com.android.support:support-core-ui:28.0.0
|    |         +--- com.android.support:support-annotations:28.0.0
|    |         +--- com.android.support:support-compat:28.0.0 (*)
|    |         +--- com.android.support:support-core-utils:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    +--- com.android.support:support-compat:28.0.0 (*)
|    |         |    +--- com.android.support:documentfile:28.0.0
|    |         |    |    \--- com.android.support:support-annotations:28.0.0
|    |         |    +--- com.android.support:loader:28.0.0
|    |         |    |    +--- com.android.support:support-annotations:28.0.0
|    |         |    |    +--- com.android.support:support-compat:28.0.0 (*)
|    |         |    |    +--- android.arch.lifecycle:livedata:1.1.1
|    |         |    |    |    +--- android.arch.core:runtime:1.1.1
|    |         |    |    |    |    +--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |         |    |    |    |    \--- android.arch.core:common:1.1.1 (*)
|    |         |    |    |    +--- android.arch.lifecycle:livedata-core:1.1.1
|    |         |    |    |    |    +--- android.arch.lifecycle:common:1.1.1 (*)
|    |         |    |    |    |    +--- android.arch.core:common:1.1.1 (*)
|    |         |    |    |    |    \--- android.arch.core:runtime:1.1.1 (*)
|    |         |    |    |    \--- android.arch.core:common:1.1.1 (*)
|    |         |    |    \--- android.arch.lifecycle:viewmodel:1.1.1
|    |         |    |         \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |         |    +--- com.android.support:localbroadcastmanager:28.0.0
|    |         |    |    \--- com.android.support:support-annotations:28.0.0
|    |         |    \--- com.android.support:print:28.0.0
|    |         |         \--- com.android.support:support-annotations:28.0.0
|    |         +--- com.android.support:customview:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    \--- com.android.support:support-compat:28.0.0 (*)
|    |         +--- com.android.support:viewpager:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    +--- com.android.support:support-compat:28.0.0 (*)
|    |         |    \--- com.android.support:customview:28.0.0 (*)
|    |         +--- com.android.support:coordinatorlayout:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    +--- com.android.support:support-compat:28.0.0 (*)
|    |         |    \--- com.android.support:customview:28.0.0 (*)
|    |         +--- com.android.support:drawerlayout:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    +--- com.android.support:support-compat:28.0.0 (*)
|    |         |    \--- com.android.support:customview:28.0.0 (*)
|    |         +--- com.android.support:slidingpanelayout:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    +--- com.android.support:support-compat:28.0.0 (*)
|    |         |    \--- com.android.support:customview:28.0.0 (*)
|    |         +--- com.android.support:interpolator:28.0.0 (*)
|    |         +--- com.android.support:swiperefreshlayout:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    +--- com.android.support:support-compat:28.0.0 (*)
|    |         |    \--- com.android.support:interpolator:28.0.0 (*)
|    |         +--- com.android.support:asynclayoutinflater:28.0.0
|    |         |    +--- com.android.support:support-annotations:28.0.0
|    |         |    \--- com.android.support:support-compat:28.0.0 (*)
|    |         \--- com.android.support:cursoradapter:28.0.0
|    |              \--- com.android.support:support-annotations:28.0.0
|    +--- com.android.billingclient:billing-ktx:7.0.0
|    |    +--- com.android.billingclient:billing:7.0.0
|    |    |    +--- androidx.activity:activity:1.2.3 -> 1.7.2 (*)
|    |    |    +--- com.google.android.datatransport:transport-api:3.0.0 -> 3.1.0 (*)
|    |    |    +--- com.google.android.datatransport:transport-backend-cct:3.1.8 -> 3.1.9 (*)
|    |    |    +--- com.google.android.datatransport:transport-runtime:3.1.8 -> 3.1.9 (*)
|    |    |    +--- com.google.android.gms:play-services-base:18.3.0 (*)
|    |    |    +--- com.google.android.gms:play-services-basement:18.3.0 -> 18.4.0 (*)
|    |    |    +--- com.google.android.gms:play-services-location:19.0.0
|    |    |    |    +--- com.google.android.gms:play-services-base:18.0.0 -> 18.3.0 (*)
|    |    |    |    +--- com.google.android.gms:play-services-basement:18.0.0 -> 18.4.0 (*)
|    |    |    |    +--- com.google.android.gms:play-services-places-placereport:17.0.0
|    |    |    |    |    \--- com.google.android.gms:play-services-basement:17.0.0 -> 18.4.0 (*)
|    |    |    |    \--- com.google.android.gms:play-services-tasks:18.0.0 -> 18.2.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:18.1.0 -> 18.2.0 (*)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 -> 1.9.23 (*)
|    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0 -> 1.7.1 (*)
|    \--- com.google.android.gms:play-services-base:18.1.0 -> 18.3.0 (*)
```

**Comment by bahadiraraz** [comment]
> @brentvatne For our app, it seems to be caused by a third party dep, `react-native-iap@12.15.1`
> 
> ```
> +--- project :react-native-iap
> |    +--- com.facebook.react:react-native:+ -> com.facebook.react:react-android:0.74.3 (*)
> |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.9.23 (*)
> |    +--- com.android.support:support-annotations:28.0.0
> |    +--- com.android.support:customtabs:28.0.0
> |    |    +--- com.android.support:support-compat:28.0.0
> |    |    |    +--- com.android.support:support-annotations:28.0.0
> |    |    |    +--- com.android.support:collections:28.0.0
> |    |    |    |    \--- com.android.support:support-annotations:28.0.0
> |    |    |    +--- android.arch.lifecycle:runtime:1.1.1
> |    |    |    |    +--- android.arch.lifecycle:common:1.1.1
> |    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
> |    |    |    |    +--- android.arch.core:common:1.1.1
> |    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
> |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
> |    |    |    \--- com.android.support:versionedparcelable:28.0.0
> |    |    |         +--- com.android.support:support-annotations:28.0.0
> |    |    |         \--- com.android.support:collections:28.0.0 (*)
> |    |    +--- com.android.support:support-annotations:28.0.0
> |    |    +--- com.android.support:interpolator:28.0.0
> |    |    |    \--- com.android.support:support-annotations:28.0.0
> |    |    +--- com.android.support:collections:28.0.0 (*)
> |    |    \--- com.android.support:support-core-ui:28.0.0
> |    |         +--- com.android.support:support-annotations:28.0.0
> |    |         +--- com.android.support:support-compat:28.0.0 (*)
> |    |         +--- com.android.support:support-core-utils:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    +--- com.android.support:support-compat:28.0.0 (*)
> |    |         |    +--- com.android.support:documentfile:28.0.0
> |    |         |    |    \--- com.android.support:support-annotations:28.0.0
> |    |         |    +--- com.android.support:loader:28.0.0
> |    |         |    |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    |    +--- com.android.support:support-compat:28.0.0 (*)
> |    |         |    |    +--- android.arch.lifecycle:livedata:1.1.1
> |    |         |    |    |    +--- android.arch.core:runtime:1.1.1
> |    |         |    |    |    |    +--- com.android.support:support-annotations:26.1.0 -> 28.0.0
> |    |         |    |    |    |    \--- android.arch.core:common:1.1.1 (*)
> |    |         |    |    |    +--- android.arch.lifecycle:livedata-core:1.1.1
> |    |         |    |    |    |    +--- android.arch.lifecycle:common:1.1.1 (*)
> |    |         |    |    |    |    +--- android.arch.core:common:1.1.1 (*)
> |    |         |    |    |    |    \--- android.arch.core:runtime:1.1.1 (*)
> |    |         |    |    |    \--- android.arch.core:common:1.1.1 (*)
> |    |         |    |    \--- android.arch.lifecycle:viewmodel:1.1.1
> |    |         |    |         \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
> |    |         |    +--- com.android.support:localbroadcastmanager:28.0.0
> |    |         |    |    \--- com.android.support:support-annotations:28.0.0
> |    |         |    \--- com.android.support:print:28.0.0
> |    |         |         \--- com.android.support:support-annotations:28.0.0
> |    |         +--- com.android.support:customview:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    \--- com.android.support:support-compat:28.0.0 (*)
> |    |         +--- com.android.support:viewpager:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    +--- com.android.support:support-compat:28.0.0 (*)
> |    |         |    \--- com.android.support:customview:28.0.0 (*)
> |    |         +--- com.android.support:coordinatorlayout:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    +--- com.android.support:support-compat:28.0.0 (*)
> |    |         |    \--- com.android.support:customview:28.0.0 (*)
> |    |         +--- com.android.support:drawerlayout:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    +--- com.android.support:support-compat:28.0.0 (*)
> |    |         |    \--- com.android.support:customview:28.0.0 (*)
> |    |         +--- com.android.support:slidingpanelayout:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    +--- com.android.support:support-compat:28.0.0 (*)
> |    |         |    \--- com.android.support:customview:28.0.0 (*)
> |    |         +--- com.android.support:interpolator:28.0.0 (*)
> |    |         +--- com.android.support:swiperefreshlayout:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    +--- com.android.support:support-compat:28.0.0 (*)
> |    |         |    \--- com.android.support:interpolator:28.0.0 (*)
> |    |         +--- com.android.support:asynclayoutinflater:28.0.0
> |    |         |    +--- com.android.support:support-annotations:28.0.0
> |    |         |    \--- com.android.support:support-compat:28.0.0 (*)
> |    |         \--- com.android.support:cursoradapter:28.0.0
> |    |              \--- com.android.support:support-annotations:28.0.0
> |    +--- com.android.billingclient:billing-ktx:7.0.0
> |    |    +--- com.android.billingclient:billing:7.0.0
> |    |    |    +--- androidx.activity:activity:1.2.3 -> 1.7.2 (*)
> |    |    |    +--- com.google.android.datatransport:transport-api:3.0.0 -> 3.1.0 (*)
> |    |    |    +--- com.google.android.datatransport:transport-backend-cct:3.1.8 -> 3.1.9 (*)
> |    |    |    +--- com.google.android.datatransport:transport-runtime:3.1.8 -> 3.1.9 (*)
> |    |    |    +--- com.google.android.gms:play-services-base:18.3.0 (*)
> |    |    |    +--- com.google.android.gms:play-services-basement:18.3.0 -> 18.4.0 (*)
> |    |    |    +--- com.google.android.gms:play-services-location:19.0.0
> |    |    |    |    +--- com.google.android.gms:play-services-base:18.0.0 -> 18.3.0 (*)
> |    |    |    |    +--- com.google.android.gms:play-services-basement:18.0.0 -> 18.4.0 (*)
> |    |    |    |    +--- com.google.android.gms:play-services-places-placereport:17.0.0
> |    |    |    |    |    \--- com.google.android.gms:play-services-basement:17.0.0 -> 18.4.0 (*)
> |    |    |    |    \--- com.google.android.gms:play-services-tasks:18.0.0 -> 18.2.0 (*)
> |    |    |    \--- com.google.android.gms:play-services-tasks:18.1.0 -> 18.2.0 (*)
> |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 -> 1.9.23 (*)
> |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0 -> 1.7.1 (*)
> |    \--- com.google.android.gms:play-services-base:18.1.0 -> 18.3.0 (*)
> ```

our app also use `"react-native-iap": "^12.13.1"`

**Comment by AdamGerthel** [comment]
I have the same error, I think:

> > Task :app:processDebugMainManifest FAILED
[androidx.versionedparcelable:versionedparcelable:1.1.1] /Users/insats/.gradle/caches/8.10.2/transforms/1dd4f6c36908fa26a3f50965bb37350f/transformed/versionedparcelable-1.1.1/AndroidManifest.xml Warning:
        Namespace 'androidx.versionedparcelable' is used in multiple modules and/or libraries: androidx.versionedparcelable:versionedparcelable:1.1.1, com.android.support:versionedparcelable:28.0.0. Please ensure that all modules and libraries have a unique namespace. For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace
<redacted>/android/app/src/debug/AndroidManifest.xml:28:18-86 Error:
        Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.13.1] AndroidManifest.xml:28:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-162 to override.

I'm also using react-native-iap, but I'm already on the latest version, `12.15.7`. Not sure how to move forward...

**Comment by bahadiraraz** [comment]
> I have the same error, I think:
> 
> > Task :app:processDebugMainManifest FAILED
> > [androidx.versionedparcelable:versionedparcelable:1.1.1] /Users/insats/.gradle/caches/8.10.2/transforms/1dd4f6c36908fa26a3f50965bb37350f/transformed/versionedparcelable-1.1.1/AndroidManifest.xml Warning:
> > Namespace 'androidx.versionedparcelable' is used in multiple modules and/or libraries: androidx.versionedparcelable:versionedparcelable:1.1.1, com.android.support:versionedparcelable:28.0.0. Please ensure that all modules and libraries have a unique namespace. For more information, See https://developer.android.com/studio/build/configure-app-module#set-namespace
> > /android/app/src/debug/AndroidManifest.xml:28:18-86 Error:
> > Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.13.1] AndroidManifest.xml:28:18-86
> > is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
> > Suggestion: add 'tools:replace="android:appComponentFactory"' to  element at AndroidManifest.xml:6:5-162 to override.
> 
> I'm also using react-native-iap, but I'm already on the latest version, `12.15.7`. Removing that package resolves the issue, but I depend on it.
> 
> @jamsch and @bahadiraraz was it resolved for you by upgrading react-native-iap?


In React Native 0.76, `android.enableJetifier=false` is the default setting, which can lead to issues with libraries like `react-native-iap`. To resolve this, you can use a `postinstall` script to enable Jetifier manually, as shown below:

Add the following script in your `scripts` section of `package.json`:

```json
"scripts": {
  "postinstall": "node ./scripts/postinstall.js"
}
```

And create a `scripts/postinstall.js` file with this content:

```javascript
const fs = require('fs');
const path = require('path');

// Path to the gradle.properties file
const gradlePropertiesPath = path.join(__dirname, '..', 'android', 'gradle.properties');

// Check if the gradle.properties file exists and add the Jetifier setting if needed
if (fs.existsSync(gradlePropertiesPath)) {
  const gradleContent = fs.readFileSync(gradlePropertiesPath, 'utf8');
  if (!gradleContent.includes('android.enableJetifier=true')) {
    fs.appendFileSync(gradlePropertiesPath, '\nandroid.enableJetifier=true\n', 'utf8');
    console.log('android.enableJetifier=true added to gradle.properties');
  } else {
    console.log('android.enableJetifier=true already exists in gradle.properties');
  }
} else {
  console.log('gradle.properties not found. Skipping Jetifier configuration.');
}
```

This fixed the issue for me when using `react-native-iap`.

**Comment by AdamGerthel** [comment]
@bahadiraraz does this work for EAS builds as well?

**Comment by bahadiraraz** [comment]
> @bahadiraraz does this work for EAS builds as well?

To make the `postinstall.js` script work with EAS builds, you can add the following to your `package.json` under the `"scripts"` section:

```json
"eas-build-post-install": "node ./scripts/postinstall.js"
```

This ensures that the script runs during the EAS build process and resolves the issue there as well.

**Comment by watadarkstar** [comment]
I was able to get this with a gradle plugin I wrote:

withGradleProperties.js

```
const { withGradleProperties } = require("@expo/config-plugins")

function withCustomGradleProperties(config) {
  return withGradleProperties(config, function (config) {
    /* Added gradle properties like this
      { type: 'property', key: 'key', value: 'value' } */
    const additionalGraddleProperties = [
      // SDK 52: https://github.com/expo/expo/issues/30725
      { type: "property", key: "android.enableJetifier", value: "true" },
      {
        type: "property",
        key: "android.enablePngCrunchInReleaseBuilds",
        value: "true",
      },
    ]

    additionalGraddleProperties.map(function (gradleProperty) {
      config.modResults.push(gradleProperty)
    })

    return config
  })
}

module.exports = withCustomGradleProperties
```

And then inside app.config.js I added the plugin like so in the `plugins` prop:

```
["./plugins/withGradleProperties"],
```

**Comment by Moi6AP** [comment]
> > ¿Esto también funciona para las compilaciones de EAS?
> 
> Para que el script funcione con compilaciones EAS, puede agregar lo siguiente a su sección inferior:`postinstall.js``package.json``"scripts"`
> 
> ```json
> "eas-build-post-install": "node ./scripts/postinstall.js"
> ```
> 
> Esto garantiza que el script se ejecute durante el proceso de compilación de EAS y también resuelva el problema allí.

TE AMOOOOOOOOOO

**Comment by Tieu-Mai-Nhi** [comment]
@bahadiraraz did you fix this?

**Comment by techgaun** [comment]
We ran into this same problem. And when we fixed it, we ran into another one. We ended up writing a [dead simple config plugin](https://github.com/DocuCare/config-plugin-rn76-expo52) if anybody is interested to streamline. May not solve for everything but both jetifier and memory allocation pool were the ones that needed resolving as soon as we upgraded to expo 52 and RN 0.76

**Comment by joenguyen0109** [comment]
> I was able to get this with a gradle plugin I wrote:
> 
> withGradleProperties.js
> 
> ```
> const { withGradleProperties } = require("@expo/config-plugins")
> 
> function withCustomGradleProperties(config) {
>   return withGradleProperties(config, function (config) {
>     /* Added gradle properties like this
>       { type: 'property', key: 'key', value: 'value' } */
>     const additionalGraddleProperties = [
>       // SDK 52: https://github.com/expo/expo/issues/30725
>       { type: "property", key: "android.enableJetifier", value: "true" },
>       {
>         type: "property",
>         key: "android.enablePngCrunchInReleaseBuilds",
>         value: "true",
>       },
>     ]
> 
>     additionalGraddleProperties.map(function (gradleProperty) {
>       config.modResults.push(gradleProperty)
>     })
> 
>     return config
>   })
> }
> 
> module.exports = withCustomGradleProperties
> ```
> 
> And then inside app.config.js I added the plugin like so in the `plugins` prop:
> 
> ```
> ["./plugins/withGradleProperties"],
> ```

this works for me. Thanks

**Comment by watadarkstar** [comment]
> We ran into this same problem. And when we fixed it, we ran into another one. We ended up writing a [dead simple config plugin](https://github.com/DocuCare/config-plugin-rn76-expo52) if anybody is interested to streamline. May not solve for everything but both jetifier and memory allocation pool were the ones that needed resolving as soon as we upgraded to expo 52 and RN 0.76

@techgaun Do you know if this is still needed in SDK 53? I upgraded to SDK 53 and I'm wondering if this code is still needed to enable Jetifier?

**Comment by techgaun** [comment]
@watadarkstar I've not actually tried it out recently. Sorry that's not helpful.

**Comment by bpeltonc** [comment]
> > We ran into this same problem. And when we fixed it, we ran into another one. We ended up writing a [dead simple config plugin](https://github.com/DocuCare/config-plugin-rn76-expo52) if anybody is interested to streamline. May not solve for everything but both jetifier and memory allocation pool were the ones that needed resolving as soon as we upgraded to expo 52 and RN 0.76
> 
> [@techgaun](https://github.com/techgaun) Do you know if this is still needed in SDK 53? I upgraded to SDK 53 and I'm wondering if this code is still needed to enable Jetifier?

I'm running Expo 53.0.22 / RN 0.79.5 and still need this Config Plugin to build for Android
