### ISSUE TITLE
Merge conflict left in published packages for expo-router 3.5.19

### ISSUE THREAD

**Issue by cjones26** [expo/expo#30724]
### Minimal reproducible example

N/A

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

The published package here:

https://www.npmjs.com/package/expo-router/v/3.5.19

Has a merge conflict in `build/testing-library/index.js`, starting on line 45:

<img width="1502" alt="image" src="https://github.com/user-attachments/assets/d0a206b0-3150-4bc7-8a9a-a83e5c7ccecb">

### Environment

N/A

**Comment by brentvatne** [comment]
hello! this is a dup of https://github.com/expo/expo/issues/30717 - it was resolved in expo-router@~3.5.20

**Comment by cjones26** [comment]
Got it, thanks @brentvatne!
