### ISSUE TITLE
[expo-video] Cannot hear audio when replace source (change quality)

### ISSUE THREAD

**Issue by Dominic-Preap** [expo/expo#30731]
### Minimal reproducible example

https://github.com/Dominic-Preap/expo-video-test

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Currently we are testing in `expo-video`, but when switch video quality  (replace source) ex: 720p, 480p, 360p ...,the audio is silent. 

Video example follow from the [doc](https://docs.expo.dev/versions/latest/sdk/video) and have function to change source. Or check in demo repo

```tsx  
import { useVideoPlayer} from 'expo-video';

const SOURCE = 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8';
const SOURCE_360 =  'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa_video_360_800000.m3u8';

const player = useVideoPlayer(SOURCE);

function onChangeVideoQuality(index: number) {
    const ct = player.currentTime;
    player.replace(SOURCE_360);
    player.currentTime = ct;
  }
  ```

### Environment

expo-env-info 1.2.0 environment info:
  - System:
      - OS: Windows 10 10.0.19045
  - Binaries:
      - Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      - Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      - npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  - npmPackages:
      - expo: ~51.0.24 => 51.0.24
      - expo-router: ~3.5.20 => 3.5.20
      - react: 18.2.0 => 18.2.0
      - react-dom: 18.2.0 => 18.2.0
      - react-native: 0.74.3 => 0.74.3
      - react-native-web: ~0.19.10 => 0.19.12
  - Expo Workflow: bare

### Expo Doctor Diagnostics

Dependencies are up to date

**Comment by behenate** [comment]
I think the problem might be that the `SOURCE_360` video source doesn't carry any audio.

**Comment by Dominic-Preap** [comment]
I know that, I brought this up because right now  there is no way to switch resolution for example 320p, 720p.

**Comment by Dominic-Preap** [comment]
@behenate it would be nice to have solution for that and it should be in documents.

**Comment by behenate** [comment]
@Dominic-Preap Sorry, I don't understand. So the issue is that there is no way to change the track of the stream? I'm not sure why you mentioned the audio

**Comment by Dominic-Preap** [comment]
Yes if that is the case for SDK52 then that's great, because currently I extract the resolution sources from .m3u8 file (which only contain video and no sound) and try to load that using `replace()` hoping it changes only video and  keeping the sound as I already pass main video source into `useVideoPlayer`

**Comment by behenate** [comment]
@Dominic-Preap Did some reading up on the topic and it seems like it might [not be possible to implement this on iOS](https://forums.developer.apple.com/forums/thread/675282) without using unreliable hacks. I'll let you know in here if anything changes.
