### ISSUE TITLE
Question: ##20456 marked resolved, but expo-constants still doesn't provide 'Constants.expoConfig.extra'?

### ISSUE THREAD

**Issue by MikeTheGreat** [expo/expo#30749]
### Minimal reproducible example

N/A - this is a question about another issue

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

in a development build

### Summary

Disclaimer: I'm new to React Native and Expo.  I read the last entry in #20456 but it doesn't make sense to me.  My apologies in advance - I'm 100% certain this is a [PEBKAC situation ](https://www.wisegeek.com/what-is-pebkac.htm) but I'm not sure how to fix the issue.

#20456 seems to confirm that you can't access Constants.expoConfig.extra.* using a web Expo app.  I think it's confirming that the 'extra' field is replaced by a submodule (which is what I'm seeing - all my fields in extra are replaced with 'router').

Can I ask what the recommended way of working around this is?  Should I use a different navigation library?  Is [react-native-dotenv](https://github.com/goatandsheep/react-native-dotenv) good here?  Is there another, better, (hopefully simpler :) ) approach?

Any help / advice / pointers would be greatly appreciated!
Thanks!

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 34, 34
        Build Tools: 30.0.3, 33.0.1, 34.0.0
        System Images: android-31 | Google APIs Intel x86_64 Atom, android-31 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      expo: ~51.0.22 => 51.0.22
      expo-router: ~3.5.18 => 3.5.18
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed

### Expo Doctor Diagnostics

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

configInfo: ================================================================
{
  name: 'MikesShoppingList',
  slug: 'MikesShoppingList',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'myapp',
  userInterfaceStyle: 'automatic',
  splash: {
    image: './assets/images/splash.png',
    resizeMode: 'contain',
    backgroundColor: '#ffffff'
  },
  ios: { supportsTablet: true },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/images/adaptive-icon.png',
      backgroundColor: '#ffffff'
    }
  },
  web: {
    bundler: 'metro',
    output: 'static',
    favicon: './assets/images/favicon.png'
  },
  plugins: [ 'expo-router' ],
  experiments: { typedRoutes: true },
  _internal: {
    isDebug: false,
    projectRoot: 'C:\\Users\\michp\\Desktop\\ReactNativeExperiments\\MikesShoppingList',
    dynamicConfigPath: 'C:\\Users\\michp\\Desktop\\ReactNativeExperiments\\MikesShoppingList\\app.config.js',
    staticConfigPath: 'C:\\Users\\michp\\Desktop\\ReactNativeExperiments\\MikesShoppingList\\app.config.json',
    packageJsonPath: 'C:\\Users\\michp\\Desktop\\ReactNativeExperiments\\MikesShoppingList\\package.json'
  },
  description: undefined,
  sdkVersion: '51.0.0',
  platforms: [ 'ios', 'android', 'web' ],
  extra: {
    apiKey: '<REDACTED>',
    authDomain: 'REDACTED.firebaseapp.com'
  },
  [Symbol(non-standard)]: true
}
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
@MikeTheGreat - good find, yeah environment variables are a better option here! however, please note that you should not be treating any of these environment variables as secret - so if you aren't comfortable with committing an api key to your source control, you should also ask whether you're comfortable with it being readable by anyone who can download your app. more info on env vars here: https://expo.dev/blog/what-are-environment-variables

**Comment by brentvatne** [comment]
also cc @amandeepmittal re: `extra` field and env vars
