### ISSUE TITLE
Image tag is not showing the image

### ISSUE THREAD

**Issue by karmalia** [expo/expo#30769]
### Minimal reproducible example

https://github.com/karmalia/react-native-image-load

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

I am experiencing an issue with my main application where the Drawer Navigation's header hamburger icon and other images are not rendering. I attempted to resolve this by adjusting my dependencies and trying various solutions, including using React Native's and Expo's Image tags, but the issue persists.

To troubleshoot, I created a new environment and installed all my dependencies to see if there was a problem with the libraries I am using. Despite these efforts, the problem remains.

I have created a repository to reproduce the issue. Any help with resolving this problem would be greatly appreciated.
I couldn't find a way to update expected dependencies that diagnosed by expo doctor.

# Steps to Reproduce:

- Clone the repository 
- Install the dependencies using npm install or yarn install.
- Run the app using expo start or react-native run.
- Image has rendered but not seen the center of the screen.

# Expected Behavior:

The image should render correctly.

Environment:

React Native version: 0.74.3
Expo version: 51.0.24
Device: Medium Phone API 28, Android 9.0

### Environment

node: v20.11.1

npmPackages:
expo: 51.0.24
expo-router: 3.5.20
react: 18.2.0
react-dom: 18.2.0 => 18.2.0
react-native: 0.74.3
react-native-web:  0.19.12

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.76.9
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.76.9
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.76.9
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

This project has multiple package manager lock files (pnpm-lock.yaml, package-lock.json). This may cause EAS build to restore dependencies with a different package manager from what you use in other environments.

One or more checks failed, indicating possible issues with the project.

**Comment by trungdvu** [comment]
Same here, I need to downgrade to expo 51.0.11 & react native 0.74.2.

**Comment by AliRehman7141** [comment]
same here, I'm using 
```
"expo": "51.0.34",
"react": "18.3.1",
"react-native": "0.75.3",
```

**Comment by marklawlor** [comment]
This appears to be a dependancy issue, altho I'm having trouble pinpointing the issue. When I clear the remove the unused dependencies, delete `node_modules` and `package-lock.json`; and reinstall the image loads correctly.

I'm going to close this issue as updating / resetting your dependencies should resolve the issue. If you do narrow it down to a specific dependency conflict, please create a new issue and we can investigate it further
