### ISSUE TITLE
Question: Expo.Calendar.createAttendeeAsync(eventId, details)

### ISSUE THREAD

**Issue by EltonZhong** [expo/expo#3076]
Expo.Calendar.createAttendeeAsync(eventId, details) is for android only. So how can I attach an attendee to an event on iOS?

**Comment by esamelson** [comment]
Hi @EltonZhong - unfortunately, Apple does not expose this functionality to iOS apps. Apps can read attendees, but not edit them. Expo apps are no exception. Sorry about this 😞

**Comment by EltonZhong** [comment]
> Hi @EltonZhong - unfortunately, Apple does not expose this functionality to iOS apps. Apps can read attendees, but not edit them. Expo apps are no exception. Sorry about this 😞

Got it, thank you.
