### ISSUE TITLE
Using api routes makes bugs on frontend

### ISSUE THREAD

**Issue by ImamJanjua** [expo/expo#30778]
### Minimal reproducible example

https://github.com/ImamJanjua/button-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

So I I am creating an native only app and there I am using react native reusables which is like shadcn but for RN built on top of nativewind. So as can be seen in the clip I just click on the button its all good. But when I call an api route using the api directory than there are error and the button will have this weird affect where It will not lose the active state. 

So I initially I thought this maybe because of the lib, but actually if I don't call there api using the api route but some other api than this effect will not take place and no error will be shown

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.22 - ~/.npm-global/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.1.1
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by ImamJanjua** [comment]
https://github.com/user-attachments/assets/312c32b2-a03d-4de0-927c-9ddcebe3164e

**Comment by marklawlor** [comment]
This appears to be an issue with NativeWind, can you please create the issue there.

If you replace the `Button` with the `import { Button } from 'react-native'` the repo works as expected.
