### ISSUE TITLE
[expo-router] Shared Routes is unusable

### ISSUE THREAD

**Issue by saulamsal** [expo/expo#30770]
### Minimal reproducible example

https://github.com/saulamsal/expo-router-twitter

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Coming to a conclusion after testing out several methods, there clearly seems to be an issue with shared routes. Essentially, when we press any bottom tab item for navigation, it just takes us to the index tab.

Video attached for reference:

https://github.com/user-attachments/assets/cccbaed2-1a8d-4aaf-be99-a09f638a1e6d

If you prefer to directly test with @EvanBacon's repo (https://github.com/EvanBacon/expo-router-twitter)

Other issues mentioning similar issue:
 #28978 
 #29273 
 #29708 
 
 I've noticed a @marklawlor update on #30266 PR on this, but still the same. The issue persists on web as well. 

### Environment

   System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.16 => 51.0.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
      react-native-web: ~0.19.6 => 0.19.12
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed

**Comment by saulamsal** [comment]
Adding a comment that this was not an issue at the time of Expo 49.

**Comment by marklawlor** [comment]
The issue is that you have no set an `initialRouteName` for these groups, so they all default to `index`.

A group name does not correlate to the default screen. E.g a tab pointing to `(profile)` does not load the `profile` screen. It just assigns you to the `(profile)` group. Typically you'd name your groups after the collective name of screens, not individual screens.

You can resolve your issue by adding this code to `app/(index,search,profile)/_layout.tsx`

```
export const unstable_settings = {
  index: {
    initialRouteName: "index",
  },
  profile: {
    initialRouteName: "profile",
  },
  search: {
    initialRouteName: "search",
  },
};
```

The reason why this may have worked in Expo 49 is because shared groups were not behaving correctly. The current implementation is more how we envision them.

We know its annoying having to rely on `unstable_settings`, but we're currently working on a new set of navigators that work in a friendlier manner.

**Comment by namluu25** [comment]
> The issue is that you have no set an `initialRouteName` for these groups, so they all default to `index`.
> 
> A group name does not correlate to the default screen. E.g a tab pointing to `(profile)` group does not load the `profile` screen, it just assigns you to the `(profile)` group. Typically you'd name your groups after the collective name of screens, not individual screens. The purpose of groups are to change the rendered layout based upon the direction of navigation (e.g You may want to render a tweet differently on a deep-link, or differently if the user navigated there from the feed or profile screen).
> 
> You can resolve your issue by adding this code to `app/(index,search,profile)/_layout.tsx`
> 
> ```
> export const unstable_settings = {
>   index: {
>     initialRouteName: "index",
>   },
>   profile: {
>     initialRouteName: "profile",
>   },
>   search: {
>     initialRouteName: "search",
>   },
> };
> ```
> 
> The reason why this may have worked in Expo 49 is because shared groups were not behaving correctly. The current implementation is more how we envision them.
> 
> We know its annoying having to rely on `unstable_settings`, but we're currently working on a new set of navigators that work in a friendlier manner.

Hi, I tried with your method on my app and it seems to not working anymore.
Current structure based on Evan's Expo Twitter
![image](https://github.com/user-attachments/assets/d638cb86-cd76-4f72-b808-c5aafc7b3437)
