### ISSUE TITLE
[expo-video] Cannot load local assets

### ISSUE THREAD

**Issue by janicduplessis** [expo/expo#30789]
### Minimal reproducible example

https://github.com/janicduplessis/expo/tree/%40janic/local-video-asset

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

Local assets do not work with expo-video. It errors with `Error: [constructor] Cannot convert 'x' to a Kotlin type`. I can workaround that error by using `Asset.fromModule` but then on Android in release mode the video still doesn't load. It looks like it is handled [here](https://github.com/expo/expo/blob/sdk-51/packages/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java#L377-L387) in expo-av, but expo video doesn't have similar code to handle local assets.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/janicduplessis/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.80.3
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.3
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.3
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Error: Problems validating fields in /Users/janicduplessis/Developer/expo/apps/bare-expo/app.json. Learn more.
 • should NOT have additional property 'facebookScheme'.
 • should NOT have additional property 'facebookAppId'.
 • should NOT have additional property 'facebookDisplayName'.
 • Field: notification - should NOT have additional property 'serviceWorkerPath'.
 • Field: notification - should NOT have additional property 'vapidPublicKey'.
 • Field: ios - should NOT have additional property 'scheme'.
 • Field: android - should NOT have additional property 'scheme'.

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@8.0.0 - expected version: 8.0.1
  expo@51.0.8 - expected version: ~51.0.24
  expo-camera@15.0.9 - expected version: ~15.0.14
  expo-dev-client@4.0.14 - expected version: ~4.0.21
  expo-image@1.12.9 - expected version: ~1.12.13
  expo-notifications@0.28.3 - expected version: ~0.28.14
  expo-splash-screen@0.27.4 - expected version: ~0.27.5
  react@19.0.0-rc-fb9a90fa48-20240614 - expected version: 18.2.0
  react-dom@19.0.0-rc-fb9a90fa48-20240614 - expected version: 18.2.0
  react-native@0.75.0-rc.5 - expected version: 0.74.3
  react-native-safe-area-context@4.10.7 - expected version: 4.10.5
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by behenate** [comment]
Hi! For now you will have to keep using `Asset.fromModule` to load the item, as we are trying to avoid having `expo-video` being dependent on `expo-asset`

You should try to load the asset this way:
```
const id = require('../../../../bare-expo/assets/bigbuckbunny.mp4');
const asset = Asset.fromModule(id).localUri || Asset.fromModule(id).uri;

const bigBuckBunnySource: VideoSource = {
  uri: asset,
  metadata: {
    title: 'Big Buck Bunny',
    artist: 'The Open Movie Project',
  },
};

// Use the bigBuckBunnySource
```

You might still have some issues with loading it on android, as this PR hasn't been released yet https://github.com/expo/expo/pull/30472

**Comment by janicduplessis** [comment]
@behenate Thanks for having a look. I did try this and it works fine except on Android in release mode. In that case it becomes the resource identifier of the asset which the current implementation does not handle. 

I found this code https://github.com/expo/expo/blob/sdk-51/packages/expo-av/android/src/main/java/expo/modules/av/player/SimpleExoPlayerData.java#L377-L387 in expo-av which I think would be needed to add something similar to handle that case.

**Comment by behenate** [comment]
@janicduplessis Interesting, for me using `localUri` made it work for release version. I'll try your repro.

**Comment by janicduplessis** [comment]
I also observed different behaviours on different android versions. In my case I tested on API 31 emulator and I just get a black box for video, but on some other android version it crashes the app.

**Comment by behenate** [comment]
@janicduplessis I managed to reproduce the issue in a fresh app. It's odd that it worked in `bare-expo` 🤔 . The code from `expo-av` seems to work ok, I'll add it to `expo-video`

**Comment by behenate** [comment]
@janicduplessis The fix is in the PR, you can patch-package and test it in your app, if you have the time 😄 Thanks for being persistent, otherwise I would've merged incorrect docs 😅

**Comment by janicduplessis** [comment]
@behenate Awesome! I will give it a try soon.

**Comment by janicduplessis** [comment]
@behenate I just tested the patch in my app and it works great now! However I did find a new issue related to proguard if you would also like to have a look :) https://github.com/expo/expo/issues/30901
