### ISSUE TITLE
Fetching all assets through expo-media-library causes UI to freeze up

### ISSUE THREAD

**Issue by dsemelianov** [expo/expo#30781]
### Minimal reproducible example

https://github.com/dsemelianov/PhotoLoaderExample

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

I am trying to use expo-media-library to fetch all of the photos on the user's device. The issue is that trying to fetch all of the user's photos causes the app to become extremely slow and UI to get unusably laggy until the sync process completes.

Here is a video from the example app that I provided which shows the issue: https://streamable.com/8uorhr

In the example app I provided, I am simply fetching all of the photos from the user's library and doing nothing else. No photo processing, no rendering any photos in the UI. I simply fetch all of the photos available in the user's library in small batches until there are no more photos left.

I am rendering a single list view full of dummy test data which can be used to test how responsive the app UI is. 
While the photo sync is running, the list is barely scrollable and extremely choppy. The entire app is slow. 
But once the photo sync completes, the list becomes fast again.

Things I have tried to speed up the sync:
- fetching photos asynchronously
- batching the photos i fetch in groups of 20
- fetching all photos at once (this crashes the app, no surprise)

In addition to the UI becoming very slow and laggy while the photo sync process is running, I have noticed that the time that it takes to fetch 100 photos using expo-media-library is significantly slower than it takes for a native iOS app to do the same. I am not sure if this is due to some limitation in the expo-media-library, but it just seems far slower to fetch photos.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 3.6.4 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/davidemelianov/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.24 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.4 => 0.74.4 
    npmGlobalPackages:
      eas-cli: 7.8.5
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

No issues

**Comment by dsemelianov** [comment]
NOTE - I have verified that excessive renders are not the issue, as the app component is only being re-rendered whenever a new batch of 20 photos is processed.

**Comment by florian-deroo** [comment]
@dsemelianov How did you solved this issue ?
