### ISSUE TITLE
Why are all the bug fixes and new features in expo-camera not released?

### ISSUE THREAD

**Issue by 0x6D70** [expo/expo#30785]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by 0x6D70** [comment]
@alanjhughes maybe you know something about this, as most features are from you

**Comment by alanjhughes** [comment]
@0x6D70 we don't always release everything during the current sdk cycle. What fix are you looking at?

**Comment by 0x6D70** [comment]
@alanjhughes I am currently waiting for #29822 to be released
