### ISSUE TITLE
Expo - AV : Issues with Audio recording Interruption detection when App goes Background

### ISSUE THREAD

**Issue by saurav-bhagat** [expo/expo#30792]
### Minimal reproducible example

https://github.com/saurav-bhagat/expo-av-sample

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Hi Team, 
I am using expo-av in my expo app and am stuck in a situation:
Could someone please look into this and let me know if any additional information is required?

Application use case:

Start Audio Recording
At a certain interval, stop the recording, take the recording chunk created till now and again start the recording.
There is also a pause button that the user can use to pause the recording and then click it again to resume.
App can go to background, or foreground in this duration.
If the recording is going on, and interruption comes from other apps like Call, siri, etc., pause the recording.

Issues:
When the app goes to the background and a call comes, we are not able to get the exact interruption. Currently, we are using a hack in the handleRecordingStatusUpdate function where if we get this condition true for 5 seconds we pause the recording.
(!status?.isRecording  &&  !status?.mediaServicesDidReset  &&  status?.durationMillis  ===  0)
Is there any way to detect these interruptions in a more accurate way?

Our recording stops as soon as the call comes, even when we have not picked up the call.  How can we avoid this situation?

Once in the background after one interruption, we are unable to restart the recording, it always says - Can't start the recording. 

Sample Recording Class can be found here: 
[https://github.com/saurav-bhagat/expo-av-sample/blob/main/AppointmentManager.tsx](https://github.com/saurav-bhagat/expo-av-sample/blob/main/AppointmentManager.tsx)

### Environment

npx expo-env-info
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.12 => 51.0.12 
      expo-router: ~3.5.16 => 3.5.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.1
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

npx expo-doctor@latest
Need to install the following packages:
expo-doctor@1.9.0
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check for common project setup issues
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains local Expo modules, but the android/ios folders inside the modules are gitignored. These files are required to build your native module into your app. Use patterns like "/android" and "/ios" in your .gitignore file to exclude only the top-level android and ios folders.

The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.12 - expected version: ~51.0.24
  expo-av@14.0.5 - expected version: ~14.0.6
  expo-build-properties@0.12.3 - expected version: ~0.12.4
  expo-camera@15.0.11 - expected version: ~15.0.14
  expo-dev-client@4.0.18 - expected version: ~4.0.21
  expo-font@12.0.7 - expected version: ~12.0.9
  expo-notifications@0.28.9 - expected version: ~0.28.14
  expo-router@3.5.16 - expected version: ~3.5.20
  expo-system-ui@3.0.6 - expected version: ~3.0.7
  react-native@0.74.2 - expected version: 0.74.3
  react-native-safe-area-context@4.10.1 - expected version: 4.10.5
  react-native-webview@13.10.5 - expected version: 13.8.6
  jest-expo@51.0.2 - expected version: ~51.0.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

**Comment by DevelopJKong** [comment]
same here

**Comment by lhr000lhr** [comment]
any updates?
