### ISSUE TITLE
Standalone build failed!

### ISSUE THREAD

**Issue by esolz-sovan** [expo/expo#3079]
Certificates are working fine for xcode but in expo getting error. I have attached the expo diallogue message. I have tried 10 times but not able to build a new one. Previosly I was build with this same same certificates it was working fine but today getting error. Last build ID: default-32966797-541c-448c-b5e4-d43766be312d

Error: codesign ident not present in find-identity: 2B921C134BFEE40DAC1A930C82D0D01C287C977F
Looking for identities matching "(K22GQFS8BW)"
     0 valid identities found

    at Object.<anonymous> (/usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:17:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:230:191)
    at /usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:230:361
    at <anonymous>

**Comment by esolz-sovan** [comment]
also tried certificates from expo fetch:ios:certs but failed. build ID: default-eb291954-5f76-4205-b2a7-3b7e50b41ba4

**Comment by esolz-sovan** [comment]
it was a Distribution certificate issue.

**Comment by jakeprins** [comment]
How did you fix it?
