### ISSUE TITLE
Cannot Access Secure store values via icloud keychain

### ISSUE THREAD

**Issue by raghulkrishna** [expo/expo#30795]
### Minimal reproducible example

https://gist.github.com/raghulkrishna/29883f9b21cd3a4c87948b4fdb4f816a

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

I am trying save a encrpytion key in icloud keychain it seems it is not saving the values to icloud keychain, i am not able to see in keychain rather dont get values in different device with same apple account . How can i enable this sync?

### Environment

expo-env-info 1.2.0 environment info:
System:
OS: macOS 14.5
Shell: 5.9 - /bin/zsh
Binaries:
Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm
Managers:
CocoaPods: 1.15.2 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
IDEs:
Xcode: 15.4/15F31d - /usr/bin/xcodebuild
npmPackages:
@expo/webpack-config: ^19.0.1 => 19.0.1
expo: ~50.0.14 => 50.0.14
expo-router: ~3.4.8 => 3.4.8
react: 18.2.0 => 18.2.0
react-native: 0.73.6 => 0.73.6
Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by vonovak** [comment]
Hello and thanks for asking,
currently keychain syncing to icloud isn't implemented. It requires [ksecattrsynchronizable](https://developer.apple.com/documentation/security/ksecattrsynchronizable)

Thank you 🙂
