### ISSUE TITLE
Feature Request: Integrate Auth0's react-native-lock

### ISSUE THREAD

**Issue by btroia** [expo/expo#308]
Are there plans to support Auth0's react-native-lock module in Expo's SDK? 

[https://github.com/auth0/react-native-lock](https://github.com/auth0/react-native-lock)

Expo's current Auth0 login/registration flow (opening a web browser and redirecting back to the app) provides a pretty poor using experience versus keeping the entire experience within an app. Thanks!

**Comment by brentvatne** [comment]
> Expo's current Auth0 login/registration flow (opening a web browser and redirecting back to the app) provides a pretty poor using experience versus keeping the entire experience within an app. Thanks!

I disagree! This is very common to use SFSafariViewController and Chrome Custom Tabs for OAuth flows. It is becoming the new standard way to do this, you'll find more and more apps are using this approach. [Read more about this flow on Google's blog](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html).

That said, if you want to use the native SDKs to get the token, you're welcome to do that too -- see the docs for [Facebook](https://docs.expo.io/versions/v18.0.0/sdk/facebook.html) and [Google](https://docs.expo.io/versions/v18.0.0/sdk/google.html). I believe auth0 exposes some API similar to `firebase.auth().signInWithCredential` [example](https://docs.expo.io/versions/v18.0.0/guides/using-firebase.html#listening-for-authentication) where you can take the token that you get back from the Facebook/Google APIs and use that to authenticate the user with auth0.

Including auth0-lock doesn't really deal with doing the kind of auth flow you're looking for either, it is just a sign in screen. You would need to install a plugin for each service you want to authenticate with on top of that, eg: [Lock-Facebook.iOS](https://github.com/auth0/Lock-Facebook.iOS). We don't plan on integrating react-native-auth0-lock: https://expo.canny.io/feature-requests/p/support-for-auth0-react-native-lock-module
