### ISSUE TITLE
npx expo prebuild fails with Unexpected end of JSON input

### ISSUE THREAD

**Issue by Gradlon** [expo/expo#30806]
### Summary

When trying to prebuild the app, I get the following output

```
📝  Android package Learn more: https://expo.fyi/android-package

✔ What would you like your Android package name to be? … com.gradlon.myapp


📝  iOS Bundle Identifier Learn more: https://expo.fyi/bundle-identifier

✔ What would you like your iOS bundle identifier to be? … com.gradlon.myapp

Unexpected end of JSON input

✖ Failed to create the native directories
You may want to delete the ./ios and/or ./android directories before trying again.
````
The direcotries ./ios and ./andorid are not present

### What platform(s) does this occur on?

Android, iOS

### SDK Version

0.18.26

### Environment

MacOS 14.5 
Apple M3
Node v20.9.0

### Minimal reproducible example

Steps to reproduce this error are
```
npx create-expo-app@latest
cd my-app
npx expo prebuild
```
I can use the app in dev mode on IOS and Android simulator but i can't build the apps.

**Comment by byCedric** [comment]
Hi @Gradlon! Unfortunately, this can happen when there are server stability issues with npm. [Prebuild](https://github.com/expo/expo/blob/58a6780e550a04897bfca6b42f13959e074488e9/packages/%40expo/cli/src/prebuild/prebuildAsync.ts#L89-L97) uses the `expo-template-bare-minimum` package as base template by default. If that's not cached locally, and npm responds incorrectly, you'll likely run into this.

I can't repro this from Europe, so I assume the server issues are either fixed or local to specific regions. It might help validating that this is the issue by running `EXPO_DEBUG=true npx expo prebuild`.

Hope this helps

**Comment by Gradlon** [comment]
@byCedric thank you!
This was the hint I needed.
For anyone having the same issue, my current employer uses its own npm repo.
The repo was added to NPM RC.

Removing it solved the problem!
