### ISSUE TITLE
Send push nofitication without expo server

### ISSUE THREAD

**Issue by ardyfeb** [expo/expo#3080]
I have production app, my app will send 100+ notification per day. How to send direct push notification without expo server.

Expo now push notification system:
Backend -> Expo server -> App

I want :
Backend -> App

Because i want to protect our user privacy

**Comment by ide** [comment]
The Expo notification service is private but if you want to use your own server for another reason, you can use ExpoKit (in which case you need to use your own notification service anyway) or you can get the native device token in standalone apps (this only works with standalone apps for technical reasons) and then send a payload in the form the Expo servers do -- this is undocumented, however.
