### ISSUE TITLE
[expo-notifications] Important crash on android 14

### ISSUE THREAD

**Issue by nguyenthanhtruongntt85** [expo/expo#30800]
### Minimal reproducible example

https://gns-slug.sentry.io/share/issue/160070f7ee3a4d1e891fb7d423e94a4e/

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

Open app is crash: Could not put 'class android.os.UserHandle' to WritableMap

### Environment

"expo": "~51.0.9",
"react-native": "0.74.1",
"react": "18.2.0",
"expo-notifications": "~0.28.14",

### Expo Doctor Diagnostics

The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.9 - expected version: ~51.0.24
  expo-asset@10.0.6 - expected version: ~10.0.10
  expo-build-properties@0.12.1 - expected version: ~0.12.4
  expo-dev-client@4.0.15 - expected version: ~4.0.21
  expo-font@12.0.6 - expected version: ~12.0.9
  expo-splash-screen@0.27.4 - expected version: ~0.27.5
  expo-updates@0.25.15 - expected version: ~0.25.21
  react-native@0.74.1 - expected version: 0.74.3
  react-native-safe-area-context@4.10.1 - expected version: 4.10.5
  jest-expo@51.0.2 - expected version: ~51.0.3

**Comment by NaokiOtsu** [comment]
Probably the same problem
https://github.com/expo/expo/issues/30738#issuecomment-2267357949

**Comment by nguyenthanhtruongntt85** [comment]
> Probably the same problem [#30738 (comment)](https://github.com/expo/expo/issues/30738#issuecomment-226735794

> Probably the same problem [#30738 (comment)](https://github.com/expo/expo/issues/30738#issuecomment-2267357949)

Correct, thanks!
