### ISSUE TITLE
Images not updated on android build

### ISSUE THREAD

**Issue by patrickLorenz83** [expo/expo#3083]
Hi, I have the problem that images are not updated when running expo build:android. I tryed using the assetbundler and loading the assets as cached images, nothing is working. any ideas whats the problem? I'm using sdk version 31. assetbundles is empty in build log (when using /assets/\*). when using the suggested value from docu (/assets/images/\*) I get the following error: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined

**Comment by esamelson** [comment]
Hi @patrickLorenz83 - could you help us help you out better by posting a full reproduction of this issue? A github repo with an [mcve](https://stackoverflow.com/help/mcve) would be great. Otherwise it's hard for us to figure out exactly what's going on. Thanks!

**Comment by patrickLorenz83** [comment]
was mz fault, I didn't published the projet :(

**Comment by patrickLorenz83** [comment]
Was mz fault, I didn't published the project. Asset bundling still doesn't work, but this is another topic.
