### ISSUE TITLE
Standalone build on local machine not working

### ISSUE THREAD

**Issue by patrickLorenz83** [expo/expo#3084]
I followed the documentation on how to build on a local machine the abdorid build.
I'm getting the following error:

Dec 29 01:39:03 turtle[12751] ERROR: spawn zipalign ENOENT
Dec 29 01:39:03 turtle[12751] INFO:  jarsigner: java.io.FileNotFoundException: shell.apk (No such file or directory)
  buildPhase: "verifying apk"
  source: "stdout"
Dec 29 01:39:03 turtle[12751] ERROR: Process exited with non-zero code: 1
Dec 29 01:39:03 turtle[12751] ERROR: Error: ENOENT: no such file or directory, lstat 'shell.apk'
Dec 29 01:39:03 turtle[12751] ERROR: Failed to build standalone app: ENOENT: no such file or directory, lstat 'shell.apk'
Dec 29 01:39:03 turtle[12751] ERROR: Error: ENOENT: no such file or directory, lstat 'shell.apk'

Any ideas what is wrong?

**Comment by esamelson** [comment]
@patrickLorenz83 - could you please post some steps to reproduce this issue? cc @dsokal

**Comment by dsokal** [comment]
Hello @patrickLorenz83,
it looks like turtle-cli cannot find `zipalign`. 
Please check whether `~/.turtle/androidDependencies/sdk/build-tools/25.0.0/zipalign` exists. If not, then remove `~/.turtle/androidDependencies/sdk` directory and run turtle build again.

**Comment by dsokal** [comment]
I'm closing this one because of the inactivity. I assume it's not a problem anymore.
