### ISSUE TITLE
App Crashes on Second Launch with Hermes: NativeUnimoduleProxy Error

### ISSUE THREAD

**Issue by bouakram** [expo/expo#30844]
### Summary

I'm experiencing an issue when i build the app using eas preview profile and when i install the app my Expo app crashes upon the second launch on Android. The crash doesn't occur on the first launch but happens every time I reopen the app.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@gorhom/bottom-sheet": "^4.6.0",
    "@hookform/resolvers": "^3.3.4",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-navigation/native": "^6.0.2",
    "@rnmapbox/maps": "^10.1.24",
    "@shopify/react-native-skia": "1.2.3",
    "@tanstack/react-query": "^5.17.19",
    "@types/d3": "^7.4.3",
    "axios": "^1.5.0",
    "d3": "^7.9.0",
    "expo": "~51.0.24",
    "expo-blur": "^13.0.2",
    "expo-build-properties": "~0.12.4",
    "expo-dev-client": "~4.0.21",
    "expo-document-picker": "~12.0.2",
    "expo-file-system": "^17.0.1",
    "expo-font": "^12.0.4",
    "expo-haptics": "^13.0.1",
    "expo-image-picker": "~15.0.7",
    "expo-linking": "^6.3.1",
    "expo-location": "^17.0.1",
    "expo-router": "~3.5.20",
    "expo-sharing": "^12.0.1",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "^1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "lottie-react-native": "6.7.0",
    "moment": "^2.30.1",
    "moment-range": "^4.0.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.49.3",
    "react-native": "0.74.3",
    "react-native-calendars": "^1.1305.0",
    "react-native-chart-kit": "^6.12.0",
    "react-native-gesture-handler": "^2.16.1",
    "react-native-modern-datepicker": "^1.0.0-beta.91",
    "react-native-reanimated": "^3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "^3.31.1",
    "react-native-star-rating-widget": "^1.7.3",
    "react-native-svg": "15.2.0",
    "react-native-web": "~0.19.6",
    "zod": "^3.22.4",
    "zustand": "^4.5.0",
    "expo-notifications": "~0.28.15",
    "expo-device": "~6.0.2",
    "expo-constants": "~16.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "@tanstack/eslint-plugin-query": "^5.17.22",
    "@types/react": "^18.2.79",
    "@types/react-native-modern-datepicker": "^1.0.5",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.3",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996
    npmPackages:
      expo: ~51.0.24 => 51.0.24
      expo-router: ~3.5.20 => 3.5.20
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

### Reproducible demo

https://github.com/bouakram/testing

### Stacktrace (if a crash is involved)

com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get for prop 'NativeUnimoduleProxy': java.lang.IllegalArgumentException: Could not put 'class android.os.UserHandle' to WritableMap, js engine: hermes, stack:
anonymous@1:692149
loadModuleImplementation@1:90499
guardedLoadModule@1:90047
metroRequire@1:89669
anonymous@1:436360
loadModuleImplementation@1:90499
guardedLoadModule@1:90047
metroRequire@1:89669
anonymous@1:434373
loadModuleImplementation@1:90499
guardedLoadModule@1:90047
metroRequire@1:89669
anonymous@1:96718
loadModuleImplementation@1:90499
guardedLoadModule@1:90047
metroRequire@1:89669
anonymous@1:96601
loadModuleImplementation@1:90499
guardedLoadModule@1:90004
metroRequire@1:89669
global@1:89210
at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
at com.facebook.jni.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:914)
at android.os.Handler.dispatchMessage(Handler.java:100)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:224)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
at java.lang.Thread.run(Thread.java:919)

**Comment by luiztafarel** [comment]
nessa nova versão do expo estou com o problema de que em dispositivos xiaomi ele abre a tela de splash e dois fecha o app, mas nos samsung e motorolas funciona perfeitamente

**Comment by bouakram** [comment]
@luiztafarel I've tried it on two Xiaomi devices, and I encountered the same problem on both.

**Comment by wcastand** [comment]
it happens on Xiaomi, Redmi and POCO devices for us

**Comment by a-leblond** [comment]
Same for us, only Xiaomi phone (Redmi, POCO, ...)
`"expo": "~51.0.24"`

**Comment by wcastand** [comment]
updating to the version suggested by `expo-doctor` fixed the bug for me on dev build.
