### ISSUE TITLE
Turborepo, expo-dev-client and prebuild fails.

### ISSUE THREAD

**Issue by danielmeyer-sa** [expo/expo#30854]
### Summary

When using expo-dev-client in a turborepo setup, it fails when using prebuild.

```
...
› Compiling myapp » myapp_vers.c
› Compiling myapp » main.m
› Compiling myapp » AppDelegate.mm
› Linking   myapp » myapp
⚠️  ld: ignoring duplicate libraries: '-lc++'
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
❌  Undefined symbols for architecture arm64
┌─ Symbol: _OBJC_CLASS_$_DevClientAppDelegate
└─ Referenced from: _OBJC_CLASS_$_EXRCTAppDelegateInterceptor in libexpo-dev-launcher.a[13](EXRCTAppDelegateInterceptor.o)


❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


```

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~4.0.21"
"expo": "~51.0.24"

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo-router: ~3.5.20 => 3.5.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare

### Reproducible demo

https://github.com/danielmeyer-sa/turborepo-expo-reproducible-demo

### Stacktrace (if a crash is involved)

```
...
› Compiling myapp » myapp_vers.c
› Compiling myapp » main.m
› Compiling myapp » AppDelegate.mm
› Linking   myapp » myapp
⚠️  ld: ignoring duplicate libraries: '-lc++'
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
❌  Undefined symbols for architecture arm64
┌─ Symbol: _OBJC_CLASS_$_DevClientAppDelegate
└─ Referenced from: _OBJC_CLASS_$_EXRCTAppDelegateInterceptor in libexpo-dev-launcher.a[13](EXRCTAppDelegateInterceptor.o)


❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


```

**Comment by danielmeyer-sa** [comment]
The problem seems to be starting at `expo-dev-client` version `4.0.20`. If I downgrade to `4.0.19` the error disappears.

**Comment by danielmeyer-sa** [comment]
It still doesn't work tough. Now I get this error. Maybe not a `expo-dev-client` problem. 

I've added these env variables to get it to work with monorepos
```
EXPO_USE_METRO_WORKSPACE_ROOT=1
EXPO_ROUTER_APP_ROOT=../../apps/my-app/app
```

But I get this error.
```
 ERROR  TypeError: Cannot read property 'useId' of null

This error is located at:
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

**Comment by brentvatne** [comment]
we don't explicitly support/test against turborepo. refer to our monorepo guide on more general information about monorepo support in expo and react-native projects: https://docs.expo.dev/guides/monorepos/

if there is something that we are doing that is incompatible with turborepo and that we should fix, let us know what that is and we can help out!

**Comment by Brenndoerfer** [comment]
> The problem seems to be starting at `expo-dev-client` version `4.0.20` (and later). If I downgrade to `4.0.19` the error disappears.

I can confirm that downgrading resolved the build error for me too. I also use `turborepo`, but I doubt that it's the root cause here.

**Comment by w4t3r-45** [comment]
still having same issue even if i install 4.0.19 version any other solutions please ?

**Comment by Arjan-Zuidema** [comment]
Same issue, not using turborep. Happend when updating expo from 50 to 51

**Comment by dylanschoenmakers** [comment]
Having the same issue, am using turborepo as well

**Comment by w4t3r-45** [comment]
hey guys i was able to resolve the issue on my side , the trick is that i had 2 expo apps using different versions (49 and 51) the old app was just deprecated so i deleted it completely the reinstalled the packages again and then the build went fine , i hope you can resolve too.

**Comment by rubinovitz** [comment]
Been having this issue all week, been unable to resolve

**Comment by Kasendwa** [comment]
Hey @rubinovitz, if you're still having this challenge, try adding an expo `overrides` entry in your `package.json` file.

```
{
    ...
    "overrides": {
       "expo": "$expo"
    },
    ...
}
```

That will help ensure that no other dependencies tries to install a separate version of the expo sdk than you've stated in your setup.

**Comment by RutvinCoditas** [comment]
I am also facing the same issue. 
expo: 51.0.39

**Comment by Frexuz** [comment]
Same here expo 52.0.47 + turborepo + Bun

```
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a specification for `ReactAppDependencyProvider` depended upon by `ExpoModulesCore`
```

if i copy the whole app outside of the monorepo, everything works 😭
