### ISSUE TITLE
[android] client shows never-ending blue spinner when connection to dev server is lost

### ISSUE THREAD

**Issue by p** [expo/expo#3085]
I am developing a React Native application with expo, running on Android. Occasionally my application on the phone gets replaced by a white background with a blue spinner. One time when this happens is when the application gets replaced on the development laptop, as follows:

1. Create two blank expo projects
2. Run `npm start` in project A
3. Open expo on the phone, load project A's application
4. Go to the laptop and kill project A
5. Run `npm start` in project B (the application gets started on the same port, 19000)
6. Go to the phone, pull down notifications and reload from expo's notification
7. The application ("Open up App.js to start working on your app!" skeleton) gets replaced by the white background with a blue spinner.

At this point, the application on the phone seems to be indefinitely stuck in this blue spinner. It does not say what it's trying to do, like during normal loading when the status bar says "downloading javascript bundle" and such. When I pull down notifications, expo's notification bar is not present and I am unable to reload the application - I have to close the application, return to expo's list of applications and launch the application again.

### Environment

<pre>
butler% expo diagnostics
[03:15:42] Cannot read property '1' of null
[03:15:42] Set EXPO_DEBUG=true in your env to view the stack trace.
</pre>

Here's the package.json:

<pre>
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
</pre>

Target is Android. My phone wants to update itself when I try to view its version hence I don't know what the version is but I believe it's 7.x.

### Expected Behavior

- When the blue spinner is spinning, there should be a status message displayed in the status bar explaining what the application is trying to do/waiting for.
- When the blue spinner is spinning, notifications should include the expo bar, allowing me to reload the application.
- Whatever the application is actually trying to do should succeed or fail and produce an appropriate message/conclusion.

**Comment by esamelson** [comment]
Hi @p - sorry about this 😞 I'm not sure exactly what's going on here but I think the app is probably confused because it expected the connection to project A to still be open. Does it work if you close project A on the phone and re-open it from the Expo home screen after starting project B?

**Comment by p** [comment]
I also get the blue spinner when I am working with a single application and I make changes to it. There is a possibly related issue which is as follows: every so often, I would get an error in the expo server (the npm run one) about connection being reset. This happens if I put the laptop to sleep once I have the RN app open on the phone, but also could possibly happen in other circumstances. I haven't yet put the time to figure out reliable reproduce steps because it involves waiting for the connection to time out. In any event, a network error appears to kill the *server* of the expo app, after which the app is not usable on the phone (npm run must be killed and restarted) and I also get the blue spinner on the phone when this happens.

The two application reproduce case I described just seems like an easier way to trigger the blue spinner. The real question/issue I have is the application should communicate what it's waiting for, and should at least have the reload button enabled.

I am not 100% certain on this but I suspect there may be other ways of getting the phone app into the blue spinner state that don't involve the expo server dying. These other situations seem to happen more frequently on my tablet which isn't as well specced hardware wise as the phone.

**Comment by p** [comment]
To answer your question, yes, closing the app with the spinner and reopening it from expo does work.

**Comment by esamelson** [comment]
This is possibly related to https://github.com/expo/expo/issues/2435 . If the connection between the device and the development server on your computer gets closed, you may need to reopen the experience from Expo. However, we should show a message or something rather than a never-ending blue spinner.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
