### ISSUE TITLE
Why there are some extra space above the header when I use drawer

### ISSUE THREAD

**Issue by zhouhao27** [expo/expo#30851]
### Minimal reproducible example

https://github.com/zhouhao27/expo-router-drawer-demo

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

![Simulator Screenshot - iPhone 15 Pro - 2024-08-06 at 21 05 59](https://github.com/user-attachments/assets/3128650a-9d6e-4163-98ba-c56dd6cfd313)

Extra space added above the header. But if I set `headerShower` to `false`, then there is no header at all.

![Simulator Screenshot - iPhone 15 Pro - 2024-08-06 at 21 08 59](https://github.com/user-attachments/assets/7cef3939-faa2-480b-8214-7f10f64ec27b)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.0/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
      Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Xcode: 16.0/16A5171r - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.24 => 51.0.24
      expo-router: ~3.5.20 => 3.5.20
      react: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
    Expo Workflow: managed

**Comment by chumaumenze** [comment]
@zhouhao27 you can remove the space with `headerStatusBarHeight`.

```ts
<Tabs screenOptions={{headerStatusBarHeight: 0}}>
    <Tabs.Screen name="overview" />
</Tabs>
```
