### ISSUE TITLE
[expo-image][Android] Gifs animation never stops even when loop count is set to 1

### ISSUE THREAD

**Issue by desquinazi-rbi** [expo/expo#30858]
### Minimal reproducible example

https://snack.expo.dev/@desquinazirbi/expo-image-gifs-issue

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Rendering Gifs with expo-image Image component on Android doesn't stop gif animation even when gif has loop count set to 1.
The expected behavior for this should be the same for iOS where gif animation only runs once and then it stops.

Dependencies: `"expo-image": "~1.12.13"`

Important Note: It is working as expected if I replace expo-image Image component with the React Native Image Component one.

### Environment

.

### Expo Doctor Diagnostics

.

**Comment by fobos531** [comment]
Not sure if this is an issue in Glide or Expo's implementation. I can confirm that this issue happens in bare-expo with the provided GIF, and even if tweak Glide version like so: 
![CleanShot 2024-08-07 at 16 07 55@2x](https://github.com/user-attachments/assets/f85d10bf-4379-4a36-8501-467598ea4dc5)

**Comment by lukmccall** [comment]
It's not an issue in `expo-image`. It has to be fixed in the Gif decoding library. [Here is a PR](https://github.com/penfeizhou/APNG4Android/pull/229) that should solve your issue. I'm closing it for now.
