### ISSUE TITLE
[3.5.21] - [id] wildcard matched higher than explicit selector

### ISSUE THREAD

**Issue by austin43** [expo/expo#30879]
### Minimal reproducible example

https://github.com/austin43/expo-router-bug-3.5.21

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

After installing 3.5.21, I noticed our explicit routes were no longer being matched over [id] wildcard routes. When we routed to "/nested/create" for example, it would render the "/nested/[id]" route with create as the id param.

Click either button on the homepage of example app, and notice how each goes to the [id] page, rather than one going to [id] and the other to create.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
      Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 28, 31
        Build Tools: 30.0.2, 30.0.3, 31.0.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.25 => 51.0.25 
      expo-router: ~3.5.21 => 3.5.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

**Comment by Cat-Green** [comment]
i find a problem when i try to navigate to parent stack in a child as example 

i have a drawer navegation

<Drawer
            backBehavior="history"
            initialRouteName="(tabs)"
            drawerContent={DrawerContent}
            screenOptions={{
                
                headerShown: false,
                drawerStyle: {
                    width: "75%",

                    backgroundColor: colors.gray[800],
                },
            }}
        >
            <Drawer.Screen
                name="(tabs)"
                options={{
                    title: "Início",
                    drawerIcon: ({ color, size }) => (
                        <HomeIcon size={size} color={color} />
                    ),
                }}
            />

          
            
          
            <Drawer.Screen
                name="(booksPublication)"
            />
            <Drawer.Screen
                name="(comicsPublication)"
            />



        </Drawer>

and tabs

 <Tabs
        backBehavior="history"
        screenOptions={{
          tabBarStyle: {
            backgroundColor: colors.gray[800],
            borderTopColor: colors.gray[500],
            height: 68,
          },
          tabBarShowLabel: false,
          headerShown: false,
          tabBarInactiveTintColor: "#fff",
          tabBarActiveTintColor: colors.green[500],
        }}
        sceneContainerStyle={{ backgroundColor: "transparent" }}
      >
        <Tabs.Screen
          name="(feed)"
          options={{
            title: "Home",
            tabBarIcon: ({ color, size }) => (
              <Entypo name="globe" size={iconSize} color={color} />
            ),
          }}
        />
</Tabs>

when my user is in tabs screen ,  i'm try navigate to  (comicPublication) the app navigate to another screeen

**Comment by Cat-Green** [comment]
i turn back to expo router in version  3.5.20 and work pretty well

**Comment by austin43** [comment]
I installed 3.5.23 and the issue persists with the demo use-case.

**Comment by austin43** [comment]
Can this be reopened @marklawlor?

**Comment by statico** [comment]
Vote to reopen. We are experiencing this after upgrading from expo-router 3.5.12 to 3.5.23.

**Comment by statico** [comment]
Oops, conversation has been moved to the PR: https://github.com/expo/expo/pull/30909
