### ISSUE TITLE
Can't use axios - It failed because the native React runtime does not include the Node standard library.

### ISSUE THREAD

**Issue by Zweird-958** [expo/expo#30870]
### Minimal reproducible example

https://github.com/Zweird-958/my-wishlist/tree/feature/mobile

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Hey 👋🏻

I have a monorepo with expo router and pnpm.
My app works on android if I set  `"main": "src/index.ts",` in my `package.json`.
Also here my `index.ts`:
```ts
import "expo-router/entry"
```

But if I use this, axios can't be used I have this error :
```
The package at "../../node_modules/.pnpm/axios@1.7.3/node_modules/axios/dist/node/axios.cjs" attempted to import the Node standard library module "url".
It failed because the native React runtime does not include the Node standard library.
```

If I use `expo-router/entry` as `main` in my `package.json` it works, but I can't run my app on Android.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.local/state/fnm_multishells/80612_1723043019523/bin/node
      npm: 10.8.1 - ~/.local/state/fnm_multishells/80612_1723043019523/bin/npm
      Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    Expo Workflow: managed

**Comment by srgoogle23** [comment]
just use `import axios from 'axios';`

**Comment by Zweird-958** [comment]
> just use `import axios from 'axios';`

It's imported in this [file](https://github.com/Zweird-958/my-wishlist/blob/feature/mobile/packages/utils/src/api.ts)

**Comment by srgoogle23** [comment]
Sorry, I hadn't taken a look at your code for reproducing the problem. 

I've already gone through this in a project of mine and decided using the meter, with the code below: 

```
config.resolver.unstable_conditionNames = [ 'browser', 'require', 'react-native', ]
```
