### ISSUE TITLE
[expo-camera] When setting ratio to ``16:9`` in expo-camera the resulting image has a ratio of``4:3``

### ISSUE THREAD

**Issue by 0x6D70** [expo/expo#30876]
### Minimal reproducible example

https://github.com/0x6D70/ExpoBugWrongRatio

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

I have set the ratio to ``16:9``, but the resulting image has a size of ``5760x4320`` which is a ratio of ``4:3``.

I have tested this on a physical Android device.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22635
    Binaries:
      Node: 20.1.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10300.40.2321.11567975
    npmPackages:
      expo: ~51.0.24 => 51.0.24
      react: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by alanjhughes** [comment]
@0x6D70 - you'll need to set the ratio prop which was added in #29822 but is not yet published. It will be published soon

**Comment by 0x6D70** [comment]
@alanjhughes I used ``patch-package`` to add the fix (as can be seen in the reproducible example).
I just tested it again with the current main branch of expo, and it does not work.

**Comment by alanjhughes** [comment]
@0x6D70 there were more PRs related to this yesterday. You're better off waiting for this to be published.

**Comment by alanjhughes** [comment]
@0x6D70 ratio relates to the review. If you want to set the size, use the `pictureSize` prop

**Comment by 0x6D70** [comment]
@alanjhughes thanks for the reply
So ``ratio`` is just for the preview? When I'm testing it, the preview is always fullscreen no matter which ratio I set.

Also when setting the ``pictureSize`` prop to 1920x1080 (which is available on my device) the resulting photo has not that size. I think this works in the emulator, but not on a physical android device. I can create a new issue for that problem later.

**Comment by 0x6D70** [comment]
@alanjhughes yes, I tested this on expo go

**Comment by alanjhughes** [comment]
@0x6D70 that's why it doesn't work. You can't change the native code in expo go. Your patches won't have any effect.

**Comment by 0x6D70** [comment]
@alanjhughes the ``ratio`` prop works now correctly.
But when only setting the ``pictureSize`` prop to ``1920x1080`` the final image has a size of ``3024x3024``. Shouldn't the final image size from `takePictureAsync` be `1920x1080` if I set the `pictureSize` prop to that value?
