### ISSUE TITLE
[expo-notifications]  Call to function 'ExpoNotificationChannelManager.setNotificationChannelAsync' has been rejected.

### ISSUE THREAD

**Issue by ekremgunes** [expo/expo#30889]
### Summary

I am using expo-notifications and when i try the get registerforpushnotification i get this and i realized the solving.

```
Error: Call to function 'ExpoNotificationChannelManager.setNotificationChannelAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Could not put 'class [D' to WritableMap

```

docs give us :
```js
if (Platform.OS === 'android') {
    await Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }
```
this is works on expo go but in developmentbuild we are getting error.I thinks vibration pattern makes an error.

my new code:
```js
if (Platform.OS === "android") {
    await Notifications.setNotificationChannelAsync("events", {
      name: "event notifications",
      importance: Notifications.AndroidImportance.MAX
    });
  }

```

Android 11 emulator
Managed
Windows
    "expo": "~51.0.25",
    "react-native": "0.74.5",
    "expo-notifications": "~0.28.15",

last week we didn't get error for the same code lines . After the updates these libraries we saw error.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/notifications/

**Comment by douglowder** [comment]
I'll take a look!

**Comment by douglowder** [comment]
I am not able to reproduce the issue with setting a channel with vibration pattern. I am using `expo-notifications@0.28.15` and getting no error.

I will add other properties and see if any of them trigger the issue you reported.

**Comment by douglowder** [comment]
I would recommend the following:

- Check `node_modules/expo-notifications/package.json` and make sure the version is not `0.28.14`
- Execute `npx expo install expo@^51.0.26 --fix`

**Comment by ekremgunes** [comment]
I was always using the latest version. I tried it 4 days later and it worked. Thanks for your attention. Nevertheless, friends who get similar errors in the coming years can apply this solution.
