### ISSUE TITLE
IOS simulator/device iPad pro 11' (inch) doesn't take whole width/height of the screen

### ISSUE THREAD

**Issue by kadoshms** [expo/expo#3088]
### Environment
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.3.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.6 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: 2.17.0 => 2.17.0 
    npmGlobalPackages:
      expo-cli: 2.6.14
### Steps to Reproduce

1. Open an app with iOS 12.1 simulator, iPad Pro 11' 

### Expected Behavior
The app should be in full width / height (depends on orientation)

### Actual Behavior

There are thick black edges in both sides of the app.

### Reproducible Demo

![rep](https://user-images.githubusercontent.com/5352933/50548871-a5d16980-0c5c-11e9-938b-15bfd269c099.jpg)

**Comment by esamelson** [comment]
Hi @kadoshms - have you set `ios.supportsTablet: true` in your app.json file?

**Comment by kadoshms** [comment]
@easadler yes

**Comment by esamelson** [comment]
@kadoshms - could you create a reproducible demo (ideally a [snack](https://snack.expo.io)) that we can run on our own device/simulator and see the problem? That will make it much easier for us to figure out what's going on and help you out. Thanks!

**Comment by kadoshms** [comment]
@esamelson I am not sure a snack would help since it doesn't support the specific device simulator

**Comment by esamelson** [comment]
@kadoshms - snacks can be run on any device/simulator, not just the Appetize ones embedded in the website. You can use the iPad simulator that comes with Xcode and run the snack on there
