### ISSUE TITLE
Error when installing dependences-  Unexpected identifier 'pipefail' in expo-module-scripts

### ISSUE THREAD

**Issue by pranavbedi** [expo/expo#30897]
### Summary

SyntaxError: Unexpected identifier 'pipefail' in expo-module-scripts
Expo Version: SDK 51
Node Version: v20.11.0
Environment: Windows 11

### Description:
I was trying to run bun install on https://github.com/lukesthl/digital-break-app.git and it throws the error.
While running expo commands, an error occurs in the expo-module-scripts package. The error log is as follows:

```
expo add v1.1.20 (ae194892)
⚙️  @acme/expo-exit-app [3/4] ..,\node_modules\expo-module-scripts\bin\expo-module-prepare:3
set -eo pipefail
        ^^^^^^^^

SyntaxError: Unexpected identifier 'pipefail'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
```

### Steps to Reproduce:

1. Clone https://github.com/lukesthl/digital-break-app.git
2.  Change directory `cd digital-break-app`
3. Run ` bun i `
4. Observe Error

### Expected Behavior:
The package should be added without any errors.

### Actual Behavior:
The command fails with a SyntaxError due to the pipefail identifier in the expo-module-prepare script.

### Additional Context:
This error appears to be related to the set -eo pipefail command in a script being run by Node.js. This syntax is typical in Unix-like shell environments but not supported in Node.js on Windows.

### SDK Version

51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.18034.62.2411.12071903
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/lukesthl/digital-break-app.git

**Comment by brentvatne** [comment]
expo-modules-scripts is currently not compatible with windows, if you'd like to submit a PR to add support for windows it would be welcome! however, nobody at expo that works in this repo uses windows as their primary dev machine

**Comment by aguspignal** [comment]
Is there any alternative?

**Comment by Will-lopesz** [comment]
Hi, did you find any alternative solution to the problem? 
I'm going through the same thing.

**Comment by Nikhilrai1** [comment]
I'm going through the same thing as well.

**Comment by Crhist0** [comment]
also looking for a solution other than change to linux

**Comment by trajano** [comment]
There's a discussion on Discord about it, looks like this won't be reopened anytime soon. https://discord.com/channels/695411232856997968/1308283424326418465/1308452975869562891

**Comment by safinghoghabori** [comment]
I'm going through the same thing. Why is it closed even without a fix? 🙄

**Comment by sushrut619** [comment]
If you are just trying to create a expo native module from template, the following worked for me
```
 npx create-expo-module expo-settings --local
```
