### ISSUE TITLE
[docs] expo-image-picker incompatibility ios and android

### ISSUE THREAD

**Issue by YuriiLutsykSPRO** [expo/expo#30895]
### Summary

There is a small incompatibility between the ios and android. The selected or captured photo object should provide the fileSize field. It works well on ios but it returns the filesize property for the android OS.
Expected value - The property key for both OS should be in camelCase - fileSize
Android - Xiaomi Redmi Note 11
iPhone - XR

### Link to the related docs page

expo-image-picker

**Comment by mrpmohiburrahman** [comment]
Unable to reproduce.
I am getting the "fileSize" on ios too.

I am using "npx create-expo-app@latest" to initialize the project and run that project on expo go..
My Android Device: Redmi Note 12
Android OS: Android 14

**Comment by entiendoNull** [comment]
This issue was fixed here https://github.com/expo/expo/issues/30895
Are you using an outdated version of the package?
