### ISSUE TITLE
Eas update issue after sdk 50 -> 51

### ISSUE THREAD

**Issue by blackwolf08** [expo/expo#30903]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by srgoogle23** [comment]
same problem of https://github.com/expo/expo/issues/30898

**Comment by kitten** [comment]
This has been resolved in `@expo/metro-config@0.18.11`, which was just released.
You can either bump this manually or upgrade to `expo@51.0.26` and run `npx expo install --fix`.
