### ISSUE TITLE
Nested layout outputs incorrect value for window.location.href

### ISSUE THREAD

**Issue by smrubin** [expo/expo#30907]
### Minimal reproducible example

https://github.com/smrubin/expo-debug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Expected:
The value of window.location.href in the nested _layout should be the requested route.

Actual:
The value of window.location.href in the nested _layout is `/`.

--

Tested on the web platform and Chrome as the browser.

I have debugged far enough to know that this only occurs when all of the following are true:
1. The expo app does not render Slot on first render
2. Async routes are enabled
3. The app is built and served (can not reproduce with expo start)

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.17.1 => 0.17.7
      expo: ~50.0.19 => 50.0.19
      expo-router: 3.4.9 => 3.4.9
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
      react-native-web: 0.19.10 => 0.19.10
    npmGlobalPackages:
      eas-cli: 9.0.7
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
It is because you were rendering exporting your app as a Single Page Application. Which means it only has a `index.html` and the routes are controlled via the history API.

In React Navigation, the navigators control the state/history and can change now things are rendered (e.g initial routes). So the URL cannot be determined after the app has rendered. Once rendered, the URL bar is updated. This is why your components see the `href` as `/`.

Expo Router provides the `usePathName()` hook for this reason.

**Comment by nabilfreeman** [comment]
@marklawlor is there an option to not export as a Single Page Application? Apologies if I have misread your post, but it seems like there is a possibility to disable usage of the history API, which would be very very interested in.
