### ISSUE TITLE
[bare-expo] Crashes on Android in release mode with proguard enabled

### ISSUE THREAD

**Issue by janicduplessis** [expo/expo#30901]
### Minimal reproducible example

https://github.com/janicduplessis/expo/tree/%40janic/expo-video-proguard

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

I was trying to create a repro case for a expo-video crash in bare-expo  when proguard is enabled, but turns out the whole app crashes on launch. Not sure if it is the same issue that I was facing with expo-video, but probably best to look at this first.

To repro you can use the provided repro or just set `enableProguardInReleaseBuilds` to true in bare-expo build.gradle then run it in release mode with `npx expo run:android --variant release`.

On a sidenote is there any automated testing around android in release with proguard enabled? In the repo the default is false and I am pretty sure it is not the first time having issues related to that. It might be good to turn it on as these errors usually only end up happening in releases and are harder to catch.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/janicduplessis/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.80.3
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.80.3
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.80.3
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Error: Problems validating fields in /Users/janicduplessis/Developer/expo/apps/bare-expo/app.json. Learn more.
 • should NOT have additional property 'facebookScheme'.
 • should NOT have additional property 'facebookAppId'.
 • should NOT have additional property 'facebookDisplayName'.
 • Field: notification - should NOT have additional property 'serviceWorkerPath'.
 • Field: notification - should NOT have additional property 'vapidPublicKey'.
 • Field: ios - should NOT have additional property 'scheme'.
 • Field: android - should NOT have additional property 'scheme'.

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@8.0.0 - expected version: 8.0.1
  expo@51.0.8 - expected version: ~51.0.25
  expo-camera@15.0.9 - expected version: ~15.0.14
  expo-dev-client@4.0.14 - expected version: ~4.0.21
  expo-image@1.12.9 - expected version: ~1.12.13
  expo-notifications@0.28.3 - expected version: ~0.28.15
  expo-splash-screen@0.27.4 - expected version: ~0.27.5
  react@19.0.0-rc-fb9a90fa48-20240614 - expected version: 18.2.0
  react-dom@19.0.0-rc-fb9a90fa48-20240614 - expected version: 18.2.0
  react-native@0.75.0-rc.5 - expected version: 0.74.5
  react-native-safe-area-context@4.10.7 - expected version: 4.10.5
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by behenate** [comment]
Might be the same as/related to https://github.com/expo/expo/issues/30267, we'll have to make sure

**Comment by janicduplessis** [comment]
That does looks like the expo-video issue I encountered. I think there is still another one affecting bare-expo since I was able to repro it yesterday on last main.

**Comment by janicduplessis** [comment]
I tried to apply the patch from https://github.com/expo/expo/pull/30659 in my app which fixed that error, but now getting a different one

```
TypeError: Cannot read property 'prototype' of undefined

anonymous@1:2663738
useReleasingSharedObject@1:1792005
useVideoPlayer@1:2663705
anonymous@1:2660989
renderWithHooks@1:244626
...
```

Don't have unminified trace, but seems pretty obvious where it comes from.

**Comment by janicduplessis** [comment]
I was able to get it working by also adding

```
-keep class * extends expo.modules.kotlin.sharedobjects.SharedObject
```

in expo-modules-core proguard file.
