### ISSUE TITLE
Cloning the repository

### ISSUE THREAD

**Issue by triplea24** [expo/expo#3090]
This is the current `README.md` instruction:

> Clone this repo; we recommend cloning it to a directory whose full path does not include any spaces.

However, I couldn't build the project as there are some submodules which are needed to be cloned. So I add this bit of instruction to the document.

> Clone this repo; we recommend cloning it to a directory whose full path does not include any spaces (you should clone all the submodules with `git clone --recurse-submodules`, check out more information on git submodules [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules))

You can find my contribution on [triplea24/expo@68c28bd](https://github.com/triplea24/expo/commit/13bb942d93546a0db807215fcda098749dc1df1d).

**Comment by esamelson** [comment]
Thanks for the suggestion @triplea24 ! Could you open a PR on this repo from your fork so that we can get it merged in easily?

**Comment by triplea24** [comment]
@esamelson thanks for your reply. I opened the PR [here](https://github.com/expo/expo/pull/3120).

**Comment by triplea24** [comment]
The PR got merged. I close the issue now.
