### ISSUE TITLE
[docs] expo camera

### ISSUE THREAD

**Issue by CDBridger** [expo/expo#30917]
### Summary

the docs says there is prop for passing active but this doesn't seem to be the case. Can this prop please be added back to the code? (rather than removed from the docs)

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/camera/#active

https://github.com/expo/expo/blob/sdk-51/packages/expo-camera/src/Camera.types.ts

**Comment by entiendoNull** [comment]
The `active`-prop is new and was added to the code only a few days ago (https://github.com/expo/expo/pull/30802).

**Comment by entiendoNull** [comment]
The `active`-prop was recently added (https://github.com/expo/expo/pull/30802).
It seems like docs landed before the change was published.

**Comment by alanjhughes** [comment]
Changes are now available in `15.0.15`
