### ISSUE TITLE
useFonts tips  [Error: Unable to save asset to directory]

### ISSUE THREAD

**Issue by xiaozheqiu** [expo/expo#30921]
### Minimal reproducible example

https://github.com/xiaozheqiu/react-native-demo

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

After I create a project with npx create-expo-app@latest, during the npm start run, 
usefont prompts 
[Error: Unable to save asset to directory: 'file://Users/zheqiu/Library/Developer/CoreSimulator/Devices/488FC908-33AC-43FF-B0B3-05AF3A09074A/data/Containers/Data/Application/5F0B0E32-62FD-4678-80B8-969C5D511CE1/Library/Caches/ExponentExperienceData/@anonymous/online-doctor-consultation-app-1ac06f85-c473-4b24-ba89-3ce0c97660d7/ExponentAsset-49a79d66bdea2debf1832bf4d7aca127 .ttf']

<img width="1283" alt="image" src="https://github.com/user-attachments/assets/e9ef954e-431d-49ca-adfd-4b399f196db7">
<img width="390" alt="image" src="https://github.com/user-attachments/assets/45438d60-e8ce-442a-af90-02162340ff54">

Only on ios emulator has this problem

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.8.1 - /usr/local/bin/npm
      Watchman: 2024.08.05.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.26 => 51.0.26 
      expo-router: ~3.5.21 => 3.5.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by je4ngomes** [comment]
im also having some issues similar related to useFonts, this is the stack erro im getting trying to load any assets and fonts:
`[TypeError: Cannot read property 'uri' of null]
2024-08-09 07:08:44.992 22864-22910 unknown:ReactNative     com.ecglobal.ecglobalapp             E  TypeError: Cannot read property 'uri' of null, stack:
                                                                                                    fromModule@1:825155
                                                                                                    getAssetForSource@1:2081921
                                                                                                    ?anon_0_@1:2079721
                                                                                                    asyncGeneratorStep@1:702634
                                                                                                    _next@1:702892
                                                                                                    anonymous@1:702844
                                                                                                    anonymous@1:702765
                                                                                                    _loadFontInNamespaceAsync@1:2079486
                                                                                                    loadFontInNamespaceAsync@1:2079434
                                                                                                    anonymous@1:2079401
                                                                                                    loadAsync@1:2079252
                                                                                                    anonymous@1:2078562
                                                                                                    commitHookEffectListMount@1:298769
                                                                                                    commitHookPassiveMountEffects@1:303766
                                                                                                    commitPassiveMountOnFiber@1:304217
                                                                                                    recursivelyTraversePassiveMountEffects@1:303851
                                                                                                    commitPassiveMountOnFiber@1:303959
                                                                                                    recursivelyTraversePassiveMountEffects@1:303851
                                                                                                    commitPassiveMountOnFiber@1:304190
                                                                                                    recursivelyTraversePassiveMountEffects@1:303851
                                                                                                    commitPassiveMountOnFiber@1:303959
                                                                                                    recursivelyTraversePassiveMountEffects@1:303851
                                                                                                    commitPassiveMountOnFiber@1:304190
                                                                                                    recursivelyTraversePassiveMountEffects@1:303851
                                                                                                    commitPassiveMountOnFiber@1:303959
                                                                                                    recursivelyTraversePassiveMountEffects@1:303851
                                                                                                    commitPassiveMountOnFiber@1:304172
                                                                                                    flushPassiveEffects@1:311878
                                                                                                    anonymous@1:311700`


```typescript
const [fontsLoaded, error] = useFonts({
		IcoMoon: require('./assets/icomoon/icomoon.ttf'),
	});
	useInitResizeEventHandler();

	useEffect(() => {
		if (fontsLoaded || error) {
			hideAsync();
		}
	}, [fontsLoaded, error]);


	if (!fontsLoaded) {
		if (error) {
			console.error(error);
		}
		return null;
	}
```

**Comment by xiaozheqiu** [comment]
I'm very unhappy, I feel that it has been configured according to the documentation.😭

**Comment by xiaozheqiu** [comment]
> im also having some issues similar related to useFonts, this is the stack erro im getting trying to load any assets and fonts: `[TypeError: Cannot read property 'uri' of null] 2024-08-09 07:08:44.992 22864-22910 unknown:ReactNative com.ecglobal.ecglobalapp E TypeError: Cannot read property 'uri' of null, stack: fromModule@1:825155 getAssetForSource@1:2081921 ?anon_0_@1:2079721 asyncGeneratorStep@1:702634 _next@1:702892 anonymous@1:702844 anonymous@1:702765 _loadFontInNamespaceAsync@1:2079486 loadFontInNamespaceAsync@1:2079434 anonymous@1:2079401 loadAsync@1:2079252 anonymous@1:2078562 commitHookEffectListMount@1:298769 commitHookPassiveMountEffects@1:303766 commitPassiveMountOnFiber@1:304217 recursivelyTraversePassiveMountEffects@1:303851 commitPassiveMountOnFiber@1:303959 recursivelyTraversePassiveMountEffects@1:303851 commitPassiveMountOnFiber@1:304190 recursivelyTraversePassiveMountEffects@1:303851 commitPassiveMountOnFiber@1:303959 recursivelyTraversePassiveMountEffects@1:303851 commitPassiveMountOnFiber@1:304190 recursivelyTraversePassiveMountEffects@1:303851 commitPassiveMountOnFiber@1:303959 recursivelyTraversePassiveMountEffects@1:303851 commitPassiveMountOnFiber@1:304172 flushPassiveEffects@1:311878 anonymous@1:311700`
> 
> ```ts
> const [fontsLoaded, error] = useFonts({
> 		IcoMoon: require('./assets/icomoon/icomoon.ttf'),
> 	});
> 	useInitResizeEventHandler();
> 
> 	useEffect(() => {
> 		if (fontsLoaded || error) {
> 			hideAsync();
> 		}
> 	}, [fontsLoaded, error]);
> 
> 
> 	if (!fontsLoaded) {
> 		if (error) {
> 			console.error(error);
> 		}
> 		return null;
> 	}
> ```

The problem is solved, I just tried to delete the previous build cache.

I think you can try it.

**Comment by je4ngomes** [comment]
Mine was a conflict with the **@react-native/assets-registry** having multiple versions.

**Comment by dipras** [comment]
Please close the issue if you had solved the problem @xiaozheqiu 
Maintener can't close it

**Comment by karol-bisztyga** [comment]
For me it only worked when I did this for simulator: `Device -> Erase all contents and settings`

**Comment by EdenGoforIt** [comment]
I had the same issue.
`
Error loading fonts:  [Error: Unable to save asset to directory: 
`

I tried

✅ If using Mac, Simulator -> Device -> Erase all contents -> this only worked. 
❌ close simulator and restart simulator
❌  npx expo start -c
