### ISSUE TITLE
Convert ImagePicker Into Universal Module

### ISSUE THREAD

**Issue by Szymon20000** [expo/expo#3092]

**Comment by EvanBacon** [comment]
Would you be addressing any of the ImagePicker issues while converting? 😊 #3058 #2925 #2708 #2288 #2020 #1819 #1818 #1522 #1423 #1268 #1132

**Comment by EvanBacon** [comment]
Related #3121

**Comment by esamelson** [comment]
unless any of these issues are really quick & straightforward to fix, let's focus on converting all of the modules to universal modules first and worry about addressing issues later. We have a lot to get through in a short amount of time! 😮

**Comment by aarjae** [comment]
Issue #2288 is actually very very bad and it requires immediate attention
