### ISSUE TITLE
Expo displays the wrong Image

### ISSUE THREAD

**Issue by papidb** [expo/expo#30936]
### Minimal reproducible example

https://github.com/papidb/expo-wrong-image

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

Image isn't displaying right, I created a new app, moved to developmental build and I'm unable to display any image rightly. The image below is meant to be the default expo logo.

<img width="864" alt="Screenshot 2024-08-10 at 15 12 01" src="https://github.com/user-attachments/assets/ca3ed1a8-4928-40f2-9517-3fa7e2a2b5ac">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.26 => 51.0.26 
      expo-router: ~3.5.21 => 3.5.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: bare

### Expo Doctor Diagnostics

None

**Comment by mrpmohiburrahman** [comment]
Unable to reproduce.
When running your code, I can see the default image.

<img width="200" alt="image" src="https://github.com/user-attachments/assets/26b6d93f-f1d7-4fc4-bf26-542dc79b3715">
