### ISSUE TITLE
Metro Build + Cache-Key Collision

### ISSUE THREAD

**Issue by leggomuhgreggo** [expo/expo#30930]
### Summary

After upgrading to Expo SDK 51, and adpting expo web projects from webpack to metro web, we noticed that sometimes one project's build would have environment variables from a different project in the monorepo.

The issue was intermittent and only happened in pipelines with multiple web builds.

We determined that metro was resolving the cached app config, from a previous project's build, because they had the same cache-key.

<img width=700 src=https://github.com/user-attachments/assets/cd0400d3-1f15-4f45-907f-d9ca51e7d7ff />

### Preliminary Explanation + Workaround
It seems like the cache-key is computed based on a hash of the metro config — because our configs were identifical when compiled the cache-key was the same. The workaround was to differentiate the `metro.config.js` files [[repro workaround branch](https://github.com/leggomuhgreggo/metro-web-cache-issue-2024-08-09/tree/workaround)]

<details>
  <summary>Additional Details</summary>

## Findings

When metro is building it compiles and caches modules

> [cacheStores](https://metrobundler.dev/docs/configuration#cachestores) - When Metro needs to transform a module, it first computes a machine-independent cache key for that file, and uses it to try to read from each of the stores in order.

The cache keys for these modules seems to be computed by hashing the project's `metro.config.js` [[code](https://github.com/expo/expo/blob/43a79fb63c909e4770b22c0eae0b8b6a82b8a97a/packages/%40expo/metro-config/src/transform-worker/metro-transform-worker.ts#L737-L758)]

In a monorepo with multiple expo projects, all using identical `metro.config.js` files, this can result in the same cache key being used for multiple projects, which can lead to cache pollution.

For example, if a given pipeline included multiple expo web builds, then whichever project went first would be cached, and subsequent projects would resolve the first project's cached module assets.

In addition to build (expo export) this appears to also be happening when running the dev server.

</details>

<details>
  <summary>Workaround</summary>

### Workaround

If you edit the `metro.config.js` files so that each projects is differentiated, this appears to be sufficient to individualizing the cache keys, avoiding config.

For exampe this works, even though it'd be the same for each project, it differentiates when the `metro.config.js` file is compiled.

```js
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// differentiate metro cache between projects, see: https://metrobundler.dev/docs/configuration#cacheversion
config.cacheVersion = require('./project.json').name;

module.exports = config;
```

But I think even just adding a random key works too

```js
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

config.projectNameCacheKey = 'my project name';

module.exports = config;
```

</details>

### What platform(s) does this occur on?

Web (possibly others, haven't checked)

### SDK Version

51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.asdf/installs/nodejs/18.20.2/bin/node
      Yarn: 1.22.22 - ~/.asdf/shims/yarn
      npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.1 => 0.18.11 
      babel-preset-expo: ~11.0.0 => 11.0.13 
      expo: ~51.0.8 => 51.0.26 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.11 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.3
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/leggomuhgreggo/metro-web-cache-issue-2024-08-09

**Comment by leggomuhgreggo** [comment]
As a possible fix, I'd suggest updating the cache key function so that it includes some way to differentiate by default — maybe based on the file path or project name or something.

**Comment by leggomuhgreggo** [comment]
While investigating the "cross-project cache contamination" bug (ie subject of this issue), another cache-related bug.

The other issue has to do with "sticky app config cache" where changes to the `app.config.js` etc don't make it into the builds. \[ additional details: https://github.com/nrwl/nx/issues/27392#issuecomment-2316550557 \]

Don't mind opening a separate issue if that's easier LMK

**Comment by leggomuhgreggo** [comment]
Pretty sure this is still an issue

**Comment by LovesWorking** [comment]
I'm having this issue... If someone figures this out that would be nice!

**Comment by iffa** [comment]
This is still an issue, unless Metro cache is cleared if you run:
`eas build --local` with profile X and then directly after `eas build --local` with profile Y, Metro will reuse the bundle from the first run even if the change in environment variables would make them different.
