### ISSUE TITLE
Dev Menu not available when building through expo android mobile app

### ISSUE THREAD

**Issue by rajatgng** [expo/expo#3094]
I created fresh react native app using expo by following way:
expo init OTPAuth
cd OTPAuth
expo start

The app get started but when I view the app in my mobile all work fine except when I tried to open Development tool for enabling hot reloading and live reloading it is not opening either by shaking android phone or by long pressing menu button in android app. 

### Environment

expo --version
2.6.14

npm --version
6.4.1

node --version
v10.15.0

###App.js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Hello World!
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

###Package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

**Comment by ardyfeb** [comment]
You are running the production build, try development mode

**Comment by rajatgng** [comment]
> mode

I tried in both mode, it did not work as well.

**Comment by rajatgng** [comment]
@esamelson  i am using lenevo k6 power.

**Comment by esamelson** [comment]
@rajatgng - could you try connecting the device to your computer and running `adb shell input keyevent 82`?

**Comment by webdevbyjoss** [comment]
hey guys,

I've recently faced the same issue and there is how I managed to switch between __DEV__ mode true/false:

1. Make sure you turn the development mode ON in `expo-cli` ( press p in expo-cli console, press ? to check the status)
2. Make sure you refresh the Metro bundler cache (Ctrl + R in expo-cli console)
3. Clean the application data on mobile device/emulator

See more details: https://forums.expo.io/t/toggle-development-mode-on-off-doesnt-work/4803/7

**Comment by rajatgng** [comment]
Issue Rectified I think that was expo version problem that time with new update its working.

**Comment by rajatgng** [comment]
But some times in some project it show the same problem.

**Comment by webdevbyjoss** [comment]
It looks like "some times" is due to reason #3 in my post above.
You are re-installing the app, re-build it, clear Metro bundler cache - but none of these helps.

It's due to Android doesn't cleanups the app data on re-install, and ** __DEV__** flag is cached there.
You need to navigate to Settings => Applications => [[yout app]] => Clean app data to get it sorted out.

**Comment by cmacdonnacha** [comment]
Clearing the cache on the expo client on my device worked for me and restarting `expo start` worked for me.

**Comment by odeke** [comment]
On android, I had to uninstall and re-install the whole expo client on the phone, for the menu to return.
