### ISSUE TITLE
[BUG] Print API - iOS 11.4+

### ISSUE THREAD

**Issue by andresmtz98** [expo/expo#3095]
### Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 31.0.6 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: 3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.6.14

App's target (iOS, Android) 

### Steps to Reproduce

1. Use Print component from 'expo-print' module and set any url with a pdf.
2. Run project on simulator (or real iPhone) with iOS 11.4+ (12.0, 12.1 too)
3. When AirPrint loads the document, zoom in on the document. Then tap the "Printer Options" button to exit the zoom.

### Expected Behavior

What you should expect when you touch the "Printer Options" button to zoom out is to return to the print screen:
![simulator screen shot - iphone 5s - 2019-01-02 at 18 25 09](https://user-images.githubusercontent.com/18200380/50617608-22ae4e80-0ebc-11e9-8be1-3336fd16b79d.png)

### Actual Behavior

In reverse, what happens is that you actually return to the print screen but the "Cancel" and "Print" buttons don't appear. It' s also not possible to leave the print screen because it doesn't allow to do the "back". The only way out is to close the application and reopen it.
![simulator screen shot - iphone 5s - 2019-01-02 at 18 32 55](https://user-images.githubusercontent.com/18200380/50617791-e2030500-0ebc-11e9-935d-73558ead6ed5.png)

It is important to note that iOS version 11.1 does work correctly. I could only test from 11.4 on so I don't know if in versions 11.2, 11.3 and 10- it works correctly or not.

### Reproducible Demo

I couldn't play it with a snack because it couldn't find the "expo-print" module despite adding it in the package.json

You can open the Expo APIs project on your simulator or iPhone and select Print Api: https://expo.io/@community/native-component-list

**Comment by tsapeta** [comment]
Hey @andresmtz98!

Unfortunately, this bug seems to be caused by our internal architecture of view controllers in Expo Client. I've been trying to solve it, but it would break some other things related to modals and alerts. I'm really sorry but we can't fix this in the client right now 😞 

Can you check if that works in standalone app? I believe it works there as expected 😉

**Comment by andresmtz98** [comment]
Morning @tsapeta 
In fact, the bug was found by my boss when he was testing one of the features of the app in which the Print module is used. He has an iPhone 7 with iOS 12.0 and yes, the problem is also in production right now :(, we had to publish the app with that bug.
