### ISSUE TITLE
Expo SDK 51: App hangs if using react-native-v8 engine

### ISSUE THREAD

**Issue by reinismu** [expo/expo#30950]
### Minimal reproducible example

npx create-expo-app@latest + setup react-native-v8

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

On launch App will hang

Before I tried to use it on just bare react-native and it didn't work as well https://github.com/reinismu/ReanimatedV8Deadlock

From my investigation then it seems that V8 wrapper deadlocks when encountered with latest Reanimated lib

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.9 EndeavourOS
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    IDEs:
      Android Studio: AI-241.18034.62.2411.12071903
    npmPackages:
      expo: ~51.0.26 => 51.0.26 
      expo-router: ~3.5.21 => 3.5.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
hi there! the problem is not related to expo, but sorry for late response. i'll try to fix the problem from v8 side.
