### ISSUE TITLE
[EXPO51][metro] Extending the expo metro config, causes RN error

### ISSUE THREAD

**Issue by StefanWallin** [expo/expo#30969]
I accidentally mistook my error to be the same as another, so I'm creating a separate issue to separate out the different issues:

My original issue in #30886 was:

> I'm having the same issue, only on Android, not iOS. Both building on my Mac M1 and on Github Actions ubuntu-latest
> 
> * Mode: `bare`
> * React Native: `0.74.5`
> * expo: `51.0.26`
> * expo-barcode-scanner: `13.0.1`
> * expo-camera: `15.0.14`
> * expo-constants: `16.0.2`
> * expo-linear-gradient: `13.0.2`
> 
> ### Ran: `cd android; ./gradlew clean build`
> ```
> > Task :app:createBundleReleaseJsAndAssets
> Android Bundled 67141ms index.js (2373 modules)
> Error: Serializer did not return expected format. The project copy of `expo/metro-config` may be out of date. Error: Unexpected token v in JSON at position 0
> Error: Serializer did not return expected format. The project copy of `expo/metro-config` may be out of date. Error: Unexpected token v in JSON at position 0
>     at MetroBundlerDevServer._bundleDirectAsync (/Users/me/appproject/app/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:1104:17)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at MetroBundlerDevServer.metroLoadModuleContents (/Users/me/appproject/app/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:442:21)
>     at MetroBundlerDevServer.legacySinglePageExportBundleAsync (/Users/me/appproject/app/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:553:20)
>     at exportEmbedBundleAndAssetsAsync (/Users/me/appproject/app/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:116:21)
>     at exportEmbedAsync (/Users/me/appproject/app/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:68:30)
> 
> > Task :app:createBundleReleaseJsAndAssets FAILED
> ```
> 
> ### My `metro.config.js`
> ```js
> /**
>  * Metro configuration
>  * https://reactnative.dev/docs/metro
>  *
>  * @type {import('metro-config').MetroConfig}
>  */
> const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config')
> 
> const config = {}
> 
> module.exports = mergeConfig(getDefaultConfig(__dirname), config)
> ```

To fix #30886 I tried this by @brentvatne

>  hi there, you should make sure you extend the expo metro config:
> 
> https://github.com/expo/expo/blob/main/templates/expo-template-bare-minimum/metro.config.js
> 
> ```
> // Learn more https://docs.expo.io/guides/customizing-metro
> const { getDefaultConfig } = require('expo/metro-config');
> 
> /** @type {import('expo/metro-config').MetroConfig} */
> const config = getDefaultConfig(__dirname);
> 
> module.exports = config;
> ```
> 
> 
> https://docs.expo.dev/guides/customizing-metro/
> 
_Originally posted by @brentvatne in https://github.com/expo/expo/issues/30886#issuecomment-2284970082_

Which hits upon this issue in RN. Should we extend both or ignore the RN error?

> From React Native 0.73, your project's Metro config should extend '@react-native/metro-config' or it will fail to build. Please copy the template at: https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js

<img width="940" alt="Screenshot of the above metro config not extending the correct config" src="https://github.com/user-attachments/assets/153d2d4a-9cd5-4a20-ad13-146ef64f59d8">

Which was introduced in this issue:
https://github.com/facebook/metro/issues/1018

**Comment by kitten** [comment]
I might be wrong here, but are you mixing the React Native CLI and Expo CLI with the React Native metro and Expo metro configs?

**Comment by StefanWallin** [comment]
It's a bare setup(RN Vanilla originally), with expo libraries added in, and this is my first ever expo upgrade from 0.49 to 0.51. Not intentionally using expo cli, only rn cli

**Comment by kitten** [comment]
If it's not causing any issues to use `@expo/metro-config` with the RN CLI, you can likely continue using it and ignore the warning.

When you use `@react-native/metro-config` with the Expo CLI, I'd assume this ill cause issues. But vice versa (`@expo/metro-config` with the RN CLI) it should build fine. I'm not sure if this a usage mode we're testing for and supporting however, and not sure if there's any pitfalls. But we can cross that bridge if you run into any issues

**Comment by totoledao** [comment]
I am having the same issue with a new project that I just created with `npx create-expo-app`.
The idea was to test some 3D stuff with [Three.js](https://docs.pmnd.rs/react-three-fiber/getting-started/installation#react-native) but as soon as I create a `metro.config.js` file the app crashes with the error:
```
Android Bundling failed 2952ms ...\node_modules\expo-router\entry.js (934 modules)
Unable to resolve "missing-asset-registry-path" from "node_modules\expo-router\assets\file.png"
```

When removing `metro.config.js` the app runs normally again.

**Comment by StefanWallin** [comment]
So when building the app for release on android with metro-config I get this error:

```
> Task :app:createBundleReleaseJsAndAssets
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)

> Task :expo-modules-core:configureCMakeRelWithDebInfo[arm64-v8a]
> Task :expo-modules-core:buildCMakeRelWithDebInfo[arm64-v8a]
> Task :expo-modules-core:configureCMakeRelWithDebInfo[armeabi-v7a]
> Task :expo-modules-core:buildCMakeRelWithDebInfo[armeabi-v7a]
> Task :expo-modules-core:configureCMakeRelWithDebInfo[x86]
> Task :expo-modules-core:buildCMakeRelWithDebInfo[x86]
> Task :expo-modules-core:configureCMakeRelWithDebInfo[x86_64]
> Task :expo-modules-core:buildCMakeRelWithDebInfo[x86_64]

> Task :app:createBundleReleaseJsAndAssets
Android Bundled 235745ms index.js (2373 modules)
Error: Serializer did not return expected format. The project copy of `expo/metro-config` may be out of date. Error: Unexpected token v in JSON at position 0
Error: Serializer did not return expected format. The project copy of `expo/metro-config` may be out of date. Error: Unexpected token v in JSON at position 0
    at MetroBundlerDevServer._bundleDirectAsync (/home/runner/work/app/app/app/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:1104:17)
    at MetroBundlerDevServer.metroLoadModuleContents (/home/runner/work/app/app/app/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:442:21)
    at MetroBundlerDevServer.legacySinglePageExportBundleAsync (/home/runner/work/app/app/app/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:553:20)
    at exportEmbedBundleAndAssetsAsync (/home/runner/work/app/app/app/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:116:21)
    at exportEmbedAsync (/home/runner/work/app/app/app/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:68:30)

> Task :app:createBundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
```

Using `@expo/metro-config` version `0.18.11` according to `package-lock.json:
```
    "node_modules/@expo/metro-config": {
      "version": "0.18.11",
      "resolved": "https://registry.npmjs.org/@expo/metro-config/-/metro-config-0.18.11.tgz",
      "integrity": "sha512-/uOq55VbSf9yMbUO1BudkUM2SsGW1c5hr9BnhIqYqcsFv0Jp5D3DtJ4rljDKaUeNLbwr6m7pqIrkSMq5NrYf4Q==",
...     
```

**Comment by taekeun-two** [comment]
For changing metro config, metro cache should be cleaned thorughly.
https://metrobundler.dev/docs/troubleshooting/
```bash
rm -rf ${TMPDIR:-/tmp}/metro-*
```

For my case, when expo's metro config is used, local build fails.

```
Unable to resolve "./app-banner.db" from "node_modules/...SOMEWHERE_OUR_CODE.../index.js"
```

react-native's metro config is used, local build works, and eas build fails

```
Error: Serializer did not return expected format. The project copy of `expo/metro-config` may be out of date. Error: Unexpected token 'v', "var __BUND"... is not valid JSON
```

I'm not sure that it's the same problem, but I just want to share I've done to fix `unable to resolve module` issue.
https://github.com/expo/expo/issues/30886#issuecomment-2292764835

**Comment by StefanWallin** [comment]
I've now solved this issue, thanks for the help, Not sure what did it exactly. But it seems it did the charm to use the proposed metro-config and ignored the RN-error. But it took a while and I battled a bunch of other issues of my own fault. Not quite sure what at last triggered the success. 
But I did run `npx react-native-clean-project` to be really sure it all was clean in the process...

**Comment by rizwan-gill** [comment]
Facing the same error "react-native 0.76.1" using expo in bare expo: "52.0.6"
**Error:**
BUILD FAILED in 1m 6s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDevelopmentdebug -PreactNativeDevServerPort=8081
(node:95211) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "jsEngine", "ios"
Learn more: https://expo.fyi/root-expo-object
Error: Serializer did not return the expected format. The project copy of `expo/metro-config` may be out of date. Error: Unexpected token v in JSON at position 0
Error: Serializer did not return the expected format. The project copy of `expo/metro-config` may be out of date. Error: Unexpected token v in JSON at position 0 at MetroBundlerDevServer._bundleDirectAsync (/Users/rizwanjavednmx/NMX-WorkSpace/TheHubbub/thehubbub/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:1573:17) at processTicksAndRejections (node:internal/process/task_queues:95:5) at MetroBundlerDevServer.metroLoadModuleContents (/Users/rizwanjavednmx/NMX-WorkSpace/TheHubbub/thehubbub/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:518:21) at MetroBundlerDevServer.legacySinglePageExportBundleAsync (/Users/rizwanjavednmx/NMX-WorkSpace/TheHubbub/thehubbub/node_modules/@expo/cli/src/start/server/metro/MetroBundlerDevServer.ts:809:20) at exportEmbedBundleAndAssetsAsync (/Users/rizwanjavednmx/NMX-WorkSpace/TheHubbub/thehubbub/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:193:21) at exportEmbedInternalAsync (/Users/rizwanjavednmx/NMX-WorkSpace/TheHubbub/thehubbub/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:125:37) at exportEmbedAsync (/Users/rizwanjavednmx/NMX-WorkSpace/TheHubbub/thehubbub/node_modules/@expo/cli/src/export/embed/exportEmbedAsync.ts:105:3) FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':app:createBundleDevelopmentDebugJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1 * Try:
> Run with the --stack trace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 1m 6s.

**metro.config.js**

const path = require('path')
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config')

const defaultConfig = getDefaultConfig(__dirname)
const { assetExts, sourceExts } = defaultConfig.resolver

const config = {
    resetCache: true,
    watchFolders: [
        path.resolve(__dirname),
        path.resolve(__dirname, '../../packages'),
        path.resolve(__dirname, '../../node_modules'),
    ],
    transformer: {
        babelTransformerPath: require.resolve('react-native-svg-transformer/react-native'),
    },
    resolver: {
        assetExts: assetExts.filter((ext) => ext !== 'svg'),
        sourceExts: [...sourceExts, 'svg'],
    },
}

module.exports = mergeConfig(defaultConfig, config)

I'm using mono repo and face this issue only on Android it works on iOS

**Comment by kitten** [comment]
@rizwan-gill Please don't use the React Native CLI's Metro preset with Expo, and instead use Expo's Metro config as a base.

I haven't checked this against SDK52 myself yet, but note how the SVG transformer library you're using has **different** set ups between Expo and the React Native CLI

This is the template they provide for Expo: https://github.com/kristerkari/react-native-svg-expo-example/blob/master/metro.config.js

**Comment by rizwan-gill** [comment]
@kitten I tried this solution this error is gone but the metro bundle does not connect with real devices 
Here are the issues logged in react-native.
[react-native issues](https://github.com/facebook/react-native/issues/47601)

**Comment by mnsrknp** [comment]
@kitten It worked in SDK52 too.
