### ISSUE TITLE
[uni] Make expo-file-system work in an app with bare RN

### ISSUE THREAD

**Issue by ide** [expo/expo#3096]
FS is a dependency of Asset and Print, and Asset is a dependency of Font so we first need FS to work. There are several issues we need to fix with expo-file-system:

1. Methods like `writeAsStringAsync` fail because the FS permissions module (EXFilePermissionModule) is not registered with RN outside of the Expo Client / ExpoKit. Proposed changed: if there is no FS permissions module, don't enforce any permissions. And to ensure we don't accidentally forget to register the FS permissions module for the Expo Client / ExpoKit, we assert that the permissions module is defined each time before we call a method on it in those environments.

2. EXFileSystem adds "ExponentExperienceData" to file paths. We want to provide direct access to the file system where possible so that other libraries that interact with the file system work with paths returned by expo-file-system, without "ExponentExperienceData" added to the path. In standalone apps, ExpoKit apps, and apps with bare RN, we shouldn't add "ExponentExperienceData" to file paths nor scope file paths. (Scoping is needed only in the Expo Client.)

**Comment by tsapeta** [comment]
We should also migrate files from `ExponentExperienceData` to the path without this directory in case someone upgrades from older SDK to the new one that doesn't have this directory.

Also, iirc we want to remove the directory with app slug, right @ide?
