### ISSUE TITLE
Expo camera：Use the scanning function to increase the flash to stay on continuously

### ISSUE THREAD

**Issue by tipbsy** [expo/expo#30988]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by tipbsy** [comment]
In SDK51, the expo barcode scanner has been cancelled. To use the scanning function, I need to use an expo camera. I need to add a constant light flashlight function to ensure that the scanning function can be used normally at night. FlashMode can only turn on the flash when taking photos

**Comment by woshigaokeji** [comment]
I also encountered the same problem. I couldn't turn on the flash when scanning the QR code with expo-camera. Has this problem been solved?
