### ISSUE TITLE
undefined is not an object (evaluating 'ExponentNotifications.getExponentPushTokenAsync')

### ISSUE THREAD

**Issue by CvBlixen** [expo/expo#310]
I have a problem (error message in title) when trying to run my expo (v42.0.0) project on a Genymotion-emulated Android Nexus 5. It seems to be caused by Notifications being imported by registerRootComponent.js, and more specifically by line 132 in Notifications.js:

```javascript
// ...

import { DeviceEventEmitter, NativeModules, Platform } from 'react-native';
const { ExponentNotifications } = NativeModules;

// ...

export default {

  // ...

  // This line causes the error because ExponentNotifications is undefined.
  getExponentPushTokenAsync: ExponentNotifications.getExponentPushTokenAsync,

  // ...

}
```

The full error message is as follows:

```
undefined is not an object (evaluating 'ExponentNotifications.getExponentPushTokenAsync')
<unknown>
    Notifications.js:132:51
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    registerRootComponent.js:8
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
registerRootComponent
    Expo.js:58:19
<unknown>
    crna-entry.js:61:15
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:119:45
_require
    require.js:110:24
global code
```

PS

It works fine on iPhone.

**Comment by CvBlixen** [comment]
I went through my package.json and pushed everything to later versions ... and now it works.

I should have done that from the start. Sorry.

**Comment by ziudeso** [comment]
Hi CvBlixen, I'm having the same issue also but starting a project right from scratch with Expo..
If you got any solution rather than updating package.json please let me know =)
Thanks in advance

**Comment by tomcrusader** [comment]
This occurs on a new project as @ziudeso said, when running on Android simuator.
If later versions are required @CvBlixen ; of what packages? It's high risk of incompatibility to just upgrade all packages.

**Comment by ShawnTe** [comment]
I'm now getting this error as well, after Android working great this past week. I'm nervous about upgrading all packages. Any other insight? Thanks!

**Comment by ide** [comment]
`expo@21.0.3` has been pushed to npm which puts the ExponentNotifications reference into a closure.

**Comment by ShawnTe** [comment]
Thanks, @ide. 

I changed the version in package.json,
then: rm -rf node_modules && npm i
then: reload in ExpoXDE
then: closed/opened Expo on Android

Do I need to do anything else to reset because I get the same error.

**Comment by ide** [comment]
It’s hard to say without knowing more about what code is being loaded and your environment. Can you debug further and go into node_modules to figure out what code is being run?

**Comment by ShawnTe** [comment]
I'd like to say, "Sure!" but that wouldn't be true. Might you provide a suggestion re: how to debug further? It's working on iOS and I've been having a tough time debugging Android as the console.logs don't show up. 

This is our package.json:
`{
  "name": "isleep",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": "Fuzzy Hat Publishing",
  "license": "MIT",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js",
    "test:watch": "node ./node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "^2.0.2",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "expo": "^21.0.3",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-native-collapsible": "^0.9.0",
    "react-native-elements": "^0.16.0",
    "react-navigation": "^1.0.0-beta.12"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "jest-expo": "^20.0.0"
  }
}`

**Comment by ide** [comment]
@ShawnTe the version of the expo package, react-native package, and your expo sdkVersion in app.json need to be compatible with each other. For SDK 21 you want to use

- expo ^21.0.3
- react-native https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
- sdkVersion 21.0.0

**Comment by ziudeso** [comment]
@ide From https://blog.expo.io/expo-sdk-21-0-0-is-now-available-be33b79921b7
```
- react-native to "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz"
- expo to "^21.0.0"
- react did not change from SDK 20("16.0.0-alpha.12")
- jest-expo to "^21.0.0" (if you use it)
- sentry-expo did not change from SDK 20("~1.6.0")
```

**Comment by ide** [comment]
That works too but those release notes are from the time SDK 21 was published, not today. Either way, both of these are semantically different from the package.json posted above.

**Comment by ShawnTe** [comment]
Hey! @ide It's back up on Android! I changed the react-native link to the one you provided for 21.0.2
Thank you!
