### ISSUE TITLE
eas build android with a fresh project not working

### ISSUE THREAD

**Issue by dandrykevych** [expo/expo#31007]
### Summary

Hey guys, 
Just tried to create a project with the latest expo version. Everything is fine: ios/android is running locally but when I try to build the android I still get the errors without adding any additional configs/dependecies.
I've been trying to fix such errors one by one for a week and still can't build a new fresh project.

`[RUN_GRADLEW] > Task :expo-file-system:writeReleaseAarMetadata
[RUN_GRADLEW] > Task :expo-constants:writeReleaseAarMetadata
[RUN_GRADLEW] > Task :expo-font:writeReleaseAarMetadata
[RUN_GRADLEW] > Task :app:processReleaseMainManifest FAILED
[RUN_GRADLEW] Incorrect package="MY_PACKAGE" found in source AndroidManifest.xml: /private/var/folders/mf/fpsqjswn0hdgdf17cg_g1kqr0000gn/T/eas-build-local-nodejs/b8170134-8d18-42f5-b4de-292ced53d130/build/android/app/src/main/AndroidManifest.xml.
[RUN_GRADLEW] Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
[RUN_GRADLEW] Recommendation: remove package="MY_PACKAGE" from the source AndroidManifest.xml: /private/var/folders/mf/fpsqjswn0hdgdf17cg_g1kqr0000gn/T/eas-build-local-nodejs/b8170134-8d18-42f5-b4de-292ced53d130/build/android/app/src/main/AndroidManifest.xml.
[RUN_GRADLEW] > Task :app:mergeReleaseResources
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:processReleaseMainManifest'.
[RUN_GRADLEW] > Incorrect package="MY_PACKAGE" found in source AndroidManifest.xml: /private/var/folders/mf/fpsqjswn0hdgdf17cg_g1kqr0000gn/T/eas-build-local-nodejs/b8170134-8d18-42f5-b4de-292ced53d130/build/android/app/src/main/AndroidManifest.xml.
[RUN_GRADLEW]   Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
[RUN_GRADLEW]   Recommendation: remove package="MY_PACKAGE" from the source AndroidManifest.xml: /private/var/folders/mf/fpsqjswn0hdgdf17cg_g1kqr0000gn/T/eas-build-local-nodejs/b8170134-8d18-42f5-b4de-292ced53d130/build/android/app/src/main/AndroidManifest.xml.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 34s
[RUN_GRADLEW] 53 actionable tasks: 53 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.`

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

`expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.1 - /opt/homebrew/opt/node@20/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.26 => 51.0.27
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 10.2.3
      expo-cli: 6.3.10
    Expo Workflow: bare`

### Minimal reproducible example

npx create-expo-app APP --template blank
eas build or eas build --platform android --local

**Comment by brentvatne** [comment]
hi there! if you can try to reproduce this on eas build and share the url for a build page we can look into this further. i am unable to reproduce using the steps provided - both with a local build and remote.

**Comment by dandrykevych** [comment]
> hi there! if you can try to reproduce this on eas build and share the url for a build page we can look into this further. i am unable to reproduce using the steps provided - both with a local build and remote.

Hi, the errors is the same for eas build. I can't share a libk to a build because you have no access I suppose. Here the gradlew logs, hope this is enough:

`
Running 'gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-8.8-all.zip
10%.
20%.
30%.
40%.
50%.
60%.
70%.
80%.
90%.
100%
Welcome to Gradle 8.8!
Here are the highlights of this release:
 - Running Gradle on Java 22
 - Configurable Gradle daemon JVM
 - Improved IDE performance for large projects
For more details see https://docs.gradle.org/8.8/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.8/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build
> Task :gradle-plugin:settings-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:settings-plugin:pluginDescriptors
> Task :gradle-plugin:settings-plugin:processResources
> Task :gradle-plugin:settings-plugin:compileKotlin
> Task :gradle-plugin:settings-plugin:compileJava
NO-SOURCE
> Task :gradle-plugin:settings-plugin:classes
> Task :gradle-plugin:settings-plugin:jar
> Task :gradle-plugin:react-native-gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:react-native-gradle-plugin:pluginDescriptors
> Task :gradle-plugin:react-native-gradle-plugin:processResources
> Task :gradle-plugin:react-native-gradle-plugin:compileKotlin
> Task :gradle-plugin:react-native-gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:react-native-gradle-plugin:classes
> Task :gradle-plugin:react-native-gradle-plugin:jar
> Configure project :expo
Using expo modules
  - [32mexpo-asset[0m (10.0.10)
  - [32mexpo-constants[0m (16.0.2)
  - [32mexpo-file-system[0m (17.0.1)
  - [32mexpo-font[0m (12.0.9)
  - [32mexpo-keep-awake[0m (13.0.2)
  - [32mexpo-modules-core[0m (1.12.21)
> Task :expo-asset:preBuild UP-TO-DATE
> Task :expo-asset:preReleaseBuild UP-TO-DATE
> Task :expo-asset:generateReleaseResValues
> Task :expo-asset:generateReleaseResources
> Task :expo-asset:packageReleaseResources
> Task :expo-file-system:preBuild UP-TO-DATE
> Task :expo-file-system:preReleaseBuild UP-TO-DATE
> Task :expo-file-system:generateReleaseResValues
> Task :expo-file-system:generateReleaseResources
> Task :expo-constants:createExpoConfig
APP_ENV undefined
> Task :expo-constants:preBuild
> Task :expo-constants:preReleaseBuild
> Task :expo-constants:generateReleaseResValues
> Task :expo-file-system:packageReleaseResources
> Task :expo-constants:generateReleaseResources
> Task :expo-font:preBuild UP-TO-DATE
> Task :expo-font:preReleaseBuild UP-TO-DATE
The NODE_ENV environment variable is required but was not specified. Ensure the project is bundled with Expo CLI or NODE_ENV is set.
Proceeding without mode-specific .env
> Task :expo-font:generateReleaseResValues
> Task :expo-font:generateReleaseResources
> Task :expo-font:packageReleaseResources
> Task :expo-keep-awake:preBuild UP-TO-DATE
> Task :expo-keep-awake:preReleaseBuild UP-TO-DATE
> Task :expo:generateExpoModulesPackageListTask
> Task :expo:preBuild
> Task :expo:preReleaseBuild
> Task :expo-keep-awake:generateReleaseResValues
> Task :expo-keep-awake:generateReleaseResources
> Task :expo-constants:packageReleaseResources
> Task :expo-modules-core:preBuild UP-TO-DATE
> Task :expo-modules-core:preReleaseBuild UP-TO-DATE
> Task :expo-modules-core:generateReleaseResValues
> Task :expo-modules-core:generateReleaseResources
> Task :expo:generateReleaseResValues
> Task :expo:generateReleaseResources
> Task :expo-keep-awake:packageReleaseResources
> Task :expo-modules-core:packageReleaseResources
> Task :expo-asset:extractDeepLinksRelease
> Task :expo-constants:extractDeepLinksRelease
> Task :expo:packageReleaseResources
> Task :expo:extractDeepLinksRelease
> Task :expo-constants:processReleaseManifest
> Task :expo-file-system:extractDeepLinksRelease
> Task :expo-asset:processReleaseManifest
> Task :expo-font:extractDeepLinksRelease
> Task :expo-font:processReleaseManifest
> Task :expo-keep-awake:extractDeepLinksRelease
> Task :expo:processReleaseManifest
> Task :expo-modules-core:extractDeepLinksRelease
> Task :expo-keep-awake:processReleaseManifest
> Task :expo-modules-core:processReleaseManifest
/home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/AndroidManifest.xml:8:9-11:45 Warning:
	meta-data#com.facebook.soloader.enabled@android:value was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present
> Task :expo-asset:writeReleaseAarMetadata
> Task :expo:writeReleaseAarMetadata
> Task :expo-constants:writeReleaseAarMetadata
> Task :expo-file-system:writeReleaseAarMetadata
> Task :expo-keep-awake:writeReleaseAarMetadata
> Task :expo-font:writeReleaseAarMetadata
> Task :expo-file-system:processReleaseManifest
/home/expo/workingdir/build/node_modules/expo-file-system/android/src/main/AndroidManifest.xml:6:9-8:20 Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
> Task :expo-modules-core:writeReleaseAarMetadata
> Task :expo-asset:compileReleaseLibraryResources
> Task :expo-asset:parseReleaseLocalResources
> Task :expo-constants:compileReleaseLibraryResources
> Task :expo-asset:generateReleaseRFile
> Task :expo-constants:parseReleaseLocalResources
> Task :expo-constants:generateReleaseRFile
> Task :expo:compileReleaseLibraryResources
> Task :expo:parseReleaseLocalResources
> Task :expo-file-system:compileReleaseLibraryResources
> Task :expo:generateReleaseRFile
> Task :expo-file-system:parseReleaseLocalResources
> Task :expo-file-system:generateReleaseRFile
> Task :expo-font:compileReleaseLibraryResources
> Task :expo-font:parseReleaseLocalResources
> Task :expo-keep-awake:compileReleaseLibraryResources
> Task :expo-keep-awake:parseReleaseLocalResources
> Task :expo-font:generateReleaseRFile
> Task :expo-modules-core:compileReleaseLibraryResources
> Task :expo:checkKotlinGradlePluginConfigurationErrors
> Task :expo:generateReleaseBuildConfig
> Task :expo-asset:checkKotlinGradlePluginConfigurationErrors
> Task :expo-asset:generateReleaseBuildConfig
> Task :expo-modules-core:checkKotlinGradlePluginConfigurationErrors
> Task :expo-modules-core:generateReleaseBuildConfig
> Task :expo-keep-awake:generateReleaseRFile
> Task :expo-modules-core:javaPreCompileRelease
> Task :expo-constants:checkKotlinGradlePluginConfigurationErrors
> Task :expo-constants:generateReleaseBuildConfig
> Task :expo-constants:javaPreCompileRelease
> Task :expo-file-system:checkKotlinGradlePluginConfigurationErrors
> Task :expo-file-system:generateReleaseBuildConfig
> Task :expo-modules-core:parseReleaseLocalResources
> Task :expo-asset:javaPreCompileRelease
> Task :expo-font:checkKotlinGradlePluginConfigurationErrors
> Task :expo-font:generateReleaseBuildConfig
> Task :expo-modules-core:generateReleaseRFile
> Task :expo-file-system:javaPreCompileRelease
> Task :expo-keep-awake:checkKotlinGradlePluginConfigurationErrors
> Task :expo-keep-awake:generateReleaseBuildConfig
> Task :expo-font:javaPreCompileRelease
> Task :expo:javaPreCompileRelease
> Task :expo-keep-awake:javaPreCompileRelease
> Task :expo-asset:mergeReleaseShaders
> Task :expo-asset:compileReleaseShaders NO-SOURCE
> Task :expo-asset:generateReleaseAssets UP-TO-DATE
> Task :expo:mergeReleaseShaders
> Task :expo:compileReleaseShaders NO-SOURCE
> Task :expo:generateReleaseAssets UP-TO-DATE
> Task :expo-asset:packageReleaseAssets
> Task :expo:packageReleaseAssets
> Task :expo-constants:mergeReleaseShaders
> Task :expo-constants:compileReleaseShaders NO-SOURCE
> Task :expo-constants:generateReleaseAssets UP-TO-DATE
> Task :expo-constants:packageReleaseAssets
> Task :expo-file-system:mergeReleaseShaders
> Task :expo-file-system:compileReleaseShaders NO-SOURCE
> Task :expo-file-system:generateReleaseAssets UP-TO-DATE
> Task :expo-file-system:packageReleaseAssets
> Task :expo-font:mergeReleaseShaders
> Task :expo-font:compileReleaseShaders NO-SOURCE
> Task :expo-font:generateReleaseAssets UP-TO-DATE
> Task :expo-font:packageReleaseAssets
> Task :expo-keep-awake:mergeReleaseShaders
> Task :expo-keep-awake:compileReleaseShaders NO-SOURCE
> Task :expo-keep-awake:generateReleaseAssets UP-TO-DATE
> Task :expo-keep-awake:packageReleaseAssets
> Task :expo:mergeReleaseJniLibFolders
> Task :expo:mergeReleaseNativeLibs NO-SOURCE
> Task :expo:copyReleaseJniLibsProjectOnly
> Task :expo-asset:mergeReleaseJniLibFolders
> Task :expo-asset:mergeReleaseNativeLibs NO-SOURCE
> Task :expo-asset:copyReleaseJniLibsProjectOnly
> Task :expo-constants:mergeReleaseJniLibFolders
> Task :expo-constants:mergeReleaseNativeLibs NO-SOURCE
> Task :expo-constants:copyReleaseJniLibsProjectOnly
> Task :expo-file-system:mergeReleaseJniLibFolders
> Task :expo-file-system:mergeReleaseNativeLibs NO-SOURCE
> Task :expo-file-system:copyReleaseJniLibsProjectOnly
> Task :expo-font:mergeReleaseJniLibFolders
> Task :expo-font:mergeReleaseNativeLibs NO-SOURCE
> Task :expo-font:copyReleaseJniLibsProjectOnly
> Task :expo-keep-awake:mergeReleaseJniLibFolders
> Task :expo-keep-awake:mergeReleaseNativeLibs NO-SOURCE
> Task :expo-keep-awake:copyReleaseJniLibsProjectOnly
> Task :expo:prepareReleaseArtProfile
> Task :expo-asset:prepareReleaseArtProfile
> Task :expo-constants:prepareReleaseArtProfile
> Task :expo-file-system:prepareReleaseArtProfile
> Task :expo-font:prepareReleaseArtProfile
> Task :expo-keep-awake:prepareReleaseArtProfile
> Task :app:createBundleReleaseJsAndAssets
APP_ENV undefined
APP_ENV undefined
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
APP_ENV undefined
> Task :expo-modules-core:mergeReleaseShaders
> Task :expo-modules-core:compileReleaseShaders NO-SOURCE
> Task :expo-modules-core:generateReleaseAssets UP-TO-DATE
> Task :expo-modules-core:packageReleaseAssets
> Task :expo-modules-core:configureCMakeRelWithDebInfo[arm64-v8a]
Checking the license for package CMake 3.22.1 in /home/expo/Android/Sdk/licenses
License for package CMake 3.22.1 accepted.
Preparing "Install CMake 3.22.1 v.3.22.1".
"Install CMake 3.22.1 v.3.22.1" ready.
Installing CMake 3.22.1 in /home/expo/Android/Sdk/cmake/3.22.1
"Install CMake 3.22.1 v.3.22.1" complete.
"Install CMake 3.22.1 v.3.22.1" finished.
> Task :expo-modules-core:compileReleaseKotlin
> Task :app:createBundleReleaseJsAndAssets
Android Bundled 17748ms node_modules/expo/AppEntry.js (540 modules)
Writing bundle output to: /home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
Writing sourcemap output to: /home/expo/workingdir/build/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
Done writing bundle output
Done writing sourcemap output
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:767:63: warning: Direct call to eval(), but lexical scope is not supported.
...typeof expo === "undefined" ? eval("require") : function (moduleId) {
                                 ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:3366:16: warning: the variable "SharedArrayBuffer" was not declared in function "from"
    if (typeof SharedArrayBuffer !== 'undefined' && (isInstance(value, Shared...
               ^~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:7358:18: warning: the variable "DebuggerInternal" was not declared in function "__shouldPauseOnThrow"
          typeof DebuggerInternal !== 'undefined' &&
                 ^~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:19579:7: warning: the variable "setTimeout" was not declared in function "logCapturedError"
      setTimeout(function () {
      ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:17689:31: warning: the variable "nativeFabricUIManager" was not declared in anonymous function " 376#"
  var _nativeFabricUIManage = nativeFabricUIManager,
                              ^~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:17717:21: warning: the variable "clearTimeout" was not declared in anonymous function " 376#"
    cancelTimeout = clearTimeout;
                    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:22347:30: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in anonymous function " 376#"
  if ("undefined" !== typeof __REACT_DEVTOOLS_GLOBAL_HOOK__) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:23904:5: warning: the variable "setImmediate" was not declared in function "handleResolved"
    setImmediate(function () {
    ^~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
:27943:5: warning: the variable "fetch" was not declared in anonymous function " 590#"
    fetch,
    ^~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27944:5: warning: the variable "Headers" was not declared in anonymous function " 590#"
    Headers,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27945:5: warning: the variable "Request" was not declared in anonymous function " 590#"
    Request,
    ^~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27946:5: warning: the variable "Response" was not declared in anonymous function " 590#"
    Response
    ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28103:24: warning: the variable "FileReader" was not declared in function "readBlobAsArrayBuffer"
      var reader = new FileReader();
                       ^~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28154:36: warning: the variable "Blob" was not declared in anonymous function " 601#"
        } else if (support.blob && Blob.prototype.isPrototypeOf(body)) {
                                   ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28156:40: warning: the variable "FormData" was not declared in anonymous function " 601#"
        } else if (support.formData && FormData.prototype.isPrototypeOf(body)) {
                                       ^~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28158:44: warning: the variable "URLSearchParams" was not declared in anonymous function " 601#"
...e if (support.searchParams && URLSearchParams.prototype.isPrototypeOf(body...
                                 ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28277:26: warning: the variable "AbortController" was not declared in anonymous function " 607#"
          var ctrl = new AbortController();
                         ^~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:28411:23: warning: the variable "XMLHttpRequest" was not declared in anonymous function " 611#"
        var xhr = new XMLHttpRequest();
                      ^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:27956:71: warning: the variable "self" was not declared in anonymous function " 593#"
...undefined' && globalThis || typeof self !== 'undefined' && self ||
                                      ^~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:31973:27
: warning: the variable "performance" was not declared in anonymous function " 768#"
if ("object" === typeof performance && "function" === typeof performance.no...
^~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
:
31996
:
26
:
warning:
the variable "navigator" was not declared in anonymous function " 768#"
"undefined" !== typeof navigator && undefined !== navigator.scheduling && u...
^~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
:
32106
:
37
:
warning:
the variable "MessageChannel" was not declared in anonymous function " 768#"
};else if ("undefined" !== typeof MessageChannel) {
^~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:32121:34: warning: the variable "nativeRuntimeScheduler" was not declared in anonymous function " 768#"
... = "undefined" !== typeof nativeRuntimeScheduler ? nativeRuntimeScheduler....
                             ^~~~~~~~~~~~~~~~~~~~~~
/home/expo/workingdir/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle:43905:34: warning: the variable "requestAnimationFrame" was not declared in function "start 9#"
...    this._animationFrame = requestAnimationFrame(this.onUpdate.bind(this));
                              ^~~~~~~~~~~~~~~~~~~~~
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preReleaseBuild
> Task :app:generateReleaseResValues
> Task :app:processReleaseGoogleServices
> Task :app:mapReleaseSourceSetPaths
> Task :app:generateReleaseResources
> Task :app:mergeReleaseResources
/home/expo/.gradle/caches/8.8/transforms/051411f9064baceaa3611501df9d076f/transformed/media-1.0.0/res/values/values.xml:2:4: Invalid <color> for given resource value.
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease
> Task :app:mergeReleaseResources FAILED
> Task :app:processReleaseMainManifest
/home/expo/workingdir/build/android/app/src/main/AndroidManifest.xml Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present
> Task :expo-modules-core:compileReleaseKotlin
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:20:26 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:63:51 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:90:54 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/defaultmodules/CoreModule.kt:6:34 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/defaultmodules/CoreModule.kt:70:12 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/events/KModuleEventEmitterWrapper.kt:97:7 'constructor Event<T : Event<(raw) Event<*>>!>(Int)' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverterHelper.kt:44:17 'get(String!): Any?' is deprecated. Deprecated in Java
> Task :expo-modules-core:buildCMakeRelWithDebInfo[arm64-v8a]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile values resource file /home/expo/workingdir/build/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@4bdc4599.). Check logs for more details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 2m 53s
133 actionable tasks: 133 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
`

**Comment by ankitkhaire20** [comment]
any answers for these I am facing the same issue...
