### ISSUE TITLE
`router.setParams` cannot delete a search param if the route you navigated from is a child of a different navigator.

### ISSUE THREAD

**Issue by trcoffman** [expo/expo#31009]
### Minimal reproducible example

https://github.com/trcoffman/expo-router-setparams-bug

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hi there. I've found an issue in the `router.setParams` API that only appears when navigating between routes that are in different navigators.

Consider the following component: https://github.com/trcoffman/expo-router-setparams-bug/blob/master/app/(tabs)/index.tsx
```typescript
export default function Page1() {
  const { query } = useGlobalSearchParams<{ query?: string }>();

  useFocusEffect(
    useCallback(() => {
      console.log("useFocusEffect ", query);
      const id = setTimeout(() => {
        router.setParams({ query: undefined });
      }, 1000);
      return () => clearTimeout(id);
    }, [query])
  );
  
  // ...
  // superfluous JSX
  // ...
}
```

Expected:
1 second after this screen comes back into focus, the component should rerender and the `query` search param is undefined.

Observed:
When the component rerenders, `query` is unchanged. This bug only occurs if the route that we navigated from is a child of the Stack navigator, and not the Tab navigator. The repository also includes an identical page at the `/workingPage` route that is also in the tab navigator. When we navigate back to `/` from that page, deleting the `query` search param works just fine.

This is problematic for our apps because we use modals that are children of the root Stack navigator to do something, and they return data to the route that spawned them by using search params. Once we trigger an animation that was triggered by that search param, we want to delete it.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.9
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.asdf/installs/nodejs/18.19.1/bin/node
      Yarn: 1.22.18 - ~/.asdf/shims/yarn
      npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/tyler.coffman/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.26 => 51.0.28
      expo-router: ~3.5.21 => 3.5.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 7.8.5
    Expo Workflow: managed

**Comment by trcoffman** [comment]
Can you reopen this issue?

**Comment by dahed92** [comment]
I have the same problem, the reset params works but not in the return of useFocusEffect
