### ISSUE TITLE
EAS IOS Fastlane error

### ISSUE THREAD

**Issue by Lyubomir-Stavrev-Dev** [expo/expo#31013]
### Summary

Im using nx monorepo with expo and nativewind:

In the cli I am having an error:

❌  error: src/global.css: A jest worker process (pid=7005) was terminated by another process: signal=SIGTERM, exitCode=null. Operating system logs may contain more information on why this occurred.

▸ ** BUILD FAILED **

▸ The following build commands failed:

▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/workingdir/build/apps/mobile/ios/build/Build/Intermediates.noindex/Mobile.build/Release-iphonesimulator/Mobile.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'Mobile' from project 'Mobile')

▸ (1 failure)

** BUILD FAILED **

here is the whole thing: https://expo.dev/accounts/lyubomir-stavrev/projects/mobile/builds/751ac140-6303-4732-8e52-66773efe0b0f

my metro config: 
```ts

const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');
const { FileStore } = require('metro-cache');
const path = require('path');

// Get the default Expo Metro configuration
const defaultConfig = getDefaultConfig(__dirname);

// Add FontAwesome configuration to the Metro config
function withFontAwesome(config) {
  const { transformer, resolver } = config;

  return {
    ...config,
    transformer: {
      ...transformer,
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      ...resolver,
      assetExts: resolver.assetExts.filter((ext) => ext !== 'svg'),
      sourceExts: [...resolver.sourceExts, 'svg'],
    },
  };
}

// Add the NX monorepo paths to the Metro config
function withNXMonorepoPaths(config) {
  const projectRoot = __dirname;
  const workspaceRoot = path.resolve(projectRoot, '../../');

  return {
    ...config,
    watchFolders: [workspaceRoot], // Watch all files in the monorepo
    resolver: {
      ...config.resolver,
      nodeModulesPaths: [
        path.resolve(projectRoot, 'node_modules'),
        path.resolve(workspaceRoot, 'node_modules'),
      ],
      disableHierarchicalLookup: true, // Force resolving nested modules to specific folders
    },
  };
}

// Move the Metro cache to the `node_modules/.cache/metro` folder
function withNXManagedCache(config) {
  return {
    ...config,
    cacheStores: [
      new FileStore({ root: path.join(__dirname, 'node_modules/.cache/metro') })
    ],
  };
}

// Combine all custom configurations with the default Expo config
module.exports = withNXManagedCache(
  withNXMonorepoPaths(
    withNativeWind(
      withFontAwesome(defaultConfig),
      { input: './src/global.css' }
    )
  )
);


```

{
  "name": "udoma-mobile-app",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "nx serve mobile",
    "android": "nx run mobile:run-android",
    "android-logcat": "nx run mobile:run-android & adb logcat",
    "ios": "nx run mobile:run-ios",
    "web": "nx run mobile:serve --platform=web",
    "ts:check": "nx run mobile:ts:check",
    "eslint-fix": "nx run mobile:eslint-fix",
    "prettier-fix": "nx run mobile:prettier-fix"
  },
  "dependencies": {
    "@awesome.me/kit-83842e231f": "^1.0.22",
    "@babel/plugin-transform-react-jsx": "^7.25.2",
    "@babel/runtime": "^7.25.0",
    "@expo/metro-runtime": "^3.2.1",
    "@fortawesome/free-solid-svg-icons": "^6.6.0",
    "@fortawesome/pro-regular-svg-icons": "^6.6.0",
    "@fortawesome/pro-solid-svg-icons": "^6.6.0",
    "@fortawesome/react-native-fontawesome": "^0.3.2",
    "@fortawesome/sharp-solid-svg-icons": "^6.6.0",
    "@hookform/resolvers": "^3.9.0",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/datetimepicker": "^8.0.1",
    "@react-native-community/geolocation": "^3.3.0",
    "@react-native/assets-registry": "^0.74.87",
    "@rneui/themed": "4.0.0-rc.8",
    "axios": "^1.7.3",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "date-fns": "^3.6.0",
    "dayjs": "^1.11.12",
    "expo": "51.0.14",
    "expo-asset": "^10.0.10",
    "expo-auth-session": "^5.5.2",
    "expo-camera": "~15.0.14",
    "expo-constants": "^16.0.2",
    "expo-document-picker": "^12.0.2",
    "expo-font": "^12.0.9",
    "expo-image-picker": "~15.0.7",
    "expo-linking": "~6.3.1",
    "expo-localization": "^15.0.3",
    "expo-location": "^17.0.1",
    "expo-modules-core": "^1.12.21",
    "expo-router": "~3.5.21",
    "expo-secure-store": "~13.0.2",
    "expo-splash-screen": "^0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-web-browser": "^13.0.3",
    "i18n-js": "^4.4.3",
    "jwt-decode": "^4.0.0",
    "metro-cache": "^0.80.10",
    "nativewind": "^4.0.14",
    "nprogress": "^0.2.0",
    "plugin": "link:@nx/expo/plugin",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.52.2",
    "react-native": "0.74.5",
    "react-native-css-interop": "^0.0.34",
    "react-native-maps": "^1.14.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-svg-transformer": "^1.5.0",
    "react-native-ui-datepicker": "^2.0.3",
    "react-native-web": "~0.19.12",
    "tailwind-merge": "^2.4.0",
    "yup": "^1.4.0"
  },
  "devDependencies": {
    "@nx/devkit": "19.5.7",
    "@nx/eslint-plugin": "19.5.7",
    "@nx/expo": "19.5.7",
    "@nx/jest": "19.5.7",
    "@nx/playwright": "19.5.7",
    "@playwright/test": "^1.46.0",
    "@swc-node/register": "~1.10.9",
    "@swc/core": "~1.7.10",
    "@testing-library/jest-native": "~5.4.3",
    "@types/jest": "^29.5.12",
    "@types/lodash": "^4.17.7",
    "@types/node": "22.2.0",
    "@types/nprogress": "^0.2.3",
    "@types/react": "~18.2.79",
    "@types/react-native-datepicker": "^1.7.6",
    "@typescript-eslint/eslint-plugin": "^8.0.1",
    "@typescript-eslint/parser": "^8.0.1",
    "babel-jest": "^29.7.0",
    "babel-preset-expo": "~11.0.13",
    "eslint": "^9.9.0",
    "eslint-config-expo": "^7.1.2",
    "eslint-config-import": "^0.13.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jsx-a11y": "6.9.0",
    "eslint-plugin-playwright": "^1.6.2",
    "eslint-plugin-prettier": "^5.2.1",
    "eslint-plugin-react": "7.35.0",
    "eslint-plugin-react-hooks": "4.6.2",
    "eslint-plugin-unused-imports": "^4.0.1",
    "jest": "^29.7.0",
    "jest-expo": "~51.0.3",
    "nx": "19.5.7",
    "prettier": "^3.3.3",
    "react-test-renderer": "18.3.1",
    "tailwindcss": "^3.3.2",
    "typescript": "~5.3.3"
  },
  "private": true
}

### Environment

.

### Minimal reproducible example

.

**Comment by brentvatne** [comment]
https://docs.expo.dev/build-reference/troubleshooting/

**Comment by brentvatne** [comment]
also, the first thing i would do in your project is look at the expo doctor warnings and address those
