### ISSUE TITLE
Android development build doesn't work with new archiecture

### ISSUE THREAD

**Issue by WKampel** [expo/expo#31018]
### Minimal reproducible example

https://github.com/WKampel/expo-issue

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Create a brand new project:
`npx create-expo-app test --template blank`

Generate a development build following this guide:
https://docs.expo.dev/develop/development-builds/create-a-build/

The development build works.

Enable new arch. following this guide:
https://docs.expo.dev/guides/new-architecture/

Generate a new development build.

The build does not work on Android.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.7.0 - /usr/local/bin/npm
      Watchman: 2024.04.29.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 7.5.0
      expo-cli: 6.3.10

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

Error: Problem validating fields in /Users/wyatt/Documents/PlatformNow/test/test/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: android/versionCode - must be integer.

This project has native project folders but also has config plugins, indicating it is configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

One or more checks failed, indicating possible issues with the project.

**Comment by WKampel** [comment]
The error that is produced:

TypeError: Cannot read property 'NativeModule' of undefined, stack:
anonymous@800:166
....(more anonymous stuff)

**Comment by erickriva** [comment]
Adding more info about this error:
https://github.com/expo/expo/blob/7be64725f7fe865af8c4f847754e1d0d298fb77e/packages/expo-modules-core/build/NativeModule.js#L3
`globalThis.expo` is undefined.

**Comment by mr-tm** [comment]
Same here.
![image](https://github.com/user-attachments/assets/caa26ba0-00dc-4a59-98b5-88f4c5e42cfe)

**Comment by oblador** [comment]
It seems latest (`51.0.28`) is aimed at 0.75, downgrading to `51.0.26` solves this issue for me.

**Comment by erickriva** [comment]
> It seems latest (`51.0.28`) is aimed at 0.75, downgrading to `51.0.26` solves this issue for me.

I've tried 51.0.28 with 0.75 and it seems to throw the same error. Downgrading worked here too.

**Comment by ilyadynin** [comment]
do you mean react-native 0.75?

**Comment by WKampel** [comment]
React native 0.75 fixed it for me as well.

**Comment by WKampel** [comment]
Downgrading Expo to 51.0.26 fixed it for me as well.

**Comment by cjones26** [comment]
+1, downgrading Expo for now, but yeah it's broken and only works ~25% of the time.

**Comment by bitfrost** [comment]
had to do the same

**Comment by adsalihac** [comment]
i just done this , but i got iOS pod installation issue , auto linking is not working this version (51.0.26)

**Comment by jingp-ofload** [comment]
+1 here

**Comment by DavidAmyot** [comment]
+1

**Comment by numandev1** [comment]
I am getting the same error with expo `51.0.30` and react-native `0.75.2`

**Comment by desonyuan** [comment]
+1

**Comment by alanjhughes** [comment]
Resolved in #31122

**Comment by gabrieldonadel** [comment]
The fix for this has just been published in `expo-modules-core@1.12.23`!

Please run `npx expo install --fix` to get the latest versions of our libraries

**Comment by DavidAmyot** [comment]
This fixed it for me! However, I had to do `yarn add expo@latest` since my expo version was 1 version behind and `npx expo install --fix` wouldn't upgrade the actual expo version but just the dependencies.

Thank you 🙂

**Comment by billomore** [comment]
@gabrieldonadel had this issue on `expo-modules-core@1.12.26` and old arch.. looks like another issue, but downgrading `expo` to 51.0.26 (`expo-modules-core` 1.12.20), as @oblador suggested worked for me. 

"react-native": 0.74.5

**Comment by manfye** [comment]
im still having such issue even i downgraded to 51.0.26 =(
