### ISSUE TITLE
native module not compatible

### ISSUE THREAD

**Issue by youssef-elmweb** [expo/expo#31030]
### Minimal reproducible example

https://github.com/expo/expo/issues/28545

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Hello,
i updated my project expo in new SDK 51.0.28 and i have a problem of compatibility in my source when i throw expo-doctor,

I've been on it for a week I managed to delete 2 errors because there were three at the beginning but I can't get this last one I tried everything
npx expo install...but things are getting worse

Detailed check results:

Expected package expo-modules-autolinking@~1.11.0
Found invalid:
  expo-modules-autolinking@1.2.0
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@7.8.4
  @expo/config-plugins@6.0.2
  @expo/config-plugins@7.8.4
  @expo/config-plugins@4.1.5
  @expo/config-plugins@6.0.2
  @expo/config-plugins@6.0.2
  @expo/config-plugins@6.0.2
  @expo/config-plugins@6.0.2
  @expo/config-plugins@6.0.2
  @expo/config-plugins@6.0.2
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~7.0.0
Found invalid:
  @expo/prebuild-config@6.7.3
  @expo/prebuild-config@6.0.1
  (for more info, run: npm why @expo/prebuild-config)
Expected package @expo/metro-config@~0.18.11
Found invalid:
  @expo/metro-config@0.6.0
  @expo/metro-config@0.7.1
  (for more info, run: npm why @expo/metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

One or more checks failed, indicating possible issues with the project.

even when I update the files as stipulated on the error message (expo-modules-autolinking@~1.11.0, @expo/config-plugins@~8.0.0 ...) with yarn or npm new errors appear in addition to the original error message (✖ Check that native modules use compatible support package versions for installed Expo SDK)

THOSE ERRORS IS :
✖ Check for common project setup issues
✖ Check that packages match versions required by installed Expo SDK
✖ Check for legacy global CLI installed locally

Thank you very mush for help,
Cordialy.

### Environment

youssef@MacBook-Pro-de-youssef pipingdata % sudo npx expo-env-info
Password:
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.7.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.15.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.8.2 - /usr/local/bin/npm
      Watchman: 2024.07.15.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.18.10 => 0.18.11 
      expo: ^51.0.28 => 51.0.28 
      react: ^18.2.0 => 18.2.0 
      react-native: ^0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 10.2.3
      expo-cli: 6.3.12
    Expo Workflow: managed

### Expo Doctor Diagnostics

youssef@MacBook-Pro-de-youssef pipingdata % sudo npx expo-doctor@latest
Password:
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by CMonjo** [comment]
Same issue here !

**Comment by Vcky4** [comment]
I have the same issue, could you fix or workaround yet?

**Comment by PatrickWatson887** [comment]
Same issue here

**Comment by Nirmal0210** [comment]
Have any of you tried running:
**npm why @expo/config-plugins**

I was facing a compatibility issue because one of the packages was using an outdated version of @expo/config-plugins. Running this command helped me trace the issue to the expo-facebook package, which I ultimately had to remove to resolve the problem.
