### ISSUE TITLE
Bun 1.1.24 can't run expo project 

### ISSUE THREAD

**Issue by leosilberg** [expo/expo#31043]
### Summary

`bun expo start`

causes the following output

```
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
› Detected a change in babel.config.js. Restart the server to see the new results. You may need to clear the bundler cache with the --clear flag for your changes to take effect.
TypeError [ERR_INVALID_ARG_TYPE]: The "streamReadable" argument must be an stream.Readable. Received an instance of Pipeline
TypeError: The "streamReadable" argument must be an stream.Readable. Received an instance of Pipeline
    at new NodeError (node:stream:420:19)
    at newReadableStreamFromStreamReadable (node:stream:2527:41)
    at new Response (node-fetch:48:13)
    at new NFCResponse (C:\Users\...\my-project\node_modules\@expo\cli\build\src\api\rest\cache\response.js:21:8)  
    at C:\Users\...\my-project\node_modules\@expo\cli\src\api\rest\cache\wrapFetchWithCache.ts:194:7
    at processTicksAndRejections (unknown:12:39)
error: script "android" exited with code 1
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      expo: ~51.0.8 => 51.0.28
      expo-router: ~3.5.23 => 3.5.23
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.75.1 => 0.75.1
      react-native-web: ~0.19.12 => 0.19.12
    Expo Workflow: managed

### Steps to reproduce

```
git clone https://github.com/mrzachnugent/react-native-reusables.git

cp -R react-native-reusables/apps/starter-base/ ./my-project

cd my-project && bun install

bun run web
```

**Comment by byCedric** [comment]
Hi @leosilberg! Thanks for opening an issue. The error you sent indicates that the cache Expo uses for API requests (like validating the dependency versions) is somehow corrupted. I don't think this is related to Bun `1.1.24`.

You could try wiping the local cache (_and signing you out of your account_) by removing the `.expo` folder in your home directory.
  - On MacOS / Linux - this is `~/.expo`
  - On Windows - this is something like `C:\Users\<username\.expo`

Wiping this should resolve these corrupted caches. Hope this helps!

**Comment by leosilberg** [comment]
Hi 

I had to install node and npm to get expo running, it seems that expo isn't compatible with bun independent of node. Is there any timeline planned to integrate just the bun runtime?

**Comment by brentvatne** [comment]
@leosilberg - Expo tooling generally works with Bun, but it could be possible that new changes to Bun occasionally cause regressions (as you can imagine, Bun doesn't run the test suite for every piece of software in the world when they change something). We will fix issues when we see them. As far as I can see in the issue reported in this thread, it is not actually an issue with Bun or Expo tooling but rather with caches.

If you run into specific issues with Bun, please create a new issue with a minimal reproducible example!
