### ISSUE TITLE
SplashScreen does not appear after updating project to use sdk>50

### ISSUE THREAD

**Issue by gabriel-logan** [expo/expo#31046]
### Minimal reproducible example

https://github.com/gabriel-logan/ExpoSplashScreenNotShowing

manual splash screen setup

https://github.com/gabriel-logan/ExpoSplashScreenNotShowing/tree/manualset

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

With sdk <50 Everything works and I didn't change anything, I just updated the sdk. In dev mode it appears fine but the playstore aab doesn't appear. Apk too.

In production everything works OK, only the problem is that the splash doesn't appear.
I've already tried analyzing the logcat etc.

https://discord.com/channels/695411232856997968/1274557376585797642
There is every conversation on discord showing my steps

The splash only appears when I make it appear manually using the library expo-splash-screen

I created this test repo to demonstrate using the default create-expo-app template.

note: WITHOUT EXPO-ROUTER

and I'm having this problem.

### Environment

 npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.2, 34.0.0
        System Images: android-31 | Google Play Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    npmPackages:
      expo: ~51.0.28 => 51.0.28
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    Expo Workflow: managed

### Expo Doctor Diagnostics

npx expo-doctor@latest
Need to install the following packages:
expo-doctor@1.9.1
Ok to proceed? (y) y

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by gabriel-logan** [comment]
### 

> [`_****_`](url)

**Comment by gabriel-logan** [comment]
..........

**Comment by nico-locket** [comment]
did you manage to solve this? experiencing the same issue unless I add SplashScreen.show to MainActivity, which should be deprecated behavior.

**Comment by gabriel-logan** [comment]
> did you manage to solve this? experiencing the same issue unless I add SplashScreen.show to MainActivity, which should be deprecated behavior.

The best solution is to never make any serious and complex app with expo, always use React Native Cli.

Now speaking of expo, the "solution" I found was to use the expo-splash-screen lib and manually set the time the splash appears, then just create a fake promise of 500ms or however long you want, and after the promise ends, then you hide the splash screen.

After MANY problems I never did anything with expo again and I have been headache-free for several weeks, as you can see, with THOUSANDS of issues no one answered this one, so I don't know how it is today. If my comments helped you, I'm happy.

**Comment by gabriel-logan** [comment]
Aqui pra expo: traduz ai 🖕.
