### ISSUE TITLE
[docs] Missing information about expo export --public-url alternatives

### ISSUE THREAD

**Issue by petemusicpancake** [expo/expo#31051]
### Summary

Since Expo SDK 49, I've been using expo export --public-url, which outputs a dist folder with android/ios-index.json. I then deployed the dist folder to S3 and generated a QR code pointing to the URL exps://my-host/android-index.json. Everything was working fine; Expo Go successfully opened my build. However, since version 51, I’m encountering the error: "Legacy manifests are no longer supported."

It seems that Expo SDK 51 made changes to how manifest.json is parsed in Expo Go, but unfortunately, I couldn’t find any information about this in the Expo documentation.

What are the new alternatives to expo export --public-url?
How to properly host and read manifest in Expo Go?

### Link to the related docs page

https://docs.expo.dev/more/expo-cli/#exporting

**Comment by kbqdev** [comment]
Do you solve it?
