### ISSUE TITLE
Unmet peer dependency with create-expo-app 

### ISSUE THREAD

**Issue by ZuluNovember** [expo/expo#31055]
### Summary

Following the tutorial in the https://docs.expo.dev/tutorial/create-your-first-app/ results in unmet peer dependency error.

I've managed the solve the issue by upgrading react to 18.3.1 and react-native to 0.75.0.

This issue shouldn't be happening with the package versions in the main branch. I tried to dig a little deeper and understand where does the cli command source the template but I wasn't able to understand how it works. I assume it should be a simple issue for the more experienced people here.

### SDK Version

51.0.28

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.local/state/fnm_multishells/30009_1724071248430/bin/node
      npm: 10.8.1 - ~/.local/state/fnm_multishells/30009_1724071248430/bin/npm
      Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.28 
      react: 18.2.0 => 18.3.1 
      react-dom: ^18.2.0 => 18.3.1 
      react-native: 0.74.5 => 0.75.0 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Minimal reproducible example

Following the [introduction tutorial](https://docs.expo.dev/tutorial/create-your-first-app/) results in unmet peer dependency error.

I created the project with the command
```
npx create-expo-app StickerSmash --template blank && cd StickerSmash
```

Following the tutorial:
```
npx expo install react-dom react-native-web @expo/metro-runtime
```
This command results with the following error:
```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: expo-template-blank@51.0.27
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.3.1" from react-dom@18.3.1
npm error node_modules/react-dom
npm error   react-dom@"^18.2.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/enizcoban/.npm/_logs/2024-08-19T12_53_11_612Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/enizcoban/.npm/_logs/2024-08-19T12_53_11_612Z-debug-0.log
Error: npm install exited with non-zero code: 1
```

**Comment by Kudo** [comment]
hi there! thanks for sharing this problem. we've fixed the problem. please try to run `npx expo install react-dom react-native-web @expo/metro-runtime` again and that should work now.
