### ISSUE TITLE
Back button missing on iOS but present on Android

### ISSUE THREAD

**Issue by snios** [expo/expo#31063]
### Minimal reproducible example

https://github.com/snios/router-err-sample

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Expected behavior is that it works the same way on both Android and iOS.

In this sample app if you on Android device go to the "Machine 1" page  you will have a back button to get back to the previous screen (as I would expect)

On iOS however when going to the Machine 1 page you do not get a back button.

I do think that this happens probably mostly becouse of that there are multiple stacks (but that should be supported?) and also the behavior should be consistent between the two platforms in any way.

Phones "back" gesture works as expected even tough the back button is missing.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      expo: ~51.0.28 => 51.0.28
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed

**Comment by Aryan-Sood** [comment]
Its weird that the next page - about machine page shows the back button but the machine page doesn't.

**Comment by Aryan-Sood** [comment]
I tried to implement a custom button on header which makes you go back to prev screen and it show up and work.

**Comment by snios** [comment]
> I tried to implement a custom button on header which makes you go back to prev screen and it show up and work.

Yes. This is only a minimal example to show the issue. We have our own custom back button on iOS aswell as long as this issue is present.

**Comment by Aryan-Sood** [comment]
I tried to create a new expo app and try recreating this kinda app. It works in my case. I have used different folder structure as I am a little confused by yours and I am not that proficient with nested navigation.

I think you can take a look at this and maybe figure out what's not working in your case. 
https://github.com/Aryan-Sood/Expo-issue-back-button

**Comment by snios** [comment]
> I tried to create a new expo app and try recreating this kinda app. It works in my case. I have used different folder structure as I am a little confused by yours and I am not that proficient with nested navigation. Most probably it has something to do with the wrong combination of header being shown on the screens.
> 
> I think you can take a look at this and maybe figure out what's not working in your case. https://github.com/Aryan-Sood/Expo-issue-back-button
> 
>  trim.BFB917F8-E14D-4094-BEF2-245DB9672BE4.MOV

This issue is with file based routing [Expo routing](https://docs.expo.dev/develop/file-based-routing/) You are not using that in your example.

**Comment by Aryan-Sood** [comment]
> > I tried to create a new expo app and try recreating this kinda app. It works in my case. I have used different folder structure as I am a little confused by yours and I am not that proficient with nested navigation. Most probably it has something to do with the wrong combination of header being shown on the screens.
> 
> > 
> 
> > I think you can take a look at this and maybe figure out what's not working in your case. https://github.com/Aryan-Sood/Expo-issue-back-button
> 
> > 
> 
> >  trim.BFB917F8-E14D-4094-BEF2-245DB9672BE4.MOV
> 
> 
> 
> This issue is with file based routing [Expo routing](https://docs.expo.dev/develop/file-based-routing/) You are not using that in your example. And it is also about the inconsistency between the two platforms iOS and Android.

Ok i will try it that way

**Comment by alanjhughes** [comment]
@snios This is the default behaviour on iOS. The first screen in a stack does not have a back button. If you want to have it there you need to implement it yourself as you have done.

**Comment by snios** [comment]
> @snios This is the default behaviour on iOS. The first screen in a stack does not have a back button. If you want to have it there you need to implement it yourself as you have done.

As in by design in expo, react-navigation or iOS as operating system? 
Why would you like inconsistency in the header?  The back swipe works normal on iOS and takes you back to the main screen, only the header does not show it.

**Comment by Aryan-Sood** [comment]
I won't call it an inconsistency because swipe back usually allows you to go back to previous screen irrespective of the type of navigation being used whereas the back button on header is only for stack based navigation. 
It references to the previous item in the stack and naturally won't appear on the first page of the stack

**Comment by snios** [comment]
> I won't call it an inconsistency because swipe back usually allows you to go back to previous screen irrespective of the type of navigation being used whereas the back button on header is only for stack based navigation. It references to the previous item in the stack and naturally won't appear on the first page of the stack

In that case we would have to agree to disagree then. It beeing present on Android and not in iOS for the same navigation is inconsistent in my book.

**Comment by alanjhughes** [comment]
@snios its not an inconsistency. It's just the default behaviour on each respective platform. React natives goal is not to mask over differences between platforms.

In any case, this is implemented by react-navigation and react-native-screens so we can't change it. I'm going to close this as there is nothing really to be done from our side.

**Comment by rcpankaj** [comment]
This is inconsistent, @alanjhughes. Do you have an example that demonstrates what you're saying? The back button does not appear in one-level navigation on iOS, but it works on Android.

**Comment by alanjhughes** [comment]
@rcpankaj as already mentioned, these behaviours are implemented in `react-native-screens` and `react-navigation`. This is the default platform behaviour. Differences like this are common between iOS and Android.

**Comment by rcpankaj** [comment]
> [@rcpankaj](https://github.com/rcpankaj) as already mentioned, these behaviours are implemented in `react-native-screens` and `react-navigation`. This is the default platform behaviour. Differences like this are common between iOS and Android.

@alanjhughes I'm just asking Do you have any good application names that implement this and leave it as the default behavior?
