### ISSUE TITLE
expo updates build fails with react native 0.75 

### ISSUE THREAD

**Issue by imranbarbhuiya** [expo/expo#31075]
### Minimal reproducible example

https://github.com/expo/examples

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Use any examples from the example repo, bump deps and create a development build
Using expo updates with react native 0.75 fails with the below error

```sh
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':expo-updates:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
* Try:
> Run with --stacktrace
option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 7m 41s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
880 actionable tasks: 879 executed, 1 up-to-date
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22635
    Binaries:
      Node: 20.16.0 - ~\AppData\Local\fnm_multishells\20920_1724150501080\node.EXE
      Yarn: 4.4.0 - ~\AppData\Local\fnm_multishells\20920_1724150501080\yarn.CMD
      npm: 10.8.1 - ~\AppData\Local\fnm_multishells\20920_1724150501080\npm.CMD
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Unsupported on New Architecture: @gorhom/bottom-sheet
Untested on New Architecture: @pusher/pusher-websocket-react-native
Unmaintained: react-native-modal, react-native-parsed-text
No metadata available: @expo-google-fonts/inter, @expo/metro-config, @hookform/resolvers, dayjs, expo-dev-client, openapi-fetch, react-native-animated-dots-carousel, react-native-headless-mention, react-native-otp-verify, react-native-typing-animation, zod
Advice:
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

The following packages should be updated for best compatibility with the installed expo version:
  react-native-pager-view@6.3.4 - expected version: 6.3.0
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by yoannHertienne** [comment]
I'm getting the same after the upgrade of React Native to 0.75.1 with following error on Android compile:

`node_modules/expo-updates/android/src/main/java/expo/modules/updates/errorrecovery/ErrorRecovery.kt:12:38 Unresolved reference: DisabledDevSupportManager
node_modules/expo-updates/android/src/main/java/expo/modules/updates/errorrecovery/ErrorRecovery.kt:115:31 Unresolved reference: DisabledDevSupportManager
node_modules/expo-updates/android/src/main/java/expo/modules/updates/errorrecovery/ErrorRecovery.kt:121:7 'handleException' overrides nothing
node_modules/expo-updates/android/src/main/java/expo/modules/updates/errorrecovery/ErrorRecovery.kt:149:33 Unresolved reference: DisabledDevSupportManager`

**Comment by imranbarbhuiya** [comment]
closing as a duplicate of https://github.com/expo/expo/issues/31069 sorry I searched using the error msg so it didn't match the ss present in that issue

**Comment by MoosaZK** [comment]
Any update what is causing this isse:
Validate packages against React Native Directory package metadata

**Comment by shridhar0021** [comment]
"expo": {
    "doctor": {
      "reactNativeDirectoryCheck": {
        "exclude": ["@hookform/resolvers", "moment", "yup"],
        "listUnknownPackages": false
      }
    }
  }

u can updates in package json @hookform/resolvers", "moment", "yup package names

**Comment by emimaricic** [comment]
> "expo": { "doctor": { "reactNativeDirectoryCheck": { "exclude": ["@hookform/resolvers", "moment", "yup"], "listUnknownPackages": false } } }
> 
> u can updates in package json @hookform/resolvers", "moment", "yup package names

✖ Check Expo config (app.json/ app.config.js) schema
Error validating fields in /home/emkaa/posao/go-cierge-all/go-cierge-mobile/app.json:
 should NOT have additional property 'doctor'.
Apperently not working anymore
