### ISSUE TITLE
[expo-camera] ``pictureSize`` prop does not work

### ISSUE THREAD

**Issue by 0x6D70** [expo/expo#31077]
### Minimal reproducible example

https://github.com/0x6D70/ExpoBug

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

When  setting the ``pictureSize`` prop to ``1920x1080`` the final image has a different resolution.

For example on my Android device the final image with ``pictureSize`` set to ``1920x1080`` has a resolution of ``3024x3024``

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22635
    Binaries:
      Node: 20.1.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10300.40.2321.11567975
    npmPackages:
      expo: ~51.0.25 => 51.0.26
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by 0x6D70** [comment]
@alanjhughes I tested it again with the new fix and now the image has a size of ``1440x1080``. It is closer to ``1920x1080``, but still not the resolution I selected.

**Comment by alanjhughes** [comment]
@0x6D70 as mentioned in the PR you won't always get the best me you selected. It depends on the device hardware. Android will select the closest possible.

**Comment by alanjhughes** [comment]
They seem to give back the same sizes for every device and then pick the best available on a case by case basis. The goal of CameraX is to cover the wide range of cameras available on Android. The older apis were a nightmare to work with. They have traded granularity of options for maximum compatibility.

**Comment by alanjhughes** [comment]
@0x6D70 say they didn't do this and you picked a resolution that is only available on 60% of devices. How would you handle the others that can't support it?

**Comment by 0x6D70** [comment]
@alanjhughes I don't know what the best solution would be, but I think that there should be some way to check what is available so the resolution can be selected dynamically. I also think that when ``getAvailablePictureSizesAsync`` lists some resolution as available, that it should be used when taking the photo. Also in my opinion keeping the same ratio is much more important when picking the closest available resolution.

For my use case I also would be happy, if I just could use some higher resolution and then resize the image afterwards. But sadly ``ImageManipulator`` removes all the exif data, which I need.

Everything I need some way to create a photo with a ratio of 16:9, exif data and the size of the image should not be to large (max. 3 MB).
