### ISSUE TITLE
Can't use Touchable inside ExpoRouter + RN Modal 

### ISSUE THREAD

**Issue by dflourusso** [expo/expo#31082]
### Minimal reproducible example

https://github.com/dflourusso/expo-router-modal-debug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

No touchable can be pressed if I open a react-native Modal inside a expo-router screen. (Only for ios. Android is working fine)

https://github.com/user-attachments/assets/cc2af0a1-19dd-4fcd-92bc-0df51e72e909

https://github.com/user-attachments/assets/f444488b-2b73-451a-8f47-f0c2fac118d1

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.07.29.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.29
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 9.0.6
    Expo Workflow: managed

**Comment by dflourusso** [comment]
Looks like something with the environment. Tested in other computer/simulators and it's working fine

**Comment by AndrzejMachnikDacDigital** [comment]
Did you found out the issue with the environment? After all I get the same error (same simulator and very similar expo/react native version) and Im not sure changing my simulator should be the solution (tried to erase all content and didnt work)

**Comment by dflourusso** [comment]
Yes, I tried deleting the content and it didn't work either. But after restarting the computer the problem went away.
