### ISSUE TITLE
Error Report in Expo

### ISSUE THREAD

**Issue by edgarscr** [expo/expo#31086]
### Summary

Dear Expo Team,
I hope this message finds you well. I would like to report an error that I have been experiencing while developing my application using Expo.
Error Description
When trying to run my project, I receive the following error message:

```
Error: Unable to resolve module ./Libraries/Image/Image from App/node_modules/react-native/index.js: 
None of these files exist:
* node_modules/react-native/Libraries/Image/Image(.native.ts|.ts|.native.tsx|.tsx|.native.mjs|.mjs|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.cjs|.cjs|.native.scss|.scss|.native.sass|.sass|.native.css|.css|.native.jsx|.jsx|.native.js|.js|.native.ts|.ts|.native.tsx|.tsx)
* node_modules/react-native/Libraries/Image/Image/index(.native.ts|.ts|.native.tsx|.tsx|.native.mjs|.mjs|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.cjs|.cjs|.native.scss|.scss|.native.sass|.sass|.native.css|.css|.native.jsx|.jsx|.native.js|.js|.native.ts|.ts|.native.tsx|.tsx)
```

### SDK Version

51.0.28

### Environment

"dependencies": {
"@expo/config-plugins": "~8.0.0",
"@expo/prebuild-config": "~7.0.0",
"@expo/vector-icons": "^14.0.0",
"@react-native-async-storage/async-storage": "1.23.1",
"@react-native-community/netinfo": "11.3.1",
"@react-native-firebase/analytics": "^20.3.0",
"@react-native-firebase/app": "^20.3.0",
"@react-native-firebase/crashlytics": "^20.3.0",
"@react-native-firebase/perf": "^20.3.0",
"@react-navigation/drawer": "^6.5.0",
"@react-navigation/native": "^6.0.12",
"@react-navigation/native-stack": "^6.8.0",
"@react-navigation/stack": "^6.3.3",
"@reduxjs/toolkit": "^1.9.5",
"axios": "^0.27.2",
"depcheck": "^1.4.3",
"expo": "~51.0.28",
"expo-application": "~5.9.1",
"expo-asset": "~10.0.6",
"expo-build-properties": "~0.12.5",
"expo-constants": "~16.0.2",
"expo-dev-client": "~4.0.23",
"expo-device": "~6.0.2",
"expo-insights": "~0.7.0",
"expo-keep-awake": "~13.0.1",
"expo-linking": "~6.3.1",
"expo-notifications": "~0.28.15",
"expo-secure-store": "~13.0.2",
"expo-splash-screen": "~0.27.5",
"expo-status-bar": "~1.12.1",
"expo-store-review": "~7.0.2",
"expo-updates": "~0.25.22",
"moment": "^2.29.4",
"native-base": "^3.4.28",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.74.5",
"react-native-base64": "^0.2.1",
"react-native-crypto-js": "^1.0.0",
"react-native-dropdown-picker": "^5.4.4",
"react-native-gesture-handler": "~2.16.1",
"react-native-maps": "1.14.0",
"react-native-reanimated": "~3.10.1",
"react-native-responsive-screen": "^1.4.2",
"react-native-safe-area-context": "4.10.5",
"react-native-screens": "3.31.1",
"react-native-store-version": "^1.4.1",
"react-native-svg": "15.2.0",
"react-native-toast-notifications": "^3.4.0",
"react-native-uuid": "^2.0.2",
"react-native-webview": "13.8.6",
"react-redux": "^8.1.2",
"redux": "^4.2.1",
"redux-persist": "^6.0.0",
"redux-thunk": "^2.4.2",
"typescript": "~5.3.3"
},
"devDependencies": {
"@babel/core": "^7.24.0",
"@types/react": "~18.2.79",
"@types/react-native-base64": "^0.2.0",
"@types/react-native-crypto-js": "^1.0.0",
"eslint": "^8.56.0",
"prettier": "^3.2.4"
},
"private": true,
"resolutions": {
"styled-components": "^5"
},
"overrides": {
"@expo/config-plugins": "~8.0.0",
"@expo/prebuild-config": "~7.0.0"
}

### Minimal reproducible example

i just use an image

**Comment by manssorr** [comment]
Hello! I have same issue as you.

**Comment by AmahAjavon** [comment]
same issue here with expo 51

**Comment by jacarrara** [comment]
Check the imports statements. Maybe the IDE imports from "@/node_modules/...". I solved removing this string.

**Comment by edgarscr** [comment]
I have tried several answers here but my problem still appears.

**Comment by natalyayyad** [comment]
same issue here

**Comment by Dcrosssensei** [comment]
same issue here
