### ISSUE TITLE
React Native 0.75: in expo-dev-client Causes Build Failure | ShadowTreeRevisionConsistencyManager

### ISSUE THREAD

**Issue by t16n** [expo/expo#31092]
### Summary

While attempting to build a project using expo-dev-client, the build fails due to a missing header file: 'react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h'. This issue occurs during the compilation of the RuntimeScheduler.h file. Additionally, a minor warning regarding an HTML tag in the CdpJson.h file was observed, but it does not cause the build to fail.

Steps to reproduce:

Add expo-dev-client to the project.
Attempt to build the project using Xcode with a Debug configuration.
Observe the build failure due to the missing header file.
Expected behavior:
The project should build successfully without missing header file errors.

### Hint
It probably has to do with `expo-build-properties` and `useFrameworks": "static"`

```
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ],

```

### Error

```

Error:
'react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h' file not found

Details:
The file RuntimeScheduler.h is trying to include ShadowTreeRevisionConsistencyManager.h, but it cannot be found in the framework react.

Warning:
HTML tag 'code' requires an end tag. This occurs in CdpJson.h at line 88.
```

_Additional Info:_
When removing the  expo-dev-client from the project (package.json) the ios build goes thru just fine.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Environment

xpo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 3.6.4 - ~/.nvm/versions/node/v18.18.0/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.14 => 51.0.29 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.75.2 => 0.75.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.4
    Expo Workflow: bare

### Reproducible demo

https://github.com/t16n/rn-75-expo-dev-client-issue

### Stacktrace (if a crash is involved)

Build target: expo-dev-menu of project Pods with configuration Debug

CompileC
/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/arm64/DevClientRootViewFactory.o
/node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm
normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'expo-dev-menu' from project 'Pods')
cd /ios/Pods
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /SDKStatCaches.noindex/iphonesimulator17.5-21F77-c098706a9f71eba4e76ae92ab367209a.sdkstatcache -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fno-color-diagnostics -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Index.noindex/DataStore -Wno-comma -Wno-shorten-64-to-32 @/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_CFG_NO_COROUTINES=1 -Wno-comma -Wno-shorten-64-to-32 -DREACT_NATIVE_TARGET_VERSION=75 -DUSE_HERMES -include /Pods/Target\ Support\ Files/expo-dev-menu/expo-dev-menu-prefix.pch -MMD -MT dependencies -MF /Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/arm64/DevClientRootViewFactory.d --serialize-diagnostics /Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/arm64/DevClientRootViewFactory.dia -c /node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm -o /Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/arm64/DevClientRootViewFactory.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/expo-dev-menu.build/Objects-normal/arm64/DevClientRootViewFactory.o

In file included from
/node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm:15:
/node_modules/react-native/ReactCommon/hermes/executor/HermesExecutorFactory.h:11:
/node_modules/react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.h:10:
/node_modules/react-native/ReactCommon/jsiexecutor/jsireact/JSINativeModules.h:13:
/node_modules/react-native/ReactCommon/cxxreact/ModuleRegistry.h:14:
/node_modules/react-native/ReactCommon/cxxreact/JSExecutor.h:16:
/jsinspector_modern.framework/Headers/jsinspector-modern/ReactCdp.h:11:
/jsinspector_modern.framework/Headers/jsinspector-modern/FallbackRuntimeTargetDelegate.h:11:
/jsinspector_modern.framework/Headers/jsinspector-modern/RuntimeTarget.h:15:
/jsinspector_modern.framework/Headers/jsinspector-modern/RuntimeAgent.h:10:
/jsinspector_modern.framework/Headers/jsinspector-modern/CdpJson.h:88:37:
Warning: HTML tag 'code' requires an end tag [-Wdocumentation-html]
* {"id": <id>, "error": { "code": <code>, "message": <message> }}

In file included from
/node_modules/expo-dev-menu/ios/DevClientRootViewFactory.mm:19:
/React_runtimescheduler.framework/Headers/react/renderer/runtimescheduler/RuntimeScheduler.h:11:10:
Fatal Error: 'react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h' file not found
#include <react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/React_runtimescheduler.framework/Headers/react/renderer/runtimescheduler/RuntimeScheduler.h:11:10:
Note: did not find header 'renderer/consistency/ShadowTreeRevisionConsistencyManager.h' in framework 'react' (loaded from /Build/Products/Debug-iphonesimulator/React-Core)
1 warning and 1 error generated.

/React_runtimescheduler.framework/Headers/react/renderer/runtimescheduler/RuntimeScheduler.h:11:10:
'react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h' file not found

**Comment by rnkdsh** [comment]
same issue

**Comment by RohovDmytro** [comment]
+1

```
 Compiling expo-dev-menu Pods/expo-dev-menu » DevClientRootViewFactory.mm

❌  (/Users/****/Library/Developer/Xcode/DerivedData/Housy-cpznytdabwtpdweckbtidfqvwsve/Build/Products/Debug-iphonesimulator/React-runtimescheduler/React_runtimescheduler.framework/Headers/react/renderer/runtimescheduler/RuntimeScheduler.h:11:10)

   9 | 
  10 | #include <ReactCommon/RuntimeExecutor.h>
> 11 | #include <react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h>
     |          ^ 'react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h' file not found
````

**Comment by t16n** [comment]
@expo-bot please reopen issue

I've added an example
https://github.com/t16n/rn-75-expo-dev-client-issue

**Comment by t16n** [comment]
@tsapeta @alanjhughes @brentvatne can maybe one of you reopen?

**Comment by anudit** [comment]
@EvanBacon Running into this too with `useFrameworks: "static"` required for RN Firebase.

**Comment by anudit** [comment]
Thanks @alanjhughes !

**Comment by tuanlevi95** [comment]
same issue with expo 51.0.37 and react native 0.75.4

**Comment by sainjay** [comment]
still facing error in RN 0.75.4 and Expo 51.0.38

```
 (/Users/{user}/Library/Developer/Xcode/DerivedData/{app_name}/Build/Products/Debug-iphonesimulator/React-Core/React.framework/Headers/RCTBridge+Inspector.h:11:9)

   9 | 
  10 | #ifdef __cplusplus
> 11 | #import <jsinspector-modern/ReactCdp.h>
     |         ^ include of non-modular header inside framework module 'React.RCTBridge_Inspector': '/Users/{user}/Library/Developer/Xcode/DerivedData/{app_name}/Build/Products/Debug-iphonesimulator/React-jsinspector/jsinspector_modern.framework/Headers/jsinspector-modern/ReactCdp.h' [-Werror,-Wnon-modular-include-in-framework-module]
  12 | #endif
  13 | 
  14 | @interface RCTBridge (Inspector)
```


"ios": {
            "deploymentTarget": "16.6",
            "useFrameworks": "static"
          }

**Comment by arosiclair** [comment]
I'm also seeing this issue with react-native 0.75.2 and expo 51.0.31 and `use_frameworks! :linkage => :static` added to my Podfile

**Comment by akilamist** [comment]
Still issuu there. Anyone how to fix this ?
