### ISSUE TITLE
Drawer Peeks Out From Behind Modal When Right Positioned

### ISSUE THREAD

**Issue by salieflewis** [expo/expo#31105]
### Minimal reproducible example

https://github.com/salieflewis/how-to-router/tree/main/drawer-and-tabs

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Following the `how-to-router` drawer structure. There is an issue where if a tab has a stack navigator that includes a modal that is presented as such, the drawer peeks out from beneath the stack when opening and closing that modal.

https://github.com/user-attachments/assets/cb342b8c-51a0-4e74-934d-07407eec8440

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
      Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 10.2.3
    Expo Workflow: managed
 ```

**Comment by marklawlor** [comment]
This is an upstream issue with React Navigation and can be replicated without Expo Router. While these components are exported from `expo-router`, we don't maintain them. I would recommend creating an issue on the React Navigation repo.

We're currently working on a new set of navigators which will be maintained by the Expo team

**Comment by salieflewis** [comment]
> This is an upstream issue with React Navigation and can be replicated without Expo Router. While these components are exported from `expo-router`, we don't maintain them. I would recommend creating an issue on the React Navigation repo.
> 
> We're currently working on a new set of navigators which will be maintained by the Expo team

I did so, thank you.
