### ISSUE TITLE
`expo-symbols` package does not contain SymbolView.web in npm

### ISSUE THREAD

**Issue by dlindenkreuz** [expo/expo#31113]
### Minimal reproducible example

https://unpkg.com/browse/expo-symbols@0.1.4/src/

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

The reproducible example is a directory listing of the npm package.

[The repo contains `SymbolView.web.tsx`](https://github.com/expo/expo/tree/main/packages/expo-symbols/src) but the npm package does not.

Weirdly enough, it's not ignored by `.npmignore` so I guess something went wrong when publishing.

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 3.6.0 - /usr/local/bin/fish
    Binaries:
      Node: 21.6.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.28 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.12 => 0.19.12 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

n/a

**Comment by alanjhughes** [comment]
Hi @dlindenkreuz the issue is #30249 has not been published yet. I've picked this now and it will be available in the next release, probably later today
