### ISSUE TITLE
Android crash on real device

### ISSUE THREAD

**Issue by wcastand** [expo/expo#31112]
### Summary

since yesterday, after upgrading my deps i get a crash on android when i build for a real device.
i tried coming back in commit on my repo and still the same crash so most likely a patch causing the issue.

only happens on real device, when i build on emulator it works

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

    "expo": "^51.0.30",
    "expo-application": "~5.9.1",
    "expo-asset": "~10.0.10",
    "expo-atlas": "^0.3.11",
    "expo-build-properties": "~0.12.5",
    "expo-clipboard": "~6.0.3",
    "expo-constants": "~16.0.2",
    "expo-datadog": "^51.0.2",
    "expo-dev-client": "~4.0.24",
    "expo-device": "~6.0.2",
    "expo-document-picker": "~12.0.2",
    "expo-font": "~12.0.9",
    "expo-image": "~1.12.14",
    "expo-image-picker": "~15.0.7",
    "expo-insights": "~0.7.0",
    "expo-intent-launcher": "~11.0.1",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-local-authentication": "~14.0.1",
    "expo-localization": "~15.0.3",
    "expo-navigation-bar": "~3.0.7",
    "expo-network": "~6.0.1",
    "expo-notifications": "~0.28.16",
    "expo-print": "~13.0.1",
    "expo-quick-actions": "^2.0.0",
    "expo-router": "~3.5.23",
    "expo-secure-store": "~13.0.2",
    "expo-sharing": "~12.0.1",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-task-manager": "~11.8.2",
    "expo-updates": "~0.25.23",
    "expo-web-browser": "~13.0.3",

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
      Watchman: 2024.08.05.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.30 => 51.0.30
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

### Reproducible demo

https://github.com/wcastand/crash-android-expo/tree/main

### Stacktrace (if a crash is involved)

 E  FATAL EXCEPTION: main
                                                                                                    Process: com.greengot.dev, PID: 27866
                                                                                                    java.lang.NoSuchMethodError: No virtual method setSystemGestureExclusionRects(Ljava/util/List;)V in class Lexpo/modules/devmenu/DevMenuReactRootViewContainer; or its super classes (declaration of 'expo.modules.devmenu.DevMenuReactRootViewContainer' appears in /data/app/com.greengot.dev-YNLYyEftDBMG6ZYgA0IQ_w==/base.apk!classes2.dex)
                                                                                                        at expo.modules.devmenu.DevMenuReactRootViewContainer$updateSystemGestureExclusionRects$1.invoke(DevMenuReactRootViewContainer.kt:35)
                                                                                                        at expo.modules.devmenu.DevMenuReactRootViewContainer$updateSystemGestureExclusionRects$1.invoke(DevMenuReactRootViewContainer.kt:22)
                                                                                                        at expo.modules.devmenu.DevMenuReactRootViewContainer.onLayout(DevMenuReactRootViewContainer.kt:53)

**Comment by larrybwosi** [comment]
I also get the same error here

**Comment by alanjhughes** [comment]
Hi @wcastand I've just tried your repro but I'm not seeing the error. App builds and runs without issue on my device. What version of Android is your device running?

**Comment by alanjhughes** [comment]
@wcastand I have repro'd now. Is your device running android 9 or lower?

**Comment by sd535682** [comment]
Yeah my app is crashing after splash screen

**Comment by wcastand** [comment]
@alanjhughes yes it's a samsung galaxy S8 on android 9

**Comment by manssorr** [comment]
Yeah! Same issue Huawei nova 3 (PAR-LX1M)
