### ISSUE TITLE
Expo Client Android App version 2.10.0 fails to open any Expo v31.0.0 projects

### ISSUE THREAD

**Issue by augustosamame** [expo/expo#3111]
Hello. Android Expo App just updated today to versión 2.10.0. Release notes indicate it now supports Expo SDK v 32

However when trying to open any v31.0.0 projects it indicates:

Something went wrong. This experience uses SDK v31.0.0, but this Expo client requires at least v 32.0.0

I think this is a serious bug? SDK has not been even been officially published, and Expo client is supposed to support recent previous versions?

**Comment by peckpeck20** [comment]
same here ,I'm using Android 9.0

**Comment by creativemind1** [comment]
Delete node_modules folder, do npm i and start with expo start -c. This has solved my problem

**Comment by MarcoLotto** [comment]
An expo app update that solves this problem is already at the stores (at least in google play)

**Comment by augustosamame** [comment]
I can confirm that latest expo add in Android Play Store fixes this issue. It was uploaded a few hours after the buggy version so it may have the same date (Jan 4th 2019).
