### ISSUE TITLE
expo-camera react native 0.75.2 android build error

### ISSUE THREAD

**Issue by hengkx** [expo/expo#31111]
### Minimal reproducible example

not

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

> Task :expo-camera:compileDebugKotlin FAILED
e: file:///**/node_modules/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.kt:23:17 Unresolved reference: appcompat
e: file:///**/node_modules/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.kt:93:15 'Nothing' property type needs to be specified explicitly
e: file:///**/node_modules/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.kt:94:44 Unresolved reference: AppCompatActivity

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
      Yarn: 3.6.4 - ~/.nvm/versions/node/v20.12.0/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.12.0/bin/npm
      Watchman: 2024.06.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/tom/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.30 => 51.0.30 
      react: 18.3.1 => 18.3.1 
      react-native: 0.75.2 => 0.75.2 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✖ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following scripts in package.json conflict with the contents of node_modules/.bin: iconfont.

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: jsEngine, ios, plugins. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/netinfo@11.3.2 - expected version: 11.3.1
  @shopify/flash-list@1.7.1 - expected version: 1.6.4
  react@18.3.1 - expected version: 18.2.0
  react-native@0.75.2 - expected version: 0.74.5
  react-native-gesture-handler@2.18.1 - expected version: ~2.16.1
  react-native-pager-view@6.4.0 - expected version: 6.3.0
  react-native-reanimated@3.15.0 - expected version: ~3.10.1
  react-native-safe-area-context@4.10.9 - expected version: 4.10.5
  react-native-screens@3.34.0 - expected version: 3.31.1
  react-native-svg@15.6.0 - expected version: 15.2.0
  react-native-webview@13.11.1 - expected version: 13.8.6
  @types/react@18.3.4 - expected version: ~18.2.79
  typescript@5.5.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by davidtran** [comment]
I am having the same error

**Comment by k2ker** [comment]
I am having the same error
