### ISSUE TITLE
Error loading font - TypeError: Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by 03balogun** [expo/expo#31142]
### Minimal reproducible example

null

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

The error started after upgrading from `"expo": "^50.0.14"` to `"expo": "~51.0.28"` 

Also updated `"expo-font": "~11.10.3"` to `"expo-font": "~12.0.9"`

Downgrading expo-font doesn't resolve the issue.

<img src="https://github.com/user-attachments/assets/e4391291-755b-49bb-969b-d0fc63dfc704" width="350px" />

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.1/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
      Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.30 => 51.0.30 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.3.1 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 7.8.0
    Expo Workflow: bare

### Expo Doctor Diagnostics

null

**Comment by ach5910** [comment]
Adding `"@react-native/assets-registry": "0.74.83"` to my package.json resolutions worked for me.

**Comment by ParAnton** [comment]
Having the same issue after upgrading to 51.0.31 adding "@react-native/assets-registry": "0.75.2" doesn't solve the issue for me.

**Comment by azzadrood** [comment]
> Adding `"@react-native/assets-registry": "0.74.83"` to my package.json resolutions worked for me.

This solved my problem!

Thanks!

**Comment by AurelienV-42** [comment]
In case somebody is still stuck here...
Upgrading from react-native 74.5 to "^0.75.4" fixed the problem for me.

npx expo-doctor@latest didn't say anything

**Comment by csulit** [comment]
same problem with 74.5

**Comment by marvin-rao** [comment]
@csulit , did you get a solution?

**Comment by haiffy420** [comment]
> [@csulit](https://github.com/csulit) , did you get a solution?

@marvin-rao , you wont believe this but did you get a solution?
