### ISSUE TITLE
BroadcastReceiver not trigerring app if it is not in foreground or background.

### ISSUE THREAD

**Issue by maniac-tech** [expo/expo#31159]
### Minimal reproducible example

https://github.com/maniac-tech/ExpoReadSMS-TestApp

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I'm currently using a [library](https://github.com/maniac-tech/react-native-expo-read-sms) to read incoming SMS.

The library works absolutely fine, when the app is in foreground/background and I receive a SMS, but it doesnt trigger anything if the app is not in memory.

### Environment

--

### Expo Doctor Diagnostics

--

**Comment by maniac-tech** [comment]
Can it be related to `RECEIVER_EXPORTED` ?

**Comment by alanjhughes** [comment]
Hi @maniac-tech, I'm not really sure what this has to do with expo? It looks like the library is your own. In any case, android will not wake up an app for a broadcast unless it is registered in the manifest. It doesn't look like you have done that. `SMS_RECEIVED_ACTION` is one of the implicit broadcasts that are exempt from the rules introduced in api 26 so you should be able to add it.
