### ISSUE TITLE
[expo-av] Recorder is not prepared when switching from audio playing to recording

### ISSUE THREAD

**Issue by sebnun** [expo/expo#31152]
### Summary

Hi, I'm using `react-native-track-player` for playing audio (due to `expo-av` not having lock screen audio controls) and `expo-av` for audio recording.

I can play audio and record audio once, but after I try to play audio and record a second time, the recording initialization fails with the error: 

>Failed to start recording [Error: Prepare encountered an error: recorder not prepared.]

The code for the recording functionality is copied from the expo official docs.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "~51.0.28",
"expo-av": "~14.0.7",
"expo-status-bar": "~1.12.1",
"react": "18.2.0",
"react-native": "0.74.5",
"react-native-track-player": "^4.1.1",
"expo-dev-client": "~4.0.25"

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.31
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: managed

### Reproducible demo

https://github.com/sebnun/testav

To Reproduce:
1) Play and Pause the audio.
2) Start and Stop recording. It records correctly.
3) Play and Pause the audio.
4) Start recording. It doesn't record, an error is shown on the console.

**Comment by jiangts** [comment]
+1 experiencing the exact same problem

**Comment by jiangts** [comment]
if it helps anyone, the problem seems to be resolved with the following audio config:

```ts
const [permissionResponse, requestPermission] = Audio.usePermissions();

  async function startRecording() {
    try {
      if (permissionResponse.status !== 'granted') {
        console.log('Requesting permission..');
        await requestPermission();
      }
      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
        interruptionModeIOS: InterruptionModeIOS.DoNotMix,
        shouldDuckAndroid: true,
        interruptionModeAndroid: InterruptionModeAndroid.DoNotMix,
        playThroughEarpieceAndroid: false,
        staysActiveInBackground: true,
      });

      console.log('Starting recording..');
      const { recording } = await Audio.Recording.createAsync(Audio.RecordingOptionsPresets.HIGH_QUALITY);
      setRecording(recording);
      console.log('Recording started');
    } catch (err) {
      console.error('Failed to start recording', err);
    }
  }
```

The key is `interruptionModeIOS: InterruptionModeIOS.DoNotMix`
This setting fixes the issue.

**Comment by sebnun** [comment]
Can also confirm that it works with the code above, closing this.
