### ISSUE TITLE
Stuck on Node Modules' files do not exist (have tried to remove and re-do npm install to see if would fix) but gone in circles.

### ISSUE THREAD

**Issue by james-hizon** [expo/expo#31155]
### Summary

Stuck on this:

Web Bundling failed 6137ms node_modules/expo-router/entry.js (1023 modules)
λ Bundling failed 6152ms node_modules/expo-router/node/render.js (1023 modules)

Metro error: Unable to resolve module ../../Utilities/Platform from /Users/jameshizon/GFA Mobile/GFA-Mobile-V2/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js: 

**None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform/index(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)**
  24 |
  25 | const {findNodeHandle} = require('../../ReactNative/RendererProxy');
> 26 | const Platform = require('../../Utilities/Platform');
     |                           ^
  27 | const React = require('react');
  28 | type ComponentRef = React.ElementRef<HostComponent<mixed>>;
  29 |

  1 | /**
  2 |  * Copyright (c) Meta Platforms, Inc. and affiliates.
  3 |  *

Call Stack
  <unknown> (node_modules/react-native/Libraries/Components/TextInput/TextInputState.js:0)
Web Bundled 1384ms node_modules/expo-router/_error.js (313 modules)
(base) jameshizon@Jamess-MacBook-Pro-2 GFA-Mobile-V2 % 

### What platform(s) does this occur on?

Android, iOS

### SDK Version

"expo": "~51.0.28"

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - /usr/local/bin/node
      npm: 10.7.0 - /usr/local/bin/npm
      Watchman: 2024.08.19.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.18.11 => 0.18.11 
      expo: ^51.0.30 => 51.0.30 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Minimal reproducible example

My Github is on private for reasons - I assume that given that this issue has been brought up more than once in discord, we don't need a minimal reproducible example.

**Comment by yakovsushenok** [comment]
i also have the same issue. did you resolve it?

**Comment by CaptainJeff** [comment]
Was anyone able to figure this out. Getting it now with expo 53
