### ISSUE TITLE
[expo-sensors] Sensor documentation is unclear

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#3117]
From what I can tell the actual functionality is not the same as what is described in the documentation. 
The Accelerometer seems to be reporting the orientation of the device and not the acceleration. It appears the Gyroscope/Accelerometer functionality is switched.

## [Accelerometer](https://docs.expo.io/versions/latest/sdk/accelerometer)

> Access the device accelerometer sensor(s) to respond to changes in acceleration in 3d space.

## [Gyroscope](https://docs.expo.io/versions/latest/sdk/gyroscope) 

> Access the device gyroscope sensor to respond to changes in rotation in 3d space.

The axis data these sensors are returning is also unclear. On Android the Accelerometer data seems to be inverted from what is returned on iOS. Unsure about which OS is corrected since the desired axis is not defined in the documentation. 

### [iOS rotation rate](https://developer.apple.com/documentation/coremotion/getting_raw_gyroscope_events)

![ios_gyroscope_orientation](https://user-images.githubusercontent.com/9664363/50719405-4d311080-1050-11e9-9d17-535626686ea6.png)

**Comment by EvanBacon** [comment]
Perhaps we should make DeviceMotion the recommended option for any sensor data: https://stackoverflow.com/a/23973072/4047926

This would also work better for web parity.

**Comment by blunket** [comment]
I'm glad I'm not crazy. Just getting into this and was losing my mind over this. They are definitely switched.

**Comment by blunket** [comment]
@EvanBacon Check this out also: https://github.com/react-native-sensors/react-native-sensors/issues/19

**Comment by EvanBacon** [comment]
I think the lack of gravity is creating a bunch of issues. The naming is correct, both iOS and Android are directly binding the native API of the same name, but perhaps expo-sensors could do some magic to make the API work better.
