### ISSUE TITLE
Image-Manipulator doesn't save images in a devices gallery

### ISSUE THREAD

**Issue by cSieves** [expo/expo#31170]
### Minimal reproducible example

https://github.com/cSieves/image-manipulator-test

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Saving images manipulated by the image manipulator does not save images in the devices's gallery but instead saves it in some cache. 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
      Watchman: 2024.07.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.14 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    npmGlobalPackages:
      eas-cli: 10.1.1
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by vonovak** [comment]
Hello and thanks for asking,
what you're seeing is the expected behavior, the images are not saved to gallery because it may not be what the user wants.

To add images to gallery I believe you want to use this: https://docs.expo.dev/versions/latest/sdk/media-library/#medialibrarycreateassetasynclocaluri

Hope this helps,
Thank you 🙂

**Comment by cSieves** [comment]
Hi @vonovak thank you for the speedy reply. Ok that makes sense, thank you!

So for my example would the flow be something like. 

1. Use Image-Manipulator to manipulate the image
2. Use MediaLibrary to save the image generated by Image-Manipulator

Are there any additional steps i.e. should I clean up the image created by Image-Manipulator when done or is it ok to leave it as it is only saved to a cache? Thanks!

**Comment by vonovak** [comment]
hello, you can leave the images in the cache and the OS will care of it when necessary.

**Comment by cSieves** [comment]
Ok, thats great, thank you for the help here!
