### ISSUE TITLE
Errors when upgrading to Expo SDK v18.0.0

### ISSUE THREAD

**Issue by jcalderaio** [expo/expo#312]
This photo displays my first error after following the steps in this guide. I decided to follow the rabbit hole and dragged the ‘glyphmaps’ folder from the ‘node_modules/react-native-vector-icons’ directory to ‘@expo/vector-icons’.

<img width="442" alt="screen shot 2017-06-28 at 12 33 24 pm" src="https://user-images.githubusercontent.com/6464473/27650295-739965f0-5c02-11e7-85ac-a26a1d643308.png">

The error went away, but another ‘@expo/vector-icons’ error showed up. So, I decided to copy the entire ‘node_modules/react-native-vector-icons’ directory to ‘@expo/vector-icons’. The ‘@expo/vector-icons’ based errors went away, but then I got an error that read “Element type is invalid: expected a string (for built in components) or a class/function (for composite components) but got: undefined”.

I read on the forums that native-base was the issue for some people, but my app uses so many native-base modules that I would have to scrap the app (I cannot. This is an app for work that needs to work for my livelihood.

Please! I need help fixing these errors.

**Comment by dikaiosune** [comment]
Hi! Sorry to hear that you're having issues. Have you tried the steps recommended in the error screen?

Also, do you think you could provide a minimal reproduction of this issue with a bare Expo app and the Native Base module that's causing it? Hard to tell exactly what's causing this without being able to trigger it locally.

**Comment by broskoski** [comment]
Running into this same identical error after upgrading from 16.0.0 to 18.0.0. Not quite sure how to minimally reproduce though, I followed the instructions for upgrading laid out in https://blog.expo.io/expo-sdk-v18-0-0-is-now-available-38e62305283. 

Cleared the cache and removed the `node_modules` folder a few times now. I'm not really willing to try and mess with the structure of any installed modules (fwiw, the `Entypo.js` file tries to load a glyphMap from `'react-native-vector-icons/glyphmaps/Entypo.json'` which does, in fact, exist).

Any help would be appreciated!

**Comment by broskoski** [comment]
Looks like I spoke too soon. `@expo/vector-icons` was stuck at 4.0.0, and upgrading to 5.0.0 did the trick. 

@jcalderaio try running `yarn upgrade @expo/vector-icons` then restart your project and see if that fixes things.

**Comment by jcalderaio** [comment]
@broskoski Your idea worked! What gave you that idea? 

Although I did get my project working, I have a lot of warnings popping up:

--Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
--Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
--Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
--Warning: View.AccessibilityTraits has been deprecated and will be removed in a future version of ReactNative. Use ViewAccessibility.AccessibilityTraits instead.
--Warning: View.AccessibilityComponentType has been deprecated and will be removed in a future version of ReactNative. Use ViewAccessibility.AccessibilityComponentTypes instead.
--Warning: View.forceTouchAvailable has been deprecated and will be removed in a future version of ReactNative. Use NativeModules.PlatformConstants.forceTouchAvailable instead.
--Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
--Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Do you know what I should do about these? I'm not even using 'PropTypes' or 'React.createClass'. And the others? I have no idea what they are referring to lol.

**Comment by broskoski** [comment]
@jcalderaio no idea, but make sure you follow all the instructions and upgrade your `react` and `react-native` sources in your package.json file.

**Comment by brentvatne** [comment]
@jcalderaio - a bunch of those warnings are unfortunately just the state of the world with React Native 0.45 / React 16.0.0-alpha -- PropTypes as an import from React has been deprecated, same as React.createClass, but not all of React Native has been updated for that and certainly not most random packages out there.

**Comment by jcalderaio** [comment]
Thanks for your swift replies. I don't have any PropTypes or React.createClass code snippets in my project. I use exclusively ES6 classes and I still am not sure what PropTypes even are. Would you be able to flip through my code real quick and let me know where the issues are? This project is for a client (due in about 8 weeks) and I'd hate for the app to break for them during use. I want to update it as much as possible before the shipping deadline. Here is the project:

https://github.com/jcalderaio/PSI-employee-timesheet

**Comment by dikaiosune** [comment]
@jcalderaio from a 30 second glance, [this](https://github.com/jcalderaio/PSI-employee-timesheet/blob/master/.babelrc#L3-L5) seems like it could cause a problem. Maybe try using only the expo preset? cc @brentvatne

**Comment by jcalderaio** [comment]
But when I was told to use one of the libs, forgot which, it required me to
use that setup. But, maybe things have changed. Either way, my apps started
working again mate. Cheers  





On Thu, Jul 6, 2017 11:14 AM, Adam Perry notifications@github.com  wrote:
@jcalderaio  from a 30 second glance, this  seems like it could cause a problem.
Maybe try using only the expo preset? cc @brentvatne

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Sincerely,John  A. Calderaio
