### ISSUE TITLE
QRCode rendered by expo start cannot be read

### ISSUE THREAD

**Issue by logemann** [expo/expo#31203]
### Summary

according to https://github.com/expo/expo/issues/21180 this is about terminal font, but i ve tried 3 different terminals, all running the default settings and the barcode will never display properly.

Doubt that his is a user issue.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.16.0/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.31 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 11.0.2
    Expo Workflow: managed

### Minimal reproducible example

nothing to reproduce

**Comment by brentvatne** [comment]
hi there! you could do the following things to help:

- share information about your terminal and the font
- share a screenshot
