### ISSUE TITLE
FetchError Invalid response body with npx expo install --check  

### ISSUE THREAD

**Issue by wilmarv** [expo/expo#31207]
### Summary

I am trying to run npx expo install --check and npx expo-doctor, but I keep encountering the following error:
"FetchError: Invalid response body while trying to fetch https://api.expo.dev/v2/versions/latest: sha512-... integrity checksum failed when using sha512: ..."

I have already cleared the cache using yarn cache clean and npm cache clean --force, but the error persists. I've also tried running the commands on other Expo projects on my machine, which were working fine before without any changes, but now all of them are showing the same error.

`FetchError: Invalid response body while trying to fetch https://api.expo.dev/v2/versions/latest: sha512-93Or+WJnqDiaah0tTLQZrA/svCeeAKayukhdPgJRqq1FsgfOdvyvto5sBWs63/zZ+MrdkYkcXLlKABHDGCeKkA== integrity checksum failed when using sha512: wanted sha512-93Or+WJnqDiaah0tTLQZrA/svCeeAKayukhdPgJRqq1FsgfOdvyvto5sBWs63/zZ+MrdkYkcXLlKABHDGCeKkA== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
    at Pipeline.<anonymous> (/home/.../.../node_modules/node-fetch/lib/index.js:400:12)
    at Pipeline.emit (node:events:531:35)`

### SDK Version

51

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.16.0/bin/yarn
      npm: 10.8.2 - ~/node_modules/.bin/npm
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.14 
      expo: ^51.0.31 => 51.0.31 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.6 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 11.0.2
    Expo Workflow: managed

### Minimal reproducible example

"I don't have permission to share the Git link."

**Comment by brentvatne** [comment]
hi there! are you using a proxy? this seems to be likely related to your network connection. try on a different machine to see if you can reproduce.

you can try opening https://api.expo.dev/v2/versions/latest to verify that it works as expected too

**Comment by wilmarv** [comment]
I asked a colleague to download the project on his machine from his home — in other words, on a different network — and he reported the same error.
It's strange because my first step was to test other projects that were working fine, and the error still occurred. So, I initially concluded that the issue wasn't with any changes made to the project but possibly with my machine or local installation. However, my colleague tested the same project on his machine and network at home, and he experienced the same error. The only things we have in common are the same project, the same version of Node installed via NVM, and the internet provider is from the same company.

![image_2024-08-27_194252813](https://github.com/user-attachments/assets/81886458-fce3-4357-8b4b-b341dfba6ca1)
