### ISSUE TITLE
{"message":"no such table: XXXX","code":5}

### ISSUE THREAD

**Issue by RavindraMaddukuri** [expo/expo#3122]
React-native-SQLite-Storage getting an error after upgrading the react-native version from 0.44.0 to 0.55.4, and react-native-SQLite-Storage version from "^3.1.2" to "3.3.9" 
After doing these two changes data is not getting from the table and showing an error like this  {"message": "no such table: xxxx", "code":5}  in Xcode. can anyone help me solve this problem? 
**and this is my code**
 handleSubmit() {
    //  const { params } = this.props.navigation.state;
    var db = SQLite.openDatabase({name: "testDB7", createFromLocation : 1});
    if(!this.state.animated){
      var count = 0;
      var word = 0;
      var count1 = this.state.count;
      var words = this.state.word
      var fakeCount = count1
      var correct = this.state.correctWords
      var Incorrect = this.state.incorrectWords
      var wrong = this.state.incorrectWords
      this.setState({
        wrong:wrong
      },()=>{
        //alert("submit:"+this.state.value)
      })

      this.state.value
      console.log("current:"+this.state.currentWord);
      for (var i = 0, n = words.length; i < n; i++) {
          for (var j = 0, m = this.state.value.length; j < m; j++) {
            if(words[i] == this.state.value[j]){
              word = word+1
            }
          }
      }
      //CREATE TABLE "xxxx" ("words" varchar DEFAULT (null) )
    if(word == this.state.value.length){
      alert(this.state.value)
      db.executeSql('SELECT * FROM xxxx WHERE words ='+"\""+this.state.value+"\"", [], (results) => {
       alert(results)
        if(results.rows.length != 0){
            this.success.bind(this)
          }
          else{
           this.fail.bind(this)
          }
        },(error)=>{
         alert('error'+JSON.stringify(error))
          console.log("errorravi:"+JSON.stringify(error))
     
      })
    }
    else{
      //alert('hfdgivhds')
      this.setState({wrong:'yes'});
      if(this.state.currentWord != "") {
            Incorrect.push(this.state.currentWord);
      }
      setTimeout(() => {
        this.setState({incorrectWords: Incorrect})
        this.setState({currentWord: '',wrong:Incorrect})
      }, 300);
    }
    }
  }
     
**and also i am little bit confusing over this topic in react-native please help me**

thanks in advance

**Comment by esamelson** [comment]
Hi @RavindraMaddukuri - this repo is for the Expo SDK only and all of the modules it includes. I'd recommend you open an issue on the [react-native-sqlite-storage repo](https://github.com/andpor/react-native-sqlite-storage) instead. We can't help you out here as we don't maintain that code. Best of luck getting your issue resolved!
