### ISSUE TITLE
expo-doctor "Cannot read properties of undefined (reading 'targetSdkVersion')"

### ISSUE THREAD

**Issue by carmonw** [expo/expo#31224]
### Summary

The latest version of `expo-doctor` is failing due to an issue with the `StoreCompatibilityCheck` which was added in version `1.10.0`.

The `StoreCompatibilityCheck` makes an [assumption](https://github.com/expo/expo/blob/main/packages/expo-doctor/src/checks/StoreCompatibilityCheck.ts#L49C42-L49C58) that projects following CNG will have `android` set for build properties and attempts to read `targetSdkVersion`, causing things to blow up.  Aside from `android` not being required for build properties, the `targetSdkVersion` in build properties is also only meant to be used if the default needs to be overridden as indicated by the docs [here](https://docs.expo.dev/versions/latest/sdk/build-properties/#pluginconfigtypeandroid).

`StoreCompatibilityCheck` needs to be reworked so that projects following CNG will not have `expo-doctor` fail if the optional `android` and `targetSdkVersion` build properties are not set.  Instead, `StoreCompatibilityCheck` should probably just check `build.gradle` for the required versions instead of doing [this](https://github.com/expo/expo/blob/main/packages/expo-doctor/src/checks/StoreCompatibilityCheck.ts#L26).

### SDK Version

51.0.31

### Environment

Doesn't matter.

### Minimal reproducible example

```
npx expo-doctor@1.10.0
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✖ Check if the project meets version requirements for submission to app stores
Unexpected error while running 'Check if the project meets version requirements for submission to app stores' check:
TypeError: Cannot read properties of undefined (reading 'targetSdkVersion')
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
One or more checks failed, indicating possible issues with the project.
```

**Comment by bndkt** [comment]
Can confirm

**Comment by keith-kurak** [comment]
apologies! should be fixed in the latest version up now.
