### ISSUE TITLE
expo build crashes if font files are in .gitignore

### ISSUE THREAD

**Issue by jankapunkt** [expo/expo#31235]
### Summary

Running eas build causes fonts not being copied to the `/tmp` folder, causing the prebuild phase to fail:

<details>
<summary>show part of the terminal output</summary>

```shell
[RUN_EXPO_DOCTOR] Didn't find any issues with the project!
[PREBUILD] - Creating native directory (./android)
[PREBUILD] ✔ Created native directory
[PREBUILD] - Updating package.json
[PREBUILD] ✔ Updated package.json
[PREBUILD] - Running prebuild
[PREBUILD] ✖ Prebuild failed
[PREBUILD] Error: [android.dangerous]: withAndroidDangerousBaseMod: ENOENT: no such file or directory, stat '/tmp/jankapunkt/eas-build-local-nodejs/6ffd61a9-9487-4dfe-bda5-bf056a099495/build/lea.App/assets/fonts/SemikolonPlus-Regular.ttf'
[PREBUILD] Error: [android.dangerous]: withAndroidDangerousBaseMod: ENOENT: no such file or directory, stat '/tmp/jankapunkt/eas-build-local-nodejs/6ffd61a9-9487-4dfe-bda5-bf056a099495/build/lea.App/assets/fonts/SemikolonPlus-Regular.ttf'
[PREBUILD] 
Error: npx expo prebuild --no-install --platform android exited with non-zero code: 1
    at ChildProcess.completionListener (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at runExpoCliCommand (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/utils/project.js:23:43)
    at prebuildAsync (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/common/prebuild.js:17:43)
    at /home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/android.js:51:44
    at BuildContext.runBuildPhase (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/context.js:107:34)
    at buildAsync (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/android.js:45:15)
    at async runBuilderWithHooksAsync (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.androidBuilder (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/@expo/build-tools/dist/builders/android.js:24:16)
    at async buildAndroidAsync (/home/jankapunkt/.npm/_npx/5e31c5d24a898acf/node_modules/eas-cli-local-build-plugin/dist/android.js:41:12)

Build failed
Unknown error. See logs of the Prebuild build phase for more information.
```

</details>

When removing the font from the `.gitignore` list then building succeeds

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    npmPackages:
      expo: ~51.0.28 => 51.0.31 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 11.0.2
    Expo Workflow: managed
```

### Minimal reproducible example

- Create a new expo project using `npx create-expo-app@latest` (currently latest is sdk 51)  
- add the default Space font (under assets/fonts) to the `.gitignore`
- build using `eas build` → will cause the error, described in the summary
- remove font from gitignore and build → success

**Comment by leonhh** [comment]
Hi @jankapunkt. Expo EAS looks at .`gitignore` to see what files need to be uploaded to build your app. Your best option is to create a `.easignore` file in the root of your project. This file has priority over `.gitignore`. In your case you can basically copy the content of your `.gitingore` file excluding the font file. 

Also see https://expo.fyi/eas-build-archive for more information

**Comment by jankapunkt** [comment]
@leonhh thank you for the hint, however I still got the error, even after adding the `.easignore` file. If I can reproduce this in a new project I will add to GitHub and link it here

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Your app needs the fonts files to build and run, so it follows that the build fails. Font files belong neither to `gitignore` nor to `easignore`. Treat the font files same as you treat application source code.

Thank you 🙂

**Comment by jankapunkt** [comment]
@vonovak font files may do belong to gitignore, for example in our case it's a domain specific font which we are allowed to use but not to redistribute. It's indeed a rare usecase but it's one.

**Comment by vonovak** [comment]
Hello, thanks for the follow-up.
I'm not an expert on licensing and what the definition of "distribute" is in this case. However, it's technically impossible to render a font without the application having direct access to the font file. This is not a limitation of Expo but it's how mobile app development works. 

Example: consider the docs for using custom font on iOS. The first step is "[Add the Font File to Your Xcode Project](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app#2939904)". There's no way around it.

Hope this makes sense,
Thank you 🙂

**Comment by jankapunkt** [comment]
Hi @vonovak the font exists on my local setup but I cannot check it into git because that would be making it publicly available (=distribution of the file). Again it's a rare edge case because most fonts are under a free license. I'll let you know here, when I found a viable solution with .easignore. thanks for the fast responses!
