### ISSUE TITLE
[expo-updates] Updates.checkForUpdateAsync() function API not working on iOS testFlight.

### ISSUE THREAD

**Issue by iita71737** [expo/expo#31230]
### Minimal reproducible example

https://gitlab.com/wasavillagerdan/otatest3

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

My project was created by a bare react native cli , 
a bare and blank project, just a simple text on it.
and I needed to test EAS Updates to replace the CodePush.

I follow the post below.
[https://docs.expo.dev/bare/installing-updates/](https://docs.expo.dev/bare/installing-updates/)
and lots of tutorial post.
Finally, I found the android is working for expo-updates with OTA.
but iOS is not working on testFlight.

### Environment

production

### Expo Doctor Diagnostics

not use it

**Comment by brentvatne** [comment]
can you explain what you mean when you say that it is not working? any additional context you can provide is helpful.

more updates troubleshooting information:
- https://docs.expo.dev/eas-update/debug/
- https://docs.expo.dev/eas-update/debug-advanced/

happy to help if you can provide some more detailed info about what you are observing. also, please run `npx expo-doctor` even if yu don't typically use it, it's helpful for us to see the output

**Comment by iita71737** [comment]
> can you explain what you mean when you say that it is not working? any additional context you can provide is helpful.
> 
> more updates troubleshooting information:
> 
> * https://docs.expo.dev/eas-update/debug/
> * https://docs.expo.dev/eas-update/debug-advanced/
> 
> happy to help if you can provide some more detailed info about what you are observing. also, please run `npx expo-doctor` even if yu don't typically use it, it's helpful for us to see the output

I found the code

```
  useEffect(() => {
    async function checkForUpdates() {
      Alert.alert(process.env.NODE_ENV,'process.env.NODE_ENV')
      try {
        const update = await Updates.checkForUpdateAsync();
        if (update.isAvailable) {
          Alert.alert('update Available')
          await Updates.fetchUpdateAsync();
          Alert.alert('fetchUpdateAsync success')
          Updates.reloadAsync();
        }
      } catch (e) {
        console.error('Failed to check or apply update:', e);
        Alert.alert('Failed to check or apply update')
      }
    }
    checkForUpdates();
  }, []);
  ```
  
  Failed on iOS Testflight 
  I confirmed the `process.env.NODE_ENV` is procution in iOS TestFlight.
  But not working , no error msg.
  I checked my installation is followed with this [doc](https://docs.expo.dev/bare/installing-updates/)
  and Android is working to fetch eas update and refresh the new update.
  But on iOS , just keep the content on my bundle version, not eas update version.

**Comment by iita71737** [comment]
> can you explain what you mean when you say that it is not working? any additional context you can provide is helpful.
> 
> more updates troubleshooting information:
> 
> * https://docs.expo.dev/eas-update/debug/
> * https://docs.expo.dev/eas-update/debug-advanced/
> 
> happy to help if you can provide some more detailed info about what you are observing. also, please run `npx expo-doctor` even if yu don't typically use it, it's helpful for us to see the output

```
[~/otaTest3] (step6) $ npx expo-doctor
Need to install the following packages:
expo-doctor@1.10.1
Ok to proceed? (y) 
Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName"
Learn more: https://expo.fyi/root-expo-object
✔ Check Expo config for common issues
✔ Check package.json for common issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions

Detailed check results:

Error: Problems validating fields in /Users/chihhao/otaTest3/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'releaseChannel'.
 • should NOT have additional property 'displayName'.

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: jsEngine, updates, android, ios. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName"
Learn more: https://expo.fyi/root-expo-object
(node:20687) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.28 - expected version: ~51.0.31
  react-native@0.75.2 - expected version: 0.74.5
  typescript@5.0.4 - expected version: ~5.3.3
  @types/react@18.3.4 - expected version: ~18.2.79
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

above is `npx expo-doctor` result.
I'm not sure is help for you to improve this problem.

**Comment by mrevanzak** [comment]
did you solve it?

**Comment by iita71737** [comment]
> did you solve it?

not yet. I open the new issue.

**Comment by phanhuy111** [comment]
not solve
