### ISSUE TITLE
[expo-video] player instance in multiple VideoView components doesn't play in Android

### ISSUE THREAD

**Issue by deodad** [expo/expo#31248]
### Minimal reproducible example

https://github.com/deodad/expo-blank/tree/expo-video-shared-player

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Rendering a single player instance into multiple VideoView components works on iOS but not on Android.

On iOS the same video is played in both components. In Android the video remains in idle.

This is useful for building press-to-expand full screen players with custom controls as it allows a single player instance that is kept in sync in the two places it's being rendered.

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.local/state/fnm_multishells/8995_1724104540101/bin/node
      Yarn: 1.22.19 - ~/.local/state/fnm_multishells/8995_1724104540101/bin/yarn
      npm: 9.5.0 - ~/.local/state/fnm_multishells/8995_1724104540101/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /var/folders/1p/8plc0yx167q53qdktkcfd20m0000gn/T/frum_8888_1724104540085/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.31
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 11.0.2
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  typescript@5.5.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

**Comment by behenate** [comment]
@deodad  @hirbod We will try to solve it, but the issue is difficult and I'm not sure if we will be able to land it in SDK 52. Basically ExoPlayer doesn't support playing in multiple VideoViews from a single player and it's not something that can be done without landing a PR in ExoPlayer or doing our own fork of it. There also might be a reason why it's not supported and might be impossible to do with SurfaceView rendering alltogether 😕 
In that case it will probably be possible to archive a good result by [synchronising two players playing the same media with a `MediaClock`](https://github.com/google/ExoPlayer/issues/11265). The usage is really niche though (except for shared element transition with videos, which would be awesome) and we have some other features and bugs to resolve before we get to it.

**Comment by pdb3616109** [comment]
I have a similar problem. When I use expo-av, if there are more than 10 videos at the same time, some of them cannot be displayed.

**Comment by behenate** [comment]
@pdb3616109 That's a separate issue, as expo-video and expo-av are two different libraries (expo-video will be replacing expo-av). On Android displaying this many players at the same time is likely to be problematic, as it's really resource intensive.
