### ISSUE TITLE
expo/types is not published

### ISSUE THREAD

**Issue by pastelmind** [expo/expo#31250]
### Minimal reproducible example

https://github.com/pastelmind/expo-app-no-types

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

The `expo` package published to NPM does not contain the `types/` directory. (See https://unpkg.com/browse/expo@51.0.31/ to view published package contents)

Expo projects (bootstrapped with `create-expo-app`) generate an `expo-env.d.ts` in the project root directory with the following line:

```ts
/// <reference types="expo/types" />
```

I assume this is meant to import [`packages/expo/types/`](https://github.com/expo/expo/tree/0179a45151743aed2fa9d1995bec57cec8d2cacf/packages/expo/types). However, because this directory is not actually published, there is no `types/` directory under `node_modules/expo/`.

Perhaps `packages/expo/package.json` is misconfigured? Right now, it has no entry for `types/` under the `"files"` key:

https://github.com/expo/expo/blob/0179a45151743aed2fa9d1995bec57cec8d2cacf/packages/expo/package.json#L14-L39

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.local/state/fnm_multishells/7884_1725003674950/bin/node
      npm: 10.8.3 - ~/.local/state/fnm_multishells/7884_1725003674950/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.31 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Expo Doctor Diagnostics

Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by Kudo** [comment]
@marklawlor do you think we should put the [`types` files](https://github.com/expo/expo/tree/main/packages/expo/types) into the files of expo package.json?

**Comment by marklawlor** [comment]
@Kudo Yep created a PR here. https://github.com/expo/expo/pull/31339
