### ISSUE TITLE
[docs] A Next.js app with the recommended settings doesn't output the styles on SSR

### ISSUE THREAD

**Issue by illbexyz** [expo/expo#31272]
### Summary

Setting up an Expo with Next.js app with the recommended settings has an issue where the styles generated by `StyleSheet.create()` are not served in the HTML document.

### Reproduction

I made a reproduction where I just added a background color to the homepage ([commit](https://github.com/illbexyz/examples/commit/6abbf1da409e860d18e0dea61b844f731f140579)), which is not served in the HTML file.

Clone my reproduction:

```bash
git clone git@github.com:illbexyz/examples.git \
&& cd examples \
&& git checkout ssr-issue-reproduction \
&& cd with-nextjs \
&& npm install
```

Start the example:

```bash
npm start
```

Inspect the content of the HTML page and verify that the background color is missing:

![image](https://github.com/user-attachments/assets/c62a07cd-f852-46df-ab95-4d8e90a99d20)

The class is correctly set in the element, but its definition is missing:

![image](https://github.com/user-attachments/assets/ff930aff-243d-4de9-b72d-1ecdde7ec49f)

### Link to the related docs page

https://docs.expo.dev/guides/using-nextjs/

**Comment by amandeepmittal** [comment]
Closing this since the docs were updated in #31273.
