### ISSUE TITLE
React Native 0.75: in expo-dev-client crash

### ISSUE THREAD

**Issue by sync** [expo/expo#31288]
### Summary

I am having some dev client issues when loading remote branches when using latest expo + related and react-native 0.75.x and react 18.3.x. Reverting to react-native 0.74.x and react 18.2.x fixes the issue. 

See the repro repo, you can build and run it on simulator for example and select build from channel and it will crash.

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android, iOS

### Package versions

```
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.22",
    "expo-constants": "~16.0.2",
    "expo-dev-client": "~4.0.25",
    "expo-font": "~12.0.9",
    "expo-insights": "~0.7.0",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.18",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-updates": "~0.25.24",
    "expo-web-browser": "~13.0.3",
    "react": "~18.3.0",
    "react-dom": "~18.3.0",
    "react-native": "~0.75.0",
    "react-native-gesture-handler": "~2.18.1",
    "react-native-reanimated": "~3.15.0",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "~3.34.0",
    "react-native-web": "~0.19.10"
```

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.local/state/fnm_multishells/90070_1725259490205/bin/node
      Yarn: 1.22.22 - ~/.local/state/fnm_multishells/90070_1725259490205/bin/yarn
      npm: 10.2.4 - ~/.local/state/fnm_multishells/90070_1725259490205/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/anthonymittaz/.gem/ruby/2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.22 => 51.0.31 
      expo-router: ~3.5.18 => 3.5.23 
      react: ~18.3.0 => 18.3.1 
      react-dom: ~18.3.0 => 18.3.1 
      react-native: ~0.75.0 => 0.75.2 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: bare

### Reproducible demo

https://github.com/sync/seventyfive 

### Android
<img width="1725" alt="Screenshot 2024-08-29 at 7 45 48 AM" src="https://github.com/user-attachments/assets/ddee8cca-b6b9-45ae-a334-83b2090d96b0">

### iOS
<img width="1198" alt="Screenshot 2024-08-29 at 7 40 15 AM" src="https://github.com/user-attachments/assets/3c8d92b5-8250-4570-8e1c-308818ea39c7">

**Comment by sync** [comment]
cc @brentvatne we have a brief twitter chat, here is the linked issue

**Comment by Kudo** [comment]
can repro and confirm the issue. not specific expo-updates related, i can also repro on loading `npx expo start --no-dev` bundle

**Comment by Kudo** [comment]
i think that's more reanimated issue that similar to https://github.com/software-mansion/react-native-reanimated/issues/6415. i can repro this problem on a bare rnc-cli react-native 0.75 project with only reanimated installed. changing [enableDev=NO](https://github.com/facebook/react-native/blob/a1668e37e56e32aa7fbe8ca8cf08163937cb13ef/packages/react-native/React/Base/RCTBundleURLProvider.mm#L391) to test production bundle. i'm closing this issue and let's see if the newer reanimated resolving the 0.75 issue.
