### ISSUE TITLE
Debugging in Chrome Dev Tools Support for Tunnel using ngrok in devices

### ISSUE THREAD

**Issue by manganapathy** [expo/expo#31287]
### Summary

I am trying to use expo tunnel because of corporate firewall rules. But the challenge is when I use iPhone device with 'expo-dev-client' and tunneling, I am not able to launch Chrome Dev Tools for debugging purposes.
I also did not find documentation for enabling debugging using expo-dev-client + Tunnel + device(USB)

Steps to repro
1. Create a project using npx create-expo-app
2. Install expo dev client using npx expo install expo-dev-client
3. Yarn install at project root
4. pod install at iOS folder
5. npx expo start --tunnel       
6. Wait for app to launch and select the development server hosted from tunnel url in dev client 
7. App launches fine 
8. Press 'j' in the terminal to launch Chrome Dev Tools
9. Getting below error 
Debug: No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine. Learn more: https://docs.expo.dev/guides/using-hermes/

Please let me know if Debugging is supported when tunnel is used to host local server

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

 "expo-dev-client": "~4.0.21"

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.24 => 51.0.31 
      expo-router: ~3.5.20 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

### Reproducible demo

This is straight-forward issue with expo-dev-client + Tunnel in a attached iOS device. But I have done example project also 
https://github.com/manganapathy/expo-tunnel-debugging

<img width="1124" alt="Screenshot 2024-09-02 at 11 25 11 AM" src="https://github.com/user-attachments/assets/e56fa0bb-bf15-4d7d-92d9-c523b09047b5">

### Stacktrace (if a crash is involved)

› Metro waiting on exp+expo-devclient-issue://expo-development-client/?url=https%3A%2F%2Fjxipqo8-anonymous-8081.exp.direct
› Scan the QR code above to open the project in a development build. Learn more: https://expo.fyi/start

› Web is waiting on http://localhost:8081

› Using development build
› Press s │ switch to Expo Go

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundled 4738ms node_modules/expo-router/entry.js (1138 modules)
iOS Bundled 75ms node_modules/expo-router/entry.js (1 module)
Debug: No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine. Learn more: https://docs.expo.dev/guides/using-hermes/
Debug: No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine. Learn more: https://docs.expo.dev/guides/using-hermes/
› Stopped server

**Comment by manganapathy** [comment]
@byCedric Kindly request your thoughts here. 
curl http://tunnel-dever-server-url/json/list always returns empty. 
Only I am able to do debugging with localhost and simulator.

**Comment by manganapathy** [comment]
I think, I couldn't find test case for JSInspector supporting tunnel logic. May be I miss something because, yet to understand complete logic around tunneling ...
https://github.com/expo/expo/tree/924494bef268cbda38f9e4760deecbe63d9e652c/packages/%40expo/cli/src/start/server/middleware/inspector/__tests__

**Comment by manganapathy** [comment]
@byCedric Did some deep dive and below is the root cause. Kindly share your thoughts on the best possible solution. 

**RootCause:**
I originally went for tunnel to expose the RN packager to the connected device because internal firewall was blocking the incoming traffic. Now the traffic problem is solved with Tunnel. 
But...

When I launch debugger with 'j' option in the terminal, expo uses [createDebugMiddleware](https://github.com/expo/expo/blob/652ac651e0cf780bfdb5b7dd38fb4bbac6e53598/packages/%40expo/cli/src/start/server/metro/debugging/createDebugMiddleware.ts#L15) creates **_serverBaseUrl_** which resolves to machine IP and again facing issue with firewall blocking IP for websocket connection between app & CD tools. 

I even tried REACT_NATIVE_PACKAGER_HOSTNAME=localhost npx expo start --dev-client --tunnel. 
With above command it's able to open Chrome DevTools fine but source code is not loaded properly.

**Comment by manganapathy** [comment]
**Some Logs**
==========

app when I run "npx expo start --dev-client --tunnel"
{
    id: 'e506f553f82d753cdcfxxxxxxxxxxxxxcb2822e8aa--1',
    description: 'com.xxxxxxxx.xxxxxxxxx.xxx.xxx',
    title: 'React Native Experimental (Improved Chrome Reloads)',
    faviconUrl: 'https://reactjs.org/favicon.ico',
    devtoolsFrontendUrl: 'devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=192.168.XX.XXX%3A8081%2Finspector%2Fdebug%3Fdevice%3De506xxxxxxxxxxx3cdcf30b823817c5cb2822e8aa%26page%3D-1',
    type: 'node',
    webSocketDebuggerUrl: 'ws://192.168.XX.XXX:8081/inspector/debug?device=e506f553f8xxxxxxxdcf30b823817c5cb2822xxxx&page=-1',
    vm: "don't use",
    deviceName: 'iPhone 15 Pro',
    reactNative: {
      logicalDeviceId: 'e506f55xxxxxxxxxdcf30b823817c5cbxxxxxxxx',
      capabilities: {}
    }
  }
]


app when I run "REACT_NATIVE_PACKAGER_HOSTNAME=localhost npx expo start --dev-client --tunnel"
 {
    id: 'e506f553f82d753cdcxxxxxxxxxxxxxx822e8aa-18',
    description: 'com.xxxxxxxx.xxxxxxxxx.xxx.xxx',
    title: 'Hermes Bridgeless React Native',
    faviconUrl: 'https://reactjs.org/favicon.ico',
    devtoolsFrontendUrl: 'devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=localhost%3A8081%2Finspector%2Fdebug%3Fdevice%3De506f5xxxxxxxxxxxxxf30b823817c5cb2822e8aa%26page%3D18',
    type: 'node',
    webSocketDebuggerUrl: 'ws://localhost:8081/inspector/debug?device=e506f553f8xxxxxxxdcf30b823817c5cb2822xxxx&page=18',
    vm: 'Hermes',
    deviceName: 'iPhone 15 Pro',
    reactNative: {
      logicalDeviceId: 'e506f55xxxxxxxxxdcf30b823817c5cbxxxxxxxx',
      capabilities: {}
    }
  }

**Comment by manganapathy** [comment]
DevTools URL
==========
https://chrome-devtools-frontend.appspot.com/serve_rev/@d9568d04d7dd79269cxxxxxxxxxxxxxxxxxxx6/devtools_app.html?panel=console&ws=127.0.0.1%3A8081%2Finspector%2Fdebug%3Fdevice%3De506f553f82d753cdcf30bxxxxxxxxxxxxxxxxxxx%26page%3D-1
++++++++++++++++====== HANDLERS FACTORY {
  page: {
    id: '-1',
    title: 'React Native Experimental (Improved Chrome Reloads)',
    vm: "don't use",
    app: 'com.xxxxxxxxx.xxxxxxxx.app.xxx',
    capabilities: {}
  },
  debugger: {
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
    sendMessage: [Function: sendMessage]
  },
  device: {
    appId: 'com.xxxxxxxxx.xxxxxxxx.app.xxx',
    id: 'e506f55xxxxxxxxxdcf30b823817c5cbxxxxxxxx',
    name: 'iPhone 15 Pro',
    sendMessage: [Function: sendMessage]
  }
}

**Comment by prashanFOMO** [comment]
I'm running into this as well - curious if there's a workaround!

**Comment by chitranjan-gupta** [comment]
@manganapathy @prashanFOMO you guys can use this blog https://medium.com/@chitranjankumargupta/expo-react-native-devtools-debugging-41eda7cf8031 which i have written to access Expo React Native Devtools using ngrok tunnel

**Comment by prashanFOMO** [comment]
@chitranjan-gupta that's great, but I shouldn't have to download an unofficial chrome extension to get this to work. I believe this issue should be re-opened.

**Comment by chitranjan-gupta** [comment]
@prashanFOMO If you don't want to download the extension, you can follow the Method 2 to open React Native Devtools

**Comment by prashanFOMO** [comment]
@chitranjan-gupta I get stuck on step 5 of that method - the array is always empty regardless of if there is a device connected it seems.

**Comment by chitranjan-gupta** [comment]
@prashanFOMO which version of React Native are you using ? I am using "react-native": "0.76.6";

**Comment by ertugrulakca** [comment]
`REACT_NATIVE_PACKAGER_HOSTNAME=localhost npx expo start --clear`
Helped this one thank you
