### ISSUE TITLE
Customizing Android App Theme

### ISSUE THREAD

**Issue by Palisand** [expo/expo#313]
Is there any way to customize the android `AppTheme` without detaching and editing *styles.xml* directly?

If it's not currently possible, it would be cool if we could set `colorPrimary`, `colorPrimaryDark`, `colorControlActivated`, `colorAccent`, etc. through *app.json*.

**Comment by dikaiosune** [comment]
Hi! This seems like a great idea. I created a [feature request](https://expo.canny.io/feature-requests/p/customize-android-apptheme) for this and we'll track it there. Thanks!
