### ISSUE TITLE
App crashes on getAssetsAsync when access is limited and no photos selected

### ISSUE THREAD

**Issue by moritzkarliczek** [expo/expo#31302]
### Minimal reproducible example

https://snack.expo.dev/@moritz.karliczek/expo-media-library-bug?platform=ios

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

The app crashes when calling `getAssetsAsync()` with the `sortBy` option set to a pair `[key, ascending]` in `AssetOptions` when the photo permission is set to "limited" and no photos are selected. This seems to be an edge case, but it consistently causes a crash under these conditions.

**Steps to Reproduce**

1. Set photo permissions to "limited".
2. Ensure no photos are selected.
3. Call `getAssetsAsync()` with `sortBy` set to `[key, ascending]` in `AssetOptions`.

**Observed Behavior**

The app crashes when `sortBy` is set in `AssetOptions`.

 **Expected Behavior**

The app should handle this scenario gracefully and not crash, even when `sortBy` is specified and no photos are selected.

**Additional Notes**

Removing the `sortBy` option prevents the crash, suggesting that the issue is related to how `getAssetsAsync()` handles the `sortBy` option in this specific scenario.

### Environment

-

### Expo Doctor Diagnostics

-

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I believe I fixed a similar issue [here](https://github.com/expo/expo/pull/29969/files) but it's not yet released.

However, the bug I was fixing had different reproduction steps. Hopefully my change should cover your case as well - would you be able to take the changes from [this file](https://github.com/expo/expo/pull/29969/files#diff-a9ca1b768462e2ff3fd1669fc571e5a001f46fae91984549350c8d58dd605710) and confirm with me that they resolve your issue? I'd then have more confidence in cherry-picking the fix and releasing it sooner.

Thank you 🙂

**Comment by moritzkarliczek** [comment]
@vonovak yes! I can confirm that these changes resolve my issue. Thank you :)

**Comment by vonovak** [comment]
> @vonovak yes! I can confirm that these changes resolve my issue. Thank you :)

Thanks for confirming. The fix was cherry-picked to sdk-51 branch and will be available with the next release (a few days usually).
