### ISSUE TITLE
Location.startLocationUpdatesAsync running once a second, docs don't accurately reflect config parameters

### ISSUE THREAD

**Issue by dereknelson** [expo/expo#3130]
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.1 => 3.0.8

Basically, `Location.startLocationUpdatesAsync` was calling the associated function a few times a second. In the [docs](https://github.com/expo/expo/blob/sdk-32/docs/versions/unversioned/sdk/location.md#arguments-6) it says timeInterval and distanceInterval are android only:
> - timeInterval (number) 
Minimum time to wait between each update in milliseconds. Default value depends on accuracy option. (Android only)
> - distanceInterval (number) 
Receive updates only when the location has changed by at least this distance in meters. Default value depends on accuracy option. (Android only)

However, adding timeInterval and distanceInterval successfully slowed down the updates on iOS. Is this expected behavior? Or am I missing something? If it's expected, the docs shouldn't reflect android only. 

### Steps to Reproduce

1. Register task with TaskManager
2. Start location updates with same task
3. View console log to see how often it is called

Relevant code: 
```
export const BACKGROUND_LOCATION_UPDATES_TASK = 'background-location-updates'

TaskManager.defineTask(BACKGROUND_LOCATION_UPDATES_TASK, handleLocationUpdate)

export async function handleLocationUpdate({ data, error }) {
    console.log('location update')
    if (error) {
		return
	}
     if (data) {
        try {
            const { locations } = data
            console.log('locations',locations)
        } catch (error) {
            console.log('the error',error)
        }
    }
}

export async function initializeBackgroundLocation(){
    let isRegistered = await TaskManager.isTaskRegisteredAsync(BACKGROUND_LOCATION_UPDATES_TASK)
    if (!isRegistered) await Location.startLocationUpdatesAsync(BACKGROUND_LOCATION_UPDATES_TASK, {
        accuracy: Location.Accuracy.High,
        /* after edit */
        timeInterval: 2500,
        distanceInterval: 5,
    })
}
```

### Expected Behavior
time/distance interval to have no effect on ios

### Actual Behavior
time/distance interval does have an effect on ios
[No time/distance interval](http://prntscr.com/m3jy25)
[time/distance interval of 2500, 5, respectively](http://prntscr.com/m3jyad). I had to run around my house for it to log.

**Comment by tsapeta** [comment]
Hey @dereknelson and thanks for this good catch!
You're right that `distanceInterval` does have an effect on iOS too and there is a mistake in the documentation. I'll fix it shortly.

Also, just to clarify, there is one case in which this parameter doesn't have an effect on iOS, according to [Apple documentation](https://developer.apple.com/documentation/corelocation/cllocationmanager/1423500-distancefilter?language=objc):
```
This property is used only in conjunction with the standard location services and is not used when monitoring significant location changes.
```

Significant location changes are used to wake up the application from killed/terminated state and we can't change what `significant` means 🤷‍♂️

**Comment by dereknelson** [comment]
@tsapeta no problem! thanks for the quick fix & clarification!

I had a question regarding permissions, is there a way to determine whether the user has enabled "only while using" vs. "always"?

**Comment by tsapeta** [comment]
@dereknelson yes, there is such way but seems that it's not documented properly 😞 You can determine that by checking `ios` property of the object resolved by `getAsync` or `askAsync`. See the snippet:
```javascript
const { status, ios } = await Permissions.getAsync(Permissions.LOCATION);
// `ios` is an object (if on iOS platform) of type: { scope: 'whenInUse' | 'always' | 'none' }
```

**Comment by dereknelson** [comment]
@tsapeta awesome! I was worried I was going to have to get crafty to figure it out, haha. I can open a PR to put that in the docs!

**Comment by tsapeta** [comment]
@dereknelson sure, that would be cool! thanks 😄
