### ISSUE TITLE
ImagePicker exception: "Image decoding failed"

### ISSUE THREAD

**Issue by marcoazn89** [expo/expo#3132]
Hello,

Device: Android
SDK: 31.0.0

I'm getting "Error: Image decoding failed." when calling ImagePicker.launchImageLibraryAsync(). I followed the exact same example showed here:
https://docs.expo.io/versions/latest/sdk/imagepicker

I see this error is coming from: https://github.com/expo/expo/blob/master/android/versioned-abis/expoview-abi28_0_0/src/main/java/abi28_0_0/host/exp/exponent/modules/api/ImagePickerModule.java#L322

Has anybody experienced this issue? Is there a fix?

**Comment by naorzr** [comment]
also getting the same error on android 8.1, doesn't happend on a standalone app, only through expo client.

**Comment by KamranFekri** [comment]
I'm suddenly getting this error too. Expo version 2.10.1

**Comment by tarzan1110** [comment]
I also have this problem. When I use ImagePicker.launchCameraAsync, it says.
"Image decoding failed"

**Comment by tomermoshe** [comment]
I'm getting the same error as well

**Comment by sasurau4** [comment]
I managed to reproduce the problem on snack.
https://snack.expo.io/@sasurau4/expo_3132

Flips `allowsEditing` option to false may cause the problem.
The workaround is to set `allowsEditing` as true.

**Comment by ClassyD** [comment]
I can verify the above works (as a workaround )

**Comment by jannikbuschke** [comment]
+1 same issue

**Comment by edgaru** [comment]
Same issue with SDK 28 and 26.

**Comment by rv-alake** [comment]
I'm seeing this issue as well with emulators on Android 7.1 and Expo SDK 31.

**Comment by giautm** [comment]
Same issues with me.

**Comment by KlymSerhii** [comment]
I have same issue. Workaround for now - downgrade mobile android expo version to 2.9.2 (if you have this issue on android phone)

**Comment by andymax** [comment]
Why is it closed? It's not fixed?

**Comment by sjchmiela** [comment]
Fix is now available in Expo Client v2.10.3 (should already be available on the Play Store). 🙂

**Comment by marcoazn89** [comment]
Thank you for the quick resolution!
