### ISSUE TITLE
Integrity verification failed

### ISSUE THREAD

**Issue by Intellidevelopers** [expo/expo#31337]
### Summary

C:\Users\A.J Full Stack\swiftpay\swiftpay>eas update --branch production
> npx expo install expo-updates
[expo-cli] Error: Integrity verification failed for sha512-J45V2ZVWJVr41PW3dMDXR04m6iIWXO02gbQtlcNcWX+QTRid/q5roV8bFRiC2WvsvAevu8DaZMuMcUhlOHQdzQ== (C:\Users\A.J Full Stack\.expo\native-modules-cache\content-v2\sha512\27\8e\55d99556255af8d4f5b774c0d7474e26ea22165ced3681b42d95c35c597f904d189dfeae6ba15f1b151882d96becbc07afbbc0da64cb8c71486538741dcd)
[expo-cli] Error: Integrity verification failed for sha512-J45V2ZVWJVr41PW3dMDXR04m6iIWXO02gbQtlcNcWX+QTRid/q5roV8bFRiC2WvsvAevu8DaZMuMcUhlOHQdzQ== (C:\Users\A.J Full Stack\.expo\native-modules-cache\content-v2\sha512\27\8e\55d99556255af8d4f5b774c0d7474e26ea22165ced3681b42d95c35c597f904d189dfeae6ba15f1b151882d96becbc07afbbc0da64cb8c71486538741dcd)
[expo-cli]     at integrityError (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\cacache\lib\content\read.js:160:15)
[expo-cli]     at read (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\cacache\lib\content\read.js:31:11)
[expo-cli]     at async AsyncFunction.getDataByDigest [as byDigest] (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\cacache\lib\get.js:48:15)
[expo-cli]     at async FileSystemCache.get (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\@expo\cli\build\src\api\rest\cache\FileSystemCache.js:44:28)
[expo-cli]     at async getResponse (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\@expo\cli\build\src\api\rest\cache\wrapFetchWithCache.js:166:27)
[expo-cli]     at async getNativeModuleVersionsAsync (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\@expo\cli\build\src\api\getNativeModuleVersions.js:17:21)
[expo-cli]     at async getVersionedNativeModulesAsync (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\@expo\cli\build\src\start\doctor\dependencies\bundledNativeModules.js:83:20)
[expo-cli]     at async getCombinedKnownVersionsAsync (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\@expo\cli\build\src\start\doctor\dependencies\getVersionedPackages.js:60:47)
[expo-cli]     at async getVersionedPackagesAsync (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\@expo\cli\build\src\start\doctor\dependencies\getVersionedPackages.js:101:28)
[expo-cli]     at async installPackagesAsync (C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\@expo\cli\build\src\install\installAsync.js:140:24)
C:\Users\A.J Full Stack\swiftpay\swiftpay\node_modules\expo\bin\cli exited with non-zero code: 1
    Error: update command failed.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

51

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-233.14808.21.2331.11842104

### Minimal reproducible example

https://github.com/intellidevelopers/swiftpay

**Comment by luizsandoval** [comment]
I'm having the same issue!

**Comment by brentvatne** [comment]
hi there! check out this comment on the npm repo: https://github.com/npm/cli/issues/960#issuecomment-593339940

this seems unrelated to expo itself
