### ISSUE TITLE
Can't delete assets - deleteAssetsAsync()

### ISSUE THREAD

**Issue by juleschavent** [expo/expo#31340]
### Summary

I'm building a personal app for my android phone.
My goal is that review media taken on a day and delete a selection when they've all been reviewed.

I was trying to use `MediaLibrary.deleteAssetsAsync` and pass it an array of assets ID.

When I run the query it doesn't throw any error and return `true` as it should.

But the assets never get actually deleted on the device.

At first I was thinking of a missing permission so I've checked it with `getPermissionsAsync` and `requestPermissionsAsync`. Also checked my app.json.

For science I then tried to create a new album -> move the selected assets to this album -> delete the album.

And this works.... but it seems really sketchy and over complicated for such a trivial task no?!

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

```
"dependencies": {
    "@expo/metro-runtime": "~3.2.3",
    "@expo/vector-icons": "^14.0.2",
    "@react-native-community/datetimepicker": "8.0.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/stack": "^6.4.1",
    "@tanstack/react-query": "^5.52.2",
    "expo": "^51.0.31",
    "expo-asset": "^10.0.10",
    "expo-av": "~14.0.7",
    "expo-media-library": "~16.0.4",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-dotenv": "^3.4.11",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-modal-datetime-picker": "^18.0.0",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10"
  },

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-35 | Google APIs ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.31 => 51.0.31
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed

### Reproducible demo

.

**Comment by helloukey** [comment]
Still facing this issue
