### ISSUE TITLE
exit 0 after npx expo run:android

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo#31343]
### Summary

Not sure if it's a bug technically, but I can't get a success exit code while running

````
npx expo run:android
````

It ends up with:

````
BUILD SUCCESSFUL in 18s
1513 actionable tasks: 14 executed, 1499 up-to-date
Waiting on http://localhost:8081
› Opening exp+****://expo-development-client/?url=...
````

I am using this command in a custom script, so having an exit code would be helpful.

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
      Yarn: 4.1.1 - /usr/local/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
      Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 23, 31, 32, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-23 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-30 | AOSP ATD ARM 64 v8a, android-30 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 11.0.14 => 11.0.14 
      expo: 51.0.32 => 51.0.32 
      expo-router: 3.5.23 => 3.5.23 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: ^0.75.2 => 0.75.2 
      react-native-web: 0.19.11 => 0.19.11 
    Expo Workflow: bare

### Minimal reproducible example

`npx expo run:android`

**Comment by brentvatne** [comment]
the process doesn't exit because it is starting the dev server. you can run it with `--no-bundler` if you start the dev server in another tab

**Comment by RohovDmytro** [comment]
No, that does not help. I forgot to mention that the server is already running in another tab, so effectively this command does not manage a server.

**Comment by brentvatne** [comment]
```bash
~/code/test-rohov git:(main)
npx expo run:android --no-bundler

(redacted irrelevant stuff)

BUILD SUCCESSFUL in 43s
337 actionable tasks: 137 executed, 200 from cache
Waiting on http://localhost:8081
› Opening com.brents.testrohov://expo-development-client/?url=http%3A%2F%2F192.168.0.201%3A8081 on Pixel_3a_API_34_extension_level_7_arm64-v8a

~/code/test-rohov git:(main)
echo $?
0
```

**Comment by RohovDmytro** [comment]
@brentvatne Ive'tried it and it worked once, I've tried it again and it did not exit. Could not later reproduce.

Not sure what's going on. My only it that `expo run` was waiting for a keystroke, but not sure why it's stopped working.

<img width="851" alt="image" src="https://github.com/user-attachments/assets/00c302d7-bf1c-422e-9890-9914856cdd44">

**Comment by RohovDmytro** [comment]
It was not working until I've deleted `.expo` & `.expo-shared` folders. Now it's all good.

Fix:

1. `rm -rf .expo`
2. `rm -rf .expo-shared`

**Comment by RohovDmytro** [comment]
@brentvatne the problem is within `.expo` folder:

1. npx expo start
2. npx expo run:ios
3. npx expo run:android (hangs out)

Editing .expo/device.json to have an empty array fixes the issue and makes run:android work as expected.
