### ISSUE TITLE
ImageManipulator.manipulateAsync not working on Android with SDK 31.0.0

### ISSUE THREAD

**Issue by ewein** [expo/expo#3136]
Hi, I'm trying to take a picture, resize it and then display it to the user. Currently this is working fine on iOS but on Android the call to ImageManipulator is failing. Here is a Snack (https://snack.expo.io/Byy0BxxGV) where you can reproduce the issue on Android. When selecting an image it should display it above the same as it does on iOS. If you comment out the call to the ImageManupulator you will see that it works as expected on Android and iOS. Thanks for your help!

### Environment
```
  Expo CLI 2.6.13 environment info:
    System:
      OS: Linux 4.4 Ubuntu 16.04.2 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/bin/node
      Yarn: 1.0.2 - /usr/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^31.0.4 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.6.13
```

**Comment by 0plus1** [comment]
I have the exact same issue, catching the manipulateAsync failed promise it returns this error:

`Warning
11:06
[Unhandled promise rejection: Error: Opening the image failed.]

Stack trace:
  node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:146:41 in createErrorFromErrorData
  node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:55 in <unknown>
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:397:4 in __invokeCallback
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:28 in <unknown>
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:17 in invokeCallbackAndReturnFlushedQueue`

Issue started after upgrading to new expo app on device a couple of hours ago..

**Comment by m25cesar** [comment]
I have the same issue to on the manipulate function in this code.

```
const { uri } = await ImageManipulator.manipulate(
      imageUri,
      [{ resize: { width: 918 } }],
      { compress: 0.5 },
);
```

i get this error

```
[11:22:16] [Unhandled promise rejection: Error: Opening the image failed.]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:121:42 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:78:57 in <unknown>
- ... 5 more stack frames from framework internals
```

**Comment by nadavpld** [comment]
Same issue over here.
Works when deploying a standalone apk.

`            const manipulatedPhoto = await ImageManipulator.manipulateAsync(
                photo.uri,
                [{ flip: { horizontal: true }}],
                { format: 'jpg', base64: true }
            );`

following error is thrown
`
Opening the image failed.
node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:95:55 in <unknown>
node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:397:4 in __invokeCallback
... 4 more stack frames from framework internals
`

**Comment by neohades** [comment]
exact same thing here :(

**Comment by daihalu** [comment]
Same issue

**Comment by srhelle** [comment]
I also have the same issue: 
`const useWidth = tempPhoto.width < tempPhoto.height;
const resizeArgument = useWidth ? { resize: { width: 1000 } } : { resize: { height: 1000 } };
const { uri: resizedUri } = await ImageManipulator.manipulateAsync(tempPhoto.uri, [resizeArgument]);`

This worked just fine before the new version of the expo app.

**Comment by TimAbraldes** [comment]
I'm using [ImageManipulator.manipulate from Expo SDK v30.0.0](https://docs.expo.io/versions/v30.0.0/sdk/imagemanipulator#expoimagemanipulatormanipulateuri-actions-saveoptions) and I'm seeing the same error.

This issue is **not present** in Expo versions `2.8.0`, `2.9.1`, or `2.9.2`, corresponding to version codes `94`, `97`, or `98`.
This issue **is present** in Expo versions `2.10.1` and `2.10.2`, corresponding to version codes `100` and `101`.

**Comment by sjchmiela** [comment]
Fix has been deployed in Expo Client v2.10.3 (should already be available on the Play Store). 🙂

**Comment by imasif** [comment]
thanks @sjchmiela

**Comment by ptariche** [comment]
The same issue is occurring on iOS

**Comment by nandorojo** [comment]
> The same issue is occurring on iOS with SDK 32. The manipulate function no longer exists as documented. https://docs.expo.io/versions/v32.0.0/sdk/imagemanipulator only manipulateAsync which is not documented.

Savior. Thanks for bringing that up. Fixed it for me.

**Comment by maxgfr** [comment]
I still have this problem...

**Comment by brentvatne** [comment]
@maxgfr - create a new issue with a minimal reproducible example, the example provided in the original post works just fine on sdk 32, i tried it myself here: https://snack.expo.io/@react-navigation/supportive-graham-crackers
