### ISSUE TITLE
EAS Build: Unrecognized native architecture for directory 'lib/riscv64'

### ISSUE THREAD

**Issue by srgoogle23** [expo/expo#31370]
### Minimal reproducible example

private!

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

On run "eas build --platform android --profile production", in the run gradlew:

[RUN_GRADLEW] > Task :app:validateSigningRelease
[RUN_GRADLEW] > Task :app:parseReleaseIntegrityConfig
[RUN_GRADLEW] > Task :app:mergeReleaseNativeLibs
[RUN_GRADLEW] > Task :app:stripReleaseDebugSymbols
[RUN_GRADLEW] Unable to strip the following libraries, packaging them as they are: libimage_processing_util_jni.so.
[RUN_GRADLEW] > Task :app:buildReleasePreBundle
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
[RUN_GRADLEW] > Task :app:extractReleaseNativeSymbolTables
[RUN_GRADLEW] > Task :app:packageReleaseBundle FAILED
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryCollectModulesCleanUp
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:packageReleaseBundle'.
[RUN_GRADLEW] > A failure occurred while executing com.android.build.gradle.internal.tasks.PackageBundleTask$BundleToolWorkAction
[RUN_GRADLEW]    > Unrecognized native architecture for directory 'lib/riscv64'.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 4m 43s
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
[RUN_GRADLEW] 1061 actionable tasks: 1061 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1

My eas.json:
{
  "cli": {
    "version": ">= 5.9.3",
    "appVersionSource": "local"
  },
  "build": {
    "preview": {
      "android": {
        "buildType": "apk"
      },
      "env": {
        "SENTRY_LOG_LEVEL": "debug",
        "SENTRY_DISABLE_AUTO_UPLOAD": "false",
        "ANDROID_SDK_ROOT": "/mypathtosdk/sdk",
        "SENTRY_AUTH_TOKEN": "token sentry"
      },
      "channel": "preview"
    },
    "previewBundle": {
      "env": {
        "SENTRY_LOG_LEVEL": "debug",
        "SENTRY_DISABLE_AUTO_UPLOAD": "false",
        "ANDROID_SDK_ROOT": "/mypathtosdk/sdk",
        "SENTRY_AUTH_TOKEN": "token sentry"
      },
      "channel": "preview"
    },
    "production": {
      "env": {
        "SENTRY_LOG_LEVEL": "debug",
        "SENTRY_DISABLE_AUTO_UPLOAD": "false",
        "ANDROID_SDK_ROOT": "/mypathtosdk/sdk",
        "SENTRY_AUTH_TOKEN": "token sentry"
      },
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 9.8.0 - /opt/homebrew/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.31 => 51.0.32 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 12.1.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Expo Doctor Diagnostics

npx expo-doctor@latest
Need to install the following packages:
  expo-doctor@1.10.1
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by srgoogle23** [comment]
ps: If I generate an .apk, it generates normally, but I can't use it to upload to the Play Store, because it gives the same error, but when uploading to the Play Store

Building locally and on expo.dev, it gives the same result

Using expo run:android, it works on my cell phone (which is connected to ADB) as well as on the simulators.

**Comment by efstathiosntonas** [comment]
Started getting this too when uploading release version on Play Store: 

```
[!] Google Api Error: Invalid request - Your app declares support for 'riscv64' architecture, but the following libraries are missing: [libVisionCamera.so, libandroidlame.so, libanimation-decoder-gif.so, libavcodec.so, libavdevice.so, libavfilter.so, libavformat.so, libavif_android.so, libavutil.so, libbarhopper_v3.so, libbugsnag-ndk.so, libbugsnag-plugin-android-anr.so, libbugsnag-root-detection.so, libc++_shared.so, libcrsqlite.so, libcrypto.so, libexpo-av.so, libexpo-modules-core.so, libfabricjni.so, libfbjni.so, libffmpegkit.so, libffmpegkit_abidetect.so, libfolly_runtime.so, libgifimage.so, libglog.so, libhermes.so, libhermes_executor.so, libhermesinstancejni.so, libimagepipeline.so, libjscinstance.so, libjsi.so, libjsijniprofiler.so, libjsinspector.so, libmapbox-common.so, libmapbox-maps.so, libmapbufferjni.so, libnative-filters.so, libnative-imagetranscoder.so, libop-sqlite.so, libreact-native-keys.so, libreact_codegen_rncore.so, libreact_debug.so, libreact_devsupportjni.so, libreact_featureflags.so, libreact_featureflagsjni.so, libreact_nativemodule_core.so, libreact_nativemodule_defaults.so, libreact_nativemodule_dom.so, libreact_nativemodule_featureflags.so, libreact_nativemodule_microtasks.so, libreact_newarchdefaults.so, libreact_performance_timeline.so, libreact_render_componentregistry.so, libreact_render_consistency.so, libreact_render_core.so, libreact_render_debug.so, libreact_render_graphics.so, libreact_render_imagemanager.so, libreact_render_mapbuffer.so, libreact_render_observers_events.so, libreact_render_uimanager_consistency.so, libreact_utils.so, libreactnativeblob.so, libreactnativejni.so, libreanimated.so, librninstance.so, librnscreens.so, librrc_image.so, librrc_legacyviewmanagerinterop.so, librrc_textinput.so, librrc_view.so, libruntimeexecutor.so, libsqlite_vec.so, libstatic-webp.so, libswresample.so, libswscale.so, libturbomodulejsijni.so, libucrop.so, libuimanagerjni.so, libunistyles.so, libworklets.so, libyoga.so, libavcodec_neon.so, libavdevice_neon.so, libavfilter_neon.so, libavformat_neon.so, libavutil_neon.so, libffmpegkit_armv7a_neon.so, libswresample_neon.so, libswscale_neon.so]. Update your app to rely on libraries that support 'riscv64' architecture.
```

**Comment by efstathiosntonas** [comment]
this issue should not be closed @brentvatne @lukmccall @tsapeta @EvanBacon (sorry for tagging you all guys but this seems serious as we can't ship on Play Store)

**Comment by efstathiosntonas** [comment]
@srgoogle23 are you using the latest version of react-native-vision-camera@4.5.3? 

It seems that CameraX to 1.5.0-alpha01 is breaking the builds. After downgrading to 4.5.2 Google Play accepted the binary.

**Comment by srgoogle23** [comment]
do not use this issue, use https://github.com/expo/expo/issues/31371
this one does not have the test example and in the test example you will see that I use version 3.8.2 of this module

**Comment by lucksp** [comment]
FWIW I also am getting this error on Android EAS build
