### ISSUE TITLE
Cannot properly drag SVG

### ISSUE THREAD

**Issue by spyshower** [expo/expo#3139]
Hello,

I am trying to implement a clock in which a user can touch a pointer and move it. This behavior works as expected on iOS but not on Android. Specifically, when you touch the pointer the 1st time it works normally, however after that while the View is being displayed at the right point on the clock, the actual View(?) is in it’s original spot (invisible, but it’s there).

Snacks:

https://snack.expo.io/@spyshower/clock-svg 1 (check the onTouchEvent(…) function)

https://snack.expo.io/@spyshower/smiling-blueberries

I face this issue for over a month. I hoped that Expo SDK 32 would fix it but it didn't. Please help.

**Comment by spyshower** [comment]
I would like the thoughts of an admin here please.

**Comment by brentvatne** [comment]
you can ask on http://github.com/react-native-community/react-native-svg

**Comment by spyshower** [comment]
@brentvatne I did and I got no answer. Honestly I don't know what else to do. The issue cannot get simpler than that and it seems I am the only one in earth that faces it.

**Comment by brentvatne** [comment]
we don't build react-native-svg, we just pull it in. sorry we can't provide support for it, but if it's important to you then i encourage you to reach out to one of the consultants on https://expo.io/consultants

**Comment by brentvatne** [comment]
one thing you could do to work around it is put a normal view on top and listen for touch events on that view. you wouldn't be able to target the hand of the clock exactly but you could apply it to the entire view
