### ISSUE TITLE
Compatibility issues with react-flow-props-to-prop-types

### ISSUE THREAD

**Issue by sonaye** [expo/expo#314]
I am trying to use [babel-plugin-react-flow-props-to-prop-types](https://github.com/thejameskyle/babel-plugin-react-flow-props-to-prop-types) within an Expo app. Basically this plugin allows me to go from:
```javascript
class Button extends Component {
  props: {
    label: string,
    disabled?: boolean
  };
}
```

to:
```javascript
class Button extends Component {
  static propTypes = {
    label: PropTypes.string.isRequired,
    disabled: PropTypes.bool
  };
}
```

After installation and configuration:
```
yarn add prop-types prop-types-extra
yarn add --dev babel-plugin-react-flow-props-to-prop-types
```

```
{
  "presets": ["expo"],
  "plugins": ["react-flow-props-to-prop-types"]
}
``` 

I get the following error:
<img src="https://user-images.githubusercontent.com/23000873/27684076-0a3de7be-5cd1-11e7-81a9-4527ec45684b.png" width="400">

Any ideas on what is causing this and how to fix it?

**Comment by brentvatne** [comment]
maybe a bug in babel-plugin-react-flow-props-to-prop-types? sorry I don't know anything about that library, seems neat though

**Comment by sonaye** [comment]
I am guessing it has to do with an unsupported type present in https://github.com/expo/expo-sdk/blob/master/src/AV.js.

<img width="634" alt="screen shot 2017-06-30 at 10 21 01 am" src="https://user-images.githubusercontent.com/23000873/27725229-0a9122fa-5d7e-11e7-9564-8ea22a47080e.png">

**Comment by sonaye** [comment]
That's definitely the issue.
