### ISSUE TITLE
Android prebuild issue with SDK 52 canary

### ISSUE THREAD

**Issue by StefSchalks** [expo/expo#31403]
### Summary

Hey!

I initialized an app using `npx create-expo-app` and then upgraded it to use the latest canary release using `npm install expo@canary` since I wanted to expirement with the new DOM components feature. 

Now, I changed nothing in the code (so it's just the basic App.js saying 'Open up App.js to start working on your app!'). When I ran `npx expo run:android` and completed all steps in the cli, it starts by creating the android folder. When it starts prebuilding, it crashes immediately and shows the error:
```
AssertionError [ERR_ASSERTION]: [android.dangerous]: withAndroidDangerousBaseMod: Project file "MainApplication" does not exist in android project for root "[APP PATH]"
```

When I go check if the file exists, I can see there is a `MainApplication.kt` file in the android folder.

This only happens with the canary since doing the exact same thing with SDK 51 does work and build the app as expected.

Are there any solutions for this?

--------------------------------------------------------------------------------------
The exact versions that my app uses are:
```
"dependencies": {
    "expo": "^52.0.0-canary-20240904-69100c1",
    "expo-status-bar": "1.12.2-canary-20240904-69100c1",
    "react": "18.3.1",
    "react-native": "0.75.2",
    "react-native-webview": "13.8.6"
  },
```

### What platform(s) does this occur on?

Android

### SDK Version

52.0.0-canary-20240904-69100c1

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.12.2 - D:\Programs\NodeJS\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.5.0 - D:\Programs\NodeJS\npm.CMD
    npmPackages:
      expo: ^52.0.0-canary-20240904-69100c1 => 52.0.0-canary-20240904-69100c1
      react: 18.3.1 => 18.3.1
      react-native: 0.75.2 => 0.75.2
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/StefSchalks/expo-android-run-test

**Comment by Sietze111** [comment]
I am running into the same issue and I as far as I can oversee any android build would too.

**Comment by e-Naeim** [comment]
same issue

**Comment by Guysnacho** [comment]
Can confirm, I don't have a nearly as bare setup but facing the same issue.
f8bc952: Bump versions again

**Comment by godavdev** [comment]
Same here

**Comment by Maclay74** [comment]
Facing the same error. Let's have a look:
There is a function that throws this error:
```ts
export function getProjectFilePath(projectRoot: string, name: string): string {
  const filePath = globSync(
    path.join(projectRoot, `android/app/src/main/java/**/${name}.@(java|kt)`)
  )[0];
  assert(
    filePath,
    `Project file "${name}" does not exist in android project for root "${projectRoot}"`
  );

  return filePath;
}
```
It's compiled version looks like this and can be found here: `node_modules/@expo/config-plugins/build/android/Paths.js`
```js
function getProjectFilePath(projectRoot, name) {
  const filePath = (0, _glob().globSync)(path().join(projectRoot, `android/app/src/main/java/**/${name}.@(java|kt)`))[0];
  (0, _assert().default)(filePath, `Project file "${name}" does not exist in android project for root "${projectRoot}: ": `);
  return filePath;
}
```
The problem is `filePath` is undefined for some reason. I just copied absolute path for `MainApplication.kt` and returned it instead. 

Anyway, it won't help build the app, you'll have to fix `node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.kt`. 

Fix `updateState` method signature, so third argument `stateWrapper` wasn't optional:
```kt
override fun updateState(
        view: Screen,
        props: ReactStylesDiffMap?,
        stateWrapper: StateWrapper
    )
```

After those fixes, the current version should build correctly.

**Comment by erickriva** [comment]
@Maclay74 `react-native-screens` fixed it in [4.0.0-beta.13](https://github.com/software-mansion/react-native-screens/releases/tag/4.0.0-beta.13)

**Comment by Guysnacho** [comment]
> @Maclay74 `react-native-screens` fixed it in [4.0.0-beta.13](https://github.com/software-mansion/react-native-screens/releases/tag/4.0.0-beta.13)

Doesn't seem to be the case, I'm still facing the issue on `52.0.0-canary-20241021-c4b5a93` with `react-native-screens@4.0.0-beta.13`.

![image](https://github.com/user-attachments/assets/6c4446af-caf4-4923-a1d1-8408802f6494)

**Comment by erickriva** [comment]
@Guysnacho Issue with `react-native-screens` was only one of them. The one with `@expo/config-plugins` still persists. Please, read @Maclay74 words again to workaround this.

**Comment by leonhh** [comment]
You can patch-package this by changing one line in `node_modules/@expo/config-plugins/build/android/Paths.js` :

```js
const filePath = (0, _glob().globSync)(path().join(projectRoot, `android/app/src/main/java/**/${name}.@(java|kt)`))[0];
```

Into:
```js
const filePath = (0, _glob().globSync)(path().join(projectRoot, `android/app/src/main/java/**/${name}.@(java|kt)`).replace(/\\/g, '/'))[0];
```

globSync does indeed not support Windows paths.

**Comment by Kavosh-m** [comment]
I have the same issue.

OS: Windows 10
Platform: Android

expo sdk version: "~52.0.0-preview.5"

**Comment by metkm** [comment]
I have this feature and making the change you suggested worked. after this I run `expo run:android --variant release`. I have this error: 

```
Error: Unable to resolve module ./C:/Users/metin/Desktop/x/node_modules/expo-router/entry.js from C:\Users\metin\Desktop\x/.:
```

Are these errors related in any way?

**Comment by Kavosh-m** [comment]
> You can patch-package this by changing one line in `node_modules/@expo/config-plugins/build/android/Paths.js` :
> 
> ```js
> const filePath = (0, _glob().globSync)(path().join(projectRoot, `android/app/src/main/java/**/${name}.@(java|kt)`))[0];
> ```
> 
> Into:
> 
> ```js
> const filePath = (0, _glob().globSync)(path().join(projectRoot, `android/app/src/main/java/**/${name}.@(java|kt)`).replace(/\\/g, '/'))[0];
> ```
> 
> globSync does indeed not support Windows paths.

it works for me. tnx a lot

**Comment by younes0** [comment]
This solution works: override the version of `@expo/image-utils` to the latest (0.6.3)
Source: https://discord.com/channels/695411232856997968/1300360703542300743/1304503480907595847

**Comment by StefSchalks** [comment]
I'm closing this since the SDK52 canary is over and the stable version is released.
