### ISSUE TITLE
`playAsync` and `pauseAsync` methods are missing for Video [expo-av][bare workflow]

### ISSUE THREAD

**Issue by yaroslavnikiforov** [expo/expo#31415]
### Minimal reproducible example

https://github.com/yaroslavnikiforov/VideoTest2

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

`playAsync` and `pauseAsync` methods are missing in the Video ref:
```
const videoRef = useRef<Video>(null);

useEffect(() => {
  console.info('videoRef.current: ', videoRef.current); // methods are not present
}, []);
..
<Video 
  ref={videoRef}
  ...
/>
```
Steps to reproduce:
```
npx react-native init AppName --version 0.74.5
npx install-expo-modules@latest
npx expo install expo-av && cd ios && pod install
```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /usr/local/bin/node
      Yarn: 3.6.4 - ~/.yarn/bin/yarn
      npm: 10.8.2 - /usr/local/bin/npm
      Watchman: 2024.07.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/yaroslav/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 34
        Build Tools: 30.0.3, 33.0.0, 34.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.32
      **"expo-av": "~14.0.7",**
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by yaroslavnikiforov** [comment]
Clarification, here are all available keys of the Video ref object:
```
[
  "props",
  "context",
  "refs",
  "updater",
  "_nativeRef",
  "_onPlaybackStatusUpdate",
  "_handleNewStatus",
  "_performOperationAndHandleStatusAsync",
  "_setFullscreen",
  "presentFullscreenPlayer",
  "dismissFullscreenPlayer",
  "getStatusAsync",
  "loadAsync",
  "unloadAsync",
  "setStatusAsync",
  "replayAsync",
  "_nativeOnPlaybackStatusUpdate",
  "_nativeOnLoadStart",
  "_nativeOnLoad",
  "_nativeOnError",
  "_nativeOnReadyForDisplay",
  "_nativeOnFullscreenUpdate",
  "_renderPoster",
  "state",
  "_reactInternals",
  "_reactInternalInstance"
]
```

So only `loadAsync`, `unloadAsync` and `replayAsync` methods are present. All other AV methods are missing:
```
pauseAsync
playAsync
playFromPositionAsync
setIsLoopingAsync
setIsMutedAsync
setPositionAsync
setProgressUpdateIntervalAsync
setRateAsync
setVolumeAsync
stopAsync
```

**Comment by yaroslavnikiforov** [comment]
In the demo, the methods are not present in the logs because they are inherited from the base class but are still available when you call them. In my real project, they are `undefined` in the logs and inaccessible. Seems like some problem with Babel.

**Comment by Ahmad-AbdElKader** [comment]
I'm facing the same problem, how did you manage to fix it?

**Comment by ldystudio** [comment]
same
