### ISSUE TITLE
Getting this React Community cli Issue while building the app in Expo via EAS.

### ISSUE THREAD

**Issue by surya-inbasagaran** [expo/expo#31435]
### Summary

I created the Expo app
and used yarn for package installation.
I know its an old expo version. but It works on other similar apps still.

I can view my app in the Expo Go App. but when I tried to build the apk, I faced this issue in Run Gradlew part.

Error Screenshot from Expo dev:
![image](https://github.com/user-attachments/assets/71e789ec-16d8-4a3e-99f5-8e7e9c0eb37b)

my package.json screenshot for ref:

![image](https://github.com/user-attachments/assets/f228ef52-f997-4004-b01c-7642b8b5100f)

### What platform(s) does this occur on?

Expo Dev - while trying to create apk

### SDK Version

47.0.14

### Environment

![image](https://github.com/user-attachments/assets/9bae401f-728d-486c-9ab8-85642c21522a)

### Minimal reproducible example

![image](https://github.com/user-attachments/assets/d03a0ee1-3d22-4ea8-97eb-93d5b6e64f58)

**Comment by brentvatne** [comment]
hi there! please refer to https://docs.expo.dev/build-reference/troubleshooting/

there is instructions at the bottom that can help further if you're stuck after following the guidance: https://docs.expo.dev/build-reference/troubleshooting/#how-to-ask-a-good-question
