### ISSUE TITLE
Error: Updates.checkForUpdateAsync() is not supported when expo-updates is not enabled

### ISSUE THREAD

**Issue by ashosipyan** [expo/expo#31436]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by atultiwaree** [comment]
> ### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?
> 
> Yes

Hey, I'm also facing the same issue how please help how you managed to solve that ? I'm on SDK 51

**Comment by AngelD18** [comment]
Tambien tengo el mismo problema, me dice Updates.checkForUpdateAsync() is not supported when expo-updates is not enabled, y estoy en sdk 51

**Comment by aderiushev** [comment]
same here, expo sdk 52

**Comment by illusorytapirus** [comment]
For anyone who does not use EAS build, please ensure the "ios/<project-name>/Supporting/Expo.plist" is imported to xcode

**Comment by eithe** [comment]
I seem to have missed that point when following [the guide to migrate from codepush](https://docs.expo.dev/eas-update/codepush/), wish it was more explicitly stated :)

**Comment by billysutomo** [comment]
im using SDK 52, expo-updates ~0.26.12, platform android and on new project.
also getting this,

**Comment by Esarhaddon** [comment]
> For anyone who does not use EAS build, please ensure the "ios/project-name/Supporting/Expo.plist" is imported to xcode

This was my problem as well, but I wasn't sure what was meant by "is imported to xcode" at first. This might only be something you run into if, like me, you're trying to get EAS Update working in the bare workflow, but the issue is that Xcode doesn't automatically know about files added to the project via a different code editor. I had added the Expo.plist file in the Supporting directory in VS Code, but to actually get it to work, I had to open the project in Xcode, open the project navigator, right click the "[MyProject]" directory, add a new group (directory) called "Supporting", right click that and select "Add files..." and then find the the Expo.plist file I had created.

**Comment by Mozartted** [comment]
> > For anyone who does not use EAS build, please ensure the "ios/project-name/Supporting/Expo.plist" is imported to xcode
> 
> This was my problem as well, but I wasn't sure what was meant by "is imported to xcode" at first. This might only be something you run into if, like me, you're trying to get EAS Update working in the bare workflow, but the issue is that Xcode doesn't automatically know about files added to the project via a different code editor. I had added the Expo.plist file in the Supporting directory in VS Code, but to actually get it to work, I had to open the project in Xcode, open the project navigator, right click the "[MyProject]" directory, add a new group (directory) called "Supporting", right click that and select "Add files..." and then find the the Expo.plist file I had created.

This, thanks for this, I almost spent a week, amongst other issues.

**Comment by DanGDroid** [comment]
> > For anyone who does not use EAS build, please ensure the "ios/project-name/Supporting/Expo.plist" is imported to xcode
> 
> This was my problem as well, but I wasn't sure what was meant by "is imported to xcode" at first. This might only be something you run into if, like me, you're trying to get EAS Update working in the bare workflow, but the issue is that Xcode doesn't automatically know about files added to the project via a different code editor. I had added the Expo.plist file in the Supporting directory in VS Code, but to actually get it to work, I had to open the project in Xcode, open the project navigator, right click the "[MyProject]" directory, add a new group (directory) called "Supporting", right click that and select "Add files..." and then find the the Expo.plist file I had created.

this must be added to Expo Updates documentation
