### ISSUE TITLE
Expo vector-icons which is required by expo causes build submission failure to app store

### ISSUE THREAD

**Issue by zachkamran** [expo/expo#31465]
### Minimal reproducible example

create a new expo project and submit it to test flight

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

When you submit a build of an expo app to test flight it will be rejected for invalid binary (see attached) this is tracked back to this issue https://github.com/expo/vector-icons/issues/314. This prevents all new builds from being submitted to test flight

![image](https://github.com/user-attachments/assets/ee25d74a-b2a6-4f97-8ea0-4742ee219710)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.1.0/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/zach/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.21 => 51.0.21 
      expo-router: ~3.5.18 => 3.5.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.0.3
    Expo Workflow: managed

### Expo Doctor Diagnostics

all passed

**Comment by zachkamran** [comment]
Fyi - seems like has been fixed https://github.com/oblador/react-native-vector-icons/releases/tag/v10.2.0 and just needs to be pulled in here

**Comment by brentvatne** [comment]
@zachkamran - currently doing that, i will publish a release soon!

**Comment by brentvatne** [comment]
@zachkamran - please try @expo/vector-icons@11.0.3!

**Comment by zachkamran** [comment]
> @zachkamran - please try @expo/vector-icons@11.0.3!

Thanks so much!
