### ISSUE TITLE
expo dev-client binds to ipv6

### ISSUE THREAD

**Issue by Gaeldrin** [expo/expo#31466]
### Summary

I have exactly the same problem as #29094. Also basically the same as #21198.

#### Baseline
When I run `expo start --dev-client`, it tells me it binds to 192.168.1.10:8081 (my correct IP) but when I verify which ports are open, I can see that `node` opens a port on tcp6.
```
$ npx expo start --dev-client
› Metro waiting on http://localhost:8081 

$ sudo netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::8081                 :::*                    LISTEN      88497/node
```
#### Not helping
I tried to set the env variable `REACT_NATIVE_PACKAGER_HOSTNAME` from https://github.com/expo/expo/issues/21198#issuecomment-1503773065 but even though it shows the IP from that variable in text after running `expo start --dev-client`, actual port open stays the same (confirmed by `sudo netstat -tunlp`).
Also https://github.com/expo/expo/issues/21198#issuecomment-1951803071 did not help in my case.

#### Workaround
Running in tunnel mode works as `ngrok` opens an ipv4 port together with the ipv6 port from `node`:
```
$ npx expo start --tunnel
› Metro waiting on exp://n81ga1s-user-8081.exp.direct
› Web is waiting on http://localhost:8081

$ sudo netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:4040          0.0.0.0:*               LISTEN      87580/ngrok
tcp6       0      0 :::8081                 :::*                    LISTEN      88496/node
```

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.2 (Victoria)
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.local/share/pnpm/node
      npm: 10.8.1 - ~/.local/share/pnpm/npm
    Expo Workflow: managed

### Minimal reproducible example

New app created by
```
npx create-expo-app my-app
```

**Comment by Gaeldrin** [comment]
Well.. let's close this. My issue was caused by firewall so I could get it fixed.
However, I will say that the lack of any response in a month is definitely quite disheartening.

**Comment by Anurag-Raut** [comment]
> Well.. let's close this. My issue was caused by firewall so I could get it fixed. However, I will say that the lack of any response in a month is definitely quite disheartening.

hey , i am also currently facing the same issue and got down to this conclusion , can you please share steps you took to solve your issue?.

i have tried disabling firewall of system (ufw) and  router also but still the problem persists.
