### ISSUE TITLE
Expo AV - App Crash after upgrade - AVManager.installJSIBindings

### ISSUE THREAD

**Issue by AJV2018** [expo/expo#31489]
### Minimal reproducible example

not able to reproduce. this crash was reported from firebase

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

AVManager.installJSIBindings
java.lang.NullPointerException - java.lang.NullPointerException

 Fatal Exception: java.lang.NullPointerException: java.lang.NullPointerException
       at expo.modules.av.AVManager.installJSIBindings(AVManager.java)
       at expo.modules.av.AVManager.lambda$onCreate$0(AVManager.java:186)
       at expo.modules.av.AVManager.$r8$lambda$MqNG0t3r5Ij3DfZ3pXPMUPGLAIk()
       at expo.modules.av.AVManager$$ExternalSyntheticLambda11.run(:2)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
       at java.lang.Thread.run(Thread.java:1012)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 3.6.4 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/amal/.rvm/gems/ruby-3.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12071903
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~8.0.0
Found invalid:
  @expo/config-plugins@2.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/metro-config@~0.18.11
Found invalid:
  @expo/metro-config@0.18.8
  (for more info, run: npm why @expo/metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Error: Problem validating fields in /Users/amal/dev/rn/GivaApp/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: plugins. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@1.24.0 - expected version: 1.23.1
  @react-native-community/datetimepicker@8.2.0 - expected version: 8.0.1
  @react-native-community/netinfo@11.3.2 - expected version: 11.3.1
  expo@51.0.21 - expected version: ~51.0.31
  expo-av@14.0.6 - expected version: ~14.0.7
  expo-font@12.0.9 - expected version: ~12.0.10
  lottie-react-native@6.7.2 - expected version: 6.7.0
  react-native@0.74.3 - expected version: 0.74.5
  react-native-gesture-handler@2.18.1 - expected version: ~2.16.1
  react-native-pager-view@6.3.3 - expected version: 6.3.0
  react-native-reanimated@3.15.0 - expected version: ~3.10.1
  react-native-safe-area-context@4.10.8 - expected version: 4.10.5
  react-native-screens@3.34.0 - expected version: 3.31.1
  react-native-webview@13.10.5 - expected version: 13.8.6
  @types/react@18.3.3 - expected version: ~18.2.79
  typescript@5.0.4 - expected version: ~5.3.3

**Comment by ilyausorov** [comment]
We're also seeing this same issue in our Bugsnag crash logs and in Google Play crash logs

**Comment by SimonAM** [comment]
Its supposedly fixed in #31464. Is that released in 14.0.7?
