### ISSUE TITLE
Focusing On Search Bar reveals hidden headers

### ISSUE THREAD

**Issue by whostinlon** [expo/expo#31482]
### Minimal reproducible example

https://github.com/whostinlon/SearchBarBug

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When a user is focused on the search bar, and selects an option (for example a filtered list based on search query), the hidden header reappears and prevents clicking elements under that header. 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.4.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.1 - /opt/homebrew/bin/npm
      Watchman: 2024.06.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.3.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Expo Router uses the React Navigation navigators for its layouts. This appears to be an upstream issue with their `<Stack />` component. I would recommend creating an issue there so they are about to fix it.
