### ISSUE TITLE
"new architecture" touch is very inconsistent for TextInput and Button (both RN and Paper)

### ISSUE THREAD

**Issue by kferch-teamworks** [expo/expo#31505]
### Minimal reproducible example

https://github.com/kferch-teamworks/RNAndroidTouch

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I'm starting a mobile app for my company and am using expo v51, react-native v75, react-navigation (v7 rc), and react-native-paper.  I turned "new architecture" on because I'm just starting and I want to smoothly switch to RN 76 when it comes out by verifying that I'm not doing anything that would not work with new architecture. I noticed in my eas preview builds that on real android phones I couldn't even press buttons or bring up the keyboard in text input.  It all works fine an ios phones and emulators and simulators.

I turned off "new architecture" and android phones work fine.  I'm worried that with RN 76 already hitting RC that this problem hasn't been solved yet.

I built up a minimal repo and things worked fine until adding in react-navigation.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/kferch/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      react: 18.2.0 => 18.2.0 
      react-native: ~0.75.0 => 0.75.3 
    npmGlobalPackages:
      eas-cli: 12.4.1
    Expo Workflow: bare

### Expo Doctor Diagnostics

(the bellow problems are a result of following [Expo documentation](https://expo.dev/changelog/2024/08-14-react-native-0.75) to use RN 75 with Expo 51)

npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  react-native@0.75.3 - expected version: 0.74.5
  react-native-screens@3.34.0 - expected version: 3.31.1
  react-native-reanimated@3.15.2 - expected version: ~3.10.1
  react-native-gesture-handler@2.18.1 - expected version: ~2.16.1
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

**Comment by AppdevTesting** [comment]
touch is very inconsistent for TextInput and Button .... Hi, Yes, we also have this problem, clicking the buttons is very difficult and you even have to be precise several times for it to work, if possible, use the buttons in a Native way to improve the feeling and interaction

**Comment by kferch-teamworks** [comment]
> touch is very inconsistent for TextInput and Button .... Hi, Yes, we also have this problem, clicking the buttons is very difficult and you even have to be precise several times for it to work, if possible, use the buttons in a Native way to improve the feeling and interaction

Thanks for the suggestion.  My goal with this bug though is to have expo or react-navigation fix it before RN 76.

For now (I hope not too long), I plan on leaving "new architecture" on and ignore android phones and rely on emulator.

**Comment by brentvatne** [comment]
hi @kferch-teamworks! this looks like an interaction between react-native-screens and react-native-paper's button component. i investigated this a bit and traced it back to this single line: https://github.com/callstack/react-native-paper/blob/9162a1fdf4e97c0669de8a8fa2057d8cfbe2e728/src/components/Button/Button.tsx#L336

if you comment that out, it fixes all other touches

**Comment by kferch-teamworks** [comment]
react-native-paper newly created [issue](https://github.com/callstack/react-native-paper/issues/4517)
