### ISSUE TITLE
WatchPositionAsync never resolves on Android with sdk 32

### ISSUE THREAD

**Issue by davidmargolin** [expo/expo#3150]
### Environment
  Expo CLI 2.4.0 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
      Shell: 5.5.1 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.0 
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
      react-navigation: ^3.0.7 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.6.8

target -> Expo Android

### Steps to Reproduce

```
Location.watchPositionAsync({ 
        accuracy: Location.Accuracy.Balanced, 
        timeInterval: 30000, 
        distanceInterval: 40 
    },
    (response) => console.log(response)
)
```

### Expected Behavior

log location response

### Actual Behavior

never gets called on Android. (Works fine on iOS) Attempted on multiple devices.

**Comment by oliverdolgener** [comment]
Same!

**Comment by davidmargolin** [comment]
> Same!
> 
> ```
> RemoteConsole.js:80 Possible Unhandled Promise Rejection (id: 0):
> Error: Encountered an exception while calling native method: Exception occurred while executing exported method watchPositionImplAsync on module ExpoLocation: null
> ```

not sure we're having the same issue. the method is `watchPositionAsync` not watchPositionImplAsync and make sure you use `import {Location as ExpoLocation} from 'expo'`

**Comment by oliverdolgener** [comment]
Yes, that's the same! `watchPositionImplAsync` is the name of the native Android method that gets called on Expo's `watchPositionAsync`.

**Comment by davidmargolin** [comment]
ah my mistake. Thanks for the lesson!

**Comment by oliverdolgener** [comment]
I've found this line over here that could cause the problem:
https://github.com/expo/expo/blob/4481a258c95ee9ef4cafded9927e2c0b663dac87/packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java#L412

**Comment by davidmargolin** [comment]
that implies that the issue is Location Services which in my case is def enabled. Prod (sdk 30) app has no trouble getting location as compared to sdk32 app on the same device.

**Comment by oliverdolgener** [comment]
Yeah, I've double checked, there was no change made to that line so it should be ok.

**Comment by esamelson** [comment]
Hi all - could somebody experiencing this issue please provide a full reproduction (ideally a [snack](https://snack.expo.io)) and also let us know which devices you're seeing this on? Thanks!

**Comment by davidmargolin** [comment]
@esamelson @tsapeta here's the snack: https://snack.expo.io/HJxDaFWzN
and here's the results from my iOS and Android devices. Let me know if any other information is needed.

<img src="https://i.ibb.co/TvPDw7m/254-FA287-46-FF-4282-B3-D2-EF8-FD70-E43-FC.png" width=250 />

<img src="https://i.ibb.co/LQzzPLM/image.png" width=250/>

**Comment by tsapeta** [comment]
I've fixed this issue in the commit above and we will release this fix together with some other fixes, possibly tomorrow.

**Comment by sjchmiela** [comment]
Fix has been deployed in Expo Client v2.10.3 (should already be available on the Play Store). 🙂

**Comment by davidmargolin** [comment]
Y'all are the best. Thank you!

**Comment by mgscreativa** [comment]
Hi! I think I hit the same issue

  Expo CLI 2.7.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.15.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^32.0.0 => 32.0.0 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.7.0

target -> Expo Android

My Implementation:
 ```
getPositionAsyncRef = async () => {
    const { alertWithType } = this.props;
    const status = await Location.getProviderStatusAsync();

    if (!status.locationServicesEnabled) {
      alertWithType(
        'error',
        'Error!',
        'Los servicios de ubicación estan deshabilitados',
      );
    } else {
      const permissions = await Permissions.askAsync(Permissions.LOCATION);

      if (permissions.status !== 'granted') {
        alertWithType(
          'error',
          'Error!',
          'No has permitido a la app acceder a los servicios de ubicación.',
        );
      } else {
        this.positionAsyncRef = await Location.watchPositionAsync(
          this.watchPositionAsyncOptions,
          this.locationChanged,
        ).catch(err => console.log(err));
      }
    }
  };
```

> Encountered an exception while calling native method: Exception occurred while executing exported method watchPositionImplAsync on module ExpoLocation: null
> - node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:30 in <unknown>
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:397:12 in MessageQueue.__invokeCallback
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:11 in <unknown>
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:8 in MessageQueue.__guard
> - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:9 in MessageQueue.invokeCallbackAndReturnFlushedQueue
