### ISSUE TITLE
Why expo-image-picker is not working on iphone 16 simulators get suck on library screen.

### ISSUE THREAD

**Issue by deepakOptimizeApp** [expo/expo#31516]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by freddi-kit** [comment]
I also have faced same issue and it looks not only iPhone 16, but also in iPhone 15. However, we are using a little old version of expo. Let me confirm how it works in latest expo and fix it if it still occur in this version

**Comment by freddi-kit** [comment]
I'm working from now. Could you recreate a issue to show more detail to track issue easily?

**Comment by deepakOptimizeApp** [comment]
@freddi-kit facing only with apple silicon mac on intel macs working fine.

**Comment by freddi-kit** [comment]
How about device? I think device should behave same because they are also arm64

**Comment by freddi-kit** [comment]
I just tested, this happens on Simulator but not happens on device. I just checked both by simulator and device

**Comment by freddi-kit** [comment]
I found forum related post https://developer.apple.com/forums/thread/763636

**Comment by freddi-kit** [comment]
it looks like Xcode SDK bug so we need to wait for fix from Apple
