### ISSUE TITLE
Stack.Screen -> screenOptions -> headerTitleStyle does not receive textTransform attribute

### ISSUE THREAD

**Issue by theolemague** [expo/expo#31527]
### Minimal reproducible example

https://github.com/theolemague/score-club

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When creating a Stack in a random _layout.tsx I'm using <Stack /> to define screens. I want to put the title in uppercase but both the `screenOptions` of `Stack.Navigator` and the `options` of `Stack.Screen` are telling me that does not exist in `headerTitleStyle` property, which was working with `@react-navigation/native`.
I know I can create my own CustomHeader which is what I'll do surely but I feel that this is an issue

<img width="934" alt="Screenshot 2024-09-17 at 22 14 27" src="https://github.com/user-attachments/assets/2b7b200d-3fc8-40a2-8e44-2c57feeb287a">

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.4.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.3 - /opt/homebrew/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.32 => 51.0.32
      expo-router: ~3.5.23 => 3.5.23
      react: ^18.2.0 => 18.2.0
      react-native: ^0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 12.3.0
    Expo Workflow: managed

**Comment by marklawlor** [comment]
`headerTitleStyle` only accepts a limited number of props.

Reference from React Navigation: [headerTitleStyle](https://reactnavigation.org/docs/headers/#adjusting-header-styles)
