### ISSUE TITLE
Error: connect ETIMEDOUT 52.84.225.40:443

### ISSUE THREAD

**Issue by brianha289** [expo/expo#3153]
A) Error when archiving project on Xcode 10

Error: connect ETIMEDOUT 52.84.225.40:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Command PhaseScriptExecution failed with a nonzero exit code

B) Error when archiving on Android Studio
 RNWebView:processReleaseJavaRes NO-SOURCE
:RNWebView:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:RNWebView:packageReleaseRenderscript NO-SOURCE
:RNWebView:mergeReleaseShaders UP-TO-DATE
:RNWebView:compileReleaseShaders UP-TO-DATE
:RNWebView:generateReleaseAssets UP-TO-DATE
:RNWebView:packageReleaseAssets UP-TO-DATE
:RNWebView:mergeReleaseConsumerProguardFiles UP-TO-DATE
:RNWebView:compileReleaseNdk NO-SOURCE
:RNWebView:mergeReleaseJniLibFolders UP-TO-DATE
:RNWebView:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:RNWebView:transformNativeLibsWithIntermediateJniLibsForRelease UP-TO-DATE
:app:preBuild
:app:extractProguardFiles UP-TO-DATE
:app:preProdMinSdkProdKernelReleaseBuild UP-TO-DATE
:app:compileProdMinSdkProdKernelReleaseAidl UP-TO-DATE
:app:compileProdMinSdkProdKernelReleaseRenderscript UP-TO-DATE
:app:checkProdMinSdkProdKernelReleaseManifest UP-TO-DATE
:app:generateProdMinSdkProdKernelReleaseBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:mergeProdMinSdkProdKernelReleaseShaders UP-TO-DATE
:app:compileProdMinSdkProdKernelReleaseShaders UP-TO-DATE
:app:generateProdMinSdkProdKernelReleaseAssets UP-TO-DATE
:app:mergeProdMinSdkProdKernelReleaseAssets
:app:processProdMinSdkProdKernelReleaseGoogleServices
Parsing json file: /Users/art3mis/lamitak/android/app/google-services.json
:app:createProdMinSdkProdKernelReleaseCompatibleScreenManifests UP-TO-DATE
:app:mainApkListPersistenceProdMinSdkProdKernelRelease UP-TO-DATE
:app:processProdMinSdkProdKernelReleaseManifest UP-TO-DATE
:app:fabricGenerateResourcesProdMinSdkProdKernelRelease
:app:generateProdMinSdkProdKernelReleaseResValues UP-TO-DATE
:app:generateProdMinSdkProdKernelReleaseResources UP-TO-DATE
:app:mergeProdMinSdkProdKernelReleaseResources
Error: connect ETIMEDOUT 52.84.225.40:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
:app:bundleProdMinSdkProdKernelReleaseExpoAssets FAILED

**Comment by ide** [comment]
A) 52.84.225.40 is an AWS CloudFront server. If you cannot connect to CloudFront, there is probably something wrong with your internet connection.

B) I gripped the Expo code base for RNWebView and found no results. The issue looks related to another library perhaps.

**Comment by huy-lv** [comment]
It's seem many people cannot connect to Cloudfront, me too
