### ISSUE TITLE
[ios] Playing an .m3u8 / streaming video URI (Expo Video / Expo AV) makes CameraView freeze on IOS + breaks AV audio recording

### ISSUE THREAD

**Issue by jvgeee** [expo/expo#31542]
### Minimal reproducible example

https://snack.expo.dev/@jvghonestfox/surprised-red-popsicle

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

My app uses MUX to stream videos in m3u8 format. It also allows you to record videos using Expo Camera, and I display a view of the camera with CameraView. I also allow users to record audio with expo-av.

I'm using Expo Video to play my videos, but this issue also occurs when using expo-av's Video component.

What happened:

- Originally I was using S3 hosted videos, and everything worked fine
- When I moved over to MUX m3u8 video URIs, when I have a video playing on Screen A, then I open Screen B which has my CameraView feed on it, the CameraView either renders 1 frame and freezes, or just renders a black screen. 
- I log out `onCameraReady`, and the camera is ready even though nothing is displayed
- I log out `onMountError`, and no errors are ever displayed

I've also noticed that audio recording breaks under these circumstances too; when the CameraView is frozen and I try to record audio, using this function (which normally works fine),  I get `Error: Prepare encountered an error: recorder not prepared.`:
```
const startRecording = async () => {
    try {

      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
      })

      const { recording, status } = await Audio.Recording.createAsync(
        Config.recordingPresets,
        onRecordingStatusUpdate,
      )
      console.log("Started recording", recording, { status })
      setRecording(recording)
    } catch (err) {
      console.log("Failed to start recording", err)
    }
  }
  ```

This only affects IOS, not Android.

I've tried downgrading a few versions of expo-camera, expo-av + expo-video to see if this helps, and it doesn't.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.12.2/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.31 => 51.0.31
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.6 => 0.19.11
    npmGlobalPackages:
      eas-cli: 10.2.4
    Expo Workflow: bare

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for issues with metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

**Comment by efstathiosntonas** [comment]
>  the CameraView either renders 1 frame and freezes, or just renders a black screen.

Got this only on first app launch. Every time I open the Camera on a fresh install if freezes for like 5-6 seconds and then shows up fine. If i close the app and relaunch it works as it should. Really weird!

**Comment by efstathiosntonas** [comment]
@jvgeee can you try patching camera with this PR? 

* https://github.com/expo/expo/pull/31514

just patched it and the camera feed showed up instantly, no freezes

`expo-camera+15.0.16.patch`

```patch
diff --git a/node_modules/expo-camera/ios/Current/CameraView.swift b/node_modules/expo-camera/ios/Current/CameraView.swift
index fe49a42..3639dd3 100644
--- a/node_modules/expo-camera/ios/Current/CameraView.swift
+++ b/node_modules/expo-camera/ios/Current/CameraView.swift
@@ -560,17 +560,14 @@ public class CameraView: ExpoView, EXCameraInterface, EXAppLifecycleListener,
     sessionQueue.async {
       if let videoFileOutput = self.videoFileOutput, !videoFileOutput.isRecording && self.videoRecordedPromise == nil {
         if let connection = videoFileOutput.connection(with: .video) {
-          if connection.isVideoStabilizationSupported {
-            connection.preferredVideoStabilizationMode = .auto
-          } else {
-            log.warn("\(#function): Video Stabilization is not supported on this device.")
-          }
+
 
           let orientation = self.responsiveWhenOrientationLocked ? self.physicalOrientation : UIDevice.current.orientation
           connection.videoOrientation = ExpoCameraUtils.videoOrientation(for: orientation)
           self.setVideoOptions(options: options, for: connection, promise: promise)
 
           if connection.isVideoOrientationSupported && self.mirror {
+            connection.preferredVideoStabilizationMode = .auto
             connection.isVideoMirrored = self.mirror
           }
         }
```

**Comment by jvgeee** [comment]
@efstathiosntonas This is a good catch and will potentially solve the hanging issue. However, my particular issue was solved by doing some heavy refactoring of my app, including some pretty heavy garbage collection of video playing objects. I'm not 100% sure what one fix solved the issue, so sorry I don't have a better answer here!
