### ISSUE TITLE
[Apple][Android] expo-apple-authentication:  unable to build on machine

### ISSUE THREAD

**Issue by lucksp** [expo/expo#31555]
### Minimal reproducible example

https://github.com/lucksp/expo-apple-auth

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a local build `npx expo run:ios` && `npx expo run:android`

using Expo SDK50, expo-apple-authentication `~6.3.0`

### Summary

I am running `npx expo run` to build local app before pushing to EAS build.  Today I was prompted with an error on iOS, the messaging requesting to update **XCode** to `iOS 18`.  This happened with XCode asking to updte to `iOS 17` previously.  Now that the error is clear up, I cannot build on my machine 🤷🏻‍♂️

🍎 iOS error message:
```

error: unexpected service error: The Xcode build system has crashed. Build again to continue.

❌  (node_modules/expo-apple-authentication/ios/AppleAuthenticationExceptions.swift:53:3)

  51 |
  52 | func exceptionForAuthorizationError(_ error: ASAuthorizationError) -> Exception {
> 53 |   switch error.code {
     |   ^ switch must be exhaustive
  54 |   case .unknown:
  55 |     return RequestUnknownException()
  56 |   case .canceled:

› Compiling expo Pods/Expo » Expo-dummy.m
```

🤖 Android error message:

```
📝  Android package Learn more

✔ What would you like your Android package name to be? … com.lucksp.expoappleauth

✔ Created native directory
✔ Updated package.json | no changes
✔ Finished prebuild
› Opening emulator Pixel_7_Pro_API_TiramisuPrivacySandbox
› Building app...
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/lucksp/dev/expo-apple-auth/android/app/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path=''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 12s
5 actionable tasks: 4 executed, 1 from cache
Error: /Users/lucksp/dev/expo-apple-auth/android/gradlew exited with non-zero code: 1
Error: /Users/lucksp/dev/expo-apple-auth/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/lucksp/dev/expo-apple-auth/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at Object.spawnAsync [as default] (/Users/lucksp/dev/expo-apple-auth/node_modules/@expo/cli/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/Users/lucksp/dev/expo-apple-auth/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/Users/lucksp/dev/expo-apple-auth/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/Users/lucksp/dev/expo-apple-auth/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.05.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/lucksp/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.19 => 50.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    npmGlobalPackages:
      eas-cli: 7.0.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

> Need to install the following packages:
expo-doctor@1.10.1
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

----

I did have a successful EAS build, FWIW.  However running this build fails because it cannot find `fs` module

**Comment by lucksp** [comment]
Thanks for checking into this.  it was working fine yesterday 😅

**Comment by yolpsoftware** [comment]
Same here. After updating to Xcode 16.0, EAS build fails with this error.

**Comment by cretaceousmart** [comment]
Same here

**Comment by rnichi1** [comment]
Can confirm, happens to me as well when trying to build to ios 18.0 and Xcode 16.0

**Comment by cretaceousmart** [comment]
> Same here

Not sure if it's the best solution but It works when I use:

func exceptionForAuthorizationError(_ error: ASAuthorizationError) -> Exception {
//    Switch must be exhaustiveswitch
switch error.code {
  case .unknown:
    return RequestUnknownException()
  case .canceled:
    return RequestCanceledException()
  case .invalidResponse:
    return InvalidResponseException()
  case .notHandled:
    return RequestNotHandledException()
  case .failed:
    return RequestFailedException()
  case .notInteractive:
    return RequestNotInteractiveException()
  @unknown default:
        return RequestUnknownException()
  }
}

**Comment by MaRaSu** [comment]
> estou emulando usando o ios 18 e tive o mesmo problema. Consegui resolver instalando a versão latest hoje da biblioteca expo-apple-authentication@6.4.2
> 
> ```
> yarn add expo-apple-authentication@latest
> ```

Did not help me. After updating the module to the 6.4.2 still got the exactly same build failure.

@cretaceousmart looks like native code - can you perhaps give a bit more guidance what and how you patched (for us less native competent).

**Comment by Alec1017** [comment]
hitting the same issue with IOS 18.0 and xcode 16.0

**Comment by MarcosWillianR** [comment]
I was able to fix using the @cretaceousmart comment, but i don't test on production.

@MaRaSu you can use simply opening your project .xcworkspace on xcode, after that try to build and it will show the error message, just double tap on it and it will open a file, just change the code with the @cretaceousmart code, just like that, here's my file:

<img width="1728" alt="Screenshot 2024-09-19 at 14 17 30" src="https://github.com/user-attachments/assets/46f50396-5fb7-4bd9-93d6-9f1b76471b0b">

you can use this code:

func exceptionForAuthorizationError(_ error: ASAuthorizationError) -> Exception {
  switch error.code {
    case .unknown:
      return RequestUnknownException()
    case .canceled:
      return RequestCanceledException()
    case .invalidResponse:
      return InvalidResponseException()
    case .notHandled:
      return RequestNotHandledException()
    case .failed:
      return RequestFailedException()
    case .notInteractive:
      return RequestNotInteractiveException()
    @unknown default:
      return RequestUnknownException()
  }
}

**Comment by yolpsoftware** [comment]
> estou emulando usando o ios 18 e tive o mesmo problema. Consegui resolver instalando a versão latest hoje da biblioteca expo-apple-authentication@6.4.2
> 
> ```
> yarn add expo-apple-authentication@latest
> ```

Can confirm that updating `expo-apple-authentication` to `6.4.2` solved the problem for me!

If it doesn't for you, try `rm -rf node_modules` and `pod repo update`, maybe that helps.

Muito obrigado @franklindrw!

**Comment by lucksp** [comment]
@yolpsoftware and @franklindrw - what Expo version are you on? 

I am on SDK50 and `expo-doctor` doesn't like if I install v`6.4.2` ❌ .  That being said, the updated version still fails to build for me on my machine.
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/52a0162a-6e13-4325-aa28-e6f000cf84d4">

**Comment by lucksp** [comment]
I also tried updating to SDK51, but no luck

**Comment by osmanbaskaya** [comment]
same issue SDK50, iOS 18

**Comment by yolpsoftware** [comment]
> @yolpsoftware and @franklindrw - what Expo version are you on?

Expo SDK 50. Yes, `expo-doctor` does not like it, but it works and I am testing the build currently on Testflight. Apple auth works fine.

Your screenshot seems to indicate that the build tools crash, instead of just showing an error? That might be a different issue. Maybe open Xcode and try to build the project manually.

**Comment by lucksp** [comment]
xcode results in the original error
<img width="701" alt="image" src="https://github.com/user-attachments/assets/9bbe7487-53c4-47af-a7a6-4bebc151125a">

**Comment by MarcosWillianR** [comment]
> xcode results in the original error <img alt="image" width="701" src="https://private-user-images.githubusercontent.com/15162169/369572442-9bbe7487-53c4-47af-a7a6-4bebc151125a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NzYzMTIsIm5iZiI6MTcyNjg3NjAxMiwicGF0aCI6Ii8xNTE2MjE2OS8zNjk1NzI0NDItOWJiZTc0ODctNTNjNC00N2FmLWE3YTYtNGJlYmMxNTExMjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDIzNDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwOGViYmYwNGIyYzEwM2YxZTcwOTRlNDgyOTgxNTczYjM4NDA5ZGE3OGRhYWZmMTcxOTA1OTQ5Y2Q2NWE3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._nl7MtrY-VP_faFi0Kx4t5nKl-felZGMTO3f_2-BpfM">

Have you tried using this func?

```swift
func exceptionForAuthorizationError(_ error: ASAuthorizationError) -> Exception {
  switch error.code {
    case .unknown:
      return RequestUnknownException()
    case .canceled:
      return RequestCanceledException()
    case .invalidResponse:
      return InvalidResponseException()
    case .notHandled:
      return RequestNotHandledException()
    case .failed:
      return RequestFailedException()
    case .notInteractive:
      return RequestNotInteractiveException()
    @unknown default:
      return RequestUnknownException()
  }
}
```

**Comment by MaRaSu** [comment]
Thanks @cretaceousmart for the fix and @MarcosWillianR for additional clarification, I got a successful build done with managed Expo SDK 49. `npx expo install` does not allow upgrading to 6.4.2 version of `expo-apple-authentication`, but simple patching of a single file (per code from @cretaceousmart) did the job. No need to leave managed Expo and play with Xcode either, just use `patch-package`:
1. install patch-package`npm install patch-package`
2. Patch the file in node_modules `node_modules/expo-apple-authentication/ios/AppleAuthenticationExceptions.swift` , adding that last default case statement should be enough
3. Create the patch `npx patch-package expo-apple-authentication`
4. Ensure that in your package.json scripts section you have `"postinstall": "patch-package"`
5. Do the normal eas build

**Comment by lucksp** [comment]
Thank you @MaRaSu - unfortunately, I am still unable to build with `npx expo run:ios`.  I don't have any issues with EAS.

For example, I am on the "latest" so in EAS, under `Spin Up Environment` it says:
>Using VM template "macos-sonoma-14.5-xcode-15.4" running macOS Sonoma 14.5

However, this doesn't match my local machine of Mac OS15, XCode 16, iOS 18

what is your `eas.json` for ios?

```js
 "build": {
    "base": {
      "ios": {
        "image": "latest"
      }
    },
```

**Comment by lucksp** [comment]
oh my, so this unknown crash on my machine is associated with an incompatibility of a different package - [react-native-expo-image-cropper](https://github.com/cloudtenlabs/react-native-expo-image-cropper/issues/25).

So now, yes I can agree that [the solution](https://github.com/expo/expo/issues/31555#issuecomment-2365045376) above works for my local machine.

I am still concerned about the EAS `latest` build image not matching my own system...but that's for a different thread

**Comment by lucksp** [comment]
And one more update, i decided to try to update to SDK 51 and this issue has been resolved without a patch.

**Comment by njculpin** [comment]
@lucksp thanks, its obviously not ideal but manually setting the image to the previous "macos-sonoma-14.5-xcode-15.4" in eas.json did work and I was able to get a build out the door.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
The issue you're seeing is because iOS 18 added one more error code which needs to be handled by the switch statement.

Either you need to use version 6.4.2 or newer (see [changelog](https://github.com/expo/expo/blob/main/packages/expo-apple-authentication/CHANGELOG.md#642---2024-07-22)) build with xcode 15.

This problem is fixed [here](https://github.com/expo/expo/pull/29639) on our side so I'm going to close this issue.
Thank you 🙂

**Comment by amorga97** [comment]
> yarn add expo-apple-authentication@latest

This did it for me too!

**Comment by Sameer-Ijaz** [comment]
I solved the issue by following these steps. https://www.youtube.com/watch?v=ya3kyKU-HY8&ab_channel=SgtSam
