### ISSUE TITLE
SDK 32 TypeScript errors

### ISSUE THREAD

**Issue by clems36** [expo/expo#3155]
Just a heads up: I'm using typescript in my project and right after updating to SDK 32, a few errors were picked up by the compiler.

**In my codebase:**

- `takeSnapshotAsync` gives ` Property 'snapshotContentContainer' is required in type 'SnapshotOptions'`

I don't see `snapshotContentContainer` anywhere in the docs, what does it do ? 

- `DocumentPicker.getDocumentAsync` gives `'copyToCacheDirectory' does not exist in type 'GetDocumentOptions'` and yet it is (still ?) in the docs

- `ImagePicker.launchImageLibraryAsync` gives `'base64' and 'exif' does not exist in type 'ImageLibraryOptions'`

- `startAsync` is marked as required in `AppLoading.d.ts` but from the docs:

> The following props are recommended, but optional for the sake of backwards compatibility

Can I still use `AppLoading` the same way ?

**In expo's codebase:**
These errors appear repeatedly in a bunch of files

-  `Namespace 'React' has no exported member 'ComponentProps'`
- `Namespace 'React' has no exported member 'RefObject'`
-  `Namespace 'React' has no exported member 'Context'`
- ` Generic type 'Component<P, S>' requires between 0 and 2 type arguments`
- `Generic type 'ComponentClass<P>' requires between 0 and 1 type arguments`

**Comment by dai-shi** [comment]
Lots of:
```
node_modules/expo/build/launch/AppLoading.d.ts:2:8 - error TS1192: Module '".../node_modules/@types/react/index"' has no default export.

2 import React from 'react';
         ~~~~~
```

I would like to avoid `"allowSyntheticDefaultImports": true` because expo itself did a breaking change: `import * as Expo from 'expo';`

**Comment by sjchmiela** [comment]
Hey all, thanks for the comments!

- My bad, I haven't updated `takeSnapshotAsync` doc after upgrading the underlying `react-native-view-shot`, on it!
- `copyToCacheDirectory` is missing in TS declaration, docs are correct
- same goes for `base64` and `exif`
- `startAsync` should be optional

When it comes to React problems, on what `@types/react` version are you? 🤔 We compile `expo` against `@types/react@^16.7.7`, maybe on this version it would work? 🙂

**Comment by dai-shi** [comment]
Another issue I have no clue is `expo-asset` and some others have no type defs:
```bash
$ ls node_modules/expo-asset 
index.js        package.json    src/
```
Although it's written in ts in https://github.com/expo/expo/tree/master/packages/expo-asset
Am I missing something? How do you guys deal with it?

**Comment by dai-shi** [comment]
> on what @types/react version are you?

```
$ npm ls|grep '@types/react'|head -1
├─┬ @types/react@16.7.18
```

**Comment by clems36** [comment]
@sjchmiela @types/react@^16.7.7 indeed does it for the React errors on my side. Thanks

**Comment by sjchmiela** [comment]
We publish the packages:
- from `master` if we're during the release process (no other changes land on `master` in that time)
- when the release is ready, `sdk-XX` branch is created, from which we publish the packages

In such case, the proper place to look for published `expo-asset@32.0.0` would be https://github.com/expo/expo/tree/sdk-32/packages/expo-asset. 🙂

**Comment by dai-shi** [comment]
> https://github.com/expo/expo/tree/sdk-32/packages/expo-asset

Thanks, that makes sense.

That also explains why I get this error:
```
node_modules/expo/build/Expo.d.ts:7:23 - error TS7016: Could not find a declaration file for module 'expo-asset'. '.../node_modules/expo-asset/index.js' implicitly has an 'any' type.
  Try `npm install @types/expo-asset` if it exists or add a new declaration (.d.ts) file containing `declare module 'expo-asset';`

7 export { Asset } from 'expo-asset';
                        ~~~~~~~~~~~~
```

**Comment by sjchmiela** [comment]
Hm… 🤔 now that I think about it I don't think types provided in `expo` package are _ready to be used_. Given discussion at https://github.com/expo/expo/pull/2617 (and your `expo-asset` problem), I think our type declarations may not be mature enough for us to recommend them to use it. Maybe definitions from `DefinitelyTyped` could solve the problem for now?

**Comment by SimenB** [comment]
Please come back with a way to tell typescript to use the ones from definitelytyped instead of the bundled ones if you find one 😀 For now I downgraded to 31 again

**Comment by dai-shi** [comment]
Hi, I'm back! 😁 

This is my project: https://github.com/dai-shi/typescript-expo-apollo-boilerplate
and especially the config is [here](https://github.com/dai-shi/typescript-expo-apollo-boilerplate/blob/0f528d87688357a6161263ddf233bb1d9fe51c6c/tsconfig.json#L13-L19).

**Comment by SimenB** [comment]
Perfect, thanks!

**Comment by slorber** [comment]
As far as I understand now Expo ships with typedefs so we should rather remove @types/expo from dependencies to avoid conflics or ambiguity (my ide made me think the @types/expo was still used, and this big change for TS users was not really documented in the SDK32 blog post. I think you should edit the blog post to avoid confusing so that users of TS know it will likely require some reworks because the @types/expo and the "official ones" do not map strictly yet.

After upgrading Expo from `"expo": "^31.0.0"` to `"expo": "^32.0.0"`, I had some TS errors, was able to fix most of them, but don't know about this one:

![image](https://user-images.githubusercontent.com/749374/51534008-c7c9a080-1e44-11e9-8f1a-f96f86bce359.png)

Any idea on how to fix this? even a workaround would be file

**Comment by sjchmiela** [comment]
As noted in https://github.com/expo/expo/issues/3155#issuecomment-452278491, although `expo` package ships with type definitions, only a part of Expo SDK has already been converted to TypeScript so our recommendation for now is still to use `@types/expo`. 🙂

**Comment by SimenB** [comment]
Might be a good idea to strip out your own types until they're ready for use

**Comment by sjchmiela** [comment]
cc @ide

**Comment by slorber** [comment]
@sjchmiela I've made a PR, it seems to do the job: https://github.com/expo/expo/pull/3285

**Comment by slorber** [comment]
@sjchmiela personnally TSC did pick the expo defs without asking me, while I still had community defs in my modules

**Comment by sjchmiela** [comment]
I think [@dai-shi's config](https://github.com/expo/expo/issues/3155#issuecomment-452289943) may help you override TSC's resolution system, but I haven't tried it myself, so 🤷‍♂️ 😞.

**Comment by slorber** [comment]
can confirm @dai-shi config works for me with minor changes because src is my root dir:

```js
{
  "compilerOptions": {
    "rootDir": "src",
    "baseUrl": "src",
    "paths": {
      "expo": ["../node_modules/@types/expo", "../node_modules/expo"],
    }
  },
}
```

**Comment by wcandillon** [comment]
@SimenB I ran into the same errors than you. To add the missing Audio API types, I included an extra type definition file: https://raw.githubusercontent.com/slavovojacek/adbrain-typescript-definitions/master/webspeechapi/webspeechapi.d.ts

This is how my tsconfig look like: 
https://gist.github.com/wcandillon/10f40b913f1c63f357169b97473f9eb2

**Comment by ide** [comment]
I published `expo@32.0.2-rc.0`, which excludes .d.ts files from the expo package. Dependencies of the expo package still have .d.ts files. If this patch update looks like it works well for people, we'll publish a non-RC version.

**Comment by wcandillon** [comment]
@ide Does it mean that we should now rely on the expo type definition from `@types` instead? Is there a plan in the long run to ship/support the `d.ts` files directly from the expo package?

**Comment by ide** [comment]
In the long run we will include .d.ts definitions with the expo package. Until then, we have no types (other than in the source .ts files) from the Expo team.

**Comment by satya164** [comment]
The latest version of `expo` package doesn't have type declaration files and I have sent a PR to DT to update the types: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32002

**Comment by satya164** [comment]
It's merged 🎉

**Comment by zaynv** [comment]
Any chance anyone has a minimal boilerplate for using TypeScript with Expo 32? The only boilerplate that I've seen seems to have the `babel.config.js`file removed but I'd like to keep it so that I can keep using [`react-native-dotenv`](https://github.com/zetachang/react-native-dotenv). Would be greatly appreciated!
