### ISSUE TITLE
[expo-video] v1.2.6 breaks the whole Expo App on Web

### ISSUE THREAD

**Issue by JeanDes-Code** [expo/expo#31565]
### Minimal reproducible example

https://github.com/JeanDes-Code/expo_video_web-bug_1.2.6_minimal_steps_to_reproduce

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

in a development build

### Summary

Hi !
When using the expo-video package in a React Native Expo project and attempting to run it on a web platform, the bundling process fails with an error related to module resolution for `../Utilities/Platform`.

### Steps to reproduce :

**1. Set Up Expo App:**
Open your terminal.
Create a new Expo app by running the command: `yarn create expo-app`.
**2. Install Dependencies:**
Install the expo-video package by running: `yarn expo install expo-video`.
**3. Prepare the Asset:**
Add a video file to the assets folder of your newly created Expo project.
**4. Modify the Homepage:**
Open the homepage file of your Expo project. (`app/(tabs)/index.tsx`)
Delete and replace with the following example code from the [expo-video documentation](https://docs.expo.dev/versions/latest/sdk/video/#usage):
```tsx
import { useVideoPlayer, VideoView } from 'expo-video';
import { useEffect, useRef, useState } from 'react';
import { StyleSheet, View, Button } from 'react-native';

import videoSource from '../../assets/videoSource.mp4';

export default function HomeScreen() {
  const ref = useRef(null);
  const [isPlaying, setIsPlaying] = useState(true);
  const player = useVideoPlayer(videoSource, player => {
    player.loop = true;
    player.play();
  });
  useEffect(() => {
    const subscription = player.addListener('playingChange', isPlaying => {
      setIsPlaying(isPlaying);
    });

    return () => {
      subscription.remove();
    };
  }, [player]);

  return (
    <View style={styles.contentContainer}>
      <VideoView
        ref={ref}
        style={styles.video}
        player={player}
        allowsFullscreen
        allowsPictureInPicture
      />
      <View style={styles.controlsContainer}>
        <Button
          title={isPlaying ? 'Pause' : 'Play'}
          onPress={() => {
            if (isPlaying) {
              player.pause();
            } else {
              player.play();
            }
            setIsPlaying(!isPlaying);
          }}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  contentContainer: {
    flex: 1,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 50,
  },
  video: {
    width: 350,
    height: 275,
  },
  controlsContainer: {
    padding: 10,
  },
});
```
**6. Start the project by running `yarn start`.**
**7. Once the Metro bundler is running, press the `s` key to select development build.**
**8. Target web by pressing `w`**
**9. Observe the Error:**
The bundling process should begin for the web. Monitor the output in the terminal.
The process will fail, and the following error related to the inability to resolve `../Utilities/Platform` will appear in the console.
![image](https://github.com/user-attachments/assets/ba7f821f-d78c-41ec-af5c-0e05577486c0)

### Expected behavior:
Upon starting the web development build, the application should successfully compile and render the `expo-video` component as per the documentation, without any bundling errors.

### Actual behavior:
The bundling process for the web platform fails with a Metro error indicating an inability to resolve the module `../Utilities/Platform` from `react-native/Libraries/Image/AssetSourceResolver.js`. This prevents the app from launching correctly and displaying the video component.

### Affected platforms:
This issue has been encountered only on web platform using Expo. 
It seems to be working on native, I've tested it successfully on Android Simulator.
![image](https://github.com/user-attachments/assets/cc45a3a7-39ac-44ff-a8c6-52f1c0917b10) 

### Error message:
```
Web Bundling failed 1526ms node_modules/expo-router/entry.js (802 modules)

Metro error: Unable to resolve module ../Utilities/Platform from /home/jean/odisei/demo_app_bug/node_modules/react-native/Libraries/Image/AssetSourceResolver.js: 

None of these files exist:
  * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.mjs|.mjs|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)
  * node_modules/react-native/Libraries/Utilities/Platform
  22 |
  23 | const PixelRatio = require('../Utilities/PixelRatio').default;
> 24 | const Platform = require('../Utilities/Platform');
     |                           ^
  25 | const {pickScale} = require('./AssetUtils');
  26 | const {
  27 |   getAndroidResourceFolderName,

  1 | /**
  2 |  * Copyright (c) Meta Platforms, Inc. and affiliates.
  3 |  *

Call Stack
  <unknown> (node_modules/react-native/Libraries/Image/AssetSourceResolver.js:0)
λ Bundling failed 1551ms node_modules/expo-router/node/render.js (868 modules)
```

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 21.6.1 - /usr/bin/node
      Yarn: 1.22.22 - /mnt/c/Program Files/nodejs/yarn
      npm: 10.7.0 - /usr/bin/npm
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.0.6
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by kimchouard** [comment]
This one is a sneaky one! 👹 

It's very hard from the error message to connect it to `expo-video`, luckily we had our CLI that built every commit so we could detect that going from `expo-video` v1.2.5 to v1.2.6 introduce this bug, which cause the whole app to crash (not just when loading a video, any page you try to load would render this build fail... 😬)

We're okay staying on v1.2.5 for now, but this will drive a lot of devs crazy, esp. when starting using expo-video straight on the current v1.2.6. Thanks in advance for the fix 🙏

**Comment by kacperkapusciak** [comment]
@behenate expo-video `v1.2.6` doesn't compile on Web, works fine on Android and iOS

the error message:

```sh
Web Bundling failed 1958ms index.js (315 modules)
Unable to resolve "../Utilities/Platform" from "node_modules/react-native/Libraries/Image/AssetSourceResolver.js"
```

`v1.2.5` works just fine on every supported platform

it is most probably caused by changes introduced in https://github.com/expo/expo/pull/30837

here's a repo with minimal reproduction: https://github.com/kacperkapusciak/expo-video-1.2.6-bug/blob/main/App.js

cheers

**Comment by behenate** [comment]
Hi everyone! Sorry for not spotting the issue before releasing 😅 This is caused by https://github.com/necolas/react-native-web/issues/1666 For now a quick workaround is to install `expo-asset` and create a metro config that will replace the `resolveAssetSource` from `react-native` with `resolveAssetSource` from `expo-asset` on web using `metro-config.js` (see [this](https://docs.expo.io/guides/customizing-metro)):

```js
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);


/** Replace react-native resolveAssetSource with expo-asset resolveAssetSource */
const WEB_ALIASES = {
  'react-native/Libraries/Image/resolveAssetSource': 'expo-asset/build/resolveAssetSource',
};

config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (platform === 'web') {
    return context.resolveRequest(context, WEB_ALIASES[moduleName] ?? moduleName, platform);
  }
  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
```

Seems to have fixed the issue in the repro for me. 

Please wait a little longer for a solution in the `expo-video` code

**Comment by ycryptx** [comment]
I'm still getting the issue (expo-video 1.2.7)
<img width="1564" alt="Screenshot 2024-10-01 at 1 42 42 PM" src="https://github.com/user-attachments/assets/f9d8fa1b-92ed-4150-9a79-3767c9459a36">

**Comment by behenate** [comment]
@ycryptx Does it work on 1.2.5 for you?
