### ISSUE TITLE
Font crash on ios after sdk 51 - Dictionary.subscript.getter (FontFamilyAliasManager.swift)

### ISSUE THREAD

**Issue by emilje-cap** [expo/expo#31563]
### Minimal reproducible example

unable

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

--

### Summary

Unable to reproduce on personal devices, but from Sentry reports (and other related font crash threads) a great deal of users are experiencing the same crash on ios devices after updating to sdk 51. Here are the relevant Sentry reports. 
We are using .ttf fonts, and tried loading them using loadAsync, useFonts and app config. The same error always remains. The trouble is that I was not able to reproduce the issue on my iPhone 11, even though there are iPhone 11s among the crash reports.

Please don't close the thread, I was asked by @lukmccall to create a new thread to make it easier to keep track.

![image](https://github.com/user-attachments/assets/5d14553b-c3fe-47e2-8006-0351f3c8adfc)
![image](https://github.com/user-attachments/assets/e0346d72-5095-4def-80c6-d92466e3d157)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-223.8836.35.2231.10406996    
    npmPackages:
      expo: ~51.0.31 => 51.0.32 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by nnimoyoefoki** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by lukmccall** [comment]
Maybe connected with https://github.com/expo/expo/issues/29030.

**Comment by nabilfreeman** [comment]
We are experiencing this almost every day in production. Package versions:

- expo: 51.0.31
- expo-font: 12.0.10

I just keep updating `expo-font` in the hopes this will go away but it's not fixed yet.

Here's a selected stack trace from a couple of hours ago which looks similar to OP:

```
MyAppName
+0x0ed3e0
Dictionary.subscript.getter (FontFamilyAliasManager.swift)

MyAppName
+0x0ed3e0
FontFamilyAliasManager.familyName (FontFamilyAliasManager.swift:37)
MyAppName
+0x0ed3e0
UIFont._expo_fontNames (UIFont+FontFamilyAlias.swift:15)
MyAppName
+0x0ed3d8
FontFamilyAliasManager.familyName (FontFamilyAliasManager.swift)
MyAppName
+0x0ed3d8
UIFont._expo_fontNames (UIFont+FontFamilyAlias.swift:15)
MyAppName
+0x0ed2c4
UIFont._expo_fontNames (<compiler-generated>)
In App
MyAppName
+0x0ed2c4
UIFont._expo_fontNames (<compiler-generated>:10)
In App
MyAppName
+0x2b1a14
fontNamesForFamilyName (RCTFont.mm:175)
MyAppName
+0x2b1104
+[RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:] (RCTFont.mm:448)
MyAppName
+0x44d0c8
-[RCTTextAttributes effectiveFont] (RCTTextAttributes.mm:220)
MyAppName
+0x44cca8
-[RCTTextAttributes effectiveTextAttributes] (RCTTextAttributes.mm:150)
MyAppName
+0x448ef8
-[RCTBaseTextShadowView attributedTextWithBaseTextAttributes:] (RCTBaseTextShadowView.mm:101)
MyAppName
+0x44ead8
-[RCTTextShadowView attributedTextWithMeasuredAttachmentsThatFitSize:] (RCTTextShadowView.mm:179)
MyAppName
+0x44ee58
-[RCTTextShadowView textStorageAndLayoutManagerThatFitsSize:exclusiveOwnership:] (RCTTextShadowView.mm:227)
MyAppName
+0x44decc
RCTTextShadowViewMeasure (RCTTextShadowView.mm:385)
```

I note with interest that this is happening on a `RCTTextShadowView` - wonder if it is related?

We are using custom fonts in our application which are in `.ttf` format. We are loading them using:

```
			await Font.loadAsync({
				RightGothicItalic: require('../../../assets/fonts/PPRightGothic-CompactRegularItalic.otf'),
				F37Beckett700: require('../../../assets/fonts/F37Beckett-Bold.otf'),
				RightGothic500: require('../../../assets/fonts/PPRightGothic-Medium.otf'),
				'F37 Beckett': require('../../../assets/fonts/F37Beckett-Regular.otf'),
				'PP Right Gothic': require('../../../assets/fonts/PPRightGothic-CompactRegular.otf'),
			});
```

Device (there are many, but this latest crash is from the following one):

- iPhone 13
- iOS 17.6.1

**Comment by events-jonas-chrisw** [comment]
> We are experiencing this almost every day in production. Package versions:
> 
> * expo: 51.0.31
> * expo-font: 12.0.10
> 
> I just keep updating `expo-font` in the hopes this will go away but it's not fixed yet.
> 
> Here's a selected stack trace from a couple of hours ago which looks similar to OP:
> 
> ```
> MyAppName
> +0x0ed3e0
> Dictionary.subscript.getter (FontFamilyAliasManager.swift)
> 
> MyAppName
> +0x0ed3e0
> FontFamilyAliasManager.familyName (FontFamilyAliasManager.swift:37)
> MyAppName
> +0x0ed3e0
> UIFont._expo_fontNames (UIFont+FontFamilyAlias.swift:15)
> MyAppName
> +0x0ed3d8
> FontFamilyAliasManager.familyName (FontFamilyAliasManager.swift)
> MyAppName
> +0x0ed3d8
> UIFont._expo_fontNames (UIFont+FontFamilyAlias.swift:15)
> MyAppName
> +0x0ed2c4
> UIFont._expo_fontNames (<compiler-generated>)
> In App
> MyAppName
> +0x0ed2c4
> UIFont._expo_fontNames (<compiler-generated>:10)
> In App
> MyAppName
> +0x2b1a14
> fontNamesForFamilyName (RCTFont.mm:175)
> MyAppName
> +0x2b1104
> +[RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:] (RCTFont.mm:448)
> MyAppName
> +0x44d0c8
> -[RCTTextAttributes effectiveFont] (RCTTextAttributes.mm:220)
> MyAppName
> +0x44cca8
> -[RCTTextAttributes effectiveTextAttributes] (RCTTextAttributes.mm:150)
> MyAppName
> +0x448ef8
> -[RCTBaseTextShadowView attributedTextWithBaseTextAttributes:] (RCTBaseTextShadowView.mm:101)
> MyAppName
> +0x44ead8
> -[RCTTextShadowView attributedTextWithMeasuredAttachmentsThatFitSize:] (RCTTextShadowView.mm:179)
> MyAppName
> +0x44ee58
> -[RCTTextShadowView textStorageAndLayoutManagerThatFitsSize:exclusiveOwnership:] (RCTTextShadowView.mm:227)
> MyAppName
> +0x44decc
> RCTTextShadowViewMeasure (RCTTextShadowView.mm:385)
> ```
> 
> I note with interest that this is happening on a `RCTTextShadowView` - wonder if it is related?
> 
> We are using custom fonts in our application which are in `.ttf` format. We are loading them using:
> 
> ```
> 			await Font.loadAsync({
> 				RightGothicItalic: require('../../../assets/fonts/PPRightGothic-CompactRegularItalic.otf'),
> 				F37Beckett700: require('../../../assets/fonts/F37Beckett-Bold.otf'),
> 				RightGothic500: require('../../../assets/fonts/PPRightGothic-Medium.otf'),
> 				'F37 Beckett': require('../../../assets/fonts/F37Beckett-Regular.otf'),
> 				'PP Right Gothic': require('../../../assets/fonts/PPRightGothic-CompactRegular.otf'),
> 			});
> ```
> 
> Fonts are **working normally** in development, QA and production. So it's a mystery why/when this is happening. Customers are not reporting it to us, which makes me wonder if it is a crash while the app is in background.
> 
> Device (there are many, but this latest crash is from the following one):
> 
> * iPhone 13
> * iOS 17.6.1

Exactly the same problems as us here (All users are IOS 17.5.1 and later). We are using the useFonts hook to load custom fonts, but I think the issue could be to do with the inbuilt vector-icons fonts...

**Comment by nabilfreeman** [comment]
Thanks @events-jonas-chrisw , just to annotate your info, we have a slightly wider distribution of iOS versions:

- iOS 15.8.2
- iOS 16.0.2
- iOS 16.1.1
- iOS 17.4.1
- iOS 17.5.1
- iOS 17.6.1"
- iOS 17.7

**Comment by bytemtek** [comment]
Same here

 "expo": "^51.0.32",
 "expo-font": "~12.0.10"

**Comment by 1forh** [comment]
We're having the same issue occasionally in our app. 

"expo": "^51.0.30",
"expo-font": "~12.0.9",

**Comment by xerdnu** [comment]
Same issue here, it seems to only happen once for every user just after app installation. I am unable to reproduce it :/

"expo": "~51.0.36",
"expo-font": "~12.0.10",

**Comment by cemck** [comment]
Same issue, I don’t use any custom fonts. I also think this happens with usage of build in vector icons fonts
"expo": "51.0.34"

**Comment by xerdnu** [comment]
Seems to happen on different iOS versions.

I managed to reproduce it after clean installation with logs from sentry below:

```
EXC_BAD_ACCESS
Exception 1, Code 1, Subcode 9223372036854775824 >
KERN_INVALID_ADDRESS at 0x8000000000000010.

Fatal crash on thread UIFont._expo_fontNames
```

**Comment by vinrei** [comment]
This affecting my app too on iOS. Mostly on pro and pro-max iPhones.
https://github.com/expo/expo/issues/29030#issuecomment-2351345485
<img width="313" alt="Screenshot 2024-10-11 at 9 15 23 PM" src="https://github.com/user-attachments/assets/49a48f41-414e-4b06-a7ef-13c90d127df0">
As a test, I have delayed mounting of most of my app content (200ms), and even further delayed mounting my react-native-paper search bar (400ms) for 15 pro max and 12 pro max. The bug has not occurred again on these two models since my test was pushed to prod

**Comment by xerdnu** [comment]
> This affecting my app too on iOS. Mostly on pro and pro-max iPhones.
> 
> https://github.com/expo/expo/issues/29030#issuecomment-2351345485
> 
> <img width="313" alt="Screenshot 2024-10-11 at 9 15 23 PM" src="https://github.com/user-attachments/assets/49a48f41-414e-4b06-a7ef-13c90d127df0">
> 
> As a test, I have delayed mounting of most of my app content (200ms), and even further delayed mounting my react-native-paper search bar (400ms) for 15 pro max and 12 pro max. The bug has not occurred again on these two models since my test was pushed to prod
> 
> 

Any updates on if this fixed the crashes? :)

**Comment by valentinchelle** [comment]
Same issue with "expo": "~51.0.37" and "expo-font": "~12.0.10". Wide range of devices and iOS versions.

**Comment by yoann84** [comment]
Same issue here.
I have this problem with this fonts : 
```
 [
      "expo-font",
      {
        fonts: [
          "./assets/fonts/Inter-Black.otf",
          "./assets/fonts/Inter-Bold.otf",
          "./assets/fonts/Inter-ExtraBold.otf",
          "./assets/fonts/Inter-Light.otf",
          "./assets/fonts/Inter-Medium.otf",
          "./assets/fonts/Inter-Regular.otf",
          "./assets/fonts/Inter-SemiBold.otf",
          "./assets/fonts/Inter-Thin.otf",
        ],
      },
    ],
```

Only ios and mostly for pro max.
Also mostly for ios 17.6.1

<img width="319" alt="Capture d’écran 2024-10-30 à 15 58 54" src="https://github.com/user-attachments/assets/96e4d9a9-ba82-46a1-8d57-a5f981c80e9f">

**Comment by vinrei** [comment]
> > This affecting my app too on iOS. Mostly on pro and pro-max iPhones.
> > [#29030 (comment)](https://github.com/expo/expo/issues/29030#issuecomment-2351345485)
> > <img alt="Screenshot 2024-10-11 at 9 15 23 PM" width="313" src="https://private-user-images.githubusercontent.com/38410447/375679674-49a48f41-414e-4b06-a7ef-13c90d127df0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MDUxNDMsIm5iZiI6MTczMTcwNDg0MywicGF0aCI6Ii8zODQxMDQ0Ny8zNzU2Nzk2NzQtNDlhNDhmNDEtNDE0ZS00YjA2LWE3ZWYtMTNjOTBkMTI3ZGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDIxMDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMGM1ZGI4ODRjNTczYjE4ZjhmMDU4NTcwNjcxZTI1YTFjYWM2NjNiYWU1MDk2OWU2ODdiYTlhNzFlMWMwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zSBkfVph_iM5cEZ6BC6Pa3EpeBjAvPxkheNe8qGy-6k">
> > As a test, I have delayed mounting of most of my app content (200ms), and even further delayed mounting my react-native-paper search bar (400ms) for 15 pro max and 12 pro max. The bug has not occurred again on these two models since my test was pushed to prod
> 
> Any updates on if this fixed the crashes? :)

The rate of errors decreased significantly after making this ""fix"". It did not 100% eliminate it though

**Comment by cemck** [comment]
> Same issue, I don’t use any custom fonts. I also think this happens with usage of build in vector icons fonts. It crashes one time after app installation 
> 
> "expo": "51.0.34"

The issue seems to be decreased or (completely fixed) now on newer expo versions. The crash didn't occur for a long time now for my app after upgrading expo. Needs more testing though

**Comment by AlejandroRM-DEV** [comment]
Same here.

"@expo/vector-icons": "^13.0.0"
"expo": "^51.0.21"

![Captura de pantalla 2024-11-25 a la(s) 1 52 18 p m](https://github.com/user-attachments/assets/fd35c62d-558c-46ee-930e-b0472ffb4558)

It doesn't seem crash to users but Sentry it's getting many hits

**Comment by yoann84** [comment]
I've tried to use TTF fonts instead of OTF but it doesn't work either and It also crashed on my phone on production mode.

**Comment by cemck** [comment]
> > Same issue, I don’t use any custom fonts. I also think this happens with usage of build in vector icons fonts. It crashes one time after app installation
> > "expo": "51.0.34"
> 
> The issue seems to be decreased or (completely fixed) now on newer expo versions. The crash didn't occur for a long time now for my app after upgrading expo. Needs more testing though

Update: the issue is still present on newest expo version 52

**Comment by fatlinesofcode** [comment]
we have a react native and are only using expo-updates.

we see this crash in our production environment even though we have no usages of expo-font, we have our fonts defined in react-native.config

expo 51 + expo-font 12

```
rashed: com.facebook.react.ShadowQueue
0  App                  0x1adda0 specialized static UIFont._expo_fontNames(forFamilyName:) + 6 (FontFamilyAliasManager.swift:6)
1  App                  0x1adc88 @objc static UIFont._expo_fontNames(forFamilyName:) + 4306230408 (<compiler-generated>:4306230408)
2  App                   0x5a8c64 fontNamesForFamilyName(NSString*) + 175 (RCTFont.mm:175)
3  App                   0x5a8370 +[RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:] + 450 (RCTFont.mm:450)
```

**Comment by dev2xl** [comment]
Could this fix also be made available in v12 for iOS 13? Many of us are not yet ready to increase the minimum iOS version of our apps to iOS 15. Thank you!

**Comment by xerdnu** [comment]
Can we please get this into v12 aswell?

**Comment by joshuadunning** [comment]
Also asking for this in v12. We are unable to upgrade to sdk 52 until other dependencies catch up.

**Comment by nabilfreeman** [comment]
Same issue here, we are blocked by one payments library that is still working on New Architecture Support and stuck on Expo 51. 

Please update v12 so our customers get the fix, and our expo doctor doesn’t complain 😇

Thank you!

**Comment by xerdnu** [comment]
I added the changes with **patch-package** for now until v12 hopefully gets fixed aswell. 

Not yet ready for iOS 15.

**Comment by nabilfreeman** [comment]
> I added the changes with **patch-package** for now until v12 hopefully gets fixed aswell.
> 
> Not yet ready for iOS 15.

@xerdnu any chance you could please post the contents of your patch file here?

**Comment by xerdnu** [comment]
@nabilfreeman  

1. Install [patch-package](https://github.com/ds300/patch-package) and make sure to add postinstall to scripts in package.json (see instructions).

2. Make sure you have a clean install of the latest expo-font v12 installed using npm inside your project.

3. Inside node_modules find expo-font and edit ios/FontFamilyAliasManager.swift. Add the changes inside FontfamilyAliasManager from these commits.

[commit 1](https://github.com/expo/expo/pull/33574/commits/2a3a859ccef4bd57d1db5be5d5eedc308593b916)
[commit 2](https://github.com/expo/expo/pull/34044/commits/2fb551e84d59598023eb431c017ef61b7e56f3e7)

Inside your project folder run npx patch-package expo-font.

Done, rebuild your project.

**Comment by nabilfreeman** [comment]
Thanks @xerdnu - here is the patch file for anybody else looking for a turnkey fix:

# expo-font+12.0.10.patch

```patch
diff --git a/node_modules/expo-font/ios/FontFamilyAliasManager.swift b/node_modules/expo-font/ios/FontFamilyAliasManager.swift
index 6f291c3..f785185 100644
--- a/node_modules/expo-font/ios/FontFamilyAliasManager.swift
+++ b/node_modules/expo-font/ios/FontFamilyAliasManager.swift
@@ -10,6 +10,11 @@ private var fontFamilyAliases = [String: String]()
  */
 private var hasSwizzled = false
 
+/**
+ Queue to protect shared resources
+ */
+private let queue = DispatchQueue(label: "expo.fontfamilyaliasmanager", attributes: .concurrent)
+
 /**
  Manages the font family aliases and swizzles the `UIFont` class.
  */
@@ -18,7 +23,9 @@ internal struct FontFamilyAliasManager {
    Whether the given alias has already been set.
    */
   internal static func hasAlias(_ familyNameAlias: String) -> Bool {
-    return fontFamilyAliases[familyNameAlias] != nil
+    return queue.sync {
+      fontFamilyAliases[familyNameAlias] != nil
+    }
   }
 
   /**
@@ -27,14 +34,18 @@ internal struct FontFamilyAliasManager {
    */
   internal static func setAlias(_ familyNameAlias: String, forFont font: String) {
     maybeSwizzleUIFont()
-    fontFamilyAliases[familyNameAlias] = font
+    queue.sync(flags: .barrier) {
+      fontFamilyAliases[familyNameAlias] = font
+    }
   }
 
   /**
    Returns the family name for the given alias or `nil` when it's not set yet.
    */
   internal static func familyName(forAlias familyNameAlias: String) -> String? {
-    return fontFamilyAliases[familyNameAlias]
+    return queue.sync {
+      fontFamilyAliases[familyNameAlias]
+    }
   }
 }
 ```
