### ISSUE TITLE
[Expo Router] Unable to change the content style of a `Tabs.Screen`

### ISSUE THREAD

**Issue by AnatoleLucet** [expo/expo#31560]
### Minimal reproducible example

https://github.com/AnatoleLucet/repro-expo-router

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I'm unable to change the content style of a `Tabs.Screen`.
It seems `Tabs.Screen`'s options prop doesn't accept a `contentStyle` property as `Stack.Screen`'s options does for instance.

#### Repro
- clone the repo (it's the default expo template)
- install deps & start expo
- open [this line](https://github.com/AnatoleLucet/repro-expo-router/blob/main/app/(tabs)/_layout.tsx#L17)

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.9 Manjaro Linux
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.15.0 - /run/user/1000/fnm_multishells/32898_1726730490102/bin/node
      Yarn: 1.22.22 - /usr/bin/yarn
      npm: 10.7.0 - /run/user/1000/fnm_multishells/32898_1726730490102/bin/npm
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Tabs does not have a `contextStyle` option. Do you mean `sceneContainerStyle`?

Reference: https://reactnavigation.org/docs/bottom-tab-navigator#props
