### ISSUE TITLE
[expo-app-auth][android] Google Signin Doesn't Resolve and Redirects to Projects Screen in Expo Android App

### ISSUE THREAD

**Issue by reggie3** [expo/expo#3157]
### Environment

 Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.4 Ubuntu 16.04.4 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.10.1 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    npmGlobalPackages:
      expo-cli: 2.6.14

Target: Android
### Steps to Reproduce
Recreate Google sign-in example from documentation as [](https://docs.expo.io/versions/v32.0.0/sdk/google)

my actual code is as follows:
```
onGoogleSignIn = async () => {
    console.log('Trying google sign in')

    this.setState({ loginInProgress: true })
    try {
      const result = await Google.logInAsync({
        androidClientId: googleCreds.androidClientID,
        iosClientId: googleCreds.iosClientID,
        scopes: ['profile', 'email'],
      });
      console.log({result});
      if (result.type === 'success') {
        return result.accessToken;
      } else {
        return {cancelled: true};
      }
    } catch(e) {
      return {error: true};
    }
 }
```

(Write your steps here:)

1. User presses a button to execute the onGoogleSignIn function above
2. "Trying google sign in" is printed to the JavaScript console as expected
3. Google accounts screen displays on Android device
4. User selects a Google account from accounts screen

### Expected Behavior

The `Google.logInAsync` function should resolve with Google account information or an error should be caught.

### Actual Behavior
"Trying google sign in" is printed to the JavaScript console as expected
The `Google.loginAsync` function does not resolve, and no error is caught
The "Projects" screen from the Expo Android app is displayed.  
Additionally, my application displays an `ActivityIndicator` when the user presses a Google Sign In that initiates the process.  The `ActivityIndicator` displays and remains displaying when I return to the application after being sent to the Projects screen indicating my application is not crashing or has not shut down in the process

No error screen appears during the process.

### Reproducible Demo

[Snack](https://snack.expo.io/@reggie3/google-login-example)

**Comment by EvanBacon** [comment]
I left my pixel at home today but I I'll get back to you soon. 

## Insight

I rewrote `Expo.Google` to be a JS module which combines two new Unimodules
* expo-app-auth for OAuth
* expo-google-sign-in for Native Auth (which I ended up pulling out)

I finished the module a while before 32 landed so I imagine something must've changed during that time. The AppAuth lib will redirect to the Expo App but then it should be routing you back in your application. This last step required some manifest code that may not work as expected.

As a side-note there is now a logout feature that is currently undocumented.

**Comment by reggie3** [comment]
Thanks, and great to hear about the logout feature. I look forward to trying it.

**Comment by EvanBacon** [comment]
I just ran https://github.com/expo/expo/blob/master/apps/native-component-list/screens/GoogleScreen.js with v32 and everything seems to be working as expected. Is your application a standalone app?

-

**Comment by reggie3** [comment]
I'm currently running the app from the Expo client, but I eventually plan to deploy it as standalone app.
I see that you're using a `clientId` parameter in `Google.logInAsync`.  I don't see that parameter in the documentation. What is it's purpose, and what should it be set to?  If I mimic the example from `GoogleScreen.js`, I get the same result as reported above.

After looking through the Expo repo, should I be following  [GoogleSignInScreen.js](https://github.com/expo/expo/blob/cfe899cc8a59eb892a193a94c54890b3c8ee160c/apps/native-component-list/screens/GoogleSignInScreen.js) as an example? Is there now a GoogleSignIn component that is available?

**Comment by EvanBacon** [comment]
I have partially identified. The issue, something to do with the versioning of the library. Hopefully we have it resolved soon. Until then you could:
* roll back to 31
* try setting the `version` prop in your `app.json` to `UNVERSIONED` - this may not work on the play store client but it does on mine.

The versioning should be such that when I built the module using `UNVERSIONED` it would be cloned over to `32.0.0` but it seems like something here isn't working as expected (or I'm just mixing the issue up with some other problem 🙃 ) Really sorry for the inconvenience.

**Comment by vijay2330** [comment]
@EvanBacon  Thanks for detail of this issue. Is this fix will be done soon or later?

**Comment by reggie3** [comment]
@EvanBacon Does the fix require doing both of those steps, or just one or the other?

**Comment by ilyausorov** [comment]
Can confirm rolling back to SDK 31 seems to be the best solution at the moment. Will wait for the Expo team to fix this issue in SDK 32

**Comment by ravixini** [comment]
@EvanBacon Sorry for bothering you, but is there any ETA on the fix for Google login on expo v32 ? Asking for people that are using SMS module and who can't go back to version 31 because of new guidelines from Google about SMS_READ permission.

Thanks.

**Comment by muhammadsarim555** [comment]
I have rolled in 31 sdk but i am still stucked in this issue, on android  it's not responding even though if i check this on iOS it is working fine.

**Comment by opringle** [comment]
Also having this issue with Expo 32.0.0 on a Pixel 3 & Pixel 3 emulator. My Nexus 5 emulator does not have the problem. IOS works fine.

**Comment by adititipnis** [comment]
Same issue on my OnePlus6T

**Comment by sjchmiela** [comment]
The fix has landed on master, we'll notify you once/if we also release an updated version of the Expo Client, to which the fix applies (standalone/ejected builds aren't supposed to be affected by this bug).

**Comment by geekysrm** [comment]
I faced this issue today, after much debugging reverting to version 31.0 fixed it for me.

But I faced some difficulty in getting the `react-native` and `react` versions for expo sdk v31.0
Nonetheless, I found them,

Change your `package.json` to:
  ```
...
"expo": "^31.0.0",

    "react": "16.5.0",

	"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
...

```
and change the sdkVersion in app.json:
`"sdkVersion": "31.0.0"`

Now `rm -rf node_modules` and run `yarn` or `npm i` again.
Then try to run the app by `yarn start` or `npm start`.
It works!! :100:

**Comment by brunohkbx** [comment]
Any update on this?

**Comment by sjchmiela** [comment]
@Szymon20000 has released an update to Expo Client, 2.10.6, which is already available as an update on the Play Store. It should fix the issue. 🙂

**Comment by buthig** [comment]
Is this solved? I'm asking because by downgrading to expo@31 as @geekysrm pointed out worked for me, although I was already running Expo Client 2.10.6 and was facing the issue with promises not being run.

**Comment by novuw** [comment]
@EvanBacon I have been toying with this for about a month, and still am having a hard time getting it to work. I followed the instructions on the expo-google-sign-in page (for SA apps), but when I go to access it in testflight, a blank page appears on my screen. A screenshot is attached.
![IMG_0009](https://user-images.githubusercontent.com/23667979/54862035-98cb9000-4d0a-11e9-8ae5-e400e9d89daf.PNG)
![IMG_0010](https://user-images.githubusercontent.com/23667979/54862037-9c5f1700-4d0a-11e9-824f-c83d2fda771e.PNG)


Any ideas? Thanks.

**Comment by sjchmiela** [comment]
Hey, @novuw, could you please open a new issue describing this problem?

On a side note, similar thing was happening in `expo-sharing` module when we didn't hold a strong reference to `UIDocumentInteractionController` (the URL would become blank and nothing would be shared), maybe we should do something like this here too?

**Comment by novuw** [comment]
@sjchmiela Absolutely! My project has been on hold for about a month because of this, so I'm hoping to get it on the road soon. I'll open up an issue right now and tag you in it.
Thanks!

**Comment by minhdang-idev** [comment]
I encounter the same issue. After upgrading to SDK 32, my google Expo.Google.logInAsync does not work properly. It can open a popup to let user select google account, after that it closes the popup and returns nothing. No errors were catch.

Any updates on it?

**Comment by brunohkbx** [comment]
@minhdang-idev did you update your expo client?

**Comment by minhdang-idev** [comment]
@brunohkbx yes, yesterday I updated my RN project from Expo SDK 31 to SDK 32 then I faced to the google login issue. After that I downgrade my Expo from 32 to 31 and it works fine. What should I do now? Thank you in advance.

**Comment by brunohkbx** [comment]
@minhdang-idev I mean your expo client on your phone. Its version should be >= 2.10.6 to works fine like @sjchmiela said.

**Comment by minhdang-idev** [comment]
@brunohkbx I don't use expo client for now. I am using Genymotion to run the emulator. My emulator device is Samsung galaxy S7 Android 8.0 API 26. In Genymotion settings -> ADB connections -> I choose Use genymotion android tools (default).

What I concern is: using the same code, same emulator, the only difference is Expo 31 and Expo 32.
Expo 31: works perfectly.
Expo 32: not working at all (behavior is described in my comment above).
I have no idea how to fix it. Can you please help?

**Comment by danikane** [comment]
Whether it's on a physical device, an Android or Genymotion emulator there is always an Expo client.
Current (and last) version is 2.10.6, it contains that missing intent.
Now I am not sure exactly what gets pushed to the emulator via adb. I've read an article before how to **downgrade** the Expo client on an iOS simulator on MacOS.
I guess you can check the version and report back.

Should it be any older I believe you can put the latest version to use in Genymotion:
https://d1ahtucjixef4r.cloudfront.net/Exponent-2.10.6.apk

`
adb install Exponent-2.10.6.apk //or adb push ...
`
https://docs.genymotion.com/latest/Content/03_Virtual_Devices/Deploying_an_application.htm

**Comment by minhdang-idev** [comment]
@danikane Thank you very much! It works like a charm now! Sorry I am new to RN and Expo. I forgot that I still needed to install Expo on my emulator too. I upgraded Expo client in my emulator by drag and drop as your guide mentioned. Now Google Login works perfectly!
