### ISSUE TITLE
DevX Bug: Navigation resets and incorrect screen appears when moving a route file in the app folder

### ISSUE THREAD

**Issue by charlotteisambert** [expo/expo#31588]
### Minimal reproducible example

https://github.com/charlotteisambert/expo-router-screen-pop-bug-reproduction-example

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When moving a page file within the app folder, the navigation state resets unexpectedly, and a different screen appears. Specifically, the first screen defined in _layout shows up, even if it wasn't previously mounted.
Example of the issue in action:
```
<Stack>
    <Stack.Screen name="+not-found" />
</Stack>
```

![Sep-20-2024 10-51-43](https://github.com/user-attachments/assets/071a5d4d-b28e-4223-8e52-e21fb4a989df)
### Steps to reproduce :
Launch the app: `yarn start`
Move the `app/(tabs)/explore.tsx` file to `app/`.
### Observed behavior :
If I remove the definition of the +not-found screen:
```
<Stack />
```
the navigation state still resets, but the mounted screen follows the usual first-mount logic (i.e., the screen defined in app/(tabs)/index).
### Expected behavior: 
Ideally, the navigation state should not reset when a file is moved.
If resetting is unavoidable, the app should follow the same rules as the initial launch, defaulting to the index file rather than the first screen listed in the Stack.

### Platforms
iOS and Android

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/Library/Caches/fnm_multishells/4497_1726821630229/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/Library/Caches/fnm_multishells/4497_1726821630229/bin/npm
      Watchman: 2023.05.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/charlotte/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31, 33, 34
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-28 | Google Play Intel x86 Atom, android-30 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.32
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
Unfortunately at this time, this is expected behaviour. But it will be something we're looking to change in the future.

The issue is that Expo Router is built on top of React Navigation 6 which expects a config. But we generate the config from the file system - so when a file is moved we need to generate a navigation config. Because its a new config, React Navigation resets the navigation state. We know its not ideal, but its going to take some engineering effort between both Expo and React Navigation to change how things work. I hope you understand, sorry for the frustration
