### ISSUE TITLE
SDK32 - TaskManager API to register a task defined by TaskManager.defineTask

### ISSUE THREAD

**Issue by kokeksibir** [expo/expo#3160]
Please excuse me in advance for not using issue template / guideline.

My usecase is to implement something similar to BackgroundFetch in android. Defining a task does not add the task to the registered tasks lists when I check by calling `TaskManager.getRegisteredTasksAsync` so I assume I need to have a method to register the defined task.

What I have understood from the documentation and source code, When a task is defined, if it is related to `BackgroundFetch` then it is registered by calling `BackgroundFetch.registerTaskAsync`, if it is related to `Location` it is registered by calling `Location.startLocationUpdatesAsync`. Currently it seems there is no other way to register a defined task, am I missing something?

**Comment by ide** [comment]
Background tasks need a trigger like fetch or location events -> the point of the background API is to be able to respond to I/O like that in the background.

**Comment by tsapeta** [comment]
Yeah, TaskManager is more like a native API for other modules that would like to respond to events received in both foreground and background app states. So, registering and unregistering a task will usually take place in other modules (e.g. `Location`, `BackgroundFetch`).
For now, these are the only modules that use TaskManager and know how to register tasks. 

What's your use case in more details?

**Comment by kokeksibir** [comment]
So does it mean the only background task available for android is location? What I was expecting was TaskManager to be able to schedule the defined task just like in [react-native-background-task](https://www.npmjs.com/package/react-native-background-task). Anyway, thank you for explanation.

**Comment by kokeksibir** [comment]
> What's your use case in more details?

My app pulls data from different servers, there is no chance to push due to various reasons. I need to collect the updates in background and create notification in certain cases. Is it a proper usecase if TaskMqnager had task scheduling feature?

**Comment by tsapeta** [comment]
@kokeksibir I'm closing this discussion, but if you have any questions feel free to message me on Expo's Slack 😉 
I can also help you in implementing background fetch on Android if you'd be interested in contributing 😄
