### ISSUE TITLE
[Expo-server-sdk-node] Mismatch between Expo API Response and `ExpoPushErrorReceipt` Type Definition in expo-server-sdk-node v3.11.0

### ISSUE THREAD

**Issue by wl-devops-tech** [expo/expo#31612]
### Summary

**Title:** Mismatch between Expo API Response and `ExpoPushErrorReceipt` Type Definition in expo-server-sdk-node v3.11.0

**Description:**
I encountered an inconsistency between the Expo push notification API response and the TypeScript type definition `ExpoPushErrorReceipt` in the `expo-server-sdk-node` package (v3.11.0).

**Steps to Reproduce:**
1. Send a push notification via the Expo API using the following `curl` command:
   ```bash
   curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '{
     "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
     "title": "hello",
     "body": "world"
   }'
   ```
2. The API returns the following response:
   ```json
   {
     "data": {
       "status": "error",
       "message": "\"ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]\" is not a registered push notification recipient",
       "details": {
         "error": "DeviceNotRegistered",
         "expoPushToken": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]"
       }
     }
   }
   ```

**Observed Behavior:**
- In the API response, the `expoPushToken` field is nested inside the `details` object.
  
**Expected Behavior:**
- According to the `ExpoPushErrorReceipt` type in `expo-server-sdk-node v3.11.0`, the `expoPushToken` should be outside of the `details` object. Here's the relevant type definition:
   ```typescript
   export type ExpoPushErrorReceipt = {
     status: 'error';
     message: string;
     details?: {
       error?:
         | 'DeveloperError'
         | 'DeviceNotRegistered'
         | 'ExpoError'
         | 'InvalidCredentials'
         | 'MessageRateExceeded'
         | 'MessageTooBig'
         | 'ProviderError';
     };
     expoPushToken?: string;
     __debug?: any;
   };
   ```

**Issue:**
- The type definition has the `expoPushToken` field outside of the `details` object, whereas the actual API response includes it within `details`. This creates a mismatch when validating the response type with TypeScript.

### Link to the related docs page

https://github.com/expo/expo-server-sdk-node/tree/v3.11.0

**Comment by vonovak** [comment]
Hello and thanks for reporting,
this was resolved in https://github.com/expo/expo-server-sdk-node/pull/97
Thank you 🙂
