### ISSUE TITLE
[expo-print][android]: printAsync with custom width and height Android error 

### ISSUE THREAD

**Issue by kusaeva** [expo/expo#3162]
### Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1

Android 9, Client

### Steps to Reproduce

use Expo.Print.printAsync with custom width and height, e.g.

`const html = '<html><body><p>test</p></body></html>';`
`await Print.printAsync({ html, width: 595, height: 842 });
`

### Actual Behavior

Expo.Print.printAsync works just fine on Android with default width and height, but I when I set width and height 
to A4 format (595x842) there is an error:

![screenshot](https://user-images.githubusercontent.com/5486933/50849767-fe091980-1388-11e9-8716-8d21db3edca2.png)

The problem reproduced only on Android, on iOS it works well

### Reproducible Demo

[Snack example](https://snack.expo.io/@kuskusaeva/printasync-android-error)

**Comment by EvanBacon** [comment]
Really sorry for the inconvenience just opened a PR, thanks for the report!

**Comment by raudinm** [comment]
What is the status??, I have the same problem :confused:

**Comment by Fire-Hound** [comment]
> 
> 
> What is the status??, I have the same problem 😕

Same problem here too, any update?

**Comment by labadze** [comment]
Same error, any updates?

**Comment by Fire-Hound** [comment]
@labadze I dont think it's fixed as of yet. You will need to use it without height and width.

**Comment by esamelson** [comment]
Hi, I just tried this on SDK 35 and wasn't able to reproduce the error. We're closing old/inactive issues that apply to older SDK versions so I'm going to go ahead and close this now. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
