### ISSUE TITLE
Nested Screen iOS back button missing

### ISSUE THREAD

**Issue by HenrikZabel** [expo/expo#31630]
### Minimal reproducible example

https://github.com/HenrikZabel/expo-nested-router

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

As explained in the minimal reproduction of the issue:

The index screen of a nested navigator is missing the back button on iOS. Navigation (router.back(), etc.) works fine on both iOS and Android but only iOS is missing the back button. I didn't test this on the web because it doesn't matter to me.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
      Watchman: 2024.09.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    Expo Workflow: bare
```

**Comment by marklawlor** [comment]
This is the expected behaviour. On iOS the back button is present within the Stack header which you are hiding.

You may want to explore `headerMode` which changes how multiple headers are rendered https://reactnavigation.org/docs/stack-navigator/#headermode

**Comment by WKampel** [comment]
Not being able to go back doesn't make sense to me. Are you not supposed to nest stack navigators?

**Comment by marklawlor** [comment]
@WKampel The user has hidden the back button as a design choice. Please refer to this doc for more information on how to better handle nested stack navigators. If you have further questions, these are better asked on the `react-navigation` github, as Expo Router does not develop/maintain these components.

> You may want to explore headerMode which changes how multiple headers are rendered https://reactnavigation.org/docs/stack-navigator/#headermode
