### ISSUE TITLE
expo-video user-agent issue in Cyrillic name in app.json

### ISSUE THREAD

**Issue by DomnitskiyOleg** [expo/expo#31647]
### Summary

The video player does not work if the project is named in Cyrillic. What is the solution? It is also not possible to set the user-agent header manually. When application name is in english, player works normally.

{"message": "A playback exception has occurred: Source error Unexpected IllegalArgumentException: Unexpected char 0x41f at 0 in User-Agent value: Проблема у називању/1.0.0 (Linux;Android 10) AndroidXMedia3/1.4.0"}

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

{
  "name": "expo-issue",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~51.0.28",
    "expo-dev-client": "~4.0.26",
    "expo-status-bar": "~1.12.1",
    "expo-video": "^1.2.6",
    "react": "18.2.0",
    "react-native": "0.74.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  "private": true
}

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 4.4 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.17.0/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    npmPackages:
      expo: ~51.0.28 => 51.0.32 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 12.3.0
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/DomnitskiyOleg/expo-issue

**Comment by fobos531** [comment]
@behenate 

This would require adding to option to override the user agent string, or doing some kind of automatic user agent string sanitization/normalization.

**Comment by DomnitskiyOleg** [comment]
> @behenate
> 
> This would require adding to option to override the user agent string, or doing some kind of automatic user agent string sanitization/normalization.

```
type VideoSource = string | number | {
    uri?: string;
    assetId?: number;
    drm?: DRMOptions;
    metadata?: VideoMetadata;
    headers?: Record<string, string>;
} | null
```
when im trying to use headers key it can add new headers in request, but its not overwrite user-agent header (

**Comment by fobos531** [comment]
Hello @DomnitskiyOleg , you can follow the progress for fixing this issue in #31659
