### ISSUE TITLE
[expo-calendar] - unable to get one instance of a recurring event, only the first instance

### ISSUE THREAD

**Issue by jahnagoldman** [expo/expo#31668]
### Minimal reproducible example

-

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

To get/update/delete an instance of a recurring event, the code comments / documentation specify to provide the whole series ID plus the date of the instance you want returned.

See https://github.com/expo/expo/blob/7b7d6fdda2ab611fa0276e531f4e8b88142914b6/packages/expo-calendar/src/Calendar.ts#L890

This (e.g. `getEventAsync`) does not return the correct instance, and always returns the very first instance of the recurrence rather than the one that matches your provided date.

Seems to be caused by this function `getEvent`, this line https://github.com/expo/expo/blob/7b7d6fdda2ab611fa0276e531f4e8b88142914b6/packages/expo-calendar/ios/CalendarModule.swift#L577

The `firstEvent.startDate` is the beginning of the series, not that specific occurrence desired. So why, if it isn't equal to the instance `startDate` desired, would we return the `firstEvent`? WIth this line, we can never get the correct instance, only the very first one no matter what `startDate` is provided. If these lines (577-578) are commented out, then we would return the correct instance event of the recurrence and so the correct result.

### Environment

```text
N/A using bare react native with the library `expo-calendar`
```

### Expo Doctor Diagnostics

```text
N/A using bare react native build with the library `expo-calendar`
```

**Comment by Rengod95** [comment]
@jahnagoldman Did you resolve this problem? I have same issue on. the latest expo calendar do not work properly yet
