### ISSUE TITLE
Cannot get BottomTabBarHeight, always undefined

### ISSUE THREAD

**Issue by Vimiso** [expo/expo#31665]
### Minimal reproducible example

https://snack.expo.dev/MZxQqbk21eVjJI_ToTwpq

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

The snack I provided shows the expected behaviour when using `@react-navigation/bottom-tabs` directly.

In my setup I am using expo `Tabs` and need to access their height via a context. So I `npm i @react-navigation/bottom-tabs` and try to use it like so:

```jsx
import { Tabs } from 'expo-router'

const TabsLayout = () => {
  return (
    <Tabs screenOptions={{
      headerShown: false,
    }}>
      <Tabs.Screen
        name="settings"
        options={{
          title: 'Settings',
        }}
      />
    </Tabs>
  )
}

export default TabsLayout
```

```jsx
import { useContext } from 'react'
import { Text, View  } from 'react-native'
import { BottomTabBarHeightContext } from '@react-navigation/bottom-tabs'

const Settings = () => {
  const tabBarHeight = useContext(BottomTabBarHeightContext)

  console.log(tabBarHeight) // always undefined :(
  
  return (
    <Text>Hey</Text>
  )
}

export default Settings
```

Is this because I'm resolving a different instance of bottom tabs? If so, just how do we retrieve the tab bar height the expo way!?

### Environment

```text
expo-env-info 1.2.0 environment info:
System:
  OS: macOS 14.2.1
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
  npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
Managers:
  CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
  Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
  expo: ~51.0.28 => 51.0.32 
  expo-router: ~3.5.23 => 3.5.23 
  react: 18.2.0 => 18.2.0 
  react-dom: 18.2.0 => 18.2.0 
  react-native: 0.74.5 => 0.74.5 
  react-native-web: ~0.19.10 => 0.19.12 
Expo Workflow: managed
```

**Comment by Vimiso** [comment]
**Update:**
Not sure this is best practise but hooking into the same dependency did it:

```jsx
import { BottomTabBarHeightContext } from 'expo-router/node_modules/@react-navigation/bottom-tabs'
```

**Comment by ThusSpokeNomad** [comment]
Do you mind trying this approach instead?

```ts
import { useBottomTabBarHeight } from "@react-navigation/bottom-tabs";

const navbarHeight = useBottomTabBarHeight();
```

**Comment by Vimiso** [comment]
That will return undefined because I need to import `@react-navigation/bottom-tabs` which is a different version and instance to which expo stack is using under the hood.

**Comment by ThusSpokeNomad** [comment]
@Vimiso I have `"@react-navigation/native": "^6.1.18"` in my `package.json` and `expo install --fix` (or `--check`) would update its version when needed. I think Expo folks are maintaining version compatibility, so it'd be safe to use it like that. (also, you're literally indirectly importing it from node_modules manually, better put it into package.json anyway)

**Comment by marklawlor** [comment]
This is not an issue with Expo Router, rather your projects dependencies installing two versions of `@react-navigation/native`. I would recommend either locking your version to the same one Expo Router uses, or using a `package.json`  overrides/resolutions to forcefully set the version
