### ISSUE TITLE
[expo-screen-capture] Can't detect screenshots on Android 14+

### ISSUE THREAD

**Issue by david98** [expo/expo#31678]
### Minimal reproducible example

https://github.com/david98/expo-screen-capture-bug

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Trying to detect a screenshot being taken by using code found in the documentation (https://docs.expo.dev/versions/latest/sdk/screen-capture/#example-functions):

```jsx
const hasPermissions = async () => {
    const { status } = await ScreenCapture.requestPermissionsAsync();
    return status === 'granted';
  };

  useEffect(() => {
    let subscription;

    const addListenerAsync = async () => {
      if (await hasPermissions()) {
        subscription = ScreenCapture.addScreenshotListener(() => {
          alert('Thanks for screenshotting my beautiful app 😊');
        });
      } else {
        console.error('Permissions needed to subscribe to screenshot events are missing!');
      }
    };
    addListenerAsync();

    return () => {
      subscription?.remove();
    };
  }, []);
```

works just fine on iOS and Android versions 13 and below. When running on Android 14+, it looks like the screenshot listener is never called. 

Also, I don't really know whether this is related or not, but we're getting a lot of unhandled exceptions for this module on Firebase:

```
 Fatal Exception: expo.modules.kotlin.exception.Exceptions$MissingActivity: The current activity is no longer available
       at expo.modules.screencapture.ScreenCaptureModule.getCurrentActivity(ScreenCaptureModule.kt:21)
       at expo.modules.screencapture.ScreenCaptureModule.access$getCurrentActivity(ScreenCaptureModule.kt:17)
       at expo.modules.screencapture.ScreenCaptureModule$definition$lambda$9$$inlined$OnDestroy$1.invoke(ModuleDefinitionBuilder.kt:147)
       at expo.modules.screencapture.ScreenCaptureModule$definition$lambda$9$$inlined$OnDestroy$1.invoke(ModuleDefinitionBuilder.kt:89)
       at expo.modules.kotlin.events.BasicEventListener.call(EventListener.kt:13)
       at expo.modules.kotlin.ModuleHolder.post(ModuleHolder.kt:98)
       at expo.modules.kotlin.ModuleRegistry.post(ModuleRegistry.kt:92)
       at expo.modules.kotlin.AppContext.onDestroy$expo_modules_core_release(AppContext.kt:333)
       at expo.modules.kotlin.KotlinInteropModuleRegistry.onDestroy(KotlinInteropModuleRegistry.kt:91)
       at expo.modules.adapters.react.NativeModulesProxy.invalidate(NativeModulesProxy.java:171)
       at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:109)
       at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:86)
       at com.facebook.react.bridge.CatalystInstanceImpl.lambda$destroy$2(CatalystInstanceImpl.java:366)
       at com.facebook.react.bridge.CatalystInstanceImpl.$r8$lambda$Oa3wfVCkSpv9UbaDKR-owki1vUU()
       at com.facebook.react.bridge.CatalystInstanceImpl$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
       at java.lang.Thread.run(Thread.java:1012)
```

This seems to be happening only on Android 14:

<img width="545" alt="Screenshot 2024-09-25 at 10 25 02" src="https://github.com/user-attachments/assets/fd75579c-2462-4cdc-a59d-a3103ee9600e">

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.7
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 22.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.8.3 - /opt/homebrew/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 30, 31, 33, 33, 34, 34, 35
        Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google APIs ARM 64 v8a, android-35 | Google APIs Intel x86_64 Atom
    IDEs:
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.34 => 51.0.34
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 12.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by chrfalch** [comment]
Hi @david98! 

I've tested this on an Android 14 device and can verify that it works as expected - the callback is correctly invoked. This happens using both the new/old architecture. 

I've tried running this on an emulator as well, and can verify that it does **NOT** work on the Emulator.

There is a change in Android 14 that might be the source of the problem - from the [documentation](https://developer.android.com/about/versions/14/features/screenshot-detection):

> In Android 14, the system API only detects a screenshot if the user performs a specific combination of hardware button presses. The API doesn't detect screenshots that are taken when running test commands related to screenshots, including [ADB](https://developer.android.com/studio/command-line/adb), or within instrumentation tests that [capture the device's current screen contents](https://developer.android.com/reference/androidx/test/core/app/DeviceCapture).

Could you make sure to test this functionality on a real device using the volume down + power buttons to capture a screenshot and see if the callback is successfully invoked?

**Comment by david98** [comment]
Hi @chrfalch, thanks for the info. I did read that in the documentation and I was indeed testing using `adb` and `input keyevent 120` (which should correspond to the screenshot key combination). Screenshots taken with the emulator button or with adb are **NOT** detected even on Android 13 and below.

I see this behavior both in our app (deployed on Play Store), where users running Android 14 can't have their screenshot detected, and in my repro project (I am testing on a Samsung Galaxy A54 5G SM-A546E), where the alert does **NOT** popup.

**Comment by chrfalch** [comment]
Ok, great that you are aware of the adb limitations.  This all sounds a bit strange, I've tested it using a Samsung SM A20e (SM_A536B) in a development build (release/debug) and in Expo Go - both shows the expected output when taking a screenshot. Have you been able to test this on other devices to see if there are any difference in device families?

**Comment by chrfalch** [comment]
I was investigating this now and was able to reproduce in a small example where the `ScreenCapture.allowScreenCaptureAsync()` was not called at all, leading to the behaviour you're describing. When I explicitly called `allowScreenCaptureAsync` the callback started to arrive. The `allowScreenCaptureAsync` is removing the `FLAG_SECURE` on the Android window.

**Comment by chrfalch** [comment]
The reason for this not working is that on Android 14 a call to the function `registerScreenCaptureCallback` is needed to register the callback. In the current code this is done when either `allowScreenCaptureAsync` or `preventScreenCapture` is called. We need to fix this on Android 14 so that the registration code is run even without calling these methods. This is probably not caught during testing since calling one of those methods is done automatically in a hook in the test code.
