### ISSUE TITLE
[SDK 52 canary][create-expo-module]Error parsing github API response

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [expo/expo#31681]
### Summary

Trying to create a new module with `npx create-expo-module@canary` errors out after prompting for email because it queries github API but the response parsing code is incorrect.
It tries to read `json.data.total_count` but `total_count` is a top level property and `data` property doesn't exist in the response at all. All properties accessed as `json.data.<prop>` are actually properties on the `json` object itself.
Because of this the command is completely unusable in this version.

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

SDK 52

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.16.0/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 23, 30, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Minimal reproducible example

Just run `npx create-expo-module@canary` and answer prompts, it errors out after entering email.

**Comment by mrmuke** [comment]
+1

**Comment by brentvatne** [comment]
i'm not able to reproduce this on the latest version of create-expo-module, published for sdk 52 release today:

```
npx create-expo-module@latest
```

the canary version is quite out of date, we'll publish a new canary soon

**Comment by mrmuke** [comment]
This still occurs in the latest version of create-expo-module. This is the faulty line of code that when i modify in the newest package ```/create-expo-module/build/utils/github.js:45
    if (json.data.total_count > 0) {
``` for expo sdk 52
