### ISSUE TITLE
Error building ExpoKit Android: java.util.zip.ZipException: duplicate entry: com/facebook/infer/annotation/Assertions.class

### ISSUE THREAD

**Issue by terribleben** [expo/expo#317]
## Description

Error at compile in Android after detached to Expokit.

## Expected Behavior

It should compile.

## Observed Behavior

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/facebook/infer/annotation/Assertions.class
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: empty
* `npm ls react-native`: react-native@0.45.1  invalid
* `npm ls expo`: expo@18.0.4
* `node -v`: v7.10.0
* `npm -v`: 5.0.1
* `yarn --version`: 0.19.1
* `watchman version`: 4.7.0

Also specify:

1. Operating system: Mac OSX 10.12.5
2. Phone/emulator/simulator & version: Android Studio 2.3.3

## Reproducible Demo

`create-react-native-app demoapp`
`yarn run eject`
`react-native run-android`
And it should give:
```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/facebook/infer/annotation/Assertions.class
```

Thanks!

**Comment by jesseruder** [comment]
Should be fixed now. Anyone hitting the issue will have to re-detach to get the new version of the Android code.

**Comment by alexwale** [comment]
hi,can somebody told me how to fix it?
thanks!
