### ISSUE TITLE
[expo-notifications] Missing title

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo#31709]
### Minimal reproducible example

(https://github.com/expo/expo/issues/31709)

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Send notifications via `firebase-admin` not working as expected:

```javascript
const message: Message = {
  android: {
    notification: {
      channelId: NOTIFICATION_CHANNEL.DEFAULT,
    },
  },
  data: {
    title: 'TODO',
    message: 'TODO',
    screen: 'TODO',
    screenParams: JSON.stringify({ id }),
  },
  token: tokenInfo.token.value,
} as const;

await messaging().send(message, false);
````

In this case the notification arrives with no title. At the same time setting `title` in `android.notification` property make it happen. The documentation suggest to prefer setting `title` via `data` object to have a Message of type `Data` (not `Notification`).

The title was working fine before latest version bump in `expo-notifications`.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.0 - /private/var/folders/5l/mcrlgr6j0q17zlq54pkfblyw0000gn/T/xfs-c2d26aaf/node
      Yarn: 4.1.1 - /private/var/folders/5l/mcrlgr6j0q17zlq54pkfblyw0000gn/T/xfs-c2d26aaf/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
      Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 23, 31, 32, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-23 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-30 | AOSP ATD ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-33-ext4 | Google Play ARM 64 v8a, android-33 | Google APIs ATD ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 11.0.14 => 11.0.14 
      expo: 51.0.34 => 51.0.34 
      expo-router: 3.5.23 => 3.5.23 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: ^0.75.3 => 0.75.3 
      react-native-web: 0.19.11 => 0.19.11 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@1.24.0 - expected version: 1.23.1
  @react-native-community/datetimepicker@8.2.0 - expected version: 8.0.1
  @react-native-community/netinfo@11.3.2 - expected version: 11.3.1
  @shopify/flash-list@1.7.1 - expected version: 1.6.4
  react@18.3.1 - expected version: 18.2.0
  react-dom@18.3.1 - expected version: 18.2.0
  react-native-safe-area-context@4.10.9 - expected version: 4.10.5
  react-native-svg@15.3.0 - expected version: 15.2.0
  react-native-webview@13.10.5 - expected version: 13.8.6
  typescript@5.5.2 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

**Comment by RohovDmytro** [comment]
Also, here are the docs that mention the difference between two types of messages and what implies that title should be present if not specified in the `notification` object.

https://github.com/expo/expo/blob/main/docs/pages/push-notifications/sending-notifications-custom.mdx

**Comment by vonovak** [comment]
Hello and thanks for reporting,
when sending messages via fcm, please follow their API docs: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#resource:-message

That should resolve the title issue.

Thank you 🙂

**Comment by RohovDmytro** [comment]
@vonovak, that does work. Then the question is about this part of expo documentation:

https://github.com/expo/expo/blob/main/docs/pages/push-notifications/sending-notifications-custom.mdx

If I will use the `notification.title` property as seen in Firebase docs, I will send a Notification type of Message, but I do want to send a Notification type of Message. Hope that makes sense :) At least, the docs suggest that. The docs use the deprecated FCM API, so maybe it is simple no more relevant.

**Comment by vonovak** [comment]
Hello,

> If I will use the notification.title property as seen in Firebase docs, I will send a Notification type of Message, but I do want to send a Notification type of Message.

I'm afraid I don't follow what you're saying.

Our docs in this case don't correspond to firebase's docs, so our docs are wrong afaict.

**Comment by RohovDmytro** [comment]
I'm also not following the relation between actions, title, FCM & expo. I will make sense of it an will update the issue.

**Comment by vonovak** [comment]
I see the docs issue can be tracked here https://github.com/expo/expo/issues/31724

Thank you
