### ISSUE TITLE
spown cmd enoent error

### ISSUE THREAD

**Issue by roopeshm456** [expo/expo#3171]
![test](https://user-images.githubusercontent.com/46523847/50894925-92778880-142a-11e9-9715-6ab3181e3850.png)

I followed the official doc to create app.
`https://facebook.github.io/react-native/docs/getting-started`
but while running `npm start ` it results in the _spown cmd enoent error_
expo version is 2.6.14

error lo
https://drive.google.com/file/d/1MoK6PVmQD6NIyLfaU64eJ5rsidYmEKcs/view?usp=sharing

**Comment by tsapeta** [comment]
I believe this issue has already been resolved in the new versions, so I'm closing it but feel free to open a new issue with updated details if I'm wrong 🙂
