### ISSUE TITLE
[docs] [expo-notification] Missing category id information for Android

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo#31711]
### Summary

The documentation missed a clear information how to set category for a notification for Android. There is information about `categoryIdentifier`, but some places mention that it is only for iOS.

Specifically, I am using `firebase-admin` to send notification and finding it very hard to identify how to properly pass category information via `messages().send()` call and docs does not suggest anything I can use.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/notifications/

**Comment by RohovDmytro** [comment]
A good place to mention setting the category via firebase-admin might be this part of the docs:

https://github.com/expo/expo/blob/main/docs/pages/push-notifications/sending-notifications-custom.mdx

**Comment by RohovDmytro** [comment]
I good place to mention setting category inforomation while using `firebase-admin` would be:

https://github.com/expo/expo/blob/main/docs/pages/push-notifications/sending-notifications-custom.mdx

There is `categoryId` field, but as mentioned [here](https://github.com/expo/expo/issues/31710) this does not work as expected.

**Comment by RohovDmytro** [comment]
Also, this part appears to have a broken link:

> The examples in the previous section provide the bare minimum notification requests. You may have to send category identifiers, custom sounds, icons, custom key-value pairs, and so on. [expo-notifications documents](https://github.com/expo/expo/blob/main/versions/latest/sdk/notifications/#manage-notification-categories-interactive-notifications) all the fields it supports, and below are the example payloads Expo sends in its notifications service:

**Comment by RohovDmytro** [comment]
Specifically, this:

> A string to associate as the ID of this category. You will pass this string in as the categoryIdentifier in your [NotificationContent](https://docs.expo.dev/versions/latest/sdk/notifications/#notificationcontent) to associate a notification with this category.

The `categoryIdentifier` is mentioned, but in other places it is described as ios-specific property while [setNotificationCategoryAsync](https://docs.expo.dev/versions/latest/sdk/notifications/#setnotificationcategoryasyncidentifier-actions-options) should work both for iOS and Android.

**Comment by RohovDmytro** [comment]
I ended up sending Data type Message via FCM, listening to that incoming data on the client and firing up the local notification with a category id. That does work and is very nice.

<img width="781" alt="image" src="https://github.com/user-attachments/assets/d1c39168-abcb-426a-8616-bdd6706af8a5">

And tbh I'm not even sure that Notification type of Message should display notification actions by design. Maybe worth mentioning for Notifications for Dummies part of the docs! :)

**Comment by vonovak** [comment]
> tbh I'm not even sure that Notification type of Message should display notification actions by design

can you please expand on that? I don't follow what you're trying to say.

**Comment by RohovDmytro** [comment]
`Message` send via `FCM` could be of two types: 
- (Message, Notification)
- (Message, Data)

Also, there two two different types in regards of 
- Local Notification
- Remote Notification

It took me a while to understand how to display actions.

What works:
(Message,Data) => Local Notification => Notification (in UI) with an action.

I did not wrap my head around a variant of sending of (Message, Notification) that will show an action :)

And what I am not sure if this even possible:
FCM => (Message, Notification) => Notification (in UI) with an action

I can see a possible confusions with all the terms around, but I hope that makes more sense :)

**Comment by RohovDmytro** [comment]
I can phrase it as a question:

How to send an FCM Message of type Notification to get actions working and if that even possible? It might just haven't found a way to make it work.

**Comment by vonovak** [comment]
> I can phrase it as a question:
> 
> 
> 
> How to send FCM Message of type Notification to get actions working and if that even possible? It might just haven't found a way to make it work.

That's not possible - the actions are passed in the 'data' part.

**Comment by RohovDmytro** [comment]
> That's not possible - the actions are passed in the 'data' part.

I can make notes that its not possible. One thing I feel worth mentioning is that Notification type _can_ hold `data` property, as you can read here:

> Notification messages with optional data payload
Both programmatically or via the Firebase console, you can send notification messages that contain an optional payload of custom key-value pairs. In the [Notifications composer](https://console.firebase.google.com/project/_/notification), use the Custom data fields in Advanced options.

App behavior when receiving messages that include both notification and data payloads depends on whether the app is in the background or the foreground—essentially, whether or not it is active at the time of receipt.

When in the background, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification.
When in the foreground, your app receives a message object with both payloads available.

https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by vonovak** [comment]
Hello, I'm going to close this in favor of https://github.com/expo/expo/pull/26931

[This comment](https://github.com/expo/expo/issues/31911#issuecomment-2530524790) explains a bit how you can pass the category id.

Thank you!
