### ISSUE TITLE
Can't suppress LogBox warnings

### ISSUE THREAD

**Issue by cseelus** [expo/expo#31746]
### Minimal reproducible example

https://github.com/EvanBacon/expo-router-layouts-example

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

As of `victory@36.4.0`, React Native apps (on both iOS and Android) will warn about require cycles.

Their[ recommended approach](https://github.com/FormidableLabs/victory/issues/2230) for now is to add …

```js
LogBox.ignoreLogs([
  "Require cycle: node_modules/victory",
]);
```

… which I did in the Expo Router sample project (in `app/_layout.js`). 

Unfortunately this isn't picked up and the warnings are still shown. Also tried using a custom entry that imports `expo-router/entry`, which doesn't work either.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 18.20.4 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2024.09.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.13
      expo: ~51.0.34 => 51.0.34
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 12.5.0
      expo-cli: 6.3.10
    Expo Workflow: bare
```

**Comment by marklawlor** [comment]
Creating a custom entry point with the `LogBox.ignoreLogs` should work, however a reproduction was not provided so I cannot verify how you performed this step.

Additionally, `victory` is deprecated for React Native, and it is recommended that `victory-native` is used instead (which does not have the dependency issue causing these logs).

I'm going to close this issue as we need a complete reproduction repro
