### ISSUE TITLE
Unable to resolve "./Amplitude" from "node_modules\expo\build\Expo.js"

### ISSUE THREAD

**Issue by JMPiechowiak** [expo/expo#3175]
### Environment
  Expo CLI 2.6.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

App target: Android

### Steps to Reproduce

When using command "expo start --localhost --android" in git bash terminal to run my app on android device.
I got error:
Unable to resolve "./Amplitude" from "node_modules\expo\build\Expo.js"

And my phone is displaying: "The development server returned response error code 500"

What I did is:
1. Updated my Expo app on android device.
2. Removed package-lock.json and node_modules
3. Updated package.json with "npm-check-updates", then "ncu -u" and finally "npm install"
4. Removed npm cache.

### Expected Behavior

Application should just run like it did couple days ago with no errors or problems. I didn't change the code whatsoever.

### Actual Behavior

git bash runs development server, QR code appears and then:
" Your app is running at exp://127.0.0.1:19000
Logs for your project will appear below. Press Ctrl+C to exit.

Unable to resolve "./Amplitude" from "node_modules\expo\build\Expo.js"
"

**Comment by liangguohun** [comment]
too many questions i alse get and can't fix

**Comment by tsapeta** [comment]
Hey guys, have you tried clearing metro bundler cache? Please try `expo start -c` 😉

**Comment by liangguohun** [comment]
yes it the same to,
Unable to resolve "expo-app-auth" from "node_modules/expo/build/Expo.js"
i try the new version and old version, if android is ok, or ios is ok just one can't do well,
this problem is on mac for iphone.

**Comment by liangguohun** [comment]
@tsapeta  o! it work now use this command,i evel try this command too, maybe,i try too much version ,now i use the version 31,thanks！

**Comment by tsapeta** [comment]
@JMPiechowiak Some people were having the same problem with Amplitude and clearing cache fixed it, see here: https://github.com/expo/expo/issues/3030#issuecomment-451558185

This new issue doesn't seem to be related to Expo. Can you post your `package.json` here?

**Comment by JMPiechowiak** [comment]
Alright. I manage to fix this as well by using:
> npm i schedule@0.4.0 --save-dev

Here is my package.json anyway:

> {
>   "name": "empty-project-template",
>   "main": "node_modules/expo/AppEntry.js",
>   "private": true,
>   "scripts": {
>     "start": "expo start",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "eject": "expo eject"
>   },
>   "dependencies": {
>     "axios": "^0.18.0",
>     "expo": "^32.0.0",
>     "immutable": "^4.0.0-rc.12",
>     "react": "16.7.0",
>     "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
>     "react-native-autocomplete-input": "^3.6.0",
>     "react-native-calendars": "^1.21.0",
>     "react-native-dialog-input": "^1.0.6",
>     "react-native-maps": "^0.22.1",
>     "react-native-modal-datetime-picker": "^6.0.0",
>     "react-native-router-flux": "latest",
>     "react-native-simple-time-picker": "^0.2.0",
>     "react-redux": "^6.0.0",
>     "redux": "^4.0.1",
>     "redux-axios-middleware": "^4.0.0"
>   },
>   "devDependencies": {
>     "babel-preset-expo": "^5.0.0",
>     "schedule": "^0.4.0"
>   }
> }
> 

But now everything works like before. Thanks for help. 
Can be closed.

**Comment by liangguohun** [comment]
**don't close so quick！**
npm i schedule@0.4.0 --save-dev when i use this command get a new question 
Unhandled JS Exception: Can't find variable:require    ..... expo/AppEntry.bundle?  
...
global code
AppEntry.bundle?..AssetFiles.js:451:3

**Comment by liangguohun** [comment]
Unhandled JS Exception: Can't find variable: require (http://192.168.1.10:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=g%3A%5CshareApp%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles.js:410)

global code
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=g%3A%5CshareApp%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles.js:451:3

**Comment by brentvatne** [comment]
```
rm -rf node_modules
rm yarn.lock
rm package-lock.json
yarn
expo start -c
```

**Comment by liangguohun** [comment]
i try many times

**Comment by brentvatne** [comment]
```
expo init
```

then copy your code over to the new project.

sorry i don't know what could be wrong with your project, the fact that `require` cannot be found means you've configured something very wrong. best to just copy your code into a new project

**Comment by EvanBacon** [comment]
The Amplitude issue appears to be resolved.

**Comment by MohammedFadin** [comment]
> The Amplitude issue appears to be resolved.

Resolved how? by moving the code to a new project?  

I'm having the same problem as @liangguohun liangguohun

**Comment by davehax** [comment]
> ```
> rm -rf node_modules
> rm yarn.lock
> rm package-lock.json
> yarn
> expo start -c
> ```

This resolved the issue for me

**Comment by ckollars** [comment]
> ```
> rm -rf node_modules
> rm yarn.lock
> rm package-lock.json
> yarn
> expo start -c
> ```

I got here from searching on this error `Unable to resolve "react-native-maps" from "node_modules/expo/build/Expo.js"`. I wasn't removing `package-lock.json` but once I did it resolved my issue.

**Comment by lysontrung** [comment]
@ckollars 
I got same issues
how i can resolve it ???

**Comment by lysontrung** [comment]
@ckollars 
you saved my day!
thanks

**Comment by Yohanson555** [comment]
> 
> 
> Hey guys, have you tried clearing metro bundler cache? Please try `expo start -c` 😉

Have this issue after updating expo to 32.0.0 and clearing cache works for me to resolve it. Thanks.

**Comment by actuallymentor** [comment]
> > Hey guys, have you tried clearing metro bundler cache? Please try `expo start -c` 😉
> 
> Have this issue after updating expo to 32.0.0 and clearing cache works for me to resolve it. Thanks.

I'm having this issue while updating to 32.0.6. Clearing cache (and deleting package-lock) did not solve the issue.

Error:

`Unable to resolve "schedule/tracking" from "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js"`
