### ISSUE TITLE
File Image size increases while uploading to firebase using XMLHttpRequest

### ISSUE THREAD

**Issue by RishavKumar-3796** [expo/expo#3177]
I am facing a very strange issue that my Image size increases while uploading to firebase. I have logged the file size before uploading, it is showing the same size but after uploading the file size gets increased. Also the image is not corrupted. Please help..

**Uploading to firebase code :**

```js
async uploadImageAsync(uri, passedParameter, ItemName) {
    const blob = await new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.onload = function() {
        resolve(xhr.response);
      };
      xhr.onerror = function(e) {
        console.log(e);
        reject(new TypeError("Network request failed"));
      };
      xhr.responseType = "blob";
      xhr.open("GET", uri, true);
      xhr.send(null);
    });

    const ref = firebase
      .storage()
      .ref()
      .child("CategoryDescription" + "/" + passedParameter + "/" + ItemName);

    const snapshot = await ref.put(blob);

    blob.close();
    const downloadUrl = await snapshot.ref.getDownloadURL();

    return downloadUrl;
  }
```

**Pick Image code**

```js
async _pickImage() {
    const { CAMERA, CAMERA_ROLL } = Permissions;
    const permissions = {
      [CAMERA]: await Permissions.askAsync(CAMERA),
      [CAMERA_ROLL]: await Permissions.askAsync(CAMERA_ROLL)
    };

    if (
      permissions[CAMERA].status === "granted" &&
      permissions[CAMERA_ROLL].status === "granted"
    ) {
      var pickerResult = await ImagePicker.launchImageLibraryAsync({
        quality: 0.1
      });

      if (!pickerResult.cancelled) {
        console.log(pickerResult);
        this.setState({
          itemImage: pickerResult.uri
        });
```

**On button pressed code**

```js
handleConfirmAddItems = () => {
    var passedParameter = this.params.item.key;
    const { ItemName, ItemPrice, ItemDesc, ItemWeight, itemImage } = this.state;


      {
        itemImage !== "" &&
          this._handleImagePicked(itemImage, passedParameter, ItemName);
      }

      writeUrlToDB(
        itemImage,
        passedParameter,
        ItemName,
        ItemDesc,
        ItemPrice,
        ItemWeight
      );
    }
  };
```

**handle image picked**

```js
async _handleImagePicked(itemImage, passedParameter, ItemName) {
    try {
      const uploadUrl = await this.uploadImageAsync(
        itemImage,
        passedParameter,
        ItemName
      );
      this.setState({ itemImage: uploadUrl });
      console.log("itemIma", uploadUrl);
    } catch (e) {
      console.log(e);
      alert("Upload failed, sorry :(");
    }
  }
```

**Comment by RishavKumar-3796** [comment]
@brentvatne

**Comment by RishavKumar-3796** [comment]
@EvanBacon 
Looks like expo team doesn't cares : (

**Comment by bberak** [comment]
I'm facing a similar issue with S3 - have you had any luck figuring this one ou @RishavKumar-3796 ?

**Comment by esamelson** [comment]
Hi @RishavKumar-3796 - please don't tag individuals on the Expo team, it wastes our time and doesn't help us respond to you any more quickly.

We may be able to help out here if someone provides [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) in the form of a [snack](https://snack.expo.io). Thanks!

**Comment by Caskia** [comment]
Hey @esamelson ,  
I met the same problem, the steps to reproduce are as follows.
1. get file info, current file's size is 100k
```
var file = await FileSystem.getInfoAsync(uri, { md5: true, size: true });
```
2. compress file, current expo api show size is 40k
```
var file = await ImageManipulator.manipulateAsync(uri, [{ resize: { width: 300, height: 300} }], { compress: 0.48 })
```
3. get file info, current expo api show size is 40k
```
var file = await FileSystem.getInfoAsync(uri, { md5: true, size: true });
```
4. upload file, current actual file size is 300k from the progress info.
```
var formData = new FormData(); 
        var fileObj: any = {
            uri: "file:///localpath",
            name: "file",
            type: "image/png"
        }
        formData.append('file', fileObj);
        await axios.post("<upload url>", formData, {
            headers: {
                Authorization
            },
            onUploadProgress(res) {
                if (res.lengthComputable) {
                    onProgress && onProgress({
                        loaded: res.loaded,
                        total: res.total,
                        progress: (res.loaded / res.total)
                    })
                }
            }
        });

```

I'm ensure using the right file path, but the file is bigger than call expo api gets(FileSystem.getInfoAsync)

**Comment by scarlac** [comment]
I can reproduce with a Snack and a 9-line nodejs/express server. 

**Snack:**
https://snack.expo.io/@scarlac/file-upload-size-21mb-with-asset

**Upload server:**
https://gist.github.com/scarlac/b8fa1d5d1f2bbdc2dfc0591e6c1efaae

**My findings:**
I am testing with an ~8.8 MB original JPEG that gets uploaded as ~21 MB. The photo was taken from a DSLR and imported into my library a long time ago. The increase in size roughly equates to re-saving the original JPEG with 100% quality.
After a few tries, you can remove the "assets" folder, and the app reloads. It then shrinks to ~8.8 MB again. Presence of the assets do not seem to directly affect the file upload size but instead seem to affect something underlying. As I do not know how Expo works, I suspect this is a combination of iOS behavior and Expo. It's likely that photos are stored as HEIF (in newer iOS version) and exported as 100% JPEGs if you have "optimize iphone storage" enabled in your photos settings. After using the photo several times the original gets downloaded, cached, and served as the original.

I can upload the (dog) photo somewhere if you wish to test. It shouldn't matter which one you use as long as you know what the original size is.

**Comment by MahmoudHemaid** [comment]
@bberak any updates about your issue i'm facing the same issue on IOS.

**Comment by MahmoudMH** [comment]
Same problem here! 

I found the size of the uploaded image before sending the request and it was 300Kb.
I logged the request info in the server and I found the request body size 2Mb.

Another Example below!
![Image](https://serving.photos.photobox.com/20180325a0bcc40998f2ce1d8a0902fb3d47b72fbe58cd1236a4f30fdb180102950ebe25.jpg)
![Image](https://serving.photos.photobox.com/15063752005d12381a150fe51b76e06e36e0d5893984a59d5e5cb72a163d0317b2249134.jpg)

**Comment by robennals** [comment]
I was able to work around this issue by getting the base64 encoded version (which appears to be the correct size) and then sending that to a custom cloud function that uploads that base64 code to firebase (since storing base64 requires binary data support that isn't present in expo).

A fairly hacky work around, but it worked.

**Comment by bberak** [comment]
Hi @robennals,

Were you able to get the base64 string of your image without completely locking the up the UI thread?

**Comment by MahmoudMH** [comment]
I agreed with you @robennals, I did this job yesterday.
I got the base64 and sent it in AWS direct using signed URL, then the uploaded image size is acceptable and it's around the buffer size.

That's how I tried to avoid the large size in IOS 👍

**Comment by peter-axomic** [comment]
I had the same issue with CameraRoll uploading an image using the ```assets-library://``` uri both through fetch and XMLHttpRequest. It would insert lots of EXIF data making the image blow up in size

Here is an example of a 107 byte tiny JPG that turns into 4950 bytes after upload
https://github.com/mathiasbynens/small/blob/355bdb20339e629e0873e4faec392508624dbcf0/jpeg.jpg

The solution for me was to

1) swap to using MediaLibrary instead of CameraRoll which returns the asset id such as ```B84E8479-475C-4727-A4A4-B77AA9980897/L0/001```
2) calling ```MediaLibrary.getAssetInfoAsync(id)``` to get ```localUri``` which starts with ```file://```
3) Using ```localUri``` for the fetch or XMLHttpRequest instead of ```uri```

If you're using ImagePicker or CameraRoll in expo 33 you might get URIs of the form ```ph://B84E8479-475C-4727-A4A4-B77AA9980897/L0/001``` in which case you could strip the ```ph://``` off to get the asset id and then call ```MediaLibrary.getAssetInfoAsync(id)```

**Comment by snooplsm** [comment]
Only workaround I found was this jawn:

const urlToBlob = url =>
  new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.onerror = reject;
    xhr.onreadystatechange = () => {
      if (xhr.readyState === 4) {
        resolve(xhr.response);
      }
    };
    xhr.open("GET", url);
    xhr.responseType = "blob"; // convert type
    xhr.send();
  });

**Comment by bberak** [comment]
Hi @snooplsm 

Thanks for your snippet. Can you elaborate a bit on your workflow? How are you using the **urlToBlob** function to upload an image to your backend?

**Comment by snooplsm** [comment]
Here is a snippet for use with amazon s3 (amplify)

isSignedIn()
      .then(user => {
        data.user = user;
        console.log("we have user");
        return ImageManipulator.manipulateAsync(file.url, null, {
          compress: 0.3
        });
      })
      .then(fc => {
        data.fc = fc;
        return urlToBlob(fc.uri);
      })
      .then(blob => {
        const time = moment().format("YYYY_MM_DD_HH_mm_ss_SSS");
        const key = `${data.user.id}/${time}.jpg`;
        console.log("blob key", key);
        const metaData = Object.assign({
          "User-Id": data.user.id,
          "File-Name": data.fc.uri,
          "Operating-System": Platform.OS,
          Device: Constants.deviceName,
          width: (data.fc.width ?? -1).toString(),
          height: (data.fc.height ?? -1).toString(),
          duration: (file.duration ?? -1).toString(),
          lat: (file.lat ?? 0.0).toString(),
          lng: (file.lng ?? 0.0).toString(),
          timeofimage: file.timeofimage ?? "-1"
        });
        data.size = blob.size;
        data.meta = metaData;
        Storage.put(key, blob, {
          customPrefix: {
            public: "uploads/"
          },
          level: "public",
          metadata: metaData,
          contentType: "image/jpeg"
        })

**Comment by bberak** [comment]
Thanks @snooplsm much appreciated, I'll give it a shot on Monday. Cheers!

**Comment by bberak** [comment]
Hi @snooplsm,

It looks like my image still increases in size about **3x** after I call `urlToBlob`. What version of the Expo SDK are you using? Is your app detached (ExpoKit) or managed? Is your `fc.uri` a local uri (starts with `file://`) or remote?

**Comment by todorone** [comment]
The problem still exists almost a year later.
On Android everything's work great.
On iOS uploaded file of image approx 3x times bigger than the size of the local file that is reported by `FileSystem.getInfoAsync`.
The issue is easily reproduced, for example by https://github.com/expo/expo/issues/3177#issuecomment-488356920
@brentvatne @EvanBacon @esamelson Can You please remove `status: needs more info` tag to raise chances of it to get more traction in future?

**Comment by mixa9269** [comment]
I'm facing a similar issue, but without Expo.
"react-native": "0.60.5"

**Comment by jasonmerino** [comment]
I was forced to abandon Expo because of this issue that had been cropping up. I was able to get around it with a standard React Native project and the addition of [react-native-firebase](https://github.com/invertase/react-native-firebase). I hope that helps anyone who needs to make the jump because of this issue.

**Comment by tareqdayya** [comment]
this problem is not related to expo, it's a well-known bug in RN on iOS for a long time now. I don't use expo, I never have, but i still have the problem on iOS in a RN project i'm currently working on.

**Comment by foloinfo** [comment]
@peter-axomic Thank you so much for this solution!

It actually solved the other problem I had which I couldn't upload any video file with Expo because `MediaLibrary.getAssetsAsync` returns uri like `assets-library://` and the file was somehow converted to image when uploading. So I was using `MediaPicker` as a workaround.

Using `localUri` returned by `MediaLibrary.getAssetInfoAsync` solved this  problem.
It seems like this solution is available since expo SDK 36.

This is the PR in which lets you use `localUri` for video files.
https://github.com/expo/expo/commit/8569e4233adb19ad94364df0d38b98a665f2b6c6

**Comment by GaoYuJian** [comment]
use rn-fetch-blob 
reasson: https://github.com/facebook/react-native/issues/27099#issuecomment-602016225

**Comment by ganzik** [comment]
https://stackoverflow.com/questions/56682109/react-native-through-upload-image-on-s3-bucket-using-aws-sdk

1. add node-module 'base64-arraybuffer'
```sh
yarn add base64-arraybuffer
```

2. 
```js
import {decode} from 'base64-arraybuffer';
import RNFS from 'react-native-fs';

 const base64 = await RNFS.readFile(filePath, 'base64');
  // console.log('base64', base64); //get base64 data

  const arrayBuffer = decode(base64);
  //console.log('arrayBuffer', arrayBuffer.byteLength); // don't increase file size

 await Storage.put(uploadPath, arrayBuffer, {
    progressCallback(progress) {
      image.progress = (progress.loaded / progress.total) * 100;
      // dispatch or setState image progress
    },
    contentType: mime,
  })
```

**Comment by NickRance** [comment]
> @peter-axomic Thank you so much for [this solution](https://github.com/expo/expo/issues/3177#issuecomment-510096711)!
> 
> It actually solved the other problem I had which I couldn't upload any video file with Expo because `MediaLibrary.getAssetsAsync` returns uri like `assets-library://` and the file was somehow converted to image when uploading. So I was using `MediaPicker` as a workaround.
> 
> Using `localUri` returned by `MediaLibrary.getAssetInfoAsync` solved this problem.
> It seems like this solution is available since expo SDK 36.
> 
> This is the PR in which lets you use `localUri` for video files.
> [8569e42](https://github.com/expo/expo/commit/8569e4233adb19ad94364df0d38b98a665f2b6c6)

Unfortunately the [solution you referenced](https://github.com/expo/expo/issues/3177#issuecomment-510096711) didn't work for me on iOS13 and SDK 39. Eager to get this solved!

**Comment by brentvatne** [comment]
here's a workaround you can use for the react-native bug, by using expo-file-system:

https://github.com/facebook/react-native/issues/27099#issuecomment-685992262

**Comment by VictorioMolina** [comment]
This works for me:

```javascript
/* eslint-disable max-len */
import { Platform } from "react-native";
import * as FileSystem from "expo-file-system";

/**
 * Builds a blob with the given uri.
 *
 * @memberof module:Global/Functions
 * @function uriToBlob
 * @param {string} uri - The URL.
 * @returns {Promise<Blob>}
 *   A promise that fulfills with a blob (group of bytes that holds
 *   the data stored in a file).
 * @example
 * (async () => {
 *   const blob = await uriToBlob(imageUri);
 *   console.log(blob._data.blobId);
 * })();
 */
export default async (uri) => {
  let blob = await new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();

    /**
     * Handles the XMLHttpsRequest response.
     */
    xhr.onload = function () {
      resolve(xhr.response);
    };

    /**
     * Handles XMLHttpRequest errors.
     *
     * @throws {TypeError} Network request error.
     */
    xhr.onerror = function () {
      reject(new TypeError("Network request failed"));
    };

    xhr.responseType = "blob";
    xhr.open("GET", uri, true);
    xhr.send(null);
  });

  // Fix RN bug when uploading iOS images to the server (reduce image size)
  if (Platform.OS === "ios" && blob.type === "image/jpeg") {
    const fileName = uri.split("/").pop();

    const newUri =
      `${FileSystem.documentDirectory}resumableUploadManager-${fileName}.toupload`;

    await FileSystem.copyAsync({ from: uri, to: newUri });

    blob =
      new Blob([await (await fetch(newUri)).blob()], { type: blob.type });
  }

  return blob;
};
```

Also, make sure to limit Firebase storage max image sizes, like:

```javascript
match /images/{userId}/{imageId} {
  allow read: if false; // only via signed URL
  allow create: if isSignedIn() && hasValidFormat("image/jpeg") && lessThanNMegabytes(2);
  allow delete: if false;
  allow update: if false;
}
```
