### ISSUE TITLE
Error: Cannot find module '../lightningcss.win32-x64-msvc.node'

### ISSUE THREAD

**Issue by angelopedroso** [expo/expo#31775]
### Minimal reproducible example

any expo project

### What platform(s) does this occur on?

Android, iOS, Web

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

After I reset my PC, all expo projects is showing the following error:

```
Error: Cannot find module '../lightningcss.win32-x64-msvc.node'
Require stack:
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\node_modules\lightningcss\node\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\dist\css-to-rn\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\dist\metro\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\nativewind\dist\metro\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\metro.config.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\import-fresh\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\loaders.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\createExplorer.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\metro-config\src\loadConfig.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\metro-config\src\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\server\metro\instantiateMetro.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\server\metro\MetroBundlerDevServer.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\server\DevServerManager.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\startAsync.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\bin\cli
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\expo\bin\cli
Error: Cannot find module '../lightningcss.win32-x64-msvc.node'
Require stack:
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\node_modules\lightningcss\node\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\dist\css-to-rn\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\dist\metro\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\nativewind\dist\metro\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\metro.config.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\import-fresh\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\loaders.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\createExplorer.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\metro-config\src\loadConfig.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\metro-config\src\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\server\metro\instantiateMetro.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\server\metro\MetroBundlerDevServer.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\server\DevServerManager.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\startAsync.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\src\start\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\@expo\cli\build\bin\cli
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\expo\bin\cli
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\node_modules\lightningcss\node\index.js:21:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
```

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10300.40.2321.11567975
    npmPackages:
      expo: ^51.0.0 => 51.0.34
      expo-router: ~3.5.9 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Running 14 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✖ Check for issues with metro config
Unexpected error while running 'Check for issues with metro config' check:
Error: Cannot find module '../lightningcss.win32-x64-msvc.node'
Require stack:
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\node_modules\lightningcss\node\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\dist\css-to-rn\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\react-native-css-interop\dist\metro\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\nativewind\dist\metro\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\metro.config.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\import-fresh\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\loaders.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\createExplorer.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\cosmiconfig\dist\index.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\metro-config\src\loadConfig.js
- C:\Users\Rei\Documents\projects\@PAGSEGURO\a\my-app\node_modules\metro-config\src\index.js
- C:\Users\Rei\AppData\Local\npm-cache\_npx\89957a0324271eeb\node_modules\expo-doctor\build\index.js
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  react-native-reanimated@3.10.0 - expected version: ~3.10.1
  react-native-safe-area-context@4.10.1 - expected version: 4.10.5
```

**Comment by angelopedroso** [comment]
solved after install Microsoft redistributable package

**Comment by tanmay-bhatgare** [comment]
> solved after install Microsoft redistributable package
@angelopedroso Please can you help me with this I stuck on same issue where I initialize nativewind but got this error. Thank you!

**Comment by tanmay-bhatgare** [comment]
> @tanmay-bhatgare bro did you solved it ? if not you can visit this link https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download the version which is compatible with your laptop for me it was 64bit just download it and then use this command in terminal rm -rf node_modules package-lock.json and reinstall them by npm install and then try running your code. for me this is how it worked

Thanks for the help Salman but lucky and silly of me I unknowingly downloaded `node(ia32) `instead of `node(x64)` so that's why it wasn't able to locate `lightingcssx64` but I downloaded the the corrected version and everything went flawlessly. Once again thank you.

**Comment by leofrs** [comment]
@Salman-Khan9 I had the same problem and I fixed it with your tip. Thanks bro!

**Comment by timothy2462** [comment]
Ihad the same problem and followed this tip.
It worked for me like magic 
Thanks to you guys for sharing this

**Comment by mbramani** [comment]
> [@tanmay-bhatgare](https://github.com/tanmay-bhatgare) bro did you solved it ? if not you can visit this link https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download the version which is compatible with your laptop for me it was 64bit just download it and then use this command in terminal rm -rf node_modules package-lock.json and reinstall them by npm install and then try running your code. for me this is how it worked

@Salman-Khan9 Thank you! I was able to solve it based on your suggestion. For me, this issue occurred when using Tailwind CSS 4 with Next.js 15 Canary.

**Comment by rutikwankhade** [comment]
> [@tanmay-bhatgare](https://github.com/tanmay-bhatgare) bro did you solved it ? if not you can visit this link https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download the version which is compatible with your laptop for me it was 64bit just download it and then use this command in terminal rm -rf node_modules package-lock.json and reinstall them by npm install and then try running your code. for me this is how it worked

Thank you. I was able to fic this issue while setting up a new React + vite application. as cra is deprecated i was trying to migrate and faced this issue. (i recently reset my laptop and uninstallled all programs)

**Comment by Tosinjoseph** [comment]
It worked like the magic it is. Thanks for this

**Comment by Ndubuisi-AndeOrji** [comment]
> [@tanmay-bhatgare](https://github.com/tanmay-bhatgare) bro did you solved it ? if not you can visit this link https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download the version which is compatible with your laptop for me it was 64bit just download it and then use this command in terminal rm -rf node_modules package-lock.json and reinstall them by npm install and then try running your code. for me this is how it worked

Thanks bro for this. It also worked like magic for me too.

**Comment by IdrisKulubi** [comment]
The issue was solved after instaling Microsoft redistributable package. download from here https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

check this issue for reference
https://github.com/expo/expo/issues/31775

**Comment by mukasha789** [comment]
Thanks community solved the issus after donwloading the redis for visual studio code for my **X64** system from this source
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by jukahiga** [comment]
@Salman-Khan9 thanks for this solution

**Comment by shivamsinghal160** [comment]
> [@tanmay-bhatgare](https://github.com/tanmay-bhatgare) bro did you solved it ? if not you can visit this link https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download the version which is compatible with your laptop for me it was 64bit just download it and then use this command in terminal rm -rf node_modules package-lock.json and reinstall them by npm install and then try running your code. for me this is how it worked

Thanks Bro its Solved Now

**Comment by Emmy-delight** [comment]
@tanmay-bhatgare This worked like magic, I have been trying to get it fixed for while. Thank you . Im emmanuel from Nigeria

**Comment by Hap-404** [comment]
> [@tanmay-bhatgare](https://github.com/tanmay-bhatgare) bro did you solved it ? if not you can visit this link https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download the version which is compatible with your laptop for me it was 64bit just download it and then use this command in terminal rm -rf node_modules package-lock.json and reinstall them by npm install and then try running your code. for me this is how it worked

It is solved thank you so much for this !!!

**Comment by daniBagaskara** [comment]
> [@tanmay-bhatgare](https://github.com/tanmay-bhatgare) bro did you solved it ? if not you can visit this link https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and download the version which is compatible with your laptop for me it was 64bit just download it and then use this command in terminal rm -rf node_modules package-lock.json and reinstall them by npm install and then try running your code. for me this is how it worked

Thank you, it work on me

**Comment by MuhammadYaseenAkhtar** [comment]
Thank you so much; it worked now; I'd spent several hours to resolve it; after these steps now working fine; thanks once again 👍

**Comment by Priyansu67** [comment]
Steps I followed:
- Reinstalled `vsredist`.
- Cleaned the node modules.
- Cleared the npm cache.
- Downgraded the Node version.
- Reinstalled everything.

Despite trying all of the above solutions, nothing worked.

Manually installed `lightningcss-win32-x64-msvc` using the command:

```bash
npm i lightningcss-win32-x64-msvc
```

After this, everything worked, as `lightningcss` was not detecting the Win32 x64 system and wasn’t creating the necessary folder in `node_modules` until I installed it manually.

**Comment by hiskuDN** [comment]
Need to have correct node matching your computer arch (x86 or x64) and then install the correct micrsoft redist as well. It should work in that case.

**Comment by nishanbudhathoki2266** [comment]
Manually installing `lightningcss-win32-x64-msvc` worked for me. Hitting this command 👇
`npm i lightningcss-win32-x64-msvc`

**Comment by st4l1nR** [comment]
If nothing above worked, try removing package-lock.json and run 'npm i' it worked for me

**Comment by Tomilola-ng** [comment]
> Steps I followed:
> 
> * Reinstalled `vsredist`.
> * Cleaned the node modules.
> * Cleared the npm cache.
> * Downgraded the Node version.
> * Reinstalled everything.
> 
> Despite trying all of the above solutions, nothing worked.
> 
> Manually installed `lightningcss-win32-x64-msvc` using the command:
> 
> npm i lightningcss-win32-x64-msvc
> After this, everything worked, as `lightningcss` was not detecting the Win32 x64 system and wasn’t creating the necessary folder in `node_modules` until I installed it manually.

This worked for me, God bless you

**Comment by waqar424** [comment]
fix: resolved lightningcss.win32-x64-msvc.node module error

Issue:
❌ Expo project was throwing "Cannot find module '../lightningcss.win32-x64-msvc.node'" error due to missing native dependencies after system reset.

Fix:
✅ Installed latest Microsoft Visual C++ Redistributable for x64 from:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170  
✅ Deleted `node_modules` and `package-lock.json`
✅ Rebooted system to apply redistributable
✅ Reinstalled dependencies with `npm install`
✅ Confirmed working by running `npx expo start --clear`

Everything works perfectly now .
