### ISSUE TITLE
Entry point stopped working suddenly on app

### ISSUE THREAD

**Issue by Dosylia** [expo/expo#31790]
### Minimal reproducible example

https://github.com/Dosylia/URSG_Debug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hi,

My app been working perfectly for a while and lately I was working on the website of project and not app anymore, I cameback and made some changes. When starting app to debug them using "npx expo run:android" I get this :

![{1EE7AD81-5FFA-4504-B5D0-A13B040CFA64}](https://github.com/user-attachments/assets/951b3154-ee2a-45f9-bbc6-e7f71938c2d7)

More about the app : I'm using _layoux.jsx and index.jsx as entry point, and all the main pages are on (tabs)

![{BCB482DC-8868-4995-8952-63677B24ABEF}](https://github.com/user-attachments/assets/7b1e50a4-ebcb-4d60-ac2e-b98fa9e4e372)

I do not get a single error when doing the build and I'm building it from the right folder. 

![{2FD25026-D1F2-405A-B140-85AAFF6C70AD}](https://github.com/user-attachments/assets/f052904c-1f03-403a-90be-652a7c1753e7)

Also did a version of the project with only the _layout.jsx and index.jsx as pages and issue was exactly the same.

I reverted all change I made using "git checkout -- ." and issue was still here so it seems like it's not linked to anything I made and last time using app everything worked perfectly.

I tried changing the entry point of app which did not fixing. I tried pressing the button the app showing and it created an index.tsx which got in conflict with my index.jsx and made the app crash. Tried restarting it only with index.tsx and still got same issue. Then while browsing online, I saw that .env could be issue and followed this guide : https://docs.expo.dev/guides/environment-variables/

It did not fix the issue and I reverted these changes aswell. This all got me pretty confused and clueless so I would really need some help.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.18034.62.2411.12071903
    npmPackages:
      expo: ^51.0.32 => 51.0.32
      expo-router: ^3.5.20 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: ^0.74.4 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare
```

**Comment by Dosylia** [comment]
To help anyone that might this issue in the future after updating to Expo 51. Dotenv was the issue and so why removing it did not fix? 

Two reasons : 
- I had forgotten to remove it from babel.config.js 
- Needed to reset cache.

Have a nice day!

**Comment by itseriqq** [comment]
Dosylia. I really need to thank you.

You helped me solve this issue doing the same as removing dotenv + cleaning babel.config.js

**Comment by SyedMuqeem03** [comment]
@Dosylia Yes, I was also facing the same issue, but as you mentioned, it worked. Thank you for your help! I wanted to ask, how did you manage to add environment variables in your Expo project?

**Comment by ShreyaSingh-14** [comment]
@Dosylia that was a great help, just spent 2 hours wondering if I deleted any file by mistake or loaded a wrong dependency. How can that adding env create such an issue...? Thanks for mentioning it here, it was a great help.
