### ISSUE TITLE
Video component replay

### ISSUE THREAD

**Issue by naorzr** [expo/expo#3179]
### Environment

  Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v11.1.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A254a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.6.14

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/broadsay-28e6cb4b-2460-4531-ac4f-523f249fa4ad.tar.gz

##
target: IOS, Android, Standalone, ExpoKit

Well I'm not sure if it's a bug or should be a feature request, but here goes

### Expected Behavior

I would expect that upon video ending(isLooping set to false) clicking on the play button again would replay the video, instead, it does none.

## steps to reproduce

1.useNativeControls flag set to true
2.play the video to the end
3. press play again

### Reproducible Demo
https://snack.expo.io/@naorz/bugged-vid-replay

**Comment by EvanBacon** [comment]
Have you tried manually resetting the media with 
```js
setStatusAsync({ positionMillis: 0, shouldPlay: true });
```

**Comment by naorzr** [comment]
@EvanBacon Thanks for your response!
I wasn't referring to the play function but rather to the button, the internal implementation of course can be as you stated.
as of now, pressing play after video has ended just causes the video to buffer, which seems odd.
I think that adding this default behavior with a declarative way to control if a video should auto-play on end could serve many.
