### ISSUE TITLE
Using fork of module included in sdk

### ISSUE THREAD

**Issue by GumboFroehn** [expo/expo#318]
Sorry if this question has been answered before. I have a question somewhat related to #155. I need to use a fork of react-native-svg since there are some issues with rendering raster images. Is there any way I can "force" expo to not use the master branch?

**Comment by jesseruder** [comment]
Expo has SVG code bundled into the mobile apps. You can use a fork of the JS side of react-native-svg but you can't use a fork of the native side.

**Comment by dikaiosune** [comment]
Also note that detaching to ExpoKit would allow you to modify the SVG code.
