### ISSUE TITLE
expo run:android Execution failed for task ':expo:compileDebugKotlin'.

### ISSUE THREAD

**Issue by TuvshinbayarO** [expo/expo#31821]
### Minimal reproducible example

https://github.com/TuvshinbayarO/my-app

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I am trying to run expo run:android but it is throwing an error:

Task :expo-permissions:compileDebugKotlin FAILED
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:18:26 Unresolved reference: ExportedModule
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:21:37 Unresolved reference: ExpoMethod
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:25:45 Unresolved reference: ExportedModule
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:30:3 'onCreate' overrides nothing
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:34:55 Unresolved reference: context
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:71:3 'getName' overrides nothing
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:73:4 Unresolved reference: ExpoMethod
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsModule.kt:82:4 Unresolved reference: ExpoMethod
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsPackage.kt:6:26 Unresolved reference: ExportedModule
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsPackage.kt:13:3 'createExportedModules' overrides nothing
e: /my-app/node_modules/expo-permissions/android/src/main/java/expo/modules/permissions/PermissionsPackage.kt:13:67 Unresolved reference: ExportedModule

What platform(s) does this occur on?

Android

SDK Version (managed workflow only)

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.4/bin/yarn
      npm: 10.8.3 - ~/.nvm/versions/node/v18.20.4/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31, 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 34.0.0, 35.0.0
        System Images: android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.36 => 51.0.36 
      metro: ~0.80.8 => 0.80.12 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
No issue
```

**Comment by kaantpll** [comment]
any update ?  I got same erorr

**Comment by Mlfraga** [comment]
Same issue here

**Comment by jaswant0605** [comment]
Same issue.

**Comment by David-Montenegro** [comment]
same issue.

**Comment by Zeeshan-Satti** [comment]
Same issue

**Comment by Zeeshan-Satti** [comment]
Is there any solution regarding above issue?

**Comment by castrolem** [comment]
+1 on this issue

**Comment by Zeeshan-Satti** [comment]
The `expo-permissions` package has been replaced with module-specific permission methods. You should now use the permission methods provided by individual modules. For more details, visit [[expo-permissions on npm](https://www.npmjs.com/package/expo-permissions)](https://www.npmjs.com/package/expo-permissions).

**Comment by castrolem** [comment]
Interesting, in my case, this is not related to `expo-permissions`, but to `expo-document-picker`

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

Building a development build

### Summary

Running `npx expo run:android` throws the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-document-picker:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'compileDebugKotlin' (11).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
```

### Environment
```
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/luiscastro/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 16.0/16A242 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.32 => 51.0.32
      expo-router: ~3.5.19 => 3.5.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 13.4.2
    Expo Workflow: bare
```

### Expo doctor diagnosis
```
No issue
```

**Comment by lukmccall** [comment]
@TuvshinbayarO the `expo-permissions` package were deprecated a long time ago and it won't work anymore. See [replay from Zeeshan-Satti](https://github.com/expo/expo/issues/31821#issuecomment-2503454743).

@castrolem it doesn't look connected with this issue, can you create a new one?

**Comment by Zeeshan-Satti** [comment]
> Interesting, in my case, this is not related to `expo-permissions`, but to `expo-document-picker`
> 
> ### What platform(s) does this occur on?
> Android
> 
> ### Where did you reproduce the issue?
> Building a development build
> 
> ### Summary
> Running `npx expo run:android` throws the following error:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':expo-document-picker:compileDebugKotlin'.
> > Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'compileDebugKotlin' (11).
> 
>   Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
>   Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> ```
> 
> ### Environment
> ```
> expo-env-info 1.2.1 environment info:
>     System:
>       OS: macOS 15.1.1
>       Shell: 5.9 - /bin/zsh
>     Binaries:
>       Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
>       Yarn: 1.22.19 - ~/.yarn/bin/yarn
>       npm: 10.9.0 - ~/.nvm/versions/node/v20.16.0/bin/npm
>       Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
>     Managers:
>       CocoaPods: 1.15.2 - /Users/luiscastro/.rbenv/shims/pod
>     SDKs:
>       iOS SDK:
>         Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
>     IDEs:
>       Android Studio: 2024.1 AI-241.18034.62.2411.12169540
>       Xcode: 16.0/16A242 - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ~51.0.32 => 51.0.32
>       expo-router: ~3.5.19 => 3.5.19
>       react: 18.2.0 => 18.2.0
>       react-dom: 18.2.0 => 18.2.0
>       react-native: 0.74.3 => 0.74.3
>       react-native-web: ~0.19.13 => 0.19.13
>     npmGlobalPackages:
>       eas-cli: 13.4.2
>     Expo Workflow: bare
> ```
> 
> ### Expo doctor diagnosis
> ```
> No issue
> ```

Regarding this issue, You can try following [solution](https://github.com/skiptools/skip/issues/150#issuecomment-2183371302)

**Comment by fullupe** [comment]
same issue
