### ISSUE TITLE
App launch is delayed in standalone

### ISSUE THREAD

**Issue by clems36** [expo/expo#3182]
### Environment
- Sdk 31
- App's target: standalone
- Device: Huawei P9
- Model: EVA-L09
- Android version: 7.0

### Steps to Reproduce

- Launch the app inside the Expo client, leave it in the background, open it again and see that it opens quickly (normally)
- Launch the standalone app, leave it in the background, open it again and see that it takes 5-10 seconds to open.

### Expected Behavior

Standalone should open as fast as Expo client like it does on all the other devices I've tested.

### Actual Behavior

![ezgif com-resize](https://user-images.githubusercontent.com/6041593/50952364-81715a80-14b0-11e9-8b17-3b60ac308a10.gif)

On the left, we have the app inside the Expo client and on the right, the standalone. You can see that on the standalone, the keyboard appears instantly because a text input is currently focused in the app, but the app only appears after a few seconds.

### Reproducible Demo

I've sent an apk and a link to the published app to secure@expo.io as suggested [here](https://forums.expo.io/t/app-launch-is-delayed-in-production/17908/2?u=emixis) 

### Two things that I find strange here

- Within the 5-10 seconds of opening, if I tap on the screen as if the app was already opened, the app responds. It’s like it is already opened but simply transparent.
- As far as I know, the issue only happens on this device. I tried on approximately 10 other devices with Android 6, 7 or 8 and everything is fine.

**Comment by esamelson** [comment]
Hey @clems36 - we refactored some of the Android standalone app loading code for SDK 32. If you get a chance to upgrade, could you let us know if the issue persists in the new version?

**Comment by ardyfeb** [comment]
I have same issue, i already all info and my app repo but expo team tagging my issue "needs more info"

**Comment by parthya** [comment]
+1 

Getting this issue since late December, although we never updated the SDK version. https://forums.expo.io/t/issue-with-exp-build-android-recently/17508

**Comment by parthya** [comment]
Can confirm this happening on SDK 32.0.0 too. App takes 5-6 seconds to open after tapping the notification.

**Comment by clems36** [comment]
@esamelson I confirm that the behavior is the same on sdk 32.

**Comment by parthya** [comment]
@esamelson Any devices for us. Also, in our case only when launching app by tapping the notification. We're using Expo Notifications. Though everything was working normal before December.

**Comment by ardyfeb** [comment]
@esamelson Xiaomi redmi 4x too

**Comment by clems36** [comment]
Any news on this ?

**Comment by tsapeta** [comment]
@clems36 no, I didn't have a chance to look at this. We will notify you once we get any news 😉

**Comment by Erlix322** [comment]
Same with sdk 33.0.0 Huawai DLI-L22

**Comment by srep2512** [comment]
Got the same behavior on Samsung Galaxy J5

**Comment by stopdesign** [comment]
A have the same issue on Huawei Mate 8, Android 7.0.
SDK 36.0.0.

I can confirm that within 5 seconds (precisely) the app is open, active and invisible. And after that I see an opening animation.

**Comment by sa1dai** [comment]
Same issue on Android 7.1, Redmi 4A, Expo 36.

> launch the standalone app, leave it in the background, open it again and see that it takes 5-10 seconds to open

**Comment by JanGunzenhauser** [comment]
Same. Android 7.0, Expo 33.0.7.

> launch the standalone app, leave it in the background, open it again and see that it takes 5-10 seconds to open
