### ISSUE TITLE
can't open apps android version kitkat

### ISSUE THREAD

**Issue by zanisis** [expo/expo#3183]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^25.0.0 => 25.1.2
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

App Target: Android (ExpoKit) from expo eject
### Steps to Reproduce

(Write your steps here:)

1. i know kitkat on expo will be drop in 2019, but some case or client has phone on android kitkat, and then apps will blink screen and apps cannot open.
2. i already downgrade on expo and sdk from 30 to 25 and still blink screen

![image](https://user-images.githubusercontent.com/25142795/51020715-f4162f00-15b1-11e9-9795-d11075105d02.png)

### Expected Behavior

still what should i do for running apk in version kitkat 

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by esamelson** [comment]
Hi @zanisis - we dropped support for Android 4.4 starting in SDK 31. If your project is on SDK 30 or below, for now you can still build a standalone APK that supports Android 4.4.

However, it looks like your project is using SDK 25, which is old enough that we no longer provide support for it. I would suggest that you upgrade to a newer SDK version and then, if you're still experiencing problems, please open a new issue with more information including a way to reproduce the problem. Thanks 🙂
