### ISSUE TITLE
Unable to Prebuild and Run Expo Application After Gradle Cache Removal

### ISSUE THREAD

**Issue by vishva-simform** [expo/expo#31843]
### Summary

Description:

I've initiated a fresh Expo project and was able to successfully prebuild and run the application without any issues initially. However, after removing the Gradle cache, I can no longer run the application. It appears that the expo run:android command is not reinstalling the required Gradle files.

In contrast, with an ejected Expo project, using the react-native run-android command automatically downloads the necessary Gradle dependencies and runs the application without any issues.

Issue:

After removing the Gradle cache, the expo` run:android `command does not reinstall or download the required Gradle files.
In an ejected Expo project, the react-native run-android command handles Gradle installation automatically.
Question:

Is there a manual step required in Expo to handle this scenario? I believe that `expo run:android` should automatically download and configure Gradle after a prebuild without manual intervention. Any insights or suggestions would be greatly appreciated!

Thank you in advance for your help.
<img width="1174" alt="Screenshot 2024-10-03 at 7 09 31 PM" src="https://github.com/user-attachments/assets/611adc89-56c0-472b-b82c-6138a8a0f8e9">

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - /usr/local/bin/npm
      Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
```

**Comment by vonovak** [comment]
Hello and thanks for asking,
This is not a problem with Expo, but an issue with Gradle. I recommend you follow either 

- this advice https://discuss.gradle.org/t/something-borked-in-gradle-8-7-specifically/49340/3
- change gradle version in `gradle-wrapper.properties` file, then it should start working
- use "invalidate caches" option in android studio

Thank you 🙂
