### ISSUE TITLE
voiceIOS option for Expo.Speech doesn't work

### ISSUE THREAD

**Issue by YanvegHD** [expo/expo#3186]
### Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19 (Tara)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/bin/node
      npm: 6.5.0 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      @types/react: ^16.3.10 => 16.7.18
      @types/react-native: ^0.55.2 => 0.55.28
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.3 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

1. Download the iOS Voice in Settings -> General -> Accessibility -> Speech -> Voice, and download the voice you want to use (For this example, Aurelie voice in French) 
2. Call this function in your app : 

`Expo.Speech.speak("Bonjour le monde", {language: 'fr', voiceIOS: 'Aurelie'});`

3. As you hear it doesn't use the voice you choose, it uses the default voice, but IF you select Aurelie as default speech voice in your iOS settings, it speaks with this voice.

The 'voiceIOS' option is ignored.

### Expected Behavior

Expected to speak with the voice defined in the 'voiceIOS option'

### Actual Behavior

Speaks with the selected voice in iOS settings.

### Reproducible Demo

Sorry, no time to make this, but it's pretty easy to make.

Thank you very much !

**Comment by EvanBacon** [comment]
Unrelated but it appears that if you specify the voice than the language is ignored.
The code seems pretty straight forward:

```objc
NSString *voice = options[@"voiceIOS"];

if (language != nil) {
      utterance.voice = [AVSpeechSynthesisVoice voiceWithIdentifier:voice];
}
```

`Aurelie` is probably not a valid voice identifier.
