### ISSUE TITLE
iOS build on M2 MacBook Pro: could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by vinnichase** [expo/expo#31885]
### Summary

On M2 MacBook Pro (Apple M2 Pro) the build fails once I add native modules like GoogleMLKit fails with

```
❌  (ios/Pods/Target Support Files/Pods-project/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/user/Library/Developer/Xcode/DerivedData/project-drllmsvyokalyvdcofnvitpdfhpa/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import ExpoAsset
  10 | import EXConstants
  11 | import ExpoFileSystem

```

I'm struggling for hours with different combinations. Shouldn't building on an arm be easier than on x86_64 and the default?

So far the expo experience is pretty limited because I'm not even getting started with coding.

### What platform(s) does this occur on?

`ios`

### SDK Version

`51.0.28`

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.17.0/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.36 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
```

### Minimal reproducible example

```
$ npx create-expo-app@latest
```
submit all defaults
```
$ yarn
```
(problem occurs with all package managers)
```
$ npx expo prebuild -p ios
```
```
$ npx expo run:ios
```
Works fine until here.

add GoogleMLKit pod

```
    flags = get_default_flags()
    pod 'GoogleMLKit/ObjectDetection', '3.2.0'
    pod 'GoogleMLKit/ObjectDetectionCustom', '3.2.0'
```

```
$ npx expo prebuild -p ios
```

```
$ npx expo run:ios
```

fails with 
```
❌  (ios/Pods/Target Support Files/Pods-project/ExpoModulesProvider.swift:8:8)

   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/user/Library/Developer/Xcode/DerivedData/project-drllmsvyokalyvdcofnvitpdfhpa/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.swiftmodule
   9 | import ExpoAsset
  10 | import EXConstants
  11 | import ExpoFileSystem

```

**Comment by ph20Eoow** [comment]
I have the same issue, also under M2 Macbook Pro

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I'm afraid this is not an issue with Expo (the error is a bit misleading here) but with Google's MLKit - you can see this in their "known issues" section: https://developers.google.com/ml-kit/known-issues


The workaround is to either
- build for a real device
- use some sort of build-time config which will skip installing MLKit for simulators and use a "stub" implementation when running on simulator.
- use Apple's vision framework: https://developer.apple.com/documentation/vision - it provides performs better for some use cases (really depends on what yours is)
- find some other workaround I'm not aware of


Thank you 🙂

**Comment by vinnichase** [comment]
Yes MLKit was only an example to bring up the `could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'`  error.

**Comment by tsapeta** [comment]
As far as I know, GoogleMLKit still doesn't support arm64 for simulator. You can see it in its podspec that arm64 is specified as an excluded arch: https://github.com/CocoaPods/Specs/blob/9112c3f116e69204c91a4c480a58b6738e522788/Specs/b/e/b/GoogleMLKit/3.2.0/GoogleMLKit.podspec.json#L18

Which means that Xcode is probably trying to build your project in x86_64 architecture and then run the simulator in the Rosetta mode. I'm guessing that precompiled version of some modules (including ExpoModulesCore) are cached on your machine and thus Xcode couldn't find it. Have you tried removing the `~/Library/Developer/Xcode/DerivedData` folder?

You can also try forcing Xcode to run the simulator in Rosetta mode, see this post that explains how to do it: https://stackoverflow.com/a/78631095

**Comment by khanhduy62** [comment]
is there any solution?

**Comment by immi-10** [comment]
Im also not using MLKit.
Any updates on this?
Running into the same Problem.
this is the part from my package.json:

```
  "dependencies": {
    "@aws-amplify/react-native": "^1.1.9",
    "@aws-amplify/rtn-web-browser": "^1.1.4",
    "@aws-amplify/ui-react-native": "^2.5.2",
    "@expo-google-fonts/work-sans": "^0.4.0",
    "@react-native-async-storage/async-storage": "^2.1.2",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-navigation/native": "^7.1.10",
    "@react-navigation/native-stack": "^7.3.14",
    "aws-amplify": "^6.14.4",
    "expo": "^53.0.9",
    "expo-app-loading": "^2.1.1",
    "expo-blur": "^14.1.5",
    "expo-dev-client": "~5.2.0",
    "expo-font": "~13.3.1",
    "expo-location": "^18.1.5",
    "expo-modules-core": "~2.3.13",
    "expo-status-bar": "~2.2.3",
    "react": "19.0.0",
    "react-native": "0.79.2",
    "react-native-get-random-values": "^1.11.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-svg": "15.11.2",
    "react-native-svg-transformer": "^1.5.1",
    "react-native-url-polyfill": "^2.0.0"
  },
```

**Comment by proambb** [comment]
We had the same error in bare ReactNative app. This comment helped https://github.com/expo/expo/issues/15800#issuecomment-1006643467

**Comment by paul-leo** [comment]
maybe you can try this expo plugin
https://github.com/Morphicai/expo-fix-ios-simulator-arch
