### ISSUE TITLE
[docs] [expo-notifications] Unclear notification handling for a 'killed' app state

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo#31886]
### Summary

After spending some hours dealing with notifications handling when the app is being killed, I'm starting to be suspicious if that should ever meant to work together.

The docs are mentioning defining a _background_ task via:
> When a notification is received while the app is backgrounded, using this function you can set a callback that will be run in response to that notification. Under the hood, this function is run using expo-task-manager. You must define the task first, with [TaskManager.defineTask](https://docs.expo.dev/versions/latest/sdk/task-manager#taskmanagerdefinetasktaskname-taskexecutor). Make sure you define it in the global scope.

I guess, my confusion was that other libraries mention have a similar API mentioning the background state, but that also work of the app is `killed`. As far as I can understand `expo-notifications` does not support processing `Data` type messages when the app is killed on Android.

My suggestion is to:
- explicitly outline this in the documentation.
- Maybe, also describing a workaround.

Workaround I'm aware of is sending the FCM Message of type Notification. That will be shown by Android OS. Also, as far as I can say, it's _not_ possible to add notification actions in that case, which is also worthy of being mentioned. 

> To handle notifications while the app is in the background or not running, you need to do the following:

The 'not running' part of the phrase might confuse to suggest a `killed` state. Let's clearly define background, foreground % killed states and limit API explanations to that, if it's possible.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/notifications/

**Comment by RohovDmytro** [comment]
Example of docs that have a similar API but supported in a terminated (killed) state:

https://rnfirebase.io/reference/messaging#gatsby-focus-wrapper

> setBackgroundMessageHandler
> Set a message handler function which is called when the app is in the background or terminated. In Android, a headless task is created, allowing you to access the React Native environment to perform tasks such as updating local storage, or sending a network request.

**Comment by RohovDmytro** [comment]
At the same time my Android logs look like `expo-task-manager` / `expo-notifications` do react to a Data type Message, but I was _not_ able to run the defined task handler.

I am confused :)

**Comment by RohovDmytro** [comment]
I will also worth pointing out that waking up the app from the killed state is done by sending a 'high' priority notification. Worth adding to docs too.

**Comment by vonovak** [comment]
Hello @RohovDmytro and thanks for reporting,
I really appreciate that you took time to report this and the other issues related to notifications - thank you!

We are ramping up our efforts to improve our notification support, which involves changes across our expo-notification package, our notification service, and documentation. As you pointed out, some scenarios are currently poorly supported and / or documented. We are working on this, but notifications have a very large surface area and improvements will take time to ship.
Please keep reporting issues that you find, it's a valuable piece of feedback for us which we'll use to improve the service.
 
Thank you! 🙂
