### ISSUE TITLE
Latest Android Expo Client (2.10.3) crashes when using RNScreens

### ISSUE THREAD

**Issue by cem2ran** [expo/expo#3191]
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.4.2 - /usr/local/bin/zsh
    Binaries:
      Node: 8.12.0 - ~/n/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/n/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 4.2.0-alpha.7 => 4.2.0-alpha.7 
      expo: ^32.0.0 => 32.0.0 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 

Targeting Android (Client/Standalone)

### Steps to Reproduce

Latest expo client 2.10.3 triggers the following error when you are using react-native-screens:

["In order to use RNScreens components your app's activity need to extend ReactFragmentActivity or ReactCompatActivity"](https://github.com/expo/expo/blob/8ba21123458615bcb21341aabaf6ebbe91a929ff/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/screens/ScreenContainer.java#L100)

(Write your steps here:)

1. Launch experience

### Expected Behavior

App should be rendered

### Actual Behavior

Crash on our internal project and in the minimal reproducible example in the snack below.

![image 3](https://user-images.githubusercontent.com/959142/51025889-7d673a80-158d-11e9-8bb7-b9c65535e008.png)

### Reproducible Demo

https://snack.expo.io/@cem2ran/expo-client-bug---rnscreens

**Comment by brentvatne** [comment]
cc @kmagiera

**Comment by cem2ran** [comment]
Just to add some more info I did not get this warning in `2.10.2`

**Comment by kmagiera** [comment]
Thanks for reporting. I think the linked PR from screens repo should resolve this issue. We will have this tested along with @tsapeta help and update here when this fix can be made available in expo client

**Comment by tsapeta** [comment]
Expo Client v2.10.4 that includes a fix in `react-native-screens` is now available on Google Play Store 😉
More specifically, it uses `react-native-screens@1.0.0-alpha.22`. In case of ejected projects, please make sure that you also have `expokit@32.0.4` installed.

Shoutout to @kmagiera for fixing it 👏
