### ISSUE TITLE
[expo-video] [android] Fullscreen with startsPictureInPictureAutomatically mismatch

### ISSUE THREAD

**Issue by erixtekila** [expo/expo#31916]
### Minimal reproducible example

https://github.com/erixtekila/expovideo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Hi,
This issue may be somewhat related to #31901 

When the fullscreen is turned on, android puts the app in background.
If `startsPictureInPictureAutomatically` is set to `true` while going fullscreen, Picture-in-Picture will be actived too, on a separate window, without image and sound.
It's then impossible to go from fullscreen to PiP and back to the `VideoView` in the app. The video stream is "locked" in the fullscreen view.

Like in iOS, the video should be able to go from fullscreen state to PiP then foregrounded app respectively. It should be 3 differents states.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0
        System Images: android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.36 => 51.0.36
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.12 => 0.19.12
    npmGlobalPackages:
      eas-cli: 12.5.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK
```

**Comment by fobos531** [comment]
@behenate This is an interesting issue - it makes perfect sense from a UX perspective. I would assume that the solution here is to make the `VideoView`'s PiP logic also apply to `FullScreenPlayerActivity`, because right now PiP is only handled for the main app activity.

**Comment by erixtekila** [comment]
Would be wonderful

**Comment by behenate** [comment]
The issues were fixed in the PR above. For now, on Android we won't have PiP that allows using the app while the app is in PiP, but we will likely try to implement something like that in a future version of `expo-video`.

**Comment by erixtekila** [comment]
Hi @behenate 
> For now, on Android we won't have PiP that allows using the app while the app is in PiP
I don't get this statement. Would you mind develop a little please ?
Anyhow, when the next `expo-video` release is planned ?
Thanks

**Comment by behenate** [comment]
You mentioned that 

> Like in iOS, the video should be able to go from fullscreen state to PiP then foregrounded app respectively. It should be 3 differents states.

From what I understand you meant: Regular playback -> playback in PiP window without closing the app -> playback in PiP window with the app backgrounded. 
For now in Android we only support Regular payback and Playback in PiP window with the app backgrounded, you can't play the video in a PiP window while the app is in the foreground. 

The PR above fixes the PiP support for fullscreen and should fix situations where the video enters PiP accidentaly when entering fullscreen.

**Comment by erixtekila** [comment]
Thanks for the explanation !

**Comment by erixtekila** [comment]
Hi,
I've updated my app dependencies to `expo-video@2.0.0-preview.0`.
Creating a new development build fails. Should I wait to `expo@52` to use it ?
Thanks

**Comment by behenate** [comment]
Hi, 2.0 won't work with the current version of `expo-modules-core`, you can try installing a nightly release of `expo-modules-core`. We will be releasing SDK 52 beta very soon as well 😄
