### ISSUE TITLE
Local non EAS build never finishes on mac

### ISSUE THREAD

**Issue by ani-t** [expo/expo#31927]
### Summary

I am new to Expo. On my Mac OS Sequoia i am unable to build an expo app. I am following the very basic steps of creating the expo app from documentation :
> npx create-expo-app@latest
Follow all prompts...
In project folder:
> npx expo install expo-dev-client
> npx expo run:ios --device

**The build proceeds till - "Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest". Nothing happens after this, no error log or warning or prompt, just stalls here.**
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/d81b8458-2a3a-44cd-aa5a-b09a969a3f62">

If i build the application in Xcode it reaches about 99% and stalls at the same line as above. No error.
All my NON expo apps build and run fine from Xcode.

I have the latest version of node (v20.18.0), npm. 

expo-doctor also shows no issues:
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions

Didn't find any issues with the project!

What should i look for? is there any other log file where I can figure out where the build is getting stuck at. Have been stuck here for a week now.

### What platform(s) does this occur on?

iOS

### SDK Version

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v20.18.0/bin/npm
      Watchman: 2024.10.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.37 => 51.0.37 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/ani-t/forwords

this is a barebones project created with npx create-expo-app@latest.

**Comment by nitinpatelm** [comment]
same issue

**Comment by flippingtables** [comment]
Same here.

**Comment by janmallari** [comment]
Have you fixed this @ani-t ?

**Comment by markmccoid** [comment]
I'm on Sequoia 15.0.1 using expo SDK 51.0.28 with react native 0.75.2

```
# Build for simulator works fine
npx expo run:ios

# Release config gets stuck
npx expo run:ios --configuration Release
``` 

This is where I get stuck if using the Release config or if sending to eas build in the cloud.

```
Linking   littleapemovies » littleapemovies
⚠️  ld: ignoring duplicate libraries: '-lc++'
› Generating debug littleapemovies » littleapemovies.app.dSYM
› Executing littleapemovies » Bundle React Native code and images
```
I have tried running "prebuild --clean", clearing xcode cache, etc.

Here is the git repo that is having the issue:
https://github.com/markmccoid/little-ape-movies

**Comment by markmccoid** [comment]
I am having the same issue as @flippingtables 

I am on Sequoia 15.0.1, expo SDK 51.0.28, react native 0.75.2

```
## Works
npx expo run:ios

## Gets stuck
npx expo run:ios --configuration Release
```

It also gets stuck in the same place when running in eas.
```
› Linking   littleapemovies » littleapemovies
⚠️  ld: ignoring duplicate libraries: '-lc++'
› Linking   littleapemovies » littleapemovies
⚠️  ld: ignoring duplicate libraries: '-lc++'
› Generating debug littleapemovies » littleapemovies.app.dSYM
› Executing littleapemovies » Bundle React Native code and images
```

Repo of app with issue.
https://github.com/markmccoid/little-ape-movies

**Comment by brentvatne** [comment]
hi there! you probably have something that is causing your metro build to hang. i've seen this happen often with tamagui, i'd recommend following something [like this](https://expo.fyi/manual-debugging) to debug it and see what the source is, if you're stuck

**Comment by flippingtables** [comment]
I think that in my case it was an issue with Nativewind that has since been resolved.
