### ISSUE TITLE
SDK 32 ScrollView not scrolling with useScreens and TabNavigator on ios  

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo#3192]
## Environment
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: 3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

(Write your steps here:)

1.Upgrading expo SDK 31 to 32.
2.import { useScreens } from 'react-native-screens' and useScreens.
3.Use createBottomTabNavigator
Like
Tab1 ScrollView
Tab2 ScrollView

4.Change Tab1 -> Tab2 -> Tab1 -> Tab2 
New Tab2 ScrollView will not scrolling.

But expo SDK 31 can scrolling.

### Expected Behavior

Tab2 ScrollView Can scrolling

### Actual Behavior

Tab2 ScrollView not scrolling

**Comment by rxhivzero** [comment]
I try Upgrading "react-native-screens": "1.0.0-alpha.21"
but same, only downgrade expo SDK 31 fix it.

**Comment by rxhivzero** [comment]
It may be the same problem?
https://github.com/kmagiera/react-native-screens/issues/53

**Comment by ikhilko** [comment]
Looks like yes, I've filled the same issue https://github.com/react-navigation/react-navigation/issues/5474

**Comment by aznoisib** [comment]
This bug is very complicated to test the needs of exposed devices
https://github.com/facebook/react-native/issues/25755

**Comment by tsapeta** [comment]
As all aforementioned issues have been closed, I'm closing this one too 🙂
