### ISSUE TITLE
Camera Facing Not working on Web

### ISSUE THREAD

**Issue by anthonybtedesco** [expo/expo#31924]
### Minimal reproducible example

https://github.com/anthonybtedesco/expo-camera-mre

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

On Expo Go the camera flip works fine.
However on the web version the camera flip does nothing.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.10 Manjaro Linux
      Shell: 5.2.32 - /bin/bash
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      npm: 10.9.0 - ~/.nvm/versions/node/v20.18.0/bin/npm
    SDKs:
      Android SDK:
        Android NDK: 27.0.12077973
    IDEs:
      Android Studio: AI-241.19072.14.2412.12360217
    npmPackages:
      expo: ~51.0.28 => 51.0.36
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by alanjhughes** [comment]
Hi @anthonybtedesco - what device did you test this on?

**Comment by anthonybtedesco** [comment]
@alanjhughes i used my phone to test this with chrome dev tools port forwarding extension

**Comment by entiendoNull** [comment]
I wasn't able to reproduce this issue in bare-expo (up to date).
Tested in Safari and Chrome on iOS and switching between `back` and `front` is working as exepcted.

Seems like the latest changes to expo-camera (that includes a fix to this specific issue) has yet not been released.

**Comment by anthonybtedesco** [comment]
@entiendoNull Hey Jacob, thanks for checking it out! How can i use this new version in my repo? Also I noticed in that other issue that you were mentioning the BarcodeScanner and some sort of interval, because I was also having trouble getting a qr code to scan in web.

It says it was merged to main by luca in that other issue, however i'm not sure what the npm registry is using?

How can i use the most up to date version of expo and expo-camera, i'm not sure what bare-expo is?

**Comment by entiendoNull** [comment]
Checking npm it seems like the latest version does not include this fix, I think. There is a canary version that does however.
But an Expo team member can probably better provide answers to your questions regarding this than I can :)

I just mentioned I tested this in `bare-expo` in order to facilitate the debugging process with this information in case an Expo member follows up on this issue. Using bare-expo is not the solution to your problem. If you are interested in reading about what it is you can refer to the contribution docs however, https://github.com/expo/expo/blob/main/CONTRIBUTING.md

**Comment by anthonybtedesco** [comment]
@alanjhughes apparently you're the guy to talk to. I'm looking to get the expo-camera-web fix merged into the main npm repo.

**Comment by anthonybtedesco** [comment]
Hello, just want to check in on the status of this. This is a pretty major issue concerning Expo Camera. How can i get the patched version?

**Comment by anthonybtedesco** [comment]
Okay, I guess I'll find another camera package.

**Comment by brentvatne** [comment]
hi @anthonybtedesco - use whichever package you like that works or you! i believe this is fixed in sdk 52 beta: https://expo.dev/changelog/2024/10-24-sdk-52-beta
