### ISSUE TITLE
Project Id not found. Despite l having the project id in app.json

### ISSUE THREAD

**Issue by elkee2003** [expo/expo#31930]
### Summary

I have my project id in app.json:
`{
  "expo": {
    "name": "AtaCrier",
    "slug": "AtaCrier",
    "version": "1.0.0",
    "orientation": "portrait",
    },
    "ios": {
      "supportsTablet": true,
      "runtimeVersion": {
        "policy": "appVersion"
      }
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "experiments": {
      "typedRoutes": true
    },
    "extra": {
      "eas": {
        "projectId": "XXXXX2f6d81ca820"
      }
    },
    "updates": {
      "url": "https://u.expo.dev/5df29d58-2ff7-48d3-b0b8-92f6d81ca820"
    }
  }
}
`
I am trying to access it here:
`import { useState, useEffect, useRef } from 'react';
import { Platform } from 'react-native';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';
import Constants from 'expo-constants';

Notifications.setNotificationHandler({
    handleNotification: async () => ({
      shouldShowAlert: true,
      shouldPlaySound: false,
      shouldSetBadge: false,
    }),
});

export default function NotificationProvider({children}){

    const [expoPushToken, setExpoPushToken] = useState('');
    const [notification, setNotification] = useState<Notifications.Notification | undefined>(
        undefined
    );
    const notificationListener = useRef<Notifications.Subscription>();
    const responseListener = useRef<Notifications.Subscription>();

    // UseEffect hook
    useEffect(() => {
        registerForPushNotificationsAsync()
          .then(token => setExpoPushToken(token ?? ''))
          .catch((error: any) => setExpoPushToken(`${error}`));
    
        notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
          setNotification(notification);
        });
    
        responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
          console.log(response);
        });
    
        return () => {
          notificationListener.current &&
            Notifications.removeNotificationSubscription(notificationListener.current);
          responseListener.current &&
            Notifications.removeNotificationSubscription(responseListener.current);
        };
    }, []);

    return children;
}

// Fuction to handle push notification below:
function handleRegistrationError(errorMessage: string) {
    alert(errorMessage);
    throw new Error(errorMessage);
}

async function registerForPushNotificationsAsync() {
    if (Platform.OS === 'android') {
      Notifications.setNotificationChannelAsync('default', {
        name: 'default',
        importance: Notifications.AndroidImportance.MAX,
        vibrationPattern: [0, 250, 250, 250],
        lightColor: '#FF231F7C',
      });
    }
  
    if (Device.isDevice) {
      const { status: existingStatus } = await Notifications.getPermissionsAsync();
      let finalStatus = existingStatus;
      if (existingStatus !== 'granted') {
        const { status } = await Notifications.requestPermissionsAsync();
        finalStatus = status;
      }
      if (finalStatus !== 'granted') {
        handleRegistrationError('Permission not granted to get push token for push notification!');
        return;
      }
    //   const projectId = '5df29d58-2ff7-48d3-b0b8-92f6d81ca820'
      
      console.log("Updated Expo Config:", Constants.expoConfig);

      const projectId =
        Constants?.expoConfig?.extra?.eas?.projectId ?? Constants?.easConfig?.projectId;
      if (!projectId) {
        handleRegistrationError('Project ID not found');
      }
      try {
        const pushTokenString = (
          await Notifications.getExpoPushTokenAsync({
            projectId,
          })
        ).data;
        console.log('This is push token', pushTokenString);
        return pushTokenString;
      } catch (e: unknown) {
        handleRegistrationError(`${e}`);
      }
    } else {
      handleRegistrationError('Must use physical device for push notifications');
    }
}
  `

the console.log gives me this :
`Updated Expo Config: {"android": {"adaptiveIcon": {"backgroundColor": "#ffffff", "foregroundImage": "./assets/images/adaptive-icon.png"}, "package": "com.anonymous.AtuaCourier", "permissions": ["android.permission.ACCESS_COARSE_LOCATION", "android.permission.ACCESS_FINE_LOCATION"]}, "experiments": {"typedRoutes": true}, "extra": {"router": {"origin": false}}, "icon": "./assets/images/icon.png", "ios": {"supportsTablet": true}, "name": "AtaCrier", "orientation": "portrait", "platforms": ["ios", "android", "web"], "plugins": ["expo-router", ["expo-location", [Object]]], "scheme": "myapp", "sdkVersion": "51.0.0", "slug": "AtaCrier", "splash": {"backgroundColor": "#ffffff", "image": "./assets/images/splash.png", "resizeMode": "contain"}, "userInterfaceStyle": "automatic", "version": "1.0.0", "web": {"bundler": "metro", "favicon": "./assets/images/favicon.png", "output": "static"}}`

I cant seem to access my project Id despite having one. How do I access it?

I passed the project id directly `const projectId = 'XXXX29'` in the `registerForPushNotificationsAsync` function and instead of `Project Id not found`, i go this error message `'ExpoPushTokenManager.getDevicePushTokenAsync' has been rejected.
→ Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.anonymous.AtuaCourier. Make sure to call FirebaseApp.initializeApp(Context) first. ` . Let it be known that I added google-services.json file in my root  folder, and I also uploaded the private key generated in firebase to expo in `upload new key`

### SDK Version

51.0.37

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22000
    Binaries:
      Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      expo: ~51.0.35 => 51.0.35
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare
```

### Minimal reproducible example

github/repo

**Comment by cross19xx** [comment]
Can you put your `app.json` (properly formatted) in, from what you pasted, there are missing closing braces, and some configurations are outside the `expo` property

**Comment by brentvatne** [comment]
run `npx expo config --type public` to see the evaluated config. it's probably missing from there. if you have app.config.js/app.config.ts, you might need to ensure you're extending your app.json.

eg:

```
module.exports = ({ config }) => {
  return {
    ...config,
  };
};

```

**Comment by elkee2003** [comment]
This is what my app.json looks like:
`{
  "expo": {
    "name": "Atier",
    "slug": "Atier",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true,
      "runtimeVersion": {
        "policy": "appVersion"
      }
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "permissions": [
        "android.permission.ACCESS_COARSE_LOCATION",
        "android.permission.ACCESS_FINE_LOCATION"
      ],
      "package": "com.anonymous.AtuaCourier",
      "runtimeVersion": "1.0.0",
      "googleServicesFile": "./google-services.json"
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow Atua to use your location."
        }
      ],
      "expo-font"
    ],
    "experiments": {
      "typedRoutes": true
    },
    "extra": {
      "eas": {
        "projectId": "XXXXX"
      }
    },
    "updates": {
      "url": "https://u.expo.dev/5df29d58-2ff7-48d3-b0b8-92f6d81ca820"
    }
  }
}
`
When I ran this `npx expo config --type public` I was able to see my project id in the console:
`extra: {
    eas: {
      projectId: 'XXXXX'        
    },
    router: {
      origin: false
    }
  },
  updates: {
    url: 'https://u.expo.dev/5df29d58-2ff7-48d3-b0b8-92f6d81ca820'
  }`

However I still get an alert stating that it cannot find project id

I created an app.config.js file and add this (I believe that is what you meant when you said ensure it is extending):
`module.exports = ({ config }) => {
    return {
      ...config,  // Spread the existing config
      extra: {
        ...config.extra,
        eas: {
          projectId: 'XXXXXX',
        },
      },
    };
  };`

Please is there a clearer way to go about this?
