### ISSUE TITLE
Open downloaded files

### ISSUE THREAD

**Issue by erbud** [expo/expo#3193]
### Environment

```
 Expo CLI 2.4.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.10.1 - /usr/local/bin/node
      npm: 4.6.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 7.3.1/7D1014 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.0 => 30.0.0 
      react: 16.3.1 => 16.3.1 
      react-native: ~0.55.4 => 0.55.4 
      react-navigation: ^1.5.12 => 1.5.12 
    npmGlobalPackages:
      expo-cli: 2.4.0
```

Run on Android device.

### Steps to Reproduce

Unable to open downloaded files.

1. Download a file (FileSystem.downloadAsync()).
2. Check if can open it (Linking.canOpenURL()).
3. Open the file (Linking.openURL()).

```
FileSystem.downloadAsync(url, fileUri)
  .then(({ uri }) => {
    Linking.canOpenURL(uri).then(supported => {
      if (supported) {
        Linking.openURL(uri);
      }
      else {
        console.log('File not supported…');
      }
    });
  })
  .catch(error => {
    console.error(error);
  });
```

### Expected Behavior

That Linking.openURL() method open the file with the default application.

### Actual Behavior

The file is not opened and the following warning message is returned.

> [Unhandled promise rejection: Error: Could not open URL 'file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540accountt2%252Fproject/myDirectory/myFile.pdf': file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540account2%252Fproject/myDirectory/myFile.pdf exposed beyond app through Intent.getData()]

### Reproducible Demo

https://snack.expo.io/S1dU7MUGV

**Comment by tcdavis** [comment]
file is not one of the built in linking schemes https://docs.expo.io/versions/v32.0.0/workflow/linking#built-in-url-schemes

If you just want to open a pdf, using WebBrowser would probably be easiest.

If you want to hook in to the intent system you'll need: https://docs.expo.io/versions/latest/sdk/intent-launcher
