### ISSUE TITLE
App must target Android 14 (API level 34) or higher

### ISSUE THREAD

**Issue by muhammad-hunnain786** [expo/expo#31944]
### Minimal reproducible example

https://github.com/expo/expo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

i update the app to expo version 51.0.37 but still google play store show be error

App must target Android 14 (API level 34) or higher

when expo will add api level 34 or release new version ??

### Environment

```text
Nothing there
```

### Expo Doctor Diagnostics

```text
No issues on Expo Doctor
```

**Comment by cross19xx** [comment]
Expo has had the target version in v34 since Expo 50 (See [this pull request](https://github.com/expo/expo/pull/25031)). Do you have a library that manipulates your build properties (like `expo-build-properties`)

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Expo already defaults to v34 as mentioned above.
Please see [here](https://docs.expo.dev/versions/latest/sdk/build-properties/#example-appjson-with-config-plugin) how you can configure the version.
Thank you 🙂

**Comment by cross19xx** [comment]
I'd be happy to help out. Can you create a repro?
