### ISSUE TITLE
Cannot make an android prebuild

### ISSUE THREAD

**Issue by dlogvin** [expo/expo#31942]
### Summary

Whenever I try to run the command:

`sudo npx expo run:android --device`

I am getting the following error:

```
* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> org.gradle.api.internal.catalog.GeneratedClassCompilationException: No Java compiler found, please ensure you are running Gradle with a JDK
```

`Doing sudo npx expo install --fix` did not help at all.

my `package.json` file looks like this:

```
"dependencies": {
    "@expo/vector-icons": "^14.0.3",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "axios": "^1.7.7",
    "expo": "~51.0.37",
    "expo-camera": "~15.0.16",
    "expo-font": "^12.0.10",
    "expo-linear-gradient": "~13.0.2",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "^3.0.7",
    "formik": "^2.4.6",
    "lottie-react-native": "6.7.0",
    "react": "18.2.0",
    "react-native": "^0.74.5",
    "react-native-animated-spinkit": "^1.5.2",
    "react-native-camera": "^4.2.1",
    "react-native-svg": "15.2.0",
    "react-native-vision-camera": "^4.5.3",
    "react-query": "^3.39.3"
  }
```

### SDK Version

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 20.17.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
      Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.37 => 51.0.37
      react: 18.2.0 => 18.2.0
      react-native: ^0.74.5 => 0.74.5
    npmGlobalPackages:
      eas-cli: 12.5.1
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Minimal reproducible example

I simply created a bare minimum expo project.

IOS prebuild works fine, android does not.

**Comment by dlogvin** [comment]
Just to also clarify, I removed `node_modules`, I did also `sudo npm i` and even though everything installs correctly, I still cannot prebuild on android. I am getting always the same error message: `Error resolving plugin [id: 'com.facebook.react.settings']`.

**Comment by cross19xx** [comment]
Try running the `android` directory in Android Studio and confirm what error pops up when you run it from there. This may be as a result of an improperly configured `JAVA_HOME`

**Comment by dlogvin** [comment]
> Hello and thanks for asking, `No Java compiler found, please ensure you are running Gradle with a JDK` - that's the error that you need to resolve.
> 
> Please follow https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build&buildEnv=local
> 
> You need to install the tooling to develop native apps - Java, Android Studio and more. Alternatively, you can use our build service to build the app - see https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build Thank you 🙂

Yup, you were right. I completely forgot, especially because I am working now with a new computer.

Thank you!
