### ISSUE TITLE
expo-updates bug when updating

### ISSUE THREAD

**Issue by Achex** [expo/expo#31946]
### Summary

When I type `npx expo install expo-updates` or `npm install expo-updates, I get the following error:
![image](https://github.com/user-attachments/assets/1c45fe40-fc59-442c-8eee-57d2a11fc314)

Even though I am not typing `expo-update`, is this a bug or am I being dumb?

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838
    npmPackages:
      @expo/metro-config: ~0.18.11 => 0.18.11
      expo: ~51.0.37 => 51.0.37
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed
```

### Minimal reproducible example

n/a, cli issue

**Comment by brentvatne** [comment]
hi there! maybe something wrong with your terminal or npm cli. we don't have any control over those. try running `npx expo install expo-updates` instead
