### ISSUE TITLE
When running expo start -p <platform>, detects as if there's other process & NaN as its port

### ISSUE THREAD

**Issue by eikefab** [expo/expo#31941]
### Summary

So the title is pretty self-explanatory, but, whenever you run

```expo start -c -p ios``` or ```expo start -c -p android```

It shows up that there's another process using the default port, even though there is not a process doing so. Reading the message, it shows up `NaN` as the "default port". At first, thought that it was caused by the `-c` flag, but even after removing it, still happens.

![image](https://github.com/user-attachments/assets/15d6720f-b5ea-4b4f-9dd1-71aa54685399)

But, when I use ```expo start -c --ios``` or ```expo start -c --android```, that doesn't happen.

So it seems that it runs different codes to check ports being used at the moment on ```-p <platform>``` and ```--<platform>```.

### SDK Version

51.0.37

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.4.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.37 => 51.0.37 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 10.1.1
    Expo Workflow: bare
```

### Minimal reproducible example

Run at your terminal:

* ```expo start -c -p ios``` or ```expo start -c -p android```
* Or even if I remove the ```-c``` flag, the issue still happens.

The "NaN" port and it being used by another process message doesn't show up if you do:

```expo start -c --ios``` or ```expo start -c --android```

**Comment by cross19xx** [comment]
`-p` specifies the port number, not the platform (you can confirm this by running `expo start --help` and reviewing the list.
A default project shows you (inside the `script` of the `package.json`) how to run for the proper platform

**Comment by eikefab** [comment]
Yeah, that's it. Though `-p` was meant to specify the platform, as doing on `EAS` (`eas build -p android`, e.g.).
