### ISSUE TITLE
expo-video - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by georgelanes** [expo/expo#31954]
### Minimal reproducible example

To reproduce the bug, use especial charset and space. Ex.: "Unifétv Portugal"

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Expo 51, Android 11 Simulator, MacBook Pro M1.

1. To reproduce the bug, use especial charset and space. Ex.: "Unifétv Portugal"
3. Run: npm run android 
2. Bug
10-09 01:13:04.959  1964  1964 D BasicMediaStatusFactory: Supported media session actions: 7339671
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal: Playback error
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:712)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: Unexpected char 0xe9 at 4 in User-Agent value: Unifétv Portugal/1.0.5 (Linux;Android 12) AndroidXMedia3/1.4.0
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:442)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:920)
**10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalArgumentException: Unexpected char 0xe9 at 4 in User-Agent value: Unifétv Portugal/1.0.5 (Linux;Android 12) AndroidXMedia3/1.4.0**
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at okhttp3.Headers$Builder.add(Headers.kt:261)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at okhttp3.Request$Builder.addHeader(Request.kt:210)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:398)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:262)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
10-09 01:13:04.968  5275  5402 E ExoPlayerImplInternal:       ... 3 more

Note.: The problem doesn't happen with expo-av.

Need to check the User-Agent definition.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-30 | Android TV Intel x86 Atom, android-31 | Google TV ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.35 => 51.0.37 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native-tvos:  0.74.5-0 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
npx expo-doctor@latest                                                   ✔  took 18s   18.17.0  
Need to install the following packages:
  expo-doctor@1.10.1
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by georgelanes** [comment]
You can reproduce it by yourself by creating a project and following these steps.

1. Create a expo project with tv template.
2. Install expo-video.
3. Use this minimal code.
`import { Video, ResizeMode } from 'expo-av';
import { useFocusEffect, useLocalSearchParams, useNavigation, useRouter } from "expo-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, BackHandler, TVEventControl, View } from "react-native";
import { useAppStyles } from "@/hooks/useAppStyes";

const LivePlayer = () => {

    const styles = useAppStyles();
    const videoRef = useRef(null);
    const navigation = useNavigation();
    const url = "http://myvideourl"; // change to real URL (m3u8 or mp4)
    const [isPlaying, setIsPlaying] = useState(true);
    

    useEffect(() => {
        TVEventControl.enableTVMenuKey();
        return () => {
          TVEventControl.disableTVMenuKey();
        };
      }, []);

    useFocusEffect(
        useCallback(() => {
            const backAction = () => {
                setIsPlaying(false);
                navigation.goBack();
                return true;
            };
            
            const backHandler = BackHandler.addEventListener('hardwareBackPress',backAction);
            return () => {
                backHandler.remove();
            };
        }, []),
    );


    return (
        <View style={styles.videoPlayerContainer}>
            {url ? (
                <Video
                    ref={videoRef}
                    style={styles.video}
                    source={{
                        uri: url,
                      }}
                    useNativeControls
                    resizeMode={ResizeMode.CONTAIN}
                    rate={1.0}
                    volume={1.0}
                    isMuted={false}
                    shouldPlay
                    isLooping                                             
                />

            ) : (
                <ActivityIndicator animating={url != null} color="#fff" size="large" />
            )}
        </View>
    )
}

export default LivePlayer;`

**Comment by RohovDmytro** [comment]
@georgelanes Have you found what was causing the issue? I'm having a similar problem but with audio file now.
