### ISSUE TITLE
Unable to run ios simulator with version 32

### ISSUE THREAD

**Issue by krini** [expo/expo#3195]
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.14

IOS

### Steps to Reproduce

1. Create a new empty project with expo init my-new-project
2. expo start

I get an error on the simulator.

In the terminal I get:
This version of the Expo app is out of date. Uninstall the app and run again to upgrade.

However I'm running versino 32.

### Expected Behavior

I should be able to run the ios simulator

### Actual Behavior

The simulator starts but it says there was a problem loading the requested app

### Reproducible Demo

https://snack.expo.io/HJbiNX8fE

**Comment by rxhivzero** [comment]
Uninstall expo app on ios simulator and expo start

**Comment by krini** [comment]
Thanks, it is actually working. How did you know that workaround?
