### ISSUE TITLE
[expo-notifications] wrong PermissionStatus export

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo#31962]
### Minimal reproducible example

- https://github.com/expo/expo/issues/31962

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Simple one. Permission status is an enum in `expo-notifications@0.28.18`.

But it's get exported as a type:
````
export type { Subscription, PermissionResponse, PermissionStatus, PermissionExpiration };
````

This leads to type error:

<img width="816" alt="image" src="https://github.com/user-attachments/assets/c66819a7-6862-49ce-8ef4-0c8cb47518da">

### Environment

```text
-
```

### Expo Doctor Diagnostics

```text
-
```

**Comment by vonovak** [comment]
Hello and thanks for reporting,
please import `import {PermissionStatus} from "expo-modules-core";` as a workaround for now.
Thank you 🙂
