### ISSUE TITLE
Audio.Sound timestretching has heavily degraded quality on iOS (but not Android)

### ISSUE THREAD

**Issue by sharpninth** [expo/expo#3197]
Reproducible demo: https://snack.expo.io/@jiveworld/jiveworld-expo-test

We are slowing down the playback (timestretching) an mp3 playback, using 

`Audio.Sound.setRateAsync(...)`

The sound quality is excellent when running on Android, but is severely degraded with "echo" artifacts when running on iOS.

### Environment
Target is iOS and Android - but problem only on iOS.

❯ expo diagnostics                                                                                                                                                                                              
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.8 => 3.0.8
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

1. After load, select a track from the list at the top
2. Click `Play`
3. Slide the `Time stretching` slider at the bottom to, for example, 0.7

### Expected Behavior

The playback should be slower without any change in pitch, and without any very noticeable audio artifacts.

### Actual Behavior

On iOS handsets there are very strong artifacts that cause a reverb type effect with heavy early reflections.

On Android there the playback is smooth.

Note also that when running iOS (not Android) it sometimes (not always) get's stuck on the initial loading screen as if it isn't connecting to the server to download the audio. Please retry if that happens. 

### Reproducible Demo

https://snack.expo.io/@jiveworld/jiveworld-expo-test

**Comment by tcdavis** [comment]
Excellent report, thank you!
The audio manipulation has been optimized for music, not speech.  
Could you create a request on canny: https://expo.canny.io/feature-requests, or let us know if you'd be interested in submitting a PR?

**Comment by sharpninth** [comment]
@tcdavis - Thanks. I'll submit a FR. A couple of observations / questions:

1. This works great on Android for speech (and music) - just not on iOS. Is it the same underlying code used on both?

2. I tried with music on iOS and even though the problem is a little less noticeable, it's still an issue. I created another Snack with a music example (tap on m4a in the initial list)

 https://snack.expo.io/@jiveworld/rebellious-milkshake

(was seeing if behavior was effected by file encoding - not surprisingly it isn't :-) )

**Comment by sharpninth** [comment]
Thanks to a [code pointer](https://github.com/expo/expo/blob/master/packages/expo-av/ios/EXAV/EXAVPlayerData.m#L292) from Jess @ Expo - it looks like on the iOS side we're using Apple's own [AVFoundation library for the timestretching](https://developer.apple.com/documentation/avfoundation/audio_track_engineering/audio_settings_and_formats/time_pitch_algorithm_settings?language=objc), which offers three algos of different quality (and computational intensity) - 

Expo defaults to the lowest quality one `AVAudioTimePitchAlgorithmLowQualityZeroLatency` which is "suitable for brief fast-forward and rewind effects as well as low quality voice".

Any chance to implement a config option to allow the selection of one of the other two:
- `AVAudioTimePitchAlgorithmTimeDomain` (med quality)
- `AVAudioTimePitchAlgorithmSpectral` (high quality)
?

**Comment by sharpninth** [comment]
Hi @sjchmiela - I can have a crack at it if I can set up the dev environment. I'll follow the README at the top of the repo.

As far as API changes, can you have a look at this spec and let me know if this looks right (naming, locations etc.) Thanks!

# Expo.Audio.Sound API changes

## Timestretching algo constants for iOS
* `Expo.Audio.PLAYBACK_PITCH_CORRECTION_LOW_QUALITY`
* `Expo.Audio.PLAYBACK_PITCH_CORRECTION_MEDIUM_QUALITY`
* `Expo.Audio.PLAYBACK_PITCH_CORRECTION_HIGH_QUALITY`

This is to match the syntax of the quality level constants on the Record object
i.e. `Expo.Audio.RECORDING_OPTIONS_PRESET_LOW_QUALITY` & `Expo.Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY`

These three constants will map to the [three time-pitch algos provided in the Apple AVFoundation libraries](https://developer.apple.com/documentation/avfoundation/audio_track_engineering/audio_settings_and_formats/time_pitch_algorithm_settings?language=objc)
* AVAudioTimePitchAlgorithmLowQualityZeroLatency (default)
* AVAudioTimePitchAlgorithmTimeDomain
* AVAudioTimePitchAlgorithmSpectral

## Add new field to PlaybackStatus structure
`iosPitchCorrectionQuality` set to one of the three new constants

Default will still be `Expo.Audio.PLAYBACK_PITCH_CORRECTION_LOW_QUALITY` so as not to affect any existing usage (though might consider defaulting to `...HIGH_QUALITY` so there is parity of behavior with Android).

## Add shortcut method to `Expo.Audio.Sound` object
This can be used instead of passing a `PlaybackStatus` structure to `setStatusAsync(...)`

`soundObject.setIosPitchCorrectionQuality (qualityValue)`

## Documentation to update
* [Audio.Sound](https://docs.expo.io/versions/v32.0.0/sdk/audio/#expoaudiosound) 
* [AV](https://docs.expo.io/versions/v32.0.0/sdk/av/)

**Comment by sharpninth** [comment]
Of course the much simpler change (1 liner - not requiring API or doc updates) would be to switch out `AVAudioTimePitchAlgorithmLowQualityZeroLatency` for `AVAudioTimePitchAlgorithmSpectral` - which would also make it parity with Android. But there would be risk of regressions for others already using this library. But I mention just in case :-)

**Comment by esamelson** [comment]
Hi @sharpninth - your proposal sounds like a solid plan to me. Agree that maintaining the current behavior as the default is worthwhile at least for now, so I think we'd want to have `LOW_QUALITY` be the default option. It would also be good to have some explanation in the docs about what the various use cases of these three options are. But overall this seems good and we'd be happy to look at a PR for it!
