### ISSUE TITLE
`ExpoView` leaks memory on iOS with the New Architecture enabled starting from version 1.12.13 of `expo-modules-core`

### ISSUE THREAD

**Issue by SiarheiBarysenka** [expo/expo#31972]
### Minimal reproducible example

https://github.com/SiarheiBarysenka/expo-memory-leak

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

`ExpoView` leaks memory on iOS in projects with New Architecture enabled. This issue occurs starting from version 1.12.13 of the `expo-modules-core` package and higher.

The sample app in the repository demonstrates the issue. The app includes a simple subclass of `ExpoView` called `LeakingExpoView`, which has no functionality beyond setting the background color to red. When navigating to this view in the app and then back, the `LeakingExpoView` remains in memory, as observed in the Xcode memory debugger (see the attached video).

### Steps to reproduce

1. Checkout the `main` branch of the https://github.com/SiarheiBarysenka/expo-memory-leak repository.
2. Run the iOS app located in the `leaking-expo-view/example` folder.
3. When the app is running, tap the "Navigate to LeakingView" button. The app presents the `LeakingExpoView` (painted in red).
4. Tap the back button to navigate back.
5. Observe the memory hierarchy in the Xcode memory debugger.

### Expected result

1. The memory hierarchy has no traces of `LeakingExpoView`.

### Actual result

1. The `LeakingExpoView` remains in the memory hierarchy.

https://github.com/user-attachments/assets/5f2a9a6f-2b00-45c1-a739-3a168c4587e7

### Additional notes

If the `expo-modules-core` package is downgraded to version 1.12.12, the issue no longer occurs. Please check out the `no-leak` branch of the https://github.com/SiarheiBarysenka/expo-memory-leak repository, which contains `expo-modules-core` downgraded to 1.12.12. Run the steps outlined above to observe the expected result (the memory hierarchy shows no traces of `LeakingExpoView`):

https://github.com/user-attachments/assets/3899f596-5adb-4de6-a06e-1c7bab3e927b

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
      Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/sbarysenka/.rvm/gems/ruby-3.1.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.37 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 12.5.1
      expo-cli: 6.3.10
    Expo Workflow: bare
```
```


### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, userInterfaceStyle, splash, ios, android, plugins. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following packages should be updated for best compatibility with the installed expo version:
  typescript@5.6.3 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```
```

**Comment by nikita-leonov** [comment]
Seems like the issue introduced in this particular change https://github.com/expo/expo/pull/28829/commits/9ff8a0387256a2009126e57abe41dd7456f81154#diff-9a415348bcd8e1ede064f28c32aaf4cb7bfa69ca9b6abe096b05c1cb228579eaR155 where `prepareForRecycle` removed.  It was nullifying `contentView`. However, PR https://github.com/expo/expo/pull/31841 fixes it. Quite unfortunately there is no control to an end developer over this behavior, so adoption of a next core library release or a patch on the dev side would be needed to pull in the behavior.

**Comment by tsapeta** [comment]
One of the main features of the New Architecture is view recycling. Unmounted views are put into the recycling pool of views, so that React Native can reuse them whenever you render them once again. I haven't done any benchmarks, but I think it does improve the performance as the view creation is not the cheapest operation. There is always a trade-off.
Thus, I wouldn't call it a memory leak as long as it's not creating more views endlessly.

In the SDK 52 all iOS views made with Expo Modules API will have the recycling disabled. We're currently looking for the best way to give the user more control on that.

**Comment by SiarheiBarysenka** [comment]
Thanks @tsapeta for your answer!

I wonder, do you plan to release a minor (or patch) update of the library with https://github.com/expo/expo/pull/31841 included? Curious if there's an update planned that would include this change before the major 52 bump. Thanks!

**Comment by tsapeta** [comment]
@SiarheiBarysenka No, we don't plan to backport this change to SDK 51, especially that SDK 52 beta will be available pretty soon. Moreover, this is not a bug, that's the default behavior of the New Architecture to recycle views. We just decided to disable it by default but only for now, to make the transition from the old architecture a bit smoother.

**Comment by SiarheiBarysenka** [comment]
Thanks @tsapeta ! I'm closing the issue, since it's all clarified now.
