### ISSUE TITLE
Invalid `hermes-engine.podspec` file: undefined method `visionos' for #<Pod::Specification name="hermes-engine/Pre-built">

### ISSUE THREAD

**Issue by emoran** [expo/expo#31975]
### Summary

In a brand new project, after  `run npx expo run:ios `  I'm getting this output:

`⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Failed to load 'hermes-engine' podspec: 
[!] Invalid `hermes-engine.podspec` file: undefined method `visionos' for #<Pod::Specification name="hermes-engine/Pre-built">.

 #  from /Users/emoran/Documents/repositories/expo/f3mobile/node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec:47
 #  -------------------------------------------
 #        ss.ios.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"
 >        ss.visionos.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"
 #        ss.osx.vendored_frameworks = "destroot/Library/Frameworks/macosx/hermes.framework"
 #  -------------------------------------------

pod install --repo-update --ansi exited with non-zero code: 1`

currently using: MAC OS Sequoia 15.0.1 (24A348)

node -v  (v18.20.4)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~4.0.28"

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.7.0 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 30, 33, 34
        Build Tools: 30.0.2, 33.0.0, 34.0.0
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.37 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.5.1
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Reproducible demo

creating a new project using
`npx create-expo-app@latest`

follow the steps to setup initial project and run:

`npx expo run:ios`

### Stacktrace (if a crash is involved)

```text
npx expo run:ios                                                                                                          11s
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Failed to load 'hermes-engine' podspec: 
[!] Invalid `hermes-engine.podspec` file: undefined method `visionos' for #<Pod::Specification name="hermes-engine/Pre-built">.

 #  from /Users/emoran/Documents/repositories/expo/f3mobile/node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec:47
 #  -------------------------------------------
 #        ss.ios.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"
 >        ss.visionos.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"
 #        ss.osx.vendored_frameworks = "destroot/Library/Frameworks/macosx/hermes.framework"
 #  -------------------------------------------


pod install --repo-update --ansi exited with non-zero code: 1
```

**Comment by bladerunner2020** [comment]
I encountered this issue in two projects with the latest version of expo (52.0.23). You might need to add a visionOS target in Xcode or instruct Xcode to install all platforms. However, I haven’t tried this approach yet.

Alternatively, you could open the problematic file, e.g., `/Users/emoran/Documents/repositories/expo/f3mobile/node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`, in an editor and comment out the following lines:

```bash
  ...
  # spec.visionos.vendored_frameworks = "destroot/Library/Frameworks/xros/hermes.framework"

  ...
 
  # ss.visionos.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"

```

This worked in my projects.


PS
I think the issue should be reopen.

**Comment by ryanyogan** [comment]
Thank you, this worked for me.  I agree, this ticket should be reopened, I am investigating which library is causing this.  In the past two days I have started three new projects, of those three, two have had this issue.   Thank you so much for causing me hours of debugging!

> I encountered this issue in two projects with the latest version of expo (52.0.23). You might need to add a visionOS target in Xcode or instruct Xcode to install all platforms. However, I haven’t tried this approach yet.
> 
> Alternatively, you could open the problematic file, e.g., `/Users/emoran/Documents/repositories/expo/f3mobile/node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`, in an editor and comment out the following lines:
> 
>   ...
>   # spec.visionos.vendored_frameworks = "destroot/Library/Frameworks/xros/hermes.framework"
> 
>   ...
>  
>   # ss.visionos.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"
> This worked in my projects.
> 
> PS I think the issue should be reopen.
