### ISSUE TITLE
Different sound to play while receiving notifications in expo 

### ISSUE THREAD

**Issue by akshayfin** [expo/expo#3198]
I want to play some other sound like an alert one on receiving a notification.Is it possible yet as it is the most basic functionality?Below is my code:
`const receipts = expo.sendPushNotificationsAsync([
            {
              to: userObj.pushToken,
              sound: 'default',
              body: notification,
              data: { withSome: notification },
              priority: 'high'
            }
          ]);`

**Comment by brentvatne** [comment]
you need to eject your project to do this currently. it's not really 'the most basic functionality' :)

here's the related feature request that you can upvote: https://expo.canny.io/feature-requests/p/push-notification-include-custom-sound-files-in-build

**Comment by brentvatne** [comment]
i would love to have this feature one day but we don't yet support it and it's not on our immediate roadmap, please upvote it on the link i shared above! :) otherwise just eject and you can do it right now
