### ISSUE TITLE
[expo-firebase] 2.0.0 firebase.firestore.FieldValue.serverTimestamp() crashes app

### ISSUE THREAD

**Issue by redpandatronicsuk** [expo/expo#3200]
Using `firebase.firestore.FieldValue.serverTimestamp()` as a field when writing to firestore, e.g.
```
firebase.firestore().doc('foo/bar').set({
  last_changed: firebase.firestore.FieldValue.serverTimestamp()
})
```
crashes the app on iOS. With version 1.0.0 this used to work.

**Comment by redpandatronicsuk** [comment]
Not sure if this is of any help, but Xcode debug shows this when the app crashes:
```
libsystem_kernel.dylib`__pthread_kill:
    0x10e130234 <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x10e130239 <+5>:  movq   %rcx, %r10
    0x10e13023c <+8>:  syscall 
->  0x10e13023e <+10>: jae    0x10e130248               ; <+20>
    0x10e130240 <+12>: movq   %rax, %rdi
    0x10e130243 <+15>: jmp    0x10e12a3b7               ; cerror_nocancel
    0x10e130248 <+20>: retq  
```

**Comment by JamesMcIntosh** [comment]
I had this problem with #2943

**Comment by redpandatronicsuk** [comment]
**Update**: The code example I gave at the top actually works. I tried out a few more things and `set` and `update` both work, but using `set` with a second argument `{ merge: true }`, causes the crash. I'll close this issue and open a new one with actual problem.

**Comment by redpandatronicsuk** [comment]
I actually made a mistake, `{ merge: true }` option makes no difference. I'll keep this closed though, the new issue is here: https://github.com/expo/expo/issues/3584
