### ISSUE TITLE
Android production build: Task :app:mergeReleaseResources restrictions to bundled asset names conflict with React Native Image DPI feature

### ISSUE THREAD

**Issue by swayok** [expo/expo#32031]
### Build/Submit details page URL

https://expo.dev/accounts/swayok/projects/platido-dom-online-mobile/builds/8ac76889-d015-4205-ae60-bd6e4ee32891

### Summary

> Task :app:mergeReleaseResources
ERROR: /home/expo/workingdir/build/android/app/src/main/res/drawable/logo@3x.png: Resource and asset merger: '@' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore

React Native uses @2x/@3x to pick image for screen DPI (https://reactnative.dev/docs/images#static-image-resources).
Task :app:mergeReleaseResources does not allow @ symbol so this feature is broken now and I haven't found any info on how to name images for different DPI. Even Androids suffixes like -xxdpi are forbidden (only underscore allowed). 

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.6
      expo: ~51.0.34 => 51.0.34
      react: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    Expo Workflow: managed
```

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### Error output

Task :app:mergeReleaseResources
ERROR: /home/expo/workingdir/build/android/app/src/main/res/drawable/logo@3x.png: Resource and asset merger: '@' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore

### Reproducible demo or steps to reproduce from a blank project

Try to bundle an images with names: logo.png, logo@2x.png, logo@3x.png.

**Comment by LeunensMichiel** [comment]
We're having the exact same issue. Latest React Native 76.5 as well as expo 51.0.18 and expo-asset 11.0.1

Following the react native docs, this should work on both ios and android. As OP said this is breaking on android

```
ERROR: .....src/main/res/drawable/marker_secondary@2x.png: Resource and asset merger: '@' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```
