### ISSUE TITLE
Expo Web error "Uncaught Error: Buffer is not defined" after Metro bundling

### ISSUE THREAD

**Issue by lucaskraus** [expo/expo#32036]
### Minimal reproducible example

https://github.com/lucaskraus/expoweb-buffer-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Hello folks!

I'm currently using Expo mainly for web-version. I was searching for web-3 wallet solutions and find Web3Auth (https://web3auth.io/docs/). They have an complete solution for React Native and it is Expo compatible.

However, after all setup according their docs I'm receving the following error:

![image](https://github.com/user-attachments/assets/5ab05fcf-ef59-4e82-a115-c444296bfbee)

The error occurs after the Metro bundling for web. Even though not shows any error during the bundling, after the root route is loaded it shows the message and don't let any other action.

I tried a lot of setups into metro.config.js and babel.config.js, but the error persists.

To reproduce the error in repository example:

1. Run "npm i --force" to install all dependencies 
2. Run "npx expo start" command
3. Open the web version pressing W

Thanks in advance.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    npmPackages:
      expo: ~50.0.19 => 50.0.19 
      expo-router: ~3.4.10 => 3.4.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.9 
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
hi there! you should post this issue to the web3authn repo. if you find that the issue is indeed on the expo side, feel free to post an issue here.
