### ISSUE TITLE
Latitude from Location.getCurrentPositionAsync

### ISSUE THREAD

**Issue by jasuno** [expo/expo#3205]
how do get the lat,long from Location.getCurrentPositionAsync. Im able to get the of the object, but i only want the latitude and the longitude.

here is my code:

state = {
    locationResult: null
  };

  componentDidMount() {
    this._getLocationAsync();
  }
 
  
  _getLocationAsync = async () => {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status !== "granted") {
      this.setState({
        locationResult: "Permission to access location was denied"
      });
    }

    let location = await Location.getCurrentPositionAsync({});
    this.setState({ locationResult: JSON.stringify(location) });
  };

  render() {
    const trending_events = this.props.trending_events || [];
    
   
  
    return (
      <ScrollView bounces={false} style={{ backgroundColor: "white" }}>
        <StatusBar barStyle="dark-content" />

        <View style={{ flex: 1 }}>
          <MapView
            style={{ height: ScreenStyles.height * 0.6 }}
            initialRegion={{
              latitude: this.state.locationResult,
              longitude: this.state.locationResult,
              latitudeDelta: 0.0922,
              longitudeDelta: 0.0421,
            }}

**Comment by tsapeta** [comment]
Hey @jasuno,

The location object returned by `await Location.getCurrentPositionAsync()` is described here: https://docs.expo.io/versions/v32.0.0/sdk/location#type-location

So, to get the latitude and longitude you could do
```
const location = await Location.getCurrentPositionAsync();
const { latitude, longitude } = location.coords;
```

Closing this issue, but feel free to comment here if you still has some troubles 😉
