### ISSUE TITLE
Problem EXPO 51 and Nativewind

### ISSUE THREAD

**Issue by mapacdev** [expo/expo#32062]
### Minimal reproducible example

https://github.com/mapacdev/myExpoApp

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

I using expo 51, and nativewind. I got the same error with nativewind 2 and nativewind 4

I've develop 2 apps, one for nativewind 2 and the other nativewind 4. Both app's are just and app generated using "npx create-expo-app@latest" and setting one for nativewind 2 and the other nativewind 4. I both i have the same problem

Below is my package.json file, and the

*** WITH EXPO 51 AND NATIVEWIND 2 *******************

when I "use npx expo start" using expo go or development build everything is OK, but when i use "npx expo run:android" I got the error. If I use "npx expo rund:android --variant release" I got the error

npx expo run:android
› Building app...
Configuration on demand is an incubating feature.
:ReactNative:Running '[node, D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\node_modules@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

Where:
Script 'D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\node_modules@react-native-community\cli-platform-android\native_modules.gradle' line: 401

What went wrong:
A problem occurred evaluating script.

Process 'command 'node'' finished with non-zero exit value 1

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
Get more help at https://help.gradle.org/.

BUILD FAILED in 4s
5 actionable tasks: 1 executed, 4 up-to-date
Error: D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
at ChildProcess.completionListener (D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\node_modules@expo\spawn-async\build\spawnAsync.js:42:23)
at Object.onceWrapper (node:events:634:26)
at ChildProcess.emit (node:events:519:28)
at cp.emit (D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (node:internal/child_process:1105:16)
at ChildProcess._handle.onexit (node:internal/child_process:305:5)
...
at spawnAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\node_modules@expo\spawn-async\build\spawnAsync.js:7:23)
at spawnGradleAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpo3\node_modules@expo\cli\build\src\start\platforms\android\gradle.js:96:48)
at assembleAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\node_modules@expo\cli\build\src\start\platforms\android\gradle.js:74:18)
at runAndroidAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\expo\myExpo3\node_modules@expo\cli\build\src\run\android\runAndroidAsync.js:45:37)
Please provide a reproduction of the issue using one of the following templates:

StackBlitz template: https://stackblitz.com/edit/nativewind-test?view=editor
Create Expo Stack template:
npx create-expo-stack@latest --nativewind
npx create-expo-stack@latest --nativewind --expo-router
*** WITH EXPO 51 AND NATIVEWIND 4 *******************

when I "use npx expo start" using expo go or development build everything is OK, but when i use "npx expo run:android" I got the following error. I use "npx expo rund:android --variant release" I got the error

myExpoApp> npx expo run:android --variant release

› Building app...
Configuration on demand is an incubating feature.
:ReactNative:Running '[node, D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

Where:
Script 'D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules@react-native-community\cli-platform-android\native_modules.gradle' line: 401

What went wrong:
A problem occurred evaluating script.

Process 'command 'node'' finished with non-zero exit value 1

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
Get more help at https://help.gradle.org/.

BUILD FAILED in 4s
5 actionable tasks: 1 executed, 4 up-to-date
Error: D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\android\gradlew.bat app:assembleRelease -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 exited with non-zero code: 1
Error: D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\android\gradlew.bat app:assembleRelease -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 exited with non-zero code: 1
at ChildProcess.completionListener (D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules@expo\spawn-async\build\spawnAsync.js:42:23)
at Object.onceWrapper (node:events:634:26)
at ChildProcess.emit (node:events:519:28)
at cp.emit (D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (node:internal/child_process:1105:16)
at ChildProcess._handle.onexit (node:internal/child_process:305:5)
...
at spawnAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules@expo\spawn-async\build\spawnAsync.js:7:23)
at spawnGradleAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules@expo\cli\build\src\start\platforms\android\gradle.js:96:48)
at assembleAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules@expo\cli\build\src\start\platforms\android\gradle.js:74:18)
at runAndroidAsync (D:\DEVAPP\CURSOS\REACT-NATIVE\fherrera\expo\myExpoApp\node_modules@expo\cli\build\src\run\android\runAndroidAsync.js:45:37)

Expected behavior

when using "npx expo run:android --variant release" i spect the app generated and installed in my device

Any Idea how to resolve it.

Additional context

with NATIVE WIND 4.0 **************

package.json *****************

{
"name": "myexpoapp",
"main": "expo-router/entry",
"version": "1.0.0",
"scripts": {
"start": "expo start",
"reset-project": "node ./scripts/reset-project.js",
"android": "expo run:android",
"ios": "expo run:ios",
"web": "expo start --web",
"test": "jest --watchAll",
"lint": "expo lint"
},
"jest": {
"preset": "jest-expo"
},
"dependencies": {
"@expo/vector-icons": "^14.0.2",
"@react-navigation/native": "^6.0.2",
"expo": "~51.0.28",
"expo-constants": "~16.0.2",
"expo-font": "~12.0.9",
"expo-linking": "~6.3.1",
"expo-router": "~3.5.23",
"expo-splash-screen": "~0.27.5",
"expo-status-bar": "~1.12.1",
"expo-system-ui": "~3.0.7",
"expo-web-browser": "~13.0.3",
"myexpoapp": "file:",
"nativewind": "^4.0.1",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.74.5",
"react-native-gesture-handler": "~2.16.1",
"react-native-reanimated": "~3.10.1",
"react-native-safe-area-context": "4.10.5",
"react-native-screens": "3.31.1",
"react-native-web": "~0.19.10"
},
"devDependencies": {
"@babel/core": "^7.20.0",
"@types/jest": "^29.5.12",
"@types/react": "~18.2.45",
"@types/react-test-renderer": "^18.0.7",
"jest": "^29.2.1",
"jest-expo": "~51.0.3",
"react-test-renderer": "18.2.0",
"tailwindcss": "^3.3.2",
"typescript": "~5.3.3"
},
"private": true
}

tsconfig.json ***************

{
"extends": "expo/tsconfig.base",
"compilerOptions": {
"strict": true,
"paths": {
"@/": [
"./"
]
}
},
"include": [
"/*.ts",
"/.tsx",
".expo/types/**/.ts",
"expo-env.d.ts",
"nativewind-env.d.ts"
]
}

tailwind.config.js ***************

/** @type {import('tailwindcss').Config} /
module.exports = {
content: ["./app/**/.{js,jsx,ts,tsx}",
"app/index.js",
"./App.{js,jsx,ts,tsx}",
"./components/**/*.{js,jsx,ts,tsx}",

],
presets: [require("nativewind/preset")],
theme: {
extend: {},
},
plugins: [],
}

metro.config.js ***************

// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname)

module.exports = withNativeWind(config, { input: './global.css' })

babel.config.js ***************

module.exports = function (api) {
api.cache(true);
return {
presets: [
["babel-preset-expo", { jsxImportSource: "nativewind" }],
"nativewind/babel",
], };
};

app.json ******

{
"expo": {
"name": "navigation_app",
"slug": "navigation_app",
"version": "1.0.0",
"orientation": "portrait",
"icon": "./assets/images/icon.png",
"scheme": "myapp",
"userInterfaceStyle": "automatic",
"splash": {
"image": "./assets/images/splash.png",
"resizeMode": "contain",
"backgroundColor": "#ffffff"
},
"ios": {
"supportsTablet": true
},
"android": {
"adaptiveIcon": {
"foregroundImage": "./assets/images/adaptive-icon.png",
"backgroundColor": "#ffffff"
},
"package": "com.cti.nativation_app"
},
"web": {
"bundler": "metro",
"output": "static",
"favicon": "./assets/images/favicon.png"
},
"plugins": [
"expo-router"
],
"experiments": {
"typedRoutes": true
},
"extra": {
"eas": {
"projectId": "862f4d19-e47a-4643-a055-955b7927bbe8"
}
},
"owner": "userno45"
}
}

WITH NATIVEWIND 2

package.json ********

{
"name": "myexpo3",
"main": "expo-router/entry",
"version": "1.0.0",
"scripts": {
"start": "expo start",
"reset-project": "node ./scripts/reset-project.js",
"android": "expo run:android",
"ios": "expo run:ios",
"web": "expo start --web",
"test": "jest --watchAll",
"lint": "expo lint"
},
"jest": {
"preset": "jest-expo"
},
"dependencies": {
"@expo/vector-icons": "^14.0.2",
"@react-navigation/native": "^6.0.2",
"expo": "~51.0.28",
"expo-constants": "~16.0.2",
"expo-font": "~12.0.9",
"expo-linking": "~6.3.1",
"expo-router": "~3.5.23",
"expo-splash-screen": "~0.27.5",
"expo-status-bar": "~1.12.1",
"expo-system-ui": "~3.0.7",
"expo-web-browser": "~13.0.3",
"myexpo3": "file:",
"nativewind": "^2.0.11",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.74.5",
"react-native-gesture-handler": "~2.16.1",
"react-native-reanimated": "~3.10.1",
"react-native-safe-area-context": "4.10.5",
"react-native-screens": "3.31.1",
"react-native-web": "~0.19.10"
},
"devDependencies": {
"@babel/core": "^7.20.0",
"@types/jest": "^29.5.12",
"@types/react": "~18.2.45",
"@types/react-test-renderer": "^18.0.7",
"jest": "^29.2.1",
"jest-expo": "~51.0.3",
"react-test-renderer": "18.2.0",
"tailwindcss": "^3.3.2",
"typescript": "~5.3.3"
},
"private": true
}

babel ******

module.exports = function (api) {
api.cache(true);
return {
presets: ['babel-preset-expo'],
plugins: ["nativewind/babel"],
};
};

tsconfig ******

{
"extends": "expo/tsconfig.base",
"compilerOptions": {
"strict": true,
"paths": {
"@/": [
"./"
]
}
},
"include": [
"/*.ts",
"/.tsx",
"**/.tsx",
".expo/types/**/*.ts",
"expo-env.d.ts"
]
}

tailwind.config.js ******

/** @type {import('tailwindcss').Config} */
module.exports = {

// content: ["./App.{js,jsx,ts,tsx}", ".///*.{js,jsx,ts,tsx}"],
content: ['./app//.tsx', './components/**/.tsx'],

theme: {
extend: {},
},
plugins: [],
}

app.json *****

{
"expo": {
"name": "myExpo3",
"slug": "myExpo3",
"version": "1.0.0",
"orientation": "portrait",
"icon": "./assets/images/icon.png",
"scheme": "myapp",
"userInterfaceStyle": "automatic",
"splash": {
"image": "./assets/images/splash.png",
"resizeMode": "contain",
"backgroundColor": "#ffffff"
},
"ios": {
"supportsTablet": true
},
"android": {
"adaptiveIcon": {
"foregroundImage": "./assets/images/adaptive-icon.png",
"backgroundColor": "#ffffff"
},
"package": "com.userno45.myExpo3"
},
"web": {
"bundler": "metro",
"output": "static",
"favicon": "./assets/images/favicon.png"
},
"plugins": [
"expo-router"
],
"experiments": {
"typedRoutes": true
}
}
}

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.13.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.9.0 - D:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31, 32, 33, 33, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom, android-34 | Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~51.0.28 => 51.0.37
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✖ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for issues with metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The name in your package.json is set to "myexpoapp", which conflicts with a dependency of the same name.

One or more checks failed, indicating possible issues with the project.
```

**Comment by danstepanov** [comment]
hey can you open this issue over on the NativeWind github repo? https://nativewind.dev/issue
