### ISSUE TITLE
Unable to inspect app in offline mode because of the dev-client 

### ISSUE THREAD

**Issue by frpaf** [expo/expo#32074]
### Summary

Trying to build apk which is a debug apk so that i can inspect the file system using device explorer . I have tried with the below changes to my eas.json and tried to run the command `eas build:run -p android --profile development`
![image](https://github.com/user-attachments/assets/1de33412-7044-40dd-bd7f-32a8cc07a044)

It runs the build and creates an apk when i install the dev-client is still included . I want a debug build without the dev-client so that i can check the device file system in an **offline mode**.

How do i achieve this ?

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.2.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/francisfernandes/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.26 => 51.0.26 
      expo-router: ~3.5.21 => 3.5.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: bare
```

### Reproducible demo

Unable to inspect app in offline mode because of the dev-client trying to access the app where there is no connection.

**Comment by brentvatne** [comment]
hi there! you should get rid of that gradle command. that will create a debug build of your app, which is not what you want if you want to be able to run your app without a dev server. debug builds in react native require dev servers.

**Comment by frpaf** [comment]
Hi @brentvatne , thanks for your reply. Is it possible to have a debug build without having to run the dev server . I need this to inspect certain files in the devices in offline mode ?

**Comment by brentvatne** [comment]
@frpaf - i believe what you want is a release build but just an apk? just remove that gradlecommand
