### ISSUE TITLE
error TypeError: Cannot read property 'Google' of undefined

### ISSUE THREAD

**Issue by blueturtle13g** [expo/expo#3210]
I followed expo tutorial https://blog.expo.io/google-sign-in-with-react-native-and-expo-9cac6c392f0e for using Google authentication but got this error.
this is the piece of code that throws the error:
`signIn = async () => {
    try {
      const result = await Expo.Google.logInAsync({
        androidClientId: "YOUR_CLIENT_ID_HERE",
        //iosClientId: YOUR_CLIENT_ID_HERE,  <-- if you use iOS
        scopes: ["profile", "email"]
      })
    } catch (e) {
      console.log("error", e)
    }
}`

and this is the whole code: https://github.com/lingonsaft/google-sign-in-expo-create-react-native-app/blob/master/App.js

    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"

**Comment by tsapeta** [comment]
Hey @blueturtle13g,
As of SDK32 we’ve removed the deprecated default exports from the expo package as well as certain individual modules. You’ll need to replace any usage of `import Expo from 'expo';` with destructured imports (`import { ... } from 'expo';`) and import only the modules you need. If you’d like to import all modules, use `import * as Expo from 'expo';`.
