### ISSUE TITLE
Expo router output static not working on vercel github deploy

### ISSUE THREAD

**Issue by alezanchet** [expo/expo#32139]
### Minimal reproducible example

I started a project on vercel and linked a github repo to the project and set the settings like the screenshots

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

![Screenshot 2024-10-18 014922](https://github.com/user-attachments/assets/113c60f3-d6df-4197-be84-be38b6530b6c)
![Screenshot 2024-10-18 015000](https://github.com/user-attachments/assets/77d037c1-d9ff-4352-be03-645ea49a3e6c)
![Screenshot 2024-10-18 015029](https://github.com/user-attachments/assets/91d3bd7a-4716-4ab6-a912-43de1049933e)

### Environment

```text
.
```

**Comment by alezanchet** [comment]
the index route works, but not others

**Comment by tscans** [comment]
Facing the same issue here.

**Comment by tscans** [comment]
I switched the app.json back to single-page - that works for now. Much prefer output static though.
"web": {
      "output": "single-page",
}

**Comment by alezanchet** [comment]
i did the same..

**Comment by marklawlor** [comment]
Please follow the Vercel deployment instructions and ensure you include the required `vercel.json` https://docs.expo.dev/distribution/publishing-websites/#vercel

If you believe your setup is correct please open a new issue with a reproduction so I can reproduce your issue
