### ISSUE TITLE
Error message on Expo Go (mobile) -> "Something went wrong." Sorry about that. You can go back to Expo home or try to reload the project.

### ISSUE THREAD

**Issue by Laureano139** [expo/expo#32134]
### Summary

So, I'm building my first project using expo + react-native. When I scan the QR code, after running the command "npm start" or even "npx expo start -c", I get this error message "Uncaught Error: java.net.ConnectException: Failed to connect to /(ip:port)".
If i open the app on my pc web browser, it works...idk what's wrong.

### What platform(s) does this occur on?

Android

### SDK Version

51.0.0

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^51.0.0 => 51.0.38 
      expo-router: ~3.5.9 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.6 => 0.19.13
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/Laureano139/my-react-native-app.git

**Comment by muneebahmedayub** [comment]
@Laureano139 make sure to use same network for mobile and pc

**Comment by Laureano139** [comment]
> @Laureano139 make sure to use same network for mobile and pc

I made sure...error was still showing

**Comment by brentvatne** [comment]
hello! more info here: https://docs.expo.dev/get-started/start-developing/#having-problems

**Comment by sanaarshed** [comment]
yes @brentvatne  > "npx expo start --tunnel"
this command worked for me. i have been struggling to get this issue resolved for whole day and unable to find the solution. thanks for saving my time 🙏

**Comment by thiagotfsilva** [comment]
> hello! more info here: https://docs.expo.dev/get-started/start-developing/#having-problems

thanks for saving my time too

**Comment by AIFry-Py3** [comment]
I did --tunnel next to the 'expo start'.
I was using npx in the command:

npx expo start --tunnel -y
expo start --tunnel -y  
Whichever is required for you

**Comment by AlizerUncaged** [comment]
jesus christ is it possible for expo to put the actual error instead of a vague "Something went wrong." message, it is not helpful at all
