### ISSUE TITLE
Android notifications for data-only messages not displaying after upgrading SDK 50 -> SDK 51

### ISSUE THREAD

**Issue by danbim** [expo/expo#32152]
### Minimal reproducible example

https://gitlab.holi.team/danbim/expo-notifications-bug-demo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

(We're still working on the minimal reproducible example, but have already verified it within our app, stay tuned for an update).

We have an app that receives push notifications via 2 different services (http://novu.co and Matrix Sygnal Push Gateway). The upgrade from Expo SDK 50 to SDK 51 seems to have broken how notifications are displayed in our app:

* App not running
  * SDK 50: notification is displayed to user, press opens app
  * SDK 51: notification is NOT displayed to user
* App is in background
  * SDK 50: notification is displayed to user, press opens app, background handler receives notification
  * SDK 51: notification is NOT displayed to user, background handler receive notification
* App is in foreground
  * SDK 50: notification is displayed to user, press opens app, background handler receives notification
  * SDK 51: notification is NOT displayed to user, background handler receive notification

This can be verified using the example project by sending a notification via FCM V1 API, using:

```
curl -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
     -H "Content-Type: application/json" \
     -d '{
           "message": {
             "token": YOUR_DEVICE_TOKEN,
             "data": {"title":"test title", "message":"test message"}
           }
         }' \
     https://fcm.googleapis.com/v1/projects/$FCM_PROJECT_ID/messages:send
```

Here, the payload conforms to what's documented in https://docs.expo.dev/versions/latest/sdk/notifications/#android-push-notification-payload-specification.

## Suspected change

We suspect `RemoteNotificationContent.kt` in [this change](https://github.com/expo/expo/commit/2b5752e899db1e88293825b0fa65d61fe5c41492) to be the root cause of the changed behavior.

* The [old code](https://github.com/expo/expo/commit/2b5752e899db1e88293825b0fa65d61fe5c41492#diff-cdd761897eb667fa84e18870f73fed872f1efb7c6596f71bd451afc35c4ffe78L108) parses message/title/... from `remoteMessage.data`
* The [new code](https://github.com/expo/expo/commit/2b5752e899db1e88293825b0fa65d61fe5c41492#diff-0499ba0c855fce1d45093fe78ebab33651d0999db4682245ef1a543d6b3a3819R33) parses them from `remoteMeessage.notification`.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nodenv/versions/20.11.0/bin/node
      npm: 10.2.4 - ~/.nodenv/versions/20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 31, 32, 33
        Build Tools: 29.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0, 35.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.38
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.13
    npmGlobalPackages:
      eas-cli: 12.5.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Indeed the linked commit was a regression. If you're willing to, I'll be happy to review and accept a fix. The existing code should not break though - it should primarily take the metadata from `remoteMessage.notification` and use `remoteMessage.data` as a fallback.

Thank you 🙂

**Comment by danbim** [comment]
> The existing code should not break though - it should primarily take the metadata from remoteMessage.notification and use remoteMessage.data as a fallback.

Yes, that is my understanding, too when reading about [Notification Messages](https://firebase.google.com/docs/cloud-messaging/concept-options#notifications) and [Data Messages](https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages).

I'll give it a try to fix it.

**Comment by danbim** [comment]
@vonovak In case you think it's critical (for us it is) feel free to already fix it. I will most likely not have time before Monday.

**Comment by vonovak** [comment]
@danbim please let me know if this works: https://github.com/expo/expo/pull/32162/files

TY :)

**Comment by danbim** [comment]
@vonovak Thanks! Looking at the code, it looks like it's going to work. But to verify it, it'd good to have a build. Is there some package coming out of the build pipeline I can use to verify?

**Comment by vonovak** [comment]
Hi! Please incorporate the changes manually into your project and then build. 👍

Thank you

**Comment by vonovak** [comment]
(You can use patch-package)

**Comment by danbim** [comment]
Thanks for the hint, never used it before :). Seems to work well for our app after patching and fixing a "typo" in the local patch, thanks. I left comments on the MR, one needs to be fixed for builds to work.
