### ISSUE TITLE
SDK 32 for Expokit iOS apps?

### ISSUE THREAD

**Issue by N1ghtly** [expo/expo#3217]
Hi guys, any timeline on the SDK 32 upgrade instructions for iOS expokit apps?

Great work btw, love what you guys are doing for the RN ecosystem :)

**Comment by tsapeta** [comment]
Hey @N1ghtly!
Sorry, we were having some issues with deploying docs to our site so the upgrade steps are not there yet, but you can read them here: https://github.com/expo/expo/blob/master/docs/versions/v32.0.0/expokit/expokit.md#ios-1

If you have any troubles or questions, let me know here 😉

**Comment by N1ghtly** [comment]
Aha awesome! I'll close this.
