### ISSUE TITLE
npx expo-doctor giving plugin error

### ISSUE THREAD

**Issue by yash2code** [expo/expo#32185]
### Summary

npx expo-doctor command suddenly started giving PluginError: Failed to resolve plugin for module "@bugsnag/plugin-expo-eas-sourcemaps" relative to "/Users/expo/workingdir/build"

### What platform(s) does this occur on?

iOS

### SDK Version

50

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^10.0.2 => 10.0.2
      expo: 50.0.21 => 50.0.21
      expo-router: ~3.4.10 => 3.4.10
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    npmGlobalPackages:
      eas-cli: 12.5.3
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Minimal reproducible example

> Running "expo doctor"
/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89549
  throw new (_errors().PluginError)(`Failed to resolve plugin for module "${pluginReference}" relative to "${projectRoot}"`, 'PLUGIN_NOT_FOUND');
        ^
PluginError: Failed to resolve plugin for module "@bugsnag/plugin-expo-eas-sourcemaps" relative to "/Users/expo/workingdir/build"
    at resolvePluginForModule (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89549:9)
    at resolveConfigPluginFunctionWithInfo (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89598:7)
    at resolveConfigPluginFunction (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89589:7)
    at withStaticPlugin (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:88669:70)
    at /Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:88510:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:88510:18)
    at withConfigPlugins (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:91158:47)
    at fillAndReturnConfig (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:90080:78)
    at getConfig (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:90137:10) {
  isPluginError: true,
  code: 'PLUGIN_NOT_FOUND',
  cause: undefined
}
Node.js v18.18.0

**Comment by walkev13** [comment]
Same issue

**Comment by jmacbhc** [comment]
Same

**Comment by dzpincus** [comment]
Same issue here. Any updates?

**Comment by dzpincus** [comment]
I'm only seeing this issue on Expo builds, not when running expo-doctor locally

**Comment by enagorny** [comment]
Downgrading to `npx expo-doctor@1.10.1` works

**Comment by jmacbhc** [comment]
> Downgrading to `npx expo-doctor@1.10.1` works

Works with that version.

**Comment by keith-kurak** [comment]
Hi all! We're looking into this. Would you be able to share links to your EAS Build jobs with us? You can send them right to https://expo.dev/contact and I'll get them if you don't want to share them publicly.

If there's anything notable about your setup (e.g., is it a monorepo), that'd be good to know. Thank you!

**Comment by yash2code** [comment]
> Hi all! We're looking into this. Would you be able to share links to your EAS Build jobs with us? You can send them right to https://expo.dev/contact and I'll get them if you don't want to share them publicly.
> 
> If there's anything notable about your setup (e.g., is it a monorepo), that'd be good to know. Thank you!

build id: `57e991a0-3406-4b8f-aa3e-8f783e87c92c`
Hope this helps.

**Comment by jmacbhc** [comment]
I still have the issue by running `npx expo-doctor@latest`

`PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" relative to`

**Comment by jerone** [comment]
Same for me, also for `@sentry/react-native/expo`.

Expo 52
Expo Doctor 1.12.4
`@sentry/react-native` 6.2.0

**Comment by brentvatne** [comment]
hi there! @jerone @jmacbhc - please create a new issue with a minimal reproducible example. thank you!

**Comment by keith-kurak** [comment]
@jerone @jmacbhc to echo what Brent said, I was able to reproduce this Bugsnag and another plugin at the time, but not with Sentry, so a minimal repro with Sentry would help us narrow this down and get a fix out quickly. Thanks!
