### ISSUE TITLE
Unzip / Unarchive support

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#322]
Hi, is there any support for unzipping files in Expo? probably not according #108 but I’m downloading compressed files using `NativeModules.ExponentFileSystem.downloadAsync`
and I need to unzip them in the same folder.

When I try to use react-native-zip-archive I get the following exception:

<img width="1136" alt="screen shot 2017-06-30 at 5 47 52 pm" src="https://user-images.githubusercontent.com/140472/27754352-88ad6f08-5dc0-11e7-89a5-c9e797649ef4.png">

Thanks

**Comment by nikki93** [comment]
We don't plan on including unzipping in the new FS API yet but we may do so. react-native-zip-archive works for this but it involves native code so you will have to detach, as described in: https://docs.expo.io/versions/v18.0.0/guides/detach.html

**Comment by outaTiME** [comment]
Hi @nikki93, 
it is understood thanks for your answer ... but it would be nice to have feature to not have to detach the project, thanks !!!

**Comment by nikki93** [comment]
Cool, will update you if we prioritize this feature. :)

**Comment by outaTiME** [comment]
Awesome, thanks 👍

**Comment by dikaiosune** [comment]
Hi! Please open feature requests on https://expo.canny.io. Thanks!
