### ISSUE TITLE
[android] Location.getCurrentPositionAsync hangs on simultaneous calls

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#3221]
> I found that Location.getCurrentPositionAsync() works just the first time I use the function. I was using it with no problems in one component, but after trying to call the function in another component it stared to hang (it hangs just in the second component that calls the function, the first one works normally).
> 
> edit: 
> The problem was I was rendering two components at the same time (react navigation tabs, with lazy: false), and a apparently Location.getCurrentPositionAsync() does not like to be called too quickly, I tried to delay it with a `setTimeout(
>       () =>
>         Location.getCurrentPositionAsync({}).then(location => {
>         //logic
>         }),
>       2000
>     );`
>  and now it's working.

_Originally posted by @ricpar11 in https://github.com/expo/expo/issues/946#issuecomment-453181014_

**Comment by rafaeluzzi** [comment]
I have this issue, Location.getCurrentPositionAsync() works the first time it is called, if called again quickly it will hang, on iOS it works fine and it doesn't matter how many times it get called. For now I made it work on my scenario by adding maximumAge:1800000 so for 30 minutes it will use the cached location but I would like to remove this for cases where the user is checking the app while moving

**Comment by tsapeta** [comment]
I'm now refactoring some methods of _Location_ module and this issue will be fixed after that 😉
