### ISSUE TITLE
Location.setApiKey not working (not exported from expo-location)

### ISSUE THREAD

**Issue by tbrnslv** [expo/expo#3222]
In 32.0.0 of expo Location.setApiKey is returning error that it is not a function. I checked expo-location in my node_moduls dir and find a problem. This function setApiKey is not exported (so I exported it manually directly in node_modules just as a workaround).
I currently work on linux system and cannot recompile everything to test and send commit for this issue, but I am reporting this as it can maybe help somebody who encounter same issue after updating expo version and also that somebody else can commit and fix this bug.

**Comment by tcdavis** [comment]
thanks @tbrnslv!

It looks like it should be there 🤔 https://github.com/expo/expo/blob/0d47bd766f852b3fdab1b2a6ace2c729922da28f/packages/expo-location/src/Location.ts#L265

but I can confirm it isn't being exposed in 32

**Comment by tsapeta** [comment]
Hey @tbrnslv,
I've just published a fix to npm registry. Just update `expo` package to version `32.0.1` 😉 
Sorry for the inconvenience!

**Comment by tbrnslv** [comment]
No problem, glad to help!
