### ISSUE TITLE
 How to differentiate secrets in EAS based on the environment?

### ISSUE THREAD

**Issue by vishva-simform** [expo/expo#32225]
### Summary

Currently, the Expo dashboard does not support defining secrets based on build channels; instead, secrets are shared across all channels and builds. When working with multiple environments such as development, staging, and production, you often need different secrets for each environment. The only solution is to add prefixes or suffixes to the keys in the secrets, which can then be identified in the app configuration based on the environment specified in the eas.json file.

For example, you might have the following keys in your environment files:

Development: MIXPANEL_KEY_DEV
Staging: MIXPANEL_KEY_STAG
Production: MIXPANEL_KEY_PROD
In your eas.json, you would define the staging and production profiles like this:

```
"staging": {
"extends": "base",
"distribution": "internal",
  "env": {
    "PROFILE": "staging"
  }
},
"production": {
  "extends": "base",
  "distribution": "internal",
  "env": {
    "PROFILE": "production"
  }
}
```

In the app configuration, you set up the **extra** property based on the PROFILE, which is necessary due to the differing key names in secrets:

```
const APP_ENV = process.env.PROFILE;

const ENVS = {
  development: {
    MIXPANEL_KEY: process.env.MIXPANEL_KEY_DEV
  },
  staging: {
    MIXPANEL_KEY: process.env.MIXPANEL_KEY_STAG
  },
  production: {
    MIXPANEL_KEY: process.env.MIXPANEL_KEY_PROD,
  }
};

extra: {
  ...ENVS[APP_ENV]
}
```

These environment variables in the extra property of the app configuration can be accessed using Expo constants, for example: `Constants.expoConfig?.extra as EnvConfig.`

Is there a different approach to managing secrets for various environments without relying on Expo constants to access the additional Expo config keys?

### SDK Version

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - /usr/local/bin/npm
      Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
```

### Minimal reproducible example

none

**Comment by TRIPLE-ADE** [comment]
I am interested can you assign this to me

**Comment by brentvatne** [comment]
the approach you used above could be fine for now! another approach could be to use `set-env` in eas build to re-assign env vars, such as `set-env MY_ENV $MY_ENV_STAGING` - put this in a pre-install hook. https://docs.expo.dev/build-reference/variables/#for-use-by-other-build-steps

we're working on shipping a much better version of env vars to eas, it should be coming in the next month or so
