### ISSUE TITLE
Standalone iOS crashes when launched by notification

### ISSUE THREAD

**Issue by rthernes** [expo/expo#3223]
SDK 32

We're not using Expo push notifications back end. We're using Notifications.getDevicePushTokenAsync()

Notifications are popping up successfully, but if we select a notification to launch our standalone app it crashes before our handlers are even invoked. This happens even after removing our notification handlers.

This was not happening in SDK 31

**Comment by rthernes** [comment]
iOS 12.1.2
iPhone 8, and the latest iPod Touch

Crashes also happen if a notification is received when the app is in the foreground, and before any of our handler code is run.

I suspect it might be because our notifications are very bare-bones. Here is an example of a notification that crashes:

`{
"APNS": "{\"aps\":{\"alert\": \"Test\"} }"
}`

**Comment by sjchmiela** [comment]
If so, I think the crash may come from:

https://github.com/expo/expo/blob/6cb4906ac5254bd07cf71cbc1ae5b593f9762ed3/ios/Exponent/Kernel/Services/EXUserNotificationManager.m#L56

where we try to save the notification _for later_ in a dictionary under `experienceId` key. If your notification doesn't contain a value under `experienceId` key it will be `nil` and this leads to crash.

Maybe as a quick workaround you could try adding `experienceId = "@your/experienceId"` to the notification?

**Comment by owenhope** [comment]
@sjchmiela I am having the same crash on the same line, trying to add `experienceId = "@your/experienceId"` crashes in expo as unexpected token.

**Comment by owenhope** [comment]
`- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler
{
  EXPendingNotification *pendingNotification = [[EXPendingNotification alloc] initWithNotificationResponse:response identifiersManager:self];
  if (![[EXKernel sharedInstance] sendNotification:pendingNotification] && [EXEnvironment sharedEnvironment].isDetached) {
    _pendingNotifications[pendingNotification.experienceId] = pendingNotification;
  }
  completionHandler();
}`

is also throwing on same issue.

**Comment by bernZ** [comment]
Does experienceID have to be an int? Or can we just give it a guid of some sort when we send it over? 
When do we think this fix will be implemented in the Expo SDK?

**Comment by sjchmiela** [comment]
`experienceId` should be a string, most specifically it should be `@yournick/your-app-slug`.

It should be fixed in SDK33. 🙂

**Comment by dereknelson** [comment]
@sjchmiela I'm trying to add experienceId to our APNS service, but can't seem to figure out where to do it. Would you mind taking a [look here](https://github.com/jazzband/django-push-notifications/blob/master/README.rst#sending-messages) to give me some direction when you get a chance?

**Comment by sjchmiela** [comment]
Hm, what if you try to add `"experienceId": "@yournick/appslug"` to either `extra` or `message` dictionaries?

**Comment by dereknelson** [comment]
@sjchmiela I tried both of those and neither worked, will update if I figure out a fix.  

This is a fairly significant bug - is there any way this could be pushed in an incremental fix before SDK 33? Or is there some way I can implement the fix myself and push it?

**Comment by owenhope** [comment]
@dereknelson @sjchmiela any update would be great here, kind of a blocker preventing me from shipping push notes.

Cannot seem to find a workaround as of yet.

**Comment by dereknelson** [comment]
@owenhope @bernZ @rthernes great news! many thanks to @sjchmiela who just pushed a fix to expo staging. if you run `EXPO_STAGING=1 expo-cli build:ios` it will build a version that fixes this bug.

**Comment by heyaj19** [comment]
@sjchmiela how when will this be merged to master for detached users?

**Comment by sjchmiela** [comment]
The fix will be deployed today to both ExpoKit users and production Turtles. 🙂

As a sidenote I wouldn’t really recommend using apps built by staging Turtles in production, as in general staging is used for, well, testing changes, and isn’t always in a stable state, plus apps built on staging won’t work well with OTA updates (as they would ask staging for updates), so what I would encourage you to do is to wait a couple of hours more for the fix to be deployed to production. 😅

**Comment by sjchmiela** [comment]
The fix has been deployed to iOS Turtles, try rebuilding your app with `expo build:ios`. 🎉 

For ejected users ExpoKit@`ios/2.10.4` has been released, so just update to this tag in your `Podfile` and run `pod install`. 🙂

**Comment by sven09** [comment]
> Does experienceID have to be an int? Or can we just give it a guid of some sort when we send it over?
> When do we think this fix will be implemented in the Expo SDK?

For all those that are using custom push sender and SDK 32 :
Adding experienceId to your data did work for us

https://forums.expo.io/t/solved-android-receive-data-from-a-fcm-push-notification-in-detached-app/12940/3


Section : new firebase api
```{
  "message": {
   ...
    },
    "data": {
    ...
      "experienceId": "@your_community_name/your-expo-project", // for EXPO`
      "experienceId": "your-expo-project", // for DETACHED`
    }
  }
}```
