### ISSUE TITLE
[expo-router] router.back() appends dynamic route params to initialRouteName's query params after hard refresh on modal route

### ISSUE THREAD

**Issue by gorbypark** [expo/expo#32241]
### Minimal reproducible example

https://github.com/gorbypark/router-modal-back

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

I've discovered what I believe to be an issue/bug with expo-router when using modal routes with unstable_settings/initialRouteName and dynamic path parameters.

The problem occurs when navigating back using useRouter `router.back()` from a modal route that was accessed via direct URL or browser refresh. When using router.back(),  the routes dynamic route params are incorrectly appended to the initialRouteName route's query params.

Steps to reproduce:

1. Open the provided minimal reproduction project
2. Navigate to one of the links in the index page to open a modal
3. Refresh the browser
4. Use the back link in the modal

Expected result: Return to the index route with a clean URL (`url.com`)

Actual result: Return to the index route with appended query params (`http://url.com/?thing_id=333`)

Note: This issue doesn't occur if you navigate from index to the modal and then use router.back(), only when the modal route is directly navigated to or the browser is refreshed while on that route.

First in the video is expected behaviour, then the actual results.
https://github.com/user-attachments/assets/1c1c2234-e494-4f8f-a68a-ac85eef27181

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
      Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/mhamilton/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.13 
    Expo Workflow: managed
```

**Comment by gorbypark** [comment]
I think I may have pinpointed an area to look at, at least!  I've updated the reproduction to show my idea.  The repo is very simple, and `index.tsx` and a dynamic path page `[thing_id].tsx` more or less

In the index page I am showing localSearchParams and globalSearchParams, which you can still see when the modal is open.

When the modal is opened, you will see `thing_id` as a `global search param` and not a `local search param`, which is expected because `thing_id` should be local to [thing_id].tsx

However, when you hard refresh with the modal open, both local and global search params have thing_id set on index.  I believe this means that the initialRouteName route (index.tsx in this case) is being incorrectly passed the local param of the [thing_id].tsx page. 

I'm theorizing that since url search params and dynamic route paths are more or less the same (both available on useLocal/GlobalSearchParams) that when a hard refresh happens, there is some logic that is grabbing all params (both dynamic path or url params) and setting them into state.  I think this logic doesn't take in account that there might be a "initialRouteName route" (sorry I'm not quite sure what to call this) also loaded and is adding the params to all routes instead of the just the specific route.

**Comment by marklawlor** [comment]
This is to be expected for the moment, due to an upstream issue with how React Navigation works with initial route names.

Your logic and reasoning in correct. For example `/[thing]/initial` and `/[thing]/[other].tsx`, where initial is the initialRouteName. When React Navigation first loads, and sets the initial route name, it unfortunately cannot tell that `[thing]` is shared and `[other]` should only belong to one of the routes. It gets even more complicated with URL Search Params eg `/[thing]/[other]?other=true` (does the query param also appear for the initial route).

I know this might seem like I bug, but URL navigation for native apps is a new concept. There's lots of edge cases like this where we need to discuss what the expected functionality actually is.

**Comment by gorbypark** [comment]
They closed the issue saying more or less "this is expected because react-navigation does things this way for now".

**Comment by marklawlor** [comment]
No, this is undefined behaviour that we haven't worked out what it should do

**Comment by gorbypark** [comment]
> No, this is undefined behaviour that we haven't worked out what it should do. The web doesn't have initial routes, nor does any URL navigation specification.

Hey sorry, I meant to leave that comment on a private repo that references this issue and I mixed up which tab I was typing in.  The explanation makes total sense, thanks for looking into it!
