### ISSUE TITLE
spring damping issue

### ISSUE THREAD

**Issue by ngoctuan001** [expo/expo#3228]
Im updating my expo to 32 because the version 25 is no longer supported by expo client

however, im getting this error 

[Image](https://discourse-cdn-sjc1.com/business5/uploads/expo/optimized/2X/4/4b7787c88d5f4cb9ebfb04fbe7ef9e3c3b8a8f6e_2_378x750.png)

my package.json
"dependencies": {
    "@expo/vector-icons": "^9.0.0",
    "babel-preset-env": "^1.7.0",
    "change-case": "^3.0.1",
    "expo": "^32.0.0",
    "firebase": "^4.9.0",
    "ignore-warnings": "^0.1.0",
    "lodash": "^4.17.4",
    "moment": "^2.20.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-communications": "^2.2.1",
    "react-native-dialog-input": "^1.0.5",
    "react-native-elements": "^0.19.0",
    "react-native-ignore-warnings": "^0.1.1",
    "react-native-modal": "^6.5.0",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-svg-charts": "^5.2.0",
    "react-native-vector-icons": "^6.1.0",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-stage-2": "^6.24.1",
    "eslint": "^4.15.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-expo": "^6.0.0",
    "eslint-config-rallycoding": "^3.2.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "eslint-plugin-react-native": "^3.2.1",
    "flow-bin": "^0.63.1",
    "metro-react-native-babel-preset": "^0.51.1",
    "prettier": "^1.10.2",
    "prettier-eslint": "^8.8.0"
  }

please help

**Comment by tcdavis** [comment]
I haven't seen the springDamping error before.  As a first step, I would carefully go through the [upgrade guide](https://docs.expo.io/versions/v32.0.0/workflow/upgrading-expo) for each SDK releases between 25 and 32 and make sure you didn't miss any steps

If that doesn't work, reopen an issue and fill out the issue template, most especially the minimal repro part so we have a shot at diagnosing it.
