### ISSUE TITLE
"orientation" key in app.json configuration doesn't have any effect in SDK 18

### ISSUE THREAD

**Issue by ccheever** [expo/expo#323]
Two users have reported this problem on the forum here:
https://forums.expo.io/t/how-do-i-update-the-app-after-changing-exp-json/1261/4

Here is a repo with a minimal repro: 
https://github.com/ccheever/repro-orientation-bug

Users have reported that the new runtime orientation API works, and that is a pretty good workaround for now.

As a hypothesis, it might be that adding this API made everything default to portrait.

I've only confirmed that this repros on iOS. I don't have my Android phone with me at the moment but will try to repro there when I have a chance.

I also added a note in the docs here about this bug. https://github.com/expo/universe/commit/47be5928102250f67a735c7a97e4155f54e774c1
We should remove the note when this bug is fixed.

**Comment by terribleben** [comment]
I can't repro this with an orientation test project I had already lying around. It works fine for me. I still need to try your provided repro project.

One difference is that mine is using exp.json while yours is using app.json. Maybe this regressed when we started defaulting to app.json? @brentvatne any idea if that theory makes sense?

**Comment by satya164** [comment]
@terribleben The test project I tried had `app.json` (freshly inited). But can't repro on Android or iOS, not on real devices or simulators.

**Comment by ccheever** [comment]
Hmmm.... so this is so strange.
This now works for me with my repro project. I didn't even `rm -rf node_modules` or anything.
The only things that make sense to me to explain this are:
- Some app update to the client?
- Somehow restarting/reopening the project didn't pick up new changes to app.json

**Comment by dikaiosune** [comment]
@terribleben app.json shouldn't have any effect on how keys are parsed, we treat it the same as exp.json very early in the project initialization pipeline: https://github.com/expo/xdl/blob/48c923d2c2e0fc5e023a37bd87fbd3ea329956d3/src/project/ProjectUtils.js#L207-L213

Not that it's impossible but seems unlikely to me.

**Comment by terribleben** [comment]
I was never able to repro this and haven't had any further reports since this thread was opened -- let me know if it comes up again.
