### ISSUE TITLE
`expo-router/testing-library`: Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by winghouchan** [expo/expo#32313]
### Minimal reproducible example

https://github.com/winghouchan/expo-router-testing-library-unable-to-find-node-mcve

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

See [this diff](https://github.com/winghouchan/expo-router-testing-library-unable-to-find-node-mcve/commit/8a8b430d3bb0c5cb8b47102bc52bc5bdc7d88921) for the code that demonstrates the failure.

#### Steps to reproduce

After cloning and installing dependencies of the minimal reproducible example:

1. Run `npm test`

The minimal reproducible example has a test case that:

1. Renders a component (`Index`) that contains a `Link` from `expo-router`, rendered in a router (using `renderRouter` from `expo-router/testing-library`).
2. Presses the link.
3. Asserts the pathname is that of the linked screen.

It also has another test case that is the same as the above, except the component `Index` is not rendered inside a router. This is to demonstrate that `expo-router/testing-library` may be having _some effect_.

#### Expected behaviour

In the test case titled "Fails: Unable to find node on an unmounted component.", the link is successfully pressed and should pass.

In the test case titled "Fails: TypeError: Cannot read properties of undefined (reading 'isReady')", the link is successfully pressed but the test fails because there is no router.

#### Actual behaviour

The test case titled "Fails: Unable to find node on an unmounted component." fails as the link could not be pressed due to the following error:

```
Unable to find node on an unmounted component.

  at findCurrentFiberUsingSlowPath (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:574:13)
  at ReactTestInstance._currentFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18325:17)
  at ReactTestInstance.get (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18397:19)
  at props (node_modules/@testing-library/react-native/src/user-event/utils/dispatch-event.ts:25:26)
  at getEventHandler (node_modules/@testing-library/react-native/src/user-event/utils/dispatch-event.ts:12:19)
  at emitTextPressEvents (node_modules/@testing-library/react-native/src/user-event/press/press.ts:125:16)
  at basePress (node_modules/@testing-library/react-native/src/user-event/press/press.ts:45:5)
  at Object.press (node_modules/@testing-library/react-native/src/user-event/press/press.ts:17:3)
  at wrapAsync (node_modules/@testing-library/react-native/src/helpers/wrap-async.ts:19:22)
```

The test case titled "Fails: TypeError: Cannot read properties of undefined (reading 'isReady')", the link is successfully pressed and the test fails because there is no router. This was expected.

### Environment

```text
expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 15.0.1
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.1.0 - ~/.local/share/mise/installs/node/22/bin/node
    Yarn: 1.22.19 - ~/.local/share/mise/installs/node/22/bin/yarn
    npm: 10.7.0 - ~/.local/share/mise/installs/node/22/bin/npm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    Android SDK:
      API Levels: 33, 34
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.1, 34.0.0
      System Images: android-33 | Google APIs ARM 64 v8a, android-34 | ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
  IDEs:
    Android Studio: 2023.2 AI-232.10227.8.2321.11479570
    Xcode: 16.0/16A242d - /usr/bin/xcodebuild
  npmPackages:
    expo: ~51.0.28 => 51.0.38 
    expo-router: ~3.5.23 => 3.5.23 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.74.5 => 0.74.5 
    react-native-web: ~0.19.10 => 0.19.13 
  Expo Workflow: managed
```

**Comment by winghouchan** [comment]
### A hypothesis

A hypothesis on the cause of the error is React Native Testing Library attempting to dispatch a `pressOut` event after the effects of the `Link`'s `press` event handler, which triggers a navigation, has run. As a navigation has occurred, the screen the `Link` is rendered in becomes unmounted so attempting to dispatch the `pressOut` event on the `Link` results in the error experienced.

This hypothesis is based on the following evidence:

- This line in the stack trace:
  > ```
  > at emitTextPressEvents (node_modules/@testing-library/react-native/src/user-event/press/press.ts:125:16)
  > ```
- The code for the above line in the stack trace: https://github.com/callstack/react-native-testing-library/blob/c56b223a5a2940359c27c862f3ff3cdb1fd36a55/src/user-event/press/press.ts#L125
- The addition of a log in [this commit](https://github.com/winghouchan/expo-router-testing-library-unable-to-find-node-mcve/commit/d6ac88a6dae439ec64d78f4464f10bac53b963c4) showing the navigation has occurred.

**Comment by winghouchan** [comment]
### Additional notes

This is just a dump of interesting things I've found (which may or may not be relevant):

- The implementation for React Native Test Library's user event simulation wraps each event dispatch with a call to React `act`. The stack trace shows the following calls: `Object.press` → `basePress` → `emitTextPressEvents`. `emitTextPressEvents` ([source](https://github.com/callstack/react-native-testing-library/blob/c56b223a5a2940359c27c862f3ff3cdb1fd36a55/src/user-event/press/press.ts)) calls `dispatchEvents` ([source](https://github.com/callstack/react-native-testing-library/blob/c56b223a5a2940359c27c862f3ff3cdb1fd36a55/src/user-event/utils/dispatch-event.ts)) which calls the handler for the event within a call to React `act`. This is significant because `act` ensures all state updates and effects are applied before subsequent code is run. This means the router state is updated on the `Link` `press` event and applied before the `pressOut` event handler is run.
- The following appears in `expo-router/testing-library`: https://github.com/expo/expo/blob/110158fe79a6f42a3042ba0983c20e7e4cc9598e/packages/expo-router/src/testing-library/index.tsx#L65-L70 `emitTextPressEvents` from React Native Testing Library also makes use of timer-related functions.
- Purely an observation: wrapping the contents of `emitTextPressEvents` with an async `act` call and removing calls to `wait` within that function _resolves_ the issue. I do not expect this to be the resolution.
- Given the hacking around within React Native Testing Library, I'm going to open an issue in React Native Testing Library as well, see it linked below. I'm not sure where the final responsibility will lie because I'm not totally familiar with the internals of either side.

**Comment by winghouchan** [comment]
Using the [`fireEvent` API](https://callstack.github.io/react-native-testing-library/docs/api/events/fire-event) from React Native Testing Library works around the issue as it only simulates the `press` event and not any of the other events (like `pressOut`).

**Comment by mdjastrzebski** [comment]
On a high level, it seems that the Link element get's unmounted between press events (likely between `press` and `pressOut` events. The mentioned `wait` call has a default duration of `0`, so there is no real waiting, just a chance to squeeze in some microtasks, one of which seems to get the element unmounted. 

From the RNTL side, we could check if the element is mounted before dispatching further events to it, but I am concerned whether this is a solution or would it only mask the underlying problem.

**Comment by winghouchan** [comment]
@mdjastrzebski: I was thinking about what the user would experience if there was a `pressOut` event handler and decided to check the docs on the [press events](https://reactnative.dev/docs/pressable#onlongpress) (they are the same for `Pressable` and `Text` native components):

> ### `onLongPress`
> 
> Called if the time after `onPressIn` lasts longer than 500 milliseconds. This time period can be customized with [`delayLongPress`](https://reactnative.dev/docs/pressable#delaylongpress).
>
> ### `onPress`
> 
> Called after `onPressOut`.
>
> ### `onPressIn`
> 
> Called immediately when a touch is engaged, before `onPressOut` and `onPress`.
>
> ### `onPressOut`
> 
> Called when a touch is released.

This means the event order is:

1. `onPressIn`
2. `onLongPress` (if press lasts longer than the long press delay)
3. `onPressOut`
4. `onPress` (if not long press)

However, React Native Testing Library ([source](https://github.com/callstack/react-native-testing-library/blob/main/src/user-event/press/press.ts#L113-L126)) does the following:

1. `onPressIn`
2. `onPress` | `onLongPress`
3. `onPressOut`

Testing a patch of moving the press out event handler before the press event handler locally resolves this issue for me. This doesn't solve the underlying issue that it is possible to cause the pressable to be unmounted before the last event is dispatched however it does narrow the edge cases. What do you think about this resolution as the first step? I'll close this issue and update callstack/react-native-testing-library/issues/1687 with new details and MCVE if the proposed solution is accepted.

**Comment by mdjastrzebski** [comment]
In real RN env, `pressOut` happens after `press`, so this is not an option.

**Comment by winghouchan** [comment]
> In our tests in RN env, `pressOut` happens after `press`, which contradicts the docs you linked. I will have to double check that.

Ah interesting, yes, please double check.

I also did a test with:

```
<Pressable
  onPress={() => console.log('onPress')}
  onPressIn={() => console.log('onPressIn')}
  onPressOut={() => console.log('onPressOut')}
  onLongPress={() => console.log('onLongPress')}
>
  <Text>Pressable</Text>
</Pressable>
```

For a normal press, the following was logged:

```
 LOG  onPressIn
 LOG  onPressOut
 LOG  onPress
```

For a long press, the following was logged:

```
 LOG  onPressIn
 LOG  onLongPress
 LOG  onPressOut
```

**Comment by winghouchan** [comment]
@mdjastrzebski: Back to the question of what happens to the event(s) after the component is unmounted, this test suggests the event handler still runs:

```tsx
function Component() {
  const [mounted, setMounted] = useState(true)

  const onPressOut = () => {
    console.log('onPressOut')
    setMounted(false)
  }

  const onPress = () => {
    console.log('onPress')
  }

  return (
    <View>
      {mounted && (
        <Pressable
          onPressOut={onPressOut}
          onPress={onPress}
        >
          <Text>Unmount</Text>
        </Pressable>
      )}
    </View>
  )
}
```

```
LOG  onPressOut
LOG  onPress
```

React Native Testing Library should simulate this behaviour, right? This means the following isn't feasible?

> From the RNTL side, we could check if the element is mounted before dispatching further events to it [...]

Also, what do you think about moving this conversation to callstack/react-native-testing-library/issues/1687? I'm not sure there's any for Expo's team to do.

**Comment by winghouchan** [comment]
Moving the convo to callstack/react-native-testing-library/issues/1687 and closing this issue because there's nothing for Expo's team to do.
