### ISSUE TITLE
WebBrowser.openBrowserAsync(undefined) should have a warning, not throw

### ISSUE THREAD

**Issue by hughbe** [expo/expo#3233]
```js
import { WebBrowser } from 'expo';
await WebBrowser.openBrowserAsync(undefined)
```

Expected: some sort of console warning/popup at the bottom
Actual: 
![49946791_373475226771305_1613556991915982848_n](https://user-images.githubusercontent.com/1275900/51249434-27c6cf80-198b-11e9-98ec-4303e6cd9810.jpg)

**Comment by hughbe** [comment]
Also, invalid urls throw, e.g. "await WebBrowser.openBrowserAsync("GARBAGIO")":
![50272842_1698209666991676_3388535807051563008_n](https://user-images.githubusercontent.com/1275900/51249490-5a70c800-198b-11e9-95c8-9f77c0e92241.jpg)

**Comment by tcdavis** [comment]
This is the standard client handling of errors within RN, although its getting a bit nicer :) https://github.com/facebook/react-native/pull/22242

You might be able to do something with error boundaries to get the effect you want.
