### ISSUE TITLE
ios.supportsTablet is Ignored when running expo prebuild

### ISSUE THREAD

**Issue by paomosca** [expo/expo#32344]
### Summary

app.js config: 

```{
  "expo": {
     ... other configs ...
    "ios": {
      "supportsTablet": false,
    },
   ... other configs ...
  }
}
```
Once running `expo prebuild --platform ios`

It will add iPad support to Info.plist
```
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationPortraitUpsideDown</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
```
The expected result is to get iphone support only.

I must remove the UISupportedInterfaceOrientations~ipad dictionary manually every time i run the prebuild.

### What platform(s) does this occur on?

iOS

### SDK Version

51.0.38

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
      Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.38 => 51.0.38 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.6.0
    Expo Workflow: bare
```

### Minimal reproducible example

Here the example: 
https://github.com/paomosca/test-issue-app

just run `npx expo prebuild --platform ios`

**Comment by EvanBacon** [comment]
iPhone-only support is defined via the `TARGETED_DEVICE_FAMILY` field in the pbxproj file. The `UISupportedInterfaceOrientations~ipad` setting relates to `ios.requireFullScreen`. It's my understanding that the ipad Info.plist values are stripped out of the binary or ignored when the device family does not indicate iPad support.

**Comment by sermagnus** [comment]
Same problem with production builds too

**Comment by JayzeeHuang** [comment]
@EvanBacon sorry for bothering you, but this seems back on the latest expo 52

**Comment by pankajtime123** [comment]
Same issue getting even have supportTablets: false

**Comment by zigcccc** [comment]
facing the same issue - `UISupportsTablet` is not added to the info.plist even though I explicitly set `ios.supportsTablet: false` in `app.config.ts`

**Comment by wittwerch** [comment]
same here with Expo 52.0.21. I'm using this script right now to fix my build before submitting.

````
echo "Generating iOS files..."
npx expo prebuild --platform ios --clean

# Remove the problematic iPad orientation key
echo "Removing UISupportedInterfaceOrientations~ipad from Info.plist..."
sed -i '' '/<key>UISupportedInterfaceOrientations~ipad<\/key>/,/<\/array>/d' ./ios/Mealino/Info.plist

echo "Building and submitting to App Store..."
eas build --platform ios --profile production --auto-submit
````
