### ISSUE TITLE
"Failed to load native binding" with Expo Router API Routes + `@node-rs/bcrypt`

### ISSUE THREAD

**Issue by karlhorky** [expo/expo#32350]
### Minimal reproducible example

https://github.com/karlhorky/repro-expo-router-api-routes-node-rs-bcrypt

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Similar to `bcrypt` issue: ["Unable to resolve module mock-aws-s3" with Expo Router API Routes + `bcrypt` #32383](https://github.com/expo/expo/issues/32383)

Companion issues:

- https://github.com/napi-rs/node-rs/issues/911
- https://github.com/facebook/metro/issues/1377

Hi, first of all, thanks as always for Expo and the energy you put in the ecosystem, amazing!

We are trying to use [`@node-rs/bcrypt`](https://www.npmjs.com/package/@node-rs/bcrypt) in [Expo Router API Routes](https://docs.expo.dev/router/reference/api-routes/), and we're getting some output that the native binding cannot be loaded (because it's `"undefined"`, see further below):

```
Android Bundled 852ms node_modules/expo-router/entry.js (1049 modules)
λ Bundled 443ms app/hash+api.ts (4 modules)

Metro error: Failed to load native binding

  357 |     //  - The user may need to bundle the correct files
  358 |     //  - The user may need to re-install node_modules to get new packages
> 359 |     throw new Error('Failed to load native binding', { cause: loadErrors })
      |           ^
  360 |   }
  361 |   throw new Error(`Failed to load native binding`)
  362 | }

Call Stack
  factory (node_modules/@node-rs/bcrypt/binding.js:359:11)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:277:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:184:12)
  require (node_modules/metro-runtime/src/polyfills/require.js:92:7)
  factory (node_modules/@node-rs/bcrypt/index.js:1:84)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:277:5)
  guardedLoadModule (node_modules/metro-runtime/src/polyfills/require.js:184:12)
  require (node_modules/metro-runtime/src/polyfills/require.js:92:7)
  factory (app/hash+api.ts:1)
  loadModuleImplementation (node_modules/metro-runtime/src/polyfills/require.js:277:5)
 ERROR  [SyntaxError: JSON Parse error: Unexpected character: <]
```

![Screenshot 2024-10-25 at 15 43 50](https://github.com/user-attachments/assets/b78afdf3-779f-48a5-baba-1af055fd35c6)

I think Metro is not logging out the error cause, so adapting the [`node_modules/@node-rs/bcrypt/binding.js`](https://github.com/napi-rs/node-rs/blob/ec14da02c7cf48e9c10720f7b49cbf1906e7f224/packages/bcrypt/binding.js#L353-L362) to log out `loadErrors` shows that it is using `"undefined"` as the module specifier:

```diff
if (!nativeBinding) {
  if (loadErrors.length > 0) {
    // TODO Link to documentation with potential fixes
    //  - The package owner could build/publish bindings for this arch
    //  - The user may need to bundle the correct files
    //  - The user may need to re-install node_modules to get new packages
+   console.log(loadErrors[0])
+   console.log(loadErrors[1])
+   console.log(loadErrors[2])
+   console.log(loadErrors[3])
    throw new Error('Failed to load native binding', { cause: loadErrors })
  }
  throw new Error(`Failed to load native binding`)
}
```

This is repeated 4 times:

```
λ  LOG  Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.
    at unknownModuleError (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/metro-runtime/src/polyfills/require.js:322:10)
    at loadModuleImplementation (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/metro-runtime/src/polyfills/require.js:244:11)
    at guardedLoadModule (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/metro-runtime/src/polyfills/require.js:184:12)
    at require (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/metro-runtime/src/polyfills/require.js:92:7)
    at requireNative (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/@node-rs/bcrypt/binding.js:130:16)
    at factory (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/@node-rs/bcrypt/binding.js:332:17)
    at loadModuleImplementation (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/metro-runtime/src/polyfills/require.js:277:5)
    at guardedLoadModule (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/metro-runtime/src/polyfills/require.js:184:12)
    at require (/Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/metro-runtime/src/polyfills/require.js:92:7)
    at /Users/k/p/repro-expo-router-api-routes-node-rs-bcrypt/node_modules/@node-rs/bcrypt/index.js:1:84
```

### Reproduction

- https://github.com/karlhorky/repro-expo-router-api-routes-node-rs-bcrypt

Creation steps:

1. `mkdir repro-expo-router-api-routes-node-rs-bcrypt && cd repro-expo-router-api-routes-node-rs-bcrypt`
2. `npx create-expo-app@latest .`
3. [`rm -r ./node_modules && npm install`](https://github.com/expo/expo/issues/29083#issuecomment-2162043358) (for `EMFILE` error)
4. Remove extra files
5. Configure `app.json` with `expo.web.output = "server"` and `expo.plugins[0][1] = { "origin": "http://localhost:8081" }`
6. Create a file [`app/hash+api.ts`](https://github.com/karlhorky/repro-expo-router-api-routes-node-rs-bcrypt/blob/main/app/hash%2Bapi.ts), with an [Expo Router API Route](https://docs.expo.dev/router/reference/api-routes/), using `hashSync` from `@node-rs/bcrypt`
7. Inside [`app/(tabs)/index.tsx`](https://github.com/karlhorky/repro-expo-router-api-routes-node-rs-bcrypt/blob/main/app/(tabs)/index.tsx), add a `fetch()` of the API Route inside `useFocusEffect`
8. 💥 `npm start` and observe the error after API Route bundling

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.13 
    Expo Workflow: managed
```

**Comment by EvanBacon** [comment]
This is partially mentioned in the docs under the known limitations. https://docs.expo.dev/router/reference/api-routes/#no-dynamic-imports

Our immediate goal is to support `workerd` and Cloudflare runtimes as opposed to the entire Node.js/Lambda runtime.

**Comment by karlhorky** [comment]
@EvanBacon ok great, thanks for the link!

Any way for users to work around the limitation in the meantime?

Eg. is there a way to modify the API Routes Metro configuration to use something similar to [webpack's `externals` option](https://webpack.js.org/configuration/externals/)?

> The `externals` configuration option provides a way of excluding dependencies from the output bundles.

**Comment by karlhorky** [comment]
## Workaround (use `bcryptjs` instead of `@node-rs/bcrypt`)

Instead of [`@node-rs/bcrypt`](https://www.npmjs.com/package/@node-rs/bcrypt), use [`bcryptjs`](https://www.npmjs.com/package/bcryptjs) (GitHub repo: https://github.com/dcodeIO/bcrypt.js), which is a JavaScript implementation of bcrypt instead of a native implementation (slower):

```bash
npm remove @node-rs/bcrypt
npm add bcryptjs
```

```diff
-import { hashSync } from '@node-rs/bcrypt';
+import { hashSync } from 'bcryptjs';

export function GET(request: Request) {
  const hash = hashSync('hello', 10);
  return Response.json({ hash: hash });
}
```

Results:

```
Android Bundled 1169ms node_modules/expo-router/entry.js (1090 modules)
λ Bundled 946ms app/hash+api.ts (3 modules)
 LOG  {"hash": "$2a$10$h8yYtmr.E866KjgKGlNf4.i/mBhIPawhUwB4AwNcAM5rgyw5fS/3u"}
```

![Screenshot 2024-10-27 at 16 28 34](https://github.com/user-attachments/assets/546185d6-aa89-4b8d-8730-e5315ad5d93a)

**Comment by marklawlor** [comment]
Duplicated issue. Response is here https://github.com/facebook/metro/issues/1377#issuecomment-2449853227
