### ISSUE TITLE
[SDK 52] new SDK breaks react-native-unistyles module 

### ISSUE THREAD

**Issue by advancedtw** [expo/expo#32351]
### Minimal reproducible example

https://github.com/advancedtw/uni

### What platform(s) does this occur on?

Android
### Where did you reproduce the issue?

in a development build

### Summary

Since upgrading to the latest preview version of expo sdk 52 I am unable to use react-native-unistyles.
It seems the problem is happening when trying to link the package.  

react-native-unistyles runs fine with react-native 0.76 and new arch enabled so clearly it is an issue with expo.

This issue was present in the past when EXPO_UNSTABLE_CORE_AUTOLINKING was set to 1 now it looks like it is the default. 

I've informed @jpudysz the maintainer of the module. We hope the expo team can help us understand the potential pitfall with the new module linking system to further investigate.

[react-native-unistyles related issue](https://github.com/jpudysz/react-native-unistyles/issues/321)

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 3.7.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 23.1.0 - ~/.volta/tools/image/node/23.1.0/bin/node
      Yarn: 4.5.1 - ~/.volta/tools/image/yarn/4.5.1/bin/yarn
      npm: 10.9.0 - ~/.volta/tools/image/node/23.1.0/bin/npm
      Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12483815
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.3 => 52.0.0-preview.3
      expo-router: ~4.0.0-preview.1 => 4.0.0-preview.1
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.0 => 0.76.0
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
// deps check fail but the project has been created using create-expo-app@latest --template default@beta
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, splash, ios, android, plugins.

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following packages should be updated for best compatibility with the installed expo version:
  expo-router@4.0.0-preview.1 - expected version: ~4.0.0-preview.1
  jest-expo@52.0.0-preview.1 - expected version: ~52.0.0-preview.1
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

**Comment by Kudo** [comment]
hey @advancedtw! the [repro](https://github.com/advancedtw/uni/blob/ab9de5c9a28203da847bf91fedbc90bc464dbafc/package.json) doesn't add react-native-unistyles to dependencies. wondering if that helps by `bun add react-native-unistyles`?

**Comment by vanstinator** [comment]
I'm seeing the same issue when attempting to upgrade from expo 51. `react-native-unistyles` is auto-linked on iOS, but not Android. I can't share my project, but if OP isn't able to update their example repo I can provide one next week.

**Comment by advancedtw** [comment]
@Kudo yes lol I didn't push that change but it's not the reason why it's failing. you can try again now.
it shoud look something like this. 
now the error message is usually when a project is misconfigured but even the module author had the same bug in his repro.
again I would like to stress that bare react native 0.76 is working as expected.

@vanstinator there is a visible error on android but I sometime see the styles failing to register on ios before I hot reload.
this could be a library bug tough and not related to the current issue wich looks like a android linking problem.

![err](https://github.com/user-attachments/assets/71694e93-6f9b-4a09-a1e2-a98cbf030eff)

**Comment by Kudo** [comment]
@advancedtw cool i was testing that on ios and not noticed the problem is android only. #32375 should resolve the problem.

**Comment by jpudysz** [comment]
Hey @Kudo, I’m also unable to link Unistyles locally with Expo SDK 52. I'm using the standard builder-bob template with an `examples/expo` folder. Do I need to add/change  anything else?

**Comment by Kudo** [comment]
@jpudysz good call! i didn't add [configurable local autolinking support](https://github.com/react-native-community/cli/blob/main/docs/autolinking.md#how-can-i-autolink-a-local-library), will create a pr to add the support. thanks!

**Comment by jpudysz** [comment]
Cool! Many thanks 💪

**Comment by duduCMT** [comment]
I fix this problem using the update my unistyles to version 2.20.0
