### ISSUE TITLE
MailComposer does not support attachments lacking an extension

### ISSUE THREAD

**Issue by PierFio** [expo/expo#3237]
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 11.6.0
  Yarn: 1.12.3
  npm: 6.5.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  expo: ^32.0.0 => 32.0.1
  react: 16.5.0 => 16.5.0
  react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1

### Steps to Reproduce
Calling MailComposer.composeAsync with an URI which filename has no extension.

### Expected Behavior
The mailer should open with the attached file.

### Actual Behavior
This crashes the application (see attached screen capture)
<img src="https://user-images.githubusercontent.com/11286090/51286121-9de52980-19bf-11e9-9924-4e79bed799b1.jpg" alt="screen-capture" width="300"/>

### Reproducible Demo
I have developed a small project reproducing the problem:
https://github.com/PierFio/MailComposerFails
(Tested on an iOS device with version 12.1.2)

**Comment by sjchmiela** [comment]
Hey, @PierFio! Thank you for submitting the issue. The fix has landed on master and will go out in the next release. See the fixing commit here — https://github.com/expo/expo/pull/3248/commits/3f01570ee92b8c2e4f5397dee3b9a55497de19b7.

**Comment by PierFio** [comment]
Hello, Many thanks for the quick fix.
