### ISSUE TITLE
[bare-expo][web] Bundling fails

### ISSUE THREAD

**Issue by entiendoNull** [expo/expo#32384]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/apps/bare-expo

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

I assume it must be I who simply have missed something. But just in case it's not, I figured I'd report the issue here as well.

Opening bare-expo web (`yarn start`, then `w`) gives me this error:

```
Web Bundling failed 8420ms apps/bare-expo/index.tsx (2994 modules)
Unable to resolve "@dotlottie/react-player" from "node_modules/lottie-react-native/lib/module/LottieView/index.web.js"
```

I ran into it a couple of weeks ago, but tried it again today. The issue seems to origin from a version update (6.7.0 -> 7.0.0) of lottie-react-native in this commit https://github.com/expo/expo/commit/6684b7eb37115104a626ef29115f86d0c895545c.

I tried reverting back to 6.7.0 in the `native-components-list`, which successfully bundles:
![image](https://github.com/user-attachments/assets/a4497669-40b3-426d-8647-b2f596de53d3)

But clicking Lottie in the Components-list will just render a blank page.

According to their npm page the following dependencies should be installed on 6x. On that page I don't find any other instructions for v7x. https://www.npmjs.com/package/lottie-react-native/v/7.0.0
```
yarn add @dotlottie/react-player @lottiefiles/react-lottie-player
```

Installing them and the errors are gone, but bare-expo in the browser is just a blank screen.

Checking out their GitHub (https://github.com/lottie-react-native/lottie-react-native) the instructions for web are different:
```
yarn add @lottiefiles/dotlottie-react
```

It appears `@dotlottie/react-player` has been deprecated, and the issue has been addressed in this commit https://github.com/lottie-react-native/lottie-react-native/commit/bc8b711bd93ed99878f25384efe246780beed004 where they get rid of the dependency of `@dotlottie/react-player` and replace it with `@lottiefiles/dotlottie-react`. But these changes have yet not been released.

![image](https://github.com/user-attachments/assets/d635ca9a-cbaf-4169-950d-e4be7211f308)

And version 7.0.0 on npm is still dependent on it:
![lottie-rn-7](https://github.com/user-attachments/assets/ee2df09a-a68c-4557-8f7b-8ac751f03f1c)

### On real apps

I tried using your lottie-react-native example from the docs on both on SDK51 and SDK52 apps, where it seem to work well (if the additional deps for web are installed too - this aligns well with Expo docs) :)

https://github.com/user-attachments/assets/aa7c00ea-401d-4e3a-b780-5dcb66e72690

**Comment by brentvatne** [comment]
hello! want to send a pr to fix this?

**Comment by entiendoNull** [comment]
Hi Brent, sure I've got it up and running in bare-expo now. Will submit a PR during the day.
Thanks.
