### ISSUE TITLE
axios or fetch getting network error

### ISSUE THREAD

**Issue by esolz-sovan** [expo/expo#3239]
Axios or fetch are working fine in ios for HTTPS request, but getting network error for android. 
For HTTP working fine in android and IOS both.

**Sending header:**
headers: {
			'Accept': 'application/json', 
			'Content-Type': 'application/json; charset=UTF-8',
			'cache-control': 'no-cache',
			'content-type': 'application/x-www-form-urlencoded'
		}

**catch error:**
Network Error
- node_modules\axios\lib\core\createError.js:16:24 in createError
- node_modules\axios\lib\adapters\xhr.js:87:25 in handleError
- ... 9 more stack frames from framework internals

**Handshake Simulation report**
![handshake_simulation](https://user-images.githubusercontent.com/46218951/51312095-7dc17300-1a70-11e9-9f70-6e67ad4d2b24.PNG)

App alredy running on live. Need help ASAP.

Thank you!

**Comment by vbnr** [comment]
Its strange behavior, i suggest you to test your code with some public rest api, for example this is a GET request.
"https://jsonplaceholder.typicode.com/todos/1"

**Comment by esolz-sovan** [comment]
I am going to close this issue. It was an SSL handshake issue. Thanks to all.
