### ISSUE TITLE
Expo.Constants.expoversion reports 1.17.1.108566 after upgrading to 1.18

### ISSUE THREAD

**Issue by raarts** [expo/expo#324]
when I log the Expo object I get:

```
console.log(Expo.Constants)

  appOwnership: "expo"
  deviceId: "AEDA3175-FC3A-..."
  deviceName: "My MacBook Pro"
  deviceYearClass: 2017
  expoVersion: "1.17.1.108566"
  getWebViewUserAgentAsync: function fn()
  ...
```
On the other hand `Constants.manifest.sdkVersion` reports: `18.0.0`

.. but `node_modules/expo/package.json` specifies `18.0.6` as version.

I'm particularly worried about the 1.17 though. Did I miss something while upgrading?

**Comment by jesseruder** [comment]
That's just the version number of the Expo app, unrelated to the SDK version. All of that seems fine!
