### ISSUE TITLE
CommandError: No development build () for this project is installed. Please make and install a development build on the device first.

### ISSUE THREAD

**Issue by incognos** [expo/expo#32418]
### Summary

I changed the package name of my development build in app.config.js to add a '.dev' to the development builds. prior I was not adding this - but now I cannot seem to do a yarn start 'expo start --android' even after successfully building and installing the new package with the .dev on eas... the command keeps asking for the app without the .dev

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - ~/.local/share/mise/installs/node/20/bin/node
      Yarn: 1.22.22 - ~/.local/share/mise/installs/node/20/bin/yarn
      npm: 10.9.0 - ~/.local/share/mise/installs/node/20/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.36 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.6.1
    Expo Workflow: bare
```

### Minimal reproducible example

expo start --android 

give me the error in the title

**Comment by incognos** [comment]
@byCedric there is no way to provide you with a valid repo. As I mentioned in the issue, all i did was add a `.dev` to the package name in android and now I can no longer get the development-client version running again - it was running just fine prior.

How am I supposed to provide you a sample?

**Comment by balbany** [comment]
Plus 1 with this issue.

**Comment by ozturksirin** [comment]
npx expo start worked for me

**Comment by muhammadqazi** [comment]
> `npx expo prebuild --clean` fixed this for me.

you are ejecting expo. 👀

**Comment by bimix** [comment]
> > `npx expo prebuild --clean` fixed this for me.
> 
> you are ejecting expo. 👀

no he is not.
