### ISSUE TITLE
[SDK52] React-navigation stack navigation unmounts previous screen too early

### ISSUE THREAD

**Issue by Veeksi** [expo/expo#32425]
### Minimal reproducible example

https://github.com/Veeksi/rn-navigation-problem/tree/sdk52

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

So basically migration from sdk51 -> sdk52 breaks @react-navigation/native-stack animation as we can see from below videos. 

The animation is basic 'slide_from_right' animation. The problem is that once we navigate to second screen, the second screen unmounts during animation. However when using sdk51, second screen unmounts after animation which is wanted behaviour.

Basically the code looks like this:
```typescript
import { NavigationContainer, useNavigation } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { Button, Text, View } from 'react-native';

const RNStack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <RNStack.Navigator>
        <RNStack.Screen name='First' component={First} />
        <RNStack.Screen
          name='Second'
          component={Second}
          options={{ animation: 'slide_from_right' }}
        />
      </RNStack.Navigator>
    </NavigationContainer>
  );
}

const First = (): JSX.Element => {
  const navigation = useNavigation();
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'red',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <Text>first</Text>
      <Button
        title='Go to second XD'
        onPress={() => navigation.navigate({ name: 'Second' })}
      />
    </View>
  );
};

const Second = () => {
  return (
    <View style={{ flex: 1, backgroundColor: 'blue' }}>
      <Text>second</Text>
    </View>
  );
};
```

Animation works on SDK51:

https://github.com/user-attachments/assets/58992cf8-6611-49c6-928d-f0b88eaabcb9

Animation doesn't work on SDK52:

https://github.com/user-attachments/assets/5ff03ceb-b8bf-45c9-8819-e156ac3e954d

You can test working animation that uses sdk51 on 'main' branch here: https://github.com/Veeksi/rn-navigation-problem/tree/main
Broken animation can be found on 'sdk52' branch here: https://github.com/Veeksi/rn-navigation-problem/tree/sdk52

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 31, 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google Play ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12483815
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0-preview.7 => 52.0.0-preview.7 
      expo-router: ~4.0.0-preview.4 => 4.0.0-preview.4 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.0 => 0.76.0 
      react-native-web: ~0.19.10 => 0.19.13 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~9.0.0
Found invalid:
  @expo/config-plugins@8.0.10
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.

Multiple lock files detected (yarn.lock, package-lock.json). This may result in unexpected behavior in CI environments, such as EAS Build, which infer the package manager from the lock file.

The following packages should be updated for best compatibility with the installed expo version:
  expo-router@4.0.0-preview.4 - expected version: ~4.0.0-preview.4
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

**Comment by ravenberg** [comment]
I also can confirm this issue. I was able to reproduce it by just starting a new project using the tabs template 

```
npx create-expo-app tabApp -t tabs
```

The issue is subtle on emulators, but for oled enabled devices the flash is really uncomfortable.

![whiteflash](https://github.com/user-attachments/assets/498db001-e467-49b5-b82e-1dd33e208b55)

**Comment by ravenberg** [comment]
Today I learned that using [SystemUI.setBackgroundColorAsync](https://docs.expo.dev/versions/latest/sdk/system-ui/#systemuisetbackgroundcolorasynccolor) to the same background color as the react root component will let you work around this issue.

For a nice example you can inspect the implementation in expo's react conf application: https://github.com/expo/react-conf-app/blob/main/app/_layout.tsx#L48

**Comment by Veeksi** [comment]
Seems like issue was caused by react-native-screens. See it here: https://github.com/software-mansion/react-native-screens/issues/1685

**Comment by drddavi** [comment]
This issue still hasn't been resolved,all the animations on android for navigation are broken.

Please close this repo 

`npx create-expo-app tabApp -t tabs`

and enable animation on the on any tab or stack

`   <Tabs
      screenOptions={{
        tabBarActiveTintColor: Colors[colorScheme ?? 'light'].tint,
        // Disable the static render of the header on web
        // to prevent a hydration error in React Navigation v6.
        headerShown: useClientOnlyValue(false, true),
        animation: 'fade'
      }}>`
      
      
     In most cases the screen flashes and there is excessive jank

**Comment by Odyrac** [comment]
same problem here

**Comment by poypoy252525** [comment]
same problem here, is there a solution to this?

**Comment by ravenberg** [comment]
> same problem here, is there a solution to this?

Yes, use this [SystemUI.setBackgroundColorAsync](https://docs.expo.dev/versions/latest/sdk/system-ui/#systemuisetbackgroundcolorasynccolor).

**Comment by Hydralerne** [comment]
any solutions guys ?

**Comment by Odyrac** [comment]
style same issue, expo 53
