### ISSUE TITLE
Google Map on IOS

### ISSUE THREAD

**Issue by MohsinAli987** [expo/expo#32438]
### Minimal reproducible example

no

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

Hi Expo Go Team,

I'm encountering an issue when switching my map from the default iOS map to a Google Map within my React Native project. The error message I'm receiving can be seen in the screenshot at end.

According to some experienced React Native developers, they mentioned that achieving this within Expo is not possible, and I may need to transition to a pure React Native environment. However, the documentation suggests that it should work.

Could you please help me understand what might be causing this issue and how to resolve it? I have been stuck on this problem for a month, and my main goal is to use Google Maps on iOS.

Thank you for your assistance.

![IOS Map Error](https://github.com/user-attachments/assets/0b50afdb-fa8c-4ef0-934b-51e28758353b)

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.38 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    Expo Workflow: managed

npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
```

### Expo Doctor Diagnostics

```text
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✖ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

The name in your package.json is set to "targetmaildrop", which conflicts with a dependency of the same name.

One or more checks failed, indicating possible issues with the project.
```

**Comment by Tadeo-Guerstein** [comment]
Look at this issue #31023

**Comment by bionicmaster** [comment]
For this specific case, you need to add in your app.json 
` "ios": {
     ...,
      "config": {
        "googleMapsApiKey": "your-maps-api-key"
      }`

and that's it, you need to rebuild your project (yarn run prebuild or something like that) and run again and done

**Comment by brentvatne** [comment]
hi there! you can't use google maps in expo go for ios (expo go is a sandbox with limited set of apis, you should use development builds!). you can create a [development build] (https://docs.expo.dev/tutorial/eas/configure-development-build/)after configuring it like this: https://docs.expo.dev/versions/latest/sdk/map-view/#ios
