### ISSUE TITLE
[SDK51] Error with newArch trying to build Android

### ISSUE THREAD

**Issue by bionicmaster** [expo/expo#32459]
### Minimal reproducible example

https://github.com/bionicmaster/expo51error

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

With a minimal version and with an existing project, I'm having a recurrent issue (doesn't matter if I'm on react 0.74, 0.75 or 076) when I enable the newArch, I'm having this error when I run yarn android: 
`file:///Users/miguel.velasco/ExpoProject/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:257:27 None of the following functions can be called with the arguments supplied:
public final fun requestPermissions(p0: Array<(out) String!>, p1: Int, p2: Int): Unit defined in android.app.Activity
public abstract fun requestPermissions(permissions: Array<String>, requestCode: Int, listener: PermissionListener?): Unit defined in com.facebook.react.modules.core.PermissionAwareActivity
e: file:///Users/miguel.velasco/ExpoProject/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:286:41 Type mismatch: inferred type is Array<out String> but Array<String> was expected`

and I'm not able to install the app in the simulator. If I try and build with gradlew clean && gradlew build it builds without any issues and finishes succesfully, but still not able to run it in the device.

If I change the flag to newArchitecture to off, it works without issues (But I have some packages like mmkv that require newArchitecture in on to work as expected)

Thanks for all your help

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 33, 33, 34, 34, 34, 35
        Build Tools: 28.0.3, 29.0.3, 33.0.2, 33.0.3, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.38 => 51.0.38
      react: ^18.3.1 => 18.3.1
      react-dom: ^18.3.1 => 18.3.1
      react-native: ^0.75.4 => 0.75.4
      react-native-web: ^0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 12.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Learn more: https://expo.fyi/root-expo-object
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check if the project meets version requirements for submission to app stores
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for app config fields that may not be synced in a non-CNG project
✖ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

Expected package metro@~0.80.8
Found invalid:
  metro@0.81.0
  (for more info, run: npm why metro)
Expected package metro-resolver@~0.80.8
Found invalid:
  metro-resolver@0.81.0
  (for more info, run: npm why metro-resolver)
Expected package metro-config@~0.80.8
Found invalid:
  metro-config@0.81.0
  (for more info, run: npm why metro-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "ignite"
Learn more: https://expo.fyi/root-expo-object
The following packages should be updated for best compatibility with the installed expo version:
  @shopify/flash-list@1.7.1 - expected version: 1.6.4
  react-native@0.76.1 - expected version: 0.74.5
  react-native-screens@4.0.0-beta.16 - expected version: 3.31.1
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

**Comment by brentvatne** [comment]
hi there! please read the doctor output for more information. react-native 0.76 is not compatible with sdk 51. you can use sdk 52 beta though: https://expo.dev/changelog/2024/10-24-sdk-52-beta. the full release is coming soon

**Comment by bionicmaster** [comment]
Sorry, I was doing some testing with 0.76 when I ran doctor, but basically as I mention rhis happens to me even with 0.74 & 0.75 (I even tríed with 0.76 & expo 52, but I that case I obtain the dame error in android and maps is breaking in 0.76 in iOS, then for now is not a option)

**Comment by brianw-tech** [comment]
@bionicmaster did you get a soluution to this? I am running a CLI App that uses a couple of expo modules. When I upgrade from React Native v0.74.3 to v0.76, I get a similar error as yours
