### ISSUE TITLE
[SDK52] Cannot build on android after adding expo-updates

### ISSUE THREAD

**Issue by mfazekas** [expo/expo#32456]
### Minimal reproducible example

https://github.com/mfazekas/Expo52UpdateTest

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

cd /tmp
% npx create-expo-app@latest --template blank-typescript@beta Expo52UpdateTest
% cd Expo52UpdateTest
% npx expo prebuild --clean
% npm run android

*** WORK FINE

% npx expo install expo-updates
% npx expo prebuild --clean
% npm run android
...
> Task :expo-updates:kspDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-updates:kspDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'kspDebugKotlin' (20).
  
  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation 

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.20.2/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /Users/boga/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12483815
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.10 => 52.0.0-preview.10 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.0 => 0.76.0 
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
% npx expo-doctor@latest
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, userInterfaceStyle, splash, ios, android. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

One or more checks failed, indicating possible issues with the project.
```

**Comment by fobos531** [comment]
@mfazekas

Feel free to follow these steps to install and set JDK 17 as the default one (you need to be using JDK 17, not 20):

https://github.com/expo/expo/blob/main/CONTRIBUTING.md#set-up-android

Additionally, If you recently updated Android studio, it probably messed up your JDK location.

In Android Studio, go to

Settings > Build, Execution, Deployment > Build Tools > Gradle > Gradle JDK

You need to use JDK 17 like in the example below:

![CleanShot 2024-10-29 at 21 48 18@2x](https://github.com/user-attachments/assets/287c27b8-58fa-4712-a419-edf7c8c1dcbe)

**Comment by mfazekas** [comment]
@fobos531 thanks much, yes using JDK 17 worked like a charm. Sorry for the noise!

**Comment by rranjan14** [comment]
I am still facing this issue while building the app on openjdk-17. Kotlin version being 1.8.22

<img width="1021" alt="Screenshot 2024-11-13 at 09 29 58" src="https://github.com/user-attachments/assets/f579baea-20c6-4d80-a678-213fc46afc0a">

**Comment by ZAWADBINSHARIF** [comment]
> I am still facing this issue while building the app on openjdk-17. Kotlin version being 1.8.22
> 
> <img alt="Screenshot 2024-11-13 at 09 29 58" width="1021" src="https://private-user-images.githubusercontent.com/47914095/385579529-f579baea-20c6-4d80-a678-213fc46afc0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NjUzMTUsIm5iZiI6MTczNTY2NTAxNSwicGF0aCI6Ii80NzkxNDA5NS8zODU1Nzk1MjktZjU3OWJhZWEtMjBjNi00ZDgwLWE2NzgtMjEzZmM0NmFmYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE3MTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MmMyZDMyZjA0YmU3ZWExN2FlMGI3OGEzNDMyZjdkZWJhMDA2OTc2YmE5NWYzOTZlMTY2MjRmMDhiNTBmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-9-L7HEgL1pTcXvjw0FILQFXAvJ85Pnf1EP17BVQS1c">

### ✅ Solution: 
**Don't use OpenJDK-17**. **Use Zulu JDK-17**. The Zulu JDK download link [here](https://www.azul.com/downloads/?version=java-17-lts&package=jdk#zulu)

**Comment by Ladvace** [comment]
I already have Zulu17, but I still get the same issue
