### ISSUE TITLE
"JSON Parse error: Unexpected character: <": Failing or missing API Routes return HTML response

### ISSUE THREAD

**Issue by ProchaLu** [expo/expo#32465]
### Minimal reproducible example

https://github.com/ProchaLu/expo-bumps

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When an Expo Router API Route fails or is missing, fetch requests using the `.json()` method return an unclear error message: `"JSON Parse error: Unexpected character: <"`. This happens particularly when switching from a non-Expo Router app to an Expo Router app (manual setup). The response appears to be HTML instead of JSON, leading to confusion about the root cause.

```
 ERROR  [SyntaxError: JSON Parse error: Unexpected character: <]
```

![Image](https://github.com/user-attachments/assets/cb74c51a-1aba-4c3b-b647-aae658f32456)

<img width="345" alt="Screenshot 2024-10-29 at 15 52 05" src="https://github.com/user-attachments/assets/ea54ffe4-5ee4-490c-be8c-a69c10928541">

I have also seen an alternative error message, which is very similar: 

```
Possible unhandled promise rejection (id: 0):
SyntaxError: JSON Parse error: Unexpected character: ‹
```
<details>
<summary>
Shows screenshot
</summary>
<img width="355" alt="Screenshot 2024-10-29 at 12 08 27" src="https://github.com/user-attachments/assets/f1b7e9c2-472a-45fb-b754-c99178891267">
</details> 

Repro steps:

1. `npx create-expo@latest . --template blank-typescript` (TypeScript blank template is important)
2. [`rm -r ./node_modules && npm install`](https://github.com/expo/expo/issues/29083#issuecomment-2162043358) (for `EMFILE` error)
3. Start dev server and open in emulator
4. Add Expo Router dependencies `npx expo install expo-router react-native-safe-area-context react-native-screens expo-linking expo-constants expo-status-bar`
5. Configure Expo Router in `package.json`: `"main": "expo-router/entry"`
6. Configure Expo Router in `app.json`: 
   1. `expo.scheme = 'your-app-scheme'`
   2. `expo.web.bundler = 'metro'`
   3. `expo.web.output = "server"`
   4. `expo.plugins[0][1] = { "origin": "http://localhost:8081" }`
7. Add web dependencies `npx expo install react-native-web react-dom`
7. Create a file `app/hello+api.ts`, with an [Expo Router API Route](https://docs.expo.dev/router/reference/api-routes/)
   ```tsx
   export function GET(request: Request) {
     return Response.json({ hello: 'world' });
   } 
   ```
8. Add fetch to API route to `index.tsx` screen
   ```tsx
	  useFocusEffect(
	    useCallback(() => {
	      async function fetchApiRoute() {
	        const response = await fetch('/api/hello');
	        const data = await response.json();
	        console.log(data);
	      }
	
	      fetchApiRoute().catch((error) => console.error(error));
	
	      return () => {
	        console.log('HomeScreen unfocused');
	      };
	    }, []),
	  );
   ```
 9. Starting the server with `npx expo start -c` 
 
💥 Observe error message (and no bundling of Expo Router API Routes)

```
Web Bundled 3834ms node_modules/expo-router/entry.js (573 modules)
 ERROR  [SyntaxError: JSON Parse error: Unexpected character: <]
```

Note: in trying to reproduce these steps, I have noticed that this intermittently doesn't reproduce the error. It seems that the response is cached somewhere, and restarting the development server, clearing the cache, or even cold booting Android Studio does not always resolve it

### Troubleshooting 

- restarting Android Studio
- restart Expo Go
- run Expo with  `--clear` flag
- clear `cache` on Expo Go
- reinstall Expo Go

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.38 => 51.0.38 
      expo-router: ^3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-native: 0.75.2 => 0.75.2 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed
```

**Comment by ProchaLu** [comment]
Creating a project without the `blank` template (using the default settings) does not seem to cause any issues. Starting a project with the default command below appears to work without encountering the JSON parse error:

```
npx create-expo-app@latest
```

**Comment by marklawlor** [comment]
I'm unable to reproduce this issue with the steps provided.

> This happens particularly when switching from a non-Expo Router app to an Expo Router app (manual setup) 

Can you maybe explain this in more detail

**Comment by mishrasatyapriya9** [comment]
@marklawlor,
I resolved this issue by just using axios insted of fetch to call API ,
const response = await axios.post(`${API_BASE_URL}/login/`, {
      email,
      password,
    }, {
      headers: {
        "Content-Type": "application/json",
      },
    });

    console.log("Response data:", response.data);
    return response.data;


This code works , But when i used fetch it shows this error 

![Image](https://github.com/user-attachments/assets/ad9c8558-0c37-4402-8432-acce24f98503)
