### ISSUE TITLE
Could not build module 'ExpoModulesCore'

### ISSUE THREAD

**Issue by kopposh** [expo/expo#32474]
### Summary

I am trying to integrate aepsdk-react-native (adobe), react-native-firebase into expo app with development build and facing this error. Issue is only in iOS. Android works fine

<img width="627" alt="Screenshot 2024-10-30 at 11 42 06 AM" src="https://github.com/user-attachments/assets/b6bdd73f-8b6a-4c18-a968-47f07027843f">

Both these libraries work fine if installed independently and also together in react native cli app.

FYI, Couple of changes made to podfile are:

 installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end

    # For installing AEP SDK
    installer.pods_project.targets.each do |t|
        if t.name.start_with?("AEP")
        t.build_configurations.each do |bc|
            bc.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
        end
        end
    end
       
s.ios.xcconfig  = { \"OTHER_CPLUSPLUSFLAGS\" => '-fmodules -fcxx-modules' }

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

iOS

### Package versions

"@adobe/react-native-aepassurance": "^6.0.2",
    "@adobe/react-native-aepcore": "^6.0.2",
    "@adobe/react-native-aepedge": "^6.0.2",
    "@adobe/react-native-aepedgebridge": "^6.0.2",
    "@adobe/react-native-aepedgeconsent": "^6.0.2",
    "@adobe/react-native-aepedgeidentity": "^6.0.2",
    "@adobe/react-native-aepplaces": "^6.0.2",
    "@adobe/react-native-aeptarget": "^6.0.2",
    "@adobe/react-native-aepuserprofile": "^6.0.2",
"@react-native-firebase/app": "^21.0.0",
    "@react-native-firebase/messaging": "^21.0.0",
 "expo": "^51.0.11",
    "expo-build-properties": "~0.12.3",
    "expo-dev-client": "~4.0.15",
  "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^13.3.1",
    "react-native": "0.74.5",

### Environment

```text
System:
      OS: macOS 15.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 23.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.11 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.6 => 0.19.13 
    Expo Workflow: bare
```

### Reproducible demo

1. create a basic expo app with development build
2. install the mentioned libraries and make the necessary podfile changes
3. try running the app to reproduce the issue

**Comment by benji-jo** [comment]
Is -fcxx-modules included in the project.pbxproj?
