### ISSUE TITLE
Drop unused files from react-native from node_modules

### ISSUE THREAD

**Issue by osdnk** [expo/expo#3249]
There're many useless things from react-native repo in node_modules. It's not a bug actually, but there's no need to have in locally. It makes indexing in my editor (WebStorm) is making useless job.    

### Environment

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.6.14
```
### Steps to Reproduce

1. `expo init`
2. `cd node_modules/react-native`
3. `ls`

### Expected Behavior

It will be nice to have not so many useless things here (see `react-native init`)

![image](https://user-images.githubusercontent.com/25709300/51381348-38568180-1b14-11e9-8d46-cdc89034d118.png)

### Actual Behavior

Here's everything from repo.
![image](https://user-images.githubusercontent.com/25709300/51381310-1a891c80-1b14-11e9-8fcf-5db02bb2eff8.png)

**Comment by ide** [comment]
This is how react-native is distributed. If you would like to remove these files you could write yourself a postinstall script, for example, but I don't think it's an ongoing cost that the Expo team is going to spend time during each release maintaining.
