### ISSUE TITLE
Doesn't work with react-native-admob after detaching

### ISSUE THREAD

**Issue by deadcoder0904** [expo/expo#325]
Complete issue [here](https://github.com/react-community/create-react-native-app/issues/285)

Idk if its the issue with `react-native-admob` or `expo` or `both` so I'm creating it in both places

The following errors are produced -
 
```
Warning: Native component for "RNAdMob" does not exist

Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

Warning: Native component for "RNAdMobDFP" does not exist
```

First I created a project using `create-react-native-app` which uses `Expo` then I detached using `exp detach` then I added `react-native-admob` using `yarn add react-native-admob` & then did `react-native link`

My Main File looks like this -  

```
import React from 'react';
import { Font } from 'expo';
import { StyleSheet, Text, View } from 'react-native';
import { 
  AdMobBanner, 
  AdMobInterstitial, 
  PublisherBanner,
  AdMobRewarded
} from 'react-native-admob';

export default class App extends React.Component {
  state = {
    fontLoaded: false,
  };

  componentDidMount() {
    Font.loadAsync({
      'open-sans-bold': require('./assets/fonts/OpenSans-Bold.ttf'),
    }).then(_ => this.setState({ fontLoaded: true }));
  }

  render() {
    return (
      <View style={styles.container}>
        {
          this.state.fontLoaded ? (
            <View>
              <Text style={styles.text}>
                Open up App.js to start working on your app!
              </Text>
              <AdMobBanner
                bannerSize="fullBanner"
                adUnitID="ca-app-pub-1425926517331745/4411715717"
                testDeviceID="EMULATOR"
                didFailToReceiveAdWithError={this.bannerError} 
              />
            </View>
          ) : null
        }
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    fontFamily: 'open-sans-bold'
  }
});

```

**Comment by brentvatne** [comment]
- iOS or Android?
- `Warning: Native component for "RNAdMobDFP" does not exist` seems to indicate that the `react-native link` step didn't work. This is quite possibly a bug with the react-native-admob library. Did you check their issues?

**Comment by deadcoder0904** [comment]
Hi I'm using Android

Also `react-native link` step worked perfectly as I checked `MainApplication.java` file in `android` folder

Also I did all the steps [manually](https://github.com/sbugert/react-native-admob#manual-installation) to install  `react-native-admob`

& its not a bug with `react-native-admob` because I used it with `react-native-cli` & it works fine

**Comment by deadcoder0904** [comment]
Label says Needs More Info 😕  

I think I clearly stated everything 😄 

If u want I can tell the steps to reproduce the error

**Comment by k2glyph** [comment]
I am also having same error please help it been a day. I am trying to integrate but it is not working.

**Comment by deadcoder0904** [comment]
@k2glyph Well dude its been 2 months for me 😂 
Don't worry Google Admob will get integrated in Expo by the end of 2017 as there is a [feature request](https://expo.canny.io/feature-requests/p/google-admob) till then just use `react-native-cli` 
I know `Expo` is a lot easy but you have to switch if you want to use Google Admob 
Its working with `react-native-cli`

**Comment by jolocity** [comment]
+1

**Comment by deadcoder0904** [comment]
@jolocity It wasn't working when I originally posted this issue on 2nd July. "It may" isn't the case at all. I tried with a clean slate. But the wait is over. Now its [In Progress](https://expo.canny.io/feature-requests/p/google-admob). So wait for SDK 21 😉

**Comment by deadcoder0904** [comment]
Well thank you Expo team 😘

Google Admob now available in [SDK 21](https://docs.expo.io/versions/latest/sdk/admob.html)

**Comment by jolocity** [comment]
Thanks!

**Comment by deadcoder0904** [comment]
I've made a [simple example](https://github.com/deadcoder0904/expo-google-admob) if anyone is finding it difficult to set up.
