### ISSUE TITLE
[SDK51] Error with newArch trying to build Android

### ISSUE THREAD

**Issue by bionicmaster** [expo/expo#32509]
### Minimal reproducible example

https://github.com/bionicmaster/expo51error

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

With a minimal version and with an existing project, I'm having a recurrent issue (doesn't matter if I'm on react 0.74 but his happens as well with 0.75) when I enable the newArch, I'm having this error when I run yarn android:
file:///Users/miguel.velasco/ExpoProject/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:257:27 None of the following functions can be called with the arguments supplied: public final fun requestPermissions(p0: Array<(out) String!>, p1: Int, p2: Int): Unit defined in android.app.Activity public abstract fun requestPermissions(permissions: Array<String>, requestCode: Int, listener: PermissionListener?): Unit defined in com.facebook.react.modules.core.PermissionAwareActivity e: file:///Users/miguel.velasco/ExpoProject/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:286:41 Type mismatch: inferred type is Array<out String> but Array<String> was expected

and I'm not able to install the app in the simulator. If I try and build with gradlew clean && gradlew build it builds without any issues and finishes succesfully, but still not able to run it in the device.

If I change the flag to newArchitecture to off, it works without issues (But I have some packages like mmkv that require newArchitecture in on to work as expected)

Thanks for all your help

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
      Yarn: 2.4.3 - ~/.nvm/versions/node/v18.20.2/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 33, 33, 34, 34, 34, 35
        Build Tools: 28.0.3, 29.0.3, 33.0.2, 33.0.3, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.38 => 51.0.38
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 12.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "ignite"
Learn more: https://expo.fyi/root-expo-object
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment]
hi there! this project is not minimal enough, it includes a bunch of unrelated code. please create a new project with `npx create-expo-app@latest --template blank`. also, sdk 52 beta is out now and 52 proper is coming soon so i'd recommend testing there. https://expo.dev/changelog/2024/10-24-sdk-52-beta
