### ISSUE TITLE
[expo-media-library@17]Couldn't create asset

### ISSUE THREAD

**Issue by AruSeito** [expo/expo#32526]
### Summary

- Download Picture with url (expo-file-system/next)
- Create assets,then get error (expo-media-library)

![image](https://github.com/user-attachments/assets/0d08ce8b-4fef-4c59-ae02-0da5b21ddef3)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-dev-client": "~5.0.0-preview.4",
"expo-file-system": "~18.0.0",
"expo-media-library": "~17.0.0",

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
      Watchman: 2024.09.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.13 => 52.0.0-preview.13 
      expo-router: ~4.0.0-preview.8 => 4.0.0-preview.8 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

### Reproducible demo

https://github.com/AruSeito/expo-test/blob/main/app/(tabs)/explore.tsx

Click Press me,then can get error info

![image](https://github.com/user-attachments/assets/0d08ce8b-4fef-4c59-ae02-0da5b21ddef3)

**Comment by anamorales05** [comment]
I have the same error but can´t find the solution

**Comment by ningacoding** [comment]
I'm not sure, but my Device has 97% of Storage, i'm freeing space, at the moment i'm facing the same error:

`Error: Could not create asset.`

once finished freeing storage space i'll let you know if anything change.
