### ISSUE TITLE
[SDK52] KeyboardAvoidingView glitches in projects that use react-native-reanimated on iPadOS

### ISSUE THREAD

**Issue by mhoran** [expo/expo#32546]
### Minimal reproducible example

https://github.com/mhoran/keyboard-avoiding-view-repro

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

This has been a difficult issue to trace down. First I traced the issue to a [bug](https://github.com/facebook/react-native/issues/47262) in react-native, which was fixed in 0.76.1. Then I [found](https://github.com/software-mansion/react-native-gesture-handler/issues/3192) that the issue was only reproducible when both react-native-gesture-handler and react-native-reanimated were loaded in the project. ~However, after further testing I found that the issue only happens when the two aforementioned libraries are loaded AND the project is built and run using Expo. It is not reproducible when using react-native directly.~

The provided repro shows this behavior. When running in a simulator or device, rotating the screen will show the keyboard either pushing up the main content with too much padding (simulator) or hiding the input text box completely (real device). The previous commit shows that the issue is not reproducible when using react-native directly.

~This behavior only seems to happen with both react-native-gesture-handler and the Reanimated Babel plugin loaded when built and run using Expo. If I remove react-native-gesture-handler from [index.js](https://github.com/mhoran/keyboard-avoiding-view-repro/blob/main/ReproducerApp/index.js#L1), the issue does not reproduce. Same if I [disable](https://www.npmjs.com/package/babel-preset-expo#user-content-reanimated) the Reanimated plugin, which is auto-loaded by babel-preset-expo.~

### Steps to reproduce
1. Launch the reproducer *on an iPad* with `npm run ios`
2. Focus the text input at the bottom
3. Rotate screen
4. Rotate screen again
5. Note that the text input is hidden by the keyboard

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - /opt/homebrew/Cellar/node@18/18.20.4_1/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - /opt/homebrew/Cellar/node@18/18.20.4_1/bin/npm
      Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^12.0.0-preview => 12.0.0-preview.4 
      expo: ^52.0.0-preview.13 => 52.0.0-preview.13 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### Screenshots

|Prior to rotation|After rotation|
|---|---|
|![Simulator Screenshot - iPad Air 13-inch (M2) - 2024-11-01 at 20 07 48](https://github.com/user-attachments/assets/8807061e-fd40-4960-810c-1046656b5146)|![Simulator Screenshot - iPad Air 13-inch (M2) - 2024-11-01 at 20 07 56](https://github.com/user-attachments/assets/49f271a0-8f14-45ea-9ce4-55d2fd2de92a)|

**Comment by brentvatne** [comment]
can you elaborate on what you mean by "running under Expo" - do you mean that installing the expo package and running `npx expo start` to launch metro and then load the app will cause this?

**Comment by mhoran** [comment]
Yes.

**Comment by mhoran** [comment]
I suppose a bit more than that; also build and installation (`npm run ios`), which perhaps could be different when using Expo rather than a react-native directly. In the repro, `HEAD` has Expo installed and running with `npm run ios` will show the broken behavior. `HEAD~` does not have Expo and instead is just using react-native 0.76.1 directly. Running with `yarn run ios` at `HEAD~` does not reproduce.

**Comment by mhoran** [comment]
I do not have enough knowledge of Expo itself to understand what could be different about the build; however, the [fix](https://github.com/facebook/react-native/commit/e271b23fad89e1e7da2e91a8f1e5cbb295406c74) for https://github.com/facebook/react-native/issues/47262 was a change to `RCTAppDelegate.mm`.

This is included in react-native 0.76.1, which is required by the latest version of SDK 52 (and correspondingly is in the package-lock.json and my local `node_modules`). But perhaps something needs to change in Expo itself to pick up the above change?

**Comment by brentvatne** [comment]
ah good catch @mhoran!

@gabrieldonadel - it looks like we need to port https://github.com/facebook/react-native/commit/e271b23fad89e1e7da2e91a8f1e5cbb295406c74#diff-b7fda5d350ac535115fa683faa7317b43aa11f3448f95266ef9ff051c3753a6fL68 over but it's not as simple as putting it in our template like this unfortunately, and may require changes in EMC/updates/dev-client/go 🥵

**Comment by mhoran** [comment]
I did a bit more digging and it looks like this is the complete change that needs to be pulled in to Expo: https://github.com/facebook/react-native/commit/61861d21ff71a9451019e0f98e0c0414cf12c153. The previously linked diff is just a fix for a regression introduced in https://github.com/facebook/react-native/commit/391680fe844aad887e497912378c699aed13464b#diff-b7fda5d350ac535115fa683faa7317b43aa11f3448f95266ef9ff051c3753a6fL63.

**Comment by mhoran** [comment]
Unfortunately it seems that the react-native patch above is a red herring. I believe I've confirmed that Expo does follow this code path. It looks like this super call bubbles up to the corresponding method in `RCTAppDelegate`: https://github.com/expo/expo/blob/00a55ba5ae4703c92a479d8714f3fe67df1ac0cb/packages/expo-modules-core/ios/AppDelegates/EXAppDelegateWrapper.mm#L59

As such, when I add a debug log in `RCTAppDelegate`, I see that the following method is called: https://github.com/facebook/react-native/blob/v0.76.1/packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm#L130-L136.

However, the issue persists. It seems to require this combination of libraries (react-native-gesture-handler and react-native-reanimated.) I see the same dependencies in issue #32575.

I'll keep digging, but it's back to square one.

**Comment by mhoran** [comment]
I've managed to trace this down to the fact that the [onLayout](https://github.com/facebook/react-native/blob/v0.76.1/packages/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L118-L134) handler in `KeyboardAvoidingView` eventually stops firing (after one rotation on a real device, or two rotations in the simulator.) This causes `_relativeKeyboardHeight` to calculate the wrong height due to a stale [frame height](https://github.com/facebook/react-native/blob/v0.76.1/packages/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L101-L103). As such, the height is [set](https://github.com/facebook/react-native/blob/v0.76.1/packages/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L171) to 0 and no padding is applied.

This `onLayout` is a bit concerning and is not limited to `KeyboardAvoidingView`. It seems that any Expo project using react-native-gesture-handler and react-native-reanimated will eventually stop firing `onLayout`. This issue is limited to the **New Architecture**. If I switch to the old architecture, the issue does not reproduce.

At this point I'm not sure where else to look, but I'm fairly certain there is some interaction between Expo and the aforementioned libraries. I'm not able to reproduce the `KeyboardAvoidingView` nor the `onLayout` event issue when using react-native directly.

**Comment by mhoran** [comment]
I've further isolated this issue to what looks like a [bug](https://github.com/software-mansion/react-native-reanimated/issues/6684) in react-native-reanimated. I'm also found a way to reproduce [without](https://github.com/mhoran/keyboard-avoiding-view-repro/compare/react-native) using Expo, so I no longer believe this is Expo specific.

**Comment by chrfalch** [comment]
Thanks for reporting back, @mhoran - we'll keep this one open to track progress in the REA bug.

**Comment by brentvatne** [comment]
@chrfalch - ah i just saw your comment here. let's just close this for now rather than mirroring the issue from reanimated. if this is pulled in as a patch release to reanimated, then it will be supported by our sdk 52 version range for the library: `~3.16.1`

**Comment by brentvatne** [comment]
@flochtililoch - you can use [expo.install.exclude](https://docs.expo.dev/versions/latest/config/package-json/#exclude) to skip validation of any package you like and switch over to another version. 3.17.0 will likely work fine

**Comment by ahamill-eversana** [comment]
I'm using 3.17.0 in my development build and am still seeing the keyboard animation issue.

**Comment by flochtililoch** [comment]
Issue is still present with SDK53 as far as I can tell
