### ISSUE TITLE
[SDK 52] [expo-image] SVG not appear on iOS

### ISSUE THREAD

**Issue by Randall71** [expo/expo#32556]
### Minimal reproducible example

https://github.com/Randall71/expo-image-svg-bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

When I use some svg with expo-image, the rendering does not appear on iOS.
On Android everything is correct.
I found an issue that dealt with this [https://github.com/expo/expo/issues/23669](bug) already so I took the latest version of the lib to see and the problem still persists

![CleanShot 2024-11-03 at 04 24 48@2x](https://github.com/user-attachments/assets/9b51a73b-fb17-4c25-9dce-f1e9b93bc511)

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.6.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31, 34, 35
        Build Tools: 30.0.3, 31.0.0, 34.0.0, 35.0.0
        System Images: android-34 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a, android-35 | Pre-Release 16 KB Page Size Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.16 => 52.0.0-preview.18 
      expo-router: ~4.0.0-preview.11 => 4.0.0-preview.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.5.4
      expo-cli: 6.3.12
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Validate packages against React Native Directory package metadata
```

**Comment by brentvatne** [comment]
@Randall71 - there are differences between the svg renderers using on ios and android and so you may encounter cases where there is some inconsistency. i'd suggest using a different svg image for now. @Kudo will investigate

**Comment by Kudo** [comment]
hi there! yes as you mentioned, this is related to #23669. SDWebImage has compatibility issue for svg files. however, i took a further look for your svg. in you case, the [svg](https://github.com/Randall71/expo-image-svg-bug/blob/main/assets/images/logo-facebook.svg?short_path=b9040a9) literally does nothing but only embed a png file. maybe you could try to use a png directly. even with the better compatible [SDWebImageSVGNativeCoder](https://github.com/SDWebImage/SDWebImageSVGNativeCoder), this svg is not rendered. i think it may have some compatibility problem inside the embedded base64 png.

i would close this issue and keep #23669 since this is duplicated. feel free to let me know if you have other svg files coming with rendering problems.

**Comment by alirezakasirzare** [comment]
i have same issues

**Comment by benounnas** [comment]
i have some svg that doesn't render properly at all because of these filters:
```
"FeComponentTransfer",
  "FeConvolveMatrix",
  "FeDiffuseLighting",
  "FeDisplacementMap",
  "FeFuncA",
  "FeFuncB",
  "FeFuncG",
  "FeFuncR",
  "FeImage",
  "FeMorphology",
  "FePointLight",
  "FeSpecularLighting",
  "FeSpotLight",
  "FeTile",
  "FeTurbulence"
```
