### ISSUE TITLE
Expo export cannot show image assets

### ISSUE THREAD

**Issue by vantuan88291** [expo/expo#32550]
### Summary

I am using this command to export the bundle with assets:
`expo export --platform android / ios`
however it not look like rn cli:
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/output/index.android.bundle --assets-dest android/output`

when export bundle in expo, it include mapping.json and assets folder, but with react-native bundle command doesn't have mapping file, seem the mapping inside index.android.bundle already, no need mapping file.

For example in android, I want to export js bundle to replace into `getJSBundleFile`, expo generate a `.hbc` file, and I point that file into `getJSBundleFile`, it working but no image assets can show, I already put all assets folder with mapping file in the same path of `.hbc` file.
I did that same thing in react-native cli when using this command `react-native bundle --platform ...` and it working, can show image... because index.android.bundle already have mapping in there.

For export export, how can I use getJSBundleFile and make image can show in android?

For iOS is the same issue but I just want give example on android first.
Thanks 

### Environment

```text
production
```

### Minimal reproducible example

expo export --platform android / ios

**Comment by brentvatne** [comment]
hey @vantuan88291! can you explain what exactly you're trying to accomplish at a higher level? when you run a build in a project that uses expo cli for bundling, we run `npx expo export:embed -p [platform]`, and you shouldn't ever need to run this yourself

**Comment by vantuan88291** [comment]
> hey @vantuan88291! can you explain what exactly you're trying to accomplish at a higher level? when you run a build in a project that uses expo cli for bundling, we run `npx expo export:embed -p [platform]`, and you shouldn't ever need to run this yourself

Hi, i want to self host a tool that can update the bundle via remote, like expo updates. But i do it by myself, my own server. So i just need run export:embed?

**Comment by vantuan88291** [comment]
I resolve that by using expo export:embed, I will close this issue. Thanks
