### ISSUE TITLE
expo-contacts crashes on getContactsAsync

### ISSUE THREAD

**Issue by pif-tech** [expo/expo#32568]
### Minimal reproducible example

https://snack.expo.dev/@piftech/75ecdf

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

the basic example https://snack.expo.dev/@piftech/75ecdf doesn't work on my iPhone 13 with 3978 contacts but works fine on my android with same contact size. App crashes on this line 

```
const { data } = await Contacts.getContactsAsync({
  fields: [Contacts.Fields.Emails],
});
```

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
      Watchman: 2024.07.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/lib/ruby/gems/3.3.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 31, 33, 33, 34, 35
        Build Tools: 30.0.3, 33.0.2, 34.0.0
        System Images: android-UpsideDownCake-ext5 | Google APIs ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.38 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.13 
      react-navigation: ^5.0.0 => 5.0.0 
    npmGlobalPackages:
      eas-cli: 12.6.2
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by pif-tech** [comment]
@EvanBacon please help

**Comment by alanjhughes** [comment]
@pif-tech - I've just tried your example and have no issue on both the simulator and my own iPhone 13
![Simulator Screenshot - iPhone 16 - 2024-11-07 at 10 44 10](https://github.com/user-attachments/assets/e807b722-9e5e-433f-8912-10ae9b8ee24f)

**Comment by pif-tech** [comment]
How many contacts please? @alanjhughes 
I only experience it when contacts are much

**Comment by alanjhughes** [comment]
@pif-tech sub 300. Is 4000 and real number or have you loaded these yourself? Seems unusually high.

**Comment by pif-tech** [comment]
my contact is that much
and some of our app user complained about it. What I find common to them is their volume of contact

**Comment by pif-tech** [comment]
@alanjhughes

**Comment by alanjhughes** [comment]
@pif-tech seems like your hitting some OS limit for how many can be returned at once. Apple has some strict restrictions around accessing contacts so that's not too surprising. Likely some kind of paging will be required.

**Comment by pif-tech** [comment]
How do you suggest I do that please?

**Comment by alanjhughes** [comment]
@pif-tech you can use the `pageSize` and `pageOffset` properties when making the query. Something like this

```typescript
const pageOffset = restart ? 0 : contacts.length || 0;
const pageSize = restart ? Math.max(pageOffset, 100) : 100;

const payload = await Contacts.getContactsAsync({
   fields: [Contacts.Fields.Emails],
  pageSize,
  pageOffset,
});
```

**Comment by pif-tech** [comment]
any doc for this?
where will I import restart from?
@alanjhughes

**Comment by alanjhughes** [comment]
@pif-tech There is no restart import. It's just a boolean. You'll have implement this based on your needs. This was just some example code.

**Comment by pif-tech** [comment]
I see. Thank you

**Comment by pif-tech** [comment]
Let me try this
