### ISSUE TITLE
Expo orientation: "portrait" setting not locking app to portrait on iPads

### ISSUE THREAD

**Issue by HaodanOgoki** [expo/expo#32566]
### Minimal reproducible example

https://github.com/HaodanOgoki/NewReactNativeApp.git

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When setting "orientation": "portrait" in app.json, the app correctly locks to portrait mode on iPhones and Android devices. However, on iPads, the app still rotates, ignoring the portrait-only setting. This occurs despite using the ScreenOrientation API in expo-screen-orientation to programmatically enforce portrait mode. The app continues to allow rotation on iPads, which disrupts the intended user experience.

Steps to Reproduce:

Create a new Expo project (or open an existing one).
Set "orientation": "portrait" in app.json.
Run the app on an iPad device or iPad simulator.
Rotate the iPad to landscape mode.

### Environment

```text
System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.8.3 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.10.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.38 => 51.0.38 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    Expo Workflow: managed


Environment:

Expo SDK Version:  "expo": "^51.0.38"
Expo CLI Version: 6.3.10
Device(s): iPad 
OS Version: 17.6.1
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by ahmad-crossplatform** [comment]
1+ 

Trying to lock it programatically will give you the following:  

Error: Calling the 'lockAsync' function has failed
→ Caused by: This device does not support the requested orientation: all

**Comment by behenate** [comment]
@HaodanOgoki 
Hi, this is a known issue with iPadOS. Your app has to have split view disabled by setting `requireFullScreen` to `true` for your app in order for the orientation to work. See the docs [here](https://docs.expo.dev/versions/latest/sdk/screen-orientation/#warning) and [here](https://docs.expo.dev/versions/latest/sdk/screen-orientation/#example-appjson-with-config-plugin)

@ahmad-crossplatform "all" will not work for most devices afaik, most declare themselves as not supporting the portrait down orientation which is included in "all". You can try using .default instead, which is all orientations except for the portrait down orientation

**Comment by ahmad-crossplatform** [comment]
@behenate  , the error is gone but unfortunatily it does not lock the screen . I am testing it in iOS simulater 17.2

**Comment by muratbiyik-dev** [comment]
I found a solution. 

You need to use infoPlist inside the ios object to specify iPad orientations.

**app.json**
```json
    "ios": {
      "supportsTablet": true,
      "requireFullScreen": true,
      "infoPlist": {
        "UISupportedInterfaceOrientations~ipad": [
          "UIInterfaceOrientationPortrait",
          "UIInterfaceOrientationPortraitUpsideDown"
        ]
      }
    },
```

**Comment by Yurii-Lutsyk** [comment]
> 1+
> 
> Trying to lock it programatically will give you the following:
> 
> Error: Calling the 'lockAsync' function has failed → Caused by: This device does not support the requested orientation: all

Thank you!!! You saved my life!!!
