### ISSUE TITLE
[SDK 52] Using a /src/app folder prevents Expo Router from finding the app directory

### ISSUE THREAD

**Issue by JamesHyot** [expo/expo#32587]
### Minimal reproducible example

https://github.com/JamesHyot/expo52

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

There's 4 branches in the repo :
- [main-working branch, pnpm with /app folder, OK](https://github.com/JamesHyot/expo52/tree/main-working)
- [main branch, pnpm with /src/app folder, NOK](https://github.com/JamesHyot/expo52/tree/main)
- [main-yarn branch, yarn with /app folder, OK](https://github.com/JamesHyot/expo52/tree/main-yarn)
- [main-yarn-broken branch, yarn with /src/app folder, NOK](https://github.com/JamesHyot/expo52/tree/main-yarn-broken)

Started from 
`npx create-expo-app --template default@beta`

1. deleted the package-lock
2. changed packageManager to "pnpm@7.2.0" in package.json
3. Got through https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build&platform=android&device=simulated&buildEnv=local to be able to run `npx expo run:android`
    - I had a lot of issues making the default template work, probably due to running this on Windows :
           - ran into [this issue](https://github.com/expo/expo/issues/31403). I ended up searching through my node_modules for the Paths.js file to modify it like [this reply](https://github.com/expo/expo/issues/31403#issuecomment-2432939844). My file wasn't in the same folder but here node_modules.pnpm@expo+config@10.0.2\node_modules@expo\config-plugins\build\android\Paths.js
           - had to choco install ninja as it seems that a recent version is required to be able to use [this workaround](https://github.com/ninja-build/ninja/issues/1900#issuecomment-1817532728). I haven't commited the change to android/app/build.gradle but I did make the change locally
           - had to create a copy of `\android\app\src\main\res\drawable\splashscreen_logo.png` and rename it to `\android\app\src\main\res\drawable\splashscreen.png`
           - had to add a dev dependency to @babel/runtime (^7.25.0) as it led to a runtime issue
    - ran `npx expo install expo-dev-client`
 4. run `npx expo run:android` and see a working app, commited this onto [main-working branch](https://github.com/JamesHyot/expo52/tree/main-working)

5. Move `/app`, `/assets`, `/components`, `/constants`, `/hooks` into a top level /src directory,  modify app.json to add `/src` to all assets paths and updated the tsconfig:

```
"paths": {
  "@/*": [
    "./src/*"
  ]
}
```

6. ran `npx expo run:android` and see the error from attached screenshot, commited this onto [main branch](https://github.com/JamesHyot/expo52/tree/main)

<img width="138" alt="qemu-system-x86_64_oRcmREo7FV" src="https://github.com/user-attachments/assets/2d7cd998-09de-4a50-b727-af84889ffa95">

7. started back from main-working branch, changed package.json to replace packageManager with yarn@1.22.22, cleaned, installed, go through the issues of step 3. again, ran `npx expo run:android` and see a working app screen, commited this onto [main-yarn branch](https://github.com/JamesHyot/expo52/tree/main-yarn)

8. go through step 5. again, ran `npx expo run:android` again and see the error from previous screenshot, commited this onto [main-yarn-broken branch](https://github.com/JamesHyot/expo52/tree/main-yarn-broken)

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 34.0.0, 35.0.0, 35.0.0
        System Images: android-VanillaIceCream | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-233.14808.21.2331.11709847
    npmPackages:
      expo: ~52.0.0-preview.16 => 52.0.0-preview.18
      expo-router: ~4.0.0-preview.11 => 4.0.0-preview.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

**Comment by JustJoostNL** [comment]
Can confirm this, I have the exact same issue.

**Comment by JustJoostNL** [comment]
Is there any update on this? I don’t want to push, but I believe this is affecting a lot of users. Currently everyone who uses the `src/app` directory (quite some people seem to do) is unable to use SDK52.

**Comment by lostpebble** [comment]
Yep, this is a pretty big annoyance. I expect everyone who uses `expo-router` and React Native 0.76+ (which we are forced to use newer Expo versions and `expo-router` versions) are being affected by this bug. I've had to move my routing code back to `/app` now.

**Comment by JustJoostNL** [comment]
Yeah I may need to move my code to `/app` temporary too, not great though. If anyone knows a temporary workaround (like a patch), please let me know.

**Comment by maboul6** [comment]
I have the same issue and it is very frustrating for our team. Would be great if it could be fixed soon!

**Comment by max-la-menacee** [comment]
Is there any update on this? Expo doc states that having our app folder in src/ should work "out of the box" but since sdk v52 update, nothing is working.

**Comment by VagnerNerves** [comment]
I'm having the same issue. if the app folder is inside src, the route is not recognized in SDK 52. The documentation still mentions it's possible to place it in the src folder - https://docs.expo.dev/router/reference/src-directory/. 
Any idea on when this might be fixed or if there’s a way to adjust it?

**Comment by brentvatne** [comment]
@JustJoostNL - #32792 has been released now, can someone confirm this resolves the issue for them?

**Comment by VagnerNerves** [comment]
> @JustJoostNL- #32792 foi lançado agora, alguém pode confirmar se isso resolve o problema para eles?

@brentvatne It’s resolved. I updated the dependencies and ran it, and now it seems to be okay.

![ok app src](https://github.com/user-attachments/assets/96f52228-cd3e-44fd-8288-7b47daf4b1e6)

**Comment by brentvatne** [comment]
thank you @VagnerNerves! sorry for the trouble

**Comment by DanielAdari** [comment]
I'm still encountering this issue,
The CLI says `Using src/app as the root directory for Expo Router.`
But still uses the `./app` directory.

**Comment by JamesHyot** [comment]
On my end the issue has correctly been resolved, thank you
