### ISSUE TITLE
Published typescript definitions don't cover the full sdk

### ISSUE THREAD

**Issue by martintreurnicht** [expo/expo#3259]
SDK 32 has way worse typing than what came from `@types/expo` I'm getting the following error:

### Environment
Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.18 => 16.7.20
      @types/react-native: ^0.57.7 => 0.57.29
      @types/react-navigation: ^2.13.5 => 2.13.5
      expo: ^32.0.1 => 32.0.1
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.3 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

1. create typescript expo project
2. create following file:
```typescript
import { Notifications } from 'expo'

Notifications.addListener(async (notification: Notifications.Notification) => {
         // handle the notification here
})
```
3. build or run tsc

### Expected Behavior

Builds or compiles without errors

### Actual Behavior

Get the following error:
```console
cannot find namespace 'Notifications'
```
This works perfectly in SDK 31

**Comment by tcdavis** [comment]
Probably best to hold of on publishing any types until we've converted the rest of the sdk

**Comment by ide** [comment]
For SDK 32 we published a patch version that excludes the TS declarations. In a future SDK we will turn them back on. The types will be different from `@types/expo` in several ways.
