### ISSUE TITLE
Method downloadAsync didn't throw error on 404

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#326]
Hi guys,
Im using the undocumented `NativeModules.ExponentFileSystem.downloadAsync` method took from https://github.com/expo/expo-sdk/blob/master/src/Asset.js to download some images from remote server, but when resource not found (404) in remote not exception is thrown, is there any way to intercept this? 

Thanks !!!

**Comment by nikki93** [comment]
Good catch, will test this for upcoming SDK version.

**Comment by nikki93** [comment]
https://github.com/expo/test-suite/commit/54b4e1e8146af7585a29803abf260953e029c62d#diff-c52f67fda6af9227fe9e3df39fae7107R418 will be available in upcoming SDK version!

**Comment by outaTiME** [comment]
Hi again @nikki93, I saw that the new SDK has the status, but I do not know if it is entirely useful for my case.

If the file I am trying to download does not exist, it should not be downloaded and I should be notified.

At the moment I have to verify if the status code is 404 and delete the file downloaded from disk and it is very annoying.

How can you handle this type of case so that if the resource does not exist, do not download and download error?

Something like https://github.com/expo/expo/issues/1169 related, thanks !!!
