### ISSUE TITLE
[SDK 52] Asset Bundling does not work on web

### ISSUE THREAD

**Issue by C2thehris** [expo/expo#32611]
### Minimal reproducible example

https://github.com/C2thehris/asset-bug

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Whenever I try to import an image from my "assets" folder, I get the following error:
Metro error: Module "[object Object]" is missing from the asset registry

  1 | import { Asset } from "expo-asset";
  2 |
> 3 | export default Asset.fromModule(require("./images/react-logo.png"));
    |                      ^
  4 |

This only happens on the web platform, other platforms work just fine. The issue only happens in expo 52.

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.11 Arch Linux
      Shell: 5.2.37 - /bin/bash
    Binaries:
      Node: 23.1.0 - /usr/bin/node
      Yarn: 1.22.22 - /usr/bin/yarn
      npm: 10.9.0 - /usr/bin/npm
    IDEs:
      Android Studio: AI-242.23339.11.2421.12483815
    npmPackages:
      expo: 52.0.0-preview.18 => 52.0.0-preview.18 
      expo-router: ~4.0.0-preview.12 => 4.0.0-preview.12 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.10 => 0.19.13 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-web
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by C2thehris** [comment]
It seems that the bundler is resolving the "require" statement to an object of the following format when bundling for web:
{
  "uri": ...,
  "width": ...,
  "height": ...,
}

On other platforms (and the previous release of expo), it is bundling it as a module number.

**Comment by Kudo** [comment]
that's kind of a breaking change from #31955. but overall it would benefit web support for just use `<img src={require("./images/react-logo.png").uri} />`. does the breaking change introduce any difficulty from you?

**Comment by C2thehris** [comment]
Doesn’t really introduce too much difficulty, as I’m early in my project and don’t have too many assets to update.

This
