### ISSUE TITLE
[SDK52]The APK file compiled using SDK 52 lacks signature information, causing the third-party SDK to fail authentication based on the signature.

### ISSUE THREAD

**Issue by gt-sunwangcheng** [expo/expo#32638]
### Minimal reproducible example

https://github.com/gt-sunwangcheng/expo52-signature-leak-android

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

After running yarn android on SDK 52, when I use keytool and jarsigner to display the signature information of app-debug.apk, both show that there is no signature information. However, it works on SDK 51. Command: jarsigner -verify -verbose -certs app-debug.apk 
![image_ea77358a-2b76-4406-842a-3deb386dc818](https://github.com/user-attachments/assets/1761c87b-b285-4019-8713-6e75507040e8)

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.10.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 23, 28, 31, 32, 33, 34, 35
        Build Tools: 28.0.3, 29.0.2, 30.0.3, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0-preview.21 => 52.0.0-preview.21 
      expo-router: ~4.0.0-preview.11 => 4.0.0-preview.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.6.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✖ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by gt-sunwangcheng** [comment]
![image_714b44b2-f585-4615-9955-a5c8c1f4d908](https://github.com/user-attachments/assets/e55dad3c-8ab6-478f-8081-516b1bced072)
This screenshot shows that the APK file compiled with expo52 is missing the cert file.

**Comment by gt-sunwangcheng** [comment]
![image_f5c0de7a-3cf4-4531-a42e-bf157b0aa001](https://github.com/user-attachments/assets/acaae392-1428-4027-bd71-ac3a889c392c)
When I compile with expo51, the APK file contains the cert file

**Comment by gt-sunwangcheng** [comment]
My project has integrated some third-party SDKs that verify using the configured signing information. After switching to expo52, the signing information is lost, causing the third-party SDKs to be unusable.

**Comment by Kudo** [comment]
@gt-sunwangcheng the META-INF cert files are for the apk signature scheme v1. jarsigner only supports the v1 signer. you should use `apksigner verify --print-certs app/build/outputs/apk/debug/app-debug.apk` to verify the apk.

expo sdk 52 bumped the minSdkVersion to 24. from minSdkVersion 24, the apk will disable apk signer v1 by default.
you can use `v1SigningEnabled` to enable that anyway

```gradle
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
            v1SigningEnabled true
        }
    }
```

reference:
- https://stackoverflow.com/a/75277846
- https://source.android.com/docs/security/features/apksigning/v2

**Comment by Kudo** [comment]
i'm closing this because this is not a valid issue. but i'm happy to answer question further. thanks!

**Comment by arielscht** [comment]
Adding v1SigningEnabled to signingConfigs did not work for me, it seems to be ignored. 

I also tried enableV1Signing because I saw it in this issue: https://issuetracker.google.com/issues/134858541?pli=1

But it did not work as well.

I had to manually use apksigner to sign the app with the option '--v1-signing-enable true', that's the only way I've been able to sign and successfully verify the v1 signing with jarsigner -verify -certs my-app.apk

**Comment by arielscht** [comment]
> I had to manually use apksigner to sign the app with the option '--v1-signing-enable true', that's the only way I've been able to sign and successfully verify the v1 signing with jarsigner -verify -certs my-app.apk

I wish I could configure the build to also sign using v1, have anyone been able to do so with expo SDK 52?

I wrote a config plugin to inject 'v1SigningEnabled true' on my app's signingConfig but it was ignored.
