### ISSUE TITLE
[docs] create-expo-app@latest is not the same as in the documentation

### ISSUE THREAD

**Issue by Ryangeorge-ctrl** [expo/expo#32635]
### Summary

In the docs, there's the command:
```bash
npx create-expo-app@latest StickerSmash && cd StickerSmash
```

The project this creates when trying in a terminal as of the day of this issue is not the same as the project shown being created in the documentation.

### Link to the related docs page

https://docs.expo.dev/tutorial/create-your-first-app/

**Comment by amandeepmittal** [comment]
Hey @Ryangeorge-ctrl, running  `npx create-expo-app@latest` for SDK 51 creates a project directory with the structure as expected in that doc, also show below:

![CleanShot 2024-11-06 at 16 57 24@2x](https://github.com/user-attachments/assets/a4719d48-dd60-44f5-b746-10301dee2cfd)

Can you share what it creates for you?

**Comment by Ryangeorge-ctrl** [comment]
Here is just one example of many:
<img width="280" alt="Screenshot 2024-11-06 at 5 37 41 PM" src="https://github.com/user-attachments/assets/03a536c9-1eb4-4468-b706-522859d788c9">
![image](https://github.com/user-attachments/assets/30b2a699-3177-4bc3-b905-6337fa990a8d)

As you can see, there is no app/index.tsx, and the entire project is different.

**Comment by amandeepmittal** [comment]
It seems you might have missed step 3 (https://docs.expo.dev/tutorial/create-your-first-app/#run-reset-project-script) which includes running the `reset-project` script. This scripts create a bare minimum structure with `app/index.tsx` as the entry point.

Project structure generated by running `npx create-expo-app@latest StickerSmash`.
![CleanShot 2024-11-07 at 12 06 40@2x](https://github.com/user-attachments/assets/f0fa7e8c-d70f-4bf6-ac3f-f82beec6c8c4)

Project structure after running `npm run reset-project` from step 3:

![CleanShot 2024-11-07 at 12 06 54@2x](https://github.com/user-attachments/assets/6a1f4ad9-7863-4c25-910b-15631f4b0ccf)

**Comment by Ryangeorge-ctrl** [comment]
Oh, sorry, closed.
