### ISSUE TITLE
share images on social app

### ISSUE THREAD

**Issue by mrishan1993** [expo/expo#3267]
This is the code I am using

```
Share.share({
            message: caption,
            url: "data:image/" + type + ";base64," + data,
            type: 'image/' + type,
            title: 'Gread'
          }, {
            // Android only:
            dialogTitle: 'Share this comic :)',
            // iOS only:
            excludedActivityTypes: [
              'com.apple.UIKit.activity.PostToTwitter'
            ]
          })
```

 when i use this, share modal pops up, but i cant share any image. 
although, I am able to share links and text

**Comment by EvanBacon** [comment]
You cannot share images using Android. Some images you may want to share using the Linking API. This video [Sharing in React Native](https://www.youtube.com/watch?v=ruaAUbekM9Q) may explain more of what you are looking for. Regardless the `Share` API, and the `Linking` API are not a part of Expo.

**Comment by gbxnga** [comment]
https://snack.expo.io/@gbxnga/expo-react-native-share

**Comment by rahul-desai3** [comment]
@gbxnga Good to see that images can now be shared on Android, but looking at [the docs for `Sharing`](https://docs.expo.io/versions/latest/sdk/sharing/),  I dont see a way to add a message along with the image.
