### ISSUE TITLE
[Expo 52] Android build failing

### ISSUE THREAD

**Issue by disolaterX** [expo/expo#32698]
### Summary

[RUN_GRADLEW] > Task :expo-font:javaPreCompileRelease
[RUN_GRADLEW] > Task :expo-modules-core:compileReleaseKotlin
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
[RUN_GRADLEW] 519 actionable tasks: 519 executed
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:processReleaseResources'.
[RUN_GRADLEW] > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
[RUN_GRADLEW]    > Android resource linking failed
[RUN_GRADLEW]      error: resource style/Theme.SplashScreen (aka com.guawaa.dediyo:style/Theme.SplashScreen) not found.
[RUN_GRADLEW]      com.guawaa.dediyo.app-mergeReleaseResources-56:/values/values.xml:5735: error: style attribute 'attr/windowSplashScreenBackground (aka com.guawaa.dediyo:attr/windowSplashScreenBackground)' not found.
[RUN_GRADLEW]      com.guawaa.dediyo.app-mergeReleaseResources-56:/values/values.xml:5736: error: style attribute 'attr/windowSplashScreenAnimatedIcon (aka com.guawaa.dediyo:attr/windowSplashScreenAnimatedIcon)' not found.
[RUN_GRADLEW]      com.guawaa.dediyo.app-mergeReleaseResources-56:/values/values.xml:5737: error: style attribute 'attr/postSplashScreenTheme (aka com.guawaa.dediyo:attr/postSplashScreenTheme)' not found.
[RUN_GRADLEW]      error: failed linking references.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 54s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.

### What platform(s) does this occur on?

Android

### SDK Version

52.0.0-preview.22

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
      Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Minimal reproducible example

npx eas-cli@12.6.0 build --platform android --local

**Comment by blaemmle** [comment]
I have the same issue with` error: resource style/Theme.SplashScreen` not found

**Comment by C2thehris** [comment]
Same here!

**Comment by mcriley821** [comment]
For posterity, I saw similar errors after upgrading to SDK 52. Installing `expo-splash-screen` seems to have fixed the problem.

**Comment by lhammond** [comment]
@mcriley821 's fix did not work for me

**Comment by Yuniac** [comment]
I keep getting: 

```
Android resource linking failed
[RUN_GRADLEW]      ERROR: /private/var/folders/bx/gd9z9z3138938bznmfm0mkk00000gn/T/eas-build-local-nodejs/d9284032-fd08-4bae-befe-6005ac031820/build/android/app/src/main/res/drawable/ic_launcher_background.xml:4: AAPT: error: resource drawable/splashscreen_logo (aka com.app.name:drawable/splashscreen_logo) not found.`

Did anyone found a solution to this?

**Comment by joaobsantos** [comment]
I have the same problem with my production app, and I tried with a clean one, and got the same result building for development.

On run gradlew step in eas:

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     error: resource style/Theme.SplashScreen (aka com.test.appInternal:style/Theme.SplashScreen) not found.
     com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1826: error: style attribute 'attr/windowSplashScreenBackground (aka com.test.appInternal:attr/windowSplashScreenBackground)' not found.
     com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1827: error: style attribute 'attr/windowSplashScreenAnimatedIcon (akacom.test.appInternal:attr/windowSplashScreenAnimatedIcon)' not found.
     com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1828: error: style attribute 'attr/postSplashScreenTheme (akacom.test.appInternal:attr/postSplashScreenTheme)' not found.
     error: failed linking references.

**Comment by Yuniac** [comment]
> I have the same problem with my production app, and I tried with a clean one, and got the same result building for development.
> 
> On run gradlew step in eas:
> 
> FAILURE: Build failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:processDebugResources'.
> 
> 
> > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> > Android resource linking failed
> > error: resource style/Theme.SplashScreen (aka com.test.appInternal:style/Theme.SplashScreen) not found.
> > com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1826: error: style attribute 'attr/windowSplashScreenBackground (aka com.test.appInternal:attr/windowSplashScreenBackground)' not found.
> > com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1827: error: style attribute 'attr/windowSplashScreenAnimatedIcon (akacom.test.appInternal:attr/windowSplashScreenAnimatedIcon)' not found.
> > com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1828: error: style attribute 'attr/postSplashScreenTheme (akacom.test.appInternal:attr/postSplashScreenTheme)' not found.
> > error: failed linking references.

I fixed my issue... somehow, I tried so many things so I don't know what exactly fixed it. But here are a few things worth trying.

* Make sure to run expo prebuild before building (this will end up creating the android and ios folders)
* Install expo-splash-screen package
* Configure the package in the app.json, something like this:
```json
    "plugins": [
      [
        "expo-splash-screen",
        {
          "backgroundColor": "#232323",
          "image": "./assets/images/splash-icon.png",
          "imageWidth": 200
        }
      ]
    ],
```


Those were the last things I did and afterwards I was able to build an app... Hope it helps.

**Comment by joaobsantos** [comment]
Thx but that didnt work, something is wrong with eas. 
This never happened to me and Im tired of making builds, thx for you help.

**Comment by Hakanlsk** [comment]
> > I have the same problem with my production app, and I tried with a clean one, and got the same result building for development.
> > On run gradlew step in eas:
> > FAILURE: Build failed with an exception.
> > ```
> > * What went wrong:
> >   Execution failed for task ':app:processDebugResources'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> > > Android resource linking failed
> > > error: resource style/Theme.SplashScreen (aka com.test.appInternal:style/Theme.SplashScreen) not found.
> > > com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1826: error: style attribute 'attr/windowSplashScreenBackground (aka com.test.appInternal:attr/windowSplashScreenBackground)' not found.
> > > com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1827: error: style attribute 'attr/windowSplashScreenAnimatedIcon (akacom.test.appInternal:attr/windowSplashScreenAnimatedIcon)' not found.
> > > com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1828: error: style attribute 'attr/postSplashScreenTheme (akacom.test.appInternal:attr/postSplashScreenTheme)' not found.
> > > error: failed linking references.
> 
> I fixed my issue... somehow, I tried so many things so I don't know what exactly fixed it. But here are a few things worth trying.
> 
> * Make sure to run expo prebuild before building (this will end up creating the android and ios folders)
> * Install expo-splash-screen package
> * Configure the package in the app.json, something like this:
> 
> ```json
>     "plugins": [
>       [
>         "expo-splash-screen",
>         {
>           "backgroundColor": "#232323",
>           "image": "./assets/images/splash-icon.png",
>           "imageWidth": 200
>         }
>       ]
>     ],
> ```
> 
> Those were the last things I did and afterwards I was able to build an app... Hope it helps.

I replaced the "black" value for backgroundColor with a hex code, ran the prebuild again, and my issue was resolved. Thank you!

**Comment by fr3nzy** [comment]
For those struggling with this, you must keep the "splash" bit that is apparently deprecated as well as the expo-splash-screen config plugin in the app.json. This is the only way I was able to build my app

**Comment by Mitsuda4Pres** [comment]
> For those struggling with this, you must keep the "splash" bit that is apparently deprecated as well as the expo-splash-screen config plugin in the app.json. This is the only way I was able to build my app

@fr3nzy you are a saint. This is what finally fixed it for me after 3 hours of researching. THANK YOU!

**Comment by Bharathsivanesh** [comment]
@fr3nzy thanky you very much after 5 hours of strugling i followed your idea and finnaly i build it .

**Comment by dpickett** [comment]
I'm also experiencing this issue, and I also have the "splash" property populated as advised by @fr3nzy - the resulting xml references a parent that doesn't exist after prebuild.

```xml
<style name="Theme.App.SplashScreen" parent="Theme.SplashScreen">
```

**Comment by billnye2** [comment]
Still getting this error, none of the above work
