### ISSUE TITLE
How to use kernel.ios.bundle for offline mode

### ISSUE THREAD

**Issue by daominhsangvn** [expo/expo#327]
After few hours for debugging, i realized that the i can archive the offline mode by generat the `kernel.ios.bundle` from `http://packager.as-wxj.<username><app-name>.exp.direct/node_modules/expo/AppEntry.bundle?platform=ios&dev=false&strict=false&minify=true&hot=false&assetPlugin=expo/tools/hashAssetFiles`. I also set `isRemoteJSEnabled` to `NO` in `EXShell.plist`
The result is the app not load the remote js anymore therefore it load the `kernel.ios.bundle` file.
I got the blank screen (white screen) but i'm still able to see the logs that i made in the js file, that's mean the js was loaded correctly but the UI not loaded somehow. @terribleben Do you have any idea?

**Comment by terribleben** [comment]
Hi! You shouldn't be doing anything with `kernel.ios.bundle`. What is your goal exactly? First-load-offline in an ExpoKit app?

Also, maybe we can take this discussion to the [forums](https://forums.expo.io) unless you think you've found a bug/issue with Expo?

**Comment by daominhsangvn** [comment]
@terribleben Yes it is. I want to archive the First-load-offline. In the previous Topic, you suggested i can use `shell-app-manifest.json` and `shell-app.bundle`. Do you have any documents for it?

**Comment by terribleben** [comment]
I see! Yeah, we don't offer documentation for that as it's not actually a feature we support, it's just a hack you can try applying. I'd be happy to help you personally if you open a [forum topic](https://forums.expo.io/) and ping me. :) I'm also available on Slack, but may not be able to answer right away.

Closing this, as we prefer to limit github issues to bug reports / problems with Expo.
