### ISSUE TITLE
[use dom] Content from DOM component not rendering in Android release mode

### ISSUE THREAD

**Issue by Rakha112** [expo/expo#32703]
### Minimal reproducible example

https://github.com/Rakha112/expo-usedom-R3F

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Hello, Thank you for creating use dom and making DOM component rendering so much easier. I’ve been testing it with React Three Fiber (R3F), and the DOM component renders models impressively fast compared to native rendering.

I understand that "use dom" is still in beta, but I’d like to report an issue where content from the DOM component doesn’t render in Android release mode (npx expo run:android --variant release). Specifically, 3D models from R3F fail to render in release mode, as shown in the image below. However, everything works as expected in Android debug mode, as well as in both debug and release modes on iOS (npx expo run:ios --configuration Release).

Thank you for your attention to this issue

| Android Debug       | Android Release       |
|---------------------|-----------------------|
| ![Android Debug SS](https://github.com/user-attachments/assets/45203724-bdce-49a0-9686-e7f0d5776e6b) | ![Android Release SS](https://github.com/user-attachments/assets/5f4fdfaa-54fb-4629-9311-e9732089fb4e) |
| iOS Debug           | iOS Release           |
| ![iOS Debug SS](https://github.com/user-attachments/assets/266a389c-50d2-40ea-bc00-5fd81f00b92b) | ![iOS Release SS](https://github.com/user-attachments/assets/42ac5519-89b4-43d3-b0d8-8bd64e7a009a) |

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 4.5.1 - /opt/homebrew/opt/node@20/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
      Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.23 => 52.0.0-preview.23 
      expo-router: ~4.0.0-preview.14 => 4.0.0-preview.14 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by Kudo** [comment]
the main reason is that the `useGLTF` loader using `fetch` to load the file. android webview does not support `file://` scheme from fetch. i don't have much experience for three.js. do you know if there're any other loaders than the fetch file loader?

we have some thought to solve the file loading but it requires a custom webview than react-native-webview. we would need some time to develop a new webview component.

**Comment by Rakha112** [comment]
Hey @Kudo, sorry for the late reply. Honestly, I only have experience using React Three Fiber and useGLTF for loading models. I tried using useFBX from Drei and GLTFLoader from Three.js (I’ve already pushed the code to the repo), but I ran into the same issue where the model wouldn’t load in Android release mode. I’m wondering if both of these loaders might also use fetch internally ? though I’m not entirely sure about that.

 I remember R3F had an [issue](https://github.com/pmndrs/react-three-fiber/issues/2992) in the past with models not loading in Android release mode, but I'm not sure if this is related or not

| Android Debug       | Android Release       |
|---------------------|-----------------------|
| ![Android Debug SS](https://github.com/user-attachments/assets/5ce9c148-27b8-4279-96aa-9ed61d385420) | ![Android Release SS](https://github.com/user-attachments/assets/1768ed6a-ad36-42f0-8154-532ba66c181b) |

**Comment by Kudo** [comment]
@Rakha112 the issue you mentioned looks unrelated.
given android webview does not support fetch to file:// uri, people suggest to use XHR or even override fetch with XHR. i asked AI to generate some code and it should work on android release build by using XHR + data uri.

```ts
// utils/fetcher.ts
export async function loadFileAsDataURIAsync(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.responseType = 'arraybuffer';

    xhr.onload = function () {
      if (xhr.status === 200) {
        const arrayBuffer = xhr.response;
        const base64String = arrayBufferToBase64(arrayBuffer);
        const mimeType = 'image/png'; // Adjust MIME type as needed
        const dataUri = `data:${mimeType};base64,${base64String}`;
        resolve(dataUri);
      } else {
        reject(new Error(`Failed to load file: ${xhr.statusText}`));
      }
    };

    xhr.onerror = function (e) {
      console.error('Network error');
      reject(e);
    };

    xhr.send();
  });
}

// Helper function to convert array buffer to Base64
function arrayBufferToBase64(buffer: ArrayBuffer): string {
  let binary = '';
  const bytes = new Uint8Array(buffer);
  const len = bytes.byteLength;

  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(bytes[i]);
  }

  return btoa(binary);
}
```

```tsx
// components/Char.tsx
"use dom";

import { useFBX } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { useEffect, useState } from 'react';

import { loadFileAsDataURIAsync } from '@/utils/fetcher';

const Char = () => {
  const [modelSrc, setModelSrc] = useState('');
  const model = modelSrc ? useFBX(modelSrc) : null;

  useEffect(() => {
    async function runAsync() {
      try {
        const dataUri = await loadFileAsDataURIAsync(`${process.env.EXPO_BASE_URL}char.fbx`);
        setModelSrc(dataUri);
      } catch (e) {
        console.error(e);
      }
    }
    runAsync();
  }, []);

  if (!model) {
    return null;
  }
  return (
    <Canvas
      style={{
        height: "100vh",
        width: "100vw",
      }}
      shadows
    >
      <ambientLight intensity={Math.PI} />
      <primitive object={model} position={[0, -50, -300]} />
    </Canvas>
  );
};

export default Char;
```

**Comment by Kudo** [comment]
i'm closing this issue because this is more threejs and android webview limitations.

**Comment by Rakha112** [comment]
Hey @Kudo, with XHR, the model is now loading properly in Android release mode. Thank you very much for your code and explanations!
