### ISSUE TITLE
Android build error during migration from SDK 51 to SDK 52

### ISSUE THREAD

**Issue by valerii-link** [expo/expo#32723]
### Minimal reproducible example

https://github.com/valerii-link/expo-sdk-52-migration-bug

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Error info:
```
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     com.example.withnewarch.app-mergeDebugResources-38:/values/values.xml:1848: error: resource drawable/splashscreen_logo (aka com.example.withnewarch:drawable/splashscreen_logo) not found.
     com.example.withnewarch.app-mergeDebugResources-38:/values/values.xml:1848: error: resource drawable/splashscreen_logo (aka com.example.withnewarch:drawable/splashscreen_logo) not found.
     error: failed linking references.
```

Steps to reproduce:
1. create project with `npx create-expo-app@latest -e with-new-arch`
2. update **expo** version in package.json to `~52.0.0-preview.23`
3. `npm install`
4. fix deps to match new sdk `npx expo install --fix`
5. `npm install`
6. `npx expo run:android`

OR (from example repo)

1. `npm install`
2. `npx expo run:android`

### How to fix:
• Add `splashscreen_logo.xml` to `android/app/src/main/res/drawable` folder

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0-preview.23 => 52.0.0-preview.23 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by alanjhughes** [comment]
Hi @valerii-link - the issue is you have no splash screen configuration. The template you have used didn't define one. This is example is no longer necessary on sdk 52. For a new project, your app will default to the new architecture

**Comment by valerii-link** [comment]
Hi @alanjhughes,
Thank you for the detailed information! 👍

**Comment by mfazekas** [comment]
Isn't it still a valid bug? I mean the DX could be improved. If splash config is now required but wasn't before, then tools like `upgrade` and `doctor` should warn this. Or even an improved build error message would be a great help.

**Comment by valerii-link** [comment]
I'm new to Expo, and here’s what I did:
• Generated a new project with the default template
• Copied the necessary data into my project
• Used `expo run:android` and `expo run:ios` to regenerate the android / ios folders

P.S. I didn't think improving the developer experience could be an outcome of this issue (as @mfazekas suggested)... So maybe I closed it too soon?

**Comment by rdhox** [comment]
I had this issue and I fought many hours to finally successfully build my app via `eas build --platform android --local`.

I did following the advices of this issue, but it was not working, but I saw this line during the build: 

```
This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: orientation, icon, userInterfaceStyle, scheme, splash, ios, android, plugins, androidStatusBar. 
```

So what I did: i didn't use `npx expo prebuild --clean`, I delete my android folder and directly launch the build, and it worked... Don't ask me why. Hope it help some people.

**Comment by skeddles** [comment]
i followed the getting started instructions here: https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build

and am on v52.0.33

and got this error

**Comment by eccianime** [comment]
Maybe a little late on this but I got this error in my recent migrations and the only feasible solution that works is using 

```
{
  expo: {
      ...,

      plugins: [
       ...,

      ]
        "expo-splash-screen",
        {
          "image": "./src/assets/images/splash-icon.png",
          "backgroundColor": "#FFFFFF"
        }
      ]

  }
}

```
