### ISSUE TITLE
expo doctor fails new arch compatibility check even with new arch explicitly disabled

### ISSUE THREAD

**Issue by doughsay** [expo/expo#32745]
### What is actually happening:

expo doctor fails its check for new arch compatibility even when you explicitly disable new arch in your app config.

### Expected:

I expect that if I am opting out of the new architecture for now, that expo doctor doesn't fail the check for new arch compatibility of packages. Having expo doctor fail on this step makes is unusable as a CI check for apps that want to upgrade to expo 52 but can't yet opt in to the new architecture.

### What platform(s) does this occur on?

Android, iOS

### SDK Version

52.0.0-preview.23

### Environment

```text
  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.9 Pop!_OS 22.04 LTS
      Shell: 3.3.1 - /usr/bin/fish
    Binaries:
      Node: 22.11.0 - ~/.asdf/installs/nodejs/22.11.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.9.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      expo: ~52.0.0-preview.23 => 52.0.0-preview.23
      expo-router: ~4.0.0-preview.14 => 4.0.0-preview.14
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Minimal reproducible example

repo: https://github.com/doughsay/expo-doctor-example

steps used to create it:

```shell
npx create-expo-app@latest --template default@beta
npx expo install react-native-track-player
# edit app.json to set "newArchEnabled": false
npx expo-doctor
```
expo-doctor fails the step "Validate packages against React Native Directory package metadata" and exits with non-zero exit status.

**Comment by brentvatne** [comment]
this is intentional, we want people to be aware of potential issues before they migrate. you can explicitly disable the check itself though: https://docs.expo.dev/guides/new-architecture/#see-all-available-options

**Comment by doughsay** [comment]
Thanks for pointing me to the right docs; I really did look a _lot_, so I think I can say with relative confidence that the docs are not very discoverable.  I looked everywhere for the "official" expo-doctor documentation, but this is the best I found: https://docs.expo.dev/guides/new-architecture/#validate-your-dependencies-with-react-native-directory

and as you can see it doesn't say anything about how (or even if) it's configurable

**Comment by shekharkhedekar** [comment]
> Thanks for pointing me to the right docs; I really did look a _lot_, so I think I can say with relative confidence that the docs are not very discoverable. I looked everywhere for the "official" expo-doctor documentation, but this is the best I found:
> 
> https://docs.expo.dev/develop/tools/#expo-doctor
> 
> and as you can see it doesn't say anything about how (or even if) it's configurable

Not easy to find, but here are the [docs for the config options](https://docs.expo.dev/versions/latest/config/package-json/#doctor).
