### ISSUE TITLE
[EXPO SDK 52] - Expo PreBuild Failed in WIndows AssertionError [ERR_ASSERTION]

### ISSUE THREAD

**Issue by Vijayabaskar56** [expo/expo#32754]
### Summary

While Try to Prebuild my android Application WIth  "bun expo prebuild" Command Encoutring this Error and the same Error is still occure while trying with other package manager like npm and pnpm .

env: load .env.development
env: export API_URL SECRET_KEY VAR_NUMBER VAR_BOOL
√ Created native directory
√ Updated package.json | no changes
× Prebuild failed
AssertionError [ERR_ASSERTION]: [android.dangerous]: withAndroidDangerousBaseMod: Project file "MainApplication" does not exist in android project for root "E:\Development\NNN",

Now I am Currently Only able to build it  via cd android && ./gradlew clean

### What platform(s) does this occur on?

Android

### SDK Version

52

### Environment

```text
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y


  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.26100
    Binaries:
      Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      expo: ~52.0.0-preview.16 => 52.0.0-preview.18
      expo-router: ~4.0.0-preview.11 => 4.0.0-preview.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Minimal reproducible example

https://github.com/Vijayabaskar56/NNN

**Comment by AbisheekKumar** [comment]
> angerousBas

Hi, have you solved it?
