### ISSUE TITLE
yarn and npm 5

### ISSUE THREAD

**Issue by skyride99** [expo/expo#328]
I am using yarn for node modules
but keep getting this error

Error: You are using npm version 5.0.3. Please use an npm version that is >= 3.0.0 and < 5.0.0. Run 'npm i -g npm@4.6.1' to resolve.

I try to install npm 4.6.1 but get this error
/Users/skyride/.npm-packages/bin/npm -> /Users/skyride/.npm-packages/lib/node_modules/npm/bin/npm-cli.js
npm ERR! path /Users/skyride/.npm-packages/share/man/man1/npm-adduser.1
npm ERR! code EEXIST
npm ERR! Refusing to delete /Users/skyride/.npm-packages/share/man/man1/npm-adduser.1: ../../../../../../private/var/folders/mw/n9g6rylx38vdw9d9qxt39pl40000gn/T/npm.51396/package/man/man1/npm-adduser.1 symlink target is not controlled by npm /Users/skyride/.npm-packages/share/man/man1
npm ERR! File exists: /Users/skyride/.npm-packages/share/man/man1/npm-adduser.1
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/skyride/.npm/_logs/2017-07-04T14_09_07_118Z-debug.log

If i delete the adduser files still the same error. Not sure how this works

**Comment by jesseruder** [comment]
That isn't a blocking error, you can ignore it if you installed the node_modules with yarn.

**Comment by dikaiosune** [comment]
You may need to install npm 4 with the `--force` option, but please exercise caution. Regardless, issues with installing npm need to be reported on their repo. Thanks!

**Comment by dikaiosune** [comment]
My bad, didn't realize this was still happening with yarn in use. @jesseruder did we make the npm 5 error a warning?

**Comment by skyride99** [comment]
with  force npm seems to install but still npm -v is always 5.0.3. I can restart the terminal still 5.0.3

npm i -g npm@4.6.1 --force
/Users/skyride/.npm-packages/bin/npm -> /Users/skyride/.npm-packages/lib/node_modules/npm/bin/npm-cli.js
+ npm@4.6.1
added 21 packages, removed 133 packages and updated 278 packages in 19.26s
Thomass-MacBook-Pro:~ skyride$ npm -v
5.0.3

**Comment by dikaiosune** [comment]
I believe we converted this check to a warning, please comment back if this is still blocking you.
