### ISSUE TITLE
[create-expo-module] Multiple issues when creating new expo module

### ISSUE THREAD

**Issue by GGGeorgiev20** [expo/expo#32835]
### Summary

IMPORTANT: Before reading this issue, I want to make it clear that I have already solved the issue and this is an informational post for users and developers working on the project.

Hello, I have recently had the need to build a native module for Expo. I started by reading the expo documentation on the topic, to where it redirected me to a tutorial for creating a new module, which I followed but ran into multiple issues while doing so.

The first issue I ran into was that after I entered my GitHub email, the command would give an error, which I have attached in 'Environment'.

I figured it was because I was trying to use bun, so I switched to npm but to no avail. I then tried to fix some error in my GitHub API, but that was not the problem. Finally, what I managed to do was go to the file and manually edit the line:
`if (json && json.data && json.data.total_count > 0) {`

After fixing this, I tried running it again using bun, but it gave me some errors about peer dependencies and what not (if a developer needs the log, I'd be glad to give them). I switched to npm and the module project was successfully created, but it gave me some kind of error about the homepage:
`Tried to guess the docs homepage for kompot-nfc-manager; add it under the "homepage" entry in package.json`
I'm not sure what this error means as in the package.json this property is set to the link of my repo with '#readme' appended to the end of it.

Anyway, after that when I tried to run the project, it gave me an error about the types file missing but, in reality, the file instead just had the word 'Module' appended to it for some reason. After renaming the file and starting it again, everything seems to work (at least, as far as I've noticed so far). This issue was made to be helpful to users who wish to get it working and developers who wish to get it fixed. Thank you for listening to my TED talk.

### Environment

```text
/home/Galin/.bun/install/global/node_modules/create-expo-module/build/utils/github.js:45
    if (json.data.total_count > 0) {
                  ^

TypeError: Cannot read properties of undefined (reading 'total_count')
    at findGitHubUserFromEmailByCommits (/home/Galin/.bun/install/global/node_modules/create-expo-module/build/utils/github.js:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async findGitHubUserFromEmail (/home/Galin/.bun/install/global/node_modules/create-expo-module/build/utils/github.js:29:12)
    at async initial (/home/Galin/.bun/install/global/node_modules/create-expo-module/build/prompts.js:90:44)
    at async prompt (/home/Galin/.bun/install/global/node_modules/prompts/lib/index.js:42:53)
    at async askForSubstitutionDataAsync (/home/Galin/.bun/install/global/node_modules/create-expo-module/build/create-expo-module.js:296:103)
    at async Command.main (/home/Galin/.bun/install/global/node_modules/create-expo-module/build/create-expo-module.js:72:18)
```
```


### Minimal reproducible example

Step to reproduce:
`npx create-expo-module my-module`

This should work with any package manager.

**Comment by brentvatne** [comment]
thanks you @GGGeorgiev20 for the information!
