### ISSUE TITLE
Absolute positions (left, right, and etc.) don't work in 4.0.3 expo-router

### ISSUE THREAD

**Issue by Maxim-Fursa** [expo/expo#32842]
### Minimal reproducible example

https://github.com/Maxim-Fursa/expo-router-bug

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Using Android. 

After updating Into latest (4.0.3) version cannot apply absolute positions (left, right, etc) for Tabs in screenOptions -> tabBarStyle. Its just doesn't work. On my previous version (3.5.24) everything works fine

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~52.0.4 => 52.0.4
      expo-router: ~4.0.3 => 4.0.3
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
This is an upstream issue with React Navigation 7 and I would recommend creating an issue there to address your problem.

A workaround is to use `marginLeft`/`marginRight` which in this instance should achieve a similar effect.
