### ISSUE TITLE
Could not find com.github.CanHub:Android-Image-Cropper:1.1.1

### ISSUE THREAD

**Issue by linus-edor** [expo/expo#32851]
I have the same problem:

Could not resolve com.github.CanHub: Android-Image-Cropper:1.1.1

_Originally posted by @huzaifaonyxtec in https://github.com/expo/expo/issues/20585#issuecomment-1363663101_
         
I need urgent assistance please. 
Trying build an update to my production ready app, I face the above issue.
Full log below:

> Configure project :expo
Using expo modules
  - expo-application (4.1.0)
  - expo-av (11.2.3)
  - expo-camera (12.2.0)
  - expo-constants (13.1.1)
  - expo-contacts (10.2.0)
  - expo-eas-client (0.2.1)
  - expo-error-recovery (3.1.0)
  - expo-file-system (14.0.0)
  - expo-font (10.1.0)
  - expo-image-loader (3.2.0)
  - expo-image-manipulator (10.3.1)
  - expo-image-picker (13.1.1)
  - expo-json-utils (0.3.0)
  - expo-keep-awake (10.1.1)
  - expo-linear-gradient (11.3.0)
  - expo-local-authentication (12.2.0)
  - expo-manifests (0.3.1)
  - expo-modules-core (0.9.2)
  - expo-permissions (13.2.0)
  - expo-secure-store (11.2.0)
  - expo-splash-screen (0.15.1)
  - expo-structured-headers (2.2.1)
  - expo-updates (0.13.4)
> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/expo/workingdir/build/node_modules/react-native-reanimated/android/react-native-reanimated-68-jsc.aar
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:mergeReleaseNativeLibs'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.github.CanHub:Android-Image-Cropper:1.1.1.
     Searched in the following locations:
- http://10.4.0.201:8081/artifactory/libs-release/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
       - file:/home/expo/.m2/repository/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
       - file:/home/expo/workingdir/build/node_modules/react-native/android/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
       - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
       - https://dl.google.com/dl/android/maven2/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
       - https://repo.maven.apache.org/maven2/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
       - https://www.jitpack.io/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
       - file:/home/expo/workingdir/build/node_modules/expo-camera/android/maven/com/github/CanHub/Android-Image-Cropper/1.1.1/Android-Image-Cropper-1.1.1.pom
     Required by:
         project :app > project :expo > project :expo-image-picker

**Comment by alanjhughes** [comment]
Hi @linus-edor the issue is you are using very old versions of these packages. `expo-image-picker` is currently using version `4.3.1` of this library. The most recent build of `1.1.1` has failed on jitpack so this is why you are seeing the error. You will need to try and update these dependencies. What SDK version are you using?

**Comment by linus-edor** [comment]
> Hi @linus-edor the issue is you are using very old versions of these packages. `expo-image-picker` is currently using version `4.3.1` of this library. The most recent build of `1.1.1` has failed on jitpack so this is why you are seeing the error. You will need to update these dependencies. What SDK version are you using?

Thanks @alanjhughes, let me update and provide feedback. 
Warm regards.

**Comment by linus-edor** [comment]
Hi @alanjhughes, 

Thanks for that suggestion. I moved past that error but the build still fails on compiling expo-image-picker. I'm using Expo SDK 45. Below is the build log:

 Task :expo-linear-gradient:compileReleaseJavaWithJavac
> Task :expo-linear-gradient:bundleLibCompileToJarRelease
> Task :expo-local-authentication:compileReleaseKotlin
> Task :expo-local-authentication:compileReleaseJavaWithJavac
> Task :expo-local-authentication:bundleLibCompileToJarRelease
> Task :expo-secure-store:compileReleaseKotlin
w: /home/expo/workingdir/build/node_modules/expo-secure-store/android/src/main/java/expo/modules/securestore/AuthenticationHelper.kt: (172, 19): Name shadowed: cipher
w: /home/expo/workingdir/build/node_modules/expo-secure-store/android/src/main/java/expo/modules/securestore/AuthenticationHelper.kt: (178, 28): Name shadowed: result
> Task :expo-secure-store:compileReleaseJavaWithJavac
> Task :expo-secure-store:bundleLibCompileToJarRelease
Note: /home/expo/workingdir/build/node_modules/expo-secure-store/android/src/main/java/expo/modules/securestore/SecureStoreModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :expo-permissions:compileReleaseKotlin
> Task :expo-permissions:compileReleaseJavaWithJavac
> Task :expo-permissions:bundleLibCompileToJarRelease
> Task :expo-image-picker:compileReleaseKotlin FAILED
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (19, 28): Unresolved reference: activityresult
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (42, 83): Type mismatch: inferred type is expo.modules.kotlin.Promise but expo.modules.core.Promise! was expected
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (46, 80): Type mismatch: inferred type is expo.modules.kotlin.Promise but expo.modules.core.Promise! was expected
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (50, 83): Type mismatch: inferred type is expo.modules.kotlin.Promise but expo.modules.core.Promise! was expected
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (54, 80): Type mismatch: inferred type is expo.modules.kotlin.Promise but expo.modules.core.Promise! was expected
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (86, 39): Unresolved reference: registerForActivityResult
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (88, 15): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (88, 22): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (89, 45): Unresolved reference: registerForActivityResult
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (91, 15): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (91, 22): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (92, 42): Unresolved reference: registerForActivityResult
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (94, 15): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (94, 22): Cannot infer a type for this parameter. Please specify it explicitly.
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (109, 40): Unresolved reference: AppContextActivityResultLauncher
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (110, 46): Unresolved reference: AppContextActivityResultLauncher
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.kt: (111, 43): Unresolved reference: AppContextActivityResultLauncher
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt: (11, 28): Unresolved reference: providers
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt: (14, 35): Unresolved reference: AppContextProvider
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt: (12, 28): Unresolved reference: activityresult
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt: (13, 28): Unresolved reference: providers
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt: (23, 35): Unresolved reference: AppContextProvider
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt: (24, 5): Unresolved reference: AppContextActivityResultContract
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt: (30, 3): 'createIntent' overrides nothing
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt: (39, 3): 'parseResult' overrides nothing
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CropImageContract.kt: (19, 28): Unresolved reference: activityresult
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CropImageContract.kt: (20, 28): Unresolved reference: providers
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CropImageContract.kt: (25, 35): Unresolved reference: AppContextProvider
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CropImageContract.kt: (26, 5): Unresolved reference: AppContextActivityResultContract
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CropImageContract.kt: (27, 3): 'createIntent' overrides nothing
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CropImageContract.kt: (55, 3): 'parseResult' overrides nothing
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/ImageLibraryContract.kt: (11, 28): Unresolved reference: activityresult
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/ImageLibraryContract.kt: (12, 28): Unresolved reference: providers
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/ImageLibraryContract.kt: (23, 35): Unresolved reference: AppContextProvider
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/ImageLibraryContract.kt: (24, 5): Unresolved reference: AppContextActivityResultContract
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/ImageLibraryContract.kt: (30, 3): 'createIntent' overrides nothing
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/ImageLibraryContract.kt: (40, 3): 'parseResult' overrides nothing
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/CompressionImageExporter.kt: (13, 28): Unresolved reference: providers
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/CompressionImageExporter.kt: (23, 35): Unresolved reference: AppContextProvider
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/CompressionImageExporter.kt: (52, 57): Type mismatch: inferred type is MatchGroup? but Bitmap was expected
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/CompressionImageExporter.kt: (57, 5): Type mismatch: inferred type is MatchGroup? but Bitmap was expected
e: /home/expo/workingdir/build/node_modules/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/CompressionImageExporter.kt: (58, 24): No value passed for parameter 'name'
> Task :expo-splash-screen:compileReleaseKotlin
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenReactActivityLifecycleListener.kt: (17, 50): Parameter 'activityContext' is never used
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenReactActivityLifecycleListener.kt: (35, 66): 'toLowerCase(): String' is deprecated. Use lowercase() instead.
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenViewController.kt: (20, 25): 'constructor Handler()' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenViewController.kt: (41, 5): Parameter 'failureCallback' is never used
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (23, 27): 'replaceSystemWindowInsets(Int, Int, Int, Int): WindowInsets' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (24, 29): 'getter for systemWindowInsetLeft: Int' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (26, 29): 'getter for systemWindowInsetRight: Int' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/singletons/SplashScreenStatusBar.kt: (27, 29): 'getter for systemWindowInsetBottom: Int' is deprecated. Deprecated in Java
> Task :expo-updates:kaptGenerateStubsReleaseKotlin
> Task :app:bundleReleaseJsAndAssets
info Writing bundle output to:, /home/expo/workingdir/build/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /home/expo/workingdir/build/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 76 asset files
info Done copying assets
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
573 actionable tasks: 573 executed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':expo-image-picker:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 4m 53s

Thanks for any other suggestion.

**Comment by alanjhughes** [comment]
@linus-edor looks like you've updated expo-image-picker only. That won't work because it has a dependency on expo-modules-core. The only thing I can suggest is trying to update your SDK version. 45 is very old.
