### ISSUE TITLE
Route Redirect in Expo Stack Navigation (Web)

### ISSUE THREAD

**Issue by astikdev** [expo/expo#32855]
### Minimal reproducible example

https://github.com/astikdev/webtamagUI/tree/issue/web/stacknavigation

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

**Issue Description**
In the current Expo Stack Navigation setup, navigating directly to specific routes via the browser by pasting the URL results in an automatic redirect to the index page on the web platform. This issue prevents users from accessing deep-linked pages directly, impacting usability in cases where users expect to access specific sub-pages without needing to start from the home (index) page.

**Key Points of the Issue**

1. Route Redirect: Navigating to a specified route link in the browser defaults to the index page, regardless of the intended path.
2. Platform Specific: This issue is isolated to the web environment; mobile navigation behaves as expected.
3. User Experience Impact: Prevents direct access to sub-pages via the browser, which can disrupt the user journey.
4. Intended Routing Behavior: Expected behavior is for the URL to route the user directly to the intended sub-page without manual intervention.

https://github.com/user-attachments/assets/55f10078-b1d4-4831-b667-53137dc7eb3c

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 4.0.2 - ~\AppData\Roaming\npm\yarn.CMD    
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636    
    npmPackages:
      @expo/metro-config: ~0.18.11 => 0.18.11
      babel-preset-expo: ^11.0.6 => 11.0.6
      expo: ^51.0.34 => 51.0.34
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
      react-native-web: ^0.19.12 => 0.19.12
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
There appears to be some conditional logic in your app that is causing the initial render to not render a navigator.  You can see this in your video where it loads a white screen of the default Stack.

In your code, if I replace the `<HODLayout />` with `<Slot />`, the routing appears to be working correctly
