### ISSUE TITLE
Expo Camera BarcodeScanningResult returns normalized coordinates rather than pixel-based screen coordinates

### ISSUE THREAD

**Issue by kaaecreme** [expo/expo#32867]
### Minimal reproducible example

https://snack.expo.dev/@kaaecreme/barcode

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

When using the expo-camera package, the bounding box coordinates returned for a scanned barcode (bounds.origin and bounds.size) are provided in normalized coordinates (values between 0 and 1) rather than pixel-based screen coordinates.

The expected behavior is to receive coordinates relative to the screen size in pixels(as I understand), allowing direct overlay positioning on the camera preview without additional transformation. While the coordinates appear correct (pixel-based) on Android, they now read as normalized on iOS.

This makes it difficult to manage barcode scanning accurately, especially when needing to restrict the scanning area precisely. Transforming normalized values to pixel coordinates based on screen resolution seems inaccurate.

This began after upgrading to SDK 52.

https://github.com/user-attachments/assets/78af037d-aa83-4af6-8a7a-6c6222f0c977

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\node_modules\.bin\yarn.CMD
      npm: 9.6.0 - ~\node_modules\.bin\npm.CMD
    IDEs:
      Android Studio: AI-241.18034.62.2411.12169540
    npmPackages:
      expo: ~52.0.4 => 52.0.4
      react: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by kaaecreme** [comment]
Forgot to add: It also seems the x and y has been switched around

**Comment by alanjhughes** [comment]
@kaaecreme are you using expo go?

**Comment by kaaecreme** [comment]
@alanjhughes Yes I am

**Comment by kaaecreme** [comment]
@alanjhughes I see, thank you for the clarification
