### ISSUE TITLE
[iOS] GeoFencing isn't working on a Standalone iOS device 

### ISSUE THREAD

**Issue by zsayenko** [expo/expo#3286]
I got GeoFencing working in a simulator(using Debug -> Location) and in Expo Client (tested driving around) - all works pretty much as expected.

However, I can't get it to work as a standalone app.
When I reload the app I get the initial location notification with all the defined regions and whether I am inside the region or not.

But after that no updates come in as I move around (in and out of the regions).
It doesn't matter if the app is backgrounded or foregrounded.

I do have my Location permission set to Always.

Info.plist has all necessary settings:
"infoPlist": {
        "UIBackgroundModes": ["location"],
        "NSLocationAlwaysUsageDescription": "To enable geofencing.",
        "NSLocationWhenInUseUsageDescription": "To enable geofencing.",
        "NSLocationAlwaysAndWhenInUseUsageDescription": "To enable geofencing.",
      }

**Comment by zsayenko** [comment]
Quick update on this issue.
The device I originally was testing it with had iOS version 11.4.1 running.
I tried the same app on the updated device (iOS 12.1.3up) and it's been working fine.

Do you know know what is the minimum version required to run geofencing?

**Comment by tsapeta** [comment]
Hey @zsayenko, thanks for the update!

From what I know geofencing is available since iOS 5.0. Maybe there was an internal iOS issue in 11.4.1? I'll try to check it out soon.

**Comment by dereknelson** [comment]
Just want to add, I could not get background location tracking or geofencing working in the background in the simulator OR on my physical device as I move around, both as a standalone and running my published app (from my profile) in the expo app.

I've tested by 
- messing around with [the location settings](http://prntscr.com/mdxw72) (for the simulator)
- driving, entering geofences, stopping for at least 1 min with my physical device

Relevant code I used to test it (cut down for sake of clarity): 
```
TaskManager.defineTask(BACKGROUND_LOCATION_UPDATES_TASK, async ({ data, error }) => {
    const username = await AsyncStorage.getItem('username')
    try {
        const { locations } = data
        Notifications.presentLocalNotificationAsync({ title: 'hey', body: `location update, isBackground: ${Constants.isHeadless ? 'true' : 'false'}`, })
        if (Constants.isHeadless) await axios.get(apiURL('userlocation', `${username}/${locations[0].coords}`))
    } catch (error) {
        if (Constants.isHeadless) Sentry.captureMessage(`location update error ${JSON.stringify(error.response)}`)
    }
})
```
I have not gotten any requests to my api, and I doubt there is a problem with `Constants.isHeadless` because AFAIK notifications can be generated in headless mode, and push notifications are only generated when the app has not been quit for the standalone and within expo.

**Comment by tsapeta** [comment]
Hi @dereknelson,

Have you been testing it while the app is closed? If the app was just backgrounded, then I guess you didn't want to use `Constants.isHeadless` checks here. It's true only when the task is running when the app was closed and was just woken up to run the task.

**Comment by dereknelson** [comment]
@tsapeta yes, the app was completely closed. 

Interestingly enough, the only time I've noticed the app being woken up from being closed is when my real device is on wifi with expo-cli running on my laptop - it will wake up, connect to the expo instance, console log updates (I omitted the console log line in my code snippet), display a notification with isBackground (aka isHeadless) being true, as well as make a request to the api.

**Comment by farzd** [comment]
I can get geofencing to operate on simulator via expo but doesnt seem to work on device via expo or stand alone build [test flight]

```
    await Location.startGeofencingAsync(client.tasks.geofencing, [
      {
        latitude: parseFloat(lat),
        longitude: parseFloat(long),
        radius: client.location.geofencingThreshold,
        notifyOnEnter: false
      }
    ])

  TaskManager.defineTask(
    client.tasks.geofencing,
    async ({ data: { eventType, region }, error }) => {
      if (error) {
        console.log({ geoFencingError: error })
        return
      }
      if (eventType === Location.GeofencingEventType.Enter) {
        console.log("You've entered region:", region)
      } else if (eventType === Location.GeofencingEventType.Exit) {
        console.log("You've left region:", region)
      }
    }
  )
```

the task is registered and i get the initial in region console but it doesnt update when i go out of bounds

**Comment by rcabarreto** [comment]
Hey guys, I'm having a similar problem, maybe one of you can help me. 

I'm running startGeofencingAsync with some regions. They work fine when the app is in foreground and when the app is recently backgrounded, but after some time (a few hours) it just stops reporting the geofencing events. I noticed that it happens when the app gets "suspended" (it still shows on the task manager, but when you open it, it's like it's starting up again).

 Is there anyway to keep the geofences working on background?

**Comment by peterorlowsky** [comment]
I am having the same issue as farzd described but on an Android Phone.
Geofence works on expo within the simulator just fine. On a real device with a standalone app I only receive the initial enter region but no exit event, regardless if the app is foregrounded/backgrounded or terminated.

**Comment by willenglishiv** [comment]
is there a chance there is a snack somewhere with a working geofence example? I can't get mines working to save my life.

**Comment by vinitsood** [comment]
Just made a snack where `startGeofencingAsync` doesn't work on real iOS devices. 

Perhaps someone can have a look

https://snack.expo.io/SkIYQZ8eU

**Comment by jvliwanag** [comment]
As of Expo SDK 36, geofencing works well with the custom IOS expo client app. Even if the expo client app is force closed, geofencing works reliably. This is both on the iOS simulator and physical devices.

On a standalone build however, geofence works but only when the app is running (foreground or background). However when the app is force closed, geofence ceases to work. On the next reopen, even if geofence was previously started, `hasStartedGeofencingAsync` ends up returning false. And geofence needs to be manually restarted.

**Comment by jvliwanag** [comment]
It looks like an error within `EXTaskService`.

In particular, I'm getting the following log:

```
EXTaskService: Loading app '@me/myapp' from url 'https://expo.io:443/@me/myapp' failed. Error description: Error Domain=RCTErrorDomain Code=0 "No cache exists for this resource: (null).bundle" UserInfo={NSLocalizedDescription=No cache exists for this resource: (null).bundle}
```

This log is only present when running a standalone app, but not when running the expo client.

Based [here](https://github.com/expo/expo/blob/dfc087cefec3349daf3f4c2d4f70fb9ceb91b0c6/packages/expo-task-manager/ios/EXTaskManager/EXTaskService.m#L543), it looks like upon encountering the error, `EXTaskService` then removes and unregisters all tasks.

**Comment by shalvipandita** [comment]
I am unable to run **Location.startGeofencingAsync** on standalone devices but it is running perfectly fine on simulator.

Here is the error I am constantly getting 
_`Error: Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient) || _CFMZEnabled()`_

I tried the[ Expo snack ](https://snack.expo.io/@devpilot/geofence)as well for geofencing , it has the same error on standalone. Any help would be much appreciated

**Comment by arthurpark** [comment]
I'm getting slightly different experience from @shalvipandita.  I also see ```[Unhandled promise rejection: Error: Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient) || _CFMZEnabled()]``` error when calling `Location.startGeofencingAsync`, but only on ExpoClient. When I build standalone app and run it on simulator, it seems to work. Posted this in [forum](https://forums.expo.io/t/geofencing-on-managed-workflow-ios/38234) before coming here and created a minimalish [project](https://github.com/arthurpark/ExpoGeofence) to reproduce this. Seems to be permission related.

- SDK Version: 37
- Platform: iOS
- Expo Client Version: 2.15.5
- Device: iPhone 11 Pro (iOS 13.4.1)

**Comment by MrMonotone** [comment]
I can confirm I am getting a similiar issue when using ExpoClient. 


```[Unhandled promise rejection: Error: Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient) || _CFMZEnabled()]```

I have all the relevant permissions in infoPlist. I have the same code working on Android.

    SDK Version: 38
    Platform: iOS
    Expo Client Version: 2.16
    Device: iPhone 6s (iOS 13.5)

**Comment by ismaelbarry** [comment]
Hey all :)

Was anyone able to solve the issue with

`[Unhandled promise rejection: Error: Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient) || _CFMZEnabled()]`

I'm also having this issue.
