### ISSUE TITLE
LayoutAnimation.configureNext() broken in SDK 52

### ISSUE THREAD

**Issue by baltagih2** [expo/expo#32868]
### Minimal reproducible example

https://snack.expo.dev/@baltagih/b638ce

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

When showing or hiding content, `LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);` usually automatically applies the "next" animation (Like opening and closing an accordion). 

In SDK 51, this works perfectly but in SDK 52 the animation never happens. The content just appears and disappears without a slide or opacity change or anything.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2024.03.25.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/mafiamalaria/.rvm/gems/ruby-3.0.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 35.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: EAP AI-242.21829.142.2422.12329062 AI-242.21829.142.2422.12329062
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.19.2 => 0.19.2 
      babel-preset-expo: ~12.0.0 => 12.0.0 
      expo: ^52.0.4 => 52.0.4 
      expo-router: ~4.0.2 => 4.0.3 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.1.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by tsouthen** [comment]
I've noticed the same problem with SDK 52. This can also be reproduced using the snacks on the React Native website, like this one: https://reactnative.dev/docs/layoutanimation#create

**Comment by brentvatne** [comment]
we don't support LayoutAnimation in Expo Go at the moment, in general this API is not very good and should probably be removed from react-native - you should use Reanimated instead. you can use it in a development build if you want to.

**Comment by brentvatne** [comment]
@baltagih2 - it could quite possibly be an old/new arch issue! i'm not sure that LayoutAnimation is supported in new arch actually. could you test this outside of expo go and verify?

**Comment by baltagih2** [comment]
@brentvatne Started a brand new project with `npx create-expo-app@latest TestProject`
Went to the `Collapsible` component, and added `LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);` to the `onPress`

Does not work with both `newArchEnabled` true or false on Expo Go.

Same exact setup with expo SDK 51 works perfectly in Expo Go.

Seems like either a `react-native: 0.76` problem (Works perfectly on 0.74.5 with SDK 51), an Expo Go issue or an expo SDK issue.

Will try to build `TestProject` and run outside of expo go and re-update this comment too.

**Comment by liufangz** [comment]
I also encountered this problem after upgrading expo 52. But it only appears on expo go for my instance. It works well with expo run:ios in ios simulator as well as native build apk on android.

**Comment by brentvatne** [comment]
@liufangz - see: https://github.com/facebook/react-native/issues/47617

in general i would strongly advise against using the layoutanimation api, it is not reliable and imo should be removed from react-native

**Comment by baltagih2** [comment]
@brentvatne What would you recommend as a replacement? LayoutAnimation has always worked great for me (until this latest version) and was the perfect "one-liner" for those quick animations like a dropdown opening and closing without the hassle of reanimated and constructing your own animation for those little things. 

In my app for example, there's this onboarding process with images and text over multiple steps and LayoutAnimation creates this nice sliding effect and button animation by itself when the step changes to replace the current images and text with the new ones while animating the "Next" and "Back" buttons, all through a one-liner. This would have wasted hours to be animated one by one. Any alternatives you'd recommend if LayoutAnimation isn't going to be working anytime soon? Loving the SDK 52 updates but forced to stay on 51 because of this.

Thanks in advance!
