### ISSUE TITLE
[expo-router/ui] SDK52 <TabList asChild> causes "Error: Failed to set an indexed property [0] on 'CSSStyleDeclaration': Indexed property setter is not supported." on web

### ISSUE THREAD

**Issue by pfleigo** [expo/expo#32879]
### Minimal reproducible example

https://snack.expo.dev/@pfleigo/happy-orange-ice-cream

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

When using `TabList` from `expo-router/ui` with `asChild`, it will break the application **on web** with the error "_Error: Failed to set an indexed property [0] on 'CSSStyleDeclaration': Indexed property setter is not supported._"

I googled already and found this issue, which describes the same behaviour for the `Link` component: https://github.com/expo/expo/issues/31352

So I am pretty certain that `asChild` will create an array of styles on the child element following `<TabList>`. I tried using StyleSheet.flatten() for the styles in the child element (ScrollView in my case), but this doesn't help either.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.4 => 52.0.4
      expo-router: ^4.0.3 => 4.0.3
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

**Comment by benkraus** [comment]
Just ran into this as well - seems it works fine when using Nativewind and `className` for styles, but as soon as you provide a `style` prop to the child of `<TabList asChild>` it dies
