### ISSUE TITLE
Warning: TypeError: _ExpoFontLoader.default.getLoadedFonts is not a function (it is undefined)

### ISSUE THREAD

**Issue by SREERAJ089** [expo/expo#32891]
### Minimal reproducible example

https://github.com/SREERAJ089/expoFontsLoadedIssue/tree/main

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

Expected Behavior: The app is expected to load custom fonts asynchronously using expo-font, and the splash screen should remain visible until the fonts are fully loaded. After the fonts are loaded, the splash screen should hide, and the app should display the content with the custom fonts applied.

Actual Behavior: The error TypeError: _ExpoFontLoader.default.getLoadedFonts is not a function (it is undefined) occurs when attempting to load custom fonts. This error indicates that the getLoadedFonts method is being called, but it is undefined, suggesting an issue with how fonts are being loaded or managed within the expo-font library. The app might fail to load fonts properly or crash unexpectedly. The issue appears to be happening on both iOS and Android platforms.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^52.0.0 => 52.0.6
      react: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Detailed check results:

The package "expo-app-loading" has been removed as of SDK 49. You should use expo-splash-screen instead. Learn more: https://docs.expo.dev/versions/latest/sdk/splash-screen/

Expected package @expo/config-plugins@~9.0.0
Found invalid:
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~8.0.0
Found invalid:
  @expo/prebuild-config@5.0.7
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: @expo/config-plugins, @expo/prebuild-config, @reduxjs/toolkit, axios, expo-app-loading, react-redux, svg-path-properties, use-latest-callback
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.

Note - I updated @expo/config-plugins and  @expo/prebuild-config and package.json shows the version packages as updated.
```

**Comment by brentvatne** [comment]
please re-post your issue when you have resolved the issues with expo doctor, thanks!

**Comment by SREERAJ089** [comment]
When running npx ***@***.***, the issues are

@expo/config-plugins@~9.0.0
found invalid:
@***@***.***

same issue with @expo/prebuild-config

but package.json shows dependencies ***@***.***/config~plugins":"^9.0.9",
***@***.***/prebuild-config":"^8.0.15"

though i have updated my dependencies to the above versions, expo-doctor is
still showing the error. I also uninstalled and installed node modules, ran
npx expo start -c. Still  the issue persists

**Comment by SREERAJ089** [comment]
help me please
