### ISSUE TITLE
 Warning: TypeError: _ExpoFontLoader.default.getLoadedFonts is not a function (it is undefined)

### ISSUE THREAD

**Issue by SREERAJ089** [expo/expo#32895]
### Minimal reproducible example

https://github.com/SREERAJ089/expoFontsLoadedIssue/tree/main

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

Expected Behavior: The app is expected to load custom fonts asynchronously using expo-font, and the splash screen should remain visible until the fonts are fully loaded. After the fonts are loaded, the splash screen should hide, and the app should display the content with the custom fonts applied.

Actual Behavior: The error TypeError: _ExpoFontLoader.default.getLoadedFonts is not a function (it is undefined) occurs when attempting to load custom fonts. This error indicates that the getLoadedFonts method is being called, but it is undefined, suggesting an issue with how fonts are being loaded or managed within the expo-font library. The app might fail to load fonts properly or crash unexpectedly. The issue appears to be happening on both iOS and Android platforms (if using Expo).

Affected Platforms: iOS, Android

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^52.0.0 => 52.0.6
      react: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by ViljamHaanpaa** [comment]
+1

**Comment by ANBithi** [comment]
getting the same error!

**Comment by ViljamHaanpaa** [comment]
my problem was that  "expo-module-scripts": "^4.0.2", wasnt installed after 52

**Comment by SREERAJ089** [comment]
> getting the same error whenever I try load an icon.
> 
> EDIT: I fixed the issue by removing the node_modules and android folders, followed by a complete rebuild of the project, and then linked the custom fonts. It worked!

can you help me fix this issue, i am encountering the same error over and over again.

**Comment by ANBithi** [comment]
> > getting the same error whenever I try load an icon.
> > EDIT: I fixed the issue by removing the node_modules and android folders, followed by a complete rebuild of the project, and then linked the custom fonts. It worked!
> 
> can you help me fix this issue, i am encountering the same error over and over again.

First of all, I didn't use expo fonts. I saved the fonts in 'assets/fonts' path, and created a react-native.config.js with the following lines - 
`module.exports = {
    project: {
        android: {},
        ios: {},
        web : {}
    },
    assets: ["./assets/fonts"]
}`
In my case, at this stage I rebuild and created a development build.
After the build is completed, in terminal I used 'react-native-asset' command, which basically linked the fonts with the native android project. Then, I could access the fonts in my app, for example: `fontFamily: Poppins-Regular,`
Another thing, since I am using React Native Paper, I had to modify the fonts following their documentations, so their components could use the custom fonts without any issues.

**Comment by SREERAJ089** [comment]
Ok, I'll check it out.

**Comment by SREERAJ089** [comment]
> > > getting the same error whenever I try load an icon.
> > > EDIT: I fixed the issue by removing the node_modules and android folders, followed by a complete rebuild of the project, and then linked the custom fonts. It worked!
> > 
> > 
> > can you help me fix this issue, i am encountering the same error over and over again.
> 
> First of all, I didn't use expo fonts. I saved the fonts in 'assets/fonts' path, and created a react-native.config.js file with the following lines - `module.exports = { project: { android: {}, ios: {}, web : {} }, assets: ["./assets/fonts"] }` In my case, at this stage, I removed the android and node_modules folders, Then I used `npm install` to install the node_modules and rebuild the app. Next, I created a development build. After the build is completed, in terminal I used 'react-native-asset' command, which basically linked the fonts with the native android project. Then, I could access the fonts in my app, for example: `fontFamily: Poppins-Regular,` Another thing, since I am using React Native Paper, I had to modify the fonts following their documentations, so their components could use the custom fonts without any issues.

it worked!!! Thank you ;)

**Comment by ykthinker** [comment]
My problem was with @expo/vector-icons. The entire rebuild did not solve it. I don't have any custom fonts, just the icons.

**Comment by tmitchel2** [comment]
I had an issue with @expo/vector-icons also, I couldn't solve it.  Did you manage to get around it @ykthinker ?

**Comment by ANBithi** [comment]
> My problem was with @expo/vector-icons. The entire rebuild did not solve it. I don't have any custom fonts, just the icons.

Have you tried deleting the node_modules folder and reinstalling?

**Comment by tmitchel2** [comment]
Yup I tried that.  This was iOS btw so perhaps different to what people saw on android

**Comment by ANBithi** [comment]
Maybe. I was also getting the error while loading an icon on Android. Then, I rebuilt the app after deleting node_modules and reinstalling, it worked fine.

**Comment by mohanataraj** [comment]
> I had a development build done with SDK 51. After I update the SDK to 52 I see the same error (This error is not happening if I open the simulator with expo-go). I should create a new development build? Or is there a way to update the actual development build? Thanks.

I created a new X-Code build and installed on the device. The error did go away. Hope this helps

**Comment by micktdj** [comment]
I'm using "expo": "~51.0.31" and expo-font "^13.0.3" after downgrade expo-font to ^12.0.9 , it's working . 

I think "^13.0.3" its for expo >= SDK 52

**Comment by sultan-arshi** [comment]
+1

**Comment by Sechorda** [comment]
+1

**Comment by sultan-arshi** [comment]
I fixed this issue by following way 
- I have native modules in my code, so, I am using EAS Build 
- declare the path of your fonts into the app.json, i.e plugins section 
something like below 

```
[
      "expo-font",
      {
        "fonts": [
          "./assets/fonts/ABC.ttf",
          "./assets/fonts/second-font.ttf",
          "./assets/fonts/Mont-Bold.ttf",
        ]
      }
]
```

> Note: Most important, don't forget to send new build to EAS and install it again 

and also 

> On Android, the font family name is the same as of the font file (without the extension). On iOS, the font family name is read from the font file itself.

**Comment by Sechorda** [comment]
Removing expo/vector-icons in replacement of another library got my over this one. Vector-fonts worked fine up until now, then my dependencies all fell over after removing package-lock.json. Now my package.json is very organized...
