### ISSUE TITLE
 Error launching DevTools: Failed to launch debugger app window

### ISSUE THREAD

**Issue by austinm911** [expo/expo#32893]
### Minimal reproducible example

https://github.com/austinm911/expo-debugger-sdk52-issue

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Getting this on SDK 52.  It appears to me the debugger is trying to open the chrome app in the user's application director, rather than the root application directory? 

`/Users/account/Applications` contains no Google Chrome app
`/Applications` contains the google Chrome app

```
Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundled 9446ms node_modules/expo-router/entry.js (1235 modules)
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 INFO
 💡 JavaScript logs will be removed from Metro in React Native 0.77! Please use React Native DevTools as your default tool. Tip: Type j in the terminal to open (requires Google Chrome or Microsoft Edge).
Debug: Launching DevTools...
Debug: Error launching DevTools: Failed to launch debugger app window: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome exited with code null
› Stopped server
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
      Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.3 => 52.0.6
      expo-router: ~4.0.2 => 4.0.5
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.1 => 0.76.1
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

**Comment by YDaskaloff** [comment]
> hi there! the launch logic from sdk 52 is from the react-native core. they use [chrome-launcher](https://www.npmjs.com/package/chrome-launcher) to open chrome. as the readme said, you can try to use `CHROME_PATH` environment variable to change the chrome path. for example, if you want to use the chrome from system application:
> 
> ```shell
> $ CHROME_PATH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' npx expo start
> ```

you can also set this into your bashprofile/.zshrc/.bashrc like this:

`export CHROME_PATH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'`

So you don't have to add it to the start command every time

**Comment by ERCAAP** [comment]
(NOBRIDGE) LOG  Bridgeless mode is enabled
 INFO 
 💡 JavaScript logs will be removed from Metro in React Native 0.77! Please use React Native DevTools as your default tool. Tip: Type j in the terminal to open (requires Google Chrome or Microsoft Edge).
 (NOBRIDGE) WARN  Route "./CaloriTrackingSystem/components/utils/PersonalData.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./CaloriTrackingSystem/components/utils/PersonalDataStorage.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./CaloriTrackingSystem/components/utils/calculations.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]
 (NOBRIDGE) WARN  Route "./CheffAIComponents/ChefAIChat.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]
 (NOBRIDGE) WARN  Route "./CheffAIComponents/RecipeDetailModal.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./CheffAIComponents/Services/Message.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./CheffAIComponents/Services/Recipe.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  expo-notifications: Push notifications (remote notifications) functionality provided by expo-notifications will be removed from Expo Go in SDK 53. Instead, use a development build. Read more at https://docs.expo.dev/develop/development-builds/introduction/. [Component Stack]
 (NOBRIDGE) WARN  `expo-notifications` functionality is not fully supported in Expo Go:
We recommend you instead use a development build to avoid limitations. Learn more: https://expo.fyi/dev-client. [Component Stack]
 (NOBRIDGE) WARN  Route "./CookingTimerComponents/Services/types.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./MainMenuComponents/Services/constants.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./RatingModal/ReviewService.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]
 (NOBRIDGE) WARN  Route "./ShoppingListComponents/ShoppingListScreen.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]
 (NOBRIDGE) WARN  Route "./app.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]
 (NOBRIDGE) WARN  Route "./index.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 guys how can i fixed this ?
