### ISSUE TITLE
[Windows 10] Expo serve on the wrong wireless card

### ISSUE THREAD

**Issue by azzsamir** [expo/expo#329]
hi!
i'm working on a project that I created with CRNA and Expo, everything worked well on mac os, but on Windows 10, `npm start` serve the app on the wrong wireless card.

![image](https://user-images.githubusercontent.com/7574268/27841043-639243f6-60fe-11e7-9d8b-3649d33946e6.png)

![image](https://user-images.githubusercontent.com/7574268/27841058-7be12666-60fe-11e7-9d02-fd69a32aefc3.png)

is there a way to choose on which card the app must be served? 
thanks!

**Comment by jesseruder** [comment]
We don't support that right now. If you want to send a PR the relevant file is https://github.com/expo/xdl/blob/master/src/UrlUtils.js

**Comment by dikaiosune** [comment]
@azzsamir you can set the `REACT_NATIVE_PACKAGER_HOSTNAME=your.ip.address.here` environment variable, as spec'd in the CRNA user guide. Have a great day!
