### ISSUE TITLE
Passing params between screens broken

### ISSUE THREAD

**Issue by jreason** [expo/expo#32901]
### Minimal reproducible example

https://github.com/jreason/params-broken.git

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Since upgrading to SDK52, passing params between screens seems to be broken?

`
router.navigate({ pathname: './view-job', params: { jobId: item.id, test: 1 } });
`

File paths:
From Screen: (app)/[id]/jobs
To Screen: (app)/[id]/view-job

Attempting to retrieve parms on view-jobs using:

`
const routeParams = useLocalSearchParams();
`

Only the [id] param is retrieved and jobId and test are missing.

`
{id: '320930'}
`

This issue is the same on both Android and iOS

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.6 => 52.0.6 
      expo-router: ~4.0.5 => 4.0.5 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.10 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.1.1
    Expo Workflow: bare
```

**Comment by gilsondefreitas2014** [comment]
Bugou toda a minha aplicação, tive de voltar para o SDK 51 pois tenho muitas rotas com 2 ou mais parâmetros e leva para uma rota anterior ou fecha o app. Precisei gerar as builds para Android e iOS e com o SDK 52 não tem como.

**Comment by marklawlor** [comment]
This should be included in the next patch release
