### ISSUE TITLE
Why SDK51 to SDK52 crash

### ISSUE THREAD

**Issue by AlejandroDavidArzolaSaavedra** [expo/expo#32903]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by AlejandroDavidArzolaSaavedra** [comment]
I need help!!!

My app crash whis this error, y doesnt why it happends, i review all my code i dont see any of "large" in my code, here you can see the dependendencies that i use, to my project, if anyone can help me.

Yes
My dependencies:

![Captura de pantalla 2024-11-14 102129](https://github.com/user-attachments/assets/ee3513ce-89fb-4734-8ee3-d1548b715635)

My console error:
![image](https://github.com/user-attachments/assets/7476c62e-b83b-4da5-ae6d-357a08a1e6f4)

**Comment by AlejandroDavidArzolaSaavedra** [comment]
thanks

**Comment by DorianBajorek** [comment]
I have the same issue as above. I'm waiting for results. @AlejandroDavidArzolaSaavedra did you have another solution to skip this issue?
