### ISSUE TITLE
npx pod-install passing unrecognized args as working directory

### ISSUE THREAD

**Issue by sam1463** [expo/expo#32914]
### Summary

Apologies if there was a better place to open this issue. I did not see an option for reporting issues on the `pod-install` cli directly, so this seemed like the closest option.

We are running `npx pod-install` with args that I thought were still supported, but perhaps are not: `npx pod-install --no-repo-update --verbose`. It looks like perhaps verbose is now the default and not needed, but I thought `no-repo-update` would still work. With the most recent update (0.3.1), [the behavior was changed](https://github.com/expo/expo/pull/32848/files#diff-584931a09cfb8354b3226f5a25227f828daae197c39ee88bcf81058003131f18R98) so that this command started suddenly failing because now it's using `--no-repo-update` as the current working directory, which of course doesn't exist.
It looks like this was intended to support functionality where the first argument should be treated as the directory to use. Is this something where we just need to update our usage? If so, happy to close this. I just wanted to call it out because it was a breaking change, so it may be affected others as well.

### SDK Version

0.3.1 of pod-install npm module

### Environment

```text
this is using npx pod-install, which uses pod-install@0.3.1
This issue does not occur on pod-install@0.3.0 if I install that manually.
```

### Minimal reproducible example

https://github.com/sam1463/npx-pod-install-repro

**Comment by brentvatne** [comment]
this is fixed in pod-install@0.3.2!
