### ISSUE TITLE
[SDK 52] `babel-preset-expo` process.env.EXPO_OS cannot replace

### ISSUE THREAD

**Issue by gavinliu** [expo/expo#32911]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by talaikis** [comment]
```
The global process.env.EXPO_OS is not defined. This should be inlined by babel-preset-expo during transformation
```

**Comment by gavinliu** [comment]
> ```
> The global process.env.EXPO_OS is not defined. This should be inlined by babel-preset-expo during transformation
> ```

thx reply, see discord threads

https://discord.com/channels/695411232856997968/1109053181247361054/threads/1306648129453690902
