### ISSUE TITLE
SDK 52 expo-sqlite failing in web build

### ISSUE THREAD

**Issue by adamantzg** [expo/expo#32918]
### Minimal reproducible example

https://github.com/adamantzg/testsdk52

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

After starting the expo start and choosing w to open browser, web shows blank page and in the console there is an error with stack trace like this (no such issue in SDK 51):

Uncaught Error: Cannot find native module 'ExpoSQLite'
    at requireNativeModule (entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:81976:11)
    at entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:127147:66
    at loadModuleImplementation (entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:256:7)
    at guardedLoadModule (entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:163:14)
    at metroRequire (entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:83:75)
    at entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:126141:44
    at loadModuleImplementation (entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:256:7)
    at guardedLoadModule (entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:163:14)
    at metroRequire (entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:83:75)
    at entry.bundle?platform=web&dev=true&hot=false&transform.engine=hermes&transform.routerRoot=app&unstable_transformProfile=hermes-stable:126093:25

The reproducible example is basic expo app created with create-expo-app and expo-sqlite installed using npx expo install. 

### Environment

```text
System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.8.1 - /usr/local/bin/npm
      Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/tvrtko/.gem/ruby/3.3.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.6 => 52.0.6 
      expo-router: ~4.0.5 => 4.0.5 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.4.1
```

### Expo Doctor Diagnostics

```text
Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: @expo/metro-runtime
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.
```

**Comment by brentvatne** [comment]
expo-sqlite does not support web: https://docs.expo.dev/versions/latest/sdk/sqlite/

that said, we could possibly make it so you can import the package, it just wouldn't do anything. use `.native.js` or `.web.js` file extensions to only import expo-sqlite in the appropriate places. we will add support for expo-sqlite on web in the future

**Comment by adamantzg** [comment]
I know that it doesn't support web and I am using jsstore for web. But in prior versions, the same code worked on web,now it doesn't. I implemented platform specific file solution (native.ts file) and now it's ok. I expected that android/ios only packages like expo-sqlite were just ignoring the web, not crashing because the same codebase should work on web and mobile platforms.

**Comment by Kudo** [comment]
@adamantzg thanks for sharing your use case. i was thinking that for modules without web support. it's better to have an error in build time (bundle time) rather than runtime. the code you had for sdk 51 would probably having a web runtime crash if the call path goes to expo-sqlite operations. the relevant code is at https://github.com/expo/expo/blob/672a1e49651614f047f5f104fa2bb65ac7fb050e/packages/expo-sqlite/src/ExpoSQLiteNext.ts#L9.

now from sdk-52, you will know the problem earlier and prevent the error by using `.native.js` or `.web.js`.
i'm open to get feedback from you and know which way is better.

**Comment by anhkieet** [comment]
> [@adamantzg](https://github.com/adamantzg) thanks for sharing your use case. i was thinking that for modules without web support. it's better to have an error in build time (bundle time) rather than runtime. the code you had for sdk 51 would probably having a web runtime crash if the call path goes to expo-sqlite operations. the relevant code is at
> 
> [expo/packages/expo-sqlite/src/ExpoSQLiteNext.ts](https://github.com/expo/expo/blob/672a1e49651614f047f5f104fa2bb65ac7fb050e/packages/expo-sqlite/src/ExpoSQLiteNext.ts#L9)
> 
> Line 9 in [672a1e4](/expo/expo/commit/672a1e49651614f047f5f104fa2bb65ac7fb050e)
> 
>  throw new Error('Unimplemented'); 
> .
> now from sdk-52, you will know the problem earlier and prevent the error by using `.native.js` or `.web.js`. i'm open to get feedback from you and know which way is better.

Do you plan to do web support?

**Comment by kuchta** [comment]
@anhkieet Seems like some experimental support is already there: [Expo SQLite - Web](https://docs.expo.dev/versions/latest/sdk/sqlite/#web-setup)
