### ISSUE TITLE
SDK 52 - Expo Router not navigating correctly to Stacks when using navigate/push

### ISSUE THREAD

**Issue by gusthavosouza** [expo/expo#32927]
### Minimal reproducible example

https://github.com/gusthavosouza/SRTParser

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Hi team,

After upgrading our App to expo SDK 52, the router has been acting strange.

E.g when navigating from Screen A to B and B to A a new Stack is created instead of navigating back to the previous one as mentioned on the docs from React navigation on: https://reactnavigation.org/docs/upgrading-from-6.x#the-navigate-method-no-longer-goes-back-use-popto-instead

The behaviour is completely different from the SDK 51, where when going from A to B and B to A it would just go back to previous screen.

"To avoid this confusion, we have removed the going back behavior from navigate and added a [new method popTo](https://reactnavigation.org/docs/stack-actions#popto) to explicitly go back to a specific screen in the stack"

Is there a way to avoid this using expo router? is there any new method that supports the pop with Params?

I am not sharing any reproducible repo as this started happening after the upgrade.

Thanks

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.7.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.2 - /usr/local/bin/node
      Yarn: 1.22.22 - ~/Library/pnpm/yarn
      npm: 6.14.17 - ~/.local/state/fnm_multishells/79590_1731621644470/bin/npm
      Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12483815
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.6 => 52.0.6 
      expo-router: ~4.0.5 => 4.0.5 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.1 => 0.76.1 
      react-native-web: ^0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.5.1
    Expo Workflow: bare
```

**Comment by markmccoid** [comment]
I'm not sure if this is related, but with SDK 52 I am also seeing strange behavior with Push and dynamic routes.

**Minimal reproducible example**
https://github.com/markmccoid/routerbugExpo52

**Summary**
In the example, on the Test tab, there is a link that pushes to a dynamic route [id], this is fine.  On that dynamic route, there is a link that pushes onto the same dynamic route [id] with a new id, but you don't get the animation as you normally would.  The ID changes, so it technically navigated to the route, however it wasn't pushed for if you go back, it takes you to the starting (non-dynamic) route.

Here is a quick screen capture of what I am seeing.
![expo52routerissue](https://github.com/user-attachments/assets/228371bc-6f55-4342-8812-fb8029a8e0a5)

https://app.screencast.com/EcxoxNRVv4qam

**Comment by AnhHT** [comment]
Workaround

Screen A
```
router.navigate('/B')
```

Screen B
```
import { CommonActions } from '@react-navigation/core'
import { useNavigation } from 'expo-router'

export default function B() {
    const router = useNavigation()
    
    const handleBack = () => {
       router.dispatch(
        CommonActions.navigateDeprecated('A', ...your params here...)
      )
    }
}
```
CommonActions.navigateDeprecated(name of your screen, params)

**Comment by halilyildiz384589** [comment]
TouchableOpacity isn't working on IOS device 
After updating to the latest version, SDK52, my app has stopped working on iOS devices, although it was previously working fine on both iOS and Android. Specifically, the TouchableOpacity button and card components are not functioning correctly on iOS.

**Comment by AnhHT** [comment]
> TouchableOpacity isn't working on IOS device After updating to the latest version, SDK52, my app has stopped working on iOS devices, although it was previously working fine on both iOS and Android. Specifically, the TouchableOpacity button and card components are not functioning correctly on iOS.

You can use <Pressable> for better experience

**Comment by halilyildiz384589** [comment]
> > TouchableOpacity isn't working on IOS device After updating to the latest version, SDK52, my app has stopped working on iOS devices, although it was previously working fine on both iOS and Android. Specifically, the TouchableOpacity button and card components are not functioning correctly on iOS.
> 
> You can use `<Pressable>` for better experience

I tried but it isn't still working.

**Comment by markmccoid** [comment]
@AnhHT - I will give that a try, but the main issue I was seeing is that Push is not Pushing a new screen onto the stack when linking to a Dynamic route from within that same Dynamic route.

Is anyone else seeing this?

**Comment by markmccoid** [comment]
@benkingcode Thanks for the confirm.  This seems like a big issue and wanted to make sure I wasn't missing something.

**Comment by markmccoid** [comment]
I haven't fully tested this, but I believe the issue I was having will be resolved using the [getId](https://reactnavigation.org/docs/screen/#id) callback when setting up your screens.

Purpose of getId
By default, React Navigation identifies screens by their name. If you navigate to a screen with the same name multiple times, it will either update the existing screen or go back to it rather than pushing a new instance onto the stack. However, by using getId, you can make React Navigation treat screens with different parameters as distinct instances, even if they share the same name.

In my _layout.tsx
```
<Stack.Screen
   name="[testId]"
   options={{ title: "TestStack" }}
   getId={({ params }) => params.testId}
/>
```
The above is a dynamic route, but I'm guessing this will work fine for a static route that receives parameters.  You just tell it in the getId what parameter makes the push unique.

I'm not sure if this is exactly what others were having an issue with and I haven't fully tested, but wanted to throw it out if others are seeing this behaviour.

**Comment by DavidAmyot** [comment]
Same issue here, though instead of using `navigateDeprecated`, we just used the `popTo` method since in our case we were using navigate considering it could go backwards.

```tsx
navigation.dispatch(
  StackActions.popTo("[route]/route-locations-list", {
    route: routeId,
  }),
);
```

**Comment by voslartomas** [comment]
@gusthavosouza Hello, is this really fixed for you as @marklawlor closed this issue due to `dismissTo` implementation? But to me it seems like different problem, we are also seeing this change in routing, when you expect navigate to simply go back if route was already opened before, as it was behaving pre 52 version.

**Comment by StarCaptain17** [comment]
> TouchableOpacity isn't working on IOS device After updating to the latest version, SDK52, my app has stopped working on iOS devices, although it was previously working fine on both iOS and Android. Specifically, the TouchableOpacity button and card components are not functioning correctly on iOS.

Having the same issue over here. onLongPress doesn't work either. Started replacing some imports with react-native-gesture-handler, but then styles don't work the same. Anyone find a fix for this? I am using React Navigation 6 and Expo 52.0.11

**Comment by gusthavosouza** [comment]
@StarCaptain17 @halilyildiz384589 I think it would be better for us to create a new ticket, as this does not seem to be related to the issue for navigation and adding support for popTo with params: https://reactnavigation.org/docs/upgrading-from-6.x/#the-navigate-method-no-longer-goes-back-use-popto-instead the PR added support to popTo on Expo router as dismissTo, this is was the issue that I encountered, I would open a new issue just for a better visibility.

I

**Comment by kriit24** [comment]
> > TouchableOpacity isn't working on IOS device After updating to the latest version, SDK52, my app has stopped working on iOS devices, although it was previously working fine on both iOS and Android. Specifically, the TouchableOpacity button and card components are not functioning correctly on iOS.
> 
> Having the same issue over here. onLongPress doesn't work either for react-native TouchableOpacity. Started replacing some imports with react-native-gesture-handler, but then styles don't work the same. Anyone else experiencing and.or find a fix for this? I am using React Navigation 6 and Expo 52.0.11

Also does not work on my IOS, replaced TouchableOpacity with Pressable, but this also does not work.
I clicked 10 times before onPress worked.
Iphone 7, IOS 15.8.3


`
let NavigationContent = () => <Text>sisu</Text>;
    let btn = <Pressable style={{borderWidth: 1}} onPress={() => {

        alert('sa');
        //this.props.navigation.goBack()
    }}>
        <Text>tagasi</Text>
    </Pressable>;

    let ScreenOptions = {
        headerStyle: css.header,
        orientation: 'all',
        headerShown: false,
        presentation: 'card',
        animationTypeForReplace: 'push',
        animation: 'fade_from_bottom',
    };
    let NavigationOptions = ({navigation, route}) => {

        return {
            ...ScreenOptions, ...{
                headerBackTitle: null,
                headerTitle: props => null,

                //if header back button not needed then set to null
                headerLeft: props => btn,

                //if header right not needed then set to null
                headerRight: props => btn,

                tabBarVisible: false,
                headerShown: true,
                headerReloadOnFocus: true
            }
        };
    };

    return (
        <NavigationContainer role="navigation">
            <Stack.Navigator initialRouteName="HomeScreen">

                <Stack.Screen name="HomeScreen" component={NavigationContent} options={NavigationOptions} listeners={({navigation, route}) => ({
                    focus: (e) => {
                        global.navigationRoute = route;
                    },
                })}/>
            </Stack.Navigator>
        </NavigationContainer>
    );
`

**Comment by cameronmurphy** [comment]
This is very confusing. `.dismissTo()` now behaves the way `.navigate()` used to behave. Essentially navigate forwards if the route isn't on the stack, navigate backwards if it is.

We have situations where it's not guaranteed that the desired route is on stack already... but calling `.dismissTo()` to perform a navigation action that adds another route to the stack is pretty unintuitive.

**Comment by kav** [comment]
Also seeing `dismissTo` with params in the url crashes the application. Will look for a min repro
