### ISSUE TITLE
LinearGradient with MaskedView not working on Android

### ISSUE THREAD

**Issue by bhavesh-trentium** [expo/expo#32934]
### Minimal reproducible example

its working well on iOS but on a Android not. On an Android, it shows a Red Color Background

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build

### Summary

I am using a MaskedView and LinearGradient. To create a GradientText its working well on iOS but on a Android not.
On an Android, it shows a Red Color Background.

```
import { LinearGradient } from 'expo-linear-gradient';
import MaskedView from '@react-native-masked-view/masked-view';

 <MaskedView maskElement={<Text style={style}>{text}</Text>}>
      <LinearGradient
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        colors={textColor}>
        <Text style={[style, { opacity: 0 }]}>{text}</Text>
      </LinearGradient>
    </MaskedView>
```
```
 "react-native": "0.72.6",
  "expo": "^49.0.21",
  "expo-linear-gradient": "~12.3.0",
  "@react-native-masked-view/masked-view": "0.2.9",
```

### ANDROID
![screenshot_2024-11-14-16-27-15-433_io smatchit app_720](https://github.com/user-attachments/assets/9973cae0-0aac-4d66-a083-1d3af75c8231)

### iOS
![image](https://github.com/user-attachments/assets/607a3a07-bd10-404a-899c-2b79fad2b71e)

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-34 | Google APIs Intel x86_64 Atom, android-VanillaIceCream | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Not working this on my command
```

**Comment by brentvatne** [comment]
hi there!

- your report is for sdk 49. please always test with the latest sdk before reporting issues, each sdk includes many fixes and improvements
- the library you're reporting the issue with is indicated to have experimental support for android [in the docs](https://docs.expo.dev/versions/latest/sdk/masked-view/), and that you should report issues to that repo 
<img width="955" alt="image" src="https://github.com/user-attachments/assets/cb62aa02-0c36-450a-9f98-c79dcd6e825d">
- you did not provide a minimal reproducible example (i cannot just clone a repository and run the code). [learn more](https://stackoverflow.com/help/minimal-reproducible-example). this is a standard requirement for creating issues in open source projects. here is an example of one: https://snack.expo.dev/@brents/privileged-orange-turkish-delight. it looks like it works correctly on sdk 51 but may not work fully correctly with sdk 52 / new arch. if you'd like, you can report this issue to the masked-view repo!

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/29d0e01e-d385-4ba7-abe0-8b85fd6532a6">

**Comment by bchappui** [comment]
And same issue :)

**Comment by brentvatne** [comment]
we bumped masked-view to the latest version, including a fix from our very own @alanjhughes: https://github.com/react-native-masked-view/masked-view/pull/228 - so run `npx expo install --fix` and create a new dev build or download the latest version of expo go from store / expo cli to get it. if you still are having issues, please create a new issue with a minimal reproducible example
