### ISSUE TITLE
tsconfig.json is ignored

### ISSUE THREAD

**Issue by vietnogi** [expo/expo#3294]
Steps to Reproduce

1. Modify tsconfig.json
2. Run expo start
3. changes in tsconfig.json is ignored

Expected Behavior

Changes in tsconfig.json should have an affect.

**Comment by wcandillon** [comment]
I've made a quick video on how to setup a typescript project with expo: https://www.youtube.com/watch?v=-3htNX9EAVQ. Does it help?

**Comment by msevestre** [comment]
@wcandillon This is a great video. Thanks for taking the time to recording and sharing it!

**Comment by ikatun** [comment]
@wcandillon I've managed to create a typescript expo project following the steps in your article, but Expo (tried both with sdk31 and sdk32) still ignores the tsconfig file, it probably uses internal tsconfig somewhere without giving us an option to override it.

**Comment by ide** [comment]
An external tsconfig.json file should work now with `tsc`. To be clear, tsconfig.json and `expo start` are unrelated -- `expo start` uses Babel, which doesn't perform type checking.

**Comment by shamilovtim** [comment]
hello, is there a way to have babel respect `tsc --noEmit` and display compile time errors in the bundler terminal watch console? this would be a significant upgrade in user experience. i know the compilation time is very short with babel, but not having the entire project scanned by the compiler is a big disadvantage
