### ISSUE TITLE
iOS: Build waiting in queue ? Why?

### ISSUE THREAD

**Issue by aghahuseynov** [expo/expo#3295]
https://expo.io/builds/a30ceba0-ffb1-4ecc-babb-ad3bb6f536b3

**Comment by AdamJNavarro** [comment]
Hey @aghahuseynov,

Sometimes our builders need to put builds in a queue in order to properly handle load balance. You can check turtle builder status here: https://expo.io/turtle-status Please refrain from creating github issues for this in the future.

Cheers,

Adam
