### ISSUE TITLE
[docs] iOS app icon config docs unclear

### ISSUE THREAD

**Issue by RyanTG** [expo/expo#32959]
## Overview

The current docs for the new light/dark/tinted iOS icon options do not include a key for a path to the assets.

## More details

With the new light/dark/tinted iOS icon option, we have three assets. The json example in the docs includes various keys, but does not appear to have a key for "here is where the light/dark/tinted assets can be found". How does the app know that, for example, "dark" is to use "my-cool-dark-icon.png"?

I tried to add in a key called "path" and that did not work. **Is there an undocumented key, or like a "default" naming convention that is not documented?**

Here is what I would expect (see the "path" key, as an example, added to each of these):
```{
  "description": "Configuration that is specific to the iOS platform icons.",
  "type": "object",
  "properties": {
    "light": {
      "path: "app/assets/images/ios-icon.png",
      "description": "The light icon. It will appear when neither dark nor tinted icons are used, or if they are not provided.",
      "type": "string",
      "meta": {
        "asset": true,
        "contentTypePattern": "^image/png$",
        "contentTypeHuman": ".png image",
        "square": true
      }
    },
    "dark": {
      "path: "app/assets/images/ios-icon-dark.png",
      "description": "The dark icon. It will appear for the app when the user's system appearance is dark. See Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/app-icons#iOS-iPadOS) for more information.",
      "type": "string",
      "meta": {
        "asset": true,
        "contentTypePattern": "^image/png$",
        "contentTypeHuman": ".png image",
        "square": true
      }
    },
    "tinted": {
      "path: "app/assets/images/ios-icon-tinted.png", 
      "description": "The tinted icon. It will appear for the app when the user's system appearance is tinted. See Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/app-icons#iOS-iPadOS) for more information.",
      "type": "string",
      "meta": {
        "asset": true,
        "contentTypePattern": "^image/png$",
        "contentTypeHuman": ".png image",
        "square": true
      }
    }
  }
}```

### Link to the related docs page

https://docs.expo.dev/versions/v52.0.0/config/app/#icon-2

### Anything else?

_No response_

**Comment by brentvatne** [comment]
@Simek - this is related to ENG-13908

**Comment by brentvatne** [comment]
@RyanTG - the answer to your question here though is that each of those keys is a string. here is an example of this in action: https://github.com/brentvatne/microfoam-app/blob/4ff82cba918e576c5bc81a7d9fbc627e655337a1/apps/mobile/app.config.ts#L13-L18

**Comment by RyanTG** [comment]
Thank you!

I use expo tools for vscode. But, in this case I am not seeing any autocompletes in my app.config.js (not using typescript yet). hmm.
