### ISSUE TITLE
[SDK52] [expo/fetch] Unwanted response data buffering

### ISSUE THREAD

**Issue by matthiasbayer** [expo/expo#32950]
### Minimal reproducible example

https://github.com/matthiasbayer/expo-fetch-buffer-bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Calling `fetch` to read a streamed response seems to buffer the response messages up to around ~500 characters before actually returning the first chunk of the response.

<img width="567" alt="image" src="https://github.com/user-attachments/assets/cf90ccb8-3087-4da3-bbcd-f522128ea5e5">

Each dot is one message streamed chunk returned from the http endpoint. Clearly visible, the first few hundred characters are buffered together somewhere. This is unwanted behavior.

Expected behavior: each chunk is rendered immediately.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/Library/Caches/fnm_multishells/7155_1731685240576/bin/node
      npm: 10.2.4 - ~/Library/Caches/fnm_multishells/7155_1731685240576/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by matthiasbayer** [comment]
Just verified that this is still happening with the latest expo version `52.0.9`

**Comment by matthiasbayer** [comment]
@Kudo I just attached a minimal reproduction example. 

This looks to me like there is some buffer in the native layer that holds back data before forwarding it to the JS context.

**Comment by matthiasbayer** [comment]
You guys are probably super busy with SDK52 bugfixes right now after the release. Happy to take a stab at this myself, but I'm honestly a bit lost where to start. Not even sure how to debug the native layer. Can anyone point me into the right direction?

**Comment by Kudo** [comment]
sorry for the late update. the problem seems fine on android. as far as i can tell, the first chunk with around 512 bytes is coming from URLSessionDataTask. maybe it's an ios system default behavior. i'll investigate more whether i can adjust the buffer chunk size.
in the meantime, does the buffer behavior have any blocker for your app?

**Comment by Kudo** [comment]
a trick mentioned from [the issue](https://developer.apple.com/forums/thread/64875) and [stackoverflow](https://stackoverflow.com/questions/21816691/streaming-chunked-http-and-nsurlsession-hanging) would be adding a content-type. trying to add a content-type to your api should help

```patch
--- a/apps/web/app/api/stream/route.ts
+++ b/apps/web/app/api/stream/route.ts
@@ -45,4 +45,5 @@ const headers = {
   "Access-Control-Allow-Origin": "*",
   "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
   "Access-Control-Allow-Headers": "Content-Type, Authorization",
+  "Content-Type": "application/octet-stream",
 };
```

**Comment by matthiasbayer** [comment]
Thanks Kudo for taking a look at this 🙏 Very interesting to hear it doesn't affect Android! 

Let me try the workaround you posted. This unexpected behavior currently degrades the UX when using the Vercel AI SDK on React Native, because the first parts of the LLM response feel delayed and choppy.

**Comment by matthiasbayer** [comment]
@Kudo wow! Adding the suggested `Content-Type` header indeed solved the problem 🎉

**Comment by Kudo** [comment]
cool, good to know it helps. thanks @matthiasbayer.
i'm closing this issue. please let me know if there are any further questions
