### ISSUE TITLE
[SDK52][react-native-maps] App crashes on iOS

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#32958]
### Minimal reproducible example

https://snack.expo.dev/@brodanoel/react-native-maps-not-working

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Seems like with the New Arch enabled, `react-native-maps` crashes the app when the markers are mounted and unmounted.

Here a serie of issues that need to be fixed on `react-native-maps`, and then we'll update the recommended versions on SDK 52:

1. https://github.com/react-native-maps/react-native-maps/issues/5217
2. https://github.com/react-native-maps/react-native-maps/issues/5214
3. https://github.com/react-native-maps/react-native-maps/issues/5207
4. https://github.com/react-native-maps/react-native-maps/issues/5206

All of them seems to be related to the same bug in the behind.

PS.: Forget about the wrong version on `expo-doctor`. I've tried 1.18.0 and 1.20.20, and all of them are reproducing the same bug.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 12.7.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
      Watchman: 2024.04.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      react: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
    npmGlobalPackages:
      eas-cli: 13.2.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Unsupported on New Architecture: expo-background-fetch
Untested on New Architecture: expo-quick-actions
No metadata available: @amplitude/analytics-react-native, country-emoji, duix, haversine-distance, i18n-js, lodash, react-native-uuid, rn-prompt, sunrise-sunset-js, use-interval
Advice:
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

The following packages should be updated for best compatibility with the installed expo version:
  react-native-maps@1.20.0 - expected version: 1.18.0
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

**Comment by brentvatne** [comment]
it looks like you're not using the recommended version of react-native-maps, although it's unclear to me if that would actually help with this issue. regardless, we don't track issues for third party libraries here, even if they are libraries that we include in expo go

**Comment by Pabloolr** [comment]
The same problem has happened to me, when I updated to sdk52 if I have many markers on the map they stop being displayed, also the custom markers that have images appear cut off and their size cannot be adjusted.

**Comment by ramonespmat** [comment]
This is happening to me too. Updated to Expo 52 and suddenly my app crashes when displaying markers on react native maps. I honestly dont know what to do

**Comment by BrodaNoel** [comment]
@ramonespmat you need to wait until react-native-maps fixes it, and then Expo will have to update the compatible version to the one who fixes it

**Comment by MohamedChahik** [comment]
Hello, did you find a solution because I have the same problem. When I update expo 52 and react native maps. I have directly crash when I try to open my map

**Comment by BrodaNoel** [comment]
@MohamedChahik no fix available yet. Try disabling NewArch and it will work again.

**Comment by hassanelaasemy** [comment]
i resolve by doing this in package.json :

 "expo": {
    "doctor": {
      "reactNativeDirectoryCheck": {
        "exclude": [
          "react-native-maps",
        ]
      }
    }
  }

**Comment by ebdem** [comment]
> i resolve this issus by doing this in package.json :
> 
> "expo": { "doctor": { "reactNativeDirectoryCheck": { "exclude": [ "react-native-maps", ] } } }

hi @hassanelaasemy  could you share your all package.json cause i added this block in my package.json file but when i run the `npx expo-doctor@latest` it gives me a change react-native-maps


` expo@52.0.14 - expected version: ~52.0.18
  expo-dev-client@5.0.5 - expected version: ~5.0.6
  expo-location@18.0.3 - expected version: ~18.0.4
  expo-splash-screen@0.29.13 - expected version: ~0.29.18
  expo-system-ui@4.0.5 - expected version: ~4.0.6
  expo-updates@0.26.9 - expected version: ~0.26.10
  lottie-react-native@7.0.0 - expected version: 7.1.0
  react-native@0.76.1 - expected version: 0.76.5
  react-native-maps@1.20.1 - expected version: 1.18.0
  react-native-pager-view@6.6.1 - expected version: 6.5.1
  react-native-screens@4.0.0 - expected version: ~4.1.0
  react-native-svg@15.10.0 - expected version: 15.8.0
  react-native-webview@13.12.2 - expected version: 13.12.5
  @react-navigation/bottom-tabs@7.0.0-rc.36 - expected version: ^7.0.0
  @react-navigation/native@7.0.0-rc.21 - expected version: ^7.0.0`
