### ISSUE TITLE
SDK52 react-native NativeModules is empty

### ISSUE THREAD

**Issue by kriit24** [expo/expo#32966]
### Minimal reproducible example

https://github.com/kriit24/sdk52-react-native-NativeModules-example.git

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

console.log(NativeModules)
expected to have object inside NativeModules, but got empty object

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11255304
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      react: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment]
this is expected behavior of the new architecture https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/BatchedBridge/NativeModules.js

**Comment by kriit24** [comment]
im trying to get locale settings

`const locale = Platform.OS === 'ios' ? (NativeModules.SettingsManager.settings.AppleLocale ||
                    NativeModules.SettingsManager.settings.AppleLanguages[0]) : NativeModules.I18nManager.localeIdentifier;`

**Comment by brentvatne** [comment]
@kriit24 - you should import the Settings module directly - https://reactnative.dev/docs/0.76/settings

alternatively, use expo-localization to get this information: https://docs.expo.dev/versions/latest/sdk/localization/
