### ISSUE TITLE
[SDK 52] Expo DOM Components not showing up on Expo Go and Development Builds

### ISSUE THREAD

**Issue by StefSchalks** [expo/expo#32998]
### Minimal reproducible example

https://github.com/StefSchalks/app-52-2

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

I was trying Expo DOM Components. What happens is I get a full height white area without any content in it (see image) while the content expected result is a "Hello World" h1 shown in the second image. The second image is from an Android build with the following specifications:
```
"preview": {
      "android": {
        "buildType": "apk"
      }
    },
```

> The screenshot of the version in Expo Go and development builds:
![Screenshot_20241114_205235_Expo_Go](https://github.com/user-attachments/assets/f8b092dd-d9ea-494d-9782-4e791f71179f)

> The screenshot of the version in build android version:
![Screenshot_20241117_180843_app-52-2](https://github.com/user-attachments/assets/aab78fb0-8ef6-48f8-8e0e-ab1e41e6065a)

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      expo: ^52.0.0 => 52.0.7
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by kennethstarkrl** [comment]
I have the same issue.

**Comment by deadbeefiv** [comment]
Me too

**Comment by ClaudiuStelian** [comment]
Same here. The TabBar Icons are not even rendering anymore :(

![image](https://github.com/user-attachments/assets/a929c544-6c5d-4e7b-bd1a-6f83be6a2bdb)

**Comment by Sietze111** [comment]
I'm getting the sense that this is somehow related to windows.

**Comment by StefSchalks** [comment]
> I'm getting the sense that this is somehow related to windows.

@Sietze111 Would the build process for Expo Go be able to change based on if I use Windows or Mac?

**Comment by Sietze111** [comment]
> > I'm getting the sense that this is somehow related to windows.
> 
> @Sietze111 Would the build process for Expo Go be able to change based on if I use Windows or Mac?

I have nothing to back this up but the feeling that if it was not working for ios we would see more people noting this.

**Comment by quitran97** [comment]
I got this error when tried to run on android 
<img width="420" alt="image" src="https://github.com/user-attachments/assets/3a7fa953-6bb7-48fb-ac28-a498f34fd88a">

**Comment by Krucial92** [comment]
I am getting this same error on Android with `react-native-webview`, ios is fine

**Comment by StefSchalks** [comment]
@Kudo Are there any updates on this?

**Comment by AliVillegas** [comment]
a workaround I found when using react-native-webview on android is to change the prop        decelerationRate={0.998}  so it uses a float value inside <WebView/>, hope it helps someone

**Comment by madanbazgai** [comment]
I am facing same issue.
Currently I'm using Linux (Ubuntu)
Expo Go on android phone.

When I run it on web it show the dom components but not on expo go app.

**Comment by StefSchalks** [comment]
Thanks! Just a quick question. How can this new version be used? Is this version automatically included when using the `create-expo-app` command?

**Comment by Monkhai** [comment]
Hey! a bit confused on why this is closed but still not working? I noticed that it would render if the dom component is the only element being rendered but otherwise it won't render. the dev tools show a tag but it does not render

**Comment by StefSchalks** [comment]
@Monkhai same here. My best guess is that it's fixed but not in the expo upgrade/update or create commands yet.

**Comment by yurtle-paul** [comment]
> a workaround I found when using react-native-webview on android is to change the prop decelerationRate={0.998} so it uses a float value inside , hope it helps someone

This fix worked for me as well.

From the react-native-webview docs:

`
A floating-point number that determines how quickly the scroll view decelerates after the user lifts their finger. You may also use the string shortcuts "normal" and "fast" which match the underlying iOS settings for UIScrollViewDecelerationRateNormal and UIScrollViewDecelerationRateFast respectively:

normal: 0.998
fast: 0.99 (the default for iOS web view)
`

So seems pretty safe as far as workarounds go as the string values for this prop were just shortcuts anyway.

**Comment by Krucial92** [comment]
> a workaround I found when using react-native-webview on android is to change the prop decelerationRate={0.998} so it uses a float value inside , hope it helps someone

Nice one! Thank you so much for this!

I had `decelerationRate="normal"` which was causing this to crash on Android, actually neither "normal" or "fast" works, either removing that prop or using `0.998` works. I just removed that prop on the webview and works without issue.

**Comment by aLemonFox** [comment]
> I'm getting the sense that this is somehow related to windows.

I can confirm that this is a Windows issue. Using Expo 52.0.11 on windows the component is not rendered, but when I did a bundle on my Mac it works fine, no changes to the code. Might be fixed in https://github.com/expo/expo/pull/33114 but I cannot confirm as I am not sure in what version these changes are released.

**Comment by JustJoostNL** [comment]
For me it also still isn't showing, just an empty "box".

**Comment by mgscreativa** [comment]
> a workaround I found when using react-native-webview on android is to change the prop decelerationRate={0.998} so it uses a float value inside , hope it helps someone

Worked for me in SDK 52 and Dev Build

**Comment by tylerjbainbridge** [comment]
> For me it also still isn't showing, just an empty "box".

did you find a solution for this?

**Comment by yubarajoli77** [comment]
> a workaround I found when using react-native-webview on android is to change the prop decelerationRate={0.998} so it uses a float value inside , hope it helps someone

Worked for me. I upgraded to expo 53 from 51 and start crashing in android only. The decelerationRate= "normal" is the culprit. I removed it and everything is normal.
