### ISSUE TITLE
await Permissions.askAsync(Permissions.NOTIFICATIONS);   connot return first time

### ISSUE THREAD

**Issue by kanapan** [expo/expo#3299]
const { status: existingStatus } = await Permissions.getAsync(
      Permissions.NOTIFICATIONS
    );
    let finalStatus = existingStatus;

    // only ask if permissions have not already been determined, because
    // iOS won't necessarily prompt the user a second time.
    if (existingStatus !== 'granted') {
      // Android remote notification permissions are granted during the app
      // install, so this will only ask on iOS
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;
    }

    // Stop here if the user did not grant permissions
    if (finalStatus !== 'granted') {
      return;
    }

    // Get the token that uniquely identifies this device
    let token = await Notifications.getExpoPushTokenAsync();
    this.setState({
      tokenNotification: token,
    });

first time run ask user grant permission 
 cannot get status in await Permissions.askAsync(Permissions.NOTIFICATIONS);

first time only

**Comment by hochmanjoel** [comment]
How did you end up getting this to work?
