### ISSUE TITLE
APK Install Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by timtawan** [expo/expo#330]
Hi

I'm trying to build APK file and install to my phone device

command I ran
> expo build:android
- With put new Keystone from my local
- once build finished download apk and ran command "
> adb -d install -r [APK path]
and tried
> adb -d install [APK path]

It's failed 
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

I assume that about keystone but HOW? 

Expo Version

>
    "expo": "^18.0.4",
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-native-action-button": "^2.7.1",
    "react-native-check-box": "^1.0.4",
    "react-native-dialogs": "^0.0.19",
    "react-native-elements": "^0.13.0",
    "react-native-swiper": "^1.5.4",
    "react-native-wheel": "^1.1.3",
    "react-navigation": "^1.0.0-beta.11",
    "react-navigation-is-focused-hoc": "^1.0.0",
    "react-redux": "^5.0.5",
    "recompose": "^0.23.5",
    "redux": "^3.7.0",
    "redux-thunk": "^2.2.0"

Thank you

**Comment by jesseruder** [comment]
What Android device are you using? and what Android OS version?

**Comment by dikaiosune** [comment]
@timtawan can you provide your Expo username and your android package name? I think we may need to check the build logs.

**Comment by timtawan** [comment]
@dikaiosune thank you for getting back to me.

My Expo username is timtawan

Thank you.

**Comment by dikaiosune** [comment]
Cool, and what's the android package you've specified in exp.json/app.json?

**Comment by dikaiosune** [comment]
Giving this a close since it's been a little while since hearing back. Post back and we'll reopen if this is still causing problems for you! Thanks!
