### ISSUE TITLE
Expo router fails when running under a test environment

### ISSUE THREAD

**Issue by josiahsrc** [expo/expo#33006]
### Minimal reproducible example

https://github.com/josiahsrc/expo-router-context-error

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Expected behavior: The app should be able to run with `NODE_ENV=test`

Actual behavior: The app crashes when running with `NODE_ENV=test`
<img width="709" alt="image" src="https://github.com/user-attachments/assets/6c771c9d-6e41-409e-99f2-2aa42516cfa4">

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Expo Router requires some environment variables to be set to operate. These are normally provided by the `expo-router` config plugin.

The recommended approach for testing is to use the testing utilities provided https://docs.expo.dev/router/reference/testing/

Alternatively, you can follow this setup which avoids the need to set `EXPO_ROUTER_APP_ROOT` https://docs.expo.dev/router/reference/troubleshooting/
