### ISSUE TITLE
[SDK52][expo-network] getNetworkStateAsync reports no connection on iOS

### ISSUE THREAD

**Issue by GiyoMoon** [expo/expo#33012]
### Minimal reproducible example

https://github.com/GiyoMoon/expo-network-bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

After updating to `expo@52.0.0` and `expo-network@7.0.0`, `getNetworkStateAsync` reports no connection (`{"isConnected": false, "isInternetReachable": false, "type": "NONE"}`) when using in an iOS simulator. I don't own a physical iOS device, so I wasn't able to test it with a real device. On an android emulator and real android device, it works as expected.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 3.7.1 - /Users/jasi/.nix-profile/bin/fish
    Binaries:
      Node: 22.10.0 - ~/.nix-profile/bin/node
      Yarn: 1.22.22 - ~/.nix-profile/bin/yarn
      npm: 10.9.0 - ~/.nix-profile/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /Users/jasi/.nix-profile/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 34, 35
        Build Tools: 33.0.1, 34.0.0, 35.0.0
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7 
      expo-router: ~4.0.6 => 4.0.6 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by augusthjerrild** [comment]
Same issue happens here, on a real iOS device.

**Comment by GiyoMoon** [comment]
Thanks, I updated the title as it seems to be a general iOS problem.

**Comment by Asekon** [comment]
This is critical as some of us rely on this package to either start the application or show a no-internet page.

**Comment by etothepowerofitimespiequalsminusone** [comment]
I temporarily switched back to [useNetInfo](https://www.npmjs.com/package/@react-native-community/netinfo). Maybe helps someone who can't wait for a fix.

**Comment by Asekon** [comment]
Is this fixed on version 7.0.2 ?  It's not working for me.

**Comment by chrfalch** [comment]
Should be fixed. I just created a new Expo app using `npx create-expo-app@latest` and installed the latest `expo-network` package by doing `npx expo install expo-network`, installing version 7.0.2 of the package.

Then I build the app (not in Expo-Go but using a [development build](https://docs.expo.dev/develop/development-builds/create-a-build/)) and verified that I had version 7.0.2 of expo-network installed - both in my `package.json` and in my `node_modules` folder.

Running the following code resulted in the correct network state being reported:

```ts
export default function HomeScreen() {
  const [networkState, setNetworkState] = useState<string | null>(null);
  useEffect(() => {
    getNetworkStateAsync().then((networkState) =>
      setNetworkState(JSON.stringify(networkState, null, 2))
    );
  }, []);

  return (
    <View style={styles.container}>
      <Text>Network state:</Text>
      <Text>{networkState}</Text>
    </View>
  );
}
```

<img width="358" alt="image" src="https://github.com/user-attachments/assets/e6f678b5-25f4-4898-9106-a997b8332925">

**Comment by GiyoMoon** [comment]
Thanks! I can confirm that it works with `7.0.2` on an iOS simulator.

**Comment by ProgramacionesWeb** [comment]
api.ts

<img width="920" alt="image" src="https://github.com/user-attachments/assets/70fdb4df-fe9c-4ef5-a855-524856d4d75d">


package-lock.json

<img width="868" alt="image" src="https://github.com/user-attachments/assets/c07d454b-5933-4b6b-8ca2-4bdabe4b31cc">

**Comment by chrfalch** [comment]
Yeah, but check `node_modules/expo-network/package.json` as well to ensure the right version.

**Comment by ProgramacionesWeb** [comment]
node_modules/expo-network/package.json

```
{
  "name": "expo-network",
  "version": "7.0.2",
  "description": "Provides useful information about the device's network such as its IP address, MAC address, and airplane mode status",
  "main": "build/Network.js",
  "types": "build/Network.d.ts",
  "scripts": {
    "build": "expo-module build",
    "clean": "expo-module clean",
    "lint": "expo-module lint",
    "test": "expo-module test",
    "prepare": "expo-module prepare",
    "prepublishOnly": "expo-module prepublishOnly",
    "expo-module": "expo-module"
  },
  "keywords": [
    "react-native",
    "expo",
    "expo-network"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/expo/expo.git",
    "directory": "packages/expo-network"
  },
  "bugs": {
    "url": "https://github.com/expo/expo/issues"
  },
  "author": "650 Industries, Inc.",
  "license": "MIT",
  "homepage": "https://docs.expo.dev/versions/latest/sdk/network/",
  "dependencies": {},
  "devDependencies": {
    "expo-module-scripts": "^4.0.0"
  },
  "peerDependencies": {
    "expo": "*",
    "react": "*"
  },
  "gitHead": "eb0d9b5b6ba8dd5b64e016e41166e42ced543a69"
}
```

**Comment by Asekon** [comment]
yeah it didnt work for me either, so i just opted for the hook instead.

**Comment by chrfalch** [comment]
Then you should have the correct version installed - try setting a breakpoint in `node_modules/expo-network/ios/NetworkModule.swift` here and step through your code in Xcode. The key difference in this fix is that we have a temporary network monitor that we use in the `getNetworkPathAsync` method - make sure you are executing the same code as in the image:

<img width="676" alt="image" src="https://github.com/user-attachments/assets/2c8e20e6-46fa-4ceb-bc88-2e605ebea4ca">
