### ISSUE TITLE
Missing react-navigation hook useIsFocused. Drawer/bottom-tabs screens not removed from DOM

### ISSUE THREAD

**Issue by fuelkoy** [expo/expo#33015]
### Minimal reproducible example

https://github.com/fuelkoy/my-app

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

(The minimal repo is made purely with `npx create-expo-app@latest` without any changes)
The react-navigation [documentation](https://reactnavigation.org/docs/upgrading-from-6.x/#the-unmountonblur-option-is-removed-in-favor-of-poptotoponblur-in-bottom-tab-navigator-and-drawer-navigator) states:

> The unmountOnBlur option is removed in favor of popToTopOnBlur in Bottom Tab Navigator and Drawer Navigator.
> ...
> It's still possible to achieve the old behavior of unmountOnBlur by using the useIsFocused hook in the screen.
> 

`expo-router` does not export this hook. On web navigating with Drawer/bottom-tabs and using `unmountOnBlur` removed the previous screens from the DOM. Now there is no way to remove the screens but they will remain in DOM.

**Problems:**
1. Imagine having for example Drawer navigator with 20 screens and all being in the DOM at the same time just having style `z-index: -1` on the inactive ones. Or having tabs that are hidden and the user has only couple of them. This makes web version with `expo-router` Drawer/bottom-tabs non-performant. 
2. e2e testing (for example playwrifght)  trusting on exact strings or labels will not work because they will notice x-number of same items from the other screens that are just hidden with style `z-index: -1`

 We have actually such use case. At the moment we cannot upgrade to `"expo": "~52.0.0"`.

**Example:**

First tab on the web page opening the first time
![Näyttökuva 2024-11-18 143940](https://github.com/user-attachments/assets/bb1927a5-ba4a-4cbf-8289-eb3ff3aa9afa)

Opening the second tab
![Näyttökuva 2024-11-18 143957](https://github.com/user-attachments/assets/0739f7de-4e3d-4a38-b72f-227462706396)

Going back to the first tab
![Näyttökuva 2024-11-18 144013](https://github.com/user-attachments/assets/95b82094-f927-42f8-9991-031c93d2e1e5)

Notice all the tab screens will remain in the DOM. Only the `z-index` value is changed. 

(Thank you for the awesome library)

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Expo Router is configuration wrapper around React Navigation, we do not maintain the React Navigation Drawer/Bottom Tabs components. If you do not believe these components work as expected, you will need to create an issue in the [React Navigation repro](https://github.com/react-navigation/react-navigation) so the maintainers of these components can address your feedback.

Expo Router doesn't re-export the all the React Navigation hooks, only the ones that we needed to modify to support the file-based approach. We recommend continuing to import these hooks from React Navigation if needed

**Comment by fuelkoy** [comment]
@marklawlor Thank you for the response. When using expo-router should we then install react-navigation in addition? Also does using the functions from there (like for example useIsFocused hook in _layout.tsx to return null for all non focused screens) work 1-to-1 with expo-router?

**Comment by johannbuscail** [comment]
Any update ?

**Comment by fuelkoy** [comment]
@johannbuscail This can be solved like the following. Note this needs to be done to every exported screen.

```
import { useIsFocused } from "@react-navigation/native";
import React from "react";

export function withAutoUnmount<T extends {}>(Component: React.ComponentType<T>) {
    return function (props: T) {
        const isFocused = useIsFocused();
        return isFocused ? <Component {...props} /> : null;
    };
}


function HomeScreen() {
  return ( 
    .. The screen 
   )
}

export default withAutoUnmount(HomeScreen);
```
