### ISSUE TITLE
Refreshcontrol not working in expo client

### ISSUE THREAD

**Issue by raajnadar** [expo/expo#3302]
### Environment

https://forums.expo.io/t/refreshcontrol-not-working-in-expo-client/16836

### Steps to Reproduce

1. Open expo client
2. Try refreshing the home screen
3. The refreshcontrol is getting stuck and not refreshing.

### Expected Behavior

The refreshcontrol should not get stuck

(Write what you thought would happen.)

### Actual Behavior

The refreshcontrol is getting stucked

(Write what happened. Add screenshots!)

### Reproducible Demo

![refresh-control-expo](https://user-images.githubusercontent.com/17236768/51606110-fe7fe380-1f36-11e9-8e47-52d5e16eb523.gif)

I am able to reproduce this issue in android 7.1 device. (Just follow the steps that are given above)

**Comment by raajnadar** [comment]
I don't know how but the refresh control is working properly in expo client.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.

**Comment by raajnadar** [comment]
The issue is fixed.
