### ISSUE TITLE
Expo Notifications Token fails on Android - Requires Firebase initialization

### ISSUE THREAD

**Issue by Jaseyacey** [expo/expo#33030]
### Minimal reproducible example

https://github.com/Jaseyacey/fixturetest/tree/main

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When attempting to get push notification token using expo-notifications on Android, the following error occurs:
CopyError: Native module RNFBAppModule not found. Re-check module install, linking, configuration, build and install steps.
Steps to reproduce:

Create new Expo app
Install expo-notifications
Request push token using:

javascriptCopyconst token = await Notifications.getExpoPushTokenAsync({
  projectId: "project-id"
});
Current behavior:

Android requires Firebase initialization
Error indicates missing RNFBAppModule

Expected behavior:

Should work without Firebase like iOS
OR
Clear documentation that Firebase is required for Android push notifications

Environment:

Expo SDK: [version]
expo-notifications: [version]
Platform: Android
Device: [model]

Possible Solution:
Consider making Firebase optional or documenting the Android requirement clearly in the expo-notifications docs.

### Environment

```text
"@react-native-firebase/app": "^21.0.0",
"expo": "~52.0.7",
"react-native": "0.76.2",
```

**Comment by vonovak** [comment]
Hello and thanks for reporting,

You error "Native module RNFBAppModule not found" points to `@react-native-firebase/app`. You probably didn't follow the installation instructions fully: https://rnfirebase.io/#configure-react-native-firebase-modules

Please read the entire instructions from [here](https://rnfirebase.io/#expo).

That being said, you don't need react native firebase if you want to receive push notifications, only `expo-notifications` is sufficient.

> Consider making Firebase optional

Push notifications on Android require Firebase but _not_ react-native-firebase (which ships a lot of other Firebase's features).

Your Minimal reproducible example [package.json](https://github.com/Jaseyacey/fixturetest/blob/main/package.json) doesn't contain `@react-native-firebase/app` or `expo-notifications` so I won't be able to confirm with certainty what issue you're facing.
Hope this helps 🙂
