### ISSUE TITLE
Bump @react-native-masked-view/masked-view version in order to fix black screen issue

### ISSUE THREAD

**Issue by mlukasik-dev** [expo/expo#33032]
### Minimal reproducible example

https://github.com/react-native-masked-view/masked-view/issues/233

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

On Android, I encountered the same issue described in [this GitHub issue](https://github.com/react-native-masked-view/masked-view/issues/233). Updating `@react-native-masked-view/masked-view` to version `0.3.2` resolved the problem.

### Environment

```text
expo-env-info 1.2.1 environment info:
  System:
    OS: macOS 15.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  Managers:
    CocoaPods: 1.15.2 - /Users/me/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
  IDEs:
    Android Studio: 2024.2 AI-242.23339.11.2421.12550806
    Xcode: 16.1/16B40 - /usr/bin/xcodebuild
  Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
expo-env-info 1.2.1 environment info:
  System:
    OS: macOS 15.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  Managers:
    CocoaPods: 1.15.2 - /Users/me/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
  IDEs:
    Android Studio: 2024.2 AI-242.23339.11.2421.12550806
    Xcode: 16.1/16B40 - /usr/bin/xcodebuild
  Expo Workflow: bare
```

**Comment by brentvatne** [comment]
fixed in https://github.com/expo/expo/commit/58c7c9156e86dab9e3f2f15135e52f03880b6cf3 - it will go out in the next release of expo go, updated the recommended version right away so run `npx expo install --fix` and rebuild your dev build to pull in the change.

**Comment by brentvatne** [comment]
(thanks for the heads up!!)
