### ISSUE TITLE
Linking.addEventListener broken in SDK 52, callback never runs

### ISSUE THREAD

**Issue by techied** [expo/expo#33031]
### Minimal reproducible example

https://github.com/techied/expo-linking

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

In SDK 52, `Linking.addEventListener` (both from `expo-linking` and from `react-native`) does not work as expected.

When opening links i.e. `xcrun simctl openurl booted` the event listener never fires. The result of the useLinkingUrl hook updates as expected.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    npmGlobalPackages:
      eas-cli: 12.6.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: scheme, orientation, icon, userInterfaceStyle, splash, ios, android. 


One or more checks failed, indicating possible issues with the project.
```

**Comment by techied** [comment]
potential duplicate of #32496

**Comment by gabrieldonadel** [comment]
Hi @techied, thanks for the report, we're already investigating this and a fix should come shortly.

> potential duplicate of #32496 ?

Not really, this problem is specific to `expo-linking` and not related with `expo-dev-client`

**Comment by techied** [comment]
Thank you for the quick fix @gabrieldonadel , when do you expect a release of `expo-linking` with this PR included?

**Comment by gabrieldonadel** [comment]
@techied a new version of `expo-linking` was just released! Please let me know if that does not fix your issues. Thanks again for the report

**Comment by Garett-MacGowan** [comment]
@gabrieldonadel Is it possible that Linking.addEventListener is also broken in SDK 51? The callback isn't running for me on IOS when the app is already in the background. Works when the app is linked from a terminated state. Works fine on Android in both terminated and backgrounded states.

**Comment by florian-deroo** [comment]
> @gabrieldonadel Is it possible that Linking.addEventListener is also broken in SDK 51? The callback isn't running for me on IOS when the app is already in the background. Works when the app is linked from a terminated state. Works fine on Android in both terminated and backgrounded states.

Same issue

**Comment by tscans** [comment]
Having the same issue here.

**Comment by RahulDey12** [comment]
`Linking.addEventListener` is working and the app is booting up to correct URL from the cold start but the `+native-intent.tsx` is not working as expected. And when the app is already running or in background it's not going to expected screen.
