### ISSUE TITLE
Expo v31 Android release build would not load JS bundle ( iOS build works on both debug and release configs)

### ISSUE THREAD

**Issue by sleepwalkerfx** [expo/expo#3303]
### Environment

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.2.5 => 3.4.11
      expo: ^31.0.4 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: v1.0.0-beta.26 => 1.0.0-beta.26
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

We have detached version of app that uses Expo v31.0.0.  In iOS App works fine. (Both debug and release versions). But in Android, only debug version works. When we try to run a release build, App woudln't load. Apparently the JS bundle is not loading.  We have correctly set up release-config.

(Write your steps here:)

1. Published JS bundle using` exp publish `command (we tried `expo publish` too)
2. Created an APK and launched on an Android device.

### Expected Behavior

App should load.

(Write what you thought would happen.)

### Actual Behavior

Only splash screen loads, then this error pops up. 

![image](https://user-images.githubusercontent.com/4486883/51613826-54aa5200-1f4a-11e9-86de-f136b88c6527.png)

Any idea why ?

**Comment by Supun94** [comment]
I'm having the same issue after upgrading to EXPO 31. Seems like this is a know issue without any exact solution and I also tried EXPO 32 as well. 

Changed `PUBLISHED_URL` after completed `expo publish`, I have updated `expo-cli` version to `2.6.14` but nothing works for me. Couldn't find proper solution for this issue. It would be a great help to get an input from expo contributors to fix this issue.  

CC: @terribleben @brentvatne @ide @sjchmiela

**Comment by Malith-Madhushanka** [comment]
I'm also having this issue and already tried all possible suggestions but the issue is still persisting.
followed these links as well - 
https://www.bountysource.com/issues/58866793-could-not-load-app-can-t-connect-to-internet-please-try-again-sdk27-30-w-expokit 

https://github.com/expo/expo/issues/2499

**Comment by sjchmiela** [comment]
Hey all,

(First of all, please don't mass call people. 🙂)

When you `expo publish` your app, JS bundle ends up updated both on Expo servers and under `publishBundlePath` (see `app.json`). File from under `publishBundlePath` is going to be used when the application is built in production mode (Generate Signed APK, `release`, etc.). Otherwise, in development/debug mode, app will try to load JS bundle from your development server. (That's why usually it's necessary to first start the packager with `expo start` and only then install the debug APK on your device — when building APK we have to know which IP should be used as the development server.)

If you're trying to run your ejected project for development, please ensure `expo start` is running in project's directory prior to building the APK.

If you're trying to build a production APK, please ensure its being built in `prodKernel` and `release` configurations.

**Comment by sleepwalkerfx** [comment]
`2019-01-24 14:31:04.367 31925-32570/? E/c: Error fetching cached manifest, falling back to default timeout: java.io.IOException: No hard coded response found
2019-01-24 14:31:04.370 31925-31925/? E/a: Map already contains entry for key experienceIdSetForActivity. Ignoring.
2019-01-24 14:31:04.371 3779-32569/? E/BatteryStatsService: no controller energy info supplied
2019-01-24 14:31:04.541 31925-32054/? E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}`

Getting these error logs in LogCat when trying to launch app.

**Comment by sleepwalkerfx** [comment]
@sjchmiela 

In MainActivity.java
```
  public String publishedUrl() {
    return ReleaseConfig.PUBLISHED_URL;
  }

```
In ReleaseConfig.java, 
```
public class ReleaseConfig {
    public static final String PUBLISHED_URL = "https://exp.host/@myUserNameHere/myAppNameHere?release-channel=qa_release_2018-01-22";
}
```

**Comment by sjchmiela** [comment]
What about `AppConstants.java`? Is this `ReleaseConfig` your class, or was it Expo-created?

**Comment by sleepwalkerfx** [comment]
```
  @Override
  public List<String> sdkVersions() {
    return new ArrayList<>(Arrays.asList("31.0.0"));
  }
```

I had set 31.0.2 instead of 31.0.0 in MainActivity.java , after fixing it , Now I'm getting following errors (only on release builds, when debugging in device it works fine)

![image](https://user-images.githubusercontent.com/4486883/51818434-f0461480-22f4-11e9-96e4-2fce6297f96d.png)

**Comment by sleepwalkerfx** [comment]
I'll add few observations we did,

In `MainActivity.java` if we hard-code the return value to `false`, debug build loads published JSBundle correctly and app starts.

```
  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

```

However if we sign the exact same build (with `isDebug` set to `false`) as an APK ,  We're getting the same errors.  What could be the reason?

**Comment by sjchmiela** [comment]
Are you sure, @sleepwalkerfx, you have published your app on the new SDK before trying to create a production build? `expo publish` builds a production JS bundle and not only uploads it to OTA server, but also puts it into the `assets` directory so the APK should contain last published version. `s.Constants.… is not a function` sounds like trying to run an old JS bundle on a new SDK… 🤔

**Comment by aniltirola** [comment]
I also registered some problems on android with ejected sdk31; I increased app-version, published, generated the release apk; then I carefully viewed logcat and realized, that the apk used an old manifest....so I tried multiple times and didn't know what to do... then I found the solution:
- android studio used in the build-process an intermediate-java-artifact from a previos build
- solution: android-studio -> build -> clean .... and the rebuild


how did I get there?
- In the publishing process I wrote a unique string into the description like "release 1.0.6 time 15:06";
- then publish, then build in android-studio
- then install your apk and view logcat and check if your unique string appears

**Comment by mtford90** [comment]
Also experiencing this. OTA works perfectly on iOS but android seems to be having issues (expokit v31). 

After the update is downloaded and loaded from the cache the following blank error is displayed:

![screenshot-2019-02-09_17 44 31 818](https://user-images.githubusercontent.com/1734057/52524203-6f8efd00-2c92-11e9-8be1-bfbf03ef8e59.png)

Here is the relevant error available via logcat:

```
2019-02-09 17:32:43.367 9892-9892/? E/ErrorFragment: ErrorActivity message: Sorry about that. Press the reload button to try again.
2019-02-09 17:32:43.389 9892-9951/? E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
2019-02-09 17:32:43.437 9892-9959/? E/EGL_emulation: tid 9959: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
```

Note: once the crash has occurred, if you restart the app & then reopen it, the app loads successfully with the new bundle.

This is quite a problem for us as we cannot release any OTA updates even to iOS due to them breaking android.

**Comment by N1ghtly** [comment]
I'm experiencing this as well. iOS builds are working fine. I've tried changing some stuff in AppConstants and DetachBuildConstants, to no avail. I'm on SDK 32. I have updates disabled in app.json.

@mtford90 did you find a solution?

**Comment by borie88** [comment]
Same issue here. Going to try and build it on Linux. Might have been an issue with permissions on Windows while ejecting for me

**Comment by sjchmiela** [comment]
Hey all, it would be really helpful if someone could provide [an MCVE](https://stackoverflow.com/help/mcve) for this problem, the problem doesn't happen on a freshly created project. 🤷‍♂️ 😕

**Comment by AlexandreLage** [comment]
Anybody? :`(

**Comment by sirmong** [comment]
Issue is still unresolved

**Comment by disappearer** [comment]
Problem, in my case is that `publishedUrl()` method in `MainActivity.java` was returning the wrong value. I was previously logged in as another user, so it was most likely a leftover from that time. Not really sure.
```@Override
  public String publishedUrl() {
    return "exp://exp.host/@wrong_user/project";
  }```

**Comment by sirmong** [comment]
Solved that issue by @disappearer method. Thanks!

**Comment by AaronStackBarnes** [comment]
SAME! thanks @disappearer!

**Comment by QuintonC** [comment]
I'm also getting this... my publishedUrl is fine...

```
  public String publishedUrl() {
    return "exp://exp.host/@my_username/project_name";
  }
```

But in my BuildConfig.java this is set. If I change it, it just auto reverts back to this as well.
```
public static final boolean DEBUG = Boolean.parseBoolean("true");
```

This is what I get... not even an expo error screen.

The most frustrating thing is that this works perfectly in development, but as soon as I go to production and attempt to test on a physical device with signed APK this is what I am getting.
![blank image](https://i.imgur.com/yxU2gks.png)

**Comment by vipontes** [comment]
I'm having the same issue on Expo 35 after migrating from 33. I'm really considering to rebuild my app in Kotlin/Swift. I'm getting tired of troubles with react-native/Expo. :-(

**Comment by Stephen2** [comment]
Expo 33 won't go past splash screen when run from APK.  I'm not ejected or anything, and this is confusing the hell out of me.

I've tried working with `logcat` but damn if there's not a lot of output to go through.

I'm going to downgrade Expo-CLI and see if I can't get this working that way?

**Comment by Stephen2** [comment]
Downgrading `expo-cli` as far as `3.1.2` had no impact, so I suspect that has nothing to do with it.

Gonna try and build an old version of code to analyse if it's code, then I'll be pretty sure it's something to do with Expo build process

**Comment by Stephen2** [comment]
It's looking like code change blew something up for me.  Ignore me.

**Comment by benjMic** [comment]
the only way to load JS Bundle for me is on `MainActivity.java` : 

```
 public String publishedUrl() {
    return DetachBuildConstants.DEVELOPMENT_URL;
  }
```

It's working for debugging but I must update the string if I want to publish.

**Comment by thanh90** [comment]
You have to change a release url both on MainActivity.java and AppContants.java.
