### ISSUE TITLE
Expo 52: Modals no longer visible when open

### ISSUE THREAD

**Issue by GitMazzone** [expo/expo#33047]
### Minimal reproducible example

https://github.com/GitMazzone/workout-tracker

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

I built this app using Expo 51. I was forced to update to 52 to use Expo Go for testing on my iPhone.
After updating, several modals do not show when opened:
- `ExercisePickerModal` 
- `AddCustomExerciseModal`
- Within `MesoMenu`, the Edit Modal

These all live under `/components`.

It seems that anything but top-level (not nested within anything) modals work after updating.
If I try opening the menu from the buttons that lead to the buttons to open these modals, they are no longer pressable. I have to close the entire app and reopen to be able to try again.

Demo video of broken modal:

https://github.com/user-attachments/assets/9d358ca8-825a-46ab-94ca-7bcbeb9651e7

In the demo, I go to the `/app/(tabs)/workout` route and see the `ExerciseSetList`.
I open the first exercise's option menu, triggering `handleMenuPress`.
I select "Replace Exercise".
If I add logs, I can see the modal's visible prop is true.
The modal does not appear on the screen.

The _only_ other thing that caused lint errors after updating from 51 --> 52 was type issues on the `buttonRef`. This seems irrelevant to the modal issue, but for sake of transparency this is what I had to change in a few places:
From this: `const buttonRef = useRef<TouchableOpacity>(null);`
To this: `const buttonRef = useRef<ElementRef<typeof TouchableOpacity>>(null);`

I'm new to React Native & Expo, so I tried working with ClaudeAI & ChatGPT, and CursorAI, and even with all the project's context and trying dozens of things, nothing is resolving this issue. I've tried
- Making the modals separate from where they currently are
- Separating their handlers
- Various attempts at removing animations altogether
- Adding `requestAnimationFrame` to the modal handlers
- Removing `presentationStyle={'pagesheet'}` and `presentationStyle` altogether

Please let me know if I can provide any more context. 
Sorry, I know this isn't technically minimally reproducible, but it's a very small project and can be run quickly with `npx expo start`.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.19.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7 
      expo-router: ~4.0.6 => 4.0.6 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.10 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.2.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✔ Check npm/ yarn versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: lucide-react-native
No metadata available: date-fns, tailwindcss
Advice: 
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by brentvatne** [comment]
unrelated to creating a minimal reproducible example, but i recommend reading https://expo.fyi/expo-go-usage - if you use development builds, you're never forced to upgrade when we release a new version! this only applies to expo go, our sandbox app.

**Comment by KarlaSaenz** [comment]
This issue may be linked to this - [Modals different behaviour on iOS in v0.76](https://github.com/facebook/react-native/issues/47694)
