### ISSUE TITLE
 Swift Type Inference Error in `expo-apple-authentication` Library 7.1.1

### ISSUE THREAD

**Issue by rybaier** [expo/expo#33046]
### Minimal reproducible example

https://github.com/rybaier/bug_report_expo_apple_auth

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

 Swift Type Inference Error in `expo-apple-authentication` Library 7.1.1

## Description

When building an app that uses the `expo-apple-authentication` library version 7.1 in VScode with Xcode 15.2  the following error occurs in the `AppleAuthenticationModule.swift` file due to Swift being unable to infer the return type for a closure containing multiple statements.

### Expected Behavior
The function should successfully compile and return a formatted string, but the closure's return type is not inferred due to multiple statements inside the closure.

### Actual Behavior
Xcode produces the error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate.

## Steps to Reproduce from [bug-report-reproducible](https://github.com/rybaier/bug_report_expo_apple_auth)
1. create .env from .envExample (you do not need to change anything just create the file)
3. run ```npx expo prebuild```
4. run ```npx expo run ios```
5. observe the following error in the `AppleAuthenticationModule.swift` file:

### Error Message
```
❌  (/<path to node_modules>/node_modules/expo-apple-authentication/ios/AppleAuthenticationModule.swift:51:32)

  50 | 
> 51 |     Function("formatFullName") { (fullName: FullName, formatStyle: FullNameFormatStyle?) in
     | ERROR                          ^ cannot infer return type for closure with multiple statements; add explicit type to disambiguate
  52 |       let formatStyle = formatStyle?.toFullNameFormatStyle() ?? .default
  53 |       var nameComponents = PersonNameComponents()
  54 | }
  ```
  
  xcodebuild produces the error: cannot infer return type for closure with multiple statements; add explicit type to disambiguate.
  
  ### Fix  
  in /<path to node_modules>/node_modules/expo-apple-authentication/ios/AppleAuthenticationModule.swift:51:32
adding ``` -> String```  to line 51 for the function 
  ```
    51| Function("formatFullName") { (fullName: FullName, formatStyle: FullNameFormatStyle?) -> String in
              let formatStyle = formatStyle?.toFullNameFormatStyle() ?? .default
              var nameComponents = PersonNameComponents()
          
              nameComponents.namePrefix = fullName.namePrefix
              nameComponents.nameSuffix = fullName.nameSuffix
              nameComponents.givenName = fullName.givenName
              nameComponents.middleName = fullName.middleName
              nameComponents.familyName = fullName.familyName
              nameComponents.nickname = fullName.nickname
          
              let formatter = PersonNameComponentsFormatter()
              formatter.style = formatStyle
          
              return formatter.string(from: nameComponents)
          }
  ```

[ AppleAuthenticationModule.swift with fix](https://github.com/rybaier/bug_report_expo_apple_auth/blob/main/AppleAuthenticationModule.swift)

### Comments 
This was discovered while upgrading to Expo SDK 52 and React Native 0.76
I tried several things before going directly to the node_modules file 
such as
- clearing the cache with expo and rebuilding with npx expo start -c
- deleting Xcode cache, Xcode build data and indexes 

I can not replicate the error on my M1 MacBook pro which is at Xcode 16 and Sonoma 14.5. 
It only happens on intel IMac with xcode 15.2 and Ventura IOS 13.7

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 13.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.1.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
      Watchman: 2024.11.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7 
      expo-router: ~4.0.6 => 4.0.6 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    npmGlobalPackages:
      eas-cli: 9.0.10
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
Unmaintained: react-native-loading-spinner-overlay, react-native-material-dropdown, react-native-modal-dropdown
No metadata available: @dicebear/collection, @dicebear/core, @expo/config-plugins, @react-native/babel-preset, date-fns, expo-doctor, prop-types, react-native-keyboard-avoiding-scroll-view, react-native-tooltip-2, save-dev, uuid
```

**Comment by brentvatne** [comment]
@alanjhughes - looks like this was caused by https://github.com/expo/expo/pull/32567
