### ISSUE TITLE
[expo-camera] video files are huge (95mb per minute @ 720p) and don't allow any bitrate/fps customisation

### ISSUE THREAD

**Issue by jvgeee** [expo/expo#33042]
### Minimal reproducible example

https://github.com/jvgeee/expo-camera-bugs

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

I'm using expo-camera to record videos and upload them to my server. 

I've noticed that the filesizes of the videos captured with expo-camera are huge. I've set the `videoQuality={"720p"}`, and when I take a 1 minute video the file size is 95mb, and even higher for IOS.  If you take a better quality video, like 1080p, filesizes jump to >150mb for a 1 minute video.

These are ridiculously large filesizes; Google tells me a 1 minute, 720p video @ 1mbps should be about 5mb, and when I do on-device compression with ffmpeg it compresses to around that size.

There are no parameters to set things like:

- Bitrate
- FPS
- Android video codec
- Anything else!

Currently, the only solution to get smaller filesizes is to use something like `ffmpeg-kit/react-native` to compress the video on-device.

What is the recommended solution here? Can we get some parameters to customise the bitrate and FPS coming from expo-camera? It seems very wasteful to have to record the video at whatever highest-quality Expo demands, and then have to spend 60+ seconds compressing the video on-device to make it small enough to send to a server over mobile network.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 33, 34
        Build Tools: 33.0.1, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-VanillaIceCream | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11668458
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    npmGlobalPackages:
      eas-cli: 13.1.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by jvgeee** [comment]
FYI I don't consider this a feature request, I think the bug is that Expo only offers 720p/etc customisation for video quality, and I expect that those parameters that you offer should be self-optimised to provide reasonable filesize, quality, audio, bitrate etc as preset defaults, similar to what is offered in expo-av's audio presets.

The current presets you offer give wildly inflated filesizes, producing basically unusable video files (especially if recording a >5min video => ~500mb!). 

I can see this PR was made that allowed setting the bitrate, but it no longer exists in the sdk: https://github.com/expo/expo/pull/11932

**Comment by alanjhughes** [comment]
Hi, I've added the ability to set the bitrate in #33087.

The ability to set the codec is available on iOS as an argument to `recordAsync`. On Android, this is tied to `videoQuality`.

> Google tells me a 1 minute, 720p video @ 1mbps should be about 5mb

This is incorrect.
There are multiple factors that effect this, the chosen quality, if you are capturing audio, codec but achieving a 5mb file seems unrealistic unless you go for the lowest options possible and these will all be available after #33087 is merged

**Comment by jvgeee** [comment]
Amazing, thanks @alanjhughes , appreciate the quick response and implementation!

**Comment by jvgeee** [comment]
@alanjhughes @brentvatne just want to confirm: setting `videoBitrate` is meant to accept a number, but the TS example says `10_000_000`:
<img width="612" alt="image" src="https://github.com/user-attachments/assets/e99fc901-36ea-4336-af27-e59c4945494f">

Should also probably denote what unit the bitrate should be set in

**Comment by alanjhughes** [comment]
@jvgeee - `10_000_000` is a number, it's just using a separator for readability. The doc specifies that it is `bits per second`

**Comment by jvgeee** [comment]
Perfect, thank you
