### ISSUE TITLE
npx expo-doctor giving plugin error - Sentry

### ISSUE THREAD

**Issue by jerone** [expo/expo#33054]
### Summary

Expo Doctor gives error when running with Sentry installed.

```
PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" relative to "C:\Projects\expo-doctor-sentry
```

Similar to #32185

### SDK Version

51 & 52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 22.6.0 - ~\AppData\Local\nvs\default\node.EXE
      Yarn: 1.22.22 - ~\AppData\Local\nvs\default\yarn.CMD
      npm: 10.9.0 - ~\AppData\Local\nvs\default\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12483815
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

#### Predefined example

1. Git clone https://github.com/jerone/expo-doctor-sentry
2. `cd expo-doctor-sentry`
3. `npx expo-doctor` (install latest if asked)

#### Self reproducible

You'll need an account for Sentry.

1. `npx create-expo-app@latest`
2. `npx @sentry/wizard@latest -i reactNative`  and follow all default instructions
3. `npx expo-doctor` (install latest if asked)

**Comment by jerone** [comment]
Related issue: https://github.com/getsentry/sentry-react-native/issues/4283

_Hint: it might be Windows related._

**Comment by byCedric** [comment]
@jerone Thanks for reporting this, it's indeed a Windows issue. That being said, since `@sentry/react-native` ships the `app.plugin.js` file as well, you can also use `@sentry/react-native` as config plugin, and it should work fine for now.

The fix for `@sentry/react-native/expo` will be released asap.

**Comment by imranbarbhuiya** [comment]
The pr label says `Published` but I'm still having issues with the latest expo doctor run `npx expo-doctor@latest`
