### ISSUE TITLE
DOM Components require "javaScriptEnabled" Error on iOS

### ISSUE THREAD

**Issue by fukuli053** [expo/expo#33064]
### Minimal reproducible example

https://github.com/fukuli053/ExpoDOM-JSBug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build, in a standalone app

### Description
When using DOM components on iOS simulator, I'm getting the error **"DOM Components require javaScriptEnabled"**. The same code works fine on Android.

I tried using both **"react-latex-next"** and **"react-markdown"** libraries to render LaTeX formatted data, but encountered this error on iOS with both libraries. The functionality works without any issues on Android.

### Expected Behavior
DOM components should work properly on iOS, allowing LaTeX content to be rendered correctly.
![Android screenshot|300](https://github.com/user-attachments/assets/b4424c3c-f0c0-4350-9b2a-024260b4afbb)

### Actual Behavior
Getting "DOM Components require javaScriptEnabled" error on iOS when trying to render LaTeX content.
![Simulator Screenshot - iPhone 16 Pro - 2024-11-19 at 14 24 03](https://github.com/user-attachments/assets/2a335a99-88f4-483c-b48b-ebdd2c5042b4)

### Relevant Code
```javascript
import { StyleSheet, Text, View } from "react-native";
import React from "react";
import Latex from "@/components/Latex";

const index = () => {
  return (
    <View style={styles.container}>
      <Latex dom={{ javaScriptEnabled: true }} />
    </View>
  );
};

export default index;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
});
```

```javascript
"use dom";

import "katex/dist/katex.min.css";
import Latex from "react-latex-next";

export default function Latex({}: { dom: import("expo/dom").DOMProps }) {
  const formulas = [
    {
      title: "Quadratik Formül",
      latex: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    },
    {
      title: "Türev",
      latex: "\\frac{d}{dx}(x^n) = nx^{n-1}",
    },
    {
      title: "İntegral",
      latex: "\\int x^n dx = \\frac{x^{n+1}}{n+1} + C",
    },
    {
      title: "Euler Formülü",
      latex: "e^{ix} = \\cos x + i\\sin x",
    },
    {
      title: "Limit",
      latex: "\\lim_{x \\to \\infty} \\frac{1}{x} = 0",
    },
  ];

  return (
    <div>
      <Latex>{`$e^{ix} = \\cos x + i\\sin x$`}</Latex>
    </div>
  );
}
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.5.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7 
      expo-router: ~4.0.6 => 4.0.6 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.2.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by EvanBacon** [comment]
Downloaded and ran in the simulator. Seems to work as expected. JS is enabled by default in the webview, perhaps there's some obscure device configuration that blocks JS system-wide on your computer/simulator?

![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-19 at 10 57 18](https://github.com/user-attachments/assets/e0dc1cee-8105-4c5a-a7f5-6dda677a9540)


Only issue I see is related to font bundling in the latex package. We'll work on improving support for this in the future, but it shouldn't be blocking.

**Comment by fukuli053** [comment]
@EvanBacon Thank you for your response. I haven't made any custom configuration to block JavaScript on my computer or simulator. This is a fresh installation of Xcode and iOS Simulator.

Could you please guide me on which specific settings I should check:
- In the iOS Simulator?
- In Xcode?
- In the Expo project configuration?

The issue consistently appears only on iOS while working fine on Android.

**Comment by disolaterX** [comment]
getting same issue using these and expo go

"react-native-webview": "13.12.4"
"expo-web-browser": "~14.0.1",    
"expo": "^52.0.7",

**Comment by yaroslav-bodnar** [comment]
I get the same error

**Comment by Lugdu84** [comment]
i get the same error too, in simulator and device (iphone 11)

**Comment by colin-chadwick** [comment]
@EvanBacon Not working for me as well. The Expo DOM components simply don't render. If I go to the debugger, it only shows an empty root tag without any errors in the console.
![Bildschirmfoto 2024-11-20 um 16 31 37](https://github.com/user-attachments/assets/aaf381e4-6209-482e-9ea8-cc257bd0bce4)

**Comment by afneyman** [comment]
Same issue here

**Comment by thestackdev** [comment]
> Finally, the component renders correctly, but it's impossible to use Tailwind, for example. With CSS in a separate file, it works fine, however. The error message appears occasionally, and is consistently present if the component with 'use dom' is on the homepage.

How did you get it worked?

**Comment by omt66** [comment]
This is strangely happenning on my iOS tests, it is working for a while till I refresh the app, and it is not working again!

**Comment by julietafoglia** [comment]
Still getting this issue on iOS simulator, not happening on Android device (using expo go)

**Comment by truong170201** [comment]
I downgraded react-native-webview to 13.2.2, it's even worse, it gives me more errors.

**Comment by omariosouto** [comment]
Something that I have done that makes things work again:

![CleanShot 2024-11-26 at 23 52 36@2x](https://github.com/user-attachments/assets/8b976b6d-1686-4959-9330-6657becbdfe3)

```ts
import React from "react";
import { View } from "react-native";
import { default as HomeScreen } from "@/src/screens/HomeScreen.web";
import WebView from "react-native-webview";

export default function Screen() {
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 100);
  }, []);

  return (
    <View
      style={{
        flex: 1,
        backgroundColor: "navy",
        // force inside elements to be full height and width
        display: "flex",
        flexDirection: "column",
      }}
    >
      {loading ? (
        <WebView
          source={{ uri: "https://www.google.com" }}
          style={{
            flex: 1,
          }}
        />
      ) : (
        <HomeScreen
          name="Sample"
        />
      )}
    </View>
  );
}

```

**Comment by Monkhai** [comment]
not sure where we stand on this but I noticed that the dom props are undefined even when explicitly defining them and passing them down. That is on an android simulator. an ios device or simulator is just not even loading so I couldn't log anything out of it. Here is what I did:

# Index at the root of the app dir
```
import DOMComponent from '@/components/DomComponent'
import React from 'react'
import { View } from 'react-native'

export default function index() {
  return (
    <View style={{ display: 'flex', flex: 1 }}>
      <DOMComponent dom={{ javaScriptEnabled: true, scrollEnabled: false }} />
    </View>
  )
}
```

# DOMComponent in components dir
```
'use dom'

export default function DOMComponent({ dom }: { dom: import('expo/dom').DOMProps }) {
  console.log(dom)
  return (
    <main>
        <h1>Hello world</h1>
    </main>
  )
}
```
# Versions
- expo: 52.0.11
- react-native-web: 0.19.13
- react-native-webview: 13.12.2,
- react: 18.3.1
- react-dom: 18.3.1
- react-native: 0.76.3

**Comment by ataschz** [comment]
Any news?

**Comment by ozancakir** [comment]
looks like something broken, official guide is not works in mobile expo app as well. 
Page:
```typescript
import { View } from 'react-native';

import MyComponent from '@/components/shared/my-component';

export default function HomeScreen() {
  return (
    <View style={{ flex: 1 }}>
      <MyComponent name="world" />
    </View>
  );
}
```
my-component.tsx
```typescript
'use dom';

export default function DOMComponent({ name }: { name: string }) {
  return (
    <div>
      <h1>Hello, {name}</h1>
    </div>
  );
}
```
package.json
```
"dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "expo": "~52.0.11",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.9",
    "expo-splash-screen": "~0.29.13",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.4",
    "expo-web-browser": "~14.0.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.3",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.2"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },
```

**Comment by NyoriK** [comment]
Got the same error. However, updating the expo go app solved the problem.
