### ISSUE TITLE
Network State Not Detecting Correctly After SDK 52 Update

### ISSUE THREAD

**Issue by samf3nn** [expo/expo#33070]
### Minimal reproducible example

-

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

After updating the SDK to version 52, the expo-network module is no longer detecting the network state correctly. Specifically, it always returns { "isConnected": false, "isInternetReachable": false, "type": "NONE" }, even though the device is connected to the internet.

Steps to Reproduce:

Update the SDK to version 52.
Use the expo-network API to check the network state (e.g., Network.getNetworkStateAsync()).
Observe that the result is always isConnected: false and isInternetReachable: false.
Expected Behavior: The expo-network module should correctly detect the network state, returning isConnected: true and isInternetReachable: true when the device is connected to the internet.

Actual Behavior: The network state is always reported as { "isConnected": false, "isInternetReachable": false, "type": "NONE" }, even when the device is connected to the internet.

Additional Information:

The issue only appeared after updating the SDK to version 52.
Testing on both physical devices and simulators/emulators has shown the same issue.
The issue persists even after restarting the device and ensuring a stable internet connection.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.9.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 9.6.3 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.0 => 52.0.7 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    npmGlobalPackages:
      eas-cli: 12.6.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: @fortawesome/fontawesome-svg-core, @fortawesome/free-brands-svg-icons, @fortawesome/free-regular-svg-icons, @fortawesome/free-solid-svg-icons, @inquirer/prompts, firebase, humanize-duration, i18next, react-native-elements, react-native-uuid, twrnc, typescript, yup
```

**Comment by GiyoMoon** [comment]
@samf3nn This seems like a duplicate of #33012
