### ISSUE TITLE
iOS app rejected due to Stripe

### ISSUE THREAD

**Issue by TamasNo1** [expo/expo#3308]
I have a very basic app without any payment features, however it got rejected by Apple due to the following reasons:

> The App Review Board evaluated your app and determined that the original rejection feedback is valid. Your app does not comply with:
> 
> 2.3.1 - Performance and 3.1.1 - Business
> We continue to discover that your app contains hidden external purchase features. 
> 
> It would be appropriate to remove all ‘Stripe’ feature within your app before resubmission.
> 
> We hope you will consider making the necessary changes to be in compliance with the App Store Review Guidelines and will resubmit your revised binary.

app.json:
```
{
  "expo": {
    "sdkVersion": "30.0.0"
...
```

I'd like to know if there's any option I could build the binary without the payment features or if anyone has found a solution to this problem?

**Comment by tsapeta** [comment]
Is your app ejected/detached? I'm asking because we don't include any payments features into iOS standalone apps built with `expo build:ios`.
To use such features, you have to eject and follow some steps described here: https://docs.expo.io/versions/v30.0.0/sdk/payments/
So I'm wondering how your app can contain it 🤔

**Comment by tsapeta** [comment]
Alright, sorry I was wrong, it looks like payments were included in standalone apps in SDK30 and probably SDK31 too. The best workaround is to upgrade your app to SDK32, build and submit it again 😉

**Comment by TamasNo1** [comment]
Perfect @tsapeta thank you, will give it a try and post the results!
