### ISSUE TITLE
Nested stack in screen using "formSheet" presentation not displaying

### ISSUE THREAD

**Issue by colin-chadwick** [expo/expo#33092]
### Minimal reproducible example

https://github.com/colin-chadwick/expo-router-nested-stack-form-sheet

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When nesting a navigation stack in a screen using the new `formSheet` type presentation, the sheet appears blank. When using the `modal` presentation type, this works as expected. As the `formSheet` presentation offers more customization options, it's unfortunate that this doesn't work.

The first video shows the correct functionality using the `modal` presentation type, and the second video shows the failing nested navigation using the `formSheet` presentation type.

https://github.com/user-attachments/assets/b5e9019c-2735-488d-a5b3-5b9b4bd04876

https://github.com/user-attachments/assets/298ba719-a002-4456-9809-83fa71dc3895

### Environment

```text
environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Managers:
      CocoaPods: 1.16.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7 
      expo-router: ~4.0.6 => 4.0.6 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.2.3
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
let's track this in react-native-screens here: https://github.com/software-mansion/react-native-screens/issues/2522
