### ISSUE TITLE
NPM > 5.0.0 ?

### ISSUE THREAD

**Issue by muescha** [expo/expo#331]
```
const MIN_WATCHMAN_VERSION = '4.6.0';
const MIN_NPM_VERSION = '3.0.0';
const BAD_NPM_VERSION = '5.0.0';
const CORRECT_NPM_VERSION = '4.6.1';
```
( from https://github.com/expo/xdl/blob/master/src/project/Doctor.js#L29-L32)

any chance to support NPM > 5.0.0 ?

**Comment by muescha** [comment]
https://github.com/expo/expo/issues/293
https://github.com/facebook/react-native/issues/14767
https://github.com/react-community/create-react-native-app/issues/277
https://github.com/react-community/create-react-native-app/issues/275
https://github.com/akveo/react-native-ui-kitten/issues/21

**Comment by brentvatne** [comment]
Hi @muescha! I tested out 5.0.4 and it appears to work, at least on a simple example. I submitted a pull request internally to let people know if they are using >= 5.0.0 <= 5.0.3 that it won't work, and to just warn that it *may not work* with >= 5.0.4. We'll likely include this in the next release.

**Comment by imtmh** [comment]
We are waiting for it, when can we expect the next release?

**Comment by dikaiosune** [comment]
Internal PR was merged, closing this as it'll land in a new release.
