### ISSUE TITLE
Expo Go app keeps crashing in Android emulator API 35 before development app even starts (iOS and Android API 34 work fine)

### ISSUE THREAD

**Issue by gtwilliams03** [expo/expo#33112]
### Minimal reproducible example

Local environment issue

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

Recently bought a new M4 Mac and used Migration Assistant to move my data over from my older MacBook Pro.  Had to reinstall a bunch of Android Studio, SDK, JDK, JRE, etc. to get the `arm` based applications to run.  I feel like I missed something because my apps cause Expo Go to crash before the app even starts (see screen record below).  No errors show up in the console, none in the debug log, and none in React Dev Tools. 

EAS builds on expo.dev build fine for Android.  So it is definitely something that got borked in the migration, but I can't figure out what I missed. 

https://github.com/user-attachments/assets/ba00c8d9-014d-4658-a776-cab1b745a986

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.4.0 - ~/.nvm/versions/node/v21.4.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v21.4.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v21.4.0/bin/npm
      Watchman: 2024.11.11.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~12.0.0 => 12.0.1 
      expo: ^52.0.0 => 52.0.8 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.3.0
      expo-cli: 6.3.12
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by gtwilliams03** [comment]
Thank you for your quick response!  I do not have `adb` installed, but I went to "Show Log in Finder" in the Help menu of the "Android Studio" app and the attached `idea.log` file was in there - would this be what you were asking about?

[idea.log](https://github.com/user-attachments/files/17835947/idea.log)

**Comment by vonovak** [comment]
Hello, what you shared is the log of the IDE, not the android app. Please see https://developer.android.com/studio/debug/logcat

You do have adb installed, most likely in a location similar to this `/Users/abc/Library/Android/sdk/platform-tools/adb`

Thank you

**Comment by gtwilliams03** [comment]
Oh thank you, I apologize for my lack of knowledge!  I have a `logcat` capture attached now.  I uninstalled the Expo Go app from my Android emulator.  Then started `adb logcat` and then tried to launch my Expo app on the Android emulator.  Then I tried manually launching the Expo Go app on the Android emulator to try and trigger more crashes.  Hopefully this helps.

[logcat.log](https://github.com/user-attachments/files/17836641/logcat.log)

**Comment by vonovak** [comment]
Hello 👋 ,
I'm afraid the logs don't show anything obvious, we'll need an [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you! 🙂

**Comment by gtwilliams03** [comment]
Yeah, that's why I think I have an environmental problem from my migration to my new laptop (Intel to Apple M chip).  I put a `console.log` statement in the first line of code and it never gets to it because Expo Go crashes immediately.

**Comment by gtwilliams03** [comment]
Same thing happens.  I cloned `https://github.com/rranjan14/expo-update-test` and it works fine in the iOS simulator, but Expo Go crashes immediately in the Android emulator. 


https://github.com/user-attachments/assets/55c70bb6-df7c-4f6e-a2a1-1741feed822b

**Comment by gtwilliams03** [comment]
It's the API version!  I duplicated my Galaxy 23 API 35 virtual device and downgraded it to API 34 and it works.

<img width="638" alt="Device_Manager" src="https://github.com/user-attachments/assets/f76b20d3-91f2-4483-a6b2-48d54568bdff">

**Comment by gtwilliams03** [comment]
I had upgraded my virtual device based upon the [release notes](https://docs.expo.dev/versions/latest/#support-for-android-and-ios-versions) that Android API 35 was now supported:

<img width="1117" alt="Reference_-_Expo_Documentation" src="https://github.com/user-attachments/assets/324b0528-d65a-4d1e-8120-87ade5845437">

**Comment by lukmccall** [comment]
I was attempting to replicate this issue on my machine. I created a new emulator with API 35, and Expo Go worked fine on it. Could you please try recreating your API 35 emulator and test again? The log you provided indicated that the crash occurred at the OS level:
```
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x000070bb060b0378

/apex/com.android.runtime/bin/linker64 (__dl___memset_aarch64+136) (BuildId: 9b5c12da165ff94e136bf97c8ffd9cea)
/apex/com.android.runtime/bin/linker64 (__dl__ZN9ElfReader4LoadEP20address_space_params+1520) (BuildId: 9b5c12da165ff94e136bf97c8ffd9cea)
/apex/com.android.runtime/bin/linker64 (__dl__Z14find_librariesP19android_namespace_tP6soinfoPKPKcmPS2_PNSt3__16vectorIS2_NS8_9allocatorIS2_EEEEmiPK17android_dlextinfobPNS9_IS0_NSA_IS0_EEEE+2544) (BuildId: 9b5c12da165ff94e136bf97c8ffd9cea)
/apex/com.android.runtime/bin/linker64 (__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv+692) (BuildId: 9b5c12da165ff94e136bf97c8ffd9cea)
/apex/com.android.runtime/bin/linker64 (__dl__ZL10dlopen_extPKciPK17android_dlextinfoPKv.__uniq.234527301065430621646263515731762262959+72) (BuildId: 9b5c12da165ff94e136bf97c8ffd9cea)
/apex/com.android.runtime/lib64/bionic/libdl.so (android_dlopen_ext+16) (BuildId: bb1360f0eae574e04d1e293e6681cea3)
/apex/com.android.art/lib64/libnativeloader.so (android::NativeLoaderNamespace::Load(char const*) const+140) (BuildId: 24d166579be78837067c8dcf28e7231b)
/apex/com.android.art/lib64/libnativeloader.so (OpenNativeLibrary+1572) (BuildId: 24d166579be78837067c8dcf28e7231b)
/apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+604) (BuildId: 05bfa63ad29b97d7dde4e764ce193f37)
/apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+356) (BuildId: 52e480f4d160d1f919dafa72cae26e8a)
/system/framework/arm64/boot.oat (art_jni_trampoline+148) (BuildId: 73f9b9faa342a487ed24dfeab499cec25d5fd3c1)
/system/framework/arm64/boot.oat (java.lang.Runtime.loadLibrary0+320) (BuildId: 73f9b9faa342a487ed24dfeab499cec25d5fd3c1)
/system/framework/arm64/boot.oat (java.lang.Runtime.loadLibrary0+400) (BuildId: 73f9b9faa342a487ed24dfeab499cec25d5fd3c1)
/system/framework/arm64/boot.oat (java.lang.System.loadLibrary+84) (BuildId: 73f9b9faa342a487ed24dfeab499cec25d5fd3c1)
/apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 05bfa63ad29b97d7dde4e764ce193f37)
/data/app/~~l5TA7gkahqWrQgJPGrwJoA==/host.exp.exponent-Pt7jLY2T1tDaywHQlprWSQ==/oat/arm64/base.vdex (com.google.firebase.crashlytics.ndk.JniNativeApi.<clinit>+18)
/apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 05bfa63ad29b97d7dde4e764ce193f37)
/apex/com.android.art/lib64/libart.so (art::ClassLinker::InitializeClass(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+5260) (BuildId: 05bfa63ad29b97d7dde4e764ce193f37)
```

**Comment by gtwilliams03** [comment]
Which processor do you have on your machine? Intel or Apple M?

**Comment by gtwilliams03** [comment]
And I recreated my Android emulator with the Google API 35, 16 Kb Google API 35 and API 34.  The two API 35 emulators crash. API 34 works.

<img width="921" alt="image" src="https://github.com/user-attachments/assets/eda30449-59c2-4522-8222-de2d9a3c5658">

**Comment by lukmccall** [comment]
Could you navigate to `Settings > About emulated device > Android version` on you emulator and let me know your kernel version and build number? Also, let's stick to the default version that does not include 16 Kb support. It should look like this:
![image](https://github.com/user-attachments/assets/7a699b1f-5568-44ca-a6b1-4f5410d53c3b)

**Comment by gtwilliams03** [comment]
Sure:

<img width="356" alt="image" src="https://github.com/user-attachments/assets/968f5f6a-4ccf-4b8f-aee8-30a791880a11">

<img width="369" alt="image" src="https://github.com/user-attachments/assets/1d11d743-0825-40ac-ba3c-d42735171f84">

`Android version` info:

<img width="338" alt="image" src="https://github.com/user-attachments/assets/49f574bc-890f-4888-863b-9396c97e8272">

**Comment by lukmccall** [comment]
Hmm, that's strange. I've tried a couple of different OS versions, but I wasn't able to reproduce the issue. However, I couldn't find the exact version that you are using.

**Comment by gtwilliams03** [comment]
It's just what came down the pipe when I created a new Android Virtual Device in Android Studio.  I don't think I was presented with any other option.

**Comment by lukmccall** [comment]
It seems this issue isn't related to Expo, so I'll close it. Fortunately, we have a workaround. 😅

**Comment by matt-toms** [comment]
> It's the API version! I duplicated my Galaxy 23 API 35 virtual device and downgraded it to API 34 and it works.
> 
> <img alt="Device_Manager" width="638" src="https://private-user-images.githubusercontent.com/1564628/388511256-f76b20d3-91f2-4483-a6b2-48d54568bdff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTYyNTgsIm5iZiI6MTczNDAxNTk1OCwicGF0aCI6Ii8xNTY0NjI4LzM4ODUxMTI1Ni1mNzZiMjBkMy05MWYyLTQ0ODMtYTZiMi00OGQ1NDU2OGJkZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMTUwNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRhZWQ0ZjMxOTBhMDRjNjY4NjFiZmZlYmJiOWE2YTAyMDlhZDM0MTI1ZGJkMTdhNzFiZjkyNjA4YjA5MmUxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.I_MFAg3sMKkL6Pnk370psHLtjzf6xHActrbRc2KGb6A">

After many hours of trying to fix the same problem, this is what I had to do
