### ISSUE TITLE
Adding a blurhash placeholder to `expo-image`'s ImageBackground component shows blurry version of the image [Android]

### ISSUE THREAD

**Issue by alterx** [expo/expo#33122]
### Minimal reproducible example

https://snack.expo.dev/@cvega/restless-violet-apples

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go, in a standalone app

### Summary

After upgrading to `"expo-image": "~2.0.0"` (SDK ~52.0.9, RN 0.76.2, "newArchEnabled": true) any `ImageBackground` component that uses the `placeholder` prop with a blurhash shows a low-res, pixelated version of the image provided as uri. 

In the minimal example provided you can see that the image renders as expected and if you uncomment the placeholder line, it renders a low-quality version of the provided image.

### Environment

```text
➜  my-app git:(master) ✗ npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.9 => 52.0.9 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
➜  my-app git:(master) ✗ npx expo-doctor@latest
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by alessandro-bottamedi** [comment]
I have same problem on Image component, if I remove the placeholder the image render correctly. Rn 0.76.2,  Expo 52, expo-image 2.0.0, old architecture on bare workflow...

**Comment by r3dm4n** [comment]
Same here on expo 52.0.11 and expo-image 2.0.2.
Bug occurs only on Android if there is a placeholder set, with blurhash.

**Comment by CodeElixir** [comment]
Same here. As @alessandro-bottamedi pointed, removing placeholder fixes the blurry image. Broken on Android.

**Comment by gavinliu** [comment]
Yep, SDK 51 is works, 52 cannot. plz fix

**Comment by hc-12** [comment]
@lukmccall 

The recent update for `expo-image@2.0.3` did not fix the problem.

Check this snack link for reproduction: https://snack.expo.dev/@hc-12/restless-violet-apples
