### ISSUE TITLE
Expo SDK 52 does not correctly schedule notifications

### ISSUE THREAD

**Issue by MichaelSweeney11** [expo/expo#33120]
### Summary

Hello,
I have an expo app in a managed workflow that schedules notifications ahead of time. I had to upgrade to SDK 52 in order to run the app on my iPhone because of the recent Expo Go update. Now, when the notifications are scheduled, they show up immediately even though I schedule them for later. My notifications worked correctly at SDK 51. My reproducible github repo is a simplified version that is just a simple calendar. When you click on the current date, a notification is scheduled. The notification should not show up for 1000 seconds, but it shows up immediately.

### What platform(s) does this occur on?

iOS

### SDK Version

52.0.7

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 13.6.9
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: 52 => 52.0.9 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    npmGlobalPackages:
      eas-cli: 13.3.0
      expo-cli: 6.3.12
    Expo Workflow: managed
```

### Minimal reproducible example

My repo: https://github.gatech.edu/msweeney40/expo-sdk52-notif-bug

To reproduce the error:
Clone the repo
Enter the directory
run ```npx expo start```
Scan the qr code using an iphone
When the calendar screen loads, press the current date. A notification will pop up immediately, but the code in screens/CalendarScreen.js schedules that notification for 1000 seconds in the future.

**Comment by khoanguyenminh222** [comment]
I also got the same error, the message showed up immediately

**Comment by vonovak** [comment]
Hello, the reproduction needs to be publicly available. The provided repro link requires log in for access.

**Comment by MichaelSweeney11** [comment]
Hello @vonovak , I accidentally used my institutional github. I edited the original issue to have the code hosted on a public github. Please let me know if this works or if I need to make a new issue. Thanks!

**Comment by MichaelSweeney11** [comment]
I went ahead and sent in a new issue because I wasn't sure if you look at issues once they are closed.

**Comment by Arjit0762** [comment]
I am also facing same issue.. I have written triggered in seconds..


Uploading WhatsApp Video 2024-12-03 at 23.39.21.mp4…

**Comment by Arjit0762** [comment]
I am also facing same issue.. I have written triggered in seconds..

https://github.com/user-attachments/assets/9598bbe1-1b56-4130-8986-e63c7996fc53

**Comment by liquidvisual** [comment]
Can confirm scheduling alarms is broken in 52, ffs
