### ISSUE TITLE
expo-splash-screen plugin does not respect `resizeMode`

### ISSUE THREAD

**Issue by yolpsoftware** [expo/expo#33138]
### Minimal reproducible example

https://github.com/expo/expo/issues/32515#issuecomment-2489350076

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

As mentioned [here](https://github.com/expo/expo/issues/32515#issuecomment-2489350076), the following splash configuration works great to create a full-screen splash image on iOS (Expo 52):

```
"expo": {
  "splash": {
    "image": "./assets/splash.png",
    "backgroundColor": "#232323",
    "enableFullScreenImage_legacy": true,
    "resizeMode": "cover"
  }
}
```

If you do the same in the `expo-splash-screen` plugin configuration, the image will not be shown full-screen, but there will be gray margins (either on the top/bottom or left/right, depending on the screen and image size). `resizeMode: cover` should make the image cover the whole screen.

Sorry for not providing a Snack, but this behavior is only on a built app, since AFAIK Expo Go cannot use the expo-splash-screen plugin. I hope the description is specific enough.

@brentvatne said @alanjhughes can handle that ticket.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.0 - ~/.nvm/versions/node/v21.6.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0 => 52.0.7 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.6 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.2.3
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by sidneip** [comment]
Hi,

I think this help you in expo 52, splash config changed a lot and the config too

please check this link and change it, you need set the config to splash in ios and Android key separately
https://docs.expo.dev/versions/v52.0.0/config/app/#resizemode-3

**Comment by yolpsoftware** [comment]
Thank you Alan!

**Comment by fpinatares** [comment]
I've tried with resize mode in 3 different places, and it is still not working for me when opening it on iOS.

"splash": {
      "image": "./assets/splash-icon.png",
      "resizeMode": "cover",
      "backgroundColor": "#1E90FF"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.fpinatares.gol-to-data",
      "splash": {
        "resizeMode": "cover"
      }
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "splash": {
        "resizeMode": "cover"
      }
    },

**Comment by rtturner** [comment]
Still an issue for iOS - see comment on [merged PR that resolved](https://github.com/expo/expo/pull/33143#issuecomment-2506943360) this issue for fix.

```
[
      'expo-splash-screen',
      {
        enableFullScreenImage_legacy: true,
        resizeMode: 'cover', // <- this needs to be at the top level, not in the ios/android objects

        ios: {
          // resizeMode: 'cover', <- don't put this here, it will get overwritten by the plugin to 'contain'
          image: envConfig.splashPath,
          backgroundColor: envConfig.splashBackgroundColour,
        },

        android: {
          backgroundColor: envConfig.splashBackgroundColour,
          image: envConfig.splashPathAndroid,
          imageWidth: 300,
        },
      },
    ],
```

**Comment by jinsley8** [comment]
@rtturner is it only the `expo-splash-screen` plugin settings that need to be set?

My app in Expo Go is pulling the `icon.png` image instead of the splash icon and a white background instead of the blue I have set - not using any of my splash screen settings. 

Not sure if I missed a config step here:

```js
{
  "expo": {
    "icon": "./assets/images/icon.png",
    "userInterfaceStyle": "light",
    "newArchEnabled": true,
    "plugins": [
      "expo-router",
      [
        "expo-splash-screen",
        {
          "enableFullScreenImage_legacy": true,
          "resizeMode": "cover",
          "ios": {
            "image": "./assets/images/splash.png",
            "backgroundColor": "#005DCC"
          },
          "android": {
            "backgroundColor": "#005DCC",
            "image": "./assets/images/splash-icon.png",
            "imageWidth": 300
          }
        }
      ]
    ],
    "ios": {
      "supportsTablet": true,
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#005DCC"
      },
    },
  }
}
```

**Comment by alanjhughes** [comment]
@jinsley8 expo go no longer supports custom splashscreens. We mentioned this in the sdk 52 release blog but will be made more obvious in sdk 53. You will need to use a development build.

**Comment by jinsley8** [comment]
Yes, I just figured out dev builds and it works now. Thanks

**Comment by ahmedibra28** [comment]
just used this and it worked for me

` plugins: [
            "expo-router",
            "expo-build-properties",
            "expo-video",
            "expo-notifications",
            "expo-font",
            "expo-web-browser",
            [
                "expo-splash-screen",
                {
                    backgroundColor: "#ffffff",
                    image: "./assets/images/splash.png",
                    imageWidth: 650
                }
            ]
        ]`
