### ISSUE TITLE
Expo SDK 52 does not correctly schedule notifications (Reopened with public github repo)

### ISSUE THREAD

**Issue by MichaelSweeney11** [expo/expo#33141]
### Summary

Hello,
I have an expo app in a managed workflow that schedules notifications ahead of time. I had to upgrade to SDK 52 in order to run the app on my iPhone because of the recent Expo Go update. Now, when the notifications are scheduled, they show up immediately even though I schedule them for later. My notifications worked correctly at SDK 51. My reproducible github repo is a simplified version that is just a simple calendar. When you click on the current date, a notification is scheduled. The notification should not show up for 1000 seconds, but it shows up immediately.

### What platform(s) does this occur on?

iOS

### SDK Version

52.0.7

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 13.6.9
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
      npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: 52 => 52.0.9 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    npmGlobalPackages:
      eas-cli: 13.3.0
      expo-cli: 6.3.12
    Expo Workflow: managed
```

### Minimal reproducible example

My repo: https://github.com/MichaelSweeney11/expo-sdk52-notif-bug

To reproduce the error:
Clone the repo
Enter the directory
run ```npx expo start```
Scan the qr code using an iphone
When the calendar screen loads, press the current date. A notification will pop up immediately, but the code in screens/CalendarScreen.js schedules that notification for 1000 seconds in the future.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Can you try with this trigger and report if it helps?

```
   trigger: {
      type: SchedulableTriggerInputTypes.TIME_INTERVAL,
      seconds: time,
    },
```
Thank you 🙂

**Comment by MichaelSweeney11** [comment]
I can't get SchedulableTriggerInputTypes.TIME_INTERVAL to work. It gives a reference error because SchedulableTriggerInputTypes doesn't exist even though I have 
```import * as Notifications from 'expo-notifications';```

**Comment by MichaelSweeney11** [comment]
I have noticied:
``` (NOBRIDGE) WARN  expo-notifications: Push notifications (remote notifications) functionality provided by expo-notifications will be removed from Expo Go in SDK 53. Instead, use a development build. Read more at https://docs.expo.dev/develop/development-builds/introduction/.
 (NOBRIDGE) WARN  `expo-notifications` functionality is not fully supported in Expo Go:```

Did SDK 52 make it so that scheduling notifications no longer works properly in a managed workflow? If I switch to a development build, will my notifications work again? Would I need to pay for an apple developer account for them to work on iOS (I really do not want to do this because my app is for a class)?

**Comment by vonovak** [comment]
Hello, in JavaScript, `import * as Notifications from 'expo-notifications';` doesn't mean that you can use `SchedulableTriggerInputTypes` without properly referencing it. So please use `Notifications.SchedulableTriggerInputTypes. TIME_INTERVAL` and that should work.

The warning you see if for push notifications. You're not using push notifications but local (in-app) notifications so you're fine :)

If you are also using push notifications then yes, you'll need to get a paid apple developer account.

**Comment by MichaelSweeney11** [comment]
This fixed it. Thank you so much for your help, I was stumped by this problem since it had been working before the update.

**Comment by akayakagunduz** [comment]
> I can't get SchedulableTriggerInputTypes.TIME_INTERVAL to work. It gives a reference error because SchedulableTriggerInputTypes doesn't exist even though I have `import * as Notifications from 'expo-notifications';`

Make sure you add "Notifications" before "SchedulableTriggerInputTypes", it works that way.

`trigger: {
				seconds: 5,
				type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,
			},`

**Comment by nandastone** [comment]
Thank you! Spent hours debugging why date schedules were firing immediately. The `NotificationTriggerInput` type should prevent a `date` property without a `type`.

**Comment by danest** [comment]
Thank you for this. I was trying to figure out this exact issue as well

**Comment by Zayn2212** [comment]
await Notifications.scheduleNotificationAsync({
                content: {
                    title: reminderName,
                    body: message,
                    data: { reminderName },
                },
                trigger: {
                    type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,
                    seconds: timeDifferenceInSeconds,
                    repeats: false
                },
            });
this one work for me 
const notificationId = await Notifications.scheduleNotificationAsync({
                content: {
                    title: reminderName,
                    body: message,
                    data: { reminderName },
                },
                trigger: {
                    type: Notifications.SchedulableTriggerInputTypes.WEEKLY,
                    weekday,
                    hour,
                    minute,
                    repeats: true,
                },
            });
this one also create schedule notification but i did not receive anyone know why?

**Comment by omar-batrawy** [comment]
Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL

**Comment by shanoysinc** [comment]
> await Notifications.scheduleNotificationAsync({ content: { title: reminderName, body: message, data: { reminderName }, }, trigger: { type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL, seconds: timeDifferenceInSeconds, repeats: false }, }); this one work for me const notificationId = await Notifications.scheduleNotificationAsync({ content: { title: reminderName, body: message, data: { reminderName }, }, trigger: { type: Notifications.SchedulableTriggerInputTypes.WEEKLY, weekday, hour, minute, repeats: true, }, }); this one also create schedule notification but i did not receive anyone know why?

weekly notifcation doesn't work for me either did you manage to figure it out

here is my code

```javascript
 await Notifications.scheduleNotificationAsync({
        ...data,
        content: {
          ...data.content,
          interruptionLevel: "timeSensitive",
        },
        trigger: {
          hour,
          minute,
          type: Notifications.SchedulableTriggerInputTypes.WEEKLY,
          weekday: dueDay,
        },
      });
```
