### ISSUE TITLE
Expo 52 splash screen is not using the expo-splash-screen config, it is picking the icons

### ISSUE THREAD

**Issue by Matthew-Oluwajuwon** [expo/expo#33144]
### Minimal reproducible example

Here's my app.json   {   "expo": {     "name": "Optima Agent",     "slug": "optima-agent-app",     "version": "1.0.0",     "orientation": "portrait",     "icon": "./assets/images/icon.png",     "scheme": "myapp",     "userInterfaceStyle": "automatic",     "newArchEnabled": true,     "ios": {       "supportsTablet": true     },     "android": {       "adaptiveIcon": {         "foregroundImage": "./assets/images/adaptive-icon.png",         "backgroundColor": "#ffffff"       }     },     "web": {       "bundler": "metro",       "output": "static",       "favicon": "./assets/images/favicon.png"     },     "plugins": [       "expo-router",       [         "expo-splash-screen",         {           "image": "./assets/images/splash.png",           "resizeMode": "contain",           "backgroundColor": "#ffffff"         }       ]     ],     "experiments": {       "typedRoutes": true     }   } }

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

Here's my app.json

{
  "expo": {
    "name": "Optima Agent",
    "slug": "optima-agent-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "newArchEnabled": true,
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "web": {
      "bundler": "metro",
      "output": "static",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      [
        "expo-splash-screen",
        {
          "image": "./assets/images/splash.png",
          "resizeMode": "contain",
          "backgroundColor": "#ffffff"
        }
      ]
    ],
    "experiments": {
      "typedRoutes": true
    }
  }
}

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.5.1 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
      Watchman: 2024.07.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 29, 34
        Build Tools: 29.0.2, 29.0.3, 34.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google Play Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom, android-35 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.9 => 52.0.9 
      expo-router: ~4.0.7 => 4.0.7 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.5.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by xthezealot** [comment]
Those bots…

FYI, I have the same problem. Only the "old" `expo.splash` value works.

**Comment by guilean** [comment]
Same here

**Comment by Matthew-Oluwajuwon** [comment]
I can see the issue has been closed but it's yet to be fixed, does anyone knows how to go around this?

**Comment by xthezealot** [comment]
Use the [`splash`](https://docs.expo.dev/develop/user-interface/splash-screen-and-app-icon/#add-the-splash-screen-in-app-config) property instead.
