### ISSUE TITLE
README.md template for universal modules / installation guide

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#3315]
`README.md` proposal:

# expo-universal-module

_One brief sentence what this module is about._
`expo-universal-module` is an [Expo universal module](https://docs.expo.io/versions/latest/universal-modules). Provides access to some system features.

## Installation

_Installation guides on docs.expo.io_
* [with Expo](https://docs.expo.io/versions/latest/universal-modules)
* [without Expo (bare React Native)](https://docs.expo.io/versions/latest/universal-modules)

## API

Please refer to [official Expo documentation](https://docs.expo.io/versions/latest/sdk/).

## Contributing

_Maybe we should add sth like this https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md_

**Comment by bbarthec** [comment]
CC: @brentvatne @tsapeta  @sjchmiela

**Comment by brentvatne** [comment]
# expo-universal-module

_One brief sentence what this module is about. Provides access to some system feature._

## Installation

This package is pre-installed in all projects that are initialized with expo-cli. You may skip the rest of the installation guide if this applies to you.

For React Native projects that don't use the Expo platform, you must [install and configure the `@universal-modules/react-native-platform` package](link-to-instructions) before continuing - 
`expo-universal-module` is a [universal module](https://docs.expo.io/versions/latest/universal-modules).

### Add the package to your npm dependencies

```
npm install expo-universal-module
```

### Configure for iOS


### Configure for Android


### Configure for web

_Until we launch web support we don't need to include this section_

## API

Please refer to [official Expo documentation](https://docs.expo.io/versions/latest/sdk/).

## Contributing

_We definitely need to add something like CONTRIBUTING.md from react-native, for now we can point to https://github.com/expo/expo#contributing and we can update that when we have our own CONTRIBUTING.md to point to_

**Comment by brentvatne** [comment]
here's an example one:

<hr/>

# expo-localization

`expo-localization` provides an interface for native user localization information.

## Installation

This package is pre-installed in **managed** projects that are initialized with `expo-cli`. You may skip the rest of the installation guide if this applies to you.

For bare React Native projects, you must ensure that you have [installed and configured the `@unimodules/react-native-platform` package](https://github.com/unimodules/react-native-platform) before continuing.

### Add the package to your npm dependencies

```
npm install expo-localization
```

### Configure for iOS

Add the dependency to your `Podfile` and then run `pod install`.

```ruby
pod 'EXLocalization', path: '../node_modules/expo-localization/ios'
```

### Configure for Android

1. Append the following lines to `android/settings.gradle`:

    ```gradle
    include ':expo-localization'
    project(':expo-localization').projectDir = new File(rootProject.projectDir, '../node_modules/expo-localization/android')
    ```

2. Insert the following lines inside the dependencies block in `android/app/build.gradle`:
    ```gradle
    api project(':expo-localization')
    ```

3. In `MainApplication.java`, import the package and add it to the `ReactModuleRegistryProvider` list:
    ```java
    import expo.modules.localization.LocalizationPackage;
    ```
    ```java
    private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(Arrays.<Package>asList(
      // Other packages
      new LocalizationPackage()
      ), Arrays.<SingletonModule>asList());
    ```

## API

- [Documentation for the master branch](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/localization.md)
- [Documentation for the latest stable release](https://docs.expo.io/versions/latest/sdk/localization/)

## Contributing

Contributions are very welcome! We need you! Please refer to guidelines described in the [contributing guide]( https://github.com/expo/expo#contributing).
