### ISSUE TITLE
app:bundleDevMinSdkDevKernelReleaseExpoAssets FAILED Error: connect ETIMEDOUT 13.32.32.15:443

### ISSUE THREAD

**Issue by manoj-makkuboy** [expo/expo#3317]
After ejecting expo 31 running gradlew assembleRelease breaks in this step.

app:bundleDevMinSdkProdKernelReleaseExpoAssets
Error: connect ETIMEDOUT 13.32.32.227:443

run.sh works fine.

**Comment by AdamJNavarro** [comment]
Hey @manoj-makkuboy,

Can you provide more information regarding your environment so we can try and figure out why it's having an issue reaching the CloudFront to bundle the assets?

Cheers,
Adam

**Comment by manoj-makkuboy** [comment]
This Morning I again ran the same without any change, The build is successful.
