### ISSUE TITLE
expo-sqlite/kv-store could not be found within the project or in these directories: node_modules

### ISSUE THREAD

**Issue by Mani-GS** [expo/expo#33183]
### Summary

Hello,
I'm building a react native app and I'm trying to use the key-value storage of the expo-sqlite package ([this one](https://docs.expo.dev/versions/v52.0.0/sdk/sqlite/#key-value-storage)), but I'm getting the error in the title when I try to import the async storage, as stated in the docs:

`import AsyncStorage from 'expo-sqlite/kv-store';`

The app is currently using the old (and deprecated) package `@react-native-community/async-storage`, I also tried to remove it and install the newer one `@react-native-async-storage/async-storage`, but nothing changed. Could it depends on the version of yarn or something else I'm missing?

I installed the package with `npx expo install expo-sqlite`, as stated in the docs, but I can't figure out what I'm missing.

### What platform(s) does this occur on?

Android

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 18.19.1 - /usr/bin/node
      Yarn: 3.6.4 - /usr/local/bin/yarn
      npm: 9.2.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-35 | Google Play Intel x86_64 Atom
    npmPackages:
      expo: ^51.0.0 => 51.0.39 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    Expo Workflow: bare
```

### Minimal reproducible example

1. Install the package `npx expo install expo-sqlite`
2. Import the package `import AsyncStorage from 'expo-sqlite/kv-store';`

**Comment by Kudo** [comment]
hi there! `expo-sqlite/kv-store` is available from sdk 52. please try to upgrade sdk. after upgrading sdk 52, let me know whether the kv-store works for you. thanks!
