### ISSUE TITLE
Expo Router breaks React Native debugger

### ISSUE THREAD

**Issue by Ryguy10712** [expo/expo#33189]
### Minimal reproducible example

https://github.com/Ryguy10712/bugTest

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Expo router appears to break the react native debugger; causing source files to not show up properly.

When this project's entrypoint (`main` in `package.json`) is set to `index.ts` - not utilizing expo router - the debugger works fine. However- when the `main` is set to `expo-router/entry`, the debugger will not show me my source files

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.5.1 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 32, 33, 34, 35
        Build Tools: 30.0.3, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ~52.0.10 => 52.0.10 
      expo-router: ~4.0.8 => 4.0.8 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
    Expo Workflow: managed
```

**Comment by AryanJ-NYC** [comment]
I've got a very similar error.

I was able to run `npx create-expo-app@latest expo-example --template` and chose "Blank (TypeScript)." When built and installed on my physical device, it ran just fine.

However, when I run`npx create-expo-app@latest expo-example --template` and chose "Navigation(TypeScript)," and built/installed on my physical device, it was no longer able to find the source compiled by Metro:

![Screenshot 2024-11-22 at 4 31 59 PM](https://github.com/user-attachments/assets/89a95589-ba98-40ed-bc62-60f6b77a5196)

```
  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 13.6.7
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.asdf/installs/nodejs/18.17.0/bin/node
      Yarn: 1.22.17 - ~/.asdf/shims/yarn
      npm: 9.6.7 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.11.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 33, 34
        Build Tools: 34.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom, android-34 | Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    Expo Workflow: managed
```

**Comment by Ryguy10712** [comment]
Interesting. My app works fine- the main issue for is that the source files are not accessible in the react native debugger as shown below.
![image](https://github.com/user-attachments/assets/ec2adab6-06b3-44ad-82f6-cd260ab9f1a2)

**Comment by AryanJ-NYC** [comment]
> Interesting. My app works fine- the main issue for is that the source files are not accessible in the react native debugger as shown below. ![image](https://private-user-images.githubusercontent.com/102754966/389111229-ec2adab6-06b3-44ad-82f6-cd260ab9f1a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMTIyMTMsIm5iZiI6MTczMjMxMTkxMywicGF0aCI6Ii8xMDI3NTQ5NjYvMzg5MTExMjI5LWVjMmFkYWI2LTA2YjMtNDRhZC04MmY2LWNkMjYwYWI5ZjFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQyMTQ1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTI2ZjdlNGMxZWRlOTg4ODFlYjczNWNhZGZmODk5ZThhMzc3NTlkOWViZTRiNTBhYzkwMzFhNTQ0MTZhNWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9M74stsnvqGRh-jif1KwReC6dVtzXbXqyeI3Jt7pca4)

Ah, apologies. I'll make my own issue...

**Comment by YasinAkimura** [comment]
> Interesting. My app works fine- the main issue for is that the source files are not accessible in the react native debugger as shown below. ![image](https://private-user-images.githubusercontent.com/102754966/389111229-ec2adab6-06b3-44ad-82f6-cd260ab9f1a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTY0MTYsIm5iZiI6MTczMjQ1NjExNiwicGF0aCI6Ii8xMDI3NTQ5NjYvMzg5MTExMjI5LWVjMmFkYWI2LTA2YjMtNDRhZC04MmY2LWNkMjYwYWI5ZjFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxMzQ4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGNlNDQyYTFiM2VlYTZjMGMxMTgzYTllNGRhNGZmY2E3ZmQ2ODdjZjNiNTVmZTllZThhYjFjMTc0ZDU5ODE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JHWo7256hK29a3BIn4iQ_fcO_QvBo3ko-ar9JSEK2aY)

I found that weird too as it was mentioned that the debugger is better by default now as I saw no sources or only one file there I instantly rejected the debugger again. Good to know that there are sources without expo-router.

Question: Do we still need to use expo-tools for debugging?

**Comment by Ryguy10712** [comment]
Some strange success today. I made three changes at once and was able to see my source files finally. I backtracked to see what the root of my success was, but I ended up being able to revert all changes and still be able to see my sourcemaps. So I'm not sure what caused it, I just know that it worked. Here are the changes

Added metro.config.js to project root:
`// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

config.transformer = {
    ...config.transformer,
    getTransformOptions: async () => ({
        transform: {
            experimentalImportSupport: false,
            inlineRequires: false,
        },
    }),
    sourceMaps: true,
    sourceMap: true
}

module.exports = config;
`

Added babel.config.js to project root:
`module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    sourceMaps: true,
  };
};
`

On iPhone, went to Settings>Wi-Fi>Private Wi-Fi Address and set to "Off". I feel like this was the solution, but I cannot prove it. 

Can someone try these same things and see if you get similar behavior?

**Comment by YasinAkimura** [comment]
I tried adding sourceMaps: true to babel.config.js, clearing cache, disabling privacy network on iPhone, deleting .expo reinstalling node_modules and except of the expo router entrypoint there's nothing. I did not try enabling source maps in metro.config but I believe on webpack we had them on dev mode enabled by default so it would make sense to have them enabled there too. 
I mean it would right?? 
I guess that must be the fix it sounds at least logical but still weird why changing the entrypoint fixes it also.

# FIX: While writing above 
Funny thing I found another fix currently the default setting in devtools is to exclude node_modules by default but the entrypoint lives inside node_modules I disabled it restarted the debugger and now I have.. a bunch of source maps including mine 😂

**Comment by Ryguy10712** [comment]
Ah. I misled myself

# Confirmed solution, thanks @YasinAkimura

Before I begin, please disregard everything I said above about metro/babel config and iPhone network settings. I now realize they are unrelated to this issue.

I forgot that I had accidentally clicked a prompt asking to exclude an arbitrary transformer file from the ignore list right as I was testing things with the config files.

I tested your solution by going back to the clean-slate project I made to reproduce the bug, and did the following:
- Reset the react native debugger to defaults
- Checked sources, were not there
- Went to `React Native Debugger Settings>Ignore List>Custom Exclusion Rules` and disabled the exclusion rule for `/node_modules/|/bower_components`
- Restarted debugger
- Source files are now there, amongst many non-project files

If you don't want to get rid of `/bower_components/` for whatever reason, you can remove `node_modules/|` from the ignore string but it yields the same result as far as I can tell.

You can get rid of the annoying non-project files by clicking the three-dotted icon above the source files, and enabling `Hide ignore-listed sources`. It will only show YOUR source files alongside a singular transformer file

Going to leave this ticket open in case the expo/react/whatever team finds it useful to alter the default behavior of the debugger so devs don't have to go jumping through these hoops to find the solution.

**Comment by masarbazi** [comment]
Thanks all, issue resolved with excluing `/node_modules/bower_componenets/`.
Also good to mention another solution is to create an `index.ts` importing router entry: 
```typescript
import 'expo-router/entry';
```
and change main property in `package.json`:
```json
...
"main": "index.ts",
...
```

**Comment by marklawlor** [comment]
It appears Chrome Devtools is sharing settings with React Native DevTools. I'll update the Expo docs for now and speak to the team if there is a way we can work around this. Thanks for the report
