### ISSUE TITLE
[docs] difficult to read

### ISSUE THREAD

**Issue by ethanneff** [expo/expo#33193]
### Summary

https://docs.expo.dev/eas-update/deployment-patterns/#diagram-of-flow
![Screenshot 15](https://github.com/user-attachments/assets/1e617201-bc6b-4253-82b1-e6b95425c2df)

### Link to the related docs page

https://docs.expo.dev/eas-update/deployment-patterns/#diagram-of-flow

**Comment by ethanneff** [comment]
all diagrams on the page are like this

**Comment by brentvatne** [comment]
thanks @ethanneff - this looks like it regressed somehow recently, @Simek will investigate
