### ISSUE TITLE
Add information in docs about debugger options

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#332]
Reacotron
React Native Debugger
React Devtools

**Comment by slorber** [comment]
@brentvatne that would be very useful

Currently I have the chome console working but I have no idea how to plug an debugger to inspect native elements on my computer.

I've tried installing https://github.com/jhen0409/react-native-debugger but I can't understand anything about how it works unfortunatly :'(

**Comment by acomito** [comment]
@brentvatne is it possible to use react-devtools with expo running? The electron app startsup with the npm script, but doesn't seem to know where to grab the expo app from.

![screen shot 2017-08-24 at 10 37 47 am](https://user-images.githubusercontent.com/12701635/29671779-6244de32-88b8-11e7-86a0-c4edd2214aa5.png)

**Comment by slorber** [comment]
if anyone has a clear tutorial on how to debug remote app on device, please ping me ;)

**Comment by cruzach** [comment]
closing since [#5005](https://github.com/expo/expo/issues/5005) is a more descriptive issue (same premise, though)
