### ISSUE TITLE
ImagePicker returns blank base64

### ISSUE THREAD

**Issue by ilkarman** [expo/expo#3320]
I'm trying to use the .base64 property of the object returned by ImagePicker.launchImageLibraryAsync, however keep getting a blank result. However .uri property works:

``` 
_pickImage = async () => {
    const { status: cameraRollPerm } = await Permissions.askAsync(
      Permissions.CAMERA_ROLL
    );

    // only if user allows permission to camera roll
    if (cameraRollPerm === 'granted') {
      let pickerResult = await ImagePicker.launchImageLibraryAsync({
        base64: true,
        allowsEditing: true,
        aspect: [1, 1],
      });

      this._handleImagePicked(pickerResult);
    }
  };

  _handleImagePicked = async pickerResult => {
    let uploadResponse, uploadResult;

    try {
      this.setState({
        uploading: true,
      });

      if (!pickerResult.cancelled) {
        uploadResponse = await uploadImageAsync(pickerResult);
        uploadResult = await uploadResponse.json();

        this.setState({
          image: uploadResult.location,
        });
      }
    } catch (e) {
      alert('Upload failed, sorry :(');
    } finally {
      this.setState({
        uploading: false,
      });
    }
  };
}

async function uploadImageAsync(img) {
  let apiUrl = '...;
  let formData = new FormData();
  formData.append('input', {
    image: img.uri,
  });

  console.log('TEST');
  console.log(img.base64)
  console.log(img.uri);
```

Returns only the uri (file:///var/mobile/Containers/Data/Application/EF18D415-2365-4D12-8C44-CCD251A3A4A6/Library/Caches/ExponentExperienceData/%2540ilia.uk%252FYW1sXy/ImagePicker/ED27379D-8DAC-4596-B13C-E30EC4EDE866.jpg) and not base64:

I'm running this on iOS, expo v32. Unfortunately my endpoint requires a json encoded b64 string of an image.

**Comment by sjchmiela** [comment]
Hey, @ilkarman!

Could you please try logging the length of `img.base64` instead of the whole thing? I just tried reproducing the issue and, yes, base64 representation of the image wasn't being logged, but when I changed `console.log` to `console.log(img.base64.length)` it got logged properly. Maybe the string is too long and takes too much time to print?

https://snack.expo.io/@sjchmiela/image-picker

**Comment by meck93** [comment]
Hey @sjchmiela and @ilkarman!

I had a similar issue and I think you are right. I tried it with multiple different images. 
Sometimes I was able to log the base64 representation of the image and sometimes not. It seems like the string is just too long to log with certain images. `console.log(img.base64.length)` always worked.

**Comment by sjchmiela** [comment]
I'm glad you got that sorted out! 🎉
