### ISSUE TITLE
Icon Shows in Place of Splash Screen with Expo Go

### ISSUE THREAD

**Issue by nathanembaye** [expo/expo#33215]
### Minimal reproducible example

https://github.com/nathanembaye/expo_bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

This is in regard to expo go specifically. I expect it to show my icon.png image in the expo app (which it does) and on boot up show my splash.png image. The latter does not happen. Instead, the icon.png is shown with the start of the app. When I run the npx expo prebuild command with the ios flag the ios simulator does show the splash screen but I am specifically looking for it to be shown with expo go. 

https://github.com/user-attachments/assets/94e56718-7aa2-4ab9-9b83-bdb619355e47

```
{
  "name": "test",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "expo": "~52.0.11",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.9",
    "expo-splash-screen": "~0.29.13",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.4",
    "expo-web-browser": "~14.0.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.3",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.2"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },
  "private": true
}

```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.2.0 - /opt/homebrew/bin/node
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.9 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.4.1
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by powerwisdom** [comment]
Same for me, icon overrides the splash screen

**Comment by samf3nn** [comment]
Same for me.

**Comment by caiopratali** [comment]
Same for me.

**Comment by codymurphyjones** [comment]
Been trying to figure out what I did to break my splash screen and it turns out I did nothing wrong, this is happening to everyone.

Same issue on my end.

**Comment by Arjit0762** [comment]
Same for me, Coming from few days..

**Comment by nathanembaye** [comment]
Hey @brentvatne, do you know if this will be worked on soon?

**Comment by brentvatne** [comment]
this is expected behavior in sdk 52. see: https://expo.dev/changelog/2024/11-12-sdk-52#known-limitations-of-splash-screen-implementation

**Comment by brentvatne** [comment]
that said -- i'd love some advice on how we can communicate this better on the loading screen itself. i think right now it's definitely confusing and i'd love for it to be more clear that in expo go and dev builds you will see the app icon in the loading  view when reloading the app (vs the splash screen in dev builds the first time you launch the app)

**Comment by nathanembaye** [comment]
> that said -- i'd love some advice on how we can communicate this better on the loading screen itself. i think right now it's definitely confusing and i'd love for it to be more clear that in expo go and dev builds you will see the app icon in the loading view when reloading the app (vs the splash screen in dev builds the first time you launch the app)

My question (and likely most attached to this post) is simply how to set the app icon image vs splash screen image.

**Comment by brentvatne** [comment]
> > that said -- i'd love some advice on how we can communicate this better on the loading screen itself. i think right now it's definitely confusing and i'd love for it to be more clear that in expo go and dev builds you will see the app icon in the loading view when reloading the app (vs the splash screen in dev builds the first time you launch the app)
> 
> My question (and likely most attached to this post) is simply how to set the splash screen image, if not under the [app.json](https://github.com/nathanembaye/expo_bug/blob/master/app.json) file. The icon for the app is successfully set in that file, but the splash screen isnt?

i believe this is covered in the release notes, but let me know how we can clarify it further. this is explained here: https://docs.expo.dev/versions/v52.0.0/sdk/splash-screen/#configuration

the loading screen: what you see from within expo go or dev build when you are opening an app. so when you launch your app through a deep link in expo go, you'd see the expo go splash screen with the expo go image, then your own loading view. this reads from your app icon. we may expose a `loadingView` config for this in the future, but given that it only impacts what you see when you reload your app in development, we didn't want to block on releasing splash screen improvements for this.
the splash screen: the native asset that is embedded in your app at compile time. configure this using the config plugin. recompile your app to see the changes.

**Comment by codymurphyjones** [comment]
> that said -- i'd love some advice on how we can communicate this better on the loading screen itself. i think right now it's definitely confusing and i'd love for it to be more clear that in expo go and dev builds you will see the app icon in the loading view when reloading the app (vs the splash screen in dev builds the first time you launch the app)

I went through the documentation for expo-router and for expo-splash and simply never found any information even remotely hinting at it.  Not sure if I'm just blind and missed it, but I don't think a blog post is a good place for what could be perceived as a major breaking change (I understand its not a breaking change now, but it certainly felt like one)

**Comment by maiki11** [comment]
We dont have news about this fix? i still having the same issue

**Comment by Kungpowpow** [comment]
+1 Would be great to get this working in Expo Go.

**Comment by nabdulrub** [comment]
Having the same issue, would love a fix for this

**Comment by ClaytonDev100** [comment]
SAME

**Comment by awriyou** [comment]
why this issue is closed? I still have same issue, anyone can explain clearly? why i see icon.png in splash?

**Comment by brentvatne** [comment]
@awriyou - it's covered here in the release notes: https://expo.dev/changelog/2024/11-12-sdk-52#known-limitations-of-splash-screen-implementation

**Comment by rafayexalter** [comment]
Is there any better solution for it? I'm trying to show an animated splash screen,

**Comment by Solamatics** [comment]
Is there any form of fix for this issues yet?

**Comment by ayobamiseun** [comment]
any fix for this

**Comment by nabdulrub** [comment]
Anyone having this issue, its really because you don't see the splash screen in Expo Go, if you create a development build you'll see the splash screen from the app config on that build. it also shows up on production builds. just doesn't work on expo go anymore.

**Comment by ugoi** [comment]
reproduces for me, after i have updated the project to expo@53 now i see the icon instead of splash.
