### ISSUE TITLE
Xdl couldn't find react native package when upgrade to sdk52

### ISSUE THREAD

**Issue by lexie011** [expo/expo#33229]
### Minimal reproducible example

Use npx create-expo-app@latest to create a default template project.

### Where did you reproduce the issue?

in Expo Go

### Summary

Since upgrade to SDK 52, xdl shows error message 

> react-native is not installed. Please run `npm install` or `yarn` in your project directory.

It turns out that in doctor.ts file, xdl try to locate react-native/local-cli/cli.js to define whether react native is installed or not. 

[https://github.com/expo/expo-cli/blob/main/packages/xdl/src/project/Doctor.ts#L411](url)

In SDK 51, react native directory looks like this:
<img width="310" alt="Screenshot 2024-11-25 at 2 11 24 PM" src="https://github.com/user-attachments/assets/49ae4d74-96b9-46a3-964d-b6efca3fff8e">

However, in SDK 52, react native package doesn't have local-cli folder.
<img width="310" alt="Screenshot 2024-11-25 at 2 20 23 PM" src="https://github.com/user-attachments/assets/33a516fb-05d5-4abe-88ed-c10fe29fb298">

So I figure that's why this error message keeps occur. It would be a great help if you guys can take a look at this one and please let me know if you need more info. Thanks!

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.16.0/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.11.11.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-33 | Google Play Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.10 
      expo-router: ~4.0.6 => 4.0.7 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by Kudo** [comment]
hi there! the global `expo-cli` has been deprecated for a while. please try to run `npm remove -g expo-cli` and use local expo cli to run related command. e.g. `npx expo start`.
reference for deprecated global cli: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
