### ISSUE TITLE
MapView is not working with Expo Go in Expo SDK 52

### ISSUE THREAD

**Issue by Developer1970** [expo/expo#33225]
### Minimal reproducible example

https://github.com/Developer1970/expo-sdk52-mapview-bug/tree/main

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

MapView module does not seem to be included in Expo Go. The following stack trace is visible when sample app is running with Expo Go: 

```
iOS Bundled 792ms node_modules/expo/AppEntry.js (670 modules)
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 INFO  
 💡 JavaScript logs will be removed from Metro in React Native 0.77! Please use React Native DevTools as your default tool. Tip: Type j in the terminal to open (requires Google Chrome or Microsoft Edge).
 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

This error is located at:
    in AIRGoogleMapMarker (created by MapMarker)
    in MapMarker (created by App)
    in AIRGoogleMap (created by MapView)
    in MapView (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 (NOBRIDGE) ERROR  Warning: TypeError: Cannot read property 'bubblingEventTypes' of null
```
This issue is not reproducible with Android (although issue #33212 is present in Android and dev build). 

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
      Shell: 5.2.21 - /bin/bash
    Binaries:
      Node: 20.5.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 10.9.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-34 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ^52.0.11 => 52.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.6 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Validate packages against React Native Directory package metadata
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: @expo/metro-runtime
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.
```

**Comment by brentvatne** [comment]
Expo Go does not support Google Maps for iOS and maps support for Android will be dropped entirely in SDK 53.

Use development builds! Learn more: https://expo.fyi/expo-go-usage

**Comment by Developer1970** [comment]
So, you're saying Expo cannot be used to develop a map-based application if I am not mistaken, right? You do have this documentation here: https://docs.expo.dev/versions/latest/sdk/map-view/ still up there! You haven't event bothered to pull the doc down. 

How do you expect companies to pay for Expo for builds and support when you are pulling the plug on my investment? I am a '650 Industries' paying customer and you're dropping support without any communication!

By the way, react-native-maps has this issue: https://github.com/react-native-maps/react-native-maps/issues/5229, AND it is reproducible in development build (at least on Android)! 

React Native with Expo seems to be a really bad choice, amateurs!

**Comment by Lopoi** [comment]
> So, you're saying Expo cannot be used to develop a map-based application if I am not mistaken, right? You do have this documentation here: https://docs.expo.dev/versions/latest/sdk/map-view/ still up there! You haven't event bothered to pull the doc down.

**Expo Go** wont have map support anymore, but Expo itself will still have, as the library for maps is just `react-native-maps` anyways.

You just have to make a development build for testing instead of using the **Expo Go** in the App/Play Store.

I'm not a fan of this change, but ohh well.

> [...] you're dropping support without any communication!

This was mentioned in the [deprecations section on the Expo 52 Changelog](https://expo.dev/changelog/2024/11-12-sdk-52#deprecations). And I presume it was mentioned before, but I didnt go back to check.

**Comment by Developer1970** [comment]
OK, but it does not work on dev build either, and here are repro steps: https://github.com/expo/expo/issues/33212

**Comment by zzjoey** [comment]
Have the same issue in SDK 52 too, I solved it by 
- delete the apps on iOS simulator
- `npx pod-install`
- `npx expo run:ios`

Wait for it rebuild from scratch, and it works.

**Comment by Developer1970** [comment]
> Have the same issue in SDK 52 too, I solved it by
> 
> * delete the apps on iOS simulator
> * `npx pod-install`
> * `npx expo run:ios`
> 
> Wait for it rebuild from scratch, and it works.

This cannot possibly be a solution to this issue. First, you seem to have a mix of managed and native code and you're not using pure Expo managed code. You could have modifications in your XCode or what have you. 

This issue (as I stated above) is also reproducible with dev builds at least on Android. It is reproducible on Expo Go, and as of now, Expo Doctor has added the following note: 

Unsupported on New Architecture: react-native-maps

Which means react-native-maps is not supporting new architecture, which is 

Please see this instructions: https://reactnative.dev/architecture/landing-page to make sure your native project is using new architecture. The solution to this issue is not some form of configuration change! You must be not using the new architecture and/or have native modification in your project and/or inadvertently using an older version of React Native. Here is further reading: https://reactnative.dev/blog/2024/10/23/the-new-architecture-is-here

Your app will eventually stop working when you fix these configuration issues

**Comment by roy-law** [comment]
same here. Couldn't get react-native-maps using Google provider to work with expo SDK 52 whatsoever

**Comment by aliunco** [comment]
I'm not sure what is the main reason of dropping support of the google map in expo go (v52)! but obviously it's a shame! and absolutely it will effect my decision (I assume not only me) about using expo from now and then.

**Comment by Ferm0494** [comment]
Any updates on this? I have even tried the dev-build and it;s still 
```
TypeError: Cannot read property 'bubblingEventTypes' of null
```

**Comment by yolohead** [comment]
I had the same error with expo SDK 52 . And I beat my head for a whole day until I somehow made It work.
I am not sure how many of you have/had this experience.  Basically, what I noticed was my app seem to run fine on my IOS simulator and only used to fail with this issue on the Physical device. 

Therefore, I had a feeling that the  build specifically that was deployed by expo on my device might/must have some problem.
And so in order to do a deploy a fresh build onto my device, 

>  I deleted the deployed app on my iPhone manually using "Remove this app" option.
>  Created a Signing Certificate in "Signing & Capabilities" in Xcode. It was missing for me.
>  Build/Run the app. It succeeded without any issue in Xcode. This way I had fresh build on my device.
>  App loaded, however incomplete. So, I started expo using --> npm run start
>  Restarted the app on my device . This time the App worked successfully and Map works without any issue

Hope this helps somebody :)

**Comment by prxneeth** [comment]
just stopping the server and rebuilding the app worked for me, on development build.

**Comment by avin1208** [comment]
use **PROVIDER_DEFAULT instead of PROVIDER_GOOGLE** in Your MapView component.

```
        <MapView style={styles.map}
                provider={PROVIDER_GOOGLE}
                ref={map}
/>
```
