### ISSUE TITLE
Self-hosted apps can't handle Expo.Linking-made URLs

### ISSUE THREAD

**Issue by kaiocristian** [expo/expo#3323]
### Description

Expo's self-hosted apps feature seem to have changed the old Linking schema-made URLs from `exp://exp.host/@whatever/whatever/--/THAT` to `exp://my-real-host/android-index.json/THAT` and it doesn't work as expected, as Expo's Linking seems to only be able to handle URLs (on non-standalone apps) that contains the `/--/` part on it.

It is important to note that if I manually write and try to handle URLs like `exp://my-real-host/android-index.json/--/THAT`, it does work.

On standalone builds it continues to work correctly, as the Linking scheme did not change and is still something like `exp://whatever/THAT`, even when self-hosted.

### Steps to Reproduce

1. Create and deploy a self-hosted app that uses and handles Linking-made URLs, like `Linking.makeUrl('auth')`
2. Open the project on your Expo client
3. Try to run the code part that handles (opens) the Linking URL

### Expected Behavior

[Handle the self Linking URL correctly](https://docs.expo.io/versions/latest/workflow/linking/#linking-to-your-app).

### Actual Behavior

Expo's blue screen of death with the following message:

```
Something went wrong.

Could not load exp://my-real-host/android-index.json/THAT.
```

### Reproducible Demo

https://snack.expo.io/BJzlwYw74

IMPORTANT: First button link (with dashes) on the demo Snack wont work anymore as @quinlanj changed the repository URL but didn't update the bundle URL on `android-index.json` nor `ios-index.json` files or did a new `expo export` with the new repo URL (pretty sure it is needed?), but you can see that the thrown errors are different. Sample repository links on [Expo's self-host documentation](https://docs.expo.io/versions/latest/distribution/hosting-your-app/) also seem to be broken as the repository name changed.

**Comment by Webdev259** [comment]
@kaiocristian Were you able to resolve this issue?

**Comment by bonafidehan** [comment]
Reproduced the bug on Expo Client Android 2.15.4 and iOS 2.15.2 & Expo 36. On Expo client, `Linking.makeUrl(...)` generates `exp://IP:PORT/--/PATH`. I'm going to do a workaround using `Constants.appOwnership` and custom generate a URL.

Will check whether this bug happens in standalone.

cc @Webdev259

**Comment by byCedric** [comment]
This should now be [resolved with `expo-linking`](https://github.com/expo/expo/pull/7934). Please open up a new issue if this still doesn't work for you with `expo-linking`!

Hope it helps 😄

**Comment by ngtrhieu** [comment]
I still encounter this issue which prevent oauth2 authentication callback. For example:
```Js
import * as Linking from 'expo-linking';
const callbackUrl = Linking.makeUrl('/'); // exp://<YOUR_HOST>/ios-index.json//
```
Authenticating with this callbackUrl will result expo complaining "There was a problem loading the requested app" with the url look something like this: `exp://<YOUR_HOST>/ios-index.json//?code=<AUTH_CODE>`

Can expo launch the app from url such as 'exp://<YOUR_HOST>' instead of 'exp://<YOUR_HOST>/ios-index.json', so that react-navigation can pick up the path behind?
