### ISSUE TITLE
Android/iOS AppIdResolver does not resolve gradle.properties and xcconfig vars

### ISSUE THREAD

**Issue by Voxar** [expo/expo#33232]
### Summary

For a white label app we inject our app/bundle identifiers into ios/android projects.

#### Android
For Android we use a brand.properties that we pull into the build.gradle
brand.properties
```
bundleId=org.TrakkLoRa
```
app/build.gradle
```
def brandProperties = new Properties()
file("../brand.properties").withInputStream { brandProperties.load(it) }

android {
    defaultConfig {
        applicationId brandProperties.bundleId
```

#### iOS
For iOS we use a brand.xcconfig and custom build property.

Brand.xcconf
```
BRAND_BUNDLE_ID=our.bundle.id
```
.xcproject
```
PRODUCT_BUNDLE_IDENTIFIER = $(BRAND_BUNDLE_ID)
```
Info.plist
```
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
```

This works great when building from XCode and Android Studio but when attempting to run from the expo cli (via metro) we get these messages 

> Failed to locate the android application identifier in the "android/" folder. This is required to open the app

> Failed to locate the ios application identifier in the "ios/" folder. This is required to open the app

### What platform(s) does this occur on?

Android, iOS

### SDK Version

50? RN 0.76

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 3.6.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.14.0 - ~/.asdf/installs/nodejs/20.14.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 31, 32, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^12.0.1 => 12.0.1 
      expo: ~52.0.7 => 52.0.7 
      expo-router: ~4.0.6 => 4.0.6 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.2 => 0.76.2 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Minimal reproducible example

Can not invest the time to set up a new project at this time but let me know when you pick this up and I might be able to assist. 

1. Create new project and generate platform folders
2. Create brand.properties
3. Copy&Paste above gradle code
4. Create brand.xcconfig
5. Assign in xcode > Project > Info tab > Configurations > "Add Configuration File.." for Debug and Release

**Comment by Voxar** [comment]
I am migrating to RN 0.76 from RN 0.73 where this system is still working.

Here's the `npx expo-env-info` output from the 0.73 project. I guess we don't use expo at all there tho. 
```
  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 3.6.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.14.0 - ~/.asdf/installs/nodejs/20.14.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
      Android SDK:
        API Levels: 31, 32, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      react: ^18.2.0 => 18.3.1 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare
```

**Comment by vonovak** [comment]
Hello and thanks for reporting,
For white-labeling, [CNG](https://docs.expo.dev/workflow/continuous-native-generation/) is the tool of choice, which you can use by having an app config file (where you can dynamically set your white-labeling) and running [`expo prebuild`](https://docs.expo.dev/workflow/prebuild/). If you use Expo, and you probably should (😄), then I recommend taking a look at that.

I'm sorry but this is a bug tracker and we require reproducers. Especially if you "guess we don't use expo at all."

Thank you 🙂

**Comment by Voxar** [comment]
Thank you @vonovak, I will definitely have a look at that! Would be happy to adapt to anything helping us with white labelling. I had no idea that Expo actually came with white labelling in mind at all. 

Do I understand it correctly that we should move towards not modifying the generated native folders at all but rather generate them each time as part of the build process?
And in addition to that instead of making changes to Podfile and grade files as requested by packages such as Mapbox, react-native-vision-camera, react-native-permissions (I guess this one might have a better expo substitute already?) etc we should write custom plugins and mods to do that instead?

**Comment by vonovak** [comment]
Hi!
It's not that prebuild was specifically designed for that use case, it just lends itself to it really well.

Yes, typically you wouldn't keep the android and iOS directories in git, though you can (losing the benefits of prebuild).
Yes, modifying to native files should not happen manually but through config plugins.
Many libraries already come with config plugins to support prebuild. Expo itself also allows you to make modifications to some things such as info.plist or entitlements: https://docs.expo.dev/versions/latest/config/app/#infoplist

For the rest, you should write your own. There's enough existing plugins to get inspired from.
