### ISSUE TITLE
[expo-splash-screen & expo-updates] Splash screen shows black screen if a lot of assets are imported

### ISSUE THREAD

**Issue by MaksymA26** [expo/expo#33257]
### Summary

After adding expo-updates we noticed a black screen appearing in the middle of splash screen in production builds. We found that by removing assets from the the project the black screen was no longer appearing and things are working as expected. Unfortunately removing assets is not the solution for us as we need them to be in the project. I believe we have the same issue as the guys in this issue: https://github.com/expo/expo/issues/30729. Here is the link to MRE: https://github.com/MaksymA26/expo-splash-mre 

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo": "~52.0.11",
"expo-dev-client": "~5.0.4",
"expo-updates": "~0.26.9",
"expo-splash-screen": "~0.29.13",

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.6.0 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/maksymaleieiv/.rvm/gems/ruby-3.3.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 33, 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.9 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.4.2
      expo-cli: 6.3.12
    Expo Workflow: managed
```

### Reproducible demo

Here is the link to reproduction repo: https://github.com/MaksymA26/expo-splash-mre

**Comment by mvanroon** [comment]
Also encountering this exact issue but we are not using `expo-updates`.

Splash screen is shown -> Short black flash -> Splash screen is shown again -> Splash screen is hidden.

**Comment by erickreutz** [comment]
Also experiencing this issue

**Comment by dkahdwk** [comment]
same issue.

(expo bare workflow)
- react-native: 0.76.2
- expo: 52.0.11
- expo-updates: 0.26.9
- react-native-bootsplash

**Comment by andrejpavlovic** [comment]
Removing `expo-updates` fixes the issue with the quick fade out to black. Setting `updates.fallbackToCacheTimeout` to `0` doesn't help unfortunately. It seems that `expo-updates` had issues in the past when interacting with the splash screen, so maybe this is a regression of sorts.

**Comment by chrfalch** [comment]
After investigating similar issues that was previously fixed I came across the issue #12000. Could this be a regression that was previously fixed in #18229?

**Comment by kubmir** [comment]
We face similar issue after update to Expo 52 and therefore update of expo-updates to 0.26.9. We use new architecture.

**Comment by alanjhughes** [comment]
@chrfalch working on a fix now. Should have a PR ready soon 👍

**Comment by AskoK** [comment]
Is this only me or this black screen is now replaced with white one? After updating expo-updates and expo-modules-core the black screen is gone but same flow happens with white one

**Comment by chrfalch** [comment]
Could this be a dark/light mode issue?

**Comment by AskoK** [comment]
@chrfalch - Seems to happen regardless of the theme. But maybe I have some other underlying issue there, just started to happen after updating to sdk 52. I will dig into it

**Comment by chrfalch** [comment]
@AskoK - The issue with the black/white flicker should be fixed in #33432 (which is not released in SDK 52 yet).

**Comment by AskoK** [comment]
@chrfalch - I think it was released in expo-updates 2.26.10 and it actually changed something, for me from black to white

**Comment by chrfalch** [comment]
The fix was merged yesterday #33432 - so it is not out yet.

**Comment by AskoK** [comment]
@chrfalch - I think GitHub is bit out of date with it cause I have these changes in my codebase already
https://github.com/expo/expo/pull/33432/files

I see there is fallback color white so maybe I'm missing something myself

**Comment by chrfalch** [comment]
> @chrfalch - I think GitHub is bit out of date with it cause I have these changes in my codebase already https://github.com/expo/expo/pull/33432/files
> 
> I see there is fallback color white so maybe I'm missing something myself

You might be right! I know there has been some movement related to `Expo Splashscreen` in SDK 52 - so this might very well be right - another PR is also in the works adding support for setting up both [dark/light mode background colors](https://github.com/expo/expo/pull/33472) on iOS.

**Comment by alanjhughes** [comment]
@AskoK - Can you share your app.json config? Not all of it, just how you are setting up the splashscreeb

**Comment by AskoK** [comment]
@alanjhughes - I don't have any config inside app.json as I'm using bare project. But I got it working, seems I had problem with splashscreen storyboard after sdk update on iOS and it works now (I don't know how it even worked before, maybe something was cached). Sorry for confusion

**Comment by dkahdwk** [comment]
Is there a fixed version of this issue?
If you update to the latest version, the background color of the splash image will be exposed to white, not the issue phenomenon of existing black. The latest version is not out yet, right?

- expo: 51.0.17
- expo-updates: 0.26.10

**Comment by kubmir** [comment]
There was a short period of time when it worked after this released of Expo Updates but it is white now. I think it started with minor update of Expo itself. Our versions are aligned with Expo Doctor recommendations.

**Comment by joefour** [comment]
Same issue here after upgrading to the latest expo and expo-splash-screen by using `npx expo install --fix`

**Comment by kubmir** [comment]
@alanjhughes can we re-open this ? It is not working with the newest set of libraries (aligned with expo doctor).

If I use "splash" config key in app.json then everything works mostly fine on iOS but there is white screen flickering on Android. It was the same with black screen flickering in the past.

If I switch to `expo-splash-screen` plugin with config containing `iOS` field then iOS splash screen displays only background color (and dismiss correctly) and Android is stuck on the splash screen - App is never rendered. I follow the documentation described [here](https://docs.expo.dev/versions/latest/sdk/splash-screen/#usage) but it is not working like it is documented.

**Comment by alanjhughes** [comment]
@kubmir please provide a minimal example and explain how you are testing, expo go or development builds

**Comment by dkahdwk** [comment]
@alanjhughes Didn't you understand the situation of this issue and decide to solve it? I think the environment where the problem occurred was sufficiently provided by people as mentioned above.

**Comment by alanjhughes** [comment]
@dkahdwk I understood it fine. the problem was resolved against the provided example. If you still have the problem, then provide an example that reproduces it again.

**Comment by alanjhughes** [comment]
@kubmir I appreciate it is not easy to reproduce but you have more means to do this than I do. I don't have access to a production app with a significant number of assets. I can't make changes to something without reproducing the problem because that risks further regressions.

> significantly slower on iOS device comparing

Can you elaborate on this a bit more? Slow in what way?

**Comment by atif089** [comment]
I'm facing the same problem on Android as well.

```
"react-native": "^0.76.5",
"expo-splash-screen": "~0.29.18",
"expo": "~52.0.20",
```

**Comment by dkahdwk** [comment]
@alanjhughes 
It's still an issue, so I'll give you a link to an example of reproducing the issue. When you build a project in release mode in an iOS environment, the issue of the splash's background color temporarily appearing white is reproduced.
https://github.com/dkahdwk/AwesomeProject

**Comment by uoon-dev** [comment]
I got the same problem after I migrated from expo 51 to 52. 
White screen appears in production when eas updated.

```
"expo": "^52.0.0",
"expo-splash-screen": "~0.29.18",
"react-native": "0.76.5",
```

**Comment by raahimkhan** [comment]
Getting same black screen before splash screen appears on Expo SDK 52 (new arch enabled). Was working fine on Expo SDK 51 (old arch). I also have expo-updates installed but issue came when I migrated from SDK 51 (old arch) to SDK 52 (new arch).

**Comment by Hosam-hsm** [comment]
Experiencing the same issue. 

```
"expo": "~52.0.25"
"expo-splash-screen": "~0.29.20"
"react-native": "0.76.6"
```

**Comment by Raidden** [comment]
Having the same issue expo 52 old arch

**Comment by dkahdwk** [comment]
@andrejpavlovic 
Why isn't the issue being resolved?
It is urgent to resolve the issue because our service needs to introduce expo-updates into the expo-bare environment before code push ends.

**Comment by shoxter** [comment]
Following -- same problem on arch.

**Comment by raahimkhan** [comment]
Any resolution yet?? Still getting same as of today.

**Comment by raahimkhan** [comment]
Any resolution yet? Still getting same issue as of April 17th 2025.

**Comment by raahimkhan** [comment]
I am using the following versions:

"expo": "~52.0.37"
"expo-updates": "^0.27.4"
"expo-splash-screen": "~0.29.22"

For me the issue of black screen only comes in development mode. It's fine in production. So far good for me. However, still it would be good to know what's causing the black screen in dev mode.

**Comment by leonardorib** [comment]
Experiencing the same behavior with `expo-splash-screen` + `expo-updates` on SDK 53. I see the native splash screen but then it "blinks" with a black screen and then it returns to the splash screen.

I am on bare workflow. New arch is enabled. I can only really notice it in the release build.

`package.json`
```json
"react-native": "0.79.5",
"expo": "~53.0.16",
"expo-asset": "~11.1.6",
"expo-updates": "~0.28.16",
"expo-splash-screen": "~0.30.10",
```

`ios/appName/Supporting/Expo.plist`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>EXUpdatesEnabled</key>
    <true />
    <key>EXUpdatesHasEmbeddedUpdate</key>
    <false />
    <key>EXUpdatesCheckOnLaunch</key>
    <string>ALWAYS</string>
    <key>EXUpdatesLaunchWaitMs</key>
    <integer>60000</integer>
    <key>EXUpdatesURL</key>
    <string>https://u.expo.dev/xxxx-xxxx-xxx-xxxxx-xxxxxx</string>
    <key>EXUpdatesRuntimeVersion</key>
    <string>x.x.x</string>
    <key>EXUpdatesRequestHeaders</key>
    <dict>
      <key>expo-channel-name</key>
      <string>dev</string>
    </dict>

    <!-- https://docs.expo.dev/versions/latest/config/app/#disableantibrickingmeasures -->
    <key>EXUpdatesDisableAntiBrickingMeasures</key>
    <true />
  </dict>
</plist>
```

I know `SplashScreen.preventAutoHideAsync()` is working because if I don't call `SplashScreen.hide` the splash screen stays there forever. So it is not auto hiding. I tried to move that call even earlier (`index.js`) but didn't have any effect.

If I disable expo updates by setting `EXUpdatesEnabled` to `<false />` the issue is solved.

We have `EXUpdatesDisableAntiBrickingMeasures` enabled in dev/staging to allow PR previews on Testflight. But even setting that to `<false />` it still triggered the issue.

**Comment by w4t3r-45** [comment]
having the same issue OTA is leading to white or black screen (based on light or dark theme in the mobile phone) any good versions or patch to test please.

new arch disabled

- expo-splash-screen: 0.29.24
- expo-updates: 0.27.4
- expo: 52.0.46

**Comment by billyjacoby** [comment]
Why was this issue closed? I'm having this issue in a production build on iOS on 53 after switching the new arch enabled.

For anyone else that runs into this issue adding a `setImmediate` seems to fix the issue

```jsx
    setImmediate(() => {
      SplashScreen.hideAsync().then(() => setIsSplashHid(true));
      if (IS_ANDROID) {
        setVisibilityAsync('hidden');
      }
    });
```

**Comment by noumantahir-authority-partners** [comment]
I am facing this issue, splash screen appears, tuns back, splash comes back and the app opens, I do have expo-spalsh-screen installed as well.... any fixes, I tried the above solution by @billyjacoby but it did not help. Perhaps I am using the fix wrongly. 

https://github.com/user-attachments/assets/f6a801f7-01fc-4160-b247-a1b3d573a801

**Comment by charlespalmerbf** [comment]
I'm also experiencing this on an application using expo-updates and expo-splash-screen, I assume there's still no updates on this thread?

Pattern is the same as explained above, splash-screen -> black screen -> splash screen -> app load.

"expo": "^54.0.0",
"expo-splash-screen": "^31.0.13",
"expo-updates": "~29.0.16",
