### ISSUE TITLE
Web Navigation Issue, browser History Mismatch with UI State 

### ISSUE THREAD

**Issue by Jawkx** [expo/expo#33265]
### Minimal reproducible example

https://github.com/expo/expo/tree/main/templates/expo-template-default

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Browser's back/forward buttons don't sync correctly with app's UI

To Reproduce:
1. Create a new expo app using `npx create-expo-app@latest`
2. Run `npm run web` 
3. Navigate to Explore tab by pressing the bottom tab "explore" button
4. Use browser's back button to navigate back to "home" tab
5. Now press browser's "go-forward" button, the url will be updated to "/explore" but the UI will remain in `Home` tab

I'm not sure if  this behavior is intended, it's really confusing and doesn't get documented anywhere. I face similar issue in my own expo project too.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Linux 6.12 Arch Linux
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 22.1.0 - ~/.asdf/installs/nodejs/22.1.0/bin/node
      npm: 10.7.0 - ~/.asdf/plugins/nodejs/shims/npm
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.9 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Fixed in #33524 will be released in the next patch shortly
