### ISSUE TITLE
Failing EAS build iOS SDK52

### ISSUE THREAD

**Issue by islamashraful** [expo/expo#33278]
### Minimal reproducible example

https://github.com/islamashraful/expo52-eas-workflow

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Created new app using `bunx create-expo-app@latest`

Configure eas build using `eas build:configure`

Run eas build locally using `eas build --profile development-simulator --platform ios --local`

Run into build failure

```
[INSTALL_PODS] 100 16.3M  100 16.3M    0     0  27.0M
[INSTALL_PODS] 0 --:--:-- --:--:-- --:--:-- 27.0M
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "SocketRocket":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     React-CoreModules (from `../node_modules/react-native/React/CoreModules`) was resolved to 0.76.3, which depends on
[INSTALL_PODS]       SocketRocket (= 0.7.1)
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `SocketRocket (= 0.7.1)`.
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.
[INSTALL_PODS] [!] [Codegen] warn: using experimental new codegen integration
[INSTALL_PODS] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `E593AC141C0D45578380A46E` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
[INSTALL_PODS]
Error: pod install exited with non-zero code: 31
    at ChildProcess.completionListener (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at installPods (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/dist/ios/pod.js:12:50)
    at runInstallPodsAsync (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/dist/builders/ios.js:225:70)
    at /Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/dist/builders/ios.js:77:19
    at BuildContext.runBuildPhase (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/dist/context.js:107:34)
    at buildAsync (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/dist/builders/ios.js:76:19)
    at async runBuilderWithHooksAsync (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.iosBuilder (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/@expo/build-tools/dist/builders/ios.js:35:16)
    at async buildIosAsync (/Users/ashrafulislam/.npm/_npx/203b5a3d3de594cf/node_modules/eas-cli-local-build-plugin/dist/ios.js:44:12)

Build failed
```

### Environment

```text
bunx expo-env-info                                                       ✘ INT

  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
      Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2411.12169540
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11
      expo-router: ~4.0.9 => 4.0.9
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
bunx expo-doctor@latest
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by gijsjager** [comment]
I am also running onto (almost) the same issue with SDK 52

```
!] Unable to find a specification for `EXImageLoader` depended upon by `ExpoImageManipulator`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
[!] [Codegen] warn: using experimental new codegen integration
[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `06E8D7E0239844F9A39A7362` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
```

**Comment by joaobsantos** [comment]
I have the same problem with my production app, and I tried with a clean one, and got the same result building for development.

Expo 52 with bun.

On run gradlew step in eas:

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
Android resource linking failed
error: resource style/Theme.SplashScreen (aka com.test.appInternal:style/Theme.SplashScreen) not found.
com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1826: error: style attribute 'attr/windowSplashScreenBackground (aka com.test.appInternal:attr/windowSplashScreenBackground)' not found.
com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1827: error: style attribute 'attr/windowSplashScreenAnimatedIcon (akacom.test.appInternal:attr/windowSplashScreenAnimatedIcon)' not found.
com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1828: error: style attribute 'attr/postSplashScreenTheme (akacom.test.appInternal:attr/postSplashScreenTheme)' not found.
error: failed linking references.

**Comment by joaobsantos** [comment]
I have the same problem with my production app, and I tried with a clean one, and got the same result building for development.

expo 52 with bun

On run gradlew step in eas:

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
Android resource linking failed
error: resource style/Theme.SplashScreen (aka com.test.appInternal:style/Theme.SplashScreen) not found.
com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1826: error: style attribute 'attr/windowSplashScreenBackground (aka com.test.appInternal:attr/windowSplashScreenBackground)' not found.
com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1827: error: style attribute 'attr/windowSplashScreenAnimatedIcon (akacom.test.appInternal:attr/windowSplashScreenAnimatedIcon)' not found.
com.test.appInternal.app-mergeDebugResources-29:/values/values.xml:1828: error: style attribute 'attr/postSplashScreenTheme (akacom.test.appInternal:attr/postSplashScreenTheme)' not found.
error: failed linking references.

**Comment by joaobsantos** [comment]
I've removed expo-splash-screen from app.json-plugins and it solved the eas build problem:

 "plugins": [
      "expo-router",
      [
        "expo-splash-screen",
        {
          "image": "./assets/images/splash-icon.png",
          "imageWidth": 200,
          "resizeMode": "contain",
          "backgroundColor": "#ffffff"
        }
      ]
    ],

**Comment by yehonadav** [comment]
i also have this issue

**Comment by yehonadav** [comment]
my workaround in `package.json` after reading https://docs.expo.dev/build-reference/npm-hooks/

```
"scripts": {
    "eas-build-pre-install": "pod repo update",
```

that fixed the problem for me.

**Comment by Guybaron14** [comment]
> my workaround in `package.json` after reading https://docs.expo.dev/build-reference/npm-hooks/
> 
> ```
> "scripts": {
>     "eas-build-pre-install": "pod repo update",
> ```
> 
> that fixed the problem for me.

tried it, and got `sh: 1: pod: not found`.

did you try it on expo 52?

**Comment by mgscreativa** [comment]
@Guybaron14 have you installed cocoa pods cli in your dev mac?

**Comment by Ozaoujal** [comment]
> my workaround in `package.json` after reading https://docs.expo.dev/build-reference/npm-hooks/
> 
> ```
> "scripts": {
>     "eas-build-pre-install": "pod repo update",
> ```
> 
> that fixed the problem for me.

Thank you, this was the answer for me!

**Comment by SFaraji** [comment]
Same issue.

**Comment by twwspes** [comment]
> my workaround in `package.json` after reading https://docs.expo.dev/build-reference/npm-hooks/
> 
> ```
> "scripts": {
>     "eas-build-pre-install": "pod repo update",
> ```
> 
> that fixed the problem for me.

Ta! That works for me even for upgrading project to Expo 53
