### ISSUE TITLE
[docs] Outdated third party library in "Display a popup toast"

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#33283]
### Summary

In this documentation (https://docs.expo.dev/ui-programming/react-native-toast/), you are recommending to use `react-native-root-toast`, which seems to be unmaintained. I am not sure, but we may have to migrate to `react-native-toast-message`, which has a WAY BETTER UI, 10x times more downloads on `npm`, and last release was 2 months ago.

Please consider taking a look

* https://www.npmjs.com/package/react-native-root-toast
* https://www.npmjs.com/package/react-native-toast-message

### Link to the related docs page

https://docs.expo.dev/ui-programming/react-native-toast/

### Anything else?

Love you all!

**Comment by amandeepmittal** [comment]
hi there! we've removed this ui-programming section of the docs, because it is mostly out of date and we think that https://reactnative.directory/ is a better place to go for this.

ref: https://github.com/expo/expo/pull/33614
