### ISSUE TITLE
eas build for android is giving me a tar.gz

### ISSUE THREAD

**Issue by Pedro-Prev** [expo/expo#33291]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by Pedro-Prev** [comment]
I always built it with eas build, then selected an option from the list on the console or ran eas build --platform android --profile production.

I know my eas.json is correct because I always got exactly what I wanted. If I ran it for iOS, it gave me an .ipa, and for Android, an .aab.

On my last build two weeks ago, everything went well. But now, when I do it, I always get a .tar.gz. I extracted it, found an .aab inside, and sent it to Google Console (currently under analysis). Now I’m curious: why did this change happen? Was it a change in Expo's build process or something else?

**Comment by creativeoutlet-ranique** [comment]
Hi there, I'm also having this issue. Did anyone provide suggestions on transitioning file from tar.gz to .aab file?

**Comment by jaltin** [comment]
Same here, just stumbled on this problem. Anyone fixed it?

**Comment by di-sukharev** [comment]
+1

here is my eas.json:

```json
{  "build": {
    "development": {
      "environment": "development",
      "extends": "base",
      "developmentClient": true,
      "distribution": "internal",
      "env": {
        "EXPO_PUBLIC_API_URL": "https://wpr-backend.fly.dev"
      },
      "android": { "buildType": "apk" }
    },
}}

**Comment by jaaywags** [comment]
I renamed my android folder to something else (like `android-temp`) and then re-ran the eas build and got just an aab file.

I suppose you could just delete the android folder. I think there is some issue maybe where the prebuild uses dev keystores and then the eas build works off of the existing android folder and creates a dev build.
