### ISSUE TITLE
expo router entry.js props.pointerEvents is deprecated. Use style.pointerEvents

### ISSUE THREAD

**Issue by rentals19** [expo/expo#33290]
### Minimal reproducible example

https://github.com/rentals19/rentapps

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

C:\Users\gchan\app1\app1\node_modules\expo-router/entry.js ░░░░░░░░░░░░░░░░  0.0% (0/1)λ  WARN  props.pointerEvents is deprecated. Use style.pointerEvents

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      expo: ~52.0.11 => 52.0.11
      expo-router: ^4.0.9 => 4.0.9
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

**Comment by rentals19** [comment]
I got a warning about exposing my api key. So, I have changed my api key, placed it into a .env file, and use .gitignore to hide the .env for future commits. Hopefully that doesn't throw off any unusual erorrs besides the one that I am requesting help with.

**Comment by vonovak** [comment]
Hello and thanks for asking,
this is the same as https://github.com/expo/expo/issues/33248
Thank you 🙂
