### ISSUE TITLE
when I "Ctrl+D" , I Get This

### ISSUE THREAD

**Issue by randianb** [expo/expo#333]
Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://sw-va5.randianb.my-app.exp.direct:80 flg=0x10000000

**Comment by jesseruder** [comment]
Can you remove `~/.expo/android-apk-cache` and try again? This sometimes happen when the app download was corrupted

**Comment by terribleben** [comment]
Seems like this is dormant and maybe resolved - let me know if jesse's solution did not resolve the issue.
