### ISSUE TITLE
Swift Compile Error with Expo Barcode Scanner: 'ExpoModulesCore/EXBarcodeScannerInterface.h' File Not Found During Fastlane Build

### ISSUE THREAD

**Issue by Koustiii** [expo/expo#33313]
### Summary

I am encountering a Swift compile error while building my app using Fastlane. The error specifically occurs with the Expo Barcode Scanner (expo-barcode-scanner) module, which fails to compile due to a missing file:
ExpoModulesCore/EXBarcodeScannerInterface.h file not found.

This issue happens when running Fastlane during the iOS build process. The build fails with Exit status 65, and the error log points to BarCodeScannerExceptions.swift and BarCodeScannerModule.swift as problematic files.

I have already tried the following:

Ensuring that expo-barcode-scanner is up-to-date.
and
Attempting to build with EAS Build.
[runfastlane.txt](https://github.com/user-attachments/files/17949774/runfastlane.txt)

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

"expo-barcode-scanner": "^13.0.1",

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^52.0.7 => 52.0.7
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.10 => 0.19.13
    Expo Workflow: managed
```

### Reproducible demo

Can add later if needed

**Comment by joshh01** [comment]
same issue here, similar packages as well. are you actually able to run the project in a simulator / on a device? I can't get it to compile

**Comment by Koustiii** [comment]
Runs fine on Expo Go / Web, no issues there. Haven't tried anything else

**Comment by joshh01** [comment]
expo-barcode-scanner seems to be deprecated with expo >51, I removed the package and it compiles fine. I believe it migrated to expo-camera or something like that

**Comment by igigi** [comment]
it is exist

**Comment by IliasseWahbi** [comment]
> expo-barcode-scanner seems to be deprecated with expo >51, I removed the package and it compiles fine. I believe it migrated to expo-camera or something like that

Agree on this, as per Expo itself : https://docs.expo.dev/versions/v51.0.0/sdk/bar-code-scanner/

**Comment by juliana-hill** [comment]
The source says there are build failures: https://github.com/expo/expo/commit/ee4f30ef3b5fa567ad1bf94794197f7683fdd481
