### ISSUE TITLE
GLView.takeSnapshotAsync with integer-based textures

### ISSUE THREAD

**Issue by ksesong** [expo/expo#3334]
There are situations when the underlying framebuffer texture is integer-based (and not float-based), so the corresponding `readPixels` command would be like `glReadPixels(x, y, width, height, GL_RGBA_INTEGER, GL_UNSIGNED_INT, buffer);` instead of `glReadPixels(x, y, width, height, GL_RGBA, GL_UNSIGNED_BYTE, buffer);`.

It would be appreciated to have the option to choose the format and type of the `readPixels` command to accommodate for these situations, instead of having it [hardcoded like now](https://github.com/expo/expo/blob/master/ios/versioned-react-native/ABI32_0_0/EXGL/ABI32_0_0EXGL/ABI32_0_0EXGLContext.m#L197).

**Comment by AdamJNavarro** [comment]
Hey @ksesong,

It's best to suggest enhancements or feature requests on our [Canny Board](https://expo.canny.io/feature-requests). Would you mind making a post there about these GLView changes you want? I'm going to close this issue to avoid confusion.

Cheers,

Adam
