### ISSUE TITLE
Expo SDK 52 beta Doc typo

### ISSUE THREAD

**Issue by khuddite** [expo/expo#33355]
### Summary

Under the `Highlights` section in the doc, there is a typo - 
>It may not handle certain niche use cases that requires more control, since this is often requires trading off stability and ease of use even in common cases.

Expected: 
>It may not handle certain niche use cases that require more control, since this often requires trading off stability and ease of use even in common cases.

### Link to the related docs page

https://expo.dev/changelog/2024/10-24-sdk-52-beta

### Anything else?

I'd be happy to create a PR fixing the typo. But, unfortunately I don't see `Edit this page` button for this doc.

**Comment by amandeepmittal** [comment]
Thanks for catching it and sharing it here. Our changelog is behind a private repo, nonetheless, I'll follow up on this.
