### ISSUE TITLE
Uncaught error: java.net.SocketTimeoutException: failed to connect to /192.168.1.103 (port 19000) mac

### ISSUE THREAD

**Issue by shbhmbnsl1** [expo/expo#3336]
### Environment

 Expo CLI 2.7.0 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.1 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.7.0

App target: Android device

### Actual Behavior

I followed getting started guide from https://facebook.github.io/react-native/docs/getting-started to create and run my react-native app. Installed expo client app on my Android device (Android version 9). Ran expo init ProjectName and then expo start and tried to scan the barcode but I am receiving Uncaught Error: java.net.SocketTimeoutException: failed to connect to /192.168.1.103 (port 19000) after 10000ms. 

I made sure that I connect both my laptop and android device to the same wireless network but it didn't work. I also created hotspot from my android device and connected my laptop with it but then again the same error. 

I have tried everything which I found on internet like these issues also https://github.com/react-community/create-react-native-app/issues/144
https://github.com/react-community/create-react-native-app/issues/270

But nothing seems to be working for me. 

Created a topic on forum.expo.io as well 
https://forums.expo.io/t/uncaught-error-java-net-sockettimeoutexception-react-native-macbook/18617
But haven't received any response there too.

![whatsapp image 2019-01-26 at 7 56 19 pm 1](https://user-images.githubusercontent.com/20023071/51788504-abab6380-21a4-11e9-89bb-0d27dc9caea9.jpeg)
![whatsapp image 2019-01-26 at 7 56 19 pm](https://user-images.githubusercontent.com/20023071/51788506-ac43fa00-21a4-11e9-9295-128d6c494ef6.jpeg)

Please help!

**Comment by AdamJNavarro** [comment]
Hey @shbhmbnsl1,

I responded to your forum post and will be continuing providing support there! Will be closing this issue. See you on the forums!

Cheers,

Adam
