### ISSUE TITLE
After update to SDK 52 Android map not working correctly, markers loading and not loading 

### ISSUE THREAD

**Issue by edgarscr** [expo/expo#33373]
### Minimal reproducible example

https://github.com/edgarscr/minimal-error-expo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

open app sometimes dont load map, sometimes markers appear on map on first load but if u close and open again map load but dont display markers.

load only on first load too
        onMapReady={() => {
          console.log("handleMapReady");
        }}
        onMapLoaded={() => {
          console.log("handleMapLoaded");
        }}

### Environment

```text
npm install

npx expo start --clear --go
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by frankwongWO** [comment]
I had the same problem as you; when I reloaded the screen, the markers didn't show up.

**Comment by alanjhughes** [comment]
Hi @edgarscr - This minimal example is not minimal. I can't run the app. Also, react-native-maps is not maintained by expo so it would be probably be best if you could open an issue on their [repo](https://github.com/react-native-maps/react-native-maps).

**Comment by edgarscr** [comment]
> Hi @edgarscr - This minimal example is not minimal. I am unable to run the app. Also, react-native-maps is not maintained by expo so it would be probably be best if you could open an issue on their [repo](https://github.com/react-native-maps/react-native-maps).

Why do you say it is not minimal? The project is a simple file with its dependencies to run it, if it contains react native maps.
