### ISSUE TITLE
DocumentPicker always copies files to cache directory (on Android)

### ISSUE THREAD

**Issue by SvenMichaelKlose** [expo/expo#3338]
On Android I let users pick audio files with
`DocumentPicker.getDocumentAsync ({type: 'audio/*', copyToCacheDirectory: false});`.
However, files are copied to the cache directory anyway, rendering saved playlists useless when the cache has been cleared.

**Comment by evark** [comment]
It seems that always the file is copied to the cache directory...
I am using the latest expo 32

**Comment by AdamJNavarro** [comment]
Hey @SvenMichaelKlose or @evark,

Could either of you provide a small [MCVE](https://stackoverflow.com/help/mcve) that we can use to test this on our end?

**Comment by SvenMichaelKlose** [comment]
With pleasure. There you go... :)
[mcve-document-picker.tar.gz](https://github.com/expo/expo/files/2822074/mcve-document-picker.tar.gz)

**Comment by mczernek** [comment]
This issue is fixed and will be delivered in next release of ExpoSDK (33). Thanks for filing it and for your help!

**Comment by mczernek** [comment]
Fix will be delivered in next expo release.

**Comment by SvenMichaelKlose** [comment]
Thanks a million!
