### ISSUE TITLE
Support background location

### ISSUE THREAD

**Issue by slorber** [expo/expo#334]
Hi,

Currently the `Location.watchPositionAsync` is not triggered when the app is closed (at least it's not specified in the doc)

It could be nice to support background location. Not anything fancy but at least the ability to run a callback that sends that location to a backend server while the app is in background.

There are some RN and Cordova plugins providing this feature where some inspiration can be taken from:

https://github.com/mauron85/react-native-background-geolocation
https://github.com/pmwisdom/cordova-background-geolocation-services
https://github.com/transistorsoft/react-native-background-geolocation

**Comment by slorber** [comment]
Hmmm it seems there is already a "Canny" request for that:

[https://expo.canny.io/feature-requests/p/background-location-tracking](https://expo.canny.io/feature-requests/p/background-location-tracking)

**Comment by brentvatne** [comment]
Canny again is a good fit for this. This is something we are working on but we need to build some general infrastructure for background code execution first -- we are working on that part now.

**Comment by GeekRishabh** [comment]
@brentvatne Any ETA for this to support in upcoming Expo SDK?

**Comment by fxfactorial** [comment]
@GeekRishabh I am doing work towards that now

**Comment by terribleben** [comment]
It won't be in the upcoming SDK (26) and we don't have an ETA but it is on our roadmap somewhere.

**Comment by GeekRishabh** [comment]
@fxfactorial & @terribleben Thanks for the response. Please update me once it is developed.

**Comment by timhuff** [comment]
Any update on this? This feature is the only thing keeping me from going all in on expo.

**Comment by brentvatne** [comment]
@timhuff - unfortunately not, I'm really aching to get this feature in as well, we'll keep you all updated on https://expo.canny.io/feature-requests/p/background-tasks-support as we make progress

**Comment by timhuff** [comment]
@brentvatne Thanks for the prompt reply. I'll keep an eye out. I have a decent amount of experience in background location apps. Is this feature being held up because of a lack of manpower or is it a matter of app constraints holding it back? I'm not too familiar with how expo is set up - would it be possible for me to create a fork, add background tracking, and use that fork while we get the tests/PR taken care of? Or would I find myself spending weeks just trying to deal with expo-based limitations?

**Comment by brentvatne** [comment]
manpower, both in terms of engineering time and oversight of engineering time. we are quite small and are working on a lot of projects :)

**Comment by timhuff** [comment]
I gotcha. I guess my question is: is this something you feel a newcomer could tackle? I know the Objective-C/Java side of this. I would think the only thing I would need to learn is how to create the expo API. It's not something I'd be tackling for another month or two but I have an app that does background tracking (amongst other things) and I'd like to migrate it to expo. Seems if I move the tracking piece into expo, I'd just have to set up an API and then we'd be all set to use expo for the rest.

**Comment by yagudaev** [comment]
@timhuff @brentvatne that is exactly my thinking as well. I would think the Expo API is a thin layer on top of some React Native Native Code modules. There are a few to do background location. Is there a guide somewhere that explains how to wrap a module with expo?

**Comment by SahilRS200** [comment]
Is anybody using any workaround to track location in background while Expo team is hard at work to release it as a part of their feature?

**Comment by duckbrain** [comment]
@SahilRS200 We've been using https://github.com/transistorsoft/react-native-background-geolocation with success. They charge for an Android license, but it's been well worth it. You do have to Eject and use Expokit to use it though.

**Comment by kiamoz** [comment]
@SahilRS200 Dear Sahil, its really works on EXPO ? I have an expo template and I really need to background tracking ,.

**Comment by raskri** [comment]
So is it supported now? Out of the box Expo Style...?

**Comment by EvanBacon** [comment]
Moved https://github.com/expo/expo/pull/2338
