### ISSUE TITLE
[web][single] experimental baseUrl gets dropped from URL on refresh

### ISSUE THREAD

**Issue by samtsai** [expo/expo#33400]
### Minimal reproducible example

https://expo-base-url.fly.dev/baseurl/

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

```
 "web": {
      "bundler": "metro",
      "output": "single",
      "favicon": "./assets/images/favicon.png"
    },
    "experiments": {
      "typedRoutes": true,
      "baseUrl": "/baseurl"
    }
```

Publish a website in single mode and with a baseUrl set.
Setup relevant redirect rules for SPA so routes redirect to `index.html` and allow the router to update the path.
On initial load of the app, you can browse normally and access routes with correct URLs.

**Expected behavior**
On refresh the route should load with the correct path. The page loads but if you were to refresh again then the app would not load correctly because the baseUrl is missing.

**Actual behavior**
On refresh, the page loads but the path is replaced without the baseUrl included.

I've narrowed down where the `replace` is happening: https://github.com/expo/expo/blob/main/packages/expo-router/src/fork/useLinking.ts#L433

But I don't know when/how the `path` loses the `baseUrl`.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.1 - ~/Library/pnpm/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - ~/Library/pnpm/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.11 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: managed
```

**Comment by jgatto1** [comment]
any news?

**Comment by mrtncode** [comment]
> any news?

@jgatto1 The bug was already fixed. Just update the Expo Version :))
