### ISSUE TITLE
expo-screen-orientation : addOrientationChangeListener not working anymore on Web

### ISSUE THREAD

**Issue by djbuch** [expo/expo#33424]
### Minimal reproducible example

https://snack.expo.dev/@djbuch/expo-screen-orientation-bug

### What platform(s) does this occur on?

Web

### Where did you reproduce the issue?

on web

### Summary

l.default.addListener is not a function
TypeError: l.default.addListener is not a function
    at eval (expo-screen.orientation:3:3829)
    at e.addOrientationChangeListener (expo-screen.orientation:3:4160)
    at eval (components/useScreenOrientation.js:9)

### Environment

```text
The bug is even reproductible on snack
```

### Expo Doctor Diagnostics

```text
The bug is even reproductible on snack
```

**Comment by chrfalch** [comment]
This should be fixed by #33361 - could you check?
