### ISSUE TITLE
Expo Go 2.32.12 keeps stoping in Android Emulator

### ISSUE THREAD

**Issue by Zoz24** [expo/expo#33420]
### Minimal reproducible example

https://github.com/Zoz24/expo-bug-repo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in Expo Go

### Summary

Without any changes Expo Go suddenly started to stop working in the Android Emulator. 
I did some debugging and realized it is because the version upgrade of the Expo Go App.

I ran "npx expo start" then pressed "A" to enter Android emulator and did some comparative research. The emulator that has Expo Go 2.32.11 installed will work without any issues whereas emulator thath as Expo Go 2.32.12 will keep stopping without explicit reasons. 

"You can reproduce it by yourself by creating a project and following these steps"
```
  npx create-expo-app@latest StickerSmash
  cd StickerSmash
  npm install
  npx expo start
```
And Press A to enter the Android Emulator, something like this will show up, press Y:
`Expo Go 2.32.12 is recommended for SDK 52.0.0 (Pixel_8_API_34 is using 2.32.11). Learn more: https://docs.expo.dev/get-started/expo-go/#sdk-versions. `

Then the error is expected to occur

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.2.0 - /opt/homebrew/bin/node
      npm: 10.9.0 - /opt/homebrew/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0, 35.0.0
        System Images: android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.14 
      expo-router: ~4.0.9 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 10.1.1
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by dzusooo** [comment]
Same thing happening to me

**Comment by asrat-77** [comment]
> Facing same issue today. Things were ok till yesterday and without any change in code, I am unable to open in Android emulator or device.


The same issue is happening to me as well.

**Comment by AdamBathoriKiss** [comment]
Same here after today's update.

**Comment by ImmanuelKee** [comment]
Same

**Comment by scriptmintsolution** [comment]
Now the recommended version is showing 2.32.11 and I am able to run my project on Android Emulator.
