### ISSUE TITLE
expo-build-properties useFramework setting throws linking error when comiling

### ISSUE THREAD

**Issue by MoritzWallner** [expo/expo#33423]
### Minimal reproducible example

https://github.com/MoritzWallner/expo-build-properties-useFramework

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

# Description
I use `expo-build-properties` with the following setting: `useFramework: "dynamic`. When running `npx expo prebuild --clean` and afterwards `npx expo run:ios` the app does not compile. The first command works fine but running the app does not work on iOS. This is the error message I am getting:

```
Compiling react-native Pods/React-defaultsnativemodule » React_defaultsnativemodule_vers.c
› Compiling react-native Pods/React-defaultsnativemodule » DefaultTurboModules.cpp
› Compiling react-native Pods/React-defaultsnativemodule » React-defaultsnativemodule-dummy.m
› Signing   react-native Pods/React-RuntimeApple » React_RuntimeApple.framework
› Creating  react-native Pods/React-RuntimeApple » React_RuntimeApple.framework
› Linking   react-native-reanimated Pods/RNReanimated » RNReanimated
❌  Undefined symbols for architecture x86_64
┌─ Symbol: facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&, std::__1::function<bool (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>)
└─ Referenced from: reanimated::NativeReanimatedModule::performOperations() in NativeReanimatedModule.o


❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)



› 3 error(s), and 2 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
```
When removing the useFramework option the app compiles just fine.

# Why do I need the `useFramework: "dynamic"` option?
I need to use the `useFramework` setting to integrate this library [https://developers.tapkey.io/mobile/ios/getting_started/#adding-the-tapkey-mobile-sdk-via-cocoapods](https://developers.tapkey.io/mobile/ios/getting_started/#adding-the-tapkey-mobile-sdk-via-cocoapods), as it requires setting the `useFramework!` option in the Podfile. 

To reproduce this error run `npx expo prebuild --clean` and afterwards `npx expo run:ios` in the minimal reproducible demo.

# How to reproduce
The error also occurs in a fresh expo app created using `npx create-expo-app@latest`.

To create the minimal reproducible demo I did the following:
1. create a new app using `npx create-expo-app@latest`
2. install `expo-build-properties`
3. set `useFramework: "dynamic"`
4. run `npx expo prebuild --clean`
5. run `npx expo run:ios`

# What I already tried
Various sources online suggest to add the following to my Podfile (which is not ideal as I want to be using the managed workflow and build with EAS).

```
pre_install do |installer|
 installer.pod_targets.each do |pod|
   if pod.name.eql?('RNReanimated')
     def pod.build_type
       Pod::BuildType.static_library
     end
   end
  end
end
```

However this does not work. Removing `useFramework: dynamic` is also not an option for me as I need to use the library mentioned above.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.8.2 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.12.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.14 
      expo-router: ~4.0.9 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 12.5.4
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by brentvatne** [comment]
it looks like this issue is covered here: https://github.com/software-mansion/react-native-screens/issues/1963
