### ISSUE TITLE
DocumentPicker is not working as expected

### ISSUE THREAD

**Issue by debotos** [expo/expo#3343]
### Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
      Shell: 4.4.19
    Binaries:
      Node: 10.13.0 
      Yarn: 1.12.3
      npm: 6.5.0
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.6.14

### Steps to Reproduce

1. Sample code trying to run, https://snack.expo.io/HkuSxz6Sf

### Actual Behavior

1. On a real device(not at snack) my Expo **client app** reload/**restart** when i select a file via **DocumentPicker**!
2. It doesn't provide an error, it just restarts again!

**Comment by sjchmiela** [comment]
Hey, @debotos!

Could you please provide some details about the device you use to reproduce the issue (like is it an Android or iOS, what system version, etc.)? 🙂

**Comment by debotos** [comment]
Hey @sjchmiela 

First of thanks for the response! :slightly_smiling_face: 

Facing this issue on my **Android – 5.0 Lollipop** phone (**Meizu M3s**) with **expo client app**

**Comment by dsokal** [comment]
Hello @debotos,
could you please confirm it's still an issue for you? I ran Expo Client app on Android emulator with Android 5.0 and the Snack you referenced works just fine - the app doesn't crash after selecting a file with Document Picker.

Could you please provide us with some logs if it still doesn't work for you?

**Comment by debotos** [comment]
Hey @dsokal,

This error **only occurs** on '**Meizu m3s**' phone.
I also tested on iPhone 6s, Samsung Galaxy phone. In there DocumentPicker works perfectly.

**Comment by dsokal** [comment]
Unfortunately, we don't have such a phone at our office and it would be hard to get one as it's pretty exotic. Could you please provide us with crash logs? You can find them in Android Studio once you connect your phone with a cable to your computer.

**Comment by dsokal** [comment]
I'm closing this issue for now (due to inactivity).
