### ISSUE TITLE
process.env.EXPO_OS is not defined

### ISSUE THREAD

**Issue by shuo-hiwintech** [expo/expo#33440]
### Summary

When I use expo-imgae in a React Native Cli project, the console reports me a warning.

Warning Screenshot：
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/3235a964-514c-4a65-b846-3ccd64aadf43">

### What platform(s) does this occur on?

Android, iOS

### SDK Version

52.0.0

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 3.6.4 - /usr/local/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
      Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0 => 52.0.14 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
    npmGlobalPackages:
      eas-cli: 10.0.2
      expo-cli: 6.3.0
    Expo Workflow: bare
```

### Minimal reproducible example

https://github.com/shuo-hiwintech/AwesomeProject

1. npx install-expo-modules@latest
2. npx expo install expo-image
3. With expo-image, the console reports an error: (NOBRIDGE) WARN  The global process.env.EXPO_OS is not defined. This should be inlined by babel-preset-expo during  transformation. [Component Stack]

**Comment by brentvatne** [comment]
hi @shuo-hiwintech - you can ignore this warning if you like, or silence it by setting `process.env.EXPO_OS = Platform.OS` (`Platform` here would be imported from react-native). however, we recommend that you use babel-preset-expo along with expo modules: https://docs.expo.dev/bare/installing-expo-modules/#configure-expo-cli-for-bundling-on-android-and-ios

**Comment by MariuzM** [comment]
But is there a need to have this warning at all? i think its just clutters terminal with the warnings that does not help us?

**Comment by shuo-hiwintech** [comment]
import {AppRegistry, Platform} from 'react-native';

process.env.EXPO_OS = Platform.OS;

import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);

When you do this, the terminal will still prompt:
The global process.env.EXPO_OS is not defined. This should be inlined by babel-preset-expo during transformation.

I'm a React Native Cli project and I'm not using the expo cli.

**Comment by jounisuo** [comment]
Just came to comment that you can also get this error, even when using babel-preset-expo, if you are on an older project which is also using babel-plugin-inline-dotenv, for me I could resolve the issue by dropping inline-dotenv from the plugins.

**Comment by ChristopherBanas** [comment]
+1. I still get this warning even after following the docs.

**Comment by wstevo4891** [comment]
+1
I am using `presets: ['babel-preset-expo']` in my babel.config.js and I'm still getting this warning when running jest. I tried setting `process.env.EXPO_OS = Platform.OS` in jest.setup.js but I still receive the warning.

**Comment by VGerris** [comment]
same here,   presets: ['babel-preset-expo'], is set and the message is printed. Why is this closed ? And why are things suggested that do not work ?

**Comment by mksglu** [comment]
+1

**Comment by zstuder25** [comment]
+1

**Comment by VGerris** [comment]
Can this be re-opened and investigated ? thank you

**Comment by aliceni81** [comment]
+1

**Comment by AJGeel** [comment]
+1

**Comment by MatiPendino** [comment]
+1

**Comment by roni-castro-shipt** [comment]
To suppress this warning in a React Native CLI project, it needs to add `process.env.EXPO_OS = Platform.OS;` to the **App** file instead of the **index** file.

Ideally, this warning wouldn't appear in a non-Expo app.

**Comment by DzmitryITGlue** [comment]
@roni-castro-shipt The file where you have to add `process.env.EXPO_OS = Platform.OS;`  depends on your codebase and where you use expo first time in js runtime. The correct way to figure out where add that line is to look into error in debug console, e.g. in my app console looks like this:

![Image](https://github.com/user-attachments/assets/83e603e2-3d44-4177-a781-7a24fcca1ec4)
So in my case target file is `en.ts`.

**Comment by KristijanKocev** [comment]
> [@roni-castro-shipt](https://github.com/roni-castro-shipt) The file where you have to add `process.env.EXPO_OS = Platform.OS;` depends on your codebase and where you use expo first time in js runtime. The correct way to figure out where add that line is to look into error in debug console, e.g. in my app console looks like this:
> 
> ![Image](https://github.com/user-attachments/assets/83e603e2-3d44-4177-a781-7a24fcca1ec4) So in my case target file is `en.ts`.

Unfortunately nothing changed for me :( For me its an image component i have where expo image but i can't seem to get rid of the warning.

**Comment by Jokotoye18** [comment]
+1

**Comment by SimonMueller** [comment]
+1

**Comment by brentvatne** [comment]
hi there!

- if you are seeing this warning it would be because you are not using babel-preset-expo (as the warning itself suggests) or expo cli. see: https://docs.expo.dev/bare/installing-expo-modules/#configure-expo-cli-for-bundling-on-android-and-ios
- as @jounisuo pointed out, you may also see this if you are using a library like babel-plugin-inline-dotenv, which seems to be clobbering the environment variables that expo cli will set. we recommend using expo cli's own environment variable support instead: https://docs.expo.dev/guides/environment-variables/
