### ISSUE TITLE
"expo start" behaving differently in different projects & linking inconsistencies

### ISSUE THREAD

**Issue by ax-vasquez** [expo/expo#33454]
### Summary

I recently created https://github.com/expo/expo/issues/33421 which was closed out as "expected behavior", but I think I may have phrased the issue poorly.

The main issue is that using `expo start` seems to be defaulting to different behavior than the default. Beyond that, if I run Expo with the `--go` command, it behaves differently when linking than it does on the starter app.

In my project, when I remove `--dev-client` from the start command, it still seems to start the Expo Bundler in development mode. This does not happen if I create a new Expo project. I got a bit mixed up since we have been using `--dev-client` for a long time and the QR code has always brought us directly to Expo Go. I'm not sure when it stopped working since we had assumed it was still working and only noticed the issue during setup for an additional developer.

## Replication steps

This issue is best understood by comparing the "broken" and "working" projects. My project (the "broken" one). Using the provided repo:
1. Run `yarn` to install dependencies
2. Run `yarn start` (which now uses `expo start` without any flags)
3. Observe the application is started in "development mode" (this is not how the default starter app works)
4. Press `s` to switch to "Expo Go" > scan the QR code
5. Observe that you ARE NOT brought into Expo Go, but are instead forced to navigate through your device browser to get to Expo Go indirectly
   * This should be the same mode the starter app is running in - _why does my app force me to go through the device browser, while the starter app does not?_

The "working" version of `expo start` without a flag:
1. Create a new test Expo app using `npx create-expo-app@latest SomeProject`
7. Start the application using the `start` script (which uses `expo start` without any flags set)
8. Scan the QR code > **observe that the QR code will open the app in Expo Go**

### Inconsistent app linking

* If you set the command to `--go` for the "broken" repo, you can link it up, **but it behaves differently than the linking behavior in the starter ("working") app**
   * In the "broken" project, you have to go through the device browser to get to Expo Go
   * In the "working" project, scanning the QR code opens Expo Go directly

I'm willing to accept there may be something I am missing here, but I am not sure what that might be. As far as I can tell, nothing we changed should have broken the ability to link directly to Expo Go using a QR code. As of now, we can only get to it through the device browser for our app.

### What platform(s) does this occur on?

iOS

### SDK Version

52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
      Yarn: 4.1.1 - ~/.nvm/versions/node/v18.20.4/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/ax-vasquez/expo-booboo

**Comment by ax-vasquez** [comment]
I truly hope this does not get closed out as "expected behavior" since the same command on the same CLI is behaving differently in different projects - both can't be right, I assume?

**Comment by brentvatne** [comment]
hey @ax-vasquez - did you recently upgrade from a much older SDK version? the behavior you are describing has been in place for years at this point

**Comment by ax-vasquez** [comment]
@brentvatne I did recently upgrade, but from version 51, so it wasn't that old of a project. The project itself was only started up earlier this summer.

**Comment by brentvatne** [comment]
the expected behavior is as follows:

- if you **do not** have expo-dev-client installed, we assume that you will always be launching into expo go.
- if you **do** have expo-dev-client installed, it's rare that you will want to launch into expo go. so the qr code in the terminal will point you to an interstitial page that allows you to select which context you'd like to open it in. that said, maybe we can get rid of this interstitial. i do think it's still possible that folks might accidentally switch to expo go in in expo cli in this mode, and so the interstitial can be somewhat useful in that case, but that's about it. the interstitial was built before we had a toggle for expo go / dev client in expo cli.

also, note that if you are signed in to expo go or your dev build on your device, you don't need to scan a qr code. just open up the app and your running apps on the same expo account will be automatically listed in the ui

**Comment by ax-vasquez** [comment]
Ahhhh that would explain my confusion. I hadn't realized expo-dev-client was altering how that logic worked. I must have added it after I had already linked things up to my installation of Expo Go.

For now, we don't need expo-dev-client, so I'll try removing that and see if it gets us back to where we were before. I assume that's more than likely the issue here, but I'll confirm later once I know for sure!

**Comment by brentvatne** [comment]
fwiw, we strongly recommend using development builds for real-world apps: https://expo.fyi/expo-go-usage

**Comment by tunino91** [comment]
@ax-vasquez 
Encountered same issue with QR code after installing `expo-dev-client`. No need to remove `expo-dev-client` to go back, just press `s` to get the QR code working as before. 

![Image](https://github.com/user-attachments/assets/b4a6221f-1d78-44f4-9628-174de5cb927f)

**Comment by brandonaaskov** [comment]
@tunino91 thank you so much, you saved me a ton of time. It wasn't immediately obvious to me, but that was absolutely the issue. Once you get your project configured to build natively, you have to be cognizant about this toggle switch.
