### ISSUE TITLE
where to put my icon picture for expo to use instead of default one?

### ISSUE THREAD

**Issue by blueturtle13g** [expo/expo#3347]
according to expo documentation:

> The most straightforward way to provide an icon for your app is to provide the icon key in app.json

so I added my own icon to the assets folder where expo's default icons are, and modified app.json to point to my icon:

```
  "expo": {
     ...
     "icon": "./assets/myIcon.png"
  }
```
but when launching I get this error from expo:

> Field: icon - cannot access file at './assets/myIcon.png

what am I missing? where should I put my Icon picture?

**Comment by AdamJNavarro** [comment]
Hey @blueturtle13g,

This type of questions are better suited for our forums. https://forums.expo.io/ Can you please make a post and I'll be happy to assist there! Closing this issue as well.

Cheers,

Adam
