### ISSUE TITLE
CLI: The development server returned error code 404

### ISSUE THREAD

**Issue by 1cedsoda** [expo/expo#33493]
### Summary

I am using `pnpm expo start` to run my project.
It works just fine on iOS, but when I run it on an android emulator with Expo Go, it return an error.
Building an APK file and installing it works also.
So I suspect it's a metro bundler/CLI problem.

CLI log:
```› Opening on Android...
› Opening exp://172.18.12.240:8081 on Pixel_3a_API_34_extension_level_7_arm64-v8a
› Press ? │ show all commands
```
It doesn't bundle the JS for android.

In Expo Go I get a red screen:
`The development server returned error code 404`

My setup:
I followed the setup here https://docs.expo.dev/workflow/android-studio-emulator/ for macos
I am running a MacBook with M2 chip.
My @expo/cli is version 0.22.3 (latest)

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 33, 34
        Build Tools: 30.0.3, 34.0.0
        System Images: android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^11.0.14 => 11.0.14 
      expo: ^51.0.39 => 51.0.39 
    npmGlobalPackages:
      eas-cli: 7.0.0
      expo-cli: 6.3.10
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
hi there! try using sdk 52 and let us know if the issue persists. if it does, please share a minimal reproducible example. thanks!

**Comment by rizwan-gill** [comment]
I'm facing an issue with Android. using the "expo": "^52.0.0", in bare. how to fix this any solution.

**Comment by rizwan-gill** [comment]
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
====>  /Users/xxx/xxx/xxx/xxx/client/mobile
✔ Check for issues with the Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match the versions required by the installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

**Comment by rizwan-gill** [comment]
@brentvatne 
can you please check this issue
https://github.com/expo/expo/issues/33602

**Comment by 1cedsoda** [comment]
I tried upgrading to SDK 52 and am now facing another issue #33650...
We'll see when the other one is resolved.

**Comment by focux** [comment]
@1cedsoda how were you able to fix this?

**Comment by mosleim** [comment]
@1cedsoda is your preblem fixed? i get this error too now.

**Comment by thomasdotdev** [comment]
In my case was changing the `MainApplication.kt` and `AppDelegate.mm` to point to the correct position:
```diff
- override fun getJSMainModuleName(): String = "index"
+ override fun getJSMainModuleName(): String = ".expo/.virtual-metro-entry"
``` 

```diff
{
#if DEBUG
-  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
+  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@".expo/.virtual-metro-entry"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}
```
