### ISSUE TITLE
[docs] DOM Components: How exactly does this work?

### ISSUE THREAD

**Issue by puopg** [expo/expo#33492]
### Summary

I read through the documentation around DOM Components and I THINK I see how it works under the hood, but I'm not 100% sure if I understand it correctly.

As a simple scenario, lets say I had a Button component that was a DOM Component. If I use that button all over the place, am I understanding this right that each button is basically a small WebView? So scattered all around the page there are basically iframes?

And finally, in your teams testing, obviously performance isnt as good as native as expected, but does the creation of that many Webviews tend to actually be a significant problem? Kinda curious as to when this is an issue, like if I had a list of 200 rows each with 2 buttons on em, and each button was a WebView, im looking at what 400 Webviews?

Thanks for the clarification and please let me know if this is best asked elsewhere!

### Link to the related docs page

https://docs.expo.dev/guides/dom-components/

**Comment by chriszs** [comment]
Non-official, community answer:

> If I use that button all over the place, am I understanding this right that each button is basically a small WebView? So scattered all around the page there are basically iframes?

Correct.

> like if I had a list of 200 rows each with 2 buttons on em, and each button was a WebView, im looking at what 400 Webviews

I believe so, yes. That does seem like it'd have a performance impact.

I have a screen with 4 DOM Components, and can see 4 webviews in Safari's debug menu when testing on iOS.

**Comment by puopg** [comment]
Much appreciated, thanks!
