### ISSUE TITLE
[React Canary] TypeError: Cannot read property 'actQueue' of undefined

### ISSUE THREAD

**Issue by chriszs** [expo/expo#33498]
### Minimal reproducible example

https://github.com/chriszs/test-expo-app/compare/main...demonstrate-react-canary-type-error

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When I turn on experimental React Canary support by the using the `experiments.reactCanary` flag in `app.json`, I get two log lines that look like ` ERROR  TypeError: Cannot read property 'actQueue' of undefined, js engine: hermes` and nothing renders. This is without new architecture in an app freshly scaffolded with `create-expo-app`. With new architecture I get a similar error but `actQueue` is replaced by the letter `T`.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - ~/.asdf/installs/nodejs/22.11.0/bin/node
      npm: 10.9.2 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2024.11.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.17 => 52.0.17 
      expo-router: ~4.0.11 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, ios, android, plugins, androidStatusBar. 


One or more checks failed, indicating possible issues with the project.
```

**Comment by chriszs** [comment]
This presumably comes from somewhere in this general area: https://github.com/expo/expo/blob/e52455b27db6ab0a6666756ee50ed8a854f2a30a/packages/%40expo/cli/static/canary-full/react/cjs/react.development.js#L2459-L2472

**Comment by chriszs** [comment]
I realize this is experimental, but the official Twitter account RTed a tweet promoting it: https://x.com/Baconbrix/status/1864785257297305833

**Comment by EvanBacon** [comment]
The `reactCanary` flag is experimental and meant for testing React Server Components. Only use it if you're avidly familiar with the internals of `react`.

Most issues can be fixed by simply updating the static vendor from facebook/react. React 19 support will likely be enabled by default in the next version of expo, depends on react-native.
