### ISSUE TITLE
Intercom support

### ISSUE THREAD

**Issue by slorber** [expo/expo#335]
Just opening this issue to discuss Intercom support in Expo without detaching, as it's a quite common dependency and it can be annoying to detach just to add Intercom support :)

This has already been discussed on [Slack](https://expo-developers.slack.com/archives/C464RMZJL/p1498238920156048)

brent:

> @slorber - typically we want to provide things that are free, have at least some kind of free plan, or in the case of segment, is a good option to use instead of including many other native sdks
> we considered intercom, and i reached out to them to see if they would share their JS source so i could rebuild the client w/ react-native views, but they were not interested at the time
> what are the approximate sizes (bytes) of the intercom sdks on ios & android?

Also this issue can be used to see how many people using Expo are interested by Intercom support, as it can help Expo team to reconsider adding the SDKs or Intercom to consider developing lightweight UIs for ReactNative users. 

Note that as a workaround it's possible to integrate [Intercom in a webview](https://github.com/donovantc/react-native-intercom-webview) in a non-detached Expo app but it does not provide a very good UX.

**Comment by slorber** [comment]
About the SDK sizes, I'm not totally sure how this can be measured so if anyone knows please tell ;)

**Comment by slorber** [comment]
I created a "Canny" issue: https://expo.canny.io/feature-requests/p/add-intercom-support

**Comment by brentvatne** [comment]
Canny issue is perfect for this, thanks for opening that :)

**Comment by tomislavhren** [comment]
Any updates regarding this ? Will there be intercom expo support in the near future ?

**Comment by emilahmed** [comment]
Any updates on this?

**Comment by iagorm** [comment]
Have Intercom SDK in Expo would be a perfect choice to have a support environment. +1

**Comment by ericc59** [comment]
+1

**Comment by LRNZ09** [comment]
This would be very helpful!

**Comment by nirpeled** [comment]
Any chance that Intercom will be integrated anytime soon? How can I help? 🤓

**Comment by brentvatne** [comment]
we're working on some stuff that will make this possible eventually but it's still a number of months away

**Comment by YoshiYo** [comment]
Nice news @brentvatne 🚀
Our team wait it so much !

**Comment by bobtista** [comment]
Any updates here? How can I help? @brentvatne

**Comment by almakary** [comment]
@brentvatne, Any updates on this?

**Comment by brentvatne** [comment]
sadly no update on doing this in managed workflow, you'd need to use bare workflow for it
