### ISSUE TITLE
[SDK52] Cannot use custom fonts in DOM Components

### ISSUE THREAD

**Issue by StefSchalks** [expo/expo#33502]
### Minimal reproducible example

https://github.com/StefSchalks/expo-repro-dom-component-fonts

### What platform(s) does this occur on?

Android, Web

### Where did you reproduce the issue?

in Expo Go

### Summary

I created a new project with the default template.
Then I tried to import a custom font in my Expo DOM component using the code below.
However, the font of the text doesn't change (also not when running on web, but I haven't been able to test on iOS).

I've tried using local fonts using `expo-font` in a different project but that isn't included in the minimal reproducible example. Basically I just can't get the custom font to work. 

style.css
```css
@import url('https://fonts.googleapis.com/css2?family=Spline+Sans:wght@300..700&display=swap');

h1 {
    color: white;
    font-family: "Spline Sans";
}
```

my-dom.tsx
```
"use dom"
import './style.css'

export default function MyDom({}: { dom: import('expo/dom').DOMProps }) {
    return (
        <div>
            <h1>Test Text</h1>
            <h1>I know it's pretty amazing</h1>
        </div>
    )
}
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      expo: ~52.0.17 => 52.0.17
      expo-router: ~4.0.11 => 4.0.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK
```

**Comment by chriszs** [comment]
I'm in the same place, in terms of wanting to know the best way to use custom fonts in DOM Components and being a little surprised there isn't guidance. What I'm doing now: loading the fonts as assets (separately from loading them natively with the `expo-fonts` config plugin and the `useFonts` hook I have in my root layout for web) and then inserting CSS directives into inline stylesheets in my `use dom` components. This is so I can refer to them in the `.css` stylesheets I'm loading for those components. But I'd rather not load custom fonts three different ways in the same project.

**Comment by StefSchalks** [comment]
Hi @chriszs,
Thanks for your detailed description. It seems that you've found a way to get it working. However, I'm not really sure how to get it working on my end.

You mention the local assets and how you refer to that using inline stylesheets. 

There is a font present in the `asset/fonts` folder of the project called `SpaceMono-Regular.ttf` (it's default in the expo default template)

I decided to change my font implementation to this (tried both url() and local()) in my `main.css` file
```css
@font-face {
    font-family: "Space Mono";
    src: url('../assets/fonts/SpaceMono-Regular.ttf');
}
```
and
```css
@font-face {
    font-family: "Space Mono";
    src: local('../assets/fonts/SpaceMono-Regular.ttf');
}
```

Using `url()`, it gives the error: `Importing local resources in CSS is not supported yet.` and when using `local()`, it doesn't show up the correct font but it shows the default one.

My dom component looks like this:
```jsx
"use dom"
import './style.css'

export default function MyDom({}: { dom: import('expo/dom').DOMProps }) {
    return (
        <div>
            <h1>custom fonts such as this one</h1>
        </div>
    )
}
```

and I use the dom component like this:
```jsx
<MyDom 
  dom={{
    matchContents: true,
    style: { height: 500 },
  }}
/>
```

Could you share the implementation that works for you?

**Comment by chriszs** [comment]
The first thing I'd try is the [useFonts](https://docs.expo.dev/develop/user-interface/fonts/#with-usefonts-hook) hook.

What I'm doing is more like:

```jsx
import SpaceMono from '../../../assets/fonts/SpaceMono-Regular.ttf';

const style = `
<style>
  @font-face {
    font-display: swap;
    font-family: spacemono;
    font-style: normal;
    font-weight: 400;
    src: url(${SpaceMono}) format('truetype');
  }
</style>
`;

export default function MyDom({}: { dom: import('expo/dom').DOMProps }) {
  return (
    <div
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{__html: style}}
    />
 )
}
```

And I'm [baking in the asset](https://docs.expo.dev/develop/user-interface/assets/) files using prebuild in `app.config.ts`:
```js
[
      'expo-asset',
      {
        assets: fonts,
      },
    ],
```

I'm also prefixing the path with `window.location.origin` for development because I'm setting a different base URL than the localhost origin and the relative path for assets doesn't work, though I may be able to [use](https://docs.expo.dev/guides/dom-components/#public-assets) `process.env.EXPO_BASE_URL`. There's a note there that "public assets are experimental and don't work with Expo Updates," which seems to be a reference to the shortcut of putting assets in a public folder. I think using the Expo Asset system this way is okay, though. I just assume I'll have to do a native release when fonts change.

**Comment by StefSchalks** [comment]
@chriszs thanks for the reaction. When I'm using the `useFonts` hook, it doesn't work at all. It's just the default font, but when I open it on the website (`react-native-web`, the font does show up correctly (see mobile and web screenshots for reference)

The `SpaceMono` font is imported using the `useFonts` hook and works in Expo Go in the first text (native) but not on the second text (dom component). When opening the generated website, however, both texts show up with the right font.

```js
const [loaded] = useFonts({
    SpaceMono: require('../assets/fonts/SpaceMono-Regular.ttf'),
  });
```

What's not really clear to me about your comments is if you got it working already or are also still searching for a way to get it working. 

> Web
![Screenshot 2024-12-08 131143](https://github.com/user-attachments/assets/31a716e4-f2c7-40b5-b7a9-1eb0faec7fcc)

> Mobile
![Screenshot_20241208_131146_Expo Go](https://github.com/user-attachments/assets/665fb686-da37-4e3a-9e49-017362b375ad)

**Comment by chriszs** [comment]
@StefSchalks What happens if you duplicate the `useFonts` hook in the DOM Component itself?

My approach does seem to be working for my use case, but I haven't thoroughly tested it in a production build.

**Comment by StefSchalks** [comment]
@chriszs Didn't even know that was possible! 😅
Seems to be working for now. Thanks for the help!

**Comment by jerrickhakim** [comment]
Feels hacks, but it this worked in my use case.
```"use dom";

import { LineChart, XAxis, YAxis, CartesianGrid, Tooltip, Line, ResponsiveContainer } from "recharts";

const style = `
  @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap');
`;

export default function MyDom({ dom, data }: { dom: import("expo/dom").DOMProps; data: Array<{ date: string; value: number }> }) {
  return (
    <div style={{ width: "100%", height: 200, overflow: "hidden", padding: 10, fontFamily: "Roboto" }}>
      <style
        dangerouslySetInnerHTML={{
          __html: style,
        }}
      ></style>
      <ResponsiveContainer width="100%" height="100%">
        <LineChart data={data} margin={{ top: 10, right: 5, left: 10, bottom: 0 }}>
          {/* <CartesianGrid strokeDasharray="3 3" opacity={0.2} /> */}
          <XAxis dataKey="date" stroke="#6EC387" tickMargin={10} />
          {/* <YAxis stroke="#6EC387" tickMargin={10} /> */}
          <Tooltip
            contentStyle={{
              backgroundColor: "rgba(0, 0, 0, 0.8)",
              border: "none",
              borderRadius: 4,
              color: "#fff",
            }}
          />
          <Line
            type="monotone"
            dataKey="value"
            stroke="#4A9ACB"
            strokeWidth={2}
            dot={{ fill: "#4A9ACB", strokeWidth: 2 }}
            activeDot={{ r: 6 }}
            animationDuration={1500}
          />
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
}
```

**Comment by badalsaibo** [comment]
@StefSchalks Can you please share an example using the `useFonts` hook?

**Comment by temlabs** [comment]
> [@StefSchalks](https://github.com/StefSchalks) Can you please share an example using the `useFonts` hook?

Second this, please!

**Comment by StefSchalks** [comment]
@badalsaibo @temlabs 

Of course!
So here's a basic example of what should work with the `useFonts` hook:

This is my component:
```js
'use dom';
import '../../../../global.css';
import loadFonts from 'utils/load-fonts';

export default function MyDomComponent({ data }) {
  const [loaded] = loadFonts();

  return (
    <div className="w-full flex flex-col gap-4">
      <span>Your amazing component</span>
    </div>
  );
}
```

And I have this other file set up so I can use it for both native as web:

```js
import { useFonts } from "expo-font";

const loadFonts = () => {
  return useFonts({
    "Onest-Thin": require("../assets/fonts/Onest-Thin.ttf"),
    "Onest-ExtraLight": require("../assets/fonts/Onest-ExtraLight.ttf"),
    "Onest-Light": require("../assets/fonts/Onest-Light.ttf"),
    "Onest-Regular": require("../assets/fonts/Onest-Regular.ttf"),
    "Onest-Medium": require("../assets/fonts/Onest-Medium.ttf"),
    "Onest-SemiBold": require("../assets/fonts/Onest-SemiBold.ttf"),
    "Onest-Bold": require("../assets/fonts/Onest-Bold.ttf"),
    "Onest-ExtraBold": require("../assets/fonts/Onest-ExtraBold.ttf"),
    "Onest-Black": require("../assets/fonts/Onest-Black.ttf"),
  });
};

export default loadFonts;
```

And that should work.

I just liked to import my fonts in a seperate place so it can be reused easily if needed for multiple components, but of course, you can also do something like this and do it directly in the component itself (untested):

```js
'use dom';
import '../../../../global.css';
import { useFonts } from "expo-font";

export default function TopTracksPreview({ data }) {
  const [loaded] = useFonts({
    "Onest-Thin": require("../assets/fonts/Onest-Thin.ttf"),
    "Onest-ExtraLight": require("../assets/fonts/Onest-ExtraLight.ttf"),
    "Onest-Light": require("../assets/fonts/Onest-Light.ttf"),
    "Onest-Regular": require("../assets/fonts/Onest-Regular.ttf"),
    "Onest-Medium": require("../assets/fonts/Onest-Medium.ttf"),
    "Onest-SemiBold": require("../assets/fonts/Onest-SemiBold.ttf"),
    "Onest-Bold": require("../assets/fonts/Onest-Bold.ttf"),
    "Onest-ExtraBold": require("../assets/fonts/Onest-ExtraBold.ttf"),
    "Onest-Black": require("../assets/fonts/Onest-Black.ttf"),
  });

  return (
    <div className="w-full flex flex-col gap-4">
      <span>Your amazing component</span>
    </div>
  );
}
```

And then you should still use your fonts your own way, whether that's with tailwind or custom css, that's a thing on it's own, but this is how you can import your fonts and use them in a DOM component.

Hope it's helpful!
