### ISSUE TITLE
Whitish Screen

### ISSUE THREAD

**Issue by ebuberoderick** [expo/expo#33521]
### Minimal reproducible example

https://github.com/ebuberoderick/my-expo-app

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

while navigating between screens some some screen appear whitish this only happen on android 

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 21.5.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~52.0.17 => 52.0.17
      expo-router: ~4.0.11 => 4.0.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
your repro includes a bunch of unrelated code, and the issue is not clearly explained. please remove any unrelated code and share a video along with an accompanying explanation
