### ISSUE TITLE
ERROR index.js: [BABEL]:'expo/config'  Cannot find in module of Require stack.

### ISSUE THREAD

**Issue by shelendrasingh** [expo/expo#33528]
### Summary

Why:
I am using React Native version upgrade 0.72.3 to latest Version of React native(0.76.3.0) with latest babel Config.

How:
I have updated the React native version (0.76.3.0) with latest babel config version (12.0.2) but I am getting the error in 'expo/config module.

Test Plan:
We are using React Native Cli with preset expo in our babel Config.

Babel.config.js : Snippet

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin']
  };
};

### What platform(s) does this occur on?

iOS

### SDK Version

0.76.3

### Environment

```text
iOS
```

### Minimal reproducible example

We are using React Native Cli with preset expo in our babel Config.

Babel.config.js : Snippet

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin']
  };
};

**Comment by byCedric** [comment]
Hi @shelendrasingh! The `expo` package is required if you want to use `babel-preset-expo`. Unfortunately, without a repro I can't do much more than mentioning that. Hope it helps!
