### ISSUE TITLE
MediaLibrary.saveToLibraryAsync throw This file type is not supported yet for any video file

### ISSUE THREAD

**Issue by zallesov** [expo/expo#33537]
### Minimal reproducible example

https://gist.github.com/zallesov/18bde4152ab200e87d12e9bbbb90f5bc

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

When calling `MediaLibrary.saveToLibraryAsync` with an mp4 file path it throws an error  `This file type is not supported yet`
The file uses h.264 codec. This started to happen after upgrading to expo version 52. Only IOS. Android works fine 

```
import * as MediaLibrary from "expo-media-library";
const url = "file:///Users/[username]/Downloads/bigbuckbunny.mp4"
await MediaLibrary.saveToLibraryAsync(url);
// throws an error `This file type is not supported yet`
```
The same error is thrown for `mov` and other video formats too.

We've tested with files downloaded from here
https://test-videos.co.uk/bigbuckbunny/mp4-h264
https://toolsfairy.com/tools/video-test/sample-mov-files

- The issue is reproduceable in the Iphone simulator as well as on a device.
- However, calling `Sharing.shareAsync` and selecting `Save` option adds the file to the Media library.
- `MediaLibrary.saveToLibraryAsync` only fails for video formats. jpeg is handled as expected.
- Permissions are granted with `MediaLibrary.requestPermissionsAsync()`
- We do locate files in  `FileSystem.cacheDirectory` but the path makes no difference.
- Library is at latest version `"expo-media-library": "~17.0.3",`
- We also tries adding `expo-video` but no luck
- `NSPhotoLibraryAddUsageDescription` and `NSPhotoLibraryUsageDescription` are present in `Info.plist`
- The error is thrown even for non-existing files with mp4 extension. Which means it does not even read its contents.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.11.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: 52.0.17 => 52.0.17 
      expo-router: ~4.0.11 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: 0.19.13 => 0.19.13 
    npmGlobalPackages:
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check if the project meets version requirements for submission to app stores
✖ Validate packages against React Native Directory package metadata
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: orientation, icon, scheme, userInterfaceStyle, ios, android, plugins, androidStatusBar. 

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: react-native-iap
Unmaintained: react-native-responsive-fontsize
No metadata available: @react-native/gradle-plugin, events, expo-video, firebase, jetifier, ky, lodash-es, query-string, react-native-global-props, react-native-windows, sentry-expo, sha1
Advice: 
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.
```

**Comment by behenate** [comment]
@zallesov  Hi! I accepted the issue, but for future issues it is required to provide a full repro in a form a Github repo with a project or a link to a snack as it makes our job a lot easier. Make sure to carefully read the guidelines when creating an issue, you can also take a look at [this](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by cinohub** [comment]
how to fix this issue, how to update the fixed code

**Comment by behenate** [comment]
@cinohub You'll have to wait until we release the changes from here https://github.com/expo/expo/pull/33589. The PR is very small so you can just patch-package it if you can't wait.

**Comment by diegobonagurio** [comment]
any solution? same error

**Comment by dmilin1** [comment]
> any solution? same error

Update `expo-media-library` to at least version `17.0.3`. The fix is included in that version.
