### ISSUE TITLE
Apple Push Notification Service Server Certificate Update in February 2025, do we have to do something?

### ISSUE THREAD

**Issue by samvoults** [expo/expo#33568]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by samvoults** [comment]
Here is the email I received from Apple:

Hello,

As we announced in October, the Certification Authority (CA) for Apple Push Notification service (APNs) is changing. APNs will update the server certificates in sandbox on January 20, 2025, and in production on February 24, 2025. To continue using APNs without interruption, you’ll need to update your application’s Trust Store to include the new server certificate: [SHA-2 Root : USERTrust RSA Certification Authority certificate](https://c.apple.com/r?v=2&a=o2CKfLM8dAL7lynfnyn7UJR94mniF31x6BQ8mUoKnZXdBU2cBFhcBXev7TReAoDDIu9NkEZkkln2ibS%2FFvZOtRd8L%2BlWMQ7Q7D5RqZpMWwm9sxVnWDujTFcNdVZ0pW70pa72kh2b4ofgyqvYTpvMLXG84KPyaku84YlJW%2FAFv51%2BlD7mXqJfOw%2B3YS16RoruT50ThzE1BMq8rnEh1aQ9ZDu2KsEyc8a4CYU8Rf3fyWo097KAMD69IvMbYFuudCgk7kjB0UhytTbjaS6zlPIpzYtXFD%2BsFzWKXIIjwQ0eiOxfvg8%2BQMs8ZHPT9GvgN1N8).

To ensure a smooth transition and avoid push notification delivery failures, please make sure that both old and new server certificates are included in the Trust Store before the cut-off date for each of your application servers that connect to sandbox and production. At this time, you don’t need to update the APNs SSL provider certificates issued to you by Apple.

If you have any questions, please [contact us](https://c.apple.com/r?v=2&a=o2CKfLM8dAL7lynfnyn7UJR94mniF31x6BQ8mUoKnZXdBU2cBFhcBXev7TReAoDDIu9NkEZkkln2ibS%2FFvZOtRd8L%2BlWMQ7Q7D5RqZpMWwm9sxVnWDujTFcNdVZ0pW70pa72kh2b4ofgyqvYTpvMLXG84KPyaku84YlJW%2FAFv51%2BlD7mXqJfOw%2B3YS16RoruT50ThzE1BMq8rnEh1aQ9ZDu2KsEyc8a4CYU8Rf3fyWo097KAMD69IvMbYFuudCgk7kjB0UhytTbjaS6zlPIpzYtXFD%2BsFzWKXIIjwQ0eiOzMJpe5NXE8GUEcQgbfz%2F%2BK).

The Apple Developer Relations Team

Is there something we, developers using expo, have to do or is it on the expo development team side?

**Comment by justinzito** [comment]
I have the same question. Currently we are using expo to deliver push notifications. I am unsure if I need to do anything on the expo dashboard side to update this.

**Comment by statico** [comment]
Confused here as well. cc @jasand-pereza

**Comment by statico** [comment]
Ah, we don't have to do anything. This is answered in the blog and referenced on Discord: https://expo.dev/blog/upcoming-apple-push-notification-service-certificate-change

**Comment by justinzito** [comment]
Thanks for that.
