### ISSUE TITLE
[docs] scrollbar doesn't respect dark mode

### ISSUE THREAD

**Issue by hichemfantar** [expo/expo#33560]
### Summary

the scrollbar doesn't switch to dark mode

can be fixed by adding
`color-scheme: dark;` to the `.dark-theme` selector

### Link to the related docs page

https://expo.dev/

### Anything else?

bug:

![image](https://github.com/user-attachments/assets/eb184909-683b-46fa-b69b-b8d3f3012ba1)

fix:

![image](https://github.com/user-attachments/assets/2d437168-b3db-42a8-9c18-bf84b004e0cd)

**Comment by Simek** [comment]
Thanks for the report @hichemfantar! 👍 The fix for expo.dev will be deployed shortly.

**Comment by hichemfantar** [comment]
Thanks for the fix @Simek ! this has been bothering me for a while, also nice seeing here from the rn website repo haha
