### ISSUE TITLE
SDK 52 expo-location 18.0.3 android build app crash Class Not Found ActivityCompat

### ISSUE THREAD

**Issue by oferraanan** [expo/expo#33573]
### Minimal reproducible example

https://github.com/oferraanan/map-location.git

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Reopen of issue #33041 
This was solved on 18.0.2 and started again 18.0.3
android build app development preview and production crash Class Not Found ActivityCompat
Please refer to the original issue and the solution that was provided in 18.0.2
Need a permeant solution
Thanks

### Environment

```text
PS C:\workspaces\map-location> npx expo-env-info

  expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.19072.14.2412.12360217
    npmPackages:
      expo: ^52.0.17 => 52.0.17
      react: 18.3.1 => 18.3.1
      react-native: 0.76.3 => 0.76.3
    Expo Workflow: managed

PS C:\workspaces\map-location>
```

### Expo Doctor Diagnostics

```text
PS C:\workspaces\map-location> npx expo-doctor@latest
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
PS C:\workspaces\map-location>
```

**Comment by oferraanan** [comment]
Adding the full exception:
Android Bundled 13424ms node_modules\expo\AppEntry.js (684 modules)
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 INFO
 💡 JavaScript logs will be removed from Metro in React Native 0.77! Please use React Native DevTools as your default tool. Tip: Type j in the terminal to open (requires Google Chrome or Microsoft Edge).
 ERROR  Your app just crashed. See the error below.
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/ActivityCompat;
  io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.startUpdating(LocationGooglePlayServicesProvider.java:147)
  io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.onConnected(LocationGooglePlayServicesProvider.java:221)
  com.google.android.gms.common.internal.zak.zad(com.google.android.gms:play-services-base@@18.2.0:11)
  com.google.android.gms.common.api.internal.zabe.zab(com.google.android.gms:play-services-base@@18.2.0:3)
  com.google.android.gms.common.api.internal.zaaw.zaC(com.google.android.gms:play-services-base@@18.2.0:11)
  com.google.android.gms.common.api.internal.zaaw.zag(com.google.android.gms:play-services-base@@18.2.0:4)
  com.google.android.gms.common.api.internal.zabi.onConnected(com.google.android.gms:play-services-base@@18.2.0:2)
  com.google.android.gms.common.api.internal.zat.onConnected(com.google.android.gms:play-services-base@@18.2.0:1)
  com.google.android.gms.common.internal.zah.onConnected(com.google.android.gms:play-services-base@@18.2.0:1)
  com.google.android.gms.common.internal.zzf.zzd(com.google.android.gms:play-services-basement@@18.1.0:10)
  com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:4)
  com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
  com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
  android.os.Handler.dispatchMessage(Handler.java:106)
  android.os.Looper.loopOnce(Looper.java:226)
  android.os.Looper.loop(Looper.java:313)
  android.app.ActivityThread.main(ActivityThread.java:8762)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.ActivityCompat" on path: DexPathList[[zip file "/data/app/~~UftrAkvZmu8dunapNf03Bw==/com.map.location-K77MoO-Smkorbod73v0Z6Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~UftrAkvZmu8dunapNf03Bw==/com.map.location-K77MoO-Smkorbod73v0Z6Q==/lib/arm64, /data/app/~~UftrAkvZmu8dunapNf03Bw==/com.map.location-K77MoO-Smkorbod73v0Z6Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
  dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
  java.lang.ClassLoader.loadClass(ClassLoader.java:637)
  java.lang.ClassLoader.loadClass(ClassLoader.java:573)
  io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.startUpdating(LocationGooglePlayServicesProvider.java:147)
  io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.onConnected(LocationGooglePlayServicesProvider.java:221)
  com.google.android.gms.common.internal.zak.zad(com.google.android.gms:play-services-base@@18.2.0:11)
  com.google.android.gms.common.api.internal.zabe.zab(com.google.android.gms:play-services-base@@18.2.0:3)
  com.google.android.gms.common.api.internal.zaaw.zaC(com.google.android.gms:play-services-base@@18.2.0:11)
  com.google.android.gms.common.api.internal.zaaw.zag(com.google.android.gms:play-services-base@@18.2.0:4)
  com.google.android.gms.common.api.internal.zabi.onConnected(com.google.android.gms:play-services-base@@18.2.0:2)
  com.google.android.gms.common.api.internal.zat.onConnected(com.google.android.gms:play-services-base@@18.2.0:1)
  com.google.android.gms.common.internal.zah.onConnected(com.google.android.gms:play-services-base@@18.2.0:1)
  com.google.android.gms.common.internal.zzf.zzd(com.google.android.gms:play-services-basement@@18.1.0:10)
  com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:4)
  com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
  com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
  android.os.Handler.dispatchMessage(Handler.java:106)
  android.os.Looper.loopOnce(Looper.java:226)
  android.os.Looper.loop(Looper.java:313)
  android.app.ActivityThread.main(ActivityThread.java:8762)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by oferraanan** [comment]
It was handled yesterday with the following commit ( Kudo Chien )
https://github.com/expo/expo/commit/94cb885ea9956908844cdb186e00f914e5901be7
But it is still not working

**Comment by DavidAmyot** [comment]
+1

Same issue, simply using `Location.watchHeadingAsync` gives me the error.

**Comment by DavidAmyot** [comment]
@oferraanan 

A temporary fix for working development is to add `android.enableJetifier=true` to **_android/gradle.properties_**. Requires you to make a development build though.

**Comment by oferraanan** [comment]
Hi @DavidAmyot  
I am building production build using EAS system and then release it to Google play store
This problem was fixed in 18.0.2 and started again 18.0.3 the 
The only change in this 18.0.3 version was to fix this same problem in a different way but it is not working
the build.gradle dependencies was changed from the local jetified aar that was placed in the lib directory
  implementation project(":${project.name}\$io.nlopez.smartlocation-jetified-aar")
To the one which has the BUG - depends on old non existing android classes 
  api('io.nlopez.smartlocation:library:3.3.3') {
    transitive = false
  }
for now I reverted back to 18.0.2 and released my App to production
https://play.google.com/store/apps/details?id=com.airmap.application
Waiting for a permeant solution from expo-location team

**Comment by Kudo** [comment]
the fix was reverted in expo-location 18.0.3 because of build errors inside expo-go. then we fixed it and reladed the fix in 18.0.4. could you help to update `expo-location@18.0.4` and see if that works for you?

**Comment by DavidAmyot** [comment]
> the fix was reverted in expo-location 18.0.3 because of build errors inside expo-go. then we fixed it and reladed the fix in 18.0.4. could you help to update `expo-location@18.0.4` and see if that works for you?

Yeah, worked for me at least @Kudo, thanks :)

**Comment by Kudo** [comment]
cool, thanks @DavidAmyot.
waiting if that works for @oferraanan and we can close the issue.

**Comment by oferraanan** [comment]
Hi @Kudo 

Confirming its working with expo-location 18.0.4 

Thanks

**Comment by Kudo** [comment]
thanks @oferraanan for the confirmation. i'm closing this issue

**Comment by GAllwyn** [comment]
I have issues with expo-location on ios. On Expo Go, it's working absolutely fine. But in Production, app crashes when permission is denied. Works fine on android though.

**Comment by petemusicpancake** [comment]
Same issue. In production build app crashes after permissions declined
