### ISSUE TITLE
Bumping `expo-router` to 4.0.12 on a fresh `create-expo-app@latest` causes `Error: Objects are not valid as React child`

### ISSUE THREAD

**Issue by alecmolloy** [expo/expo#33585]
### Minimal reproducible example

https://github.com/alecmolloy/expo-router-child-object-error

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Creating a fresh boilerplate app from `create-expo-app@latest`, and only updating `expo-router` to `4.0.12` from `4.0.11` causes the error: 

```
Error: Objects are not valid as a React child(found object with keys {$$typeof, type, key, props, _owner, _store}}. If you meant to render a collection of children, use an array instead.
```
![Simulator Screenshot - iPhone 16 Pro - 2024-12-10 at 13 09 03](https://github.com/user-attachments/assets/50943a2e-2172-48cd-8af1-3813eb6c5b9f)

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 14.0.3
```

**Comment by brentvatne** [comment]
hello! you shouldn't bump the version to 4.0.12. we rolled back the suggested version to 4.0.11

**Comment by z1haze** [comment]
Seeing this on a freshly generated expo app using the pnpm create expo command and tabs template. The version of expo-router that is pulled in is 4.0.17.

**Comment by 11joselu** [comment]
@brentvatne Hi,

I don't want to open a new issue with same problem, but starting a new project with tv router throws same error

```npx create-expo-app MyTVProject -e with-router-tv
```

**Comment by brentvatne** [comment]
@11joselu - if you run `npx expo install --fix` in that repo does it help?

cc @douglowder - maybe we need to update the dep in that example

**Comment by douglowder** [comment]
@brentvatne @11joselu I do reproduce the problem after creating an app using `with-router-tv`, even after upgrading all dependencies to latest versions. Looks like the app source code needs to be checked against our default template to see what has changed.

**Comment by douglowder** [comment]
@brentvatne @11joselu TV templates have been fixed in https://github.com/expo/examples/pull/548 .

**Comment by XingJoe** [comment]
I encountered this problem, it turns out that the react-router version is too high, thank you

**Comment by hussainabeer** [comment]
Hi, I am having the same error @brentvatne mentioned... fresh install from with-router-tv example.
