### ISSUE TITLE
[docs] Consider a different recommendation for Toast components

### ISSUE THREAD

**Issue by coolsoftwaretyler** [expo/expo#33581]
### Summary

"Display a popup toast" entry recommends a package that seems to be unmaintained and has compatibility issues with recent Expo and React Native versions

### Link to the related docs page

https://docs.expo.dev/ui-programming/react-native-toast/

### Anything else?

Hey folks, the `react-native-root-toast` package is listed as an official Expo recommendation for Toasts, but it seems to be pretty inactive, and may even be broken on latest Expo and React Native versions

1. Here is an issue concerning the inactivity: https://github.com/magicismight/react-native-root-toast/issues/182
2. An issue about Expo compatibility (with a workaround, but no response from the maintainer for the last 8 months): https://github.com/magicismight/react-native-root-toast/issues/175
3. An issue about RN 0.75.3 compatibility (with no response from the maintainer for a month and a half): https://github.com/magicismight/react-native-root-toast/issues/181

I don't mean to put the library maintainer on blast. We all know open source is hard, and the MIT license means no one owes us any free work, of course. We should be grateful for any prior work done for free and made available.

However, I think the Expo docs should consider a different recommendation at this point. I don't have a strong opinion myself (that's why I was reading up for Expo's recommendations), but some of the commenters in those issues pointed to https://github.com/calintamas/react-native-toast-message. Perhaps there are other good options as well? Maybe [react-native-simple-toast](https://www.npmjs.com/package/react-native-simple-toast)?

The original library is implemented in JavaScript, so maybe it's appropriate even to just show a sample implementation.

**Comment by brentvatne** [comment]
hi there! we are remoivng this ui-programming section of the docs, because it is mostly out of date and i think that https://reactnative.directory/ is a better place to go for this.

ref: https://github.com/expo/expo/pull/33614
