### ISSUE TITLE
SDK 32: Tried to register to views with the same name GestureHandlerRootView

### ISSUE THREAD

**Issue by dev-esoftplay** [expo/expo#3358]
### Environment

Expo CLI 2.7.0 environment info:
    System:
      OS: Linux 4.13 Ubuntu 17.10 (Artful Aardvark)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 6.5.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      @types/expo: ^31.0.4 => 31.0.8 
      @types/react: ^16.7.18 => 16.7.22 
      @types/react-native: ^0.57.22 => 0.57.32 
      @types/react-navigation: ^3.0.1 => 3.0.1 
      expo: ^32.0.0 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.7.0

Device Target : IOS and Android

### Steps to Reproduce

1. npm install -s expo
2. npm install -s react-navigation
3. expo start

### Expected Behavior

![image](https://user-images.githubusercontent.com/38025170/51885796-b4c44c80-23bf-11e9-90a3-0b316dcdc2be.png)
must be same version

### Actual Behavior
![photo_2019-01-29_12-17-40](https://user-images.githubusercontent.com/38025170/51885839-e5a48180-23bf-11e9-8ab8-92b03bb02e06.jpg)

### Reproducible Demo
see step to reproduce

**Comment by sayem314** [comment]
32.0.2 giving me RNGestureHandler error!

**Comment by brentvatne** [comment]
update to 32.0.3 and the latest version of react-navigation and it'll resolve the issue

we've worked out a good versioning scheme for react-native-gesture-handler such that this should not occur again in the future
