### ISSUE TITLE
[sensors][ANDROID] Pedometer does not count steps when the app is closed

### ISSUE THREAD

**Issue by freddy-b-cyber** [expo/expo#33591]
### Minimal reproducible example

https://github.com/freddy-b-cyber/PedometerExpo

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Description
The watchStepCount function from the Pedometer module in expo-sensors does not include steps taken while the app was closed. On Android, the Pedometer relies on the TYPE_STEP_COUNTER sensor, which according to the Android documentation, should continue counting steps even when the app is closed, provided the sensor is not unregistered.

### Expected Behavior
When the app is reopened, watchStepCount should include all steps taken while the app was closed.

### Actual Behavior
When reopening the app, the watchStepCount function only reports steps taken after the app is reopened. Steps taken while the app was closed are not included.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
      Watchman: 2024.10.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34, 35
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-35 | Google Play Experimental 16k Page Size ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0 => 52.0.17 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by behenate** [comment]
Hi, as per our docs, [this is not a bug](https://docs.expo.dev/versions/latest/sdk/pedometer/#pedometerwatchstepcountcallback:~:text=Pedometer%20updates%20will%20not%20be%20delivered%20while%20the%20app%20is%20in%20the%20background.%20As%20an%20alternative%2C%20on%20Android%2C%20use%20another%20solution%20based%20on%20Health%20Connect%20API.%20On%20iOS%2C%20the%20getStepCountAsync%20method%20can%20be%20used%20to%20get%20the%20step%20count%20between%20two%20dates.)
