### ISSUE TITLE
__fbBatchedBridge error is not a useful message

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#336]
<img width="680" alt="screen shot 2017-07-05 at 10 26 25 am" src="https://user-images.githubusercontent.com/90494/27876630-a54b310e-616c-11e7-8baf-53ba9897d1bd.png">

We should either patch React Native upstream or in our fork or something else fancy to provide a more useful error message than this cryptic one

**Comment by ccuilla** [comment]
I've seen this too. Somewhat randomly. Only saw it on the iOS simulator so far.

**Comment by llukasxx** [comment]
I'm getting this error on my iOS simulator very often and the only solution is to constantly re-open the simulator once the error disappears. Any clue what might cause this?

**Comment by esganzerla** [comment]
+1 having this issue. It happens only while debugging remotely.
For me it only gets back to normal if I uninstall the app from de iOS simulator and run `yarn run ios` again.

**Comment by kicktheken** [comment]
+1. I also have to restart many times to get a good state. I have debugging remotely enabled with a lot of assets to load, so I'm wondering if either or both of these things are related to this error?

**Comment by GollyJer** [comment]
This is happening to me pretty regularly when remotely debugging with iOS. 
The only way to fix it immediately is to uninstall the iPhone Expo app and reinstall.

**Comment by terribleben** [comment]
Related issue: https://github.com/expo/expo/issues/321

Leaving this thread open because it is specifically about making the error message more useful. That other issue ^ is about a problem which has this symptom.

**Comment by terribleben** [comment]
Fix for the error message is merged upstream: https://github.com/facebook/react-native/commit/26168d034d88365cdfc5297c1866e2ba8e76a9d0

Issue #321 (which had this symptom) is also fixed.
