### ISSUE TITLE
expo-updates breaks op-sqlite with libsql on ios

### ISSUE THREAD

**Issue by jmatsushita** [expo/expo#33644]
### Minimal reproducible example

https://github.com/jmatsushita/expo-libsql-bug

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in a development build

### Summary

Without `expo-updates` the main page shows `Sqlite Test Result: 1` but after adding `expo-updates` and regenerating the project with `expo prebuild`, running the project in XCode breaks and shows:  

```
thread '<unnamed>' panicked at libsql/src/local/database.rs:239:17:
assertion `left == right` failed: libsql was configured with an incorrect threading configuration and
                    the api is not safe to use. Please check that no multi-thread options have
                    been set. If nothing was configured then please open an issue at:
                    https://github.com/libsql/libsql
  left: 21
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x109c51b20 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6e07ac9cbc84bbf7
   1:        0x109c91760 - core::fmt::write::he4e08ea2421faad4
   2:        0x109c47988 - std::io::Write::write_fmt::h8e35f44829a6d492
   3:        0x109c540dc - std::panicking::default_hook::{{closure}}::h5423069eaa907c60
   4:        0x109c53ce8 - std::panicking::default_hook::ha5bc641a0ba9a664
   5:        0x109c54d84 - std::panicking::rust_panic_with_hook::hff8ab7378efed505
   6:        0x109c545f0 - std::panicking::begin_panic_handler::{{closure}}::h7f4f159596a77c8b
   7:        0x109c51fac - std::sys::backtrace::__rust_end_short_backtrace::hd94c1ab8ebbb033f
   8:        0x109c542e0 - _rust_begin_unwind
   9:        0x109cc10c8 - core::panicking::panic_nounwind_fmt::h28cf8620a708db9b
  10:        0x109cc1140 - core::panicking::panic_nounwind::h23f9ec7786b388ce
  11:        0x109cc12b8 - core::panicking::panic_cannot_unwind::hb9fd807402cdce34
  12:        0x109673e38 - _libsql_open_file
  13:        0x10947f1bc - __ZN8opsqlite20opsqlite_libsql_openERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_S8_
  14:        0x109499b44 - __ZN8opsqlite12DBHostObjectC2ERN8facebook3jsi7RuntimeERNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENS5_10shared_ptrINS1_5react11CallInvokerEEENSD_INS_10ThreadPoolEEESC_SC_SC_SC_SC_
  15:        0x109499d28 - __ZN8opsqlite12DBHostObjectC1ERN8facebook3jsi7RuntimeERNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENS5_10shared_ptrINS1_5react11CallInvokerEEENSD_INS_10ThreadPoolEEESC_SC_SC_SC_SC_
  16:        0x109475810 - __ZNSt3__112construct_atB8de180100IN8opsqlite12DBHostObjectEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_10shared_ptrINS3_5react11CallInvokerEEERNSE_INS1_10ThreadPoolEEESD_SD_SD_SD_SD_EPS2_EEPT_SP_DpOT0_
  17:        0x10947573c - __ZNSt3__114__construct_atB8de180100IN8opsqlite12DBHostObjectEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_10shared_ptrINS3_5react11CallInvokerEEERNSE_INS1_10ThreadPoolEEESD_SD_SD_SD_SD_EPS2_EEPT_SP_DpOT0_
  18:        0x109475534 - __ZNSt3__116allocator_traitsINS_9allocatorIN8opsqlite12DBHostObjectEEEE9constructB8de180100IS3_JRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEERKNS_10shared_ptrINS7_5react11CallInvokerEEERNSH_INS2_10ThreadPoolEEESG_SG_SG_SG_SG_EvvEEvRS4_PT_DpOT0_
  19:        0x109475408 - __ZNSt3__120__shared_ptr_emplaceIN8opsqlite12DBHostObjectENS_9allocatorIS2_EEEC2B8de180100IJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEERKNS_10shared_ptrINS7_5react11CallInvokerEEERNSH_INS1_10ThreadPoolEEESG_SG_SG_SG_SG_ES4_Li0EEES4_DpOT_
  20:        0x1094750a4 - __ZNSt3__120__shared_ptr_emplaceIN8opsqlite12DBHostObjectENS_9allocatorIS2_EEEC1B8de180100IJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEERKNS_10shared_ptrINS7_5react11CallInvokerEEERNSH_INS1_10ThreadPoolEEESG_SG_SG_SG_SG_ES4_Li0EEES4_DpOT_
  21:        0x109474f58 - __ZNSt3__115allocate_sharedB8de180100IN8opsqlite12DBHostObjectENS_9allocatorIS2_EEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEERKNS_10shared_ptrINS5_5react11CallInvokerEEERNSF_INS1_10ThreadPoolEEESE_SE_SE_SE_SE_EvEENSF_IT_EERKT0_DpOT1_
  22:        0x109474dec - __ZNSt3__111make_sharedB8de180100IN8opsqlite12DBHostObjectEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_10shared_ptrINS3_5react11CallInvokerEEERNSE_INS1_10ThreadPoolEEESD_SD_SD_SD_SD_EvEENSE_IT_EEDpOT0_
  23:        0x109474c34 - __ZZN8opsqlite7installERN8facebook3jsi7RuntimeERKNSt3__110shared_ptrINS0_5react11CallInvokerEEEPKcSC_SC_ENK3$_0clES3_RKNS1_5ValueEPSF_m
  24:        0x109474848 - __ZNSt3__18__invokeB8de180100IRZN8opsqlite7installERN8facebook3jsi7RuntimeERKNS_10shared_ptrINS2_5react11CallInvokerEEEPKcSD_SD_E3$_0JS5_RKNS3_5ValueEPSH_mEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOSK_DpOSL_
  25:        0x1094747d0 - __ZNSt3__128__invoke_void_return_wrapperIN8facebook3jsi5ValueELb0EE6__callB8de180100IJRZN8opsqlite7installERNS2_7RuntimeERKNS_10shared_ptrINS1_5react11CallInvokerEEEPKcSG_SG_E3$_0S8_RKS3_PSJ_mEEES3_DpOT_
  26:        0x109474784 - __ZNSt3__110__function12__alloc_funcIZN8opsqlite7installERN8facebook3jsi7RuntimeERKNS_10shared_ptrINS3_5react11CallInvokerEEEPKcSE_SE_E3$_0NS_9allocatorISF_EEFNS4_5ValueES6_RKSI_PSJ_mEEclB8de180100ES6_SK_OSL_Om
  27:        0x1094733b8 - __ZNSt3__110__function6__funcIZN8opsqlite7installERN8facebook3jsi7RuntimeERKNS_10shared_ptrINS3_5react11CallInvokerEEEPKcSE_SE_E3$_0NS_9allocatorISF_EEFNS4_5ValueES6_RKSI_PSJ_mEEclES6_SK_OSL_Om
  28:        0x1019cf58c - __ZN8facebook6hermes17HermesRuntimeImpl9HFContext4funcEPvRN6hermes2vm7RuntimeENS5_10NativeArgsE
thread caused non-unwinding panic. aborting.
Type: stdio
```

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /nix/store/fwgfw6i5q1hv49bgfl96bmzv72l98khy-nodejs-18.18.2/bin/node
      Yarn: 3.6.0 - /nix/store/4m2cr08zb0f01axz21g7kjjpy5qwd390-yarn-1.22.19/bin/yarn
      npm: 9.8.1 - /nix/store/fwgfw6i5q1hv49bgfl96bmzv72l98khy-nodejs-18.18.2/bin/npm
      Watchman: 2024.11.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.18 => 52.0.18
      expo-router: 4.0.11 => 4.0.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, if you don't run prebuild in your build pipeline, the following properties will not be synced: orientation, icon, scheme, userInterfaceStyle, ios, android, plugins, androidStatusBar.


The following issues were found when validating your dependencies against React Native Directory:
Untested on New Architecture: tamagui
Unmaintained: react-native-keyboard-accessory
No metadata available: react-native-safe-area, react-table, rn-text-editor, signia, signia-react, sodium-javascript, sodium-native, three, three-forcegraph, three-stdlib, three-to-cannon, troika-three-text, universal-tooltip, util, variant, wa-sqlite
Advice:
- Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.
- Add packages to expo.doctor.reactNativeDirectoryCheck.exclude in package.json to selectively skip validations, if the warning is not relevant.
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by brentvatne** [comment]
... or does op-sqlite break expo-updates? 🤔 it looks like from the top of your error trace it is saying that libsql is incorrectly configured

**Comment by jmatsushita** [comment]
I suppose that's possible 😬 , but `op-sqlite` with `libsql` works fine until you install `expo-updates`, If you remove `expo-updates` from the repro and clean `node_modules` and `ios` directories, 

Maybe @ospfranco has some ideas? It seems that [the failing assertion](https://github.com/tursodatabase/libsql/blob/main/libsql/src/local/database.rs#L239-L246) means we might need the `-DSQLITE_CONFIG_SERIALIZED` flag?

**Comment by ospfranco** [comment]
This is covered in the docs

https://ospfranco.notion.site/Gotchas-bedf4f3e9dc1444480fc687d8917751a

**Comment by jmatsushita** [comment]
Thank you 🙏 I guess we're falling in this documented case
> Even if they manage to compile, they might compile sqlite with different compilation flags and you might face runtime errors.

Maybe the expo team has ideas on how to avoid different sqlite builds interfering with each other?

**Comment by ospfranco** [comment]
You can add the `-DSQLITE_CONFIG_SERIALIZED` flag on the op-sqlite config and see what happens, but the .a should already contain the compiled sqlite so it's probably a symbol error where the version compiled by expo-sqlite is being used instead. I would also be curious to find a solution here, expo-updates is a valuable package and widely used and would love to get rid of clashes.

**Comment by Kudo** [comment]
that libsql static lib `libsql_experimental.a` exposes sqlite3 symbols so other sqlite callsites will just use the symbols primarily. that includes expo-updates. expo-updates internally calls `sqlite3_open ( -> sqlite3_initialize)` beforehand. that's from app startup and before op-sqlite(libsql) be initialized. after sqlite3_initialize, the `sqlite3_config(SQLITE_CONFIG_SERIALIZED)` will return `SQLITE_MISUSE`. i can see the return value from sqlite3_config is 21 (SQLITE_MISUSE).

so, i think in libsql side it should allow other people call `sqlite3_initialize` beforehand. or, maybe dylib is another option to keep everything isolated.

**Comment by ospfranco** [comment]
switching to a dylib can be done. I just don't have the bandwidth for it at the moment plus would require to get in touch with the turso folks. @jmatsushita you can try on their discord to see if they have appetite to sponsor the work.

**Comment by jmatsushita** [comment]
@Kudo hi 👋  Thanks a lot for the detail outline of what is going wrong. I see you've addressed similar problems with https://github.com/expo/expo/commit/599c032c44216005774efac1bf640fe628506de6 so it's really appreciated to have your perspective on this. 

@ospfranco Makes sense that turso might need to be involved in this. CC @levydsa who seems to be doing most of the work on `libsql-c`. 

I'll follow up on a new issue in the `op-sqlite` repo. :wave:

**Comment by Kudo** [comment]
thanks @ospfranco and @jmatsushita!
i felt that i mislead for the symbol stuff. symbol conflict from 599c032c is to resolve a build time error. the libsql error in this issue is a runtime error. no matter the sqlite3 symbols coming from libsql, ios system sqlite3, third party [sqlite3](https://cocoapods.org/pods/sqlite3), or sqlcipher, the issue will still happen. this is just libsql doesn't expect other people to call `sqlite3_initialize` beforehand.

**Comment by ospfranco** [comment]
Ah ok, yeah, I was already wondering how switching to a dylib would change the situation as they all register the same symbols. So, this basically needs changes in libsql itself. Not as easy...

**Comment by Kudo** [comment]
> I was already wondering how switching to a dylib would change the situation as they all register the same symbols.

even they all have the same symbols. i would expect the [global `sqlite3GlobalConfig` variable](https://github.com/sqlite/sqlite/blob/9ee02515c45b8de7586e01024221cd9eb4d9b40b/src/main.c#L429) would be isolated and have different instances, since they are cross dynamic library boundary. not 100% sure for this, please correct me if my understanding is wrong.

**Comment by ospfranco** [comment]
Gonna have to involve @haaawk here. I don't know how the internals of libsql work

**Comment by ospfranco** [comment]
I've tried messaging the turso team on discord but I don't think this is a priority for them.

**Comment by haaawk** [comment]
> I've tried messaging the turso team on discord but gotten no answer. I don't think RN is a priority for them.

Sorry I forgot to tag the right engineer.

**Comment by 386sx** [comment]
Just mentioning that the same thing happens with https://github.com/transistorsoft/react-native-background-geolocation on iOS

op-sqlite 11.2.5, "libsql": true
rn 0.76.1
ios 18.2

`thread '<unnamed>' panicked at libsql/src/local/database.rs:239:17:
assertion `left == right` failed: libsql was configured with an incorrect threading configuration and
                    the api is not safe to use. Please check that no multi-thread options have
                    been set. If nothing was configured then please open an issue at:
                    https://github.com/libsql/libsql
  left: 21
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x104e9d520 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6e07ac9cbc84bbf7
   1:        0x104edd160 - core::fmt::write::he4e08ea2421faad4
   2:        0x104e93388 - std::io::Write::write_fmt::h8e35f44829a6d492
   3:        0x104e9fadc - std::panicking::default_hook::{{closure}}::h5423069eaa907c60
   4:        0x104e9f6e8 - std::panicking::default_hook::ha5bc641a0ba9a664
   5:        0x104ea0784 - std::panicking::rust_panic_with_hook::hff8ab7378efed505
   6:        0x104e9fff0 - std::panicking::begin_panic_handler::{{closure}}::h7f4f159596a77c8b
   7:        0x104e9d9ac - std::sys::backtrace::__rust_end_short_backtrace::hd94c1ab8ebbb033f
   8:        0x104e9fce0 - _rust_begin_unwind
   9:        0x104f9eb70 - core::panicking::panic_nounwind_fmt::h28cf8620a708db9b
  10:        0x104f9ebe8 - core::panicking::panic_nounwind::h23f9ec7786b388ce
  11:        0x104f9ed60 - core::panicking::panic_cannot_unwind::hb9fd807402cdce34
  12:        0x1048c11cc - _libsql_connect
  13:        0x104784aa8 - __ZN8opsqlite20opsqlite_libsql_openERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_S8_
  14:        0x10479fb2c - __ZN8opsqlite12DBHostObjectC2ERN8facebook3jsi7RuntimeERNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENS5_10shared_ptrINS1_5react11CallInvokerEEENSD_INS_10ThreadPoolEEESC_SC_SC_SC_SC_
  15:        0x10479fd10 - __ZN8opsqlite12DBHostObjectC1ERN8facebook3jsi7RuntimeERNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENS5_10shared_ptrINS1_5react11CallInvokerEEENSD_INS_10ThreadPoolEEESC_SC_SC_SC_SC_
  16:        0x10477b064 - __ZNSt3__112construct_atB8de180100IN8opsqlite12DBHostObjectEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_10shared_ptrINS3_5react11CallInvokerEEERNSE_INS1_10ThreadPoolEEESD_SD_SD_SD_SD_EPS2_EEPT_SP_DpOT0_
  17:        0x10477af90 - __ZNSt3__114__construct_atB8de180100IN8opsqlite12DBHostObjectEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_10shared_ptrINS3_5react11CallInvokerEEERNSE_INS1_10ThreadPoolEEESD_SD_SD_SD_SD_EPS2_EEPT_SP_DpOT0_
  18:        0x10477ad88 - __ZNSt3__116allocator_traitsINS_9allocatorIN8opsqlite12DBHostObjectEEEE9constructB8de180100IS3_JRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS1_IcEEEERKNS_10shared_ptrINS7_5react11CallInvokerEEERNSH_INS2_10ThreadPoolEEESG_SG_SG_SG_SG_EvvEEvRS4_PT_DpOT0_
  19:        0x10477ac5c - __ZNSt3__120__shared_ptr_emplaceIN8opsqlite12DBHostObjectENS_9allocatorIS2_EEEC2B8de180100IJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEERKNS_10shared_ptrINS7_5react11CallInvokerEEERNSH_INS1_10ThreadPoolEEESG_SG_SG_SG_SG_ES4_Li0EEES4_DpOT_
  20:        0x10477a8f8 - __ZNSt3__120__shared_ptr_emplaceIN8opsqlite12DBHostObjectENS_9allocatorIS2_EEEC1B8de180100IJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEERKNS_10shared_ptrINS7_5react11CallInvokerEEERNSH_INS1_10ThreadPoolEEESG_SG_SG_SG_SG_ES4_Li0EEES4_DpOT_
  21:        0x10477a7ac - __ZNSt3__115allocate_sharedB8de180100IN8opsqlite12DBHostObjectENS_9allocatorIS2_EEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS3_IcEEEERKNS_10shared_ptrINS5_5react11CallInvokerEEERNSF_INS1_10ThreadPoolEEESE_SE_SE_SE_SE_EvEENSF_IT_EERKT0_DpOT1_
  22:        0x104779c54 - __ZNSt3__111make_sharedB8de180100IN8opsqlite12DBHostObjectEJRN8facebook3jsi7RuntimeERNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKNS_10shared_ptrINS3_5react11CallInvokerEEERNSE_INS1_10ThreadPoolEEESD_SD_SD_SD_SD_EvEENSE_IT_EEDpOT0_
  23:        0x104779954 - __ZZN8opsqlite7installERN8facebook3jsi7RuntimeERKNSt3__110shared_ptrINS0_5react11CallInvokerEEEPKcSC_SC_ENK3$_0clES3_RKNS1_5ValueEPSF_m
  24:        0x104779568 - __ZNSt3__18__invokeB8de180100IRZN8opsqlite7installERN8facebook3jsi7RuntimeERKNS_10shared_ptrINS2_5react11CallInvokerEEEPKcSD_SD_E3$_0JS5_RKNS3_5ValueEPSH_mEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOSK_DpOSL_
  25:        0x1047794f0 - __ZNSt3__128__invoke_void_return_wrapperIN8facebook3jsi5ValueELb0EE6__callB8de180100IJRZN8opsqlite7installERNS2_7RuntimeERKNS_10shared_ptrINS1_5react11CallInvokerEEEPKcSG_SG_E3$_0S8_RKS3_PSJ_mEEES3_DpOT_
  26:        0x1047794a4 - __ZNSt3__110__function12__alloc_funcIZN8opsqlite7installERN8facebook3jsi7RuntimeERKNS_10shared_ptrINS3_5react11CallInvokerEEEPKcSE_SE_E3$_0NS_9allocatorISF_EEFNS4_5ValueES6_RKSI_PSJ_mEEclB8de180100ES6_SK_OSL_Om
  27:        0x1047780d8 - __ZNSt3__110__function6__funcIZN8opsqlite7installERN8facebook3jsi7RuntimeERKNS_10shared_ptrINS3_5react11CallInvokerEEEPKcSE_SE_E3$_0NS_9allocatorISF_EEFNS4_5ValueES6_RKSI_PSJ_mEEclES6_SK_OSL_Om
  28:        0x106031a08 - __ZNKSt3__110__function12__value_funcIFN8facebook3jsi5ValueERNS3_7RuntimeERKS4_PS7_mEEclB8de180100ES6_S8_OS9_Om
  29:        0x10603138c - __ZNKSt3__18functionIFN8facebook3jsi5ValueERNS2_7RuntimeERKS3_PS6_mEEclES5_S7_S8_m
  30:        0x106030a28 - __ZZN8facebook3jsc10JSCRuntime30createFunctionFromHostFunctionERKNS_3jsi10PropNameIDEjNSt3__18functionIFNS2_5ValueERNS2_7RuntimeERKS8_PSB_mEEEEN20HostFunctionMetadata4callEPK15OpaqueJSContextP13OpaqueJSValueSL_mPKPKSK_PSN_
thread caused non-unwinding panic. aborting.`

**Comment by ospfranco** [comment]
Hey, I've spoken with the Turso team and it seems there is safe way to do this without potentially causing data loss on libsql. May I ask what configuration is expo-updates setting? Could there be a way to disable this?

**Comment by ospfranco** [comment]
@Kudo asking again, where can I find what expo-updates calls on the intialize call? Would you guys be willing to add a flag to disable the configuration?

**Comment by ospfranco** [comment]
I just carefully re-read everything and went through the expo-updates code. I now got what @Kudo was saying. Expo-updates just calls sqlite3_open (which internally calls sqlite3_initialize) and libsql doesn't like this. So indeed there is nothing "wrong" expo-updates is doing, it's just libsql not being happy with sqlite3 being initialized before it can set a configuration.

One solution I would like to try is to open a connection before expo-updates does anything, but not sure how the expo tool chain works, if it loads it's own modules before the other modules. I guess one solution would be to delay the initialization of expo-updates but I don't see any API for it. Looking at the example by @jmatsushita I guess expo router is now the default so I don't see an index.js which I don't know how it works, but I don't see an index.js anymore one could force the loading of op-sqlite ahead of time.

There might be an update on libsql that gets rid of the assertion, but libsql sets SERIALIZED mode and relies on the internal sqlite mutex to guarantee thread safety.

**Comment by ospfranco** [comment]
Found a way to make this work. Open a dummy libsql db before anything else. It's not dumb if it works :)

I will add it to the op-sqlite docs. It probably can be automated with a plugin, but I'm too lazy to write one so PRs are welcome.

![Image](https://github.com/user-attachments/assets/6677e677-4102-4619-b139-fc95baead5d6)
