### ISSUE TITLE
'use dom' directive with react-player fails to build while it's working fine on dev client

### ISSUE THREAD

**Issue by mianala** [expo/expo#33660]
### Minimal reproducible example

https://github.com/mianala/expo-use-dom-react-player

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a standalone app

### Summary

After installing react-player and using it with 'use dom', I am no more able to build a release variant or build the app in EAS both for iOS and Android. Dev client works fine.  Error from terminal:

`DOM Bundling failed 3741ms node_modules\expo\dom\entry.js (371 modules)
DOM node_modules\expo\dom\entry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99                          
.5% (370/371)SyntaxError: node_modules\react-player\lib\players\Mux.js: node_modules\react-player\lib\players\Mux.js:Invalid call at line 121: import(/* webpackIgnore: true */
`${sdkUrl}`)
Error: node_modules\react-player\lib\players\Mux.js:Invalid call at line 121: import(/* webpackIgnore: true */
`${sdkUrl}`)
    at transformJS (C:\code\stage\node_modules\@expo\metro-config\build\transform-worker\metro-transform-worker.js:309:23)
    at transformJSWithBabel (C:\code\stage\node_modules\@expo\metro-config\build\transform-worker\metro-transform-worker.js:455:18)
error Command failed with exit code 1.`

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.26120
    Binaries:
      Node: 21.7.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20240728.093121.0 - C:\ProgramData\chocolatey\bin\watchman.EXE  
    IDEs:
      Android Studio: AI-241.18034.62.2411.12169540
    npmPackages:
      expo: ~52.0.18 => 52.0.18
      expo-router: 4.0.11 => 4.0.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✖ Check for common project setup issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project       
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK
```

**Comment by Kudo** [comment]
hi there! the issue is because [metro doesn't support dynamic import](https://github.com/facebook/metro/issues/1258#issuecomment-2068187925), that have been [used in react-player](https://github.com/cookpete/react-player/blob/3cda23fd0d43e747b8b8d2b58f04ceb6173b3552/src/players/Mux.js#L80). 
it happens only for release build because on release build, we have to go through every call path and generate each bundle split chunks. it then reaches to the Mux.js that having the problem.

i'm not sure whether it is possible to ask react-player adding metro support. but it you pretty sure that you won't reach to Mux.js. you can even try mocking out the Mux.js

adding metro.config.js the this
```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName === './Mux' && context.originModulePath.indexOf('node_modules/react-player') >= 0) {
    return { type: 'empty' };
  }
  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
```
