### ISSUE TITLE
Unable To Run Jest Tests

### ISSUE THREAD

**Issue by rfinni** [expo/expo#3366]
### Environment

Expo CLI 2.7.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
      npm: 6.5.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.7.0

Device Target : IOS and Android

### Steps to Reproduce

1. ```expo init new-project```
2. Choose ```tabs: several example screens and tabs using react-navigation``` option
3. Choose ```managed: (default) Build your app with JavaScript with Expo APIs.``` option
4. ```cd new-project```
5. ```expo start```
6. ```npm run test```

### Expected Behavior

Expected sample tests to run with the ```npm run test``` script.

### Actual Behavior

The sample tests do not run and the following error and error log are produced. 

```
> @ test /Users/me/Projects/react-native/test-app
> node ./node_modules/jest/bin/jest.js --watchAll

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/me/Projects/react-native/test-app/node_modules/jest/bin/jest.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `node ./node_modules/jest/bin/jest.js --watchAll`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2019-01-30T16_43_54_111Z-debug.log
```

<img width="1422" alt="screen shot 2019-01-30 at 11 03 10 am" src="https://user-images.githubusercontent.com/1593553/51998653-abe68000-247e-11e9-81ac-6b5770faf111.png">

In addition, there is no "jest" directory in node_modules.
<img width="297" alt="screen shot 2019-01-30 at 10 56 27 am" src="https://user-images.githubusercontent.com/1593553/51998514-72ae1000-247e-11e9-8049-1b5bf35d694a.png">

### Reproducible Demo

No demo but this appears to be happening on fresh expo projects for me.

**Comment by c316** [comment]
Upgrading jest to `"jest": "^24.1.0",` and then doing an `npm install` fixed it for me. There are some breaking changes in 24, so beware.

**Comment by rfinni** [comment]
I got this working temporarily by manually installing Jest (24.1.0) and then adding an additional config change to jest in package.json. Something similar was suggested here: https://forums.expo.io/t/cannot-run-jest/15477/3

```
"jest": {
  "preset": "jest-expo",
  "transformIgnorePatterns": [
    "node_modules/(?!(.*expo.*|.*react.*)/)"
  ],
}
```

**Comment by cmacdonnacha** [comment]
Thanks @c316 , I also got this to work after upgrading to `"jest": "^24.1.0"`

**Comment by EvanBacon** [comment]
Sorry you had issues with this, it seems resolved with Jest 24. If you continue to have issues with Jest 24, please open a new issue.
