### ISSUE TITLE
[expo-audio] Unable to play bundled assets

### ISSUE THREAD

**Issue by mihailapuste** [expo/expo#33665]
### Minimal reproducible example

https://github.com/mihailapuste/ExpoAudioAssetTest

### What platform(s) does this occur on?

Android, iOS

### Where did you reproduce the issue?

in a development build

### Summary

I'm looking to fully replace our usage of the current `expo-av` module, however I have not been able to play bundled assets. Streaming and playing files saved to local storage is fine, however files that are bundled with my project cannot be played. 

I get the following error when attempting to use `.replace(source)` on the audio player, as demonstrated in my minimal repro:
```bash
Error: FunctionCallException: Calling the 'replace' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137)
→ Caused by: ArgumentCastException: The 1st argument cannot be cast to type AudioSource (at ExpoModulesCore/MainValueConverter.swift:40)
→ Caused by: ConvertingException<AudioSource>: Cannot convert 'Optional(Optional(2))' to AudioSource (at ExpoModulesCore/Record.swift:40)
```

Locally bundled files have a `number` as their identifier, and it seems the `replace()` method's type `AudioSource` doesn't allow for such
```tyepscript
export type AudioSource =
  | string
  | {
      uri?: string;
      headers?: Record<string, string>;
    }
  | null
```

I ran into a similar issue once before on expo sdk 50 https://github.com/expo/expo/issues/26474.

Hope this helps, and can be addressed relatively easily.

Thank you expo team for all your hard work! 🚀

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.5.1 - /opt/homebrew/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/bin/npm
      Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/mihailapuste/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.0 => 52.0.18 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    npmGlobalPackages:
      eas-cli: 7.1.3
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Multiple lock files detected (yarn.lock, package-lock.json). This may result in unexpected behavior in CI environments, such as EAS Build, which infer the package manager from the lock file.

Error: Problem validating fields in /Users/mihailapuste/ExpoAudioAssetTest/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'displayName'.

It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config. This can lead to unexpected and hard to debug issues. Learn more: https://docs.expo.dev/guides/customizing-metro/
Advice: Update your metro.config.js to extend @expo/metro-config.

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-audio
Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

The following packages should be updated for best compatibility with the installed expo version:
  typescript@5.0.4 - expected version: ^5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.
```

**Comment by mihailapuste** [comment]
@alanjhughes 

I just re-tested you latest changes released in `expo-audio-0.3.1` and the issue still persist. I've upgraded my test repro to include the latest version for testing and reproducing the issue


https://github.com/mihailapuste/ExpoAudioAssetTest 

https://github.com/user-attachments/assets/15e66236-3cba-4085-9eb1-4e9c764706cd

Or perhaps I'm missing some other step?

Thank you for your quick response.

**Comment by anasvemmully** [comment]
+1 @ expo-audio-0.3.1

**Comment by durpy2** [comment]
@alanjhughes I think we may need to open this issue again, currently the expo-audio doesn't work with bundled asset audio files (by providing assetIds).

It looks like we can provide assetId as the audiosource for bundled asset audio files in expo-audio ~0.3.1 in addition to uri. However the audioPlayer is stuck on "isBuffering" like below in the audioStatus when an assetId is provided instead of uri - 

`{"currentTime": 0, "duration": 0, "id": "0A01EEC5-FE63-4DD1-A5F1-EEC119CF9364", "isBuffering": true, "isLoaded": false, "isPlaying": false, "loop": false, "mute": false, "playbackRate": 1, "playbackState": "unknown", "playing": false, "reasonForWaitingToPlay": "noItemToPlay", "shouldCorrectPitch": false, "timeControlStatus": "waitingToPlayAtSpecifiedRate"}
`

Anyone figured out on playing bundled audio file assets in expo-audio ?

**Comment by songkeys** [comment]
> When changing the audioSource type (local vs remote) the audioPlayer instance crashes with below error.
Error: FunctionCallException: Calling the 'get' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137) → Caused by: NativeSharedObjectNotFoundException: Unable to find the native shared object associated with given JavaScript object (at ExpoModulesCore/DynamicSharedObjectType.swift:58)

I'm encountering the same issue. I'm surprising to see this is the only issue talking about this. What is the correct way to load a remote audio? My current code goes like this:

```tsx
function App() {
  const player = useAudioPlayer({ uri: "https://.../example.mp3" });

  return (
    <View>
      <Button title="Play Sound" onPress={() => player.play()} />
    </View>
  );
}
```

Anything I've missed?

**Comment by Rinshin-Jalal** [comment]
Hey @araujobarret 
Were you able to fix?

**Comment by araujobarret** [comment]
@Rinshin-Jalal not at all, was trying to investigate the native code to create a fix, but since I'm not too familiar with Kotlin and Swift I failed there miserably 😂

**Comment by joranb** [comment]
Was about to migrate from expo-av when I ran into this error message, doesn't seem like this library is mature enough yet.

**Comment by JapjyotSuri** [comment]
Is there any fix for being able to play local bundled assets while building the app using eas.I am being able to play a sound in local build but not in eas build?

**Comment by vicnguyenqt** [comment]
No one actually fix this, still an issue with eas build

**Comment by dmartincc** [comment]
Similar issue with expo-video 2.2.2 and Expo 53.0.19.

` ERROR  Error toggling video playback: [Error: FunctionCallException: Calling the 'play' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137)
→ Caused by: NativeSharedObjectNotFoundException: Unable to find the native shared object associated with given JavaScript object (at ExpoModulesCore/DynamicSharedObjectType.swift:58)]`

I'm migrating to expo-av for now.

**Comment by PierreCapo** [comment]
It seems the `expo-audio`library indeed has a bug, functions like `play` doesn't work as `0.4.8`

**Comment by araujobarret** [comment]
@dmartincc does `expo-av` work in your case?

**Comment by 0hhanum** [comment]
Temporary workaround I found.
I noticed that playback wasn’t working properly in the Android production build.
I found that the asset paths included in the bundle weren’t being resolved correctly.
I used expo-asset.

Here’s the code I used:
```tsx
import { Asset } from "expo-asset";
import { useAudioPlayer } from "expo-audio";
import { Platform } from "react-native";


export default function useAudioAsset(assetId: number) {
  const platform = Platform.OS;
  const getAudioSource = () => {
    if (!__DEV__ && platform === "android") {
      const assetinfo = Asset.fromModule(assetId);
      const rawPath = assetinfo.localUri?.replace("file://", "");
      if (!rawPath) return;
      return { uri: rawPath };
    }
    return assetId;
  };

  const player = useAudioPlayer(getAudioSource());
  const play = () => {
    player.seekTo(0);
    player.play();
  };

  return { play };
}

...

const { play } = useAudioAsset(require("@/assets/audios/example.mp3"));

```

**Comment by Muromi-Rikka** [comment]
The issue with being unable to play remote audio still persists in Expo v53.0.20 and expo-audio v0.4.8. For this reason, I think the issue needs to be reopened.

**Comment by alanjhughes** [comment]
@Muromi-Rikka - This issue was specifically to do with bundled audio files. Not remote.

**Comment by araujobarret** [comment]
@alanjhughes, for me, this issue is still alive; it fails for me for remote and local files https://github.com/expo/expo/issues/33665#issuecomment-2862021210

**Comment by alanjhughes** [comment]
@araujobarret please provide an example project that accurately demonstrates the issue and I can look in to it.

**Comment by steelzeh** [comment]
Make sure the audio is played from a component that remains mounted. This approach worked for me.

If you start playback and then dismiss the view or hide the component, the AudioPlayer will be released, and the audio will stop working.

**Comment by know-mad** [comment]
I have the same issue it seems when trying to implement a custom seekTo functionality using a panResponder on an Animated View. Basically if i try to run it from the onPanResponderRelease it crashes my app but if I put the seekTo on any of the pressable components inline it works fine? So weird.

```
console.js:654 Error: FunctionCallException: Calling the 'get' function has failed (at ExpoModulesCore/SyncFunctionDefinition.swift:137)
→ Caused by: NativeSharedObjectNotFoundException: Unable to find the native shared object associated with given JavaScript object (at ExpoModulesCore/DynamicSharedObjectType.swift:58), js engine: hermes

```

```
  const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onMoveShouldSetPanResponder: () => true,
      onPanResponderGrant: () => {
        setIsDragging(true);
        pan.extractOffset();
      },
      onPanResponderMove: Animated.event([null, { dx: pan }], {
        useNativeDriver: false,
        // visual drag only
      }),
      onPanResponderRelease: () => {
        pan.flattenOffset();
        setIsDragging(false);

        if (!player || !player.isLoaded) return; // ✅ safe guard

        pan.stopAnimation((position) => {
          const maxX = Math.max(barWidth - knobSize, 0);
          const clamped = Math.min(Math.max(position, 0), maxX);
          const progress = maxX > 0 ? clamped / maxX : 0;
          const newTime = progress * (player?.duration ?? 0);

          setCurrentTime(newTime);
          player.seekTo(newTime);
        });

      },
    })
  ).current;
```
