### ISSUE TITLE
React Native & Expo update causing my app to crash

### ISSUE THREAD

**Issue by adammartiska** [expo/expo#33687]
### Minimal reproducible example

https://github.com/Do-lacna/usetri

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

2 days ago I wanted to update expo & react native to its latest version in order to use React Native Debugger. I updated it somehow and get the app working after some local development setup struggle and was able to successfully run my application. As landing page I have **sign-in.tsx** screen where is login performed. I try to login via google (or just regular email/password login) and once authentication succeeds I get the token and information about user from firebase. Once I get this I want to navigate with expo router like this: 

 
```
const navigationState = useRootNavigationState();
const navigatorReady = navigationState?.key != null;

  React.useEffect(() => {
    if (!navigatorReady) {
      return;
    }
    if (user && authToken) {
      router.replace("/");
    }
  }, [user, authToken, navigatorReady]);
```

Once I am navigation to this path my app crashes with error message:
**Warning: TypeError: Cannot read property 'regular' of undefined**

As I was investigating it a little bit, this error might have something to do with **React Navigation** library as Expo Router is built upon that. In the debug log I managed to find the error comes from **useHeaderConfigProps.js** where there is font loading with font.regular option. I also found some issue opened in React Navigation for that - https://github.com/react-navigation/react-navigation/issues/12222
Can someone please help me what might be wrong with this? 

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.18 => 52.0.18
      expo-router: 4.0.11 => 4.0.11
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
      react-native-web: ~0.19.6 => 0.19.13
    Expo Workflow: bare
```

**Comment by tyrauber** [comment]
@adammartiska, I got bit by this as well after a SDK 52 upgrade. 

First make sure expo-router and all the react-navigation dependencies are up-to-date.  The error is related to an API change in react-navigation 7.0 in regards to theme.  You [must now provide a fonts prop to theme](
https://reactnavigation.org/docs/upgrading-from-6.x/#the-theme-prop-now-accepts-a-fonts-property) before using theme in ThemeProvider.

```
import { DefaultTheme } from '@react-navigation/native';

const theme = {
  colors: {
    // ...
  },
  fonts: DefaultTheme.fonts,
};
```

This resolved the error for me.

**Comment by adammartiska** [comment]
> @adammartiska, I got bit by this as well after a SDK 52 upgrade.
> 
> First make sure expo-router and all the react-navigation dependencies are up-to-date. The error is related to an API change in react-navigation 7.0 in regards to theme. You [must now provide a fonts prop to theme](https://reactnavigation.org/docs/upgrading-from-6.x/#the-theme-prop-now-accepts-a-fonts-property) before using theme in ThemeProvider.
> 
> ```
> import { DefaultTheme } from '@react-navigation/native';
> 
> const theme = {
>   colors: {
>     // ...
>   },
>   fonts: DefaultTheme.fonts,
> };
> ```
> 
> This resolved the error for me.

Hello, thank you for your reply. I am not using react-navigation library I suppose expo-router is using it, so I don't have any control over it. I haven't tried to update expo-router to the latest version, will try that. Thank you

**Comment by sabinayakc** [comment]
@adammartiska , in your root layout when you define the themeprovider pass the theme there.

 ```
 <ThemeProvider value={theme}>
       ....
  </ThemeProvider>
```

**Comment by MateuszRostkowski** [comment]
My issue was that in expo 51 I didn't have font values in theme object, and I've needed to add something like this to theme:

```
  fonts: {
    bold: { fontFamily: fonts.Bold, fontWeight: '600' },
    heavy: { fontFamily: fonts.Bold, fontWeight: '700' },
    medium: { fontFamily: fonts.Medium, fontWeight: '500' },
    regular: { fontFamily: fonts.Regular, fontWeight: '400' },
  },
```
