### ISSUE TITLE
Task :expo-dev-launcher:compileReleaseWithDevLauncherKotlin FAILED

### ISSUE THREAD

**Issue by SimantaRajSarma** [expo/expo#33707]
### Minimal reproducible example

https://github.com/SimantaRajSarma/testing-native-support

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

Summary
> Task :expo-dev-launcher:compileReleaseWithDevLauncherKotlin
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:304:20 Unresolved reference: launchUrl
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/DevLauncherController.kt:310:20 Unresolved reference: launchUrl
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/helpers/DevLauncherReactUtils.kt:23:39 Unresolved reference: DevLauncherBridgelessDevSupportManager
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/helpers/DevLauncherReactUtils.kt:24:39 Unresolved reference: DevLauncherDevSupportManagerSwapper
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/helpers/DevLauncherReactUtils.kt:48:38 Unresolved reference: DevLauncherBridgelessDevSupportManager
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/helpers/DevLauncherReactUtils.kt:56:3 Unresolved reference: DevLauncherDevSupportManagerSwapper
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/DevLauncherReactHost.kt:18:8 Unresolved reference: devmenu
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/DevLauncherReactHost.kt:80:15 Unresolved reference: SafeAreaProviderManager
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/DevLauncherReactNativeHost.kt:8:8 Unresolved reference: devmenu
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/DevLauncherReactNativeHost.kt:46:15 Unresolved reference: SafeAreaProviderManager
e: file:///C:/Users/Dell/Desktop/testing-native-support/node_modules/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/react/DevLauncherReactNativeHostHandler.kt:17:12 Unresolved reference: DevLauncherDevSupportManagerFactory

> Task :expo-dev-launcher:compileReleaseWithDevLauncherKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-dev-launcher:compileReleaseWithDevLauncherKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 31m 42s
1441 actionable tasks: 1287 executed, 154 up-to-date

When i try to build local android dev build i am getting this error.

Managed or bare workflow?
bare

What platform(s) does this occur on?
Android

Package versions
  "dependencies": {
    "expo": "^52.0.19",
    "expo-dev-client": "^5.0.6",
    "expo-dev-launcher": "^5.0.19",
    "expo-dev-menu": "^6.0.14",
    "expo-status-bar": "~2.0.0",
    "react": "18.3.1",
    "react-native": "0.76.5",
    "react-native-blob-util": "^0.21.1",
    "react-native-pdf": "^6.7.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@expo/cli": "^0.22.6",
    "@react-native-community/cli": "^15.1.3"
  },

Environment

System:
OS: Windows 11
Binaries:
Node: v23.1.0
npm: v10.9.0
IDE: VS Code

Reproducible demo

`https://github.com/SimantaRajSarma/testing-native-support`

### Environment

```text
Environment

System:
OS: Windows 11
Binaries:
Node: v23.1.0
npm: v10.9.0
IDE: VS Code
```

### Expo Doctor Diagnostics

```text
C:\Users\Dell\Desktop\testing-native-support>npx expo-doctor@latest
(node:10908) ExperimentalWarning: CommonJS module C:\Users\Dell\AppData\Roaming\npm\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\Dell\AppData\Roaming\npm\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Need to install the following packages:
expo-doctor@1.12.4
Ok to proceed? (y) y

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✖ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✖ Check for app config fields that may not be synced in a non-CNG project
✖ Validate packages against React Native Directory package metadata
✔ Check if the project meets version requirements for submission to app stores
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The package "expo-dev-launcher" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.
The package "expo-dev-menu" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.

This project contains native project folders but also has native configuration properties in app.json, indicating it is configured to use Prebuild. When the android/ios folders are present, EAS Build will not sync the following properties: orientation, icon, userInterfaceStyle, splash, ios, android.

Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: expo-dev-launcher, expo-dev-menu
Advice:
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by Kudo** [comment]
hi there! please try to remove `expo-dev-launcher` and `expo-dev-menu` from [your dependencies](https://github.com/SimantaRajSarma/Openpaper/blob/73a40cc7a1943f8f5197352186507ff354f43bd9/package.json#L16-L17). as expo-doctor shown,
```
The package "expo-dev-launcher" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.
The package "expo-dev-menu" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.
```

**Comment by SimantaRajSarma** [comment]
Hi

> hi there! please try to remove `expo-dev-launcher` and `expo-dev-menu` from [your dependencies](https://github.com/SimantaRajSarma/Openpaper/blob/73a40cc7a1943f8f5197352186507ff354f43bd9/package.json#L16-L17). as expo-doctor shown,
> 
> ```
> The package "expo-dev-launcher" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.
> The package "expo-dev-menu" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.
> ```

Hi, the issue has been resolved when I run `npx expo run:android`, I was doing `gradlew build` but it shows multiple issues. and I did what you told but got other issues about `CopyAssets`

**Comment by Kudo** [comment]
if you want to run gradlew explicitly, please try `./gradlew :app:assembleDebug` or `./gradlew :app:assembleRelease`.
since the build error is resolved. i'm closing this issue. if you have other issues like the `CopyAssets` mentioned, please try to create a new one. thanks!

**Comment by zhouzhonghao** [comment]
Same issue.
 
1. Run npx expo run:android. It works like a charm.
2. First run ./gradlew --refresh-dependencies and then run ./gradlew :app:assembleRelease. It works too.

**Comment by sahildb** [comment]
Same issue.

I get this issue when I try to run the ./gradlew build command.
