### ISSUE TITLE
Pushing a new dynamic route from the same dynamic route does not push a new screen onto the stack

### ISSUE THREAD

**Issue by pebeasley** [expo/expo#33727]
### Minimal reproducible example

https://github.com/pebeasley/dynamic-routing-issue

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When pushing a dynamic route and navigating to the same dynamic route but with a new param, there is no additional screen placed onto the route stack.  Instead it seems to be replacing the current dynamic route with the new params.  This should place a new route onto the stack, otherwise it seems to break the expected back behavior.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
      Yarn: 4.0.2 - ~/.nvm/versions/node/v20.4.0/bin/yarn
      npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
      Watchman: 2024.12.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.19 => 52.0.19 
      expo-router: ~4.0.13 => 4.0.13 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    Expo Workflow: bare
```

**Comment by pebeasley** [comment]
https://github.com/user-attachments/assets/b7aac4fe-0838-4dc2-9b4e-8534ca2bb7c0

**Comment by arasrezaei** [comment]
i think you should pass getId prop for that screen:
https://docs.expo.dev/router/advanced/stack/#custom-push-behavior

**Comment by pebeasley** [comment]
Yessir that's the answer 🤦 

Thank you for your response
