### ISSUE TITLE
Use UNNotificationSettings for checking notifications permissions

### ISSUE THREAD

**Issue by tidbeck** [expo/expo#3373]
### Environment
```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.7.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 31.0.4 => 31.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: 2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.6.14
```
### Steps to Reproduce

```
    const { status: existingStatus } = await Permissions.getAsync(
        Permissions.NOTIFICATIONS,
    );
```

granted or undetermined

### Expected Behavior

The `existingStatus` should be `granted`, `denied` or `undetermined`

### Actual Behavior
As described on [Expo Permission](https://docs.expo.io/versions/v32.0.0/sdk/permissions/) we will only get `granted` or `undetermined`

### Reproducible Demo
With dropped support for iOS 9 [UNNotificationSettings](https://developer.apple.com/documentation/usernotifications/unnotificationsettings) could be used to differentiate between `undetermined` and `denied` which was not possible before.

**Comment by AdamJNavarro** [comment]
Hey @tidbeck,

I agree that this would be a great addition to the SDK, but would you mind creating a Feature Request on [Canny](https://expo.canny.io/feature-requests) for this? We prefer to use github issues to track bugs rather than enhancements/feature requests.

Cheers,

Adam

**Comment by tidbeck** [comment]
Thanks for informing me @AdamJNavarro 

The Feature Request can now be found on [Canny](https://expo.canny.io/feature-requests/p/use-unnotificationsettings-for-checking-notifications-permissions)
