### ISSUE TITLE
[expo-splash-screen] Splashscreen auto hides even when using preventAutoHideAsync()

### ISSUE THREAD

**Issue by SanjayDevTech** [expo/expo#33762]
### Minimal reproducible example

https://github.com/SanjayDevTech/react-native-test-app

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

I have a simple App with Splashscreen enabled using `expo-splash-screen`.
On Mounting, the App will simulate a 2secs delay before the content is loaded. But while loading, it should show the splash screen.

I used `SplashScreen.preventAutoHideAsync()` on top of the file and on completing of delay task `SplashScreen.hide();` called.
But `SplashScreen.preventAutoHideAsync()` doesn't seems to be applied and always autohides.
It only works for a cold start.

One more thing,
`SplashScreen.preventAutoHideAsync()` returns `null` instead of a boolean as state in the documentation: https://www.npmjs.com/package/expo-splash-screen

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-242.23339.11.2421.12700392
    npmPackages:
      expo: ~52.0.20 => 52.0.20
      react: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

The following issues were found when validating your dependencies against React Native Directory:
No metadata available: patch-package, postinstall-postinstall
Advice:
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

One or more checks failed, indicating possible issues with the project.
```

**Comment by alanjhughes** [comment]
Hi @SanjayDevTech - I've just tried your example and it's working fine. I would recommend changing it to this

```typescript
  const [appIsReady, setAppIsReady] = useState(false);
  useEffect(() => {
    const id = setTimeout(() => {
      setAppIsReady(true);
      SplashScreen.hide();
    }, 2000);

    return () => clearTimeout(id);
  }, []);

  if (!appIsReady) {
    return null;
  }
```
It works only from a cold start because android will not show it again on reload. Reloading is something that only happens in development and not when you deploy to the stores.

**Comment by SanjayDevTech** [comment]
@alanjhughes Yes for production build, splash screen shows for 2 secs in cold starts.

But when I click back and open from the launcher, the splash screen shows for half a second and then shows a white screen for 2 seconds (which is the null part)

**Comment by SanjayDevTech** [comment]
Screen recording

https://github.com/user-attachments/assets/11d4addf-a6b7-49c3-8d1a-d160a9a35b1d

**Comment by alanjhughes** [comment]
@SanjayDevTech are you delaying your ui? The app shouldn't need to show the splascreen when it's already open and brought to the foreground

**Comment by SanjayDevTech** [comment]
@alanjhughes Yes I am trying to simulate an API call that I'll be implementing in my app (future) to check for Auth, check versions.
Delay code is documented here https://docs.expo.dev/versions/latest/sdk/splash-screen/#usage

**Comment by SanjayDevTech** [comment]
I still think there is some issue with `preventAutoHideAsync` function.
Because as stated in docs, this function should return boolean. But for me it returns `null`.

**Comment by yolpsoftware** [comment]
I think I have the same issue. This seems to have regressed somewhere between `0.29.12` and `0.29.18`.

Gonna investigate at which version it regressed exactly.

**Comment by alanjhughes** [comment]
@SanjayDevTech I will fix the return value but this call does not need a one and probably should never have had one. In the current implementation it will never return anything but true.

**Comment by SanjayDevTech** [comment]
I am suspecting that something changed the behaviour of `preventAutoHideAsync` somewhere between `0.27.12` and `0.29.18` and the return value `null` is just a side effect of this.

**Comment by alanjhughes** [comment]
@SanjayDevTech since the recent rewrite this function toggles a boolean. That's all. That's all it has ever done. There is no possible error that can occur and inspecting the value makes no sense.

**Comment by SanjayDevTech** [comment]
Leaving it here for reference.

Similar issue: https://github.com/expo/expo/issues/31875

**Comment by yolpsoftware** [comment]
Yes, duplicate of #31875.

**Comment by alanjhughes** [comment]
@SanjayDevTech @yolpsoftware this issue was with android. The other issue you have linked is about iOS and expo go from a version that is   3 months old and prior to the rewrite.

**Comment by alanjhughes** [comment]
@SanjayDevTech This is your example running in debug unmodified

https://github.com/user-attachments/assets/ae9e6e03-9725-41e0-8d86-7c9fc0dfa895

Here it is in release mode

https://github.com/user-attachments/assets/332136fe-8e18-42f7-b5f8-3e9c5624dab5

**Comment by SanjayDevTech** [comment]
@alanjhughes Yes that's working as expected.
But instead of going home, just click back closing the app (and not removing it from recents) now open the app from the launcher.

The app shows a splash screen for a sec and shows a blank screen.

**Comment by alanjhughes** [comment]
@SanjayDevTech 

https://github.com/user-attachments/assets/4bae4f5c-fb04-4b42-b675-fc7ba2f6de13

**Comment by alanjhughes** [comment]
@SanjayDevTech example with the back button 

https://github.com/user-attachments/assets/7d274971-183e-4258-96e9-74d14cdb2fe2

**Comment by SanjayDevTech** [comment]
@alanjhughes that's strange
I was able to reproduce this issue with my physical device.

For the first time it works.
But after that it shows blank on all cases.

I am using Android 14.

https://github.com/user-attachments/assets/0d0b1f27-7a3e-4b31-9b50-b70f0c5cd818

**Comment by alanjhughes** [comment]
@SanjayDevTech i can't reproduce on a physical device either using Android 15

**Comment by alanjhughes** [comment]
I've tried on android 13, 14, and 15

**Comment by SanjayDevTech** [comment]
Let me try it with more devices.

**Comment by SanjayDevTech** [comment]
@alanjhughes can you also share the release apk you have used.

I am suspecting everything 😬 now
