### ISSUE TITLE
Tab bar not respected as border

### ISSUE THREAD

**Issue by Bufib** [expo/expo#33767]
### Minimal reproducible example

https://github.com/Bufib/expo-bottombar

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

The tab bar doesn't work as a border in iOS. **Look at the "Test" on the bottom in android but missing in iOS!**

It does in android but in iOS the text gets beneath whereas in android it does not.  This causes the need of much more margin. The code is literally the expo template. I just changed the index page:

```
import { StyleSheet, Text, View } from "react-native";
import React from "react";

const index = () => {
  return (
    <View style={styles.container}>
      <View>
        <Text>Test</Text>
      </View>
    </View>
  );
};

export default index;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
});
```

<img width="429" alt="Bildschirmfoto 2024-12-19 um 20 06 55" src="https://github.com/user-attachments/assets/3c565eb0-b942-4b07-b4df-396cd58c9e53" />

<img width="350" alt="Bildschirmfoto 2024-12-19 um 20 11 17" src="https://github.com/user-attachments/assets/7687a2ea-ac5c-4dc9-a53b-b819595a59e0" />

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.3.0 - /opt/homebrew/bin/node
      npm: 11.0.0 - ~/.npm-global/bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.20 => 52.0.20 
      expo-router: ~4.0.14 => 4.0.14 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 14.1.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by marklawlor** [comment]
Hey! Thanks for opening the issue. Seems that this issue is related to `react-navigation` library which is a dependency of Expo Router. Can you also post your issue in [this repo](https://github.com/react-navigation/react-navigation) so that it's notified to the maintainers of that library? This will help us fix the issue faster since it's upto the maintainers of that library to investigate it.

**Comment by marklawlor** [comment]
The default template has some `ios` specific styling in the `(tabs)/_layout` that is causing your issue. This is needed for the template's `<ParallaxScrollView />` but may not be needed for your design. 

You may want to considering removing this block of code https://github.com/Bufib/expo-bottombar/blob/c690b9b1d53476b099a7009248ad815c6b5fece8/app/(tabs)/_layout.tsx#L21-L27

**Comment by Bufib** [comment]
> The default template has some `ios` specific styling in the `(tabs)/_layout` that is causing your issue. This is needed for the template's `<ParallaxScrollView />` but may not be needed for your design.
> 
> You may want to considering removing this block of code https://github.com/Bufib/expo-bottombar/blob/c690b9b1d53476b099a7009248ad815c6b5fece8/app/(tabs)/_layout.tsx#L21-L27

It worked, thanks! 

In my opinion this should be written/marked somewhere for newbies like me, since other people had the same issue. I've also seen a YouTuber who had to deal with this problem and just passed along without figuring it out.
