### ISSUE TITLE
Barcodescanner size on Android devices

### ISSUE THREAD

**Issue by ghost** [expo/expo#3378]
### Environment

Expo SDK 32 on Mac 10.13.6

### Steps to Reproduce

Create a new expo project and paste this sample, test on Android device:
https://snack.expo.io/HyiTlAn0e

### Expected Behavior

The barcode viewer is a square 200x200

### Actual Behavior

The barcode viewer height is more than 200 and cover other components vertically

![screenshot_2019-02-01-09-16-16](https://user-images.githubusercontent.com/24822858/52110962-97cb8b80-2602-11e9-863e-d53c6a6033c6.jpg)
![image-1](https://user-images.githubusercontent.com/24822858/52111113-0577b780-2603-11e9-8097-52471f39259b.jpg)

**Comment by mgiorgi-github** [comment]
I've partially solved by added a wrapper View with fixed size that covers the barcode screen

**Comment by olee2002** [comment]
Currently I made the scan to the full screen and added a button box (w:250px, h:250px) with dotted line to indicate the scan area. Temp fix until they resolve this.
```<Root style={stylesHome.container}>
                <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                    {this.props.isFocused ? <BarCodeScanner
                        onBarCodeScanned={this.handleBarCodeScanned}
                        style={Platform.OS === 'ios' ?
                            { height: 250, width: 250 } : { height: '100%', width: '100%' }}
                    /> : null}
                    <Button style={style.qrButtonBox} />
                </View>
                <View style={stylesHome.footer}>
                    <Button
                        bordered
                        style={stylesHome.qrButton}
                        onPress={() => navigation.navigate('NoScanRequest')}
                    >
                        <Text style={{ color: '#fff' }}> QR Code Doesn't Scan </Text>
                    </Button>
                </View>
            </Root>```

```qrButtonBox: {
        flex: 0,
        borderWidth: 0.5,
        backgroundColor: 'transparent',
        alignSelf: 'center',
        borderColor: '#fff',
        position: 'absolute',
        width: 250,
        height: 250
    },```

**Comment by mfhassan22** [comment]
> I've partially solved by added a wrapper View with fixed size that covers the barcode screen
@mgiorgi-github 
can you help me how did you managed to do this i am trying but is not working 
`<View style={{width:150,height:150}}>
<BarCodeScanner onBarCodeRead={this._handleBarCodeRead} style={{flex:1}}/>
</View>`

**Comment by mgiorgi-github** [comment]
I've created this wrapper...

  cameraBarcodeScannerWrapper: {
    overflow: 'hidden',
    width: 260,
    height: 200,
  },

**Comment by dfagneraythink** [comment]
> 
> 
> I've created this wrapper...
> 
> cameraBarcodeScannerWrapper: {
> overflow: 'hidden',
> width: 260,
> height: 200,
> },

That works very well, thanks a lot.

**Comment by schiche** [comment]
I found something out that might help the original developer solve the issue...

If you run the code on my phone (not simulator) with my phone laying FLAT on a table , it works fine, no bug.  But the moment I tilt my phone just a little bit , the barcode window resize itself to the "wrong" size..

**Comment by bbarthec** [comment]
Hello there!
`BarCodeScanner` has been extracted into separate universal module in SDK32 and currently has a few flaws, like one described in this issue.
My suggestion is to use `Camera` component in SDK32 as it's shipped with `onBarCodeScanned` callback and behaves like `BarCodeScanner` prior to SDK32.
Unfortunately `Camera` has it's own problems as well, like not cropping preview but stretching it according to provided view dimensions.
Both `Camera` and later on `BarCodeScanner` would be refactored. You can see [this issue](https://github.com/expo/expo/issues/3612)

**Comment by bbarthec** [comment]
@zjw199011 would mind providing minimal app showcasing your issue via https://snack.expo.io?

**Comment by hpduy** [comment]
> I've created this wrapper...
> 
> cameraBarcodeScannerWrapper: {
> overflow: 'hidden',
> width: 260,
> height: 200,
> },

it is hidden but its hidden part is still scanning. is there any way to disable that area?

**Comment by bbarthec** [comment]
@hpduy currently there's no way to disable that hidden area from being scanned 😞

**Comment by elabayoub** [comment]
I had same issue, i've tried different solutions, but neither worked;

Here is what i did:

`npx expo install expo-camera`

Then in my tsx file:

```
<Camera
            style={[StyleSheet.absoluteFill, dynamicStyles.container]}
            ratio={'16:9'}
            barCodeScannerSettings={{
              barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
            }}
          onBarCodeScanned={shouldScan ? handleBarCodeScanned : undefined}
        >
</Camera>
```
Container style:

```
const dynamicStyles = useMemo(
    () => ({
      container: {
        width: dimensions.width,
        //width: dimensions.width * 1.7,
        //height: dimensions.height * 1.1,
        height: dimensions.height,
      },
    }),
    [dimensions]
  );
```

**Comment by lgbestel** [comment]
Hey there! Any suggestions for now? I just got the same issue in my expo-barcode-scanner camera. Cheers!

**Comment by Mynameisjohndev** [comment]
I managed to do it in a way that helped me, but I can't guarantee that it will be full screen for all devices

![image](https://github.com/expo/expo/assets/47609014/5638de6b-1e95-4a95-8b44-1920416f6a28)

source code:

```
import React, { useEffect } from 'react';
import Permissions from 'react-native-permissions';
import { StyleSheet, TouchableOpacity, View } from 'react-native';
import { BarCodeScanner } from "expo-barcode-scanner";


export default function App() {

  useEffect(() => {
    Permissions.request("android.permission.CAMERA");
  }, [])

  const handleBarCodeScanned = ({ type, data }) => {
    console.log({ type, data });
  };

  return (
    <View style={styles.container}>
    <BarCodeScanner
      type="back"
      onBarCodeScanned={handleBarCodeScanned}
      style={{
        width: "100%", height: "100%", padding: 0, transform: [
          {
            scale: 1.25
          }
        ]
      }}

    />
    <TouchableOpacity style={styles.button} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button:{
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "blue",
    position: "absolute",
    margin: 16,
    top: 0,
    right: 0,
  }
});

```
