### ISSUE TITLE
Request for documentation about security of code

### ISSUE THREAD

**Issue by anthony-tietjen** [expo/expo#338]
This is a request for documentation about the security of code that gets uploaded to the Expo server.

**Comment by jesseruder** [comment]
Can you elaborate? The bundled code is uploaded to S3 and publicly visible, we don't make any promises that it's a secret.

**Comment by anthony-tietjen** [comment]
@jesseruder Thanks for the follow up. Normally, development code and intellectual property stays within the corporate firewall. When I say to a manager: "Hey I'm uploading this code to a remote server." The next question on the manager's mind is going to be: "How secure is that? Does that mean the whole world can see our prototype? Everyone can access our code? Etc."

This is just a request to have something official in writing for people to see what happens with the code, who all can access it? Do they have to have links to it or can anyone randomly just pull up any one else's project?

Thanks

**Comment by anthony-tietjen** [comment]
(@brentvatne answered my question about this on Slack but thought it would be a good idea to have it documented somewhere. He recommended I write up a request here about it.)

Thanks all, keep up the great work!

**Comment by jesseruder** [comment]
You could send a PR to https://github.com/expo/expo-docs if you want to help out!

**Comment by dikaiosune** [comment]
Hi! I believe this is covered on the [How Expo Works](https://docs.expo.io/versions/v18.0.0/guides/how-expo-works.html#publishingdeploying-an-expo-app-in-production) docs page. Specifically:

> When you Publish an Expo app, we compile it into a JavaScript bundle with production flags enabled (minify, disable runtime development checks) and upload that bundle, along with any assets that it requires (see Assets) to CloudFront. We also upload your Manifest (including most of your app.json configuration) to our server.

> When publishing is complete, we’ll give you a URL to your app which you can send to anybody who has the Expo client.

I guess we could be more explicit about the public nature there, if you have some language you'd suggest please comment back and I'll reopen. Thanks!
