### ISSUE TITLE
[docs] useSegments() link to unexpected site

### ISSUE THREAD

**Issue by artiphishle** [expo/expo#33805]
## Summary

Link `useSegments()` points to a site where `useSegments()` isn't described.

## Reproduce

1. Visit **_{source}_**
2. Click: `useSegments()` link.

## Expectation

**_{target}_** site should be opened when clicking to `useSegments()` in **_{source}_** site

## Current behaviour

Click to `useSegments()` in **_{source}_** opens a site where `useSegments()` is not described.

### Link to the related docs page

**_source_**:
https://expo.github.io/router/docs/migration/react-navigation/navigation-container/

**_target_**:
https://docs.expo.dev/router/reference/typed-routes/

**Comment by amandeepmittal** [comment]
Hi @artiphishle, you are using an outdated documentation version of Expo Router as the source. It was deprecated at the time of Expo Router v3. See the Router API reference: https://docs.expo.dev/versions/latest/sdk/router/#api or Router guides for up to date information: https://docs.expo.dev/router/introduction/.
