### ISSUE TITLE
[SDK 52] - Splash screen image is not displaying

### ISSUE THREAD

**Issue by RilsonO** [expo/expo#33872]
### Minimal reproducible example

https://github.com/RilsonO/splash-proj-test

### What platform(s) does this occur on?

iOS

### Where did you reproduce the issue?

in Expo Go

### Summary

Once I have replaced the default images in the `assets` folder at the root of the project with the images I want my app to be built with, when I run the app again, the expected behavior is that while the bundle is loading, the splash screen displayed should be as configured in my `app.json` file, which references the `splash-icon.png` image in this case.

![Captura de Tela 2024-12-29 às 10 57 42](https://github.com/user-attachments/assets/34c1a26f-2c3d-4cd6-8e12-769758b24d45)

However, what we observe is that the image that appears is the `icon.png` image in the center of the screen. Interestingly, the background color configuration is applied, but only the image settings of the `splash` object are completely ignored in favor of the `icon.png` image.

![Captura de Tela 2024-12-29 às 11 00 18](https://github.com/user-attachments/assets/46986d07-c4e6-42f5-8df4-e63c7efb913d)

I configured the background color of my `splash` object with a green color and placed a `splash-icon.png` image that is completely different from the `icon.png` image to make it easy to distinguish which one is being displayed, as we can see in the attached images. And as we can see in the short video, the image that appears instead of the `splash-icon.png` image on the splash screen is indeed the `icon.png` image.

https://github.com/user-attachments/assets/dffb735a-72ec-49ba-92d0-cd1b3e8ed3c9

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - /usr/local/bin/node
      npm: 10.9.0 - /usr/local/bin/npm
      Watchman: 2023.10.09.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/rilsonoliveira/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
      Android SDK:
        API Levels: 31, 32, 33, 34, 35
        Build Tools: 30.0.3, 33.0.0, 34.0.0, 35.0.0
        System Images: android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.23 => 52.0.23 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by RilsonO** [comment]
But this is not a "customization", but rather the application of a configuration already established as standard in the "splash" object of the app.json file, which works up to version 51 of the SDK and which stopped working in version 52.
Do you mean that from version 52 of the SDK onwards the image configuration that is made within the "splash" object of the app.json file will no longer be applied?
If I downgrade to version 51 it works exactly as it should, with the exact same configuration and images as it was done.

**Comment by RilsonO** [comment]
> Hi, expo go does not support customising the splashscreen. It defaults to using the app icon. You can use development builds to have full control over the splashscreen


But this is not a "customization", but rather the application of a configuration already established as standard in the "splash" object of the app.json file, which works up to version 51 of the SDK and which stopped working in version 52.
Do you mean that from version 52 of the SDK onwards the image configuration that is made within the "splash" object of the app.json file will no longer be applied?

If I downgrade to version 51 it works exactly as it should, with the exact same configuration and images as it was done.

If so, what is the point of there still being a "splash-icon.png" image within the "assets" folder in the project root, if it will not be applied to the splash screen as referenced in the app.json file?

**Comment by sir-george2500** [comment]
I think this issue need to be reopen has I am currently facing the same problem ,like @RilsonO  what is the point of having a asset folder in the root of the project if it will not be applied to the screen as referenced in the app.json file?

**Comment by sir-george2500** [comment]
> Hi, expo go does not support customising the splashscreen. It defaults to using the app icon. You can use development builds to have full control over the splashscreen

also we are not customizing it should load the splash image which of course it not can you kindly explain further

**Comment by cruso003** [comment]
@alanjhughes The issue needs to be reopened, the app icon(icon.png) is not meant to be loading in place of the splash icon(splash.png/splash-icon.png).

It has absolutely nothing to do with a custom splash screen. 

even with a development build its not functioning properly

**Comment by alanjhughes** [comment]
@cruso003 @sir-george2500 @RilsonO  this was pointed out in the release notes of sdk 52 https://expo.dev/changelog/2024/11-12-sdk-52#known-limitations-of-splash-screen-implementation it is the first item. 

The splash-icon is a part of the template because the  default path we expect most projects to take is development builds. Expo go is a sandbox environment for learning and quick testing. It should not be used when developing a full project you intend to ship to the stores.

**Comment by lorddegenx** [comment]
im having same issue ever since upgrading to 52.

splash was working perfectly fine in 51 but now since upgrading it doesn't work

**Comment by cruso003** [comment]
> @cruso003 @sir-george2500 @RilsonO this was pointed out in the release notes of sdk 52 https://expo.dev/changelog/2024/11-12-sdk-52#known-limitations-of-splash-screen-implementation it is the first item.
> 
> The splash-icon is a part of the template because the default path we expect most projects to take is development builds. Expo go is a sandbox environment for learning and quick testing. It should not be used when developing a full project you intend to ship to the stores.

@alanjhughes I haven't tried with production build yet but its the same with deployment build

**Comment by alanjhughes** [comment]
@cruso003 i tried it earlier today and it's working fine. Please provide a reproducible example.

**Comment by nubwang** [comment]
This will add trouble to the novice, it is recommended to re-open this problem, or remind in the documentation!
