### ISSUE TITLE
White page on running expo-camera

### ISSUE THREAD

**Issue by SalAlba** [expo/expo#33897]
### Minimal reproducible example

https://github.com/albarudy/mobile-app/blob/reproduce-the-issue/app/(authed)/(tabs)/scan-ticket/index.tsx#L67C1-L68C1

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a standalone app

### Summary

I'm trying a make simple application scanning the QR code. I'm using  _expo-camera_. Everything is working on the browser.

The issue start when I create an APK of the application and install it on my physical device (Android) the application is frizzing and getting a **White scree** all the time, even I can't back to other pages.

I deleted the application, installed again  and rest the permission, and granted again still I'm facing the issue.

Any advice or help?  

📌  The steps: 
(1) Initial step , select the Scan tab.
![image](https://github.com/user-attachments/assets/7043ade6-2478-410b-b599-70f3aa4a8912)

(2) the issue ⚠️ ⚠️ ⚠️ 
![image](https://github.com/user-attachments/assets/aff50356-5bc4-434f-b444-26a25b05ebed)

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^52.0.0 => 52.0.23
      expo-router: ~4.0.13 => 4.0.15
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.5 => 0.76.5
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by alanjhughes** [comment]
Hi @SalAlba - The issue is your javascript is crashing because the `<pre>` tag is not supported in react native. You cannot use any html tags. When you remove the tag, it works without issue
