### ISSUE TITLE
MapView Won't render

### ISSUE THREAD

**Issue by baron816** [expo/expo#339]
First, the docs still say to use Components.MapView.
Second, I get a deprecation warning for View.propTypes.

Third, and most importantly, the MapView won't render at all. I copy the code directly from the docs into a fresh app and nothing shows up. Any ideas on what could be causing this?

**Comment by baron816** [comment]
Ok, I figured it out. I was nesting it inside a View component.

**Comment by zeeshanjan82** [comment]
So it does not work when nested inside other view so if we need to put elements above the mapview or place is inside other view how can we do that?
