### ISSUE TITLE
calling AsyncStorage jumps out of app in standalone .apk file

### ISSUE THREAD

**Issue by blueturtle13g** [expo/expo#3393]
I tried my app in development and production and it works correctly but when I produced a standalone app, it jumps out when using AsyncStorage

**Comment by sjchmiela** [comment]
Hey, @blueturtle13g!

What do you mean by _jumping out_? 🤔

**Comment by blueturtle13g** [comment]
Hi, my app restarts when I want to enter a name in a textInput and save it with asyncstorage!
it works perfectly in development mode and production mode on my expo but when I generated .apk file, it restarts my app and can't save anything.
this is my project: https://expo.io/@pia13g/bomb

**Comment by blueturtle13g** [comment]
> Hey, @blueturtle13g!
> 
> What do you mean by _jumping out_? 🤔
Hi, my app restarts when I want to enter a name in a textInput and save it with asyncstorage!
it works perfectly in development mode and production mode on my expo but when I generated .apk file, it restarts my app and can't save anything.
this is my project: https://expo.io/@pia13g/bomb

**Comment by sjchmiela** [comment]
Could you please provide us with the offending APK? Also, if possible, could you please try to reproduce an MVCE with Snack?

**Comment by sjchmiela** [comment]
I'll close this issue tentatively, I hope you have resolved your issue! 🙂
