### ISSUE TITLE
error during publish .apk on play store "you need to upload a valid APK file"

### ISSUE THREAD

**Issue by waqaramjad** [expo/expo#3395]
I build an APK using expo and I tested on mobile and it worked perfectly fine but when I try to upload it on play store it give me error that "you need to upload a valid APK file" can you tell me the possible reason for that error from the Google play store

**Comment by holczhauserSky** [comment]
any update on this?
I am facing the same issue

**Comment by brentvatne** [comment]
send your information to secure@expo.io.

**Comment by EvanBacon** [comment]
Closing as we don't have a repro or other method of debugging. If users are still encountering this issue please feel free to open a new issue with all of the required info. Also perhaps try checking the expo/expo-cli repo for more info.
