### ISSUE TITLE
app automatic disconnect with expo CLI 

### ISSUE THREAD

**Issue by waqaramjad** [expo/expo#3396]
i am using react native expo but I am facing issue in starting the app , when the app start and the expo stopped working after it builds complete and I have to again restart the complete package and then it work again only for 1 minutes or less time , also I have upgraded my node JS chrome 8. to 10 I think the issue is from Node.js side

**Comment by AdamJNavarro** [comment]
Hey @waqaramjad,

Would you mind creating an issue on the CLI repo here? https://github.com/expo/expo-cli/issues

Cheers,

Adam
