### ISSUE TITLE
Feature Request: logInWithPublishPermissions for Facebook API

### ISSUE THREAD

**Issue by Joshuabaker2** [expo/expo#34]
Would it be possible to add `logInWithPublishPermissions` for the Facebook integration to authorize additional permissions? Can see more about it with the Facebook SDK here: https://developers.facebook.com/docs/reference/ios/current/class/FBSDKLoginManager/

**Comment by dikaiosune** [comment]
Hi! We're tracking feature requests on Canny now. I [created one](https://expo.canny.io/feature-requests/p/loginwithpublishpermissions-for-facebook-api) for this there. Thanks!

**Comment by davibe** [comment]
@anp I do not understand how the publish permission is related to accountkit  (?)
