### ISSUE TITLE
Nothing happens when running npm test

### ISSUE THREAD

**Issue by cmacdonnacha** [expo/expo#3404]
### Environment

  Expo CLI 2.7.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

**package.json file:**

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node_modules/.bin/jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^31.0.2",
    "firebase": "^5.6.0",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-elements": "^1.0.0-beta4",
    "react-navigation": "^3.0.4"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^32.0.0"
  },
  "private": true
}
```

### Steps to Reproduce

1. Install jest-expo: `npm i jest-expo --save-dev`
2. Make changes to packages.json
3. Run `npm test`

### Expected Behavior

Tests run

### Actual Behavior

Nothing seems to happen. Tests do not run.

![image](https://user-images.githubusercontent.com/9777763/52166784-cbdda400-2709-11e9-818f-acd91f41293b.png)

### Reproducible Demo
N/A

**Comment by AdamJNavarro** [comment]
Hey @cmacdonnacha,

Thanks for the report. There's already an issue open about this: https://github.com/expo/expo/issues/3366 so I'll be closing this one. Please follow along there for updates.

Cheers,
Adam

**Comment by cmacdonnacha** [comment]
Great thanks, missed that one during my search.

**Comment by cmacdonnacha** [comment]
Oh, just noticed #3366 is also closed, has it been resolved?
