### ISSUE TITLE
babel-plugin-rewrite-require not respected during bundle

### ISSUE THREAD

**Issue by kparkov** [expo/expo#3409]
Since it is not possible to use native Node.js modules, I want to use the babel option to rewrite requires to a ported version.

However, trying to configure babel to use `stream-browserify` instead of the Node `stream` module does not work.

Specifically, I am trying to make [uport-connect](https://github.com/uport-project/uport-connect) work with expo in a manner similar to what is demonstrated in the [uport-connect-react-native](https://github.com/uport-project/react-native-uport-connect) project. This cannot be used directly in expo for various reasons, so I want to reimplement it in an expo version.

### Environment

```
Expo CLI 2.6.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

Target OS: mainly iOS

### Steps to Reproduce

- Install `babel-plugin-rewrite-require`.
- Configure `babel.config.js`:

```js
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      ["rewrite-require", { aliases: {
        "stream": "stream-browserify"
      }}]
    ]
  };
};
```

- Require `stream` through another module.

### Expected Behavior

Project compiles and uses `stream-browserify` instead of `stream`.

### Actual Behavior

During bundle, this error appears:

```
[10:02:27] The package at "node_modules\qr-image\lib\qr.js" attempted to import the Node standard library module "stream". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo
```

**Comment by plaa** [comment]
@kparkov Did you ever find a workaround? I'm facing the same issue.

**Comment by kparkov** [comment]
@plaa, I did not. In the end, I concluded that ejecting would be the only way to achieve it.

**Comment by bradleat** [comment]
Same problem here :/

**Comment by tsapeta** [comment]
Closing it as we don't support such functionality in the managed workflow. I'd recommend using bare workflow now, as the ExpoKit is no longer maintained.
