### ISSUE TITLE
Google Admob Support

### ISSUE THREAD

**Issue by deadcoder0904** [expo/expo#341]
[react-native-admob](https://github.com/sbugert/react-native-admob) support directly from Expo SDK

**Comment by btk** [comment]
Expo takes feature requests via Canny. 

Google admob support request is already made: 
https://expo.canny.io/feature-requests/p/google-admob

Also for some weird reason Expo has support for Facebook Ads SDK if you are into really low cpm.

**Comment by deadcoder0904** [comment]
Ok thanks 😄 

I was looking for Google Admob bcz I've used it before with `react-native-cli` so all I needed was just to put the ID as the account is already set up

**Comment by deadcoder0904** [comment]
Also there are a lotta FB terms & conditions like you can add only 1 ID per app which makes me not wanna use FB ADS 😭

**Comment by btk** [comment]
Yeah I was being sarcastic, Facebook Ads are not worth it. Only reason it is implemented in Expo is probably because Expo is backed by facebook.

**Comment by dikaiosune** [comment]
@deadcoder0904 please go vote on the AdMob feature request -- it's one of the main ways we prioritize new SDK additions right now.

@btk we list our current investors on our [About page](https://expo.io/about), but we don't have any backing from Facebook. As I recall, FB ads were pretty commonly requested when we added support for them and I seem to remember that the implementation was a bit easier than AdMob. We are still tracking AdMob support to add in the future, nothing political or conspiratorial about it :).

Giving this a close as we're already tracking the feature request on Canny. Thanks!

**Comment by k2glyph** [comment]
Please add support to google-ads

**Comment by deadcoder0904** [comment]
@k2glyph Its added in [SDK 21](https://docs.expo.io/versions/latest/sdk/admob.html). A simple example can be found [here](https://github.com/deadcoder0904/expo-google-admob).

**Comment by deadcoder0904** [comment]
Checkout my example man, it shows all ads.

**Comment by pahosler** [comment]
@deadcoder0904 yes I saw your example, thank you for it. So, do you have to you the interstitial admob to set the ADUNITID when you are only using a banner ad? I'll give that a try, maybe it's the secret sauce I've been missing...

**Comment by pahosler** [comment]
Sorry, totally my fault, missed some steps in the set up at adMob. Works great now!
