### ISSUE TITLE
Standalone Android FCM data notifications are not showing while backgrounded

### ISSUE THREAD

**Issue by rthernes** [expo/expo#3411]
### Environment

  Expo CLI 2.7.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.7.0

Android 9

### Steps to Reproduce

Sending FCM data messages do not show when the app is in the background. FCM notification messages show, but show twice (#3307). We're not using Expo's notification backend, but rather Notifications.getDevicePushTokenAsync()

Via AWS SNS console we send the following:

{
"GCM": "{ \"data\": { \"message\": \"This is a message.\" } }"
}

### Expected Behavior

When the app is backgrounded, a notification showing "This is a test message" should show.

### Actual Behavior

Nothing happens. It's as if the notification never happened.

Sending the following does work, however

{
"GCM": "{ \"notification\": { \"text\": \"test message\" } }"
}

**Comment by aniltirola** [comment]
you need to format the payload correctly, maybe these points from my forum post could help you:

https://forums.expo.io/t/solved-android-receive-data-from-a-fcm-push-notification-in-detached-app/12940/3

**Comment by rthernes** [comment]
Hi @aniltirola 
Part of the issue is that bare-bones notifications in iOS work fine (now that #3223 is fixed) , while Android data messages have all these undocumented required fields that cause the notification to not do anything or behave strangely. Bare-bones Android notification messages aren't handled properly either, and I was told to use data ones instead (#3307).

**Comment by awinograd** [comment]
I'm observing the same issue as @rthernes here.

Tried implementing the payload as described in https://github.com/expo/expo/issues/3307#issuecomment-459186582 by @esamelson, but the notification doesn't appear.

One caveat, is I'm not exactly sure what should be used as the `experienceId` for an app who's bundles I'm self hosting and building with turtle

**Comment by awinograd** [comment]
Ok, so after some deeper code spelunking I was able to get a background notification to be shown by expo notifications code (i.e. not the FCM library showing the notification).

Here's the payload I'm sending to the FCM HTTP v1 API:

```rb
{
  message: {
    data: {
      experienceId: "@anonymous/<SLUG_FROM_APP_JSON>",
      message: "Test message",
      title: "Test title",
    }
  }
}
```

**Comment by mczernek** [comment]
We've provided new notifications API recently, so I assume this issue is not valid anymore. Please feel free to comment on it if this is not the case.

Please refer [to this documentation page](https://docs.expo.io/versions/v38.0.0/sdk/notifications/) on how to use new notifications api on Android.

**Comment by papb** [comment]
Hi @awinograd!

> One caveat, is I'm not exactly sure what should be used as the `experienceId` for an app who's bundles I'm self hosting and building with turtle

I am facing exactly this issue. Looks like from your next comment that you figured out to use `@anonymous` to do it? May I ask where did you get this information from?

**Comment by awinograd** [comment]
Digging through source code! Don't have the specific lines saves however

**Comment by papb** [comment]
@awinograd It really worked! Thank you so much finding and sharing this solution!! :rocket: :rocket: :rocket: :rocket:
