### ISSUE TITLE
Expo Firebase Analytics requires all other optional Firebase modules to be installed

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#3412]
### Environment

Expo CLI 2.7.1 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: ^3.0.2 => 3.0.2
    npmGlobalPackages:
      expo-cli: 2.7.1

Target: iOS, Android, ExpoKit

### Steps to Reproduce

1. Create an Expo app
2. Eject to ExpoKit
3. Add expo-firebase-analytics using the directions here: https://www.npmjs.com/package/expo-firebase-analytics
4. Use analytics in any capacity, e.g.,

```
import firebase from 'expo-firebase-app';

firebase.analytics().setCurrentScreen('someScreen');

```

### Expected Behavior

No transpilation errors appear on the console and the app loads.

### Actual Behavior

The app fails to build with the error:
```
Unable to resolve "expo-firebase-auth" from "node_modules/expo-firebase-app/src/utils/getModuleInstance.js"
```

If you go to `getModuleInstances.js` and comment out the require for `expo-firebase-auth`, you'll just get an error for the next package that is missing.

### Reproducible Demo

https://github.com/llamaluvr/testfirebaseimports

To run repro:
1. Restore yarn deps
2. Restore cocoapods
3. `yarn start`
4. Run in Xcode

(note that this demo would not actually log analytics, base it doesn't have a google-services.plist and doesn't have the corresponding code in AppDelegate. However, just including the node modules is enough to reproduce the error.)

### Workarounds

- comment out unneeded modules in `getModuleInstances.js`, or
- add every expo-firebase node module to your project, even if you don't otherwise need it (you do not need to add them to the native projects for this workaround to work)

### Other notes

This was noted in this Expo forums thread: https://forums.expo.io/t/expo-firebase-auth-app-eject-and-sdk-32/18098/5

It's not isolated to Firebase Analytics or Expo 32 (I have the issue on an Expo 31 project), but seems to be with just about any Firebase module being used. It appears that by referencing `getModuleInstances`, every single Firebase package in that file needs be installed.

**Comment by EvanBacon** [comment]
I think the solution is just to make `expo-firebase-app` include every module. The bloat is really just when you include the native code. Unfortunately the bundler React Native uses (Metro bundler) tries to evaluate the code before it's called.

**Comment by patgoley** [comment]
I'm having this same issue. Is there any way we can make the `require`s lazy instead of bundling every module? Maybe by wrapping them in functions instead of getters?

Thank you for a sweet library, by the way.

**Comment by EvanBacon** [comment]
The current system is "lazy" but Metro compiles it all on Android. Working on a solution to this now.

**Comment by codeplaygoa** [comment]
I tried installing every module it requires, and now it gives me this error
ExpoFirebase core module was not found natively on iOS, ensure you have correctly included the ExpoFirebase pod in your projects 'Podfile' and have run 'pod install'.

Does it require me to eject from expo and use ExpoKit?

**Comment by vpontis** [comment]
> I tried installing every module it requires, and now it gives me this error
> ExpoFirebase core module was not found natively on iOS, ensure you have correctly included the ExpoFirebase pod in your projects 'Podfile' and have run 'pod install'.
> 
> Does it require me to eject from expo and use ExpoKit?

Yea, you need to be ejected to use Firebase modules other than Firestore.

**Comment by lenichols** [comment]
Any fix on this? I'm getting an error : ExpoFirebase core module was not found natively on iOS, ensure you have correctly included the ExpoFirebase pod in your projects 'Podfile' and have run 'pod install...

This error comes after installing everything from firebase as suggested above.

**Comment by tsapeta** [comment]
`expo-firebase-*` modules are no longer maintained by us, so I'm gonna close this issue. 
If you still want to use them, you can read this guide on how to use Firebase in Expo apps: https://docs.expo.io/versions/latest/guides/using-firebase/
