### ISSUE TITLE
Expo.js: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by matthewjj** [expo/expo#3422]
I've just tried to upgrade expo to 31.0.0 from 28.0.0 and i'm encountering this error when running the command `expo start`

`C:\xampp\htdocs\dseapp\node_modules\expo\build\Expo.js: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "C:\\xampp\\htdocs\\dseapp\\node_modules\\babel-preset-expo\\index.js")`

### Environment
```
 Expo CLI 2.7.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

here is my package.json dependencies

```
"dependencies": {
    "babel-plugin-transform-remove-console": "^6.9.4",
    "expo": "^31.0.0",
    "expo-cli": "^2.1.3",
    "lodash": "^4.17.11",
    "native-base": "^2.8.1",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-native": "^0.55.4",
    "react-native-account-manager": "^1.0.6",
    "react-native-chart-kit": "github:matthewjj/react-native-chart-kit-dse",
    "react-native-chart-x": "github:matthewjj/react-native-chart-x",
    "react-native-cookie": "^0.2.0",
    "react-native-error-reporter": "^1.0.7",
    "react-native-exception-handler": "^2.8.9",
    "react-native-keychain": "^3.0.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-pathjs-charts": "0.0.34",
    "react-native-pure-chart": "0.0.24",
    "react-native-sentry": "^0.37.1",
    "react-native-svg": "^6.4.1",
    "react-native-swipeout": "^2.3.6",
    "react-native-swiper": "github:matthewjj/react-native-swiper",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.6.0",
    "react-redux": "^5.0.7",
    "react-timer-mixin": "^0.13.4",
    "redux": "^3.7.2",
    "sentry-expo": "^1.9.0",
    "universal-cookie": "^3.0.4",
    "victory-native": "^0.18.2"
  },

```

**Comment by jmporchet** [comment]
Hey @matthewjj I might be shooting in the dark here but have you converted your .babelrc to the new babel.config.js format?
Here's a sample of ours:
```javascript
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo', 'module:react-native-dotenv'],
    plugins: [
      '@babel/transform-arrow-functions',
      '@babel/transform-react-jsx-source'
    ]
  };
};
```

Also, no devDependencies? Ours look like this:
```javascript
"devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/runtime": "^7.2.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^7.2.3",
    "babel-preset-expo": "5",
    "babel-runtime": "^6.26.0",
    [...]
}
```

**Comment by matthewjj** [comment]
Hi,
I've created the babel.config.js file and remove the .babelrc

Ive also added those dev dependencies like so:

```
"devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/runtime": "^7.3.1",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-preset-expo": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "jest-expo": "~28.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },

```

Now im getting this error, in Asset.js:

`C:\xampp\htdocs\dseapp\node_modules\expo-asset\src\Asset.js: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "C:\\xampp\\htdocs\\dseapp\\node_modules\\babel-preset-expo\\index.js")`

**Comment by jmporchet** [comment]
Are you using `npm` or `yarn`? If `npm`, try `rm -rf node_modules && yarn`

**Comment by matthewjj** [comment]
Hi, I use NPM

I've tried the command you suggested but I'm still getting the same error message

**Comment by dalcib** [comment]
You need to use babel-core version 7.0.0-bridge.0

https://stackoverflow.com/questions/51455882/babel7-and-jest-configuration

**Comment by matthewjj** [comment]
Dev dependencies now reads:

```
 "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/runtime": "^7.3.1",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-preset-expo": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "jest-expo": "~28.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },
```

still getting the same error message of Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

**Comment by olegreznichenko** [comment]
Try to use yarn
I had a lot of caches problems with npm

**Comment by tsapeta** [comment]
The SDK version that this issue refers to is already not supported and I believe it's been fixed already. Feel free to open a new issue if I'm wrong tho 🙂
