### ISSUE TITLE
Add ios -> Pods folder to .gitignore

### ISSUE THREAD

**Issue by JonnyBurger** [expo/expo#3425]
When ejecting to ExpoKit, the `Pods` folder is not in .gitignore.
By default there will be 17'000 uncommitted files after ejecting.
It would be a nice UX improvement if `ios/Pods` is in the `.gitignore` template by default or if it gets added upon ejecting.

### Environment
Any Environment

### Steps to Reproduce

(Write your steps here:)

1. Run `expo eject`
2. Select 'ExpoKit'
3. Run `cd ios && pod install`

### Expected Behavior

Pods are ignored by Git.

### Actual Behavior

Pods are not ignored by Git.

**Comment by sjchmiela** [comment]
Hey, @JonnyBurger!

Actually, the debate whether to commit `Pods` folder to Git or not is open and everyone is invited to answer this question on their own. 🙂 See official CocoaPods guide for more information:

[“Should I check the Pods directory into source control?” in “Using CocoaPods guide”](https://guides.cocoapods.org/using/using-cocoapods#should-i-check-the-pods-directory-into-source-control)
