### ISSUE TITLE
Location.getCurrentPositionAsync() Takes 10+ seconds after upgrading to SDK 31

### ISSUE THREAD

**Issue by obibring** [expo/expo#3433]
### Environment

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v8.10.0/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^31.0.1 => 31.0.7 
      @types/react: ^16.7.13 => 16.7.18 
      @types/react-native: ^0.57.18 => 0.57.27 
      expo: ^31.0.0 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.6.14
```

This bug is happening on iOS in **standalone app only**

### Steps to Reproduce

I upgraded my app to SDK V31.  After noticing severly degraded performance related to location based services, I started profiling to see what was going on. The following consistently takes 10,100 ms to complete:

```js
import { Location } from 'expo';

async function getLocation() {
  const start = Date.now();
  await Location.getCurrentLocationAsync();
  console.log(Date.now() - start); // consistently around 10,100ms
}
```
This issue **only** happens in the standalone production version of my app. In development, there are no issues. I'd be happy to provide more information, but not sure what more to include given that this singular invocation is what's causing problems.

**Comment by ezrra** [comment]
+1

**Comment by obibring** [comment]
Any updates on this? I upgraded to SDK 32 and this is still an issue. The initial logged-in screen of my app defers rendering until it has read the user's location, and as a result of this bug my app is being rejected by Apple.

**Comment by obibring** [comment]
I figured out how to prevent the issue. It's related to the `accuracy` option. See discussion [here](https://forums.expo.io/t/location-getcurrentpositionasync-takes-10-seconds/19714/4)

**Comment by croaky** [comment]
I bumped into this issue as well:

* Expo SDK v32
* iPhone X
* Expo Client
* Expo managed app
* `Location.Accuracy.High` consistently takes 10s + a hundred milliseconds or so
* `Location.Accuracy.Balanced` is less than 500ms

**Comment by sbichenko** [comment]
For me this happens on both the Expo Client and the standalone app. The workaround for me was not to pass the `accuracy` parameter to `getCurrentPositionAsync`: this way it becomes much faster (1-2 s).

**Comment by avinashlng1080** [comment]
Hello Team,
When do you think this issue will get fixed?
