### ISSUE TITLE
Documentation doesn't mention OTA limitation: can't change notification icon

### ISSUE THREAD

**Issue by ailinca** [expo/expo#3435]
### Environment

 Expo CLI 2.4.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.4 - C:\Users\ailinca\AppData\Roaming\npm\yarn.CMD
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/tpa-feccd220-2a1c-4b2a-a1ee-0baeb12df04b.tar.gz

Target:
Android

Expo version: 31

### Steps to Reproduce

1. Create a dummy app but don't set the **notification** attribute in _app.json_
2. Make sure to implement a way of getting the Expo Push Notifications Device Token after the app is installed on devices ( I used Sentry to log it ) 
3. Build the Android .apk using the expo build:android
4. Download and install the .apk on an Android device
5. Retrieve the Expo Push Notifications Device Token ( via Sentry, adb logcat etc. ) - will be needed to test the notification icon
6. Use the Expo Push Notifications tool to send a notification to the Android device
7. Notice the Expo logo appearing as icon
8. Add the following object to the _app.json_: 
`"notification": {
      "icon": "app/assets/images/splash-logo-loading_96x96.png",
      "color": "#EB0000"
    },`

**Note**: the image specified is a grayscale 96px x 96px with transparent background png. 
9. Run _expo publish_
10. Restart the app ( so that the OTA updates are downloaded ) 
11. Send a new notification to the device

### Expected Behavior

Upon receiving a push notification, I expect the new icon to be displayed in the top left corner of the device, in the status bar, and to also appear in the notifications tray.

### Actual Behavior

After restarting the app, upon receiving a push notification, the expo icon still appears both in the status bar and in the notifications tray. 

## Note 

After creating and deploying a new build, the icon is indeed updated.  If this is the intended behavior, please update the Expo Docs OTA limitations to also include the **notification** attribute. I can happily make a PR for it, if agreed upon.

**Comment by sjchmiela** [comment]
Hey, @ailinca! You are right in your note, unfortunately it's not possible to update the notification icon over the air. If you could make a PR with this change, that would be awesome! 🎉

**Comment by ailinca** [comment]
Thank you, @sjchmiela for the prompt response. I will make the PR today.
