### ISSUE TITLE
React Context as per Context documentation does not work in Expo

### ISSUE THREAD

**Issue by badbod99** [expo/expo#3438]
### Environment

Running within Snack, latest Expo client.  Expo version v32.0.0.

### Steps to Reproduce

1. Create a Context object using `React.createContext` (within separate file)
2. Import Context object within your component file
3. Create Context.Provider object wrapping custom component.
4. Set currentContext of the component using either `myComponent.currentContext` or `static currentContext`
5. Access `this.context` anywhere in your component class, you get `{}`

### Expected Behavior

Context should be available within component after contextType set as per [React Context documentation](https://reactjs.org/docs/context.html).

### Actual Behavior

`this.context` is `{}` unless Context.Consumer is used.

### Reproducible Demo

Demo produced based on [React Context documentation](https://reactjs.org/docs/context.html) modified for React Native.
https://snack.expo.io/@badbod99/calm-candies

**Comment by brentvatne** [comment]
`contextType` was added in react@16.6, we'll likely be updating to that with our next SDK release but until then you need to use `Context.Consumer` instead

**Comment by mohmdalfaha** [comment]
@brentvatne Does the new release Expo v33 support contextType?
