### ISSUE TITLE
Tensorflow or Keras support

### ISSUE THREAD

**Issue by morenoh149** [expo/expo#344]
Hello, I ran into this nice video https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/ detailing how to add a tensorflow model to an app. I'm wondering what needs to be done to get expo to do similar things.

**Comment by dikaiosune** [comment]
Hi! We'd probably need to include native code in the SDK for this. Can you open a feature request at https://expo.canny.io? Thanks!

**Comment by morenoh149** [comment]
done https://expo.canny.io/feature-requests/p/tensorflow-or-keras-support
