### ISSUE TITLE
Facebook Native Ads Not Showing <AdIconView /> Without <AdMediaView /> 

### ISSUE THREAD

**Issue by blntylmn** [expo/expo#3442]
### Environment
```

Expo CLI 2.9.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0-next.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.9.0
```

No icon fetching (or fetching but not showing) if you not include `<AdMediaView />`
Is this expected behavior ?

### Steps to Reproduce

1) Just use expo init and create a new expo project wit CLI..
2) Follow the instructions on expo document (https://docs.expo.io/versions/v32.0.0/sdk/facebook-ads/)
3) Remove `<AdMediaView />`

### Expected Behavior
There should be a logo (`<AdIconView />`) without `<AdMediaView />` so I can create a native banner ad.

### Actual Behavior

There is no logo (`<AdIconView />`) when I not include `<AdMediaView />`

### Reproducible Demo

Just use expo init and create a new expo project wit CLI..

**Comment by tsapeta** [comment]
SDK32 is no longer supported and a lot of time has passed, so let me close this issue. Feel free to open a new one if you're still facing it in the latest SDK 🙂
