### ISSUE TITLE
Videos in Flatlist do not load and native controls of the video 's aren't working as aspected on Android.

### ISSUE THREAD

**Issue by thekrol01** [expo/expo#3443]
### Environment

Expo CLI 2.8.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.8.0

Apps target Android. I tested with Galaxy A 3 (2017) Android v 8.0, Samsung Experience versie: 9.0.

### Steps to Reproduce

1. Import a Flatlist from react-native. Connect the flatlist to a datasource with video uri's.
2. Render the items of the flatlist with the Video component from Expo. 
3.Navigate (with react-navigation)  from another page to the page with the Flatlist with video 's.

### Expected Behaviour

 I expect the flatlist to show all Video 's. I expect that I can start and stop the video 's with nativecontrols. I expect that when I navigate away from the Flatlist and navigate to the Flatlist again that the video 's are shown like the first time I navigated to the page with the Flatlist.

### Actual Behaviour

Test with Android device:Galaxy A 3 (2017) Android v 8.0, Samsung Experience versie: 9.0.
  - When I navigated the first time to the page with the Flatlist (with 3 Video 's) all video 's are shown and are loading. 
- I notice that the all video 's are shorter (about 0.01 )on the Android device  then when i test the same code on my Iphone (5s Ios 12.1.2)
- When I stop and start a video in the flatlist with native controls I can't start the video again. I can jump forward and backward, but I don't see the video moving. The playbutton doesn't react at all.
When I navigate away from the page with the Flatlist and navigate back again  the video 's aren't shown. Only  Empty videos with native control buttons.

All the above that doesn't work on the Android Galaxy A 3 device. It works perfect as aspected on my iPhone 5s device..

### Screenshots
First time navigation [two videos are loaded]:
![photo-2019-02-06-22-07-39 1](https://user-images.githubusercontent.com/34987076/52373965-58ff6080-2a5c-11e9-965d-1ffb375ea193.jpg)
Second time navigation [same two videos are not loaded]
![photo-2019-02-06-22-07-39 2](https://user-images.githubusercontent.com/34987076/52373985-64528c00-2a5c-11e9-99fb-2c48369773c7.jpg)
Another second time navigation [same two videos are not loaded]
![photo-2019-02-06-22-07-39](https://user-images.githubusercontent.com/34987076/52373993-6b799a00-2a5c-11e9-81a0-98d0ba60349d.jpg)

### Reproducible Demo
(https://snack.expo.io/@thekrol/videosinflatlist)

The difference in behaviour can be seen when opening the project with an iPhone and an Android.
Same videos on Android are a fraction shorter then on Ios. Also not all videos are loading on Android. When navigating back and forth native controles (sometimes) stop working on Android.

**Comment by thekrol01** [comment]
I also added the reproducible Demo. Don't see it in the Issue. So here it is. 
https://snack.expo.io/@thekrol/dmlkZW
Open the snack with and Android and Iphone to see the difference in behaviour.

**Comment by thekrol01** [comment]
I have done some additional research about expo videos in a flatlist. I have noticed that the problem is platform independent and occurs after navigating back and forth to the flatlist with the video's, Mostly around 10 times navigating back and forthwith react-navigation to the flatlist stops showing the video 's. Also manualy mounting unmounting of the AV component does not solve the problem. I have tested this with two video in the flatlist both refering to: http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4
(Expo: tunnel, production mode).

**Comment by thekrol01** [comment]
With just one video in the flatlist the video (AV component) component works as aspected. Perhaps the  workaround would be to manually unload the video when scrolling. So that always only one video is manually loaded in the flatlist.

**Comment by icorradi** [comment]
+1

**Comment by IjzerenHein** [comment]
Hi! I've tried to reproduce the issue reported here but was unable to with the latest Expo client and SDK 37 (snack I used: https://snack.expo.io/kdiCo_FQC)

Various issues have been fixed with react-navigation and expo-av as well. I'll close this issue as we think it has been resolved. Feel free to reopen with additional reproduction details if the problem this exists.

**Comment by brunolcarlos** [comment]
I have a similar problem, sometimes after 10, 20 scrolling the videos stop to work.

**Comment by siddharth-kt** [comment]
@brunolcarlos did you got any workaround ?

**Comment by brunolcarlos** [comment]
> @brunolcarlos did you got any workaround ?
> 

Only with Big Flat List package

**Comment by Ianduha13** [comment]
+1 here, having the same issue
