### ISSUE TITLE
Expo Firestore - all dates and timestamps in queries are null 

### ISSUE THREAD

**Issue by JamesMcIntosh** [expo/expo#3446]
I just upgraded from Expo31 with Firebase 1.5 rc5 to Expo32 and Firebase 2.0.0.
Firestore is now sending back all timestamps as null.
I have checked the datastore and they have been saved correctly.
Target app iOS

@EvanBacon Could it be related to https://github.com/invertase/react-native-firebase/issues/1869 ?

### Expected Behavior

The timestamp / dates value

### Actual Behavior

Queries with timestamps / dates return null values

### Environment

  Expo CLI 2.8.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.4
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.8.0

**Comment by JamesMcIntosh** [comment]
I have tested on Android and it works correctly so may be related to Firebase/Firestore pod version.

The version is the Podfile.lock is ```Firebase/Core (5.16.0)``` the same problamatic version as listed in the related issue in the description.

**Comment by JamesMcIntosh** [comment]
From the release notes https://firebase.google.com/support/release-notes/ios

Cloud Firestore
Breaking change: *The areTimestampsInSnapshotsEnabled setting is now enabled by default.* Timestamp fields that read from a FIRDocumentSnapshot are now returned as FIRTimestamp objects instead of NSDate objects. Update any code that expects to receive a NSDate object. See the reference documentation for more details.

**Comment by JamesMcIntosh** [comment]
Explicitly specifying the dependency in the Podfile seems to be enough to fix the problem temporarily.

The full fix will be to update the ExFirebaseFirestore project to use the new timestamps.

**Comment by EvanBacon** [comment]
Working on a rewrite with some of these revisions. Unfortunately Firebase updates with braking changes too often for me to keep up. Enforcing a lower version is probably the best solution for now.

**Comment by yashlinmaistry** [comment]
@JamesMcIntosh 

Hey James 

This is my current podfile. Do I need to put  pod 'Firebase', '5.15.0' in addition to what I have or replace EXFirebaseApp

```
 pod 'EXFirebaseApp', 
    path: '../node_modules/expo-firebase-app/ios'

  pod 'EXFirebaseFirestore',
    :path => "../node_modules/expo-firebase-firestore/ios"

  pod 'EXFirebaseAnalytics',
    :path => "../node_modules/expo-firebase-analytics/ios"
 pod 'EXFirebaseAuth',
    :path => "../node_modules/expo-firebase-auth/ios"
```

**Comment by JamesMcIntosh** [comment]
@yashlinmaistry Yes, that's what I did.

**Comment by tsapeta** [comment]
`expo-firebase-*` modules are no longer maintained by us, so I'm gonna close this issue. 
If you still want to use them, you can read this guide on how to use Firebase in Expo apps: https://docs.expo.io/versions/latest/guides/using-firebase/
