### ISSUE TITLE
Barcode Scanner does not stop scanning

### ISSUE THREAD

**Issue by nikoootine** [expo/expo#345]
Just like what aeamaea raised here:
https://forums.expo.io/t/barcode-scanner-component-behaviour-in-snack/1218

The scanner doesn't stop scanning even when a qr/bar code has already been detected. There should be a way to stop this

**Comment by dikaiosune** [comment]
Hi! Are you seeing this on iOS or Android? What Expo version, OS version?

**Comment by joaohkfaria** [comment]
I'm having the same problem. There's no way to pause the scanner? (maybe a prop enabled: true/false)

OS: Android 7.1.2
Expo: 18.0.4

**Comment by brentvatne** [comment]
see: https://forums.expo.io/t/turning-off-barcodescanner/1698

**Comment by terribleben** [comment]
Not sure if this is resolved, leaving open

**Comment by joaohkfaria** [comment]
I don't think that's the best solution, but it works :)

**Comment by madhums** [comment]
Turning off the barcode scanner doesn't seem like the solution. The `onBarCodeRead` callback should be called once per barcode. But right now, it is being called as many times any barcode is read.

**Comment by madhums** [comment]
As a workaround, I added a bit of delay. Works well. But it should be handled in the `onBarCodeRead` method IMHO. 

```js
function delay(time) {
  return new Promise(function(resolve, reject) {
    setTimeout(() => resolve(), time);
  });
}

class Scanner extends Component {
  state = {
    read: null
  };

  // This get's called multiple times
  onBarCodeRead = async obj => {
    // Workaround is to add a delay and check if that was already scanned
    await delay(500);
    if (this.state.read == obj.data) return;
    this.setState({ read: obj.data });
    // Whatever you wanna do with the scanned barcode
  };

  render() {
    return (
      <View style={styles.container}>
        <BarCodeScanner
          onBarCodeRead={this.onBarCodeRead}
          style={styles.barcodeContainer}
        />
      </View>
    );
  }
}
```

**Comment by cseufert** [comment]
I disagree, sometimes you want to only show information while the barcode is onscreen (eg an overlay that draws a box around the code), or have the user scan the barcode for a period of time to reduce accidental scans. Ideally, it would be great to have a property like readOnce that filters the repeated reads when true, but can still be set to false to get a read for every frame.

**Comment by Inlesco** [comment]
@dikaiosune hello there! I'd like to ask - are there any plans to add some features to the BCS component?

Like the ones mentioned above - immediate scanning, timed scanning (while the scanned entity must be on-screen for X seconds, etc.), ability to avoid scan events bubbling, etc.

i'm sure many of us would love to hear more on this ;) Thanks!

**Comment by dikaiosune** [comment]
cc @aalices about barcode scanning features ^^

**Comment by aalices** [comment]
SDK 23 will make BCS use `Camera` component where the `OnBarCodeRead` prop is optional - it will only enable scanning when set, so basically if one wants to stop the scanning process but have the component still visible they set the prop to `undefined` and scanning stops. Does it sound okay? Or is there still something you guys would suggest?

**Comment by joaohkfaria** [comment]
@aalices I think that's pretty good for me.

**Comment by glodfinch** [comment]
As a temporary fix I found using lodash's debounce the simplest method, in my contstructor:
`this.handleBarCodeRead = _.debounce(this.handleBarCodeRead.bind(this), 500, {leading:true, trailing:false});`

This is similar to the method of adding delay but worked best for me, where I was closing the screen with the camera after the first scan.

**Comment by jaggerwang** [comment]
@aalices Set onBarCodeRead to `undefined` not stop scan in v23.

```
...
  onBarCodeRead(code) {
    this.camera.onBarCodeRead = undefined;
    Alert.alert(
      '扫描到二维码',
      code.data,
      [
        {text: 'OK', onPress: () => this.camera.onBarCodeRead = this.onBarCodeRead.bind(this)},
      ]
    );
  };
...
```

**Comment by aalices** [comment]
@jaggerwang you have to set it as a prop, so for example:

```
state = {
  onCodeRead = this.OnCodeRead
};
...
<Camera onBarCodeRead={this.state.onCodeRead} />
...
onCodeRead(result) {
  ...process result...
  this.setState({
    onCodeRead: undefined
  });
}
```

Please let me know if that helps.

**Comment by jaggerwang** [comment]
@aalices Thanks! By doing as your suggestion, the scan stopped, but the app crashed when I confirmed the alert dialog.

```
...
  onBarCodeRead(code) {
    let prev = this.state.onBarCodeRead;
    this.setState({onBarCodeRead: undefined});
    Alert.alert(
      '扫描到二维码',
      code.data,
      [
        {text: 'OK', onPress: () => this.setState({onBarCodeRead: prev})},
      ]
    );
  };
...
```

**Comment by aalices** [comment]
@jaggerwang what exactly happens? Maybe try to bind the function you pass to the initial state?

**Comment by jaggerwang** [comment]
@aalices Already did.

```
...
  constructor() {
    super();
    this.state = {
      flash: 'off',
      autoFocus: 'on',
      type: 'back',
      whiteBalance: 'auto',
      onBarCodeRead: this.onBarCodeRead.bind(this),
    };  
  }
...
```

**Comment by aalices** [comment]
So what actually happens? A crash without an error or maybe something is logged ?

**Comment by jaggerwang** [comment]
Please see the above comment.

**Comment by jaggerwang** [comment]
And it's fine if I remove the Camera component and show the scan result.

**Comment by aalices** [comment]
Are you using iOS ? If so I'll fix this very soon - checked this myself and yeah - it crashes, sorry for that. Works fine on Android for me

**Comment by jaggerwang** [comment]
@aalices Yes, I fixed it by remove camera component when found qrcode.

**Comment by lukewendling** [comment]
I'm seeing a related issue, on expo v23.... BCS correctly scans a couple of bar codes (as expected) but after a couple of scans, the onbarcoderead handler is no longer called, even when I focus on another image. I can get it working again by changing orientation. Then it works for another cpl of scans, but again onbarcoderead is no longer triggered after that. Is there a recommended react mounting/unmounting routine I should use? I was planning to have the camera (BCS) component mounted alwasy and update an overlay View with each scan's results (this is a movie ticket scanning app)... but it sounds like i might be better off showing another component, unloading the camera component, and re-mounting each time.

**Comment by peniqliotuv** [comment]
@lukewendling I had a similar issue: I noticed this was an issue with the Expo app. When I would exit out of my app and try to scan the QR code displayed by the Expo packager, the barcode scanner wouldn't even pick up that code. I would usually just clear all apps on my device and rescan the QR code to get everything working.

**Comment by oswaldano** [comment]
I resolved this by using the react-native-display library to unrender the component when code is scanned the first time. This works for me because I navigate away from the scanner screen immediately a code is scanned.

**Comment by Just01** [comment]
Yes! I've done it!

**Comment by Just01** [comment]
### Yes! I've done it!
I tried many ways, even handle parsing data, and show Activity indicator instead of BarCodeScanner, but there was no result.
So, i have a BarCodeScanner which onBarCodeRead parse data and navigate to another screen with data result.
After i navigated, onBarCodeRead did not stoping because it was in stack navigation!
In my handleBarCodeScanned method of Bar Code Reading, i did next:
```javascript
handleBarCodeScanned = ({ data }) => {
    this.setState({ parsedData: data })
    if (this.state.parsedData) {
      this.props.navigation.pop()
      this.props.navigation.navigate('scannerResult', { data })
    } else {
      this.setState({ parsedData: data })
    }
  }
```
### And it works! 
It is so simple and stupid, but works!

**Comment by debotos** [comment]
`
state = {
		scannedItem: {
			type: null,
			data: null
		},
		modal: false
	}
renderSuccessAlert = (title, message) => {
		Alert.alert(
			title,
			message,
			[
				{
					text: 'No',
					onPress: () => this.setState({ modal: false }),
					style: 'cancel'
				},
				{ text: 'Yes', onPress: () => this.handleSuccess() }
			],
			{ cancelable: false }
		);
	};

	handleSuccess = () => {
		const { type, data } = this.state.scannedItem;
		this.setState({ modal: false });
		this.props.setScanComplete(true, data);
	};

	onBarCodeRead = async ({ type, data }) => {
		if (this.state.modal) return;
		Vibration.vibrate();
		this.setState({ scannedItem: { data, type }, modal: true }, () => {
			this.renderSuccessAlert('Success!', 'Do you want to go next step?');
		});
	};`

Using an alert **Alert** I handled the situation.
