### ISSUE TITLE
Make TaskManager work outside of managed workflow

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#3453]
As stated in [TaskManager's readme](https://github.com/expo/expo/blob/master/packages/expo-task-manager/README.md), right now it doesn't support vanilla React Native apps. We'd like to make it work outside of Expo.

Creating this issue to keep track on the progress 😄 

@esamelson's note from #6516:

> Partial step of #6513 
>
> These two modules need to be extracted into unimodules while keeping the implementation and API the same as much as possible.
>
> Some extra setup during installation will probably be necessary for these modules. We want to aim to keep this as lightweight as we possibly can. If the PR size or installation process for the modules are getting to be out of hand, please pause work and check in with someone else.
> 
> Since we expect these PRs to be somewhat larger in scope than other unimodule extractions, please be sure to structure the PRs and code in a way that makes them as easy as possible to review!

**Comment by grigored** [comment]
Thanks for working on this, greatly appreciated. Any idea about when to expect background location to work on a detached app?

**Comment by Sukumar-Abhijeet** [comment]
When will be the task manager available for bare apps ??

**Comment by brentvatne** [comment]
> When will be the task manager available for bare apps ??

focusing on sdk 33 right now, @tsapeta may have time soon after sdk 33 to circle back to this

**Comment by Sukumar-Abhijeet** [comment]
Can i use any alternate package for this TaskManager ??

**Comment by brycedbjork** [comment]
+1

**Comment by samih7** [comment]
> When will be the task manager available for bare apps ??

+1000 😄

**Comment by littlehome-eugene** [comment]
Being available for bare apps  means we could use TaskManager on a project where we we do `react-native init`?

**Comment by IanKemp** [comment]
Pushed from 33, to 35, to 35, now to 36... any possibility this will actually get done sometime this century?

**Comment by tsapeta** [comment]
@IanKemp I'm sorry you need to wait for it, but Expo is a big open source product where the queue of tasks to do is always full - I tried to prioritize this task but I've been involved in other, more important tasks during that time which fully absorbed my bandwidth. Please, be patient as it is still on our roadmap. If you can't wait, your pull requests are always welcome.

**Comment by IanKemp** [comment]
@tsapeta My comment was in no way directed at you specifically, or the team. It's more around the mixed messages Expo is giving out. 

To explain: my project is forced to use eject because we (a) require React Native modules not available in Expo (b) require Expo modules not yet available for RN (like `TaskManager`). The work to port TaskManager to RN has not been done, yet if I go to https://docs.expo.io/versions/v34.0.0/bare/customizing/ it has an ominous notice:

> Note: We don't recommend the ExpoKit eject option, it is less flexible and we will stop supporting it in the near future.

Is "the near future" before or after all Expo modules are ported to RN? If before, then you have essentially locked my project to the last version of Expo that will support ejecting. For obvious reasons, this possibility concerns me. When I see no progress on porting a module that my project depends on, it concerns me even more.

**Comment by tsapeta** [comment]
I don't think the messages we're giving out are mixed - maybe not fully clear instead 😉 
Yes, we want to deprecate `ExpoKit` but before we do this, we need to, among other things:
- create unimodules for every Expo module (OTA updates and notifications are the main ones that we're working on right now)
- add React Native provider to TaskManager

So, don't worry, we won't drop ExpoKit support before this task is done. Also, we'll probably still give you a way to use ExpoKit for a few releases even after we say it's deprecated - mostly because there is still some work ahead of us to remove ExpoKit internally and as long as we need it internally it still needs to exist.

**Comment by tsapeta** [comment]
^ Hopefully, this is the last time when we're postponing this task to the next SDK 😉

**Comment by IanKemp** [comment]
@tsapeta Many thanks for the clarification, that has put my mind at rest somewhat.

**Comment by tsapeta** [comment]
Closing this issue - we've merged a PR adding TaskManager support for bare workflow - it will be out with the next release.
