### ISSUE TITLE
Ads from Google Ad manager not showing in Android

### ISSUE THREAD

**Issue by davidcort** [expo/expo#3455]
**Environment**
Expo CLI 2.10.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.4
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.10.0

**Steps to Reproduce**

Very simple:
1. expo init myNameApp
2. Edit App.js
3. expo start
4. Open Expo App 

**Expected Behavior**

The banner should show in iOS Emulator, Android Emulator, iOS and Android (Real devices)

**Actual Behavior**

The Banner only showing in iOS Emulator and iOS real device  :(
In Android simulator only add "Test Add" in Real Devices not showing.

<img width="744" alt="captura de pantalla 2019-02-07 a la s 18 15 47" src="https://user-images.githubusercontent.com/6045573/52451403-77b93200-2b04-11e9-836d-e7271d2cea73.png">

**Reproducible Demo**
https://snack.expo.io/@davidcort/issue-admob-android

**Comment by Szymon20000** [comment]
When I use your slack with adUnitID from our [example](https://docs.expo.io/versions/v32.0.0/sdk/admob/) and everything seems to work fine. Maybe something is wrong with your adUnitID.

**Comment by davidcort** [comment]
> When I use your slack with adUnitID from our [example](https://docs.expo.io/versions/v32.0.0/sdk/admob/) and everything seems to work fine. Maybe something is wrong with your adUnitID.

But is your example a banner from Google Ad ? Because the banners from Admob works well but this issue is only with Google Ad Manager. Please, keep this in mind.

**Comment by Szymon20000** [comment]
Ok, I was able to reproduce the issue.  I'm got the following error while running your snack: [ERROR_CODE_NO_FILL](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_NO_FILL). After I changed your adUnitId to '/6499/example/Banner' snack started to work properly.

**Comment by kesha-antonov** [comment]
Same here
Just blank space

**Comment by tsapeta** [comment]
There hasn't been any activity here for over a year and we haven't received any similar reports so I'm closing it. Feel free to chime in here if you're still encountering this in the most recent SDK 🙂
