### ISSUE TITLE
React Native developer menu shows up when shaking if two-finger gesture is selected

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3456]
- Sign in to your account in Expo client
- Go to profile screen and tap options
- Switch to two finger gesture
- Open an app that's in development locally
- Shake your device
- Default React Native menu opens

![image from ios](https://user-images.githubusercontent.com/90494/52452369-982ebf80-2af7-11e9-972c-7d79e26ce493.png)

**Comment by nghiaoi3** [comment]
how can AVOID this menu if I use "shake gesture" in my app (I want to test my app's functions)?

**Comment by tsapeta** [comment]
Hey @nghiaoi3, sorry for late response, I was just looking on the oldest issues and found this one 🙂 
Recently we pushed an update to iOS App Store with a new three-finger gesture to bring up the dev menu and the option to turn each of them off. Just go to Profile and then Options and select the gesture you want to be enabled.

Closing this issue as it's been fixed already.
