### ISSUE TITLE
Expokit, error when running react-native run-android

### ISSUE THREAD

**Issue by foxdreamstudio** [expo/expo#3460]
hi @all, i need your help. i have create apps using expokit, and i have add library onesignal. the problem is when im execute react-native run-android, theres error like this
![screen shot 2019-02-08 at 5 54 47 pm](https://user-images.githubusercontent.com/37882679/52474646-a3ebb600-2bcb-11e9-8db0-68ba61f1eb8d.png)

i have been looking the solution in internet but there's no any solution can solve it.
please anyone help me. thanks.

this the gradle file
[Android_build.gradle.txt](https://github.com/expo/expo/files/2844794/Android_build.gradle.txt)
[App_build.gradle.txt](https://github.com/expo/expo/files/2844795/App_build.gradle.txt)

**Comment by gsunsnackv** [comment]
According to https://docs.expo.io/versions/v32.0.0/expokit/expokit/#4-android-build-and-run you should be running `./gradlew installDevKernelDebug` . Try that

**Comment by foxdreamstudio** [comment]
@gsunsnackv , i have do that, when i execute "./gradlew installDevKernelDebug" , the resuls is success, but when i execute "react-native run-android" the result error still happen. theres any solution please?

**Comment by AdamJNavarro** [comment]
Hey @foxdreamstudio,

As Gordon mentioned you have to use that command. We do not support react-native run-android as state in our docs.

Cheers,
Adam
