### ISSUE TITLE
Builds stuck in "Queue" for over an hour.

### ISSUE THREAD

**Issue by dela1000** [expo/expo#3462]
Trying to build by using exp build:android but now the builds go in queue and do not go from there. What used to take about 5 minutes to build is now sitting idle in the queue for over an hour, and it never starts. Cancelling the build and starting a new one does not help. Tried starting a build for a different project and had the same issue. Can this be related to my set up (Pasted below), or is it on the build-servers side?

> Expo CLI 2.10.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.3 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.1.2 => 3.1.2 
    npmGlobalPackages:
      expo-cli: 2.10.0

**Comment by AdamJNavarro** [comment]
Hey @dela1000,

This was an issue on our side. We'll be deploying a fix to our builders soon.

Cheers,
Adam

**Comment by dela1000** [comment]
Ah ok. Good to know. Thanks for the lighting-fast response! Should I leave my project on the queue or should I wait a few hours and start it then?
