### ISSUE TITLE
How to eject to a regular React Native project then add parts of Expo SDK that we need manually?

### ISSUE THREAD

**Issue by gsunsnackv** [expo/expo#3464]
The reason I'm doing this:
1. Video in Expo is not working for Android 9.0 which is a large portion of our user base https://github.com/expo/expo/issues/2941
2. If eject to a Expo Kit project, you cannot add `react-native-video` because of https://github.com/expo/expo/issues/2298 (side note: I don't have data but I'm feeling so many other things cannot be imported as well, pretty much render Expo Kit useless)
3. We are not using many other things from Expo. We are only using: Constants, ImagePicker, Permissions, ScreenOrientation, Svg and Google Facebook Login

You help or criticism are welcomed and appreciated

**Comment by brentvatne** [comment]
hello! there isn't a great way to do this right now but we're working on it. more info [here](https://blog.expo.io/expokit-2019-1e5cb02106f8).

here's an example project with just a few things set up: https://github.com/brentvatne/my-app-with-unimodules. you could clone that project and add the packages from https://github.com/expo/expo/tree/master/packages as you need them. this doc outlines roughly how to install each of the packages: https://gist.github.com/brentvatne/074f64446b06907e13dea9dc099f4ed7

**Comment by gsunsnackv** [comment]
Thank you @brentvatne . We will have a look. Our current plan is to find alternatives in react-native world for all the Expo things we currently use.

**Comment by brentvatne** [comment]
ah, too bad! we're very close to being able to launch the workflow that allows you to eject in the way that you would like

**Comment by AdamJNavarro** [comment]
Hey @gsunsnackv,

I'm going to close this issue as I believe Brent answered your questions, but if you have any more please feel free to raise them on our [forums](https://forums.expo.io/)!
