### ISSUE TITLE
Try out RAM bundles

### ISSUE THREAD

**Issue by ide** [expo/expo#3467]
Talked to Christoph a little bit about enabling RAM bundles - they are encapsulated in one file (by default) and there are instructions on them in the performance section of the RN docs. Few things we need to do to investigate:

1) Learn more by trying it out (manually patch Expo CLI if needed) and with `dev=false` locally. Also may need to make client changes so it interprets the bundle as a RAM bundle instead of plain JS.
2) Publish a RAM bundle (manually upload to S3 and modify manifest if needed) + test with client.
3) See what changes we'd need to make to Expo CLI to provide this as an option.

**Comment by kylewang4929** [comment]
How should I modify it Expo CLI ?
If I need to try RAM bundles.

**Comment by ide** [comment]
You should start by reading the RN CLI + RN + Expo CLI source code around bundling and then figure it out (that's largely what this GH issue is about).

**Comment by kylewang4929** [comment]
```
response = await axios.get(fullUrl, {
      responseType: 'text',
      // Workaround for https://github.com/axios/axios/issues/907.
      // Without transformResponse, axios will parse the body as JSON regardless of the responseType/
      transformResponse: [data => data],
      proxy: false,
      validateStatus: status => status === 200,
      headers: {
        'Exponent-Platform': platform,
      },
    });
```

Generate the bundle here.
However, I still don't understand where the bundle are generated.

Is the build bundle done in the dev-serve?

Is there anyone who can help me?

**Comment by cpojer** [comment]
There is a command called `bundle` in the react-native cli, and a corresponding command called `ram-bundle`. I'm not sure how expo uses the cli or if everything is custom, but somewhere Metro is being invoked with `bundle` right now and should be invoked with `ram-bundle` instead.

**Comment by ide** [comment]
Closing this since we are not working on RAM bundles but are keeping other forms of bundles in mind in future projects.
