### ISSUE TITLE
Location.hasServicesEnabledAsync() is not a function error

### ISSUE THREAD

**Issue by mreorhan** [expo/expo#3472]
### Environment
System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
NPM Packages:
   "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "expo": "^31.0.4",
    "moment": "^2.22.2",
    "native-base": "^2.8.1",
    "react": "^16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
    "react-native-i18n": "^2.0.15",
    "react-native-maps": "^0.23.0",
    "react-native-maps-directions": "^1.6.0",
    "react-navigation": "^2.18.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-promise-middleware": "^5.1.1",
    "redux-thunk": "^2.3.0"

This issue happening in real android device. (Samsung Galaxy S8)
### Steps to Reproduce

I tried Location.hasServicesEnabledAsync() function for check gps enable/disable status. But I had received an error like this:
[Unhandled promise rejection: TypeError: _expo.Location.hasServicesEnabledAsync is not a function. (In '_expo.Location.hasServicesEnabledAsync()', '_expo.Location.hasServicesEnabledAsync' is undefined)]

Also I tried with Expo snack. (Worked correctly)
https://snack.expo.io/@mreorhan/async-has-services-enabled

### Expected Behavior

GPS open/close status

(Write what you thought would happen.)

### Actual Behavior

I tried without hasServicesEnabledAsync() function. Working correctly in my device.

  export async function _getLocationAsync() {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status !== 'granted') {
      alert('permission.location_error')
      return
    }
    let location = await Location.getCurrentPositionAsync({});
      return location
  };

(Write what happened. Add screenshots!)

### Reproducible Demo
https://snack.expo.io/@mreorhan/async-has-services-enabled

**Comment by drfenixion** [comment]
Have same in 30 version of Expo API. I think it is because of Expo introduced this method in the late version of API. In docs of 31 version you can't see this method https://docs.expo.io/versions/v31.0.0/sdk/location/

**Comment by mreorhan** [comment]
> Have same in 30 version of Expo API. I think it is because of Expo introduced this method in the late version of API. In docs of 31 version, you can't see this method https://docs.expo.io/versions/v31.0.0/sdk/location/
> 
> Yes, it is. I updated my project to 32 version and its work. But if you will decide to update, see manual and breaking changes https://blog.expo.io/expo-sdk-v32-0-0-is-now-available-6b78f92a6c52
> I faced with some errors In the update process, but decided them in 1-2 hour.

Thank you, I'll try it.

**Comment by tsapeta** [comment]
Hello guys,

Yeah, `Location.hasServicesEnabledAsync` was added in SDK32, however it's just a shortcut to `(await Location.getProviderStatusAsync()).locationServicesEnabled` that you can use in previous SDKs. See the [documentation](https://docs.expo.io/versions/v32.0.0/sdk/location/#locationgetproviderstatusasync).

**Comment by mreorhan** [comment]
> await Location.getProviderStatusAsync()).locationServicesEnabled

This usage working correctly:
```
let gpsServiceStatus = await Location.getProviderStatusAsync()
  if (gpsServiceStatus.locationServicesEnabled) {
       ...
  }
```

**Comment by igorbrandao** [comment]
I'm using sdk 32 and am getting this error. Using previous method (`getProviderStatusAsync `) solved my issue.

**Comment by methodbox** [comment]
> Hello guys,
> 
> Yeah, `Location.hasServicesEnabledAsync` was added in SDK32, however it's just a shortcut to `(await Location.getProviderStatusAsync()).locationServicesEnabled` that you can use in previous SDKs. See the [documentation](https://docs.expo.io/versions/v32.0.0/sdk/location/#locationgetproviderstatusasync).

This should be re-opened. Your documentation is either wrong, or you are (I'm assuming it's the docs) as it lists this as a method, and doesn't explain at all what you just said (see your own link, read docs).

<img width="911" alt="Screen Shot 2019-06-03 at 7 40 29 PM" src="https://user-images.githubusercontent.com/12660440/58843291-78d41900-8637-11e9-9c7a-0579390e5fca.png">

It doesn't actually return a Promise that resolves to `true` or `false`; it returns a Promise that looks like this:

```js
componentWillMount() {
    let locationEnabled = Location.hasServicesEnabledAsync();

    console.log(locationEnabled);
  }

Promise {
  "_40": 0,
  "_55": null,
  "_65": 0,
  "_72": null,
}
```

Which is worthless. Unfortunately, so does `getProviderStatusAsync` - it returns the same useless Promise.

Unfortunately, NONE of this works with TypeScript.
