### ISSUE TITLE
Error closing multiples opened modals

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#3473]
### Environment
```
  Expo CLI 2.7.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.10.1 - ~/.nvm/versions/node/v9.10.1/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v9.10.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.7.0
```

Reproducible only on iOS.
Android is working well.

### Steps to Reproduce
1. Open https://snack.expo.io/HJQ_fn34N
2. Open the app in Android (we are gonna see it working well at first)
3. The App is gonna to open a Red Modal, automatically.
4. Quickly, Tap on "Show Modal Blue" (so, the Red Modal is gonna open a Blue Modal).
5. Wait for 10 seconds.
6. The parent "App" is gonna close the Red Modal. So, Blue modal is gonna be closed as well, due to the Blue Modal is a Red Modal children.

Now, let's see the error on iOS
1. Open the same Snack
2. Open the app in iOS
3. The App is gonna to open a Red Modal, automatically.
4. Quickly, Tap on "Show Modal Blue" (so, the Red Modal is gonna open a Blue Modal).
5. Wait for 10 seconds.
6. The parent "App" is gonna close the Red Modal. **But**, the Blue Modal is gonna be closed but the Red Modal still there, broken. Kind of froze.

### Expected Behavior
The Android behavior (both modals should be closed)

### Actual Behavior
iOS only close the Blue Modal (the second one) and keeps the Red Modal (the first one) opened.

### Reproducible Demo
https://snack.expo.io/HJQ_fn34N

**Comment by AdamJNavarro** [comment]
Hey @BrodaNoel,

This looks to be a RN issue rather than an Expo-specific one. The best course of action would be to file an issue on the official repo here: https://github.com/facebook/react-native/issues

Cheers,
Adam

**Comment by BrodaNoel** [comment]
My bad.
Thanks!
I'll do it right now.
