### ISSUE TITLE
Jest tests fail on newly init project

### ISSUE THREAD

**Issue by karlkras** [expo/expo#3476]
### Environment

  Expo CLI 2.7.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

### Steps to Reproduce

[As per basic install and validate instructions simply do this](https://github.com/expo/jest-expo#installation)
### Expected Behavior

From that link above, test should run without error.

### Actual Behavior

```
C:\Users\karlk\work\universal-consumerapp\src\components\__tests__\Example.test.js
  1:1  error  'it' is not defined      no-undef
  2:3  error  'expect' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)

npm ERR! Test failed.  See above for more details.
```

**Comment by ide** [comment]
Tested with these steps and had tests passing:

```
cd /tmp
expo init example # set up a new project, choose tabs template
cd example
yarn test # tests pass
```
