### ISSUE TITLE
No devices connected (can't see the logs from the iOS devices)

### ISSUE THREAD

**Issue by LAITONEN** [expo/expo#348]
Hello! 

**Issue:** 
Under the right-part of Expo XDE I continuously see "no devices connected". The XDE does not detect neither my iPhone, nor the iOS simulator.

**What did not help:**
- restarting the XDE, app, project
- emptying .expo folder
- when I open the project's url in the browser and go to logUrl, it says: Cannot GET /logs

**Comment by ide** [comment]
Are you able to load your project on your phone successfully?

**Comment by LAITONEN** [comment]
Yes.

**Comment by terribleben** [comment]
Does the problem still happen with a brand new "tabs" project? Or is it specific to one project you're working on?

**Comment by LAITONEN** [comment]
@terribleben it happens in every single project. Even with updated Expo (19.0.0).

**Comment by terribleben** [comment]
Hey there, sorry for reviving this very old thread, but we've made several improvements to this since July (falling back to a better connection when our tunnel fails). I'm going to optimistically close this but please comment here if you still see the same behavior.

**Comment by JulianKingman** [comment]
I just started running into this problem. I don't see logs in the console, nor in the browser if I debug remote js. Same for external devices.

**Comment by isaachinman** [comment]
I also do not see logs on an external Android device after running `adb logcat`.

**Comment by qiangf811** [comment]
i have met the same question in expo (vesion:2.24.3 (2.24.3.34267))，how to fixed it ?

**Comment by SaveYourTime** [comment]
same here with no devices connected.
<img width="1680" alt="2018-05-22 3 11 28" src="https://user-images.githubusercontent.com/35715664/40347361-94ead3c4-5dd2-11e8-94d9-6f1fe13614e7.png">

**Comment by MeKyleH** [comment]
I had this problem the last couple of days where Expo would only show my iOS simulator but none of my Android connected devices. However, I closed the project, closed Expo, and then opened it back up. I started the app on the Android device first and it started showing the logs again.

**Comment by LeiZeng** [comment]
Same issue with EXPO XDE 2.24.4 (2.24.4.53441), IOS emulater

App works fine, but can not print any console logs from the devices.

**Comment by chosungwon** [comment]
![image](https://user-images.githubusercontent.com/22117662/43045952-aad46fec-8dfc-11e8-84ee-bd7d4f444f8a.png)
me too :(

**Comment by MeKyleH** [comment]
@chosungwon Did you try closing the simulator and Expo and then re-open? That fixed it for me.

**Comment by chosungwon** [comment]
@MeKyleH yes in ios simulator not working but i connect my iphone7+ device detected :(

**Comment by ChaeWonKong** [comment]
I have exactly the same problem every single time. Even if i restart the project or re-open expo, i encountered same problem. No devices connected. iOS Simulator renders my app successfully thou. Is there anyway i can fix this problem and see logs in expo?
