### ISSUE TITLE
'ExpoKit.h' file not found

### ISSUE THREAD

**Issue by rishiankush** [expo/expo#349]
After Detaching using `exp detach` I got this error: 'ExpoKit.h' file not found in xcode wokspace.
I performed these steps:
1. exp detach
2. installed cocoapods
3. pod install
4. run the project in xcode workspace.

**Comment by ide** [comment]
Can you verify that ExpoKit.h exists on your disk somewhere? You also might want to try checking out the commit prior to detaching and following the instructions carefully here: https://docs.expo.io/versions/v18.0.0/guides/expokit.html#3-ios-configure-build-and-run.

**Comment by terribleben** [comment]
No other reports of this and haven't heard back about the original problem - let me know if you're still hitting the issue.

**Comment by joshpitzalis** [comment]
I'm having the same issue.

I ejected, npm installed gain, pod inatalled and then tried to build but I get **.../AppDelegate.m:4:9: 'ExpoKit.h' file not found**

Any suggestions?

I deleted and reinstalled everything a few times. Tried just clearing npm modules and or just clearing pods. Nothing seems to help.

**Comment by bhoomika911** [comment]
I have same issue.

Any one can help?

**Comment by Ronnyrr** [comment]
Same issue. Any recommendations?

**Comment by abrarum** [comment]
Same problem.. Need some eyeballs.

**Comment by vuthanhtrung0504** [comment]
same issue with CocoaPods 1.4.0 tag ios/2.6.5
