### ISSUE TITLE
Foreign keys not working

### ISSUE THREAD

**Issue by i-schuetz** [expo/expo#3496]
Foreign keys are not working in iOS (tested only with the simulator so far). I found that I have to execute PRAGMA foreign_keys = ON; I did this in a transaction, like this:

```typescript
db.transaction((tx: SQLite.Transaction) => {
  tx.executeSql(
    "PRAGMA foreign_keys = ON;",
    [],
    (_, { rows: { _array } }) => {
      console.log(`Enable foreign keys result: ${JSON.stringify(_array)}`)
    },
    ({}, error) => {
      console.log(`Enable foreign keys error: ${error}`)
    }
  )
})
```

It doesn’t seem to work. Cascade delete doesn’t work, and if I log the setting in a new transaction, it says it’s still 0:

```typescript
tx.executeSql(
  "PRAGMA foreign_keys;",
  [],
  (_, { rows: { _array } }) => {
    console.log(`foreign keys result: ${JSON.stringify(_array)}`) // prints {"foreign_keys":0}
  },
  ({}, error) => {
    console.log(`foreign keys error: ${error}`)
  }
)
```

I found this: https://github.com/litehelpers/Cordova-sqlite-storage/issues/45
There the solution seems to be to execute PRAGMA foreign_keys = ON; “directly” on the db, i.e. without a transaction, but I don’t see an api in Expo to do that.

How do I enable foreign keys?

**Comment by cschloer** [comment]
Hi, for those looking for a workaround I was able to find a way to execute directly onto the db without a transaction.
```
const db = SQLite.openDatabase('dbName', version);

db._db.exec(
  [{ sql: 'PRAGMA foreign_keys = ON;', args: [] }],
  false,
  () => console.log('Foreign keys turned on'),
);
```
Testing on Android 9.0 running this code I was able to get Foreign Keys and Cascade Deletes working.
