### ISSUE TITLE
Updating react-native-maps to 0.15.2

### ISSUE THREAD

**Issue by jxeeno** [expo/expo#350]
Version 0.15.2 of `react-native-maps` brings two features I'm waiting for on iOS:

* onPress support for Google Maps Polyline
* Marker rotation support for Google Maps on iOS

Could we update to the latest version?

**Comment by ide** [comment]
We'll look into this for SDK 19 (should work but can't say for sure without trying).

**Comment by jxeeno** [comment]
0.15.3 now live on SDK 19 :) thanks!
