### ISSUE TITLE
Can not use getCamera() method with mapView

### ISSUE THREAD

**Issue by daihalu** [expo/expo#3502]
### Is this a bug report?

YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

YES

### Environment
"expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-maps": "^0.23.0"
Device: android 7

### Steps to Reproduce

I try to control camera in mapView by using getCamera method but I get this error: 
`[Unhandled promise rejection: TypeError: undefined is not an object (evaluating` `_reactNative.NativeModules.AirMapModule.getCamera')]`
`Stack trace:`
  `node_modules\react-native-maps\lib\components\MapView.js:600:40 in getCamera`
  `screens\HomeScreen.js:18:25 in getCamera$`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:44 in tryCatch`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:288:30 in invoke`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:44 in tryCatch`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:152:28 in invoke`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:187:17 in <unknown>`
  `node_modules\promise\setimmediate\core.js:45:7 in tryCallTwo`
  `node_modules\promise\setimmediate\core.js:200:23 in doResolve`
  `node_modules\promise\setimmediate\core.js:66:12 in Promise`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:186:27 in` `callInvokeWithMethodAndArg`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:209:38 in enqueue`
  `node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:233:8 in async`
  `null:null in getCamera`
  `screens\HomeScreen.js:70:27 in onPress`
 `node_modules\react-native\Libraries\Components\Touchable\TouchableOpacity.js:212:45 in` `touchableHandlePress`
  `node_modules\react-native\Libraries\Components\Touchable\Touchable.js:803:34 in` `_performSideEffectsForTransition...`
### Expected Behavior

I expected that I can animate camera when I have some pickers without using fitToCoordinates method.

### Actual Behavior

getCamera() works normally when I import  MapView from "react-native-maps" and test on android device directly without using expo client app. But I get error that I mentioned when I test with expo client app either import MapView from expo or react-native-maps.
Thank in advance

**Comment by AdamJNavarro** [comment]
Hey @daihalu,

Thanks for this report! Would you be able to create a repro case for us either in the form of a [Snack](snack.expo.io) or a public github repo? In addition to a multitude of other factors, we prioritize issues that have a [MCVE](https://stackoverflow.com/help/mcve) as we can more efficiently debug and investigate when one is provided.

One other question: Have you tested to see if this error occurs on iOS as well by chance?

Cheers,
Adam

**Comment by daihalu** [comment]
I have tested on iOS and this error still occurs.
This is my repo: https://github.com/daihalu/Pokemon-Animation

**Comment by sjchmiela** [comment]
Hey, @daihalu! I think `getCamera` is only available in `react-native-maps` since 0.23.0 release, which has landed on `master` thanks to [this PR](https://github.com/expo/expo/pull/3389), however, it hasn't been released in an Expo SDK yet. So SDK32 is still on `react-native-maps@0.22.0`. SDK33 will contain at least 0.23.0 of `rn-maps`, so you'll then be able to use `getCamera` method. 🙂
