### ISSUE TITLE
Video Compressing

### ISSUE THREAD

**Issue by Freysi21** [expo/expo#3505]
Hi

I'm trying to use the ImagePicker to select videos or photos and I want to compress them before uploading to server. 

I have this code to test it

`  
async onMediaPress() {
    const { status: cameraRollPerm } = await Permissions.askAsync(Permissions.CAMERA_ROLL);

    if (cameraRollPerm === "granted") {
      let pickerResult = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: "All",
        quality: 0.1
      });
      console.log("PICKER");
      console.log(pickerResult);
      this.handleImagePicked(pickerResult);
    }
  }

  handleImagePicked(pickerResult) {
    FileSystemService.getMedia(pickerResult.uri, 1);
  }
`

And file systemservice

`
import JSZip from "jszip";
import { FileSystem, ImageManipulator } from "expo";

export default class FileSystemService {
  static async getRatioToMaxSize(path: string, maxSize: number) {
    const file = await FileSystem.getInfoAsync(path, {
      size: true
    });
    console.log(file);
    this.getMedia(path, maxSize);
  }

  static async getMedia(path: string, maxSize: number) {
    const file = await FileSystem.getInfoAsync(path, {
      size: true
    });
    const saveOptions = {
      base64: false,
      compress: 0.5
    };
    console.log(file);
    const compressed = await ImageManipulator.manipulateAsync(file.uri, undefined, saveOptions);
    console.log(compressed);
  }
}
`
And when logging the file I see that only images are compressed from imagePicker but has no effect on videos. 

When I pass the file to the ImageManipulator it returns the video as jpg or png. 

Is there any way to compress a currently existing video within device with expo?
I don't need Camera.recordAsync btw. I need to pick it from the phone media library and compress it before I upload it to server.

**Comment by AdamJNavarro** [comment]
Hey @Freysi21,

Client-side video compression with the Expo SDK is not currently possible. For future reference, please take these types of questions to our [forums](http://forums.expo.io) as we try our best to keep github issues reserved for bugs.

All the best,

Adam
