### ISSUE TITLE
Will expo builds support Apple's MANDATORY two factor authentication?

### ISSUE THREAD

**Issue by joelgetaction** [expo/expo#3508]
Apple is making  two factor authentication MANDATORY for all use of the developer portal and starting February 27, 2019.  See https://support.apple.com/en-us/HT204915

Will this break expo builds?  Will expo builds still be able to manage certs etc?  If not, how can we update expo builds so that it can still work with 2FA?

**Comment by AdamJNavarro** [comment]
Hey @joelgetaction,

The expo-CLI already supports 2FA. Depending on when you made your Apple account, it may not prompt you as only newer accounts require it -- that is until the 27th when all accounts will require it as you linked to.

Cheers,
Adam
