### ISSUE TITLE
Android 7 standalone push notification not staying to be addressed

### ISSUE THREAD

**Issue by townmulti** [expo/expo#3509]
Push notifications are not staying available on my android phone. My android is running 7.1.1 and it is a Alcatel Raven LTE (Model A574BL). Here is a link to the [expo form topic](https://forums.expo.io/t/android-7-does-not-show-push-notification-android-8-and-ios-works-well/19292/6).

##Environment
```
  Expo CLI 2.10.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.3.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.5 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.2.1 => 3.2.1 
    npmGlobalPackages:
      expo-cli: 2.10.0
```

App's target: Standalone iOS and Android

I can see this by using expo push notification tool. 

1. Use [snack](https://snack.expo.io/@multitown/YW5kcm) and it will show push token on screen
1. Send Notification with expo push notification tool
2. When notification arrives to the phone, it comes and goes quickly.

I expect the notification to remain available until I address it.

The notification doesn't stay as in this picture.

![ezgif com-resize](https://user-images.githubusercontent.com/10806345/52761703-13054800-2fda-11e9-8224-f767331543a9.gif)

I've figure out how to duplicate the issue I'm having. The problem is the badge setting to clear with `Notifications.dismissAllNotificationsAsync()`. 

A snack to duplicate it [here](https://snack.expo.io/@multitown/YW5kcm).

**Comment by AdamJNavarro** [comment]
Hey @townmulti,

Could you edit your post and make sure you follow the issue template as close to possible. The device model is helpful but we'll need more information to deep dive into this.

**Comment by townmulti** [comment]
Okay @AdamJNavarro thanks! I've updated my post.

**Comment by HichamELBSI** [comment]
Same error for our company's application. On some Android 8.X phones, notifications are cleared directly !

This error appear also with the Expo Push Notification Tool.
Expo SDK : 32.0.0

Thx to the Expo Team

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. This appears to be an issue in your code -- `addListener` is called as soon as the notification arrives so it's dismissed immediately. Please create a new issue with a full repro case if you run into a similar issue with different code in a currently supported SDK version. Thanks!
