### ISSUE TITLE
Android - windowSoftInputMode="adjustResize" not working on SDK 18.0.0 but SDK 17.0.0 does

### ISSUE THREAD

**Issue by daominhsangvn** [expo/expo#351]
as the title

**Comment by ide** [comment]
Android's behavior depends on whether the status bar is opaque. I'm not sure why it would differ between SDK versions, though. For `adjustResize` to be active, you need to have an opaque status bar. In app.json/exp.json, try setting `backgroundColor` on `androidStatusBar` to an opaque value: https://docs.expo.io/versions/v18.0.0/guides/configuration.html#backgroundcolor-1.

**Comment by daominhsangvn** [comment]
my issue i when the keyboard show up, the screen doesn't get resized so the input is behide the keyboard and not get scroll to focused input.
Is it related to the status bar @ide ? idk..

**Comment by ide** [comment]
The status bar is related: https://issuetracker.google.com/issues/36911528
If you're using a detached app you may want to research more on StackOverflow for native Android solutions: https://stackoverflow.com/a/21860837/454967

BTW if you plan to support iOS you will have to handle the keyboard.

**Comment by daominhsangvn** [comment]
thanks, i will close it.
