### ISSUE TITLE
How to make an svg properly clickable on React Native with Expo?

### ISSUE THREAD

**Issue by maketroli** [expo/expo#3514]
I am using React Native with Expo and I have 4 SVG elements that I need them to be clickable. This is the code for each of these:
```javascript
  <Svg.G
    id="Passangers-Going-B"
    onPress={() => console.log(`${cardinalPoint} Avatar Was Clicked`)}
   >
...

```
With that code I am able to click on the SVG element but the weird thing is that when I try to click on another element the click is still firing the event for the last element I clicked on.

[I recorded a video with the behavior][1]

So, is there a better way to do this? All I need is to click on those SVG elements in order to change to a new route.

Any ideas?

I am using SVG from expo. `import { Svg } from 'expo';` -> https://docs.expo.io/versions/latest/sdk/svg/

  [1]: https://monosnap.com/file/PMvw5gQzSx0YpnTSmWXjthtEKzvDOK

**Comment by AdamJNavarro** [comment]
Hey @maketroli,

We reserve Github issues for bug reports and prefer these types of questions to be directed to our [forums](https://forums.expo.io/c/how-to). I'm going to close this issue but please don't hesitate to raise the question in the forums.

Cheers,
Adam
