### ISSUE TITLE
Facebook oath routes being called automatically????

### ISSUE THREAD

**Issue by otaviogaiao** [expo/expo#3515]
Hi. I developed an app at work using the latest version of expo, however, I’m facing a very strange bug on Android (on my production build)

The app stops working out of nowhere! and randomly! When I say it stops working, it doenst crash or anything. But all network requests fails! I dont receive any error on Sentry also.
At first I thought my requests could be cached, so I made some changes to prevent such issues. However the problem still persists! So I installed a package capture app on my phone to see if I could grab the issue. And it surprised me:

Some facebook oAuth routes are being called automatically! But I don’t use facebook at all in the app! We do login using oAuth to a private api. In no moment I use the facebook login sdk, All my auth flux is made using normal post requests with axios to my private api.

Take a look at some screenshots:

![erro6](https://user-images.githubusercontent.com/3965485/52814919-7350c400-3084-11e9-865d-ae418a8420f0.jpg)
![erro5](https://user-images.githubusercontent.com/3965485/52814920-73e95a80-3084-11e9-9af7-48305188689f.jpg)
![erro4](https://user-images.githubusercontent.com/3965485/52814921-73e95a80-3084-11e9-82b0-94b76e99793d.jpg)
![erro3](https://user-images.githubusercontent.com/3965485/52814923-73e95a80-3084-11e9-8dc6-e9df18feb623.jpg)
![erro2](https://user-images.githubusercontent.com/3965485/52814924-7481f100-3084-11e9-8b1f-1f848f49a2fa.jpg)
![erro1](https://user-images.githubusercontent.com/3965485/52814925-7481f100-3084-11e9-8d1d-8104b2cb29c9.jpg)

### Environment

Expo SDK 32
Node 9.10

### Steps to Reproduce

This bug only happens on Android and on Production build. I don't know how to reproduce it because it happens randomly.

### Expected Behavior

These routes should not be implicitly called right?

### Actual Behavior

Some Facebook oath routes being called automatically and that is breaking the app because its not prepared for that.

**Comment by cruzach** [comment]
Hi! sorry for the late response, but this was fixed and we now do not initialize the facebook SDK at all unless you do so from your code. Thanks for your patience!
