### ISSUE TITLE
detox: allow configuration of experience permissions

### ISSUE THREAD

**Issue by quinlanj** [expo/expo#3516]
allow experience permissions to be set from expo detox helpers:

https://forums.expo.io/t/set-up-permissions-for-e2e-test-with-detox/19403/2

**Comment by vasyas** [comment]
@quinlanj 
Is there any help required for this ticket to be fixed? 
Or maybe you can provide a guidance what should be changed to get it fixed, I can make a PR>
I'm really interested in getting this fixed.

**Comment by awinograd** [comment]
This is blocking for me as well. Unfortunately I don't know if there's currently a way to workaround the issue

**Comment by awinograd** [comment]
Ignore the above comment. Just realized we can interact with this permissions dialog because it's not a native systems permissions dialog, but an Expo one. That means we can just do 

`await element(by.text('Allow')).tap();  `

**Comment by bsgbryan** [comment]
Has this been worked on? This is an issue for me, and the workaround mentioned by @awinograd does not work for me.

**Comment by awinograd** [comment]
@bsgbryan make sure you're calling reloadApp (https://github.com/expo/detox-expo-helpers/blob/4474232f6c5f9ab259e2b80133e14a4270f57a1c/index.js#L69) with the proper permissions. I pass in:

```
const permissions = {
    calendar: 'YES',
    camera: 'YES',
    contacts: 'YES',
    faceid: 'YES',
    location: 'inuse',
    medialibrary: 'YES',
    microphone: 'YES',
    notifications: 'YES',
    photos: 'YES',
    reminders: 'YES',
    speech: 'YES',
  }
```

**Comment by bsgbryan** [comment]
Thanks for your quick reply!

Below is the full code for the test:

```javascript
import { reloadApp } from 'detox-expo-helpers'

describe('Example', () => {
  beforeEach(async () => {
    const permissions = {
      calendar: 'YES',
      camera: 'YES',
      contacts: 'YES',
      faceid: 'YES',
      location: 'inuse',
      medialibrary: 'YES',
      microphone: 'YES',
      notifications: 'YES',
      photos: 'YES',
      reminders: 'YES',
      speech: 'YES'
    }
    await reloadApp({ permissions })
  })

  it('should have welcome screen', async () => {
    await element(by.text('Allow')).tap()
    await expect(element(by.id('welcome'))).toBeVisible()
  })
})
```

Line 22 never gets reached because line 18 does not yield until I manually tap Allow.

I have tried placing the `tap()` call on line 19. That does not work either, as line 18 does not yield.

**Comment by awinograd** [comment]
@bsgbryan not sure what might be going on. If the dialog says access was already granted for another experience, then it's definitely an expo dialog controlled by the app and I previously was able to find it `by.text`

We've since moved to the bare workflow so I haven't had to deall with this specific issue in a whihle

**Comment by tochman** [comment]
Hi, throwing in my 5 cents worth of knowledge: I managed to get the permissions with:

```js
beforeEach(async () => {
  await adapter.beforeEach();
  await reloadApp({
    permissions: { location: 'inuse' },
  })
});
``` 
Ans in the `it` block to tap the"Allow" button: (never really gotten `by.text()` to work 🤨)
```js
await element(by.label('Allow')).atIndex(1).tap()
```

However, my problem is that I can't get anything out of `Location.getCurrentPositionAsync()` in test env. 

Here's my function: 

```js
  const getLocation = async () => {
    const { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status === 'granted' ) {
      let location = await Location.getCurrentPositionAsync({ enableHighAccuracy: true });
      dispatch({ type: 'SET_LOCATION', payload: location })
    } else {
      dispatch({ type: 'SET_ERROR_MESSAGE', payload: 'Permission to access location was denied' });
    }
  }
  useEffect(() => {
    getLocation()
  }, []);
```js

Works when I run the app in the simulator but returns `Possible <Unhandled Promise Rejection (id: 0)` as if the location was not set (or set to 'none'). Any ideas?

**Comment by tochman** [comment]
I played around with my code and ended up with the following:

```js
  const getLocation = async () => {
    const { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status === 'granted') {
      let location = await Location.getCurrentPositionAsync({ enableHighAccuracy: true });
      return location
    } else {
      throw new Error('Permission to access location was denied')
    }
  }
  useEffect(() => {
    getLocation()
      .then(location => {
        dispatch({ type: 'SET_LOCATION', payload: location })
      })
      .catch(error => {
        dispatch({ type: 'SET_ERROR_MESSAGE', payload: error.message });
      })
  }, []);
```
This allows me to clearly see the `error.message` in test env: 
```
"Cannot obtain current location: Error Domain=kCLErrorDomain Code=0 "(null)""
```
So the challenge is to make sure that my Simulator starts with a location already preset... Ths hunt goes on...

**Comment by Livijn** [comment]
This shouldn't be closed.

**Comment by Livijn** [comment]
@tochman Did you manage to get this to work?
