### ISSUE TITLE
Expo App with await Contacts.getContactsAsync({fields: [Contacts.Fields.PHONE_NUMBERS]}) does not return contacts with phone numbers 

### ISSUE THREAD

**Issue by shubham-2710** [expo/expo#3518]
## Environment

 Expo CLI 2.10.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.14.0 - C:\Users\User\AppData\Roaming\npm\yarn.CMD
      npm: 5.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  2.3.0.0 AI-162.4069837

I am trying to get the contacts with phone numbers fields by using Contacts.getContactsAsync. 
Using this with the field parameter set as PHONE_NUMBERS does not fetch contacts with phone numbers. 
Below the basic snack example having usage with the above.

### Expected Behavior

The Contacts Contacts.getContactsAsync call should return contacts with  phone numbers when passed with field PHONE_NUMBERs as a parameter.

(Write what you thought would happen.)

### Actual Behavior

Contacts are returned but without the phone number fields

### Reproducible Demo

 Snack Available : https://snack.expo.io/@shub2710/test_with_expo_contacts

**Comment by EvanBacon** [comment]
The constant you are using is invalid. Omit the `Fields` value or use the correct `PhoneNumbers` property. Let me know if this works for you.

```diff
import { Permissions, Contacts } from 'expo';

await Permissions.askAsync(Permissions.CONTACTS);

const { data } = await Contacts.getContactsAsync({
  fields: [
-     Contacts.Fields.PHONE_NUMBERS
+    Contacts.Fields.PhoneNumbers
+    // Deprecated: Contacts.PHONE_NUMBERS
  ]
});
```

**Comment by EvanBacon** [comment]
Confirmed this works on iOS running Expo v32

**Comment by AdamJNavarro** [comment]
Hey @shubham-2710,

I'm guessing that @EvanBacon's solution has worked for you. If you have implemented his solution and you are still not seeing phone numbers in the array returned, please let us know and I'll re-open this issue.

Cheers,

Adam

**Comment by kristofsteindl** [comment]
For me it's not working either. I use the API per the docs (I suppose). Before, and after it logs (the code runs), but it doesn't log the contacts. Actually, it doesn't log anything (undefined, null, promise, break line...) Can you please check out what I miss / what's the problem?
https://snack.expo.io/@kristof.steindl/text-or-delete

Thanks!

**Comment by o-pooja-o** [comment]
not working still..showing undefined phoneNumbers[0] when trying to get just number item

**Comment by SeoBG** [comment]
here a working expo snack

https://snack.expo.io/@malfuckingfurion/react-native-expo-contacts

**Comment by Harshaou** [comment]
> not working still..showing undefined phoneNumbers[0] when trying to get just number item

same problem for me too

**Comment by Harshaou** [comment]
> here a working expo snack
> 
> https://snack.expo.io/@malfuckingfurion/react-native-expo-contacts

Its possible to take one contact but can’t access all the contacts on phone. How can do that ?

**Comment by Vanns35** [comment]
> not working still..showing undefined phoneNumbers[0] when trying to get just number item

if(item.phoneNumbers && item.phoneNumbers.length > 0) {													 
    console.log(item.phoneNumbers[0];
} 
@o-pooja-o  You have to check this condition to avoid error.
