### ISSUE TITLE
Networking.sendRequest got 8 arguments, expected 9

### ISSUE THREAD

**Issue by crazyx13th** [expo/expo#352]
Hi there, 

I'm developing ReactNative on Windows. All fine, but not the last step :-(
"expo": "17.0.0"
"react": "16.0.0-alpha.6"
"react-native": "github:exponent/react-native#sdk-17.0.0"
"sdkVersion": "17.0.0"

iOS@expo: fine!
iOS@Apple Store: fine!
Android@expo: fine!
Android@PlayStore / Android-APK at Simulator: fail :-(

can't use "sdkVersion": "18.0.0" because of https://github.com/facebook/react-native/issues/14209
any idea!? very frustrating to waste days only for the Android Play Store...

thanks!

cya crazyx13th

**Comment by crazyx13th** [comment]
ok, now I don't understand anything. The App at long-press "info" shows version 1.17.2 (my version nr depends on sdk version. but the log says 

```
07-10 18:50:46.326  5784  5855 I ReactNativeJS: Running application "main" with appParams: {"initialProps":{"exp":{"initialUri":"https://exp.host:443/@xxxxxxx/xxxxxxx","manifest":{"iconUrl":"https://d1wpxxxxxsqw74a.cloudfront.net/~assets/a91068xxxxxxx9472707ce
b4d902e1298e","isVerified":true,"version":"1.18.1","loading":{"iconUrl":"https://d1wxxxxsqw74a.cloudfront.net/~assets/a91068c437f9472707cxxxxxxe1298e","icon":"src/icons/expo.png"},"slug":"xxxxxxx","icon":"src/icons/expo.png","sdkVersion":"18.0.0","packagerOp
ts":{"assetExts":["ttf"]},"ios":{"bundleIdentifier":"com.xxxxxxx.exp.ios"},"bundleUrl":"https://d1wp6m56sxxxxx4a.cloudfront.net/%40xxxxxxx%2Fxxxxxxx%2F1.18.1%2F94c360f71f7xxxxxxxxx61f760e1c-18.0.0-android.js","name":"xxxxxxx","publishedTime":"2017-07-10T
17:37:55.839Z","revisionId":"1.18.1-r.Z4Kma4qPA2","orientation":"portrait","android":{"package":"com.xxxxxxx.exp.android"},"privacy":"unlisted","primaryColor":"#023C69","id":"@xxxxxxx/xxxxxxx"},"shell":true}},"rootTag":1}. __DEV__ === false, development-le
vel warning are OFF, performance optimizations are ON
```

version 1.18.1? the last version was 1.18.1 with sdk 18.0.0 (and react-native 44.1)

confused...

**Comment by crazyx13th** [comment]
hey, trying a lot of things but he allways show the old "inner" version

the app info is the new v1.20.x
![grafik](https://user-images.githubusercontent.com/8912561/28059249-db87bbc8-6623-11e7-9c88-7d97db2eea54.png)

But the opened App is the old one. These are my steps:
- `node node_modules/react-native/local-cli/cli.js start --reset-cache`
- `exp start`
- `exp build:android`
- remove the old app from simulator
- download and drag'n'drop the apk to the simulator

What I'm doing wrong?! Why does the new container points to an old inner version?
Thanks!

**Comment by ide** [comment]
Regarding your second comment:

If you've published your project for SDK 18 in the past, then that's the version that is going to be bundled with your standalone app built with `exp build:android`. This is because the standalone apps support SDK 18 and they will try to use the JS for the newest SDK that you've published for. So I'd recommend upgrading to SDK 18 and republishing.

That AccessibilityInfo error shouldn't be happening. Have you tried clearing your packager state? https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352

**Comment by crazyx13th** [comment]
thx for feedback! Does this mean I can't go back to 17 after i was trying 18?!

I try to clear the hole world! :-)
```
"reset1": "rimraf \"C:/Users/xxxxx/AppData/Roaming/npm-cache/*\"",
"reset2": "rimraf \"C:/Users/xxxxx/AppData/Local/Temp/react-*\"",
"reset3": "rimraf \"C:/Users/xxxxx/AppData/Local/Temp/npm-*\"",
"reset4": "rimraf node_modules",
"reset5": "npm cache clean",
"reset6": "npm i",
"reset7": "node node_modules/react-native/local-cli/cli.js start --reset-cache",
"exp-start": "exp start --clear",
```
Do I forgot something to clear? :-)
thx!
cya crazyx13th

**Comment by ide** [comment]
Generally you can only move forward with SDK versions right now.

It looks like you've cleaned your caches well but I'm not familiar with RN on Windows so I'm not 100% sure. On that issue you linked, someone said they found old Node processes running on their computer. You could try checking for extra Node processes or restarting your computer and see if that helps. 

BTW I'm going to go to bed in a bit since it's late in my time zone, hope you find the bug

**Comment by crazyx13th** [comment]
> Generally you can only move forward with SDK versions right now.

uhh.. not good, because react-native is fantastic! but sorry, for me a tool at alpha state :-/ and now I'm stucking at sdk 18 because of trying to upgrade some dependencies? mhh...

I think with my **clear-all** commands the AccessibilityInfo error (https://github.com/facebook/react-native/issues/14209) is gone, but now I have the next Problem: https://github.com/facebook/react-native/issues/14851

Thanks!
greetings crazyx13th

**Comment by crazyx13th** [comment]
```
 "expo": "18.0.9",
"react": "16.0.0-alpha.13",
"react-native": "0.46.1"
```

at the moment maybe I'm a step further... but now I got 
```
Unable to resolve module
'react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass'
from 'D:\workspace\xxxx-mobile-app\node_modules\react-native-svg\elements\Rect.js':
Module does not exist in the module map
```

com'on! :-/

**Comment by crazyx13th** [comment]
at the end it was a hard fight... at last I changed from ex-navigation to react navigation.
now all seems to work

```
"expo": "18.0.9"
"react": "16.0.0-alpha.12"
"react-native": "github:expo/react-native#sdk-18.0.0"
```

**but downgrading the sdk ist a MUST HAVE (because if I see too late a Problem in a bigger App)**

thx!

**Comment by dikaiosune** [comment]
Hi! Glad you were able to resolve this by removing ex-navigation. I created a [feature request](https://expo.canny.io/feature-requests/p/revert-publish) that would allow for publishing again using an older sdk version. Thanks!
