### ISSUE TITLE
Typescript error with AppAuth, expo sdk 32

### ISSUE THREAD

**Issue by Johanli93** [expo/expo#3520]
Hi,
Im using Expo sdk 32 with typescript and cannot import AppAuth from expo. 
I have tried updating expo types with npm install @types/expo but it did not help.

Is there a solution to this?
Thanks

**Comment by ide** [comment]
expo-app-auth is one of the few remaining modules that does not have a type declaration. In a future release, it will be typed. https://github.com/expo/expo/issues/2336
