### ISSUE TITLE
Revert expo-blur to using the original code

### ISSUE THREAD

**Issue by ide** [expo/expo#3523]
~d4535e7d2795290b47574338d1c81a04f47f1f48~

a4598c6a439bcdfa03f7cd835929897a4e352f3d?

**Comment by moxorama** [comment]
This is sad
- expo module doesn't have support for blur on android
- It have some bugs with transition style property

**Comment by ide** [comment]
The other code was not sustainable for us to include. Feel free to submit PRs to address those issues you mentioned, if they are high-quality and maintainable we will be happy to review them.
