### ISSUE TITLE
[Question] Is it possible to use the Snack Editor with non-expo projects? Pure RN

### ISSUE THREAD

**Issue by Eyesonly88** [expo/expo#3524]
Hi there,

I use Expo in some projects and would love to know if I can use the Snack Editor with my non-expo projects? If so how?

Cheers.

**Comment by brentvatne** [comment]
hi! I don’t understand your question. what specifically are you trying to do?

**Comment by Eyesonly88** [comment]
Hey @brentvatne, I have a vanilla RN project and I essentially want to use the snack editor but without having to depend/use expo. So host my code online on my expo profile and be able to code anywhere using the snack editor and preview it live with appetize.io.

This is probably not supported but thought I'd ask in case someone tried to do what I want to do 😄 .
Thanks

**Comment by brentvatne** [comment]
you can't link native code in snack but otherwise you can do anything you want so it might work for you!
