### ISSUE TITLE
Jest proxy makes debugging impossible

### ISSUE THREAD

**Issue by garfieldnate** [expo/expo#3528]
I need to debug an issue with react-test-renderer in a Jest test. The Jest documentation [here](https://jestjs.io/docs/en/troubleshooting) explains how to debug Jest tests, and I thought I could follow the instructions for debugging using Chrome. However, I found that the `debug;` statements were never stopped on, and the only file shown in the debugger was [the Expo-Jest proxy](https://github.com/expo/expo/blob/master/packages/jest-expo/bin/jest.js). 

I do not know why a proxy for the real Jest program is being used, and the proxy source does not explain it. 

Because the proxy runs the real Jest program in a separate process, it is not possible to debug tests using the instructions on the Jest website, and indeed I have no idea how to debug the tests in this setup. 

I did find this issue reported by another user, but no solution was found: https://forums.expo.io/t/how-to-debug-jest-unit-test-on-expo-app/7901.

### Environment

`expo diagnostics` output:

    Expo CLI 2.10.1 environment info:
      System:
        OS: macOS 10.14.2
        Shell: 4.4.12 - /usr/local/bin/bash
      Binaries:
        Node: 11.6.0 - /usr/local/bin/node
        Yarn: 1.12.3 - /usr/local/bin/yarn
        npm: 6.7.0 - /usr/local/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
      IDEs:
        Xcode: 10.1/10B61 - /usr/bin/xcodebuild
      npmPackages:
        expo: ^32.0.0 => 32.0.5
        react: 16.5.0 => 16.5.0
        react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      npmGlobalPackages:
        expo-cli: 2.10.1

### Steps to Reproduce

1. In Chrome, open `chrome://inspect` and click on `Open dedicated DevTools for Node`. This will open a debug window.

2. In the example project I've attached, install dependencies with `yarn`.

3. Next, do `npm run test:debug`. This is set to `node --inspect-brk node_modules/.bin/jest --runInBand --no-cache` in package.json. The debug window opened previously will gain the screen focus and Expo's Jest proxy will be loaded.

3. Press the continue button, and the single example test will run and finish. The `debugger;` statement is ignored.

### Expected Behavior

I expect the debugger to stop on the `debugger;` statement in the test. In Jest, this can only be done when you use the `--runInBand` argument, which prevents tests from being run in a separate process. However, Expo's Jest proxy always runs Jest in a separate process, so the argument makes no difference.

### Actual Behavior

`debugger;` statement is ignored.

### Reproducible Demo

[jest-debug.zip](https://github.com/expo/expo/files/2874506/jest-debug.zip)

### What is Needed

One or more of the following:

* (Best) Get rid of the Jest proxy and allow `npm test` to run the real Jest program directly.
* Documentation explaining why Jest must be run through a proxy program and how to run it directly instead.
* Documentation on how to debug a test when run through the Expo-Jest proxy.

**Comment by ide** [comment]
We can add a comment to the proxy explaining that you need to start Jest directly if you want to debug.

**Comment by garfieldnate** [comment]
Works fantastically! Thank you very much. When I saw that there were already ~15 other tickets open since this one, I thought, "aw, man! They'll never get to this." Very much appreciated.
