### ISSUE TITLE
Sdk 31 Notifications.getExpoPushTokenAsync() not working on standalone Android 

### ISSUE THREAD

**Issue by dajohnny** [expo/expo#3534]
Hey, All!
SDK 31 Notifications.getExpoPushTokenAsync() not working on standalone Android (IOS can be used)

### Environment
```
 Expo CLI 2.10.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.3.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.0.4 => 3.0.4 
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.10.1
```

### Steps to Reproduce
1. According to [Testing Expo push notifications](https://forums.expo.io/t/new-tool-for-testing-expo-push-notifications/7100), Run the demo can receive notifications on iPhone.
2. Then I begin to research how to receive notifications on Android. According to [Using FCM for Push Notifications](https://docs.expo.io/versions/latest/guides/using-fcm/) completed all operations.
3. Finally, I found `Notifications.getExpoPushTokenAsync()` not working.

### Expected Behavior
`Notifications.getExpoPushTokenAsync()` can return token.

### Actual Behavior
`Notifications.getExpoPushTokenAsync() ` not working on Android

Because the project is private, it is not convenient to disclose. Here is my part of the code, Thanks for understanding.
```
export const requestNotificationsPermissionAsync = async () => {
  const oldPermission = await Permissions.getAsync(Permissions.NOTIFICATIONS)
  if (oldPermission.status === 'granted') {
    return true
  }

  const newPermission = await Permissions.askAsync(Permissions.NOTIFICATIONS)
  return newPermission.status === 'granted'
}

export const printExpoPushTokenAsync = async () => {
  const hasPermission = await requestNotificationsPermissionAsync()
  // 😥No results have been returned until now
  if (hasPermission) {
    const pushToken = await Notifications.getExpoPushTokenAsync()
    console.log(`Your device's Expo push token is: ${pushToken}`)
  } else {
    console.log(`Your device does not have permission to show push notifications.`)
  }
}
```

**Comment by AdamJNavarro** [comment]
Hey @dajohnny,

Can you try reproducing this on a fresh standalone project running on SDK31? If you are able to do that, we will investigate this further. If you can not, it may reveal there may be a problem with your standalone project rather than Expo's implementation.

Cheers,

Adam

**Comment by dajohnny** [comment]
Hey @AdamJNavarro ,

I have patiently checked, The problem has been solved. Thank you very much for your reply.

Cheers,

Johnny

**Comment by xiangfengsu** [comment]
@dajohnny 
Hello, I want to ask how you set it up successfully? I also follow Steps to Reproduce, but still Notifications.getExpoPushTokenAsync() not working. Thank you
