### ISSUE TITLE
Background Geolocation task "disappears" when app is killed on Android

### ISSUE THREAD

**Issue by martin-ecatch** [expo/expo#3535]
Firstly, the new background geolocation task is awesome! BUT...
When the app is killed (either by swiping it in the task manager, or by running other apps - I believe Android kills the app to free up ram), the background task stops working and actually completely disappears. Calling hasStartedGeofencingAsync() returns false and TaskManager.getRegisteredTasksAsync() returns an empty object.
This happens only on Android.
iOS is fine, the app starts after a significant location change with Constants.isHeadless=true. On Android, the app is never executed with the headless flag = true.

### Environment
  Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 9.11.2 - /usr/bin/node
      npm: 6.5.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.3.0 
    npmGlobalPackages:
      expo-cli: 2.6.14

App is built (using expo build) to standalone apps for both iOS and Android.
The problem is reproducible in both the standalone app and Expo client.

Tested on:
- iPad 4: runs without issues, using Expo client
- Samsung Galaxy S5 mini (physical device), using Expo client or standalone app: fails following the below steps
- Android Emulator with Android 9, using Expo client or standalone app: fails following the below steps

### Steps to Reproduce
1. run the app
2. click "Enable background location"
3. click "Refresh" - it will show "Running: Yes"
4. go to task manager and kill the app
5. run the app again
6. it displays "Running: No". Which means the background task has disappeared without a trace. No Location updates are happening. 

### Expected Behavior
Step 6 should display "Running: Yes" and location updates should still be happening.

### Actual Behavior
Location updates stop and the task is completely gone (confirmed by calling TaskManager.getRegisteredTasksAsync()). It needs to be started again.

### Reproducible Demo
This is the (almost) minimal code to reproduce the steps outlined above:
```
import React from 'react';
import { Location, TaskManager, Permissions, Notifications } from 'expo';
import { Text, TouchableOpacity } from 'react-native';
import axios from 'axios';
import moment from 'moment';

const LOCATION_TASK_NAME = 'background-location-task';

export default class Root extends React.Component {
  constructor() {
    super();
    this.state={};
    this.initState();
  }
  async initState() {
    const x = await Location.hasStartedLocationUpdatesAsync(LOCATION_TASK_NAME);
    this.setState({running: x});
  }
  async on() {
    await Permissions.askAsync(Permissions.LOCATION);
    await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
      timeInterval: 0,
      distanceInterval: 0,
      accuracy: Location.Accuracy.High,
    });
  };
  async off() {
    await Location.stopLocationUpdatesAsync(LOCATION_TASK_NAME);
  };

  render() {
    return (
      <React.Fragment>
      <Text>Running: {this.state.running?"Yes":"No"}</Text>
      <TouchableOpacity onPress={this.initState.bind(this)}>
        <Text>Refresh</Text>
      </TouchableOpacity>
      <TouchableOpacity onPress={this.on}>
        <Text>Enable background location</Text>
      </TouchableOpacity>
      <TouchableOpacity onPress={this.off}>
        <Text>Disable background location</Text>
      </TouchableOpacity>
      </React.Fragment>
    );
  }
}

TaskManager.defineTask(LOCATION_TASK_NAME, async ({ data, error }) => {
  if (error) {
    await axios.get("http://192.168.1.107:8000/error");
  }
  if (data) {
    // just so I know if it's happening or not
    await axios.get("http://192.168.1.107:8000/loc?ts=" + moment().format());
  }
});

```

**Comment by superyarik** [comment]
discussion here https://github.com/expo/expo/issues/3256

**Comment by tsapeta** [comment]
Hey @martin-ecatch,
Thanks for your report, I'll check it out shortly 😉

**Comment by martin-ecatch** [comment]
Hi @tsapeta, just checking... any luck with this issue? Is there anything that I can provide that might help?

**Comment by Szymon20000** [comment]
I wasn't able to reproduce this issue (I’ve tried on: [Android 9 mi max 3, Android 9 Pixel XL - emulator]).
Probably someone fixed it by fixing another issue related to background tasks. I will close this issue tentatively.
Feel free to reopen it if you encounter it once again.
