### ISSUE TITLE
expo-image-picker isn't published on npm

### ISSUE THREAD

**Issue by zubko** [expo/expo#3536]
Hi,

`expo-image-picker` is missing on npm registry.
https://www.npmjs.com/search?q=expo-image-picker

Is it intentional or accidental? :)

**Comment by raajnadar** [comment]
Not all expo packages are pushed to npm regsitry.

https://github.com/expo/expo/tree/master/packages/expo-image-picker

You need to install `expo` in you project to use `expo-image-picker`

**Comment by AdamJNavarro** [comment]
Hey @zubko,

@raajnadar is correct (for the moment). Once the Unimodule conversion is complete, the modules will be published independently.

Cheers,
Adam

**Comment by brentvatne** [comment]
published expo-image-picker@1.0.0 for you! ymmv, we are going to release all of this soon and include better documentation

**Comment by brentvatne** [comment]
published expo-image-picker@1.0.0 for you! ymmv, we are going to release all of this soon and include better documentation

**Comment by zubko** [comment]
Yay! Thanks a lot! Docs of course will help.
For example the `provider` section needs to be added to AndroidManifest for the camera to work. I'll wait for the docs before sending a PR :)
