### ISSUE TITLE
Detect headphone buttons

### ISSUE THREAD

**Issue by gollkn** [expo/expo#3537]
Hello, I am using Expo with **Managed Flow**, I want to detect headphone events, like volume up / down, play/pause.

How can I do this without react-native-music-control, I'm not have music to play just want to detect this button click events on IOS/Android how can i do ?

**Comment by AdamJNavarro** [comment]
Hey @gollkn,

This is not possible in a Managed project. You'll have to use the Custom (ejected) workflow. Also, please direct these types of questions to our [forums](http://forums.expo.io) as we intend to keep Github issues reserved for bugs!

Cheers,
Adam
