### ISSUE TITLE
Trouble with creating a project

### ISSUE THREAD

**Issue by Hayko1994** [expo/expo#354]
When I am trying to create project there are several errors are causing:
 1) says unable to init git repo  of expo git not installed while I have git on my mac 
2) there are a huge number of unmet peer dependency errors
3) after some period shows  warning not using expo fork of react native because of those issues
4)react-native link command even shows not found . 
By the way I am using mac so its not connected with windows usage. Also watchman and node are installed on my laptop.

**Comment by dantejauregui** [comment]
me too "Unable to initialize git repo. `git` not installed."   even i have installed in Mac

**Comment by nfarias5** [comment]
I am having the same issue. @Hayko1994 were you able to solve this? Thanks

**Comment by jhlosin** [comment]
same error here..anyone has solution to this issue?
