### ISSUE TITLE
Google sign in Error

### ISSUE THREAD

**Issue by ThakurKarthik** [expo/expo#3540]
### Environment

 Expo CLI 2.10.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      npm: 6.8.0 - /usr/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.3.0 => 3.3.0 
    npmGlobalPackages:
      expo-cli: 2.10.1

Iam currently on non ejected Expo app

### Steps to Reproduce

(Write your steps here:)

1.Create a project in firebase and get the web client id with google authentication enabled.
2.Try to perform sign in with google with Expo.Google with the client id

### Expected Behavior

The app opens the google sign in page in browser mode with the chance to input the details of google account.

### Actual Behavior

Instead a error 400 pop's up even though i followed every step from Expo docs.
![screenshot_20190219-213016](https://user-images.githubusercontent.com/26309938/53084010-ff9c3480-3525-11e9-8153-ef76a8afbb88.png)

### Reproducible Demo

https://snack.expo.io/@karthik.01/socialintegration

**Comment by lfv89** [comment]
I'm getting the same error here... Maybe something Google OAuth2 configuration is missing?

**Comment by ohpax** [comment]
I updated my existing app from exp 31 to 32 and I have the same issue

**Comment by ThakurKarthik** [comment]
In the ejected app using the native react native module there was no issue,although the above issue is present in non ejected expo app.

**Comment by mcxsic** [comment]
Even though it looks like an issue with Expo, I've found a temporary solution:

**Solution**
- Keep using Expo SDK 32.
- Go Google Developer Console and create an Android Oauth2 Client ID and an iOS Oauth2 Client ID, as stated on the [SDK 31 documentation for the Google sign in](https://docs.expo.io/versions/v31.0.0/sdk/google/) (make sure that the package name is `host.exp.exponent`).
- Use the Android Client ID and iOS Client ID as it follows:
```javascript
import { Platform } from 'react-native';
export const isAndroid = () => Platform.OS === 'android';

const result = await Google.logInAsync({
    clientId: isAndroid() ? '<YOUR_ANDROID_CLIENT_ID>' : '<YOUR_IOS_CLIENT_ID>',
    scopes: ['profile', 'email']
});
```
**Explanation**
The main problem that I've seen is that even though on the new documentation the following is stated:
```javascript
const clientId = '<YOUR_WEB_CLIENT_ID>';
```
The truth is that internally the request is being called from the Expo app, and you can see that when you expand the request details on the error page:
<img width="256" alt="captura de pantalla 2019-02-23 a las 14 41 28" src="https://user-images.githubusercontent.com/5372190/53292593-741ae180-3779-11e9-8a01-29c966600769.png">
as you can see, it adds the package name `host.exp.exponent`.

Anyway, this will only work while you're in development or in the Expo app. If you create a standalone app, you need to use [Google Sign-In](https://docs.expo.io/versions/v32.0.0/sdk/google-sign-in/) and that's a complete different battle.

Also, it would be great if the documentation for SDK 32 it's clearer about how to create the Client ID, since it was clearer on previous versions. In addition, `@types/expo` still has the old structure ( this is what `Google.LogInConfig` looks in version `^32.0.3`):

```javascript
export namespace Google {
    interface LogInConfig {
        androidClientId?: string;
        androidStandaloneAppClientId?: string;
        iosClientId?: string;
        iosStandaloneAppClientId?: string;
        webClientId?: string;
        behavior?: 'system' | 'web';
        scopes?: string[];
    }
}
```
(PS: also weird things are happening with Firebase if you create an app inside your Firebase Project; using React Native + Login + Database these days can be nerve-wracking...)

**Comment by lfv89** [comment]
@mcxsic Your solution works locally, but when I build the app with:

```
expo build:android --keystore-path key.jks
```

And then I upload and download directly from Google Play, the problem stays...

**Comment by mcxsic** [comment]
@lfv89 yes, that only works on development. As I said in my previous message:
> Anyway, this will only work while you're in development or in the Expo app. If you create a standalone app, you need to use [Google Sign-In](https://docs.expo.io/versions/v32.0.0/sdk/google-sign-in/) and that's a complete different battle.

**Comment by lfv89** [comment]
@EvanBacon any thoughts?

**Comment by novuw** [comment]
Thank god! I thought I was the only person getting this. It's really frustrating. Would love to know if anyone finds a fix. I'm going to toy around with the standalone settings- hopefully that will work. Definitely possible they changed the module to working like the facebook one.

**Comment by waleCloud** [comment]
@novuw There's a temporary fix by @mcxsic https://github.com/expo/expo/issues/3540#issuecomment-466709365

**Comment by EvanBacon** [comment]
a legacy JS solution has been merged https://github.com/expo/expo/pull/3617

**Comment by lfv89** [comment]
Thanks @EvanBacon, any ideas when there will be a release with the fix?

**Comment by yareyaredesuyo** [comment]
Revised docs looks nice https://github.com/expo/expo/blob/72dcdb5a389310bcc9a028befb3d59d61bbc723c/docs/pages/versions/unversioned/sdk/google.md

but it does not reflected on latest docs ( https://docs.expo.io/versions/latest/sdk/google/ )

**Comment by lanbau** [comment]
i'm getting this error too. 

```
 async logInGoogle () {
        const clientId = 'xxx';
        const { type, accessToken, user } = await Google.logInAsync({ clientId });

        if (type === 'success') {
        /* `accessToken` is now valid and can be used to get data from the Google API with HTTP requests */
        console.log(user);
        }
    }
```

**Comment by yumikohey** [comment]
Gosh! I spent my a whole day, because the doc is wrong.
I followed this Youtube tutorial, which saved my day.
https://www.youtube.com/watch?v=ZcaQJoXY-3Q

Step1,
In google developer console,
when register an iOS client id, the app bundle ID should be  `host.exp.exponent`.

Step2,
The code should be
```
            const { type, accessToken, user } = await Google.logInAsync({
                behavior: 'web',
                iosClientId: 'xxx.apps.googleusercontent.com',
                scopes: ['profile', 'email']
            });
```

**Comment by hadnazzar** [comment]
Master documentation doesnt updated yet. 

Here is the handle Login  code 

```
_handleGoogleLogin = async () => {
    try {
      const result = await Expo.Google.logInAsync({
        androidClientId: 'yourID.apps.googleusercontent.com',
        iosClientId: 'yourID.apps.googleusercontent.com',
        scopes: ['profile', 'email'],
      });
      console.log(result)
      if (result.type === 'success') {
        Alert.alert(
          'Logged in!',
          `Hi ${result.user.name}! \n  ${JSON.stringify(result.user)}`,
        );
        return result.accessToken;
        } else {
          Alert.alert(
            'Cancelled!',
            'Login was cancelled!',
          );
          return { cancelled: true };
        }
      } catch (e) {
        Alert.alert(
          'Oops!',
          'Login failed!',
        );
        return { error: true };
      }
    }
```

**Comment by novuw** [comment]
This is for a stand-alone app?

**Comment by novuw** [comment]
And is this for a stand-alone app?
Thanks so much for responding!!

**Comment by danikane** [comment]
For standalone this is perfect:
https://github.com/EvanBacon/expo-google-sign-in-demo

I just want to point out I implemented out of curiosity Google Sign In on Android in just a couple of hours for both in-Expo and standalone app (browser-based AND native) including OAuth2 API keys and Firebase stuff. All thanks to amazing documentation and examples.

FYI using SDK 32. Expo ftw!

**Comment by novuw** [comment]
Thanks for replying Daniel. This is where my original error lies. When I followed the article’s instructions, I received the errors stipulated above. Any advice?
Thanks!

**Comment by danikane** [comment]
@novuw 
I presume you are talking about the error below AND you are working with browser-based authentication via the Google Expo export AND you are using SDK 32 with the latest Expo app that indeed had included the fix 😄
![image](https://user-images.githubusercontent.com/18037666/55675827-1c6faa00-58d1-11e9-861f-002a45da0013.png)

You would hit that error in DEV unless you have created a new OAuth 2.0 Client ID for **host.exp.exponent** package name.
Follow this:
https://blog.expo.io/google-sign-in-with-react-native-and-expo-9cac6c392f0e

You would hit that error in STANDALONE unless you have created another OAuth 2.0 Client ID for **your app's package name**.
Install/Extract OpenJDK for the **keytool** application and run this to get the fingerprint:
`
expo fetch:android:hashes
`
I only pass the **clientId** parameter, there is no **behaviour** anymore and there is no need for **scopes** I guess.
Hope this info will get you sorted out.

P.S. I will link this here too:
https://github.com/expo/expo/issues/3253

**Comment by novuw** [comment]
Oh shoot. Sorry! I thought this was on the error page I created. This is the problem I was having, although I was having the redirect one before I switched to the new documentations. Here’s a link to my problem: https://github.com/expo/expo/issues/3839
Thanks for being so friendly!

**Comment by novuw** [comment]
> @novuw
> I presume you are talking about the error below AND you are working with browser-based authentication via the Google Expo export AND you are using SDK 32 with the latest Expo app that indeed had included the fix 😄
> 
> ![image](https://user-images.githubusercontent.com/18037666/55675827-1c6faa00-58d1-11e9-861f-002a45da0013.png)
> 
> You would hit that error in DEV unless you have created a new OAuth 2.0 Client ID for **host.exp.exponent** package name.
> Follow this:
> https://blog.expo.io/google-sign-in-with-react-native-and-expo-9cac6c392f0e
> 
> You would hit that error in STANDALONE unless you have created another OAuth 2.0 Client ID for **your app's package name**.
> Install/Extract OpenJDK for the **keytool** application and run this to get the fingerprint:
> `expo fetch:android:hashes`
> I only pass the **clientId** parameter, there is no **behaviour** anymore and there is no need for **scopes** I guess.
> Hope this info will get you sorted out.
> 
> P.S. I will link this here too:
> #3253

@danikane 
I just followed your steps for a standalone app, and they worked perfectly, until I signed in. I was logged in into Google, but it said that "no external user agent flow in progress." Might you have any idea what this means?

**Comment by enekesabel** [comment]
For anyone struggling with this problem, I managed to solve it using AuthSession. This way you can use your web client credentials to authenticate.
`
import {AuthSession} from "expo";

// both can be found under https://console.developers.google.com/apis/credentials
const clientId = '<YOUR_WEB_CLIENT_ID>';
const clientSecret = '<YOUR_WEB_CLIENT_SECRET>';

const doAuth = async ()=>{
  const redirectUrl = AuthSession.getRedirectUrl();
  const result = await AuthSession.startAsync({
    authUrl:
      'https://accounts.google.com/o/oauth2/v2/auth?'
      + `&client_id=${clientId}`
      + `&redirect_uri=${encodeURIComponent(redirectUrl)}`
      + '&response_type=code'
      + '&scope=profile',
  });

  const response = await fetch('https://www.googleapis.com/oauth2/v4/token', {
    method: 'post',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      code: result.params.code,
      client_id: clientId,
      client_secret: clientSecret,
      redirect_uri: redirectUrl,
      grant_type: 'authorization_code',
    }),
  });

  const data = await response.json();
  /*
  "data" contains access_token and id_token needed for firebase credential login
  {
    "access_token": "access_token",
    "expires_in": 3599,
    "id_token": "id_token",
    "scope": "https://www.googleapis.com/auth/userinfo.profile",
    "token_type": "Bearer",
  }
  */
};
`

**Comment by novuw** [comment]
Thank you so much for responding! I actually managed to make it work by using the new auto method and changing my bundle Id to all lowercase letters. I have no clue why this worked, but it did.

**Comment by robertobrogi** [comment]
@novuw sorry can you explain your fix? i have the same problem...

**Comment by robertobrogi** [comment]
i find a fix!

behavior: 'web',
                scopes: ['profile', 'email'],
                androidClientId: Expo.Constants.appOwnership === 'standalone' ? PROPERTIES.ANDROID_STAND_ALONE_APP_CLIENT_ID : PROPERTIES.ANDROID_CLIENT_ID,
                iosClientId: Expo.Constants.appOwnership === 'standalone' ? PROPERTIES.IOS_STAND_ALONE_APP_CLIENT_ID : PROPERTIES.IOS_CLIENT_ID,
                androidStandaloneAppClientId: PROPERTIES.ANDROID_STAND_ALONE_APP_CLIENT_ID,
                iosStandaloneAppClientId: PROPERTIES.IOS_STAND_ALONE_APP_CLIENT_ID,
                webClientId: '274334129691-k9shjbjjttr3tfj39opodgr2llusucn0.apps.googleusercontent.com'

work in expo and app store

**Comment by novuw** [comment]
Hey Roberto,
I went through literally every post- this halted my development for a few months. I made a new expo project and changed my bundle Id to all lowercase characters (ex: one.two.com), and for some reason, I no longer had my redirect error. Must be a problem on Expo’s end, but it works in App Store and Expo App.
Good luck!
