### ISSUE TITLE
Detecting Android soft navigation keys 

### ISSUE THREAD

**Issue by eitanfr** [expo/expo#3542]
There is no way in react-native to know if an android device has soft navigations keys (the bottom buttons). For example, in Xaiomi Mi 8 the navigations keys are configurable and can be removed.
In my use case, My view changes if the device navigations keys are shown or not. 

From a quick search online I found a way to do it but it requires to write Android code and to use Native Modules (aka eject expo). [here](https://medium.com/@elliothesp/detecting-android-soft-navigation-keys-in-react-native-30163abd7113) .

### Environment
 expo: `31.0.6`
react:  `16.5.0`
react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => `0.57.1`

### Reproducible Demo
Similar issue demostrating the problem:
https://github.com/facebook/react-native/issues/14887

**Comment by AdamJNavarro** [comment]
Hey @eitanfr,

I'm a bit confused at this issue. I'm thinking you want this functionality added and if that's the case, please create a feature request here: https://expo.canny.io/feature-requests Though there may already be one so be sure to check for that. In the future please refrain from creating a github issue unless you have a reproducible bug relating to Expo.

All the best,
Adam
