### ISSUE TITLE
FacebookSDKStrings.bundle problem

### ISSUE THREAD

**Issue by weihuali0509** [expo/expo#3544]
I tried to submit the binary to App Store Connect and got the following error message back from Apple - 

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "XXX". Please correct the following issues, then upload again.
> 
> This bundle is invalid - The Info.plist file for /Payload/xxx.app/FacebookSDKStrings.bundle is missing or could not be read.
> 
> Invalid Bundle - The bundle at '/Payload/xxx.app/FacebookSDKStrings.bundle' does not contain a bundle executable.
> 
> Best regards,
> 
> The App Store Team

Does anyone also experience this problem?

**Comment by jocelyngirard** [comment]
Hi @weihuali0509 , I have experienced the same issue in my latests iOS standalone builds.

I tried again 1h ago, after updating expo-cli to 2.10.1.
This build pass the AppStore processing successfully.

Here my expo environment info : 

  Expo CLI 2.10.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: 32.0.2 => 32.0.2 
      @types/react: ^16.7.20 => 16.7.20 
      @types/react-native: ^0.57.29 => 0.57.29 
      @types/react-navigation: ^3.0.2 => 3.0.2 
      expo: ^32.0.5 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: 3.3.0 => 3.3.0 
    npmGlobalPackages:
      expo-cli: 2.10.1

Does it work on your side ?

**Comment by AdamJNavarro** [comment]
Hey @weihuali0509,

It appears that Apple has resolved this issue on their end and that users' builds are getting approved as expected. Let me know if that's not the issue and I'll be happy to re-open this issue.

Cheers,
Adam

**Comment by weihuali0509** [comment]
Confirmed - it is working as this morning :)
