### ISSUE TITLE
Publish failing with Travis CI build

### ISSUE THREAD

**Issue by AdamPD** [expo/expo#355]
Hi guys,

I'm trying to publish to Expo automatically in a CI build using Travis, but it's consistently failing.  I've tried a whole range of different things, but it always fails with "socket hang up" when trying to build the iOS bundle.

```travis@testing-docker-a713eda9-a00a-490a-a356-b314203e0716:~/build/pharmadata/tonic-app$ exp publish                                                       
[exp] Making sure project is set up correctly...                                                                                                           
\[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.                                                                        
[exp] Your project looks good!                                                                                                                             
[exp] Unable to find an existing exp instance for this directory, starting a new one...                                                                    
[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.                                                                         
[exp] Starting React Native packager...                                                                                                                    
[exp] Scanning 782 folders for symlinks in /home/travis/build/pharmadata/tonic-app/node_modules (8ms)                                                      
[exp] Loading dependency graph.                                                                                                                            
[exp] Running packager on port 19001.                                                                                                                      
[exp] Publishing...                                                                                                                                        
[exp] Building iOS bundle                                                                                                                                  
[exp] socket hang up                                                                                                                                       
Building JavaScript bundle [                                                                                                    ] 0%Error: socket hang up  
    at createHangUpError (_http_client.js:302:15)                                                                                                          
    at Socket.socketOnEnd (_http_client.js:394:23)                                                                                                         
    at emitNone (events.js:91:20)                                                                                                                          
    at Socket.emit (events.js:188:7)                                                                                                                       
    at endReadableNT (_stream_readable.js:975:12)                                                                                                          
    at _combinedTickCallback (internal/process/next_tick.js:80:11)                                                                                         
    at process._tickCallback (internal/process/next_tick.js:104:9)                                                                                         
```

Using node v7.10.0 and npm 4.2.0 (but I've tried a variety of versions with no difference).

I'm not quite sure how to debug the issue.

**Comment by AdamPD** [comment]
Interesting update.  If I debug my build and run `exp start` manually, the tunnel is created but nothing ends up listening on port 19001 (as if the packager has stopped, for some reason).  This would make sense the same thing is occurring on publish.

**Comment by giautm** [comment]
I seen this error couple times with Circle CI, too.

**Comment by dikaiosune** [comment]
@AdamPD are you building this on Travis' linux or mac machines? If on linux, have you increased the inotify watch limit?

**Comment by AdamPD** [comment]
@dikaiosune - I'm using the Linux machines.  Haven't increased the inotify watch limit - will investigate that.

**Comment by AdamPD** [comment]
@dikaiosune - this resolved the issue.  Running:

```
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl fs.inotify.max_queued_events=524288
sudo sysctl -p
```

before the publish solved the problem.

**Comment by giautm** [comment]
I getting same issues with Circle CI. Today, i build failed 22 times with this error. I can't set inotify on `circle.yml`, `sudo` permission not allowed. i have tried with Circle CI 2.0, that said:
```
#!/bin/bash -eo pipefail
sudo sysctl fs.inotify.max_user_watches=524288
sysctl: setting key "fs.inotify.max_user_watches": Read-only file system
Exited with code 255
```
Unhappy day.

**Comment by lsps9150414** [comment]
I'm getting this with Jenkins as well:
```bash
[philip@li515-121 cd-expo-md-mobile]$ ./node_modules/.bin/exp -V
43.0.0
[philip@li515-121 cd-expo-md-mobile]$ ./node_modules/.bin/exp whoami
[exp] Logged in as philip_mvpfastlane
[philip@li515-121 cd-expo-md-mobile]$ ./node_modules/.bin/exp p
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Unable to find an existing exp instance for this directory, starting a new one...
[exp] EACCES: permission denied, open '/var/lib/jenkins/workspace/cd-expo-md-mobile/.expo/packager-info.json'
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.
```

**Comment by enthal** [comment]
I'm using **CircleCI**, not Travis, but I leave this here for the next person... it works, but only if you don't need docker.  :(

---
Since inotify limits cannot be raised in the Circle 2.0 docker, I've gotten successful builds (and deploys with `exp publish`) by using a machine build (set `machine: true`) in `config.yml`... and (for my project) installing `yarn` as part of the build.  I've left these changes only on the `deploy` branch.

```
version: 2
jobs:
  build:
    # Allow increase of inotify limit to support watchman for exp publish.
    # This should only be on the deploy branch.
    # See  https://circleci.com/docs/2.0/executor-types/
    machine: true
    steps:
      ...
      - run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update && sudo apt-get install yarn
      - run: yarn install
```

Good luck.  It's an unfortunate limitation in the environment for docker in CircleCI 2.0.  Hope they fix it soon.

**Comment by Avinashkoganti1** [comment]
> Can successfully publish on my local mac but getting this error with Jenkins as well:
> 
> ```shell
> [philip@li515-121 cd-expo-md-mobile]$ ./node_modules/.bin/exp -V
> 43.0.0
> [philip@li515-121 cd-expo-md-mobile]$ ./node_modules/.bin/exp whoami
> [exp] Logged in as philip_mvpfastlane
> [philip@li515-121 cd-expo-md-mobile]$ ./node_modules/.bin/exp p
> [exp] Making sure project is set up correctly...
> [exp] Your project looks good!
> [exp] Unable to find an existing exp instance for this directory, starting a new one...
> [exp] EACCES: permission denied, open '/var/lib/jenkins/workspace/cd-expo-md-mobile/.expo/packager-info.json'
> [exp] Set EXPO_DEBUG=true in your env to view the stack trace.
> ```
> 
> Tried but no luck.
> 
> ```
> sudo sysctl fs.inotify.max_user_watches=524288
> sudo sysctl fs.inotify.max_queued_events=524288
> sudo sysctl -p
> ```
> It used to work on Jenkins. Seems it start to fail after updating expo to v19.0.0.

Hi Isps could you post the jenkins file you used for build and publish expo app
