### ISSUE TITLE
Rename @expo/vector-icons to expo-vector-icons

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3550]
cc @tcdavis as this may impact Snack.

The purpose for this is to make the import style consistent with unimodules, eg: `expo-camera`.

- [ ] Rename and publish package
- [ ] Update the vector icons directory
- [ ] Update expo package dependency to point to expo-vector-icons
- [ ] Update babel preset to remap @expo/vector-icons to expo-vector-icons, and also warn users that the old package name is deprecated

**Comment by AdamJNavarro** [comment]
Adding a note that https://github.com/expo/react-native-fade-in-image and https://github.com/expo/react-native-action-sheet should get the same treatment to maintain consistency. Can create separate issues for each if you think that'd be better @brentvatne.

**Comment by cruzach** [comment]
adding `sentry-expo` to list of modules to rename

**Comment by EvanBacon** [comment]
Should be called `expo-font-icons`

**Comment by ccheever** [comment]
@EvanBacon what is the reason for calling it expo-font-icons? just want to make sure i'm doing the right thing if i work on this?

**Comment by Simek** [comment]
@brentvatne Is this request still valid? 🙂

**Comment by brentvatne** [comment]
@Simek - it's a nice to have but not really a priority
