### ISSUE TITLE
selfhosted apps: make them compatible with ejected apps

### ISSUE THREAD

**Issue by quinlanj** [expo/expo#3553]
eg https://forums.expo.io/t/ios-missing-bundled-scripts-and-assets-in-ipa-wont-work-offline/19575

**Comment by rxhivzero** [comment]
any help will be appreciated

**Comment by Charlie-Hua** [comment]
@quinlanj Would you please point me a direction that I may patch to make it work? Thanks!

**Comment by cruzach** [comment]
Hi! Expokit was deprecated in this last SDK release (38) in favor of the bare workflow. Additionally, `expo-updates` and `expo-cli` have both received substantial updates to supporting self hosted apps- a bare workflow app supports `expo export` 😄  If you see any issues with this workflow, you should open a new issue with details on what's not working, and please include a reproducible demo!
