### ISSUE TITLE
Docs on main app file rename don't work

### ISSUE THREAD

**Issue by mbluemer** [expo/expo#3554]
Relevant section in docs: 
https://docs.expo.io/versions/latest/sdk/register-root-component/#what-if-i-want-to-name-my

Error being returned:
![image](https://user-images.githubusercontent.com/5315473/53209847-d3f27a80-3609-11e9-89f5-ec2505c8a2ea.png)

I start a new project with `expo init TestProject` and then proceed to make the relevant changes mentioned in the documentation.

For reference, my `src/main.js` file:
```javascript
import Expo from 'expo';
import React from 'react';
import { View } from 'react-native';

class App extends React.Component {
  render() {
    return <View />;
  }
}

Expo.registerRootComponent(App);
```
and `package.json`:
```json
{
  "main": "src/main.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
```

**Comment by AdamJNavarro** [comment]
Hey @mbluemer,

As of SDK32 importing `Expo` as a whole can only be done via `import * as Expo from 'expo` or you can import the specific module you need via `import {registerRootComponent} from 'expo`. Can you let me know if changing your import statement fixes it for you?

Cheers,
Adam

**Comment by mbluemer** [comment]
Hey @AdamJNavarro,

That works! I guess no surprise, looks like I must have been looking at some version other than latest, my bad.

Thanks for the quick response!

**Comment by mbluemer** [comment]
Actually weird follow up: If I click the link I posted, or click the link on the side nav bar, I get the proper code snippet for latest. If I search the site for `registerRootComponent` and navigate from the search bar it shows the incorrect snippet despite having the same URL and showing "latest" on the version selector.

I think there may be a bug in the site.

**Comment by AdamJNavarro** [comment]
Ah, yeah this is an issue with our caching with Algolia. We're tracking that issue internally so I'm going to close this issue. Thanks for the report! Glad you got it working!

**Comment by mbluemer** [comment]
Steps to reproduce not exactly the same behavior but something similar locally:
1. Load up site, make sure you're on latest
2. search for `registerRootComponent` and follow result, should bring you to the latest docs
3. click "quick start", this will bring you to the quick start page and change your version to v32.0 rather than latest
4. search for `registerRootComponent` and follow result, this will bring you to the `registerRootComponent` docs page and set your version to v28.0
