### ISSUE TITLE
Expo CLI docs should explain how to use it

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3555]
Not so useful in its current form: https://docs.expo.io/versions/v32.0.0/workflow/expo-cli/

**Comment by brentvatne** [comment]
Related and also in need of love:
https://docs.expo.io/versions/v32.0.0/workflow/logging/
https://docs.expo.io/versions/v32.0.0/workflow/development-mode/
https://docs.expo.io/versions/v32.0.0/workflow/debugging/

**Comment by amandeepmittal** [comment]
Hi @brentvatne I'd love to help with this particular docs. Please point me or let me know what exactly is the requirement here? 

Also, this line isn't clear from end-user POV: `The web interface you to use some of the most often used features from a quick-to-use graphical interface.` 

IMO, it could be, `The web interface you use has some of the most common used features such as [list some features] or [provide a screenshot] .` 

Providing a screenshot or listing GUI features will help, especially, the new users.

**Comment by Simek** [comment]
@brentvatne Is the current workflow page for CLI any better, or it still need to be updated?

* https://docs.expo.dev/workflow/expo-cli

**Comment by brentvatne** [comment]
@Simek - i think the current docs are fine but we could maybe do better still. that said, it may not be worth investing in this at the moment given that we're hoping to move a bunch of these commands directly to the expo package
