### ISSUE TITLE
Expo not returning token with getExpoPushTokenAsync on iOS Expo Client

### ISSUE THREAD

**Issue by Miraj98** [expo/expo#3562]
### Environment

```
    Expo CLI 2.11.2 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.6 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
```

### Steps to Reproduce

1. Copy paste the `async function registerForPushNotificationsAsync()` from the Expo Push Notification docs: https://docs.expo.io/versions/latest/guides/push-notifications/
2. Add a line of code to log the token value:  `console.log(token)`
2. Call the async function from `componentDidMount()`

### Expected Behavior

The Expo Push Token should be console logged. 

### Actual Behavior

The app is asking for permission and after giving permission it is being 'granted' successfully. Next I am using `let token = await Notifications.getExpoPushTokenAsyn()` to get the token but it never returns anything. The `fetch` call below the above line is never executed, meaning it gets stuck in the Async call above. I am facing this issue only in the Expo Client app for iOS. It is working perfectly fine for android.

### Reproducible Demo

https://snack.expo.io/@miraj98/push-notification-bug

**Comment by AdamJNavarro** [comment]
Hey @Miraj98,

I just ran your Snack and got a token as expected. Can you let me know if you're still encountering this issue and if so, what version of the iOS Expo Client your device is running?

Cheers,
Adam

**Comment by Miraj98** [comment]
Hey @AdamJNavarro,

Updating the iOS client solved it. Sorry for bothering you with such a simple issue. Closing the issue.
