### ISSUE TITLE
Vulnerabilities due to 'braces' required manual review

### ISSUE THREAD

**Issue by sehranhas** [expo/expo#3563]
### Environment

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.6.14
```

App Target: Expo Client iOS

### Steps to Reproduce

1. Run `npm install` with `"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz"` in the package.json file. (Same issue exists for v32 as well.)
2. Run `npm audit`

### Expected Behavior

I expected to have 0 npm vulnerabilities

### Actual Behavior

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ 340b3518123802ac26ca07db89ab5d6501b95589ee8f3698d28756bafeb… │
│               │ [dev]                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ 340b3518123802ac26ca07db89ab5d6501b95589ee8f3698d28756bafeb… │
│               │ > metro-core > jest-haste-map > micromatch > braces          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/786                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 69 low severity vulnerabilities in 37481 scanned packages
```

### Proposed Solution

Can we please update the metro version to 0.52.0 [here](https://github.com/expo/react-native/blob/exp-latest/package.json#L174) to fix this issue?

**Comment by ide** [comment]
Expo doesn't depend on Metro directly. This is better addressed in the RN repo. If you would like to patch Metro locally I think digging into [Yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) maybe would work.

**Comment by sehranhas** [comment]
@ide my project does not use yarn it uses npm and package-lock.json. Ideally the issue should be addressed within the forked react-native repo not by yarn.

**Comment by ide** [comment]
The longer-term fix is to address this upstream. A short-term fix would be to use Yarn, or to wait otherwise. Many of these npm package vulnerabilities have threat models that are different from how they are used here and therefore aren't relevant (DoS doesn't make much sense in this local context...).
