### ISSUE TITLE
jest snapshots missing icons

### ISSUE THREAD

**Issue by garfieldnate** [expo/expo#3566]
Regarding this line here: https://github.com/expo/vector-icons/blob/master/createIconSet.js#L39

When you run snapshot tests using `react-test-renderer` and your rendered component contains an icon from Expo's vector-icons, then the resulting snapshot doesn't contain the icon text or any styling information because the font hasn't been loaded yet. If the tests take long enough, at some point the font will load and the snapshots will contain the styling. This is confusing, inconsistent behavior for tests.

### Environment

 > Expo CLI 2.10.1 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 4.4.12 - /usr/local/bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.10.1

### Project Demoing the Issue

[expo-icon-test.zip](https://github.com/expo/expo/files/2897732/expo-icon-test.zip)

1. Run `yarn` 
2. Run `npm test`. Both `Example-bad-test.js` and `Example-good-test.js` should pass.
3. Inspect the snapshots. The `Example-bad` snapshot contains no styling information and no icon text. The `Example-good` snapshot contains the styling and icon text because the workaround noted below was applied to the test. 

### Workaround

The test must allow the font to finish loading before creating the snapshot:

    import { Ionicons } from '@expo/vector-icons';
    import { Font } from 'expo';
    beforeAll(() => {
      return Font.loadAsync(Ionicons.font);
    });

Of course, if the icon is from FontAwesome, then that should be pre-loaded instead of Ionicons above.

### What is Needed

This needs to be documented in expo-jest, expo-vector-icons, a list of gotchas somewhere, or all of these places. I will gladly write the documentation and send a PR if you could suggest to me the best place for it.

I'm not sure that the current behavior makes sense. If the screen is shown with empty text elements with no styling, then it might look really funny for a moment until the fonts are loaded. Not having the icon is, of course, understandable, but without styling the spacing of the elements on the screen could become very strange. I think it would make more sense to write a text element with all of the requested styling, but containing a single invisible character the same size as an icon (assuming that icons are all the same size). Then nothing on the screen would move around after the font is loaded.

**Comment by ide** [comment]
If I understand correctly, this is part of a larger class of issues where your test is dependent on some state (in this case, whether the font is loaded) that you don't deterministically control in your test. Other examples of issues in this class would be if your test depended on the current time or the existence of some files on disk without mocking the time/FS libraries or preparing the FS to be an expected state before the test. In essence, this isn't specific to fonts.

Depending on what your unit under test is, I would either mock the font library or do something like your `beforeAll(() => Font.loadAsync(Ionicons.font))` so that your preconditions are known before you run your test; deterministic preconditions of your unit under test should lead to deterministic postconditions.

Mocking the font library is probably a better choice since it isolates you from external network I/O. If you don't take the mocking approach, running `beforeAll(() => Font.loadAsync(Ionicons.font))` still exposes you to external network failures that are part of your unit under test but out of your control and you can't make that deterministic.

**Comment by garfieldnate** [comment]
I did not think about the fact that the font loading could be a network request. Usually for data or time sources I would rely on some kind of provider injection rather than using a resource directly somewhere and requiring the client to deal with it (I come from Java land). That said, I am new to working with UI code and have never thought about having to injecting a font provider.

As being able to write unit tests is pretty important, I guess the next thing needed would be a list of Expo resources that are loaded in the background that affect rendering and therefore unit tests.  I do not know how to mock out the font loading but I can look into it and share whatever solution I find. I think this would be useful for the next person trying to take a snapshot of a component with an icon.

**Comment by ide** [comment]
DI: a mock test environment like Jest's adds DI to the JS module system where you can swap out the modules (dependencies) that are imported (injected via the mock module graph). That mental model carries over here if we're talking about DI as a general concept.

List: It's something that would be ever-changing as new APIs are added and old ones are removed. The cost of keeping a list is probably too expensive and I'd prefer to have no list than a wrong list.

**Comment by garfieldnate** [comment]
I was going to try to mock the Font loading or the Ionicons lib, but in the end it was too difficult to figure it out properly so I abandoned that.

There is another easy workaround for testing snapshots with icons:

    Ionicons.state = {"fontIsLoaded": true};

This is in my opinion dirtier than the solution I provided in my opening comment, and may break if the Expo font class structure is changed. However, it will prevent any attempt to load a font from disk, which might be desired.

I thought I would need to at least provide the glyph map which determines the character ID to display from the icon font, but react-test-renderer always prints these icons as , or U+F100 (https://unicodes.smpc.io/%EF%84%80). This means that it is not actually meaningful to test the icon text value in the snapshot output (although we should still test that the font, styling, etc. are set correctly, which requires loading or pretending to load the font.). 

@ide Unless you think there is actionable information here, you can close this. It is at least good documentation for any googlers looking for a solution.
