### ISSUE TITLE
Android and Expo Multi Window problem

### ISSUE THREAD

**Issue by NiwuoDev** [expo/expo#3567]
### Environment

Expo CLI 2.10.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
    npmPackages:
      @types/react-native: ^0.57.37 => 0.57.37 
      expo: ^32.0.0 => 32.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.1.5 => 3.1.5 

- Android, and Standalone

## 🐛 Bug Report

Hi, I want to know if is there any support or something that I can use when the user uses the multi window of Android, because when I use it Expo or even the APK restart the app then load but using the last size of screen.  In example, my device have 600 of height so the app render with that size in mind. Then after the app open I want to multi window it, so the app restart, the new height should be 50% or 300, but it renders with 600, so I have to manually in the code made a reload like Ctrl + S to get that height of 300 and the app will load fine. 

IMG 1: APP - NORMAL SIZE
![image](https://user-images.githubusercontent.com/21696326/53301721-63737580-3824-11e9-8f2b-822f47a97164.png)

IMG 2: APP - AFTER MULTI WINDOW
![image](https://user-images.githubusercontent.com/21696326/53301741-9a498b80-3824-11e9-85b0-24b9f34cf6d3.png)

IMG 3: APP - READY ON MULTI WINDOW
![image](https://user-images.githubusercontent.com/21696326/53301749-adf4f200-3824-11e9-857a-51ab0079689f.png)

If you see there buttons still way to big because is getting height 680 when it should be 50% of that.
## To Reproduce

 1. Open Expo or even the APK generated by expo
2. After the app is open, use the button of android to check all the open apps.
3. Activate multi window to Expo or APK 
4. Then you can see the app will load but with bad dimesions.
## Expected Behavior

IMG 1: APP - NORMAL SIZE
![image](https://user-images.githubusercontent.com/21696326/53301721-63737580-3824-11e9-8f2b-822f47a97164.png)

IMG 2: APP - AFTER MULTI WINDOW
![image](https://user-images.githubusercontent.com/21696326/53301741-9a498b80-3824-11e9-85b0-24b9f34cf6d3.png)

IMG 3: APP - READY ON MULTI WINDOW
![image](https://user-images.githubusercontent.com/21696326/53301802-3a9fb000-3825-11e9-87e5-0731e0412252.png)

## Code Example

 You don't need any code example you can test with any Expo app I guess

**Comment by ziponia** [comment]
For anyone landing here from search: this was root-caused in 2026 — it is **not** an RN surface limitation, it's a **multi-display density mismatch**, and it's fixable today.

- react-native-screens converts px→dp with the process-global (phone) density in its Fabric state sync, collapsing Stack/NativeTabs content into a `1/density` box: software-mansion/react-native-screens#4159 (fix: software-mansion/react-native-screens#4160)
- react-native core's `DisplayMetricsHolder` is initialized once and never updated → text clips on different-density displays: facebook/react-native#57183
- Full write-up, reproducer and an Expo config-plugin workaround: expo/expo#46844 / https://github.com/ziponia/rn-multidisplay-density-repro

*Disclosure: authored by Claude (an AI coding agent) on behalf of and supervised by @ziponia; validated on their physical device (Galaxy S25 Ultra + DeX) and reviewed before posting.*
