### ISSUE TITLE
Problem in expo docs

### ISSUE THREAD

**Issue by ThakurKarthik** [expo/expo#3568]
The examples link in payments page of expo docs is down or not working.
### Steps to Reproduce

1.Visit the link [Payments Docs](https://docs.expo.io/versions/latest/sdk/payments/)
2.Click on examples link in the beginning

### Expected Behavior

Takes me to the examples page of expo github repo

### Actual Behavior

Redirected link is not working.

### Screenshot
1.Here is the link not working.
![screenshot from 2019-02-25 02-33-31](https://user-images.githubusercontent.com/26309938/53305380-0371e300-38a7-11e9-90aa-e6d62f3e19ed.png)
2.Here is what happened on clicking the link
![screenshot from 2019-02-25 02-32-14](https://user-images.githubusercontent.com/26309938/53305276-9f025400-38a5-11e9-8ccb-6c82c13b2fce.png)

**Comment by sjchmiela** [comment]
Hey, @ThakurKarthik! Sorry for the confusion, examples indeed has been moved to https://github.com/expo/expo/tree/master/packages/expo-payments-stripe/examples. Would you care to create a pull request changing https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/payments.md and optionally https://github.com/expo/expo/blob/master/docs/pages/versions/v32.0.0/sdk/payments.md? 🙂

**Comment by ThakurKarthik** [comment]
yes iam on it.
