### ISSUE TITLE
Location.getCurrentPositionAsync({}); not return in Emulator

### ISSUE THREAD

**Issue by mreorhan** [expo/expo#3570]
### Environment
System:
OS: Windows 10
Binaries:
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.3.0.0 AI-182.5107.16.33.5199772
NPM Packages:
"expo": "^32.0.0",
"react": "^16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-navigation": "^2.18.2",
"react-redux": "^5.0.7",
"redux": "^4.0.0",
"redux-promise-middleware": "^5.1.1",
"redux-thunk": "^2.3.0"

This issue happening in real android device. (Samsung Galaxy S8)

### Steps to Reproduce
I tried Location.getCurrentPositionAsync({}); function. But I function not return anything on emulator. (Android 7). By the way, location high accuracy is open

But when i tried on my telephone, its working well

### Expected Behavior
GPS Location

(Write what you thought would happen.)

### Actual Behavior
Not return

`
export async function _getLocationAsync() {
  let { status } = await Permissions.askAsync(Permissions.LOCATION);
  if (status !== 'granted') {
    alert(strings('permission.location_error'))
    return
  }
  let gpsServiceStatus = await Location.getProviderStatusAsync()
  if (gpsServiceStatus.locationServicesEnabled) {
    let location = await Location.getCurrentPositionAsync({});
   console.log("not return and this log is not seeming");
    try {
      await AsyncStorage.setItem('location', JSON.stringify(location));
      console.log("lca"+location)
    } catch (error) {
      console.log("Async get location error")
    }
    return location
  }
  else
    return false
};`

**Comment by AdamJNavarro** [comment]
Hey @mreorhan,

Would you be able to put your code into a [Snack](http://snack.expo.io) so we can try test it out on our end? Also, what emulator platform are you using?

Cheers,
Adam

**Comment by mreorhan** [comment]
> Hey @mreorhan,
> 
> Would you be able to put your code into a [Snack](http://snack.expo.io) so we can try test it out on our end? Also, what emulator platform are you using?
> 
> Cheers,
> Adam

[https://snack.expo.io/@mreorhan/get-location-test](https://snack.expo.io/@mreorhan/get-location-test)
My emulator is Android Studio's. Nexus 5X API24, Android 7.0, X86

> when i tried on my telephone, its working well

**Comment by goranefbl** [comment]
Why was this closed? Just testing on my emulator and again no location while on iPhone its working fine. Did you find a fix @mreorhan ?

**Comment by KBB99** [comment]
Try using[ this package](https://github.com/Agontuk/react-native-geolocation-service) instead:
`yarn add react-native-geolocation-service`
Apparently its a bug with React Native's current implementation of the geolocation API.
