### ISSUE TITLE
After making changes to app.js expo is still building the previous code version

### ISSUE THREAD

**Issue by ricardolousada** [expo/expo#3572]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

Expo CLI 2.10.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.2/9C32c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.10.1

I'm just testing with the IOS simulator

### Steps to Reproduce

(Write your steps here:)

1. I change my code in app.js
2. expo builds the code based on my old code, before the changes
3. So I always get the same error

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by tcdavis** [comment]
What command are you running to "build"
Have you only reproduced on simulator?  Simulator for which platform?
Have you tried to clear packager caches? (delete and reinstall dependencies, expo start --clear)

**Comment by ricardolousada** [comment]
Hello Davis, thank you for your kick replay, and i'm sorry about anything less clear but i'm just starting...Regarding your questions:

What command are you running to "build" - When i mean building is just saving the app.js with changes then I would expect an automatic change in the simulator but the s Expo’s Developer Tools gives-me an error based on the code before the change. I'm I being clear?

Have you only reproduced on simulator? Simulator for which platform? IOS simulator

Have you tried to clear packager caches? (delete and reinstall dependencies, expo start --clear)No because i thought that using hot reloading wouldn't need this!?

**Comment by AdamJNavarro** [comment]
Hey @ricardolousada,

Sounds like there may be a caching issue on the simulator. I would try [reseting the simulator's content and settings](https://stackoverflow.com/questions/2763733/how-to-reset-iphone-simulator) and see if that helps.

Also, I would recommend against using hot reloading as it doesn't work particularly well in JS. We're planning on pushing a change to the Clients to indicate this (https://github.com/expo/expo/issues/3326)

Cheers,
Adam

**Comment by ricardolousada** [comment]
Thank you @AdamJNavarro I will close the issues it's the same as #3326
