### ISSUE TITLE
Notification category (createCategoryAsync) on iOS does not yield interactive notifications

### ISSUE THREAD

**Issue by nathanziarek** [expo/expo#3573]
### Environment

```
Expo CLI 2.10.1 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.10.1
```

**Target**: iOS

### Steps to Reproduce

1. Open Snack
2. Tap "Notify". If you get a message in "Notification Payload" you know push notifications are working.
3. Tap "Delayed Notify" and close app. A notification will appear with no interactive features. (Alternatively, you can send yourself a notification using the Expo notification tool).

### Expected Behavior

When the notification arrives, you should be able to "open" the notification (deep press on iOS) and see two buttons (labeled One and Two).

### Actual Behavior

The notification comes through but does not feature any interactive features.

### Reproducible Demo

https://snack.expo.io/@nathanziarek/interactive-notifications

![image](https://user-images.githubusercontent.com/1020351/53369796-a0696600-3911-11e9-94d6-9a8eee3b9805.png)

**Comment by sjchmiela** [comment]
Hey, @nathanziarek! Good job on the demo! Check out https://snack.expo.io/@sjchmiela/interactive-notifications, I've made some changes that make the demo work ok, most notably:
- use `_category` as the key of the `categoryId` when sending the notification request to Expo server,
- use `${experienceId}:welcome` as the value of the `_category`
- (note that the third button won't show without `buttonTitle`!)

**Comment by nathanziarek** [comment]
Excellent! Thank you so much. I made a small edit to the documentation to reference this. Trying to give back with the world's tiniest pull request. https://github.com/expo/expo/pull/3583
