### ISSUE TITLE
No cache exists for this resource: shell-app.bundle

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#3574]
### Environment
```
  Expo CLI 2.11.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.10.1 - ~/.nvm/versions/node/v9.10.1/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v9.10.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.11.1
```

Happening on an iPhone 7. iOS 12.1.4

### Steps to Reproduce
1. The user opens the app, and gets the white page, with the "There was a problem running "xxxx" Try again".
Below, the grey error message: "No cache exists for this resource: shell-app.bundle"
2. The user press "Try again", and it works properly.

### Expected Behavior
No error

### Actual Behavior
The error.

### Reproducible Demo
I can't add a reproducible demo. I can't even reproduce it again in any device.

### My app.json
```json
{
  "expo": {
    "name": "NoFilter",
    "icon": "src/styles/imgs/nofilter-icon.png",
    "splash": {
      "backgroundColor": "#000",
      "resizeMode": "cover",
      "image": "src/styles/imgs/splash-screen-ph.png"
    },
    "version": "2.0.5",
    "slug": "xxxxxx",
    "sdkVersion": "32.0.0",
    "scheme": "nofilter",
    "assetBundlePatterns": [
      "node_modules/@expo/vector-icons/fonts/MaterialCommunityIcons.ttf",
      "node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf",
      "node_modules/@expo/vector-icons/fonts/Feather.ttf",
      "node_modules/@expo/vector-icons/fonts/SimpleLineIcons.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Regular.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Medium.ttf",
      "src/styles/fonts/Montserrat/Montserrat-SemiBold.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Bold.ttf",
      "src/styles/imgs/nofilter-icon.png",
      "src/styles/imgs/nofilter-logo-v.png",
      "src/styles/imgs/splash-screen-ph.png",
      "src/styles/imgs/splash-screen-ph.jpg"
    ],
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "xxx",
            "project": "xxxx",
            "authToken": "xxxxf"
          }
        }
      ]
    },
    "ios": {
      "buildNumber": "2.0.5",
      "bundleIdentifier": "xxxx",
      "config": {
        "googleMapsApiKey": "Axxxxx"
      },
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "NoFilter uses your location to see how far you are from spots, and also to show you your position in the map",
        "NSPhotoLibraryUsageDescription": "NoFilter uses your library when you want to upload a photo",
        "NSPhotoLibraryAddUsageDescription": "NoFilter uses your library when you want to upload a photo"
      }
    },
    "android": {
      "versionCode": 25,
      "package": "xxxx",
      "config": {
        "googleMaps": {
          "apiKey": "xxxxx"
        }
      },
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ]
    }
  }
}
```

I didn't ejected the App.
While building the app, I have 3 terminals open. One with `yarn start` running (wich executes `expo start`), in PRODUCTION mode, and then 2 another terminals building one for iOS and another for Android.
Then I downloaded the IPA and APK, and published it on the app store.

**Comment by BrodaNoel** [comment]
I asked the last person saw this issue if he was using internet mobile connection in the moment that opened the app.

He told me:
1. He opened the app for first time after the last App update (so, he updated the app in the App Store, and the next time that he opened the app, he saw this error)
2. **He is really convinced that the internet was NOT working at that moment**, due to he was actually using another App that stopped working (something similar to internet connection issues), so then he decided to close that another app and open mine (moment where he see the error)


So, the scenario was something like:

* Opened the App Store and updated my app (NoFilter)
* He didn't open the app after updating it.
* He opens, let's say, Instagram, and he see after a while that Instagram was not working (and he is convinced that he saw some errors similars to when the internet is not working)
* He closed Instagram
* He opened my app, and there he saw the error.
* He presed on "Try Again" and it works automatically

**Comment by BrodaNoel** [comment]
I have another question related to this:
I'm currently using Sentry to track the errors in the app. It's tracking perfectly all the errors that are happening in the code that I write, but, is there a way to track even these kind of errors with Sentry? I'd like to have most of the code covered with Sentry, just to have a better context about which users are having problems with the app.

**Comment by AdamJNavarro** [comment]
Hey @BrodaNoel,

Based on your reports, do you know if this has occurred on both iOS or just one of them?

Cheers,
Adam

**Comment by BrodaNoel** [comment]
@AdamJNavarro Did you try to say "both OS"?
I only received this error report from 1 device. An iPhone 7, iOS 12.1.4

**Comment by AdamJNavarro** [comment]
Oops. I meant to say "both iOS and Android". 🙃 Alright, thanks for clarifying.

**Comment by esamelson** [comment]
Hey all -- sorry for the slow followup here. This has been fixed in production. You'll need to rerun `expo build:ios` to get a new version of the client with the fix. Thanks very much for reporting this!!

**Comment by shaneosullivan** [comment]
Hi @esamelson , we just saw this happen on iOS, non-dev mode, from an app build a few days ago.  Are you certain it's fixed?

**Comment by esamelson** [comment]
@shaneosullivan a message like this can have multiple causes, unfortunately 😞 could you open a new issue with more information and, ideally, steps to reproduce the issue?
