### ISSUE TITLE
import {Location} from 'expo' pulls in wrong typescript types for LocationOptions

### ISSUE THREAD

**Issue by devlinb** [expo/expo#3576]
### Environment

  Expo CLI 2.11.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

dependencies from package.json:

```
"dependencies": {
    "@expo/vector-icons": "^9.0.0",
    "expo": "^32.0.0",
    "firebase": "4.8.0",
    "moment": "^2.22.1",
    "prop-types": "^15.6.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-collapsible": "^0.9.0",
    "react-native-elements": "^1.0.0",
    "react-native-google-matrix": "0.0.3",
    "react-native-modal-selector": "0.0.27",
    "react-native-selection-group": "^0.4.1",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-status-bar-height": "1.0.1",
    "react-navigation": "^2.17.0",
    "react-navigation-fluid-transitions": "^0.2.74",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-thunk": "2.2.0"
  }
```

### Steps to Reproduce

```
import { Location } from 'expo'

function getLocation() {
    var accur = Location.Accuracy;
    const options: LocationOptions = { accuracy: Location.Accuracy.High };
}
```

### Expected Behavior

Typescript is happy

### Actual Behavior
Namespace '"<stuff>/node_modules/@types/expo/index".Location' has no exported member 'Accuracy'

If I look at the exported namespace Location in index.d.ts I see

```

export namespace Location {
    interface LocationOptions {
        enableHighAccuracy?: boolean;
        timeInterval?: number;
        distanceInterval?: number;
    }
/* cut */
```

I can see the proper types in node_modules/expo-location/Location.ts

If I am just using Typescript + Expo wrong please let me know, thanks!

**Comment by tcdavis** [comment]
We're still in the process of converting all of our modules to typescript, and recommend using the definitely typed one's until that's completed.
