### ISSUE TITLE
[expo-firebase] 2.0.0 firebase.firestore.FieldValue.serverTimestamp() crashes app (when using set with merge set to true)

### ISSUE THREAD

**Issue by redpandatronicsuk** [expo/expo#3584]
I can use the following code:

```
firebase.firestore().doc('foo/bar').set({
  last_changed: firebase.firestore.FieldValue.serverTimestamp()
})
``` 

and

```
firebase.firestore().doc('foo/bar').update({
  last_changed: firebase.firestore.FieldValue.serverTimestamp()
})
```

, but

```
firebase.firestore().doc('foo/bar').set({
  last_changed: firebase.firestore.FieldValue.serverTimestamp()
}, { merge: true })
```

crashes the app.

**Comment by AdamJNavarro** [comment]
Hey @redpandatronicsuk,

Can you try checking the device logs in Xcode to see if there is any insight on what may be causing the crash?

Cheers,
Adam

**Comment by redpandatronicsuk** [comment]
Hi @AdamJNavarro 

First of all, all three code examples crash the app. I was trying to figure out what cause the error and forgot to uncomment the line with `serverTimestamp()` in it before testing `update` and `set` without `{ merge: true }`.

Xcode doesn't show much, I get

```
libsystem_kernel.dylib`__pthread_kill:
    0x110af1234 <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x110af1239 <+5>:  movq   %rcx, %r10
    0x110af123c <+8>:  syscall 
->  0x110af123e <+10>: jae    0x110af1248               ; <+20>
    0x110af1240 <+12>: movq   %rax, %rdi
    0x110af1243 <+15>: jmp    0x110aeb3b7               ; cerror_nocancel
    0x110af1248 <+20>: retq  
```

and

```
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

Not sure which one is the device log, Xcode confuses me :)

In the stack of the thread that crashes, I think the last code it runs is line 116 in `node_modules/expo-react-native-adapter/ios/EXReactNativeAdapter/EXNativeModulesProxy/EXNativeModulesProxy.m`. I've set a breakpoint on line 116 and see this:
<img width="1130" alt="screenshot 2019-02-26 at 20 49 17" src="https://user-images.githubusercontent.com/8609582/53442289-42b84500-3a09-11e9-8cc9-b5c1ff8449cb.png">

Is any of this useful? Woult it help if I pasted the contents of my `package.json` and `Podfile`?

**Comment by JamesMcIntosh** [comment]
See issue [2943](2943)

**Comment by redpandatronicsuk** [comment]
Thanks @JamesMcIntosh the fix you proposed seems to work.

Have you made a PR for this? @EvanBacon could you make a release (maybe 2.0.1) on npm with that fix please.

Cheers,
Dominik

**Comment by redpandatronicsuk** [comment]
I couldn't find a PR, so made one here: https://github.com/expo/expo/pull/3598

**Comment by redpandatronicsuk** [comment]
Expo firebase is deprecated now, so I'm closing this.

**Comment by JamesMcIntosh** [comment]
@redpandatronicsuk Just wondering where you saw Expo Firebase being deprecated?

**Comment by redpandatronicsuk** [comment]
@JamesMcIntosh on any `expo-firebase-*` npm page, such as here: https://www.npmjs.com/package/expo-firebase-app
There is a deprecation warning in beg red letters near the top of the page.
