### ISSUE TITLE
Using iOS and Android together does not work for me on Expo XDE

### ISSUE THREAD

**Issue by raarts** [expo/expo#359]
From other issues I read that it should be possible or even trivial, but whenever I start the second one, the first one complains on a red screen about Runtime not being ready for debugging. 

Am I missing some secret sauce?

**Comment by jimmylee** [comment]
Hi @raarts, I'm sorry you're having this problem. To clarify are you trying to build and demo the application on Android and iOS at the same time?

**Comment by raarts** [comment]
I am trying to live-compare my changes on both iOS and Android, having both set to hot-reloading. So press save in my editor, and see both of them update.

**Comment by terribleben** [comment]
Hi, unfortunately this is an underlying problem with the way hot reloading is implemented in React Native. Only one device can listen to these updates. There are [various issues](https://github.com/facebook/react-native/issues/14334) about it upstream so we'll just wait for it to get fixed there.
