### ISSUE TITLE
Cancel push notification in Expo

### ISSUE THREAD

**Issue by narefyev91** [expo/expo#3595]
Expo provides dismiss push notification by ID on android, but when this feature would be available on IOS? Because right now it's needed to eject from expo, and use native libraries to dismiss received push notification

**Comment by cruzach** [comment]
Hey @narefyev91 ,

Thanks for bringing this up, but it belongs over at our [Feature Requests](https://expo.canny.io/feature-requests). There, you can check to see if it's already been requested and planned, and if not you can put in a request for it. 

This way, we can keep this space specifically for issues.

Thank you!
