### ISSUE TITLE
AdMob support

### ISSUE THREAD

**Issue by ibrahim9** [expo/expo#36]

**Comment by terribleben** [comment]
fwiw, we added Facebook Ads support in SDK 15, though we're still currently working on docs. For now, here's the code: https://github.com/expo/exponent-sdk/tree/master/src/FacebookAds

**Comment by aswinmohanme** [comment]
Adding AdMob would be a Big plus, It's the only thing Lacking as of Now I think

**Comment by Kepro** [comment]
same here I don't want to eject expo :(

**Comment by terribleben** [comment]
We're moving feature requests over to canny, this one is tracked [here](https://expo.canny.io/feature-requests/p/google-admob).
