### ISSUE TITLE
Disable requirement for internet access to manually input IP in expo app

### ISSUE THREAD

**Issue by jkulubya** [expo/expo#360]
Hi,
I'm on a network where internet access is through a proxy. I tried getting the expo tooling to run behind a proxy and failed. That's ok, I have a development server on my local network and the target phone (physical and emulator) is on my local network. The issue is that if the expo app cannot reach the internet, it doesn't let you manually enter an ip as shown below.

Step 1 - Tries to connect to expo servers
![expo-issue](https://user-images.githubusercontent.com/7911793/28114317-a2e430fc-6700-11e7-8c13-a4d8ccaae9bd.png)

Step 2 - Times out and doesn't give an option to manually enter the IP
![expo2](https://user-images.githubusercontent.com/7911793/28114326-a727511c-6700-11e7-8171-458e411d6498.png)

To show that I can hit the server without needing an internet connection
![expo3](https://user-images.githubusercontent.com/7911793/28114390-07ef146c-6701-11e7-8ba6-c7d5cf0d4d40.png)

I can't rely on scanning the QR code on the physical device because sometimes it encodes the wrong IP address.

Is it possible to have an input where I can manually enter the ip without having to connect to the internet?

**Comment by terribleben** [comment]
I think the best solution for now is to paste from clipboard, yeah. There is also a "+" button on the Projects tab you can click to manually input a URL. Let me know if you're still blocked or think this should remain an open issue.
