### ISSUE TITLE
In the Chinese part, the OTA Updates.fetchUpdateAsync() is very slowly.

### ISSUE THREAD

**Issue by dajohnny** [expo/expo#3608]
Hey, All!

Sorry, please forgive me for not being good at English.

I am very grateful to the official for providing such a good framework, which greatly improved our development efficiency. Today, online user feedback updates in China are very slow, troubleshooting found Updates.fetchUpdateAsync () problems, Chinese users need to go through a long wait to load resources! I want to know if there is a solution?

Can I Hope that？：
1. Can the official provide a progress API for Updates.checkForUpdateAsync? Helps to enhance the user experience;
2. Second, Can we manage the dynamic resources of the latest hot updates? and give them to Chinese users through CDN? This will help retain more Chinese users and increase the download speed of users!

I am very much looking forward to the official reply, if you can tell me anyway, I would be grateful!

### develop environment:
```
  Expo CLI 2.10.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.3.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.0.4 => 3.0.4 
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.10.1
```

Snack: https://snack.expo.io/@dajohnny/example-expo-ota-update-prompt

Cheers,
Johnny

**Comment by brentvatne** [comment]
I replied to your email:

Hi there,

You might want to host your app on your own servers to make it faster to download in China: https://docs.expo.io/versions/latest/distribution/hosting-your-app/

We use Cloudfront and Amazon S3, which works very well in most places in the world but perhaps could be slower in China due to the firewall.

Best,
Brent
