### ISSUE TITLE
[expo-camera] Major rework

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#3612]
## `expo-camera` rework plan

_This issue be will updated along with the work progress._

## Android
- [ ] preserve all functionalities from the [docs](https://docs.expo.io/versions/latest/sdk/camera/)
- [ ] remove `Camera1` API completely in favour of `Camera2` API.
- [ ] camera preview should preserve aspect-ratio of the actual image provided from the sensor
- [ ] preview should be cropped (either horizontally or vertically) to fill view (iOS works this way).
- [ ] new feature: focusing on a given point of the camera view.

## iOS
- [ ] preserve all functionalities from the [docs](https://docs.expo.io/versions/latest/sdk/camera/)

## both platforms
- [ ] prevent camera from accepting children components
- [ ] allow continued video recording (original from here: #1887)

**Comment by otaviogaiao** [comment]
Nice! There is also an issue when a view is rendered on top of the camera component on Android: https://github.com/expo/expo/issues/3495

Would be happy to help with whatever I can.

**Comment by goldleon** [comment]
I have the same issue using Samsung S9+ with Pie

**Comment by otaviogaiao** [comment]
Any progress on this?

**Comment by edoantonioco** [comment]
Huawei P10 and Camera2 api doesnt get along well last time I tried few months ago. Just to take in consideration. Maybe now it works fine.

**Comment by xiCO2k** [comment]
Hey Guys, any update on this task?

Thanks

**Comment by bbarthec** [comment]
@xiCO2k, unfortunately this issue is suspended right now and I cannot guarantee any accurate date of resuming work on it 😞

**Comment by xiCO2k** [comment]
@bbarthec Thanks, curious about that since I'm making the cropping for the android myself :)

**Comment by raphaelbadia** [comment]
@xiCO2k mind sharing your implementation ?

**Comment by TheWirv** [comment]
Is this rework still happening?

**Comment by bbarthec** [comment]
@TheWirv, unfortunately there's no camera rework happening at this moment nor in the nearest future.
