### ISSUE TITLE
AuthSession in webview, is it possible?

### ISSUE THREAD

**Issue by alexlvovich** [expo/expo#3616]
I don't know how about you, but when chrome is opened over your app is ugly and bad user experience. 
Is there any option to make it run in embedded browser, popup. I can find any example related to this topic. don't you guys work tightly with PMs as I do :)

### Environment

 Expo CLI 2.11.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by brentvatne** [comment]
you can't use a webview for this. apple will reject your app if you don't use a modal like authsession does.
