### ISSUE TITLE
Standalone android app is stuck on loading screen

### ISSUE THREAD

**Issue by Bundas** [expo/expo#362]
Hi, I've developed an app, I built it (using **Expo 18**), installed on android 7 and I tried to turn it on, but I get stuck on loading screen. I can see only the animation of Expo logo and nothing else, even after 10 minutes of loading. It doesn't work on internet nor offline. 

I've signed NDA, so I can not show you source code or screens, but If you tell me what you need to see to debug, I will post you a censored version of that code :D

The app works perfectly in development mode in expo.

**Comment by terribleben** [comment]
Hi, thanks for the report. It's going to be hard to help debug without much transparency into what you're building. Here are some things I can think of:

- If you're comfortable sending your published app url to me or @jesseruder we can try loading it ourselves and diagnosing.
- I'd double check if you're using the `<AppLoading />` component in your JS and think about what cases might be different in production.
- I'd try running the app from XDE with development mode turned off and seeing if that makes a difference.

**Comment by dikaiosune** [comment]
Hi! Sorry that you were hitting this problem. Since we didn't hear from you I'm assuming that you weren't able to help us reproduce the issue. If you'd still like help with this, please post back and we'll reopen the issue. Thanks!
