### ISSUE TITLE
Bare React Native App, Permissions, status always resolves to denied. 

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#3621]
I created bareReact Native app, with expo-cli and trying to use permissions but getting denied as status without any prompt to ask for permissions.

```
import {

Permissions,

} from ‘@unimodules/core’;
```

using it like: 

```
async componentDidMount() {

const { status } = await Permissions.askAsync(Permissions.LOCATION);

alert(status);

}
```

**I also tried installing expo-permissions. Getting same results. Please guide me.If I am using this wrong. (Platform: Android)**

**Comment by sjchmiela** [comment]
Hey, @shubhamdeol! I have just created a bare React Native application with `expo-cli` and `granted` is being shown. What is your `@unimodules/core` version?

**Comment by sjchmiela** [comment]
I think this should help you solve your issue: https://medium.com/@notbrent/if-you-initialize-again-this-will-be-resolved-i-added-a-bunch-of-default-optional-permissions-to-882704943edf. 🙂
