### ISSUE TITLE
Expo Tunnel URL was mistake

### ISSUE THREAD

**Issue by dajohnny** [expo/expo#3623]
Hi All,

I found that I created a new Expo project in the local area and found the following problems.
I wish like that "exp://192.168.123:1900", I should be how to do that?

![image](https://user-images.githubusercontent.com/17939743/53625241-200a7400-3c35-11e9-9a9a-0aefcc8d930b.png)

**Comment by sjchmiela** [comment]
Hey, @dajohnny! This longer scheme is an indication that you have ejected your project. Since you've ejected your project you won't be able to open it in Expo Client and this is why the scheme is modified.

**Comment by dajohnny** [comment]
Okay. I got it. Thank you @sjchmiela
