### ISSUE TITLE
Support "subtitle" on iOS in expo-server-sdk

### ISSUE THREAD

**Issue by tonyxiao** [expo/expo#3627]
According to apple's [docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification), on iOS push notification can have `title`, `subtitle` and `body` keys. 

![image](https://user-images.githubusercontent.com/696842/53647918-6ccd5b00-3bf3-11e9-87cc-3ff096896c4f.png)

However, `expo-server-sdk` only supports `body` and `title`. 

![image](https://user-images.githubusercontent.com/696842/53647991-971f1880-3bf3-11e9-9959-a8b7b640514f.png)

**Comment by AdamJNavarro** [comment]
Hey @tonyxiao,

Thanks for bringing this up. As this is more so a feature request than a bug, I'm going to ask if you can create a Feature Request on our [Canny board](https://expo.canny.io/feature-requests). We try our best to reserve github issues for bugs to keep things organized. With that said, I'm going to close this issue.

All the best,
Adam

**Comment by tonyxiao** [comment]
Thanks. Opened https://expo.canny.io/feature-requests/p/support-subtitle-for-ios-push-notification-in-expo-server-sdk
