### ISSUE TITLE
Pedometer only gets the last 7 days on iOS

### ISSUE THREAD

**Issue by Oakyden** [expo/expo#3629]
### Expected Behavior

Pedometer to get steps for the range of dates provides to Pedometer.getStepCountAsync(start, end)

### Actual Behavior

Pedometer gets the last 7 days steps on iOS even if healthkit has months of steps recorded (things act as expected on Android and get steps much further back)

I have seen this across 3 different iOS devices

### Reproducible Demo

https://snack.expo.io/@alanlatus/ios-pedometer-issue

(snack has to be opened on a real device due to needing google fit / health kit data)

**Comment by AdamJNavarro** [comment]
Hey @Oakyden,

Just for clarification, is this only occurring on SDK32? Only reason I ask is 32 is the default version when creating a Snack.

Cheers,
Adam

**Comment by Oakyden** [comment]
I think i've been seeing this the whole time i've used Expo which i think is since 25 / 26, but it's only really come to my attention now as i am specifically making a steps related app

**Comment by sjchmiela** [comment]
As [Apple Pedometer documentation](https://developer.apple.com/documentation/coremotion/cmpedometer/1613946-querypedometerdatafromdate?language=objc) explains:
> Only the past seven days worth of data is stored and available for you to retrieve. Specifying a start date that is more than seven days in the past returns only the available data.

so I'm afraid we won't be able to fetch more data from the device. I'll add a note about this to the documentation. Thanks for bringing this up!

**Comment by Oakyden** [comment]
ah, what a shame. They could definitely up that!
