### ISSUE TITLE
not using fork expo repo from github also shows not dimensions set for key window 

### ISSUE THREAD

**Issue by Hayko1994** [expo/expo#363]
When I am trying to run a app it shows not using fork expo. Also when I am opening an app on ios simulator it says not dimensions set for key window.... Can you help me to solve those problems?

**Comment by terribleben** [comment]
Hi, you need to use Expo's fork of react native if you are developing an Expo App. That means `package.json` will show something like this: `"react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz"`

For future questions, it's a good idea to ask for help on the [forums](https://forums.expo.io) unless you think you've found an issue with Expo.
