### ISSUE TITLE
Add warnings when static permissions config isn't present

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3630]
It'd be useful whenever we need permissions to add a static check like this: https://github.com/react-native-community/react-native-cameraroll/blob/4777d0554612f816e9c9714028f58e613231a383/ios/RNCCameraRollManager.m#L338-L345 - then if people forget to add it in their bare app they can be guided by the error message.

**Comment by EvanBacon** [comment]
Xcode automatically does this and we surface simulator error messages in `expo run:ios`.

**Comment by brentvatne** [comment]
i suspect now that we surface this from `expo run:ios`, it will help. i created this issue because i saw a trend of people omitting the description key and then being confused about how to resolve the issue. i believe the behavior is often for the app to crash outright in this situation - a warning or a red screen is preferred imo.
