### ISSUE TITLE
Android simulator not running

### ISSUE THREAD

**Issue by ricardolousada** [expo/expo#3634]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

 Expo CLI 2.10.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.2/9C32c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.10.1

I'm targeting for IOS and Android but the Android simulator does not run

### Steps to Reproduce
1. When tun on the Android simulator i have the follow error in the Expo Dev Tools

"Couldn't start project on Android: Error running adb: This computer is not authorized to debug the device. Please follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory."

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by cruzach** [comment]
Hi @ricardolousada ,

First, go ahead and try out the solutions commented on [this github issue](https://github.com/expo/expo/issues/490). Let me know if that fixes the problem

Thanks!
Charlie

**Comment by ricardolousada** [comment]
Hello @cruzach,

It did not work for me...I have the Android simulator running but the error is the same! Any other recommendation? 

Thank you

**Comment by cruzach** [comment]
@ricardolousada ,

Alright, next step I'd suggest is to provide us with some more information. Comb through your event logs and see where something is failing. Post those logs here and hopefully we can get a fix for you soon!

**Comment by ricardolousada** [comment]
Hi @cruzach,

Thanks again for your help :) I start with YARN start and then even with the Android simulator the app does not run there. I use IOS and don't have and Android phone to do the configurations suguested. In the simulator does options don't exist.
Cheers

**Comment by cruzach** [comment]
Hey @ricardolousada ,

Without a reproducible demo, it's hard for us to effectively help you and troubleshoot the issue.
