### ISSUE TITLE
expo payments stripe does not display email or phone fields

### ISSUE THREAD

**Issue by sehranhas** [expo/expo#3636]
### Environment

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.6.14
```

### Steps to Reproduce

1. Eject from Expo Client to ExpoKit
2. Add the following to Podfile and run `pod install`.
```
  pod 'EXPaymentsStripe',
    :path => "../node_modules/expo-payments-stripe/ios",
    :inhibit_warnings => true
```
3.  Added the following code
```
import { PaymentsStripe as Stripe } from 'expo-payments-stripe';

class TestComponent extends React.Component {
   	componentWillMount() {
		Stripe.setOptionsAsync({
			publishableKey: <SOME_KEY>
		});
	}

   	async openAddCardView() {
		try {
			const options = {
				requiredBillingAddressFields: 'zip',
                                 prefilledInformation: {
                                     email: 'test@email.com',
                                     phone: '123456789'
                                 } 
			};
			const token = await Stripe.paymentRequestWithCardFormAsync(options);
		}
		catch(error) {

		}
	}
}
```

### Expected Behavior

Expected to see the email and phone fields in the 'Add a Card' view

### Actual Behavior
![screen shot 2019-03-02 at 11 58 44 pm](https://user-images.githubusercontent.com/8731417/53691231-4f110a80-3d47-11e9-8c9a-0efbd1059ff8.png)

**Comment by Szymon20000** [comment]
`prefilledInformation` always pertain to 'billingAddress' or 'shippingAddress'. You can see an example [here](https://docs.expo.io/versions/v32.0.0/sdk/payments/#example). More about it [here](https://stripe.dev/stripe-ios/docs/Classes/STPUserInformation.html#/c:objc(cs)STPUserInformation(py)shippingAddress).

**Comment by sehranhas** [comment]
@Szymon20000 yes however in your first link it states that `billingAddress` or `prefilledInformation` accept an `email` or `phone` param as well but they do not work when I pass these params in.
