### ISSUE TITLE
Location.getCurrentPositionAsync({}); not return in Emulator

### ISSUE THREAD

**Issue by mreorhan** [expo/expo#3638]
Environment
System:
OS: Windows 10
Binaries:
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.3.0.0 AI-182.5107.16.33.5199772
NPM Packages:
"expo": "^32.0.0",
"react": "^16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
"react-navigation": "^2.18.2",
"react-redux": "^5.0.7",
"redux": "^4.0.0",
"redux-promise-middleware": "^5.1.1",
"redux-thunk": "^2.3.0"
My emulator is Android Studio's. Nexus 5X API24, Android 7.0, X86

Steps to Reproduce
I tried Location.getCurrentPositionAsync({}); function. But I function not return anything on emulator. (Android 7). By the way, location high accuracy is open

But when i tried on my telephone, its working well

Expected Behavior
GPS Location

(Write what you thought would happen.)

Actual Behavior
Not return

Demo
https://snack.expo.io/@mreorhan/get-location-test

**Comment by cruzach** [comment]
Hi @mreorhan ,

I opened up the snack you provided and ran it on the Android simulator, and was able to correctly receive my location. Could you try again and see what happens? What does the 'location' promise resolve to?

Thanks!
Charlie

**Comment by mreorhan** [comment]
> Hi @mreorhan ,
> 
> I opened up the snack you provided and ran it on the Android simulator, and was able to correctly receive my location. Could you try again and see what happens? What does the 'location' promise resolve to?
> 
> Thanks!
> Charlie

In my emulator, not answering function. and not writing anything. But Im trying on samsung s8 (real device). Its working well.
Why its happening? I dont understand.

**Comment by cruzach** [comment]
@mreorhan ,

Could you try out [this snack](https://snack.expo.io/@charliecruzan/get-location-test) and let me know if it works appropriately in the android simulator? Make sure the simulator has Locations permission.

Thanks!
Charlie

**Comment by mreorhan** [comment]
> @mreorhan ,
> 
> Could you try out [this snack](https://snack.expo.io/@charliecruzan/get-location-test) and let me know if it works appropriately in the android simulator? Make sure the simulator has Locations permission.
> 
> Thanks!
> Charlie

Screenshot: [https://serving.photos.photobox.com/164433191c289e31bd5b6e2232ef211ce4df1b25e3baccfaa55d9b19cad4f20dd6c15ce4.jpg](url)

**Comment by cruzach** [comment]
@mreorhan, that link doesn't take me to a screenshot, it links to https://github.com/expo/expo/issues/url

**Comment by mreorhan** [comment]
> @mreorhan, that link doesn't take me to a screenshot, it links to https://github.com/expo/expo/issues/url

[Screenshot link](https://serving.photos.photobox.com/164433191c289e31bd5b6e2232ef211ce4df1b25e3baccfaa55d9b19cad4f20dd6c15ce4.jpg)

**Comment by mreorhan** [comment]
@cruzach It doesnt work. Why did you close this issue?

**Comment by cruzach** [comment]
We need a reproducible demo to troubleshoot the issue, however the demo you provided seems to work as it should. 

If you can provide a Snack that reproduces the bug, then I'll definitely re-open the issue!

**Comment by goranefbl** [comment]
Same problem here and besides this, navigator.geolocation.getCurrentPosition does not return anything, it just times out. Location is enabled on emulator. Besides emulator, same happens on real device. Could it be a different android version? Which version where u using @mreorhan ?

**Comment by AdamJNavarro** [comment]
Hey @mreorhan  and @goranefbl,

Can you see if any of the ideas discussed in this [SO post](https://stackoverflow.com/questions/38247350/emulators-location-simulation-not-working) help to remedy this? Also, Goran can you try using Expo's `Location` API rather than RN's `Geolocation` API?

**Comment by goranefbl** [comment]
Hi Adam,

I tried with both Expo and RN. But after the latest testing it is working on real devices, so it has to be something with emulator setup and not with expo, you can close this issue. 

Thanks for help.

**Comment by brentvatne** [comment]
@AdamJNavarro @cruzach - we should add info about how to use geolocation in emulator
