### ISSUE TITLE
[expo-camera] Could not find com.google.android:cameraview:1.0.0

### ISSUE THREAD

**Issue by gmaclennan** [expo/expo#3639]
### Environment

Standalone
@unimodules/core v0.2.0
react-native v0.58.5
expo-camera v3.0.0
Android SDK 28.0.3

### Steps to Reproduce

Followed the steps in packages/expo-camera/README.md

```
cd android 
./gradlew assembleDebug
```

### Expected Behavior

Expected to build without issue on Android

### Actual Behavior

 I get an error `Could not find com.google.android:cameraview:1.0.0.` from `':app:debugRuntimeClasspath'` `Required by: project :app > project :expo-camera`

This might be a docs issue - am I missing an install step? I’m wondering if there is something from the android sdk components that I am missing? I’ve tried installing everything that seemed potentially relevant. 

### Reproducible Demo

Git commit adding expo-camera on branch where this fails:

https://github.com/gmaclennan/mapeo-nodejs-mobile/commit/54e29920899b596954efb4ffe8250fb6f57ec50f

**Comment by sjchmiela** [comment]
Hey, @gmaclennan, thanks for reporting the problem! The simplest fix would be https://github.com/gmaclennan/mapeo-nodejs-mobile/pull/1. I thought this would work, but it looks like it doesn't:

https://github.com/expo/expo/blob/8864b1cd7ce15f5f9e058360d6474e2d02d455fd/packages/expo-camera/android/build.gradle#L59-L61

**Comment by gmaclennan** [comment]
Thank you @sjchmiela this fixes it. I can send a PR to update the docs if needed.

**Comment by jpudysz** [comment]
It didn't work for me. Any other ideas?

**Comment by brentvatne** [comment]
sorry about that missing bit of info! updated the README accordingly, much appreciated
