### ISSUE TITLE
How to use 'react-native-google-places' or anyway to use kind of place picker in Expo without detach??

### ISSUE THREAD

**Issue by hai2014bk** [expo/expo#364]
Hi guys, now i facing this problem: I need to use place picker (i chose 'react-native-google-places' library) but it not supported by Expo, that mean i cant ` react-native link` it to my project. And sure, i don't want to `detach` my project.

So anyone has anyway to do this?? 
Thanks you so much

**Comment by ccheever** [comment]
What parts of this module require native code? Is it the UI or the network requests ... or something else?

**Comment by terribleben** [comment]
Hi, we're adding a [geocoding](https://github.com/expo/expo/pull/315) API in our next release. Will that solve your problem?

**Comment by aswinmohanme** [comment]
Try https://github.com/FaridSafi/react-native-google-places-autocomplete

It's entirely JavaScript and works beautifully for my expo project.

**Comment by terribleben** [comment]
Seems like this is resolved, let me know if I should reopen.

**Comment by hai2014bk** [comment]
@aswinmohanme i have to use it, but that isn't a good way, 'cause i want to place picker, not just autocomplete text of the place, haizzz

**Comment by hai2014bk** [comment]
@terribleben pls noti me when you finish your geocoding, thank you
