### ISSUE TITLE
Video: `onReadyForDisplay` never called on iOS if the video format is .m3u8

### ISSUE THREAD

**Issue by magiskaoskar** [expo/expo#3649]
### Environment

Expo CLI 2.6.14 environment info:
System:
    OS: Windows 10
Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
    Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

App target: iOS
iOS version: 12.1.3

The function passed to `onReadyForDisplay` on the Video component is never called on iOS if the video has the `.m3u8` format.
It is working fine on Android.

### Steps to Reproduce

1. Create a new project with expo.
2. Add a `Video` component.
3. Set the source prop to a .m3u8 formatted video.
If you don't have a .m3u8 video you can use this one: https://content.jwplatform.com/manifests/aFlgP0Hz.m3u8
4. Set Video `style` prop to `{ width: 200, height: 200 }`
5. Set Video `onReadyForDisplay` prop to a function.

### Expected Behavior

The function passed to `onReadyForDisplay` should be called when the video is ready for display.

### Actual Behavior

Function passed to onReadyForDisplay is never called.

### Reproducible Demo

https://snack.expo.io/SkPdLp5IE

**Comment by shirohana** [comment]
Same problems here with difference env.

K | V
--- | ---
OS | MacOS 10.14.3
Expo SDK | v33
Expo CLI | 2.21.1
Detached | true
Target | iPhone 6 in iOS 12.3.1 with XCode

Tried `.mp4` works but `.m3u8` won't.
