### ISSUE TITLE
React.PropTypes is no longer supported

### ISSUE THREAD

**Issue by crazyx13th** [expo/expo#365]
hi there,

I started logging with `import * as Expo from 'expo'; // start logging`
But then i got these Messages:
```
[exp] Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
[exp] Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
[exp] Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
```

if I only use `import {Logs} from 'expo'; // start logging` I got the first two messages

Expo requires `react-native-maps` and `lottie-react-native`
Both uses the old PropTypes way...

Second Message... yeah not easy, because a lot of Modules using React.createClass at the moment :-)

```
"expo": "18.0.9",
"react": "16.0.0-alpha.12",
"react-native": "github:expo/react-native#sdk-18.0.0",
```

thx
greetings crazyx13th

**Comment by dikaiosune** [comment]
Hi! Unfortunately this is an issue due to upstream dependencies for React Native. Hopefully React 16 will be stable in the near future and everyone will move to the new APIs. In the meantime, these warnings shouldn't impact the functionality of your app, even though they are annoying :).
