### ISSUE TITLE
Preloading images doesn’t work with capInset

### ISSUE THREAD

**Issue by holgersindbaek** [expo/expo#3652]
I’m having an issue with setting capInset on an image, when that image is preloaded.

If I don’t preload the image, then it works fine, but there's a lag in loading the image. If the image is preloaded then an image with the wrong density is chosen:

![screenshot 2019-03-02 at 13 50 57 copy 1](https://user-images.githubusercontent.com/698979/53758857-34fa3800-3ebf-11e9-9d45-a56f3c3062f9.jpg)

### Environment

  Expo CLI 2.11.6 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.11.6

### Steps to Reproduce

Preload image and create image with capInset.

### Expected Behavior

The correct image density is expected.

### Actual Behavior

The image density is wrong

### Reproducible Demo

https://snack.expo.io/@holgersindbaek/capinset-bug

It's not possible to replicate the bug in the browser. Download the example and run it in the simulator or on the phone.

**Comment by cruzach** [comment]
Hey @holgersindbaek ,

Sorry you're having this issue, but when I downloaded and ran the example you provided on my iPhone, and on the simulator (iPhone 6s, same as your screenshot), I didn't experience this bug. 

Our environments are also almost exactly equal (maybe it has something to do with your connection?), so I would re-run this and see if you still get the same issue.

Thanks!
Charlie

**Comment by holgersindbaek** [comment]
@cruzach I definitely still have this issue. Both on the simulator and in the expo app on my iPhone 6s.

Are you sure you changed "preloadImages"? 

Do you have any idea what could be different in our environment?

**Comment by cruzach** [comment]
@holgersindbaek I'm sure, changing 'preloadImages' in the state from 'true' to 'false' has no effect.

Is there a step I'm missing somewhere?

**Comment by holgersindbaek** [comment]
No. That should be it.

That should be it. I just tested again by downloading the snack and running locally. I get the same blurry images corners with too big corners (because of the wrong density). It happens both on iOS 12.1 iPhone 6 simulator and when running from the Expo app on my iPhone 6.

Are you sure our environment is the same? Do you have any idea what could be going on?

**Comment by holgersindbaek** [comment]
@cruzach Have you still not been able to reproduce the bug? What in our environments do you think could be different?

I think it might be related to this bug: https://github.com/facebook/react-native/issues/22383

**Comment by AdamJNavarro** [comment]
I just tried reproducing as well with an iPhone 7s running the latest iOS and am unable to see any changes by toggling `state.preloadImages` between `true` and `false`.

**Comment by holgersindbaek** [comment]
Just downloaded and checked again. I'm still getting the same.

@AdamJNavarro Could you post an image of the screen you're seeing with "preloadImages" set to true and false? Is there anything in your environment that's different to mine?

**Comment by holgersindbaek** [comment]
@AdamJNavarro Are the corners of the figure pixelated on your phone? Does the figure look like image 1 or 2?

**Comment by cruzach** [comment]
Sorry @holgersindbaek, I must have missed the notification that you mentioned me. Are you still having trouble with this?
