### ISSUE TITLE
[expo-camera] mm-camera error mct_controller_handle_SOF_proc

### ISSUE THREAD

**Issue by gmaclennan** [expo/expo#3653]
### Environment

Standalone
@unimodules/core v0.2.0
react-native v0.58.5
expo-camera v3.0.0
Android SDK 28.0.3

### Steps to Reproduce

(Write your steps here:)

1. Add expo-camera to a new standalone RN project
2. Open camera view

### Expected Behavior

Camera works as expected, no errors in logs

### Actual Behavior

`adb logcat` shows the log filled with hundreds of error messages (they arrive at about 2-3 a second constantly while the camera is open):

```
Camera2ClientBase: notifyShutter: Shutter notification for request id 10000001 at time 6671351479767
03-04 20:04:12.885  1101  1101 D SDM     : DisplayBase::BuildLayerStackStats: LayerStack layer_count: 4, app_layer_count: 3, gpu_target_index: 3, display type: 0
03-04 20:04:12.917  1093  6319 E mm-camera: <MCT   ><ERROR> 1355: mct_controller_handle_SOF_proc: (sofdelay, curr_sofdelay) = (0, 0) kptr NULL
```

The camera does seem to work, it doesn't crash the app.

### Reproducible Demo

https://github.com/gmaclennan/mapeo-nodejs-mobile/tree/expo-camera

**Comment by cruzach** [comment]
Hey @gmaclennan ,

Have you only experienced this on Android, or does it occur on iOS as well?

Thanks!
Charlie

**Comment by gmaclennan** [comment]
I'm only developing on Android at the moment, so I haven't tested on iOS.

**Comment by gmaclennan** [comment]
Update: I see this error using react-native-camera v1.12.0 too. It might be phone related - I am testing on a Moto X4, running Android 9 (annoyingly Android auto-updated on my test phone this morning)

**Comment by bbarthec** [comment]
I'm tentatively closing this issue as it seems not to be Expo-related.
