### ISSUE TITLE
Upgrade from Expo 28 to 32 detached mode result in "Native module cannot be null" 

### ISSUE THREAD

**Issue by liuqimin323** [expo/expo#3654]
### Environment
Expo CLI 2.11.6 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/opt/node@8/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^1.5.11 => 1.6.1 
    npmGlobalPackages:
      expo-cli: 2.11.6

App's target (iOS, Android, Standalone, ExpoKit)

### Steps to Reproduce
1. I am following the documents  [upgrading-expokit](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit) and [expokit](https://docs.expo.io/versions/v32.0.0/expokit/expokit/#ios-1) to upgrade expo v28 to v32 and its detached branch.

2. I finally got everything working on my non-detached branch on my RN app. Now I am trying to upgrade the detached branch but the following error struck me.

3. after I twitch the AppDelegate.m and packages and pods and bable to resolve other errors, the following one turns out when I build with Xcode 

### Expected Behavior

It should build like a charm.

### Actual Behavior

The problem is that I don't even understand this error let alone how to handle it(there is nothing else print in the console from expo-cli). It points me to some files inside expo npm modules, ./node_modules/expo/tools/hashAssetFiles.js. which doesn`t make any sense to me :((

![simulator screen shot - iphone xs max - 2019-03-04 at 09 18 26](https://user-images.githubusercontent.com/16411009/53775754-9531af80-3ea8-11e9-90e9-5c9558c52d8d.png)

### Reproducible Demo

Unfortunately, I got my expo version working, it is my detached version that is having problems.

- I have tried to comment out everything in App.js and return just null, but the problem persists. 
- Google lead me to some similar cases which are caused by [push notification][4], but that doesn't see to be my problem.
I tried to comment out the codes in AppDelegate.m and doesn't help with the situation.

Maybe something wrong with my AppDelegate.m? 

[AppDelegate.m](https://github.com/expo/expo/files/2928987/AppDelegate.txt)
my pacakge.json
[package.json](https://github.com/expo/expo/files/2928979/package.txt)

**Comment by AdamJNavarro** [comment]
Hey @liuqimin323 ,

Can you make sure you have updated your Expo Client to the latest version?

Cheers,
Adam

**Comment by ibubbo** [comment]
@AdamJNavarro Hi,

I used require, and this exception also occurred.

expo: ^32.0.0.

Can updating expo solve this problem.

**Comment by tsapeta** [comment]
SDK28 and 32 are no longer supported so I'm closing this issue. If this issue still persists, feel free to create a new issue.
