### ISSUE TITLE
[expo-camera] recordAsync and FaceDetector at the same time

### ISSUE THREAD

**Issue by ndjemel** [expo/expo#3655]
### Environment

Expo Camera Universal module on a vanilla react native app
RN Version : 0.57.8
expo-camera : 2.0.0
expo-camera-interface: 2.0.0
expo-core : 2.0.0

### Steps to Reproduce

I have certain requirements within a video. I want the face to be in a certain part of the screen - if the face is out of bounds recording stops and the person has to try again, 

1. have an onFacesDetected response (as simple as console.log("we have a face"))
2. recordAsync

### Expected Behavior

onFacesDetected would call the related function when recordAsync is recording

### Actual Behavior

onFacesDetected no longer fires up.

**Comment by cruzach** [comment]
Hey @ndjemel ,

Unfortunately, as of right now that isn't possible. But, I encourage you to go to [our feature requests page](https://expo.canny.io/feature-requests) and find if this is already there, and if not, create a request 👍 

Good luck,
Charlie
