### ISSUE TITLE
ExpoVideoManagerConstants is undefined when using Video Component

### ISSUE THREAD

**Issue by naorzr** [expo/expo#3657]
Hey guys,

Using the video component from your api in a bare react native
getting "undefined is not an object evaluating ExpoVideoManagerConstants.ScaleNone"

this happens to me in the most minimal implementation of the component(using only source,resizeMode and style props)

getting the error on android simulator.

### Environment

  Expo CLI 2.11.2 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^31.0.0 => 31.0.12 
      @types/react: ^16.7.3 => 16.8.6 
      @types/react-native: ^0.57.7 => 0.57.38 
      react: 16.6.0 => 16.6.0 
      react-native: ^0.57.3 => 0.57.8 
    npmGlobalPackages:
      expo-cli: 2.11.2

**Comment by cruzach** [comment]
Hey @naorzr,

Thanks for linking all the environment info! Could you also provide a Snack or other code sample for us to use to reproduce this issue on our side?

Thanks!
Charlie

**Comment by naorzr** [comment]
@cruzach since expo snacks doesn't support importing none pure js npm packages, I've added a code example

tried it on a local android device this morning, and on the local device I wasn't getting the error, but the video wasn't loading either, no status update.
it just notified onLoadStart and then nothing..
tried to listen to  onLoad,onError .. nothing
```
import * as React from 'react'
import { View } from 'react-native'
import { Video } from 'expo-av'

class DemoComp extends React.Component {
  render() {
    return (
      <View style={{ height: 300, width: 300 ,backgroundColor: 'black'}}>
        <Video
          useNativeControls={true}
          source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
          rate={1.0}
          volume={1.0}
          isMuted={false}
          resizeMode="cover"
          style={{ width: 300, height: 300 }}
        />
      </View>
    )
  }
}

export default DemoComp
```

**Comment by sjchmiela** [comment]
What setup steps have you done to add `expo-av` to your bare React Native project? 🤔

**Comment by naorzr** [comment]
the one stated in the documentation, i've also added unimodules/core
It works well when running it on ios device

**Comment by sjchmiela** [comment]
Sorry for asking, but are you sure you've followed steps described in https://github.com/expo/expo/tree/master/packages/expo-av#configure-for-android?

**Comment by naorzr** [comment]
positive, i've rechecked just to be certain, and i've implemented them

**Comment by sjchmiela** [comment]
Thanks! I'll try to take a look and reproduce the problem tomorrow, in the meantime if you have some spare time you could help me by creating a reproducing repo on GitHub (but since this isn't a very advanced example I will make it myself quickly too).

**Comment by sjchmiela** [comment]
I have just created a bare RN app, installed `expo-av@4.0.0` and the code above worked without any problems. Could you please try installing latest versions of `expo-av` and `react-native-unimodules` into your project?

**Comment by naorzr** [comment]
@schellack i've installed the latest vr of expo-av and react-native-unimodules, the issue persists

**Comment by brentvatne** [comment]
@naorzr - care to share a reproducible example? it seems like it is an installation/configuration issue on your end

**Comment by naorzr** [comment]
well I've upgraded(to v.4+) the night before and the issue persisted, the day after it magically vanished..
I guess it has something to do with watchman or what not(even though i cleaned it up, reinstalled node_modules)
Thanks for all your time and help
