### ISSUE TITLE
Can't take picture with ImagePicker.launchCameraAsync

### ISSUE THREAD

**Issue by ewein** [expo/expo#3662]
I'm no longer able to take a picture using `ImagePicker.launchCameraAsync`. The call to this method seems to hang for a few seconds and then fail. It is occurring on both Android and iOS for me currently. However, selecting an image using `ImagePicker.launchImageLibraryAsync` works correctly. Running the following snippet on Android and iOS devices causes the following errors.

### Code
```
try {
    await ImagePicker.launchCameraAsync({
        quality: 1,
        allowsEditing: true
    });
} catch (err) {
    console.log(JSON.stringify(err));
}
```

### Android Error
`{"line":3212,"column":26,"sourceURL":"http://192.168.0.155:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fme%2FProjects%2Fproj-name%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js","framesToPop":1,"code":"EUNSPECIFIED"}`

### iOS Error
`{"line":3222,"column":26,"sourceURL":"http://192.168.0.155:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fme%2FProjects%2Fproj-name%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js","framesToPop":1,"code":"E_MISSING_PERMISSION","nativeStackIOS":["0   Exponent                            0x0000000103a3bbe0 ABI32_0_0RCTFBQuickPerformanceLoggerConfigureHooks + 727912","1   Exponent                            0x00000001039dfed8 ABI32_0_0RCTFBQuickPerformanceLoggerConfigureHooks + 351840","2   Exponent                            0x000000010394b58c ABI31_0_0RCTFBQuickPerformanceLoggerConfigureHooks + 1375744","3   CoreFoundation                      0x00000001860976a0 <redacted> + 144","4   CoreFoundation                      0x0000000185f76820 <redacted> + 292","5   CoreFoundation                      0x0000000185f7b22c <redacted> + 60","6   Exponent                            0x00000001039e0818 ABI32_0_0RCTFBQuickPerformanceLoggerConfigureHooks + 354208","7   Exponent                            0x00000001039e7a50 ABI32_0_0RCTFBQuickPerformanceLoggerConfigureHooks + 383448","8   Exponent                            0x00000001039e77ac ABI32_0_0RCTFBQuickPerformanceLoggerConfigureHooks + 382772","9   libdispatch.dylib                   0x0000000185a15088 <redacted> + 24","10  libdispatch.dylib                   0x0000000185a15048 <redacted> + 16","11  libdispatch.dylib                   0x0000000185a531c0 <redacted> + 520","12  libdispatch.dylib                   0x0000000185a53b30 <redacted> + 340","13  libdispatch.dylib                   0x0000000185a54528 <redacted> + 380","14  libdispatch.dylib                   0x0000000185a5c5c4 <redacted> + 640","15  libsystem_pthread.dylib             0x0000000185cbafe0 _pthread_wqthread + 932","16  libsystem_pthread.dylib             0x0000000185cbac30 start_wqthread + 4"],"userInfo":null,"domain":"ABI32_0_0RCTErrorDomain"}`

### Environment

 Expo CLI 2.11.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.3.2 
    npmGlobalPackages:
      expo-cli: 2.11.1

### Reproducible Snack

https://snack.expo.io/Byy4et3LV

Thanks for your help!

**Comment by AdamJNavarro** [comment]
Hey @ewein,

Based on your Snack it looks like you may not be requesting the required `CAMERA` permission as indicated in the docs [here](https://docs.expo.io/versions/v32.0.0/sdk/imagepicker/#imagepickerlaunchcameraasyncoptions). Can you try adding that and see if it works for you then?

Cheers,
Adam

**Comment by ewein** [comment]
Did this recently change? It has been working fine with just the single CameraRoll permission check until recently.

**Comment by paaatcha** [comment]
> Did this recently change? It has been working fine with just the single CameraRoll permission check until recently.

It was. I'm having the same problem here. I have an app that uses the `ImagePicker.launchCameraAsync` and it doesn't work anymore. I think the solution is using Camera only.
