### ISSUE TITLE
Strange behavior after SDK released when change the whole app color from blue to green

### ISSUE THREAD

**Issue by AhmSaeed** [expo/expo#3665]
I use expo v31 with react navigation v3

When changing the whole app color from blue to green including tab bar, headers, assets, splash screen and icons. after build a new apk release the react navigation tab bar background color changed from white to green although I already set it's background color to white

Why might such a problem happen and if there is a way to clear the old apk build as there might be a conflict when build JavaScript bundle

**Comment by cruzach** [comment]
Hey @AhmSaeed,

Without more information, it's tough for us to help you out. My suggestion is to follow the Issue template, and make sure to provide a reproducible example.

To answer your second question- we can delete the old apk file, send us an email at secure@expo.io and include your Expo username, app ID, and Build ID.

Thanks!
Charlie
