### ISSUE TITLE
React Native Bare-Minimum Demo - Hot Swapping throws an error

### ISSUE THREAD

**Issue by AlexMachin1997** [expo/expo#3666]
### Environment

```
 Expo CLI 2.11.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

The target device for this application is Android

### Steps to Reproduce

1. Install React-Native and Expo-CLI
2) Create the expo project via expo init AwesomeProject
3) Select the bare-minimum option
2. Connect your Android smartphone via a USB-C cable, ensure USB debugging is enabled in the developer settings.
3. Issue react-native run-android or npm start
4) After the app has compiled enable: development mode, live reloading, hot swapping, delta files (Experimental feature)

### Expected Behavior
The application shouldn't show the error, instead, it should show the applications first screen.

### Actual Behavior
![screenshot_20190306_123825_com awesomeproject](https://user-images.githubusercontent.com/29917195/53901834-c5f41f00-4037-11e9-8366-d546a876cdd3.jpg)
(Write what happened. Add screenshots!)

### Reproducible Demo

Github repo: https://github.com/AlexMachin1997/React-Native-Demo

It contains the current version of the demo environment.

1. Install React-Native and Expo-CLI
2) Create the expo project via expo init AwesomeProject
3) Select the bare-minimum option
2. Connect your Android smartphone via a USB-C cable, ensure USB debugging is enabled in the developer settings.
3. Issue react-native run-android or npm start
4) After the app has compiled enable: development mode, live reloading, hot swapping, delta files (Experimental feature)

**Comment by brentvatne** [comment]
hello! this is a bug with react-native upstream -- i see you've created an issue there: https://github.com/facebook/react-native/issues/23788 - let's track it there

**Comment by brentvatne** [comment]
I can't actually repro this, it worked fine for me. you might want to disable live reloading, it doesn't make much sense to use that with hot reloading (you should use one or the other and not both at the same time)

**Comment by AlexMachin1997** [comment]
@brentvatne see my attached comment in the other repo.

Sorry for creating duplicate issues, won't happen again 👍 

I couldn't figure out if it was an Expo or React-Native.
