### ISSUE TITLE
What is difference between between expo init my-new-project and create-react-native-app

### ISSUE THREAD

**Issue by awaissadiq99** [expo/expo#3667]
Hello I'm new to reactnative i want to ask my first question, what is differnce between  between expo init my-new-project and create-react-native-app.

**Comment by AdamJNavarro** [comment]
Hey @awaissadiq99,

CRNA has been replaced by the expo-cli so I wouldn't give it much thought. You'll just want to decide if you want to use the Managed workflow or Bare workflow. You can read about these two choices [here](https://docs.expo.io/versions/v32.0.0/introduction/managed-vs-bare/).

Also, for future reference, we prefer to reserve github issues for bugs. These types of questions belong on our [forums](forums.expo.io) where we'd be happy to answer them!

Cheers,
Adam

**Comment by awaissadiq99** [comment]
Sure thankyou,, let me close the issue.
