### ISSUE TITLE
Sdk32 - RN0.57.1 : Invariant Violation : Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#3668]
### Environment

````
Expo CLI 2.11.6 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.11.6
````

### Steps to Reproduce

Using FlatList and then VirtualizedList ...

I face this issue https://github.com/facebook/react-native/issues/23790 which is related to RN 0.57.1 used in sdk32. When do you expect to update RN to later version (i.e. 0.58) that should fix this issue ?

**Comment by AdamJNavarro** [comment]
Hey @lc3t35,

We'll update to .58 with SDK33's release barring any breakages found between now and the upgrade. As for when SDK33 will drop, we don't have anything concrete to report. The Unimodules initiative and Managed/Bare workflow projects have taken a lot of time and bandwidth as of late but we're hoping to get back to cutting a release in the near term.

As this issue deals specifically with RN, I'm going to close this issue.

Cheers,
Adam

**Comment by lc3t35** [comment]
Thank you ! Let's wait sdk33 ...

**Comment by alexpchin** [comment]
Any suggestions on how to combat this prior to sdk33 launching? It seems not possible to have a FlatList inside another FlatList?

**Comment by xwartz** [comment]
I have the same issue on RN 0.59. 
And i find the TODO hasn't been fixed https://github.com/facebook/react-native/blob/0.59-stable/Libraries/Lists/VirtualizedList.js#L1137

@lc3t35
