### ISSUE TITLE
undefined is not a function(near'...(0,_reactNavigation.Tabnavigator)...)

### ISSUE THREAD

**Issue by tomo25** [expo/expo#3672]
I got an error in a part of a Udemy course.
I was adding navigation to my app but got this error 
`undefined is not a function(near'...(0,_reactNavigation.Tabnavigator)...) `

### Environment

Expo CLI 2.11.6 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.3.2 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.11.6

### Steps to Reproduce

1. `create-react-native-app Tinder`
2. `cd Tinder`
3. `npm install`
4. `npm start`

File structure

Tinder
|--.expo
|       |--packeger-info.json
|       |--settings.json
|--navigation
|       |--RootNavigator.js
|       |--TabNavigator.js
|--node_modules
|--.watchmanconfig       
|--screens
|       |--Home.js
|       |--Matches.js
|       |--Profile.js
|--App.js
|--app.json
|--babel.config.json
|--package-lock.json
|--package.json
|--yarn.lock

App.js
```
import React from 'react';
import RootNavigator from './navigation/RootNavigator.js'
import { 
  Text, 
  View 
} from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <RootNavigator/>
    );
  }
}
```

Home.js
```
import React from 'react';
import styles from '../styles'

import { 
  Text, 
  View
} from 'react-native';

class Home extends React.Component {
  state = {}

  componentWillMount() {}

  render() {
    return (
     <View>
      <Text>Home</Text>
     </View>
    )
  }
}

export default Home;
```

Matches.js
```
import React from 'react';
import styles from '../styles'

import { 
  Text, 
  View
} from 'react-native';

class Matches extends React.Component {
  state = {}

  componentWillMount() {}

  render() {
    return (
     <View>
      <Text>Matches</Text>
     </View>
    )
  }
}

export default Matches;
```
Profile.js
```
import React from 'react';
import styles from '../styles'

import { 
  Text, 
  View
} from 'react-native';

class Profile extends React.Component {
  state = {}

  componentWillMount() {}

  render() {
    return (
     <View>
      <Text>Profile</Text>
     </View>
    )
  }
}

export default Profile;
```
RootNavigator.js
```
import React from 'react';
import { StackNavigator } from 'react-navigation';
import TabNavigator from './TabNavigator.js';

const RootStackNavigator = StackNavigator(
  {
    Main: {
      screen: TabNavigator,
    },
  }
);

export default class RootNavigator extends React.Component {
  render() {
    return <RootStackNavigator/>;
  }
}
```

TabNavigator.js
```
import React from 'react';
import Home from '../screens/Home';
import Profile from '../screens/Profile';
import Matches from '../screens/Matches';
import { TabNavigator } from 'react-navigation';

export default TabNavigator(
  {
    Profile: {
      screen: Profile,
      navigationOptions: {
        tabBarLabel: 'Profile',
      },
    },
    Home: {
      screen: Home,
      navigationOptions: {
        tabBarLabel: 'Home',
      }
    },
    Matches: {
      screen: Matches,
      navigationOptions: {
        tabBarLabel: 'Matches',
      },
    },
  },
  {
    navigationOptions: {
      header: null
    },
    tabBarPosition: 'top',
    initialRouteName: 'Home',
    animationEnabled: true,
    swipeEnabled: true,
    tabBarOptions: {
      style: {
        height: 75
      },
    }
  }
);
```

### Expected Behavior

It suppose to show tabs and be able to swich screens when you touch each tab.  

### Actual Behavior

I got an error saying "undefined is not a function(near'...(0,_reactNavigation.Tabnavigator)...)"
here is a screenshot

![fullsizeoutput_312](https://user-images.githubusercontent.com/38713998/53958179-acc89c80-4123-11e9-8724-2e7826e89820.jpeg)

this is my package.json file

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-navigation": "^3.3.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

```

### Reproducible Demo
this is one part of this Udemy cource
[https://www.udemy.com/how-to-build-tinder/]()

**Comment by cruzach** [comment]
Hey @tomo25 ,

The problem looks to be in your `TabNavigator.js` file. I would go take a look at the [React Navigation docs](https://reactnavigation.org/docs/en/tab-based-navigation.html), and restructure your file after reading up on that API.

As this doesn't seem to be a problem related to Expo, I'm going to go ahead and close this issue.

Good luck with your course!

**Comment by tomo25** [comment]
hi  @cruzach ,

Thank you so much for answering! looking forward to hearing from you.
