### ISSUE TITLE
undefined is not an object (evaluating '_this2.firestore.log.error')

### ISSUE THREAD

**Issue by redpandatronicsuk** [expo/expo#3675]
https://github.com/expo/expo/blob/3ad8c1df631cedcae51cc72c7b3543408ae629b5/packages/expo-firebase-firestore/src/Query.ts#L280

For me `firestore.log` is undefined.

Expo version: 22
ExpoFirebase version: 1.0.0-rc.5

**Comment by cruzach** [comment]
Hi @redpandatronicsuk,

In order to effectively help you, we need a reproducible demo of the issue. If you just follow the template provided when you file an issue at our Github, solving this will be a lot quicker/smoother. The more details the better!

Thanks,
Charlie

**Comment by redpandatronicsuk** [comment]
Thanks @cruzach,

I agree that a demo usually helps, but I think in this case it is not needed. In the referenced line, `this.firestore` is of type `Firestore` which is defined here: https://github.com/expo/expo/blob/3ad8c1df631cedcae51cc72c7b3543408ae629b5/packages/expo-firebase-firestore/src/firestoreTypes.types.ts#L1
and there is no `log` function defined. Also _regular_ `Firestore` instances (I mean like the ones returned by `firebase.firestore()` do not have a property called `log`.

I assume `this.firestore.log` is a typo. Would it be possible to confirm with the author of that code if that is the case? If it is not a typo, I can try setting up a demo. The only problem is that the demo needs to be configured to use a Firebase project and I would have to set up a Firebase project just for that.

Cheers,
Dominik

**Comment by redpandatronicsuk** [comment]
Btw, as a temporary fix, I just commented the line out (line 280 in Query.ts) and my app doesn't crash anymore and behaves as expected.
