### ISSUE TITLE
IOS upload error: Invalid Code Signing Entitlements 

### ISSUE THREAD

**Issue by tuqire** [expo/expo#3677]
Hi,

I am getting the following error when trying to upload a new version of my IOS app.

```ERROR ITMS-90163: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. The bundle contains a key that is not included in the provisioning profile: 'com.apple.developer.icloud-services' in 'Payload/ExpoKitApp.app/ExpoKitApp'."```

build url https://expo.io/builds/c7ead65e-6e5b-47ab-b824-c319d5998285

**Comment by wkozyra95** [comment]
It seems that you changed sth in the app id(enabled icloud) and didn't recreate provisioning profile. You need to run build with `--clear-provisioning-profile` option and allow expo to generate a new one.

**Comment by tuqire** [comment]
Ah thank you for that! Giving it a go now.

Out of interest, how do I know when i need to flush the provisioning profile?

**Comment by tuqire** [comment]
It's telling me to delete my old provisioning profile on Apple Developer portal. Am I okay to do this? (sorry I am a newbie to mobile app dev)

**Comment by wkozyra95** [comment]
yes you need to revoke old one, sorry forgot about that. There is also `--revoke` option in cli that can do it for you

**Comment by wkozyra95** [comment]
You need to recreate provisioning profile if you are changing anything in app id or generating a new certificate or old one expired. In most cases, expo command will do that for you.

**Comment by tuqire** [comment]
Hi again,

So still getting the same problem.

I tried manually deleting the provisioning profile and running `expo build:ios --clear-provisioning-profile`. When this didn't work, I tried manually deleting the provisioning profile and running `expo build:ios --clear-provisioning-profile` after another version bump, but still having the same problem.

Is there an extra step somewhere I am missing?

1.2.0 (post new provisioning profile): https://expo.io/builds/b968b6ce-058a-4a40-9a66-81e52603b914
1.3.0 (post new provisioning profile): https://expo.io/builds/db49136b-bc1c-476b-9ee5-a54f761c63be

**Comment by wkozyra95** [comment]
If you want use icloud storage there should be
- icloud enabled in app id on apple developer portal
- `ios.usesIcloudStorage` set to true in app.json

If you don't use icloud
- icloud disabled in app id on apple developer portal
- `ios.usesIcloudStorage` should not be present in app.json

Based on the fact that previous fix didn't work I'm guessing that you only set usesIcloudStorage in app.json.
If that's the case enable it on https://developer.apple.com/ -> Account -> “Certifactes, ids & Profiles” -> App IDs
and recreate provisioning profile once more

**Comment by tuqire** [comment]
That worked, thanks so much. Apologies for being dense, this is my first app so I am still learning the intricacies of mobile app deployment.
