### ISSUE TITLE
Invariant Violation when drawing Marker on MapView

### ISSUE THREAD

**Issue by AlexBungiu** [expo/expo#3679]
Hi, I am trying to render a map with some markers. Map renders fine, but when i try to draw a marker it crashes. You will find below a link to a snack i've made to reproduce the issue.

### Environment

  Expo CLI 2.7.1 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: 32.0.5 => 32.0.5 
      @types/react: 16.7.18 => 16.7.18 
      @types/react-native: 0.57.23 => 0.57.23 
      @types/react-navigation: 3.0.2 => 3.0.2 
      expo: 32.0.6 => 32.0.6 
      react: 16.8.2 => 16.8.2 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.1.tar.gz => 0.57.1 
      react-navigation: 3.2.3 => 3.2.3 
    npmGlobalPackages:
      expo-cli: 2.7.1

iOs

### Steps to Reproduce

I have made a snack that can reproduce the problem I have

1. https://snack.expo.io/@alexbungiu/map-markers-not-working-final
2. click on addMarker button above map
3. crash

### Expected Behavior

a marker should be drawn at the specified location

### Actual Behavior

app crashes with invariant violation
[error screenshot](https://imgur.com/N4Efg84)

### Reproducible Demo

https://snack.expo.io/@alexbungiu/map-markers-not-working-final

**Comment by brentvatne** [comment]
this is a bug in your code, see https://snack.expo.io/@notbrent/map-markers-not-working-final
