### ISSUE TITLE
Can't use loaded fonts as per documentation

### ISSUE THREAD

**Issue by ryanvanderpol** [expo/expo#368]
Following the [Using Custom Fonts](https://docs.expo.io/versions/v18.0.0/guides/using-custom-fonts.html) guide to load a custom font and then using `fontFamily: 'my-font-name'` in a `StyleSheet` always results in the following error message:

> fontFamily 'my-font-name' is not a system font and has not been loaded through Exponent.Font.loadAsync.

However, if I use `fontFamily: Font.style('my-font-name').fontFamily` it works correctly.  I'm not sure if this means the documentation is incorrect (maybe a breaking change was introduced recently?) or if this is some sort of bug.

**Comment by brentvatne** [comment]
Hello! What sdkVersion are you using? `Font.style('my-font-name').fontFamily` used to be required a while ago but it isn't anymore.

**Comment by ryanvanderpol** [comment]
Looks like I'm using `^17.0.0`

**Comment by brentvatne** [comment]
Can you share your code? Maybe there's a typo or something.

**Comment by ryanvanderpol** [comment]
I'll share what I can (or rather what I think is relevant... it's a big project)

> ./App.js
```
export default class App extends Component {

	state = { ready: false }

	componentWillMount(){
		this._loadAssetsAsync();
	}

	async _loadAssetsAsync(){
		try {
			await Font.loadAsync({
				'montserrat': require('./assets/fonts/Montserrat-Regular.ttf')
			});
		}
		catch(e) {
			Log.error(e);
		}
		finally {
			console.log(Font.isLoaded('montserrat'));
			console.log(Font.style('montserrat'));
			this.setState({ready: true});
		}
	}

	render() {
		if(this.state.ready){
			return (
					<Provider store={store}>
						<AppWrapper />
					</Provider>
			);
		}
		return null;
	}
}
```

And then attempting to use it later:
```
const styles = StyleSheet.create({
    profileName: {
        backgroundColor: 'transparent',
        color: 'white',
        fontSize: 16,
        fontFamily: 'montserrat'
        //fontFamily: Font.style('montserrat').fontFamily
    },
});
```

In the `finally` block in `_loadAssetsAsync` the first `console.log` line spits out `true`, so I know it's loaded.  And the second line spits out `{"fontFamily":"ExponentFont-76C191A7-BB71-496A-A92A-DD36143E6C06-montserrat"}`  

Using it with just the font name results in the error from my original post. Swapping out the commented-out line works fine, though.

**Comment by brentvatne** [comment]
Here's an example of it working: https://github.com/brentvatne/expo-issue-368

**Comment by ryanvanderpol** [comment]
Ah, I figured it out.  Google search results originally returned me the documentation for 13.0.0 which had `import { Font } from 'exponent'` rather than `import { Font } from 'expo'`.  I guess at some point there was a name change.  For whatever reason, my `package.json` only has `"expo": "^17.0.0"` and no line for `exponent` so I'm not sure why it worked, but switching `exponent` to `expo` fixed the problem.

**Comment by brentvatne** [comment]
here's a branch using the code that you provided above, works as expected: https://github.com/brentvatne/expo-issue-368/tree/example-with-provided-code

**Comment by brentvatne** [comment]
It's possible that when updating the project someone didn't notice this in the release notes:

<img width="741" alt="screen shot 2017-07-13 at 1 34 27 pm" src="https://user-images.githubusercontent.com/90494/28186446-0c142a08-67d0-11e7-9fc2-09e8dd5a606c.png">

**Comment by brentvatne** [comment]
Anyhow thanks for the followup, we'll keep this kind of thing in mind in the future and try to catch it automatically for people!

**Comment by ryanvanderpol** [comment]
The project was created on v17 only about a month ago, so no upgrades have happened yet (although I see v18 is out now).  Not sure how the old package is in there, but glad it's solved now.  Thanks for pointing me in the right direction!

**Comment by ryanvanderpol** [comment]
One thing that might help is in old versions of the documentation there should be a big warning banner at the top that says something about this version being outdated.  Might cause people to look twice at the documentation version

**Comment by AlexandreRoba** [comment]
Hi All,

I'm having the same problem. Lost tow hours on this.
Here is my code. Any idea?

```javascript
import React,{Component} from 'react';
import {  Text, View } from 'react-native';

import { Font } from 'expo';


export default class App extends Component{
    state = {
        ready: false,
    };

    componentDidMount(){
        this._loadAssetsAsync();
    }

    async _loadAssetsAsync(){
        try {
            await Font.loadAsync({
                'Roboto-Regular':require('./assets/fonts/Roboto-Regular.ttf')
            });
        }
        catch(e) {
            Log.error(e);
        }
        finally{
            console.log('Roboto is loaded:' + Font.isLoaded('Roboto-Regular'));
            this.setState({ready: true});
        }
    }

    render(){
        return (

                <View style={{flex:1,marginTop:100}}>

                    this.state.ready ? (
                    <Text style={{fontFamily:'Roboto-Regular'}}>New Font in Robotto</Text>
                    ) : null
                </View>
        )
    }
}
```

And My package.json
```json
{
  "name": "test app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.13.2",
    "jest-expo": "26.0.0",
    "react-test-renderer": "16.3.0-alpha.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "apollo-cache-inmemory": "^1.1.12",
    "apollo-client": "^2.2.8",
    "apollo-link-http": "^1.5.4",
    "expo": "^26.0.0",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.1",
    "react": "16.3.0",
    "react-apollo": "^2.1.3",
    "react-native": "~0.54.1"
  }
}
```

**Comment by joelvh** [comment]
This does not seem to work for me either. Has something changed again? v27.0.2

**Comment by shic** [comment]
Double checked my code, see no error. It just not work...

```
export default class App extends React.Component {
    componentDidMount() {
        Font.loadAsync({
            'lato-regular': require('./assets/fonts/LatoRegular.ttf'),
        });
    }


    render() {
        return (
                        <Text
                            style={styles.text}
                            color={Colors.main}
                            size={20}
                        >
                            Download
                        </Text>
        );
    }
}

const styles = StyleSheet.create({

    text: {
        fontFamily: 'lato-regular',
        padding: 20,
        color: 'white'
    },
})

```

**Comment by terribleben** [comment]
To the recent commenters--

Thanks for the report. I just tried doing loading a font using our Tabs starter project on the latest version of the Expo SDK (27.0.2 at time of writing), and it worked as expected.

Most issues you encounter now are unlikely to be related to this thread from 1 year ago. If you think you've found a new issue, please open a new thread which follows our issue template, ideally with a [snack](https://snack.expo.io/) we can run to reproduce the issue.

Thanks!
