### ISSUE TITLE
[feature request] Expo client home-screen widget

### ISSUE THREAD

**Issue by warren-bank** [expo/expo#3686]
Hi. I'm new to Expo. It's a brilliant idea, and the implementation is great. One thought:

It would be __really__ nice to be able to add home-screen widgets that can each be initially configured to load the URL of a published javascript bundle. The URL could either be entered by keyboard or QR code. The URL could either use the "exp://" scheme for apps published in the Expo CDN, or "http[s]://" schemes for apps that are self-hosted (ex: in GitHub/GitLab Pages). Given this URL, the widget can determine both the name of the app and the URL of its icon from JSON data. When each pre-configured widget is clicked, Expo client would immediately open and load the corresponding app's javascript bundle.

**Comment by warren-bank** [comment]
On a closely related topic, I just noticed in [AndroidManifest.xml](https://github.com/expo/expo/blob/master/template-files/android/AndroidManifest.xml#L62) that the `LauncherActivity` has intent filters that would allow an external app to launch the URL of a javascript bundle hosted in the Expo CDN (as identified by "exp://" scheme and/or "exp.host" hostname).

It would also be nice to add a more explicit intent filter that would allow launching a self-hosted javascript bundle. For example:

```xml
      <intent-filter>
        <action android:name="host.exp.exponent.LAUNCHER_INTENT" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:scheme="http" />
        <data android:scheme="https" />
      </intent-filter>
```

```java
  import android.app.Activity;
  import android.content.Intent;
  import android.net.Uri;

  public class MainActivity extends Activity {
    ...

    public void launchAppBundle(String uri) {
      Intent i = new Intent("host.exp.exponent.LAUNCHER_INTENT", Uri.parse(uri));
      startActivity(i);
    }
  }
```

where:
* the example _uri_ used [in the docs](https://docs.expo.io/versions/latest/distribution/hosting-your-app/) is: `"https://expo.github.io/self-hosting-example"`

_PS_:
* Sorry if my code is a bit rough.. I haven't written in Java for several years.

**Comment by cruzach** [comment]
Hey @warren-bank!

Thanks for these suggestions! No worries about the rough code, but if you could add these over at our [feature requests page](https://expo.canny.io/feature-requests), that would be awesome. We just like to keep Github for issues only

Thanks again!
Charlie

**Comment by warren-bank** [comment]
OK, sorry about that. However, I'd like to share one final comment on the topic for anyone else who may be interested in this feature.

I was wrong about the purpose of the `exp://` scheme. I had previously thought that it was in some way tied to the Expo CDN; this is entirely wrong. I've come to realize that if the javascript bundle is hosted and reachable by `http://`, then changing this protocol to `exp://` in the Intent's data will:

* allow it to match an [intent filter](https://github.com/expo/expo/blob/master/template-files/android/AndroidManifest.xml#L62) for the `LauncherActivity`
* be translated back to the correct protocol within the Expo client

Likewise, the same is true of changing `https://` to `exps://`.

On an Android device that has the Expo client installed, an Intent can be used to load any arbitrary javascript bundle from its URI after performing the above protocol translation.

Both of the following tools are tested to work well:

1. run ["AnyCut"](https://f-droid.org/archive/com.example.anycut_5.apk) and configure a new home-screen widget (ie: shortcut):
   * select: "Make your own"
     * action:<br>`android.intent.action.VIEW`
     * data:<br>`exp://192.168.1.100:80/android-index.json`
     * type:<br>_[leave empty, this is for MIME type]_
     * click: "OK"
     * enter a descriptive name for the app (ex: "Expo Demo App")

2. run ["With Intent"](https://github.com/zach-klippenstein/with-intent) and launch:
   * action:<br>`android.intent.action.VIEW`
   * category:<br>`android.intent.category.BROWSABLE`
   * data URI:<br>`exp://192.168.1.100:80/android-index.json`

notes:

* both of these examples assume that the javascript bundle is self-hosted and can be loaded from a webserver on the LAN
* I did this as follows:
  ```bash
    expo export --public-url 'http://192.168.1.100:80/'
    httpd ./dist
  ```
* where `httpd` is a wrapper script I added to `PATH` that opens a webserver rooted at a specified directory
