### ISSUE TITLE
Setting Audio config to allowsRecordingIOS routes playback audio to headphones only

### ISSUE THREAD

**Issue by piffie** [expo/expo#3689]
When i set the global Audio
`Audio.setAudioModeAsync({
allowsRecordingIOS: true
...
});`
then all sounds are redirected to the Headphones on IOS.
This issue was described already in the forums (https://forums.expo.io/t/try-to-use-expo-audio-ios-play-with-receiver-but-not-speaker/699/13) but it seems has never been transferred to the issues.

As a workaround, i set it globally to false, and when i want to record stuff, i set it to true, and afterwards back. But actually that should not be the case. 
Tested on an IphoneX with IOs 12.1

*Steps to reproduce*
set on app start the audio to
`Audio.setAudioModeAsync({
allowsRecordingIOS: true
...
});`

playback a video with the <video> tag.
check that audio is not played through the speakers (no matter if headphones are there or not) but only when the headphone is connected through the headphone.

*Expected behaviour*
Sound can be played through the speakers and recorded at the same time.

**Comment by cruzach** [comment]
Hey @piffie,

Can you provide a [Snack](https://snack.expo.io/) demo of this?

Also, let me know what SDK version you're using, and if this is in standalone app or through the Expo Client.

Thanks!
Charlie

**Comment by piffie** [comment]
Hi, can try to make it into a snack demo tonight.

SDK version is 32, tested on both the standalone and on the expo client app.

Am So., 10. März 2019 um 19:21 Uhr schrieb Charlie Cruzan <
notifications@github.com>:

**Comment by HERRKIN** [comment]
Any workaround?

**Comment by yastrebovb** [comment]
SDK version 33. The problem still exists.

**Comment by riwu** [comment]
Still happening on SDK 35: https://snack.expo.io/@riwu/allowsrecordingios
When `allowsRecordingIOS` is true, audio is routed to phone receiver even when not recording.

**Comment by sjchmiela** [comment]
This is an expected behavior of the iOS system. An appropriate note is already added to the docs:

> NOTE: when this flag is set to true, playback may be routed to the phone receiver instead of to the speaker.
