### ISSUE TITLE
iOS build stucks with no possibility to interrupt

### ISSUE THREAD

**Issue by EugeneButusov** [expo/expo#369]
Hi everyone
We have situation when iOS build is in progress for along time and didn't finish during the day. Why it could happen? and is there any way to send command to stop building process? Because while it's in progress we cannot start the new building again.
Thanks in advance for your help!

**Comment by terribleben** [comment]
Hi, the `exp build` output should give you a build id, can you paste that here?

**Comment by terribleben** [comment]
Actually, let's take this to the corresponding [forum thread](https://forums.expo.io/t/ios-build-stucks-with-no-possibility-to-interrupt/1609) you opened.
