### ISSUE TITLE
[Android] Unable to install program

### ISSUE THREAD

**Issue by dajohnny** [expo/expo#3692]
Hi, All!

Today, I found the "Redmi Note 6 Pro" model. After uninstalling the program, installing again will give an error "The program is not installed."

Note:
Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
I chose that Let Expo handle the process!

**Comment by brentvatne** [comment]
hello! can you describe more in detail what is going on? step by step as if i'm a child who has no idea what is happening

**Comment by AdamJNavarro** [comment]
I'm going to close this. If you are able to provide more information, I'll be happy to re-open so we can continue discussions.

Cheers,
Adam
