### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by halallahh** [expo/expo#37]
Any plan to make TypeScript support for exponent like exponent has done with ClojureScript?

**Comment by joshyhargreaves** [comment]
+1

**Comment by pierre-H** [comment]
+1

**Comment by pierre-H** [comment]
I just created TypeScript definitions here : https://gist.github.com/pierre-H/eef9a9225fb1c5a0f81180a8b0fbb2c2

All the v16.0.0 SDK API is there I think except the MapView which is very big and I don't have the time to do it.
There is also `@expo/vector-icons`.

Need testing.
Few things should be also checked (look at TODOs).

For anyone who wants to use it, just save this file in your project root directory.

**Comment by pierre-H** [comment]
@ccheever I don't know exactly, if I want to do a PR, where to place the file.
When I add expo to a project with npm or yarn, `index.d.ts` has to be on `node_modules\expo` folder. So, where should I save it in the repository ?

**Comment by halallahh** [comment]
@pierre-H the typings looks good. Thanks!. maybe you can push to DefinitelyTyped?

**Comment by RnMss** [comment]
I tried [react-native-typescript-transformer](https://www.npmjs.com/package/react-native-typescript-transformer) and it works perfectly for vanilla react-native(>=0.45). 

Now I switched to expo-18.0.0, which is supposed to use react-native@0.45.1, but react-native-typescript-transformer doesn't work.

It requires me to add an `rn-cli.config.js` file to the package root, and the expo version of react-native packager doesn't seem to read it at all. If this can be fixed, supporting TS should be easy.

**Comment by RnMss** [comment]
Now I figured it out.

- upgrade to expo>=18.0.0
- install react-native-typescript-transformer:
--`npm i --save react-native-typescript-transformer`
- merge the following settings into `exp.json`:
```json
{
  "packagerOpts": {
    "sourceExts": ["ts", "tsx"],
    "transformer": "node_modules/react-native-typescript-transformer"
  }
}
```
- reload the project

**Comment by filipmares** [comment]
This is great progress! I think Typescript can add a lot of value to the already awesome dev experience for expo.

**Comment by dalcib** [comment]
A example of create-react-native-app with Typescript, using react-native-typescript-transformer and jest-expo-ts: [https://gitHub.com/dalcib/expo-ts-exemple](https://gitHub.com/dalcib/expo-ts-exemple)

**Comment by mozinator** [comment]
@dalcib do you got hot reloading working with typescript ?

**Comment by brunolm** [comment]
@pierre-H maybe you could place on `/typings` and add the file on the type list in `package.json`

```
"types": "typings/index.d.ts",
```

So when you install the package TypeScript (2+) will automatically know where to look for the type.

**Comment by retrixe** [comment]
@mozinator you can use watch mode.

**Comment by janaagaard75** [comment]
I updated @pierre-H type definitions with the following changes:

* Changed the module name from `Expo` to `expo`.
* Updated the definitions for React Native SVG.

There is still some work to do before a pull request for Definitely Typed can be made, so until now you have to put `index.d.ts` among your source files.

https://github.com/janaagaard75/expo-type-definitions/blob/master/index.d.ts

**Comment by PavelPZ** [comment]
I updated @janaagaard75  type definitions with the following changes:
- removed ```void```'s from ```React.Component```
- added ```style``` prop to ```IconProps```

https://github.com/PavelPZ/rw4/blob/master/typings/expo.d.ts

**Comment by janaagaard75** [comment]
@PavelPZ: Nice work.

I just realize, that I had forgotten to update the link in my comment above. That has been fixed now.

**Comment by PavelPZ** [comment]
Thanks, my version modified, including:
- some minor change to Asset definition

**Comment by janaagaard75** [comment]
Thanks for the info, @PavelPZ. I've update the type definitions for the vector icons in https://github.com/janaagaard75/expo-and-typescript. Will integrate your changes to Asset another day.

**Comment by Jonatthu** [comment]
@janaagaard75 Is there anyway to enable hot reload yet?

**Comment by Bundas** [comment]
@pierre-H Any update on the MapView types? I still can not find it in @types/expo

**Comment by janaagaard75** [comment]
@Bundas: I have create types for MapView in this repo <https://github.com/janaagaard75/expo-and-typescript>, so you could extract them from there, and create a pull request to `@types/expo`.

**Comment by janaagaard75** [comment]
Automatic reloading works. Subsequent reloads are significantly faster than the first, so there is at least some kind of caching that works.

Don't know if the React Native support hot module replacement as well as web development does. It could very well be that developing in TypeScript is already on par with using regular JavaScript for React Native.

**Comment by moshfeu** [comment]
@RnMss It seems that it should be in _app.json_ this days, right? https://forums.expo.io/t/exp-json-wasnt-there/394

**Comment by janaagaard75** [comment]
@moshfeu: Yep. The Expo team changed it from `exp.json` to `app.json` at some point.

**Comment by sjchmiela** [comment]
Expo SDK 31 now uses TypeScript. Hooray! 🎉

**Comment by janaagaard75** [comment]
@awwong1: I've written a small demo app showing how to write an Expo app in TypeScript. It might be able to help you get started. <https://github.com/janaagaard75/expo-and-typescript>

**Comment by rauldeheer** [comment]
@awwong1 I created a empty boilerplate project for people that want to use Typescript with the new Expo SDK [31.0.0]!

Here it is:
https://github.com/rauldeheer/expo-typescript

I hope people will find it usefull! 

Cheers!

**Comment by artyorsh** [comment]
@rauldeheer 
Good job. It would be great if your repo will contain ui or unit testing integrations ;)

**Comment by rauldeheer** [comment]
@artyorsh feel free to create an issue on this matter and I’ll take a look at it, or feel free to send over a PR!

**Comment by alamothe** [comment]
Thanks for the Expo+TypeScript starters! 

Still, it would be great if Expo offered official TypeScript starter i.e. `expo init` to offer options for empty TypeScript project.
