### ISSUE TITLE
expo-image-picker fails with class cast exception when aspect option is passed

### ISSUE THREAD

**Issue by joelgetaction** [expo/expo#3702]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

  Expo CLI 2.11.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.6 => 0.58.6
      react-navigation: ^3.3.2 => 3.3.2

This is a bare Expo app created with `expo init --template bare-minimum` and which has the `expo-image-picker` module added as per https://github.com/expo/expo/tree/master/packages/expo-image-picker

I am running on a Samsung Galaxy S5 (SM-G930F) running Android 8.0.0 Oreo, API Level 26.

### Steps to Reproduce

(Write your steps here:)

Here's the code that launches the image picker:
```
import * as ImagePicker from "expo-image-picker";
import PropTypes from "prop-types";
import { Component } from "react";

// create a component
class PickImage extends Component {
  componentDidMount() {
    const { onSuccess, onError, onCancel, quality } = this.props;

    ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      aspect: [1, 1],
      quality: quality,
      base64: true,
    })
      .then(res => {
        if (!res.cancelled) {
          const file = `data:image/jpeg;base64,${res.base64}`;
          onSuccess(file);
        } else {
          onCancel();
        }
      })
      .catch(error => onError(error));
  }

  render() {
    return null;
  }
}


PickImage.propTypes = {
  onSuccess: PropTypes.func.isRequired,
  onError: PropTypes.func.isRequired,
  onCancel: PropTypes.func.isRequired,
  quality: function(props, propName, componentName) {
    const quality = props[propName];
    if (typeof quality !== "number" || quality <= 0 || quality > 1) {
      return new Error(
        `Invalid prop ${propName} supplied to ${componentName} must be a number in (0, 1].  Validation failed.`,
      );
    }
  },
};

PickImage.defaultProps = {
  quality: 0.5,
};

export default PickImage;
```

1. Tap a button to launch the image picker using the `PickImage` component above.
2. Pick an image in the Expo image picker that gets launched.
3. See the following error in the Android Studio logs:

```
/System.err: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
W/System.err:     at expo.modules.imagepicker.ImagePickerModule$2.run(ImagePickerModule.java:323)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

The line of code in question is:
```
if (forceAspect != null) {
                cropImage
                    // The next line is the bad line:
                    .setAspectRatio((Integer) forceAspect.get(0), (Integer) forceAspect.get(1))
                    .setFixAspectRatio(true)
                    .setInitialCropWindowPaddingRatio(0);
              }
```
### Expected Behavior

(Write what you thought would happen.)

ImagePicker should NOT fail with a class cast exception when aspect is set.

### Actual Behavior

(Write what happened. Add screenshots!)

Image picker DOES fail (on Android) when aspect is set.

NOTE: this did NOT happen in Expo 32 using the same PickImage component above.  It only started happening when I converted the code to run as a bare Expo app and added expo-image-picker as a module.

### Reproducible Demo

I cannot create a snack as this is bare expo code.  However, the bug is clearly in expo-image-picker and only happens in expo bare projects so you should be able to repro it pretty easily.

If you need more supporting data or any help, please let me know!

Thanks!  :-)

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by brentvatne** [comment]
looks like something changed re: android props in react-native 0.58

**Comment by joelgetaction** [comment]
Thanks for the quick response @brentvatne !  :-)

You mean React is passing the value as a double now instead of as an int?

Could the code be changed to
```
.setAspectRatio((Integer) forceAspect.get(0).intValue(), (Integer) forceAspect.get(1).intValue())
```
And that would cast to a primitive int and then autobox back to an Integer (sorry, I think that's right, I haven't written any Java in a long time ...).

**Comment by joelgetaction** [comment]
OK, I tried to fix the cast as follows:
```
.setAspectRatio(((Number) forceAspect.get(0)).intValue(), ((Number) forceAspect.get(1)).intValue())
```
but that leads to other issues:
```
W/System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.bidvidclientmobile/com.theartofdev.edmodo.cropper.CropImageActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1950)
W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1622)
        at android.app.Activity.startActivityForResult(Activity.java:4564)
        at android.app.Activity.startActivityForResult(Activity.java:4522)
        at com.theartofdev.edmodo.cropper.CropImage$ActivityBuilder.start(CropImage.java:486)
W/System.err:     at expo.modules.imagepicker.ImagePickerModule$2.run(ImagePickerModule.java:332)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
I don't see anything in the `expo-image-picker` README asking us to add this `CropActivity` to the manifest.

**Comment by brentvatne** [comment]
good catch, you should add that your AndroidManifest.xml. I'll add this to the README

**Comment by joelgetaction** [comment]
Thanks @brentvatne !  Yeah, if changed my `AndroidManifest.xml` to be:
```
<application ...>
...
<activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
            android:theme="@style/Base.Theme.AppCompat"/>
</application>
```
Then it works!

Do you want me to create a PR for both the cast fix and the README fix - would that help since I want to contribute where I can.

**Comment by brentvatne** [comment]
a PR for the cast fix would be great, I updated the README already here: https://github.com/expo/expo/commit/3ee3b7b7d6d09ad3bc94a81e89713403e596958f

**Comment by joelgetaction** [comment]
OK, I'll create a PR.

**Comment by joelgetaction** [comment]
Hey @brentvatne - how do you prefer I do the PR?  I'm a bit confused because there's the entire expo repo but then there's the individual expo-image-picker npm module and I don't know the best way to contribute.  Do I fork expo/expo and then PR that or can I pull the source for the expo-image-picker or can I push a new branch directly to expo/expo?

Thanks!

**Comment by brentvatne** [comment]
you can clone the entire expo/expo repo, make the change to `packages/expo-image-picker` and then open a PR here :)

**Comment by joelgetaction** [comment]
@brentvatne see PR at https://github.com/expo/expo/pull/3705
