### ISSUE TITLE
expo-image-picker fails with exception when launching camera async

### ISSUE THREAD

**Issue by joelgetaction** [expo/expo#3706]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

Expo CLI 2.11.7 environment info:
System:
OS: macOS 10.14.3
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
Yarn: 1.13.0 - /usr/local/bin/yarn
npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.3 AI-182.5107.16.33.5314842
Xcode: 10.1/10B61 - /usr/bin/xcodebuild
npmPackages:
react: 16.6.3 => 16.6.3
react-native: 0.58.6 => 0.58.6
react-navigation: ^3.3.2 => 3.3.2

This is a bare Expo app created with expo init --template bare-minimum and which has the expo-image-picker module added as per https://github.com/expo/expo/tree/master/packages/expo-image-picker

I am running on a Samsung Galaxy S5 (SM-G930F) running Android 8.0.0 Oreo, API Level 26.

### Steps to Reproduce

Here's the code that launches the ImagePicker:
```
import * as ImagePicker from "expo-image-picker";
import PropTypes from "prop-types";
import { Component } from "react";

class TakePhoto extends Component {
  // Permissions.CAMERA and Permissions.CAMERA_ROLL have already been secured at this point
  componentDidMount() {
    const { onSuccess, onError, onCancel, quality } = this.props;

    ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [1, 1],
      quality: quality,
      base64: true,
    })
      .then(res => {
        if (!res.cancelled) {
          const file = `data:image/jpeg;base64,${res.base64}`;
          onSuccess(file);
        } else {
          onCancel();
        }
      })
      .catch(error => onError(error));
  }

  render() {
    return null;
  }
}

TakePhoto.propTypes = {
  onSuccess: PropTypes.func.isRequired,
  onError: PropTypes.func.isRequired,
  onCancel: PropTypes.func.isRequired,
  quality: function(props, propName, componentName) {
    const quality = props[propName];
    if (typeof quality !== "number" || quality <= 0 || quality > 1) {
      return new Error(
        `Invalid prop ${propName} supplied to ${componentName} must be a number in (0, 1].  Validation failed.`,
      );
    }
  },
};

TakePhoto.defaultProps = {
  quality: 0.5,
};

export default TakePhoto;
```

(Write your steps here:)

1. Tap the button that mounts the TakePhoto Component.
2. TakePhoto launches the camera async.
3. The app instantly crashes with the exception given below.

### Expected Behavior

expo-image-picker should NOT crash when we use it to take a picture with the device camera.

### Actual Behavior

App crashes with the following exception:
```
03-11 23:27:52.537  2257  2257 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.bidvidclientmobile/com.bidvidclientmobile.MainActivity}: android.os.FileUriExposedException: file:///data/user/0/com.bidvidclientmobile/cache/ImagePicker/458e779d-3481-4e7d-8e85-caca047b2d41.jpg exposed beyond app through ClipData.Item.getUri()
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: Caused by: android.os.FileUriExposedException: file:///data/user/0/com.bidvidclientmobile/cache/ImagePicker/458e779d-3481-4e7d-8e85-caca047b2d41.jpg exposed beyond app through ClipData.Item.getUri()
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2356)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:944)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10480)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10465)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4564)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4522)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.startActivityOnResult(ImagePickerModule.java:755)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.launchCameraWithPermissionsGranted(ImagePickerModule.java:201)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.access$000(ImagePickerModule.java:60)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule$1.onPermissionsResult(ImagePickerModule.java:156)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.permissions.PermissionsService$1.onPermissionResult(PermissionsService.java:56)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.adapters.react.services.UIManagerModuleWrapper$5.onRequestPermissionsResult(UIManagerModuleWrapper.java:217)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate$1.invoke(ReactActivityDelegate.java:201)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:111)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onResume(ReactActivity.java:64)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7352)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	... 8 more
```
### Reproducible Demo

I can't create a snack because this is an expo bare app.

**Comment by joelgetaction** [comment]
This same code to launch the camera worked fine in Expo 32 but now crashes in `expo-image-picker`.

I tried to follow the suggestions at https://medium.com/@ali.muzaffar/what-is-android-os-fileuriexposedexception-and-what-you-can-do-about-it-70b9eb17c6d0 but they didn't fix the problem.

Any ideas?  I need to be able to use the camera in my app so this is an impactful regression ...

I'm happy to test on my Android device if somebody on the Expo team can provide a patch.

**Comment by joelgetaction** [comment]
Here are the lines showing that this crash is clearly happening within expo-image-picker:
```
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.startActivityOnResult(ImagePickerModule.java:755)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.launchCameraWithPermissionsGranted(ImagePickerModule.java:201)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule.access$000(ImagePickerModule.java:60)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.imagepicker.ImagePickerModule$1.onPermissionsResult(ImagePickerModule.java:156)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.modules.permissions.PermissionsService$1.onPermissionResult(PermissionsService.java:56)
03-11 23:27:52.537  2257  2257 E AndroidRuntime: 	at expo.adapters.react.services.UIManagerModuleWrapper$5.onRequestPermissionsResult(UIManagerModuleWrapper.java:217)
```

**Comment by bbarthec** [comment]
Possible duplicate: https://github.com/expo/expo/issues/3702
See this comment: https://github.com/expo/expo/issues/3702#issuecomment-471793478

**Comment by shubhamdeol** [comment]
@bbarthec  I have followed #3702  , Image pick from gallery works fine, but on open camera app crashes.

**Comment by joelgetaction** [comment]
Hi @bbarthec , this issue is NOT a duplicate of #3702 .  #3702 was about using the image picker to select an existing image from the gallery (and getting a class cast exception) whereas this issue is about using the camera to take a new photo (and getting some kind of file system privacy/sharing exception).  Yes both issues occur in the same file `ImagePickerModule.java` but they are different bugs caused by different things and occur in different usages on different lines and different methods within the file.  #3702 was about `launchImageLibraryAsync` whereas this issue is about `launchCameraAsync`.

I was the one that submitted the PR to fix #3702 (thanks for approving that by the way :-) ) but that PR does NOT fix this issue (since this issue still occurs even using the code that includes the fix in that PR).  This issue is caused by a totally different section of code.

I'm not sure how to fix this issue here - I tried some fixes on the internet but they didn't help.  Maybe it's because when expo-image-picker was separated from the classic expo app the API level was boosted to 24 or higher?

So this issue is not a duplicate and please don't close it as one.  Sorry for being so verbose here, I just wanted to make sure the difference between the two issues was clear.  :-)

I'm happy to help in any way and I have an Android device I can test any fixes on if that helps.

Any idea how to fix this @bbarthec or @brentvatne ?  Thanks!

**Comment by joelgetaction** [comment]
Hi @cruzach @bbarthec @brentvatne @Szymon20000 @sjchmiela  - I realize you are busy so I wanted to help out by creating a test project that repros this crash reliably.  That test project is here:

https://github.com/joelgetaction/ExpoImagePickerCameraCrash

You can just download that and run it on an Android emulator (e.g. Nexus 5 API 26) and it will crash every single time in the emulator.  You do NOT need an actual Android device to test this.

If somebody has time, could they take a look at this and figure out a fix?  :-) I've tried but my Android skills are not strong enough for this.

I'm happy to help however I can, just let me know.

Thanks!

**Comment by lgraubner** [comment]
I think this is a problem with the dependency [Android-Image-Cropper](https://github.com/ArthurHub/Android-Image-Cropper). Since `compileTarget` > 24 The used method for loading files (`URI.fromFile`) is no longer allowed and causes Apps to crash with the error mentioned in this issue.

Possible related issue: ArthurHub/Android-Image-Cropper/issues/659

**Comment by joelgetaction** [comment]
Thanks @lgraubner .  So the bug is in Android-Image-Cropper even though the last stack trace line is `expo.modules.imagepicker.ImagePickerModule.startActivityOnResult(ImagePickerModule.java:755)`?  Is there any way we can accelerate the fix of the Android-Image-Cropper or replace it with a different component?  The reason I ask is that I have a presentation to investors for my startup in a few weeks and I need to show camera functionality on Android and right now that crashes ... Which is making me nervous.  :-(  My Android skills aren't strong enough to fix this myself but I would be willing to help in any other way including testing, code review, etc.  Or if it helps, I can offer to pay a cash $ bug bounty via a Patreon or something similar?  I understand people are busy so I just want to help in whatever way I can.  :-)

**Comment by joelgetaction** [comment]
Actually, @lgraubner are you sure that this is an issue with Android-Image-Cropper?  It seems like `expo-image-picker` is not creating and passing the right scheme of uri to Android-Image-Cropper: expo-image-picker is passing a `file://` uri when a comment mentions that it should be passing a `content://` uri.

For example, at the line [ImagePickerModule.jave lines 199-200](https://github.com/expo/expo/blob/master/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java#L199):
```
// camera intent needs a content URI but we need a file one
cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT, ExpFileUtils.contentUriFromFile(imageFile, getApplication(null)));
```
yet if you log out the uri generated by `ExpFileUtils.contentUriFromFile` it is clearly a `file://` uri and not a `content://` uri:
```
android.util.Log.e("joel_log", "image uri is " + ExpFileUtils.contentUriFromFile(imageFile, getApplication(null)));

/* This logs:
*   E/joel_log: image uri is file:///data/user/0/com.bidvidclientmobile/cache/ImagePicker/bf44b646-671f-466b-843c-d763bc75c001.jpg
*/
```
So it seems like the wrong scheme of uri is being passed to Android-Image-Cropper?

**Comment by lgraubner** [comment]
You might be right. I'm not an Android expert either. Feel free to ignore my comment, it was just a wild guess.

**Comment by bbarthec** [comment]
I've provided PR with fix for that, but if you need changes immediately you can go apply it manually 😉

**Comment by joelgetaction** [comment]
@bbarthec thank you!!! :-)  I tested your fix on a Samsung Galaxy S5 Android 8.0.0 API 26 and it works and doesn't crash.  I can take photos using the camera without issue now.

I really appreciate you helping with this - I know you're busy and it means a lot to me that you'd fix this so quickly.  Thanks again and take care!

**Comment by lgraubner** [comment]
Doesn't seem to work for me. Here is what I did:
- Added both files to `node_modules/expo-image-picker` folder (according to paths in PR)
- reimported gradle project
- cleaned cache

The error remains the same. Did I miss something?

**Comment by joelgetaction** [comment]
Then did you do a clean and build in Android Studio then run from there?
  

  
  

  
  
>

**Comment by lgraubner** [comment]
Yes I did. Still not working.

**Comment by joelgetaction** [comment]
That’s unfortunate. What version of Android are you on and which device? Also which dev env?    I’m on a Samsung Galaxy S5 Android  

 8.0.0 API level 26 developing on a Mac.
  

  
  

  
  
>

**Comment by lgraubner** [comment]
Tried with Android 8 SDK 26 and Android 9 SDK 28 on various emulated devices + Samsung S3 Hardware device. No difference. :(

**Comment by martinezguillaume** [comment]
Weird, I changed files manually like @lgraubner and it doesn't work but I didn't link `rn-fetch-blob`. Pretty sure that this is a clean problem, but I cleaned my project with android studio and run it from there, and it doesn't change...

**Comment by bbarthec** [comment]
One of the reason `rn-fetch-blob` might be colliding with `expo-image-picker` are these lines in `rn-fetch-blob` configuration for Android: https://github.com/joltup/rn-fetch-blob/blob/master/android/src/main/AndroidManifest.xml#L26-34. That `FileProvider` configuration is the most basic one, but unfortunately cannot be duplicated across different sub-project (aka `packages`) (see https://developer.android.com/guide/topics/manifest/provider-element.html).
`expo-image-picker` had the same `FileProvider` configuration and that might be causing the problem.
Now `expo-image-picker`'s configuration has been fixed as can be seen here: https://github.com/expo/expo/blob/master/packages/expo-image-picker/android/src/main/AndroidManifest.xml

**Comment by shubhamdeol** [comment]
@bbarthec  check issue with expo-image-picker which I recently created,
https://github.com/expo/expo/issues/4073

**Comment by EOdOW** [comment]
@bbarthec before upgrade to 32 I was using ImagePicker from 'expo', now I am getting the error mentioned in this issue. Should I switch to 'expo-image-picker' now? I have an ejected app.

**Comment by bbarthec** [comment]
@EOdOW, that would be beneficial in a long run, but `Expo` in SDK32 is already using `expo-image-picker` under the hood. The reason for this issue is wrongly configured android module. Please see my previous comments and attached PR (changes that are introduces in it will be available with next SDK release, so you need to apply them manually at this point).

**Comment by EOdOW** [comment]
@bbarthec I looked at the PR and when I tried to change the files mentioned in the PR I did not find `expo-image-picker` as a separate package. Thats what confused me. 

> under the hood
Means that there will be a package in my node_modules called `expo-image-picker` or should I look for it somewhere else? Switching to use `expo-image-picker` explicitly  seems like the best solution for now.
Thanks you.

**Comment by AlbertVilaCalvo** [comment]
@bbarthec are you sure that your pull request #3743 fixes the issue? I've copied the changes into my bare app and I still get the `FileUriExposedException`.

In order to fix it I've had to replace `ExpFileUtils.uriFromFile` with `ExpFileUtils.contentUriFromFile` in `launchCameraWithPermissionsGranted`:

```diff
-mCameraCaptureURI = ExpFileUtils.uriFromFile(imageFile);
+mCameraCaptureURI = ExpFileUtils.contentUriFromFile(imageFile, getApplication(null));
```

The change goes into this line: https://github.com/expo/expo/blob/master/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java#L301

In addition, in `ExpFileUtils.contentUriFromFile` I've had to change the name of the provider to match the one you put in the [`AndroidManifest.xml`](https://github.com/expo/expo/blob/9fa9738eaa273ac40286a595fae86147c1742df3/packages/expo-image-picker/android/src/main/AndroidManifest.xml#L8) in #3743:

```diff
-return FileProvider.getUriForFile(application,application.getPackageName() + ".provider", file);
+return FileProvider.getUriForFile(application,application.getPackageName() + ".ImagePickerFileProvider", file);
```

The names need to match - see https://stackoverflow.com/a/30896464/4034572.

The change goes into this line: https://github.com/expo/expo/blob/master/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java#L807

With this 2 changes it does work.

If you want I can open a pull request (would be my first open source contribution :) Just let me know.

**Comment by retyui** [comment]
@AlbertVilaCalvo 

I applied your fix in my module https://gist.github.com/retyui/e8cefc8b11e727b1b6d3639b1b2fbf22
And now a camera screen opens without problems.

But when creating a picture I get an error:
```js
Error: Could not copy image from content://com.synergeto.ImagePickerFileProvider/cached_expo_files/ImagePicker/e6397cd7-4332-4e6f-bab6-46d6bd6ae120.jpg: /cached_expo_files/ImagePicker/e6397cd7-4332-4e6f-bab6-46d6bd6ae120.jpg (No such file or directory)
    at createErrorFromErrorData (TouchablePreview.js:2)
    at ComponentEventsObserver.js:72
    at MessageQueue.__invokeCallback (blob:file:///0183c481-50f4-4e47-ac22-b0e4325505dd:28264)
    at ComponentWrapper.js:7
    at MessageQueue.__guard (OptionsProcessor.js:29)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (ComponentWrapper.js:6)
    at e (RNDebuggerWorker.js:1)
```

**Comment by bbarthec** [comment]
@AlbertVilaCalvo thank you very much for your effort and investigating the problem further.

It seems that your suggestion is almost perfectly fine.

This change from your response is fixing the remaining problem that I overlooked somehow proposing my previous PR:

> To fix it, in `ExpFileUtils.contentUriFromFile` I've had to change the name of the provider authority to match the one you put in the [`AndroidManifest.xml`](https://github.com/expo/expo/blob/9fa9738eaa273ac40286a595fae86147c1742df3/packages/expo-image-picker/android/src/main/AndroidManifest.xml#L8) in #3743:
> 
> ```diff
> -return FileProvider.getUriForFile(application,application.getPackageName() + ".provider", file);
> +return FileProvider.getUriForFile(application,application.getPackageName() + ".ImagePickerFileProvider", file);
> ```

However this one:

> In order to fix it I've had to replace `ExpFileUtils.uriFromFile` with `ExpFileUtils.contentUriFromFile` in `launchCameraWithPermissionsGranted`:
> 
> ```diff
> -mCameraCaptureURI = ExpFileUtils.uriFromFile(imageFile);
> +mCameraCaptureURI = ExpFileUtils.contentUriFromFile(imageFile, getApplication(null));
> ```

is causing the problem that @retyui is reporting in his comment.

I've already provided PR containing this tiny fix.

@AlbertVilaCalvo thank you again for your effort and please feel free to open any PR in the future anytime you find something is not working properly! 😉

**Comment by AlbertVilaCalvo** [comment]
@bbarthec you are right, the change `ExpFileUtils.uriFromFile` to `ExpFileUtils.contentUriFromFile` is _not_ needed - it works fine without it :) 

I didn't get any error with the change though. FYI @retyui my code is:
```
ImagePicker.launchCameraAsync({
    allowsEditing: true,
    aspect: [4,3],
});
```

@bbarthec is it possible to get an update of [expo-image-picker](https://www.npmjs.com/package/expo-image-picker) with the fix? Or we have to wait for a new Expo SDK release? I'm writing a bare app with `react-native-unimodules`.

**Comment by bbarthec** [comment]
@AlbertVilaCalvo I wish I could, but there's a lot that changed in the `react-native-unimodules` that is already affecting this module codebase on `master` and in other core things. Releasing this module right now and updating it in your project would require a lot of adjustments that aren't documented anywhere yet, so please wait until next release 😅 Sorry for that inconvenience 😞

**Comment by cjpete** [comment]
@bbarthec What would the upgrade path look like in order to fix this in a bare app (with unimodules)?

Is it a case of waiting for a new version of expo-image-picker (currently 4.0.0), and react-native-unimodules (currently 0.2.0)? Upgrading to react-native-unimodules v0.3.1 doesn't seem to have fixed it, at least.

**Comment by cjpete** [comment]
I've tried copying all of the suggested changes into the expo-image-picker node_module android directory, but still getting the same crash error:

```
05-22 10:55:47.851 12063 12063 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {[PACKAGENAME].MainActivity}: android.os.FileUriExposedException: file:///data/user/0/[PACKAGENAME]/cache/ImagePicker/80a716fe-bba6-47e0-92d3-11223bf39eec.jpg exposed beyond app through ClipData.Item.getUri()
```

**Comment by bbarthec** [comment]
@cjpete, upcoming `expo-image-picker@5.x.x` would include this fixes and it will be published alongside upcoming SDK33 (in next few days I believe).
To have this fixed earlier please ensure that changes from both PRs #3743 and #4218 are applied.
