### ISSUE TITLE
[expo-template-tabs] style correction

### ISSUE THREAD

**Issue by warren-bank** [expo/expo#3708]
after [expo-template-tabs](https://github.com/expo/new-project-template) is [moved to this repo](https://github.com/expo/expo/issues/3694)..

the [`View.tabBarInfoContainer`](https://github.com/expo/new-project-template/blob/master/screens/HomeScreen.js#L56) is [absolutely positioned](https://github.com/expo/new-project-template/blob/master/screens/HomeScreen.js#L149)..

when I run this template in Expo client, this overlays the `View` on top of the [`ScrollView`](https://github.com/expo/new-project-template/blob/master/screens/HomeScreen.js#L54).. hiding its bottom elements.

__current style:__

```javascript
  tabBarInfoContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    ...
```

__modified style that uses flexbox to position this element properly:__

```javascript
  tabBarInfoContainer: {
    flex: 0,
    alignSelf: 'stretch',
    ...
```

**Comment by cruzach** [comment]
Hey @warren-bank,

I just ran this template and didn't experience the same issue. What version of the expo-cli are you using?

Thanks!
Charlie

**Comment by warren-bank** [comment]
https://expo.io/@warren-bank/expo-template-tabs-SDK32

#### what:

* started with the stock [tabs template v0.0.3](https://www.npmjs.com/package/expo-template-tabs)
* edited [`screens/HomeScreen.js`](https://github.com/expo/new-project-template/blob/master/screens/HomeScreen.js#L36)
  ```javascript
    const __DEV__ = true

    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
    {this._maybeRenderDevelopmentModeWarning()}
  ```

#### why:

* [open the project in your web browser](https://expo.io/appetize-simulator?url=https://expo.io/@warren-bank/expo-template-tabs-SDK32)
* scroll to the bottom of the `ScrollView`
* what do you see?
  * is the content at the very bottom hidden behind the absolutely positioned `View`
* this is identical to what I observed on a small screen Android device using the unmodified tabs template

**Comment by cruzach** [comment]
Thanks for the repro! Okay, I see the issue now, and your proposed solution works for on my iOS device as well.

Original repo is now read-only, so as soon as it is moved, I can make the PR

**Comment by cruzach** [comment]
I don't believe this is an issue anymore, or at least I'm not able to reproduce it 😕 

If it is @warren-bank then let me know how to repro (or just open a PR 👍 )
