### ISSUE TITLE
How do I use @expo/vector-icons with bare react native project

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#3709]
How to use  @expo/vector-icons with bare react native project created with expo init.

If I choose to use react-native-vector-icons, Lot of imports needed to change to convert an expo project to bare rn project.

edit: Closing the issue as import changes doesn't look much time :)

**Comment by kmhari** [comment]
@shubhamdeol can you share the import changes here?

**Comment by shubhamdeol** [comment]
@kmhari 
I installed react-native-vector-icons, you can follow instructions on their repo or npm package
You can import like 
```javascript
import AntDesign from 'react-native-vector-icons/AntDesign';

// and use it like 
<AntDesign name="pluscircle" size={50} color={Colors.SECONDARY_COMMON} />
```
You can also use it like this:

```javascript
import Icon from 'react-native-vector-icons/AntDesign';

// and use it like 
<Icon name="pluscircle" size={50} color={Colors.SECONDARY_COMMON} />
```
