### ISSUE TITLE
Problem with Node update

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#371]
Hi,

After updating my version of Node I get this error message when I open a project in the Expo XDE:

```sh
`npm` command not found. If you have npm installed please run `npm install -g exp && exp path`.
```

Does the Expo XDE rely on the `exp` npm package? So, if I update Node do I need to re-install the `exp` package? Maybe this could be mentioned in docs. Thanks!

**Comment by dikaiosune** [comment]
cc @fson

**Comment by humancatfood** [comment]
I was getting the same message(s):

```
Warning: Could not determine npm version. Make sure your version is >= 3.0.0 - we recommend 4.6.1.
```
and 
```
`npm` command not found. If you have npm installed please run `npm install -g exp && exp path`.
```

I've re-installed `exp` and ran `exp path` and then reloaded Expo and that seems to have solved it.
