### ISSUE TITLE
[expo-payments-stripe] Create Custom Source

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#3710]
Is there anyway to create a custom source with expo-payment-stripe? Stripe SDK exposes this method to create custom sources: https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/model/SourceParams.java#L238-L240
(and similarly another one for iOS).

We're trying to utilize this so we can create a source for wechat.

How do we tap into this?

**Comment by cruzach** [comment]
Hey @lightninglu10,

We like to keep GIthub issues just for reproducible bugs/issues, but this looks like a great question to post on [our forums](https://forums.expo.io/)!

Off the top of my head, I would take a look at the [Creating a Source](https://docs.expo.io/versions/latest/sdk/payments/#creating-source-android-ios) section of our docs for the Expo Payments API.

Thanks,
Charlie
