### ISSUE TITLE
Error: Failed to resize image: AppIcon20x20@3x.png. (Error: Input file contains unsupported image format)

### ISSUE THREAD

**Issue by arikanmstf** [expo/expo#3711]
### Environment

Environment:
  OS: macOS 10.14.3
  Node: 8.3.0
  Yarn: 1.7.0
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: 31.0.6 => 31.0.6
  react: 16.6.3 => 16.6.3
  react-native: 0.57.8 => 0.57.8

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/arikanmstf-1bdc4436-24ef-4641-b24b-cf28ea40c6f1.tar.gz

### Steps to Reproduce

1. Running expo build like this: `API_ENV=live expo build:ios`

### Expected Behavior
Should build successfully

### Actual Behavior

As an application icon, I am using one withuot alpha or transparent channels. app.json is like this:

```json
{
  "expo": {
    "icon": "./static/img/icon-no-alpha.png",
    "sdkVersion": "31.0.0",
    "privacy": "unlisted",
    "platforms": ["ios"],
     ...
  }
}

``` 
![image](https://user-images.githubusercontent.com/13220774/54234807-8b4b2480-4518-11e9-9725-ae7b2b03d9d9.png)

Build  was working correct with transparent png file, However with transparent png file, Xcode's `Application Loader`  fails with following error: 

`ERROR ITMS-90717: "Invalid App Store Icon. The App Store Icon in the asset catalog in 'ExpoKitApp.app' can't be transparent nor contain an alpha channel."`

![image](https://user-images.githubusercontent.com/13220774/54235046-13312e80-4519-11e9-92bf-4a141f5383b0.png)

### Reproducible Demo

Here can be found build with full log:

https://expo.io/builds/bf69c1c4-f2e2-486f-a984-4ff5d7d55d76

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by AdamJNavarro** [comment]
Hey @arikanmstf,

We are aware of this issue and are tracking it [here](https://github.com/expo/expo-cli/issues/414). You can get around this by downgrading your `expo-cli` version as indicated in that thread. Also, for future reference, please route issues that involve the `expo-cli` here: https://github.com/expo/expo-cli/issues

Cheers,
Adam

**Comment by arikanmstf** [comment]
@AdamJNavarro  , I dont have expo-cli installed. Should I downgrade expo sdk ? to which version ?

**Comment by arikanmstf** [comment]
@AdamJNavarro I tried with expo cli - 2.11.6 still same error.

**Comment by brentvatne** [comment]
you share the icon that you are having problems with?

**Comment by arikanmstf** [comment]
@brentvatne https://drive.google.com/file/d/1r2HzmNdeV0Mg5mnnEUGV9VO_BqW1tQu_/view?usp=sharing here inside zip.

**Comment by lebreRafael** [comment]
Same problem here.
I have tested with version 2.6.X, 2.13.0 and 2.11.6 and all have the same problem

**Comment by evanheckert** [comment]
I've also tried it with 2.11.6, 2.11.7 and 2.13.0 with the same result. Saved from Preview with no Alpha, and even tried Photoshop 8-bit, no transparency. Same result every time. Really need to get this published - any other ideas?

**Comment by lebreRafael** [comment]
I have finish my build successfully but I don't really know how.
I'm running expo-cli 2.11.8 and the steps that I did are listed below:

* Tried another 1024x1024 png file downloaded from google **(still got error)**
* Start a new project with expo, change the icon to my png and tried to build **(success)**
* Start to copy all configuration stuff from the new project to my project (package.json, app.json, babel.config.js) but obviously keeping particular things from my project such as name, version...
* I was using react-native 0.57.1 and the new project was using an exotic version, so I needed to run `yarn upgrade`
* After these two steps above I tried again to build and It worked.
* After that I decided to delete my project and clone again to test if just changing the react-native version It works, but before that I tried to build immediately after clone and install dependencies to see the error again. But for the surprise the error has gone. It works without any changes now

**Comment by evanheckert** [comment]
@lebreRafael Thanks for sharing what worked for you! I'll give that a try, although I have two separate projects with the same issue. If you find anything else on this, I'd love to hear a reliable solution!

**Comment by evanheckert** [comment]
Same result with 2.14.0.

**Comment by evanheckert** [comment]
Interesting. So both icons work fine if I'm using the proper version of react-native. Unfortunately, I've built this all with hooks, so I'm using `"react-native": "npm:@brunolemos/react-native",`. This works just fine in dev, and I can expo publish just fine. It's when I expo build:ios that it fails.

The weird thing is, one of my icons works every time even with this odd version of react-native, while the other gets the error every time. Both were made the same way, both have no alpha channels. I can't for the life of me figure out why one would work and the other wouldn't? Is there any chance full white with no alpha would cause this?

**Comment by arikanmstf** [comment]
any updates for this issue ?

**Comment by arikanmstf** [comment]
I tried with last version of expo-cli, 2.16.1 

Previously working, app icon is not working now. Error says 

> Your application icon can't have transparency if you wish to upload your app to Apple Store.

as implemented in the commit.


Well, but still can not build with my no-alpha image. I dont know. Send me any icon if it works. I will try that one.

**Comment by dsokal** [comment]
@arikanmstf 
I checked your build logs and it looks like it's not a problem with the icon itself, but rather with that the icon is not uploaded to Expo servers :) Check it yourself - please open the build logs, expand `reading manifest` group and find `iconUrl` there. Try opening the url in the browser, you'll get Access Denied error from S3 which means that there is no image you're looking for.
I think that in order to fix it, you need to make sure you have `assetBundlePatterns` key in your `app.json`:
```
{
  "expo": {
    ...,
    "assetBundlePatterns": [
      "**/*"
    ],
    ...,
  }
}
```
and then publish your app (or run `expo build:ios`). The error should go away.

@lebreRafael @evanheckert 
First of all, if you want to use Expo, you can't change `react-native` version to a one chosen by you. You must use the version provided by Expo for each SDK release.

**Comment by arikanmstf** [comment]
@dsokal , I've Tried error says:

```
{"buildID":"4","type":"bundle_transform_progressed","transformedFileCount":1099,"totalF
Cannot read property 'forEach' of undefined
Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by dsokal** [comment]
@arikanmstf I'm guessing here but you most probably changed the `react-native` package version to a one from npm. If you wish to use Expo you must use a version released by our team. Expo's `react-native` version should look like this - https://github.com/expo/turtle-cli-example/blob/master/package.json#L15

**Comment by cem2ran** [comment]
@dsokal We've started experiencing this issue yesterday on CI. SDK32
https://forums.expo.io/t/error-failed-to-resize-image-appicon29x29-2x-png/23829

**Comment by priapproved** [comment]
@dsokal Were you able to determine what was going on? We ran into OP's issue, thereafter we updated the `assetBundlePatterns` as recommended, and now we have your problem as well.

**Comment by arikanmstf** [comment]
@dsokal 

Packages: (wanted => installed)
expo: 31.0.6 => 31.0.6
react: 16.6.3 => 16.8.6
react-native: 0.57.8 => 0.57.8

**Comment by dsokal** [comment]
@arikanmstf 
Please read my comments carefully:
https://github.com/expo/expo/issues/3711#issuecomment-491252136
https://github.com/expo/expo/issues/3711#issuecomment-500322583

**Comment by pauldcollins** [comment]
Hi @dsokal 

Thanks for your help, I've followed your instructions, including copying and pasting the dependencies from your [comment here](https://github.com/expo/expo/issues/3711#issuecomment-500322583)

I'm still getting the `Cannot read property 'forEach' of undefined` error. The original error was definitely the image upload error you mentioned earlier. 

If you have any other suggestions, I would be greatly appreciative.

**Comment by eddyoc** [comment]
Having the same issue. PNG has no transparency. Verified that in Photoshop. And yet I see the error 
```
Your application icon can't have transparency if you wish to upload your app to Apple Store.
```
upon performing 
```
expo build:ios
```
Is there a workaround for this?

**Comment by brad-n** [comment]
Looking for a work around as well.  Everything worked fine a couple months ago.  Made a quick code change and ran build:ios and I'm getting the same complaint about the icon as everyone else.  The bundle pattern breaks it in different ways or doesn't do anything.

**Comment by tsapeta** [comment]
Looks like this issue is pretty old and is related to the SDK that is no longer supported and we didn't get similar reports for newer SDK versions. I'm closing it but feel free to create a new issue if it still persists.
