### ISSUE TITLE
[expo-payments-stripe] Using old version of tipsi-stripe

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#3714]
# READ THIS FIRST, PLEASE!

### Environment

  Expo CLI 2.11.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.4.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.11.7

iOS, Android, + ExpoKit
### Steps to Reproduce

(Write your steps here:)

1. try to use PaymentsStripe from `expo-payments-stripe` with type `card`:
```
    const params = {
      type: 'card',
      number: cardValues.number,
      expMonth: parseInt(exp[0], 10),
      expYear: parseInt(exp[1], 10),
      cvc: cardValues.cvc,
      amount: 500,
      currency: 'USD',
    };

   const source = await stripe.createSourceWithParamsAsync(params);
```

### Expected Behavior

Expected to work and create a card payment.

### Actual Behavior

Get an error 

"[Unhandled promise rejection: Error: Failed params type: Invalid params `type` of value `card` supplied to `Stripe.createSourceWithParams`, expected one of ["bancontact","giropay","ideal","sepaDebit","sofort","threeDSecure","alipay","wechat"].]
"
There was a bug in tipsi-stripe's implementation, and now expo's payment kit needs to be updated as they have fixed the bug: https://github.com/tipsi/tipsi-stripe/pull/261/files

**Comment by n-sviridenko** [comment]
Any updates on this?
Our app crashes on sdk-30. More details are here https://gist.github.com/n-sviridenko/d61a5310863663063cc9a8579eafbeea .

**Comment by n-sviridenko** [comment]
<img width="1191" alt="main_m" src="https://user-images.githubusercontent.com/9335422/56083915-ae286b80-5e2b-11e9-963a-ca3413bce285.png">

**Comment by changLiuUNSW** [comment]
Same here. Any update ?

**Comment by sjchmiela** [comment]
We shall update `expo-payments-stripe` as soon as possible, but I can't promise any clear timeline. Would you care to make the proposed changes (to either `expo-payments-stripe` or docs) and submit a PR? 🙂

**Comment by changLiuUNSW** [comment]
Not very familiar with native codes :(
I probably create a PR to remove ```type = card``` from docs.

**Comment by johnli611** [comment]
Is it possible to remove expo-payments-stripe from ExpoKit after ejecting? We got rejected from the Apple App Store because Stripe was in the podspec.

**Comment by changLiuUNSW** [comment]
@johnli611 .  I cannot see it in my Podfile. I believe it is optional. 
https://docs.expo.io/versions/v33.0.0/expokit/universal-modules-and-expokit/
Which version of Expo are you using?

**Comment by johnli611** [comment]
v32

I added ExpoKit Stripe as well as tipsi-stripe at some point, but just removed it all from my package.json and podfile files. I believe this might be the main cause of the rejection.

However, after removing all that Stripe still shows up in my ExpoKit.podspec.json file as seen below (scroll to the bottom). I'm not very familiar with what this file does. Will this affect my app store submission?

```
{
  "name": "ExpoKit",
  "version": "32.0.0",
  "summary": "ExpoKit",
  "description": "ExpoKit allows native projects to integrate with the Expo SDK.",
  "homepage": "http://docs.expo.io",
  "license": "MIT",
  "authors": "650 Industries, Inc.",
  "requires_arc": true,
  "platforms": {
    "ios": "10.0"
  },
  "default_subspecs": "Core",
  "source": {
    "git": "http://github.com/expo/expo.git"
  },
  "subspecs": [
    {
      "name": "Core",
      "source_files": [
        "ios/Exponent/**/*.{h,m}",
        "template-files/keys.json"
      ],
      "preserve_paths": "ios/Exponent/**/*.{h,m}",
      "exclude_files": [
        "ios/Exponent/Supporting/**",
        "ios/Exponent/Versioned/Optional/**/*.{h,m}"
      ],
      "dependencies": {
        "Amplitude-iOS": [
          "~> 3.8"
        ],
        "Analytics": [
          "~> 3.5"
        ],
        "AppAuth": [
          "~> 0.4"
        ],
        "CocoaLumberjack": [
          "~> 3.2.1"
        ],
        "Crashlytics": [
          "~> 3.8"
        ],
        "FBAudienceNetwork": [
          "4.99.0"
        ],
        "FBSDKCoreKit": [
          "4.38.1"
        ],
        "FBSDKLoginKit": [
          "4.38.1"
        ],
        "FBSDKShareKit": [
          "4.38.1"
        ],
        "Fabric": [
          "~> 1.6"
        ],
        "GoogleSignIn": [
          "~> 4.1"
        ],
        "GoogleMaps": [
          "~> 2.5.0"
        ],
        "Google-Maps-iOS-Utils": [
          "~> 2.1.0"
        ],
        "lottie-ios": [
          "~> 2.5.0"
        ],
        "JKBigInteger2": [
          "0.0.5"
        ],
        "Branch": [
          "~> 0.24.2"
        ],
        "Google-Mobile-Ads-SDK": [
          "~> 7.22.0"
        ],
        "React": [

        ],
        "EXCore": [

        ],
        "EXReactNativeAdapter": [

        ],
        "EXSensorsInterface": [

        ],
        "EXFileSystemInterface": [

        ],
        "EXPermissionsInterface": [

        ],
        "EXCameraInterface": [

        ],
        "EXConstantsInterface": [

        ]
      }
    },
    {
      "name": "Payments",
      "dependencies": {
        "ExpoKit/Core": [

        ],
        "Stripe": [
          "~> 10.1.0"
        ]
      },
      "source_files": "ios/Exponent/Versioned/Optional/Payments/*.{h,m}"
    },
    {
      "name": "AR",
      "dependencies": {
        "ExpoKit/Core": [

        ]
      },
      "source_files": "ios/Exponent/Versioned/Optional/ARKit/**"
    },
    {
      "name": "FaceDetector",
      "dependencies": {
        "EXFaceDetector": [

        ]
      }
    }
  ]
}

```

**Comment by changLiuUNSW** [comment]
@johnli611 This is normal. 
s long as it doesn't appear in your Podfile, it should be fine.

**Comment by changLiuUNSW** [comment]
Also it is worthy to check your podlock file

**Comment by johnli611** [comment]
Great thank you @changLiuUNSW!!

**Comment by tsapeta** [comment]
Closing this as we no longer support ExpoKit and this issue report was made for pretty old SDK32. Please open a new bug report if this issue still exists in bare workflow.
