### ISSUE TITLE
Provide guide for use with React Native Web

### ISSUE THREAD

**Issue by AlfredOdling** [expo/expo#3718]
React Native Web and hybrid apps are becoming more popular and it works with apps bootstrapped with Expo. But when trying to implement certain Expo components, such as LinearGradient the follow error occurs:
`'expo' does not contain an export named 'LinearGradient'`

How do I get around this?

**Comment by AdamJNavarro** [comment]
Hey @AlfredOdling,

We'll provide resources and documentation when we officially roll out web support but until then you'll have to navigate the waters on your own as we don't have the bandwidth to provide support for something that is not release yet.

Cheers,
Adam
