### ISSUE TITLE
Error when preloading and caching assets

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#372]
Hi,

I'm preloading and caching assets as described here: https://docs.expo.io/versions/v18.0.0/sdk/app-loading.html#app-loading

The app runs fine in the iOS simulator, caching images.

If I turn the WiFi off on my laptop though the app stops working and I get this red screen error:

![screenshot](https://user-images.githubusercontent.com/3594037/27960196-b1a43576-632a-11e7-96a4-4869902f643f.png)

Isn't caching supposed to work offline? Before I modified the app as described above it was working also with WiFi off without any problem.

Can you please help me understand what's going on and how to fix it? Thanks

**Comment by terribleben** [comment]
This should be fixed with https://github.com/expo/expo/commit/8b49c527ce5a5b318cd3dce2ce6452e7467a0744 which will hopefully ship this week.

**Comment by pensierinmusica** [comment]
Ok, thx!

**Comment by terribleben** [comment]
This shipped - let me know if the bad behavior is still happening and I can reopen.
