### ISSUE TITLE
SQLite transactions do not work.

### ISSUE THREAD

**Issue by enzomd** [expo/expo#3726]
When `tx.executeSql(`x`, [], onSuccess, onError);` is run inside a `db.transaction(t, error, success)`, each statement runs as its own transaction.

The expo API does not issue any `BEGIN TRANSACTION` or `COMMIT TRANSACTION` statements.
https://www.sqlite.org/lang_transaction.html 

This is misleading as the documentation does not mention this, and the API specifically mentions `transaction`.

Here is a reproduction:

https://snack.expo.io/r1A-1yPw4
- A table is created, with a single row inserted.
- Inside the same transaction, a SQL syntax error is purposely thrown.
- What should happen: Transaction is rolled back, no changes applied to DB, transaction error callback called.
- What happens: The new table and row are written to disk, the transaction success callback is called.

Please can you update your documentation to mention that transactions are not supported.

**Comment by brentvatne** [comment]
cc @sjchmiela not sure who should check this out

**Comment by emadda** [comment]
Ive written a library that allows you to use SQLite transactions:

https://github.com/sqlite-mpi/sqlite-mpi-client-js

**Comment by duckbrain** [comment]
This issue just bit me pretty hard, so I'm trying to find a way to work around it; here is what I have discovered so far as of Expo 36.

On Linux (for unit tests) it appears to wrap individual statements in transactions because I don't get transaction behavior, but `BEGIN TRANSACTION` fails with SQLITE_ERROR: cannot start a transaction within a transaction. I've refactored my code to abstract `expo-sqlite` away and am looking into using another node SQLite library for tests.

On Android, It doesn't seem to use transactions at all. I've been able create my own wrapper function that does a list of queries in a transaction.

<details>

<summary>My wrapper for transactions on Android</summary>

```typescript

function sqlQueryTransaction(
  db: WebSQLDatabase,
  sqlList: string[],
  argsList: string[][] = []
): Promise<SQLResultSet[]> {
  return new Promise((resolve, reject) => {
    const results = new Array<SQLResultSet>(sqlList.length);

    function handleError(context: string, query: string = "") {
      return (tx: SQLTransaction, error: SQLError) => {
        tx.executeSql("ROLLBACK TRANSACTION;");
        reject(new Error(`${context} ${error.message}`));
        // we return false because the WebSQL API requires a return value, but
        // doesn't say what it's for. It appears that expo-sqlite ignores it.
        return false;
      };
    }

    db.transaction(
      tx => {
        tx.executeSql(
          "BEGIN TRANSACTION;",
          [],
          () => {
            let remainingQueries = sqlList.length;
            sqlList.forEach((q, i) => {
              const args = argsList[i] || [];
              tx.executeSql(
                q,
                args,
                (tx, resultSet) => {
                  results[i] = resultSet;
                  remainingQueries--;
                  if (!remainingQueries) {
                    tx.executeSql(
                      "COMMIT TRANSACTION",
                      [],
                      () => {},
                      handleError("commit")
                    );
                  }
                },
                handleError("query", q)
              );
            });
          },
          handleError("tx")
        );
      },
      error => {
        // This appears to never be called.
      },
      () => {
        resolve(results);
      }
    );
  });
}
```

</details>

On iOS, I'm having trouble with what I think is #5760, so I can't test it right now. When I get it compiling I'll update.

@emadda, thanks. I'll be looking into using that once I get compilation working.

**Comment by viktor-podzigun** [comment]
@enzomd it works for me, as per spec [here](https://www.w3.org/TR/webdatabase/) to rollback transaction you should either do not specify error handler (`null`) or return true from it:

```javascript
tx.executeSql("...", [], null, null)
//or
tx.executeSql("...", [], null, (tx, error) => {
  return true //rollback
})
```

**Comment by enzomd** [comment]
@viktor-podzigun I think your right, I tested with returning `true` from the error handler and this rolled back the transaction. Thanks for posting the solution.

Expo includes `node-websql` here:
https://github.com/expo/expo/blob/master/packages/expo-sqlite/src/SQLite.ts#L3
 
`ROLLBACK` is defined here:
https://github.com/nolanlawson/node-websql/blob/master/lib/websql/WebSQLDatabase.js#L10

I think maybe this should be documented/added to the Expo test cases.

**Comment by viktor-podzigun** [comment]
@enzomd you are welcome, happy that it was helpful for you :)

+1 for documenting it in the expo docs together with the `readTransaction` method that is also available, will try to find a time to provide PR for it.
