### ISSUE TITLE
expo-mail-composer invokes UIKit methods off main thread causing assertion failures and logspam

### ISSUE THREAD

**Issue by joelgetaction** [expo/expo#3728]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

  Expo CLI 2.11.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.6 => 0.58.6
      react-navigation: ^3.3.2 => 3.3.2

iOS expo bare app created with bare-minimum template and using expo-mail-composer

### Steps to Reproduce

(Write your steps here:)

Invoke mail composer as follows:
```
MailComposer.composeAsync({
      recipients: ["joel@test.com"],
      subject: "Feedback About Your App",
      body: "The body",
      isHtml: false,
    });
```

1. Install expo-mail-composer.
2. Invoke `MailComposer.composeAsync` as above in response to a button push.
3. See dangerous warnings about EXMailComposer invoking UIKit methods off of the main thread.

### Expected Behavior

(Write what you thought would happen.)

MailComposer should NOT invoke UIKit methods off of the main thread and should NOT cause scary assertion warnings in logs.

### Actual Behavior

(Write what happened. Add screenshots!)

MailComposer should DOES invoke UIKit methods off of the main thread and DOES cause scary assertion warnings in logs.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

This is a bare minimum template bare expo app so I cannot create a snack.  However, here is the stack trace:

```
2019-03-13 16:27:09.160615-0600 BidVidClientMobile[46856:8712133] [Animation] +[UIView setAnimationsEnabled:] being called from a background thread. Performing any operation from a background thread on UIView or a subclass is not supported and may result in unexpected and insidious behavior. trace=(
	0   UIKitCore                           0x0000000220453710 <redacted> + 136
	1   libdispatch.dylib                   0x00000001036e0dc8 _dispatch_client_callout + 16
	2   libdispatch.dylib                   0x00000001036e2e28 _dispatch_once_callout + 84
	3   UIKitCore                           0x0000000220453684 <redacted> + 100
	4   UIKitCore                           0x000000022045380c <redacted> + 92
	5   UIKitCore                           0x000000021f77cb1c <redacted> + 336
	6   UIKitCore                           0x000000021f77d794 <redacted> + 1376
	7   UIKitCore                           0x000000021f77bedc <redacted> + 360
	8   UIKitCore                           0x000000021f785a50 <redacted> + 256
	9   UIKitCore                           0x000000021f785d14 <redacted> + 216
	10  UIKitCore                           0x000000021f80455c <redacted> + 800
	11  UIKitCore                           0x000000021f80478c <redacted> + 232
	12  UIKitCore                           0x000000021f7c22ac <redacted> + 272
	13  UIKitCore                           0x000000022046177c <redacted> + 1380
	14  UIKitCore                           0x000000021f7c1fd4 <redacted> + 244
	15  QuartzCore                          0x00000001f73d9b7c <redacted> + 184
	16  QuartzCore                          0x00000001f73deb34 <redacted> + 324
	17  UIKitCore                           0x000000022044cc68 <redacted> + 548
	18  UIKitCore                           0x000000021f94d5fc <redacted> + 696
	19  UIKitCore                           0x000000021f94d848 <redacted> + 396
	20  UIKitCore                           0x000000021f94cfa4 <redacted> + 1356
	21  UIKitCore                           0x000000021f94c90c <redacted> + 132
	22  UIKitCore                           0x000000021f953e90 <redacted> + 208
	23  UIKitCore                           0x000000021f9f1554 <redacted> + 172
	24  UIKitCore                           0x000000021f9f1cc0 <redacted> + 28
	25  UIKitCore                           0x000000021f961e78 <redacted> + 540
	26  UIKitCore                           0x000000021f961a28 <redacted> + 676
	27  MessageUI                           0x0000000208a5d4c8 <redacted> + 268
	28  BidVidClientMobile                  0x0000000102abfe88 -[EXMailComposer composeAsync:resolver:rejecter:] + 288
	29  CoreFoundation                      0x00000001f2de5610 <redacted> + 144
	30  CoreFoundation                      0x00000001f2cc3340 <redacted> + 292
	31  BidVidClientMobile                  0x0000000102aa6574 -[EXExportedModule callExportedMethod:withArguments:resolver:rejecter:] + 1200
	32  BidVidClientMobile                  0x0000000102ad05a0 __79-[EXNativeModulesProxy callMethod:methodNameOrKey:arguments:resolver:rejecter:]_block_invoke + 64
	33  libdispatch.dylib                   0x00000001036df824 _dispatch_call_block_and_release + 24
	34  libdispatch.dylib                   0x00000001036e0dc8 _dispatch_client_callout + 16
	35  libdispatch.dylib                   0x00000001036e8e6c _dispatch_lane_serial_drain + 720
	36  libdispatch.dylib                   0x00000001036e9b60 _dispatch_lane_invoke + 460
	37  libdispatch.dylib                   0x00000001036f3bfc _dispatch_workloop_worker_thread + 1220
	38  libsystem_pthread.dylib             0x00000001f29f90dc _pthread_wqthread + 312
	39  libsystem_pthread.dylib             0x00000001f29fbcec start_wqthread + 4
)
2019-03-13 16:27:09.162578-0600 BidVidClientMobile[46856:8712133] [Assert] Cannot be called with asCopy = NO on non-main thread.
2019-03-13 16:27:09.162637-0600 BidVidClientMobile[46856:8712133] [Assert] Cannot be called with asCopy = NO on non-main thread.
```

The offending line in the stack trace indicates that this is clearly a bug in `expo-mail-composer`:
```
	28  BidVidClientMobile                  0x0000000102abfe88 -[EXMailComposer composeAsync:resolver:rejecter:] + 288
```
[Here is the offending code](https://github.com/expo/expo/blob/master/packages/expo-mail-composer/ios/EXMailComposer/EXMailComposer.m#L27).

**Comment by joelgetaction** [comment]
Thanks @tsapeta !

**Comment by tsapeta** [comment]
All props go to @sjchmiela who took care of that 😊

**Comment by joelgetaction** [comment]
Thanks @sjchmiela !  Really appreciate your hard work on Expo.  :-)
