### ISSUE TITLE
GLView not showing on Android

### ISSUE THREAD

**Issue by y5bcit** [expo/expo#3735]
### Environment
  Expo CLI 2.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files (x86)\Microsoft Visual Studio\2017\MSBuild\Microsoft\VisualStudio\NodeJs\npm.CMD

Build Target: Android

### Steps to Reproduce

1. Create a `<GLView>`
2. Add a alert to [onContextCreate](https://docs.expo.io/versions/latest/sdk/gl-view/#props)`onContextCreate={gl => {
            Alert.alert('GL context created1');
          }}`

### Expected Behavior

A alert should show up, indicate `onContextCreate` triggered.
![image](https://user-images.githubusercontent.com/46827125/54331111-aa5bbc00-45d5-11e9-9404-7f545b31a7c5.png)

### Actual Behavior

The alert doesn't show up, indicate `onContextCreate` not triggered. This only happens on Android.
![image](https://user-images.githubusercontent.com/46827125/54331027-5e107c00-45d5-11e9-9457-90ca208e7438.png)

### Reproducible Demo

https://snack.expo.io/@y5bcit/expo-glview
Switch target device to iOS to see expected behavior, and Android to see actual behavior.

**Comment by cruzach** [comment]
Hey @y5bcit ,

Thanks for the repro! Have you also experienced this on a physical Android device, or just on the simulator?

Thanks,
Charlie

**Comment by y5bcit** [comment]
> Hey @y5bcit ,
> 
> Thanks for the repro! Have you also experienced this on a physical Android device, or just on the simulator?
> 
> Thanks,
> Charlie

Yes, on my Android 7.1 device. I thought I did something wrong when the expo-three didn't show up, but then I found GLView itself doesn't work. 

However, [`gl-react-expo`](https://github.com/gre/gl-react), which `backed by Expo implementation`, can display shaders correctly (without using `onContextCreate`)

**Comment by tsapeta** [comment]
Hey @y5bcit,
Indeed, there is a bug in our code but it occurs only when one of the `GLView`'s dimension equals to 0. Looks like it can be fixed easily in your JS code by setting a height of the `GLView` to a non-zero value.

**Comment by y5bcit** [comment]
Hey @tsapeta ,
Thanks for answering. I've try to add width prop and width in style props, but it doesn't help. Missing something?
Snack updated: [width and style props added](https://snack.expo.io/@y5bcit/expo-glview)
