### ISSUE TITLE
Missing info in ImagePicker response?

### ISSUE THREAD

**Issue by allpwrfulroot** [expo/expo#374]
When I successfully choose an image with ImagePicker.launchImageLibraryAsync(), the response is as follows:
```
{
  "cancelled": false,
  "height": 498,
  "uri": "file:///Users/xxxxx...69-439B-8D96-3408D1B3A5A6.jpg",
  "width": 746,
}
```
There used to be a fileSize field that was super handy. I see it in v17 but not v18, can we possibly get that restored?

**Comment by nikki93** [comment]
You should be able to use the "FileSystem" API that will be present in the new versions of the SDK to get this information now!
