### ISSUE TITLE
Any way to user MapView.Animated?

### ISSUE THREAD

**Issue by vitorfreitas** [expo/expo#3740]
I'm trying to set up some smooth animation between locations, but MapView.Animated doesn't work, MapViewAnimated expo component neither. How can I do that using expo?

**Comment by cruzach** [comment]
Hey @vitorfreitas,

If you're having an issue, please follow the template we provide. This way you give us all the info we need to troubleshoot and help you out as fast as we can!

If this is just a question on how to use something, and not necessarily a possible bug you found, then it's much better to just post a question over at our [How-to Forums](https://forums.expo.io/c/how-to)

Thanks!
Charlie

**Comment by vitorfreitas** [comment]
Got it. Thanks!
