### ISSUE TITLE
MediaLibrary.getAssetInfoAsync size bug on Android

### ISSUE THREAD

**Issue by djbuch** [expo/expo#3744]
### Environment

Bugs on Android, tested on different devices in Standalone and Expo App

### Steps to Reproduce

Take a video on Android, initially when I record in Portrait, I get `width: 0, height: 0`. When I switch to Landscape I get `width: 1920, height: 1080` and after switching back I get the same value as landscape ( `width: 1920, height: 1080`).

On iOs every works fine

### Expected Behavior

The width and height in Portrait should be width: 1080, height: 1920 (or according to device recording options but in portrait format and available since the first record)

### Actual Behavior

The size is wrong

### Reproducible Demo

Here you have a Snack https://snack.expo.io/@djbuch/android-camera-bug showing the bug.

**Comment by djbuch** [comment]
Hello, have you any news about this point ?

**Comment by lukmccall** [comment]
I've tried to reproduce this bug. It seems to work in SDK 35. So I'm closing this issue. Feel free to open this if this bug still exists.
