### ISSUE TITLE
Unable to resolve "./createHandler" from "node_modules/react-native-gesture-handler/GestureHandler.js"

### ISSUE THREAD

**Issue by imad93** [expo/expo#3746]
Steps to reproduce:
1- run `npm install --save react/navigation`
2- run `react-native link react-native-gesture-handler` (tried it with and without this command)
3- run `npm install`
4- run `npm start`
5- run on simulator or on phone expo app and you will get this error

Versions I am using:
Expo SDK: 32.0.0
react-native: 16.5.0
 react-navigation: ^3.3.2
react-native-gesture-handler: 1.0.17
![Screen Shot 2019-03-15 at 08 07 06](https://user-images.githubusercontent.com/10802895/54414673-31a25000-46fa-11e9-8b86-8527b528d7eb.jpeg)

**Comment by brentvatne** [comment]
i'm not sure what was misconfigured in your project because you didn't share a reproducible example, the only incorrect thing in the steps you listed above is step 2.

https://reactnavigation.org/docs/en/getting-started.html#installation

notice that it says:

> Next, install react-native-gesture-handler. If you’re using the Expo managed workflow then you don’t need to do anything here, it’s included in the SDK. Otherwise:

so you can skip everything after that point. i just created a new blank expo project and added `react-navigation` and it worked as expected

**Comment by dhmoclex** [comment]
Hello,

I got this error, and after a very search I found that the name of my root directory was the problem, I renamed it from "projet-2019-chirac_debenay" to "test-aaaaaaaaaaaaaaaaaaaah" and it worked.

Cheers.

**Comment by daveols** [comment]
@dhmoclex I believe the reason this worked is because you implicitly busted the packager cache.

This fixed the issue for me:

```shell
rm -rf $TMPDIR/haste-map-*
rm -rf $TMPDIR/metro-cache*
```

**Comment by dhmoclex** [comment]
Thanks.

More commands about cleanning npm cache and so on can be found here:
https://www.bountysource.com/issues/29386320-workarounds-packager-unable-to-resolve-module-from-users-node_modules

Cheers.

**Comment by prionkor** [comment]
I have having the same issue. But still not working.

```
$ npm list react-native react-native-gesture-handler

├─┬ expo@32.0.6
│ └── react-native-gesture-handler@1.0.17 
└── react-native@0.57.1 
```

**Tried **

-  deleting `node_modules`, `package-lock.json` and reinstall them. 
- `rm -rf $TMPDIR/haste-map-*`
- `rm -rf $TMPDIR/metro-cache*`
-  `npm start --reset-cache`

**Worked:** Renaming the project directory :-/

**Comment by gac3k** [comment]
For anybody struggling with Expo, what has worked for me is:

`expo r -c`

Which clears the packager cache. Then simply `npm start`

**Comment by bestkanthed** [comment]
`npm uninstall react-native-gesture-handler --save`
`npm install react-native-gesture-handler --save`
