### ISSUE TITLE
headerRight disappear when passing data from a function 

### ISSUE THREAD

**Issue by Rafaell416** [expo/expo#375]
hello, i'm trying to navigate between screens using a button in header RIght but, when I pass navigate from the function the button is not shown in the screen.
This is the code: 

`headerRight: ({ navigate }) => <AddIcon navigate={navigate}/>    //disappears of the screen`  

`headerRight:  <AddIcon />    //appears in the screen`

**Comment by terribleben** [comment]
Hi, unfortunately we can't provide support for navigation libraries on this repo. I recommend using the reactnative or react-navigation channels on our [Slack](http://slack.expo.io/), or reaching out in the community for the navigation library.
