### ISSUE TITLE
Possible Unhandled Promise Rejection: Geocoder is not running

### ISSUE THREAD

**Issue by codGmer** [expo/expo#3753]
### Environment

<Expo CLI 2.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842>

SDK 32 

My target is Android and IOS. I am experiencing this error on my android device, i haven't yet tested it on the iphone.

### Steps to Reproduce

1. Cmd: `expo init geocodebug`
2. Choose blank template
3. Name: geocodedebug
    Slug: geocodebug
4. Cd geocodebug
5. Cmd: `npm install --save react-navigation`
6. Copy files from the [Github repo](https://github.com/codGmer/geocoderbugreport) and overwrite in 'geocodedebug' folder
7. Npm start
8. Open app in expo
9. Click on the 'Open shared link' button.

### Expected Behavior

I expected the full output (latitude,longitue) of the translated address from the geocode process in the console.

### Actual Behavior

No output on the console from the geocoder function. Instead error:

`[Unhandled promise rejection: Error: Geocoder is not running.]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:146:41 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:95:55 in <unknown>
- ... 5 more stack frames from framework internals`

### Reproducible Demo

[Github repo](https://github.com/codGmer/geocoderbugreport)

Download these files and place and replace them in your new project.
The issue seems to come up only when I use the `Linking.addEventListener('url', this._handleRedirect);` and then continue to another page to then convert the address to coördinates.

**Comment by cruzach** [comment]
Hey @codGmer,

I tried reproducing and didn't experience this error. Both in development and a published app. 
Are you sure this is the exact code that results in the error on your side? If so, it might have to do with your environment. Run `expo diagnostics` and let me know what the output is.

Thanks!
Charlie

**Comment by codGmer** [comment]
@cruzach, yes that is the exact code that gives me the error, I will try it again for verification.

This is my diagnostics output:  <Expo CLI 2.11.9 environment info:
System:
OS: Windows 10
Binaries:
npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.3.0.0 AI-182.5107.16.33.5314842>

SDK 32

**Comment by codGmer** [comment]
I have tested the issue myself on another computer and it seems to work there, What can I do to resolve this, reinstall all?

**Comment by cruzach** [comment]
When you tested on the other computer, did you use the same physical device for testing?

**Comment by codGmer** [comment]
@cruzach yes i did.

**Comment by cruzach** [comment]
I'm running the same version of the Expo CLI as you, only major difference is npm version (I'm using `6.9.0`). 

Was there anything significantly different about the environment of the computer you were able to get it to work correctly on?

**Comment by matias91** [comment]
Hi, everyone!
My team is having the same issue with an app just released to production.
We are using Bugsnag so I'm attaching two screenshots with some details.

**Error:**
<img width="912" alt="bugsnag-1" src="https://user-images.githubusercontent.com/2778383/66004414-2688f480-e47f-11e9-9568-a8c0f6f39f8e.png">

`"Get location failed"` is just a custom title that we added to the error.

**Details:**
<img width="811" alt="bugsnag-3" src="https://user-images.githubusercontent.com/2778383/66004417-2688f480-e47f-11e9-90f5-5ac196d8a875.png">

```
expo diagnostics

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @bugsnag/expo: ^6.4.0 => 6.4.0 
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.16.0 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.1.2
```

There is something that can be done to solve this?
Thanks in advance!

**Comment by SeanRenet** [comment]
@cruzach this happens randomly.  I even have my location code wrapped inside Location.hasServicesEnabledAsync()  and Location.getProviderStatusAsync().  I have only noticed the behavior on android.  The randomness could be because my cell network where I live in Los Angeles is horrible, but that's a real world test.

Seans-MBP:~ $ expo -V
3.9.1
Seans-MBP:~ $ expo-cli -V
3.9.1
Seans-MBP:~ $ npm -v
6.13.1
Seans-MBP:~ $ node -v
v13.2.0


"dependencies": {
    "@typescript-eslint/eslint-plugin": "^2.9.0",
    "base-64": "^0.1.0",
    "expo": "^35.0.0",
    "expo-camera": "~7.0.0",
    "expo-constants": "~7.0.0",
    "expo-facebook": "~7.0.0",
    "expo-google-app-auth": "^7.0.0",
    "expo-image-manipulator": "~7.0.0",
    "expo-image-picker": "~7.0.0",
    "expo-location": "~7.0.0",
    "expo-permissions": "~7.0.0",
    "faker": "^4.1.0",
    "firebase": "^7.5.0",
    "metro-react-native-babel-transformer": "^0.57.0",
    "moment": "^2.24.0",
    "nanoid": "^2.1.7",
    "native-base": "^2.13.8",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-action-sheet-component": "^0.0.36",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.2.0",
    "react-native-safe-area-context": "~0.3.6",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-form": "^8.2.6",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "uuid": "^3.3.3"
  },

**Comment by cruzach** [comment]
Could you try and reproduce on a blank project? Much easier to narrow down the root cause

**Comment by SeanRenet** [comment]
@cruzach can you give me a package.json that you would like me to test with?

**Comment by cruzach** [comment]
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~36.0.0",
    "expo-location": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.0.0"
  },
  "private": true
}
```

**Comment by kdthomas2121** [comment]
I'm seeing this issue when the app is in the background for a while, and is opened. Even in a try catch this crashes my app

`  try {
      if (isConnected && appState.current === "active") {
        const addressResult = await Location.reverseGeocodeAsync({
          latitude: location.coords.latitude,
          longitude: location.coords.longitude,
        });
        if (addressResult.length > 0) {
          address = addressResult[0];
        }
      } else {
        console.log("not connected");

      }
    } catch (error) {
      console.log("not connected. Error", error);
      Sentry.Native.captureException("Error geocoding with expo: " + error)
    }`
