### ISSUE TITLE
Sometimes BarCodeScanner looks widely

### ISSUE THREAD

**Issue by aleki** [expo/expo#376]
This is normal view:
![screenshot_20170716-211127](https://user-images.githubusercontent.com/4836709/28250189-cfac19d8-6a6b-11e7-836b-9f18e46ff404.png)
But sometimes this is looks like this with the same code base:
![screenshot_20170716-211149](https://user-images.githubusercontent.com/4836709/28250190-d57b66de-6a6b-11e7-9e26-3f9a922f3f06.png)

**Comment by aleki** [comment]
sdkVersion: 18.0.0,
platform: android

**Comment by dikaiosune** [comment]
@nikki93 correct me if I'm wrong but I think we're just vendoring a Google library for this, am I correct?

@aleki can you reproduce this with an SDK 20 example in https://snack.expo.io?

**Comment by aleki** [comment]
@dikaiosune Sorry, but I migrate from `create-react-native-app` to `react-native-cli`

**Comment by dikaiosune** [comment]
OK. Good to know. Sorry about this issues here. Since we don't have a recent reproduction I'll give this a close.
