### ISSUE TITLE
pod install fails with the latest versions.

### ISSUE THREAD

**Issue by manujbahl** [expo/expo#3760]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Environment

Standalone

### Steps to Reproduce
The latest standalone expo core fails validations in pod install

(Write your steps here:)

1. follow instructions at https://github.com/expo/expo/tree/master/packages/expo-sensors
2. npm install
3.pod install

### Expected Behavior

pods install fine.
(Write what you thought would happen.)

### Actual Behavior
pod install validation errors for missing information. ( similar issues with multiple modules )

gnoring ffi-1.9.18 because its extensions are not built. Try: gem pristine ffi --version 1.9.18
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
Installing unimodules:
expo-constants@4.0.0 from ../node_modules/expo-constants/ios
expo-file-system@4.0.0 from ../node_modules/expo-file-system/ios
expo-permissions@4.0.0 from ../node_modules/expo-permissions/ios
unimodules-barcode-scanner-interface@1.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
unimodules-camera-interface@1.0.0 from ../node_modules/unimodules-camera-interface/ios
unimodules-constants-interface@1.0.0 from ../node_modules/unimodules-constants-interface/ios
unimodules-core@1.0.0 from ../node_modules/@unimodules/core/ios
unimodules-face-detector-interface@1.0.0 from ../node_modules/unimodules-face-detector-interface/ios
unimodules-file-system-interface@1.0.0 from ../node_modules/unimodules-file-system-interface/ios
unimodules-font-interface@1.0.0 from ../node_modules/unimodules-font-interface/ios
unimodules-image-loader-interface@1.0.0 from ../node_modules/unimodules-image-loader-interface/ios
unimodules-permissions-interface@1.0.0 from ../node_modules/unimodules-permissions-interface/ios
unimodules-react-native-adapter@1.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
unimodules-sensors-interface@1.0.0 from ../node_modules/unimodules-sensors-interface/ios
unimodules-task-manager-interface@1.0.0 from ../node_modules/unimodules-task-manager-interface/ios

Analyzing dependencies
Fetching podspec for DoubleConversion from ../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec
Fetching podspec for EXConstants from ../node_modules/expo-constants/ios
[!] The EXConstants pod failed to validate due to 2 errors:
- ERROR | attributes: Missing required attribute authors.
- WARN | attributes: Missing required attribute license.
- ERROR | attributes: Missing required attribute homepage.
- WARN | license: Missing license type.
- WARN | source: Git sources should specify a tag.
- WARN | description: The description is equal to the summary.

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by tsapeta** [comment]
I've just tried initializing a new bare-minimum project using `expo-cli` and installing `expo-sensors` there, it works as expected - `pod install` succeeds.
Which version of CocoaPods do you have?

**Comment by tsapeta** [comment]
Closing as there are no more comments here and there is not enough info.
