### ISSUE TITLE
"disabled" prop not working

### ISSUE THREAD

**Issue by chrishaig14** [expo/expo#3762]
Here's the link to the snack:
https://snack.expo.io/B1irFscvE

I have a `TouchableWithoutFeedback` with `disabled={true}`. It just doesn't work, when I run it, both on the emulator online and on my own device, the `onPress` callback is still executed. 

If you put the same code here https://facebook.github.io/react-native/docs/tutorial it works fine.

**Comment by brentvatne** [comment]
If you wrap the `Text` in a `View` then it will work as expected - this seems to be a bug in react-native upstream. eg:

```js

        <TouchableWithoutFeedback
          disabled={true}
          onPress={() => {
            alert('without feedback!!!!!!');
          }}>
          <View>
            <Text
              style={{ backgroundColor: 'blue', padding: 10, color: '#fff' }}>
              Submit without feedback
            </Text>
          </View>
        </TouchableWithoutFeedback>
```

If you can open an issue on https://github.com/facebook/react-native/issues that would be appreciated!

<hr />

That said, I recommend using react-native-gesture-handler where possible for buttons etc:

```js
import { BaseButton } from 'react-native-gesture-handler';

// later on in render function
        <BaseButton
          enabled={false}
          onPress={() => {
            alert('base button!!!!!!');
          }}>
          <Text style={{ backgroundColor: 'blue', padding: 10, color: '#fff' }}>
            Submit without feedback via BaseButton
          </Text>
        </BaseButton>
```
