### ISSUE TITLE
main.js missing

### ISSUE THREAD

**Issue by sbdm05** [expo/expo#377]
Hello
I have already used Expo for previous project, and I use to work on main.js as the entry file. 
I have installed 3 times Expo today for my projects, and it seems that we now have to edit App.js at the root, but that the component is sent over to AppEntry.js in  ""node_modules/expo/AppEntry.js".
As we can see in package.json: 
```
{
  "name": "test",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^18.0.4",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-navigation": "^1.0.0-beta.11",
    "@expo/samples": "~1.0.4"
  },
  "devDependencies": {
    "jest-expo": "~18.0.0"
  }
}
```

So Iam lost here, is it normal ? Plus react-navigation is not working inside App.js

If anyone has a clue ? Thank you

**Comment by cbm4090** [comment]
this started happening for me as well.

**Comment by sbdm05** [comment]
Hi @cbm4090 , it seems like this is part of the version 18 ! ;-)

**Comment by dikaiosune** [comment]
Sorry for the delay here!

@sbdm05 yes, we moved the template projects over to use App.js to match CRNA and Snack. This allows for a number of nice improvements that we can bundle into the `expo` npm package without requiring developers to add them into their entry points.

react-navigation definitely works with App.js, so please open another issue with a repro of the bug you're seeing if you're still having problems there. Thanks!

**Comment by stevematdavies** [comment]
Im using a typescript project and I'm getting `App.tsx.js `not found, its driving me nuts because it isn't set anywhere

**Comment by brentvatne** [comment]
@stevematdavies - if you use the latest expo version it has babel 7 which supports typescript out of the box, so you can just rename App.js to App.tsx and it will work. more info at https://docs.expo.io/versions/v32.0.0/guides/typescript/
