### ISSUE TITLE
GLView crashing in bare project

### ISSUE THREAD

**Issue by pserrer** [expo/expo#3773]
### Environment

  Expo CLI 2.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

### Target

A real Android Pie device

### Steps to Reproduce

1. `expo init --template bare-minimum`
2. `yarn add expo-gl`, `yarn add expo-gl-cpp`
3. Adding `GLPackage` to MainApplication.java
4. Adding `GLView` from `expo-gl` to the app component
5. `yarn android`

### Expected Behavior

App should not crash and show at least a black box.

### Actual Behavior

App crashes and closes immediately after opening. Just got a very short glimpse at the black box. This happens always - even if I don't pass the `onContextCreate` param or trying to paint a black box on the canvas.

The debug log from Android Studio says:

> E/SoLoader: couldn't find DSO to load: libexpo-gl.so caused by: dlopen failed: "/data/data/com.chllng/lib-main/libexpo-gl.so" is 32-bit instead of 64-bit
> E/AndroidRuntime: FATAL EXCEPTION: mqt_js
>                   Process: com.chllng, PID: 16188
>                   java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libexpo-gl.so caused by: dlopen failed: "/data/data/com.chllng/lib-main/libexpo-gl.so" is 32-bit instead of 64-bit

If I add `ndk.abiFilters "armeabi-v7a", "x86"`, this error goes, but I got:

> A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x2e in tid 25832 (mqt_js), pid 25760 (com.chllng)

Any ideas how to solve this?

**Comment by Asday** [comment]
I _think_ this is the same issue I'm having?

```shell
npx expo-cli init .  # Name it whatever, use the bare template, don't use yarn.
npx expo-cli install expo-gl
```

Replace the contents of `App.js` with the following:

```es6
import { GLView } from 'expo-gl';
import React from 'react';

export default () => <GLView />
```

```shell
npx expo-cli start
```

Open the expo app on an iPhone, it'll load just fine, and show a blank white screen.

Open the expo menu, and enable remote JS debug.  Once the app has reloaded, it will instantly crash to desktop.

This is a new issue with SDK33.  There's no difference between `import { GLView } from 'expo'` and `import { GLView } from 'expo-gl'`.  I can't find any logs or errors anywhere.

**Comment by Laughlete** [comment]
I'm experiencing the same thing with `import { GLView } from 'expo-gl'` Crashes when the screen renders.

**Comment by Cwejman** [comment]
Can confirm, works correctly but crashes on JS debugging. 

Making a dev tools performance recording shows that the CPU goes to the roof when switching on JS debugging. All rasterise threads become occupied until crash. I've attached my performance recording file: [expo-gl-crash-on-chrome-debug.zip](https://github.com/expo/expo/files/3583887/expo-gl-crash-on-chrome-debug.zip)

Using expo 34.0.4, expo-gl 6.0.0 and yarn 1.5.1 on macOS 10.14.5's iOS simulator.

**Comment by Laughlete** [comment]
@Cwejman Without remote debugging on it wasn't crashing, but it also wasn't displaying.

I then tried displaying it elsewhere in my application and it worked.

It isn't working as a child of a stack navigator that's a child of a switch navigator. I don't know if this is expected, but couldn't find anything about this is the docs.

**Comment by Cwejman** [comment]
@Laughlete, I'm not sure I understand completely what you mean, also what version of the SDK are you referring to?

As @Asday states: the docs is or at least was not acknowledging the full truth of the problem (SDK32). I'd certainly appreciate some feedback from anyone with knowledge of the architecture of GLView and it's inherit issue. Before implementing a solution we'd have to understand in more depth why it's behaving this way.

When time presents it self I could research this further but expo doesn't have much of my unfortunately limited time. I have no more knowledge about this issue than you guys, perhaps we can find and ping someone with more in depth understanding...

**Comment by Cwejman** [comment]
Here's the commit to mention this issue in the docs: [Add info about GLView not working when debugging is enabled](https://github.com/expo/expo/commit/7499f9782f014650d242abaf5a4eb43c5c1fa4ae)

I'm shooting in the dark here but as you (@cruzach and @tsapeta) are responsible for this commit, could you possibly have some insight into this issue?

**Comment by chalarlie** [comment]
I'm seeing the exact same issue in SDK 35 in a Bare app. The app simply doesn't load when remote debugging is disabled, and will crash on the screen using GLView when it is enabled.

**Comment by brentvatne** [comment]
@Cwejman - if remote debugging is enabled it's not possible for glview to work because it depends on synchronous apis that aren't supported via chrome debugging. this has always been the cae for glview

@chalarlie - want to provide a minimal repro? @tsapeta can have a look

**Comment by Asday** [comment]
@brentvatne Please allow me to direct you, as I did Cwejman, to my comment:  https://github.com/expo/expo/issues/3773#issuecomment-531115131

**Comment by Asday** [comment]
I can confirm that `expo-three` is nothing to do with it in my case.  Trying to render a `<GLView />` at all, with remote debugging, now hard crashes the app, whereas it didn't in SDK32, (it was simply blank).

**Comment by reimertz** [comment]
I managed to get it to work if I build my app in `Release`-mode. 

When I run it in `Debug` mode, I can see a bunch of console.logs spewing out window.performance.. is not implemented and the CPU is running at 250%. Wonder if it could be related to that.  

If we can get Three to run in production mode, I think these issues might go away. Investigating...

**Comment by reimertz** [comment]
Yep, I managed to get it to work by adding `THREE.suppressExpoWarnings(true)`

Happy three.js-ing! <3

**Comment by chalarlie** [comment]
@reimertz How did you generate your project?

**Comment by chalarlie** [comment]
Actually @reimertz is there any chance you would mind uploading your repo where you got it to work?

**Comment by reimertz** [comment]
Hello there, I spent some time removing all the company-specific code and created a demo.

![demo](https://user-images.githubusercontent.com/625287/67285243-d4267b00-f4f4-11e9-9056-8bd69b68b648.png)

https://github.com/reimertz/expo-three-demo

**Comment by chalarlie** [comment]
You are a life saver!!! I'm not really sure what was much different from my project to yours other than I started with an Expo Bare project, but yours was clearly a conversion from a basic React Native project. I took that path and now everything seems to be working, which leads me to believe the issue is with the Expo package itself.

Thank you so much for providing that repo, @reimertz !

**Comment by Warmachine13** [comment]
I am having problems with your repo, @reimertz ! 
The same problem with glview

**Comment by mamahfouz66** [comment]
if you have 2 graphic adaptor installed disable one of them then run glview

**Comment by Asday** [comment]
> if you have 2 graphic adaptor installed disable one of them then run glview

I don't.

**Comment by Asday** [comment]
Bad bot.

**Comment by brentvatne** [comment]
@Asday - can you share a reproducible example? this works as expected in our tests

**Comment by Asday** [comment]
https://github.com/expo/expo/issues/3773#issuecomment-504395406

**Comment by brentvatne** [comment]
@Asday - i see the following when doing that:

<img width="487" alt="Screen Shot 2022-01-18 at 4 36 31 PM" src="https://user-images.githubusercontent.com/90494/150041368-169af504-61ac-4ba1-983c-6ea240e4fb06.png">

here's the repo: https://github.com/brentvatne/asday

this is expected behavior because you cannot use remote debugging in chrome with expo-gl - https://docs.expo.dev/versions/latest/sdk/gl-view/#remote-debugging--glview

you could try using it with hermes and then use the inspector to debug: https://docs.expo.dev/guides/using-hermes/#javascript-inspector-for-hermes

**Comment by Asday** [comment]
I still see this as a huge regression as it requires ANY users of a `GLView` component to wrap it in a HOC that checks for remote debugging and then doesn't render the child, compared to just, you know, _not crashing_ like it did in SDK32.

I'll begrudginly accept the closing of this issue because now at least it's not a CtD, and the error message shown explains the reason it's happening.  I haven't checked if it points to the actual component causing the issue, (again, the user has to know which one to conditionally disable, or run a manual binary search to find it), so how useful the error message is in practice is unknown to me, but mainly I've run out of motivation to care, having left Expo behind.  Should someone else follow in my footsteps in future, I wish them luck.
