### ISSUE TITLE
Expiring Distribution Certificate

### ISSUE THREAD

**Issue by jonsgreen** [expo/expo#3778]
I apologize for asking this question here but I am concerned I may not get an answer to my post in the forum in time. 

We are wondering if OTA updates will be affected by an
expiring distribution certificate and provisioning profile, which we
are in the process of regenerating.

Basically, once we have new certificate and provisioning profile, will
we still be able to do OTA updates on the existing release?

Or, if we don’t generate a new cert, at least if we don’t associate it with our provisioning profile, will we be able to do OTA updates on the current build that is associated with an expired cert?

Please let me know if there is a more effective way to get this sort of question answered elsewhere.

**Comment by AdamJNavarro** [comment]
Hey @jonsgreen,

Dist certs and provisioning profiles have no bearing on OTA updates. Sorry for not getting a timely response to you on our forums. I'm going to reply on your [post ](https://forums.expo.io/t/expiring-distribution-certificate/20621)as well so others can see.

Cheers,
Adam

**Comment by cruzach** [comment]
Answered your post in our forums 😃

That way we can keep Github for issues/bugs

**Comment by jonsgreen** [comment]
Thanks so much @cruzach and @AdamJNavarro
