### ISSUE TITLE
[expo-app-auth][android][home] Freshly built home is red-screening because of missing unimodule

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#3781]
Expo client's `Home` screen is not building on master throwing following red screen on Android.

![Screenshot_2019-03-19-15-51-37-854_host exp exponent](https://user-images.githubusercontent.com/16623003/54616170-9560ac00-4a5f-11e9-8b9b-e2cd26d65a5d.png)

**Comment by sjchmiela** [comment]
Fixed in https://github.com/expo/expo/pull/3780
