### ISSUE TITLE
App doesn't work after installation expo-av package

### ISSUE THREAD

**Issue by Hannibal2** [expo/expo#3782]
I just installed bare react-native app with expo-cli and install expo-av library (configure it of course), run it with react-native run-android, and it actually doesn't work. 

<img width="1093" alt="Screen Shot 2019-03-19 at 7 00 39 PM" src="https://user-images.githubusercontent.com/9866156/54626410-c51cad80-4a79-11e9-8776-e83cedee9c59.png">

Expo CLI 2.11.9 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      expo-cli: 2.11.9

my MainApplication.java

```
`package com.mytestapp;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import org.unimodules.adapters.react.ReactAdapterPackage;
import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;
import org.unimodules.core.interfaces.Package;
import org.unimodules.core.interfaces.SingletonModule;
import expo.modules.constants.ConstantsPackage;
import expo.modules.permissions.PermissionsPackage;
import expo.modules.filesystem.FileSystemPackage;
import expo.modules.av.AVPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(Arrays.<Package>asList(
     new ReactAdapterPackage(),
     new ConstantsPackage(),
     new PermissionsPackage(),
     new FileSystemPackage(),
     new AVPackage()
  ), Arrays.<SingletonModule>asList());

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ModuleRegistryAdapter(mModuleRegistryProvider)
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
`

```

**Comment by pserrer** [comment]
Have you tried `npm android` instead of `react-native run-android`? Adding expo-av to a new bare project works for me.

**Comment by cruzach** [comment]
Hey @Hannibal2 ,

Could you provide a demo of this? I know since it's a bare react native app, you can't give us a Snack, but even minimal steps you took to reproduce this issue helps troubleshooting on our end.

Thanks!
Charlie

**Comment by Hannibal2** [comment]
@pserrer neither of them worked. I created one more app after that and found another mistake
<img width="1135" alt="Screen Shot 2019-03-20 at 11 00 14 AM" src="https://user-images.githubusercontent.com/9866156/54672166-2f783100-4b00-11e9-8204-e5cf03321321.png">
I solved it by changing my build.gradle file(change only buildToolVersion to newer one and chage minSdkVersion to 28 instead of 21):
        buildToolsVersion = "28.0.3"
        minSdkVersion = 28

Hope it will be useful for someone.

**Comment by Hannibal2** [comment]
@cruzach Just empty bare react-native project created with expo-cli and installed and configured expo-av package

**Comment by Hannibal2** [comment]
I try to install react-native-video library and got the same error. It was connected with Exoplayer. After installation of this library we have to configure it by adding to settings.gradle next code:
`include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`

and after that app stops working and throw such error. 
 app will start if change  build.gradle file as I wrote above but player will be broken and not work

But if not use exoplayer and change it to it will be working
`include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android'`

**Comment by sjchmiela** [comment]
I was able to fix this issue by adding

```groovy
android {
  // ...

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  // ...
}
```

to `android/app/build.gradle`. Could you please try this workaround?

**Comment by Hannibal2** [comment]
@sjchmiela It solves the problem.

**Comment by Hannibal2** [comment]
Maybee I should find another place to ask this but, why my code doesn't work?

```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import { Video } from 'expo-av';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Video
          source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
        />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
```

**Comment by sjchmiela** [comment]
Glad to hear that!

Try adding some `style={{ width: 300, height: 300 }}` to your `Video` component. 🙂

**Comment by Hannibal2** [comment]
@sjchmiela thanks, it works. Found one bug - when I press fullscreen button the app crashes. Should I close this issue and open one moe for this bug?

**Comment by sjchmiela** [comment]
Yes, please!
