### ISSUE TITLE
IOS expo notification not working

### ISSUE THREAD

**Issue by juanmarlobo** [expo/expo#3784]
### Environment
From my windows:

  Expo CLI 2.11.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

From Mac
Expo CLI 2.11.9 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.11.9

This is an IOS and Android app, already published in both stores

1. I'm able to get the Expo Token, and store on my DB
2. I'm able to push notification from https://expo.io/dashboard/notifications and all android phones are receiving the notifications
3. I'm pushing notifications and I'm getting status OK
4- I'm checking the status of the IOS notification in https://exp.host/--/api/v2/push/getReceipts
And I'm getting: 

        "e0c4ffd4-a62b-4ae0-841c-194a75b7198d": {
            "status": "error",
            "message": "The Apple Push Notification service key for your account could not be loaded, likely due to a malformed p8 file. Expo needs a valid PEM key in order to deliver notifications to APNs.",
            "details": {
                "error": "InvalidCredentials",
                "sentAt": 1553015463
            },
            "__debug": {
                "internalError": "Failed to generate token: error:0906D06C:PEM routines:PEM_read_bio:no start line"
            }
        }

I let expo to create my certificates, and also I tried to clear the certs and it's still not working:'
expo build:ios --clear-push-cert

I'm getting crazy, i do not know what else to try.

Do you have any idea, what's happening here? and how to solve the issue?

Thanks

Juan

**Comment by cruzach** [comment]
Hey @juanmarlobo,

Have you already tried running `expo build:ios -c`? This will clear all credentials, rather than just the push notifications certificate.

Let me know if that helps!
Charlie

**Comment by juanmarlobo** [comment]
@cruzach thanks for your answer.

I did what you suggested, and i let expo to create all the certificates once again, and failed again ...

So, i did all the certificates p8 and p12 from scratch, and i clean all credentials, and I updaload my own certificates, and only it worked!
