### ISSUE TITLE
expoKit ejected app & fabric crashlytics & onCreate

### ISSUE THREAD

**Issue by ozanhonamlioglu** [expo/expo#3791]
hello guys,

I have an issue with installing fabric crashlytics on my expokit ejected app.
I have followed the docs https://fabric.io/kits/android/crashlytics/install step by step, and also installed react-native-fabric module, now my android studio and also my js codes are aware of the installed fabric and crashlytics packages. But only one things is missing which is I should add this ```       Fabric.with(this, new Crashlytics()); ``` into my onCreate method, but in my android ejected expokit project **there is no any onCreate() method** even if in any single java file.

I really need a help from you community. Thanks to everyone.

**Comment by cruzach** [comment]
Hey @ozanhonamlioglu,

You should be fine just adding the `onCreate` method to your `MainActivity` class.

Just be sure you include everything included in the `onCreate` method shown in the Crashlytics docs (basically copy/pasting their method should work, including the `@Override`)

Thanks for bringing this up!
Charlie
