### ISSUE TITLE
Update react-native-svg

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3795]
https://github.com/expo/expo/issues/3587

**Comment by maketroli** [comment]
Yes, please. I really need this update. I have to deliver an App on Monday and this is still a bug.

**Comment by webkreation** [comment]
I need this update urgently, too, but I'm not sure if it solves the problem.

I tried yarn resolutions with SDK32:
```
"resolutions": {
    "expo/react-native-svg": "9.3.6"
  }
```
but I got the same error.

Now i'm back to Expo SDK30 with with react-native-svg ^6.3.1 and all SVGs are processed correctly.

**Comment by christoph-hautzinger** [comment]
+1

**Comment by shirohana** [comment]
Tried `resolutions` didn't works since Expo was already built before install (˘̩̩̩ ω ˘̩ƪ)
