### ISSUE TITLE
Android emulator 'JavaScript heap out of memory'

### ISSUE THREAD

**Issue by osamaq** [expo/expo#3797]
## 🐛 Bug Report

`MaxListenersExceededWarning: Possible EventEmitter memory leak detected.`

`JavaScript heap out of memory`

To save your time, I can't really reproduce this bug, but only posting about it because I did some testing and know what to do when it happens.

My Nexus S (API 28, 9.0) emulator started to experience a memory leak related to NodeJs server with expo created projects. Whenever the app is reloaded, the NodeJs process memory usage increases. Eventually the NodeJs server crashes. It is related to my specific emulator which somehow has this bug and expo. I think so because:

1. The same emulator **does not** experience the memory leak with blank react-native-cli projects.
2. The same emulator **does** experience the memory leak with blank expo projects.

Here is a video where I manually reload a blank expo project repeatedly. 
It only shows until the first error message from metro bundler about a memory leak (1:30): https://streamable.com/e2yft

I can always reproduce this with the same emulator, but other emulators are fine. Physical devices are fine. Using a phyiscal device alongside the buggy emulator still results in the leak. 

### Environment

  Expo CLI 2.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

### Steps to Reproduce

Required: buggy emulator

1. `expo init myproject`

2. Choose `blank` and install with `yarn`

2. Start buggy emulator

3. `expo start --android`

4. Reload project and observe nodejs server process. Every reload will increase memory usage.

How can emulator get the bug? Unknown.

### Expected Behavior

Memory usage should stay around the same range.

### Actual Behavior

If I repeatdly reload the project metro bundler will soon report

`(node:12432) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit`

and eventually nodejs server crashes:

```
FATAL ERROR: I
neffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 00007FF7B1E5
F04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF7B1E3A0C6 node::MakeCallback+4518
 3: 00007FF7B1E3AA30 node_module_register+2032
 4: 00007FF7B20C20EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7B20C201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7B25E2BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF7B25D9C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF7B25D829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF7B25D7765 v8::internal::ScavengeJob::operator=+14869
10: 00007FF7B25E1064 v8::internal::Heap::MaxHeapGrowin
gFactor+2548
11: 00007FF7B219CBE8 v8::internal::Factory::AllocateRawArray+56
12: 00007FF7B219D562 v8::internal::Factory::NewFixedArrayWithFiller+66
13: 00007FF7B228F5A1 v8::internal::LookupIterator::Start<1>+12849
14: 00007FF7B228E091 v8::internal::LookupIterator::Start<1>+7457
15: 00007FF7B228E89E v8::internal::LookupIterator::Start<1>+9518
16: 00007FF7B228E072 v8::internal::LookupIterator::Start<1>+7426
17: 00007FF7B228E89E v8::internal::LookupIterator::Start<1>+9518
18: 00007FF7B228E072 v8::internal::LookupIterator::Start<1>+7426
19: 00007FF7B228F38C v8::internal::LookupIterator::Start<1>+12316
20: 00007FF7B228E091 v8::internal::LookupIterator::Start<1>+7457
21: 00007FF7B228E89E v8::internal::LookupIterator::Start<1>+9518
22: 00007FF7B228E072 v8::internal::LookupIterator::Start<1>+7426
23: 00007FF7B228D66B v8::internal::LookupIterator::Start<1>+4859
24: 00007FF7B20F0630 v8::internal::DeferredHandles::Iterate+1696
25: 00007FF7B2287F84 v8::internal::CodeStubAssembler::ConstexprBoolNot+38356
26: 00007FF7B2287EBB v8::internal::CodeStubAssembler::ConstexprBoolNot+38155
27: 00000342A3F5C721
```

### How did I come across the bug?

I was coding using with `Live Reload` enabled. Every ~30 minutes my nodejs server would crash with `JavaScript heap out of memory` due to the increase in memory usage with every app reload on save.

### How to alleviate?

Once the android emulator catches the bug, I don't know if the emulator can be fixed. Rebooting it does not fix it. Use a different emulator or create a new one. Creating the same device emulator with the same settings did not experience the leak.

**Comment by p-kolacz** [comment]
Got the same problem, physical Android device, `expo start`, Linux.

**Comment by atyrian** [comment]
Same problem, Android emulator using expo start, Windows 10

**Comment by lukmccall** [comment]
Hi everyone, could someone check if this bug still occurs in the newest expo-cli? 

I've tried to reproduce it and I wasn't able to do it 😕

**Comment by osamaq** [comment]
Hey. Wow, this is almost a year ago. I am glad to say I haven't experienced this issue again during my porjects. Please close it if you think it is not receiving enough attention 👍🏻

**Comment by z1haze** [comment]
Still running into this issue...
