### ISSUE TITLE
[docs] Testing with Jest

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3798]
We need a section on how to test your app with Jest.

**Comment by deefourple** [comment]
Seriously though, can't seem to find anything useful. 

I had set up a simple test:
```
import React from "react";

describe("App", () => {
    it("should pass", () => {
        expect(1).toBe(1);
    })
});
```

with a simple jest configuration inside my package.json:
```
  "jest": {
    "preset": "react-native"
  }
```
while using jest version 22.4.3

I couldn't even run the testing suite. Kept getting an error:
```
 /Users/{user}/pulse/pulse-mobile-app/node_modules/react-native/jest/setup.js:
babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.

    Invalid variable access: console

    Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, expect, jest, require, undefined, DTRACE_NET_SERVER_CONNECTION, DTRACE_NET_STREAM_END, DTRACE_HTTP_SERVER_REQUEST, DTRACE_HTTP_SERVER_RESPONSE, DTRACE_HTTP_CLIENT_REQUEST, DTRACE_HTTP_CLIENT_RESPONSE, global, process, Buffer, clearImmediate, clearInterval, clearTimeout, setImmediate, setInterval, setTimeout.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` are permitted.
```

This eventually led me to [this issue](https://github.com/facebook/react-native/issues/19120) which said using node 10> can cause issues. I'm using node v.10.15.1.

The only piece of advice that worked for me from that github issue is using ["jest": "23.0.0-charlie.1"](https://github.com/facebook/react-native/issues/19120#issuecomment-389377995).

As I kept reading the same user says that version 22.4.4 should work. It doesn't. Neither does upgrading it to the latest version of jest. Usually getting different unrelated errors that don't even let me run the test suites

It's very possible I need more in my jest config. But so far this process has been brittle and frustrating.

**Comment by brentvatne** [comment]
@deefourple - if you initialize an app with the tabs template from expo-cli you get a full setup jest environment, but you can also follow the guide on https://staging.docs.expo.io/versions/v32.0.0/guides/testing-with-jest/
