### ISSUE TITLE
Expose Constants.platform.version?

### ISSUE THREAD

**Issue by slorber** [expo/expo#3805]
Hi,

When dealing with an ejected/bare/ExpoKit app, we actually have somehow 2 version numbers to deal with: 
- js/manifest one (updatable OTA)
- native version (not updatable without a new native store submission)

I'd like to be able to show those 2 versions in my app (or through Sentry integration), to get better context about what the user is actually running. Currently it's easy to read the manifest.

We can also get some native infos with:

```jsx
export const AppNativeBuildVersion = Platform.select({
  ios: () => Constants.platform.ios.buildNumber,
  android: () => Constants.platform.android.versionCode,
})();
```

but we can't get the native version string. I think this should be included, for the exact same reasons as documented here:

![image](https://user-images.githubusercontent.com/749374/54752898-eac3c700-4bdf-11e9-8f8b-c804113b5b2d.png)

Also, it would be convenient to unify those under an unique "universal interface", like react-native-version-number do:

![image](https://user-images.githubusercontent.com/749374/54753008-41310580-4be0-11e9-99a3-e4a29738d387.png)

This would be helpful to avoid using a Platform.select() and could support web platform too.

**Comment by AdamJNavarro** [comment]
Hey @slorber,

This sounds reasonable to us. Let's just keep using this thread to track updates.

Cheers,
Adam

**Comment by sergeichestakov** [comment]
Hey @slorber,

I opened a PR addressing this issue. Feel free to take a look and let me know if that's in line with what you were referring to.

Thanks,
Sergei

**Comment by slorber** [comment]
thanks that looks great but don't know much about native dev so can't be so sure
