### ISSUE TITLE
Blank screen or Could not connect to server

### ISSUE THREAD

**Issue by ASAPHAANING** [expo/expo#381]
Ever since upgrading to Expo 18 I've experienced a lot of issues ranging from a necesarry npm downgrade to 3rd party libraries like kitten ui not working at all. The most fatal to my development is the blank screens however.

Going to my ip:19000 will return a JSON object in the browser but the phone will not sync. Either I get a blank screen or an error. In desperation I had to create a new project from SDK 18 template and starting porting the code. This worked, sort of, until today where I am now experiencing the same issues.

OS: Linux Ubuntu 16.04
Phone: iOS 10
Latest Expo client from the app store.
Server hosted using XDE, latest release.

**Comment by ASAPHAANING** [comment]
![img_0937](https://user-images.githubusercontent.com/6765179/28278181-7aae9ddc-6b1c-11e7-8542-c9b103a2f103.PNG)

**Comment by terribleben** [comment]
I don't think anything changed in SDK 18 related to how we connect to the server - that message is just the standard system network error for when it can't reach your project's URL.

Does it work if you switch to using a tunnel?

**Comment by ASAPHAANING** [comment]
It doesn't, no, weird thing is it works in a similar environment on my laptop. No idea how to debug./Frederik Haaning
          
            
            On jul 20 2017, at 1:09 am, Ben Roth <notifications@github.com> wrote:
            
            
              I don't think anything changed in SDK 18 related to how we connect to the server - that message is just the standard system network error for when it can't reach your project's URL.
Does it work if you switch to using a tunnel?

**Comment by terribleben** [comment]
If the same Expo setup is working on one of your computers but not the other, I'd investigate any network settings which might be preventing connections to that port, or to locally hosted services in general.

**Comment by ASAPHAANING** [comment]
Oh, no, this is persistant on any network I've tried including mobile hotspots.
It also persists through OS'.

Also, sometimes the issue is there sometimes it isnt I haven't been able to find a pattern.

**Comment by terribleben** [comment]
Ok. It's going to be hard to track down without a pattern of any kind. Let me know if you pin it down to something more specific.

**Comment by ASAPHAANING** [comment]
News in this matter, for 2 days and probably ~10 independent exp CLI server sessions it has worked consistently without errors. What I did was apply sudo to the command:

**Full command used for a working session:**
`sudo exp start -c `

Also thank you for the interest in this issue.

**Comment by terribleben** [comment]
Ok, I guess it's possible the packager server wasn't running in the earlier circumstances (resulting in the "could not connect to sever" message). Glad you found a solution.
