### ISSUE TITLE
Expo bar code reader not picking data up

### ISSUE THREAD

**Issue by AlexMachin1997** [expo/expo#3811]
Hi,

I'm an issue setting up the barcode scanner in a bare-minimum expo application.

I've installed the barcode reader and expo-permissions, after installing and configuring them I imported them like this:

```
import { BarCodeScanner } from 'expo-barcode-scanner';
import * as Permissions from 'expo-permissions';

```

But when I try the [barcode reader stack](https://snack.expo.io/Skxzn6-5b) it shows TypeError: TypeError: undefined is not a function (evaluting this.requestCameraPermission())

I'm not exactly sure how to set up the barcode reader in a bare-minimum workflow, it would be great if someone could give a hand with this issue.

Github Gist: https://gist.github.com/AlexMachin1997/77e0cc993b818796456e94ead329872e

**Comment by AlexMachin1997** [comment]
UPDATE: Ok I figure the problem I was referencing the method wrong, however now it's not asking for permissions at all.

**Comment by AlexMachin1997** [comment]
Cleared the cache, rebuilt the project it now works woooh!!!

**Comment by AlexMachin1997** [comment]
The barcode reader isn't picking data up.

**Comment by brentvatne** [comment]
the function has been renamed to `onBarCodeScanned`, when using these pkgs its best to refer to the "Documentation for the master branch" - perhaps i should rename this to make it more clear

**Comment by AlexMachin1997** [comment]
@brentvatne No it's fine, when I was adding this it was late at night and I couldn't find the docs. I was mostly following an old expo snack I think. It's fine as it is, I found it straight away today.

I do have one last question, how would I prevent continuous scans? would I just check if the data exists if its true just return or something like that.
