### ISSUE TITLE
Expo generated apk [Android] keeps reloading but everything in the expo app works fine

### ISSUE THREAD

**Issue by sseoussama** [expo/expo#3813]
After installing the generated apk into my phone, the application keeps reloading randomly.

After running expo diagnostics.

OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
      npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.11.9

**Comment by brentvatne** [comment]
turn production mode on in expo-cli (https://docs.expo.io/versions/v32.0.0/workflow/development-mode/) and try again there, you will likely see the error that you're looking for

**Comment by sseoussama** [comment]
thanks and it helped, It was a problem with my react navigation.

**Comment by brentvatne** [comment]
any ideas how we can make it more clear how to do this in documentation?

**Comment by sseoussama** [comment]
Are you talking about the development mode or what ?

**Comment by brentvatne** [comment]
yeah, how to make it more clear that you can test out the production js build of your app locally
