### ISSUE TITLE
[docs] Some links throw errors.

### ISSUE THREAD

**Issue by rauldeheer** [expo/expo#3816]
A lot of URL's in the documentation throw a error. You can for example go to [this page.](https://docs.expo.io/versions/latest/sdk/)

I'm not sure why, but I've already found a few. I was able to fix a few of them in a PR #3815, but I guess there are many more throughout the site.

**Comment by brentvatne** [comment]
thanks for the prs. i don't think that there are many more, we have a script that runs automatically before deploying docs to check for broken links. cc @nicknovitski re: pr #3815 links being missed
