### ISSUE TITLE
Cryptic Error Message for Push Notification

### ISSUE THREAD

**Issue by michaelgiba** [expo/expo#382]
Hello!

I have followed the guide for allowing for push notifications on IOS devices. I am testing from a physical device, I have set the necessary settings on the developer portal, but whenever I try to invoke the HTTP API for dispatching push notifications I recieve the following error:

```
>>> r.post(host, data={"to":"ExponentPushToken[T-9nIkDTD1a5YMhLbc5K7b]","body":"test"}).text
u'{"data":{"status":"error","message":"There was an unexpected error delivering the notification."}}'
```

I have no idea what to do to try to fix this. Is this a bug?

Please help!

Thanks,
Michael

**Comment by brentvatne** [comment]
@ide is looking into this and will get back to you shortly

**Comment by michaelgiba** [comment]
cool thank you

**Comment by ide** [comment]
It looks like you're trying to send push notifications for a standalone app and we're not able to find the Apple push notification credentials we need for your app. Is this an app that you detached, or did you build it with `exp build:ios`?

**Comment by michaelgiba** [comment]
I needed to link a couple of binary libraries so I detached, built
standalone in Xcode and I'm serving my bundle using Expo. How do I go about
setting the credentials?

**Comment by ide** [comment]
The credentials get set when you build a standalone app with `exp build:ios`. We currently don't support sending push notifications with detached apps: https://docs.expo.io/versions/v18.0.0/guides/detach.html#you-require-expos-push-notification-services-after-detaching-since-expo-no-longer-manages-your-push-certificates-youll-need-to-manage-your-own-push-notification-pipeline

We'll look into providing an actually helpful error message for now since we don't have a great way to support push notifications for detached apps but you'll have to use another push provider.

**Comment by ide** [comment]
Small update: We've made the error message a lot clearer on the server side, which should make it less confusing as to why things aren't working.

**Comment by michaelgiba** [comment]
Great. We can close this ticket in that case

**Comment by chuyee** [comment]
I had the exact same problem as @andremellow. Push notification works with Expo app. But standalone IPA (with ad-hoc profile) doesn't. My app is not rejected. I created it with `create-react-native-app`. Build it with `exp build:ios` and provide the correct certificates and provision files.

BTW, the standalone Android version of the exact same App (w/ `exp build:android`) works fine for push notifications.

@ide, please help to take a look. My pushToken is t6VsAXGlZVF13CHhs07vhx. I've tried `rm -rf node_modules && npm install`. Doesn't help.

**Comment by ide** [comment]
@chuyee We don't have support for ad hoc profiles. I suspect that is the problem. An App Store build is the solution for this.

@andremellow Could you please write into support@expo.io with the Expo push token you're having issues with?

**Comment by chuyee** [comment]
@ide Thanks for the reply. I understand `exp build:ios` doesn't support Ad Hoc profile if I choose to let "Expo handles all credentials, ...". So I choose to provide all the credentials myself.

I managed to get it work just now. Long story short, I think something is wrong with my various Apple certificates and provision files. I deleted all my App Store production and Push Notification (both development and production) certificates, App ID and distribution provisioning profiles and regenerate them. Now the Ad Hoc profile works fine on my fleet iDevices.

**Comment by ide** [comment]
OK, thanks for the update. Glad to hear you figured out a way to resolve your issue. I'm going to lock this topic since it is more often easier for the Expo team and community members to respond to new threads rather than existing ones that have similar symptoms but different causes.
