### ISSUE TITLE
FileSystem downloadAsync no message given when target directory does not exist

### ISSUE THREAD

**Issue by wende60** [expo/expo#3820]
it is about FileSystem.downloadAsync(uri, fileUri, options) in https://docs.expo.io/versions/latest/sdk/filesystem/
In the doc there is no info that a path like FileSystem.documentDirectory + '**myDir**/' + 'myFile.jpg' **must exist**. If '**myDir**' does not exist, even in a try-catch-block no error or status will be given, just nothing. Makes development frustrating...

```
        try {
            const fileData = await FileSystem.downloadAsync(
                'http://www.mygallery.com/myDir/myFile.jpg',
                FileSystem.documentDirectory + 'myDir/myFile.jpg'
            );
            console.info("fileData", fileData)
        } catch (e) {
            console.info("ERROR", e);
        }
```
No output at all here...

**Comment by brentvatne** [comment]
which platform does this happen for you on? ios or android? which sdk version? managed or bare workflow?

**Comment by wende60** [comment]
Expo CLI 2.13.0 environment info:
System:
OS: macOS High Sierra 10.13.6
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 11.12.0 - /usr/local/bin/node
npm: 6.7.0 - /usr/local/bin/npm
IDEs:
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
expo: ^32.0.0 => 32.0.6
react: 16.5.0 => 16.5.0
react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
npmGlobalPackages:
expo-cli: 2.13.0

developing on a Huawei P10 via Expo App, Android 8.0. Expo has permission to read/write in storage.
