### ISSUE TITLE
makeDirectoryAsync creates error although directories were created properly

### ISSUE THREAD

**Issue by wende60** [expo/expo#3823]
## 🐛 Bug Report

First of all i found different discussions about this bug, **but all were closed**. But it is still alive, and it is frustrating for any developer while diving into Expo: makeDirectoryAsync creates an error, however the directories are created.

### Environment
  Expo CLI 2.13.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.13.0

developing on a **Huawei P10** via Expo App, **Android 8.0**. Expo has permission to read/write in storage.

### Steps to Reproduce

- execute makeDirectoryAsync to create directories like 'foo/bar'. 
- check succes with readDirecoryAsync by reading 'foo'

### Expected Behavior
checking 'foo' via readDirecoryAsync should be like:
DIR Array [ 
    "bar"
 ]

### Actual Behavior
this will result in an error like

ERROR [Error: Directory 'file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540anonymous%252Fhiker-87e39a6d-864b-4d3d-b56a-83f7b51cccd2/foo/bar' could not be created.]

In fact thats nonsens because the directories were created as a check via readDirecoryAsync of 'foo' shows

### Reproducible Demo
Try out that snippet
```
        try {
            await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'foo/bar', { intermediates: true });
        } catch (e) {
            console.info("ERROR", e);
        }
        try {
            const isDir = await FileSystem.readDirectoryAsync(FileSystem.documentDirectory + 'foo');
            console.info("DIR", isDir);
        } catch (e) {
            console.info("ERROR", e);
        }
```
Both outputs are there: the error and the expected success 'DIR'.

**Comment by sjchmiela** [comment]
Are you sure the error doesn't say that the directory already exists? I remember `makeDirectoryAsync` throwing an error in such case, similarly to what `mkdir` does without `-p` flag. 🤔 Try logging `JSON.stringify(e)` or `console.error(e)` and see if those views let you inspect the error better. 🙂

**Comment by wende60** [comment]
That's why i am doing it like this:
```
        const metaDataDir = await FileSystem.getInfoAsync(FileSystem.documentDirectory + imgDir);
        const isDir = metaDataDir.isDirectory;
        if (!isDir) {
            try {
                await FileSystem.makeDirectoryAsync(
                    FileSystem.documentDirectory + imgDir,
                    { intermediates: true }
                );
            } catch (e) {
                console.info("ERROR", e);
            }
        }
```
regards, jo

**Comment by wende60** [comment]
thanks folks, much appreciated :)

**Comment by sergeichestakov** [comment]
No problem, happy to help :)
