### ISSUE TITLE
[docs] Add guide on uploading files and images

### ISSUE THREAD

**Issue by ide** [expo/expo#3824]
This is a common use case that is not well-documented. We want to accommodate a wide variety of servers, so rather than writing a guide for a specific service, we want to cover the most common HTTP/web upload protocols.

We want to explain how to upload a file with the contents of the file in the HTTP request body and how to specify the content type of the file.

We also want to explain how to do multipart form uploads, where the content type of the request is a multipart form request and the body is a form with potentially multiple files, each with their own content type.

And of course, we want the guide to apply to all platforms.

**Comment by brentvatne** [comment]
yesss

**Comment by eragon512** [comment]
hi, I'd like to take up this issue, if its available for first-time contributors

**Comment by eragon512** [comment]
could you please elaborate on how this is implemented right now? also, is there any existing documentation that needs to be extended or does it need to be written from scratch?
