### ISSUE TITLE
asset.downloadAsync is not a function

### ISSUE THREAD

**Issue by serranoarevalo** [expo/expo#383]
Hey guys! First of all thanks for the amazing work you've done.

I'm using the [new project template](https://github.com/expo/new-project-template/blob/master/App.js) and I'm getting an error that says `TypeError: asset.downloadAsync is not a function. (In 'asset.downloadAsync()', 'asset.downloadAsync' is undefined)`

Am I doing something wrong?

Cheers!!

**Comment by ide** [comment]
Did you set up the new project using XDE or `exp init` and are you using the latest version of the Expo client?

**Comment by brentvatne** [comment]
hello! the latest version of new-project-template on Github will only work with the latest SDK. you need to use the template provided by `exp init` or in XDE to be sure that it'll work with the currently released version.

**Comment by serranoarevalo** [comment]
I set it up using the XDE @ide. Where can I find this template @brentvatne ? 

Thanks for your time guys!

**Comment by terribleben** [comment]
Brent just means you need to use the "New Project" button in XDE, rather than manually cloning the template repo you previously linked to. Does that solve your problem?

**Comment by serranoarevalo** [comment]
@terribleben I didn't actually cloned the repo I just copy pasted the code that is doing the font caching and pasted it into my XDE generated project.

**Comment by serranoarevalo** [comment]
Updated to 19, works now. Closing this.
