### ISSUE TITLE
[web] expo-barcode-scanner support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#3834]
Add support for Barcode scanning in the browser.

https://wicg.github.io/shape-detection-api/#barcode-detection-api

- #4166

**Comment by DavideMichelotti** [comment]
Does it take a long time to be completely supported for the web?

**Comment by EvanBacon** [comment]
Completed a small subset of this feature, you can will be able to perform QR scanning via `expo-camera` on web https://expo-web-9630.now.sh/components/qrcode. Closing. When the web spec is complete we can look at support for more things using native platform APIs.
