### ISSUE TITLE
Expo-Google-Sign-In Returns Blank Web Page

### ISSUE THREAD

**Issue by novuw** [expo/expo#3839]
### Environment

Expo CLI 2.13.0 environment info:
  System:
    OS: Windows 10
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

### Steps to Reproduce

To reproduce this error, simply use the following two lines in any ios standalone expo app for google login:
            await GoogleSignIn.initAsync({ clientId: 'xxxxxxxxxxx'});
            const result = await GoogleSignIn.signInAsync();

### Expected Behavior

I want my project to sign in, so I can pass the result variable to firebase to login through Google. 

### Actual Behavior
Essentially, the behavior now opens up a blank screen that changes color on reloading. It is shown here:
https://ibb.co/QMdhzb7
https://ibb.co/Nny4jd8

### Reproducible Demo
I don't know if I should make a SA demo. Should I? Let me know!

Another user said (@sjchmiela ):
On a side note, similar thing was happening in expo-sharing module when we didn't hold a strong reference to UIDocumentInteractionController (the URL would become blank and nothing would be shared), maybe we should do something like this here too?

Thank you!

**Comment by ChlorUpload** [comment]
I have the same problem.
