### ISSUE TITLE
Please provide The Expo android apk download link.

### ISSUE THREAD

**Issue by es6rn** [expo/expo#384]
At https://expo.io/, only provide Google play address to download the Expo apk.
But many developer in China can not visit Google play.
Please provide a download link which can download the Expo apk directly.

**Comment by es6rn** [comment]
BTW, I download the source and try build it with my windows 10 PC, and failed......

**Comment by ide** [comment]
There's a link to our APK at the bottom of this page here: https://expo.io/tools

**Comment by duguying** [comment]
my device could not reach android app store, could you please provide The Expo android apk download link.

**Comment by ide** [comment]
The current link is here https://d1ahtucjixef4r.cloudfront.net/Exponent-2.0.0.apk. That link is from https://expo.io/tools. Please be aware that we only keep that page up to date.

**Comment by nishadpnktdi** [comment]
https://m.apkpure.com/expo/host.exp.exponent

**Comment by qianggetaba** [comment]
open the link [https://expo.io/tools](https://expo.io/tools), use ctrl +f find "apk" or in the page source code
