### ISSUE TITLE
Assets and OTA updates

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3840]
Currently, if a developer wants an image to load immediately as if it were bundled in the binary, they need to add something like `Asset.fromModule(require('./whatever.png')).downloadAsync()` to the app somewhere in order to cache the asset manually. This is not so clear from the documentation currently. We can go further than this though, and we should probably improve the OTA update tooling so that developers are able to not just download and cache the new JS bundle, but also the assets associated with that bundle.

**Comment by ide** [comment]
Treating updates atomically is a part of Eric's Updates work (along with other characteristics like isolation and durability), which will handle this.

**Comment by brentvatne** [comment]
not relevant now that assets are downloaded atomically with update js
