### ISSUE TITLE
Babel-module-resolver plugin not working when upgrading from SDK 30 to 31/32

### ISSUE THREAD

**Issue by alaboudi** [expo/expo#3849]
### Environment

Expo CLI 2.13.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.8 => 3.3.2 
    npmGlobalPackages:
      expo-cli: 2.13.0

### Steps to Reproduce
I tried to upgrade my project from expo SDK 30 to SDK 32 but it now doesn't run because the babel-module-resolver plugin is no longer supported for some reason. Below is my current `.babelrc` file

```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        [
          "module-resolver",
          {
            "alias": {
              "@app": "./src"
            }
          }
        ]
      ]
    }
  }
}
```

I have updated my expo, react, and react-native to the versions listed above. I have also ensured to delete the `node_modules` folder and re-install all the dependencies. It doesn't seem to work with my current `.babelrc` file. I am aware that there are some breaking changes with an upgrade from SDK 30 but I am not sure what to do from here.

I get an error message saying `cannot load "<SomeScreen>" from "<SomeOtherScreen>"`. This just means that the module-resolver is not kicking in. Any ideas?

**Comment by cruzach** [comment]
Hey @alaboudi 

Have you read through the [SDK 31.0.0](https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49) release notes? This update brought us to Babel 7, and in those release notes you can read:

> If you use a custom babel configuration, you’ll need to update it to support Babel 7. Additionally, if you depend on babel-preset-expo, you’ll need to install version 5.0.0 or later.

Let me know if this helps,
Charlie

**Comment by alaboudi** [comment]
Hey @cruzach ,

Thanks for writing back. I have read the release notes and I think you are right. It seems to be related to the Babel upgrade. I think I am struggling to understand the changes I need to do to my `.babelrc`. Do you mind sharing your opinion on what should be done differently to accommodate Babel 7?

On a side note, I don't think I'd have to upgrade or install `babel-preset-expo` since its implicitly part of expo's dependency. Correct me if I am wrong about that.

**Comment by brentvatne** [comment]
@alaboudi - it should look like this: https://github.com/brentvatne/hackernews-react-native-apollo/blob/master/babel.config.js

then install the latest version of module resolver and add it to this config. if you need help with babel config properties check out https://babeljs.io/docs/en/config-files#project-wide-configuration
