### ISSUE TITLE
Improve documentation around Keyboard and StatusBar

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#385]
- StatusBar on Android needs to be opaque to use adjustResize
- Overall lots of confusion around how to do this well
- It probably belongs in React Native docs but somewhat in Expo too wherever it is specific to Expo

**Comment by cruzach** [comment]
Closing this bc stale, we've got a few docs on this now:
- https://docs.expo.io/versions/latest/guides/configuring-statusbar/
- https://docs.expo.io/versions/latest/react-native/statusbar/

**Comment by brentvatne** [comment]
we probably still need this but let's leave this issue closed for now because we need to rethink a lot of the docs structure
