### ISSUE TITLE
expo-image-picker does not work in bare react-native apps

### ISSUE THREAD

**Issue by faustoct** [expo/expo#3851]
### Environment
````
  Expo CLI 2.11.6 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
      react-navigation: ^3.3.2 => 3.3.2 
    npmGlobalPackages:
      expo-cli: 2.11.6
````

### Steps to Reproduce

`yarn add expo-image-picker`

### Expected Behavior

````
gradle added to the android project
build successfully 
````

### Actual Behavior

````
expo-image-picker not added to android project
build fails

/Users/fausto/Projects/coding/viby-frontend/android/app/src/main/java/com/linked4/app/social/MainApplication.java:29: error: package expo.modules.imagepicker does not exist
import expo.modules.imagepicker.ImagePickerPackage;
                               ^
/Users/fausto/Projects/coding/viby-frontend/android/app/src/main/java/com/linked4/app/social/MainApplication.java:43: error: cannot find symbol
     new ImagePickerPackage()
         ^
  symbol:   class ImagePickerPackage
  location: class MainApplication

````

**Comment by cruzach** [comment]
Hi @faustoct , 

Is this just with Android, or does it also occur on iOS?

Thanks,
Charlie

**Comment by faustoct** [comment]
@cruzach android only

**Comment by cruzach** [comment]
We tested on our end and seems to be working fine, [here](https://github.com/brentvatne/testing-pickers) is the repo.

I would make sure you're [installing](https://github.com/expo/expo/tree/master/packages/expo-image-picker#installation) the module correctly.

**Comment by faustoct** [comment]
@cruzach yes I installed correctly. Also I have many expo modules . Only this one is not working here.

**Comment by brentvatne** [comment]
@faustoct - please look at the repo that @cruzach shared, and feel free to clone and run it if you like in order to verify that it works. inspect the code there and compare to yours to see what is wrong

**Comment by faustoct** [comment]
<img width="263" alt="Screen Shot 2019-03-26 at 18 39 11" src="https://user-images.githubusercontent.com/3135444/55035421-b3e21c80-4ff6-11e9-8f4c-e98b96691aa7.png">
As you can see I don't have `expo-image-picker` added to gradles

**Comment by brentvatne** [comment]
are you using the `react-native-unimodules` package? which version? which version of expo-image-picker?

**Comment by faustoct** [comment]
`resolved "https://registry.yarnpkg.com/@unimodules/core/-/core-0.2.0.tgz#86a37f01fb4adaa00dad5fab5a03d8549ac24e0c"`
`expo-image-picker@^4.0.0:
  resolved "https://registry.yarnpkg.com/expo-image-picker/-/expo-image-picker-4.0.0.tgz#42bbf2d4691559e533eb5425408bb995e7b5cb0c"`

**Comment by faustoct** [comment]
Fixed it. I had re-run `expo init --template bare-minimum` . Something changed to the new version and image-picker only worked with current version. I'm very unware on version changes. I don't know, each module works, each doesn't.
