### ISSUE TITLE
Expo crash after <Camera> mounts (sometimes) [iOS]

### ISSUE THREAD

**Issue by MickaelBergem** [expo/expo#3852]
### Environment

Diagnostics:

```
  Expo CLI 2.11.6 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/local/opt/node@8/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.7 => 4.1.11
      expo: ^32.0.6 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.2.tar.gz => 0.57.1
      react-navigation: ^3.5.1 => 3.5.1
```

App target: iOS app for iPad, not ejected. Issue reproducible with the IPA file and with the Expo client, as well as in the simulator.

I have local stacktraces generated from my actual application, let me know if you need them.

### Steps to Reproduce

I have an app using react-navigation and the Camera component. When opening the app and pressing a button, we navigate to a second screen with more or less the Camera example from the docs. It works fine - I am scanning a QR code. When going back (camera screen unmounts) and on this screen again a couple times, the app will crash entirely (Expo closes). This sometimes happen on the first mount as well.

The error message is the following:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureSession addOutput:] Cannot add output <AVCaptureMetadataOutput: 0x28225f6c0> to capture session <AVCaptureSession: 0x2820f40c0 [AVCaptureSessionPresetHigh]> because more than one output of the same type is unsupported'
```

### Expected Behavior

The app never crashes ;)

### Actual Behavior

Random crash when trying to actually mount the <Camera> element.

### Reproducible Demo

I was able to reproduce the issue on a fresh base: https://github.com/MickaelBergem/bug-repro-camera-crash. I usually need to repeat the unmount/mount cycle by navigating back and forth at least 10 times before the app crashes.

**Comment by cruzach** [comment]
Hi @MickaelBergem ,

I've tried a couple times to reproduce this issue, but even after navigating back/forth ~20 times, I'm not having this error pop up.

All you're doing is navigating back and forth, and it results in this issue? Are you testing this on an iPad or an iPhone?

Thanks,
Charlie

**Comment by MickaelBergem** [comment]
Hello @cruzach , I was able to reproduce this on an iPad Pro running iOS 12.1.4.

I am also able to reproduce on the simulator (iPhone): 
![image](https://user-images.githubusercontent.com/3510190/55099543-1d0c7300-507d-11e9-9ec5-8ab4722e2e29.png).

Can you reproduce the issue in the simulator? On what device did you test?

I just updated the repro repo to automatically redirect so that the app will cycle without any user interaction - until it crashes.

**Comment by cruzach** [comment]
Okay, was able to reproduce. Had to let it cycle for a while but eventually I got the same error output as you did.

**Comment by evankwok** [comment]
Thanks for opening a ticket on this issue! 
@bbarthec I understand this could be a complex issue, I was wondering if you have a rough estimation/timeline for when this could be fixed?

**Comment by NathanBeesley** [comment]
I have been trying to figure out this bug for a while now. I experience this issue on iOS 12.1+. I was passing barCodeScannerSettings something like { barCodeTypes:[BarCodeScanner.Constants.BarCodeType.code39, BarCodeScanner.Constants.BarCodeType.code39mod43] }}. I event tried like this { barCodeTypes: [] }}. I still experienced the crash. I found to resolve my issue(temporiarly) was to remove prop barCodeScannerSettings altogether. Haven't experienced it yet.

**Comment by NathanBeesley** [comment]
I have been trying to figure out a similar bug for a while. Expo/App Store app was crashing with no stack trace. I was experiencing this on iOS 12.1+. I was passing barCodeScannerSettings something like { barCodeTypes: [BarCodeScanner.Constants.BarCodeType.code39, BarCodeScanner.Constants.BarCodeType.code39mod43] }}. I even tried  { barCodeTypes: [] }}. I still experienced the crash. I found to resolve my issue(temporiarly) was to remove prop barCodeScannerSettings altogether. Haven't experienced it again. Hope this helps!

**Comment by MickaelBergem** [comment]
@NathanBeesley you just saved my day!! Thanks a lot.

I just tested it on the reproduction case, and it's no longer crashing. I confirm this workaround works.

**Comment by OscarYuen** [comment]
@NathanBeesley @cruzach  I also found that when barCodeTypes is given to Camera component, when you keep navigating back and forth or directly facing the barcode after mounting the Camera component, the onBarCodeScanned callback would not be called.

After I switch to BarCodeScanner, it resumes normal.

**Comment by JaapWeijland** [comment]
I had an issue with the BarCodeScanner taking like 5 seconds to initialize, freezing my whole app. Removing `barCodeTypes={[BarCodeScanner.Constants.BarCodeType.qr]}` seems to have fixed the issue.

**Comment by FinnFrotscher** [comment]
same issue, without having set any barcode props
