### ISSUE TITLE
could not be moved/copy file,in iOS

### ISSUE THREAD

**Issue by shouhuori** [expo/expo#3853]
error code:
```[Unhandled promise rejection: Error: File 'file:///Users/zhichou/Library/Developer/CoreSimulator/Devices/0157685B-B45C-486A-8F60-F2C6B21605F8/data/Containers/Data/Application/87264EE6-C2CD-4156-A294-E75C2D098698/Library/Caches/ExponentExperienceData/%2540anonymous%252Fmeet-more-1be9fa1c-a607-4dc4-9ff1-b2a67b1cc4dc/ImageManipulator/10145D30-8A11-4DBC-9C04-B331803A0B95.png' could not be moved to 'file:///Users/zhichou/Library/Developer/CoreSimulator/Devices/0157685B-B45C-486A-8F60-F2C6B21605F8/data/Containers/Data/Application/87264EE6-C2CD-4156-A294-E75C2D098698/Documents/ExponentExperienceData/%2540anonymous%252Fmeet-more-1be9fa1c-a607-4dc4-9ff1-b2a67b1cc4dc/image/1553671143859.png'.]```
but in Android is fine.

**Comment by somechild** [comment]
How did you solve this?

**Comment by somechild** [comment]
> How did you solve this?

For others who had a similar issue: I fixed this by initializing the subdirectory I was copying to using `FileSystem.makeDirectoryAsync`
