### ISSUE TITLE
getting build error after upgrading react native version 0.58.6 t0 0.59.0

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#3854]
Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints: 
        Dependency path 'host.exp.exponent:expo-react-native-adapter:3.0.0' --> 'host.exp.exponent:expo-image-loader-interface:3.0.0' --> 'com.android.support:support-annotations:27.1.1'

looks something wrong with expo-react-native-adaptor

** I also Tried adding** 
    implementation 'com.android.support:support-annotations:28.0.0'
to build.gradle

**Comment by raajnadar** [comment]
Use react native fork by expo.

https://github.com/expo/react-native

**Comment by shubhamdeol** [comment]
@raajnadar  I am not using expo sdk as whole, I am just using there universal modules with bare react native setup

**Comment by cruzach** [comment]
Hey @shubhamdeol ,

Please follow the issue template, as it contains a lot of the info we need to help you as best as we can

Specifically, including a way for us to reproduce the event on our end makes solving the issue much easier.

Thanks, I'll open this back up after we get the details necessary
Charlie

**Comment by brentvatne** [comment]
heya @shubhamdeol - we renamed this package and some other related ones recently, you should follow the instructions on https://github.com/unimodules/react-native-unimodules for how to get unimodules running in your project
