### ISSUE TITLE
WebBrowser not supported for expo web

### ISSUE THREAD

**Issue by AlexGrafe** [expo/expo#3855]
### Environment

web

### Steps to Reproduce

```
let result = await WebBrowser.openBrowserAsync('https://expo.io');
```

### Expected Behavior

Should open a new window or provide an iframe potentially.

### Actual Behavior

Throws error:
`Unhandled Rejection (Error): The method or property WebBrowser.openBrowserAsync is not available on web, are you sure you've linked all the native dependencies properly?`

### Reproducible Demo

Cannot share demo since it's web. But simply invoke above code on web-enabled project.

**Comment by cruzach** [comment]
Hey @AlexGrafe,

WebBrowser is not supported **yet**. You can see all of the currently supported modules [here](https://github.com/expo/web-examples/blob/master/docs/FEATURES.md). Feel free to read all about Expo's [release of experimental Web Support](https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375).

Thanks!
Charlie

**Comment by AlexGrafe** [comment]
Thanks @cruzach. Didn't see this page before but am using it. Full steam ahead :) !

**Comment by AlexGrafe** [comment]
One more question: Is there _any_ way to open a new browser window through expo then?

**Comment by brentvatne** [comment]
`window.open('url');` https://www.w3schools.com/jsref/met_win_open.asp
