### ISSUE TITLE
Expo Contacts getContactsAsync returns empty array on Android 7.0

### ISSUE THREAD

**Issue by FabioConsonni** [expo/expo#386]
OS version: Android 7.0
Expo version: 18

On Android 7.0 the following code return empty Array

```
const permission = await Expo.Permissions.askAsync(Expo.Permissions.CONTACTS);
if (permission.status !== 'granted') { return; }

const { pageSize, pageOffset } = this.state;

this.setState({ loading: true });

      const contacts = await Expo.Contacts.getContactsAsync({
        fields: [
          Expo.Contacts.PHONE_NUMBERS
        ],
        pageSize,
        pageOffset,
      });

      console.log(contacts.data);
```

On Android 6 it works, slow but it works.

Tks, Fabio.

**Comment by dikaiosune** [comment]
Hi! What happens if you don't specify pageSize and pageOffset? Does it still return empty?

**Comment by jesseruder** [comment]
Hi! We've made some changes to the Contacts api that should resolve this. Thanks for the report!

**Comment by heresmyinfo** [comment]
@jesseruder I'm still running into really long read times for Android with getContactsAsync - do the changes you mentioned address this? Thanks!

**Comment by IElgohary** [comment]
I still have this issue
