### ISSUE TITLE
ImageManipulator manipulateAsync Crop is not working on Android SDK 32.0.0

### ISSUE THREAD

**Issue by johnnietirado** [expo/expo#3862]
## 🐛 Bug Report

`ImageManipulator.manipulateAsync` passing Crop function with valid parameter is throwing error: `"Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image."`

### Environment

```
  Expo CLI 2.10.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Users\tirad\AppData\Roaming\npm\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
```

Targeting Android on Expo App
Current Issue found running on a Samsung S8+ and Samsung J2 Prime

### Steps to Reproduce

Take picture using the following Snack:

https://snack.expo.io/@johnnietirado/android-crop-camera-issue

1. Click Camera Button, accept use of Camera.
2. Click Button at bottom of screen.
3. Original Image will be shown but not cropped correctly.

### Expected Behavior

Image should be cropped correctly like a card. About a third of the height of the image and grabbing the center third.

### Actual Behavior

Image is not cropped and error is thrown

`Error: "Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image." in h@/data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40johnnietirado%2Fandroid-crop-camera-issue281302753-32.0.0:38:1566 << /data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40johnnietirado%2Fandroid-crop-camera-issue281302753-32.0.0:38:960 << value@/data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40johnnietirado%2Fandroid-crop-camera-issue281302753-32.0.0:46:3650 << /data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40johnnietirado%2Fandroid-crop-camera-issue281302753-32.0.0:46:1155 ...`

### Reproducible Demo

https://snack.expo.io/@johnnietirado/android-crop-camera-issue

### Notes

I found where the error is being throw in the code:
[File](https://github.com/expo/expo/blob/master/android/versioned-abis/expoview-abi31_0_0/src/main/java/abi31_0_0/host/exp/exponent/modules/api/ImageManipulatorModule.java)

Line 121 has the logic which checks for correct dimensions

**Comment by AdamJNavarro** [comment]
Hey @johnnietirado,

Thanks a ton for the detailed report. We are actually already aware of this and actively working on a fix that should hopefully be available this week.

Cheers,
Adam

**Comment by johnnietirado** [comment]
@AdamJNavarro Thanks! Wasn't sure since I couldn't find any mentions of it anywhere.

Will keep an eye out for when the fix is out. Need it for the next update of our app 😄 

Thanks for the awesome work!

**Comment by AdamJNavarro** [comment]
You make a good point. We've been tracking it internally but we should definitely do a better job of making sure bugs are publicly known and can be followed along by the public. We usually try to make sure most things that can be public-facing are but I fell short here haha. I'll be sure to ping you when we have an update on the fix.

**Comment by juliazxu** [comment]
Hi all, I am also having trouble with `manipulateAsync` but specifically converting to base64. Also Android. Is this a related issue @AdamJNavarro , or should I file a separate ticket? It works fine on iOS.

**Comment by randomjunk** [comment]
@AdamJNavarro also possibly related… invoking the ImageManipulator at all on some devices seems to be causing a huge decrease in image size.

Works fine on an S8, but on an HTC One M9 an image 3456x4608 becomes just 864x1152 when just doing a no-op call…

Snack for that here:
https://snack.expo.io/@randomjunk/aW1hZ2

**Comment by maxgfr** [comment]
Hi @AdamJNavarro, I have the same issue on Android when I'd like to resize a picture. Here is a sample of code for my problem : 

```javascript
onPickPicture = async (callback) => {
      const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (status !== 'granted') {
          callback({cancelled: true});
          this.openParameter('Enable camera and photos', 'You need to grant access to your camera and photos to enable this feature');
      } else {
          let result = await ImagePicker.launchImageLibraryAsync({
              allowsEditing: false,
              mediaType: 'Images'
          });

          console.log(result);

          if (!result.cancelled) {
              var w = 0;
              var h = 0;
              if(parseInt(result.height) > 650 || parseInt(result.width) > 650) {
                var constante = parseInt(result.height) / 650;
                w = parseInt(result.width) / constante;
                h = parseInt(result.height) / constante;
              } else {
                w = parseInt(result.width);
                h = parseInt(result.height);
              }
              const manipResult = await ImageManipulator.manipulateAsync( /* THE PROBLEM IS HERE */
                result.uri,
                [{resize: {width: w.toString(), height: h.toString()}}],
                { format: 'jpeg'}
              );
              console.log(manipResult); //
              this.setState({ image: manipResult.uri, height: manipResult.height, width: manipResult.width });
              callback(manipResult);
          }
      }
  };
```

I also have another problem on both platforms which cannot compress a picture with the `ImageManipulator` when I disable the cropping property (allowsEditing: false)

**Comment by pontusab** [comment]
I also got the same `Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image.` on some iOS users.

**Comment by MasonBergstrom** [comment]
I'm getting this also. Looks like it's some sort of multiply by 2 issue. 

I was able to fix work around it by dividing originX, originY, width and, height all by 2. 

```js
let cropped = await ImageManipulator.manipulateAsync(photo.uri, [
    {
        crop: {
            originX: ((photo.width * .05) / 2),
            originY: ((photo.height * .4) / 2),
            width: ((photo.width * .9) / 2),
            height: ((photo.height * .2) / 2)
        }
    }
]);
```

This gives me 90% width and 20% height with it being centered on the original photo.

**Comment by liyuchenf1** [comment]
> I also got the same `Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image.` on some iOS users.

Me too. You solved yet?

**Comment by GollyJer** [comment]
This is super painful for us as our released app started having this problem and it's basically just a picture taking app. 😟

**Comment by johnhaldson** [comment]
Incase anyone else runs into this, I ran into this problem when the width and height ratios got changed due to portrait/landscape mode. I detected the orientation through the exif (if available), then if height > width, then adjusted accordingly and it fixed all my `Please make sure the requested crop rectangle is inside source image.` issues.

**Comment by flieks** [comment]
I also have this problem on latest v34. Only when getting picture from <Camera>
Images from imagePicker and native camera apps work. (tested on pocophone f1)
Making the crop smaller to 75% of width works but i fear on other androids it will fail

**Comment by cruzach** [comment]
Looks like this was fixed in the above PR. If you still run into this behavior, please open up a new issue

**Comment by TomFrames** [comment]
Hey @johnnietirado! Did you encounter a resolution to this issue? I have recently run into this problem.
