### ISSUE TITLE
[three.js] suppress extension warnings differently

### ISSUE THREAD

**Issue by abi** [expo/expo#387]
Right now, the suggested solution is to do `console.disableYellowBox = true;`, unfortunately, this means legit errors encountered within the async `_onGLContextCreate` function also get suppressed. See example below:

![photo jul 19 10 00 48 am](https://user-images.githubusercontent.com/23818/28379660-52a2635c-6c69-11e7-8f7c-aa29effcfbb7.png)

**Comment by brentvatne** [comment]
<img width="903" alt="screen shot 2017-07-19 at 10 35 29 am" src="https://user-images.githubusercontent.com/90494/28380951-007d7efe-6c6e-11e7-89f6-d2facd0e429b.png">

**Comment by abi** [comment]
Which slack channel is this?

**Comment by brentvatne** [comment]
#support

**Comment by nikki93** [comment]
done
