### ISSUE TITLE
StatusBar style different between standalone app and expo app

### ISSUE THREAD

**Issue by SimenB** [expo/expo#3874]
### Environment

```
  Expo CLI 2.13.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /var/folders/gj/0mygpdfn6598xh34njlyrqzc0000gn/T/yarn--1553783196803-0.8192714850884069/node
      Yarn: 1.13.0 - /var/folders/gj/0mygpdfn6598xh34njlyrqzc0000gn/T/yarn--1553783196803-0.8192714850884069/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.9 => 32.0.9
      @types/react: ^16.8.1 => 16.8.6
      @types/react-native: ^0.57.18 => 0.57.38
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.11.9
```

iOS standalone and client

### Steps to Reproduce

The StatusBar when running in the Expo app is different from a built Standalone app.

### Expected Behavior

The app should look identical regardless if the app is ran in the expo app or standalone

![image](https://user-images.githubusercontent.com/1404810/55165930-891ad400-516e-11e9-9697-594807ed3829.png)

### Actual Behavior

the clock etc gets black text in the expo app, but white text in standalone.

![image](https://user-images.githubusercontent.com/1404810/55165907-802a0280-516e-11e9-9fa8-7914ed882d9e.png)

### Reproducible Demo

Happy to create one if you need one, but I think this is pretty straight-forward.

The fix is to add `StatusBar.setBarStyle('dark-content');` in our own `App.tsx` file

**Comment by brentvatne** [comment]
this is listed under "Known issues" currently here: https://docs.expo.io/versions/v32.0.0/guides/splash-screens/#known-issues

but we really should just fix this, it's not a huge change.

**Comment by maxcan** [comment]
@brentvatne since its a known issue, can we release sdk 33 without this and add it as a patch release:

**Comment by SimenB** [comment]
According to that link it's only an issue with splash screen, which is not what I'm seeing (it's different all the time). However, since I can set the style myself, it's not a big issues for us 🙂

**Comment by SKempin** [comment]
@brentvatne I am experiencing this exact issue too, however it is not just on the splash screen - it is on all screens on an iOS standalone build. Examples below.

Is there a fix for this? I wish to submit my standalone app to the iTunes app store, however the status bar is not currently visible (and it will likely get rejected)!

Thanks

Standalone app:

![Simulator Screen Shot - iPhone 8 - 2019-04-09 at 20 53 27](https://user-images.githubusercontent.com/10877466/55832654-ee2ade00-5b0d-11e9-897d-ab813c8d69fc.png)

Expo app:

![Simulator Screen Shot - iPhone 8 - 2019-04-09 at 21 11 13](https://user-images.githubusercontent.com/10877466/55832689-013dae00-5b0e-11e9-8af8-151c4581d33d.png)

**Comment by SKempin** [comment]
@SimenB Can you explain your fix please? Thanks!

**Comment by SimenB** [comment]
We added

```js
StatusBar.setBarStyle('dark-content');

if (Platform.OS === 'android') {
  StatusBar.setTranslucent(true);
  StatusBar.setBackgroundColor('transparent');
}
```
Which works for us

**Comment by SKempin** [comment]
@SimenB Thanks, did you add this in every screen or just the router?

**Comment by SimenB** [comment]
Added it to `App.tsx`. `StatusBar.setBarStyle('dark-content');` is the fix for iOS. That messed up something on android though, so we added those lines to fix it. This is using `react-navigation`, fwiw

**Comment by sakettawde** [comment]
We have the same issue. Standalone iOS app had no status bar, but it looked perfectly fine in expo client app.
On further inspection, it turns out the content of the status bar has a white text and the status bar has a default white background making everything seem like it has been shown in the screenshot.

The solution mentioned by @SimenB worked for us.

For others with the same issue coming here, what I would like to point out is that programmatically setting StatusBar and using props gives you different results!

`StatusBar.setBarStyle('dark-content');` and `<StatusBar barStyle='dark-content'/>` are not the same, though I expected them to be.

The programmatic version ensures it works on the standalone app in iOS and the JSX component does not. Whereas both of them work in the iOS client app. Hence the difference in the standalone and expo client app versions.

**Comment by yuzhakovvv** [comment]
@SimenB thanks, worked for me.

The weird part is that in Expo Status Bar text still remain white on white background, but after build to iOS and upload to TestFlight Status Bar text became black. So everything is fixed

**Comment by eduardofinotti** [comment]
> We added
> 
> ```js
> StatusBar.setBarStyle('dark-content');
> 
> if (Platform.OS === 'android') {
>   StatusBar.setTranslucent(true);
>   StatusBar.setBackgroundColor('transparent');
> }
> ```
> 
> Which works for us

Where???

**Comment by yuzhakovvv** [comment]
@eduardofinotti into `App.js` after `imports`

**Comment by tsapeta** [comment]
Looks like https://github.com/expo/expo/issues/3874#issuecomment-481459231 is the solution. Closing it then 🙂

**Comment by SimenB** [comment]
I disagree - it should behave the same in the expo app and standalone. That comment might be a valid solution, but the status bar should behave the same regardless of config across expo app and standalone

**Comment by brentvatne** [comment]
this should fix it: https://github.com/expo/expo-cli/commit/a91b6517c96ce168e182ceab127616bea9c67b8b

but it isn't on master and needs to be tested

**Comment by richardwu** [comment]
> We added
> 
> ```js
> StatusBar.setBarStyle('dark-content');
> 
> if (Platform.OS === 'android') {
>   StatusBar.setTranslucent(true);
>   StatusBar.setBackgroundColor('transparent');
> }
> ```
> 
> Which works for us

Just ran into this recently when I upgraded from SDK 41 -> SDK 42, and switched from `expo build` to `expo eas build`. On my custom development client the status bar is fine and lets me render screens underneath it, but once a standalone app is built status bar is white on white and prevents rendering underneath.

Your fix seems to work however!

**Comment by SleeplessByte** [comment]
This API actually worked/works when using `expo` build, but is broken on `eas` (same as @richardwu is mentioning).

The bug isn't just that the status bar is white, it's that it does _not_ use the defined properties in app.json / does not respond to the `<StatusBar>` component mounted. It doesn't matter if react-native or `expo-status-bar` is used. 

- expo client: works
- eas dev client: works
- expo standalone ios: works
- expo standalone android: works
- eas standalone ios: works
- eas standalone android: 💥 _broken_ 💥 

In my case, I get `#00000080` as background colour with _black_ foreground text, no matter the background colour and/or bar style.

**Comment by fabio-alvarenga** [comment]
> This API actually worked/works when using `expo` build, but is broken on `eas` (same as @richardwu is mentioning).
> 
> The bug isn't just that the status bar is white, it's that it does _not_ use the defined properties in app.json / does not respond to the `<StatusBar>` component mounted. It doesn't matter if react-native or `expo-status-bar` is used.
> 
>     * expo client: works
> 
>     * eas dev client: boom _sometimes works_ boom
> 
>     * expo standalone ios: works
> 
>     * expo standalone android: works
> 
>     * eas standalone ios: works
> 
>     * eas standalone android: boom _broken_ boom
> 
> 
> In my case, I get `#00000080` as background colour with _black_ foreground text, no matter the background colour and/or bar style.

Chiming in to say: the exact same thing is happening here :(

**Comment by fabio-alvarenga** [comment]
@SleeplessByte did you manage to fix it? I'm stuck with EAS Builds because I'm using native modules in my app, but I couldn't figure out how to properly style the status bar on Android for the life of me.

**Comment by SleeplessByte** [comment]
@fabio-alvarenga unfortunately not. I don't have a workaround at this moment.

**Comment by fabio-alvarenga** [comment]
No worries, mate. If I figure out something I'll share. Thanks!

**Comment by fabio-alvarenga** [comment]
Boy, oh boy. I was on the verge of giving up, it's friday night, everyone is drinking outside, it just occurred to me in my 10th build or so that I could remove the following bit from `app.config.ts`

```ts
  androidStatusBar: {
    translucent: true,
    barStyle: 'light-content',
    backgroundColor: '#00000000',
  },
```
and it worked. 

Even without setting this configuration explicity, it's working as expected for me: the status bar is either transparent or inherits the background-color from the splash screen. Which is a win. In the splash screen, it doesn't matter if the status bar is translucent or not; in the rest of the app the translucency and the background colors are working fine.

It's enough for me right now :)

**Comment by SleeplessByte** [comment]
@fabio-alvarenga very nice. I copied that exact configuration (but using `app.config.json`) and unfortunately it only works in non-standalone builds for me. Was worth a try tho!

**Comment by fabio-alvarenga** [comment]
Wait, just to be sure: did you *copy* the configuration above? That code snippet is the one I've _removed_ from my `app.config`. Not setting any `androidStatusBar` configuration at all is what works for me.

**Comment by SleeplessByte** [comment]
Ah. Let me try that. I didn't read this correctly 😅

**Comment by SleeplessByte** [comment]
Unfortunately it doesn't work for me. When I removed the entire block from the app.json, no visual changes in the _standalone_ builds. Works fine in dev client.

**Comment by fabio-alvarenga** [comment]
Too bad. It is a workaround anyway - guess it's associated with some other config in my project I'm not aware of. Let's keep an eye on this issue.

**Comment by SleeplessByte** [comment]
Not stale, but I have experienced different behaviour in the last few updates.

**Comment by SleeplessByte** [comment]
It's not stale. Seeing this in eas built binaries.

**Comment by Julioevm** [comment]
Seeing the same issue. Works perfectly fine in local dev build but the eas built app shows a different background color on android for the status bar than the normal one (inherited from the header color, respecting the theme.) With eas it just seems to be picking the splash screen color :(

**Comment by SleeplessByte** [comment]
It's not stale, and still seeing this in eas binaries, but I have no interest in keeping up with this or keeping it open, so I've unsubscribed from the thread, which probably means that unless someone else responds this will be closed in 67 days.
