### ISSUE TITLE
Update Facebook docs to indicate how to set it up in bare and ejected apps

### ISSUE THREAD

**Issue by tafelito** [expo/expo#3876]
## 🐛 Bug Report

this is a similar issue than #1867 but I'm running expo v32.0

The error says

`Error. Tried to perform Facebook login with behavior `(null)`, but no Facebook app id was provided`

Everything was working fine before ejecting the app. After I eject it, i added the facebookScheme, facebookAppId & facebookDisplayName to the app.json. I also changed the fb app bundle id.

### Environment

Expo CLI 2.13.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.4.1 => 3.4.1 
    npmGlobalPackages:
      expo-cli: 2.13.0

The app is an ExpoKit and I'm testing it on a iOS & iOS simulator

### Steps to Reproduce

Create a new expo app that use Facebook login. Eject it and try to login

### Expected Behavior

Be able to use native behavior 

### Actual Behavior

Login works if I use "web" as the behaivor. It does not when using native.

**Comment by brentvatne** [comment]
hey there! when you eject you should not add this information to app.json, you now have full control over the native project and you should instead put the configuration where the fbsdk tutorial tells you to put it

**Comment by tafelito** [comment]
thanks @brentvatne, that worked!  the error was what drove me off, it said I needed to be added in the app.json. 
Just doing the [Step 3] of (https://developers.facebook.com/docs/ios/getting-started/) did the trick
