### ISSUE TITLE
GLView's onContextCreate not called when React Native debugger is open

### ISSUE THREAD

**Issue by evanram** [expo/expo#3877]
### Environment

```
Expo CLI 2.11.6 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.11.6
```

I am targeting iOS.

x-posted from https://github.com/expo/expo-2d-context/issues/8

### Steps to Reproduce

Enable remote debugging while the current screen is a GLView component. 

Reproducible on both the external React Native debugger as well as the 'default' one in my browser.

### Expected Behavior

I would like to be able to use the React Native debugger while a GLView is running. Specifically, I want to use the canvas (discovered this bug while playing with `expo-2d-context`).

### Actual Behavior

The component will render a blank white screen, instead of whatever fun stuff I've drawn to it.

### Reproducible Demo

I have issues running `expo-2d-context` in Snack, so here's a component that shows the issue.

```javascript
class TestDummy extends React.Component {
  constructor(props) {
    super(props);
    this._onGLContextCreate = this._onGLContextCreate.bind(this);
  }

  render() {
    return <GLView
              style={{ flex: 1 }}
              onContextCreate={this._onGLContextCreate}
              onTouchStart={(e) => alert('touch start')}
           />;
  }

  _onGLContextCreate(gl) {
    alert('created context');
  }
}
```

`onTouchStart` triggers the alert "touch start" always, so I know that `GLView` exists in React's tree. However `_onGLContextCreate` does not seem to be called (_only when using debugger_) as the alert "created context" does not appear in debug mode.

**Comment by brentvatne** [comment]
unfortunately GLView does not work with remote debugging enabled because it requires synchronous native calls which are not supported when executing JS in chrome. cc @cruzach we should add this to the doc for GLView, not sure why it's not there already

**Comment by ide** [comment]
The way RN does debugging is incompatible with the way GLView and future RN modules work because the RN debugger runs JS on your computer instead of on the phone.

Obviously in the long term, something needs to change since the corollary here is that RN is moving in a direction where debugging is not possible.

**Comment by tsapeta** [comment]
As mentioned above, GLView doesn't work with remove debugging enabled and the limitation is now described in the docs. Closing.
