### ISSUE TITLE
how do i get rid of this weird inspect/ performnace screen on my app ?  

### ISSUE THREAD

**Issue by jpca999** [expo/expo#388]
i dont know what did i do to turn it ON

![image](https://user-images.githubusercontent.com/1026325/28380729-6864dee6-6c86-11e7-8300-068ddb4166f7.png)

**Comment by brentvatne** [comment]
if you open dev menu and choose 'toggle element inspector' it will hide that

see: https://docs.expo.io/versions/v18.0.0/guides/development-mode.html

**Comment by jpca999** [comment]
Thanks
