### ISSUE TITLE
Barcode scanner not triggering onBarCodeScanned on some android devices with expo 32

### ISSUE THREAD

**Issue by fxaeberhard** [expo/expo#3886]
## 🐛 Bug Report

Hello everybody, I have an issue with the BarcodeScanner. While it works greats on the expo app, it does not when I build the app on some devices, namely the Huawai P Smart +.

### Environment
Expo CLI 2.13.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
Packages
    expo: "^32.0.0" => 32.0.6,
    react: "16.5.0" => 16.5.0,
    react-native: "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz" =>0.57.1
Target 
   Android and IOS standalone app
 

### Steps to Reproduce
1. Download the Barcode example (twicked to add app.json on https://snack.expo.io/@fxaeberhard/barcodescanner-example)
2. Expo start => works fine
3. expo build:android =>not that much

### Expected Behavior
Upon scanning the QR code, an alert should appear.

### Actual Behavior
While scan works on some device and on expo app, it does not work on others (Huawei Psmart+). The app asks for permissions fine, displays the camera on view but fails to trigger the onBarCodeScanned handler. Just to make it clear, the scan work on my Huawei Psmart with expo app but not standalone (same device).

### Reproducible Demo
https://snack.expo.io/@fxaeberhard/barcodescanner-example (need to build standalone app and run on device like Huawei Psmart+).

Thank you all for the hard work and long live expo!

**Comment by muhammad-ihsan** [comment]
any progress? because i have the same problem :D

**Comment by salmanLee** [comment]
Check your phone permissions.

**Comment by Galadrim-fr** [comment]
We have the same problem on Expo 32 / React 16.5.0 with different android devices:
- One plus one / android 9.0
- Doogee X20L / android 7.0
Any clue ? It would be great to fix that without ejecting !

**Comment by alexn29** [comment]
I have the same problem with Huawei's devices

**Comment by Guichaguri** [comment]
Same problem. Restarting the app seems to fix the issue, but it's too unstable.

**Comment by a-fortunato** [comment]
We're having this same problem too, but on iOS and with the expo client.
We have our camera component inside a popup component. First and some times it recognises the bar code (then triggers the onBarCodeScanned) and some other times it just doesn't.

We think it could be a problem with mounting/unmounting the component? Is it possible that the camera is not unmounting correctly?

**Comment by exAspArk** [comment]
It works on Samsung Galaxy s8 but doesn't work on Pixel 2 XL and Huawei nova 3i.

**Comment by Yuying-He** [comment]
I have the same problem with expo 33/react 16.8.0. On Redmi 7 / Android 9. It does not recognize the QR code.

**Comment by Sxleein** [comment]
On Expo 35, the same problem on xiaomi 8. First and some times it recognizes the bar code (then triggers the onBarCodeScanned) and some other times it just doesn't.

**Comment by bakabon86** [comment]
i used expo sdk 35, the problem still exist on xiaomi redmi 5a.  it only scanned 1 time only. after that the barcode scanner couldn't read the QRcode again. any help?

**Comment by JimVanEeden** [comment]
I have the same issue with some iPhones, will this be fixed in sdk 36? It seems the Camera component will be reworked there.

**Comment by tonylanglet** [comment]
Anyone found a solution for this or is there any status updates? I recently started using expo-barcode-scanner again and it worked a few months back but now I get like all others in this thread the onBarCodeScanned is never called. 

I'm using a One Plus (Android)

**Comment by sa1dai** [comment]
Problem is still here

**Comment by brandner** [comment]
Seeing the same thing on a Pixel4. Scans the first time, but then refuses to call the callback until the app is restarted.

**Comment by matrak-jason** [comment]
It would be good if Expo produced a list of devices where this feature does, or does not work. I tried on a Samsung S7 and it does not work. Is anyone close to figuring out how to predict which devices are the problem?

**Comment by ibrust** [comment]
I don't understand why you'd automatically close issues that have not been addressed. It's not like the problem goes away when you ignore it... 
Honestly, the expo team is one of the worse teams I've seen as far as investigating and properly addressing bugs, they do things like this all the time.
