### ISSUE TITLE
[expo-image-manipulator][Android] Crop fails on SDK32

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#3887]
### Environment

Expo SDK32 on Android

### Steps to Reproduce

Launch `ImageManipulator.manipulate` with cropping operation

### Expected Behavior

Crop works just fine and returns valid cropped image.

### Actual Behavior

Crop fails with exception `[Unhandled promise rejection: Error: Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image.]`

### Reproducible Demo

https://snack.expo.io/@barthec/android-camera-bug---2

### Side notes

Since SDK32 on Android we use `Fresco` library to handle loading images.
These lines are the cause.
https://github.com/expo/expo/blob/master/android/versioned-abis/expoview-abi32_0_0/src/main/java/abi32_0_0/host/exp/exponent/modules/api/ImageManipulatorModule.java#L58-L62

**Comment by pontusab** [comment]
Same on iOS, can't reproduce but some users get this issue currently on iPhone xs max.

**Comment by maxgfr** [comment]
+1

**Comment by bbarthec** [comment]
@pontusab I've created separate issue for your case as from what you're writing it only affects one `iOS` device. See https://github.com/expo/expo/issues/3929

**Comment by pontusab** [comment]
@bbarthec Thanks! Only from Sentry so may be more devices in the end
