### ISSUE TITLE
[expo-face-detector] Conflict with react-native-firebase in iOS

### ISSUE THREAD

**Issue by ndjemel** [expo/expo#3888]
### Environment

target: iOS

### Steps to Reproduce

install and link react-native-firebase (more specifically the Firebase Pod), install and link this library via react-native-unimodules

### Expected Behavior

Both libraries working simultaneously 

### Actual Behavior

The expo libraries rely on GoogleUtilities 1.3.2, while firebase requires 5.x to work with react native 0.59. 

I am not sure if it's possible to just bump the GoogleUtilities version used by expo-face-detector since it's actually a dependency of GoogleMobileVision/Detector (1.1.0), and GoogleMobileVision was deprecated in favor of MLKit ?

**Comment by changLiuUNSW** [comment]
I get blocked by this issue as well. Cannot install eact-native-firebase

**Comment by tsapeta** [comment]
Please see my comment for the workaround for now: https://github.com/unimodules/react-native-unimodules/pull/42#issuecomment-500168574

Anyway, I'm keeping this issue open as we do want to exclude these optional modules in ejected apps by default.

**Comment by KowalskiP** [comment]
Hi, guys. Any news about updates here? I need both packages as well.

**Comment by raajnadar** [comment]
@KowalskiP follow this PR https://github.com/expo/expo/pull/4056

**Comment by tsapeta** [comment]
It seemed to be an issue in the apps ejected to ExpoKit which is no longer supported by us, so I'm closing it. We suggest ejecting to bare workflow instead, where you have full control on what it's being installed in your app 🙂
