### ISSUE TITLE
[GLView] 2D context doesn't work on Android because it requests 0 bits for stencil buffer

### ISSUE THREAD

**Issue by JeffBobbo** [expo/expo#3893]
Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
    npmPackages:
      expo: ^31.0.2 => 31.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.14

For Android/iOS

### Steps to Reproduce

Attempt to run the example from 
https://blog.expo.io/introducing-the-canvas-2d-context-api-for-expo-8ba6106ed8e5

Or this cutdown example which screenshots are of:
https://snack.expo.io/@innershed/expo2d-android

### Expected Behavior

To draw a purple line, like this (iOS):
![image](https://user-images.githubusercontent.com/5425481/50684023-0ae5e000-100c-11e9-946a-05e512b18a1b.png)

### Actual Behavior

Entire canvas area is filled with purple, adjusting `moveTo` and `lineTo` parameters has no effect.
![image](https://user-images.githubusercontent.com/5425481/50684065-2a7d0880-100c-11e9-85c5-a002d1dba499.png)
A warning is given in the console: `WARNING: Was given 0 stencil bits - strokes and clipping will be broken`

### Reproducible Demo
https://snack.expo.io/@innershed/expo2d-android

**Comment by evanram** [comment]
Yikes that's too bad it's not on the roadmap. This basically kills Expo as a viable option for cross-platform mobile game development.

**Comment by hugpeter** [comment]
Is there a quick fix we can do locally in short term while we wait?

**Comment by L0g1k** [comment]
Can you please detail any additional risks or explain what is needed to resolve this issue in a minimal sense beyond changing that integer from 0 to 4? 

If there is more needed, someone could create a PR if you are too busy.

If there is not more needed, and it is low risk, I would like humbly and respectfully ask why you need a roadmap for it...

**Comment by faria** [comment]
fyi: this issue appears on my Samsung Galaxy J7 (2016) SM-J710MN as well.

**Comment by iyobo** [comment]
This is still an issue. It does seem strange that only iOS gets all the attention. Team Android is jealous! :D

Seriously though, do the maintainers need a PR? This has made expo canvas unusable on Adroid.
