### ISSUE TITLE
styled-components not working in snack.expo.io

### ISSUE THREAD

**Issue by ttmarek** [expo/expo#3896]
Hi,

I'm not sure if this is the best repository to report this in, but styled-components does not seem to work in any of my snacks. For example, here's the snack that's linked directly in the styled-components docs: https://snack.expo.io/@danielmschmidt/styled-components.

Everything works as-intended locally and only seems to be an issue on snack.expo.io.

**Comment by ttmarek** [comment]
There's also a related issue on the styled-components website repo: https://github.com/styled-components/styled-components-website/issues/440

**Comment by satya164** [comment]
For now, importing styled components without the `/native` part works.

```js
import styled from 'styled-components/native';
```

I'll fix the issue with `/native`.

**Comment by FiberJW** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
