### ISSUE TITLE
Install master branch of expo-location on bare application

### ISSUE THREAD

**Issue by lautaro-osacar** [expo/expo#3897]
I'm trying to install expo-location next release but i'm getting 
``MainApplication.java:49: error: cannot find symbol
     new LocationPackage(),
``
when I try to build on android.

I installed expo-location with `npm install --save expo-location@next`

What can I do to use expo-location current master branch with unimodules?

**Comment by cruzach** [comment]
Hey @lautaro-osacar,

Have you followed all the steps of the [installation instructions](https://github.com/expo/expo/tree/master/packages/expo-location#installation)?

Thanks!
-Charlie

**Comment by lautaro-osacar** [comment]
> Hey @lautaro-osacar,
> 
> Have you followed all the steps of the [installation instructions](https://github.com/expo/expo/tree/master/packages/expo-location#installation)?
> 
> Thanks!
> -Charlie

Yes, but according of https://www.npmjs.com/package/expo-location I realized that I was installing 2.0.0-rc.3 version with `npm install --save expo-location@next` command.

How can I use current master branch of expo-location?

**Comment by cruzach** [comment]
Under the `Versions` tab on the npm page, you can see the "next" tag corresponds with version 2.0.0-rc.3, but "latest" corresponds to version 4.0.0, which is the current master branch.
