### ISSUE TITLE
Docs: widgets overview / tutorial for simple app

### ISSUE THREAD

**Issue by petr001** [expo/expo#39]
Hi,

I'm new to React Native and ExponentJS. I've started a new project like a charm (really excellent work!), but now I'm struggling with what can I do with it. I'm missing  list of all GUI widgets, how to use router / navigation in the app, etc., etc.

I've googled a bit but didn't find anything useful. Do you have any up-to-date link to some tutorial?

**Comment by brentvatne** [comment]
Hello! Did you look at the documentation?

https://docs.getexponent.com/versions/v14.0.0/introduction/additional-resources.html
https://docs.getexponent.com/versions/v14.0.0/guides/routing-and-navigation.html
https://docs.getexponent.com/versions/v14.0.0/sdk/index.html
https://docs.getexponent.com/versions/v14.0.0/guides/index.html

You can also use components listed in the React Native docs:
https://facebook.github.io/react-native/docs/getting-started.html

Let me know what you think is missing from here! Sorry for the late reply.
