### ISSUE TITLE
Update ExpoSDK 32 unimodules not working

### ISSUE THREAD

**Issue by DubluDD** [expo/expo#3907]
I recently tried to update the Expo SDK from 27.0.0 to 32.0.0. First I d like to point out that following the documentation for updating the SDK gets you nowhere, the build would fail, but in the end I`ve got the build to run and managed to install the app with the updated SDK. 

Next I started the expo packager via "expo start" and opened the app on Android Emulator.

![image](https://user-images.githubusercontent.com/30705188/55380141-f2606580-5527-11e9-89c7-d4aefca0af0d.png)

The app opens successfully but seems to fail on these lines.

![image](https://user-images.githubusercontent.com/30705188/55380200-2c316c00-5528-11e9-810d-49d8707c4786.png)

This might be related/useful.

![image](https://user-images.githubusercontent.com/30705188/55380243-508d4880-5528-11e9-9026-3ec7e8801c10.png)

/app/build.gradle

buildscript {
  repositories {
    google()
    maven { url 'https://maven.fabric.io/public' }
  }

  dependencies {
    classpath 'io.fabric.tools:gradle:1.27.1'
  }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'devicefarm'

// apply plugin: 'com.neenbedankt.android-apt'

repositories {
  maven { url 'https://maven.fabric.io/public' }
}

android {
  compileSdkVersion 27
  // buildToolsVersion '26.0.1'

  }
  defaultConfig {

    targetSdkVersion 26
    versionCode 1701
    versionName '0.1057'
    ndk {
      abiFilters 'armeabi-v7a', 'x86'
    }
    multiDexEnabled true
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    // Deprecated. Used by net.openid:appauth
    manifestPlaceholders = [
      'appAuthRedirectScheme': 'host.exp.exponent'
    ]
  }
  dexOptions {
    javaMaxHeapSize System.getenv("DISABLE_DEX_MAX_HEAP") ? null : "8g"
  }
  buildTypes {
    release {
      //Settings this to true will not build IF aws-amplify-react-native is linked. Unlink it and you 
      //can use minification (reduces APK size from ~90 to ~40)
      //Or do some more research on why this crashes with minify enabled.
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      signingConfig signingConfigs.config
    }
    debug {
      minifyEnabled false
      signingConfig signingConfigs.config
    }
  }

  flavorDimensions 'default'
  productFlavors {
      dev {
          buildConfigField  "String", "RELEASE_CHANNEL", "\"default\""

          dimension "default"
      }
      trial {
          buildConfigField  "String", "RELEASE_CHANNEL", "\"test\""

          dimension "default"
      }
      beta {
          buildConfigField  "String", "RELEASE_CHANNEL", "\"beta\""

          dimension "default"
      }
      production {
          buildConfigField  "String", "RELEASE_CHANNEL", "\"production\""

          dimension "default"
      }
  }
  lintOptions {
    abortOnError false
  }
  packagingOptions {
    pickFirst "**"
  }
  configurations.all {
    resolutionStrategy.force 'com.android.support:design:27.1.0'
  }
}

// Don't use modern jsc-android since it still has some critical bugs that
// crash applications when the string for the JS bundle is loaded and when
// locale-specific date functions are called.
// configurations.all {
//   resolutionStrategy {
//     force 'org.webkit:android-jsc:r216113'
//   }
// }

devicefarm {
  projectName System.getenv("DEVICEFARM_PROJECT_NAME")
  devicePool System.getenv("DEVICEFARM_DEVICE_POOL")
  executionTimeoutMinutes 40
  authentication {
    accessKey System.getenv("AWS_ACCESS_KEY_ID")
    secretKey System.getenv("AWS_SECRET_ACCESS_KEY")
  }
}

configurations.all {
  resolutionStrategy {
    force 'org.webkit:android-jsc:r224109'
  }
}
// WHEN_PREPARING_SHELL_REMOVE_FROM_HERE

apply from: 'expo.gradle'

// WHEN_PREPARING_SHELL_REMOVE_TO_HERE

dependencies {
    // compile project(':aws-amplify-react-native')
  implementation fileTree(dir: 'libs', include: ['*.jar'])

  api project(':react-native-add-calendar-event')
  api project(':react-native-vector-icons')

  implementation 'com.android.support:multidex:1.0.1'

  // Our dependencies
  implementation 'com.android.support:appcompat-v7:27.1.1'

  // Our dependencies from ExpoView
  // DON'T ADD ANYTHING HERE THAT ISN'T IN EXPOVIEW. ONLY COPY THINGS FROM EXPOVIEW TO HERE.
  implementation 'com.android.support:appcompat-v7:27.1.1'
  implementation 'com.facebook.android:facebook-android-sdk:4.37.0'
  implementation('com.facebook.android:audience-network-sdk:4.99.0') {
    exclude module: 'play-services-ads'
  }
  compileOnly 'org.glassfish:javax.annotation:3.1.1'
  implementation 'com.jakewharton:butterknife:8.4.0'
  implementation 'de.greenrobot:eventbus:2.4.0'

  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
  implementation 'com.amplitude:android-sdk:2.9.2'

  implementation 'com.squareup.picasso:picasso:2.5.2'
  implementation 'com.google.android.gms:play-services-gcm:15.0.1'
  implementation 'com.google.android.gms:play-services-analytics:16.0.1'
  implementation 'com.google.android.gms:play-services-maps:15.0.1'
  implementation 'com.google.android.gms:play-services-auth:15.0.1'
  implementation 'com.google.android.gms:play-services-location:15.0.1'
  implementation 'com.google.android.gms:play-services-ads:15.0.1'
  annotationProcessor 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
  implementation "com.raizlabs.android:DBFlow-Core:2.2.1"
  implementation "com.raizlabs.android:DBFlow:2.2.1"
  implementation "com.madgag.spongycastle:core:1.53.0.0"
  implementation "com.madgag.spongycastle:prov:1.53.0.0"
  debugImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  // debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.4-beta1'
  releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  implementation 'com.facebook.device.yearclass:yearclass:2.1.0'
  implementation 'commons-io:commons-io:1.4'
  implementation 'me.leolin:ShortcutBadger:1.1.4@aar'
  implementation 'com.theartofdev.edmodo:android-image-cropper:2.7.0'
  implementation 'com.yqritc:android-scalablevideoview:1.0.1'
  implementation 'commons-codec:commons-codec:1.10'
  implementation 'com.segment.analytics.android:analytics:4.3.0'
  implementation 'com.google.zxing:core:3.3.3'
  implementation 'net.openid:appauth:0.4.1'
  implementation('com.airbnb.android:lottie:2.5.5') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
  }
  implementation 'io.branch.sdk.android:library:2.17.1'
  implementation('io.nlopez.smartlocation:library:3.2.11') {
    transitive = false
  }
  implementation 'com.android.support:exifinterface:27.1.1'
  implementation 'com.squareup.okio:okio:1.9.0'
  implementation 'com.facebook.soloader:soloader:0.5.1'

  implementation 'com.google.android.exoplayer:exoplayer:2.6.1'
  implementation 'expolib_v1.com.google.android.exoplayer:expolib_v1-extension-okhttp:2.6.1@aar'

  // expo-file-system
  implementation 'com.squareup.okhttp3:okhttp:3.10.0'
  implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0'

  // Testing
  androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
  // We use a modified build of com.android.support.test:runner:1.0.1. Explanation in maven-test/README
  androidTestImplementation 'com.android.support.test:runner:1.0.1'
  androidTestImplementation 'com.android.support:support-annotations:27.1.1'
  androidTestImplementation 'com.google.code.findbugs:jsr305:3.0.0'
  androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.1'
  androidTestImplementation 'com.azimolabs.conditionwatcher:conditionwatcher:0.2'

  testImplementation 'junit:junit:4.12'
  testImplementation 'org.mockito:mockito-core:1.10.19'
  testImplementation 'org.robolectric:robolectric:3.8'
  testImplementation 'com.android.support.test:runner:1.0.2-alpha1'
  testImplementation 'com.android.support.test:rules:1.0.2-alpha1'

  
  implementation('host.exp.exponent:expoview:32.0.0@aar') {
    transitive = true
    exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    exclude group: 'com.squareup.okhttp3', module: 'okhttp-urlconnection'
  }
  

  
  api 'com.facebook.react:react-native:32.0.0'
  api 'host.exp.exponent:expo-app-loader-provider:1.0.0'
  api 'host.exp.exponent:expo-core:2.0.0'
  api 'host.exp.exponent:expo-constants-interface:2.0.0'
  api 'host.exp.exponent:expo-constants:2.0.1'
  api 'host.exp.exponent:expo-errors:1.0.0'
  api 'host.exp.exponent:expo-file-system-interface:2.0.0'
  api 'host.exp.exponent:expo-file-system:2.0.0'
  api 'host.exp.exponent:expo-image-loader-interface:2.0.0'
  api 'host.exp.exponent:expo-permissions:2.0.0'
  api 'host.exp.exponent:expo-permissions-interface:2.0.0'
  api 'host.exp.exponent:expo-sensors-interface:2.0.0'
  api 'host.exp.exponent:expo-react-native-adapter:2.0.0'
  api 'host.exp.exponent:expo-task-manager:1.0.0'
  api 'host.exp.exponent:expo-task-manager-interface:1.0.0'

  // Optional universal modules, could be removed
  // along with references in MainActivity
  api 'host.exp.exponent:expo-ads-admob:2.0.0'
  api 'host.exp.exponent:expo-app-auth:2.0.0'
  api 'host.exp.exponent:expo-analytics-segment:2.0.0'
  api 'host.exp.exponent:expo-barcode-scanner-interface:2.0.0'
  api 'host.exp.exponent:expo-barcode-scanner:2.0.0'
  api 'host.exp.exponent:expo-camera-interface:2.0.0'
  api 'host.exp.exponent:expo-camera:2.0.0'
  api 'host.exp.exponent:expo-contacts:2.0.0'
  api 'host.exp.exponent:expo-face-detector:2.0.0'
  api 'host.exp.exponent:expo-face-detector-interface:2.0.0'
  api 'host.exp.exponent:expo-font:2.0.0'
  api 'host.exp.exponent:expo-gl-cpp:2.0.0'
  api 'host.exp.exponent:expo-gl:2.0.0'
  api 'host.exp.exponent:expo-google-sign-in:2.0.0'
  api 'host.exp.exponent:expo-local-authentication:2.0.0'
  api 'host.exp.exponent:expo-localization:2.0.0'
  api 'host.exp.exponent:expo-location:2.0.1'
  api 'host.exp.exponent:expo-media-library:2.0.0'
  api 'host.exp.exponent:expo-print:2.0.0'
  api 'host.exp.exponent:expo-sensors:2.0.0'
  api 'host.exp.exponent:expo-sms:2.0.0'
  api 'host.exp.exponent:expo-background-fetch:1.0.0'

  
}

// This has to be down here for some reason
apply plugin: 'com.google.gms.google-services'

build.gradle

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    google()
    jcenter()
    maven { url 'https://dl.bintray.com/android/android-tools/' }
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    classpath 'com.google.gms:google-services:3.2.1'
    classpath 'de.undercouch:gradle-download-task:2.0.0'
    classpath 'com.amazonaws:aws-devicefarm-gradle-plugin:1.3' // https://github.com/awslabs/aws-device-farm-gradle-plugin/releases
  }
}

allprojects {
  repositories {
    // For non-detach
    maven {
      url "$rootDir/maven"
    }
    // For old expoviews to work
    maven {
      url "$rootDir/versioned-abis/expoview-abi26_0_0/maven"
    }
    maven {
      url "$rootDir/versioned-abis/expoview-abi27_0_0/maven"
    }
    maven {
      url "$rootDir/versioned-abis/expoview-abi28_0_0/maven"
    }
    maven {
      url "$rootDir/versioned-abis/expoview-abi29_0_0/maven"
    }
    maven {
      url "$rootDir/versioned-abis/expoview-abi30_0_0/maven"
    }
    maven {
      url "$rootDir/versioned-abis/expoview-abi31_0_0/maven"
    }
    maven {
      url "$rootDir/versioned-abis/expoview-abi32_0_0/maven"
    }
    // For detach
    maven {
      url "$rootDir/../node_modules/expokit/maven"
    }
    maven {
      // We use a modified build of com.android.support.test:runner:1.0.1. Explanation in maven-test/README
      url "$rootDir/maven-test"
    }
    google()
    jcenter()
    maven {
      // Local Maven repo containing AARs with JSC built for Android
      url "$rootDir/../node_modules/jsc-android/dist"
    }
    flatDir {
      dirs 'libs'
      // dirs project(':expoview').file('libs')
    }
    // https://github.com/google/ExoPlayer/issues/5225#issuecomment-445739013
    maven { url 'https://google.bintray.com/exoplayer' }
    maven { url "https://jitpack.io" }

    // Want this last so that we never end up with a stale cache
    mavenLocal()
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}

expo.gradle
// Gradle script for detached apps.

import org.apache.tools.ant.taskdefs.condition.Os

void runBefore(String dependentTaskName, Task task) {
  Task dependentTask = tasks.findByPath(dependentTaskName);
  if (dependentTask != null) {
    dependentTask.dependsOn task
  }
}

afterEvaluate {
  def expoRoot = file("../../")
  def inputExcludes = ["android/**", "ios/**"]

  task exponentPrebuildStep(type: Exec) {
    workingDir expoRoot
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
      commandLine "cmd", "/c", ".\\node_modules\\expokit\\detach-scripts\\run-exp.bat"
    } else {
      commandLine "./node_modules/expokit/detach-scripts/run-exp.sh", "prepare-detached-build", "--platform", "android", expoRoot
    }
  }
  runBefore("preBuild", exponentPrebuildStep)

  // Based on https://github.com/facebook/react-native/blob/master/react.gradle

  android.applicationVariants.each { variant ->
    def folderName = variant.name
    def targetName = folderName.capitalize()

    def assetsDir = file("$buildDir/intermediates/merged_assets/${folderName}/merge${targetName}Assets/out")

    // Bundle task name for variant
    def bundleExpoAssetsTaskName = "bundle${targetName}ExpoAssets"

    def currentBundleTask = tasks.create(
        name: bundleExpoAssetsTaskName,
        type: Exec) {
      description = "Expo bundle assets for ${targetName}."

      // Create dirs if they are not there (e.g. the "clean" task just ran)
      doFirst {
        assetsDir.mkdirs()
      }

      // Set up inputs and outputs so gradle can cache the result
      inputs.files fileTree(dir: expoRoot, excludes: inputExcludes)
      outputs.dir assetsDir

      // Set up the call to exp
      workingDir expoRoot

      if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        commandLine("cmd", "/c", ".\\node_modules\\expokit\\detach-scripts\\run-exp.bat", "bundle-assets", expoRoot, "--platform", "android", "--dest", assetsDir)
      } else {
        commandLine("./node_modules/expokit/detach-scripts/run-exp.sh", "bundle-assets", expoRoot, "--platform", "android", "--dest", assetsDir)
      }

      enabled targetName.toLowerCase().contains("release") || targetName.toLowerCase().contains("prod")
    }

    currentBundleTask.dependsOn("merge${targetName}Resources")
    currentBundleTask.dependsOn("merge${targetName}Assets")

    runBefore("process${targetName}Resources", currentBundleTask)
  }
}

settings.gradle 

include ':app'

include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-add-calendar-event'
project(':react-native-add-calendar-event').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-add-calendar-event/android')
// include ':aws-amplify-react-native'
// project(':aws-amplify-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/aws-amplify-react-native/android')

include ':expo-core'
project(':expo-core').projectDir = new File(rootProject.projectDir, '../node_modules/expo-core/android')

//FOR-AWS-AMPLiFY
// include ':aws-amplify-react-native'
// project(':aws-amplify-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/aws-amplify-react-native/android')

MainApplication.java

package host.exp.exponent;

import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

import expo.core.interfaces.Package;
import expo.loaders.provider.interfaces.AppLoaderPackagesProviderInterface;
import expo.modules.ads.admob.AdMobPackage;
import expo.modules.analytics.segment.SegmentPackage;
import expo.modules.appauth.AppAuthPackage;
import expo.modules.backgroundfetch.BackgroundFetchPackage;
import expo.modules.barcodescanner.BarCodeScannerPackage;
import expo.modules.camera.CameraPackage;
import expo.modules.constants.ConstantsPackage;
import expo.modules.contacts.ContactsPackage;
import expo.modules.facedetector.FaceDetectorPackage;
import expo.modules.filesystem.FileSystemPackage;
import expo.modules.font.FontLoaderPackage;
import expo.modules.gl.GLPackage;
import expo.modules.google.signin.GoogleSignInPackage;
import expo.modules.localauthentication.LocalAuthenticationPackage;
import expo.modules.localization.LocalizationPackage;
import expo.modules.location.LocationPackage;
import expo.modules.medialibrary.MediaLibraryPackage;
import expo.modules.permissions.PermissionsPackage;
import expo.modules.print.PrintPackage;
import expo.modules.sensors.SensorsPackage;
import expo.modules.sms.SMSPackage;
import expo.modules.taskManager.TaskManagerPackage;
import expolib_v1.okhttp3.OkHttpClient;

// Needed for `react-native link`
import com.facebook.react.ReactApplication;
import com.oblador.vectoricons.VectorIconsPackage;
import com.vonovak.AddCalendarEventPackage;
// import com.facebook.react.shell.MainReactPackage;
// import com.amazonaws.amplify.pushnotification.RNPushNotificationPackage;

public class MainApplication extends ExpoApplication implements AppLoaderPackagesProviderInterface<ReactPackage> {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        new MainReactPackage(),
        new VectorIconsPackage(),
        new AddCalendarEventPackage()
            // new RNPushNotificationPackage()
    );
  }

  public List<Package> getExpoPackages() {
    return Arrays.<Package>asList(
        new CameraPackage(),
        new SensorsPackage(),
        new FileSystemPackage(),
        new FaceDetectorPackage(),
        new GLPackage(),
        new GoogleSignInPackage(),
        new PermissionsPackage(),
        new SMSPackage(),
        new PrintPackage(),
        new ConstantsPackage(),
        new MediaLibraryPackage(),
        new SegmentPackage(),
        new FontLoaderPackage(),
        new LocationPackage(),
        new ContactsPackage(),
        new BarCodeScannerPackage(),
        new AdMobPackage(),
        new LocalAuthenticationPackage(),
        new LocalizationPackage(),
        new AppAuthPackage(),
        new TaskManagerPackage(),
        new BackgroundFetchPackage()
    );
  }

  @Override
  public String gcmSenderId() {
    return getString(R.string.gcm_defaultSenderId);
  }

  @Override
  public boolean shouldUseInternetKernel() {
    return BuildVariantConstants.USE_INTERNET_KERNEL;
  }

  public static OkHttpClient.Builder okHttpClientBuilder(OkHttpClient.Builder builder) {
    // Customize/override OkHttp client here
    return builder;
  }
}

  Expo CLI 2.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4819257

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/expertnetwork-0e68c700-b77f-41ea-a923-da01225696f0.tar.gz

Not working on Android, neither on OSX/Windows.

Simply update the sdk from 27.0.0 to 32.0.0 and voila.

**Comment by cruzach** [comment]
Hey @DubluDD,

This is on an ejected ExpoKit project? In that case I just wanted to make sure that you docs you followed for updating are [these](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit). 

-Charlie

**Comment by DubluDD** [comment]
Hi @cruzach,

You are right, this is an ejected ExpoKit project. I managed to get my apps working again but I can provide feedback, so maybe it will help somebody. This is regarding UPDATING EXPO SDK FOR EJECTED PROJECT FROM 27.0.0 to 32.0.0.

First, for ANDROID, I gave up on trying to respect the steps that you mentioned. I just created a brand new expo project(expo init) + eject(expo eject) with ExpoKit and just COPY+PASTE contents from the android project(/app/build.gradle, /build.gradle, settings.gradle, can t remember all the names but pretty much anything). After the project build I posted this. Found out that the issues were caused by some breaking changes @ fonts, had to use an older version for @expo/fonts to make it work(also had to change some imports). Finally android worked.

Secondly, for IOS, the steps provided by expo worked fine except that when I tried to 'pod install' I'd get some errors, something like this (No podspec found for `EXCamera` in `../node_modules/expo/node_modules/expo-camera/ios`). I manged to fix this by
 manually 'npm install <MissingPackage>@3.0.0'(Ex: npm i EXCamera@3.0.0) by default these were installed @4.0.0 but that didn t work with pod install.

I m sorry I can't provide more accurately steps that I followed.

So, I d recommend to further document the breaking changes and just get this process together because it s not an exaggeration to say it is a mess.

**Comment by cruzach** [comment]
Hey @DubluDD thanks for the feedback, sorry I'm just getting around to responding. We realize that the ExpoKit workflow does have its difficulties, so we have been hard at work this year on creating the bare workflow for developers, like yourself, who need more customization and control over the native code.

As for the versioning issue, we've since released the `expo install` command, which will look at your project and automatically install the best version of that expo package for you!
