### ISSUE TITLE
YUV to NV21 does not work well on XiaoMi 9

### ISSUE THREAD

**Issue by JoyHong** [expo/expo#3908]
Hi

I use CameraView module in my project. i open the scanning mode, it works ok on most devices, but on XiaoMi 9, the preview color is wrong, could u help to fix it?

**Comment by JoyHong** [comment]
Seems that
YUV_420_888 convert to NV21, the U and V is reversed

**Comment by tsapeta** [comment]
As this issue is pretty old and there hasn't been any activity here and we haven't received similar reports, I'm closing it but please give us a feedback here if it's still bothering you 🙂
