### ISSUE TITLE
Can't run IOS after expo eject, see only white screen, how to make it work?

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#3909]
### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.2.1 => 3.2.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

IOS, ExpoKit

### Steps to Reproduce

I did expo eject, after that I installed pods, now I want to run app through Xcode, Xcode builds app and I see only white screen and error in Xcode: 

> "libc++abi.dylib: terminating with uncaught exception of type NSException"

### Expected Behavior

I expect that app will work normally just like it was before expo eject 

### Actual Behavior

Nothing works, I see only white screen, error in Xcode and nothing is happening  

### Reproducible Demo

Do expo eject
Dp Pod install 
Face the problem in IOS 

P.S: I downgraded cocoapods to 1.5.3, I have already saw thread in expo forum related to that issue, but didn't find any useful information there: https://forums.expo.io/t/new-project-ejected-stuck-in-spashscreen/19458/4

**Comment by cruzach** [comment]
Hey @Luckygirlllll,

In your forum post, it seems that you were still using Cocoapods 1.7.0

Can you verify that you're running this with Cocoapods v1.5.3? I followed your steps to reproduce, but it worked fine for me. You can follow the steps [here](https://forums.expo.io/t/getting-issue-while-run-pod-install/19134/8?u=charliecruzan) to downgrade. Then re-run and re-build 

Let me know if that fixes it!
-Charlie

**Comment by Luckygirlllll** [comment]
@cruzach I have already downgraded cocoapods, the problem actually was not in the version of cocoapods, because I saw white screen even after the downgrading version, but I guess the problem was that I didn't run expo start before doing pod install. I
