### ISSUE TITLE
Downloading AppImage/exe takes forever 

### ISSUE THREAD

**Issue by mikolajadamowicz** [expo/expo#391]
Whenever i try to download installer it takes roughly 3h to download with speed dropping from 50kb/s to 20 kb/s. Tested on win 10 and ubuntu on different PCs and different network connections.

**Comment by dikaiosune** [comment]
Hi! Where are you located? The XDE AppImage is served from GitHub's CDN, so I suspect some networking issue is at play here.

**Comment by mikolajadamowicz** [comment]
Warsaw, Poland also downloading directly from github https://github.com/expo/xde solved the issue for me.

**Comment by dikaiosune** [comment]
Interesting. @jesseruder does the download on our website go through a different CDN than GitHub releases?
