### ISSUE TITLE
[expo-face-detector] Change face detection library to MLKit

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#3910]
Would probably close https://github.com/expo/expo/issues/3888.

**Comment by changLiuUNSW** [comment]
@sjchmiela Is there a workaround or not. My app needs ```react-native-firebase``` for push notification and analytics stuff.
Because my app eject to ```expokit``` and package ```expo``` require ```expo-face-detector```. So when I do ```pod install``` it will install ```EXFaceDetector``` which conflicts with```firebase/core 5.20.1``` (require GoogleUtilities 5.8.0 )

**Comment by sjchmiela** [comment]
At the moment there is no workaround, we are working on upgrading `expo-face-detector` to use MLKit (see https://github.com/expo/expo/pull/4056).

**Comment by nebrasjemel** [comment]
@sjchmiela Thank you guys for tackling this issue. Is there a timeline for when you expect this PR to be merged ? And will you be waiting for SDK 34 to release it or will the package be released as soon as it's merged for people using unimodules ?
