### ISSUE TITLE
RN Maps MapView kmlSrc prop not displaying markers

### ISSUE THREAD

**Issue by chris-poe** [expo/expo#3914]
### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^32.0.6 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.1.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.14.0

Target: iOS & Android

### Steps to Reproduce

1. Create any bare bones Expo project and import `MapView` from Expo
2. Add props `provider="google"` & `kmlSrc="<KML-URL>"`
3. You will notice the marker locations, in this case 3 marks located on the west campus of Google in Mountain View, California, are not displaying.

Attempting to display contents of an official Google KML example file URL:(https://developers.google.com/maps/documentation/javascript/examples/kml/westcampus.kml).

**NOTE:** Using that same URL/KML code on any KML viewer yields the desired results.

### Expected Behavior

Marker locations should be displayed based off of KML source URL provided within `kmlSrc` prop.

### Actual Behavior

Map does not display markers from KML file when provided a URL (sting) as per the react-native-maps `MapView` docs state [here](https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md).

### Reproducible Demo

https://snack.expo.io/@chris-bytelion/a21sc3

**Comment by cruzach** [comment]
Hey @chris-poe,

Thanks for following the issue template! It really helps a lot. 

Unfortunately, adding Markers via kml [isn't possible right now](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#runtime-errors-on-ios-apple-maps), at least for iOS. The Snack you shared works as it should on Android.


@brentvatne [docs](https://docs.expo.io/versions/latest/sdk/map-view/) just point to [react-native-maps](https://github.com/react-native-community/react-native-maps) right now, do you think it's worth fleshing them out on our side or leave it the way it is?

**Comment by chris-poe** [comment]
Hey @cruzach,

It could definitely be worth outlining the props that don't transfer between the base react-native-maps API and Expo's. I do a fair amount of GIS applications with large data sets so knowing this in advance would have helped.

Either way thanks for the quick reply!

**Comment by cruzach** [comment]
Happy to help, but the problem isn't that some of the props don't transfer. Rendering markers from KML files on iOS raises an exception bc it's an advanced feature that depends on the Google Maps SDK for iOS. If you've had trouble using a different prop from react-native-maps, let me know
