### ISSUE TITLE
country code don't match the ISO country code standards.

### ISSUE THREAD

**Issue by unutoiul** [expo/expo#3915]
Example:
```
 "ADP",
"AED",
"AFA"
```
```
Afghanistan | AF | AFG | 4 | 93
Albania | AL | ALB | 8 | 355
Algeria | DZ | DZA | 12 | 213
```

**Comment by cruzach** [comment]
I think the codes you have in your example are from the [isoCurrencyCodes](https://docs.expo.io/versions/latest/sdk/localization/#localizationisocurrencycodes-arraystring), the country code returns just one, not a full list of all of them. 

You can see this [snack](https://snack.expo.io/@charliecruzan/localizationtest) for example. 

ref: [Currency Codes Wikipedia Page](https://en.wikipedia.org/wiki/ISO_4217#Active_codes)

Closing this for now, if I misunderstood the issue just let me know
