### ISSUE TITLE
Attempting to call Js function on a bad application bundle

### ISSUE THREAD

**Issue by dajohnny** [expo/expo#3916]
Hi, All!

The local environment debugging is normal, but after packaging, very few user feedback has made a mistake. Can I know if this is caused by something?

![image](https://user-images.githubusercontent.com/17939743/55451925-4f7b1a80-55ff-11e9-8def-910cc45d410f.png)

The last packing time was 5:30 on March 30th, Beijing time.

https://status.expo.io/incidents/mk8q30ybv8nc.

**Comment by cruzach** [comment]
Hey @dajohnny, 

Did you already try making any change and then re-publishing, as per the link you posted? If it's not possible to make a whitespace change to your bundle, republish anyway and email us at secure@expo.io with your username and app slug (as per [this reply](https://github.com/expo/expo/issues/3902#issuecomment-478294671) )

Same as #3902
