### ISSUE TITLE
Implicit declaration of function 'RCTAssertMainThread' is invalid in C99

### ISSUE THREAD

**Issue by NunoCardoso** [expo/expo#392]
Hi. 

I have a detached react-native project that has react-native-i18n dependency.

I can't compile on XCode because of this error. 

I have CocoaPods 1.2.1. I upgraded the ExpoKit to 1.18.1. 

The error starts on the EXFrame.m

**Comment by terribleben** [comment]
Hi, seems like for whatever reason your project can't find some of the react native files, including (in this case `RCTAssert.h`. Couple things:

- We already support [everything from react-native-i18n](https://docs.expo.io/versions/v18.0.0/sdk/util.html) without detaching, as far as I know, so you may not need to detach if that's your only dependency.
- What does your `package.json` dependency on `react-native` look like? And what does `../node_modules/react-native/package.json` say for its version?

**Comment by NunoCardoso** [comment]
Hi, thanks for the quick answer. 

My react-native dependence is the expo's github URL, version 1000.

**Comment by terribleben** [comment]
Are you on Expo SDK 18? For SDK 18, I would expect the following:

- Your project's `package.json` to say something like this: `"react-native": "https://github.com/expo/react-native#sdk-18.0.0"`
- `your-project/node_modules/react-native/package.json` to say: `"version": "0.45.1"`
- The contents of `your-project/ios/Podfile` to contain this:
```
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/1.17.1",
    :subspecs => [
      "Core",
      "CPP"
    ]
```

If those don't look the same as yours (and you're on SDK 18), can you try fixing them, then re-running `npm install` and `pod install`?

**Comment by terribleben** [comment]
I think the problem would be solved by sanity-checking the react native dependency as recommended. Let me know if you're still having issues.

**Comment by NunoCardoso** [comment]
Hi, thank you all for you support.
I manager to understand what is the problem, so I will share it because it might help somebody else.

I was adding to the headers path $(SRCROOT)../../iOS/Pods/Headers/Public, but for some libraries, the path might be ../../../ or even ../../../../, depending on how deep is the library located inside the node_module, so please check that.

**Comment by doc-phily** [comment]
I have this same issue, I've detached from expo so that I can use react-native-firebase to make use of the new firestore database which is not supported yet in expo. When I try to build using xcode I get the error `Implicit declaration of function 'RCTAssertMainThread' is invalid in C99`, anybody know how I can resolve this?

**Comment by Quixotical** [comment]
I'm also having this same issue @doc-phily

**Comment by joshmello** [comment]
Same as @Quixotical

**Comment by visylvius** [comment]
same as @Quixotical

**Comment by ide** [comment]
Where is the call to `RCTAssertMainThread`? This macro/function doesn't exist in React Native anymore. It's now `RCTAssertMainQueue`.
