### ISSUE TITLE
[docs] exponent-server-sdk-python Documentation link is broken

### ISSUE THREAD

**Issue by amrlsayed** [expo/expo#3920]
Hi,
I am using [exponent-server-sdk-python](https://github.com/expo/expo-server-sdk-python)
On the readme file, there's a link for the Full documentation for the API's and the [link](https://docs.expo.io/versions/latest/guides/push-notifications.html#http2-api) is broken.

Thanks,

**Comment by antgel** [comment]
@amrlsayed Suggest expanding the issue title to be more helpful for the casual browser. Also, perhaps just submit a PR? It sounds quite simple.

**Comment by amrlsayed** [comment]
@antgel Thank you I edited the title, For the PR I do not have the link for that exponent-server-sdk-python documentation to suggest an edit.

**Comment by cruzach** [comment]
@amrlsayed thanks for pointing this out! Link should work properly now 👍 
- Charlie
