### ISSUE TITLE
(Android) Question about OkHttp client usage in FileSystem

### ISSUE THREAD

**Issue by ihavenoface5** [expo/expo#3923]
While looking over FileSystemModule.java I noticed that network requests are creating a new HTTP client per each request. Would you be open to a pull request where I implemented a shared client for all network requests? The OkHttp documentation indicates this is the ideal implementation.

Source: https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html

>OkHttpClients should be shared

>OkHttp performs best when you create a single OkHttpClient instance and reuse it for all of your HTTP calls. This is because each client holds its own connection pool and thread pools. Reusing connections and threads reduces latency and saves memory. Conversely, creating a client for each request wastes resources on idle pools.

**Comment by shcheuk** [comment]
It actually caused memory leak, and out of memory crash when downloading 80 + files (depend on device memory). So it is a critical bug. Is it any reason of closing it? Can it be implemented? should I open a new issue or can this be reopened?

`05-09 17:03:32.492: E/AndroidRuntime(7949): FATAL EXCEPTION: OkHttp Dispatcher
05-09 17:03:32.492: E/AndroidRuntime(7949): Process: host.exp.exponent, PID: 7949
05-09 17:03:32.492: E/AndroidRuntime(7949): java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.lang.Thread.nativeCreate(Native Method)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.lang.Thread.start(Thread.java:733)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1038)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1180)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-09 17:03:32.492: E/AndroidRuntime(7949):     at java.lang.Thread.run(Thread.java:764)
05-09 17:03:32.504: E/libc++abi(7949): terminating with uncaught exception of type std::bad_alloc: std::bad_alloc`

**Comment by ihavenoface5** [comment]
I closed it because my understanding of the implementation might be incorrect. Using the Client.builder() methods a client is created that has shared thread and connection pools. I have read other places, however, where people report the client builder not creating a client having shared resources. Are you able to track resource usage and isolate the problems you are having to this library?

**Comment by shcheuk** [comment]
if you do something like the page's example
`public final OkHttpClient client = new OkHttpClient.Builder()`
and then keep reusing it every where in the FileSystem class, then the thread and connection pools will be shared. Client.builder is shared only if you declared it that way and reuse it. Making a new will not
While currently we are doing the oppsite:
```
line 738: private OkHttpClient.Builder getOkHttpClientBuilder() {
    CookieHandler cookieHandler = mModuleRegistry.getModule(CookieHandler.class);
    OkHttpClient.Builder builder = new OkHttpClient.Builder();
     .....
 }
```
and this getOkHttpClientBuilder is called every time downloadAsync is called. Which means new client is created from time to time. 

I did some search on my crash report, it is exactly same as this one https://stackoverflow.com/questions/35701501/throwing-outofmemoryerror-pthread-create-1040kb-stack-failed-try-again-when and the fix it suggest is exactly what we need here, something like:
```

private OkHttpClient client
public void downloadAsync(String url, ....){
...
if (client == null) {
        client =  getOkHttpClientBuilder()
}
...
}

```
