### ISSUE TITLE
can expo open the contacts app of iphone/android and let you select

### ISSUE THREAD

**Issue by unutoiul** [expo/expo#3926]
can expo open the contacts app of iPhone/android and let you select

How is possible achieve this? is nothing in the documentation...

**Comment by cruzach** [comment]
Hey @unutoiul,

Is our [Contacts](https://docs.expo.io/versions/latest/sdk/contacts/) API what you're looking for?

Sidenote: we try to keep github issues for bug reports, so questions like this really belong at the [Expo Forums](https://forums.expo.io/). I'm going to close this for now, but if there is something in our Contacts docs that you think is missing, just let me know what it is and I'd be happy to re-open

Thanks!
Charlie

**Comment by unutoiul** [comment]
Hi Charlie,

The issue is I can see the file ContactScreen in the repo but there is not documentation of API for this file.
