### ISSUE TITLE
[expo-image-manipulator][iOS] Crop fails on SDK32 iPhoneXsMax

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#3929]
### Environment

Expo SDK32 on iOS on `iPhone Xs Max`

### Steps to Reproduce

Launch `ImageManipulator.manipulate` with cropping operation

### Expected Behavior

Crop works just fine and returns valid cropped image.

### Actual Behavior

_https://github.com/expo/expo/issues/3887#issuecomment-478512372_

### Reproducible Demo

Snack: https://snack.expo.io/@barthec/Z2l0aH

_Originally posted by @pontusab in https://github.com/expo/expo/issues/3887#issuecomment-478512372_

**Comment by maxgfr** [comment]
+1

**Comment by dsokal** [comment]
I tried to reproduce this but it works for me. Tested on my iPhone Xs and on iPhone Xs Max simulator and works fine in both cases.
