### ISSUE TITLE
Need Proxy Setting

### ISSUE THREAD

**Issue by EzioKissshot** [expo/expo#393]
Hi, could you add a setting of proxy in Expo?
I faced download error in template project and Android apk upgrade, then I have to mannually download blank-18.0.5.tar.gz, tabs-18.0.5.tar.gz and Exponent-1.18.2.apk, and move them to folder. And everytime upgrade have to repeate this.

**Comment by CrazyWr** [comment]
Chinese? Ha

**Comment by EzioKissshot** [comment]
@CrazyWr Yes :)

**Comment by CrazyWr** [comment]
其实我用VPN了  但是并没有卵用  感觉exp这个服务用不用 VPN 效果都一样  昨天detach的时候  下载iOS Android的文件夹  也是 下了几十遍才下成功挂不挂VPN都一样...

**Comment by EzioKissshot** [comment]
我也用了shadowsocks，没用，开全局也没用。

**Comment by CrazyWr** [comment]
ss 即使全局  终端的请求也不会走代理  
通过其他方式设置了终端走代理 也是没有什么卵用...

**Comment by AlberZ1989** [comment]
I'm chinese and i fixed this issues.
I used proxifier set expo host working through proxy server.Add the expo host list to proxifier rules,i works normal.

My environment:
```
Mac OS 10.12.6
shadowsocksX-ng
proxifier for mac 2.18
``` 

expo xde host list:
```
exp.host
api.segment.io
api.amplitude.com
```

**Comment by AlberZ1989** [comment]
You can also fixed this issues by replace the two places(refer to the arrow in the picture) with fake json which you get from the url.
see #468

**Comment by dikaiosune** [comment]
Hi! I'm really glad you found a workaround for this issue. Unfortunately we're a small team and don't have a lot of resources to dedicate to supporting users in China right now. We plan to revisit this in the future, but for now I'll give this a close as it seems to pertain primarily to people in PRC.

**Comment by ivanzhang** [comment]
@dikaiosune i am in china, i think we still need a solution for us to use proxy while a new installed apk or ipw is lunching, because if the first lunching is too slow, people will leave our app... .

We know china always been effected by GFW,  but we app owners could set up our own proxy server to expo hosts to download scripts faster while lunching app when its new or upgraded.

**Comment by zuoge85** [comment]
gwf blocked  s3.amazonaws.com

i use  proxifier solve


<img width="820" alt="wx20180412-160337 2x" src="https://user-images.githubusercontent.com/8085329/38664071-2e94d29a-3e6b-11e8-9ac6-021d767442ec.png">


[04.12 15:47:11] node - s3.amazonaws.com:443 close, 684 bytes sent, 74287195 bytes (70.8 MB) received, lifetime 00:53


@anp I want to add Proxy Setting  Or join the mirrors configuration.
