### ISSUE TITLE
ERROR: The module 'expo-payments-stripe' is an Android project without build variants, and cannot be built.

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#3933]
### Environment

Expo CLI 2.11.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.4.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.11.7

### Steps to Reproduce

Build expo-payments-stripe for android on a fresh ExpoKit detach and follow the instructions here: https://docs.expo.io/versions/latest/sdk/payments/ for android

### Expected Behavior

expo-payments-stripe builds fine on android

### Actual Behavior

ERROR: The module 'expo-payments-stripe' is an Android project without build variants, and cannot be built.

**Comment by cruzach** [comment]
Hey @lightninglu10 ,

This [issue](https://github.com/expo/expo-payments-stripe/issues/1) has the same error message and seemed to fix it by installing expo-core. Does that solve it for you? We may need to update the docs if this is always required.

Thanks!
Charlie

**Comment by lightninglu10** [comment]
expo-core is deprecated isn't it? 

I tried building it with expo-core and it still doesn't work. Not 100% sure what the issue is, but pretty frustrating that it doesn't work. 

Gonna try building tipsi-stripe soon

**Comment by aikhan** [comment]
Same issue did you found a way around it. iOS is working for me fine, error is on Android.

How did Tipsi-stripe work out for you?

**Comment by lightninglu10** [comment]
@aikhan what sdk are you using? It's pretty finnacky but in expo33 expo-payments-stripe at 5.1.0 is working for me. I also heard the newest release 6.0.0 should work too.

If you follow these threads you should be able to set it up properly: 
1. https://github.com/expo/expo/issues/3597#issuecomment-470121059
2. https://github.com/expo/expo/issues/5072

**Comment by aikhan** [comment]
Thanks I'll check the threads out.


Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.2

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
