### ISSUE TITLE
AndroidRuntime: java.lang.RuntimeException: Unable to create application host.exp.exponent.MainApplication: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.p

### ISSUE THREAD

**Issue by safciplak** [expo/expo#3934]
Please help me detach project crash i executed
adb logcat com.ciplak.zindertestsafak:V AndroidRuntime:E "*:S"

04-06 12:57:37.546 12383 12383 E AndroidRuntime: FATAL EXCEPTION: main
04-06 12:57:37.546 12383 12383 E AndroidRuntime: Process: com.ciplak.zindertestsafak, PID: 12383
04-06 12:57:37.546 12383 12383 E AndroidRuntime: java.lang.RuntimeException: Unable to create application host.exp.exponent.MainApplication: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.p
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: Caused by: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.p
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at host.exp.exponent.c.a.b(NativeModuleDepsProvider.java:1108)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at host.exp.a.b.<init>(Exponent.java:136)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at host.exp.a.b.a(Exponent.java:117)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at host.exp.exponent.l.onCreate(ExpoApplication.java:75)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
04-06 12:57:37.546 12383 12383 E AndroidRuntime: 	... 8 more

**Comment by cruzach** [comment]
Hey @safciplak ,

Please follow the issue template, it asks for a lot of the information we need to help you. (Specifically, a way to reproduce the issue and/or a step by step walkthrough of how you arrived at the problem).

-Charlie

**Comment by safciplak** [comment]
I found a solution
android/app/build.gradle buildTypes { debug { debuggable true ext.enableCrashlytics = false } release { minifyEnabled true proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' zipAlignEnabled true } } 


under release replece with release { debuggable false } 


./apktool d zinder.apk && ./apktool b zinder -o x.apk && jarsigner -verbose -tsa timestamp.digicert.com -sigalg SHA1withRSA -digestalg SHA1 -keystore zinderlastfriday last_zinder.apk zinder && ./zipalign -f -v 4 x.apk xa.apk

**Comment by cruzach** [comment]
Glad you were able to fix it 👍

**Comment by abowerman** [comment]
That doesn't look like a fix, just a workaround. Am seeing this issue too.

**Comment by tncbbthositg** [comment]
@safciplak, are you saying you stopped using proguard and it started working again?  

I'm having a similar problem.  I'm waiting for more crash reports, but when I look at the mappings, it looks like mine is related to `host.exp.exponent.ExponentManifest`.
