### ISSUE TITLE
[iOS][bare][expo-blur] BlurView not blurring in bare project

### ISSUE THREAD

**Issue by redpandatronicsuk** [expo/expo#3935]
## 🐛 Bug Report
I migrated my project from ExpoKit to bare. Now BlurView no longer blurs.
### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.1/bin/npm
      Watchman: 4.9.4 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.6 => 0.58.6
      react-navigation: 3.3.2 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.14.0

This bug is only on iOS, as BlurView only works on iOS.

### Steps to Reproduce

Clone this repo: `https://github.com/invertase/react-native-firebase-starter/` => configure project => add `react-native-unimodules` dependency and `expo-blur`.

### Expected Behavior

Stuff behind `BlurView` get's blurred.

### Actual Behavior

It is behaving like a normal `View`.

### Reproducible Demo
The demo is not initialised from the `rb-firebase-starter`, but instead with `expo init --template bare-minimum`. The issue can also be seen there.

https://github.com/redpandatronicsuk/expo-blur-view-issue-demo

**Comment by redpandatronicsuk** [comment]
I saw this error printed in the XCode console:
```
Accessing view manager configs directly off UIManager via UIManager['ViewManagerAdapter_ExpoBlurView'] is no longer supported. Use UIManager.getViewManagerConfig('ViewManagerAdapter_ExpoBlurView') instead.
```

So changed line 32 in `node_modules/@unimodules/react-native-adapter/build/NativeViewManagerAdapter.js` from
```
const reactNativeUIConfiguration = UIManager[reactNativeViewName] || {
```
to
```
const reactNativeUIConfiguration = reactNativeViewName === 'ViewManagerAdapter_ExpoBlurView' ? UIManager.getViewManagerConfig(reactNativeViewName) : UIManager[reactNativeViewName] || {
```
the warning disappeared, but it didn't fix the problem.

**Comment by johnanthonyeletto** [comment]
Don't want to wait for the release on NPM? I downloaded the [Expo Blur Package](https://github.com/expo/expo/tree/master/packages/expo-blur) and linked it locally in package.json like this:
`"expo-blur": "file:<path_to_local_expo-blur>"`
