### ISSUE TITLE
fbbatchedbridge is undefined

### ISSUE THREAD

**Issue by Stophface** [expo/expo#394]
I am working with Expo XDE (2.19.2) and Xcode 8.3.3

- I created a new Project with Expo (the one with the NavBar, Development Mode on) 
- Then I send that one to the iOs simulator. Works perfectly. 
- I edited the code produced an error on purpose (i.e. delete a `{`)
- I get a proper error message in the Simulator
- I remove the error and save -> the App reloads and all good.
- I then open in the simulator "Remote JS Debugging"
- Chrome opens
- I then produce the same error
- I get an error message in the simulator, but *not* in the Chrome console.
- I remove the error, save and then I get the error `fbbatchedbridge is undefined`

That error does not got away. Even when I restart the project, I still get that error. I have to newly create a project to get rid of the error....

I tried commenting out the lines (as suggested here: https://github.com/facebook/react-native/issues/6282

But that does not do the trick. Still getting the error. 
Whats going wrong?

**Comment by williamwlchan** [comment]
Same here. Every time when I do Remote JS Debugging, I get this error on my iOS simulator. If I do not do Debugging, it is fine.

**Comment by Oleg24** [comment]
I get this same bug as well, it's pretty dang annoying. The only thing that's helped is restarting my mac.

**Comment by javidjamae** [comment]
+1

**Comment by williamwlchan** [comment]
@Oleg24 Can you use Remote JS Debugging after you resetting the simulator and re-installing expo onto the simulator?

**Comment by terribleben** [comment]
Thanks for the report - we're actively working on this. Closing this issue because it's a [duplicate](https://github.com/expo/expo/issues/321).
