### ISSUE TITLE
Android Build Error: ":expo-core" not found in ":expo-react-native-adapter"

### ISSUE THREAD

**Issue by thlee1122** [expo/expo#3942]
### Environment

Expo CLI 2.10.1 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.10.1

**My app's target is Android**

### Steps to Reproduce
When I try to build my app in the Android Studio, I get below error.
`Project with path ':expo-core' could not be found in project ':expo-react-native-adapter'.`
in "android/build.gradle".

Does anyone know how to fix this issue?

**Comment by cruzach** [comment]
Hey @thlee1122,

This is an ejected Expokit project, correct? 
Also, what version of the Expo SDK are you using and did you recently upgrade that version? It would help if you provided a way to reproduce the error you're getting

Thanks!
-Charlie

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.

**Comment by linus** [comment]
It seems in my case I had an outdated dependency on `expo-react-native-adapter`, which was added when upgrading to Expo 34. It seems as if this has been subsumed by `react-native-unimodules`, and seems to work after removing.
