### ISSUE TITLE
Local notifications work until standalone ios builds in testflight

### ISSUE THREAD

**Issue by spacemonkey** [expo/expo#3944]
### Environment

```
  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.0.3 - /usr/local/bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.1 
      react: ^16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.14.0
```

This app is being built for ios with `expo build:ios --clear-push-cert`, with both testing and production certs setup and added to apple developer account for this app.

### Steps to Reproduce

1. Create a standard expo app
2. Add a local notification (say 10 seconds in the future) [like this](https://gist.github.com/spacemonkey/effb9b140cc7d45f040e4c955fc3f563)
3. Test app locally with `expo start` and expo client on device by viewing screen that sets notification, kill app (long swipe on iPhone X) and wait for ten seconds
4. Build standalone binary with `expo build:ios --clear-push-cert`
5. Be sure to provision keys through expo, but also setup certificates for Apple Developer portal and xcode
6. Upload to TestFlight
7. Run local native TestFlight application, repeat above exercise (load screen that sets notification, kill app, wait ten seconds

### Expected Behavior

I expected the local native app to be able to fire the notification with the app in the background, just like when running through expo client.

### Actual Behavior

When I follow the exact same process as from using expo client, the notification never happens. I checked in the TestFlight app to be sure notifications were enabled (true), but no luck. The rest of the app works exactly as intended.

### Reproducible Demo

- https://github.com/spacemonkey/expo-test

I know this is all based on once standalone binaries are built, which is why I didn't just create a snack. Please let me know if there's anything I can do to demonstrate, or provide more helpful information to figure this out.

**Comment by spectre3ooo** [comment]
I'm having the same issue.

**Comment by briansztamfater** [comment]
Are Push Notifications enabled on your App ID and Provisioning Profile? If not, try enabling it, and rebuild your app with `expo build:ios -c`

**Comment by spacemonkey** [comment]
Well thanks @briansztamfater for the `-c`, ended up blowing out my whole Apple developer setup! ;-)

Redid the entire build, same results though. I let expo do all the provisioning, blew out all of my existing certs and so on.

Is there any other information I can share to help figure this out?

**Comment by spectre3ooo** [comment]
That worked for me, @briansztamfater.  I had enabled push notifications in my app id after the distribution profile was created, so the profile was showing as invalid.  It worked after I regenerated the profile.

**Comment by spacemonkey** [comment]
I have my App Id configured thusly, do I need to go through the upload certs process again?

<img width="735" alt="screenshot_37" src="https://user-images.githubusercontent.com/93724/55730913-39969c80-59e7-11e9-8272-54738a7dcc55.png">

**Comment by spacemonkey** [comment]
Just ran another build to be sure, my provisioning profile (as created by expo) says:

```
Enabled Services:
    Game Center, In-App Purchase, Push Notifications
```

What am I missing?

**Comment by cruzach** [comment]
Hey @spacemonkey,

Could you try sending a notification to the device through Expo's [Push Notification Tool](https://expo.io/dashboard/notifications) and see if that works? Grabbing the [push receipt](https://docs.expo.io/versions/latest/guides/push-notifications/#push-receipts) for it should give you a lot more information about the what error you might be getting.

Thanks!
-Charlie

**Comment by spacemonkey** [comment]
Thanks for the pointer to the push notification tool @cruzach! 

I'm using a local notification though, by calling `Notifications.scheduleLocalNotificationAsync()` and setting the notification to fire ten seconds in the future. How am I supposed to test a local notification from a push notification tool?

**Comment by cruzach** [comment]
Yeah I saw that, my bad I should've been clearer- I'm suggesting you set up the app for receiving a regular old push notification. (There's a simple app at the [examples repo](https://github.com/expo/examples) that shows how to do this) Then, use the tool I linked and the receipt will give us a better pointer as to what's going on

**Comment by spacemonkey** [comment]
Ahh I got you - thanks for clarifying. I'll give that a shot and report back.

**Comment by spacemonkey** [comment]
Looks like I'm missing something on the config side, as I cannot find my app in Settings::Notifications on iOS.

**Comment by salman90** [comment]
@spacemonkey I can't also find my app in Settings::Notifications on iOS. Did you find a solution?

**Comment by monceeef** [comment]
Any news about this ? I cannot get the expo push token once the standalone app is build with expo

**Comment by cruzach** [comment]
@monceeef could you check your [Push Receipts](https://docs.expo.io/versions/latest/guides/push-notifications/#receipt-response-format) and see what the error (if there is one) is?

If it was working in the Expo Client app, then this most likely has to do with your credentials

-Charlie

**Comment by spacemonkey** [comment]
My notifications are local only, effectively a reminder ten seconds into the future. They fire locally, they fire through the expo client, but once I build iOS for TestFlight they go silent. I must be missing a setup requirement for notifications to work, and I'm blocking off time to try again tonight.

**Comment by cruzach** [comment]
Yup understood, the reason I ask for a Push Notification is that the error returned might shed some light on the underlying issue.

When you build the IPA, are you letting Expo handle certs @spacemonkey ?

**Comment by HazT** [comment]
I`m having the same issue for iOS test flight app build but notification works fine in development iOS build with expo client. Did anyone know a solution for this issue?

**Comment by cruzach** [comment]
This is most likely due to an issue with credentials. @HazT did you let Expo handle push certs? Can you test sending a push notification to see if there's an error returned with details? (See our [Push Notification docs](https://docs.expo.io/versions/latest/guides/push-notifications/) for more info on those errors/causes )

**Comment by HazT** [comment]
I had tried with both way, to handle certs by expo and also manually but does not receiving push notification in test flight iOS app build.

**Comment by cruzach** [comment]
Any specific errors you receive when trying to send notifications to those devices? It's pretty tough to debug without more information. [This forum post](https://forums.expo.io/t/unable-to-receive-notifications-on-testflight-error-stream-ended-unexpectedly/13044), for example, provides a good amount of detail!

**Comment by Levilian** [comment]
Same issue here. Notifications.getExpoPushTokenAsync() throws an error and can't proceed.

**Comment by spacemonkey** [comment]
Ok back in the saddle, working on this tonight and will report back here either way.

**Comment by spacemonkey** [comment]
Here's what I got - I finally freed up time (thank you Labor Day!) and got push receipts and all, works just fine locally when running the app from `expo start` and then firing up the expo app on an iphone.

I used the CURL command to send the message, got the notification on my phone, and then got a receipt that had `{"status":"ok"}` in the payload.

Now what?

**Comment by spacemonkey** [comment]
Here's what I got - I finally freed up time (thank you Labor Day!) and got push receipts and all, works just fine locally when running the app from `expo start` and then firing up the expo app on an iphone.

I used the CURL command to send the message, got the notification on my phone, and then got a receipt that had `{"status":"ok"}` in the payload.

Now what?

**Comment by spacemonkey** [comment]
Ok yesterday I walked through the [Push Notifications](https://docs.expo.io/versions/v34.0.0/guides/push-notifications/) docs and re-implemented based on the example provided (`registerForPushNotificationsAsync` function). I pushed up a build for TestFlight, and badda-bing, badda-boom there's a notification waiting for me when I woke up today.

Can't say for sure whether it was docs or just me, but it works now - notification docs for SDK34 are much clearer IMHO.

Thanks to everyone for pitching in, particularly @cruzach for being so patient :-)

**Comment by cruzach** [comment]
Glad you were able to get it working! 😄 

If there's any part of the Notifications docs you think was confusing still, let me know so I can fix it

**Comment by spacemonkey** [comment]
Pretty sure that is what _fixed it_ for me!

For total rookies to react AND react native (such as myself), sometimes it has to be painfully, mind-numbingly spelled out:

1. Create react native app
2. Add logic at the top level to ensure notifications are available
3. Actually do something with notifications

Step 2 was where the wheels fell off for me, thanks for updating the docs!
