### ISSUE TITLE
Local Schedule Notification Throwing Multiple Notifications at Once Instead of Single on Android

### ISSUE THREAD

**Issue by sinansonmez** [expo/expo#3946]
### Environment

I am trying to create water reminder app with notification feature once in every hour. 
I have implemented notifications with scheduleLocalNotificationAsync. My implementation works as expected in IOS but in Android when I open the app, the app sending 12 notifications at the same time instead of sending them one by one at scheduled time.

### Reproducible Demo

My code is below, I didnt create snack because testing notifications is quite hard. 
Maybe you can understand from my code what is wrong with it. If you still need a snack, I can create it. 

```
  componentDidMount = () => {
    this._sendNotifications();
  };

_sendNotifications = async () => {
    // Not to create duplicated notifications first cancel all notifications
    await Notifications.cancelAllScheduledNotificationsAsync();

    // beginning of notification part
    const localnotification = {
      title: 'Water Reminder',
      body: "Don't forget to drink water!",
      android: {
        sound: true,
      },
      ios: {
        sound: true,
      },
    };

    // get the current date
    let currentDate = Date.now();
    currentDate = new Date(currentDate);

    // get the day, month and year from current date to create time to schedule
    let year = currentDate.getFullYear();
    let month = currentDate.getMonth();
    let date = currentDate.getDate();

    // then create unix epoch number for eact date with number from notification section
    // then we call notification function with each timestamp (not1)
    if (this.state.switchStatus === false) {
      await Notifications.cancelAllScheduledNotificationsAsync();
    } else {
      // Notification for nine
      if (this.state.otherSwitchStatus.nine === true) {
        let not0 = new Date(year, month, date, 9);
        not0 = Date.parse(not0);
        const schedulingOptions0 = { time: not0, repeat: 'day' };
        // call the function to send notification at 9:00
        await Notifications.scheduleLocalNotificationAsync(localnotification, schedulingOptions0);
      }

      // Notification for ten
      if (this.state.otherSwitchStatus.ten === true) {
        let not1 = new Date(year, month, date, 10);
        not1 = Date.parse(not1);
        const schedulingOptions1 = { time: not1, repeat: 'day' };
        // call the function to send notification at 10:00
        await Notifications.scheduleLocalNotificationAsync(localnotification, schedulingOptions1);
      }
}
```

**Comment by Szymon20000** [comment]
I tried to schedule local notifications on Android 9 and 6.0.1. Everything was fine. Could you describe exact steps to reproduce the issue?

**Comment by sinansonmez** [comment]
I am trying to build a water reminder app. I have 3 screens and I am using react-navigation

- Home (that I allow users to increase their amount drink that day and display how much water they drunk)

- Notifications (where users defining with switch buttons if they want to receive notifications and when to receive)

- Settings (where the user enters age, weight to determine how much they should drink daily). this is the first screen users see when they downloaded the app


The issue is when I open the app and click notifications screen and put the app to background and I receive 11 notifications immediately. I have observed it couple days and saw that actually rest of notifications are working accordingly. If open the app once again and click notification screens I receive another 11 notifications immediately. 

I have tried with specs below. Please let me know if you need any other information?
Android: 9 and Q
expo: ^32.0.0
react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz

**Comment by sinansonmez** [comment]
@Szymon20000 I guess I understand what is going on with the code. 

Since as you can see in my code, independent of current time of the day, I am calling scheduleLocalNotificationAsync for 15 times (starting from 09:00 to 23:00, with daily repeat option). However when I open Notification screen at 12:40 I receive 4 notifications immediately (for one each 09:00, 10:00, 11:00 and 12:00). 

I guess expo immediately calling notification function for 4 passed times. This is not the case for ios but it is happening in Android. I guess it needs to be fixed in expo side and I need to manage my code dynamically until it is fixed in expo side.

**Comment by bulby97** [comment]
@sinansonmez  Are your notifications working when your app is closed ? My notifications work only on foreground and background, not when the app is closed. 

Am I missing something ?

**Comment by leandrorovagnoli** [comment]
Same here! Any solution?

**Comment by sinansonmez** [comment]
> @sinansonmez Are your notifications working when your app is closed ? My notifications work only on foreground and background, not when the app is closed.
> 
> Am I missing something ?

yeah it is working even the app is closed

**Comment by sinansonmez** [comment]
> Same here! Any solution?

Please read my previous reply and you can find the solution. 
https://github.com/expo/expo/issues/3946#issuecomment-482939436

What I did here is that first check the current time, if current time is 12:40 
- I schedule alarms after 12:40 (13:00, 14:00, 15:00 etc.) for the same day with repeating daily  
- I schedule alarms before 12:40 (12:00, 11:00, 10:00 etc.) for tomorrow with repeating daily again. You can find the sample code below
```
let hour = currentDate.getHours();
// I changed the code below
// let not0 = new Date(year, month, date, 9) // alarms after 12:40
// to this
let not0 = new Date(year, month, hour > 9 ? date + 1 : date, 9); // alarms before 12:40
```

**Comment by vlastikczech** [comment]
Hey @sinansonmez!

Does it still send you multiple notifications when you reopen the application? I'm running into a similar issue. In my application if I schedule notifications for 11:30am, 1:30pm, 3:30pm at 8am and then close the application. If I open the application at 5pm i'll instantly get 3 notifications right away.

**Comment by sinansonmez** [comment]
@vlastikczech Please read my previous answer for a workaround solution

**Comment by cruzach** [comment]
It looks like this was fixed in the new `expo-notifications` module! 🎉 

Here's the code I used to test this, make sure you're using Expo SDK 38, and have installed the new module with `expo install expo-notifications`: https://snack.expo.io/@charliecruzan/notifications3946

If you're still seeing this bug, please let me know and I can reopen the issue

**Comment by ljcp** [comment]
we are  still having this problem with Expo SDK 52 and expo-notifications 29.
It only happens on Android — iOS works fine.
When the app starts, all the scheduled notifications show up right away instead of at the right time.
I already make sure to cancel old notifications before scheduling new ones.
No errors or warnings in the logs.
Let me know if you want a small test project to show the issue. Thanks!
