### ISSUE TITLE
Unable to resolve module 'scheduler/tracing'

### ISSUE THREAD

**Issue by impactcolor** [expo/expo#3949]
This error has been reported in React-Native around September of 18 but all I've read doesn't show anything about Expo.  

The exact error is "Unable to resolve module 'scheduler/tracing' from '.../ReactNativeRenderer-dev.js': Module 'scheduler/tracing' does not exist in the Haste module map.
I've tried the 4 fixes it outlines and nothing.

I installed "@babel/runtime": "7.0.0" & "schedule": "0.5.0" as suggested in other places.

Here is my package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@babel/runtime": "7.0.0",
    "expo": "^32.0.0",
    "native-base": "^2.12.1",
    "react": "16.5.0",
    "react-native": "^0.59.3",
    "schedule": "0.5.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

```

**Comment by cruzach** [comment]
Hey @impactcolor,

Could you provide a way for us to reproduce this issue? And provide your environment info as well (run `expo diagnostics`)

This is all in the issue template, so following that is always the best way to get these issues resolved quickly 👍 

Thanks!
-Charlie

**Comment by impactcolor** [comment]
Hi I'm sorry for not adding it here goes:

  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.2.0 - ~/.nvm/versions/node/v10.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: ^0.59.3 => 0.59.3 
    npmGlobalPackages:
      expo-cli: 2.14.0

**Comment by impactcolor** [comment]
According to this stack questions: https://stackoverflow.com/questions/52817118/module-schedule-tracking-does-not-exist-in-the-haste-module-map

It's because of the version of react with react-native.  Thank you!
