### ISSUE TITLE
Latest version of Expo app (1.18.x) crashes on Android emulator 4.4.4, 5.0, 5.1.1

### ISSUE THREAD

**Issue by aaymont** [expo/expo#395]
The latest version of the Expo app for Android (version 1.18.2) crashes under the Android emulator.

I have tried it on Android API level 22 (5.1.1), 20 (5.0), and 19 (4.4).

I have done full resets on all versions of the emulator and the result is the same.

The application briefly flashes on the screen then crashes.  This was not an issue in previous version.

The app does still appear to work on an actual device (Android 7.0), but not in the emulator.

![expo-crash](https://user-images.githubusercontent.com/5459780/28466652-b4218aec-6df2-11e7-974d-4d9faf1c272d.png)

**Comment by WeaVaer** [comment]
+1
I have the same issue but on a physical device.
Expo client was working happily on my Samsung Galaxy Note (android 4.4) until I see the dreaded 'updating' sign for Expo client today and ...
Wham! 
it doesnt work anymore.

New updated Expo client just keeps stopping when I try to launch it, whilst it works on ios.
I have tried to uninstall it, clear app data and cache, reinstall but it doesnt work.

My work is clearly disrupted and I'm feeling bad about this.

**Comment by jpodeszwik** [comment]
+1
I have the same problem on myPhone Hammer Axe LTE (android 4.4.4)
expo version 1.18.2

**Comment by giautm** [comment]
I guys, that issues have been reported and they fixed on same day. Try update Expo client and run again.

**Comment by htala** [comment]
I have the same problem

**Comment by WeaVaer** [comment]
I have updated again to 1.18 and immediately crashed when I run Expo client on my Samsung Note 4 (android 4.4.4).
I have reverted back to a downloaded release 1.17 apk and it runs smoothly.
So clearly, nothing has been fixed yet.

**Comment by aaymont** [comment]
> Hi guys, that issues have been reported and they fixed on same day. Try update Expo client and run again.

This does nothing as the latest update (1.18.2) is what broke it.
The only solution I've found, and only fixes it on Android 4.4.4 is to use the 1.17.0 apk.

**Comment by giautm** [comment]
@WeaVaer : Try to run `adb logcat` to see what make your app crash.

**Comment by jesseruder** [comment]
Looking at this today

**Comment by jesseruder** [comment]
@WeaVaer @aaymont can you send your crash logs using `adb logcat? Want to make sure this is all the same crash.

**Comment by jesseruder** [comment]
There's a new apk here: https://d1ahtucjixef4r.cloudfront.net/Exponent-1.18.3.apk
Let me know if that fixes this issue

**Comment by aaymont** [comment]
@jesseruder Here are the logfiles for 4.4.4, 5.0 and 5.1.1.
It appears to work on 4.4.4 again, but does not work on 5.0 or 5.1.1, still seeing the crash.
[android_logs.zip](https://github.com/expo/expo/files/1173137/android_logs.zip)

**Comment by WeaVaer** [comment]
@jesseruder
sorry, couldn't check here last couple of days.

I attempted to download 1.18 expo client to provide some crash logs but the latest client version 1.18.4 seems to be working now on android 4.4.4. Samsung Note 4
:)

**Comment by ide** [comment]
Thanks for the crash logs @aaymont. I found something interesting in them: `Encountered an error connecting to Google Play Services` and `Google Play Store is missing.` which might be one of the sources of crashes.

**Comment by aaymont** [comment]
@ide Well, I would tend to agree, however this is running in an emulator and those things don't come stock in most emus.  It works fine under 4.4.4 emulator though, which also lacks these things.

**Comment by satya164** [comment]
You should flash gapps on the emulator.

**Comment by syssam** [comment]
I also get this problem.How to solve it?
I'm run on Android 7.0(emulator)
exp version:1.19

I'm following below step to create apk.

1. exp init project
2. exp detach
3. https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by dikaiosune** [comment]
@aaymont Expo expects gapps to be available on the emulator, we unfortunately don't have the resources today to build and maintain versions of our native APIs without depending on play services (for example, I believe Location relies on gApps due to a deprecation in Android).

Since it looks like the issues here are due to missing play services, going to give this a close for now. If there's another issue at play, please post back with some more information and I'll reopen. Thanks!
