### ISSUE TITLE
Location.getProviderStatusAsync() Doesn't work with Android

### ISSUE THREAD

**Issue by chinamcafee** [expo/expo#3950]
### Environment
  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.1/9B55 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.14.0

I tried this code https://snack.expo.io/@charliecruzan/get-location-test on my own MacBook, and ran this code on iOS simulator(iOS 11.1), Genymotion simulator(Android 7.0.0), and my phone(OnePlus 5T Android 8.1.0)，IOS simulator works fine as follows:
![image](https://user-images.githubusercontent.com/3439961/55779144-498da980-5ad7-11e9-9e07-0a2b01971778.png)

but both Genymotion simulator and my OnePlus 5T doesn't work and can't get any location infos as follows(All permissions are granted):
![image](https://user-images.githubusercontent.com/3439961/55779287-9ec9bb00-5ad7-11e9-9a01-cba77d7fe3e6.png)

I noticed that both Genymotion simulator and my OnePlus 5T doesn't have Google Framework installed, does getProviderStatusAsync need Google Framework installed on Android devices?

**Comment by cruzach** [comment]
Hey @chinamcafee,

We actually recommend and have a [guide](https://docs.expo.io/versions/latest/workflow/android-studio-emulator/) for using the Android Studio Emulator to do Android device testing on your computer. 

Anyways, I just ran the snack you linked through a Pixel 2 and latest OS and it worked, BUT when running on a Pixel with Android 7.1.1 Nougat, I had the same output as you. @tsapeta might be able to answer if it's because of a need of Google Framework.

Thanks for bringing this up,
-Charlie

**Comment by tsapeta** [comment]
Hey,
*Google Framework* - do you mean *Google Play Services*? Actually almost all devices have them installed, maybe except Kindle devices or sth. They are required for location module to work properly, but `getProviderStatusAsync` doesn't need them, it's just checking whether any location provider (GPS or network) is available.

**Comment by chinamcafee** [comment]
@tsapeta Thanks for your reply, without VPN, Google Play Services can't work well in China，so Google Play Services don't preinstalled in all devices which sold in China, including Samsung, Huawei, HTC, Xiaomi, etc. For example, GMS doesn't available in China too, so Expo Push API can't work. Since getProviderStatusAsync doesn't need Google Play Services, I'll try my best figure out why this API can't work in my Android devices and emulator, although I have no idea about it now, any suggestion would be appreciated.

**Comment by chinamcafee** [comment]
I have tried this code https://github.com/expo/expo/blob/master/apps/native-component-list/screens/Location/LocationScreen.js on  Android Studio Emulator with the version of Android 9.0, 8.1, 7.0. Finally I found that only Android 9.0 does work.
![image](https://user-images.githubusercontent.com/3439961/55935119-5c35e900-5c65-11e9-954a-a7062195f3d1.png)

I doubt if this API only work fine with the lastest version of Android. Please check it, thanks.

@cruzach @tsapeta

**Comment by Husbin** [comment]
same here, my device is Xiaomi9, android version is 9, can't use location, can't get location info, anybody help?
