### ISSUE TITLE
Authsession with additional embedded SSO Webviews

### ISSUE THREAD

**Issue by flex79** [expo/expo#3951]
Hello,

I was wondering is there is a solution for getting Webviews in a React native app to work using the same SSO session started by Authsession (which uses Webbrowser). 

It seems that Webbrowser and Webview don't share context. We are building an app that uses Auth0  for logging in and in the app itself there are several embedded Webviews that are also using  the same SSO provider. 

One solution I came across described here [https://stackoverflow.com/questions/47340210/webview-should-use-same-cookies-as-fetch]

This tries to inject Javascript into the Webview and recreate a cookie, but this seems like a hack and Apple will probably reject this if this even works with SSO cookies.

Any thoughts on this are appreciated.

**Comment by AdamJNavarro** [comment]
Hey @flex79,

We prefer to reserve github issues for clearly defined and reproducible bugs and I noticed you have created a [forum post](https://forums.expo.io/t/expo-authsession-with-additional-embedded-sso-webviews/21449) so we'll continue discussions there!

Cheers,
Adam
