### ISSUE TITLE
Expo sdk: "32" IOS, Standalone, Expo.Notifications.getExpoPushTokenAsync() never returns.

### ISSUE THREAD

**Issue by MagdyMedhat** [expo/expo#3957]
"sdkVersion": "32.0.0" the token on IOS standalone app never come from
const token = await Notifications.getExpoPushTokenAsync();

it works fine for IOS on Expo client.
it works fine for Android all versions.

problem is only on IOS standalone apps ..

**Comment by cruzach** [comment]
Hi @MagdyMedhat,

Please follow the issue template, it will help you provide all the information we need to resolve this issue as fast as we can 😄 

Thanks!
Charlie

**Comment by dylanbathurst** [comment]
## 🐛 Bug Report

### Environment

  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.14.0



### Steps to Reproduce
1. expo init new app
1. follow main push notification instructions here https://docs.expo.io/versions/v32.0.0/guides/push-notifications/ (works fine in expo app)
1. Create standalone app and distribute to testflight using iOS push key instead of p12 cert. 
1. Accept request for push notification permissions.
1. `Permissions.askAsync(...)` returns "undetermined.
1. `Notifications.getExpoPushTokenAsync()` throws error 
![Image from iOS (1)](https://user-images.githubusercontent.com/43463/55939466-a631b700-5bf2-11e9-93b6-1c94a1e38b7c.png)

![Image from iOS](https://user-images.githubusercontent.com/43463/55939415-84383480-5bf2-11e9-91a8-b3b299820090.png)



### Expected Behavior

I expect it to give me an expo push token like it did in the expo app

### Actual Behavior

Even when the push permission is accepted, the `askAsync` method returns 'unrecognized'

**Comment by MagdyMedhat** [comment]
This is exactly what is happening for me as well!

**Comment by cruzach** [comment]
@dylanbathurst and @MagdyMedhat ,

Could you use [`getAsync`](https://docs.expo.io/versions/latest/sdk/permissions/#permissionsgetasyncpermissiontypes) to check if the app has permission? Don't think the issue is with `getExpoPushToken` since it doesn't look like the app has the appropriate permissions atm

**Comment by dylanbathurst** [comment]
Oh I have many times, lol. I just get the status back as `undetermined`. In this example both `getAsync` and `askAsync` just alert `undetermined`
```
        const { status: existingStatus } = await Permissions.getAsync(
          Permissions.NOTIFICATIONS
        );

        alert('getAsync: ' + existingStatus);

        if (existingStatus !== 'granted') {
          const { status: askingStatus } = await Permissions.askAsync(
            Permissions.NOTIFICATIONS
          );

          alert('askAsync: ' + askingStatus);
        }
```

**Comment by dylanbathurst** [comment]
I added in `Permissions.CALENDAR` and `Permissions.CONTACTS` just to see if they were working properly and they are after I alert "status, expires, permissions". I accepted the permission for each of the three prompts. The screenshot shows `askAsync` but `getAsync` shows the same info after I've accepted the permission prompts.
 
![IMG_BB0CEC73A64F-1](https://user-images.githubusercontent.com/43463/56003336-079d6880-5c7b-11e9-8517-c1926512bc8f.jpeg)

**Comment by MagdyMedhat** [comment]
happens exactly the same to me .. i get permission first then ask for it and i still get undetermined from both and thats only happening to  Expo.Permissions.NOTIFICATIONS
all other permissions are ok.

**Comment by MagdyMedhat** [comment]
@dylanbathurst, @cruzach

i found this link, currently validating if thats my case:

https://forums.expo.io/t/ios-push-notification-permission-status-undetermined/19395

**Comment by MagdyMedhat** [comment]
Yes it works .. giving the App ID push notification permissions and re importing the certificates in the build works :+1:

**Comment by dylanbathurst** [comment]
@MagdyMedhat to get it working did you recreate the Distribution Certificate (.p12 file), Push notifications key (.p8 file), and the Provisioning Profile (.mobileprovision file) and then upload them to expo manually by running `expo build:ios --clear-credentials` I think I'm still missing a piece.

**Comment by HOllarves** [comment]
Having the same issue and wondering the same as @dylanbathurst. I tried enabling Push Notifications in my AppID configuration (leaving it as configurable), and then I did `expo fetch:ios:certs` and then `expo build:ios -c` reimporting the same files given by the previous commands.

It is still not working.

**Comment by MagdyMedhat** [comment]
@dylanbathurst  sorry i didnt get a notifcation so i missed your comment.

@HOllarves, enable the app ID push notificaiton permission, then go delete the certificates and make expo create the certificates for you.

**Comment by HOllarves** [comment]
@MagdyMedhat when you say enable, you mean leaving it as configurable? Or actually generating the production certificates?

Cause that will require me to create a CSR file, that will return a .cer file and I don't know what to do with that.

This is my App ID:

<img width="1271" alt="Captura de Pantalla 2019-06-25 a la(s) 2 12 48 p  m" src="https://user-images.githubusercontent.com/10587409/60097367-8a4ea380-9753-11e9-96d6-973dc3c980ae.png">

**Comment by MagdyMedhat** [comment]
Not this page .. you need to go to your  admin account settings and search for the permissions and enable them, I can show you later i'm a bit of a hurry sorry.

**Comment by HOllarves** [comment]
If you could show me I will appreciate a lot. Been trying to fix this for a couple of days now with now avail. Thanks!

**Comment by Tornaldo** [comment]
> Not this page .. you need to go to your admin account settings and search for the permissions and enable them, I can show you later i'm a bit of a hurry sorry.

Can you (or somebody else) show now? I've been stuck on this for a while, and feel confused as to what to do.

**Comment by Shomari** [comment]
@Tornaldo Would you mind writing what specific step you took?  Having the same issue

**Comment by Tornaldo** [comment]
I don't remember exactly, but I think these were some of the things I did:

1) Clicked on the identifier here, and checked the checkmark for enabling notifications (didn't add a certificate): https://developer.apple.com/account/resources/identifiers/
2) Deleted the profile I had here and created a new one: https://developer.apple.com/account/resources/profiles/list
3) Ran “expo build:ios --clear-push-cert” (but my guess is that this wasn't neccecary)
4) Ran "expo build:ios --clear-push-cert"

Best of luck with solving the issue (if you haven't already) :)

**Comment by Tornaldo** [comment]
My comment contained a typo (wrote "--clear-push-cert" instead of "--clear-provisioning-profile" in step 4). Fixed it not. I think it's unlikely, but not impossible, that I while fixing the problem didn't write "--clear-provisioning-profile", but instead wrote "--clear-[something else]".
