### ISSUE TITLE
getExpoPushTokenAsync fails to return from promise on Android with appetize.io

### ISSUE THREAD

**Issue by devlinb** [expo/expo#3959]
### Environment

Android through Appetize.io

### Steps to Reproduce

Visit https://snack.expo.io/@devlinb/broken-getexpopushtokenasync-in-appetize.io
### Expected Behavior

The following is printed in order:

```
ready to get token
Got token ...
```
or

```
ready to get token
exception thrown:...
```

### Actual Behavior

The async function never returns

### Reproducible Demo

Visit https://snack.expo.io/@devlinb/broken-getexpopushtokenasync-in-appetize.io and run on Android

**Comment by cruzach** [comment]
Hey @devlinb,

Are you using a physical device, or trying to run on the Android simulator in Snack? Push notifications require that you use a physical device

**Comment by devlinb** [comment]
> Hey @devlinb,
> 
> Are you using a physical device, or trying to run on the Android simulator in Snack? Push notifications require that you use a physical device

@cruzach 

I am using the simulator in snack, I don't expect that notifications will work, just that getExpoPushTokenAsync will return or throw.
