### ISSUE TITLE
[iOS] Font accessibility scaling not working with custom font

### ISSUE THREAD

**Issue by Palisand** [expo/expo#396]
When using a custom font (loaded via `Expo.Font.loadAsync`) on iOS, it does not scale to respect accessibility settings; a system font must be used instead.

This is not a problem on Android.

**Comment by Palisand** [comment]
@nikki93 Is this looking like it's going to be non-trivial?

**Comment by nikki93** [comment]
Hey sorry for lack of following up on this. Haven't looked into how to implement this yet. Have you happened to try accessibility scaling with custom fonts in a pure React Native application (not Expo)?

**Comment by Palisand** [comment]
No, good point. Will do soon this week and I'll report back.

**Comment by Palisand** [comment]
@nikki93 **Accessibility font scaling DOES work in a pure React Native app.**

I used OpenSans:
1) `react-native init ...`
2) Add _`assets/fonts/OpenSans-Regular.ttf`_ to project root
3) `react-native link` 

Adds the following to _`Info.plist`_
```
<key>UIAppFonts</key>
<array>
  <string>OpenSans-Regular.ttf</string>
</array>
```
4) Set `fontFamily: "OpenSans"`

**NOTE:**
[Unlike with Expo](https://docs.expo.io/versions/v19.0.0/guides/using-custom-fonts.html#loading-the-font-in-your-app), setting `fontFamily` to `"OpenSans-Regular"` results in an error and `fontWeight: "bold"` works.

**Comment by Palisand** [comment]
@nikki93 Is there anything I can do to help with this?

**Comment by nikki93** [comment]
Fixed by https://github.com/expo/expo/commit/be263617fa1d34f6a7adcf47ea7c82e5e51c6861.
