### ISSUE TITLE
[android] MANAGE_DOCUMENTS permission by default against official doxs

### ISSUE THREAD

**Issue by aniltirola** [expo/expo#3968]
## 🐛 Bug Report
android-expo-apps have by default enabled the permissions `MANAGE_DOCUMENTS` in `AndroidManifest.xml`

The official docu tells us here: [https://developer.android.com/reference/android/Manifest.permission.html#MANAGE_DOCUMENTS](https://developer.android.com/reference/android/Manifest.permission.html#MANAGE_DOCUMENTS)

> This permission should only be requested by the platform document management app. This permission cannot be granted to third-party apps.

We can assume, that most expo-developers create 3rd-party-apps and not system-apps, so this permission should be disabled by default.

### Environment

- Platform: android
- app generated by expo build:android
- app generated by expo eject

### Expected Behavior

The Permission `android.permission.MANAGE_DOCUMENTS` should be disabled (removed) by default, or there should be an option in app.json to enable/disable for app-builds.

### Actual Behavior

The Permission `android.permission.MANAGE_DOCUMENTS` is enabled by default.

### Workaround

- for ejected apps:  disable (remove) `MANAGE_DOCUMENTS` in `AndroidManifest.xml`
- for builds by expo: no workaround possible, changes needed by the expo-team

Thanks for investigation.
Currently a big issue for us. 😳

**Comment by cruzach** [comment]
Hey @aniltirola,

What do you mean when you say this is currently a big issue for you? 

Also, for standalone app builds, you can actually configure Android permissions in `app.json`, see our [docs](https://docs.expo.io/versions/latest/workflow/configuration/#android) for specifics

-Charlie

**Comment by aniltirola** [comment]
thanks for the advice; just tested the property `permission` in `app.json` --> works!
closing now
