### ISSUE TITLE
[expo.io website] The website crashes if you have uBlock Origin preventing analytics scripts from running

### ISSUE THREAD

**Issue by ccheever** [expo/expo#3970]
@jimmylee reported this. If you have uBlock running, it will block scripts from Amplitude and Segment from running which will crash the page when you type into the search bar. 

A possible solution to this might be that we should use a `try`/`catch` around the analytics code.

**Comment by tsapeta** [comment]
Just tried and looks like it's no longer an issue — the website works for me with uBlock Origin running.
