### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by arshij** [expo/expo#3971]
Hi! I am building a project from scratch that uses the expo sensors pedometer. I built an app from scratch (not using Expo IDE) that imports expo-sensors and it works perfectly on its own. Once I add the JS file that uses the pedometer into my project, I run into the "Native module cannot be null" error. It is the one line `import {Pedometer} from expo-sensors` that is causing this issue, so I am assuming there is some error in the linking of expo-sensors to my project. This is odd since it is working perfectly on its own without using expo. I have followed the steps from the expo-sensors project (i.e., installing and linking uni-modules, expo-sensors, etc.) and made some changes to my podfile, but I keep running into this error. 

Can anyone maybe shed some light on what exactly might need to be linked in order for this to run properly? Any help is GREATLY appreciated, thank you so much in advance.

**Comment by AdamJNavarro** [comment]
Hey @arshij,

Can you ensure you've installed [react-native-unimodules](https://github.com/unimodules/react-native-unimodules#installation)? In the mean time, I'll try and see if I can repro the issue on my end.

Cheers,
Adam

**Comment by arshij** [comment]
Hi Adam, yes react-native-unimodules is installed and part of my package.json file.

**Comment by AdamJNavarro** [comment]
Can you possibly share a repo where I can test this? I just managed to implement it without issue. 
<img width="1440" alt="Screen Shot 2019-04-12 at 4 37 07 PM" src="https://user-images.githubusercontent.com/8992878/56067605-60cfcf80-5d41-11e9-8eea-1078a67935fc.png">

**Comment by arshij** [comment]
Yes here's a link to the repo: [https://github.com/arshij/solemate]. The setup instructions are all in the README file!

The file that is using the Pedometer is called `Steps.js` and the file calling functions from `Steps.js` is called `StartRunScreen.js`. I have commented out line 18 in `StartRunScreen.js` that causes the error (as it calls the import expo-sensors statement in Steps.js), so you may verify the app builds correctly for you first.

To access other pages of our application, you may need to log into Spotify (as well as have Spotify Premium), but regardless the app will throw an error after uncommenting that line. Let me know if you have any questions, thank you so much for taking a stab at this :)

**Comment by arshij** [comment]
Closing this as it seems like we found a workaround :)

**Comment by pvanny1124** [comment]
> Closing this as it seems like we found a workaround :)

Hey @arshij, can you post what the workaround is? I am getting the same error "Native module cannot be null". I am trying to access the pedometer as well and have read the instructions for `react-native-unimodules` but nothing is working. Would be a really big help. Thanks!!

**Comment by arshij** [comment]
Hey @pvanny1124, we actually decided to go with a completely different framework (CoreMotion) rather than trying to use expo-sensors in our non-expo project.
