### ISSUE TITLE
Fetch with multipart/form-data throws "Network Request Failed" error when content is not accessed before backend returns

### ISSUE THREAD

**Issue by sesterki** [expo/expo#3973]
## 🐛 Bug Report
I am using fetch to post images to a Django/Django Rest Framework backend. If I return before accessing the images (i.e. a 401, or even an early 200) then on Android fetch throws a `Network Request Failed` error, and on iOS the code simply hangs. This is a problem because we want to handle 401s differently from general network errors.

### Environment

  Expo CLI 2.14.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^32.0.2 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 

Target: iOS and Android

### Steps to Reproduce
Create a form data object with some file content.
```
const formData = new FormData()
photos.map((photo, index) =>
  formData.append('images', {
    name: `test${index}.jpg`,
    type: 'image/jpeg',
    uri: photo.uri,
  }),
)
```
Then use fetch to post this to the backend.
```
try {
  const response = await fetch(url, {
    body: formData,
    headers: {
      Authorization: `Bearer ${userToken}`,
    },
    method: 'POST'
  })
} catch (e) {
  console.log(e)
}
```
On the backend (Django Rest Framework in this case) return immediately or return a 404 etc from the endpoint.
```
return Response({'status': 'success'}, status=status.HTTP_200_OK)
```

If I access the image files and then return, everything works as expected.
```
images = request.FILES.getlist('images', [])
return Response({'status': 'success'}, status=status.HTTP_200_OK)
```

### Expected Behavior

Fetch should resolve normally.

### Actual Behavior

Fetch throws a `Network Request Failed` error on Android, and simply hangs and does nothing on iOS.

**Comment by AdamJNavarro** [comment]
Hey @sesterki,

Could you try seeing if this is reproducible in a vanilla React Native Project (one created via `react-native init AwesomeProject --version 0.57.1`)? Doing so will let us know if this is an Expo issue or rather a RN issue.

Cheers,
Adam

**Comment by sesterki** [comment]
Hello,

I retested this on a react-native 0.57.1 project on both a simulator and my actual phone and did not get the same issue. It looks like it is an Expo issue.

Thanks,
~Sean

**Comment by brentvatne** [comment]
@sesterki - can you provide a repository we can clone to reproduce this? it would be quite time consuming for us to do this for each issue report

**Comment by sesterki** [comment]
@brentvatne - here is a github repo: https://github.com/sesterki/expo-fetch-bug

In working on this repo I figured out that the issue is only when I am trying to post a local file (like one taken with the Expo Camera) and it does not happen when I specify a URL as the uri. This is reflected in my demo.

**Comment by sesterki** [comment]
@brentvatne Do you need any further information from me about this issue?

**Comment by j-ornelas** [comment]
I can confirm this is not an Expo issue. I'm trying to send a PDF from my phone using formData and I'm getting the same error, and I'm using a vanilla React Native project.

**Comment by jpramassini** [comment]
Bump, running into this issue as well. Are there currently any workarounds?

**Comment by Valiums** [comment]
Hey @sesterk, I had something similar on my end when I updated my expo sdk (from 31 -> 33) 
I think it might have something to do with fetch and FormData somehow? 

The workaround I found was to use XMLHttpRequest to handle FormData instead of fetch. 
Maybe this could help you too!

**Comment by dheerajrborra** [comment]
@brentvatne I am running into this problem too.  Checking to see if you had to investigate this issue.

**Comment by ThibautGeriz** [comment]
I have the same issue, it only happen on android
Have any of you managed to fix the issue?
```js
   const uri = 'file:///data/user/0/com.my.app/cache/ImagePicker/10cd6423-42d7-4146-80ab-10a66391220d.jpg, photo-a964dbZEeX-0.jpg' 
    const url = /upload/photo
    formData.append('photo', {
      uri,
      name: fileName,
      type: 'image/jpeg',
    });
    const result = await axios.put(url, formData);
```

**Comment by FrenchBully** [comment]
Was anyone able to resolve this issue successfully? 

Expo 33
RN 0.59.8

``` TypeError: Network request failed
    at S.u.onerror (whatwg-fetch.js:504)
    at S.value (event-target.js:172)
    at S.value (XMLHttpRequest.js:580)
    at S.value (XMLHttpRequest.js:394)
    at XMLHttpRequest.js:507
    at c.value (EventEmitter.js:189)
    at c.value (MessageQueue.js:366)
    at MessageQueue.js:106
    at c.value (MessageQueue.js:314)
    at c.value (MessageQueue.js:105)
```

**Comment by sharifhh** [comment]
Any ideas?

**Comment by ningacoding** [comment]
still happening, ios and web OK, Android with error Network request failed

**Comment by JJS4ntos** [comment]
Still happening here, nothing work!
```javascript
        let picture = {
            uri: 'https://facebook.github.io/react/logo-og.png',
            type: 'image/png',
        }
        let data = new FormData()
        data.append('image', picture)
        fetch(`myhost/shopping-list-products/detect`, {
            method: 'POST',
            headers:{  
                "Content-Type": "multipart/form-data"
            },
            body: data
        }).then(result => console.log(result))
        .catch(err => console.log(err))  
```
or

```javascript
        let data = new FormData()
        data.append('hello', 'world')
        fetch(`myhost/shopping-list-products/detect`, {
            method: 'POST',
            body: data
        }).then(result => console.log(result)))
        .catch(err => console.log(err))  
``` 

Its really breaked since april 2019?!

**Comment by brentvatne** [comment]
@JJS4ntos - i just cloned the repo from the original post, ran `expo upgrade` and installed `expo-camera` and `expo-permissions` and it worked fine on android - try it here: https://github.com/brentvatne/expo-fetch-bug

here is a snack showing a similar thing - uploading a local file from imagepicker to anonymousfiles.io - https://snack.expo.io/@notbrent/sharing-from-image-picker?platform=android

please create a new issue with a mcve (https://stackoverflow.com/help/mcve) if you think you have an issue
