### ISSUE TITLE
are images in the src/assets folder cached when launching app in expo?

### ISSUE THREAD

**Issue by HassanMehdi17** [expo/expo#3978]
i have many images saved locally in my src/assets folder. while running my app in expo, i notice that when going to a new page it takes a moment to load the image, even though it is local.

for reference, this is how i'm displaying the image:
```
                    <Image 
                        style={radioFormStyles.logo}
                        resizeMode={'contain'}
                        source={require('../../assets/logo_text.png')}
                    />
```
my question is:

is this just something the app does while being launched from expo?

will it do this when it is a standalone app?

how can i fix this?

thank you for your answers in advance.

before image loads:
![IMG_3877](https://user-images.githubusercontent.com/27031368/56010065-1baf8d00-5cb0-11e9-8108-430ddf7cd68f.PNG)

after image loads:
![IMG_3874](https://user-images.githubusercontent.com/27031368/56010091-32ee7a80-5cb0-11e9-83b0-c17990bf149a.PNG)

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/v32.0.0/guides/offline-support/#bundle-your-assets-inside-your-standalone-binary
