### ISSUE TITLE
exp-cli freezes when installing with yarn or npm

### ISSUE THREAD

**Issue by rollymaduk** [expo/expo#398]
Hi great tool, trying to install the cli on my linux machine using yarn v0.27.5 or npm v 5.3.0 fails to install, It just freezes after a while during installation at the same spot, for npm at `extract:core-js: sill extract delay-async@1.1.0` and for yarn at same spot.

**Comment by dikaiosune** [comment]
Hi! The tunnel service we use has a large-ish binary to download that sometimes hangs on slower internet connections. If you discover that this isn't related to your network connection or a yarn/npm bug, please post back and we'll take another look. Thanks!

**Comment by ghasemikasra39** [comment]
The same problem on windows:
freezes at extract:@expo/traveling-fastlane-linux: sill pacote @expo/traveling-fastlane-linux@https://registry.npmjs.org/@

**Comment by edoantonioco** [comment]
Same problem in W10, trying to install the expo cli and its stuck on the traveling fastline

**Comment by swarnim89** [comment]
freezes at extract:@expo/traveling-fastlane-linux: sill pacote @expo/traveling-fastlane-linux@https://registry.npmjs.org/@

npm cache clean --force, try again to install. Probably slow internet make it stuck. I too face this but after few attempts, was able installed it successfully.

**Comment by invertmap** [comment]
how fast internet speed you want???? 95GB/second ?

**Comment by eleallegue** [comment]
@swarnim89 I hav that exact problem too, the thing is that I unistalled everything again, even node.js, and still does not work.... don't know what to do...

**Comment by eleallegue** [comment]
Plase @anp @swarnim89 I cannot make it work, I have updated to the last version, and now it gets stucked there, and I have a work to finish....
My internet connection speed is: 80Mbps
I am trying the ``npm cache clean --force``` and after that I try the ```npm install -g expo-cli``` and nothing changes, I have even reinstalled Node just in case there was a problem (I was obtaining a lot of problems with libraries with expo that's why I tried to upgrade it from 2.19.4 to 2.19.5)

ANY COMMENT HELP
