### ISSUE TITLE
[webview][Android] Unable to select photo from library using [input type = "file"]

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#3981]
### Environment

**Android**
SDK32

### Reproducible Demo

**Snack**: https://snack.expo.io/S1U4Xv-ZQ

### Side notes

Initially from here: https://github.com/expo/expo/issues/1879#issuecomment-435959931 and here: https://github.com/expo/expo/issues/1879#issuecomment-482166553

**Comment by dsokal** [comment]
@sjchmiela told me it's ok to close this one

**Comment by dsokal** [comment]
@sjchmiela I tested this on current master and it works fine, so I think we can close this one because it won't be an issue in SDK 33.

**Comment by jibeizhao** [comment]
@dsokal  how does one use the 33.0.0-alpha.web.3 version, while the cli only support v32? 
Thanks

**Comment by tsapeta** [comment]
@jibeizhao `expo` package on npm registry contains only JavaScript code and it won't change anything regardless this issue. If you want to use the most recent native code, you may try to build your own Expo client from source or just wait a little bit as we're going to release SDK33 soon.

**Comment by jibeizhao** [comment]
@dsokal i just tested it using SDK33
with a new project created by `expo init`

```javascript
import React from 'react';
import { WebView } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <WebView
        source={{uri: 'http://www.localtesthtml.com'}}
        style={{marginTop: 20}}
      />
    );
  }
}

```

the html file only has this in it:
`<input type="file" name="files[]" multiple>`

Nothing happens after clicking on the button in the android emulator or on pixel 2
but it does work fine on iphone

**Comment by dsokal** [comment]
@jibeizhao please install `react-native-webview` and replace:
`import { WebView } from 'react-native';`
with:
`import WebView from 'react-native-webview';`

It should fix the issue.
