### ISSUE TITLE
Remote Debugging on a Published Build?

### ISSUE THREAD

**Issue by zocheyado** [expo/expo#3985]
Is it possible to debug a remote published build? Basically I publish a build to let a few people test the app. One particular user, is having issues (app hanging up). I am wondering if there is a way to debug this remotely like I do if the device is on wifi (connected to local instance of expo). If not is there a way to keep all the console logs / errors for the app somewhere and export them so I can view them?

**Comment by AdamJNavarro** [comment]
Hey @zocheyado,

You can run `expo start --no-dev --minify` which reproduces the production JS bundle locally.

Cheers,
Adam

**Comment by zocheyado** [comment]
Well I know that, you can also just enable production mode from the expo. my issue specifically is with some remote device that another person is using. if you have the device locally you can obviously debug it, I am talking specifically about a way to remotely debug, or save the debug information to a file so a remote person could send it to me.

**Comment by brentvatne** [comment]
hey @zocheyado no need to be salty here, @AdamJNavarro was just trying to help. you can use services like sentry to report errors or unexpected behavior in production. you cannot connect to someone's device and debug it.

**Comment by zocheyado** [comment]
I wasn't salty, I was just looking for an answer and it seemed like he didn't understand what I was trying to do. I will look into sentry.

**Comment by brentvatne** [comment]
if you're using the word "obviously" in response to someone's attempt to help you it's a good sign that you're going to be perceived as being passive aggressive / salty. hope sentry works out for you, lmk if you have any further questions about it
