### ISSUE TITLE
Expected Javascript but got null

### ISSUE THREAD

**Issue by d7laungani** [expo/expo#3987]
It is hard for me to demonstrate this but in my case.

running expo --lan causes this error

Other instances

running expo --tunnel - makes the app stuck on the loading screen

Publishing the same app and running with the code in the cases above works perfectly as deployed.

I am giving this scenario and the results to help with debugging.

**Comment by brentvatne** [comment]
hi! sorry we can't really do much without either a way for us to reproduce this or a more detailed description of what you are experiencing :O
