### ISSUE TITLE
Error: Invalid FileSystem URI since 19.0.0

### ISSUE THREAD

**Issue by zoruninho** [expo/expo#399]
Hi,

First, thanks for all your hard work, I enjoy a lot using expo for my app project and can't wait to keep going on with it. 

But today I tried to update my project from expo 18 to expo 19, as explained on [this tutorial](https://blog.expo.io/expo-sdk-v19-0-0-is-now-available-821a62b58d3d)

Firstly I encountered an issue with react-native-svg. The article says that expo updated to 5.3.0 (but found 5.2.0 in the dependencies) and I had to manually apply [this PR](https://github.com/react-native-community/react-native-svg/pull/411) to remove the first issue. 

But I still get stucked now with this issue: 

`Possible Unhandled Promise Rejection (id: 0):
Error: Invalid FileSystem URI 'ExponentAsset-8599704930316b431e827d8e63e916bf.ttf', make sure it's in the app's scope.`

I deleted the node_modules folder as explained, quit Expo XDE multiple times, restarted a few dozens of times too. I searched a lot for this issue but found nothing currently. It was working perfectly fine before the update and I didn't change anything apart from what was explained in the blog's article. 

Thanks for your help!

**Comment by brentvatne** [comment]
> Firstly I encountered an issue with react-native-svg. The article says that expo updated to 5.3.0 (but found 5.2.0 in the dependencies) and I had to manually apply this PR to remove the first issue.

this makes me think that you may have forgotten to update the version of `expo` in your package.json. notice that it is indeed 5.3.0: https://github.com/expo/expo-sdk/blob/master/package.json#L41

assigned @nikki93 to this issue re: filesystem

**Comment by zoruninho** [comment]
@brentvatne I thought too but here is my package.json

```
{
  "name": "relaxppmobile",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "axios": "^0.16.2",
    "expo": "^19.0.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz",
    "react-native-elements": "^0.13.0",
    "react-native-parallax-scroll-view": "^0.19.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.1",
    "redux-form": "^7.0.0",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.2.0",
    "eslint-plugin-react": "^7.1.0"
  }
}
```

**Comment by chachasikes** [comment]
The same problem started happening for me once I upgraded expo 18.0.0 to 19.0.0. Similar error, but it is effecting loading image for gl-react-expo. 
I updated my package.jon & also app.json.

`Error: Invalid FileSystem URI 'ExponentAsset-73a9d34a77eedf6c3b264de939e86284.jpg', make sure it's in the app's scope.`

**Comment by chachasikes** [comment]
This seems relevant:
https://blog.expo.io/expo-sdk-v19-0-0-is-now-available-821a62b58d3d
"FileSystem
The FileSystem API that lets you read, write, delete, move, copy files in a scoped file system (so you can’t access files for other projects opened with the Expo client). You can also make and navigate directories, download files from a remote URI and read file metadata. The API provides access to images saved by ImagePicker, recordings made by the Audio recording API, and databases created by the SQLite API. You can also use any of the files in the FileSystem API as audio, video, image, GL texture sources or SQLite databases.
Read the documentation."
https://docs.expo.io/versions/v19.0.0/sdk/filesystem.html

Maybe the modules that load images need to be updated in some way... I'll see if I can figure it out.

**Comment by nikki93** [comment]
Hey all! Can you tell us what this line: https://github.com/expo/expo-sdk/blob/dbc787c90875a8605d6bbac49a5ece18aae13069/src/Asset.js#L125 looks like in your `node_modules/expo/src/Asset.js`?

**Comment by zoruninho** [comment]
Hi :) 

Here are my lines from 118 to 148
```
try {
      const path = `ExponentAsset-${this.hash}.${this.type}`;
      let exists, md5, uri;
      ({
        exists,
        md5,
        uri,
      } = await NativeModules.ExponentFileSystem.getInfoAsync(path, {
        cache: true,
        md5: true,
      }));
      if (!exists || md5 !== this.hash) {
        ({
          md5,
          uri,
        } = await NativeModules.ExponentFileSystem.downloadAsync(
          this.uri,
          path,
          { cache: true, md5: true }
        ));
        if (md5 !== this.hash) {
          throw new Error(
            `Downloaded file for asset '${this.name}.${this.type}' ` +
              `failed MD5 integrity check`
          );
        }
      }
      this.localUri = uri;
      this.downloaded = true;
      this.downloadCallbacks.forEach(({ resolve }) => resolve());
    } 
```

And here is my app.json 

```
{
  "expo": {
    "name": "test",
    "description": "An empty new project",
    "slug": "test",
    "privacy": "public",
    "sdkVersion": "19.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      backgroundColor: "#3AB0CE",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true
    }
  }
}

```

**Comment by nikki93** [comment]
Yeah that's the old JS. `rm -rf node_modules/ && npm i` will get you the new stuff if your `package.json` is updated.

Simply updating `package.json` will not affect the change in your `node_modules/` directory which is where the JS is bundled from. Often also simply updating `package.json` and running `npm i` or `npm i <packagename>` will also not successfully update the package. An `rm -rf node_modules/` is good to be sure.

**Comment by zoruninho** [comment]
Will I did delete the node_modules folder 4/5 times already and downloaded again every time but I'll give it another try then. Maybe some weird stuff there. Thanks for the help :)

**Comment by zoruninho** [comment]
I don't know why but this time that did the trick! Probably some bad deletion on my previous tries, had to run sudo from the command line to make it properly. 

I still have a strange behaviour from the app but I'll probably fix it soon, most of it is working, thanks a lot :)
