### ISSUE TITLE
Location SDK permission granted without granting

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#3992]
### Environment

  Expo CLI 2.11.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.4.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.11.7

### Steps to Reproduce

In my code, I'm calling

```
let perms = await Location.hasServicesEnabledAsync();
```

And if perms are true, I call

```
      let location = await Location.getCurrentPositionAsync({accuracy: Location.Accuracy.Lowest});
```

I've reset my simulator and the permissions for this app do not exist in the settings, and yet perms is always returning true which causes the call to Location.getCurrentPositionAsync to throw an error:

```
Error: LOCATION permission is required to do this operation.
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:397)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:72
```

### Expected Behavior

Expected perms to be null or false.

**Comment by brentvatne** [comment]
`let perms = await Location.hasServicesEnabledAsync();` does not mean that you have permission, it just means that the device has location services turned on. you need to call `Location.requestPermissionsAsync()` to actually request permission

**Comment by lightninglu10** [comment]
How do we check if we've requested permission before or not and whether the user has authorized permission or not?

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/v32.0.0/sdk/permissions/
