### ISSUE TITLE
Error Xcode build

### ISSUE THREAD

**Issue by Brhernann** [expo/expo#401]
Hello, i have this error in my project is generate when i wanna build my project:

../ios/Pods/ExpoKit/ios/Exponent/Versioned/EXVersionManager.m:261:67: No visible @interface for 'RCTAsyncLocalStorage' declares the selector 'initWithStorageDirectory:'

this is the line:

[[RCTAsyncLocalStorage alloc] initWithStorageDirectory:[experienceScope scopedPathWithPath:EX_UNVERSIONED(@"RCTAsyncLocalStorage") withOptions:@{}]],
 ]];

Please help!

**Comment by terribleben** [comment]
Hi there! Can you make sure your project is pointing at Expo's fork of React Native?

**Comment by Brhernann** [comment]
I understand that the problem is because expo don't work with EXcode.

**Comment by terribleben** [comment]
It does if you use [ExpoKit](https://docs.expo.io/versions/v19.0.0/guides/detach.html)!

**Comment by cummings** [comment]
@Brhernann I'm having the same issue. How did you solve it?

**Comment by joshpitzalis** [comment]
+1

**Comment by Brhernann** [comment]
first try run `npm start` (up the server),  after run the xcode project (if you use pod, run the nameproyect.xcworkspace).

this work for me.

i remember that the logic of Expo is not use xcode because them provide the [SDK API reference](https://docs.expo.io/versions/latest/sdk/index.html) if you want use xcode is recommended use react-native init, i needed install FCM, my final solution was change to generator to react native init.

**Comment by hugoh1995** [comment]
Having similar issue, how can I fix this?

**Comment by terribleben** [comment]
To others finding this thread, here's a more detailed version of my original answer:

1. This error only applies if you are using an [ExpoKit](https://docs.expo.io/versions/latest/expokit/index.html) project (an Expo project that contains native code).
2. Make sure your project is using Expo's fork of react native. Specifically, Expo's fork declares `initWithStorageDirectory` but Facebook's upstream version does not. So you would see this error if you mistakenly are using Facebook's version.

To use Expo's fork, make sure your `package.json` contains a react native dependency similar to `https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz` but replace `24` with your Expo SDK version. Reinstall JS dependencies, then after that, re-run `pod install`. For documentation about this, see the [Developing with ExpoKit](https://docs.expo.io/versions/latest/guides/expokit.html) guide.

**Comment by yingdongzhang** [comment]
> 1. Check JS dependencies
Your project’s package.json should contain a react-native dependency pointing at Expo’s fork of React Native. This should already be configured for you.

The documentation isn't quite clear about what exactly to put in there regarding the react native dependency, I only found out the right url by reading this thread.
