### ISSUE TITLE
Requests sent are delayed when not using localhost.

### ISSUE THREAD

**Issue by Jomik** [expo/expo#4012]
### Environment

```
  Expo CLI 2.14.0 environment info:
    System:
      OS: Linux 4.19 NixOS 19.03beta171931.3a4ffdd38b5 (Koi) 19.03beta171931.3a4ffdd38b5 (Koi)
      Shell: 4.4.23 - /run/current-system/sw/bin/bash
    Binaries:
      Node: 10.15.3 - /nix/store/mpswfnh8q707as429grnabv5agxqcx1g-nodejs-10.15.3/bin/node
      Yarn: 1.13.0 - /nix/store/7l0hf7fy9qc92fjgb301d9y5xlkslyw5-yarn-1.13.0/bin/yarn
      npm: 6.4.1 - /nix/store/mpswfnh8q707as429grnabv5agxqcx1g-nodejs-10.15.3/bin/npm
    npmPackages:
      @types/expo: ^32.0.9 => 32.0.10 
      @types/react: ^16.8.9 => 16.8.13 
      @types/react-navigation: ^3.0.5 => 3.0.6 
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.5.1 => 3.6.1 
```

For iOS and Android.

### Steps to Reproduce

We are accessing a server running on our local machine.
We get the IP for the server using `manifest.debuggerHost`.
Thus we get a LAN IP or `127.0.0.1`.
Send a request to the given IP at app startup.

```
const baseUrl =
  typeof manifest.packagerOpts === "object" && manifest.packagerOpts.dev
    ? `http://${manifest.debuggerHost
        .split(`:`)[0]}:3000/`
    : // "http://localhost:3000/"
      conf.apiBaseUrl;
```

### Expected Behavior
We expect that the request comes through nearly instantly, as they are sent on app startup.

### Actual Behavior
We observe that there is noticeable latency before the request is received by the server, about 30-60 seconds.

This delay happens when the address is a LAN IP _and_ when the address is `http://127.0.0.1:3000/`, but _NOT_ when the address is `http://localhost:3000/`.
Even though `127.0.0.1` and `localhost` should essentially be the same.

### Reproducible Demo
Not easily reproducible.

**Comment by cruzach** [comment]
Hey @Jomik,

Sorry about that delay. Are both devices (computer & mobile device) on the same network? If not, that can tend to cause some issues when using LAN.

-Charlie

**Comment by Jomik** [comment]
Yeah, both devices are connected to the same network, and right next to each other. This is an issue for everyone on my team.
As I wrote, it is even an issue when corrected through `local` using adb reverse.
Though, that is only if we use `127.0.0.1` instead of `localhost`. For some reason the ip address causes a slowdown, where using localhost does not. Even though it should be exactly the same.

**Comment by cruzach** [comment]
@Jomik,

Not sure what could cause that, I'll ask around internally. 

Curious: why use `127.0.0.1` instead of `localhost`?

**Comment by Jomik** [comment]
That is what `manifest.debuggerHost` reports.

Also, it is an issue with any IP, that is not `localhost`. So if we want to use a LAN ip, that also cause these slow requests.

**Comment by Jomik** [comment]
To clarify, we see a large delay in sending requests to our server when we use _any_ IP address.
That is, even using something like a `local` connection and using the localhost ip address `127.0.0.1` causes this delay.
The devices are connected to the same local area network.
The only case where we do not see a delay, is using `localhost` hostname as the address, even though this should be the _same_ as `127.0.0.1`.

**Comment by ide** [comment]
Have you tested with external servers (ex: fetching HTML from http://example.com)? It sounds like there's some network/LAN or emulator/VM configuration issue.

**Comment by Jomik** [comment]
The server I am running against is a `nodejs` server running on my local machine. I don't experience any issues connecting to it via LAN, using the browser on my phone.
I _will_ make sure to test this Wednesday with our production server and update here.

Thank you :)

**Comment by Jomik** [comment]
@ide So it seems that we do not get the issue when connecting to our production server.
So it is only when accessing an IP address over LAN.
I suppose this may not directly be related to Expo - we simply did not have this issue before..

**Comment by ide** [comment]
I'd try a different router or different computer to see if you can isolate the problem further. Could be some kind of firewall setting.

**Comment by Jomik** [comment]
@ide We are 4 people experiencing the issue. I have tested on 3 separate routers from my machine.

**Comment by abstruse9** [comment]
@ide 

I have been experiencing a similar issue too.  All requests are initially delayed during app startup when on LAN. 

A delay (variable from 30sec to 1 minute) when using `192.168.0.50` which is basically where the Node JS server is running on my LAN.

When I request via LAN from my phone via Chrome Browser, it's fast.

But when I request from Expo App, the issue occurs.

On an another note, when I request my cloud server hosted on internet, the expo requests are fine.

**Comment by ide** [comment]
I'm not sure what this is -- the best path forward is probably for someone with this network setup to identify the root cause.

**Comment by Jomik** [comment]
@ide what network setup?
It seems to simply occur when you try to access an external webserver (not on `localhost`) from within the Expo development environment.
It occurs on 3 separate networks for me alone, there is no super weird setup going on, we are simply accessing our API.

**Comment by ide** [comment]
There isn’t anything special in the Expo client that intercepts and handles LAN IPs differently than other hosts. Also, if you are experiencing this behavior across iOS and Android, it’s unlikely to be an issue with the Java or Obj-C code unless the same behavior was unintentionally implemented twice in the Expo Client or underlying OSes (ex: Apple and Google may have implemented the same bug). It’s more likely that a common part of your setup is introducing the issue, such as your network or computer. Part of the issue is that the root cause is unknown so it’s inherently hard to precisely say what network setup is causing the issue without investigating further.

**Comment by abstruse9** [comment]
@Jomik 

Did you find a solution for this problem?

**Comment by Jomik** [comment]
No, sadly not. I am guessing it may be due to something like redux-logger. But, we have just settled to using localhost and a cable..

**Comment by abstruse9** [comment]
@Jomik 

I wasn't even using redux-logger and it still caused the delay. I thought it was due to React Navigation. 

And yes, localhost and a cable works fine for me too!
