### ISSUE TITLE
Horizontal Flatlist on scroll jumps to the start

### ISSUE THREAD

**Issue by manzoorwanijk** [expo/expo#4013]
### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.1-next.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

For iOS and Android

### Steps to Reproduce

Create a horizontal flatlist of considerable items (50+) and scroll to the end.

### Expected Behavior

The scroll should stop at the end of the list.

### Actual Behavior

It jumps to the start of the list.

### Reproducible Demo

There is a related [issue on RN repo](https://github.com/facebook/react-native/issues/22710), which seems to have been fixed. When can we expect it to be available in expo SDK?

**Comment by AdamJNavarro** [comment]
Hey @manzoorwanijk,

As long as there have been no regressions, the fix should be included with the release of SDK33 (we're hoping for an April release but don't have a concrete target date). For questions like these, please use the forums rather than opening a github issue!

Cheers,
Adam
