### ISSUE TITLE
Invariant Violation: Maximum update depth exceded

### ISSUE THREAD

**Issue by ricardolousada** [expo/expo#4014]
## 🐛 Bug Report
I was doing the class this Harvard Class: https://video.cs50.net/mobile/2018/spring/lectures/4?t=1h7m41s

And with the same exact code I got this error in expo, i'm going crazy with this because i can not understand it? can you please help?

import React from 'react';
import {Button, SectionList, StyleSheet, Text, View } from 'react-native';
import contacts, {compareName} from './contacts'
import {Constants} from 'expo';
import Row from './row';

export default class App extends React.Component {
  state = {
    showContacts:false,
    contacts: contacts,
  }

  toggleContacts = () => {
    
    this.setState(prevState => ({showContacts:!prevState.showContacts}))
    
  }

  sort = () => {
    this.setState(prevState => 
      ({contacts: [...prevState.contacts].sort(compareName)
      }))
  }

  renderItem = ({item}) => <Row {...item}/>

  renderSectionHeader = ({section}) => <Text>{section.title}</Text>
  

  render() {
    return (
      <View style={styles.container}>
        <Button title = "Toggle contacts" onPress={this.toggleContacts}/>
        <Button title = "sort" onPress={this.sort()}/>
        {this.state.showContacts && (
        <SectionList
          renderItem = {this.renderItem}
          renderSectionHeader = {this.renderSectionHeader}
          sections={[{
            title: A,
            data: this.section.contacts
          }]}
        />
        )}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    marginTop: Constants.statusBarHeight,
    flex: 1,
    backgroundColor: '#fff',
    alignItems:'flex-start',
    justifyContent: 'flex-start',
  },
});

### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

**Comment by AdamJNavarro** [comment]
Hey @ricardolousada,

Can you put your code in a [Snack](snack.expo.io) so we can test it?

Cheers,
Adam

**Comment by ricardolousada** [comment]
sure, I will do it...

**Comment by ricardolousada** [comment]
@AdamJNavarro  my snack is: https://snack.expo.io/@rlousada/insane-blueberries

Thank you for your help :)

**Comment by cruzach** [comment]
Hey @ricardolousada,

We try to keep Github for bugs, and this error most likely has something to do with your code. Best course of action is probably to look at React Native's [docs for SectionList](https://facebook.github.io/react-native/docs/sectionlist), and if you're still having issues feel free to post in our [How-To Forums](https://forums.expo.io/c/how-to) 👍

**Comment by ricardolousada** [comment]
Thanks @cruzach after so many complications I have decided to go native :) all the best for you and the team
