### ISSUE TITLE
getCurrentPositionAsync does not work concurrently

### ISSUE THREAD

**Issue by paldepind** [expo/expo#4015]
### Environment

Expo 32.0

### Steps to Reproduce

Insert the following code in an Expo project and run it.

```javascript
import { Permissions, Location } from 'expo';

Permissions.askAsync(Permissions.LOCATION).then(({ status }) => {
  if (status === "granted") {
    console.log("Asking for location twice");

    Location.getCurrentPositionAsync({
      accuracy: Location.Accuracy.Highest
    }).then((l) => console.log("First", l));

    Location.getCurrentPositionAsync({
      accuracy: Location.Accuracy.Highest
    }).then((l) => console.log("Second", l));
  }
});
```

### Expected Behavior

Both promises from the two calls to `getCurrentPositionAsync` resolve and both `First` and `Second` is logged to the console.

### Actual Behavior

Only `Second` is ever logged to the console. The promise from the first invocation to `getCurrentPositionAsync` never resolves.

Note that it is always `Second` that gets logged and never `First`. It appears to me that when `getCurrentPositionAsync` is called while there already is an ongoing location request that hasn't resolved yet the promise from the first call is forgotten and never resolved.

### Reproducible Demo

Here is a Snap reproducing the issue. I've simply pasted the code above into the default project Snap creates: https://snack.expo.io/SJGdW6E5E

**Comment by cruzach** [comment]
Hey @paldepind,

Have you considered using a lock in between calls (or any other mechanism that would ensure the completion of the first `getCurrentPositionAsync` call before starting the second)? I'm not sure this is necessarily a bug

-Charlie

**Comment by paldepind** [comment]
@cruzach Thank you for the suggestion. Yes, after tracking a bug in our app down to this I have temporarily solved the problem by wrapping `getCurrentPositionAsync` in a function that keeps track of position requests and ensures that `getCurrentPositionAsync` is never called concurrently.

> I'm not sure this is necessarily a bug

To me it certainly seems like a bug. `getCurrentPositionAsync` returns a promise that _never_ resolves. And the docs clearly states the following about `getCurrentPositionAsync`:

> Returns a promise resolving to an object representing Location type.

Any code awaiting the promise will silently hang forever. To make matters worse since this is associated with concurrent calls the error may be a hard to debug race conditions. So this causes bugs in users of `getCurrentPositionAsync` that are both silent and sporadic.

It also seems very unexpected that a second call to `getCurrentPositionAsync` messes with the result of a previous call to `getCurrentPositionAsync`.

[react-native-location](https://github.com/timfpark/react-native-location) which we used before switching to Expo does not have this problem.

**Comment by ide** [comment]
The current behavior is not intended but we are not actively working on it. I would recommend serializing your calls in your application code as a workaround.
