### ISSUE TITLE
Adding and referencing an external font causes an "Unable to resolve..." error.

### ISSUE THREAD

**Issue by slimwizard** [expo/expo#4016]
## Description

After creating a new project using the Expo CLI, I am unable to use new fonts in the project. Adding and referencing an external font other than the one included (Space Mono) results in an "Unable to resolve module..." error. 

## Expected Behavior

I expected to be able to add and reference an external font in the same exact way that the project does with the Space Mono font. 

## Observed Behavior

After adding the Roboto.tff file to `./assets/fonts/` and referencing it in the App.js file with `'roboto': require('./assets/fonts/Roboto.tff')`, the application will not compile and I am presented with an error message stating that the specified module does not exist. 

Error message:

```
Unable to resolve "./assets/fonts/Roboto.tff" from "App.js"
```
<img width="780" alt="Screen Shot 2019-04-14 at 5 09 16 PM" src="https://user-images.githubusercontent.com/26125306/56100681-724fdd80-5ee1-11e9-8d70-8a84170a4d41.png">
<img width="428" alt="Screen Shot 2019-04-14 at 5 23 43 PM" src="https://user-images.githubusercontent.com/26125306/56100686-7da30900-5ee1-11e9-9d74-1c8815b79a82.png">

I've already tried the following solutions:
- clearing the NPM cache
- deleting and reinstalling node modules
- deleting and recreating the project
- changing the font file name to match the "Full Name" of the file
- using font files other than the one specifically mentioned in this issue
- running `react-native link` (I know, I know...different CLI, but I was desperate)
- referencing the full path to the file in the require() method
- restarting the iOS simulator
- restarting the machine

## Environment

`  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.8.1 
    npmGlobalPackages:
      expo-cli: 2.14.0`

Using Xcode iOS simulator - iPhone X 12.2

### Step 1: 
Run `expo init New-Project`; choose to create the 'tabs' template.
### Step 2: 
Download Roboto font from Google fonts.
### Step 3: 
Copy Roboto-Regular.tff into `./assets/fonts` and change file name to `Roboto.tff` so that it matches the "Full Name" displayed after right-clicking the file and selecting "Get Info". Please keep in mind that I have also added the font and referenced the name as it came, which was `Roboto-Regular.tff`. Same behavior. 
### Step 4: 
Reference the font file in the same way Space Mono is referenced by adding `'roboto': require('./assets/fonts/Roboto.tff')` to line 41 in `App.js` (make sure and add a comma after the Space Mono reference).

<img width="1058" alt="Screen Shot 2019-04-14 at 6 12 19 PM" src="https://user-images.githubusercontent.com/26125306/56100691-8b588e80-5ee1-11e9-946a-91026519a547.png">

### Step 5: 
Run the application with `npm start`.
### Step 6: 
Click "Run on iOS simulator" in the Expo Developer Tools to run on the simulator. This step can be replaced by scanning the QR code with an iPhone camera to open the project in the native Expo application. The results are the same.

**Comment by squeamish-ossifrage** [comment]
Having the same issue. Is there a solution?

**Comment by divee789** [comment]
please i am having this error
what is the solution
