### ISSUE TITLE
ERROR ITMS-90725: SDK Version Issue

### ISSUE THREAD

**Issue by ThalesCrisostomo** [expo/expo#4018]
When I upload the application through Application Loader I get this error:

> ERROR ITMS-90725: "SDK Version Issue This app was built with the iOS >11.4 SDK.All iOS apps submitted to the App Store should be built with >the iOS 11 SDK or later, included in Xcode 9 or later. 2019, all iOS >apps submitted to the App Store must be built with the iOS 12.1 SDK or >later, included in Xcode 10.1 or later. "

Xcode: 10.2
MacOS MoJave: 10.14.4
Expo-cli: 2.14
Expo SDK: ^32.0.0
react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz

**Comment by cruzach** [comment]
Closing here, continued @ [this forum post](https://forums.expo.io/t/error-itms-90725-invalid-version-app-store/21722). Will re-open if it turns out to be a bug 🐛
