### ISSUE TITLE
[docs] Clicking on "Getting to know Expo" while already on the page on latest leads to bad state

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4026]
This tweet describes it well: https://twitter.com/elioncho/status/1118921180998664192

1. Go into https://docs.expo.io/versions/latest/
2. Click on "Getting to know Expo" in the left side menu
3. Scroll down to the “Ready to get started” section
4. “Installation” and “Up and running” guide links should be broken. Their urls don’t specify a version.

**Comment by cruzach** [comment]
Looks like it happens to all the links on the page that point to Expo documentation
