### ISSUE TITLE
Interactive Push Notifications in ExpoKit

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#4028]
Is that possible to use Interactive Push Notifications in ExpoKit? Or this feature is only available in the pure Expo?

**Comment by AdamJNavarro** [comment]
Hey @Luckygirlllll,

You'll only be able to make use of our Interactive Push Notifs within a managed Expo project. There are alternatives that are available with a Bare workflow or ExpoKit project however. Also, we try to keep github issues reserved for bugs and try our best to keep questions like this one on our [forums](https://forums.expo.io/)! In the future, if you have any more questions please feel free to ask away there.

Cheers,
Adam

**Comment by Luckygirlllll** [comment]
@AdamJNavarro What alternatives would you recommend for ExpoKit project?
