### ISSUE TITLE
[Android] [Build] Execution failed for task :app:exponentPrebuildStep (Ejected Expo App)

### ISSUE THREAD

**Issue by lucamir** [expo/expo#4029]
Hi guys,
I'm trying to build an ejected expo app but the build fails in for the task 
**:app:exponentPrebuildStep**.

Any Solution?

**Env Conf:**

> Mac OS: 10.14.4,
node: 10.15.2
npm: 6.9.0
expo-cli: 2.15.3
expo: "^31.0.5"
react-native: "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",

**Execution failed for task ':app:exponentPrebuildStep'.**
> A problem occurred starting process 'command './node_modules/expokit/detach-scripts/run-exp.sh''

**ERROR:** Unable to resolve dependency for ':app@devMinSdkDevKernelDebug/compileClasspath': 
> Could not find expolib_v1.com.google.android.exoplayer:expolib_v1-extension-okhttp:2.6.1.
Any solution for fix this issues?

**ERROR:** Failed to resolve: 
> host.exp.exponent:expoview:31.0.0

**ERROR:** Unable to resolve dependency for ':app@devMinSdkDevKernelDebugAndroidTest/compileClasspath':

> Could not find expolib_v1.com.google.android.exoplayer:expolib_v1-extension-okhttp:2.6.1.

**ERROR:** Unable to resolve dependency for ':app@devMinSdkDevKernelDebugUnitTest/compileClasspath': 

> Could not find expolib_v1.com.google.android.exoplayer:expolib_v1-extension-okhttp:2.6.1.

**Comment by ilyeSudo** [comment]
@lucamir any solution found please?

**Comment by lucamir** [comment]
@ilyeSudo In my case i only had to install expokit with the same version of my expo SDK version.
> e.g. npm install --save expokit@31.0.0 ( 31.0.0 is the project's expo SDK version )

**Comment by ilyeSudo** [comment]
> @ilyeSudo In my case i only had to install expokit with the same version of my expo SDK version.
> 
> > e.g. npm install --save expokit@31.0.0 ( 31.0.0 is the project's expo SDK version )

Saved my day. Thanks!!!

**Comment by pedro-lb** [comment]
Thanks @lucamir! Saved me after spending 3 hours looking for a solution. You're amazing! 💯

**Comment by tsapeta** [comment]
Taking into account that the solution has been found above and SDK31 is no longer supported I decided to close this issue.
