### ISSUE TITLE
detached project crashed when running

### ISSUE THREAD

**Issue by CrazyWr** [expo/expo#403]
I had configured and build following https://docs.expo.io/versions/v17.0.0/guides/expokit.html

pod install 
![image](https://user-images.githubusercontent.com/19635808/28515859-c03b67ca-7091-11e7-9672-1752e11d9148.png)

setting.json
![image](https://user-images.githubusercontent.com/19635808/28516023-517fecce-7092-11e7-81c1-a8b08b0cf900.png)

exp start
![image](https://user-images.githubusercontent.com/19635808/28516056-6aaff9fa-7092-11e7-8cf0-93091344e1ea.png)

crashed 
![image](https://user-images.githubusercontent.com/19635808/28516070-800e0ad0-7092-11e7-8a56-78a3c2c42ae8.png)

**Comment by CrazyWr** [comment]
I tried protocal "exp" and "lan" but not working too

**Comment by CrazyWr** [comment]
It crashed like this when I tried the real device 
![image](https://user-images.githubusercontent.com/19635808/28517011-a7b5451e-7095-11e7-85a7-513a2ee46482.png)

**Comment by terribleben** [comment]
Hi, it doesn't look like you ran `exp detach` at any point, so your project isn't configured for development from Xcode. Can you make sure you run that step prior to following the rest of the guide?

**Comment by CrazyWr** [comment]
![image](https://user-images.githubusercontent.com/19635808/28551152-a1fc9e8c-7118-11e7-9fc0-dc1c3f35a1d3.png)
I'm sure to run that step following the guide, before "exp detach" I have develope some modules and functions with expo, and it works good.
I ran exp detach to develope some module for BLE, and tried dozens of times before success because of GFW in China.

**Comment by terribleben** [comment]
Oh ok. Your `exp.json` should have an `isDetached` key and a `detach.scheme` property. The error shown in Xcode indicates that it can't find those, so it's unable to configure a local url for loading your project. Can you verify that those keys exist?

**Comment by CrazyWr** [comment]
![image](https://user-images.githubusercontent.com/19635808/28551654-015226ec-711c-11e7-8065-6f3520e0cae4.png)
like this

**Comment by CrazyWr** [comment]
wait a second.  why it is 'expe'xxxxxxxxx rather than 'expo'xxxxxxx

**Comment by terribleben** [comment]
Interesting. When you run `exp start` you should see something like 
```
[exp] Your URL is
exp8b0564d169.....://something
```
(using your `detach.scheme` instead of `http`)

But based on your earlier screenshot, that's not happening. Can you make sure you have the latest version of `exp`?

**Comment by CrazyWr** [comment]
![image](https://user-images.githubusercontent.com/19635808/28551747-8f65afc6-711c-11e7-9702-5b4c4dcf6882.png)

**Comment by terribleben** [comment]
Interesting -- Pinging @jesseruder. It seems like everything is configured correctly but `exp` is not picking up the detached scheme of this project. Changing the issue name to clarify

**Comment by CrazyWr** [comment]
I think I should `exp detach` again, but it's a difficult task because of the GFW...... and it's strange 
I used VPN or not is the same result

**Comment by CrazyWr** [comment]
@terribleben  I tried ro run the project just now , it does look like picking up detached scheme, but also crashed in XCode
![image](https://user-images.githubusercontent.com/19635808/28552328-56f5c230-7120-11e7-8f47-4361e92cd0f1.png)

![image](https://user-images.githubusercontent.com/19635808/28552373-a5dc7a24-7120-11e7-9349-f027e1b0b481.png)

**Comment by CrazyWr** [comment]
finally, solve the problem by upgrading to EXPOSDK 18.0.0
