### ISSUE TITLE
[Expo SDK] -- lottie version not up to date

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#4031]
### Environment

```

  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.4.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.14.0
```

### Steps to Reproduce
```
import { DangerZone } from 'expo';
const { Lottie } = DangerZone;

<Lottie
  ref={animation => {
      this.animation = animation;
  }}
  style={styles.lottie}
  autoplay
  loop={false}
  onAnimationFinish={this.animationFinish}
  source={require('./...json')}
/>
```
### Expected Behavior

Lottie component has `onAnimationFinish` as a prop.

### Actual Behavior

onAnimationFinish does not fire. I think expo is running an old version of Lottie.

**Comment by matheuscouto** [comment]
Is your animation in loop? In Lotties api doc there is a note:

> ... this callback will be called only when loop is set to false.

**Comment by lightninglu10** [comment]
No it's not in a loop. Loop is set to false.

**Comment by AdamJNavarro** [comment]
Hey @lightninglu10,

We usually update our third-party library dependencies upon new SDK releases. As long as we don't encounter any breaking changes, we'll try to get lottie updated. Since we try our best to keep github issues reserved for actual bugs, I'm going to close this issue.

Cheers,
Adam

**Comment by Hirbod** [comment]
I can also confirm: the callback won't be fired.
