### ISSUE TITLE
[Android, Standalone] Delayed linking when it is in backgrounded

### ISSUE THREAD

**Issue by ooyun0** [expo/expo#4032]
### Environment

- SDK version: 32
- Target: Standalone
- Galaxy Note5 (SM-N920S)
- Android 7.0

### Steps to Reproduce

Launch app (scheme: 'testest'), leave it in background.

- `Lining.openURL('testest://root')` from another expo app

or 

- `adb shell am start -W -a android.intent.action.VIEW -d "testest://root"`

adb result
<img width="947" alt="스크린샷 2019-04-21 오후 1 52 18" src="https://user-images.githubusercontent.com/20644690/56465661-b7719380-643c-11e9-96fe-27cbee11fefe.png">

### Expected Behavior

Backgrounded app pop up immediately

### Actual Behavior

Backgrounded app pop up after 5 seconds as shown in the picture above

### Reproducible Demo

I just init project using `expo init`, add `scheme: 'testest'` to app.json , and `expo build:android` without modification of the code. (Both templates of "empty" and "tabs" were tested)

**Comment by gomonk3037** [comment]
Any updates?

**Comment by lukmccall** [comment]
Hi @ooyun0, I think this was fixed. I've tested it (in SDK 36) and it workes fine. Here, you can check out logs: 
```
Starting: Intent { act=android.intent.action.VIEW dat=testest://root }
Warning: Activity not started, its current task has been brought to the front
Status: ok
ThisTime: 0
TotalTime: 0
WaitTime: 443
Complete
```

So, I'm closing this issue. However, feel free to reopen it, if this bug occurs in the newest SDK.
