### ISSUE TITLE
background notifications do not work in iOS - regular notifications do

### ISSUE THREAD

**Issue by robbiemu** [expo/expo#4033]
### Environment

  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

### Steps to Reproduce

I believe the steps to reproduce are

1. start and iOS target project, successfully configure it for APNs.
2. register to receive APNs at runtime - also, for convenience, Alert the Expo token so you cna use the web interface to send the APN.
3. have a callback that for APNs that can verify that you have received a message -- for example, Alert the payload.
4. use the web interface to send the APN. First, with a body so you can verify it is successfully set up. then with exactly the payload:  with json data, category, and content available

### Expected and Actual Behavior

Apple's "content-available" tag was designed to facilitate background notifications: ie, notifications that allow he app to do small background tasks on demand, without notification to the user. This was so true that they posted an official recommendation that _no other tags be turned on if the content-available tag is_. This has been relaxed over time, but there are still popular swift and javascript libraries offer "silentNotification" methods that do not accept options.

Expo's push notification implementation had been a popular voted item and the discussion threads there make it clear that the design chosen was chosen specifically because, in comparison to other approaches, it was friendlier to background notifications on iOS.

Background notifications on iOS currently _do not work_.

--

At first I was worried that expo had a custom notification system (had me thinking "coulda had a p8", if you know the commercial like that, haha). In the end, I was impressed with how direct and easy sending messages with expo's push notification service is. The only problem I ran into was in coming to realize that this *will never work* on a simulator. Otherwise, it's pretty spiffy really, even easier than a p8.

But I'm noticing a different pattern of behavior when I try to send a background notification.  In that instance, nothing seems to be happening.

My platform is iOS, and my App component has an extension that it binds to `this` and then fires off only once:
# extensionAPNs.js
```js
import { Alert } from 'react-native'
import { Permissions, Notifications } from 'expo'
import AsyncStorage from '@callstack/async-storage'

import { handleNotification } from '@src/lib/APNs'

export async function registerForPushNotifications () {
  const { status } = await Permissions.getAsync(Permissions.NOTIFICATIONS)

  if (status !== 'granted') {
    const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS)
    if (status !== 'granted') {
      Alert.alert('received no permission to listen to APNs')
      return
    }
  }

  const expoToken = await Notifications.getExpoPushTokenAsync()
  Alert.alert('recieved permission to listen to APNs with token ' + expoToken)

  this.subscription = Notifications.addListener(handleNotification)

  this.setState({ expoToken })
  AsyncStorage.setItem('expoToken', expoToken)
}
```

```js
import { Alert } from 'react-native'

export async function handleNotification () {
  Alert.alert(JSON.stringify(arguments))
  console.log('arguments', arguments)

```
Elsewhere, I share that token so I can message it. I noticed it wasnt working when my server sent its background message, although it does register as a success from the POST (didn't open the app, didn't add the Alert popup... even if the app was in the foreground, no popup). So I went to the [PN tool](https://expo.io/dashboard/notifications) and sure enough, the first "hello world" that I did worked. Immediately, it works, too. 

But if I configure it like my own message, with json data, category, and content available -- **and nothing else**, nothing happens. Not in the foreground, not in the background. Not when closed. :frowning:

### Reproducible Demo

https://snack.expo.io/rkz1sx554 -- note some work will need to be done, including running this on a physical device, to test. This is not my fault, it is part of expo's fundamental design.

**Comment by cruzach** [comment]
Hey @robbiemu ,

Could you share how you're sending your push notifications? That way I can get a fuller picture of what's going on

Thanks!
-Charlie

**Comment by robbiemu** [comment]
I believe that is in the op, @cruzach --specifically using the web tool, its 

* json data (`{ "a": 1 }`)
* category ('@user/experienceId:notification')
* and a check mark on "content available"
and of course the Expo token

from my server instead of the PN web tool, actual data will be the category and content-available

**Comment by cruzach** [comment]
Sorry I should've been clearer- Since the PN tool is resulting in everything working as it should, but when sending from your server you don't receive any notification, I need your server code for sending the notification to repro the issue.

-Charlie

**Comment by robbiemu** [comment]
No Charlie I’m afraid you didn’t understand the OP.  The PN tool does not work nor does my code when trying to send a background notification to my app.

  The pn tool *does work*  when sending a foreground notification to my app.

**Comment by robbiemu** [comment]
pretty sure that if my message has no message body (as per the PN tool's input for that field), my `handleNotification`method is not called, and otherwise, it is ( content_available has no effect )

**Comment by robbiemu** [comment]
Ive gotten a bit more use in and I see that my solution with the badge also is not working. It *does* work, both updating the badge (in the case that I set it to something other than what it was before) and running my handler function when the app is in the foreground. However, the badge decoration is changed without ever triggering my handler when the app is not in the foreground.

**Comment by cruzach** [comment]
Hi @robbiemu,

My bad, I wasn't understanding exactly what you were reporting as a bug. Sorry for the miscommunication on my part!

Handling push notifications in the background may be something we implement in the future, but right now Expo doesn't support it ([source](https://docs.expo.io/versions/v32.0.0/introduction/why-not-expo/)).

FYI: There is an open [feature request](https://expo.canny.io/feature-requests/p/handle-push-notifications-in-the-background) for this, so going to close this issue

**Comment by robbiemu** [comment]
That’s all right, I’ve already assumed that it is nonfunctional and worked around it.  I do wish that you would not close the ticket until revisiting the documentation however because it’s not at all clear that that is the case.  The presence of a content available flag specific to iOS strongly indicates that it is in fact supported. People like me who further research it and find the feature request where it was first implemented will encounter in this discussion many decisions that were made in order to support background processing,  as well as a direct and lively conversation about how to best implement that  specific behavior.

I feel like it should be mentioned in the first four or five paragraphs but certainly by the time that the content available flag is  included in the specification, it should be noted that it is not functional.
