### ISSUE TITLE
can't find variable appDevice

### ISSUE THREAD

**Issue by hoi030** [expo/expo#4034]
How can I fix this problem?

<img width="358" alt="螢幕截圖 2019-04-22 上午2 37 18" src="https://user-images.githubusercontent.com/47256153/56474215-5338e900-64a9-11e9-9fee-a1d155d36af7.png">

### Please note that Expo CLI issues opened in the core Expo repository will be closed.

**Comment by AdamJNavarro** [comment]
Hey @hoi030,

Is this occurring on a new project or an existing one? If it's an existing one, can you try creating a new project via `expo init` and see if you encounter the same issue?

Cheers,
Adam

**Comment by hoi030** [comment]
sorry for the late reply, i solved it by opening a new project
thank you.

But I have another problem now.

Since I am new to programming ,Can i ask you some question about facebook
login here?

Adam Navarro <notifications@github.com> 於 2019年4月23日週二 上午5:17寫道：

**Comment by AdamJNavarro** [comment]
Glad you got the first issue resolved! As for the facebook issue, please create a topic and post your question [here](https://forums.expo.io/c/sdk).
