### ISSUE TITLE
Undetermined Expo Push all the time

### ISSUE THREAD

**Issue by ThalesCrisostomo** [expo/expo#4036]
When push notifications are requested, the response is always undetermined.

`const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);`

Test run with Testflight

https://ibb.co/P1xm83w

Expo sdk 32
expo cli: 2.15.3

**Comment by AdamJNavarro** [comment]
Hey @ThalesCrisostomo,

This is a known issue and a PR has been merged to fix this. https://github.com/expo/expo/pull/3737/files

Cheers,
Adam

**Comment by giacomocerquone** [comment]
@AdamJNavarro only way to use that fix is to wait for sdk 33 right?

**Comment by HOllarves** [comment]
I'm running SDK 33 and still encountering the same issue. Any help would be appreciated.

I've traid revoking everything by my AppID and then issuing an `expo build:ios -c` command and asking Expo to handle everything and no luck. Don't really know what else to do besides attempting to manually import the files, which knowing how Apple works, is very likely to be messed up.
