### ISSUE TITLE
[Chat apps] Can't cancel or replace a push notification on new incoming messages

### ISSUE THREAD

**Issue by vandrieu** [expo/expo#4039]
### Steps to Reproduce

Build a dummy chat app that sends a push notification when a user receives a new message

### Expected Behavior

1. User A sends 1 message to User B
2. User B receives a notification but doesn't check his phone. Meanwhile, user A sends 10 new messages.
3. User B checks his phone. He has a notification that reads "11 new messages from User A" (just like any real world chat app)

### Actual Behavior

User B will get 11 individual notifications when he checks his phone, 1 per message.
That's because as soon as the 1st notification is sent to notify the 1st message, there is no way to cancel or replace it with the next one.

There would be if the app was running, using a listener, but while the app is closed we can work only server side, and server side expo SDK doesn't seem to offer the feature to cancel or replace a notification, which is mandatory for implementing a decent chat app.

**Comment by AdamJNavarro** [comment]
Hey @vandrieu,

We definitely agree this behavior is needed for providing a proper experience with app's that leverage chat functionality. Would you mind creating a detailed [feature request](https://expo.canny.io/feature-requests) about exactly you would need and want with regards to the Push Notification API? We try to keep github issues reserved for bugs.

Cheers,
Adam

**Comment by vandrieu** [comment]
Done, here: https://expo.canny.io/feature-requests/p/remotely-replace-or-cancel-a-push-notification
