### ISSUE TITLE
Ref inside modal not working anymore on Expo SDK19

### ISSUE THREAD

**Issue by mmazzarolo** [expo/expo#404]
Hello there,
I'm the maintainer of [react-community/react-native-modal](https://github.com/react-native-community/react-native-modal) which [since Expo SDK19 doesn't work correctly anymore](https://github.com/react-native-community/react-native-modal/issues/42).  

I never used Expo SDK before, but I debugged the issue a bit and created a super-minimal case of it.  
Basically the issue is that the `ref`s of the components inside a [React-Native's Modal](https://facebook.github.io/react-native/docs/modal.html) don't work at all since Expo SDK19.  
They worked perfectly before this release and they're still working on the last version of React-Native (0.46).  

Maybe the Expo component is overriding the React Native's original Modal behavior in some way?  

```javascript
import React from 'react';
import { Modal, StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  componentDidMount() {
    console.log('ref outside the modal: ', this.textOutsideModalRef);
    console.log('ref inside the modal: ', this.textInsideModalRef);
  }

  render() {
    return (
      <View>
        <Text ref={ref => (this.textOutsideModalRef = ref)}>
          {'Hello, I am a Text outside of a Modal and I have a ref'}
        </Text>
        <Modal>
          <Text ref={ref => (this.textInsideModalRef = ref)} visible={true}>
            {'Hello, I am a Text inside a Modal and I should have a ref too :('}
          </Text>
        </Modal>
      </View>
    );
  }
}
```

Thank you in advance and keep up with the good work!

**Comment by satya164** [comment]
Can't repro on snack - https://snack.expo.io/BkcmW57LW

![image](https://user-images.githubusercontent.com/1174278/28530751-1aa93b8a-7095-11e7-95b9-e9f99e3a3b0f.png)

**Comment by mmazzarolo** [comment]
Hi @satya164,
yep, I gave it a try to, I can confirm that it works on snack.expo.io but not on a clean project (or better: it doesn't work for me and the people on the issue).  

Let me know if I can help in any way :)
<img width="1495" alt="schermata 2017-07-24 alle 17 33 45" src="https://user-images.githubusercontent.com/9536354/28531661-c927e8c6-7097-11e7-9826-ac870a6cc0bc.png">

**Comment by hysan** [comment]
Just adding another confirmation. This was working on SDK17 and SDK18 for me. It was only when upgrading to SDK19 did this break in my project. Downgrading to SDK18 (or 17) seems to be the only workaround that I can find right now.

**Comment by mmazzarolo** [comment]
Yup, let me know if I can provide more info on the matter.

**Comment by dikaiosune** [comment]
@mmazzarolo can you paste the package.json from your repro case? I think this bug was fixed in the 19.0.1 release of the `expo` npm package.

**Comment by KeabetsweFx** [comment]
Hi @mmazzarolo I've just tested it with expo npm package 19.0.1 and it works fine, thanks for following up on this issue I will update the people on the issue above and then you can close it. Thanks for the help @dikaiosune

**Comment by mmazzarolo** [comment]
Thank you @dikaiosune and @KeabetsweFx! 
Closing the issue.

**Comment by wiloke1** [comment]
PLEASE HELP ME
expo 26.0.0
this._imageLightBox // undefined
![screenshot 2018-05-14 15 52 57](https://user-images.githubusercontent.com/5530913/39987833-fe29c776-578f-11e8-9208-0dac695c44cd.png)
