### ISSUE TITLE
[Unhandled promise rejection: SyntaxError: JSON Parse error: Unexpected identifier "Phaza"] 

### ISSUE THREAD

**Issue by olee2002** [expo/expo#4040]
``` [Unhandled promise rejection: SyntaxError: JSON Parse error: Unexpected identifier "Phaza"]
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- ... 8 more stack frames from framework internals
```

I have been working with Location with Expo and a post call to create a location at every 15sec interval. 
Everything seems to be working great until today, I was running the app to test and start seeing this error message. 
 I am not even sure if it is related to Expo at all but just want to see if anyone encounter this error message before?
 I checked on the postman so I know that the create location route is working well but get this error.

```js
async componentDidMount() {
      const TIME_INTERVAL = 1000 * 15
      await this._getLocationAsync()
      const lat = await AsyncStorage.getItem('lat')
      const long = await AsyncStorage.getItem('lng')
      const location = await AsyncStorage.getItem('location')
      this.setState({ location })
      if (lat && long) {
      await setTimeout(() => createLocation({ lat, long }), 1000)
      await setInterval(() => createLocation({ lat, long }), TIME_INTERVAL)
      }
   }
```

**Comment by brentvatne** [comment]
at some point you are trying to parse a string of text as JSON where the text is just "Phaza" :O you might want to look wherever you're parsing JSON and verify that the string that you're parsing is valid

**Comment by olee2002** [comment]
The thing is the "phaza" is not done by me and seems to be coming from one of those packages that either Expo or React native uses.

**Comment by brentvatne** [comment]
it probably comes from whatever backend you're interacting with

**Comment by olee2002** [comment]
Yup.. Apparently it was. Sorry to have wasted your time on this matter and
I appreciate your patience!
