### ISSUE TITLE
Upstream takeSnapshotAsync React ref object support

### ISSUE THREAD

**Issue by fson** [expo/expo#4042]
Support for ReactRef objects was added in to `takeSnapshotAsync` in SDK 32 (https://github.com/expo/expo/pull/2771). To be able to remove the `takeSnapshotAsync` API from the `expo` package in favor of importing directly from `react-native-view-shot`, we should upstream the support for ref objects to `react-native-view-shot`.

**Comment by sjchmiela** [comment]
Submitted https://github.com/gre/react-native-view-shot/pull/212
