### ISSUE TITLE
[web] expo-local-authentication support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#4045]
- Emulate fingerprint authentication with [WebAuthn](https://www.w3.org/TR/webauthn/)
- [caniuse](https://caniuse.com/#search=webauthn)
- demo https://github.com/fido-alliance/webauthn-demo

**Comment by Jonatthu** [comment]
@EvanBacon Is this something in progress?

**Comment by cyrfer** [comment]
@EvanBacon will this happen soon?

**Comment by EvanBacon** [comment]
It's not something I'm planning on working anytime soon. Happy to review a PR.
