### ISSUE TITLE
[docs] Saying uploading Firebase Cloud Messaging server key to Expo is mandatory so that Expo can send notifications to your app, while it's not true

### ISSUE THREAD

**Issue by vandrieu** [expo/expo#4050]
Docs say "For Android, you'll also need to upload your Firebase Cloud Messaging server key to Expo so that Expo can send notifications to your app. This step is necessary unless you are not creating your own APK and using just the Expo Client app from Google Play."

That's not true. I'm currently using my standalone android app that I build using "expo build:android" and installed by downloading the APK, I'm receiving push notifications on my device, and I have never uploaded any Firebase Cloud Messaging server key to Expo. 

Actually, I have never ever logged into Firebase, I don't have an account.

So why would the docs say that?

**Comment by ide** [comment]
It is not intended for notifications to work without an FCM key. If it's working without uploading an FCM key that is unintended behavior and may change at any time. Always provide an FCM key.
