### ISSUE TITLE
[docs] Update how to import modules + installation instructions

### ISSUE THREAD

**Issue by ide** [expo/expo#4052]
The `expo` package in SDK 33 will warn when importing modules outside of a smaller core (https://github.com/expo/expo/pull/4047). We need to reflect this change in the docs.

- We currently show how to import a module two different ways for the managed & bare workflows. Now there is just one way for both workflows.
- The import syntax differs per module. Sometimes use import star, other times use the default import. Need to look at the code to determine the right syntax.
- Also need a guide on `expo install` for the managed workflow e.g. "Installing Foundation Unimodules".

**Comment by redpandatronicsuk** [comment]
Would be nice if you could also add instructions on how to install modules straight from the Github repository, as opposed to from npm. Kinda related to my question here: https://forums.expo.io/t/recommended-way-for-using-expo-packages-straight-from-github/22022

Thanks

**Comment by cruzach** [comment]
API docs are up-to-date with import syntax and specifying `expo install`, so I'm going to close this

@redpandatronicsuk you can [install a specific branch](https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a), if you want, although it's probably better to wait for the officially released version
