### ISSUE TITLE
How to set android detached publishedUrl and embeddedResponses?

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo#4054]
### Environment

Expo CLI 2.15.4 environment info:
System:
OS: macOS 10.14.4
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 8.11.4 - /usr/local/bin/node
Yarn: 1.5.1 - /usr/local/bin/yarn
npm: 5.6.0 - /usr/local/bin/npm
Watchman: 4.7.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.0 AI-171.4443003
Xcode: 10.2/10E125 - /usr/bin/xcodebuild
npmPackages:
expo: 32.0.6 => 32.0.6
react: 16.5.0 => 16.5.0
react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
react-navigation: 3.7.1 => 3.5.1
npmGlobalPackages:
expo-cli: 2.15.4

### Steps to Reproduce

Step 1. I follow [Hosting An App on Your Servers](https://docs.expo.io/versions/latest/distribution/hosting-your-app/#__next) 
use command "expo export --public-url https://my-bundle-url/"

Step 2.
I try update android/app/src/main/java/host.exp.exponent/MainActivity
publishedUrl value to "exp://my-bundle-url/" and change AppConstants assets://shell-app-manifest.json and embeddedResponses value.

Step3
I build apk and install my android device
But, if I offline device network will showing Error
Uncaught Error: java.net.UnknownHostException: Unable to resolve host "my-bundle-url/"

How to set android detached publishedUrl and embeddedResponses?
Any help? Thank you

**Comment by cruzach** [comment]
Hi @rxhivzero,

Sorry about this issue! When you build with network access, does it work as it should? 
Also, could you let me know what SDK version you're using, and what version of the expo-CLI? 

The issue template asks for all the info we need 👍 

Thanks!
-Charlie

**Comment by rxhivzero** [comment]
@cruzach 

Yes! It build apk work with network access.

Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: 32.0.6 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: 3.7.1 => 3.5.1 
    npmGlobalPackages:
      expo-cli: 2.15.4

**Comment by cruzach** [comment]
Thanks!

There's actually already an open issue for making ejected apps compatible with self-hosting (#3553)

Closing this since it's asking for the same thing.
