### ISSUE TITLE
Edit info.plist (App Transport Security)

### ISSUE THREAD

**Issue by AzizAK** [expo/expo#406]
Hello,

Thank you guys for the great IDE. but i'm wondering how can i edit the info.plist and add exception URL's in App Transport Security ?

**Comment by terribleben** [comment]
Hi,

1) Right now we disable App Transport Security altogether (though this will change in the future, and we'll add a configuration for it at that point).
2) Besides that, most info.plist changes you would want are covered [here](https://docs.expo.io/versions/v19.0.0/guides/configuration.html).

**Comment by terribleben** [comment]
Sorry if I was unclear in my last comment: the Expo app completely disables App Transport Security already.

![image](https://user-images.githubusercontent.com/1316332/28553424-637db9a4-70a8-11e7-9283-6f8b277f45ab.png)

**Comment by dreadful-dev** [comment]
@terribleben My apologies for commenting on an old, closed issue, but does Expo still disable App Transport Security? I'm running into issues where http requests are failing on iOS, but are successful on android, and hoping this is something I can resolve without ejecting my application.

**Comment by terribleben** [comment]
We do still disable it at the time of writing. Our configuration in info.plist is currently identical to the one in my earlier screenshot. At the moment I don't know of any other reports of http requests failing within our iOS apps.

**Comment by idgafl7** [comment]
Is there any way to enable ATS and add exceptions through app.json yet? I need ATS enabled for security reasons.
