### ISSUE TITLE
"App not installed" error after building android app

### ISSUE THREAD

**Issue by moahammadalt** [expo/expo#4061]
after I ran `expo build:android` i got the apk file built successfully but when I try to install it in many devices, it is not being installed and it shows "App not installed" error.

and here is my package.json:

> {
  "name": "some-app",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-navigation": "^3.1.2",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  }
}
`

**Comment by AdamJNavarro** [comment]
Hey @moahammadalt,

Sorry you're running into this. Can you elaborate on what devices you've tried installing on that results in the `Application Not Installed` error such as model, OS version, manufacturer, etc? Also, if you could create a fresh project, build an `.apk` and see if it also errors like your current one that would be helpful.

Cheers,
Adam

**Comment by moahammadalt** [comment]
@AdamJNavarro  i  tried to install it on p20 light Hawaii and Samsung tab s device, both of them showing this [error](https://res.cloudinary.com/dqueufbs7/image/upload/v1556140443/images/Screen_Shot_2019-04-25_at_00.09.03.png)

i am wondering if i am using an old react-native dependency, beause it is a 3-month-old app

**Comment by moahammadalt** [comment]
i am not even able to create a new expo project, i created another [issue](https://github.com/expo/expo/issues/4064) for that

**Comment by moahammadalt** [comment]
the problem was in the android packager name in my app.json

so it was like that:

"package": "com.<myName>.<appName>"
i replaced myName with the appName like that :

"package": "com.<appName>.<appName>"
and it worked like a magic and I was able to successfully build and install the app on multiple devices

**Comment by cruzach** [comment]
Awesome! Thanks for sharing the solution here 😄
