### ISSUE TITLE
expo init app stuck forever at 50%

### ISSUE THREAD

**Issue by moahammadalt** [expo/expo#4064]
I am trying to start a new expo project with `expo start someApp` on my mac but the terminal stuck at 50 % forever, I got expo 2.15.4 version, the same problem happened also on a windows machine.
[click to see the problem](https://res.cloudinary.com/dqueufbs7/image/upload/v1556142665/images/Screen_Shot_2019-04-25_at_00.46.52.png)

**Comment by AdamJNavarro** [comment]
Hey @moahammadalt,

You need to enter values into those fields and then press enter. It won't continue progress until valid values have been entered and you hit `enter` to continue.

Cheers,
Adam
