### ISSUE TITLE
How to implement RTSP in Expo?

### ISSUE THREAD

**Issue by ilyaux** [expo/expo#4065]
Good day there was a need to implement streaming video in the application. Format links like this :

`rtsp://user:password@**.**.***.**:****/Streaming/Channels/`

Are there any ways to implement this in Expo?

Is it possible to implement it somehow through WebView ?

Maybe someone knows how to implement the module in Expo project : [react-native-vlc-player](https://github.com/ekreative/react-native-vlc-player)

**Comment by AdamJNavarro** [comment]
Hey @ilyaux,

We try to keep github issues reserved for bugs. For questions such as this one, please feel free to create a post on our forums. For this specific instance, it would belong [here](https://forums.expo.io/c/how-to).

Cheers,
Adam
