### ISSUE TITLE
[docs] add [content-type] to Hosting An App on Your Servers

### ISSUE THREAD

**Issue by u0x01** [expo/expo#4069]
[Hosting An App on Your Servers](https://docs.expo.io/versions/v32.0.0/distribution/hosting-your-app/#asset-hosting) is not description that self-hosted server static files must set `javascript bundle`'s HTTP header `Content-Type` to `application/javascript`.

-------------------------------------------

this ota issue haunted me for a long time, i have to check native source code to solve this issue. can u add doc to ota module that when detached (or standalone) app and self-hosted server must deploy return content-type as `application/javascript` instead `text/javascript`, if not it will updates will panic ‘failed to fetch new update:
![image](https://user-images.githubusercontent.com/9703404/56712887-b1dcbc00-6762-11e9-81b6-23bc31a6150e.png)

**Comment by cruzach** [comment]
Hi @u0x01,

Are you not using the [Updates](https://docs.expo.io/versions/v32.0.0/sdk/updates/) module to check/reload any js updates from your server?

-Charlie

**Comment by cruzach** [comment]
@u0x01 it's not clear exactly what needs to be added to the docs and where, could you explain a little more? Or better yet, open a PR?

**Comment by sandrina-p** [comment]
Today I'm facing the same issue.

I didn't understand why OTA updates weren't working on iOS. I released a new build (standalone and hosted on my own servers) to testFlight.

It has a new button "Check for new updates" that calls `Updates.checkForUpdateAsync()`. When I click it, it fails with the error "Failed to fetch new update" and I don't know what I should change :/

**Comment by sandrina-p** [comment]
Actually, I already understood what @u0x01 meant.

In my case, I'm using Firebase to host my app. At `firebase.json` I need to explicitly set the headers for JS files and add `Content-type` as `application/javascript`.

```diff
  "hosting": [
    {
      "target": "native",
      "public": "dist",
+      "headers": [
+        {
+          "source": "**/*.js",
+          "headers": [
+            {
+              "key": "Content-Type",
+              "value": "application/javascript"
+            }
+          ]
        }
      ]
    }
  ],
```
