### ISSUE TITLE
Verbose mode for exp/xde

### ISSUE THREAD

**Issue by Cryrivers** [expo/expo#407]
I currently upgraded my project to Expo 19. However, I cannot run it anymore.
```
[exp] Starting React Native packager...
[exp] Scanning 800 folders for symlinks in /Users/blabla/Desktop/blabla/packages/blabla/node_modules (6ms)
[exp] EISDIR: illegal operation on a directory, read
```
The error is not verbose enough to pinpoint the cause, even `node --inspect --debug-brk` cannot help.

So is there any way to have more verbose logs? or could we have this feature in the future?

Thanks

**Comment by brentvatne** [comment]
seems like a somewhat useful error message: https://www.google.ca/search?q=EISDIR+node

I agree though it would be better to provide some more information.

**Comment by dikaiosune** [comment]
Unfortunately, I'm pretty sure this particular error message comes from the React Native packager. @brentvatne it could be related to some of our configuration, but it seems like maybe this needs an upstream report?

**Comment by Cryrivers** [comment]
@dikaiosune I found the cause of my case, which is having wrong configuration for `react-native-typescript-transformer`. Not sure if verbose error messages for React Native packager or other plugins could be exposed.

**Comment by bkostrowiecki** [comment]
@Cryrivers , hi,

I encountered the same problem with `react-native-typescript-transformer` as you, so maybe you could bring some details to the table? Because I cannot fix it by myself. I have no experience with `react-native` and `expo` at all.

**Comment by Cryrivers** [comment]
@bkostrowiecki hey. to be honest, i don't know the root cause. I just strictly followed the instruction of `react-native-typescript-transformer`.
