### ISSUE TITLE
[docs] Mention the uses of @expo/vector-icons with expo-font

### ISSUE THREAD

**Issue by jarvisluong** [expo/expo#4070]
If a bare react native app uses `expo-font` to load fonts in run time, and by the documentation of `expo-font`: 

> StyleSheet.setStyleAttributePreprocessor('fontFamily', Font.processFontFamily);

This will make `react-native-vector-icons` incompatible with that bare react-native app. In this case, we need to inform users to use `@expo/vector-icons` instead.

I'm happy to make a pull request to improve the documentation, I just need to know where the most suitable place is? 🤔

**Comment by brentvatne** [comment]
we're going to remove the need to do `StyleSheet.setStyleAttributePreprocessor('fontFamily', Font.processFontFamily);` in expo-font so this won't be an issue in the future, should be done soon

**Comment by expjess** [comment]
Looks like @brentvatne made this [optional/experimental](https://github.com/expo/expo/blob/bb19ae51ec436f1e229fa7da178f6e70e8008291/docs/pages/versions/v37.0.0/react-native/stylesheet.md#methods) ❤️

**Comment by brentvatne** [comment]
indeed this is no longer needed anymore in bare apps because we no longer apply any scoping prefix to font family names in bare apps
