### ISSUE TITLE
expo-image-picker build fail, after updating to latest version

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#4073]
Steps I followed:

1- yarn remove expo-image-picker
2- yarn add expo-image-picker
3- yarn android

**version** "expo-image-picker": "^4.0.0",
Build Error:
```
node_modules/expo-image-picker/android/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':expo-image-picker'.
> Project with path ':unimodules-core' could not be found in project ':expo-image-picker'.
```

**Comment by cruzach** [comment]
Hi @shubhamdeol ,

Is this in a `bare` project created with Expo-CLI, or a React Native project create with `react-native init`?

-Charlie

**Comment by shubhamdeol** [comment]
Hi @cruzach  Yes, this is in ```bare``` project created with Expo-CLI

**Comment by shubhamdeol** [comment]
```
if (new File(rootProject.projectDir.parentFile, 'package.json').exists()) {
  apply from: project(":unimodules-core").file("../unimodules-core.gradle")
}
```
I can see this code written in build.gradle inside android. I guess it's not able to find it.

**Comment by bbarthec** [comment]
@shubhamdeol please check out instructions for installing `unimodules` in `bare` project. https://github.com/expo/expo/tree/master/packages/expo-image-picker#installation and https://github.com/unimodules/react-native-unimodules

**Comment by shubhamdeol** [comment]
@bbarthec  unimodules are already there in bare react native projected created with expo right?
Why I need to install again

**Comment by bbarthec** [comment]
I've just created working android project following these steps and succeeded in launching it on device:
1. `expo init`
	a. template: `expo-template-bare-minimum`
	b. named it
	c. used yarn
2. `cd <newly-created-project>`
3. `yarn android`
	a. resulted in successful launch on device
4. `yarn remove expo-image-picker` // steps you've mentioned
5. `yarn add expo-image-picker`
6. `yarn android`
	a. success again

Packages versions for some reference:
- `expo-cli@2.15.4`
- `expo-image-picker@4.0.0`
- `unimodules-core@1.0.0`

@shubhamdeol, may I ask you to check that minimal flow I've presented?

**Comment by shubhamdeol** [comment]
@bbarthec  yeah, I followed the above steps, the build is successful now. My project was build with expo-cli@2.11.0, maybe that's the reason. If I will reproduce this with expo-cli@2.11.0. Would you guys consider fixing this?

**Comment by cruzach** [comment]
@shubhamdeol,

Using expo-cli@2.11.0, you cannot create a bare minimum project, it only provides options for either `blank` or `tabs`, so I think there is something missing.

If you can provide steps to repro the issue then I'm happy to reopen! but for now will close

-Charlie
