### ISSUE TITLE
Remove jsc-android dependency from ExpoKit

### ISSUE THREAD

**Issue by ide** [expo/expo#4079]
RN 0.59 upstream uses the new JSC, so we don't need to include it ourselves in ExpoKit (and expoview, etc...).

**Comment by rickysullivan** [comment]
I'm trying to add `android-jsc-intl` and my Expokit project is throwing me an error `Program type already present: org.webkit.androidjsc.BuildConfig`. Is there a workaround to allows a custom JSC?

**Comment by pencilcheck** [comment]
Does jsc-android included in Expokit in SDK 34 supports international timezone support?

**Comment by ide** [comment]
No, the included version of JSC is the lightweight version.

**Comment by ide** [comment]
@wkozyra95 Do we use the copy of JSC that RN specifies, or do we still override it in ExpoKit? (This is just a clean-up task that isn't so important but nice to have.)

**Comment by wkozyra95** [comment]
We are using our own version, but at this point, it's the same as one in latest react-native.

@pencilcheck expokit contains both versions of jsc, if you are ejected you can switch dependency to intl one.
You can read more here https://github.com/react-native-community/jsc-android-buildscripts

@ide Can you clarify what you mean by "remove dependency"? Do you mean gradle or package.json? Are you taking into account that we still need to keep our custom version of JSC to embed in client (it's unversioned)?

If you want to make this change to next sdk without upgrading react-native we would downgrade jsc in that case,  react-native upgraded jsc to the same version as ours in `v0.62` https://github.com/facebook/react-native/commit/58d87940a1a995f0faf1270c0da435b44015575f

**Comment by ide** [comment]
I opened this issue just to remove the lines in the ExpoKit Gradle files that override the version of JSC to use. We first introduced these lines when we sponsored Software Mansion to upgrade JSC years ago. We can wait until RN 0.62 to make this change.

**Comment by ide** [comment]
Closing this as ExpoKit was deprecated earlier and will be finally dropped in SDK 39.
