### ISSUE TITLE
Replacing deprecated lodash modules

### ISSUE THREAD

**Issue by byCedric** [expo/expo#4086]
Hi Dreamteam!

I noticed Expo is using the modular packaged from Lodash. [At CommitLint someone noticed us](https://github.com/conventional-changelog/commitlint/pull/473) that these [packages are deprecated](https://github.com/lodash/lodash/issues/3838#issuecomment-398592530) and not being updated anymore. The [roadmap also states it will drop support](https://github.com/lodash/lodash/wiki/Roadmap#v500-2018) for these modules.

I would recommend swapping to the main build for security and support reasons. Luckily there are still ways to import specific functions from Lodash. You could either tree-shake it, and if that isn't available you can "cherry pick" it:

1. `import { zipObject } from 'lodash';`
2. `const zipOjbect = require('lodash/zipObject');`

I'd be happy to help with this if you agree! 😄 No hard feelings if you don't ❤️ 

Cheers,
❤️ Cedric

**Comment by ide** [comment]
We'd be open to taking PRs to update to the single lodash model with cherry-picked imports (while we still are using Metro, we don't have tree-shaking).

**Comment by byCedric** [comment]
Sounds fair, I'll make a PR tonight (CEST).
