### ISSUE TITLE
[iOS] Facebook Ads AdTriggerView blank screen

### ISSUE THREAD

**Issue by Abdelrahman-Nabil** [expo/expo#4087]
### Environment

 Expo CLI 2.14.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Users\Abdu\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

NOTE: working fine on Android, the issue is only present on iOS.
### Expected Behavior

Properly navigating depending on the action (for example: install now -> navigates to App Store)

### Actual Behavior
I get the following blank screen:
![21e21653-9746-485f-aecf-159f15a40152](https://user-images.githubusercontent.com/24702951/56866426-35074780-69d9-11e9-8d71-3082f9340e0e.jpg)

### Steps to Reproduce
follow Expo's guide in documentation: https://docs.expo.io/versions/latest/sdk/facebook-ads/

### Reproducible Demo

`import { FacebookAds } from 'expo';
const { AdTriggerView, AdMediaView } = FacebookAds;
class AdComponent extends React.Component {
  render() {
    return (
      <View>
        <AdMediaView />
        <AdTriggerView>
          <Text>{this.props.nativeAd.bodyText}</Text>
        </AdTriggerView>
      </View>
    );
  }
}
export default FacebookAds.withNativeAd(AdComponent);`

### Notes
Unregistering components in the file: AdTriggerView.js causes the app to crash with the following error:

`Got unexpected null`
commenting this line as a temporarily fix just to get it working, the error goes away, but the navigation issue is still not resolved:
`context.unregisterComponent(nullthrows(this._trigger));` line 24 in AdTriggerView.js

**Comment by Ematusz** [comment]
Any update on this? I'm having the same issue.

**Comment by girishjjain** [comment]
Are people still having the same issue with SDK v37? Looks like it is broke with SDK v37 and clicking on component in `AdTriggerView` tree does nothing. Does not open blank page either. Wanted to confirm before opening another issue.

**Comment by cruzach** [comment]
Sorry for the lack of response here, I added a comment on #8923 that will hopefully help us find out what the issue is here. Since that issue is newer and has a reproducible demo, I'm going to close this in favor of the new issue just so we can stay organized
