### ISSUE TITLE
Upgrade react-native-gesture-handler to 1.2.0

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#4089]
We might want to upgrade `react-native-gesture-handler` to [`1.2.0`](https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.2.0) in our codebase for SDK33 as it includes a lot of native changes with exciting features and improvements 😍

**Comment by mczernek** [comment]
[#4159](https://github.com/expo/expo/pull/4159)
