### ISSUE TITLE
can't get exponent to install on genymotion, errors with Exponent-1.11.1.apk

### ISSUE THREAD

**Issue by vesper8** [expo/expo#41]
Genymotion is using Android Studio's sdk path.
I ran exp path after running npm install -g exp and made sure it includes the Android Studio sdk path

My app runs on my android hardware device on the exponent app.

When I try to install it (on 5.1 or 6.0) on a Genymotion emulator.. it says 

Uninstalling Exponent from Android device.

Downloading latest version of Exponent

Installing Exponent on device

all good right? But on the emulator nothing is happening at all. No icon.. no app

running adb logcat shows this.. which seems to be the culprit? But why is it invalid? How to clear it and force a valid download?

```
D/        ( 1820): Zip: EOCD not found, /data/local/tmp/Exponent-1.11.1.apk is not zip
W/zipro   ( 1820): Error opening archive /data/local/tmp/Exponent-1.11.1.apk: Invalid file
D/asset   ( 1820): failed to open Zip archive '/data/local/tmp/Exponent-1.11.1.apk'
W/DefContainer( 1820): Failed to parse package at /data/local/tmp/Exponent-1.11.1.apk: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/Exponent-1.11.1.apk
```

**Comment by jesseruder** [comment]
Hmm maybe the download was corrupted? You could try removing `~/.exponent/android-apk-cache/` to force it to redownload
