### ISSUE TITLE
KeyboardAvoidingView 

### ISSUE THREAD

**Issue by cmitz** [expo/expo#4100]
### Environment

Diagnostics: 

```
± % expo diagnostics                                                                                                                        !3765

  Expo CLI 2.15.4 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
      Yarn: 1.15.2 - /usr/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
```

### Steps to Reproduce

My goal is simple, when the keyboard is visible, the input field needs to move up to make sure it does not get blocked by the keyboard.

1. Make a new repo with `expo init`
1. Add a `<KeyboardAvoidingView>` just like mentioned in the [React Native docs](https://facebook.github.io/react-native/docs/keyboardavoidingview)

### Expected Behavior

1. The View containing the Text and TextInput element would somehow move up

### Actual Behavior

1. The TextInput disappears behind the keyboard

### Reproducible Demo

Can be found here: https://github.com/cmitz/expo-keyboard-avoiding-behaviour

### Extra information

I took a look at #1065 , which seems to demonstrate the exact opposite. I tried this, it worked. Look at https://github.com/cmitz/expo-keyboard-avoiding-behaviour/blob/master/app.json#L19, after commenting this in the screen resizes correctly but the KeyboardAvoidingView is not needed at all...

It might be that I have totally wrong expectations, but if so: please tell me.

### Screenshots

<img alt="Screenshot_1556634480" src="https://user-images.githubusercontent.com/5594436/56969248-0c13bd80-6b65-11e9-8395-844d7a541a45.png" width="256" align="left" />
<img alt="Screenshot_1556634482" src="https://user-images.githubusercontent.com/5594436/56969258-0fa74480-6b65-11e9-83bb-c55ea861c00b.png" width="256" />

**Comment by AdamJNavarro** [comment]
Hey @cmitz,

Can you make sure this is an Expo issue by trying to reproduce the issue in a vanilla RN project running version `0.57` as that is what SDK32's RN fork is based on. You can do so by running `react-native init AwesomeProject --version X.XX.X`. If the issue occurs as well, the best course of action would be to create an issue on the RN repo. If it does not, we'll continue investigating on the Expo side of things.

Cheers,
Adam

**Comment by cmitz** [comment]
Will close this, since it seems it's a more common problem, also for `react-native init` people.
Not sure how to solve this though, seems tricky.

https://medium.com/@nickyang0501/keyboardavoidingview-not-working-properly-c413c0a200d4
