### ISSUE TITLE
Notifications does not work

### ISSUE THREAD

**Issue by SergeyShablenko** [expo/expo#4101]
### Environment

Expo CLI 2.11.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1

target: Standalone for both IOS and Android

### Steps to Reproduce

try to send any notification

### Expected Behavior

notification is sent and received by devices

### Actual Behavior

notification is sent but was not received by any device

It was working for few months, but stopped about month ago, does expo have limitations for notifications or something else?

**Comment by cruzach** [comment]
There's no limitations, and unfortunately without more information it's tough to say what could be wrong. If you fetch the [push receipts](https://docs.expo.io/versions/latest/guides/push-notifications/#push-receipts), it should provide you with more information regarding the error. 

Most likely it's either a case of 
>DeviceNotRegistered: the device cannot receive push notifications anymore and you should stop sending messages to the corresponding Expo push token.

or 

>InvalidCredentials: your push notification credentials for your standalone app are invalid (ex: you may have revoked them). Run expo build:ios -c to regenerate new push notification credentials for iOS.

**Comment by SergeyShablenko** [comment]
I`m registering device when user sign in to application, so token is refreshed once a day or once a week, I`m sure that tokens are valid. Also I tried reinstalling application as it should create new token, did not help. Will try to fetch receipts in few days

**Comment by SergeyShablenko** [comment]
Status ok, but message is not received by device

```json
{"data":[{"id":"5623878d-c39d-4dd1-8dad-52640edbb0dc","status":"ok"}]}
```

**Comment by SergeyShablenko** [comment]
Tried to send notification to multiple devices, one is iPhone 8 (os 12.2) another one is samsung s8 (android 9)

Both are successfully sent, iPhone received notification, android not

```json
{"data":[{"status":"ok","id":"f3342de4-33c9-4acf-bc1e-ae1c6958d222"},{"id":"a8c68a71-a7ed-4e1c-9250-6f32a93d6f65","status":"ok"}]}
```

**Comment by cruzach** [comment]
Okay! Glad that iOS is working. 

Have you already configured Android for [FCM](https://docs.expo.io/versions/v32.0.0/guides/using-fcm/)? We migrated from GCM a couple weeks ago in preparation for its deprecation

**Comment by SergeyShablenko** [comment]
@cruzach can I configure firebase for ios too (without ejecting)?

**Comment by cruzach** [comment]
Not yet. That may be something we implement in the future but right now we use APNS for iOS push notifications
