### ISSUE TITLE
Value for color cannot be cast from string to double

### ISSUE THREAD

**Issue by birendra-90** [expo/expo#4109]
When I am trying to run on Android mobile then I am getting below error

![Error-with-android](https://user-images.githubusercontent.com/15954316/57005162-111f4e00-6bf3-11e9-85e6-93dede779f1b.jpeg)

**Comment by ide** [comment]
Please provide a repro case and ideally the root cause. We can't tell what the core issue is from this report.

**Comment by birendra-90** [comment]
please have a look into this - https://snack.expo.io/@chanchal02/demo-app

**Comment by cruzach** [comment]
Hi @birendra-90, does this happen when you navigate to a certain screen? I was able to load up the app without seeing this error.

Best course of action is to follow the issue template we provide, as it asks for info we need such as:
- environment information
- SDK version
- exact steps to reproduce the behavior

Thank you!
Charlie

**Comment by jseils107** [comment]
Same issue when transitioning screens.  On SDK 34.

**Comment by ide** [comment]
IIRC there might be issues passing in color strings into setNativeProps. Try a hex literal (AARRGGBB or RRGGBBAA -- might need to look at the source code).

**Comment by jseils107** [comment]
For me it was setting a color property on a react native textinput instead of passing the color in the style property.  iOS didn’t give any warnings on it but android would fail with that error. 

I would check all your TextInput components and make sure you aren’t passing it a color prop.
