### ISSUE TITLE
Incorrect MapView types

### ISSUE THREAD

**Issue by jeanverster** [expo/expo#4118]
### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.1.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.0 => 32.0.0 
      @types/react: ^16.7.17 => 16.8.2 
      @types/react-native: ^0.57.18 => 0.57.34 
      @types/react-navigation: ^3.0.6 => 3.0.6 
      expo: ^32.0.4 => 32.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.7.1 => 3.8.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

Target: iOS, Android, Client & Standalone

### Steps to Reproduce

1. Using TS auto import feature, import both MapView and Marker from expo
2. Attempt to render MapView with Marker inside as per docs
3. Get error about invalid import

### Expected Behavior

1. Import { MapView, Marker } from 'expo'
2. Render MapView with nested Marker from above imports
3. No invalid import error

### Actual Behavior

1. Import { MapView, Marker } from 'expo' (default TS auto imports)
2. Render MapView with nested Marker from above imports
3. Invalid import error

### Reproducible Demo

https://snack.expo.io/@jeanverster/mapview-incorrect-types

**Comment by cruzach** [comment]
Hi @jeanverster,

I believe that the Marker module you're importing from 'expo' may be web-only (but I could be wrong there). 
As an aside- `const { Marker } = (MapView as any)` gets rid of that compiler complaint

-Charlie

**Comment by thekrol01** [comment]
You can just import { Mapview } from expo;
And use the marker like so:
<MapView.Marker

**Comment by methodbox** [comment]
> You can Import { Mapview } from expo;
> And nest the marker(s) like so:
> <MapView.Marker

This does not work. It will throw a type error, because the module isn't designed to be used this way. `Marker` is a separate, exported module.

Please read their docs - Expo's implementation should match their exact usage - it doesn't.

As a side note I have updated the `react-native-maps` types for their module @types/react-native-types. It was just merged today.

**Comment by methodbox** [comment]
This was driving me crazy, so this is the solution I've found. The type definitions in `react-native-maps` don't seem to be exported correctly, and something with Expo's implementation isn't exposing the rest of the exports other than `MapView` (basically the TL;DR of what I said above).

It also isn't picking up the new @types package for some reason.

So do this:

```bash
npm install --save-dev @types/react-native-maps

rm -rf [project path]/node_modules/expo/node_modules/react-native-maps/index.d.ts

cp [project-path]/node_modules/@types/react-native-maps/index.d.ts [project path]/node_modules/expo/node_modules/react-native-maps
```

Then update your imports, assuming the above example, like this:

```js
import MapView, { Circle, Marker } from 'expo/node_modules/react-native-maps/index';
```

This allows the proper ES6-style import of the`default exported module` and the additional modules, such that you can use this format to import the proper API components as listed here:  

https://github.com/react-native-community/react-native-maps

It will also now find the correct type definitions, of course.

As a side node the method of `MapView.ComponentName` is effectively deprecated and notated by `react-native-maps` that it should be unnecessary in their own `MapView.js`:

<a href="https://ibb.co/T0gkWsb"><img src="https://i.ibb.co/Wz26VLP/Screen-Shot-2019-05-19-at-6-04-14-PM.png" alt="Screen-Shot-2019-05-19-at-6-04-14-PM" border="0"></a><br /><a target='_blank' href='https://freeonlinedice.com/'>free coin toss</a><br />

**Comment by cruzach** [comment]
Thanks for your thorough-ness @methodbox! Sorry you're having to jump through these hoops to get the behavior you want 😕 

Wanted to let you know that an update to MapView is coming with [SDK 33](https://github.com/expo/expo/issues/4154), hopefully clearing this up!

**Comment by cruzach** [comment]
You now import from `react-native-maps`, I just tested this locally on a brand new `expo init` TS project, and had no typing issues, so I'll close this issue. 

If you have problems importing `Mapview` or other `react-native-maps` components, please open a new github issue with a full repro, thanks!
