### ISSUE TITLE
Scheduled notifications are not shown after reboot

### ISSUE THREAD

**Issue by RikTheunis** [expo/expo#4121]
### Environment

Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.15.4

### Steps to Reproduce

Local scheduled notifications are not shown after reboot of device on Android. On iOS it works.
To reproduce, view steps below.

### Expected Behavior

Scheduled notifications should be shown after a reboot.

### Actual Behavior

Local scheduled notifications are not shown after reboot of device on Android.

### Reproducible Demo

https://snack.expo.io/@riktheunis/schedulednotificationtester

1. Run the snack.
2. Press the blue button to schedule a notification in 2 minutes from the current time.
3. Reboot device.
4. No notification will be received on Android. On iOS the notification is received.

**Comment by RikTheunis** [comment]
I noticed others are having the same problems and they already opened a [feature request on Canny](https://expo.canny.io/feature-requests/p/keep-scheduled-notifications-after-reboot).

**Comment by etse** [comment]
I got the same problem in my app - using the same steps to reproduce.

**Comment by jannikbuschke** [comment]
I'm also running into this issue. Does anyone know about workarounds?

**Comment by krombipils** [comment]
Any news on this? The cordova-plugin-local-notifications plugin guys had the same issue a while ago and already fixed it, see [https://github.com/katzer/cordova-plugin-local-notifications/issues/1449](https://github.com/katzer/cordova-plugin-local-notifications/issues/1449)

**Comment by cruzach** [comment]
We're aware of this issue, and have [changed the docs to reflect this limitation](https://github.com/expo/expo/commit/2c94f9839cc9eddacb5af26dc3469e0a3be7f321). FYI, the notifications module is getting a significant revamp

I'm not sure about possible workarounds for this, though

**Comment by krombipils** [comment]
> the notifications module is getting a significant revamp

What is the estimated time for this to get released?

**Comment by cruzach** [comment]
No ETA, yet

**Comment by gammalost** [comment]
Am I right to assume that this PR solves the problem? https://github.com/expo/expo/pull/7035

**Comment by sjchmiela** [comment]
This PR solves the problem in the new `expo-notifications` package which is not yet included in the Expo client or standalone apps. To use `expo-notifications` you'd need to eject (at the moment). We're working on adding it to Expo client and standalone apps, you can track the progress at https://github.com/expo/expo/issues/8135.

**Comment by cruzach** [comment]
Hi everyone- I can confirm this is fixed in the managed workflow on SDK 38 now, with the new `expo-notifications` module 🎉 

You can test it with this snack- https://snack.expo.io/@charliecruzan/notifications4121 - just press the button, reset your device, and the notification should come through in 120 seconds. make sure you have the most recent Expo client downloaded!

**Comment by BeKnowDo** [comment]
> Hi everyone- I can confirm this is fixed in the managed workflow on SDK 38 now, with the new `expo-notifications` module 
> 
> You can test it with this snack- https://snack.expo.io/@charliecruzan/notifications4121 - just press the button, reset your device, and the notification should come through in 120 seconds. make sure you have the most recent Expo client downloaded!

I had such high hopes your example would work but for some reason, it doesn't show after rebooting the device. That's with the latest expo client installed :-/

**Comment by cruzach** [comment]
@BeKnowDo can you double-check for me that _not_ resetting your device results in the push notification being delivered? You also may have to test outside of snack, running the app locally with expo-cli, and add [this configuration](https://docs.expo.io/versions/latest/sdk/notifications/#android)
