### ISSUE TITLE
missing ‘onPlaybackStatusUpdate’ warning expo-av

### ISSUE THREAD

**Issue by thekrol01** [expo/expo#4122]
### Environment

Bare react native project

IOS

### Steps to Reproduce

 1. Installed the latest version of Universal Module expo-av in a bare react native project.
2. Ios Build with Xcode 10.2 on a local device (Iphone 5) .
3. Video with property shouldPlay loads correctly but has to be started manually (playbutton) and does not replay. 
4. I use the onPlaybackStatusUpdate property with referal to the function below to set the video to 0.

handlePlaybackStatusUpdate = async playbackStatus => {
if (playbackStatus.didJustFinish) {
await this.player.setPositionAsync(0);
}
}

I get the warning: Tried to set property ‘onPlaybackStatusUpdate’ on View manager of view ’ ExpoVideoView’ when the view manager does not support such prop.
5.Same code worked with managed expo Video API.

### Expected Behavior

Video should automatic play and replay. 

### Actual Behavior
no replay. Property warning appears.

### Reproducible Demo

Bare react native project

**Comment by sjchmiela** [comment]
Hey, @thekrol01!

I just tried to reproduce a bug you've described in a new bare React Native project and:
- in my project `shouldPlay` works ok,
- setting `onPlaybackStatusUpdate` would indeed raise a warning, #4130 should fix that.

**Comment by thekrol01** [comment]
Hi @sjchmiela,
Wow thats fast 👍 Thanks for looking into this issue.
