### ISSUE TITLE
[bare] @expo/vector-icons not working in bare

### ISSUE THREAD

**Issue by redpandatronicsuk** [expo/expo#4127]
## 🐛 Bug Report
Get this error when trying to use `@expo/vector-icons` in bare project.
```
bundling failed: Error: Unable to resolve module `expo-font` from `(...)/node_modules/@expo/vector-icons/build/createIconSet.js`: Module `expo-font` does not exist in the Haste module map
```

**Comment by cruzach** [comment]
Hi @redpandatronicsuk !

`@expo/vector-icons` actually is not a supported unimodule (see [here](https://docs.expo.io/versions/latest/bare/unimodules-full-list/) for the full list of supported APIs)

If you check out the [Readme](https://github.com/expo/vector-icons#expovector-icons) for `@expo/vector-icons`, it points you to use [@oblador/react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) if you're in a React Native project (but it should be more clear and explicitly say "bare" projects as well.

Thanks!
Charlie

**Comment by Gardens18** [comment]
then what is the solution for this issue ?
we used the @expo/vector-icons in the managed expo project initially and now we want to convert it to bare react native project , but we are having this issue, 

error:(Unable to resolve module `@expo/vector-icons` from `/Users/***/****/node_modules/galio-framework/src/Icon.js`: Module `@expo/vector-icons` does not exist in the Haste module map

**Comment by cruzach** [comment]
If you check out the Readme for @expo/vector-icons, it points you to use @oblador/react-native-vector-icons if you're in a bare React Native project
