### ISSUE TITLE
[Android] wanna hide status bar in splash screen

### ISSUE THREAD

**Issue by salmanLee** [expo/expo#4128]
## [Android] wanna hide status bar in splash screen

      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.5.1 
      expo-cli: 2.14.0
      Android: 8.0

here my app.json 

 "androidStatusBar": {
      "barStyle": "dark-content",
      "backgroundColor": "#ffffff"
    },

here my issue

the statusbar on the top of splashscreen picture. and i do not wanna statusbar in the splashscreen .ios is good.

**Comment by cruzach** [comment]
This is actually a [feature request](https://expo.canny.io/feature-requests/p/configure-status-bar-for-splash-screen) right now, so it is something we would like to implement in the future, but it isn't planned yet.

Definitely give it a vote over there on our Canny!

Thanks, 
Charlie
