### ISSUE TITLE
[iOS] expo init -> eject -> Thread 1: EXC_BAD_ACCESS from AVAudioSession

### ISSUE THREAD

**Issue by AidasK** [expo/expo#4132]
### Environment

```
  Expo CLI 2.16.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.3.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.16.1
```

Pods: 1.5.3
Device: iPhone 6(a1549), OS 11.4.1

### Steps to Reproduce

1. expo init exxp (install with npm)
2. cd exxp
3. npm start (stop once QR code is loaded)
4. expo eject (with expo kit)
5. cd ios && pod install
6. xcode open exxp/ios/exxp.xcworkspace
7. xcode select team -> connect iphone 7 to my macbook -> build and run on iphone 7 device (virtual machine works without an issue)

Result:
![image](https://user-images.githubusercontent.com/2088484/57228757-3c53d400-701d-11e9-8cea-3ced77dbf3a4.png)

the odd thing is that thread error comes from AVAudioSession, don't know why, because I have not changed anything in the code. I have only done steps above. It always fails.

### Expected Behavior

expo init  and expo eject should create a working project ready to be run on ios device.

**Comment by GedSni** [comment]
same problem here

**Comment by AidasK** [comment]
Tested on iPhone 6s, OS 12.2, works
iPhone 6(a1549), OS 11.4.1, doesn't

**Comment by cruzach** [comment]
@GedSni, is it also only happening with OS 11.4.1 devices for you as well?

**Comment by sjchmiela** [comment]
cc @tsapeta

**Comment by timboektoe** [comment]
I am experiencing the same on iPhone 6 (A1586), OS 12.2
