### ISSUE TITLE
iOS `exp detach` should update all occurrences of com.getexponent in the .xcodeproj

### ISSUE THREAD

**Issue by xavier-villelegier** [expo/expo#414]
Hi everyone,

# Config
```
exp: 42.2.0
sdk: 18.0.0
```

# Problem

I am trying to detach my app to use `fastlane` and automate the deployment process. But when I detach my application by running `exp detach`, the App Identifier identified by `fastlane` is `com.getexponent.productinuse`, with `productinuse` being the `slug` in the `app.json`.

I thought that maybe it was a fastlane issue and it was taking a wrong identifier, but when I open my project in Xcode, it's looking for a profile for the app id `com.getexponent.productinuse`.
![image](https://user-images.githubusercontent.com/17592779/28563608-c171d594-7126-11e7-9786-a867a6642e9d.png)

Why is Expo not using the `bundleIdentifier` of the `app.json` ? Is there any property I missed in the configuration file ?

In my `app.json`:

```json
"ios": {
  "bundleIdentifier": "com.productinuse.demo",
  "buildNumber": "14",
  "config": {
    "usesNonExemptEncryption": false
  },
  "isRemoteJSEnabled": true,
  "supportsTablet": true
},
"android": {
  "package": "com.productinuse.demo",
  "versionCode": 14
},
```

Thank's ✌️

**Comment by terribleben** [comment]
Thanks for the report! What does the bundle identifier in `Info.plist` say? What version of Xcode are you using?

**Comment by xavier-villelegier** [comment]
@terribleben The `CFBundleIdentifier` is good in `Info.plist`. It seems that the `com.getexponent.productinuse` comes from `PRODUCT_BUNDLE_IDENTIFIER` in the `project.pbxproj`.

**Comment by aidanw** [comment]
I did this as a step in my Fastfile. (thanks @xavier-villelegier for pointing me here from my [Stackoverflow question](https://stackoverflow.com/questions/45307364/building-an-iphone-app-exported-from-expo-using-fastlane-or-any-other-method/45436908)!)


> sh "sed -i '' 's/com.getexponent.allotmentlab/com.foam.allotmentlab/g' '../../ios/allotmentlab.xcodeproj/project.pbxproj'"

**Comment by terribleben** [comment]
Cool, that makes sense. When I get a chance, I can update the `detach` script to substitute your bundle id for `PRODUCT_BUNDLE_IDENTIFIER` in the xcodeproj. (and substitute all other occurrences of `com.getexponent` as well.) I think this used to work, so I wonder why that's a requirement now. :man_shrugging:

**Comment by xavier-villelegier** [comment]
I've edited [my answer on Stackoverflow](https://stackoverflow.com/a/45436908/8399418) for those who want a workaround waiting for this to be fixed. You were on the good way @aidanw !

Thank's for your time @terribleben.

**Comment by terribleben** [comment]
This is fixed on master, will go in the pipeline for release: https://github.com/expo/xdl/commit/192acebc37f71376be4397da6d7d10dce19d062b
