### ISSUE TITLE
react-native-unimodules breaks workspace linking

### ISSUE THREAD

**Issue by ide** [expo/expo#4145]
The root package.json depends on react-native-unimodules, which depends on individual unimodules. This breaks workspace linking when we bump the major version of a unimodule:

Say react-native-unimodules depends on `"@unimodules/core": "~1.0.0"`. In this repo, standalone-ncl depends on `"@unimodules/core": "*"`. We also have `@unimodules/core` 2.0.0-alpha.0 in this repo.

When running Yarn (even after deleting yarn.lock), Yarn will link `"@unimodules/core": "*"` to `~1.0.0` from npm instead of linking to the local copy of `2.0.0-alpha.0`. I'm not sure why, but that is Yarn's current behavior. We can fix this by changing the `*` to `^2.0.0-alpha.0`, but we still have the issue of our repo installing two copies of the unimodules that are in react-native-unimodules's dependencies.

*Potential fix:* there is a dependency cycle between the expo repo and the react-native-unimodules repo. Reading the original commit (https://github.com/unimodules/react-native-unimodules/pull/2), it looks like we only want the Gradle and CocoaPods auto-installation scripts and don't actually care about any of the dependencies in the react-native-unimodules package. So, perhaps one thing we could do is move the auto-installation scripts into this repo (ex: `packages/unimodule-autolink`), and have react-native-unimodules depend on that package, breaking the dependency cycle.

**Comment by tsapeta** [comment]
Yeah, that's tricky. What if we add `react-native-unimodules` as a submodule? Also, shouldn't `standalone-ncl` depend on `react-native-unimodules` instead of core and adapter packages directly?

**Comment by ide** [comment]
I think the submodule would solve some of the problems since we could add the submodule to the list of workspace packages.

> Also, shouldn't standalone-ncl depend on react-native-unimodules instead of core and adapter packages directly?

Probably, yes. AFAIK standalone-ncl was created before react-native-unimodules, which is why it doesn't.

**Comment by ide** [comment]
Closing this for now since we are trying out a submodule.
