### ISSUE TITLE
Having trouble building with uploaded certificates.

### ISSUE THREAD

**Issue by timbrandin** [expo/expo#415]
It just ends with: 
```
[exp] iOS: There was an error with this build. Please try again.
```

But it works when I let Expo manage my certificates!

**Comment by timbrandin** [comment]
I wish there was a way of getting a log of what went wrong here.

**Comment by xavier-villelegier** [comment]
@timbrandin Which file are you giving to `exp` as a certificate ? I think it has to be a `.p12` file, which is the private key.
A good thing is to run `exp fetch:ios:certs` to download the `.p12` files (distribution + push), and these files can be used later with `exp`. For the push certificate, I generally let `exp` handle this for the first time, and then I use `exp fetch:ios:certs` to reuse these certificates for future deployment.

**Comment by timbrandin** [comment]
Thx @xavier-villelegier, I've downloaded them now, I tried creating the certs myself from apple developers by downloading and using the app keychain access, that did not work.

**Comment by xavier-villelegier** [comment]
@timbrandin That's why I let `exp` handle the process for the first time. `exp` generates the certificates for you (you don't create them on from apple developers), and you just have to run `exp fetch:ios:certs` to get the certificates it has created for you + the passwords. Then you keep using these `.p12` file for the next builds !

**Comment by dikaiosune** [comment]
@timbrandin can you paste the build ID that `exp` prints when starting the job? We can take a look at the logs for you.

**Comment by timbrandin** [comment]
@dikaiosune I haven't saved the logs, or are they always the same when starting the job?

**Comment by dikaiosune** [comment]
The build ID is unique for each job -- if you try it again, can you paste the build ID here?

**Comment by timbrandin** [comment]
Well it works now for us when we let exp manage the certs, and I don't want to break it down now as we're really close to publishing the app now and need to be able to ship changes in case.

**Comment by timbrandin** [comment]
I remember now the reason why I had to upload them, for starters, and it was because the build was failing, and it wasn't until exp created new certs for me that it worked to build.

**Comment by dikaiosune** [comment]
OK, makes sense. If you hit this again please post to the forums with your build ID and I'll take another look. Thanks!

**Comment by timbrandin** [comment]
Thx @dikaiosune, will do that.
