### ISSUE TITLE
Custom app.json with Jest

### ISSUE THREAD

**Issue by bduff9** [expo/expo#4156]
I am unable to find this in the documentation, or in previous issues.  Basically, I have custom app.json files per env (app.dev.json, app.prod.json, etc.).  Starting and publishing works fine with the --config flag, however our Jest tests are failing since it cannot find the needed info from the app.json file.  I looked at the jest-expo files and they are loading the app.json from disk, so I cannot use a module mapper like I typically would in Jest config.

A workaround for us is to have a useless dupe of our app.json files, but this is undesirable as it is not used in live envs and so it would be easy to miss adding a value we need at runtime.

If there is a way to accomplish this now, awesome.  If not, ideally, we would like this to work similarly to Angular where we can pass in the current env/file to use so we can reliably test that each env is working as expected.  This is a private repo so I am unable to link to it, however if needed, I am happy to provide additional details.  Thank you!

**Comment by EvanBacon** [comment]
To accommodate multiple configs we've started rolling out an `app.config.js`. Adding support for this would fix your issue. I opened a PR to add this feature.

**Comment by EvanBacon** [comment]
We've dropped support for custom app.json paths. app.config.js is the only solution now.
