### ISSUE TITLE
Is there any way how to update library react-native-maps?

### ISSUE THREAD

**Issue by ondrej-janosik** [expo/expo#4157]
Hi, 

Is there any way how to update library react-native-maps? There is a bug in version 0.22.1 (included in EXPO 32) that is a real blocker for my app. It was fixed in version 0.24.0 (https://github.com/react-native-community/react-native-maps/releases/tag/v0.24.0). So far I tried to use MapView directly from react-native-maps and rewriting of react-native-maps in node_modules. None of that works. I will be happy with any solution (even temporary hacks).

Thanks, Ondrej

**Comment by cruzach** [comment]
Hi @ondrej-janosik !

If you're using the managed workflow (see Expo's docs on [Managed & Bare Workflows](https://docs.expo.io/versions/v32.0.0/introduction/managed-vs-bare/)), then this isn't possible and you would need to wait for the next SDK update.

**However** if you're using what we refer to as the bare workflow, then you're able to use whichever version of `react-native-maps` you need. There are pros and cons to each workflow, but this is a major benefit of the bare workflow/unimodules in general.

Feel free to post on our [forums](https://forums.expo.io/) if you have any other questions!
-Charlie

**Comment by ondrej-janosik** [comment]
Hi Charlie,

Thanks for such a quick response! However we are using managed workflow. Can you just tell me what version of react-native-maps will be included in SDK33? So I just know if we should wait or if we need to figure out something else.

Thanks, Ondre
