### ISSUE TITLE
Google ios standalone login error

### ISSUE THREAD

**Issue by stochris** [expo/expo#416]
When trying to login with google in a standalone app, I sometimes (no apparent pattern ) get the following error
```
Exception '***-[__NSArrayM insertObject:atIndex:]:object cannot be nil' was thrown while invoking logInAsync on target ExponentGoogle with params (
   {
     behaviour: web;
     scopes = ( profile, email );
   },
   446,
   447
)
```

I'm using version 18.0.6 of the SDK

**Comment by s7dhansh** [comment]
You need androidClientId
See: https://docs.expo.io/versions/v19.0.0/sdk/google.html

**Comment by janicduplessis** [comment]
We have a bunch of fix coming up to Google Sign In in sdk 21 this should be fixed. Just make sure you follow the documentation. For standalone apps you will have to use iosStandaloneAppClientId.

**Comment by mgscreativa** [comment]
Hi! I have the same issue using Expo v20 with CRNA I got this:

```
Exception '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil' was thrown while invoking logInAsync on target ExponentGoogle with params (
{
behavior = web;
scopes = (
profile,
email
);
},
444,
445
)

ABI20_0_0RCTFatal
ABI20_0_0RCTSetFatalHandler
ABI20_0_0RCTSetFatalHandler
<redacted>
<redacted>
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
Exponent
<redacted>
```

This is the code to trigger Google sign in:
import { Google } from 'expo';
...
...
  handleLoginWithGoogle = async () => {
    try {
      const result = await Google.logInAsync({
        androidClientId: config.OAuth.facebook.androidClientId, // Filled in separate config file
        iosClientId: config.OAuth.facebook.iosClientId, // Filled in separate config file
        scopes: ['profile', 'email'],
      });

      // if (result.type === 'success') {
      //   console.log(result);
      // }

      console.log(result);
    } catch (e) {
      this.props.alertWithType('error', 'Error', e);
    }
  };
...
...

**Comment by stochris** [comment]
For me, setting `behavior` to web removed all the problems ( in SDK 19 and 20 )

**Comment by mgscreativa** [comment]
Well. in my case I needed to be more careful!

`config.OAuth.facebook.androidClientId` that config branch didn't contain any google clientIDs! jeje

**Comment by sebasgarcep** [comment]
If the behaviour is `web` shouldn't the API only ask for the `webClientId`? In my humble opinion this looks like a bug.

**Comment by Anees-Raja** [comment]
I'm having this same error and i'm not even on a standalone app just following the documentation provided for Google sign in and I still got this error. Nothing in this thread works to fix it either.

**Comment by znack2** [comment]
hi everyone, faced this issue today, just placed api_key right to code, not import them, removed problem.
