### ISSUE TITLE
[expo-image-picker][Android] Image decoding failed

### ISSUE THREAD

**Issue by lakhman** [expo/expo#4161]
### Environment

```
  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.17.1
```

This is a bare react native app with unimodules integrated I created with the expo-cli, I then installed expo-image-picker only.

### Steps to Reproduce

View my reproducible demo and steps below, I can replicate this with a new bare project (with unimodules) as of today on a physical device (Samsung S5 (SM-G901F) v6.0.1).

### Expected Behavior

It should return the newly photographed image in base64 (if option is provided) or the file URL.

### Actual Behavior

Nothing happens, I caught the thrown error and it's simply returned as "Image decoding failed".

I found the following adb log item:

```
W ActivityManager: No content provider found for permission revoke: file:///data/user/0/com.awesomeproject/cache/ImagePicker/9cd2ca73-9f4d-43d8-a81b-6ce61e70280c.jpg
```

### Reproducible Demo

I have created a github repository here which reproduces this:

> https://github.com/lakhman/expo-image-picker-image-decoding-failed-error/blob/master/App.js

You can also follow the following steps to setup a fresh new project:

```
# Create a new "bare-minimum" project with unimodules integrated
expo init decode-failed-bug

# Change working directory
cd decode-failed-bug/

# Install expo image picker
yarn add expo-image-picker

# Update AndroidManifest.xml as per instructions here:
# https://github.com/expo/expo/tree/master/packages/expo-image-picker#configure-for-android

# Paste the code from here into App.js (expo permissions and basic UI for camera)
https://github.com/lakhman/expo-image-picker-image-decoding-failed-error/blob/master/App.js

# Run android (on a physical device)
yarn android
```

- When you take a photograph and are presented with the confirmation screen "Retry" or "Select" - When you press select you get this "Image decoding error"

- When you upload an image via the photo gallery, everything works as expected.

### Other Information
Related issues: https://github.com/expo/expo/issues/3132

I also tried applying this patch manually but it didn't work. https://github.com/expo/expo/commit/c1091799d72ce65f153cd190c6ea162bf89e45ed#diff-716483280f828da5fdc3fc878aefd078

I also tried upgrading expo-image-picker to 5.0.0-rc.0, gradle clean and rebuild, but that didn't work.

I also tried upgrading unimodules to latest alpha build (as of today) - but that caused the app to crash with some other unrelated error.

There's also another issue here (maybe related?): https://github.com/lakhman/expo-image-picker-image-decoding-failed-error/blob/master/App.js#L70
If I set `allowsEditing: true`, When I photograph the image and select it, I am returned `{cancelled: true}` - when it should return the selected image. In this scenario the "Image decoding failed" does not occur.

Please let me know if you need any more info.

**Comment by BrodaNoel** [comment]
I just received a Sentry error with the same message. No trace reported in Sentry (weird)

**Comment by bbarthec** [comment]
@lakhman, @BrodaNoel this problem is already solved by this [PR](https://github.com/expo/expo/pull/4717).
Just update `expo-image-pickaer` to newest version (at the time of writing this message it's `5.0.2`) 😁

**Comment by bbarthec** [comment]
@lakhman, thank you greatly for this amazingly described issue supported by this repo (with so many useful comments and very nicely written code) 💯 🎉 😁
