### ISSUE TITLE
Facebook Ads shows blurry images on android device and when its happens the link does not work.

### ISSUE THREAD

**Issue by techday84** [expo/expo#4169]
### Environment

  Expo CLI 2.17.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

react-native-cli: 2.0.1
react-native: 0.59.4
https://github.com/unimodules/react-native-unimodules
https://github.com/expo/expo/tree/master/packages/expo-ads-facebook

### Steps to Reproduce
I configure react-native-unimodules with expo-ads-facebook on a react native app.

On android device:

I can see the ad with the text but the image is blurred, when its happens the link doesn't work.
If the ad is a carrousel of images, the link works and the image is ok.

**Comment by cruzach** [comment]
Hi @techday84,

Could you provide a reproducible example of this? Either step-by-step, or share a repo

Thanks!
Charlie

**Comment by techday84** [comment]
Hi, when the ad is a video it works perfect. Tomorrow i will provide you a repo to show the problem. Thanks.

**Comment by gamingumar** [comment]
In Android when I scroll, the media view disappears. Works fine in iOS.

**Comment by Szymon20000** [comment]
I'm unable to reproduce. Could you provide a reproducible example and your Android version?

**Comment by techday84** [comment]
- Android version:

react-native-cli: 2.0.1
react-native: 0.59.4

https://github.com/techday84/expo-ads-facebook-issue/tree/master

**Comment by techday84** [comment]
- Android version:

react-native-cli: 2.0.1
react-native: 0.59.4

https://github.com/techday84/expo-ads-facebook-issue/tree/master

I can see the ad with the text but the image is blurred, when its happens the link doesn't work.
If the ad is a carrousel of images the link works and the image is ok.
If the ad is a video all is ok.

**Comment by techday84** [comment]
Hi, something new about this problem?

**Comment by esamelson** [comment]
Hi, we're closing old/inactive issues that apply to older SDK versions. I tried to clone your repo and was not able to reproduce the problem. In general, when providing repro cases, please include a list of steps to follow and ensure the problem can be fully reproduced -- the more information, the better.. If this problem persists on a new version of this package, please open a new issue with more information. Thanks!
