### ISSUE TITLE
~/.expo/PATH is not set on macOS in some situations

### ISSUE THREAD

**Issue by smiless** [expo/expo#417]
Hello everyone,

I'm working on a existing project made with Expo and detached because as iOS developer I need to made some bridges.
When I try to run the project with XCode I got the following errors : 
Any clues ?

> PhaseScriptExecution PrepareExpo /Users/bryandhaeseleer/Library/Developer/Xcode/DerivedData/my-adiction-bxtnpiqzkbqvpldwjiyuyrtaulvu/Build/Intermediates/my-adiction.build/Debug-iphonesimulator/my-adiction.build/Script-B5722AD01DFB7E3F0084848F.sh
> 
> ~/Desktop/hybrid-app ~/Desktop/hybrid-app/ios
> cat: /Users/bryandhaeseleer/.expo/PATH: No such file or directory

complete stack here : [PhaseScriptExecution.txt]
(https://github.com/expo/expo/files/1173287/PhaseScriptExecution.txt)

**Package.json**

```
{
  "name": "myadiction",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "~1.0.1",
    "native-base": "^2.2.0",
    "react-native-scripts": "0.0.31",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@shoutem/ui": "^0.19.3",
    "expo": "^17.0.0",
    "firebase": "^4.1.2",
    "react": "^16.0.0-alpha.6",
    "react-native": "https://github.com/exponent/react-native#sdk-17.0.0",
    "react-native-elements": "^0.13.0",
    "react-native-fbsdk": "^0.6.1",
    "react-native-vector-icons": "^4.2.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "react-redux-firebase": "^1.4.1",
    "redux": "^3.7.0",
    "redux-thunk": "^2.2.0"
  }
}
```

**Comment by YKSing** [comment]
same issue here

**Comment by terribleben** [comment]
@jesseruder any idea why `.expo/PATH` would not exist?

**Comment by remeryAGS** [comment]
I am also having this issue.

**Comment by jesseruder** [comment]
try running any `exp` command in your terminal

**Comment by remeryAGS** [comment]
I was able to run `exp start` without any issues.

**Comment by jesseruder** [comment]
Ok not sure what's going on. For now `echo $PATH > ~/.expo/PATH` should fix the issue. I'll investigate more.

**Comment by jesseruder** [comment]
What's the output of `exp path`?

**Comment by remeryAGS** [comment]
```
$ exp path
[exp] Set XDE path to /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by remeryAGS** [comment]
Running `exp path` seems to have made Xcode happy

**Comment by dikaiosune** [comment]
Seems like running the `exp path` command is resolving the issue. If you're still hitting this after running the command, please let us know and we'll reopen. Thanks!

**Comment by bho01** [comment]
@anp i got a mach-o linker error after running exp path

**Comment by epicfaace** [comment]
How do we fix this when using just the `expo` cli utility (and not `exp`)?

**Comment by zanechua** [comment]
The expo command `expo path` says that no such command is available but the PATH file actually does get created.
