### ISSUE TITLE
[expo-image-manipulator] ImageManipulator.manipulateAsync is not available on ios

### ISSUE THREAD

**Issue by donysukardi** [expo/expo#4180]
## 🐛 Bug Report

Expo libraries don't seem to get linked in Release build for iOS.

### Environment

Target: iOS Bare
expo-image-manipulator@4.0.0

### Steps to Reproduce

- Follow instructions to install `react-native-unimodules` and then install `expo-image-manipulator`.
- Call `ImageManipulator.manipulateAsync` in code with a given uri

### Expected Behavior

`ImageManipulator.manipulateAsync` should work on iOS

### Actual Behavior

Getting the following error

`The method or property ImageManipulator.manipulateAsync is not available on ios, are you sure you've linked all the native dependencies properly?`

![image](https://user-images.githubusercontent.com/410792/57503911-e33db600-7324-11e9-9222-aadf8e811f57.png)

**Comment by sjchmiela** [comment]
Hey, could you please share your `Podfile.lock` to let us ensure that the manipulator is getting installed properly?

**Comment by donysukardi** [comment]
@sjchmiela it happens for `expo-file-system` apparently too. here are my current config https://gist.github.com/donysukardi/14776f9b0ef906563e45853ab14f7668

**Comment by sjchmiela** [comment]
How about if you tried moving line 41 (`self.moduleRegistryAdapter = …`) to the beginning of `application:didFinishLaunchingWithOptions:`? (Most specifically, before initializing the bridge in line 28.)

**Comment by donysukardi** [comment]
That seems to do the trick. Thank you so much @sjchmiela! I spent 2 days trying to figure out what was wrong 😱
