### ISSUE TITLE
Push notification listener is not invoked at all Android

### ISSUE THREAD

**Issue by vinaynb** [expo/expo#4183]
### Environment

```bash
Expo CLI 2.17.1 environment info:
    System:
      OS: Linux 3.13 Ubuntu 14.04.5 LTS, Trusty Tahr
      Shell: 5.0.2 - /usr/bin/zsh
    Binaries:
      Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
      npm: 5.3.0 - ~/.nvm/versions/node/v8.3.0/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.3.0 
    npmGlobalPackages:
      expo-cli: 2.17.1

```

standalone android

### Steps to Reproduce

- get native device token using `Notifications.getDevicePushTokenAsync`
- build standalone apk using expo build:android
- install and run on physical device
- send push notification using aws sns and firebase
- notification is recieved successfully on device and shows up in system tray
- click on notification and app opens but the notifications listener never gets called

### Expected Behavior

I have copied notifications code from Expo's documentation and implemented in-app. The listener should fire when user opens app by tapping notification.

### Actual Behavior
Notification listener is not fired at all even once.

### Reproducible Demo

i can provide a repro via snack but that wouldn't be of help in my case as you need to have standalone apk to get device native token as I am not using expo's notifications service.

my listener code is written on root component's `componentDidMount` and i can confirm that it is being called.

```js
componentDidMount(){
this._notificationSubscription = Notifications.addListener(this._handleNotification);
}
_handleNotification = (notification) => {
        alert('notification');
        //this.setState({ notification: notification });
    };
```

This issue is very  similar to #1997 except that i use aws sns and i am facing this issue on android

**Comment by cruzach** [comment]
Hi @vinaynb ,

Since you're not using FCM for your Android Push Notifications, I'm not sure this is an Expo-related issue. The payload format could be different with AWS SNS.

Please take a look at [this forum post](https://forums.expo.io/t/expo-push-notifications-at-amazon-sns/10543/3?u=charliecruzan) for a possible solution.

Closing as I don't believe this is Expo-related, will re-open if necessary.
-Charlie

**Comment by vinayscaletech** [comment]
@cruzach i am using FCM for push android notifications just the difference is that it does via AWS SNS and not via Expo Servers. Can you guide me to the required format which i need to take care of when sending notifications.

> Closing as I don't believe this is Expo-related, will re-open if necessary.

As i am recieving notifications successfully and the app opens up as well but listener doesn't get called leads me to something wrong happening in expo.

**Comment by vinaynb** [comment]
@cruzach i am using FCM for push android notifications just the difference is that it does via AWS SNS and not via Expo Servers. Can you guide me to the required format which i need to take care of when sending notifications.

Closing as I don't believe this is Expo-related, will re-open if necessary.

As i am recieving notifications successfully and the app opens up as well but listener doesn't get called leads me to something wrong happening in expo.

**Comment by vinaynb** [comment]
UPDATE - today i checked the same on iOS and it works so issue is specifically hitting android right now.

**Comment by cruzach** [comment]
See [these Github issue comments](https://github.com/expo/expo/issues/2458#issuecomment-431517941), as that seems to be the issue. Not 100% sure if that exact fix will work, but taking a look at our source code for Notifications will let you see the exact payload to model.

**Comment by vinaynb** [comment]
UPDATE
I managed to solve it. Thanks @cruzach for the pointers. For other's who might come to this issue with the same problem using below json in AWS SNS with FCM fixed the issue.

```json
{
"GCM": "{ \"data\": { \"message\": \"Sample message for Android endpoints\", \"title\": \"Hello world...\", \"body\": \"msg body\", \"experienceId\": \"@expousername/app-slug\" } }"
}
```

`experienceId` and `data` properties were  the missing piece. Your app slug can obtained from `app.json` file in your root directory of expo project.

old json which didn't work (for reference)

```json
{
  "GCM": "{ \"notification\": { \"message\": \"Sample message for Android endpoints\", \"title\": \"Hello You...\" } }"
}
```
Another issue that i solved with new json was that of double notifications being shown in android. The reason behind that was because of the `notification` key expo was triggering another local notification of its own along with the push notification. Replacing it with `data` key fixed that.

**Comment by cruzach** [comment]
Awesome! And thanks for sharing the fix for others who might run into the same problem 😄
