### ISSUE TITLE
Trying to solve white flash on navigation issue

### ISSUE THREAD

**Issue by rrajasek92** [expo/expo#419]
I have an app that has an image as a background and am seeing a white flash (Android)/ white page(iOS) when navigating between stack components. Several sources say that this issue can be fixed by delving into MainActivity.java (for Android) or AppDelegate.m (for iOS) and altering some properties in there, but because I'm using expo I am unable to access these files. Is there a way to get to these files? If not, is there any other way to stop said flashes from happening? It's a local file so it shouldn't be that it's taking too long to load, and regardless I am preloading the image in an async function, so it seems like the rendering of the image itself is slow.
Any ideas? Thanks!

**Comment by terribleben** [comment]
Hi! Sorry for the delayed response. We're hoping to limit this board to tracking bugs in Expo, but it sounds like you have a question about your navigation implementation. Would it be ok to open a [forum topic](http://forums.expo.io) instead?
