### ISSUE TITLE
[Camera] getAvailablePictureSizes -- unexpected error

### ISSUE THREAD

**Issue by EskelCz** [expo/expo#4190]
### Environment

On latest Snack, Expo v32.0.0

### Steps to Reproduce

Run this snack on **Xiaomi Redmi 6**: https://snack.expo.io/@eskel/camera-crop

### Expected Behavior

Show supported camera resolutions

### Actual Behavior

```
Error: "getAvailablePictureSizes -- unexpected error -- Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference" in h@/data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40snack%2FHk74mSm2N-1224914376-32.0.0:38:1566 << /data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40snack%2FHk74mSm2N-1224914376-32.0.0:38:960 << value@/data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40snack%2FHk74mSm2N-1224914376-32.0.0:46:3650 << /data/user/0/host.exp.exponent/files/32.0.0/cached-bundle-experience-%40snack%2FHk74mSm2N-1224914376-32.0.0:46:1155 ...
```

### Reproducible Demo

https://snack.expo.io/@eskel/camera-crop

Also I'm not the first to report this, but it got no response: https://forums.expo.io/t/might-be-a-bug-camera-getavailablepicturesizesasync-throw-error-with-proper-args/20175

**Comment by EskelCz** [comment]
as a sidenote, on Appetize.io preview the onCameraReady is never fired (naturally, the camera is disabled), so it can't be tested there.

**Comment by jamesloper** [comment]
`getAvailablePictureSizesAsync` requires you to pass a ratio argument like '16:9'

**Comment by bbarthec** [comment]
@EskelCz, please see this [snack](https://snack.expo.io/@bbarthec/github---camera---getavailablepicturesizes).

**Comment by EskelCz** [comment]
Ah,  I missed that, sorry and thanks for pointing it out.
On the other hand it makes no sense to give a ratio when I want to get all available ratios. I see no reason for the parameter. That's also why I missed  it.
