### ISSUE TITLE
[Android] [Expo-AV] [Video] [Bare Workflow] Video crashes on full screen Android

### ISSUE THREAD

**Issue by zibs** [expo/expo#4191]
### Environment

```

  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.6 => 0.58.6
    npmGlobalPackages:
      expo-cli: 2.17.1

```

Android - Bare WorkFlow
### Steps to Reproduce

1. Create a bare workflow app using expo-cli ->
2. Add expo-av with `yarn add expo-av` ->
3. Copy/paste example video component from docs ->
4. Try to make it full screen on Android (Pixel) using the `useNativeControls` prop ->
5. App crashes with: `05-10 16:41:16.072 17091 17091 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.unimodules.core.interfaces.services.KeepAwakeManager.isActivated()' on a null object reference
05-10 16:41:16.072 17091 17091 E AndroidRuntime: 	at expo.modules.av.video.FullscreenVideoPlayer$KeepScreenOnUpdater.run(FullscreenVideoPlayer.java:45)`

There is a repro-demo below

If I comment out like 45 from `FullscreenVideoPlayer.java:45`, full screen works properly.

### Expected Behavior

Full screen works

### Actual Behavior

App is crashing from native-land with a null object reference.

### Reproducible Demo

Repro: https://github.com/zibs/mvce-expo-av-android

Thanks! Let me know if you need any other infos!

**Comment by sjchmiela** [comment]
Thanks, this line definitely doesn't make any sense. Removing!

**Comment by avinashlng1080** [comment]
@sjchmiela  can you please tell us which line you removed ?

**Comment by sjchmiela** [comment]
I was talking about this change https://github.com/expo/expo/commit/a49e9cbc58de2441b5705c7578e9bad754df9fd0

**Comment by sjchmiela** [comment]
It must be another kind of issue, try searching for that kind of problem in Issues list and if there's no such issue submitted, please submit your own. 🙂

**Comment by avinashlng1080** [comment]
Sure thanks :) @sjchmiela
