### ISSUE TITLE
expo-camera flip front to back camera don't work when use `useCamera2Api`

### ISSUE THREAD

**Issue by retyui** [expo/expo#4192]
### Environment
expo-camera: 4.0.0
react-native: 0.59.8
react-native-unimodules: 0.3.1

### Steps to Reproduce
Use own code from [Camera basic-example](https://docs.expo.io/versions/latest/sdk/camera/#basic-example)

### Expected Behavior
When you clicking on the text `flip`  (from the example above) at first time the camera is changing but if you press again nothing happens

if you remove `useCamera2Api: true`, then everything works as needed

### Actual Behavior
flip behavior work without the dependency of `useCamera2Api`

### Reproducible Demo
https://snack.expo.io/@retyui/f0fc5c

**Comment by retyui** [comment]
thank expo team, 2019...2022 issue still open

**Comment by brentvatne** [comment]
hey @retyui! this is how it works in large projects sometimes - we can't fix everything and we prioritize the issues we consider the most important. now that EAS Build makes it possible to include any native module in your managed app, you can use an alternative camera library if you find one that solves your issue.

**Comment by aramhovsepyan** [comment]
+1

**Comment by NK-Hertz** [comment]
i have the same issue

**Comment by siddharth-kt** [comment]
which other lib did you guys used ?

**Comment by retyui** [comment]
oh no, a bot be patient

**Comment by RRaideRR** [comment]
Facing the same problem :-/ . Fallback is to not use `useCamera2Api` but that is not always possible or desired

**Comment by retyui** [comment]
any progress?

**Comment by aramhovsepyan** [comment]
I wouldn't expect either expo nor Google to fix camera2Api bugs as it's being pushed towards deprecation. We found a workaround for this one, i.e., adding a timeout does the trick when switching camera's. Here is some sample code:

`switchCamera = async () => {
        await this.setState({showCamera: false});
        setTimeout(async () => {
            if (this.state.cameraType === CameraType.back) {
                await this.setState({cameraType: CameraType.front});
            } else {
                await this.setState({cameraType: CameraType.back});
            }
        }, 100);
        setTimeout(async () => {
            await this.setState({showCamera: true});
        }, 200);
    }`

**Comment by theartificialguy** [comment]
Same issue here, when the camera is flipped for the first time, it works correctly, but now any more tries won't do a thing, so I removed the `useCamera2Api` prop and it started working fine. What are the -ve points of not using `useCamera2Api`?

**Comment by jacobSND** [comment]
Leaving this here in case someone else might find it useful...

```jsx
  <Camera
    key={`camera-${type}`} // https://github.com/expo/expo/issues/4192
    type={type}
    useCamera2Api
  />
```

Since the key is also changed, the `Camera` component is forced to re-render. Still not a great solution but a little nicer than a timeout.
