### ISSUE TITLE
[Video][IOS][Bare Workflow] PlayAsync only works on second time it was invoked

### ISSUE THREAD

**Issue by naorzr** [expo/expo#4195]
### Environment

  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      expo-cli: 2.14.0

IOS

### Steps to Reproduce

1. start a bare expo project, install expo-av
2. apply this patch https://github.com/expo/expo/pull/3875/commits/232c24576733ed7b6d1a6731c40ef621548195a3
3. click the gray Play/Pause button to start the video(only work after the second time)

note: the patch on step 2 is necessary, otherwise it would just invoke an error and crash whenever trying to reload and so on.

### Expected Behavior

PlayAsync should work after the first time it was invoked

### Actual Behavior

PlayAsync is invoked only after the second time it was called

### Reproducible Demo
You can clone this minimal repo, just follow the short README
https://github.com/naorzr/expoVidRepro/tree/master

**Comment by sjchmiela** [comment]
I think this should have been fixed by https://github.com/expo/expo/pull/4125. 🤔 

Try using `react-native-unimodules@0.4.0-alpha.3`, which depends on `@unimodules/react-native-adapter@2.0.0-rc.1` which contains that fix. 🙂

**Comment by naorzr** [comment]
after upgrading to 0.4.0-alpha i'm getting 'No visible @interface for 'UMModuleRegistryAdapter' declares the selector 'extraModulesForBridge:andExperience:'' error when trying to build for ios

**Comment by sjchmiela** [comment]
Ah, sorry, forgot to add you need to remove the `andExperienceId:…` part from this line. 🙂

**Comment by naorzr** [comment]
after applying the change you mention the build went fine, got another error message while running it, 'could not import omit from lodash.omit'
so i've changed your source code in video.js to import {omit} from 'lodash', and it ran.
though now I can't seem to get the video playing, when ever I try to invoke playFromPositionAsync I'm getting a new error message 'expo audio is disabled, so the audio session could not be activated'

**Comment by sjchmiela** [comment]
Whenever you're trying to use Expo's AV APIs, first you need to ensure it has been enabled with [`Audio.setIsEnabledAsync`](https://docs.expo.io/versions/v32.0.0/sdk/audio/#audiosetisenabledasyncvalue). 🤔

**Comment by naorzr** [comment]
Holy cow! it worked.. 
Per the docs, 'Audio is enabled by default' , so why did I had to explicitly enable it then?

**Comment by ronlaureles** [comment]
> after upgrading to 0.4.0-alpha i'm getting 'No visible @interface for 'UMModuleRegistryAdapter' declares the selector 'extraModulesForBridge:andExperience:'' error when trying to build for ios

hi, how did you fix this issue on `0.4.0-alpha.3` ?

**Comment by lenarmazitov** [comment]
> Ah, sorry, forgot to add you need to remove the `andExperienceId:…` part from this line. 🙂

could you update this gist with your changes?
https://gist.github.com/brentvatne/94960dacb343310b76be9cc157d90049/revisions

**Comment by vdlindenmark** [comment]
@sjchmiela could you do what @lenarmazitov said above? I've struggled with the same bug (`No visible @interface for 'UMModuleRegistryAdapter' declares the selector 'extraModulesForBridge:andExperience:`) and checked multiple times the installation guide and gist xD

**Comment by kbrandwijk** [comment]
👍 For updating that gist, I just ran into the same issue.

**Comment by mcmar** [comment]
@sjchmiela @brentvatne [The gist that shows how to integrate `react-native-unimodules`](https://gist.github.com/brentvatne/94960dacb343310b76be9cc157d90049/revisions) is currently broken
That gist is still [linked from the `react-native-unimodules` README](https://github.com/unimodules/react-native-unimodules#configure-ios). So anyone who follows the instructions with a fresh install is getting broken builds. Please consider updating the gist or updating the README

**Comment by mcmar** [comment]
Also, please consider adding upgrade instructions to the [CHANGELOG](https://github.com/unimodules/react-native-unimodules/blob/master/CHANGELOG.md)

**Comment by IjzerenHein** [comment]
it seems the original problem mentioned in this issue is fixed. @naorzr can we close this? cheers

**Comment by IjzerenHein** [comment]
Closing this as this appears fixed. Feel free to reopen with additional reproduction details in case the problem still exists.
