### ISSUE TITLE
add possibility to set custom data in RewardedVideoAd

### ISSUE THREAD

**Issue by bazhukov** [expo/expo#4196]
it is impossible now to check a rewarded event on a server side... Is it possible to pass a custom data into native calls?

**Comment by cruzach** [comment]
Hey @bazhukov,

I'm not entirely sure what you're asking for, and for bug reports we really need you to follow the template we've provided, so I'm going to close this for now. If you've encountered a bug, I will re-open once we have the necessary info to troubleshoot 👍 

Note: We try to keep Github issues for bugs in the Expo SDK. For questions- I suggest posting on our [Forums](https://forums.expo.io/). For feature requests, head on over to our [Feature Request Page](https://expo.canny.io/feature-requests).

Thanks!
Charlie
