### ISSUE TITLE
Python SDK example code doesn't work

### ISSUE THREAD

**Issue by antgel** [expo/expo#4197]
Hi, I'm attempting to use https://github.com/expo/expo-server-sdk-python/blob/master/README.md to send push notifications to Expo apps from my Flask server.

There are a couple of `raise self.retry(exc=exc)` lines in there, which cause exceptions. What is `self.retry(...)`? We're not in a class, and there's no `retry(...)` method.

**Comment by cruzach** [comment]
Hi @antgel , 

That repo is actually maintained by the community (see [here](https://docs.expo.io/versions/latest/guides/push-notifications/#2-call-expos-push-api-with-the)) and the README is just out of date pointing here, so I'll change that.

Please feel free to open a PR for it, though!

**Comment by antgel** [comment]
@cruzach Thanks for responding, just saw this. Where should issues for that repo be opened, if not here? The repo issue tracker is disabled. Also, any clues who exactly "the community" is in this case?

**Comment by cruzach** [comment]
Hey @antgel, that repo has issues enabled now, so you're all set! 

And the community just refers to the people who use and contribute to Expo (including you 😄)
