### ISSUE TITLE
app.json - ios.config.bundleIdentifier doesn't work

### ISSUE THREAD

**Issue by methodbox** [expo/expo#4199]
### Environment

Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.12 => 32.0.12 
      @types/react-native: ^0.57.51 => 0.57.51 
      @types/react-navigation: ^3.0.6 => 3.0.6 
      expo: ^32.0.0 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.17.1

Both, but iOS for the moment.

### Steps to Reproduce

When using the `MapView` component, the API rejects usage of the API key unless no restrictions are placed on it.

Placing the iOS restriction when providing the iOS config in `app.json` does not work; it indicates the app, IP, etc. are restricted.

For example, in the config shown below, we would use `com.example.app` as the allowed identifier at Google in the API restrictions. This does not work and it is indicated that there is an empty referer (sic - their spelling, not mine).

```json

"ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.example.app",
      "config": {
        "googleMapsApiKey": "redacted-api-key"
      }
    },
```
### Expected Behavior

The `bundleIdentifier` value should be sufficient to identify the app to the Google API. It doesn't seem this is the case.

### Actual Behavior

The API failure suggests the app identifier is not passed when performing an API request.

### Reproducible Demo

In order to reproduce this, you need to install `react-native-maps-directions` and attempt to make a second API request after the initial load. I did this with a button which just update the coordinates stored in state to simulate a subscription to an updating observable containing the coordinates. When the button is pushed, the marker moves and a new API request is sent.

My best guess is that somehow this module escapes the expo wrapper and it ends up the `bundleIdentifier` isn't tied to it's API request.

This poses a fundamental concern with Expo: how do we send an API request that includes the `bundleIdentifier` when we are making a general API fetch request, if this is required?

If I allow the API unrestricted, it works fine. If I restrict it to the iOS app bundle identifier in my `app.json`, it does not work, except on initial load.

This won't work in a snack, here's the test code:

```js
import React from 'react';
import { View } from 'react-native';
import { MapView } from 'expo';
import { LatLng, Marker, Region } from 'react-native-maps';
import MapViewDirections from 'react-native-maps-directions';
import { Button } from 'react-native-elements';

type State = {
  initialRegion: Region;
  startMarker: LatLng;
  endMarker: LatLng;
};

export default class MapTest extends React.Component<State> {
  state = {
    initialRegion: {
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    },
    startMarker: {
      latitude: 37.78825,
      longitude: -122.4324,
    },
    endMarker: {
      latitude: 37.88,
      longitude: -122.0,
    },
  };

  _onMapChange = () => {
    setTimeout(() => {
      this.setState({
        endMarker: {
          latitude: this.state.endMarker.latitude + 0.009,
          longitude: this.state.endMarker.longitude + 0.0008,
        },
      });
    }, 300);
  };

  render() {
    return (
      <MapView style={{ flex: 1 }} initialRegion={this.state.initialRegion}>
        <Marker coordinate={this.state.startMarker} />
        <Marker coordinate={this.state.endMarker} />
        <MapViewDirections
          origin={this.state.startMarker}
          destination={this.state.endMarker}
          apikey={'redacted api key'}
          strokeWidth={5}
          strokeColor="blue"
        />
        <View style={{ position: 'absolute', alignSelf: 'flex-end' }}>
          <Button title="Change State" onPress={() => this._onMapChange()} />
        </View>
      </MapView>
    );
  }
}
```

**Comment by methodbox** [comment]
@dsokal Any chance you've had an opportunity to look at this?

**Comment by Szymon20000** [comment]
Did you run this code within Expo Client or you have your own standalone app?

**Comment by methodbox** [comment]
Expo client. Is that the issue?

**Comment by Szymon20000** [comment]
We can change bundleIdentifier only on standalone and detached apps.

**Comment by methodbox** [comment]
@Szymon20000

Ok thanks! Did not realize that. I may review the docs to see if there is an opportunity to better communicate that.

Thanks for the feedback!

**Comment by methodbox** [comment]
> We can change bundleIdentifier only on standalone and detached apps.

Is there a default bundleIdentifier which Expo uses? Is that documented somewhere?
