### ISSUE TITLE
[Suggestion] Add QR code on Exponent project website

### ISSUE THREAD

**Issue by alphasp** [expo/expo#42]
Not sure whether this is the correct place to raise this issue as this is related to Exponent website.

Currently, Exponent app have QR scan feature which is cool, but we are not able to fully utilise this feature by scanning QR code from Exponent project website to try out demo without typing on mobile device. It will be great to display QR code on Exponent project website.

**Comment by jesseruder** [comment]
Interesting idea! We'll definitely think about that.

**Comment by lucfranken** [comment]
Am I correct that this is about this page right?
<img width="1238" alt="schermafbeelding 2017-04-25 om 12 18 19" src="https://cloud.githubusercontent.com/assets/1609379/25380698/76a4371c-29b1-11e7-82f2-4ca238248d81.png">
Would be really useful if that's the case. If not: I will post new issues on this.

**Comment by alphasp** [comment]
@lucfranken Yes.

**Comment by terribleben** [comment]
This is a thing now!
