### ISSUE TITLE
ScreenOrientation.Orientation.All not working

### ISSUE THREAD

**Issue by mlvhub** [expo/expo#420]
Hello, I haven't been able to get the ScreenOrientation.Orientation.All to work, setting it in the app.json as "default" does nothing but I've seen this is an issue right now, and that using ScreenRotation as a workaround is the way to go, but using it does nothing for me.

All portrait and landscape modes work fine, but the ALL or ALL_BUT_UPSIDE_DOWN which are the ones I want don't.

I even tried cloning the app below, but it doesn't work either. My app uses Expo 18, I also tried with 19 but with no luck. For what I saw in the repo below, it uses Expo 19 as well.
https://github.com/expo/native-component-list

All I did was clone it, run "npm install" and open it in Expo.
My Expo XDE version is 2.19.2, in case that's helpful.

Thanks.

**Comment by donni106** [comment]
I also tried to change the orientation in my app.json to default (or removing the key entirely) to have an rotating app. Nothing happens, it stays portrait.
Is there a way to fix this?

@mlvhub you say
> I've seen this is an issue right now
So editing the app.json does not help anybody?

What can I do to get my app rotating?

**Comment by mlvhub** [comment]
> So editing the app.json does not help anybody?

That's what I've seen in other issues in this repo.

> What can I do to get my app rotating?

Well, have you tried using [ScreenOrientation](https://docs.expo.io/versions/v18.0.0/sdk/screen-orientation.html)?

In my case, that didn't work either, so I ended up [detaching from Expo](https://docs.expo.io/versions/v18.0.0/guides/detach.html) to be able to control the native projects manually, and now my app is rotating normally.

Hope that helps.

**Comment by skevy** [comment]
Thanks for the report. This is on our internal task list, and someone will get back to you early next week about this. Thanks!

**Comment by donni106** [comment]
With having nothing given in app.json it works now. I can rotate devices and simulators and the app is following.

**Comment by terribleben** [comment]
Hello, I just tried testing this in https://github.com/expo/native-component-list and it works as expected with both `ALL` and `ALL_BUT_UPSIDE_DOWN`. I'm running iOS 10.3 on my device, using the latest SDK. Are you using a different version of iOS, perchance?

**Comment by dikaiosune** [comment]
Going to give this a close pending a reply to Ben's question above. Please let us know how to repro and we'll reopen. Thanks!
