### ISSUE TITLE
Execution failed for task ':app:bundleProdKernelReleaseExpoAssets'. Process 'command './node_modules/expokit/detach-scripts/run-exp.sh'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#4202]
### Environment

 Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.2.1 => 3.2.1 
    npmGlobalPackages:
      expo-cli: 2.17.1

ExpoKit (Android)

### Steps to Reproduce

I want to create release apk, when I'm trying to create it I'm getting an error 
` Execution failed for task ':app:bundleProdKernelReleaseExpoAssets'. Process 'command './node_modules/expokit/detach-scripts/run-exp.sh'' finished with non-zero exit value 1` 

### Expected Behavior

I should get release apk

### Actual Behavior

I'm getting an error

### Reproducible Demo

eject expo project to ExpoKit 
do expo publish 
create release build

**Comment by AnderAmorim** [comment]
I managed to solve running `expo publish`. I hope it works for you too.

**Comment by adamsythe** [comment]
I had this issue after publishing through the CLI.  I then published through command line and it worked.  Not sure if its the command line that fixed it, or just publishing a second time or possibly just building some time after the first publish.

**Comment by chenliang2016** [comment]
hi :
  do you resolve this problem

**Comment by Luckygirlllll** [comment]
Yes, I resolved it, but I don’t remember what exactly I did, as far as I remember, I was try expo publish once again, plus don’t forget, that you need to run expo publish, when expo start is running, also make sure that you  have latest version of CLI.

**Comment by paragbhadoria** [comment]
@Luckygirlllll, I was facing the same issue.
And after hell lot of searching and analysing things. I realised the problem could be either with my assets or the published version of the project. 
As app:bundleProdKernelReleaseExpoAssets includes prod (production) and assets
So steps I followed are:
1. In Terminal go to expo root 
2. run expo optimise (to optimise assets)
3. run expo publish (so your local copy is reflected live)
4. Came back to android studio cleaned the project and tried build release apk / bundle again

**Comment by nandhakishorenk** [comment]
@paragbhadoria  what is expo root?  and while running 'expo optimize' i am getting the error that the command needs the dependency of installing the sharp-cli@1.1.10, but it throws the same error even after the installation of sharp-cli

**Comment by paragbhadoria** [comment]
@nandhakishorenk by expo root I meant expo project's root directory. I don't remember anything about sharp-cli. But after following the steps mentioned [here](https://github.com/expo/expo/issues/4202#issuecomment-509017837) I was able to resolve it.

**Comment by nandhakishorenk** [comment]
@paragbhadoria 
![Screenshot 2019-09-16 at 4 47 51 PM](https://user-images.githubusercontent.com/31855442/64954117-42e33980-d8a2-11e9-8573-a9afd3aed3d7.png)
This is the issue i am facing while optimizing expo assets.

**Comment by paragbhadoria** [comment]
@nandhakishorenk 
can you help me out with your environment details:
1. Node version
2. Expo version
3. React Version
4. React Native Version
5. MacOS version

**Comment by nandhakishorenk** [comment]
node : 10.16.0
mac os: 10.154.6
react: 16.5.0
expo: 32.0.0
react-native: expo sdk 32.0.0

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. It sounds like the original issue here has been resolved. If you're still running into this, please create a new issue on the [`expo-cli` repo](https://github.com/expo/expo-cli) with full repro steps (including a GH repo with a project to publish, if necessary). Thanks!
