### ISSUE TITLE
Getting a simple list of images from user device

### ISSUE THREAD

**Issue by tzookb** [expo/expo#421]
Read through the docs and permissions and could not find how to get the user images with Expo.

I know I can access the camera and take a picture, but not access to

    CameraRoll.getPhotos()

and I only want the photos to display them on my app.

Any ideas?

**Comment by dikaiosune** [comment]
Is there a reason that you can't use RN's [CameraRoll API](https://facebook.github.io/react-native/docs/cameraroll.html) in combination with the Expo permissions API? Can you use https://snack.expo.io to demonstrate the problem you're hitting?

**Comment by tzookb** [comment]
thanks @dikaiosune 

maybe Im really off here :/

As I can see in CameraRoll API, I need to link the "RCTCameraRoll"
and as I understand in Expo, you cant link external plugins unless you eject your project or if the plugin is already part of Expo SDK API

If Im wrong, I would be happy if you could scribble some code so I know which part to add,
as I tried importing "CameraRoll" and to use  expo "ImagePicker" but with no success .

Thanks!

**Comment by ide** [comment]
RCTCameraRoll is already link when you use Expo. See this example Snack: https://snack.expo.io/BkhOYRPUZ.

**Comment by tzookb** [comment]
You are the king @ide !
