### ISSUE TITLE
uncaught error module appregistry is not a registered callable module

### ISSUE THREAD

**Issue by farhanaslam5151** [expo/expo#4210]
![60234247_431319104093915_5167438375459749888_n](https://user-images.githubusercontent.com/38375932/57647252-e44c3d00-75db-11e9-8b11-7de5e67f7bae.jpg)

app is working fine on expo client when make expo:build after installing into android giving this error

Package.json
{
  "main": "src/index.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "firebase": "^6.0.2",
    "native-base": "^2.12.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-swipe-gestures": "^1.0.3",
    "react-navigation": "^3.9.1",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "babel-plugin-import":"1.5.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

**Comment by raajnadar** [comment]
If the error is only in production then try turning on production mode in expo web interface.

**Comment by farhanaslam5151** [comment]
> If the error is only in production then try turning on production mode in expo web interface.

i don't know how to do with expo web interface can you please guide me

**Comment by cruzach** [comment]
Hi @farhanaslam5151 ,

We need more information to help you out, so please follow the issue template, and definitely provide a reproducible example! The error in the title indicates and issue that's stopping your javascript from being loaded. 

Once we get the info and repro, then I will re-open the issue 👍 

-Charlie
