### ISSUE TITLE
Change header color on overview screen. 

### ISSUE THREAD

**Issue by YajanaRao** [expo/expo#4214]
Is there a way to change the color of the header of my app on the overview screen ?

As we can see with these applications

![image](https://user-images.githubusercontent.com/38914337/57685787-3fbb1100-7656-11e9-998d-a4a4cd8f6954.png)

**Comment by AdamJNavarro** [comment]
Hey @YajanaRao,

You'll want to configure your [primaryColor](https://docs.expo.io/versions/v32.0.0/workflow/configuration/#primarycolor) value in your `app.json`. Also, we try our best to keep Github issues reserved for bug reports. For future questions like this one, please create a post in our [forums](https://forums.expo.io/)!

Cheers,
Adam
