### ISSUE TITLE
expo-yarn-workspaces v1.1.0 - Windows 10 - spawnSync UNKNOWN

### ISSUE THREAD

**Issue by nattyrice** [expo/expo#4215]
### Environment

  Expo CLI 2.17.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Users\thana_000\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

I was attempting to configure and run expo in a yarn workspace.  Using expo-yarn-workspaces.  

### Steps to Reproduce
Simply running `expo-yarn-workspaces postinstall`  (Either via npx, or package.json script).  This issue is specific to running in a Windows environment.

### Expected Behavior

I expected it to symlink and generate an AppEntry.js file.

### Actual Behavior

The expo-yarn-workspaces.js script in the bin folder attempts this line of code:

```
child_process.execFileSync(path.join(__dirname, 'symlink-necessary-packages.js'), {
      stdio: 'inherit',
    });
```

Which results in this error:

`spawnSync D:\Projects\Parade\packages\app\node_modules\expo-yarn-workspaces\bin\check-workspace-dependencies.js UNKNOWN`

### Reproducible Demo

Use the package, in pretty much any way, while on Windows. 

### Fix Action

There are three calls to child_process.exeFileSync in the package like the one above.  To fix this problem, all you need to do is change them to mirror this example:

```
   child_process.execFileSync(
      "node",
      [path.join(__dirname, "symlink-necessary-packages.js")],
      {
        stdio: "inherit"
      }
    );
```

The problem came from relying on Shebangs in the scripts when trying to execute with `execFileSync()`.  On Windows, you need to explicitly use "node" as the command.  Shebangs are not supported.  Again, there are three locations, you will need to change them all to call node.

I would have submitted PR but your README says to contact somebody on the project first before submitting a PR.  Consider this me doing that.

**Comment by ide** [comment]
Feel free to submit a PR for this. Windows support is a mix of YMMV and BYOB so a PR would be appreciated.
