### ISSUE TITLE
Use prop-types package

### ISSUE THREAD

**Issue by EnriqueDev** [expo/expo#422]
Hi! I've started using expo a couple of months ago and there is always the following warn in the console:

```
console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
```

I guess you are probably working on it already, but just as a reminder I'll open this issue. Feel free to close it if it has already been reported.

**Comment by dikaiosune** [comment]
Hi! These warnings are due to upstream React Native using React 16. The warnings will be resolved in a future RN release. Thanks!
