### ISSUE TITLE
AdMob: AdMobInterstitial.showAdAsync() does not resolve

### ISSUE THREAD

**Issue by pawelsas** [expo/expo#4226]
### Environment

System:
  OS: macOS 10.14.4
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 10.13.0 - /usr/local/bin/node
  Yarn: 1.7.0 - /usr/local/bin/yarn
  npm: 6.9.0 - /usr/local/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
  Android Studio: 3.2 AI-181.5540.7.32.5056338
  Xcode: 10.1/10B61 - /usr/bin/xcodebuild
npmPackages:
  expo: ^32.0.6 => 32.0.6 
  react: 16.5.0 => 16.5.0 
  react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
  react-navigation: ^3.3.0 => 3.3.0 
npmGlobalPackages:
  expo-cli: 2.14.0

Standalone

### Steps to Reproduce

There are basically 2 screens.

1. Screen: preload ad and pass information whether to show the ad to the next screen

```
import { AdMobInterstitial } from 'expo'

async componentDidMount() {
  AdMobInterstitial.addEventListener('interstitialDidFailToLoad', () => {
    this.showAd = false
  })

  try {
    const preloaded = await AdMobInterstitial.getIsReadyAsync()

    if (!preloaded) {
      AdMobInterstitial.setTestDeviceID('EMULATOR')
      AdMobInterstitial.setAdUnitID(INTERSTITIAL_ID)

      await AdMobInterstitial.requestAdAsync()
    }
  } catch (error) {
    this.showAd = false
  }
}

componentWillUnmount() {
  AdMobInterstitial.removeEventListener('interstitialDidFailToLoad')
}
```

2. Screen: show ad if necessary

```
import { AdMobInterstitial } from 'expo'

async componentDidMount() {
  if (this.showAd) {
    try {
      const loaded = await AdMobInterstitial.getIsReadyAsync()
      if (loaded) {
        await AdMobInterstitial.showAdAsync() // the app crashes here 
      }
    } catch (error) {
      ...
    }
  }
}
```

### Expected Behavior

If the ad is preloaded successfully, an Interstitial is shown on screen 2.
If the is NOT preloaded successfully, nothing happens.

### Actual Behavior

After the ad is shown several times (sometimes 2, sometimes 50) `await AdMobInterstitial.getIsReadyAsync()` resolves to true but `await AdMobInterstitial.showAdAsync()` does not resolve. This leads to an endless loop which crashes the app.

I'm not sure if it does matter but the app has 20K+ monthly impressions. Maybe thats to much for AdMob?

### Reproducible Demo
Will follow soon if necessary.

**Comment by cruzach** [comment]
@pawelsas - is this happening on iOS, Android, or both?

**Comment by pawelsas** [comment]
@cruzach I was able to reproduce it 4 or 5 times on iOS. Not sure (yet) if it happens on Android as well.

**Comment by pawelsas** [comment]
Here's a test snack: https://snack.expo.io/@psas/admob-example

Unfortunately, the ad unit id must be replaced by an actual id. That's why this is so hard to reproduce.

But a general question: why is `showAdAsync` async? I mean there's no need to block everything just to show an interstitial. The ad is must be requested/loaded before anyway. Imho this is just a potential source of error.

**Comment by pawelsas** [comment]
Update: after further testing I noticed that the bug occurs only when `await AdMobInterstitial.requestAdAsync()`and `await AdMobInterstitial.showAdAsync()` are split into different screens.

Imho this is really bad for user experience because the ad may take some seconds to load. Meanwhile the user will most likely continue using the UI. A delayed ad popup may be confusing and annoying (more annoying than an ad needs to be).

**Comment by macmal** [comment]
I did something similar and it works. I have Ad.js file shared with other screens:
export async function requestFullAd(adname) {
    console.log("set AdUnitId")
    if (adname == "Support")
        AdMobInterstitial.setAdUnitID('ca-app-pub-3940256099942544/1033173712');// Test ID    
    if (adname == "Alert")
        AdMobInterstitial.setAdUnitID('ca-app-pub-3940256099942544/1033173712');// Test ID  
    console.log("request ad")
    await AdMobInterstitial.requestAdAsync({ servePersonalizedAds: true });   
}
export async function showAd() {
    console.log("display ad")
    const loaded = await AdMobInterstitial.getIsReadyAsync()
    console.log(loaded);
    if (loaded)
        await AdMobInterstitial.showAdAsync();
    else
        console.log("add not loaded yet")
}

other screens:
import * as Ad from './Ad';
*****
componentDidMount() {
Ad.requestFullAd("Alert");
}
buttonClick(){
Ad.showAd();
}
*****

**Comment by VictorioMolina** [comment]
Did you solve this issue? I am getting the error "Add cannot be presented".

https://github.com/expo/expo/issues/17536
