### ISSUE TITLE
Standalone apps should hard crash rather than show Expo error UI

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4230]
In our [Error Handling doc](https://docs.expo.io/versions/v32.0.0/guides/errors/):

> In Production: If your published app encounters a fatal JS error, Expo will immediately reload your app. If the error happens very quickly after reloading, **Expo will show a generic error screen with a button to try manually reloading.**

@ide, @ccheever, @tcdavis and I all agreed that we should not show any Expo UI in standalone apps and that it is preferable to hard crash the app than to show these screens:

<img width="412" alt="Screen Shot 2019-05-15 at 15 54 04" src="https://user-images.githubusercontent.com/90494/57814946-3b602800-772a-11e9-9f4b-02bddd2329a8.png">

<img width="468" alt="Screen Shot 2019-05-15 at 16 04 59" src="https://user-images.githubusercontent.com/90494/57815180-38b20280-772b-11e9-81e7-0f34446caabe.png">

**Comment by harisvsulaiman** [comment]
@brentvatne Will this be included in SDK 33

**Comment by brentvatne** [comment]
Probably not initially but we may roll it out in a patch release.

**Comment by llamaluvr** [comment]
Hi! Is there any place in the code (for Android in particular) you could point me that triggers this error screen? I'm wondering if it's something I can try to override as a temporary workaround in an ExpoKit project. In our case, it's not great aesthetically to show the error screen, but the bigger issue at the moment is that we have classes of mysterious device-specific errors that don't get reported to Play Store Console as crashes; or errors that throw the native bits into an unstable that a JS restart cannot resolve (like this one https://github.com/facebook/react-native/issues/17530). Thanks!

**Comment by ide** [comment]
@sjchmiela could you please assign this to someone at SWM and prioritize it for SDK 35?
