### ISSUE TITLE
expo-camera types installed with Expo v.32.0.0 vs. @types/expo

### ISSUE THREAD

**Issue by methodbox** [expo/expo#4231]
### Environment

```bash
Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.17 => 16.8.17 
      @types/react-native: ^0.57.57 => 0.57.57 
      expo: ^32.0.0 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.17.1
```

Both
### Steps to Reproduce

The files `Camera.d.ts` and `index.d.ts` are still included in the `expo-camera` package installed with the default `expo` node package.

These contain types that conflict with those [which are newer] in `index.d.ts` provided by `@types/expo`.

An easy way to see this is to create a module using the `Camera` component; you will get a conflict when using `esnext` or `es5` in
your `tsconfig.json` due to the method of importing React:

```js
//  wrong 
import React from 'react';

//  right
import * as React from 'react';

//  right - used in @types/expo/index.d.ts
import { Component, ComponentClass, Ref, ComponentType } from 'react';
```
This is a bug because they should be removed; they supersede those in the `@types` package. I'm sure although I haven't been able to produce it the duplicate definitions will eventually cause problems, too.

### Expected Behavior

There should be not be this error when using the `Camera` component:

```js
JSX element class does not support attributes because it does not have a 'props' property.
```
There is no error when React is properly imported / the files are removed.

### Actual Behavior
This error is seen, unless the files are removed or modified as stated above.
```js
JSX element class does not support attributes because it does not have a 'props' property.
```

### Reproducible Demo

You can use my fork of `camerja`:
https://github.com/methodbox/camerja

All you have to do is `npm install` and open the `App.tsx` in VS Code, scroll down to the `<Camera>` and search out the definition. It will drop you in `node_modules/expo-camera/Camera.d.ts`

**Comment by ide** [comment]
All the main unimodules have been migrated to TS in SDK 33 (not yet released, but addressed on master) and the TS definitions are used in the test apps in this repo, so closing this. Feel free to make a new issue when 33 is out if it isn't resolved.

**Comment by methodbox** [comment]
> All the main unimodules have been migrated to TS in SDK 33 (not yet released, but addressed on master) and the TS definitions are used in the test apps in this repo, so closing this. Feel free to make a new issue when 33 is out if it isn't resolved.

In that case, is it worth placing a PR to update the documentation to warn of this conflict?

https://docs.expo.io/versions/latest/guides/typescript/#__next

Your docs (for v32.0.0) indicate to install `@types/expo`, which is in direct conflict with that version.

I feel like if you're not going to both to fix it in this version, users should still be aware of the conflict and how to resolve it (which is just to remove the offending *.d.ts files).

**Comment by ide** [comment]
Feel free to send a PR; I closed this since the root issue is addressed on master and we're focused on the `n+1`th release.

**Comment by methodbox** [comment]
Kk will do thanks.
