### ISSUE TITLE
jest-expo 33-alpha for use with expo@33.0.0-alpha.web.3

### ISSUE THREAD

**Issue by marnusw** [expo/expo#4233]
We have started using `expo@33.0.0-alpha.web.3` for the web build which is excellent. We have found, though, that this version does not seem immediately compatible with `jest-expo@32.0.0`. I noticed in #4154 that there is a tick against "Generate new mocks and update `jest-expo`" which I'm hoping means the `jest-expo` on `master` works with the latest 33 alpha. Is there any chance a `jest-expo@33-alpha` could be released in the near future to use for this setup?

As a side note, with some fiddling I think we got it *almost* working by juggling some dependencies and configs, but we now get the error `The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo.` so my guess is the latest Expo SDK isn't detected by old `jest-expo` correctly which is understandable.

**Comment by ide** [comment]
When SDK 33 is released, we'll have all the packages published. In the meantime you could use your own npm registry or install from your computer locally.

**Comment by marnusw** [comment]
Got it. Thanks for the reply and for your continued work on Expo, it's incredibly valuable.

**Comment by ide** [comment]
We've published 33.0.0-alpha.0 to npm if you would like to try it.

**Comment by marnusw** [comment]
That's excellent! Thank you very much.
