### ISSUE TITLE
Animated GIF support for ImagePicker doesn't work as expected

### ISSUE THREAD

**Issue by RajatPawar** [expo/expo#4238]
## 🐛 Bug Report
Animated GIF support doesn't work as expected - here is the given documentation in ImagePicker (https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/imagepicker.md)
`Animated GIFs support If the selected image is an animated GIF, the result image will be an animated GIF too if and only if quality is set to undefined and allowsEditing is set to false. Otherwise compression and/or cropper will pick the first frame of the GIF and return it as the result (on Android the result will be a PNG, on iOS — GIF).`

### Environment
Expo CLI 2.14.0 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 8.16.0 - /usr/bin/node
      Yarn: 1.15.2 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    npmPackages:
      expo: ^30.0.0 => 30.0.0 
      react: 16.4.1 => 16.4.1 
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4 
      react-navigation: 2.6.0 => 2.6.0 
    npmGlobalPackages:
      expo-cli: 2.14.0

### Steps to Reproduce
1) Use ImagePicker to try to select a GIF from the ImagePicker.launchImageLibraryAsync method
2) As per given in the documentation, use the options - allowEditing: false & quality: undefined 
3) Print out the result.uri once you have chosen the GIF
4) It outputs a JPG path and chooses a still of the GIF and not the entire GIF

### Expected Behavior
I expect it to return a GIF path that I can use to upload to firebase storage

### Actual Behavior
A JPG still of the GIF is chosen instead and placed in the expo filesystem

### Reproducible Demo
```
import ImagePicker from 'expo';
import React, { Component } from 'React';
import {Text, View, TouchableOpacity} from 'react-native';

export default class Select extends Component {
  state = {};

  _selectPhoto = async () => {
        const result = await ImagePicker.launchImageLibraryAsync({
                           mediaTypes: 'Images',
                          allowsEditing: false,
                          quality: undefined,
                          aspect: undefined,
                          base64: false
      });

      if (!result.cancelled) {
        alert(result.uri);
      }
  };

  render() {
    return (
      <View>
        <TouchableOpacity onPress={this._selectPhoto}>
          <Text>
            Select Photo
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```

In the above, I tried using additional aspect/base64 options to try and see if that could help me - but to no avail. The alert shows me a JPG still.

Please let me know if this is a bug or if it's me doing something wrong! Thank you for your time.

**Comment by cruzach** [comment]
Hi @RajatPawar,

The docs you linked are actually `unversioned` so they aren't really applicable just yet. SDK 33 will have support GIFs in ImagePicker (see the [changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md))

On a side note- I see you're using SDK 30, and just thought I'd let you know that we are deprecating support for SDK <31, so I definitely suggest upgrade! You can find guides on that [here](https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/)

Thanks!
Charlie

**Comment by RajatPawar** [comment]
@cruzach Thanks for the quick reply! My apologies for this question, but if you could help with understanding when SDK33 will be stable or available for use, that'd be great (I see now that the master branch has this feature but is probably unstable!)

Again - thanks for taking out the time!

**Comment by cruzach** [comment]
No apologies needed! I can't give you a definitive date on the release, but it's looking soon, within the next couple of weeks 😄
