### ISSUE TITLE
Detox example project

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#424]
[Detox](https://github.com/wix/detox) is a neat "gray box" testing library that is useful for end to end acceptance testing. We should have an example project that shows how to integrate with it.

**Comment by cem2ran** [comment]
@brentvatne Reopening this one to get an idea about the state of getting Detox working again with Expo as there are quite a few issues pilling up on the Detox repo.
My findings so far debugging the issue: https://github.com/wix/detox/issues/917#issuecomment-422396875

I'd be happy maintaining the support including example repo going forward and add Android support when the above mentioned issue is resolved.
