### ISSUE TITLE
[jest-expo] jest does not work on windows

### ISSUE THREAD

**Issue by DenisBiondic** [expo/expo#4248]
### Environment

Tested on several development workstations with different versions of:
Windows 10
Node.js (ranging 8-11)

### Steps to Reproduce

Start a simple project with jest-expo on windows, running npm test with jest through package.json does not work.

### Expected Behavior

jest tests run

### Actual Behavior

nothing happens

### Reproducible Demo

Clone this repo (on windows, linux works fine): https://github.com/DenisBiondic/ReactNativeJestSetupPrototypes/tree/master/ExpoBasicWithJest

`yarn install`
`yarn run test`

**Comment by DenisBiondic** [comment]
The core of the issue is the jest.js wrapper that comes with jest-expo. Somehow, on Windows, the jest.js to which it redirects is not recognized as executable file and cannot be run. Most people simply install jest manually and write 

package.json:
`"test": "node node_modules/jest/bin/jest.js",`

So, there are a few solutions here:
 - jest-expo does not implement the wrapper, and the documentation is updated so that users have to install jest themselves
 - jest-expo wrapper is fixed, this is a working solution I think:

instead of:
`const result = childProcess.spawnSync(jestProgramPath, jestProgramArgs, { stdio: 'inherit' });`
we could use:
`const result = childProcess.spawnSync("node", [jestProgramPath, jestProgramArgs], { stdio: 'inherit' });`

 - the node js executables on windows are somehow correctly recognized

**Comment by DenisBiondic** [comment]
Similar issues: https://github.com/expo/expo/issues/2306 https://github.com/expo/expo/issues/2515

**Comment by cruzach** [comment]
Hi!

So there's no output at all after running running the script [messages, errors, etc]?

@DenisBiondic would you like to open a PR with this fix? You should be able to test your fix locally

**Comment by ide** [comment]
Fixed in https://github.com/expo/expo/pull/3477 (thank you @Artorp!)

**Comment by ide** [comment]
Backported the PR linked right above to 32.0.1 and published to npm.
