### ISSUE TITLE
Can't specify headers when streaming audio files

### ISSUE THREAD

**Issue by anp** [expo/expo#425]
https://stackoverflow.com/questions/45332922/is-it-possible-to-download-an-audio-file-and-play-it-using-react-native-expo

**Comment by terribleben** [comment]
We may want to discuss best practices and documentation around streaming audio in general.

**Comment by butlermd** [comment]
Does this need to be turned into a feature request?

**Comment by sjchmiela** [comment]
SDK31 introduced a new `headers` property that you can use to specify headers used when downloading media files!

https://docs.expo.io/versions/v31.0.0/sdk/av#a-dictionary-of-the-form--uri
