### ISSUE TITLE
Disable browser zoom by default in Expo Web

### ISSUE THREAD

**Issue by ide** [expo/expo#4253]
The viewport config lets people zoom in via pinch or double tap, which conflicts with other gestures. Think we should disable zooming by default and let people enable it manually if they want (ex: provide their own viewport meta tag). 

ex: https://stackoverflow.com/questions/4472891/how-can-i-disable-zoom-on-a-mobile-web-page

**Comment by EvanBacon** [comment]
This had been a feature for a while, we removed it because it lowered the lighthouse score since it's considered bad practice.
