### ISSUE TITLE
Multipart body must have at least one part

### ISSUE THREAD

**Issue by lylest** [expo/expo#4255]
I am using expo react native I successfully picked an image from storage however I tried to send it using
let localUri = photo.uri;

      let formData = new FormData();
      formData.append('photo', {
        uri: localUri,
        name:ProductName
        //type:'image'
      })

    fetch('https://sizoni.000webhostapp.com/sell/upload.php', {
      method: 'POST',
      body: formData,
      header: {
         Accept: "application/json",
        'content-type': 'multipart/form-data',
      },
    });

but it fails and throw an error of Multipart body must have at least one part can someone help me out

**Comment by cruzach** [comment]
Hey @lylest,

This doesn't seem to be a bug in Expo, I think you're best bet is to look up some examples of multipart/form-data fetches ([here](https://stackoverflow.com/questions/32441963/how-to-use-formdata-in-react-native) is one) and try to debug from there. Feel free to post in our [How-To Forums](https://forums.expo.io/c/how-to) for some help, as well. We just try to keep Github for Expo-related bugs 😄 

-Charlie
