### ISSUE TITLE
[docs] Add reference to `Constants.manifest` in MapView docs, to access `googleMapsApiKey`

### ISSUE THREAD

**Issue by methodbox** [expo/expo#4257]
This isn't exactly "missing" from the docs, but I'm not sure how else to classify this. I am trying assist with a module which would use MapView and the Google API key found in app.json.

I'm wondering how a module (or any of our RN code) could be made to use the API key in app.json vs. storing it right in the code, for security reasons, as this is the best practice.

Is there a method to do this and if so, where is it documented?

**Comment by harisvsulaiman** [comment]
@methodbox try this https://docs.expo.io/versions/v32.0.0/sdk/constants/
https://docs.expo.io/versions/v32.0.0/sdk/constants/

**Comment by methodbox** [comment]
@harisvsulaiman Dude, you rock!

It's not in the docs, though so I may put in a PR to add that.

Here's how I accessed it in a test example:

```js
_onPressTest = (): void => {
    const test = Constants.manifest.ios.config.googleMapsApiKey;
    console.log(test);
  };
```

**Comment by methodbox** [comment]
Sweet looks like @cruzach go to this. Thanks, man!

**Comment by cruzach** [comment]
👍  Thanks for pointing it out!
