### ISSUE TITLE
FileSystem.documentDirectory changes between TestFlight and App Store version

### ISSUE THREAD

**Issue by seveneightn9ne** [expo/expo#4261]
## 🐛 Bug Report

The FileSystem.documentDirectory changes when switching between TestFlight and App Store app versions for a published iOS app. Practically, this means that images saved in the file system whose URIs are stored in AsyncStorage are now gone, because the saved URIs are not accessible.

### Environment

This bug happens in a standalone iOS app.

Expo diagnostics:
```
  Expo CLI 2.17.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.14.1 - /opt/node/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - /opt/node/bin/npm
    npmPackages:
      @types/expo: ^31.0.3 => 31.0.4 
      @types/react: ^16.7.17 => 16.7.18 
      @types/react-native: ^0.57.19 => 0.57.22 
      expo: ^31.0.4 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
```

### Steps to Reproduce

You can just `console.log(FileSystem.documentDirectory)` to observe that it changes when switching between TestFlight and App Store versions.

### Expected Behavior

I'd expect that versions of an app that share the same AsyncStorage share the same FileSystem.documentDirectory.

### Actual Behavior

The FileSystem.documentDirectory changes every time you switch between TestFlight and App Store versions, so if you switch, then anything you saved to the documentDirectory is not accessible anymore.

### Reproducible Demo

[This snack](https://snack.expo.io/@seveneightn9ne/thoughtful-tortilla) demonstrates the problem, but you'd need a fully deployed app to actually see it happen. If anyone is interested, I can add you to the TestFlight for my actual app, [Pottery Log](https://github.com/seveneightn9ne/pottery-log), and provide instructions to reproduce the problem from there.

**Comment by sjchmiela** [comment]
Hey! What are those paths? What's the difference? (Could you paste here document directory for TestFlight app and for the App Store app?)

**Comment by seveneightn9ne** [comment]
Basically, the folder name between `Application` and `Documents` randomizes every time you switch. These names are from one phone, switching from App Store to TestFlight back to App Store:

App store: `file:///var/mobile/Containers/Data/Application/5F0E8676-5353-4B9D-BB8F-185F3867FD9D/Documents/ExponentExperienceData/%2540seveneightn9ne%252Fpottery-log/`

Test flight: `file:///var/mobile/Containers/Data/Application/12E9380C-D528-499F-AF70-0DA636AEBC22/Documents/ExponentExperienceData/%2540seveneightn9ne%252Fpottery-log/`

App store: `file:///var/mobile/Containers/Data/Application/0A939A93-61D8-40A3-A0FD-2BE5B622336C/Documents/ExponentExperienceData/%2540seveneightn9ne%252Fpottery-log/`

**Comment by sjchmiela** [comment]
By _switching_, do you mean installing new builds? If so, I think the UUID may be right to change, at least according to some sources:

> This includes the path for [NSBundle mainBundle], which now looks something like
> ```
> /private/var/mobile/Containers/Bundle/Application/4CACB504-652B-44AF-8DBE-7AD40578507E/example.app/
> ```
> In addition, that UUID part of the path will change when updating the app or installing new builds during development.
> 
> Source: https://hetzel.net/2014-09-18/ios-8-folder-structure/

Strange thing would be if `AsyncStorage` was persisted between builds… Are you sure it is?

**Comment by seveneightn9ne** [comment]
Yeah, installing new builds. The AsyncStorage is definitely being persisted between the 2 versions, that's how my app gets links to files that aren't accessible. [Here's a video](https://www.dropbox.com/s/xr2ssadl6mniuaz/testflight-appstore-image-loss.MP4?dl=0) that demonstrates the problem, you can see we add an item with an image and then switch versions and the item (i.e. the AsyncStorage) is still there, but the image that was stored in the FileSystem is gone.

**Comment by brettdh** [comment]
I have the same issue, but it's in an ejected app, whenever I install a new build via `react-native run-ios`. The app stores paths that include `FileSystem.documentDirectory` in AsyncStorage, and installing a new build (iOS Simulator) keeps the paths in AsyncStorage, but they point to a directory that no longer exists.

Not sure what to do, other than invalidating all the paths if the app detects that the `documentDirectory` has changed. These are an offline cache of downloaded media, so this kinda works, but it's ugly - and if it happens on every update from the app store, that'd be really bad.

Is there a path that persists across installs? Or do the app's documents still stay there, just under a different UUID? Should I be storing relative paths, and appending them to `FileSystem.documentDirectory` just before loading the media?

**Comment by brettdh** [comment]
Update: after some light testing I can confirm that storing the relative path works - i.e. after a `react-native run-ios` reinstall, the new `documentDirectory` already contains the relative path that was saved before the reinstall. (whew)

**Comment by dean9703111** [comment]
I have same issue here.
When I push new version to TestFlight or appStore
My dir is change, can any way to keep use same dir?

**Comment by dean9703111** [comment]
Upate
filesystem in ios will update Directory in every update version.
But your file is still exsits in folder.
you just use relative path replace absolute path.

**Comment by mczernek** [comment]
I guess that the real solution to this problem is storing relative path rather than absolute. We cannot change behavior of iOS system itself, which does not guarantee paths to be persistent between builds.
