### ISSUE TITLE
Local Notification without connection 

### ISSUE THREAD

**Issue by Nparooei** [expo/expo#4262]
Hi ,I just used expo notifications in android it works perfect,  now I have a question,  when I run Notifications.getExpoPushTokenAsync()
It seems it needs Internet connection to give me the  result.  But my app mostly works offline . 
So I was wondering is there a way to get the token offline? Or it absolutely needs internet.

**Comment by cruzach** [comment]
Hi @Nparooei !

`Notifications.getExpoPushTokenAsync()` does require a network connection, so unfortunately you can't get it offline.

Side note- questions like this are perfect for our [Forums](https://forums.expo.io/), as we keep Github for bug reports!

-Charlie

**Comment by Nparooei** [comment]
So I Will Ask it in the forums.
