### ISSUE TITLE
[docs] sdk/filesystem

### ISSUE THREAD

**Issue by RWOverdijk** [expo/expo#4268]
Not 100% sure if this is a typescript bug or a documentation bug. However, [the docs of getInfoAsync say](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/filesystem.md#filesystemgetinfoasyncfileuri-options):

```
- options (object) -- A map of options:
  - md5 (boolean) -- Whether to return the MD5 hash of the file. false by default.
  - size (boolean) -- Whether to include the size of the file if operating on a source from CameraRoll.getPhotos() (skipping this can prevent downloading the file if it's stored in iCloud, for example). The size is always returned for file:// locations.
```

But the typings say:

```ts
export async function getInfoAsync(
  fileUri: string,
  options: { md5?: boolean; cache?: boolean } = {}
): Promise<FileInfo> {
  if (!ExponentFileSystem.getInfoAsync) {
    throw new UnavailabilityError('expo-file-system', 'getInfoAsync');
  }
  return await ExponentFileSystem.getInfoAsync(fileUri, options);
}
```

**Comment by cruzach** [comment]
Hey @RWOverdijk ,

Are you referring to `md5` not explicitly being defaulted to false?

**Comment by RWOverdijk** [comment]
No, that's not even possible in type definition files afaik. I'm talking about the `size` option being in the docs, and `cache` in the typings.

**Comment by cruzach** [comment]
Ah oops I completely glossed over that, thanks for specifying 👍
