### ISSUE TITLE
expo-file-system as standalone

### ISSUE THREAD

**Issue by RWOverdijk** [expo/expo#4269]
## 🐛 Bug Report

I'm trying to use the fs module standalone.

### Environment

- Expo: N/A
- Platform: iOS
- Standalone. It contains _nothing_ related to expo.

### Steps to Reproduce

https://github.com/expo/expo/tree/master/packages/expo-file-system#installation

### Expected Behavior

An installed and usable FS module.

### Actual Behavior

- No pod added to Podfile. 
- When running app anyway, "@unimodules/core" can't be found.
- Trying to add podfile myself doesn't work either. `pod 'EXFileSystem', :path => '../node_modules/expo-file-system/ios/EXFileSystem.podspec'` results in _Unable to find a specification for `UMCore` depended upon by `EXFileSystem`_

Seems like two separate issues.

### Reproducible Demo

I really want to supply one, but it's literally an installation issue so I can't make one.

1. `react-native init SomeName --template typescript`
2. `yarn add expo-file-system`
3. `react-native link expo-file-system`

No output (nothing linked). No updates in ios/Podfile.

**Comment by brentvatne** [comment]
see the readme: 

> For bare React Native projects, this package is included in react-native-unimodules, so if you use that then you already have this! If you are intentionally not using that package, follow the steps below to install expo-file-system manually.

**Comment by brentvatne** [comment]
my bad this is actually not properly described. you need to install react-native-unimodules to use it, as it's a pre-requisite for using any expo package outside of the managed expo experience

**Comment by brentvatne** [comment]
updated the readme, thanks for pointing this out!

**Comment by RWOverdijk** [comment]
@brentvatne It's not a rap battle, you can slow down :p 

Appreciate the fast response, thanks.

**Comment by RWOverdijk** [comment]
Speaking of rap battles, I'm guessing there's no way this'll become a standalone thing? I really don't want to use any more of expo than I absolutely have to.

I'm fine with helping out, if that's something you'd be open to.
