### ISSUE TITLE
Is there a way to refresh a stack/page?

### ISSUE THREAD

**Issue by rrajasek92** [expo/expo#427]
I have a switch component, which controls a bunch of sub-switches further down the stack. When the sub-switches are all off I want the master switch component to be re-rendered as off. I have all the logic in place, it's just I can't find a way to have the page reload when I pop back up to said page. Anyone know if this is possible?

**Comment by terribleben** [comment]
Hi! We're hoping to limit this board to tracking bugs in Expo, but it sounds like you have a question about your app's implementation. You might want to make use of a state management tool like Redux for something like what you described. I recommend asking about this on the [forum](http://forums.expo.io).
