### ISSUE TITLE
Expo Constant Linking Uri

### ISSUE THREAD

**Issue by surndraraj3** [expo/expo#4277]

**Comment by surndraraj3** [comment]
Constants.linkingUri
let base_scanner_ip = Constants.linkingUri;
base_scanner_ip = base_scanner_ip.replace(/[a-zA-Z/]/g, "");
base_scanner_ip = base_scanner_ip.split(":");
export const DeviceURL = base_scanner_ip[1];

Expo linking Uri is working on development mode for android. When i build application it's displaying as empty. Can anyone help me on this

In ios simulator: Linking URI is displaying as 12.0.0.1 instead of IP address
package.json
{
"expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
}

**Comment by cruzach** [comment]
Hey @surndraraj3 ,

Can you try using the [Linking](https://docs.expo.io/versions/v32.0.0/sdk/linking/) API instead? If you encounter behavior you believe could be a bug, then open a new issue and please follow the issue template 😄 

Thanks!
Charlie
