### ISSUE TITLE
Unable to put snapshot results into a PDF

### ISSUE THREAD

**Issue by ttchuah** [expo/expo#4278]
### Environment

  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 6.11.1 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 

I want to end up with a standalone app that runs in iOS and Android.

### Steps to Reproduce

**What I want to accomplish:** Take a screenshot of a particular view, then put the resulting image into a PDF. I then want to let the user be able to print it. This needs to work in both iOS and Android. 

How to reproduce? Clone this repo and then run it (yarn start). 
https://github.com/ttchuah/react-native-screenshot

Have both an iOS and Android device handy and run the app on both.

In the app, first press on the button labelled "take a screenshot using takeSnapshotAsync()". This will generate a screenshot image on the screen. (Slightly skewed dimensions, but I will take care of this later). This proves that using Expo's takeSnapshotAsync() method does properly create an image.

Next, press on the "Print screenshot" button. It should take you to the device's print-preview screen.

### Expected Behavior

In the print-preview screen, the screenshot image should show up above the text "Hello world".

### Actual Behavior

In the print-preview screen, the image only shows up on Android. In iOS, it is blank.

### Reproducible Demo

See this repo below. All the code is in App.js.
https://github.com/ttchuah/react-native-screenshot

### An explanation of what I tried

In a nutshell, I am using Expo's [takeSnapshotAsync](https://docs.expo.io/versions/latest/sdk/take-snapshot-async/) method to get a screenshot of a View component. 

Note that the `snapshot` variable is the URI of the screenshot. `pixels` just holds a numeric value.

```javascript
let html = `<img src="${snapshot}" width="100%" style="border:2px solid black; height:${pixels}px; width:${pixels}px;" />`;
            html += '<p>Hello world</p>'

            const pdf = await Print.printToFileAsync({ html });

            return Print.printAsync({ uri: pdf.uri }).catch(error =>
                Alert.alert(error.message)
            );
```

At the point where it hits Print.printAsync(), the device will open up the print preview screen. This is where you'll see the missing image on iOS.

I should note that this used to work for iOS on Expo v30. However, I had to upgrade to v32 in order to take advantage of an Expo bug fix, so going back to v30 isn't an option for me.

**Comment by tsapeta** [comment]
Hey @ttchuah,
If I remember correctly, `takeSnapshotAsync` returns a path without `file://` prefix - have you tried adding it before `snapshot` to the `src` attribute?

**Comment by ttchuah** [comment]
@tsapeta 
That worked. Thank you.

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Hi, I got the same issue. react-native-view-shot produces an uri like this (on the iOS simulator):

`/Users/username/Library/Developer/CoreSimulator/Devices/DFE9AEB4-B5E5-424D-A1F1-2849964F143F/data/Containers/Data/Application/CDFF398D-7600-4864-8EF3-2602D4F99025/tmp/ReactABI35_0_0Native/02D10A0D-CB09-419B-B7AF-F4B9EAB5B868.jpg`

adding file:// in front of it doesn't work. What can I do?
