### ISSUE TITLE
EISDIR error when using TypeScript

### ISSUE THREAD

**Issue by janaagaard75** [expo/expo#428]
After upgrading to version 19 I get the error `[exp] EISDIR: illegal operation on a directory, read` when running `exp start`. I use [react-native-typescript-transformer](https://github.com/ds300/react-native-typescript-transformer) to compile the TypeScript, and have set up a minimal project showing the error: https://github.com/janaagaard75/expo-19-typescript. It works fine with version 18.

I am not sure where this issue belongs, since the error message isn't very informative about what cause the error, so apologies in advance if this is completely unrelated to Expo.

**Comment by ide** [comment]
The packager (Metro Bundler) has been changing a lot, especially between SDK 17, 18, and 19 and the next few SDKs as well. I bet some change in the packager caused this to break and would recommend looking under `node_modules/metro-bundler` to start.

**Comment by Deco** [comment]
I think I've found a workaround, put `/index.js` at the end of `packagerOpts.transformer` in `app.json`.

```json
    "packagerOpts": {
      // ...
      "sourceExts": ["ts", "tsx"],
      "transformer": "node_modules/react-native-typescript-transformer/index.js",
    },
```

But I'm still having a lot of trouble getting Typescript and Expo working together.

**Comment by janaagaard75** [comment]
Thanks a lot, @Deco. That seems to do the trick, and https://github.com/janaagaard75/expo-19-typescript is now up a running, where I combine React Native, Expo and TypeScript.

**Comment by Deco** [comment]
@janaagaard75 Does your setup support live or hot reloading? I can't seem to get either working when using TypeScript.

**Comment by janaagaard75** [comment]
@Deco. Live reloading and debugging of TypeScript (both ts and tsx) files in Chrome works. I don't think hot reloading works, though.
