### ISSUE TITLE
publish without login when expo detached(ejected)

### ISSUE THREAD

**Issue by vvtop** [expo/expo#4285]
Detached expo app must run `expo publish` before building standalone app then able to run `expo export`. 

But `expo publish` asking user login, its not necessary to publish js bundle to expo when user just wanna release it for [Hosting An App on Your Servers](https://docs.expo.io/versions/v32.0.0/distribution/hosting-your-app/). Is there any way to skip login expo platform's distributing service? or still fulfill js bundle self-hosting without publishing it?

See more: [Hosting An App on Your Servers](https://docs.expo.io/versions/v32.0.0/distribution/hosting-your-app/)

**Comment by AdamJNavarro** [comment]
Hey @vvtop,

Would you mind making a [forum post](https://forums.expo.io/) for this? We reserve Github Issues for bugs and prefer to direct questions of this nature to our forums!

Thanks,
Adam
