### ISSUE TITLE
[Android][expo-permissions]  No ability to distinguish when a user has denied access with "Don't ask again" check

### ISSUE THREAD

**Issue by retyui** [expo/expo#4289]
### Expected Behavior
I can get a specific status when user press deny with 'don't ask again', like `react-native` Permissions API:
```js
import { PermissionsAndroid, Platform } from 'react-native';

PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN;
```

### Actual Behavior
When user press `"DENY"`, no matter the checkbox `"Don't ask again"` was set to the truth

We get the same result:
```js
{
   expires:"never"
   status:"denied"
}
```
### Reproducible Demo
```js
// @flow
import {
  CAMERA,
  askAsync,
} from 'expo-permissions';

askAsync(CAMERA).then(result => {
	// ...
})
```

**Comment by AdamJNavarro** [comment]
Hey @retyui,

Your repro demo is incomplete. Could you provide a complete one so we can investigate?

Cheers,
Adam

**Comment by retyui** [comment]
@AdamJNavarro
What exactly do you need ?

**Comment by tsapeta** [comment]
@AdamJNavarro @retyui 
I think repro is not needed here - it's more like a feature request than a bug 😉 Assigned to @bbarthec who is an owner of that module.

**Comment by vanurox** [comment]
Hey @retyui,

I have been facing the same issue. How did you manage this use case ? I mean what should I show to the user in case he/she has checked the Don't ask again checkbox and I am not able to know the detail of denied request.

**Comment by retyui** [comment]
It is a popular case , try deny permission in some applications snap chat, Instagram

And do something like that

**Comment by vanurox** [comment]
@reyui thank you (Y)

**Comment by cmacdonnacha** [comment]
Hey just wondering which SDK this will be in?
