### ISSUE TITLE
Android camera unexpected error

### ISSUE THREAD

**Issue by stochris** [expo/expo#429]
When trying to take a photo on certain android phones, the camera throws an unexpected error on the native thread.

Looking at the logs, the following error is thrown:
`E/AndroidRuntime(11163): java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{436d00a8 11163:com.google.android.GoogleCamera/u0a43} (pid=11163, uid=10043) that is not exported from uid 10077`

SDK version is 18.0.6 ( also tested inside the expo client using 19.0.1, without any luck )
Android version is 4.4
Phone model is Nexus 5

We tested the miminum android version shown in the play store after uploading the final apk ( API level 19+ )

**Comment by ide** [comment]
Looks like this might be a common issue we can resolve on the native side of Expo: https://medium.com/@a1cooke/using-v4-support-library-fileprovider-and-camera-intent-a45f76879d61

**Comment by stochris** [comment]
In the meantime, is there anyway to upgrade the minimum api version of the generated apk ?

**Comment by stochris** [comment]
Any pottential fixes for this ?

**Comment by jesseruder** [comment]
Will be available in the next release!
