### ISSUE TITLE
[docs] You are recommending Stephen Grider React Native courses at Udemy but they are very outdated

### ISSUE THREAD

**Issue by dinobu** [expo/expo#4292]
You are recommending Stephen Grider's classes at Udemy for React Native but these are very outdated and irrelevant today.  Worse, the author is not replying at all to questions nor user requests to update the course.  Please remove this reference or provide references to up to date courses/materials.

**Comment by AdamJNavarro** [comment]
Hey @dinobu,

Thanks for bringing this to our attention. I took a look at the reviews for the course and it seems most people had the same feedback. Just pushed a commit that removed references to the course.

Cheers,
Adam

**Comment by dinobu** [comment]
> Hey @dinobu,
> 
> Thanks for bringing this to our attention. I took a look at the reviews for the course and it seems most people had the same feedback. Just pushed a commit that removed references to the course.
> 
> Cheers,
> Adam

Thanks.  It is unfortunate because I personally loved Stephen's classes.  Even both them both and finished one cpl of years ago.  The Advanced class he provided was great, too.  However, I looked back and it is outdated from the very beginning.  Me and number of people tried contacting him to shed some lights but there is no replies for about a year now :(
