### ISSUE TITLE
Combine Document picker and Image picker

### ISSUE THREAD

**Issue by siddhantbenadikar** [expo/expo#4294]
Can we have a component that will combine the functionality of a document picker and image picker. Something similar to file picker, where we can get options on what is the source of the image/document.

**Comment by cruzach** [comment]
Hi @siddhantbenadikar, would the [Filesystem](https://docs.expo.io/versions/latest/sdk/filesystem/) API fit what you're looking for?

-Charlie

**Comment by siddhantbenadikar** [comment]
The Filesystem api let's me do a lot but I would like something that would call the systems UI for selecting files from Browse.. or images from Gallery. Chrome supports this on <input /> fields.
<img width="361" alt="Screen Shot 2019-05-23 at 8 53 32 PM" src="https://user-images.githubusercontent.com/24991867/58295362-deedb000-7d9c-11e9-833d-075559ad7977.png">

**Comment by cruzach** [comment]
Ah okay, gotchya. 

Best place for this then would be our [Feature Requests page](https://expo.canny.io/feature-requests)! Then, if it picks up some traction, we can make plans for it 😄
