### ISSUE TITLE
Using Expo bare workflow and writing Jest test for a single module

### ISSUE THREAD

**Issue by kayciwang-okta** [expo/expo#4298]
Hi, 

I'm currently switching a SDK from Expo managed workflow to Expo bare workflow. I'm currently modifying my test and I was wondering what is the correct way to mock a single Expo module.

I'm using three libraries from Expo: expo-constants, expo-secure-store and expo-web-browser. Before switching the workflow I was using the code below to mock the modules.

```
jest.mock('expo', () => {
  const Constants = {};
  Object.defineProperty(Constants, 'platform', { get: jest.fn() });
  return {
    SecureStore: {
      getItemAsync: jest.fn(),
      setItemAsync: jest.fn(),
      deleteItemAsync: jest.fn()
    },
    WebBrowser: {
      openAuthSessionAsync: jest.fn()
    },
    Constants
  };
});
```

After switching to Expo bare workflow, and importing the libraries individually as such: 
```
import * as SecureStore from 'expo-secure-store';
import Constants from 'expo-constants';
import * as WebBrowser from 'expo-web-browser';
```

I would still like to mock them. I was doing 
```
jest.mock('expo-constants', () => {
  const Constants = {};
  Object.defineProperty(Constants, 'platform', { get: jest.fn() });
  return {
    Constants
  };
});
```
for each individual module, but seems like when I'm setting my mocks like this: 
```
Object.getOwnPropertyDescriptor(Constants, 'platform').get.mockReturnValue({
    ios: {
      platform: 'ios-platform'
    },
    android: {
      versionCode: 'android-platform'
    }
  });
```
It seems like Object.getOwnPropertyDescriptor(Constants, 'platform') isn't defined. What is the correct way to mock these modules?

Thank you so much for the help!

**Comment by ide** [comment]
We set up a mock file like this:
```
/**
 * A mock of the Constants module with extra fields specified to simulate a project in development.
 * Use it by importing and returning it from a `jest.mock` call explicitly.
 */

const Constants = jest.requireActual('expo-constants').default;

const MockConstants = Object.create(Constants);
MockConstants.manifest = {
  ...Constants.manifest,
  developer: {
    projectRoot: '/home/test/project',
  },
  logUrl: 'https://localhost:19001/logs',
  // put whatever here
};

module.exports = MockConstants;
```

I wouldn't say this is the "correct way" but it is a way. If you want to mock Constants differently, I'd recommend stepping through Jest with a debugger and seeing what is going on.
