### ISSUE TITLE
Standalone app takes too long on splash screen

### ISSUE THREAD

**Issue by michaelVictoriaDev** [expo/expo#4299]
Is there a way you can handle the time when the splash screen is appear ? or possible to handle when the app is minimize it will not loading the splash screen (I replicate this bug on Marshmallow and Nougat Android )

**Comment by cruzach** [comment]
Hey @bazhukov,

I'm sure exactly what you're asking, and for bug reports we really need you to follow the template we've provided, so I'm going to close this for now. If you've encountered a bug, I will definitely re-open once we have the necessary info to troubleshoot!

Note: If this is just a general How-To question, I suggest posting on our [Forums](forums.expo.io)

Thanks!
Charlie
