### ISSUE TITLE
why MapView is showing apple map instead of google map?

### ISSUE THREAD

**Issue by craigcosmo** [expo/expo#4303]
```js

import React from 'react';
import {MapView} from 'expo'

export default class Map extends React.Component {
	state = {
		region: {
			latitude: 37.78825,
			longitude: -122.4324,
			latitudeDelta: 0.0922,
			longitudeDelta: 0.0421,
		}
	}
	render() {
		return(
				<View>
					<MapView 
					initialRegion={this.state.region} 
					showCompass={true} 
					rotateEnabled={false}
					showUserLocation={true} 
					style={css.map} />
				</View>
		)
	}
}

```

I use the sample code on expo doc. I got this apple map.  was expecting google map, what am I missing?

<img width="167" alt="Screen Shot 2019-05-24 at 9 03 35 PM" src="https://user-images.githubusercontent.com/538657/58334044-ed090280-7e68-11e9-95e8-bd3b7378c664.png">

**Comment by craigcosmo** [comment]
I found out. I need this prop in mapview component `provider={MapView.PROVIDER_GOOGLE}`

Why is this not in the expo document?

**Comment by brentvatne** [comment]
in the expo documentation we say:

> See full documentation at [react-community/react-native-maps](https://github.com/react-native-community/react-native-maps).

if you go read the documentation there you can find the `provider` option
