### ISSUE TITLE
[android] Signing in with Facebook login seems not to work

### ISSUE THREAD

**Issue by ide** [expo/expo#4306]
> maybe because of the old `facebook-android-sdk` dependency which is on 4.39.0 and latest is 5.0.1

**Comment by sjchmiela** [comment]
ID of the test application provided to `loginAsync` wasn't connected to the user's account. In production everything should work, upgrading the dependency nonetheless.

**Comment by sjchmiela** [comment]
Closed by https://github.com/expo/expo/commit/910773f49dce5fbdbff79360eddecc03e9a490af
