### ISSUE TITLE
Verify on Android whether "mediaTypes" is ignored when launching a camera instead of library picker

### ISSUE THREAD

**Issue by ide** [expo/expo#4310]
> We have _Take photo_/_Take video_ in ImagePicker examples in NCL, but looks like setting `mediaTypes` up on iOS was intentionally skipped when launching a camera instead of the image library picker. Such option is also not documented for `launchCameraAsync`.

**Comment by esamelson** [comment]
fixed by https://github.com/expo/expo/commit/bda6ee9a01fbc348bdc89bc78a77718d297b5e6e for iOS but we need to verify it works on Android and add docs

**Comment by sjchmiela** [comment]
Android can't handle `launchCameraAsync` accepting videos (images are hardcoded), documentation doesn't mention `mediaTypes` for `launchCameraAsync`, so for now it's ok.
