### ISSUE TITLE
orientation is not locked during app's initial startup

### ISSUE THREAD

**Issue by 3p3r** [expo/expo#4316]
### Environment

```
  Expo CLI 2.17.3 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.5.1 - /usr/bin/zsh
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.3.2 
    npmGlobalPackages:
      expo-cli: 2.17.3
```

### Steps to Reproduce

Lock an app's orientation in `app.json` as [documented here](https://docs.expo.io/versions/latest/workflow/configuration/#orientation). Rotate the phone in the opposite orientation you had set in `app.json`. You can see that the orientation is changed to whatever orientation the phone is in and then quickly resets when app launches. This messes up all font sizes and view sizes in app.

### Expected Behavior

Orientation should remain locked even during startup (splash screen).

### Actual Behavior

Orientation is whatever the phone's orientation is in during startup and then resets once splash screen is gone and app is loaded.

**Comment by abhip10** [comment]
having the same issue

**Comment by brentvatne** [comment]
can someone record a video of this? i'm not sure how to reproduce

**Comment by abhip10** [comment]
In this recording, the app should be opening portrait. However, it only switches to portrait after the app loads, which causes bugs in the UI (look at the list, which is too long for the screen. When opened normally, there are no bugs)

https://streamable.com/90oqp

**Comment by JustynaKK** [comment]
I have the same issue, it looks exactly as on video from _abhip10_

**Comment by jaulz** [comment]
Same here... is it maybe related to the iPad?

**Comment by abhip10** [comment]
> Same here... is it maybe related to the iPad?

+1

For me, it only happens when i test on ipads

**Comment by JustynaKK** [comment]
I also reproduced it on iphone's but only when the system option of locking ios was not turned on.
