### ISSUE TITLE
StoreReview supported for an Expo ejected app in React Native?

### ISSUE THREAD

**Issue by spaul03** [expo/expo#4317]
Is StoreReview supported for an Expo ejected app in React Native?
Using Expo version 27.0.0 and getting below error on import

<img width="461" alt="undefined_Store" src="https://user-images.githubusercontent.com/23045979/58402422-e6070d80-807d-11e9-9b26-b27331f927ae.png">

**Comment by AdamJNavarro** [comment]
Hey @spaul03,

The `StoreReview` module was added in SDK28. You'll have to upgrade to 28+ to make use of it.

Cheers,
Adam
