### ISSUE TITLE
watchPositionAsync constantly increase returned value

### ISSUE THREAD

**Issue by mikhpush** [expo/expo#4322]
### crna

in debugger console.log of lat / long
distance = 59.9383587 30.3880393
3RemoteConsole.js:80 distance = 59.9383586 30.3880394
6RemoteConsole.js:80 distance = 59.9383585 30.3880394
RemoteConsole.js:80 distance = 59.9383586 30.3880393
RemoteConsole.js:80 distance = 59.9383585 30.3880393
RemoteConsole.js:80 distance = 59.9383586 30.3880393
3RemoteConsole.js:80 distance = 59.9383585 30.3880393
2RemoteConsole.js:80 distance = 59.9383585 30.3880392
RemoteConsole.js:80 distance = 59.9383584 30.3880392
RemoteConsole.js:80 distance = 59.9383585 30.3880392
3RemoteConsole.js:80 distance = 59.9383584 30.3880391
6RemoteConsole.js:80 distance = 59.9383584 30.388039
3RemoteConsole.js:80 distance = 59.9383584 30.3880389
3RemoteConsole.js:80 distance = 59.9383583 30.3880389
2RemoteConsole.js:80 distance = 59.9383583 30.3880388
console.warn @ YellowBox.js:67
(anonymous) @ debuggerWorker.js:25
(anonymous) @ debuggerWorker.js:53
RemoteConsole.js:80 distance = 59.9383583 30.3880388
11RemoteConsole.js:80 distance = 59.9383582 30.3880387
3RemoteConsole.js:80 distance = 59.9383581 30.3880387
RemoteConsole.js:80 distance = 59.938358 30.3880387
2RemoteConsole.js:80 distance = 59.938358 30.3880386
RemoteConsole.js:80 distance = 59.9383579 30.3880386
4RemoteConsole.js:80 distance = 59.9383579 30.3880387
3RemoteConsole.js:80 distance = 59.9383579 30.3880386
5RemoteConsole.js:80 distance = 59.938358 30.3880386
2RemoteConsole.js:80 distance = 59.938358 30.3880385
2RemoteConsole.js:80 distance = 59.9383579 30.3880385
4RemoteConsole.js:80 distance = 59.9383579 30.3880384

Android 6.0

### Steps to Reproduce
watchPositionAsync({accuracy: 6, timeInterval: 100}, (it) => console.log(it)

### Expected Behavior
for some reasons, if i use getCurrentPositionAsync({accuracy: 6}) func with setInterval of 100ms, it works fine. I m getting the same values within accuracy range.

### Reproducible Demo
https://snack.expo.io/Bye3ljFp4

**Comment by tsapeta** [comment]
I think these differences between consecutive results are still acceptable and they are within the limits of measurement error. It also cannot be fixed by us, as we're just passing the values we got from the device 🤷‍♂
