### ISSUE TITLE
Cannot get push notification icon and sound to work on Android.

### ISSUE THREAD

**Issue by spyshower** [expo/expo#4323]
### Environment

Expo CLI 2.18.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.6 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.18.3

### Expected Behavior

I thought it would work..

### Actual Behavior

I see this:

![61403085_2229903257130720_6804094165350088704_n](https://user-images.githubusercontent.com/7046283/58442066-2f904080-80f0-11e9-8b45-2f99821a6ffa.png)

and there is no sound or popup (I have to manually open the status bar to see it).

Note that the picture shows how it looks using the Expo client, but it also looks the same in a standalone app. Earlier I tweaked some fields and I got it to show 'Expo' for title, while using the Expo's logo instead of the purple box in the image. But not the correct one and never playing a sound.

Server code:

```

let data = {

    sender: mainUserId,
    dateId: extraArgs.dateId,
    type: type,
  }

messages.push({
    to: otherUser.expoPushToken,
    sound: 'default',
    body: 'some body',
    data: data,
    channelId: 'loox-messages',
    badge: 1,
    priority: 'high',
  })

  let chunks = expo.chunkPushNotifications(messages);

  (async () => {
    for (let chunk of chunks) {
      try {
        let receipts = await expo.sendPushNotificationsAsync(chunk);
        console.log("receipts: ");
        console.log(receipts)
      } catch (error) {
        console.error("error sendPushNotificationsAsync: " + error);
      }
    }
  })();
```

Client code:

```
if (Platform.OS === 'android') {
      Notifications.createChannelAndroidAsync('loox-messages', {
        name: 'Loox messages',
        sound: true,
        priority: 'high', // was max
        vibrate: [0, 250, 250, 250],
      });
    }
```

My app.json is this:
```
{
  "expo": {
    "name": "Loox",
    "icon": "./assets/icons/app_icon.png",
    "description": "Dating app",
    "version": "0.5.11",
    "slug": "looxapp",
    "primaryColor": "#a649f2",
    "orientation": "portrait",
    "notification": {
      "icon": "./assets/icons/test.png",
      "color": "#a649f2",
    },
    "splash": {
      "backgroundColor": "#a649f2",
      "image": "./assets/splash/splash.png",
      "resizeMode": "contain",
    },
    "ios": {
      "bundleIdentifier": "com.app.loox",
      "buildNumber": "0.5.11",
      "supportsTablet": true
    },
    "android": {
      "versionCode": 11,

      "package": "com.app.loox",
      "googleServicesFile": "./google-services.json",

      "permissions": [
        "CAMERA",
        "RECORD_AUDIO",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION"
      ],
    },
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#a649f2"
    },
    "sdkVersion": "32.0.0",
    "facebookScheme": "fb20759449098030294",
    "facebookAppId": "20759419098002594",
    "facebookDisplayName": "Loox",
    "assetBundlePatterns": [
      "**/*"
    ],
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "loox",
            "project": "loox",
            "authToken": "xxx"
          }
        }
      ]
    }
  }
}

```

I have also used `expo build:android` so that's not the problem. iOS sound and icon work fine. I kindly request some help here, I plan to release my app this week.

**Comment by BillyFigueroa** [comment]
I have been struggling with this too. I got the heads up notifications to show up and vibrate but the sound does not work. Have you looked into the new channel requirements for notification after Android Oreo?

**Comment by qalqi** [comment]
+1

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. Questions like this about how to get push notifications working are better asked on our [forums](https://forums.expo.io), and you can also search around there to see if other people have the same problem. Please create a new issue here if you run into reproducible bugs with the provided APIs. Thanks!
