### ISSUE TITLE
Expo@33 for Web incompatible with react-navigation (due to react-gesture-handler)

### ISSUE THREAD

**Issue by brookemitchell** [expo/expo#4339]
I get an error from gesture-handler as shown in this minimal example https://github.com/brookemitchell/expo-react-navigation-web-example 

iIn one (largish) project I was able to get  expo@33.0.0-alpha.web.1 running with react-navigation.  ( and no versions later that that 🤷‍♀ )

Have also tried switching react-navigation to `react-navigation@3.5.0-alpha.0`

ps: keep up the good work, expo for web is the most incredible thing ever!

**Comment by EvanBacon** [comment]
Related: https://github.com/kmagiera/react-native-gesture-handler/pull/617

**Comment by brentvatne** [comment]
for now you can add yarn resolutions for react-native-gesture-handler to lock it to 1.2.1
