### ISSUE TITLE
console.logging 22MB fails (loading large json file)

### ISSUE THREAD

**Issue by lukeberry99** [expo/expo#4340]
Hi,

I'm loading a large json file using the file system api (22mb), when I go to read it I get a `PayloadTooLarge` error, what am I doing wrong?

```
let {uri} = await DocumentPicker.getDocumentAsync()
let content  = FileSystem.readAsStringAsync(uri)
console.log(content)
```

`PayloadTooLargeError: request entity too large` is the error I receive

Any ideas? Thanks

**Comment by sjchmiela** [comment]
Maximum log string size receivable by Expo server (the thing you start with `expo start` which also receives and prints logs) is capped at under 10 MB (I think), so when you try to log an even bigger string it's just too large. 🙂

**Comment by moxorama** [comment]
This is about `console.log`,  you can log smaller parts of `content`.

**Comment by ide** [comment]
Probably the prudent thing to do is to truncate each log entry sent to Expo CLI at ~10KiB or so.

**Comment by tsapeta** [comment]
I believe #4419 solved this issue so I'm closing it 🙂
