### ISSUE TITLE
Installing expo-av on bare minimum project, breaks the build.

### ISSUE THREAD

**Issue by omerman** [expo/expo#4343]
Not sure where exactly is the bug.
but here are the steps I took:

1. `yarn global add expo-cli`
2. `expo init --template bare-minimum`
3. open project folder.
4. `cd ios; pod install;`
5. `yarn ios` 

---- Up until here everything seems to work as expected. ----

6.  `yarn add expo-av`
7. again, `pod install`
8. yarn ios - build fails.

![image](https://user-images.githubusercontent.com/6780529/58619409-8acb5a00-82cd-11e9-8231-12e65c73b4e0.png)

![image](https://user-images.githubusercontent.com/6780529/58619364-71c2a900-82cd-11e9-91c8-e0fb91903cff.png)

Help?

**Comment by sjchmiela** [comment]
Could you try upgrading `react-native-unimodules` to `^0.4.0`, reinstalling the pods, removing `andExperience:nil` from `EXAppDelegate.m` and rebuilding?

**Comment by omerman** [comment]
Worked!! 
Thank you kind sir!
