### ISSUE TITLE
TypeError: "exports" is read-only

### ISSUE THREAD

**Issue by ghmeec** [expo/expo#4359]
../../../../../../../../../Desktop/workspace/expo-web/uqs/node_modules/react-native-gesture-handler/GestureHandler.js/<
C:/Users/Administrator/Desktop/workspace/expo-web/uqs/node_modules/react-native-gesture-handler/GestureHandler.js:636

  633 |   gestureHandlerRootHOC,
  634 |   PureNativeButton: GestureHandlerButton,
  635 |   Directions,
> 636 |   createNativeWrapper,
  637 | };
  638 | 
when running "npm start web" with sdk 33, i  get this error,

../../../../../../../../../Desktop/workspace/expo-web/uqs/node_modules/react-native-gesture-handler/GestureHandler.js
http://192.168.43.201:19006/static/js/bundle.js:72048:30
__webpack_require__
C:/Users/Administrator/Desktop/workspace/expo-web/uqs/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;
.....
help!

**Comment by brentvatne** [comment]
if you create a new project *or* clear your node_modules / yarn.lock / package-lock.json and reinstall it should be resolved
