### ISSUE TITLE
[ expo-camera ]: TS 3.5.1 - JSX element type 'Camera' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by methodbox** [expo/expo#4366]
### Environment
```
Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.17 => 16.8.17 
      @types/react-native: ^0.57.57 => 0.57.57 
      expo: ^32.0.0 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.17.1
```

Environment really has nothing to do with this - the type definitions are hosed.

### Steps to Reproduce

NOTE: This issue occurs specifically when the `tsconfig` target is `es6` or `esnext`.
Your type definitions for the `Camera` module seem to be missing something that has to do with the props, beyond that I'm not clear what's causing this. It doesn't even look like you're using TypeScript, but instead PropTypes (they are not the same thing and the syntax is not directly compatible). 

There also isn't a valid `tsconfig` in the module - look here for an example to compare: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/tsconfig.json - there's no definition of anything I'd expect to see in a `tsconfig` which again leads me to wonder how this was tested.

This is the `tsconfig` found in `expo-camera`:

```json
{
  "extends": "expo-module-scripts/tsconfig.base",  // Throws error: File 'expo-module-scripts/tsconfig.base' not found.
  "compilerOptions": {
    "outDir": "./build"
  },
  "include": ["./src"],
  "exclude": ["**/__mocks__/*", "**/__tests__/*"]
}
```
There also isn't an `index.d.ts` in the module directory for `expo-camera`. Installing `@types/expo` doesn't resolve this. There doesn't appear to be another source for type definitions for this module.

My guess is the types are not exported correctly (resulting in the compiler being unable to find the type definitions) and there is a constructor function missing somewhere in the type definition. I would also suspect that whoever is writing the types is testing them with PropTypes, but not TypeScript since it's not even a dependency, though it exists in VS Code, but only version 3.4.5, 3.5.1 is the latest.

You can easily repeat the behavior by simply using your own default example here: https://docs.expo.io/versions/latest/sdk/camera/ in a TypeScript enabled project. I initially thought this problem was something in my own camera project, but creating a new project and wiping all the code and replacing with yours causes the same error.

This is the exact error seen:

```ts
(alias) class Camera
import Camera
JSX element type 'Camera' is not a constructor function for JSX elements.
  Type 'Camera' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.ts(2605)
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
```

### Expected Behavior

The provided type definitions should be sufficient, at the very least, to use the `<Camera />` component without type errors, when referencing the most basic example.

### Actual Behavior
Type error suggesting types are incorrectly defined or possibly just written wrong.

### Reproducible Demo
Already gave an example of this.

**Comment by bbarthec** [comment]
@methodbox, I've just created blank expo project, added TypeScript 4.5.1 and used code from docs for sample camera screen. I haven't observed the issue you're describing. Would you mind proving some info what kind of flow you're following ([Expo flows](https://docs.expo.io/versions/v32.0.0/introduction/managed-vs-bare/)) or how you've achieved the state you're describing? 

Regarding your suggestions about TypeScript, we're not maintaining types for `expo` package in `DefinitelyTyped` repository, but we're gradually introducing TypeScript into our own codebase. `tsconfig.json` is in correct shape (it's only used for developing each module, not using it) and you should not worry about it. You can observe that `expo-camera` package has it's own types located in `build` directory as stated in it's `package.json` under `types` key. I recommend importing `expo-camera` like this `import * as Camera from 'expo-camera'` ([see here](https://docs.expo.io/versions/latest/sdk/camera/#api)).

**Comment by methodbox** [comment]
> @methodbox, I've just created blank expo project, added TypeScript 4.5.1 and used code from docs for sample camera screen. I haven't observed the issue you're describing. Would you mind proving some info what kind of flow you're following ([Expo flows](https://docs.expo.io/versions/v32.0.0/introduction/managed-vs-bare/)) or how you've achieved the state you're describing?
> 
> Regarding your suggestions about TypeScript, we're not maintaining types for `expo` package in `DefinitelyTyped` repository, but we're gradually introducing TypeScript into our own codebase. `tsconfig.json` is in correct shape (it's only used for developing each module, not using it) and you should not worry about it. You can observe that `expo-camera` package has it's own types located in `build` directory as stated in it's `package.json` under `types` key. I recommend importing `expo-camera` like this `import * as Camera from 'expo-camera'` ([see here](https://docs.expo.io/versions/latest/sdk/camera/#api)).

Are you saying you guys changed the method of import in the middle of a major version? It doesn't fix the issue, but that makes me question your thinking if this has changed.

**Comment by methodbox** [comment]
It looks like this was some kind of weird conflict with something (unknown at this time) in the node_modules folder. I removed it and the package-lock.json and reinstalled and it seems to have cleared the issue.
