### ISSUE TITLE
addContactAsync doesn't set contact image on iOS.

### ISSUE THREAD

**Issue by hashamali** [expo/expo#4369]
### Environment
```
  Expo CLI 2.16.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 2.3 AI-162.3764568
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.7.18 => 16.7.18
      @types/react-native: 0.57.23 => 0.57.23
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: 3.0.8 => 3.0.8
    npmGlobalPackages:
      expo-cli: 2.6.5
```

Build to iOS.

### Steps to Reproduce

Create a new contact using `addContactAsync`. Provide an image via the `RawImage` field. Check to see that contact is created, but image is not set.
 
```
const containerId = await Contacts.getDefaultContainerIdAsync();
const contact = await Contacts.addContactAsync({
    [Contacts.Fields.FirstName]: 'Test',
    [Contacts.Fields.LastName]: 'McTest',
    [Contacts.Fields.PhoneNumbers]: [
        {
            number: '(123) 456-7890',
            isPrimary: true,
            digits: '1234567890',
            countryCode: 'us',
            id: '1',
            label: 'main',
        },
    ],
    [Contacts.Fields.Emails]: [
        {
            email: 'test@gmail.com',
            isPrimary: true,
            id: '2',
            label: 'main',
        },
    ],
    [Contacts.Fields.RawImage]: image,
}, containerId);
```

### Expected Behavior

Expect the contact image to be set.

### Actual Behavior

Contact image is not set. But contact is created successfully.

### Reproducible Demo

See the code above. Can't seem to make a snack as the Contacts API doesn't seem to work in that demo.

**Comment by Matt-Swingvy** [comment]
Hi @tsapeta , did you find a way to solve this issue ?

I ran into it as well. 
I try setting `Contacts.Fields.ImageAvailable]: true,` but it didn't help.
I tried changing from `RowImage` to `Image` and even thought the contact is still created successfully , it throw the following error:

```
The callback callMethod() exists in module NativeUnimoduleProxy, but only one callback may be registered to a function in a native module.
```

I am planning to build a standalone app to see if the problem persisit or only due to `expo app`

**Comment by Matt-Swingvy** [comment]
I tried building a standalone app and I do get the same results contact is created successfully but  without the image.

I am not sure what to try anymore any ideas @tsapeta ? I don't see any valuable error message :(

**Comment by buhny** [comment]
I'm running into this issue too.

**Comment by fkjohn** [comment]
After I had the same issue I looked into the Expo source code and figured out how it works. 
Here is a code snippet for adding a contact with an image from the camera roll:

```
    const pickerResult = await ImagePicker.launchImageLibraryAsync();
    const contact = {
      [Contacts.Fields.FirstName]: "Tester",
      [Contacts.Fields.Image]: {
        uri: pickerResult.uri
      },
      [Contacts.Fields.ImageAvailable]: true,

    };
     await Contacts.addContactAsync(contact);
```

**Comment by dsokal** [comment]
Hi,
As @fkjohn mentioned, if you want to create a contact with an image you should set the `Contact.Fields.Image` property, not `Contact.Fields.RawImage`. The latter is returned when requesting contacts.

This is what just worked for me (the contact image was set):
```
await Contacts.addContactAsync(
  {
    [Contacts.Fields.FirstName]: 'Dominik',
    [Contacts.Fields.LastName]: 'Sokal',
    [Contacts.Fields.ContactType]: Contacts.ContactTypes.Person,
    [Contacts.Fields.Image]: {
      uri: 'image-uri',
    },
  }
);
```
