### ISSUE TITLE
Importing AppAuth from expo not working

### ISSUE THREAD

**Issue by akutamruta** [expo/expo#4370]
## 🐛 Bug Report
I'm using Expo client to build a react native app. I'm using v32.0.13 of @types/expo but still while importing AppAuth from expo I'm getting following error:
Module '"../../../../../../Users/abc/Development/Help/node_modules/@types/expo"' has no exported member 'AppAuth'. [2305]
This issue was marked as resolved in #3520 but I'm still seeing this issue. 
What release of @types/expo has this fixed ?

### Environment

Expo client

### Steps to Reproduce
- Install expo version 32.0.6 and @types/expo as 32.0.13 in Expo client.
- Do import { AppAuth } from 'expo';
- Error mentioned above shows up

**Comment by brentvatne** [comment]
we don't actually provide the @types/expo definition, this is maintained by the community and the appropriate place for an issue for it would be on definitelytyped. when sdk33 is released we will ship our own type definitions directly from the expo package

**Comment by akutamruta** [comment]
Thank you. When will sdk33 be released ?

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/4154

**Comment by brentvatne** [comment]
you can preview it right now if you want https://blog.expo.io/updated-expo-client-available-on-app-store-and-play-store-8747bd3a1364

**Comment by akutamruta** [comment]
Great , thanks for the info :)
