### ISSUE TITLE
useScreens causes white screen on latest expo client (iOS)

### ISSUE THREAD

**Issue by bmanturner** [expo/expo#4371]
I updated to the latest expo client on my iPhone Xs and my app loaded to a white screen. I had to comment out `useScreens()` at the top of my `App.js` to get it to work again.

**Comment by rpander93** [comment]
Same for me. Removing useScreens() works.

If I remove everything react-navigation related, effectively leaving just one screen available, the "problem" also goes away as in there is not white screen anymore.

**Comment by jtklein** [comment]
Same for me. Thanks for posting this @bmanturner you have just save me a lot of time!

**Comment by nottmey** [comment]
We also noticed this behaviour for our app in development (loaded in the newest version of the expo app `2.11.0`, other devices with the `2.10.0` version of the expo app work fine)
-> `useScreens()` breaks all screens with pictures in them 

Does this also affect current builds for releasing an app update? Did anyone experience issues with publishing or building?

**Comment by tsapeta** [comment]
Hi! I'm sorry for this bug, we've mistakenly backported changes to SDK32. Fix for this already landed on master and I'll submit a new build with this fix to Apple review soon.
