### ISSUE TITLE
[Android] Support for 64-bit builds

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#4374]
Since JSC and react-native just started supporting 64-bit builds, we're ready to do the same in the next release. We have a deadline for that, as of August all new updates in Google Play Store are required to provide 64-bit build versions in addition to 32-bit.

**Comment by jrgonh** [comment]
Hi All, 
Do we know when this version will be released? We are worried about the deadline of August 1st.

**Comment by tsapeta** [comment]
Hi @jrgonh, 
64-bit support is already implemented and merged to the master branch, so it will be a part of SDK34 release which will be out before the deadline. We also plan to push these changes to SDK33 builders as well, this may happen even this week. Stay tuned 😉

**Comment by jrgonh** [comment]
Cool!, Thanks ;)

**Comment by ricardovf** [comment]
Any news on this? Just got a message from Google Play with the August 1 deadline.

Thanks for the work guys, hope we can have this feature by this week.

**Comment by ibogdan94** [comment]
@tsapeta when is sdk 34 release planned?

**Comment by ibogdan94** [comment]
I see, that you add 17 hours ago several commits to sdk33 about the android support 

Thanks 🙏

**Comment by calvinf** [comment]
For status of SDK 34 release follow the issue they pinned: https://github.com/expo/expo/issues/4437

**Comment by alonroth** [comment]
Is it merge to SDK33?

Thanks 🙏

**Comment by tsapeta** [comment]
Hello,
64-bit support has been released to our builders for SDK33, it's there enabled by default. The size of the final APK might be bigger because of this additional architecture, however I recommend to use `-t app-bundle` when running `expo build:android` - this will give you app bundle instead of APK, which contains binaries for each architecture separately so your users after all will be downloading less from the store 😉

**Comment by StevenShadman** [comment]
@tsapeta I've been using an older version of turtle-cli to build my standalone app for android so that I can use branch.io is this going to make it so I can't build a 64 bit version?  What is the recommended way to support Branch and 64-bit on android without ejecting?
Thanks

**Comment by jrgonh** [comment]
@tsapeta I'm seeing that the last version was updated 19 days ago (version 33.0.7)
https://www.npmjs.com/package/expo
Do you say that this version has the changes to support 64-bit 

Thanks in advance

**Comment by AleksandarSavic95** [comment]
Can we make 64-bit buils with `expo-cli v2.21.2`? @tsapeta 
Thank You for all the work and support! 😊

**Comment by oriharel** [comment]
@AleksandarSavic95 - yes. I just did.

**Comment by AleksandarSavic95** [comment]
Thank You for Your reply! 😊I did the same, but forgot to write it here. 😅

**Comment by AryanJ-NYC** [comment]
@StevenShadman Looks like Expo now allows 64-bit builds with Branch support. I'm copying and pasting from my post on https://forums.expo.io/t/update-regarding-64-bit-support-and-branch/25103/35:

> It looks like Expo listened and will (or is making moves to) support Branch with 64-bit builds: https://github.com/expo/expo/issues/5132
> 
> I was able to build a 64-bit Android build complete with Branch using the expo-branch module:
> 
> 1) [Upgrade to SDK 34](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319)
> 2) `npx expo install expo-branch`
> 3) Change the `import { DangerZone } from 'expo'` imports to `import * as Branch from 'expo-branch'`.
> 4) Change all calls to DangerZone.Branch.someFunction() to just Branch.someFunction().
> 5) Use `npx expo build:android` to build.

**Comment by AppleCkp** [comment]
Hi @tsapeta,

I hit this issue at sdk 32, do this issue fix in sdk34?
is that i need to update my expo sdk to 34 version?

Thanks,
Apple

**Comment by tsapeta** [comment]
@AppleCkp yes, SDK34 fully supports 64 bit builds.
