### ISSUE TITLE
Extract OTA updates to unimodule

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#4375]

**Comment by ide** [comment]
The main goal of this task is to support the current OTA system and current feature set with both the managed Expo client and bare workflow. We are not looking to add any new features to this OTA updates module.

**Comment by moxorama** [comment]
It would be amazing cool if this unimodule will have an API for choosing release channel or publishId in API

**Comment by moxorama** [comment]
Is this module will have a possibility to select release channel for updates?

**Comment by zaptrem** [comment]
Does this mean bare workflow users who are using native modules will be able to use Expo OTA updates?

**Comment by ide** [comment]
@zaptrem Yes, that is the plan. We are replacing ExpoKit with the bare workflow and to do that smoothly and maintain feature parity, we are extracting this updates module so that ExpoKit users have a transition path forward.

**Comment by bitlab-code** [comment]
Thanks to work on this.
Are there any realistic chance to see this feature in v36?

**Comment by mczernek** [comment]
This work is focused on pulling this feature off and make it available for bare apps (with unimodules). Hence, it is quite independent from any specific SDK. However, it should land soon after SDK 36 is released.

**Comment by anton-sharpdev** [comment]
Hi, thank you for your job)
I wondering if you have any estimates when you can deliver this feature like separate package.
