### ISSUE TITLE
Extract Notifications to unimodule

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#4376]

**Comment by rikur** [comment]
Looking forward to this, there are no solid notification libraries available for RN.

**Comment by brunolemos** [comment]
Is this a required step to be able to use expo notifications module on a non-expo cross-platform app? Or is it already possible? Currently looking for a solution. cc @EvanBacon

**Comment by superphil0** [comment]
will this be included in sdk36? it has been pushed back 2 versions already? any ETA? Development hasnt even started on this or?

**Comment by evanheckert** [comment]
> Is this a required step to be able to use expo notifications module on a non-expo cross-platform app? Or is it already possible? Currently looking for a solution. cc @EvanBacon

Also curious. Looking to eject for other reasons, but need Expo's notifications functionality. 

Thanks for all your hard work!
