### ISSUE TITLE
Cannot access debug menu on Android detached app

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#439]
## Description
I cannot access the debug menu in ejected app, either by shaking, `adb shell `, or menu button.

## Expected Behavior
Should have been able to access the debug menu to set the options.

What action did you perform, and what did you expect to happen?
1.`exp start`
2. start app
3.Tried 
    1. shaking
    2. `adb shell `
    3. menu button
    
## Observed Behavior
![image](https://user-images.githubusercontent.com/29329325/28679584-425c4a0e-7311-11e7-8298-68f222379aa3.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
*   `:```
weave@0.1.0 /home/harisvsulaiman/work/weave/expo/weave
└── react-native-scripts@1.0.0  extraneous

npm ERR! extraneous: react-native-scripts@1.0.0 /home/harisvsulaiman/work/weave/expo/weave/node_modules/react-native-scripts
```
* `npm ls expo`:
```
weave@0.1.0 /home/harisvsulaiman/work/weave/expo/weave
└── expo@19.0.0 
```
* `node -v`:
```
v8.1.3
```
* `npm -v`:```
4.6.1
```
* `yarn --version`:
```
0.27.5
```
Also specify:

1. Operating system:
Elementary OS Loki
2. Phone/emulator/simulator & version:
Moto e
Lyf Flame 5
Mi Redmi Note

**Comment by tiendv89** [comment]
@brentvatne Hello, I experience the same issue. Why this is closed ?
