### ISSUE TITLE
ExpFileUtils not exposed to JS layer

### ISSUE THREAD

**Issue by jacobsmith** [expo/expo#4390]
### Environment

Target of Android

### Steps to Reproduce

Attempt to call:

```
                IntentLauncherAndroid.startActivityAsync(
                    'android.intent.action.VIEW',
                    null,
                    url
                );
```
where `url` is a `file://` url to a file owned by the Expo FileSystem API.

### Expected Behavior

After getting a handle to a file via the `FileSystem` API, I expect to be able to pass that to another application via the `IntentLauncherAndroid`.

### Actual Behavior

Raises: 
```
 [Unhandled promise rejection: Error: file:///data/user/0/host.exp.exponent/files/ExperienceData/<redacted>.docx exposed beyond app through Intent.getData()]
```

### Reproducible Demo

```
                IntentLauncherAndroid.startActivityAsync(
                    'android.intent.action.VIEW',
                    null,
                    url
                );
```

`ExpFileUtils` contains a `contentUriFromFile` method that should allow for newer android versions to pass a handle to a file. However, it is not exposed to the JS layer, so files on Android cannot be opened outside of the Expo App (or using the MailComposer, which internally uses `ExpFileUtils.contentUriFromFile`.

**Comment by cruzach** [comment]
Hey @jacobsmith, thanks for bringing this up! I've assigned it and we'll get to it (pretty busy this week with the new SDK release coming up). But if you feel comfortable- feel free to submit a PR for this!

**Comment by jacobsmith** [comment]
Sounds good, thanks @cruzach! My Java is fairly rusty, but I may give it a try if I have time. Best of luck with the SDK release! Looking forward to it (:

**Comment by jacobsmith** [comment]
closing due to #4526 merging.
