### ISSUE TITLE
[camera] ref type concerns

### ISSUE THREAD

**Issue by methodbox** [expo/expo#4399]
### Environment

``` 
Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react-native: ^0.57.57 => 0.57.60 
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.17.1
```
### Steps to Reproduce

Because `camera` (lower-case), which refers to the Camera object when it's _instantiated_ is undefined, it's not possible to use the given example in the docs for the `ref` attribute. 

As such, the only work-around I can find (I am open to any better suggestions) is to define `camera` as undefined in my component. This works, but results in *none* of the type definitions from `expo-camera` actually being peekable; they're effectively disassociated which makes using TypeScript with this component pointless (it's quickly becoming infuriating to begin with as the types are arguably poorly done).

This is used in the linked `camerja` from the Expo docs, and it's given as an example in the docs link this:

```js
<Camera ref={ref => { this.camera = ref; }} />
```

There doesn't seem to be a way to reference `Camera`, `CameraObject` or anything else exposed by the types provided which satisfies all use cases of available methods without a type error.

For example, setting the `camera` value (which is automatically inferred to be `CameraScreen.camera`) to anything other than `undefined`, such as `camera = React.createRef<CameraObject>();` will result in a type error using the `getAvailablePictureSizesAsync` method; it will indicate this method doesn't exist.

Setting the `camera` value to `CameraObject` and leaving it undefined seems to solve this issue for all but `getAvailablePictureSizesAsync`, which also causes an issue at runtime.

Setting the value of camera as `camera: any;` resolves the issues functionally but as said before, renders the types useless as they are no longer enforced on any method using this object like `this.camera.methodName`.

### Expected Behavior

Overall it seems bad practice to use an undefined variable for a non-instantiated object as a placeholder for the camera instance, instead I'd expect to be able to use a method to instantiate the camera (the docs don't seem to indicate what this is or how to use it if it exists at all) and assign this to the variable.

In any case, I'd expect the types to be more clearly documented (they aren't documented in comments or the docs at all so it's a matter of looking through the type code to sort it out.

### Actual Behavior

Missing types, type errors, all noted above.

### Reproducible Demo

https://github.com/methodbox/react-native-full-camera

**Comment by methodbox** [comment]
@ide if it's not clear, this issue actually does cause a problem using `Camera` in the documented way when using TypeScript; i.e. it's not possible to use `ref` in this way and get past the TS error without doing something very hacky.

I'm not really clear why something like this is considered ok in the current version and added as a milestone; are bugs not fixed in current versions?

**Comment by methodbox** [comment]
I really hope this isn't a good example of how you guys are testing your TypeScript issues:

https://forums.expo.io/t/expo-has-no-exported-member-storereview/22953

@AdamJNavarro responds to this post with a Snack example in JS, not TS which completely overlooks the actual issue the user is having, which is not unlike my issue here.

I'm wondering if Expo plans on having 1st-class support for TS?

**Comment by ide** [comment]
The TypeScript support is fairly new and obviously there are issues to work through. Some of the sample apps in this repo do use TypeScript as a base litmus test and as time provides, coverage will improve. Firstly, writing the modules in TypeScript is probably the most significant way to give TypeScript first-class support.

I do want to make clear that first-class support doesn't mean a complete absence of bugs or perfection on the first try. Additionally, `@types/react` and `@types/react-native` have their fair share of type bugs and seeing as how several parts of Expo meaningfully depend on them, those bugs will surface their way through to apps.

In the meantime, `// @ts-ignore` is very helpful and I'd recommend it in scenarios when you need to make forward progress. And if time permits, we're open to PRs that are generally applicable and maintainable from people who believe in what we're working on.

**Comment by methodbox** [comment]
> The TypeScript support is fairly new and obviously there are issues to work through. Some of the sample apps in this repo do use TypeScript as a base litmus test and as time provides, coverage will improve. Firstly, writing the modules in TypeScript is probably the most significant way to give TypeScript first-class support.
> 
> I do want to make clear that first-class support doesn't mean a complete absence of bugs or perfection on the first try. Additionally, `@types/react` and `@types/react-native` have their fair share of type bugs and seeing as how several parts of Expo meaningfully depend on them, those bugs will surface their way through to apps.
> 
> In the meantime, `// @ts-ignore` is very helpful and I'd recommend it in scenarios when you need to make forward progress. And if time permits, we're open to PRs that are generally applicable and maintainable from people who believe in what we're working on.

Unfortunately, `// @ts-ignore` doesn't work when the type error is inside the `return` on the component (as in the issue I actually opened this about).

So in this case, it's a breaking bug. It effectively means using TypeScript and `Camera` is a non-starter. There are some work-arounds I've found but that makes it hard to proceed with developing an app that includes the camera, since the core instance of `Camera` using `ref` is bugged; this work-around would need to be incorporated into the app going forward until a fix is rolled out.

If I find an actual solution, I'll be sure to place a PR but in the mean time, do you have any suggestions? Is this planned on being fixed in an upcoming version? (I see the milestone reference but couldn't find something indicating it was included).

**Comment by benhjames** [comment]
I wasn't able to reproduce this in either of the following ways that React supports using refs (in class components, but should be same results with function components/hooks):

```tsx
class MyCamera {
  cameraRef = React.createRef<Camera>();

  takeSnapshot = () => {
    if (this.cameraRef.current) {
      // This is typed correctly
      this.cameraRef.current.takePictureAsync();
    }
  }

  render () {
    return <Camera ref={cameraRef} />
  }
}
```

```tsx
class MyCamera {
  camera: Camera | null = null;

  takeSnapshot = () => {
    if (this.camera) {
      // This is typed correctly
      this.camera.takePictureAsync();
    }
  }

  render () {
    return (
      <Camera ref={(camera) => {
        this.camera = camera
      }} />
    );
  }
}
```

@methodbox let me know if this is still an issue, otherwise I think this can be closed. 👍

**Comment by methodbox** [comment]
@benhjames 
You realize the way that I used was ripped directly from Expo’s own documentation, right?

The conundrum is knowing what to define the Camera object as; in their original example it’s not defined at all, so in Typescript the check fails because it’s not set to something like a null value.

You’re first example is probably the right way to go, so long as the types are still effective and it’s not throwing an error.

At the time I opened this Expo acknowledged this was effectively a bug (in a different issue) and it was related to type definitions - this might be why what you’re doing now works properly.

I appreciate the feedback, but *I would expect someone from the Expo team to clarify exactly how this was resolved* which I’m assuming was part of v33, before actually closing it.

I appreciate the examples and I’ll give them a shot when I have some free time.

That said, it might be worth putting in a PR to update the docs accordingly.

**Comment by MikaelSvanasbakken** [comment]
Late response. Currently facing this issue as well, can't get around it without doing some REAL hacky stuff.

**Comment by Anybowdy** [comment]
I found a working solution: 
First declare a reference to your camera:
` const cameraRef = useRef<Camera | null>();`
Then use the current value of this ref:

```
const takePicture = () => {
    if (cameraRef.current) {
      console.log('camera is set');
    }
  };

<Camera
        ref={(camera) => {
          cameraRef.current = camera;
        }}
        style={styles.camera}
        type={type}
      />
```

**Comment by brentvatne** [comment]
can someone open a pr to expo-camera to change the type to work how you believe it should?

**Comment by yhugow** [comment]
I'm using typescript + expo;
You can try this. Hope it helps Cheerrss :) 

```
import * as React from "react";
import { Text, View, StyleSheet, Image, TouchableOpacity } from "react-native";
import * as Permissions from "expo-permissions";
import { Camera, CameraRecordingOptions } from "expo-camera";
 
type Props = {};
type State = {};

class Camera extends React.Component<Props, State> {
  private camera: Camera;
  constructor(props: Props) {
    super(props);
    this.state = {};
    this.camera = new Camera({});
  }

  askForPermission = async () => {
    const permissionResult = await Permissions.askAsync(Permissions.CAMERA);
    if (permissionResult.status !== "granted") {
      alert("no permissions to access camera!");
      return false;
    }
    return true;
  };

  onPressRecordAsync = async () => {
    const hasPermission = await this.askForPermission();
    if (!hasPermission) {
      return;
    } else {
      const options: CameraRecordingOptions = {
        mute: true,
        maxDuration: 10,
      };
      this.camera.recordAsync(options).catch;
    }
  };

  render() {
    return (
      <View>
        <TouchableOpacity 
          onPress={this.onPressRecordAsync}
        >
          <Text>Record Video</Text>
        </TouchableOpacity>

        <Camera
          ref={(ref: Camera) => {
            this.camera = ref;
          }}
          style={{ height: 300, width: 200 }}
        ></Camera>
      </View>
    );
  }
}

export default Camera;

```

**Comment by The3dgar** [comment]
This temp solution may be usefull for users that use ts with expo

Assuming that you import react, expo-camera, etc...

The any in useRef is for ts complain

```
const cameraRef = useRef<Camera | any>();

const takePhoto = async () => {
    if (!cameraRef) return;
    const camera: Camera = cameraRef.current;
    const photo = await camera.takePictureAsync();
}
.
.
.
return (
<>
   <Camera style={camStyle.camera} ref={cameraRef} />
</>
```
