### ISSUE TITLE
add button to clear cache?

### ISSUE THREAD

**Issue by vesper8** [expo/expo#44]
I made changes to my app. On XDE v14 I hit 'restart', then 'publish'. Then launched Exponent on my physical android phone and loaded up the URL, and it still showed me the old app code.

I had to go under the androids app settings.. scroll down to Exponent.. clear the cache there.. then close and restart the app.. and only then did I see the new changes.

Could we have an easier way of clearing the cache

**Comment by jesseruder** [comment]
Was your app already opened in another task when you loaded the url the first time? It shouldn't use the old code in that case.

If you need to manually refresh you can pull down to see the Exponent notification and click the refresh button there.

**Comment by martinezguillaume** [comment]
Hello, speaking about that notification, it's still there when you build your apk... Look
![image](https://cloud.githubusercontent.com/assets/17292331/23229712/9053c880-f941-11e6-9061-bc0534e14cb4.png)

How can I remove it ?

**Comment by jesseruder** [comment]
https://docs.getexponent.com/versions/v14.0.0/guides/configuration.html#androidHideExponentNotificationInShellApp @martinezguillaume

**Comment by martinezguillaume** [comment]
Gosh... Thanks 💕
