### ISSUE TITLE
"Request to the server was malformed..." when sending Push Notification for Android

### ISSUE THREAD

**Issue by nsainaney** [expo/expo#4401]
### Environment

  Expo CLI 2.18.7 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13
      @types/react: ^16.8.18 => 16.8.19
      @types/react-native: ^0.57.60 => 0.57.60
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.1 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.18.7

### Steps to Reproduce

1. Go to [https://expo.io/dashboard/notifications](https://expo.io/dashboard/notifications)
1. Set up a push notification using token ExponentPushToken[QNh9kEJsH-r3lPzZCRdwi6]
1. Hit 'Send a Notification'

### Expected Behavior

Notification should be successfully send

### Actual Behavior

Error message "Request to the server was malformed or contained invalid parameters shows up"

The same happens in code with no more information on what is malformed. The same message with an iOS token works great.

### Reproducible Demo

The error is easy to reproduce using the Push Notification tool and token ExponentPushToken[QNh9kEJsH-r3lPzZCRdwi6] or ExponentPushToken[3HmR7oNMhVO661P6dU8M-Z]. The former was generated by uninstalling and reinstalling the Expo Client.

**Comment by cruzach** [comment]
Hi @nsainaney! 

Are you able to send the same payload to different Expo push tokens?

**Comment by nsainaney** [comment]
I am. I have an iOS device and the push notification works great. I substitute the iOS ExpoPushToken[xxx] with the one above in the Push Notification tool and it works fine which suggests there's no problem with the payload.

I've tried with and without a channel id as well.

**Comment by cruzach** [comment]
But all Android devices experience this issue? Or only some?

**Comment by nsainaney** [comment]
I only have one device. Am working on securing another device to test. Do you think this could be device related? The error message suggests I have an invalid parameter sent to the Expo backend.

**Comment by cruzach** [comment]
There has been an [instance](https://forums.expo.io/t/push-notification-error-the-request-sent-to-the-server-was-malformed-or-contained-invalid-parameters/20310/3?u=charliecruzan) where this was device related, but I can't be sure- so I just thought I would ask

**Comment by nsainaney** [comment]
Ok. I'm using a Xiaomi Mi Pad 3 so this could be MIUI related if that's the case. I'll test with a Samsung and circle back.

**Comment by cruzach** [comment]
Any updates @nsainaney ? If not, I will probably close this issue soon for inactivity

**Comment by nsainaney** [comment]
The client dropped the need for Android so I've not been able to fully follow through on this.

Thanks for following up and feel free to close the issue.

Happy New Year!

________________________________
