### ISSUE TITLE
[Android] Webview is not scrollable when embed inside a scrollview

### ISSUE THREAD

**Issue by gasolin** [expo/expo#4405]
### Environment

Expo CLI 2.18.7 environment info:
    System:
      OS: Linux 4.15 elementary OS 5.0 Juno
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
    npmPackages:
      expo: 31.0.6 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: 2.18.3 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.18.7

Android and iOS

### Steps to Reproduce

We'll embed tradingview (https://www.tradingview.com/blog/en/adjustable-font-size-on-scales-1603/) as our trading chart, but found `scroll down` is not possible when open the settings menu.

The scroll up/down (y-axis) and wont work in webview because of The Scroll listens only on ScrollView.

By providing a lightweight android wrapper it could be solved https://stackoverflow.com/questions/13257990/android-webview-inside-scrollview-scrolls-only-scrollview

Embed a webview inside a scrollview. 

### Expected Behavior

The scroll up/down in webview works both on iOS and Android

### Actual Behavior

The scroll up/down in webview not works on Android

### Reproducible Demo

https://snack.expo.io/r1E6viX0N

Note when the `height` is large enough to exceed the current screen size, the webpage is not scrollable, when the height is small and within the current screen size, the webpage is scrollable.

**Comment by cruzach** [comment]
Looks like this issue lies with `react-native-webview`, and there's an [issue for it](https://github.com/react-native-community/react-native-webview/issues/22), as well as a [pending PR](https://github.com/react-native-community/react-native-webview/pull/281).
