### ISSUE TITLE
Version of the Expo app is out of date.

### ISSUE THREAD

**Issue by aregos** [expo/expo#4406]
Hello! I have 'This version of the Expo app is out of date. Uninstall the app and run again to upgrade.' problem after installing the last version of expo on my android emulator. And I think because of this expo can't run remote debugger console. Can anyone help me with it?

**Comment by cruzach** [comment]
Could you try following the solution [here](https://stackoverflow.com/questions/54251369/expo-is-out-of-date-uninstall-and-run-again-to-upgrade/54251496) and let me know if the problem persists? 

Side note- this question fits better on our [Forums](https://forums.expo.io/), as Github is reserved for bug reports!
