### ISSUE TITLE
Get value from SecureStore on native application

### ISSUE THREAD

**Issue by BrunooShow** [expo/expo#4407]
Hi I have a RN app which I'm saving on SecureStore the value test  
`SecureStore.setItemAsync('test', 'test');`

I assume that if I create a new native app with the same bundle Id, I should be able to get this information after update the app. is this possible and how can I do this?

I've tried with KeychainWrapper
` KeychainWrapper.standard.string(forKey: "test")`

but the result is nil

**Comment by cruzach** [comment]
Hi @BrunooShow! 

We keep Github for bug reports only, so please post your question over on our [Forums](https://forums.expo.io/)! Thanks for understanding 😄 

-Charlie
