### ISSUE TITLE
Cannot open developer menu in ChromeOS

### ISSUE THREAD

**Issue by jonjlee** [expo/expo#4417]
Is it possible to open the developer menu when running the Expo Android app on a ChromeOS? I am running expo-cli in Termux and I am aBlessings to successfully start my app. However, pressing Ctrl+M does not bring up the developer menu as it usually would in an Android simulator. I don't believe there is a way to simulate shaking the Android device in ChromeOS, and I do not have access to adb.

If it is not possible to open the developer menu, are there other debugging tools available to help when running in ChromeOS?

My Chromebook is running ChromeOS 74.0.3729.159. I am running expo-cli 2.18.4 via Termux. I have the Expo Android app installed, last updated May 31, 2019.

**Comment by cruzach** [comment]
Hey @jonjlee, it doesn't look like Android Studio for Chrome OS supports emulation (yet) according to [this](https://www.aboutchromebooks.com/news/android-studio-chrome-os-chromebook-recommendation-google-io-2019/). 

There is a workaround for reloading (at least)  w/o access to the dev menu shown [here in the docs](https://docs.expo.io/versions/v32.0.0/workflow/up-and-running/#manually-reloading-the-app)
