### ISSUE TITLE
Facebook SDK not working

### ISSUE THREAD

**Issue by nabeel-s** [expo/expo#4421]
I followed instructions to add the Facebook SDK to my app using expo, but the Android app installs are not being detected by Facebook at all.

iOS app installs are being detected correctly. 

https://docs.expo.io/versions/latest/sdk/facebook/

Please let me know how to solve this.

**Comment by cruzach** [comment]
Hey @nabeel-s,

Please follow the issue template, it asks for a lot of the information we need so that it's much easier to identify the problem

-Charlie

**Comment by nabeel-s** [comment]
@cruzach  The Facebook SDK is outdated in expo, can you please update it to the latest version?

****

# Expo CLI 2.14.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617


iOS, Android

**### Steps to Reproduce**

I followed instructions to add the Facebook SDK to my app using expo, but the Android app installs are not being detected by Facebook in the App Ads Helper.

https://developers.facebook.com/tools/app-ads-helper

iOS app installs are being detected correctly.

**### Expected Behavior**

Android app install numbers should be logged in the Facebook account App Ads Helper here:
https://developers.facebook.com/tools/app-ads-helper

**### Actual Behavior**

Android app install numbers are shown as 'Unavailable' in the App Ads Helper. iOS app install numbers are shown correctly.

**Comment by cruzach** [comment]
What SDK are you using? The Android Facebook SDK version being used in the Expo module is 5.0.1, which is current

**Comment by nabeel-s** [comment]
There was previously a warning message in the Facebook app settings page stating that the SDK is outdated, however this seems to be gone now. Can you please test the Facebook SDK in expo to see if this is working for you?

**Comment by nabeel-s** [comment]
I just ejected my app to ExpoKit and checked build.gradle under the 'app' directory, it states under dependencies:

> implementation 'com.facebook.android:facebook-android-sdk:4.37.0'

Version 4.37 of the Facebook SDK is from September 27 2018 and is not current. Are you sure Expo is using the latest SDK?

**Comment by nabeel-s** [comment]
I have just tested this by manually changing the above line to version 5.0.1 and built the release, now Facebook is able to detect the SDK in the apk. This means the SDK version in expo is definitely outdated and is not current. Please update the SDK to the latest version 5.0.1 as soon as possible.

**Comment by nabeel-s** [comment]
On further testing using the Events Manager (https://www.facebook.com/events_manager), it has become clear that the problem with Facebook detecting the SDK is with Expo's build in non-ejected state only. Facebook can detect the SDK built with Android Studio in ejected state using both old and new versions of the SDK. This means there is something wrong with the Facebook SDK being called in builds generated by Expo. Please check this.

**Comment by nabeel-s** [comment]
Is the Facebook SDK actually loaded by the Expo module unless the Facebook Login function is being used?

**Comment by nabeel-s** [comment]
The Facebook SDK needs to run automatically WITHOUT calling the Login function - to detect the number of app installs. Otherwise this is useless to me.

**Comment by jasminecrazy** [comment]
> 
> 
> I have just tested this by manually changing the above line to version 5.0.1 and built the release, now Facebook is able to detect the SDK in the apk. This means the SDK version in expo is definitely outdated and is not current. Please update the SDK to the latest version 5.0.1 as soon as possible.

I met the same problem, I has already updated expo to the latest version, and can see the facebook sdk is now 5.0.1 in gradle file. But still see the warning in facebook and no record for android .
Is there any solution to fix this issue?

**Comment by nabeel-s** [comment]
Jasmine, the only solution I found is to build the apk in ejected state using Android Studio. Using expo to generate the build does not activate the SDK unless using the Login function only.

**Comment by lmuntaner** [comment]
I found a solution in this comment: https://github.com/expo/expo/issues/2079#issuecomment-454266708

**Comment by nabeel-s** [comment]
> I found a solution in this comment: [#2079 (comment)](https://github.com/expo/expo/issues/2079#issuecomment-454266708)
> 
> It seemed to be a problem with the hash created by expo

Are you using Facebook Login function with Expo, or just the Facebook SDK without Login function? Is your app activity detected by the Events Manager (https://www.facebook.com/events_manager) when you build the apk using Expo in unejected state? For me it didn't work even using the solution you linked to.

**Comment by jasminecrazy** [comment]
Hi @nabeel-s  I have ejected expo app and build apk file , Do we need to publish to google play to make it affect. 
:3 'cause nothing change on facebook developer console after I install this apk.

**Comment by nabeel-s** [comment]
> Hi @nabeel-s I have ejected expo app and build apk file , Do we need to publish to google play to make it affect.
> :3 'cause nothing change on facebook developer console after I install this apk.

You need to add the development or release key hashes to the Facebook control panel of your app:

To get development key on Mac:

keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64

To get development key in Windows:

keytool -exportcert -alias androiddebugkey -keystore %HOMEPATH%\.android\debug.keystore | openssl sha1 -binary | openssl base64

There is a similar command to get the release key for release builds.

**Comment by nabeel-s** [comment]
Jasmine, which version of Expo SDK are you using? After updating to the latest SDK 34, I get errors in Android Studio (unrelated to Facebook) when building in ejected state. Now it seems impossible to use the Facebook SDK (without Login function) either in ejected or unejected state. This is very annoying, Expo needs to fix this asap.

**Comment by nabeel-s** [comment]
If Expo does not fix this soon, I will need to consider switching to an alternative react native platform.

**Comment by sjchmiela** [comment]
When it comes to Facebook SDK — we do disable tracking app installs in standalone apps until one triggers the login. I agree this isn't the best possible way, but we haven't had time to fix that yet.

Fortunately, this is the case only for standalone apps! In ejected/bare workflow you are capable of changing nearly every aspect of the configuration! 🎉 With great power comes great responsibility, which is in big part shifted from our side. 😉

If you'd like to track app installs my guess is that you would need to edit your `android/app/src/main/AndroidManifest.xml` and change this line

https://github.com/expo/expo/blob/6334f82adccb529e9347e348c874bd8f6a92cacc/template-files/android/AndroidManifest.xml#L396

so it includes your real application ID from Facebook. ([Step 1.6 of Android Facebook SDK setup instructions](https://developers.facebook.com/docs/app-events/getting-started-app-events-android#1--integrate-the-facebook-sdk-in-your-android-app))

<img width="829" alt="Zrzut ekranu 2019-08-14 o 08 36 47" src="https://user-images.githubusercontent.com/1151041/62999426-a971d380-be6e-11e9-8935-12dfacbbd9ee.png">

(You can also set the value as it is written in the instructions and then also complete step 2 — editing `strings.xml`.)

When it comes to not-Facebook-related errors when building ejected apps — they shouldn't happen and there's not enough detail for me to help and they are out of the scope of this issue. 🙂

**Comment by jasminecrazy** [comment]
Hi @nabeel-s I am using expo version 33. there is no error after I eject app so far. :)
for add debug keystore to facebook console. after adding it to console, nothing change :(( 
Maybe  I have to wait to publish to store

**Comment by nabeel-s** [comment]
@sjchmiela, please try to fix in standalone apps as not everyone needs or wants the Facebook Login function.

I have posted regarding build errors in SDK 34 in the Expo forums: https://forums.expo.io/t/android-build-error-after-updating-to-sdk-34/26398

@jasminecrazy, if you update to SDK 34, please let me know if you're able to build successfully.

**Comment by sjchmiela** [comment]
A little bit teasing you, but please remember that fortunately Expo is an open-source project and we would be glad to review your contributions to features you need! 😜

Speaking seriously, adding support for this feature isn't on SDK35 roadmap, so I won't promise that we will implement it any time soon. Fortunately, there is a workaround! 🙂

**Comment by nabeel-s** [comment]
@sjchmiela, I understand Expo is open source, but it doesn't make sense for Expo to feature Facebook Login without the option to activate a basic tracking of app installs. 

Ejecting appeared to be a workaround, but SDK 34 still seems to have bugs in Android Studio. SDK 34 is required to fulfill the 64-bit requirement of Play Store.

**Comment by nabeel-s** [comment]
Is it possible to add Facebook install tracking to Expo as a paid feature request?

**Comment by jasminecrazy** [comment]
HI @nabeel-s I have upgrade to v34, eject it also, and publish to Google play. There is no error.
But right now the data still not show on Facebook analytics as expect.
The login function still works fine but data not being collected ? Any suggest?

**Comment by nabeel-s** [comment]
@jasminecrazy, I solved the build errors by un-ejecting and re-ejecting my project and using the original Gradle version.

The Facebook SDK is now tracking installs. I would recommend checking the following:

- Use the latest version of Facebook SDK in build.gradle:

**implementation 'com.facebook.android:facebook-android-sdk:5.4.0'**

- Add **mavenCentral()** to the correct places in build.gradle under all 'repositories' brackets

- Check that you are using the correct password for the keystore when generating the release key hash.  Add this key hash to your Facebook App settings

- In AndroidManifest, use a string to add your Facebook app ID instead of hardcoding it because hardcoding gives an error when running, eg. use:

**<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>**

**Comment by sjchmiela** [comment]
Enabling/disabling app installs has been recently added to Expo. Since SDK36 you will be able to add several new configuration options to `app.json`. See https://github.com/expo/expo/pull/5924 for more information. 🙂
