### ISSUE TITLE
A lot of types cannot be imported

### ISSUE THREAD

**Issue by methodbox** [expo/expo#4422]
### Environment

```bash
Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.12 => 32.0.12 
      @types/react-native: ^0.57.51 => 0.57.51 
      @types/react-navigation: ^3.0.6 => 3.0.6 
      expo: ^32.0.0 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.17.1
```
### Steps to Reproduce

A lot of inferred types are correctly inferred, but the item cannot be typed explicitly as the type itself isn't exported anywhere in Expo's types.

There are a number of cases, but I most recently ran into this issue with the Location API.

This will show you the inferred type `ProviderStatus` which is just a boolean, but it cannot be typed as such as it's not really correct based on the `interface` definition.

```ts
let locationServiceStatus = await Location.getProviderStatusAsync();
```

### Expected Behavior

Either I should be able to type the object explicitly with the type (if it's exported correctly and exists on the "Expo" namespace, for example) or import it then do this. Like this:

```ts
let locationServiceStatus: ProviderStatus = await Location.getProviderStatusAsync();
```

### Actual Behavior
The type isn't exported (this is the case with many, many types in the `Location.d.ts` in `expo-location` and the other types included seemingly at random in the other broken up parts of Expo) so I can't use it or import it.

This doesn't break anything. The type is correctly inferred.

### Reproducible Demo

```ts
let locationServiceStatus = await Location.getProviderStatusAsync();
```

Suggested solution:

I don't know if this is the best solution, but as an example **I exported the type from your `Location.d.ts`** and then was able to use it without issue like this:

```ts
import { Location } from 'expo';
import { ProviderStatus } from 'expo-location';

locationEnabled = async (): Promise<void> => {
  let locationServiceStatus: ProviderStatus = await Location.getProviderStatusAsync();
  this.setState({ locationIsEnabled: locationServiceStatus.locationServicesEnabled });
};

```

Note that prior to this I imported Location from `expo` not `expo-location`; I'm not sure if this unimodules thing you're doing is conflicting somehow, but it's not pulling these types from `@types/expo`.

**Comment by ide** [comment]
As of SDK 33 and beyond, importing from `expo-location` (and other packages directly) is recommended and will soon be required. So the approach in the solution you posted will be necessary, regardless of TypeScript.

**Comment by methodbox** [comment]
@ide I think you might still be missing my point.

I *exported the type* from *your* definition file in order to use it.

Unless you’ve fixed the issue that the *types* are not correctly exported, you haven’t fixed this issue.

The problem I’m describing is **explicitly related to TypeScript**; your answer seems to indicate you’ve overlooked that.

**Comment by ide** [comment]
I understand that the location module still needs changes. The earlier posts says that importing from `expo` will not work in the future.

**Comment by methodbox** [comment]
> I understand that the location module still needs changes. The earlier posts says that importing from `expo` will not work in the future.

I get that ... but what you responded to and what the issue addresses are two different things.

There are a LOT of types that seem to be like this in Expo, not just Location. Is this being addressed in v33?

**Comment by ide** [comment]
If I understand correctly, there are two necessary changes to address the problem here:
1. Packages like expo-location don't export some types. This will get addressed over time. A lot of the types are designed to be structural rather than nominal, so the names of the types may change from release to release until they stabilize.
2. If (1) is addressed, the types generally won't be exported from the `expo` package -- `import { ProviderStatus } from 'expo'` won't work.

33 has already been published and most changes to types will probably go out with 34, 35, etc...

**Comment by methodbox** [comment]
> If I understand correctly, there are two necessary changes to address the problem here:
> 
> 1. Packages like expo-location don't export some types. This will get addressed over time. A lot of the types are designed to be structural rather than nominal, so the names of the types may change from release to release until they stabilize.
> 2. If (1) is addressed, the types generally won't be exported from the `expo` package -- `import { ProviderStatus } from 'expo'` won't work.
> 
> 33 has already been published and most changes to types will probably go out with 34, 35, etc...

I think you're still missing part of this:  they types aren't exported AT ALL - I had to do this manually from the `expo-location` package. I'm not seeing in your description that has been made clear; sorry if it is.

**Comment by methodbox** [comment]
> If I understand correctly, there are two necessary changes to address the problem here:
> 
> 1. Packages like expo-location don't export some types. This will get addressed over time. A lot of the types are designed to be structural rather than nominal, so the names of the types may change from release to release until they stabilize.
> 2. If (1) is addressed, the types generally won't be exported from the `expo` package -- `import { ProviderStatus } from 'expo'` won't work.
> 
> 33 has already been published and most changes to types will probably go out with 34, 35, etc...

Is there a reason things that cause actual TypeScript bugs can't be fixed in the mean time? Like if I put in a PR to fix this on 32 or 33, etc. why will that not be merged until the next major version?

I get the adherence to a release schedule, but how does that work for **actual bugs**?

**Comment by iamdavidmartin** [comment]
I have the same request as @methodbox. I'd like to import and use the Region interface for typescript but it's simply not exported from Location.d.ts. It seems like it ought to be.

https://github.com/expo/expo/blob/083fdf718973239a3f88fb2d37bf30cc048a82c1/packages/expo-location/build/Location.d.ts#L64

**Comment by tsapeta** [comment]
We've just fixed this by exporting some interfaces and types, see #7079 for more details, so I'm closing this ticket.
_Note_: We're also making sure that the types are exported correctly in other packages 😉
