### ISSUE TITLE
Can't start app created with create-react-native-app

### ISSUE THREAD

**Issue by leocristofani** [expo/expo#443]
After running `npm start`, I get the messages below in the  terminal, but the packager never packs the files to serve the app so I can see it from the expo client in my mobile device. Any idea why that's happening? This used to work.

```
11:45:08 AM: Starting packager...
Packager started!
To view your app with live reloading, point the Expo app to this QR code.
You'll find the QR scanner on the Projects tab of the app.
Or enter this address in the Expo app's search bar:
  exp://192.168.0.9:19000
Your phone will need to be on the same local network as this computer.
For links to install the Expo app, please visit https://expo.io.
Logs from serving your app will appear here. Press Ctrl+C at any time to stop.
```

my dependencies in case it helps:

```
"dependencies": {
    "deep-freeze": "0.0.1",
    "expo": "^17.0.0",
    "native-base": "^2.1.4",
    "prop-types": "^15.5.10",
    "ramda": "^0.24.1",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-easy-grid": "^0.1.13",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "uuid": "^3.0.1"
  }
```
my machine is `macOS Sierra 10.12.6`

**Comment by terribleben** [comment]
The packager will wait for something to request a bundle. Does the device screen say something in particular when you scan the QR code / open the url being served by your packager?

**Comment by elantion** [comment]
I use yarn and follow official get-start tutorial. I come to the same result as leocristofani. Expo logo keep flashing and nothing happened.
My PC system is Windows and my phone is android. Before running example app, I got a message 'Permit drawing over other apps'. I click 'OK', But Expo didn't open anything.
