### ISSUE TITLE
Release SDK 34

### ISSUE THREAD

**Issue by ide** [expo/expo#4437]
SDK 34 project board: https://github.com/orgs/expo/projects/2

**Comment by sjchmiela** [comment]
## SDK33 release plan

Release branch: [sdk-34](https://github.com/expo/expo/tree/sdk-34)

### SDK code related

- [ ] drop obsolete SDKs
- [ ] update `@expo/vector-icons`
- [ ] update `react-native-gesture-handler`
- [ ] update `react-native-reanimated`
- [ ] update `react-native-screens`
- [ ] update `@react-native-community/netinfo`
- [ ] update `@react-native-community/webview`
- [ ] update `react-native-maps`
- [ ] update `react-native-branch`
- [ ] update `react-native-svg`
- [ ] Generate new mocks and update `jest-expo`
- [ ] Version Android code (@sjchmiela)
- [ ] Version iOS code (@tsapeta)
- [ ] QA Expo Client on iOS (@tsapeta)
- [ ] QA Expo Client on Android (@sjchmiela)
- [ ] Publish prerelease packages
- [ ] Tag react-native fork `sdk-34.0.0` (@ide)
- [ ] Tag iOS ExpoKit (@tsapeta)
- [ ] Publish `!expo` packages to npm (@sjchmiela)
- [ ] Update `expokit-npm-package` (@sjchmiela)
- [ ] Publish `react-native-unimodules` to npm (@sjchmiela)
- [ ] Publish `expo` to npm (@sjchmiela, @tsapeta)
- [ ] Test web in template projects and in general (@EvanBacon)


### Launch blockers
- [ ] The "Profile" tab in the Expo client is blank #4734
- [ ] Add react-native-datetimepicker to SDK #4691

### Infrastructure related
- [ ] Update schema on staging (@sjchmiela)
- [ ] Deploy schema to production (@sjchmiela)
- [ ] Release xdl and expo-cli (@sjchmiela)
- [ ] Publish dev and prod home (@tsapeta)
- [ ] Push iOS Turtle to staging (@tsapeta)
- [ ] Push Android Turtle to staging (@sjchmiela)
- [ ] Release new project templates
- [ ] Update ExpoKit Android on staging (@sjchmiela)
- [ ] Update ExpoKit iOS on staging (@tsapeta)
- [ ] Update ExpoKit AdHoc iOS on staging (@tsapeta)
- [ ] Update `versions` on staging
- [ ] Publish NCL to Apple's account (@tsapeta)
- [ ] Update Home to show web projects
- [ ] Submit for Apple review (@tsapeta)
- [ ] Release iOS in App Store (@tsapeta)
- [ ] Rollout Expo Client build for Simulator (@tsapeta)
- [ ] Push Android ExpoKit (@sjchmiela)
- [ ] Add Android apk (@sjchmiela)
- [ ] Release Android in Play Store (@sjchmiela)
- [ ] Mark old SDK as deprecated on server (@sjchmiela)
- [ ] Promote versions to prod
- [ ] Add SDK34 support to Snack (@tcdavis)
- [ ] Release iOS Turtle to prod
- [ ] Release Android Turtle to prod (@sjchmiela)
- [ ] Release turtle-cli
- [ ] Test ad-hoc builds (@quinlanj)

### Information related
- [ ] Prepare changelog (@sjchmiela)
- [ ] Review changelog (@tsapeta)
- [ ] Publish NCL to @ community account
- [ ] Add release notes to docs
- [ ] Publish blog post with release notes (@ide, @esamelson)
- [ ] Update React Native docs for this SDK (@tsapeta)
- [ ] Publish new docs (@tsapeta)
- [ ] Promote new docs to prod
- [ ] Update website front page
- [ ] Post on Twitter

**Comment by ide** [comment]
Closing this; onto SDK 35.
