### ISSUE TITLE
`exp detach` doesn't handle `"supportsTablet": true` well

### ISSUE THREAD

**Issue by xavier-villelegier** [expo/expo#444]
Hello everyone,

# Config
```
exp: 43.0.0,
Xcode: 8.3.3,
```

# Issue
In my `app.json` I have the following:
```
"ios": {
  …
  "supportsTablet": true
},
```

But when I run `exp detach`, it misses:
- `TARGETED_DEVICE_FAMILY = "1,2"` in the `project.pbxproj`
- Icons for iPad are suffixed by `~ipad.png` and I think it messes up the build process

EDIT: It seems that `AppIcon.appiconset/Contents.json` does not include the `76x76` and `83.5x83.5` icons

EDIT 2: I tried to modify the `Contents.json` and it works, but ideally, `exp detach` should do it itself, to be able to automate as much as possible the deployment of an expo application.
I have added:
```
{
  "size": "76x76",
  "idiom": "ipad",
  "filename": "AppIcon76x76@2x.png",
  "scale": "2x"
},
{
  "size": "83.5x83.5",
  "idiom": "ipad",
  "filename": "AppIcon83.5x83.5@2x.png",
  "scale": "2x"
},
{
  "size": "83.5x83.5",
  "idiom": "ipad",
  "filename": "AppIcon83.5x83.5@3x.png",
  "scale": "3x"
}
```

**Comment by slorber** [comment]
Also want to add that it seems some icons are missing when trying to publish the app.

Here I get these errors from Fastlane:

```
ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format for iOS versions supporting iPad Pro."
ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 10.0."
```

**Comment by slorber** [comment]
Actually iPad icons are generated if the source app.json icon is large enough. Maybe Expo should refuse to eject or warn if supportsTablet=true and current icon is not large enough to support ipads

**Comment by AdamJNavarro** [comment]
Closing this issue as the exp devtool has since been replaced by the expo-cli.
