### ISSUE TITLE
[SDK 33] Unable to resolve module expo-react-native-adapter

### ISSUE THREAD

**Issue by center-777** [expo/expo#4441]
### Environment

 Expo CLI 2.19.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.2.3 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.1

On IOS device (Managed workflow)

![image](https://user-images.githubusercontent.com/7359520/59016413-d770e100-8849-11e9-84ae-6fa17114f558.png)

reinstall node_modules, watchman watch-del-all, npm start --reset-cache doesn't help

**Comment by sjchmiela** [comment]
It seems strange that something still imports `expo-core` and `expo-react-native-adapter` in your project — we've moved them to `@unimodules/core` and `/react-native-adapter`. Do you import the former packages somewhere in your code? Could you please post `dependencies` field from your `package.json`?

**Comment by center-777** [comment]
My package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "react-devtools": "react-devtools"
  },
  "dependencies": {
    "@expo/vector-icons": "^9.0.0",
    "expo": "^33.0.0",
    "expo-localization": "^2.0.0",
    "prop-types": "^15.7.1",
    "react": "16.8.3",
    "react-devtools": "^3.6.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-navigation": "^3.11.0",
    "underscore": "^1.9.1"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "flow-bin": "^0.97.0"
  },
  "private": true
}
```

**Comment by sjchmiela** [comment]
1. Remove `expo-localization` from `dependencies`.
2. Add it back using `expo install expo-localization`. The new `expo install` command will ensure proper version (compatible with the SDK version you're using) of the unimodule is installed.

**Comment by center-777** [comment]
Yes it solved the problem.
Thank you!

**Comment by AbodyAmer** [comment]
Hello, I have the same problem: 

This is my package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@unimodules/react-native-adapter": "^2.0.1",
    "axios": "^0.18.0",
    "expo": "^33.0.0",
    "expo-analytics": "^1.0.7",
    "expo-google-sign-in": "^2.0.0",
    "firebase": "^5.8.3",
    "moment": "^2.24.0",
    "native-base": "2.8.0",
    "qs": "^6.6.0",
    "react": "16.8.3",
    "react-moment": "^0.8.4",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-auto-height-image": "^1.0.5",
    "react-native-fcm": "^16.2.4",
    "react-native-firebase": "^5.2.2",
    "react-native-floating-action": "^1.14.2",
    "react-native-fullwidth-image": "^0.1.2",
    "react-native-google-signin": "^1.1.0",
    "react-native-htmlview": "^0.13.0",
    "react-native-lazyload-deux": "^2.0.4",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-modal": "^7.0.2",
    "react-native-render-html": "^4.1.1",
    "react-native-router-flux": "^4.0.6",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-swiper": "^1.5.14",
    "react-native-unimodules": "^0.4.1",
    "react-native-vector-icons": "^6.2.0",
    "react-native-webview": "^5.2.1",
    "react-native-webview-autoheight": "^1.0.6",
    "react-navigation": "^3.1.5",
    "react-outbrain-widget": "^1.0.6",
    "react-timer-mixin": "^0.13.4",
    "striptags": "^3.1.1"
  },
  "devDependencies": {
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

```

**Comment by sjchmiela** [comment]
Try:
- removing `@unimodules/react-native-adapter` from your `package.json` (`react-native-unimodules` depends on proper version already)
- removing `expo-analytics` and `expo-google-sign-in` from `package.json`
- run `expo install expo-analytics expo-google-sign-in`, which will install proper version of these libraries (compatible with the whole unimodules infrastructure)

**Comment by Xyzor** [comment]
Just to extend the list :smile:, for me it was `expo-pixi` which required a reinstall.
