### ISSUE TITLE
SDK 33 — createIconSet missing or removed?

### ISSUE THREAD

**Issue by akinadebowale** [expo/expo#4445]
## 🐛 Bug Report

Amazing work on Expo family.

**createIconSet** seems to be missing or removed from recent updates. Am I missing something? Not sure if it directly related to SDK upgrade or upgrading associated packages because of the SDK upgrade but it seems like a mistake? According [expo/vector-icons](https://github.com/expo/vector-icons/commits/90e5902bdec46ffdbcb0a8090e41e6b54f174d1c/build/Icons.js) it happened mid-March so I guess not too many people are creating Icons from scratch. Nevertheless, messing with ``node_modules/@expo/vector-icons/build/Icons*`` was the temporary fix for me.

### Environment

Expo CLI 2.19.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.npm-global/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.4 => 16.8.19 
      @types/react-native: ^0.57.60 => 0.57.60 
      @types/react-navigation: ^3.0.7 => 3.0.7 
      expo: ^33.0.0 => 33.0.3 
      react: ^16.8.3 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.0

App's target: iOS

### Steps to Reproduce

Upgraded Expo SDK using this guide: https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c

Also ran ``yarn upgrade expo``.

Imported **createIconSet** with ``import { createIconSet } from '@expo/vector-icons';``

Ran app on my device.

### Expected Behavior

App loads without error.

### Actual Behavior

App does not load.
Error: ``_createIconSet is not defined`` or ``_createIconSet is not a function``

**Comment by ide** [comment]
@brentvatne looking in Icons.ts of expo/vector-icons, we don't export createIconSet anymore. Should we add that export, or is createMultiStyleIconSet now recommended?

**Comment by akinadebowale** [comment]
@ide seems to have been a bug fixed in this newer [issue](https://github.com/expo/expo/issues/4458).
