### ISSUE TITLE
[templates] Optimize template assets

### ISSUE THREAD

**Issue by fson** [expo/expo#4456]
Right now if I create a brand new project with `expo init` and start it, I immediately get this warning (even though I have not added any assets myself, yet):
> Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory.

I think we should run `expo optimize` in all the templates and also commit the resulting `.expo-shared/assets.json` so that a pristine project doesn't show any warnings.

**Comment by ide** [comment]
Yes, let’s do this. I think the template icons are already very optimized (IIRC they are smaller than what Expo optimize emits) and we just need the .expo-shared metadata.

**Comment by ilahishaikh** [comment]
When i started Expo new Project that time give warning: Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory. like this how can i solve.
