### ISSUE TITLE
How to install bitcoinjs-lib and ethers or other about cryptowallet package for sdk 33?

### ISSUE THREAD

**Issue by Lursun** [expo/expo#4457]
I can't install  bitcoinjs-lib and ethers on my local and Snack.
https://snack.expo.io/@lursun914013/groaning-bubblegum

**Comment by cruzach** [comment]
Hi @Lursun, according to the https://github.com/novalabio/react-native-bitcoinjs-lib , there are some dependencies that require `link`ing, so you'll have to use these in a bare project, rather than managed or a Snack.
