### ISSUE TITLE
[docs] createIconSet is missing

### ISSUE THREAD

**Issue by gabrielmaiaf** [expo/expo#4458]
I tried to use createIconSet using @expo/vector-icons like shown in https://docs.expo.io/versions/latest/guides/icons/ but it raised a error telling that createIconSet is missing; and exists a module called createMultiStyleIconSet that there's no info in docs

**Comment by timotius02** [comment]
I am also having this issue. Currently running Expo version 2.19.1

**Comment by brentvatne** [comment]
fixed, if you delete node_modules and your lockfile and reinstall then you'll get the fix. it's a patch update for @expo/vector-icons to 10.0.2
