### ISSUE TITLE
Haptic docs link is broken [docs] 

### ISSUE THREAD

**Issue by dereknelson** [expo/expo#4460]
[Haptic docs link](https://docs.expo.io/versions/latest/sdk/haptic) says "an unexpected error occurred". It's the top link from google, maybe add a redirect to haptics?

**Comment by brentvatne** [comment]
should be fixed now

**Comment by brentvatne** [comment]
it isn't for some reason

**Comment by dereknelson** [comment]
@brentvatne fwiw I was going to open a PR because I tried doing the same exact fix as nick locally but it didn't work and I didn't have time to dig deeper :/

**Comment by tsapeta** [comment]
cc @nicknovitski

**Comment by cruzach** [comment]
fixed by [this commit](https://github.com/expo/expo/commit/af28e265c4974e0927c6bafb7f16e5131fcefeec)
