### ISSUE TITLE
Flow error after SDK 33 update

### ISSUE THREAD

**Issue by jfaris** [expo/expo#4462]
### Environment

```
  Expo CLI 2.18.7 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: 33.0.1 => 33.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
```

### Steps to Reproduce

Run flow on an expo project after updating to SDK 33

### Expected Behavior

flow type checking should run successfully.

I know that TypeScript is now the "official" type system for expo but I have existing code with flow annotations and I would like to continue using flow on that code for now.

### Actual Behavior

Flow gives this error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-native/Libraries/Text/TextProps.js:58:21

Cannot get React.Node because property Node is missing in object type [1].

     node_modules/react-native/Libraries/Text/TextProps.js
      55│    * See https://facebook.github.io/react-native/docs/text.html#allowfontscaling
      56│    */
      57│   allowFontScaling?: ?boolean,
      58│   children?: ?React.Node,
      59│
      60│   /**
      61│    * When `numberOfLines` is set, this prop defines how text will be
```

There are other similar `React.Node` errors including one in `ViewPropTypes.js`

It appears that commit https://github.com/facebook/react-native/commit/0ee5f68929610106ee6864baa04ea90be0fc5160 from react-native master (now in 0.60.0-rc.0) would fix this.

**Comment by brentvatne** [comment]
you might want to fix this in your node_modules directly and use `patch-package` to keep it patched after each yarn/npm command - https://www.npmjs.com/package/patch-package

**Comment by jfaris** [comment]
Thanks for the `patch-package` tip, I'll check it out.

Is this something that you would update in the expo react-native tgz eventually? Maybe if it were cherry-picked to react native 0.59 first?

**Comment by brentvatne** [comment]
possibly, but i wouldn't count on us continuing to do that for flow at all times. flow is not very well supported for folks outside of facebook at the moment and we don't have time to stay on top of the issues that fall out from that

**Comment by jfaris** [comment]
Thanks for the honesty. I'll see what I can do with patch-package.
