### ISSUE TITLE
SDK33 react-native-webview window.ReactNativeWebView undefined

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo#4463]
### Environment

  Expo CLI 2.19.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: 33.0.3 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: 3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.19.1

### Steps to Reproduce

use react-native-webview example.
but window.ReactNativeWebView is  undefined.

https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onmessage

const INJECTED_JAVASCRIPT = `(function() {
    window.ReactNativeWebView.postMessage(JSON.stringify(window.location));
})();`;

<WebView
  source={{ uri: 'https://facebook.github.io/react-native' }}
  injectedJavaScript={INJECTED_JAVASCRIPT}
  onMessage={this.onMessage}
/>

**Comment by rxhivzero** [comment]
https://github.com/react-native-community/react-native-webview/releases/tag/v5.0.0
In sdk 33 not use window.ReactNativeWebView and window.postMessage.
I can only use `import { StyleSheet, WebView } from 'react-native'`

**Comment by rompjin** [comment]
same issue.

**Comment by ru88s** [comment]
I have the same bug.
Thank you for posting the issue.

**Comment by brentvatne** [comment]
perhaps it's a bug in react-native-webview? can somebody try it in a bare project with version 5.8.1 (the version we use in expo) and verify?

**Comment by rompjin** [comment]
> perhaps it's a bug in react-native-webview? can somebody try it in a bare project with version 5.8.1 (the version we use in expo) and verify?

I tried it in a bare project with react-native-webview 5.8.1,  just finished the test and it works fine.

**Comment by brentvatne** [comment]
@rompjin - can you share the JS code from your test?

**Comment by brentvatne** [comment]
ah, I see the problem. our approach to versioning mangles the name of the message handler constant: https://github.com/expo/expo/blob/5b2f50c5cbe19a3a15287dda8bf1195edfe93e6c/ios/versioned-react-native/ABI33_0_0/Expo/Core/Api/Components/WebView/ABI33_0_0RNCWKWebView.m#L17

this constant is used to define the handler: https://github.com/expo/expo/blob/5b2f50c5cbe19a3a15287dda8bf1195edfe93e6c/ios/versioned-react-native/ABI33_0_0/Expo/Core/Api/Components/WebView/ABI33_0_0RNCWKWebView.m#L122-L128

**Comment by brentvatne** [comment]
here's a temporary workaround:

```js
import React from 'react';
import { Dimensions, View } from 'react-native';
import { WebView } from 'react-native-webview';

const INJECTED_JAVASCRIPT = `(function() {
    if (!window.ReactNativeWebView) {
      window.ReactNativeWebView = window['ReactABI33_0_0NativeWebView'];
    }

    window.ReactNativeWebView.postMessage(JSON.stringify(window.location));
})();`;

export default function App() {
  return (
      <WebView
        source={{ uri: 'https://facebook.github.io/react-native' }}
        style={{width: Dimensions.get('window').width, height: Dimensions.get('window').height}}
        injectedJavaScript={INJECTED_JAVASCRIPT}
        onMessage={event => alert(event.nativeEvent.data)}
      />
  );
}
```

**Comment by rompjin** [comment]
@brentvatne appreciate it!

**Comment by ru88s** [comment]
https://github.com/facebook/react-native/issues/10865

`const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;

  var patchedPostMessage = function(message, targetOrigin, transfer) { 
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() { 
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };

  window.postMessage = patchedPostMessage;
};

const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';

...

<WebView injectedJavaScript={patchPostMessageJsCode} />`

Thank you for your quick response.
I'm using this.
It does not work well.
How should this be changed?

**Comment by devdebajyotidas** [comment]
> ```js
> ReactNativeWebView
> ```

@brentvatne This works great on iOS, however, it doesn't work on Android thought. Any solution for Android so far?
