### ISSUE TITLE
SDK33 red error screen flashes and then goes white

### ISSUE THREAD

**Issue by vonwao** [expo/expo#4468]
## 🐛 Bug Report

After upgrading to SDK33, when the app loads, a red screen flashes but immediately goes to white, so I can't read the error.  How can I troubleshoot this?

**Comment by vonwao** [comment]
Now I tried to downgrade back to DSK 32, but now my project doesn't work anymore.  Now it just says "There was a problem running the requested app".  Are there any other caches or things that I can clear, other than node_modules?

**Comment by brentvatne** [comment]
> Now I tried to downgrade back to DSK 32, but now my project doesn't work anymore. Now it just says "There was a problem running the requested app". Are there any other caches or things that I can clear, other than node_modules?

`expo start -c` will clear caches. Restart the Expo client app as well.

> After upgrading to SDK33, when the app loads, a red screen flashes but immediately goes to white, so I can't read the error. How can I troubleshoot this?

If you can let us know how to reproduce this error we can look into it!

**Comment by grinono** [comment]
i'm having the same issue in production Dev works fine, though I'm not seeing a red screen. 2sec after the launch icon is show the app crashes without a crash report. no idea where to start.

**Comment by ide** [comment]
I would recommend looking in the adb logs or Mac console app to see if there is any relevant information. This sounds like an issue with a specific project's code causing some kind of fatal.

**Comment by vonwao** [comment]
Thanks @ide I need to go back to this and check this.  I was running on iPhone without any console, so I have to find a way to look at the console.  How to get the iPhone logs if I'm developing on a PC?

**Comment by ide** [comment]
I'm not sure how do that, maybe there is a third-party tool -- on Mac you can open up Console.app and read the iPhone logs.

**Comment by tsapeta** [comment]
SDK33 is no longer supported and we haven't seen any similar reports referring to newer SDK versions, so I'm closing this one. Feel free to open a new issue if you're still experiencing this in the latest SDK.
