### ISSUE TITLE
Add support for drawing an overlay when shooting pictures with camera?

### ISSUE THREAD

**Issue by awakenrz** [expo/expo#447]
I would like to draw some lines to guide users to align the camera with the object in a certain way when taking pictures. I don't think I can achieve this with `Expo.ImagePicker.launchCameraAsync`. Is it possible to add this support?

**Comment by terribleben** [comment]
Hi! We're working on adding support for this now. Hooray. I don't have an exact eta. In the meantime, you can [upvote the feature request on canny](https://expo.canny.io/feature-requests/p/camera-component)!

**Comment by gitrago** [comment]
Hello @terribleben, 
I see the new camera component https://docs.expo.io/versions/latest/sdk/camera.html Waycool. But how does one add an overlay image (or "draw some lines") to the viewfinder as @awakenrz requested?

**Comment by EmirGluhbegovic** [comment]
@terribleben With regards to @gitrago question, any answers?
