### ISSUE TITLE
[docs] Documentation on creating Unimodules

### ISSUE THREAD

**Issue by robertherber** [expo/expo#4471]
I'm missing documentation on how to implement and create third-party unimodules. I suppose this is the direction unimodules should go - it's not meant just for expo packages but for the entire community to contribute with unimodules?

**Comment by brentvatne** [comment]
what are you hoping to accomplish by building a unimodule? what advantages do you see it as having over building a plugin with the normal react-native api? not asking this to be facetious, i'm genuinely curious what makes you interested.

at this point we don't recommend making unimodules for components that require view managers. unimodules in their current state are best suited for apis that don't render anything to react view hierarchy, eg: calendar allows you to get info and set info but doesn't have a view representation in your app. if there's enough interest we can certainly document how you can create these.

**Comment by robertherber** [comment]
It's supposed to work in the Expo Managed workflow, right? What I've been missing in Expo before is the extensibility that's available in vanilla RN, which unimodules seems to solve.

What it boils down to is that right now I'd hesitate to use Expo for most projects - since I often need things that are only available as third-party NativeModules. Using Expo when I think I'll need to eject is just not worthwhile. Just having a documented way to convert an existing NativeModule into a Unimodule would make it so much easier for me to choose Expo for new projects.

**Comment by brentvatne** [comment]
unimodules don't actually make it possible to write arbitrary native code and include it in the expo client app or in standalone apps. we're currently thinking that we'd like to get to that point by allowing you to do a [custom client build](https://docs.expo.io/versions/v33.0.0/guides/adhoc-builds/) where you can specify what unimodules to include and have standalone app builders analyze your dependencies and include whatever unimodules you have in your package.json, but this is all still hypothetical, we haven't built that yet so it's not currently possible to add / remove modules from the client build. knowing this, i suspect you are less interested in unimodules and a guide may not be particularly urgent

**Comment by robertherber** [comment]
Ah, ok, then it’s not as urgent. Thanks for the info.

Any timeframe/roadmap on adding it to custom client builds? I do think this would be the single most important addition to the Expo ecosystem.

**Comment by brentvatne** [comment]
don't have a timeline right now. different pieces to make it possible are actively being worked on and we agree it's very important

**Comment by brentvatne** [comment]
https://docs.expo.dev/modules/overview/
