### ISSUE TITLE
`exp start` broken while trying to build a shell app for a detached expo application to bypass 2fa

### ISSUE THREAD

**Issue by Elijen** [expo/expo#448]
Running `exp start` in both `js` and `js/__develop__` fails with an error. This is the error for `js/__develop___`:
<img width="980" alt="screen shot 2017-08-01 at 18 05 13" src="https://user-images.githubusercontent.com/1304054/28835025-54797e38-76e4-11e7-9e8a-b8d67d97c872.png">

I figured out that this could be fixed by using `../../..react-native-lab/blacklist` instead of `react-native/packager/blacklist` (which has been removed). But then there is another error appearing:
<img width="780" alt="screen shot 2017-08-01 at 18 10 38" src="https://user-images.githubusercontent.com/1304054/28835161-c43043b0-76e4-11e7-92dc-4216e641af09.png">

Any ideas how could I fix or debug this further? 

Some more information:
- Running via `./tools/setup` in the latest master of `expo/expo-dev`
- macOS v10.12.6 
- Node v8.0.0
- NPM v4.6.1

**Comment by Elijen** [comment]
So far here is a list of workarounds I had to do:

- replace `js/__develop__/rn-cli.config.js` with a version from @brentvatne (below)
```js
const path = require('path');
const { expoBlacklist } = require('../../../react-native-lab/blacklist');
const LabConfig = require('../../../react-native-lab/LabConfig');

module.exports = {
  getProjectRoots() {
    return [path.join(__dirname, '..'), LabConfig.getUniverseRoot()];
  },

  getBlacklistRE() {
    return expoBlacklist([]);
  },

  getTransformModulePath() {
    return LabConfig.getLabTransformerPath();
  },
};
```

- fix all references of `metro-bundler/build` to `metro-bundler/src` in the `react-native-lab` directory

- Make sure `isInUniverse` and `isInOssDev` variables are set as below in `tools-public/generate-dynamic-macros.js`:
```
let isInUniverse = false;
let isInOssDev = true; 
```

**Comment by Elijen** [comment]
My adventure ended after building the iOS app:

<img width="436" alt="screen shot 2017-08-01 at 21 17 13" src="https://user-images.githubusercontent.com/1304054/28842689-eb2c9328-76fe-11e7-8366-90809bf20632.png">

<img width="862" alt="screen shot 2017-08-01 at 21 16 58" src="https://user-images.githubusercontent.com/1304054/28842690-eb2d031c-76fe-11e7-810f-d2fda0ad6af0.png">

**Comment by ccheever** [comment]
Hi-

Just wanted to check, what are you trying to do? Just build an Expo app or work on the Expo client itself?

I don't think you need to do `exp start` if you're working on the Expo client itself.

And you don't need to clone the repo if you just want to build an app on Expo.

**Comment by Elijen** [comment]
@ccheever Hi, I am trying to build a shell app by myself because `exp bi` does not work with 2FA.

I was following the expo/expo-dev README.
