### ISSUE TITLE
[android] Eject from latest expo SDK, got A problem occurred configuring project ':expo-gl-cpp'.

### ISSUE THREAD

**Issue by narefyev91** [expo/expo#4483]
### Environment

Expo CLI 2.19.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.3

Expokit Android

### Steps to Reproduce

I updated my project with latest SDK 33, and start to eject - on IOS everything done well, on android I open Android studio - and the project started automatically build

### Expected Behavior

Project build successful

### Actual Behavior

Got error: 
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':expo-gl-cpp'.

Also got this - Cannot get property 'absolutePath' on null object - in file expo-gl-cpp inside this peace of code  

def ndkDir = android.hasProperty('plugin') ? android.plugin.ndkFolder :
      plugins.getPlugin('com.android.library').hasProperty('sdkHandler') ?
          plugins.getPlugin('com.android.library').sdkHandler.getNdkFolder() :
          android.ndkDirectory.absolutePath

Any ideas what to do?
Thanks

**Comment by tsapeta** [comment]
Hey @narefyev91,
Do you have Android NDK installed? It would probably work when you install it, however our intention was to make it optional, so something went wrong 😅 I'll investigate it further.
Was it working in ejected SDK32 project? 🤔

**Comment by mikaarefyev** [comment]
> Hey @narefyev91,
> Do you have Android NDK installed? It would probably work when you install it, however our intention was to make it optional, so something went wrong 😅 I'll investigate it further.
> Was it working in ejected SDK32 project? 🤔

Yes it was working on SDK32. Yes I installed all packages in Android Studio - and everything starts to work. Thanks a lot for your help

**Comment by changLiuUNSW** [comment]
You need to install Android NDK

**Comment by jacinto123** [comment]
I had the same issue installing Android NDK fixed it.

**Comment by fxbayuanggara** [comment]
Solved after installing the Android NDK, thanks.

**Comment by chakradhari** [comment]
Hey @fxbayuanggara 
I downloaded Android NDK but I still see the issue should I map android ndk in a file.

**Comment by fxbayuanggara** [comment]
Hello @chakradhari ,

have you exported the NDK folder to the right path?
mine is in android/sdk/ndk-bundle.

Make you have created the right path in your system environment for both android sdk and ndk.
Mine is like this: 

export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle
export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle

export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/build-tools/28.0.3

**Comment by jeremybdk** [comment]
Hello @tsapeta,
Our build was working fine with SDK32 but now SDK33 do require NDK installed. I noticed that the issue is now closed.
I can install the NDK just fine on my computer but it's more complicated to setup the NDK for CI/CD.
Is the NDK now mandatory? If so I guess the docs should be updated, if not any plan to fix this issue for SDK33?

Thanks a lot

**Comment by tsapeta** [comment]
@jeremybdk, I've just addressed this issue in PR #4697. It wasn't our intention to require Android NDK. I'll publish a fix to `expo-gl` once we merge this pull request - I'll let you know here then 😉

**Comment by jeremybdk** [comment]
@tsapeta Thank you so much :)

**Comment by mjgallag** [comment]
@tsapeta would be great if we could get this back ported to v33 at some point, thanks!

**Comment by hashmatmuqbil** [comment]
> android/sdk/ndk-bundle.



> Hello @chakradhari ,
> 
> have you exported the NDK folder to the right path?
> mine is in android/sdk/ndk-bundle.
> 
> Make you have created the right path in your system environment for both android sdk and ndk.
> Mine is like this:
> 
> export ANDROID_HOME=$HOME/Library/Android/sdk
> export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
> export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle
> export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle
> 
> export PATH=$PATH:$ANDROID_HOME/emulator
> export PATH=$PATH:$ANDROID_HOME/tools
> export PATH=$PATH:$ANDROID_HOME/tools/bin
> export PATH=$PATH:$ANDROID_HOME/platform-tools
> export PATH=$PATH:$ANDROID_HOME/build-tools/28.0.3

Hi @fxbayuangg

where can I put these export PATH?

**Comment by hashmatmuqbil** [comment]
> export ANDROID_HOME=$HOME/Librar

Hi @fxbayuanggara 
where should I put these export PATHs?

**Comment by bogrees** [comment]
@hashmatmuqbil, if you are on a mac, edit your .bashrc file.

https://stackoverflow.com/questions/29795388/how-to-set-ndk-build-path-in-osx-for-android-studio

https://github.com/bahattincinic/react-native-starter-kit/wiki/How-to-set-ANDROID_HOME-environment-variable-in-mac

**Comment by hashmatmuqbil** [comment]
> @hashmatmuqbil, if you are on a mac, edit your .bashrc file.
> 
> https://stackoverflow.com/questions/29795388/how-to-set-ndk-build-path-in-osx-for-android-studio
> 
> https://github.com/bahattincinic/react-native-starter-kit/wiki/How-to-set-ANDROID_HOME-environment-variable-in-mac

@bogress  no, I'm on Windows

**Comment by hashmatmuqbil** [comment]
> @hashmatmuqbil, if you are on a mac, edit your .bashrc file.
> 
> https://stackoverflow.com/questions/29795388/how-to-set-ndk-build-path-in-osx-for-android-studio
> 
> https://github.com/bahattincinic/react-native-starter-kit/wiki/How-to-set-ANDROID_HOME-environment-variable-in-mac

@bogrees no, I'm on windows

**Comment by julekgwa** [comment]
@hashmatmuqbil put them in environment variables https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

**Comment by hashmatmuqbil** [comment]
> ## 🐛 Bug Report
> ### Environment
> Expo CLI 2.19.3 environment info:
> System:
> OS: macOS 10.14.5
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 10.14.2 - /usr/local/bin/node
> Yarn: 1.16.0 - /usr/local/bin/yarn
> npm: 6.9.0 - /usr/local/bin/npm
> IDEs:
> Android Studio: 3.4 AI-183.6156.11.34.5522156
> Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
> npmPackages:
> expo: ^33.0.0 => 33.0.3
> react: 16.8.3 => 16.8.3
> react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
> react-navigation: ^3.11.0 => 3.11.0
> npmGlobalPackages:
> expo-cli: 2.19.3
> 
> Expokit Android
> 
> ### Steps to Reproduce
> I updated my project with latest SDK 33, and start to eject - on IOS everything done well, on android I open Android studio - and the project started automatically build
> 
> ### Expected Behavior
> Project build successful
> 
> ### Actual Behavior
> Got error:
> org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':expo-gl-cpp'.
> 
> Also got this - Cannot get property 'absolutePath' on null object - in file expo-gl-cpp inside this peace of code
> 
> def ndkDir = android.hasProperty('plugin') ? android.plugin.ndkFolder :
> plugins.getPlugin('com.android.library').hasProperty('sdkHandler') ?
> plugins.getPlugin('com.android.library').sdkHandler.getNdkFolder() :
> android.ndkDirectory.absolutePath
> 
> Any ideas what to do?
> Thanks

Hi,
I have the same issue (org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':expo-gl-cpp'.
Also got this - Cannot get property 'absolutePath' on null object - in file expo-gl-cpp inside this peace of code) on Windows.
Android NDK is already installed.
Any help please??
