### ISSUE TITLE
Fetch not working in background location task

### ISSUE THREAD

**Issue by inspmoore** [expo/expo#4484]
## 🐛 Bug Report
I'm trying to send location data to the server while the app is in background. Seems to work on iOS, NOT working on Android.
### Environment

Expo SDK 33
Expo CLI 2.19.3 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.19.3

Expo Client on Android

### Steps to Reproduce
So I'm defining a task in the global scope. Something like this:
```
TaskManager.defineTask(TASK_NAME, async ({ data: { locations } }) => {
  try {
      const response = await fetch('https://blah.blah.url/endpoint', {
        body: JSON.stringify(locations),
        headers: {
          'Content-Type': 'application/json'
        },
        method: 'POST'
      })
    }
  } catch (error) {
    console.log(TASK_NAME, error)
  }
})
```
Then after checking for Location permissions I start a task with
```
await Location.startLocationUpdatesAsync(TASK_NAME, {
      accuracy: Location.Accuracy.BestForNavigation,
})
```
app.json is updated with the following
```
"UIBackgroundModes": [
          "location",
          "fetch"
        ]
```

On iOS I do see requests coming to the server, even if the app is in the background. The problem is Android. As soon as I move the app to the background the requests just stop.

### Expected Behavior

Expected fetch requests to work both on iOS and Android.

### Actual Behavior

On iOS I do see requests coming to the server, even if the app is in the background. The problem is Android. As soon as I move the app to the background the requests just stop.

### Reproducible Demo

Sorry, can't make a snack out of it due to snack limitations.

**Comment by inspmoore** [comment]
Hi @tsapeta Is there a way around this?

**Comment by giautm** [comment]
Hi @inspmoore, I think you missed something in document https://docs.expo.io/versions/v33.0.0/sdk/background-fetch/

```
stopOnTerminate (boolean) -- Whether to stop receiving background fetch events after user terminates the app. Defaults to true. (Android only)
```
You should set `stopOnTerminate` to `false` manually. 😄

**Comment by inspmoore** [comment]
Hi!

Thanks for your reply. I don't think that's the problem. I'm not using
BackgroundFetch (i don't want update my app in the background). I just want
to send data to the server during the background location event, and i'm
using fetch to make a request to the server. Works fine on iOS, but not on
Android. Do you suggest I should register a BackgroundFetch task too?

Thanks
Lucas

pt., 7 cze 2019 o 20:22 Giau Tran Minh <notifications@github.com>
napisał(a):
