### ISSUE TITLE
[iOS] Missing exp.notification in standalone app

### ISSUE THREAD

**Issue by giautm** [expo/expo#4487]
### Environment

```
 Expo CLI 2.19.3 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 2.2 AI-145.3537739
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.2.3 
    npmGlobalPackages:
      expo-cli: 2.19.3
```
App's target: Standalone, iOS

### Steps to Reproduce

Build standalone app.
Send notification to the app (App was not open)

### Expected Behavior

App should receive notification when user click to the notification to open the app.

### Actual Behavior

App can't receive init notification because `exp.notification` is undefined.

I just trying logs `exp` props to Amplitude, and there is no `exp.notification`

![image0](https://user-images.githubusercontent.com/12751435/59124215-4f91f080-8989-11e9-8935-aba879c289cc.png)

![image](https://user-images.githubusercontent.com/12751435/59124236-5e78a300-8989-11e9-82fe-e08e5750d5ed.png)

so, this code was never work:
https://github.com/expo/expo/blob/afc2565d1a385fd32d8957a3706dbfa9921cf5d6/packages/expo/src/launch/withExpoRoot.tsx#L17-L20

I think it related to [this commit](https://github.com/expo/expo/commit/1684b5d543bfd168d577a0be48f87d8210331707), cc: @sjchmiela 

https://github.com/expo/expo/blob/41fff1e6afd0e8f36481b5ea9cceeff7258b0ba0/ios/Exponent/Kernel/Services/EXUserNotificationManager.m#L18-L25

**Comment by sjchmiela** [comment]
Could you try SDK33? The supposedly fixing commit you have referenced landed in this release. 🙂

**Comment by giautm** [comment]
Hi @sjchmiela, Is it was fixed in SDKv33? I will trying to upgrade my app to SDKv33

**Comment by sjchmiela** [comment]
The commit you have linked (https://github.com/expo/expo/commit/1684b5d543bfd168d577a0be48f87d8210331707) should have fixed this bug. It is present in SDK33, so your app on SDK33 shouldn't have this problem.

**Comment by giautm** [comment]
Yah, thank you very much. Because, I can't found issue #3410 in any release note. 😄
