### ISSUE TITLE
Google Sign In isOfflineEnabled returns null refreshToken

### ISSUE THREAD

**Issue by jordan-thenumber** [expo/expo#4489]
### Environment

  Expo CLI 2.18.7 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.3 AI-162.3871768
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.7 => 3.5.1
    npmGlobalPackages:
      expo-cli: 2.18.7

Android standalone

### Steps to Reproduce

```
  initGoogleSignIn = async () => {
    try {
      const user = await GoogleSignIn.initAsync({
        clientId: <AndroidClientID>,
        webClientId: <WebClientID>,
        scopes: ['https://www.googleapis.com/auth/calendar.events'],
        isOfflineEnabled: true,
      })
    } catch ({ message }) {
      alert('GoogleSignIn.initAsync(): ' + message)
    }
  }
  googleSignIn = async () => {
    try {
      await GoogleSignIn.askForPlayServicesAsync()
      const { type, user } = await GoogleSignIn.signInAsync()
      if (type === 'success') {
        alert(JSON.stringify(user))
      }
    } catch ({ message }) {
      alert('login: Error:' + message)
    }
  }
```
### Expected Behavior

Expected to get a valid `refreshToken` from `signInAsync`

### Actual Behavior

returned object contained a `null` `refreshToken`

### Reproducible Demo

This requires google oAuth credentials to reproduce which I cannot provide for security reasons.

**Comment by cruzach** [comment]
[Relevant forum post](https://forums.expo.io/t/google-sign-in-isofflineenabled-in-standalone-app/23455)

**Comment by jordan-thenumber** [comment]
@cruzach lol that's my post. would appreciate feedback on my latest post!

**Comment by cruzach** [comment]
I know! Just posting here so that the engineer assigned can get the whole story in one place 😄

**Comment by jordan-thenumber** [comment]
@cruzach i see. ;) I wasn't sure whether to file it as a bug originally but it seems that is the case.

**Comment by jordan-thenumber** [comment]
@EvanBacon After upgrading to SDK 33 I see there was a bugfix which correctly uses the `isOfflineEnabled` option. The resulting auth object still returns a `null` `refreshToken` but it now returns a valid `serverAuthCode` to exchange for a `refreshToken`. Perhaps an update to the docs would clear this up a bit.

**Comment by zolrath** [comment]
This is causing me issues as well, is there a good document describing how to get around this issue?

**Comment by jordan-thenumber** [comment]
@zolrath you'll have to manually generate the refresh token via the google oAuth api. 
https://developers.google.com/identity/protocols/OAuth2InstalledApp#exchange-authorization-code

**Comment by zolrath** [comment]
@jordan-thenumber I've been trying that method for the past few days and ended up with a bit of an opaque error code.
 Performing a `POST https://www.googleapis.com/oauth2/v4/token?code=${serverAuthCode}&grant_type=authorization_code&client_id=${clientID}`

The clientID is the same as the initial request which grants me the serverAuthCode.
It's set up with an OAuthClient for Android so it doesn't require a secret.

Google responds with a JSON response containing a 401. The "data" field is:
`{"error": "unauthorized_client", "error_description":"Unauthorized"}` which is not the most descriptive error I've ever seen.

I'm sure my clientId being passed is the same as the one succesfully logging in and from what I can tell the grant_type and serverAuthCode match what I would expect. 

Starting to go a bit mad!

**Comment by jordan-thenumber** [comment]
@zolrath are you sure you don't need the `client_secret`? from the documentation it looks like it's required.

**Comment by zolrath** [comment]
@jordan-thenumber According to the description of the client secret 

> The client secret obtained from the API Console. This value is not needed for clients registered as Android, iOS, or Chrome applications.

So that part should be optional.  I'm using the same clientId without a secret via the initial google sign in to get the serverAuthCode and the oAuth2 client made for the android client doesnt actually have a secret.

**Comment by zolrath** [comment]
Got it! It seems, despite being an Android project etc the GoogleSignIn usese the Web ClientId.
I input a web based OAuth2 client_id/client_secret and it worked!

@jordan-thenumber Thanks for making me question that aspect, I was hung up on using the Android client_id!

**Comment by jordan-thenumber** [comment]
@zolrath ah right of course. unfortunately it's not well documented but very important to note.

**Comment by davidli3100** [comment]
Can you access the user's accesstoken and idtoken as well? Me and a few other people are having issues accessing those with the GoogleSignIn library

**Comment by esamelson** [comment]
Hi, I'm going to go ahead and close this issue since it's been inactive for a while. I've updated the docs based on the comments above. Please feel free to open a PR updating the docs whenever you find missing information or inaccuracies in there!
