### ISSUE TITLE
Expokit - IOS cannot install react-native-firebase due to incompatible GoogleUtilities

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#4493]
```EXFaceDetector``` ->  ```GoogleMobileVision/FaceDetector``` -> ```GoogleMobileVision/Detector```
```
  - GoogleMobileVision/Detector (1.1.0):
    - GoogleInterchangeUtilities (~> 1.2)
    - GoogleNetworkingUtilities (~> 1.2)
    - GoogleUtilities (~> 1.3)
```

```GoogleMobileVision/Detector``` require ```GoogleUtilities (~> 1.3)```and ```'Firebase/Core', '~> 5.20.1'``` require ```GoogleUtilities (->5.8.0)```

Because of this, after ```pod install```, ```GoogleUtilities``` is broken which cause 
compile error ```'GoogleUtilities/GULAppEnvironmentUtil.h file not found``` in ```FirebaseCore```

**Comment by tsapeta** [comment]
For now we can only recommend to exclude `expo-face-detector` from your project. You can do this using `exclude` option in `use_unimodules` method in your Podfile. It's now documented, you can check out PR adding it to the docs: https://github.com/unimodules/react-native-unimodules/pull/41

**Comment by bogrees** [comment]
This is what I had to modify to get Firebase working for me.

# Install unimodules
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
use_unimodules!(exclude: ['expo-face-detector'])
