### ISSUE TITLE
Splash screen not visible in standalone app after SDK 33 update (Android)

### ISSUE THREAD

**Issue by spyshower** [expo/expo#4498]
### Environment

Expo CLI 2.19.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.1

The splash image is not visible at all. Instead I get the `backgroundColor` specified in `"splash"`. Everything work fine in development or in `--no-dev --minify`
This issue happens on Android standalone app only.

app.json:

```
"splash": {
      "backgroundColor": "#666666",
      "image": "./assets/splash/splash.png",
      "resizeMode": "contain"
    }
```

I have posted this on Expo forums too: https://forums.expo.io/t/splash-screen-not-visible-in-standalone-app-after-sdk-33-update/23579

It blocks my official release so let me know if more info is needed and I will post immediately.

Thanks!

![ezgif-3-60805cd51948](https://user-images.githubusercontent.com/7046283/59146900-8f45f000-89fc-11e9-9a24-0ba37649de62.gif)

**Comment by choco9620** [comment]
Yo tengo el mismo problema, en un dispositivo de Huawei y 7 se logra con normalidad pero en Huawei p20 se ve la pantalla oscura y en el caso de motorola g4 no inicia la aplicación, todo esto en modo standalone

**Comment by choco9620** [comment]
I have the same problem, in a Huawei device and 7 is achieved normally but in Huawei p20 the screen is dark and in the case of Motorola g4 does not start the application, all this in standalone mode

**Comment by francescotimperi** [comment]
I have similar issues after migrating to SDK33 in Android with splash screen. Splash screen is visible @startup but after that a blank screen is showed and sometime the app does not start. In addition the splash screen image does not fit properly in the screen itself. 

Using the expo app i don't face such issue..so i believe it is something related to the SDK33 shell app used for standalone app builds.

**Comment by spyshower** [comment]
Can someone from the Expo team give some input on this one please?

**Comment by jamesbechet** [comment]
Same problem here.

**Comment by JorgeMoralesLopez** [comment]
I also have the same problem in an independent Android application with splash screen, the logo is increased and takes almost the entire screen, also yesterday in tests there were a couple of times that the app did not open. Huawei p9lite

**Comment by francescotimperi** [comment]
I had a similar issue after migration to SDK33. I´m using turtle for build, so I removed turtle/workingDir/android folder to force a new download of shellApp and it solved the problem for me since a couple of days. Give it a try.

**Comment by spyshower** [comment]
@francescotimperi personally I don't use turtle..

**Comment by jamesbechet** [comment]
@spyshower this seems to have been fixed since: https://forums.expo.io/t/expo-sdk-33-android-standalone-build-crashes/23695/20

**Comment by shinhong-codelinkcorp** [comment]
@spyshower are you solved? 
I have the same issue.
    "@expo/samples": "~3.0.0",
    "@expo/vector-icons": "^10.0.1",
    "axios": "^0.19.0",
    "crypto-js": "^3.1.9-1",
    "expo": "^33.0.7",
    "expo-asset": "^5.0.0",
    "expo-constants": "^5.0.0",
    "expo-web-browser": "^5.0.3",
    "immutable": "^4.0.0-rc.12",
    "intl": "^1.2.5",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "qs": "^6.7.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"

![GitHub Logo](http://g.recordit.co/VBpW7NODz2.gif)

After Expo.SplashScreen.hide(), My app should process in SwitchNavigator but it will no be.
