### ISSUE TITLE
BarCodeScanner not scanning ITF codes

### ISSUE THREAD

**Issue by dydx** [expo/expo#450]
Heya,

I've noticed that I can't scan Interleaved Two of Five codes with the built in barcode scanning component (though I am able to scan the same codes with Scandit.

Looking through the code, I see the following

```
+ (NSDictionary *)validBarCodeTypes
{
  return @{
     @"upc_e" : AVMetadataObjectTypeUPCECode,
     @"code39" : AVMetadataObjectTypeCode39Code,
     @"code39mod43" : AVMetadataObjectTypeCode39Mod43Code,
     @"ean13" : AVMetadataObjectTypeEAN13Code,
     @"ean8" : AVMetadataObjectTypeEAN8Code,
     @"code93" : AVMetadataObjectTypeCode93Code,
     @"code138" : AVMetadataObjectTypeCode128Code,
     @"pdf417" : AVMetadataObjectTypePDF417Code,
     @"qr" : AVMetadataObjectTypeQRCode,
     @"aztec" : AVMetadataObjectTypeAztecCode
  #ifdef AVMetadataObjectTypeInterleaved2of5Code
     ,
     @"interleaved2of5" : AVMetadataObjectTypeInterleaved2of5Code
  #endif
  #ifdef AVMetadataObjectTypeITF14Code
     ,
     @"itf14" : AVMetadataObjectTypeITF14Code
  #endif
  #ifdef AVMetadataObjectTypeDataMatrixCode
     ,
     @"datamatrix" : AVMetadataObjectTypeDataMatrixCode
  #endif
  };
}
```
https://github.com/expo/expo/blob/ebbe37b4709320e5c6174f4925a8e8ec9fd8c799/ios/Exponent/Versioned/Modules/Api/Components/EXBarCodeScannerManager.m#L81-L84

Not exactly sure how to verify that `AVMetadataObjectTypeInterleaved2of5Code` is defined, but it seems like its not since its not scanning those codes.

Not 100% sure what to do about this.

**Comment by abi** [comment]
Fixed in SDK 20. Thanks for reporting, @dydx
