### ISSUE TITLE
[jest-expo] wrong mock of expo-file-system with individual import since SDK 33

### ISSUE THREAD

**Issue by colinux** [expo/expo#4503]
### Environment

 Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.3 => 33.0.3
      react: 16.8.6 => 16.8.6
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ~3.11.0 => 3.11.0

### Steps to Reproduce

```js
// in a test file
import * as FileSystem from 'expo-file-system'; // new SDK 33 module import syntax

it('should mock downloadAsync', () => {
   expect(FileSystem.downloadAsync('something', 'somewhere')).resolves.toEqual(
     expect.any(Object),
   );
});
```
### Expected Behavior

The test should pass because jest-expo mock `expo-file-system` https://github.com/expo/expo/blob/16d0e12a953584f1d0ecb52f0abf6ae1f2c17c81/packages/jest-expo/src/preset/setup.js#L150

### Actual Behavior

We got this error :
`TypeError: FileSystem.downloadAsync is not a function`
because `expo-file-system` functions are still mocked under the `FileSystem` namespace. The mock has not been updated with the new import syntax.

### Fix
The fix would remove  the `FileSystem` namespace in the mock definition (I'm doing this  in my setup configuration).

I can provide a PR if you want.

By the way it would be great if all async functions were mocked with promise resolutions instead of simple function like the 2 first functions.

**Comment by ThibautGeriz** [comment]
@sjchmiela @tsapeta You fixed the issue and closed the issue but the release `jest-expo` `33.0.2` does not include the patch. Could you release 33.0.3 please?
Thank you
