### ISSUE TITLE
errors in build SDK 33 android

### ISSUE THREAD

**Issue by sweebee** [expo/expo#4505]
I've updated from SDK 32 to 33. It works fine in the expo client and on standalone iOS. But on android i get various errors:

```
TypeError node_modules/expo-font/build/Font.js:91
undefined is not an object (evaluating 'c.default.loadAsync')
```

```
The method or property WebBrowser.openBrowserAsync is not available on android, are you sure you've linked all the native dependencies properly?
```

**Comment by djbuch** [comment]
I’m having the same error !

**Comment by sjchmiela** [comment]
Have you followed the instructions logged when running your application, eg.:?

```
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: Constants, FileSystem, KeepAwake.

1. Add correct versions of these packages to your project using:

   expo install expo-constants expo-file-system expo-keep-awake

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { Constants } from 'expo' -> import Constants from 'expo-constants'
 - import { FileSystem } from 'expo' -> import * as FileSystem from 'expo-file-system'
 - import { KeepAwake } from 'expo' -> import KeepAwake from 'expo-keep-awake'
```

**Comment by djbuch** [comment]
Hello,

after expo install ... it works for me, it was not clear in the docs that this was mandatory as when doing expo init the node packages for expo-font, expo-constants etc... are already installed.

Regards,

**Comment by sweebee** [comment]
got it working: 

```
import * as WebBrowser from 'expo-web-browser'
```

this also fixed the font error.

**Comment by sweebee** [comment]
I'm reopening it. somehow i still have the issue with the fonts on android:

```
TypeError node_modules/expo-font/build/Font.js:91
undefined is not an object (evaluating 'c.default.loadAsync')
```
I'm using:
```
import { Ionicons } from '@expo/vector-icons'

const icon = Platform.OS === 'ios' ? 'ios-settings' : 'md-settings'

<Ionicons name={icon} style={{marginTop: 2}} size={26} color="#fff" />
```

**Comment by brentvatne** [comment]
when did you do the build? on monday we pushed some changes that should resolve this

**Comment by sweebee** [comment]
I will create a new build and check if it works.

**Comment by sjchmiela** [comment]
What version of `@expo/vector-icons` do you have installed? If I remember correctly this problem has been solved in recent versions of this package.

**Comment by sweebee** [comment]
```10.0.2```

**Comment by sweebee** [comment]
it working.

**Comment by iamrommel** [comment]
My case is im always seeing this

````
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: FileSystem.

1. Add correct versions of these packages to your project using:

   expo install expo-file-system

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { FileSystem } from 'expo' -> import * as FileSystem from 'expo-file-system'

````

I already used code-mod and here is the result
````
$ npx expo-codemod sdk33-imports '**/*.js'
Transforming 181 JS files...
Processing 181 files...
Spawning 7 workers...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 25 files to free worker...
All done.
Results:
0 errors
180 unmodified
1 skipped
0 ok
Time elapsed: 2.928seconds
````
Nothing was changed, i looked around my codes manually,  (CTRL + F) and did not find anything similar to ```import { FileSystem } from 'expo' ```

How was the expo is able to detect this? Are there any tools or ways to check which code uses this? I'm really scratching my balls for a couple of day just looking for this issue.

**Comment by sjchmiela** [comment]
Your description, @iamrommel, suggests that one of your dependencies may import `FileSystem` from `'expo'`. 🙂

**Comment by iamrommel** [comment]
That is problem that expo team i think should reconsider, what if one if my dependency module does update, then that it means i cannot also update my project, furthermore as stated on the comments above, at least the expo cli should tell which file whether it  came from the dependency modules got problem. I been scratching my balls for several days now looking where is the offensive file/module.
