### ISSUE TITLE
[expo-linear-gradient][Bare] Unable to use expo-linear-gradient

### ISSUE THREAD

**Issue by leesiongchan** [expo/expo#4509]
### Environment

Bare Workflow LinearGradient Unimodule Android

### Steps to Reproduce

Use LinearGradient like what the documentation has guided and got below error message

```
null is not an object (evaluating 'NativeUnimoduleProxy.viewManagerNames')
requireNativeViewManager
index.delta?platform=android&dev=true&minify=false:126006:32
...
``` 

### Expected Behavior

Should work as expected

### Actual Behavior

Got error

```
null is not an object (evaluating 'NativeUnimoduleProxy.viewManagerNames')
requireNativeViewManager
index.delta?platform=android&dev=true&minify=false:126006:32
...
```

**Comment by sjchmiela** [comment]
Hey, @leesiongchan! You need to configure your project to use unimodules. Check out [`react-native-unimodules`](https://github.com/unimodules/react-native-unimodules) package to see the instructions. 🙂

**Comment by leesiongchan** [comment]
Sorry, miss out `MainApplication.java`
