### ISSUE TITLE
Feature request: Support for multiple deployments/publish (stage, test, prod, etc)

### ISSUE THREAD

**Issue by timbrandin** [expo/expo#451]
When having one app in the AppStore, we don't want to update (OTA) the app for everyone when we're testing out new features, we want to publish it to another slug (preferably through CI). Right now I can't find an easy way to keep multiple configurations for expo publishing with different slugs.

One solution would be to pass a relative application path to the app.json file, with that I can keep multiple deployments in a folder structure like below and I can decide when to deploy to which deployment. Now I have to manually modify the slug of the app to circumvent the behaviour of: one deployment rules them all.

APP_ROOT/.deploy/stage
```
{
  "expo": {
    "name": "ExampleApp",
    "path": "../../",
    "slug": "exampleapp-stage",
    "sdkVersion": "19.0.0",
    "orientation": "portrait",
    "icon": "./icon.png",
    "version": "1.0.0",
    "ios": {
      "bundleIdentifier": "com.company.exampleapp",
      "icon": "./icon.png"
    }
  }
}
```

APP_ROOT/.deploy/test
```
{
  "expo": {
    "name": "ExampleApp",
    "path": "../../",
    "slug": "exampleapp-test",
...
```

APP_ROOT/.deploy/prod
```
{
  "expo": {
    "name": "ExampleApp",
    "path": "../../",
    "slug": "exampleapp",
...
```

From this I can just `cd .deploy/stage && exp publish` to publish to stage.

I hope you like this idea, it is inspired by how Meteor Up (mup) allows you to store it's configuration for multiple deployments.

**Comment by dikaiosune** [comment]
Hi! We have a [feature request](https://expo.canny.io/feature-requests/p/support-multiple-release-channels) for this currently. We have some plans, not sure exactly when it'll be available.

**Comment by timbrandin** [comment]
Awesome!!
