### ISSUE TITLE
[lottie-react-native][Android][sdk-33] Not every Lottie animation works on Android v9 in Expo v33

### ISSUE THREAD

**Issue by yaroslavnikiforov** [expo/expo#4510]
### Environment

| software         | version
| ---------------- | -------
| expo | 33.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz
| device    | Android emulator, Redmi note 7
| platform version | 9

<img width="660" alt="Screen Shot 2019-06-10 at 11 47 01 AM" src="https://user-images.githubusercontent.com/42115630/59183859-8cbad600-8b75-11e9-8880-c473d5771ba2.png">

### Steps to Reproduce

Some Lottie animations stopped working on Android 9 after updating to expo v33.  It worked fine on v32. Everything works on iOS and lower Android versions.

### Expected Behavior

Animations that work on iOS and previous Android versions should work on Android 9.

### Actual Behavior

App crashes every time you try to open it, if it has some of not supported by Android version 9 animations. On Android version 8 app works fine.

### Reproducible Demo

It works on android in https://snack.expo.io/@git/github.com/yaroslavnikiforov/lottie-example. So this is the demo repository on Github:

https://github.com/yaroslavnikiforov/lottie-example

In this demo, there are two examples of animations (animation1.json and animation2.json). First one doesn't work on Android 9.

**Comment by sjchmiela** [comment]
Is something special about the first animation that it can't work? Have you looked into the `lottie-react-native` or `lottie-android` repositories in search for other issues like that? The only thing I could easily find was this commit — https://github.com/react-native-community/lottie-react-native/commit/d2147e9faa9fcc2995bb26e4602c5e793f81877d, which set `lottie-android` version to `2.5.6` (we use `2.5.5` at Expo, maybe we should bump the patch?)

**Comment by serhiipalash** [comment]
Hi @sjchmiela ! Please bump the patch, maybe it will help. If you can explain how to do it manually in expo module source code, we can try and test it ourself.

**Comment by sjchmiela** [comment]
To test it yourself, please eject and edit `android/app/build.gradle` manually, updating lottie 2.5.5 to 2.5.6. Then run the native application and verify if it works. 🙂 Let me know if you'll do it!

**Comment by serhiipalash** [comment]
Need to update my Android Studio. I'll try it in the evening and let you know.

**Comment by yaroslavnikiforov** [comment]
@sjchmiela nothing special about the first animation. I tested a few examples and some of them work, some not.

Just ejecting to 'plain' React Native project helped, without updating Lottie in android/app/build.gradle. 
Steps:
1) run 'expo eject'
2) run 'rm -rf node_modules'
3) run 'npm i'
4) add 'local.properties' file in 'android' folder and specify the local path to Android Studio SDK:
for mac:
  sdk.dir = /Users/yaroslav/Library/Android/sdk
for windows:
  sdk.dir=C\:\\Users\\UserName\\AppData\\Local\\Android\\sdk
5) run 'export PATH=$PATH:~/Library/Android/sdk/platform-tools/' (for window specify another path)
6) run 'react-native link'
7) open Android emulator
8) run 'react-native run-android'

I created a branch in the demo repository with an ejected project:
https://github.com/yaroslavnikiforov/lottie-example/tree/ejected-to-plain-react-native

All animations already work there on Android v9

**Comment by frapporti** [comment]
This is a pretty serious bug. We are in need to send out an urgent update for an app that uses Lottie extensively, but it crashes badly on Android 9. And unfortunately we use expo notifications.
Any pointer on how to patch without ejecting would be great.

**Comment by sjchmiela** [comment]
We will address this issue on Monday. I think it would be safe to say it should be fixed by thr end of the day CEST.

**Comment by maxtuzz** [comment]
@sjchmiela Great to hear! Patiently waiting :)

**Comment by sjchmiela** [comment]
In a couple of minutes apps rebuilt with Turtle should have this bug fixed. On to deploy fixed version of Expo Client!

**Comment by serhiipalash** [comment]
Great work! Thank you @sjchmiela !

**Comment by frapporti** [comment]
Impressive reaction speed, thank you!

**Comment by yaroslavnikiforov** [comment]
@sjchmiela thanks for a quick fix

**Comment by tonnenpinguin** [comment]
Sorry for resurrecting this. Our app still crashes on Android 8 and 9 with certain animations.

I've created a snack that reproduces this consistently: https://snack.expo.io/@fittrack/tenacious-blueberries

**Comment by digitalsleep** [comment]
Hey Sorry also for adding to this but we are currently experiencing this.  I just wanted to confirm do we need to detach the expo project to bump this version? or was this fixed in expo ?

**Comment by developperReact** [comment]
have same issue , worked only on IOS and for ANDROID expo app still closed  ,someone help me please 
"expo": "^34.0.1" 
"lottie-ios":"2.5.0" 
 "lottie-react-native":"2.6.1"
