### ISSUE TITLE
[SDK33][Android] Standalone build failed!

### ISSUE THREAD

**Issue by ru88s** [expo/expo#4516]
## 🐛 Bug Report
Fail on Android build.
Only me?

### Environment
  Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.19.4

![スクリーンショット 2019-06-10 13 02 45](https://user-images.githubusercontent.com/42270511/59171868-25eeea00-8b80-11e9-90c9-180dea812583.png)

**Comment by ru88s** [comment]
It is a build log.
<img width="1005" alt="スクリーンショット 2019-06-10 13 18 12" src="https://user-images.githubusercontent.com/42270511/59172319-56378800-8b82-11e9-94da-6d9dff459b58.png">

**Comment by tsapeta** [comment]
We've just fixed this on our builders, could you try building it again? Let me know how it goes 🙃

**Comment by ru88s** [comment]
Succeeded!
Thank you very much!😊

**Comment by ru88s** [comment]
It became to fail.

![スクリーンショット 2019-06-11 17 16 07](https://user-images.githubusercontent.com/42270511/59256262-8eb49000-8c6e-11e9-80a8-2553c37e8ce8.png)
<img width="1197" alt="スクリーンショット 2019-06-11 17 31 57" src="https://user-images.githubusercontent.com/42270511/59256405-d89d7600-8c6e-11e9-9c3d-fed02ccdb4f6.png">
