### ISSUE TITLE
exp(o) no longer seems to resolve modules in parents?

### ISSUE THREAD

**Issue by gre** [expo/expo#452]
It's kinda weird issue and i'm not 100% sure yet if what i'm reporting is correct but I feel I'm currently experimenting a regression: an expo app I have among other projects using lerna no longer resolve dependencies that are "hoisted" by lerna.
I might be wrong but I think this used to work (like < 1 month ago), (my app is https://github.com/gre/gl-react/tree/master/packages/cookbook-expo )

basically, for instance,

if I have `node_modules/prop-types`, my app at `packages/expo-app` no longer will resolve the `prop-types` lib as relatively `../../node_modules/prop-types` if it's not in `packages/cookbook-expo/node_modules` – like a normal node/webpack project do.

now maybe this is a bug in React Native packager instead? but basically I have this error: `Unable to resolve module 'prop-types' from $PWD/packages/coobook-expo/node_modules/react-native-maps/lib/components/MapView.js: Module does not exist in the module map or in these directories: $PWD/node_modules` (NB: actually it **does** exist in this directory –_–)

**Comment by satya164** [comment]
Packager never supported it AFAIK unless you specify a custom root.

**Comment by terribleben** [comment]
I'm not positive this was ever supported, but I'm fairly certain it's not supported today. It would be something to take up with the metro folks upstream. Sorry for the slow response.
