### ISSUE TITLE
expo detach doesn't read create-react-native-app's app.json same way as exp.json

### ISSUE THREAD

**Issue by dikaiosune** [expo/expo#453]
from https://github.com/expo/xdl/issues/15:

From creating the project through `create-react-native-app my-app`, I get a file `app.json` which holds the following contents:
```json
{
  "expo": {
    "sdkVersion": "19.0.0"
  }
}
```

Running `exp detach`, I get the error 
`app.json is missing android.package field. See https://docs.expo.io/versions/latest/guides/configuration.html#package` and no ios nor android directories seem to be downloaded. So, I add in android.package.

```json
{
  "expo": {
    "sdkVersion": "19.0.0"
  },
  "ios": {
     "bundleIdentifier": "org.bob",
   },
   "android": {
     "package": "org.bob",
   }
}
```

I receive the same error.

Looking through the code, I notice the program spits out this default json instead of my app.json:
```json
{
   "sdkVersion":"19.0.0",
   "name":"my-app",
   "slug":"my-app",
   "version":"0.1.0"
}
```

There also seems to be lines of code in `xdl/src/project/ProjectUtils.js`:
```javascript
    if (configName === 'app.json') {
      // if we're not using exp.json, then we've stashed everything under an expo key
      // this is only for app.json at time of writing
      exp = exp.expo;
    }
```

Since `exp detach` allows the use of `app.json`, the file outputted by `create-react-native-app`, should `app.json` be expected to be the same structure as `exp.json`, or should there be documentation that states that `app.json` should be reformatted?

**Comment by ranvir-gorai** [comment]
Use This Structure 

{
 "expo": {
    "name": "My app",
    "slug": "my-app",
    "sdkVersion": "22.0.0",
    "privacy": "public",
    "ios": {
      "bundleIdentifier": "org.test"
    },
    "android": {
      "package": "org.test"
    }
  }

Works For me

**Comment by dikaiosune** [comment]
@ranvir-gorai thanks! This was an issue with how we process these files, not with my specific project. I suspect that this has changed since (it was migrated from another repository), so I'll close this and reopen if we discover it happens again.

**Comment by inform880** [comment]
For anyone who happens upon this issue, when you get this error try using 
`exp detach --config "path\to\files\"`

I just spent 3 hours getting this error trying to do this, and I feel like I lucked out.

**Comment by tidelake** [comment]
I'm coming directly to expo w/o react experience. What is the `path\to\app.json` normally?
