### ISSUE TITLE
expo-yarn-workspaces unable to resolve module `./__generated__/AppEntry`

### ISSUE THREAD

**Issue by GlynL** [expo/expo#4531]
## 🐛 Bug Report

Error when trying to open app. Have tried in android studio and on android phone w/ qr code.

### Environment

Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.10.1 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-183.6156.11.34.5522156

### Steps to Reproduce

create yarn workspace 
expo init to create app inside packages as a workspace.
install expo-yarn-workspaces and follow setup guide.
npm start

### Expected Behavior

opens app

### Actual Behavior

doesn't open and errors.

Error: Unable to resolve module `./__generated__/AppEntry` from `C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile/.`: The module `./__generated__/AppEntry` could not be found from `C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile/.`. Indeed, none of these files exist:
  * `C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\__generated__\AppEntry(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\__generated__\AppEntry\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\node_modules\metro\src\lib\transformHelpers.js:261:42
    at Server.<anonymous> (C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\node_modules\metro\src\Server.js:1038:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\node_modules\metro\src\Server.js:99:24)
    at _next (C:\Users\glyn_\Documents\Coding\Play\monorepo\packages\mobile\node_modules\metro\src\Server.js:119:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### Reproducible Demo

https://github.com/GlynL/monorepo

**Comment by ide** [comment]
expo-yarn-workspaces is currently not supported outside of this repo. I suspect your issue is that you don't have the postinstall script set up (did you follow https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces#add-a-postinstall-script-to-packagejson to a T?).

**Comment by GlynL** [comment]
@ide yeah I followed it to a T. And recreated it a second time in the demo I made. https://github.com/GlynL/monorepo

Is it not supported as in, it's just for making expo work? Not designed for use in expo projects?

**Comment by ide** [comment]
Correct; some people have gotten it working in their own projects but it is self-service.

**Comment by GlynL** [comment]
thanks, sorry I came across a link recommending it and didn't realise.

**Comment by slorber** [comment]
Just giving this info if anyone pass by... I had this exact error in an Expo app that was working fine, just after having attempted to contribute to Expo client app (on my forked repo: launching code in expo/home). My totally unrelated app refused to package for unknown reasons. I tried clearing node modules, metro cache, reinstalled the expo client, reboot etc and it didn't work, but it seems deleting the .expo at the root of my project may have helped fix it. Just giving this info if anyone pass by...

**Comment by revgum** [comment]
Also leaving this for others to find.. it wasn't immediately obvious to me, but I had to `yarn postinstall` in the Expo app directory so that the `__generated__` folder and code was created.
