### ISSUE TITLE
How can i remove ‘SYSTEM_ALERT_WINDOW’ from app permissions?

### ISSUE THREAD

**Issue by alibabaei69** [expo/expo#4535]
i want to remove ‘SYSTEM_ALERT_WINDOW’ from app permissions from expo but there is not any way,please help me!

**Comment by AdamJNavarro** [comment]
Hey @alibabaei69,

We try to reserve github issues for bug reports. I see you already made a post on the forums so we'll follow up with you there.

Cheers,
Adam
