### ISSUE TITLE
App data files not moved to new location when upgrading SDK31->SDK33

### ISSUE THREAD

**Issue by martin-ecatch** [expo/expo#4537]
## 🐛 Bug Report
This happens on Android standalone app (haven't tested iOS yet).
An app (SDK31) using SQLite creates a database in:
/data/…/files/ExperienceData/app-slug-perhaps/SQLite
When the app is upgraded to SDK33, it ignores the old database and creates a new database in:
/data/…/files/SQLite
virtually losing all data on the upgrade.
Screenshot of the filesystem in the discussion here [https://forums.expo.io/t/cannot-upgrade-to-sdk33-sqlite-files-location-changed/23702](https://forums.expo.io/t/cannot-upgrade-to-sdk33-sqlite-files-location-changed/23702)

Looking at [https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java) it seems like it is supposed to move the old data directory to the new location, but it doesn't seem to be working.

### Environment
Android 8 emulator
Samsung S5 mini

### Steps to Reproduce
1. In SDK31 project build standalone app for Android that creates a SQLite database.
2. Upgrade to SDK33, build standalone app for Android and run it -> the SQLite database from previous step is inaccessible.

### Expected Behavior
The database needs to be moved to the new location and reused by the upgraded SDK33 app.

### Actual Behavior
Existing SQLite database is inaccessible, new empty one is created.

### Reproducible Demo
Step 1:
Use the official SQLite example, use an older commit (this one is SDK30, but that's good enough for this example): [https://github.com/expo/sqlite-example/commit/65ad89bca6fe7e93080135d9ccf7694c922ae522](https://github.com/expo/sqlite-example/commit/65ad89bca6fe7e93080135d9ccf7694c922ae522)
add to app.json
    "android": {
      "package": "sqlite.example",
      "versionCode": 1
    },

npm i
expo build:android
and put the app on your device/emulator.

Step 2:
Run the app and add a few items to the database

Step 3: upgrade project to SDK33
in app.json change:
    "sdkVersion": "33.0.0",

in package.json change dependencies:
    "expo": "^33.0.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

npm i
expo build:android
and put the app on your device/emulator

Step 4: run the app and viola! Your previously entered tasks are gone.

**Comment by martin-ecatch** [comment]
@Szymon20000 Have you been able to reproduce the problem using my description? Let me know if there's anything else I can do to help. This is quite critical and I suspect it's not limited to just SQLite, but any files that the app stores locally would be inaccessible after upgrade.
I'm actually a little bit surprised by the quietness here... Am I the only person using SQLite with Expo? Strange!

**Comment by ericluong** [comment]
I am also facing the same issue. I am storing some images and videos in the appdata folder and cannot access it after the upgrade (SK31 to 33).

Will try the FileSystem API to copy the directory myself on app launch if no solution is offered quickly.

**Comment by Slapbox** [comment]
Same issue. It's not documented that there was even a change to this that I've seen, even though it is 100% breaking. Can anyone on the team speak to this?

**Comment by martin-ecatch** [comment]
Ok, looks like I'll have to move the files in my app. Can somebody please confirm these two questions?
1. The old location looks like ExperienceData/@username-slug url encoded (%40username%2Fslug). Is that always correct regardless of android version, release channel, etc?
2. Is it the same on iOS or does it work differently?
Thanks for help!

**Comment by martin-ecatch** [comment]
Ok, so I finally did it. Moved the data myself. If anybody is doing the same thing, beware of some gotchas:
On Android the URI is "ExperienceData/%2540username%252Fslug/" - you'll need to URL encode the %40 and %2F!
On iOS the URI is "ExponentExperienceData/%2540username%252Fslug/", but it actually seems to not be a problem on iOS. The files were moved automatically.

Then it was just a simple case of FileSystem.moveAsync call to move all app data files.

**Comment by ericluong** [comment]
Here is how I migrated my files on Android.

The old location was:
file:///data/user/0/com.bundle/files/ExperienceData/%2540username%252Fslug/

The new location is:
file:///data/user/0/com.bundle/files/

In this example, I had the move the `images` folder.
This code is being run on app launch in a generator.

```
const fromDirectory = `${FileSystem.documentDirectory}ExperienceData/%2540username%252Fslug/images`;
const toDirectory = `${FileSystem.documentDirectory}images`;

const fromDirectoryInfo = yield call(FileSystem.getInfoAsync, fromDirectory);
const toDirectoryInfo = yield call(FileSystem.getInfoAsync, toDirectory);

if (!fromDirectoryInfo || !fromDirectoryInfo.exists) return; // old directory must exist
if (toDirectoryInfo && toDirectoryInfo.exists) return; // new directory must not exist

try {
    yield call(FileSystem.copyAsync, {
        from: fromDirectory,
        to: toDirectory,
    });
} catch (e) {
   // Do something
}
```

**Comment by onizam95** [comment]
hey @martin-ecatch  can you please share your code. I am not able to resolve it. here's my code 


 async moveDB() {

        fromDirectory = `${FileSystem.documentDirectory}ExperienceData/%2540owais.nizam%252FReferralAppProduction/SQLite`;
        toDirectory = `${FileSystem.documentDirectory}SQLite`;
        let [fromDirectoryInfo,toDirectoryInfo] = await Promise.all([FileSystem.getInfoAsync(fromDirectory, {}), FileSystem.getInfoAsync(toDirectory, {})])
        // fromDirectoryInfo = await FileSystem.getInfoAsync(fromDirectory, {});

        // toDirectoryInfo = await FileSystem.getInfoAsync(toDirectory, {});

        console.log("================")
        console.log(fromDirectory)
        console.log("================")

        console.log(toDirectory)
        console.log("================")

        console.log(fromDirectoryInfo)
        console.log("================")

        console.log(toDirectoryInfo)

        if (!fromDirectoryInfo || !fromDirectoryInfo.exists) return; // old directory must exist
        if (toDirectoryInfo && toDirectoryInfo.exists) return; // new directory must not exist
        console.log("================")

        console.log("here for the update")
        try {
           await  FileSystem.copyAsync, {
                from: fromDirectory,
                to: toDirectory,
            };
        } catch (e) {
            console.log(e + "here")
        }
    }

**Comment by martin-ecatch** [comment]
I wonder if you also need to url-encode the '.' in your username 'owais.nizam' => 'owais%2Enizam'. Use the filesystem explorer to check the actual path on your device/emulator. If it has a dot '.' in the name, I'd try %2E and if it has %2E you'd also need to url-encode the % so it'll become 'owais%252Enizam'.
This is how I do it:
```
import * as FileSystem from 'expo-file-system';

const oldPaths = [
  "ExperienceData/%2540expoUsername%252FappName/",
  "ExponentExperienceData/%2540expoUsername%252FappName/",
];

export default async function moveDataFiles() {
  const newUri = FileSystem.documentDirectory + "SQLite";
  var info = await FileSystem.getInfoAsync(newUri, {});
  if (info.exists) {
    console.log("New location already exists.");
    return;
  }

  // try to move the SQLite directory from one of the old locations
  for (let index = 0; index < oldPaths.length; index++) {
    var path = oldPaths[index];
    var oldUri = FileSystem.documentDirectory + path + "SQLite";
    info = await FileSystem.getInfoAsync(oldUri, {});
    if (info.exists) {
      console.log("moving " + oldUri);
      await FileSystem.moveAsync({
        from: oldUri,
        to: newUri,
      });
      console.log("moved " + oldUri);
      return;
    }
  }
}
```

**Comment by onizam95** [comment]
sure let me try. Although i just fetched the whole data from server on app start now in case there is no DB as we were a bit rushed over here (some tight release deadlines). But i'll let you know thanks for your concern.

P.S: don't you think it should be a part of expo SDK 33 by default?

**Comment by atominvention** [comment]
still having this upgrade issue on expo sdk 34, is anyone in the Expo team notified about this issue?

**Comment by Jomik** [comment]
I am surprised that there has not been any response on this issue, even though it persists over two releases and is completely breaking. :-1:

**Comment by gunaangs** [comment]
I am also facing the same issue from SDK32 to SDK34.
I don't know how to handle it.
I lost my whole data:(

**Comment by martin-ecatch** [comment]
@gunaangs unfortunately you'll have to handle it yourself. Fortunately there's example code in the previous comments. It's not lost, it's just in the wrong place so just move the files to the new location and you're done.

**Comment by gunaangs** [comment]
I think this line is wrong

var oldUri = FileSystem.documentDirectory + path + "SQLite";
    info = await FileSystem.getInfoAsync(oldUri, {});

**Comment by Szymon20000** [comment]
Sorry, Guys! I somehow missed this issue. The ScopedContext should move all your files but as it turned out it doesn't work as expected. I found a better approach to moving files on Android. The problem should be fixed soon. I will keep you informed.

**Comment by onizam95** [comment]
thanks. waiting for it

**Comment by esamelson** [comment]
Hey everyone, we're really sorry about this issue and that it's gone unanswered for so long. SDK 36 is out now and should provide a solid path forward here. When you update your standalone app to SDK 36 or above, it will:
- attempt to copy individual files from the legacy directory, if it exists, into the new (unscoped) directory
- if a naming conflict exists (i.e. if your app has recreated your files in the unscoped directory), it will NOT overwrite
- leave the legacy directory alone and not delete it (in case you use the workaround people have suggested above which includes hardcoding the scoped directory name into your application code)
- provide a `FileSystem.deleteLegacyDocumentDirectoryAndroid` method to delete the legacy directory, in case you don't use it and you have a lot of files that might be taking up space on the user's device.

We've designed this so that whichever way you've worked around this issue in the past, you shouldn't have to change anything in your application code to keep things working. However, if you are hardcoding the scoped directory name into your application code, we recommend that you stop doing that in SDK 36 as the upgrade should handle this properly now. We also highly suggest testing upgrading your standalone app before releasing a new build.

Again, we apologize for not making this path as smooth as it could have been, but I hope it's smooth going forward. I'm going to close this issue now but please comment here and ping me if you have questions or continue to run into issues moving forward. Thanks all!
