### ISSUE TITLE
Pressing on "Done" on Google.logInAsync results in broken promise

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#454]
Pressing "Done" before logging in (in 'web' behavior) results in a broken promise, but it should return an object with `{type: 'cancel'}` like the facebook implementation does.

Using expo 19

![simulator screen shot aug 4 2017 12 31 07 pm](https://user-images.githubusercontent.com/1566400/28977629-cde56416-7910-11e7-83ce-a29c59272b0a.png)

**Comment by JulianKingman** [comment]
In the meantime I did this:
```javascript
const loginResponse = await new Promise((resolve, reject) => {
      Google.logInAsync({
        behavior: "web",
        scopes: ["openid", "profile", "email"],
        iosClientId: googleId
      })
        .then(response => {
          resolve(response);
        })
        .catch(err => {
          resolve({type: 'cancel'});
        });
    });
```

**Comment by marstankev** [comment]
Same issue here, cancelling a login results in a `Google sign in error` instead of a object with `type: 'cancel'` returned as expected.
