### ISSUE TITLE
[android] Localization.country return country part of locale instead of region

### ISSUE THREAD

**Issue by vasyas** [expo/expo#4540]
### Environment
```
  Expo CLI 2.18.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.0 => 32.0.0 
      @types/react: ^16.8.1 => 16.8.1 
      @types/react-native: ^0.57.32 => 0.57.32 
      expo: ^32.0.0 => 32.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.18.4
```

Android 6.

### Steps to Reproduce

I use `Localization.country` from `expo-localization` to get the user's country. 

I expect this field to return the configured country. For example, when configuring Region as in the following screenshot from the Android preferences, "UK" should be returned indicating Ukraine: 
![preferences region](https://api.monosnap.com/file/download?id=d7qh7WBPCepTkoLnrH83V7I0Chz5xk).

Instead, I get part of the configured locale. For example, when the locale is set to English (US), as on the following screenshot, I get US as country. 
![preferences locale](https://api.monosnap.com/file/download?id=BgtIurvFQy7zoHgDxWP6xTRSzDiilV)

On iOS it works as expected, returning country.

**Comment by ide** [comment]
Could you please provide more detail?

**Comment by vasyas** [comment]
@ide Added more details & screenshots to the description.
