### ISSUE TITLE
bare workflow build fail expo-facebook 

### ISSUE THREAD

**Issue by shcheuk** [expo/expo#4547]
### Environment

 Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.15.4

     other: pod:1.7.1

iOS with expo init -t bare-minimum

podfile
```
Using DoubleConversion (1.1.6)
Using EXAppLoaderProvider (5.0.1)
Using EXConstants (5.0.1)
Using EXFacebook (5.0.1)
Using EXFileSystem (5.0.1)
Using EXPermissions (5.0.1)
Using FBSDKCoreKit (5.0.2)
Using FBSDKLoginKit (5.0.2)
Using Folly (2018.10.22.00)
Using React (0.59.8)
Using UMBarCodeScannerInterface (2.0.1)
Using UMCameraInterface (2.0.1)
Using UMConstantsInterface (2.0.1)
Using UMCore (2.0.1)
Using UMFaceDetectorInterface (2.0.1)
Using UMFileSystemInterface (2.0.1)
Using UMFontInterface (2.0.1)
Using UMImageLoaderInterface (2.0.1)
Using UMPermissionsInterface (2.0.1)
Using UMReactNativeAdapter (2.0.1)
Using UMSensorsInterface (2.0.1)
Using UMTaskManagerInterface (2.0.1)
Using boost-for-react-native (1.63.0)
Using glog (0.3.5)
Using yoga (0.59.8.React)
```
package.json
```
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo-facebook": "^5.0.1",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-unimodules": "0.4.0"
  },
  "devDependencies": {
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.52.0",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

```

### Steps to Reproduce
open terminal in a mac 
expo init --template bare-minimum
(enter the project name e.g. issue4547)
(enter the display name e.g. issue4547)
(enter y to use yarn)
cd issue4547
yarn add expo-facebook
cd ios
pod install
cd ../
yarn ios

### Expected Behavior

build success

### Actual Behavior

build failed , message in console:
** BUILD FAILED **

The following build commands failed:
```
        CompileC /Users/user/Documents/expobare/expofbbug/ios/build/expofbbug/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/EXFacebook.build/Objects-normal/x86_64/EXFacebook.o /Users/user/Documents/expobare/expofbbug/node_modules/expo-facebook/ios/EXFacebook/EXFacebook.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at ChildProcess.buildProcess.on.code (/Users/user/Documents/expobare/expofbbug/node_modules/@react-native-community/cli/build/commands/runIOS/runIOS.js:231:16)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:197:13)
    at Pipe._handle.close (net.js:611:12)
error Command failed with exit code 1.
```
in xcode workspace
<img width="632" alt="Screen Shot 2019-06-12 at 12 35 44 AM" src="https://user-images.githubusercontent.com/2862630/59290121-69de0e00-8caa-11e9-893e-62f12eec456f.png">
<img width="955" alt="Screen Shot 2019-06-12 at 12 36 58 AM" src="https://user-images.githubusercontent.com/2862630/59290134-719db280-8caa-11e9-9c93-cfb3b3642645.png">

### Reproducible Demo

unable to create demo as it can't even build, but it can easily be reproduce by doing:

open terminal in a mac 
expo init --template bare-minimum
(enter the project name e.g. bug596)
(enter the display name e.g. bug596)
(enter y to use yarn)
cd bug596
yarn add expo-facebook
cd ios
pod install
cd ../
yarn ios

**Comment by malikid** [comment]
+1

**Comment by StefanBurscher** [comment]
+1
Please take my pain away :(

**Comment by denispixi** [comment]
How to get this fix? i create a new project and still get the error :c

**Comment by Amerr** [comment]
have u guys experiencing the same problem in facebook developer account
https://github.com/expo/expo/issues/4701#issuecomment-508193652

**Comment by sjchmiela** [comment]
I think you may be using `use_frameworks!` or modular headers in your `Podfile`, with which Facebook is not compatible at the moment. 😕

**Comment by jafri** [comment]
If expo-facebook is not needed in your project, use:
` use_unimodules!(exclude: ['expo-facebook'])`

**Comment by sjchmiela** [comment]
The compilation fail depends on user configuration in this case. I'll let myself close this issue, if you have any more problems head over to [Expo Slack](https://slack.expo.io/) and try asking the question there. 🙂
