### ISSUE TITLE
Reload app on device

### ISSUE THREAD

**Issue by R3dC0d3** [expo/expo#455]
Hey guys.
I have a feature/suggestion that I think would help everyone that is developing on the device. When I'm testing the app on my device having to pick up the phone and shake it takes up quite some time, and I think that having a setting to display a button on the top corner of your app that would just open the development tools would help us to speed up the process.

Again just a suggestion from someone who had to pick up the phone and "shake" it about 100 times in the past 2 hours :).

**Comment by serranoarevalo** [comment]
I believe you can also use a two finger long press gesture, no? https://blog.expo.io/new-developer-menu-in-expo-for-ios-80d6ba8217f5

**Comment by waynebloss** [comment]
The 2 finger long press doesn't work for me in iOS after enabling it. I tried reloading my app and also restarting Expo.

**Comment by waynebloss** [comment]
It would be nice if there were an API for reloading. Then I could just put a button in my app that only appears at development time and it could call something like `Expo.DevUtil.reload()`.

Obviously there is `Expo.Util.reload()` but that requires you to publish the app.

**Comment by R3dC0d3** [comment]
I was actually doing some research today, i thought there might be an api to allow me to build a button to reload the app.
If it's just after the build doesn't help because then we need to run the build to be able to test...

I also tried the 2 finger long press and didn't seem to work on IOS.

**Comment by terribleben** [comment]
`Expo.Util.reload()` is supported in all situations now, not just published apps.

**Comment by bayudw** [comment]
Hey guys,  i'm new here. i have a problem when i create a project use create react native app use expo. when scan the barcode with my phone, my project can not reaload even though my phone and my laptop in the same connection. 
![20819](https://user-images.githubusercontent.com/33413373/33139945-fb277d74-cf41-11e7-8e00-19dc6f4fcee4.jpg)

**Comment by waynebloss** [comment]
@bayudw This issue is closed. You should ask your question on [The Expo Forum](https://forums.expo.io) or [StackOverflow](https://stackoverflow.com/).
