### ISSUE TITLE
Preloading images

### ISSUE THREAD

**Issue by onselakin** [expo/expo#456]
Hi Expo team,

Below in the screen shot you can see what happens when loading one of my screens. All the images you see on the uniforms are same and they're all loaded as described here: https://docs.expo.io/versions/v19.0.0/guides/preloading-and-caching-assets.html

Although I cached all the images, they still feel like they're loading sequentially, resulting in a very unpolished look. Also it takes almost 5 seconds for all the images to be shown.

Is there anything I can do to show the images all at once without any delays, just like in native apps?

Thank you.

<img width="588" alt="screen shot 2017-08-06 at 9 10 36 pm" src="https://user-images.githubusercontent.com/10635384/29005780-bb19ac16-7aeb-11e7-8a60-0d3756c56d76.png">

**Comment by abi** [comment]
Please ask such questions in the forums or Slack in the future. Are you rendering https://docs.expo.io/versions/v19.0.0/sdk/app-loading.html#app-loading until after your cache promises return?

**Comment by dikaiosune** [comment]
@onselakin as @abi said, this doesn't seem like a bug report. Can you create a minimal reproduction in snack.expo.io and paste it to the forums? Thanks!
