### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.TabBarIOS.Item')

### ISSUE THREAD

**Issue by akbasonder** [expo/expo#4560]
## 🐛 Bug Report
I upgraded my expo from 32.0.0 to 33.0.0. Before I upgraded it, everything worked fine.
Now my app crashes with "undefined is not an object (evaluating '_reactNative.TabBarIOS.Item')" error message. I use react-navigation and I also upgraded it to latest version 3.11.0
Error trace is as follows:

undefined is not an object (evaluating '_reactNative.TabBarIOS.Item')
<unknown>
    tabbar.ios.js:71:37
loadModuleImplementation
    require.js:331:6
<unknown>
    index.native.js:13:22
loadModuleImplementation
    require.js:331:6
<unknown>
    index.native.js:304:22
loadModuleImplementation
    require.js:331:6
<unknown>
    ScreenUtil.tsx:7
loadModuleImplementation
    require.js:331:6
<unknown>
    FriendTab.tsx:10
loadModuleImplementation
    require.js:331:6
<unknown>
    MainBar.tsx:10
loadModuleImplementation
    require.js:331:6
<unknown>
    RootNav.ts:8
loadModuleImplementation
    require.js:331:6
<unknown>
    App.tsx:4
loadModuleImplementation
    require.js:331:6
<unknown>
    AppEntry.js:4
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code
    <unknown file>:0

### Environment

Expo CLI 2.19.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/opt/node@10/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.7.11 => 16.8.19 
      @types/react-native: ^0.57.15 => 0.57.60 
      @types/react-navigation: ^3.0.1 => 3.0.7 
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 

I use ExpoKit an important libraries versions in package.json:
"expo": "^33.0.0",
"expo-secure-store": "^5.0.1",
"expokit": "^33.0.2",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
"react-navigation": "^3.11.0",

### Steps to Reproduce
I created a new expo project by using createMaterialBottomTabNavigator (in react-navigation library). I didn't encounter with any problem with it.
Unfortunately in my project I use badge on tab bar.
I suspected from getting badge number.
I use apollo-graphql to get badge number from server.

### Expected Behavior
I could see my tab bar when app started

### Actual Behavior
App crashes after it is loaded.

**Comment by sjchmiela** [comment]
Hey, @akbasonder!

Have you checked out React Native's changelog? If you haven't noticed, in SDK33 we upgraded not only some Expo and React Native Community libraries, but also React Native itself. In 0.59, previously deprecated `TabBarIOS` has been removed (see [changelog entry](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#ios-specific-11)). 

To use Expo SDK 33 (and thus React Native 0.59) you'll need to upgrade your code to use something else. I would recommend [`react-navigation`'s tab bar navigation](https://reactnavigation.org/docs/en/tab-based-navigation.html), but the choice is up to you!

**Comment by akbasonder** [comment]
Hello, 
everything started to work fine after I remove all apollo graphql libraries by using "yarn remove" and add them again by using "yarn add".
I think there was a conflict with apollo old libraries.
Now everything is fine.
Best Regards.

**Comment by thestoneoflapiz** [comment]
TabBarIOS is IOS specific changes but in my android app still shows the error, how can I removed it or hide it?

**Comment by sjchmiela** [comment]
You should not render it if you're rendering **not on iOS**. Imagine something as simple as:

```jsx
import { Platform, TabBarIOS } from 'react-native';

function MyCustomTabBar() {
  // ...
  if (Platform.OS === 'ios') {
    return <TabBarIOS {...someProps} />;
  } else {
    return <SomeOtherTabBar {...someOtherProps} />;
  }
}
```

**Comment by thestoneoflapiz** [comment]
@sjchmiela Yeah simple as that, but we didn't use any TabBarIOS in our app. And it's really surprising we're still having errors despite that..

**Comment by sjchmiela** [comment]
To debug where is it rendered, if it also happens in development mode, one would need the stack trace. If you can access stack trace of this error, you should be able to see the offending component (like in the OP's question, there's `ScreenUtil.tsx:7`, `FriendTab.tsx:10`, etc)
