### ISSUE TITLE
Expo tabs template does not work out the box with expo-web 

### ISSUE THREAD

**Issue by uksparky** [expo/expo#4563]
### Environment

$ expo diagnostics

  Expo CLI 2.19.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.5
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.19.5

App target:   web (expo-web)

### Steps to Reproduce
1. run expo init
2. choose the tabs managed workflow and finish setup
3. run expo start from new project
4. hit w to view page using expo-web
5. Web version fails to load due to missing image or incorrect image path.

### Expected Behavior

The basic tabs sample should load as it does on a real device. 

### Actual Behavior

Web page fails to open with an error message of:

Failed to compile.
/Users/mick/Documents/expo_test/slober-io/node_modules/@expo/samples/ExpoLinksView.js
Module not found: Can't resolve './assets/images/expo-icon.png' in '/Users/mick/Documents/expo_test/slober-io/node_modules/@expo/samples'

Copying the image into the path specified gets the page working as expected but not sure that's the expected fix, shouldn't the path be different?

Sorry for not creating a demo but it's not really applicable in this case.

**Comment by cruzach** [comment]
Hi @uksparky, thanks for pointing this out! 

Do you want to submit a PR changing the require statement? (Make sure to test both on mobile and web)

-Charlie

**Comment by EvanBacon** [comment]
This was resolved before SDK33 was released. Please ensure you are using `@expo/samples@^3.0.0`

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/pull/4354

**Comment by uksparky** [comment]
Using latest 3.02, it's still broken.

**Comment by summerkiflain** [comment]
In my case `expo-icon.png` was missing from `node_modules/@expo/samples`, changing `expo-icon.png` to `expo-icon@2x.png` makes it working on web.
