### ISSUE TITLE
Why not use React exact version 16.8.4 on SDK 33 ?

### ISSUE THREAD

**Issue by YoshiYo** [expo/expo#4569]
Hi Expo team 👋🏻

I'm wondering why the exact version of react for the last release of expo was set on [16.8.3](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c).

I would like to use the latest version of react-redux, which needs [16.8.4](https://github.com/facebook/react/releases/tag/v16.8.4). 
In the [changelog](https://github.com/reduxjs/react-redux/releases) of react-redux, the last package was 16.8.4 and they lowered it to ^16.8.3.

According to the fix of react 16.8.4, the change is really minor. I tried on my side and everything works well. 
May the exact version be 16.8.4 to include the fix?

Bye guys :)

**Comment by brentvatne** [comment]
We used this because it's the version that react-native@0.59 depends on: https://github.com/facebook/react-native/blob/43945c114eabaa46bd7ec91f5e241f18e1004f2f/package.json#L157-L159

**Comment by ide** [comment]
The interface between React and React Native does not follow semver. In the past, using a different patch version of React has broken things.

As Brent said, since React Native depends on 16.8.3, that is the version to use.

**Comment by YoshiYo** [comment]
Allright, thank you @brentvatne and @ide for your time and explanations.
