### ISSUE TITLE
Permission denied when running `exp path`

### ISSUE THREAD

**Issue by w4ndry** [expo/expo#457]
Hey guys,
I use ubuntu 16.04 LTS Xenial Xerus. I have install exp with this command `npm install -g exp` after that i run this command `exp path` but it's show error.
```shel
Error: EACCES: permission denied, open '/home/wandry/.expo/log'
```
anyone can help me?

**Comment by dikaiosune** [comment]
Hi! It looks like you may have run `exp` with `sudo exp` at some point. Can you run `sudo rm -r ~/.expo` and see if this happens again?

**Comment by jimmylee** [comment]
Closing this issue because its been a month with no reply.

**Comment by CaliKat** [comment]
@dikaiosune that worked, thank you!
