### ISSUE TITLE
Remove JS kernel execution from standalone apps

### ISSUE THREAD

**Issue by ide** [expo/expo#4570]
Based on some recent issues, it appears that standalone apps (on iOS at least) run the kernel JS. Removing the kernel JS will improve stability, performance, and a small improvement to IPA size.

Not sure we can complete this for SDK 34 but would be good to work on.

**Comment by sjchmiela** [comment]
I have debugged iOS shell app project and I couldn't find any trace of the application downloading/running kernel. `EXHomeModule` isn't created, I/O activity instrument doesn't show that any bundle other than the shell app bundle is being downloaded/saved to file system/interpreted. There's no kernel bundle in the shell app. I think we can close this safely. 🙂

**Comment by ide** [comment]
Thanks for verifying this :)
