### ISSUE TITLE
Deprecation plan for importing from "expo" in SDK 34+

### ISSUE THREAD

**Issue by ide** [expo/expo#4572]
SDK 33 introduced "modular imports" which means importing APIs like Camera from `expo-camera` instead of the `expo` package. The `expo` package will become much smaller and focus on app set-up rather than exporting many APIs. As part of a transition plan, there are deprecation messages in the `expo` package, and there is a nice tool called `expo-codemod` to automatically rewrite imports, and `expo install` will install the correct versions of the individual packages.

We need to figure out the rest of the transition plan. Talking to several people, it seems like targeting SDK 34 to remove all of the deprecated imports from the `expo` package. To aid with debugging, we may still export stubs from `expo` that print an error:

```js
Object.defineProperties(exports, {
  Camera: {
    get() {
      console.error('deprecation message; how to fix');
    }
  }
})
```

**Comment by brentvatne** [comment]
I think we should throw an error instead. This has the benefit of stopping execution right there rather than continuing on and waiting for the next call to error.

eg:

```
Constants has been removed from the expo package
- node_modules/expo/build/environment/muteWarnings.fx.js:26:24 in error
- node_modules/expo/build/deprecated.js:155:26 in get
- node_modules/expo/build/ExpoLazy.js:153:23 in get
* App.js:8:13 in App
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:9473:27 in renderWithHooks
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:11994:6 in mountIndeterminateComponent
- ... 21 more stack frames from framework internals

TypeError: undefined is not an object (evaluating '_expo.Constants.appOwnership')

* App.js:8:23 in App
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:9473:27 in renderWithHooks
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:11994:6 in mountIndeterminateComponent
- ... 18 more stack frames from framework internals
```

vs

```
Error: Constants has been removed from the expo package
- node_modules/expo/build/deprecated.js:155:28 in get
- node_modules/expo/build/ExpoLazy.js:153:23 in get
* App.js:8:13 in App
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:9473:27 in renderWithHooks
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:11994:6 in mountIndeterminateComponent
- ... 18 more stack frames from framework internals
```

**Comment by ide** [comment]
That seems good since getting back `undefined` would probably result in an error and clobber the message we want to show.

**Comment by ide** [comment]
Closed by https://github.com/expo/expo/pull/4815.
