### ISSUE TITLE
Convert standalone-ncl/expo-payments test to use the bare workflow

### ISSUE THREAD

**Issue by ide** [expo/expo#4573]
We want to be able to (a) test the bare workflow and (b) test bare-workflow-only modules like In-app Purchases.

We also need this for Bluetooth and modules that behave differently in the bare workflow.

**Comment by ide** [comment]
@EvanBacon is working on adding a new bare project to the repo, but ran into some issues for Android (definitely would be helpful to get guidance from SWM folks with Android expertise). This bare project can provide the foundation for our bare test project.

One thing we can do is add all of our modules to this bare project (including payments, BLE, and other bare-only modules), and then load different JS bundles. This way one bare project could be used to run NCL and test-suite!

**Comment by mczernek** [comment]
@ide Why do we want it to be in one application? As far as I know it is doable, but it looks like lot of work. I wanted to make sure we really need this, before we decide to go for it.

**Comment by sjchmiela** [comment]
Both `standalone-ncl` and `expo-payments` have been removed in favor of a single native app, `bare-expo`, capable of incorporating both `test-suite` and `native-component-list`.
