### ISSUE TITLE
Expo upgrade issue (sdk 32.0.0 to sdk 33.0.0) this._listeners[n] is not a function

### ISSUE THREAD

**Issue by aguileraps** [expo/expo#4574]
### Environment

  Expo CLI 2.19.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.1-next.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

app target iOS

### Steps to Reproduce

1 - create a MapView.AnimatedRegion
2 - addListener to previous AnimatedRegion
3 - animate to a new coordinte

### Expected Behavior

Animation of the marker at the new coordinates and the listener's execution 

### Actual Behavior

display error : 
this._listeners[n] is not a function. (In 'this._listeners[n]({value:t})', 'this._listeners[n]' is an instance of Object)

### Reproducible Demo

https://snack.expo.io/@bykomarg/animatedregion

### Demo code

`
import React, {Component} from 'react';
import {View, Text} from 'react-native';
import MapView, {AnimatedRegion, Animated, Marker, MarkerAnimated} from 'react-native-maps';

export default class Test extends Component {

    constructor() {
        super();
        this.state = {
            coordinate: new AnimatedRegion({
                "latitude": -33.07204,
                "latitudeDelta": 0.01,
                "longitude": -68.98632,
                "longitudeDelta": 0.005622188905547227,
            })
        };

        // without these lines works well
        const listener = this.state.coordinate.addListener((value) => {
            console.log(value);
        }); 

    }

    async componentDidMount() {

        const duration = 5000;

        const coord = {
            "latitude": -33.07350,
            "latitudeDelta": 0.01,
            "longitude": -68.98632,
            "longitudeDelta": 0.005622188905547227,
        };

        this.state.coordinate.timing({
            ...coord,
            duration
        }).start();

    }

    render() {

        const {coordinate} = this.state;

        return <View style={{flex: 1}}>
            <Text>test...</Text>
            <MapView
                style={{flex: 1}}
                initialRegion={{
                    "latitude": -33.07204,
                    "latitudeDelta": 0.01,
                    "longitude": -68.98632,
                    "longitudeDelta": 0.005622188905547227,
                }}
            >
                <MarkerAnimated
                    ref={(ref) => {
                        this.marker = ref
                    }}
                    title={'tirulo'}
                    description={'description'}
                    coordinate={coordinate}
                />
            </MapView>

        </View>;
    }
}
`

### Screenshot
![Screenshot_1](https://user-images.githubusercontent.com/1988234/59379744-c6ced800-8d2d-11e9-9417-54ad9cbd8b39.png)

**Comment by cruzach** [comment]
This looks like it was an upstream issue in `react-native-maps`, and I've opened a PR with a fix: https://github.com/react-native-community/react-native-maps/pull/3131

**Comment by aguileraps** [comment]
great!
