### ISSUE TITLE
Make CI consistently green

### ISSUE THREAD

**Issue by ide** [expo/expo#4575]
The client workflow has been failing for awhile. We need to fix the client_ios job and the android test suite job.

**Comment by sjchmiela** [comment]
First thing would be to fix test timeout on waiting for Google sign in — the device hangs on

<img width="203" alt="Zrzut ekranu 2019-08-14 o 08 18 52" src="https://user-images.githubusercontent.com/1151041/62998549-310a1300-be6c-11e9-8b13-8be390654097.png">

Assigning @EvanBacon, when it's fixed we will look for the next problem. 🙂

**Comment by EvanBacon** [comment]
We should pass an env variable something like `IS_INTERACTABLE` so certain tests can be disabled in device farm

**Comment by EvanBacon** [comment]
Error is now `Linking`:

<img width="510" alt="Screen Shot 2019-08-15 at 3 08 33 PM" src="https://user-images.githubusercontent.com/9664363/63130260-ad851a80-bf6e-11e9-95cd-a6e38288ed36.png">
