### ISSUE TITLE
alternative to realm?

### ISSUE THREAD

**Issue by kiodou** [expo/expo#458]
I'm looking for an alternative to realm with similar features, and fast.

I need to support local storage at first, then in the future i will need to be able switch the app to use remote storage. The process is specific to the job. 

Realm was perfect for this situation, but expo doesn't support it, and i don't really want to detach my application.

So any alternatives? or is there any chance support will come out for it, soooon.

Thank you.

**Comment by ide** [comment]
Expo includes support for SQL, would that work for you?

**Comment by dikaiosune** [comment]
Hi! We're trying to keep our GitHub issues focused on bug reports -- can you ask this on the forums or Slack? Thanks!
