### ISSUE TITLE
Revisit RootErrorBoundary

### ISSUE THREAD

**Issue by ide** [expo/expo#4581]
- Should we rethrow? See https://github.com/expo/expo/pull/4208
- Need to implement getDerivedStateFromError:
```
Warning: %s: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI., RootErrorBoundary
- node_modules/expo/build/environment/muteWarnings.fx.js:26:24 in error
- ... 28 more stack frames from framework internals
```

**Comment by ReallyLiri** [comment]
Is there a workaround get get Error Boundary working in Expo in any manner?

**Comment by brentvatne** [comment]
error boundary will work fine however you want to use it in your app. this issue is only related to a top-level error boundary in case the error bubbles up there

**Comment by ide** [comment]
Closing this since we revisited the error boundary in https://github.com/expo/expo/pull/8050.
