### ISSUE TITLE
Expo SQLite not doing more than one transaction

### ISSUE THREAD

**Issue by impactcolor** [expo/expo#4586]
I posted this in the Expo forum but not getting much traction there.  So figured I'd try here.  It appears as if db.transaction cannot perform more than one transaction in any given session.  

I load my db with
const db = SQ.Lite.openDatabase('db.db');

I run two db. transactions in componentDidMount()
```
.then(() => { db.transaction(tx => {all my stuff here with a console.log} })
.then(() => { db.transaction(tx => {second all my stuff here with a console.log} })
```
After I run another db.transaction in another method and it won't execute.  I even copied the exact db transaction from the original one that worked and nothing it won't fire up.  Also after I exit a page and navigate back when componentDidMount() should fire up again nothing happens.  Console logs don't appear so it doesn't even fire up the db.transaction.  Is there something I'm missing to why it's not working as expected?

**Comment by cruzach** [comment]
Hi @impactcolor! 

It looks like the [snack](https://snack.expo.io/r1NrkTT04) you shared in the forum post didn't have the screen you said contained the problem, the project only contained the `app.js` file.

Could you replicate this in a snack and share it here? Preferably with minimal code- feel free to use this example snack that uses SQLite already- https://snack.expo.io/@charliecruzan/github.com-expo-sqlite-example (It uses different transactions in different methods right now, so I'm not sure how to reproduce this myself)
