### ISSUE TITLE
Expo LocalAuthentication disable passcode Fallback in IOS

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#4589]
For security reason, we need to disable passcode failback in the IOS.
![unnamed](https://user-images.githubusercontent.com/7379922/59426251-08897c80-8e1b-11e9-9c11-5f8f6ed17a35.jpg)

I check the docs of LocalAuthentication, we cannot find an option to disable it. It looks like Expo LocalAuthentication does not support this feature

However I find that feature is available in another third party library ```react-native-touch-id```.

I am just wondering if it is possible to add this feature to Expo LocalAuthentication in near future.

**Comment by tsapeta** [comment]
Yeah, sure, this should be easy to do. Maybe you would like to work on it and submit a PR? 🤔

**Comment by changLiuUNSW** [comment]
I am not very familiar with native code but will try my luck this weekend and submit a PR if all good

**Comment by AdamJNavarro** [comment]
Hey @changLiuUNSW,

I'm going to close this issue to reduce noise on the issues thread. Best of luck with the PR. If you have any questions during the process, please don't hesitate to reach out on the [forums](https://forums.expo.io/)!

Cheers,
Adam

**Comment by amsimoes** [comment]
Any update on this?

Docs state that ```fallbackLabel (string) -- Allows to customize the default Use Passcode label shown after several failed authentication attempts. Setting this option to an empty string disables fallback to device passcode. (iOS only)```...

But it's not working as intended, device passcode input still appears once authentication is failed 3 times.

Also, when providing options for the authenticateAsync method, authentication modal doesn’t open if only fallbackLabel is provided, needs promptMessage too although docs state no obligation.

Thank you
