### ISSUE TITLE
1.19.0 is missing

### ISSUE THREAD

**Issue by leo108** [expo/expo#459]
I have built a detached expo project using version 1.18.0 and I'm going to upgrade it to 1.19.0.

I'm following the steps in https://docs.expo.io/versions/v19.0.0/guides/expokit.html, but there is no `1.19.0` in [release](https://github.com/expo/expo/releases)  page.

**Comment by terribleben** [comment]
Hello there! Did you read something which told you "1.19.0" ? As you mentioned, currently there is no such version. The latest release at the time of writing is 1.18.2, a minor update to SDK 19.

**Comment by leo108** [comment]
@terribleben yes, I think I mix up the sdk version and the expo version
