### ISSUE TITLE
Accelerometer and Gyroscope (and Sensors) don't work on web platform

### ISSUE THREAD

**Issue by cdcv** [expo/expo#4595]
## 🐛 Bug Report
Accelerometer and Gyroscope components don't work when running on web platform, including when running in a  mobile browser.  I imagine this is also true for other device hardware features that are not exposed in the web platform (but could be).
This is presumably because the underlying code only uses the native hardware drivers, not the web-browser-based versions via the webAPIs, like:
https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer
There are web-browser versions of the accelerometer, gyroscope, and other sensors.  For Expo web to be  'cross-platform', these should be connected so that the various features of the phone that will work in the browser... will work in an Expo web app.
Extra credit (which would be awesome): set it up so that when the app is run in an environment without sensor data, it's possible to use sample data.

Thanks!

### Environment

 Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.1
      Shell: Unknown - /usr/local/bin/fish
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.3 => 5.1.3 
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.9.1 
    npmGlobalPackages:
      expo-cli: 2.19.4

### Steps to Reproduce
Create app that includes the component(s):
          <Text>Accelerometer Data</Text>
          <AccelerometerSensor />

          <Text>Gyroscope Data</Text>
          <GyroscopeSensor />

### Expected Behavior
Run the app on phone-> works.
Run the app on web in browser-> works.

### Actual Behavior
Run the app on phone-> works.
Run the app on web in browser-> no data.

**Comment by ide** [comment]
Expo Web implements these I believe but Apple disabled it by default Can you take a look at https://www.macrumors.com/2019/02/04/ios-12-2-safari-motion-orientation-access-toggle/ and see if it is relevant?

**Comment by EvanBacon** [comment]
You should use the [`isAvailableAsync()`](https://docs.expo.io/versions/v33.0.0/sdk/accelerometer/#accelerometerisavailableasync) method on each sensor to get availability. Unfortunately there is no web API for the sensor permission provided by apple, so we shim one out. 

> Extra credit (which would be awesome): set it up so that when the app is run in an environment without sensor data, it's possible to use sample data.

This wouldn't make sense as part of the SDK, maybe a support library.

**Comment by EvanBacon** [comment]
You could build something like this:

```ts
// iOS 12.2 disables DeviceMotion by default now
// https://github.com/w3c/deviceorientation/issues/57
export async function assertSensorEventEnabledAsync(): Promise<void> {
  const isEnabled = await Accelerometer.isAvailableAsync();
  if (Platform.OS !== 'web' || isEnabled) {
    return;
  }

  throw new Error(
    `Accelerometer is not enabled on this device!` +
      '\nEnable device orientation in Settings > Safari > Motion & Orientation Access' +
      '\nalso ensure that you are hosting with https as DeviceMotion is now a secure API on iOS Safari.'
  );
}
```

**Comment by cdcv** [comment]
Evan, thanks for your help... but this isn't an Apple issue.  I'm trying to run the Expo code on an Android device, and testing on Google Chrome.  Please re-open this issue and address.  Thank you.

**Comment by brentvatne** [comment]
@cdcv - probably worth mentioning that in your original issue 😅

**Comment by EvanBacon** [comment]
Maybe try running `expo start --https`. AFAICT It works for everyone else who's used it. Accelerometer is also the first API in the list of demo APIs in case you want to test it on your device: https://expoweb.netlify.com

**Comment by cdcv** [comment]
Thank you very much.  Using expo start --https option seems to solve the problem, and I am now getting gyroscope data correctly on an expo react native app running in an android chrome mobile browser.  Please add to documentation so others don't get stuck on this too...

**Comment by cdcv** [comment]
Also, now that it's running, I'm getting a warning: expo-sensors: setUpdateInterval() is not supported on web.  Is there some other way to do this?  We need to be able to adjust how quickly the data are sampled (or at least set this to the maximum possible sampling rate and we can down-sample from there).  Thanks

**Comment by EvanBacon** [comment]
Data is returned as quickly as possibly. There is no way to throttle it natively and AFAICT it doesn't make sense to purposefully throttle the return value.
