### ISSUE TITLE
undefined is not an object error when using gl-react with Expo SDK v33

### ISSUE THREAD

**Issue by afrozopsy** [expo/expo#4596]
## 🐛 Bug Report
An error is throw on the screen which says "undefined is not an object(evaluating '_expo2.default.FileSystem')" when using [gl-react](https://github.com/gre/gl-react/) library with [gl-react-expo](https://github.com/gre/gl-react/tree/master/packages/gl-react-expo) and [gl-react-image](https://github.com/gre/gl-react-image).

### Environment

I am using iphone 5s expo client app.

expo diagnoistics says:

  Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

### Steps to Reproduce

Following gist will reproduce it.

[`Link to the gist`](https://gist.github.com/afrozopsy/f7c1c86517f26c23b98acf7baf76749e)
### Expected Behavior

Image from the asset should load on the screen.

### Actual Behavior

It throws the specified error as mentioned.

### Error Screen.

This screen shows up on runtime,

![IMG_4644](https://user-images.githubusercontent.com/51536094/59457408-c4ee3d00-8e31-11e9-986a-354051efc715.PNG)

SideNote: I think its worth mentioning here that the problem seems to be coming from [react-native-image](https://github.com/gre/gl-react-image) coz mere shaders rendered correctly. But, I think something broke when using [react-native-image](https://github.com/gre/gl-react-image) with file system of SDK v33 of Expo.

**Comment by cruzach** [comment]
Hi @afrozopsy!

This is most likely due to the fact that we are making the switch to modular importing (see the [SDK 33 release notes for more info](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c)). I suggest you look into how those libraries you're using are importing their Expo modules (the last commits were all either a year or older), as this doesn't seem to be a bug with the Expo SDK

**Comment by RayMoore** [comment]
Hi @afrozopsy, 
You can try to replace '_expo2.default.FileSystem' with '_expo.FileSystem', It works for me.

**Comment by afrozopsy** [comment]
@RayMoore Thanks Man :) That actually worked. But its a naive solution i guess :p I had to go through the node_modules folders find what is the dependency of what, and then locate _expo2 variable, then change it. I looked into it, and this is happening because gl-react-expo library is out-dated, and it has not yet implemented modular imports as of SDK v33 of expo. Also, _expo2 variable was in babel code not in the library code, so I guess someone should make necessary changes in the lib, build the package and then release it so others may not have to waste hours like I had to do.

**Comment by afrozopsy** [comment]
I have figured this out, I wrote an answer to stackover flow question about it, Here is the link [Stackoverflow question](https://stackoverflow.com/questions/55197155/gl-react-expo-shader-with-external-image-texture-input/56611242#56611242)
