### ISSUE TITLE
In background task, promises never resolve if they do not resolve immediately

### ISSUE THREAD

**Issue by mslavik2** [expo/expo#4599]
### Environment

 Expo CLI 2.19.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

### Steps to Reproduce

Create a background task and use a promise that takes some time to resolve. (See the demo in App.js)

### Expected Behavior

The promise to resolve correctly in the background.

### Actual Behavior

The promise never resolves while the application is in the background. When the application returns to the foreground, the promise resolves correctly. 

### Reproducible Demo

https://github.com/mslavik2/expo-background-fetch-issue

**Comment by g-bastianelli** [comment]
I m not able to use fetch at all. I only try with SDK 33 on ipad and iphone. The task is registred but never run

**Comment by mslavik2** [comment]
This issue actually was caused by having the react-native-debugger connected while attempting to use the background-fetch. It looks like the debugger was blocking react-native bridge commands which caused JSTimers.callImmediates to fire very rarely in the background. Promises rely heavily on setImmediate in order to function and was the root of this issue. I am closing this issue with the solution of "disconnect the debugger".

@g-bastianelli I would suggest moving your issue to https://github.com/expo/expo/issues/3582 as that is more inline with the issue I think you are facing.
