### ISSUE TITLE
Cannot open Contacts app and edit a user using addressbook:// url

### ISSUE THREAD

**Issue by raarts** [expo/expo#460]
According to [Apple Developer Docs](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/AddressBook/Tasks/URLScheme.html), addressbook://<uuid> should open the contact page for a user. Can even work in edit mode. This does not work using expo Linking.

(I have to add that safari also refuses to open it, but don't know if this means anything)

**Comment by terribleben** [comment]
Hi, you've linked to documentation for macOS, not iOS. This [isn't a feature on iOS](https://stackoverflow.com/questions/3531585/is-there-a-custom-url-scheme-for-the-built-in-contacts-app).
