### ISSUE TITLE
Error: AnimatedRegion could not obtain AnimatedWithChildren base class

### ISSUE THREAD

**Issue by drfenixion** [expo/expo#4601]
## 🐛 Bug Report
When app starts get the error - "AnimatedRegion could not obtain AnimatedWithChildren base class
- node_modules/expo/build/logs/LogSerialization.js:148:4 in w
- node_modules/expo/build/logs/LogSerialization.js:41:24 in <unknown>
- node_modules/regenerator-runtime/runtime.js:45:44 in p
- node_modules/regenerator-runtime/runtime.js:271:30 in <unknown>
- node_modules/regenerator-runtime/runtime.js:45:44 in p
- node_modules/regenerator-runtime/runtime.js:135:28 in n
- node_modules/regenerator-runtime/runtime.js:170:17 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in c
"

### Environment

  Expo CLI 2.19.5 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.5

Android

### Steps to Reproduce

Update to Expo 2.11.2 from the previous version and started getting this error. 

### Actual Behavior

The app works as previously but getting the error. The app works fine if skip error.

### I did
remove node_modules
remove package-lock.json
npm install
yarn install (just trying another dependency system, without profit)

### Other info
Here I see same issue https://github.com/react-native-community/react-native-maps/issues/1303
And answer with likes: 

> got the same problem only when i enable "JS minify" in "dev settings" when i shake the smartphone.
> un check it solve the error showing

How can I do it with Expo?

**Comment by cruzach** [comment]
You can turn the minify flag on/off by passing either the `--minify` or `--no-minify` flags to `expo start`, respectively. ([source](https://docs.expo.io/versions/v29.0.0/workflow/exp-cli/))

Let me know if that ends up working!

**Comment by drfenixion** [comment]
Yes, it works. If `expo start --no-minify` app works without error. With `--minify` get the error.

**Comment by cruzach** [comment]
Since it seems like this is an issue (only with minified code) that is due to the `react-native-maps` library, I'm going to close here.

(Seems like using `yarn` instead of `npm` fixes it though)

**Comment by drfenixion** [comment]
Yarn not fix it for me
