### ISSUE TITLE
Sign out not working

### ISSUE THREAD

**Issue by jzgarcia123** [expo/expo#4602]
Signing out seems to have blocked me from logging back into an expo account.

The problem appears to occur on both android and iOS. Deleting the app and reinstalling does not fix the problem. This problem exists for multiple people.

**Comment by tonnenpinguin** [comment]
Did you try to log in, close the app (also remove it from the background) and then reopen the app?
We had similar issues in the past that were "fixed" by that.

**Comment by sjchmiela** [comment]
I couldn't reproduce it. Are you sure the issue persists?

**Comment by danielisaacgeslin** [comment]
i have the same issue
