### ISSUE TITLE
[docs] Specify how to use torch (flashlight)

### ISSUE THREAD

**Issue by DenisBiondic** [expo/expo#4609]
I didn't find it documented how to use the torch function via a button or something similar. We need this function during barcode scanning process. I presume this is in expo therefore the "docs" issue.

**Comment by cruzach** [comment]
Hi @DenisBiondic ! 

You can use the Camera API and the `onBarCodeScanned` prop to do bar code scans, and just set the [flashMode prop](https://docs.expo.io/versions/latest/sdk/camera/#props) to `torch`. If you want to submit a PR to the BarCodeScanner docs, please feel free! 👍

**Comment by DenisBiondic** [comment]
Hey @cruzach, thx for the quick response. Another question perhaps -> what is the purpose of BarCodeScanner if Camera can achieve everything BarCodeScanner can (and more)?

**Comment by cruzach** [comment]
We're working on possibly deprecating `BarCodeScanner` and just having `Camera` takeover that functionality completely, but it's a process 😅
