### ISSUE TITLE
Stack traces way too long... make collapsible?

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#461]
The stack trace in Expo XDE is way too long. Perhaps the paths could be concatenated, or the trace could be collapsed (like in the browser)?

![stacktrace](https://user-images.githubusercontent.com/1566400/29035786-e43daf32-7b6a-11e7-9681-58897036d131.gif)

**Comment by davepack** [comment]
@brentvatne you are working on this, correct?

**Comment by brentvatne** [comment]
yep, also symbolicating the stack trace correctly

**Comment by brentvatne** [comment]
![expand](https://user-images.githubusercontent.com/90494/29942031-4bfa1d9a-8e49-11e7-8b8d-4619f7387afc.png)

coming in next release

**Comment by jimmylee** [comment]
Closing this issue since this feature will be enabled for projects using Expo SDK 21
