### ISSUE TITLE
Support app.json entryPoint for web

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4613]
### Steps to Reproduce

- Clone https://github.com/brentvatne/bare-but-runs-in-client
- Run `expo start --web`
- Notice that the page is blank
- Copy `entryPoint` from `app.json` into `package.json` and rename `entryPoint` to `main`
- Run `expo start --web` again
- It works

Note that we support customizing the `entryPoint` in `app.json` for iOS and Android. This is useful in case we have a different entry point when building the project another way, eg: through Xcode.

**Comment by ide** [comment]
Why do we have `entryPoint` at all and not just use main everywhere?

**Comment by EvanBacon** [comment]
we use `package.json` main to define the entry point. If you want a different entry point on native you should use a platform extension. 

## Example 

**package.json**
```js
{
  // Notice the lack of an extension
  "main": "./index"
}
```

Then create a `index.web.js` for the entry point to your web app. This is how we recommend doing things in the docs https://docs.expo.io/versions/v33.0.0/introduction/running-in-the-browser/#web-only-method

**Comment by brentvatne** [comment]
See the doc I shared about supporting Expo client and bare workflow in the same project. You may want to have a different entry point if you are starting with `expo start` vs `react-native start`. With `expo start` we want to point to the `expo` AppEntry file. Open to other ideas for doing this.

**Comment by EvanBacon** [comment]
Oh interesting. Yeah I'll open a PR if we're already doing this. We also check for `index.*`, `src/index.*` if the `"main"` field is missing (CRA support). Perhaps we could add `node_modules/expo/AppEntry` as well.

**Comment by ide** [comment]
Let's add a couple sentences to the docs here https://docs.expo.io/versions/latest/workflow/configuration/#entrypoint to explain that `entryPoint` lets you override `main` in package.json and why you'd want to do that. We should also maybe recommend `main` when possible though, since it is compatible with more JS tools.
