### ISSUE TITLE
Location.watchPositionAsync never calls the location callback on Android 9 with SDK 33

### ISSUE THREAD

**Issue by robclouth** [expo/expo#4616]
## 🐛 Bug Report

Calling ```Location.watchPositionAsync``` never calls the location callback.

Location services are enabled. Google Maps works fine.

```Location.getProviderStatusAsync``` returns true for everything.

I've tested it on other phones with other android versions and it works fine.

There is another similar issue but it has been closed: #3150

### Environment

Expo SDK 33
Xiaomi Mi A2
Android 9

### Steps to Reproduce

Snack:
https://snack.expo.io/@robclouth/expo-33-location

**Comment by lukmccall** [comment]
Could you check if this issue occurred on Android 9 simulator or other devices? I need more information to reproduce same behaviour.

**Comment by esamelson** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. We weren't able to reproduce this issue with the provided information. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
