### ISSUE TITLE
No space in app name on iOS

### ISSUE THREAD

**Issue by bomanimc** [expo/expo#4617]
## 🐛 No space in app name on iOS
Seems very related to #3180, but the issue found to cause the problem there doesn't seem to be an issue for my `app.json` file.

### Environment

**Diagnostics**
```
Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.9.1 => 3.9.1
    npmGlobalPackages:
      expo-cli: 2.19.4
```

**Target**: Standalone iOS App

### Steps to Reproduce

Here's my `app.json` file. Please note the `expo.name` value.
```
{
  "expo": {
    "name": "The Summer Smash",
    "slug": "summer-smash-app",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "dial-up-code",
            "project": "summer-smash-app"
          }
        }
      ]
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "com.dialup.summersmashapp",
      "infoPlist": {
        "LSApplicationQueriesSchemes": ["fb", "twitter", "instagram"]
      }
    },
    "android": {
      "package": "com.dialup.summersmashapp",
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/androidForegroundIcon.png",
        "backgroundColor": "#F5E82F"
      }
    }
  }
}
```

### Expected Behavior
I would expect the name on iOS to show up as "The Summer Smash" on iOS (like it does when running a built .apk file on Android). See Android working correctly below:
<img width="334" alt="Screen Shot 2019-06-12 at 9 00 22 AM" src="https://user-images.githubusercontent.com/6589909/59534894-23a8ca80-8eb5-11e9-8c2e-16d6ed7283b1.png">

### Actual Behavior
App name is displayed as "TheSummerSmash" on iOS.

<img width="399" alt="Screen Shot 2019-06-12 at 9 20 28 AM" src="https://user-images.githubusercontent.com/6589909/59534864-1390eb00-8eb5-11e9-918e-ed89658d3d39.png">

### Reproducible Demo
I'll update this issue thread with a test of trying to add spaces to a name on a new, public Expo project. Posting early just in case anyone has immediate insights.

**Comment by cruzach** [comment]
Hi @bomanimc- see [this comment](https://github.com/fastlane/fastlane/issues/12154#issuecomment-376907942) on an issue in the `fastlane` repo. Looks like iOS automatically removes spaces when the name is too long to show?

-Charlie
