### ISSUE TITLE
Permissions.getAsync() results inconsistent with iOS settings after upgrade to ExpoKit 33

### ISSUE THREAD

**Issue by briavicenti** [expo/expo#4618]
### Environment
```
  Expo CLI 2.19.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.2 => 16.8.7 
      @types/react-native: ^0.57.35 => 0.57.38 
      @types/react-navigation: ^3.0.2 => 3.0.4 
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.1
```

We are running an iOS ExpoKit app, distributed through TestFlight.

### Steps to Reproduce

You can repro this issue on [this snack](https://snack.expo.io/@curalate/expo-33-permissions-bug-repro-) provided that Expo is set to v33. You will **not** repro if you set Expo to v32.

Repro steps on this snack:
- Trigger the iOS permissions modal via the `Ask for Perms` button (which calls `Permissions.askAsync(Permissions.CAMERA_ROLL)`)
- Select `Don't Allow` to deny the permission
- Verify that the current permission status as determined by `Permissions.getAsync(Permissions.CAMERA_ROLL)` is `denied` by hitting the `Check Perms` button.
- Go to the settings app within the snack iOS simulator, navigate to Expo -->  Photos, and give the Expo app camera roll read/write permissions
- Navigate back to the Expo app, hit the `Check Perms` button again, and observe that the camera roll permission is still reported as denied.

### Expected Behavior

The status returned by `Permissions.getAsync()` should reflect the permissions found in the iOS settings app. 

### Actual Behavior

Under certain conditions the status from `Permissions.getAsync()` is always returned as `denied`, and cannot be changed even if you manually adjust permissions via iOS settings.

We discovered this issue primarily because the status is returned as `denied` when we upgrade directly from our older non-Expo app where we have already granted permissions to our new TestFlight build running ExpoKit 33. This is causing a bunch of issues for our testers, so we'd love a better workaround than having all of our testers delete our app and re-request perms from scratch!

**Comment by jb4e** [comment]
Ha, small world, @briavicenti. I was running into the same issue and found your bug report. A workaround that works for me and appears to work in your snack as well: 
Call Permissions.askAsync again after the user changes it in settings. That appears to return the correct status, and getAsync subsequently will as well. I want to check out the new version of the app when it's ready!

**Comment by briavicenti** [comment]
Heyy fancy seeing you here @jb4e! That workaround is indeed working as a temp fix for us, thanks for the tip!

**Comment by PipBoy2000** [comment]
Any update on this? I just got slammed with it while testing my code after we upgraded to SDK33.

**Comment by bbarthec** [comment]
`expo-permissions` are being refactored at the moment (#5061).
Right now I suggest using `Permissions.askAsync` as it's querying system permissions correctly.
