### ISSUE TITLE
`Project.startAsync` should warm the packager cache by requesting a bundle

### ISSUE THREAD

**Issue by anp** [expo/expo#462]

**Comment by imasif** [comment]
i there nobody to fix it?

**Comment by rafialikhan** [comment]
Exploring Expo and stuck at the start.
Stuck at the same issue cant proceed any further. [https://forums.expo.io/t/am-i-supposed-to-wait-on-loading-dependency-graph/407/5](expo forum issue)

Details:
OS: Mac OS X El Capitan
Node Version: v8.9.0

![screen shot 2017-11-07 at 6 11 47 pm](https://user-images.githubusercontent.com/179993/32494469-c31cebd6-c3e7-11e7-8fd9-4f057fcb273d.png)

**Comment by mtnptrsn** [comment]
+1 I have the same problem. Any sulotions?

**Comment by beckzar** [comment]
+1 Same problem here

**Comment by dikaiosune** [comment]
Deleted some comments about an unrelated issue -- the issue title refers to a performance improvement we could make. Please open a new issue for any bugs you're seeing.
