### ISSUE TITLE
Turtle-cli standalone build .apk instead of .aab

### ISSUE THREAD

**Issue by ctopher7** [expo/expo#4620]
I want to build my own apk file using standalone build . 

- First of all, I already did the expo publish
- Second, I ran the command 'turtle build:android --username xxxx --password xxxx --publish-url xxxx
- Build finished and it is sae into expo-apps folder

The problem that I encounter is: I don't want android app bundle, I need .apk file so I could easily share this app to other people. Is there any way to produce .apk file instead of .aab file using turtle standalone build?

**Comment by cruzach** [comment]
Hi @ctopher7!

You can read this in the [turtle changelog](https://github.com/expo/turtle/blob/master/CHANGELOG.md), but:
> App bundles are built by default, use -t apk to build apk
