### ISSUE TITLE
After ejecting the app from Expo When i try creating a standalone app(apk) using android studio app display's "Could not load app. Are you sure XDE or EXP is running?".

### ISSUE THREAD

**Issue by sheshashayan** [expo/expo#4622]

**Comment by sheshashayan** [comment]
Is it necessary to run expo packager .. Even after ejecting from Expo..? How can i create a standalone app without expo packager

**Comment by geolivero** [comment]
This issue is on IOS asswell and i think is related to this issue at [https://github.com/expo/expo-cli/issues/737]()

After eject then build, the app is unusable.

**Comment by cruzach** [comment]
For development- yes. This is covered in the [Expokit documentation](https://docs.expo.io/versions/latest/expokit/expokit/).

Your ExpoKit project is configured to load your app's published url when you build it for release. So when you want to release it, don't forget to publish, like with any normal (non-ExpoKit) project.
