### ISSUE TITLE
📚Small documentation/typing inconsistency in FileSystem

### ISSUE THREAD

**Issue by wcandillon** [expo/expo#4625]
https://docs.expo.io/versions/latest/sdk/filesystem/ documents a size option parameter which is not used anymore. If you can point me to the right places to update the doc, I would be happy to submit a PR.

**Comment by cruzach** [comment]
Hi @wcandillon,

Can you elaborate on which method documents a `size` parameter that isn't used? The only one in the docs is `getInfoAsync` which [does use the `size` parameter](https://github.com/expo/expo/blob/master/packages/expo-file-system/src/FileSystem.ts#L56)

**Comment by wcandillon** [comment]
@cruzach this is the type definition I'm getting in my project (which works correctly):

```ts
export declare function getInfoAsync(fileUri: string, options?: {
    md5?: boolean;
    cache?: boolean;
}): Promise<FileInfo>;
```

**Comment by cruzach** [comment]
What SDK are you using?

**Comment by wcandillon** [comment]
v33

**Comment by cruzach** [comment]
Taken care of in [this PR](https://github.com/expo/expo/pull/4436), `expo-file-system` just hasn't been published yet to reflect the changes

Thanks for bringing this up though 😄
