### ISSUE TITLE
Upgrade failed SDK 32.0.6 -> 33.0.6

### ISSUE THREAD

**Issue by tdimnet** [expo/expo#4629]
### Environment

- Environment before SDK 32.

>   Expo CLI 2.20.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.18 => 4.1.18 
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.19 => 16.8.19 
      @types/react-native: ^0.57.60 => 0.57.60 
      expo: ^32.0.6 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.0

- Environment after SDK 33.

>   Expo CLI 2.20.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.18 => 4.1.18 
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.19 => 16.8.19 
      @types/react-native: ^0.57.60 => 0.57.60 
      expo: ^33.0.6 => 33.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.0

### Steps to Reproduce

Once I updated the dependencies I have a red screen telling me the **expo SDK requires expo to run**. I pasted a copy of the red screen below (within the **actual behavior** section).

For your information, here are the commands I ran:

- `rm -rf node_modules && yarn`
- `expo start -c`
- `npm install -g expo-cli`

I also deleted and reinstalled the expo app within my iOS simulator.

### Actual Behavior

![Screenshot 2019-06-17 at 11 04 55](https://user-images.githubusercontent.com/9935925/59592463-60acd100-90f0-11e9-87ec-d04671204963.png)

**Comment by gabrielmaiaf** [comment]
You have to upgrade React and React native too to SDK 33 requirements:
https://docs.expo.io/versions/v33.0.0/workflow/upgrading-expo-sdk-walkthrough/

**Comment by tdimnet** [comment]
@gabrielmaiaf : Ok, I am truly sorry, I did not look at expo upgrading workflow.
I did everything the documentation told me to do and it works fine by now.

Thank you very much for your help 🎆
