### ISSUE TITLE
TypeError: e[r] is undefined

### ISSUE THREAD

**Issue by sayeed99** [expo/expo#4633]
expo build:web produces a non working runtime js file

https://5d079bfafd94048e9fd62339--smdevops.netlify.com/

**Comment by kations** [comment]
@sayeed99 having the same error, do you have success resolving it?

**Comment by sayeed99** [comment]
> @sayeed99 having the same error, do you have success resolving it?

update your expo-cli to the latest one. 
run : 
expo customize:web
select webpack and edit env mode to development.

should look something like this :

const createExpoWebpackConfig = require('@expo/webpack-config');

module.exports = function(env, argv) {
  env.mode = 'development';
  const config = createExpoWebpackConfig(env, argv);
  // Customize the config before returning it.
  return config;
};

And this is not a good thing to do. I don't know if the production builds are back to fine or not since been away for a while.

**Comment by kations** [comment]
Thanks got it working, found this workaround without the need to hardcode dev mode:

const createExpoWebpackConfig = require("@expo/webpack-config");

module.exports = (env, argv) => {
  const config = createExpoWebpackConfig(env, argv);
  return config.then(c => {
    c.plugins = c.plugins.filter(
      x => x.constructor.name !== "WebpackDeepScopeAnalysisPlugin"
    );
    return c;
  });
};

**Comment by sayeed99** [comment]
Gonna update my webpacks well. Thanks.
