### ISSUE TITLE
storing login/password

### ISSUE THREAD

**Issue by flieks** [expo/expo#464]
Hi, 

i need a way to securely save the login/pass. This is my solution 
https://github.com/oblador/react-native-keychain
but i can't use this with Expo right because you need to edit the gradle file on android ?

What other save way exists ? AsyncStorage is not secure.

If i detach from Expo i can't use the expo XDE and push notifications anymore ? And publishing ?

Thanks
Greetings
Felix

**Comment by dikaiosune** [comment]
Hi! We plan to ship a secure storage solution (with an API similar to the linked library) very soon. Stay tuned!
