### ISSUE TITLE
[SDK 33] [WEB BUILD] Can't resolve 'react-native/Libraries/EventEmitter/RCTDeviceEventEmitter'

### ISSUE THREAD

**Issue by lamipaul** [expo/expo#4648]
Expo CLI 2.20.0 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19 (Tara)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    npmPackages:
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.0

This project was previously using react-native-web with SDK 30, and working fine on all platforms (until the expo client app update making SDK31 a minimum). 
I thus followed the walkthroughs to upgrade up to SDK 33 one version after the other.
Building and running on phone works fine. 

Trying to run it on web gives the following error : 
```
Failed to compile.
/home/lamipaul/Documents/piple/piple/node_modules/@unimodules/react-native-adapter/build/SyntheticPlatformEmitter.js
Module not found: Can't resolve 'react-native/Libraries/EventEmitter/RCTDeviceEventEmitter' in '/home/lamipaul/Documents/piple/piple/node_modules/@unimodules/react-native-adapter/build'
```

I've tried to [reinstall the expo dependencies using expo install](https://github.com/expo/expo/issues/4441), or reinstalling my node_modules. Didn't change the behaviour. 

By the way, thanks so much for intergrating RNW into SDK33, we're very excited about how easier how life is gonna get ! 

cheers

**Comment by cruzach** [comment]
Hi @lamipaul-

Could you provide a method for us to reproduce this error on our end?

**Comment by vjsingh** [comment]
I'm having the same issue.

Not sure if it's related, but I use absolute imports, and following the instructions here (https://forums.expo.io/t/help-resolving-absolute-imports-in-expo-33/23780/3) and here (https://docs.expo.io/versions/latest/guides/customizing-webpack/), have the following webpack.config.js:

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const path = require('path');

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  config.resolve.alias['src'] = path.resolve(__dirname, 'src/src');
  return config;
};
```

**Comment by hashim-sohail** [comment]
+1
Facing the same issue

**Comment by trulyenlightened** [comment]
Anyone who can help

**Comment by EvanBacon** [comment]
Should be mostly fixed in this https://github.com/necolas/react-native-web/pull/1402. For legacy users remember to install `expo` and to use `@expo/webpack-config` as this will alias polyfills.
