### ISSUE TITLE
[ExpoKit][SDK33] IntentLauncher now calls startActivityForResult in all cases, breaking compatibility with SDK32

### ISSUE THREAD

**Issue by ShimShamSam** [expo/expo#4649]
### Environment

```
  Expo CLI 2.20.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.20.0
```

Targeting Android 8.0+ (two specific devices)

### Steps to Reproduce

1. Add a custom Intent Filter to Expo's `MainActivity` in `AndroidManifest.xml`:

```xml
<intent-filter>
	<action android:name="com.my_example.TEST_ACTION" />
	<category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```

2. In your App, call:

```JS
IntentLauncher.startActivityAsync('com.my_example.TEST_ACTION', {
	packageName : 'host.exp.exponent', // <-- This is important
});
```

### Expected Behavior

In SDK32, specifying `packageName` caused IntentLauncher[Android] to call `startActivity()` instead of `startActivityForResult()` like it does in most cases.

I relied on this functionality because MainActivity has a launch mode of `singleTask` and therefore cannot return a result. Calling `startActivity()` allows MainActivity to handle the Intent via its `onNewIntent()` handler.

### Actual Behavior

In SDK33, IntentLauncher always calls `startActivityForResult()` regardless of any options passed to it. Unfortunately, this causes MainActivity to restart (not crash) because it is a `singleTask`.

### Reproducible Demo

I think this is pretty cut and dry. I've stepped through the code and isolated the issue. If anyone really wants me to build a small demo, I'll find time to do so.

### Workaround

I'm thinking I can work around this by making a separate (transparent) activity that starts an `AsyncTask` or thread and then calls `finish()` immediately after. I'm more than happy to try a better approach if there is one.

### My Thoughts

I'm aware that my working code in SDK32 likely relied on an oversight in the original IntentLauncher which was effectively patched in SDK33. However, I have two main concerns:

1. This breaks backward compatibility, so it should probably be documented in the changelog and upgrade guide
2. This brings about the question of whether IntentLauncher should be extended with less ambiguous functions. It also wouldn't hurt to add support for `startService` (and others) to better accomplish what I'm trying to do.

**Comment by tsapeta** [comment]
SDK33 is already not supported, also we no longer support ejecting to ExpoKit, so I'm closing this issue.
