### ISSUE TITLE
This exprience uses an unsupported verion of Expo  ( SDK 9.0.0 ) 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#465]
How can i run a project on a desired version of expo ?  Any easy way ?

![image](https://user-images.githubusercontent.com/1026325/29052977-46bfbdb2-7bbb-11e7-8d44-9bedbdeab283.png)

My current version 

![image](https://user-images.githubusercontent.com/1026325/29053017-799423f4-7bbb-11e7-9ac0-5f1a5349ad73.png)

**Comment by dikaiosune** [comment]
Hi! SDK 9 is no longer supported in the current Expo client. You can see a list of supported versions in the drop-down on the top right of https://docs.expo.io/versions/latest/index.html. Standalone apps that were built with an old version of the SDK will continue to work, but to use the client for development the app needs to be on a more recent SDK version.

In the future, we plan to announce an LTS process for some SDK versions, but we don't have all of the details in place yet. Thanks!
