### ISSUE TITLE
gulp android-shell-app doesn't exist

### ISSUE THREAD

**Issue by evanlarkin10** [expo/expo#4650]
### Environment
Expo CLI 2.17.2
OS Linux 4.15 Ubuntu 18.04

### Steps to Reproduce
Clone the repository

Follow the steps in the documentation to build a standalone app.

Here are the steps to build a standalone Android app:

- Publish your experience with Expo CLI. Note the published URL.
- cd tools-public.
- If you want a signed .apk, run gulp android-shell-app --url [the published experience url] --sdkVersion [sdk version of your experience] --keystore [path to keystore] --alias [keystore alias] --keystorePassword [keystore password] --keyPassword [key password] --workingDir=../.
- If you don't want a signed .apk, run gulp android-shell-app --url [the published experience url] --sdkVersion [sdk version of your experience] --workingDir=../.
- The .apk file will be at /tmp/shell-signed.apk for a signed .apk or at /tmp/shell-debug.apk for an unsigned .apk.
- adb install the .apk file to test it.

### Expected Behavior

Build unsigned apk for debugging

### Actual Behavior

Error:
'Using gulpfile
Task never defined: android-shell-app
To list available tasks try running: gulp --tasks'

(running gulp --tasks shows only 'ios-shell-app')

**Comment by cruzach** [comment]
Hi @evanlarkin10- did you follow all of the [setup instructions](https://github.com/expo/expo/blob/master/README.md#set-up) beforehand?

**Comment by sjchmiela** [comment]
Hey, sorry for the trouble! When looking for remaining usage occurrences of this script I used filter with `files_to_exclude: .git, …, .md, …`, which obviously excluded `README.md` from searching and thus I haven't removed outdated instructions.

Is there some specific reason for building a standalone app like that or have you just followed the README instructions?

In general if you'd want to build a standalone app on your machine, I would recommend [Turtle](https://docs.expo.io/versions/latest/distribution/turtle-cli/)! When we release a new version of Expo SDK we put the shell app to Turtle and it should always be able to build a standalone app on a specific Expo version. Using this script could result in unexpected errors—standalone apps use `expoview` native library package from `expokit-npm-package`, which is built on demand by us, developers, basically whenever we want to publish an update to packaged AARs. When preparing shell app project is also copies over some files from the `android` folder, which, in turn, uses `expoview` from `android/expoview`.

So, to sum up, this script could create invalid shell apps with conflicting:
- `MainActivity` expecting `expoview` from that commit
- `expoview` built when releasing last SDK.

Turtle doesn't have this problem. 🙂 

Documentation for Turtle — https://docs.expo.io/versions/latest/distribution/turtle-cli/
GitHub repository for Turtle — https://github.com/expo/turtle

Another possible reason for using `android-shell-app` would be to test one's changes to `expoview` — how they would behave in an ejected scenario. For this that script would also produce invalid result, it wouldn't rebuild neither the `expoview` nor unimodules' packages, so as a replacement for that I would suggest doing:
- `expo init` somewhere
- `expo eject` to ExpoKit
- `gulp update-exponent-view --abi REQUESTED_ABI` in `expo`
- somehow connect the `somewhere` project with `expo/expokit-npm-package`, either by running `npm pack` in `expokit-npm-package` and copying archive over or by using `file:` or `link:` dependency version in `somewhere`'s `package.json`.

**Comment by evanlarkin10** [comment]
@sjchmiela Thanks for the reply. The reason we are looking for a standalone build with android-shell-app is because we need a build with a debug keystore for testing. To this point we were using expo build:android and expo build:ios, which creates standalone apks/ipas just fine, however they are signed and don't work for automation testing.

**Comment by sjchmiela** [comment]
Ok! I added this feature today to `turtle-cli`. Try installing `turtle-cli` from this specific commit — https://github.com/expo/turtle/commit/952dcd0cd329143a2ea00672d0bf9468e05234de. (`npm i -g "expo/turtle#952dcd0"` iirc) Then you should be able to use a new option to `build:android`, which is `--mode debug`. So, if you install turtle-cli and go to your project's dir and run `turtle build:android -m debug` it should build the app in debug mode.

Unfortunately somehow I can't install Turtle on my computer, it fails on
```
(node:41097) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

but maybe you will have more luck. 😅

**Comment by evanlarkin10** [comment]
@sjchmiela Oh cool thanks, I am getting the same error as well as others including:
npm ERR! package.json Non-registry package missing package.json: github:expo/turtle#952dcd0.
npm ERR! package.json npm can't find a package.json file in your current directory.

**Comment by cruzach** [comment]
This is one of the intended use cases for [EAS Build,](https://docs.expo.io/build/introduction/) so I'm going to close this issue
