### ISSUE TITLE
[sqlite] iOS fails to execute "create table" with "could not prepare..."

### ISSUE THREAD

**Issue by tkrajina** [expo/expo#4656]
## 🐛 Bug Report

I'm trying to create a table in SQLite. 

The SQLite library fails to create a table using the sql statement `create table if not exists taskssss (id INTEGER primary key not null)` on iOS. 

It fails **only** on an iOS device (with the Expo client app). It works on Android (device and simulator) and iOS simulator (using Expo client).

I tried to debug `SQLIte.js` in:

```
function _deserializeResultSet(nativeResult) {
    let [errorMessage, insertId, rowsAffected, columns, rows] = nativeResult;
```

And the `nativeResult` variable is:

```
["could not prepare create table if not exists taskssss (id INTEGER primary key not null)"]
```

I also tried to find where that error is created:

```
$ grep -r "could not prepare" node_modules/*
node_modules/@expo/websql/lib/sqlite/SQLiteDatabase.js:  'could not prepare statement (23 not authorized)');
node_modules/expo-sqlite/ios/EXSQLite/EXSQLite.m:    error = [NSString stringWithFormat:@"could not prepare %@", sql];
node_modules/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.java:      super("could not prepare statement (23 not authorized)");
```

...and this to me looks like it's something in `EXSQLite.m`. Unfortunately, my knowledge of Objective-C fails short here.

### Environment

```
  Expo CLI 2.20.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.13 => 16.8.13 
      @types/react-navigation: ^3.0.7 => 3.0.7 
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.1
```

The iOS device I'm using is an iPhone 5 with iOS 10.3.3. But, I suspect it's a similar behaviour on my colleague's device (except I haven't had the opportunity to debug it directly).

### Steps to Reproduce

See the minimal demo below.

### Expected Behavior

Should create a table (like it does on Android and the iOS simulator)

### Actual Behavior

Fails to create a table on iOS (but only on actual devices, using Expo client).

### Reproducible Demo

This is the minimal (typescript) application that reproduces the bug:

```
import { SQLite } from "expo-sqlite";
import React from "react";
import { Text, View } from "react-native";

// --------------------------------------------------------

export interface Query {
  sql: string;
  args: unknown[];
}
export interface ResultSetError {
  error: Error;
}
export interface ResultSet {
  insertId?: number;
  rowsAffected: number;
  rows: Array<{
    [column: string]: any;
  }>;
}

declare type SQLiteCallback = (error?: Error | null, resultSet?: (ResultSet | ResultSetError)[]) => void;
interface WebSQLDatabase {
  exec(queries: Query[], readOnly: boolean, callback: SQLiteCallback): void;
}

// --------------------------------------------------------

class AppState {
  error?: Error | null;
  resultSet?: (ResultSet | ResultSetError)[];
}

class App extends React.Component<any, AppState> {
  constructor(props: any) {
    super(props);
    this.state = new AppState();
  }

  async componentDidMount() {
    const db = SQLite.openDatabase("dbdb.db") as WebSQLDatabase;
    db.exec([{ sql: "create table if not exists tasks_sss (id INTEGER)", args: [] }], false, (error?, resultSets?) => {
      this.setState({
        resultSet: resultSets,
        error: error
      });
    });
  }

  componentWillUnmount() {}

  render() {
    return (
      <View style={{ flex: 1, alignContent: "center", justifyContent: "center" }}>
        <Text style={{ alignSelf: "center" }}>
          err={JSON.stringify(this.state.error)}
          rs={JSON.stringify(this.state.resultSet)}
        </Text>
      </View>
    );
  }
}

export default App;

```

Note that the interfaces and types at the beginning are here only because not all parts of the SQLite API is properly exposed for Typescript (https://github.com/expo/expo/pull/4446). They can be removed when trying this with plain Javascript.

The result (on an iOS device):

![IMG_0642](https://user-images.githubusercontent.com/379243/59754801-1a3daa80-9287-11e9-8e4e-9c9308644a3e.PNG)

**Comment by tkrajina** [comment]
One more thing, if the error
```
["could not prepare create table if not exists taskssss (id INTEGER primary key not null)"]
```
...happens here...
```
  bool queryIsReadOnly = sqlite3_stmt_readonly(statement);
  if (readOnly && !queryIsReadOnly) {
    error = [NSString stringWithFormat:@"could not prepare %@", sql];
    return @[error];
  }
```
...and this bug happens regardless the value of `readOnly` in the `db.exec(...)` call, I suspect the problem is in the `sqlite3_stmt_readonly(...)` not properly detecting the type of the `create table ...` SQL statement.

**Comment by tkrajina** [comment]
Note also that the bug happens even with the `db.transaction()` instead of `db.exec()`. The reason why I used `db.exec()` is that `db.transaction()` also isn't yet exported in the `.d.ts` file for SQLite. This is something I planned to fix in a future PR (if you are OK with it).

Here's the `componentDidMount()` with the transaction executing code (still failing with the same error):

```
  async componentDidMount() {
    const db = SQLite.openDatabase("dbdb.db") as WebSQLDatabase;
    (db as any).transaction(
      (tx: any) => {
        tx.executeSql(
          "create table if not exists tasks11 (id INTEGER primary key not null)",
          [],
          (_tx: any, rs: any) => {
            Alert. alert("rs=" + JSON.stringify(rs));
          },
          (_tx: any, err: any) => {
            Alert.alert("2error=" + JSON.stringify(err));
          }
        );
      },
      (error: any) => {
        Alert.alert("1error=" + JSON.stringify(error));
      },
      (success: any) => {
        Alert.alert("2success=" + JSON.stringify(success));
      }
    );
  }
```

**Comment by cruzach** [comment]
Hi @tkrajina- I'm trying to reproduce this error, but it seems to be successfully creating the table for me on iOS (iPhone 7, v11.4), using Expo client. What version of the Expo client are you using?

Can you try out [this example snack](https://snack.expo.io/@charliecruzan/github.com-expo-sqlite-example) and see if it works properly on your device?

**Comment by tkrajina** [comment]
@cruzach thanks to looking into this!

I uninstalled and reinstalled the Expo client now. App version is `2.11.1`. 

Tried your snack now, same error:
```
Error code 1: no such table: items
- node_modules/expo-sqlite/build/SQLite.js:36:34 in _deserializeResultSet
- node_modules/expo-sqlite/build/SQLite.js:17:48 in <unknown>
- ... 10 more stack frames from framework internals
```
I just changed to add the callback with the error here:
```
  componentDidMount() {
    db.transaction(tx => {
      tx.executeSql(
        'create table if not exists items (id integer primary key not null, done int, value text);' ,
        [],
        (_, rs) => Alert.alert("rs=" + JSON.stringify(rs)), // <--- added this
        (_, err) => Alert.alert("err1=" + err)  // <--- and this
      );
    });
  }
```
Here's a screenshot of the result:
![IMG_0643](https://user-images.githubusercontent.com/379243/59781784-d5346b00-92bc-11e9-9c08-57e3dbf5d22e.PNG)

**Comment by GalacticSmarties** [comment]
Following my upgrade to SDK 33, I am getting the same error in the iOS Simulator running 10.3 on an iPhone 5. 

could not prepare CREATE TABLE IF NOT EXISTS Recordings (ID INTEGER PRIMARY KEY, authorID INTEGER, name TEXT, status TEXT , recordingType TEXT CHECK( recordingType IN ('DRILL','CONGRATS','FEEDBACK','NOTIFICATION', 'DRILL PREP','BETTERNEXT')), recordingPath TEXT, AssociatedDrillID INTEGER, updDT DATE);
- node_modules/expo-sqlite/build/SQLite.js:36:34 in _deserializeResultSet
- node_modules/expo-sqlite/build/SQLite.js:17:48 in <unknown>

iPhone6 running 10.3.1 does NOT have this problem.
Hope this helps.

**Comment by FabianOMB** [comment]
I'm having the same issue when I run expo on an iPhone 5 with iOS 10.3.3 after upgrade to SDK33. I can read (i.e. make selects) but when I try to do an update or delete I get "could not prepare...".
