### ISSUE TITLE
[expo-av] shouldCorrectPitch is ignored without specifying pitchCorrectionQuality

### ISSUE THREAD

**Issue by colinux** [expo/expo#4657]
### Environment

 Expo CLI 2.20.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.6 => 33.0.6
      react: 16.8.6 => 16.8.6
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ~3.11.0 => 3.11.0

### Steps to Reproduce

Play a sound with a `rate` and `shouldCorrectPitch` options, without specifying the new `
pitchCorrectionQuality`, using `setStatusAsync` method API.

```js
 // playback creation
 playback.setStatusAsync({
    shouldPlay: true,
    rate: 1.6,
    shouldCorrectPitch: true,
 });
```
Note: only the `setStatusAsync` method API seems to be affected. This work fine with `setRateAsync`.

### Expected Behavior
Pitch is corrected (documentation is saying there is a default `pitchCorrectionQuality`.)

### Actual Behavior

Pitch is not corrected (`shouldCorrectPitch` option is ignored).

However if we specifying `pitchCorrectionQuality` when setting `shouldCorrectPitch`, this works fine :

```js
 // playback creation
 playback.setStatusAsync({
    shouldPlay: true,
    rate: 1.6,
    shouldCorrectPitch: true,
    pitchCorrectionQuality: Audio.PitchCorrectionQuality.Low,
 });
```

### Reproducible Demo

https://snack.expo.io/@colinux/audio-no-default-pitch-correction

**Comment by cruzach** [comment]
Hi @colinux! I don't believe this is a bug- as only `setRateAsync` is said to have a default `pitchCorrectionQuality`

Check out the [source code](https://github.com/expo/expo/blob/master/packages/expo-av/src/AV.ts#L286) if you want to take a closer look!
