### ISSUE TITLE
[docs] Testing docs out of date.

### ISSUE THREAD

**Issue by Asday** [expo/expo#4658]
https://docs.expo.io/versions/latest/guides/testing-with-jest/#jest-configuration lists a `transformIgnorePatterns` that was valid in SDK32, but no longer matches what is in `jest-expo/jest-preset.js`:

```es6
jestPreset.transformIgnorePatterns = [
  'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)',
];
```

I discovered this as _some_ of my tests were failing with:

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/asday/code/src/gitlab.artumi.com/forensictesting/empirical/collectors_app/node_modules/@unimodules/core/build/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './AdapterProxy';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/expo-constants/src/ExponentConstants.ts:1:1)

**Comment by Asday** [comment]
Introduced with https://github.com/expo/expo/commit/fa1e1678bf53d5e8d83c2a230ef0b002f4cfb2dc#diff-717d4308015eba6179d92dc5374ad243

**Comment by cruzach** [comment]
Hi @Asday! Thanks for pointing this one out- do you want to make a PR to the docs?

**Comment by Asday** [comment]
I briefly looked into it when I opened the issue, but I'm on the clock, it wasn't stopping work, and I couldn't immediately figure out how to, so I figured just opening an issue would be good enough.

Perhaps at the weekend, if nobody else beats me to it?

**Comment by Asday** [comment]
Much appreciated.  :heart:

**Comment by AudyOdi** [comment]
@cruzach hi! Is this changes applied to the latest version of the docs? Because I'm still seeing the non-updated version in latest docs (screenshot below)
![image](https://user-images.githubusercontent.com/11345526/60111588-ce1bca00-97a0-11e9-985f-71f041602c6e.png)

As you can see in the screenshot above, no `@unimodules` before `sentry-expo`. But if I change the version to be specific SDK 33, it will show the updated version (screenshot below).

![image](https://user-images.githubusercontent.com/11345526/60111721-11763880-97a1-11e9-993f-40c045b533ee.png)

**Comment by cruzach** [comment]
It should be applied! I just checked, and seems like it's consistent across both of these pages: 

https://docs.expo.io/versions/latest/guides/testing-with-jest/

https://docs.expo.io/versions/v33.0.0/guides/testing-with-jest/

**Comment by AudyOdi** [comment]
just checked once again and it's all good! I think it's my cache, sorry for the false alarm!
