### ISSUE TITLE
Expo not responding with console.log statement in ref

### ISSUE THREAD

**Issue by James2516** [expo/expo#466]
### Environment

1. `react-native -v`:  
react-native-cli: 2.0.1
react-native: 0.45.1
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10

- Target Platform: Android

- Development Operating System: Windows

### Steps to Reproduce

(Write your steps here:)

1. Clone https://github.com/James2516/drawer-app
2. npm install && npm start
3. remove `console.log(this.drawer);` from https://github.com/James2516/drawer-app/blob/master/src/components/Main.js#L15
4. App now loads in Expo.
5. put  `console.log(this.drawer);` back to the same place.
6. Expo will never load (not responding)

**Comment by JulianKingman** [comment]
If I wait a while, I see this error, which is weird because I don't reference or use the Camera in any of these components.
![simulator screen shot sep 1 2017 9 56 23 am](https://user-images.githubusercontent.com/1566400/29972934-df8fa2fc-8efb-11e7-9572-5d81bbe8d967.png)

**Comment by James2516** [comment]
I think this has to do with some of the properties of the object which resulted in some sort of recursive calls among the properties?

**Comment by dikaiosune** [comment]
Hi! Sorry for the delay in getting to this. Unfortunately the repro case you've linked in your report 404s. If you're able to reproduce this on the latest SDK version, can you post back and I'll reopen? Thanks!

**Comment by James2516** [comment]
Try this: https://snack.expo.io/HkPZjE2n-

**Comment by dikaiosune** [comment]
Hm, the error I'm seeing is from referencing the `ref` variable outside of the ref callback (line 16, it's not in a scope where ref is defined).

![screenshot_20171011-174918](https://user-images.githubusercontent.com/6812281/31473975-ae7bd5fc-aeac-11e7-8215-584d3ad882df.png)

**Comment by James2516** [comment]
Ok i'm not able to reproduce it, couldn't remember what's the case where i encountered the problem or maybe it got fixed. Will reopen if i come across it again.

**Comment by ptaking** [comment]
Try this: https://snack.expo.io/HkcEZumjz
Expo crashed.
