### ISSUE TITLE
How to work with localized number formats in Expo?

### ISSUE THREAD

**Issue by lukewlms** [expo/expo#4662]
Our app needs to use localized number formats for input and output.

E.g. 1,000.00 vs 1.000,00

[This solution](https://stackoverflow.com/a/56243866/152711) works in RN, but only with react-native-localize.  Is this not possible in Expo?  It would seem like quite a strong limitation.

**Comment by cruzach** [comment]
Hi @lukewlms! 

For questions like these (basically anything but a bug reports), you're better off posting on our [forums](https://forums.expo.io/)

But- I think your best option is to use Expo's [Localization library](https://docs.expo.io/versions/latest/sdk/localization/) to get the locale string, and then [this function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) for the rest 👍

**Comment by lukewlms** [comment]
@cruzach That works - excellent, thanks a lot!

Using like this:

`const thousandsSeparator = (1000).toLocaleString("locale")[1] === "," ? "," : ".";`
