### ISSUE TITLE
React-Native Web crashes on Edge

### ISSUE THREAD

**Issue by abhishek-raj** [expo/expo#4663]
### Environment

Expo CLI 2.20.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

My target is Web.

### Steps to Reproduce

1. Create a new SDK33 project and run the web version on Microsoft Edge Browser.

### Expected Behavior
Should run normally like it does on Firefox.

### Actual Behavior
It crashes with this error:
```
node_modules/expo/build/ScreenOrientation/ExpoScreenOrientation.web.js
src/ScreenOrientation/ExpoScreenOrientation.web.ts:53
  50 | }
  51 | 
  52 | if (orientation) {
> 53 |   orientation.addEventListener('change', emitOrientationEvent);
  54 | } else {
  55 |   window.addEventListener('orientationchange', emitOrientationEvent);
  56 | }
```
### Reproducible Demo
Just the default expo project would do. Snack does not support react-native-web(Does it?).

Also I checked and apparently Edge has a global variable called `orientation` and thus this is breaking in Edge.

Edit: Tested it on Edge Dev based on Chromium, it works fine there. Only the Edge that comes with Windows currently has the rogue `orientation` variable which causes the crash.

**Comment by abhishek-raj** [comment]
It seems the code here https://github.com/expo/expo/blob/360d1cd7917f9091248d1821b597a2150344ceee/packages/expo/src/ScreenOrientation/ExpoScreenOrientation.web.ts#L39 is causing the error.

The msOrientation object does not support addEventListener (as used here https://github.com/expo/expo/blob/360d1cd7917f9091248d1821b597a2150344ceee/packages/expo/src/ScreenOrientation/ExpoScreenOrientation.web.ts#L53) according to Microsoft Docs(https://msdn.microsoft.com/en-us/ie/dn342934(v=vs.94)).

**Comment by mamang126** [comment]
When is planned this bug to be solved?
Is known any work arround?

Thanks

**Comment by vandre** [comment]
> When is planned this bug to be solved?
> Is known any work arround?
> 
> Thanks

The reason why addEventListener exception occurs is because for Edge orientation is a string property, not an object. On my local I fixed it  by changing line 34 in node_modules\expo\build\ScreenOrientation\ExpoScreenOrientation.web.js to:

if (orientation && **typeof(orientation)!=='string'**) {

**Comment by pacheco7** [comment]
> if (orientation && typeof(orientation)!=='string') {

I had the same issue and the statement above solves it.

**Comment by mikailcetinkaya** [comment]
How may i get this fix ?

**Comment by thebetterjort** [comment]
Still getting this error in SDK 35.
