### ISSUE TITLE
[expo-gl] 'EXGL-CPP/UEXGL.h' file not found in non-expo project

### ISSUE THREAD

**Issue by allthetime** [expo/expo#4664]
### Environment

React Native v0.59
Xcode Version 10.2.1
Non-expo project

### Steps to Reproduce

Attempt to build/run xcode project with all necessary pods (unimodules, expo-gl-cpp) installed

### Actual Behavior

receive this error:

`'EXGL-CPP/UEXGL.h' file not found`

**Comment by cruzach** [comment]
Hi @allthetime, 

We need more information to solve your issue, **especially** a way for us to reproduce the behavior.

Like it says in the `expo-gl-cpp` repo, it should be used in conjunction with [expo-gl](https://github.com/expo/expo/tree/master/packages/expo-gl).

**Comment by allthetime** [comment]
@cruzach I have installed expo-gl-cpp via cocoapods as well, the pod and all its files are definitely there. 

To reproduce you simply follow all the instructions given at the expo-gl readme... install unimodules, install expo-gl-cpp, and install expo-gl. After following all those steps, you attempt to run the *.xcworkspace project

**Comment by allthetime** [comment]
@cruzach I have just confirmed that with a completely clean project built with `react-native init` on the latest stable version of RN. Following the expo-gl install instructions leads to this error, not being able to find the cpp header file. I can compile and run the app all the way past installing `expo-gl-cpp`, but after installing `expo-gl` the compile error appears.

Full steps to reproduce:

```
react-native init expo-gl-test && cd expo-gl-test
npm install react-native-unimodules
```

now edit Podfile as per instructions at https://github.com/unimodules/react-native-unimodules#configure-ios and do:

`pod install`

edit AppDelegate.h and AppDelegate.m as per instructions at https://github.com/unimodules/react-native-unimodules#configure-ios

after unimodules is set up the rest is:

```
npm install expo-gl-cpp
pod install
```

The project compiles and runs up to this point, but fails after the next step:

```
npm install expo-gl
pod install
```

And once again, this is in a clean project, freshly initialized with nothing else done but the previous commands and edits.

**Comment by Jlexyc** [comment]
The same issue after `expo eject` using Expo Kit.

**Comment by crubier** [comment]
Same problem here on a bare react native project ... Any info about at least a workaround for this issue @Jlexyc @allthetime ?

**Comment by crubier** [comment]
Ok found the cause of the problem, the imports are of the form 

```
#import <EXGL-CPP/EXGL.h>
```

But the framework is called EXGL_CPP with an underscore not an hyphen, by correcting it to:

```

```
#import <EXGL_CPP/EXGL.h>
```

I was able to solve this problem (only to fail on other problems later...)

**Comment by crubier** [comment]
The question is: why is the framework called EXGL_CPP in XCode, while it is named EXGL-CPP everywhere in the source code ? Does Unimodules or CocoaPods do something strange to modules with an hyphen in their names?

**Comment by tsapeta** [comment]
Hey guys and sorry for not responding - we have a lot of other tasks to do going on right now.
The framework should be called `EXGL-CPP` as it is in the source code - and this is how it should be installed by CocoaPods. Also, `EXGL` declares in the podspec that is depends on `EXGL-CPP` (with an hyphen).
https://github.com/expo/expo/blob/d2409774d86c127116f9307a0dffb64ade6f2d70/packages/expo-gl/ios/EXGL.podspec#L21-L23

@crubier, if it would be a CocoaPods thing then it would also affect Expo client builds that work as expected, but we use version `1.8.1` in the repo so it can make the difference. I'll check it out and let you know soon.

**Comment by crubier** [comment]
This only happens when the option `use_frameworks!` is enabled in CocoaPods

**Comment by tuanna1601** [comment]
Any update on this? I'm encountering this issue too, but I can't remove `use_frameworks!` from my Podfile because it will break other dependencies

**Comment by tsapeta** [comment]
I've just checked this issue and can confirm that it happens only when `use_frameworks!` is used. It turns out that hyphens are not allowed in framework names and CocoaPods are converting the package name to framework name by replacing hyphen with underscore. The proper solution would be to change all `EXGL-CPP` references to `EXGL_CPP`. I'll make a PR for this shortly 🙂

**Comment by OKNoah** [comment]
Oddly experiencing this. Podfile:

```ruby
# source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods'

platform :ios, '14.1'

target 'tinyrama' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  use_unimodules!

  target 'tinyramaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
```
