### ISSUE TITLE
[ios] Enable "multiple xcodeproj" files with CocoaPods 1.7 once FBSDK supports it

### ISSUE THREAD

**Issue by ide** [expo/expo#4667]
FBSDK in expo-facebook is keeping us back from enabling the "multiple xcodeproj" option in CocoaPods 1.7 (speeds up Xcode) as well as the "incremental installation" option (speeds up `pod install`). Once FBSDK changes the way it does headers and we upgrade it, we can try enabling these options again.

**Comment by sjchmiela** [comment]
The `:project_name` property added in 1.8 beta unblocks us on this — we are able to specify same `:project_name` on both `FBSDKCoreKit` and `FBSDKLoginKit` and thus allow importing by `"../path/"`.
