### ISSUE TITLE
expo-image-picker stopped working after upgrading to Expo SDK 33

### ISSUE THREAD

**Issue by bnolens** [expo/expo#4669]
## 🐛 Bug Report

I've got a detached Expokit app I've been upgrading from SDK 27 to SDK 33. 
I ran into problems with the `expo-image-picker` in this last step upgrading from SDK 32 to SDK 33. 
Opening the camera using `launchCameraAsync` fails on Android when the project also includes the `rn-fetch-blob` dependency. 

### Environment

```     Expo CLI 2.20.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.3.2 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.19
      @types/react-native: ^0.57.60 => 0.57.60
      expo: ^33.0.0 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^2.16.0 => 2.16.0
    npmGlobalPackages:
      expo-cli: 2.20.1
```

### Steps to Reproduce

1. Create a clean, managed workflow,  Expo SDK 33 project using `expo init`
2. Eject by running `yarn eject`
3. [Add `rn-fetch-blob` dependency](https://github.com/joltup/rn-fetch-blob#user-content-installation)
4. import `expo-image-picker` in your js and add a button that calls `launchCameraAsync` on press.
5. Build on an Android device and call the image picker.

### Expected Behavior

The native Android camera opens.

### Actual Behavior

The `launchCameraAsync` function throws an error and the native Android camera doesn't open.

![Screenshot_20190620-143513_accountable-app-33](https://user-images.githubusercontent.com/221925/59850822-6a8e3880-936b-11e9-84cc-fa60162feb82.jpg)

### Reproducible Demo

https://github.com/bnolens/broken_image_picker_demo

**Comment by iRayzer** [comment]
Hello,
Any news about this ?
I am stuck with it too so I cannot upgrade :(

**Comment by tsapeta** [comment]
Hey @iRayzer, we will be investigating this issue today - will keep you posted 😉

**Comment by bnolens** [comment]
That fixed it for me! Thanks @bbarthec!
