### ISSUE TITLE
Get stuck at `Making sure project is set up correctly`

### ISSUE THREAD

**Issue by leo108** [expo/expo#467]
I have just created a new project via `exp init`, and I run `exp start` but it keeps showing `Making sure project is set up correctly` for a long time, it works well a few days ago.

my exp version is `43.0.0`

**Comment by leo108** [comment]
Is there any option like `-v` or `--verbose` to see more detail of the progress

**Comment by dikaiosune** [comment]
Sorry this slipped through the cracks. Is this still happening?

**Comment by leo108** [comment]
@dikaiosune no, it just happened that time

**Comment by dikaiosune** [comment]
Glad to hear it! Unfortunately that means we won't have a reliable reproduction that we can use to fix this. Going to give it a close for now, please comment back so I can reopen if you see it again!
