### ISSUE TITLE
JS bundle doesn't rebuild/reload sometimes when there's a syntax error

### ISSUE THREAD

**Issue by vonwao** [expo/expo#4675]
Expo CLI 2.15.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

(on iPhone) 
Any tips?

**Comment by cruzach** [comment]
Hi @vonwao!

You should be able to hit `reload JS` on your iPhone to reload it after hitting a syntax error.

Let me know if that doesn't work, though!

**Comment by vonwao** [comment]
@cruzach  No, it doesn't work.  Sometimes I get the same error 5 or more times, and then suddenly it works.  Sometimes it gets stuck in a certain state for half a minute or more.  Sometimes it suddenly works, sometimes I have to restart expo manually after waiting for a long time (but that also takes time). 

Is Expo well supported on Windows?  Could this be my problem?

**Comment by vonwao** [comment]
Does android work better?  If so, I'm thinking of getting an android device.  I know android can also connect locally via ADB.  Is it better/faster if I tether the device to laptop via ADB?

**Comment by cruzach** [comment]
Many people use Expo on Windows OS (especially Windows 10), so I don't think that's the problem
