### ISSUE TITLE
Android build failing for a new completely blank ejected ExpoKit project

### ISSUE THREAD

**Issue by mjgallag** [expo/expo#4676]
### Environment
```
  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.20.2
```
### Steps to Reproduce
1. clone `https://github.com/thunkable/expo-kit-diff` (this is just a new completely blank ejected ExpoKit project)
1. `cd expo-kit-diff`
1. `npm install`
1. `cd android`
1. `./gradlew app:assembleDebug --stacktrace`

### Actual Behavior

```
> Configure project :expo-gl-cpp
Project evaluation failed including an error in afterEvaluate {}.
java.lang.IllegalStateException: compileSdkVersion is not specified.
```

**Comment by cruzach** [comment]
Hi @mjgallag- do you have the Android NDK installed? I think I saw a similar issue recently and that was the fix

**Comment by mjgallag** [comment]
Hmmm, let me try that now, thanks. Turns out it's working on a colleague's computer.

**Comment by mjgallag** [comment]
That did it. Terrible error message from gradle. I guess it doesn't automatically try and download like it does for SDKs. Thanks! Hopefully someone will see this when they google next time.

**Comment by mjgallag** [comment]
this issue is a duplicate of #4483.
