### ISSUE TITLE
expo install react-native-reanimated installs the wrong version of reanimated (1.0.1 vs 1.0.0-alpha.11)

### ISSUE THREAD

**Issue by wcandillon** [expo/expo#4678]
`expo install react-native-reanimated` installs an older version of `react-native-reanimated` as the one shipped by Expo SDK 33. I noticed that the TS declaration for that module is much older after running `expo install react-native-reanimated` in compare to the one you have by default with SDK 33.

**Comment by wcandillon** [comment]
Expo SDK 33 ships `reanimated@1.0.1`, `expo install` installs `reanimated@1.0.0-alpha.11`

**Comment by brentvatne** [comment]
updated the expo package to 33.0.7 which changes the `bundledNativeModules.json` file to the correct version!
