### ISSUE TITLE
npm start stuck in Starting packager...

### ISSUE THREAD

**Issue by kinglywork** [expo/expo#468]
## Description

npm start stuck in Starting packager... without any error message.

I debugged the code of exp and xdl and I found the process hung at getting schema from https://exp.host/--/xdl-schema/19.0.0
and getting versions from 
https://exp.host/--/api/v2/versions
I send request with postman to these urls and they response very slow and fail to response mostly.

Any idea to avoid getting schema from server?
Or maybe the server should be fixed.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.1.0
* `npm ls react-native`: 0.46.4
* `npm ls expo`: 19.0.1
* `node -v`: 3.11.0
* `npm -v`: 3.10.10
* `yarn --version`:  none
* `watchman version`: 4.7.0

Also specify:

1. Operating system: MacOs
2. Phone/emulator/simulator & version: IOS

**Comment by kinglywork** [comment]
maybe it has something to do with the network environment, close this

**Comment by CrazyWr** [comment]
hey, buddy, How do you  fix it? my vpn is not work

**Comment by kinglywork** [comment]
![screen shot 2017-08-10 at 16 14 04](https://user-images.githubusercontent.com/2428973/29161223-02927970-7de8-11e7-8805-2b033bd65480.png)

replace the two places(refer to the arrow in the picture) with fake json which you get from the url
