### ISSUE TITLE
Add react-native-datetimepicker to SDK

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4691]
Another set of APIs extracted in lean core, another lib we need to add.

**Comment by tsapeta** [comment]
Unfortunately, this lib uses AndroidX that we can't use right now. We will need to upgrade our project to use AndroidX before we get it into our codebase. Related issue: #2956

**Comment by brentvatne** [comment]
we should add this for sdk36 as react-native 0.61 is probably going to be the last release to include date picker components in core. so if we add this for sdk36 we give people a release where they can use either react-native-datetimepicker or the core components, which makes it easier to transition
