### ISSUE TITLE
APK build gives me permission errors on Google Play console

### ISSUE THREAD

**Issue by kresogalic8** [expo/expo#4696]
Hello, i've built an APK so I can publish my app, and then I got this error in console.

android.permission.CAMERA,android.permission.RECORD_AUDIO,android.permission.READ_PHONE_STATE,android.permission.READ_CONTACTS. 

Here's my package.json and angular.json

<img width="1260" alt="Screenshot 2019-06-24 at 09 42 15" src="https://user-images.githubusercontent.com/7289406/60000401-6e200900-9664-11e9-9142-61b73627a138.png">
<img width="1260" alt="Screenshot 2019-06-24 at 09 42 23" src="https://user-images.githubusercontent.com/7289406/60000402-6e200900-9664-11e9-9fcc-bf0ec0e14be2.png">

**Comment by cruzach** [comment]
Hi @kresogalic8! Could you copy/paste the full error? A list of Android permissions doesn't tell us too much. 

Also- no problems when running your app in the Expo client app?

**Comment by kresogalic8** [comment]
Sure, here's the screenshot on google play console. Btw I don't use anything in my app which requires permissions. And yes, I don't have any error in console when I run the app with expo start.

<img width="1260" alt="Screenshot 2019-06-24 at 22 23 28" src="https://user-images.githubusercontent.com/7289406/60049524-bffd7900-96ce-11e9-951e-d497ef92ed47.png">

**Comment by kresogalic8** [comment]
@cruzach any help?

**Comment by cruzach** [comment]
Take a look at the [docs for app.json](https://docs.expo.io/versions/latest/workflow/configuration/), specifically the `android.permissions` key.

> To use ALL permissions supported by Expo, do not specify the "permissions" key.

This is what you have configured now.

> To use ONLY the following minimum necessary permissions and none of the extras supported
      by Expo, set "permissions" to []

This is what you should configure
