### ISSUE TITLE
Expo Speech Crashes App, no error checking or error msg

### ISSUE THREAD

**Issue by cdcv** [expo/expo#4698]
## 🐛 Bug Report
Expo Speech currently has inadequate error checking, and if the passed parameter isn't as expected, crashes the entire app without ado or any information.
In my case, this meant that all of a sudden when a variable changed type, the whole app started crashing, and it was completely unclear why, or what was causing it, or that it had anything to do with Speech.

Please added more defensive programming around this, and make sure that whatever is passed, it can't crash the app!
Workaround for now: *only pass it a string*!
Thanks

### Environment
  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.1
      Shell: Unknown - /usr/local/bin/fish
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.3 => 5.1.3 
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.9.1 
    npmGlobalPackages:
      expo-cli: 2.20.2

### Steps to Reproduce
var score = "zero"
Speech.speak(score,{pitch:.85,rate:.75});
//works
var score = 0
Speech.speak(score,{pitch:.85,rate:.75});
crashes native app, no error msg

**Comment by bbarthec** [comment]
@cdcv, each Expo module has been rewritten to TypeScript to prevent runtime checking for correctness of arguments types.
I recommend migrating to TypeScript or provide some type checking on your side.
I'm closing this issue as we are stripping of any runtime type-checking code since TypeScript is taking care of it for us 🤝.

**Comment by melihmucuk** [comment]
This issue about iOS 13. It works on below version 13. I recommend open this issue again and find a workaround.
