### ISSUE TITLE
facebook: support long-lived token flow, with token refresh

### ISSUE THREAD

**Issue by skabbes** [expo/expo#47]
I am trying to implement a facebook login flow that uses a long-lived token for server access.  The server token will expire in 60 days after the initial exchange.

https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension

The native SDKs provide a way to request a new short-lived token (which will be exchanged for a long lived on on the server) in the background with no user interaction.

From what I can tell, Exponent does not expose the necessary API calls into the facebook SDKs to accomplish this.

I believe the relevant API calls needing to be implemented would be:

iOS:
[renewSystemCredentials](https://developers.facebook.com/docs/reference/ios/4.15/class/FBSDKLoginManager/)

Android:
[refreshCurrentAccessTokenAsync](https://developers.facebook.com/docs/reference/android/current/class/AccessToken/)

I think this is a completely necessary API call for anyone who wants integrate with Facebook for anything more than simply login.

**Comment by dikaiosune** [comment]
Hi! We're tracking feature requests on Canny now. I [created one](https://expo.canny.io/feature-requests/p/long-lived-token-for-facebook-api) for this there. Thanks!
