### ISSUE TITLE
Custom Expo client crashes when using MapView and 'google' as the provider

### ISSUE THREAD

**Issue by vinsidious** [expo/expo#4704]
### Environment

```
  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.7 => 16.8.15
      @types/react-native: ^0.57.63 => 0.57.63
      @types/react-navigation: ^3.0.5 => 3.0.5
      expo: ^33.0.3 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.20.2
```

Targets: `ios` and `android`

### Steps to Reproduce

On a [**custom iOS Expo client**](https://docs.expo.io/versions/latest/guides/adhoc-builds/), do the following:

1. Open your custom Expo Client app
2. Go to the `Explore` tab
3. Tap `Expo APIs` row
4. Click the `Expo Components` tab on the bottom tab bar
5. Scroll down and click on `Maps`. The default Apple Maps should be loaded
6. Flip the `Use Google maps` toggle and the app will crash immediately

### Expected Behavior

The app shouldn't crash on a custom iOS Expo client when using `MapView` with `google` as the provider. 

### Actual Behavior

The app crashes.

### Reproducible Demo

I'm not sure how to create a reproducible demo since this bug only seems to affect custom-built iOS Expo clients. That being said, this bug is **very** easy to reproduce using the existing `Expo APIs` project on a custom iOS Expo client.

**Comment by cruzach** [comment]
Hey @vinsidious, thanks for bringing this up!

We're aware of it actually, and have a PR already. So this issue should close once [4674](https://github.com/expo/expo/pull/4674) and associated PRs land!
