### ISSUE TITLE
SVG issue

### ISSUE THREAD

**Issue by ssbers** [expo/expo#4705]
### Environment

Expo CLI 2.19.5 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.npm-global/bin/npm
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.5

After update svg modules, i've got some problems with this kind of images, which you can see on your own site (in preview) in the link below:
https://docs.expo.io/versions/latest/sdk/svg/

![issue 1](https://user-images.githubusercontent.com/33072844/60044663-86773e80-96cb-11e9-9974-c0621db07ff6.jpg)

**Comment by cruzach** [comment]
Hi @ssbers- I just updated the Snack, should be working now. Let me know if you still run into an issue with it 👍
