### ISSUE TITLE
Could not download FontAwesome icons

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#4707]
### Environment
Sentry Catch it in `iOS 12.3.1`
SDK 33.

### Steps to Reproduce
Not sure. It was caught by Sentry, but it may be an error loading FontAwesome

### Expected Behavior
Download FontAesome properly

### Actual Behavior
Triggers an error

### Reproducible Demo
Hard to reproduce. Not sure if it was a temporal problem.

### Full description
I got this error in Sentry:
```
Could not download from 'https://d1wp6m56sqw74a.cloudfront.net/~assets/5a293a273bee8d740a045d9922b9a9ae'
```
If you download that file, it's FontAwesome

I have 2 questions:
1. Why is it downloading FontAwesome? I don't use FontAwesome in the app. it should not download it
2. Why is it downloading FontAwesome? Why isn't it attached to the build file?

Now, important data:
A few months ago I reported this issue: https://github.com/expo/expo/issues/3216
It basically is a friend that has an iPhone 8 that he NEVER could open the app. He always gets a blank screen error.
He has an iPhone 8, and this error (the one that I'm reporting now) also happens in iPhone 8.

Is there a way to avoid downloading FontAwesome if I don't use it? I use a lot of fonts from `@expo/vector-icons`, but FontAwesome is not one of them

**Comment by brentvatne** [comment]
you'll need to provide a reproducible example for us to understand this. it's likely that some library you use actually uses fontawesome without you knowing it

**Comment by zocheyado** [comment]
Also getting this error from sentry. In fact getting the exact same asset hash. Same as OP, only happening on iOS (I have examples of iPhone 6, 8 and X). Not using phone awesome, only expo vector-icons.

**Comment by brentvatne** [comment]
my above comment still stands

**Comment by BrodaNoel** [comment]
@brentvatne this is not something reproducible. We can not create a reproducible example. Sentry report those errors some times. 1 time per week (with 100 active users).

In my App.js I have:
```
import {
  MaterialCommunityIcons,
  MaterialIcons,
  Feather,
  SimpleLineIcons,
} from '@expo/vector-icons';

//

Font.loadAsync(MaterialCommunityIcons.font);
Font.loadAsync(MaterialIcons.font);
Font.loadAsync(Feather.font);
Font.loadAsync(SimpleLineIcons.font);
```

Then I use it like:
```
import { MaterialCommunityIcons } from '@expo/vector-icons';

//

<MaterialCommunityIcons name="information-outline" size={24} color="#000" />
```

**Comment by brentvatne** [comment]
this is likely to be a network connection issue - perhaps the user starts downloading the asset and loses a connection or something along those lines. you can use `assetBundlePatterns` to embed the fonts in your app binary so they don't need to be downloaded

**Comment by BrodaNoel** [comment]
Here some Sentry errors related to this kind of network-connection-issue:
<img width="1190" alt="Screen Shot 2019-11-14 at 17 04 27" src="https://user-images.githubusercontent.com/1837969/68892049-d8fbda80-0700-11ea-993b-99b80a6bb74f.png">

**Comment by BrodaNoel** [comment]
@brentvatne I actually have them set in `assetBundlePatterns`, but it doesn't seems to be working:

```
"assetBundlePatterns": [
      "node_modules/@expo/vector-icons/fonts/MaterialCommunityIcons.ttf",
      "node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf",
      "node_modules/@expo/vector-icons/fonts/Feather.ttf",
      "node_modules/@expo/vector-icons/fonts/SimpleLineIcons.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Regular.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Medium.ttf",
      "src/styles/fonts/Montserrat/Montserrat-SemiBold.ttf",
      "src/styles/fonts/Montserrat/Montserrat-Bold.ttf",
      "src/styles/imgs/nofilter-icon.png",
      "src/styles/imgs/nofilter-icon-android.png",
      "src/styles/imgs/nofilter-logo-v.png",
      "src/styles/imgs/splash-screen-ph.png",
      "src/styles/imgs/splash-screen-ph.jpg",
      "src/styles/imgs/noti-icon.png"
    ],
```

**Comment by BrodaNoel** [comment]
Oh wait... I see that fonts are not un `/fonts` anymore.
Now they are in `node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf`. Is that the correct path?

**Comment by brentvatne** [comment]
i think so - you could also use `**/MaterialCommunityIcons.ttf` instead, that will just match the icon wherever it is located in the project. we should make this easier

**Comment by BrodaNoel** [comment]
@brentvatne thank you a lot! I just changed them to

```
      "node_modules/@expo/vector-icons/**/MaterialCommunityIcons.ttf",
      "node_modules/@expo/vector-icons/**/MaterialIcons.ttf",
      "node_modules/@expo/vector-icons/**/Feather.ttf",
      "node_modules/@expo/vector-icons/**/SimpleLineIcons.ttf",
```

**Comment by brentvatne** [comment]
i made this issue to follow up on getting better documentation around `assetBundlePatterns` https://github.com/expo/expo/issues/6272

also i made this issue to document the specific type of error you encountered: https://github.com/expo/expo/issues/4707

**Comment by outaTiME** [comment]
@brentvatne this is glob expression?

```
node_modules/@expo/vector-icons/**/{MaterialIcons,MaterialCommunityIcons}.ttf
```

thanks !!!
