### ISSUE TITLE
Using GLView causes crash on iOS simulator

### ISSUE THREAD

**Issue by lunarraid** [expo/expo#471]
After creating a new project using XDE and using the GLView demo code from https://snack.expo.io/SJaCWirsg, the app crashes immediately on load in the iOS simulator (currently using iOS 10.3). It seems that attempting to render a GLView as a component in any fashion causes this. I do not see the same behavior running in the app on my Android device.

**Comment by nikki93** [comment]
Hi @lunarraid -- will look into this.

FWIW though, generally OpenGL performance is much worse on simulators than on the device for iOS, this is just how the simulator is, even if you write a C++ or Obj-C OpenGL app.

**Comment by nikki93** [comment]
<img width="758" alt="screenshot 2017-09-05 14 29 50" src="https://user-images.githubusercontent.com/49151/30086121-6e55b60c-924e-11e7-8e4a-e58dfd3db40f.png">

^ it's working for me the last time I tried. Could you try again?

**Comment by lunarraid** [comment]
Still seeing the problem, though I just noticed that this is only happening when I choose iPhone 5 as the hardware target. Other targets seem to work.

**Comment by nikki93** [comment]
This use case is hard to support in general because iOS simulator has a slow implementation of OpenGL, and it seems to work sufficiently on new simulators. So closing for now.
