### ISSUE TITLE
Toggle Element Inspector not working

### ISSUE THREAD

**Issue by SantiMA10** [expo/expo#4714]
### Environment

```
Expo CLI 2.20.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^4.0.1 => 4.0.1 
      @types/expo: ^32.0.0 => 32.0.0 
      @types/react: ^16.7.0 => 16.8.2 
      @types/react-native: ^0.57.34 => 0.57.34 
      @types/react-navigation: ^3.0.1 => 3.0.1 
      expo: ^32.0.0 => 32.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.3.2 => 3.3.2 
    npmGlobalPackages:
      expo-cli: 2.20.6
```
On Expo Client with versions: `2.11.1.106175` and `2.11.1.106135`

### Steps to Reproduce

- Open `Developer Menu`
- Press `Toggle Element Inspector`

### Expected Behavior

- Activates the `Element Inspector`

### Actual Behavior

- Nothing

### Reproducible Demo

I'm not providing any demo because it happens with all the apps I try with the `expo-cli` and `expo-client`.

**Comment by cruzach** [comment]
Hi @SantiMA10- I just tested this on my device (iPhone, Expo client v2.11.1.106175), and the element inspector works as intended. What device are you testing this on?

**Comment by SantiMA10** [comment]
Hi!

I usually use my iPhone 8 and the iOS emulator to run our expo app.

Today I'm working with a different computer and it's working properly with my iPhone 8. Here is the `expo diagnostics` for the new computer.

## Environment
```
Expo CLI 2.20.7 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /var/folders/sf/plm98l3d3c7425kld69gwzfw0000gn/T/yarn--1561528822019-0.6902534532578215/node
      Yarn: 1.16.0 - /var/folders/sf/plm98l3d3c7425kld69gwzfw0000gn/T/yarn--1561528822019-0.6902534532578215/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^4.0.1 => 4.0.1 
      @types/expo: ^32.0.0 => 32.0.0 
      @types/react: ^16.7.0 => 16.8.2 
      @types/react-native: ^0.57.34 => 0.57.34 
      @types/react-navigation: ^3.0.1 => 3.0.1 
      expo: ^32.0.0 => 32.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.3.2 => 3.3.2 
```

Tomorrow I can let you if is working with the last `expo-cli` version on my other computer.

**Comment by SantiMA10** [comment]
It still not work on my main mac. :(

![Simulator Screen Shot - iPhone SE - 2019-06-27 at 15 06 06](https://user-images.githubusercontent.com/7255298/60268669-38da1c00-98ed-11e9-82a5-cd67ca962426.png)

**Comment by cruzach** [comment]
Are there any differences in environment between the two? I believe this may be an issue specific to your machine

**Comment by SantiMA10** [comment]
I do not see anything remarkable (only yarn and node versions), if you can give any clue I will appreciate it, if not you can consider the issue close
