### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by joebologna** [expo/expo#4716]
Documentation for FileSystem.writeAsStringAsync is missing a description of the options and what it returns.

[FileSystem.writeAsStringAsync(fileUri, contents, options)](https://docs.expo.io/versions/v33.0.0/sdk/filesystem/#filesystemwriteasstringasyncfileuri-contents-options)

**Comment by cruzach** [comment]
Hi @joebologna! Could you expand a little more? Or better, make a PR?

As far as I know, the docs describe the `options` (although it's just one option- `encoding`), and the method doesn't return anything.

**Comment by joebologna** [comment]
I realized after posting that options were shown. Sorry. I was expecting the return information. I’ll have to look at it again to see if I can make an improvement. 

I was attempting to find an option to append to a file. It seemed a simple use case but appending to files does not appear to be supported by the component.

**Comment by cruzach** [comment]
Ah okay I see. I think the best bet would be to simply `readAsStringAsync`, then append what you need to the returned string, and pass the result to `writeAsStringAsync`. Definitely some room for improvement in that workflow though. 

Going to close this issue, but would love to see a PR from you if you find time to make improvements!
