### ISSUE TITLE
Support data only push notifications

### ISSUE THREAD

**Issue by Roger** [expo/expo#472]
Is there any way to handle data only push notifications?

**Comment by ide** [comment]
This is supported on iOS -- you can omit user-visible properties like the badge count and body. Expo doesn't do anything really special with regard to the delivery of notifications -- most of the work is delegated to Apple/Google. Tell us if you need the content-available flag on iOS.

**Comment by Roger** [comment]
What i want to do, is something like this [2], run js code without displaying a notification or mounting the react components (on both Android and iOS).

react-native support headless js [2], but only on Android, and also needs some java code, so it won't work without ejecting.

1) https://facebook.github.io/react-native/docs/headless-js-android.html
2) https://github.com/zo0r/react-native-push-notification/pull/220

**Comment by ide** [comment]
Yeah that isn't supported right now, partly because it wasn't supported that well on iOS until 10. You'll have to eject if you want that.

**Comment by dikaiosune** [comment]
Giving this a close since we probably won't support for a little while. Please open a [feature request](https://expo.canny.io) if you'd like to give other users a chance to vote for this! Thanks!
