### ISSUE TITLE
[Amplitude] Expo Version Number Submitted to Amplitude Instead of App Version Number

### ISSUE THREAD

**Issue by AryanJ-NYC** [expo/expo#4720]
### Environment

```
Expo CLI 2.18.7 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.6 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.8.0 => 3.11.0 
```

iOS + Android

### Steps to Reproduce
1. Initialize Amplitude (using `Amplitude.initialize) and set the userID (using `Amplitude.setUserId).
2. Log an Amplitude event (using [`Amplitude.logEvent`](https://docs.expo.io/versions/latest/sdk/amplitude/#amplitudelogeventeventname) or [`Amplitude.logEventWithProperties](https://docs.expo.io/versions/latest/sdk/amplitude/#amplitudelogeventwithpropertieseventname-properties)
3. Log into the Amplitude dashboard and find the dispatched event.

### Expected Behavior
The version number logged in the Amplitude dashboard should be the version number denoted in `app.json`

### Actual Behavior
The version number logged in the Amplitude dashboard is that of the Expo application.

### Reproducible Demo
https://snack.expo.io/r1hc6klgS

### Things I Tried
* Manually adding `version` to `properties` parameter of `Amplitude.logEventWithProperties`.
* Manually setting `version` and `app_version` using [`Amplitude.setUserProperties`](https://docs.expo.io/versions/latest/sdk/amplitude/#amplitudesetuserpropertiesuserproperties)

### Notes
According to Amplitude:

> By default, Amplitude tracks the below user properties automatically via our SDKs.

- https://amplitude.zendesk.com/hc/en-us/articles/215562387-Appendix-Amplitude-User-Property-Definitions

**Comment by cruzach** [comment]
Hi @AryanJ-NYC- sorry about this. So are you only seeing this in the Expo client? Have you tested with a standalone Expo app yet?

**Comment by AryanJ-NYC** [comment]
@cruzach No need to apologize! Thanks for any help.

I can confirm that I am only seeing this in the Expo client and not the standalone Expo app (Expo app currently in production and reports the correct app version number).

**Comment by sjchmiela** [comment]
It is unfortunately not possible to set a custom app version number on an Amplitude instance (as per https://github.com/amplitude/Amplitude-iOS/issues/170, it's still a feature request). Amplitude fetches the app version automatically from app resources which are not customizable by us in runtime.

I will add a note to the docs describing this specific behavior to mitigate any further misconceptions. 🙂
