### ISSUE TITLE
Half black curve screen on startup - before splash screen

### ISSUE THREAD

**Issue by IAmAbhishekTomar** [expo/expo#4729]
Hi Team,

Can you please look into this issue...

Device : Iphone 10 IOS 13 Beta

Half black curve screen on startup - before space screen 
https://github.com/facebook/react-native/issues/25405#issue-460912324

**Comment by cruzach** [comment]
Hi @IAmAbhishekTomar - It seems like you've posted the same issue in two different repositories. I suggest digging a little deeper into the issue to find out where you think it may be stemming from, and then posting as a possible bug. Also, be sure to include a way for us to reproduce the issue on our end (we provide an issue template that lists everything you need to include)
