### ISSUE TITLE
How to debug the detached app with chrome Dev Tools?

### ISSUE THREAD

**Issue by CrazyWr** [expo/expo#473]
I had detached my app and ran it with a physical device, and it's good. But there is no response after I shacked my device. How to debug the detached app with chrome Dev Tools?
Environment:
expoSDK: 18.0.0
yarn: 0.27.5
node: 6.9.1
device: iPad mini

**Comment by ide** [comment]
The shaking should still work. You also can go back to Expo Home and then tap on your profile and go to your settings to change the dev menu gesture from the shake to the two-finger touch and see if that  works for you.

**Comment by CrazyWr** [comment]
hey, buddy. thks for response.  When running the detached app that is our own native app not the expo client, Could the shaking  work? And there is no response after I shacked my device.
Also, recently, it took a long long time running the project like this:
![image](https://user-images.githubusercontent.com/19635808/29151932-e4b833d0-7db6-11e7-95f4-dbfc4c769745.png)
or XDE this:
![image](https://user-images.githubusercontent.com/19635808/29151940-f2c36760-7db6-11e7-8220-47cfaa3ebb0a.png)

I'm chinese, I think it may refer to the GFW, but it doesn't work with VPN to US server,
Do you know why is this?

**Comment by dikaiosune** [comment]
@terribleben is there a way to configure the dev menu gesture in ExpoKit?

@CrazyWr I'd suggest disabling the tunnel (gear icon -> change options to lan) since ngrok's tunnel servers are probably at a very high latency from you.
