### ISSUE TITLE
[docs] Cannot find how to enable Android 64bit build for Ejected Expokit app in docs

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#4730]
My app is ejected from Expo 33 and I need to enable Android 64bit build to submit app to Google Play.

I cannot find how to enable Android 64bit build for Ejected Expokit app in docs.

Please help

**Comment by cruzach** [comment]
Hi @changLiuUNSW!

This isn't supported **yet**, but it will be in SDK 34. We're working hard to give developers as much time as possible  to upgrade their apps before Google's deadline of August 1st.

**Comment by changLiuUNSW** [comment]
@cruzach Is SDK 34 a light upgrade ? Do you have ETA for it ?

**Comment by giacomocerquone** [comment]
I still don't quite understand why the ejected application is still build dependent from expo... this and some explanation should really be added in the docs

**Comment by brentvatne** [comment]
we are moving away from expokit and towards a more modular [bare workflow](https://docs.expo.io/versions/v33.0.0/introduction/managed-vs-bare/#bare-workflow) so people can have much more control over their apps when they eject.

**Comment by changLiuUNSW** [comment]
@giacomocerquone for the sake of OTA upgrade, we cannot eject to bare wokrflow :(

**Comment by harisvsulaiman** [comment]
@changLiuUNSW Did you find any solution?
