### ISSUE TITLE
The "Profile" tab in the Expo client is blank

### ISSUE THREAD

**Issue by Larzack** [expo/expo#4734]
Hello,

Since 2 week, my expo client can’t display the loggin form. 

I have a blank page where my projects where dusplayed before. 

I reset my iPhone settings, uninstalled the app and i still have the blank page. 

How to debug or see logs ?

**Comment by cruzach** [comment]
What is displayed in the `Profile` tab? What version is your Expo client?

**Comment by ide** [comment]
There's likely a bug in the authentication code when the credentials are null. Need to fix this before the next release.

**Comment by Larzack** [comment]
Version 2.11.1.106175

Nothing displayed. Blank page.
