### ISSUE TITLE
Documentation about publishing should explain nuanced publishing behaviour for standalone apps and their support for multiple SDK versions

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#474]
If I have a SDK18 standalone app (built before SDK19 was released) and publish SDK19 JS, the SDK18 standalone will not use that, it will use the latest version published for SDK18. etc.

**Comment by dikaiosune** [comment]
Related: we probably want some UI that offers users really granular control over which JS versions go out to which binary versions.
