### ISSUE TITLE
[ios] Research macros for supported SDK versions

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#4740]
https://github.com/expo/expo/pull/4738#pullrequestreview-255218695

On Android we could use annotation processor, by @Szymon20000

**Comment by lukmccall** [comment]
To add these checks, we need to apply a lot of changes to our infrastructure. After a small discussion about it with @sjchmiela, we decided that it isn't worth maintaining. It's worth to mention that we currently don't have a lot of `// TODO: remove once` in our code.
