### ISSUE TITLE
[docs] Broken link to Amplitude example

### ISSUE THREAD

**Issue by bscaspar** [expo/expo#4743]
The [Amplitude docs](https://docs.expo.io/versions/latest/sdk/amplitude/#__next) links to the Expo app source code at this url https://github.com/expo/expo/blob/master/home/api/Analytics.js, which returns a 404. 

I did some poking around but couldn't find where in the source this might have moved to. Would love to see how Expo uses Amplitude!

**Comment by cruzach** [comment]
Thanks for pointing this out, looks like it was just broken bc the file went from `.js` to `.ts`
