### ISSUE TITLE
Remove all kinds of project discovery from web, Expo client

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4749]
As mentioned in https://twitter.com/encryptologist/status/1144328682267299840, as we continue to march forward with SDK releases and dropping old versions, more and more search results will be unable to run in the client. Search isn't the focus of Expo, it's building an app and sharing it with a small group of stakeholders.

The only thing we may want to leave in place are the basic examples that we provide and update, like native component list and react-navigation playground.

**Comment by brentvatne** [comment]
I removed https://expo.io/examples recently and set it up to redirect to our examples repo instead

**Comment by FiberJW** [comment]
This has been addressed on web and iOS, but search is still on Android (which I think is intended? for when adhoc builds allow us to do more stuff).

**Comment by brentvatne** [comment]
hmm this shouldn't be there on android, perhaps we just didn't publish dev home since it was removed
