### ISSUE TITLE
Detaching should configure iOS *UsageDescription keys

### ISSUE THREAD

**Issue by firdausious** [expo/expo#475]
When i try to submit to App Store, my detached ios app was rejected by ItunesConnect, because have one or more issues on Info.plist like this photo:

![screen shot 2017-08-09 at 2 55 39 pm](https://user-images.githubusercontent.com/730987/29117918-369f8ed8-7d2a-11e7-893e-868fc8af8268.png)

So must adding some key manually (below) to Info.plist

``
        <key>NSCameraUsageDescription</key>
        <string>This app requires camera access to run the function properly</string>
        <key>NSContactsUsageDescription</key>
        <string>This app requires contacts access to run the function properly</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires microphone access to run the function properly</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires photo library access to run the function properly</string>
``

And than finally they approved my ios app.
Looks like there’s something missing on ExpoKit / ExpoView Template itself, it should be adding this key automatically.

btw, on that case above, this is my env:

**Node**: 7.10.0
**Expo CLI** : 41.0.0
**Expo**: SDK 17
**React Native**: SDK 17 (Expo forked)

Even with this env below doesn’t work either :

**Node**: 8.1.4
**Expo CLI** : 43.0.0
**Expo**: SDK 19
**React Native**: SDK 19 (Expo forked)

Thanks

**Comment by terribleben** [comment]
Hi, yeah, historically we don't add these keys automatically when you detach, since not everybody wants or uses them. If Apple has started automatically checking for them then maybe we should plug them in for you.

**Comment by terribleben** [comment]
Still tracking, but closing in favor of https://github.com/expo/expo/issues/592 which is the same thing but for both platforms.
