### ISSUE TITLE
Move scoping entirely to scoped module in expo-font

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4750]
Related comments:
- https://github.com/expo/expo/pull/4652#discussion_r296630843
- https://github.com/expo/expo/pull/4652#discussion_r296633527

There should be no mention of `expo` in the JS or in the expo-font package, it should be contained instead in the scoped module.

**Comment by ide** [comment]
@brentvatne did your scoping change resolve this issue?

**Comment by brentvatne** [comment]
functionally speaking the #4652 has the desired effect. however, the word 'expo' is present in the unimodule code and it should instead only exist in expo client. this is a follow up issue to address a couple comments from @sjchmiela re: removing 'expo' from the unimodule code and putting the string into a scoped module instead.
