### ISSUE TITLE
Fresh install of standalone app on iOS and Android loads old JS bundle from .ipa/.apk build

### ISSUE THREAD

**Issue by bomanimc** [expo/expo#4754]
## 🐛 Bug Report
After freshly installing the app, I'd expect that the app opens to the most recent JS bundle that has been published to expo (assuming that you have fallbackCache value that's sufficient, such as the one in my app.json file). Instead, Expo loads a dated copy of the JS bundle (which was most recent at the time of building the .ipa/.apk files). Even users who have freshly installed the app after a new publish have to restart the app to get the OTA. 

Would love some help here please!

Full `app.json file:
```
{
  "expo": {
    "name": "The Summer Smash",
    "slug": "summer-smash-app",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "primaryColor": "#F5E82F", 
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "dial-up-code",
            "project": "summer-smash-app"
          }
        }
      ]
    },
    "updates": {
      "fallbackToCacheTimeout": 20000
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "com.dialup.thesummersmash",
      "buildNumber": "2.0.1",
      "infoPlist": {
        "LSApplicationQueriesSchemes": ["fb", "twitter", "instagram"]
      }
    },
    "android": {
      "package": "com.dialup.summersmashapp",
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/androidForegroundIcon.png",
        "backgroundColor": "#5ec4fc"
      },
      "versionCode": 4
    }
  }
}
```

### Environment
**Expo Diagnostics Output**
```
Expo CLI 2.20.7 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.9.1 => 3.9.1
    npmGlobalPackages:
      expo-cli: 2.20.7
```

**App Target**
Standalone app for Android and iOS phones.

### Steps to Reproduce
- Build the app for iOS or Android.
- Place the .ipa/.apk builds up for review in the appropriate stores.
- Once they have passed, make changes to your application
- Run `expo publish --release-channel prod` to publish a new JS bundle
- Install the app (for the first time) from Play Store or App store
- Notice that the app opens with an out-of-date JS bundle representing the state of the JS code when the .ipa/.apk file was built.

### Expected Behavior
After freshly installing the app, it opens to the most recent JS bundle that has been published to expo (assuming that you have fallbackCache value that's sufficient, such as the one in my app.json file).

### Actual Behavior
After freshly installing the app, it opens to the JS bundle that was most recent when the .ipa/.apk files were built, which is now outdated.

### Reproducible Demo
Guidance on the best way to reproduce this without making a totally new app in App Store Connect would be great, as I assume people looking to repro this would not be interested in doing that much to see this issue.

**Comment by bomanimc** [comment]
Thanks for triaging @cruzach. 

@esamelson Just following up here. I know that this may not be a significant priority on the Expo side, but it's quite significant for my small team since we're launching this app for a music festival that starts tomorrow. 

I'm sure that this is an error on my side, though, as it seems like opening fresh installs to the latest JS bundle would be a core requirement for OTA updates via Expo. If it's not/wasn't, then I think it's a serious enough issue for us to have to consider solutions outside of Expo.

**Comment by brentvatne** [comment]
@bomanimc - just a thought - was `"fallbackToCacheTimeout": 20000` configured at the time when you built the standalone apps? if not, then it wouldn't have that behavior because the standalone apps would use the configuration that was present at built, until a new manifest/bundle has been downloaded

**Comment by bomanimc** [comment]
Thanks @brentvatne. I think that must be the issue. I didn't realize that a rebuild was necessary based on this document: https://docs.expo.io/versions/latest/workflow/publishing/#some-native-configuration-cant-be-updated-by

**Comment by brentvatne** [comment]
@bomanimc - it can be updated but it is only applied at the time when the update that contains it is applied. if you think about it, there's no way for us to tell the app before it's downloaded the new update that any configuration has changed

**Comment by brentvatne** [comment]
fwiw, you should be able to push through an update to the play store very quickly. it might take a bit longer on the app store but it could still be possible to get it through if you submit it right away

**Comment by bomanimc** [comment]
@brentvatne: Gotcha. I put in new builds with the updated fallbackToCacheTimeout this morning. We'll cross our fingers that we can get through the stores on time. I've actually noticed that our Play Store updates longer than on the App Store, but we'll see how it goes.

**Comment by esamelson** [comment]
Hi there, we're triaging old issues and it sounds like this was resolved, so I'm going to go ahead and close the issue. If you're experiencing something similar on a currently supported SDK version, please go ahead and open a new issue. Thanks!
