### ISSUE TITLE
Expo contacts unparseable date

### ISSUE THREAD

**Issue by josaric** [expo/expo#4757]
### Environment
React native expo android
expo "sdkVersion": "32.0.0",

Import/sync contacts from Skype to your native contacts library, contact from Skype has different date format e.g. Jan 10, 1988.
Now in your react native app run this code

`import {Contacts} from "expo";`

`componentDidMount() {`
`Contacts.getContactsAsync()`
`.then(async (contacts) => { console.log(contacts) })`
`.catch( err => console.log(err.message))` 
`}`

In catch error message you will get: Unparseable date Jan 10, 1988 and contacts will not be fetched. Now for each contact you will need to remove birthday or change it to another date format.
I have tested also this issue on iOS and there I'm not getting this error, so issue exists only on Android.

**Comment by josaric** [comment]
To avoid this issue you can say what fields you need for displaying contacts, in my case I don't need birthday, but anyone who needs birthday information will have the Skype problem.

This is the way to select fields in query;

`Contacts.getContactsAsync({
                fields: [
                    Expo.Contacts.PHONE_NUMBERS,
                    Expo.Contacts.IMAGE
                ],
            })
`

**Comment by monjohn** [comment]
@EvanBacon Any update on this? We just ran into this. It seems like it would be better to just not return the birthday for that contact rather than reject the promise.
