### ISSUE TITLE
[bug] unimodules exclude `expo-ads-facebook` not working

### ISSUE THREAD

**Issue by u0x01** [expo/expo#4761]
I didn't figure out way to remove `expo-ads-admob`, `expo-ads-facebook` dependencies, its looks like expo internal dependencies. 

I was tried:
- exclude unimodules `expo-ads-admob`, `expo-ads-facebook`
- delete those folder in node_modules and resync gradle.
- add gradle build config `configurations.all` `exclude group:"com.facebook.ads"`

<img width="350" src="https://user-images.githubusercontent.com/9703404/60378326-91c3c480-9a53-11e9-99be-9979976adfc8.png">

`admob` was succeeded remove, but `facebook ads` still packaged in apk, the AVL still detected `Facebook Ads`, decompiled apk dex also can see `com.facebook.ads`:

<img width="350" src="https://user-images.githubusercontent.com/9703404/60378537-6bebef00-9a56-11e9-8c7f-329e0f88a30a.png">

It's affected that users who using with brand of oppo phone, AVL will blocked install process, AVL Pro scan result:

<img width="240" src="https://user-images.githubusercontent.com/9703404/60344569-699f7b80-99e9-11e9-9efd-956e48acf9d5.jpg">

is there any way remove ads widget from ejected app of android ?

download AVL Pro: https://play.google.com/store/apps/details?id=com.antiy.avlpro&hl=en

refer issue: https://github.com/expo/expo/issues/1789

**Comment by cruzach** [comment]
Hi @u0x01 - 

As it says in the issue you linked: 
> For now you would have to detach and manually remove those dependencies.

Since your project is ejected, you should be able to remove those dependencies. You have total control over your project once you eject.

**Comment by u0x01** [comment]
@cruzach I didn't figure out way to remove those dependencies, its looks like expo internal dependencies. 

I was tried:
- exclude unimodules `expo-ads-admob`, `expo-ads-facebook`
- delete those folder in node_modules and resync gradle.
- add gradle build config `configurations.all` `exclude group:"com.facebook.ads"`

<img width="350" src="https://user-images.githubusercontent.com/9703404/60378326-91c3c480-9a53-11e9-99be-9979976adfc8.png">

`admob` was succeeded remove, but `facebook ads` still packaged in apk, the AVL still detected `Facebook Ads`, decompiled apk dex also can see `com.facebook.ads`:

<img width="350" src="https://user-images.githubusercontent.com/9703404/60378537-6bebef00-9a56-11e9-8c7f-329e0f88a30a.png">

**Comment by cruzach** [comment]
Ah sorry @u0x01 - removing unimodules from Expokit projects is only supported on [iOS as of now](https://docs.expo.io/versions/latest/expokit/universal-modules-and-expokit/), that was my confusion. You may have to disclose to your users directly that you aren't **making use of** FB Ads in your app, even though the antivirus software is detecting code for it.

**Comment by tsapeta** [comment]
I'm closing this thread as it seems that you used ExpoKit in your project which is no longer supported and maintained. We recommend switching to bare workflow where you have more control on which Expo modules are being installed 🙂
