### ISSUE TITLE
accessToken and idToken are undefined when calling GoogleSignIn.signInAsync()

### ISSUE THREAD

**Issue by cmacdonnacha** [expo/expo#4762]
## 🐛 Bug Report
When calling the new `GoogleSignIn.signInAsync()` method, ` accessToken` and `idToken` are undefined. To test this I created a new android standalone build `expo build:android` and installed on my device. The sign in is successful but the ` accessToken` and `idToken` are undefined.  I need this to be able to sign into firebase. 

I followed these docs: https://docs.expo.io/versions/v33.0.0/sdk/google-sign-in/

Seems to work ok when I was using the old `Expo.Google` way to sign in: https://docs.expo.io/versions/v33.0.0/sdk/google/

### Environment

 Expo CLI 2.20.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD

Testing this on Android, not iOS.

### Steps to Reproduce

I have the following code:

```
  try {
    // Docs show that clientID is for IOS only. I'm testing on Android only.
    await GoogleSignIn.initAsync();
  } catch ({ message }) {
    alert('GoogleSignIn.initAsync(): ' + message);
  }
```
```
  try {
    await GoogleSignIn.askForPlayServicesAsync();
    const { type, user } = await GoogleSignIn.signInAsync();
    if (type === 'success') {
      // I get a success here but user.idToken is null

      //  Sign into Firebase with the credential from the Google user.
      const credential = firebase.auth.GoogleAuthProvider.credential(user.idToken, user.accessToken);
      firebase
        .auth()
        .signInAndRetrieveDataWithCredential(credential)
        .then(function(result) {
          alert('Firebase sign in success');
        })
        .catch(function(error) {
          console.error('Error with Firebase sign in ', error.message);
        });
    }
  } catch ({ message }) {
    alert('login: Error:' + message);
  }
```

### Expected Behavior

` accessToken` and `idToken` should be returned.

### Actual Behavior

 ` accessToken` and `idToken` are undefined. 

### Reproducible Demo

Can't create snack as GoogleSignIn cannot be used with the Expo client, only standalone.

**Comment by cruzach** [comment]
Hi @cmacdonnacha- I just tested with SDK 33 on Android, and was able to sign in and get correct values for `accessToken` and `idToken`.

I followed the docs (as you linked), but also I added a SHA certificate fingerprint to my Firebase project, as well as a support email. Could you try configuring both of those and seeing if that fixes it for you? Although, even before doing that I was just being returned an error, not `success`, so I'm not 100% sure that those steps will solve it

**Comment by davidli3100** [comment]
@cruzach I'll try that and report back with results. I'll also update the open forum post if it works. Thanks for the help!

**Comment by davidli3100** [comment]
@cruzach how would you go about getting a SHA certificate for a React Native app? Do I need to build it and get the keystore from there?

**Comment by davidli3100** [comment]
@cmacdonnacha did you manage to fix the issue? I'm trying to get the app SHA1 signature onto Firebase but the docs are quite unclear

**Comment by cmacdonnacha** [comment]
@davidli3100 No I haven't tried yet. How do you get the SHA1 signature?

**Comment by cmacdonnacha** [comment]
@cruzach Thanks for looking into this. So if we take firebase out of the equation isn't there still an issue where I am not getting an `idToken` and `accessToken` even after I receive a "success"?

**Comment by cruzach** [comment]
> how would you go about getting a SHA certificate for a React Native app

Not sure how you'd do this, I was assuming this was in an Expo managed app. That may explain why it was working for me and not working for you.

**Comment by cmacdonnacha** [comment]
@cruzach, just FYI it's a managed Expo app that I'm using.

**Comment by cruzach** [comment]
Yeah that's what I did (this API can't be used in the Expo client, so standalone is the only option)

Steps for successful googleSignIn behavior-
- `expo init newproject`
- set `android.package` in app.json to `com.example.newproject`
- create new [firebase project](https://console.firebase.google.com/u/0/)
- "Get started by adding Firebase to your app" -> click the android btn
- enter your exact `android.package`
- download config file, add it to your project
- in your app.json, set `expo.android.googleServicesFile` to the relative path of your google-services.json file
- build project with `expo build:android`, once it's completed run `expo fetch:android:hashes` and copy Google Certificate Fingerprint
- go to your project's settings in firebase, and "Add Fingerprint" using the copied Google Certificate Fingerprint from previous step

**Comment by cmacdonnacha** [comment]
Thanks @cruzach, I did the same but still doesn't seem to be working. Would you mind posting all of the sign in related code you have?

**Comment by cruzach** [comment]
Don't mind at all, although it's almost exactly what you posted above
```
// make sure your import looks like this
import * as GoogleSignIn from "expo-google-sign-in";

// I call this method in componentDidMount, otherwise it's the blank `expo init` starting code
signInAsync = async () => {
    try {
      await GoogleSignIn.initAsync();
    } catch ({ message }) {
      alert("GoogleSignIn.initAsync(): " + message);
    }

    try {
      await GoogleSignIn.askForPlayServicesAsync();
      const { type, user } = await GoogleSignIn.signInAsync();
      if (type === "success") {
        alert(JSON.stringify(user));
      } else {
        alert(type);
      }
    } catch (error) {
      alert("login: Error:\n" + error.message + "\n" + JSON.stringify(error));
    }
  };
```

**Comment by cmacdonnacha** [comment]
@cruzach , thanks for that. Can you explain what you mean by "the blank `expo init` starting code"?

Also, have you got these 2 code blocks in separate methods or are you calling them all in one? I feel like there may be a race condition where it may try to call the second block of code before `GoogleSignIn.initAsync();` resolves.

```
// Block 1
try {
  await GoogleSignIn.initAsync();
} catch ({ message }) {
  alert('GoogleSignIn.initAsync(): ' + message);
}

// Block 2
try {
  await GoogleSignIn.askForPlayServicesAsync();
  const { type, user } = await GoogleSignIn.signInAsync();
  if (type === 'success') {
    alert(JSON.stringify(user));
  } else {
    alert(type);
  }
} catch (error) {
  alert('login: Error:\n' + error.message + '\n' + JSON.stringify(error));
}
```

**Comment by cmacdonnacha** [comment]
Also, to access to the `idToken` and `accessToken` should we be using `user.auth.idToken` and `user.auth.accessToken`?

**Comment by huylv-teko** [comment]
> Yeah that's what I did (this API can't be used in the Expo client, so standalone is the only option)
> 
> Steps for successful googleSignIn behavior-
> 
> * `expo init newproject`
> * set `android.package` in app.json to `com.example.newproject`
> * create new [firebase project](https://console.firebase.google.com/u/0/)
> * "Get started by adding Firebase to your app" -> click the android btn
> * enter your exact `android.package`
> * download config file, add it to your project
> * in your app.json, set `expo.android.googleServicesFile` to the relative path of your google-services.json file
> * build project with `expo build:android`, once it's completed run `expo fetch:android:hashes` and copy Google Certificate Fingerprint
> * go to your project's settings in firebase, and "Add Fingerprint" using the copied Google Certificate Fingerprint from previous step

This help me alot.
For someone who got idToken when calling GoogleSignIn.signInAsync(), try `expo build:android` and try on new APK

**Comment by cmacdonnacha** [comment]
@huylv-teko are you accessing it through `user.auth.idToken`?

**Comment by huylv-teko** [comment]
@cmacdonnacha exactly man

**Comment by cmacdonnacha** [comment]
@huylv-teko , great, I'm getting the tokens now. However, when trying to log in to firebase I seem to be getting an error `Unable to verify the ID Token signature.`.

@cruzach, do you know if firebase authentication still works ok with the new `GoogleSignIn` package? Here's my code:

```
try {
  await GoogleSignIn.initAsync();
} catch ({ message }) {
  alert('GoogleSignIn.initAsync(): ' + message);
}

try {
  await GoogleSignIn.askForPlayServicesAsync();
  const { type, user } = await GoogleSignIn.signInAsync();
  if (type === 'success') {
    alert(JSON.stringify(user));  // I now have access to user.auth.idToken

const credential = firebase.auth.GoogleAuthProvider.credential(
  JSON.stringify(user.auth.idToken),
  JSON.stringify(user.auth.accessToken)
);

firebase
  .auth()
  .signInAndRetrieveDataWithCredential(credential)
  .then(function(result) {
    alert('Firebase sign in success'); 
  })
  .catch(function(error) {
    console.error('Error with Firebase sign in ', error.message);  //error here
  });
  } else {
    alert(type);
  }

} catch (error) {
  alert('login: Error:\n' + error.message + '\n' + JSON.stringify(error));
}
```

**Comment by cruzach** [comment]
I'll update the docs to reflect those steps, since it seems the current docs aren't comprehensive enough.

@cmacdonnacha I haven't tested it personally, but I'd imagine since all you're using is the token, it should still be working. I'd poke around a little more and see what throws that error message exactly, and if it looks to be a problem on our end, it's probably best to open a separate issue. 
(Also go ahead and close this one if the issue with null tokens is solved 👍 )

**Comment by davidli3100** [comment]
@cmacdonnacha Are you using the expo client or testing on the APK? If
you're testing on the Expo client the SHA1 signatures won't match so the
tokens would be invalidated by firebase auth

**Comment by cmacdonnacha** [comment]
Hi @davidli3100 , yes testing with the APK. The `GoogleSignIn` package doesn't work with expo client.

**Comment by cmacdonnacha** [comment]
@cruzach great thanks for your patience on this.

**Comment by cmacdonnacha** [comment]
I got firebase to work now too. I was stupidly using the stringified version of `idToken` and `accessToken`. Correct code:

```
try {
  await GoogleSignIn.initAsync();
} catch ({ message }) {
  alert('GoogleSignIn.initAsync(): ' + message);
}

try {
  await GoogleSignIn.askForPlayServicesAsync();
  const { type, user } = await GoogleSignIn.signInAsync();
  if (type === 'success') {
    alert(JSON.stringify(user));  // I now have access to user.auth.idToken

const credential = firebase.auth.GoogleAuthProvider.credential(
 user.auth.idToken,
 user.auth.accessToken
);

firebase
  .auth()
  .signInAndRetrieveDataWithCredential(credential)
  .then(function(result) {
    alert('Firebase sign in success'); 
  })
  .catch(function(error) {
    console.error('Error with Firebase sign in ', error.message);
  });
  } else {
    alert(type);
  }

} catch (error) {
  alert('login: Error:\n' + error.message + '\n' + JSON.stringify(error));
}
```

**Comment by StevenHarlow** [comment]
This is happening to me in the android studio emulator, but it works for ios.

My app.json looks like:
"expo": {
  "android": {
      "package": "com.appname",
      "googleServicesFile": "./android/app/google-services.json"
    }
}
my firebase project setting has the Package name as: com.appname, the google-services.json file is in the correct location...

Not sure where the issue is.
