### ISSUE TITLE
Breaking API changes and library compatibility

### ISSUE THREAD

**Issue by bengourley** [expo/expo#4764]
## 🐛 Bug Report

This is not currently a bug, but potentially a problem in the near future. This relates to Expo and React Native's upcoming breaking API changes, and what that means for third-party modules that are designed to be used with Expo, such as the one I maintain – [`@bugsnag/expo`](https://www.npmjs.com/package/@bugsnag/expo).

#### `NetInfo`

Currently in SDK 33, `react-native@v0.59.8` includes the package `NetInfo` which we import in our notifier:

[`const { NetInfo } = require('react-native')`](https://github.com/bugsnag/bugsnag-js/blob/5e241be93dc03a7bd536aa9ecaa4f588738358a3/packages/delivery-expo/network-status.js#L1)

In [`react-native@v0.60.0` this has been removed](https://github.com/facebook/react-native/commit/5a30c2a2052ba76e88dbf71b5b5c92966591bf26) since this functionality is now maintained in the external library [`@react-native-community/netinfo`](https://github.com/react-native-community/react-native-netinfo).

In version 33 of the SDK docs this package [has been removed](https://docs.expo.io/versions/v33.0.0/react-native/netinfo/). Is the API going away or is Expo going to continue to provide it based on the third party module?

This means in the future our notifier can only work for Expo SDKs with `react-native@<0.60` _or_ `react-native@>=0.60` but not __both__.

If we could dynamically import `NetInfo` based on the API version or something we could solve this, but as it stands we can't support all versions of Expo with a single version of our library.

__Is the only solution for us to drop support for versions of the Expo SDK that include `react-native@<0.60` when we release support for Expo SDK with `react-native@>0.60`__ or to maintain forks of our notifier for different Expo SDK versions?

#### `Constants` and `FileSystem`

These two Expo packages have moved. How do we deal with this migration?

If it were possible using the bundler to do a conditional import we can support all versions with a single version of our codebase, but I don't think anything like this is possible:

```js
// I know this doesn't work, but could there be something that could achieve it?
try {
  import { Constants } from 'expo'
} catch (e) {
  import Constants from 'expo-constants'
}
```

Please let me know how best we can support our Expo users as your (and React Native's) APIs evolve!

**Comment by SleeplessByte** [comment]
```javascript
try {
  import { Constants } from 'expo'
} catch (e) {
  import Constants from 'expo-constants'
}
```

This might not work, but dynamic imports should -- as do commonjs imports. Don't know if that is the solution _here_, but we've used this in the past:

```javascript
// web dynamic import
import('expo-constants')
  .catch(() => import('expo').then(({ Constants }) => Constants))
  .then((imported) => ...)

// commonjs
let Constants;

try {
  Constants = require('expo-constants')
} catch () {
  Constants = require('expo').Constants
}
```
```

**Comment by cruzach** [comment]
The netinfo package is [still in the docs for SDK 33](https://docs.expo.io/versions/latest/react-native/netinfo/#__next), although we now use `@react-native-community/netinfo`. 

> So this seems to be in place?

Yep! The old way of importing does still work in SDK 33.

**Comment by bengourley** [comment]
> The netinfo package is [still in the docs for SDK 33](https://docs.expo.io/versions/latest/react-native/netinfo/#__next), although we now use `@react-native-community/netinfo`.

This link doesn't work for me, it says "An unexpected error has occurred." and if I navigate around the latest docs I can't find `netinfo` mentioned anywhere 🤔 I would assume this is because the RN docs are imported verbatim, and the docs for that package are no longer in the RN docs since the package was extracted but I coud be wrong.

I know that it currently works with SDK 33 (even though the docs page disappeared), but I'm trying to figure out how we support SDK 34, 35, 36 etc. while still supporting 33 in the same version.

Thanks for the suggestion around dynamic imports @SleeplessByte – I will see if something like that is workable.

**Comment by zanechua** [comment]
I was going to create my own issue but I think this issue is generic enough.

I am facing an issue similar to @bengourley but instead of the expo third party modules, in my case it's my own third party modules that I am introducing to newer versions of the application. Currently the way Expo Updates work doesn't seem to care about that. According to the expo workflow, it only cares about sdkVersion and platform when checking for new js bundles. This doesn't work very well with Expokit since we can introduce our own native modules and it will break all existing versions of the app that is currently being used by users. Shouldn't there be an additional constant check if necessary e.g. app version to check before actually pulling an update.

**Comment by cruzach** [comment]
@zanechua with the new `expo-updates` module available for the bare workflow, you should use the `runtimeVersion` constant for your use case (native code changes -> increment `runtimeVersion`). You can find docs on that here - https://docs.expo.io/bare/updating-your-app/

**Comment by zanechua** [comment]
Thanks for the response. Hopefully that'll be useful for people utilizing Expo and end up on this thought train.

Unfortunately due to the requirements of the app I was building, I had to go with a full react-native workflow.

**Comment by cruzach** [comment]
> I had to go with a full react-native workflow

That's exactly what [the bare workflow offers](https://docs.expo.io/introduction/managed-vs-bare/#bare-workflow), just in case you're interested in checking that out again

**Comment by cruzach** [comment]
dynamic imports are now well supported, so I'm going to allow myself to close this issue for now
