### ISSUE TITLE
App sometimes reverts/downgrades to old bundle

### ISSUE THREAD

**Issue by jbirori** [expo/expo#4772]
## 🐛 Bug Report

After getting the latest OTA I'd expect that the app opens to the most recent JS bundle that has been published to expo. Instead, Expo will run the latest OTA for a few min/hours and then will sometimes load a previous version of the JS bundle. 

Would love some help here please!

### Environment
```
  Expo CLI 2.18.7 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.5.0-next.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 9.0/9A235 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.9.1 => 3.9.1
    npmGlobalPackages:
      expo-cli: 2.18.7
```

### App Target
Standalone app for Android and iOS phones.

### Steps to Reproduce

- Build the app for iOS or Android
- Push an OTA
- Restart the app
- Use the app with the latest OTA
- Leave app alone for minutes/hours
- Open the app again and it might open an older bundle

### Expected Behavior

After getting the latest OTA I'd expect that the app opens to the most recent bundle and every sequential open will render the most recent update.

### Actual Behavior

After letting the app sit for a short while following an OTA, it sometimes opens up an older bundle

**Comment by bomanimc** [comment]
Thanks for posting @jbirori! @nicolasrouanne issue on https://github.com/expo/expo/issues/2468 speaks to this issue as well.

**Comment by nicolasrouanne** [comment]
@jborori @bomanimc That’s exactly the behavior I’ve been experiencing 👍

**Comment by esamelson** [comment]
Hey all, sorry for the slow followup here. This was fixed in more recent SDK versions so this error should go away if you upgrade to a supported SDK version!
