### ISSUE TITLE
Permissions.askAsync(Permissions.NOTIFICATIONS) not returning 

### ISSUE THREAD

**Issue by hochmanjoel** [expo/expo#4773]
My code is simple yet status returns as "undetermined" rather than granted. I cannot find any solutions in the forum or elsewhere online.

```async askPermissions() {
    this.closeModal();
    const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS); // Needs to be fixed
    console.log(status);
    if (status === 'granted') {
      console.log('damn successful fool');
      this.setState({ actuallyIsVisible22: !this.state.actuallyIsVisible22 });
    } else {
      console.log('successful failure');
    }
  }
```

**Comment by AdamJNavarro** [comment]
Hey @hochmanjoel,

Closing this as you got it figured out on the forums. For those interested, this was a result of trying to test on a simulator which is not possible. Push notifications are not compatible on simulators.

Cheers,
Adam
