### ISSUE TITLE
Local Authentication dont work on build production

### ISSUE THREAD

**Issue by gothaussen** [expo/expo#4775]
Localauthentication does not work for me at the time of compiling the application, but it works for me when testing with expo-cli. I do not throw away error when compiling.!

Do you know what can be treated?

**Comment by AdamJNavarro** [comment]
Hey @gothaussen,

Can you provide some more information such as what platform this is occurring on and what SDK version your project is using?

**Comment by AdamJNavarro** [comment]
Actually, better yet let's continue the discussion on your [forum post](https://forums.expo.io/t/local-authentication-doesnt-work-on-build/24571).
