### ISSUE TITLE
Expo-blur not working with react-native-web

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#4781]
### Environment

Running on web with react-native-web via ```react-scripts start```

```
  Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.7.20 => 16.8.20
      @types/react-native: ^0.52.25 => 0.52.25
      expo: ^33.0.0 => 33.0.5
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^2.0.4 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.21.1
```

### Steps to Reproduce
```
import { BlurView } from 'expo-blur';
function() {
   return <BlurView/>
}
```

### Expected Behavior

View displays without errors.

### Actual Behavior

```
./node_modules/expo-blur/build/BlurView.web.js
SyntaxError: /Users/Varun/Documents/workspace/clyme/node_modules/expo-blur/build/BlurView.web.js: Unexpected token (9:15)

   7 |         let { tint, intensity, style = {}, ...props } = this.props;
   8 |         const blurStyle = getBlurStyle({ tint, intensity });
>  9 |         return <View {...props} style={[style, blurStyle]}/>;
     |                ^
  10 |     }
  11 | }
  12 | BlurView.propTypes = {
```

### Reproducible Demo

Can't create on snack since it seems to be related to react-native-web, let me know if more info or a different kind of repro is needed.

**Comment by EvanBacon** [comment]
Given that this is using `react-scripts start` and not `expo-cli` could you provide a repro. It seems like this could be do to the configuration. You may also just want to try running with `expo start` since `react-scripts` uses a slightly different webpack config.

**Comment by vjsingh** [comment]
@EvanBacon Thanks for the reply. I'm having two other babel / webpack configuration issues that cropped up when upgrading to SDK 33. Commented in those places - if I can resolve the issues soon I'll try to switch over to ```expo-cli``` and let you know if it fixes the issue. If not I can try to build a repro.

https://forums.expo.io/t/help-resolving-absolute-imports-in-expo-33/23780/4
https://github.com/expo/expo/issues/4648

**Comment by ide** [comment]
This doesn't seem to be an issue with expo-blur specifically unless you have tested other view modules -- the error shows that your code is not being transformed correctly. I'd recommend creating a new project with `expo init`, verifying that `expo-blur` works there, and then gradually narrowing down the differences between the new project and the old project until you can hone in on the exact cause.

**Comment by vjsingh** [comment]
OK, I'll close this for now. Hopefully it's because I'm still using ```react-scripts```.

Having some issues getting expo web to work for now, but I'll take a look again at some point, maybe when it's matured a little.
