### ISSUE TITLE
[docs] addOrientationChangeListener is not mentioned in methods list.

### ISSUE THREAD

**Issue by kerrytazi** [expo/expo#4783]
https://docs.expo.io/versions/latest/sdk/screen-orientation/#methods

There are no `addOrientationChangeListener` in methods list but it is described below.

**Comment by cruzach** [comment]
Could you explain a little further?

The link you shared does have an entry under Methods for `addOrientationChangeListener` [here](https://docs.expo.io/versions/latest/sdk/screen-orientation/#screenorientationaddorientationchangelistenerlistener), and I think you forgot to add the content you're referencing when you say "described below" 😄

**Comment by kerrytazi** [comment]
There are two lists with methods. On the top - just names and below with descriptions. So they don't match.

**Comment by cruzach** [comment]
Ohhhh I see exactly what you mean now, thanks for explaining that. Guess I was having a bit of a slow moment there
