### ISSUE TITLE
Google.logInAsync restarts the app while in expo client

### ISSUE THREAD

**Issue by stochris** [expo/expo#479]
On Android 4.4, on a Nexus 5 device, the application restarts when trying to log in with google

React native version:  0.46
Expo sdk version: 19.0.1
Expo client version: 1.18.4

[The adb log](https://github.com/expo/expo/files/1211508/exp_log.txt)

**Comment by janicduplessis** [comment]
Are you able to repro on [snack](https://snack.expo.io/)
