### ISSUE TITLE
Login Facebook behavior native is not working

### ISSUE THREAD

**Issue by duylinhdang1998** [expo/expo#4792]
I set behavior 'native' for Standalone Apps but it's not working and get error. I set up my keyhash facebook with command line expo fetch:android:hashes. But it not work. I using behavior:'web' and work correctly but i want to using native. Please help me. Thanh you

**Comment by AdamJNavarro** [comment]
Hey @duylinhdang1998,

We'll use your forum post to continue discussions. We prefer to keep github issues reserved for issues that have reproducible cases and root causes identified.

Cheers,
Adam

**Comment by duylinhdang1998** [comment]
I got the error? what happen
![image](https://user-images.githubusercontent.com/40199004/60532257-1dc13f00-9d27-11e9-92d6-691c69f606f0.png)

**Comment by duylinhdang1998** [comment]
I got error 
![image](https://user-images.githubusercontent.com/40199004/60532361-5234fb00-9d27-11e9-858a-50c460421313.png)

**Comment by duylinhdang1998** [comment]
https://prnt.sc/o9nd1y
I got error

**Comment by Amerr** [comment]
Is this the same issue 
https://github.com/expo/expo/issues/4701#issuecomment-508193652
