### ISSUE TITLE
undefined is not an object (evaluating '_expoPrint.Print.printToFileAsync')

### ISSUE THREAD

**Issue by robinpaulson** [expo/expo#4793]
## 🐛 Bug Report
I've seen this error with other expo modules, but none so far for expo-print. It appears similar to others, based upon the "undefined is not an object" error message. I only used this module for the first time this week, so don't know when the error was introduced, but suspect v33 of the SDK

### Environment
Expo CLI 2.21.2 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      npm: 6.9.2 - ~/.nvm/versions/node/v11.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2

app target: Android

### Steps to Reproduce
run expo start
open the code in the expo app
click the button in the app which is titled "Create PDF"

### Expected Behavior
I expected it to create a very simple PDF file in the app's cache directory

### Actual Behavior
An error message "undefined is not an object"

### Reproducible Demo
import React from 'react';
import { StyleSheet, Text, View, TouchableHighlight } from 'react-native';
import { Print } from 'expo-print';

export default class App extends React.Component {

createPDF(){
   const filePath = Print.printToFileAsync({ html : "<h1>PDF test</h1>", base64 : false });
   console.log(filePath);
  };

  render() {
    return (
      <View>
        <TouchableHighlight onPress={this.createPDF} style={styles.Main}>
          <Text>Create PDF</Text>
        </TouchableHighlight>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  Main : { marginTop : 120, marginLeft : 60 }
});

**Comment by AdamJNavarro** [comment]
Hey @robinpaulson, can you try running `expo install expo-print` and see if that remedies the situation?

Cheers,
Adam

**Comment by robinpaulson** [comment]
Yeah, I've already done that.

**Comment by cruzach** [comment]
If you change your import syntax to `import * as Print from 'expo-print'`, that solves the problem (just tested on my end). I'll update the docs, thanks so much for catching this error and pointing it out to us!
