### ISSUE TITLE
Plans to support native share extension without detaching?

### ISSUE THREAD

**Issue by broskoski** [expo/expo#48]
See approach for implementing share extensions with RN here: https://github.com/alinz/react-native-share-extension

Curious if this is already something that's on your minds (before I attempt to implement). 

Thanks for all your work thus far, really enjoying the Exponent dev experience!

**Comment by acornejo** [comment]
Not sure there is a need for an extension, the new RN supports sharing out of the box:

https://facebook.github.io/react-native/docs/share.html

Thus my guess is that this will come to exponent whenever the SDK upgrades to the latest RN branch.

**Comment by broskoski** [comment]
Thinking of sharing from the other direction (I.e you're on an app outside the context of an exponent app and want to share content TO the exponent app). Basically registering a react native / exponent app on the share screen.

**Comment by filipmares** [comment]
+1

**Comment by ide** [comment]
It's not at the top of our roadmap right now -- could you add an entry here? (I didn't find an existing entry when searching) https://expo.canny.io/feature-requests

**Comment by filipmares** [comment]
Just submitted. Thanks! https://expo.canny.io/feature-requests/p/ios-app-extension

**Comment by peterlandry** [comment]
I updated the above, but also added a roadmap request more specifically for android, as well. I didn't want it to get lost in the shuffle: https://expo.canny.io/feature-requests/p/implement-android-share-receiver

**Comment by sw-yx** [comment]
keen on this too!

**Comment by DavitVosk** [comment]
Hi I am working with share extension too. Could you please advise whether the feature is already added to Expo? And if yes, please provide me some guides for using it. Thanks in advance

**Comment by isaachinman** [comment]
Hi @ide any update on this feature? I am building an app that needs to be inside the device's share menu so that data (photos, specifically) can be passed into the app from external apps, as @broskoski explained.

I would be happy to assist in a PR if you think it'd get merged.

**Comment by ide** [comment]
For updates regarding Expo APIs, see https://docs.expo.io. There is no native share extension API.

We could possibly take a PR that satisfies these nominal criteria:
- Works on both Android and iOS
- is small in scope and maintainable (this is subjective)
- Follows the Expo SDK conventions implied by existing APIs
- Objective-C and Java implementations to the standard of expo/expo code and facebook/react-native code
- A few example code snippets we can include in the integration test suite
- If the JS implementation has logic, Jest tests along with it

**Comment by isaachinman** [comment]
@ide Okay, understood. It's a shame that something relatively trivial is going to end up forcing me to detach. To your knowledge is there one or more existing canny feature requests that I should use, or create a new one?

**Comment by ide** [comment]
I don’t know if there is a request out for this. Please feel free to create a new one if you don’t find one after searching.

**Comment by xcarpentier** [comment]
Any PR of the share extension feature?

**Comment by brentvatne** [comment]
pr would be welcome!

**Comment by isaachinman** [comment]
Hey all - just want to point out that we aren't really actively maintaining `react-native-share-extension` anymore, and most (to my knowledge) production use cases are running off forks.

Share extensions are hard, and very platform-specific.

May or may not be better to start over if Expo wants to devote resources to it!

**Comment by xcarpentier** [comment]
@isaachinman do you know if there is a good starting point? (ie. specific fork or resources)
BTW differences between platforms can be managed and interfaced in front TS code, no?

I think I will start at a new `expo-share-extension` package on my own and proposed.

**Comment by isaachinman** [comment]
@xcarpentier So in general, it is highly dependent on what it is you actually want to share. The `react-native-share-extension` repository originally began as a project to share _text links_ from web browsers into other apps.

It's since evolved, but mostly via PRs and forks, to support other content like images, videos, multiple images, and so on.

I would suggest looking through this https://github.com/alinz/react-native-share-extension/pull/84 PR, and taking a look at the iOS approach on `master`. In general, there are a lot more hoops to jump through to achieve this on iOS (unsurprisingly), and it's very hard to achieve feature parity, depending on what sort of content types you want to support.

Let me know if you have any other questions. @AndrewHenderson probably has more knowledge than I do - he might be able to help as well. Would be great to have movement in this area, as there's currently no (even remotely) easy way to do this with RN right now.

**Comment by patrickomeara** [comment]
Thanks for the great explanation @isaachinman 

A share extension would be a welcome addition to expo. If anyone is tackling this problem, I'm happy to help.

**Comment by CanRau** [comment]
Any news on this?
