### ISSUE TITLE
Investigate alternatives to react-native upstream image loading

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4801]
The Image component upstream suffers from a variety of problems, summarized in the [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) as:

```
- Flickering.
- Cache misses.
- Low performance loading from cache.
- Low performance in general.
```

The solution used by react-native-fast-image is to leverage SDWebImage on iOS (instead of custom image loading logic built for react-native specifically) and Glide instead of Fresco on Android.

**Comment by ide** [comment]
Along with this, it'd be nice to start exploring `expo-network` that provides a shared network interface for unimodules (`expo-network-interface`) and a much more powerful version of `fetch` on top of which we can build `fetch` but also let people control OS-specific networking behavior (e.g. on iOS you can instruct it to continue a download even if your app is terminated due to memory pressure).

**Comment by immortalx** [comment]
I'm sorry if this question was already answered. Why not just use react-native-fast-image? Any big compatibility issue? 
The maintainer has offered to help with a possible integration.

**Comment by ide** [comment]
@immortalx We can start with r-n-f-i as an inspiration but there are a couple of key things:

- One of the things we need to work on for Expo is API stability, so the Expo team needs to approve all API changes
- We want to be able to use other cache & network implementations
- We need to be able to add support for other platforms

(This is the case for most modules, not just image.)

**Comment by immortalx** [comment]
@ide Thank you for taking the time to explain. As a suggestion, contacting @DylanVann to see if all this is possible seems like a good idea as he was willing to help. 

It can save a lot of time.

**Comment by raphaelrk** [comment]
An `expo-network-interface` could be a great platform for debugging as well. Large responses from JSON APIs and loading dozens of images we didn't realize were several megabytes each were killing the performance of (and crashing) our Android app. I wonder how many people who want RNFI have really big images and don't realize. Might just be a me issue :-)

Given the name, `expo-network-interface` could also be a potential place to have webRTC support.

**Comment by nandorojo** [comment]
> Along with this, it'd be nice to start exploring `expo-network` that provides a shared network interface for unimodules (`expo-network-interface`) and a much more powerful version of `fetch` on top of which we can build `fetch` but also let people control OS-specific networking behavior (e.g. on iOS you can instruct it to continue a download even if your app is terminated due to memory pressure).

This sounds like a great addition. Would something like this land in sdk36?

**Comment by Egizas** [comment]
I also thing that fastImage would be really good addition to expo. I hope it well get added.

**Comment by divs1210** [comment]
Sad that this hasn't been done yet. This issue is only on Android and fixable by using the native `SurfaceView` class in Android instead of the normal `View`. If a RN component called `AnimatedView` could fall back on `View` on iOS but `SurfaceView` on Android, that would be great.

**Comment by ide** [comment]
Assigning this to Stanley and Hein for expo-image.

**Comment by divs1210** [comment]
Just to help anyone who ends up here looking for a solution, I'm making a game and use series of images for animated characters. I solved flickering between frames by rendering all frames but setting their opacity to 0, setting it to 1 only for the current frame. It hits the performance, but the game becomes playable at least.

**Comment by IjzerenHein** [comment]
> Just to help anyone who ends up here looking for a solution, I'm making a game and use series of images for animated characters. I solved flickering between frames by rendering all frames but setting their opacity to 0, setting it to 1 only for the current frame. It hits the performance, but the game becomes playable at least.

Show us 😃

**Comment by RWOverdijk** [comment]
@IjzerenHein Glad to see you're assigned to this 😄

Anything we can do to help with this? Caching is becoming a big deal for me.

**Comment by raphaelrk** [comment]
Possible memory leak test cases here, too: [Image and ImageBackground memory leaks in iOS](https://github.com/facebook/react-native/issues/22448)

**Comment by brentvatne** [comment]
you can use react-native-fast-image with EAS Build & expo-dev-client. we plan on continuing to build out expo-image at some point but it's not currently a priority
