### ISSUE TITLE
"File isn't readable" when using `ImageManipulator.manipulateAsync` with Expo SDK 33 on iOS

### ISSUE THREAD

**Issue by hussain-t** [expo/expo#4806]
## 🐛 Bug Report
"File isn't readable" when using `ImageManipulator.manipulateAsync` with Expo SDK 33 on iOS.

### Environment

`Expo client iOS:  2.11.1.106175`

```
Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.4 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.3.2 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2
```
Issue appears in iPhone and iOS simulator only. It works with Android.

### Steps to Reproduce
When using `ImageManipulator.manipulateAsync` getting `File isn't readable` permission error. Snapshot is captured and stored in the file system. However, the issue is not able to read the file.

### Expected Behavior

Should read image successfully.

### Actual Behavior
`[Unhandled promise rejection: Error: File '/private/var/mobile/Containers/Data/Application/BF2874F8-9EAF-484B-A3C7-04CF9A1401DF/tmp/ReactABI33_0_0Native/5378EF2C-5DEC-4BE0-A609-69F2CF195CFC.png' isn't readable.]`

### Reproducible Demo

Please check the Snack URL below:

https://snack.expo.io/@hussain-t/imagemanipulator

Check the console logs on Snack.

**Comment by dean9703111** [comment]
I have same issue when I use FileSystem.copyAsync

**Comment by Bad-Listener** [comment]
Yeap, me too, since the update in expo SDK 33

**Comment by bbarthec** [comment]
@hussain-t, please take a look at this [snack](https://snack.expo.io/@bbarthec/github---imagemanipulator---ios---react-native-view-shot).
I've checked that result that is being returned from `react-native-view-shot#captureRef` on iOS is not a valid uri (there's no scheme at the beginning of the returned string). I manually added missing scheme. Android returns valid `file://` scheme.

**Comment by bbarthec** [comment]
@deadcoder0904, may I ask you to provide separate issue for your problem? It would very beneficial to have some mvp snack that demonstrated what's wrong with `expo-filesystem#copyAsync# method.

**Comment by deadcoder0904** [comment]
@bbarthec I think you pinged the wrong guy 😂

**Comment by bbarthec** [comment]
@deadcoder0904, yeah, you're right 😂 sorry for this 🙇

**Comment by hussain-t** [comment]
Hey @bbarthec, yes, adding `file://` scheme manually works 🔥 Thanks, man! 
However, will that be fixed with `react-native-view-shot` instead of adding manually?

**Comment by bbarthec** [comment]
@hussain-t, Expo is not not maintaining `react-native-view-shot` 😞 But we'll report that problem!

**Comment by Abdelrahman-Nabil** [comment]
I have the same issue with the paths coming from `CameraRoll.getPhotos()` after upgrading to SDK 33, it returns `ph://` prefix, when passing it to `ImageManipulator.manipulateAsync()` i get `File isn't readable` error.

**Comment by JasonMize** [comment]
The path returned from `CameraRoll.saveToCameraRoll` returns `ph://` prefix.  When passed to `ImageManipulator.manipulateAsync()` I get `File isn't readable` error.  Manually changing prefix to `file://` doesn't work.

**Comment by iboy15** [comment]
anyone fix this issue ?

**Comment by bbarthec** [comment]
@iboy15, #5195 has introduces support for schema `ph://`

**Comment by ghmendonca** [comment]
@bbarthec  Is this fix already available? I have expo 34.0.04 and expo-file-system 6.0.2 installed, but I still get this error when trying to get ph:// files

**Comment by iboy15** [comment]
same here,
using expo 34 and expo file system 6.0.2
 still get same error on iOS simulator

@bbarthec

**Comment by kesha-antonov** [comment]
Same error with ```FileSystem.getInfoAsync(fileUri)```

**Comment by tattivitorino** [comment]
I am using (ejected app) react-native-image-crop-picker (I want to save a copy of the image in the app directory which I created with FileSystem.makeDirectoryAsync(directoryStr) but i am  facing the same issue when trying to save:
SDK 33
"expo-file-system": "~5.0.1",
FileSystem.copyAsync({})
File 'file:///var/mobile/Media/DCIM/101APPLE/IMG_1162.PNG' isn't readable.

**Comment by iboy15** [comment]
@bbarthec @sjchmiela  i think u need to remerge #5195 
i've re check expo filesystem code (6.0.2) in node modules and compare it with #5195 and there's no updated
for example this

 ```
NSArray *validSchemas = @[
                            @"assets-library",
                            @"http",
                            @"https",
                            ];
  if ([validSchemas containsObject:uri.scheme]) {
    return UMFileSystemPermissionRead;
  }

```
there is no @"ph" included / still old file

**Comment by ghmendonca** [comment]
Any update on this?

**Comment by ghmendonca** [comment]
Just tested and it works, thanks @bbarthec , but I can see another issue.. Now the FIleSystem.getInfoAsync returns the uri field null. I managed to get working by manually setting the uri after getInfoAsync

**Comment by bbarthec** [comment]
@ghmendonca, please open new issue addressing this bug 🙇 That would simplify work on this problem 😉
