### ISSUE TITLE
33.0.0 is not a valid SDK version

### ISSUE THREAD

**Issue by thegtagamer** [expo/expo#4812]
33.0.0 is not a valid SDK version.

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.21.2

**Comment by AdamJNavarro** [comment]
Hey @thegtagamer,

What version of the Expo Client are you using? There's a chance you're using an outdated Client and you'll need to update to get a Client that has SDK33 compatibility.

Cheers,
Adam

**Comment by ChiuMungZitAlexander** [comment]
@AdamJNavarro 

Same issue here.
```
"expo": "^33.0.0",
"expo-cli": "2.20.2",
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
```

**Comment by AdamJNavarro** [comment]
Hey @ChiuMungZitAlexander, Did you see my note about client version? Can you let me know what version of the Expo client you are running?

**Comment by ChiuMungZitAlexander** [comment]
> Hey @ChiuMungZitAlexander, Did you see my note about client version? Can you let me know what version of the Expo client you are running?

Dear @AdamJNavarro , my Expo Client is **2.10.4, Android**

**Comment by thegtagamer** [comment]
@ChiuMungZitAlexander Hey Buddy, try updating your expo client from the play store. It worked for me.

**Comment by ChiuMungZitAlexander** [comment]
@thegtagamer @AdamJNavarro 
Thank you, sir. It is good now.
