### ISSUE TITLE
getContactByIdAsync throws an error on android

### ISSUE THREAD

**Issue by mohebifar** [expo/expo#482]
I have a code that uses `getContactByIdAsync` to get the data of a contact. It works fine on iOS but on Android, I get this error:

> The callback getContactsAsync() exists in module ExponentContacts, but only one callback may be registered to a function in a native module

My guess is that, in [ContactsModule.java#163](https://github.com/expo/expo/blob/ios/sdk19/android/app/src/main/java/abi19_0_0/host/exp/exponent/modules/api/ContactsModule.java#L163), `promise.resolve` gets invoked more than once since it does not quit the `while` loop after fetching the contact.

**Comment by terribleben** [comment]
Tracking this pending the open pull request

**Comment by tjw0051** [comment]
Possible work-around I'm using for now is to get contacts by Index using:

`getContactsAsync({ pageSize: 1, pageOffset: index });`

Obviously not reliable if you're getting contacts between sessions but if you're reading all contacts then using getContactByIdAsync to get e.g. images it seems to work.

**Comment by jesseruder** [comment]
Should be fixed with https://github.com/expo/expo/commit/3ba3f945c28886b26f4c28ba493ea9a835f18ba3
