### ISSUE TITLE
Integration tests.

### ISSUE THREAD

**Issue by tdimnet** [expo/expo#4824]
Hello there,

we are using expo at work and so far we do envoy our experience with this amazing tool.
We set up tests (snapshot and unit tests) with jest. However, I would like to integrate some integration tests to our app.

After browsing the internet, I found out a few solutions and I am wondering which one is the best.

- Here is the first one: https://airbnb.io/enzyme/docs/guides/react-native.html. We would create an emulated DOM with JSDom.
- The other one is the one: https://blog.expo.io/testing-expo-apps-with-detox-and-react-native-testing-library-7fbdbb82ac87.

Which solution should I use?

Thank you and have a great day.

**Comment by AdamJNavarro** [comment]
Hey @tdimnet,

In an effort to reduce noise on our Github repo, we try our best to reserve issues to reproducible bugs. Would you mind creating a [forum post](https://forums.expo.io/) for this discussion so other's can participate easily as well?

Cheers,
Adam

**Comment by tdimnet** [comment]
@AdamJNavarro : ok sorry for that.

If I find a great solution for integration testing may I create a PR related to this subject in order to update the documentation?

**Comment by AdamJNavarro** [comment]
No need to apologize! We are always welcome to PRs!
