### ISSUE TITLE
Cannot get camera permissions

### ISSUE THREAD

**Issue by Menna-Ibrahim** [expo/expo#4826]
I'm trying to enable camera permissions in react-native app and I used the functions in Expo documentation but it gave me this warning and the camera keeps on loading 

[Unhandled promise rejection: Error: Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.]

any help?

**Comment by AdamJNavarro** [comment]
Hey @Menna-Ibrahim,

Can you provide some more information to help us debug the issue. It sounds like you're running either a bare workflow project or a vanilla react-native project. If you're running a vanilla project, can you ensure you've done the [necessary steps](https://github.com/unimodules/react-native-unimodules) to enable usage of Unimodules?

Also, is this occurring on Android, iOS or both platforms?

Cheers,
Adam

**Comment by Menna-Ibrahim** [comment]
I did these steps yes but still have the same issue, I'm running it on android emulator and even tried to run it on my own device using Expo.
Here's some additional information:
   "expo": "^33.0.0",
    "expo-permissions": "~5.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git"

**Comment by Menna-Ibrahim** [comment]
Hey, I was using react-native-camera, but I changed it to expo-camera and it worked very well!

Thanks anyway
