### ISSUE TITLE
Module `Libraries/StyleSheet/ColorPropType` could not be found after upgrading from expo 32 to 33

### ISSUE THREAD

**Issue by karlolopez** [expo/expo#4832]
Hi, I want to implement full administration in my Expo Project so I can send Push Notifications to both platforms via Expo, use image-picker easily and many more features so I decided to upgrade from expo 32 to 33 following the official guide and after a successful installation I get the following fatal error:

Recently read about a temp solution:
https://github.com/react-native-community/react-native-linear-gradient/issues/356#issuecomment-460044459

But honestly don't want to do that, I want to find the definitive solution.

`While resolving module `react-native/Libraries/StyleSheet/ColorPropType`, the Haste package `react-native` was found. However the module `Libraries/StyleSheet/ColorPropType` could not be found within the package.`

**Comment by karlolopez** [comment]
Just copied ColorPropType.js from Deprecated Modules folder to react-native/Libraries/StyleSheet/ and actually works but need to do this every time I run yarn/npm :S

**Comment by cruzach** [comment]
Hi! In order to look into this, we need you to give us all the info we ask for in the issue template (especially a repro!). 

Also- Are you sure this is an issue specifically with `expo` and not with `react-native-linear-gradient`?

**Comment by karlolopez** [comment]
> Hi! In order to look into this, we need you to give us all the info we ask for in the issue template (especially a repro!).
> 
> Also- Are you sure this is an issue specifically with `expo` and not with `react-native-linear-gradient`?

Thanks. Where can I find the issue template? 

The issue is with expo and react-native. Linear gradient repo was just a reference. 

Thanks

**Comment by cruzach** [comment]
https://raw.githubusercontent.com/expo/expo/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by lvojnovic** [comment]
I had a very similar error after updating Expo SDK from 32 to 33.

> While resolving module `react-native/Libraries/Components/View/ViewStylePropTypes`, the Haste package `react-native` was found. However the module `Libraries/Components/View/ViewStylePropTypes` could not be found within the package


The error was caused by some old code that did not trigger deprecation warnings in earlier versions. Example:
`import ViewStylePropTypes from 'react-native/Libraries/Components/View/ViewStylePropTypes';`

My hint is to try searching your project for `StyleSheet/ColorPropType` or `ColorPropType`. If it is not there try the same search in your dependencies (in node_modules).

**Comment by parthibanloganathan** [comment]
Also facing this issue. Receiving the error: `Unable to resolve "react-native/Libraries/StyleSheet/ColorPropType.js" from "node_modules/react-native-linear-gradient/index.ios.js"` when I upgraded to SDK 33

**Comment by lvojnovic** [comment]
@parthibanloganathan Try searching your code and the code of your dependencies for `ColorPropType`. Maybe you need to update some dependencies...
