### ISSUE TITLE
[lottie-react-native][Android][sdk-33]  Certain Lottie Animations cause App crashes on Android 8&9

### ISSUE THREAD

**Issue by tonnenpinguin** [expo/expo#4835]
### Environment
  Expo CLI 2.21.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      npm: 6.10.0 - ~/.npm-global/bin/npm
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.1.9 
      expo: 33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2

Other relevant packages:
    "lottie-react-native": "^2.6.1",

### Steps to Reproduce
Some Lottie Animations cause crashes on at least Android 8&9.

This seems to be a native code issue as we don't see anything showing up in our Sentry/Logs.

### Reproducible Demo
This snack reproduces the crash consistently on both Android 8&9 for us.

The animation starts 2 seconds after the app is loaded and initially plays back as expected. After a few frames the App crashes.

https://snack.expo.io/@fittrack/tenacious-blueberries

I don't think this is a duplicate of #4510 as it happens on the latest expo version and other users reported their problems to be fixed by the lottie update.

**Comment by cruzach** [comment]
Hey @tonnenpinguin, sorry you're running this 😕 
What version of the Expo client app are you running?

If it's the most recent, can you try running `adb logcat` to see if you can find out anymore about the crashing from those device logs?

**Comment by changLiuUNSW** [comment]
@tonnenpinguin I believe your lottie file is generated with latest lottie 3 format which is not supported by ```lottie-react-native``` in Android.
Unfortunately this is not going to change in near future due to compatible issue with Android X:
https://github.com/react-native-community/lottie-react-native/pull/485
Currently the only way to resolve our issues is to reexport the lottie file from bodymovin with old format by changing:
Settings > Advanced > Export Old Json Format

**Comment by tonnenpinguin** [comment]
Hi guys,

I'm running 2.11.4.

Thanks @changLiuUNSW! I'll give it a try! :)

**Comment by cruzach** [comment]
@tonnenpinguin let me know if that worked!

**Comment by tonnenpinguin** [comment]
We did move to an older json format (and just manually edit the values we needed changed) and now everything works as expected.

Interesting choice by the lottie guys to just let the whole app crash rather than raise an exception on an unsupported data format version but oh well :)
