### ISSUE TITLE
Allow choosing of audio source in Audio API

### ISSUE THREAD

**Issue by aquach** [expo/expo#484]
Right now it seems like if I use the Audio API to play and record at the same time, the resulting recording contains both the sound being played and the recording mixed together. That seems like unintentional behavior, which I'm hoping can be fixed by changing the audio source. Right now it's set to DEFAULT but I think setting it to MIC might fix my issue?

https://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html

Not sure if I'm looking at this right:

https://github.com/expo/expo/blob/6ce7840b3364c8bb0c4ddc7b97cb18aada87232b/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/av/AVModule.java

Thanks!

**Comment by aquach** [comment]
Looks like it was modified in this commit: https://github.com/expo/expo/commit/6e5d92e9454d0bdfaac5f4a3aa3fe778bbf802be

I don't know anything about Android, so maybe I'm on the wrong track, but some way to prevent recordings from picking up the audio being played would be nice. Thanks!

**Comment by ide** [comment]
Thanks for the report, this sounds like an option we should expose.

**Comment by aquach** [comment]
Hmm, testing some more, it looks like my headset could just be leaking into my microphone. I'm able to reproduce the issue with Google Play Music and a generic sound recording app. In that case, I'm not sure changing the setting will help.

**Comment by ide** [comment]
Interesting, that could be it. Android has a separate permission called `android.permission.CAPTURE_AUDIO_OUTPUT` that appears to be locked-down ("not for use by third-party applications") - based on that it seems likely that the recording API isn't directly recording your speaker audio stream.

**Comment by gkufera** [comment]
Hi @aquach !!!!

As @ide mentioned, it seems like changing the setting won't help. We're in the middle of QA now but will investigate this next week. FYI, we intend to eventually expose audio route as an option for both playback and recording so you will be able to test this in the javascript in the future.

In the meantime, do you have a bluetooth speaker (that doesn't have a microphone attached), and if so, can you get the app to play through the speaker but record through the phone? That might isolate the issue.

I hope you're doing well!!

Greg

**Comment by aquach** [comment]
Hey Greg,

Hope you're doing well too! I did try it using a Chromecast, and saw that no played sounds were picked up on the microphone. So the issue is with my headset. Thanks for the help!
