### ISSUE TITLE
[web] [expo-image-picker] [suggestion] Component for web + Returning base64 prop in web

### ISSUE THREAD

**Issue by NiciusB** [expo/expo#4840]
### Component for web 
It would be great to have a component that enables drag and dropping images in web (and maybe windows?). For ios/android, it could just behave as a Touchable that fires ImagePicker.launchImageLibraryAsync when pressed.

### Returning base64 prop in web 
Currenly, when enabling `base64` in the options, ImagePicker.launchImageLibraryAsync returns both uri and base64 for ios/android.
But in web the option `base64` is ignored and only uri is returned. It would make sense to also return a base64 prop when the `base64` option is enabled. (And remove the prepended `data:image/jpeg;base64,` for the base64 prop)

Edit: Just realized that I used the bug tag, instead of suggestion. Sorry!

**Comment by cruzach** [comment]
Hi @NiciusB ! Thanks for the suggestion, but we try to keep Github solely for bug reports, so could you instead fill out a request on our [Canny](https://expo.canny.io/feature-requests)?

Thanks!
