### ISSUE TITLE
iOS Unimodule Lifecycle

### ISSUE THREAD

**Issue by ninjaachibi** [expo/expo#4847]
iOS 

**Open app**  
`init` -> `setModuleRegistry`

**Reload JS bundle and manifest**
`dealloc` -> `init` -> `setModuleRegistry`

**Reload JS bundle**
`init` -> `setModuleRegistry` -> `dealloc`

This is app breaking for development since event emitters that should be initialized upon live/hot reloading (not sure which) become deallocated when a JS change is made during development.

**Comment by sjchmiela** [comment]
The workaround is a valid and recommended way to handle observers in unimodules. All setup should happen in `setModuleRegistry` and all deallocation in `dealloc`.
