### ISSUE TITLE
how to debug webview when use expo?

### ISSUE THREAD

**Issue by owcc** [expo/expo#485]
with native code, set **WebView.setWebContentsDebuggingEnabled(true)** is work for webview debugging. how to debug webview on expo?

**Comment by terribleben** [comment]
Can you provide more context on what you're trying to accomplish?

**Comment by AndyHubert** [comment]
Being able to debug a webview via expo would also be extremely helpful for me as I am needing to fix problems with displaying Readium books on Android in a webview as described [here](https://github.com/readium/readium-js-viewer/issues/628).

**Comment by dikaiosune** [comment]
Hi! I don't see this exposed in the JS interface of WebView, so I've opened a [feature request](https://expo.canny.io/feature-requests/p/support-running-debugger-against-webview-without-native-changes) for this.

**Comment by daicemirror** [comment]
Thanks for the great project and developers.

Could you provide another expo client that using WebView.setWebContentsDebuggingEnabled(true) in MainApplication.java?
Developing a hybrid application it's important to debug webview content on the application.
I tried to compile it myself but I always failed.
Please tell us any workaround to achieve this.
