### ISSUE TITLE
TypeError: Response is not a constructor in jest-expo 33

### ISSUE THREAD

**Issue by bvigerzi** [expo/expo#4859]
## 🐛 Bug Report
This bug is specific to the `jest-expo` package. I have included the version of `jest-expo` in the environment info below. This isn't included in the `expo diagnostics` printout normally.
### Environment
```
 Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13
      @types/react: ^16.5.0 => 16.8.14
      @types/react-native: ^0.57.20 => 0.57.47
      @types/react-navigation: ^3.0.1 => 3.0.6
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^2.18.2 => 2.18.3
      jest-expo: ^33.0.2 => 33.0.2
    npmGlobalPackages:
      expo-cli: 2.21.2
```

### Steps to Reproduce
1. Start a new Expo project
2. `yarn add jest-expo --dev` or `npm i jest-expo --save-dev`
3. Add following config to `package.json`
```json
"scripts": {
  "test": "node_modules/.bin/jest",
  "test:debug": "node --inspect-brk node_modules/jest/bin/jest.js --runInBand"
},
"jest": {
  "preset": "jest-expo"
}
```
4. Create a new test with the following body:
```typescript
const mockGet = jest.fn();
mockGet.mockReturnValue(new Response(
            JSON.stringify({
                data: true
            }),
            {'status': 200}
        ));
```

### Expected Behavior
The Response object will be created and `mockGet` will be mocked correctly.

### Actual Behavior
When running the test, a TypeError is raised. The error states that "Response is not a constructor".

### Solution
I have already debugged the latest `jest-expo` release (33.0.2) and found the line responsible. In `src/preset/setup.js`, line 8 was added this year which breaks the fetch mocks. When removing this line, the Response mock (and related mocks) work again. The line of code is; `global.self = global;`.

**Comment by ide** [comment]
The cause of this bug is that jest-expo was including its own copy of `whatwg-fetch` and defining fetch, Headers, Request, and Response. This worked in this repo but not outside where Haste was still enabled for RN. Since we want parity between the real and test environments, we're no longer including `whatwg-fetch` in the Jest setup script in https://github.com/expo/expo/pull/4875. If you do want to set up your own copy of fetch, you can import it yourself or reach into RN's private interface at `react-native/Libraries/vendor/core/whatwg-fetch`.
