### ISSUE TITLE
[expo-blur] SDK33 regression "Invalid view found for requested tag" 

### ISSUE THREAD

**Issue by wcandillon** [expo/expo#4863]
### Environment

SDK 33 on iOS

### Steps to Reproduce

Since upgrading to SDK33, animating a BlurView on iOS gives the following warning

```
[Unhandled promise rejection: Error: Invalid view found for requested tag]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:31 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:30 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:12 in MessageQueue.__invokeCallback
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:11 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:8 in MessageQueue.__guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:9 in MessageQueue.invokeCallbackAndReturnFlushedQueue
* http://localhost:19001/debugger-ui/debuggerWorker.js:80:58 in <unknown>
```

**Comment by cruzach** [comment]
Hey @wcandillon,

Could you provide a repro for this? List out the steps to take so that we can reproduce the error on our end. Thanks!

**Comment by wcandillon** [comment]
@cruzach thank you for getting back to me and sorry for not doing this earlier: 
Here is the snack: https://snack.expo.io/@wcandillon/authentic-cookies you need to tap a lots of time for the warning to appear. The video of the warning appearing on tap is available here: https://www.dropbox.com/s/6oggnpt9mzuvtpo/RPReplay_Final1562770368.MP4?dl=0

**Comment by cruzach** [comment]
> you need to tap a lots of time for the warning to appear
 
How many? I rapidly tapped at least 50 times, didn't receive any warning.

**Comment by wcandillon** [comment]
Is it possible that snack is running a different version of expo than me? I was not able to reproduce it on snack although I can consistently repoduce the issue locally with expo33

**Comment by wcandillon** [comment]
or that snack hides this warning somehome?

**Comment by cruzach** [comment]
Oh wasn't aware that it needed to be run locally. I'll try that now.

Snack always runs in production

**Comment by cruzach** [comment]
@wcandillon - still no warning coming up when tested through `expo-cli`

**Comment by wcandillon** [comment]
here it is:
https://www.dropbox.com/s/1f84c19v0fadfk0/expo-blur-warning.zip?dl=0

**Comment by wcandillon** [comment]
@cruzach Are you able to reproduce this warning on your side?

**Comment by cruzach** [comment]
Yes, just reproduced the warning on SDK 35. Although, it only happens if I **rapidly** tap the component

Looks like the error is thrown [here](https://github.com/expo/expo/blob/87558b0d6314311a34c9a3a55b68b9a6ac831d7f/packages/expo-blur/ios/EXBlur/EXBlurViewManager.m#L64) if you want to take a deeper look

**Comment by jhalborg** [comment]
Hm, this exact error message has started popping op on Sentry for me over the last 3-4 days, in spite of the app not using `BlurView` explicitly anywhere. Are there any other components that rely on this?

**Comment by jbrodriguez-bytelion** [comment]
This is happening to me on SDK36 as well

**Comment by jhalborg** [comment]
That was it for me as well @jbrodriguez-bytelion - haven't found out why, though. The errors started from a specific deploy, but no change was made to package versions.

**Comment by faoiseamh** [comment]
I'm seeing this in production as well with SDK 35. Also not using BlurView explicitly but I am using `react-native-expo-image-cache`. It's not obvious what is triggering this for me and I haven't been able to reproduce it locally. I'm seeing this on iOS only, although my users are predominantly iOS so it may just be a reflection of that.

Was this resolved for others by upgrading SDKs or is this still an issue folks are seeing in the wild?
