### ISSUE TITLE
Unable to resolve module '@unimodules/core'

### ISSUE THREAD

**Issue by Triggybet** [expo/expo#4864]
## 🐛 Bug Report

We are running SDK 31 for our current project. The source code works fine for my colleagues, however I see the error pasted below. I have done steps 1-4 without success.

Unable to resolve module `@unimodules/core` from `/.../node_modules/expo-analytics/node_modules/expo-constants/build/ExponentConstants.js`: Module `@unimodules/core` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

ABI31_0_0RCTFatal
__37-[ABI31_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

### Environment

Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.21.2

### Steps to Reproduce

I have tried all 4 suggested posted above.

1. Upgrade from SDK 31 -> SDK 33
2. Downgrade from SDK 33 -> 31

That's when the errors started to appear.

### EXPO diagnostic from working computer

Our working setup looks like this.

  Expo CLI 2.10.1 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.4
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^2.18.2 => 2.18.2
    npmGlobalPackages:
      expo-cli: 2.10.1

**Comment by Triggybet** [comment]
FYI I have also tried running expo start -c without success

**Comment by cruzach** [comment]
Hey @Triggybet, sorry you're running into this issue. So the exact same repo works on your colleagues devices, but not your own? What version of `expo-cli` are they running?

Also- if you could share a reproducible example with me that'd help a lot!

**Comment by Triggybet** [comment]
Hi, @cruzach version 2.10.1.

**Comment by Triggybet** [comment]
Closing this issue as problem was related to 3rd party package bug.

**Comment by jamesleech** [comment]
hey, @Triggybet which third party package?
