### ISSUE TITLE
Support filename.expo.[ios/android/web/_/etc].[tsx/ts/js]

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#4867]
This makes it easier to execute different code when you are using your app in the client or in a bare project. Maybe instead of `expo` could be `managed`.

Right now we need to do something like this:

```js
let Module;
if (Constants.appOwnership === 'expo') {
  Module = require('./ModuleClient').default;
} else {
  Module = require('./ModuleBare').default;
}
```

**Comment by EvanBacon** [comment]
Done
