### ISSUE TITLE
Make it clear if using tunnel that LAN or localhost improve loading speed (Original title: Speed of Live Reload or manual Reload)

### ISSUE THREAD

**Issue by farzd** [expo/expo#487]
Hey Guys,
Is it normal for live reload to take 3-4 seconds? even on small things like text change?
Vanilla react-native in comparison is instant.  I've tried turning off dev mode too

My project is pretty barebones, i noticed the speed even on Hello World.
![image](https://user-images.githubusercontent.com/1423413/29211742-b87f7d1e-7e92-11e7-978c-d770565fb31a.png)

**Comment by erdogany** [comment]
I feel the same, while normal react-native is able to instantly update things, I find expo is slow when it comes to live reload

**Comment by brentvatne** [comment]
hello! please change from tunnel to LAN or localhost, that will solve your problem. we need to make this more obvious :)

**Comment by erdogany** [comment]
Hmm actually tried localhost before I post but it didn't make any difference, but now I tried LAN and it's much better. Although I might have forgotten to restart after I changed it to 'localhost'.... Thanks!

**Comment by farzd** [comment]
Thanks @brentvatne, i tried that but i'm not sure its any better.
I was having this discussion on the expo forums https://forums.expo.io/t/simulator-slow-to-refresh/519/10

i've done a quick speed test between Expo and Create-react-native-app, the latter seems to be much quicker and subsequent manual reloads in create-react-native-app are really fast too,
I've added a quick screencast of me using both - in the repo, you can get an indication of the loading time by noticing when the loader starts on the simulator and when the update is rendered.
[note: I used http as the protocol on expo but got same results by using the expo protocol]

https://github.com/farzd/expoSpeedTest
