### ISSUE TITLE
[docs] Wrong import name in Upgrading ExpoKit android to SDK32

### ISSUE THREAD

**Issue by baradusov** [expo/expo#4876]
In [instruction about upgrading ExpoKit](https://docs.expo.io/versions/v32.0.0/expokit/expokit/#android-1) to SDK32 step 4 suggests adding imports in `MainApplication.java`. First import is `import org.unimodules.core.interfaces.Package;`. I think there should be `import expo.core.interfaces.Package;` like in `MainActivity.java`.

With current import (unimodules) gradle build failing with
`error: package org.unimodules.core.interfaces does not exist
import org.unimodules.core.interfaces.Package;`

Installing react-native-unimodules[ only appears in SDK33](https://docs.expo.io/versions/v33.0.0/expokit/expokit/#android-1).

**Comment by tsapeta** [comment]
Which version of `react-native-unimodules` do you have?

**Comment by baradusov** [comment]
@tsapeta I don't have `react-native-unimodules` installed. I have been upgraded datached project to **SDK32** and in docs there is no such step to install `react-native-unimodules` (only for upgrading to SDK33). Was I supposed to install  `react-native-unimodules` after all?

**Comment by cruzach** [comment]
Expokit has been deprecated in favor of the bare workflow, so I'm going to close this issue. @baradusov if you init a new bare project with `expo init`, unimodules will come preconfigured
