### ISSUE TITLE
how to reduce the size of the build for android

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#4877]
As i found, need some files those belongs to react-native app but those file are not present into expo project.
I am not getting it how can i reduce the size of the build, for now my build size is 35mb
google play giving an error 

`
Unoptimized APK
Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Resolution:

Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.`

**Comment by AdamJNavarro** [comment]
Hey @reactexcel,

You'll want to run the command `expo build:android -t app-bundle` to make use of AAB's. Note that this only works with SDK33 builds.

Cheers,
Adam

**Comment by lylest** [comment]
i am facing the same issue  can somebody help us to solve this myth

**Comment by lylest** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/34285538/61161566-2fd67680-a4b9-11e9-9aad-356dfbffc2bb.png)

**Comment by brentvatne** [comment]
@lylest - as @AdamJNavarro said, `expo build:android -t app-bundle`

**Comment by overclokk** [comment]
Thank you @AdamJNavarro

**Comment by xgenem** [comment]
So we're basically being forced to use app-bundles for releases now right?

**Comment by khatiblou** [comment]
What do you recommend for those of us that don't use Google Play to distribute Android apps ? I distribute my Android app from my website.

It looks like we might be able to use a local tool from Google to generate APKs from the app bundle, but not sure. 

bundletool build-apks --bundle=/MyApp/my_app.aab --output=/MyApp/my_app.apks

https://developer.android.com/studio/command-line/bundletool
