### ISSUE TITLE
Google login doesn't work in android standalone builds apk

### ISSUE THREAD

**Issue by edoantonioco** [expo/expo#4879]
## 🐛 Bug Report

In the emulator while developing it I can use google login as the documentation recommends
https://docs.expo.io/versions/latest/sdk/google/
but when I did
expo build:android
and I generated a new apk for android, in that new build the expo login webview window doesnt even launch

### Environment
 expo 33

### Steps to Reproduce
1. Add google login as mentioned here https://docs.expo.io/versions/latest/sdk/google/ (for a normal expo app)
2. test it to check that it works properly
3. run expo build:android
4. Install the generated apk
5. Click on the buttom that is meant to open the google login, it does nothing

### Expected Behavior

google login should open the webview

### Actual Behavior

it does nothing, it should open the login prompt but it does not 

### Reproducible Demo

Here is a snack where it works properly
https://snack.expo.io/@edoantonioco/google-login-example
and this
https://expo.io/@edoantonioco/snack-SkFjFvZ-r

and here is an apk generated
https://expo.io/builds/c5f6fb2c-2d7a-4145-a321-131aded2697b

if you try the first 2, google login view will show up. But not in the apk, where its that it really matters to work.

**Comment by cruzach** [comment]
There are different configuration steps for standalone apps as opposed to apps running in the Expo client. I would [check here](https://docs.expo.io/versions/latest/sdk/google/#deploying-to-a-standalone-app-on-android) to make sure you've followed them.

**Comment by edoantonioco** [comment]
there was a step I did not followed. At least now it show up so this specific bug is fixed
