### ISSUE TITLE
BlurView doesn't work

### ISSUE THREAD

**Issue by gen4sp** [expo/expo#488]
It doesn't blur at all. 
Why it could happen?
<img width="346" alt="screen shot 2017-08-11 at 16 36 16" src="https://user-images.githubusercontent.com/4303628/29215335-474b42ce-7eb3-11e7-88be-618442434515.png">

```
<View style={{ flex: 1 }}>
        <Image style={{ width: 192, height: 192 }} source={{ uri }} />

        {/* Adjust the tint and intensity */}
        <BlurView tint="light" intensity={50} style={StyleSheet.absoluteFill}>
          <Image style={{ width: 96, height: 96 }} source={{ uri }} />
        </BlurView>

        <StatusBar hidden />
      </View>
```

The example from expo site, just under the `StackNavigator` of  `react-navigation`

**Comment by davepack** [comment]
Are you having trouble with blurview in your own code or are you having trouble getting the example to run?

**Comment by brentvatne** [comment]
hey @gen4sp - please post the full code. the code that you provided is not the actual code that you used. how do I know this?

![](http://url.brentvatne.ca/jfbe3.png)

if possible, post a link to the project. this definitely works, go ahead and open https://snack.expo.io/SyElpRoDb on your phone. happy to help you debug the bug in your code though.

**Comment by brentvatne** [comment]
```
import React from 'react';
import { Image, StyleSheet, View, StatusBar } from 'react-native';
import { BlurView } from 'expo';

const uri = 'https://s3.amazonaws.com/exp-icon-assets/ExpoEmptyManifest_192.png';

export default class BlurViewExample extends React.Component {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <Image style={{ width: 192, height: 192 }} source={{ uri }} />

        {/* Adjust the tint and intensity */}
        <BlurView tint="light" intensity={50} style={StyleSheet.absoluteFill}>
          <Image style={{ width: 96, height: 96 }} source={{ uri }} />
        </BlurView>

        <StatusBar hidden />
      </View>
    );
  }
}
```

![screen shot 2017-08-11 at 8 04 23 pm](https://user-images.githubusercontent.com/90494/29237300-51821e9e-7ed0-11e7-9d76-06b2278f7528.png)


please share full example project link in a new issue, thanks :) we can't do much without an actual repro case

**Comment by laureldaigneault** [comment]
The problem still occurs.
Anybody found a way to fix this issue? I see it has been closed but not solved.
Still, either the example from the doc (even in the embed emulator) nor my implementation seem to work.

**Comment by kiorq** [comment]
Still occur for me too

**Comment by laureldaigneault** [comment]
Had the chance to play with it tonight.
Seems I could only blur images underneath, and "once".
I mean, when the component (BlurView) renders, it calculates and show the blur for what was underneath it at the moment of the render,
But let say you had it over a ScrollView, and you scroll, the blur effect won't "move" with it.
Was it made to be like that, and could it be an interesting feature to launch in the future? To be able to blue "realtime" what is underneath the BlurView?

**Comment by ac1dr3d** [comment]
add viewrefs prop to blu component + add this.setState({ viewRef: findNodeHandle(this.refs.content) }); on componentDidMount (with timeout);

the only solution here...

it works without expo... with BlurVeiw component. react-native-blur i believe.

**Comment by sirajulm** [comment]
IMO, it is not blurring the view behind it. It just sets an opacity to the container. This probably need to be renamed as, `transparency` or `translucency`. Object blur or background blur is a different concept, as handled by`react-native-blur`

**Comment by brentvatne** [comment]
@sirajulm - on android it doesn't actually blur, but on ios it indeed is the same thing as react-native-blur
