### ISSUE TITLE
[ios] `pod install` in shellAppWorkspaces causes machine to run out of disk space and crash

### ISSUE THREAD

**Issue by esamelson** [expo/expo#4887]
This has been an issue for at least a few months now -- when I try to run the `gulp ios-shell-app` task locally and generate a shellAppWorkspaces folder, the `pod install` step in this folder never completes, causing my machine to quickly run out of disk space and then crash. My recollection is that running in verbose mode, it fails after logging `    - Generating deterministic UUIDs`. This makes local debugging of both turtle issues and failing CI jobs significantly more difficult. We should figure out why this is happening and make the shellAppWorkspaces project lightweight/possible to run locally.

**Comment by ide** [comment]
We'll probably need to run a Ruby heap analyzer to find out why it's using so many resources. I believe it uses a lot of memory, which then eats up all the swap space.

**Comment by ide** [comment]
Several people on the team are running into this -- let's move this up in priority for SDK 35.
