### ISSUE TITLE
GET /message/device GET /inspector/device

### ISSUE THREAD

**Issue by flieks** [expo/expo#489]
I'm seeing this in left console in XDE every 2-3 seconds.. Very strange
```
3:31:27 PM
::1 - - [11/Aug/2017:13:31:27 +0000] "GET /inspector/device?name=PRA-LX1%20-%207.0%20-%20API%2024 HTTP/1.1" 404 67 "-" "okhttp/3.4.1"
3:31:27 PM
::1 - - [11/Aug/2017:13:31:27 +0000] "GET /message?device=PRA-LX1%20-%207.0%20-%20API%2024&app=host.exp.exponent&clientid=DevSupportManagerImpl HTTP/1.1" 404 121 "-" "okhttp/3.4.1"
```

**Comment by sjchmiela** [comment]
XDE has been deprecated (see [this blog post](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c)) and this issue should have been fixed in latest `expo-cli` with https://github.com/expo/expo-cli/commit/88aeb735808fe86da5789e699099cdf3fd0bfd74. 🙂
