### ISSUE TITLE
AppAuth / Android: wrong parameter order when creating AuthorizationServiceConfiguration

### ISSUE THREAD

**Issue by sgehrig** [expo/expo#4896]
### Environment

```
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2
```

Target is android, iOS works fine.

### Steps to Reproduce

Setup `AppAuth` without service discovery and provide `authorizationEndpoint` and `tokenEndpoint` via `serviceConfiguration` directly.

```javascript
const config = {
    issuer: apiUrl,
    scopes: ['all'],
    clientId: clientId,
    serviceConfiguration: {
        authorizationEndpoint: `${apiUrl}/authorize`,
        tokenEndpoint: `${apiUrl}/access_token`,
    }
};
```

### Expected Behavior

`AppAuth` starts an Authorization Code Grant flow against the provided urls.

### Actual Behavior

`AppAuth` tries to call the `tokenEndpoint` as if it was the `authorizationEndpoint` using a `GET` request and including all parameters required for authorising the request.

### Reproducible Demo

Not needed, because we already figured out the problem.

In 

https://github.com/expo/expo/blob/61a00b0eccc12bc9279d171b3160ace24520ec67/packages/expo-app-auth/android/src/main/java/expo/modules/appauth/AppAuthModule.java#L67-L71

the constructor parameters are swapped. The `net.openid.appauth. AuthorizationServiceConfiguration` constructor takes the parameters in the following order: first `authorizationEndpoint ` and then `tokenEndpoint` (and then `registrationEndpoint`) - not the other way round. See here:

https://github.com/openid/AppAuth-Android/blob/f12592517140ecfe91a411090601b4264ddb641f/library/java/net/openid/appauth/AuthorizationServiceConfiguration.java#L120-L123

So the Android build only works with service discovery and not when manually configuring AppAuth.

**Comment by tomvanderlee** [comment]
Is there a fix incoming for this issue?
