### ISSUE TITLE
AppAuth / Android: undefined vs. null when configuring service manually

### ISSUE THREAD

**Issue by sgehrig** [expo/expo#4897]
### Environment

```
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2
```

Target is android, iOS works fine.

### Steps to Reproduce

Setup `AppAuth` without service discovery and provide `authorizationEndpoint` and `tokenEndpoint` via `serviceConfiguration` directly but do not provide `clientSecret` and/or `registrationEndpoint`, both of which are optional.

```javascript
const config = {
    issuer: apiUrl,
    scopes: ['all'],
    clientId: clientId,
    serviceConfiguration: {
        authorizationEndpoint: `${apiUrl}/authorize`,
        tokenEndpoint: `${apiUrl}/access_token`,
    }
};
```

### Expected Behavior

Besides the problem described in https://github.com/expo/expo/issues/4896 which renders the whole approach unusable, I'd expect that `AppAuth` starts an Authorization Code Grant flow against the provided urls.

### Actual Behavior

Error messages happen because of problems with `clientSecret` and/or `registrationEndpoint` are undefined. If you set both parameters to `null`, it'd work in general (besides the problem described in https://github.com/expo/expo/issues/4896). We tested it with switching the `authorizationEndpoint` and `tokenEndpoint`.

The following would work:

```javascript
const config = {
    issuer: apiUrl,
    scopes: ['all'],
    clientId: clientId,
    clientSecret: Platform.OS === 'ios' ? undefined : null,
    serviceConfiguration: {
        authorizationEndpoint: `${apiUrl}/authorize`,
        tokenEndpoint: `${apiUrl}/access_token`,
        registrationEndpoint: Platform.OS === 'ios' ? undefined : null,
    }
};
```

By the way: the platform switch is required because the iOS build does not work well with the `null` values and expects `undefined` instead.

### Reproducible Demo

Just use the example code provided in https://docs.expo.io/versions/latest/sdk/app-auth/ but change the configuration to use manually configured endpoints instead of service discovery.

**Comment by bradjones1** [comment]
This is fixed in https://github.com/expo/expo/commit/a78392d762975021d258e7f51a001bc71c44b8e0

**Comment by esamelson** [comment]
Going to close this as the referenced commit was included in the last release
