### ISSUE TITLE
Push notification not trigger for ok status message when an error in a single receipt but not the entire request.

### ISSUE THREAD

**Issue by pasanascentic** [expo/expo#4898]
### Environment

Application Structure 

Simply we have a Expo API call application structure showed in the given link [https://docs.expo.io/versions/latest/guides/push-notifications/#2-call-expos-push-api-with-the](url)

React native application used following expo packages,
-  "expo": "^33.0.0",
-  "expo-asset": "^5.0.1",
-  "expo-constants": "^5.0.1",
-  "expo-font": "^5.0.1",

DotNet core project (backend) used Expo API V2 to call the push notifications.

### Steps to Reproduce

1. Create an array of receipts  to send multiple messages to efficiently minimize the number of requests you need to make to Expo servers.  Array contains two receipts. First one is valid and return _status "ok"_ but second one is invalid and return error _The recipient "{token goes here}" is associated with a different experience than @app_
2. Use http web request to call the Expo web API by passing the array of receipts.
Sample code below (This is not the actual code),
`public static dynamic SendPushNotification(string ExpoToken)`
`{`
`    dynamic body = new [`
`        new {`
`            to = ExpoToken1,`
`            title = "hello",`
`            body = "world",`
`            sound = "default"`
`        },`
`        new {`
`            to = ExpoToken2,`
`            title = "hello",`
`            body = "world",`
`            sound = "default"`
`        }`
`    ];`
`    string response = null;`
`    using (WebClient client = new WebClient())`
`    {`
`        client.Headers.Add("accept", "application/json");`
`        client.Headers.Add("accept-encoding", "gzip, deflate");`
`        client.Headers.Add("Content-Type", "application/json");`
`        response = client.UploadString("https://exp.host/--/api/v2/push/send", JsonExtensions.ToJson(body));`
`    }`
`    var json = JsonExtensions.FromJson<dynamic>(response);`
`    return json;`
`}`

3. Retrieve the respond. Respond is below,

`"{\"data\":[{\"id\":\"6fa559e6-c618-48c2-b2f1-e35ab169a363\",\"status\":\"ok\"},{\"status\":\"error\",\"message\":\"The recipient \\\"{token goes here}" is associated with a different experience than \\\"@app\\\"\"}]}"`

4. No Push Notification for the status "ok" receipts.

### Expected Behavior

Push Notification for the status "ok" receipts.

### Actual Behavior

No Push Notification for the status "ok" receipts.

### Reproducible Demo

**Please note that Push Notifications received for the single receipt. Multiple valid receipts (status = "ok") receipts.**

I have already added sample code and response to the issue at the top. Please let me know if you need any more information. I don't think I can add Reproducible Demo for this.

Appreciate if you can support me on this matter. Thank you :)

**Comment by AdamJNavarro** [comment]
Hey @pasanascentic,

Is there any chance you have changed the project's `slug` value or have different accounts with the associated project? If so, I'm thinking you may have saved tokens to your backend that are not compatible with your current project as Expo experiences rely on both the `slug` value and account name to differentiate.

Cheers,
Adam

**Comment by ide** [comment]
When you send notifications, you get back tickets with receipt IDs. You later need to look up the actual receipts, *not* just the tickets. If the receipt says "ok", then there is an issue.

**Comment by cruzach** [comment]
As @ide said above, you need to check the push **receipt** for errors, as well. There are helper methods for doing that in each of the server SDKs, and you can also do it easily from your terminal just to test it. If you need more information, please give our [Sending Push Notifications guide](https://docs.expo.io/push-notifications/sending-notifications/) a read 😄 

Closing this for now, if you encounter an error with push notifications please open a new issue with the push receipt's error message and preferably a reproducible demo
