### ISSUE TITLE
Is it possible to include the assets in app bundle instead of Amazon CloudFront?

### ISSUE THREAD

**Issue by pronevich** [expo/expo#49]
Documentation says:

> Each time you publish your app, Exponent will upload your assets to Amazon CloudFront, a blazing fast CDN.

I want the assets to exist when user install app from play market with no need to wait anymore for loading assets from CDN and to avoid this step:

> In order to keep the loading screen visible while we cache our assets, we render Exponent.Components.AppLoading and only that component until everything is ready.

Is it possible to include assets in app bundle and remove AppLoading component because it will be useless?

**Comment by pronevich** [comment]
It seems I understand now this case with assets. This possible when building standalone app. Am I right?

**Comment by dikaiosune** [comment]
It is possible, yes, but unfortunately not without significant overhauls to how we build standalone apps. We have a number of plans to improve this in the future, so I'll leave this open as a reminder while we're working on this.

**Comment by dikaiosune** [comment]
We're now tracking this feature request at https://expo.canny.io/feature-requests/p/allow-standalone-apps-to-load-and-function-with-no-internet-connection. Thanks!
