### ISSUE TITLE
"Pin" button doesn't actually create shortcut icon (Android Oreo)

### ISSUE THREAD

**Issue by danopia** [expo/expo#491]
Hey, I used snack to make a utility app but I'm having trouble adding it to my homescreen. When I select the pin icon on the Expo notification, I get sent to my homescreen but nothing is added. I've tried a handful of times and the outcome doesn't change.

I'm running Expo 1.18.4 on a Google Pixel XL with the latest Android Beta (Android 8.0). I suspect this might be a compatibility problem with the [Pixel Launcher](https://play.google.com/store/apps/details?id=com.google.android.apps.nexuslauncher) that Google ships.

I also tested on a Nexus 6P (Android 7.1.2) and the shortcut was properly added to Nova Launcher.

**Comment by danopia** [comment]
I apologize for the rapid follow, logcat very quickly gave me more info.

`ActivityManager: Broadcast com.android.launcher.action.INSTALL_SHORTCUT no longer supported. It will not be delivered.`

Then I found:

>The com.android.launcher.action.INSTALL_SHORTCUT broadcast no longer has any effect on your app, because it is now a private, implicit broadcast. Instead, you should create an app shortcut by using the requestPinShortcut() method from the ShortcutManager class.

Source: https://developer.android.com/preview/behavior-changes.html

So, seems like Android O will require apps to add homescreen shortcuts via a different API.

**Comment by KevinAst** [comment]
It appears to me this issue is broader than Android O.

I am experiencing the same problem (where pins simply no-op) on Android 7.1.2 after updating to Expo Client 1.19.0.

**Comment by jesseruder** [comment]
Works on my Pixel with 7.1.2 @KevinAst. Is there an error in your log?

**Comment by KevinAst** [comment]
@jesseruder - Thanks for you quick response.

My Expo client started miss-behaving after updating to Expo Client 1.19.0 (7 hrs ago).

- I lost all home screen icons (both my expo apps and the expo client itself).
- The expo "pin" was basically no-oping.
- I don't recall seeing anything in the logs, but in trying to re-create this, my Expo client is not even running :-( It launches with a blue screen stating it "requires an internet connection" ... hmmmm

Based on all this, **_I un-installed and re-installed the expo client._**

**It now is working correctly!**

Not sure what this was ... something quirky happened in the upgrade.

Thoughts?

Thanks again for your quick response.

**Comment by jesseruder** [comment]
Ok, that's concerning. I'll try to reproduce that but not sure what's going on. Weird that the Expo app home screen icon would disappear since that's controlled by the Play Store app.

**Comment by jesseruder** [comment]
Just pushed a build to the Play Store that should resolve the "requires an internet connection" error. Haven't looked into the pin bug yet.

**Comment by danopia** [comment]
Guess what, [Android Oreo is officially released](https://www.android.com/versions/oreo-8-0/). I took the update and the pin feature remains broken.

This message remains unchanged: `ActivityManager: Broadcast com.android.launcher.action.INSTALL_SHORTCUT no longer supported. It will not be delivered.`

**Comment by jesseruder** [comment]
Thanks, I realize it's officially released. Haven't had time to fix yet but will get it into the next release. Feel free to send a PR if you get there before me!

**Comment by herdani** [comment]
+1

Same `com.android.launcher.action.INSTALL_SHORTCUT no longer supported` error, with Android O

**Comment by tasomaniac** [comment]
`ShortcutManagerCompat` from support library handles this for you. It also uses the legacy Intent mentioned here to add the shortcut to older devices. 

Here is an example:

```

        ShortcutInfoCompat shortcut = new ShortcutInfoCompat.Builder(getContext(), id)
                .setIntent(intent)
                .setShortLabel(label)
                .setIcon(icon)
                .build();
        ShortcutManagerCompat.requestPinShortcut(getContext(), shortcut,null);
```

**Comment by jesseruder** [comment]
@tasomaniac, yeah using the support library is easy but it's non-trivial to update the app to target the correct sdk version. For now we've removed the pin button

**Comment by tasomaniac** [comment]
This change is not relevant to targetSdk at all. You need to compile
against 26 and use support lib 26. You can keep targetSdk whatever you
want. And what's more is that the above code piece will add the pin
(shortcut) for all devices (both Oreo and older versions).

**Comment by jesseruder** [comment]
You're right @tasomaniac, I was trying to batch this with the work of updating the targetSdk but that turned out to be more work than I was expecting. Feel free to send a PR updating just compileSdk and this if you get there before me.

**Comment by KevinAst** [comment]
The Expo Client (ver 23) was updated on my Pixel 11/17/2017 (in support of Expo SDK 23) -AND- the **PIN BUTTON IS BACK!**

Thought you would want to know.

I am under the impression that the "pin" button has NEVER been available on ios (i.e. only supported on android).  **_Can someone please confirm this?_**

**Comment by jesseruder** [comment]
@KevinAst, correct only supported on Android. Sorry about this everyone! We'll make sure to keep this working.

**Comment by itslittlejohn** [comment]
I've noticed that this works fine with the stock Android launcher, but breaks for Action Launcher and Nova Launcher. I'm not sure, but I'm guessing this is still a bug with expo. Pinning things to the home screen from within other apps works with both of these third party launchers without difference. (For example, pinning a file/folder from Google Drive). 

Is it possible to handle this in a way that would work for any launcher system (the way I'm assuming Google Drive does it)?

**Comment by brentvatne** [comment]
@itslittlejohn - i moved that into a more specific issue. i'm sure it is possible to handle it but we have not investigated it yet. if you can figure it out and want to open a pull request that would be welcome!
