### ISSUE TITLE
hi! i really wish someone helps me.

### ISSUE THREAD

**Issue by pattyditz** [expo/expo#4916]
well i am new to android programming using react native. My expo on my android device doesn't scan the code on my pc. can i know why or how to fix it?

**Comment by YoshiYo** [comment]
You can send the link by sms if you want. 
Start your project and then press `e` to send a link on your phone.

**Comment by tsapeta** [comment]
You can also login to your Expo account using `expo login` command and do the same in Expo client app. Then you will see the project you started by `expo start` under `Recently in development` section of the Projects screen.
I'm closing this thread - if you need any help, please use our [forums](https://forums.expo.io) instead.

**Comment by pattyditz** [comment]
ok, thanks.
