### ISSUE TITLE
Hermes evaluation

### ISSUE THREAD

**Issue by ide** [expo/expo#4927]
We need to make sure that Hermes:

- is debuggable on-device
- can run on iOS
- can run plain JS (in addition to HBC) without issues
- that all tests pass
- that we maybe have an incremental upgrade path, if we think there is risk

**Comment by sjchmiela** [comment]
Helpful note: when upgrading React Native to 0.60, at least several commits from https://github.com/expo/expo/pull/4593/commits should make it easier.

**Comment by tsapeta** [comment]
We also need to evaluate how GLView will work with Hermes, probably we will have to speed up our work on #4377

**Comment by wkozyra95** [comment]
- Hermes releases are not backward compatible, so we will need to version it somehow or support hermes in client only for sdk with latest react-native,

- bytecode generated with one version of hermes will work only with the same version of vm (@esamelson  this might be important for `expo-updates` module)

**Comment by ide** [comment]
Closing since Kudo has looked into this.
