### ISSUE TITLE
Guide for explaining how to add features to SDK

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#493]
Moved from https://github.com/expo/expo-sdk/issues/77

**Comment by FiberJW** [comment]
This now exists in the form of https://github.com/expo/expo/blob/master/CONTRIBUTING.md and https://github.com/expo/expo/blob/master/guides/Expo%20Universal%20Module%20Infrastructure.md. If you think this needs further investment, please open another issue. Thanks :)
