### ISSUE TITLE
unable to create new expo account web or android app

### ISSUE THREAD

**Issue by crcnum4** [expo/expo#4930]
### Steps to Reproduce

website:
1. open https://expo.io/signup
2. fill out form
3 click "Create account"

android client
1. open app.
2. tap profile
3. tap sign up for expo
4. fill out form
5. tap signup

### Expected Behavior

on website and android app:
successful account creation.

### Actual Behavior

website:
the button spinner appears then disappears.
no error nothing.
checking the network tag under the developer bar shows a Graphql error.

Android:
activity indicator
alert pops up giving postgres error
![Screenshot_20190711-155227_Expo](https://user-images.githubusercontent.com/14855448/61081479-516e2a00-a3f5-11e9-8d43-50633c5c6715.jpg)

### Reproducible Demo
https://expo.io/signup
https://play.google.com/store/apps/details?id=host.exp.exponent&hl=en_US

**Comment by crcnum4** [comment]
I've tried a different email. and I've also tried other usernames

**Comment by ide** [comment]
@crcnum4 sorry about that, there was a server-side issue, mind trying again?
