### ISSUE TITLE
Support Offline not working

### ISSUE THREAD

**Issue by alirezadarvishi** [expo/expo#4937]
I'm using offline support but not working and stuck on the splash screen for much time. 
App loading is very fast When I change my IP to another country like Germany and I think this is like bottom question. But I did not use AppLoading.

### **The app loading is very fast When wifi or data are discontented.**

https://github.com/expo/expo/issues/1751#event-2412233626
@zhaozhiming

**Comment by cruzach** [comment]
Hi! Could you fill out the full issue template? It asks for all the info we need to troubleshoot effectively

**Comment by alirezadarvishi** [comment]
Expo CLI 2.21.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Users\Alireza\AppData\Roaming\npm\yarn.CMD
      npm: 4.6.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338


I've build my project by expo build:android and now app takes long time to load and start (it stuck on splash screen),but when I use a proxy it is load is very fast.


I think expo need to check something when i started the app but that is banned in my country so it took so long time to load at beginning.

**Comment by alirezadarvishi** [comment]
any idea for this problem?

**Comment by alirezadarvishi** [comment]
> Hi! Could you fill out the full issue template? It asks for all the info we need to troubleshoot effectively

**Comment by cruzach** [comment]
@alirezadarvishi- I'm not sure this is a problem with Expo, since you're able to get the correct behavior by changing your IP address..

Really hard to say what could be wrong without more information
