### ISSUE TITLE
exp build:ios gives an error - Request failed with status code 500

### ISSUE THREAD

**Issue by PavithaW** [expo/expo#4940]
Hi there,
I'm having an error while building an IPA file using expo.
Steps Followed,

1. cd project_folder
2. npm install -g exp
3. exp start
4. exp build:ios
5. I chose expo to handle all credentials
6. Then I provided my apple Id and password
7. I chose 'Let Expo handle the process for both Distribution Certificate and Push Certificate'

It creates iOS Distribution certificate, Apple Push Services under the certificates section, Provisioning Profile under the profile section and App ID Configuration under the Identifiers section in my Apple developer account.

Then I'm having an error,
`Error while gathering & validating credentials`
`Request failed with status code 500`

Tried the same process multiple times but still have the same error.
This is the screenshot of the error,

<img width="975" alt="3" src="https://user-images.githubusercontent.com/12149006/61165434-e7c05e00-a563-11e9-88a9-65d83f7238db.png">

Thanks in advance!

**Comment by jkjohan** [comment]
I have exactly the same problem!

**Comment by ide** [comment]
It looks like this could be because you're using `exp`, which was deprecated over a year ago. Please see the notice that `exp` printed out at the top of your terminal output. You can install it with `npm install -g expo-cli`.

**Comment by carlosbpf** [comment]
I had the same problem with expo cli for two days. The problem goes away if you update to the newest version:

There is a new version of expo-cli available (2.21.2).
You are currently using expo-cli 2.6.14

**Comment by AdamJNavarro** [comment]
Hey @PavithaW and @jkjohan,

As James and Carlos mentioned, you'll want to upgrade to the latest `expo-cli` version as `exp` has long since been replaced. I'm going to close this issue. If you have any issues with the new devtools, please open an issue [here](https://github.com/expo/expo-cli/issues).

Cheers,
Adam

**Comment by PavithaW** [comment]
Thanks guys. It worked with expo-cli 👍
