### ISSUE TITLE
How can I handle split-screen mode on Android?

### ISSUE THREAD

**Issue by mileskrell** [expo/expo#4944]
When running an app on Android in the Expo client app, if I put the app into split-screen mode, it restarts.

How can I keep this from happening?

**Comment by cruzach** [comment]
Hey @mileskrell - is this on all Android devices? Does the behavior still happen on simulators?

**Comment by mileskrell** [comment]
I'm totally new to both React Native and Expo, and since opening this issue I've realized that a lack of good support for Android's [configuration changes](https://developer.android.com/guide/topics/resources/runtime-changes) is just an issue with React Native more generally - it's not specific to Expo. So this probably wasn't the right place for me to open this issue.

But yes, I'm seeing this behavior on Appetize previews at https://snack.expo.io, as well as at least one other emulator (Pixel 2, API 27) and one physical device (Moto G6, API 26).

**Comment by christianjuth** [comment]
@cruzach I am seeing the same issue. I thought it might only be in the Expo client app, so I tried installing a standalone apk build on an emulator. App restarts as soon as you put it in split-screen. All previous state is lost.

#### Notes:
- Pixel 2 Emulator running android Q
- Testing on MacOS Mojave
- My app is using Expo SDK 34
- App was built on Expo server using `expo build:android` and installed using `adb install`
- I have not tried installing my Expo app through the Play Store. I will try this soon, but I'm guessing it won't make a difference.
- I have not had a chance to test this using a physical device

**Comment by cruzach** [comment]
@christianjuth have you tried a bare RN app? as Miles pointed out, this may not be an issue specific to Expo

**Comment by cruzach** [comment]
The answer to handling this situation properly is provided [here](https://github.com/facebook/react-native/issues/25040#issuecomment-515297669). To make those changes to `AndroidManifest.xml`, you'll ned to use the bare workflow, since you don't have access to that level of customization in the managed workflow
