### ISSUE TITLE
MediaLibrary doesn't return all audio files

### ISSUE THREAD

**Issue by Tenpeter** [expo/expo#4948]
### Environment

Expo CLI 2.21.2 environment info:
    System:
      OS: Linux 5.1 Fedora 30 (Workstation Edition) 30 (Workstation Edition)
      Shell: 5.0.7 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.9.0 - /usr/bin/npm
    npmGlobalPackages:
      expo-cli: 2.21.2

### Steps to Reproduce
see demo here https://snack.expo.io/SyPdeYObr

### Expected Behavior

return all audio files, stored on the device and external storage.

### Actual Behavior

return only 20 audio files

### Reproducible Demo

see demo here https://snack.expo.io/SyPdeYObr

**Comment by cruzach** [comment]
Hey @Tenpeter- you need to provide an integer for the `first` property of the `options` argument that you provide to `getAssetsAsync`. See the [docs](https://docs.expo.io/versions/latest/sdk/media-library/#medialibrarygetassetsasyncoptions) for more info.

Basically, just change your code to 
```
const media = await MediaLibrary.getAssetsAsync({
      mediaType: MediaLibrary.MediaType.audio,
      first: 40
    });
```

and you'll get 40 items returned.
