### ISSUE TITLE
 Does not show ads in apk

### ISSUE THREAD

**Issue by Laloww** [expo/expo#4949]
I am using expo to debug an application. In debug mode (expo start) advertising is correctly displayed

on when I build the application (expo build: android) advertising is not displayed

when using the test key, the advertisement works correctly in apk

checked the key. google admob it's active

Do I need to make some settings to display admob ads

I watched the documentation there described only about inserting the code into the program. I use the library expo-ads-admob

```
_openInterstitial = async () => {
    if(this.state.loaded){
      try {
        AdMobInterstitial.setAdUnitID('ca-app-pub-7150588601360327/9901080259');
        await AdMobInterstitial.requestAdAsync();
        await AdMobInterstitial.showAdAsync();
      } catch (error) {
      } finally {
        this.setState({ loaded: false });
      }
    }
  }
```

**Comment by cruzach** [comment]
Hey @Laloww - this is normal, it usually takes a few days for the ads to show in real builds, see [here](https://forums.expo.io/t/admob-is-not-showing-ads-on-real-device-after-build/21778/9?u=charliecruzan).
