### ISSUE TITLE
[expo-keep-awake] TypeError: api.caller is not a function

### ISSUE THREAD

**Issue by Pines-Cheng** [expo/expo#4952]
## 🐛 Bug Report

use `expo-keep-awake` under :
```js
import { activateKeepAwake, deactivateKeepAwake } from 'expo-keep-awake'
```
and iOS simulator will throw error:

```
error: bundling failed: TypeError: api.caller is not a function (While processing preset: "/Work/taro/packages/taro-rn/node_modules/babel-preset-expo/index.js")
```

click to jump to the corresponding code : 
```js
module.exports = function(api, options) {
  const isWeb = api.caller(isTargetWeb);

  if (isWeb) {
    return getWebConfig(options.web);
  }

  return getNativeConfig();
};
```

### Environment

```shell
  Expo CLI 2.20.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.8.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1
      react-native: 0.55.4 => 0.55.4
    npmGlobalPackages:
      expo-cli: 2.20.10
```

### Steps to Reproduce
already described

### Expected Behavior
can use this package normally

### Actual Behavior

![image](https://user-images.githubusercontent.com/9441951/61202134-467b0880-a719-11e9-8632-0cd0d254e5f8.png)

**Comment by AdamJNavarro** [comment]
Hey @Pines-Cheng,

`expo-keep-awake` does not have web compatibility yet. You can check compatibility via [Native Directory](https://www.native.directory/). We'll also be adding a note in our docs to avoid confusion.

Cheers,
Adam

**Comment by Pines-Cheng** [comment]
sorry , I still not know what you mean..

**Comment by tacnoman** [comment]
I made expo downgrade to `27.1.1` and worked for me.
