### ISSUE TITLE
android.adaptiveIcon.foregroundImage is not sized correctly

### ISSUE THREAD

**Issue by peterzernia** [expo/expo#4954]
### Environment

 Expo CLI 2.20.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.4

### Steps to Reproduce

Link to [app.json](https://github.com/peterzernia/wanderlist-native/blob/master/app.json) for the app that's causing issues.

Deploy an app on Google play store with adaptiveIcon settings:
`    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/icon_fg.png",
        "backgroundColor": "#2196f3"
      }`

### Expected Behavior

The foreground Icon should show the whole Icon on a blue background.
This is the icon:
![icon_fg](https://user-images.githubusercontent.com/43378846/61214652-c351b680-a708-11e9-99dd-e16d3ae82cb7.png)

### Actual Behavior

The foreground Icon is too large to fit completely in the icon on android:
![Screenshot_20190715-114405_2](https://user-images.githubusercontent.com/43378846/61214683-debcc180-a708-11e9-903e-8d5da317000e.png)

### Reproducible Demo

Not sure I can make a reproducible demo as I can only see the issue on the deployed app.

**Comment by cruzach** [comment]
Hi! Have you followed Android's [Adaptive Icon guidelines](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)? 

We also recommend that you use a 1024x1024 png file, leaving at least the outer 1/6 transparent on each side.

**Comment by peterzernia** [comment]
Am I allowed to use the .xml file created by Android Image Studio? I didn't see anything in the docs about what the filetype of foregroundImage should be
