### ISSUE TITLE
App crashing completely when loading a view with Google maps in iOS device only

### ISSUE THREAD

**Issue by georgiosd** [expo/expo#4955]
We just released a new feature that uses react-native-maps and it all works fine in Android and the iOS simulator.

However on iOS devices we get an instant app crash when we switch to the view with the maps, no error shown, no app restart, no sentry sent.

How do we resolve this??

expo: 31.0.6
expo-cli: 2.11.3
react: 16.5.0
react-native: sdk-32
app.json sdkVersion: 32

After upgrading to these, we still get the same problem:

expo: 33.0.0
expo-cli: 2.11.3
react: 16.8.3
react-native: sdk 33
app.json: 33

PS: apologies for the double post with the forums but we were supposed to release yesterday and after much trial and error there's been nothing

**Comment by cruzach** [comment]
Hey @georgiosd, sorry you're running into this! Hopefully we can figure out what's going on here quick to minimize the impact on your release

First- are you providing an API key for Google Maps? 
I suggest following along with the [Configuration docs](https://docs.expo.io/versions/latest/sdk/map-view/#configuration) for Mapview if you aren't

**Comment by georgiosd** [comment]
That was indeed the problem. It tricked us because it was working fine without a key on Android. Thank you.
