### ISSUE TITLE
Unable to resolve "./Google" from "node_modules/expo/build/ExpoLazy.js"

### ISSUE THREAD

**Issue by kirsantov** [expo/expo#4956]
### Environment

Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.0-rc.0 => 34.0.0-rc.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0

### Steps to Reproduce

update expo to 34.0.0-rc.0
expo start

### Expected Behavior
build

### Actual Behavior

Unable to resolve "./Google" from "node_modules/expo/build/ExpoLazy.js"
Failed building JavaScript bundle.

**Comment by cruzach** [comment]
Hey @kirsantov - 

SDK 34 is not released yet, so you shouldn't be able to upgrade to it.

Let me know if this occurs on an SDK 33 or below project, and I'll reopen the issue!

**Comment by kirsantov** [comment]
But how I can resolve problem from previous version? I can't build app  with this permission popup:
https://github.com/expo/expo/commit/97fc5275ba91fb56ea25829785d362ef8f64fb6d

**Comment by cruzach** [comment]
What was the problem, exactly?

**Comment by kirsantov** [comment]
Prevent dialog for scoped permissions from showing
https://github.com/expo/expo/pull/4839

**Comment by kirsantov** [comment]
And this https://github.com/expo/expo/issues/4680

**Comment by eggnukes** [comment]
Still error occurs for me after updating to SDK 34 following instructions in the [release guide](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319).

**Comment by callyb** [comment]
Me too

**Comment by cruzach** [comment]
Can you try `expo start -c`?

**Comment by callyb** [comment]
Tried that - good point, it solved the Google error but now I've got  another error: "fontFamily "FontAwesome" is not a system font and has not been loaded through Font.loadAsync." even though I've imported and used FA with "import {FontAwesome} from '@expo/vector-icons';" as stated in the docs...  I've given up and gone back to SDK 33 for now.

**Comment by cruzach** [comment]
That could be caused by a different issue (at least I've seen that before), or I would take a look at the fixes in [this issue](https://github.com/expo/expo/issues/5126)

Otherwise, share your code with me and I can take a look!

**Comment by callyb** [comment]
Gosh, I'm having real problems upgrading to v34 - I never had any problems I couldn't solve upgrading before but the latest error message I got after clearing the cache and updating all the expo-fonts as suggested in the other thread you quoted (and updating all the other expo packages I could) I'm still getting the Font.loadAsync error plus one about Firestore timestampInSnapshots as [referenced here](https://github.com/firebase/firebase-js-sdk/issues/1498).  Plus another error "[Unhandled promise rejection: ReferenceError: Can't find variable: Permissions]".  I've shared my app.js and package.json files with you through github - I don't know if you meant to share any of the rest of the code but it's my first big app & it's nearly done so I didn't really want to put all the files in!  Thank you - but unless you can suggest anything else I'm going to stay on v33 which is working great for me and just hope the next upgrade doesn't give me the same headaches!

**Comment by cruzach** [comment]
@callyb i was able to run your app.js (with some changes since I don't have access to the rest of your codebase) with no errors. I would try some of the updates that people said fixed this error message [here](https://github.com/expo/expo/issues/5100#issuecomment-516693003)


For the permissions error message, I would make sure you're importing it with `import * as Permissions from 'expo-permissions';`, other than that I can't say more about it since your app.js doesn't use Permissions so idk how you're using it. 

The Firestore error message I don't believe is related to the SDK 34 update. 

Hopefully some of this helped, sorry I don't have an explicit "fix this" for you

**Comment by callyb** [comment]
Thanks for your help @cruzach, I did manage to sort all the errors except the fontAwesome issue with suggestions from various github posts (the firestore error wasn't related to SDK 34 as you said) but I've tried everything on the link you referenced to fix FA and other posts referenced in that link and still get the same error.   I'll stick to 33 for now and watch the posts for more info as it seems I'm not the only one who can't get FA to work with SDK 34...& thanks for looking at my code.

**Comment by eggnukes** [comment]
What worked for me and got rid of all upgrade related errors was:

1. Delete node_modules folder.
2. **Delete package-lock.json (yarn.lock if you are using yarn instead of npm).**
3. Run npm install.
4. Run `expo start -c`.

Make sure you have latest Expo CLI version (`npm install -g expo-cli`) before you do this or you might have to do it all again.

**Comment by callyb** [comment]
Thank you @eggnukes but I'd already tried that - but Wow, finally!!  I've been keeping an eye & trying any solutions I could find - none worked - and finally this morning found this solution #5507 from @SteveAquino that worked - it's a workaround, and I still don't understand the problem, but at least I can use v35 now...!
