### ISSUE TITLE
Expo Client Hot Reload: Doesn't Register Saved Changes

### ISSUE THREAD

**Issue by AMSTKO** [expo/expo#4957]
Hi

I followed https://expo.io/learn but now I can't have the "hot reloading" feature.

Expo client config (with hot reloading enabled),

![image](https://user-images.githubusercontent.com/408968/61233856-d9c03800-a731-11e9-9872-6d46e4673d82.png)

I'm in "development" mode on Expo "server" on my Mac

I tried to modify the App.js file from the "blank" example,
We can see a message "hot loading..." on the bottom of the Android simulator, but nothing change

![expo_hotr](https://user-images.githubusercontent.com/408968/61233878-e0e74600-a731-11e9-9d4f-1f0254499980.gif)

>  ➜  ~ expo --version
> 2.21.2

> macOS Mojave 10.14.5

> Fresh install of Expo, iOS and Android simulators

**Comment by cruzach** [comment]
Hey @AMSTKO, that's weird, I just tested this on Android and iOS and hot reloading worked on both. Do you have a similar issue with live reloading?

Does your terminal show any messages when you save your changes?

**Comment by AMSTKO** [comment]
Live reloading work well! No problem with it

### Demo
Live reload on iPhone, Hot reload on Android,

![expo_hotr2](https://user-images.githubusercontent.com/408968/61239558-72a98000-a73f-11e9-895d-cbb04ba530eb.gif)

### Terminal

```
Finished building JavaScript bundle in 806ms.
Running application on iPhone X.
```

But nothing about Android since I manually reload the bundle

### Console from Debugger-ui from Android (http://localhost:19001/debugger-ui/)

We can see `&hot=false` in the bundleUrl

```
Running application "main" with appParams: {"initialProps":{"exp":{"initialUri":"exp://192.168.1.104:19000","manifest":{"iconUrl":"http://192.168.1.104:19001/assets/./assets/icon.png","version":"1.0.0","xde":true,"updates":{"fallbackToCacheTimeout":0},"sdkVersion":"33.0.0","platforms":["ios","android","web"],"hostUri":"192.168.1.104:19000","slug":"my-new-project","icon":"./assets/icon.png","loadedFromCache":false,"debuggerHost":"192.168.1.104:19001","splash":{"resizeMode":"contain","backgroundColor":"#ffffff","image":"./assets/splash.png","imageUrl":"http://192.168.1.104:19001/assets/./assets/splash.png"},"primaryColor":"#023C69","orientation":"portrait","isVerified":true,"env":{},"id":"@amstko/my-new-project","privacy":"public","bundleUrl":"http://192.168.1.104:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false","packagerOpts":{"dev":true,"lanType":"ip","hostType":"lan","minify":false,"urlRandomness":"j4-g2x"},"name":"testme","ios":{"supportsTablet":true},"developer":{"tool":"expo-cli","projectRoot":"/Users/amstko/Projects/trojob/mobile/my-new-project"},"mainModuleName":"node_modules/expo/AppEntry","logUrl":"http://192.168.1.104:19000/logs","assetBundlePatterns":["**/*"]},"shell":false}},"rootTag":41}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF```

**Comment by AMSTKO** [comment]
Also with Hot Reload mode both can display error 

![expo_hotr3](https://user-images.githubusercontent.com/408968/61240186-eac47580-a740-11e9-9f1f-f567132c64bd.gif)

**Comment by cruzach** [comment]
> We can see &hot=false in the bundleUrl

This is probably an unrelated bug, as I see the same on my end (but hot reloading works for me)

Could you run `expo diagnostics` and paste the output here? Maybe the difference lies in our environment setups? As both Android and iOS simulators work with hot reloading on my end

Also- does hot reloading work on your physical device?

**Comment by AMSTKO** [comment]
```
➜  ~ expo diagnostics

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.21.2
```

My first tests was with an physical iPhone 7 on iOS 13 public beta 2, live reload ok but hot reload broken like in simulator

**Comment by AMSTKO** [comment]
I tried to downgrade Node to 10.16 with a new install of Expo and blank project example,

```
➜  my-new-project git:(master) ✗ expo diagnostics /Users/amstko/Projects/my-new-project

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.21.2
```

**Comment by AMSTKO** [comment]
Test with a downgrade of expo-cli to 2.20.2 and Node 10.16, Hot Reload always fail

➜  my-new-project git:(master) ✗ expo diagnostics /Users/amstko/Projects/my-new-project
┌─────────────────────────────────────────────────────────────┐
│                                                             │
│   There is a new version of expo-cli available (2.21.2).    │
│   You are currently using expo-cli 2.20.2                   │
│   Run `npm install -g expo-cli` to get the latest version   │
│                                                             │
└─────────────────────────────────────────────────────────────┘

  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.20.2

**Comment by AMSTKO** [comment]
Another try, I downgrade my iOS simulator to iPhone 7 with iOS 11.4, back to expo-cli 2.21.2 and I tried the "blank with tabs" example project.

Hot reload always fail. Live reload and CMD+R always run well for update the bundle

```
➜  node_modules expo diagnostics /Users/amstko/Projects/my-new-project

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.21.2
```

<img width="544" alt="Screenshot 2019-07-16 at 11 44 51" src="https://user-images.githubusercontent.com/408968/61284390-243bc600-a7bf-11e9-979d-a6d4da8e3429.png">

<img width="544" alt="Screenshot 2019-07-16 at 11 42 58" src="https://user-images.githubusercontent.com/408968/61284260-e048c100-a7be-11e9-9cea-2c341cc4199c.png">

**Comment by AMSTKO** [comment]
I tried a full new install of my Mac with just Xcode, node 10.16, macOs 10.14.5, npm 6.9, expo-cli 2.21.2, Intellij Idea IDE

Hot Reload always not working

![gGS+9dPdTuSDgedYMygu+g](https://user-images.githubusercontent.com/408968/61296051-a89b4280-a7d9-11e9-9649-9a25af565014.jpg)

**Comment by cruzach** [comment]
Mine is:
```
 Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
```

Make sure you have Watchman installed -> https://docs.expo.io/versions/v33.0.0/introduction/installation/#watchman

**Comment by AMSTKO** [comment]
Thx, I have installed watchman, not installed before
Nothing change hot reloading doesn't work :/
I have created a new blank project, cleared the cache one time, reinstalled Expo Client in the simulator

```
/usr/local/bin/node v11.6.0
/usr/local/bin/watchman 4.9.0
/usr/local/bin/npm 6.5.0-next.0
```

**Comment by cruzach** [comment]
You could also try the fix [here](https://github.com/expo/expo/issues/828#issuecomment-339820319), seems to have worked for a few others. Also another fix [here](https://forums.expo.io/t/hot-reload-live-reload-manual-reload-none-of-this-is-working/3205/3?u=charliecruzan)

Basically, I don't think this is a bug with Expo. Unfortunately HMR (Hot Module Replacement) can be pretty finicky (if you Google your problem, a lot of others in the react-native sphere have had similar issues) ☹️

**Comment by arisferyanto** [comment]
@cruzach I have the same issue. Tried deleting yarn.lock, fresh install, still doesn't work. @AMSTKO any luck?

**Comment by AMSTKO** [comment]
It's not working, I just tried with the react native cli and I have the same issue
https://github.com/facebook/react-native/issues/18899#issuecomment-512197831

**Comment by arisferyanto** [comment]
Turns out hot reload doesn't support functional component (https://github.com/facebook/react-native/issues/10991) and the blank template created by expo-cli is using functional component. Changing to class component solved the issue for me. Hope this helps, @AMSTKO.

**Comment by AMSTKO** [comment]
OMG It was just that... thank you

**Comment by cruzach** [comment]
Thanks for the find @arisferyanto , looks like they're planning on [fixing this in 0.61](https://github.com/facebook/react-native/issues/10991#issuecomment-506881184)

**Comment by dacastro4** [comment]
Hey, @AMSTKO did it work using node v12? or v10? I don't have any functional components and I can't make it work

**Comment by stephentan** [comment]
Thanks @arisferyanto  You are right. 
However, I noticed that only the App.js needs to be using class.
The rest of the components can be in the form of functional component!

**Comment by mattirizarry** [comment]
I know this is bumping an issue from way back but I ran into this issue today and @stephentan's response fixed my issue. If you are using TS like I am just remove the `FC` from your main class and it should work okay.

**Comment by tslocke** [comment]
In case this of help to anyone else, this issue came up for me searching for a solution to the iOS simulator not picking up hot changes. The message at the bottom of the simulator screen would show, but nothing would change.

Physical phone was picking up changes no problem.

The fix for me was to delete the Expo app from the simulator phone, and then reinstall it by pressing i in the expo terminal window.

**Comment by Rijk** [comment]
Thanks @tslocke , this was the only way to get the Simulator to pick up code changes again. For some reason, it was stuck on a cached, old version of some files. I already tried restarting the bundler, and force closing and restarting the app, and disabling fast refresh. Uninstalling/reinstalling the app was the only thing that worked. This was on the latest Expo btw:

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/lib/node_modules/node/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/lib/node_modules/node/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.6

**Comment by annyh** [comment]
@Rijk I've been able to reproduce the issue running expo on Android. With the "Debug Remote JS" option the app gets an old version of the app. I ran `adb shell input keyevent 82` in my terminal window to bring up the menu to disable "Debug Remote JS", and got the latest.

**Comment by denniske** [comment]
I had to delete my browser cache to make the debugger forget about old version.

**Comment by chamberrr2809** [comment]
Thank you! you helped me a lot. I spent hours looking for a solution and this is the only one that works
