### ISSUE TITLE
Expo video doesn't fetch

### ISSUE THREAD

**Issue by zRelux** [expo/expo#4958]
## 🐛 Bug Report

I have a download link where a mp4 file gets downloaded. I want to use that download link as a streaming source for the Video component. The problem is that after some time the video component stops, and that is because it doesn't fetch after some time. I think it is because of the HTTP header but in the browser if I use the same link on a html 5 video it plays the video fully.
In the console I get: `Player error: java.net.ProtocolException: unexpected end of stream`
### Environment

  Expo CLI 2.21.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Users\Leo\AppData\Roaming\npm\yarn.CMD
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD

### Expected Behavior

Expo Video plays the video fully without breaking

### Reproducible Demo

https://snack.expo.io/@relux/arrogant-ramen

 If you look at the logs after some time the playableDurationMillis key doesn't get update and the app crashes

**Comment by cruzach** [comment]
Hey @zRelux - how long does the video usually have to play until the crash? And are you seeing it both on Android and iOS?

**Comment by zRelux** [comment]
The time is always the same and it's around one minute, after that I get the error. Regarding IOS i can only try in the snack, but it seams to work fine.

**Comment by zRelux** [comment]
Update: The issue seems to be happening only on Android since the Web and the IOS version in the snack work fine
