### ISSUE TITLE
Overlapping TouchableHighlight no longer works in Expo 33

### ISSUE THREAD

**Issue by sguha00** [expo/expo#4961]
### Environment

$ expo diagnostics

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.1.9 => 3.1.9 
      @storybook/react-native: ^4.1.18 => 4.1.18 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.10 
      react-navigation: ^3.9.1 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2

Target: iOS

### Steps to Reproduce

Check https://snack.expo.io/@carforce/lonely-cashew on a physical iOS device and observe that clicking on the `TouchableHighlight` that overlaps the `View` does not trigger the `onPress`. https://snack.expo.io/@carforce/lonely-cashew-32 with Expo 32 works as expected

### Expected Behavior

Expo 33 should behave the same as Expo 32 when it comes to overlapping `TouchableHightlight`s.

### Actual Behavior

The `onPress` isn't triggered in Expo 33 on the overlapping region. Overlapping `TouchableWithoutFeedback` still works as expected

### Reproducible Demo
Expo 33: https://snack.expo.io/@carforce/lonely-cashew
Expo 32: https://snack.expo.io/@carforce/lonely-cashew-32

**Comment by cruzach** [comment]
Hey @sguha00 - thanks for both the Snacks! I can confirm I'm seeing the difference in behavior

Have you tried making plain React Native projects and testing this? I'm curious to see if the underlying issue lies with Expo, **or** if it lies with upgrading to React Native 0.59.8 (which we did in SDK 33). SDK 32 was based on RN 0.57.1

**Comment by sguha00** [comment]
I'm actually seeing the opposite behavior on  an Android device (Pixel running the latest Android 9) - it doesn't work in Expo 32, but works in Expo 33

I haven't tried to replicate it on a plain RN project - can I create a snack or something similar without including expo?

**Comment by cruzach** [comment]
> can I create a snack or something similar without including expo?

Unfortunately, you can't do this in snack (that would be really convenient, though)
The simplest thing to do would be to make a bare Expo project ([see here for a brief explanation](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/) and [more in-depth here](https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331)). 

I just tried this on my end, and still see the same behavior (without any expo dependencies), so I believe this to be an upstream `react-native` issue. I'll wait for you to confirm before I close, though

**Comment by sguha00** [comment]
Yes, look like an upstream issue
