### ISSUE TITLE
How to Use Developer Certificate to Building Standalone Apps

### ISSUE THREAD

**Issue by lcfei** [expo/expo#4965]
How to Use Developer Certificate to Building Standalone Apps

**Comment by cruzach** [comment]
Hi!

Go ahead and take a look at our [docs](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/), we talk about app signing there. If you have any questions, best place to ask them is on the [Expo forums](https://forums.expo.io/), since we keep Github just for bug reports
