### ISSUE TITLE
BarcodeScanner is currently way slower than using Camera

### ISSUE THREAD

**Issue by Amirjab21** [expo/expo#4968]
Very simple issue -

BarcodeScanner takes a while to mount but using the Camera component from Expo is way faster.

**Comment by cruzach** [comment]
Hey @Amirjab21-

We provide an issue template to reduce the back and forth of asking for more information. Could you go ahead and provide:
- your environment info (just run `expo diagnostics`)
- whether this is happening on iOS, Android, or both
- a snack that reproduces the behavior (in this case, probably 2-> one that implements Camera, and the other implementing BarCodeScanner)
