### ISSUE TITLE
How can I disable blue screen error?

### ISSUE THREAD

**Issue by alirezadarvishi** [expo/expo#4969]
I have this blue screen when request network is filed. How can I disable or customize that?
When I use ' fetch ' and internet is disconnected I see this blue screen.

<img src="http://8upload.ir/uploads/f286852271.jpeg" width="200px">

**Comment by cruzach** [comment]
This is currently an [open issue](https://github.com/expo/expo/issues/4230) (may be included in SDK 35), so I'm going to close this since it's a duplicate.
