### ISSUE TITLE
Standalone build does not run on Android

### ISSUE THREAD

**Issue by skyride99** [expo/expo#497]
Using the standalone build from this link:
https://docs.expo.io/versions/latest/guides/building-standalone-apps.html

If I run the apk on the phone I get an error msg 'Something Went Wrong'

And then the list of errors
![screenshot_20170814-211416](https://user-images.githubusercontent.com/3801142/29273312-68ad4bd0-8136-11e7-8b84-0c6c8a02778c.png)

**Comment by skevy** [comment]
Hi there @skyride99. 

I presume your app has no issues when running in the Expo client normally?

**Comment by skyride99** [comment]
Yes its running on the Expo Client fine.

exp.json
{
  "name": "Mietnomaden",
  "description": "The app to find the best renters.",
  "slug": "report-abuser-app",
  "privacy": "public",
  "sdkVersion": "14.0.0",
  "version": "1.0.0",
  "orientation": "portrait",
  "primaryColor": "#cccccc",
  "icon": "./assets/icons/app-icon.png",
  "notification": {
    "icon": "./assets/icons/notification-icon.png",
    "color": "#000000"
  },
  "loading": {
    "icon": "./assets/icons/loading-icon.png",
    "hideExponentText": false
  },
  "packagerOpts": {
    "assetExts": ["ttf"]
  },
  "ios": {
    "supportsTablet": true
  },
    "android": {
      "package": "com.makeurofferph.apartment"
    }
}

**Comment by skyride99** [comment]
That is exp.json  not app.json.

**Comment by skyride99** [comment]
When running from expo xde with an actual android phone, running marshmallow I get 

Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://88-bjw.skyride99.muo-apartment.exp.direct:80 flg=0x10000000 }

ios Runs fine...

**Comment by skyride99** [comment]
Fixed by uninstalling Node NPM and reinstalling.

**Comment by ProteanDev** [comment]
Still having this issue
