### ISSUE TITLE
Incorrect error message in SDK 33.00.0 when using LocalAuthentication in Expo Client

### ISSUE THREAD

**Issue by vernondegoede** [expo/expo#4970]
## 🐛 Bug Report

I tried to launch FaceID using `LocalAuthentication`, but got an incorrect error message. This error message was more clear in SDK 32.0.0.

### Environment

```
Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.17.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.23
      @types/react-native: ^0.57.60 => 0.57.65
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 2.21.2
```

### Steps to Reproduce

I tried to launch `LocalAuthentication` from within the Expo Client in SDK 33.0.0 (on iOS 13 and iOS 12), and got the following error message:

```
FaceID is available but has not been configured. To enable FaceID, provide `NSFaceIDUsageDescription`.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- ... 17 more stack frames from framework internals
```

I actually set the description in my `app.json`. It looks like this: https://gist.github.com/vernondegoede/81203b3a70adff097dbe57c027545a8f

After some digging into the code, I found out that FaceID simply does not work in Expo Client. I found this out by switching back to SDK 32.0.0. With a similar `app.json`, I got the following error message:

```
Running application on iPhone van Vernon.
FaceID is not available in Expo Client. You can use it in a standalone Expo app by providing `NSFaceIDUsageDescription`.
```

This error message would have saved me a couple of hours :-)

### Expected Behavior

I would expect this error not to show up. I would instead expect a warning which indicates that FaceID would normally work, but simply is not available in the Expo Client (which was the case in the previous SDK).

### Actual Behavior

I got a confusing error message, which points developers in the wrong direction.

**Comment by KevinYingWeiYeh** [comment]
@cruzach Did you only have an error message or included faceID feature on your iOS device was not work as well? Mine situation is the LocalAuthentication went to password prompt screen. Is it the same as yours?

**Comment by vernondegoede** [comment]
I did indeed not manage to get the FaceID functionality.

**Comment by cruzach** [comment]
@KevinYingWeiYeh I don't understand your question

I'm adding a warning that FaceID is not available for apps being run inside the Expo Client. For FaceID devices: when your prompt for `LocalAuthentication. authenticateAsync` **in the Expo Client**, it will automatically prompt for a passcode instead

**Comment by KevinYingWeiYeh** [comment]
@cruzach Sorry for confusing you

I have the same issue as you have, and I have the error messages on both sides terminal and Expo Client you have too

**Comment by IsaacWIvins** [comment]
@cruzach is there a reason as to why apps being run in Expo Client have a passcode instead? I'm using expoKit so I just built it through XCode for now, just curious

**Comment by IsaacWIvins** [comment]
Piggie backing on this thread because getting FaceID and TouchID set up was more annoying than anticipated. I'm working on a detached application using Expo SDK 33.

I was able to get Face ID and Touch ID working after adding
`<key>NSFaceIDUsageDescription</key>
<string>Enabling Face ID allows you quick and secure access to your account.</string>`
to my info.plist

We upgraded from SDK 30 a couple of weeks ago and this must have slipped through the cracks.

**Comment by cruzach** [comment]
This has been resolved- see [here](https://github.com/expo/expo/blob/9e39fced75da9b43eb59a8deb18735c9824efcac/ios/Exponent/Versioned/Core/UniversalModules/EXScopedLocalAuthentication.m#L35) 👍

**Comment by activebiz** [comment]
I know its been closed but how to fix this if you are not using expo client? For just react-native cli. I am getting the errros `FaceID is available but has not been configured. To enable FaceID, provide `NSFaceIDUsageDescription`. even after using 
```  "ios": {
    "bundleIdentifier": "uk.co.rac.myracnative",
    "infoPlist": {
      "NSFaceIDUsageDescription": "We'll use Face ID or Touch ID to secure your payment details."
    }
  }
```

**Comment by haseebeqx** [comment]
@activebiz you have to add this in info.plist
```
<key>NSFaceIDUsageDescription</key>
<string>$(PRODUCT_NAME) requires FaceID access to allows you quick and secure access.</string>
```
