### ISSUE TITLE
iOS buildNumber config option docs unclear

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#498]
Documentation for `ios.buildNumber` is unclear and easily confused with Android versionCode

```
"buildNumber": {
  "description": "Build number for your iOS standalone app.",
  "type": "string",
  "pattern": "^[0-9]+$"
},
```

Additionally, `buildNumber` currently supports what I believe are invalid values -- eg:" "000001" as a build number.

`buildNumber` corresponds to `CFBundleVersion`:

```
dev/xdl/src/detach/IosShellApp.js
205:      let buildNumber =
206:        manifest.ios && manifest.ios.buildNumber
207:          ? manifest.ios.buildNumber
210:      config.CFBundleVersion = buildNumber;
```

> CFBundleVersion (String - iOS, macOS) specifies the build version number of the bundle, which identifies an iteration (released or unreleased) of the bundle.

> The build version number **should be a string comprised of three non-negative, period-separated integers with the first integer being greater than zero—for example, 3.1.2**. The string should only contain numeric (0-9) and period (.) characters. Leading zeros are truncated from each integer and will be ignored (that is, 1.02.3 is equivalent to 1.2.3). The meaning of each element is as follows:

> The first number represents the most recent major release and is limited to a maximum length of four digits.
> The second number represents the most recent significant revision and is limited to a maximum length of two digits.
> The third number represents the most recent minor bug fix and is limited to a maximum length of two digits.
> If the value of the third number is 0, you can omit it and the second period.

> While developing a new version of your app, you can include a suffix after the number that is being updated; for example 3.1.3a1. The character in the suffix represents the stage of development for the new version. For example, you can represent development, alpha, beta, and final candidate, by d, a, b, and fc. The final number in the suffix is the build version, which cannot be 0 and cannot exceed 255. When you release the new version of your app, remove the suffix.

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364

**Comment by dikaiosune** [comment]
Fixed in https://github.com/expo/expo-docs/commit/2867e141f5020a08aba280fe3cb7add3dcc18fb5, when docs are deployed it'll be live.
