### ISSUE TITLE
Sqlite DB data cleared on App update From SDK 32 to SDK 33

### ISSUE THREAD

**Issue by onizam95** [expo/expo#4980]
## 🐛 Bug Report
When a standalone build(EXPO SDK 32) on android   is updated with new apk which is using EXPO SDK 33 the sqlite database data is cleared. 
### Environment
Android: 8.0.1
expo: 33.0.0
react-native : 0.59 ("https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz")

Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.9.1 
    npmGlobalPackages:
      expo-cli: 2.21.2

Android Standalone build
on Huawei Mate 10 Lite Emui 8.1 Android 8.0.1
### Steps to Reproduce
Install a build using expo sdk 32
update this app with a build with expo sdk 33 db data is cleared

### Expected Behavior
 The data should be persisted

### Actual Behavior
The data is cleared

**Comment by AdamJNavarro** [comment]
Hey @onizam95,

Just want to be certain, did you change the expo account or slug value for the project between the SDK upgrades?

Cheers,
Adam

**Comment by onizam95** [comment]
hi @AdamJNavarro  no i didn't, I think it is related to this [issue](https://github.com/expo/expo/issues/4537) please let me know if you find anything as well. because this is certainly breaking the app 
Thanks

**Comment by onizam95** [comment]
@AdamJNavarro 
any update ? 
i am trying to move the db to the new location but its not working here's the code.
async moveDB() {
        fromDirectory = `${FileSystem.documentDirectory}ExperienceData/%2540owais.nizam%252FReferralAppProduction/SQLite`;
        toDirectory = `${FileSystem.documentDirectory}SQLite`;
        let [fromDirectoryInfo,toDirectoryInfo] = await Promise.all([FileSystem.getInfoAsync(fromDirectory, {}), FileSystem.getInfoAsync(toDirectory, {})])
        // fromDirectoryInfo = await FileSystem.getInfoAsync(fromDirectory, {});

        // toDirectoryInfo = await FileSystem.getInfoAsync(toDirectory, {});

        console.log("================")
        console.log(fromDirectory)
        console.log("================")

        console.log(toDirectory)
        console.log("================")

        console.log(fromDirectoryInfo)
        console.log("================")

        console.log(toDirectoryInfo)

        if (!fromDirectoryInfo || !fromDirectoryInfo.exists) return; // old directory must exist
        if (toDirectoryInfo && toDirectoryInfo.exists) return; // new directory must not exist
        console.log("================")

        console.log("here for the update")
        try {
           await  FileSystem.copyAsync, {
                from: fromDirectory,
                to: toDirectory,
            };
        } catch (e) {
            console.log(e + "here")
        }
    }

**Comment by thomfre** [comment]
I have the exact same issue in my app. Data is just gone after upgrade from SDK 32 to SDK 33.

**Comment by onizam95** [comment]
@thomfre  please refer to this [issue](https://github.com/expo/expo/issues/4537) and read the comments.  its shortsightedness on their(expo) side.
thanks.

**Comment by thomfre** [comment]
Thank you, @onizam95! Managed to get everything back by moving the database file from the old to the new directory.

**Comment by cruzach** [comment]
Hey everyone, really sorry about this issue 😦 

as mentioned [here](https://github.com/expo/expo/issues/4537#issuecomment-546348079), we are working on the fix for this. Since this issue is due to some files not being migrated right, I'm going to close this so and we will keep track in the linked issue 4537
