### ISSUE TITLE
GoogleSignIn.isSignedInAsync is not working

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#4981]
I am using sdk version 32 also have checked it with sdk version 33 but not working at all.
its always  giving  an error **There is some Async operation is still in pending and return no data**

**Comment by AdamJNavarro** [comment]
Hey @reactexcel,

Would you mind making a [forum post](https://forums.expo.io/) for this and on that post, sharing the relevant code that this error is popping up from? We try to reserve Github issues for cases that have a reproducible example.

Cheers,
Adam
