### ISSUE TITLE
ExpoKit + react-native-firebase

### ISSUE THREAD

**Issue by moxorama** [expo/expo#4985]
### Environment

 Expo CLI 2.20.11 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.21.2

### Steps to Reproduce

1) Eject to ExpoKit
2) yarn add react-native-firebase@5.5.5 package
3) Modify grade scripts as recommended.
### Expected Behavior

I should be able to build app with firebase support

### Actual Behavior

I'm getting this log

```
  Dependency failing: com.google.firebase:firebase-messaging:17.4.0 -> com.google.firebase:firebase-iid@[17.1.0], but fire
  base-iid version was 17.1.2.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'android_conflict' depends on project 'app' which depends onto com.google.firebase:firebase-core@16.0.9
  -- Project 'android_conflict' depends on project 'app' which depends onto com.google.firebase:firebase-analytics@16.5.0
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-analytics@16.4.
  0
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-perf@16.2.4
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-core@16.0.8
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-invites@16.1.1
  -- Project 'android_conflict' depends on project 'app' which depends onto host.exp.exponent:expoview@33.0.0
  -- Project 'android_conflict' depends on project 'expo' which depends onto com.google.firebase:firebase-measurement-conn
  ector-impl@17.0.1
  -- Project 'android_conflict' depends on project 'app' which depends onto com.google.android.gms:play-services-measureme
  nt-api@16.5.0
  -- Project 'android_conflict' depends on project 'expo' which depends onto com.segment.analytics.android.integrations:fi
  rebase@1.2.0
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-ads@15.0.1
  -- Project 'android_conflict' depends on project 'expo' which depends onto com.google.firebase:firebase-analytics@16.0.3
  -- Project 'android_conflict' depends on project 'expo' which depends onto com.google.firebase:firebase-core@16.0.3
  -- Project 'android_conflict' depends on project 'expo' which depends onto com.google.firebase:firebase-analytics-impl@1
  6.2.1
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-config@16.4.1
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-messaging@17.5.
  0
  -- Project 'android_conflict' depends on project 'app' which depends onto com.google.firebase:firebase-messaging@17.4.0
  -- Project 'android_conflict' depends on project 'expo' which depends onto com.google.firebase:firebase-iid@16.0.0
  -- Project 'android_conflict' depends on project 'react' which depends onto com.google.firebase:firebase-functions@16.3.
  0
  -- Project 'android_conflict' depends on project 'expo' which depends onto com.google.android.gms:play-services-measurem
  ent-api@16.0.1
  -- Project 'android_conflict' depends on project 'app' which depends onto com.google.firebase:firebase-iid@17.1.2
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :android_conflict:assembleDebug t
  o see the dependency paths to the artifact. This error message came from the google-services Gradle plugin, report issue
  s at https://github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false
   }" to your build.gradle file.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.1.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.google.firebase:firebase-messaging:17.4.0 -> com.google.firebase:firebase-iid@[17.1.0], but fire
  base-iid version was 17.1.2.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-iid@17.1.2
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@17.4.0
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-config@16.4.1
  -- Project 'app' depends on project 'expo' which depends onto com.google.firebase:firebase-iid@16.0.0
  -- Project 'app' depends on project 'expo' which depends onto com.google.firebase:firebase-measurement-connector-impl@17
  .0.1
  -- Project 'app' depends on project 'expo' which depends onto com.segment.analytics.android.integrations:firebase@1.2.0
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@16.5.0
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-analytics@16.4.0
  -- Project 'app' depends on project 'expo' which depends onto com.google.android.gms:play-services-measurement-api@16.0.
  1
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-perf@16.2.4
  -- Project 'app' depends onto com.google.firebase:firebase-core@16.0.9
  -- Project 'app' depends on project 'expo' which depends onto com.google.firebase:firebase-analytics-impl@16.2.1
  -- Project 'app' depends on project 'expo' which depends onto com.google.firebase:firebase-core@16.0.3
  -- Project 'app' depends onto host.exp.exponent:expoview@33.0.0
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-invites@16.1.1
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-ads@15.0.1
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-messaging@17.5.0
  -- Project 'app' depends on project 'expo' which depends onto com.google.firebase:firebase-analytics@16.0.3
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@16.5.0
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-core@16.0.8
  -- Project 'app' depends on project 'react' which depends onto com.google.firebase:firebase-functions@16.3.0
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.
```

I've found that In node_modules/expokit/maven/host/exp/exponent/expoview/33.0.0 has this dependencies

```
    <dependency org="com.google.firebase" name="firebase-core" rev="16.0.7" conf="api-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-messaging" rev="17.4.0" conf="api-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-core" rev="16.0.7" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-analytics" rev="16.3.0" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-analytics-impl" rev="16.3.0" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-common" rev="16.0.3" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-iid" rev="17.1.0" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-iid-interop" rev="16.0.1" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-measurement-connector-impl" rev="17.0.5" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-measurement-connector" rev="17.0.1" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
    <dependency org="com.google.firebase" name="firebase-messaging" rev="17.4.0" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
```

So maybe they should be removed? Or may be we should have official way to use this packages in ExpoKit projects?

**Comment by brentvatne** [comment]
Hello!

You are likely to have a bad time using react-native-firebase with ExpoKit. The direction that we are moving with for ejected projects is called the bare workflow.

Here's some information on the differences from a change to the documentation that's about to land:

## Bare workflow

This is our way of describing the workflow where you use some of the Expo tools in a vanilla React Native app. Unlike in the managed workflow where you don't touch the underlying native code directly, in this workflow the developer has complete control, along with the complexity that comes with that. You can use most APIs in the Expo SDK. Much of the Expo documentation will not apply to building your app if you use this workflow, instead you can refer to tutorials and guides that are oriented towards native iOS and Android apps and React Native.

### What about ExpoKit?

ExpoKit is another way to use Expo tools in a vanilla React Native app. The problem with ExpoKit is it is, compared to the "bare workflow", very monolithic &mdash; you essentially include the entire runtime from the Expo "managed workflow" in your app, rather than only the pieces of it that you want. Developers building a React Native app couldn't just pull in one of the Expo SDK dependencies, it's all or nothing. We have found that this has been difficult for developers to work with for a variety of reasons, and so ExpoKit is on a deprecation path. It will be continued to be supported for at least one SDK release after the Updates API is available for all vanilla React Native apps.

<hr />

The reason why you're running into the issues that you are facing is that ExpoKit is monolithic and pulls in a bunch of dependencies that you're not using and react-native-firebase also includes some of those dependencies but with incompatible versions. I'd suggest using the "bare" workflow instead of ExpoKit, but for now we don't support OTA updates there. We're working on that and should have support for it soon. We don't have a well documented migration path from ExpoKit right now, it'll probably require you to initialize a new project using `expo init` and selecting the "bare" option, then porting over your project to that new one (or the reverse would work too, depending on your calculus for what would be easier/harder).

**Comment by moxorama** [comment]
Thank you for answer.

I've found workaround with manual setting versions of Firebase libraries that matches ExpoKit, and still be on ExpoKit until libraries like OTA will be extracted.

**Comment by rogerlopz** [comment]
Hi @moxorama Could you explain in more detail how did you implement firebase with expokit? I have setup everything as the react-native-firebase documentation say, i have an FCM token but i cannot receive a test notification.

@brentvatne We need to implement firebase into our project, thats why we ejected from expo. Do you recommend holding on until the expo sdk 34 is released? Would the sdk 34 help us integrate firebase easily?

**Comment by brentvatne** [comment]
SDK 34 does not do anything in particular to help you integrate Firebase. We will be adding the ability to eject to a "bare" project rather than ExpoKit, and "bare" projects play more nicely with third party libs, so to the extent that this will help you it may be useful.

**Comment by rogerlopz** [comment]
I get it now, thanks. It seems that waiting for expo 34 may help. Thanks!

**Comment by moxorama** [comment]
> Hi @moxorama Could you explain in more detail how did you implement firebase with expokit? I have setup everything as the react-native-firebase documentation say, i have an FCM token but i cannot receive a test notification.
> 
> @brentvatne We need to implement firebase into our project, thats why we ejected from expo. Do you recommend holding on until the expo sdk 34 is released? Would the sdk 34 help us integrate firebase easily?

https://github.com/moxorama/expokit-firebase

**Comment by dineshmatta** [comment]
@moxorama 

Thanks for sharing your Github profile, your changes worked for me as I was on the same setup.


@brentvatne 

So does this mean in the future we will only have bare workflow available if we eject our Expo app? We recently started our project with Expo and after some time we realised we needed native module support so we ejected with Expokit, but after your comment, it looks like Expokit will not be maintained in the future and if that is the case we will have to do the eject again and select the other option

**Comment by cruzach** [comment]
Expokit is no longer supported, and we encourage anyone on Expokit to move to the bare workflow. Whttps://blog.expo.io/time-to-start-using-expos-bare-workflow-expokit-now-deprecated-d6052890c18be have a guide for that here-
