### ISSUE TITLE
Calendar.getCalendarsAsync error on Android

### ISSUE THREAD

**Issue by AppleCkp** [expo/expo#4991]
### Environment- Android

 /** Gets an array of calendar objects with details about the different calendars stored on the device. */
    function getCalendarsAsync(
        /** (iOS only) Not required, but if defined, filters the returned calendars to a specific entity type.  */
        entityType?: EntityTypes
    ): Promise<Calendar[]>; 
 

### Steps to Reproduce
 I have encounter same issue as #1390 and i have checked the issue for this status is pending. May I know have any update for the issue?

Besides, when i click on the expo  function getCalendarsAsync,  it is stated only IOS is applicable as above.

May I know how can i get list of calendars on android phone?

### Expected Behavior
 Able to return list of calendar as Ios

### Actual Behavior
  List of calendars is not returned. No response return.

Thanks, 
Apple

**Comment by cruzach** [comment]
Hey @AppleCkp - are you asking for permission first via `Permissions.askAsync(Permissions.CALENDAR)`? That's required before reading/writing to the device's calendar. 

I put together [this snack](https://snack.expo.io/@charliecruzan/calendarexample) where it seems to work fine on my iOS device. If it doesn't work for you, please provide the device details

**Comment by AppleCkp** [comment]
Hi @cruzach , 

Thank for helping. I was tested in android emulator and the android emulator is not connected to google server.

However, i did get the list of calendar if i test in real android device.

Thanks,
Apple
