### ISSUE TITLE
FileSystem.getInfoAsync on IOS throw error "ph://...' isn't readable" 

### ISSUE THREAD

**Issue by AramArakelyan22** [expo/expo#4995]
Environment:
OS: IOS 10.14.4,
Node: 10.15.3,
npm: 6.4.1

Packages:
expo: 33.0.0,
react: 16.8.3,
react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz

Device:
iphone Xr, IOS 12.2

Steps to Reproduce
code:

try {
FileSystem.getInfoAsync(url);
} catch(e) {
console.log(error.message);
}

output: File 'ph://1724924E-9632-492E-B4E1-8DB6C818FF5B/L0/001' isn't readable.
permissions CAMERA_ROLL granted.
It reproduce only on IOS, on Android it works fine.

How can i solve this problem?

**Comment by cruzach** [comment]
Hey @AramArakelyan22 - could you provide a snack that reproduces this issue?

**Comment by bluedaniel** [comment]
I'm also having this issue, here is a snack that reproduces it.

https://snack.expo.io/By5ImfRZH

Ultimately I'm trying to convert the image to Base64.

**Comment by cruzach** [comment]
Hm..I just tested that snack on my iPhone 7 and it worked without any problems. What device are you using to test?

**Comment by bluedaniel** [comment]
An iPad Pro, the simulator and device.

Are you sure it works? In the demo, when you click on an image then FileSystem will error. It shows that way in the online snack I posted above

**Comment by cruzach** [comment]
Oops, sorry I made a mistake. You're right, I'm getting the same error

**Comment by brian1959** [comment]
Any ideas how to fix this?  I am using SDK33 and having the same problem.

**Comment by Sford4** [comment]
Same problem, SDK 33, please let me know if we find a solution!

**Comment by allankikkas** [comment]
Still broken in SDK 34

**Comment by allankikkas** [comment]
This also happens in published builds in testflight, not just in simulator.

**Comment by allankikkas** [comment]
@sjchmiela does it make camera roll files accessible using Filesystem. readAsStringAsync ? Also documentation probably should be updated regarding receiving null in uri, not inputted uri as stated in docs.

**Comment by peterkuiper** [comment]
@sjchmiela I know this issue is closed, but how can we get this fix? I have tried patching `expo-file-system` (in node_modules) manually but it still doesn't work so I'm not sure where this patch needs to be applied. I'm also curious where files like these `ios/versioned-react-native/ABI34_0_0/EXFileSystem/ABI34_0_0EXFileSystem/ABI34_0_0EXFileSystem.m` end up.

**Comment by sjchmiela** [comment]
`ABIXX_X_X` files are Expo client-specific files allowing you to run experiences in multiple SDK versions side by side. To patch `EXFilesystem`, you'd need to edit `node_modules/expo-file-system/ios/EXFileSystem/…` files according to [this](https://github.com/expo/expo/commit/998eee6c441608cd906ed97d73cc56cecb65b480#diff-c404baca63279481045007b855a798ce) and [this](https://github.com/expo/expo/commit/998eee6c441608cd906ed97d73cc56cecb65b480#diff-72367532d11c69bb33704ea5ff835c8f) diff. 🙂

**Comment by MahmoudMH** [comment]
> `ABIXX_X_X` files are Expo client-specific files allowing you to run experiences in multiple SDK versions side by side. To patch `EXFilesystem`, you'd need to edit `node_modules/expo-file-system/ios/EXFileSystem/…` files according to [this](https://github.com/expo/expo/commit/998eee6c441608cd906ed97d73cc56cecb65b480#diff-c404baca63279481045007b855a798ce) and [this](https://github.com/expo/expo/commit/998eee6c441608cd906ed97d73cc56cecb65b480#diff-72367532d11c69bb33704ea5ff835c8f) diff. 🙂

I made these changes but still the same error.

**Comment by sjchmiela** [comment]
Did you do them on an ejected project? Since these are in native code, you'll need to edit native code, i. e. also rebuild native code (or wait for native code update coming with SDK35-compatible Expo client).

**Comment by MahmoudMH** [comment]
I did not, I was trying to edit on node_modules directly and rebuild the bundle.
I will try to make it once I eject Expo.

Thanks @sjchmiela
