### ISSUE TITLE
Its not redirecting to mobile app after Google login, instead it goes to google.com

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#4996]
Google redirection is working fine in development that is on localhost server, 
and for that i red in expo document to user package name as **host.exp.exponent** in google console
but for production it stopped working as got errro **redirect_uri mismacth**  in production mode so i just changed package name in google console as its in app.json so its working now
but **not redirecting back to app instead it goes to google.com**.
Thanks in advance.

**Comment by cruzach** [comment]
Hey @reactexcel ,

Please follow the issue template, because without all the information it asks for it makes it very difficult to solve your problem.

I'm not sure if you're using [GoogleSignIn](https://docs.expo.io/versions/latest/sdk/google-sign-in/) or [Google](https://docs.expo.io/versions/latest/sdk/google/) (which had a fix merged recently for this exact issue -> see [here](https://github.com/expo/expo/pull/4904))

We'll be happy to help troubleshoot once we get everything we need 👍

**Comment by reactexcel** [comment]
Thanks for the reply @cruzach 
I am Google _https://docs.expo.io/versions/latest/sdk/google/_
Here is my code 

try {
      const result = await Google.logInAsync({
        androidClientId:"xxxxxxx",
        scopes: ['profile', 'email'],
        redirectUrl:redirectUrl
      });
      console.log(result);
    } catch(e) {
      console.log({e});
    }

Its working perfectly in dev mode as i am using package in google console that is **host.exp.exponent** but when checked it in prod(build) then got an redirect_uri_mosmatch so i change package name as in may app.json file then its is allowing user to login but after login it stay there for a while and goes to google.com.
Please help :)
Thank you

**Comment by cruzach** [comment]
Ah okay, so this is the same issue as #4655, which was solved in [PR 4904](https://github.com/expo/expo/pull/4904). Unfortunately, you won't see the fix until the next SDK release (which is coming **very** soon), but you **can** make those same changes to your `node_modules` folder, OR pass in `redirectUrl` that is constructed the same way it is in the PR (`${AppAuth.OAuthRedirect}:/oauth2redirect/google`)

**Comment by reactexcel** [comment]
still its not  working 
here is my code :-

try {
      const result = await Google.logInAsync({
        androidClientId:"xxxx",
        scopes: ['profile', 'email'],
        redirectUrl:`${AppAuth.OAuthRedirect}:/oauth2redirect/google`
      });
      console.log(result);
    } catch(e) {
      console.log({e});
    }

and one more question , what should be the package name in production mode?
As now i am using **host.exp.exponent**  for dev mode and **com.xxxx**(as it is in app.json) so is it right?

**Comment by DonGabo** [comment]
This fix worked only on android. On iOS I'm still being redirected to Google after the login.
I'm on expo  v33. Any idea why this could be happening?

**Comment by cruzach** [comment]
@DonGabo could you open a separate bug report for that?
