### ISSUE TITLE
SecureStore fails silently in Node environment (like tests)

### ISSUE THREAD

**Issue by bugeats** [expo/expo#5007]
### Environment

If you say so...

    > expo diagnostics 
    Cannot read property '1' of null
    Set EXPO_DEBUG=true in your env to view the stack trace.

The above is unrelated brokenness. 

### Steps to Reproduce

Pseudo test code:

```javascript
await SecureStore.setItemAsync('MAGIC', 'BEANS');
const got = await SecureStore.getItemAsync('MAGIC');
assert(got === 'BEANS'); // <-- fails with `got` as `undefined`
```

### Expected Behavior

SecureStore should either:

1. Provide a compatibility layer that persists data in the Node (or other) environment

or

2. Throw an exception if trying to write data in an unsupported environment

### Actual Behavior

_silent failure_

**Comment by ide** [comment]
`setItemAsync` already does:

```
  if (!ExpoSecureStore.setValueWithKeyAsync) {
    throw new UnavailabilityError('SecureStore', 'setItemAsync');
  }
```

Could you look into why this isn't running in Node (which isn't something we plan to support anytime soon)?

**Comment by ide** [comment]
Additionally, for tests I'd recommend mocking out SecureStore (eventually we'd like to ship Jest mocks with each module when it makes sense, but need to do some research into whether that's even possible).

**Comment by bugeats** [comment]
So I sat down to try and write an actual test case for this issue using a blank project from `expo init`. I am unable to import SecureStore into my jest test case due to the following error:

    > jest ./secure-storage.test.js

    FAIL  ./secure-storage.test.js
      ● Test suite failed to run

        /tmp/expo-fix/expo-fix/node_modules/expo/build/Expo.fx.js:1
        ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import './environment/validate.fx';
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^

        SyntaxError: Unexpected string

          at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
          at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
          at Object.<anonymous> (node_modules/expo/src/Expo.ts:1:1)

If importing SecureStore into a test case from a fresh expo project (with default babel config) doesn't work, then we have bigger problems. I'm going to have to postpone my work on this until I have some more time.

**Comment by bugeats** [comment]
I am however app to run tests from my established project. 

The below fails:

```javascript
import { NativeModulesProxy } from '@unimodules/core';

test('feature check for native secure store', async () => {
  expect(
    !!NativeModulesProxy.ExpoSecureStore.setValueWithKeyAsync,
  ).toBe(false);
});
```

So this check is going to pass in the test environment:

```javascript
 if (!ExpoSecureStore.setValueWithKeyAsync) {
    throw new UnavailabilityError('SecureStore', 'setItemAsync');
  }
```

In this test environment `NativeModulesProxy.ExpoSecureStore.setValueWithKeyAsync` is just a reference to a function called `mockConstructor`, which is not a falsey value.

**Comment by ide** [comment]
It looks like babel-jest isn't loading the expected Babel config, not sure why that is happening.

> In this test environment NativeModulesProxy.ExpoSecureStore.setValueWithKeyAsync is just a reference to a function called mockConstructor, which is not a falsey value.

This explains what's going on -- in the test environment, there are Jest mocks for all native methods. The Jest mocks are just `jest.fn(async () => {})` since they are dumb mocks. I suppose we could change them to be
```
jest.fn(async () => {
  throw new Error(`Called a mocked platform method from a test. Mock one of the methods in the call stack at the appropriate level of abstraction for your test unit.`);
});
```

We'll have to think about this more. It'd require all tests that call these mocks to provide their own mocks, which might be the correct thing to do. For instance, in your tests, you'd mock out `expo-secure-store` with methods that do whatever is right for your tests.

Aside: `Constants.isDevice` is `true` because the mock value was generated from a real device. The code is not running in a simulator either, though, so the value of the field is undefined and if you need to control it you should mock it explicitly.
