### ISSUE TITLE
[android] Calendar.deleteEventAsync unable delete event created and the app crashed 

### ISSUE THREAD

**Issue by AppleCkp** [expo/expo#5010]
### Steps to Reproduce

1) Get Calendar permission
2) Create calendarId
3) Create eventId using calendarId
4) Delete event using the eventId created(Failed)

### Expected Behavior

Event is successfully deleted in calendar and without app crash.
However, i able to update event with the eventId.

### Actual Behavior

Event in calendar unsuccessfully deleted and the app crash after call the delete event function without return and error message.

### Reproducible Demo

Here is my snack :
https://snack.expo.io/@appleckp/0a1707

### Log

My log as below:

calendarEvent [{"allowedAttendeeTypes":["none","required","optional"],"source":{"isLocalAccount":false,"type":"com.android.huawei.phone","name":"Phone"},"timeZone":"GMT","accessLevel":"owner","color":"#00AAEE","isSynced":true,"allowedReminders":["default","alert"],"isPrimary":false,"title":"Phone","name":null,"ownerAccount":"Phone","isVisible":true,"allowedAvailabilities":["busy","free"],"allowsModifications":true,"id":"1"},{"allowedAttendeeTypes":["none","required","optional"],"source":{"isLocalAccount":false,"type":"com.google","name":"apple.ckpgb@gmail.com"},"timeZone":"Asia/Kuala_Lumpur","accessLevel":"owner","color":"#9A9CFF","isSynced":true,"allowedReminders":["default","alert","email"],"isPrimary":false,"title":"apple.ckpgb@gmail.com","name":"apple.ckpgb@gmail.com","ownerAccount":"apple.ckpgb@gmail.com","isVisible":true,"allowedAvailabilities":["busy","free"],"allowsModifications":true,"id":"2"},{"allowedAttendeeTypes":["none","required","optional"],"source":{"isLocalAccount":false,"type":"com.google","name":"apple.ckpgb@gmail.com"},"timeZone":"Asia/Kuala_Lumpur","accessLevel":"read","color":"#92E1C0","isSynced":true,"allowedReminders":["default","alert","email"],"isPrimary":false,"title":"Contacts","name":"Contacts","ownerAccount":"addressbook#contacts@group.v.calendar.google.com","isVisible":true,"allowedAvailabilities":["busy","free"],"allowsModifications":false,"id":"3"},{"allowedAttendeeTypes":["none","required","optional"],"source":{"isLocalAccount":false,"type":"com.google","name":"apple.ckpgb@gmail.com"},"timeZone":"Asia/Kuala_Lumpur","accessLevel":"read","color":"#16A765","isSynced":true,"allowedReminders":["default","alert","email"],"isPrimary":false,"title":"Holidays in Malaysia","name":"Holidays in Malaysia","ownerAccount":"en.malaysia#holiday@group.v.calendar.google.com","isVisible":true,"allowedAvailabilities":["busy","free"],"allowsModifications":false,"id":"4"},{"allowedAttendeeTypes":["none","required","optional"],"source":{"isLocalAccount":true,"type":"LOCAL","name":"Phone"},"timeZone":null,"accessLevel":"owner","color":"#008000","isSynced":false,"allowedReminders":["default","alert"],"isPrimary":false,"title":"FAMS Appointments","name":"FAMS Appointments","ownerAccount":"Phone","isVisible":true,"allowedAvailabilities":["busy","free"],"allowsModifications":true,"id":"5"}]
success 173
this.state.event.  173
updatedCalender  173
success delete this.state.event 173

Thanks,
Apple

**Comment by AppleCkp** [comment]
Hi @cruzach ,
Any update for this?

**Comment by cruzach** [comment]
No update yet, we are in the midst of preparing for SDK 34 release you might have to be patient for a fix for this. You can always take a look at the source code and try to find the root cause of this, that will definitely help speed up the process!

**Comment by AppleCkp** [comment]
Hi @cruzach ,

May I know when SDK 34 will release?

Thanks,
Apple

**Comment by cruzach** [comment]
Now! 😄 

https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319

**Comment by AppleCkp** [comment]
Hi, 

Does this issue fixed in sdk 34?

Thanks,
Kah Peng

**Comment by cruzach** [comment]
No, this is still open so it's not fixed in SDK 34

**Comment by AppleCkp** [comment]
Hi @cruzach ,

When this issue will fixed?

Thanks,
Apple

**Comment by AppleCkp** [comment]
Hi @cruzach ,

Any update??

Thanks, 
Apple

**Comment by cruzach** [comment]
Hey @AppleCkp, this is on our radar, but no update yet

**Comment by lukmccall** [comment]
Hi @AppleCkp, I've run your snack on Android phone and simulator. Everything seems to work fine on SKD 34 (I needed to change import form `import { Permissions, Calendar } from "expo";` to `import * as Calendar  from "expo-calendar";
import * as Permissions from "expo-permissions";`).

Please, try to run it on SKD 34. If this bug will occur, let me know.
I'll be nice if you provide me with information about your Android version and phone.

**Comment by AppleCkp** [comment]
Hi @lukmccall ,

Thank for reply, It works like charm in SDK 34!!

Thanks,
Apple
