### ISSUE TITLE
ExpoKit upgrade 31 -> 33 fails on `pod install`

### ISSUE THREAD

**Issue by amoghpalnitkar** [expo/expo#5011]
## 🐛 Bug Report

On upgrading from ExpoKit 31 to 33, `pod install` fails returning the following error

```
[!] An error occurred while processing the post-install hook of the Podfile.

wrong number of arguments (given 0, expected 1..2)

/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.4/lib/cocoapods-core/podfile/dsl.rb:365:in `target'
/.../ios/Podfile:145:in `block (4 levels) in from_ruby'
/.../ios/Podfile:116:in `each'
/.../ios/Podfile:116:in `block (3 levels) in from_ruby'
```

### Environment

Environment:
  OS: macOS 10.14.5
  Node: 10.10.0
  Yarn: 1.13.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^33.0.0 => 33.0.7
  react: 16.8.3 => 16.8.3
  react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8

### Steps to Reproduce

Follow exact steps given here
[Upgrading ExpoKit](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit)

### Expected Behavior

`pod install` should execute without any errors.

### Actual Behavior
`pod install` returns following error
```
[!] An error occurred while processing the post-install hook of the Podfile.

wrong number of arguments (given 0, expected 1..2)

/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.4/lib/cocoapods-core/podfile/dsl.rb:365:in `target'
/.../ios/Podfile:145:in `block (4 levels) in from_ruby'
/.../ios/Podfile:116:in `each'
/.../ios/Podfile:116:in `block (3 levels) in from_ruby'
```

## Question
When I comment out Podfile:145 code, i.e. `next if target.pod_name != 'React'`
then, `pod install` runs successfully.

What issues would I run into if I keep that commented OR, comment that entire block in the Podfile

```
#      next if target.pod_name != 'React'
#      target.native_target.build_configurations.each do |config|
#        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
#        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
#        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
#        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
#      end
```

**Comment by cruzach** [comment]
Hi @amoghpalnitkar 

What release is the `Expokit` tag pointing to (in `ios/Podfile`)? What version of cocoapods are you using?

I've been able to run SDK 33 projects in Expokit locally, so I'm curious if you see this error when trying to run a fresh, blank Expokit (SDK 33) project?

**Comment by amoghpalnitkar** [comment]
Hey @cruzach ,

`Expokit` tag is pointing to `ios/2.11.2` in `ios/Podfile`.

I don't get this error when trying to run a fresh SDK 33 project. 

What could be the issue? What would happen if I don't run 

```
      next if target.pod_name != 'React'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end
```

**Comment by cruzach** [comment]
There was probably a skipped step somewhere in your upgrade process- maybe step 4 under iOS? 
> Change the whole post_install block at the bottom of the Podfile to...

I would take a look through those steps once more, and maybe compare your podfile to the fresh SDK 33 ejected project's podfile

**Comment by amoghpalnitkar** [comment]
> I would take a look through those steps once more, and maybe compare your podfile to the fresh SDK 33 ejected project's podfile

That helped identify the error. Thanks! 👍
