### ISSUE TITLE
expo notification with sticky is getting dismissed on click

### ISSUE THREAD

**Issue by raajnadar** [expo/expo#5018]
### Environment

  Expo CLI 2.21.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.15.2 - C:\Users\user\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### Steps to Reproduce
Add sticky value to true in android.
The notification gets triggered.
The notification sticks in the notification bar.

But on clicking the notification gets dismissed. As per the docs the notifs cannot be dismissed by user.

> sticky (optional) (boolean) -- if true, the notification will be sticky and not dismissable by user. The notification must be programmatically dismissed. Default: false.

### Expected Behavior

The notification should not be dismissed on click.

### Actual Behavior

The notification gets dismissed.

### Reproducible Demo

https://snack.expo.io/@raajnadar/nervous-peach

```
Notifications.presentLocalNotificationAsync({
  title: 'Testing',
  body: 'Lorem ipsum',
  android: {
    sticky: true,
    color: '#ffa500'
  }
}).then(data => {
  console.log(data)
})
```
This piece of code is enough

**Comment by raajnadar** [comment]
I think the issue can be resolved by removing this line

https://github.com/expo/expo/blob/b7ed5aac7aad3eeb5b7fc40c55d655174db5b5cf/android/expoview/src/main/java/host/exp/exponent/notifications/NotificationHelper.java#L378

But this will make all the notification sticky.

Or we can make it false here

https://github.com/expo/expo/blob/b7ed5aac7aad3eeb5b7fc40c55d655174db5b5cf/android/expoview/src/main/java/host/exp/exponent/notifications/NotificationHelper.java#L469-L471

**Comment by ariona** [comment]
is this still in WIP? stumbled upon this issue.

**Comment by oriooctopus** [comment]
Any progress on this? I'm having the same problem

**Comment by lukmccall** [comment]
This bug should be fixed by the new `expo-notifications` module. So, I'm closing this issue. If this is still a problem for you and it's reproducible using the latest SDK version, feel free to open up a new issue!
