### ISSUE TITLE
In Ios Facebook Login "behavior": "native" Not working

### ISSUE THREAD

**Issue by tofoli** [expo/expo#502]
WebView only works (_default_) to log in with Facebook. When I change the "_behavior_" parameter to any of the other options, after I elevate the Facebook APP, the following message is displayed and nothing in the log is printed.

![whatsapp image 2017-08-14 at 17 55 57](https://user-images.githubusercontent.com/2599384/29291414-e099512e-8119-11e7-8191-5057d593578b.jpeg)

I'm testing on an iPhone 4S with IOS 9.3.5 and an iPhone 6S with IOS 10.2.1. On Android it works normally. Any idea what that might be?

PS: I used Google Translate. Excuse me

**Comment by tofoli** [comment]
Simulated error here https://snack.expo.io/B1doutgdW

**Comment by siwel** [comment]
I believe that the 'native' option only works with standalone apps. [Expo Docs | Facebook](https://docs.expo.io/versions/latest/sdk/facebook.html#behavior-string--the-type-of-login-prompt-to-show-currently-this-is-only-supported-on-ios-and-must-be-one-of-the-following-values)

**Comment by tofoli** [comment]
What is standalone apps @siwel?

**Comment by siwel** [comment]
From the [Building Standalone Apps](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html) Guide;

> Not everybody wants to tell their customers or friends to download Expo to use their app; You want to be able to have the app on its own from the App Store and Play Store. We call these “shell apps” or “standalone apps”…

**Comment by tofoli** [comment]
Many thanks @siwel, I'm going to build and check it out
