### ISSUE TITLE
[snack] Issue using imported module expo-calendar-helper

### ISSUE THREAD

**Issue by graceluo-intel** [expo/expo#5020]
I am trying to create a snack that integrates expo-calendar-helper; however I am getting the error in the attached image. It seems that snack is having trouble accessing internal functions denoted by an underscore. 

![Capture](https://user-images.githubusercontent.com/51839609/61566882-733d6180-aa32-11e9-8aa1-54d99e2ea9c5.PNG)

link to the snack: https://snack.expo.io/rJIAF3JMr

**Comment by FiberJW** [comment]
This is a bug with `expo-calendar-helper`, as it's trying to access functions from an object/class even though the source file shows that the module doesn't contain a class. Please file an issue with [here](https://github.com/AtilaDev/expo-calendar-helper) to bring it to the maintainer's attention for a fix :)
