### ISSUE TITLE
[Web] Always serves blank/default index.html

### ISSUE THREAD

**Issue by peabnuts123** [expo/expo#5022]
## 🐛 Bug Report
Hey all I understand targeting web is a new feature so I'm not sure if I'm doing something wrong or if something isn't working. I can't seem to get expo running on web at all. What I'm trying to run is the command `expo start --web`. It seems any expo projects I try need some extra eslint packages installed to even compile properly, and once that happens, no matter what I try, I am always just served the default HTML file from the expo-cli repo found [here](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/web-default/index.html).
I've tried running the `blank` template (from expo-cli) and I need to install the following packages to get it compiling:

  * "eslint": "^6.0.1",
  * "eslint-config-universe": "^1.0.7",
  * "eslint-plugin-flowtype": "^3.12.1",
  * "prettier": "^1.18.2",

From there, the build works, but all I get served in the browser is the default index.html file linked above. None of the app code in App.tsx seems to be running. **This is also happening with the web-example "[expo-managed-workflow](https://github.com/expo/web-examples/tree/master/expo-managed-workflow)"** and in a friend's project. 

It's probably worth noting I have no issues running any of these apps normally via `expo start` and bringing them up in the iOS app (live reload, etc. it all works).

Screenshot attached:
<img width="1066" alt="Screen Shot 2019-07-20 at 11 09 43 PM" src="https://user-images.githubusercontent.com/2322840/61578123-d9ff6f80-ab45-11e9-9e35-da41a9c4f110.png">

### Environment

```Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.1 - ~/.nvm/versions/node/v12.6.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.23 
      @types/react-native: ^0.57.60 => 0.57.65 
      expo: ^33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.2
```

### Steps to Reproduce

1. Clone [web-example repo](https://github.com/expo/web-examples)
1. `cd expo-managed-workflow`
1. `yarn`
1. `yarn run web`

You should see build errors for `flowtype` eslint plugin not being found in BaseConfig.

5. `yarn add --dev eslint eslint-config-universe eslint-plugin-flowtype prettier`
6. `yarn run web`

Build should succeed now, browser opens a page serving blank, default index.html.

### Expected Behavior

My code is run in some form (i.e. App.jsx)

### Actual Behavior

Default file from `expo-cli` webpack config is served instead.

### Reproducible Demo

See [web-example repo](https://github.com/expo/web-examples/tree/master/expo-managed-workflow).

**Comment by gardner** [comment]
I can't run the example either:

    npm i -g expo-cli
    git clone https://github.com/expo/web-examples.git
    cd web-examples/expo-managed-workflow
    yarn
    expo start --web --non-interactive

Results in the output:

    [10:13:15] Starting project at /Users/gardner/src/web-examples/expo-managed-workflow
    [10:13:15] Expo DevTools is running at http://localhost:19002
    [10:13:17] Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v32.0.0/workflow/configuration/
    [10:13:17]  • Field: platforms - should NOT have more than 2 items.
    [10:13:17] Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory.
    [10:13:22] Starting Metro Bundler on port 19001.
    [10:13:24] Tunnel ready.
    [10:13:26] Cannot find module 'eslint'
    [10:13:26] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by EvanBacon** [comment]
Should bee fixed in the next release. Also adding tests to prevent ultra-fatal issues like this https://github.com/expo/expo-cli/pull/861

**Comment by vivirose** [comment]
when is the next release? @EvanBacon

**Comment by peabnuts123** [comment]
Wow, okay. Love your work 🙂

**Comment by EvanBacon** [comment]
It's released. Please run `npm i -g expo-cli` to use the latest. Sorry for any & all inconveniences this may have caused :/

**Comment by gardner** [comment]
Verified fixed with expo-cli@3.0.4. Thank you!

**Comment by estebanjb** [comment]
Im using expo-cli@3.0.4 but i'm facing the blank html page. It seems like RN App is not mounting the main component in the root node of the basic html template.

**Comment by EvanBacon** [comment]
@estebanjb this is unrelated to the original issue. Could you please open a new issue.
