### ISSUE TITLE
The video disappear with .mov type has alpha channel

### ISSUE THREAD

**Issue by tamdao** [expo/expo#5023]
### Environment

Expo v33

### Steps to Reproduce
Use video tag with the code below and the video file is mov and has alpha channel. You can get a video with alpha channel here: https://www.videezy.com/elements-and-effects/7214-animated-characters-couple-walking-alpha-transparent

```
<Video
          source={require('./assets/walking_Couple.mov')}
          rate={1.0}
          volume={1.0}
          isMuted={false}
          resizeMode="cover"
          shouldPlay
          isLooping
          style={{ width: 300, height: 300 }}
        />
```

### Expected Behavior

See the video

### Actual Behavior

The video disappear. But I can hear audio

**Comment by cruzach** [comment]
Hey @tamdao - is this happening on iOS, Android, or both? I would make sure and take a look at either the [iOS docs](https://developer.apple.com/documentation/) or the [Android docs](https://developer.android.com/guide/topics/media/media-formats#formats-table) to make sure your filetype is supported.

**Comment by tamdao** [comment]
@cruzach mov file only support on iOS

**Comment by sjchmiela** [comment]
Hey, @tamdao! I'm sorry to say that it's iOS which doesn't support videos containing an alpha channel (see [this StackOverflow answer](https://stackoverflow.com/a/16449013/1123156)).

There are ways to simulate the effect, but it would require video editing and native code changes — see https://medium.com/@quentinfasquel/ios-transparent-video-with-coreimage-52cfb2544d54.

I'll let myself close this issue, it's too specific feature and much implementation to add to Expo. Try looking for a 3rd party library and ejecting! 🙂
