### ISSUE TITLE
BottomTabNavigator not  show as expected in standalone build

### ISSUE THREAD

**Issue by minhtus** [expo/expo#5026]
I'm using react-navigation for navigators, my BottomTabNavigator is lost half in standalone build but work as usual in expo client. I've submitted a question at StackOverflow https://stackoverflow.com/questions/57095974/bottomtabnavigator-is-half-override-when-built-standalone-app but haven't received any proper solution yet. 
I don't know whether this is an error in the expo compiler or not so please help me. 

Here're the screenshots [Expo client](https://i.stack.imgur.com/fN0QG.png) and [Standalone build](https://i.stack.imgur.com/H18o3.png)

I've tested on several devices so I believe it's not the specific device issue.

**Comment by AdamJNavarro** [comment]
Hey @minhtus,

If you have `androidStatusBar` in your `app.json` remove it as that is the cause for the tab bar getting pushed down and instead make use of the `StatusBar` API from React Native.

Cheers,
Adam

**Comment by minhtus** [comment]
It works, thanks! I didn't even think about that.
