### ISSUE TITLE
Location.requestPermissionsAsync throws error in Expo SDK 33

### ISSUE THREAD

**Issue by sfyfedotcom** [expo/expo#5027]
### Environment

Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: 33.0.0 => 33.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 

This is happening in the XCode iOS simulator and a Genymotion Android emulator

### Steps to Reproduce

When trying to request a user's location using `expo-location`

### Expected Behavior

It requests the user's location

### Actual Behavior

It throws:
> undefined is not an object (evaluating '_ref.status')

I was using `navigator.geolocation` on iOS, which was working fine. But it wasn't working on Android, hence trying `expo-location`, which doesn't appear to work on either.

### Reproducible Demo

```
import { requestPermissionsAsync } from 'expo-location'
...
const { status } = await requestPermissionsAsync()
```

**Comment by lukmccall** [comment]
Hi @sfyfedotcom, I think this bug was fixed in SDK 34. However, if you wanna stick with the older version, you always can request the same permissions using this code:
```
import * as Permissions from 'expo-permissions';
...
const { status } = await Permissions.askAsync(Permissions.LOCATION);
```

**Comment by lukmccall** [comment]
@sfyfedotcom, feel free to reopen this issue if this bug is still present. I'm closing it for now because I think `requestPermissionsAsync` was fixed.
