### ISSUE TITLE
ScrollView not scrolling with TabNavigator on iPhone

### ISSUE THREAD

**Issue by haaswill** [expo/expo#503]
## Environment:
- Expo Client 1.18.0
- Expo XDE 2.19.3
- SDK Version: 18.0.0
- React Navigation: 1.0.0-beta.11
- Node: 8.1.4

**MainScrollView.js**

`import React from 'react';`
`import { ScrollView, View } from 'react-native';`
`import styles from './styles';`

`const MainScrollView = ({ header, children, innerContainerStyle = [] }) => (`
`<View style={styles.container}>`
`{header}`
`<ScrollView style={[styles.body, innerContainerStyle]}>`
`{children}`
`</ScrollView>`
`</View >`
`);`

`export { MainScrollView };`

**styles.js**

`import { StyleSheet } from 'react-native';`
`import { colors } from '../../config/styles';`

`export default StyleSheet.create({`
`body: {`
`backgroundColor: colors.white,`
`flex: 1`
`},`
`container: {`
`backgroundColor: colors.white,`
`flex: 1`
`}`
`});`

This issue had been addressed here: 
https://github.com/react-community/react-navigation/issues/1797

Yet, I guess this is an issue within the Expo Client itself, because running on iOS Emulator works just perfectly.

The project can be found here:
Github: https://github.com/haaswill/open-wallet-app
Expo: https://exp.host/@haaswill/open-wallet-app

**Comment by haaswill** [comment]
The bug has been fixed. Thank you!

**Comment by jlc467** [comment]
@haaswill How/when was it fixed? Having this same issue.

**Comment by haaswill** [comment]
@jlc467 For me, it was fixed when I updated Expo Client to the latest version(1.19.0).
What version are you using?
Does it work on the iOS emulator?

**Comment by jlc467** [comment]
Works in iOS emulator. Expo client version: 1.19.0.109298

**Comment by jlc467** [comment]
@haaswill reinstalled expo client and now it working. Thanks!
