### ISSUE TITLE
Error : there is some async operations still in progress after first login with  GoogleSignIn.signInAsync

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#5036]
const { type, user } = await GoogleSignIn.signInAsync();
after login it give an error **there is some async operations still in progress** and failed.
some then **GoogleSignIn.signInAsync()** does not get triggered and then no error no result nothing, again and again says **there is some async operations still in progress**
i have tried both Google and GoogleSignIn but no luck.
its been one week but no solution.
Please help me out with sharing your code if yours working fine.
Thanks in advanced.

**Comment by cruzach** [comment]
@reactexcel this is the 3rd issue you've opened regarding this behavior, and each time I've said we need you to follow the issue template to be able to help effectively. It also makes it very difficult to keep track of the conversation when it's going on in 3 different locations.

All correspondence regarding this issue should happen in [this issue](https://github.com/expo/expo/issues/5032#issuecomment-513777385)
