### ISSUE TITLE
When restarting project packager runs on different port

### ISSUE THREAD

**Issue by avalanche1** [expo/expo#504]
If I restart project without clearing package cache (holding down Shift while pressing Restart) React Native packagers runs on 19002 whereas by default it runs on 19001. Is that normal? It breaks my genymotion emulator.

**Comment by jesseruder** [comment]
How does it break the emulator? Please provide an error message or more details.

**Comment by jimmylee** [comment]
Closing this issue since we haven't gotten a reply for close to a month.
