### ISSUE TITLE
Unable to read ExpoKit version from Podfile.lock

### ISSUE THREAD

**Issue by jafri** [expo/expo#5047]
### Environment

  Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.0.2

Target: iOS

### Steps to Reproduce

Seeing the following error when following instructions at https://docs.expo.io/versions/latest/expokit/expokit/:
```Unable to read ExpoKit version from Podfile.lock```

### Fix?
Was able to get past the error by adding
```
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.11.2",
    :subspecs => [
      "Core"
    ]
```

**Comment by cruzach** [comment]
Hi! What version are you upgrading from and what version are you upgrading to?

Also, you added that code to your Podfile? I have that code already present in a blank SDK 33 ejected project, so you're right in doing that (although I wonder why it wasn't present before)

**Comment by jafri** [comment]
I upgraded from SDK 31, however it looks like I copied a file from one of the guides that did not specify that ExpoKit pod still had to remain
