### ISSUE TITLE
OrientationChangeListener not firing for landscape left and right 

### ISSUE THREAD

**Issue by bsehovac** [expo/expo#5048]
Let's say I want landscape only orientation in my app, and I lock it in app.json to `landscape`. I have vertical toolbar like on the sketch bellow, and when i rotate my phone on one side, the toolbar is hidden bellow the notch on iPhone.

![iphone-x](https://user-images.githubusercontent.com/25138348/61708815-01288d80-ad4e-11e9-81ac-691fc82f2102.png)

I can't add `OrientationChangeListener`, because it is not firing for different landscape orientations, so there is no way that i can know on which side phone is rotated, so i can adjust my layout for it then.

I can add `ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE_RIGHT)`, but when I open my app, splash screen is rotated to the left, and then app loads, and it rotates right.

Do we have any other solution here, like setting application in landscape right or left in app.json, or at least to fire `OrientationChangeListener` when i rotate phone?

**Comment by cruzach** [comment]
Hey @bsehovac - could you follow share a repro so I can see the behavior on my end? Specifically `OrientationChangeListener` not firing when you rotate from one landscape orientation to another.

>setting application in landscape right or left in app.json

Right now, this isn't possible. But maybe it is something we could look into, or would happily review a high-quality PR for!

**Comment by cruzach** [comment]
Hey @bsehovac, the best way to position your content appropriately around notches like the one in the image you shared is with the [SafeAreaContext API](https://docs.expo.io/versions/latest/sdk/safe-area-context/) we recently added

**Comment by lukmccall** [comment]
Hey @bsehovac,  [SafeAreaContext API](https://docs.expo.io/versions/latest/sdk/safe-area-context/)  should resolve your problem. `OrientationChangeListener` won't fire for different landscape orientations. This's not possible, because to do it on iOS we need to apply a workaround solution. We don't want to do it. 

I'm closing this issue right now. If SafeAreaContext is not fit your needs, feel free to reopen this issue.
