### ISSUE TITLE
How to run on Genymotion in offline mode?

### ISSUE THREAD

**Issue by avalanche1** [expo/expo#505]
I need to develop in an environment that doesnt have internet connection.
I have managed to run my project on a physical device by creating a wifi hotspot on it (data connection disabled) and connecting to the hotspot with my laptop. Then in project folder I ran `exp start --lan --offline` and scanned the QR from the console.

But what about Genymotion? When I try `exp android --offline` I get this error screen:
![image](https://user-images.githubusercontent.com/10534563/29361959-ac055138-8281-11e7-8cb5-606620fee709.png)
![image](https://user-images.githubusercontent.com/10534563/29361984-c98a0050-8281-11e7-907c-7934060c93cb.png)

**Comment by sebas5384** [comment]
Yeah! same need over here.

**Comment by dikaiosune** [comment]
Hi! Sorry for the delay in replying here. Are you still experiencing this issue on a recent version of exp & Genymotion? If so, can you tell me whether you're able to load the URL that `exp` provides in a web browser, replacing `exp://` with `http://`? I'm curious whether we're sending an incorrect URL or whether your emulator can't view the server we're running on the host OS.

**Comment by jesseruder** [comment]
You should be able to use `exp start --offline --localhost` as long as `adb` can connect to Genymotion. Let us know if that doesn't work, but going to close this issue for now!

**Comment by integrable** [comment]
@jesseruder I am struggling to do offline development on a project detached to ExpoKit. 
I run `exp start --offline --localhost`. Then, I run the project from Android Studio (or with react-native run-android) in emulator or a connected physical device, in both cases, I get the error "Could not load app. Are you sure XDE or exp is running". Is it possible, to develop offline after detaching to ExpoKit ?
