### ISSUE TITLE
import * as Svg from 'react-native-svg' producing an error after expo upgrade from 32.0.0 to 33.0.0

### ISSUE THREAD

**Issue by sauzy34** [expo/expo#5051]
After upgrading the Expo SDK from 32.0.0 to 33.0.0, I'm receiving a warning not to use `import { Svg } from 'expo'` & use it like `import * as Svg from 'react-native-svg'` after installing the `react-native-svg` dependency using `expo-install`. But after that i'm getting an error. Otherwise, it's working fine.

![Screenshot_20190723-200410](https://user-images.githubusercontent.com/19049022/61721988-14a41a80-ad87-11e9-88f6-25784aa3258b.jpg)

**Comment by sguha00** [comment]
Can you post the render method of `Icon`?

**Comment by cruzach** [comment]
Try changing your import to something more like this: (don't need to include the Circle or Rect if you don't use them, it's just what the example uses)
```
import Svg, { Circle, Rect } from 'react-native-svg';
```
as it shows in the example from Expo's [Svg docs](https://docs.expo.io/versions/latest/sdk/svg/)

**Comment by sauzy34** [comment]
`import Svg, { Path, G, Defs, Stop, LinearGradient, Circle, Polygon, Rect, Ellipse } from 'react-native-svg'
` used it like this & working fine!☺
