### ISSUE TITLE
Push notifications don't get delivered on some specific Android devices

### ISSUE THREAD

**Issue by nilsdnz** [expo/expo#5058]
### Environment

Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.9.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.21.2

App target is standalone for both Android and iOS although this issue only affects some Android devices.

### Steps to Reproduce

Unfortunately its hard to reproduce... Push notifications do not get delivered on some Android devices like Xiaomi, Huawei or OnePlus unless you manually enable the Auto-start option on the app settings page. This behavior is sporadic and only happens if the app is closed.

### Expected Behavior

Push notifications get delivered all of the time on all devices.

### Actual Behavior

When the app is closed it gets force killed on some Android devices (mainly chinese manufacturers like Xiaomi, Huawei, OnePlus or Samsung) due to aggressive battery optimization mechanisms. You have to manually enable an option often called Auto-start or disable battery optimization for your app in the Android settings.

### Reproducible Demo

This affects all apps build with Expo which deliver push notifications, even the notifications sample app.

This behavior is also mentioned in these two articles:

https://www.freecodecamp.org/news/why-your-push-notifications-never-see-the-light-of-day-3fa297520793/

https://hackernoon.com/notifications-in-android-are-horribly-broken-b8dbec63f48a

The second article suggests to implement a mechanism to detect if a push notification was received and then show the user an alert to guide to the responsible settings.

The problem with the Expo push notification implementation is that there is (to my understanding) no possible way of detecting if a notification was actually received and displayed on the device unless the user interacts with it. The receipts of the affected notification show a status of successful delivery by FCM.

For some apps (eg messengers) successful and reliable notifications are really crucial so I guess this is a problem that definitely should get addressed.

Thanks in advance for any investigation and possible help!

**Comment by cruzach** [comment]
Hey @nilsdnz 

For FCM, `{"status": "ok"}` indicates that Firebase acknowledged receipt of the notification so I suspect the issue is between Google and the device, or an issue on the device. That is, if you are getting all `{"status": "ok}` messages with FCM enabled, the delivery rate from Expo to Firebase is 100%.

Also, I suggest digging into the receipts a little more. From our [docs](https://docs.expo.io/versions/latest/guides/push-notifications/#receipt-response-format):
> Important: in particular, look for a details object with an error field inside both push tickets and push receipts. If present, it may be one of these values: DeviceNotRegistered, MessageTooBig, MessageRateExceeded, and InvalidCredentials

**Comment by nilsdnz** [comment]
Thanks for answering. I am aware of the error fields of the receipts but they don't show any. As stated in the two articles I linked this is an issue with the OEMs customizing Android to aggressively kill background processes.
What I am looking for is any possible way to detect if the notification was received and displayed on the users phone so if that's not the case I could show an alert with additional help.

**Comment by cruzach** [comment]
Well, the `Notifications` API provides the `Notifications.addListener(listener)` method, but that is for when the *app* receives the notification, not the device (which I think is what you're looking for). Besides the receipts (which let you know if *Expo* successfully received the notification), I don't believe there's another way of detecting if the notification was received by the actual device.

**Comment by nilsdnz** [comment]
If im not mistaken this is possible for native Android apps. Would opening a feature request be the way to go or do you think this is just something we have to live with?

**Comment by cruzach** [comment]
If it is, then definitely open a feature request over at our [canny](https://expo.canny.io/feature-requests) (if there isn't one for it already)

**Comment by nilsdnz** [comment]
Ok, I'm gonna research a little more and then open a feature request with some more detail. Thanks for taking the time!
