### ISSUE TITLE
react-native-image-picker doesn't work in detached android app

### ISSUE THREAD

**Issue by leo108** [expo/expo#506]
I have a detached project and I have followed the installation steps in [react-native-image-picker](https://github.com/react-community/react-native-image-picker), my js code is 

```
import React from 'react';
import { View, Button } from 'react-native';

var ImagePicker = require('react-native-image-picker');

export default class App extends React.Component {
    selectPhoto() {
        var options = {
          title: 'Select Avatar',
          storageOptions: {
            skipBackup: true,
            path: 'images'
          }
        };
        ImagePicker.launchImageLibrary(options, (response) => {
            console.log(response);
        });
    }
    render() {
        return (
          <View>
            <Button title = "Pick an image" onPress = { this.selectPhoto } />
            </View>
        );
    }
}
```

When I click the button it shows the image library and I can pick an image from the library, but the `console.log(response);` is not executed, and there is no error message in console.

I have tried the example the react-native-image-picker project provides and it works well in normal react native project.

This bug only appears in android version, ios version works well.

**Comment by jesseruder** [comment]
Sounds like it could be a bug in `react-native-image-picker`. Are you sure it works in the version of React Native that you detached with? A good next step would be to hook up the Android debugger and see what's going on from the native side.

**Comment by leo108** [comment]
@jesseruder I have added some debug code to trace what happened and found that `onActivityResult` was not called after `startActivityForResult`, that’s why there was no response in js code, I have tried to add breakpoints at `startActivityForResult` and `onActivityResult`, but `onActivityResult` was never executed.

**Comment by terribleben** [comment]
@jesseruder anything for us to do about the above?

**Comment by dikaiosune** [comment]
It looks to me like #651 is a more general report that pertains to a wider variety of libraries. We'll track this issue there. Thanks!
