### ISSUE TITLE
Unable to resolve “../../App” from “node_modules/expo/AppEntry.js”

### ISSUE THREAD

**Issue by VanLaerAshley** [expo/expo#5069]
### Environment

  Expo CLI 3.0.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: 33.0.0 => 33.0.0 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.2

### Steps to Reproduce

I am making a vue-native app with expo. when upgrading to expo version 33 I get the following error "Unable to resolve "../../App" from "node_modules/expo/AppEntry.js". The need to upgrade to version 33 is because I need the expo filesystem module.

I have already made a new project from scratch and the same error still occurs.

 **package.json**
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^33.0.0",
    "global": "^4.4.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-cli": "^2.0.1",
    "react-native-web": "^0.11.4",
    "vue-native-core": "0.0.8",
    "vue-native-helper": "0.0.11"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-0",
    "babel-preset-expo": "^5.1.1",
    "vue-native-scripts": "0.0.16"
  },
  "private": true
}
```

**Comment by mmustafau** [comment]
i have same problem.

**Comment by cruzach** [comment]
Could you provide a repro for for this? I think it might be more specific to `vue-native` (and I see you've already found the [relevant issue on vue-native's repo](https://github.com/GeekyAnts/vue-native-core/issues/117) 👍 )

**Comment by EvanBacon** [comment]
This is a Metro bundler issue, seems solved with: https://github.com/GeekyAnts/vue-native-core/issues/117#issuecomment-520403713
