### ISSUE TITLE
Add details in documentation for production flags

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#507]
Hi,

In the Expo docs there's [a section that says](https://docs.expo.io/versions/latest/guides/how-expo-works.html#publishingdeploying-an-expo-app-in-production):
> When you Publish an Expo app, we compile it into a JavaScript bundle with production flags enabled (minify, disable runtime development checks) and upload that bundle, along with any assets that it requires (see Assets) to CloudFront.

What does "with production flags enabled" means? Are you referring to `process.env.NODE_ENV` or to `__DEV__`?

Basically, how do I detect inside of a React Native app built with Expo if it's running in a production or development environment?

Also can we please make the docs more clear on this point? Once I figure it out if you like I can send a PR. Thx!

**Comment by jesseruder** [comment]
You can use `__DEV__`. Yes, a docs PR would be great!

**Comment by HuiSF** [comment]
@jesseruder Could you please give me some directions that how should I enable `__DEV__` flag? Thanks.

**Comment by pensierinmusica** [comment]
@jesseruder I sent the PR, hopefully it should be accepted befor a new version of the docs is generated, otherwise the added info won't beincluded in future versions. Thx :)

**Comment by alamothe** [comment]
Does `process.env.NODE_ENV` work too?

The reason I ask is because I use `create-react-app` (for web) together with Expo, and it doesn't support `__DEV__`.

**Comment by kylebebak** [comment]
As of earlier today, `__DEV__` is now `false` instead of `true` when I run `expo start`. This happened  without any warning today. I'm on expo 32.0.0. I didn't update expo or anything. Clearing the cache did nothing.

**Comment by brentvatne** [comment]
<img width="584" alt="Screen Shot 2019-03-22 at 11 07 32 AM" src="https://user-images.githubusercontent.com/90494/54843896-ba893080-4c92-11e9-8281-ff8832de81e4.png">

notice the line with `(current mode: development)` - yours probably says production. you can toggle it as explained there.

<hr />

or if you use the web ui, you can click the production toggle so it looks like what you see here

<img width="411" alt="Screen Shot 2019-03-22 at 11 09 08 AM" src="https://user-images.githubusercontent.com/90494/54844000-fae8ae80-4c92-11e9-9577-69fe714653eb.png">

**Comment by AdamGerthel** [comment]
I'm having issues with this, as it doesn't seem to be consistent at all:

![Screenshot 2019-04-05 at 14 59 04](https://user-images.githubusercontent.com/1490370/55629691-1932cc00-57b4-11e9-9bb7-a1c8dca73cdb.png)

**Comment by brentvatne** [comment]
@AdamGerthel - you may need to close and reopen the app, or refresh with the expo to ensure it updates the manifest

**Comment by AdamGerthel** [comment]
@brentvatne doesn't help :/

The toggle doesn't seem to work properly either. Is it supposed to be like this? I've reproduced it in a video: https://www.dropbox.com/s/ntlspw0e6qg72zw/expo%20production%20toggle.mov?dl=0

**Comment by marklundin** [comment]
I'm also getting this. I'm not sure what the intended behaviour is, but it seems incorrect
