### ISSUE TITLE
Cached redirects for GET requests using fetch on expo iOS app

### ISSUE THREAD

**Issue by domenbukovac** [expo/expo#5077]
## 🐛 Bug Report

I've spent two hours trying to debug an issue with fetch and finally figure it out what might have caused the problem.

What I did was update the API and changed one route to exclude trailing slash. The URL endpoint for GET request used to be `.../api/users/` and after I changed it to `.../api/users`.

When I've made a request before to endpoint `.../api/users?id=10`, it was redirected to `.../api/users/?id=10` by a server. 

```
// after the first request with a 301 response, any new request to the same URL
// would be changed according to the previous redirect
 
fetch('.../api/users/?id=10', {
  method: 'GET',
  headers: new Headers({
      Accept: 'application/json',
      Authorization: auth,
  }),
});
```

> Backend is made in Flask, so by default routes with a trailing slash would accept URL without it and redirect it to the URL with an added slash `/api/users => /api/users/`. But if a route is defined without a trailing slash, requests with one would be invalid `/api/users/ => 404`

The problem was that I've made a request to the route without trailing slash and it was automatically redirected to the one with it. After I changed the API route to `.../api/users` and made a request (using fetch) to route `/api/users?id=10`, URL was converted to `/api/users/?id=10` which was invalid.

Restarting Expo and the iOS client didn't erase the cache and the only way to fix this was to reinstall the app.

> Note: Request is not redirected (from cache) if URL with the exact same parameters have not been fetched before. So request to `/api/users?id=123` would still work afterwards.

### Environment

Expo app on iOS

### Steps to Reproduce

Create fetch request to API a route which responses with redirect. Then change the route which returns HTTP response 200 and try to make same request again.

### Expected Behavior

I think expo iOS client shouldn't cache redirects since there are no benefits to it while developing or at least have an option to erase the cache.

### Actual Behavior

Redirects are cached and I couldn't find and option to erase them. It actually took me some time to figure out what was the cause of the problem in the first place.

**Comment by cruzach** [comment]
Hi! Thanks for bringing this up

Right now, we use RN's network implementation, which is the one Apple uses (NSURL). We may work on our own networking library in the future, but we don't have any current plans for it. 

Separately, we've opened an [issue](https://github.com/expo/expo/issues/5129) to provide tools to clear the app's cache, but your case, the HTTP headers are what control the caching policy, so this may be more in your control
