### ISSUE TITLE
Still got issues after updating to SDK33 and i cannot even find where is the FileSystem that showing on the log

### ISSUE THREAD

**Issue by iamrommel** [expo/expo#5079]
My case is im always seeing this

````
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: FileSystem.

1. Add correct versions of these packages to your project using:

   expo install expo-file-system

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { FileSystem } from 'expo' -> import * as FileSystem from 'expo-file-system'

````

I already used code-mod and here is the result
````
$ npx expo-codemod sdk33-imports '**/*.js'
Transforming 181 JS files...
Processing 181 files...
Spawning 7 workers...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 26 files to free worker...
Sending 25 files to free worker...
All done.
Results:
0 errors
180 unmodified
1 skipped
0 ok
Time elapsed: 2.928seconds
````
Nothing was changed, i looked around my codes manually,  (CTRL + F) and did not find anything similar to ```import { FileSystem } from 'expo' ```

My device got stuck to ```Downloading Javascript Bundles 100.00%```

How was the expo is able to detect this? Are there any tools or ways to check which code uses this? I'm really scratching my balls for a couple of day just looking for this issue.

**Comment by iamrommel** [comment]
Maybe related to this https://github.com/expo/expo/issues/4444

**Comment by cruzach** [comment]
It's probably a dependency of yours that is using the old import syntax. I would grep your project folder for `FileSystem` and see what comes up. Most likely you'll have to submit a PR to whatever relevant library you're using to update to the new syntax

**Comment by iamrommel** [comment]
Ow, that is a big breaker for me to adapt to new sdks, i need to wait for
the dependency to update thier library which i dont know if they interested
in doing so and thier timeline. If also expo cli can be updated to tell me
which file got offensive for that issue it will be a big help for those
that are upgrading to new sdks

**Comment by mdouazou** [comment]
Applying the following solved this same issue I had : 

> For example, if you currently have import { FileSystem } from 'expo';, you'll need to run expo install expo-file-system and then change your import to import * as FileSystem from 'expo-file-system';.

For these two files :

- ...\node_modules\@expo\browser-polyfill\src\DOM\HTMLImageElement.js

- ...\node_modules\expo-three\lib\loaders\readAsStringAsync.js

Hope this is helpful.
