### ISSUE TITLE
[web] css styles in "public/index.html"

### ISSUE THREAD

**Issue by oxyii** [expo/expo#5081]
Expo decided to use the rubber template vertically on web. This does not match the behavior on other platforms. This is especially inconvenient if you develop cross-platform packages. Look at this [snack](https://snack.expo.io/@oxyii/expo-strange-html-template). This situation is quite standard: parent View (may be not root of app, may be in package) sets itself flex and overflow hidden. A child View can try to expand vertically and horizontally. At the same time, this child View can be in another package. So, native platforms work correctly, web-platform works correctly horizontally, but not vertically. Most developers (of the main application) will solve a problem with overscroll for native platforms, why not provide him with the opportunity to automatically solve this for the web platform?

P.S. Sorry for my english. If you cannot understand me, just look into snack on all platforms

**Comment by EvanBacon** [comment]
I don't think I understand exactly what you'd like changed. Could you please open a PR in https://github.com/expo/expo-cli/blob/master/packages/webpack-config/web-default/index.html

**Comment by oxyii** [comment]
https://github.com/expo/expo-cli/pull/1090
