### ISSUE TITLE
How do I react native expo compress a video before uploading it to a database?

### ISSUE THREAD

**Issue by Salihhhhh** [expo/expo#5083]
Hi guys,
I'm sorry my English is bad.
How do I react native expo compress a video before uploading it to a database?
 Is there a video compression package or other method for expo?

**Comment by cruzach** [comment]
Hey! This has [already been asked on our forums](https://forums.expo.io/t/can-i-compress-a-video/11137), basically you can do this, but you'd have to use a third-party software to do it

**Comment by Salihhhhh** [comment]
This can't solve my problem.
Nevertheless thanks.
