### ISSUE TITLE
[expo-av] onLoad repeatedly called after shouldPlay updates

### ISSUE THREAD

**Issue by riwu** [expo/expo#5084]
### Environment
  Expo CLI 3.0.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: Using globally installed version of Yarn
1.12.1 - /opt/facebook/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.4 - /opt/facebook/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8

iOS, Client

### Steps to Reproduce
1. Update the `shouldPlay` prop value
2. `onLoad` gets called

### Expected Behavior
`onLoad` & `onLoadStart` should only be called once after initial video load.

### Actual Behavior
`onLoad` & `onLoadStart` is called whenever `shouldPlay` prop updates.
This bug does not exist in v28 (didn't test v29-32).
![](https://i.imgur.com/LCO5MQO.gif)

### Reproducible Demo
https://snack.expo.io/@riwu/video-onload
```
import React from 'react';
import { View, StyleSheet, Button, Alert } from 'react-native';
import { Video } from 'expo-av';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
});

const App = () => {
  const [shouldPlay, setShouldPlay] = React.useState(false);
  return (
    <View style={styles.container}>
      <Video
        source={{
          uri: 'http://techslides.com/demos/sample-videos/small.mp4'
        }}
        isLooping
        shouldPlay={shouldPlay}
        onLoad={() => Alert.alert('loaded')}
        style={{ width: 100, height: 100 }}
      />
      <Button
        title={shouldPlay ? 'Pause' : 'Resume'}
        onPress={() => setShouldPlay(!shouldPlay)}
      />
    </View>
  );
};

export default App;
```

**Comment by riwu** [comment]
On a separate note, `Video.pauseAsync()` takes very long to execute as well (`status.positionMillis` updated by 1 sec after `.pauseAsync()` is called).

**Comment by cruzach** [comment]
Hi!

I'm curious if using the [Playback API](https://docs.expo.io/versions/latest/sdk/av/#playback-api) results in the same behavior, could you test that?

**Comment by riwu** [comment]
@cruzach `.pauseAsync()` does not reload the video but execution is delayed (see above comment).
