### ISSUE TITLE
E_UNEXPECTED_ERROR in FaceDetection

### ISSUE THREAD

**Issue by gunaangs** [expo/expo#5085]
## 🐛 Bug Report

**Encountered an exception while calling native method: Exception occurred while executing exported method detectFaces on module ExpoFaceDetector: null

Stack trace:
  node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:95:55 in <unknown>
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:397:4 in __invokeCallback
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:127:28 in <unknown>
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297:10 in __guard
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:126:17 in invokeCallbackAndReturnFlushedQueue
  [native code]:null in invokeCallbackAndReturnFlushedQueue**

### Steps to Reproduce

After the Expo cli update I am facing the Error in Face detection module.
Steps:
Select the image file and send it to the Face detection code but its throws an error.

FaceDetector.detectFacesAsync(this.props.imageurl, {
      detectLandmarks: FaceDetector.Constants.Landmarks.none,
      runClassifications: FaceDetector.Constants.Classifications.all,
    })
      .then(this.facesDetected)
      .catch(this.handleFaceDetectionError);

### Expected Behavior

Face detection should work and show the smile rate

### Actual Behavior

Face detection shows a unexpected error

**Comment by cruzach** [comment]
> After the Expo cli update

Which `expo-cli` update? what version are you upgrading from/to?

Also, is this in the Expo Client, or a standalone app? Android, iOS, or both?

**Comment by gunaangs** [comment]
@cruzach 
Thank you for your reply

Now I am using expo-cli 3.0.4
I think I have upgraded from 2.21.2

This is my expo project
https://expo.io/@gunaseelan/angs-secure

I am facing this error in Android module.

**Comment by cruzach** [comment]
And is this occurring in the Expo Client app (via `expo start`), or when you build an apk (`expo build:android`)?

**Comment by gunaangs** [comment]
via expo start

**Comment by gunaangs** [comment]
I have already used this facility without any error now only i got this error.

ExpoFaceDetector: null

So that I am facing the E_UNEXPECTED_ERROR

**Comment by cruzach** [comment]
Hm okay, and the only change was an upgrade to `expo-cli`? Or have you also updated the Expo SDK, as well. copy/paste your `package.json` here

**Comment by gunaangs** [comment]
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^9.0.0",
    "dateformat": "^3.0.3",
    "expo": "^32.0.6",
    "native-base": "^2.13.1",
    "react": "^16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-orientation": "^3.1.3",
    "react-native-thumbnail-video": "^0.1.2",
    "react-navigation": "^3.11.0",
    "react-redux": "^6.0.1",
    "redux": "^4.0.3",
    "redux-thunk": "^2.3.0",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

**Comment by rooque** [comment]
This also started to happen for me after I upgraded expo client to version 2.12.0. I downgraded to 2.11.2 and everything is back to normal.

**Comment by gunaangs** [comment]
@cruzach 

Actually after build the code and generated the apk file Face detection works fine 
The issue only available in the expo-cli in local execution.

**Comment by cruzach** [comment]
Yeah, this looks to be an issue specifically with the Expo Client app, thanks for reporting @gunaangs and @rooque

**Comment by gunaangs** [comment]
@cruzach 
And one more issue, while using face detection in Camera Some of the attributes or not returned
Only the following attributes get returned from the Face detection.
Refer: https://docs.expo.io/versions/latest/sdk/facedetector/#event-shape
Array [
  Object {
    "bounds": Object {
      "origin": Object {
        "x": 81.52380952380952,
        "y": 262.33809523809526,
      },
      "size": Object {
        "height": 224.01904761904763,
        "width": 231.6190476190476,
      },
    },
    "faceID": -1,
    "rollAngle": 357.3493275642395,
    "yawAngle": 2.2153072357177734,
  },
]

**Comment by ricardovf** [comment]
Also have this error after going from expo-cli 2 to 3.

**Comment by ricardovf** [comment]
Just reforcing, this a critical limitation, as i upgraded the sdk to 33 and cant test my app because of this error. Tried to run with older client but got other errors (i guess because sdk is newer).

**Comment by sjchmiela** [comment]
Glad to hear that! I'll close this issue tentatively in such case.

When it comes to event shape it depends on `faceDetectionClassifications` set, as noted in the documentation:
> `smilingProbability`, `leftEyeOpenProbability` and `rightEyeOpenProbability` are returned only if `faceDetectionClassifications` property is set to `.all`.
Positions of face landmarks are returned only if `faceDetectionLandmarks` property is set to `.all`.

so eg. 
```jsx
<Camera
  // ... other props
  onFacesDetected={this.handleFacesDetected}
  faceDetectorSettings={{
    mode: FaceDetector.Constants.Mode.fast,
    detectLandmarks: FaceDetector.Constants.Landmarks.all,
    runClassifications: FaceDetector.Constants.Classifications.all,
    minDetectionInterval: 100,
    tracking: true,
  }}
/>
```
