### ISSUE TITLE
EXC_BREAKPOINT: moduleMapping on iOS, EXC_BREAKPOINT_os_unfair_lock_corruption_abort

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo#5086]
### Environment

Expo CLI 3.0.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.0.4

### Steps to Reproduce

I'm not sure how this is happening, and it doesn't happen to all of our users, but we're getting reports in sentry that these native errors are occurring. 

There's not much information anywhere online and in the facebook/react-native repo, there's only one report here: https://github.com/facebook/react-native/issues/25565

Anyone know what this issue is?

**Comment by cruzach** [comment]
Could you provide more information from Sentry? any more of a stack trace or device info?

**Comment by lightninglu10** [comment]
Not sure if this gives enough info but here are some sentry stack traces: https://sentry.io/share/issue/232450ca401b483c8307a33bb828f901/

https://sentry.io/share/issue/03a9287c8bc24301aba972433ef28d46/

https://sentry.io/share/issue/6a4427754c2448f08fd940a5e7320dfd/

https://sentry.io/share/issue/62d52a39ab1f4b1cbb0e1b5bcbfb75df/
