### ISSUE TITLE
End-To-End Testing For Expo-enabled Apps

### ISSUE THREAD

**Issue by jackkinsella** [expo/expo#509]
I've been struggling to use Expo with end-to-end testing suites such as [Detox](https://github.com/wix/detox/). One of the main things holding me back is that there are currently no testIDs for the UI elements in the initial Expo screen rendered by [MenuView.js](https://github.com/expo/expo/blob/master/js/Menu/MenuView.js).

Adding testIDs would mean that testing suites that drive iOS/Android simulators would be able to easily find and dismiss the initial Expo screen and move on to testing the core code of each individual project.

I was wondering if you'd consider adding these hooks in the next release?

**Comment by jesseruder** [comment]
Want to submit a PR? Don't think we'll have time to get Detox set up to test but if you want to add the correct hooks we'll merge it.

**Comment by jackkinsella** [comment]
It's actually not necessary anymore - they've updated their own repos with helpers for testing expo: https://github.com/expo/detox-expo-helpers
