### ISSUE TITLE
[iOS] Camera barcode scanner often not working

### ISSUE THREAD

**Issue by sweebee** [expo/expo#5092]
### Environment

```
 Expo CLI 3.0.4 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.4
```
I'm using the expo client

### Steps to Reproduce

example snack: https://snack.expo.io/@sweebee/non-working-camer-scanner

if it works, try restarting the expo client. For me it works 1/10 times or so.

### Expected Behavior

always return callback when scanning barcode (onBarCodeScanned)

### Actual Behavior

onBarCodeScanned does not work while camera image works fine. It doesn work on my iPhone 5 (iOS 10) and iPhone 7 (iOS 13).

on my android test device it works fine (Nokia 5.1).

### Reproducible Demo

https://snack.expo.io/@sweebee/non-working-camer-scanner

https://www.youtube.com/watch?v=SDt5gft_yWg&feature=share

**Comment by sweebee** [comment]
The BarCodeScanner component works fine on iOS. but using default Camera with barcodescanned doesn't.

**Comment by sweebee** [comment]
what's the status of this issue?

**Comment by bbarthec** [comment]
I'm gonna take a look at this and eventually fix it by SDK35 release 🙂
