### ISSUE TITLE
[expo-camera] Execution failed for task ':expo-camera:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by michaelszerman-Ripio** [expo/expo#5094]
### Environment

Native Project ( started with: `react-native init` )
```
"react": "16.8.6",
"react-native": "0.60.4",
"react-native-unimodules": "^0.4.2",
"expo-camera": "^6.0.0",
```

### Steps to Reproduce

1. Create a new project: `react-native init`

2. Install React Native Unimodules following the steps in the repo:
[https://github.com/unimodules/react-native-unimodules/](https://github.com/unimodules/react-native-unimodules/)

3. Install expo-camera following the steps in the repo:
[https://github.com/expo/expo/tree/master/packages/expo-camera](https://github.com/expo/expo/tree/master/packages/expo-camera)

4. Try to run the application in Android or IOS: `react-native run-android | react-native run-ios.`

### Expected Behavior

Application compiled correctly without errors and with expo-camera installed.

### Actual Behavior

When you compile the applications is throws error in both Android & IOS.

### Link to Log Error

https://docs.google.com/document/d/1FoijYSv7_IkfKaKaU9Kjjv7OS9SEFdAzCCl5X27JNR0/edit?usp=sharing

**Comment by cruzach** [comment]
Could you try this with
```
"react": "16.8.3",
"react-native": "0.59.8",
```

**Comment by michaelszerman-Ripio** [comment]
> Could you try this with
> 
> ```
> "react": "16.8.3",
> "react-native": "0.59.8",
> ```

I will try with this version but it would be awesome if the bug would be fix for react-native@0.60.4 .

Btw I added the Log Error.

**Comment by cruzach** [comment]
> but it would be really helpful if the bug would be fix for react-native@0.60.4 

Right now, it's best to use unimodules with the version of `react-native` used in the most recent Expo SDK, which is `0.59.8` at the moment. Ymmv for the time being when it comes to using versions much newer/older

**Comment by michaelszerman-Ripio** [comment]
With react-native@0.59.8 it works. What you say makes sense, I may downgrade my project to 0.59.X . Do you know when expo will work smoothly with react-native@0.60.X ?

**Comment by cruzach** [comment]
It would be in a future SDK release, although I can't definitively say which or how soon

**Comment by cruzach** [comment]
We will be upgrading to RN .61 in the next SDK release, within the next few weeks 👍
