### ISSUE TITLE
MapView doesn't work in ExpoKit 33

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#5095]
Environment

Expo CLI 3.0.2 environment info:
System:
OS: macOS 10.14.5
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - /usr/local/bin/node
Yarn: 1.12.3 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.4 AI-183.6156.11.34.5692245
Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
npmPackages:
expo: ^33.0.0 => 33.0.7
react: 16.8.3 => 16.8.3
react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
react-navigation: ^3.2.1 => 3.2.1
npmGlobalPackages:
expo-cli: 3.0.2

ExpoKit Android

Steps to Reproduce

Upgrade ExpoKit SDK from 32 to 33
Change MapView from expo to react-native-maps

Expected Behavior
Map works 

Actual Behavior
Map doesn't work 

Related issue: https://github.com/react-native-community/react-native-maps/issues/2778

It seems that it wouldn't work with react-native 0.59.2. When will be support in expoKit for react-native 0.60 ?

**Comment by edoantonioco** [comment]
did you follow this? https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android

**Comment by theZulqarnain** [comment]
i'm facing same problem in expo 34

**Comment by Ansari-Tech** [comment]
I am also experiencing this on expo 34, it's broken my whole project which unfortunately relies on expo 34-specific features so I cannot roll back.

Is there a workaround for this?

I get a warning when loading my project: `Accessing view manager configs directly off UIManager via UIManager['AIRGoogleMap'] is no longer supported. Use UIManager.getViewManagerConfig['AIRGoogleMap']`

When navigating to the page that uses react native maps, I get the following error:
`TypeError: undefined is not an object (evaluating '_reactNativeMaps.MapView.Marker')

This error is located at:
    in Projects (created by SceneView)
    in SceneView (at StackViewLayout.js:795)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.js:69)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:57)
    in Card (at createPointerEventsContainer.js:27)
    in Container (at StackViewLayout.js:860)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:311)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.js:307)
    in Handler (at StackViewLayout.js:300)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:79)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:214)
    in Transitioner (at StackView.js:22)
    in StackView (created by Navigator)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:388)
    in NavigationContainer (at App.js:118)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:182388:73
render
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:182387:36
finishClassComponent
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:19614:43
updateClassComponent
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:19577:50
performUnitOfWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23734:27
workLoop
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23768:47
renderRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23834:21
performWorkOnRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24572:23
performWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24499:30
performSyncWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24475:20
requestWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24373:26
scheduleWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24246:22
enqueueSetState
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:16499:23
setState
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:7794:37
componentWillMount$
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:182320:30
tryCatch
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:26421:23
invoke
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:26596:32
tryCatch
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:26421:23
invoke
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:26497:30
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:26507:21
tryCallOne
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3747:16
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3848:27
_callTimer
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28259:17
_callImmediatesPass
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28295:19
callImmediates
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28514:33
__callImmediates
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3149:35
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2970:34
__guard
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3132:15
flushedQueue
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2969:21
`

**Comment by Ansari-Tech** [comment]
I seem to have fixed this.

Funnily enough, this problem was fixed by changing
`import {MapView} from "react-native-maps";`
to 
`import MapView from "react-native-maps";`

**Comment by cruzach** [comment]
@Luckygirlllll did changing your import syntax fix the problem for you? Support for RN 0.60 will come in SDK 36
