### ISSUE TITLE
all app will crash when you fetch this api

### ISSUE THREAD

**Issue by craigcosmo** [expo/expo#5096]
### Environment

Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.6.1 
    npmGlobalPackages:
      expo-cli: 2.21.1

### Steps to Reproduce

Just call this api in any of your app, you can init a brand new expo app and call it as welll

```js
let query = await fetch(
	'https://cloud.vegasegamingclub.com/api/booking/3' ,
	{
		method: 'PUT',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({id:3}),
	}
)
```
### Expected Behavior

app not crash

### Actual Behavior

app crashes

**Comment by cruzach** [comment]
Just tried this on a blank Expo project, both SDK 32 and SDK 33, and didn't see a crash. There's most likely something else causing the crash, I suggest digging into the device logs to get more info

**Comment by craigcosmo** [comment]
yes, tested it again in other device. it won't crash
