### ISSUE TITLE
Inconsistency with when onEnd prop is called for video

### ISSUE THREAD

**Issue by samwise00** [expo/expo#51]
When passing in the onEnd prop: 

If video playback has already reached the end of the video, exiting fullscreen mode will trigger the onEnd event a second time (it already fired once when the playback reached the end).

If video playback has NOT reached the end of the video, exiting fullscreen mode will not trigger onEnd event

Exiting fullscreen should either always invoke onEnd, or never invoke onEnd.

**Comment by gkufera** [comment]
Hi @samwise00!

We just did a revamp of the `Video` component in SDK17, and this behavior should be gone. We actually do not include an `onEnd` prop anymore, and this functionality has been consumed by the `callback` prop. See the [docs](https://docs.expo.io/versions/v17.0.0/sdk/video.html) for more info on the new API.

Thanks!
