### ISSUE TITLE
Font.loadAsync not working after sdk 34 update.

### ISSUE THREAD

**Issue by alialaa** [expo/expo#5100]
Hello, I had an app that loads some custom fonts and it was working properly until I updated to sdk 34. I now get this error:
```
fontFamily "manrope-regular" is not a system font and has not been loaded through Font.loadAsync.
```

Here's my code:
```
export default function App() {
    const [isReady, setIsReady] = useState(false);

    const _cacheSplashResourcesAsync = () => {
        return Font.loadAsync({
            "manrope-regular": require("@assets/fonts/manrope-regular.otf"),
            "manrope-medium": require("@assets/fonts/manrope-medium.otf"),
            "manrope-light": require("@assets/fonts/manrope-light.otf"),
            "manrope-bold": require("@assets/fonts/manrope-bold.otf"),
            "manrope-semibold": require("@assets/fonts/manrope-semibold.otf"),
            "manrope-extrabold": require("@assets/fonts/manrope-extrabold.otf")
        });
    };

    if (!isReady) {
        return (
            <AppLoading
                startAsync={_cacheSplashResourcesAsync}
                onFinish={() => {
                    setIsReady(true);
                }}
                autoHideSplash={false}
            />
        );
    }
    return (
        <Provider store={store}>
            <StatusBar barStyle="light-content" />
            <AppContent />
        </Provider>
    );
}
```
I don't think I am doing something wrong because as I said it was working before the update. Did that happen to anybody?

**Comment by alialaa** [comment]
I tried on a blank project and it worked so I must have something wrong in my project. Sorry!

**Comment by MindFreeze** [comment]
I also have this issue after updating to 34. There seems to be some breaking change that is not documented.

**Comment by alialaa** [comment]
Ok I will reopen the issue, it worked for me in a blank project but I can't seem to find any problem in my old code

**Comment by sweebee** [comment]
Looks the same as the issue i found. The icons in the expo client are working fine. But in the build one all my icons are squares with questionmarks in it.

**Comment by cruzach** [comment]
Could someone provide a repro? There seems to be differing reports. Is this in the Expo Client, or in a standalone app? iOS, Android, or both?

**Comment by sweebee** [comment]
For me the icons don’t work on standalone iOS build. In the expo client and standalone android it works fine.

**Comment by MindFreeze** [comment]
Expo client, Android. Haven't tried iOS or standalone.
Can't provide a repro beyond what alialaa already posted. It seems to work on a fresh expo app but not in my project, even with the exact same code.
`Font.loadAsync` is resolved but later the font is not found.
I tried delaying the render for 10 secs to give the fonts time to load in case it was a race condition but the font was still missing.

**Comment by cruzach** [comment]
There was an update to `expo-font` just recently, [due to this issue](https://github.com/expo/expo/issues/5110) which seems to be the same as the one most of your are having, so could you try updating `expo-font` or `expo`? (Brent says the specific versions in that issue)

**Comment by athenawisdoms** [comment]
The solution of updating `expo` worked for me [in this issue](https://github.com/expo/expo/issues/5110).

**Comment by MindFreeze** [comment]
Updating to `expo@34.0.3` and `expo-font@6.0.1` fixed it. I think we can close this now.

**Comment by sweebee** [comment]
Also worked for me.

**Comment by alialaa** [comment]
Worked for me

**Comment by knightkiddo** [comment]
I upgraded to `expo@34.0.3` and `expo-font@6.0.1 ` ... still have the issue :
`
fontFamily "markpro-bold" is not a system font and has not been loaded through Font.loadAsync.
`

Any idea ?

**Comment by alialaa** [comment]
Maybe you need to clear the cache. Did you try expo start -c?

**Comment by knightkiddo** [comment]
Yes. Many times.. maybe I have something wrong in my code but it worked before upgrading to SDK 34...

Here my code : 

```
import React, {Component}  from 'react';
import {
  AsyncStorage,
  Image,
  StyleSheet,
  View
} from 'react-native';

import { AppLoading } from 'expo';
import * as Font from 'expo-font';
import { withNavigation } from 'react-navigation';

class Loading extends Component {

  static navigationOptions = {
    header: null
  }

  state = {
    userToken: '',
    isLogged: false,
    isReady: false,
    loadingImage: require('assets/images/loading/loader.gif')
  }

  componentDidMount = async () => {

    let userToken = await AsyncStorage.getItem('userToken');

    this.setState({ userToken })
  }

  _cacheResourcesAsync = () => {

    return Font.loadAsync({
      'markpro': require('assets/fonts/MarkPro.ttf'),
      'markpro-medium': require('assets/fonts/MarkPro-Medium.ttf'),
      'markpro-bold': require('assets/fonts/MarkPro-Bold.ttf'),
      'markpro-black': require('assets/fonts/MarkPro-Black.ttf')
    }, () => {
      this.setState({isReady: true})
    });
  }

  render() {
    const {isReady, loadingImage, userToken} = this.state;

    if (!isReady) {
      return (
        <AppLoading
          startAsync={this._cacheResourcesAsync}
          onFinish={() => this.props.navigation.navigate(userToken ? 'Main' : 'Start')}
          onError={console.warn}
        />
      );
    }

    return (
      <View style={styles.container}>
        <Image source={loadingImage} style={{width: 400, height: 400}} />
      </View>
    )
    
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
    alignItems: "center",
    justifyContent: "center"
  },
  loadingImage: {
    width: 400,
    height: 400
  },
});

export default withNavigation(Loading);
```
Am I missing something ? Thank you!

**Comment by NiclasEricsson** [comment]
Same here, I've updated to the version numbers above in package.json but it still throws that error message at me. I've cleared the cache, tried simulator and real device but nothing seems to work. My current dependencies look like this:

`"dependencies": {
    "@expo/vector-icons": "^10.0.2",
    "ex-react-native-i18n": "0.0.6",
    "expo": "^34.0.3",
    "expo-font": "^6.0.1",
    "expo-localization": "^6.0.0",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-calendars": "^1.22.0",
    "react-native-gesture-handler": "^1.2.2",
    "react-native-reanimated": "^1.0.1",
    "react-navigation": "^3.11.1",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  }`

**Comment by brentvatne** [comment]
let's discuss in https://github.com/expo/expo/issues/5126
