### ISSUE TITLE
expo-constants:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by beibars1396** [expo/expo#5101]
error: package android.support.annotation does not exist

in:

node_modules/expo-constants/android/src/main/java 

```
/Users/ushbaybeibars1/Documents/GitHub/platform-rn/node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java:6: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;

/Users/user/Documents/GitHub/project/node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java:51: error: cannot find symbol
  @Nullable
   ^
  symbol:   class Nullable
  location: class ConstantsService
2 errors

```
my app build.gradle: 

```
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.bmintegrityapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    androidImplementation "com.android.support:support-annotations:28.0.0"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-svg')
    addUnimodulesDependencies()
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

Any ideas? 

Many thanks

**Comment by cruzach** [comment]
Hey @beibars1396 - in order to help you, we'll need you to go back and fill out the entire issue template. That way we have all the info we need 👍

**Comment by beibars1396** [comment]
Hey @cruzach 
I was trying to run the app on Android. On IOS it was Ok. I changed the line 

import android.support.annotation.Nullable; 

to 

import androidx.annotation.Nullable;

It’s building now but I still got some feelings that I’m doing something wrong

**Comment by Rizaldinurm** [comment]
I have some familiar error,

./node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java:6: error: cannot find symbol
import androidx.annotation.Nullable;

./node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java:51: error: cannot find symbol

* What went wrong:
Execution failed for task ':expo-constants:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

In Ios work well, but in android I get an error like that.

**Comment by beibars1396** [comment]
@Rizaldinurm hi
I found the solution by using Jetifier https://www.npmjs.com/package/jetifier
Hope it will resolve your problem too.

**Comment by iamstr** [comment]
> @Rizaldinurm hi
> I found the solution by using Jetifier https://www.npmjs.com/package/jetifier
> Hope it will resolve your problem too.

this works magics

**Comment by glittle** [comment]
I've added Jetifier and it did not solve the issue.

Logs show lines like:

> Transform react-native.aar (com.facebook.react:react-native:0.59.10) with JetifyTransform

but still have:

> Task :expo-constants:compileDebugJavaWithJavac FAILED
/Users/vsts/agent/2.158.0/work/1/s/node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java:8: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/vsts/agent/2.158.0/work/1/s/node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java:56: error: cannot find symbol
  @Nullable
   ^
  symbol:   class Nullable
  location: class ConstantsService
Note: /Users/vsts/agent/2.158.0/work/1/s/node_modules/expo-constants/android/src/main/java/expo/modules/constants/ConstantsService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

> FAILURE: Build failed with an exception.

> * What went wrong:
Execution failed for task ':expo-constants:compileDebugJavaWithJavac'.

**Comment by ZenitH-AT** [comment]
I tried using jetify but now 
```package android.support.v7.app does not exist
import android.support.v7.app.AppCompatActivity;```

**Comment by mama00** [comment]
jetifier   worked thx

**Comment by WickedBrat** [comment]
jetifier doesn't seem to be working for me

**Comment by iamstr** [comment]
delete  the build directory
``` 
cd android && ./gradlew clean
```

then return to the root of your project and run

``` 
npx jetify

npx react-native run-android
```

your app should correctly compile and work

**Comment by aliwaqar981** [comment]
I tried as @iamstr said but problem doesn't seems to be resolved. Any other solution!!

**Comment by iamstr** [comment]
> I tried as @iamstr said but problem doesn't seems to be resolved. Any other solution!!
try clearing  your cache 

```npm cache clean ```

**Comment by o-pooja-o** [comment]
nothing wordked till now

**Comment by santiagomarcano** [comment]
Any more solutions???

**Comment by bionara** [comment]
Having issues with this also
