### ISSUE TITLE
Notifications.getExpoPushTokenAsync() breaks without error

### ISSUE THREAD

**Issue by PiotrSzlagura** [expo/expo#5103]
### Environment

```
 Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.0.6
```

Target: iOS, Android

### Steps to Reproduce

Call `Notifications.getExpoPushTokenAsync()` as it is shown in example at expo.io

### Expected Behavior

`Notifications.getExpoPushTokenAsync()` should return valid exponent notification token.

### Actual Behavior

`Notifications.getExpoPushTokenAsync()` breaks function call.

### Reproducible Demo

Here's my code, which is in 99% copied from example on expo.io guide (I have only added redux action to store token in back-end):

```
  async registerForPushNotificationsAsync() {
    const {
      userID,
      registerForPushNotifications: executeRegisterForPushNotifications
    } = this.props;

    const { status: existingStatus } = await Permissions.getAsync(
      Permissions.NOTIFICATIONS
    );
    let finalStatus = existingStatus;

    if (existingStatus !== "granted") {
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;
    }

    if (finalStatus !== "granted") {
      return;
    }

    // Before this line, everything is OK
    let token = await Notifications.getExpoPushTokenAsync();
    // It doesn't get to this line

    executeRegisterForPushNotifications(userID, token);
  }
```

`finalStatus` is always `"granted"`, checked it multiple times.

When it gets to `await Notifications.getExpoPushTokenAsync();` the function breaks. I tried wrapping it in `try/catch`, also i tried it like this:

```
Notifications.getExpoPushTokenAsync()
	.then(token => {
		console.log("success");
		executeRegisterForPushNotifications(userID, token);
	})
	.catch(error => {
		console.log("failure");
		console.log(error);
	})
```

In the example above, neither `success` nor `failure` log was present. Has anyone got any idea what am I doing wrong?

**Comment by PiotrSzlagura** [comment]
Also, when I run the project using `expo start` it works without problems. This problem occurs when I build apk using `expo build:android`. After installing it and running on device (Samsung Galaxy j3 6), it doesn't work. On iOS build this code also doesn't work, I assume it's for the same reason.

**Comment by cruzach** [comment]
Have you already [set up your project for FCM](https://docs.expo.io/versions/latest/guides/using-fcm/)? Since this is only happening in standalone builds, I'd imagine it has something to do with your app's credentials or permissions

**Comment by PiotrSzlagura** [comment]
You're right, I missed this step earlier. I have added it now and it generates expo push token without problems. Thank you very much!

I have one more question though, when we sent our first build for testing, a few tokens landed in our back-end, which indicates that they were generating, even though there was no FCM configured. Have you got any idea how was that possible?

**Comment by cruzach** [comment]
Probably from iOS devices, since those don't require FCM configuration

**Comment by PiotrSzlagura** [comment]
They were certainly from Android, as we differ them and they end up in different places in database. From iOS I couldn't get any token yet, probably because I didn't set up push certificate for iOS yet.
