### ISSUE TITLE
Unable to resolve "react-native-gesture-handler" Expo SDK 34.0.1

### ISSUE THREAD

**Issue by sauzy34** [expo/expo#5107]
### Unable to resolve "react-native-gesture-handler" from "node_modules\@react-navigation\native\src\Scrollables.js"

My `package.json` looks like this: 
```
{
  "name": "nativeapp",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^10.0.0",
    "axios": "^0.19.0",
    "expo": "^34.0.1",
    "expo-asset": "~6.0.0",
    "expo-font": "~6.0.0",
    "formik": "^1.5.8",
    "lodash": "^4.17.15",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-svg": "~9.5.1",
    "react-navigation": "^3.11.0",
    "styled-components": "^4.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-eslint": "^10.0.2",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-expo": "^5.2.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-config-react-app": "^3.0.8",
    "eslint-plugin-flowtype": "^3.12.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "jest-expo": "^34.0.0",
    "prettier": "^1.18.2"
  }
}
```

**Comment by sweebee** [comment]
```npm i -s react-native-gesture-handler``` worked for me.

**Comment by diegorodriguesvieira** [comment]
`expo install react-native-gesture-handler` worked for me too...

**Comment by EtienneBourque** [comment]
Indeed, I upgraded to SDK 34 yesterday before the blog post and I noticed that `expo-*` modules didn't resolved automatically like in 33.

Now, per the blog post, we are now required as @diegorodriguesvieira suggested to run `expo install` for each expo module, paving the way I guess to smaller builds if the whole expo package is not included by default anymore.

**Comment by Srini-B** [comment]
npx expo-codemod sdk33-imports '**/*.js' '**/*.{ts,tsx}' fixed it

**Comment by EtienneBourque** [comment]
> `npx expo-codemod sdk33-imports '**/*.js' '**/*.{ts,tsx}'` fixed it

The codemod changes the old imports pre SDK 32 module to the new ones post SDK 33, but it won't add them in package.json to be installed by npm as required by some of them since SDK 34.

I was finding it odd that some of them must be installed separately while some others are not. That said, using `npm info`, I see that those not needing to be installed via `expo install` are listed as dependencies of the npm expo package.

As mentioned in the documentation, I will nonetheless `expo install` those I required since the expo dependencies could change in the future.

**Comment by ide** [comment]
The codemod just rewrites your imports and does not run `expo install` for you, but IIRC it will print out an `expo install` command that you can run yourself.

>As mentioned in the documentation, I will nonetheless expo install those I required since the expo dependencies could change in the future.

This is a good idea :)

**Comment by tsapeta** [comment]
As mentioned earlier, installing `react-native-gesture-handler` is the solution and the proper way to do this is `expo install react-native-gesture-handler` which installs the version that is supported by the SDK you're using.

**Comment by isoume** [comment]
Hello I am a beginer in react native.

Now i am trying to use the react-navigation, more precisely the TabNavigator.

It sow me the error 
Unable to resolve "react-native-gesture-handler" from "node_modules\@react-navigation\native\src\Scrollables.js"

Please i need a help

**Comment by EtienneBourque** [comment]
> It sow me the error
> Unable to resolve "react-native-gesture-handler" from "node_modules@react-navigation\native\src\Scrollables.js"

Did you run this command?  `expo install react-native-gesture-handler`
It is now necessary since Expo 34 since it's not included by default in the Expo install.

**Comment by Slapbox** [comment]
I'm suddenly seeing this message again, but my `package.json` and my `node_modules` both contain `react-native-gesture-handler@1.3.0`

**Comment by samipshah100** [comment]
> I'm suddenly seeing this message again, but my `package.json` and my `node_modules` both contain `react-native-gesture-handler@1.3.0`

same here. happening after i upgraded to sdk 35.

**Comment by webwarrior** [comment]
I am facing the same problem - nothing works so far even after clearing the cache

**Comment by eddiesmag** [comment]
hey guys. This is how i resoled it.

- Remove/uninstall that `react-native-gesture-handler`

- Then install it again with expo, run `expo install react-native-gesture-handler`

other solutions, downgrade `expo install react-native-gesture-handler` to `~1.3.0`. take note of `~1.3.0`.

**Comment by isoume** [comment]
Hello  Smag thanks for this help that work for me.

That's the same solution with createMaterialBottomTabNavigator ?

**Comment by Enkumicahel** [comment]
I did what @eddiesmag said but wasn't sufficient enough to make it work. But, then I deleted the node_modules folder and run **npm install** again, and it worked. Thank you @eddiesmag
