### ISSUE TITLE
Unable to resolve "./Google" from "node_modules/expo/build/ExpoLazy.js"

### ISSUE THREAD

**Issue by philip-dakno** [expo/expo#5112]
### Environment

Expo CLI 3.0.6 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19.1 (Tessa)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.1 - /home/plwrenn/bin/watchman
    npmPackages:
      expo: ^34.0.1 => 34.0.2 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.6

Target: Android

### Steps to Reproduce

`npm run android` after upgrade from Expo 33 to Expo 34

### Expected Behavior

Android app to start.

### Actual Behavior

Development server returns 500 error. 

Unable to resolve "./Google" from "node_modules/expo/build/ExpoLazy.js"

This issue seems similar to what was described in #4956, but it seems it was closed because they didn't want to address the issue prior to SDK 34 actually going live.

**Comment by brentvatne** [comment]
can you try `expo start -c`? there is no import of './Google' in `build/ExpoLazy.js`

```
Object.defineProperty(exports, "Google", {
  enumerable: true,
  get: function () {
    return _removed.Google;
  }
});
```

**Comment by philip-dakno** [comment]
That fixed it. Thanks!

**Comment by changLiuUNSW** [comment]
@brentvatne  Do we have a fix for this now?  since expo 34 is live now but the issue still exists

**Comment by philip-dakno** [comment]
@changLiuUNSW For me at least, the fix was clearing the React Native packager cache as @brentvatne suggested. Did you try that?
