### ISSUE TITLE
Two different app versions appear intertwined in final bundle

### ISSUE THREAD

**Issue by davidgithub1980** [expo/expo#5116]
Hi. I am experiencing a strange issue after upgrading my app version from **v9** to **v10** inside **app.json**. My current **app.json** version 10 is defined as follows (it is only a short extract):

```
{
  "expo": {
    "name": "MyApp",
    "description": "My App",
    "slug": "my-app",
    "privacy": "public",
    "sdkVersion": "33.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "0.1.0",
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "com.mall.myapp"
    },
    "android": {
      "package": "com.mall.myapp",
      "versionCode": 10,
    }
  }
}
```

I build the app via _expo build:andorid_. The process completes successfully.

Whenever I launch my app, there is only a **blank white screen** and nothing happens. I have to enter the Android app manager to **clear the app cache and storage**. It then starts successfully but another strange thing happens. I have a log inside my **App.js** to let me know of the currently installed version. The strange thing is that when the app starts (after the cache clearance) the log is hit twice informing me that the used version is **both 9** (the first log hit) **and 10** (second log hit). There should be only one log hit informing me of using v10. I have even tried to uninstall the app from my Android device and reinstall it again but to no avail, i.e. both issues still prevail :-( I would like a hint as to what to do.

```
expo-cli 3.0.2
expo sdk 33
```

**Comment by cruzach** [comment]
Hey @davidgithub1980 - could you try [running `adb logcat`](https://docs.expo.io/versions/latest/workflow/logging/#view-logs-from-android-device-or-emulator) to get the device logs? Might provide some insight as to what's happening here in regards to the white screen

With `fallbackToCacheTimeout` set to `0`, your app should start immediately with a cached bundle while downloading a newer one in the background for future use (which would explain the version 9, then version 10 logs). Although, I'd have expected the newer bundle when installing the latest published bundle. I've seen a similar issue from a while back, and they said it was fixed after also incrementing the `version` value of `app.json`

**Comment by davidgithub1980** [comment]
Hi. the issue is happening for quite some time. Spaning across SDK 31, 32 and 33. When it comes to _app.json_, I always increase both the value of the **version** and the value of **android.versionCode** as well, but, unfortunately, I cannot make it go away :-( The log generates no error, just  a blank white screen that forces me to got to the app manager to clear cache and then, when launching the app, the already mentioned two log hits with two versions (9 and 10). This also happened when I moved from _v8_ to _v9_ (moving **android.versionCode** as well from _0.0.8_ to _0.0.9_).

**Comment by cruzach** [comment]
There are no logs at all when you first try to open the app?

Also- have you been publishing the app *after* building?

**Comment by davidgithub1980** [comment]
Things started working as normal after another app version upgrade (v10 -> v11). Do not know why previous attempts failed.
