### ISSUE TITLE
Websocket not found

### ISSUE THREAD

**Issue by pmpbar** [expo/expo#512]
Hello,
When initializing a websocket on a fresh app I get the following output: 
`Can't find variable: Websocket`
Using `macOS: 10.12.6, node: 8.4.0, npm: 4.6.1, exp: 43.0.0`
The project was set up using `$ exp init test`. My code looks like:
```javascript
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.ws = new Websocket('wss://myendpoint.com');
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```
Any help is much appreciated!

**Comment by jimmylee** [comment]
I believe all you need to do is to move `new Websocket('wss://myendpoint.com');` into `componentDidMount()`.

**Comment by pmpbar** [comment]
Still getting the error when I use `componentDidMount()`
package.json:
```
{
  "name": "test",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^19.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz"
  }
}
```

**Comment by jimmylee** [comment]
Sorry @pmpbar I noticed that the reference to `websocket` needs to be `WebSocket`

Here is a working example for you

```
import React from 'react';
import { View } from 'react-native';

export default class App extends React.Component {
  componentDidMount() {
    console.log(WebSocket);
  }

  render() {
    return (
      <View>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}
```

**Comment by pmpbar** [comment]
No problem, I actually did use the capital letter when I tried it, and got the same result.

**Comment by jimmylee** [comment]
Our `package.json` are both identical so this interesting... are you running your example from the simulator? or from your physical phone?

**Comment by pmpbar** [comment]
iPhone 7 using the expo app v1.18.0

**Comment by jimmylee** [comment]
Would you be willing to paste me an updated code example with the updated spelling so I can it out again on my end? I'm sorry you have to deal with this, must be frustrating.

**Comment by pmpbar** [comment]
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  componentDidMount() {
    this.ws = new Websocket('wss://echo.websocket.org');
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by jimmylee** [comment]
Your pasted example doesn't work because its `Websocket`, but if you change it to `WebSocket` it does work.

**Comment by pmpbar** [comment]
Welp! I am an idiot! Thank you so much. Delete this forever and may it never be seen again
