### ISSUE TITLE
Error while compiling iOS Expo 2.12.1

### ISSUE THREAD

**Issue by atiato78** [expo/expo#5122]
Dears,

While compiling Expo iOS 2.12.1 on Xcode I'm getting the below error 👍 
I'm deploying it on my Iphone , my OS is Mac.

ld: warning: ignoring file /Users/omar/Downloads/expo-ios-2.12.1/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/omar/Downloads/expo-ios-2.12.1/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork
ld: warning: ignoring file /Users/omar/Downloads/expo-ios-2.12.1/ios/Pods/GoogleMobileVision/FaceDetector/Frameworks/FaceDetector.framework/FaceDetector, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/omar/Downloads/expo-ios-2.12.1/ios/Pods/GoogleMobileVision/FaceDetector/Frameworks/FaceDetector.framework/FaceDetector
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBAdOptionsView", referenced from:
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXAdOptionsViewManager.o)
      objc-class-ref in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXAdOptionsViewManager.o)
      objc-class-ref in libEXAdsFacebook.a(EXAdOptionsViewManager.o)
  "_OBJC_CLASS_$_FBAdSettings", referenced from:
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXAdSettingsManager.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXAdSettingsManager.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXAdSettingsManager.o)
      objc-class-ref in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXAdSettingsManager.o)
      objc-class-ref in libEXAdsFacebook.a(EXAdSettingsManager.o)
  "_OBJC_CLASS_$_FBAdView", referenced from:
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXBannerView.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXBannerView.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXBannerView.o)
      objc-class-ref in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXBannerView.o)
      objc-class-ref in libEXAdsFacebook.a(EXBannerView.o)
  "_kFBAdSizeHeight250Rectangle", referenced from:
      -[ABI31_0_0EXBannerView fbAdSizeForHeight:] in libABI31_0_0ExpoKit.a(ABI31_0_0EXBannerView.o)
      -[ABI32_0_0EXBannerView fbAdSizeForHeight:] in libABI32_0_0ExpoKit.a(ABI32_0_0EXBannerView.o)
      -[ABI33_0_0EXBannerView fbAdSizeForHeight:] in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXBannerView.o)
      -[ABI34_0_0EXBannerView fbAdSizeForHeight:] in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXBannerView.o)
      -[EXBannerView fbAdSizeForHeight:] in libEXAdsFacebook.a(EXBannerView.o)
  "_OBJC_CLASS_$_FBInterstitialAd", referenced from:
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXInterstitialAdManager.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXInterstitialAdManager.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXInterstitialAdManager.o)
      objc-class-ref in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXInterstitialAdManager.o)
      objc-class-ref in libEXAdsFacebook.a(EXInterstitialAdManager.o)
  "_OBJC_CLASS_$_FBNativeAdsManager", referenced from:
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXNativeAdManager.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXNativeAdManager.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXNativeAdManager.o)
      objc-class-ref in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXNativeAdManager.o)
      objc-class-ref in libEXAdsFacebook.a(EXNativeAdManager.o)
  "_kFBAdSizeHeight90Banner", referenced from:
      -[ABI31_0_0EXBannerView fbAdSizeForHeight:] in libABI31_0_0ExpoKit.a(ABI31_0_0EXBannerView.o)
      -[ABI32_0_0EXBannerView fbAdSizeForHeight:] in libABI32_0_0ExpoKit.a(ABI32_0_0EXBannerView.o)
      -[ABI33_0_0EXBannerView fbAdSizeForHeight:] in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXBannerView.o)
      -[ABI34_0_0EXBannerView fbAdSizeForHeight:] in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXBannerView.o)
      -[EXBannerView fbAdSizeForHeight:] in libEXAdsFacebook.a(EXBannerView.o)
  "_OBJC_CLASS_$_FBAdIconView", referenced from:
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXAdIconViewManager.o)
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXNativeAdManager.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXNativeAdManager.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXAdIconViewManager.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXAdIconViewManager.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXNativeAdManager.o)
      objc-class-ref in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXAdIconViewManager.o)
      ...
  "_kFBAdSizeHeight50Banner", referenced from:
      -[ABI31_0_0EXBannerView fbAdSizeForHeight:] in libABI31_0_0ExpoKit.a(ABI31_0_0EXBannerView.o)
      -[ABI32_0_0EXBannerView fbAdSizeForHeight:] in libABI32_0_0ExpoKit.a(ABI32_0_0EXBannerView.o)
      -[ABI33_0_0EXBannerView fbAdSizeForHeight:] in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXBannerView.o)
      -[ABI34_0_0EXBannerView fbAdSizeForHeight:] in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXBannerView.o)
      -[EXBannerView fbAdSizeForHeight:] in libEXAdsFacebook.a(EXBannerView.o)
  "_OBJC_CLASS_$_FBMediaView", referenced from:
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXNativeMediaViewManager.o)
      objc-class-ref in libABI31_0_0ExpoKit.a(ABI31_0_0EXNativeAdManager.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXNativeAdManager.o)
      objc-class-ref in libABI32_0_0ExpoKit.a(ABI32_0_0EXNativeMediaViewManager.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXNativeAdManager.o)
      objc-class-ref in libABI33_0_0EXAdsFacebook.a(ABI33_0_0EXNativeMediaViewManager.o)
      objc-class-ref in libABI34_0_0EXAdsFacebook.a(ABI34_0_0EXNativeAdManager.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cruzach** [comment]
Hi @atiato78 - what is that you're trying to do? If you're trying to develop apps with Expo, take a look at our [walkthrough guide](https://docs.expo.io/versions/v34.0.0/workflow/exploring-managed-workflow/). If all you need is to download the Expo Client app on your device, you can get it directly from the app store.

If, on the other hand, you're trying to build the iOS Client code from source, let me know

**Comment by atiato78** [comment]
@cruzach I'm trying to build the client from sources , I need to get the benifit of rich content feature added with version 2.12.1
Do you have guide ? do we have to use pod install for example ?

**Comment by cruzach** [comment]
Guide is [here](https://github.com/expo/expo#introduction)

**Comment by atiato78** [comment]
I used this guide before now I'm getting 

atiato~/Downloads/expo-ios-2.12.1$ et ios-generate-dynamic-macros
You don't have access to decrypted secrets. Falling back to `template-files/keys.json`.
Resolving macros...
Resolved TEST_APP_URI macro to ""
Resolved TEST_CONFIG macro to ""
Resolved TEST_SERVER_URL macro to "TODO"
Resolved TEST_RUN_ID macro to "cc8bd391-2451-4d15-a9f9-1f402683e099"
Resolved BUILD_MACHINE_LOCAL_HOSTNAME macro to "atiato.local"
Resolved DEV_PUBLISHED_KERNEL_MANIFEST macro to "{\"android\":{\"package\":\"host.exp.exponent\"},\"dependencies\":[\"@expo/react-native-action-sheet\",\"@expo/react-native-touchable-native-feedback-safe\",\"@react-navigation/web\",\"apollo-boost\",\"apollo-cache-inmemory\",\"dedent\",\"es6-error\",\"expo\",\"expo-analytics-amplitude\",\"expo-asset\",\"expo-barcode-scanner\",\"expo-blur\",\"expo-camera\",\"expo-constants\",\"expo-font\",\"expo-linear-gradient\",\"expo-location\",\"expo-permissions\",\"expo-task-manager\",\"expo-web-browser\",\"graphql\",\"graphql-tag\",\"immutable\",\"lodash\",\"prop-types\",\"querystring\",\"react\",\"react-apollo\",\"react-native\",\"react-native-fade-in-image\",\"react-native-gesture-handler\",\"react-native-infinite-scroll-view\",\"react-native-maps\",\"react-navigation\",\"react-navigation-material-bottom-tabs\",\"react-redux\",\"redux\",\"redux-thunk\",\"semver\",\"sha1\",\"url\"],\"description\":\"\",\"extra\":{\"amplitudeApiKey\":\"081e5ec53f869b440b225d5e40ec73f9\"},\"icon\":\"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png\",\"iconUrl\":\"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png\",\"ios\":{\"bundleIdentifier\":\"host.exp.exponent\",\"supportsTablet\":true},\"locales\":{},\"name\":\"expo-home\",\"orientation\":\"portrait\",\"packagerOpts\":{\"config\":\"metro.config.js\"},\"platforms\":[\"ios\",\"android\"],\"primaryColor\":\"#cccccc\",\"privacy\":\"unlisted\",\"scheme\":\"exp\",\"sdkVersion\":\"UNVERSIONED\",\"slug\":\"expo-home-dev-f03fd6e8d77993e3670ca9a4789f3ae8051bc8f1\",\"updates\":{\"checkAutomatically\":\"ON_LOAD\",\"fallbackToCacheTimeout\":0},\"version\":\"34.0.0\",\"id\":\"@expo-home-dev/expo-home-dev-f03fd6e8d77993e3670ca9a4789f3ae8051bc8f1\",\"revisionId\":\"34.0.0-r.jp58X5pg1m\",\"publishedTime\":\"2019-07-16T06:07:29.461Z\",\"commitTime\":\"2019-07-16T06:07:29.505Z\",\"bundleUrl\":\"https://d1wp6m56sqw74a.cloudfront.net/%40expo-home-dev%2Fexpo-home-dev-f03fd6e8d77993e3670ca9a4789f3ae8051bc8f1%2F34.0.0%2F595f7fc5c11db3c3d8ae09f3bd2344ec-34.0.0-ios.js\",\"releaseChannel\":\"default\",\"hostUri\":\"expo.io/@expo-home-dev/expo-home-dev-f03fd6e8d77993e3670ca9a4789f3ae8051bc8f1\"}"
Unable to generate manifest from home: Failed to fetch manifest from exp://172.20.10.3:80
Resolved BUILD_MACHINE_KERNEL_MANIFEST macro to ""
Resolved TEMPORARY_SDK_VERSION macro to "34.0.0"
Resolved INITIAL_URL macro to null

Modifying Info.plist at ios/Exponent/Supporting/Info.plist ...
Generating build config ios/Exponent/Supporting/EXBuildConstants.plist ...
Rendering ios/Podfile from template template-files/ios/Podfile ...
Rendering ExpoKit.podspec from template template-files/ios/ExpoKit.podspec ...
Rendering exponent-view-template/ios/Podfile from template template-files/ios/ExpoKit-Podfile ...
atiato~/Downloads/expo-ios-2.12.1$

**Comment by atiato78** [comment]
I found this as Failed to build the client:
https://circleci.com/gh/expo/expo/73387

**Comment by atiato78** [comment]
Success!
After pod install I'm facing the below while running expo client on my iOS mobile
Google App ID needs to be newly configured and not using github ID.

2019-08-01 11:06:24.123391+0300 Exponent[2706:1633619] [DYMTLInitPlatform] platform initialization successful
2019-08-01 11:06:24.837584+0300 Exponent[2706:1633633]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2019-08-01 11:06:24.921469+0300 Exponent[2706:1633449] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2019-08-01 11:06:24.926728+0300 Exponent[2706:1633449] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-08-01 11:06:24.927471+0300 Exponent[2706:1633449] [MC] Reading from public effective user settings.
2019-08-01 11:06:24.936936+0300 Exponent[2706:1633449] [Crashlytics] Version 3.13.1 (140)
2019-08-01 11:06:24.937233+0300 Exponent[2706:1633639] 6.2.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2019-08-01 11:06:24.937509+0300 Exponent[2706:1633639] 6.2.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2019-08-01 11:06:24.970775+0300 Exponent[2706:1633449] *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'
*** First throw call stack:
(0x1d177127c 0x1d094b9f8 0x1d167b4b0 0x1031a7ab8 0x1031a7078 0x1031a6ae8 0x1031a6a14 0x1024f6bac 0x1fdf2ae30 0x1fdf2c594 0x1fdf31d20 0x1fd7f52dc 0x1fd7fd874 0x1fd7f4f60 0x1fd7f5850 0x1fd7f3b9c 0x1fd7f3864 0x1fd7f83a4 0x1fd7f9188 0x1fd7f825c 0x1fd7fcf5c 0x1fdf30328 0x1fdb2cba8 0x1d40ec9fc 0x1d40f640c 0x1d40f5c14 0x109a20c74 0x109a24840 0x1d4127040 0x1d4126cdc 0x1d4127294 0x1d1703018 0x1d1702f98 0x1d1702880 0x1d16fd7bc 0x1d16fd0b0 0x1d38fd79c 0x1fdf33978 0x1025f785c 0x1d11c28e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by atiato78** [comment]
Now after creating project on firebase and adding the GoogleService-Info.plist to the project.
<img width="1401" alt="Screen Shot 2019-08-01 at 12 19 22 PM" src="https://user-images.githubusercontent.com/40871759/62281679-e0032380-b456-11e9-8455-66a35b440063.png">

Now please tell me if I'm going to create notification project with rich content . should I update the expo client on Mac ! or the previous expo client will do the job and synch with my mobile app.
will try both case.

**Comment by atiato78** [comment]
Now I'm getting the below while sending notifications from postman .
<img width="1272" alt="Screen Shot 2019-08-01 at 1 01 17 PM" src="https://user-images.githubusercontent.com/40871759/62284682-c664da80-b45c-11e9-8d2b-4993742bf8a3.png">

my iOS expo client bundle identifier is host.exp.test and my expo react native app is @atiato78/notify how to link my expo client on my mobile app with the application and be able to get APN credentials ?
when running I'm using expo start and open the notify app on iOS expo client updated for rich content . 
Could you please help.

**Comment by atiato78** [comment]
@cruzach please help , how to enable notifications with my custom Expo iOS client?

**Comment by bessonette** [comment]
In case anyone else runs into this issue, what we had to was create a new Firebase App using host.exp.exponent as the Bundle ID. Then you can download the GoogleService-Info.plist file and save it to expo/template-files/ios. On our builds Xcode always picks up that file and replaces whatever is in iOS apps Supporting folder.

![image](https://user-images.githubusercontent.com/1441562/64456831-be7d0380-d0b6-11e9-850b-e0e212d9dab4.png)
