### ISSUE TITLE
app crashes on mapview page

### ISSUE THREAD

**Issue by abhinav-official** [expo/expo#5125]
Bug
When using MapView with react-native-maps in expo and building the app for production, the app restarts itself when navigated to the page calling MapView.

Environment info
React native info output:

   "dependencies": {
    "axios": "^0.18.1",
    "expo": "^32.0.0",
    "moment": "^2.24.0",
    "qs": "^6.7.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-counters": "0.0.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^1.1.0",
    "react-native-image-slider-show": "^1.0.3",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-maps": "^0.24.2",
    "react-native-paper": "^2.15.2",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-super-grid": "^3.0.8",
    "react-navigation": "^3.11.0"
  },
Library version:"^0.24.2" + "^0.25.0"

Steps To Reproduce
expo build:android
...

Describe what you expected to happen:

1.expected to work after building apk
2. works in development and on expo apps but not in production build

**Comment by cruzach** [comment]
Hey! There are some [extra steps to configure MapView in standalone apps](https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android), have you already worked through those?

**Comment by abhinav-official** [comment]
> Hey! There are some [extra steps to configure MapView in standalone apps](https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android), have you already worked through those?

not a standalone app its totally expo manged app.

**Comment by samisamsam** [comment]
I have the same issue its very annoying. Did you find a solution ?

**Comment by abhinav-official** [comment]
@samisamsam just follow this carefully
https://docs.expo.io/versions/v34.0.0/sdk/map-view/#deploying-to-a-standalone-app-on-android
