### ISSUE TITLE
Font.loadAsync does not work with SDK 34

### ISSUE THREAD

**Issue by knightkiddo** [expo/expo#5126]
### Environment

Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.10.1 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.6

### Steps to Reproduce

Hi ! Since I upgraded to SDK 34 I have this error with Font.loadAsync. It worked perfectly before with SDK 33 : 

`fontFamily "markpro-bold" is not a system font and has not been loaded through Font.loadAsync. `

### Expected Behavior

Load custom fonts and use react-navigation to go to the next screen.

### Actual Behavior

I get an error while trying to use AppLoading and custom font.

### Reproducible Demo

Here my code : 

```
import React, {Component}  from 'react';
import {
  AsyncStorage,
  Image,
  StyleSheet,
  View
} from 'react-native';

import { AppLoading } from 'expo';
import * as Font from 'expo-font';
import { withNavigation } from 'react-navigation';

class Loading extends Component {

  static navigationOptions = {
    header: null
  }

  state = {
    userToken: '',
    isLogged: false,
    isReady: false,
    loadingImage: require('assets/images/loading/loader.gif')
  }

  componentDidMount = async () => {

    let userToken = await AsyncStorage.getItem('userToken');

    this.setState({ userToken })
  }

  _cacheResourcesAsync = () => {

    return Font.loadAsync({
      'markpro': require('assets/fonts/MarkPro.ttf'),
      'markpro-medium': require('assets/fonts/MarkPro-Medium.ttf'),
      'markpro-bold': require('assets/fonts/MarkPro-Bold.ttf'),
      'markpro-black': require('assets/fonts/MarkPro-Black.ttf')
    }, () => {
      this.setState({isReady: true})
    });
  }

  render() {
    const {isReady, loadingImage, userToken} = this.state;

    if (!isReady) {
      return (
        <AppLoading
          startAsync={this._cacheResourcesAsync}
          onFinish={() => this.props.navigation.navigate(userToken ? 'Main' : 'Start')}
          onError={console.warn}
        />
      );
    }

    return (
      <View style={styles.container}>
        <Image source={loadingImage} style={{width: 400, height: 400}} />
      </View>
    )
    
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
    alignItems: "center",
    justifyContent: "center"
  },
  loadingImage: {
    width: 400,
    height: 400
  },
});

export default withNavigation(Loading);
```

If I'm missing something, please tell me, thank you !

**Comment by martintreurnicht** [comment]
Same here, i've been trying to figure it out for hours. Doesn't seem to affect android, seems like iOS only

**Comment by NiclasEricsson** [comment]
I'm also having this problem. Currently using expo-font@6.0.1 and expo@34.0.3, which I read somewhere should solve the issue, but I can't get it to work.

**Comment by martintreurnicht** [comment]
Duplicated of https://github.com/expo/expo/issues/5100
Fix for me by either upgrading:
expo >= `34.0.3`
expo-font >= `6.0.1`

**Comment by brentvatne** [comment]
@NiclasEricsson - can you try clearing node_modules and your lockfiles and reinstalling to ensure that you are getting the correct version of expo-font?

**Comment by brentvatne** [comment]
if you have this issue and updating to expo@34.0.3 doesn't resolve it then please post a minimal reproducible example here

**Comment by NiclasEricsson** [comment]
@brentvatne Ok, now I think it works. Not sure what solved it though, earlier I removed, reinstalled and cleared cache several times without it working (with the right version numbers). Now I also reinstalled expo-font again and removed the lock file, which seemed to solve it. But a bit confusing :)

**Comment by brentvatne** [comment]
sorry for that!

**Comment by NiclasEricsson** [comment]
@brentvatne No worries!

**Comment by knightkiddo** [comment]
> @NiclasEricsson - can you try clearing node_modules and your lockfiles and reinstalling to ensure that you are getting the correct version of expo-font?

Ok I will try that too because I didn't think to delete the lockfiles..
When I upgraded I deleted `node_modules`, did another `npm install` and `expo start -c`

**Comment by knightkiddo** [comment]
Problem solved ! For me, it was the package-lock.json ! Thank you @brentvatne

**Comment by Razorholt** [comment]
Nope. Still having that issue after cleaning both node_modules and package-lock

```
 "expo": "^34.0.3",
 "expo-font": "^6.0.1"
```
Also, after I dismiss the error, the app loads but without the icons. Will that be my next issue with SDK 34?

**Comment by javi10823** [comment]
Hi Everyone! I have the same issue

versions:
```
“expo”: “^34.0.3",
   “expo-font”: “~6.0.1",
```

- I deleted expo app in iPhone
- I removed node modules folder
- I executed yarn clear cache

Any ideas?

**Comment by Razorholt** [comment]
You also have to delete package-lock.json, so the steps would be:

1.-  Delete the node_modules folder
2.-  Delete the package-lock.json file
3.-  Run `npm/yarn install`

Then run `expo start -c`

**Comment by javi10823** [comment]
> You also have to delete package-lock.json, so the steps would be:
> 
> 1.- Delete the node_modules folder
> 2.- Delete the package-lock.json file
> 3.- Run `npm/yarn install`
> 
> Then run `expo start -c`

@Razorholt  I don't have package-lock.json, I'm using yarn.

I Already tried everything.

**Comment by edoantonioco** [comment]
@Razorholt way fixed it

>
> @Razorholt I don't have package-lock.json, I'm using yarn.
> 
> I Already tried everything.

then delete yarn.lock

**Comment by kotenarok** [comment]
any updates?

**Comment by brunokiafuka** [comment]
> You also have to delete package-lock.json, so the steps would be:
> 
> 1.- Delete the node_modules folder
> 2.- Delete the package-lock.json file
> 3.- Run `npm/yarn install`
> 
> Then run `expo start -c`

This worked for me :) 
Thanks @Razorholt

**Comment by billychasen** [comment]
Make sure you delete the Expo app and let it reinstall. That was the missing piece to get it to work for me.

**Comment by kotenarok** [comment]
> Make sure you delete the Expo app and let it reinstall. That was the missing piece to get it to work for me.

I have tried clearing data (using Android) but still no luck.

**Comment by TheSupremeBeard** [comment]
I am having the same issue when rendering a **native-base Checkbox** element.

Expo is set to **34.0.3**
Expo Font is set to **6.0.1**

I have removed node_modules and any lock files, reinstalled npm, started expo with a clear cache, reinstalled the expo app on the iOS simulator.

Yet i am still getting:

console.error "fontFamily "Ionicons" is not a system font and has not been loaded through Font.loadSync

**Comment by stevenbuchko** [comment]
I’m still running into issues with this even after nuking everything and updating expo and expo-fonts to the recommended versions above. My package.json has the following dependencies:

"expo": "^34.0.3",
    "expo-asset": "^6.0.0",
    "expo-constants": "^6.0.0",
    "expo-font": "^6.0.1",
    "expo-linear-gradient": "^6.0.0",
And I’m implementing the fonts in the App.tsx like so

private loadResourcesAsync = async () => {
    await Promise.all([
      Expo.Asset.loadAsync([
        // ...
      ]),
      Font.loadAsync({
        // ...
      }),
      Font.loadAsync({
        AvenirNext_Medium: require('./assets/fonts/AvenirNext-Medium.ttf'),
        AvenirNext_Regular: require('./assets/fonts/AvenirNext-Regular.ttf'),
        AvenirNext_UltraLight: require('./assets/fonts/AvenirNext-UltraLight.ttf'),
        Montserrat_Bold: require('./assets/fonts/Montserrat-Bold.ttf'),
        Montserrat_Medium: require('./assets/fonts/Montserrat-Medium.ttf'),
        Montserrat_Regular: require('./assets/fonts/Montserrat-Regular.ttf'),
        Montserrat_Light: require('./assets/fonts/Montserrat-Light.ttf'),
        Rubik_Medium: require('./assets/fonts/Rubik-Medium.ttf'),
        Rubik_Regular: require('./assets/fonts/Rubik-Regular.ttf'),
        Rubik_Light: require('./assets/fonts/Rubik-Light.ttf'),
        // TODO: Put these back to Roboto
        Roboto: require('./assets/fonts/AvenirNext-Regular.ttf'),
        Roboto_medium: require('./assets/fonts/AvenirNext-Medium.ttf'),
        // Ionicons: require('@expo/vector-icons/fonts/Ionicons.ttf'),
        CoinClear_Icons: require('./assets/fonts/coinclearicons.ttf'),
      }),
    ]);
  };```

**Comment by brentvatne** [comment]
@stevenbuchko - please create a new issue with a minimal reproducible example (https://stackoverflow.com/help/mcve)
