### ISSUE TITLE
Research and implement Branch as an optional module on Android

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#5132]
Recently we've removed Branch from Android (more details [in the blog post](https://blog.expo.io/changes-to-expo-branch-support-d002c4bc564e)) but we'd like to provide a way to include this module if someone wants to do a build with it, maybe as a `--include-branch` flag to `expo build:android` command. 
Pull request removing Branch code for reference: #4058

**Comment by wkozyra95** [comment]
added turtle support here https://github.com/expo/turtle/commit/7a80d92e72061406f7b104d9a096ea0b28d1c355

Unimodule `expo-branch` will be added if there is a dependency in package.json with the same name
