### ISSUE TITLE
SDK 34 ImagePicker doesn't work on Android standalone apps

### ISSUE THREAD

**Issue by thanh90** [expo/expo#5137]
I just wanna reopen issue [#627](https://github.com/expo/expo/issues/627) because it still happens on SDK 34.
ImagePicker.launchImageLibraryAsync() and ImagePicker.launchCameraAsync() do not seem to work on Android standalone apps. The permissions are requested correctly, but the async calls never return and the view for taking/picking photos never appears.
Permissions have been put into the app.json, and on iOS things are working correctly. 

And I got this error:
import * as ImagePicker from 'expo-image-picker';
TypeError: o.slice is not a function. (In 'o.slice(0,3)', 'o.slice' is undefined)

**Comment by raajnadar** [comment]
Try this https://stackoverflow.com/a/57088204/5519872

**Comment by thanh90** [comment]
i'm not sure what happened, but permission is not my error, i resolved my issue when `expo publish `again

**Comment by raajnadar** [comment]
Build new apk file `expo publish` (OTA) won't work for non js files.

**Comment by thanh90** [comment]
it seemed that I need to use `expo publish` to make it works
