### ISSUE TITLE
SDK34 can not add property 'iosDisplayInForeground' in app.json.

### ISSUE THREAD

**Issue by CuSO4-5H2O** [expo/expo#5139]
### Environment

  Expo CLI 3.0.6 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.10.2 - /usr/local/bin/npm
    npmPackages:
      expo: ^34.0.0 => 34.0.3 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.0.6

### Steps to Reproduce
According to SDK34 Docs, I set the new property notifications->iosDisplayInForeground(only available in SDK34) in app.json, and get this error message when I run 'expo start'

Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v34.0.0/workflow/configuration/
 • Field: notification - should NOT have additional property 'iosDisplayInForeground'.

### Expected Behavior

Normally build, and show notifications foreground in iOS.

### Actual Behavior

Get Above Error Message when build.

### Reproducible Demo

{
  "expo": {
 ...
   "notification": {
      "icon": "./assets/images/icon-noti.png",
      "color": "#0047ab",
      "iosDisplayInForeground": true,
      "androidMode": "default"
    }
  }
}

  What happens if you skip this step?
  Can not show notifications when the app showing at foreground in iOS.

Addtionally, the SDK34 documents search feature is also not available. When I search anything, only got 'No results found for query xxx'

**Comment by CuSO4-5H2O** [comment]
And I got error message 'Unable to resolve "./Google" from "node_modules/expo/build/ExpoLazy.js"
Failed building JavaScript bundle.' each time when I run 'expo start'.

**Comment by cruzach** [comment]
Hi! This feature actually isn't available in the current SDKs. We hope to include it very soon! I've updated the changelog and docs to reflect this, but thanks for pointing it out

**Comment by cruzach** [comment]
We're also currently looking this.
> Addtionally, the SDK34 documents search feature is also not available. When I search anything, only got 'No results found for query xxx'


For this error:
>  'Unable to resolve "./Google" from "node_modules/expo/build/ExpoLazy.js"

see here-> https://github.com/expo/expo/issues/5112
