### ISSUE TITLE
Tabs boilerplate broken?

### ISSUE THREAD

**Issue by umxr** [expo/expo#5140]
Hey, so im setting up app using expo. I was reading through the docs and it suggests to use the tabs example as its a pretty solid starting point. I installed everything fine, I then tried to load it up on my iPhone 8 and got this error...

<img width="1038" alt="Screenshot 2019-08-01 at 06 30 02" src="https://user-images.githubusercontent.com/20203468/62267971-170d1100-b426-11e9-84ea-82ad87bd3199.png">

What am I doing wrong? I get the same error for ionicons aswell

**Comment by cruzach** [comment]
Thanks for pointing this out, looks like the version of `expo-font` used in the tabs template needs to be updated.

As a workaround- you can just run `expo install expo-font` and it should run properly
