### ISSUE TITLE
[ios] Add "Sign In With Apple" module

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#5145]
Either as a vendored module or a unimodule. To be discussed!

**Comment by ide** [comment]
We discussed with some folks over at https://github.com/react-native-community/apple-authentication. We could try using this module for now. If the API starts to move away from an API design we like, we can make expo-apple-authentication later anyway.

**Comment by ide** [comment]
It looks like that library is usable -- from the examples, it appears you can render a button using the native Apple UI and then write your own press handler, which calls into another API to start the authentication flow.

This task would be to import that module's native code, and add the package to the JSON file that `expo install` reads from.
