### ISSUE TITLE
Exits the app after showing Admob support video

### ISSUE THREAD

**Issue by LukasNavickas** [expo/expo#5148]
Hello, I have an identical Admob implementation as [https://github.com/deadcoder0904/expo-google-admob](https://github.com/deadcoder0904/expo-google-admob)
The reward ad is shown, but right after it finishes the app is closed (expo).
No error is shown.
The same happens in your [demo app](https://expo.io/@deadcoder0904/expo-google-admob) 
Banner ads are working just fine.
I'm using SDK 33 at the moment and an Android phone.

**Comment by vivianzzhu91** [comment]
Hi, I tried running the same code on snack, Android simulator and Android phone, and I didn't encounter the same problem. Here's a reproducible [`demo`](https://snack.expo.io/@vivianzzhu91/9f7339) on snack, could you try upgrading to SDK 34 or try test it on the snack and let me know if there're still problems!

**Comment by cruzach** [comment]
Going to close this for inactivity, since we couldn't reproduce ourselves. If you can provide more info so that we can reproduce the issue, happy to re-open!
