### ISSUE TITLE
Picking same image from same location with ImagePicker returns different uris.

### ISSUE THREAD

**Issue by Dmytraw** [expo/expo#5151]
### Environment

Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.0.6

Encountered on:
Iphone xr simulator
Android device expo tunnel

### Steps to Reproduce

0)
```
pickImage = async () => {
    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: false,
    });
    if (!result.cancelled) {
      console.log(result.uri);
    }
  };
```
1) pick image
2) pick exact same image from exact same location
### Expected Behavior

`result.uri` from step 1 and step 2 should match

### Actual Behavior

`result.uri`from step 1 and 2 do not match

### Reproducible Demo
[Snack](https://snack.expo.io/SktaqogmB)
or
```
import * as React from 'react';
import { Button, Image, View } from 'react-native';
import {ImagePicker, Permissions, Constants} from 'expo';

export default class ImagePickerExample extends React.Component {

  render() {

    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Button
          title="Pick an image from camera roll"
          onPress={this._pickImage}
        />
      </View>
    );
  }

  componentDidMount() {
    this.getPermissionAsync();
  }

  getPermissionAsync = async () => {
    if (Constants.platform.ios) {
      const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (status !== 'granted') {
        alert('Sorry, we need camera roll permissions to make this work!');
      }
    }
  }

  _pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: false,
    });

    

    if (!result.cancelled) {
      console.log(result.uri);
    }
  };
}
```

**Comment by cruzach** [comment]
@Dmytraw is this also the case in SDK 34?

**Comment by Dmytraw** [comment]
@cruzach that's actually a good question. in our project sdk version is `"expo": "^33.0.0"`

**Comment by Dmytraw** [comment]
@cruzach bug confirmed with `"expo": "^34.0.4"`.

**Comment by lukmccall** [comment]
I think it's not a bug. ImagePicker copy selected files to the cache directory. That's why `launchImageLibraryAsync` returns path similar to this:
`file:/data/user/0/host.exp.exponent/cache/ExperienceData/sandbox/ImagePicker/14f4bf26-5ba0-4f73-bbd1-8f26284140b3.jpg `.
Moreover, when you selected the same file twice, it will copy this file two times into the cache directory but with different names.
