### ISSUE TITLE
React Native Version Mismatch with SDK 33 or 34

### ISSUE THREAD

**Issue by nickjuntilla** [expo/expo#5156]
### Environment

`  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.6`

Target iOS and Android

### Steps to Reproduce

expo start -c 
Fails to start the app. I'm upgrading from SDK 32 for Android 64bit compliance.

### Expected Behavior

App starts up

### Actual Behavior

 I get:

console.error: "React Native
version mismatch.
JavaScript version: 0.59.8
Native version: 0.57.1

My package file: 

`
{
  "main": "./src/App.js",
  "private": true,
  "dependencies": {
    "@babel/plugin-transform-react-jsx-source": "^7.0.0",
    "@expo/vector-icons": "^9.0.0",
    "@shoutem/ui": "^0.23.4",
    "algoliasearch": "^3.33.0",
    "b64-to-blob": "^1.2.19",
    "big-number": "^1.0.0",
    "bip32": "^1.0.2",
    "bn.js": "^4.11.8",
    "buffer": "^5.1.0",
    "crypto-js": "^3.1.9-1",
    "email-validator": "^1.1.1",
    "expo": "^34.0.3",
    "expo-analytics-amplitude": "^6.0.0",
    "expo-barcode-scanner": "^6.0.0",
    "expo-file-system": "^6.0.0",
    "expo-image-picker": "^6.0.0",
    "expo-location": "^6.0.0",
    "expo-permissions": "^6.0.0",
    "firebase": "^5.0.2",
    "lodash": "^4.17.10",
    "md5": "^2.2.1",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "qs": "^6.5.1",
    "react": "16.8.3",
    "react-instantsearch-native": "^5.7.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-dropdownalert": "^3.4.0",
    "react-native-elements": "^1.1.0",
    "react-native-extended-stylesheet": "^0.8.1",
    "react-native-fit-image": "^1.5.4",
    "react-native-fs": "^2.10.14",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-iphone-x-helper": "^1.0.2",
    "react-native-keyboard-aware-scroll-view": "^0.7.0",
    "react-native-local-storage": "^1.5.2",
    "react-native-location-view": "^0.1.5",
    "react-native-maps": "^0.22.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^6.1.0",
    "react-native-qrcode": "^0.2.6",
    "react-native-router-flux": "^4.0.6",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-super-grid": "^2.3.1",
    "react-native-svg": "^9.5.3",
    "react-native-svg-uri": "^1.2.3",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.11.1",
    "react-navigation-props-mapper": "^0.3.0",
    "react-redux": "^5.0.7",
    "react-router-hash-link": "^1.2.1",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-persist": "^5.10.0",
    "tcomb-form-native": "^0.6.13",
    "uuid": "^3.2.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.1.6",
    "@babel/plugin-proposal-decorators": "^7.1.6",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-react": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-loader": "^8.0.4",
    "babel-preset-react-app": "^6.1.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.9.1"
  },
  "resolutions": {
    "babel-core": "7.0.0-bridge.0"
  },
  "scripts": {
    "lint": "eslint ./src --fix"
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}

`

**Comment by cruzach** [comment]
Hi! Looks like your `expo`,`react`, and `react-native` dependencies are all right. Could you try killing the Expo Client on your phone and trying again? Also, there's a few more fixes listed in [this issue](https://github.com/expo/expo/issues/923)

**Comment by nickjuntilla** [comment]
@cruzach I found the problem. I needed to update the sdk version in the project app.json file:

"sdkVersion": "34.0.0",
