### ISSUE TITLE
Expo Sharing [Unhandled promise rejection: Error: You don't have access to provided file.]

### ISSUE THREAD

**Issue by alexandrius** [expo/expo#5159]
### Environment

  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 

### Steps to Reproduce

Just follow https://docs.expo.io/versions/v34.0.0/sdk/sharing/
Execute 
`Sharing.shareAsync('https://github.com')`

### Expected Behavior

Show sharing dialog

### Actual Behavior
Logging an error
```
[Unhandled promise rejection: Error: You don't have access to provided file.]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in h
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals
```

**Comment by cruzach** [comment]
The string you pass should be a
> Local file URL to share

according to the docs. This probably explains the error, since you're using an https url

**Comment by AleksandarSavic95** [comment]
What I did to overcome this is that I **downloaded** the file to a local cache directory, and then share it from there.
### [>> Link to my answer on StackOverflow <<](https://stackoverflow.com/a/57379644/2101117)
