### ISSUE TITLE
Permissions on simulator always undetermined  

### ISSUE THREAD

**Issue by farzd** [expo/expo#516]
Seems to be working on the device
But on the simulator, its always 'undetermined' ?
Heres a plain expo app for testing it https://github.com/farzd/expo-permissions/blob/master/App.js
Simulator = iPhone 6/ iOS 10
```
  "dependencies": {
    "expo": "^19.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz"
  }
```

**Comment by ide** [comment]
Push notifications aren't supported on the simulator, which is why iOS never tells us whether the user has granted permission for them. You'll have to use a real device to test push notifications.

**Comment by farzd** [comment]
My bad. Thanks for the response !

**Comment by James2516** [comment]
Local notification is supported on the simulator though...
Purchasing an iPhone just for testing local notification feels wasteful.

**Comment by farzd** [comment]
You will need an iPhone to test your app though?

**Comment by James2516** [comment]
Why? My app only uses local notification which simulator supports.

**Comment by HristoEftimov** [comment]
The same problem and for me. iOS simulator always returns `undetermined` as a status... for any kind of notification.

**Comment by alexey-ambrozevitch** [comment]
The same problem.

**Comment by lednhatkhanh** [comment]
So this is actually a problem :(

**Comment by ralfrotamola** [comment]
I encounter this right now, even when i side load the application.  I also added a callback but it always ended undetermined result.

**Comment by ralfrotamola** [comment]
oh I forgot i'm using xcode but I don't have any possible solution to this problem.
