### ISSUE TITLE
Can not install apk to my device

### ISSUE THREAD

**Issue by marknguyen85** [expo/expo#5168]
### Environment

 Expo CLI 3.0.6 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.0 - /usr/local/opt/node@8/bin/node
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.0.6

### Steps to Reproduce
i have been using expo-cli to build and export to an apk file but cannot install it to my device.

`There was a problem parsing the package.`

here the config files:

app.json 
```

{
  "react-native": "0.59.8",
  "expo": {
    "name": "BVBDReport",
    "icon":"./assets/logo.png",    
    "version": "0.1.0",
    "slug": "BVBD",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android"
    ],

```
package.json 
```

{
  "name": "report",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "^34.0.0",
    "react-test-renderer": "16.3.1",
    "redux-logger": "^3.0.6",
    "remote-redux-devtools": "^0.5.13",
    "remotedev-rn-debugger": "^0.8.3"
  },
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.1",
    "expo": "^34.0.0",
    "moment": "^2.22.2",
    "native-base": "^2.13.4",
    "npm": "^6.3.0",
    "react": "16.3.1",
    "react-native": "0.59.8",
    "react-native-awesome-alerts": "^1.0.8",
    "react-native-datepicker": "^1.7.2",
    "react-native-flags": "^1.0.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-orientation-loading-overlay": "^0.1.4",
    "react-native-picker-select": "^4.2.0",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-table-component": "^1.2.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.11.2",
    "react-navigation-redux-helpers": "^2.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-promise": "^0.6.0",
    "redux-saga": "^0.16.0"
  }
}
```

and when ran to export apk i used keystone from expo-cli handle it.

  Thanks for helping us help you!
-->

**Comment by cruzach** [comment]
Is this a bare React Native project, or an Expo managed project? 
From your dependencies, it looks like a bare project, in which case I really can't say what the cause behind this is (but I don't think it's specific to Expo)

If it's a managed project, make sure your dependencies match those we specify in the release notes -> https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319

**Comment by marknguyen85** [comment]
> https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319

I did from followed the release note but still got error like above

here the package.json 

<pre>

{
  "name": "report",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "^34.0.0",
    "react-test-renderer": "16.3.1",
    "redux-logger": "^3.0.6",
    "remote-redux-devtools": "^0.5.13",
    "remotedev-rn-debugger": "^0.8.3"
  },
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^34.0.3",
    "expo-font": "^6.0.1",
    "moment": "^2.22.2",
    "native-base": "^2.13.4",
    "npm": "^6.3.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-awesome-alerts": "^1.0.8",
    "react-native-datepicker": "^1.7.2",
    "react-native-flags": "^1.0.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-orientation-loading-overlay": "^0.1.4",
    "react-native-picker-select": "^4.2.0",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-table-component": "^1.2.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^3.11.1",
    "react-navigation-redux-helpers": "^2.0.5",
    "react-redux": "^5.1.1",
    "redux": "^4.0.0",
    "redux-promise": "^0.6.0",
    "redux-saga": "^0.16.0"
  }
}

</pre>

and app.json

<pre>
{
  "expo": {
    "name": "BVBDReport",
    "icon":"./assets/logo.png",    
    "version": "0.1.0",
    "slug": "BVBD",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "loading": {
      "icon": "./assets/logo.png",
      "hideExponentText": false
    },
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "bundleIdentifier": "BVBD.Report",
      "icon":"./assets/ios_logo_1024.png"
    },
    "android":{
      "permissions": [
        "READ_EXTERNAL_STORAGE",
        "com.anddoes.launcher.permission.UPDATE_COUNT",
        "com.android.launcher.permission.INSTALL_SHORTCUT",
        "com.google.android.c2dm.permission.RECEIVE",
        "com.google.android.gms.permission.ACTIVITY_RECOGNITION",
        "com.google.android.providers.gsf.permission.READ_GSERVICES",
        "com.htc.launcher.permission.READ_SETTINGS",
        "com.htc.launcher.permission.UPDATE_SHORTCUT",
        "com.majeur.launcher.permission.UPDATE_BADGE",
        "com.sec.android.provider.badge.permission.READ",
        "com.sec.android.provider.badge.permission.WRITE",
        "com.sonyericsson.home.permission.BROADCAST_BADGE"
      ],
      "package":"BVBD.Report",
      "versionCode": 1, 
      "icon":"./assets/logo_1024.png"
    }
  }
}
</pre>

**Comment by cruzach** [comment]
What device and OS are you trying to install it on?

It's best if you can list out all the steps you took to get to this error, step 1 being starting a new blank project

**Comment by marknguyen85** [comment]
my devide is samsung and run on android 7.
My project has been upgraded from version expo sdk v27.0.0.0, react-native version v55.0 and still run with this version.

**Comment by cruzach** [comment]
@marknguyen85 were you able to resolve this issue? I haven't seen other reports of this

Were you trying to upgrade directly from SDK 27 to 34? It's recommended to upgrade one SDK at a time
