### ISSUE TITLE
[Android][FileSystem] Unable to delete any directory via FileSystem.deleteAsync(Uri) on Older Android Versions

### ISSUE THREAD

**Issue by josepaez2** [expo/expo#5170]
### Environment

  System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.0/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v10.15.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.5
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 3.0.6

### Steps to Reproduce
````
  myCreateDirectoryMethod = async () => {
    try {
       await FileSystem.makeDirectoryAsync(FileSystem.documentDirectory + 'myDirectory');
    } catch (error) {
      }
  }
  myDeleteDirectoryMethod = async () => {
    try {
       await FileSystem.deleteAsync(FileSystem.documentDirectory + 'myDirectory');
    } catch (error) {
      }
  }

   this.myCreateDirectoryMethod()
   this.myDeleteDirectoryMethod()
````
### Expected Behavior

Delete successfully

### Actual Behavior

[Error: Encountered an exception while calling native method: Exception occurred while executing exported method deleteAsync on module ExponentFileSystem: null]

**Comment by cruzach** [comment]
Hey @josepaez2 - I made [this snack](https://snack.expo.io/@charliecruzan/filesystemdirectories) based off your steps and didn't see the error. Could you share a snack that does?

**Comment by MaHermes** [comment]
I'm also getting this error. Also if I try it with the snack example.
![grafik](https://user-images.githubusercontent.com/36889405/63165333-67da5780-c02b-11e9-9a8e-3f82607ebe0c.png)

**Comment by walkerlifee** [comment]
I'm also getting this issue on android 6.0.1, my 'expo-file-system' dependencies version is 6.0.2.
![Screen Shot 2019-09-09 at 2 05 27 PM](https://user-images.githubusercontent.com/28886111/64509879-e8c6ff00-d30a-11e9-9f4c-c47aa9ab8ced.png)

**Comment by colinux** [comment]
Same problem for me.

From my bug report system, the exception always occurs with the following Android versions, with SDK 33 & 34 (I didn't have this feature with previous SDK).

- Android 22
- Android 23
- Android 24
- Android 25

Also, it could be related : renaming directories with `FileSystem.moveAsync` is broken too for the same Android versions (but code works like a charm for iOS and recent Android).

**Comment by tal2** [comment]
I'm having the same issue with SDK 35

**Comment by dean9703111** [comment]
Sdk 35 encounter isuuse too
