### ISSUE TITLE
[iOS] Custom font rendering problem

### ISSUE THREAD

**Issue by jaeyoi** [expo/expo#5172]
### Environment

Expo CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8

### Steps to Reproduce

When I try to use a custom font in iOS, the top of the characters at the first line is cut off.

Font: Cooper Hewitt (https://www.cooperhewitt.org/open-source-at-cooper-hewitt/cooper-hewitt-the-typeface-by-chester-jenkins/)

### Expected Behavior

In Android, the font is rendered correctly.

First Text font: Cooper Hewitt
Second Text font: System font

> ![Screenshot_20190803-105741](https://user-images.githubusercontent.com/1281315/62406150-f4275c00-b5e1-11e9-987b-06c31a9d1ea2.png)

### Actual Behavior

In iOS, the top of the characters at the first line is cut off.

First Text font: Cooper Hewitt
Second Text font: System font

> ![Screen Shot - iPhone 7 - 2019-08-03 at 11 22 00](https://user-images.githubusercontent.com/1281315/62406143-d8bc5100-b5e1-11e9-9a05-f5a2d09ca2c6.png)

### Reproducible Demo

https://snack.expo.io/rk_R3PMXS

**Comment by cruzach** [comment]
@jaeyoi I believe this might be Font-specific, since I've tested on other fonts (random ones from https://fonts.google.com/ ) and they don't have this same behavior.

**Comment by sjchmiela** [comment]
It looks like you can mitigate this issue by setting a bigger line height. I'm not an expert when it comes to fonts, but I second @cruzach in that it may be a specific-font problem rather than our implementation. 🙂

**Comment by jaeyoi** [comment]
Ok. I will use the font with a bigger line height.
Thanks!
