### ISSUE TITLE
Search bar in expo docs not working [docs]

### ISSUE THREAD

**Issue by mufaddalhamidofficial** [expo/expo#5173]
Search bar in docs is not working

Whenever we write anything it says "No result found for query"
Image:
![image](https://user-images.githubusercontent.com/49232863/62408492-8e3dd300-b5e7-11e9-9aaa-726226f74367.png)

**Comment by cruzach** [comment]
Hi- thanks for opening an issue for this.

This is fixed now, just tested on my end!
