### ISSUE TITLE
Component expo-camera doesn't work on back of a stack navigation

### ISSUE THREAD

**Issue by diogoduartec** [expo/expo#5174]
### Environment

  Expo CLI 2.20.7 environment info:
    System:
      OS: Linux 4.18 Pop!_OS 18.10
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: 2.18.3 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.20.7

   > target: Android, S9+

### Steps to Reproduce

1. Create a Stack Navigator with following screens: CameraScreen and ShowPictureScreen

2. On CameraScreen create an expo's component Camera. Camera component will take a picture and then will go to ShowPictureScreen using `this.props.navigation.navigate(ShowPictureScreen)`

3. Create a goBack button with onPress: `this.props.navigation.goBack()`, or just go back with android native button

### Expected Behavior

The Camera component should work just like before navigate to ShowPictureScreen

### Actual Behavior

Camera component show just a black screen

**Comment by cruzach** [comment]
Hey @diogoduartec, we provide an issue template so that you know exactly the information we need so that we can help you out as fast as possible. Please go back and edit your issue so that it has everything we ask for in the issue template (especially your SDK version **and** a reproducible example). Thanks!

**Comment by diogoduartec** [comment]
Where can i find this issue template?

**Comment by cruzach** [comment]
It's automatic when you open an bug report. But you can see the raw file here -> https://raw.githubusercontent.com/expo/expo/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by diogoduartec** [comment]
Thank you @cruzach !

**Comment by diogoduartec** [comment]
is everything ok now @cruzach ?

**Comment by cruzach** [comment]
Looks good! You might want to try on SDK 34 and see if the problem persists there

**Comment by diogoduartec** [comment]
I changed to SDK 34 and the problem persists @cruzach

**Comment by diogoduartec** [comment]
I solved it changing default behavior of 'hardwareBackPress', instead does 'goBack' it does a 'navigate'.

https://facebook.github.io/react-native/docs/backhandler.html
