### ISSUE TITLE
[docs] createIconSet documentation outdated

### ISSUE THREAD

**Issue by Xerus2000** [expo/expo#5175]
https://docs.expo.io/versions/latest/guides/icons/#createiconset

The example only shows `createIconSet` with 2 arguments, but in the latest version it additionally requires an `expoAssetId`, and I have no idea what I should put in there.

**Comment by cruzach** [comment]
From the looks of the source, since `expoAssetId` is used like this:
```
const font = { [fontName]: expoAssetId };
```
and then loaded via:
```
await Font.loadAsync(font);
```
my guess is that `expoAssetId` is the asset returned from require statement

**Comment by Xerus2000** [comment]
Well, I am passing null now, and it seems to work fine. So I have no idea what this is doing. Some docs would be nice...

**Comment by cruzach** [comment]
Agreed! We'll be updating the Font docs soon
