### ISSUE TITLE
Import problem upgrading from SDK 32 to 34

### ISSUE THREAD

**Issue by charlesblack** [expo/expo#5176]
## 🐛 Bug Report

When I upgrade from SDK 32 to 33 or 34, I get an input error, in App.js. Here is the code from that file:

Turns out, you can't do <Expo.AppLoading/>, you have to import it and do <AppLoading/>

### Environment

> Expo CLI 2.21.2 environment info:
>     System:
>       OS: Windows 10
>     Binaries:
>       Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>       npm: 6.8.0 - C:\Users\curda\AppData\Roaming\npm\npm.CMD
>     IDEs:
>       Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

Developing for Android

### Steps to Reproduce

Simply run the app and you'll get an import error that I don't know where it comes from. What is strange is that the same code worked in SDK 32.

### Expected Behavior

The app should run without errors

### Actual Behavior

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

> Check your code at App.js:115., 
>     in App (created by Context.Consumer)
>     in Connect(App) (at App.js:147)
>     in Provider (at App.js:146)
>     in Top (at withExpoRoot.js:20)
>     in RootErrorBoundary (at withExpoRoot.js:19)
>     in ExpoRootComponent (at renderApplication.js:35)
>     in RCTView (at View.js:45)
>     in View (at AppContainer.js:98)
>     in RCTView (at View.js:45)
>     in View (at AppContainer.js:115)
>     in AppContainer (at renderApplication.js:34)
> 
> Stack trace:
>   node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8 in error
>   node_modules\expo\build\environment\muteWarnings.fx.js:26:24 in error
>   node_modules\react\cjs\react.development.js:188:36 in warningWithoutStack
>   node_modules\react\cjs\react.development.js:603:32 in warning
>   node_modules\react\cjs\react.development.js:1730:14 in createElementWithValidation
>   App.js:115:20 in render
>   node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:11581:21 in finishClassComponent
>   node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:11509:4 in updateClassComponent

**Comment by raajnadar** [comment]
Go step by step upgrade from sdk 32 to sdk 33 and then sdk 34.

Make sure you are reading the breaking change section in the upgrading blog post.

**Comment by charlesblack** [comment]
> Go step by step upgrade from sdk 32 to sdk 33 and then sdk 34.
> 
> Make sure you are reading the breaking change section in the upgrading blog post.

I've done this already. The problem comes out in the update of SDK 32 to SDK 33. I went through every single API change and none really applied. Is there any way to debug where this error is coming from?

The error I get is very general, and it doesn't point to anything.

**Comment by raajnadar** [comment]
Can you link a repo to check the issue.

I think the issue is at line 115.

**Comment by charlesblack** [comment]
> Can you link a repo to check the issue.
> 
> I think the issue is at line 115.

Fixed it. <Expo.AppLoading/> was the problem

**Comment by charlesblack** [comment]
> Can you link a repo to check the issue.
> 
> I think the issue is at line 115.

Fixed it. <Expo.AppLoading/> was the problem
