### ISSUE TITLE
Is it possible to debug two "instances" at the same time? 

### ISSUE THREAD

**Issue by brunoreis** [expo/expo#518]
First, expo is fantastic. Thanks a lot!
Second, I'm testing an offline first app using expo. So I need to see how things happen on one end and after that, on another end. Let's say, on the mobile and on the iosSimulator. Is it possible to have both working and being debugged? I'm using React Native Debuger and I see it can have multiple windows in different ports. Is it possible to have, let's say, iosSimulator on 19001 and the "shared" android on 19002? So that when I start to debug remote js it does not break the other instance debugger.

**Comment by ide** [comment]
I don't think we support simultaneous Chrome debugging right now, but we do support loading from multiple clients simultaneously in non-debugging mode and you can using console.log statements to debug. In SDK 22 we might have support for hot module reloading across multiple clients as well (it just got added to RN master).

**Comment by dikaiosune** [comment]
Chrome debugging is managed by React Native, AFAIK we don't do anything special for this. Going to give this a close for now, but if multiple debugger clients lands upstream please post back and let us know so we can double check that it works! Thanks!
