### ISSUE TITLE
[ScreenOrientation] Cant Lock to Landscape on iOS Client 2.12.1 [SDK 34]

### ISSUE THREAD

**Issue by bruno-edo** [expo/expo#5188]
## 🐛 Bug Report

Before updating to SDK 34 (and the new Expo app for iOS) the orientation lock through `app.json` worked correctly, now it doesn't work anymore.

### Environment

```
  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.0 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1
```

Targets: iOS.

### Steps to Reproduce

- Create project using SDK 34;
- Set orientation to `landscape` in your `app.json` file;
- Open app on simulator;
- Roatate device a few times.

### Expected Behavior

App should only allow the landscape orientation.

### Actual Behavior

App allows both landscape and portrait orientations.

![](https://thumbs.gfycat.com/NextIdealisticDobermanpinscher-size_restricted.gif)

### Reproducible Demo

I've set my `app.json` file like so:

```json
{
  "expo": {
    "name": "test",
    "slug": "test",
    "privacy": "unlisted",
    "sdkVersion": "34.0.0",
    "platforms": [ "ios" ],
    "version": "0.1.0",
    "orientation": "landscape",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "test",
      "buildNumber": "0.1.0",
      "supportsTablet": true,
      "isTabletOnly": true
    }
  }
}
```

And also tried using the `ScreenOrientation` API on my `App.js` file:

```js
/* eslint-disable react/prefer-stateless-function */
import React, { Component } from 'react';
import { ActivityIndicator } from 'react-native';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/es/integration/react';
import { Provider as PaperProvider, Portal } from 'react-native-paper';
import { ScreenOrientation } from 'expo';

import configureStore from './src/store/store';
import Navigator from './src/navigation/AppNavigator';
// eslint-disable-next-line no-unused-vars
import i18n from './src/config/i18n';

const { persistor, store } = configureStore();

export default class App extends Component {
  async componentDidMount() {
    await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE);
  }

  render() {
    return (
      <Provider store={store}>
        <PaperProvider>
          <PersistGate loading={<ActivityIndicator />} persistor={persistor}>
            <Portal.Host>
              <Navigator />
            </Portal.Host>
          </PersistGate>
        </PaperProvider>
      </Provider>
    );
  }
}
```

**Comment by cruzach** [comment]
Hey @bruno-edo , I just tried this in a blank SDK 34 project, and wasn't able to get the issue you described

Is it a specific device/iOS version that you're seeing this on?

**Comment by bruno-edo** [comment]
@cruzach No. I've tested it on a physical iPad (iOS 11.4.1)  and in a simulator running the latest specs.

**Comment by cruzach** [comment]
Woops, didn't see you had `"isTabletOnly": true`. I was testing on my device (not an iPad) -- testing this on an iPad sim with most recent Expo Client version brings up the error

**Comment by Pitchlab** [comment]
I can verify this issue still exists with latest Expo (36). Is there anything that can be done? The orientation doesn't lock on tablet (sim and physical device)

**Comment by smddzcy** [comment]
It's still an issue. Can't lock the orientation for tablets (tested on iPad Pro 12.9").

**Comment by lukmccall** [comment]
Hi everyone, unfortunately in the expo client this will be unfixable for now. However, in the standalone app, to fix it you can set `requireFullScreen` options ([under the `ios` key](https://docs.expo.io/versions/latest/workflow/configuration/#ios)) to true in app.json.
In bare flow, you can check the `Requires Full Screen` checkbox under General > Targets ([see](https://stackoverflow.com/a/32728607)).

**Comment by brayanL** [comment]
Not Works yet on Expo 40, any update?

**Comment by sergeu90** [comment]
I have same issue.

**Comment by lukmccall** [comment]
Please open a new issue 😉
