### ISSUE TITLE
Error sending push notifications on iOS

### ISSUE THREAD

**Issue by gnardini** [expo/expo#5189]
The app I'm working on has push notifications. On Android I created the firebase stuff and uploaded it from the CLI, they work great on production. On iOS, when I try to send one to my phone I get a receipt and the repecipt returns the following error:
```
{"data":{"47d33e11-1ded-4637-befd-3fea336c4c23":{"status":"error","message":"There was an unexpected error delivering the notification.","details":{"sentAt":1565022111},"__debug":{"internalError":"Failed to generate token: error:0909006C:PEM routines:get_name:no start line"}}}}
```
When I created the app I let expo handle everything, I didn't do anything else special for push notifications on iOS. The files I have that were created for me are `fidus.mobileprovision`, `fidus_dist.p12`  and `fidus_push.p12`. I read guides and  stuff but none of them suggest I have to do anything else and the error is quite cryptic, so I'm having trouble figuring it out.

Any ideas? Help please!

**Comment by cruzach** [comment]
Hi! Are you sure Expo created new push credentials? Or it used old ones you had?

This same error was posted over at our forums, and OP shared the fix, you can read it [here](https://forums.expo.io/t/ios-push-notification-error-failed-to-generate-token-errorpem-routinesno-start-line/25343)

Let me know if that works!

**Comment by cruzach** [comment]
@gnardini were you able to solve this issue with the fix from our forums?

**Comment by gnardini** [comment]
Hi @cruzach thanks for answering. I found the solution around the time I opened the issue but I don't remember how. I'm sorry I forgot to post here after that :(
