### ISSUE TITLE
Updating to SDK 20 => can't read property "mark" of undefined

### ISSUE THREAD

**Issue by slorber** [expo/expo#519]
Hi,

After upgrading to SDK 20 on Android I get these errors and application stays on splash screen:

```
ExceptionsManager.js:65 Cannot read property 'mark' of undefined
ExceptionsManager.js:65 Module AppRegistry is not a registered callable module (calling runApplication)
```

My application runs fine in SDK19.

Any idea?

**Comment by schettino** [comment]
Are you using sagas?

If so, you should change
```javascript
export function* gen() { }
```
to
```javascript
const gen = function* () { };
export const genSaga = gen;
```

At least for now. You can track this issue here
https://github.com/facebook/react-native/issues/14838

**Comment by slorber** [comment]
thanks I'm using saga, I'll try your solution when I can

**Comment by digitalmaster** [comment]
Hmm... didn't work for me... Strange tho - I was using sagas before this upgrade.

**Comment by reggie3** [comment]
I got it to work using @schettino's suggestion.  My code ended up looking like this:
```
const handleFormSubmitSuccess = function* handleFormSubmitSuccess(action) {
  try {
    console.log(action);
    switch (action.meta.form) {
      case "addItemForm":
        let state = yield select();
        yield put({
          type: "POST_INVENTORY_ITEM",
          payload: lambdaPost.purchase(state.form.addItemForm.values)
        });
        break;
    }
  } catch (e) {
    yield console.log("ERROR: handleFormSubmitSuccess");
    yield console.log({ e });
  }
}
export const sagaHandleFormSubmitSuccess =  function* sagaHandleFormSubmitSuccess() {
  yield takeEvery(
    ["@@redux-form/SET_SUBMIT_SUCCEEDED"],
    handleFormSubmitSuccess
  );
}
```

**Comment by ide** [comment]
React Native (upstream) updated its Babel preset to babel-preset-react-native@2 so we updated babel-preset-expo@3 to use it. Therefore the breaking changes in RN's preset apply to Expo's preset too.

**Comment by digitalmaster** [comment]
Awesome Thanks for update @ide. 

Thanks @reggie3... @schettino solution worked for me too :)

**Comment by slorber** [comment]
thanks @schettino it seems to work.

The problem is not related to exports but rather all function declarations should be assigned to variables to solve the problem.

**Comment by ide** [comment]
There is a PR to fix this that has been submitted upstream to RN. Someone who works on the RN packager has looked at it. If/when it gets merged into RN, we'll probably want to publish a new copy of babel-preset-react-native. Assuming it's not a breaking change, you will get the new b-p-r-n if you delete your lockfiles and reinstall node_modules.

**Comment by danscan** [comment]
The workaround in this thread worked for me.  Gonna copy [my comment from here](https://forums.expo.io/t/updated-to-expo-20-getting-warning-about-app-json/2465/11) in case it's helpful to anyone:

> This resolved it for me: https://github.com/expo/expo/issues/519.  To be clear, if you have a generator function like  `function* namedGenerator() {}`, you can't use it directly as `namedGenerator`, you need to set it as some variable/constant first... e.g.:
> 
> ```javascript
> const namedGeneratorFn = function* namedGenerator() {};
> 
> // This will NOT work!
> // export default namedGenerator;
> 
> // This will work
> export default namedGeneratorFn;
> ```

**Comment by dikaiosune** [comment]
Upstream PR is in progress, workaround is available. Going to give this a close as we generally track babel preset upgrades elsewhere. If you're finding this issue and the workaround isn't helping, please post here and we'll reopen. Thanks!

**Comment by ide** [comment]
babel-preset-react-native v2.0.1 (which babel-preset-expo v3 pulls in) should have the fix. If you run `yarn upgrade` you should get it.

**Comment by xcarpentier** [comment]
Hello @ide @dikaiosune,

Just to be sure, the latest version of expo (ie. "expo": "**20.1.2**") should be fixed this issue entirely ?
Or should we rewrite too rewrite generator function ?

In other word, is the expo upgrade not enough?

**Comment by ide** [comment]
You need babel-preset-react-native 2.0.1 or newer. If you have that under node_modules then you should be fine and don't need to modify your code. You might want to clear your packager caches just to be safe though.

**Comment by xcarpentier** [comment]
@ide I have install in devDependency this version "babel-preset-react-native": "3.0.2". 

But I still have this warning in console log (after clean node_modules):

> [exp] Warning: Problem validating app.json: regeneratorRuntime is not defined.

And this error in red screen:

> undefined is not an object (evaluating 'regeneratorRuntime.mark')

in node_modules:
{
  "name": "babel-preset-react-native",
  "version": "3.0.2",
  "description": "Babel preset for React Native applications",
  ...
}

**Comment by kadoshms** [comment]
+1

**Comment by xcarpentier** [comment]
@dikaiosune @ide any idea? or will you delete my comment too 😄  ?

**Comment by iosdev-republicofapps** [comment]
@ide sorry, I still get this error with babel-preset-react-native 2.1.0 `Cannot find property 'mark' of undefined`.  Nothing fixes it except @danscan suggestion.  Any ideas?

Thanks!

**Comment by nbaghiro** [comment]
Is this issue not fixed yet? 

I had the same issue and setting generator to const variable solved the issue for me. But that should not be the permanent fix, right? 

Thanks.
