### ISSUE TITLE
[ web ] speed issue when using Permissions and Location together on web

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#5192]
### Environment

This issue is most prevelant on safari desktop in my testing.

  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.1.9 
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.22 => 16.8.22 
      @types/react-native: ^0.60.2 => 0.60.2 

### Steps to Reproduce

run the following code in safari:

```javascript
  async function getLocationAsync() {
    const { status } = await Permissions.askAsync(Permissions.LOCATION)
    if (status === 'granted') {
      const location = await Location.getCurrentPositionAsync()

      console.log(location.coords.latitude.toString())
    }
  }
```
### Expected Behavior

Location should come back as quickly as using the following:

```javascript
  async function getLocationAsync() {
    const location = await Location.getCurrentPositionAsync()

    alert(location.coords.latitude.toString())
  }
```

### Actual Behavior

The example with permissions takes *much* longer (say, 20 seconds vs. the instant results when just using `navigator.geolocation.getCurrentPosition`

### Reproducible Demo

https://snack.expo.io/HJgems8QS

I think this has something to do with calling `navigator.geolocation.getCurrentPosition` as a result of calling `navigator.geolocation.getCurrentPosition`. I'm not sure why, but on safari desktop this makes things take much longer than just calling the function once.

**Comment by cruzach** [comment]
Hmm..I'm not seeing any difference in speed in Safari.

Are you running through the snack, or through `expo-cli`?

**Comment by chrisdrackett** [comment]
I'm running the snack (https://snack.expo.io/HJgems8QS) in safari `Version 12.1.2 (14607.3.9)`

Here is a video:

https://cl.ly/224de0582fd8

**Comment by cruzach** [comment]
Okay, after updating my mac OS and getting Safari from 12.1.1 to 12.1.2, I see the behavior. (although I don't think it's specific to this version) I think that this speed decrease only happens **sometimes**. At first, both methods return close to instantly, then it gets hung up on the `Permissions` call (narrowed it down to that with some `console.log`ing
