### ISSUE TITLE
Basic AR example in docs doesn't work on iPhone SE

### ISSUE THREAD

**Issue by jacklj** [expo/expo#5197]
### Environment
At the top of the latest AR docs ([here](https://docs.expo.io/versions/v34.0.0/sdk/AR/#getting-started)), there is an example called [basicAR](https://snack.expo.io/@charliecruzan/basicar).

I have an iPhone SE (iOS 12.4), with the Expo Client app on it (v2.12.0).

### Steps to Reproduce
When I run basicAR via the Expo app on my iPhone , it just displays a white screen.

 It seems the AR bit is working, as on startup, text appears saying "Initializing", and if I move the phone around a lot it says "Excessive motion".

However the screen is just all white apart from that text,  so it seems the graphics aren't rendering.

### Expected Behavior
Something is displayed.

### Actual Behavior
Nothing is displayed.

### Reproducible Demo
[https://snack.expo.io/@charliecruzan/basicar](https://snack.expo.io/@charliecruzan/basicar)

**Comment by peterel** [comment]
Any news on this? Its not working on iPhoneX either. Just get a white screen when running on my device.

**Comment by cruzach** [comment]
Haven't had time to work through this example yet, but if you want to take a crack at it we'd love a docs PR!

**Comment by peterel** [comment]
I can appreciate that but I was really just looking to do an initial test to try out the expo platform and ran into this. Could you direct me to any other sample/tutorial that works for expo AR?

**Comment by EvanBacon** [comment]
Expo AR has been deprecated. The new bare-workflow package will be located here in the future https://github.com/expo-community/expo-ar
