### ISSUE TITLE
Feature Request: onFullscreenDismissed prop for video / full-screen-only mode

### ISSUE THREAD

**Issue by samwise00** [expo/expo#52]
It would be helpful if there were an onFullscreenDismissed prop for video, or a fullscreen-only mode. Ideally both.

In some apps, like the one I am working on, the expected functionality is that a video opens in fullscreen, and the video is terminated once fullscreen is dismissed. I think this is fairly common video functionality for many apps.

These are both features that other players like react-native-youtube have

thanks much

**Comment by tanvirislam06** [comment]
It would be great have this feature or a full-screen only mode!

**Comment by MichaelZawadzki** [comment]
Would be nice to have this indeed!

**Comment by JakeTheLion89** [comment]
Hoping this feature gets implemented as well.

**Comment by samwise00** [comment]
Any word on if this will make it into a release soon? This is really integral to my app and I'd really love for it to be added, especially considering it's pretty standard video functionality to have videos be viewable only in fullscreen in an app. Really love exponent and would love to keep using it @brentvatne @nikki93

**Comment by gkufera** [comment]
Hey all --

SDK 17 (released this week) includes native fullscreening on iOS + a prop called `onIOSFullscreenUpdate` which includes information like onFullscreenDismissed. I am updating the docs for this now; expect them in the next few days.

At the moment we do not provide a special native view for fullscreening on Android, but creating a cross-platform fullscreen video view is possible on top of our current SDK by creating a `Video` component that fills the screen of your app. It is a priority for us to create more helpful tools surrounding fullscreening, and we hope to include a convenience fullscreen-only video component in a future SDK release.

I am closing this issue and merging it with #166. Let me know if you have any questions or need some direction on creating a fullscreen video component with our current SDK.

Thanks!
