### ISSUE TITLE
Linking Uri turns into 'https://expo.host' in iOS standalone app with scheme defined

### ISSUE THREAD

**Issue by schettino** [expo/expo#520]
Tried sdk versions 18, 19 and 20.

Just created a brand new app using exp init and patched app.json and App.js (entry):

app.json
```json
{
  "expo": {
    "name": "Helldirect-exp",
    "slug": "Helldirect-exp",
    "sdkVersion": "20.0.0",
    "orientation": "portrait",
    "privacy": "unlisted",
    "scheme": "helldirectexp",
    "version": "1.0.0",
    "icon": "./assets/icons/app-icon.png",
    "packagerOpts": {
      "assetExts": ["ttf"]
    },
    "loading": {
      "hideExponentText": false
    },
    "ios": {
      "buildNumber": "1",
      "supportsTablet": false,
      "bundleIdentifier": "br.com.helldirectexp.schettino"
    },
    "android": {
      "package": "br.com.helldirectexp.schettino"
    }
  }
}
```

App.js
```javascript
import React from 'react';
import { Constants } from 'expo';
import { StyleSheet, Text, View, Linking } from 'react-native';

export default class App extends React.Component {
  state = { initialLinkingUri: '' };
  
    async componentWillMount() {
      const initialLinkingUri = await Linking.getInitialURL();
      this.setState({ initialLinkingUri });
    }  
  render() {
    return (
      <View style={styles.container}>
      <Text>initialLinkingUri: {this.state.initialLinkingUri}</Text>
      <Text>linkingUri: {Constants.linkingUri}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

Finally, a did run exp build:ios -t simulator and the result is:
![captura de tela 2017-08-22 as 16 12 49](https://user-images.githubusercontent.com/7825467/29584839-67378b8c-875b-11e7-88b1-c99a2825abae.png)

npm version: 4.6.1
exp version: 44.0.0
yarn version: 0.24.6
node version: v7.9.0

Turns out that it's almost impossible to continue developping the iOS app since the user authentication process is throw auth0, and I can't neither link auth0 rn library nor open a WebBrowser to complete the authentication (which is what I'm trying to do).

**Comment by schettino** [comment]
Tried with sdkVersion 20.0.0 and didn't work also. Can someone help me out over here, please?

**Comment by ide** [comment]
This might have been a regression, don't have more info right now.

**Comment by peterpme** [comment]
Related: https://forums.expo.io/t/issues-with-linking-from-webbrowser-in-standalone-app/779/36

**Comment by terribleben** [comment]
This fix just rolled out to `exp build:ios` and ExpoKit. Let me know if you're still seeing issues. Thanks for the report and for the repro code, really appreciate it.

**Comment by Rutulpatel7077** [comment]
@terribleben I am still having this issue. 

More info: https://github.com/expo/expo/issues/2644
