### ISSUE TITLE
ExpoAR: image detection doesn't work until the isArRunningStateEnabled play/pause button has been toggled

### ISSUE THREAD

**Issue by jacklj** [expo/expo#5201]
### Environment

```
  Expo CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 3.0.8
```

App's target: iOS (I've got an iPhone SE)

### Steps to Reproduce
When running a minimal image detection example, images aren't detected until the 'isArRunningStateEnabled button' (play/pause button) is turned off and on. Once this has been done, images are then detected successfully.

1. Run the app on your iPhone
1. Try and detect the `./assets/bug.png` image by opening the image on your computer and pointing your phone's camera at it
1. The app won't detect the image (nothing will be console.logged)
1. Press the play button and then the pause button (to restart AR)
1. You can now detect the image

### Expected Behaviour
Images are detected immediately

### Actual Behavior
Images aren't detected until AR has been 'restarted'

### Reproducible Demo
https://snack.expo.io/@jackvlj/expo-ar-image-detection-bug

N.B. This Snack doesn't work, for some reason. If you download the code and run it locally, it works. (Click Export, unzip, `yarn && expo start`)

Also, I have deliberately used expo v32 as I couldn't get the minimal AR image detection app working at all with more recent versions.

**Comment by EvanBacon** [comment]
Expo AR is now deprecated as of SDK 37. Community members are working on a bare workflow module which will live here https://github.com/expo-community/expo-ar
