### ISSUE TITLE
[docs] For ExpoAr Image Detection, in the listener `onAnchorsDidUpdate()`, when is the event type `AR.AnchorEventType.Remove` supposed to happen?

### ISSUE THREAD

**Issue by jacklj** [expo/expo#5202]
For image detecting, when the image is first detected, the eventType `AR.AnchorEventType.Add` is fired.

When the image moves relative to the camera, the eventType `AR.AnchorEventType.Update` is fired.

When is `AR.AnchorEventType.Remove` meant to fire? I thought it might fire when the image is no longer in view of the camera, but this isn't the case. So when does it fire? (and separate question really - how can i detect when an image is no longer in view?)

Thanks

**Comment by AdamJNavarro** [comment]
Hey @jacklj,

These types of questions are better suited on our [forums](https://forums.expo.io/). Would you mind creating a post there and we'll get you an answer as soon as we can. We try our best to keep Github issues reserved for reproducible bugs.

Cheers,
Adam

**Comment by jacklj** [comment]
Sure, no worries.

Posted it here because the docs are a bit sparse so thought it might be worth clarifying and then adding the answer to the docs.

Thanks!
