### ISSUE TITLE
[unimodules] update READMEs to suggest `expo install` instead of `npm install`

### ISSUE THREAD

**Issue by esamelson** [expo/expo#5203]
https://github.com/expo/expo/pull/5098#discussion_r310202219

All the docs pages recommend `expo install` to install individual unimodules in bare workflow projects. We should update the packages READMEs to match.

**Comment by b4stien** [comment]
What is `expo install` and how is it different than `yarn add`? Is it documented somewhere?

**Comment by AdamJNavarro** [comment]
All readmes have been updated.
