### ISSUE TITLE
SDK 34 - _expo.FileSystem.cacheDirectory - undefined is not an object

### ISSUE THREAD

**Issue by owenhope** [expo/expo#5206]
Hello,

I am upgrading my ExpoKit app from 33 to 34, and I am getting this error on iOS...

![Simulator Screen Shot - iPhone Xʀ - 2019-08-06 at 16 09 04](https://user-images.githubusercontent.com/6454237/62583342-aa9a7380-b864-11e9-94bf-d56f1fb1a1d6.png)

Any ideas?

**Comment by ru88s** [comment]
I moved after changing `react-native-expo-image-cache` from ^ 3.2.0 to ^ 4.0.4.
how is it?

**Comment by cruzach** [comment]
Can you make sure you're importing `FileSystem` correctly? The proper syntax is:
```
import * as FileSystem from 'expo-file-system';
```
You also will need to run `expo install expo-file-system` in your project directory.

I just tried this in [this snack](https://snack.expo.io/@charliecruzan/suspicious-tea) (SDK 34) and wasn't able to reproduce the error.

**Comment by owenhope** [comment]
> I moved after changing `react-native-expo-image-cache` from ^ 3.2.0 to ^ 4.0.4.
> how is it?

This solved the problem for me! Thank you very much! cc: @cruzach
