### ISSUE TITLE
undefined is not an object(evaluating '_ExpoBarCodeScannerModule.default.BarCodeType')

### ISSUE THREAD

**Issue by OscarYuen** [expo/expo#5215]
### Environment

After upgrade Expokit from 33 to 34, I got this error in iOS. (Not tested in Android yet)

### Steps to Reproduce

1. Run expo install expo-barcode-scanner
2. Run expo start
3. During launching, I encountered this error

### Actual Behavior
![IMG_8363](https://user-images.githubusercontent.com/5617834/62621551-b7939180-b94e-11e9-8197-92fcd914134e.jpg)

**Comment by cruzach** [comment]
How are you importing this module?

I'd compare your code to [this example snack](https://snack.expo.io/@charliecruzan/barcodescanner) which runs well, and see if there are any differences.

**Comment by OscarYuen** [comment]
I found out that I need to run again pod install after installing the latest version react-native-onesignal in npm. The issue is gone. Thanks
