### ISSUE TITLE
Audio plays in iOS simulator, but not on production

### ISSUE THREAD

**Issue by pauldcollins** [expo/expo#5216]
My sounds work fine on my simulator and using Expo on my phone, but for some reason, as soon as I deploy to Test Flight, I get no sound whatsover. I'm building using the standard `expo build:ios` and letting Expo take care of everything - then uploading to the App Store. I thought it might be a path issue, but I've tried adding the WAVs in the same folder, and still no luck.

Here's my code:

```
constructor(props) {
    super(props);
   
    this.heartBeat = new Audio.Sound();
  }

  async componentWillMount() {
    await Audio.setAudioModeAsync({
      playsInSilentModeIOS: true,
      allowsRecordingIOS: false,
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
      shouldDuckAndroid: false,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      playThroughEarpieceAndroid: true
    });
    await Audio.setIsEnabledAsync(true);
    await this.heartBeat.loadAsync(require("./MySound.wav"));
  }

  handlePlaySound = async () => {
    try {
      await this.heartBeat.setPositionAsync(0);
      await this.heartBeat.playAsync();
    } catch (error) {
      console.log("ERROR", error);
    }
  };

```

Then call `handlePlaySound` when I want it to play. Works fine locally, just not on production.

Here's my **app.json**

```
{
  "expo": {
    "name": "My App",
    "version": "0.0.4",
    "slug": "my-app",
    "sdkVersion": "32.0.0",
    "ios": {
      "bundleIdentifier": "com.myapp"
    },
    "android": {
      "package": "com.myapp"
    }
  }
}
```
And my **package.json** dependencies list.

```
  "dependencies": {
    "babel-preset-expo": "^5.0.0",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-stopwatch-timer": "0.0.20",
    "react-navigation": "^1.5.7"
  }
```

Would greatly appreciate any advice, as I'm running out of ideas! 

Thanks for any help.

**Comment by cruzach** [comment]
Hey @pauldcollins 

Could you try changing your `react-native` dependency to point to `"https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"` ? We always state exactly what to pin that to in our release notes (you can find the SDK 32 release notes [here](https://blog.expo.io/expo-sdk-v32-0-0-is-now-available-6b78f92a6c52))

Also, running the project in production locally might provide some insight, you can do this by running `expo start --no-dev --minify`

**Comment by pauldcollins** [comment]
Hey @cruzach thanks for the quick response. 

I did try pointing to the Tar at one stage, but got a build error. Let me check again though, as I've changed a few things since.

That is great to know about running production locally. I'll try both of these things and get back. Thanks again.

**Comment by pauldcollins** [comment]
For anyone coming back to this. I managed to get Audio working, using the following steps:

- Change the `react-native` dependency to point to Expo's version (as shown above by Cruzach)
- Update Expo, React Native, and React to the latest versions (as required by Expo)
- Change the `Audio` import to point to `expo-av`, instead of just `expo`. [See here](https://docs.expo.io/versions/latest/sdk/av/)
- Change formats from `wav` to `mp3` (It's possible that the Audio files were too large).

Can't say which of these specifically solved the problem, but I was on fairly old versions of everything, so the updates make sense. 

Good luck, thanks again for the help @cruzach
