### ISSUE TITLE
Expo SDK 20, Android on Genymotion emulator, TypeError in Networking.sendRequest

### ISSUE THREAD

**Issue by GrigoryPtashko** [expo/expo#522]
I've cleaned the cache like this

`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules && yarn`

I'm starting exp like this

`exp r -c`

My versions are

exp cli 44.0.0
expo client 1.19.0
expo sdk 20.0.0

ios version works fine.
On android (genymotion emulator) I get this:

![screenshot 2017-08-20 23 55 07](https://user-images.githubusercontent.com/2768788/29498378-968fa8d2-8603-11e7-8334-4a24b98cc365.png)

**Comment by ide** [comment]
This can happen when you have a mismatch between JS and native code. Perhaps your versions aren't lined up correctly or you're loading some stale code?

**Comment by GrigoryPtashko** [comment]
@ide, isn't it enough to clean react caches as I wrote? I guess there are no other means to do this. And exactly which versions can be not lined up? I don't understand what else can I do since all of the expo tools are up to date.

**Comment by GrigoryPtashko** [comment]
I also deleted the Genymotion virtual device and created it again. The fresh install of expo client. The error stays exactly the same. What else can I do?

**Comment by GrigoryPtashko** [comment]
Here's my `exp.json`

```
{
  "name": "Hashnews",
  "description": "The news selection service",
  "slug": "hashnews",
  "privacy": "unlisted",
  "sdkVersion": "20.0.0",
  "version": "0.4.1",
  "orientation": "portrait",
  "primaryColor": "#cccccc",
  "icon": "./assets/icons/app-icon.png",
  "notification": {
    "icon": "./assets/icons/notification-icon.png",
    "color": "#000000"
  },
  "loading": {
    "icon": "./assets/icons/loading-icon.png",
    "hideExponentText": true
  },
  "packagerOpts": {
    "assetExts": [
      "ttf"
    ]
  },
  "ios": {
    "supportsTablet": true,
    "bundleIdentifier": "me.hashnews"
  },
  "android": {
    "package": "me.hashnews"
  }
}
```

Here's my `package.json`

```
{
  "name": "hashnews",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "main": "src/main.js",
  "scripts": {
    "test": "node node_modules/jest/bin/jest.js",
    "lint": "eslint .",
    "devtools": "react-devtools",
    "relay": "relay-compiler --src ./src --schema ./schema.json"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "~1.0.3",
    "@expo/vector-icons": "~5.0.0",
    "antd-mobile": "^1.6.2",
    "base-64": "^0.1.0",
    "expo": "^20.0.0",
    "hoist-non-react-statics": "^2.2.0",
    "lodash.isequal": "^4.4.0",
    "moment": "^2.17.1",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-native-style-tachyons": "^3.4.2",
    "react-native-swipeout": "^2.0.13",
    "react-navigation": "^1.0.0-beta.12",
    "react-relay": "^1.2.0",
    "sockjs-client": "^1.1.1",
    "stompjs": "file:../stomp-websocket"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-eslint": "^7.1.1",
    "babel-plugin-idx": "^1.5.1",
    "babel-plugin-import": "^1.3.1",
    "babel-plugin-relay": "^1.2.0",
    "eslint": "^4.3.0",
    "eslint-plugin-react": "^7.1.0",
    "flow-bin": "^0.51.0",
    "graphql": "^0.10.5",
    "graphql-relay": "^0.5.2",
    "idx": "^1.5.0",
    "jest-expo": "~20.0.0",
    "prop-types": "^15.5.8",
    "react-devtools": "^2.5.0",
    "relay-compiler": "^1.2.0",
    "sync-request": "^4.0.1"
  },
  "eslintConfig": {
    "env": {
      "browser": true,
      "jest": true
    },
    "parser": "babel-eslint",
    "plugins": [
      "react"
    ],
    "extends": [
      "eslint:recommended",
      "plugin:react/recommended"
    ],
    "rules": {
      "max-len": [
        2,
        120,
        2
      ]
    }
  }
}
```

**Comment by dikaiosune** [comment]
I'd be curious to know where in the JS these bad args are getting passed. Do you have any libraries that are calling directly into RN's native modules? For example

```
    "sockjs-client": "^1.1.1",
    "stompjs": "file:../stomp-websocket"
```

seem like likely culprits.

**Comment by GrigoryPtashko** [comment]
@dikaiosune, thanks I'll check them. But still it is not clear to me how these js-only libs can cause problems. These libs worked so far in the exactly equal way in my web app and in the ios app. The problem appeared when I tried to look at the android version of my expo app.

**Comment by dikaiosune** [comment]
I'm not an expert on the Networking native module, but it seems possible that different calls to `fetch` could cause problems in RN that are handled more gracefully than on the web.

**Comment by GrigoryPtashko** [comment]
@dikaiosune, thanks for the hint. It helped! I've managed to find the problem. It's the `sockjs-client` that was making the problem.
The commit that fixed it was https://github.com/sockjs/sockjs-client/commit/a21ab072325569cc94b3fad95724d90eb5db42d8
