### ISSUE TITLE
Cannot use expo-local-authentication

### ISSUE THREAD

**Issue by lincdh** [expo/expo#5221]
I tried the expo-local-authentication for my app but it says:

> Unable to resolve "@unimodules/core" from "node_modules/expo-local-authentication/build/LocalAuthentication.js": Module `@unimodules/core` does not exist in the Haste module map.

Also, I found that the file tsconfig.json says 'expo-module-scripts/tsconfig.base' not found:
[https://imgur.com/kwswchL](https://imgur.com/kwswchL)

**Comment by cruzach** [comment]
Hi - there's a similar error message in [this issue](https://github.com/expo/expo/issues/4864), which turned out to be caused by a 3rd party package.

Before we can properly look into this, please go back and fill out the issue template, and make sure to add a reproducible example, thanks!

**Comment by lincdh** [comment]
I made it working by upgrading expo sdk, react-native. Close for now thank u.
