### ISSUE TITLE
The method or property WebBrowser.dismissAuthSession is not available on android

### ISSUE THREAD

**Issue by ribas14** [expo/expo#5225]
### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.0 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.0.9 => 3.3.0
    npmGlobalPackages:
      expo-cli: 3.0.9

Error happens only on android

### Steps to Reproduce

I'm using SDK 34, on android when I try to use AuthSession.dismiss() the response I get is 

`[Unhandled promise rejection: Error: The method or property WebBrowser.dismissAuthSession is not available on android, are you sure you've linked all the native dependencies properly?]
- node_modules/@babel/runtime/helpers/construct.js:30:26 in _construct
- node_modules/@babel/runtime/helpers/wrapNativeSuper.js:26:23 in Wrapper
- node_modules/@unimodules/react-native-adapter/build/errors/CodedError.js:8:8 in CodedError
- node_modules/@unimodules/react-native-adapter/build/errors/UnavailabilityError.js:9:42 in UnavailabilityError
- node_modules/expo-web-browser/build/WebBrowser.js:86:42 in dismissAuthSession
- node_modules/expo/build/AuthSession.js:54:4 in dismiss
* screens/Perfil.js:72:4 in _callee2$
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:27 in callInvokeWithMethodAndArg
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:216:8 in async
* screens/Perfil.js:70:11 in _callee2
* components/Perfil/Informacoes.js:34:16 in onPress
- node_modules/react-native/Libraries/Alert/Alert.js:213:38 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals`

### More info

I was using SDK 32 and everything was working fine, but I need to update to publish a new version on play store, but google only accepts 64bits apk's now and SDK 32 does only 32bits.

Does anyone have a similar problem?

**Comment by cruzach** [comment]
Hi

Before SDK 33, WebBrowser.dismissBrowser() wouldn't do anything (including throw an error message or warning). Now, it'll throw an error to let you know that it won't do anything.

When the web browser window doesn't close after redirect you're encountering this issue: #4524  
 which doesn't happen in standalone Android apps (so it won't impact projects in production). It only happens in the Expo client.

**Comment by junchenjun** [comment]
@cruzach Is there a plan to fix this in the Expo client?

**Comment by brentvatne** [comment]
@junchenjun - a fix for automatically dismissing the browser window when redirecting back to the app will land soon. for `WebBrowser.dismissBrowser()` as far as i know you cannot dismiss chrome custom tabs on android programmatically, so we cannot build a wrapper for a feature that does not exist. please correct me if i'm wrong and point me to appropriate documentation

**Comment by ribas14** [comment]
@cruzach thanks for your help

My question is, if nothing changed why on sdk 32 when I would call AuthSession.dismiss() the app would open a WebBrowser and go to the link to logout, and then come back to the app (standalone or via expo) and now it only gives me this warning (Error: The method or property WebBrowser.dismissAuthSession is not available on android)? 

SDK 34 
```
export function dismissAuthSession() {
    if (_authSessionIsNativelySupported()) {
        if (!ExponentWebBrowser.dismissAuthSession) {
            throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
        }
        ExponentWebBrowser.dismissAuthSession();
    }
    else {
        if (!ExponentWebBrowser.dismissBrowser) {
            throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
        }
        ExponentWebBrowser.dismissBrowser();
    }
}

```

SDK 32 

```
function dismissAuthSession() {
    if (_authSessionIsNativelySupported()) {
        if (!ExponentWebBrowser.dismissAuthSession) {
            throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
        }
        ExponentWebBrowser.dismissAuthSession();
    }
    else {
        if (!ExponentWebBrowser.dismissBrowser) {
            throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
        }
        ExponentWebBrowser.dismissBrowser();
    }
}
```

I don't want to publish this bundle with the SDK 34 because it could break my app, and because I can't publish I can't build a standalone version to test if it would really work because the standalone app would get the bundle from the previous version with the SDK 32.

**Comment by OscarYuen** [comment]
> @cruzach thanks for your help
> 
> My question is, if nothing changed why on sdk 32 when I would call AuthSession.dismiss() the app would open a WebBrowser and go to the link to logout, and then come back to the app (standalone or via expo) and now it only gives me this warning (Error: The method or property WebBrowser.dismissAuthSession is not available on android)? It does not open the browser or anything, just the default warning on the bottom of the screen and nothing else.
> 
> SDK 34
> 
> ```
> export function dismissAuthSession() {
>     if (_authSessionIsNativelySupported()) {
>         if (!ExponentWebBrowser.dismissAuthSession) {
>             throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
>         }
>         ExponentWebBrowser.dismissAuthSession();
>     }
>     else {
>         if (!ExponentWebBrowser.dismissBrowser) {
>             throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
>         }
>         ExponentWebBrowser.dismissBrowser();
>     }
> }
> ```
> 
> SDK 32
> 
> ```
> function dismissAuthSession() {
>     if (_authSessionIsNativelySupported()) {
>         if (!ExponentWebBrowser.dismissAuthSession) {
>             throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
>         }
>         ExponentWebBrowser.dismissAuthSession();
>     }
>     else {
>         if (!ExponentWebBrowser.dismissBrowser) {
>             throw new UnavailabilityError('WebBrowser', 'dismissAuthSession');
>         }
>         ExponentWebBrowser.dismissBrowser();
>     }
> }
> ```
> 
> I don't want to publish this bundle with the SDK 34 because it could break my app, and because I can't publish I can't build a standalone version to test if it would really work because the standalone app would get the bundle from the previous version with the SDK 32.

I think you could publish it to another channel like 'v2.0-staging' and you can test it by standalone build. It would not affect the channel that your production build is using.

**Comment by cruzach** [comment]
@ribas14 let me know how the SDK 34 test build ended up working out 👍

**Comment by ribas14** [comment]
@cruzach I just removed the AuthSession.dismiss() and did something like this and it worked, thanks for you help

```
    await Linking.openURL(
      config.logoutUrl +
        encodeURIComponent(
          __DEV__ ? "exp://localhost:19000" : "app:/callback"
        )
    );
```
