### ISSUE TITLE
'EXBranch/EXBranchManager.h' file not found on blank ejected ExpoKit project

### ISSUE THREAD

**Issue by mjgallag** [expo/expo#5231]
## 🐛 Bug Report

iOS build is currently failing for a new completely blank ejected ExpoKit projects.

The workaround is to revert ExpoKit pod tag to `ios/2.12.1` from `ios/2.12.3` in your `Podfile` [here](https://github.com/thunkable/expo-kit-diff/blob/529d8d225f944befbe13e8324b67edb0cd8f4953/expo-kit-diff/ios/Podfile#L7).

### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.9
```

### Steps to Reproduce

1. clone `https://github.com/thunkable/expo-kit-diff` (this is just a new completely blank ejected ExpoKit project)
1. `cd expo-kit-diff`
1. `npm install`
1. `(cd ios && pod install)`
1. `npx react-native run-ios --no-packager`

### Actual Behavior

```
❌  /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/ios/Pods/ExpoKit/ios/Exponent/Kernel/Services/EXScopedBranchManager.h:4:9: 'EXBranch/EXBranchManager.h' file not found

#import <EXBranch/EXBranchManager.h>
            ^
```

**Comment by owenhope** [comment]
Experiencing the same issue with 2.12.3

**Comment by razvananton21** [comment]
is this any fix for this issue? I encountered it too.

**Comment by NazeerBZ** [comment]
+1

**Comment by changLiuUNSW** [comment]
Get the same issue

**Comment by RodolfoGS** [comment]
Same issue. I fixed it downgrading to **ios/2.12.1**

**Comment by qiongyue** [comment]
missing expo-branch module, you can install it with yarn or npm,then pod install and rebuild again

`
# from your project root path
yarn add expo-branch
cd ios
pod install
`

**Comment by RodolfoGS** [comment]
@qiongyue thank you! Works great using **ios/2.12.3**

```
npm install expo-branch
cd ios/
pod install
```

**Comment by sjchmiela** [comment]
My bad, this shouldn't have happened, I'll release a proper fix asap, hang on

**Comment by sjchmiela** [comment]
If you don't intend to use Branch in your app, you should be able to remove `expo-branch`. Then, upgrade the pod to `ios/2.12.4` tag. This should fix the issue.

If you intend to use Branch, leave `expo-branch` installed (but also upgrade to `ios/2.12.4`, for clarity's sake 😅).

**Comment by mjgallag** [comment]
@sjchmiela I can confirm that it works, thanks! FYI, I'm sure you already know this, but the new ExpoKit project template is still pointing to the broken `ios/2.12.3`. Until we get onto the bare workflow I upgrade ExpoKit by merging in from a brand new ExpoKit project to make sure I don't miss anything thus I notice these things with https://github.com/thunkable/expo-kit-diff :)
