### ISSUE TITLE
This version of the Expo app is out of date. Uninstall the app and run again to upgrade.

### ISSUE THREAD

**Issue by ssomlk** [expo/expo#5234]
I have upgraded the Expo SDK from 33 to 34 as per instructions mentioned below.
https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/

Gets the warning “This version of the Expo app is out of date. Uninstall the app and run again to upgrade”.

Tried below steps.

npm update -g
npm uninstall expo-cli -g
npm cache clean --force
npm install -g expo-cli
Ran the command expo start --localhost --android and get the warning below.

![image](https://user-images.githubusercontent.com/30547921/62666939-99bf3e80-b9d9-11e9-97be-bb9afcf71320.png)

expo diagnostics

Expo CLI 3.0.9 environment info: System: OS: Windows 10 Binaries: npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD

I am using an Android device (Huawei nova 3i, Android version 9, Model INE-LX2). The app is working fine. I have uninstalled the expo client app and reinstalled it.

Have tried solutions in similar issues reported by others, but out of luck.

Any ideas??

**Comment by cruzach** [comment]
What version of the Expo Client app are you trying to run your project on?

**Comment by ssomlk** [comment]
> What version of the Expo Client app are you trying to run your project on?

Expo client version 2.12.0

**Comment by cruzach** [comment]
Hm okay

Go ahead and paste your `app.json` and `package.json` files here

It'd be best if you could share a minimal version of your project so that I can reproduce the error locally

**Comment by kelvinsaputra** [comment]
I got the same error, here my package.json and app.json
![image](https://user-images.githubusercontent.com/23160216/63209344-b6f6ba00-c109-11e9-9115-671e514d0b69.png)

![image](https://user-images.githubusercontent.com/23160216/63209350-c37b1280-c109-11e9-9e95-aed95288603e.png)

**Comment by ssomlk** [comment]
App.json
![image](https://user-images.githubusercontent.com/30547921/63402033-aa39d500-c42d-11e9-9b11-12fa6cd661f2.png)

package.json
![image](https://user-images.githubusercontent.com/30547921/63402050-c2a9ef80-c42d-11e9-9c31-e656672428b3.png)

**Comment by abduraufsherkulov** [comment]
I am having the same problem, any fixes?

**Comment by cruzach** [comment]
I would make sure you've updated all dependencies in your app.json and package.json according to the [SDK 34 upgrade instructions](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319), and then make sure you are running the most recent Expo Client app version (iOS is 2.12.3 and Android is 2.12.2)

**Comment by cruzach** [comment]
@ssomlk are you still having this issue?

**Comment by dsomel21** [comment]
Yes, also having this. I guess it's just another week where I spend hours trying to get started with RN instead of actually coding.

**Comment by cruzach** [comment]
Sorry for the trouble you're having! If you could share a way to repro this, it would a lot, since otherwise it's hard for us to debug this. There's a new version of the Expo Client app out (released yesterday), so make sure you update it!

**Comment by ssomlk** [comment]
Not getting the issue now. Hence closing the issue. Updated to the latest nodejs and expo and issue is solved
