### ISSUE TITLE
Routing  on web with url not working expo 34

### ISSUE THREAD

**Issue by shakti97** [expo/expo#5238]
## 🐛 Bug Report
Routing on web with url or vice-versa not working in expo 34

### Environment

Expo CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: 3.11.0 => 3.11.0 

Testing Expo 34 on all the platform

### Steps to Reproduce
1. make a new project with expo 34.
2. Introduce basic navigation in it.

### Expected Behavior

It should normally work with different navigation url.

### Actual Behavior
navigation is working fine in web , but url not changing or vice-versa.

**Comment by cruzach** [comment]
Could you link a [snack](https://snack.expo.io/) we can use to see this behavior?

**Comment by EvanBacon** [comment]
Unfortunately I haven't had time to work on navigation yet, most users are using `react-navigation` for native and a web solution like `react-router` for web.

**Comment by EvanBacon** [comment]
For further issues related to navigation please open them on React Navigation related repos (also managed by expo).
