### ISSUE TITLE
Scanning QRCode with Client SDK 19 against app SDK 20 => friendly error message

### ISSUE THREAD

**Issue by slorber** [expo/expo#524]
Hi,

I've upgraded my app to SDK20.

I thought my iOS client was up to date (SDK 20) but it was not (SDK19), probably due to delay in store publishing. 

I scanned my app SDK20 QRCode with iOS client SDK 19 and got a cryptic error message.

I think it would be nice if Expo did provide a user-friendly error telling about the mismatch in such case

**Comment by jesseruder** [comment]
Yes, we should have a better message there. It's on our list!

**Comment by terribleben** [comment]
Expo Client shows a clearer error message in this case now.
