### ISSUE TITLE
Build issue for the SDK version 26

### ISSUE THREAD

**Issue by saravanapriyan95** [expo/expo#5241]
I have been used SDK version: ‘26.0.0’, Currently not able to take the build. It show’s an error 26.0.0 is not a valid SDK version. Options are 34.0.0, 31.0.0, 32.0.0, If there any way to take the build without upgrading the version.

**Comment by cruzach** [comment]
Hey @saravanapriyan95 - we dropped support for SDKs 26-30 back when we released SDK 33 in June. [Here](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c#dab0) are the release notes with all the details

In order to build, you'll need to upgrade SDKs
