### ISSUE TITLE
[SDK 34] Failed to build/launch the app after upgrading SDK from 32 to 34

### ISSUE THREAD

**Issue by malikid** [expo/expo#5244]
### Environment

```
Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
```

### Target
Platform: Android and iOS
Mode: Standalone App

### Steps to Reproduce

We followed the instruction in [the blog](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319#59ef):

1. Updated `sdkVersion` in `app.json` to `34.0.0`
2. Changed the versions of related dependencies in `package.json`
3. `expo install` related libraries as we use `react-navigation` in our project
4. Removed `node_modules` and `yarn.lock` then re `yarn`
5. Did `expo-codemod`

Also, followed the instruction [here](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit) to do upgrades regarding ExpoKit:

1. `yarn add -D react-native-unimodules@^0.5.0`
2. `gem update cocoapods` to `1.7.5`
3. Updated `expokit` to `34.0.2` as it’s the corresponding expokitNpmPackage version
4. `expo install` the missing modules, for example `expo-av`, `expo-localization`, and some other `react-native-*`

After all these, we re-eject everything:
1. `rm -rf android/ ios/`
2. `expo eject --eject-method expoKit --non-interactive`
3. `react-native link`

##### For iOS
1. `pod install`
2. `xcodebuild` with params
*Error below appears in the terminal*

```
ios/Pods/ExpoKit/ios/Exponent/Versioned/Core/Api/Components/Svg/Text/RNSVGFontData.h:7:1: error: 
      duplicate interface definition for class 'RNSVGFontData'
```

and

```
ios/Pods/ExpoKit/ios/Exponent/Versioned/Core/Api/Components/Svg/Text/RNSVGGlyphContext.h:9:1: error: 
      duplicate interface definition for class 'RNSVGGlyphContext'
```

##### For Android
1. `./gradlew cleanBuildCache`
2. `./gradlew clean`
3. `./gradlew bundleRelease` with our credential
4. Convert to APK with bundletool
5. Install onto device with bundletool
6. Launch the app
*Error below appears on the device*

```
Native module RNGestureHandlerModule tried to override RNGestureHandlerModule for module name. Check getPackages() method in MainAppllication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true
```

### Expected Behavior

The app can be successfully built and launched as it was with SDK 32 on Android and iOS.

##### For iOS
Error below appears in the terminal while building with `xcodebuild`

```
ios/Pods/ExpoKit/ios/Exponent/Versioned/Core/Api/Components/Svg/Text/RNSVGFontData.h:7:1: error: 
      duplicate interface definition for class 'RNSVGFontData'
```

and

```
ios/Pods/ExpoKit/ios/Exponent/Versioned/Core/Api/Components/Svg/Text/RNSVGGlyphContext.h:9:1: error: 
      duplicate interface definition for class 'RNSVGGlyphContext'
```

##### For Android
Error below appears on the device while launching the app

```
Native module RNGestureHandlerModule tried to override RNGestureHandlerModule for module name. Check getPackages() method in MainAppllication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true
```

### Others
1. Also tried to run it with detached mode:

> For iOS, there’s also the error while building. And for Android, the same that the error appears while launching the app on device.

2. Have tried [this](https://github.com/expo/expo/issues/4856#issuecomment-512234912) but got another error I put [there](https://github.com/expo/expo/issues/4856#issuecomment-519551751).

**Comment by cruzach** [comment]
Have you always re-ejected your project when upgrading SDK versions in the past? That isn't something I've ever done when upgrading an expokit project

**Comment by malikid** [comment]
Yes, and not only when upgrading. Because one of the reasons we use Expo is to rely on Expo on Native part. We do JS part only and use the wrapper value from Expo, so we lock the versions of all the libraries including Expo and re-eject every time we need to build a new version.

> Have you always re-ejected your project when upgrading SDK versions in the past? That isn't something I've ever done when upgrading an expokit project

**Comment by malikid** [comment]
I'm closing it cause we found the issue. It's about `react-native link` automatically links all the custom modules including those already used by unimodules. We now make it more precisely which modules to link.

**Comment by lc3t35** [comment]
Reopen : @malikid please describe the solution.

**Comment by malikid** [comment]
The same as this one: https://github.com/expo/expo/issues/4856#issuecomment-521687514

**Comment by kevinvugts** [comment]
This does not solve it
