### ISSUE TITLE
Exception when upgrade sdk from v19 to 20 on IOS

### ISSUE THREAD

**Issue by ianmark89** [expo/expo#525]
I uploaded my application to App Store with SDK v19.0.0, then I've uploaded new app version with SDK v20.0.0.
After updating the app from TestFlight I've got error as image below.
![error after updating v19 to v20](https://user-images.githubusercontent.com/22815640/29521513-1acbc6ec-86b0-11e7-9cf0-bead3c1a2244.jpg)

**Comment by jesseruder** [comment]
Did you follow all the instructions in the release notes? What's in your app.json and package.json?

**Comment by ianmark89** [comment]
@jesseruder  I've followed all the instructions in the release notes and this issue is only happened on IOS when updating application from SDK v19 to v20, but fresh install.
My app.json and package.json:
<img width="550" alt="app json" src="https://user-images.githubusercontent.com/22815640/29548717-401513e0-872d-11e7-801a-6b4071216efe.png">
<img width="610" alt="package json" src="https://user-images.githubusercontent.com/22815640/29548718-436bd54c-872d-11e7-9b3c-279faf60a416.png">

**Comment by DerJacques** [comment]
I'm experiencing the exact same error on a detached app.
When creating a fresh project everything works just fine. `package.json` and `app.json` are identical.

I've tried to remove `node_modules`, re-installed the Pod dependencies, and cleaned XCode, but nothing has worked so far.

**Comment by dikaiosune** [comment]
Can you try the instructions at https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352 and see if that helps?
