### ISSUE TITLE
How to reset allowed orientation?

### ISSUE THREAD

**Issue by slorber** [expo/expo#526]
Hi,

I'm using the orientation API bit I found it a bit confusing. 

What I want is to do is simply always run my app in portrait, except when browsing full-screen images where landscape is fine.

This lead to something confusing because there's no way to rollback the orientation we just set and reset it to default of app.json.

```javascript
export default class ImageCarousel extends React.PureComponent {
  componentDidMount () {
    ScreenOrientation.allow(ScreenOrientation.Orientation.ALL_BUT_UPSIDE_DOWN);
  }
  componentWillUnmount () {
    ScreenOrientation.allow(ScreenOrientation.Orientation.PORTRAIT);
  }
}
```

I think it would be nicer to have an API that permits easier declarative integration with React by stacking/unstacking orientation settings as components get mounted/unmounted. 

For example it could take form of a HOC like that: 

```javascript
const OrientationHOC = (Component,orientation) => {
  class Orientation extends React.Component {
    componentDidMount () {
      this.orientationAllowed = ScreenOrientation.allow(orientation);
    }
    componentWillUnmount () {
      this.orientationAllowed.remove();
    }
    render() {
      return <Component {...this.props}/>
    }
  } 
}
```

It would be more powerful if you need to deal with more than one level of stacking of orientation changes (like navigating in portals/modals where each can allow different orientation, yes quite fancy app...)

This kind of API is clearly not something critical and can probably be built in userland, but I think it makes sense for many apps that deal with orientation changes so it may be worth shipping it with expo for user-friendliness

**Comment by jesseruder** [comment]
Think it probably makes more sense to build this in userland, like you said. Don't want to start attaching our APIs to a particular navigation paradigm.

**Comment by slorber** [comment]
@jesseruder existing apis are already attached to this navigation pattern. Take the StatusBar for example, it seems to me it works exactly like that (and it's actually recommended to use the component rather than the imperative API). As it's already used in RN, we could imagine a `<Orientation value="portrait"/>` instead of a HOC.

**Comment by dikaiosune** [comment]
I think this seems like a pretty solid idea, but I'm guessing we'd like to see it working in practice before supporting it in the SDK. Maybe release it as an npm package and see how it goes? Closing for now, but post back if you think we should reconsider!

Also, it's usually easier to gauge how much the community would value inclusion in the SDK if you create a [feature request](https://expo.canny.io) that people can vote on!

**Comment by joeyespo** [comment]
Ran into the same issue. Here's a quick component I came up with if anyone's looking:

```js
import { Component } from 'react';
import PropTypes from 'prop-types';
import Expo from 'expo';
import { expo } from '../app.json';

const ORIENTATION_DEFAULT = Expo.ScreenOrientation.Orientation.ALL;
const ORIENTATIONS = {
  'portrait': Expo.ScreenOrientation.Orientation.PORTRAIT,
  'landscape': Expo.ScreenOrientation.Orientation.LANDSCAPE,
  'default': ORIENTATION_DEFAULT,
};

export default class ScreenOrientation extends Component {
  allow(orientation) {
    const key = orientation === 'default' ? expo.orientation : orientation;
    Expo.ScreenOrientation.allow(ORIENTATIONS[key] || ORIENTATION_DEFAULT);
  }

  componentDidMount() {
    this.allow(this.props.allow);
  }

  componentWillUnmount() {
    this.allow('default');
  }

  render() {
    return this.props.children;
  }
}

ScreenOrientation.propTypes = {
  children: PropTypes.node,
  allow: PropTypes.oneOf(Object.keys(ORIENTATIONS)),
};
```

Note that this reads `app.json` to get the global value.

Usage

```js
<ScreenOrientation allow="portrait">
  ...
</ScreenOrientation>
```
