### ISSUE TITLE
[androidx] Investigate running Jetifier over older SDK versions

### ISSUE THREAD

**Issue by ide** [expo/expo#5260]
If we could migrate older SDKs to AndroidX, this would let us keep them when we eventually include a new SDK version that uses AndroidX.

We don't plan to ship AndroidX support with SDK 35 but want to start investigating now.

**Comment by katbusch** [comment]
When will androidx support be released?

**Comment by ide** [comment]
AndroidX will be coming with SDK 36. We don't have a release date for SDK 36, but when it is released you can find out at blog.expo.io.
