### ISSUE TITLE
Streamline the release process

### ISSUE THREAD

**Issue by ide** [expo/expo#5262]
On of our primary areas of focus for SDK 35/36/37 will be internal tools and streamlining the release process. Eric will be leading this effort.

Related issues:
- Done:
  - https://github.com/expo/expo/issues/4449
  - https://github.com/expo/expo/issues/5254
  - https://github.com/expo/expo/issues/4551
  - https://github.com/expo/expo-cli/issues/766
  - https://github.com/expo/expo/issues/4575
  - https://github.com/expo/expo/issues/5253
  - https://github.com/expo/expo/issues/4887
  - https://github.com/expo/expo/issues/5144
- To be done:
  - https://github.com/expo/expo/issues/5255
  - https://github.com/expo/expo/issues/4644

**Comment by tsapeta** [comment]
Just two of listed issues have left and since it's not our top priority right now, I'm closing this umbrella issue.
