### ISSUE TITLE
Property 'transaction' does not exist on type 'WebSQLDatabase'.

### ISSUE THREAD

**Issue by danielmichaelni** [expo/expo#5264]
## 🐛 Bug Report

Types missing for SQLite since it was separated into its own package (expo-sqlite). App still runs fine.

### Environment

iOS

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      npm: 6.10.2 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react-native: ^0.60.3 => 0.60.3 
      expo: ^34.0.3 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9

### Steps to Reproduce

Open a database and execute a transaction (following the example here: https://docs.expo.io/versions/latest/sdk/sqlite/)

```
import { SQLite } from "expo-sqlite";
const db = SQLite.openDatabase(DB_NAME);
db.transaction((tx) => {});
```

### Expected Behavior

No type errors.

### Actual Behavior

We get the following type error: Property 'transaction' does not exist on type 'WebSQLDatabase'.

Looking at the source code (https://github.com/expo/expo/blob/master/packages/expo-sqlite/src/SQLite.ts), I see that the WebSQLDatabase interface only has an `exec` property, but there should also be a `transaction` property.

**Comment by TvrtkoM** [comment]
Also there's no Transaction type in d.ts file declared
