### ISSUE TITLE
[Amplitude][Android] Standalone app crash - Amplitude.setUserProperties() results in java.lang.NullPointerException

### ISSUE THREAD

**Issue by jamesbechet** [expo/expo#5288]
## 🐛 Bug Report
Since I've upgraded to SDK 33 and 34, I'm getting this crash in production. However, I'm only getting this error on Android and not on iOS. Sentry doesn't seem to catch anything.

I've hesitated to post this error since I'm not able to reproduce in development, but it happened tot 10 different devices in production. It's the exact stack trace every single time. So if you have an idea on how to prevent me to have this issue, it would greatly appreciated.

Here's the full error:
```
java.lang.NullPointerException: 
  at org.json.JSONTokener.nextCleanInternal (JSONTokener.java:116)
  at org.json.JSONTokener.nextValue (JSONTokener.java:94)
  at org.json.JSONObject.<init> (JSONObject.java:159)
  at org.json.JSONObject.<init> (JSONObject.java:176)
  at com.amplitude.api.AmplitudeClient$9.run (AmplitudeClient.java:1254)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.os.HandlerThread.run (HandlerThread.java:65)
```

### Environment
Production - Standalone Android

### Steps to Reproduce
N/A

### Expected Behavior
To not crash.

### Actual Behavior
Crashes.

### Reproducible Demo
N/A

**Comment by cruzach** [comment]
Hey @jamesbechet , sorry you're seeing this issue in production!

To try and get more info, could you run this locally in production? Use `expo start --no-dev --minify`

I don't think any major changes were made to the `expo-analytics-amplitude` package for SDK 34

**Comment by jamesbechet** [comment]
@cruzach I ran this locally, but I don't seem to get any errors.

I looked at my crash logs and this issue only started appearing in SDK 33 and SDK 34. When `expo-analytics-amplitude` became an unimodule. I simply went from:

```
import { Amplitude } from 'expo'
```
to
```
import * as Amplitude from 'expo-analytics-amplitude'
```

That's when I started seeing this error. My code was not changed regarding analytics.

Any update were made to this module when between SDK 32 and SDK 33?

**Comment by cruzach** [comment]
Nothing is listed in the [changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md), and you can also take a look at the commit history for the [expo-analytics-amplitude module](https://github.com/expo/expo/tree/master/packages/expo-analytics-amplitude)

When updating to SDK 34, you do need to run `expo install expo-analytics-amplitude`. Have you already done that?

**Comment by jamesbechet** [comment]
@cruzach so I was able to "fix" the crashes.

I checked at the version of the Amplitude client you're using and my app would crash here: https://github.com/amplitude/Amplitude-Android/blob/v2.9.2/src/com/amplitude/api/AmplitudeClient.java#L1254

I used to call `Amplitude.setUserProperties` with an object with all kind of values: strings, numbers, null and nested objects. I tried removing nil values and I still saw problems.

I don't call it on Android and I don't have the crashes anymore. I also faced some issues with `logEventWithProperties` so now I only use `logEvent` and I don't get any crashes. Is there any known limitations with `org.json.JSONTokener` for nested objects?

**Comment by cruzach** [comment]
> Is there any known limitations with org.json.JSONTokener for nested objects?

Not that I'm aware of, but I'm not the most knowledgeable person on this subject

The [user properties docs](https://help.amplitude.com/hc/en-us/articles/207108327-Step-4-Set-User-Properties-and-Event-Properties#user-properties) from Amplitude might be able to shed a little light on what was going wrong

**Comment by jamesbechet** [comment]
Yes I read it already, but it's not very descriptive. Also, expo uses an old version of the Android client.

When I looked at Expo's functions' signatures, I assumed any data could be stored (which works in iOS). However, some Android devices break.

```
export declare function setUserProperties(userProperties: {
    [name: string]: any;
}): Promise<void>;
```

```
export declare function logEventWithProperties(eventName: string, properties: {
    [name: string]: any;
}): Promise<void>;
```

**Comment by superphil0** [comment]
I have a similar issue on two Samsung Devices in production:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at org.json.JSONTokener.nextCleanInternal + 116(JSONTokener.java:116)
       at org.json.JSONTokener.nextValue + 94(JSONTokener.java:94)
       at org.json.JSONObject.<init> + 159(JSONObject.java:159)
       at org.json.JSONObject.<init> + 176(JSONObject.java:176)
       at com.amplitude.api.DatabaseHelper.getEventsFromTable + 253(DatabaseHelper.java:253)
       at com.amplitude.api.DatabaseHelper.getEvents + 231(DatabaseHelper.java:231)
       at com.amplitude.api.AmplitudeClient.updateServer + 1522(AmplitudeClient.java:1522)
       at com.amplitude.api.AmplitudeClient.updateServer + 1494(AmplitudeClient.java:1494)
       at com.amplitude.api.AmplitudeClient$13.run + 1485(AmplitudeClient.java:1485)
       at android.os.Handler.handleCallback + 789(Handler.java:789)
       at android.os.Handler.dispatchMessage + 98(Handler.java:98)
       at android.os.Looper.loop + 164(Looper.java:164)
       at android.os.HandlerThread.run + 65(HandlerThread.java:65)

Is this related to this?

**Comment by superphil0** [comment]
It appears to me that the error happens here, when polling for new events:
v2.9.2 (currently used)
https://github.com/amplitude/Amplitude-Android/blob/2a24a849adb0569a86492e2598d607adeacc2355/src/com/amplitude/api/DatabaseHelper.java#L253

latest version
 https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/DatabaseHelper.java#L360

there is an extra check for null
 public static boolean isEmptyString(String s) {
        return (s == null || s.length() == 0);
    }

in the new version

so upgrading this Lib will fix the issue, can this be fast tracked for 7.0.0?
