### ISSUE TITLE
[docs] NetInfo docs page

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#5289]
A common broken link is to the latest version of NetInfo docs. Since we included the extracted lib (https://github.com/expo/expo/blob/master/packages/expo/bundledNativeModules.json#L3) We should have a page that explains how to install and use the community package then redirect to that.

**Comment by cruzach** [comment]
Redirect from `/v33.0.0/react-native/netinfo/` to  `/v33.0.0/sdk/netinfo/`? (and `/v34.0.0/react-native/netinfo/` to  `/v34.0.0/sdk/netinfo/`)
