### ISSUE TITLE
Splash screen not working + indicator/statusBar styling

### ISSUE THREAD

**Issue by sonaye** [expo/expo#529]
I have tried to implement the new API in many ways, all attempts failed. Tried building with the `--type simulator` flag and the actual build, no luck.

```
    "loading": {
      "backgroundColor": "#171717",
      "backgroundImage": "./full.png",
      "loadingIndicatorStyleExperimental": "light",
      "splash": {
        "backgroundColor": "#171717",
        "image": {
          "ios": {
            "backgroundImage": "./full.png"
          }
        }
      }
    },
```

Even tried using `backgroundImageUrl` instead of `backgroundImage`, https://github.com/expo/expo/blob/ae3d137e5128fd6ab8a37e042f628ad3e4285ee1/js/Browser/BrowserScreen.js#L336-L341

Also, it feels like there are many options at the moment, in addition to them being kind of confusing, I am sure some of them can be removed, what options should I keep in `app.json` to have both the splash screen and the loading component be a static full image on both platforms? I am thinking the following snippet should be enough to achieve that, but not sure.

```
    "loading": {
      "loadingIndicatorStyleExperimental": "light",
      "splash": {
        "backgroundImage": "./full.png", // android
        "image": {
          "ios": {
            "backgroundImage": "./full.png"
          }
        }
      }
    },
```

A couple of additional notes for future releases:
- `loadingIndicatorStyleExperimental` should be deprecated in favor of something like `loadingIndicatorColor` and `loadingIndicatorSize` to allow more customization.
- An option to completely hide the indicator is helpful as well, it's not the most pleasant piece of UI to be honest.
- On IOS, an option for styling the status bar when launching, `iosStatusBarMode` which accepts `light`, `dark` and `hidden` as values would be great.

We've been waiting for this feature for a long time, thanks for the great work.

**Comment by nsillik** [comment]
Hey, sorry you're having trouble with this new feature, it's still quite experimental and improvements are coming soon. I could use some info to help debug this:
1. What does your complete `app.json` look like?
2. What does your compiled manifest look like (get this by running `curl http://<your-experience>.exp.direct` and possibly piping it through `python -njson.tool` to make it look pretty).
3. Do you see any output relating to the `loading.splash.*` keys when running `exp` or through `xde`?

Also, I just created a really simple test project which I've verified works for me (i.e. running `exp build:ios -t simulator`) you can find that [here](https://github.com/nsillik/expo-splash-screen-example).

**Comment by sonaye** [comment]
@nsillik Before proceeding with debugging the situation, I want to make sure that we are on the same page about what the behavior of a splash screen should be. The splash screen essentially is the view that shows immediately the second you click the app icon, then it expands to take the full dimensions of the screen, basically the xib file in IOS in a typical rn app.

Attached is a gif of your example, you can see that the transition is white and not the splash screen defined in `app.json`, the splash screen is behaving like the loading screen now.

Please correct me if I am misunderstanding the correct behavior or whether the new api doesn't support the traditional splash screen idea.

See the third gif in https://github.com/expo/expo/issues/112, notice how when opening the expo app, the logo is there (gray), that's a splash screen, I am assuming that this is what was introduced as new feature here.

<img src="https://user-images.githubusercontent.com/23000873/29712882-b57b43ba-89a4-11e7-86ce-fbd05dce18eb.gif" width="400">

**Comment by nsillik** [comment]
@sonaye sorry it took a while to get back to you, this was an interesting issue to chase down. It's now fixed for me, try to `exp build:ios` again and let me know if it's working as expected. Also there are a number of improvements coming in SDK21, including better documentation and Android support.

**Comment by sonaye** [comment]
@nsillik Now that the original issue have been solved (by sdk 21), can you please take a look at the other notes?

> A couple of additional notes for future releases:
>
> - loadingIndicatorStyleExperimental should be deprecated in favor of something like loadingIndicatorColor and loadingIndicatorSize to allow more customization.
>- An option to completely hide the indicator is helpful as well, it's not the most pleasant piece of UI to be honest.
>- On IOS, an option for styling the status bar when launching, iosStatusBarMode which accepts light, dark and hidden as values would be great.

Tackling these would take the splash screen to the next level. They are easy to implement.

**Comment by sonaye** [comment]
Closing in favor of #542.
