### ISSUE TITLE
Stack Protection

### ISSUE THREAD

**Issue by gyurka00** [expo/expo#5292]
Our security team encountered a vulnerability that doesn't have "-fstack-protector" option the library.
Can you integrate it?

**Comment by cruzach** [comment]
Hey @gyurka00, could you be a little more descriptive?

**Comment by gyurka00** [comment]
Hi @cruzach,
 
Sorry for the short comment.
Our security team encountered a [Stack Smashing Protector](https://wiki.osdev.org/Stack_Smashing_Protector) issue.
To solve this problem the GCC has on option to turn on "-fstack-protector".
I check expo documentation about to find a flag in the app.json, but I didn't find.
So is it possible to integrate a flag that is turn on/off the GCC stack protection?

**Comment by brentvatne** [comment]
can you provide all of the context you have? as much information as possible. also please open a pull request to demonstrate where you believe this is necessary
