### ISSUE TITLE
Cant' record video with ImagePicker.launchCameraAsync

### ISSUE THREAD

**Issue by Vidlec** [expo/expo#5293]
## 🐛 Bug Report
Even when you pass media type `Videos` to `ImagePicker.launchCameraAsync` it doesn't allow you to record video. It forces you to take a photo instead.

### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.1 => 16.9.1 
      @types/react-native: ^0.60.04 => 0.60.4 
      expo: ^34.0.4 => 34.0.4 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 

### Steps to Reproduce

See snack

### Expected Behavior

When you pass Videos media type to ImagePicker.launchCameraAsync you can record video

### Actual Behavior

When you pass Videos media type to ImagePicker.launchCameraAsync it doesn't allow you to record video, only to snap a picture

### Reproducible Demo

https://snack.expo.io/@qest/thrilled-pretzels

**Comment by cruzach** [comment]
What device/OS is this happening on for you?

I just tried on iOS 12.4 and was able to record a video

**Comment by lukmccall** [comment]
@cruzach, We have code responsible for capture video in **unversioned** packages however we don't have it in **versioned** codebase.

**Comment by Vidlec** [comment]
This happens on Android. I wasn't able to test on iOS sadly.

**Comment by cruzach** [comment]
Thanks @lukmccall! Wasn't this included in `expo-image-picker v6.0.0`?

@Vidlec this was fixed in [PR 4903](https://github.com/expo/expo/pull/4903)

**Comment by Vidlec** [comment]
@cruzach Thats what i thought as well. But I encountered this issue when I was trying out the new version...

This is my `package.json`
![image](https://user-images.githubusercontent.com/8297118/62879741-1fb9ed00-bd2c-11e9-9f64-4192a669eea5.png)
And still I don't get video recording

**Comment by rxhivzero** [comment]
ios is work.
but android not work.

**Comment by hrastnik** [comment]
I can confirm this behaviour too.

Here's the repro: https://snack.expo.io/@hrastnik/imagepicker-launchcameraasync-issue

My device is Google Pixel 2 XL, Android version 10.

**Comment by eyemovic-oie** [comment]
I have same issue.
I use Pixel 3 (Android 9.0)

https://snack.expo.io/@hrastnik/imagepicker-launchcameraasync-issue
The same is true for the above sample.

**Comment by lukmccall** [comment]
In expo client, it should work correctly on SDK 35 (it will be fully published later today).
However, if you build a standalone app or use bare workflow, recording video should work with expo-image-picker v6.0.0. 
If something goes wrong, you could always try the new version of image-picker (7.0.0).

**Comment by Vidlec** [comment]
@lukmccall 
I can confirm that his is indeed working now in `SDK 35` and `expo-image-picker (7.0.0)`

Thank you! 🙏
