### ISSUE TITLE
Expo standalone app crashes on map view

### ISSUE THREAD

**Issue by samisamsam** [expo/expo#5294]
I have a big issue with an app that i'm trying to pusblish on prod. Everything is ok when i'm coding on expo start, but when i'm creating a standalone apk and test the app, it crashes when i'm trying to open a view which have expo map view on it. The app just restart when i'm trying to get this view

**Comment by cruzach** [comment]
Make sure you've followed all the standalone app instructions for adding `MapView` [here](https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android)! If the problem still persists after that, I'd try running locally in production mode (use `expo start --no-dev --minify`) to try and get the error to surface there.

After that, if you still can't get it to work, please go back and edit your post to follow the [issue template](https://github.com/expo/expo/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) we provide (it asks for all the information we need to help you as best we can)

**Comment by samisamsam** [comment]
Thanks for your answer

**Comment by samisamsam** [comment]
Can you help me please i can't see tthe problem ?
 "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.novatecweb.fidlink",
      "config": {
        "googleMaps":{
          "apiKey": "Key"
        }
      }
    },
    "android": {
      "package": "com.novatecweb.fidlink",
      "config": {
        "googleMaps":{
          "apiKey": "Key"
        }
      },

Tunnel ready.
Publishing to channel 'default'...
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v32.0.0/workflow/configuration/
 • Field: ios.config - should NOT have additional property 'googleMaps'.
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.

**Comment by cruzach** [comment]
Refer to the docs I linked above, one of your keys is the wrong name
Under `iOS.Config`, you should have `googleMapsApiKey` -- NOT `apiKey`

**Comment by samisamsam** [comment]
Thanks a lot for your help. Now the standalone apk its not crashing but i have no display of the map

**Comment by samisamsam** [comment]
> Thanks a lot for your help. Now the standalone apk its not crashing but i have no display of the map

Nevermind my problem is solved. Thank you.

**Comment by samisamsam** [comment]
My bad, i forgot to test it on Ios before send this answer. ts ok on Android, but on Ios there's only the ocean and nothing else.
