### ISSUE TITLE
[TypeScript] Jest tests using 'expo-localization' or '@expo/vector-icons' throw Syntax Error: Unexpected Identifier

### ISSUE THREAD

**Issue by Gi11i4m** [expo/expo#5296]
## 🐛 Bug Report
When testing files using the following imports 
```typescript
import { locale } from 'expo-localization';
import { createIconSetFromIcoMoon } from '@expo/vector-icons';
```
the following error will be thrown
```bash
SyntaxError: Unexpected identifier
```
about these libraries' internal imports
```javascript
import ExpoLocalization from './ExpoLocalization';
import createIconSet from './createIconSet';
```

### Environment
```
Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.19 => 16.8.23 
      @types/react-native: ^0.57.60 => 0.57.65 
      expo: ^34.0.4 => 34.0.4 
      react: ^16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9
```

Mainly targetting the latest iOS for now.

### Steps to Reproduce
(Assuming `bash`, `expo` and `yarn` installations)
- `expo init`
- `yarn add -D ts-jest @types/jest @types/react @types/react-native`
- `yarn add jest expo-localization`
- Use [this guide](https://kulshekhar.github.io/ts-jest/user/react-native/) to integrate ts-jest
**Apparently the bug already occurs even without ts-jest**
- Write a test that uses a file importing `{ locale }` from `expo-localization` or `{ createIconSetFromIcoMoon }` from `@expo/vector-icons`

### Expected Behavior
Tests using the `expo-localization` and `@expo/vector-icons` libraries run just as smoothly as other tests.

### Actual Behavior
Tests using the `expo-localization` and `@expo/vector-icons` libraries throw the following error:

```bash
$ jest
 FAIL  ./demo-bug-localization.spec.ts
  ● Test suite failed to run

    /Users/gilliamf/Projects/ts-jest-import-bug-demo/node_modules/expo-localization/build/Localization.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import ExpoLocalization from './ExpoLocalization';
                                                                                                    ^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

    > 1 | import { locale } from "expo-localization";
        | ^
      2 | 
      3 | export class Localization {
      4 |   getCurrentLocale() {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at Object.<anonymous> (localization.ts:1:1)

 FAIL  ./demo-bug-vector-icons.spec.ts
  ● Test suite failed to run

    /Users/gilliamf/Projects/ts-jest-import-bug-demo/node_modules/@expo/vector-icons/build/AntDesign.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createIconSet from './createIconSet';
                                                                                                    ^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
```

### Reproducible Demo
A very minimal demo reproducing the issue can be found [right here](https://github.com/Gi11i4m/ts-jest-import-bug-demo).

**Comment by ide** [comment]
It looks like `import` isn't being transformed  -- are you using jest-expo and the jest-expo preset?

**Comment by Gi11i4m** [comment]
> It looks like `import` isn't being transformed -- are you using jest-expo and the jest-expo preset?

Yes, that's indeed what it looks like. I also found that there were still import statements in the bin/ 
 or build/ directories of these libraries, in which I would assume should only be transpiled files.

No, I'm not using those presets. If I use it in my repro demo I get the following error:
```bash
FAIL  ./demo-bug-vector-icons.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/gilliamf/Projects/ts-jest-import-bug-demo/node_modules/jest-expo/src/index.js:1
    (function (exports, require, module, __filename, __dirname) { import { Platform as PlatformExpo } from '@unimodules/core';
                                                                         ^

    SyntaxError: Unexpected token {

      at Module._compile (node_modules/pirates/lib/index.js:99:24)
```

**Comment by ide** [comment]
I believe if you run `expo init` and choose the tabs template you will get a project that includes Jest already set up. I would try creating a new project (just for testing) and then pull over parts of that working test config into your existing project.

As it stands, it is intentional that all these libraries contain `import`/`export` and need extra compilation. (Even with Node versions that support `import`/`export`, Jest needs to transform them so that it can inject mock dependencies.) jest-expo is designed to support this but if you wanted to write your own preset that did the same thing of course that would work too.
