### ISSUE TITLE
[expo-av] pauseAsync executed with few hundred milliseconds delay

### ISSUE THREAD

**Issue by riwu** [expo/expo#5297]
### Environment
  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: Using globally installed version of Yarn
1.12.1 - /opt/facebook/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.4 - /opt/facebook/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8

iOS, Client

### Steps to Reproduce
1. Call `Video.pauseAsync()`
2. Call `Video.playAsync()`

### Expected Behavior
Video should resume from exactly when `pauseAsync()` is called.

### Actual Behavior
Video resumes from a few hundred milliseconds after `pauseAsync()` is called.

### Reproducible Demo
https://snack.expo.io/@riwu/video-onload

Observe that the video time moves forward by a few hundred milliseconds when `pauseAsync()` is executed.

![Untitled](https://user-images.githubusercontent.com/2226023/62879906-b6070680-bd5e-11e9-8afc-e14b64bd6f7e.gif)

```
import React from 'react';
import { View, StyleSheet, Button, Alert, Text } from 'react-native';
import { Video } from 'expo-av';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

class App extends React.Component {
  state = {
    time: 0,
    playing: false,
  };
  video = React.createRef();

  render() {
    return (
      <View style={styles.container}>
        <Video
          ref={this.video}
          source={{
            uri: 'http://techslides.com/demos/sample-videos/small.mp4',
          }}
          isLooping
          onPlaybackStatusUpdate={status =>
            this.setState({ time: status.positionMillis })
          }
          style={{ width: 100, height: 100 }}
        />
        <Button
          title={this.state.playing ? 'Pause' : 'Resume'}
          onPress={() => {
            if (this.state.playing) {
              this.video.current.pauseAsync();
            } else {
              this.video.current.playAsync();
            }
            this.setState(prevState => ({ playing: !prevState.playing }));
          }}
        />
        <Text>{this.state.time}</Text>
      </View>
    );
  }
}

export default App;
```

@sjchmiela

**Comment by riwu** [comment]
Any progress on this? It makes `expo-av` practically unusable.

**Comment by karam94** [comment]
I have this problem too. Unfortunately it doesn't look like there's any interest in fixing it, so I'll have to migrate away from using expo-av some time further down the line I would guess. 

*sigh*

**Comment by t1gu1** [comment]
Try to change that:
```javascript
<Button
          title={this.state.playing ? 'Pause' : 'Resume'}
          onPress={() => {
            if (this.state.playing) {
              this.video.current.pauseAsync();
            } else {
              this.video.current.playAsync();
            }
            this.setState(prevState => ({ playing: !prevState.playing }));
     }}
/>
```

To this:
```javascript
<Button
          title={this.state.playing ? 'Pause' : 'Resume'}
          onPress={() => {
            if (this.state.playing) {
              this.video.current.pauseAsync.then(() => {
                        this.setState(prevState => ({ playing: !prevState.playing }));
              });
            } else {
              this.video.current.playAsync().then(() => {
                        this.setState(prevState => ({ playing: !prevState.playing }));
              });
         }
    }}
/>
```

**The point here is the player don't really love when you re-render just when the play/pause async isn't finish.** you'll see that will be a lot faster to see the action.

Also, please don't set a state in onPlaybackStatusUpdate.. It's a bit insane to re-render that much. Use a `useRef().

**Comment by valentinsld** [comment]
No other solution ? 😕

**Comment by RSSfeed** [comment]
any update?

**Comment by alexandertyler** [comment]
Pinging on this thread again.

**Comment by hirbod** [comment]
Not only does it take few hundred milliseconds, it drops UI FPS from 60 down to 20-30 ish. I also posted an issue about this but there is barley any response on issues at all, only stale bits closing down legit issues…

**Comment by hirbod** [comment]
The root cause is described here:
https://github.com/expo/expo/issues/15873

But the "workaround" is most likely only working for videos and haven't been checked against audio.

**Comment by bbarthec** [comment]
Some changes in the following packages that may fix this issue have just been published to npm under `next` tag 🚀

| 📦 Package | 🔢 Version | ↖️ Pull requests | 📝 Release notes |
|:--:|:--:|:--:|:--:|
| [expo-av](https://www.npmjs.com/package/expo-av/v/11.1.0) | 11.1.0 | #16578 | [CHANGELOG.md](https://github.com/expo/expo/blob/main/packages/expo-av/CHANGELOG.md) |

If you're using bare workflow you can upgrade them right away. We kindly ask you for some feedback—even if it works 🙏

They will become available in managed workflow with the next SDK release 👀

Happy Coding! 🎉
