### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ViewManagerAdapter_ExponentCamera" was not found in the UIManager.

### ISSUE THREAD

**Issue by derekstavis** [expo/expo#5300]
### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.0 - /usr/local/bin/fish
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
```

The issue happened on an Android device model Samsung Galaxy A3 (SM-A320FL).

### Steps to Reproduce

The reproduction is not clear. I don't have such device to test, but it seems to be a race condition, since the user that had this issue was able to use the camera before.

### Expected Behavior

Camera should _either_ always crash _or_ never crash.

### Actual Behavior

On mount, the `Camera` component crashes with error:

```
Invariant Violation: Invariant Violation: requireNativeComponent: "ViewManagerAdapter_ExponentCamera" was not found in the UIManager.
```

See the sentry stack trace:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1611639/62892344-e8801780-bcfc-11e9-8dc2-2e7dc3d174b3.png">

### Reproducible Demo

As said before, it's hard to reproduce. Our code doesn't do any trick with the camera:

```tsx
      <Camera
        style={styles.fill}
        type={Camera.Constants.Type.back}
        ref={this.cameraRef}
      >
        {content}
      </Camera>
```

**Comment by esamelson** [comment]
Looks like this was fixed by the commit referenced above, so I'm going to go ahead and close this issue. If it still happens on a currently supported SDK version, please open a new issue with a full repro case. Thanks!
