### ISSUE TITLE
expo-server-sdk: Heads-up Notifications for Android

### ISSUE THREAD

**Issue by khuang-citylift** [expo/expo#5302]
Hi, I am using the expo-server-sdk to send push notifications. Heads-up notifications do not show up for Android. I have been searching around for a solution and one solution was to set the priority for the message to 'high'. 

```
messages.push({ 
				...

				priority: 'high',
	
				...
			});
```

However, that does not work. 

Another solution was to create a channel. However, I am using the server side SDK and I do not see any functions for creating channels. Is there a solution for this or is heads-up notifications still not supported on Android?

Thanks

**Comment by cruzach** [comment]
Hi! So you won't use the server-sdk for creating a channel, you would use [`Notifications. createChannelAndroidAsync`](https://docs.expo.io/versions/latest/sdk/notifications/#android-channels), and then pass in the [channelId](https://github.com/expo/expo-server-sdk-node/blob/master/src/ExpoClient.ts#L353) in your push messages

(Note that this is only available on On Android 8.0+)

**Comment by khuang-citylift** [comment]
Thanks for the response Charlie.
My understanding is that the Notifications library is used in my frontend React Native app for local notifications. However, I am creating the notifications in my Node.js backend server.

Are you suggesting that I import Notifications to my Node?

**Comment by khuang-citylift** [comment]
It looks like the expo-server-sdk for Node.js does not have the Notifications module.

In my Node:

```
const { Expo } = require('expo-server-sdk');
Expo.Notifications.createChannelAndroidAsync({
			priority: 'max',
			channelId: 'pushChannel',
		});
```

Error:
`TypeError: Cannot read property 'createChannelAndroidAsync' of undefined`

**Comment by cruzach** [comment]
Sorry, I don't think I was clear. 

> Are you suggesting that I import Notifications to my Node?

No. You'll create the channel in your app. Then, when sending a notification, you pass in a `channelId` in your [message format](https://docs.expo.io/versions/latest/guides/push-notifications/#message-format)

**Comment by khuang-citylift** [comment]
Hi Charlie,

If I create the channel in my app, then how would my backend know of the channel's existence?

I am doing the push notifications in my Node following the guide here: https://github.com/expo/expo-server-sdk-node

**Comment by khuang-citylift** [comment]
In my app's componentDidMount(), I have:

```
componentDidMount() {
		if (Platform.OS == 'android') {
			Notifications.createChannelAndroidAsync('pushChannel', {
			    name: 'pushChannel',
			    sound: true,
			  });
		}
	}
```

In my node server I have:
```
messages.push({ 
				to: token,
				priority: 'max',
				sound: 'default',
				body: 'Your vehicle is ready for pick up.',
				data: { withSome: 'data' },
				channelId: 'pushChannel',
			});
```

However, heads-up notifications are still not showing up for Android. Just like before, it shows in the background and I have swipe down from the top to see the notification.

**Comment by khuang-citylift** [comment]
**Another update:**

I got it working by wiping the device (emulator), and restarting expo with `expo start -c`.
