### ISSUE TITLE
Expo modules no longer getting installed automatically? (SDK 34)

### ISSUE THREAD

**Issue by andersravn** [expo/expo#5305]
Hi.

I just upgraded from SDK 33 to 34 (ExpoKit). Already in SDK 33 we changed to the new imports, and all dependencies such as expo-analytics-amplitude were automatically installed. However, after upgrading to SDK 34 I get `Unable to resolve "expo-analytics-segment" from "path/to/file/bla.js"` and indeed it is not present in `node_modules`. Do we need to install all these manually now using `expo install`? I just don't see that mentioned in https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319. It mentions switching to the new imports just like in the blog post for SDK 33, but not the above imo, only .

I just want to make sure that I actually have to do this manually now, as I don't want to diverge from the setup you guys have. It took me a week to upgrade from SDK 30 to 33, because so much had changed in the native project structure.

**Comment by raajnadar** [comment]
From sdk 34 we need to install all the expo-* packages manually. You maybe wonder why?? Right??

This is to reduce the app size (apk and ipa) and to remove modules that are not required in the final build. Till sdk 33 all the expo-* modules were installed in the main package.json of expo/expo repo now we need to install required modules with `expo install <module-name>`.

ExpoKit is pain wait for bare workflow.. it will reduce a lot of issues.

**Comment by cruzach** [comment]
Hey @andersravn, in the blog post you linked, we state
> To remedy this, you should use the `expo install` command to install modules

Thanks for explaining this @raajnadar!

**Comment by andersravn** [comment]
Sorry to be nitpicking, but that statement does not relate directly to my problem. That statement is in relation to importing from the monolith expo package. I was not doing that. It's just very important that you guys are crystal clear in your communication. Something like this would be more clear: In SDK 33 you were asked to import from the individual expo libraries, which were all installed automatically. In SDK 34 you also have to install all these individual libraries, using expo install, as they are no longer installed automatically.

I don't know. I've just come across quite a few ambiguities/in-complete documentation in the Expo docs the last year. Maybe it's just me who need it explained like a 5-year-old.

**Comment by cruzach** [comment]
Sorry it wasn't clear that you have to run `expo install` for those modules @andersravn, thanks for suggesting that edit! We've updated the blog post.

Really sorry you haven't been happy with Expo's documentation this year. We really want to make our docs as clear as possible, so if you happen to remember any specifics about what parts you found confusing, please lmk and I can work to fix those pages up

**Comment by andersravn** [comment]
Thanks for listening. I really appreciate what you guys are doing. I'll let you know if I stumble upon something.

**Comment by nabeel-s** [comment]
I am getting the following error when trying to build with SDK 34:

![](https://aws1.discourse-cdn.com/business5/uploads/expo/original/2X/7/7c1394ac382c81b5e8a9af87546b01a5d6db8302.png)

I have manually installed all expo-* modules from package.json.

**Comment by andersravn** [comment]
@nabeel-s did it complain about this package missing? We might not have to install all expo-* packages manually yet. For example, we use expo-linear-gradient, and didn't have to install it manually, yet. So maybe it is installed twice?

**Comment by nabeel-s** [comment]
@andersravn, it didn't complain about the package missing, but installing it made no difference to the error message. It seems to be related to some deprecated modules.

**Comment by raajnadar** [comment]
@cruzach when can we expect the new feature to remove unused Expo SDK modules?

> After moving from expo 34, my app size increased from 15Mb to 46Mb for both App bundle and APK as well, even in google play store its showing around 25 Mb for app bundle, i think this is pretty huge size for a simple application.

https://expo.canny.io/feature-requests/p/reducing-app-size

**Comment by cruzach** [comment]
You can choose exactly what modules to include/exclude now if you use the bare workflow

Otherwise optional modules will only be for **certain** modules, not all of them, and it's still early in the process

**Comment by raajnadar** [comment]
If I am wrong the only limitation at the moment with bare workflow is OTA update right?

**Comment by cruzach** [comment]
this is the best resource to see the difference between the workflows- https://docs.expo.io/versions/latest/introduction/managed-vs-bare/

We're working on expanding the feature set of the bare workflow, but right now it doesn't support Expo's build service, OTA updates, or Expo Push Notifications
