### ISSUE TITLE
barCodeTypes ignored

### ISSUE THREAD

**Issue by matteofrana** [expo/expo#5309]
Even if I set
```
barCodeTypes={[BarCodeScanner.Constants.BarCodeType.qr]}
```
the onBarCodeScanned event fires for linear barcodes too (for example with type 32).

**Comment by cruzach** [comment]
Is this on Android or iOS? Could you use [this snack](https://snack.expo.io/@charliecruzan/barcodescanner-example) as a base and create a reproducible example of the issue? 

Please fill out the entire issue template, that's the best way for us to help you!

**Comment by cruzach** [comment]
Closing for lack of info, and I couldn't reproduce. If you see this issue, please provide a reproducible demo and I'll reopen 🙂
