### ISSUE TITLE
iOS simulator crashes when using Camera

### ISSUE THREAD

**Issue by DerJacques** [expo/expo#531]
Excited about the new Camera component in Expo 20, I tried replacing `react-native-camera` with the Expo implementation.

It works great on a real device, but in the simulator I receive this error:

![image](https://user-images.githubusercontent.com/3896442/29561012-32b695dc-8734-11e7-9100-80e3bd5e9dfc.png)

This seems to be related to the fact that the simulator obviously doesn't have a camera.
`react-native-camera` solves this issue by simply displaying a black square where the camera input would have been, and whenever a picture is taken the picture is simply a coloured square with a timestamp.

Any way to circumvent this error in Expo?

**Comment by aalices** [comment]
@DerJacques I'll take care of this, should be fixed soon

**Comment by CSamuelLents** [comment]
@aalices 

Any word on this? Thanks for working on it!

**Comment by aalices** [comment]
@CSamuelLents It's in review. I am not sure if it will be released before SDK 21. We'll keep you informed.

**Comment by vysakh0** [comment]
@aalices The camera works perfectly in Android (both front and back). In iOS, I couldn't get the front camera working, also the image captured is a total black image. Thanks for the awesome project, it'd be really helpful if this camera module was working :+1: 

```
# package.json
{
  "name": "mirror",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native-aws3": "^0.0.8",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz"
  }
}
```

**Comment by aalices** [comment]
@vysakh0 Would you mind creating a new issue and providing some more info? What device this is, system version and some code sample.

**Comment by bwalsh** [comment]
Getting same issue on  expo Version 2.20.1 (2.20.1),  Version 10.0 (SimulatorApp-700.5.3

**Comment by luisaverza** [comment]
There is a solution? I'm having the same problem here. 
And when I dismiss the error I get a black screen with the Flip button right.
```Expo 1.20.1
Version 10.0 (SimulatorApp-829.6 ```

**Comment by aalices** [comment]
@luisaverza what sdk are you using? (number in your `app.json` under `sdkVersion`)

**Comment by luisaverza** [comment]
Hi @aalices . I'm using ` "sdkVersion": "20.0.0" `

**Comment by aalices** [comment]
@luisaverza Give it a try with SDK 21, should work fine
