### ISSUE TITLE
[expo-av] Android build fails with "cannot find symbol class Nullable"

### ISSUE THREAD

**Issue by lgraubner** [expo/expo#5310]
### Environment

Bare React Native app with Expokit
react-native@0.60.4
react@16.8.6
expo-av@6.0.0
react-native-unimodules@0.5.4

### Steps to Reproduce

```
npm run android
```

### Expected Behavior

Should build project without issues.

### Actual Behavior

Build fails with the following error:

```
error: cannot find symbol class Nullable
```

I migrated my project to AndroidX and run jettifier on build. It doesn't matter if I build with Android Studio or via React Native CLI.

### Reproducible Demo

Sadly hard to share as it's directly tied to the build process.

**Comment by cruzach** [comment]
In Expokit, your version of `react-native` should be pointing to Expo's fork of React Native. In the bare workflow, it's usually best to to use the same version as the one we use for the current sdk

I'm not sure if you're in bare or Expokit. When you ejected, you should've been able to choose between those two options, so let me know which one you went with and we can narrow this problem down.

**Comment by creativemind1** [comment]
I'm also facing the exact issue. I'm in ExpoKit: 
`"expokit": "^34.0.2",`
`"react-native": "https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz",`

How do I resolve this?.

**Comment by lgraubner** [comment]
@cruzach Originally the project was created without Expo (`react-native init`). I added expo kit afterwards and use the original React Native. Worked fine for me so far. iOS also works without any problems.

**Comment by cruzach** [comment]
Ah okay, sounds like bare workflow then

Can you try with the version of `react-native` supported in the most recent Expo SDK? would be `v0.59.8`

**Comment by irothenbaum** [comment]
Not sure if this post is contributing, but I'm in the same boat. Ejecting from expo was a headache and a half so I started a new project with `react-native init` and have been adding the expo modules back in.

All the ones I was using (see below) work except for expo-av. I suspect it has everything to do with react-native being version `^0.60.0` because of [this](https://stackoverflow.com/a/54605272/657280), but curious that only expo-av has a problem. Would be nice if jetifier would migrate it to AndroidX also as I understand it does with other legacy libraries.

```
    "expo-av": "^6.0.0",
    "expo-barcode-scanner": "^6.0.0",
    "expo-contacts": "^6.0.0",
    "expo-image-picker": "^6.0.0",
    "expo-linear-gradient": "^6.0.0",
    "expo-location": "^6.0.0",
    "expo-permissions": "^6.0.0",
```

**Comment by rogerlopz** [comment]
I think its because the expo-av package needs to update its dependencies.

Im getting the same error:
![Screenshot from 2019-08-19 11-01-47](https://user-images.githubusercontent.com/4995589/63280659-d52afa00-c270-11e9-860f-4160b3ed6ac8.png)

**Comment by rogerlopz** [comment]
```gradle
dependencies {
  unimodule "unimodules-core"
  unimodule "unimodules-permissions-interface"
  // Newer version introduces dependency versions conflict
  // on 'com.android.support:support-annotations'
  api 'com.google.android.exoplayer:exoplayer:2.9.2'

  api 'com.google.android.exoplayer:extension-okhttp:2.9.2'

  api 'com.yqritc:android-scalablevideoview:1.0.1'

  api "com.squareup.okhttp3:okhttp:3.10.0"
  api "com.squareup.okhttp3:okhttp-urlconnection:3.10.0"
}
```
This is in the build.gradle file of the expo-av package. I think we have to wait until the update that.

**Comment by dangrahn** [comment]
@rogerlopz same problem here.

> I think its because the expo-av package needs to update its dependencies.

Do you know dependencies would need to be updated? I tried to patch it but this didn't help.

```diff
diff --git a/node_modules/expo-av/android/.DS_Store b/node_modules/expo-av/android/.DS_Store
new file mode 100644
index 0000000..163341d
Binary files /dev/null and b/node_modules/expo-av/android/.DS_Store differ
diff --git a/node_modules/expo-av/android/build.gradle b/node_modules/expo-av/android/build.gradle
index 2d3568e..7ba6a9b 100644
--- a/node_modules/expo-av/android/build.gradle
+++ b/node_modules/expo-av/android/build.gradle
@@ -5,7 +5,7 @@ buildscript {
   }

   dependencies {
-    classpath 'com.android.tools.build:gradle:3.1.3'
+    classpath 'com.android.tools.build:gradle:3.3.0'
   }
 }

@@ -69,11 +69,10 @@ if (new File(rootProject.projectDir.parentFile, 'package.json').exists()) {
 dependencies {
   unimodule "unimodules-core"
   unimodule "unimodules-permissions-interface"
-  // Newer version introduces dependency versions conflict
-  // on 'com.android.support:support-annotations'
-  api 'com.google.android.exoplayer:exoplayer:2.9.2'

-  api 'com.google.android.exoplayer:extension-okhttp:2.9.2'
+  api 'com.google.android.exoplayer:exoplayer:2.9.5'
+
+  api 'com.google.android.exoplayer:extension-okhttp:2.9.3'

   api 'com.yqritc:android-scalablevideoview:1.0.1'
```

**Comment by devNimi** [comment]
I'm facing the same issue, it kept throwing following errors
and my build is failing
<img width="1355" alt="Screenshot 2019-08-30 at 9 41 17 PM" src="https://user-images.githubusercontent.com/13298263/64035665-f8a64c80-cb6e-11e9-8321-5ae3b8f163ef.png">

**Comment by beaurushton** [comment]
Adding ` api 'com.android.support:support-annotations' ` into the dependencies in the node_modules/expo-av/android/build.gradle seemed to help for me.

**Comment by lgraubner** [comment]
@beaurushton That works for me as well. I created a pull request.

**Comment by Speedy1991** [comment]
@beaurushton This will break the dependencies with e.g. codepush - you will have to set `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true` to have a working expo-av/codepush implementation

This will also fail with `react-native-gesture-handler` because as soon we enable

```
android.useAndroidX=true
android.enableJetifier=true
```
expo-av won't be able to compile again (same error as above)

**Comment by Speedy1991** [comment]
Found a running fix:
- Apply your patch
- `yarn add -D jetifier`

Add this to your `package.json`:
```
"android": "node node_modules/react-native/local-cli/cli.js run-android",
"preandroid": "npx jetify",
```
Jetify [docs](https://github.com/mikehardy/jetifier)

Add this to your `gradle.properties`:

```
android.useAndroidX=true
android.enableJetifier=true
```

Run `yarn android`

This will patch every project without androidx to androidx

**Comment by lgraubner** [comment]
This is what I'm doing as stated in my initial issue. This is not a migration to AndroidX, but compatibility for using jettifier to enable AndroidX.

**Comment by sjchmiela** [comment]
On `expo-av@7.0.1` this bug should be fixed, thanks @lgraubner!

**Comment by Luckygirlllll** [comment]
I have the same error with expo-constants in ExpoKit 35 version

**Comment by Luckygirlllll** [comment]
@sjchmiela Why this issue was closed? what is the working solution of this problem?

**Comment by Luckygirlllll** [comment]
@sjchmiela And what do you exactly mean by "configure Jetifier properly"?

**Comment by sjchmiela** [comment]
Installing and running sth like https://github.com/mikehardy/jetifier (something like https://developer.android.com/studio/command-line/jetifier, but for prepared specifically for React Native modules).

**Comment by vladp** [comment]
@getting the same error in bare flow.

using expo-av 7.0.1

We have
```
android.enableBuildCache=true
android.useAndroidX=true
android.enableJetifier=true
```

What steps are needed to properly configure jettifier to be used for expo-av >= 7.0.1 ?

**Comment by brentvatne** [comment]
@vladp - if you init a new bare workflow project it has jetifier set up and you can look at that as an example

**Comment by vladp** [comment]
@brentvatne thank you. it helped. I was missing jettifier in package.json and having it run on all node_modules as part of the postinstall.

**Comment by mazenongithub** [comment]
> Found a running fix:
> 
> * Apply your patch
> * `yarn add -D jetifier`
> 
> Add this to your `package.json`:
> 
> ```
> "android": "node node_modules/react-native/local-cli/cli.js run-android",
> "preandroid": "npx jetify",
> ```
> 
> Jetify [docs](https://github.com/mikehardy/jetifier)
> 
> Add this to your `gradle.properties`:
> 
> ```
> android.useAndroidX=true
> android.enableJetifier=true
> ```
> 
> Run `yarn android`
> 
> This will patch every project without androidx to androidx

Android MESSIAH!
