### ISSUE TITLE
Is there a way to check Device Model in Simulator?

### ISSUE THREAD

**Issue by KendoJaaa** [expo/expo#5316]
I want to know the Device model on the simulator I'm using but I don't know how to. 

this is what I print from Constants.Platform
```
Object {
  "ios": Object {
    "buildNumber": null,
    "model": "Simulator",
    "platform": "x86_64",
    "systemVersion": "12.1",
    "userInterfaceIdiom": "handset",
  },
}
```
But there is no data, what model of my simulator is for example iphone X, iphone 5. 

Where I can get those data? or there is no way we can get the data currently?

**Comment by AdamJNavarro** [comment]
Hey @KendoJaaa,

Would you mind creating a [forum post](https://forums.expo.io/) for this? We reserve Github issues for reproducible bugs and try our best to redirect questions of this nature to our forums!

Cheers,
Adam

**Comment by KendoJaaa** [comment]
I will @AdamJNavarro. :)
