### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by deadcoder0904** [expo/expo#5319]
## 🐛 Bug Report

I tried it multiple times. Live Reloading works but Hot Reloading does not work. As @brentvatne said in an Expo Forum, I also tried opening & closing Expo app but still doesn't work.

Even when I save the file, I don't see the output in Terminal which I see if I choose Live Reload. By output, I mean `Finished building JavaScript bundle in 33ms. Running the application on iPhone X.`. This I see with Live Reload & if my memory serves right this used to be seen with Hot Reload.

### Environment

```bash
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
```

**Comment by dereknelson** [comment]
hi! this doesn't have anything to do with expo - hot reloading has had many ongoing issues, but Dan Abramov (originally creator of hot reloading) is [introducing a new version](https://twitter.com/dan_abramov/status/1144630328142831616) in RN .61!!

**Comment by deadcoder0904** [comment]
yeah, I know about that... I think its fast reloading but what does it have to do with expo? when will expo support the new version...also hot reloading used to work until the latest version. how do I know? I made a lot of projects in previous months 😂

**Comment by dereknelson** [comment]
@deadcoder0904 it doesn't have anything to do with expo - neither does hot reloading. hot reloading working is a matter of the react native version. it not working with expo's latest version simply means it doesn't work with the react native version expo uses in the latest version. 

0.61 hasn't even had a release candidate so it's impossible to estimate when expo will support the new version.

**Comment by deadcoder0904** [comment]
ahh cool got you now

**Comment by ImAbhishekTomar** [comment]
Anyone help on this issue it’s looks 👀 related... @5755

https://github.com/expo/expo/issues/5755

**Comment by cruzach** [comment]
Hot reloading is being replaced with fast refresh, here's the relevant PR https://github.com/expo/expo/pull/6110
