### ISSUE TITLE
Cannot login with expo cli

### ISSUE THREAD

**Issue by Xachman** [expo/expo#532]
Using the command ***expo login*** interactively Im unable to login.  Setting the environment variable EXPO_DEBUG to true gives me this output;

`[exp]
[exp] Error
    at _formatAuth0NodeError (C:\xdl\src\User.js:801:14)
    at C:\xdl\src\User.js:692:15
    at throw (native)
    at step (C:\Users\dell precision\AppData\Roaming\npm\node_modules\exp\node_modules\xdl\build\User.js:188:191)
    at C:\Users\dell precision\AppData\Roaming\npm\node_modules\exp\node_modules\xdl\build\User.js:188:402
`

**Comment by jimmylee** [comment]
What version of `exp` are you using? can you reinstall `exp` globally if you're not at version `44`?

**Comment by Xachman** [comment]
This morning I was able to login with the cli and had no errors

**Comment by dikaiosune** [comment]
Glad to hear it! I'm assuming that this was due to a temporary network outage, but please reply back if you find this is occurring regularly. Thanks!

**Comment by madaviela** [comment]
i cant login in exp cli... i only can see this ---> 

`[exp] Invalid or unexpected token
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.`


but i dont know where i need set that variable, im using mac OS...

**Comment by pbrewczynski** [comment]
I think there could be an issue when working via proxy. My environment was quite well prepared to work with proxy (all environmental vars set up properly) but there is possibility that this tool ignores it or have it's own settings or envs to set.

**Comment by raulvictorrosa** [comment]
Abouth `EXPO_DEBUG=true` run this  command `export EXPO_DEBUG=true`

**Comment by ourway** [comment]
Same error here.  I can only login with XDE not cli.

**Comment by samanthasheadavis** [comment]
I'm having issues logging in with the CLI as well, seeing `the connection was disabled` message.

**Comment by fermyth** [comment]
Earlier i got the same error seeing "the connection was disabled".

my expo cli version is 48.0.2

what i've done is run npm install -g exp and updated my expo cli to version 54.0.0 and i can login normally.
