### ISSUE TITLE
VideoThumbnails not work when SAMSUNG phone.

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo#5320]
### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.1.11 => 3.1.11 
      expo: 34.0.4 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: 3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9

android SAMSUNG phone
### Steps to Reproduce
use VideoThumbnails.getThumbnailAsync in Galaxy S8 or Galaxy S9
will Flash back.

example
const { uri } = await VideoThumbnails.getThumbnailAsync(
        videoUri,
        {
          compress: 0.7,
          time: 0,
        }
)

**Comment by AdamJNavarro** [comment]
Hey @rxhivzero,

I just tested the `VideoThumbnails` module on a Galaxy 8 and it works as expected. You can test in this [snack](https://snack.expo.io/@adamjnav/bd752c) and here's a screenshot of the test:  
![Screenshot_20190814-123149_Expo](https://user-images.githubusercontent.com/8992878/63043439-dc798e80-be91-11e9-8a88-4709b8602908.jpg)

Cheers,
Adam

**Comment by rxhivzero** [comment]
Hi  @AdamJNavarro
is form ios take MOV file.
use in s8 not work.
but my sony x1 is work.

like

import React from 'react';
import { StyleSheet, Button, View, Image, Text } from 'react-native';
import * as VideoThumbnails from 'expo-video-thumbnails';

export default class App extends React.Component {
  state = {
    image: null,
  };

  generateThumbnail = async () => {
    try {
      const { uri } = await VideoThumbnails.getThumbnailAsync(
        'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
        {
          time: 100,
        }
      );
      this.setState({ image: uri });
    } catch (e) {
      console.warn(e);
    }
  };

  render() {
    const { image } = this.state;
    return (
      <View style={styles.container}>
        <Button onPress={this.generateThumbnail} title="Generate thumbnail" />
        {image && <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />}
        <Text>{image}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
