### ISSUE TITLE
Cannot use takeSnapshotAsync: '(0, _expo.takeSnapshotAsync)' is undefined)

### ISSUE THREAD

**Issue by LarkStephens** [expo/expo#5324]
### Environment
Expo CLI 3.0.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
Making apps for iOS and android.

### Steps to Reproduce

Assign a view to be referenced in the snapshot and use takeSnapshotAsync as directed in the docs.

### Expected Behavior

The screenshot of the image would be taken.

### Actual Behavior

The attempt fails, expo gives an error that suggests that it cannot find takeSnapshotAsync or that it does not exist.

### Reproducible Demo

Running the pressable code at this snack reproduces my error:
https://snack.expo.io/@lark/nervous-pastry

**Comment by AdamJNavarro** [comment]
Hey @LarkStephens,

You need to use an `async` function and `await` the result. If you change your function to the following it will work:

takeScreenShot = async () => {
  console.log('Calling')
  const snap = await takeSnapshotAsync(this.view, {
            format: 'png',
            quality: 1,
            result: 'file',
        })
    };

Cheers,
Adam

**Comment by AppleCkp** [comment]
Hi @AdamJNavarro ,

I encounter same issue as above after i updated expo from sdk 32 to sdk 34.
Below is my error:
[TypeError: (0,p.takeSnapshotAsync) is not a function. (In '(0,p.takeSnapshotAsync)(u._container,{format:'png',quality:1,result:'file'})', '(0,p.takeSnapshotAsync)' is undefined)]

Here is my snack:
https://snack.expo.io/@appleckp/takesnapshotasync-undefined

Thanks,
Apple

**Comment by JulianKingman** [comment]
Ditto.

I suspect that Expo 34 cut out `takeSnapshotAsync`, and replaced it with `react-native-view-shot`, and didn't document the change. I can `expo install react-native-view-shot`, and it works.

**Comment by jeffreyflynt** [comment]
I am getting the same error as well on sdk 35.

```
[TypeError: (0,S.takeSnapshotAsync) is not a function. (In '(0,S.takeSnapshotAsync)(I,{result:"tmpfile",height:217,width:299,quality:1,format:"png"})', '(0,S.takeSnapshotAsync)' is undefined)]
```
