### ISSUE TITLE
expo build: android takes too long

### ISSUE THREAD

**Issue by MohamedAboushnief** [expo/expo#5329]
### Environment

Expo CLI 3.0.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

Android

### Steps to Reproduce

when i use expo build: android it takes tooooooo long  in build queued

### Expected Behavior

i expected that the build will work normally as before

### Actual Behavior

It takes too long in build queued without any change

**Comment by dereknelson** [comment]
hi, I recommend taking a look at the builder status at https://expo.io/turtle-status, sometimes there are just a lot of people trying to build at once :)

**Comment by MohamedAboushnief** [comment]
> hi, I recommend taking a look at the builder status at https://expo.io/turtle-status, sometimes there are just a lot of people trying to build at once :)

so when i take a look how to know it will take too long ,,I mean how much is too much builds in a queue?

**Comment by dereknelson** [comment]
@MohamedAboushnief you can always setup [turtle locally](https://docs.expo.io/versions/latest/distribution/turtle-cli/) to skip the line and build it on your own machine!

**Comment by cruzach** [comment]
I second @dereknelson's suggestion of turtle, or another option is to take a look at Expo's [Developer Services](https://blog.expo.io/taking-care-of-business-66a1624c6634), which includes
> priority access to our build infrastructure

**Comment by nicolasrouanne** [comment]
Not exactly the same, but close though: **Android builds now take 1 hour** when they use to take around 10 minutes top 😨 

I'm not talking about time in the _build queue_, but **the build itself**:
- [old build](https://expo.io/builds/d93c11ef-4e23-4f8d-9860-0466bf7334d9) - 7 min
<img width="425" alt="Screenshot 2019-11-28 at 15 21 08" src="https://user-images.githubusercontent.com/12157019/69813566-c7333080-11f2-11ea-896b-b3499db37582.png">


- [recent build](https://expo.io/builds/8680a8c8-537c-44ce-b836-b91af76aa645) - 1h
<img width="451" alt="Screenshot 2019-11-28 at 15 21 00" src="https://user-images.githubusercontent.com/12157019/69813545-baaed800-11f2-11ea-9924-9b3e85179e0d.png">

**Comment by cruzach** [comment]
Hm, not exactly sure why that would happen, but it looks specific to your build. You can see [here](https://expo.io/turtle-status) that the average build time is still around 7 minutes

**Comment by Jobians** [comment]
My own takes more than 1 hour, I immediately cancelled it
