### ISSUE TITLE
[web][webpack] Storybook cannot resolve modules with platform extensions

### ISSUE THREAD

**Issue by DaveClissold** [expo/expo#5334]
## 🐛 Bug Report
Firstly if this is not the appropriate place for this I do apologise, am really not sure where else to highlight this

When using Storybook with the expo-linear-gradient package, I get the following error
```
ERROR in ./node_modules/expo-linear-gradient/build/LinearGradient.js
Module not found: Error: Can't resolve './NativeLinearGradient' in '/Fleyver/front/node_modules/expo-linear-gradient/build'
```
It seems that Webpack and Storybook do not recognise the .platform extensions. When I duplicate the NativeLinearGradient.web.js and rename it NativeLinearGradient.js everything works

### Environment

   System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react: ^5.1.10 => 5.1.11 
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.25 => 16.9.1 
      @types/react-native: ^0.60.3 => 0.60.4 
      @types/react-navigation: ^3.0.8 => 3.0.8 
      expo: ^34.0.4 => 34.0.4 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.4

### Steps to Reproduce

- Clean install of expo with expo init 
- Add typescript, react-native-web and Storybook
- Create a React.FC with LinearGradient
- Add a story for the component
- yarn storybook

### Expected Behavior

Webpack should recognise the .platform specific files and should render the Storybook application

### Actual Behavior

Webpack doesn't recognise the .platform specific files, throws a 'Module not found' Error relating to NativeLinearGradient.

As mentioned above when I duplicate the NativeLinearGradient.web.js file and rename ite, everything works as expected

### Reproducible Demo

Here is a repo that recreates the issue
[https://github.com/DaveClissold/expo-strorybook-problem](https://github.com/DaveClissold/expo-strorybook-problem)

**Comment by EvanBacon** [comment]
This is due to the `.storybook/webpack.config` please refer to this example of how to use expo web with storybook https://github.com/expo/examples/blob/master/with-storybook/.storybook/webpack.config.js

**Comment by DaveClissold** [comment]
Fab thanks @EvanBacon and thanks to everyone involved for the time you guys put in to find the solution.
