### ISSUE TITLE
ExpoKit 34 - Errors when trying to build

### ISSUE THREAD

**Issue by nabeel-s** [expo/expo#5335]
I have updated to SDK 34 but getting the following errors when trying to build:

![](https://i.snag.gy/kiFjeB.jpg)

https://i.snag.gy/kiFjeB.jpg

The errors seem to be related to deprecated modules like universal modules. Please advise how to fix.

**Comment by cruzach** [comment]
Hi @nabeel-s, please follow the issue template we provide, we need all that information to help you as best we can

I suggest double checking the upgrade steps [here](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319) AND the specific Android Expokit upgrade steps/file changes listed [here](https://docs.expo.io/versions/latest/expokit/expokit/#android-1)

**Comment by nabeel-s** [comment]
@cruzach, we have followed all the upgrade steps carefully and have double-checked each step, still no luck. I am filling in the issue template below in the next message, please investigate it.

**Comment by nabeel-s** [comment]
## 🐛 Bug Report

### Environment



  **Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245**



**Android with Expokit, iOS standalone**

### Steps to Reproduce

**After updating to SDK 34, following the blog guide and the upgrade guide for Expokit, build fails in Android Studio with the following errors:**

![](https://i.snipboard.io/kiFjeB.jpg)

### Expected Behavior

Build should complete successfully without errors.

### Actual Behavior

**Build fails with following errors in Android Studio with the following error:**

![](https://i.snipboard.io/kiFjeB.jpg)

**Comment by cruzach** [comment]
Could you share your `build.gradle`?

**Comment by nabeel-s** [comment]
buildscript {
  repositories {
    google()
    maven { url 'https://maven.fabric.io/public' }
    mavenCentral()
  }

  dependencies {
    classpath 'io.fabric.tools:gradle:1.28.1'
  }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'devicefarm'

repositories {
  maven { url 'https://maven.fabric.io/public' }
}

android {
  compileSdkVersion 28
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }


  defaultConfig {
    applicationId 'com.cookaid.android'
    minSdkVersion 21
    targetSdkVersion 28
    versionCode 32
    versionName '1.1.4'
    ndk {
      abiFilters 'armeabi-v7a', 'x86'
    }
    multiDexEnabled true
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    // Deprecated. Used by net.openid:appauth
    manifestPlaceholders = [
        'appAuthRedirectScheme': 'host.exp.exponent'
    ]
  }
  dexOptions {
    javaMaxHeapSize System.getenv("DISABLE_DEX_MAX_HEAP") ? null : "8g"
  }

  signingConfigs {
    debug {
      storeFile file('../debug.keystore')
    }
    release {
      storeFile file(System.getenv("ANDROID_KEYSTORE_PATH") ?: "release-key.jks")
      storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
      keyAlias System.getenv("ANDROID_KEY_ALIAS")
      keyPassword System.getenv("ANDROID_KEY_PASSWORD")
    }
  }
  buildTypes {
    debug {
      debuggable true
      ext.enableCrashlytics = false
    }
    release {
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      signingConfig signingConfigs.release
    }
  }
  lintOptions {
    abortOnError false
  }
  packagingOptions {
    pickFirst "**"
  }
  configurations.all {
    resolutionStrategy.force 'com.android.support:design:27.1.0'
  }
}

devicefarm {
  projectName System.getenv("DEVICEFARM_PROJECT_NAME")
  devicePool System.getenv("DEVICEFARM_DEVICE_POOL")
  executionTimeoutMinutes 40
  authentication {
    accessKey System.getenv("AWS_ACCESS_KEY_ID")
    secretKey System.getenv("AWS_SECRET_ACCESS_KEY")
  }
}

configurations.all {
  resolutionStrategy {
    force 'org.webkit:android-jsc:r245459'
  }
}

// WHEN_PREPARING_SHELL_REMOVE_FROM_HERE

apply from: 'expo.gradle'

// WHEN_PREPARING_SHELL_REMOVE_TO_HERE

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])

  implementation 'com.android.support:multidex:1.0.3'

  // Our dependencies
//  implementation 'com.android.support:appcompat-v7:28.0.0'

  // Our dependencies from ExpoView
  // DON'T ADD ANYTHING HERE THAT ISN'T IN EXPOVIEW. ONLY COPY THINGS FROM EXPOVIEW TO HERE.
//  implementation 'com.android.support:appcompat-v7:28.0.0'
  implementation 'com.facebook.android:facebook-android-sdk:5.1.1'
  implementation('com.facebook.android:audience-network-sdk:4.99.0') {
    exclude module: 'play-services-ads'
  }
  compileOnly 'org.glassfish:javax.annotation:3.1.1'
  implementation 'com.jakewharton:butterknife:9.0.0'
  implementation 'de.greenrobot:eventbus:2.4.0'

  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
  implementation 'com.amplitude:android-sdk:2.9.2'

  implementation 'com.squareup.picasso:picasso:2.5.2'
  implementation 'com.google.android.gms:play-services-gcm:17.0.0'
  implementation 'com.google.android.gms:play-services-analytics:17.0.0'
  implementation 'com.google.android.gms:play-services-maps:17.0.0'
  implementation 'com.google.android.gms:play-services-auth:17.0.0'
  implementation 'com.google.android.gms:play-services-location:17.0.0'
  implementation 'com.google.android.gms:play-services-ads:18.1.1'
  annotationProcessor 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
  implementation "com.raizlabs.android:DBFlow-Core:2.2.1"
  implementation "com.raizlabs.android:DBFlow:2.2.1"
  implementation "com.madgag.spongycastle:core:1.58.0.0"
  implementation "com.madgag.spongycastle:prov:1.58.0.0"
  debugImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  // debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.4-beta1'
  releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta1'
  implementation 'com.facebook.device.yearclass:yearclass:2.1.0'
  implementation 'commons-io:commons-io:2.6'
  implementation 'me.leolin:ShortcutBadger:1.1.22@aar'
  implementation 'com.theartofdev.edmodo:android-image-cropper:2.7.0'
  implementation 'com.yqritc:android-scalablevideoview:1.0.1'
  implementation 'commons-codec:commons-codec:1.10'
  implementation 'com.segment.analytics.android:analytics:4.3.0'
  implementation 'com.google.zxing:core:3.3.3'
  implementation 'net.openid:appauth:0.7.1'
  implementation('com.airbnb.android:lottie:2.5.5') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
  }
  implementation('io.nlopez.smartlocation:library:3.2.11') {
    transitive = false
  }
  implementation 'com.android.support:exifinterface:28.0.0'
  implementation 'com.squareup.okio:okio:1.15.0'
  implementation 'com.facebook.soloader:soloader:0.6.0'

  implementation 'com.google.android.exoplayer:exoplayer:2.9.3'

  // expo-file-system
  implementation 'com.squareup.okhttp3:okhttp:3.12.1'
  implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.12.1'

  // Testing
  // androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
  // // We use a modified build of com.android.support.test:runner:1.0.1. Explanation in maven-test/README
  // androidTestImplementation 'com.android.support.test:runner:1.0.1'
  // androidTestImplementation 'com.android.support:support-annotations:28.0.0'
  // androidTestImplementation 'com.google.code.findbugs:jsr305:3.0.0'
  // androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.1'
  // androidTestImplementation 'com.azimolabs.conditionwatcher:conditionwatcher:0.2'

  // testImplementation 'junit:junit:4.12'
  // testImplementation 'org.mockito:mockito-core:1.10.19'
  // testImplementation 'org.robolectric:robolectric:3.8'
  // testImplementation 'com.android.support.test:runner:1.0.2-alpha1'
  // testImplementation 'com.android.support.test:rules:1.0.2-alpha1'

  
  implementation('host.exp.exponent:expoview:34.0.0@aar') {
    transitive = true
    exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    exclude group: 'com.squareup.okhttp3', module: 'okhttp-urlconnection'
  }
  
  
  api 'org.webkit:android-jsc:r245459' // needs to be before react-native
  api 'com.facebook.react:react-native:34.0.0'
  
/*  addUnimodulesDependencies([
      modulesPaths : [
        '../../node_modules'
      ],
      configuration: 'api',
      target       : 'react-native',
      exclude      : [
        // You can exclude unneeded modules here, eg.
        // 'unimodules-face-detector-interface',
        // 'expo-face-detector'
                    'expo-av',
                    'expo-sqlite',
                    'expo-facebook',
                    'expo-app-loader-provider',
                    'expo-barcode-scanner',
                    'expo-local-authentication',
                    'expo-gl',
                    'expo-print'
        // Adding a name here will also remove the package
        // from auto-generated BasePackageList.java
      ]
  ])
  */
}

// This has to be down here for some reason
apply plugin: 'com.google.gms.google-services'
apply from: "../../node_modules/react-native-unimodules/gradle.groovy"

**Comment by nabeel-s** [comment]
Updating the import statements using expo-codemod didn't solve the above build errors.

**Comment by cruzach** [comment]
Sorry, this should’ve been an earlier question- what SDK are you upgrading from? You’ll need to run “expo install <package-name>” along with updating the import statements. That will install the best version of that particular package with whatever SDK version you’re on (in your case, 34)

**Comment by nabeel-s** [comment]
@cruzach, I'm upgrading from SDK 32. I deleted the whole node_modules folder and reinstalled using npm install. That would install the required modules, right?

**Comment by expjess** [comment]
Hey @nabeel-s - just wanted to pop in and say hi! (@rbrowngt is a good friend of mine so I recognized your name!) Would love to hear what you're working on if it's shareable! 

Oh, and of course, let us know if using `expo install` as @cruzach mentioned above still doesn't resolve things for you.

**Comment by nabeel-s** [comment]
@expjess, it's a food-related app but not shareable.

@cruzach, unfortunately using 'expo install' did not fix the build errors.

**Comment by nabeel-s** [comment]
I saw the following log in Android Studio:

`Compilation is not supported for following modules: expo-ads-admob, expo-app-loader-provider, expo-constants, expo-av, expo-font, expo-file-system, expo-keep-awake, expo-linear-gradient, expo-location, expo-permissions, expo-sqlite, expo-web-browser, unimodules-core, unimodules-constants-interface, unimodules-camera-interface, unimodules-barcode-scanner-interface, unimodules-file-system-interface, unimodules-task-manager-interface, unimodules-font-interface, unimodules-face-detector-interface, unimodules-image-loader-interface, unimodules-react-native-adapter, unimodules-permissions-interface, unimodules-sensors-interface. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.`

Is this related to the errors?

**Comment by nabeel-s** [comment]
Unfortunately that didn't solve the original errors, although the above log is gone.

**Comment by nabeel-s** [comment]
Given up on fixing the errors and will try to switch to bare workflow now.

**Comment by nabeel-s** [comment]
@cruzach, I have finally solved this issue by un-ejecting the project, deleting the android folder and re-ejecting again. It was also important **not** to update the Gradle version like the pop-up suggested in Android Studio.

This has been quite a nightmare to solve in the last couple of weeks so please try to update the Expo documentation to include this. For projects like mine, where minimal changes are required on the native side, it is far more straightforward to simply un-eject the project and re-eject instead of going through all the upgrade steps (and running into errors).

**Comment by cruzach** [comment]
Thanks for sharing how you fixed the issue, and also thanks for the feedback! We're working hard to improve the feature set of the bare workflow so that devs can opt for that instead of Expokit in the future, and have a much smoother experience

I should note that [in the Expokit docs](https://docs.expo.io/versions/latest/expokit/expokit/#4-android-build-and-run) we say:
> When opening the project, Android Studio may prompt you to upgrade the version of Gradle or other build tools, but don't do this as you may get unexpected results. ExpoKit always ships with the latest supported versions of all build tools.

**Comment by shamilovtim** [comment]
Hit the same exact issue. Stupidly upgraded Gradle with no way back it seems. Looks like my only option is to uneject and reeject
