### ISSUE TITLE
react-native-share-extension support please

### ISSUE THREAD

**Issue by ursNj** [expo/expo#5340]
From a long time im waiting for this feature please make it support at the priority. i can see many requests for the same in the community. 

I want to use app extensions.

So please support https://github.com/alinz/react-native-share-extension

**Comment by cruzach** [comment]
Hey! This is actually an [open feature request](https://expo.canny.io/feature-requests/p/ios-app-extension), I suggest voting for it over there! 

We keep github for bug reports, however, so I'm going to close this. Any further conversation should take place in that canny thread 👍
