### ISSUE TITLE
Expo.Updates.reloadFromCache seems not working on ios

### ISSUE THREAD

**Issue by ModyQyW** [expo/expo#5341]
### Environment

```json
Expo CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/opt/nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.17.3 - /usr/local/opt/nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.10.2 - /usr/local/opt/nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.0.8
```

Target: iOS, Standalone

### Steps to Reproduce

This is an app hosted on my own server and distributed in the iTunes Store. So it is hard to reproduce and hard to give a demo. But I will give related infos as I can.

1. run `expo export --public-url https://fakeweb.net/fakeapp`
2. upload files to https://fakeweb.net/fakeapp
3. run `expo build:ios --public-url https://fakeweb.net/fakeapp/ios-index.json` and get the ipa
4. upload the ipa to the iTunes Store
5. install the app on iphone
5. update codes and redo step 1, 2
6. open the app on iphone, alert updates is isAvailable and begin fetching
7. after fetching, didn't reload from cache as I do call `Updates.reloadFromCache()`

Using Charles, I find that the app did download ios-index.json and bundles/ios-xxxx.js but didn't reload...

### Expected Behavior

can reload from cache

### Actual Behavior

can't reload from cache

### Related Codes And Configuration

package.json

```json
{
  ...,
  "dependencies": {
    "axios": "^0.19.0",
    "color": "^3.1.2",
    "expo": "^34.0.3",
    "expo-barcode-scanner": "~6.0.0",
    "expo-camera": "~6.0.0",
    "expo-constants": "~6.0.0",
    "expo-font": "~6.0.1",
    "expo-location": "~6.0.0",
    "expo-permissions": "~6.0.0",
    "expo-web-browser": "~6.0.0",
    "lodash": "^4.17.15",
    "mobx": "^5.13.0",
    "mobx-react": "^5.4.4",
    "moment": "^2.24.0",
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-datepicker": "1.7.2",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.1.0",
    "react-navigation": "2.18.3"
  }
}
```

app.json

```json
{
  "expo": {
    "name": "...",
    "description": "...",
    "slug": "...",
    "sdkVersion": "34.0.0",
    "version": "1.0.5",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "...",
    "assetBundlePatterns": [
      "assets/fonts/*",
      "assets/img/*"
    ],
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#334393"
    },
    "splash": {
      "backgroundColor": "#FFEF02",
      "resizeMode": "contain",
      "image": "..."
    },
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "fallbackToCacheTimeout": 0
    },
    "ios": {
      "bundleIdentifier": "...",
      "buildNumber": "1.0.5",
      "infoPlist": {
        "NSCameraUsageDescription": "...",
        "NSLocationWhenInUseUsageDescription": "..."
      }
    },
    "android": {
      "package": "...",
      "versionCode": 10005
    }
  }
}
```

related codes

```js
import { Updates } from 'expo';
...
try {
  const res = await Promise.race([
    Updates.checkForUpdateAsync(),
    new Promise((resolve, reject) => {
      setTimeout(() => {
        reject(new Error('Timeout!'));
      }, 10000);
    }),
  ]);
  // check update successfully in 10s
  if (res.isAvailable) {
    // get version and updtInfo
    const { version: newVersion, updtInfo = 'No update Info' } = res.manifest;
    // get update time
    let date = res.manifest.publishedTime;
    date = date.substring(0, date.indexOf('T'));
    // compare versions, check if breaking update
    const newVersionArr = newVersion.split('.').map(ele => parseInt(ele, 10));
    if (newVersionArr[0] !== [1, 0, 5][0]) {
      // breaking update
      if (Platform.OS === 'ios') {
        // alert hint
        Alert.alert(...);
      } else {
        // alert hint
        Alert.alert(...);
      }
    } else {
      // alert hint
      Alert.alert(
        'Hint', `Please wait for update and reload automatically.\r\nPublishedTime：${date}\r\nVersion：${newVersion}\r\nVersionInfo${updtInfo}`,
        [{ text: 'OK', onPress: () => {} }],
        { cancelable: false, onDismiss: () => {} },
      );
      // stuck below and never reload
      Updates.fetchUpdateAsync()
        .then(() => { Updates.reloadFromCache(); });
    }
  }
} catch (err) {
  Alert.alert(...);
}
```

I also add a new topic in the forum [here](https://forums.expo.io/t/updates-seems-having-problems-on-ios/26512).

Actually you can search `都城Epay` in the iTunes Store and try. The auto update is 
accessible during 00:00:00 - 10:59:59, 13:00:00 - 16:59:59, 19:00:00 - 23:59:59. But the app is all Chinese.

Reproducible Demo
N/A

**Comment by cruzach** [comment]
Hi, sorry you're running into this. Couple things I should mention:
- to make your workflow a little easier, you can push a new update by simply running `expo publish` rather than having to do a whole new build with `expo build:ios`
- your logic can be a little simpler, since the `fetchUpdateAsync()` method returns an object with an `isNew` key, which is `true` if the fetched bundle is new (i.e. a different version that the what's currently running). (might be worth a shot to check what is getting returned here)

So nothing happens after calling `reloadFromCache`?

**Comment by ModyQyW** [comment]
Thanks for your advice.
I think that `expo publish` isn't work for the app hosted on my own server. Maybe I have a wrong understanding?
Nothing happens. And I am sure that the fetched bundle is a different version.

**Comment by cruzach** [comment]
Hey @ModyQyW, sorry I missed your response! Are you still not able to reload from cache?

**Comment by ModyQyW** [comment]
Hey @cruzach .
I've been busy with other work recently, so there's no way to deal with this problem. But I plan to release a new version recently in order to fix this. If the new version has the same problem, I'll contact you as soon as possible.

**Comment by ModyQyW** [comment]
Hey @cruzach . New progress here! I build a new package and do testflight test today.

First, I rewrite some code.

`dependencies` in package.json is just the same.

app.json:

```json
{
  "expo": {
    "name": "...",
    "description": "...",
    "slug": "...",
    "sdkVersion": "34.0.0",
    "version": "1.0.7",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "...",
    "assetBundlePatterns": [
      "assets/fonts/*",
      "assets/img/*"
    ],
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#334393"
    },
    "splash": {
      "backgroundColor": "#FFEF02",
      "resizeMode": "contain",
      "image": "..."
    },
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "fallbackToCacheTimeout": 0
    },
    "ios": {
      "bundleIdentifier": "...",
      "buildNumber": "1.0.7",
      "infoPlist": {
        "NSCameraUsageDescription": "...",
        "NSLocationWhenInUseUsageDescription": "..."
      }
    },
    "android": {
      "package": "...",
      "versionCode": 10007
    }
  }
}
```

related codes:

```js
import { Updates } from 'expo';
...
try {
  const res = await Promise.race([
    Updates.fetchUpdateAsync(),
    new Promise((resolve, reject) => {
      setTimeout(() => {
        reject(new Error('Timeout!'));
      }, 30000);
    }),
  ]);
  // alert hint
  Alert.alert(
    'Hint', `isNew：${res.isNew}`,
    [{ text: 'OK', onPress: () => {} }],
    { cancelable: false, onDismiss: () => {} }
  );
  // check update successfully in 30s
  if (res.isNew) {
    // get version and updtInfo
    const { version: newVersion, updtInfo = 'No update Info' } = res.manifest;
    // get update time
    let date = res.manifest.publishedTime;
    date = date.substring(0, date.indexOf('T'));
    // compare versions, check if breaking update
    const newVersionArr = newVersion.split('.').map(ele => parseInt(ele, 10));
    if (newVersionArr[0] !== [1, 0, 7][0]) {
      // breaking update
      if (Platform.OS === 'ios') {
        // alert hint
        Alert.alert(...);
      } else {
        // alert hint
        Alert.alert(...);
      }
    } else {
      // alert hint
      Alert.alert(
        'Hint', `Please wait for update and reload automatically.\r\nPublishedTime：${date}\r\nVersion：${newVersion}\r\nVersionInfo${updtInfo}`,
        [{ text: 'OK', onPress: () => {} }],
        { cancelable: false, onDismiss: () => {} },
      );
      // stuck below and never reload
      Updates.fetchUpdateAsync()
        .then(() => { Updates.reloadFromCache(); });
    }
  } else {
    // alert hint
    Alert.alert(
      'Hint', `Lastest version!`,
      [{ text: 'OK', onPress: () => {} }],
      { cancelable: false, onDismiss: () => {} }
    )
  }
} catch (err) {
  Alert.alert(...);
}
```

I export assets using `expo export --public-url https://fakeweb.net/fakeapp`, rename `ios-index.json` to `ios-index-test.json` and upload related files to  https://fakeweb.net/fakeapp. After that, I build the ios app using `expo build:ios --public-url https://fakeweb.net/fakeapp/ios-index-test.json`.

I use testflight and get the app v1.0.7. Open it and I get two hints: `isNew: false` and `Lastest version!`. That's fine.

I modify `ios-index-test.json`, replacing `1.0.7` with `1.0.8`. And I open the app again, and I get the same hint! Which means, I think, the `Updates` apis have some problems judging the version.

PS: I use Charles to check the fetched json and I save the session. If you need it, please leave an email.

Could you please check `Expo.Updates`? Or maybe what I think is wrong and give me some advice please. :)

**Comment by ModyQyW** [comment]
Environment now.

```sh
Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: 2.18.3 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.4.1
```

**Comment by cruzach** [comment]
Did you re-`export` after making changes to `ios-index-test.json`?

**Comment by ModyQyW** [comment]
No. As I only change the version, I think there is no need to export again and get new assets and the new ios bundle. I just need to modify the ios json file in `dist`, upload it and `Updates` module will find out this is a new version.

But I try these just now:

1) modify app.json: `1.0.7 => 1.0.8`, `10007` => `10008`.
2) export, rename `ios-index.json` to `ios-index-test.json` and upload related files.
3) open the app and find that code run into `catch`. I only get the hint from `catch`.

I don't get it. I am sure my network is fine and I find this time, `ios-index-test.json` and `bundles/ios-xxxx.js` are fetched.

**Comment by cruzach** [comment]
Hey @ModyQyW , sorry for the late follow up here! Have you upgraded to the new `expo-updates` module, and if you have, are you still having issues?

**Comment by nitishdhar** [comment]
Can confirm, I am still getting this on iOS. 

>TypeError: S.reloadFromCache is not a function. (In 'S.reloadFromCache()', 'S.reloadFromCache' is undefined)

Using 

> expo-updates 0.5.4
