### ISSUE TITLE
Is expo-analytics-amplitude supporting web

### ISSUE THREAD

**Issue by TingC** [expo/expo#5347]
### Please note that discussions opened as issues in the core Expo repository will be closed.

Is `expo-analytics-amplitude` supporting web? Because https://www.native.directory/ said `expo-analytics-amplitude` supports web while npm page [expo-analytics-amplitude](https://www.npmjs.com/package/expo-analytics-amplitude) said it's a module wraps [Amplitude-iOS](https://github.com/amplitude/Amplitude-iO) and [Android SDKs](https://github.com/amplitude/Amplitude-Android). Or is there any configuration I missed? Below is the error I got when trying it out.

> Unhandled Rejection (Error): The method or property Amplitude.initialize is not available on web, are you sure you've linked all the native dependencies properly?

**Comment by cruzach** [comment]
Looks like native.directory could use a PR, from [the expo-analytic-amplitude package's `.web.ts` file](https://github.com/expo/expo/blob/master/packages/expo-analytics-amplitude/src/ExpoAmplitude.web.ts), it doesn't seem to support web
