### ISSUE TITLE
[expo-branch] Default export missing from expo-branch

### ISSUE THREAD

**Issue by AryanJ-NYC** [expo/expo#5348]
### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.1.11 
      expo: ^34.0.3 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9

iOS + Android
### Steps to Reproduce

```js
import branch from expo-branch
// use the branch API as per https://www.npmjs.com/package/react-native-branch docs
// realize `branch` is undefined
``` 

### Expected Behavior
```js
import branch from 'expo-branch'
console.log(branch) // should be an instance of Branch()
```

### Actual Behavior

```js
import branch from 'expo-branch'
console.log(branch) // is undefined
```

### Reproducible Demo

https://github.com/AryanJ-NYC/expo-sandbox

**Comment by cruzach** [comment]
You'll want to run `expo install react-native-branch` and to import like this:
```
import Branch, { BranchEvent } from 'react-native-branch'
```
But thanks for revealing that the docs need an update 👍
