### ISSUE TITLE
[expo-branch] null is not an object (evaluating RNBranch.STANDARD_EVENT_ADD_TO_CART

### ISSUE THREAD

**Issue by AryanJ-NYC** [expo/expo#5349]
### Environment
This bug happens in Android

```

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.9
```

### Steps to Reproduce
1.
`import * as whatever from 'expo-branch'`
OR
`import whatever from 'expo-branch'`
OR
`import { Branch } from 'expo-branch'`

2. `npm start`
3. Scan QR code on Expo on Android app
4. See red screen of death:
![WhatsApp Image 2019-08-15 at 4 14 01 PM](https://user-images.githubusercontent.com/8263430/63124058-6865e600-bf78-11e9-8321-9045fbffc625.jpeg)

### Expected Behavior
It does not break.

### Actual Behavior
It breaks.

### Reproducible Demo
https://github.com/AryanJ-NYC/expo-sandbox

**Comment by cruzach** [comment]
You'll want to run `expo install react-native-branch` and to import like this:
```
import Branch, { BranchEvent } from 'react-native-branch'
```

**Comment by AryanJ-NYC** [comment]
This works on iOS but still results in the same screen (shown in OP) on Android.

**Comment by cruzach** [comment]
We state in Expo's [Branch docs](https://docs.expo.io/versions/latest/sdk/branch/):
 > This module is currently not supported on standalone or ExpoKit Android builds. If you'd like to use Branch in your Android app, we recommend that you use the bare workflow and install the react-native-branch module separately.

**Comment by AryanJ-NYC** [comment]
I see. I was under the impression that [Branch was re-added as an optional module for Android](https://github.com/expo/expo/issues/5132).

**Comment by cruzach** [comment]
That will probably go out with SDK 35 (released around September)

**Comment by AryanJ-NYC** [comment]
I don't this is an issue that will be fixed with Expo SDK 35. Instead, it's a bug in the `expo-branch` unimodule.

I think this issue should be re-opened. @sjchmiela, thoughts?

**Comment by sjchmiela** [comment]
This hasn't been communicated clearly anywhere, since we haven't announced this feature publicly yet, but when trying to use Branch you will need to remember that:

- nothing has changed when it comes to Expo client — it didn't have Branch and it won't. So, trying to import and/or call any Branch methods in Expo client will raise an error, since `RNBranch`, i. e. native module, is `null` in Expo client.
- Branch module is only added to Android standalone apps. `expo-branch` is a wrapper around `react-native-branch` which allows us to optionally include it in standalone applications depending on `dependencies` field in `package.json`. Branch will be available in your application only in Expo-built apps (`expo build:android`) and only if you add `expo-branch` to your NPM dependencies.
- If you build your app with `expo-branch` included and importing from `expo-branch` doesn't work due to some problem with exports, try importing from `react-native-branch`, as @cruzach proposed [here](https://github.com/expo/expo/issues/5348#issuecomment-522125159).
- As always you can eject to either bare workflow or ExpoKit and add `expo-branch`/`react-native-branch` there. 🙂 

Has this description helped understand current situation? 😅

**Comment by AryanJ-NYC** [comment]
Yes, it has, @sjchmiela.

This would mean that, while `import { DangerZone } from 'expo'` was a safe import, `import ... from 'expo-branch' // or react-native-branch` is unsafe since `RNBranch` is `null` in Expo client.  This lead me to uaw the following pattern:

```js
  if (Constants.appOwnership === 'standalone') {
    const { BranchEvent } = await import('expo-branch')
    const branchEvent = new BranchEvent(eventType, null, properties)
    branchEvent.logEvent()
  }
```

which now does _not_ return the same error as above. Unfortunately, I'm still trying to successfully build the app. Will keep updated.

**Comment by sjchmiela** [comment]
That's right, that should do the work! To inspect whether `expo-branch` has been added to the build, expand the `resolve native modules` step in `expo.io/builds` and verify whether `Adding expo-branch:1.0.0` is present there. If it is, most probably all the required native modules have been added to the application.

<img width="433" alt="Zrzut ekranu 2019-08-19 o 20 55 09" src="https://user-images.githubusercontent.com/1151041/63291350-a427e500-c2c3-11e9-9a76-21bf2c81498a.png">

**Comment by AryanJ-NYC** [comment]
I can confirm that `expo-branch` is added to the build.

Additionally, trying to `import react-native-branch` breaks the app (as it is _not_ added to the build).

Lastly, I can also confirm that `expo-branch` is _not_ default exporting a `Branch()` singleton (which makes it difficult to use as most of the functionality is tied to that singleton). I was able to get some functions to work (such as `logout()` and `setIdentity()`) but calling `createBranchUniversalObject` brings the app to its knees without the necessary singleton.

**Comment by nmakiya** [comment]
I've found `import Branch, { BranchEvent } from 'react-native-branch'` works on iOS but still not on Android with SDK 34. I have confirmed looking at the build that both `expo-branch` and `react-native-branch` are included in the build:android output.

**Comment by matias91** [comment]
I'm stuck with the same problem.

I'm trying with SDK 35 and still getting that error on IOS and Android.
The error happens importing as
```
import Branch from 'expo-branch'
```
and 
```
import Branch from 'react-native-branch'
```

I read about the Android support [here](https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4), and followed [this instructions](https://docs.expo.io/versions/latest/sdk/branch/#importing-branch).

error: `null is not an object (evaluating 'RNBranch.STANDARD_EVENT_ADD_TO_CART')`

i'm missing something?

**Comment by sjchmiela** [comment]
Branch is only included in standalone apps (`expo build:android`) and only if at the moment of executing that command you have `expo-branch` listed among dependencies in `package.json`. So no support in Expo client. 🙂

**Comment by matias91** [comment]
> Branch is only included in standalone apps (`expo build:android`) and only if at the moment of executing that command you have `expo-branch` listed among dependencies in `package.json`. So no support in Expo client. 🙂

Thanks for the reply, @sjchmiela!
So is included in the build but can't be tested first because the app crashes. What about IOS? Is also crashing in Expo client in SDK 35, but works on SDK 34.
Seems to me that is the same as before and devs need to eject from expo to use it properly.
Or there is a way to integrate it without breaking the app?

Please, correct me if I'm wrong. Thanks

**Comment by davidbiller** [comment]
Same here. We can´t test in in the iOS Simulator?

**Comment by cruzach** [comment]
Correct, you can't test in the Expo Client, **but** you can [install your binary onto a simulator](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#5-test-it-on-your-device-or) before moving on to TestFlight, if you wish

**Comment by binchik** [comment]
Branch doesn't work for me even in standalone builds. I tried iOS only.

```
if (Constants.appOwnership === 'standalone') {
      const branch = await import('expo-branch')

      branch.subscribe(({error, params}) => {
     }
}
```

**Comment by davidbiller** [comment]
> Branch doesn't work for me even in standalone builds. I tried iOS only.
> 
> ```
> if (Constants.appOwnership === 'standalone') {
>       const branch = await import('expo-branch') // tried react-native-branch here too
> 
>       branch.subscribe(({error, params}) => {
>      }
> }
> ```

Did you tried to import it direct for testing? without condition. 
I have the same issue, but it works if i import it from start.

**Comment by binchik** [comment]
@davidbiller do you mean the regular import without `await`? And how do you import it? `expo-branch` or `react-native-branch`?

**Comment by davidbiller** [comment]
//import Branch from "expo-branch";

this works for me.

**Comment by binchik** [comment]
@davidbiller are you using expo v35?

**Comment by davidbiller** [comment]
> @davidbiller are you using expo v35?

Yes. 
import is in app.js 

So what error do you get?

**Comment by binchik** [comment]
@davidbiller

I get the following error:

```
Can't find variable: Branch
```

**Comment by davidbiller** [comment]
so you do the import with branch and not **B**ranch

**Comment by binchik** [comment]
@davidbiller it used to be `Branch`. Forget about `Can't find variable: Branch`.

Here is the error I get from sentry:

```
TypeError
undefined is not a function (near '...o.sent.subscribe...')
```

with the following code:

```
if (Constants.appOwnership === 'standalone') {
      const Branch = await import('expo-branch')
      Branch.subscribe(({error, params}) => {
        console.log('Branch.io deeplink handler', JSON.stringify(params))
        ...
```

**Comment by davidbiller** [comment]
> @davidbiller it used to be `Branch`. Forget about `Can't find variable: Branch`.
> 
> Here is the error I get from sentry:
> 
> ```
> TypeError
> undefined is not a function (near '...o.sent.subscribe...')
> ```
> 
> with the following code:
> 
> ```
> if (Constants.appOwnership === 'standalone') {
>       const Branch = await import('expo-branch')
>       Branch.subscribe(({error, params}) => {
>         console.log('Branch.io deeplink handler', JSON.stringify(params))
>         ...
> ```
> 
> I don't know what error I get when importing branch the regular way because it doesn't get reported to sentry. App just crashes on launch.

Looks like you dont use it in a standalone app, without expo.

**Comment by binchik** [comment]
@davidbiller I'm doing a build with `expo build:ios -t simulator` and run it on simulator. It's standalone. https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#5-test-it-on-your-device-or

**Comment by davidbiller** [comment]
> @davidbiller I'm doing a build with `expo build:ios -t simulator` and run it on simulator. It's standalone. https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#5-test-it-on-your-device-or

mhhh okay. 
so try:
import Branch from "expo-branch";
and than you can do expo publish for testing.
Run again in Simulator

**Comment by binchik** [comment]
@davidbiller I don't know why, but it works now. I import it with regular top import and I left the `if (Constants.appOwnership === 'standalone') {`.

Thank you! I spent about 5 hours on this.

**Comment by yodaheis** [comment]
So I have struggled a lot with this issue and tried both sdk 34 as well as 35. Now I've got it up and running (functional in standalone app and error-less build in expo-cli for development purpose)

This error will appear only if actively importing Branch from 'expo-branch' in any module at the time of building the app.

So a simple conditional if(Constants.appOwnership === 'standalone') {
    const Branch = import('expo-branch)
    // Your code here ...
}
works perfectly fine

**Comment by AryanJ-NYC** [comment]
@yodaheis Just be aware that [`import()` returns a `Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). You should probably make it something like...

```js
const someAsyncFunction = async () => {
  if(Constants.appOwnership === 'standalone') {
    const Branch = await import('expo-branch)
    // Your code here ...
  }
}
```

**Comment by walidvb** [comment]
I'm running this on a standalone app on my device, expo 35, and getting a `undefined is not a function` on `Branch.subscribe` with that approach (i do use `await`).

Also, when importing normally(without the standalone condition), and running as standalone on a device, the code within subscribe doesn't run, even when opening from a branch url.

Any pointers?

**Comment by 0duaht** [comment]
To import dynamically using await, what worked for us was:

```js
const ExpoBranch = await import('expo-branch')
const Branch = ExpoBranch.default;
Branch.setIdentity('user_id')
```

**Comment by walidvb** [comment]
I tried importing as @0duaht suggested, but am still getting an error on importing the library: 
`null is not an object (evaluating 'c.STANDARD_EVENT_ADD_TO_CART')`.
I've 
I'm running a standalone build on Android. 

Not sure what i'm doing wrong?
Here is my full source:

```
// ./Branch.js
import { Alert } from 'react-native';
import Constants from 'expo-constants';

(async function(){
  if (Constants.appOwnership === 'standalone') {
    const ExpoBranch = await import('expo-branch')
    const Branch = ExpoBranch.default;
    Alert.alert(`branch ${typeof ExpoBranch} | ${typeof Branch}`)

    // Branch.subscribe((bundle) => {
    //   Alert.alert(`bundle ${typeof bundle}`, JSON.stringify(bundle))
    //   if (bundle && bundle.params && !bundle.error) {
    //     Alert.alert(`bundle exists ${typeof bundle}`, JSON.stringify(bundle))
    //     console.log(bundle.params)
    //   }
    // });
  }
})()
```

**Comment by walidvb** [comment]
Also, for those interested, I've ended up handling it this way:

```js
// /my-branch.js
import Constants from 'expo-constants';

if (Constants.appOwnership !== 'standalone') {
  module.exports = {
    subscribe: console.log,
    createBranchUniversalObject: async () => ({
      showShareSheet: console.log,
    })
  }
}
else{
  module.exports = require('expo-branch')
}
```

and then `import Branch from 'my-branch'`. The above code would obviously need to mock all functions called by your code.

**Comment by nsdub** [comment]
I struggled getting the syntax correct to export the nested `logEvent` function inside `BranchEvent`.  Riffing off of @walidvb 's comment...

```
import Constants from 'expo-constants'

if (Constants.appOwnership !== 'standalone') {
  module.exports = {
    BranchEvent: function(eventName, buo) {
      this.logEvent = function() {
        console.log(eventName) // or whatever...
      }
    }
  }
}
else {
  module.exports = require('expo-branch')
}

**Comment by augustolp** [comment]
Hello! is there any experienced dev here that can help me with expo & branch implementation? Please contact me at augusto@lemmonet.com to discuss collaboration fees ... thanks!

**Comment by Winnie16** [comment]
> Also, for those interested, I've ended up handling it this way:
> 
> ```js
> // /my-branch.js
> import Constants from 'expo-constants';
> 
> if (Constants.appOwnership !== 'standalone') {
>   module.exports = {
>     subscribe: console.log,
>     createBranchUniversalObject: async () => ({
>       showShareSheet: console.log,
>     })
>   }
> }
> else{
>   module.exports = require('expo-branch')
> }
> ```
> 
> and then `import Branch from 'my-branch'`. The above code would obviously need to mock all functions called by your code.

Hey @walidvb , I am new to branch and expo.I am trying to integrate branch on expo v36 for android.  I am not quite clear on those function implementations. Can you please elaborate on it?

**Comment by walidvb** [comment]
@Winnie16 the idea is to conditionally load branch, depending on your environment.

Across your codebase, instead of doing `import Branch from 'expo-branch'`, you would `import Branch from 'my-branch'`, which would give you a real branch instance in standalone(production), and a mock in the expo client(development).

I'm now adding branch  for web, and seeing that this will be needed either way, as they have quite different implementations. In this case, I will have a `MyBranch` which would interface with either the WebSDK(web prod/dev), the ReactNativeSDK(prod) or the mock(dev).

Makes sense?

**Comment by Winnie16** [comment]
> @Winnie16 the idea is to conditionally load branch, depending on your environment.
> 
> Across your codebase, instead of doing `import Branch from 'expo-branch'`, you would `import Branch from 'my-branch'`, which would give you a real branch instance in standalone(production), and a mock in the expo client(development).
> 
> I'm now adding branch for web, and seeing that this will be needed either way, as they have quite different implementations. In this case, I will have a `MyBranch` which would interface with either the WebSDK(web prod/dev), the ReactNativeSDK(prod) or the mock(dev).
> 
> Makes sense?

Yes this does make things clear.  Can you give me an idea about mocking the functions?

**Comment by walidvb** [comment]
As per my previous post, which only mocks `subscribe` and `createBranchUniversalObject`, although Branch has more methods than that. I've been adding them as they are called in my codebase.
The mocked functions do nothing more than logging(so that I can see the calls being made)

**Comment by augustolp** [comment]
Hello @walidvb / @Winnie16 
Have you tried Branch links? I'm struggling to make it work ... when doing an install test using a branch link, it doesn't attribute the install in Branch dashboard, and I'm not able to read link data within subscribe method in standalone.

Here is my app.js code, as you can see I'm logging with Sentry:

import React from 'react';
import { Provider } from 'react-redux';
import Main from './src/index.js';
import store from './src/store';
import Constants from 'expo-constants';
import * as Sentry from 'sentry-expo';
import * as Facebook from 'expo-facebook';

Sentry.init({
  dsn:
    '-----------------------------------------',
  enableInExpoDevelopment: true,
  debug: true,
});

class App extends React.Component {
  constructor(props) {
    super(props);
  }

  async componentDidMount() {
    //Sentry.captureMessage(`appOwnership: ${Constants.appOwnership}`, `debug`);
    try {
      //await Facebook.initializeAsync('----------------');

      if (Constants.appOwnership === 'standalone') {
        const Branch = await import('expo-branch');

        Branch.default.subscribe((bundle) => {
          Sentry.captureMessage(
            `Branch Subscribed: ${JSON.stringify(bundle)}`,
            `debug`
          );
          if (bundle && bundle.params && !bundle.error) {
            // `bundle.params` contains all the info about the link.
            Sentry.captureMessage(`Params: ${bundle.params}`, `debug`);
            Sentry.captureMessage(
              `Params length: ${bundle.params.length}`,
              `debug`
            );

            for (const i = 0; i < bundle.params.length; i++) {
              Sentry.captureMessage(
                `Params(${i}): ${bundle.params[i]}`,
                `debug`
              );
            }
          } else {
            Sentry.captureMessage(
              `Branch Subscription Error: ${bundle.error}`,
              `debug`
            );
          }
        });
        Sentry.captureMessage(`Branch Ok`, `debug`);
      }
    } catch (error) {
      Sentry.captureMessage(`Branch Error: ${error}`, `debug`);
    }
  }

  render() {
    return (
      <Provider store={store}>
        <Main />
      </Provider>
    );
  }
}

export default App;

**Comment by SirPhemmiey** [comment]
Hi @walidvb, i used your method and was able to run it in Expo client. But when I make a new build with `expo build:android` the app crashes on opening. 

Please, help!

**Comment by SirPhemmiey** [comment]
Hi @walidvb, @Winnie16, i used your method and was able to run it in Expo client. But when I make a new build with expo `build:android` the app crashes on opening.

Please, help!

**Comment by walidvb** [comment]
@SirPhemmiey share your code? Were you able to see the error? Can you run in debug?

**Comment by SirPhemmiey** [comment]
Hi @walidvb , thanks for your response.

Below is the code I'm using
//myBranch.ts

```
(async function(){
  if (Constants.appOwnership === 'standalone') {
    const ExpoBranch = await import('expo-branch') //i have tried react-native-branch also
    const Branch = ExpoBranch;
    module.exports = ExpoBranch;

  }
   else {
    module.exports = {
      initSessionTtl: console.log(''),
      subscribe: async(bundle: any) => {
        console.log({bundleLol: bundle});
      },
      createBranchUniversalObject: async () => ({
        showShareSheet: (opts: {}, props: any, params: {}) => {
          console.log({});
        }
      })
    }
  }
})()
```

And I'm importing it normally as in:

`const Branch = require('../clients/branch/branch');
`

Thanks for your help

**Comment by walidvb** [comment]
@SirPhemmiey i'm not expert enough in js to have a proper answer, but why the wrap in async? Could be the issue. I think expo has added conditional and/or async imports recently, but i don't know how it works exactly, or whether it is already available in the latest SDK

**Comment by SirPhemmiey** [comment]
Hi @walidvb , i removed the async and it was still the same. This is disappointing.

**Comment by walidvb** [comment]
@SirPhemmiey it's difficult to tell without a crash log. Build your app in debug mode and see what that says.

**Comment by yzalvov** [comment]
Hello everyone. Thanks to a number of comments, I now handle the Branch code in dev and production environments.

But can anyone please help me to set up a simple thing? **I need to count installs.** Expo 40, managed workflow.
- I installed `expo-branch` according to the [Expo docs](https://docs.expo.io/versions/latest/sdk/branch/).
- I successfully import the `Branch` module and can confirm it works on a stand-alone build.
- I do `Branch.setIdentity('user_id')`

As a result – nothing on my dashboard.branch.io: no installs, no opens, nothing.
Please advise, should I consider any setup on dashboard.branch.io side? Many thanks for considering my request.

**Comment by MoeMamdouh** [comment]
Hello any one face the issue? @malikhamza0546  did you find a solution?

**Comment by shanekunz** [comment]
Assuming you just want to hide this error on Expo Go, and you don't actually care that Branch doesn't work on Expo Go, here is a working version in Expo v52:

```
// branch-sdk.js:
/**
 * Branch SDK Wrapper
 * 
 * This file conditionally exports either a mock version of the Branch SDK (for Expo Go development)
 * or the real Branch SDK (for standalone builds). This is necessary because the Branch SDK is not
 * compatible with Expo Go and will throw errors when trying to access native Facebook SDK constants
 * like STANDARD_EVENT_ADD_TO_CART that don't exist in the development environment.
 * 
 * The mock provides the same API surface as the real SDK but with console logging instead of
 * actual functionality, allowing development to proceed without crashes.
 */

import Constants, { ExecutionEnvironment } from 'expo-constants';

// Only mock in Expo Go (StoreClient) - Branch SDK works fine in Bare and Standalone environments
if (Constants.executionEnvironment === ExecutionEnvironment.StoreClient) {
  // Mock for Expo Go development
  module.exports = {
    subscribe: (callback) => {
      console.log('Branch SDK mock: subscribe called');
      // Call callback with empty params to prevent errors
      setTimeout(() => callback({ error: null, params: {}, uri: null }), 100);
      return () => {}; // Return unsubscribe function
    },
    getLatestReferringParams: async () => {
      console.log('Branch SDK mock: getLatestReferringParams called');
      return {};
    },
    createBranchUniversalObject: async () => ({
      showShareSheet: () => console.log('Branch SDK mock: showShareSheet called'),
    }),
    // Add other methods that might be used
    setIdentity: () => console.log('Branch SDK mock: setIdentity called'),
    logout: () => console.log('Branch SDK mock: logout called'),
    getFirstReferringParams: async () => {
      console.log('Branch SDK mock: getFirstReferringParams called');
      return {};
    }
  };
} else {
  // Use real Branch SDK in standalone builds
  module.exports = require('react-native-branch');
}
```

```
// +native-intent.js or wherever you were importing react-native-branch
import branch from "@/[path-to-file]/branch-sdk"; // Wrapped Branch SDK that mocks in Expo Go to prevent crashes - see branch-sdk.js for details
```
