### ISSUE TITLE
Cannot build android .apk with exp CLI

### ISSUE THREAD

**Issue by stochris** [expo/expo#535]
When trying to build the final .apk for android, I suddenly started getting the following error when running `exp build:status`: `Android: There was an error with this build.`

SDK version : 19.0
exp CLI version: 44.0.0

The project belongs to https://expo.io/@stochris.

I've already tried loging out of the cli, clearing keystore credential, and it did not help.

**Comment by jpca999** [comment]
i got similar issue

**Comment by stochris** [comment]
In the meantime, the problem seems to have been solved.

**Comment by dikaiosune** [comment]
@stochris I'm glad you were able to resolve this. @jpca999 can you post to our forums with your build ID? Happy to take a look at the logs for you.

**Comment by jpca999** [comment]
@dikaiosune  i think it got resolved now.
