### ISSUE TITLE
 Android: There was an error with this build.

### ISSUE THREAD

**Issue by jpca999** [expo/expo#536]
![image](https://user-images.githubusercontent.com/1026325/29619441-1ed738fe-87e9-11e7-9939-9258d8c0f807.png)

Build ID: 37af3e71-3d2c-4584-ab37-2d2d12f4cb00

![image](https://user-images.githubusercontent.com/1026325/29619528-536cb31e-87e9-11e7-8888-723e8d46fc47.png)

![image](https://user-images.githubusercontent.com/1026325/29619628-8b85559e-87e9-11e7-96b9-320eb861e7f3.png)

**Comment by dikaiosune** [comment]
Hi! It looks like the builder failed to fetch some code during a minor GitHub outage. Sorry for the inconvenience!
