### ISSUE TITLE
[docs] Improve web deploy to gh-pages Guide

### ISSUE THREAD

**Issue by cruzach** [expo/expo#5363]
Just a few changes need to be made to account for fixes made in [938](https://github.com/expo/expo-cli/pull/938)

**Comment by 5ervant** [comment]
@cruzach It would be great if we can deploy the complete static web pages of an Expo web application on GitHub Pages hosting. Is it already possible, where's the documentation?

Expo Forums > Help: Expo for Web:
https://forums.expo.io/t/how-to-generate-all-the-static-pages-of-your-expo-web-application/26554?u=5ervant

**Comment by cruzach** [comment]
Those instructions can be found [here](https://docs.expo.io/versions/latest/distribution/publishing-websites/#__next) (the github pages section needs an update, I'll get to that soon)

**Comment by 5ervant** [comment]
@cruzach I believe, that's the same guide that I've followed.

Check this GitHub Pages-hosted site: https://expo-gh-pages.github.io
That deployed site contains a link to: https://expo-gh-pages.github.io/Settings

There will be no problem if you click the _"Settings"_ navigation menu while you've initially visit the homepage. But if you directly visit the _"Settings"_ page using the above link, it will show you a _"File not found"_ page.

That's what I'm looking, to **completely deploy the static web pages of an Expo web application on GitHub Pages hosting.**

**Comment by 5ervant** [comment]
@cruzach It's also happening on Netlify: https://expo-gh-pages.netlify.com/Links

**Comment by cruzach** [comment]
Hey @5ervant , thanks for opening a [new issue](https://github.com/expo/expo/issues/5392), since it's not really related to this docs issue imo. We'll continue the conversation there
