### ISSUE TITLE
FaceDetector not working in iOS standalone builds after MLKit migration

### ISSUE THREAD

**Issue by rooque** [expo/expo#5373]
## 🐛 Bug Report

After FaceDetector started using MLKit, it stopped working in iOS standalone builds.

I think is related to Firebase not being configured correctly.

After running ```build:ios```, generating production ipa and sending it to TestFlight this is the log when I open the screen with FaceDetector :

```
6.5.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
```

Also I didn’t found anywhere I can provide my "GoogleService-Info.plist" file to configure Firebase. I think this is obligatory now that FaceDetector uses MLKit.

I tried building a version for android without any GoogleService info, installed apk direct to device (without putting it in play store) and FaceDetector just works. 

I’m missing something here?

### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.9
```

```
"dependencies": {
    "axios": "^0.19.0",
    "axios-retry": "^3.1.2",
    "expo": "^34.0.3",
    "expo-barcode-scanner": "~6.0.0",
    "expo-camera": "~6.0.0",
    "expo-face-detector": "~6.0.0",
    "expo-font": "~6.0.1",
    "expo-image-manipulator": "~6.0.0",
    "expo-linear-gradient": "~6.0.0",
    "expo-permissions": "~6.0.0",
    "lodash.debounce": "^4.0.8",
    "lodash.get": "^4.4.2",
    "lodash.inrange": "^3.3.6",
    "lodash.throttle": "^4.1.1",
    "native-base": "^2.12.1",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-confirmation-code-field": "^3.6.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-orientation-loading-overlay": "^0.1.6",
    "react-native-pose": "^0.9.1",
    "react-native-reanimated": "~1.1.0",
    "react-native-size-matters": "^0.2.1",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.0.3",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-saga": "^1.0.2",
    "reduxsauce": "^1.1.0"
  },
```

Targets: iOS and Android

### Steps to Reproduce

```build:ios``` app with FaceDetector.

### Expected Behavior

FaceDetector working.

### Actual Behavior

FaceDetector not working.

**Comment by topace124** [comment]
The same issue.

**Comment by wkozyra95** [comment]
add field `ios.googleServicesFile` to app.json (this requires latest cli)

**Comment by topace124** [comment]
Could you tell me exactly how to add the field to app.json file?
Thank you @wkozyra95

**Comment by topace124** [comment]
{
  "expo": {
    "name": "Scener",
    "slug": "Scener",
    "privacy": "public",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "-------",
      "publishBundlePath": "ios/scener/Supporting/shell-app.bundle",
      "publishManifestPath": "ios/scener/Supporting/shell-app-manifest.json"
    },
    "isDetached": true,
    "detach": {
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.12.4-sdk34.0.0-ee3e7450-9ec2-4836-8c8c-335483e62917.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.12.2-sdk34.0.0-767c7d3b-87b6-4f80-a9af-92ce67e2a49d.tar.gz"
    },
    "scheme": "exp9c201391878b4b5980820da0942e4a0c",
    "android": {
      "package": "---------",
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    }
  }
}

**Comment by wkozyra95** [comment]
@topace124  for ejected build it won't work. You need to add `JsonService-Info.plist` file to your project in xcode (follow instruction from firebase console). You'll also need to update `expo-face-detector` to version `6.0.1`

**Comment by topace124** [comment]
I added `GoogleService-Info.plist` file to my project in xcode.
and the `expo-face-detector` is version `6.0.1`.

**Comment by topace124** [comment]
It's not executed I think.

**Comment by topace124** [comment]
Could you help me with Teamviewer?

**Comment by wodin** [comment]
@topace124 according to the following it should be in the root of your project:

https://firebase.google.com/docs/ios/setup#add-config-file

**Comment by topace124** [comment]
@wodin Are you using expo?
And this is ejected expo project.

**Comment by topace124** [comment]
@wkozyra95 
`[FIRApp configure]` is not executed in EXFaceDetectorAppDelegate.m file.
Could you tell me why this happens?

**Comment by topace124** [comment]
The function is executed but `[FIRApp configure]` is not.

**Comment by topace124** [comment]
`[FIRApp configure]` is executed but the face detector is not working.

**Comment by topace124** [comment]
No, errors.
Just not detecting faces.
It says there is `GoogleServices-Info.plist` file exists.

**Comment by topace124** [comment]
Not, yet.
I don't build for Android.
I need only iOS.
So I did configure nothing for Android.

**Comment by topace124** [comment]
@wkozyra95 
Could you help me?

**Comment by wkozyra95** [comment]
What about my second question?

> What is the output of detectFacesAsync, have you tried it with different options, different images?

I don't work on sdk, so If it's configured properly I don't really have any ideas.
@mczernek

**Comment by mferak** [comment]
Hi, in case anyone needs to find a solution for how to make the expo FaceDetector work in a standalone RN app (no expo & not ejected), here's what I had to do:

1) [Generate my config file for Firebase](https://support.google.com/firebase/answer/7015592)
2) Add this config file to the ios/ProjectName folder
3) Initialize Firebase [per instructions here](https://firebase.google.com/docs/ios/setup#initialize-firebase), which basically means adding two lines to AppDelegate.m:

`#import "AppDelegate.h"
// Add this line
@import Firebase;`

And under the didFinishLaunchingWithOptions:

`  // Use Firebase library to configure APIs
  [FIRApp configure];`

**Comment by Aryk** [comment]
I'm on Managed SDK 38 and running the newest version of FaceDetector.

I cannot get it working on iOS standalone build:

https://github.com/expo/expo/issues/10392
