### ISSUE TITLE
Store and Retrieve Data from iCloud Storage

### ISSUE THREAD

**Issue by Miscavel** [expo/expo#5378]
Hi, is there a way to store and retrieve data from iCloud Storage via expo? I tried using this library : 

https://github.com/manicakes/react-native-icloudstore 

but was met with the following error :

null is not an object (evaluating '_reactNativeIcloudstore.default.getItem')

Thank you in advance.

**Comment by cruzach** [comment]
Hi! We keep github mainly for bug reports, so I'm going to close this (you're better off posting on our [forums](https://forums.expo.io/)!)

That library is a replacement for React Native's AsyncStorage, which we [provide access to](https://docs.expo.io/versions/latest/react-native/asyncstorage/)
