### ISSUE TITLE
FileSystem.createDownloadResumable() + MediaLibrary crashes without any error message

### ISSUE THREAD

**Issue by ArturasMi** [expo/expo#5379]
Hi, I was playing around with expo and noticed this issue. Basic functionality of this app is click and download video using file system and move to a photo gallery album with media library, it works as expected except if video is really large ( for example really high quality video that is 1GB ) my octa core machine cpu goes crazy up to 100% and 1/3 times app crashes without any error messages (tested on iPhone and Android ). Example code bellow:

const downloadResumable = FileSystem.createDownloadResumable(
      'https://example.ex/someFile.mp4',
      FileSystem.documentDirectory + 'file.mp4',
      {},
      callback,
      null
    );

    try {
      const { uri } = await downloadResumable.downloadAsync();
      const asset = await MediaLibrary.createAssetAsync(uri);
      MediaLibrary.addAssetsToAlbumAsync([asset],'MyAwesomeAlbum', false);
    } catch (e) {
      console.log(e);
    }

I'm not sure if I'm doing something wrong or file system was not created for large files or maybe there is another reason. Any help would be really appreciated.

**Comment by lukmccall** [comment]
I created a simple demo to test this. You can find it [here](https://snack.expo.io/@lukaszkosmaty/e3a1ab). To run it you need to provide `file URL` and `album id` (not name). 

I've tried to reproduce this bug and everything worked fine (It's worth to mention that I've run it only on Android - device and simulator). Please, test this demo and tell me if it works in your case.
