### ISSUE TITLE
Silent mode in iOS not working 

### ISSUE THREAD

**Issue by pauldcollins** [expo/expo#5380]
## 🐛 Bug Report
I can't get the Audio to Play when silent mode is on with iOS. Maybe it's the order I'm laying out the code in, but I can't find any examples of exactly what I'm trying to do.

### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.9
```

The environment is the Standalone Expo, using iOS

### Expected Behavior

Here is the current code I'm using - I'm wondering if I need to somehow wait for the `Audio.setAudioModeAsync` to load before triggering the `loadAsync` and `playAsync`?

```
async componentWillMount() {
    this.MySound = new Audio.Sound();
    await this.MySound.loadAsync(require("./MySound.mp3"));

    await Audio.setAudioModeAsync({
      playsInSilentModeIOS: true,
      allowsRecordingIOS: false,
      interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_MIX_WITH_OTHERS,
      shouldDuckAndroid: false,
      interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      playThroughEarpieceAndroid: true
    });
    await Audio.setIsEnabledAsync(true);
    await this.MySound.setPositionAsync(0);
  }

  handlePlaySound = async () => {
    try {
      await this.MySound.setPositionAsync(0);
      await this.MySound.playAsync();
    } catch (error) {
      console.log("ERROR", error);
    }
  };
```

Thanks for any help

**Comment by ide** [comment]
I tested this about a month ago and it worked. You need to use a real device IIRC and make sure your volume is up and silent mode is on and the audio should play.

**Comment by pauldcollins** [comment]
Thanks for your comments @ide 

I'm testing on a real device, tried multiple iPhones - using iOS and TestFlight. But, for some reason it doesn't work.

Do you remember your code, or do you have an example of it? Just wondering if it's the order I'm doing things - do I need to set `setAudioModeAsync` properties before adding sound perhaps?

**Comment by ide** [comment]
This is some sample code: https://github.com/expo/expo/blob/master/home/screens/AudioDiagnosticsScreen.tsx. You can open the latest Expo client on iOS, go to the Diagnostics tab, and select the Audio diagnostics to try it out.

**Comment by pauldcollins** [comment]
Hi @ide 

I got it working, thanks to your example! I was missing this line:

`staysActiveInBackground: false`

All working now, thanks heaps!
