### ISSUE TITLE
GeoFencing isn't working when the app is killed/closed (not in the background)

### ISSUE THREAD

**Issue by zacksayenko** [expo/expo#5383]
Environment
iPhone
iOS 12.4

npmPackages:
expo: 34.0.0
"react": "16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
"expo-location": "~6.0.0",
"expo-task-manager": "~6.0.0",

### Steps to Reproduce
Testing GeoFencing. Running on a stand alone device. 
Everything works correctly when the app is in the foreground (open) or in the background.
However, as soon as I swipe up the app and kill it. GeoFencing stops working. No event notifications are received when either entering or exiting the specified location. 

### Relevant Code
In App.js (in global scope, not inside a component)
```
TaskManager.defineTask(GEO_TRACK_LOCATION, (args) => {
    Segment.trackWithProperties('GEO_TRACK_' + args.data.eventType, args);
});
```

```
Location.startGeofencingAsync(GEO_TRACK_LOCATION, regions)
.then(result => console.log(`${GEO_TRACK_LOCATION} started`));
```

### Expected Behavior
App should wake up when entering or exiting a specified location and fire off an update.

### Actual Behavior
No geofencing updates are sent when the app is killed/closed
Works as expected when app is open/foreground/background

**Comment by cruzach** [comment]
Hi! this looks really similar to #3503 

I see you commented on that thread, so is there something different about this situation? Otherwise we should probably close this in favor of 3503, to keep the conversation in one place

**Comment by zsayenko** [comment]
That one is about startLocationUpdatesAsync not working, which seemed to work fine for me when we did the testing.
I've only ran into issues with startGeofencingAsync not sending updates, so decided to create a new issue which clearly captures the problem that we are seeing. 
I've also noticed that the check for background location was removed when starting/stopping geofencing - https://github.com/expo/expo/pull/5198

Wasn't sure if there was a relationship there?

**Comment by zacksayenko** [comment]
That one is about startLocationUpdatesAsync not working, which seemed to work fine for me when we did the testing.
I've only ran into issues with startGeofencingAsync not sending updates, so decided to create a new issue which clearly captures the problem that we are seeing. 
I've also noticed that the check for background location was removed when starting/stopping geofencing - https://github.com/expo/expo/pull/5198

Wasn't sure if there was a relationship there?

**Comment by zsayenko** [comment]
Any updates on this guys?

**Comment by rcabarreto** [comment]
Hey guys, I'm having a similar problem, maybe one of you can help me.

I'm running startGeofencingAsync with some regions. They work fine when the app is in foreground and when the app is recently backgrounded, but after some time (a few hours) it just stops reporting the geofencing events. I noticed that it happens when the app gets "suspended" (it still shows on the task manager, but when you open it, it's like it's starting up again).

Also, when the app is closed it does not work. 

Is there anyway to keep the geofences working on background?

**Comment by leemcmullen** [comment]
Hello! Any update on this issue? Can’t seem to get it working either when the app is killed. No longer seems to fire the event when the region is entered or exited.

**Comment by Tbeck-91** [comment]
I have this issue on android currently, works fine on a standalone app but the app doesn't receive any updates from the background task if the app is suspended or killed.

**Comment by ourmaninamsterdam** [comment]
I'm also experiencing the same issue with Geofencing on Android. Works fine when the app is in the foreground/background but not when the app is killed. Same issue on emulator and device.

**Comment by ahmadshakeel78** [comment]
geofencing is working fine but with some permission like location always in android and IOS. But below IOS13 it will not support.
The best way if you want to check you are in the circle or not is below..


function distance(checkPoint, centerPoint) {
    var ky = 40000 / 360;
    var kx = Math.cos(Math.PI * centerPoint.lat / 180.0) * ky;
    var dx = Math.abs(centerPoint.lng - checkPoint.lng) * kx;
    var dy = Math.abs(centerPoint.lat - checkPoint.lat) * ky;
    return Math.sqrt(dx * dx + dy * dy);
}

function arePointsNear(checkPoint, centerPoint, km) {
    var ky = 40000 / 360;
    var kx = Math.cos(Math.PI * centerPoint.lat / 180.0) * ky;
    var dx = Math.abs(centerPoint.lng - checkPoint.lng) * kx;
    var dy = Math.abs(centerPoint.lat - checkPoint.lat) * ky;
    return Math.sqrt(dx * dx + dy * dy) <= km;
}

var vasteras = { lat: 25.303612, lng:55.367048 };
var stockholm = { lat:25.304092,lng: 55.366993};

console.log(distance(vasteras, stockholm));
console.log(arePointsNear(vasteras, stockholm, 0.04));
console.log(arePointsNear(vasteras, stockholm, 0.04));
