### ISSUE TITLE
Expo AR doens't work in production or in development with ExpoKit

### ISSUE THREAD

**Issue by jacklj** [expo/expo#5384]
### Environment

```
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.0.10
```

### Expected Behavior
Expo AR doesn't crash immediately in production, or in development when ejected to ExpoKit.

### Actual Behavior
When developing a simple AR app with marker recognition, with the Managed workflow, it works well in development. However the standalone app in production immediately crashes, with the following error:
```
TypeError: this._nativeModule.addListener is not a function. (In 'this._nativeModule.addListener(eventType)', 'this._nativeModule.addListener' is undefined)
```

I also tried ejecting to ExpoKit - I then see this same error in dev builds when I build to my phone from Xcode. 

Seems that the AR module only works with the managed workflow, in development, but not in production or once ejected to ExpoKit.

### Reproducible Demo
https://snack.expo.io/@jackvlj/expo-ar-production-expokit-bug

To see the error, you need to build this as a standalone app and run it on your device, or eject to ExpoKit and build locally from Xcode.

Thanks!

**Comment by EvanBacon** [comment]
ExpoKit and AR have both been deprecated in SDK 37, if you have interest in working on the bare-workflow community package https://github.com/expo-community/expo-ar please let us know.
