### ISSUE TITLE
[iOS][expo-sms] Improvements

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#5386]
- [ ] Using two different methods for `isAvailableAsync` [this](https://github.com/expo/expo/blob/e4aaf37cfefa8408426a8573d788a0981272643b/packages/expo-sms/ios/EXSMS/EXSMSModule.m#L32) should be [this](https://github.com/expo/expo/blob/e4aaf37cfefa8408426a8573d788a0981272643b/packages/expo-sms/ios/EXSMS/EXSMSModule.m#L43)... or both ¯\\\_(ツ)\_\/¯ (regardless, same method should be used). Edit: The current method returns `true` in the iOS simulator, when it should be `false`.
- [ ] Missing docs description: 
  - **Android:** The device has a telephony radio with data communication support.
  -   **iOS:** Application can open a url with the `sms:` prefix. (should probably be different)
- [ ] All external view controllers should have a method for dismissing, controlling animated presentation, and completion callback (needed for testing) [target code](https://github.com/expo/expo/blob/e4aaf37cfefa8408426a8573d788a0981272643b/packages/expo-sms/ios/EXSMS/EXSMSModule.m#L64) (expo-av does this for videos)
- [ ] delete [permissions manager](https://github.com/expo/expo/blob/e4aaf37cfefa8408426a8573d788a0981272643b/packages/expo-sms/ios/EXSMS/EXSMSModule.m#L23)

- Missing iOS features: `disableUserAttachments`, `isSupportedAttachmentUTI(UTI: string)`, `canSendAttachments`, `canSendSubject`, `canSendText`, `subject`, `attachments`, `addAttachmentURL(attachmentURL: NSURL)`, `addAttachmentData()`

- [ ] should have a standard `concurrent task` error code instead [of this](https://github.com/expo/expo/blob/e4aaf37cfefa8408426a8573d788a0981272643b/packages/expo-sms/ios/EXSMS/EXSMSModule.m#L49)

- [ ] change [incorrect error message](https://github.com/expo/expo/blob/e4aaf37cfefa8408426a8573d788a0981272643b/packages/expo-sms/ios/EXSMS/EXSMSModule.m#L79) Should be `User's attempt to save or send was unsuccessful.`
- [ ] delete [unreachable condition](https://github.com/expo/expo/blob/e4aaf37cfefa8408426a8573d788a0981272643b/packages/expo-sms/ios/EXSMS/EXSMSModule.m#L87) creating FUD

**Comment by EvanBacon** [comment]
`expo-mail-composer` API should match the `expo-sms` API

**Comment by owencm** [comment]
It'd be great to also update docs to specify how to provide no recipient, since this is common for SMS flows and not documented today (I tried null and '' to no avail before trying []).
