### ISSUE TITLE
TypeError: Parse.setAsyncStorage is not a function

### ISSUE THREAD

**Issue by FahadAlbukhari** [expo/expo#5388]
×
TypeError: Parse.setAsyncStorage is not a function
../../../../../../../../Documents/T/app/t/src/API.js/<
src/API.js:4

  1 | const Parse = require('parse/react-native');
  2 | import { AsyncStorage } from "react-native";
  3 | 
> 4 | Parse.setAsyncStorage(AsyncStorage);
  5 | Parse.initialize("62e0b0de934753870808063b4baa617ca3a84450");
  6 | Parse.serverURL = 'https://parse.t.com/parse'
  7 | 

../../../../../../../../Documents/T/app/t/src/API.js
http://192.168.1.79:19006/static/js/bundle.js:140643:30
__webpack_require__
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T/app/t/src/Screens/Coupon.js
src/Screens/Coupon.js:4

  1 | import React, { Component } from "react";
  2 | import { ActivityIndicator, Alert, Dimensions, FlatList, View, StyleSheet} from "react-native";
  3 | import { Avatar, Divider, Icon, Text, ListItem } from "react-native-elements";
> 4 | const Parse = require("../API");
  5 | var {height, width} = Dimensions.get('window');
  6 | 
  7 | var hasOne = false

__webpack_require__
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T/app/t/src/navigation/AppNavigator.js
src/navigation/AppNavigator.js:1

> 1 | import { createAppContainer, createSwitchNavigator } from 'react-navigation';
  2 | 
  3 | import Coupon from "../Screens/Coupon";
  4 | import Netinfo from "../Screens/Netinfo";

__webpack_require__
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T/app/t/App.tsx
http://192.168.1.79:19006/static/js/bundle.js:827:87
__webpack_require__
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T/app/t/node_modules/expo/AppEntry.js
node_modules/expo/AppEntry.js:1
__webpack_require__
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

0
http://192.168.1.79:19006/static/js/bundle.js:154063:18
__webpack_require__
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

(anonymous function)
/Users/alghreeb/Documents/T/app/t/webpack/bootstrap:791

  788 | 
  789 | 
  790 | // Load entry module and return exports
> 791 | return hotCreateRequire(0)(__webpack_require__.s = 0);
      | ^  792 | 

(anonymous function)
http://192.168.1.79:19006/static/js/bundle.js:795:10
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by cruzach** [comment]
From your stack trace:
```
1 | const Parse = require('parse/react-native');
2 | import { AsyncStorage } from "react-native";
```
It looks like you're importing differently than [`parse` recommends](https://www.npmjs.com/package/parse). I'd go through their docs and make sure you're implementing correctly.

I don't think this a bug with Expo so I'm going to close this issue. If you can provide all the info we ask for in the bug report template, including a repro, I'll be happy to re-open.

**Comment by FahadAlbukhari** [comment]
Same problem.

×
TypeError: Parse.setAsyncStorage is not a function
../../../../../../../../Documents/T's/app/Ts/src/API.js
src/API.js:4

  1 | const Parse = require('parse/react-native');
  2 | // On React Native >= 0.50 and Parse >= 1.11.0, set the Async
  3 | const AsyncStorage = require('react-native').AsyncStorage;
> 4 | Parse.setAsyncStorage(AsyncStorage);
  5 | 
  6 | 
  7 | Parse.initialize("62e0b0de934753870808063b4baa617ca3a84450");

__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/src/Screens/Coupon.js
src/Screens/Coupon.js:4

  1 | import React, { Component } from "react";
  2 | import { ActivityIndicator, Alert, Dimensions, FlatList, View, StyleSheet} from "react-native";
  3 | import { Avatar, Divider, Icon, Text, ListItem } from "react-native-elements";
> 4 | const Parse = require("../API");
  5 | var {height, width} = Dimensions.get('window');
  6 | 
  7 | var hasOne = false

__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/src/navigation/AppNavigator.js
src/navigation/AppNavigator.js:1

> 1 | import { createAppContainer, createSwitchNavigator } from 'react-navigation';
  2 | 
  3 | import Coupon from "../Screens/Coupon";
  4 | import Netinfo from "../Screens/Netinfo";

__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/App.tsx
http://192.168.1.79:19006/static/js/bundle.js:827:87
__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/node_modules/expo/AppEntry.js
node_modules/expo/AppEntry.js:1
__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

0
http://192.168.1.79:19006/static/js/bundle.js:154086:18
__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

(anonymous function)
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:791

  788 | 
  789 | 
  790 | // Load entry module and return exports
> 791 | return hotCreateRequire(0)(__webpack_require__.s = 0);
      | ^  792 | 

(anonymous function)
http://192.168.1.79:19006/static/js/bundle.js:795:10
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
