### ISSUE TITLE
[expo-branch] Calling branchUniversalObject's generateShortUrl() function crashes app

### ISSUE THREAD

**Issue by AryanJ-NYC** [expo/expo#5391]
### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.9
### Steps to Reproduce

1. Call `generateShortUrl` from a `branchUniversalObject` instance
2. Watch the app break.

For example:

```js
export default class App extends React.Component {
  state = { url: "emptyfornow" };

  onPress = async () => {
    console.log("build to a standalone device to see the app break!");
    if (Constants.appOwnership === "standalone") {
      const { Branch } = await import("expo-branch");
      const branchUniversalObject = await new Branch().createBranchUniversalObject(
        `imsuchauniqueid`,
        {
          canonicalUrl: "http://blank.us",
          contentMetadata: {
            customMetadata: {
              urlCode: "1700"
            }
          },
          locallyIndex: true
        }
      );

      const { url } = await branchUniversalObject.generateShortUrl();
      this.setState({ url });
    }
  };
  render() {
    return (
      <View style={styles.container}>
        <Text>{this.state.url}</Text>
        <TouchableOpacity onPress={this.onPress}>
          <Text>Create a Branch Universal Object</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```
### Expected Behavior
It doesn't break.

### Actual Behavior
It breaks.

![Screenshot_20190819-215456](https://user-images.githubusercontent.com/8263430/63312552-e3f4c980-c2cf-11e9-8566-17d1a848b0c3.jpg)

### Reproducible Demo
https://github.com/AryanJ-NYC/expo-sandbox

### Possibly Related Issues

- https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/517
- https://forums.expo.io/t/current-status-of-branch-sdk-integration/1626
- https://mobilegrowth.org/questions/question/short-url-null-android-sdk/
- https://github.com/expo/expo/issues/3546

**Comment by sjchmiela** [comment]
Hey, this issue has been fixed both on `master` (so for upcoming SDK35) and for SDK34. Try rebuilding your app with `expo build:android` — everything should work as expected now. 🙂
