### ISSUE TITLE
[docs] "Page Not Found" error by deploying on Netlify and GitHub Pages

### ISSUE THREAD

**Issue by 5ervant** [expo/expo#5392]
Here's my deployed Expo web app on GitHub Pages hosting: https://expo-gh-pages.github.io
And here's on Netlify: https://expo-web.netlify.com

Their problems are similar, if you click and visit either any of these pages directly, you'll get a 404 _"Page Not Found"_ error:
- https://expo-web.netlify.com/Links
- https://expo-gh-pages.github.io/Links

However, you can access the _"Links"_ page when you click the _"Links"_ menu at the bottom while you are on their homepage.

Here's the documentation that will guide you how to deploy on Netlify and on GitHub Pages:
https://docs.expo.io/versions/latest/distribution/publishing-websites/

But unfortunately, deploying Expo web app on either Netlify or GitHub Pages does not work as expected. It would be great if there's already a solution for this!

**Comment by 5ervant** [comment]
@cruzach @EvanBacon Here's the solution for deploying on Netlify:
https://www.netlify.com/docs/redirects/#history-pushstate-and-single-page-apps

**Comment by EvanBacon** [comment]
Thanks for the research! We've done a bunch of work to fixup and test deployment on GH pages. https://github.com/expo/expo-cli/pull/938 https://github.com/expo/expo-cli/pull/1336
