### ISSUE TITLE
[iOS][Location] Location.getCurrentPositionAsync() always returns "speed = -1"

### ISSUE THREAD

**Issue by cjgendron** [expo/expo#5401]
### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.10

### Steps to Reproduce

Copy and paste example code listed at https://docs.expo.io/versions/latest/sdk/location/. Bug occurs on Xcode iOS simulator and Expo client on device.

### Expected Behavior

Coords should list accurate speed.

### Actual Behavior

Coords always show speed as -1.

### Reproducible Demo

https://expo.io/@purplemudkip/InstantSpeed
Source code is exact replica of example code in SDK documentation.

**Comment by cjgendron** [comment]
![IMG_1159](https://user-images.githubusercontent.com/7276432/63397258-03572980-c398-11e9-965e-565a12807789.jpg)
Here's an example of the values I get from Location.getCurrentPositionAsync().

**Comment by cruzach** [comment]
Afaik, `speed: -1` indicates an invalid speed (meaning you're not moving)

Expo is copying the speed value from the [iOS location object's speed](https://developer.apple.com/documentation/corelocation/cllocation/1423798-speed). By just asking for one current location, not sure if it’s possible to obtain a value for speed.

This is also explained here -> https://stackoverflow.com/questions/30098202/cllocationmanager-always-returning-speed-1/30107728#30107728 13

**Comment by cjgendron** [comment]
@cruzach - I updated my expo app linked above to fetch the location every 5 seconds. Walking around the house, it's still giving me -1. I'm going to take my phone out for a drive and see if I get the same results.

I haven't tested on Android at all.

**Comment by cruzach** [comment]
What device/iOS version is this happening on?

I just [tested on a simulator](https://docs.expo.io/versions/latest/sdk/location/#enabling-emulator-location) and simulated driving on a freeway, and got appropriate speed values on iPhone X iOS 12.2

**Comment by cjgendron** [comment]
Physical device is iPhone XR iOS 12.4. Xcode simulator is iPhone X 12.1.

**Comment by cruzach** [comment]
Going to close this for inactivity, @cjgendron let me know if you are still seeing this when running the project in the repo I linked, and we can investigate further
