### ISSUE TITLE
ExpoKit - SDK 34 - ExBranchManager branchModuleDidInit unreconigzed selector

### ISSUE THREAD

**Issue by owenhope** [expo/expo#5407]
Hi,

I am running my app on iOS ... and I get random crashes on app launch (fresh launch) regarding ExBrancManager and branchModuleDidInit

Full error:

`Fatal Exception: NSInvalidArgumentException -[EXBranchManager branchModuleDidInit:]: unrecognized selector sent to instance 0x2826bd2a0 -[EXScopedBranch setModuleRegistry:]`

Any advice?

**Comment by neilco** [comment]
We're also experiencing this. It seems that `setModuleRegistry:` is retrieving `EXBranchManager` when it’s expecting `EXScopedBranch`. 

Changing [this line](https://github.com/expo/expo/blob/ios/2.12.4/ios/Exponent/Versioned/Core/UniversalModules/EXScopedBranch.m#L35) in `EXScopedBranch.m` to the following seems to resolve this issue:

```objc
[(id<EXBranchScopedModuleDelegate>)[_moduleRegistry getModuleImplementingProtocol:@protocol(EXBranchScopedModuleDelegate)] branchModuleDidInit:self];
```

**Comment by rxhivzero** [comment]
same problem

**Comment by cruzach** [comment]
Can one of your share the steps to reproduce this crash? Does it occur on SDK 35?

**Comment by raheelshah31** [comment]
Is this fixed in SDK 35 ?

**Comment by cruzach** [comment]
Tested on SDK 36, and I'm not having any trouble using Branch in an iOS standalone app

If you are seeing this issue, please provide a method to reproduce it
