### ISSUE TITLE
Using images in Lottie with Expo

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#541]
OK, so I think this is possible, theoretically. Normally, to use an image in Lottie, you would either set the folder (Android) or add an image as an image asset (iOS), and then refer to it by name (file name, I believe). After looking at this comment (https://github.com/airbnb/lottie-react-native/issues/145#issuecomment-310788316), it looks like it should be possible to use the pre-fetched images in expo, but they're not appearing for me. These are the params I have to play with:
```json
"assets": [
    {
      "id": "CookerGradient",
      "w": 1000,
      "h": 1000,
      "u": "/images",
      "p": "CookerGradient.jpg"
    }
  ],
```
Can I put the right thing in there so that Lottie will detect and use my image? If I get this figured out, I'll add some docs via PR.

**Comment by mgscreativa** [comment]
The same here for me, trying this animation I get a blank view...

https://www.lottiefiles.com/786-workout

**Comment by friendlyuis** [comment]
Hi,

Did anyone solve this yet? I think I may have to eject... https://github.com/airbnb/lottie-react-native/issues/228

**Comment by gvnc** [comment]
An animation without an image makes no sense at all, so this must be fixed.
But I guess noone is looking at this, so my conclusion is that lottie is not something you can use with expo. 
Why would I use expo if I have to eject my project to make it work ?

**Comment by hiteshchaudhari-tudip** [comment]
Hey did anyone get a solution to this?

**Comment by aindong** [comment]
I wonder why this issue is closed but no solution so far?

**Comment by mikeaveli007** [comment]
I was able to get this to work by enabling the "Include in Json" option in Bodymoving settings.  Settings->Assets->Include in json
