### ISSUE TITLE
Pedometer not available soms phone (Samsung A40, Nokia 5.1)

### ISSUE THREAD

**Issue by Tinkvision** [expo/expo#5419]
### Environment
Android

### Steps to Reproduce

Lance demo example (https://docs.expo.io/versions/latest/sdk/pedometer/) on Samsung A40 or Nokia 5.1

### Expected Behavior
isAvailableAsync is returning true or false (but with the reason why is false)

### Actual Behavior
isAvailableAsync is returning false. I don't know why, there are no reason and no error. 
I can't find the reason why is not available on theses phones

The code works fine on other smartphone like OnePlus 6T.

### Code Example
```
import React, { useEffect, useState, useRef } from 'react';
import {
  Text, View,
} from 'react-native';
import { Pedometer } from 'expo-sensors';
import { styles } from './styles';
import I18n from '../../i18n/I18n';
import messages from './messages';

function PedometerComponent({ pedometer, setPedometer }) {
  let subscription = useRef(null).current;
  const [available, setAvailable] = useState('');
  const subscribe = () => {
    subscription = Pedometer.watchStepCount(result => setPedometer(result.steps), error => console.log(error));
    Pedometer.isAvailableAsync().then(
      (result) => {
        setAvailable(String(result));
      },
      (error) => {
        setAvailable(I18n.t(messages.podometerNoAvailable, { error }));
      },
    );
  };
  const unsubscribe = () => {
    if (subscription) { subscription.remove(); }
    subscription = null;
  };
  useEffect(() => {
    subscribe();
    return () => {
      unsubscribe();
    };
  }, []);

  return (
    <View style={styles.container}>
      <Text>{available}</Text>
      <Text style={styles.podometer}>
        {I18n.t(messages.stepCount.id, { stepCount: pedometer })}
      </Text>
    </View>
  );
}

export default PedometerComponent;
```

**Comment by cruzach** [comment]
Are you testing on real devices, not simulators?

**Comment by Tinkvision** [comment]
Real device ;) yes

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by AlastairTaft** [comment]
Seeing this behavior as well. Still trying to figure out the cause.

**Comment by Tinkvision** [comment]
Some news about this ?

**Comment by arzola** [comment]
@Tinkvision I started to have the same problem but with lot of android phones becase they delivered an incomplete Pedometer implementation for android in the new Expo > 34 unimodules

**Comment by cruzach** [comment]
@Tinkvision does this not happen for you on SDK 33? If so, then we should close this issue as a duplicate of the one arzola linked

**Comment by Tinkvision** [comment]
Sorry, yes it's happen for me on SDK 33 too with the workaround @arzola  (@cruzach)

**Comment by jhowpaes** [comment]
@Tinkvision  Were you able to solve the problem? Because I'm experiencing the same problem where the pedometer activates on Motorola phones, but not on samsung. Use react-native with unimodules expo package.

**Comment by Tinkvision** [comment]
Hello @jhowpaes, 

Sorry I haven't found a solution and in the meantime I've changed company so I can't say if my successor has found a solution to the problem. 

I had disabled the functionality on the devices that have the problem.

**Comment by jhowpaes** [comment]
Hello @Tinkvision,

Thank you for giving feedback.
