### ISSUE TITLE
Ad working in expo client but in android standalone app: ERROR_CODE_NO_FILL

### ISSUE THREAD

**Issue by dcefram** [expo/expo#5420]
### Environment

**expo diagnostics**:
```
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.11.1 
```

**App's target**: Android (standalone, apk)

### Steps to Reproduce

I'm using managed workflow.

```
import { AdMobBanner } from 'expo-ads-admob';

// And then used somewhere in the render method
<AdMobBanner
  bannerSize="banner"
  adUnitID={
    Platform.OS === 'ios'
      ? settings.IOSAdUnitID
      : settings.AndroidAdUnitID
  }
  testDeviceID="EMULATOR"
  onDidFailToReceiveAdWithError={handleError}
/>
```

#### Running app through Expo app
**IOS:** banner shows properly
**Android:** banner shows properly

#### Running app through standalone versions
**IOS:** banner shows properly
**Android:** banner should show properly

#### Running app through Expo app
**IOS:** banner shows properly
**Android:** banner shows properly

#### Running app through standalone versions
**IOS:** banner shows properly
**Android:** banner does not show. `onDidFailToReceiveAdWithError` will be triggered, and based on my logs, it's receiving `ERROR_CODE_NO_FILL`. And sometimes I would also log some more detailed error.

> Admob failed: Error Domain=com.google.ads Code=1 "Request Error: No ad to show."

### Reproducible Demo

```
import React from 'react';
import { View, Platform } from 'react-native';
import { shape } from 'prop-types';
import { AdMobBanner } from 'expo-ads-admob';

import settings from '../../constants/AdmobSettings';

import styles from './Ads.style';

function Ads({ style }) {
  function handleError(error) {
    // some remote logging thingy here
  }

  return (
    <View style={[styles.container, style]}>
      <AdMobBanner
        bannerSize="banner"
        adUnitID={
          Platform.OS === 'ios'
            ? settings.IOSAdUnitID
            : settings.AndroidAdUnitID
        }
        testDeviceID="EMULATOR"
        onDidFailToReceiveAdWithError={handleError}
      />
    </View>
  );
}

Ads.propTypes = {
  style: shape({}),
};

export default Ads;
```

NOTE: I'm aware that #4684 is somewhat similar, but this one is using `AdMobBanner` and the error code is somewhat different.

**Comment by cruzach** [comment]
Based on [Google's docs](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_NO_FILL), it looks like it could be an issue with the `adUnitID`

Should note that sometimes it takes awhile for the ad to be served, but I'm not sure why that would only affect one platform rather than both

**Comment by dcefram** [comment]
I see... although, why does it consistently work when I load it up through expo's app? Is it because those are just test ads that I'm seeing through that? I always thought that the test ads are only loaded in the emulator...

**Comment by cruzach** [comment]
@dcefram were you able to find the root cause of this error on Android? I'm interested as to why it was working on one platform's standalone but not the other

**Comment by dcefram** [comment]
@cruzach no, I never got that to work, nor was I able to dig any further as to what the root cause is.

**Comment by ragrag** [comment]
any luck getting ads to show on standalone apps? i'm getting a blank space in the app as well.

**Comment by gogovan-anthonychan** [comment]
I encounter this error too. I had already set up like the document descript. Don't know why yet.

**Comment by ragrag** [comment]
the issue is solved when you deploy the app to the play store

**Comment by cruzach** [comment]
@dcefram can you confirm that solution?

**Comment by dcefram** [comment]
Yes, the ads seemed to be working when deployed to play store :)
