### ISSUE TITLE
When launching a Chrome Custom Tab (through `openBrowserAsync`) on Android, the intent does not persists

### ISSUE THREAD

**Issue by aav7fl** [expo/expo#5422]
### Environment

```
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.10.1 - ~/.nvm/versions/node/v12.6.0/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.0.10
```

App target is both iOS and Android apps using Expo SDK 34.

### Steps to Reproduce

On PR #4882 , there was a code change that made Custom Tabs opened in *Android* no longer show up in the device history. 

https://github.com/expo/expo/pull/4882/files#diff-181a67a85ff6d2497b2ab4301faf3769R133-R134

That means when we call an external link in our app (on *Android devices), and the user briefly leaves the view, it closes on them.

#### Scenario 1:

1. The user clicks the menu item which makes a `openBrowserAsync` call to a url.

2. The user views their task list.

3. The chrome custom tab *dismisses itself* without me tapping on anything.

![app_switch](https://user-images.githubusercontent.com/3487107/63534820-065c3200-c4de-11e9-88d4-5740e68f4180.gif)

#### Scenario 2:

1. The user clicks the menu item which makes a `openBrowserAsync` call to a url.

2. The user navigates home on their device.

3. The chrome custom tab *dismisses itself* in the background and the user cannot return to it.

![app_home](https://user-images.githubusercontent.com/3487107/63535030-808cb680-c4de-11e9-869d-8a263b351ae8.gif)

### Expected Behavior

I am expecting the custom chrome tab to persist if I leave the app and return. *Just like how it behaves on our iOS app.* 

If the user leaves the app to check on something else, we shouldn't close their session in case they were in the middle of finishing something up.

### Actual Behavior

The custom chrome tab is closed immediately when the app is put in the background/loses focus. 

### Reproducible Demo

https://snack.expo.io/@kylegfs/call-openbrowserasync

In the demo, tap purple the button. 

On Android, if you leave the app (by going home, or viewing the other opened apps), the web browser goes away (bad!).

On iOS, if you leave the app, the web browser stays (good!).

**Comment by cruzach** [comment]
Hey @aav7fl , is this happening on a particular device? Just tried your snack, and saw the same behavior on both iOS and Android sims (if you leave the app, the web browser stays)

**Comment by aav7fl** [comment]
Hi. I've only tested this on real devices. Both devices exhibit the behavior in the snack, and my app. 

I'm able to replicate on my Google Pixel 2, Android 9. I'm also able to replicate it on a Moto X4 running Android 9. Those are the only two real Android devices I have around.

**Comment by aav7fl** [comment]
I was able to pull out an older device of mine, Samsung Galaxy S5 running Android 6.0.1. I was _unable_ to reproduce on this device.

I'm wondering if it's only happening in more recent versions of Android.

Recap:

| Device            | Android Version | Can Replicate |
|-------------------|-----------------|---------------|
| Pixel 2           | 9               | Yes           |
| Moto X4           | 9               | Yes           |
| Samsung Galaxy S5 | 6.0.1           | No            |

**Comment by aav7fl** [comment]
For debugging sake, here is the snack on my Pixel 2 with both scenarios. 

![expo_bug](https://user-images.githubusercontent.com/3487107/63593981-40cbda80-c583-11e9-9d62-3467a79a0b50.gif)

My co-worker with a Pixel 3 cannot replicated in the snack, but can in the app.

We dug into _why_.

When he opens the snack on Expo with his device, it's not opening the `Chrome Custom Tab` in the same way. See how in the overview it's not tossing it away _and_ the icon shows Expo? 

![Screenshot_20190823-084759](https://user-images.githubusercontent.com/3487107/63594049-69ec6b00-c583-11e9-9920-ea958a32ea16.png)

But in my Gif above, when I view the overview, you can see the chrome icon for a short second before it dismisses itself. 

![image](https://user-images.githubusercontent.com/3487107/63594398-5b528380-c584-11e9-804b-245114e8db1b.png)

**Comment by aav7fl** [comment]
Issue still persists on Android 10 (public release).

**Comment by SimenB** [comment]
Having the same issue, and using the new `showInRecents` from #5442 fixes it. We're stuck on v34 due to svg issues though, so can't use it...

**Comment by aav7fl** [comment]
> Having the same issue, and using the new `showInRecents` from #5442 fixes it. We're stuck on v34 due to svg issues though, so can't use it...

Thanks for the heads up about that PR. We hadn't seen that one yet. It looks like it is fixed in the SDK 35 for us by adding `showInRecents: true` to `openBrowserAsync()`. There are no options for `openAuthSessionAsync()`, but that's good enough since we don't intent to have them log in _that_ often. 

Thanks for you work on adding back that option @mczernek!

**Comment by GuyAvraham** [comment]
Is there a similar `showInRecents : true` for `openAuthSessionAsync `.
Its available only with `openBrowserAsync `
https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowseropenbrowserasyncurl

**Comment by cruzach** [comment]
`openAuthSessionAsync` falls back to `openBrowserAsync`, so the options you pass to it will trickle-down to `openBrowserAsync`

We do need to update the docs to reflect this, but you can see that it's the case by taking a look at the javascript source

**Comment by GuyAvraham** [comment]
@cruzach Thanks, now I see it.
I used 
`import { AuthSession } from 'expo';`
As shown here:
https://docs.expo.io/versions/latest/sdk/auth-session/#example

But then after reading your comment, I found the 'showInRecents' implemented on AuthSession when importing it from `expo-auth-session` instead of from 'expo'.
