### ISSUE TITLE
Import { AppLoading } from 'expo'

### ISSUE THREAD

**Issue by nabeel-s** [expo/expo#5423]
I'm trying to update the old imports to their individual packages for SDK 33.

I have this line in my code:

`import { AppLoading } from 'expo'`

Which package can I update this import to? I tried using expo-codemod but it didn't update this line.

**Comment by cruzach** [comment]
You'll still use the same import syntax for the `Apploading` module

You can always check the [docs](https://docs.expo.io/versions/latest/sdk/app-loading/) for this information
