### ISSUE TITLE
[iOS 13] Print Example API adds black area

### ISSUE THREAD

**Issue by giautm** [expo/expo#5439]
### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.7479.19.35.5763348
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.2 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.9
```
App target: Expo Client on iOS

### Steps to Reproduce

Choose `Print HTML` from example app.

### Expected Behavior

Print example without black area
![IMG_E32C31503BAE-1](https://user-images.githubusercontent.com/12751435/63661665-c353d480-c7e5-11e9-8593-7069770fd652.jpeg)

### Actual Behavior

Printer preview show black area
![IMG_950D1DA8694A-1](https://user-images.githubusercontent.com/12751435/63661715-e8e0de00-c7e5-11e9-8afd-6b73cd35e21d.jpeg)

### Reproducible Demo

With SDK 34
https://github.com/expo/expo/tree/master/apps/native-component-list

**Comment by cruzach** [comment]
Just tested this on iOS 13 with [this snack](https://snack.expo.io/@charliecruzan/spunky-kiwi) and it seems it's been fixed (either with an update to iOS 13, or with SDK 35), so I'm going to close this.

**Comment by giautm** [comment]
yeah, fixed
