### ISSUE TITLE
File not working offline 

### ISSUE THREAD

**Issue by Mohammadhunan97** [expo/expo#544]
I have a video on my app built with create-react-native-app and I'm using the Video component of expo.io . I am displaying a local video, and on my application this is working when connected to the internet, but when the app is offline the video does not play/work/load.

Here is my project structure:

```
App.js          app.json        node_modules        yarn.lock
App.test.js     images          package.json
README.md       my-app-key.keystore videos
```

Here is the code for the video player component:

```
import React, { Component } from 'react';
import { StyleSheet, Text, View, Image, Button } from 'react-native';
import { Video } from 'expo';

class Player extends Component {
  constructor(props){
    super(props);
  }
  render(){
    return(
     <Video
      source={require('./videos/asthma-1.mp4')} //local video
      rate={1.0}
      volume={1.0}
      muted={false}
      useNativeControls
      resizeMode="cover"
      shouldPlay
      isLooping
      style={{ width: 900, height: 450, position:'relative',left:350,bottom:410 }} />
      )
  }
}
```
What am I doing wrong? Why is the video being delivered online but not offline?

I am using it on an android device btw

Edit: Also, I noticed that the images located in the image folder work both offline and online. Did I structure/name my videos folder incorrectly for that not to load offline?

**Comment by dikaiosune** [comment]
Hi! It looks like you also created a [forum post](https://forums.expo.io/t/video-file-not-working-offline/2598), which I've been trying to help with. I'll close this so we can continue troubleshooting there.
