### ISSUE TITLE
React Navigation problems

### ISSUE THREAD

**Issue by dekm** [expo/expo#545]
I'm running into some issue trying to navigate with React-Navigate when using expo.  This is also related to redux I believe.

My tab bar and side drawer all work as intended but when I try and use props or a state to navigate it wont work.

navigate will come back undefined in the component
const {navigate} = this.props.navigation;

Then if i use a redux nav my AppNavigator never receives the call.
`case 'MEDS_SEARCH':
      return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'SearchMeds'}), state)`

**Comment by dikaiosune** [comment]
Hi! Please look for issues on https://github.com/react-community/react-navigation. If one doesn't exist, please open one there!

**Comment by dekm** [comment]
This isnt an issue with react-navigation its an issue with Expo blocking the props.

**Comment by dikaiosune** [comment]
Sorry, could you elaborate by what you mean by "blocking the props"?

**Comment by dekm** [comment]
If I were not using Expo I could add below In a render function without error.
const {navigate} = this.props.navigation;

I had the same problem with redux where i had to wrap the class like this for it to connect.
@connect( mapStateToProps, {switchDate, setTime, navRoute})
class CalendarSelector extends Component {

My navigator is not a class though so not sure how to work around that.

**Comment by dikaiosune** [comment]
Can you provide a small reproduction of what you're talking about with https://snack.expo.io?

**Comment by dekm** [comment]
I can try and set something up yes.

**Comment by dekm** [comment]
@dikaiosune  Here is a simple example of using the props.navigation and using it's send event in onPress.

https://snack.expo.io/r1279e6uW

Thanks

**Comment by dikaiosune** [comment]
I don't see react-navigation used in that example at all?
