### ISSUE TITLE
[iOS][Audio] Playing sound in background Problem

### ISSUE THREAD

**Issue by onka13** [expo/expo#5456]
### Environment

  Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.0.2

>

### Steps to Reproduce

1- Open app, play sound
2- Lock Phone
3- Stop or pause sound with Music controls buttons
4- Try to play sound with Music controls buttons

Error: 
- code: E_AV_PLAY 
- domain: UMModulesErrorDomain 
- NSLocalizedDescription: This experience is currently in the background, so the audio session could not be activated

I found the related file and comment that line works for me. Now I can play and stop sounds on background on IOS.

File; [https://github.com/expo/expo/blob/master/packages/expo-av/ios/EXAV/EXAV.m#L272](https://github.com/expo/expo/blob/master/packages/expo-av/ios/EXAV/EXAV.m#L272) 

```
  if (_isBackgrounded && ![_kernelAudioSessionManagerDelegate isActiveForModule:self]) {
    //return UMErrorWithMessage(@"This experience is currently in the background, so the audio session could not be activated.");
  }
```

### Sample
```
import { Audio } from "expo-av"
import MusicControl from "react-native-music-control"


Audio.setAudioModeAsync({
	allowsRecordingIOS: false,
	staysActiveInBackground: true,
	interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
	playsInSilentModeIOS: true,
	shouldDuckAndroid: false,
	interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
	playThroughEarpieceAndroid: true
})

MusicControl.resetNowPlaying()
MusicControl.enableControl("play", true)
MusicControl.enableControl("pause", true)
MusicControl.enableControl("stop", true)
MusicControl.enableControl("nextTrack", false)
MusicControl.enableControl("previousTrack", false)
MusicControl.enableControl("changePlaybackPosition", false)
MusicControl.enableControl("setRating", false)
MusicControl.enableControl("volume", false)
MusicControl.enableControl("remoteVolume", false)
MusicControl.enableControl("enableLanguageOption", false)
MusicControl.enableControl("disableLanguageOption", false)
MusicControl.enableControl("closeNotification", true, { when: "always" })

MusicControl.enableBackgroundMode(true)
MusicControl.handleAudioInterruptions(true)
MusicControl.on("play", () => {
	playSound()
})
MusicControl.on("pause", () => {
	stopSound()
})
MusicControl.on("stop", () => {
	stopSound()
})
MusicControl.on("closeNotification", () => {
	stopSound()
})
```

**Comment by onka13** [comment]
@cruzach Thanks for supporting. Sure this is an Expokit project.  "react-native-music-control" is supplying for background process. Not related about this issue. Alternatively we can use "react-native-background-timer" for testing. 

Additionally the app is working on Android.

**Comment by onka13** [comment]
Here is my dep. ;

  ```
  "expo": "^33.0.0",
  "expo-av": "~5.0.2", 
  "expokit": "^33.0.4",
  "react": "16.8.3",
  "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
```

**Comment by cruzach** [comment]
Hey @onka13 , sorry I didn't link this earlier, but [according to the docs](https://docs.expo.io/versions/v34.0.0/introduction/why-not-expo/):
> The SDK doesn't support all types of background code execution (running code when the app is not foregrounded or the device is sleeping). We support background geolocation (including geofencing) and background fetch, **but we do not yet support background audio with the operating-system playback controls** and you cannot handle push notifications in the background. This is a work in progress.

**Comment by onka13** [comment]
@cruzach , sorry for late reply. I've read the docs and got it. So background audio's not supported yet. I'll comment that line manually for temporary solution. 

By the way, I think ios and android have different conditions about this issue. Because of that **android is working well** but ios not.  Could you please check if conditions?


Android;
[https://github.com/expo/expo/blob/master/packages/expo-av/android/src/main/java/expo/modules/av/AVManager.java#L249](https://github.com/expo/expo/blob/master/packages/expo-av/android/src/main/java/expo/modules/av/AVManager.java#L249)
```

    if (mAppIsPaused && !mStaysActiveInBackground) {
      throw new AudioFocusNotAcquiredException("This experience is currently in the background, so audio focus could not be acquired.");
    }
```

IOS;
[https://github.com/expo/expo/blob/master/packages/expo-av/ios/EXAV/EXAV.m#L272](https://github.com/expo/expo/blob/master/packages/expo-av/ios/EXAV/EXAV.m#L272)

```
  if (_isBackgrounded && ![_kernelAudioSessionManagerDelegate isActiveForModule:self]) {
    return UMErrorWithMessage(@"This experience is currently in the background, so the audio session could not be activated.");
  }
```

**Comment by cruzach** [comment]
I was able to get iOS background sound working, although it wasn't entirely clear from the docs as to how. When using `Audio.setAudioModeAsync`, you need to include **all** the keys.

See [this snack](https://snack.expo.io/@charliecruzan/background-audio)
