### ISSUE TITLE
[iOS][Video] prop "onFullscreenUpdate" is not triggered with native control actions

### ISSUE THREAD

**Issue by pierreclr** [expo/expo#5467]
### Environment

Expo CLI 3.0.6 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1

### Steps to Reproduce

Write a Video component with `onFullscreenUpdate={console.log}` prop. Set prop `useNativeControls={true}`. If you call `videoRef.presentFullscreen()`, the onFullscreenUpdate callback is fired. If you enter fullscreen with native controls, it is not. 

### Expected Behavior

onFullscreenUpdate should be always triggered

**Comment by pierreclr** [comment]
Hi there !

Any news on this little fix ?

**Comment by mczernek** [comment]
Will be part of SDK37.
