### ISSUE TITLE
Network request failed android (emulator and device)

### ISSUE THREAD

**Issue by ms4ever7** [expo/expo#5469]
### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v8.9.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: 2.3.1 => 2.3.1
    npmGlobalPackages:
      expo-cli: 3.0.10

Android device and emulator

### Steps to Reproduce

So I'm really new to expo and don't know how all your magic works, and I'm having an error like this: 
```
[Unhandled promise rejection: TypeError: Network request failed]
- node_modules/react-native/Libraries/vendor/core/whatwg-fetch.js:504:29 in onerror
- node_modules/event-target-shim/lib/event-target.js:172:43 in dispatchEvent
- ... 8 more stack frames from framework internals
```

So I'm having this error on both emulator and device build - `TypeError: Network request`
I've found a lot of issues related to problem like this, but the solutions did not really help.

Here is how I'm making request: 
```
const response = await fetch(`${urls.apiBase}/auth/logout`, {
    ...fetchParams,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      Authorization: `bearer ${token}`,
    },
    body: JSON.stringify({}),
  });
```

and here is my `app.json`:
```
{
  "expo": {
    "name": "CommonSpace",
    "description": "CommonSpace is a prototype built by Sidewalk Labs to explore how technology might enable the study of public life. It allows space managers and community groups to study activity in their public spaces in accordance with the Public Life Data Protocol.",
    "githubUrl": "https://github.com/sidewalklabs/commonspace",
    "primaryColor": "#4A90E2",
    "slug": "CommonSpace",
    "privacy": "unlisted",
    "sdkVersion": "32.0.0",
    "scheme": "commonspace",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/AppIcon.png",
    "splash": {
      "image": "./assets/images/CS_LaunchImage.png",
      "resizeMode": "contain"
    },
    "updates": {
      "enabled": false
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "com.commonspace.commonspace",
      "supportsTablet": true,
      "config": {
        "googleMapsApiKey": "GENERATE_A_MAPS_KEY",
        "googleSignIn": {
          "reservedClientId": "GENERATE_A_RESERVEDCLIENTID"
        }
      },
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "Your location is used to show you where you are on a map of your assigned survey zone. Your location is never stored or transmitted off your device."
      }
    },
    "android": {
      "package": "com.commonspace.commonspace",
      "versionCode": 1,
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "CAMERA"
      ],
      "config": {
        "googleMaps": {
          "apiKey": "GENERATE_A_MAPS_KEY"
        },
        "googleSignIn": {
          "apiKey": "GENERATE_AN_AUTH_KEY",
          "certificateHash": "GENERATE_A_CERTIFICATE_HASH"
        }
      }
    },
    "extra": {
      "googleAuthClientId": {
        "expo": {
          "android": "603386649315-vp4revvrcgrcjme51ebuhbkbspl048l9.apps.googleusercontent.com",
          "ios": "603386649315-vp4revvrcgrcjme51ebuhbkbspl048l9.apps.googleusercontent.com"
        },
        "standalone": {
          "android": "GENERATE_AN_AUTH_KEY",
          "ios": "GENERATE_AN_AUTH_KEY"
        },
        "guest": {
          "android": "GENERATE_AN_AUTH_KEY",
          "ios": "GENERATE_AN_AUTH_KEY"
        }
      }
    }
  }
}
```

Also, I know that there is some issue like this - https://github.com/expo/expo/issues/1606
but did not find solution there.

**Comment by ms4ever7** [comment]
did not try on iOS, they need it only on android
earlier I've worked with xCode

so request is making to api, not to localhost, as its caused on both localhost and device with apk build
its Expo @cruzach  client app

**Comment by cruzach** [comment]
I don't think I understand. Could you explain what you mean by "as its caused on both localhost and device with apk build"?

**Comment by ms4ever7** [comment]
Sorry, 
I mean that I was thinking that it may be only local error, 
so I've tried to make apk build to check on real device - but error still exists

**Comment by cruzach** [comment]
Ah okay, understood. What happens if you try to visit your endpoint in the browser?

Also, please share a minimal repro for this. I suggest using any test API endpoint, rather than your own API (just to narrow down the possible root causes)

**Comment by Chasty** [comment]
I'm having the same issue, any solution please.

**Comment by eyeamkd** [comment]
test API works fine, but local server doesn't respond. getting the same error

**Comment by rodriguezmanu** [comment]
+1

**Comment by onlyargon** [comment]
The same issue experiencing. Any fix ??

**Comment by cruzach** [comment]
Still need a repro for this, so if you're having the same issue, please share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by onlyargon** [comment]
@cruzach `try {
      let response = await fetch(
        'http://localhost:3000/api/traffic/get-traffic-conditions'
      );
      try {
        let responseJson = await response.json();
      } catch (error) {
        console.log(error);
        alert(error);
      }
    } catch (error) {
      console.log(error);
      alert(error);
    }`

This is how i try to read the API

**Comment by onlyargon** [comment]
@cruzach Please find sample repo [here ](https://github.com/onlyargon/react-network-issue-repo)

**Comment by yatagan** [comment]
I have the same issue both on Android device and iOS Simulator, steps to reproduce: https://docs.expo.io/versions/latest/guides/using-clojurescript/

**Comment by ThiagoLAMF** [comment]
> I have the same issue both on Android device and iOS Simulator, steps to reproduce: https://docs.expo.io/versions/latest/guides/using-clojurescript/

Try this: https://github.com/seantempesta/expo-cljs-template/issues/84

**Comment by yatagan** [comment]
> Try this: [seantempesta/expo-cljs-template#84](https://github.com/seantempesta/expo-cljs-template/issues/84)

Commented

**Comment by onlyargon** [comment]
This is fixed for me when I deploy endpoint with https

**Comment by cruzach** [comment]
@ms4ever7 can you confirm @onlyargon's solution?

**Comment by ms4ever7** [comment]
Thx, @ThiagoLAMF , worked for me

**Comment by nfabacus** [comment]
yes, I also have the same issue only for android simulator.  web and ios simulator work fine.  For the time being for android simulator, I am using ngrok to access localhost via https.

**Comment by yemialpha** [comment]
please is there a solution to this problem yet?

**Comment by obie3** [comment]
Please I'm having similar issue, my app works well on iOS and postman but always throws a network error on android further debugging with adb and axios showed

 { err: 
    { [Error: Network Error]
      config: 
     { url: 'https://xxx.yyy.zzz:7071/',
       method: 'post',
         data: '{"id":"12345678910"}',
         headers: [Object],
       transformRequest: [Object],
         transformResponse: [Object],
         timeout: 0,
         adapter: [Function: xhrAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         maxBodyLength: -1,
       validateStatus: [Function: validateStatus],
       body: '{"id":"12345678910"}',
      request: 
        { UNSENT: 0,
         OPENED: 1,
        HEADERS_RECEIVED: 2,
        LOADING: 3,
         DONE: 4,
        readyState: 4,
         status: 0,
         timeout: 0,
        withCredentials: true,
         upload: {},
         _aborted: false,
       _hasError: true,
        _method: 'POST',
        _response: 'Unable to resolve host "xxx.yyy.zzz": No address associated with hostname',
      _url: 'https://xxx.yyy.zzz:7071/',
        _timedOut: false,
         _trackingName: 'unknown',
       _incrementalEvents: false,
       responseHeaders: undefined,
         _requestId: null,
        _cachedResponse: undefined,
        _headers: [Object],
         _responseType: '',
         _sent: true,
         _lowerCaseResponseHeaders: {},
         _subscriptions: [] 
     },
      response: undefined,
      isAxiosError: true,
     toJSON: [Function: toJSON],
     line: 178238,
      column: 26,
      sourceURL: 'http://192.168.0.16:19001/node_modules/expo/AppEntry.bund 

here is a screenshot of my environment
![Screen Shot 2020-09-16 at 9 42 49 AM](https://user-images.githubusercontent.com/18898840/93319322-a67eaa80-f807-11ea-8e0f-aae8c208d9da.png)

**Comment by xgenem** [comment]
I am currently facing the same issue. I'm surprised this wasn't resolved. Hope someone from expo can help.

**Comment by brentvatne** [comment]
please post a new issue with a [mcve](https://stackoverflow.com/help/mcve) if you are experiencing some problem that you believe to be a bug in expo tools.
