### ISSUE TITLE
Notifications.getExpoPushTokenAsync() hangs

### ISSUE THREAD

**Issue by khuang-citylift** [expo/expo#5473]
### Environment

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.1 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.0.10

### Steps to Reproduce

I followed the expo push notifications guide here:
https://docs.expo.io/versions/latest/guides/push-notifications/

### Expected Behavior

A push token should be returned from:
`let token = await Notifications.getExpoPushTokenAsync();`

### Actual Behavior

Inside of async function registerForPushNotificationsAysnc():

```
	const { status: existingStatus } = await Permissions.getAsync(
    	Permissions.NOTIFICATIONS
  	);
	
	console.log("The current permission status for push notification is: " + existingStatus);
  	let finalStatus = existingStatus;

  	// only ask if permissions have not already been determined, because
  	// iOS won't necessarily prompt the user a second time.
  	if (existingStatus != 'granted') {
		// Android remote notification permissions are granted during the app
		// install, so this will only ask on iOS
		console.log("Requesting user to grant permission for Push Notifications.");
		const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
		finalStatus = status;
  	}

  	// Stop here if the user did not grant permissions
  	if (finalStatus != 'granted') {
		console.log("User did not grant permissions for push notifications.");
		return;
  	}
	console.log("Right before getting an access token."); /* Does get here */
	
  	// Get the token that uniquely identifies this device
  	let token = await Notifications.getExpoPushTokenAsync();
  	console.log( token); /* Never gets here */
```

I'd like to note everything was perfectly before I upgraded expo from 32 to 34 and react native from 0.57.x to 0.59.8

**Comment by cruzach** [comment]
Could you share a full snack to reproduce this issue? We have an [example snack](https://snack.expo.io/@charliecruzan/pushnotifications34) that works correctly, if you want to take a look and see where your code might be different.

Two additional questions:
- does it hang only on iOS or Android? or is it both?
- does this happen in standalone apps or in the Expo Client?

**Comment by khuang-citylift** [comment]
I am not sure why but the snack page is not accepting several packages of mine in package.json, including expo 34.0.1, react 16.8.3, and sdk 34.0.0. 

1. It hangs on both iOS and Android
2. It happens using the Expo Client

**Comment by cruzach** [comment]
not sure what you mean about the snack page. The one I linked doesn't work for you?

**Comment by khuang-citylift** [comment]
The one you linked does work. I tried replacing package.json with mine but it throws a myriad of errors saying it cannot resolve expo 34.0.1, react 16.8.3, etc. These packages work fine with my expo build.

Also, my registerForPushNotificationsAsync() is verbatum with the one in the snack you linked except my registerForPushNotificationsAsync() is outside of the class. Putting it inside of the class makes the 
await Permissions.getAsync(...); hang as well.

**Comment by cruzach** [comment]
(You shouldn't need to update package.json for your snack, so I suggest trying without modifying that file. If the snack still doesn't work, just share a repo)

Since this popped up after upgrading to SDK 34, can you make sure you've updated your import syntax to how it is displayed in the docs? It's changed since SDK 32. You should also install your expo modules individually with `expo install [package-name]`. This is all in the [SDK 34 release notes](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319)

**Comment by khuang-citylift** [comment]
Ok, let's revisit the snack or repo sharing option if we still need to but I think you are right about the imports.

Per the documentation:
> For example, for the FileSystem module, you should run expo install expo-file-system and use import * as FileSystem from 'expo-file-system';.

I tried to to run : `expo install Notifications` but it gives an error saying I have a syntax error in my app.json. However, I am pretty sure there is no error in my app.json because it has remained unchanged prior to my change from SDK 32 to SDK 34.

app.json:

{ 
 "expo": {
 ...
    "notifications": {
        "icon": "./assets/pushIcon96x96.png",
     }
  }
}

**Comment by cruzach** [comment]
You don't need to run it for Notifications, it would say so in the docs for each API. [notifications docs here](https://docs.expo.io/versions/latest/sdk/notifications/)

However, you are using [expo-permissions](https://docs.expo.io/versions/latest/sdk/permissions/)

**Comment by khuang-citylift** [comment]
Charlie,

Here is the snack. I just quickly removed most of the unnecessary code and private info.
https://snack.expo.io/rkUDVtESB

**Comment by khuang-citylift** [comment]
Hey Charlie - I figured it out. I ran "expo install expo-permissions" but I did not run "expo install expo". Do you know why I would have to re-install expo manually? I thought "npm install" would have managed this for me?

**Comment by cruzach** [comment]
My guess is you missed updating your `expo` dependency in your package.json file? Not really sure. 

`expo install` is just a wrapper around `npm install`/`yarn add`
