### ISSUE TITLE
How do expo knows from where load new js bundles?

### ISSUE THREAD

**Issue by volodyad** [expo/expo#548]
According to docs expo automatically loads new js bundles 
Note: Updates are handled differently on iOS and Android. On Android, updates are downloaded in the background. This means that the first time a user opens your app after an update they will get the old version while the new version is downloaded in the background. The second time they open the app they’ll get the new version. On iOS, updates are downloaded synchronously, so users will get the new version the first time they open your app after an update.

The only thing I cannot understand - how standalone app bundle connected to expo account? Also I want setup ci from qa and productin build how can i handle this

**Comment by terribleben** [comment]
Standalone apps are connected to a published Expo url such as @your-name/your-app. That's how they know which bundle to fetch. Check out [project lifecycle](https://docs.expo.io/versions/latest/introduction/project-lifecycle.html) for an overview.

If you want separate staging/production versions of your app, the best strategy for now is to maintain two app slugs, e.g. your-app and your-app-staging. Later this year we're hoping to build more formalized release channels.

Closing this as we try to limit this venue to bug reports - feel free to let me know if you're blocked, or follow up on the [forums](https://forums.expo.io/)!
