### ISSUE TITLE
AppAuth on Android breaks when switching app during AppAuth.authAsync

### ISSUE THREAD

**Issue by ivopatty** [expo/expo#5488]
### Environment

```  Expo CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.8.23 
      @types/react-native: ^0.57.65 => 0.57.65 
      @types/react-navigation: ^3.0.7 => 3.0.7 
      expo: 34.0.4 => 34.0.4 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.8
```
Affects:
- Android (Expo Client)
- Android (Simulator, Standalone)
- Galaxy S8 (Standalone)

Versions:
expo-app-auth: 6.0.0 (Snack is 5.0.0)

### Steps to Reproduce

In an app that uses AppAuth to authenticate the user (we are using Auth0):

1. Open app
2. Click the Log In button that triggers `AppAuth.authAsync()`
3. The web browser opens
4. Press the Android Home button
5. Re-open the app from the icon on the home screen (Standalone) or the Snack in the Expo client
6. The app is now back on the screen with the Log In button
7. The Log In button stopped working and triggers the exception `Error: ExpoAppAuth.Get Auth: Cannot start a new task while another task is currently in progress` and user cannot return to the browser window.

### Expected Behavior

Two possible expected behaviors:

1. The user is returned to the active browser sessions when clicking the app-icon on Android
2. When opening the app again the AppAuth session is canceled and the user can use the button to start a new Auth session.

### Actual Behavior

Without any user feedback present, the user is presented with a non-functioning button.

### Reproducible Demo

This snack reproduces the issue: https://snack.expo.io/@platformco/appauth-android-bug

**Comment by derekstavis** [comment]
I confirm this issue currently happens on Android. It looks like the authentication screen open in a separate app instead of inside the same one, hence when you switch back to the app it's unable to continue the authentication. Perhaps opening the web auth window on the same navigation stack would help?

**Comment by deathemperor** [comment]
I can confirm this happens when using `expo-google-app-auth` too. Not 100% of the time but sometimes.

**Comment by NeOMakinG** [comment]
I got this error too, can't find the behavior to generate it

**Comment by jtibrewal09** [comment]
facing same issue in expo-google-app-auth, expo facebook is working perfectly.

**Comment by EquesMedia** [comment]
I have the same issue with `expo-google-app-auth` on Android. Anyone found a solution?

**Comment by EvanBacon** [comment]
The issue shouldn't be happening in `expo-facebook`.

App Auth uses a custom implementation of the `expo-web-browser` functionality which has had a lot of reported functionality issues across various different Android vendors/versions. The custom system works by storing a local value to internally redirect to when the authentication finishes in Expo Go (breaks when switching between local apps). Our solution has been to create a version of AppAuth which is entirely JS (`expo-auth-session`) and relies on `expo-web-browser` and `expo-linking` for the redirect functionality, then drop all custom redirect logic.

This solution has been available for about a year now and we will start sunsetting `expo-app-auth`, and `expo-google-app-auth` in favor of `expo-auth-session`. Here is a small migration guide: [`expo-app-auth` -> `expo-auth-session`](https://expo.fyi/expo-app-auth-deprecated).
