### ISSUE TITLE
AsyncStorage not working on background task

### ISSUE THREAD

**Issue by niv-breez** [expo/expo#5489]
Hi.
I created a background task using expo for the location updates like expo described here:
[https://docs.expo.io/versions/latest/sdk/location/](https://docs.expo.io/versions/latest/sdk/location/
)
I want to send the server the user location so I need to read the access token from the device storage.

Something like this:

```
defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  const accessToken = await AsyncStorage.getItem('accessToken')
  fetch(SERVER_URL + '/' + 'update_user_location', {
        method: 'POST',
        headers: {
            Authorization: 'Bearer ' + accessToken
        },
        body: data
   }
})
```

The problem is that  `await AsyncStorage.getItem('accessToken')` returns null if the task runs in killed mode, when the app is open/background it works fine!

I also tried to replace the AsyncStorage with using the FileSystem (write and read the accessToken to a file) and it also didn't worked it wrote for me something like "File .... could not be found", and also try to use SQLite of expo and also didn't help, it wrote for me "table items didn't found" while when the app is running it works fine.

I start thinking that when the task runs in killed mode it doesn't look for the right path or it doesn't have permissions to read from the device storage.

What am I missing ?

thanks.

>

**Comment by cruzach** [comment]
Hi! So atm the Expo SDK doesn't support all types of background code execution. We support both [background fetch](https://docs.expo.io/versions/latest/sdk/background-fetch/) and some [background location](https://docs.expo.io/versions/latest/sdk/location/#background-location), but I'm not sure if its possible with the API's you're trying to use

**Comment by alxyuu** [comment]
are there any other options outside of asyncstorage for accessing data within a task when in a killed state, like passing data directly to the task?

**Comment by niv-breez** [comment]
There is an option to pass data directly to the task but in order to pass the access_token it should be fetch first from the device storage which is impossible because fetching from device storage is an async call and the task should be define in the global scope according to Expo.

**Comment by Szymon20000** [comment]
I couldn't reproduce this issue on iOS.  
Is your app ejected? 
Is it Android or iOS?
I think your arrow function should be async.

**Comment by niv-breez** [comment]
Not ejected.
It both for IOS and Android.

I tried also with async function and it still doesn't work.

If it works for you please share your code and how you run it.
Thanks.

**Comment by LucasBSC** [comment]
Hi @niv-breez, check if this snippet can help you out... I am using `BackgroundFetch` just to execute some code periodically alongside with `TaskManager` referencing a static method that returns me `AsyncStorage` data inside a class component. It should work normally in background mode

```javascript
export default class Main extends React.Component {

  static getData = async () => {
    const data = await AsyncStorage.getItem("My data");
    return JSON.parse(data);
  };

   componentDidMount() {

      BackgroundFetch.registerTaskAsync("taskExample", {
        minimumInterval: 2
      });
  }

  state = {
    ...
   };


}


TaskManager.defineTask("taskExample", async ({ data, error }) => {
  if (error) {
    console.log(error.message);
    return;
  }
  if (data) {
    const dataFetch = await Main.getData();
    console.log("My data", dataFetch);
  }
});
```

**Comment by niv-breez** [comment]
Hi @LucasBSC, 
Thanks for the snippet,
Did you and @Szymon20000 try it only with expo client or checked it also as a standalone app?
Cause I think checking via expo client always work because when your app is killed the expo client still in foreground.

**Comment by LucasBSC** [comment]
@niv-breez tried with expo client only because I've just printed something on console to test (My data). Notice on this snippet you must previously have something saved on `AsyncStorage` with this "My data" key. Gotta check anyway this expo client issue

**Comment by niv-breez** [comment]
Yes, for sure I have tested with saved/persisted value. When the app was open everything worked.
Please verify on standalone app without expo client and let us know.

Thanks @LucasBSC

**Comment by AlexBungiu** [comment]
Any updates? I'm having the same problem, need the access token in expo's Location.startLocationUpdatesAsync, anyone managed to find a workaround?

**Comment by kiyopikko** [comment]
When I use [SecureStore](https://docs.expo.io/versions/latest/sdk/securestore/) like the code below, it works fine on standalone app via TestFlight. My app is built on managed workflow.

```jsx
TaskManager.defineTask(BACKGROUND_GEOLOCATION_TASK, async ({ data, error }) => {
  if (error) {
    return;
  }
  try {
    const userId = await SecureStore.getItemAsync("userId");
    if (userId !== null) {
      fetch(
        "https://xxxxxxxxxxxxxxxxxxxxx.net/saveLocation?userId=" +
          userId
      )
        .then((response) => response.json())
        .then((responseJson) => {
          console.log(responseJson);
        })
        .catch((error) => {
          console.error(error);
        });
    }
  } catch (e) {
    // error reading value
  }
});

export default function App() {
  const isLocationPermitted = useRef(false);

  useEffect(() => {
    async function startLocationUpdatesAsync() {
      isLocationPermitted.current = await confirmLocationPermission();
      if (isLocationPermitted.current) {
        await Location.startLocationUpdatesAsync(BACKGROUND_GEOLOCATION_TASK, {
          deferredUpdatesInterval: 5000,
          showsBackgroundLocationIndicator: true,
        });
      }
      try {
        await SecureStore.setItemAsync("userId", "hogehoge");
      } catch (e) {
        // saving error
      }
    }
    startLocationUpdatesAsync();
  }, []);

  return (
      <SafeAreaProvider>
        <Navigation />
        <StatusBar />
      </SafeAreaProvider>
    );
}
```

I did the step below.

1. Open the app, `BACKGROUND_GEOLOCATION_TASK` starts
1. Terminate the app (location tracking goes OFF)
1. Turn my iPhone sleep mode.
1. Ride my bicycle and move 500m in order to occur [significant location update](https://forums.expo.io/t/locationupdates-geofencing-not-running-in-background/17960/23) (location tracking goes ON)
1. `BACKGROUND_GEOLOCATION_TASK` works fine
