### ISSUE TITLE
[expo-av] Sound is delayed.

### ISSUE THREAD

**Issue by FullMoon04** [expo/expo#5492]
I want to play a sound immediately when a button is pressed. However, the sound is actually delayed.
Here is a code sample:
```
import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Button,
} from 'react-native';
import {Audio} from 'expo-av';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.press = this.press.bind(this);
  }

  press() {
    this.playSound();
  }

  async playSound() {
    const soundObject = new Audio.Sound();
    try {
      await soundObject.loadAsync(require('./assets/sounds/sample.mp3'));
      await soundObject.playAsync();
    } catch (error) {
      alert('An error occurred!')
    }
  }

  render() {
    return (
      <TouchableOpacity 
        style={styles.container}
        onPress={this.press}
      >
        <Text>Play</Text>
      </TouchableOpacity>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

What can I do? Thank you for your help.

**Comment by cruzach** [comment]
You'll need to share an actual [snack link](https://snack.expo.io/), since your code includes a reference to an mp3 asset

Is the delay only on one platform, or both? I would also try and see if the delay is happening from `loadAsync` or `playAsync`

**Comment by FullMoon04** [comment]
When I tried snack link, the sound was not delayed. There may be a cause in my development environment. The platform is iOS. Check again and ask again if there was a problem. Thank you for your help.
