### ISSUE TITLE
UMReactNativeAdapter javaScriptContextRef failing in 0.61

### ISSUE THREAD

**Issue by birkir** [expo/expo#5493]
## 🐛 Bug Report

https://github.com/expo/expo/blob/87558b0d6314311a34c9a3a55b68b9a6ac831d7f/packages/%40unimodules/react-native-adapter/ios/UMReactNativeAdapter/Services/UMReactNativeAdapter.m#L174-L178

The ContextRef extractor is now failing in React Native @ 0.61.0-rc.0

### Environment

- Platform: iOS
- React Native 0.61
- Using the SDK manually

**Comment by wkozyra95** [comment]
Hi thanks for reporting that. We were expecting that the future version of react-native might break this workaround. 
To do this properly we would need to rewrite expo-gl to use JSI instead of JSC(it's planed together with adding Hermes support on android, probably sdk36). I'll try to look for a similar workaround for the new version, but I'll probably have a chance to look at this at the end of next week

Is `_bridge.runtime` has some value or is it null?

**Comment by birkir** [comment]
Sounds good, I just wanted to surface the issue, don't expect to figure anything out just yet, also, many changes are coming to react-native 61 and 62 so I think waiting a bit is good.

The `runtime` value is null, but I tried to call it manually later with success. So it looks like it's not initialized (or set) at the time of access, but later, somehow.

---

This is how realm is doing it https://github.com/realm/realm-js/blob/master/react-native/ios/RealmReact/RealmReact.mm#L331-L335 (but its in Objective-C++).

I implemented this method in a separate ObjC++ class, but it was also failing. So it has something to do with timing for sure.

**Comment by wkozyra95** [comment]
ok thanks for investigating

realm solution is actually the same as ours they create fake class/struct with virtual methods table and cast to it and we just access directly by offset.

**Comment by birkir** [comment]
Ok, that confirms my suspicion on how that particular casting works. TIL.

They do, however, a timeout until the previous JS thread is finished (https://github.com/realm/realm-js/blob/master/react-native/ios/RealmReact/RealmReact.mm#L282-L294) and also wrap it in `dispatchBlock`. That could be a reason why it works for realm.

**Comment by ide** [comment]
We are planning to write things to use JSI to address this, likely with the next major SDK release but will need to actually see how that work goes.

**Comment by chalarlie** [comment]
I am getting the same crash on SDK 35 with RN 59.10. Is there any plan to fix this?

**Comment by ide** [comment]
This issue has all the updates related to fixing this problem. If there are new updates, they will show up here.

**Comment by tsapeta** [comment]
Hi, just wanted to send you a small update that my PR #6381 is going to slightly change the behavior you're experiencing but it isn't the proper solution for this bug yet. This change just prevents against application crashes when `_bridge.runtime` is not available, but then `expo-gl` will think the context was initialized in the remote JS context (with Chrome debugging enabled) which I guess isn't true in your case.
Hopefully I'll find some time to fix this correctly soon.

**Comment by wkozyra95** [comment]
it was fixed in later versions of react-native, (first, non rc version should be working correctly)
