### ISSUE TITLE
Cherry pick iOS/Android fixes from upstream

### ISSUE THREAD

**Issue by esamelson** [expo/expo#5494]
https://github.com/facebook/react-native/commit/db5994980df136c5cce6cd90348b4bf18180562f
https://github.com/facebook/react-native/commit/46bdb4161c84b33f1d0612e9c7cdd824462a31fd (see https://github.com/facebook/react-native/issues/25182)
We should either cherry-pick these or make an intentional decision not to

**Comment by brentvatne** [comment]
Related: https://github.com/expo/expo/issues/5532

**Comment by QuintonC** [comment]
Talked with @cruzach in chat about this, but it looks like https://github.com/facebook/react-native/issues/25138 has more information in it than #25182.

Worth mentioning... SDK32 worked really well with Xcode 11 and iOS 13.

**Comment by esamelson** [comment]
done in https://github.com/expo/expo/commit/643b0726d90d5c74edeb66021b9dba7134c67eda
