### ISSUE TITLE
Users are getting `The operation couldn’t be completed. (EXNetwork error 53.)` when app updates

### ISSUE THREAD

**Issue by holgersindbaek** [expo/expo#5496]
## 🐛 Bug Report

Some of my users are getting the following error:

`The operation couldn’t be completed. (EXNetwork error 53.)`

![Screenshot 2019-08-29 at 20 34 27](https://user-images.githubusercontent.com/698979/63966860-8107ed00-ca9c-11e9-8fe8-a1904a994d6a.jpg)

It seems to be happening when the app is either trying to update in the background or when the app is trying to update when it starts. I'm not sure which. It seems to be only happening on a device (not simulator).

From what I can tell, it doesn't cause any crash or anything like that, but Sentry still catches the bug.

### Environment

My app is running `expo 34.0.3` and is detached.

### Steps to Reproduce

Publish a new Expo version of the app, open the app and download the new version in the background, close and open the app again, which will force a restart so the new version is applied.

### Expected Behavior

No bug report being sent to Sentry.

### Actual Behavior

Bug report being is being sent to Sentry.

**Comment by cruzach** [comment]
Since the app isn't crashing- does it just hang, or does it update successfully?

**Comment by holgersindbaek** [comment]
It seems to be updating successfully. It hangs for a while when the new version loads, but I think that's normal, and then it starts.

I'm only on iOS for now.

**Comment by Rojdestv** [comment]
im having this issue as well, but i dont have sentry. It just doesnt load on the actual device and just shows the same warning after some hanging=(

**Comment by cruzach** [comment]
@Rojdestv it seems like in @holgersindbaek 's case the app still downloads the update successfully, but Sentry captures this error. Could you explain exactly what's happening in your case? Where does it show the warning?

**Comment by expjess** [comment]
Hi @Rojdestv - we haven't heard from you for awhile so maybe you solved this problem? If not, can you please open a new issue with more details and a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so we can help figure out what's going? Thanks!
