### ISSUE TITLE
Dokcernize expo program

### ISSUE THREAD

**Issue by JunyuanZheng** [expo/expo#550]
Hi all,

First of all, thanks for the great tool, it's amazing!

Right now, I am trying to dockernize my development environment so I can share with my teammates. However, I am getting this error:

```
[exp] Logs for your project will appear below. Press Ctrl+C to exit.
[exp] Dependency graph loaded.
[exp] Warning: You are using npm version 5.3.0. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
[exp] Launching Dev Tools...
[exp] Google Chrome exited with error: { Error: spawn google-chrome ENOENT
[exp]     at _errnoException (util.js:1041:11)
[exp]     at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
[exp]     at onErrorNT (internal/child_process.js:374:16)
[exp]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[exp]     at process._tickCallback (internal/process/next_tick.js:180:9)
[exp]   code: 'ENOENT',
[exp]   errno: 'ENOENT',
[exp]   syscall: 'spawn google-chrome',
[exp]   path: 'google-chrome',
[exp]   spawnargs: [ 'http://localhost:19001/debugger-ui' ] }
[exp] Finished building JavaScript bundle in 31317ms.
```

The dockerfile I am using is:
```
# Set the base image to Ubuntu
FROM ubuntu:trusty

# File Author / Maintainer
MAINTAINER UBC / Microsoft

# Install Node.js and other dependencies
RUN apt-get update && \
    apt-get -y install curl && \
    apt-get -y install apt-transport-https && \
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

# Install Yarn
RUN sudo apt-get update && \
    sudo apt-get install -y nodejs && \
    sudo apt-get install -y yarn


# Install EXP
RUN yarn global add exp

# Set work directory
RUN mkdir -p /app
WORKDIR /app

EXPOSE 19001

CMD exp login --username $EXP_USERNAME --password $EXP_PASSWORD && \
    yarn install && \
    exp start
```

Can someone give me some suggestion?

**Comment by JunyuanZheng** [comment]
At the same time, I got this error on from my iPhone:

![img_0950](https://user-images.githubusercontent.com/9393110/29733032-2da672a6-89a0-11e7-87a6-95d59671a8fd.PNG)

**Comment by ide** [comment]
`exp` works in a Docker container for CI but we haven't really tried to use it for development. I suspect you might be better off creating VM images (or AMIs for AWS, or the equivalent for other cloud hosts). With Docker, your Docker container would need to include Chrome, or you'd need to submit a PR upstream to React Native that somehow lets it talk to Chrome outside of the container.

**Comment by JunyuanZheng** [comment]
Ok, so basically I need to find install the chrome inside docker, and is there any way I can change the server port number from 19000 to something else?

**Comment by ide** [comment]
You can create a file called .exprc in your project root, which is a JSON file. You can add a field called `manifestPort` which sets the port of the server that serves the Expo project manifest (this is 19000 by default if it is free).

In app.json you can specify:
```json
{
  "expo": {
    "packagerOpts": {
      "port": <port>
    }
  }
}
```

**Comment by JunyuanZheng** [comment]
Thank you so much!
