### ISSUE TITLE
iOS standalone launches to blank screen on first launch after installation

### ISSUE THREAD

**Issue by zilahir** [expo/expo#5506]
### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.0.9 => 3.12.0
    npmGlobalPackages:
      expo-cli: 3.0.10

Standalone – ios
### Steps to Reproduce

I am trying to release an app to the apple app store. By building it with using the `simulator` flag, downloading, and installing the app on my simulator the *first* launch is always ends up with a blank white screen. Then closing the app, launching it again makes it work. The apple rejecting it every time, with the message > app launches to blank white screen. 

The problem is not happening on android build, that version already has been released. I am struggling with this for weeks now. 

Any idea how to solve this?

**Comment by cruzach** [comment]
Could you run this locally in production mode, that might surface the fatal error causing this

Just run `expo start --no-dev --minify`

**Comment by zilahir** [comment]
@cruzach thanks for your reply. 

I've tried it, and it's work on the simulator by starting it with `expo start --no-dev --minify`. It also works with just `expo start`

By building the app with `expo build:ios -t simulator` and then downloading, unzipping, and then installing the problem still persist, but as i stated above, only for the first launch. I close the app, launching again, and then everything works. 

During the previous days, i have managed to dig a bit deeper. The `initialScreen` i am using, using `react-native-maps` package (`"react-native-maps": "^0.25.0",`), so definitely that causing the issue. 

If i choose some dummy screen for `initialScreen` and then navigating to the screen which using the `react-native-maps` everything works even for first launch.

**Comment by cruzach** [comment]
Have you configured your app [according to these instructions](https://docs.expo.io/versions/latest/sdk/map-view/#configuration) for `MapView`?

**Comment by zilahir** [comment]
@cruzach Yes, as i wrote, the maps are working, until they are not on the `initialScreen` where I want to use it. All the api and credential settings are correct in my application.

**Comment by cruzach** [comment]
does the issue persist if you downgrade `react-native-maps`? The recommended version for SDK 34 is `@~0.24.0`, but you're on SDK 33 so running `expo install react-native-maps` should automatically install the best version for you

**Comment by zilahir** [comment]
sorry for the late answer @cruzach , still having this issue. 

i have downgraded it to `"react-native-maps": "^0.24.2", bult the app, downloaded,  unzipped, and installed,  the problem still happening unfortunately. 

Launching the app, and only . white blank screen happening. 

Closing it, launching it again, and it works.

**Comment by cruzach** [comment]
Could you try getting the [device logs](https://docs.expo.io/versions/latest/workflow/logging/#view-logs-for-an-ios-simulator)? Without being able to repro it, it's tough to deduce the root cause of the crash

**Comment by zilahir** [comment]
@cruzach sure thing, here is the `system log`. 

1. opened system log
2. cleared it
3. installed my app
4. opened it
5. blank white screen instead of map view 

the log itself

[devicelog.txt](https://github.com/expo/expo/files/3672965/devicelog.txt)

**Comment by cruzach** [comment]
Hm yeah not too much from those logs, really not sure what's going on here. Could you share a repro with me so I can see this on my end? Also ooc, does this work correctly as an Android standalone app?

**Comment by zilahir** [comment]
No, as an Android standalone app, it works just as it should.  I'll try to create a repo for you. Thanks!

**Comment by zilahir** [comment]
@cruzach i have made a forked repo from my project, set it private, since it's an ongoing project, and added you as a [collaborator](https://github.com/zilahir/react-native-maps-bug-repro).

Thanks for taking another look on this!

**Comment by cruzach** [comment]
Wasn't able to install dependencies, `npm install` and `yarn` both error'd out 😦

**Comment by zilahir** [comment]
@cruzach please use `npm` and version `node/10.16.0` i just installed everything like 30 mins ago and tested the project, it should work. :(

**Comment by zilahir** [comment]
@cruzach anything new? have you managed to install the dependencies?
