### ISSUE TITLE
Hot reaload on Android Device

### ISSUE THREAD

**Issue by phenrigomes** [expo/expo#551]
I could not open the developer menu on Android device. I tried all forms following the docs, but I could not. Is there some problem with Android? I only see three buttons on the blue bar on Android. How can I open the developer menu, do I need to set a property on config, anything?

**Comment by skevy** [comment]
Are you using a simulator or a real device?

If it's a real device -- shake to open the dev menu.

If it's the simulator (specifically, Genymotion), press "command + m" (or "ctrl + m" on windows/linux).

**Comment by tahagit** [comment]
i have this question too! how to solve it?
