### ISSUE TITLE
Classnames as mechanism for integration testing, nested styles

### ISSUE THREAD

**Issue by stephenhandley** [expo/expo#5510]
Given that expo is now supporting a web target, I'm wondering whether it would be worthwhile adding support for classnames in components to provide addressing that would accomplish a couple use cases.

1) Integration testing
Using [WebDriver](https://webdriver.io) and accessing components in the web runtime via [selectors](https://webdriver.io/docs/selectors.html) would be preferable to using something like [Cavy](https://cavy.app) that requires explicit coupling via [ref props](https://cavy.app/docs/getting-started/hooking-up-components).

2) Using [styled-components](https://www.styled-components.com/) with nested (sass-style) declarations
Rather than having to define a number of dedicated top level styled components to attach styles to a hierarchy within a given component, when using styled-components on web it can be more convenient to use [selectors and nesting](https://www.styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting) to address subcomponents in a single configurable style for the entire component.

**Comment by cruzach** [comment]
For integration testing- you can use the [`testId`](https://facebook.github.io/react-native/docs/view.html#testid) prop

**Comment by FiberJW** [comment]
This seems to be resolved, so I'll close this for now. If you have any further related problems, please open another issue. Thanks :)
