### ISSUE TITLE
DEVELOPMENT_URL in Ejected App

### ISSUE THREAD

**Issue by nabeel-s** [expo/expo#5512]
What should go in DEVELOPMENT_URL in file DetachBuildConstants.java after ejecting?

It is blank by default and this results in an error when running.

**Comment by cruzach** [comment]
The Android project *should* automatically request your `DEVELOPMENT_URL` from expo-cli

Are you running the js project locally via `expo start`?

**Comment by nabeel-s** [comment]
@cruzach, yes I'm running the project locally with `expo start`
The app crashes on opening with following error:

**Comment by cruzach** [comment]
Can you provide your SDK version, and your `expo-cli` version? (run `expo diagnostics` and paste the output here)

Is this reproducible on a blank `expo init` project? It's best to follow the issue template we provide when submitting a bug report

**Comment by nabeel-s** [comment]
```
 Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
```

@cruzach, the SDK version is 34. The issue is reproducible on a blank expo init project.

**Comment by nabeel-s** [comment]
Updating `expo-cli` to the latest version 3.0.10 did not solve this issue.

**Comment by cruzach** [comment]
I just tried on a brand new `expo init` project on SDK 34 and was not able to see this issue

Was the blank project you reproduced this on SDK 34?

**Comment by nabeel-s** [comment]
Yes, it is on SDK 34. Please see screenshot: 

![](https://i.snipboard.io/SaC12x.jpg)

Are you running `expo start` on Tunnel, LAN or Local?

To be clear, this issue occurs when running from Android Studio, not using the Expo client.

**Comment by cruzach** [comment]
I'm running `expo start` on LAN (default and suggested)

Yes, I'm doing the same. Following the exact steps [here](https://docs.expo.io/versions/latest/expokit/expokit/), `Android Studio: 3.5`

Maybe this is an issue bc you don't have `watchman` installed?

**Comment by nabeel-s** [comment]
I'm using Windows and `watchman` doesn't seem to be available for Windows here (the download link is broken): https://facebook.github.io/watchman/docs/install.html

**Comment by nabeel-s** [comment]
I'm still having this issue in Android Studio version 3.5.1.

Previously, entering the published URL in file DetachBuildConstants.java was a workaround to running the app:

`public static final String DEVELOPMENT_URL = "(Published URL here)";`

However, even this does not work anymore and shows a constant spinning/loading sign on a white background.

**Comment by nabeel-s** [comment]
Has anyone been able to reproduce this issue? It always occurs for me so I'm not able to test any debug builds from Android Studio.

**Comment by cruzach** [comment]
I still haven't been able to repro this 🙁 

Keeping my `DEVELOPMENT_URL` allows me to run `expo start` and run the project, even from a blank `expo init` and `expo eject` project

**Comment by nabeel-s** [comment]
Can you please explain what you mean by 'Keeping my DEVELOPMENT_URL'?

Mine is always blank like this: ""
It is not auto-generated. What does yours have?

**Comment by nabeel-s** [comment]
I moved to bare workflow from Expokit and this still occurs.

**Comment by nabeel-s** [comment]
How can I disable the local development URL and instead use the published URL in development too?

**Comment by nabeel-s** [comment]
Can anyone else confirm if the same issue occurs for them? It occurs for me on a new expo init project too.

**Comment by nabeel-s** [comment]
After ejecting to bare workflow, I can use `react-native run-android` to run the project. I no longer require the above error fixed although it was unsolved for me in the Expokit project.

**Comment by cksiow** [comment]
quick sure it is a bug. once you change the code
  @Override
  public String developmentUrl() {
	  //expa70516686da34df28a2f118559a6d8e4://192.168.0.102:19000
	  //DetachBuildConstants.DEVELOPMENT_URL
    return "expa70516686da34df28a2f118559a6d8e4://192.168.0.102:19000";
  }
it will work like charm....

**Comment by cruzach** [comment]
That constant is filled in once you run `expo start` or `expo publish`, it is meant to be blank, and is autogenerated (so it should not be manually rewritten). We are pushing the bare workflow as our suggested route if you want to control/change native code.

**Comment by saidhappy010** [comment]
@nabeel-s 
would you have found the solution for this problem?
thanks

**Comment by cksiow** [comment]
@nabeel-s just quick answer for you
Change the return value of public String developmentUrl() to your network IP with expo prefix will do

**Comment by Doroni** [comment]
Exactly same problem here.
What is the string that I string that I am supposed to fill in?
In my case the expo start says "Your native app is running at exp56ad2..://10.0.0.4:19000". Is that the string to fill in? (with the full string, not "...")
