### ISSUE TITLE
[SDK34] Ejected expo Android build fails on "Program type already present: androidx.versionedparcelable.CustomVersionedParcelable"

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#5517]
### Environment

```
Expo CLI 3.0.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.11.2 - ~/.npm-global/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.0.10
```

Ejected ExpoKit SDK34 app, building for Android
Build is ok on iOS (app deployed and approved on AppStore)

### Steps to Reproduce

This is detailled here : https://forums.expo.io/t/help-wanted-how-to-build-android-with-expokit-sdk34/27097 

### Expected Behavior

Build success ...

### Actual Behavior

./gradlew installDebug fails with
```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: androidx.versionedparcelable.CustomVersionedParcelable
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: androidx.versionedparcelable.CustomVersionedParcelable
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 42s
```

### Reproducible Demo

Is there an existing example project that builds fine on Android, so I can modify it to make a reproducible demo ?

**Comment by cruzach** [comment]
I don't believe Expokit is compatible with AndroidX just yet, do you know if one of your dependencies relies on an AndroidX library?

Added this to the forum post, but we'll just keep the conversation here so adding here as well-

> One thing I should add here that I’ve noticed caused some problems for others ->
When opening the project, Android Studio may prompt you to upgrade the version of Gradle or other build tools, but don’t do this as you may get unexpected results. ExpoKit always ships with the latest supported versions of all build tools. (from our docs)

**Comment by tsapeta** [comment]
SDK34 and ExpoKit are no longer supported and we didn't get similar reports since this one. I recommend to eject to bare workflow instead of ExpoKit.
I'm closing this.
