### ISSUE TITLE
SQLite directory does not exist

### ISSUE THREAD

**Issue by pixel-rain** [expo/expo#5518]
### Environment

  Expo CLI 2.19.4 environment info:
    System:
      OS: Windows 7
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

The problem is with apk that's built with **expo build:android** command, SDK 33, I run it on my Xiaomi Redmi 4X, Android 7.1.2

### Steps to Reproduce

It cannot properly load the pre-existing sqlite3 database from assets when it's an apk build, but when it's run on the testing environment via Expo app it works perfectly.

### Expected Behavior

The pre-filled sqlite3 database should be properly loaded from assets and be usable.

### Actual Behavior

It doesn't load and as I have said earlier it happens with apk only. Here is a screenshot of logcat from android studio when I opened the apk there. On the actual device it simply does nothing.

![no sqlite directory exists](https://i.imgur.com/OYfegCJ.png)

On a side note, it's not the only expo-related problem with this sqlite database, it also has problems with updating (similar to this https://github.com/expo/expo/issues/639 old issue, that db.close() command doesn't helps much because it crashes the app after execution and has to be commented after I reset my database with it), so I am tempted to use a js file with hashtable entries instead since it's a read-only database anyway and it is not particularly large...

### Reproducible Demo

I doubt that creating a snack expo app would help here because it's a build issue...
Here are the lines of code that I use to upload the database

in the App.js

```
  async function loadDB() {
    const check = await FileSystem.getInfoAsync(`${FileSystem.documentDirectory}SQLite/recipes.sqlite3`);
    if (!check.exists) {
      await FileSystem.downloadAsync(Asset.fromModule(require('./assets/db/recipes.sqlite3')).uri, `${FileSystem.documentDirectory}SQLite/recipes.sqlite3`);
    }
  }

  useEffect(() => {
    loadDB();
  }, []);
```

in the file that handles the db interaction:

`const db = SQLite.openDatabase('recipes.sqlite3');`

**Comment by tryvy** [comment]
Try this

import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';
const databaseName = "recipes.sqlite3";

  async copyDatabase() {
    try {
      await FileSystem.makeDirectoryAsync(`${FileSystem.documentDirectory}SQLite`, {
        intermediates: true
      });
      const localDatabase = await FileSystem.getInfoAsync(`${FileSystem.documentDirectory}SQLite/${databaseName}`);
      if ( !localDatabase.exists ) {
        FileSystem.downloadAsync(
          Asset.fromModule(require('../../assets/www/'+databaseName)).uri,
          `${FileSystem.documentDirectory}SQLite/${databaseName}`
        ).then(({ uri }) => {
          console.log('✅ Database copy to : ' + uri);
        })
        .catch(error => {
          console.log('❗️ Database copy error : ' + error);
        })
      } else {
        console.log('✅ Database exist');
      }
    } catch (error) {
      console.log('❗️ Error : ' + error);
    }
  }

**Comment by tryvy** [comment]
Try this

`
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';
const databaseName = "recipes.sqlite3";

async componentDidMount() {
	this.copyDatabase();
}

async copyDatabase() {
	try {
	  await FileSystem.makeDirectoryAsync(`${FileSystem.documentDirectory}SQLite`, {
	    intermediates: true
	  });
	  const localDatabase = await FileSystem.getInfoAsync(`${FileSystem.documentDirectory}SQLite/${databaseName}`);
	  if ( !localDatabase.exists ) {
	    FileSystem.downloadAsync(
	      Asset.fromModule(require('../../assets/www/'+databaseName)).uri,
	      `${FileSystem.documentDirectory}SQLite/${databaseName}`
	    ).then(({ uri }) => {
	      console.log('✅ Database copy to : ' + uri);
	    })
	    .catch(error => {
	      console.log('❗️ Database copy error : ' + error);
	    })
	  } else {
	    console.log('✅ Database exist');
	  }
	} catch (error) {
	  console.log('❗️ Error : ' + error);
	}
}
`

**Comment by tryvy** [comment]
Try this!


```
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';
const databaseName = "recipes.sqlite3";

async componentDidMount() {
	this.copyDatabase();
}

async copyDatabase() {
	try {
	  await FileSystem.makeDirectoryAsync(`${FileSystem.documentDirectory}SQLite`, {
	    intermediates: true
	  });
	  const localDatabase = await FileSystem.getInfoAsync(`${FileSystem.documentDirectory}SQLite/${databaseName}`);
	  if ( !localDatabase.exists ) {
	    FileSystem.downloadAsync(
	      Asset.fromModule(require('../../assets/www/'+databaseName)).uri,
	      `${FileSystem.documentDirectory}SQLite/${databaseName}`
	    ).then(({ uri }) => {
	      console.log('✅ Database copy to : ' + uri);
	    })
	    .catch(error => {
	      console.log('❗️ Database copy error : ' + error);
	    })
	  } else {
	    console.log('✅ Database exist');
	  }
	} catch (error) {
	  console.log('❗️ Error : ' + error);
	}
}
```

**Comment by pixel-rain** [comment]
Thank you! Adding this line
```
await FileSystem.makeDirectoryAsync(`${FileSystem.documentDirectory}SQLite`, {
	    intermediates: true
	  });
```
made it work in apk too.

That discrepancy between apk and testing environment is weird though, I hope I won't stumble into another one equally confusing...

**Comment by cruzach** [comment]
It looks like you might have to run a `transaction` on the `Database` object in order for the directory to be created (at least that's what it seems from my testing so far).

So if you've run SQLite queries in your Expo Client app before, the SQLite directory will already have been created, but if you haven't then `${FileSystem.documentDirectory}SQLite/` doesn't exist

**Comment by 16isaac89** [comment]
i have done the same as this method copyDatabase() and it returns database exists but when i try to execute a transaction on one of the tables, it says table does not exist
