### ISSUE TITLE
Cannot run application after eject

### ISSUE THREAD

**Issue by billtlee** [expo/expo#5520]
Hi, I am working on an application that uses:

    "expo-facebook": "~6.0.0",
    "expo-google-app-auth": "^6.0.0",

The application was working in expo but because I need to use a native lib, I decided to eject the project.  After I ejected, I ran pod install in the iOS directory and did not receive any errors.  I then tried to run react-native run-ios to build the app.  At this point, it failed and gave me a bunch of error on no type or protocol named 'OIDExternalUserAgentSession'.  After doing some reading, from the doc, it suggested that I also install expo-app-auth.  I did that and ran pod install again.  The same error came back.  I tried adding @protocol OIDExternalUserAgentSession; into ExAppAuthSessionsManager.h and I was able to get rid of that first error.  However, I am now getting an error saying:

no known instance method for selector 'resumeExternalUserAgentFlowWithURL:'

I can't seem to find any solutions on this error.  Can someone please help?

**Comment by cruzach** [comment]
Were you trying to install [expo-app-auth](https://docs.expo.io/versions/latest/sdk/app-auth/) or [expo-google-app-auth](https://docs.expo.io/versions/latest/sdk/google/)?

**Comment by billtlee** [comment]
The original app had expo-google-app-auth in it and it was working within expo.  I then ejected and wasn't able to get the app to work.  I found some post that expo-app-auth is needed for expo-google-app-auth, I then tried to install expo-app-auth.  So, expo-app-auth was installed after I ejected.

**Comment by cruzach** [comment]
What Expo SDK version are you using? And what version of `expo-app-auth`?

**Comment by billtlee** [comment]
"expo": "^34.0.1",
    "expo-app-auth": "^6.0.0",
    "expo-barcode-scanner": "~6.0.0",
    "expo-camera": "~6.0.0",
    "expo-constants": "~6.0.0",
    "expo-facebook": "~6.0.0",
    "expo-google-app-auth": "^6.0.0",
    "expo-secure-store": "~6.0.0",

**Comment by cruzach** [comment]
Hm okay, those are all up-to-date

And you ejected when you were already on SDK 34? As opposed to ejecting in a previous SDK and now upgrading to 34? I would check through [the upgrade guide](https://docs.expo.io/versions/latest/expokit/expokit/#ios-1) to ensure your native files are all up to date

**Comment by billtlee** [comment]
The project is relatively new.  Just created it 2 weeks ago and I haven't upgraded expo since I created the project.

**Comment by cruzach** [comment]
Gotchya, that's definitely weird

Could you share the full error message you're getting/any relevant stack trace?

**Comment by billtlee** [comment]
Sure.  Here it is:

info Found Xcode workspace inwallet.xcworkspace
info Building using "xcodebuild -workspace inwallet.xcworkspace -configuration Debug -scheme inwallet -destination id=5C38FF19-A215-4253-AF6B-5E896B91CD69 -derivedDataPath build/inwallet"
    The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'AppAuth')
    The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'FBSDKLoginKit')
    The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'FBSDKCoreKit')
    The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'RNGestureHandler')
    The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'RNReanimated')
    The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'react-native-rsa-native')
▸ Compiling EXAppAuthAppDelegate.m

❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.h:10:29: no type or protocol named 'OIDExternalUserAgentSession'

- (void)registerSession:(id<OIDExternalUserAgentSession>)session;
                            ^



❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.h:11:31: no type or protocol named 'OIDExternalUserAgentSession'

- (void)unregisterSession:(id<OIDExternalUserAgentSession>)session;
                              ^


▸ Compiling EXAppAuth.m

❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.h:10:29: no type or protocol named 'OIDExternalUserAgentSession'

- (void)registerSession:(id<OIDExternalUserAgentSession>)session;
                            ^



❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.h:11:31: no type or protocol named 'OIDExternalUserAgentSession'

- (void)unregisterSession:(id<OIDExternalUserAgentSession>)session;
                              ^


▸ Compiling EXAppAuthSessionsManager.m

❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.h:10:29: no type or protocol named 'OIDExternalUserAgentSession'

- (void)registerSession:(id<OIDExternalUserAgentSession>)session;
                            ^



❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.h:11:31: no type or protocol named 'OIDExternalUserAgentSession'

- (void)unregisterSession:(id<OIDExternalUserAgentSession>)session;
                              ^



❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.m:8:47: no type or protocol named 'OIDExternalUserAgentSession'

@property (nonatomic, strong) NSMutableSet<id<OIDExternalUserAgentSession>> *currentAuthorizationFlows;
                                              ^



❌  /Users/Bill/Documents/MyProjects/inwallet/node_modules/expo-app-auth/ios/EXAppAuth/EXAppAuthSessionsManager.m:24:29: no type or protocol named 'OIDExternalUserAgentSession'

- (void)registerSession:(id<OIDExternalUserAgentSession>)session
                            ^


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening inwallet.xcworkspace

** BUILD FAILED **

**Comment by cruzach** [comment]
Ah okay, what version of Xcode do you have?

**Comment by billtlee** [comment]
I am running 10.3

**Comment by cruzach** [comment]
Okay, that's good

Well after re-reading your original post, I'm not sure why you're trying to run with `react-native run-ios`. The appropriate method to run an iOS Expokit project can be found [here](https://docs.expo.io/versions/latest/expokit/expokit/#setting-up-your-project), and that might show some more helpful info

**Comment by Kailash23** [comment]
@cruzach I had also ejected my app from the expo with expokit workflow. I want to know the proper way of making a standalone app.  This doesn't provide [link](https://docs.expo.io/versions/latest/expokit/expokit/#setting-up-your-project ) to make a standalone application.

**Comment by cruzach** [comment]
Unless you're in the managed workflow, you'll build standalone apps normally (with Xcode or Android Studio, depending on the platform you're building for)

Expo's build service only applies to managed Expo apps at the moment

**Comment by Kailash23** [comment]
@cruzach Okay, Thanks for your response.

**Comment by EvanBacon** [comment]
Please migrate to using the new expo-auth-session API which works in the bare-workflow and for iOS, Android, and web. Google guide: https://docs.expo.io/guides/authentication/#google
