### ISSUE TITLE
Hot loading could fail in some circumstances

### ISSUE THREAD

**Issue by ScreamZ** [expo/expo#5524]
Hello,

I just figured out my Hot reloading was not working.

**I just found why he wasn't**, so I would like to share the answer here so maybe other people can use this, we can also add it to expo FAQ ?

My hot reloading was broken because my root component was not a class component, but a function component. I don't know exactly why this is required, by I guess it could be related to refs and/or component life-cycle.

Generally speaking, this is not working well with hooks currently, because this doesn't keep state with them.

So, you just need to migrate something like this in `App.tsx` (or App.js)

**From**
```tsx
import React from "react";
import { ThemeProvider } from "styled-components";
import AppNavigator from "./src/modules/navigation/AppNavigator";
import { theme } from "./src/modules/ui/theme";

import "./src/modules/i18n";

export default function App() {
  return (
    <ThemeProvider theme={theme}>
      <AppNavigator />
    </ThemeProvider>
  );
}
```

**To**
```tsx
import React from "react";
import { ThemeProvider } from "styled-components";
import AppNavigator from "./src/modules/navigation/AppNavigator";
import { theme } from "./src/modules/ui/theme";

import "./src/modules/i18n";

export default class App extends React.Component {
  render() {
    return (
      <ThemeProvider theme={theme}>
        <AppNavigator />
      </ThemeProvider>
    );
  }
}
```

I know that https://twitter.com/dan_abramov/status/1144630328142831616 is coming to the next release, I don't know if this would fix the following issue (@gaearon poke).

Hope this can help and is not exactly a bug ?

Best regards

**Comment by cruzach** [comment]
Thanks for pointing this out! I just opened a PR to update the docs

**Comment by ScreamZ** [comment]
@cruzach It's even worse, each component that should support HMR should be a class, otherwise it get replacing completely, (hope this is fixed in 0.61)

**Comment by cruzach** [comment]
Ah right, okay I'll update my docs PR

**Comment by ScreamZ** [comment]
For coming user and further updates : 

(Temporary fix)
https://github.com/bvic23/babel-plugin-functional-hmr

And Main thread https://github.com/facebook/react-native/issues/8465

Dan answer https://github.com/facebook/react-native/issues/8465#issuecomment-506883639 (Will be fixed in 0,61), But root has to be in a separated file. (It's ok)
