### ISSUE TITLE
Detaching to ExpoKit not working on iOS

### ISSUE THREAD

**Issue by joseasalazar** [expo/expo#5525]
Tried to follow the steps to eject expo app to expokit and I faced the next build error in Xcode
No visible @interface for 'EXLocalAuthentication' declares the selector 'authenticateWithOptions:resolve:reject:'

### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.0.10

Podfile: 
pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.12.4",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true

### Steps to Reproduce

Followed ExpoKit Developing instructions as following https://docs.expo.io/versions/latest/expokit/expokit/ and tried to run project in xcode and had build error

### Behavior
Cant run the app on ios so I can't run it on expo either

**Comment by cruzach** [comment]
You have the `expo` package set to `^33.0.0`, but your `react-native` dependency points to Expo's SDK 34 tar. Try matching those (either use Expo SDK 34, or use the SDK 33 react native dependency point) and then build/run again

**Comment by joseasalazar** [comment]
Thanks a lot, I didn't knew there was a new release that's why I didn't checked that, thank you! ☺️
