### ISSUE TITLE
Camera not working in Android-emulator

### ISSUE THREAD

**Issue by timLoewel** [expo/expo#5529]
## 🐛 Bug Report
The expo camera component does not work in the current android emulator on linux.

### Environment
 Expo CLI 3.0.10 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
      Shell: 5.5.1 - /usr/bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.11.2 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.3.2 => 3.7.1 
    npmGlobalPackages:
      expo-cli: 3.0.10

Android emulator version 29.0.11.0 (build_id 5598178) (CL:N/A)

AVD:

Name: PixelAPI28
CPU/ABI: Google Play Intel Atom (x86)
Path: /home/timloewel/.android/avd/PixelAPI28.avd
Target: google_apis_playstore [Google Play] (API level 28)
Skin: 1080x2220
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_3a
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 28
tag.id: google_apis_playstore
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: PixelAPI28
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: true
fastboot.forceColdBoot: no
hw.cpu.ncore: 2
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 2220
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
skin.path.backup: _no_skin
hw.audioInput: yes
image.sysdir.1: system-images/android-28/google_apis_playstore/x86/
showDeviceFrame: no
hw.camera.back: virtualscene
AvdId: PixelAPI28
hw.lcd.density: 440
hw.arc: false
hw.device.hash2: MD5:0e6953ebf01bdc6b33a2f54746629c50
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google Play
runtime.network.latency: none
disk.dataPartition.size: 6442450944
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

### Steps to Reproduce

- Start the android emulator
- Start the expo app
- Start in the **Expo APIs@community** App 
- go to tab "Expo Components"
- choose camera 

=> The screen is black.

### Expected Behavior
see a virtual scene, as in the stock camera of the same emulator.

### Actual Behavior
Black preview. All controlls are there, but no preview.

### Reproducible Demo
**Expo APIs@community** App

**Comment by cruzach** [comment]
Not sure if it's possible to integrate with the virtual scene...we do state in the Camera API docs:
> Note: The Camera API will not work on simulators or emulators.

**Comment by lukmccall** [comment]
The camera doesn't work on simulators and emulators, that's why you get black screen. On real devices, it should work fine.
