### ISSUE TITLE
How to use redux-devtools with Expo

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#553]
Hi,

Can you please provide an example of how to use [redux-devtools](https://github.com/gaearon/redux-devtools) with Expo?

What do you think, would it also make sense to add it to the docs?

Thanks, cheers!

**Comment by jimmylee** [comment]
You can use React Native Debugger :) it includes Redux DevTools

Learn more here: https://github.com/jhen0409/react-native-debugger

Here is an example of React Native Debugger + Create React Native App: https://github.com/jhen0409/react-native-debugger/tree/master/examples/counter-with-redux

Here is a medium post you can follow to use it With Expo:
https://medium.com/@jimgbest/react-native-debugger-expo-awesome-d7a00da51460

**Comment by pensierinmusica** [comment]
@jimmylee thx! It'd be cool to have some reference included in the Expo docs imho. What do you think? Cheers!

**Comment by Viral-Inc** [comment]
@jimmylee  I'm not sure following that Medium post works anymore for using React Native Debugger with Expo, re this issue: https://github.com/jhen0409/react-native-debugger/issues/32

<img width="575" alt="screenshot 2017-09-22 12 45 16" src="https://user-images.githubusercontent.com/17430356/30766127-6a914eae-9fb0-11e7-86d9-219b1bced264.png">

<img width="591" alt="screenshot 2017-09-22 12 45 36" src="https://user-images.githubusercontent.com/17430356/30766132-6d73b1e8-9fb0-11e7-9502-21bccb0e0f8e.png">

**Comment by corysimmons** [comment]
I gotcha fams

![image](https://user-images.githubusercontent.com/224636/36965777-9fc7c60e-2028-11e8-81c2-2f8ddd5e1882.png)

- Clone https://github.com/react-navigation/react-navigation/tree/f1bfdeee46369cc52e89603d44c297254110fc36/examples/ReduxExample
- `yarn add redux-devtools-extension`
- modify App.js by adding:

```js
// ...
import { composeWithDevTools } from 'redux-devtools-extension'

const store = createStore(
  AppReducer,
  composeWithDevTools(applyMiddleware(middleware)),
);
// ...
```
- `open "rndebugger://set-debugger-loc?host=localhost&port=19001"`
- Fire up your project in Expo XDE
- cmd + d > "Debug Remote JS"

**Comment by Tetsuya3850** [comment]
@pensierinmusica I've added this topic in the docs! (https://docs.expo.io/versions/v32.0.0/workflow/debugging/)
