### ISSUE TITLE
Calendar created using Expo-Calendar not modifiable

### ISSUE THREAD

**Issue by davidli3100** [expo/expo#5534]
### Environment

Latest expo CLI, Android Expo Client

### Steps to Reproduce

use the object below as the settings for a new calendar

`calendarDetails = {
                id: "foo",
                title: "foo",
                entityType: "Calendar.EntityTypes.EVENT",
                color: "#0063e7",
                allowsModifications: true,
                sourceId: 
                Platform.OS === 'ios'
                  ? this.state.calendars.find(cal => cal.source && cal.source.name === 'Default').source.id
                  : undefined,
                source:
                    Platform.OS === 'android'
                    ? {
                        name: this.state.calendars.find(
                            cal => cal.accessLevel === Calendar.CalendarAccessLevel.OWNER
                        ).source.name,
                        isLocalAccount: true,
                    }
                    : undefined,
                name: "foo",
                ownerAccount: "foo",
                accessLevel: "Calendar.CalendarAccessLevel.ROOT"
            }`

### Expected Behavior

The events that the calendar makes should be able to be deleted, changed, etc.

### Actual Behavior

Calendar and events in the calendar aren't modifiable

### Reproducible Demo

I'm not quite sure how to reproduce it correctly on snack. but if you paste my calendar config as the settings/options for a new calendar it should reproduce

**Comment by lukmccall** [comment]
Hi @davidli3100, I've tried to reproduce this bug, but I've failed. Could you provide me some more information or working demo?

**Comment by davidli3100** [comment]
@lukmccall sorry for the delay, I just used the calendar config I pasted above to create my calendar. Not sure if there's anything wrong with that. 

Is it now possible to just write to an user's default calendar on both iOS and Android now?

**Comment by lukmccall** [comment]
Hi @davidli3100, on iOS, you can use `getDefaultCalendarAsync` to get the default calendar. 
However, it's not possible to get it on Android.

I've double-checked your calendar's configuration. You passed the wrong values into access level property. Please, remove apostrophes. `Calendar.CalendarAccessLevel.ROOT` is exported const so use it as a variable.

Let me know if it's fixed your issue ;)
