### ISSUE TITLE
[ad hoc] Expo custom iOS client crash

### ISSUE THREAD

**Issue by 0es** [expo/expo#5537]
The created ios custom client app does crash while starting.
The app was deinstalled and re-installed. Did restart the iPhone, too.
When opening the App the white Expo splash screen with the “A”-icon is visible for a second and then back to the home screen.
```
Device: iPhone XS with iOS 12.4.1
```
Then I suspect the problem is on the Profile file.So I cleared Certificates & Identifiers & Profiles on the apple developer account and use expo client:ios rebuild it for many many time. Undoubtedly failed. Just crash and crash
**When the Profile been installed, it just open a web page, but it didn't show up at configuration profile like other Profile file**
And I tried it with Apple configurator 2. the same
I very much hope that someone can come out and help us solve this problem.
Thank you very much

**Comment by ide** [comment]
This is most likely related to the ad hoc provisioning profile as you suspect. When you get this behavior it means your device UDID is not registered with the provisioning profile. Be sure to go through the UDID registration flow through the Expo website on your device and make sure your device UDID is associated with an ad hoc provisioning profile on the Apple developer site.

**Comment by 0es** [comment]
I repeated the build process again, then confirmed that my current device's UDID is correct and enabled in the Profile file.
but still crash

**Comment by 0es** [comment]
Can anyone help us test it?
Thank u very much

**Comment by tsaiDavid** [comment]
@ide - I'm seeing the same issues and tried it several times and ensured that I do have the correct ad hoc provisioning profile set up.

**Comment by schellack** [comment]
I am experiencing this issue as well. The Custom Expo Client crashes when loading.

I verified that my device's UDID is listed on the Apple Developer Portal. I am running an iPhone XS Max on iOS 12.4. Expo CLI version 3.0.10.

[Here is the most recent crash log from my device](https://github.com/expo/expo/files/3587088/DevExpoClientXvf26jvf3jdukhngscefgkroh5ic2xmlpcfh4b3ftgllq-2019-09-07-170041.crash.zip).

**Comment by tsaiDavid** [comment]
I as well tried numerous times, using a great variety of devices, each time ensuring the correct UUID (device) was listed on Apple's side - and each time the custom client would just open only to crash immediately. I've even tried removing the standard installation of Expo I had through the App Store, in case of any conflicts that could've been happening.

![ScreenShot](https://user-images.githubusercontent.com/12259854/64500387-d2b93000-d271-11e9-9c7c-7b9f0a127ed8.jpg)

**Comment by mccordgh** [comment]
iOS: 12.4.1
iPhone 7

Having same issue with custom expo client build crashing out to desktop as soon as it is started up. It then appears in the list of active apps, but if I try to select it again it just crashes out to desktop again.

I've been using the Expo Custom Client on and off successfully. I'm working with a couple apps that do push notification and location tracking so I have to swap between the regular and custom expo apps.

 I hadn't used the custom client in a few weeks until today. Had the crash issue, deleted it from phone, went through the build process again, new custom build still crashes.

Is there a way to clear the cache and re-initialize all the custom build stuff? Would that help?

**Comment by LaszloDev** [comment]
> This is most likely related to the ad hoc provisioning profile as you suspect. When you get this behavior it means your device UDID is not registered with the provisioning profile. Be sure to go through the UDID registration flow through the Expo website on your device and make sure your device UDID is associated with an ad hoc provisioning profile on the Apple developer site.

Hey @ide and @quinlanj, could you have a second look? Some more information is provided and more people having the issue.
In my case Im still using the same phone with the same UDID as I used to generate a custom client with v34. Just ran a new build with the SDK v34 and getting crashes now.
Thanks, alot

**Comment by edot-dev** [comment]
@quinlanj Our team is facing the same issue, the custom iOS Client crashed. We have tried on multiple devices whose UDID  is registered with the provisioning profile created by expo.

![screenshot 98](https://user-images.githubusercontent.com/46995428/65512788-8ae40b00-def7-11e9-8a24-2eed2d331570.png)

**Comment by LaszloDev** [comment]
Same problem with expo SDK v35

**Comment by justinchan23** [comment]
also having the same issue here =(

**Comment by quinlanj** [comment]
i took a look at the crash logs and the reason the client builds are erroring out is because we have a `FaceDetector` package that is erroneously attempting to configure a Firebase App on startup. (see https://github.com/expo/expo/pull/5829 for more details)

We will get this fixed soon, but in the meantime, a quick way to get unblocked is to pass in a valid `GoogleService-Info.plist` file in your manifest, under the field `ios.googleServicesFile` (this requires the latest cli). Sorry for the inconvenience.

**Comment by 0libre** [comment]
> i took a look at the crash logs and the reason the client builds are erroring out is because we have a `FaceDetector` package that is erroneously attempting to configure a Firebase App on startup. (see #5829 for more details)
> 
> We will get this fixed soon, but in the meantime, a quick way to get unblocked is to pass in a valid `GoogleService-Info.plist` file in your manifest, under the field `ios.googleServicesFile` (this requires the latest cli). Sorry for the inconvenience.

Could you please provide what's needed (in detail)? Since the once of us who's just getting started with Expo and want to try this (and aren't running anything from Google) would love to get started.. Like I want to create a custom client to test the background location - but can't even start the custom client because of this. I tried adding a custom file:

`"ios": {
      "googleServicesFile": "./google-services.json"
}`

But even though I have create the file with data from a mock Firebase project - the custom client app still crashes...

**Comment by schellack** [comment]
Here are the steps I followed to workaround the issue, based on what @quinlanj said above:

- Follow [these instructions](https://firebase.google.com/docs/ios/setup) to generate and download the Google Firebase .plist file. Note that I already had a Firebase project; if you don't, you'll have to create one first.
- Create a new empty Expo app using Expo init from the CLI: `expo init custom-expo`
- Copy the downloaded .plist file into the new Expo app's folder
- Open the app.json file in the new Expo app. In the `ios` section, add this entry to reference the .plist file: `"googleServicesFile": "./GoogleService-Info.plist"`
- From the terminal/command line, make sure you are inside the folder of your new Expo app and run the following command to generate a new custom expo client: `expo client:ios --config ./app.json`

If you haven't generated a custom Expo client before, there may be other prerequisites you need to follow, so you may want to familiarize yourself with the normal instructions [here](https://docs.expo.io/versions/v35.0.0/guides/adhoc-builds/).

**Comment by quinlanj** [comment]
opening this back up  until we can successfully deploy changes

**Comment by quinlanj** [comment]
changes are deployed now, adhoc builds should be back up.

**Comment by LaszloDev** [comment]
Thank you @quinlanj its working again.
