### ISSUE TITLE
Better way of checking if module from registry exists

### ISSUE THREAD

**Issue by lukmccall** [expo/expo#5538]
When we getting something from `module registry` in `setModuleRegistry/onCreate` method, we never check if what we got exists.
Then in the exported method, we have code like this: 
```
if (!_moduleFromRegistry) {
  return reject(@"E_NO_PERMISSIONS", @"Module not found. ", nil);
}
```
Maybe we could develop a mechanism, which will check if the module exists in initial method and then we could get rid of our checks in the exported method.
I think it will be a cleaner solution. 

cc @sjchmiela

**Comment by sjchmiela** [comment]
It's not always obvious what should the module do if the `moduleFromRegistry` is not present. Sometimes we may want to ignore the problem, eg. if there is no filesystem permissions module we may decide that we want to allow access to whole filesystem and sometimes if there is no eg. screen orientation manager the module should reject the promise. Do you have some general flow that you would suggest?

**Comment by lukmccall** [comment]
I think, If the module is closely related to another module (Camera and Permissions), is better to throw an exception earlier. Maybe we could add the macro to `UMDefines`, which could wrap getting implementation from the registry and throw if the module is not present. 
Otherwise, we could leave it as it is.
