### ISSUE TITLE
can not upgrade or downgrade sdk at all

### ISSUE THREAD

**Issue by alemkhodadadi** [expo/expo#5539]
## 🐛 Bug Report
hi everyone. I dont know its related to expo or me. 
I started my project last year with sdk 30. last month i was going to publish my app in google play but i faced with an error talking about upgrading target api. now I want to upgrade to sdk 33 or 34. I tested upgrading as exactly what documentations said about 20 times or more! but everytime after npm i and expo start it shows different errors with my code while starting project. I dont think there are more ways to do that i hadn't been tested. unfortunately my project is really big. you believe or not but I spended about two terrific weeks for solving this but not succeed yet! and pardon me for my bad english!
any help?

### Environment
npm: 6.10.3
node : 10.16.1
expo: 3.0.9
OS: linux

### Please also let us know about your app's target: 

Android
my Package.json:
```
{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "env": "expo-env --env=development",
    "env:prod": "expo-env --env=prod"
  },
  "dependencies": {
    "@expo/vector-icons": "^8.0.0",
    "audit": "0.0.6",
    "axios": "^0.19.0",
    "crypto-js": "^3.1.9-1",
    "debounce": "^1.2.0",
    "ex-react-native-i18n": "0.0.4",
    "expo": "^34.0.3",
    "expo-cli": "^2.6.14",
    "expo-env": "^1.1.1",
    "fix": "0.0.6",
    "link": "^0.1.5",
    "native-base": "^2.13.4",
    "react": "16.8.3",
    "react-google-calendar-events-list": "^1.1.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-awesome-alerts": "^1.1.1",
    "react-native-camera": "^2.0.0",
    "react-native-checkbox-heaven": "^0.1.5",
    "react-native-easy-toast": "^1.1.0",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.0.10",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-jalali-calendar-picker": "^0.2.6",
    "react-native-jalali-date-picker-rtl": "^1.0.1",
    "react-native-lightbox": "^0.8.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^7.0.1",
    "react-native-navbar": "^2.1.0",
    "react-native-pulse": "^1.0.6",
    "react-native-pushe": "^1.6.3",
    "react-native-render-html": "^4.1.2",
    "react-native-sentry": "^0.42.0",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-ssl-pinning": "^1.1.8",
    "react-native-websocket": "^1.0.2",
    "react-navigation": "^3.11.1",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.15",
    "rn-viewpager": "^1.2.9",
    "sentry-expo": "^1.13.0",
    "sharp-cli": "^1.10.0",
    "uglify-es": "^3.2.2",
    "uuid": "^3.3.2",
    "ws": "^6.1.2"
  }
}
```
my app.json:
```
{
  "expo": {
    "name": "name",
    "description": "description",
    "slug": "slug",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "platforms": ["ios", "android"],
    "version": "24.1.4",
    "orientation": "portrait",
    "icon": "./src/assets/icons/Icon.png" , 
    "scheme": "scheme",
    "updates": {
      "enabled":true,
      "fallbackToCacheTimeout": 0,
      "checkAutomatically": "ON_ERROR_RECOVERY"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "splash": {
      "image": "./src/assets/images/Splashscreen.png",
      "resizeMode": "cover"
    },
    "android":{
      "package":"com.com.com",
      "permissions":[
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "CAMERA",
        "CAMERA_ROLL",
        "WRITE_EXTERNAL_STORAGE",
        "READ_EXTERNAL_STORAGE",
        "READ_INTERNAL_STORAGE",
        "WRITE_INTERNAL_STORAGE"
      ],
      "config":{
        "googleMaps": {
          "apiKey": "apiKey"
        }
      },
      "intentFilters": [
        {
          "action": "VIEW",
          "autoVerify": true,
          "data": [
            {
              "scheme": "https",
              "host": "*.host.com",
              "pathPrefix": "/adv"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ]
    }
  },
  "hooks": {
    "postPublish": [
      {
        "file": "sentry-expo/upload-sourcemaps",
        "config": {
          "organization": "organization",
          "project": "mysentry",
          "authToken": "authToken"
        }
      }
    ]
  }
  
  
  
}
```
### Steps to Reproduce

  1- In app.json, change sdkVersion to "34.0.0"
  2- In package.json, change these dependencies:
- react-native to "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz"
- expo to "^34.0.3"
- react to "16.8.3" — (this exact version)
- react-navigation to "^3.11.1" 
  3- If you use react-navigation you should also run expo install react-native-gesture-handler react-native-reanimated as these are no longer bundled in the expo JavaScript package.
  4- Delete your project’s node_modules directory and run npm install again (or use Yarn, we love Yarn)
  5- Run expo start -c **(and then errors and more errors about everything!)**
  6- Update the Expo app on your phones from the App Store / Google Play. expo-cli will automatically update your apps in simulators.
  7- Make sure to check the breaking changes section of this post!
If you built a standalone app previously, remember that you will need to create a new build in order to update the SDK version. Run expo build:ios and/or expo build:android when you are ready to do a new build for submission to stores.
  8- Update all of your imports to the new modular style, optionally by using expo-codemod.**(Done)**

### Expected Behavior

sdk version gets update as expected

### Actual Behavior

it seems updated but weird errors about syntax and varibles and imports or exports and ... while starting project

### Reproducible Demo
my app is a big project designed for a startup and unfortunately i really dont know where the problem is so i cant represent demo

**Comment by ide** [comment]
For dedicated help for a nebulous issue like this, I think a consultant might be the most direct way to helping you upgrade. We list some consultants at https://expo.io/consultants or can put you in touch with someone we think could help.

**Comment by alemkhodadadi** [comment]
@ide i really appreciate if you put me in touch with these people

**Comment by alemkhodadadi** [comment]
is it just my issue?!!!!  no solution?!

**Comment by ide** [comment]
I'll ask around for consultants who may be able to help with this. It would be a smaller job so I'm not sure we'll be able to find someone but I will let you know if we do.

**Comment by alemkhodadadi** [comment]
@ide i really appreciate if you do it for me. You'll save from migration to react-native cli

**Comment by alemkhodadadi** [comment]
@ide i really appreciate for your Generously help. You'll save me from migration to react-native cli

**Comment by ide** [comment]
Hi - I talked to a few folks but generally these consultancies are looking for larger projects. As this issue is very specific to one project and we need to spend our time on more general issues, I don't think this is something we can help with.
