### ISSUE TITLE
Push Notifications not working ios/android

### ISSUE THREAD

**Issue by madaviela** [expo/expo#554]
im getting an error when im trying to follow the guide for set up push notifications, im usinc expo proyect sdk 20 and also real devices, i can get the expopushtoken but when i post to my server it says an error 422

`
    async registerPN() {
        const { existingStatus } = await Permissions.getAsync(Permissions.REMOTE_NOTIFICATIONS);
        let finalStatus = existingStatus;
      
        // only ask if permissions have not already been determined, because
        // iOS won't necessarily prompt the user a second time.
        if (existingStatus !== 'granted') {
          // Android remote notification permissions are granted during the app
          // install, so this will only ask on iOS
          const { status } = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);
          finalStatus = status;
        }
      
        // // Stop here if the user did not grant permissions
        // if (finalStatus !== 'granted') {
        //   return;
        // }
      
        // Get the token that uniquely identifies this device
        let tookeeen = await Notifications.getExpoPushTokenAsync();
        console.log("AN ERROR OCCURED:\n" + tookeeen)     

        let peticion = fetch("https://domain.com/api/exponent/devices/subscribe", {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + this.state.Auth
            
          },
          body: JSON.stringify({
            token: {
              value: tookeeen,
             },
             user: {
              username: 'David',
             },
          }),
        });
        console.log(peticion)
    }`

![captura de pantalla 2017-08-26 a la s 16 35 18](https://user-images.githubusercontent.com/10695637/29745301-9875e3a0-8a7c-11e7-9c58-243f6935ff3f.png)

**Comment by ablankenship10** [comment]
The 422 error is a problem with your API, not expo

**Comment by madaviela** [comment]
at this point its problem from my api, i cant send push notifications from laravel

**Comment by skevy** [comment]
As @ablankenship10 mentioned, this is a problem with your API.

Please provide any specific error messages you receive from Expo's API, and we can help you further.

Closing for now.
