### ISSUE TITLE
json validation error when adding googleMobileAdsAppId per v34 release note as Admob requirement

### ISSUE THREAD

**Issue by hsiehro** [expo/expo#5545]
According to v34 release note below

Google Mobile Ads now require expo.[platform].config.googleMobileAdsAppId configuration value present in app.json. The value can be found by following the guide in this Google Support answer. (#5447) by @sjchmiela

By trying to add the configuration into my app.json, return below error during the build. It seems the new field is still not recognize as valid value in the latest release.

Error: Problems validating fields in app.json. See https://docs.expo.io/versions/v32.0.0/workflow/configuration/
 • Field: ios.config - should NOT have additional property 'googleMobileAdsAppId'.
 • Field: android.config - should NOT have additional property 'googleMobileAdsAppId'.

Here is my app.json config for Android part for your reference:

"android": {
      "package": "xxxx",
      "versionCode": 1,
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-xxxxxx"
      }
    }

**Comment by sjchmiela** [comment]
Although this PR has been merged, the changes haven't been released yet. They will be part of the SDK35 release. Then there will be no errors when building with `googleMobileAdsAppId` in `app.json`. 🙂

**Comment by nucle4r** [comment]
Any Workaround till then?

**Comment by AustinMCrane** [comment]
im still getting this error after upgrading to sdk35
```❯ expo build:ios
Checking if there is a build in progress...

Publishing to channel 'default'...
Error: Problems validating fields in app.json. See https://docs.expo.io/versions/v34.0.0/workflow/configuration/
 • Field: ios.config - should NOT have additional property 'googleMobileAdsAppId'.
 • Field: android.config - should NOT have additional property 'googleMobileAdsAppId'.
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.```

package.json:
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "~3.0.3",
    "@expo/vector-icons": "^10.0.3",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "android": "0.0.8",
    "axios": "^0.19.0",
    "expo": "^35.0.0",
    "expo-ads-admob": "^6.0.0",
    "expo-analytics": "^1.0.11",
    "expo-app-auth": "^6.0.0",
    "expo-asset": "^6.0.0",
    "expo-constants": "6.0.0",
    "expo-font": "~6.0.0",
    "expo-google-sign-in": "^6.0.0",
    "expo-store-review": "^1.0.0",
    "expo-web-browser": "6.0.0",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-elements": "^1.2.1",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-segmented-control-tab": "^3.4.1",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0",
    "jest-expo": "^34.0.0"
  },
  "private": true
}
```
what am i doing wrong?

**Comment by hsiehro** [comment]
> im still getting this error after upgrading to sdk35
> 
> ```
> Checking if there is a build in progress...
> 
> Publishing to channel 'default'...
> Error: Problems validating fields in app.json. See https://docs.expo.io/versions/v34.0.0/workflow/configuration/
>  • Field: ios.config - should NOT have additional property 'googleMobileAdsAppId'.
>  • Field: android.config - should NOT have additional property 'googleMobileAdsAppId'.
> Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.```

@AustinMCrane You are getting this error most likely due to you forgot to change your expo sdkVersion inside app.json. Make the change with "sdkVersion" : "35.0.0" and it should work. If not, remove your node_modules folder and re-build again.

Hope this will help.
