### ISSUE TITLE
ScreenOrientation UNKNOWN on iPad (Expo Client)

### ISSUE THREAD

**Issue by awinograd** [expo/expo#5549]
Orientation stays as UNKNOWN on iPads, but works on Android phones + iPhones. Haven't tested an Android tablet yet.

Repro: https://snack.expo.io/@ouihealth/screenorientation-test

Simulator demo: https://cl.ly/1b6df68df53a

Potentially related to https://github.com/expo/expo/issues/5033 https://github.com/expo/expo/issues/5257

**Comment by mauriciocarlesso** [comment]
same problem!

**Comment by lukmccall** [comment]
Hi everyone, it'll be fixed in SDK 37. However, it won't work in expo-client. For more information, check out [this PR](https://github.com/expo/expo/pull/6838).

For now, I'm closing this issue. Feel free to reopen it if this bug still occurs in the newest SDK.

**Comment by awinograd** [comment]
Thank you @lukmccall !
