### ISSUE TITLE
segment import

### ISSUE THREAD

**Issue by flieks** [expo/expo#555]
Very strange but if i 
`import { Segment } from 'expo'`
it seems to be importing "default"
![image](https://user-images.githubusercontent.com/5032389/29749198-ccd5a1b2-8b26-11e7-9659-855e4104982c.png)

this is my babelrc code:
```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

**Comment by jimmylee** [comment]
Hi there, I hope I can help you out.

I'm confused why you are using `Expo.Segment.initializeAndroid`, Shouldn't it just be

```
import { Segment } from 'expo';

Segment.initializeAndroid(<YOUR KEY>);
```

Let me know if this fixes your problem.

**Comment by flieks** [comment]
Thanks @jimmylee , i puted Expo because it's like this in the docs. 
I changed to your code and it fixed the "default" but i get now
`cannot read property initializeAndroid of undefined`
![image](https://user-images.githubusercontent.com/5032389/29846335-c3036a06-8d16-11e7-9cdb-f2f5f015149c.png)

**Comment by jimmylee** [comment]
That looks like exactly what it should be

**Comment by flieks** [comment]
this is very weird indeed. 
Maybe because i'm running it in componentWillMount? Where to put this code in App.js ?
