### ISSUE TITLE
Exp camera api issue

### ISSUE THREAD

**Issue by tbiinfotech** [expo/expo#5556]
I am using expo camera api for recording purpose, I open camera in landscape mode for video recording in android, After video recording path of video not work on android but on ios it works. When i open on portrait it worked on both ios and android, Please sort ou

**Comment by cruzach** [comment]
Hi! Please follow the bug report template, since we need a lot more information to troubleshoot effectively. Specifically, make sure to include the SDK version and a [snack](https://snack.expo.io/) that reproduces the bug
