### ISSUE TITLE
[docs] Why is documentDirectory string | null

### ISSUE THREAD

**Issue by iwikal** [expo/expo#5558]
https://docs.expo.io/versions/latest/sdk/filesystem/
According to the typescript definitions, FileSystem.documentDirectory et al. are `string | null`, but the documentation doesn't mention the nullability. When are they null? Judging by the documentation alone, never. Which is right? Do we need to put a null check in? Or is it safe to ignore, and suppress the error message?

**Comment by cruzach** [comment]
They return `null` on web -> https://github.com/expo/expo/blob/master/packages/expo-file-system/src/ExponentFileSystemShim.ts
