### ISSUE TITLE
Expo Push Notifications linked to an old app

### ISSUE THREAD

**Issue by mikadze** [expo/expo#556]
I used Expo Push notifications in my app and they worked, but the app got rejected from the app-store due to the naming, so I had to create the same app with different name. Changed app name and slug, but forgot to change the bundle identifier. Built app with new certificates and now when I try to send push notifications I get the following error:  The recipient "ExponentPushToken[xxxxxxxxx]" is associated with a different experience than "@username/old-app-name"

Why generating new certificates still links to old app? is it because i didn't change the bundle identifier?
I can't change bundle identifier in itunes connect. Is there any way to solve this  or I have to delete the submission and resubmit with different bundle id?

**Comment by itslittlejohn** [comment]
How did you resolve this @mikadze?

**Comment by AbdulazizGH** [comment]
I'm having the same problem. Did anyone solve this? @mikadze @brownbl1

**Comment by robertobrogi** [comment]
me too i have the same problem.... there is any solution?
