### ISSUE TITLE
[SecureStore] Changing passcode does not remove SecureStore entries or prevent from setting entries

### ISSUE THREAD

**Issue by joshg2k** [expo/expo#5561]
### Environment
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.0.10

App targets: iOS, Android, Standalone

### Steps to Reproduce
1. Make sure your device has a passcode.
2. Store a value in SecureStore using WHEN_PASSCODE_SET_THIS_DEVICE_ONLY:
`SecureStore.setItemAsync(KEY, VALUE, { keychainAccessible: SecureStore.WHEN_PASSCODE_SET_THIS_DEVICE_ONLY });`
3. Disable your device passcode.
4. Retrieve the value from SecureStore and see that it is still present:
`SecureStore.getItemAsync(KEY)`

### Expected Behavior
getItemAsync returns null since there should not longer be an entry for the given key.

### Actual Behavior
getItemAsync returns VALUE

### Reproducible Demo
I unfortunately don't think I can do this with a Snack since you have to set and remove a device passcode.

**Comment by cruzach** [comment]
Hi @joshg2k - you can still provide a snack and then we can run it on a device rather than a simulator

I've gone ahead and made one, thanks for reporting this! 

Repro- https://snack.expo.io/@charliecruzan/secure-store

**Comment by joshg2k** [comment]
Hey @cruzach, sorry I was having brain issues that day. I didn't think about using the device.

**Comment by joshg2k** [comment]
I just confirmed that this issue occurs in both iOS and Android.

**Comment by ryanphung** [comment]
Hi @joshg2k confirmed that I also face a similar issue, at least on iOS.

(I don't think this option is available in Android? - at least that's what is said in the documentation).

https://docs.expo.io/versions/latest/sdk/securestore/

May I know if there is any update to this issue? Thanks.

It seems a big security concern if the app decides to store login credentials in SecureStorage, isn't it?
