### ISSUE TITLE
[expo-module-scripts] Generate a template .gitignore

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#5562]
When we run tests EMS will generate a temporary file in the `.expo` folder. We should add a step (maybe to `expo-module-configure`) to ensure that `/.expo` is always ignored.

**Comment by daltonfelipe** [comment]
> When we run tests EMS will generate a temporary file in the `.expo` folder. We should add a step (maybe to `expo-module-configure`) to ensure that `/.expo` is always ignored.

Would you just put this folder in `.gitignore` file?
