### ISSUE TITLE
Text gets truncated on the One Plus 7 Pro

### ISSUE THREAD

**Issue by ElectronicManuel** [expo/expo#5569]
### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: Linux 5.0 Pop!_OS 19.04
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
    npmPackages:
      @types/react: ^16.8.23 => 16.9.2 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.0 => 4.0.0

Phone Environment:
    OS: Android 9 (Oxygen OS 9.5.11)

I target my app for android and ios. But this issue doesn't just happen in my app, it also occurs in every other expo app, for example in the official React Navigation Example. I can also confirm that it's happening on other One Plus 7 Pros.

### Steps to Reproduce

1. Create a new app
2. Add a button with a title that is either long or has a space in it
3. (Optional): Add react-navigation and use the header bar

### Expected Behavior

You would expect that every text is displayed in its full length.

![Screenshot of android emulator](https://i.imgur.com/gxqaatu.png)

### Actual Behavior

The header bar text is truncated and ends in `...`. The Button title only displays the first part.  
I've also seen instances where a button title was truncated and ended with `-`.  
Sometimes text just ends with no indication at all.

![Screenshot of snack on one plus 7 pro](https://cdn.discordapp.com/attachments/222055221730344962/620398041886752778/temp.jpg)

### Reproducible Demo

https://snack.expo.io/@softwulf/frisky-peanut

**Comment by SaravanakumarSubramanian** [comment]
You can change the font in your code [https://github.com/facebook/react-native/issues/15114](here).one plus uses slate as their default font

**Comment by SaravanakumarSubramanian** [comment]
[https://github.com/facebook/react-native/issues/15114](Related)

**Comment by cruzach** [comment]
Looks like this is an upstream react-native issue, which you can follow [here](https://github.com/facebook/react-native/issues/25481)
