### ISSUE TITLE
Standalone app guide - warn people to be careful about bundle identifier and package name

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#557]
For many folks, this will be their first time publishing an app to app / play store. We should let them know that they won't be able to change the bundle identifier and package name and that it will show up in the url in the case of the play store.

**Comment by acomito** [comment]
I also started a checklist, which is old at this point. But I'll be updating/finishing it again soon, as I have to go through the process again this week.

https://github.com/acomito/expo-to-appstore-checklist
