### ISSUE TITLE
[docs] workflow/debugging instructions for "Virtual" Android devices also apply to physical devices

### ISSUE THREAD

**Issue by wodin** [expo/expo#5577]
The documentation says:

> ### On Android Virtual Device
> 
> Either hit `Cmd+M`, or run `adb shell input keyevent 82` in your terminal window.

However, the above `adb` command works fine on a physical device too. I'm not sure if plugging in a USB keyboard and pressing e.g. `Ctrl-M` would do anything, so not sure what the best change is, but I think the documentation should at least point out that the above `adb` command should work on physical or virtual devices.

**Comment by cruzach** [comment]
closed in #6146
👍
