### ISSUE TITLE
Cannot redirect to app with openBrowserAsync on IOS but on safari itself it works.

### ISSUE THREAD

**Issue by codGmer** [expo/expo#5579]
### Environment

  Expo CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    I use SDK 33
Its target is IOS and Android standalone.

### Steps to Reproduce

1. Using Linking.openBrowserAsync to navigate to a website.

This website should contain a redirect url back to the app in my case it is representin://

```
$(document).ready(function() {
            var baseUri = 'representin://';
            // Take the uri from the params
            var qs = decodeURIComponent(document.location.search);
            if (qs) {
                baseUri = qs.split('?linkingUri=')[1];
            }
            // Update the link urls
            setInterval(function() {
                window.location.href =
                    baseUri +
                    'message=' +
                    encodeURIComponent('Redirected automatically by timer');
            }, 1000);
        });
```

2. Wait for the page to redirect back to the app

### Expected Behavior

I expected the browser to show a dialog asking to open the app using deep linking

### Actual Behavior

I get the error "safari cannot open the page because the address is invalid".

But when I click on the safari icon right bottom corner to open the redirect page in the normal safari the prompt works fine, also deep linking is set correctly in my project because the other deep linking functionality is working fine and the redirecting back to the app works from safari itself.

The prompt telling me to open the url in the app in the normal Safari
![image](https://user-images.githubusercontent.com/25817827/64539059-0e113880-d31e-11e9-983e-822470e7155a.png)

The error message when opening with openBrowserAsync, "safari cannot open the page because the address is invalid"
![image](https://user-images.githubusercontent.com/25817827/64539078-16697380-d31e-11e9-8562-7c9d61dab57f.png)

I have tried this problem on multiple IOS devices and IOS versions, and i cleared the cache of the browsers

app.json: 

```{
  "expo": {
    "name": "Representin",
    "slug": "representin-project",
    "privacy": "public",
    "sdkVersion": "33.0.0",
    "scheme": "representin",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.5.2",
    "orientation": "portrait",
    "icon": "./assets/images/LogoRepresentin.png",
    "facebookScheme": "",
    "facebookAppId": "",
    "facebookDisplayName": "Representin",
    "splash": {
      "image": "./assets/images/splashscreen_Representin_x4.png",
      "resizeMode": "cover",
      "backgroundColor": "#000000"
    },
    "updates": {
      "fallbackToCacheTimeout": 30000,
      "enabled": true,
      "checkAutomatically": "ON_LOAD"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "com.representin.representin",
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "Geef toestemming voor jouw locatie, het aanbod van deze app wordt afgestemd op jouw omgeving"
      },
      "associatedDomains": [
        "applinks:www.representin.nl"
      ]
    },
    "android": {
      "permissions": [
        "ACCESS_FINE_LOCATION",
        "ACCESS_COARSE_LOCATION"
      ],
      "versionCode": 6,
      "package": "com.representin.representin",
      "splash": {
        "mdpi": "./assets/images/splashscreen_Representin_m.png",
        "hdpi": "./assets/images/splashscreen_Representin_x1.5.png",
        "xhdpi": "./assets/images/splashscreen_Representin_x2.png",
        "xxhdpi": "./assets/images/splashscreen_Representin_x3.png",
        "xxxhdpi": "./assets/images/splashscreen_Representin_x4.png"
      },
      "intentFilters": [
        {
          "action": "VIEW",
          "data": [
            {
              "scheme": "http",
              "host": "*.representin.nl",
              "pathPrefix": "/app"
            }
          ],
          "category": [
            "BROWSABLE",
            "DEFAULT"
          ]
        }
      ]
    },
    "description": ""
  }
}```

**Comment by cruzach** [comment]
Hi! Could you provide a full repro for this? Redirects from `WebBrowser` should work the same as [other links into your app](https://docs.expo.io/versions/latest/workflow/linking/#handling-links-into-your-app)

**Comment by karlvd** [comment]
Try using
`var baseUri = Linking.makeUrl();`
which works in both expo and stand-alone

See this example
https://github.com/expo/examples/tree/master/with-webbrowser-redirect

**Comment by mczernek** [comment]
I guess this might be expected behavior.

You are never actually leaving the app on iOS, since SFSafariViewController opens within the app. Given you haven't registered any event listener, there is nothing to notify.

Please refer to [this example](https://github.com/expo/examples/blob/master/with-webbrowser-redirect/app/App.js) for iOS implementation.
If you want to support Android, be aware of an [issue in given example](https://github.com/expo/expo/issues/5555).

Please let me know if that helps. In case it doesn't, I'll reopen the issue or create new one.
