### ISSUE TITLE
[SQLite][Typescript] compile time error:  Property '_array' does not exist on type '{ [column: string]: any; }[]'.

### ISSUE THREAD

**Issue by TvrtkoM** [expo/expo#5581]
### Environment

  Expo CLI 2.20.2 environment info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 5.3.1 - /usr/bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @types/react: ^16.8.23 => 16.9.2 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.20.2

I'm working on an app for Android currently

### Steps to Reproduce

ResultSet interface is wrong. Specifically rows property. Rows is not array. It is an object containing _array and length properties from what I've seen.

I'm trying to execute simple query `select * from table` and parse the results.

```typescript
export interface ResultSet {
    insertId?: number;
    rowsAffected: number;
    rows: Array<{
        [column: string]: any;
    }>;
}
```

When trying to access _array I get error:
```
Property '_array' does not exist on type '{ [column: string]: any; }[]'.
```

But compiled code works.

### Expected Behavior

ResultSet type is fixed in the package.

Documentation is also wrong on https://docs.expo.io/versions/latest/sdk/sqlite/
Items method is non-existing.

**Comment by ide** [comment]
I believe this will be fixed in SDK 35 with https://github.com/expo/expo/pull/5544. This is the new result set declaration:
```
export interface SQLResultSetRowList {
  length: number;
  item(index: number): any;
}
```
