### ISSUE TITLE
expo-ads-facebook - AdOptionsView on iOS crashes on click

### ISSUE THREAD

**Issue by owenhope** [expo/expo#5582]
### Environment

```
Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.10
```

iOS standalone using ExpoKit.

### Steps to Reproduce

On iOS only (Android is fine) whenever you press the AdOptionsView icons when showing a Facebook ad from the expo-ads-facebook the app abruptly crashes.

`libc++abi.dylib: terminating with uncaught exception of type NSException`

We also see these warnings on mount.

`Tried to set property 'orientation' on view manager of view 'AdOptionsView' when the view manager does not export such prop`

`Tried to set property 'iconSize' on view manager of view 'AdOptionsView' when the view manager does not export such prop`

### Expected Behavior

AdViewOptions should open with moderation options.

### Actual Behavior

App crashes with:

`libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by cruzach** [comment]
Hi! could you follow the issue template? please include your SDK version and a thorough explanation of the issue you're running into, as well as a way for us to reproduce

**Comment by owenhope** [comment]
@cruzach I have updated my question.

**Comment by owenhope** [comment]
Any update on this? Please let me know if you would like further debug information.

Cheers.

**Comment by cruzach** [comment]
Can you provide a link to a Snack or gh repo that reproduces the bug?

**Comment by iwantooxxoox** [comment]
I can confirm this issue exists

**Comment by cruzach** [comment]
Can you provide a link to a minimal example that reproduces this error?

**Comment by iwantooxxoox** [comment]
@cruzach A reproducible example needs "placementId" which generated from Facebook Audience Network and is sensitive, does it work for you to give you access permission to a private GitHub repo?

**Comment by cruzach** [comment]
Sure, or actually a better idea is to just list out the steps I can take to reproduce this on a local project

**Comment by iwantooxxoox** [comment]
@cruzach for sure, here you ago, when you press on the AdIconView, the iOS client would crash. Thanks
#### Environment
```
Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 8.13.0 - ~/.config/nvm/8.13.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.config/nvm/8.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 3.4.1
```

#### AdComponent.js
```js
import React from 'react';
import * as FacebookAds from 'expo-ads-facebook';
const {
  withNativeAd,
  AdIconView,
  AdTriggerView,
  AdMediaView,
  AdOptionsView
} = FacebookAds;

class AdComponent extends React.Component {
  render() {
    return (
      <View>
        <AdOptionsView />
        <AdIconView style={{ width: 50, height: 50 }} />
        <AdMediaView style={{ width: 160, height: 90 }} />
        <AdTriggerView>
          <Text>{this.props.nativeAd.description}</Text>
        </AdTriggerView>
      </View>
    );
  }
}
```
##### App.js
```js
export default withNativeAd(AdComponent);
 
 class MainApp extends React.Component {
   render() {
     return (
       <View>
         <AdComponent adsManager={adsManager} />
       </View>
     );
   }
 }
```

**Comment by iwantooxxoox** [comment]
@cruzach @Szymon20000 do you deed any other information?

**Comment by astoimenov** [comment]
I'm facing the same issue. Any updates?

**Comment by jm555jm** [comment]
Same problem with expo SDK 36,
And how to custom it's layout?
the icon not align center, nor with alignItem: 'center'

**Comment by KihtrakRaknas** [comment]
I am also facing the same issue. I can't find AdOptionsView in the official documentation either.

**Comment by nelsonjonq** [comment]
I have been facing this issue as well, preventing me from integrating with expo-ads-facebook. Are there any updates on the status of this?

**Comment by cruzach** [comment]
The full error message here is:
```
The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported.
```

So it seems we are not setting the `adChoicesLinkURL` properly
