### ISSUE TITLE
[MailComposer] improve error message if no Mail account set up

### ISSUE THREAD

**Issue by showcasecode** [expo/expo#5583]
### Environment

Using expo app on ios (simulator or through tunnel)

### Steps to Reproduce

run code: MailComposer.composeAsync({recipients:["showcaseteam@protonmail.com"], subject:"Showcase Support Contact"})

### Expected Behavior

open mail app

### Actual Behavior

error: mail services are not available

### Reproducible Demo
https://snack.expo.io/SkmQwSVUS

**Comment by cruzach** [comment]
I just tested your snack, and it's working for me on iPhone 7 iOS 12

Could you provide more device info?

**Comment by ide** [comment]
You might need to set up the Mail app with an email account first.

**Comment by showcasecode** [comment]
> You might need to set up the Mail app with an email account first.

OK didn't realize that it only works with apple's mail app.

**Comment by ide** [comment]
Yeah, on iOS, for operations like sending email or composing a text message or presenting a webview, you have to use Apple's app / implementation since e.g. Google is not allowed to set Gmail as the default email app, for example.

As far as Expo goes, we probably should throw a clearer error message and document this better. Even though we can't fix the underlying issue we can at least communicate it better.

**Comment by showcasecode** [comment]
I'm happy to help with a pull request

**Comment by cruzach** [comment]
I think the error message itself could be made clearer (something along the lines of- "Make sure you're signed into the Mail app")
https://github.com/expo/expo/blob/master/packages/expo-mail-composer/ios/EXMailComposer/EXMailComposer.m#L38

And also I think the [docs](https://docs.expo.io/versions/latest/sdk/mail-composer/) could also use an added note that MailComposer has to use Apple's Mail app for iOS

**Comment by showcasecode** [comment]
![IMG_1342](https://user-images.githubusercontent.com/52054658/64754079-9f85d380-d4f3-11e9-8113-31c205cb3dc7.jpg)

So it's not possible to get this functionality?

**Comment by sjchmiela** [comment]
Closed by https://github.com/expo/expo/pull/5622. 🎊
