### ISSUE TITLE
google authentication error

### ISSUE THREAD

**Issue by myavaydotcom** [expo/expo#5590]
transform[stderr]: openssl config failed: error:02001005:system library:fopen:Input/output error

I found this error right now .. I created fingerprint hash from git bash but it's not working for me

**Comment by cruzach** [comment]
Sorry, but without a lot more information it's really difficult to help you 🙁 

Take a look at our [support resources](https://github.com/expo/expo/blob/master/SUPPORT.md), and if you think this is a bug then please follow the bug report template we provide
