### ISSUE TITLE
MapView Android API key access in code

### ISSUE THREAD

**Issue by kizaonline** [expo/expo#5591]
https://docs.expo.io/versions/latest/sdk/map-view/ mentions that the google maps api key can be accessed in code via:

> Note: The API key can be accessed through your app's Constants (via Constants.manifest.android.config.googleMaps.apiKey) if you'd prefer not to have it in your code directly.

The below works when running an app via the expo client but does not work when using a built apk:

`const manifestExtra = Constants.manifest.android || {};
const config = manifestExtra.config || {};
const googleMaps = config.googleMaps || {};
const googleMapsApiKey = googleMaps.apiKey;`

Not sure if this is a docs or SDK bug

**Comment by cruzach** [comment]
When you say it doesn't work, do you mean there's no value returned for `googleMaps.apiKey`? Or is that key not working?

**Comment by kizaonline** [comment]
Sorry wasn't clear, there is no value returned `googleMaps.apiKey`

**Comment by cruzach** [comment]
That's odd. I made an SDK 34 test app with MapView recently and didn't have this problem

Could you share a full repro in a repo or snack and I can take a look/build the apk on my end?

**Comment by KemikalGeneral** [comment]
I've been having an issue with the MapView working in development, but blank (with a Google logo in the corner) when built in production for weeks now. I've asked on the Expo forum, but to no avail. 

Could this be related? If there's no key, there's no map!

**Comment by isocra** [comment]
I've got the same problem. When I run the Expo cli, my app works fine and the map is displayed, but when I build with `expo build android`, I can see int the expo build logs (and on the command line):
```
Using manifest: {"android":{"package":"com.jumptech.atom","versionCode":57},"bundledAssets":...
```
It hasn't included any of the `android.config`. In my `app.json` I've got
```
    "android": {
      "package": "com.jumptech.atom",
      "versionCode": 57,
      "config": {
        "googleMaps": {
          "apiKey": "XXXXXXXXX-XXXXXXXXX_XXXXXX_g"
        }
      }
    },
``` 
What am I doing wrong? Or what can I do about it?

**Comment by veleda3** [comment]
> I've been having an issue with the MapView working in development, but blank (with a Google logo in the corner) when built in production for weeks now. I've asked on the Expo forum, but to no avail.
> 
> Could this be related? If there's no key, there's no map!



> I've been having an issue with the MapView working in development, but blank (with a Google logo in the corner) when built in production for weeks now. I've asked on the Expo forum, but to no avail.
> 
> Could this be related? If there's no key, there's no map!

im having the same issue! MapView does not render in production android build. but it works in dev and on iphone. i followed this article to try to fix it as the app was crashing before. https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android
this was also a silent crash as sentry logs does not even catch it. i added an android config
`"config": {
        "googleMaps": {
          "apiKey": "XXXXX"
        }
      }`
 and also made sure i added the android.package name to the key retrict key use as well as a signing-certificate fingerprint that i got from running expo fetch:android:hashes on the terminal. i rebuild the app and now my doesn't crash but i get a blank google map. cant figure out how to fix this. 

 "react-native-maps": "~0.25.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
"react": "16.8.3",

**Comment by diegohenicka** [comment]
@veleda3 I have the same problem

**Comment by sakettawde** [comment]
I have the same issue as well. MapView renders blank on production app which is on play store.

I would like to add: MapView works fine if built in standalone apk file. But renders blank when android aap bundle is built and uploaded to playstore.

**Comment by cruzach** [comment]
This issue shouldn't cause the MapView to not render in your standalone app. As KizzaOnline said:

> Correct, Mapview does work, but accessing the key to use for other google map API's call's fails due to the key not being accessible via Constants

If your MapView isn't rendering, I don't think this is the main cause, and you should do some more investigation

**Comment by fabiohfab** [comment]
Hey, i have a similar problem. My map view is rendered in apk but in the app bundle for play store is not rendered.
I have a configuration in app.json android.config.googleMaps.apiKey. I use a sdk 36.0.0

**Comment by fabiohfab** [comment]
https://github.com/expo/expo/issues/2580 last asnwer works for me

**Comment by isocra** [comment]
@fabiohfab do you mean the answer from markmoomoo saying `expo fetch:android:hashes` returns the wrong SHA fingerprint?

How did you actually fix it so that the version downloaded from the Playstore has the right info?

**Comment by fabiohfab** [comment]
@isocra Yes, you need to debug in your phone, for example with logcat (https://developer.android.com/studio/command-line/logcat) and find in terminal something like " Ensure that the following Android Key exists: API Key:". Some line below you found the sha fingerprint to put in google maps api for android. I hope this helps

**Comment by cruzach** [comment]
If your map isn't rendering when in the play store, it's most likely due to this: (from the [docs](https://docs.expo.io/versions/latest/sdk/map-view/)):
> Note: If you've enabled Google Play's app signing service, you will need to grab their app signing certificate in production rather than the upload certificate returned by expo fetch:android:hashes. You can do this by grabbing the signature from Play Console -> Your App -> Release management -> App signing, and then going to the API Dashboard -> Credentials and adding the signature to your existing credential.

Otherwise, this issue is for not being able to access `android.config.googleMaps.apiKey` in code, so please keep the conversation focused on that

**Comment by cruzach** [comment]
@kizaonline what mapview methods are you using that require you to manually pass the API key?

**Comment by kizaonline** [comment]
@cruzach We are using the Google Places API (via http) to lookup addresses for a GPS location

**Comment by Tyfoods** [comment]
> I've got the same problem. When I run the Expo cli, my app works fine and the map is displayed, but when I build with `expo build android`, I can see int the expo build logs (and on the command line):
> 
> ```
> Using manifest: {"android":{"package":"com.jumptech.atom","versionCode":57},"bundledAssets":...
> ```
> 
> It hasn't included any of the `android.config`. In my `app.json` I've got
> 
> ```
>     "android": {
>       "package": "com.jumptech.atom",
>       "versionCode": 57,
>       "config": {
>         "googleMaps": {
>           "apiKey": "XXXXXXXXX-XXXXXXXXX_XXXXXX_g"
>         }
>       }
>     },
> ```
> 
> What am I doing wrong? Or what can I do about it?

I'm experiencing the same problem. I looked at the "Reading Manifest" and I do not have the config listed there. I then attempted to use Expo-Constants, just to see if the config would be present in the manifest retrieved by Expo-Constants. As one would expect, the config does not exist in the Manifest retrieved by Expo-Constants and instead returns "undefined". However, I have defined my config in app.json.

In my case, MapView doesn't render visually, if a throw an "alert" before/inside of the render, I do indeed see my alert, indicating it renders, but I don't see this visually, instead I get stuck on the "Splash Screen".

Will test SDK build, and set up Sentry to see if it catches an error.

Try installing this app on your android device: https://play.google.com/store/apps/details?id=com.tyfoodsforthought.flow_arts_meet_up

All I'm doing is returning a component which displays Constants.manifest.android and Constants.manifest.android.config.


Expo SDK ~36.0.0

**Comment by truca** [comment]
@Tyfoods I have the same issue, and been trying to follow your steps. 
I used `expo fetch:android:upload-cert` to get the upload certificate and calculated the fingerprint from that .pem file.
But I don't get how to obtain the `app signed certificate` (I've a managed app). How you got that file?

**Comment by Tyfoods** [comment]
@truca I think that's maybe the correct way to get the upload certificate. I don't totally remember, but I'm not sure that it matters. To get the app signed certificate go to your googleplay console, select your app, and then on the left side click release management, then app signing: 
![image](https://user-images.githubusercontent.com/31166839/81845024-f974e800-951d-11ea-8897-ae2471b5c763.png)

Next, you'll find both Upload Certificate, and App Signing Certificates, with their SHA-1's here!

As pictured: 
![image](https://user-images.githubusercontent.com/31166839/81845297-62f4f680-951e-11ea-8615-8cdb5879ddd1.png)

**Comment by truca** [comment]
@Tyfoods TY very much! that's really useful. One last question: I have a published app, when I do this, do I have to resubmit a new build of the app through App/Play store or I can just do an `expo publish` and it gets fixed?

**Comment by Tyfoods** [comment]
@truca I'm fairly certain that you'll have to resubmit a new build. Of course, you can test this yourself by doing the following steps:

1. Expo Publish
2. Check published app to see if the change worked, if not..
3. Resubmit the app and repeat steps 2-3 as necessary!

I'm happy to help, good luck 💯 👍

**Comment by cruzach** [comment]
The `android.config` object is not available from the manifest (it's mostly API keys so some people may want to avoid having those as part of the public manifest)

If you'd like to access this key via `Constants.manifest`, use the [`extra`](https://docs.expo.io/workflow/configuration/#extra) field of app.json
