### ISSUE TITLE
FacebookAds does not show on iOS or Android

### ISSUE THREAD

**Issue by SlayterDev** [expo/expo#5599]
### Environment

```Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.10
```

Targeting iOS and Android

### Steps to Reproduce

I am trying to show simple native facebook ads. I've set up my app in the monetization manager and gotten placement ids for both android and iOS. I'm creating a native ad manager (outside of a class if it makes a difference) and requesting 10 ads. When I pass the admanager to my component nothing shows up. Not even static text. Logging the admanager shows `isValid: false` but I can't get any other info out of it. No other errors.

### Expected Behavior

Ad text shows up in my list

### Actual Behavior

Component does not render at all

### Reproducible Demo

In App.js
```
FacebookAds.AdSettings.addTestDevice(FacebookAds.AdSettings.currentDeviceHash);
```

In my root component:

```
const adsManager = new FacebookAds.NativeAdsManager(config.FACEBOOK_PLACEMENT_ID, 10);

export default class RootComponent extends React.Component {
    render() {
        return (
            <View style={styles.container}>
                <FlatList
                    data={this.state.items}
                    renderItem={({item}) => {
                        if (item.id.includes('ad_')) {
                          return <AdItem adsManager={adsManager} />
                        }

                        return <Item 
                            checkin={item} 
                          />
                    }}
                    keyExtractor={(item, i) => item.id}
                    refreshControl={
                        <RefreshControl
                            refreshing={this.state.isLoading}
                            onRefresh={this.loadData}
                        />
                    }
                />
            </View>
        );
    }
}
```

In AdItem.js

```
class AdItem extends React.Component {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.adText}>This is an ad!</Text>
                <Text style={styles.adText}>{this.props.nativeAd.bodyText}</Text>
            </View>
        );
    }
}

export default FacebookAds.withNativeAd(AdItem);
```

**Comment by L42y** [comment]
maybe related to this: https://github.com/callstack/react-native-fbads/issues/172?

**Comment by bantingGamer** [comment]
currently experience the exact same issue with 
```
"expo": "~38.0.8",
"expo-ads-facebook": "~8.3.0" 
```

When using the **FacebookAds.withNativeAd()** HOC the component does render at all.

i also tried just loading a banner advert but i get this error: **Ad was re-loaded too frequently**

This has been a issue for a while now? is there any update to this?

**Comment by cruzach** [comment]
here's a working example of a screen making use of Facebook Ads- https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/FacebookAdsScreen.tsx

I tested that on both android and ios (android currently has a bug where the version we're using is too low, but I have a PR out to fix that).

Hopefully this example helps you to debug what the issue is here

@bantingGamer that error message is directly from the Facebook Audience Network SDK, i suggest you refer to those docs to investigate further (there's a limit on how often you can request)

**Comment by jes89** [comment]
I found BannerAd not working in my application.

So, I tried to  run [FacebookAdsScreen](https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/FacebookAdsScreen.tsx) example.

I could see the other facebook ads in my app but banner ad was not shown.

My expo sdks are "expo": "^38.0.0",  and "expo": "^39.0.0", 

and facebook sent me an email to let me know my facebook SDK is not latest one and have a problem to show.

my facebook ads sdk 5.9

latest facebook ads sdk  6.1

how can I solve this problem?

is there anything I can do?

**Comment by cruzach** [comment]
What error are you seeing in your console? https://docs.expo.io/versions/latest/sdk/facebook-ads/#troubleshooting

**Comment by jes89** [comment]
expo 38 => no fill

Ad error :( Object {
  "message": "Error Domain=com.facebook.ads.sdk Code=1001 \"No fill\" UserInfo={NSLocalizedDescription=No fill, FBAdErrorDetailKey={
    msg = \"No fill\";
}}",
  "target": 147,
  "userInfo": Object {
    "FBAdErrorDetailKey": Object {
      "msg": "No fill",
    },
    "NSLocalizedDescription": "No fill",
  },
}


expo 39 -> there is only a lot of rendering information in the error log.
