### ISSUE TITLE
exp build:ios failed on generate certificate.

### ISSUE THREAD

**Issue by 20chix** [expo/expo#560]
Hi I always fail on this step, I tried nearly 10 times and also tried with -c but nothing .

i got this.

? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? true
[exp] Generating distribution certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch distribution certificate. Request ID d9486200-8b7a-11e7-a0f2-a9731e7f3721, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by jimmylee** [comment]
Hi I'm really sorry about this, we're running into some internal issues right now where the server is out of space. We will try to resolve this as soon as possible.

**Comment by 20chix** [comment]
Could you please keep me update as i need to push my app?

p.s. android build worked fine just ios

**Comment by jimmylee** [comment]
@20chix we fixed the issue where the server was out of space, if you're still running into a build error please open another issue with the build id, since `d9486200-8b7a-11e7-a0f2-a9731e7f3721` has no logs within the last 12 hours.
