### ISSUE TITLE
Webpack Bundle Analyzer integration broken

### ISSUE THREAD

**Issue by f-o-w-l** [expo/expo#5608]
## 🐛 Bug Report

Not sure where the `expo init` example template lives, but hoping it's here and not in expo/expo-cli.

`expo diagnostics` (example project from expo init):
```
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.12.1 
```

### Steps to Reproduce

`expo init myproject`
`cd myproject && expo build:web`

### Expected Behavior

>  Expo automatically generates a `web-build/report.html` with Webpack Bundle

[Described in expo/web-examples](https://github.com/expo/web-examples/blob/master/docs/PERFORMANCE.md)

### Actual Behavior

Missing file: `web-build/report.html`

**Comment by EvanBacon** [comment]
I have removed this functionality while in beta because it can add significantly more time to the rebuilds. Please run `expo customize:web` and create a `webpack.config.js` then you can modify it to look like this:

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(
    { ...env, report: true },
    argv,
  );
  // Customize the config before returning it.
  return config;
};
```

re-running `expo build:web` will now create a `web-report/`

**Comment by EvanBacon** [comment]
I have also updated the MD that you referenced https://github.com/expo/web-examples/blob/master/docs/PERFORMANCE.md

**Comment by maxired** [comment]
> I have also updated the MD that you referenced https://github.com/expo/web-examples/blob/master/docs/PERFORMANCE.md

Hi @EvanBacon , thanks for the great work !
are you are the website doc is not up to date and still mentioned the report flag in the app.json ??
https://docs.expo.io/versions/latest/guides/web-performance/

**Comment by murbanowicz** [comment]
@EvanBacon I did follow the docs but it is not working for me.

```js
const createExpoWebpackConfigAsync = require("@expo/webpack-config");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");

module.exports = async function (env, argv) {
  const config = createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: ["@ui-kitten/components"],
      },
    },
    argv
  );

  // Optionally you can enable the bundle size report.
  // It's best to do this only with production builds because it will add noticeably more time to your builds and reloads.
  if (env.mode === "production") {
    if (!config.plugins) {
      config.plugins = [];
    }
    config.plugins.push(
      new BundleAnalyzerPlugin({
        path: "web-report",
      })
    );
  }

  return config;
};
```

I had to add plugins initialization as it was undefined.

No report etc.
