### ISSUE TITLE
Standalone app crashed in Airplane mode

### ISSUE THREAD

**Issue by jeisonng** [expo/expo#5609]
Hello I have a problem when publishing an app on google play, I need it to work offline and when I enable airplane mode, close the app and open it again, it returns me this error.

My app.json

> {
  "expo": {
    "name": "Resenha App",
    "slug": "Resenha-App",
    "privacy": "public",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 1
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "package": "com.beestart.resenhaapp",
      "versionCode": 2
  }
  }
}

![Screenshot_2019-09-11-13-57-28-112_com beestart resenhaapp](https://user-images.githubusercontent.com/40074314/64718606-f613f300-d49c-11e9-89a3-99c7591f10f5.png)
![Screenshot_2019-09-11-13-57-32-859_com beestart resenhaapp](https://user-images.githubusercontent.com/40074314/64718615-fa401080-d49c-11e9-83a6-ab444d525dc4.png)

**Comment by cruzach** [comment]
We have docs for [offline support](https://docs.expo.io/versions/latest/guides/offline-support/), specifically I'd try `setting updates.fallbackToCacheTimeout` to 0 in app.json, and either caching or bundling your assets

**Comment by adriaanbalt** [comment]
Thanks @cruzach I did the following

Note: App loads fine if I'm on the network.

1. Update app.json to include the following:
```
"updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
```
2. ran `expo build:ios` to create the `.ipa` build
3. uploaded via Application Loader to _appstoreconnect_ 
4. waiting for the build to finish processing in TestFlight.  An hour or so later it was completed
5. verified compliance and the new build became ready for testing
6. deleted my previous version of my app from my device
7. used TestFlight to install the app onto my device
8. flipped to airplane mode to test "offline" support
9. I get the following screenshot
![image1](https://user-images.githubusercontent.com/146778/65072640-4be61080-d95f-11e9-8645-d71c9c417521.jpeg)

**Comment by cruzach** [comment]
@adriaanbalt have you published your Expokit project since rebuilding? What SDK are you using?

**Comment by cruzach** [comment]
@adriaanbalt are you still seeing this issue? If not, could you share what the fix was?

**Comment by tsapeta** [comment]
Due to inactivity in this thread, I'm gonna close this issue. Feel free to reopen if you're still experiencing this in the most recent SDK — SDK38.
