### ISSUE TITLE
OkHttp version incompatiblity in detached Android app

### ISSUE THREAD

**Issue by flieks** [expo/expo#561]
i want to install 
react-native-pdf.
All is good but because expo v20 uses RN 0.47 (and not 0.48).
I get this problem
![image](https://user-images.githubusercontent.com/5032389/29770739-b0b99a36-8bf0-11e7-866e-2e3932dd204c.png)

okhttp3 of expo is not same of RN ?

**Comment by jimmylee** [comment]
I'm checking on Native Directory https://native.directory/?search=pdf and it appears that `react-native-pdf` is not compatible with Expo.

Are you trying to use that library with Expo?

**Comment by flieks** [comment]
Hi @jimmylee yes with detached Expo app. Thanks for that url, seems handy.

**Comment by daominhsangvn** [comment]
The react-native-fetch-blob also, please check if you dont mind @terribleben

**Comment by flieks** [comment]
indeed i think the react-native-fetch-blob issue is connected to it. There is a bug in RN 0.47. Let's hope it's fixed in 0.48 and then we can use fetch-blob in expo v21

**Comment by jesseruder** [comment]
@flieks can you give more information about where this error is happening? What file? Also maybe upload the file to a gist.

**Comment by flieks** [comment]
sorry i don't have that code anymore but that code was from `react-native-fetch-blob` libs i think

**Comment by dikaiosune** [comment]
Doesn't look like there's anything concrete to do here. Please comment back with more details and we'll reopen if there's a bug here. Thanks!

**Comment by flieks** [comment]
thanks but it's a react-native-fetch-blob issue not working along for now with Expo. 
I hope it gets resolved in next release of expo

**Comment by dlaynes** [comment]
Hi, thanks to the Expo team for providing us their help. Is this issue still on stand-by?
The error messages are available here:
https://github.com/wkh237/react-native-fetch-blob/issues/481

**Comment by pencilcheck** [comment]
I wonder which side should do the fix, as react-native-fetch-blob can simply merge one of the pull requests, but if expo can also update okhttp client it should also resolve that issue.

**Comment by NoerNova** [comment]
Any update for this issues? 
I get this error too on Android studio with detached app Expokit.

**Comment by peterlazar1993** [comment]
@dikaiosune @jesseruder  Here's more info about this issue, the app fails to compile with this error `/trackplayer_integration/node_modules/react-native-track-player/android/src/main/java/guichaguri/trackplayer/metadata/components/ArtworkLoader.java:45: error: incompatible types: expolib_v1.okhttp3.OkHttpClient cannot be converted to okhttp3.OkHttpClient OkHttpClient client = OkHttpClientProvider.getOkHttpClient();`

It's happening becuase of this https://github.com/react-native-kit/react-native-track-player/issues/74#issuecomment-343194816

This is the [caller](https://github.com/react-native-kit/react-native-track-player/blob/dev/android/src/main/java/guichaguri/trackplayer/metadata/components/ArtworkLoader.java#L45) and the [provider](https://github.com/expo/expo/blob/eee087141276dd2a539a62403bb811794fd24d3d/android/ReactAndroid/src/main/java/com/facebook/react/modules/network/OkHttpClientProvider.java#L30 ) returns an instance of `expolib_v1.okhttp3.OkHttpClient`

**Comment by TrillCyborg** [comment]
this is affecting me as well. any updates of the fix?

**Comment by faustoct** [comment]
this is my workaround
> in all imports referenced by `okhttp3` I replaced by `expolib_v1.okhttp3`
It worked. It's not the best solution but is working as supposed to.

https://github.com/wkh237/react-native-fetch-blob/issues/481#issuecomment-358820091

**Comment by yingdongzhang** [comment]
So does this mean there's no way to natively render PDF in Expo even detached?

**Comment by watadarkstar** [comment]
@faustoct Thanks! Works for now if anyone finds something better please post

**Comment by proguru58** [comment]
@faustoct I tried your solution and then I got the following error:

error: RNFetchBlobDefaultResp is not abstract and does not override abstract method source() in ResponseBody

in file: com/RNFetchBlob/Response/RNFetchBlobDefaultResp.java

in the following setion:

    @Override
    public BufferedSource source() {
        return Okio.buffer(new ProgressReportingSource(originalBody.source()));
    }

Can you help please? Thank you!

**Comment by proguru58** [comment]
@watadarkstar 

I have used the same solution.

Were you able to render pdf in local storage by locating the uri: file?

I am getting an error No such file or directory.

**Comment by watadarkstar** [comment]
Hi @proguru58 I dont work with pdfs just images / videos in my app. Did you figure it out?

**Comment by yingdongzhang** [comment]
@proguru58  

From what I found currently you can't render PDF natively without detaching from Expo. That's what I ended up doing and used a native module to render PDF on Android. With iOS you can use the WebView if you don't need advanced features.
