### ISSUE TITLE
[docs] Description about pedometer module 

### ISSUE THREAD

**Issue by thierrysantoos1** [expo/expo#5611]
I was searching about some modules to use native pedometer of Android and i saw that Expo has a module in expo-sensor, i saw the code implementation and see that we are using android.hardware.Sensor, but in the documentation about the module, we say that we use google fit ("Use Core Motion (iOS) or Google Fit (Android) to get the user's step count.").

We are using native sensor or google fit?

code implementation: https://github.com/expo/expo/blob/master/packages/expo-sensors/android/src/main/java/expo/modules/sensors/services/PedometerService.java

Thanks!!

**Comment by cruzach** [comment]
Looks like we used to use Google Fit in the Expo.Pedometer module, but now that we've moved that to its own `expo-sensors` package, we use the native sensor

**Comment by thierrysantoos1** [comment]
@cruzach Thanks!!
