### ISSUE TITLE
[expo-app-auth][bare] authWithConfiguration throws on Android

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#5615]
Using expo-app-auth in a bare-workflow project throws: **Failed to log in** `ExpoAppAuth.Get Auth: Missing experienceUrl in the experience Constants`

**Comment by xakep-sava** [comment]
@EvanBacon hi. Did you solve the problem?

**Comment by archieherbias** [comment]
Also experiencing this but only on Android.

**Comment by xakep-sava** [comment]
> Also experiencing this but only on Android.

I also experiencing this only on Android. Restarting the emulator or application helps me.

**Comment by archieherbias** [comment]
> I also experiencing this only on Android. Restarting the emulator or application helps me.

@xakep-sava what do you mean it helps you by restarting? Does it solve the problem? I did restart many times but that didn't help me.

**Comment by xakep-sava** [comment]
@archieherbias turn on and off the android emulator. I switched from Linux to MacOS, maybe only there this problem is solving so.

**Comment by archieherbias** [comment]
I’m using MacOS too but didn’t solve the problem.

**Comment by xakep-sava** [comment]
@archieherbias magic 🤷‍♂️

**Comment by alexyangjie** [comment]
I am having the same problem, only on Android. Using expo SDK v35 in the bare react native workflow. 

```
ExceptionsManager.js:82 Problem Error: ExpoAppAuth.Get Auth: Missing experienceUrl in the experience Constants
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:80
```

**Comment by alexyangjie** [comment]
In line 307 in `AppAuthModule.java`, it checks the `experienceUrl` if the `appOwnership` is not `standalone`. But for bare workflow, the appOwnership is `guest`. 

Changing the line to 
```java
if ("expo".equals(constantsService.getAppOwnership())) {
```
can fix the issue.

But I am not sure if there is any impact on other functions.

**Comment by JofBigHealth** [comment]
I think that's a legit fix. See here for my (uneducated) guess as to why https://github.com/expo/expo/issues/4544#issuecomment-573102166

**Comment by sushrut-desora** [comment]
> In line 307 in `AppAuthModule.java`, it checks the `experienceUrl` if the `appOwnership` is not `standalone`. But for bare workflow, the appOwnership is `guest`.
> 
> Changing the line to
> 
> ```java
> if ("expo".equals(constantsService.getAppOwnership())) {
> ```
> 
> can fix the issue.
> 
> But I am not sure if there is any impact on other functions.

Would someone detail the steps to apply this fix ? I changed the file as suggested under node-modules and did gradle clean and then re-built the app using npx react-native run-android, but that did not solve the issue

**Comment by EvanBacon** [comment]
I recommend using the new `expo-auth-session` API which has first class support for bare-workflow https://docs.expo.io/versions/latest/sdk/auth-session/ 

I will be deprecating `expo-app-auth` in favor of `expo-auth-session` in time.

**Comment by GleidsonDaniel** [comment]
> In line 307 in `AppAuthModule.java`, it checks the `experienceUrl` if the `appOwnership` is not `standalone`. But for bare workflow, the appOwnership is `guest`.
> 
> Changing the line to
> 
> ```java
> if ("expo".equals(constantsService.getAppOwnership())) {
> ```
> 
> can fix the issue.
> 
> But I am not sure if there is any impact on other functions.

Man works like a charm.

A comment about the expo, I never use it again in my life, the support is practically non-existent. Every week they change lib or have an update that breaks the project.
If you use expo and are reading this, stop using it right now ...

**Comment by emmanuelhar** [comment]
In AppAuthModule.java I have in line 317:
` if (!"standalone".equals(constantsService.getAppOwnership())) { `
If I change it to 
`if ("expo".equals(constantsService.getAppOwnership())) {`
Once I signin in the google web page, in my main app window I am redirected to google website °_°
So what is the recommended library to sign in with google from expo or react / native app ? Is it expo-auth-session ? If so please update the documentation to say that:
- https://docs.expo.io/versions/latest/sdk/google-sign-in/
- https://docs.expo.io/versions/latest/sdk/google/
are deprecated

**Comment by mirelasteve** [comment]
> 
> 
> > In line 307 in `AppAuthModule.java`, it checks the `experienceUrl` if the `appOwnership` is not `standalone`. But for bare workflow, the appOwnership is `guest`.
> > Changing the line to
> > ```java
> > if ("expo".equals(constantsService.getAppOwnership())) {
> > ```
> > 
> > 
> > can fix the issue.
> > But I am not sure if there is any impact on other functions.
> 
> Would someone detail the steps to apply this fix ? I changed the file as suggested under node-modules and did gradle clean and then re-built the app using npx react-native run-android, but that did not solve the issue

**node_modules\expo-app-auth\android\src\main\java\expo\modules\appauth\AppAuthModule.java**

**Comment by RenatoSerra22** [comment]
Having the same issue :(

**Comment by RenatoSerra22** [comment]
thank you @brentvatne, Love the expo packages they save me a lot of time.
Might be worth adding a warning that this one is no longer maintained or being deprecated so new devs can make an informed choice :)

**Comment by brentvatne** [comment]
@RenatoSerra22 - will do! we plan to deprecate expo-auth-session in sdk 41

**Comment by summerkiflain** [comment]
@brentvatne well `expo-google-app-auth` which uses `expo-app-auth` does not work (!"standalone" to "expo" fix doesn't work now) in expo sdk 41 bare workflow, its not deprecated.

**Comment by brentvatne** [comment]
see docs for indication about deprecation

<img width="1429" alt="Screen Shot 2021-06-18 at 11 19 24 AM" src="https://user-images.githubusercontent.com/90494/122602047-0ae4c980-d027-11eb-9ad7-7b120ae82973.png">

<img width="1435" alt="Screen Shot 2021-06-18 at 11 19 36 AM" src="https://user-images.githubusercontent.com/90494/122602068-12a46e00-d027-11eb-8502-e7d33c2a34b4.png">

**Comment by summerkiflain** [comment]
@brentvatne Sorry I thought deprecated meant it is supported for now but migration is recommended, wouldn't dropped support would be a better message than deprecated.

**Comment by fatikhan-gasimov** [comment]
changing

**if (!"standalone".equals(constantsService.getAppOwnership())) {**
to
**if ("expo".equals(constantsService.getAppOwnership())) {**

in **node_modules\expo-app-auth\android\src\main\java\expo\modules\appauth\AppAuthModule.java**

worked for me

**Comment by duplxey** [comment]
Did anyone manage to solve this without  changing *node_modules*?

**Comment by mgretz** [comment]
It would be a nice if that gets fixed. Until now i didnt got expo-auth-session  working either, because it has some issues with latest firebase 9.8.3.... 

See: https://github.com/expo/expo/issues/16719
