### ISSUE TITLE
react-native-calendars not rendering properly

### ISSUE THREAD

**Issue by BillyFigueroa** [expo/expo#5621]
## 🐛 Bug Report

react-native-web is not working properly with react-native-calendars.

A similar issue was opened with react-native-calendars and they suggested that an issue was opened with the expo team

[Referenced comment](https://github.com/wix/react-native-calendars/issues/839#issuecomment-499484419)

Details are given about what could be the problem

> This is most probably not an issue with react-native-calendars, but with expo / webpack config. I'm using calendars fine with my web webpack setup. react-native-calendars needs transpilation (just like most react-native libraries), so I guess your webpack babel rule needs to be told to include node_modules/react-native-calendars for transpilation. If I was you, I'd close this issue and open a new one in the expo community.

### Environment

```bash
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.2 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.10
```

The target with the problem is `web`. `ios` and `android` are both working fine

### Steps to Reproduce

use `react-native-calendars` with `react-native-web` on `expo`

### Expected Behavior

The calendar should look like this (ios pictured)

![error](https://user-images.githubusercontent.com/1371105/64753094-ed004180-d4ef-11e9-8101-711ff8353180.jpg)

### Actual Behavior

This is what it looks like on web

![Screen Shot 2019-09-11 at 11 48 52 PM](https://user-images.githubusercontent.com/1371105/64753116-030e0200-d4f0-11e9-9512-def9266346ce.png)

The dates section is not working and the expand bar does not do anything

### Reproducible Demo
I created a snack for expo
[expo snack](https://snack.expo.io/@mintgroomingapp/react-native-calendars-expo-web)

**Comment by bkniffler** [comment]
Try updating your babel config file by adding `@babel/plugin-proposal-class-properties`. In case of .babelrc

```
{
  "presets": ["babel-preset-expo"],
  "plugins": [
        "@babel/plugin-proposal-class-properties"
   ]
}
```

**Comment by BillyFigueroa** [comment]
@bkniffler that was not my original thread. I just added to it. The original post was by a different user and he was the one who had that issue with the class-properties

[original post](https://github.com/wix/react-native-calendars/issues/839#issue-451562786)

**Comment by bkniffler** [comment]
Ah, sorry, my bad, I totally missed that you weren't the one with the original issue and so I didn't read your issue properly. This is indeed an interesting issue, I'll look if I can reproduce in my web project. Though, compared to the original issue of @ceribbo, this issue is surely related to react-native-calendars, or at least with react-native-web. Sorry for misunderstand :( 

Can you copy & paste this in a new issue to react-native-calendars and ping me? I'll check it out in the next days, since I relate on react-native-calendars a lot in a hybrid expo native/web app, I'm interested in this.

**Comment by BillyFigueroa** [comment]
I just added a reproduce-able demo

[here](https://snack.expo.io/@mintgroomingapp/react-native-calendars-expo-web)

**Comment by bkniffler** [comment]
Nice, I guess this here can be closed then, I'm sure its not related to expo but some issue with how react-native-calendars handles press event on the expander and some styling issues that do not seem to transfer well to web.

**Comment by EvanBacon** [comment]
I agree that this would require source changes in `react-native-calendar` to be fully resolved.
