### ISSUE TITLE
Expo standalone app on Android TV show Home Screen with Expo Brand icon when re-open

### ISSUE THREAD

**Issue by lucifekit** [expo/expo#5624]
Hi, i have developed an expo app, built a standalone apk and install on my Android TV.

After installed, my app is running well, support the tv remote well.

But the problem is when i press home, or back to tv home screen, and go back to my app, it show a white screen with expo brand icon in center, then stuck there forever.

**So what do i need to do to make my app resume, or make my app open like when i install it ?** 

Now everytime i exit my app i have to reinstall it again. I read react document about tv support and it say i have to do something with my androidmanifest.xml, adding leanback_launcher or something, but when i extract my standalone app apk the intent filter leanback_launcher already there, which point to the HomeActivity, not the MainActivity. I think this is where the problem occur. I dont want to eject my app to android and edit it everytime i modified my app. Maybe there is someway in edit app.json, or whatever way please help me?

**Comment by lucifekit** [comment]
My app work fine on Android mobile devices. It only happen on Android TV ( Im using Nvidia Shield )

Yes, i have configured my app's splashscreen, but i dont think that is the problem, app should work with or without splashscreen.

Environment
Expo CLI 3.0.10 environment info:
System:
OS: Window 7
Binaries:
Node: 12.10.0 - 
npm: 4.6.1

Target: Android

package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^34.0.0",
    "npm": "^6.4.1",
    "react": "^16.6.0-alpha.8af6728",
    "react-mixin": "^4.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-cookie": "^0.2.0",
    "react-native-easy-toast": "^1.2.0",
    "react-native-gesture-handler": "^1.2.2",
    "react-native-iphone-x-helper": "^1.2.0",
    "react-native-slider": "^0.11.0",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-tab-navigator": "^0.3.4",
    "react-navigation": "^1.5.9",
    "react-timer-mixin": "^0.13.3",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "schedule": "^0.4.0"
  }
}



Demo : 

https://github.com/lucifekit/tv-demo/tree/master/tv-demo

Install it on android tv (shield tv), open it, you should see the red screen with text "loading screen", then press home to go exit to device home screen, then open it back, now you will see white screen with expo brand icon in center, then stop at that.

**Comment by lucifekit** [comment]
Image : http//imgur.com/a/L2HevRf

**Comment by lucifekit** [comment]
Hi, i have video and apk files for repro here :

https://drive.google.com/open?id=14dP7WlL51W7fRZZh0KxKRPF1deTuRv8r

**Comment by lucifekit** [comment]
FYI, if i eject the project, clone the MainActivity to TvActitvity, add an action to AndroidManifest.xml and make some adjustment to exclude 'expo' from the project, my app can now run on android Tv and not show the blank white screen anymore. ( I cant use the Updates and ScreenOrientation from Expo )

But i hope my process will be integrated to expo core in the next SDK so i dont have to eject my project and can use expo Updates and ScreenOrientation module:(.

**Comment by cruzach** [comment]
Hey @lucifekit ! Good news, you can now use [ScreenOrientation](https://docs.expo.io/versions/latest/sdk/screen-orientation/) and [Updates](https://docs.expo.io/versions/latest/sdk/updates/) in bare workflow apps! Just follow the instructions for installing/configuring each from those documentation pages. I'm going to close this issue now, but let me know if you have any other problems! Hope you android TV app is coming along well 👍

**Comment by PrabinKarki03** [comment]
I am developing expo app for android tv but when i install apk file on android tv it gets crash after white screen.
how can i find issue about this ? how to solve this problem
