### ISSUE TITLE
Building Expokit 34 ExpoClient and Npm package

### ISSUE THREAD

**Issue by timdelange** [expo/expo#5626]
## 🐛 Bug Report

I would like to modify expokit, specifically add some headers to the request that fetches the manifest.  I found it simple under sdk30 earlier to build, but I am having trouble making an updated expokit npm package under sdk 34.

I clone http://github.com/expo/expo
Then I checkout sdk-34
I run yarn in tools/ and tools-public/
I run yarn in /
I then run "./gradlew assemble" in android.

It runs for a while and fails on:

> Task :expo-branch:compileDebugJavaWithJavac FAILED
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/tim/dev/expo/packages/expo-branch/android/src/main/java/expo/modules/branch/BranchPackage.java:16: error: BranchPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class BranchPackage extends BasePackage implements ReactPackage {
       ^
Note: /Users/tim/dev/expo/packages/expo-branch/android/src/main/java/expo/modules/branch/vendored/RNBranchModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/tim/dev/expo/packages/expo-branch/android/src/main/java/expo/modules/branch/vendored/AgingHash.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
3 warnings

2: Task failed with an exception.
-----------
* What went wrong:
Could not resolve all files for configuration ':expoview-abi33_0_0:debugCompileClasspath'.
> Could not resolve com.facebook.soloader:soloader:0.6.0.
  Required by:
      project :expoview-abi33_0_0
   > Cannot find a version of 'com.facebook.soloader:soloader' that satisfies the version constraints: 
        Dependency path 'android:expoview-abi33_0_0:unspecified' --> 'com.facebook.soloader:soloader:0.6.0'
        Constraint path 'android:expoview-abi33_0_0:unspecified' --> 'com.facebook.soloader:soloader' strictly '0.5.0' because of the following reason: debugRuntimeClasspath uses version 0.5.0

### Environment

<!-- Please also let us know about your app's target (iOS, Android, Client, Standalone, ExpoKit) 

### Steps to Reproduce

git clone http://github.com/expo/expo
cd expo
git checkout sdk-34
yarn
cd tools
yarn
cd tools-public
yarn
cd ../android
./gradlew assemble

### Expected Behavior

Projects  should build

### Actual Behavior

Build fails

**Comment by AdamJNavarro** [comment]
Hey @timdelange,

Seeing as we haven't heard back from you, I'm going to close this issue. If you followed the the readme steps that Charlie linked to and are still encountering issues, please feel free to create a [forum post](https://forums.expo.io/) and we'll do our best to help!

Cheers,
Adam
