### ISSUE TITLE
[docs] Managing different action by clicking on a notification and buttons

### ISSUE THREAD

**Issue by jonathanatn** [expo/expo#5640]
I don't find anywhere in the documentation how to do specific action when the user click on a notification.

For example when users click on notifications I want to send them on a specific page, not just open the app.

Hand also how to add some buttons in the notification that send different actions.

Maybe it's just not possible for the moment.

**Comment by cruzach** [comment]
I think what you're looking for in regards to adding buttons/responses on notifications is [Notification Categories](https://docs.expo.io/versions/latest/sdk/notifications/#notification-categories)

For sending the user to a specific page, you can send `data` in your notification, and then handle the data in whichever way you choose (like navigating to a certain screen based on what that data is) in your [notification listener](https://docs.expo.io/versions/latest/sdk/notifications/#subscribing-to-notifications)
