### ISSUE TITLE
npm install expo-apple-authentication returns 404 not found.

### ISSUE THREAD

**Issue by cuttlas** [expo/expo#5643]
I was trying the standalone package for [apple-autentication](https://github.com/expo/expo/tree/master/packages/expo-apple-authentication) but the "npm install expo-apple-authentication" command returns a 404 Not Found. Isn't the package publish yet? Are the docs not correct?

Thanks.

**Comment by ide** [comment]
This will be published with SDK 35. We are aiming to release that SDK before iOS 13 is generally available on September 19.
