### ISSUE TITLE
Expokit - Missing Library folder in Xcode

### ISSUE THREAD

**Issue by therhapzody** [expo/expo#5650]
I've been using Expo and recently had to eject the project to Expokit so that I can have the tipsi-stripe package installed.

Unfortunately, I cannot proceed with manual linking as I don't see any Library folder in Xcode.

Anybody here with the same issue? How did you solve this?

**Comment by domhacking** [comment]
Same here

**Comment by tsapeta** [comment]
We no longer support ExpoKit so I encourage you to use bare workflow instead. If this issue still exists in bare workflow then please open a new bug report with more details about your dependencies and errors that you're having.
