### ISSUE TITLE
Migrate AsyncStorage to ReactNative (iOS), losing old data

### ISSUE THREAD

**Issue by charlyBerthet** [expo/expo#5651]
## 🐛 Bug Report
I wanted to migrate from ejected Expo to the last react native version and figured out expo do not use the same directory path as ReactNative Core so migration from Expo to React Native Community result in a lost of my local stored data.

Here Expo directory name (@"RCTAsyncLocalStorage"): https://github.com/expo/expo/blob/15a7ff76abb149962b1c42f617ca97d3f6c98021/ios/Exponent/Versioned/Core/EXVersionManager.m#L348

Here ReactNative Core directory name (@"RCTAsyncLocalStorage_V1"):
https://github.com/facebook/react-native/blob/ce0ad9f7121c70b1dd27508910156ecc95b6f10c/React/Modules/RCTAsyncLocalStorage.m#L20

Here ReactNative Community migration PR:
https://github.com/react-native-community/async-storage/commit/8d275ad706c27962f71849119bc0f1be811a375e#diff-54c57f4041d9a698ab027d21344b6e63

Why do you use @"RCTAsyncLocalStorage" instead of @"RCTAsyncLocalStorage_V1"?

### Expected Behavior

Do not lose local stored data once migrated to https://github.com/react-native-community/async-storage.

### Actual Behavior

Keep local stored data once migrated to https://github.com/react-native-community/async-storage.

**Comment by jaquan1227** [comment]
same issue here

**Comment by burivuhster** [comment]
Hey guys, just in case any of you are still looking for a solution.

I faced the same issue when I was rewriting my app from ExpoKit (SDK 31) to the bare Expo workflow and SDK 35.
I solve it by accessing an old documentDirectory via FileSystem API and copying all the content with manual migration code.

Here is a piece of code to give you an idea:
```
import * as FileSystem from 'expo-file-system';
import AsyncStorage from '@react-native-community/async-storage';

const oldDocumentDirectory =
    FileSystem.documentDirectory +
    'ExponentExperienceData/' +
    encodeURIComponent('%40burivuh%2Fmy-app-expo-slug') +
    '/';

export async function migrate() {
    const oldDocumentDirectoryContents = await FileSystem.readDirectoryAsync(
        oldDocumentDirectory
    );

    for(let itemUri of oldDocumentDirectoryContents) {
        let result = await FileSystem.moveAsync({
            from: oldDocumentDirectory + itemUri,
            to: FileSystem.documentDirectory + itemUri
        });
    }

    // Migrate AsyncStorage
    // old AsyncStorage (from Expo) was using directory "RCTAsyncLocalStorage" under documentDirectory
    // new AsyncStorage (from @react-native-community/async-storage) uses "RCTAsyncLocalStorage_V1"
    const oldAsyncStorageInfo = await FileSystem.getInfoAsync(
        FileSystem.documentDirectory + 'RCTAsyncLocalStorage/manifest.json'
    );
    if (oldAsyncStorageInfo && oldAsyncStorageInfo.exists) {
        const oldAsyncStorageContents = await FileSystem.readAsStringAsync(FileSystem.documentDirectory + 'RCTAsyncLocalStorage/manifest.json');
        const oldAsyncStorageObj = JSON.parse(oldAsyncStorageContents);

        if(oldAsyncStorageObj) {
            // Copy all the data you need from the old AsyncStorage, in my case it was "settings"
            if (oldAsyncStorageObj.settings) {
                await AsyncStorage.setItem('settings', oldAsyncStorageObj.settings);
            }
        }
    }

    // Save a flag in AsyncStorage that migration was completed
    await AsyncStorage.setItem('migration-from-expo-31-completed', true);

    console.log('Migration from Expo 31 completed');
    return true;
}
```

**Disclaimer:** didn't release it to production yet, please review it carefully and test it first and use it with caution.

**Comment by solace** [comment]
@burivuhster Hi, out of interest, have you tried this in TestFlight?

**Comment by burivuhster** [comment]
@solace Yes, and the update with data migration code is in production since yesterday. But I enabled phased release, so only a couple of real users were updated to this moment. So far so good.
I discovered that AsyncStorage is a bit more complicated than I expected, I'll edit the code above.

**Comment by solace** [comment]
@burivuhster Good to know, thanks. I'm trying to upgrade from SDK 32 to bare and I'm finding the data is lost when I attempt to inspect the ExponentExperienceData manifest file. It works fine in the simulator but on TestFlight there is no data. Did you follow a specific guide, or do you have steps for transitioning to bare? I feel like I'm missing something critical here that's causing the data to not be there. Switching back down to an older version shows the old data, so it's still there, just not accessible by the bare version.

**Comment by burivuhster** [comment]
@solace I didn't find any guides, that's why I decided to share my experience here. Please note that AsyncStorage saves values in separate files when the value length is more than 1024 bytes. And it keeps a null value in manifest.json in this case.

**Comment by solace** [comment]
@burivuhster That note about AsyncStorage saving values in different files was the key to my issue. Thanks!
