### ISSUE TITLE
Expo Google.logInAsync does not redirect back to app

### ISSUE THREAD

**Issue by jitenderchand1** [expo/expo#5652]
### Environment

 Expo CLI 2.21.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.9 => 0.59.9 
      react-navigation: ^3.11.0 => 3.11.0 

Android, Standalone
Android version : 6.0.1

### Steps to Reproduce

use Goggle from expo and use 

```
const result = await Google.logInAsync({
        androidStandaloneAppClientId:
          'client key,
        iosStandaloneAppClientId:
          'client key,
        scopes: ['profile', 'email'],
        behavior: 'web'
      });
``` 

I have defined all the step I have done so far in [here](https://stackoverflow.com/questions/57946590/expo-google-login-redirect-to-google-home-page)

### Expected Behavior

It should redirect to app home page

### Actual Behavior

In standalone android app on the real device, after giving valid crendential it does not redirect back to the app. Its redirect to google home page.

### Reproducible Demo

**step 1**

![Screenshot_20190915-220957](https://user-images.githubusercontent.com/19687185/64925799-e848cf80-d806-11e9-9e71-218a32bd85cb.png)

**step 2**

![ScreenCaptures_2019-09-15-221049](https://user-images.githubusercontent.com/19687185/64925798-e7b03900-d806-11e9-8046-d1ed25d6b94a.png)

**step 3** 
After entering the password 

![Screenshot_20190915-221111](https://user-images.githubusercontent.com/19687185/64925826-3b228700-d807-11e9-9801-4a3e79a88ad2.png)

**current behavior**

![Screenshot_20190915-203459](https://user-images.githubusercontent.com/19687185/64925825-3a89f080-d807-11e9-840f-ed2122192c5e.png)

expected 
It should redirect to app

**Comment by FloDev974** [comment]
I have the same problem did you find the solution?

**Comment by jitenderchand1** [comment]
I manage to fix it. below is what I did.

`import * as AppAuth from 'expo-app-auth';`

```
const result = await Google.logInAsync({
        androidStandaloneAppClientId:
          'myKey,
        iosStandaloneAppClientId:
          'myKey,
        scopes: ['profile', 'email'],
        behavior: 'web',
        redirectUrl: `${AppAuth.OAuthRedirect}:/oauthredirect`
      });
```
Hope this help

**Comment by FloDev974** [comment]
thanks @jitenderchand1
