### ISSUE TITLE
Expo 34 Issue: Invariant Violation

### ISSUE THREAD

**Issue by therhapzody** [expo/expo#5653]
Please provide the following:
1. SDK Version: 34
2. Platforms(Android/iOS/web/all): Android/iOS

I just upgraded from version 33 to 34 and got the following error:

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

This error is located at:
    in RCTView
    in l
    in Styled(l)
    in RCTView
    in l
    in Styled(l)
    in n
    in p
    in RCTView
    in u
    in RCTView
    in u
    in n
    in o
    in E
    in RCTView
    in n
    in RCTView
    in u
    in PanGestureHandler
    in n
    in L
    in RCTView
    in n
    in t
    in C
    in v
    in p
    in RCTView
    in RCTView
    in l
    in RCTView
    in n
    in RCTView
    in u
    in RCTView
    in u
    in PanGestureHandler
    in n
    in S
    in C
    in p
    in p
    in C
    in P
    in n
    in v
    in RCTView
    in RCTView
    in c

nn
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:26115
f
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:34102
m
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:35374
Ur
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:44607
Qr
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:52488
na
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:72881
ra
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:73371
Oa
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:80972
Wa
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:80310
Aa
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:79323
sa
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:78013
enqueueSetState
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:96:29425
setState
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:65:2231
dispatch
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:740:1477
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:702:741
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:1102:730
f
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:45:155
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:45:882
y
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:119:657
C
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:119:1021
callImmediates
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:119:3216
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:31:2873
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:31:1264
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:31:2565
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:31:1234

I have been trying to resolve this, but could not find a solution. downgrading to version 33 works fine.
Any ideas on how this could be solved?

**Comment by dellwatson** [comment]
same, just upgraded from sdk 32, fix another issue and then come this one, i have no clue on google searching.

**Comment by AdamJNavarro** [comment]
Hey all, could you share your `app.json` and `package.json`?

**Comment by dellwatson** [comment]
Ok i fixed it, 

I forgot to change all expo module from previous 
import { imagePicker, etc } from 'expo'

to

import { LinearGradient } from 'expo-linear-gradient'
import * as ImagePicker from 'expo-image-picker';
etc... 


but i dont know with your situation, if I'm not wrong, the sdk 33 already use this system right ?
they already no longer use 'expo' but deprecated to individual module ??

**Comment by therhapzody** [comment]
After spending a bit of time, following fixed the issue:

1 - Downgraded to expo 33
2 - Follow the steps for expo 34 update
3 - npm/yarn Install specific packages where any error is shown
4 - Run ‘npx expo-codemod sdk33-imports’ --> I think this is exactly what solved the issue.

https://www.npmjs.com/package/expo-codemod
