### ISSUE TITLE
Default method desugaring of `org.unimodules.adapters.react.views.SimpleViewManagerAdapter` failed because its super class `com.facebook.react.uimanager.SimpleViewManager` is missing

### ISSUE THREAD

**Issue by pencilcheck** [expo/expo#5654]
### Environment

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.2 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: 1.0.0-beta.23 => 1.0.0-beta.23
    npmGlobalPackages:
      expo-cli: 3.0.10

ExpoKit

### Steps to Reproduce

Trying to upgrade SDK 30 to 34, made a lot of changes, now getting this error.

### Expected Behavior

Should just work

### Actual Behavior

Getting error about: `Default method desugaring of `org.unimodules.adapters.react.views.SimpleViewManagerAdapter` failed because its super class `com.facebook.react.uimanager.SimpleViewManager` is missing`
For task
`> Transform artifact full.jar (project :unimodules-react-native-adapter) with DexingWithClasspathTransform`

**Comment by pencilcheck** [comment]
The issue seems to remove itself somehow...

**Comment by 28harishkumar** [comment]
How does it resolved? I am still getting this error

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
      Memory: 343.75 MB / 7.68 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Error is:

```
> Transform artifact full.jar (project :unimodules-react-native-adapter) with DexingWithClasspathTransform
AGPBI: {"kind":"error","text":"Default method desugaring of `org.unimodules.adapters.react.views.SimpleViewManagerAdapter` failed because its super class `com.facebook.react.uimanager.SimpleViewManager` is missing","sources":[{}],"tool":"D8"}

> Task :app:mergeLibDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'full.jar (project :unimodules-react-native-adapter)' to match attributes {artifactType=android-dex, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.api.attributes.VariantAttr=debug, com.android.build.gradle.internal.dependency.AndroidTypeAttr=Aar, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /home/harish/workspace/LyflinkDoctor/node_modules/@unimodules/react-native-adapter/android/build/intermediates/full_jar/debug/createFullJarDebug/full.jar.
         > Error while dexing.
```

**Comment by longzhi** [comment]
@pencilcheck Did you resolve it?

**Comment by sjchmiela** [comment]
I have just encountered this too in the process of upgrading our Expo project to latest Android Studio/Gradle. I'm not yet sure what caused it and how to solve it. Will keep you updated.

**Comment by connorpmullins** [comment]
I'm running into the same issue.

**Comment by JacopoKenzo** [comment]
Same error here - new Bare project coming from latest Expo
Android Studio and Gradle updated to latest version

**Comment by JacopoKenzo** [comment]
Changed "Android Gradle Plugin Version" to 3.4.0 in Android Studio > File > Project Structure and seems to be working now.
Gradle Version still at 5.4.1

**Comment by longzhi** [comment]
Great, it works now. Thanks.

**Comment by MarijanaScarlet** [comment]
> Changed "Android Gradle Plugin Version" to 3.4.0 in Android Studio > File > Project Structure and seems to be working now.
> Gradle Version still at 5.4.1

Thank you so so so much !

**Comment by zongxiaomi** [comment]
look up your `build.gradle` is has the code

> configurations.all {
    exclude group: "om.facebook.react", module: "xxx"
}
if (has)
   delete
else
  看上面的答案
