### ISSUE TITLE
VideoThumbnails: Error: Can't read file

### ISSUE THREAD

**Issue by maharjanaman** [expo/expo#5657]
I'm unable to generate thumbnails for the uri which I took using `ImagePicker`. I'm using same code as documented in expo docs.

P.S. it works on iOS.

**Comment by AdamJNavarro** [comment]
Hey @maharjanaman,

I know you said you're using the code documented in our docs, but could you still provide all your relevant code in a [Snack](snack.expo.io)? While I believe you, seeing the code removes any uncertainty of an accidental typo, forgotten change, etc. Also seeing your ImagePicker code in conjunction with the `VideoThumbnails` module is important here.

Cheers,
Adam

**Comment by maharjanaman** [comment]
Hy @AdamJNavarro, sorry about that. Here is the code I implemented on real app.
This is method for picking images/videos;
```
handleAssetUpload = async () => {
    const permission = await Permissions.getAsync(Permissions.CAMERA_ROLL);
    if (permission.status !== "granted") {
      const newPermission = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (newPermission.status !== "granted") {
        return Alert.alert(
          "Permission Denied",
          "This app needs permission to access media files.",
          [{ text: "OK" }],
          { cancelable: false }
        );
      }
    }

    try {
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.All
      });

      if (!result.cancelled) {
        let videoThumbnail;

        if (result.type === "video") {
          videoThumbnail = await this.getThumbNail(result.uri);
        }

        this.formPostData(result.uri, videoThumbnail, result.type);
      }
    } catch (error) {
      throw error;
    }
  };
```

And then I add `getThumbNail` method to get video thumbnail if asset pick is of `video` type
```
getThumbNail = async videoUri => {
    try {
      const { uri } = await VideoThumbnails.getThumbnailAsync(videoUri, {
        time: 5000
      });
      return uri;
    } catch (e) {
      throw e;
    }
  };
```

**Comment by lukmccall** [comment]
@maharjanaman, when you try to generate a thumbnail, do you get any errors/exceptions?
