### ISSUE TITLE
undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants')

### ISSUE THREAD

**Issue by vinils** [expo/expo#566]
![image](https://user-images.githubusercontent.com/14332724/29825060-975a15b6-8ca9-11e7-89ed-30f9467fdb5e.png)

Getting red screen of death with undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants') on Android

related to https://github.com/react-native-community/react-native-video/issues/184

**Comment by skevy** [comment]
Please provide a code example, and possibly a repro on snack.expo.io.

**Comment by custam** [comment]
I solved it by installing react-native-video with pods :
1) install pods
2) add this to your podfile is ios folder of your project : 
`pod 'react-native-video', path: '../node_modules/react-native-video'`
3) launch pod install
4) maybe delete the "-obj" in the "target support files" of file "pods". You can find it by opening your xcworkspace file in xcode.
5) rerun your project

**Comment by andresmtz98** [comment]
Hi. How can i do this on Windows 10?

**Comment by roxguel** [comment]
> Hi. How can i do this on Windows 10?

Me hago la misma pregunta
_I ask myself the same question_
