### ISSUE TITLE
Tap focus in camera module

### ISSUE THREAD

**Issue by valdezcervera** [expo/expo#5661]
Hi,

When I run the Expo ["camera" module](https://docs.expo.io/versions/v34.0.0/sdk/camera/) I can't access the native focus on tap from the phone.

Is this intentional or a bug?

I've seen there seems to be an open feature request @EvanBacon that might be related to this here:
https://expo.canny.io/feature-requests/p/camera-focus-at-point-on-touch

@terribleben @brentvatne @ide @sjchmiela @esamelson @tsapeta in case this feature is missing, would you guys like for me to work on a PR to include it in Expo?

Look forward to hearing from you, thanks!

**Comment by AdamJNavarro** [comment]
Hey @valdezcervera,

We don't have tap-to-focus implemented yet, but we are always open to PRs. We're currently getting ready to release a new version of the SDK so it will likely be a bit before anyone would be able to review it. Do me a favor and email adamjnav@expo.io and I'll get you in contact with those who have the most experience with the Camera module.

Also, please refrain from pinging a ton of people in issues. It causes unnecessary distractions for the team and creates extra noise. I'm going to close this issue as we try to reserve github issues for reproducible bugs.

Cheers,
Adam
