### ISSUE TITLE
Add an initialization option of Segment

### ISSUE THREAD

**Issue by indiev** [expo/expo#5665]
Hello.
In Segment, there is an option to set 'trackApplicationLifecycleEvents' and 'recordScreenViews'.
It would be nice to pass options in the initialization phase and allow them to be set.

'trackApplicationLifecycleEvents' option is necessary for Facebook App event tracking.

**Comment by AdamJNavarro** [comment]
Hey @indiev,

We try our best to reserve Github Issues for reproducible bugs. For feature requests such as this one, we'd love it if you could create a one on our [Canny Board](https://expo.canny.io/feature-requests).

Cheers,
Adam
