### ISSUE TITLE
Can't get precise address with expo-locations

### ISSUE THREAD

**Issue by GNPhoque** [expo/expo#5667]
Expo 34.0.1, expo-location : 6.0.0, react-native-web:0.11.4, react: 16.8.3

I managed to get a google maps running on my app, clicking on the map gives me an object containing lat/long functions to get gps position of where I click.

When I try to reverse geocode this gps position, the output I get is an array of 6-11 objects containing only the city, region, country, postal code, and sometiomes name (for places) so I cannot get specific address back from it.

Any idea what I could do?

Sample code : 
```
componentDidMount(){
    Location.requestPermissionsAsync();
    Location.setApiKey(MY_KEY) //might actually need advice to secure this part too :3
  }

  _attemptReverseGeocodeAsync = async (coords) => {
    try {
      let result = await Location.reverseGeocodeAsync(coords);
      console.log(result[0].street) //undefined
      return result;
    } catch (e) {
      return e;
    }
  };

  onPress = (position) => {
    const coords = {latitude:position.latLng.lat(), longitude:position.latLng.lng()};
    console.log("coords", coords);
    this._attemptReverseGeocodeAsync(coords).then(result => {
      console.log('result',result);
    })
    .catch((error)=> {
      console.log('error',error);
    })
}
```

Which gives this : 
![image](https://user-images.githubusercontent.com/26761057/65041862-fa865300-d957-11e9-9c7b-347fa0110229.png)

This was based on a snack which works on expo v32.0.0 on android : 
https://snack.expo.io/S1AGp7AIr

**Comment by AdamJNavarro** [comment]
Hey @GNPhoque,

Thanks for the detailed report here. Can you let me know what platforms this is occurring on? I see you mention Android at the end but I'd like to be sure.

Cheers,
Adam

**Comment by GNPhoque** [comment]
Hello @AdamJNavarro ,
The working state is on android, using the linked snack.
But when using expo 34+ on web, it gives me only up to City precision.
By the way, I currently switched to using locationiq 's api to get full address for the moment.

**Comment by karimcambridge** [comment]
No matter what I do, I continue to get my country or a highway in the Caribbean, when I place a marker anywhere on the island

```pinPointingLocationState Array [
  Object {
    "city": null,
    "country": "Saint Vincent and the Grenadines",
    "isoCountryCode": "VC",
    "name": "Saint Vincent and the Grenadines",
    "postalCode": null,
    "region": "Saint Vincent and the Grenadines",
    "street": null,
  },
```
