### ISSUE TITLE
Keeps reloading only when in prod mode (after publishing)?

### ISSUE THREAD

**Issue by cmeehanSL** [expo/expo#567]
I am trying to use the crypto-js encryption library, and everything works fine in XDE when just sharing a QR code (\__DEV__ is true). However, once I publish, when the app reaches the stage where this encryption occurs, it just reloads the bundle again.

The encryption code is basically:

`   var encryptedText = CryptoJS.AES.encrypt(text, key)
`

Does anyone know why this won't work when published, but is fine when not?

Thanks!

**Comment by dikaiosune** [comment]
Can you try enabling production mode in your local XDE copy? I believe you can do so by unchecking "Development mode" under the gear icon in XDE.
