### ISSUE TITLE
[docs] Guide and API reference for unimodule authoring

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#5674]
Currently we don't have comprehensive documentation around how to write a module using the unimodule api. We have: https://github.com/expo/expo/blob/master/packages/@unimodules/core/README.md and https://github.com/expo/expo/blob/master/packages/@unimodules/react-native-adapter/README.md to provide actual info on API usage and https://github.com/expo/expo/blob/master/guides/Expo%20Universal%20Module%20Infrastructure.md and https://github.com/expo/expo/blob/master/guides/Creating%20Universal%20Modules.md for explaining how to create unimodules within the monorepo.

In addition to improving the API reference, we should have guides like this:
- https://facebook.github.io/react-native/docs/native-modules-ios
- https://facebook.github.io/react-native/docs/native-components-ios
- https://facebook.github.io/react-native/docs/native-modules-android
- https://facebook.github.io/react-native/docs/native-components-android

**Comment by EvanBacon** [comment]
Completed in https://github.com/expo/expo/pull/15261
