### ISSUE TITLE
[docs] Download and setup bug Missing Cocoapods

### ISSUE THREAD

**Issue by zoruc** [expo/expo#5676]
In step 4 where you run ```yarn ios``` I received an error of ```ERROR: Missing CocoaPods installation. Run 'sudo gem install cocoapods --pre' to install``` should this be part of the install scripts vs a separate command?

**Comment by AdamJNavarro** [comment]
Hey zoruc,

I'm not entirely sure what step you are referring to in the docs, but we do make mention of needing to install Cocoapods [here](https://docs.expo.io/versions/v35.0.0/bare/hello-world/#ios-configuration). If there is somewhere else you think it would benefit to mention this, we would welcome a PR to the docs!

Cheers,
Adam
