### ISSUE TITLE
20.0.0 is not a valid SDK version on Android only.

### ISSUE THREAD

**Issue by waynebloss** [expo/expo#568]
After updating to SDK 20 and opening my app in Expo/Android, I receive the following error:

```
Uncaught Error: 20.0.0 is not a valid SDK version.
Options are 19.0.0, 18.0.0, 17.0.0, 16.0.0, 15.0.0, 
14.0.0, 13.0.0, UNVERSIONED.
Time: 7:38:32 Fatal Error
```

The same app works in Expo/iOS.

**Comment by skevy** [comment]
Is this on device or on simulator? Can you try removing the Expo app and reinstalling it?

**Comment by waynebloss** [comment]
Re-installing Expo on the device worked.

**Comment by jimmylee** [comment]
Nice @waynebloss I'm going to close this then :D

**Comment by JoeRoddy** [comment]
Just in case anyone comes here on an emulator. I was using an Android emulator and had the same issue.  Manually uninstalling Expo from the emulator and then restarting the app worked.

It must reserve a new version of Expo, but only if it isn't already on the emulator.

**Comment by UmarAdkham** [comment]
Yeah true. Reinstalling works. Or if you have an update for Expo on your device just go for it. It will solve your problem.

**Comment by fazeelzama20** [comment]
Re-installing works..   cheers!!!!

**Comment by SirPhemmiey** [comment]
Had the same issue. Re-installing the Expo app on my device, and restarting (clear cache) the packager did it. Relieved!

**Comment by EvanBacon** [comment]
@amypellegrini Expo only supports the most recent 6 versions. I think you will need to update your app as v27 is almost out..?.. https://blog.expo.io/expo-sdk-v26-0-0-is-now-available-2be6d9805b31

**Comment by amypellegrini** [comment]
@EvanBacon Thanks, I've finally sorted out, I left my answer in another thread:

[https://github.com/expo/expo/issues/1216#issuecomment-382547330](https://github.com/expo/expo/issues/1216#issuecomment-382547330)

Thanks!

**Comment by gersonmontenegro** [comment]
reinstalling Expo on my device works for me. Thanks

**Comment by amypellegrini** [comment]
In my case I had to upgrade to SDK v21. To upgrade to the latest version is not trivial as we need to upgrade also a lot of other dependencies otherwise it breaks badly and it would take more effort to stabilise, so we are doing it in baby steps.

**Comment by charleston10** [comment]
> reinstalling Expo on my device works for me. Thanks ²

**Comment by TedSean** [comment]
Update Expo App, it worked for me !

**Comment by ChandniSharma** [comment]
I have uninstalled expo app and reinstalled it, but not working. how to upgrade sdk version in existing code?
Any idea?

**Comment by avinash-pnv** [comment]
> I have uninstalled expo app and reinstalled it, but not working. how to upgrade sdk version in existing code?
> Any idea?

In you project package.json file update the version as per you need under dependencies - "dependencies": {
    "expo": "25.0.0",
}

and run npm install

**Comment by ChandniSharma** [comment]
Thank you it worked.

**Comment by AhmedMKamal** [comment]
@avinash-pnv  It was the version but not the one at `package.json` I faced the same issue today with version 31.0.2 and the mobile app needed version  32.0.0 so I referred to the official website  [here](https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough) and as they mentioned I updated the `sdkVersion` at `app.json` file and it's working now.

**Comment by GodJerry** [comment]
> Is this on device or on simulator? Can you try removing the Expo app and reinstalling it?

did it

**Comment by NickDiVona** [comment]
Just found this works for my problem as well. Same error, android only, with expo version 32.0.0.

**Comment by abdullahmoon** [comment]
If you are using expokit, make sure to have the latest version of expokit in your package.json as well

**Comment by thanh90** [comment]
i got this problem in the release mode when upgrade from 31 to 33. it works well in the debug mode. did reinstall but nothing works.
