### ISSUE TITLE
Expokit 34 - 35: Fail to import app to Google Play Console

### ISSUE THREAD

**Issue by Nahani** [expo/expo#5688]
### Environment

 Expo CLI 3.0.10 environment info:
   System:
     OS: Windows 10
   Binaries:
     Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
   IDEs:
     Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

App -> Android Expokit

### Steps to Reproduce
1/ expo init project
1/ eject to expokit (sdk 34)
2/ Add " implementation 'com.stripe:stripe-android:10.2.1' " in the app build.gradle
3/ Generate a signed APK
4/ Try to upload the APK to Google Play Console

### Expected Behavior
The app should be uploaded to the Google Play console.

### Actual Behavior
> Failed to import.
> You uploaded an APK or Android App Bundle with invalid or missing signing information for some of its files.

### Reproductible demo

Just make the steps above

### Other

This issue with this dependency appear only with an expokit project. (Expo 34 & 35)

If I use a vanilla RN project there are no issue. So I think there are something wrong with the generated expokit project configuration.

Thank you for your help !

**Comment by sjchmiela** [comment]
Hey @Nahani! It looks like you have ejected your project before we introduced changes to the template that is used when ejecting which enabled 64-bit builds.

Could you, please, ensure you've read the article about adding 64-bit support to ExpoKit projects (https://blog.expo.io/64-bit-support-and-android-app-bundles-fe0c6a28669) and have followed the step-by-step guide on how to do so (https://medium.com/@andriidrozdov/reactnative-and-android-64-bit-new-google-play-market-rules-what-to-do-584b067d6f1a)?

**Comment by Nahani** [comment]
@sjchmiela  Yes my project enabled 64-bit builds.
Since SDK33 it's enabled for expokit.

I also tested with an expokit project generate from SDK35 I get the same error.

**Comment by sjchmiela** [comment]
Great! And how do you create the APK/AAB you try to upload? A correct way would be to eg. use Android Studio's `Build` > `Generate signed APK` menu or to provide `signingConfig` in `build.gradle`. Incorrect way would be just running `assembleRelease` which would produce a release APK/AAB, but it wouldn't be signed.

**Comment by Nahani** [comment]
@sjchmiela I created the AAB witht Android Studio with the good keystore.

As I said in my my post if I remove `implementation 'com.stripe:stripe-android:10.2.1` from my build.gradle, I don't have anymore issue and I can import the AAB to the Google Play sotre, so the issue doesn't come from my build process.

I think there are something in the generated expokit build.gradle that causing this.

**Comment by mshafrir-stripe** [comment]
@Nahani can you try reverting to an older Stripe version that uploads successfully, then add the following dependencies?

```
implementation 'org.bouncycastle:bcprov-jdk15on:1.61' 
implementation 'com.nimbusds:nimbus-jose-jwt:7.8'
```

This will help determine if it's something related to the 3DS2 library dependency, or one if its dependencies.

**Comment by Nahani** [comment]
@mshafrir-stripe After investigation I found that the issue appear from` Stripe v9.1.1` and I found that the issue come from this line added from this release:

`implementation "com.stripe:stripe-3ds2-android:0.0.5"`
If I remove this dependency there are not issue.

I will try with the dependencies that you said.

**Comment by Nahani** [comment]
@mshafrir-stripe So with stripe v9.0.1 and following dependencies:

```
implementation 'org.bouncycastle:bcprov-jdk15on:1.61' 
implementation 'com.nimbusds:nimbus-jose-jwt:7.8'
```

I have no issue and I can upload the bundle to Google Play console.

**Comment by Nahani** [comment]
@mshafrir-stripe After some investigation I found this when I execute this command line:

`apksigner verify -print-certs -v package.apk`

I get: 
```
DOES NOT VERIFY
ERROR: JAR signer BC1024KE.DSA: JAR signature META-INF/BC1024KE.DSA uses digest algorithm SHA-256 and signature algorithm DSA which is not supported on API Level(s) 21 for which this APK is being verified
ERROR: JAR signer BC2048KE.DSA: JAR signature META-INF/BC2048KE.DSA uses digest algorithm SHA-256 and signature algorithm DSA which is not supported on API Level(s) 21 for which this APK is being verified
```

There are something wrong in the files BC1024KE added by the stripe sdk.

**Comment by mshafrir-stripe** [comment]
For more context, the files in the logs come from Bouncy Castle, a Java library used for encryption.

**Comment by mshafrir-stripe** [comment]
I found the following pages which might be useful:
* https://stackoverflow.com/questions/42477546/can-i-specify-digest-algorithm-apksigner-uses
* https://jokester.io/post/2017-02/sha1-collision-and-apk-signing/

Can you try specifying a `minSdkVersion` lower than 21, such as 20?

**Comment by Nahani** [comment]
Thank you I will check your links and try with `minSdkVersion `20.

You can find here an APK that reproduce this issue:
[APK issue](https://doc-04-3g-docs.googleusercontent.com/docs/securesc/91fi0u6uhth8h2s0a5539dlt2bnfubts/1ndd5l7u6lreeg8i2g1eqiqat4iuh2gb/1570197600000/09476561705373848031/09476561705373848031/1Lw7ACOnwh1NvcW6Z6AlIyFkKIUaHZWAk?e=download)

**Comment by Nahani** [comment]
I can't use a lower version than 21 due to expo dependancies. But if I understand I need to uprgrade the version.
When I put `minSdkVersion `22
I get :

```
$ apksigner verify -print-certs -v apkMinSdk22.apk
DOES NOT VERIFY
ERROR: JAR signer BC1024KE.DSA: SHA-256 digest of META-INF/MANIFEST.MF main section does not match the digest specified in META-INF/BC1024KE.SF. Expected: <Lb09FaDj1lietEQMwGfkjd1FGmcply3dhFjGNzO97Rk=>, actual: <pyXj4uypcC2QPJYcv73qePx1vJeoVTd1TflUO3J6DKg=>
WARNING: JAR signer BC1024KE.DSA: APK is signed using APK Signature Scheme v2 but these signatures may be stripped without being detected because META-INF/BC1024KE.SF does not contain anti-stripping protections.
WARNING: JAR signer BC1024KE.DSA: SHA-256 digest of META-INF/MANIFEST.MF does not match the digest specified in META-INF/BC1024KE.SF. Expected: <kHZmD/zAxo9vQvROF+pavQhDPwHzv7PBvUVR2Yaocxo=>, actual: <tExPIdSCy/g2FVm00LKHiutlSCxEyOw8ELTZnLI471Y=>
ERROR: JAR signer BC2048KE.DSA: SHA-256 digest of META-INF/MANIFEST.MF main section does not match the digest specified in META-INF/BC2048KE.SF. Expected: <Lb09FaDj1lietEQMwGfkjd1FGmcply3dhFjGNzO97Rk=>, actual: <pyXj4uypcC2QPJYcv73qePx1vJeoVTd1TflUO3J6DKg=>
WARNING: JAR signer BC2048KE.DSA: APK is signed using APK Signature Scheme v2 but these signatures may be stripped without being detected because META-INF/BC2048KE.SF does not contain anti-stripping protections.
WARNING: JAR signer BC2048KE.DSA: SHA-256 digest of META-INF/MANIFEST.MF does not match the digest specified in META-INF/BC2048KE.SF. Expected: <kHZmD/zAxo9vQvROF+pavQhDPwHzv7PBvUVR2Yaocxo=>, actual: <tExPIdSCy/g2FVm00LKHiutlSCxEyOw8ELTZnLI471Y=>
```

**Comment by mshafrir-stripe** [comment]
@Nahani it appears that the issue is coming from `jarsigner`, not `apksigner`.

https://stackoverflow.com/questions/21457538/how-to-use-jarsigner-for-signing-an-apk

**Comment by mshafrir-stripe** [comment]
@Nahani I'm not able to get a signing failure with API 19 or 21 APKs on the latest version of stripe-android. This leads me to believe that there's some issue with how expo is building its APK.

**Comment by mshafrir-stripe** [comment]
@Nahani have you been able to make any progress?

**Comment by Nahani** [comment]
@mshafrir-stripe Not really I'm discussing with the Google support. I hope I will find a solution soon :)
I let you know when I have some more info.

**Comment by thcolin** [comment]
Hello, any news about this issue ? Got same issue with an ejected expo application

**Comment by alexislefebvre** [comment]
Sorry to bump this thread, is there something new?

> @mshafrir-stripe Not really I'm discussing with the Google support. I hope I will find a solution soon :)
> I let you know when I have some more info.

ping @Nahani

**Comment by Nahani** [comment]
Hello,

After discussing with the Google Support they said me that the issue come from this files in the APK:

```
META-INF/BC1024KE.DSA
META-INF/BC1024KE.SF
META-INF/BC2048KE.DSA
META-INF/BC2048KE.SF
META-INF/CERT.RSA
META-INF/CERT.SF
META-INF/MANIFEST.MF
```

I removed all and I resigned my apk and now I am able to upload the app to the Google Play Console.

@mshafrir-stripe Do you know if this can have an impact to the Stripe Librarie ?

**Comment by mshafrir-stripe** [comment]
@Nahani these files are part of Bouncy Castle, a library we use to handle cryptographic requirements for [3DS2 payment authentication](https://stripe.com/guides/3d-secure-2). If you need to support 3DS2 and you remove these files, there's a high likelihood that your app users will experience a crash or failure. If you don't need to support 3DS2, it's probably fine to remove these files.

**Comment by Nahani** [comment]
Ok thank you @mshafrir-stripe . But yes I need to support 3DS2 to be SCA complient :weary: .

I still do not understand why there is this problem with the expokit build.

I waiting Expo sdk 36 with the integration of  https://github.com/expo/expo/issues/5628 and hope that fix this issue... :pray:

**Comment by sjchmiela** [comment]
Could this be a problem of having both SpongyCastle and BouncyCastle dependencies in one app? Expo uses SpongyCastle since the beginning, maybe we could/should remove it in favor of BouncyCastle?

https://github.com/expo/expo/blob/2a38a11e3964a11c884d2cd2581f1c89c6391ef0/android/app/build.gradle#L128-L129

**Comment by mshafrir-stripe** [comment]
@sjchmiela for what it's worth, SpongyCastle seems to no longer be maintained - the [last commit](https://github.com/rtyley/spongycastle/commits/spongy-master) was almost 2 years ago

**Comment by Nahani** [comment]
Thank you @sjchmiela for your works.
How I can apply these changes in my project ? Can I apply changes manually or should wait the next release of Expo sdk ?

**Comment by sjchmiela** [comment]
Is your app ejected to ExpoKit workflow? If so, I could build a custom version of ExpoKit so you could test if these changes really fixed the issue. Just let me know which version should I apply the changes onto. 🙂

**Comment by Nahani** [comment]
@sjchmiela Yes my app is ejected to Expokit workflow with Expo sdk 35.

Thank you ! :smiley:

**Comment by alminde** [comment]
I’m facing the exact same issue, got the exact same response from Google Play support.

@sjchmiela, did you build a version of ExpoKit that includes this potential fix? I couldn’t find any instructions on how to build it from source, so I started messing around with it, found `buildAndroidTarballLocally.sh`, managed to run it after `expo start`ing in the `home` dir.

Now I have a `android-shell-builder.tar.gz`. Is that all what I need? How do I stick it into my app?

**Comment by sjchmiela** [comment]
If your app is ejected try installing `expokit@36.1.0-rc.0`. It contains SDK36, but with SpongyCastle removed.

**Comment by alminde** [comment]
Thanks for the release candidate!

After upgrading to ExpoKit 36, I tried installing `expokit@36.1.0-rc.0`, but unfortunately it looks like the issue remains:

> You uploaded an APK or Android App Bundle with invalid or missing signing information for some of its files. You need to create a valid signed APK or Android App Bundle.

**Comment by alminde** [comment]
If I change `minSdkVersion` from 21 to 24, `apksigner verify` works, but I still can’t upload the APK/AAB to Google Play.

**Comment by sjchmiela** [comment]
Just to be sure — how are you creating the APK/AAB that you're trying to upload to Google Play?

**Comment by alminde** [comment]
By running `./gradlew bundleRelease`. I can try using Android Studio too.

**Comment by sjchmiela** [comment]
If you could, it would let us rule out any missing configuration from `build.gradle`. 🙂

**Comment by alminde** [comment]
Alright. I tried with “Generate Signed Bundle / APK” in Android Studio. Same result, sadly. 😅

**Comment by Nahani** [comment]
Same for me I still have the issue with `expokit@36.1.0-rc.0` ... 😢

**Comment by Nahani** [comment]
@sjchmiela  any news ? Maybe should we open a new issue regarding this one is not resolved after removing SpongyCastle ?

**Comment by n-sviridenko** [comment]
@sjchmiela I created a repo reproducing the issue and all recommendations applied there which don't work at the end: https://github.com/n-sviridenko/stripe-expo-av-android-bug/tree/stripe-fix
Here's the PR showing the diff: https://github.com/n-sviridenko/stripe-expo-av-android-bug/pull/1/commits
