### ISSUE TITLE
Expo build status "waiting in queue" for a *long* time

### ISSUE THREAD

**Issue by ignatiusbill** [expo/expo#569]
Hi, I ran `exp build:android` and accidentally closed my `exp start` command prompt. Now, whenever I run `exp build:status`, it says "Android: Build waiting in queue..." and it's been like this for 3 hours (usually it's only 1-3 minutes and build is done in ~15 minutes on average).

I've tried reinstalling expo globally but it doesn't seem to work (first time `exp start` and checking status, build is already waiting in queue). Does anyone know a fix to this?

**Comment by 03balogun** [comment]
I had this issue earlier, It been fixed now

Hi there –

We had some issues with the Android builders this evening.

The issue has been fixed and the queue is processing.

Sorry for the inconvenience.

-Adam (@skevy)

However my downloadlink shows me access denied I dont know if you can help with that

**Comment by ignatiusbill** [comment]
@03balogun How did you get this information from Adam? Does this mean that the `exp build:android` will build even if I quit `exp start`?

**Comment by 03balogun** [comment]
@ignatiusbill I ran into the same issue some moments ago, posted it on the forum and got a reply from him. 

> will build even if I quit exp start? Yes I think.

**Comment by 03balogun** [comment]
@ignatiusbill My download link after build takes me to a page that shows access denied, Do you have an idea what would be wrong?

**Comment by ignatiusbill** [comment]
@03balogun No, I've never ran into that error before. Can you post the full error log?

**Comment by 03balogun** [comment]
I opened it as an issue aleady https://github.com/expo/expo/issues/570 with screenshot attached, Kindly check it there. Thanks

**Comment by ignatiusbill** [comment]
Expo finished building the android apk first thing in the morning.
