### ISSUE TITLE
[expo-apple-authentication] AppleAuthenticationButton not showing up

### ISSUE THREAD

**Issue by cuttlas** [expo/expo#5690]
### Environment

Bare react-native app. iOS simulator with iOS 13. 

### Steps to Reproduce

I'm trying to insert the AppleAuthenticationButton using the exact same code provided in the documentation:

```javascript
import * as AppleAuthentication from "expo-apple-authentication";
...
  <AppleAuthentication.AppleAuthenticationButton
    buttonType={
      AppleAuthentication.AppleAuthenticationButtonType.CONTINUE
    }
    buttonStyle={
      AppleAuthentication.AppleAuthenticationButtonStyle.BLACK
    }
    cornerRadius={5}
    onPress={async () => {
      try {
        const credential = await AppleAuthentication.signInAsync({
          requestedScopes: [
            AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
            AppleAuthentication.AppleAuthenticationScope.EMAIL
          ]
        });
        console.warn(credential);
        // signed in
      } catch (e) {
        console.warn(e);
      }
    }}
  />
```

### Actual Behavior

Nothing is showing up. Worth things to note:

- If I remove the props buttonType / buttonStyle it throws an error. So the component is being executed.
- The AppleAuthentication.isAvailableAsync() method returns true.
- If I call AppleAuthentication.signInAsync() using a custom button the Sign In flow works perfectly.

**Comment by tsapeta** [comment]
Hey @cuttlas,
Is your app ejected or in bare workflow? I'm asking because `expo-apple-authentication` is still not released in public version of Expo client, so the only way to use the RC version is by ejected app or bare React Native workflow.

**Comment by cuttlas** [comment]
It's a bare react-native app. Sorry for not pointing that out.

**Comment by mlguys** [comment]
Hey, I'm facing the same issue with my bare react native app too.

**Comment by ide** [comment]
IIRC you need the Apple auth entitlement or maybe a plist key in your Xcode project, which we don’t set up for bare Expo projects. Try researching that and seeing if it helps.

**Comment by cuttlas** [comment]
I've rechecked and I pretty sure my Xcode config is correct. And again, the AppleAuthentication.isAvailableAsync() method returns true and the AppleAuthentication.signInAsync() method works perfectly, which I don't think they would if I was missing something in my config.  It's only the React component that's not showing up.

I guess as a temporary solution I can implement a custom button that looks exactly alike to the Apple button.

**Comment by ide** [comment]
Thanks for the clarification. We’ll need to investigate further.

We should probably add the module to bare-expo as an easy way to test this.

**Comment by ide** [comment]
Adding this to SDKs 35 and 36 since we likely will want to cherry-pick the fix back into the sdk-35 branch and publish the module from there, assuming the fix is backwards compatible with 35.

**Comment by Szymon20000** [comment]
I think all you need to do is to set width and height to the button :D. 
Try to set style
```Js

style={{ width: 200, height: 44 }}

```

**Comment by mlguys** [comment]
> I think all you need to do is to set width and height to the button :D.
> Try to set style
> 
> ```js
> style={{ width: 200, height: 44 }}
> ```
Thanks @Szymon20000 for the tip, it works!

**Comment by tsapeta** [comment]
^ This is the recommended workaround for that problem, so I'm closing this issue.
I'm also going to update docs to clarify that setting a dimensions of the button is required 🙂

**Comment by jamesbechet** [comment]
@tsapeta you might also want to update the example: https://docs.expo.io/versions/latest/sdk/apple-authentication/

**Comment by Dexwell** [comment]
I can't get the button to show up even with the dimensions set :( 
Using bare react-native 0.60.5 and expo-apple-authentication 1.0.0 as a UniModule. Any tips?

**Comment by ide** [comment]
@Dexwell With an app using bare RN I'd recommend using the iOS debugger to figure out what is going on.

**Comment by Dexwell** [comment]
@ide Thanks, apparently you can't set it to `flex: 1` but must give it only a width and height.

**Comment by shrolr** [comment]
I can't get the button to show up I've try to set height and width but I't does not work.

 expo : "35.0.0"
"expo-apple-authentication": "~1.0.0",
"react": "16.8.3",

**Comment by aaronbesson** [comment]
> I can't get the button to show up I've try to set height and width but I't does not work.
> 
> expo : "35.0.0"
> "expo-apple-authentication": "~1.0.0",
> "react": "16.8.3",

same

**Comment by hcondron** [comment]
> I can't get the button to show up I've try to set height and width but I't does not work.
> 
> expo : "35.0.0"
> "expo-apple-authentication": "~1.0.0",
> "react": "16.8.3",

+1

**Comment by hcondron** [comment]
Strangely, the button shows up when I run my app on a device, but not on the simulator.

**Comment by shrolr** [comment]
> Strangely, the button shows up when I run my app on a device, but not on the simulator.

did you check your os version on simulator? it needs to be higher than 13.
