### ISSUE TITLE
Create release apk after eject to ExpoKit not working

### ISSUE THREAD

**Issue by niv-breez** [expo/expo#5697]
Hello,
I worked with the regular Expo for the last months but now I need to eject.
So I run expo eject and choose eject to ExpoKit.

I build and run the debug application and it works fine, now I want to create a signed release apk but after installing it I got a failed message when opening the application.

These are the steps I made for running in RELEASE mode:

1. expo publish
2. open AndroidStudio
3. "Generate signed APK" and choose my key file and put the alias and the passwords I got from 4. expo when I built with them
5. I tried to installed the apk that was generated but after installing and get into the app there is a message: "Something went wrong, Cloud not load app"

I also tried to run the ./gradlew assembleRelease but I got the same message

What am I missing ?

**Comment by lewatt23** [comment]
Use logcat on android studio to see what are the errors logs

**Comment by AdamJNavarro** [comment]
Hey @niv-breez,

We'll continue the conversation in your forum post. https://forums.expo.io/t/create-release-apk-after-eject-to-expokit-not-working/27875

Cheers,
Adam
