### ISSUE TITLE
Generated download link for standalone app shows access denied

### ISSUE THREAD

**Issue by 03balogun** [expo/expo#570]
After following the guide here: https://docs.expo.io/versions/latest/guides/building-standalone-apps.html\

I the app build successfully but the generated link leads to a page that shows access denied.

Any suggestion on how fix this will be appreciated.

![screenshot 171](https://user-images.githubusercontent.com/28654450/29859447-020600d6-8d5a-11e7-9afd-2f80d3d4942c.png)

**Comment by ignatiusbill** [comment]
From our discussion in issue #569, no, sorry I've never ran into this problem. Have you tried building it again?

**Comment by 03balogun** [comment]
I have tried re-building over and over again, link keeps getting generated but same error. **ACCESS DENIED**

**Comment by dikaiosune** [comment]
@03balogun can you ping me on slack with the URL you received? My username there is `ap`.

Going to close this since we need private information to resolve.
