### ISSUE TITLE
SVG doesn't work

### ISSUE THREAD

**Issue by IWTBCAdeveloper** [expo/expo#5704]
I upgrade expo SDK from 32 to 34 and SVG doesn't work. What should I do now ? Please help
![70838146_1113759745498019_7937217902241906688_n](https://user-images.githubusercontent.com/13016058/65300936-77efd480-db9f-11e9-9d92-fecaf3c0719f.jpg)

**Comment by AdamJNavarro** [comment]
Hey @IWTBCAdeveloper, closing this as your forum [post](https://forums.expo.io/t/svg-doesnt-work-after-upgrading-sdk-version/27920/2) has the solution!

Cheers,
Adam
