### ISSUE TITLE
Camera. Capture photo stretching

### ISSUE THREAD

**Issue by nvvetal** [expo/expo#5709]
### Environment

 Expo CLI 3.0.4 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.0.4

### Steps to Reproduce

By using Sanmsung M40 preview of photo while capturing photo by camera-expo is stretched

### Expected Behavior

We need to have it not stretched
react-native-camera has before aspect={Camera.constants.Aspect.fit} for that

### Reproducible Demo

`import {Camera} from 'expo-camera';
<Camera
            style={styles.camera}
            type={this.state.type}
            flashMode={this.state.flashMode}
            onCameraReady={this.prepareRatio}
            ratio={this.state.ratio}
            ref={ref => {
              this.camera = ref;
            }}
          >
`

**Comment by AdamJNavarro** [comment]
Hey @nvvetal,

It looks like react-native-camera removed the `aspect` prop. Have you tried to use the `getSupportedRatiosAsync` (https://docs.expo.io/versions/v35.0.0/sdk/camera/#getsupportedratiosasync) and `getAvailablePictureSizesAsync` methods and passing the values into the `ratio` and `pictureSize` properties?

Cheers,
Adam
