### ISSUE TITLE
Unable to resolve "scheduler/tracing" on latest Expo SDK 25.

### ISSUE THREAD

**Issue by Vista1nik** [expo/expo#5712]
### Environment

  Expo CLI 3.0.10 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    npmPackages:
      expo: 35.0.0 => 35.0.0 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.6 
    npmGlobalPackages:
      expo-cli: 3.0.10

Target: Android

### Steps to Reproduce

Set example project dependencies to this
```
    "expo": "35.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
```

### Expected Behavior

Successful render.

### Actual Behavior

Error:
```
Unable to resolve "scheduler/tracing" from "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js"

```

### Note 
Solution from #3949 and clearing of haste cache don't help.
Clearing haste cache also don't help.

**Comment by Vista1nik** [comment]
Fixed by full reinstall of node env.

**Comment by MedafPayDevelopers** [comment]
I have faced the same issue 
Unable to resolve "scheduler/tracing" from "node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js"
