### ISSUE TITLE
expo-sharing

### ISSUE THREAD

**Issue by mgiorgi-github** [expo/expo#5713]
### Environment
Mac Mojave 10.14.6
Expo cli 3.0.10
Expo sdk version: 34.0.3
React: 16.8.3

### Steps to Reproduce
Share image with expo-sharing module:
Sharing.shareAsync(uri)

### Expected Behavior
If i share an image i've a callback with status (ok or cancel) and the app i've used to share (Facebook, Instagram etc...), my perfect callback data is {status:'success', method:'instagram'} or {status:'cancel'}

### Actual Behavior
I can't see wich app i've used to share and if i've confirmed or cancel the sharing...

**Comment by mgiorgi-github** [comment]
Hi Adam,
what info do you need? The problem is when i share an image with Facebook or Instagram, at the end i can't know if the image is really shared (i've annulled for example) and what app i've used...
Is possible retrive this information?
Thanks

**Comment by mgiorgi-github** [comment]
Hi Adam, can you help me about this beaviour?
Thanks in advance

**Comment by AdamJNavarro** [comment]
Hey @mgiorgi-github,

Sorry for labelling the issue and then going ghost silent. I'm thinking this is more so functionality we need to add rather than a bug itself. I'm going to bring this up internally and see what the best course of action is.

**Comment by mgiorgi-github** [comment]
Thanks, i think this functionality is necessary in order check if the sharing is done or not
Thanks

**Comment by mgiorgi-github** [comment]
Hi @AdamJNavarro ,
is this a hard features?

**Comment by mgiorgi-github** [comment]
Up...

**Comment by mgiorgi-github** [comment]
Hi Adam,
this features for us is very important... is a hard work?
Thanks

**Comment by razinazam** [comment]
Sharing.shareAsync("", options) local path issue

**Comment by mgiorgi-github** [comment]
News about this features?

**Comment by expjess** [comment]
Hi @mgiorgi-github - sorry for the lack of clarity. It doesn't look like this is slated right now, and we don't want it to get lost. The best place to provide input (like this) for feature requests is on [Canny](https://expo.canny.io/feature-requests) -- and, of course, we welcome PRs :)

**Comment by pkreissel** [comment]
Is this something that will be implemented?
