### ISSUE TITLE
Bug in Expokit 2.13.0 cannot build on iOS

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#5715]
### Environment
```

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: yarn install v0.21.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.32s. - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.20 => 16.8.20
      @types/react-native: ^0.57.63 => 0.57.63
      @types/react-navigation: ^3.0.7 => 3.0.7
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.6 => 4.0.6
    npmGlobalPackages:
      expo-cli: 3.0.10
```

### Steps to Reproduce

Followed instructions to update to ExpoKit ios/2.13.0 for Expo 35. ExpoKit throws errors when trying to build iOS.

`'preferredUserInterfaceStyle' is unavailable: not available on iOS`
```
Property 'overrideUserInterfaceStyle' not found on object of 
type 'EXAppViewController *'; did you mean 'preferredUserInterfaceStyle'?
```

**Comment by tsapeta** [comment]
Hey @shamilovtim,
Since ExpoKit 2.13.0 fully supports iOS13, you will need to use Xcode 11 to build it.
Closing this thread as I'm sure the new version of Xcode will fix that problem.

**Comment by shamilovtim** [comment]
Oh, I thought this might be it! I checked the app store for an Xcode update and it didn't show one. Apparent it won't show you unless you actually click on "Xcode."

**Comment by objectiveSee** [comment]
Is there a fix for users who can't upgrade to Xcode 11 at the moment?

**Comment by shamilovtim** [comment]
@objectiveSee I assume you can follow [these instructions](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit) and point the tag to 2.12.5
