### ISSUE TITLE
[splash-screen] Per-appearance splash screens

### ISSUE THREAD

**Issue by ide** [expo/expo#5716]
* dark mode splash screens
* XDL support
* a way to test it in the Expo client too

**Comment by ide** [comment]
@tsapeta @brentvatne could you two be in charge of this issue for SDK 36? (@EvanBacon -- if web supports `prefers-color-scheme` in custom splash screens, we'll want to update the webpack PWA generator too.)

**Comment by outaTiME** [comment]
Available in SDK38?

**Comment by brentvatne** [comment]
sadly only in the bare workflow, we weren't able to finish integrating expo-splash-screen native code into the managed workflow. see https://github.com/expo/expo-cli/tree/master/packages/configure-splash-screen to learn how to configure for bare projects

**Comment by outaTiME** [comment]
so sad @brentvatne 😢, im still waiting on managed, thanks !!!

**Comment by brentvatne** [comment]
closing this because it's not a bug but rather a feature. technically possible to do this with eas build and the expo-splash-screen config plugin

**Comment by outaTiME** [comment]
> closing this because it's not a bug but rather a feature. technically possible to do this with eas build and the expo-splash-screen config plugin

Great news Brent, how would the eas configuration be to achieve that? do you have an example to share?

**Comment by brentvatne** [comment]
@outaTiME - it's not yet documented and may change in the future but you can see the options here: https://github.com/expo/expo-cli/blob/c3ebf9e46deba08241981430c887960cc9479fde/packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/getIosSplashConfig.ts#L9-L23

**Comment by dgellow** [comment]
@brentvatne Do I understand correctly that only iOS is supported? I cannot find an equivalent for Android. I understand it isn't a finalized API, just wondering if the feature is expected to be supported cross-platform.
