### ISSUE TITLE
Unrecognized font family on SDK35

### ISSUE THREAD

**Issue by FH-Hersey** [expo/expo#5717]
### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.4.10 => 3.4.12 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.6 
    npmGlobalPackages:
      expo-cli: 3.0.10

### Steps to Reproduce

I just update from SDK34 to SDK35 and got the error, It was working normally before the update, also using expo-font`: 7.0.0.

I'm loading the custom fonts, while loads I return `<AppLoading`/>, when finish return `<App />`,  I think this is the normal flow, when I move to a screen that uses that font get the error.

**On Android is working without problems, the error only shows on iOS**

### Expected Behavior

The app should run normally

### Actual Behavior

<img width="406" alt="Screen Shot 2019-09-20 at 15 11 58" src="https://user-images.githubusercontent.com/50335902/65360204-34f02a00-dbbc-11e9-9b55-66b756eb3a44.png">

**Comment by hrmoller** [comment]
Same experience here after upgrading to 35.

Also tried the below which doesn't help.
```
rm -rf node_modules
rm package-lock.json 
npm i
npm run start -- -c
```

**Comment by Jbrutausorus** [comment]
I have the same issue

**Comment by Jbrutausorus** [comment]
I did these commands twice and now it's worked !
1.- Delete the node_modules folder
2.- Delete the package-lock.json file
3.- Run npm/yarn install

**Comment by yohamta** [comment]
I did the following and it fixed.
````
$ expo install expo-font
```
Seems it should be noted on Expo Upgrade Guide

**Comment by FH-Hersey** [comment]
@yohamta I did that, (because there's a warning from the cli), also removed `node_modules` and `yarn.lock` with no success

**Comment by jmzwar** [comment]
@yohamta Are you running this on a simulator or device.

When I run the simulator no error is thrown but on a device one is.

**Comment by yohamta** [comment]
@FH-Hersey @jmzwar I checked on device and no problem.
I think you may have to do below.
```
$ expo install expo-asset
```

**Comment by FH-Hersey** [comment]
Is not working on a real device or emulator, @yohamta I tried `expo install expo-asset` but it's not working (removed `yarn.lock` and `node_modules`) in the process

**Comment by mortenc** [comment]
I am having the same issue after upgrading to SDK35. 

In my case, it seems the error is arising from trying to use the custom font with `victory-native` for an SVG chart. When I stop trying to use the font for styling the chart, the error stops – and the font loads fine for the rest of the app. So it possibly has something to do with SVG and custom fonts? 

@FH-Hersey Any chance you're trying to use the custom font for styling SVGs, like with `victory-native` or `react-native-svg`?

**Comment by hefler** [comment]
I've tried all the above without success. This problem is happening for me since I started a new app (SDK34), upgraded to SDK35 in the hopes this would get fixed, apart from that it didn't. However, on another App developed by someone else I've added custom fonts, update from SDK32 to SDK34 and it works. No clue what is the issue as the implementation is virtually the same.

**Comment by samipshah100** [comment]
> @FH-Hersey @jmzwar I checked on device and no problem.
> I think you may also have to do below.
> 
> ```
> $ expo install expo-asset
> $ yarn add -D babel-preset-expo@^7.0.0 
> ```

I did this and also 
` expo install expo-font`

but it's not working for me.

**Comment by jmzwar** [comment]
@mortenc I had a similar issue with svg text (appears to be a breaking change in the upgrade to react-native-svg).

Once that was resolved the following was successful.
`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache verify && npm install && npm run start`

**Comment by mortenc** [comment]
> @mortenc I had a similar issue with svg text (appears to be a breaking change in the upgrade to react-native-svg).
> 
> Once that was resolved the following was successful.
> `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache verify && npm install && npm run start`

Thanks! Where did you find information on the breaking change to react-native-svg, though? Did you get the issue fixed, or did you also just 'solve' it by removing custom fonts for now?

**Comment by davidbiller** [comment]
So for me the same issue, if there is Text in the SVG Component.
Expo SDK35

**Comment by mskg** [comment]
> So for me the same issue, if there is Text in the SVG Component.
> Expo SDK35
> 
> ```
>           <G fill="#FFF" fillRule="evenodd"  x={ x(index) + (bandwidth / 2) } y={ 255 }>
>                 <Text fontSize={14}  textAnchor={'middle'}>
>                     <TSpan x={0.67} y={74}>
>                         {Sugar.String.truncate(value.label,10,"right")}
>                     </TSpan>
>                 </Text>
>                 <Text fontSize={48}  textAnchor={'middle'} **fontFamily='Inter-UI-Medium'>**
>                     <TSpan x={-4} y={50}>
>                         {index == 0 ? 2 : index == 1 ? 1 : index == 2 ? 3 : null}
>                     </TSpan>
>                 </Text>
>         </G>
> ```

I can confirm this.

**Comment by matapo** [comment]
> I am having the same issue after upgrading to SDK35.
> 
> In my case, it seems the error is arising from trying to use the custom font with `victory-native` for an SVG chart. When I stop trying to use the font for styling the chart, the error stops – and the font loads fine for the rest of the app. So it possibly has something to do with SVG and custom fonts?
> 
> @FH-Hersey Any chance you're trying to use the custom font for styling SVGs, like with `victory-native` or `react-native-svg`?

Did you find a solution? I have the same issue.

**Comment by maharjanaman** [comment]
Any update on this? I'm also using victory-native. For me issue occurred after I upgraded `react-native-svg` to 9.9.5.

**Comment by superphil0** [comment]
i also use react-native-svg however the error message is not very helpful it is:
Unrecognized font family " <== like this with one "
defaultTimeoutInvoke

any update on this?

**Comment by gilbert** [comment]
I'm having the same issue. `<Svg.Text fontFamily="X">` throws `Unrecognized font family 'X'`, even though I preloaded that same font and use it elsewhere successfully.

**Comment by ghmendonca** [comment]
Same issue here, deleting node_modules, cleaning cache or deleting package-lock does not work.

I've tested on an iPhone X physical device and Android emulator using version 8.0, both does not load the SVG.

Running on expo 36 too.

**Comment by devspacenine** [comment]
Does it have something to do with [this line](https://github.com/expo/expo/blob/master/packages/expo/src/launch/withExpoRoot.tsx#L17) in withExpoRoot()?

```
if (StyleSheet.setStyleAttributePreprocessor) {
    StyleSheet.setStyleAttributePreprocessor('fontFamily', Font.processFontFamily);
}
```

The issue seems to disappear if I comment that line out. I'm not sure if there would be any cascading effects by deleting that step, though.

**Comment by Ryxar** [comment]
Hi,

I'd got the same issue and I tried :

> 1.- Delete the node_modules folder
> 2.- Delete the package-lock.json file
> 3.- Run npm/yarn install

This didn't work...

For my case I deleted the 

> `expo-font`

 folder inside 

> `node_modules/expo/node_modules`

Everything works now

**Comment by harryli0088** [comment]
Not sure if this workaround helps anyone, but I found that my issue is because of ```react-native-svg```. I used a ```ForeignObject``` element with a ```react-native``` ```Text``` element and it was fine!

Originally I was using the ```react-native-svg``` ```Text``` element to render the fontFamily like this:
```
import Svg, { Text as SvgText } from 'react-native-svg';
...
<Svg width={100} height={100}>
    <SvgText
        x={0)
        y={0}
        fontFamily="space-mono"
        >
        test
    </SvgText>
</Svg>
```

But it works for me when I do this:
```
import { Text } from 'react-native';
import Svg, { ForeignObject} from 'react-native-svg';
...
<Svg width={100} height={100}>
    <ForeignObject
        x={0}
        y={0}
        width={100}
        height={100}
        >
        <View>
            <Text style={{fontFamily:"space-mono"}}>test</Text>
        </View>
    </ForeignObject>
</Svg>
```

**Comment by mafiusu** [comment]
@harryli0088 your solution works. I no longer get an annoying error message.

**Comment by Hirbod** [comment]
September 2021 - Issue still persists.

**Comment by LagoonProject** [comment]
This is still an issue and is related somewhat to SVGs.
