### ISSUE TITLE
Unable to cache fonts after upgrading to SDK 35

### ISSUE THREAD

**Issue by schellack** [expo/expo#5718]
### Environment

Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.6 
    npmGlobalPackages:
      expo-cli: 3.1.0

Issue occurs on both iOS and Android simulators.

### Steps to Reproduce

After upgrading to Expo SDK 35.0.0 and expo-font 7.0.0, on app launch I get errors trying to cache custom fonts. This is code that worked before on SDK versions 34.

To reproduce, follow the instructions in https://docs.expo.io/versions/latest/guides/using-custom-fonts/ and make sure to use your own font file that is bundled your project. 

I am using the Lato font and have included the ttf file in an assets/fonts folder.

### Expected Behavior

Custom fonts are cached by `Font.loadAsync()` without error.

### Actual Behavior

When my app runs and I hit the Font.loadAsync code, I get this error:

> console.error: "fontFamily "lato" is not a system font and has not been loaded through Font.loadAsync.
> 
> - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
> 
> - If this is a custom font, be sure to load it with Font.loadAsync."
> 
> __expoConsoleLog
>     RemoteConsole.js:80:37
> error
>     YellowBox.js:59:8
> error
>     muteWarnings.fx.js:27:24
> processFontFamily
>     Font.js:35:16

### Reproducible Demo

I attempted to reproduce through a snack (see link below(, but don't get the error. Instead, the custom font is just not loaded.
https://snack.expo.io/@salus/custom-font-sdk-35

**Comment by mskg** [comment]
Related #5717

**Comment by Razorholt** [comment]
1.- Delete the node_modules folder
2.- Delete the package-lock.json file
3.- Run npm/yarn install

Then run expo start -c

**Comment by skulljuice** [comment]
@schellack did you update expo-font to latest version?

upgrade expo-font to "expo-font": "7.0.0" on sdk 35.

**Comment by jmzwar** [comment]
I am facing the same issue.

"expo-font": "^7.0.0",
"expo": "^35.0.0",

Tried deleting node_modules, pack-lock all to no avail.

**Comment by lukerayman** [comment]
Looks like I'm stuck on the same error while updating from Expo 34 to 35. 😞 

I also tried to downgrade Expo Font to version 6.0.1 - nothing changed. 

![Simulator Screen Shot - iPhone 11 - 2019-09-23 at 16 28 45](https://user-images.githubusercontent.com/1166994/65434671-7df3e880-de1f-11e9-8c5b-5f5d5295ba1a.png)

**Comment by rodriguezmanu** [comment]
I did this:

- delete node_modules
- delete package.lock and yarn.lock
- yarn 
- cd ios - pod install

**Comment by lukerayman** [comment]
Removing `package-lock.json` and reinstalling packages and pods fixed it for me.

**Comment by schellack** [comment]
[Per the upgrade instructions](https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4#a3f5) I had already deleted my node_modules folder, run `npm install`, and run `expo start -c` to start up again.

What I had not done, as others have mentioned here, was to delete my package-lock.json file before running `npm install`.

Doing that has resolved the problem for me as well.
