### ISSUE TITLE
why does the exp.io point to old sdkVerison ?  even after updaing the expo.xde to 20.0.0 on mac ?

### ISSUE THREAD

**Issue by jpca999** [expo/expo#572]
I already have an expo project  I want to use the latest apis provided in expo 20 like SecureStore. 
So for that I am creating a whole new project and tranfering the fiels on to new project. 

Is there a shortcut to do the above. ?

after updating My expo xde,  and create a new app.   when i looked at this file, it showed skdVersion to be 16.0.0..  

{
  "name": "react-native-elements-app",
  "description": "A demo app for React Native Elements UI Library",
  "slug": "react-native-elements-app",
  "privacy": "public",
  "sdkVersion": "16.0.0",
  "version": "1.0.0",
  "orientation": "portrait",
  "primaryColor": "#cccccc",
  "icon": "./assets/icons/app.png",
  "loading": {
    "icon": "./assets/icons/loading.png",
    "hideExponentText": false
  },
  "packagerOpts": {
    "assetExts": ["ttf", "mp4"]
  },
  "ios": {
    "supportsTablet": true
  }
}

![image](https://user-images.githubusercontent.com/1026325/29900927-ed798d0e-8dc2-11e7-9566-97a102f6b817.png)

**Comment by terribleben** [comment]
Hi, new projects should always use the latest SDK. How are you creating a new project? Are you clicking this button?
![image](https://user-images.githubusercontent.com/1316332/29938484-b76f20f4-8e3d-11e7-9e9e-137769f4a77b.png)

**Comment by jpca999** [comment]
That's exactly how I'm creating like you showed in the pic below.

**Comment by terribleben** [comment]
Hi, upon taking a closer look at the file you pasted, it's not our new project template. It's some other project called `react-native-elements-app`. You should double check that you're looking at the right file.

**Comment by davepack** [comment]
Hi @jpca999, I'm going to close this issue. Feel free to reopen if you have new info.

**Comment by jpca999** [comment]
@davepack  its running fine now, Thanks Dave,   thanks @terribleben
