### ISSUE TITLE
Unable to load svg files with SDK35

### ISSUE THREAD

**Issue by rphlmr** [expo/expo#5722]
### Environment

```
  Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.6 
    npmGlobalPackages:
      expo-cli: 3.1.0

```

### Steps to Reproduce

`expo install react-native-svg`

Load a svg file

### Expected Behavior

Packager works

### Actual Behavior

When I try to start ou publish I have thos error : 

```
While trying to resolve module `react-native-svg` from file `/Users/rphlmr/app/assets/images/coin.svg`, the package `/Users/rphlmr/app/node_modules/react-native-svg/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/rphlmr/app/node_modules/react-native-svg/src/index.ts`. Indeed, none of these files exist:

  * `/Users/rphlmr/app/node_modules/react-native-svg/src/index.ts(.native||.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.json|.native.json|.json)`
  * `/Users/rphlmr/app/node_modules/react-native-svg/src/index.ts/index(.native||.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.svg|.native.svg|.svg|.ios.json|.native.json|.json)`
Failed building JavaScript bundle.
```

Everything was working with sdk 34 and previous version of react-native-svg (9.5.1).
I follow all steps for metro packaging (https://github.com/react-native-community/react-native-svg#use-with-svg-files). 
I clean all chaches and still this issue :(

Thanks

**Comment by rphlmr** [comment]
Ok that's fixed : https://github.com/kristerkari/react-native-svg-transformer/pull/46

We have to update our app.json with ts and tsx support : 

```
"packagerOpts": {
  "config": "metro.config.js",
  "sourceExts": ["js", "jsx", "svg", "ts", "tsx"]
}
```

**Comment by jtaylor1989** [comment]
> Ok that's fixed : [kristerkari/react-native-svg-transformer#46](https://github.com/kristerkari/react-native-svg-transformer/pull/46)
> 
> We have to update our app.json with ts and tsx support :
> 
> ```
> "packagerOpts": {
>   "config": "metro.config.js",
>   "sourceExts": ["js", "jsx", "svg", "ts", "tsx"]
> }
> ```

Thanks so much. I have been struggling with this all morning after I upgraded to cli 3.1.0.
