### ISSUE TITLE
Expo is trying to load (really) old builds

### ISSUE THREAD

**Issue by spyshower** [expo/expo#5723]
## 🐛 Bug Report

A few days ago I went to my gf's house and tried to load my app in Expo client. I noticed it was a really old build, like months ago. Once I went home, the produced build was fine.

Today after configuring some things in my internet network, the same (?) thing happened, although SDK 32 is not valid anymore since I upgraded to SDK 35.

### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.6 
    npmGlobalPackages:
      expo-cli: 3.0.10

### Expected Behavior

Load SDK 35

### Actual Behavior

Expo is trying to load SDK 32 and I get this error:

`Uncaught Error: 32.0.0 is not a valid SDK version.`

**Comment by ide** [comment]
It looks like this is likely a caching issue. If you have normal network connectivity (home internet working, no firewalls, your ISP doesn't block connections), the client should receive the latest version of your project with the latest SDK version your clients supports.
