### ISSUE TITLE
expo-av

### ISSUE THREAD

**Issue by jdaly13** [expo/expo#5726]
### Steps to Reproduce
Follow the documentation

				<Video 
					//source={{ uri: this.state.videoSource }}
					usePoster={true}

					ref={this.handleVideoRef}
				/>

	handleVideoRef = (component) => {
		this.playBackObject = component;
		var x = this.playBackObject.loadAsync({uri: this.state.videoSource}, {shouldPlay: true}, downloadFirst = true).then((obj)=>{
			console.log(obj);
		})
		console.log(this.playBackObject, 'x' , x);
		this.playBackObject.setOnPlaybackStatusUpdate(this.onPlaybackStatusUpdate);
		
	}
_this.playBackObject.setOnPlaybackStatusUpdate is not a function

### Expected Behavior
It should be a method of object
when logging out other methods are listed like loadAsync
even in your example
https://github.com/expo/playlist-example/blob/master/App.js it's commented out
I can't find any other documentation
### Actual Behavior

Gives an error _this.playBackObject.setOnPlaybackStatusUpdate is not a function
Poor documentation if a user needs to take extra steps to use this method it should be stated in documentation 

https://docs.expo.io/versions/latest/sdk/av/

**Comment by wboka** [comment]
I agree. I've only been working with this for a few weeks so it might just be inexperience but I feel like this example needs to be expanded to show more working code. Anyone have a working example of how this is supposed to work?

**Comment by kevgrig** [comment]
To save others' research time, if you hit this problem, you can use the property on the `Video` instead:

```
<Video
  ref={(v) => { this._v = v; }}
  onPlaybackStatusUpdate={this.onPlaybackStatusUpdate}
/>
```

**Comment by IjzerenHein** [comment]
The `setOnPlaybackStatusUpdate` method for Video was added in SDK 37 and the documentation has been updated a while back already.

@jdaly13 Is this still an issue for you or can we close this? Regards.

**Comment by IjzerenHein** [comment]
Closing this as this issue has been resolved. Feel free to reopen with additional information if the problem still exists.
