### ISSUE TITLE
Android Image picker returns JPG regardless of original format of picked image

### ISSUE THREAD

**Issue by nickknissen** [expo/expo#573]
Image picker on android always convert images to JPG. This does not seems to be the case for iOS. 
Is this inteded behavior?

The code for handling file conversion can be found here.
https://github.com/expo/expo/blob/d523b01dd167efe6cde4ab39d3ba6740f3bddc04/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/ImagePickerModule.java#L360

**Comment by terribleben** [comment]
@jesseruder / @nikki93 is this intended behavior?

**Comment by nikki93** [comment]
hey! Would you like maybe an option exposed that lets you choose the file format?

**Comment by nickknissen** [comment]
The best solution would be to return the image as the format it's stored in.
Pick a PNG return a PNG.

A solution could be allowing `writeImage` method take a second argument which was a value of `Bitmap.CompressFormat`
