### ISSUE TITLE
Build fails on iOS after eject from SDK 35 with ExpoKit

### ISSUE THREAD

**Issue by darth-veitcher** [expo/expo#5733]
### Environment
Attempting to build for iOS target after ejecting from Expo with ExpoKit option selected. It's worth noting that these steps worked absolutely fine with `"expo": "^34.0.1"` and `"expokit": "34.0.2"` previously.

#### expo diagnostics
```
  Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nodenv/versions/10.16.3/bin/node
      Yarn: 1.17.3 - ~/.nodenv/versions/10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nodenv/versions/10.16.3/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.1.0
```

### Steps to Reproduce
Create a blank template app
```
expo-cli init -t blank --yarn --name testEject testEject
cd testEject
expo eject
```
Select `ExpoKit` option on ejecting and then update pods.
```
cd ios
pod install --repo-update
```
Now try to build
```
cd ..
react-native run-ios
```

### Expected Behavior
I'd expect the application to be built and then deployed onto the simulator.

### Actual Behavior
Build fails on ExpoKit. Loading up in XCode and attempting the build there shows the following:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/1722315/65393308-12eed700-dd77-11e9-8224-2fc77b08d98b.png">

<img width="820" alt="image" src="https://user-images.githubusercontent.com/1722315/65393317-28fc9780-dd77-11e9-8aec-cfe5d5f622e2.png">

Commenting out this line allows the build to succeed and application launch on the simulator.

```
/testEject/ios/Pods/ExpoKit/ios/Exponent/Kernel/Views/EXAppViewController.m:398:10: 'preferredUserInterfaceStyle' is unavailable: not available on iOS
```

### Reproducible Demo
N/A

**Comment by changLiuUNSW** [comment]
I get same issue.

**Comment by lukmccall** [comment]
I'm closing this thread because I'm pretty sure new version of XCode should fix it.
