### ISSUE TITLE
Getting push notification in client switches to that expo experience

### ISSUE THREAD

**Issue by raphaelrk** [expo/expo#5734]
### Environment

The latest expo client for SDK 35, downloaded from the app store on an iPhone X on iOS 13.

### Steps to Reproduce

- Have one expo project open
- Receive a notification from a different one
- Expo will switch to the other one when it gets a push notification for it

### Expected Behavior

- You stay in the original expo project you were working on

### Actual Behavior

- It switches to a different project

**Comment by AdamJNavarro** [comment]
Hey @raphaelrk,

Just for clarification, are you interacting with the notification at all or just simply receiving a notification is causing the client to switch experiences?

Cheers,
Adam

**Comment by raphaelrk** [comment]
Hey Adam,

Thank you for the reply. Simply receiving the notification causes the client to switch experiences. It's also probably not related to any recent commits as it's done this as long as I can remember.

Cheers,
Raphael
