### ISSUE TITLE
After Upgrade to SDK 33: undefined is not an object (evaluating '_expo Localization.Localization.locale')

### ISSUE THREAD

**Issue by tinyGoldfish** [expo/expo#5735]
## 🐛 Bug Report
Hello,

after Upgrading to SDK 33 I got the following error: "undefined is not an object (evaluating '_expo2.default.registerRootComponent), but before upgrade everything was fine. I got the below errors,

it first popped up this error:
![IMG_6665](https://user-images.githubusercontent.com/49922775/65394963-a6032d80-ddc6-11e9-8306-cb603b03fbee.PNG)

then 3 seconds later changed to this:
![IMG_E57C0E26D1E7-1](https://user-images.githubusercontent.com/49922775/65394919-0180eb80-ddc6-11e9-8940-4b5d459520df.jpeg)

### Environment
  Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.1.0

app's target: iOS

I just started learning Expo, please let me know if I need to provide more details.

Thanks very much,
SK

**Comment by andersravn** [comment]
Did you run `expo install expo-localization` and import it as `import * as Localization from 'expo-localization';`? As per the docs: https://docs.expo.io/versions/v33.0.0/sdk/localization/.

**Comment by kevinvugts** [comment]
> Did you run `expo install expo-localization` and import it as `import * as Localization from 'expo-localization';`? As per the docs: https://docs.expo.io/versions/v33.0.0/sdk/localization/.

I also experiencing this error.

**Comment by tsapeta** [comment]
How do you import `Localization` module? Also, please remember about showing us an example that will help us to reproduce the bug you're having.

**Comment by slauzinho** [comment]
I'm also having the same issue.

Here is a code example:

```javascript
import * as Localization from 'expo-localization';
const userLocaleCountryCode = Localization.country;
```

<img width="372" alt="Screenshot 2019-09-23 at 10 07 34" src="https://user-images.githubusercontent.com/445345/65413825-3010bd80-ddea-11e9-8870-9007155dee33.png">

**Comment by kevinvugts** [comment]
> How do you import `Localization` module? Also, please remember about showing us an example code that will help us to reproduce the bug you're having.

As you stated above.

**Comment by lukmccall** [comment]
Hi @slauzinho, `Localization.country` was changed to `Localization.region` and it's only available on iOS (in SDK 35).

**Comment by serhiipalash** [comment]
> It all happened after upgrading to xcode 13

I can confirm that this bug only happens in iOS 13 simulator and on iOS 12.2 everything works fine. Plus, this bug affect not only SDK 33, but also 34 and 35.

In SDK 34 app crashes in this line https://github.com/expo/expo/blob/master/packages/expo-localization/build/Localization.js#L4

![Simulator Screen Shot - iPhone 8 - 2019-09-22 at 20 37 31](https://user-images.githubusercontent.com/14208343/65415973-7e7c8700-ddff-11e9-8f64-c4e69252f47a.png)

**Comment by serhiipalash** [comment]
> It all happened after upgrading to xcode 13

@kevinvugts you can install iOS 12.2 in your new Xcode 13 and use its Simulator to continue your work today.

**Comment by andersravn** [comment]
Just to be clear. You guys mean Xcode 11 right? I guess you are confusing it with iOS 13.

**Comment by kevinvugts** [comment]
> > It all happened after upgrading to xcode 13
> 
> @kevinvugts you can install iOS 12.2 in your new Xcode 13 and use its Simulator to continue your work today.

Sure. Already did that. @andersravn I mean xCode 11 right. Sorry for the misconception

**Comment by tinyGoldfish** [comment]
> Did you run `expo install expo-localization` and import it as `import * as Localization from 'expo-localization';`? As per the docs: https://docs.expo.io/versions/v33.0.0/sdk/localization/.

Yes I did,  and I tried both iOS 13 and iOS 12.4.1 also not working.

**Comment by lukmccall** [comment]
I've created PR which may fix it.

However, it will be nice if you go to `settings > general > language and region` in your iOS simulator and update `region` setting. Then let me know if the `Localization` module starts working correctly.

**Comment by serhiipalash** [comment]
> You guys mean Xcode 11 right?

Yes, we do. Sorry, I was confused with first message about it.

**Comment by serhiipalash** [comment]
> However, it will be nice if you go to `settings > general > language and region` in your iOS simulator and update `region` setting. Then let me know if the `Localization` module starts working correctly.

It helps. After updating region all future app starts, even if you kill the simulator, don't crash.

**Comment by tinyGoldfish** [comment]
> I've created PR which may fix it.
> 
> However, it will be nice if you go to `settings > general > language and region` in your iOS simulator and update `region` setting. Then let me know if the `Localization` module starts working correctly.

Hi thanks! But sorry it still does not work for me, I tried both on my iphones iOS 12.4.1 & iOS13, and iOS 12.2 simulator on Xcode, all still got the same error.

**Comment by tinyGoldfish** [comment]
> I've created PR which may fix it.
> 
> However, it will be nice if you go to `settings > general > language and region` in your iOS simulator and update `region` setting. Then let me know if the `Localization` module starts working correctly.

Would there be any hot fixes for iphone testing directly as well? Many thanks!

**Comment by lukmccall** [comment]
Hi @tinyGoldfish, could you check if this bug occurred in iOS 13.1?
Please provide me with some information, because I'm struggling with reproducing this bug.

**Comment by serhiipalash** [comment]
@lukmccall there is no iOS 13.1 in Xcode Simulator, at least for now, but I tried to run our app in Expo app on my iPhone with iOS 13.1 and everything works fine. Also, as I understood, the bug happens only in iOS 13 Simulator.

**Comment by serhiipalash** [comment]
> the bug happens only in iOS 13 Simulator.

not in standalone or Expo-client app

**Comment by superKalo** [comment]
@serhiipalash , it happens on our side too. Both - in simulator and Expo-client. More details: https://forums.expo.io/t/updating-expo-sdk-to-v35-nsstring-cannot-be-converted-to-a-uicolor/28131

**Comment by superKalo** [comment]
@serhiipalash , it happens on our side too. Both - in simulator and Expo-client (on a real device). iOS 13.0. However, iOS 12 - all good.

Happens right after when you install the latest Expo-client on the simulator.

**Comment by serhiipalash** [comment]
@superKalo I've read your post and I don't see how it is related to this issue. This issue is about `expo-localization` module and not about `react-native-svg`, which is your post about.

**Comment by superKalo** [comment]
> @superKalo I've read your post and I don't see how it is related to this issue. This issue is about `expo-localization` module and not about `react-native-svg`, which is your post about.

Sorry, I shared wrong issue. Please see my updated [comment above](https://github.com/expo/expo/issues/5735#issuecomment-534992565).

**Comment by tinyGoldfish** [comment]
> Hi @tinyGoldfish, could you check if this bug occurred in iOS 13.1?
> Please provide me with some information, because I'm struggling with reproducing this bug.

Hi @lukmccall , thanks for the follow up, just tried again with the iOS 13.1 on my iphone, it's not working on my project neither...got the same error. 
Yes sure, what kind of other information you would like me to provide? Thanks a lot!

**Comment by superKalo** [comment]
@lukmccall do you think this issue happens on iOS simulator (iOS v13.0) only?

I tried to publish same app (which displays this error) on a different release channel and I opened it on a real device (iPhone, iOS v13.0) via Expo-client. It works just fine. I wonder if this error will appear on the standalone app, if I decide to update.

**Comment by bit-scrambler** [comment]
As per my understanding the problem is that if the phone (either device or simulator) has the default language because the user didn't set it, all the language properties like timezone, country, currency and so on are undefined raising the exception 
I'm able to reproduce the issue with iOS13 on a fresh simulator or on some devices.
Changing the language in "settings" to English/UK or English/US, the Localization.* properties are set properly.

**Comment by lukmccall** [comment]
@superKalo I think @bit-scrambler is right. This bug can occur not only in simulators. 

For now, I've added a fallback value to `locale property`. Unfortunately, I don't know when a new version with the fix will be available.

**Comment by serhiipalash** [comment]
> For now, I've added a fallback value to locale property.

@lukmccall do you mean that `locale`, `timezone`, `currency` properties could be `undefined`?

**Comment by lukmccall** [comment]
@serhiipalash, I was talking only about `locale` and `locales` properties. For some reason, iOS's function which should get system locale value return `null`.

**Comment by serhiipalash** [comment]
@lukmccall thanks for explanation, I just want to be sure that at least `region` still works and we can resolve app `locale` by `region` when user starts the app first time. Did you test `region`? Showing users app not in their native language will downgrade users retention a lot :(

**Comment by lukmccall** [comment]
@serhiipalashu unfortunately, `region` could fail too. Sorry for misleading you about this.

To sum everything up, `locale`, `locales` and `region` properties may not work correctly on iOS 13. I've added fallback values to `locale` and `locales` which should prevent an app from crashing. On the other hand, the `region` could be `null`.

 For now, we should wait for a system patch.

**Comment by jazzy-pm** [comment]
I am using localization only for **I18nManager**. Below you can find the code. The above issue is only coming for **iPhone pro 11 max** and the other version before this are working fine.

```
import * as Localization from "expo-localization";
....
 loadFonts = async () => {
    await Font.loadAsync({
      icomoon: require("@assets/fonts/icomoon.ttf"),
      Roboto_medium: require("../node_modules/native-base/Fonts/Roboto_medium.ttf")
    });
    const { isRTL } = await Localization.getLocalizationAsync();
    I18nManager.forceRTL(isRTL);
    await I18n.initAsync();
  };
....
```

**Comment by holgersindbaek** [comment]
Can anyone confirm that this is NOT happening in production apps?

**Comment by jacekd** [comment]
@holgersindbaek I have an app in production and so far we have no problems with any of the iOS 13 devices.

**Comment by morer62** [comment]
settings > General > Language & Region and pick the United State as a region ...... If your region is already US, you have to click again in united States and Update

**Comment by morer62** [comment]
This Uodate have to be made in your simulator

**Comment by CruelMoney** [comment]
Just got this on sdk 35 in the simulator, but after uograding to 36 it seems to be fixed 👌

**Comment by feliperaul** [comment]
@tsapeta Tomasz, won't this fix be backported to SDK 33, since it's still a supported SDK?

Just upgraded my XCode and I see the crash on my simulator.

Also, can the expo team confirm this won't affect real devices, only the simulator?

**Comment by marcelxsilva** [comment]
worked for me, here's what needs to be done: https://docs.expo.io/versions/latest/sdk/svg/

**Comment by sarcadass** [comment]
<img width="379" alt="Capture d’écran 2020-05-07 à 17 07 38" src="https://user-images.githubusercontent.com/2452603/81276190-43288300-9085-11ea-9342-fa30418798b4.png">

I still experience the problem here when I **start a simulator for the first time without setting the region on the iPhone preferences**. If the problem happen only on the Simulator it's not such a big deal as **the solution is to set the region in the simulator preferences** (even if a fix will be appreciated).
But if it happen too on real devices it's a **critical bug**, I don't have an iPhone on me so I can't test if the bug occur on real devices.

Is it possible to check if `locale` is not undefined before calling the `replace()` method?
And if `locale` is `undefined` you can fallback to English as it is the default language on the Simulator when you didn't set the region (`locale = locale || 'en-en'`).

**Comment by lukmccall** [comment]
@sarcadass, #8193 should fix it ;)

**Comment by drpiou** [comment]
So, hum hum, SDK 40, just as simple as that with real iOS device:

```javascript
import * as Localization from 'expo-localization';

console.log({ Localization });
```

throws : `Cannot read property 'locale' of undefined`.

And no, I didn't opened "Settings > General > Language & Region" **because** I do not expect my app users to do so on their side, it would be ugly to mention anything like that to anyone.

**Comment by DamianBarrionuevo** [comment]
I have a similar problem but I've been trying to fix it for a long time and I can't.
If they could help me they would save my time

![image](https://user-images.githubusercontent.com/54154159/131409748-510000e6-fe68-4f0a-86f5-1e640fe66c6c.png)


![image](https://user-images.githubusercontent.com/54154159/131409787-264d0998-4719-49cb-bf82-c7e1c853c136.png)
