### ISSUE TITLE
Please revert the default screen from "Featured Projects" to "Projects" or give users the option

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#5736]
It's a bigger issue than you might think given the number of times Expo must be restarted.

I have to restart the Expo app probably fifty times a day during development with Android (physical device) and Windows 7. This choice to change the default screen adds around fifty extra steps to development each day I work with Expo, and as far as I can tell there's no option to revert this.

**Comment by raajnadar** [comment]
Why do you need to restart your expo app again and again?

**Comment by Slapbox** [comment]
Expo is not fully stable or predictable and requires many restarts throughout the day.

**Comment by ide** [comment]
This will be fixed in the next release. It was an unintentional change.

**Comment by Slapbox** [comment]
Thanks for the update @ide!

PS: Overall stability is way better than when I started back with SDK 30. The Expo team is killing it!

**Comment by ide** [comment]
> PS: Overall stability is way better than when I started back with SDK 30.

We're working on it and will continue for the next couple of SDK releases. We now run our pure JS tests 4x (Android, iOS, web, Node (SSR)) and are steadily growing our integration tests for simulators and real devices to get there incrementally.
