### ISSUE TITLE
Unable to define the app language metadata to something else than English

### ISSUE THREAD

**Issue by vandrieu** [expo/expo#5738]
### Environment

expo diagnostics
  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.2 - ~/.npm-global/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.4 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.0.6

### Steps to Reproduce

1. Create a standalone app in a foreign language (e.g. french)

1. Try to find a setting to define the metadata language for your app in https://docs.expo.io/versions/latest/workflow/configuration/ and realize there is no such setting. The only setting that seems to be related to language is "locales" but the doc says it's used to "Provide overrides by locale for System Dialog prompts like Permissions alerts", this doesn't seem like what I need.

1. Submit it to the app store and set the main app language metadata to "french" in the "App Store Connect" website (the website where Apple requests you to define your app metadata like name, language, screenshots,...)

1. Check you app in the app store: the language is set to English because the app language metadata doesn't come from the "App Store Connect" metadata but from the build itself. Full story: I called Apple support to know why my app was listed as english while I set french in their "App Store Connect" website, and he told me this metadata comes from the binary build that I submitted, and if the build states it's an english app, or if it doesn't state any language then it's going to show english in the app store. He told me I need to define the language of my app in my build, by going into XCode, which of course I can't because it's a 100% Expo project.

### Expected Behavior

I expect app.json to provide a setting to define app language and I expect it to be documented here: https://docs.expo.io/versions/latest/workflow/configuration/

### Actual Behavior

It seems there is no such setting.
The only setting that seems to be related to language is "locales" but the doc says it's used to "Provide overrides by locale for System Dialog prompts like Permissions alerts", this doesn't seem like what I need.

### Reproducible Demo

See steps to reproduce

**Comment by AdamJNavarro** [comment]
Hey @vandrieu,

Since this is more so a feature that's missing rather than a bug, it'd be great if you could create a Feature Request on our [Canny board](https://expo.canny.io/feature-requests) (if one doesn't exist already). We try to reserve Github issues for reproducible bugs as best we can.

Cheers,
Adam

**Comment by jhogervorst** [comment]
*For anyone that also looks for a solution to this:*

It seems that you can override the locale of the iOS binary by setting the following in `app.json`:

```json
{
  "expo": {
    ...,
    "ios": {
      "infoPlist": {
        "CFBundleDevelopmentRegion": "nl"
      }
    }
  }
}
```

(Replace `nl` by your desired base locale.)

If you want the binary to support multiple locales, you can use the `locales` key in `app.json` as described in the [docs](https://docs.expo.io/versions/latest/distribution/app-stores/#localizing-system-dialogs-on-ios).
