### ISSUE TITLE
New Camera component not returning same image data as ImagePicker

### ISSUE THREAD

**Issue by btroia** [expo/expo#574]
Hi, thanks for the new `Camera` component! I'm working on replacing my current `ImagePicker`-based solution with `Camera` and it works well. _However_, after taking a photo I do not have access to all of the exif info (timestamp, etc.), width, height, etc. that`ImagePicker` does provide. It currently only returns the image path.

Any ideas regarding how I can access this information using `Camera`? Thanks!

**Comment by terribleben** [comment]
Hi, we don't support this yet, but someone is currently working on it, so we hope to ship this ability soon! (hopefully in the upcoming SDK release.)

Closing this for now as we try to limit this venue to bug reports. Let me know if you're still blocked on something, or feel free to follow up on the [forums](https://forums.expo.io).
