### ISSUE TITLE
Acesso aos arquivos da última build

### ISSUE THREAD

**Issue by emersonwdesigner** [expo/expo#5745]
Olá amigos,
É possível ter acesso ao arquivos .js da última Build? Deletei os arquivos acidentalmente e preciso recuperar.

**Comment by AdamJNavarro** [comment]
Hey @emersonwdesigner,

Infelizmente, isso não é possível, pois apenas uma versão minificada do pacote JS criado por uglify-es é enviada para a CDN. Seu código fonte não está disponível. Eu sugeriria fortemente o uso de alguma forma de armazenamento em nuvem, como o Github, para armazenar seu código regularmente e evitar instâncias como esta. No futuro, seria ótimo se você pudesse trazer uma pergunta como essa para nossos [Fóruns](https://forums.expo.io/).

Sorry if the message above is not clear as I had to use Google translate as I do not speak Portuguese. 

Cheers,
Adam
