### ISSUE TITLE
[docs] removal of dbflow not mentioned in android expokit upgrade instructions (expo 35)

### ISSUE THREAD

**Issue by Maddemacher** [expo/expo#5749]
https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit

I was unable to upgrade android to SDK 35 because of a dex issues with dbFlow
Looking at https://github.com/expo/expo/pull/5429/files it seems like dbFlow has been removed from app/build.gradle but it's not mentioned in the upgrade instructions

I removed the related lines from app/build.gradle and after that it built fine
```
annotationProcessor 'com.raizlabs.android:DBFlow-Compiler:2.2.1'
implementation "com.raizlabs.android:DBFlow-Core:2.2.1"
implementation "com.raizlabs.android:DBFlow:2.2.1"
```

**Comment by AdamJNavarro** [comment]
Hey @Maddemacher,

Thanks for bringing this to our attention. I just merged a PR from a community member adding this to our docs https://github.com/expo/expo/pull/5750.

Cheers,
Adam
