### ISSUE TITLE
Assets not working offline in production? 

### ISSUE THREAD

**Issue by Mohammadhunan97** [expo/expo#575]
Hi, I am working on an android app using create-react-native-app and my video assets and when the device is connected to the internet but don’t work when the device is not connected to the internet.

I’ve used the require syntax for every asset as they are all local files.
For instance require(’…/assets/videos/file1.mp4’)

Can anyone explain this? I used the standalone app docs to generate the apk and also tried the ejecting method in both cases the video assets didn’t work offline. Can anyone explain this??

I’ve been struggling with finding the solution for this for days and am not sure where to go to for support.

Note, I've asked a similar question on the forums and as I haven't gotten a solution yet, I thought I'd come here. Can anyone help?

**Comment by terribleben** [comment]
Hi, I responded to your [forum thread](https://forums.expo.io/t/assets-not-working-offline-in-production/2798/2). Did that adequately answer your question?

**Comment by Mohammadhunan97** [comment]
Not quite yet @terribleben , thanks for the help so far. I left an additional comment

 " Is there any other option that I have other than standalone app that will allow my assets to be available offline? I have quite a number of video assets and I’m not sure that caching them is a solution that will work for that much video data. (I have about 10gb of video assets that I would like to be on the device at all times; note: this is for a store kiosk that autoplays content related to the store not for the average user that’s why we have so much video content)."

also, I came across this in the expo docs(https://docs.expo.io/versions/v15.0.0/introduction/faq.html#what-is-the-difference-between-expo-and-react-native): 

> Images, videos, fonts, etc. are all distributed dynamically over the Internet with Expo. This means they work with instant updating and can be changed on the fly. The asset management system built-in to Expo takes care of uploading all the assets in your repo to a CDN so they’ll load quickly for anyone.


Anyway to block/prevent the uploading of assets to the cdn, and just get them local on the device?

**Comment by vlad-zhukov** [comment]
Is there an update on this? A guide on how to bundle assets within an app would be great!

**Comment by jhalborg** [comment]
@vlad-zhukov - You can't, at least not yet. See https://docs.expo.io/versions/latest/introduction/why-not-expo.html#its-not-currently-possible-to-bundle-assets-inside-of-standalone-apps-for-many-apps-this-is-a-dealbreaker-for-example-if-your-app-includes-100mb-of-images-and-you-need-them-to-be-available-immediately-when-the-user-opens-the-app-you-will-need-to-detacheject-when-you-publish-your-app-all-assets-that-you-import-with-require-in-your-app-are-uploaded-to-cloudfront-and-loaded-on-demand-when-requested-in-your-app--similar-to-how-a-webpage-works-this-has-the-benefit-of-allowing-you-to-update-any-asset-over-the-air-without-re-submitting-to-app-stores-but-it-isnt-ideal-for-every-situation-some-assets-need-to-be-available-immediately-when-the-app-loads-and-sometimes-there-are-a-lot-of-these-assets-in-these-situations-the-only-option-available-to-you-right-now-is-downloading-and-caching-assets-when-your-app-loads-we-are-working-on-making-it-possible-to-bundle-assets-with-your-standalone-app-while-also-preserving-the-ability-to-update-them-ota

**Comment by Unforgiven-wanda** [comment]
Ouch, this was literally the one thing I absolutely needed
Oh well, back to vanilla RN
I'll revisit expo when it has this feature :/

**Comment by jhalborg** [comment]
Any existing canny request for this feature/option yet, @terribleben ? Can't seem to find it, but it'd be immensely useful IMO. If it doesn't exist, I'll create one

**Comment by terribleben** [comment]
Hi guys, sorry for forgetting about this thread.

This is our [#1 feature request on canny](https://expo.canny.io/feature-requests/p/allow-standalone-apps-to-load-and-function-with-no-internet-connection) at the moment, and we are actively working on building it. (but it will be some time before we finish, because this is a large project and we really want to avoid breaking people's existing workflows.)

Closing this old-ish thread in favor of the canny thread for now. We're really excited to launch this when it's ready.
