### ISSUE TITLE
Paypal integration

### ISSUE THREAD

**Issue by ipod1987** [expo/expo#5751]
Hello everyone! I have a new request, there is the possibility to integrate Paypal with expo? I tried with many libraries but for issues integration I had failed.

Thanks advance

**Comment by AdamJNavarro** [comment]
Hey @ipod1987,

There isn't a way to integrate Paypal with a Managed Expo project. In the future, it'd be great if you could bring these types of questions to our [forums](forums.expo.io). We try to reserve Github issues for reproducible bugs as best we can.

Cheers,
Adam

**Comment by ipod1987** [comment]
Hi Adam, many thanks! 

Kind regards

**Comment by oron11** [comment]
Hi @ipod1987 

Did you manage to figure it out?

Thank you

**Comment by ipod1987** [comment]
Hi @oron11 Sadly no, very frustrated to work this, the only way that I saw from many post is with a webview
