### ISSUE TITLE
After upgrading to sdk 35.0.0 an get an error even after installing expo asset

### ISSUE THREAD

**Issue by GodwinEbikwo** [expo/expo#5758]
Some of your project's dependencies are not compatible with currently installed expo package version:
 - expo-asset - expected version range: ~7.0.0 - actual version installed: ^6.0.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages,

**Comment by humbertocruz** [comment]
I'am having  the same problem, after upgrade to SDK35 it's works for a while, suddentely only works on production mode. On dev mode it shows "The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit .. to elarn more about developing an Expo project.

my App.json
{
  "expo": {
    "name": "Expo Ppupex",
    "slug": "expo-poupex",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}

my package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "expo-constants": "~7.0.0",
    "expo-font": "~7.0.0",
    "expo-location": "~7.0.0",
    "mobx": "^5.13.0",
    "mobx-react": "^6.1.3",
    "native-base": "^2.13.8",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.2.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.6",
    "react-navigation-drawer": "^2.2.2",
    "react-native-screens":"~1.0.0-alpha.23",
    "react-navigation-stack": "^1.9.0"
  },
  "devDependencies": {
    "eslint":"6.4.0",
    "@babel/core":"7.6.2",
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.57.65",
    "babel-preset-expo": "^7.0.0",
    "typescript": "^3.6.3"
  },
  "private": true
}

thanks
