### ISSUE TITLE
ld: library not found for -lBolts

### ISSUE THREAD

**Issue by igor-lemon** [expo/expo#5760]
## 🐛 Bug Report
After update from 34 to 35 I have the error:
![image](https://user-images.githubusercontent.com/14764799/65530413-97209600-df00-11e9-95f0-d3b45710c01c.png)

The cache was cleaned. Node modules, old pods and podfile.lock files were removed.
If return back to 34 all compiles ok.

### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.9 => 4.0.9 
    npmGlobalPackages:
      expo-cli: 3.1.2

iOS

### Steps to Reproduce

Update from 34 to 35

**Comment by jvgaeta** [comment]
Same issue here. Looks like the linker flags need to be updated.

**Comment by igor-lemon** [comment]
Temporary fix, remove this flag manually
![image](https://user-images.githubusercontent.com/14764799/65725591-ba437500-e0bb-11e9-84fc-12c0eff31456.png)

**Comment by jvgaeta** [comment]
If you remove that flag, you'll just get other linker errors, no? For example, -l"EXAV" will also fail in my case and many others as well.

**Comment by jvgaeta** [comment]
Confirmed this is an issue with the linker flags. I looked at the output of my pod installation and removed packages from the linker flags that weren't installed via pod install.

**Comment by tsapeta** [comment]
After reading comments above, looks like there is a workaround for this issue. Because we no longer support ExpoKit, we're not going to fix this, however I recommend you to migrate to bare workflow (or managed if you can) where this workaround won't be needed.
