### ISSUE TITLE
Remove deprecated React methods like componentWillMount

### ISSUE THREAD

**Issue by ide** [expo/expo#5763]
There are several warnings of this nature that should be straightforward to change but require a careful pair of eyes:

```
    Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
    
    * Move code with side effects to componentDidMount, and set initial state in the constructor.
    * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: Icon

```

**Comment by esamelson** [comment]
there are a number of these warnings in NCL, among other places -- let's fix them during/as part of QA

**Comment by paulcabrera** [comment]
Any news about this warning? When is it coming a new update that fixes it?

**Comment by tsapeta** [comment]
@paulcabrera where specifically are you seeing this warning?

**Comment by paulcabrera** [comment]
> @paulcabrera where specifically are you seeing this warning?

When I run the expo in the device or simulator I'm getting `Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details. Please update the following components: Icon` .

I'm using Expo SDK 36

**Comment by brentvatne** [comment]
@paulcabrera - what version of @expo/vector-icons? or is this Icon component coming from somewhere else?

**Comment by paulcabrera** [comment]
I have installed "@expo/vector-icons": "^10.0.6", but I think it comes from somewhere else because I tried removing this from my screens and it still happens.

**Comment by paulcabrera** [comment]
I fixed by using this command: `grep -w -r componentWillMount node_modules/*`. 

`node_modules/expo/node_modules/@expo/vector-icons/build/Foundation.d.ts:        componentWillMount(): Promise<void>;`

I found that I have two libraries @expo/vector-icons and expo/node_modules/@expo/vector-icons and the second one includes `componentWillMount`, the second one is version 10.0.2. 

So I removed all node_modules and install again and now it works, it shows version 10.0.5.

**Comment by brentvatne** [comment]
odd, the version bundled with `expo` is `^10.0.2` and when combined with the dep of `^10.0.6` they should resolve to the same version. i wonder if this was a npm/yarn issue

**Comment by lmuntaner** [comment]
The version bundled with expo 36 `^10.0.2` shows the warning.

I installed `@expo/vector-icons` manually to use the latest version.

Shouldn't the latest version of Expo come with the latest?

**Comment by brentvatne** [comment]
the bundled version is not `10.0.2` it is `^10.0.2` which resolves to the latest version that is >= 10.0.2 and < 10.1.0, so it should resolve to `10.0.6`

see https://semver.npmjs.com/

**Comment by lmuntaner** [comment]
true, sorry 😳

**Comment by MehmetKaplan** [comment]
As suggested in warning of the ```expo start``` running ```npx react-codemod rename-unsafe-lifecycles``` in the root folder of the project did NOT solve my case.

The message that I receive are:

Please update the following components: SafeView, Transitioner

**Comment by mi-mazouz** [comment]
I have the same issue but somewhere else
<img width="1440" alt="Screen Shot 2019-12-18 at 10 41 44 AM" src="https://user-images.githubusercontent.com/24244248/71100450-0cf47080-2183-11ea-8a14-3e093f4801fe.png">

**Comment by marchingband** [comment]
i managed to cure this with 
`expo install @expo/vector-icons`

**Comment by MehmetKaplan** [comment]
Is there any progress on this? 

The warning may cause some other important ones to be missed.

**Comment by adriaanbalt** [comment]
@marchingband solution worked for me

**Comment by princefishthrower** [comment]
@marchingband's solution worked for me as well BUT don't forget to clean the expo cache with `expo r -c` - then the error for sure goes away 🙂  (as long as you aren't using `componentWillMount` anywhere else in your code 🙂

**Comment by MehmetKaplan** [comment]
Upgraded to Expo SDK 37 and this annoying warning persists. 

Just noticed it is deferred to Expo 38 (as of now)... :-/ https://github.com/expo/expo/pull/7227

Until then any (other) workaround suggestion? None of the mentioned methods solved my case and I have no clue where the warnings are coming from.

**Comment by ide** [comment]
You will need to debug further (e.g. monkey patch the warning and get it to print a stack trace) to determine where the warnings are coming from. This issue has been resolved with regard to the code in this repository (`git grep componentWillMount -- packages`) and other issues are likely to be in your npm dependencies or your own application code.
