### ISSUE TITLE
Problem with expoKeepAwake

### ISSUE THREAD

**Issue by fcabrera23** [expo/expo#5764]
Hi, im having some problems with expo-keep-awake.

Im using react native 0.59.8 and last version of expo-keep-awake and im getting the following error "Cannot ready property "activateKeepAwake" of undefined"

I checked in the function and the line ExpoKeepAwake.activate(tag); fails because ExpoKeepAwake is null..

**Comment by AdamJNavarro** [comment]
Hey @fcabrera23, could you provide us with a reproducible example of this, ideally in the form of a [Snack](snack.expo.io)?

Cheers,
Adam

**Comment by fcabrera23** [comment]
Hi, I uploaded a test project to bitbucket, just clone,  npm install and react-native run android will do it...

https://bitbucket.org/francisco_cabrera/keepawaketest/src/master/

I have tried both Hook and function, neither works..

Thanks for your help

**Comment by fcabrera23** [comment]
@AdamJNavarro  could you test the issue?

**Comment by pabloluz** [comment]
Similar issue here: `Cannot read property 'activate' of undefined`

I'm on RN 0.61.2

**Comment by lukmccall** [comment]
Hi everyone, I've tested `KeepAwake` and everything seems to work fine. 

It's worth to mention that I tested it using SDK 36. 

For now, I'm closing this issue. However, feel free to reopen it if this bug still occurs.

**Comment by baotoan1905** [comment]
I got the same issue, not sure how to fix ? I'm using react-native 0.61.5 and unimodules 0.9.0

**Comment by lukmccall** [comment]
@baotoan1905, please create a separate issue for this and add the required information there (from issue template). 

It'll be nice if you could provide us with a reproducible example - I think that GitHub repo will be the best idea here. 

Thanks in advance ;)
