### ISSUE TITLE
iOS 13: Expo-localization -> Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by RoromiDev** [expo/expo#5768]
### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.1 - /usr/local/opt/node@8/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.9 => 4.0.9 
    npmGlobalPackages:
      expo-cli: 3.1.2

### Steps to Reproduce

On iOS 13 only, I have Cannot read property 'replace' of undefined when i try to import expo-localization.
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-25 at 13 40 28](https://user-images.githubusercontent.com/20064333/65597705-0b5b4800-df9a-11e9-9722-63342a304fec.png)

**Comment by lukmccall** [comment]
I think, It may be related to #5735.

**Comment by Zmeu213** [comment]
I got same error after updating expo. Solved by removing `node_modules` and `package-lock.json` and then running `npm i`. But i got this https://github.com/expo/expo/issues/5769 after it

**Comment by Zmeu213** [comment]
Hey @RoromiDev, check if https://github.com/expo/expo/issues/5735#issuecomment-534063072 solves your issue. It solved mine.

**Comment by mskg** [comment]
Just switch the language once in the simulator und the error is gone.
