### ISSUE TITLE
Expo cant find StoreReview

### ISSUE THREAD

**Issue by Zmeu213** [expo/expo#5769]
## 🐛 Bug Report

```
Unable to resolve "./StoreReview/StoreReview" from "node_modules/expo/build/ExpoLazy.js"
Failed building JavaScript bundle.
```

### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
      npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.1.2

Simulator (iPhone 8 - 13.0)

### Steps to Reproduce

No idea. This error appear after updating expo by `npm i` in working project

### Expected Behavior

Project would start as usual

### Actual Behavior

Got error 
![image](https://user-images.githubusercontent.com/8945959/65607497-55055c00-dfb5-11e9-9b7d-0a80c5096ba4.png)

**Comment by lukmccall** [comment]
Hi @Zmeu213, could you send me your package.json file content?

**Comment by Zmeu213** [comment]
@lukmccall sure, here are list of dependencies from it (im not sure I can share entire project or its parts)

```
"dependencies": {
    "@expo/vector-icons": "^10.0.2",
    "expo": "^35.0.0",
    "expo-analytics": "^1.0.11",
    "expo-asset": "~7.0.0",
    "expo-av": "~7.0.0",
    "expo-constants": "~7.0.0",
    "expo-font": "~7.0.0",
    "expo-image-picker": "~7.0.0",
    "expo-localization": "~7.0.0",
    "expo-secure-store": "~7.0.0",
    "expo-store-review": "^1.0.0",
    "fastlane": "^0.1.0",
    "fetch": "^1.1.0",
    "node-fetch": "^2.1.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-auto-grow-textinput": "^1.2.1",
    "react-native-autolink": "1.6.0",
    "react-native-check-box": "^2.1.7",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-detection": "^0.2.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-image-zoom-viewer": "^2.2.25",
    "react-native-iphone-x-helper": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.6.0",
    "react-native-markdown-renderer": "^3.2.8",
    "react-native-masonry-layout": "^1.0.6",
    "react-native-material-menu": "^0.4.1",
    "react-native-modal": "^6.5.0",
    "react-native-modal-overlay": "^1.3.1",
    "react-native-motion": "^1.0.0",
    "react-native-really-awesome-button": "^0.8.3",
    "react-native-reanimated": "^1.1.0",
    "react-native-simple-dialogs": "^1.1.0",
    "react-native-slider": "^0.11.0",
    "react-native-tag-autocomplete": "^1.0.21",
    "react-navigation": "^3.11.1",
    "react-navigation-transitions": "^1.0.4",
    "react-redux": "^5.0.7",
    "react-sticky-state": "^2.1.9",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "request-promise-native": "^1.0.5",
    "scoo-lib": "file:../scoo/frontend/scoo-lib",
    "sentry-expo": "~1.13.0",
    "socket.io-client": "^2.1.1",
    "underscore": "^1.9.1"
  },
  "devDependencies": {
    "@babel/runtime": "^7.1.5",
    "@welldone-software/why-did-you-render": "^3.3.3",
    "babel-eslint": "^10.0.1",
    "babel-preset-expo": "^5.0.0",
    "eslint-config-react-app": "^3.0.5",
    "eslint-plugin-flowtype": "^3.2.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "exp": "^57.2.1",
    "expo-cli": "^3.1.2",
    "google-spreadsheet-to-json": "^1.0.0",
    "jest-expo": "^35.0.0",
    "react-devtools": "^3.2.3",
    "react-native-root-toast": "^3.0.1",
    "schedule": "^0.4.0",
    "standard": "^12.0.1"
  },
```

you could find `expo-store-review` in it, i tried to install it with npm after error appeared but it no effect

**Comment by lukmccall** [comment]
Here everything it looking fine. Could you send me your app.json file too?

**Comment by Zmeu213** [comment]
@lukmccall again, not sure about sharing sensitive project parts, but sdkVersion is 35
```
"sdkVersion": "35.0.0",
```

**Comment by AdamJNavarro** [comment]
Hey @Zmeu213,

Can you let me know how you're importing StoreReview? Initially we forgot to update the docs, but as of SDK35 the StoreReview module has been pulled out of the Expo scope and should be imported like so: `import * as StoreReview from 'expo-store-review'`

Cheers,
Adam

**Comment by Zmeu213** [comment]
Hi @AdamJNavarro !

Thats most interesting part. I dont import `StoreReview` anywhere in the project. I dont use this module at all. Stacktrace points to `expo/build/ExpoLazy.js` but there is no such import statement here either. I cant get what exactly requires this module.

**Comment by ElijahBrandyberry** [comment]
I am having the same issue.  I am running Expo Kit with Expo SDK 25.  Let me know if it would be helpful to upload my `package.json`

**Comment by ElijahBrandyberry** [comment]
I do not import `StoreReview` anywhere in my project either.  After searching for it the only reference to `expo-store-review` is in `expo/build/removed.js` which doesn't appear to be requiring it.

**Comment by AdamJNavarro** [comment]
Hey @Zmeu213 and @ElijahBrandyberry, we have reason to believe this could be a cache issue. Could you try clearing all pertinent caches and see if that does anything?

**Comment by ElijahBrandyberry** [comment]
@AdamJNavarro  I have run `npm cache clean -f` and run the "Clean" command in Xcode.  Is there another cache that needs cleared?

**Comment by ElijahBrandyberry** [comment]
If anyone else runs into this issue after upgrading the Expo SDK, run `expo r -c` to clear the expo cache as well as `npm cache clean -f`.  Thanks for the help!

**Comment by JaimeRamos99** [comment]
i had the same issue and @AdamJNavarro was right it is a cache issue.

**Comment by sydney900** [comment]
Thanks so much.  run expo r -c and npm cache clean -f works for me. 
But if enable OPTIMIZE ASSETS, publish will be stuck for ever

**Comment by Zmeu213** [comment]
Yup, cache cleaning helped, but then i got this bug https://github.com/expo/expo/issues/5735 and solved it thanks to this comment https://github.com/expo/expo/issues/5735#issuecomment-534084362

**Comment by miguelmaquieira** [comment]
> If anyone else runs into this issue after upgrading the Expo SDK, run `expo r -c` to clear the expo cache as well as `npm cache clean -f`. Thanks for the help!

running **expo r -c** did the work. Thanks
