### ISSUE TITLE
Missing steps from ExpoKit 35 Update instructions (update pods)

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#5774]
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.11 => 5.1.11 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.1.2

ExpoKit project, building in iOS.

### Steps to Reproduce

Upgrade from ExpoKit 34 (followed instructions on blog)

### Expected Behavior

Runs on iOS

### Actual Behavior

Build fails:
```
error: Build input file cannot be found: '/Users/Julian/Projects/headsup-mobile/node_modules/expo/node_modules/expo-web-browser/ios/EXWebBrowser/EXWebBrowser.m' (in target 'EXWebBrowser' from project 'Pods')
```

Additional I followed to get it to build:

```
cd ios
rm Podfile.lock
rm -rf Pods
pod install
pod update
```

Also, updating the FBSDK libraries, but I think those aren't a part of expokit.

**Comment by JulianKingman** [comment]
Change `import Sentry from "expo-sentry"` to `import * as Sentry from "expo-sentry"`

**Comment by cruzach** [comment]
That change in import statement i reflected in [Expo's sentry docs](https://docs.expo.io/versions/latest/guides/using-sentry/), was that the final fix?

Also, running pod update then pod install is already specified in the docs. Let me know specifically what's missing and I can add it in
