### ISSUE TITLE
After upgrading to SDK 35, works for a white, suddentely clains about is not a expo app.

### ISSUE THREAD

**Issue by humbertocruz** [expo/expo#5775]
### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19.2 (Tina)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @types/react: ^16.8.23 => 16.9.3 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.9 
    npmGlobalPackages:
      expo-cli: 3.1.2

my primary target is Android, also iOS on a later time

### Steps to Reproduce

expo init new-expo-project
use yarn
yarn start and open genymotion simulator

### Expected Behavior

open first app screen

### Actual Behavior
shows Expo SDK requires expo to run but expo modules area unavailable and this code is not runing on expo.

### Reproducible Demo

It's happing create a new app with expo init

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->

**Comment by humbertocruz** [comment]
seens to be something to do with expo-constants

**Comment by cruzach** [comment]
Maybe this is related to the genymotion sim? I was able to run a brand new SDK 35 project on both Android and iOS with no problems. We recommend using the [Android Studio Emulator](https://docs.expo.io/versions/latest/workflow/android-studio-emulator/)

**Comment by cruzach** [comment]
@humbertocruz were you able to reproduce this outside of genymotion?
