### ISSUE TITLE
Images can't load in production environment

### ISSUE THREAD

**Issue by cristiankmb** [expo/expo#5776]
Hi Guys,

i have a problem in production environment, as in develop environment don’t happen. This problem is happen since i updated to Expo SDK Version 34.0.0

I have an array contain 12 items, item is image, which images weight is average 100kb and size is 720x2560. This array is render with a FlatList vertical.

Each images is local storage and i use asset tools to download async each image.

In develop environment with expo star and simulator and different device both iOS as Android the app run correctly even when in the DevTools production mode is active.

But when i build a .apk as “expo build:android --no-publish” or “expo build:android” or upload with “expo publish” the images in the production app never can see, only can see a white image.
(This process too happen with a .ipa)

I updated .apk and .ipa in the store create a new project with the last Expo SDK Version, i changed images for low weight images and low size, Sentry never notify this as a bug.

Any idea? Thank

package.json:

```
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/netinfo": "4.2.2",
    "eslint-config-rallycoding": "3.2.0",
    "expo": "^34.0.1",
    "expo-analytics": "1.0.11",
    "expo-asset": "6.0.0",
    "expo-av": "6.0.0",
    "expo-font": "6.0.1",
    "expo-image-picker": "6.0.0",
    "expo-linear-gradient": "6.0.0",
    "expo-permissions": "6.0.0",
    "expo-video-player": "1.2.0",
    "firebase": "4.6.2",
    "firebase-admin": "8.6.0",
    "firebase-functions": "1.0.2",
    "jetifier": "1.6.4",
    "lodash": "4.17.15",
    "moment": "2.19.1",
    "native-base": "2.13.4",
    "prop-types": "15.6.2",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-app-intro": "1.1.5",
    "react-native-aws3": "0.0.8",
    "react-native-dropdownalert": "3.1.2",
    "react-native-gesture-handler": "1.4.1",
    "react-native-i18n": "2.0.5",
    "react-native-reanimated": "1.2.0",
    "react-native-router-flux": "4.0.5",
    "react-native-unimodules": "0.7.0-rc.1",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-logger": "3.0.6",
    "redux-persist": "4.8.2",
    "redux-thunk": "2.2.0",
    "sentry-expo": "2.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.54.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

app.json:

```
{
  "name": "",
  "displayName": "",
  "expo": {
    "name": "",
    "slug": "",
    "privacy": "unlisted",
    "sdkVersion": "34.0.0",
    "version": "2.7.0",
    "entryPoint": "node_modules/expo/AppEntry.js",
    "orientation": "portrait",
    "primaryColor": "#FFFFFF",
    "platforms": [
      "ios",
      "android"
    ],
    "icon": "./assets/icons/app-icon.png",
    "splash": {
      "image": "./assets/icons/bg-splash.png",
      "resizeMode": "cover"
    },
    "notification": {
      "icon": "./assets/icons/notification-icon.png"
    },
    
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "",
            "project": "",
            "authToken": ""
          }
        }
      ]
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4"
      ]
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "",
      "icon": "./assets/icons/ios/app-icon.png",
      "buildNumber": "1"
    },
    "android": {
      "permissions": [],
      "package": "",
      "versionCode": 26
    }
  }
}

```

**Comment by cruzach** [comment]
Hi! Looks like your question was already answered [here on our forums](https://forums.expo.io/t/images-cant-load-on-production-environment/28216). For anyone else coming here with the same question - when you publish assets to the CDN, only those that are explicitly required will be picked up by the packager which may explain why you are not seeing them in a production environment. 

As a side note, to provide the best experience to your end users regarding assets like these, it's best to [bundle them into your binary](https://docs.expo.io/versions/v35.0.0/guides/offline-support/#bundle-your-assets-inside-your-standalone-binary)
