### ISSUE TITLE
expo-keep-awake Android Build Error

### ISSUE THREAD

**Issue by Johnsonzhangc** [expo/expo#5777]
### Environment

  Expo CLI 2.19.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.19.5

App Target: Android

### Steps to Reproduce

React-Native Run-Android result in following error: 
> Task :expo-keep-awake:compileDebugJavaWithJavac FAILED
/Users/zhangce/Documents/iMenu-1.9.8/node_modules/expo-keep-awake/android/src/main/java/expo/modules/keepawake/ExpoKeepAwakeManager.java:22: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/zhangce/Documents/iMenu-1.9.8/node_modules/expo-keep-awake/android/src/main/java/expo/modules/keepawake/KeepAwakeModule.java:29: error: method does not override or implement a method from a supertype
  @Override
  ^
2 errors

FAILURE: Build failed with an exception.

**Comment by cruzach** [comment]
What version of `expo-keep-awake` are you using? Also, I'm assuming this is a bare project?

**Comment by Johnsonzhangc** [comment]
> What version of `expo-keep-awake` are you using? Also, I'm assuming this is a bare project?

Hi cruzach,

Yes, It is a bare project. And here are the version number of major libraries:

- "expo-keep-awake": "^7.0.0",
-"react-native": "0.59.8"

**Comment by cruzach** [comment]
Hm, I just tried this on a blank `expo init` bare project, ran `yarn add expo-keep-awake`, using this code:
```
import React from "react";
import { Text, View } from "react-native";
import { useKeepAwake } from "expo-keep-awake";

export default function App() {
  useKeepAwake();
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>This screen will never sleep!</Text>
    </View>
  );
}
```
And was able to run successfully. Have you [configured unimodules](https://github.com/unimodules/react-native-unimodules)?

**Comment by Johnsonzhangc** [comment]
Thanks cruzach,

I also created a new bare project, it seems no problem. 

My project is a long time project, and was initialized by expo init - base minimum. I am using a bunch of other expo libraries as well. 

Do you think is it possible because of the following configuration in build.gradle?
classpath 'com.android.tools.build:gradle:3.3.2'

In the newly created project, is was 3.3.0, and has no problem.

But seems only 3.3.2 can work with my google firebase library.

**Comment by Johnsonzhangc** [comment]
I manage to adjust the classpath to 3.3.0, but still have the same error for me.

**Comment by cruzach** [comment]
What version of `react-native-unimodules` do you have installed?

**Comment by Johnsonzhangc** [comment]
"react-native-unimodules": "0.4.0"

**Comment by cruzach** [comment]
That version was released about 4 months ago. Since you're using the most recent version of the `expo-keep-awake` module, I'd try upgrading that to v5 (in the bare project I tested on and had this working, it was set to `"react-native-unimodules": "~0.5.4"`)

**Comment by Johnsonzhangc** [comment]
Thanks a lot. Let me try it.
