### ISSUE TITLE
Video fullscreen playback when orientation is fixed to portrait

### ISSUE THREAD

**Issue by soukupl** [expo/expo#578]
Hello,
if I set orientation to portrait only in app.json, <Video> in fullscreen is also locked to portrait only. Is it possible to temporarily "release" the orientation lock when Video is playing and is switched to fullscreen?

Example... I would like to lock the full application to only allow use in portrait mode, but when user starts watching any video (via Expo's <Video> or possibly any other component) and switch to fullscreen, app should allow rotation to landscape... 

Not sure if this is easy to implement for your <Video> component... If it would be possible, we can have some API function to tell the Expo "app frame" to allow rotation or manually switch to orientation from portrait to landscape and then back.

**Comment by terribleben** [comment]
Hello there! You can change which orientations your app supports at runtime using our [ScreenOrientation](https://docs.expo.io/versions/latest/sdk/screen-orientation.html#content) api.

We usually try to limit this venue to bug reports so I'll close this issue. We'd be happy to help answer more questions on the [forums](https://forums.expo.io). :)

**Comment by abi** [comment]
@soukupl Here's how I did it: https://github.com/expo/harvard-cs50-app/blob/master/screens/WeekScreen.js#L113
