### ISSUE TITLE
Expo SDK35 not working with react-native-webview

### ISSUE THREAD

**Issue by Flaxinnovations** [expo/expo#5780]
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.8.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.1.2

Environments: iOS and Android

### Steps to Reproduce

Import react-native-weview (version ^7.0.5)
Create a simple site that sends a postMessage on e.g. a button press
Try to console log something in the onMessage

Result: onMessage is never called

### Expected Behavior

The onMessage should be called.

### Actual Behavior

The onMessage does not get called.

**Comment by linus** [comment]
It seems (from react-native-webview issues) that postMessage is now on another property, see e.g. https://github.com/react-native-community/react-native-webview/issues/726 -- does that work for you?

**Comment by Flaxinnovations** [comment]
Thanks Linus. We fixed the problem.
