### ISSUE TITLE
[AppleAuthentication][Managed app][iOS] Standalone: AuthorizationError error 1000

### ISSUE THREAD

**Issue by jamesbechet** [expo/expo#5781]
## 🐛 Bug Report
I am able to sign in with apple when I'm using my app through the iOS Expo Client. However, I'm having an error in my standalone app

The error:
```
The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)
```

The code:
```
try {
      const data = await AppleAuthentication.signInAsync({
        requestedScopes: [
          AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
          AppleAuthentication.AppleAuthenticationScope.EMAIL
        ]
      })
} catch (error) {
// the error happens here
}
```

I suspect it's a configuration issue, but I followed the steps in:
- https://github.com/expo/expo/tree/master/packages/expo-apple-authentication
- I also added `ios.usesAppleSignIn` to my `app.json`

Any ideas what could be the issue?

### Environment
Production - Managed App - Standalone iOS

### Steps to Reproduce
N/A

### Expected Behavior
Pressing the sign in button should open the sign in modal.

### Actual Behavior
Pressing the sign in button throws an error.

### Reproducible Demo
N/A

**Comment by danmaas** [comment]
I'm experiencing the same thing, with the same error message: `ERR_APPLE_AUTHENTICATION_REQUEST_FAILED: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)`

**Comment by esamelson** [comment]
Hi, just want to acknowledge that we're looking into this. Not sure yet where the problem is but will update here when we have more information.

**Comment by hasis** [comment]
+1 to this issue. Are the SPF steps in `https://developer.apple.com/account/resources/services/configure` necessary for this to work on a TestFlight build?

**Comment by danmaas** [comment]
I haven't run that Apple email Domain Verification step yet. Wonder if that's the problem.

(I'm currently struggling to get the domain verification, it seems like Apple has odd restrictions on SSL https://forums.developer.apple.com/thread/122594)

**Comment by tsapeta** [comment]
> I wonder if it has something to do with needing to update the entitlements in the distribution profile that the .ipa is signed with. I saw some mentions about needing to re-generate the profiles when turning on new entitlements.

Yeah, I think it might be needed. Could you try to run a new build with `expo build:ios --clear-provisioning-profile --revoke-credentials` which should recreate a new provisioning profile with updated capabilities inside. Let me know if it doesn't help 🙂

**Comment by danmaas** [comment]
It worked, thank you @tsapeta ! Would be great to update the documentation to add this step :)

**Comment by tsapeta** [comment]
Yeah, that's good point, we will update the documentation 😉 
Thank you for checking it out and reporting this thing to us! 🙏

**Comment by hasis** [comment]
Thanks folks! Above also helped me. Verification step from Apple is **not** required, despite the misleading documentation on their side. 

> Sign In with Apple
>Allow users to set up an account and sign in to your apps and associated websites with the Apple > IDs they already have. Configuration is required to communicate with your users and receive > updates from Apple.

https://developer.apple.com/account/resources/services/list

**Comment by imbudhiraja** [comment]
@tsapeta @danmaas Getting the same error but my project is completely native. Can you help me with this. 

```
{ [Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)]
  framesToPop: 1,
  code: 'ERR_APPLE_AUTHENTICATION_REQUEST_FAILED',
  domain: 'RCTErrorDomain',
  userInfo: null,
  nativeStackIOS: 
   [ '0   parkao                              0x0000000108617957 RCTJSErrorFromCodeMessageAndNSError + 135',
     '1   parkao                              0x00000001085a7d03 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 179',
     '2   parkao                              0x00000001081877cc __62-[EXAppleAuthentication requestWithOptions:resolver:rejecter:]_block_invoke + 268',
     '3   parkao                              0x000000010818a366 -[EXAppleAuthenticationRequest authorizationController:didCompleteWithError:] + 118',
     '4   libdispatch.dylib                   0x000000010ba12df8 _dispatch_call_block_and_release + 12',
     '5   libdispatch.dylib                   0x000000010ba13d6c _dispatch_client_callout + 8',
     '6   libdispatch.dylib                   0x000000010ba21e24 _dispatch_main_queue_callback_4CF + 1500',
     '7   CoreFoundation                      0x00007fff23b0ce49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9',
     '8   CoreFoundation                      0x00007fff23b07aa9 __CFRunLoopRun + 2329',
     '9   CoreFoundation                      0x00007fff23b06e66 CFRunLoopRunSpecific + 438',
     '10  GraphicsServices                    0x00007fff38346bb0 GSEventRunModal + 65',
     '11  UIKitCore                           0x00007fff47578dd0 UIApplicationMain + 1621',
     '12  parkao                              0x00000001080f5d10 main + 112',
     '13  libdyld.dylib                       0x00007fff516ecd29 start + 1' ],
  line: 1795,
  column: 26,
  sourceURL: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false' }
```

**Comment by danmaas** [comment]
Make sure the "Apple Sign-in" entitlement is added to your build settings. If you're running a development build, try switching to a production build. You might need to go as far as signing the app bundle for Ad Hoc distribution and installing it that way, vs. running in Xcode.

**Comment by imbudhiraja** [comment]
@danmaas Okay, Thanks for your help. Working in released bundle.

**Comment by mvpscottjon** [comment]
don't forget add apple sign-in capabilities at xcode target project

**Comment by shakyarahul** [comment]
@tsapeta bro how to do it in react-native without expo (expo build:ios --clear-provisioning-profile --revoke-credentials)

**Comment by MattGoldwater** [comment]
I'm getting this error only when I run it on a custom expo client on my phone. Why could that happen? Could this indicate potential issues in production?

**Comment by dankras** [comment]
@danmaas @mvpscottjon thanks for the tips! is "make sure the "Apple Sign-in" entitlement is added to your build settings." and "don't forget add apple sign-in capabilities at xcode target project" relevant for managed Expo projects? If so, how would one go about making those changes?

**Comment by danmaas** [comment]
Adding the entitlement is only relevant if you are building the app with Xcode. In managed mode Expo does the build for you so they are responsible for that setting.

**Comment by dankras** [comment]
ah got it!

I'm still having jamesbechet's original issue even after building with `expo build:ios --clear-provisioning-profile --revoke-credentials` 😢 

same setup as his: everything works great in the iOS Expo Client, but in the standalone app the sign in modal doesn't open and instead get the error.

anyone know of any other magical tips?

**Comment by tsapeta** [comment]
@dankras, do you have `expo.ios.usesAppleSignIn` set to `true` in your `app.json`? If not, then try to add this and make another build 🙂 This lets our builders know to add appropriate entitlements and capabilities to your app.

**Comment by dankras** [comment]
@tsapeta yessir, that's `true`

**Comment by dankras** [comment]
(was poking around the commits for `expo-apple-authentication` - perhaps @bbarthec or @esamelson might know a good way to debug?)

**Comment by tsapeta** [comment]
> does that look right? anything else worth checking / any other ways to debug why this may be misbehaving?

Yeah, it looks right. That's the same that we use in Expo Client: https://github.com/expo/expo/blob/ca91e1bedf1edc0f7b8e8812c7a143dea0e838e2/ios/Exponent/Supporting/Exponent.entitlements#L7-L10
I'm not sure if there is anything more to check, let me investigate this 🙂

**Comment by ChesterLaborde** [comment]
Having the same issue as @dankras , `"usesAppleSignIn": true` and running `expo build:ios --clear-provisioning-profile --revoke-credentials`. Building simulator IPA and it's not working, I'm testing with archive build now to see if it changes anything

**Comment by andreas-arkulpa** [comment]
same behavior here.

**Comment by tsapeta** [comment]
@ChesterLaborde have you been able to test the archive build? I'm afraid Apple Authentication may not work very well on simulators 🤔

**Comment by ChesterLaborde** [comment]
@tsapeta the archive build worked like a charm. Odd that it's not working as expected on a simulator

**Comment by tsapeta** [comment]
@ChesterLaborde thank you for the feedback then 🙂 And yeah, you're right. I'll try to make it more clear and return a better error message in that case.

**Comment by JinZhe34** [comment]
@tsapeta In my case, Apple Sign is working well on a simulator using expo. but "Share my email" option not showing on standalone. (share email option is showed on a simulator). could you let me know why it happens and how to fix it? thanks

**Comment by lkeshavan** [comment]
it used to run on simulators just fine. But now it isn't. I'm getting the same error

**Comment by oron11** [comment]
Apple sign-in doesn't work for me either after simulator build.

**Comment by ARMATAV** [comment]
Verified, does not work with the simulator build - works with the archive build when you sign it accordingly https://docs.expo.io/distribution/building-standalone-apps/ 

Sign in With Apple works in the Expo app when you're developing assuming you're using the `host.exp.exponent` (?) Service ID.
