### ISSUE TITLE
Error building Expo web

### ISSUE THREAD

**Issue by Arlen22** [expo/expo#5782]
I'm trying to build my app for expo web, and after running into several snags, I turned off all my config files, including tsconfig.json, and just ran build:web, and this is the error I'm getting now. 

The @expo/vector-icons package is required in globals.web.

```plain
/react-native-expo-35/com.github.arlen22.reactnative.sdk35/node_modules/@expo/vector-icons/build/createIconSet.js
SyntaxError: /react-native-expo-35/com.github.arlen22.reactnative.sdk35/node_modules/@expo/vector-icons/build/createIconSet.js: Unexpected token (36:27)

  34 |             render() {
  35 |                 if (!this.state.fontIsLoaded) {
> 36 |                     return <Text />;
     |                            ^
  37 |                 }
  38 |                 return (<RNVIconComponent ref={view => {
  39 |                     this._icon = view;
```

**Comment by Arlen22** [comment]
I guess this belongs on expo-cli

**Comment by Bulatbik** [comment]
Any idea how you solved this? I'm experiencing the same problem right now.

**Comment by ganzonoble** [comment]
Same problem here :-/

**Comment by Arlen22** [comment]
In that case I'm going to reopen it because I think you can move issues if necessary.

**Comment by EvanBacon** [comment]
Please provide a repro

**Comment by Arlen22** [comment]
I can't reproduce it now, so maybe it was fixed, but it was a really strange error, because the offending module was loaded by globals.web.js so it would have been really obvious to anyone trying to run it. 

The only way I am able to reproduce it in a fresh `expo init` (blank, typescript) is by disabling my babel.config.js file, which contains the all-important "babel-preset-expo" preset. So basically it's a PEBKAC, but it's not obvious when you look at the error why it would be doing that. 

I'm pretty sure this is the only reason that error would happen, because obviously all code in node_modules and everywhere else goes through babel and get's built together, which makes sense for tree-shaking and other things. 

So make sure your babel-preset-expo or equivalent is actually set. Even though this is an expo managed app, you're quite free to tweak things to your needs, I guess.

**Comment by Truth1984** [comment]
same issue here, I guess it's a babel parsing issue because of "syntax error"

**Comment by Truth1984** [comment]
@EvanBacon 

1. `$ expo init pn`  _(choose tabs)_

2. ``` bash
cd pn
mkdir public
echo '<html><body><div id="root"></div></body></html>' > ./public/index.html
mkdir src
# better use vscode to mv
mv app.js ./src/app.js 
echo 'import React from "react";import myapp from "./src/App";export default class App extends React.Component {render() {return <myapp />;}}' > App.js
echo 'import React from "react";import ReactDOM from "react-dom";import App from "./App";ReactDOM.render(<App />, document.getElementById("root"));' > ./src/index.js
```

3. move 'assets','components','constants','navigation','screens' into src.

4. use `react-scripts start`

**Comment by EvanBacon** [comment]
If anyone has any input on where I should put educational material regarding this please let me know. Because the scope of this project is so large I won't be able to support `react-scripts` or `react-native-cli` directly.
