### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:19001 Error: connect ECONNREFUSED 127.0.0.1:19001     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

### ISSUE THREAD

**Issue by thejasreeb** [expo/expo#5789]

**Comment by cruzach** [comment]
You might want to check [this issue](https://github.com/expo/expo/issues/2115) out. Closing due to lack of information

**Comment by thejasreeb** [comment]
if we run expo build:android this command - we are getting this error ---connect ECONNREFUSED 127.0.0.1:19001 Error: connect ECONNREFUSED 127.0.0.1:19001 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

**Comment by JavatarSRB** [comment]
Mostly every time I had this issue since the update in the expo-cli is to "expo start -c" which will clear the cache for you and will fix the issue you have. Other solutions mentioned in the question referred to you by cruzach is not working for a while now.

**Comment by VitaliKaniushok** [comment]
I have the same problem

**Comment by creditcoder** [comment]
I have also this problem. Any news about this?

**Comment by brentvatne** [comment]
can someone who is having this problem please create a new issue and fill out the issue template correctly? it'd be better to post the issue here: https://github.com/expo/expo-cli/issues - thank you!
