### ISSUE TITLE
Front Camera doesn't work in iOS, works in Android [expo 20.0.0]

### ISSUE THREAD

**Issue by vysakh0** [expo/expo#579]
```js
# App.js
import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity, Image, TextInput, StatusBar } from 'react-native';
import { Camera, Permissions } from 'expo';

export default class App extends React.Component {
  state = {
    hasCameraPermission: null,
    type: Camera.Constants.Type.front,
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png',
  };

  async componentWillMount() {
    StatusBar.setHidden(true);
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({ hasCameraPermission: status === 'granted' });
  }

  snap = () => {
    this.camera.takePictureAsync().then(image => {
      console.log('pic', image);
      this.setState({loading: false, image, counter: 3})
    }).catch(e => {
      console.log('error -> ', e)
    })
  }

  render() {
    const { hasCameraPermission, image } = this.state;
    if (hasCameraPermission === null) return (<View/>)
    if (hasCameraPermission === false) return (<View><Text>No access to camera</Text></View>)
      return(
        <View style={{flex: 1}}>
          <Camera style={{flex: 1}} type={this.state.type}
            ref={ref => {this.camera = ref}} ></Camera>
          <View style={{flex: 1, alignItems: 'center'}}>
            <TouchableOpacity onPress={this.snap}>
              <Text style={styles.text}>Snap</Text>
            </TouchableOpacity>
            <View style={{flex: 1}}>
              <Image
                  style={{width: 200, height: 200}}
                  source={{uri: image}}
              />
          </View>
          </View>
        </View>
      )
    }
}

const styles = StyleSheet.create({
  text: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center'
  }
});
```

```
# package.json

{
  "name": "mirror",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native-aws3": "^0.0.8",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz"
  }
}

```

```
#app.json
{
  "expo": {
    "name": "mirror",
    "description": "An empty new project",
    "slug": "mirror",
    "privacy": "public",
    "sdkVersion": "20.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app-icon.png",
    "loading": {
      "icon": "./assets/icons/loading-icon.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true
    }
  }
}
```

![21284303_1598549210184970_1444633582_o](https://user-images.githubusercontent.com/1475197/29961030-ab85bf4e-8f1b-11e7-91c8-cc69da034827.jpg)

My use case is to show a timer and then click a photo, in that case it's not even capturing the image, it is completely black. (Works perfectly in android) expo link: https://expo.io/@vysakh0/mirror. Related to question, what about the best way to take a pic, without showing the preview for the user. Not sure if it is the right way, currently using,

```js
          <Camera style={{flex: .001}} type={this.state.type} />
```

**Comment by aalices** [comment]
@vysakh0 the example works fine on my iPhone 6 and 5s. What device are you using? You're right as it comes to having no preview as on iOS we crop the image to match the preview and as long as it's about 1px size, the picture is that small and some weird scale image appears when you pass it as a source for `<Image>`.  However, I think there is a solution for that. Just create a component inside `Camera` and make it fill whole preview. As long as there is nothing fancy in the background this should work just fine. In the future there should be a boolean prop `cropToPreview`. Thanks for feedback!

**Comment by vysakh0** [comment]
@aalices Thank you so much @aalices for the reply! :+1:  Sorry, forgot to include the device that I tested. 
`iOS 11 beta`  in `iphone 6plus`, that is where the above code doesn't work. 

I haven't tested this snippet in other devices. Probably this is only specific to the beta version.

I had got the black image in all other devices like the `iPad`, thanks for the suggestion on creating a component! :+1:

**Comment by 3rfan** [comment]
I have experienced the same problem on `iOS 10.3.3` on an iPhone 6. No problems on Android. It seems like that on iOS the `Camera` component sometimes doesn't realize the `type` prop on the initial render. I have found that setting the `type` prop initially to `Camera.Constants.Type.back` and changing it with a small delay to `Camera.Constants.Type.front` works. I hope it helps you guys to fix this issue. 
Thx for your time and effort on expo :)

**Comment by aalices** [comment]
@3rfan @vysakh0 are you seeing this issue in SDK 21 ?

**Comment by 3rfan** [comment]
Yes, the issue still exists in sdk 21. Just initialize the camera with `type` set to `front`. It always displays the back camera first and then it changes to the front camera after a second, most of the times. But 1 out of 5 times it doesn't, except you call `setState` and set the `type` again. FYI: I am using `react-navigation`.

**Comment by aalices** [comment]
Thanks, you're right - it sometimes happens and sometimes not. We'll let you know when it gets fixed!

**Comment by 3rfan** [comment]
Nice, looking forward to it :)

**Comment by terribleben** [comment]
Fix is landed and will ship with next SDK.

**Comment by rebitte** [comment]
SDK 24, same problem.

**Comment by aalices** [comment]
@rebitte are you sure your app is using SDK 24? Can you provide a short clip/gif showing the issue?

**Comment by rebitte** [comment]
My mistake: I don't accepted the permission to show the camera.

Em 21 de dez de 2017 06:20, "Alicja Warchał" <notifications@github.com>
escreveu:
