### ISSUE TITLE
Detox e2e testing and app permissions

### ISSUE THREAD

**Issue by Antonhansel** [expo/expo#5790]
### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
```

App is running on iOS 12.4 on iPhone Xs Max

Relevant package versions:

```
    "detox": "12.3.0",
    "detox-expo-helpers": "^0.6.0",
    "expo": "^34.0.1",
    "expo-cli": "^3.0.10",
    "expo-detox-hook": "^1.0.10",
```

```
  "detox": {
    "configurations": {
      "ios.sim": {
        "binaryPath": "bin/Exponent.app",
        "type": "ios.simulator",
        "name": "iPhone Xs Max"
      }
    },
    "test-runner": "mocha",
    "specs": ""
  },
```

### Steps to Reproduce

I have been using detox as an e2e testing tool with success until now.
I'm using expo's `Permissions.askAsync(Permissions.CAMERA_ROLL);` which makes this window pop up:

![image](https://user-images.githubusercontent.com/4123811/65753440-534fab80-e10f-11e9-85b6-e4bd4445abfe.png)

My goal is to select and tap the `OK` button here.

For those familiar with detox, I have tried the following:
```
await element(by.type('_UIAlertControllerActionView').and(by.text('OK'))).tap();
```
```
 await element(by.type('_UIAlertControllerActionView').and(by.label('OK'))).tap();
```
```
await element(by.label('OK').and(by.type('_UIAlertControllerActionView'))).tap();
```
```
await element(by.text('OK').and(by.type('_UIAlertControllerActionView'))).tap();
```

With no success.

After more investigation and using the `View Hierarchy debugger` of xcode I realised that the `Alert` window isn't even seen by the debugger. 

![image](https://user-images.githubusercontent.com/4123811/65753606-a1fd4580-e10f-11e9-8669-ecd7564e19c3.png)

Is it running in another process ? Is there any way to properly test this ?
If there isn't, I read that it is possible to set permissions using `detox-expo-helpers` but the documentation and example lacks details about the `CAMERA_ROLL` permission

```
  await reloadApp({
    permissions: { location: 'inuse', notifications: 'YES' },
  });
```

I found the list of permissions

```
    calendar=YES|NO|unset
    camera=YES|NO|unset
    contacts=YES|NO|unset
    health=YES|NO|unset (iOS 12.0 and above)
    homekit=YES|NO|unset
    location=always|inuse|never|unset
    medialibrary=YES|NO|unset
    microphone=YES|NO|unset
    motion=YES|NO|unset
    notifications=YES|NO|unset
    photos=YES|NO|unset
    reminders=YES|NO|unset
    siri=YES|NO|unset
    speech=YES|NO|unset
    faceid=YES|NO|unset
```

But I am faced with the WEIRDEST issue when using them:

I have in my `init.ts` file:

```
before(async () => {
  await detox.init(config);
  await reloadApp({
    permissions: { medialibrary: 'YES' },
  });
});
```

The app launches on the device specified in package.json (iPhone Xs Max), the reloads, and then a random emulator opens 😅 iPad, iPhone, Apple TV, iPad pro, etc...

Should I pass more parameters to `reloadApp` ?

It seems that `expo-detox-helpers` is throwing the following error:
```
detox[23798] ERROR: [exec.js/EXEC_FAIL, #8] Unknown command line option --simulator, try --help!
```

it seems to ignore or fail to recognize the configuration set in package.json

**Comment by Antonhansel** [comment]
Feel free to ask any infos / code that can be useful for debugging @quinlanj :)

**Comment by EvanBacon** [comment]
AFAIK you cannot interact with the permission dialog directly.

**Comment by Antonhansel** [comment]
As this issue has been inactive for a while and I have moved on to other projects and away from Expo, I'm closing.
Feel free to re-open if you have additional infos.
