### ISSUE TITLE
Image orientation on Pocophone and Nokia 7.1 returns with 90 deg rotation

### ISSUE THREAD

**Issue by SerdarMustafa1** [expo/expo#5791]
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v12.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.4 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.1.2

The issue appears on android devices with multiple cameras, namely Pocophone and Nokia 7.1.

### Steps to Reproduce

Take a picture using either expo camera or image picker and when rendered to the screen as a preview, the image has been rotated 90deg clockwise. Exif data returns orientation as 0.

### Expected Behavior

The image should be portrait with no additional rotation applied. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/45297391/65763427-10e89780-e12c-11e9-9452-1ea895f55661.png)

### Reproducible Demo

  const takeImageHandler = async () => {
    const hasPermission = await verifyPermissions();
    if (!hasPermission) {
      return;
    }
    const image = await ImagePicker.launchCameraAsync({
      allowsEditing: false,
      aspect: [16, 9],
      quality: 0.8,
      base64: false,
      exif: true,
    });
    console.log(image);
    setPickedImage(image.uri);
    setState({ pictureURI: image.uri });
  };

**Comment by cruzach** [comment]
Could you try this on a fresh new `expo init` project? Your dependencies are off according to your `expo diagnostics` output. You're using SDK 33, but are pointing to the SDK 34 version of `react-native`  (https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz)

**Comment by SerdarMustafa1** [comment]
No joy on a new project either. On the existing one I have updated all of the dependencies but still, get the same error. 

On further investigation, it seems that the images are being rotated into landscape mode when taken in portrait. However, when the picture is taken in Landscape, it then remains as it should.

**Comment by cruzach** [comment]
> No joy on a new project either
So this worked well on a blank project, or did not work? If it didnt, list out all the steps you took and provide a [snack](https://snack.expo.io/) to repro, please
