### ISSUE TITLE
SDK35 com.apple.developer.user-fonts is valid only for apps build with SDK 13 or later.

### ISSUE THREAD

**Issue by czy0729** [expo/expo#5792]
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.1.3 => 3.1.15 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.1.2

### Steps to Reproduce

Appstore failed to submit audit.

ITMS-90807: Invalid entitlement - The com.apple.developer.user-fonts is valid only for apps build with SDK 13 or later.

This happened after the release of IOS version 13, the code is the same as before, before I used sdk33, I immediately upgraded to 35 after the problem, or the same problem.

I used a custom font of my own, and I couldn't find the relevant problems and solutions in search engines.

Another thing is that my phone ios 13.1 can run the ipa. Expo can do it, too.

**Comment by cruzach** [comment]
Hi! This was asked about [here on our forums](https://forums.expo.io/t/entitlement-error/27670/7)

Looks like the solution was to uncheck `Fonts` in your app ID config in the Apple Developer console, can you try that and let me know how things progress?

**Comment by czy0729** [comment]
Definitely, don't check font of developer center, SDK 35, rebuild once, no problem.
but the ipa which use sdk35 is huge, 17m -> 45m, it's a pity.

**Comment by sooperfly563** [comment]
I tried unchecking Fonts in the Developer center and I still get this issue :( is there anything else I am missing?

**Comment by msevestre** [comment]
It says rebuild once. Did you try that?

**Comment by czy0729** [comment]
> I tried unchecking Fonts in the Developer center and I still get this issue :( is there anything else I am missing?

I rebuild once in SDK35 and and then there was no more warning, maybe you forgot to  change "sdkVersion": "35.0.0" in app.json after update the sdk?
