### ISSUE TITLE
jest-expo/universal ignores setupFilesAfterEnv

### ISSUE THREAD

**Issue by d4rky-pl** [expo/expo#5793]
### Environment

```

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /var/folders/qt/10542x9d2wbg0x93mmh1xsw00000gn/T/yarn--1569593414658-0.2333632498886371/node
      Yarn: 1.17.3 - /var/folders/qt/10542x9d2wbg0x93mmh1xsw00000gn/T/yarn--1569593414658-0.2333632498886371/yarn
      npm: 5.6.0 - ~/.asdf/shims/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.1.2
```

jest: 24.9.0
jest-expo: 35.0.0

### Steps to Reproduce

Add `setupFilesAfterEnv` in package.json jest configuration with a code that should crash the specs so you can observe the behaviour

### Expected Behavior

The setup file should be loaded and the specs should not pass 

### Actual Behavior

The setup file is not loaded, specs pass

### Reproducible Demo

https://github.com/d4rky-pl/jest-expo-universal-bug

**Comment by SimenB** [comment]
This is due to how `projects` work in jest. Not sure how Expo would best deal with it... Merge all user config into the projects? Project vs global config is pretty confusing stuff (I've created https://github.com/facebook/jest/issues/7185, but there's no progress on it as of yet).

**Comment by d4rky-pl** [comment]
@SimenB is there a way to load polyfills and extend jest matchers with jest-expo other than manually importing them in every test file then?

**Comment by SimenB** [comment]
You can probably compose it yourself by importing the expo preset, but I haven't looked into it

**Comment by d4rky-pl** [comment]
Seems that for now I'll probably have to get back to using react-native-web and skip all the `universal` goodies since `debugger` statements also seem to no longer work for me and that's a no-go as far as I'm concerned 😅

Thanks for the help, I'll keep the notifications open here in case you ever sort these things out ❤

**Comment by ide** [comment]
I don't think this is something we will add support for because as stated above, this is how Jest works. We could add warnings that some options in the config are ignored, but none of this behavior is specific to Expo and that functionality would best belong in Jest.

I agree that composing it yourself into the preset is the way to go (ex: import the preset -> modify `preset.projects[n].setupFilesAfterEnv`).

**Comment by d4rky-pl** [comment]
You could implement it similar to create-react-app by defaulting the setup file path for every project to a file in the app itself while supporting having multiple setup files per different plaform (e.g. `setupTests.ios.js` / `setupTests.android.js`). At least that's how I'm planning to make it work in my composed preset :)
