### ISSUE TITLE
[bare] trouble installing bare APK

### ISSUE THREAD

**Issue by pedro3900** [expo/expo#5795]
### Environment
Android
### Steps to Reproduce
I eject my expo app with SDK 34 to a bare project (the app was working fine with expo start), but after that process I tried to build an Signed APK with Android Studio, the build works fine but when I tried to install the apk the mobile give me and error as "The app was not installed it seems that it is damaged.

I did it without android studio executing npm start and ./gradlew assembleRelease but the result is the same

I don't know if I miss an intermidiate step
### Expected Behavior

I expect that the signed app works fine.

### Actual Behavior

It is not working fine.

**Comment by cruzach** [comment]
This probably has to do with how you're building the project/your Android Studio settings/your device. I would try installing onto a blank sim to rule out device issues
