### ISSUE TITLE
App Store app size doubled sincde SDK35

### ISSUE THREAD

**Issue by Gorbus** [expo/expo#5796]
## 🐛 Bug Report

I upgraded to Sdk 35 from Sdk 33 and the app size on the App store doubled (from 40mb to 80mb) while the ipa file size is more or less the same ( around 195Mb). Is there any new configuration or optimization in order to avoid this ?

### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.1.2

iOs (on Android App size is 17Mb on store using the app-bundle option)

### Steps to Reproduce

expo build:ios and then using the app uploader

### Expected Behavior

Keep a similar app size on the App Store

### Actual Behavior

 App size doubled

**Comment by Gorbus** [comment]
Actually seems from the itunesconnect that the Universel version is 88Mb but the other version are only 54Mb but on the shop it shows 88Mb. What is the real value ? Why is 88Mb shown if it takes less on the user's phone ? Or will the user see a different value according to its phone ? (My client said he saw 88Mb though he has a iPhone 6 for which it is supposed to be 54Mb) He used to see aroudn 40Mb in the shpo for the preivous versions.

![image](https://user-images.githubusercontent.com/12472982/65811890-c44e9c00-e1bf-11e9-99d5-afafc2525059.png)

**Comment by OscarYuen** [comment]
> Actually seems from the itunesconnect that the Universel version is 88Mb but the other version are only 54Mb but on the shop it shows 88Mb. What is the real value ? Why is 88Mb shown if it takes less on the user's phone ? Or will the user see a different value according to its phone ? (My client said he saw 88Mb though he has a iPhone 6 for which it is supposed to be 54Mb) He used to see aroudn 40Mb in the shpo for the preivous versions using Sdk 33.
> 
> ![image](https://user-images.githubusercontent.com/12472982/65811890-c44e9c00-e1bf-11e9-99d5-afafc2525059.png)

User would see the value on the right(Install size).
After sdk 33, you need to exclude the face-detector or other unused components to make the ipa/apk smaller

**Comment by wkozyra95** [comment]
Hi
Most likely `face-detector ` is responsible for most of this size increase, currently, we are using partially prebuild project with all the modules enabled, the process of building on our servers is mostly configuring, packaging and signing. Including a custom set of modules would require separate compilation per build, we plan to work on a way to build an app from precompiled packages, but it will take some time.

**Comment by cmacdonnacha** [comment]
How can I disable the `face-detector`?
