### ISSUE TITLE
"errorCode": 1203, "errorMessage": "The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK",Facebook ads does not appears on app

### ISSUE THREAD

**Issue by knightkhan** [expo/expo#5797]
error SyntheticEvent {
"_dispatchInstances": FiberNode {
"tag": 5,
"key": null,
"type": "ViewManagerAdapter_CTKBannerView",
},
"_dispatchListeners": [Function onError],
"_targetInst": FiberNode {
"tag": 5,
"key": null,
"type": "ViewManagerAdapter_CTKBannerView",
},
"bubbles": undefined,
"cancelable": undefined,
"currentTarget": 219,
"defaultPrevented": undefined,
"dispatchConfig": Object {
"registrationName": "onAdError",
},
"eventPhase": undefined,
"isDefaultPrevented": [Function functionThatReturnsFalse],
"isPropagationStopped": [Function functionThatReturnsFalse],
"isTrusted": undefined,
"nativeEvent": Object {
"errorCode": 1203,
"errorMessage": "The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK",
},
"target": undefined,
"timeStamp": 1569895959235,
"type": undefined,
}

Expo 35.0.0
expo facebook ads : 7.0.0

**Comment by knightkhan** [comment]
`import { AppLoading } from 'expo';
import { Asset } from 'expo-asset';
import * as Font from 'expo-font';
import React, { useState } from 'react';
import { Platform, StatusBar, StyleSheet, View, Text, config } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as FacebookAds from 'expo-ads-facebook';


import AppNavigator from './navigation/AppNavigator';

export default function App(props) {
  const [isLoadingComplete, setLoadingComplete] = useState(false);

  if (!isLoadingComplete && !props.skipLoadingScreen) {
    return (
      <AppLoading
        startAsync={loadResourcesAsync}
        onError={handleLoadingError}
        onFinish={() => handleFinishLoading(setLoadingComplete)}
      />
    );
  } else {
    
    return (
      <View style={styles.container}>
        {Platform.OS === 'ios' && <StatusBar barStyle="default" />}
      
      
        <View  style={styles.containertwo}>
      <AppNavigator />
      </View>
      <View  style={styles.containerone}>
      <FacebookAds.BannerAd
        placementId="420331372172311_420332352172213"
        type="standard"
        onPress={() => console.log('click')}
        onError={error => console.log('error', error)}
      />
     </View>
      </View>
    );
  }
}

async function loadResourcesAsync() {
  await Promise.all([
    Asset.loadAsync([
      require('./assets/images/robot-dev.png'),
      require('./assets/images/robot-prod.png'),
    ]),
    Font.loadAsync({
      // This is the font that we are using for our tab bar
      ...Ionicons.font,
      // We include SpaceMono because we use it in HomeScreen.js. Feel free to
      // remove this if you are not using it in your app
      'space-mono': require('./assets/fonts/SpaceMono-Regular.ttf'),
    }),
  ]);
}

function handleLoadingError(error) {
  // In this case, you might want to report the error to your error reporting
  // service, for example Sentry
  console.warn(error);
}

function handleFinishLoading(setLoadingComplete) {
  setLoadingComplete(true);
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    flexDirection: 'column'
  },
  containerone: {
    flex: 0.11,
    backgroundColor: '#fff',
    alignSelf: 'stretch'
  },
  containertwo: {
    flex: 1,
    backgroundColor: '#fff',
  },
  bottomBanner: {
    position: "absolute",
    top: 0
  },
});


`

**Comment by cruzach** [comment]
Please fill out the entire issue template when submitting a bug report

Also, make sure to provide any error messages you may be getting

**Comment by knightkhan** [comment]
error SyntheticEvent {
“_dispatchInstances”: FiberNode {
“tag”: 5,
“key”: null,
“type”: “ViewManagerAdapter_CTKBannerView”,
},
“_dispatchListeners”: [Function onError],
“_targetInst”: FiberNode {
“tag”: 5,
“key”: null,
“type”: “ViewManagerAdapter_CTKBannerView”,
},
“bubbles”: undefined,
“cancelable”: undefined,
“currentTarget”: 219,
“defaultPrevented”: undefined,
“dispatchConfig”: Object {
“registrationName”: “onAdError”,
},
“eventPhase”: undefined,
“isDefaultPrevented”: [Function functionThatReturnsFalse],
“isPropagationStopped”: [Function functionThatReturnsFalse],
“isTrusted”: undefined,
“nativeEvent”: Object {
“errorCode”: 1002,
“errorMessage”: “Ad was re-loaded too frequently”,
},
“target”: undefined,
“timeStamp”: 1569859582688,
“type”: undefined,
}
Running application on HTC Desire 630 dual sim.
error SyntheticEvent {
“_dispatchInstances”: FiberNode {
“tag”: 5,
“key”: null,
“type”: “ViewManagerAdapter_CTKBannerView”,
},
“_dispatchListeners”: [Function onError],
“_targetInst”: FiberNode {
“tag”: 5,
“key”: null,
“type”: “ViewManagerAdapter_CTKBannerView”,
},
“bubbles”: undefined,
“cancelable”: undefined,
“currentTarget”: 219,
“defaultPrevented”: undefined,
“dispatchConfig”: Object {
“registrationName”: “onAdError”,
},
“eventPhase”: undefined,
“isDefaultPrevented”: [Function functionThatReturnsFalse],
“isPropagationStopped”: [Function functionThatReturnsFalse],
“isTrusted”: undefined,
“nativeEvent”: Object {
“errorCode”: 1002,
“errorMessage”: “Ad was re-loaded too frequently”,
},
“target”: undefined,
“type”: undefined,
}

**Comment by knightkhan** [comment]
error SyntheticEvent {
  "_dispatchInstances": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "_dispatchListeners": [Function onError],
  "_targetInst": FiberNode {
    "tag": 5,
    "key": null,
    "type": "ViewManagerAdapter_CTKBannerView",
  },
  "bubbles": undefined,
  "cancelable": undefined,
  "currentTarget": 219,
  "defaultPrevented": undefined,
  "dispatchConfig": Object {
    "registrationName": "onAdError",
  },
  "eventPhase": undefined,
  "isDefaultPrevented": [Function functionThatReturnsFalse],
  "isPropagationStopped": [Function functionThatReturnsFalse],
  "isTrusted": undefined,
  "nativeEvent": Object {
    "errorCode": 1203,
    "errorMessage": "The SDK version in the ad request is no longer supported for new apps. Please upgrade to one of the latest versions of the SDK",
  },
  "target": undefined,
  "timeStamp": 1569895959235,
  "type": undefined,
}

**Comment by knightkhan** [comment]
i am using 7.0.0 expo facebook ads 
and exxpo skd 35

**Comment by cruzach** [comment]
[here is the bug report template](https://github.com/expo/expo/edit/master/.github/ISSUE_TEMPLATE/bug_report.md). Edit your original post with that format, and then we can try to help 👍

**Comment by AdamJNavarro** [comment]
Hey @knightkhan,

We spoke on the forums about using the Bare workflow that allows you to upgrade the FB ads SDK version so I'm going to close this issue.

Cheers,
Adam
