### ISSUE TITLE
Add home screen icon for specific Exponent apps

### ISSUE THREAD

**Issue by lyahdav** [expo/expo#58]
Similar to how [Workflow](https://itunes.apple.com/us/app/workflow-powerful-automation/id915249334?mt=8) does it, it should be possible to have the Exponent client walk a user through the steps to create a home screen icon for specific apps. This would leverage a deep link into the Exponent app, which is a feature that already exists.

**Comment by dikaiosune** [comment]
I believe this works on Android today, but I've created a [feature request on Canny](https://expo.canny.io/feature-requests/p/home-screen-icon-for-individual-experiences) for us to cover this on iOS. Thanks!
