### ISSUE TITLE
Packager keeps hot-reloading without any changes in code

### ISSUE THREAD

**Issue by DLesage25** [expo/expo#5800]
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.12.0 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.1.2

App's Target: iOS

### Steps to Reproduce

When running `npm start`, on both an emulator and real device, the bundler finishes and I see the application for a few seconds, until the packager starts to rebundle again. This continues happening without me editing any code. 

### Expected Behavior

Reload upon changes.

### Actual Behavior

Packager reloads without there being any code changes

**Comment by cruzach** [comment]
This could be caused by storing your project in a Dropbox/iCloud backed-up directory, could you try moving files out of those directories and seeing if that fixes it?

**Comment by ide** [comment]
Might help to debug further (`lsof +D` or some equivalent on your OS) to see what is accessing the files.

**Comment by DLesage25** [comment]
Project indeed was in my iCloud backed-up directory. Thanks guys!
