### ISSUE TITLE
[Docs] docs don't state iOS sim doesn't support audio input

### ISSUE THREAD

**Issue by pavlov-sergey-alexandr** [expo/expo#5801]
## 🐛 Bug Report
I get error "Prepare encountered an error: recorder not prepared." when i run my app on simulator IOS.

`Prepare encountered an error: recorder not prepared.
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:415:4 in __invokeCallback
- ... 4 more stack frames from framework internals`

### Environment
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.7 => 4.0.8 
    npmGlobalPackages:
      expo-cli: 3.0.10

Error for on IOS simulator.

### Steps to Reproduce

I run the following function:

```
`export const startRecord = async (handleSetRecording, handleErr) => {
       await Audio.setIsEnabledAsync(true);
       await Audio.setAudioModeAsync({
       allowsRecordingIOS: true,
       interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
       playsInSilentModeIOS: true,
       shouldDuckAndroid: true,
       interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
       playThroughEarpieceAndroid: false,
       staysActiveInBackground: true
   });

  const recordingSettings = Audio.RECORDING_OPTIONS_PRESET_LOW_QUALITY

  const recording = new Audio.Recording();
  try {
       await recording.prepareToRecordAsync(recordingSettings); <----This line of error
       handleSetRecording(recording);
       await recording.startAsync();
  } catch (error) {
       console.log(error);
       handleErr(error);
  }
};`
```

After executing  function
`                  await recording.prepareToRecordAsync (recordingSettings)`
error occurs

### Expected Behavior

 Expected there would be no error and audio recording would start

### Actual Behavior

Sample error in the project from this repository https://github.com/expo/audio-recording-example
When I click the “audio recording” button - an error is issued, as in the picture below

![image](https://user-images.githubusercontent.com/53443993/65828968-5d0d1680-e2a9-11e9-8cd5-46583ad88001.png)

### Reproducible Demo

I tested the project https://github.com/expo/audio-recording-example.
i got this error

  Thanks you!

**Comment by cruzach** [comment]
What iOS version are you running? I tried that example repo app on my phone (iOS 12) and it worked without that warning

**Comment by pavlov-sergey-alexandr** [comment]
This is not a warning. This is error.

I run the project from this repository (https://github.com/expo/audio-recording-example.) in Xcode simulator. Maybe for iOS necessary to test on a physical device. 
But on the simulator android studio everything works fine.

**Comment by cruzach** [comment]
Ah, wasn't aware this was only occurring on simulator for you. The iOS simulator does not support audio input, as stated in [Apple's docs](https://help.apple.com/simulator/mac/current/#/devb0244142d). I'll make a change to our docs to make this clearer, thanks for bringing it up!

**Comment by pavlov-sergey-alexandr** [comment]
Thank you!!!
