### ISSUE TITLE
When Try connect

### ISSUE THREAD

**Issue by openmaya** [expo/expo#5803]
### Environment

Tried to use     "expo-in-app-purchases": "^7.0.0",

OS : Android 
"sdkVersion": "34.0.0",
app.json's android  permission 👍 

      "permissions": [
        "INTERNET",
        "SYSTEM_ALERT_WINDOW",
        "com.android.vending.BILLING"
      ]

### Steps to Reproduce
My Code
>     try {
      this.screenLog(`connectAsync`);
      const history = await InAppPurchases.connectAsync();
      this.screenLog(`history=${history}`);
      if (history.responseCode === InAppPurchases.IAPResponseCode.OK) {
        history.results.forEach(result => {
      this.screenLog(result.productId);
        });
      } else {
        this.screenLog(`history=${history.errorCode},${history.responseCode}`);
      }
    } catch (err) {
      this.screenLog(`EXPO error:${err.message}`);
 }

### Expected Behavior
get message with subscription Product Id on screen

### Actual Behavior
got message "EXPO error:undefined is not an object(evaluating y.default.connectAsync')

### Reproducible Demo
Because this is first step to get subscription products, I had simular errors above whenever use any apis

**Comment by tsapeta** [comment]
How do you import `InAppPurchases`? Looks like it might be something wrong with the way how you import it 🙂

**Comment by openmaya** [comment]
import * as InAppPurchases from 'expo-in-app-purchases';
import { IAPItemDetails } from 'expo-in-app-purchases/build/InAppPurchases.types';

**Comment by cruzach** [comment]
The [InAppPurchases module](https://docs.expo.io/versions/latest/sdk/in-app-purchases/) is only available in the bare workflow. Is this a [managed or bare](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/) project?

**Comment by openmaya** [comment]
My project may be managed by expo. I'm building app bundle by expo-cli like "expo build:android -t app-bundle". Do I need to eject my project? Because I experienced lots of problems and fails when I registered my app to Play Store with react-native cli, I'm afraid of using it.

**Comment by cruzach** [comment]
You can get your keystore by running `expo fetch:android:keystore` from the root directory of your project

closing since InAppPurchases is only available in the bare workflow, which explains this error message

**Comment by openmaya** [comment]
After link this module, I cannot build my project

(Duplicate jar entry [android/support/v4/app/v$a$a.class]))
Thread(Tasks limiter_1): destruction

Something is duplicated.

**Comment by openmaya** [comment]
@cruzach Thanks
I need to figure out next step :)
