### ISSUE TITLE
ImagePicker launchImageLibraryAsync Crashes on Android

### ISSUE THREAD

**Issue by jjg77** [expo/expo#5804]
"expo-image-picker": "~6.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
expo client: 2.13.0

Sometime is opens, but then hangs and crashes.  Other times it won't open when you click the button. 

https://snack.expo.io/@charliecruzan/imagepickerfromcameraroll

**Comment by lukmccall** [comment]
Hi @jjg77, which version of Android do you use?

**Comment by jjg77** [comment]
Version 9.

**Comment by lukmccall** [comment]
I've tried to reproduce your bug on S8 with Android 9. Unfortunately, I've failed.
Could you provide more information? 
For example, is it happen only on physical devices or maybe can you reproduce this behaviour in the simulator?

**Comment by wodin** [comment]
Works for me on Appetize (in the snack) an on physical Galaxy S8 running Android 9.
@jjg77 does it work for you using SDK 36?

**Comment by psyycker** [comment]
I have the same issue. Using a oneplus 7 pro running android 10. The camera launches, I take a picture and then confirm and the application restarts directly.

```
ImagePicker.launchCameraAsync()
      .then(response => {

      })
```
That's all I've got. Using expo sdk 6 (https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz)
And the last version of expo and expo-image-picker

**Comment by wodin** [comment]
@psyycker do you get an error message in the `adb logcat` output?

**Comment by psyycker** [comment]
![Screenshot 2020-02-05 at 10 13 16](https://user-images.githubusercontent.com/9397742/73832482-279caa80-4800-11ea-9db1-f55fd11862b9.png)
Yes!

**Comment by lukmccall** [comment]
Thank you 🎉 I'll check it soon.

**Comment by psyycker** [comment]
Great! If you need any testing from my side please let me know! I'm keen to
help!

**Comment by lukmccall** [comment]
@psyycker, I think your case is more connected with this [issue](https://github.com/expo/expo/issues/2925).

**Comment by psyycker** [comment]
It might indeed. Anything I can do to help ?

**Comment by lukmccall** [comment]
Does it happen in the expo client?

**Comment by psyycker** [comment]
It happens with a production apk or with the expo debug. I couldn't have any case where it doesn't happen

**Comment by lukmccall** [comment]
@psyycker, I've tried to do something with it. Sadly, I can't reproduce it. Moreover, the logs which you provide gave me some idea about what could have gone wrong. However, I can't check it :/

Could you help me with debugging it?
How? It's simple :) 
- create a bare workflow project (`expo init`)
- add expo-image-picker (`expo install expo-image-picker` and https://github.com/expo/expo/tree/master/packages/expo-image-picker#configure-for-android)
- add js code which causing crashes
- set breakpoints using android studio
  - a good place to start an investigation is this function: https://github.com/expo/expo/blob/a9705b7667b13bce0f9de5c2d0e10a8688cc7777/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java#L308
    - I'm not sure if the permissions are granted to other packages correctly (`for loop`)
  - the next interesting function is: 
https://github.com/expo/expo/blob/a9705b7667b13bce0f9de5c2d0e10a8688cc7777/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java#L373
    - I think, in your case, this function isn't called at all. However, it's worth to check it.

**Comment by psyycker** [comment]
@lukmccall I'm gonna try that in the evening (I'm living in England, just for precision) and give you some more info!

**Comment by psyycker** [comment]
@lukmccall I'm sorry, I'm not familiar with debugging expo. How can I connect my android studio debugger directly to my phone running expo ? Would you have a sample project I can run ?

**Comment by lukmccall** [comment]
@psyycker, I've created for you a simple project. Please, check out this [repo](https://github.com/lukmccall/ImagePickerCrashes). 

How to start with this?
- clone this repository
- run `yarn` / `npm install`  in the main directory of this project
- open the `android subfolder` in Android Studio
- run `react-native start` (in the main directory)
- using Android Studio build your app with a debugger  (https://developer.android.com/studio/debug#startdebug)

If you don't see `expo-image-picker` in the `Project` tab, you should sync your project with Gradle. To do it click here:
![Screenshot 2020-02-12 at 10 13 19](https://user-images.githubusercontent.com/9578601/74320120-60003380-4d80-11ea-949c-34af2c2dda23.png)

If you have any question, feel free to ask. 

Thank you for helping me 🥇

**Comment by psyycker** [comment]
Thank you so much ! I'll give it a go

**Comment by psyycker** [comment]
Okay so, what I understand is that when the camera starts, I think the app crashed already. We are going through the full first function you talked about but definitely not in the second one. Also when the camera starts, the debugger is disconnected from my phone.

**Comment by lukmccall** [comment]
I have two more questions. Have you set `don't keep activity` in developer options? Could you provide me with more logs from your device? I want to see what had happened before the `FileNotFoundException` was thrown.

**Comment by psyycker** [comment]
No, I didn't.
Yes I can provide you more logs tonight!

**Comment by psyycker** [comment]
<img width="1629" alt="Screenshot 2020-02-13 at 9 58 00 pm" src="https://user-images.githubusercontent.com/9397742/74482218-04cb5f80-4eac-11ea-8b21-79c73fc495f4.png">
<img width="1576" alt="Screenshot 2020-02-13 at 9 55 53 pm" src="https://user-images.githubusercontent.com/9397742/74482231-09901380-4eac-11ea-956c-38a5fcfd7054.png">
<img width="1635" alt="Screenshot 2020-02-13 at 9 55 28 pm" src="https://user-images.githubusercontent.com/9397742/74482234-0ac14080-4eac-11ea-8913-014f1a6f3142.png">
There is nothing much unfortunately. That's all I could find. Logs are going very fast, I tried to get a maximum

**Comment by wodin** [comment]
Hi

In order to get the whole log you could try:

```
adb logcat -d -f log.txt
```

Here's a list of the options:

https://developer.android.com/studio/command-line/logcat

**Comment by lukmccall** [comment]
@psyycker, Unfortunately, logs, which you provided, weren't very helpful. So, I'll be pleased if you provide me with whole logs. 

Thanks in advance.

**Comment by psyycker** [comment]
Hi, very sorry for the reply time, here is the logs. I started the manipulations at exactly 8:41. Reload the app first, then press take a picture, take the picture and the app restarts.

[log.txt](https://github.com/expo/expo/files/4232906/log.txt)

**Comment by wodin** [comment]
That's a lot to wade through! And I'm not really sure what's relevant or what everything means. But could this be a race condition?

```
02-20 20:41:03.194  1526  2279 D OemSceneCallBlock: isCallBlockedWithUidIntent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.oneplus.camera/.OPCameraServiceActivity clip={text/uri-list U:content://com.imagepickercrash.ImagePickerFileProvider/cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg} (has extras) }, ResolveInfo{a9f99d com.oneplus.camera/.OPCameraServiceActivity m=0x108000}, false
[...]
02-20 20:41:03.196  1526  2279 I ActivityTaskManager: START u0 {act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.oneplus.camera/.OPCameraServiceActivity clip={text/uri-list U:content://com.imagepickercrash.ImagePickerFileProvider/cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg} (has extras)} from uid 10538 pid 17010
[...]
02-20 20:41:03.242 17517 17517 V OPCameraServiceActivity: checkStartMode() - Start mode: SERVICE_PHOTO, Media extras: com.oneplus.camera.MediaResultInfo@f96e178 - [ extraDurationLimit: 0, extraOutput: content://com.imagepickercrash.ImagePickerFileProvider/cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg, extraSizeLimit: 0, extraVideoQuality: 0 ], Launch source: NORMAL
[...]
02-20 20:41:06.090 17517 19676 D CameraImpl: [Property] CaptureState(id=238) : STARTING -> STARTED
02-20 20:41:06.090 17517 19676 D CameraThread: [Property] PhotoCaptureState(id=97) : STARTING -> CAPTURING
02-20 20:41:06.091 17517 17517 V OPCameraServiceActivity: onPhotoCaptureStarted() - Handle : Capture [102172608]
[...]
02-20 20:41:06.928 17517 19755 D FileManagerThread: MESSAGE_SAVE_MEDIA  1
02-20 20:41:06.928 17517 19755 V RequestedPhotoSaveTask: saveMediaToFile() - File path : /cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg
02-20 20:41:06.928 17517 19755 V RequestedPhotoSaveTask: saveMediaToFile() - Save to file [start]
02-20 20:41:06.928 17517 17517 D OPCameraServiceActivity: [Property] PhotoCaptureState(id=70) : CAPTURING -> STOPPING
02-20 20:41:06.929 17517 17517 D OPCameraServiceActivity: [Property] PhotoCaptureState(id=70) : STOPPING -> REVIEWING
[...]
02-20 20:41:06.966 17517 19755 V RequestedPhotoSaveTask: onPrepareMediaStoreValues() - Taken time: 1582231266084
02-20 20:41:06.967 17517 19755 E ImageUtils: decodeOrientation() - Fail to access file /cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg
02-20 20:41:06.967 17517 19755 E ImageUtils: java.io.FileNotFoundException: /cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg: open failed: ENOENT (No such file or directory)
[...]
02-20 20:41:06.967 17517 19755 V RequestedPhotoSaveTask: insertToMediaStore() - Content URI : content://com.imagepickercrash.ImagePickerFileProvider/cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg
[...]
02-20 20:41:07.009 17517 17517 W OPCameraServiceActivity: onMediaFileSaved() - capture is not completed yet, kept metadata for later use.
[...]
02-20 20:41:07.671 17517 17517 V OPCameraServiceActivity: setMediaResult() - OK, Uri: content://com.imagepickercrash.ImagePickerFileProvider/cached_expo_files/ImagePicker/2379b1d3-c62e-45a4-a5f8-66c0cd04fd71.jpg
```

i.e. it seems to be saying that the file is not saved (or finished saving?) until after the `FileNotFoundException` has already been thrown.

**Comment by lukmccall** [comment]
@psyycker, one more time thanks to you for help.

I've looked into your logs. I apply one fix. However, I'm not sure if it's help. 
Could you test [this repo](https://github.com/lukmccall/ImagePickerCrashes) one more time?

If it didn't help, please provide logs. Cause this app will logs more information right now.

**Comment by lukmccall** [comment]
And one more thing.
You don't get a screen like this:
![image](https://user-images.githubusercontent.com/9578601/75049342-538b8180-54ca-11ea-8487-d51dafc6dffb.png)
It's just reloading?

**Comment by psyycker** [comment]
@lukmccall it's my pleasure to help you!
I will try to run these tests during the weekend.
For the screen, no I do not get it, it's reloading every time without giving me any crash

**Comment by psyycker** [comment]
@lukmccall I tried your fix and it's now working! I have the render of the image appearing after taking the picture!
