### ISSUE TITLE
Next Android Release?

### ISSUE THREAD

**Issue by kitingChris** [expo/expo#5805]
We are in severe need for this fix https://github.com/expo/expo/pull/5311
Since it was merged in August there has been yet no Android release. When is the next release expected?

**Comment by tsapeta** [comment]
It should be fixed in the newest version that was released in September 19 😛

**Comment by AdamJNavarro** [comment]
Hey @kitingChris,

As Tomasz alluded to, this fix was included in SDK35 which was released already. https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4

If you still encounter an issue, please open a new issue with as much relevant information as you can provide.

Cheers,
Adam

**Comment by kitingChris** [comment]
Quite confusing. It is not listed in releases https://github.com/expo/expo/releases
