### ISSUE TITLE
Pausing Video using shouldPlay lags on Android

### ISSUE THREAD

**Issue by riwu** [expo/expo#5807]
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: Using globally installed version of Yarn
1.12.1 - /opt/facebook/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.4 - /opt/facebook/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A419c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8

Android

### Steps to Reproduce
Add a `<Video />` component with `onPlaybackStatusUpdate` updating  a state at default intervals.

### Expected Behavior
Video plays smoothly.

### Actual Behavior
Video is extremely laggy.

**Comment by cruzach** [comment]
Can you add the state updates to [a snack like this](https://snack.expo.io/@charliecruzan/videoexample) to replicate the bug?

**Comment by riwu** [comment]
@cruzach here's a repro snack: https://snack.expo.io/@riwu/video-lag
On iOS, everything works as expected:
![](https://i.imgur.com/mHRLT77.gif)

On Android, the video frequently hangs half way, and the status update interval is clearly not at the default value of 500ms -- might be the root cause:
![](https://i.imgur.com/xQ2ijGm.gif)

**Comment by cruzach** [comment]
What SDK are you using? the snack you linked was made in an old SDK
I updated your snack to sdk 35 [here](https://snack.expo.io/@charliecruzan/eager-raspberries), and I'm not seeing any video lag on android or ios

(This is a side note, but in my experience it's better to play/pause via `videoRef.playAsync()` and `videoRef.pauseAsync()`)

**Comment by riwu** [comment]
@cruzach it seems like the issue only occurs when video is initially paused (`shouldPlay={false}` on load).

See https://snack.expo.io/@riwu/eager-raspberries

**Comment by cruzach** [comment]
Ah okay, thanks for sharing that snack, I was able to see the behavior you're referring to.

As for a fix- I changed the `onPress` prop of your `Button` component to:
```js
onPress={() => {
  this.videoRef.playAsync()
}}
```
after adding a reference to the video component with:
```js
<Video
  ref={(video) => this.videoRef = video}
  ...the rest of your video props
/>
```
and there's no lag, and the status update interval is 500ms 

Let me know how that works for you

**Comment by riwu** [comment]
The workaround fixed the issue, thanks! 

Is there any strong reason why `videoRef.playAsync()` is preferred over using the `shouldPlay` prop? I assume using `shouldPlay` is slightly slower because it'll only pause the video when the `Video` component re-renders with the updated prop?

If using `shouldPlay` is not optimal, it should be deprecated...

**Comment by cruzach** [comment]
You can use `shouldPlay`, but like this:
```js
playbackObject.setStatusAsync({ shouldPlay: true });
```
the docs could probably be more clearer on this (if you'd like to submit a PR, that'd be awesome. if not, I can get around to it)
