### ISSUE TITLE
Support for using native firebase

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [expo/expo#581]
Is it possible to import the native firebase into an application that uses the expo?

**Comment by ccheever** [comment]
You can eject/detach and do this. You can use some parts of Firebase with just JavaScript. Here is a guide: https://docs.expo.io/versions/latest/guides/using-firebase.html

**Comment by mrded** [comment]
@ccheever Firebase Web SDK is very limited. And [React Native Firebase](https://rnfirebase.io/) requires Expo Ejecting, which is not a solution.

It would be nice to see a native Firebase integration, as it's already [integraed with Facebook](https://docs.expo.io/versions/latest/sdk/facebook).

Can I ask to reopen the feature request?

**Comment by anp** [comment]
Hi! We are tracking a couple of firebase feature requests over on Canny, which we use for feature requests now:

https://expo.canny.io/feature-requests/p/full-native-firebase-integration

https://expo.canny.io/feature-requests/p/adding-react-native-firebase-to-expo
