### ISSUE TITLE
Inconsistent return fields on Android Subscriptions

### ISSUE THREAD

**Issue by Speedy1991** [expo/expo#5818]
### Environment (unrelated I guess)
  Expo CLI 2.20.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
react-native: 0.61.1
expo-in-app-purchases: ^7.0.0
react-native-unimodules: ^0.7.0-rc.1

Android

### Steps to Reproduce

- Set up InAppPurchases in a bare App
- `connectAsync()`

### Expected Behavior
`getPurchaseHistoryAsync` should return the same fields as `getPurchaseHistoryAsync(true)` and `connectAsync()`

Looking into the Typescript definition, these fields should be set

### Actual Behavior

`getPurchaseHistoryAsync(true)` doesn't return the same fields as  `getPurchaseHistoryAsync()` nor `getPurchaseHistoryAsync()`

Missing fields (e.g. `orderId`)

Calling `getPurchaseHistoryAsync()` will return the expected fields.

The missing fields on `getPurchaseHistoryAsync(true)` is due to the fact, that [here](https://github.com/expo/expo/blob/master/packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java#L436) the fields are not added to the bundle

I _think_ the missing information is in [getOriginalJson](https://developer.android.com/reference/com/android/billingclient/api/PurchaseHistoryRecord) and must be parsed into the bundle too

But I am not sure

**Comment by Speedy1991** [comment]
Well, getOriginalJson returns only the subset too.

The best "fix" would be to correct the Typescript + the Docs

**Comment by cruzach** [comment]
We state in the docs: 

> An important caveat is that the return type when refresh is true is actually a subset of when it's false. This is because Android returns a PurchaseHistoryRecord which only contains the purchase time, purchase token, and product ID, rather than all of the attributes found in the InAppPurchase type.

But when that's `true`, the iOS return type remains the same, so I'm not sure if this is an issue TS can address 🤔
