### ISSUE TITLE
October Bug Hunt

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#5819]
## FileSystem (11 issues)

@dsokal @bbarthec @mczernek 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3AFileSystem

## ImagePicker (21 issues)

@lukmccall @WoLewicki 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3AImagePicker

## Permissions (16 issues)

@lukmccall  @sjchmiela 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3APermissions

## WebBrowser (10 issues)

@mczernek  @sjchmiela 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3AWebBrowser

## TaskManager (8 issues)

@Szymon20000 @tsapeta 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3ATaskManager

## BackgroundFetch (1 issue)

@Szymon20000 @tsapeta 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3ABackgroundFetch

## GLView (9 issues)

@tsapeta @wkozyra95 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3AGLView

## MediaLibrary

@tsapeta, @lukmccall 

https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3AMediaLibrary

**Comment by amaurymartiny** [comment]
I don't see it in BackgroundFetch, but I would add https://github.com/expo/expo/issues/3582 in that category.
