### ISSUE TITLE
expo/ expo xde / simulator running very slow. 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#582]
how can i/ we debug this ?

![image](https://user-images.githubusercontent.com/1026325/29978360-e5e0b0a2-8f0e-11e7-9ffa-0ce7ed1e3993.png)

**Comment by terribleben** [comment]
We'll probably need more information about what you mean by "running very slow", do you mean network requests are slow? App reloads are taking longer than expected? The screen is not responsive to gestures? You aren't seeing logs which you expect to see?

**Comment by jpca999** [comment]
App reloads are taking longer than expected?

**Comment by ccheever** [comment]
Hmmm.... how much longer than they were before? Are you clearing cache or otherwise triggering some kind of full rebuild of the JS bundle? Are things also slow when loading on a device? Or is it specific to the simulator? Have you restarted your computer lately?

**Comment by mattSydney** [comment]
Hi maybe I have the settings wrong but when I make any change to the source code even say adding a // comment and hitting save the ios simulator says "downloading javascript bundle" with a spinning indicator and takes at least 5-10 seconds to refresh the simulator

**Comment by jpca999** [comment]
Resolved.

**Comment by bramses** [comment]
What was the resolution to this? I'm experiencing the same issue

**Comment by jpca999** [comment]
1 check if the animations should be off. 
2.  i moved on to the next sdk version.
