### ISSUE TITLE
Doc: missing info about uploading the apn push notification key

### ISSUE THREAD

**Issue by borgogelli** [expo/expo#5823]
At the following page, https://docs.expo.io/versions/latest/guides/adhoc-builds/#uploading-an-existing-push-key,  I read:

`If you have your push key on file, you can provide the path to your .p8 file for upload.`

but there is no hint about how to do it

**Comment by cruzach** [comment]
Not sure I understand what you mean by hint. 

Once you select that option, all you do is provide the path (let's say it's in your current working directory, you'd just input `./myappname_apns_key.p8`). Do you think an example like that would be helpful there, or do you mean there should be more info on getting the .p8 file in the first place?

**Comment by borgogelli** [comment]
I have done some test and now I have understood. We usually use turtle-cli to build the app and the first time we have used the "_expo build:ios_" command (a year ago) there wasn't the possibility to upload any .p8 key but only the legacy push certificate.  Today the push notification certificates Apple architecture is changed. (see https://docs.expo.io/versions/latest/distribution/security).
So to upload the new .p8 key certificate, we have to run: 
`expo build:ios --clear-credentials`
and answer to the questions on the screen.
Thank you

**Comment by cruzach** [comment]
Oh okay, the docs you linked are for building the custom Expo Client, not for building standalone apps, I think that's why I was confused. 

I think the docs you are looking for [are here](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#switch-to-push-notification-key-on-ios)
