### ISSUE TITLE
expo-av: recording crashes app when app goes to background (iOS 13+)

### ISSUE THREAD

**Issue by dbruc3** [expo/expo#5824]
### Environment

bare react-native application
- "react-native-unimodules": "^0.7.0-rc.1"
- "expo-av": "^7.0.1",

iOS 13+ (not aware of this happening on iOS < 13)

### Steps to Reproduce

Start a recording and then let the app go to background (either by turning off the screen or letting the screen time out via OS settings).  After a minute or so the app will crash.  Happens every time on iOS.  No crashes on Android.

Using the following settings:
```
const audioMode = {
  allowsRecordingIOS: true,
  staysActiveInBackground: true,
  interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS,
  playsInSilentModeIOS: true,
  interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DUCK_OTHERS,
  shouldDuckAndroid: false,
  playThroughEarpieceAndroid: false,
};
```

### Expected Behavior

The app should not crash and should continue recording while in the background.

### Actual Behavior

App crashes.

### Reproducible Demo

Not reproducible on the iOS simulator as the app won't fully go to background.

**Comment by shamilovtim** [comment]
This suddenly appeared in our app at compile time about 20 minutes ago despite no change in dependencies

**Comment by IjzerenHein** [comment]
Hi! I'm going to close this issue as a ton of bug/stability fixes have been applied to `expo-av` since this issue (also related to activation/deactivation due to backgrounding). Feel free to reopen with additional details and a repro case when this issue is still relevant 👍

**Comment by jacklj** [comment]
I'm getting this exact bug: crashes in background after ~1 minute on iOS, latest `expo-av` in bare RN project.
Not doing anything fancy, just followed the install guide to do a basic implementation. 

Will try and do a repro case soon.
