### ISSUE TITLE
pre-empting some Expo-AV build issues

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#5825]
Version 0.10.2 of react-native-gifted-chat currently throws a compilation error with Expo-AV. this is not obvious as none of the error messages cite react-native-gifted-chat specifically.

just thought I'd call this out here incase anyone also runs into this issue. switch to `react-native-gifted-chat": "^0.10.0"` and your expokit app should compile.

**Comment by cruzach** [comment]
thanks for posting! Would you mind making a post over on our [forums](https://forums.expo.io/) about this, too? Just bc we try to keep github mainly for bug reports 😄 

Worthwhile to link the [relevant issue you opened on `react-native-gifted-chat`](https://github.com/FaridSafi/react-native-gifted-chat/issues/1432)
