### ISSUE TITLE
Specifying a loading icon in app.json causes Android to crash

### ISSUE THREAD

**Issue by ryanvanderpol** [expo/expo#583]
Since some issues have been found with the splash API in SDK20 I'm reverting back to using `loading.backgroundImage`.  However, on Android devices, the Expo logo keeps showing up over the top of that image.  Per [the app.json documentation](https://docs.expo.io/versions/latest/guides/configuration.html#icon-2) it seems like this is a configurable property via `loading.icon`. I've tried replacing it with a 1x1 transparent png and with an actual image and everything I do causes my app to crash when run via the Expo client on an Android device (iOS works fine).  The background image and the icon I specify *do* show up, but then the app hangs and stops responding and then crashes.  Removing the `loading.icon` property reverts it back to correct behavior (although the Expo logo still shows up then).

**Comment by itajenglish** [comment]
Was this bug ever fixed? My app is crashing as a result of this change.

**Comment by brentvatne** [comment]
the `loading` api is not supported anymore. any issues that may have existed with the `splash` api would have long since been resolved, to my knowledge. if you encounter an issue with it, please post an issue with more information!
