### ISSUE TITLE
Huge increase of size on SDK 35

### ISSUE THREAD

**Issue by jonathanatn** [expo/expo#5830]
I have seen a huge increase of size since I upgrade Expo to SDK35. (coming from SDK 33 so I don't know if it's due by v. 34 or 35)

My app go from 13mb to 25mb, for a simple todo list which seems a bit too much

Do there is something to do about that?

This is very problematic for the fact that size is a really important factor for app installation, many people will add an app on their phone depending of the size of it because they have a full memory, this issue could cause lot of harm in the future for Expo.

**Comment by jonathanatn** [comment]
<img width="894" alt="Screenshot 2019-10-02 at 11 02 42" src="https://user-images.githubusercontent.com/10233811/66031718-40b8e600-e504-11e9-9ae2-e0fae40b6d4a.png">

It seems to actually came from a huge increase in what Android consider as assets. It goes from 1.64mb to 9mb

**Comment by SimenB** [comment]
#5796

**Comment by jonathanatn** [comment]
<img width="272" alt="Screenshot 2019-10-02 at 11 32 17" src="https://user-images.githubusercontent.com/10233811/66033827-57613c00-e508-11e9-949a-4db28a1474f4.png">

I don't have any facedetector or expo-facedectector in my modules. Is it somewhere else?

**Comment by jonathanatn** [comment]
I have delete the folder:
unimodules-face-detector-interface

and erase these lines from the packages-lock.json
"unimodules-face-detector-interface": "~3.0.0",
"unimodules-face-detector-interface": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/unimodules-face-detector-interface/-/unimodules-face-detector-interface-3.0.0.tgz",
      "integrity": "sha512-fMQ3ZnhdOjbQ5ZXW62s/t1bbqBaenxzVIcgVEcwvLIFek0mx/EMHFkySgFkFjU11icUvaPEXW1yJtkK4QEpLhg=="
    },

It doesn't changed anything to the size

**Comment by rpander93** [comment]
Noticed the same issue. The APK contains a folder "models" in the assets folder which is ~10mb for stuff which I now assume is due to the face detector.

**Comment by cruzach** [comment]
As stated in #5796 :
> Most likely `face-detector` is responsible for most of this size increase, currently, we are using partially prebuild project with all the modules enabled, the process of building on our servers is mostly configuring, packaging and signing. Including a custom set of modules would require separate compilation per build, we plan to work on a way to build an app from precompiled packages, but it will take some time.

@jonathanatn even though you removed those lines and deleted the folder from your `node_modules`, the binary still includes the `face-detector` code. We do this for the reasons stated above about building, plus this also allows you to push over-the-air updates to use new APIs (instead of having to submit a whole new build). We are working on implementing a way to build apps with only the necessary packages, but if you need a smaller size right now, you might want to consider the bare workflow
