### ISSUE TITLE
MAPVIEW ERROR: Failed prop type: Invalid prop `region.latitude` of type `string` supplied to `MapView`, expected `number`.

### ISSUE THREAD

**Issue by aejaex** [expo/expo#5833]
### Environment

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react-navigation: ^3.11.0 => 3.11.0 

### Steps to Reproduce

NOTE: This error only occurs on Android, and not on IOS. On IOS this works perfectly fine.

HERE IS THE CODE:

class MapScreen extends Component{

    constructor(props){
        super(props);

        this.state ={
                    myLocation:{
                        latitude:Number(0),
                        longitude:Number(0)
                    },
                    mapRegion: {
                        latitude: Number(0),
                        longitude: Number(0),
                        latitudeDelta: 0.01,
                        longitudeDelta: 0.01
                      }, };
    }

    async componentWillMount() {
        
        await Expo.Font.loadAsync({

          'Futura': require('../../assets/Fonts/futura.ttf'),

        });

        await this.setState({isLoading:false, isRefreshing:true, latitude:0, longitude:0, 
                    myLocation:{
                        latitude:Number(0),
                        longitude:Number(0)
                    },                   
            mapRegion: {
            latitude: Number(0),
            longitude: Number(0),
            latitudeDelta: 0.01,
            longitudeDelta: 0.01
          }});

    }

    GetMarkers = () =>{

        try{
            var marks = [];

            var posts = this.state.gotPosts;
    
            for(let i = 0; i< this.state.gotPosts.length; i++){
    
    
                if(Number(posts[i].Latitude) === null || Number(posts[i].Latitude) === "" || Number(posts[i].Longitude) === null || Number(posts[i].Longitude) === ""){
                    
                    var loc = ({latitude:0,longitude:0});
    
                }
                else{
    
                    var loc = ({latitude:Number(posts[i].Latitude),longitude:Number(posts[i].Longitude)});
    
                }
    
                marks.push(<MapView.Marker
                                onPress={()=>this.MarkPress(posts[i].DisplayName, posts[i].UserEmail)}
                                coordinate={loc}>
                                <TouchableOpacity >
                                    <Image source={{uri:posts[i].UserPicture}} style={{height:60, width:60, 
borderRadius:10}}/>
                                </TouchableOpacity>
    
                            </MapView.Marker>)
    
            }
    
            return marks;
        }
        catch(e){
            //
        }

    }

render (){

                    <View style={{flex:1, justifyContent:'flex-start', alignItems:'center'}}>                        

                        <MapView
                                style={{ width:'100%', height:400 }}
                                initialRegion={this.state.mapRegion}
                                onRegionChangeComplete={this.handleMapRegionChange}
                            >
                            <MapView.Marker
                                coordinate={this.state.myLocation}
                                title="Me"
                                description="My Location"
                            />

                            {this.GetMarkers()}

                        </MapView>
</View>

}
}

### Expected Behavior

The Map should render with no glitches, and markers should be placed on the map as per the coordinates that have been provided.

### Actual Behavior

On IOS, the code above works fine - it's reliable and robust, there are no errors.

On Android, I get the following errors INTERMITTENTLY - So the code works fine at many times, and at many times it causes the app to crash (the worst kind of error possible). Here is the error:

"Error while updating property 'coordinate' of a view managed by: AIRMAPMARKER
                     null
                     Value for latitude cannot be cast from String to Double"

And along with the error I get two related warnings:

1) Warning: Failed prop type: Invalid prop `region.latitude` of type `string` supplied to `MapView`, expected `number`.

2) Warning: Failed prop type: Invalid prop `initialRegion.latitude` of type `string` supplied to `MapView`, expected `number`.

### Reproducible Demo

Kindly note the code shared above.

Hoping to hear from you soon !

**Comment by cruzach** [comment]
What Expo SDK is this and what version of `react-native-maps` do you have installed?

**Comment by IanReit** [comment]
Having the same issue
