### ISSUE TITLE
ImagePicker - Buttons are not localized to device locale

### ISSUE THREAD

**Issue by visto9259** [expo/expo#5834]
### Environment

 Expo CLI 3.1.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

Target:  iOS Expo Client, iOS

### Expected Behavior

The `Cancel` button and any other buttons should be localized as per the device's locale.  Or optionally, allow the `Cancel` button title to be set via the API parameters.

On that note, the `ImagePicker` iOS code file `EXImagePicker.m` has defaults options that seem to indicate that options could be set.  I tried to add `cancelButtonTitle` as an option to the `ImagePicker.launchImageLibraryAsync` call but it did change the `Cancel` button title.

    - (instancetype)init
    {
      if (self = [super init]) {
        self.defaultOptions = @{
                            @"title": @"Select a Photo",
                            @"cancelButtonTitle": @"Cancel",
                            @"takePhotoButtonTitle": @"Take Photo…",
                            @"chooseFromLibraryButtonTitle": @"Choose from Library…",
                            @"allowsEditing" : @NO,
                            @"base64": @NO,
                            };
       self.shouldRestoreStatusBarVisibility = NO;
      }
      return self;
    }

### Actual Behavior
The `Cancel` button is not localized to the device's locale settings.

![Capture](https://user-images.githubusercontent.com/7890483/66049656-d13df900-e4f9-11e9-8641-d230b362dce0.JPG)

### Reproducible Demo

Just run the `imagePickerFromCameraRoll34` snack from the documentation on an iOS device with a device locale other than English.

**Comment by lukmccall** [comment]
I've tried to reproduce this bug. Unfortunately, I've failed.
When I changed the device language, is also changed the button's titles.
<img width="337" alt="Screenshot 2019-10-04 at 08 51 48" src="https://user-images.githubusercontent.com/9578601/66187540-47229b80-e685-11e9-8caf-d4d1bb9cac3c.png">

It is worth mention that you can't change buttons titles.

**Comment by visto9259** [comment]
I tried different languages on my iPhone (iOS 12.4) and while the title and list content changes, the Cancel button remains Cancel.

So what's different between your environment and mine?  Is there the some config somewhere in Expo that I missed.

![capture 3](https://user-images.githubusercontent.com/7890483/66206379-f0659380-e67d-11e9-92cc-1afe0b4c213c.jpg)

**Comment by lukmccall** [comment]
@visto9259 are you are using expo client to run your application?

**Comment by visto9259** [comment]
@lukmccall I use the Expo client for development and testing.  Then I build the iOS app via the managed workflow and use TestFlight to install on the iPhone.  I have the same issue with the built app on the iPhone.

**Comment by lukmccall** [comment]
@visto9259, did you run it on a simulator? I've checked it in client and managed workflow app. Everything was working correctly. However, I've tested it only on iOS simulators. Maybe this bug only occurs on real devices. Sadly, now I don't have access to a physical device. I will try to reproduce it again next Monday.

**Comment by visto9259** [comment]
@lukmccall Only on a real device.  I'll try on the iOS simulator over the weekend.

**Comment by visto9259** [comment]
@lukmccall Ran it on an iOS simulator (iPhone 8, iOS 11) and same issue.

Here's my expo setup on my iMac:

Expo CLI 3.2.2 environment info:
  System:
    OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.11.1 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.2.2

Can someone else try to run the snack on an iPhone with a different locale, so that we can determine if it is my setup which is causing the issue?

![capture](https://user-images.githubusercontent.com/7890483/66230267-d180f480-e6b1-11e9-891d-e2536fee8d5c.png)

**Comment by lukmccall** [comment]
@visto9259, I've run it on real devices. It seems to happen on every device with iOS 11 or 10. 
I'm going to try to fix it.

**Comment by lukmccall** [comment]
I've tried to investigate this problem today. Unfortunately, it seems to be more complicated than I thought. Also, I think we can't fix this.

Long story short. When you change your system settings then system framework tries to fit in with a new language. However, it can change buttons titles, only when your app supports selected language. Sadly, when you're using our cloud, your app will only support the English language. To change this, you need to eject and build your app locally.  [Here](https://stackoverflow.com/questions/38588857/spanish-support-for-retake-and-use-photo-buttons-of-uiimagepickercontroller) you can check what you need to do to add multi-language supports. 

Moreover, Apple in its new system changed how it works. In iOS 13, your system settings will affect UI, even when an app doesn't support selected language.

**Comment by visto9259** [comment]
@lukmccall Thanks for letting me know.

I gather from your investigation than, for anyone developing an app in languages other than English, then some of the components will not localize when using the managed workflow and ejecting is the only option to have full support for other languages as it is required to modify settings directly in Xcode.

May I suggest that a plan be put in place to augment the managed workflow to support more info.plist and settings without having to eject.

I personally like the managed workflow as it handles the building for me.  It allows me to build standalone apps without having to spend too much time learning Xcode and Android Studio.  This is important when the dev team is small as in my case where I am the only developer.

**Comment by lukmccall** [comment]
I'm closing this issue for now. However, we'll discuss adding other languages support to Xcode builds. Unfortunately, I can't promise anything yet.

**Comment by amsimoes** [comment]
I'm having the same issue for ImagePicker Camera:

(My device has Portuguese as 1st language)

1. When in the camera waiting to take a photo, "Photo" and "Cancel" appear:

![IMG_6563](https://user-images.githubusercontent.com/13181161/66761987-0143af80-ee9d-11e9-8e01-458768c0de1d.PNG)

2. And afterwards, more critical, as it appears "Retake" and "Use Photo" which is not as universal:

![IMG_6564](https://user-images.githubusercontent.com/13181161/66761980-fc7efb80-ee9c-11e9-98f4-8485e3133c93.PNG)

Are these strings changeable somehow? Thank you

**Comment by lukmccall** [comment]
Hi @amsimoes, unfortunately, these strings come from system framework and you can't change them.   
However, when you use bare workflow, adding another language to Xcode settings will fix it.  Sadly, this options isn't available in other flows.

**Comment by amsimoes** [comment]
@lukmccall thanks for the answer!

Do you know if is there anyway to hide those buttons then? Like taking the picture and accepting it straightforward?

**Comment by lukmccall** [comment]
@amsimoes, Sadly `UIImagePickerController`, which is used in `expo-image-picker` doesn't have the option to hide these buttons.

**Comment by taneba** [comment]
@amsimoes 
@lukmccall 
@visto9259 

This issue can be fixed by set CFBundleDevelopmentRegion in your app.json.

```
"expo":{
  ...
  "ios":{
    "infoPlist":{
      "CFBundleDevelopmentRegion":"ja_JP"
    }
  }
}
```

**Comment by amsimoes** [comment]
@taneba Thanks for the info.

I've just tried it and inside Expo client it's still in English.
Probably only works in standalone - will try asap.

**Comment by lukmccall** [comment]
@taneba, thanks for the information. It won't work in the client, cause we don't use everything that is in app.json (some options need to be know during compilation). However, it'll work in a standalone app. 

@amsimoes, sorry for misleading you. I've forgotten about this option.

**Comment by qiliangya** [comment]
@lukmccall 
I have same problem.
For now, I need eject my project to work?

**Comment by amsimoes** [comment]
@qiliangya No, it works on the standalone app. When you build it and use it in the device, it's localized assuming you set the correct language in Plist.

**Comment by qiliangya** [comment]
> @qiliangya No, it works on the standalone app. When you build it and use it in the device, it's localized assuming you set the correct language in Plist.

It means that I need to break away from the Expo app and build a separate app. Is the plist I set effective?

**Comment by brentvatne** [comment]
@qiliangya - read https://github.com/expo/expo/issues/5834#issuecomment-574553123

**Comment by qiliangya** [comment]
> @qiliangya - read [#5834 (comment)](https://github.com/expo/expo/issues/5834#issuecomment-574553123)

I see, but it not work :(

**Comment by hugoh59** [comment]
Is this issue solved ?

**Comment by taneba** [comment]
Hey guys, you need to know you cannot control the localization on expo go (expo client), but it's configureable in standalone app which users will use, regardless of managed/bared workflow.

Correct me if it's wrong.

**Comment by dorkycam** [comment]
Does anyone know if there is a solution for this issue?

**Comment by RubenMCCarreira** [comment]
@lukmccall any update on this?

**Comment by branaust** [comment]
2026 and still an issue
