### ISSUE TITLE
Sentry under SDK 35 could not connect to Sentry native SDK

### ISSUE THREAD

**Issue by davidbiller** [expo/expo#5835]
## 🐛 Bug Report

So i tried today to install Sentry.

i get the Message as Alert in the App:
Warning, could not connect to Sentry native SDK. 

I found this info:

https://github.com/getsentry/sentry-react-native/issues/630

**Comment by cruzach** [comment]
Please open an issue at the [sentry-expo repo](https://github.com/expo/sentry-expo/issues)

Also, make sure to include a repro method, as I just tested and was able to setup (and use) `sentry-expo v2.0.1` on an SDK 35 project
