### ISSUE TITLE
[Android] Hot reloading not working on genymotion sim

### ISSUE THREAD

**Issue by jackhts4** [expo/expo#5846]
Issue : React Native Expo hot reloading not working

Environment
Expo CLI 3.1.2:
System:
OS: Window 7
Binaries:
Node: 10.16.3
npm: 6.9.0
npmPackages:
expo: ^35.0.0
react: 16.8.3
react-dom: 16.8.3
react-native-web: 0.11.7

Steps to Reproduce
Using Genymotion 3.0.2 and create a android emulator(9.0 - API 28)
Open code, running expo init and npm start,
connect to localhost:19002
run on android emulator
everything works fine until when I just randomly change anything in App.js
such as adding a TextInput or whatever, after saving.
the android emulator is not refreshing, 
'Building JavaScript bundle: finished in XXXms.' is not shown in the :19002 log
By connecting to my real iphone, changing stuff and saving in App.js do refresh automatically

Expected Behavior
reload app when i change code.

Actual Behavior
When i am changing anything in code but this changes not updating on my UI.

**Comment by cruzach** [comment]
We recommend using the [Android Studio Emulator](https://docs.expo.io/versions/latest/workflow/android-studio-emulator/), I haven't seen any problems with using that myself
