### ISSUE TITLE
[Expo 35]Keep getting error Could not determine "artifacts for com.github.Raizlabs.DBFlow:dbflow:4.2.4"

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#5847]
My project is ejected from Expo 35.
I checked my ```app/build.gradle``` and I do not have any ```DBFlow```stuff in it.

But when I run ```gradlew build``` or ```gradlew test```. I am keeping getting this error:
```
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.Raizlabs.DBFlow:dbflow:4.2.4
```
I am not familiar with gradle and I am not sure where this comes from. 
Can anyone help?

**Comment by changLiuUNSW** [comment]
I think it comes from here:
https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/expoview/build.gradle#L258

**Comment by changLiuUNSW** [comment]
If that is the case, we should update the docs to tell users to upgrade ```DbFlow``` instead of removing it
https://github.com/expo/expo/issues/5749

**Comment by changLiuUNSW** [comment]
I just fixed this by adding below code to ```app/build.gradle```:
```
  annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:4.2.4"
  implementation "com.github.Raizlabs.DBFlow:dbflow-core:4.2.4"
  implementation "com.github.Raizlabs.DBFlow:dbflow:4.2.4"
```

**Comment by NiciusB** [comment]
I had the same error, but it went away by clearing the cache (expo r -c)

**Comment by aslakrin** [comment]
@NiciusB was that all you did? I've tried your way, deleting all the gradle caches I could find, and node_modules, and tried adding back with updated version as described above. Still, I always get this:

```AWS Device Farm configuration is NOT VALID

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
> Could not determine artifacts for com.github.Raizlabs.DBFlow:dbflow:4.2.4: Skipped due to earlier error
```
Not sure what the earlier error is supposed to be about.

**Comment by NiciusB** [comment]
@aslakrin I don't know much about gradle, but maybe opening android studio and updating gradle helps? I did that before getting the error (and then clearing the cache), but it doesn't seem to be related to the problem

**Comment by changLiuUNSW** [comment]
@NiciusB I tried your solution. It didn’t work.

**Comment by shiba-hiro** [comment]
I'm facing a same error.
In my case, my local build (`./gradlew bundleDebug` on my Mac) works but production build on Bitrise (`$ /Users/vagrant/git/android/gradlew ":app:bundleRelease"`) fails.

```
> Task :app:preReleaseBuild FAILED

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:preReleaseBuild'.
> Could not resolve all dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not determine artifacts for com.github.Raizlabs.DBFlow:dbflow:4.2.4: Skipped due to earlier error
```


I tried solutions above but did not work;
- Add dependenies of `com.github.Raizlabs.DBFlow` in app/build.gradle
- Clear cache before gradlew command by `expo publish --clear --release-channel my-production-channel`
- Update gradle version by opening the project with Android Studio


Does anyone know other things I can try?

**Comment by 29er** [comment]
I am stuck with this issue. 
I added and removed those line and tried via .

> /gradlew installDebug

 cannot build. any help you be greatly appreciated

**Comment by aslakrin** [comment]
Gradle seems to be able to sync for me when I change `android/build.gradle` -> `allprojects { repositories { /* ...others... */ maven { url 'https://jitpack.io' } ...` and add www in front, so it's `www.jitpack.io`

**Comment by viktorgvozdikov** [comment]
> Gradle seems to be able to sync for me when I change `android/build.gradle` -> `allprojects { repositories { /* ...others... */ maven { url 'https://jitpack.io' } ...` and add www in front, so it's `www.jitpack.io`

it's helped me

**Comment by shiba-hiro** [comment]
It also works for me! Thank you!!

**Comment by changLiuUNSW** [comment]
@aslakrin Have you also added this back ?
```
annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:4.2.4"
  implementation "com.github.Raizlabs.DBFlow:dbflow-core:4.2.4"
  implementation "com.github.Raizlabs.DBFlow:dbflow:4.2.4"
```
