### ISSUE TITLE
Upgrade Android/iOS rendering engine to RN 0.61

### ISSUE THREAD

**Issue by ide** [expo/expo#5849]
- [x] Create new RN release (`sdk-36` branch)
- [x] Update bare-expo to work with iOS and Android (compilation errors on Android)
- [ ] Get Detox iOS tests passing (test-suite passes but Detox has errors) https://github.com/expo/expo/issues/5984
- [x] Get the Expo client working on iOS (mostly done)
- [x] Get the Expo client working on Android
- [x] Get Home working (mostly done but we need to bring in NetInfo)
- [x] Make sure jest-expo works, especially with Haste changes
- [x] Make sure all Jest tests pass
- [x] Update babel-preset-expo if needed
- [x] Update TS declarations
- [x] Fix log formatting in Expo CLI (Metro changed)

https://github.com/expo/expo/issues/5985
https://github.com/expo/expo/issues/5986
https://github.com/expo/expo/issues/5987
https://github.com/expo/expo/issues/5988
https://github.com/expo/expo/issues/5989
https://github.com/expo/expo/issues/5990

**Comment by esamelson** [comment]
going to go ahead and close this as all the work is finished except for one task which we are tracking separately here: https://github.com/expo/expo/issues/5984
