### ISSUE TITLE
Expected JavaScript, but got content type 'application/javascript; chartset=UTF-8'. Check that your internet connection is working.

### ISSUE THREAD

**Issue by justinr1234** [expo/expo#585]
Seeing this error on load:

https://github.com/expo/expo/blob/master/ios/Exponent/Api/EXJavaScriptResource.m#L142

I've tried everything short of reinstalling my OS. Changed node, changed watchman, global expo, used XDE, etc, etc, etc...

Anyone have ideas?

Sep  4 08:05:26 Justins-MBP Exponent[88409]: 2017-09-04 08:05:26.454 [info][tid:main][ABI15_0_0RCTBatchedBridge.m:72] Initializing <ABI15_0_0RCTBatchedBridge: 0x6180001ba5c0> (parent: <ABI15_0_0RCTBridge: 0x6000000d4040>, executor: ABI15_0_0RCTJSCExecutor)
Sep  4 08:05:26 Justins-MBP Exponent[88409]: 2017-09-04 08:05:26.462 [warn][tid:NSOperationQueue 0x61000043ada0 :: NSOperation 0x6180004415c0 (QOS: DEFAULT)][ABI15_0_0RCTBatchedBridge.m:110] Failed to load source: Error Domain=RCTJavaScriptLoaderErrorDomain Code=3 "Could not connect to development server.
	
	Ensure the following:
	- Node server is running and available on the same network - run 'npm start' from react-native root
	- Node server URL is correctly set in AppDelegate
	- WiFi is enabled and connected to the same network as the Node Server
	
	URL: http://localhost:3020/index.mobile.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles" UserInfo={NSUnderlyingError=0x618000441a70 {Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x61800025bcc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://localhost:3020/index.mobile.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles, NSErrorFailingURLKey=http://localhost:3020/index.mobile.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.}}, NSLocalizedDescription=Could not connect to development server.
	
	Ensure the following:
	- Node server is running and available on the same network - run 'npm start' from react-native root
	- Node server URL is correctly set in AppDelegate
	- WiFi is enabled and connected to the same network as the Node Server

**Comment by justinr1234** [comment]
Tracking here instead: https://github.com/sysgears/apollo-universal-starter-kit/issues/326

**Comment by terribleben** [comment]
Hey there - if you find a case where we could provide a clearer error message here, or if you think this error message was incorrect, let me know and we can reopen and track this.

**Comment by justinr1234** [comment]
@terribleben This looks to be a bug in the React Native code actually: https://github.com/facebook/react-native/blob/master/React/Base/RCTJavaScriptLoader.mm#L276

**Comment by justinr1234** [comment]
https://github.com/facebook/react-native/issues/15791

**Comment by terribleben** [comment]
cc @janicduplessis who I believe wrote that commit as part of some work he was doing for Expo. Also my fault since I think I was the one who requested this.
