### ISSUE TITLE
[localization] undefined is not an object (evaluating 'locale.replace') on iPhone pro 11 max

### ISSUE THREAD

**Issue by jazzy-pm** [expo/expo#5850]
I am using expo SDK 35 and when I open my app on iPhone pro 11 max. It gives me an error while building the app from the expo show below.

<img width="410" alt="Screen Shot 2019-10-03 at 11 33 25" src="https://user-images.githubusercontent.com/28728565/66107919-6d3b3380-e5d2-11e9-81c9-6e42aeafd9e2.png">

**Comment by lukmccall** [comment]
Hi @jazzy-pm, please check https://github.com/expo/expo/issues/5735. I think this issue is duplicated.

**Comment by c00piser** [comment]
I'm also having this problem. Any result yet ?

**Comment by lukmccall** [comment]
Hi @c00piser, please check #5735.

Also, I'm closing this because it's duplication of another issue.

**Comment by mgrada6** [comment]
Change the region of the phone simulator itself, go to settings > General > Language & Region and pick the United State as a region. It worked for me

**Comment by morer62** [comment]
It works for me too!!

**Comment by LucaRed** [comment]
This bug affects real devices too, not only the simulator.

IPAs sent via TestFlight crash immediately on my iPad 7th generation, iOS 13.2.2. After changing the language once, the app started working.

**Comment by zilahir** [comment]
any solution on this? both simulator and real devices are effected.
