### ISSUE TITLE
[docs] [Android] Audio encoder missing FLAC and PCM/WAVE

### ISSUE THREAD

**Issue by riwu** [expo/expo#5854]
https://docs.expo.io/versions/latest/sdk/audio/

audioEncoder :
- Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_DEFAULT
- Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AMR_NB
- Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AMR_WB
- Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AAC
- Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_HE_AAC
- Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AAC_ELD

From https://developer.android.com/guide/topics/media/media-formats.html#audio-formats, FLAC and PCM/WAVE should be supported but it's not listed above. 

The doc also did not clarify what the `RECORDING_OPTION_ANDROID_AUDIO_ENCODER_DEFAULT` is.

**Comment by cruzach** [comment]
If you take a look at the [expo-av android sourcecode](https://github.com/expo/expo/blob/1d5998d7b12e09194c889abb361f51d283da5083/packages/expo-av/android/src/main/java/expo/modules/av/AVManager.java), you can see it makes use of [MediaRecorder.AudioEncoder](https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder), and the constants provided there are the viable options for the `setAudioEncoder` method
