### ISSUE TITLE
Is it working for RN 0.61 ?

### ISSUE THREAD

**Issue by lucasriondel** [expo/expo#5858]
I have updated my bare app from 0.59 to 0.61 and my expo features are not working anymore. I am using expo-barcode-scanner and expo-image picker 7.0 but they doesn't seem to do anything.

The barcode scanner freezes the app when launched, and the image picker's `launchCameraAsync` is not launching either but doesn't freeze the app at least (and permissions are asked) on android.

Is Expo compatible with 0.61 ? When using expo-cli and creating a new project, it installs the 0.59.10 version of RN.

**Comment by cruzach** [comment]
We're working on upgrading the Expo SDK for RN 0.61 (there are some open issues about it) for our next release. 

With unimodules, we usually recommend using the same version of RN that the most recent SDK is pinned at, ymmv when trying to use a newer version of RN
