### ISSUE TITLE
Alert.alert inside fetch causes crash on device through expo XDE but not in expo snack emulator 

### ISSUE THREAD

**Issue by rafetkhallaf** [expo/expo#586]
I'm trying to push an alert message when something goes wrong with fetch(), when I run the code through Expo Snack, everything works fine. but when i push the code through the XDE and open on my device, the app crashes when when it tries to execute the alert command.

The code is too long, but the part that's having the issue is:
```
			fetch('http://....', {
				method: 'POST',
				headers: {
					'Accept': 'application/json',
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({
					otp: this.state.verificationCode,
					phone: this.state.countryCode + this.state.phoneNumber,
				})
			})
			.then((response) => response.json())
			.then((responseJson) => { 
				if(responseJson.Status === 'success') {
					Alert.alert('testing',
								'testing');
					this.navigation.navigate('Login');
				}
				else {
					Alert.alert(
						'testing',
						'testing');
				}
				console.log(responseJson);
			})
			.catch((error) => {
				console.error(error);
			});
```

The error message i get is:
```
There was a problem running Expo

Refresh

Exception '-[__NSDictionary length]: unrecogonized selector sent to instance .... was thrown while invoking alertWithArgs on target AlertManager with prams(
{
buttons = ({ 0 = OK; });
message = "...";
title = "...";
type = default;
},
169
)
```

I'm I doing something wrong?
everything is imported and the code works completely fine with no issues on Expo Snack, I thought it would be versions but not 100% sure:

i'm using:
node -v
v8.4.0
npm -v
5.3.0
expo xde
latest version

any advice would be appreciated!

**Comment by rafetkhallaf** [comment]
So i tested on other phones, out of 5 phones it only crashed on 2.

Currently working on figuring out why those two.

**Comment by dikaiosune** [comment]
Can you please paste your `package.json`? Thanks!

**Comment by terribleben** [comment]
Hi, it looks like your Alert usage is consistent with the [docs](https://facebook.github.io/react-native/docs/alert.html), so as far as I can tell you're not doing anything wrong. I would double check that your JS copy of the react-native dependency is the correct version. Maybe the JS lib is calling a different method footprint compared to what native code expects.

If everything looks ok, then I suggest opening an upstream issue with react-native.
