### ISSUE TITLE
RN WebView not loading (anymore) on SDK 33, 34, 35

### ISSUE THREAD

**Issue by bscaspar** [expo/expo#5864]
Snack: https://snack.expo.io/@bcaspar/webview

### Steps to Reproduce

Build a basic WebView from react-native, almost an exact replica of the minimal example on the [RN WebView site](https://facebook.github.io/react-native/docs/webview#source).

Note: this is not the react-native-community WebView, I haven't migrated to this yet and am currently unable to do so. Is this still supported by Expo? I've been assuming it is since it's still supported by react native.

### Expected Behavior

The web view loads the source. This is working successfully when deployed to a phone in prod but fails in the simulator and expo app. This was working successfully in dev as recently as last week.

### Actual Behavior

It appears as though the web view is stuck in the loading state. Again, I've only seen this on the simulator and expo app and snack. The same code is working as expected in the standalone app.

**Comment by cruzach** [comment]
Hi! Just to confirm, was Android working well for you while iOS was stuck in the loading state?

**Comment by bscaspar** [comment]
It looks like in the snack Android works as expected. I haven't been testing locally on Android since we only have an iOS app deployed.

The standalone app is SDK 33.

**Comment by cruzach** [comment]
We had to remove the `WebView` implementation that used `UIWebView` -> [PR here](https://github.com/expo/expo/pull/5578). A warning should be logged about the deprecation

Best option is to replace with `@react-native-community/webview`, but I know you said you can't migrate to that (could you explain why?)

**Comment by bscaspar** [comment]
I'm using Instagram oauth in the webview which persists the auth state in the cookies when the app is closed so users don't need to re-authenticate every time they open the app. However when they logout I need to clear the cookies, which, as far as I can tell, isn't possible with the community webview. There are multiple issues referencing a similar request but none seem to resolve it: [#737](https://github.com/react-native-community/react-native-webview/issues/737), [#386](https://github.com/react-native-community/react-native-webview/issues/387), [#175](https://github.com/react-native-community/react-native-webview/pull/175). I'm currently clearing the cookies with `RCTNetworking.clearCookies`.

**Comment by cruzach** [comment]
As a workaround, you can set the prop `useWebKit={true}` on your WebView component. Just tried it on a local project running SDK 35, worked like a charm

**Comment by bscaspar** [comment]
This works! I suppose this issue can be closed. However this prevents my previous method of clearing cookies from working. So I guess I'm back at square 0. :persevere:

**Comment by JulianKingman** [comment]
@cruzach can a note be added to the Expo 35 blog post? I almost shipped this a broken webview.

**Comment by cruzach** [comment]
@JulianKingman added 👍

**Comment by MinxianLi** [comment]
@cruzach Your solution 'useWebKit={true}' works, however, I notice, now it is very slow to load the video after setting 'useWebKit={true}', any suggestion?

**Comment by cruzach** [comment]
Use `@react-native-community/webview` instead?

**Comment by thanh90** [comment]
I used @react-native-community/webview and could not get an action for onMessage callback
