### ISSUE TITLE
[expo-av] Fullscreen mode forces to use native controls instead of custom controls

### ISSUE THREAD

**Issue by kosmateus** [expo/expo#5867]
Dear All, 
I'm trying to create video player which will has my own custom controls. It's possible to use those controls in normal mode, but when I switch to full screen mode native controls show up (In android and web video player). 
How can I disable native controls and use custom in fullscreen mode?? Is it even possible? 

I was also trying use https://github.com/ihmpavel/expo-video-player
But with the same result.

**Comment by cruzach** [comment]
Hi! Questions like this are better off posted on our [forums](https://forums.expo.io/). If you take a look at the [Expo Video](https://docs.expo.io/versions/latest/sdk/video/) docs, it states:
> This presents a fullscreen view of your video component on top of your app's UI. **Note that even if useNativeControls is set to false, native controls will be visible in fullscreen mode.**
