### ISSUE TITLE
[expo-app-auth] Unable to obtain authorization code response (always tries to obtain token)

### ISSUE THREAD

**Issue by btroia** [expo/expo#5868]
### Environment

```
  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 4.6.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.9.3
      @types/react-native: ^0.57.60 => 0.57.65
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.13.0
```

### Expected Behavior

Passing in `AppAuth` configuration options `clientId: [CLIENT_ID]` and `responseType: 'code'` (or `additionalParameters: { response_type: 'code' }`) without providing a `clientSecret` should only perform an authorization code request and not try to exchange the code for a token.

### Actual Behavior

`AppAuth` will always try to obtain a token. In cases where `clientSecret` isn't provided for security reasons (i.e., mobile app making a `code` request to pass back my server to securely handle obtaining tokens on behalf of users on the server side), a token request error is returned (even though I am not trying to request a token):

`Error: ERR_APP_AUTH: Non-200 HTTP response (401) making token request to 'https://api.fitbit.com/oauth2/token'.`

However, if `clientSecret` is included in the request, a successful token response is returned (regardless of what value `requestType` is set to:

```
{
  "accessToken": "eyLhbGciOiKzI1NiJ9.eyJh",
  "accessTokenExpirationDate": "2019-10-04T03:32:45.746Z",
  "additionalParameters": Object {
    "user_id": "1234CD",
  },
  "idToken": null,
  "refreshToken": "139f6f33478168a16a26c94",
  "tokenType": "Bearer",
}
```

But that's not what I want 🙂I need to get the code response object.

### Reproducible Demo

Example trying to obtain authorization code only (not a token) from Fitbit:

```
   const returnUrl = `${Linking.makeUrl()}/callback`;
   const config = {
      serviceConfiguration: {
        authorizationEndpoint: 'https://www.fitbit.com/oauth2/authorize',
        tokenEndpoint: 'https://api.fitbit.com/oauth2/token',
      },
      issuer: 'https://www.fitbit.com/oauth2/',
      // clientSecret: FITBIT_CLIENT_SECRET, <-- not providing clientSecret
      clientId: FITBIT_CLIENT_ID,
      redirectUrl:  returnUrl,
      scopes: ['activity weight'],
      additionalParameters: {
        response_type: 'code',
      },
    };

    try {
      const tokenResponse = await AppAuth.authAsync(config);
      console.log('FITBIT RESPONSE: ', tokenResponse);
    } catch (err) {
      console.log('FITBIT ERROR: ', err);
    }
```
`Error: ERR_APP_AUTH: Non-200 HTTP response (401) making token request to 'https://api.fitbit.com/oauth2/token'.`

Thanks in advance for your help!

**Comment by btroia** [comment]
Also, the error response object returned from the `AppAuth` target server usually provides more information than just the error code, but the library does not pass that information back in the result (rather, it just provides a generic `[Error: ERR_APP_AUTH: Non-200 HTTP response (401) making token request to <URL>]`

**Comment by EvanBacon** [comment]
I recommend migrating to use the new pure JS, universal AuthSession API which has tests and a guide for using FitBit auth: 

- [FitBit Guide](https://docs.expo.io/guides/authentication/#fitbit)
- [Example Usage](https://github.com/expo/expo/blob/e5473358605f40b1d5e9c6d396390f3a3f6ae928/apps/native-component-list/src/screens/AuthSession/AuthSessionScreen.tsx#L339-L378)

In time I'll be deprecating app-auth in favor of this new universal system.
