### ISSUE TITLE
ImagePicker crop not working in detached project

### ISSUE THREAD

**Issue by wilonth** [expo/expo#587]
Platform: Android
I tried creating a fresh project and **detached** it. The code just has a simple _ImagePicker_ call. If `allowsEditing: false`, things work normally. However with `allowsEditing: true`, I can pick an image but the crop UI is never displayed and the result is always set to "cancelled" even though I pick a valid image.  

The test project uses Expo SDK 18.0.3 with the valid Expo react-native fork, getting no important warning or errors. Note that this only happens for **detached** projects, it works well for normal undetached ones.

**Comment by daominhsangvn** [comment]
Are you testing on Android?

**Comment by wilonth** [comment]
@daominhsangvn of course, I mentioned that right at the beginning.

**Comment by daominhsangvn** [comment]
Okay sorry, here the solution: Open `AndroidManifest.xml` then add following into `<application>`
```
...
<application ...>
   <activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity" android:theme="@style/Base.Theme.AppCompat" /> <~ Add this line
   <activity android:name=".MainActivity" ... >
</application>
...
```

**Comment by dikaiosune** [comment]
Hi! Does this still happen on a newer ExpoKit project?

**Comment by wilonth** [comment]
@daominhsangvn Thank you, that works perfectly!
@dikaiosune Still happens with Expo 21.0.0

**Comment by OGPoyraz** [comment]
Any workaround / suggestion here ?

**Comment by aniltirola** [comment]
I just tested this with 
- expo sdk 25.0.0
- exp 49.1.0

Now everything works! :smiley:
After detaching with `exp detach` the 4 important lines mentioned by @daominhsangvn appear in `AndroidManifest.xml`.

Big thanks to the developers for fixing the bug.
