### ISSUE TITLE
Error with React-native-web: > 1 | module.exports = __webpack_public_path__ + "static/media/tuple.e6b50867.mjs";

### ISSUE THREAD

**Issue by rodhoff** [expo/expo#5871]
### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.1.2

Web

### Expected Behavior
I have some simple text components in a screen. Initially they have worked properly when using the "w" option, but now it is not working anymore.

### Actual Behavior

This error is triggered:
> 1 | module.exports = __webpack_public_path__ + "static/media/tuple.e6b50867.mjs";
[error_web.txt](https://github.com/expo/expo/files/3688801/error_web.txt)

**Comment by cruzach** [comment]
Could you provide a little more detail (steps to recreate, or the steps you took to run into this issue) as well as a demo that reproduces? thanks!

**Comment by rodhoff** [comment]
Hello!

I have attached my source folder so far - except the libs. Below is my package.json:

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/webpack-config": "^0.7.11",
    "@react-native-community/netinfo": "^4.3.1",
    "aws-amplify": "^1.1.40",
    "aws-amplify-react-native": "^2.1.19",
    "aws-appsync": "^2.0.0",
    "aws-appsync-react": "^2.0.0",
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-apollo": "^3.1.2",
    "react-dom": "^16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.0.0"
  },
  "private": true

I'm using aws-amplify, running on amaon's cloud9 IDE, with react-native.

The issue has apparently started after I have installed some of the libs. I think it may be probably after installing aws-amplify.

[source.zip](https://github.com/expo/expo/files/3696809/source.zip)

**Comment by EvanBacon** [comment]
fixed https://github.com/expo/expo-cli/pull/1075
