### ISSUE TITLE
Silence or fix warnings about deprecated rnpm config

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#5878]
![Screen Shot 2019-10-04 at 16 58 34](https://user-images.githubusercontent.com/90494/66246316-4101de80-e6c8-11e9-8556-432d2277adf7.png)

**Comment by fson** [comment]
Looks like we will just need to update these dependencies and the warnings will be gone.
- `lottie-react-native` has been [fixed](https://github.com/react-native-community/lottie-react-native/commit/9e25cca5ebcdd7d23d12b3d3bc5933b95f90f430#diff-b9cfc7f2cdf78a7f4b91a753d10865a2), in [v3.0.3](https://github.com/react-native-community/lottie-react-native/releases/tag/v3.0.3) and newer.
- `react-native-branch` has been [fixed](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/469#issuecomment-514826650), in [v4.0.0](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases/tag/v4.0.0) and newer.
- `react-native-maps` has been [fixed](https://github.com/react-native-community/react-native-maps/pull/2975) in [v0.26.0](https://github.com/react-native-community/react-native-maps/releases/tag/v0.26.0) and newer.

**Comment by fson** [comment]
I've silenced the warnings in Expo CLI (https://github.com/expo/expo-cli/pull/1165), because in any case they're not relevant to managed app developers, and according to the message the deprecated configuration should still work until the next release. I'll leave this issue still open in case we want to upgrade some of these modules for SDK 36.

**Comment by sjchmiela** [comment]
`react-native-branch` and `react-native-maps` have been updated, `lottie-react-native` is unupdatable due to introduction of Swift.

**Comment by sjchmiela** [comment]
Published `expo-cli` containing the mentioned PR. Since we aren't going to update `lottie-react-native`, I'll close this issue.
