### ISSUE TITLE
SecureStore not accepting whitespaces in values

### ISSUE THREAD

**Issue by Coriou** [expo/expo#588]
This code throws an error that I believe shouldn't be there and, it seems, rendering the SecureStore API pretty useless right now:

```js
import Expo from 'expo'

const store = Expo.SecureStore

let key = "SOMEKEY",
    value = "TEST VALUE"

store.setValueWithKeyAsync( value, key )
	.then( () => { console.log( "ALL GOOD" ) })
	.catch( (e) => { console.log( `Could not save "${key}" with value "${value}" in store (${e})` ) })
```

Log: `
Could not save "SOMEKEY" with value "TEST VALUE" in store (Error: Invalid key. Keys may not contain white space.)`

Expo SDK 20.0.0

**Comment by dikaiosune** [comment]
cc @RoninSTi

**Comment by RoninSTi** [comment]
This will be addressed in the next release which allows any valid string to be stored, including strings that contain whitespace.

**Comment by odero** [comment]
@RoninSTi The issue, it seems, is that it's throwing the error even for keys that DO NOT have whitespace in them. Or is that just a bug in expo?

**Comment by RoninSTi** [comment]
@odero Can you give me an example of a key/value pair that is throwing for you?  Also, are you experiencing an issue in ios/android or both?

**Comment by Coriou** [comment]
@odero I have had success when storing keys & values without spaces. As of 20.0.0, it will not accept spaces neither in the keys (which makes sense) nor in the values (which is the bug reported here).

**Comment by odero** [comment]
@Coriou @RoninSTi I guess it was the error message that was misleading by stating `Keys may not contain white space` while it's the value that have white space.

**Comment by Coriou** [comment]
@odero The message is indeed misleading too. But more importantly I think the value field should accept any valid string. Happy that this is getting fixed in the next update ! Great work on those new APIs btw :) (and Expo in general of course)

**Comment by ide** [comment]
SDK 21 (in progress) removes this constraint and you'll be able to store arbitrary strings in SecureStore. I'm closing this out now and you can expect to see it fixed when SDK 21 is released.

**Comment by danielmartinprieto** [comment]
Anyone knows when SDK 21 is supposed to be released?

**Comment by Creative-Dotlogics** [comment]
You are actually exchanging the position of the key and value in your secureStore function.

`SecureStore.setItemAsync(key, value, options)`

this should work
