### ISSUE TITLE
How to use Jest to test if a file has been written?

### ISSUE THREAD

**Issue by XW-Yanis** [expo/expo#5880]
Hi all, I am trying to write some tests for our little project. We used expo-file-system to allow us r/w on a device. The functionality works well on the device, but I am facing some critical problems. Below is my psuedocode of test.

`
import SaveData from "../app/resources/SaveData/SaveData"
import * as FileSystem from 'expo-file-system';

var promiseHolder = 0;

describe('\nsaveNewFile() is tested.\n', ()=>{
  it("A file is going to be created.",async ()=>{
    await FileSystem.getInfoAsync(FileSystem.documentDirectory + "helloTest5").then(
      function (result){
        console.log("File has existed "+result);
      },
      function (error){
        console.log("File is going to be create.");
        SaveData.saveNewFile("Hello from test5","helloTest5");
      }
    );
    promiseHolder = FileSystem.getInfoAsync(FileSystem.documentDirectory+'helloTest5');
    console.log(promiseHolder);
    // return expect(promiseHolder).resolves.toBe("Hello from test");
  })
})
`

But somehow I can't read from / write to the FileSystem.documentDirectory on my computer. What can I do? Thank you!

**Comment by SimenB** [comment]
Please note this issue tracker is not a help forum. We recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/MWRhKCj) for questions.

**Comment by cruzach** [comment]
The `expo-file-system` module [doesn't support web](https://github.com/expo/web-examples/blob/master/docs/FEATURES.md) just yet
