### ISSUE TITLE
Error in Svg

### ISSUE THREAD

**Issue by rajbchoudhary79** [expo/expo#5881]
Unable to resolve "./elements/Marker" from "node_modules\react-native-svg\src\xml.tsx"

this error showing when i use svg 

import Svg from 'react-native-svg';

**Comment by cruzach** [comment]
Hi! We have an [example snack](https://snack.expo.io/@charliecruzan/svgexample) that implements SVG, I suggest looking at that code, and yours, and seeing where the difference lies. 

It also depends on your SDK version and `react-native-svg` version (make sure you've run `expo install react-native-svg`), so if the issue persists then please provide all the info we ask for in the issue template, and I'll reopen the issue 👍
