### ISSUE TITLE
updateContactAsync for ios 13 not working

### ISSUE THREAD

**Issue by arnaudambro** [expo/expo#5884]
## 🐛 Bug Report

On iOS 13, without [`com.apple.developer.contacts.notes` entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_contacts_notes), the method [`updateContactAsync`](https://docs.expo.io/versions/latest/sdk/contacts/#updatecontactasync) throws an error.

To make it work, I guess there is a need of adding a `fields` argument, like it is the case for [`getContactByIdAsync`](https://docs.expo.io/versions/latest/sdk/contacts/#getcontactbyidasync) method (which is not working without the `fields` argument in iOS 13 neither).

### Environment

  System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.11.3 - ~/.npm/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      expo-cli: 3.0.10

Target: iOS 13

**Comment by dsokal** [comment]
It seems it has been fixed in https://github.com/expo/expo/pull/5601
