### ISSUE TITLE
How to update facebook ads SKD

### ISSUE THREAD

**Issue by knightkhan** [expo/expo#5886]
Expo ads facebook have using  api 'com.facebook.android:audience-network-sdk:5.1.1' i want to update its latest version  
 api 'com.facebook.android:audience-network-sdk:5.6.0-beta'
can i change it and how can i do so

**Comment by AdamJNavarro** [comment]
Hey @knightkhan,

I answered your forum post. https://forums.expo.io/t/how-to-update-facebook-ads-skd/28663/2 Please refrain from creating Github issues for questions like this one in the future. Creating a forum post like you did is the best way to ask questions.

Cheers,
Adam
