### ISSUE TITLE
[upstream] No SVG shown when using `react-native-svg` >v9.9.2

### ISSUE THREAD

**Issue by pkail** [expo/expo#5888]
## 🐛 Bug Report
The sample for SVGs shown in the docs causes Expo to crash.
I have included the metro.config.js file recommended on the react-native-svg-transformer GitHub page:
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
	const { resolver: { sourceExts, assetExts } } = await getDefaultConfig();
	return {
		transformer: {
			babelTransformerPath: require.resolve('react-native-svg-transformer')
		},
		resolver: {
			assetExts: assetExts.filter((ext) => ext !== 'svg'),
			sourceExts: [ ...sourceExts, 'svg' ]
		}
	};
})();
I included this because, without it, the Expo server fails to start, giving an error message saying that the metro.config.js file is missing.

I also updated App.js to include 

"packagerOpts": {
			"config": "metro.config.js",
			"sourceExts": [ "js", "jsx", "ts", "tsx", "svg" ]
		}
### Environment

  Expo CLI 3.2.3 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19.1 (Tessa)
      Shell: 4.4.19 - /bin/bash
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 

### Steps to Reproduce
Follow instructions here:
https://docs.expo.io/versions/latest/sdk/svg/

### Expected Behavior
See a circle and a rectangle.

### Actual Behavior
It crashed.

**Comment by pkail** [comment]
I also tried using:

import { Svg } from 'expo';
const { Circle, Rect } = Svg;

which is what is recommended on the react-native-svg GitHub page.  This produced a slightly different crash (blue circle rather than message).  I am using an Android device with reverse tethering.

**Comment by pkail** [comment]
The same code works on the iPhone, so I suspect that this is a problem with the Android app.

**Comment by anatula** [comment]
Look at this [issue](https://github.com/react-native-community/react-native-svg/issues/1127#issuecomment-538390517). Try using the exact version that Expo supports, change your `package.json` to `"react-native-svg": "9.9.2"`, (after running `expo install react-native-svg`) this worked for me!

**Comment by pkail** [comment]
Thanks very much for your help.
I am using 9.9.2.  There is a bug with Android's use of Rect.  It works OK with Circle.

**Comment by anatula** [comment]
Yes, I had the same problem as you, I'm using Android, when I tried to plot a Rect component on my device, the app closed but somehow if I plotted only the Circle it was OK (of the Expo page). In the thread I linked, in the comment one of the guys said that it was probably because of the "~9.9.2", which I changed and installed the EXACT 9.9.2 version and the problem went away. Sorry I can't help more

**Comment by pkail** [comment]
Thanks: you are correct.  I was using "^9.9.2" instead of  "9.9.2".  This was on a completely clean installation, so, for some reason, Expo put in the wrong version.  However, it does work now.

**Comment by cruzach** [comment]
Thanks for sharing the workaround!

**Comment by ilantuqqi** [comment]
Same, After changing to "react-native-svg": "9.9.2" everything works fine.
We had a problem using this library https://github.com/FullstackStation/react-native-svg-animated-linear-gradient and the error from android logcat was:

`10-08 11:27:10.722  8045  8045 E unknown:ReactNative: java.lang.NullPointerException: Attempt to read from field 'abi35_0_0.host.exp.exponent.modules.api.components.svg.SVGLength$UnitType abi35_0_0.host.exp.exponent.modules.api.components.svg.SVGLength.unit' on a null object reference
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.VirtualView.relativeOnWidth(VirtualView.java:360)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.RectView.getPath(RectView.java:79)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.draw(RenderableView.java:335)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:324)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.GroupView.drawGroup(GroupView.java:102)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.GroupView.draw(GroupView.java:81)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:324)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawChildren(SvgView.java:301)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawOutput(SvgView.java:252)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.host.exp.exponent.modules.api.components.svg.SvgView.onDraw(SvgView.java:104)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:20207)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19082)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19073)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:20210)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.widget.ScrollView.draw(ScrollView.java:1739)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:400)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19082)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:20210)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19082)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:20210)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19082)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19073)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19073)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.support.v4.widget.i.drawChild(DrawerLayout.java:1426)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:19073)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.draw(View.java:19935)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at abi35_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:684)
10-08 11:27:10.722  8045  8045 E unknown:ReactNative:   at android.view.View.updateDisplayListIfDirty(View.java:1
10-08 11:27:10.835  1987  2005 E memtrack: Couldn't load memtrack module
10-08 11:27:10.835  1987  2005 W android.os.Debug: failed to get memory consumption info: -1
10-08 11:27:11.014  8045  8180 I ExoPlayerImpl: Init 69e8769 [ExoPlayerLib/2.9.2] [generic_x86, Android SDK built for x86, Google, 28]
10-08 11:27:11.017  8045  8180 D i       : WARNING: getPackageName called on ScopedContext
10-08 11:27:11.022  1987  6862 I MediaFocusControl: abandonAudioFocus() from uid/pid 10087/8045 clientId=android.media.AudioManager@ac8ca8fabi35_0_0.expo.modules.av.AVManager@149396
10-08 11:27:11.023  8045  8180 I ExoPlayerImpl: Init ed0011c [ExoPlayerLib/2.9.2] [generic_x86, Android SDK built for x86, Google, 28]
10-08 11:27:11.024  8045  8180 D i       : WARNING: getPackageName called on ScopedContext
10-08 11:27:11.027  1987  6862 I MediaFocusControl: abandonAudioFocus() from uid/pid 10087/8045 clientId=android.media.AudioManager@ac8ca8fabi35_0_0.expo.modules.av.AVManager@149396
10-08 11:27:11.044  1987  2382 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@38ab736)
10-08 11:27:11.044  1987  2005 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@38ab736)
10-08 11:27:11.045  8045  8045 D AndroidRuntime: Shutting down VM
10-08 11:27:11.049  8045  8045 E AndroidRuntime: FATAL EXCEPTION: main
10-08 11:27:11.049  8045  8045 E AndroidRuntime: Process: host.exp.exponent, PID: 8045`

**Comment by brentvatne** [comment]
@pkail @ilantuqqi - i suspect that you're using npm rather than yarn. it turns out that npm doesn't behave as one might expect when installing a package, if you run `npm install react-native-svg@9.9.2` it'll add a more loose matcher. we handle this behavior properly in the latest version of expo-cli: https://github.com/expo/expo-cli/pull/1059

sorry about that!

**Comment by spyshower** [comment]
I am having the same problem, an svg isn't showing and I can't figure out a solution. I have tried multiple versions too. Shall I open an issue or..?

**Comment by brentvatne** [comment]
@spyshower - `expo install react-native-svg` - does this not resolve your issue?

**Comment by spyshower** [comment]
> @spyshower - `expo install react-native-svg` - does this not resolve your issue?

Unfortunately not. To be honest there is something mysterious with that specific svg, although I am sure something buggy is going on, as I came here looking for a thread like this and I indeed found it.

**Comment by brentvatne** [comment]
could you share the svg in question?

**Comment by djangojack** [comment]
I had the same issue - 

`expo install react-native-svg` adds `"react-native-svg": "~9.9.2",` to package.json, which resolves as 9.9.9 in yarn.lock. This version is not actually rendering the svg on Android via react-native-qrcode-svg. Removing the `~` and updating package.json to "9.9.2" resolved the issue for me.

**Comment by spyshower** [comment]
@brentvatne here it is:
```

import React from 'react';
import { Svg } from 'expo';
const { Circle, Rect, Path, Line, TSpan, TextPat, G } = Svg;



export default function LooxLogoFull(props) {


  const color = props.letterColor == 'white' ? 'rgb(240,240,240)' : '#a649f2'
  const reverseColor = props.letterColor == 'white' ? '#a649f2' : 'rgb(240,240,240)'
  
  const letterOpacity = props.letterColor == 'white' ? '0.9' : '1'

  return (
    <Svg style={props.style} version="1.1" viewBox="-200 375.9 195 70" xmlSpace="preserve">


      <G transform="translate(0, 62)">
        <G transform="translate(530 240) scale(0.94)">
    		<Path fill={color} opacity='0.3' d="M-739.8,217.1c-6.2,1.5-17.2-8.2-24.7-21.5c-7.5-13.3-8.5-25.3-2.4-26.8s17.2,8.2,24.7,21.5&#xA;&#x9;&#x9;C-734.7,203.6-733.6,215.6-739.8,217.1z"/>
    		<Path fill={color} opacity='0.6' d="M-752.8,191.5a11.9,25.7 0 1,0 23.8,0a11.9,25.7 0 1,0 -23.8,0z"/>
    		<Path fill={color} opacity='0.9' d="M-715.2,168.7c6.1,1.5,5.1,13.5-2.4,26.8c-7.5,13.3-18.5,23-24.6,21.5&#xA;&#x9;&#x9;c-6.2-1.5-5.1-13.5,2.4-26.8C-732.4,176.9-721.4,167.3-715.2,168.7z"/>
    	</G>
      <G transform="translate(0, -8)">

        <G transform="translate(0, 2)">
      		<Path fill={color} d="M-117.6,448.9v-50.3h3.1v50.3H-117.6z"/>
      		<Path fill={color} d="M-90,449.7c-5,0-8.9-1.6-11.8-4.9c-2.9-3.3-4.3-7.5-4.3-12.7c0-5.6,1.5-10.1,4.5-13.2c3-3.2,7-4.8,11.9-4.8&#xA;&#x9;&#x9;c4.8,0,8.7,1.6,11.5,4.7c2.8,3.2,4.2,7.5,4.2,13.1c0,5.3-1.4,9.6-4.3,12.8C-81.1,448.1-85,449.7-90,449.7z M-89.7,416.8&#xA;&#x9;&#x9;c-4,0-7.2,1.4-9.6,4.1c-2.4,2.7-3.6,6.5-3.6,11.3c0,4.4,1.2,8,3.5,10.7c2.3,2.7,5.5,4.1,9.5,4.1c4.1,0,7.2-1.3,9.5-4&#xA;&#x9;&#x9;c2.2-2.7,3.3-6.3,3.3-11.1c0-4.8-1.1-8.6-3.3-11.2C-82.6,418.1-85.7,416.8-89.7,416.8z"/>
      		<Path fill={color} d="M-51.8,449.7c-5,0-8.9-1.6-11.8-4.9c-2.9-3.3-4.3-7.5-4.3-12.7c0-5.6,1.5-10.1,4.5-13.2c3-3.2,7-4.8,11.9-4.8&#xA;&#x9;&#x9;c4.8,0,8.7,1.6,11.5,4.7c2.8,3.2,4.2,7.5,4.2,13.1c0,5.3-1.4,9.6-4.3,12.8C-42.9,448.1-46.8,449.7-51.8,449.7z M-51.6,416.8&#xA;&#x9;&#x9;c-4,0-7.2,1.4-9.6,4.1c-2.4,2.7-3.6,6.5-3.6,11.3c0,4.4,1.2,8,3.5,10.7c2.3,2.7,5.5,4.1,9.5,4.1c4.1,0,7.2-1.3,9.5-4&#xA;&#x9;&#x9;c2.2-2.7,3.3-6.3,3.3-11.1c0-4.8-1.1-8.6-3.3-11.2C-44.4,418.1-47.6,416.8-51.6,416.8z"/>
      		<Path fill={color} d="M-18.1,432.2L-7,448.9h-3.9l-9-14.3H-20l-1.2,1.9c-0.2,0.3-0.3,0.6-0.6,0.9l-7.5,11.6H-33l11.4-16.6&#xA;&#x9;&#x9;l-11.2-17.4h3.6l7.6,12.2c1,1.6,1.6,2.5,1.8,2.9h0.1l1.7-2.8l7.9-12.3h3.6L-18.1,432.2z"/>
      	</G>
      </G>
      <Rect x='-120' y='386' width='10' height='10' fill={reverseColor} opacity='1'/>
    </G>

    </Svg>
  );
}

```

**Comment by kopax** [comment]
hi! I am on 9.13.3 and downgrading to 9.9.2 break my app. I have no svg displayed on Android device. Any clue ?
