### ISSUE TITLE
decorators-legacy support in expo web 

### ISSUE THREAD

**Issue by davidbiller** [expo/expo#5894]
So i guess this is not a bug, but a question of setting.

So can someone help?

Support for the experimental syntax 'decorators-legacy' isn't currently enabled.

"sdkVersion": "35.0.0",
 "mobx": "^4.3.1",
"react-native-web": "^0.11.4",

"devDependencies": {
    "babel-preset-expo": "^7.0.0",
    "expo-codemod": "^1.0.0",
    "jest-expo": "^27.0.0"
  }

and babel rc file

{
  "presets": ["babel-preset-expo"]
}

**Comment by cruzach** [comment]
Not sure what exactly the question here is, but we keep github reserved for bug reports, so for questions regarding Expo, you're better off posting on our [forums](https://forums.expo.io/) 👍
