### ISSUE TITLE
ios.userInterfaceStyle override to light mode does not affect DatePickerIOS inside of Modal / or Alerts or ActionSheets

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#5897]
### Environment

Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.2.3

Target: iOS 13 Managed and ExpoKit

### Steps to Reproduce

1. Create a blank Expo app with `expo init`. (you could also eject here and get the same results)
2. Replace the JSX in App.js with something that shows a DatePickerIOS in a modal, like:
```
export default function App() {
  const [ showModal, setShowModal ] = useState(false);

  return (
    <View style={styles.container}>
      <Button
        onPress={() => {
          setShowModal(true);
        }}
        title="Press to show a modal with a non-working DatePicker"
      />
      <Text>This DatePicker works OK in dark mode</Text>
      <View style={{ height: 40, width: 300 }}>
        <DatePickerIOS mode="date" date={date} onDateChange={() => {}} />
      </View>
      <Modal visible={showModal}>
        <View style={{ flex: 1, backgroundColor: 'pink', justifyContent: 'center', alignItems: 'center' }}>
          <Button
            onPress={() => {
              setShowModal(false);
            }}
            title="Close modal"
          />
          <View style={{ width: 300 }}>
            <DatePickerIOS mode="date" date={date} onDateChange={() => {}} />
          </View>
        </View>
      </Modal>
    </View>
  );
}
```
3. Make sure `ios.userInterfaceStyle` is set to `light` or is not set at all (which should default the app to force light mode)
4. Run the app (simulator or device)
5. Switch the device to dark mode
6. Open the modal.

### Expected Behavior

The `DatePickerIOS` inside the `Modal` should look just like the one outside of it, with dark text on a light background (just like how it would look when the phone is in light mode).

<img width="338" alt="Screen Shot 2019-10-07 at 4 08 38 PM" src="https://user-images.githubusercontent.com/8053974/66344844-c7aef980-e91c-11e9-9804-45bbd5299158.png">

### Actual Behavior

The `DatePickerIOS` inside the `Modal` has light text, while the one outside of the modal has dark text. On a white background, the picker inside the modal would not be visible.

<img width="317" alt="Screen Shot 2019-10-07 at 4 10 19 PM" src="https://user-images.githubusercontent.com/8053974/66344950-faf18880-e91c-11e9-9fd4-35ffdd0ef1e5.png">

### Reproducible Demo

Here is a demo. I did this in ExpoKit, because it lets you play around with some options that actually things work correctly.

1. Clone https://github.com/llamaluvr/Expo-35-Dark-Mode-DatePicker-Issue
2. run `yarn` and `cd ios; pod install` to restore dependencies
3. `yarn start`
4. Run the app from Xcode to the simulator or device

### Workarounds

Going back to the ExpoKit version, if you add the `UIUserInterfaceStyle` key to `Info.plist` with a value of `Light`, then you will see the expected behavior (the modal date picker looks right).

Hopefully, adding this propery to `ios.infoPList` in `app.json` has the same effect on managed apps. TestFlight is taking its good old time today, so I'll update that once it finishes.

***UPDATE***

I just set
```
"infoPlist": {
        "UIUserInterfaceStyle": "Light"
      }
```
and it fixed the DatePicker issue. Not only that, but a bunch of other non-ViewController elements started showing up in light mode again - alerts and action sheets. So, it seems like there's a whole lot of overriding to light mode that cannot be achieved unless using the Info.plist setting.

### Discussion

I think what is happening is that `ios.userInterfaceStyle` is being applied in `ExAppViewController` for both managed and ExpoKit apps using the `UIViewController.overrideUserInterfaceStyle` property (see https://github.com/expo/expo/blob/6e2eab62e4d4c563ffe699b9c54d19a106ea44c0/ios/Exponent/Kernel/Views/EXAppViewController.m#L398). This is applied per-view-controller. Meanwhile, the React Native `Modal` is appears to be hosted in a separate `UIViewController`, which is not getting this override applied.

Since the override isn't being applied to the modal at all, in theory, this means other UI components that would be changed by dark mode would also be affected. I can't think of any similar components off the top of my head.

**Comment by mauriciord** [comment]
The `"userInterfaceStyle": "light"` in `app.json` section  `"ios"` doesn't work in this case :/

**Comment by psppro26** [comment]
How did you make it work with "infoPlist": {
        "UIUserInterfaceStyle": "Light"
      }
?
i run expo 35 and the issue still here with your first :/

**Comment by llamaluvr** [comment]
@psppro26 my app.json looks like this:
```
"infoPlist": {
        "UIUserInterfaceStyle": "Light"
      }
```
Note that this only takes affect on a standalone build created through Expo's servers. The Expo client cannot apply Info.plist values.

**Comment by psppro26** [comment]
So there is no workaround for app running with expo ?

**Comment by llamaluvr** [comment]
@psppro26 none I know of (besides implementing a dark mode so the white text of the date picker appears)

**Comment by tleed5** [comment]
Hmm, I tried adding the `UIUserInterfaceStyle` to app.json but even after building through expo and deploying through test fairy it still wasn't forcing light mode. We're running expo 35 managed

**Comment by brentvatne** [comment]
you shouldn't need to use that infoplist property on a managed expo project, there is a specific app.json configuration for this: https://docs.expo.io/versions/v35.0.0/sdk/appearance/#configuration

**Comment by lukBakTsh** [comment]
Currently, setting the `userInterfaceStyle` option does not affect the `Modal` -> `DatePickerIOS` component. Definitely, this is a bug.

**Comment by Riseley** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/320

**Comment by Riseley** [comment]
Issue happens in SDK35, welp, the easy but moot workaround is implement Dark Mode like llamaluvr said.

**Comment by Riseley** [comment]
> Currently, setting the `userInterfaceStyle` option does not affect the `Modal` -> `DatePickerIOS` component. Even worse, `react-native-appearanc` returns the light value, and the interface is presented for the dark value. So I can't react properly. Definitely, this is a bug.

Exact same issue. The Appearance thing returns "light", but the interface is white yet the text is dark.

**Comment by Velua** [comment]
@psppro26 A work around for Expo would be to use the Appearance API to detect what the OS is set too then use the isDarkMode prop on the ```react-native-modal-datetime-picker``` library. 

Just make sure you set your ```app.json``` include ```    "userInterfaceStyle": "automatic",``` on the ```expo``` property.

**Comment by Velua** [comment]
> Currently, setting the `userInterfaceStyle` option does not affect the `Modal` -> `DatePickerIOS` component. Even worse, `react-native-appearanc` returns the light value, and the interface is presented for the dark value. So I can't react properly. Definitely, this is a bug.

Mine was returning the ```light``` value despite the phone being on dark mode until I set the ```app.json``` to include ```"userInterfaceStyle": "automatic"``` for some reason this doesn't appear to happen automatically.
