### ISSUE TITLE
[docs] Consolidate Documentation on OTA Updates

### ISSUE THREAD

**Issue by tcdavis** [expo/expo#5898]
Documentation on how OTA Updates work is spread across:
- https://docs.expo.io/versions/v35.0.0/workflow/publishing/ 
- https://docs.expo.io/versions/v35.0.0/distribution/release-channels/ 
- https://docs.expo.io/versions/v35.0.0/distribution/advanced-release-channels/ and 
- https://docs.expo.io/versions/v35.0.0/guides/configuring-ota-updates/
- https://docs.expo.io/versions/v35.0.0/sdk/updates/

which makes it difficult for users to be confident relying on the feature or get answers to questions like:
- “why aren’t I getting the update I just made”
- “if I publish this will I break things for my users that have a different SDK version”

Let's try to consolidate these pages as much as possible so the information is easy to find and digest.

**Comment by tcdavis** [comment]
![image](https://user-images.githubusercontent.com/4551666/66605461-00d9aa80-eb65-11e9-94f7-babc457ec3fe.png)

**Comment by cruzach** [comment]
The new docs should address this common question: https://github.com/expo/expo/issues/7258

**Comment by brentvatne** [comment]
closing this issue because it's not a bug but cc @jonsamp to make sure it's considered in EAS Update docs
