### ISSUE TITLE
Problem with IOS emulator

### ISSUE THREAD

**Issue by thiagoterleski** [expo/expo#59]
I open my IOS emulator from xcode and when I try to run project from exponent, this errors happens:

`You may need to install Xcode from https://developer.apple.com/xcode/download/.`

**Comment by sonaye** [comment]
Xcode > Preferences > Locations
![screen shot 2017-02-16 at 5 45 16 am](https://cloud.githubusercontent.com/assets/23000873/23005067/35e1c2de-f40b-11e6-827c-f56f0a556db9.png)
