### ISSUE TITLE
Possible CLI Feature

### ISSUE THREAD

**Issue by iamclaytonray** [expo/expo#590]
I was looking around on the docs and didn't really find anything relating to an Expo CLI. Did I miss this? If not, is there chance of integrating a CLI with Expo? I personally am not a fan of GUIs and it kind of messes with my workflow. (As a side note, I wouldn't mind contributing with a fully featured CLI). At least something (to start off with) basic like:

`expo init AwesomeApp`
`cd AwesomeApp`
`yarn start`(or npm)

The idea would be to boilerplate the app with additional features, like react-navigation, somewhat setup, where a developer could come in and just make changes/add routes. That's just one example. (Basically, what you already have with the GUI as a first step, and then add new features in as time progresses)

**Comment by iamclaytonray** [comment]
I should also add, I am brand new to the Expo community. Maybe I missed this in the docs? If so, if you could point me out to where it is in the docs, that would be great.

**Comment by DigiOrb** [comment]
There is already a CLI for Expo called EXP. The links below will take you to the docs:
https://docs.expo.io/versions/latest/guides/exp-cli.html

You will need to first install globally:
npm install -g exp

then the CLI cmd start as below:
exp [options] [command]

The Github for this is:
https://github.com/expo/exp

Hope this helps.

**Comment by iamclaytonray** [comment]
Awesome, thanks! I guess I should have read the docs better 😅

**Comment by dikaiosune** [comment]
@DigiOrb is correct -- most development features of XDE are available through `exp`.
