### ISSUE TITLE
Expo 35, Push Notifications not working on android "Error: Couldn't get GCM token for device"

### ISSUE THREAD

**Issue by FrickenHamster** [expo/expo#5900]
### Environment

Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.11.0 - ~/.nvm/versions/node/v12.11.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v12.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.2.3

Issue is on android, I've tested on S7 and One Plus 7 Pro

### Steps to Reproduce

Upgrade and old app using push notifications to expo 35. I also tried singling out the problem by creating a new project that only tried getting a token.

Alternatively, you can try the example on the expo page, https://snack.expo.io/@charliecruzan/pushnotifications34?platform=ios
which will give the same issue.

Here is the relevant part of my code

```
async requestNotificationPermissions() {
    let { status: latestStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS)
    console.log('permission status', latestStatus)
    if (latestStatus === 'granted') {
      return true
    } else {
      ;({ status: latestStatus } = await Permissions.askAsync(Permissions.NOTIFICATIONS))
      if (latestStatus === 'granted') {
        return true
      }
    }

    return false
  }

async componentDidMount() {
  const haveNotificationPermissions = await this.requestNotificationPermissions()
    if (!haveNotificationPermissions) {
      return
    }
    try {
    const token = await Notifications.getExpoPushTokenAsync()
    } catch (e) {
      console.log('waaa', e)
    }
    console.log('ree', token)
}
```

### Expected Behavior

I expected it to correctly get an expo push token

### Actual Behavior

I get an error that says 
`Error: Couldn't get GCM token for device`

**Comment by AdamJNavarro** [comment]
Hey @FrickenHamster, 

For clarity's sake, when you say "I also tried singling out the problem by creating a new project that only tried getting a token." did the new project also throw the GCM token error?

**Comment by FrickenHamster** [comment]
> Hey @FrickenHamster,
> 
> For clarity's sake, when you say "I also tried singling out the problem by creating a new project that only tried getting a token." did the new project also throw the GCM token error?

Yes it did

**Comment by FrickenHamster** [comment]
hey @cruzach thanks for the response.
I tried again by running the snack again. I am running it in the expo app. If I scan the qr code from the snack, it fails to give me a notification, but doesn't give any warnings.
If I copy the code into a local repo, or I download the code and run expo start, it gives me the gcm token warning.

 I'm going to try building the app

**Comment by cruzach** [comment]
Hm..just copy/pasted the snack code into a blank `expo init` project using `expo-cli` version `3.2.3` and got the token no problem

**Comment by FrickenHamster** [comment]
@cruzach
Thanks for testing.
I can't really explain what happened, but 10 minutes ago, notifications started working on our app, and now I can get tokens in the snack and test apps

**Comment by cruzach** [comment]
That's great! although knowing what the cause was would've certainly helped...no update to the Expo Client app or anything like that?

**Comment by FrickenHamster** [comment]
I wish I knew more. It just started working for me. We're working on getting a build out to see if it fixes the problem.

**Comment by ucallQA** [comment]
We are getting the same error but only for some of our users. We used to use GCM and have uploaded the FCM server key / JSON client file according to the Expo docs. Maybe the issue is occurring for us because we used to use GCM and updated pretty late? We are on the latest version of Expo and FCM does work for most of our users, but every day we get several users who get the error "Couldn't get GCM token for device". It only happens on standalone / production for our app, I would post code but it's all standard and followed from the docs so I'm not sure if it would be useful.

**Comment by cruzach** [comment]
@ucallQA Are those users that it's happening to on the most recent version of your binary?

@FrickenHamster let me know if that new build resolved the issue

**Comment by ucallQA** [comment]
@cruzach Most of the users who had the issue before do have the newest binary, although some who have the new binary still appear to have the issue according to Sentry. Maybe it's a cache issue with some of these users? I was wondering if there is anything on Expo's side that would cause this for accounts who upgraded to FCM really late (maybe kept the old GCM keys or something)

**Comment by FrickenHamster** [comment]
@cruzach Currently, everything is working. I don't know if the new build had anything to do with it, but in addition to the GCM issue on devices, our FCM key disappears from expo suddenly. I am unsure the cause of that.

**Comment by Foxhound401** [comment]
I don't know if this is relevant or not but i encouter that GCM issue only when I'm not sign in to the expo-cli, after signed in with expo account everything works fine

**Comment by ivansenic** [comment]
We hit the first user in the production today that experienced this error. We got a Sentry error report so I can send back anything that can be valuable here. 

Just quick info, it's on the latest SDK (v35.0.0) and user is running Android 28.

**Comment by cruzach** [comment]
@ivansenic I still haven't been able to reproduce this.

Are you relying on GCM for your push notifications, rather than FCM? The GCM servers should have been shut down in May. Do you know if the user who ran into this issue was on a binary from before you [configured FCM](https://docs.expo.io/versions/latest/guides/using-fcm/)?

**Comment by ivansenic** [comment]
@cruzach The first version of our app was deployed at the end of the August. We always used the FCM setup and it was working without any problem until this one error report (still we got this only for one user). So we never had GCM setup I am pretty sure here.

**Comment by bill-pairaktaridis** [comment]
> I don't know if this is relevant or not but i encouter that GCM issue only when I'm not sign in to the expo-cli, after signed in with expo account everything works fine

Thank you! I've been trying to figure this out literally all day!

**Comment by subhu9999** [comment]
> I don't know if this is relevant or not but i encouter that GCM issue only when I'm not sign in to the expo-cli, after signed in with expo account everything works fine

This Works ! Thank you very muchhh !!

**Comment by cruzach** [comment]
Looks like this has been resolved for OP, and the additional solution of signing into expo-cli resolves it for others

but, I've opened a new issue here for that since it seems more appropriate to put in the `expo-cli` repo https://github.com/expo/expo-cli/issues/1389

**Comment by nikhilthakur001** [comment]
> I don't know if this is relevant or not but i encouter that GCM issue only when I'm not sign in to the expo-cli, after signed in with expo account everything works fine

This fixed the issue. Thanks.

**Comment by AakashPat** [comment]
I have been running into the same issue and this solution has not worked for me. I am already logged in to my expo account on the expo-cli.

> I don't know if this is relevant or not but i encouter that GCM issue only when I'm not sign in to the expo-cli, after signed in with expo account everything works fine

**Comment by zifahm** [comment]
same here unable to get the token. 

## I dont even get an error. when I console.log(token) there is nothing.

**Comment by alkeshattal** [comment]
**Please make sure that you are on the latest version of the Expo Client App, that supports the SDK you are running**
I had the older version of Expo Client (installed in Feb'20) and my react-native project was using SDK 37 released in April. I spent the entire day trying to figure out why the notification service is not working. Then I borrowed my friend's mobile (also on Android 9) today and it worked.
On further digging, saw the expo client release notes published on April 14 about support on SDK 37.
Updated my Expo Client
Logged in with my Expo account on both CLI and Client
Expo Start
It Worked!!!
Thank God, I found it, was about to switch to FCM.
I wonder why I wasn't prompted by the Expo App to update.

@zifahm  & @AakashPat 
Maybe it was similar for you. SDK 37 released on 31st March and Client was updated on April 14th.

**Comment by ashishsober** [comment]
@alkeshattal you saved my day,absolutely correct just do the login in expo cli .
   expo login 
then type your user name and password,then do the same from physical device.

It will work
