### ISSUE TITLE
[docs] Clarification on the correct file for supported info.plist

### ISSUE THREAD

**Issue by leoskyrocker** [expo/expo#5902]
I'm reading on [this part of the documentation](https://github.com/expo/expo/blob/3e89a67851a818ed96f02933daf728a28ec3c250/docs/pages/versions/v33.0.0/distribution/app-stores.md) and getting some confusion as to whether the link to the full list of keys Expo provides is accurate:

> The full list of keys Expo provides by default can be seen [here](https://github.com/expo/expo/blob/master/exponent-view-template/ios/exponent-view-template/Supporting/Info.plist#L28-L41).

In particular, the key `UIUserInterfaceStyle` is not supported, but it seems that we were able to still set it and get our desired outcome.

And then I found a different supporting list [here](https://github.com/expo/expo/blob/73c4d23244e24edfca24d7a60b6e86557cf7d85b/ios/Exponent/Supporting/Info.plist), which I'm not quite sure what it's for. This one does contain the key we're setting `UIUserInterfaceStyle`, which is why it makes me wonder whether it is the **actual documentation** for the supported keys.

**Comment by cruzach** [comment]
The second list you linked is referencing the Expo Client app, whereas the one linked in the documentation are the defaults provided for your standalone app

**Comment by leoskyrocker** [comment]
Thanks
