### ISSUE TITLE
Autoupdate app on store

### ISSUE THREAD

**Issue by javigodoy** [expo/expo#5903]
Hi!
When i run expo build:android, it autoupdate the app in PlayStore.

-I published an app on the store, for example v.1.0
-Install app v.1.0 from store
-expo build:android of v.2.0
-open playstore installed app (shows v.1.0)
-close app
-open app again (shows v.2.0)
How can i disable this behaviour?

**Comment by raajnadar** [comment]
The same thing happened to me the app got updated automatically without installing update from google play.

Sdk 34 apk

**Comment by javigodoy** [comment]
@raajnadar seems is the normal behaviour 
https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#7-update-your-app

take a look for no autoupdate
https://forums.expo.io/t/how-can-i-generate-an-apk-without-updating-in-store/24172/2

**Comment by raajnadar** [comment]
Does that mean `expo build:android` also runs `expo publish` by default??

**Comment by sjchmiela** [comment]
(Yes it does)

**Comment by cruzach** [comment]
You can pass the `--no-publish` flag to disable automatic publishing before building.
