### ISSUE TITLE
[expo-in-app-purchases] purchaseItemAsync() never resolves on Android

### ISSUE THREAD

**Issue by danmaas** [expo/expo#5918]
## 🐛 Bug Report

On Android, the promise returned by `InAppPurchases.purchaseItemAsync()` never seems to resolve, regardless of whether the Google Play purchase prompt succeeds or is canceled.

This is in a bare build with `expo-in-app-purchases@^7.0.0` that was ejected from Expo SDK 35 and uses `react-native@0.59.10`.

In my reading of [BillingManager.java](https://github.com/expo/expo/blob/f8f9418439aaa0e2d6d55b9a5801c01542a1eaac/packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java#L135), it looks like the promise passed to `purchaseItemAsync()` isn't remembered anywhere that it could later be resolved?

### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @sentry/react-native: ^1.0.7 => 1.0.7 
      @types/expo: ^32.0.0 => 32.0.13 
      @types/react-native: ^0.60.19 => 0.60.19 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
      react-navigation: ^3.13.0 => 3.13.0 

### Steps to Reproduce

In an Android bare-built app, after initializing the InAppPurchase module with `connectAsync()`, `setPurchaseListener()`, and `getProductsAsync()`, attempt a purchase as follows:

`await InAppPurchases.purchaseItemAsync(productId);`

### Expected Behavior

The promise returned by `purchaseItemAsync()` resolves as soon as the Google Play billing UI disappears, regardless of whether the purchase succeeded or not, as [documented](https://docs.expo.io/versions/latest/sdk/in-app-purchases/#inapppurchasespurchaseitemasyncproductid-string-olditem-string).

### Actual Behavior

The Google Play billing UI appears, but after it finishes, the app appears "stuck" because the `purchaseItemAsync()` promise does not resolve.

### Reproducible Demo

(sorry, I can't think of an easy way to create a repro case due to the large size of the Google Play Store infrastructure)

**Comment by OscarYuen** [comment]
Could you get the response from getProductsAsync()?

**Comment by danmaas** [comment]
Hi Oscar - I don't have the exact data handy (I will log it in a future build), but I do know the data returned by `getProductsAsync()` was good for running the purchase flow successfully. In fact, the whole Google Play billing flow works perfectly, if I just call `purchaseItemAsync()` without awaiting the promise it returns :).

My general flow is as follows:

Shortly after app startup:
`await connectAsync()`
`setPurchaseListener()`
`await getProductsAsync()` (the results of this are cached so that we can display purchasable items instantly when the user opens the in-app store)

Later, on purchase request:
`purchaseItemAsync()`...

**Comment by YousefED** [comment]
Any update on this?

> In my reading of BillingManager.java, it looks like the promise passed to purchaseItemAsync() isn't remembered anywhere that it could later be resolved?

Looking at the code I have to agree; I'm evaluating IAP libraries for Android - quite some IAP libs seem to have trouble with handling Promises / Errors correctly, so curious about this before moving to expo for IAP

**Comment by yaroslavnikiforov** [comment]
I have an issue when PurchaseListener doesn't trigger after you successfully purchase a subscription, for example. And you are not able to detect the result of the purchase. It seems like because of the same reason (didn't test on iOS).

**Comment by OscarYuen** [comment]
> I have an issue when PurchaseListener doesn't trigger after you successfully purchase a subscription, for example. And you are not able to detect the result of the purchase. It seems like because of the same reason (didn't test on iOS).

Where did your listener put?  Need to put it globally

**Comment by yaroslavnikiforov** [comment]
I put `setPurchaseListener(callback)` globally in componentDidMount() of the App.js container after calling `connectAsync()`. Here is the piece of code:

`async componentDidMount() {
    try {
      const { responseCode, results, errorCode } = await InAppPurchases.connectAsync()
        
      InAppPurchases.setPurchaseListener(
        ({ responseCode, results, errorCode }) => {
          const { OK, USER_CANCELED, DEFERRED } = InAppPurchases.IAPResponseCode

          switch (responseCode) {
            case OK:
              Promise.all(
                results.map(async purchase => {
                  if (!purchase.acknowledged) {
                    alert(`Successfully purchased ${purchase.productId}`)
                    // Process transaction here and unlock content...
                   
                    // Then when you're done
                    InAppPurchases.finishTransactionAsync(purchase, false)
                  }
                })
              ).catch(err => console.log('err', err))
              break

            case USER_CANCELED:
              alert('User canceled the transaction')
              break

            case DEFERRED:
              alert('User does not have permissions to buy but requested parental approval (iOS only)')
              break

            default:
              alert(`Something went wrong with the purchase. Received errorCode ${errorCode}`)
              break
          }
        }
      )
`

Then when I open subscription screen call `getProductsAsync(productIds)` and `purchaseItemAsync(productId)'. After you successfully subscribe listeners callback doesn't trigger.

![Screenshot_2020-03-17-10-51-56-840_com android vending](https://user-images.githubusercontent.com/42115630/77225871-19220c80-6b7c-11ea-8106-ee6cfd6cd854.jpg)

**Comment by yaroslavnikiforov** [comment]
Also tested on iOS and in this case purchase listener is triggered as expected. So it seems like a bug on Android.

**Comment by simplesthing** [comment]
Also facing this issue, having to write additional code that operates differently for android in which the callback fires an update to app state in a completely different way that iOS, wish I would have found this issue _before_ I completed the iOS path thinking everything was fins with the library and flow.

**Comment by sbrighiu** [comment]
+1

**Comment by ferrannp** [comment]
I have the same problem on Android. When calling `purchaseItemAsync()` if the user does not buy it (cancel the dialog) the promise never resolves.

**Comment by danmaas** [comment]
As a work-around, you can wrap `purchaseItemAsync()` with your own promise, which you can resolve from inside your purchase listener function. Even though `purchaseItemAsync()` won't resolve, you will still get a listener callback.

**Comment by ferrannp** [comment]
So the issue on Android is here:

https://github.com/expo/expo/blob/a84f4cebce2e38d1d4ea8269bcca7035103bef6e/packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java#L134-L153

When you call `purchaseItemAsync`, then it will hit the listener https://github.com/expo/expo/blob/a84f4cebce2e38d1d4ea8269bcca7035103bef6e/packages/expo-in-app-purchases/android/src/main/java/expo/modules/inapppurchases/BillingManager.java#L162-L173 which will send events to JS but it will not resolve any promise.

I have been writing a workaround locally (if somebody reading this is up to using something like `patch-package`) but basically:

```java
// This inside purchaseItemAsync
promises.put(PURCHASE_PRODUCT, promise); // These promises array already exist inside the file mBillingClient.launchBillingFlow(mActivity, purchaseParams);
```

Then:
```java
// This inside onPurchasesUpdated
...
    Promise promise = promises.get(PURCHASE_PRODUCT);
    if (promise != null) {
      promise.resolve(result.getResponseCode());
      promises.remove(PURCHASE_PRODUCT);
    }
  }
```

**Comment by dawntommm** [comment]
any update on this? getting same issue

**Comment by jmoussu** [comment]
Any update on this? getting same issue !
And Play console ask for update to PLay billing 3 before the 1 Nov 2021 ?

**Comment by jamesst20** [comment]
> promise

Did you make a PR ? It would be indeed very nice to get this resolved. It's hard to believe after all this time Expo team havn't looked into it. I find this bug kind of 'major'

**Comment by jinghongchan** [comment]
I'm still experiencing this issue on iOS

**Comment by arcln** [comment]
I am also running into this on `v13.0.0`.

**Comment by kesha-antonov** [comment]
> Happens the same for me on IOS `"expo-in-app-purchases": "13.0.0"`. This is a major blocker to our project. We might consider switching to react-native-iap package.

I advise you to not. We had problems with that package. Switched to this one. And problems gone. Except this one

**Comment by kesha-antonov** [comment]
> As a work-around, you can wrap `purchaseItemAsync()` with code that creates and returns your own promise, which you can then store in a global variable and resolve from inside your purchase listener function. Even though `purchaseItemAsync()` won't resolve, you will still get a listener callback.

this method works for me
