### ISSUE TITLE
[expo-in-app-purchases] connectAsync() causes distracting pop-up on iOS

### ISSUE THREAD

**Issue by danmaas** [expo/expo#5919]
## 🐛 Bug Report

On iOS, when initializing the InAppPurchases module with `connectAsync()`, the `SKPaymentQueue` `restoreCompletedTransactions` method is always called.

This causes a distracting pop-up UI prompt to appear immediately, asking the user for their Apple ID and password.

Since InAppPurchases initialization may take place during critical UI flows, like sign-in or browsing an in-app store, it would be better for `connectAsync()` to operate silently and _not_ cause this UI disruption.

Basically, while `connectAsync()` does what it is documented to do - returns a promise that resolves to a list of past purchases - I question whether this is really a good design for iOS. Many iOS apps offer a special "Restore old purchases" button, which would be a natural place to call `getPurchaseHistoryAsync()` and trigger any necessary pop-up UI.

### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @sentry/react-native: ^1.0.7 => 1.0.7 
      @types/expo: ^32.0.0 => 32.0.13 
      @types/react-native: ^0.60.19 => 0.60.19 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
      react-navigation: ^3.13.0 => 3.13.0 

(This is a bare build with expo-in-app-purchases@^7.0.0 that was ejected from Expo SDK 35 and uses react-native@0.59.10)

### Steps to Reproduce

In an iOS bare-built app:

`await InAppPurchases.connectAsync();`

### Expected Behavior

Nothing appears in the UI.

### Actual Behavior

The app is interrupted by a pop-up prompt for the user's Apple ID and password.

### Reproducible Demo

(sorry, I can't think of an easy way to create a repro case due to the large size of the Apple In-App Purchase infrastructure)

**Comment by OscarYuen** [comment]
It only happens in development and test flight environment. I think it is for sandbox account connection.
In production, the pop up would not show.

**Comment by danmaas** [comment]
Thanks Oscar! I have only been testing sandbox purchases for now, so it's good to hear this will not happen in production. I'll post here if anything changes.
