### ISSUE TITLE
Expo Permissions for Detached Apps

### ISSUE THREAD

**Issue by michaelgiba** [expo/expo#592]
I realize supporting detached apps is not a priority, but for public reference I think it may be helpful to someone to mention that Expo.permissions will only work properly in a detached app if the permissions are properly set in the info.plist of the application. I had an app that used Expo.Permissions with no error but once I detached I began to receive cryptic Xcode errors whenever I requested permissions through that interface.

I assume Expo manages these permissions when attached, it may be helpful to have those permissions copied into the expo project when detached.

Low priority

**Comment by terribleben** [comment]
This is [landed](https://github.com/expo/xdl/commit/2e04946713562393243041f7e611d0dad6d81767) for iOS and will go out next time we release exp.

**Comment by terribleben** [comment]
Continuing to track this as an Android-only ticket.

**Comment by sjchmiela** [comment]
I believe permissions are now configurable on Android too with `expo.android.permissions` key in `app.json`. 🙂
