### ISSUE TITLE
[expo-branch] null is not an object (evaluating RNBranch.STANDARD_EVENT_ADD_TO_CART) in SDK 35

### ISSUE THREAD

**Issue by davidbiller** [expo/expo#5920]
Error: null is not an object (evaluating RNBranch.STANDARD_EVENT_ADD_TO_CART)

`import Branch, { BranchEvent } from "expo-branch";`

and 

`"expo-branch": "~1.0.2",`

in Expo SDK 35.

Just after the import. In iOS Simulator. 

So this Error is still/again there in SDK 35 - check  #5349  too

tried too:
import Branch, { BranchEvent } from "react-native-branch";
"react-native-branch": "~3.1.1",
But same error.

**Comment by cruzach** [comment]
As it says in that issue: 
> nothing has changed when it comes to Expo client — it didn't have Branch and it won't. So, trying to import and/or call any Branch methods in Expo client will raise an error, since RNBranch, i. e. native module, is null in Expo client.

Branch is only available in standalone builds
