### ISSUE TITLE
Archive error IOS in bare expo workflow: library not found for -lReact 

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#5922]
### Environment

Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
      react-navigation: ^3.2.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.1.2

### Steps to Reproduce

I have expo project ejected to bare workflow, when I'm trying to make IOS archive, I'm getting an error: "library not found for -lReact ", in react-native GitHub I got an answer that I need to upgrade react-native to the latest version, so my question is whether or not react-native-unimodules will work with the latest react-native version? or it will support only 0.59.10 version now? 

### Expected Behavior

I can make an archive

### Actual Behavior

I'm getting an error

**Comment by Luckygirlllll** [comment]
Here is my issue opened in react-native Github: https://github.com/facebook/react-native/issues/26785

**Comment by cruzach** [comment]
It's best practice to use the same version of `react-native` that is associated with the most recent Expo SDK release when using unimodules. Not that it definitely won't work with newer versions, but ymmv
