### ISSUE TITLE
[docs] [expo-in-app-purchases] clarify finishTransactionAsync() usage on failed payments

### ISSUE THREAD

**Issue by danmaas** [expo/expo#5927]
I noticed a possible oversight in the documentation for
[InAppPurchases.finishTransactionAsync()](https://docs.expo.io/versions/latest/sdk/in-app-purchases/#inapppurchasesfinishtransactionasyncpurchase-inapppurchase-consumeitem-boolean)

The docs state: "Marks a transaction as completed. This must be called on successful purchases only after you have verified the transaction and unlocked the functionality purchased by the user."

This does not say what I should do in case of an _unsuccessful_ purchase - for example, one whose receipt does not verify with the Google or Apple REST APIs, or a purchase that is marked with a permanent "canceled" status. (e.g. Google API reports `"purchaseState": 1`).

If I don't call `finishTransactionAsync()`, then these failed purchases seem to get stuck in an `acknowledged: false` state, and are eventually cleared or refunded after a long time (hours or days).

This is probably OK for blocking fraudulent/invalid purchases, but I noticed a problematic case with Google Play Billing today: I used the sandbox payment method to make a "slow declined" payment. This eventually puts the payment into a permanently canceled state (`"purchaseState": 1`). However, since we did not "acknowledge" the purchase, it blocks the user from attempting another purchase of the same (consumable) item. (Google seems to block purchases when there's an un-acknowledged purchase of the same productId in its systems). Calling `finishTransactionAsync()` on that purchase fixed the problem, but I felt uneasy because the docs say it should only be used for successful transactions.

Anyway, I wish the documentation for `finishTransactionAsync()` were more specific about what to do with failed/invalid payments. Based on my experiments, it seems like the rule should be something like "do not call `finishTransactionAsync()` for invalid payments, but do call it for permanently failed/canceled payments, to acknowledge that the app understands the payment status, even though no item/unlock was granted to the user".

**Comment by expjess** [comment]
Hey @danmaas - would you be willing to open a PR to take a stab at filling out the extra guidance around unsuccessful purchases?

**Comment by danmaas** [comment]
Ya I wouldn't mind - what file should I be updating? Is it `docs/pages/versions/unversioned/sdk/in-app-purchases.md` ?

Incidentally, I have a couple of questions regarding the roadmap for `expo-in-app-purchases`:
- currently it uses v2.0.0 of the Google Play Billing library on Android; v3.0.0 is now available and it includes a couple of fixes and deprecations (there is a minor API change around how subscription upgrades/downgrades are handled); is anyone working on support for this?
- Also, both Google Play and Apple StoreKit offer a way to attach an (obfuscated for privacy) user ID to purchases. Curious if you have a plan to expose that via the Expo API?

**Comment by victoriaSh** [comment]
@danmaas I see in my stats that there is a lot of users that cannot purchase if they canceled purchase for the first time.

I tried to call `finishTransactionAsync()` on failed purchases but got reports from users who paid for item but didn't get it. It seems that listener with error code called several ms before successful callback. How do you deal with it?

**Comment by danmaas** [comment]
Hi Victoria - are you de-bouncing the purchase flow in the UI? It sounds like there might be multiple overlapping requests, which this SDK does not support. In my code I've "single-threaded" all interaction with the expo-in-app-purchases API to avoid this issue.

Regarding reports from users who paid for the item but didn't get it - can you find out if you actually delivered the item? I believe as long as you deliver the item before calling `finishTransactionAsync()`, then the user should not encounter a situation where they were charged but didn't receive an item. This assumes you are also checking the purchase history on app start-up, to handle any purchases that completed while the app was off-line.

**Comment by victoriaSh** [comment]
Hi Dan,

> are you de-bouncing the purchase flow in the UI? It sounds like there might be multiple overlapping requests, which this SDK does not support. 

No, there are no overlapping requests. There are more than 30sec between purchase requests. All errors has "USER_CANCELED" code and no money was withdrawn according to appstore sales stats and app reviews. Unfortunately I can't reproduce it but my stats shows me that there are 2-3 times more unique users with this error than successful transactions. Most of them tried to purchase several times. It looks suspicious to me. 
<img width="452" alt="Снимок экрана 2021-07-16 в 19 59 07" src="https://user-images.githubusercontent.com/8823284/125983570-b574430a-1a3e-4861-88a3-4f4783322c92.png">

> Regarding reports from users who paid for the item but didn't get it - can you find out if you actually delivered the item? 

I was able to talk to one of these users. His problem was solved by itself after 3-4 hours and countless attempts to purchase and restore. The error was also "USER_CANCELED".
There is the code that caused that error.

```

InAppPurchases.setPurchaseListener(({ responseCode, results, errorCode }) => {
	if (responseCode === InAppPurchases.IAPResponseCode.OK) {
		results.forEach( async (purchase) => {
			if (!purchase.acknowledged) {
				let result = await SubscriptionActions.verifyReceipt(purchase);
				if (result == true){
					InAppPurchases.finishTransactionAsync(purchase, false);
					amplitude.getInstance().logEvent("subscription_success");
					setPurchaseActive();
				} else {
					amplitude.getInstance().logEvent("verify_receipt_error");
					setPurchaseInactive();
				}
			}
		});
	} else {
		let errorType = i18n.t('Purchase.unknown_error');
		let errorCode = "UNKNOWN";
		// there were errorType and errorCode definition
		...
		amplitude.getInstance().logEvent("subscription_error",{code: errorCode});

		setPurchaseInactive();
		// finishing failed transaction
		try{
			results.forEach(async (purchase) => {
				if (!purchase.acknowledged) {
					InAppPurchases.finishTransactionAsync(purchase, true);
				}
			});
		} catch(err) {
			amplitude.getInstance().logEvent("finish_transaction_error",{error: err}); 
		}
		Alert.alert(i18n.t('Purchase.error'), errorType);
       }
});

```



Checking purchase history before every "purchase_click" or app start sounds good. I will try to implement it in release and will come back.

**Comment by danmaas** [comment]
`USER_CANCELED` is extremely common, it's just what happens when the user sees the final confirmation prompt and then decides not to complete the purchase. In my game, probably 60-70% of purchase attempts end with `USER_CANCELED`.

**Comment by saharshsingh** [comment]
> This does not say what I should do in case of an unsuccessful purchase - for example, one whose receipt does not verify with the Google or Apple REST APIs, or a purchase that is marked with a permanent "canceled" status.

@danmaas - did you ever get clarity on this? I am implementing a subscription purchase flow in my app, where on purchase I would like to have my backend activate the subscription. I am not sure how to handle cases like receipt validation failure or even connectivity failure with my API.

**Comment by danmaas** [comment]
If you're just starting out here, I would recommend looking at a wrapper product like https://www.revenuecat.com/ to deal with the complexity.

What I ended up doing was, in case of a non-recoverable receipt validation failure, do call finishTransactionAsync(), but just don't give the user the items purchased. For connectivity failure, the transaction will not enter the "completed" state so it is too early to call finishTransactionAsync(). You should be retrying the purchase history manually on every app start (and ideally every network re-conenction).

**Comment by saharshsingh** [comment]
Thanks for the quick reply @danmaas. Your comment was very helpful.

**Comment by CallumHemsley** [comment]
> This is probably OK for blocking fraudulent/invalid purchases, but I noticed a problematic case with Google Play Billing today: I used the sandbox payment method to make a "slow declined" payment. This eventually puts the payment into a permanently canceled state (`"purchaseState": 1`). However, since we did not "acknowledge" the purchase, it blocks the user from attempting another purchase of the same (consumable) item. (Google seems to block purchases when there's an un-acknowledged purchase of the same productId in its systems). Calling `finishTransactionAsync()` on that purchase fixed the problem, but I felt uneasy because the docs say it should only be used for successful transactions.

Hi @danmaas - How were you able to test using a 'slow declined' payment? My product is a subscription, and I'm not seeing an option for a 'slow declined purchase', only decline or accept 🤔

**Comment by danmaas** [comment]
That option might only be available for one-time purchases.

Based on later learnings, I can confirm that our earlier discussion in the thread is correct. Meaning, you should call `finishTransactionAsync()` as soon as the final outcome of the transaction is known - no matter whether the outcome is success or failure of the payment.
