### ISSUE TITLE
Move expo admob Android ads to Google mobile ads SDK 18.1.0 to support user metrics

### ISSUE THREAD

**Issue by bculley** [expo/expo#5928]
Admob user metrics require Android Google mobile ads SDK 18.1.0 in order to function per Google https://support.google.com/admob/answer/9263723?hl=en-GB

**Comment by AdamJNavarro** [comment]
Hey @bculley,

We prefer to reserve Github issues for reproducible bugs. For feature requests or library upgrade requests, it'd be much appreciated if you could create a post on our [Canny Board](https://expo.canny.io/feature-requests). This way others can also voice their support for the upgrade as well.

Cheers,
Adam
