### ISSUE TITLE
How to hide SQLite folder in iTunes File Sharing?

### ISSUE THREAD

**Issue by lincdh** [expo/expo#5929]
I am using Expo SQLite and it works fine but also my app shares files in the iTunes File Sharing, and the SQLite folder called 'SQLite' also appears there.

So how can i hide the SQLite folder?

**Comment by AdamJNavarro** [comment]
Hey @lincdh,

We prefer to reserve Github issues for reproducible bugs. For questions like this one, could you please create a forum post [here](https://forums.expo.io/c/how-to)?

Thanks,
Adam
