### ISSUE TITLE
IOS 13.1 http get requests network error

### ISSUE THREAD

**Issue by asnewman** [expo/expo#5931]
## 🐛 Bug Report
When doing http (not https) get requests in an iOS 13.1 device using axios, it returns with a network error. Using an iOS 12.2 device, the get request works.

Looking at this https://forums.expo.io/t/how-to-enable-ios-http-requests/1794, it looks like http requests are suppose to work via expo as ATS is disabled.

### Environment
iOS 13.1
Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.0 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.2.3

iOS 13.1

### Steps to Reproduce
Do an axios get request in iOS 13.1.

### Expected Behavior
Resolves

### Actual Behavior
Network error

### Sample Code
https://github.com/asnewman/sample-project

**Comment by AdamJNavarro** [comment]
Hey @asnewman,

Could you please provide a reproducible example of this behavior? By taking the time to create a MCVE, it expedites our ability to investigate and resolve issues.

Cheers,
Adam

**Comment by kevinvugts** [comment]
I've got the same issue. After updating to ios 13 I am receiving network errors, code -1 on http requests

**Comment by asnewman** [comment]
@AdamJNavarro here is a sample repo:
https://github.com/asnewman/sample-project
From my testing, it looks like https://github.com/asnewman/sample-project/blob/fb63f4656a3f68595488945ccff99dfe01971fb2/App.js#L11 is the issue. The reason why it needs to be included can be seen via https://github.com/axios/axios/issues/86.
This error occurs in iOS 13 but not in iOS 12.

**Comment by kevinvugts** [comment]
I've got a fix

Apparently on iOS 13.0 there was a change in how we handle GET requests. 

The answer is in this thread: https://stackoverflow.com/questions/56955595/1103-error-domain-nsurlerrordomain-code-1103-resource-exceeds-maximum-size-i

Instead of using a body on a get request move it too the params. And dynamically add body / data to the request object depending on the method. (not if GET)

**Comment by asnewman** [comment]
Awesome, nice find @kevinvugts !

**Comment by kevinvugts** [comment]
Thanks @asnewman hope I could help some of you guys out!
