### ISSUE TITLE
expo-sharing - can't share file on Android

### ISSUE THREAD

**Issue by Haper** [expo/expo#5933]
## 🐛 Bug Report
I'm trying to share file saved with 'expo-file-system' into documents or cache directory.
It works fine on iOS, but on Android it looks like any selected app can't access the file.

```js
url = 'file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540n0_quarter%252Fhotel-force/filesCache/attachments/6227.pdf';
const options = {
   mimeType: 'application/pdf',
   dialogTitle: 'Open file',
   UTI: 'com.adobe.pdf',
};
Sharing.shareAsync(url, options);
```

### Environment
Expo CLI 3.2.3 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.11.1 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.8 => 4.0.8 
    npmGlobalPackages:
      expo-cli: 3.2.3

Device:
Mi A1, Android 9

Android permissions:
```
"permissions": [
        "CAMERA",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "READ_INTERNAL_STORAGE",
        "WRITE_INTERNAL_STORAGE"
      ]
```

### Expected Behavior
File opened in selected app

### Actual Behavior
PDF Viewer - shows 'File loading error!'
ES File Explorer - saves zero length file

**Comment by AdamJNavarro** [comment]
Hey @Haper,

Could you please create a [Snack](snack.expo.io) that reproduces this behavior so we can test and investigate it on our end?

Cheers,
Adam

**Comment by Haper** [comment]
Sorry, guys. The problem is on the other side.
