### ISSUE TITLE
expo-image-picker not working on Android only

### ISSUE THREAD

**Issue by ian** [expo/expo#5934]
### Environment

  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @bugsnag/expo: ^6.4.0 => 6.4.0
      expo: ^34.0.1 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.0.9

### Steps to Reproduce

Add an `await ImagePicker.launchImageLibraryAsync` on Android and it will fail to return after picking an image.

Note - this happens on `ImagePicker.launchCameraAsync` as well

### Expected Behavior

Expected permissions to be granted and then `Picker Result` to output the selected file after chosen.  

### Actual Behavior

The picker opens, file is selected, then no response as a return from the await ImagePicker.launchImageLibraryAsync.

Per the example below, the output ends after the permissions output: 

```
Permissions: Object {
  "expires": "never",
  "permissions": Object {
    "camera": Object {
      "expires": "never",
      "status": "granted",
    },
    "cameraRoll": Object {
      "expires": "never",
      "status": "granted",
    },
  },
  "status": "granted",
}
```

### Reproducible Demo

Here's the code that I'm running:
```
handlePickImage = async () => {
    try {
      const res = await Permissions.askAsync(
        Permissions.CAMERA,
        Permissions.CAMERA_ROLL
      )
      console.log("Permissions:", res)

      let result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.All,
        allowsEditing: false,
        aspect: [4, 3]
      })

      console.log("Picker Result", result)

      if (!result.cancelled) {
        const { session } = this.props
        this.handleSend([
          {
            _id: Math.random(),
            user: { _id: session.user.id },
            image: result.uri
          }
        ])
      }
    } catch (err) {
      console.log("ERR", err)
    }
  }
```

Add a button anywhere that has an `onPress={this.handlePickImage}`

**Comment by lukmccall** [comment]
There aren't any callback. Information about photos you selected goes to console. If you are using a snack, you can check them in `Logs` sections on the bottom of the page. 
You should get something like this:
<img width="1114" alt="Screenshot 2019-10-10 at 15 47 37" src="https://user-images.githubusercontent.com/9578601/66574899-57e77b80-eb75-11e9-9741-8e9418a64023.png">

Also, I added to my demo alert box which shows you information about the selected image.

**Comment by ian** [comment]
Not sure how to pull up remote debugging on a snack-loaded Expo project.  





On Thu, Oct 10, 2019 1:50 PM, Łukasz Kosmaty notifications@github.com  wrote:
There aren't any callback. Information about photos you selected goes to
console. If you are using a snack, you can check them in Logs  sections on the
bottom of the page.
You should get something like this:


Also, I added to my demo alert box which shows you information about the
selected image.

**Comment by ian** [comment]
Ah, I see you added an alert.  It's showing the picked file for me with
cancelled = false, so I'm unsure what's different about my code since it works
fine on iOS.







On Thu, Oct 10, 2019 1:50 PM, Łukasz Kosmaty notifications@github.com  wrote:
There aren't any callback. Information about photos you selected goes to
console. If you are using a snack, you can check them in Logs  sections on the
bottom of the page.
You should get something like this:


Also, I added to my demo alert box which shows you information about the
selected image.

**Comment by ian** [comment]
Thanks for your help @lukmccall, it seems to be an issue on my side.  Closing until it happens again in a more reproducible way.

**Comment by lc3t35** [comment]
Reopening this issue ...

If you look closer with the snack (updated with SDK35), you will notice that there is a blue "Updating..." banner at the top after you select the image and when it displays the alert, that means the app is reloaded or crashes.

I have the same behaviour with my app, monitoring AppState, when you launch the ImagePicker
` DEBUG _handleAppStateChange current appState : active, nextAppState : background`

**Comment by lc3t35** [comment]
@lukmccall can you please test the reproducible snack ?

**Comment by lukmccall** [comment]
Hi, I've checked your demo. You're right - something seems to be wrong. I'll try to investigate it.
 However, please open a new issue.

**Comment by lukmccall** [comment]
I've double-checked it. I don't think this is a bug.
To launch the system image-picker we need to background the application.
So what you see it's correct behaviour.

**Comment by lc3t35** [comment]
The problem is that in my expo sdk35 app, it needs two clicks to select the image with image picker on Android, it works fine on iOS.

**Comment by lukmccall** [comment]
Do you mean that the image picker show twice?

**Comment by lc3t35** [comment]
No the image picker shows once on screen, but when you click the first time, it seems you put it in the foreground, then you have to pick again the image you want to choose ?

**Comment by lukmccall** [comment]
Could you open the new issue? It'll be easy to track it.

**Comment by petr166** [comment]
I have the same issue using `expo-image-picker@8.0.2` and `react-native-unimodules@0.7.0`. I'm trying to select a video  and the promise of `launchImageLibraryAsync()` is never resolved (or any error thrown). 

Simulator: `Pixel_3_API_29 - Google Pixel 3 with Android 10`
This issue happens if i try to select a video recorded in the simulator, from Google Photos app (the default photos app on Pixel). I have tested with downloaded videos and it works fine.
Running the simulator attached to Android Studio produces this log:

```
2020-02-12 17:00:56.258 32522-371/com.myapp W/ContentResolver: Failed to get type for: content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F35/ORIGINAL/NONE/1271397717 (Invalid column latitude)
2020-02-12 17:00:56.298 32522-371/com.myapp W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
2020-02-12 17:00:56.298 32522-371/com.myapp W/System.err:     at expo.modules.imagepicker.ImagePickerModule$1.run(ImagePickerModule.java:437)
2020-02-12 17:00:56.298 32522-371/com.myapp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2020-02-12 17:00:56.298 32522-371/com.myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-02-12 17:00:56.298 32522-371/com.myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-02-12 17:00:56.298 32522-371/com.myapp W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

It seems to be related to the `uri` the system returns to picker lib not including a file extension?
Please reopen @lukmccall 

My setup:
```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 29.88 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.2, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by lukmccall** [comment]
Hi @petr166, please open a new ticket for your issue. It's not connected with this one.

**Comment by MattGrouchy** [comment]
I noticed in the code of the first comment that mediaTypes is set to all. The documentation says this Enum is compatible with IOS, it doesn't mention android.
[https://docs.expo.io/versions/latest/sdk/imagepicker/#imagepickermediatypeoptions](url)
