### ISSUE TITLE
Deep link url `null` on Android and causes Expo error on iOS

### ISSUE THREAD

**Issue by xavier-villelegier** [expo/expo#594]
Hey,

I'm trying to use deep links on iOS and Android on a **detached** app.
My `scheme` is `piu`, and I get the url like this:
```js
const handleIncomingURL = ({ url }) => {
  console.log("url: ", url)
  return url
}
Linking.addEventListener('url', handleIncomingURL)
Linking.getInitialURL()
  .then(url => handleIncomingURL({ url }))
  .catch(error => console.error('Error trying to retreive initial URL', error))
```

### On iOS
When I open Safari and go to `piu://test`:

**When the app is closed**: I receive `exp://test` as the URL. (Why not `piu://test` ?)
**When the app is in background**: Expo handles the link and I get this error:
![simulator screen shot 5 sept 2017 a 11 39 24](https://user-images.githubusercontent.com/17592779/30056010-82581afe-9231-11e7-8b2c-e66b14e880bd.png)

### On Android
The `url` is always `null`. I've tried two ways to open the deep link:

**Through Android Studio**:
<img width="600" alt="capture d ecran 2017-09-05 a 12 00 50" src="https://user-images.githubusercontent.com/17592779/30056147-f718291a-9231-11e7-8e3c-8372683cacfe.png">

**Through the command line**:
```
adb shell am start -W -a "android.intent.action.VIEW" -d "piu://test" com.productinuse.demo
```

As my application is detached, did I miss something ?

**Comment by terribleben** [comment]
What is the value of `Constants.linkingUri` ?

**Comment by xavier-villelegier** [comment]
@terribleben 
### On Android
When I run `react-native run-android`, the `linkingUri` is `exp://10.42.0.95:19000/+`

### On iOS
When I run `react-native run-ios`, the `linkingUri` is `exp://+`

**Comment by terribleben** [comment]
Can you try this again with SDK 27 (or higher if you read this later)? Be sure to follow the upgrade instructions for each version. We updated how we compute deep links in SDK 27+.

Also, starting in SDK 27, if you have a generated ExpoKit scheme like `exp12345` in your `Info.plist`, you can delete that one in favor of just your custom scheme like `piu`. You only need one.

**Comment by terribleben** [comment]
Closing because I believe this was fixed in SDK 27 and haven't heard more in the last month.

**Comment by xavier-villelegier** [comment]
Sorry @terribleben, I missed the notification. I'm not in the company where we had this issue anymore, so I can't test that, but looking at the nice enhencements you did on the linking I guess this is solved. Cheers ✌️
