### ISSUE TITLE
High CPU Usage after ctrl-c in the terminal

### ISSUE THREAD

**Issue by mzgnr** [expo/expo#5948]
### Environment

  Expo CLI 3.3.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.11.1 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.5
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.3.0

### Steps to Reproduce

npm run start
open application in iOS simulator
ctrl-c in the terminal while simulator is open

### Expected Behavior
Should not increase CPU usage

### Actual Behavior
High CPU Usage

### Reproducible Demo
<img width="586" alt="Screen Shot 2019-10-11 at 15 54 46" src="https://user-images.githubusercontent.com/6003317/66653164-1243b500-ec40-11e9-8bb8-b93c4ec781f5.png">

**Comment by cruzach** [comment]
Hi! thanks for the screen shot, but I wasn't able to reproduce this on my end. Max CPU usage for `Exponent` was 10% (and that was on startup, not quitting the sim). Only difference is Xcode versions, but just to make sure- can you run this on a blank `expo init` project and confirm the same behavior?

**Comment by mzgnr** [comment]
@cruzach Sorry, I changed the issue, to reproduce, cancel the command in the terminal with ctrl-c combination

**Comment by alitsvin** [comment]
Faced that too
