### ISSUE TITLE
[expo-contacts] getContactsAsync hangs on iOS 13

### ISSUE THREAD

**Issue by Audace** [expo/expo#5949]
### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.1.10 
      expo: ^34.0.1 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
      react-navigation: ^3.0.9 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9
```

We're running Standalone.

### Steps to Reproduce

1. Request permission to contacts

    `Permissions.getAsync(Permissions.CONTACTS)`

2. Grab non-image fields

    ```
    export const nonImageFields = Object.values(Contacts.Fields).filter(
      field =>
        field !== Contacts.Fields.Image && field !== Contacts.Fields.RawImage,
    )
    ```

3. Fetch contacts async
    `const { data: allContacts } = await Contacts.getContactsAsync({fields: nonImageFields,})`

### Expected Behavior

At some point, the async function will return, meaning a log statement the line below would fire and the allContacts list would be populated (assuming > 0 contacts).

### Actual Behavior

The async function hangs indefinitely. The log statement on the next line is never fired, moreover no line below is ever executed as it's still awaiting `getContactsAsync`.

### Notes

If I only fetch `"emails"` as a field it works fine. This makes me think that some fields no longer work in iOS 13.

**Comment by Audace** [comment]
Turns out that the `Note` field causes this to hang. It may be related to updates to permissions / privacy with iOS 13.

I appended the `nonImageFields` function to do the following:
```
export const nonImageFields = Object.values(Contacts.Fields).filter(
  field =>
    field !== Contacts.Fields.Image && field !== Contacts.Fields.RawImage && field !== Contacts.Fields.Note,
)
```

**Comment by Audace** [comment]
Would it be reasonable for Expo to update the `expo-contacts` documentation with a warning around this? Additionally, is there any idea _why_ this is happening?

**Comment by lukmccall** [comment]
Hi @Audace, I've tried to investigate your problem. It seems to occur because of the privacy update. Now, when you want to get note `field`, you have to add a new entitlement - `com.apple.developer.contacts.notes`. You can read more [here](https://stackoverflow.com/questions/57442114/ios-13-cncontacts-no-longer-working-to-retrieve-all-contacts) or [here](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_contacts_notes?language=objc).

I'll update the `expo-contacts` documentation, but first I want to consult this with Expo team.
