### ISSUE TITLE
Could not find host.exp.exponent:expoview:20.0.0 with detached project

### ISSUE THREAD

**Issue by tiendv89** [expo/expo#595]
Hello,

I have a detached project and when I try to build standalone Android app, I got the issue below:

`* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find host.exp.exponent:expoview:20.0.0.
     Searched in the following locations:
         file:/C:/Users/Teko/.m2/repository/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.pom
         file:/C:/Users/Teko/.m2/repository/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.aar
         https://jcenter.bintray.com/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.pom
         https://jcenter.bintray.com/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.aar
         file:/D:/Projects/others/winvestor/.expo-source/android/maven/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.pom
         file:/D:/Projects/others/winvestor/.expo-source/android/maven/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.aar
         file:/D:/Projects/others/winvestor/android/app/libs/expoview-20.0.0.aar
         file:/D:/Projects/others/winvestor/android/app/libs/expoview.aar
         https://maven.fabric.io/public/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.pom
         https://maven.fabric.io/public/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.aar
         file:/C:/Users/Teko/AppData/Local/Android/Sdk/extras/android/m2repository/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.pom
         file:/C:/Users/Teko/AppData/Local/Android/Sdk/extras/android/m2repository/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.aar
         file:/C:/Users/Teko/AppData/Local/Android/Sdk/extras/google/m2repository/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.pom
         file:/C:/Users/Teko/AppData/Local/Android/Sdk/extras/google/m2repository/host/exp/exponent/expoview/20.0.0/expoview-20.0.0.aar
     Required by:
         android:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

**Comment by beeant** [comment]
just ran into the same problem. I believe you have to do:
https://docs.expo.io/versions/latest/guides/expokit.html check out the upgrade section

**Comment by He1nr1chK** [comment]
Hi @tiendv89 I don't know whether you were successful but I thought I might just as well share my solution seeing as the version of my ExpoKit wasn't the source of my problem. I accidentally upgraded my build tools in Android Studio. Thus I deleted and reinstalled Android Studio and changed this line in android/app/build.gradle: `implementation('host.exp.exponent:expoview:30.0.0@aar') {` to `compile('host.exp.exponent:expoview:30.0.0@aar') {`
