### ISSUE TITLE
Getting build error when using expo-sms module for bare RN project

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#5950]
**React native verison: 0.59.3**
**expo-sms: "6.0.0"** , also tested with latest version got same error
**react-native-unimodules": "^0.4.2"**
**target: android**

```
/node_modules/expo-sms/android/src/main/java/expo/modules/sms/SMSModule.java:45:
 error: method does not override or implement a method from a supertype
  @Override
  ^
2 errors
```

Same error is showing up for line 37.

I also tried:
1-**yarn cache clean**
2-**./gradlew clean**
3- I removed override from line 37 and 45 and my app build was successful.

Here is better explanation of why I removed @override .
https://stackoverflow.com/questions/32217737/method-does-not-override-or-implement-a-method-from-a-supertype-for-override

If this is the bug with **expo-sms** I will send PR. I am not sure whether it's only me who is getting this error or others too.

**Comment by cruzach** [comment]
What version of `expo-sms`, and what version of `react-native`? If you can fill out the entire issue template, that would be very helpful

**Comment by shubhamdeol** [comment]
@cruzach  I have updated the issue description with version information.

**Comment by nico-bellante** [comment]
I am also getting this error:
```
    "react-native-unimodules": "^0.4.0",
    "expo-sms": "^7.0.0",
    "react-native": "0.61.3",
```

**Comment by cruzach** [comment]
@nico-bellante looks like you're using an older version of RN unimodules, and an incompatible version of `react-native`. You should usually keep the same version of `react-native` installed on your bare project as we use in the most recent SDK (as of right now, RN0.59). However, we are released SDK 36 soon with support for RN 0.61, so stay tuned, we're just a couple weeks away most likely)

Can either of you try this on a blank `expo init` bare project, after running `expo install expo-sms`? That way we know the dependencies all line up correctly

**Comment by nico-bellante** [comment]
hey @cruzach thanks for the quick response. 

after much trial and error, i was able to get this to work by upgrading a TON of packages, namely:

all of these to 7.0
```
    "expo-asset": "7.0.0",
    "expo-constants": "7.0.0",
    "expo-contacts": "7.0.0",
    "expo-font": "7.0.0",
    "expo-haptics": "7.0.0",
    "expo-image-picker": "^7.0.0",
    "expo-linear-gradient": "7.0.0",
    "expo-location": "7.0.0",
    "expo-permissions": "7.0.0",
    "expo-sms": "^7.0.0",
    "expo-task-manager": "7.0.0"
```
and 
```
    "react-native-unimodules": "0.6.0",
```

**Comment by cruzach** [comment]
Nice! Glad you resolved it

When installing packages you can use `expo install [package-name]` and it will automatically install the appropriate version for your SDK. When you upgrade SDKs, you can run `expo upgrade` and it'll also upgrade those packages for you 👍
