### ISSUE TITLE
When should I submit a new build / how much OTA is OK with Apple? 

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#5954]
Hey guys, I just got accepted to the App Store with an app based on Expo. The Expo tools were amazing and allowed me to have a really straightforward development process. Cheers for that!

I do have one uncertainty tho: 

After the initial release, I fixed the first batch of bugs that showed up right away, and quickly published my JS bundle over-the-air to my app's release channel. Worked great. Now, I just fixed another critical one, and was thinking of just doing the same thing again.

But is it ok? Can I just keep updating my app OTA forever? (of course, considering no native changes)

The Expo docs as well as Apple's guidelines are vague at best...

Has anyone had any issues with Apple for changing their app too much via OTA? Thanks.

**Comment by cruzach** [comment]
Hi! As long as the changes your are trying to make aren't in [this list](https://docs.expo.io/versions/latest/workflow/publishing/#some-native-configuration-cant-be-updated-by), you are absolutely fine updating your app via OTA updates.

If there were a problem with OTA, it would've been flagged during the app review process.

As for when you should submit a new build, I recommend doing so at least every Expo SDK release, which you can stay on top of via [our blog](https://blog.expo.io/). Or if you need to change anything else on that list I linked, then you'll need to submit a new build.

**Comment by iuliuvisovan** [comment]
So you're saying Apple should be fine with me adding any amount of new functionalities without any of it ever going through the App Store?

**Comment by cruzach** [comment]
Well I can't speak for Apple, but as long as any new functionalities abide by Apple's [guidelines](https://developer.apple.com/app-store/review/guidelines/), I can't see why they would have any problem with it
