### ISSUE TITLE
[iOS] Location.(reverse)GeocodeAsync sometimes never rejects/resolves 

### ISSUE THREAD

**Issue by mskg** [expo/expo#5955]
### Environment

 Expo CLI 3.3.0 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.1.0 - /var/folders/s_/nmlwk9l54pzb7056qvn4j4680000gn/T/yarn--1570974053576-0.4029103391940123/node
      Yarn: 1.17.3 - /var/folders/s_/nmlwk9l54pzb7056qvn4j4680000gn/T/yarn--1570974053576-0.4029103391940123/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.9 => 32.0.13 
      @types/react: ^16.8.6 => 16.9.5 
      @types/react-native: ^0.57.38 => 0.57.65 
      @types/react-navigation: ^3.0.4 => 3.0.8 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.6 => 4.0.10 

### Steps to Reproduce
N/A see "Actual Behavior".

### Expected Behavior
The call to `geocodeAsync`, `reverseGeocodeAsync` should reject immediately if the `AppState` is `background` and the `Platform`, `ios`.

### Actual Behavior
Method call(s) blocks the JS thread indefinitely. 

The `EXLocation` implementation checks the AppState but does not reject/resolve the JS promise in case the App is in background state (https://github.com/expo/expo/blob/8741cda545ba50e2a93d0f5ec886237cd3e12bb1/packages/expo-location/ios/EXLocation/EXLocation.m#L244).

I quickly scanned through some other modules and they always reject/resolve in all code paths. 

Is the implemented behavior correct? If yes, please just close the issue right away.

### Reproducible Demo
N/A see "Actual Behavior"

**Comment by Kolyunya** [comment]
I see this behavior on Android when I make multiple (2+) requests during a short time span (couple of seconds).
