### ISSUE TITLE
Android - Map continue to animate when I'm zooming

### ISSUE THREAD

**Issue by quentinncl** [expo/expo#5956]
### Environment

```bash
Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: ^16.8.6 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-native-maps: ^0.25.0,
```

### Target
Android

### Steps to Reproduce

When I am zooming on the map, if I zoom too far, the map starts to animate itself and starts to descend slowly. The behavior is the same if I dragged the map down.

### Expected Behavior

I would like to, when I zoom to the max, the map don't move and I would like to store the new region.

### Already tried
- Remove `onRegionChangeComplete` : I have the expected behavior but I don't store the location.
- Change `onRegionChangeComplete` to `onRegionChange` : the map is shaking and I can't move.

### Reproducible Demo

I created a snack [here](https://snack.expo.io/@quentinncl/f1e354)

**Comment by cruzach** [comment]
Just to rule out this being an upstream `react-native-maps` issue, can you try this on a bare react native app?

**Comment by quentinncl** [comment]
Hi @cruzach ! Thanks for watching ! 

I tried on a bare react native app (without `expo`) and I have also this issue. does it mean that the issue came from `react-native-maps` directly ?

**Comment by cruzach** [comment]
Most likely, yes. Thanks for taking the time to check that! I'm going to close this for now

I suggest searching for a similar issue on the [react-native-maps repo](https://github.com/react-native-community/react-native-maps/issues)
