### ISSUE TITLE
when using expo,react-native-webview throws an error  

### ISSUE THREAD

**Issue by GuvanchBayryyyev** [expo/expo#5958]
The error is: Invariant Violation: Native component for "RNCWebView does not exist"
##########################
As I know, there are two options for displaying web contents 
1. import {WebView} from "react-native-webview"
2. import {WebView} from "react-native"
I am using expo for my react-native project
So, there are some bugs/errors I got 
For the 1st option, I got error--> Invariant Violation: Native component for "RNCWebView does not exist"
For the 2nd option, I got no error but instead of showing url, it shows me white page which shows nothing 
I tried many solutions from GitHub and StackOverflow but doesn't work
Any new idea?

**Comment by raajnadar** [comment]
`import WebView from 'react-native-webview'`

**Comment by cruzach** [comment]
Hi! I believe [this issue](https://github.com/expo/expo/issues/5864) will answer your questions.
In short- we had to remove the `WebView` implementation from `react-native` that used `UIWebView`. Best option is to replace with `@react-native-community/webview`

**Comment by jm4r7in** [comment]
> Hi! I believe [this issue](https://github.com/expo/expo/issues/5864) will answer your questions.
> In short- we had to remove the `WebView` implementation from `react-native` that used `UIWebView`. Best option is to replace with `@react-native-community/webview`

Hi!
What exactly are we supposed to replace with `@react-native-community/webview` ?
Thank you!
