### ISSUE TITLE
which  module in expo SDK (like MapView, PushNotification, Location, ..) needs access to the expo server?

### ISSUE THREAD

**Issue by derakhshanfar** [expo/expo#596]
for some reason my App doesn't have access to expo server (https://expo.io/) after publishing.
which module in expo SDK (like MapView, PushNotification, Location, ..) needs access to the expo server?

Thanks in advance

**Comment by jimmylee** [comment]
Hey @derakhshanfar thanks for writing in, do you mean publishing to the app store?

**Comment by derakhshanfar** [comment]
Hey @jimmylee .. yes after publishing on app store.. do i need a access to expo server?(https://expo.io/)

**Comment by ide** [comment]
If you use the Expo push notification service (the tokens from getExpoPushTokenAsync), those go through Expo servers. MapView and Location use Apple and Google's servers directly.

**Comment by derakhshanfar** [comment]
@ide thanks a lot for answer but i don't use push notification in my App and when i want to run my app in developing mode it has error (undefined is not an object (evaluating m.getExponentPushTokenAsync) ) because i think expo needs to access https://expo.io/ in bootstrap.. please see this link https://github.com/expo/expo/issues/379.  so if i don't use a push notification after publishing in app store do i have any problem?

**Comment by ide** [comment]
The method is getExpoPushTokenAsync, not getExponentPushTokenAsync. The latter is an old method that we deprecated and then later removed.

Expo also does need access to the Expo servers to load the JS bundle and images. If you can't access Expo servers at all then you should to check your firewall configuration. The Expo servers are hosted by Google Cloud and AWS, nothing out of the ordinary.

**Comment by derakhshanfar** [comment]
ok thanks a lot @ide, i have access to expo servers while i'm developing but after publish my app on store because of some reason i don't have access to expo.. in this case can i use expo in my app?

**Comment by derakhshanfar** [comment]
@ide i live in iran and unfortunately  because of sanction we can't access to expo server without VPN. i can use VPN when i'm developing but after publishing my App on store my customers can't use VPN.. as you say Expo need access to the Expo servers to load the JS bundle and images that's and this is after publishing. that's why i can't use expo in my react app. do you have any solution?

**Comment by ide** [comment]
You could still use Expo to build your standalone apps since we embed the JS bundle in the app, but you won't be able to load updates to your project or load images (you will have to host images yourself).

**Comment by derakhshanfar** [comment]
@ide ok thanks a lot
