### ISSUE TITLE
Can we add getSupportedRatiosAsync to Camera and not in ref

### ISSUE THREAD

**Issue by kangbb** [expo/expo#5962]
As we can see in the Doc:
> `getSupportedRatiosAsync`
> Android only. Get aspect ratios that are supported by the device and can be passed via ratio prop.

But `ratio` is also a prop for `Camera`. So we must get the `ref`, get the support ratio, and then pass to `Camera` with `ratio` prop.  Actually, we usually use the branch structure with `Camera` page, which is useful to get Permission before rendering the component. So we can't get the `ref` in `componentDidMount`.

I think it's necessary to  migrate the `getSupportedRatiosAsync` from `ref` to `Camera`.

**Comment by zanona** [comment]
By the docs, I had no idea `getSupportedRatiosAsync` was only accessible through the `Camera` ref. It looked like a static method just as `Camera.requestPermissionsAsync`. It would be nice to have this documented. :)
