### ISSUE TITLE
[docs] Link to "/workflow/linking" from "sdk/linking/" so guide is easy to find

### ISSUE THREAD

**Issue by RomanovYurii** [expo/expo#5964]
`Linking.parseInitialURLAsync()` doesn't react on the app being focused with deep link. Opening with deep link works fine

Is it supposed to be so, or it is an issue?

**Comment by mskg** [comment]
Yes: https://docs.expo.io/versions/latest/workflow/linking/#handling-links-into-your-app

**Comment by RomanovYurii** [comment]
Nice. Maybe anyone may add this point to [https://docs.expo.io/versions/latest/sdk/linking/]() ?
This is not really obvious one, tbh :)

**Comment by RomanovYurii** [comment]
Thank you, @mskg anyways :)
