### ISSUE TITLE
drawer overlaps with StatusBar on ios

### ISSUE THREAD

**Issue by Hayko1994** [expo/expo#597]
<img width="322" alt="bug" src="https://user-images.githubusercontent.com/22639899/30078292-d0183218-928d-11e7-9487-d56e2d7a32a2.png">

On android, drawer works perfectly and status bar looks like good. While on ios it overlaps. How can it be solved? I am using expo and tried all in their documentation still the same issue I see on the simulator.

**Comment by nirpeled** [comment]
+1 happens to me as well

**Comment by dikaiosune** [comment]
Are you talking about the top of your app? Generally if you don't want to render underneath the status bar you should make sure to use https://docs.expo.io/versions/latest/sdk/constants.html#expoconstantsstatusbarheight and pad the top of your view.

**Comment by Hayko1994** [comment]
I did it but in ios still, the same trouble exists.

**Comment by terribleben** [comment]
Hi, this sounds like an issue with the way you're styling your component. We're hoping to limit github to expo bug reports - feel free to open a discussion on the [forums](https://forums.expo.io).
