### ISSUE TITLE
[android] [build] Expo build gives 47Mb apk on empty project

### ISSUE THREAD

**Issue by google-master** [expo/expo#5974]
## 🐛 Expo build gives 47Mb apk on empty project

Why v35.0.0 `expo build:android` on empty project gives 47Mb apk instead of 29Mb of v33.0 version?

### 35.0.0

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v8.9.4/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.0.10

### Steps to Reproduce

`expo init`
`expo build:android`

### Expected Behavior

apk size ~ 30Mb

### Actual Behavior

apk size ~ 47Mb

**Comment by raajnadar** [comment]
Upload it to Appstore it will be 26mb

**Comment by google-master** [comment]
I made app and uploaded it to Google Play. 47Mb it’s kind of a bit too much for minimal size of apk.

**Comment by raajnadar** [comment]
Make sure you are uploading the app bundle `.aab` and not `.apk`

**Comment by google-master** [comment]
I tried to make .aab by 'expo build:android -t app-bundle’ but .aab size is almost 49Mb on empty project. I’ll check the size of this .aab on Google Play after submitting.

**Comment by cruzach** [comment]
The AAB might be larger, but when the phone installs the app, Google Play will generate the APK for that specific device, which will be smaller.

**Comment by cruzach** [comment]
Closing this since we keep Github for bug reports, and there are many other forum posts and github issues you can read through ([like this one](https://github.com/expo/expo/issues/5830)) where we talk more about the reasons behind binary size.
