### ISSUE TITLE
AuthSession - Automatically closes browser tab the moment you leave the tab.

### ISSUE THREAD

**Issue by Cartas** [expo/expo#5975]
### Environment

```
  Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react: ^5.2.1 => 5.2.1
      @testing-library/react: ^9.2.0 => 9.2.0
```

This issue occurs on Android!

### Steps to Reproduce

Quite simply, use `AuthSession.startAsync`. After the Expo page opens in a Chrome tab, navigate to another app (which would occur in an example where authentication requires some 2FA via another app).

### Expected Behaviour

The opened tab remains open.

### Actual Behaviour

The tab will instantly close of its own accord.

### Reproducible Demo

Here is an incredibly simple demo:  https://snack.expo.io/ryTX3UXFr

Try it on Android, go to the app switcher and you'll see that the browser tab will close.  This seems related to https://github.com/expo/expo/issues/5422, which was seemingly solved with this change:  https://github.com/expo/expo/pull/5442.  This only solves the issue for `WebBrowser`,  and not for `AuthSession`.

**Comment by FlooCharm** [comment]
Run into the same issue, @Cartas could you find a solution for this?

**Comment by Cartas** [comment]
@FlooCharm The solution for now is to basically copy the URL that `AuthSession` is generating, and use that with `WebBrowser.openBrowserAsync` with `showInRecents: true`.

**Comment by FlooCharm** [comment]
@FlooCharm Thanks for the quick reply! I'll give it a try to see if it works as expected
