### ISSUE TITLE
[iOS] Request main thread in EXDocumentPickerModule 

### ISSUE THREAD

**Issue by mrgerych** [expo/expo#5979]
### Environment

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: 3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.0.10
### Steps to Reproduce

DocumentPicker.getDocumentAsync on iOS 13

### Expected Behavior

Opened Document picker

### Actual Behavior

rejected with reason 
`DocumentPicker requires the iCloud entitlement. If you are using ExpoKit, you need to add this capability to your App Id. See https://docs.expo.io/versions/latest/expokit/advanced-expokit-topics#using-documentpicker for more info.`

but actual error is 

`Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.`

**Comment by mrgerych** [comment]
My solution is
https://github.com/expo/expo/pull/5980

**Comment by rodriguezmanu** [comment]
+1

**Comment by sjchmiela** [comment]
Fixed by https://github.com/expo/expo/commit/9898c618ca42e8a1951a9616c0b969677ab74cda in SDK 35.
