### ISSUE TITLE
[Android] Async storage item retrieval takes a while

### ISSUE THREAD

**Issue by agilesrivas** [expo/expo#5981]
### Environment
 SDK Expo : 33.0.0
 React-Native : https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz
 Device : Samsung Galaxy S7 y Iphone 6s
 Platform : iOS/Android

 Version de Android S7 : 8.0.0 

 **Output expo diagnostic**
 Expo CLI 3.3.0 environment info:
 System: OS: Windows 10
 Binaries:npm: 6.12.0 
 IDEs:Android Studio: Version  3.2.0.0 
### Steps to Reproduce

When I initialize the application or use it for the first time to obtain a variable 'x' from storage while this action is being processed, a loading is shown on the screen. When the get item takes about a few seconds, it becomes annoying to see it charging so long, but this only happens sometimes
In iOS this does not happen the get item is resolved quickly

1. Save a value in storage
2. Then I should go get that value
` const example=await AsyncStorage.getItem("example");`
3.In some tests this should take longer than usual.
 
I'm facing this problem specifically in Samsung Phones, for example a Galaxy S7 SM-g930F. This happens when developing and in production app.

Also, if I store more values, the first that i obtain is the one slow, the rest are very fast.

**Cases**

1: Open the application works correctly
2: I close the application and open it again get item delay

3: Open the application and get item does not work properly
4: I close the application and open again and get item works correctly

### Expected Behavior
Currently on Android when you start the application you get a value of async storage which takes a long time but sometimes returns it as it should, any ideas?

In iOS this does not happen.

### Actual Behavior
Currently in ios it works correctly but in Android you must open the application and when obtaining a storage value this takes a few seconds longer than normal

### Reproducible Demo
Snack : [https://snack.expo.io/@alekano/async-storage](https://snack.expo.io/@alekano/async-storage)

It would be best to test the environment in a non-reproducible project that can best see the problem

**Comment by cruzach** [comment]
Are you seeing this behavior when running your project in the Expo Client app, or as a standalone build? I'd also be curious if the same long wait occurs in a bare RN app (you can test this by initializing a bare project with `expo init -t bare-minimum`

**Comment by Alekano** [comment]
Any idea why this behavior?

**Comment by cruzach** [comment]
Not yet. Might be worthwhile to try and go through the device logs during the asyncStorage retrieval and try to garner some information from that
