### ISSUE TITLE
Update Android code transformer (gulp android-update-rn) so it generates correct error handling code

### ISSUE THREAD

**Issue by ide** [expo/expo#5985]
Due to changes in RN 0.61, the transformer no longer generates the correct error-handling code for Android.

The class is src/main/java/com/facebook/react/modules/core/ExceptionsManagerModule.java. We need to update the transformer so that it makes `reportException` do the right thing for the Expo client, and also update the code generated for the deprecated exception methods like  `reportFatalException` and `reportSoftException`.

**Comment by esamelson** [comment]
Closed in #6062 (thanks @tsapeta !)
