### ISSUE TITLE
Get bare-expo compiling and running for Android

### ISSUE THREAD

**Issue by ide** [expo/expo#5987]
bare-expo is not compiling for Android because both our copy of RN and RNGH define UIManagerReanimatedHelper. We need to tell Gradle to exclude the copy in RNGH.

Repro: cd into `react-native-lab/react-native`, run `./gradlew :ReactAndroid:installArchives` (this takes time), cd into `bare-expo/android`, run `./gradlew assemble`.

Error:
```
Execution failed for task ':app:transformDexArchiveWithDexMergerForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.facebook.react.uimanager.UIManagerReanimatedHelper
```

**Comment by tsapeta** [comment]
@ide Do we need to define our own `UIManagerReanimatedHelper` in react-native fork? Looks like they are the same, so maybe removing it from the fork would help?
