### ISSUE TITLE
Re-enable development tools for Android

### ISSUE THREAD

**Issue by ide** [expo/expo#5988]
In this commit b5230674e11cbed7f3b188a04ae2dea245dd00b0 we comment out accessing member variables named `DEBUG_SERVER_HOST_PORT` and `INSPECTOR_PROXY_PORT` because they have been replaced by methods. This task is to update android/expoview/src/main/java/host/exp/expoview/Exponent.java to use the new RN 0.61 API when appropriate (and the old API when appropriate).

This is the commented-out code in Exponent.java:
```diff
-        Field debugServerHostPortField = fieldObject.rnClass().getDeclaredField("DEBUG_SERVER_HOST_PORT");
-        debugServerHostPortField.setAccessible(true);
-        debugServerHostPortField.set(null, debuggerHostPort);
+        // Field debugServerHostPortField = fieldObject.rnClass().getDeclaredField("DEBUG_SERVER_HOST_PORT");
+        // debugServerHostPortField.setAccessible(true);
+        // debugServerHostPortField.set(null, debuggerHostPort);
```

One possible fix is to add a setter method to the RN class that we call, instead of trying to override the port with reflection. Not sure what is most robust here.

**Comment by brentvatne** [comment]
related PR upstream https://github.com/facebook/react-native/pull/23616
