### ISSUE TITLE
[exp] connect ETIMEDOUT 35.184.55.1:443

### ISSUE THREAD

**Issue by milad1367** [expo/expo#599]
i have problems with build production apk for android and ios .

```
C:\Users\admin\Desktop\gitlab\sirin>exp build:android
[exp] Making sure project is set up correctly...
/[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] connect ETIMEDOUT 35.184.55.1:443
[exp] Set EXPO_DEBUG=true in your env to view the stack trace.

C:\Users\admin\Desktop\gitlab\sirin>
```

**Comment by terribleben** [comment]
Hi, sorry for the slow followup. Can you try again?

**Comment by milad1367** [comment]
hi tnx for response . That problem has been resolved . But I was faced with other problems.
It is located on this page for hours.


![issue](https://user-images.githubusercontent.com/15375991/30774709-c6dcd06e-a093-11e7-986c-a9a2e5265eab.png)

i use this command for create project "create-react-native-app AwesomeProject".

**Comment by milad1367** [comment]
please help me. I want to develop the application for the customer!!

**Comment by dikaiosune** [comment]
Hi! I'm glad the timeout was resolved. I'll close this issue.

Regarding the screenshot you pasted, it gives you a status command to run to see if your build is finished. If it fails, please post to the forums with the build ID that failed. Thanks!

**Comment by kumarryogeshh** [comment]
Happening again !

**Comment by JB-CHAUVIN** [comment]
Same goes for me : [exp] connect ETIMEDOUT 35.184.55.1:443

**Comment by milad1367** [comment]
some times the expo server  is down,
it can be solve ,
try again later

**Comment by Dipak-Bari** [comment]
For me it works when I added this in PS.

`$env:EXPO_DEBUG = 'true'`

**Comment by thg303** [comment]
any idea why this issue keep hapening? I can't even login using expo-cli?
is there any monitoring to watch that server heartbeat?
