### ISSUE TITLE
Expo client on iOS 13 keeps restarting (losing state)

### ISSUE THREAD

**Issue by johot** [expo/expo#5992]
I'm sorry I couldn't really use the bug template for this (didn't find a matching category), but I wanted to see if anyone else have this problem.

Since iOS 13 the expo client app will restart if you switch to any other app for say 1 minute... I have created a workout app for myself and what happens is that if I use it at the gym and then during resting time browse a webpage or Twitter then return to my app, expo client will restart loosing all State. I then have to restart my app etc which basically makes it useless.

Note this doesn't appear to be connected to my app it also happens if you just launch the expo client without launching any app.

Reproduce:
1. Start expo client in iOS without opening an app
2. Browse the web for a minute or 2
3. Go back to expo
4. Expo now restarts

Have anything changed in iOS 13 or in the expo client itself that causes iOS to "flush" it all the time?

Thanks for a great product!

**Comment by cruzach** [comment]
Hey @johot, thanks for bringing this up. I upgraded to iOS 13 and saw the same behavior, and tried getting more information as to why this was happening via the device logs. Not too much was revealed (if you want to give this a go, please do! Maybe you will notice something I didn't)

It looks like there have been a few reports of apps being terminated/having their states cleared when in the bg in iOS 13, so I'm not sure that this is an Expo-specific issue, but will keep this issue open for now until we find out more

**Comment by cruzach** [comment]
Closing this since it seems to be due to iOS 13 being a little more aggressive when it comes to killing backgrounded apps, not specific to Expo

**Comment by johot** [comment]
I don't believe this to be the only reason just opened a game I launched 3 hrs ago still in the same place where I left off. It must be expo client using resources like memory, doing something in the background etc that makes iOS kill it after about a minute. If this was true all my apps would restart all the time?

Thank you for looking into it, but I still think something fishy is going on here.

**Comment by cruzach** [comment]
Seems to be a pretty common theme in iOS 13 if you search for 'ios 13 killing background apps', but I'll keep this open for now

**Comment by cruzach** [comment]
@johot good news- we are [reverting the commit](https://github.com/expo/expo/pull/6150) that seems to have caused this issue

Thanks for pressing on this and keeping us accountable! Will be fixed in SDK 36

**Comment by johot** [comment]
Woho, great news good work @cruzach!!

Glad I could help! Looking forward to the new release! 😄
