### ISSUE TITLE
react-native-maps method map.getMapBoundaries does not work

### ISSUE THREAD

**Issue by iampeterbanjo** [expo/expo#5996]
## 🐛 Bug Report

The method `map.getMapBoundaries` does exist but the module required by Android, AirMapModule, is null therefore an error is thrown:

```
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.getMapBoundaries')]
```

This issue has been [reported at react-native-maps](https://github.com/react-native-community/react-native-maps/issues/2665) but it's actually an issue with Expo. I have created a repo that demonstrates using the same dependencies as Expo, react-native (0.59.10) and react-native-maps (0.25.0) the `map.getMapBoundaries` method works. See https://github.com/iampeterbanjo/react-native-v59-maps.

### Environment

  Expo CLI 3.3.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.11.4 - ~/.config/fnm/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.9.0 - ~/.config/fnm/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmGlobalPackages:
      expo-cli: 3.3.0

We are using Expo and targeting iOS and Android. This issue occurs only on Android.

### Steps to Reproduce

* git clone https://github.com/iampeterbanjo/react-native-maps-issues-2665
* cd into the repository folder.
* yarn install and yarn start.
* Launch the app in Expo on an Android simulator or device.

### Expected Behavior

There should be no errors and the map should display on Android.
See https://github.com/iampeterbanjo/react-native-v59-maps.

### Actual Behavior

There is an error thrown:

```
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.getMapBoundaries')]
```

### Reproducible Demo

https://github.com/iampeterbanjo/react-native-maps-issues-2665

**Comment by jbrumwell** [comment]
Anything that relies on `NativeModules.AirMapModule` fails as it is `undefined`

**Comment by ryanhobsonsmith** [comment]
We are also hitting this issue. Both on Expo 34 and 35 with native maps 0.24 or 0.25. Any updates on ways to work around this or when it might be fixed? Would hate to eject out of expo just for this issue.

**Comment by fl0r3k** [comment]
Same here
SDK 35
react-native-maps 0.25

**Comment by dragma** [comment]
Same here too. Does anyone have a workaround or something ? This is a pretty annoying bug.

**Comment by ribbit-rota** [comment]
Any updates on this one?

**Comment by vincentvella** [comment]
It appears that the AirMapModule is not linked through the Expo managed client via the `expo install react-native-maps` command, we'll need a fix for this. @brentvatne do you know if this was something addressed in upgrading any packages for the v36 upgrade that's around the corner?

**Comment by ribbit-rota** [comment]
Seems like it's still unfixed as of SDK 36

**Comment by davx1992** [comment]
Hi,
having same issue. Do you have any information when this will be fixed, as this criitcal issue, due to which it this impossible to use Maps on Android.
SDK 36

**Comment by eric1foard** [comment]
Related: https://github.com/expo/expo/issues/4791

**Comment by gabycasper007** [comment]
Same problem here

**Comment by bautrukevich** [comment]
I found how, not to getMapBoundaries, but calculate:
```typescript
import { LatLng, Region } from 'react-native-maps'

export const getMapBoundaries = (region: Region): [LatLng, LatLng] => {
  const northEast = {
    latitude: region.latitude + region.latitudeDelta / 2,
    longitude: region.longitude + region.longitudeDelta / 2
  }
  const southWest = {
    latitude: region.latitude - region.latitudeDelta / 2,
    longitude: region.longitude - region.longitudeDelta / 2
  }

  return [northEast, southWest]
}
```

**Comment by cruzach** [comment]
Patch has just been deployed, you'll need to rebuild your app with `expo build:android` to get the fix

**Comment by davx1992** [comment]
@cruzach how can I get this working when I am developing, without building?

**Comment by cruzach** [comment]
We'll have to release a new version of the Android Expo client app with the fix

**Comment by davx1992** [comment]
@cruzach is there any estimates when this could be done? As without this, it is almost impossible to develop app for Android.

**Comment by steele-cjf** [comment]
so？ what solution?

**Comment by cruzach** [comment]
We're in the midst of preparing for the SDK 37 release, so probably won't release a new version of the Expo client until then (will be released by March 31)

**Comment by steele-cjf** [comment]
Is there any emergency treatment method that we can solve it？

**Comment by dragma** [comment]
I had to remove expo from my project. 
And what I feared the most, has made me completly free.
I'm glad I encountered this bug !

**Comment by cruzach** [comment]
@steele-cjf one option that's pretty quick and easy is to build the android client from the `sdk-36` branch of this repo from source, just make sure you follow this [guide here](https://github.com/expo/expo/blob/master/guides/Developing%20the%20Client.md#configuring-your-environment)
