### ISSUE TITLE
OTF fonts error?

### ISSUE THREAD

**Issue by allpwrfulroot** [expo/expo#60]
I'm using some custom fonts, and although the TTF format works just fine, the system refuses to acknowledge .OTF files:
![screen shot 2017-02-14 at 1 48 55 pm](https://cloud.githubusercontent.com/assets/2465035/22943730/93f48e7e-f2bc-11e6-8c0b-7ba5f188c80d.png)

Is this an iOS simulator thing? I see references to .otf in Android parts of Exponent's codebase but not iOS, so that's my guess. The Exponent documentation doesn't mention any requirements?

**Comment by sonaye** [comment]
do you have this in your `exp.json`?
```
"packagerOpts": {
    "assetExts": ["ttf", "otf"]
  }
```

**Comment by manjeets12** [comment]
not working for me even after adding 
`"packagerOpts": {
    "assetExts": ["ttf", "otf"]
  }`

**Comment by expjess** [comment]
Hi @manjeets12 can you try restarting packager or `exp start -c` ? Thanks! 

cc @nikki93

**Comment by manjeets12** [comment]
@expjess  yeah it works, I have founded this thing on some other thread

**Comment by expjess** [comment]
yay great @manjeets12 ! which other thread?

**Comment by manjeets12** [comment]
this one [https://github.com/expo/expo/issues/85](url)

**Comment by manjeets12** [comment]
Now I have a strange behavior, I have loaded fonts in my root component before app loaded.They are coming fine in all components except my modal components, there is just white space in place of all those text where I have used custom fonts

**Comment by terribleben** [comment]
Hi @manjeets12, can you post a thread in the Help section of our forums with a small piece of code which reproduces your bug?

**Comment by manjeets12** [comment]
sorry that was by my mistake, I have resolved that
