### ISSUE TITLE
Expo web react-navigation-drawer: onHandler state change is not a function

### ISSUE THREAD

**Issue by swhistler** [expo/expo#6004]
### Environment

  Expo CLI 3.4.0 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.4.0

### Steps to Reproduce

React Navigation 4.0 just released so I was about to try out the drawer navigation on expo web. However, I encountered an error for onHandler state change is not a function while debugging through chrome. There are also bunch of other warnings for Reanimated module.

### Expected Behavior

I expected the drawer to be able to open and close, and to navigate through different screens/pages.

### Actual Behavior

Currently it can navigate to different pages but closing of the drawer does not work, it stays open permanently. However, it works fine on iOS and Android.

### Reproducible Demo

I created a blank expo project and installed the following dependencies.

expo install react-navigation react-native-gesture-handler react-native-reanimated react-native-screens

I followed the exact react-navigation-drawer example here.
https://reactnavigation.org/docs/en/drawer-based-navigation.html#docsNav

**Comment by brentvatne** [comment]
hello! this belongs on https://github.com/react-navigation/drawer - thanks!

**Comment by alejandropaciotti** [comment]
Hi @hazeeq-dev, I agree with brentvatne, this belongs on react-navigation-drawer . But I didn't find any solution in those [issues](https://github.com/react-navigation/drawer/issues).
I solved it importing `createDrawerNavigator` from **react-navigation** instead **react-navigation-drawer**.


```
import { createStackNavigator, createDrawerNavigator } from 'react-navigation'
// import { createDrawerNavigator } from 'react-navigation-drawer'
```
