### ISSUE TITLE
Error Bare Workflow Up and Running

### ISSUE THREAD

**Issue by Gardens18** [expo/expo#6012]
Goal : To migrate from existing managed and developed expokit project to bare react native xcode project.

So to create the bare workflow,  I just followed the below instruction just now, 

Up and Running
To get started with a bare React Native project, run expo init and choose one of the bare templates. We'll use the minimum template here. This guide assumes that you have Xcode and/or Android Studio installed and working.
# If you don't have expo-cli yet, get it
npm i -g expo-cli
# If you don't have react-native-cli yet, get it
npm i -g react-native-cli
# This is a shortcut to skip the UI for picking the template
expo init --template bare-minimum
Next, let's get the project running. Go into your project directory and run react-native run-ios or react-native run-android — hurray! Your project is working.

We are getting the below errors :

debug Error: Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening tdappb1.xcworkspace

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/riaz/tdappb1/ios/build/tdappb1/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/EXAppLoaderProvider.build/Objects-normal/x86_64/EXAppLoaderProvider.o /Users/riaz/tdappb1/node_modules/expo/node_modules/expo-app-loader-provider/ios/EXAppLoaderProvider/EXAppLoaderProvider.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at ChildProcess.buildProcess.on.code (/Users/riaz/tdappb1/node_modules/@react-native-community/cli/build/commands/runIOS/runIOS.js:231:16)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)

**Comment by Gardens18** [comment]
I did pod install. nothing works. 

try this repo and confirm whether bare workflow works ?\
https://github.com/expo/expo/issues/5997

**Comment by cruzach** [comment]
@Gardens18 is this issue and 5997 separate problems? Or should we close one to consolidate the conversation?

**Comment by cruzach** [comment]
closing in favor of 5997
