### ISSUE TITLE
ImageManipulator.manipulateAsync "Calling bridge.imageLoader is deprecated" warning on RN 0.61.*

### ISSUE THREAD

**Issue by sezginriggs** [expo/expo#6018]
### Environment

iOS, bare React Native 0.61.2, expo-image-manipulator 7.0.0

### Steps to Reproduce

The following call to ImageManipulator.manipulateAsync creates warning: "Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to themoduleForClassAPI or turboModuleLookupDelegate API."

`        const rotateResult = await ImageManipulator.manipulateAsync(
            this.state.photoPreviewImageUri,
            [{ rotate: 90 }],
            { compress: 1, format: ImageManipulator.SaveFormat.JPEG }
        );`

### Actual Behavior

ImageManipulator.manipulateAsync creates warning: "Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to themoduleForClassAPI or turboModuleLookupDelegate API."

**Comment by cruzach** [comment]
Hi! We recommend using the version of RN pinned with the most recent Expo SDK when in a bare project (right now that's RN 0.59). As for newer RN version, your mileage may vary

We are working on upgrading to RN 0.61 for our next SDK release, so stay tuned for that.

**Comment by rogercsg** [comment]
i am getting same error:

react-native-cli: 2.0.1
react-native: 0.61.5
![Screenshot 2019-12-04 at 3 27 44 PM](https://user-images.githubusercontent.com/47353104/70132637-a6fbe980-16aa-11ea-8de2-b2357a977ae3.png)

**Comment by lukmccall** [comment]
Hi everyone, I think it'll be fixed by this [PR](https://github.com/expo/expo/pull/6400).
