### ISSUE TITLE
[android] Bare App requires unused permissions

### ISSUE THREAD

**Issue by dehli** [expo/expo#6023]
### Environment

```
  Expo CLI 3.4.0 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.15.2 - /usr/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.10.1 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
    npmPackages:
      @types/react: ^16.9.6 => 16.9.6 
      @types/react-native: ^0.60.20 => 0.60.20 
      @types/react-navigation: ^3.0.8 => 3.0.8 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.4.0
```

I'm targeting iOS and Android, but the bug is specific to Android.

### Steps to Reproduce

1. Run `expo init`
1. Choose `Bare`
1. Remove all optional permissions from `AndroidManifest.yml`
1. Build your Android project. 
1. Notice that the project still requires the following unused permissions:
  - `android.permission.ACCESS_COARSE_LOCATION`
  - `android.permission.ACCESS_FINE_LOCATION`
  - `android.permission.FOREGROUND_SERVICE`

### Expected Behavior

Those permissions wouldn't be included.

### Notes

~~Before building your Android project, you can manually remove the permissions from the following file:~~

```
./node_modules/expo-location/android/src/main/AndroidManifest.xml
```

Unfortunately this doesn't work - I was too optimistic that it would. Permissions are still being added from below:

```
uses-permission#android.permission.ACCESS_FINE_LOCATION
ADDED from [io.nlopez.smartlocation:library:3.2.11] /home/cpdehli/.gradle/caches/transforms-1/files-1.1/jetified-library-3.2.11.aar/18892650106ab8050c0a2f862246cf39/AndroidManifest.xml:14:5-79
	android:name
		ADDED from [io.nlopez.smartlocation:library:3.2.11] /home/cpdehli/.gradle/caches/transforms-1/files-1.1/jetified-library-3.2.11.aar/18892650106ab8050c0a2f862246cf39/AndroidManifest.xml:14:22-76
```

The following did work though! If you run `rm -rf ./node_modules/expo-location`, then `BasePackageList.java` will auto update and remove the location service.

### Reproducible Demo

[Expo Bare Project](https://github.com/expo/expo/files/3743944/permissions.zip)

**Comment by solace** [comment]
Curious about a similar set of perms on a bare app.

I have an app that explicitly uses location permissions, and these are included in the manifest on Android, but my play store listing indicates that it also has "Photos / Media / Files" permissions but these have not been specified in the manifest.

Is something implicitly setting these permissions? If so is there a way to remove them?

**Comment by esamelson** [comment]
Hi -- sorry for the slow followup here! Permissions that are requested by libraries you include in your Android project, such as React Native, get merged into the final manifest included with the app. If you want to explicitly exclude certain permissions, you can add the following line to your app's AndroidManifest:
```<uses-permission android:name="<permission-name-here>" tools:node="remove"/>```
Note that this can cause undefined behavior in some cases since libraries can depend on certain permissions! But for Expo libraries and React Native it's generally fine if you're not using the specific functions that require those permissions.

**Comment by avinashiitb** [comment]
Hello @esamelson can you tell me the location of the AndroidManifest file, I am using expo SDK 39.0.0
And I am not able to find the AndroidManifest file

**Comment by brentvatne** [comment]
@avinashiitb - it's easy to find if you have a bare project, so i won't bother explaining that case. it's not exposed in a managed project. read about android permissions here: https://docs.expo.io/distribution/app-stores/#android-permissions
