### ISSUE TITLE
Computer stops responding at starting metro bundler in expo react native project 

### ISSUE THREAD

**Issue by mohamedcutte** [expo/expo#6027]
I am developing react native app using expo cli. I installed **expo-cli** using **yarn** with ```yarn global add expo-cli``` .

I created my project using ```expo init appname```.
everything looks good, my project is created but when ever I try to start my project, my computer is getting stuck at:

```starting metro bundler on port 19001```

**Comment by cruzach** [comment]
Hi! We like to keep Github reserved for bug reports, so you're probably better off asking questions like this on our [forums](https://forums.expo.io/) (or fill out the full bug report template)

If you're using a mac, I'd make sure you have watchman installed.
