### ISSUE TITLE
expo keeps reloading app after initial "npm start"

### ISSUE THREAD

**Issue by Nbestwl** [expo/expo#603]
i don't know where is the issue, here are my dependencies
  "dependencies": {
    "expo": "^18.0.3",
    "firebase": "^4.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-elements": "^0.16.0",
    "react-native-router-flux": "^4.0.0-beta.19",
    "react-native-vector-icons": "^4.3.0",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-form": "^7.0.3",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  }

And i have been searching solutions for couple days, but the only thing works now is to manually disable live reload. Also i don't see anyone else has same issue as me, so it will be appreciated if anyone can tell me where to start. Thanks

**Comment by jimmylee** [comment]
@Nbestwl sorry you're experiencing trouble. It doesn't look like your dependencies are setup with Expo? For example:

```
    "expo": "20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
```

Did you [detach](https://docs.expo.io/versions/latest/guides/detach.html#content) your project to ExpoKit? Normally to run Expo applications from the command line we use a command called `exp`

You can learn more about it here: https://docs.expo.io/versions/latest/guides/exp-cli.html#content

If you're using `exp`, you should also try a clean `rm -rf node_modules` if you're going to install new dependencies.

Let me know if you have any more details and if I can help in any other way.

**Comment by JoeAnzalone** [comment]
Are you working on your project from within a Dropbox folder? I had the same issue and moving it out of Dropbox fixed it for me.

**Comment by c316** [comment]
I'm seeing the same thing and I don't have my project in Dropbox. Also, iCloud isn't active

**Comment by c316** [comment]
It is strange, because this only happens on the iOS emulator. I can run the exact same project from my android phone and it doesn't get reloaded.
