### ISSUE TITLE
[jest-expo-enzyme] Fails to resolve react-native mocks

### ISSUE THREAD

**Issue by mahmut-gundogdu** [expo/expo#6030]
### Environment

 Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
      npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1

### Steps to Reproduce
expo init --template tabs
npm install jest-expo-enzyme
change present to  "jest": { "preset": "jest-expo-enzyme"},   in package.json.
delete default *-test.js files
create new App.test.js in __tests__ folder.
add it('works', () => { expect(1).toBe(1); }); to App.test.js
run npm run test in terminal

### Expected Behavior
passed 3 tests (ios ,android and web)

### Actual Behavior
` FAIL   Web  __tests__/App-test.js
  ● Test suite failed to run

    /Users/username/Documents/Expo/Expo35WithTestTabs/node_modules/jest-expo-enzyme/src/setupEnzyme.web.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Adapter from 'enzyme-adapter-react-16';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
          at Array.forEach (<anonymous>)

 FAIL   Android  __tests__/App-test.js
  ● Test suite failed to run

    /Users/username/Documents/Expo/Expo35WithTestTabs/node_modules/jest-expo-enzyme/src/setupEnzyme.native.js:4
    import 'react-native';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
          at Array.forEach (<anonymous>)

 FAIL   iOS  __tests__/App-test.js
  ● Test suite failed to run

    /Users/username/Documents/Expo/Expo35WithTestTabs/node_modules/jest-expo-enzyme/src/setupEnzyme.native.js:4
    import 'react-native';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
          at Array.forEach (<anonymous>)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        2.616s
Ran all test suites in 3 projects.`

### Reproducible Demo
https://github.com/mahmut-gundogdu/expo-35-with-expo-jest-enzyme

**Comment by EvanBacon** [comment]
Sorry we fixed this a while ago but the package wasn't published. Just verified in a fresh project that this works in `jest-expo-enzyme@0.0.1`. 
Sorry again for the inconvenience.
