### ISSUE TITLE
expo bundle-assets  required for Expokit release 

### ISSUE THREAD

**Issue by AmriApps** [expo/expo#6032]
I had a problem to generate APK for release or even for debug. After hours of debugging I fix that by using the following command: 

`expo bundle-assets --platform android --dest ./android/app/src/main/assets`

`expo-cli 3.4.1`
`Expokit: updated from 33 to >> 35`
`gradle 5.4.1 , android gradle 3.4.0`

I don't know if this is a bug or new feature! 

----- UPDATE ----- 
When I run iOS I face the same problem. Till I run the `expo bundle-assets` to generate assets for ios too

**Comment by cruzach** [comment]
I think this only applies to Expokit projects, would definitely be open to a PR to this page of the docs though > https://docs.expo.io/versions/v35.0.0/expokit/expokit/ 🙂

**Comment by FabrizioCaldarelli** [comment]
If you eject a project starting from SDK 35, android gradle will be 3.5.1 by default. But if then you migrate to Android X (maybe because you want to add Firebase Analytics feature), it will not build anymore.

So it is needed to manually change to android gradle 3.4.0.

@DevSoFar fix works for me, thank you. It seems that expo.gradle doesn't fully work.

**Comment by lc3t35** [comment]
@DevSoFar what is the --dest path for ios ?

**Comment by FabrizioCaldarelli** [comment]
@lc3t35 this is taken from "Bundle Expo Assets" from Xcode Build Phases

```
set -eo pipefail

if [ "$CONFIGURATION" == "Debug" ]; then
  echo "Skipping asset bundling in debug mode."
  exit 0
fi

pushd "${SRCROOT}/.."
export PATH="$(if [ -f ~/.expo/PATH ]; then echo $PATH:$(cat ~/.expo/PATH); else echo $PATH; fi)"
dest="$CONFIGURATION_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH"
expo bundle-assets --platform ios --dest "$dest"
popd
```

<img width="1137" alt="Schermata 2019-11-15 alle 17 20 46" src="https://user-images.githubusercontent.com/4108673/68958375-4b85bc80-07cc-11ea-9cfa-b77e21f67346.png">

**Comment by DevSoFar** [comment]
> @DevSoFar what is the --dest path for ios ?

For me ios was working

**Comment by lc3t35** [comment]
It happens when CONFIGURATION changes to Debug (don't know why)
During Dev mode, I had to comment exit 0 so assets are bundled correctly.

**Comment by juandav** [comment]
Platform: windows

```
$ expo-module babel --config-file ./babel.config.build.js --source-maps --out-file build/IconsLazy.js build/Icons.js
node_modules\expo-module-scripts\bin\expo-module-babel:3
set -eo pipefail
        ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by vivek751** [comment]
https://github.com/expo/expo-cli/issues/4150
i am facing issue

**Comment by lfabl** [comment]
This issue still continue.
