### ISSUE TITLE
[iOS][appauth] cancelled appauth code not accounted for in Google.logInAsync SDK v35

### ISSUE THREAD

**Issue by nolanholden** [expo/expo#6033]
### Environment
iOS 13, expo SDK v35.0.0

### Steps to Reproduce
Open [the example snack](https://snack.expo.io/@nolanholden/faulty-ios13-google-auth) and run **on iOS 13**.

NOTE: the snack emulator does not run iOS 13. You'll need an iOS 13 device, or try to update the emulator.

### Expected Behavior
Tapping "Cancel" on first native iOS modal, or tapping "Continue" and then "Cancel" should not throw errors (and instead return a `loginResult.type === 'cancel'`).

### Actual Behavior
I'm getting inexplicable errors stemming from native code, instead of expected `loginResult.type === 'cancel'`. Sign in works perfectly when followed through.

Seems to be related to #454.

### Reproducible Demo
https://snack.expo.io/@nolanholden/faulty-ios13-google-auth

### Screenshot of output:
![](https://i.imgur.com/aMQMFPp.jpg)

**Comment by cruzach** [comment]
@nolanholden it looks like this isn't specific to iOS 13. But, the issue isn't the `expo-google-app-auth` library, but rather the call to `AppAuth.authAsync` is resulting in this error (which doesn't match the error that the underlying `catch` in Google.js is looking for, which results in it slipping through

**Comment by nolanholden** [comment]
@cruzach thanks for the clarification there. Still the example snack posted works fine for earlier iOS versions but fails iOS 13. Any ideas?

**Comment by cruzach** [comment]
I'm getting the same error response on iOS 12

**Comment by cruzach** [comment]
Looks like the error code is actually correct -> https://github.com/openid/AppAuth-iOS/blob/65ef95c6b38c7889fdda7a22f242fa0156fd43b2/Source/OIDError.h#L103
-3 `Indicates the user manually canceled the OAuth authorization code flow.`

**Comment by nolanholden** [comment]
Perfect, great detective work 😁 this VEVO or is inconsistent with the API right? We prefer to respond with a `response.type === 'cancel'` right?

**Comment by cruzach** [comment]
Correct, looks like it has to be handled correctly in the iOS AppAuth src
