### ISSUE TITLE
setting SelectionColor on a RN TextInput gives error on android when running on an expo detached app

### ISSUE THREAD

**Issue by clickclickonsal** [expo/expo#604]
This is a screenshot of the error that I am getting.
![screenshot_20170906-143703](https://user-images.githubusercontent.com/8260678/30128827-0901f4ae-9312-11e7-8443-149004206159.png)
    
To verify that this isn't related to my application that I'm working on, I created a brand new expo project (v20.0.0) & only added this code to the `App.js` file. 
```
<TextInput value="value"selectionColor="blue" />
```
It runs fine perfectly fine. Then when I detach the app by running `exp detach` and start the app by running `react-native run-android` I get the error shown in the screenshot above. This only occurs when adding the `selectionColor` property to the `TextInput` component from 'react-native`.

**Comment by peterlazar1993** [comment]
Running into the same error on detached sdk 22 android build. Also reproduced the issue via the same method as OP

**Comment by sjchmiela** [comment]
I've just run an ejected project on SDK31 in release mode and the code provided in Snack didn't crash the app. 🎉 I hope the issue is solved now. 🙂 (x-ref: 
https://github.com/expo/expo/issues/925#issuecomment-440770380)
