### ISSUE TITLE
Pedometer.getStepCountAsync(start, end) gets step count inconsistent with iOS Health App

### ISSUE THREAD

**Issue by ngkel** [expo/expo#6041]
I have been troubleshooting my app's pedometer on iOS as some iPhone get step count using Pedometer.getStepCountAsync(start, end) inconsistent with the Health App (3984 steps from expo pedometer vs 6264 steps from health app). I tried to collect some data from iPhone users and it seems those without Apple watch are all working fine. Is it a problem associated with the use of Apple watch?

**Comment by cruzach** [comment]
What do you mean by "those without apple watch are fine"? As of now, you can't create apps for WatchOS with Expo/RN

If the `Pedometer` module is inaccurate, could you provide a method to demonstrate this?

**Comment by ngkel** [comment]
I have tested on the demo App (https://docs.expo.io/versions/latest/sdk/pedometer/) and compared the value of "Steps taken in the last 24 hours" with the one recorded in iOS Health App. It is found that when I pair my iPhone with Apple watch, the values between the expo demo App and iOS Health App are different. If I disconnect the Apple Watch, the two values match again.

You may replicate the result with the following steps:
1. Expo init project with code from https://docs.expo.io/versions/latest/sdk/pedometer/
2. Pair Apple Watch with iPhone
3. Compare the value between the Expo App and the Health App in iOS

**Comment by cruzach** [comment]
The value in the iOS Health App changes when you connect to the Apple Watch?

**Comment by ingstartup** [comment]
Still seeing the same problem today.
Basically, the Pedometer.getStepCountAsync() can only retrieve step counts done by the mobile device. The step count done by the apple watch is ignored from the sum

**Comment by JonasHenrq** [comment]
Has this problem been resolved yet? Today, with `"expo-sensors": "~11.3.0"`, I have the same problem.
