### ISSUE TITLE
Can't save event to Calendar on Android

### ISSUE THREAD

**Issue by lucas-wilmart** [expo/expo#6042]
### Environment

Expo CLI 3.4.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: 34.0.4 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.4.0

I get the same errors on Snack, Android Studio Emulator and real devices. I didn't test on iOS

### Steps to Reproduce

Just try to create an event using `Calendar.createEventAsync`. Either with an existing calendar id, or with a freshly created one.

### Expected Behavior

When I create an event, I want the event to be saved (and the app to not crash obviously)

### Actual Behavior

At first I was confused on which calendar id to pick to create my event since you guys removed `Calendar.DEFAULT` (since it does not exist on Android it makes sense to have removed it though). I tried to create a basic event on each one of the calendars on my phone, every time I tried so => either I get this very explicit and useful output "Error: Event could not be saved" or the expo app just crash. With my snack demo (see in reproducible demo section), I could only reproduce the case where I get the error message. 

### Reproducible Demo

https://snack.expo.io/SyY5lxsYr

**Comment by lukmccall** [comment]
Hi @lucas-wilmart, I've tested your snack. However, I found one mistake in your code. You used `createCalendarAsync` instead of `createEventAsync`. So I created my own [snack](https://snack.expo.io/@lukaszkosmaty/github---calendar-doesn't-save-event---android). 
Everything worked fine.

Please, check my snack and tell me if it's working in your case. If no, provide more information to help me with reproducing this bug.

**Comment by lucas-wilmart** [comment]
Thanks a lot. Indeed there was an obvious mistake in my snack, sorry for that.
But my code on my app is good, but still I get this very useless error message "Event could not be saved" which I can't reproduce in a snack. I will try to reproduce it or solve it and come back later. This might not be an error, but still, the error message could be changed because it's a bit confusing

**Comment by lucas-wilmart** [comment]
No matter how similar my code and my snack are, I get "Error: Event could not be saved" every time. I carefully checked everything that might have gone wrong other than that, but everything's seems fine. My app code is pretty much a copy / paste of what I've done in Snack but somehow, still the same error, and it's working perfectly on snack. I also checked the calendar id do exists and do corresponds to a calendar which is own by the user...

**Comment by lukmccall** [comment]
Unfortunately, I've no clue why you're still getting this error.
Could you provide a GitHub repo with your code? Or create a new one only with crucial parts, which could help to reproduce this bug?

**Comment by lucas-wilmart** [comment]
@lukmccall By literally copy/paste my whole code into a snack I was finally able to reproduce the bug: https://snack.expo.io/S1I1J92tS Could you please check it out? Thanks for your patience

**Comment by lukmccall** [comment]
@lucas-wilmart, thanks for a new demo. I'll check it later.
