### ISSUE TITLE
A rectangle appears on my screen when I bindtap will exit the program

### ISSUE THREAD

**Issue by EasonQwQ** [expo/expo#6043]
### like this
![451571638862_ pic](https://user-images.githubusercontent.com/22360580/67194323-76792c80-f429-11e9-9983-cceec1345d8e.jpg)
this rectangle can be dragged。iPhone XR ，ios 13。

**Comment by cruzach** [comment]
That looks like the `performance monitor`. Simple bring up the developer menu by either shaking your device or pressing with two fingers, and tap `hide perf monitor`
