### ISSUE TITLE
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.11.5`

### ISSUE THREAD

**Issue by Gardens18** [expo/expo#6044]
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.11.5`

pod install stucks on this after ejecting to expokit

**Comment by cruzach** [comment]
Was this automatically configured to `ios/2.11.5`? What Expo SDK version are you using? 2.11.5 isn't one of [our releases](https://github.com/expo/expo/releases)

**Comment by Gardens18** [comment]
It is automatically configured to ios/2.11.5  
"sdkVersion": "33.0.0",

**Comment by cruzach** [comment]
Can you try the solutions posted [here](https://forums.expo.io/t/pod-install-fail-to-download-expokit-2-9-0/16158/2?u=charliecruzan)? Seems like that hang is a not-so-rare occurence

Barring that, I'd try upgrading to SDK 34
