### ISSUE TITLE
Change spinner color on loading screen

### ISSUE THREAD

**Issue by AdamPD** [expo/expo#605]
Hi guys,

I haven't been able to see a way to change the spinner color on the loading screen for either iOS or Android.  I know that we can change `backgroundColor`, `icon` etc. but nothing about the color of the spinner.

In our example, our background is fairly dark so the spinner is almost invisible.

Looking at the documentation and the source (at least for iOS), it seems that the colour is never modified from the default.

Is this possible or is it a new feature request?

**Comment by jimmylee** [comment]
Hey @AdamPD, I also just looked at the implementation and noticed that we don't support changing the color from the loader. I've cc'd @brentvatne and maybe we'll be able to do this quickly.

Cool idea.

**Comment by terribleben** [comment]
Hi there, we're no longer supporting the `loading` API with the spinner and we recommend everyone uses the `splash` API we introduced a few months ago. Closing this as a result.
