### ISSUE TITLE
No Push Notifications Sent (Tool)

### ISSUE THREAD

**Issue by DConnorFong** [expo/expo#6052]
## 🐛 Bug Report
As a note this was working completely fine in the online tool and my Node.js server approximately 16 hours ago (12AM PST). I am trying to use the tool today and nothing is reaching my device. I have also tried to delete the app, and reinstall on my phone (getting and then trying a new token) as well as log out and back in.

### Environment
iOS app (iPhone X 13.1.2)

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.19.1 - ~/.yvm/shim/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.2
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^34.0.1 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.0.10

iOS device running the app

### Steps to Reproduce
1. Retrieve my expo token from Notifications.getExpoPushTokenAsync();
2. Place it in the Expo push notification tool https://expo.io/dashboard/notifications
3. Send a notification

### Expected Behavior
Should receive a push notification

### Actual Behavior
Nothing is sent

**Comment by cruzach** [comment]
Hi! We've received just a few reports of this so far. Currently looking into it, but thanks for bringing it to our attention

**Comment by cruzach** [comment]
Update: we've pushed out a fix for this. We'll keep an eye on it, but your notifications should be up and running

**Comment by cruzach** [comment]
Closing this issue since the outage has been resolved. Thanks again for posting about this @DConnorFong
