### ISSUE TITLE
LottieView - "Platform.select(...) is not a function" Error Occurs When Running Expo in Web

### ISSUE THREAD

**Issue by melnikeug** [expo/expo#6054]
## 🐛 Bug Report

Unable to run expo project in web, when using LottieView, because of an error:
"Platform.select(...) is not a function"

### Environment

Expo Documentation

### Steps to Reproduce

Go to: https://docs.expo.io/versions/latest/sdk/lottie/
Toggle "Preview" Switch "On" and press "Web":
![image](https://user-images.githubusercontent.com/7370201/67265374-3ca23780-f4b6-11e9-9fcb-dd454dd1e720.png)

### Expected Behavior

Lottie animation should appear instead of an error.

### Actual Behavior

"Platform.select(...) is not a function" Error Occurs

### Reproducible Demo

https://docs.expo.io/versions/latest/sdk/lottie/

**Comment by cruzach** [comment]
I'm not sure if [`lottie-react-native`](https://github.com/react-native-community/lottie-react-native) offers web support

**Comment by Cryptec** [comment]
same issue here. Is there already a solution?

**Comment by Nate1546** [comment]
same issue here

**Comment by calumjames** [comment]
> I'm not sure if [`lottie-react-native`](https://github.com/react-native-community/lottie-react-native) offers web support

@cruzach, there seems to be a version of Lottie for React Native for Web, by the React Native for Web Community: https://github.com/react-native-web-community/react-native-web-lottie.

Could that package be used instead of lottie-react-native?

**Comment by mafiusu** [comment]
Is there any news regarding of how using Lottie for expo web?

**Comment by Zaidusk21** [comment]
Tried to use low kb file of lottie and tried once 
its working for me

**Comment by bananemo** [comment]
The [react-native-web-lottie](https://github.com/react-native-web-community/react-native-web-lottie) package works for me, thanks!

**Comment by farhanalislalom** [comment]
@bananemo, I am stuck on this as well and cant get react-native-web-lottie to work. How did you make it work?

**Comment by bananemo** [comment]
@farhanalislalom I just installed the `react-native-web-lottie` and then add the alias in my `webpack.config.js` following the steps in the [README](https://github.com/react-native-web-community/react-native-web-lottie) and then it works

**Comment by farhanalislalom** [comment]
@bananemo Thanks for the quick reply. It still didnt work for me. When I update my webpack.config.ts, it gives me errors about my config.resolve. It could be a typescript issue. 
But for the time being, I have just used 2 files (web and native) to load lottie-react and lottie-react-native. This works but still figuring out how to position the animation in mobile. It just disappears if I put it inside a View.

**Comment by KeitelDOG** [comment]
@farhanalislalom that's what I did too. Only instead of using a `lottie-react`, I used directly `lottie-web` package and mount it with `useRef`, this way I have full control of features. After I use `Lottie.native.js` and `Lottie.web.js` that loads automatically the correct one. There is even a `lottie-ios` package that I'm not sure if it's necessary if I already use `lottie-native`.

**Comment by bananemo** [comment]
@farhanalislalom I didn't use `lottie-react`, I just used `lottie-react-native` directly without the platform-specific file, after making sure that it works on the mobile, I installed the `react-native-web-lottie` and then add the alias in my `webpack.config.js`, and then it just works on the web for me. I didn't do anything else for `react-native-web-lottie`

**Comment by farhanalislalom** [comment]
@bananemo Thanks. I think this is where I was messing up. Using react-native-web-lottie instead of lottie-react-native.
