### ISSUE TITLE
How to add Image to PDF with Expo Print.printAsync() in <html> tag?

### ISSUE THREAD

**Issue by veronicalw** [expo/expo#6057]
I want to add an image in my pdf file after generating html to strings with this print function, but it turns out nothing. The image that I get from an url even from my local storage didnt show up.  How can I retrieve image from somewhere to my PDF File? 
**Here's my print method:**

`
async createPDF() {

    let filePath = await Print.printAsync({
      html:  '<h1 style="text-align: center;"><strong>Bukti Peminjaman </strong></h1>' +
                '<Header align="center"><img src="https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwiLz-_67q_lAhUJcCsKHaNtAP0QjRx6BAgBEAQ&url=https%3A%2F%2Fid.wikipedia.org%2Fwiki%2FBerkas%3APoliteknik_Caltex_Riau.png&psig=AOvVaw1UYEZsJySh5sbNJsAYQ3WA&ust=1571833694362498"></Header>'+
              '<p style="text-align: center;">Data Lab ID : '+(this.state.TextFieldid)+
              '</p><p style="text-align: center;"><strong>by Lab.Co</strong></p><table>'+
              '<tr><td><strong> Ketua Kegiatan </strong></td><td>:</td><td>'+(this.state.TextFieldketua_kegiatan)+'</td></tr><tr><td></td></tr>'+
              '<tr><td><strong> Laboratorium </strong></td><td>:</td><td>'+(this.state.TextFieldlab)+'</td></tr><tr><td></td></tr>'+
              '</table><br><br><br><br>'+
              '<Footer<center>&copy; Copyright 2019 LAB.CO<br><br>'
              +this.state.date+'</center></footer>',
      width : 612,
      height : 792,
      base64 : false
    });

    alert('PDF Generated', filePath.uri);
  }
`

**Comment by JensSam** [comment]
I can't get it to work either, so not sure why this is closed. The example in snack has absolutely nothing to do with the print function either.. I've tried it with a local image as well, but the same result. PDF comes out without a picture in it.

**Comment by veronicalw** [comment]
> I can't get it to work either, so not sure why this is closed. The example in snack has absolutely nothing to do with the print function either.. I've tried it with a local image as well, but the same result. PDF comes out without a picture in it.

Yes, exactly... I've tested this before and nothing happen, even I took the picture using URL, and absolutely nothing.

**Comment by cruzach** [comment]
The example snack was just an easy way to embed an image into HTML. If that same html doesn't work with the `Print` api, then that's an easy demo to make 😄 

As it says in the discussion template you filled out:
> Please note that discussions opened as issues in the core Expo repository will be closed.

I'm happy to reopen this, but will need you to follow the full bug report format including a reproducible demo
