### ISSUE TITLE
Is it possible to enable "App Transport Security"?

### ISSUE THREAD

**Issue by christiantakle** [expo/expo#6059]
The question is in the title. I didn't find anything when looking at the documentation. Maybe I can do it by changing the plist in the app manifest for IOS.

Last lead got me here: https://github.com/expo/expo/issues/406

**Comment by cruzach** [comment]
We keep github reserved for bug reports, but it looks like a similar question was posted on our [forums](https://forums.expo.io/t/expo-info-plist-setup-for-app-transport-security-exception/27227)!

**Comment by christiantakle** [comment]
Did search the forum; have seen that post and it doesn't answer the question. There are some similar questions on the forum but none answered hence this issue.

But thanks will go try my luck there / do experiments with `app.json` `ios.infoPlist`

**Comment by christiantakle** [comment]
@cruzach based on your reply the project should consider removing the 'Questions and discussion' option when creating an issue.

<img width="1192" alt="Screenshot 2019-10-23 at 11 59 04" src="https://user-images.githubusercontent.com/684866/67390615-8cebc900-f58c-11e9-8191-f26e946a382a.png">

**Comment by cruzach** [comment]
When you open the Questions and Discussions issue templates, it states that the issue will be closed and you should instead post on our forums (same goes for the Feature Requests template). We keep them there just to give those who only know of our Github a way to find out about those features.
