### ISSUE TITLE
How to setup android minSdkVersion ?

### ISSUE THREAD

**Issue by volodyad** [expo/expo#606]
I need to forbid android 4.x versions, usually android devs do it via https://developer.android.com/guide/topics/manifest/uses-sdk-element.html 
but I don't see in expo config possibilities to set minSdkVersion. How I can set this parameter?

**Comment by jimmylee** [comment]
In react native you can do the following:

```
Detecting the Android version #
On Android, the Platform module can also be used to detect the version of the Android Platform in which the app is running:

import { Platform } from 'react-native';

if (Platform.Version === 25) {
  console.log('Running on Nougat!');
}
```

Snack: https://snack.expo.io/SJ3XoEyjW
React Native Docs: https://facebook.github.io/react-native/docs/platform-specific-code.html

And thats the best we can do for you at the moment.

**Comment by knicefire** [comment]
@jimmylee  Correct me if I'm wrong but the question was about different thing. 
Adding property through manifest would restrict the app installation altogether. 
Google Play uses it to filter out the app for the devices that don't meat bear minimum requirements regarding SDK level. 
Your example show's the detection in case you need different behavior. 
So basically you can show something like an error message "Your phone is not supported" but this is not a good UX in my opinion. 

Does expo apply <uses-sdk android:minSdkVersion="?" /> when dropping support of an android SDK in a new version of the expo SDK? 

Just recently expo released SDK 26 that drops support for android SDK 19. 
But publishing android apk to Google Play doesn't exclude devices with no SDK 19 (basically all android 4.4)

**Comment by anp** [comment]
@knicefire I think you might be mixing up Expo SDK versions with Android SDK versions. All versions of the Expo SDK support Android 4.4 and greater. If you want to control these fields more directly I would recommend detaching and building your app with ExpoKit -- you'll get full control over the Play Store metadata that way.

**Comment by knicefire** [comment]
@anp Hmmm.. it might be the case. 
So you basically saying that when Expo announces that "Drop SDK19, will drop SDK20 next release" they are speaking about Expo SDK support and not about Android SDK support. 

So the reason I have crashes a lot in android 4.4 is not related to Expo dropping SDK19 of they own. 

Thanks. :)
