### ISSUE TITLE
Cannot attach audio recording .caf file to email

### ISSUE THREAD

**Issue by youngchingjui** [expo/expo#6061]
### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.8.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.0 => 4.0.0 
    npmGlobalPackages:
      expo-cli: 3.1.2

iOS 13.1.2 - iPhone X device

### Steps to Reproduce

Users can record audio using the expo-av library. I'd like to attach that audio recording to an email.

### Expected Behavior

I expect the audio recording to attach to the email without any problems.

### Actual Behavior

 However, when trying to attach the audio file, I get this error message: 

```
Error: An exception was thrown while calling `ExpoMailComposer.composeAsync` with arguments `(
        {
        attachments =         (
            "file:///var/mobile/Containers/Data/Application/CBB9D654-71D3-43F1-9078-86981769B30C/Library/Caches/ExponentExperienceData/%2540youngchingjui%252FRecordAndEmail/AV/recording-C828A4A2-E150-496E-8327-48FB628B8566.caf"
        );
        body = "This is a test body message";
        isHtml = 1;
        recipients =         (
            "testing@email.com"
        );
        subject = "Testing sending mail and attachment with Expo";
    }
)`: *** -[NSPlaceholderString initWithString:]: nil argument
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at debuggerWorker.js:80
```

### Reproducible Demo

I've published a small demo of this issue here:
https://expo.io/@youngchingjui/RecordAndEmail

I'm unsure as to how to load the source code into Snack, so I've uploaded the major files to Github:
https://github.com/youngchingjui/RecordAndEmail
There you'll see the App.js and package.json file you can download. You'll need to run `npm i` to install the packages within package.json.

There's a simple button to make a quick audio recording. Do that first.
Then after the audio recording is made, tap the second button to try and send an email.
For comparison, I also made a simple test.txt file in the FileSystem.documentDirectory. I am able to successfully attach the .txt file. So I'm wondering if the issue is something to do with the audio file?

Thank you for your time with this!
Meanwhile, I'll be looking for another workflow to send out audio recordings (ie upload audio to S3 and email from there?...)

**Comment by cruzach** [comment]
Can you share the snack's source code link?

**Comment by youngchingjui** [comment]
I've updated my report above with a link to a github repo to the code (I'm not sure how to upload code into Snack...)

Here is the repo: 
https://github.com/youngchingjui/RecordAndEmail

**Comment by cruzach** [comment]
Just tested the snack above in SDK 40 and it's working appropriately, so it looks like this issue was fixed! Please open a new issue if you run into this again
