### ISSUE TITLE
Incorrect Flow type declaration for `moduleId` parameter in `Asset.loadAsync`

### ISSUE THREAD

**Issue by johnneed** [expo/expo#6066]
### Environment

Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @types/react-navigation: ^3.0.8 => 3.0.8 
      expo: ^34.0.0 => 34.0.4 
      react: 16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1

App Targets: iOS, Android

### Steps to Reproduce

1. Create a new App with Tabs using expo init.
2. Install Flow 
3. Install flow-typed
4. Run `flow-typed install` to load the Expo types.
5. Run a flow check against App.js
6. Notice that Flow reports an error on the following snippet from App.js
7. Also notice that flow-typed/npm/expo-asset_v6.x.x.js defines the type for moduleId as 'number | Array<number>'  However the example generated from expo init indicates that the type should be 'string | Array<string>'

Here's the error from my project
```
Cannot call Asset.loadAsync with array literal bound to moduleId because:
 • string [1] is incompatible with number [2] in array element.
 • string [3] is incompatible with number [2] in array element.
 • string [4] is incompatible with number [2] in array element.
 • string [5] is incompatible with number [2] in array element.
 • string [6] is incompatible with number [2] in array element.
 • string [7] is incompatible with number [2] in array element.
 • string [8] is incompatible with number [2] in array element.
 • string [9] is incompatible with number [2] in array element.
 • string [10] is incompatible with number [2] in array element.
 • string [11] is incompatible with number [2] in array element.
 • string [12] is incompatible with number [2] in array element.
 • string [13] is incompatible with number [2] in array element.

      components/app-init/index.js
      23│     }
      24│
      25│     _loadResourcesAsync = async () => Promise.all([
      26│         Asset.loadAsync([
  [1] 27│             require("../../assets/images/circle-turquoise.png"),
  [3] 28│             require("../../assets/images/circle-blue.png"),
  [4] 29│             require("../../assets/images/circle-red.png"),
  [5] 30│             require("../../assets/images/circle-yellow.png"),
  [6] 31│             require("../../assets/images/circle-green.png"),
  [7] 32│             require("../../assets/images/circle-purple.png"),
  [8] 33│             require("../../assets/images/circle-orange.png"),
  [9] 34│             require("../../assets/images/broom.png"),
      35│             require("../../assets/images/robot-dev.png"),
      36│             require("../../assets/images/robot-prod.png"),
 [10] 37│             require("../../assets/images/google-logo.jpg"),
 [11] 38│             require("../../assets/images/facebook-logo.png"),
 [12] 39│             require("../../assets/images/green-up-logo.png"),
 [13] 40│             require("../../assets/images/covered-bridge2.jpg"),
      41│             require("..assets/images/teamwork.jpeg")
      42│         ]),
      43│         Font.loadAsync({
      44│             // This is the font that we are using for our tab bar
      45│             ...Ionicons.font,

      flow-typed/npm/expo-asset_v6.x.x.js
  [2] 48│     static loadAsync(moduleId: number | Array<number>): Promise<Array<void>>;

```

### Expected Behavior

ModuleId should accept types `string | Array<string>`

### Actual Behavior

An error indicating that moduleId should be of type `number | Array<number>`

### Reproducible Demo

This project is open source and can be viewed at : https://github.com/codeforbtv/green-up-app

It seems the solution is to change line 48 of expo-asset_v6.x.x.js from :
`    static loadAsync(moduleId: number | Array<number>): Promise<Array<void>>;`
To:
`   static loadAsync(moduleId: string | Array<string>): Promise<Array<void>>;`

**Comment by tsapeta** [comment]
We use TypeScript for type definitions instead of Flow and so we don't support nor maintain those Flow types. I recommend to use TypeScript — you would get correct type definitions to Expo modules out of the box. Closing this issue 🙂
