### ISSUE TITLE
issue relesing the Build in andoird.react-native expo

### ISSUE THREAD

**Issue by MUNEENDRA2019** [expo/expo#6073]
react-native-expo does not update the code in releasing build android studio and Xcode. successfully run in debug mode but releasing built not use updated code.before and after they migrate the code in 64-bit release build not use updated code.on debugging mode successfully updated the code in debug build .then the time of releasing the APK and IPA file build not updated and not use the updated code. without any showing error. please find this solution as soon as possible

**Comment by cruzach** [comment]
Could you provide a little bit more information? To get a 64-bit compatible binary version, you'll need to update to SDK 33 (at least). You can see steps on how to do this in our [SDK 33 release notes](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c)

By updated code, do you mean native code, or your JS code? The more details you can give, the easier this will be to solve 👍

**Comment by cruzach** [comment]
Closing this for now- if you can fill out the bug report template or provide more details, I'll re-open the issue
