### ISSUE TITLE
v35/ App crash when receive notification foreground

### ISSUE THREAD

**Issue by ya-watanabe** [expo/expo#6081]
## 🐛 Bug Report
When I receive remote notification with "data" when app  is foreground,  the app always crash.
It works when the app is background.

Note;
I use fcm to send notification with device token.
```
curl -X POST --header "Authorization: key=$FIREBASE_SERVER_KEY" \
--Header "Content-Type: application/json" \
https://fcm.googleapis.com/fcm/send \
-d @- << EOF
{
    "to": "$TOKEN",
    "notification": {
      "body": "body",
      "title": "title",
    },
    "data": {
      "body": {
        "somedata": "foo",
        "_displayInForeground": false
      },
    },
    "priority":10,
}
EOF
```

### Environment

```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
      Yarn: 1.17.3 - ~/.nodenv/versions/10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nodenv/versions/10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.8.24 
      @types/react-native: ^0.57.65 => 0.57.65 
      @types/react-navigation: ^3.0.8 => 3.0.8 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.4.1
```

iOS / Standalone

### Steps to Reproduce
 - launch app
 - send notification with data from remote.
 - crash

### Expected Behavior
User can receive 

### Actual Behavior
App crash immediately when receive notification.

### Reproducible Demo
It issue happen only standalone build.

**Comment by ya-watanabe** [comment]
From iOS device log; 

```
-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x28316b360

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x28316b360'
*** First throw call stack:
(0x198319c30 0x1980340c8 0x198217fc0 0x19831e3d4 0x198320570 0x10043a23c 0x19c3c3dd0 0x19c3946f0 0x19b9c59ec 0x19b9c5440 0x19b9c40f4 0x19b9c5360 0x19bf5123c 0x19d483b1c 0x19d4aa128 0x19d48e0f8 0x19d4aa044 0x197fc100c 0x197fc3d50 0x19d4d0384 0x19d4d0030 0x19d4d059c 0x198295260 0x1982951b4 0x198294920 0x19828f7ec 0x19828f098 0x1a23f9534 0x19c3af7ac 0x100258658 0x19810ef30)
```

It works without data payload, and it works with sdk34,
so I guess there's something wrong here; not sure though :(
https://github.com/expo/expo/blob/master/ios/Exponent/Kernel/Services/EXUserNotificationManager.m#L71-L75

**Comment by cruzach** [comment]
Hi, so just to be clear you're not using Expo's push notification system, you're implementing your own? 

If you change your payload to match [this format](https://github.com/expo/expo/issues/5304#issuecomment-520711466), do you still see a crash?

**Comment by ya-watanabe** [comment]
@cruzach 
I am not using Expo's push notification. Insted, using fcm.
I've just checked android and it works correctly.

When I set null "notification" key , notification is not showing.
It is also not work, when I removed "notification" key from payload.

**Comment by cruzach** [comment]
I don't think this is a bug with Expo, I think it's a matter of your payload

Expo expects a specific payload format for Notifications, so if you're not using Expo's push notification service, then you need to tailor your payload to match exactly that. You'll have to take a look at the source code for it (think [this](https://github.com/expo/expo/blob/6a392fca2fa9118b2c30bf7bc14b4c4cf5c66c8e/ios/Exponent/Versioned/Core/Api/EXNotifications.m#L297) will help), but be aware that this is subject to change

**Comment by aonamrata** [comment]
Hi @ya-watanabe  You mentioned that this works for android using FCM but not IOS.
Can you please share your fcm message body? I could not get the data in either case. It just shows notification and opens the app but does not trigger the handler to get notification data.
