### ISSUE TITLE
Expo35 upgrade: 'Unable to create application host.exp.exponent.MainApplication'

### ISSUE THREAD

**Issue by RobFairclough** [expo/expo#6082]
## 🐛 Bug Report
After upgrading to Expo 35 to fix an issue with iOS13 crashes, we're now unable to launch the app on Android. The app seems to run fine in simulator and on devices when run locally, but when we deploy to an SDK it crashes without loading.

### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.4.1

iOs & Android. Issue only present on Android

### Steps to Reproduce

App runs as expected in Simulator and running locally, but crashes when deployed to APK.

### Expected Behavior

App opens successfully

### Actual Behavior

App immediately crashes, <appName> has stopped working
with following error in Logcat:

```
FATAL EXCEPTION: main
Process: com.app.appdroid, PID: 10260
java.lang.RuntimeException: Unable to create application host.exp.exponent.MainApplication: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.f
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5678)
    at android.app.ActivityThread.-wrap2(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6524)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.f
    at host.exp.exponent.l.a.a(NativeModuleDepsProvider.java:12)
    at host.exp.exponent.l.a.b(NativeModuleDepsProvider.java:2)
    at f.a.a.b.<init>(Exponent.java:9)
    at f.a.a.b.a(Exponent.java:4)
    at host.exp.exponent.d.onCreate(ExpoApplication.java:9)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5659)

```

Unfortunately not able to share a reproducible demo

**Comment by cruzach** [comment]
Sorry, you're running into this, a similar error message was [reported a while ago](https://github.com/expo/expo/issues/3934), and OP shared their fix so that might be worth a look.

Is this a managed workflow project? If it is, you could try running locally in production mode with `expo start --no-dev --minify`

**Comment by abowerman** [comment]
I'm running into exactly this as well.

**Comment by RobFairclough** [comment]
The issue for us turned out to be two things:
 A package duplicated during our upgrade to Expo 35 - We'd commented it out in build.gradle and mainapplication.java but we'd missed out settings.gradle and we were getting an error:
```
Program type already present: com.facebook.react.uimanager.UIManagerReanimatedHelper
``` 
- we ended up just removing the file in question based on some advice on another issue which seemed to work for local testing but again not in APK releases. 

When we put the file back in, we went back to the old error and eventually found that commenting the line in settings.gradle fixed our issue.

For anyone else encountering the same thing: we had to comment out:

in settings.gradle lines 4 and 5
```
// include ':react-native-reanimated'
// project(':react-native-reanimated').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-reanimated/android')
```
app/build.gradle line 108 in dependencies
```
    // implementation project(':react-native-reanimated')
```

mainapplication.java
line 17 
```
// import com.swmansion.reanimated.ReanimatedPackage;
```
and line 32, within the getPackages function
```
            // new ReanimatedPackage(),
```

Note that there was a few other packages causing us issues earlier on that we had correctly removed so there might be others to remove if you still have trouble after this.

@cruzach  Thanks for the suggestion! If we'd have seen this earlier on it would've sped up the debugging a ton! We were constantly redeploying apks to our device to get the production version 🤦‍♂️ didn't even think of enabling minify

**Comment by cruzach** [comment]
@RobFairclough I'm planning to do a rewrite of our `Development` docs page to include instructions on running in production this week, so it'll be easier to find 👍

**Comment by abowerman** [comment]
I still have this issue even after removing *all* my native dependencies

**Comment by abowerman** [comment]
Unfortunately I had to remove expo/expokit from the project, no issues with bare RN app.
