### ISSUE TITLE
FlashMode in BarCodeScanner : expo-camera

### ISSUE THREAD

**Issue by adarshsripathyrao** [expo/expo#6084]
I am not able to enable flash while scanning barcodes via expo-camera. 

Have attached my code below, is it something that I am doing wrong or is there no support for it currently?

<Camera
        style={{ height: Dimensions.get("window").height / 4 }}
        flashMode={Camera.Constants.FlashMode.on}
        ratio="3:4"
        onBarCodeScanned={e => this.onScan(e)}
        barcodeTypes={Object.values(BarCodeScanner.Constants.BarCodeType)}>

**Comment by cruzach** [comment]
Thanks for reporting this! Closing in favor of https://github.com/expo/expo/issues/6086 since i provide a repro there
