### ISSUE TITLE
expo-facebook "Sign In Using Facebook App" not working...

### ISSUE THREAD

**Issue by arshiuh** [expo/expo#6089]
### Environment

Expo CLI 3.4.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

App target: iOS and Android

### Steps to Reproduce
[https://cdn.discordapp.com/attachments/469170673533583361/637336561679335436/video0.mp4](url)
### Expected Behavior

It is supposed to redirect me to my app and sign me into the app.

### Actual Behavior

Blank screen after clicking "Sign in using Facebook App"

### Reproducible Demo

`async function signInWithFacebook() {
  const appId = "538720086941899";
  const permissions = ["public_profile", "email"];

  const { type, token } = await Facebook.logInWithReadPermissionsAsync(
    appId,
    { permissions }
  );

  switch (type) {
    case "success": {
      await firebase
        .auth()
        .setPersistence(firebase.auth.Auth.Persistence.LOCAL); 
      const credential = firebase.auth.FacebookAuthProvider.credential(token);
      const facebookProfileData = await firebase
        .auth()
        .signInAndRetrieveDataWithCredential(credential); 

      return Promise.resolve({ type: "success" });
    }
    case "cancel": {
      return Promise.reject({ type: "cancel" });
    }
  }
}`

**Comment by ImAbhishekTomar** [comment]
i am facing same issue... in expo 35 and IOS 13

**Comment by cruzach** [comment]
@arshiuh is this issue different from https://github.com/expo/expo/issues/4701 ? If not, it's better to close this and instead provide more information on the original issue

**Comment by danmaas** [comment]
If this is a managed build, double-check your settings in app.json (facebookAppId, facebookScheme). If it's a bare build, check AndroidManifest.xml and Info.plist because there are a bunch of settings that need to exist in order for the FB SDK to work. (this is documented on Facebook's Android/iOS SDK setup instructions).

**Comment by cruzach** [comment]
Closing in favor of https://github.com/expo/expo/issues/6112
