### ISSUE TITLE
Improve Audio prepareToRecordAsync error message when `allowsRecording: false`

### ISSUE THREAD

**Issue by DLesage25** [expo/expo#6096]
### Environment

  ```
Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.16.2 - ~/.nvm/versions/node/v8.16.2/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.2/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.12.0 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.4.1
```
Target: Managed App

### Steps to Reproduce
The error `Error: Prepare encountered an error: recorder not prepared.` surfaces when attempting to prepare a new instance of `Audio.Recording()`

```
export const recordSound = async () => {
    const recording = new Audio.Recording();
    try {
        let { canRecord, isDoneRecording } = await recording.getStatusAsync();

        await recording.prepareToRecordAsync(
            Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY
        );
        // Error surfaces after trying to prepare recorder

    } catch (error) {
        console.log(`Error while recording ${error}`);
    }
};

```
### Expected Behavior
Should mount the recorder unto memory and subsequently allow the device to record.

### Actual Behavior
An error gets thrown unexpectedly after attempting to prepare the recorder.

**Comment by DLesage25** [comment]
@cruzach I am testing on a physical device. iPhone 7 Plus running iOS13 and the latest version of the expo app

**Comment by cruzach** [comment]
I just tried to repro this and didn't get any error. Could you link a [Snack](https://snack.expo.io/) that reproduces this?

**Comment by DLesage25** [comment]
I couldn't figure out how to see console logs in Snack, but here's exactly the code that I'm using, specifically in `Audio.js`: https://snack.expo.io/rJQVCXScH

**Comment by DLesage25** [comment]
If it's of any help, this is the error that I'm seeing: `Prepare encountered an error: recorder not prepared.`

I'm befuzzled by the fact that the same function that's supposed to prepare the recorder is throwing an error saying the recorder is not prepared.

**Comment by cruzach** [comment]
I've found the problem- 
 you need to call `Audio.setAudioModeAsync` before calling `prepareToRecordAsync`

**Comment by cruzach** [comment]
As for right now, you need to include [all the keys](https://docs.expo.io/versions/latest/sdk/audio/#arguments-1) when you call `setAudioModeAsync`, but we've changed it to auto-fill with default values for SDK 36.

**Comment by DLesage25** [comment]
That worked, thank you. I found it interesting to have to include android keys as well, even if the project I'm working in is intended for iOS only.

**Comment by chalarlie** [comment]
I'm getting the same issue here and have followed all of the steps above. I'm on a Bare app initialized using Expo 35, so my package.json has the following dependencies:

`"dependencies": {
    "expo": "^35.0.0",
    "expo-av": "^7.0.1",
    "expo-file-system": "^7.0.0",
    "expo-font": "^7.0.0",
    "expo-permissions": "^7.0.0",
    "firebase": "^7.2.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "0.59.10",
    "react-native-ble-plx": "^1.1.0",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.4.1",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-picker-select": "^6.3.3",
    "react-native-reanimated": "~1.3.0",
    "react-native-router-flux": "^4.0.6",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-stopwatch-timer": "^0.0.21",
    "react-native-unimodules": "0.6.0",
    "react-native-web": "^0.11.7",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  },`

I'm trying to record audio while playing sound at the same time using code I've used in the past that worked flawlessly (this app has been upgraded from a managed app using Expo 32). However, I'm getting the "recorder not prepared" error. I've followed the steps above (not testing in a simulator, using all of the keys for setAudioModeAsync) to no avail. Can someone take a look at my code and tell me if I'm missing something obvious? It never makes it past the call to "prepareToRecordAsync", throwing "Error: Prepare encountered an error: recorder not prepared." 

`
async componentDidMount() {
    this.soundObject = new Audio.Sound();
    this.recording = new Audio.Recording();
    
    try {
      const { status } = await Permissions.getAsync(Permissions.AUDIO_RECORDING);
      if (status !== 'granted') {
        console.log('no recording permission');
        return;
      }

      const { songToRecord } = this.props;

      await Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
        allowsRecordingIOS: true,
        staysActiveInBackground: false,
        interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
        shouldDuckAndroid: true,
        interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
        playThroughEarpieceAndroid: true,
      });

      console.log('recording created');

      await this.recording.prepareToRecordAsync(Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY);
      
      console.log('prepared');
      await this.soundObject.loadAsync(songToRecord.audio);
      await this.soundObject.playAsync();

      console.log('playing');

      // Set a timeout to start recording the voice so that the long intro
      // doesn't cause silence
      setTimeout(async () => {
        await this.recording.startAsync();
        console.log('started recording');
      }, songToRecord.introTime);

      this.timeNextPhrase();
    } catch (error) {
      // An error occurred!
      console.log(error);
    }
  }
`

**Comment by phillipb** [comment]
I also get this error on ios 13 when running the example app. I think there's an actual bug here at least on ios 13

**Comment by ronaiza-cardoso** [comment]
I'm also getting this issue: https://github.com/expo/expo/pull/9612#issuecomment-694907969
