### ISSUE TITLE
Authorization Header not sent

### ISSUE THREAD

**Issue by mrdezzods** [expo/expo#61]
I am using exponent 14.0.0. When I make a request to my api backend, the Authorization header is not sent. From the code below, I can read the header Test in my django backend but not the header Authorization. If I send the same headers using postman, the Authorization header is there
```
        let headers = {
            'method': 'get',
            'headers': {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': 'Basic' + authToken,
                'Test': 'Token ' + authToken
            }
        };
        let url = baseUrl + uri;

        console.log(url, headers);

        return fetch(url, headers)
            .then(response => {
                console.log(response);
                return response.json();
            });
    }
```

**Comment by charlesvinette** [comment]
Hi @mrdezzods, thanks for reaching out. I actually had a similar issue last week and it turned out to be an issue with fetch interaction with CORS.

Read more here http://stackoverflow.com/questions/34662288/setting-authorization-in-native-browser-fetch
