### ISSUE TITLE
[feature-request] exit app

### ISSUE THREAD

**Issue by salzhrani** [expo/expo#610]
Hello,
We faced an issue with `I18nManager.forceRTL` where a restart is required to apply the direction change and `Expo.Util.reload()` does not suffice. there are modules like [react-native-exit-app](https://github.com/wumke/react-native-exit-app) that does that and I was hoping that a similar API is available in expo without the need to eject.

**Comment by jimmylee** [comment]
I wish I had a better solution for you but your best bet is to make a feature request on canny, where we prioritize supporting features you normally have to eject to have. https://expo.canny.io/feature-requests
