### ISSUE TITLE
Uncaught Error: TypeError: undefined is not an object (evaluating 'Expo.ScreenOrientation.allowAsync')

### ISSUE THREAD

**Issue by codedisco** [expo/expo#6104]
Error:
> Uncaught Error: TypeError: undefined is not an object (evaluating 'Expo.ScreenOrientation.allowAsync')

Relatively new Expo user here. After updating a project to a more recent version, the app that I'm working on gets hung up on this screen orientation error. Not sure what I need to do to correct the issue.

Any help would be greatly appreciated!

![emm-error-2019-10-28](https://user-images.githubusercontent.com/49171821/67717605-71295e00-f9a4-11e9-8e54-6b784c25a820.png)

**Comment by cruzach** [comment]
Looks like you're still using the old API syntax. A few SDKs ago (believe it was 33) we changed our imports from the `expo` package to smaller modularized imports. I'm guessing you upgraded that import syntax, but forgot to update all your API calls (moving from `Expo.ScreenOrientation.allowAsync` to `ScreenOrientation.allowAsync`). This is assuming you've already updated import syntax from `import * as Expo from 'expo''` to `import { ScreenOrientation } from 'expo'` along with the particular imports of any other expo libraries you're using in that file

**Comment by codedisco** [comment]
Thanks for the help @cruzach! We're all good on the import sytax front, but after updating the API calls we're getting a new error. It seems like there might be an error in a way that we're implemented screen orientation.

Error:
![image](https://user-images.githubusercontent.com/49171821/67719228-cca91b00-f9a7-11e9-8b5b-a6c26560d61a.png)

Code:
`ScreenOrientation.lockAsync(ScreenOrientation.Orientation.LANDSCAPE);
    if (!this.state.isReady) {
      return <Expo.AppLoading />;
    }
    ScreenOrientation.lockAsync(ScreenOrientation.Orientation.LANDSCAPE_LEFT);
    return (
...`
