### ISSUE TITLE
WebBrowser presentation styles on iOS

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#6109]
We should support full screen in addition to modal presentation, because the modal presentation isn't ideal for some use cases on iOS 13.

## iOS 13

<img width="483" alt="Screen Shot 2019-10-28 at 19 39 17" src="https://user-images.githubusercontent.com/90494/67733126-a80a6e80-f9ba-11e9-88fb-4a5acef8526c.png">

## iOS 12

<img width="447" alt="Screen Shot 2019-10-28 at 19 42 48" src="https://user-images.githubusercontent.com/90494/67733703-59f66a80-f9bc-11e9-8513-a95e67c50ccb.png">

**Comment by mmurphyalo** [comment]
+1 for this. I have a dark themed app that would be better suited for the full screen option because the top white portion cannot be styled. 
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-28 at 22 27 56](https://user-images.githubusercontent.com/35151017/67734274-f88fc500-f9d6-11e9-8395-634f5aa5f66c.png)

**Comment by MarkMurphy37** [comment]
+1 for this. I have a dark-themed app that would be better suited for the full screen option because the top white portion cannot be styled.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-28 at 22 27 56](https://user-images.githubusercontent.com/20745354/67734323-2117bf00-f9d7-11e9-8ec8-3ab35b1ffe6e.png)

**Comment by brentvatne** [comment]
@MarkMurphy37 - you can style that now on sdk 36 by adding a background color to the root view using app.json:

```
{
  "expo": {
    "backgroundColor": "#000000"
  },
}
```

**Comment by MarkMurphy37** [comment]
@brentvatne Awesome! Thank you! Are there any plans to add the full screen option in the future as well?

**Comment by brentvatne** [comment]
yeah we're considering that in our scoping for sdk 37 right now

**Comment by pdugan20** [comment]
@brentvatne I tried adding the backgroundColor property as both a child of expo and of ios in app.json and it's still only showing as white even with SDK 36. I also don't see it listed in the docs: https://docs.expo.io/versions/latest/workflow/configuration/. Is there currently a way to change the rootview to a color other than white?

**Comment by brentvatne** [comment]
@pdugan20 - run this example to see it in action: https://github.com/brentvatne/example-6109

i'll update that docs page

**Comment by pdugan20** [comment]
@brentvatne ah bummer, I thought this updated the rootview of the app but that still defaults to white. Any idea when true background color support will be added?

<img width="407" alt="Screen Shot 2019-12-18 at 5 52 01 PM" src="https://user-images.githubusercontent.com/1837100/71138117-41861d80-21bf-11ea-950c-817bfb04b1dd.png">

**Comment by brentvatne** [comment]
hm ok. i was not aware of this case not being supported - we set the background color of the root react view but apparently we should do more than that. i'll make an issue

**Comment by brentvatne** [comment]
@pdugan20 - are you on sdk36? can you share the exact code that reproduces the issue you screenshotted?

**Comment by brentvatne** [comment]
this is resolved in sdk36. we don't give an option to toggle between the presentation styles but they are now consistent between ios12 and 13. https://github.com/expo/expo/commit/3f901cf5ca6255d46b89808ceb431136e228945d#diff-df2ef22908105fdda98715793ba0a54f

**Comment by pdugan20** [comment]
@brentvatne yup I'm on SDK36! Anytime you have a modal using presentationStyle='pageSheet' it exposes a white background that sits behind the view backgroundColor gets applied to.

A bit of a separate issue, but it also looks like the expo WebBrowser component inherits the system default statusbar light/dark style, which means that you can't see the statusbar depending on whether you set the toolbarColor to a light or dark color.

That wasn't an issue until it switched to a fullscreen modal treatment in SDK36

**Comment by brentvatne** [comment]
ah, so the issue you are encountering is with the react-native `Modal` component using `presentationStyle='pageSheet'` and not the web-browser component then?

> A bit of a separate issue, but it also looks like the expo WebBrowser component inherits the system default statusbar light/dark style, which means that you can't see the statusbar depending on whether you set the toolbarColor to a light or dark color.

yeah let's add a separate issue for that

**Comment by pdugan20** [comment]
@brentvatne that's all correct! Thanks for all of your help with this let me know how else I can assist. Also would love to be able to track the issues once they get filed!

**Comment by brentvatne** [comment]
I created an issue for the Modal presentationStyle problem: https://github.com/expo/expo/issues/6585

Can you create one with more info on the WebBrowser status bar concerns you have? Thanks!

**Comment by pdugan20** [comment]
Happy to do that. Opened a second issue here: https://github.com/expo/expo/issues/6588. Thanks again for your help.

**Comment by brentvatne** [comment]
thank you @pdugan20!
