### ISSUE TITLE
Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.100:19000 flg=0x10000000 }

### ISSUE THREAD

**Issue by a-eid** [expo/expo#611]
I'm trying to launch either the android emulator or genymotion , I have been following the docs and resolved most of the issues but still getting the following error 

`Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.100:19000 flg=0x10000000 }` 

which does not make sense to me ... 

any help appreciated ... thanks

**Comment by terribleben** [comment]
Hi, did the Expo app manage to install on the emulator before running that command? It sounds like it can't find the Expo app to open.

Just double checking, have you followed [this guide](https://docs.expo.io/versions/latest/guides/genymotion.html#content)?

**Comment by terribleben** [comment]
Closing because we didn't get any other info about the issue. Let me know if you're still having trouble.

**Comment by testbil5656** [comment]
I am facing same issue.

**Comment by brentvatne** [comment]
you probably need to reinstall the android app, you can do it with `expo install:android` then try opening it again
