### ISSUE TITLE
[web] expo-calendar support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6118]
Create an API for linking to a populated native calendar app.

**Comment by agar23** [comment]
@EvanBacon would like to take this up? any guidance on where to start/requirements?

**Comment by EvanBacon** [comment]
Invoking `createEventAsync` would deep link you into a calendar app with some of the fields pre-populated.

**Comment by iainnash** [comment]
I can try to work on thiss iif @agar23 hasn't already.
