### ISSUE TITLE
[android] Fix RedBox in older SDK versions on master

### ISSUE THREAD

**Issue by esamelson** [expo/expo#6120]
currently, running an SDK 35 project that should show a redbox error causes the Expo app to crash with

```
10-29 11:23:31.424 24460 24460 E AndroidRuntime: java.lang.NoSuchFieldError: No static field rn_redbox_copy_button of type I in class Labi35_0_0/com/facebook/react/R$id; or its superclasses (declaration of 'abi35_0_0.com.facebook.react.R$id' appears in /data/app/host.exp.exponent-b_IzqWiJUyHZBnBetVrGcw==/base.apk!classes3.dex)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at abi35_0_0.com.facebook.react.devsupport.RedBoxDialog.<init>(RedBoxDialog.java:292)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at abi35_0_0.com.facebook.react.devsupport.DevSupportManagerImpl$5.run(DevSupportManagerImpl.java:411)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-29 11:23:31.424 24460 24460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

This is probably due to something in the RN 0.61 upgrade - need to figure out what's causing this and how to fix it

edit: https://github.com/expo/react-native/commit/d338a60cbe5e438d407a560b16ece40e2c0ad6d7 looks like this commit removed the id in question from RN 0.61. need to determine why we aren't using versioned xml resources

**Comment by sjchmiela** [comment]
Both old and new React Natives share one layout `redbox_view`: one has the `_copy` button, the other has not.

According to https://stackoverflow.com/a/19355128/1123156, when resource names collide, only one of the resources gets bundled into application, in that case it's the new `redbox_view` (without `_copy`).

My guess is that since the only reference to the `_copy` button was in `redbox_view` and we just removed it, AAPT removes the obsolete `R` value too.

**Comment by sjchmiela** [comment]
A hotfix would be to prefix `redbox_view.xml` with `versioned_`, so the whole diff would look like:

```diff
diff --git a/android/ReactAndroid/src/main/java/com/facebook/react/devsupport/RedBoxDialog.java b/android/ReactAndroid/src/main/java/com/facebook/react/devsupport/RedBoxDialog.java
index bf509d3345..6e22a33443 100644
--- a/android/ReactAndroid/src/main/java/com/facebook/react/devsupport/RedBoxDialog.java
+++ b/android/ReactAndroid/src/main/java/com/facebook/react/devsupport/RedBoxDialog.java
@@ -235,7 +235,7 @@ import org.json.JSONObject;
 
     requestWindowFeature(Window.FEATURE_NO_TITLE);
 
-    setContentView(R.layout.redbox_view);
+    setContentView(R.layout.versioned_redbox_view);
 
     mDevSupportManager = devSupportManager;
     mDoubleTapReloadRecognizer = new DoubleTapReloadRecognizer();
```
```diff
diff --git a/android/ReactAndroid/src/main/res/devsupport/layout/redbox_view.xml b/android/ReactAndroid/src/main/res/devsupport/layout/versioned_redbox_view.xml
similarity index 100%
rename from android/ReactAndroid/src/main/res/devsupport/layout/redbox_view.xml
rename to android/ReactAndroid/src/main/res/devsupport/layout/versioned_redbox_view.xml
```

This has let me run Expo client from `master` and not experience crash when `console.error`ing on both SDK35 and UNVERSIONED projects. All the buttons remained working.

The best solution would be to prefix all the resources with some string and, when versioning it too. We could use https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.LibraryExtension.html#com.android.build.gradle.LibraryExtension:resourcePrefix to ensure that all the resources are prefixed.

In fact, I will make this change in `expo/react-native` right now. Then we may see if we would like to try to upstream it to `facebook/react-native`. In general it's a good practice to have the resources prefixed as stated by Android Studio, so we may try.

> In Gradle projects you can specify a resource prefix that all resources in the project must conform to. This makes it easier to ensure that you don't accidentally combine resources from different libraries, since they all end up in the same shared app namespace.

**Comment by sjchmiela** [comment]
Fixed in https://github.com/expo/expo/commit/43e091f5c250808697c6718c828b0573fb1e3694
