### ISSUE TITLE
Improve developer menu ergonomics

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#6122]
- Why is it "Toggle Element Inspector" and not "Show" or "Hide" depending on whether it's visible?
- Provide more information for each item and link out to debugging documentation
- Add icons where none

<img width="483" alt="Screen Shot 2019-10-29 at 15 41 51" src="https://user-images.githubusercontent.com/90494/67814920-adbb8f00-fa62-11e9-9207-7a88270bba2e.png">

**Comment by EvanBacon** [comment]
Completed by @tsapeta
