### ISSUE TITLE
Show some UI when fast refresh is triggered

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#6124]
Currently we don't show the "Refreshing" overlay when Fast Refresh starts to refresh. We should probably show this or something like it. I'm not sure if this is a launch blocker.

<img width="340" alt="Screen Shot 2019-10-28 at 21 08 39" src="https://user-images.githubusercontent.com/90494/67737147-5e745080-f9c7-11e9-8ae4-6a15ca390ace.png">

Android uses a 'toast' and it shows up just fine, so this is just an iOS issue.

**Comment by cruzach** [comment]
addressed by https://github.com/expo/expo/pull/6209
