### ISSUE TITLE
EXImageManipulatorModule.m line 322 crash

### ISSUE THREAD

**Issue by DallAcqua** [expo/expo#6135]
Good Afternoon people.

I have an expo project that uses firebase, when i use it's crashlytics resource it shows me that the project is getting an error at:

```
Fatal Exception: NSInvalidArgumentException
-[__NSDictionaryM isEqualToString:]: unrecognized selector sent to instance 0x282c242a0

EXImageManipulatorModule.m - line 322
-[EXImageManipulatorModule flipImage:flipType:] + 322
```

A few users of my project are getting this error which i cannot reproduce. It only happens on IOS.

Don't even know where to start, it seems that no one here is getting errors in that file.

Thanks.

**Comment by sjchmiela** [comment]
Are you sure that the value passed under `flip` key is a string?

**Comment by DallAcqua** [comment]
That was it!, apparently the documentation had changed, so we were passing wrong parameters.

Thanks.
