### ISSUE TITLE
[Solved] One Notification Token notifies multiple devices

### ISSUE THREAD

**Issue by dhcmega** [expo/expo#6137]
Hi!
I'm completely puzzled with this. If I send a notification to a token using the expo web tool, it goes to the correct device.
If I do it with guzzle from my laravel project, it goes to all my devices.
How is this event possible? I'm 100% sure I'm only sending it to one token!
Any help would be appreciated.
Thanks!

EDIT1: I have 3 devices, each with its own notification token. I have just realized that all the notifications are crossing. I have deleted 2 tokens from my database and push to only one. The one with the token used received twice, the other only one. If I push to the three of them, I get duplicated notifications in all of them.

SDK 35

App is standalone downloaded as beta tester from Google Play.
Also texto is always 1 black and 1 blue
Example:
![Screenshot_2019-10-31-00-35-31-764_com miui home](https://user-images.githubusercontent.com/6719578/67917335-74287800-fb77-11e9-8515-508d6d83d437.png)
![Screenshot_20191031-003610](https://user-images.githubusercontent.com/6719578/67917345-77bbff00-fb77-11e9-865d-1efa7bcc942e.png)

EDIT2: This is the info I'm sending:
```
[2019-10-31 00:39:17] prod.DEBUG: Sending notification: array (
  0 => 
  array (
    'data' => 
    array (
      'notification_id' => 162225,
      'account_id' => 1,
    ),
    'title' => 'Invitación aceptada',
    'body' => 'Johnny Bravo aceptó su invitación para concurrir el jueves 31 de octubre 2019.',
    'sound' => 'default',
    'priority' => 'high',
    'to' => 'ExponentPushToken[VAUF**************_UG6]',
    'badge' => 5,
  ),
)
[2019-10-31 00:39:18] prod.DEBUG: Execution time for Expo Notification(162225): 0,350s 
``` 

EDIT3: On one phone I have deleted all my app data, re logged in, a new token was created and uploaded to my server. I have sent a notification to that brand new token and my other android phone also received. The only thing in common I can think of is my google account, is this related?

EDIT4:
MYSTERY SOLVED!
The app was originally a react native app, using FCM topics for notifications. Now it's an EXPO app using Expo for notifications. Somehow the app is still enrolled with the topics and that was the notifications it was receiving.

**Comment by AdamJNavarro** [comment]
Glad you got to the bottom of things, @dhcmega. Thanks for sharing the answer with us as well!
