### ISSUE TITLE
Build Stuck :  iOS: There was an error with this build.  Cannot start new build, as there is a build in progress.

### ISSUE THREAD

**Issue by jpca999** [expo/expo#614]
I dont understand whats going on..  It works sometimes and quite often doesnt. 

For creating the build, is there an alternative to expo (command line) ?

![image](https://user-images.githubusercontent.com/1026325/30240800-3444e97a-9545-11e7-9819-3d6e6510ebc0.png)

![image](https://user-images.githubusercontent.com/1026325/30214411-63c7f56e-947a-11e7-8037-7e4ad77242b8.png)

![image](https://user-images.githubusercontent.com/1026325/30214339-0a44f726-947a-11e7-96f9-28ab6e3a8f3b.png)

{
    "expo": {
    "name": "app",
    "description": "app App",
    "slug": "recherry",
    "privacy": "public",
    "sdkVersion": "20.0.0",
    "version": "1.0.5",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true
    },
    "ios": {
          "bundleIdentifier": "com.app.exp",
          "supportsTablet": true
    },
    "android": {
       "package": "org.app.exp",
     }
  }
}

**Comment by dikaiosune** [comment]
Hi! Sorry about the delay here. It looks like our devtools weren't able to find your icon: `Invalid URI "./assets/icons/app.png"`. Sorry about the poor error, we're working to improve these going forward.

**Comment by jpca999** [comment]
Cool I fixed that ./assets/icons/app.png  issue,   but the build is still stuck, can you please clear it ?

![image](https://user-images.githubusercontent.com/1026325/30241968-623bb9e2-955b-11e7-8065-041bd34fa42e.png)

**Comment by dikaiosune** [comment]
Oh, sorry about that. I cleared the failed job.

**Comment by jpca999** [comment]
@dikaiosune  Okay, so after all the cleanup, When I re-try the doing the exp: build:ios  I still get the status = undefined. 

What could be the issue ?
![image](https://user-images.githubusercontent.com/1026325/30242725-e36645ec-9569-11e7-8484-df9b4c7acbaa.png)

![image](https://user-images.githubusercontent.com/1026325/30242726-eba84606-9569-11e7-9a5e-d9ebbeb10c81.png)


app.json 


{
    "expo": {
    "name": "myapp",
    "description": "myapp App",
    "slug": "recherry",
    "privacy": "public",
    "sdkVersion": "20.0.0",
    "version": "1.0.5",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true
    },
    "ios": {
          "bundleIdentifier": "com.myapp.exp",
          "supportsTablet": true
    },
    "android": {
       "package": "org.myapp.exp",
     }
  }
}

**Comment by skevy** [comment]
Hi @jpca999 -

The error from the builder still has to do with not being able to resolve the icon.

You're positive that the icon you've specified in app.json exists and is in `./assets/icons/app.png`, and your loading icon is in `./assets/icons/loading.png`?

Also, I noticed that in your app.json you have the `ios` key defined twice.

**Comment by koushikmohan1996** [comment]
Am having similar issue, can you please check it

Build ID: 3b8c5dee-41d8-4c5c-9566-99c083f16ca2

**Comment by jengjeng** [comment]
I have fixed this issue by resizing&crop the app images/icons to square ratio.
(From [Expo Doc](https://docs.expo.io/versions/latest/guides/configuration.html#icon) that show we can't use an image as the icon above size 512x512 px.)

So, about the size of my images.
e.g.
> assets/icons/app-icon.png => 512x512 px
> assets/icons/loading-icon.png => 500x500 px
> assets/icons/notification-icon.png => 144x144 px

**Comment by jpca999** [comment]
K

**Comment by esoytekin** [comment]
Hi, i am having the same issue. Build is in progress for two days now.
Can you please check it?

**Comment by ide** [comment]
We've cleared out standalone app builds that have been stalled for more than three hours. If your build didn't succeed you can try again.

**Comment by manoj-nama** [comment]
Hi, I also am having this issue with my build. Android build is stuck in progress. Can someone clear it up. My expo username is `@manoj.nama`.
Thanks.

**Comment by tusharchutani** [comment]
Hi there same issue here my username is @tusharchutani on expo 

thanks
