### ISSUE TITLE
expo install react-native-svg installs an incompatible version

### ISSUE THREAD

**Issue by maxwedwards** [expo/expo#6142]
### Environment

```
Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.4.1
```

### Steps to Reproduce

`expo install react-native-svg` will install a minor patch of react-native-svg that is not compatible. `"~9.9.2"` is added to my package.json but version `"9.9.9"` is actually what gets installed by yarn. This version causes the following bugs: https://github.com/awesomejerry/react-native-qrcode-svg/issues/67 and https://github.com/react-native-community/react-native-svg/issues/1175

### Expected Behavior

Rather than just submit a PR to fix the version, I'm creating this issue as I see that all packages in the bundled packages file allow patch version changes (they have the tilde symbol). Also I see that there was a recently accepted PR bumping the version from `"~9.9.2"` to `"~9.9.5"` (https://github.com/expo/expo/pull/5770/files) and I wouldn't want to undo that.

Both `9.9.2` and `9.9.5` versions appear to work for me. Version `9.9.9` does not.

### Reproducible Demo

`Rect` is not working for me with version `9.9.9`.

Whilst this works:

```           
<View>
  <Svg height="100" width="100">
    <Circle cx="50" cy="50" r="50" fill="pink" />
  </Svg>
</View>
```

This does not display:

```            
<View>
  <Svg height="100" width="100">
    <Rect x='15' y='15' width='100' height='100' stroke='red' strokeWidth='2' fill='yellow' />
  </Svg>
</View>
```

The fix for me seems to be to just fix the version at `"9.9.5"`.

**Comment by cruzach** [comment]
Is this happening on both iOS and Android for you? There was another issue opened for problems using a certain version of `react-native-svg`, but I think it was specific to Android and on any version over `react-native-svg v9.9.2`

**Comment by maxwedwards** [comment]
Just Android. iOS worked ok. `9.9.5` works ok but `9.9.9` does not.

**Comment by cruzach** [comment]
Thanks for reporting this, just tested in both the Expo Client and standalone and I'm seeing crashes 

You're just seeing a blank screen, no crash?

**Comment by cruzach** [comment]
Hey @maxwedwards, just fixed and published this. With `expo` package v35.0.1, when you run `expo install react-native-svg` it will pin 9.9.5

**Comment by maxwedwards** [comment]
@cruzach great news, thanks for pinning. Good luck upgrading this in the future! The latest version of `react-native-svg` seems to still have the problem.

I have seen crashes when using certain svg elements, can't reproduce at the moment. The crash was a null reference IIRC. The simple example above using a `Rect` just produces a blank screen for me.

**Comment by chschafl** [comment]
I am still seeing a blank screen with 9.9.5 on the Android emulator.

**Comment by maxwedwards** [comment]
@chschafl apologies if you've already checked but have you confirmed it's `9.9.5` that has been installed in `node_modules` and rn-svg isn't using a different version.

**Comment by cruzach** [comment]
If you still see the blank screen, please share the code that causes it to break so I can repro

**Comment by Dyshay** [comment]
@cruzach 9.9.5 is not working for me but 9.9.2 is good
