### ISSUE TITLE
expo bare workflow can't use nativemodule

### ISSUE THREAD

**Issue by kangbb** [expo/expo#6143]
### Environment

```sh
Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
```

### Steps to Reproduce

I want to use a native module, so I tried to use `expo bare workflow`. The native module is simple, just refer to:

[https://github.com/mitsuruog/react-native-call-native-module-sample](https://github.com/mitsuruog/react-native-call-native-module-sample)

Actually, the initial project works well. But I use:

```sh
expo init --template bare-minimum
```  
It doesn't work any way.

### Expected Behavior

Use a react native `native module`.

### Actual Behavior

I can't get a native from `NativeModules`, which from `react-native`.

**Comment by kangbb** [comment]
Or, is there a mature and success example for this?

**Comment by cruzach** [comment]
Could you provide a few more details? The bare workflow supports adding your own custom native code/modules. We have a [walkthrough for the bare workflow](https://docs.expo.io/versions/v35.0.0/bare/exploring-bare-workflow/) that might help you get started 👍

**Comment by kangbb** [comment]
According to my understanding, `expo  bare workflow` just is much like `react native`, which can use `expo` API by `react-native-unimodules`。So, I can use a `native module` by the way explained in `react native` docs:

[https://facebook.github.io/react-native/docs/native-modules-setup](https://facebook.github.io/react-native/docs/native-modules-setup)

So, I use a native module from npm as following:

1. Open up `android/app/src/main/java/[...]/MainApplcation.java`
  - Add `import com.crypho.scrypt.RNScryptPackage;` to the imports at the top of the file
  - Add `new RNScryptPackage()` to the list returned by the `getPackages()` method
2. Append the following lines to `android/settings.gradle`:
  	```
  	include ':react-native-scrypt'
  	project(':react-native-scrypt').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-scrypt/android')
  	```
3. Insert the following lines inside the dependencies block in `android/app/build.gradle`:
  	```
      implement project(':react-native-scrypt')
  	```

Now, we can use it by:

```js
import { NativeModules } from 'react-native'

const { RNScrypt } = NativeModules

RNScrypt.scrypt(password, salt, N, r, p, token)
```

It comes from: [https://github.com/Crypho/react-native-scrypt/blob/master/README.md](https://github.com/Crypho/react-native-scrypt/blob/master/README.md). And it works for `react-native init` project.

I use a native module that write by myself. the project structure is:

```sh
├──app
│   └── src
│       └── main
│           ├── AndroidManifest.xml
│           ├── java
│           │   └── com
│           │       └── expobareapp
│           │           ├── CounterModule.java
│           │           ├── CounterPackage.java
│           │           ├── generated
│           │           │   └── BasePackageList.java
│           │           ├── MainActivity.java
│           │           └── MainApplication.java
```

Then I add `MainApplication.java` with:

```java
new CounterPackage(),
```

Finally, I use it just like `RNScrypt`.

It's all. What's the difference about native module between `react-native` and `expo bare workflow`?

**Comment by brentvatne** [comment]
there is no difference, you are correct that bare workflow is a plain react-native app. it's just with [react-native-unimodules](https://github.com/unimodules/react-native-unimodules) pre-installed in it

**Comment by brentvatne** [comment]
@kangbb - i added the react-native-scrypt library you mentioned to a brand new project that i init'd with expo-cli, it worked as expected. see https://github.com/brentvatne/expo-issue-6143.
