### ISSUE TITLE
Expo app rejected for Invalid Binary for WebView and user-fonts

### ISSUE THREAD

**Issue by sooperfly563** [expo/expo#6151]
tried uploading an app I created with Expo onto the Apple App Store and 30 minutes later I get an email saying my project has Invalid Binary they provided two reasons behind why it was rejected. 

**Problem 1.** because `Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs`

However from what I've seen on other forums this doesn't usually result in a rejection for Expo projects with SDK ranging from SDK 28 to 35 (my project is running on 33).

**Problem 2** because `Invalid entitlement - The com.apple.developer.user-fonts is valid only for apps build with SDK 13 or later.`

The solution I've found on other forums say that I should go into the developer console and uncheck the 'fonts' section in the Apple Developer section. Upon doing this the problem still persists

I'm not sure what I can do now, I need help

My project is running on SDK 33

**Comment by brentvatne** [comment]
you can ignore problem 1, it's just a warning, and we'll resolve the warning in the next release.

for problem 2, see this issue: https://github.com/expo/expo/issues/5792
