### ISSUE TITLE
Google auth: documentation not clear when using google signing

### ISSUE THREAD

**Issue by michalgarcarz** [expo/expo#6153]
This document:
https://docs.expo.io/versions/v35.0.0/sdk/google/

At the end of the section: "Deploying to a standalone app on Android"
We have the sentence:
"Note that if you've enabled Google Play's app signing service, you will need to grab their app signing certificate in production rather than the upload certificate returned by expo fetch:android:hashes. You can do this by grabbing the signature from Play Console -> Your App -> Release management -> App signing, and then going to the API Dashboard -> Credentials and adding the signature to your existing credential."

That last part of this is completely unclear: "and then going to the API Dashboard -> Credentials and adding the signature to your existing credential". We can not add any signature to existing credentials because we have only one credentials which is "Service account keys" type. Could you please clarify that sentence and explain what should be done here ?
Do you suggest to create a new credential ? Which type ? Do you suggest to edit existing service account key ? (but can not add any signature there.

Thanks,
Michal

**Comment by davidli3100** [comment]
You should build out your expo project, then use the expo cli to get the keys/secrets for that particular build and upload them as security certs on the iOS and Android app section of firebase

**Comment by michalgarcarz** [comment]
Thanks @davidli3100.
Firebase is not mentioned at all in the documentation
https://docs.expo.io/versions/v35.0.0/sdk/google/

I am not using firebase and Facebook is working fine for  both expo and standalone. That is why i do believe documentation for google is broken here.
For Android google is signing my build (not expo) - as per documentation - right ?
So i should not need to upload expo keys/secrets there ? Also there are a lot of questions unclear for example what value should i have in app.json for  "config"/ "googleSignIn"/ "certificateHash" ? (expo hash or google hash ?)

Thanks,

**Comment by davidli3100** [comment]
@michalgarcarz sorry, I assumed you were using the google-sign-in module. If you aren't using firebase for google sign in, then the secrets should go onto your developer console (although that may not be necessary on web, someone correct me if that's wrong)

**Comment by michalgarcarz** [comment]
Thanks @davidli3100 - that is correct - i have all the oauth + api credentials in developer's console as per expo documentation. But still it does not work for native app (works only for expo app). And still multiple answers are not answered (like the mentioned value for certificateHash in app.json).

**Comment by bonafidehan** [comment]
@michalgarcarz did you ever resolve this? Also trying to figure out how to set `certificateHash` in app.json for Google login in standalone Android when using Play's app signing service.

**Comment by SleeplessByte** [comment]
> Note that if you've enabled Google Play's app signing service, you will need to grab their app signing certificate in production rather than the upload certificate returned by `expo fetch:android:hashes`. You can do this by grabbing the signature from Play Console -> Your App -> Release management -> App signing, and then going to the API Dashboard -> Credentials and adding the signature to your existing credential.

In other words, those _signatures_ are the certificate hashes!
