### ISSUE TITLE
infoPlist.NSCameraUsageDescription is not updating on the app

### ISSUE THREAD

**Issue by ozgepoundandgrain** [expo/expo#6154]
## 🐛 Bug Report
Hi all, 
I've changed the info.NSCameraUsageDescription value in the app.json file, changed the expo.version key in app.json, ran `expo build:ios` and then `expo upload:ios`.
However, at no point has the popup message been updated to the string I have in my app.json file.

Am I missing something?

### Environment
expo version 3.4.1
npm version 6.11.3
node version 8.15.0

Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.4 => 34.0.4 
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.8 => 0.59.8 
      react-navigation: ^2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 3.4.1

**Comment by cruzach** [comment]
Have you already uploaded your app manually at least once? We do state in the uploading docs that:
> Note: The expo upload:ios command is temporarily unavailable due to changes in Xcode 11. Until this is resolved, please refer to the Manually uploading your app for the first time section for instructions. If you encounter any issues, please refer to [this thread](https://github.com/expo/expo-cli/issues/927).

But that seems to have been fixed in `expo-cli` v3.2.1

Are you sure that you are running the most recent build of the app?
