### ISSUE TITLE
Error with recordAsync

### ISSUE THREAD

**Issue by perojas3** [expo/expo#6156]
### Environment

```
  Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.6.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1

```
I target Android and IOs, but, for now, I can only test with Android. A Nokia 6.1 phone with API 27. Also tested in a Samsung Galaxy A8 with API 26.
### Steps to Reproduce

The problem occur when trying to record with the function recordAsync.
I have this function:

```
  recordVideo = async() => {
    const cameraPermission = await PermissionService.askRecordingPermission();
    if (cameraPermission.status !== 'granted') {
      return;
    }
    if (this.camera) {
      try {
        const data = await this.camera.recordAsync({});
        this.setState({ isProcesing: true });
        const file = await FileSystem.readAsStringAsync(data.uri, {
          encoding: FileSystem.EncodingType.Base64,
        });
        await this.uploadVideo(data.uri, file);
      } catch (error) {
        console.log(error);
        this.camera.stopRecording();
        this.setState({ cameraIsRecording: false });
        ToastService.showToast('Error: Can't record', 5000, 'warning');
      }
    }
    this.setState({ isProcesing: false });
  };
```
Just like that, an error occur when `await this.camera.recordAsync({});` is reached.

### Expected Behavior

The function should  stop at  `recordAsync` and continue after a `stopRecording` elsewhere in the code is reached. And then continue to retrieve the temporal Uri for later upload the code.

### Actual Behavior

An error is raised instantaneously when `recordAsync`, going directly to the catch. In the Nokia 6.1, the console log in the catch shows this:
```
null
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```
If I try to record a second time the error changes to: 
```
unlock failed
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```
In the Samsung A8 the first time shows this:
```
start failed.
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```
The second one is exactly the same.

Naturally, I am using react navigation. If I ever navigate back from the camera screen after the error occurs, it work for a few moments, then for a split second returns to the camera screen, and then the next error appears:

![Screenshot_20191103-224013](https://user-images.githubusercontent.com/14139107/68096041-ff15b500-fe8c-11e9-851c-095c9f674be4.png)

After this expo stops.

### Reproducible Demo

Attempted to make a reproducible demo in snack:
https://snack.expo.io/@perojas3/authentic-candies
But the error is different there. It change making the screen black after recording.

I suspect that my error may be because the camera options, or a compatibility with the react navigation due to the bug of being unable to go back after it.
Also find this issue with a similar problem:
https://stackoverflow.com/questions/56430983/react-native-camera-recordasync-start-failed-error
But don't know how to solve in expo.

**Comment by cruzach** [comment]
Can you try using [this snack](https://snack.expo.io/@charliecruzan/examplerecordasync) and let me know if you see the same error?

**Comment by perojas3** [comment]
No, the error doesn't show up there.

**Comment by cruzach** [comment]
Then the problem is probably specific to your code, rather than a bug with `recordAsync`

**Comment by perojas3** [comment]
Well. I use your example to find the problem. Thanks.
Apparently, this occurs when you have a "video", from expo-av (https://docs.expo.io/versions/latest/sdk/av/) running somewhere in the app while you call recordAsync.
In my case, I have a video loaded (but no playing) in the previous screen. Solved it by using the navigation events from react-navigation, and unmounting the video components when unfocused.
¿You know why this happens?

**Comment by samuelvisscher** [comment]
@cruzach thanks for providing the snack, this helped me debug a very similar, though odd issue.

I was having a very similar error as the one above, seemingly completely random. It would state: "stop failed.", as also described here:

https://github.com/expo/expo/issues/2579

In the end your snack was working without a problem, which allowed me to identify the problem. When a view with the following styles was present, the error would occur. After removing the View, the issue stopped.

```
android: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 6,
    bottom: 140,
    justifyContent: 'center',
    alignItems: 'center',
    left: Space * 2,
    padding: Space,
    position: 'absolute',
    right: Space * 2,
  },
```

Not sure if it's relevant, but it may save someone else some of the time I wasted ;-)

**Comment by cruzach** [comment]
@samuelvisscher happy I could help! Although that's a very odd issue

@perojas3 could you share a snack that reproduces the case where having a video loaded somewhere in the app prevents you from recording?

**Comment by Fahad-Mahmood** [comment]
> Well. I use your example to find the problem. Thanks.
> Apparently, this occurs when you have a "video", from expo-av (https://docs.expo.io/versions/latest/sdk/av/) running somewhere in the app while you call recordAsync.
> In my case, I have a video loaded (but no playing) in the previous screen. Solved it by using the navigation events from react-navigation, and unmounting the video components when unfocused.
> ¿You know why this happens?

I am also using Video component from expo-av and the error appears if my video component is mounted and I am recording a video. Is there any other solution apart from unmounting your screen?

**Comment by cruzach** [comment]
You could conditionally render the `Video` component based off of some prop you pass down (`isVideoVisible=true` if not recording, `isVideoVisible=false` if you are)

Still need a repro of this

**Comment by Fahad-Mahmood** [comment]
> You could conditionally render the `Video` component based off of some prop you pass down (`isVideoVisible=true` if not recording, `isVideoVisible=false` if you are)

Yes this is what I am doing, don't you think there should be a proper solution to allow this feature?

**Comment by Hiti3** [comment]
I have a very distrurbing issue at hand, if anyone can help I would appreciate it. I record a video like this:  `                await cameraRef.current.recordAsync({maxDuration: 15, mute: true})
                    .then((videoData) => {
                        console.log("res data: " + JSON.stringify(videoData, null, 4));
                        dispatch(saveVideoScan(videoData.uri, props.videoIndex, measurementId, true));
                    });`

In another stateless screen (the same as the one above in which I record video) I display video.uri with Video (from 'expo-av') component. Now the problem is that I display different videos on different screens (you navigate on 4 screens, record 4 different videos (with the above stateless camera function screen) and display the each video on each screen from which you called camera view and recorded the video). AFTER 1ST recording on FIRST SCREEN, I can not record video on different screens, it automatically creates 2 beeps as if he started and instantly stopped the recording... What is going on here? The same issue is I can not upload this video on the server for some reason, it is like such simple functionalities do not work. I am reaching deadline and I am really in need of any suggestions, thank you!

**Comment by amit13091992** [comment]
> Then the problem is probably specific to your code, rather than a bug with `recordAsync`

@cruzach I am trying the same in functional component but this is giving error "Starting video recording failed. Another recording might be in progress". I am little new here could you please help me out?
