### ISSUE TITLE
Error while loading: Could not connect to the server

### ISSUE THREAD

**Issue by ethantran** [expo/expo#616]
I am trying to use my iPhone 6+ with a detached expo project and am stuck on step 3 of https://docs.expo.io/versions/latest/guides/expokit.html

It works on simulator, but I need to use device.

![screen shot 2017-09-08 at 11 57 01 pm](https://user-images.githubusercontent.com/3276358/30237151-8199a1ba-94f1-11e7-91d9-cccbe4285ff7.png)
![file_000](https://user-images.githubusercontent.com/3276358/30237153-990bad48-94f1-11e7-8596-54a9b1364c1e.png)

**Comment by daominhsangvn** [comment]
Try to use Tunnel see if it work

**Comment by dikaiosune** [comment]
Hi! Sorry to hear you're having issues. It looks like XDE has been set to use the localhost network setting, which will only be available to the simulator. If you set it to "LAN" or "Tunnel" you should be able to reach the packager from your physical device. Please post back if this doesn't work though, and we can help you troubleshoot!
