### ISSUE TITLE
[docs] DocumentPicker types has incorrect option

### ISSUE THREAD

**Issue by sospedra** [expo/expo#6160]
Per the DocumentPicker's types selecting **multiple** documents is possible:
https://github.com/expo/expo/blob/master/packages/expo-document-picker/src/types.ts#L4

But this option is not used anywhere inside the `ios` nor `android`.
It neither changes anything if provided to `getDocumentAsync`.

I assume that's because there's no option for multipick.

Am I missing something or we shall remove this attribute?

**Comment by cruzach** [comment]
Looks like [it's used here](https://github.com/expo/expo/blob/master/packages/expo-document-picker/src/ExpoDocumentPicker.web.ts#L19) in the JS source

Although @bbarthec may know if this option should be added to the [docs](https://docs.expo.io/versions/v35.0.0/sdk/document-picker/#arguments)? Happy to add but not sure what is does

**Comment by bbarthec** [comment]
From what I can see `multiple` option is only available on `web` ([see here](https://github.com/expo/expo/blob/6ea39d69a50c58d6725d2a64ba08de66bc82b3b2/packages/expo-document-picker/src/ExpoDocumentPicker.web.ts#L12)). @EvanBacon added this option in https://github.com/expo/expo/pull/3119. I suppose that this should be annotated with `web only`.

**Comment by sospedra** [comment]
Wow, that was fast. Ty folks ❤️
