### ISSUE TITLE
ExpoKit/ expo-branch requires a newer version of RNBranch than react-native-branch requires

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#6165]
### Environment

 Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.4.1

ExpoKit 35 / iOS

### Steps to Reproduce

(first four steps are easy and anyone can see them)
1. Create a new app with `expo-init`
2. CD into folder, run `expo eject`
3. Run `expo install expo-branch`
4. CD into `ios` folder, run `pod install`

(Optional steps below add to understanding of issue, but require valid Branch keys)
5. Configure Branch keys (see https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/tree/v3.1.1#ios-project-configuration)
6. Add `import Branch from 'expo-branch'` to App.js
7. `yarn start` / run app in Xcode

### Expected Behavior

Steps 1-4: Open `ios/Podfile.lock`, see `Branch (0.27.1)` because `expo-branch` requires `react-native-branch` 3.1.1, which requires `RNBranch` Cocoapod version 0.27.1.
Steps 5-7: Run iOS app and don't see any Branch-related console errors

### Actual Behavior

Steps 1-4: Open `ios/Podfile.lock`, see `Branch (0.29.3)`
Steps 5-7: Run iOS app and see the following error:

```
2019-11-04 14:42:09.639 [error][tid:main][RNBranch.m:82] Please use v. 0.27.1 of Branch. In your Podfile: pod 'Branch', '0.27.1'. Then pod install.
```

The app will still proceed to work, and at least some Branch functionality is not affected.

### Reproducible Demo

Unfortunately, this is hard to do in a meaningful way without sharing branch keys or making someone sign up for a Branch account and injecting them. Fortunately, pretty easy to see the mismatch from the `Podfile.lock` alone.

### Discussion

It's not to me clear this has any actual adverse affect on Branch functionality itself. My Branch universal links still work even with this error. That's all I use from Branch, though. Recently, I changed some code to read non-Branch links from my Branch subscription. That worked in ExpoKit 34, but is not in Expo 35 (that said, I can't say for sure this is the problem).

Per, the `react-native-branch` repo, version 3.1.1 is the last version that supports React Native <0.60, and 3.1.1 requires `RNBranch` 0.27.1. So, `expo-branch`/ `EXBranch` is requiring a Cocoapod that Branch does not recommend using against this version of their React Native library.

The most obvious adverse affect at the moment is that, unlike in ExpoKit 34, we cannot just choose to use `react-native-branch` instead. Installing `react-native-branch` 3.1.1 and the corresponding Cocoapod will result in an error like:
```
[!] CocoaPods could not find compatible versions for pod "Branch":
  In Podfile:
    Branch (= 0.27.1)

    EXBranch (from `../node_modules/expo-branch/ios`) was resolved to 1.0.2, which depends on
      Branch

    ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.13.0`) was resolved to 35.0.0, which depends on
      Branch (~> 0.28)

Specs satisfying the `Branch (= 0.27.1), Branch, Branch (~> 0.28)` dependency were found, but they required a higher minimum deployment target.```

**Comment by sjchmiela** [comment]
Thanks for bringing this up, https://github.com/expo/expo/pull/6176 will set the `Branch` dependency requirement to what `react-native-branch` expects.

**Comment by jdponomarev** [comment]
Hey, How do I update to that version?
Should change :git in Podfile to :path and pre-download the repo?

**Comment by sgatenby** [comment]
> Hey, How do I update to that version?
> Should change :git in Podfile to :path and pre-download the repo?

After dancing with the usual version lottery for a few hours, I've managed to work around this by switching to using the expo packaged version. Just change references in your app delegate file from 

react-native-branch/RNBranch.h

to 

EXBranch/RNBranch.h

The javascript references can remain unlinked to react-native-branch.
It's not pretty, but it worked and passed UI tests on click throughs. 

Any other attempts at using both react-native-branch related pods in the project failed due to conflicts.
