### ISSUE TITLE
Supporting payments without detatching to expokit also Web

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo#6166]
I'm currently working on a mobile app and web using Expo v35.0.0, Expo-Cli v3.4.1 and want to integrate payments with stripe.

However, the built-in Expo stripe module requires you to eject to expokit, which I would prefer not to do if possible. I've looked into this library on the official Expo repository: [stripe-expo](https://github.com/expo/stripe-expo) but it seems like it hasn't been updated in a really long time.

Is there a known way of doing this without ejecting? Thanks!

**Comment by cruzach** [comment]
Hi! We like to keep Github reserved for bug reports, so I'm going to close this issue. Questions like this are best posted on our [forums](https://forums.expo.io/).

You'll need to eject to the bare workflow (or Expokit, but we recommend the bare workflow) to integrate payments into your app. We're working hard to bring the bare workflow to feature parity with the managed workflow, so I suggest looking at the [bare workflow docs](https://docs.expo.io/versions/v35.0.0/bare/exploring-bare-workflow/) to get more info on it
