### ISSUE TITLE
FileSystem.downloadAsync can't download images to local cache with long URIs

### ISSUE THREAD

**Issue by paultranzestpost** [expo/expo#6168]
## 🐛 Bug Report

My application fetches a list of image names from the remote server. The program I pasted above tries to download them to the local cache. What I noticed was when the image names are long and have special characters, I get a [Unhandled promise rejection: Error: Unable to download from: (null)] for each download attempt.

Filesystem.downloadAsync failed when the URI is long:
https://gateway.zestpost.com:8443/gateway/images/8db1f9a8-2f9b-4dff-b0e8-79bd49286db4-medium_300x188_->pgammJjIJfOJOmKKvIk5.jpg.jpg
https://gateway.zestpost.com:8443/gateway/images/f2b84d45-0cff-4c81-8700-808dbf1beed9-medium_300x225_->F2ZVPcIVt00QfHRIEdqq.jpg.jpg

[Unhandled promise rejection: Error: Unable to download from: (null)]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals

[Unhandled promise rejection: Error: Unable to download from: (null)]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals

=============================== SOURCE CODE =========================
// Get file path to local cache using remote server URI
export async function getLocalCacheFilePath(uri) {
  // Extract the file name from the URI without the file extension
  const filename = uri.substring(
    uri.lastIndexOf("/"),
    uri.indexOf("?") === -1 ? uri.length : uri.indexOf("?")
  );

  // Extract the file extension from the URI
  const extension =
    filename.indexOf(".") === -1
      ? ".jpg"
      : filename.substring(filename.lastIndexOf("."));

  // File path to cache storage
  const localUri = `${CACHE_DIR}${SHA1(uri)}${extension}`;
  // const localUri = `${CACHE_DIR}${shorthash.unique(uri)}${extension}`;
  const { exists } = await FileSystem.getInfoAsync(localUri);
  console.log(uri);
  if (!exists) {
    const result = await FileSystem.createDownloadResumable(
      uri,
      localUri
    ).downloadAsync();
    // If the image download failed, we don't cache anything
    if (result && result.status !== 200) {
      return undefined;
    }
  }
  return localUri;
}
### Environment

Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
      npm: 6.12.0 - ~/.nvm/versions/node/v12.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1

IOS and Andrea
### Actual Behavior
I get the following error for each download attempt:

[Unhandled promise rejection: Error: Unable to download from: (null)]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals

**Comment by cruzach** [comment]
Looks like it is failing because of the `>` character

According to https://tools.ietf.org/html/rfc3986#section-2.2 , the `>` isn't a valid URI character

**Comment by paultranzestpost** [comment]
Thanks, Cruzach! I'm having the backend team re-encode all the URIs without the ">" character and test my expo code again. I will add my comment afterwards. Thank you so much for your help.

**Comment by paultranzestpost** [comment]
Hi, Cruzach.

Looks like I'm still getting the same "null" error and I am also getting a location error.

https://gateway.mcphagia.com:10000/gateway/images/35f826cd-13a1-4e26-a076-9ae00a335d04-medium_300x168_--jDRatwWvjqz8KPdVLYKL.jpg.jpg
https://gateway.mcphagia.com:10000/gateway/images/19a736e0-143c-4b51-ba91-1e78c1bfb89c-medium_300x225_--RAIV1a6qg6TWrKOUkrj5.jpg.jpg

[Unhandled promise rejection: Error: Unable to download from: (null)]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals

[Unhandled promise rejection: Error: Need a `from` location.]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals

**Comment by cruzach** [comment]
Please provide a snack that reproduces the error

Here's a basic example that uses FileSystem.downloadAsync successfully https://snack.expo.io/@charliecruzan/fascinated-ramen

**Comment by paultranzestpost** [comment]
Hi, Charlie.

Below is the snack that produces an error:

https://snack.expo.io/@paultran4300/fascinated-ramen

I can't tell from the error log if it's the same error.

**Comment by paultranzestpost** [comment]
Code in Snack:

export const CACHE_DIR = `${FileSystem.cacheDirectory}zestpost-image-cache/`;
export const BASE_DIR = "'https://gateway.mcphagia.com:10000/gateway/images/";
export default class App extends React.Component {
  async componentDidMount() {
    const filename = '35f826cd-13a1-4e26-a076-9ae00a335d04-medium_300x168_--jDRatwWvjqz8KPdVLYKL.jpg.jpg'
    const {exists} = await FileSystem.getInfoAsync(CACHE_DIR);
    if (!exists) {
      await FileSystem.makeDirectoryAsync(CACHE_DIR);
    }
    await FileSystem.downloadAsync(BASE_DIR + filename, CACHE_DIR + '6ba455260176c48ea07ff3ff33e5c4e02ddc167c.jpg')
      .then(({ uri }) => {
        console.log('Finished downloading to ', uri);
      })
      .catch(error => {
        console.error(error);
      });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          Change code in the editor and watch it change on your phone! Save to
          get a shareable url.
        </Text>
        <Card>
          <AssetExample />
        </Card>
      </View>
    );
  }
}

==========

The error returned from the Android SDK is a little more informative. 

==========
Android Error:
Android SDK built for x86:
Error: "Expected URL scheme 'http' or 'https' but no colon was found" in h@/data/user/0/host.exp.exponent/files/35.0.0/cached-bundle-experience-%40paultran4300%2Ffascinated-ramen-1328109476-35.0.0:39:1800 << /data/user/0/host.exp.exponent/files/35.0.0/cached-bundle-experience-%40paultran4300%2Ffascinated-ramen-1328109476-35.0.0:39:1194 << value@/data/user/0/host.exp.exponent/files/35.0.0/cached-bundle-experience-%40paultran4300%2Ffascinated-ramen-1328109476-35.0.0:47:3601 << /data/user/0/host.exp.exponent/files/35.0.0/cached-bundle-experience-%40paultran4300%2Ffascinated-ramen-1328109476-35.0.0:47:1145 ...

==========
IOS Error:
Error: "Could not download from ''https://gateway.mcphagia.com:10000/gateway/images/35f826cd-13a1-4e26-a076-9ae00a335d04-medium_300x168_--jDRatwWvjqz8KPd ... .jpg.jpg'" in h@[snack internals] << [snack internals] << value@[snack internals] << [snack internals] ...

**Comment by cruzach** [comment]
That's due to a typo in your file URI: `BASE_DIR` has an extra single quote in it. Replace it with:
```
BASE_DIR = "https://gateway.mcphagia.com:10000/gateway/images/";
```
and the Snack works 👍

**Comment by paultranzestpost** [comment]
Sorry to trouble you, Charlie. I should have caught that. Have a great day!
