### ISSUE TITLE
ExpoKit doesn't work with pods written in Swift

### ISSUE THREAD

**Issue by ethantran** [expo/expo#617]
I am trying to use react-native-hypertrack with ejected app.

Without use_frameworks, I get:

[!] Pods written in Swift can only be integrated as frameworks; add use_frameworks! to your Podfile or target to opt into using it. The Swift Pods being used are: Alamofire, GzipSwift, HyperTrack, JustLog, SQLite.swift, and SwiftyBeaver

With use_frameworks I get:

[!] **The 'Pods-rescue-fm-tracker' target has transitive dependencies that include static binaries:** (/Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/Crashlytics/iOS/Crashlytics.framework, /Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/FBAudienceNetwork/FBAudienceNetwork.framework, /Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/Fabric/iOS/Fabric.framework, /Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework, /Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework, /Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework, /Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/GoogleSignIn/Libraries/libSignIn_external.a, and /Users/RONIN/ReactNativeProjects/rescuefmtracker/ios/Pods/GoogleSignIn/Libraries/libGIPNSURL+FIFE_external.a)

I am not using these pods either, so if removing them helps, then I would like to do that.

**Comment by ethantran** [comment]
https://github.com/hypertrack/react-native-hypertrack/issues/15

**Comment by ethantran** [comment]
Doing the pre_install part of https://github.com/CocoaPods/CocoaPods/issues/2926 removes the transitive dependency warnings, but now I am getting React/RCTView.h file not found in AIRGoogleMapCallout.h.

**Comment by terribleben** [comment]
This is something i need to spend some time investigating to give a good answer for. Ideally we could find a way to convince CocoaPods to build this correctly. Let me know if you find a solution.

**Comment by awatson1978** [comment]
+1
@muratozgul

**Comment by BenBrostoff** [comment]
Hey @terribleben - wondering if there were any plans to support this in the near future. Thanks again!

**Comment by spedy** [comment]
@ethantran you might need to add the React dependency to that specific podspec.

**Comment by paul019** [comment]
+1

@terribleben This is very unfortunate error, because many other Pods only work with `use_frameworks`. When can we expect a workaround?

**Comment by paul019** [comment]
@ethantran

**Comment by paul019** [comment]
@ethantran Can you specify exactly, what you mean by this or how your Podfile looks like?

> Doing the pre_install part of CocoaPods/CocoaPods#2926

**Comment by paul019** [comment]
@terribleben @tsapeta I've tried the same workaround like @ethantran:

> Doing the pre_install part of CocoaPods/CocoaPods#2926

Now my Podfile has a prebuild script like this:

```
pre_install do |installer|
  # workaround for CocoaPods/CocoaPods#3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```

Now the `pod install` is in fact successful, but in Xcode I get the following error:

<img width="1141" alt="xcode 1" src="https://user-images.githubusercontent.com/39464035/48918088-b129bc00-ee8a-11e8-8db4-0dfdc940b9ab.png">

Have you any idea to solve this issues?

**Comment by amanforindia** [comment]
EXLogError undefined problem seems to be happening due to the definition of these functions existing in EXReactNativeAdapter. (When use_frameworks is present, the function definition needs to be present at build time due to this I think: https://github.com/CocoaPods/CocoaPods/issues/4792) So, the solution might be to add a dependency from EXCore -> EXReactNativeAdapter. But, EXReactNativeAdapter already depends on EXCore. So, I'm not sure how to proceed. Any ideas?

**Comment by ilya-section4** [comment]
@terribleben Does the Expo team have any updates on the possibility of being able to use a dependency that requires "use_frameworks!" in an ExpoKit project? Thanks!

**Comment by FiberJW** [comment]
Due to a lack of activity, I'm closing this issue for now. See [the Bare Workflow](https://docs.expo.io/versions/latest/bare/exploring-bare-workflow/) for a cleaner way to use Expo in with custom native dependencies. If you have any further related problems, please open another issue. Thanks :)
