### ISSUE TITLE
Update to RN 0.61.4

### ISSUE THREAD

**Issue by esamelson** [expo/expo#6170]
Post-IRL discussion with @ide today -- We want to update to the latest minor version before versioning since it should fix a few small issues (e.g. will take care of https://github.com/expo/expo/pull/6150). We can probably wait until before versioning to pull in the commits because they are fairly minor changes.

**Comment by kopax** [comment]
Sorry if that was asked before but I am totally new in expo and I am willing to start. 

- When will the RN 0.61 version for expo be released?
- Should I start with RN 0.59 version of expo ?
- Will the migration between old to new expo be smooth?
- Why should I consider using expo in the first place? Wouldn't it be easier to make my own boilerplate with all the tools I need? 

The 0 experience dev who doesn't know where to start.

Thanks in advance.

**Comment by ide** [comment]
- We are looking at releasing Expo SDK 36 sometime before the end of this year. The way to think of things is that Expo releases several new versions throughout the year (SDK 36, 37, etc...) and there is no "RN 0.61 version" of Expo.
- You can use SDK 35 right now.
- We try to make migrations between SDK versions smooth for official code that is authored by Expo. For third-party dependencies like React Native, it depends on whether those dependencies have smooth or rough upgrade paths.
- Expo is a universal platform for React apps for developers who want to reach users across Android, iOS, and web while accessing native capabilities of each of those platforms.

**Comment by ide** [comment]
Locking to keep the original issue on topic.

**Comment by esamelson** [comment]
https://github.com/expo/expo/pull/6243
