### ISSUE TITLE
(Android) ScrollView not showing all contents in standalone app in landscape mode.

### ISSUE THREAD

**Issue by minhnbwork97** [expo/expo#6172]
### Environment

System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.11.1 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.4.1

Target: Android, Standalone

### Standalone App
ScrollView is working fine when I run my app with Expo app by scanning QR code but there is a big problem when I run standalone app.
In my standalone app:
ScrollView in portrait mode is ok. This is how it looks when I scrolled to the end of the screen.

![Screenshot_1572930062](https://user-images.githubusercontent.com/38205529/68179931-5f5b4280-ffc4-11e9-9a2a-f77167f62808.png)

In landscape mode, I scrolled to the end of the screen but ScrollView did not show all contents. 
![Screenshot_1572930069](https://user-images.githubusercontent.com/38205529/68179956-7ef26b00-ffc4-11e9-82a7-8d6d989725a0.png)

### Expected Behavior (When I run my app with Expo app by scanning QR code)
Expected Result: 
All contents are shown like I run my app with Expo app: 
![Screenshot_1572930412](https://user-images.githubusercontent.com/38205529/68180055-cd076e80-ffc4-11e9-9187-241b861af14f.png)

Is there anyone facing this issue? Is this a Expo bug? Please help!

**Comment by cruzach** [comment]
Hi! Really sorry you're seeing this, we'll look into it.

In the meantime, could you share a code sample of your scrollview? Have you tested this on iOS already? This may be related to https://github.com/expo/expo/issues/5033

**Comment by minhnbwork97** [comment]
@cruzach Thank you. This is duplicate of #5033 . I don't know why changing resizeMode from 'contain' to 'native' works but it does 😄 .

**Comment by minhnbwork97** [comment]
Duplicate of #5033
