### ISSUE TITLE
[maintenance] Auto CHANGELOG.md

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#6178]
Add ability to add CHANGELOG.md entries either during PR creation or Merging to master ([slack for reference](https://exponent-internal.slack.com/archives/C1QP38NQ5/p1572441987057100?thread_ts=1572432071.056900&cid=C1QP38NQ5)).

Proposal ([slack message](https://exponent-internal.slack.com/archives/C1QP38NQ5/p1573637542010000)):
https://danger.systems/js/

**Comment by tsapeta** [comment]
I think we can consider this issue as closed - appropriate action was taken in #7570 and now it just needs some small improvements and ramping up to other people.
