### ISSUE TITLE
Hoiw to add splashscreen to my app?? I am very New in React

### ISSUE THREAD

**Issue by nipasarker01** [expo/expo#618]
Hello ,I am new in React Native.Figured out how expo works.I got working with few pages too.Like splash screena nd login page etc.

But I couldn't find a simple answer for how can I add a splash-screen which automatically loads to my app intro screens after two seconds.Please help.Please answer with which files I need to modify.I am using expo.

**Comment by dikaiosune** [comment]
Hi! One option for this is to use the [AppLoading](https://docs.expo.io/versions/latest/sdk/app-loading.html) API from the Expo SDK. Since this is a general "how do I do X" type of question, I'd recommend asking on StackOverflow under the `react-native` tag. Thanks!
