### ISSUE TITLE
Error  Configure project :@unimodules_react-native-adapter

### ISSUE THREAD

**Issue by mvits** [expo/expo#6181]
My project configuration in react native is:

> System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 5.26 GB / 15.88 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
and my settings.gradle: 

```
rootProject.name = 'AppSICA'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

include ':unimodules-core'
project(':unimodules-core').projectDir = new File(rootProject.projectDir, '../node_modules/@unimodules/core/android')

include ':unimodules-react-native-adapter'
project(':unimodules-react-native-adapter').projectDir = new File(rootProject.projectDir, '../node_modules/@unimodules/react-native-adapter/android')

include ':unimodules-font-interface'
project(':unimodules-font-interface').projectDir = new File(rootProject.projectDir, '../node_modules/unimodules-font-interface/android')

include ':unimodules-permissions-interface'
project(':unimodules-permissions-interface').projectDir = new File(rootProject.projectDir, '../node_modules/unimodules-permissions-interface/android')

include ':unimodules-image-loader-interface'
project(':unimodules-image-loader-interface').projectDir = new File(rootProject.projectDir, '../node_modules/unimodules-image-loader-interface/android')

```

I need a help with this problem when i execute this sentence : "react-native run-android" return this related with @unimodules_react-native-adapter :

> Configure project :@unimodules_react-native-adapter
Observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in inconsistent location 'C:\Users\Stiv\AppData\Local\Android\Sdk\.temp\PackageOperation02' (Expected 'C:\Users\Stiv\AppData\Local\Android\Sdk\extras\intel\Hardware_Accelerated_Execution_Manager')

`FAILURE:` Build failed with an `exception.`

* What went wrong:
Could not determine the dependencies of task ':@unimodules_react-native-adapter:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':@unimodules_react-native-adapter:debugCompileClasspath'.
   > Could not resolve androidx.core:core:{strictly 1.0.0}.
     Required by:
         project :@unimodules_react-native-adapter
      > Cannot find a version of 'androidx.core:core' that satisfies the version constraints: 
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0'
           Constraint path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'androidx.core:core:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.facebook.react:react-native:0.61.2' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.core:core:1.0.1'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.loader:loader:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.1' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.customview:customview:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.viewpager:viewpager:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.coordinatorlayout:coordinatorlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.drawerlayout:drawerlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.slidingpanelayout:slidingpanelayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'org.unimodules:@unimodules_react-native-adapter:4.0.0' --> 'com.github.bumptech.glide:glide:4.9.0' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.asynclayoutinflater:asynclayoutinflater:1.0.0' --> 'androidx.core:core:1.0.0'

**Comment by brentvatne** [comment]
can you explain how you arrived to this error and ideally provide a reproducible example?

**Comment by cruzach** [comment]
hey @mvits I'm going to close this issue for inactivity. If you believe you've found a bug in the Expo SDK, please open a new issue with a reproducible demo, thanks!
