### ISSUE TITLE
Crash when open Android React with detached Expo

### ISSUE THREAD

**Issue by khantthulinn** [expo/expo#6188]
### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1

I am building android app with detach Expo (Expo Eject). 

It is working perfectly fine for debug but when I build as release and download apk, I got this error. I am trying to use ssl pinning though (should not be any issue i guess).

> 
`2019-11-06 10:27:13.494 14739-14739/? E/AndroidRuntime: FATAL EXCEPTION: main Process: sg.edu.nus.timesheet, PID: 14739 java.lang.RuntimeException: Unable to create application host.exp.exponent.MainApplication: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.h at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222) at android.app.ActivityThread.access$1200(ActivityThread.java:237) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7045) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) Caused by: java.lang.RuntimeException: NativeModuleDepsProvider could not find object for class class host.exp.exponent.h at host.exp.exponent.o.a.a(NativeModuleDepsProvider.java:12) at host.exp.exponent.o.a.b(NativeModuleDepsProvider.java:2) at f.a.a.b.(Exponent.java:9) at f.a.a.b.a(Exponent.java:4) at host.exp.exponent.f.onCreate(ExpoApplication.java:9) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6217)
`

<br>
I also saw quite a lot of similar issue.

https://forums.expo.io/t/release-build-on-detached-project-doesnt-run/16777 <br>

https://github.com/expo/expo/issues/3934 https://github.com/expo/expo/issues/6082

How shall I do?  I tried `exp publish` before I release and it is also not okay.

**Comment by pedro-lb** [comment]
@khantthulinn I think we've got the same problem. I've opened [this issue](https://github.com/expo/expo/issues/6184), but had no luck.

By any chance did you manage to fix it?

**Comment by cruzach** [comment]
Have either of you tried the solutions shared in those issues you shared? I.e. running in production with `expo start --no-dev --minify`? 
@khantthulinn `exp` was deprecated a while ago, can you try with `expo publish` and **then** build your binary?

@pedro-lb `expo start` doesn't automatically link libraries, for that you'll have to run `react-native link x`

**Comment by pedro-lb** [comment]
@cruzach Sorry I haven't been clear. I've already linked the dependencies with `react-native link x`, but even so when I do `expo start` it doesn't seem to be linked (doesn't work and outputs an error that only happens when it is unlinked).

I've tried the same code with a normal react native app - it works fine (I don't even need to link the dependencies because of AndroidX and Jetifier).

**Comment by cruzach** [comment]
We're adding full AndroidX support in SDK 36, but I think jetifier should work on most libraries (there were a few reports of it not working [here](https://github.com/unimodules/react-native-unimodules/issues/61) however)

You should be able to `react-native link` and run with `expo start` (I'm able to in a fresh expo init, ejected project), so there's probably another problem in that case

**Comment by pedro-lb** [comment]
@cruzach Thanks for the feedback! Really looking forward for SDK 36.

I'm trying to use this lib: [react-native-music-control](https://github.com/tanguyantoine/react-native-music-control). I've followed the install & linking procedures but upon opening the app there is this error:

![image](https://user-images.githubusercontent.com/22061051/68339447-5ac98380-00c3-11ea-8b88-52d04f0e5cc1.png)

This error is also referenced in https://github.com/tanguyantoine/react-native-music-control/issues/167, https://github.com/tanguyantoine/react-native-music-control/issues/112, all pointing to the fact that the link isn't working.

Note that it works perfectly in a normal react native app - with manual or autolinking. It's just that when using `expo start` in a `ExpoKit` app it doesn't appear to link the lib correctly.

**Comment by khantthulinn** [comment]
I forgot what I have done exactly but I did change a few things (may or may not be related).

In app.json (shell-app-manifest.json >> kernel-manifest.json), it is because I don't see shell-app-manifest.json after I detach in android. 

"publishManifestPath": "android/app/src/main/assets/kernel-manifest.json"

I take out **cleartextTrafficPermitted** for my SSL pinning. 

I also run **expo publish** .  After all that, it is okay now. Thank you guys.

**Comment by cruzach** [comment]
@pedro-lb I tried recreating your error, but I wasn't able to. Do you see that on a blank `expo init` then `expo eject` project, after running:
`expo install react-native-music-control`
`react-native link react-native-music-control`
?

@khantthulinn glad you were able to resolve this, should we close the issue? It looks like Pedro's issue is unrelated, so it's probably better off in its own ticket

**Comment by pedro-lb** [comment]
@cruzach Thanks for the feedback! That's exactly what I'm doing and still getting the error.

Note that the error only occurs when you actually use the library, by doing `import MusicControl from 'react-native-music-control';` in any component file.

I've created a repo simulating the issue: https://github.com/pedro-lb/expo-35-react-native-music-control/. If you run it you'll probably get the same error.

**Comment by khantthulinn** [comment]
Yes. @cruzach . Let close . Thanks for helping us.

**Comment by pedro-lb** [comment]
Thanks!

@cruzach I've opened a separate issue for my problem: https://github.com/expo/expo/issues/6230

**Comment by tncbbthositg** [comment]
@cruzach, I'm having the same problem but none of these solutions have helped me.  I'm hoping you might have some insight.

I'm getting basically the same error, only for me it fails when looking for `host.exp.exponent.f`.  I looked at the mapping file output, and I believe it's failing because the `host.exp.exponent.ExponentManifest` does not exist in the [injectable property map](https://github.com/expo/expo/blob/master/android/expoview/src/main/java/host/exp/exponent/di/NativeModuleDepsProvider.java#L107-L109):

```
      if (!mClassesToInjectedObjects.containsKey(fieldClazz)) {
        throw new RuntimeException("NativeModuleDepsProvider could not find object for class " + fieldClazz.toString());
      }
```

I'm going to try to get some more information if I can.  It works fine if I build it in debug mode, but in release mode, I think Proguard isn't mapping the types.  I'm not sure yet.

**Comment by abowerman** [comment]
Not sure if this is helpful, but I pulled my hair with this for a bit: 

When I gave up and ejected completely without expo kit, the automated script added a few dependencies that I had no clue were needed. Maybe if I added these back expokit would work, but I didn't waste any additional time with this.
