### ISSUE TITLE
Speech.speak only wokrs once when the language is set.

### ISSUE THREAD

**Issue by brunacaster** [expo/expo#619]
The three commands below work _perfectly_ every time the componet is mounted.
`componentDidMount() { Speech.speak("Hi"); }`
`componentDidMount() { Speech.speak("Hi", { language: "en" }); }`
`componentDidMount() { Speech.speak("Hi", { language: "en-US" }); }`

The following command only works once.
Even if I restart the application (close and reopen it, it only works a single time and never again)
`componentDidMount() { Speech.speak("Oi, eu sou o Hudson", { language: "pt-BR" }); }`

The same goes for any other language I tried.
`componentDidMount() { Speech.speak("Ohayou", { language: "ja-JP" }); }`
`componentDidMount() { Speech.speak("Hola", { language: "es" }); }`

Once a language is used in a **Speach.speak** method, it doesn't ever work again.

Reference:
* react: 16.0.0-alpha.12
* exp/react-native: 19.0.0
* running on an android emulator

**Comment by aalices** [comment]
@brunacaster I cannot reproduce it - what device are you emulating and what SDK it uses ?

**Comment by brunacaster** [comment]
Hi @aalices , 

Here's everything I got on versions and SDKs:

Versions:
-> "expo": "^19.0.0"
-> "react": "16.0.0-alpha.12"

AVD run with the command:
-> emulator -avd NEXUS_5_API_25 -skin 1080x1920 -use-system-libs

AVD was created with the following command line:
-> avdmanager create avd -n "NEXUS_5_API_25" -d "Nexus 5" -k "system-images;android-25;google_apis;x86" -g "google_apis"

Sorry for the late answer, and thanks for the help.

**Comment by aalices** [comment]
@brunacaster Are you sure `componentDidMount` is called? In what cases do you want the speaker to speak?

**Comment by brunacaster** [comment]
Yes, 100% positive about it: `componentDidMount` is getting invoked every time.

This is also proved by the fact that 'en' and 'en-US' work everytime, in the same `componentDidMount` handler.

Like I mentioned before, other languages run only once, and then never again.
I have a feeling that some underlying component crashes (for other languages) and won't come back alive. The same does not seem to happen with 'en-US' language, that doesn't (apparently) crash AND always plays.

Hugely grateful for your attention - please let me know if I can provide you with any more intel on this case.

**Comment by aalices** [comment]
Everything works perfectly fine for me - however, some changes have been made not really related to this in the module, try SDK 21 when it's out - I hope it will solve you problem :)

**Comment by terribleben** [comment]
SDK 21 is coming out this week, let us know if you're still seeing an issue.
