### ISSUE TITLE
`exp build` is not supported for detached projects.

### ISSUE THREAD

**Issue by kruyvanna** [expo/expo#620]
I got this after I run

`exp build:ios`

How to build a detached project?

**Comment by kruyvanna** [comment]
I can build the project using XCode but it got this on the Simulator

![simulator screen shot sep 9 2017 7 48 46 pm](https://user-images.githubusercontent.com/1171793/30240301-ef77cbca-9597-11e7-8e0e-8e4cf330a6d5.png)

**Comment by daominhsangvn** [comment]
Try to start the Expo, select the project then make the iOS build via xCode again see if it work.

**Comment by kruyvanna** [comment]
@daominhsangvn 
it works!
Thanks!

**Comment by daominhsangvn** [comment]
you're welcome :)
