### ISSUE TITLE
Add Vibration on receiving Remote Push notifications

### ISSUE THREAD

**Issue by anasanzari** [expo/expo#6203]
Is it possible to add vibration on receiving Remote Push notifications

**Comment by cruzach** [comment]
Yes! You can read how in our [Notification channels guide](https://docs.expo.io/versions/latest/guides/notification-channels/#updating-an-existing-app-to-use-channels) 👍

**Comment by anasanzari** [comment]
@cruzach for iOS

**Comment by cruzach** [comment]
Ah, well you can use [Vibration](https://docs.expo.io/versions/latest/react-native/vibration/) in the notification listener
