### ISSUE TITLE
Retrieve value within JSON Data

### ISSUE THREAD

**Issue by mporres** [expo/expo#6205]
Good afternoon, I have a big question and that's why I need your help.
I have to extract the name I receive in Data when the notification arrives. How do I get only the value of a JSON within Data?

`const message = {
      to: ExponentPushToken[...],
      sound: "default",
      title: "Original Title",
      body: "And here is the body!",
      data: { "name": "max" },
    };`

That is the notification I send, hence I need to take out and store the value of "name" in a variable.
How do I make this possible?

**Comment by AdamJNavarro** [comment]
Hey @mporres,

You'll want to use the `notification.data` object you receive from the Notifications listener. https://docs.expo.io/versions/v35.0.0/guides/push-notifications/#3-handle-receiving-andor-selecting-the-notification

For your example, you could `notification.data.name` which would return `"max"` or you could use object destructuring. It's up to you. On that note, this is more so to do with basic javascript knowledge so I'd recommend reading MDN docs like this one https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment to get comfortable.

Cheers,
Adam
