### ISSUE TITLE
GLView and GPU on iOS

### ISSUE THREAD

**Issue by alexpareto** [expo/expo#6208]
Is there a way to have GLView take advantage of the GPU on the device? When running GLView and associated components, the CPU on iOS spikes to extreme highs but the GPU looks fairly untouched. Is there a way to have GLView take advantage of the GPU?

**Comment by cruzach** [comment]
Is this specifically happening on iOS 13?

Can you provide a repo that I can run locally to see this behavior? We want to keep github reserved for bug reports, so if this is just a general question, it's better off posted on our [forums](https://forums.expo.io/)
