### ISSUE TITLE
Expo.Video fullscreen transition animation

### ISSUE THREAD

**Issue by Elijen** [expo/expo#621]
It would be nice to be able to use the native fullscreen transition animation instead of a modal view used by `presentIOSFullscreenPlayer()`. 

It should probably be set as default to keep consistency with the behavior of the fullscreen icon in native controls.

**Comment by Elijen** [comment]
I made this work by modifying `EXVideoPlayerViewController` and `EXVideoView` however the solution uses a private API. Based on the StackOverflow answer: https://stackoverflow.com/a/36853320/190438

What's the Expo policy on using private APIs?

**Comment by dikaiosune** [comment]
Hi! If you're using private Apple APIs that may endanger your app going through their review process for the App Store, but it's up to you if you've detached. We avoid using private Apple APIs in the client and standalone apps, as it's very important for us to keep user's applications in compliance with Apple's review guidelines.
