### ISSUE TITLE
When i init a project, yarn start  but error, who can help me, thanks

### ISSUE THREAD

**Issue by CooLNuanfeng** [expo/expo#6210]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

`expo init expo-demo
? Choose a template: expo-template-tabs
✔ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration/ · 100% completed
? Yarn v1.16.0 found. Use Yarn to install dependencies? Yes
Extracting project files...
Customizing project...
Initialized a git repository.
Installing dependencies...
yarn install v1.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning react-native-web > deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @react-navigation/web@1.0.0-alpha.9" has unmet peer dependency "@react-navigation/core@^3.0.0-alpha.13".
warning "react-native > metro-react-native-babel-transformer@0.51.0" has unmet peer dependency "@babel/core@*".
warning "react-native > @react-native-community/cli > metro-react-native-babel-transformer@0.51.1" has unmet peer dependency "@babel/core@*".
warning "react-navigation > react-navigation-tabs@1.2.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-drawer@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.5.3" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "jest-expo > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "jest-expo > babel-jest > babel-preset-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 23.23s.

Your project is ready at /Users/wuhongsong/Documents/www/ReactNative/Expo/expo-demo

To get started, you can type:

  cd expo-demo
  yarn start`

`$ cd expo-demo && yarn start
Starting project at /Users/wuhongsong/Documents/www/ReactNative/Expo/expo-demo
(node:84772) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT] [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.
    at Server.listen (net.js:1427:13)
    at /Users/wuhongsong/.nvm/versions/node/v12.13.0/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:8:12
    at new Promise (<anonymous>)
    at testPortAsync (/Users/wuhongsong/.nvm/versions/node/v12.13.0/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:6:10)
    at availableAsync (/Users/wuhongsong/.nvm/versions/node/v12.13.0/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:24:17)`

**Comment by cruzach** [comment]
Closing this, as it says in the issue template:
> Please note that Expo CLI issues opened in the core Expo repository will be closed.

[This post on our forums](https://forums.expo.io/t/npm-start-hangs/29020) discuss the same issue you're having. If you still can't resolve it, I would also provide your SDK version and `expo-cli` version

**Comment by CooLNuanfeng** [comment]
> H! I'm going to close this, as it says in the issue template:
> 
> > Please note that Expo CLI issues opened in the core Expo repository will be closed.
> 
> However, [this post on our forums](https://forums.expo.io/t/npm-start-hangs/29020) discuss the same issue you're having. If you still can't resolve it, I would also provide your SDK version and `expo-cli` version

OK, thanks  i try 3.3.0 or 3.2.3
