### ISSUE TITLE
ERROR ITMS-90786: "Invalid Entitlement. Apps that contain the 'com.apple.developer.coremedia.hls.low-latency'"

### ISSUE THREAD

**Issue by WebWorkDeveloper** [expo/expo#6215]
## Expected Behavior

When I upload my app to Application Loader have this error

## Observed Behavior

![image](https://user-images.githubusercontent.com/8726541/66149634-2bcf7600-e61c-11e9-910c-043129d8423f.png)

```
ERROR ITMS-90786: "Invalid Entitlement. Apps that contain the 'com.apple.developer.coremedia.hls.low-latency' entitlement must be built with the iOS 13.0 SDK or later."
```

## Environment

Expo CLI 2.18.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v8.11.3/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.5 => 4.0.5
    npmGlobalPackages:
      expo-cli: 2.18.3

  Xcode 11
  IOS 13
  iPhone 10

**Comment by cruzach** [comment]
@erwinwahyura when you use `expo build:ios`, certs in your local keychain shouldn't affect the build unless you're providing your own certs manually. 

Does this happen to you when building/submitting a new, blank expo app to application loader? Since you're already on SDK 35, your app should be built with the iOS 13 SDK, so maybe this has to do with old certs being associated with that app?

**Comment by erwinwahyura** [comment]
@cruzach thanks for your reply, i think i solved my issue, idk why but when i build ios app using `expo build:ios --clear-provisioning-profile`  its feel it didnt delete all the certs that associated with the apps, so there is an old certs being associated with this apps. 

i solved this issue with create new account of expo and build the same app with `expo build:ios` and then its works.

**Comment by erwinwahyura** [comment]
@cruzach more information
i didnt build or submitting a new blank expo app, but i guess it will error too.

i also tried 2 times delete all the certs in apple developer settings  create new identifiers,  and let all expo handle this works, but it still error `ITMS-90787: Invalid Entitlement - This app is not permitted to use the 'com.apple.developer.coremedia.hls.low-latency' entitlement.` and the apps goes `invalid binary`

**Comment by cruzach** [comment]
We don't delete the certs in the Apple Developer console, we only remove the certs we have for you on our servers. So to fully delete certs, you have to go through Apple's UI

Sorry, but I'm a little confused, this happens on a blank app using all new certs?

**Comment by WebWorkDeveloper** [comment]
@crubier having the same issue

**Comment by cruzach** [comment]
@WebWorkDeveloper does this happen on a blank expo project? We push a fix out to our builders a couple weeks ago which resolved a similar (but not identical) issue, so how long ago did you run `expo build`?

**Comment by WebWorkDeveloper** [comment]
@cruzach I am using my real application, `expo build` was run yesterday. And now I trying to build an application.

**Comment by WebWorkDeveloper** [comment]
@cruzach @erwinwahyura so, I fix this issue :)

I'm just disabled `Low Latency HLS` in my application Identifier

![image](https://user-images.githubusercontent.com/8726541/69411349-d52e1080-0d1d-11ea-8016-1a23da7cc434.png)

Next, I delete all my `Certificates`, `Profiles`, `Keys` and generate again.

And build ipa
```
expo build:ios -c
```

Now my app is status `Ready for Sale` and  I can take up to 24 hours before my app becomes available on the App Store.

**Comment by cruzach** [comment]
Aha! Thanks for sharing that. Any changes to your entitlements need to be followed by a rebuild so that it's associated with the provisioning profile, which would explain it.
