### ISSUE TITLE
Do not use expo.name from app.json to generate paths

### ISSUE THREAD

**Issue by Elijen** [expo/expo#622]
App name from app.json (https://docs.expo.io/versions/latest/guides/configuration.html#name) is used to generate paths (e.g. to `EXBuildConstants.plist`) in `exp prepare-detached-build --platform ios` which makes it harder to rename the app.

Maybe `expo.ios.projectPath` property should be generated on detach and used instead?

**Comment by terribleben** [comment]
Reasonable suggestion, thanks for raising.

**Comment by katiepeters** [comment]
Any update on this?

**Comment by pcowgill** [comment]
I just ran into this issue for a previously detached app that I needed to rename so that the name would look nicer under the app icon after downloading from the app store.

Is there any way to force the paths to still point to the path based on the old name?

**Comment by moxorama** [comment]
Looks like still actual

**Comment by FiberJW** [comment]
Due to a lack of activity, I'm closing this issue for now. See [Bare Workflow](https://docs.expo.io/versions/latest/bare/exploring-bare-workflow/) for a cleaner way to use Expo in with custom native dependencies. If you have any further related problems, please open another issue. Thanks :)

**Comment by pcowgill** [comment]
Just created this feature request on Canny for those who still would like this feature https://expo.canny.io/feature-requests/p/do-not-use-exponame-from-appjson-to-generate-paths-when-ejecting
