### ISSUE TITLE
Expo web syntax error: Use of const in strict mode

### ISSUE THREAD

**Issue by zartosht** [expo/expo#6220]
### Environment

```
 Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
```

Target: web

### Steps to Reproduce

I made my project using Expo and it all worked fine as expected but when I tried to test it in older browsers (for older TV compatibility check) I came across a problem in chrome 38, 39 and 40 that instead of showing the complete project it goes blank and with this error in the console:

```
Uncaught SyntaxError: Use of const in strict mode.
```

### Expected Behavior
I expected that the project ran in older versions of browsers

### Actual Behavior
```
Uncaught SyntaxError: Use of const in strict mode.
```

### Reproducible Demo
https://tv.sekans.com

I also asked my question over [Stakoverflow](https://stackoverflow.com/questions/58777636/expo-web-syntax-error-use-of-const-in-strict-mode).

**Comment by cruzach** [comment]
Expo for Web should have the same compatibility as react native web. Chrome 40 is from about 5 years ago, so I'm not sure if it's supported by RNweb

**Comment by zartosht** [comment]
> Expo for Web should have the same compatibility as react native web. Chrome 40 is from about 5 years ago, so I'm not sure if it's supported by RNweb

But is required for viewing websites in older Smart TVs.

**Comment by EvanBacon** [comment]
This is not something we are looking to support. You can work around it by writing a babel transform and including it in your `babel.config.js`.
