### ISSUE TITLE
it is very slow to load the video after setting 'useWebKit={true}'

### ISSUE THREAD

**Issue by MinxianLi** [expo/expo#6221]
Based on this https://github.com/expo/expo/issues/5864,

solution 'useWebKit={true}' works, however, I notice, now it is very slow to load the video after setting 'useWebKit={true}', any suggestion?

**Comment by cruzach** [comment]
Responded to your comment there. Basically, I'd try using `@react-native-community/webview` instead. If that is still slow, I would compare using it in a bare RN App and in an Expo managed app, and if the speed is slower in the Expo app then open an issue following the full bug report template we provide 😄
