### ISSUE TITLE
Video under 10 seconds causes memory leak (using expo-av)

### ISSUE THREAD

**Issue by adamski-g** [expo/expo#6225]
### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.11.0 - ~/.nvm/versions/node/v12.11.0/bin/node
      npm: 6.11.3 - ~/.nvm/versions/node/v12.11.0/bin/npm
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.4.1

iOS

### Steps to Reproduce

I'm trying to loop a video that's under 10 seconds. Each loop of the video seems to add more and more memory until my system crashes. 

### Expected Behavior

Going by the examples I presumed looping video would be fine.

### Actual Behavior

Looking at Active Monitor the SimRenderServer jumps to the top of the processes. Then memory goes from 0 to 100GB within 10mins. 

### Reproducible Demo

https://snack.expo.io/rJ_dFeLir

**Comment by cruzach** [comment]
Tried to repro this locally, but memory doesn't seem to be jumping (ran it for 10 mins)

Although, I'm using xcode 10 and haven't upgraded to catalina

There is [this issue](https://github.com/appium/appium/issues/13378) on another repo that indicates maybe you need to upgrade your xcode version

**Comment by adamski-g** [comment]
Hi. Thanks for the suggestions. I just upgraded to the newest version of Xcode and the latest version on Expo and the problem still persists. I'm on Mojave 10.14.5.

**Comment by cruzach** [comment]
What iOS version is the sim running?

**Comment by adamski-g** [comment]
It's iOS 13.2.

**Comment by cruzach** [comment]
```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.4.1
```

Hm, just upgraded to the most recent Xcode version and still can't seem to replicate this

**Comment by adamski-g** [comment]
Hi. I finally got to try this on another setup today and...it ran fine, no memory issues. I've got to assume it's a bug with older graphic cards (iMac 2014 model). I can work round it. Thanks for the help on this so far.

**Comment by IjzerenHein** [comment]
@adamski-g Is this still an issue for you or can we close this issue?

**Comment by IjzerenHein** [comment]
Closing as this appeared resolved. Feel free to reopen with additional info if the problem still exists.
