### ISSUE TITLE
Secure Store value size limit is wrong

### ISSUE THREAD

**Issue by niclarcipretti** [expo/expo#6231]
Hi,

Expo's secure store doc says that I can store values up to 2048 bytes. But, when I try to store a 1000 bytes string in it, expo gives me a warning that I'm trying to store more then 2048 bytes in secure store.

My question is: 2048 bytes, before or after encryption? If after, wich encryption algorithm are you using so I can check before storing?

Thanks in advance.

Nikao

**Comment by cruzach** [comment]
Is this on iOS or Android, and which SDK? Could you provide a repro for this? Following the full Github issue template is really helpful!

Also, feel free to take a look at the [source](https://github.com/expo/expo/tree/master/packages/expo-secure-store) for whichever platform is giving you trouble
