### ISSUE TITLE
expo-linear-gradient failing on tests

### ISSUE THREAD

**Issue by adamsythe** [expo/expo#6232]
### Environment

Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: ^0.60.6 => 0.60.6 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.4.1

Standalone app with react-native-unimodules
### Steps to Reproduce
npx react-native init AwesomeProject
Add the following to package.json
    ```
"react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-unimodules": "0.7.0-rc.1",
    "expo-linear-gradient": "^7.0.1"

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

```
import React from 'react';
import {
  SafeAreaView,
} from 'react-native';

import { LinearGradient } from 'expo-linear-gradient'

const App: () => React$Node = () => {
  return (
    <>
      <SafeAreaView>
      </SafeAreaView>
    </>
  );
};


export default App;


```

in command line run npm test and it fails with
   Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/adamkatz/projects/virtual_institute/vip-mobile/viperStudent/node_modules/expo-linear-gradient/build/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as LinearGradient } from './LinearGradient';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

A project with expo-linear-gradient doesn't pass tests

### Expected Behavior

I expect tests to pass

### Actual Behavior

tests do not pass

### Reproducible Demo

https://github.com/adamsythe/RNTestingRepo/tree/master/TestingExpoLinearGradient

**Comment by cruzach** [comment]
Hi! My guess is that maybe this is happening due to your dependencies

We are currently in the process of upgrading the SDK to RN .61, so until SDK 36 comes out, you're better off using RN0.59

**Comment by adamsythe** [comment]
Hi thanks but its not really feasible to be on 0.59 anymore.  

I managed to work out the problem i had to use "preset": "jest-expo", instead of 'preset': "react-native"

Why on a RN app does it need jest-expo to test and not jest-rn?

**Comment by cruzach** [comment]
We talk about this in our [documentation](https://docs.expo.io/versions/latest/guides/testing-with-jest/):
> it's a Jest preset that mocks out the native side of the Expo SDK and handles some configuration for you
