### ISSUE TITLE
How to have Expo Pedometer always running in background?

### ISSUE THREAD

**Issue by a37803464** [expo/expo#6241]
I’m using the Expo Pedometer:(https://docs.expo.io/versions/latest/sdk/pedometer/ 2), and have a working step-counter which works well on one page of my app.

It counts up as expected as I walk when i hold my phone with the screen open, using state to store the currentSteps. However, when I turn my phone screen off/lock my phone, the steps do not go up as I walk - it only works if i have the screen open.

I have been reading about Expo Task Manager: https://docs.expo.io/versions/latest/sdk/task-manager/ 1 but really have not much of an idea how I should even go about this…

My goal is to have the pedometer count the user’s steps no matter if the app is open or not; so when the user checks the app, they can see their daily steps from within the app in real time.

Anyone can help me？

**Comment by cruzach** [comment]
Hi! We like to keep github issues reserved for bug reports, so I'm going to close this. It seems from [your forum post](https://forums.expo.io/t/how-to-run-expo-pedometer-constantly-in-background/26896) that we already have an [issue for this open](https://github.com/expo/expo/issues/4895)
