### ISSUE TITLE
[docs] add Android UI example to Local Authentication docs 

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#6248]
## 🐛 Bug Report

The Local Authentication documentation currently heavily implies that it works natively cross platform but there's no convenient, bundled fingerprint UI provided with the plugin for Android and Face / Iris detection is entirely not present for Android. It would be helpful to developers to provide a disclaimer in a prominent place on the documentation that this API is **basically** not cross platform at the moment and is more or less iOS only.

**Comment by cruzach** [comment]
I agree that we should add an example UI for Android in the docs, I can add that in

But, I wouldn't go so far as to say this API is iOS only. We do state in the [docs](https://docs.expo.io/versions/latest/sdk/local-authentication/) right now both that Android doesn't support FaceID yet (but does support the Fingerprint API), and that:
> Note: When using the fingerprint module on Android, you need to provide a UI component to prompt the user to scan their fingerprint, as the OS has no default alert for it.

**Comment by cruzach** [comment]
@shamilovtim here's an example Snack that can be used on iOS or Android
https://snack.expo.io/@charliecruzan/localauthentication35example
On Android, it creates a modal when fingerprint scanning is occuring
