### ISSUE TITLE
[permissions] Can not get CAMERA_ROLL permissions for Standalone apple app

### ISSUE THREAD

**Issue by michalgarcarz** [expo/expo#6254]
### Environment
React-native app with expo/managed flow.

 Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.4.1

### Steps to Reproduce

I use the following code to ask for permissions to use camera (and also file upload) for ImagePicker:

```
const verifyPermissions = async () => {
        if (Constants.platform.ios) {
            //for IOS we need also CAMERA_ROLL
            const { ios_status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
            if (ios_status !== 'granted') {
              alert('Sorry, we need camera roll permissions to make this work!');
              return false;
            }            
        }
       //for both Android and IOS
        const result = await Permissions.askAsync(
            Permissions.CAMERA
        );
        if (result.status !== 'granted') {
            Alert.alert(
                'Insufficient permissions!',
                'You need to grant camera permissions to use this app.',
                [{ text: 'Okay' }]
            );
            return false;
        }
        return true;
    };
```

In my app.json for ios i have only:
```
"infoPlist": {
        "NSCameraUsageDescription": "This app uses the camera to make a photo of your car"
      }
```

### Expected Behavior

It should ask user for permissions.

### Actual Behavior

Working fine on both android and apple simulators.
Working fine on android standalone devices.
Does not work on apple standalone devices: users got alert:
"Sorry, we need camera roll permissions to make this work!"
And are never asked for any permissions, can not approve anything.

**Comment by lukmccall** [comment]
Hi @michalgarcarz, to be able to ask for `CAMER_ROLL` permissions you need to add to your `app.json` the `NSPhotoLibraryUsageDescription` key. 
Please try it and tell me if it's working.

**Comment by michalgarcarz** [comment]
Thank you Łukasz, testing, will update you soon (it would be good to add that to the documentation!).

**Comment by lukmccall** [comment]
If adding the key to `infoPlist` won't help,  please check what you have in the permissions section in settings.

**Comment by michalgarcarz** [comment]
Those are my ios/android sections in app.json
```
"ios": {
      "supportsTablet": true,
      "bundleIdentifier": "pl.xxx",
      "buildNumber": "1.0.11",
      "infoPlist": {
        "NSPhotoLibraryUsageDescription": "This app is able to attach car from your photo library",
        "NSCameraUsageDescription": "This app uses the camera to make a photo of your car"
      },
      "config": {
        "googleSignIn": {
          "reservedClientId": "com.googleusercontent.apps.586xxx"
        }
      }
    },
    "android": {
      "package": "pl.xxxx",
      "versionCode": 12,
      "permissions": [
        "READ_EXTERNAL_STORAGE", 
        "WRITE_EXTERNAL_STORAGE",
        "CAMERA"
      ],
      "config": {
        "googleSignIn": {
          "apiKey": "xxx",
          "certificateHash": "xxx"                             
        }
      }
    }
```

I do not have any dedicated permission section for ios - that is android specific. Am i missing something ?

Thanks,

**Comment by lukmccall** [comment]
Go to Privacy > Photos > Your app.
If your app doesn't have permissions set there. It means that you denied them earlier. On iOS you can't ask for them again - need to change it manually.

**Comment by michalgarcarz** [comment]
When going to Privacy > Photos > my app on that phone there is already read/write.
This is apple iphone 8 with version 12.3.1. And still inside the app i got mentioned alarm:
"Sorry, we need camera roll permissions to make this work!"

But one of the other TestFlight testers got it working fine, trying to figure out hardware and iOS software version.

Is it possible to be iOS version dependant issue ?

Thanks,

**Comment by lukmccall** [comment]
It's sound pretty weird. How do you run your app on a real device? I assumed that you run it through TestFlight. 

I don't think it's related to the iOS version.

**Comment by michalgarcarz** [comment]
Yes - it's through TestFlight. Let me gather feedback from 2 more testers along with hardware/software versions and come back with that.
