### ISSUE TITLE
createEventAsync doesn't work

### ISSUE THREAD

**Issue by zxl634** [expo/expo#6257]
### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.0.11 - /usr/local/bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.4.1

### Steps to Reproduce

Keep getting an errror that the event was not saved when using `createEventAsync`.

Have made a repo with a reproducible app that asks for calendar permissions, creates a new calendar and then tries to write to it: https://github.com/zxl634/expo-calendar-mwe

### Expected Behavior

Expected to be able to create event in calendar.

### Actual Behavior

Got the following error message:
```
Event with id C138BFC7-42C1-404A-849D-B5314C2E460A was not saved
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals
```

### Reproducible Demo

https://github.com/zxl634/expo-calendar-mwe

https://snack.expo.io/@zxl634/expo-calendar-mwe

**Comment by zxl634** [comment]
Created a workaround using Google Calendar API for now, but just wondering whether you have had a change to look at it?

**Comment by lukmccall** [comment]
Hi @zxl634, you need to provide `endDate` value to create an event. I know, in our documentation, this field is only required on `Android`. However, I think this is a mistake. You need to specify `endDate` on both: iOS and Android. I'll correct that mistake in our documentation.
