### ISSUE TITLE
iOS ExpoKit build hook should include ~/.nvm/nvm.sh

### ISSUE THREAD

**Issue by bpeters** [expo/expo#626]
https://github.com/expo/expo/blob/8a199ff9607914dc9df130a55fb189e868a3ca62/exponent-view-template/ios/exponent-view-template.xcodeproj/project.pbxproj#L250

Proposed to add `. ~/.nvm/nvm.sh` to top of script

was fixed here in react-native https://github.com/facebook/react-native/issues/3935

**Comment by dikaiosune** [comment]
Hi! I don't see any upstream fix for that issue, actually, but I agree being compatible with NVM would be ideal. Has a fix been committed elsewhere in upstream RN?

**Comment by FiberJW** [comment]
Due to a lack of activity, I'm closing this issue for now. See [Bare Workflow](https://docs.expo.io/versions/latest/bare/exploring-bare-workflow/) for a cleaner way to use Expo in with custom native dependencies. If you have any further related problems, please open another issue. Thanks :)
