### ISSUE TITLE
WebBrowser.dismissBrowser() crasshes iOS App

### ISSUE THREAD

**Issue by kevzettler** [expo/expo#6260]
### Environment
```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.16.0/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.1.15 => 3.1.15 
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.4.1
```

Target:
iOS iPhone X 13.2

### Steps to Reproduce

I have the following function I am using in an Oauth flow:
```
const urlOpener = async (url, redirectUrl) => {
  // On Expo, use WebBrowser.openAuthSessionAsync to open the Hosted UI pages.
  const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(url, redirectUrl);

  if (type === 'success') {
    // This crashes the app on IOS ??

    await WebBrowser.dismissBrowser();

    if (Platform.OS === 'ios') {
      return Linking.openURL(newUrl);
    }
  }

  return null;
};
```

This function will crash the app on iOS. If I comment out the `dismissBrowser` line the crash does not occure

### Expected Behavior
App should not crash

### Actual Behavior
App crashes on `await WebBrowser.dismissBrowser();` line

### Reproducible Demo
https://snack.expo.io/ByIZAZ5jH

I tried to make a snack that reproduces this unfortunately due to privacy reasons i'm not sure what to use for an authURL to `openAuthSessionAsync`

**Comment by cruzach** [comment]
Hi! this was a known issue, [here's the issue](https://github.com/expo/expo/issues/5742), and it's been solved. I'm thinking you must have built your app before the fix was released (although that was a few weeks ago)?

When did you build your app?

**Comment by kevzettler** [comment]
hi @curzach working on the app currently. what do I need to upgrade and get fix?

**Comment by cruzach** [comment]
Are you using SDK 34? I wasn't aware that this bug occurred in SDK 34 standalone apps, so if that's the case then we might want to fix that

Right now, you can just upgrade your app to SDK 35 and build it, and you'll have the fix
