### ISSUE TITLE
[docs] ExpoKit Android docs explain not to upgrade Gradle but do not provide a way back for people who did

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#6261]
In:
https://docs.expo.io/versions/v35.0.0/expokit/expokit/

The following is written:
When opening the project, Android Studio may prompt you to upgrade the version of Gradle or other build tools, but don't do this as you may get unexpected results. ExpoKit always ships with the latest supported versions of all build tools.

It would be helpful to users to add a table which outlines the gradle & android studio versions compatible with Expo/RN so that the users can have a way back in their gradle-wrapper.properties file or so they know which version is compatible and which isn't.

**Comment by cruzach** [comment]
since Expokit ships with the correct version, you can always just eject a blank project, and check the version in `gradle-wrapper.properties`

**Comment by shamilovtim** [comment]
It would nuke the user's app icons, splash screens, permissions requests, associated domains, and all of the other platform specific custom configurations. Wouldn't it be easier to just document under ExpoKit / Android the Android Studio and Gradle compatibility so the user could pull it down without re-ejecting? I guess if you're trying to move away from ExpoKit it makes sense not to document it in depth but for now the Android build can really break in opaque ways due to these dependencies and Android studio. For instance, how do we know whether to *ever* upgrade Android studio or Gradle?

**Comment by cruzach** [comment]
Sorry, maybe I wasn't clear. You can start a brand new, completely separate project, and eject it to see the version it has pinned in that file

**Comment by shamilovtim** [comment]
Good points actually
