### ISSUE TITLE
Revise ReactAndroid changes to be sustainable for the next release

### ISSUE THREAD

**Issue by ide** [expo/expo#6262]
This commit here needs to be cleaned up so that when we do the next rebase, it's clearer what the changes are, especially when there's a merge conflict that we need to manually resolve: https://github.com/expo/react-native/commit/2a2663ff532439d7b8a98a1179558eb9e7824224

Also, we want to make sure our copy of RN still works with bare-expo, so the JS reloading features need to work in non-Expo apps too.

**Comment by sjchmiela** [comment]
Closed in https://github.com/expo/react-native/pull/20
