### ISSUE TITLE
[docs] Expo CLI is using Netinfo version ~2.0.10

### ISSUE THREAD

**Issue by travislang** [expo/expo#6266]
## Description

running `expo install @react-native-community/netinfo` installs version ~2.0.10 which doesn't work with the current docs both on expos website and in the netinfo README.

## Expected Behavior

Being able to use netInfos API like this:
```
const unsubscribe = NetInfo.addEventListener(state => {
  console.log('Connection type', state.type);
  console.log('Is connected?', state.isConnected);
});
```

## Observed Behavior

running the code gives a `Trying to subscribe to unknown event message` warning.
Here is a related issue on netinfo's repo:
https://github.com/react-native-community/react-native-netinfo/issues/93

I'm not sure if this is a mixup between the docs and the installed version but the current API documentation doesn't work with the version of netinfo that gets installed.  The fix is to use the old API:

https://github.com/react-native-community/react-native-netinfo/commit/47faad2470024339ee01b7af68e480eca15eee39?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

## Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.1 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.0.10

Also specify:

-iOS simulator - iPhone X

Either the docs should be updated to reflect the old API or the installed version should be updated

**Comment by expjess** [comment]
Closing this since SDK33 docs are now extinct; flagging this for @esamelson re: release process.
