### ISSUE TITLE
"Cannot start new build, as there is a build in progress " 

### ISSUE THREAD

**Issue by mayu-496** [expo/expo#6269]
"Cannot start new build, as there is a build in progress " stuck on this error .. when i login in my account it shows no builds exist

https://expo.io/@prashant.team/growler-prowler/builds this is my login account

What should I do? 
Thanks..

**Comment by mayu-496** [comment]
https://expo.io/@prashant.team/growler-prowler/builds this is my login account

**Comment by cruzach** [comment]
Hi @mayu-496, were you building for another project at the same time? It seems from our logs that you've been able to complete builds since posting this so maybe the issue is resolved?

**Comment by mayu-496** [comment]
yes this issue is resolve..

Thanks..
