### ISSUE TITLE
Can anyone change StatusBar backgroundColor?

### ISSUE THREAD

**Issue by niawinter** [expo/expo#6270]
Hi everyone,

it seems **backgroundColor** property of StatusBar doesn't work, in expo snack too.
Please check: https://snack.expo.io/@niawinter/statusbar_backgroundcolor

What do i wrong?

Properties **barStyle**, **hidden** and **translucent** work well.

**Comment by cruzach** [comment]
Closing as a duplicate of https://github.com/expo/expo/issues/2813

A good workaround for this is to configure status bar through app.json, just add

```
"androidStatusBar": {
      "backgroundColor": "#ffc0cb"
    },
```
to app.json (although you'll need to run your project locally for that)

**Comment by niawinter** [comment]
> Closing as a duplicate of #2813
> 
> A good workaround for this is to configure status bar through app.json, just add
> 
> ```
> "androidStatusBar": {
>       "backgroundColor": "#ffc0cb"
>     },
> ```
> 
> to app.json (although you'll need to run your project locally for that)

Hi @cruzach , thanks for your reply. I tried to change app.json, but nothing has changed, backgroundColor prop still inactive

**Comment by niawinter** [comment]
I restarted all, and now it works well. Thanks again!
