### ISSUE TITLE
Real bt barcode scanner with differences between Expo Client and native app

### ISSUE THREAD

**Issue by SK-DNS-NET** [expo/expo#6271]
## Description
I updated an app developed with expo, because provisioning profile runs out of date.
The app is running on an iPad 6 with via blue tooth connected real barcode scanner as keyboard. The tests with the expo client app run without problems. But with the built version of the app the scanner writes incomplete and wrong strings in to the textfields. In the iOS app “notes” all scanned barcodes are correct written.

## Expected Behavior
The values of the barcode scans are correct, same as Expo Client app version and previous native version.

## Observed Behavior
The values of the barcode scans are incomplete and/or wrong.
There is no error message.

Scan results:

`original 00040E-DC396F38C8F0`
`scan     0004DC39638C8F0K`

`original DNS117795`
`scan     DNS775`    

`original 4105550064093`
`scan     41050064093`    

## Environment
 Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v8.10.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^1.0.0-beta.27 => 1.5.12 
    npmGlobalPackages:
      expo-cli: 3.1.2

iPad 6 @ iOS 13.1.2, iPhone 8 @ iOS 13.1.2

## Reproducible Demo

Create an app with input textfield. Connect bluetooth scanner as keyboard with device and scan barcodes. Test it with expo client app and native app.

Thank you,
Stephan

**Comment by cruzach** [comment]
Not a very easy reproducible demo, you're using an external barcode scanner, right? Not the Expo SDK barcode scanner?

**Comment by SK-DNS-NET** [comment]
Hello Cruzach,
sorry for my late response. Yes, im using an external bluetooth barcode scanner without Expo SDK barcode scanner. It is handled as an external keyboard. 

Thanks,
Stephan

**Comment by cruzach** [comment]
Hey Stephan, I'm not exactly sure where the difference between the Expo Client and the standalone app would be in regards to using this external scanner as a keyboard. Maybe if you can provide more information on this, or a way for us to reproduce this ourselves, it might clear things up
