### ISSUE TITLE
It didn't install the Expo client to the Android emulator or open up my app

### ISSUE THREAD

**Issue by c617089219** [expo/expo#628]
When I run on genymotion Android emulator,it didn't install the Expo client to the emulator or open up my app inside of it, only display text message in web browser.  What did I miss?
_{"sdkVersion":"20.0.0","name":"AwesomeProject","slug":"awesomeproject","version":"0.1.0","xde":true,"developer":{"tool":"xde"},"packagerOpts":{"hostType":"lan","lanType":"ip","dev":true,"strict":false,"minify":false,"urlType":"http","urlRandomness":"2b-5jy"},"env":{},"bundleUrl":"http://192.168.0.25:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","debuggerHost":"192.168.0.25:19001","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://192.168.0.25:19000/logs"}_

**Comment by dikaiosune** [comment]
Hi! Sorry to hear you're having issues with this. What actions are you taking to end up there?

**Comment by terribleben** [comment]
Did you change your url configuration from `exp` to `http` by chance? Try switching it back to `exp`.

**Comment by c617089219** [comment]
I give up this way and trying "Building Projects with Native Code" and it succeeded!
