### ISSUE TITLE
[android] Location.GeofencingEventType.Enter getting called twice

### ISSUE THREAD

**Issue by YuryDG** [expo/expo#6283]
### Environment
Pixel Android 10, Emulator

### npmPackages:
```
"expo": "33.0.7"
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
"expo-location": "7.0.0",
"expo-task-manager": "7.0.0",
```

### Expo diagnostics
```
Expo CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - C:\Users\my-user\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
```

### Steps to Reproduce

Start geofencing with specific regions

 ```
import * as Location from 'expo-location'

Location.startGeofencingAsync(taskName, regions)
```
Let's call the regions A (first) and B(the 2nd one). I'll replace the regions ID to better understanding 

**A -> 5dc96f5012892600119df8b8**

**B -> 5dc96f8d12892600119df8b9**
```
[
  {
      "identifier": "A",
      "latitude": 42.66948587788525,
      "longitude": 23.351275976747278,
      "notifyOnEnter": true,
      "notifyOnExit": true,
      "radius": 245,
    },
    {
      "identifier": "B",
      "latitude": 42.698528709750214,
      "longitude": 23.30798713490367,
      "notifyOnEnter": true,
      "notifyOnExit": true,
      "radius": 431,
    },
  ],
```
On the main app file there is a task running in the background

```
import * as Location from 'expo-location';
import * as TaskManager from 'expo-task-manager';

TaskManager.defineTask(MY_TASK_NAME, ({ data: { eventType, region }, error }) => {
  if (error) {
    // check `error.message` for more details.
    return;
  }
  if (eventType === Location.GeofencingEventType.Enter) {
    console.log("You've entered region:", region);
  } else if (eventType === Location.GeofencingEventType.Exit) {
    console.log("You've left region:", region);
  }
});
```

### Expected Behavior

Entering to region A console output should be 

```
You've entered region: Object {
  "identifier": "A",
  "latitude": 42.66948587788525,
  "longitude": 23.351275976747278,
  "radius": 245,
  "state": 1,
}
```

After that, exiting from region A and entering to region B console output is
```
You've entered region: Object {
  "identifier": "B",
  "latitude": 42.698528709750214,
  "longitude": 23.30798713490367,
  "radius": 431,
  "state": 1,
}

You've left region: Object {
  "identifier": "A",
  "latitude": 42.66948587788525,
  "longitude": 23.351275976747278,
  "radius": 245,
  "state": 2,
}
```
### Actual Behavior

Entering to region A console output is 
```
You've entered region: Object {
  "identifier": "5dc96f5012892600119df8b8",
  "latitude": 42.66948587788525,
  "longitude": 23.351275976747278,
  "radius": 245,
  "state": 1,
}

Perfect output.
```

After that, exiting from region A and entering to region B console output is

```
You've entered region: Object {
  "identifier": "B",
  "latitude": 42.698528709750214,
  "longitude": 23.30798713490367,
  "radius": 431,
  "state": 1,
}

You've entered region: Object {
  "identifier": "B",
  "latitude": 42.698528709750214,
  "longitude": 23.30798713490367,
  "radius": 431,
  "state": 1,
}

You've left region: Object {
  "identifier": "A",
  "latitude": 42.66948587788525,
  "longitude": 23.351275976747278,
  "radius": 245,
  "state": 2,
}
```
Any tips? Am I doing something wrong?

**Comment by cruzach** [comment]
So the problem is that it's calling `Location.GeofencingEventType.Enter` twice?

Have you tested this on iOS and it works, or you've only tested Android?

**Comment by YuryDG** [comment]
The problem is that when I'm in a region, exit from the region and I enter to another region, I'm receiving two notification of entering.

I only tested on Android device, 
I tested on my device, Android 9, Xiaomy Redmi Note 6 Pro.
I also connect the expo with an android emulator, I used PIXEL X phone - API 29.

**Comment by rosnaib11** [comment]
Same issue to me

**Comment by sinisa-nimcevic** [comment]
I have the same problem, the task is defined at App.js globel scope level, and I've went through and checked that it gets attached only once, so my console log ends up like this:
[Mon Jul 20 2020 08:18:59.999]  LOG      ===geoFencingTask=== attached
[Mon Jul 20 2020 08:19:00.285]  LOG      ===geoFencingTask=== called with eventType 1
[Mon Jul 20 2020 08:19:00.290]  LOG      You've entered region: DH
[Mon Jul 20 2020 08:19:00.368]  LOG      ===geoFencingTask=== called with eventType 1
[Mon Jul 20 2020 08:19:00.370]  LOG      You've entered region: DH
[Mon Jul 20 2020 08:19:00.398]  LOG      ===geoFencingTask=== called with eventType 2
[Mon Jul 20 2020 08:19:00.399]  LOG      You've left region: ZSINAGOGA

**Comment by doongsilee** [comment]
seems like this problem still exist. Is there any workaround?

**Comment by JavaScriptJohn** [comment]
I'm having this issue as well. For me I have an array of 4 regions. On android if I enter 1 region it will alert me 4 times that I entered the actual region i'm in.

**Comment by Patafix** [comment]
Same issue here any news ?

**Comment by abdulbasitideofuzion** [comment]
I have same issue. I'm using expo-location to get location updates in the background and this method called twice. I'm not understanding why it is happening.
