### ISSUE TITLE
[docs] imagepicker multipleselection is web-only

### ISSUE THREAD

**Issue by MonstroDev** [expo/expo#6284]
### Environment
Dependency:
```
"expo-image-picker": "~7.0.0",
```
Expo CLI 3.4.1 environment info:
```
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.12.0 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.4.1
```

### Steps to Reproduce
```
import * as ImagePicker from 'expo-image-picker';

let result = await ImagePicker.launchImageLibraryAsync({
  allowsMultipleSelection: true,
})
```

### Expected Behavior

I want to select multiple files and as a result, get an array of images objects

### Actual Behavior

Result is:
```
Object {
  "cancelled": false,
  "height": 4032,
  "type": "image",
  "uri": "file:/data/user/0/host.exp.exponent/cache/ExperienceData/%2540username%252FAppName/ImagePicker/39abd44a-96c6-45b2-b42f-4fdb6b9ee289.jpg",
  "width": 2268,
}
```

### Reproducible Demo

https://snack.expo.io/@monstrodev/expoimagepicker

**Comment by cruzach** [comment]
Sorry, we need to document this better but I believe `allowsMultipleSelection` is web-only

**Comment by MonstroDev** [comment]
> Sorry, we need to document this better but I believe `allowsMultipleSelection` is web-only

@cruzach Oh, What I need to use for multiple photo selection?

**Comment by cruzach** [comment]
According to [this feature request](https://expo.canny.io/feature-requests/p/allow-choosing-multiple-images-in-imagepicker), you have to build your own multiple image selector, using the imagepicker and cameraroll apis
