### ISSUE TITLE
WebBrowser.openAuthSessionAsync returns "dismiss" even when the user successfully logged in

### ISSUE THREAD

**Issue by DianaKoenraadt** [expo/expo#6289]
## 🐛 Bug Report
We're doing OAuth2 and the user logs in using `WebBrowser.openAuthSessionAsync`. If the user dismisses the browser without logging in, we catch this by checking `result.type == "dismiss"`.

Unfortunately, we *always* get `'dismiss'`, even if the user logged in succesfully. That means our check for whether the browser was dismissed is useless now.

### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203

App target is Android.

### Steps to Reproduce

0. Attach a listener to handle linking.

       Linking.addEventListener('url', this.handleOpenURL);

1. Use openAuthSessionAsync to redirect to OAuth2

            const redirectUrl = await Linking.makeUrl(...);
            var result = await WebBrowser.openAuthSessionAsync(
                uri +
                '?response_type=code' +
                '&client_id=' + process.env.OAUTH_CLIENT_ID +
                '&redirect_uri=' + encodeURIComponent(redirectUrl) +
                '&state=' + challenge.state +
                '&code_challenge=' + challenge.code_challenge +
                '&code_challenge_method=' + challenge.method);

2. Right after the await, check the result type for the case where the user canceled the login.

        if (result.type == "dismiss") {
            // Browser was dismissed without logging in. 
            this.setState({ ...this.state, status: 'ERROR', message: "Our error message" });
        }

3. Open the browser and successfully log in.

### Expected Behavior

The user logs in and does not see the error that is associated with `'dismiss'`. The message `"Our error message"` should not be shown.
In essence, in code I expected `type == "opened"`, because the user didn't cancel. 

### Actual Behavior

The error message is shown briefly :(
After a short pause, the listener catches the redirect and processing the succesful login continues as expected. 

I created this as a question, not an issue, because I don't know if there is another way I should be handling the `type == "dismiss"` instead of right after the `await`. Any suggestions are most welcome.

**Comment by cruzach** [comment]
Hi! 

So `{ type: 'dismiss' }` is returned whenever the WebBrowser is closed with `dismissBrowser`. It might be more useful for you to check for `{ type: 'cancel' }` to check if the user closed the web browser

**Comment by DianaKoenraadt** [comment]
Do I still need to call `dismissBrowser` when handling the callback? If so, how do I distinguish between that and the user closing the browser without logging in? Because that also gives `{ type: 'dismiss'}`, as I see from my code behavior.

**Comment by cruzach** [comment]
Hm I just tested that and I'm getting a result of `{ type: 'cancel' }` in that situation

**Comment by schellack** [comment]
@cruzach the documentation on [Handling deep links from the WebBrowser says](https://docs.expo.io/versions/latest/sdk/webbrowser/#handling-deep-links-from-the-webbrowser):

> be sure to add a handler with `Linking.addEventListener` before opening the browser. When the listener fires, you should call `dismissBrowser`

The older Expo example repo also does this [here](https://github.com/expo/examples/blob/bdd79383b540b33d34ea01b6793098585127fc75/with-webbrowser-redirect/app/App.js#L32).

So I think that may be where @DianaKoenraadt's last question was coming from.

Based on my testing with Expo SDK 36, if you call `WebBrowser.openAuthSessionAsync` and then cancel the modal web browser on iOS, you get a result.type of 'cancel'. If you do the same on Android you get a result.type of 'dismiss'. The two are inconsistent.

I would expect both platforms to never return 'open' (unless you are calling `WebBrowser.openBrowserAsync` instead of `WebBrowser.openAuthSessionAsync`, since they behave differently on Android).

Another confusing thing in all this:
The documentation for both [dismissBrowser](https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowserdismissbrowser) and [openAuthSessionAsync](https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl) says they are iOS only. And yet using `WebBrowser.openAuthSessionAsync()` on Android not only seems to work, but works much better than trying to roll your own version with vanilla `WebBrowser.openBrowser`.

Perhaps that could also be clarified?

**Comment by schellack** [comment]
It looks like the specific line of code that is emitting the 'dismiss' value for `result.type` on Android is [here](https://github.com/expo/expo/blob/52eda002430daa57357727a3b887bd1b5abd458e/packages/expo-web-browser/src/WebBrowser.ts#L155):

```javascript
async function _openBrowserAndWaitAndroidAsync(startUrl: string): Promise<BrowserResult> {
  let appStateChangedToActive = new Promise(resolve => {
    _onWebBrowserCloseAndroid = resolve;
    AppState.addEventListener('change', _onAppStateChangeAndroid);
  });

  let result: BrowserResult = { type: 'cancel' };
  let { type } = await openBrowserAsync(startUrl);

  if (type === 'opened') {
    await appStateChangedToActive;
    result = { type: 'dismiss' };
  }

  AppState.removeEventListener('change', _onAppStateChangeAndroid);
  _onWebBrowserCloseAndroid = null;
  return result;
}
```

The above code in WebBrowser is called for Android from `_openAuthSessionPolyfillAsync`. From what I've seen of `WebBrowser.openBrowserAsync`, it always returns a `result.type` of 'open', which means that the code on line 155 if going to overwrite a type of 'cancel' with a type of 'dismiss' in every case.

**Comment by cruzach** [comment]
Closing this in favor of 6679 since it is more detailed and includes a solution (possibly a forthcoming PR, as well 😄 )

**Comment by danlordan** [comment]
For those that still couldn't find an answer, my answer was just adding the redirectUrl into the query. On iOS I didn't need to - `const result = await WebBrowser.openAuthSessionAsync(authUrl)` worked fine. But on Android I needed to add the second param - `const result = await WebBrowser.openAuthSessionAsync(authUrl, redirectUri)` like here - https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl

**Comment by mrchess** [comment]
Just ran into this issue on Expo 43 on my Pixel 4 API 30 simulator. The above comment to set `redirectUri` seems to have resolved it.

**Comment by travishoki** [comment]
> Just ran into this issue on Expo 43 on my Pixel 4 API 30 simulator. The above comment to set `redirectUri` seems to have resolved it.

@danlordan @mrchess I'm experiencing this issue. What `redirectUri` did you use as a fix? There's a lot of confusing information on constructing a redirectURl using combinations of `useProxy` and `scheme`.

**Comment by danlordan** [comment]
@travishoki I stopped using expo a while ago but the `redirectUri` I used was my app uri. If I can help at all - DM me on twitter https://twitter.com/DanJLordan and we can talk!

**Comment by travishoki** [comment]
Still experiencing this. I haven't been able to get a `redirectUri` to work for fixing the issue yet.

**Comment by dylanlewis89** [comment]
@travishoki for me it matched the `redirectUri` that was passed to the Auth Service I was using. In my case, this was Auth0 and I was actually brokering a logout, so my code looks like this. Note how the `redirectUri` passed into my `logoutUri` const is the same as the `redirectUri` passed as the second argument to `openAuthSessionAsync`

```
const logoutUri = `https://${config.auth.domain}/v2/logout?client_id=${clientId}&returnTo=${redirectUri}`
WebBrowser.openAuthSessionAsync(
  logoutUri,
  redirectUri,
  { preferEphemeralSession: true } // this avoids iOS users from seeing a login prompt
  // https://community.auth0.com/t/swift-login-alert-shows-up-when-you-logout/21598
).then(() => {// success})
```

**Comment by travishoki** [comment]
I'm so confused. I'm just trying to get Google Login working on the Android Standalone app. I've been stuck on this for month and don't even know if I'm on the right thread anymore. :(

**Comment by Armster15** [comment]
For those struggling to create a redirectUri, you can use [`expo-linking`](https://docs.expo.dev/versions/latest/sdk/linking/).

```tsx
import * as Linking from 'expo-linking';
const redirectUri = Linking.createURL("/");
let login = await WebBrowser.openAuthSessionAsync(url, redirectUri);
```

**Comment by carlaTatiana** [comment]
`let login = await WebBrowser.openAuthSessionAsync(url, redirectUri)`

Always returns type: dismiss on Android.

**Comment by Darren120** [comment]
SOLUTION!

If your site is deeplinking like: com.fck.you://
the create redirectUri will make com.fck.you:///
just copy ur scheme/ bundle and use com.fck.you://  as redirectUri

this solution was brought to you in the name of JESUS.
pray to the Lord and repent for your sins
