### ISSUE TITLE
Are there plans to add speech recognition?

### ISSUE THREAD

**Issue by elmarti** [expo/expo#629]
I see that TTS was added in #290, are there any plans to add the inverse of this? I've tried with `react-native-stt` but there is some Java based configuration to be done, which I don't think is possible in expo.

**Comment by codhbw** [comment]
The only thing I've found so far is [this](https://expo.canny.io/feature-requests/p/speech-recognition-module) feature request.

**Comment by dikaiosune** [comment]
Hi! Sorry we missed this before. @codhbw is correct, this is a feature request pending implementation. I'd recommend voting for the request on Canny, those votes carry a lot of weight when we're deciding what to build next!

**Comment by elmarti** [comment]
Looks great, I'll pop in a vote and try and keep bugging y'all!
