### ISSUE TITLE
style={{height:'100%'}} doesn't work on Android in apk in landscape but works in debug

### ISSUE THREAD

**Issue by ExpoNfinity** [expo/expo#6293]
Trying to make fullscreen image gallery with landscape support, imposition is like there:
<View style={{height:'100%', width:'100%'}}>
<Image resizeMode='contain' style={{height:'100%',width:'100%',borderColor:'#00ffff',borderWidth: 10}}/>
</View>
In debug mode borders match screen borders in both landscape and portrait, in apk in landscape mode behavior of render is different, i don't see bottom border and seeing near half of image. 

### Environment:
Using latest sdk 35.
Expo CLI 3.7.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Users\User\AppData\Roaming\npm\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

### How to reproduce:
import React from "react";
import {
    View,
    Image,
} from "react-native"; 
import { ScreenOrientation } from 'expo'

componentDidMount() {
        ScreenOrientation.unlockAsync()
}
render() {
return <View style={{height:'100%', width:'100%',backgroundColor:'#ffffff',}}>
<View style={{height:'100%',width:'100%',backgroundColor:'#ff0000',borderColor:'#00ffff',borderWidth: 10}}/>
< / View> //remove spaces
}

### Expected behavior: 
border visible at all sides of screen in both landscape and portrait
### Actual Behavior: 
in debug everything is fine, in apk version in landscape mode actual height is much higher than screen, bottom border is not visible

**Comment by deodorhunter** [comment]
I'm seeing the same behavior when using <Video> component in landscape mode with the same styling.  Debug is fine and APK is not, video gets cut in half and I loose player controls.

**Comment by ExpoNfinity** [comment]
Any update on this? This is a critical bug when debug does not match retail.

**Comment by bbarthec** [comment]
Hello there! @deodorhunter please provide MVP [snack](snack.expo.io) for this issue - that would be a lot easier for us to check the issue and provide any valid feedback (possibly a fix).

**Comment by ExpoNfinity** [comment]
hi @bbarthec as we've said, the issue is visible with ***APK ONLY*** 
Have you tried to build apk using the code you've asked already with new issue creation form?
Do your guys always respond to critical issues after 4 months, changing 3 assigned persons?

**Comment by bbarthec** [comment]
@ExpoNfinity, we're quite a small team taking care of many modules and many more issues, so we cannot handle everything immediately. Any contribution from community is welcome though and you can contribute as well (this is an open source project after all and it's also free of charge so well... 😉) 🎉
Nevertheless, I'll give this problem a shot in the next couple of days, but no promises yet 😉

**Comment by bbarthec** [comment]
@ExpoNfinity, I've confirmed that the issue you're reporting is present in SDK36, but I can also assure you that in SDK37 it's already fixed 🎉
Please try it yourself with SDK37 and `expo-screen-orientation` module 😊
As I've tested that this problem no longer exists in SDK37, I'm closing this issue. Please comment or reopen if there's anything more connected with this issue that is not resolved.

**Comment by ExpoNfinity** [comment]
Sounds good, we'll try in next days, thx
