### ISSUE TITLE
Bare workflow ios build fail after creating project - Ts

### ISSUE THREAD

**Issue by DavidNeiOs** [expo/expo#6297]
### Environment

```
Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.8.0
```

Target iOs after creating the project and doing `pod install`

### Steps to Reproduce
1. expo init --name--
1. Select Typescript bare workflow
1. cd ios && pod install
1. cd ..
1. yarn ios

### Expected Behavior

See App.tsx screen

### Actual Behavior

<img width="347" alt="Screen Shot 2019-11-17 at 5 23 02 PM" src="https://user-images.githubusercontent.com/40399577/69015305-a2bc9600-0960-11ea-82df-8cef77d1d47b.png">

first line says `Failed to load bundle(http://loacalhost:8081/...`
### Reproducible Demo

This happens in a newly created project

**Comment by brentvatne** [comment]
is it possible that you have a react-native packager instance running for another project already?

**Comment by DavidNeiOs** [comment]
@brentvatne Oh you are right ! I didn't realize I yarn start in a different project. Thank you so much!
