### ISSUE TITLE
Print doesn't print local images

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [expo/expo#6299]
### Environment

  Expo CLI 3.7.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.12 => 32.0.13 
      @types/react-navigation: ^3.0.6 => 3.0.8 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.1 

app target: Standalone iOS and Android

### Steps to Reproduce

If you try to print anything with a local image, it doesn't work. Printing with a remote image works though!

### Expected Behavior

It prints local images too

### Actual Behavior

Local images are not shown.

Tried in expo shell app and standalone app.

related issue: https://github.com/christopherdro/react-native-print/issues/65

### Reproducible Demo

```
<Button
          title="Images print"
          onPress={() =>
            Print.printAsync({
              html: `
<html>
<body>

<div style="height:101%; margin: 20px">
This is the text for page #1.<br />
${images.map(c => {
    console.log("c.", c.uri);
    return `<img src="${c.uri} style="border:3px;" width="100" height="100" />`;
  })}

  <img src="https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500" style="border:3px;" width="100" height="100" />

</div>


<div style="height:101%; margin: 20px">
This is the text for page #2.
</div>


<div style="height:101%; margin: 20px">
This is the text for page #3.
</div>


</body>
</html>
        `
            })
          }
        />
```

**Comment by cruzach** [comment]
Hi! This was reported in this issue https://github.com/expo/expo/issues/6057 but was closed for lack of a reproducible demo

Can you put together a snack that shows fully reproduces this behavior? It makes debugging/fixing a whole lot easier on our part
