### ISSUE TITLE
Does exp:build also perform an exp:publish?

### ISSUE THREAD

**Issue by Foosballfan** [expo/expo#63]
I have seen that the data updates automatically on client apps once there is an exp:publish.

My concern is that when testing an app you need to exp:build and it may publish an unsuitable release to all client applications.

If so, is there any way to prevent this issue?

**Comment by jesseruder** [comment]
Yes, right now it always performs a publish. That's a good point that you won't always want that. We can work on making that optional soon.

**Comment by Foosballfan** [comment]
Thanks for the reply Jesse, looking forward to the update.

Once the app goes live I'll stick to development from the server until the publish becomes optional.

**Comment by jesseruder** [comment]
Actually @Foosballfan can you elaborator on your use case a little more?

**Comment by Foosballfan** [comment]
Hi Jesse,

The reason I would want to build the app into an APK is to do testing, for example using Amazon App Testing service.

I also like the idea of testing the fully compiled build in case anything goes wrong between the development server and the final release.

Maybe some sort of roll back service might alleviate my concerns with doing a publish.

**Comment by jesseruder** [comment]
Ok testing the final APK is a great reason to want this. Will try to figure out a good solution soon.

In the meantime you could simulate a staging app by changing the `slug` field in exp.json before publishing.

**Comment by dikaiosune** [comment]
We're now tracking this as [a feature request on Canny](https://expo.canny.io/feature-requests/p/add-parameter-on-build-ie-exp-buildiosandroid-to-disable-publishing-to-expo-serv). Thanks!

**Comment by andersravn** [comment]
@anp This feature was never addressed on Canny. They just closed it as it addressed another issue.

**Comment by gregbenner** [comment]
Yeah https://expo.canny.io/feature-requests/p/add-parameter-on-build-ie-exp-buildiosandroid-to-disable-publishing-to-expo-serv is marked as completed but not the same issue as this Github one. CC @anp

**Comment by anp** [comment]
Hi! You can run `exp build:{ios,android} --no-publish` if you want to avoid publishing altogether, but you can also specify a release channel like so:

`exp build:ios --release-channel CHANNEL_NAME`

So if you want to test an APK before releasing your changes to live clients, you could create a build with `exp build:ios --release-channel testing-feature-name`. Once you're confident that you want to ship the change, you can use the `exp publish history` and `exp publish set` commands to promote that release from your testing channel to your production/default channel. There's also an `exp publish rollback` option if you make a mistake here.

I *think* that all of these features cover the original request, so I'll lock this issue now. If there are still elements of this request that we don't support, please open a new issue so it's easier to track! Thanks :D
