### ISSUE TITLE
Push notification status on Android always returning granted

### ISSUE THREAD

**Issue by lilosir** [expo/expo#630]
Hey, I called following function on Android to get the current status, 
`const { existingStatus }  = await Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);` 

it only returns **granted** even I turn off from system settings. Any ideas? BTW, the response should be **status** instead of **existingStatus**, v19.0.0, right?

**Comment by dikaiosune** [comment]
Hi! What Android version and device is this happening on?
