### ISSUE TITLE
expo calendar: all day events change between gets

### ISSUE THREAD

**Issue by tasn** [expo/expo#6301]
### Environment

Can't run `expo diagnostics`: `Cannot read property '1' of null`
Though this shouldn't matter for this bug.

This is on iOS.

### Steps to Reproduce

Create an all day event:
```
const eventId = await Calendar.createEventAsync(containerId, {
  title: 'Yet another',
  allDay: true,
  startDate: new Date('2019-01-12T00:00:00.000Z'),
  endDate: new Date('2019-01-13T00:00:00.000Z'),
});

const event = await Calendar.getEventAsync(eventId);
console.log('Old: ', event);


setTimeout(async () => {
  // Wait a while, may potentially only work after app restart
  const event2 = await Calendar.getEventAsync(eventId);
  console.log('New: ', event2);
}, 3000);
```

### Expected Behavior

Expected behaviour is to have both event fetches return the same event on the first fetch as on a later fetch..

### Actual Behavior

For the example above, the output is below. Look at the different original start date and the start date fields.

```
Old:  Object {                                               
  "alarms": Array [],                              
  "allDay": true,                             
  "availability": "notSupported",                    
  "calendarId": "775CB6AD-C941-4EE1-A3A9-70463FCF41C9",
  "creationDate": "2019-11-18T09:13:52.400Z",          
  "endDate": "2019-01-12T21:59:59.000Z",
  "id": "6D900769-DA09-4178-B0C3-9AD004F0AE9A",
  "isDetached": false,    
  "lastModifiedDate": "2019-11-18T09:13:52.404Z",       
  "location": "",                               
  "notes": "",           
  "organizer": null,     
  "originalStartDate": "2019-01-12T00:00:00.000Z",
  "startDate": "2019-01-12T00:00:00.000Z",            
  "status": "none", 
  "timeZone": null,
  "title": "Yet another",                           
  "uid": "920a89c1-3a12-421f-bb90-c8e8de798dee",
  "url": null,
}
New:  Object {                                                                                                                          
  "alarms": Array [],                                                                                                                   
  "allDay": true,                                                                                                                       
  "availability": "notSupported",
  "calendarId": "775CB6AD-C941-4EE1-A3A9-70463FCF41C9",
  "creationDate": "2019-11-18T09:13:52.400Z",
  "endDate": "2019-01-12T19:59:59.000Z",                                                                                                
  "id": "6D900769-DA09-4178-B0C3-9AD004F0AE9A",
  "isDetached": false,                                                                                                                  
  "lastModifiedDate": "2019-11-18T09:13:52.404Z",                                                                                       
  "location": "",
  "notes": "",                                                                                                                          
  "organizer": null,
  "originalStartDate": "2019-01-11T22:00:00.000Z",
  "startDate": "2019-01-11T22:00:00.000Z",
  "status": "none",
  "timeZone": null,
  "title": "Yet another",
  "uid": "920a89c1-3a12-421f-bb90-c8e8de798dee",
  "url": null,
}
```

Even though `lastModifiedDate` remains the same, the startDate and originalStartDate change.
I assume this is because iOS is using local time for event dates (not sure how it does it for all day events) and that expo is processing these values differently. Though it may as well just be an iOS bug.
I'm also not sure if events are only returned in local time, or also returned in local time. It's hard to say because the expo docs say nothing about this, and the iOS docs are lacking.
Either way there is some inconsistency depending on when you fetch the event which makes it very hard (impossible?) to correctly handle the returned events.

### Reproducible Demo

I tried to make a snack, but snack doesn't seem to support expo-calendar (it's stuck on trying to create the event).
https://snack.expo.io/rJlGP1x2B

**Comment by tasn** [comment]
CC @tsapeta (as requested)

**Comment by lukmccall** [comment]
I've tried to reproduce this. Unfortunately, I didn't get the same result as you.

Here is my output from iOS 13 (it's correct):
```
Old:  Object {
  "alarms": Array [],
  "allDay": true,
  "availability": "notSupported",
  "calendarId": "41EEFAC0-2482-4662-8B8A-C1CA6483B266",
  "creationDate": "2019-11-20T08:04:38.927Z",
  "endDate": "2019-01-13T22:59:59.000Z",
  "id": "948A4404-C04C-4617-964C-545AF85656B4",
  "isDetached": false,
  "notes": null,
  "organizer": null,
  "originalStartDate": "2019-01-11T23:00:00.000Z",
  "startDate": "2019-01-11T23:00:00.000Z",
  "status": "none",
  "timeZone": null,
  "title": "Yet another",
  "url": null,
}
New:  Object {
  "alarms": Array [],
  "allDay": true,
  "availability": "notSupported",
  "calendarId": "41EEFAC0-2482-4662-8B8A-C1CA6483B266",
  "creationDate": "2019-11-20T08:04:38.927Z",
  "endDate": "2019-01-13T22:59:59.000Z",
  "id": "948A4404-C04C-4617-964C-545AF85656B4",
  "isDetached": false,
  "lastModifiedDate": "2019-11-20T08:04:38.929Z",
  "notes": null,
  "organizer": null,
  "originalStartDate": "2019-01-11T23:00:00.000Z",
  "startDate": "2019-01-11T23:00:00.000Z",
  "status": "none",
  "timeZone": null,
  "title": "Yet another",
  "url": null,
}
```

However, I've faced a different issue which may be related. 
On iPhone 5, I got an event normally for the first try.  But what is weird is that when I called `getEventAsync()` again, I got an error - `couldn't find event`.

I'll try to investigate this again today.

**Comment by tasn** [comment]
I wonder if it's related to #6302, maybe I was passing an empty timezone here too (instead of undefined) which was causing issues.

Have you tried also doing it after restarting the application (or in general, waiting for a few minutes).

I'm testing on a 5S with iOS 12.4.2.

**Comment by lukmccall** [comment]
Yes, I tried restarting the application - the same result.

I don't think that is related to the `timezone` issue. When you didn't write `timeZone` explicitly, the iOS saving an event with the current device time zone value. I curious what happened if you get an event, then you close the application and change the time zone setting. Next, you try to get the same event.

**Comment by tasn** [comment]
I'm saying that when testing, my code probably set the timeZone to an empty string.

**Comment by lukmccall** [comment]
Oh, sorry I miss understand you. Could you test it again?

**Comment by tasn** [comment]
I'll try to test it this week, but may have to wait until the weekend. Don't worry about this issue for now then, wait for my update.

I do still wonder what's going on with it not finding events for you.

**Comment by tasn** [comment]
I can no longer reproduce it, I guess it was related to #6302. I'm sorry for the noise.

Closing.
