### ISSUE TITLE
Expo calendar: end date is incorrect when creating events

### ISSUE THREAD

**Issue by tasn** [expo/expo#6302]
### Environment

Can't run `expo diagnostics`: `Cannot read property '1' of null`
Though this shouldn't matter for this bug.

This is on iOS.

### Steps to Reproduce

When creating events, expo (iOS?) requires you pass wrong/bad end dates for it to create the events at the correct time. For example, to create an event that is one day long on the 5th of November, you need to create it like this:
```
    const eventId = await Calendar.createEventAsync(containerId, {
      "allDay": true,
      "startDate": new Date("2019-11-05T00:00:00.000Z"),
      "endDate": new Date("2019-11-04T22:01:00.000Z"),
      "timeZone": "",
      "title": "All day 5",
    });
```
Instead case you missed it: the end date is 2 hours before the start date (my timezone offset)! It doesn't work if you pass a correct end date, or even an end date that's equal to start date.
This is the same with events spanning multiple days, not just 1 day long. It's just that the example is most obvious like this.

It does error (I assume from iOS?) if you pass end dates that are more than 24 hrs before the start date, so I assume something is wrong with a conversion in Expo or something.

### Expected Behavior

Don't allow end dates before the start date, and use the end date passed correctly.

### Actual Behavior

The end date seems to be offset by a day and you can therefore use end dates that are before the start date.

### Reproducible Demo

https://snack.expo.io/SkyjiyxnS

Snack doesn't seem to support creating events, but you can just run it on your device and test there.

**Comment by tasn** [comment]
CC @tsapeta (as requested)

**Comment by lukmccall** [comment]
I've tested your demo. At first glance, everything seemed to work fine. Then I've realised that you passed an empty string as a `timeZone`. 

Here is a code which we used to set the time zone: 
```
  if (timeZone) {
    calendarEvent.timeZone = [NSTimeZone timeZoneWithName:timeZone];
  } else if (details[@"timeZone"] == [NSNull null]) {
    calendarEvent.timeZone = nil;
  }
```
You provided `timeZone` so the first condition will be true. Then you override default timeZone value with `nil`. This made that dates were wrongly interpreted.

**Comment by tasn** [comment]
I just tried again with setting timezone to `undefined` and it's still broken. I'll give it a proper look again tomorrow, though I don't think this fixes it.

**Comment by tasn** [comment]
OK, I can confirm it works, thanks a lot!

Maybe worth it to add an error if timezone is ''?

**Comment by lukmccall** [comment]
> OK, I can confirm it works, thanks a lot!
> 
> Maybe worth it to add an error if timezone is ''?

Yes, I've added it in this [PR](https://github.com/expo/expo/pull/6326)

**Comment by tasn** [comment]
Oh I missed it. Great, thanks.
