### ISSUE TITLE
[iOS 13] weird behavior w/ Slider when `step` set >0

### ISSUE THREAD

**Issue by cruzach** [expo/expo#6305]
### Environment

SDK 35

### Steps to Reproduce

create Slider component with `step` prop:
```
<Slider
  value={this.state.value}
  onValueChange={value => this.setState({ value })}
  step={0.5}
/>
```

https://snack.expo.io/@charliecruzan/slider-bug

### Expected Behavior

Slider should move in increments equal to the step.

### Actual Behavior

Slider behaves erratically

### Reproducible Demo

https://snack.expo.io/@charliecruzan/slider-bug

**Comment by gasolin** [comment]
seems fine when step < 1, ex:  `step={0.01}`, but has issue when `step={20}`

**Comment by cruzach** [comment]
resolved in https://github.com/expo/expo/pull/8451
