### ISSUE TITLE
Expo 35 updateContactAsync is failing on Android

### ISSUE THREAD

**Issue by shineforth** [expo/expo#6306]
I reported this issue on the forums: https://forums.expo.io/t/expo-35-android-updatecontactasync-is-failing/30080

Contacts.updateContactAsync fails on android, whether in expo app on android or if through an apk file installed on Android. Contacts.updateContactAsync works fine on iOS with no issues.

Here's the important part of my app.json.

    "expo": {
        "name": "xxxxxxxxxx",
        "slug": "xxxxxxxxxx",
        "scheme": "xxxxxxxxxx",
        "privacy": "unlisted",
        "sdkVersion": "35.0.0",
        "android": {
            "package": "xxx.xxxxxxxxxx.xxxx",
            "googleServicesFile": "./google-services.json",
            "versionCode": 2,
            "permissions": [
            "android.permission.ACCESS_COARSE_LOCATION",
            "android.permission.ACCESS_FINE_LOCATION",
            "android.permission.CAMERA",
            "android.permission.VIBRATE",
            "android.permission.READ_CONTACTS",
            "android.permission.READ_EXTERNAL_STORAGE",
            "android.permission.READ_PHONE_STATE",
            "android.permission.WRITE_CONTACTS",
            "android.permission.WAKE_LOCK",
            "android.permission.WRITE_EXTERNAL_STORAGE",
            "com.anddoes.launcher.permission.UPDATE_COUNT",
            "com.android.launcher.permission.INSTALL_SHORTCUT",
            "com.google.android.c2dm.permission.RECEIVE",
            "com.google.android.gms.permission.ACTIVITY_RECOGNITION",
            "com.google.android.providers.gsf.permission.READ_GSERVICES",
            "com.htc.launcher.permission.READ_SETTINGS",
            "com.htc.launcher.permission.UPDATE_SHORTCUT",
            "com.majeur.launcher.permission.UPDATE_BADGE",
            "com.sec.android.provider.badge.permission.READ",
            "com.sec.android.provider.badge.permission.WRITE",
            "com.sonyericsson.home.permission.BROADCAST_BADGE"
        ],

Here's a simple code example of what I am trying to do.

    const { status, expires, permissions } = await Permissions.getAsync(Permissions.CONTACTS);
    console.log('status: ', status);
    console.log('permissions: ', permissions);
    let contact = await Contacts.getContactByIdAsync('478');
    contact.phoneNumbers.push({
        isPrimary: 0,
        label: 'home',
        number: '402-999-9999',
        type: '2'
    });
    console.log('contact: ', contact);
    return Contacts.updateContactAsync(contact)
        .then(response => console.log('Success!'))
        .catch(error => console.log('error: ', error));

When I run expo start and test it locally in the expo client (QR code) on an Android Moto e5 play device I get the following console log messages with the error at the end:

    Running in development...
    Running application on moto e5 play.
    status:  granted
    permissions:  Object {
        "contacts": Object {
        "expires": "never",
        "status": "granted",
     },
    }
    contact:  Object {
        "company": "xxxxxxxxxxx",
        "contactType": "person",
        "emails": Array [
            Object {
                "email": "xxxxxxxxxxx@xxxxxx.com",
                "id": "1788",
                "isPrimary": 1,
                "label": "home",
                "type": "1",
            },
            Object {
                "email": "xxxxxxxxxxx@xxxxxx.com",
                "id": "3019",
                "isPrimary": 0,
                "label": "home",
                "type": "1",
            },
        ],
        "firstName": "Xxxxxxxx",
        "id": "478",
        "image": Object {
        "uri": "content://com.android.contacts/contacts/478/photo",
        },
        "imageAvailable": true,
        "lastName": "Xxxxxxxxx",
        "lookupKey": "xxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxx",
        "name": "Xxxxxx xxxxxxxxx",
        "phoneNumbers": Array [
            Object {
                "id": "1787",
                "isPrimary": 1,
                "label": "mobile",
                "number": "XXX-XXX-XXXX",
                "type": "2",
            },
            Object {
                "id": "3018",
                "isPrimary": 0,
                "label": "mobile",
                "number": "XXX XXX-XXXX",
                "type": "2",
            },
            Object {
                "isPrimary": 0,
                "label": "home",
                "number": "402-999-9999",
                "type": "2",
            },
        ],
    }
    error:  [Error: Missing write contacts permission.]

Earlier when I was not running it through a try catch the following was the console log error message:

    Missing write contacts permission.
    - node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
    - node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
    - ... 4 more stack frames from framework internals

I hid sensitive info with xxxx's but you can see that my object gets added to the contact then expo is returning that error. This is on local development in the expo client app on an Android phone. I've also tested this same logic/code on an apk file that I installed on the same android phone.

One thing I noticed is that on iOS even though I don't specify an id field for the PhoneNumber object that I add, iOS generates a id for it. I'm not sure if Android requires an id field before calling the updateContactAsync?

**Comment by cruzach** [comment]
Hi- as it says in the [Contacts docs](https://docs.expo.io/versions/v35.0.0/sdk/contacts/), `updateContactAsync` is iOS only at the moment. But, on Android, you can use `presentFormAsync` to make edits to contacts. Just remember:
> For Android users, the Expo client App does not have the required `WRITE_CONTACTS` permission to write to Contacts. In order to do this, you must build a standalone app and add permission through there.

So basically, it'll have to be a standalone app to use the method

**Comment by shineforth** [comment]
Standalone meaning eject from expo? Or using a bare workflow?

I've deployed this as an apk file with permissions in the app.json and it still would not work to use the expo updateContactAsync. Are there no examples of how to do this within expo as a managed app?

**Comment by cruzach** [comment]
Standalone as in not running in the Expo Client app, so as an apk or ipa (we have a [guide for building standalone apps](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/))

As I said, `updateContactAsync` is iOS only so it won't work on Android. you'll have to use `presentFormAsync`
