### ISSUE TITLE
[docs] Filter out highly noisy error messages

### ISSUE THREAD

**Issue by ide** [expo/expo#6308]
There are some errors that are very noisy on the docs site (e.g. in some kind of loop) and aren't due to our code (could be ISP injection or browser extension). We need to filter these out.

I looked into Sentry's source code a bit to figure out how best to do this. It looks like overriding the onerror handler is *not* a good way to do this, but IIRC Sentry provides (used to provide?) ways to specify a callback for whether or not to report an error. That seems like a good mechanism.

**Comment by brentvatne** [comment]
dats fixed
