### ISSUE TITLE
npm install causes tunneling errors

### ISSUE THREAD

**Issue by JCDJulian** [expo/expo#631]
New to expo here, so I'm not sure if I'm missing something obvious.

I can install expo and get the new projects up and running no problem. But the issue comes when I run npm install. It installs a lot of dependencies - this might be my limited knowledge of npm showing, but I'm not sure why all of those new dependencies appear. After it finishes, the connection to my client no longer works. Instead I get an HTML response saying "Failed to complete tunnel connection. The connection to {my url} was successfully tunneled to your ngrok client, but the client failed to established a connection to the local address. Make sure that a web service is running [...]"

What's the failure point here? Are you not supposed to run npm install in the folder root?

**Comment by JCDJulian** [comment]
Should mention that I'm using:
npm 3.5.2
Bash on Ubuntu for Windows

**Comment by dikaiosune** [comment]
Hi! I'm not sure that watchman (which react native uses for detecting changed files) will work correctly within Ubuntu for Windows. What happens if you use XDE in a plain ol' Windows environment?
