### ISSUE TITLE
Live stream in expo-av with protocol rtmp

### ISSUE THREAD

**Issue by tacnoman** [expo/expo#6315]
Hello guys.

I want to use the expo-av as a client to stream audio using the protocol rtmp

In the documentation I only found examples with `require("./path/to/file.mp3")`.

Is possible to connect in a protocol rtmp to listen live audios?

Thanks for this

**Comment by cruzach** [comment]
Looks like this was added back in SDK 25, see [this issue](https://github.com/expo/expo/issues/1187). In the future, questions like this are better off posted on our [forums](https://forums.expo.io/) instead of Github
