### ISSUE TITLE
[android] apk runs slower than app in Expo Client

### ISSUE THREAD

**Issue by Apple-Zeroa** [expo/expo#6316]
Dear expo,

When i run and test my app by using expo start, the app run smoothly and without buggie.
However, when i created apk by expo build:android the apps run slow during create calendar.

### expo build:android

Apk generated by expo:build android doesn't work well on  createFamsEvent()
Below is the link of my apk:
https://play.google.com/store/apps/details?id=com.inetsoho.famsexpo

App created should run on android phone.

### Expected Behavior

Standalone apk should running smoothly and create calendar instantly like what is testing during expo start.

![Simulator Screen Shot - iPhone Xʀ - 2019-11-19 at 15 25 58](https://user-images.githubusercontent.com/43272938/69125546-ff46bf00-0ae0-11ea-932f-8cb060fe45f4.png)

![Simulator Screen Shot - iPhone Xʀ - 2019-11-19 at 15 26 11](https://user-images.githubusercontent.com/43272938/69125552-0241af80-0ae1-11ea-9855-859d8343b792.png)

### Actual Behavior

Standalone apk running laggy and create calendar after 30 minutes after user click "ok" to create calendar at homepage.

![Simulator Screen Shot - iPhone Xʀ - 2019-11-19 at 15 25 58](https://user-images.githubusercontent.com/43272938/69125541-f9e97480-0ae0-11ea-9a1e-125b86555f7a.png)

## May I know why the standalone apk build doesn't work as expo start.

Thanks,
Apple

**Comment by Apple-Zeroa** [comment]
Dear expo,

my expo version is sdk 35

Thanks,
Apple

**Comment by cruzach** [comment]
It might help you debug to run it locally in production mode with `expo start --no-dev --minify`

I also suggest running your app with the [react profiler](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) open to get a better idea of performance. Not sure why it would run slower in the Expo Client though. If anything, it should be running faster in production mode than in dev mode

**Comment by Apple-Zeroa** [comment]
Dear @cruzach ,

First of all, thanks for the reply.
Im using react native to build my app so i not able to use react profiler to check my app performance.
Besides, I have run it locally in production mode with expo start --no-dev --minify.
The app run smoothly by using expo client app.

However, the app still run laggy when i build it as apk and run the apk.

## The app is already in production mode. The apk having same coding as i run in expo client.

### 1) May I know what is the reason the apk run slowly as i build it with expo build:android?
### 2) How could i debug in apk mode. As when i test in expo client there is no error and run smoothly.


Thanks, 
Apple

**Comment by cruzach** [comment]
You can use the profiler with react-native projects, see [this guide we wrote up](https://docs.expo.io/versions/latest/workflow/debugging/)

Hopefully running your app through the profiler will reveal the performance bottlenecks

**Comment by hharchani** [comment]
We're facing the exact same problem. The app is very smooth in the expo client, but its working very slow  when we built apk using `expo build:android` command

**Comment by cruzach** [comment]
We'll need a reproducible demo to investigate this issue, so far I have not been able to see any noticeable loss in performance when going from developing in the Expo Client app to an APK

**Comment by Alishba90** [comment]
i have the same issue my expo runs fine in expo client but very laagy in production mode . I can share my git repo if you want . Could you please look into it ?

**Comment by matheusleaao** [comment]
Same problem here. We have our backend on AWS. Expo client runs fast when get the image on S3, but after APK generation, we have a delay to load profile images

**Comment by simamkele44** [comment]
Experiencing the same problem, any solution @Apple-Zeroa ?

**Comment by GeorgeFlorian** [comment]
I am experiencing  the same exact thing. 
I am creating the android directory using `npx expo prebuild --platform android` and installing the dev build using `npx run:android`.
I use Android Studio to build the actual APK in release mode.

The app is fast in dev mode and unusable after building the release apk.

**Comment by dibyopra** [comment]
same issue here
