### ISSUE TITLE
Prevent going back to initial route when saving a file (Hot reload) 

### ISSUE THREAD

**Issue by rosnaib11** [expo/expo#6317]
Is it only me that every time I save my file it compiles and reload BUT keep going back to initial route screen of my app. Or its just normal? Its not too much bothering but to optimize my workflow. Especially on nested routes when it reloads it goes back to start, and I have to click couple screens to reach my destination screen.

**Comment by cruzach** [comment]
That's normal right now. We do provide the hot reload feature, which should result in , but when we release SDK 36 we will be providing support for Fast Refresh instead - https://facebook.github.io/react-native/docs/fast-refresh

This is the PR adding in Fast Refresh https://github.com/expo/expo/pull/6110
