### ISSUE TITLE
the bug  about the expo-barcode-scanner 

### ISSUE THREAD

**Issue by zwjjap** [expo/expo#6319]
hi ,everyone；
I found some problems in using expo-barcode-scanner on ios ；the app can scan datamatrix except the datamatrix code on the machine；I find that the DataMatrix generated with the same string is different from that of the machine；I'm sure it's the same  Bar code format on DataMatrix ；
![image](https://user-images.githubusercontent.com/13042642/69139148-e0edbd00-0afa-11ea-9bd1-86d57990d537.png)

Note: the left can be swept, the right can not

How to solve it

thanks!

**Comment by cruzach** [comment]
How are you generating the bar code on the right? When you say it can't scan it, do you mean nothing happens, or the app crashes? Following the issue template we provide would be very helpful

Here's a snack- https://snack.expo.io/@documentation/barcodescanner-example -  to test scanning barcodes with

**Comment by zwjjap** [comment]
> How are you generating the bar code on the right? When you say it can't scan it, do you mean nothing happens, or the app crashes? Following the issue template we provide would be very helpful
> 
> Here's a snack- https://snack.expo.io/@documentation/barcodescanner-example - to test scanning barcodes with
> 
en, i mean  nothing happens，the app did not crash; 
the QR code is not generated  by me; it was generated  by the manufacturer on the machine

**Comment by cruzach** [comment]
If you can dig through the device logs during that crash, that would help in exploring the root cause of the crash
