### ISSUE TITLE
KeepAwake doesn't work with some libraries

### ISSUE THREAD

**Issue by wandersage** [expo/expo#6324]
### Environment

My app not using expo.

My app target iOS and Android. I've tested only on android.

### Steps to Reproduce

I just tried to use `activateKeepAwake` and `deactivateKeepAwake`  in my component and this doesn't have any results, but `useKeepAwake` works if I call it in App function before store, persistence and navigation setup. 

My App function
```
export const App = (): React.ReactElement => {
  useKeepAwake();
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <StatusBar barStyle="light-content" />
        <AppNavigationContainer />
      </PersistGate>
    </Provider>
  );
};
```
Navigation components
```
export const AppNavigationContainer = createAppContainer(RootSwitch);
export const RootSwitch = createSwitchNavigator({
  [Routes.Login]: Login,
  [Routes.Activity]: Activity,
  [Routes.ActivityList]: ActivityListStack,
  [Routes.Splash]: Splash,
}, {
  initialRouteName: Routes.Splash,
});
```

### Expected Behavior

Screen keeps awake after calling `activateKeepAwake`

### Actual Behavior

Screen goes off. 

### Reproducible Demo

Unfortunately I can't share my app code. I'll try to make simple demo from it near time.
<details>
<summary>Dependencies</summary>
<br>

- "expo-keep-awake": "^7.0.0",
- "react": "16.9.0",
- "react-native-unimodules": "0.7.0-rc.4",
- "react-native": "0.61.2",
- "react-native-vector-icons": "6.6.0",
- "react-navigation": "4.0.10",
- "react-navigation-stack": "1.9.4",
- "react-redux": "^7.1.1",
- "redux": "^4.0.4",
- "redux-logger": "3.0.6",
- "redux-persist": "6.0.0",

</details>

**Comment by cruzach** [comment]
When you make the demo, it's best if you can do it on a bare `expo init` project

**Comment by wandersage** [comment]
I've reinstalled it and for 2nd try it works.
