### ISSUE TITLE
[android] Unable to retrieve the FCM server key for the recipient's app

### ISSUE THREAD

**Issue by jacobjohn90** [expo/expo#6328]
## 🐛 Bug Report
I followed the FCM documentation and got status OK when i uploaded the api-key and I am also able to retrieve it when I put expo push:android:show, but when I send a push notification from my server, I get this response:
```{  "error": { "code": null, "message": "Unable to retrieve the FCM server key for the recipient's app. Make sure you  have provided a server key as directed by the Expo FCM documentation." }}```
I get this error every time.
Any help would be greatly appreciated!

There was one topic that stated the expo owner of this app changed. We are currently using the expo team workflow with an owner flag in our app.json and built the app (expo build:android) with the owner flag, so this user currently owns the application. Does the expo:push:android:upload command work with the owner flag?

### Environment

SDK 35, android devices

### Steps to Reproduce

Triggering a push notification with our server or with the expo push notification tool

### Expected Behavior

To retrieve a push notification on android phones

### Actual Behavior

```
{
   "error": { 
      "code": null, 
      "message": "Unable to retrieve the FCM server key for the recipient's app. Make sure you 
                            have provided a server key as directed by the Expo FCM documentation." 
   }
}
```

**Comment by cruzach** [comment]
Hi! Thanks so much for reporting this, we'll look into it. It's possible that command may need to be run from the team owner account. 

Could you send an email to secure@expo.io with your account name, and we can look into it on the backend, as well?

**Comment by jacobjohn90** [comment]
Thank you so much! sent the email along with the owner account name and project name.

**Comment by jacobjohn90** [comment]
I tried removing the owner key in the app.json file and made a new build from my account. I then pushed the server key after but I am still getting that error.

**Comment by Fokus969** [comment]
After updating to version 35, we had the same problem. Is a solution found? Notifications come if the application is launched through EXPO, but they do not come through the APK. Why?

**Comment by cruzach** [comment]
@Fokus969 are you using the Teams feature? If so, the key has to be uploaded by the team owner (that was the case in this issue)

**Comment by cruzach** [comment]
Closing in favor of https://github.com/expo/expo-cli/issues/1294

**Comment by kadirguloglu** [comment]
is solution provided? I have the same problem. sdk38

**Comment by WeZinc** [comment]
same here

**Comment by cruzach** [comment]
We have an open issue for this here- https://github.com/expo/expo/issues/8905

Please provide a reproducible demo there
