### ISSUE TITLE
Getting "Error starting tunnel: Error: Starting tunnels timed out"

### ISSUE THREAD

**Issue by Lipsa1st** [expo/expo#633]
Hello,
I am new to react-native, and had created one project at the time of loading it is showing "Error starting tunnel: Error: Starting tunnels timed out",
I switched between Lan and Tunnel still facing same issue,
I also run the ngrok , and restarted but it was also not helpful to me ,

Each time coming like

Restarting project and clearing packager cache (Hold shift while clicking restart to avoid clearing cache).
11:26:20 PM
Starting React Native packager...
11:26:24 PM
Scanning 531 folders for symlinks in E:\React-Native\myregistrationpage\myregistrationpage\registrationpage\myreg\lipsa\my-new-project\node_modules (42ms)
11:26:24 PM
11:26:36 PM
Error starting tunnel: Error: Starting tunnels timed out
11:26:36 PM
Project opened! You can now use the "Share" or "Device" buttons to view your project.
11:27:05 PM
Dependency graph loaded.

Can you help me to get rid of this problem

**Comment by rijkerd** [comment]
Also encountering the same problem any help.

**Comment by AbhayShiro** [comment]
I am facing the same problem in Expo XDE


```
Installing Expo on device
11:59:55 AM
Restarting project and clearing packager cache (Hold shift while clicking restart to avoid clearing cache).
12:00:30 PM
Starting React Native packager...
12:00:33 PM
Scanning 531 folders for symlinks in F:\Users\Freeware Sys\Desktop\reactnative\expo\my-new-project\node_modules (28ms)
12:00:33 PM
12:00:46 PM
Error starting tunnel: Error: Starting tunnels timed out
12:00:46 PM
Project opened! You can now use the "Share" or "Device" buttons to view your project.
```

**Comment by saikrishnanaru** [comment]
Guys how u solved this problem...

**Comment by terribleben** [comment]
@fson maybe we should just improve the error message here, explaining what went wrong and giving a recommendation for what to do instead.

**Comment by huzaifasaeed** [comment]
same problem what to do?
expo.io

**Comment by podeig** [comment]
The same problem here: 

12:54:46
Starting React Native packager...
12:54:49
Scanning folders for symlinks in /Users/denis/Geo/Dev/udemy-swipe/node_modules (10ms)
12:54:49
Loading dependency graph.
12:54:49
Running packager on port 19002.
12:54:49
12:54:52
Dependency graph loaded.
12:54:59
Error starting tunnel: Error: Starting tunnels timed out
12:54:59
Project opened! You can now use the "Share" or "Device" buttons to view your project.

**Comment by saikrishnanaru** [comment]
guys i found by re-starting project it will solve

**Comment by cdbBinary** [comment]
restarting worked for after several times. I notice when I open expo at the start all is clean. But when I open simulators and something hicups on restart I get the same error. I wonder if I need to close down my simulators restart then re-open simulators. Seems like there is an order of operations. 

I agree the explanation should drilldown deeper but expo really doesn't offer enough meat, so I hear both sides for sure.

**Comment by kohli11** [comment]
can organization firewall cause this problem ? Any help would be appreciated.

**Comment by SalahAdDin** [comment]
I have the same problem with the last version in linux.

**Comment by mchen37** [comment]
I am also running into this problem sometimes. After the XDE update, it's still happening but they added a new error message.

> Switched to a LAN URL because the tunnel appears to be down. Only devices in the same network can access the app. You can restart the project to try reconnecting.

As for organization firewall, I don't think it is the issue. Sometimes tunnel works for me, sometimes it does not. I am always on org wifi though. It seems random as to when it does start working.

**Comment by dikaiosune** [comment]
Hi everyone! Because we don't control the network tunnel (we use ngrok under the hood) there's not a lot we can do beyond providing better errors when the tunnel isn't connecting. For troubleshooting, I'd recommend trying to connect to the tunnel on a different network, trying switching to LAN mode, or restarting your computer.

In the future we may offer our own network tunneling provider and be able to debug these things at a lower level but our team doesn't have bandwidth to work on this just yet.

**Comment by RyanPWalker** [comment]
I constantly run into this error.  It'd be awesome if you guys offered your own tunneling or options for troubleshooting the tunnels.

**Comment by matteo-pennisi** [comment]
Uninstalling and reinstalling Expo XDE worked for me.
Hope it helps

**Comment by NaveenDK** [comment]
what does 'only devices on the same network can access the app ' mean?
both o my devices  on the same network?

**Comment by neutronixx** [comment]
Hi, the same problem, any idea?

**Comment by charlesdeb** [comment]
I also don't want to install Android studio on my computer - my hard drive is too full. I was only able to get round this one by putting the Genymotion version of `adb` onto my path, installing `exp` and then using the command line: `exp android`.

**Comment by danibjor** [comment]
Got the same problem today. Found out the issue  was an invalid entry in `app.json` - to be more presice, the `google-service.json` path was invalid

```
  "expo":
    "android": {
      "googleServicesFile": "invalid/path/here/google-services.json"
```

If you open the share-uri from Expo XDE in the browser, it might give you a hint on what's wrong. localhost:19000 on my browser displayed this error message:

```
{
"error": "Error: ENOENT: no such file or directory, open '/Users/daniel/projects/apps/test-app/google-services.json'"
}
```

Manually fixing the entry `app.json` solved my issue.
