### ISSUE TITLE
Can i disable hardware overview button (a recent button)  on a phone in expo?

### ISSUE THREAD

**Issue by pavlov-sergey-alexandr** [expo/expo#6331]
I need disable a recent button (phone button). It is possible to implement this functionality when using expo?
About disable recent button when use react native i didn't find any thing  

Please help me!

**Comment by ide** [comment]
I'm not sure what the "hardware overview button" is but on Android you can hide some of the system buttons as of SDK 35: https://docs.expo.io/versions/latest/workflow/configuration/#androidnavigationbar. If that doesn't address the question you're asking, I'd recommend using the [bare workflow](https://docs.expo.io/versions/v35.0.0/introduction/managed-vs-bare/#bare-workflow) and writing whatever code you need for this feature.
