### ISSUE TITLE
empty array return for await Location.geocodeAsync(address)

### ISSUE THREAD

**Issue by Apple-Zeroa** [expo/expo#6332]
Dear expo,

# I have use await Location.geocodeAsync(address) to retrieve lat, long for address key in for expo client in android phone, it return empty array.

getGeocodeLocation location Array [] 

# However, when i test using ios stimulator, it return array object as below(im using same address: kl).
getGeocodeLocation location Array [
  Object {
    "accuracy": 100,
    "altitude": 0,
    "latitude": 3.135985,
    "longitude": 101.6726903,
  },
]

Here is my code:
https://snack.expo.io/@appleckp/d9fd9b

Thanks, 
Apple

**Comment by Apple-Zeroa** [comment]
Dear expo,

Im using sdk35 expo and test in real android device phone.

Thanks,
Apple

**Comment by cruzach** [comment]
Hi! I put together [this example snack](https://snack.expo.io/@charliecruzan/geolocationexample) that uses geocodeAsync, and tested it on android and it's working 👍 

Your snack wasn't running for me, I suggest using the snack I provided to help you debug. Good luck!
