### ISSUE TITLE
Unable to remove DocumentPicker files with FileSystem.deleteAsync

### ISSUE THREAD

**Issue by NotifydLLC** [expo/expo#6335]
### Environment
  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.6 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.8.0

App Target: iOS, Android, Standalone

### Steps to Reproduce

1. Use DocumentPicker to select a file from one of your phone's file locations (doesn't matter which one, can be local to the phone or from a cloud storage provider).
2. After retrieving the file, it will be located in the app's tmp directory. Try to remove this tmp file explicitly by calling FileSystem.deleteAsync(uri).

### Expected Behavior
File is deleted from the file system.

### Actual Behavior
An error is thrown with description: Location 'FILE_PATH_HERE' isn't deletable.

### Reproducible Demo
https://snack.expo.io/SkfIh0z3B

**Comment by NotifydLLC** [comment]
Just to add some more color to the issue, I found that iOS and Android are inconsistent in what type of uri DocumentPicker.getDocumentAsync returns.

Android returns a URI that references an authority and its relative path as described here (https://developer.android.com/reference/android/content/ContentUris), whereas iOS appears to download a copy of the file to the app's tmp folder.

The reason I include this is because I would assume FileSystem should not (and probably cannot) extend to cloud storage providers, and therefore the expected behavior described above may not fit all use cases. In this case, I'm trying to think what the best way to detect the source of the file is for Android so I know when to call FileSystem.deleteAsync. Without extending the object DocumentPicker provides back, I would need to examine the ContentURI authority and determine if it's a local authority that falls under the scope of FileSystem.

**Comment by cruzach** [comment]
I think this is probably due to your setting `copyToCacheDirectory: false`. Set that value to true, and was able to delete the file. From the docs: 
> copyToCacheDirectory (boolean) -- If true, the picked file is copied to FileSystem.CacheDirectory, which allows other Expo APIs to read the file immediately

Any particular reason you aren't copying to cache directory?

**Comment by NotifydLLC** [comment]
It depends on what "copy" means in "copyToCacheDirectory".

For iOS, does "copy" mean that the file will be located in both the app's tmp folder as well as the expo cache folder? If so, we would still want to remove the tmp file. If it means that it stores the file in the cache directory as opposed to the tmp folder, then I think you probably identified a solution for us - in which case the property name is what threw me off.

For Android, it appears like the file is being accessed at the source URI and not being copied anywhere, so for our application this isn't an issue - however, this issue still does exist for Android if the expected behavior is that it removes the file from the phone (or the cloud storage provider).

**Comment by cruzach** [comment]
Hm @bbarthec might know the answer to that

**Comment by lukmccall** [comment]
Hi @NotifydLLC, I've tried to investigate your problem. Here is what I found:
- iOS
  - picked files are always copied to the temporary directory. When you chose `copyToCacheDirectory` options, there are also copied to the expo dir (you should delete it).
  - you shouldn't bother deleting them from the application dir because they will be clean up. According to the Apple documentation, `The URL refers to a copy of the selected document. This document is a temporary file. It remains available only until your application terminates. To keep a permanent copy, you must move this file to a permanent location inside your sandbox.`. 
- Android
  - when `copyToCacheDirectory` is false, then `DocumentPicker` doesn't copy your file. It only returns a URI. So, you don't have to clean up. 
  - when `copyToCacheDirectory` is true, then the file is copied to expo dir and you should delete it.

**Comment by NotifydLLC** [comment]
Thanks for looking into this @lukmccall. I believe my use case is satisfied, so I'm happy to see this issue closed.

It might be worth expanding the documentation on the "copyToCacheDirectory" setting or linking to any other documentation you were able to reference. The differences between MediaPicker, DocumentPicker, ImagePicker, and how they all work with (and without) FileSystem is a bit confusing at the moment.
