### ISSUE TITLE
Network.getNetworkStateAsync isInternetReachable returns nothing on Android when it goes offline

### ISSUE THREAD

**Issue by okeybond** [expo/expo#6338]
## 🐛 Bug Report

```
export const isInternetReachable = async () => {
    let {isInternetReachable} = await Network.getNetworkStateAsync();
    return isInternetReachable;
};
```

### Environment

 Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.16.2 - /usr/local/opt/node@8/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.4.0

Android

### Expected Behavior

Network.getNetworkStateAsync isInternetReachable  should return false on Android when it goes offline

### Actual Behavior

Network.getNetworkStateAsync isInternetReachable returns nothing on Android when it goes offline, it works fine for iOS

**Comment by esamelson** [comment]
Hi there -- sorry for the slow response here. I wasn't able to reproduce this issue -- when the device was offline `isInternetReachable` was `false` for me, as expected. If you are still experiencing this issue, please open a new ticket and include a fully reproducible example demonstrating the problem, ideally a snack. (A code snippet is not enough as context is just as important.) Thanks!

**Comment by ronaiza-cardoso** [comment]
I have the same issue:

https://snack.expo.io/@rcardoso/network.getnetworkstateasync
