### ISSUE TITLE
not working on ios

### ISSUE THREAD

**Issue by mayu-496** [expo/expo#6341]
Whenever i start the recorder everythig gets disabled.. recording never get start..

**Comment by cruzach** [comment]
Audio recorder? Video recorder? If you're having trouble getting these set up, I recommend reading through our docs, and here are some examples that I had that are able to use both with no issues:

Video recorder - https://snack.expo.io/@charliecruzan/examplerecordasync

Audio recorder repo - https://github.com/expo/audio-recording-example

If you you run into a bug, please fill out the entire bug report template, thanks!

**Comment by mayu-496** [comment]
Audio recorder.. 
https://snack.expo.io/@git/github.com/expo/audio-recording-example

Above is the link os snack code which I'm using . It works fine on Android but not on iOS..

Thanks..

**Comment by cruzach** [comment]
What is the error? Like I said, you need to fill out the full bug report template for us to help you effectively

**Comment by mayu-496** [comment]
There is no error .. its just not working ... I don't know why.. I'm not getting any errors.. Actually I'm new to it..
Thanks..
Below is my code.
import React from 'react';
import {
  Dimensions,
  Image,
  Slider,
  StyleSheet,
  Text,
  TouchableHighlight,
  View,
  ScrollView,
  TextInput,
  ToastAndroid,
  BackHandler,
  Button
} from 'react-native';
//import { Audio, FileSystem, Font, Permissions } from 'expo';
import { Audio } from 'expo-av';
import * as FileSystem from 'expo-file-system';
import * as Font from 'expo-font';
import * as Permissions from 'expo-permissions';
import { Asset } from 'expo-asset';
import { Card, Icon, Header } from 'react-native-elements';
import firebase from '@firebase/app';
import "firebase/auth"
import "firebase/database"
import "firebase/storage"
import { GradientButton } from './../components/';
import Spinner from 'react-native-loading-spinner-overlay';

class Icons {
  constructor(module, width, height) {
    this.module = module;
    this.width = width;
    this.height = height;
    Asset.fromModule(this.module).downloadAsync();
  }
}

const ICON_START_RECORD = new Icons(require('../assets/images/mic_start.png'), 70, 119);
const ICON_STOP_RECORD = new Icons(require('../assets/images/mic_stop.png'), 70, 119);
const ICON_RECORDING = new Icons(require('../assets/images/record_icon.png'), 20, 14);

const ICON_PLAY_BUTTON = new Icons(require('../assets/images/play_button.png'), 34, 51);
const ICON_PAUSE_BUTTON = new Icons(require('../assets/images/pause_button.png'), 34, 51);
const ICON_STOP_BUTTON = new Icons(require('../assets/images/stop_button.png'), 22, 22);

const ICON_MUTED_BUTTON = new Icons(require('../assets/images/muted_button.png'), 67, 58);
const ICON_UNMUTED_BUTTON = new Icons(require('../assets/images/unmuted_button.png'), 67, 58);

const ICON_TRACK_1 = new Icons(require('../assets/images/track_1.png'), 166, 5);
const ICON_THUMB_1 = new Icons(require('../assets/images/thumb_1.png'), 18, 19);
const ICON_THUMB_2 = new Icons(require('../assets/images/thumb_2.png'), 15, 19);

const { width: DEVICE_WIDTH, height: DEVICE_HEIGHT } = Dimensions.get('window');
const BACKGROUND_COLOR = '#ffffff';
const LIVE_COLOR = '#FF0000';
const DISABLED_OPACITY = 0.5;
const RATE_SCALE = 3.0;

export default class Answer_Screen extends React.Component {
  constructor(props) {
    super(props);
    this.recording = null;
    this.sound = null;
    this.isSeeking = false;
    this.shouldPlayAtEndOfSeek = false;
    this.state = {
      haveRecordingPermissions: false,
      isLoading: false,
      disable: false,
      isPlaybackAllowed: false,
      muted: false,
      soundPosition: null,
      soundDuration: null,
      recordingDuration: null,
      shouldPlay: false,
      isPlaying: false,
      isRecording: false,
      fontLoaded: false,
      start: false,
      shouldCorrectPitch: true,
      next: false,
      searchString: '',
      volume: 1.0,
      rate: 1.0,
      message: 'this is test call',
    };
    this.recordingSettings = JSON.parse(JSON.stringify(Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY));
    this.handleBackButtonClick = this.handleBackButtonClick.bind(this);
  }
  componentWillMount() {
    // This is the first method in the activity lifecycle
    // Addding Event Listener for the BackPress 
    BackHandler.addEventListener('hardwareBackPress', this.handleBackButtonClick);
  }
  componentWillUnmount() {
    // This is the Last method in the activity lifecycle
    // Removing Event Listener for the BackPress 
    BackHandler.removeEventListener('hardwareBackPress', this.handleBackButtonClick);
  }

  handleBackButtonClick = () => {
    this.props.navigation.goBack(null);
    //BackHandler.exitApp();
    // ToastAndroid.show('Exit !', ToastAndroid.SHORT);
    return true;
  }

  componentDidMount() {
    (async () => {
      await Font.loadAsync({
        'cutive-mono-regular': require('../assets/fonts/CutiveMono-Regular.ttf'),
      });
      this.setState({ fontLoaded: true });
    })();
    this._askForPermissions();
  }

  _askForPermissions = async () => {
    const response = await Permissions.askAsync(Permissions.AUDIO_RECORDING);
    this.setState({
      haveRecordingPermissions: response.status === 'granted',
    });
  };

  _updateScreenForSoundStatus = status => {
    if (status.isLoaded) {
      this.setState({
        soundDuration: status.durationMillis,
        soundPosition: status.positionMillis,
        shouldPlay: status.shouldPlay,
        isPlaying: status.isPlaying,
        rate: status.rate,
        muted: status.isMuted,
        volume: status.volume,
        shouldCorrectPitch: status.shouldCorrectPitch,
        isPlaybackAllowed: true,
      });
    } else {
      this.setState({
        soundDuration: null,
        soundPosition: null,
        isPlaybackAllowed: false,
      });
      if (status.error) {
        console.log(`FATAL PLAYER ERROR: ${status.error}`);
      }
    }
  };

  _updateScreenForRecordingStatus = status => {
    if (status.canRecord) {
      this.setState({
        isRecording: status.isRecording,
        recordingDuration: status.durationMillis,
      });
    } else if (status.isDoneRecording) {
      this.setState({
        isRecording: false,
        recordingDuration: status.durationMillis,
      });
      if (!this.state.isLoading) {
        this._stopRecordingAndEnablePlayback();
      }
    }
  };

  async _stopPlaybackAndBeginRecording() {
    this.setState({
      isLoading: true,
    });
    if (this.sound !== null) {
      await this.sound.unloadAsync();
      this.sound.setOnPlaybackStatusUpdate(null);
      this.sound = null;
    }

    try {
      await Audio.setAudioModeAsync({
        allowsRecordingIOS : true,
        interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
        playsInSilentModeIOS: true,
       
        shouldDuckAndroid: true,
        interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      });
    } catch (error) {
      // alert(error) // eslint-disable-line
    }
    
    if (this.recording !== null) {
      this.recording.setOnRecordingStatusUpdate(null);
      this.recording = null;
    }
    const recording = new Audio.Recording();

    try {

      await recording.prepareToRecordAsync(Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY);
      await recording.startAsync();
      // You are now recording!
    // await recording.prepareToRecordAsync(this.recordingSettings);
    recording.setOnRecordingStatusUpdate(this._updateScreenForRecordingStatus);
    this.recording = recording;
    // await this.recording.startAsync(); // Will call this._updateScreenForRecordingStatus to update the screen.
    this.setState({
      isLoading: false,
    });
  } catch (error) {
    console.log(error);
  }
  }

  handleAddMessage = (type, message, question, Qkey) => {
    const path = "answers";
    const { currentUser } = firebase.auth();
    let newMessage = {
      created: firebase.database.ServerValue.TIMESTAMP,
      email: currentUser.email,
      uid: currentUser.uid,
      authorPhotoUrl: currentUser.photoURL,
      question: question.question,
      languageCode: 'en-US',
      type
    }
    if (type === 'image') {
      newMessage.image = message
    } else if (type === 'location') {
      newMessage.location = message
    } else if (type === 'audio') {
      newMessage.audio = message
    } else {
      if (message.startsWith('http') || message.startsWith('https')) {
        newMessage.link = message
        newMessage.type = 'link'
      } else {
        newMessage.message = message
      }
    }
    this.setState({ searchString: '' });
    if (message && message.length > 0) {
      if (Qkey) {
        firebase
          .database()
          .ref(`${path}/${currentUser.uid}/${Qkey}`)
          .update(newMessage)
      } else {
        firebase
          .database()
          .ref(`${path}/${currentUser.uid}/${Qkey}`)
          .push(newMessage)
      }

      if (type === 'text') {
        ToastAndroid.show('Answer Sent Successfully !', ToastAndroid.SHORT);
      }
    }
  }

  handleFileSubmit(file, question, Qkey) {
    const path = "answers";
    const receiverPath = "answers";
    const { currentUser } = firebase.auth();
    if (file === null) {
      return
    }
    if ((file.size / 1024 / 1024).toFixed(4) > 20) {
      //file larger than 10mb
      //alert(intl.formatMessage({ id: 'max_file_size' }))
      return
    }

    const metadata = {
       contentType: 'audio/mp3',
      // mimeType:'audio/ogg; codecs=opus',
      customMetadata: {
        path,
        receiverPath,
        Qkey,
        languageCode: "en-US",
      }
    }
    let uploadTask = firebase
      .storage()
      .ref(`/user_chats/${currentUser.uid}/${Qkey}.mp3`)
      .put(file, metadata)
    console.log("key = " + Qkey);
    uploadTask.on(
      'state_changed',
      snapshot => {
        var progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100
        console.log('Upload is ' + progress + '% done')

        this.setState({
          sending: true,
          uploadCompleted: progress
        })
        
        setTimeout(() => {

          if(this.state.sending == true)
          {
            alert("Internet Connection is slow");
            this.setState({
              sending: false,
              // isLoading: true,
              disable: false,
              next: false,
              uploadCompleted: 0
            })
          }
          }, 20000)

        console.log('Upload is ' + this.state.uploadCompleted + '% done')
      },
      error => {
        console.log(error)
      },
      () => {
        this.setState({
          sending: false,
          uploadCompleted: undefined
        })

        uploadTask.snapshot.ref.getDownloadURL().then(downloadURL => {
          this.handleAddMessage('audio', downloadURL, question, Qkey)

        })
      }
    )
  }
  async _stopRecordingAndEnablePlayback(question, Qkey) {
    this.setState({
      isLoading: true,
      disable: true,
      next: true,
      uploadCompleted: 0
    });
    try {
      await this.recording.stopAndUnloadAsync();
    } catch (error) {
      // Do nothing -- we are already unloaded.
    }

    const info = await FileSystem.getInfoAsync(this.recording.getURI());
    console.log(`FILE INFO: ${JSON.stringify(info)}`);
    // const response = await fetch(info.uri);
    // const blob = await response.blob();
     
     const blob = await new Promise((resolve, reject ) => {

      const xhr = new XMLHttpRequest();
      xhr.onload = function () {
        resolve(xhr.response);
      };
      xhr.onerror = function (e) {
        console.log(e);
        reject(new TypeError('Network request failed'));
      };
      xhr.responseType = 'blob';
      xhr.open('GET', info.uri, true);
      xhr.send(null);
    });

    this.handleFileSubmit(blob, question, Qkey);
    // blob.close();
    try {
      await Audio.setAudioModeAsync({
        allowsRecordingIOS : true ,
        interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
        playsInSilentModeIOS: true,
         playsInSilentLockedModeIOS: true,
        shouldDuckAndroid: true,
        interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      });
    } catch (error) {
      // alert(error) // eslint-disable-line
    }
    const { sound } = await this.recording.createNewLoadedSound(
      {
        isLooping: true,
        isMuted: this.state.muted,
        volume: this.state.volume,
        rate: this.state.rate,
        shouldCorrectPitch: this.state.shouldCorrectPitch,
      },
      this._updateScreenForSoundStatus
    );
    this.sound = sound;
    this.setState({
      isLoading: false,
    });
  }
  _onRecordPressed = (question, Qkey) => {
    if (this.state.isRecording) {
      this.setState({ start : false });
      this._stopRecordingAndEnablePlayback(question, Qkey);
    } else {
      this.setState({ start : true });
      this._stopPlaybackAndBeginRecording();
    }
  };
  _onPlayPausePressed = () => {
    if (this.sound != null) {
      if (this.state.isPlaying) {
        this.sound.pauseAsync();
      } else {
        this.sound.playAsync();
      }
    }
  };
  _onStopPressed = () => {
    if (this.sound != null) {
      this.sound.stopAsync();
    }
  };
  _onMutePressed = () => {
    if (this.sound != null) {
      this.sound.setIsMutedAsync(!this.state.muted);
    }
  };
  _onVolumeSliderValueChange = value => {
    if (this.sound != null) {
      this.sound.setVolumeAsync(value);
    }
  };
  _trySetRate = async (rate, shouldCorrectPitch) => {
    if (this.sound != null) {
      try {
        await this.sound.setRateAsync(rate, shouldCorrectPitch);
      } catch (error) {
        // Rate changing could not be performed, possibly because the client's Android API is too old.
      }
    }
  };
  _onRateSliderSlidingComplete = async value => {
    this._trySetRate(value * RATE_SCALE, this.state.shouldCorrectPitch);
  };
  _onPitchCorrectionPressed = async () => {
    this._trySetRate(this.state.rate, !this.state.shouldCorrectPitch);
  };
  _onSeekSliderValueChange = () => {
    if (this.sound != null && !this.isSeeking) {
      this.isSeeking = true;
      this.shouldPlayAtEndOfSeek = this.state.shouldPlay;
      this.sound.pauseAsync();
    }
  };
  _onSeekSliderSlidingComplete = async value => {
    if (this.sound != null) {
      this.isSeeking = false;
      const seekPosition = value * this.state.soundDuration;
      if (this.shouldPlayAtEndOfSeek) {
        this.sound.playFromPositionAsync(seekPosition);
      } else {
        this.sound.setPositionAsync(seekPosition);
      }
    }
  };
  _getSeekSliderPosition() {
    if (
      this.sound != null &&
      this.state.soundPosition != null &&
      this.state.soundDuration != null
    ) {
      return this.state.soundPosition / this.state.soundDuration;
    }
    return 0;
  }
  _getMMSSFromMillis(millis) {
    const totalSeconds = millis / 1000;
    const seconds = Math.floor(totalSeconds % 60);
    const minutes = Math.floor(totalSeconds / 60);
    const padWithZero = number => {
      const string = number.toString();
      if (number < 10) {
        return '0' + string;
      }
      return string;
    };
    return padWithZero(minutes) + ':' + padWithZero(seconds);
  }
  _getPlaybackTimestamp() {
    if (
      this.state.soundPosition != null &&
      this.state.soundDuration != null
    ) {
      return `${this._getMMSSFromMillis(this.state.soundPosition)} / ${this._getMMSSFromMillis(
        this.state.soundDuration
      )}`;
    }
    return '';
  }
  async _next(nextIndex, all_question) {
    this.setState({ recordingDuration: null });
    this.setState({ disable: false });
    this.setState({ next: false });
    this.setState({ searchString: '' });
    this.setState({ soundPosition: null });
    this.setState({ soundDuration: null });
    this.setState({ isPlaying : false});

    if (this.sound !== null) {
      await this.sound.unloadAsync();
      this.sound.setOnPlaybackStatusUpdate(null);
      this.sound = null;
    }


    if (this.state.isRecording) {
      // this._stopRecordingAndEnablePlayback();
      // alert("Stop the recorder");
    }
    else {
      this.props.navigation.navigate('answer', {
        rowData: nextIndex, all_rows: all_question
      })
      ToastAndroid.show('Answer Sent Successfully !', ToastAndroid.SHORT);
    }
  }
  
  async _textSubmit (question, Qkey, nextIndex, all_question) {
    // this.setState({ next: true });
    this.setState({ recordingDuration: null });
    this.setState({ disable: false });
    this.setState({ next: false });
    this.setState({ searchString: '' });
    this.setState({ soundPosition: null });
    this.setState({ soundDuration: null });
    this.setState({ isPlaying : false});

    if(this.state.isRecording)
    {
         ToastAndroid.show('Stop Recording to Send Text Answer', ToastAndroid.SHORT);
    }

    else
    {
            if (this.sound !== null) {
              await this.sound.unloadAsync();
              this.sound.setOnPlaybackStatusUpdate(null);
              this.sound = null;
            }

            this.handleAddMessage('text', this.state.searchString, question, Qkey);
            this.setState({ searchString: '' });
            this.props.navigation.navigate('answer', {
              rowData: nextIndex, all_rows: all_question
            })

    }

  }
  _getRecordingTimestamp() {
    if (this.state.recordingDuration != null) {
      return `${this._getMMSSFromMillis(this.state.recordingDuration)}`;
    }
    return `${this._getMMSSFromMillis(0)}`;
  }
  render() {
    var rowIndex = this.props.navigation.state.params.rowData;
    var num = parseInt(rowIndex);
    var nextIndex = num + 1;
    var all_question = this.props.navigation.state.params.all_rows;
    var Qkey = Object.keys(all_question)[rowIndex]
    var all_question_array = Object.keys(all_question).map(i => all_question[i])
    length = all_question_array.length;
    if (rowIndex >= length) {
      return (
        this.props.navigation.navigate('thank')
      )
    }
    return !this.state.fontLoaded ? (
      <View style={styles.emptyContainer} />
    ) : !this.state.haveRecordingPermissions ? (
      <View style={styles.container}>
        <View />
        <Header backgroundColor='#fff'
              leftComponent={{
                icon: 'arrow-back',
                color: '#000',
                onPress: () => this.props.navigation.navigate('Question_screen'),
              }}
            />
        <Text style={[styles.noPermissionsText, { fontFamily: 'cutive-mono-regular' }]}>
          You must enable audio recording permissions in order to use this app.
        </Text>
        <View />
      </View>
    ) : (
          <View style={styles.container}>
            <Header backgroundColor='#fff'
              leftComponent={{
                icon: 'arrow-back',
                color: '#000',
                onPress: () => this.props.navigation.navigate('Question_screen'),
              }}
            />
            <ScrollView style={styles.container}>
              <View style={{
                flex: 1, flexDirection: 'row',
                justifyContent: 'center',
                alignItems: 'center',
              }}>
                <Card style={styles.card}>
                  <Text style={styles.paragraph}>
                    {parseInt(rowIndex) + 1}.{all_question_array[rowIndex].question}
                  </Text>
                </Card>
              </View>
              <View style={styles.searchSection}>
                <TextInput
                  value={this.state.searchString}
                  style={styles.input}
                  placeholder="  Answer"
                  onChangeText={(searchString) => { this.setState({ searchString }) }}
                  underlineColorAndroid="transparent"
                />
                {this.state.searchString === '' && (
                  <Icon
                    raised
                    name='create'
                    type='material'
                    color='#3bd555'
                  />
                )}
                {this.state.searchString !== '' && (
                  <Icon
                    raised
                    name='send'
                    type='material'
                    color='#3bd555'
                    onPress={() => this._textSubmit(all_question_array[rowIndex], Qkey, nextIndex, all_question)}
                  // onPress={() => this._next(nextIndex , all_question)} 
                  />)}
              </View>
              <View
                style={[
                  styles.halfScreenContainer,
                  {
                    opacity: this.state.isLoading ? DISABLED_OPACITY : 1.0,
                  },
                ]}>
                <View />
                <View style={styles.recordingContainer}>
                  <View />
                  {this.state.searchString === '' && (
                    <TouchableHighlight
                      underlayColor={BACKGROUND_COLOR}
                      onPress={() => this._onRecordPressed(all_question_array[rowIndex], Qkey)}
                      disabled={this.state.isLoading}>

                      <Image
                        style={{
                          backgroundColor: BACKGROUND_COLOR,
                          height: 80,
                          width: 80,

                        }}
                        source={this.state.start ? ICON_STOP_RECORD.module : ICON_START_RECORD.module}
                      />

                    </TouchableHighlight>
                  )}
                  {this.state.searchString !== '' && (
                    <TouchableHighlight
                      underlayColor={BACKGROUND_COLOR}
                      onPress={() => this._onRecordPressed(all_question_array[rowIndex], Qkey)}
                      disabled={true}>
                      <Image
                        style={{
                          backgroundColor: BACKGROUND_COLOR,
                          height: 80,
                          width: 80,
                          opacity: DISABLED_OPACITY,
                        }}
                        source={this.state.start ? ICON_STOP_RECORD.module : ICON_START_RECORD.module} />

                    </TouchableHighlight>
                  )}
                  <View>
                    <View />

                    <Text style={[styles.liveText, { fontFamily: 'cutive-mono-regular' }]}>
                      {this.state.isRecording ? 'LIVE' : ''}
                    </Text>
                    <View style={styles.recordingDataRowContainer}>
                      <Text style={[styles.recordingTimestamp, { fontFamily: 'cutive-mono-regular' }]}>
                        {this._getRecordingTimestamp()}
                      </Text>
                    </View>
                    <View />
                  </View>
                  <View />
                </View>
                <View />

                <Spinner
                  //visibility of Overlay Loading Spinner
                  visible={this.state.sending}
                  //Text with the Spinner 
                  textContent={'Loading...'}
                  //Text style of the Spinner Text
                  textStyle={styles.spinnerTextStyle}
                />
              </View>



              <View style={[styles.playbackContainer,
              {
                opacity: !this.state.disable ? DISABLED_OPACITY : 1.0,
              }]}>
                <Slider
                  style={styles.playbackSlider}
                  trackImage={ICON_TRACK_1.module}
                  thumbImage={ICON_THUMB_1.module}
                  value={this._getSeekSliderPosition()}
                  onValueChange={this._onSeekSliderValueChange}
                  onSlidingComplete={this._onSeekSliderSlidingComplete}
                  disabled={!this.state.disable}
                />
                <Text style={[styles.playbackTimestamp, { fontFamily: 'cutive-mono-regular' }, {
                  opacity: !this.state.disable ? DISABLED_OPACITY : 1.0,
                }]}>
                  {this._getPlaybackTimestamp()}
                </Text>
              </View>
              <View style={[styles.buttonsContainerBase, styles.buttonsContainerTopRow, {
                opacity: !this.state.disable ? DISABLED_OPACITY : 1.0,
              }]}>
                <View style={styles.volumeContainer}>
                  <TouchableHighlight
                    underlayColor={BACKGROUND_COLOR}
                    style={styles.wrapper}
                    onPress={this._onMutePressed}
                    disabled={!this.state.disable}>
                    <Image
                      style={styles.image}
                      source={this.state.muted ? ICON_MUTED_BUTTON.module : ICON_UNMUTED_BUTTON.module}
                    />
                  </TouchableHighlight>
                  <Slider
                    style={styles.volumeSlider}
                    trackImage={ICON_TRACK_1.module}
                    thumbImage={ICON_THUMB_2.module}
                    value={1}
                    onValueChange={this._onVolumeSliderValueChange} this
                    disabled={!this.state.disable}
                  />
                </View>
                <View style={styles.playStopContainer}>
                  <TouchableHighlight
                    underlayColor={BACKGROUND_COLOR}
                    style={styles.wrapper}
                    onPress={this._onPlayPausePressed}
                    disabled={!this.state.disable}>
                    <Image
                      style={styles.image}
                      source={this.state.isPlaying ? ICON_PAUSE_BUTTON.module : ICON_PLAY_BUTTON.module}
                    />
                  </TouchableHighlight>
                  <TouchableHighlight
                    underlayColor={BACKGROUND_COLOR}
                    style={styles.wrapper}
                    onPress={this._onStopPressed}
                    disabled={!this.state.disable}>
                    <Image style={styles.image} source={ICON_STOP_BUTTON.module} />
                  </TouchableHighlight>
                </View>
                <View />
                <View />
              </View>
              
              {this.state.searchString === '' && (
                <View style={[styles.recordingContainer, { fontFamily: 'cutive-mono-regular' }, {
                  opacity: !this.state.next ? DISABLED_OPACITY : 1.0,
                }]}>


                   <TouchableHighlight style={[styles.buttonContainer, styles.loginButton]}
                   disabled={!this.state.next}
                   onPress={() => this._next(nextIndex, all_question)} >
                   <Text style={styles.loginText}> NEXT </Text>
                   </TouchableHighlight>
                </View>
              )}
              {this.state.searchString !== '' && (
                <View style={[styles.recordingContainer, { fontFamily: 'cutive-mono-regular' }, {
                  opacity: DISABLED_OPACITY,
                }]}>


                    <TouchableHighlight style={[styles.buttonContainer, styles.loginButton]}
                   disabled={true} >
                   <Text style={styles.loginText}> NEXT </Text>
                   </TouchableHighlight>

                </View>
              )}

            </ScrollView>
          </View>
        );
  }
}

const styles = StyleSheet.create({
  emptyContainer: {
    alignSelf: 'stretch',
    backgroundColor: BACKGROUND_COLOR,
  },
  container: {

    flex:1,
    backgroundColor: BACKGROUND_COLOR,
    minHeight: DEVICE_HEIGHT,
    maxHeight: DEVICE_HEIGHT,
  },
  noPermissionsText: {
    textAlign: 'center',
  },
  wrapper: {},
  halfScreenContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    minHeight: DEVICE_HEIGHT / 3.5,
    maxHeight: DEVICE_HEIGHT / 3.5,
  },
  recordingContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
   
  },
  recordingDataContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  
  },
  recordingDataRowContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: ICON_RECORDING.height,
    maxHeight: ICON_RECORDING.height,
  },
  playbackContainer: {
    flex: 1,
    alignItems: 'center',
    alignSelf: 'stretch',
    minHeight: ICON_THUMB_1.height * 2.0,
    maxHeight: ICON_THUMB_1.height * 2.0,
  },
  playbackSlider: {
    alignSelf: 'stretch',
  },
  liveText: {
    color: LIVE_COLOR,
  },
  recordingTimestamp: {
    paddingLeft: 20,
  },
  playbackTimestamp: {
    textAlign: 'right',
    alignSelf: 'stretch',
    paddingRight: 20,
  },
  image: {
    backgroundColor: BACKGROUND_COLOR,
  },
  textButton: {
    backgroundColor: BACKGROUND_COLOR,
    padding: 10,
  },
  buttonsContainerBase: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  buttonsContainerTopRow: {
    maxHeight: ICON_MUTED_BUTTON.height,
    alignSelf: 'stretch',
    paddingRight: 20,
  },
  playStopContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minWidth: (ICON_PLAY_BUTTON.width + ICON_STOP_BUTTON.width) * 3.0 / 2.0,
    maxWidth: (ICON_PLAY_BUTTON.width + ICON_STOP_BUTTON.width) * 3.0 / 2.0,
  },
  volumeContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minWidth: DEVICE_WIDTH / 2.0,
    maxWidth: DEVICE_WIDTH / 2.0,
  },
  volumeSlider: {
    width: DEVICE_WIDTH / 2.0 - ICON_MUTED_BUTTON.width,
  },
  buttonsContainerBottomRow: {
    maxHeight: ICON_THUMB_1.height,
    alignSelf: 'stretch',
    paddingRight: 20,
    paddingLeft: 20,
  },
  rateSlider: {
    width: DEVICE_WIDTH / 2.0,
  },
  text: {
    fontSize: 20,
  },
  button: {


    borderRadius: 25,

  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
    color: '#34495e',
  },
  card: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: BACKGROUND_COLOR,
    minHeight: DEVICE_HEIGHT,
    maxHeight: DEVICE_HEIGHT,
    width: (Dimensions.get("window").width) - 20,
    borderRadius: 2,
  },
  searchSection: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  searchIcon: {
    padding: 10,
  },
  input: {
    flex: 1,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 0,
    backgroundColor: '#fff',
    color: '#424242',
    borderRadius: 2,
    borderWidth: 2,
    borderColor: '#cdcdcd',
    marginLeft: 15,

  },
  button: {
    width: (Dimensions.get("window").width / 2) - 30,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 32,
    alignSelf: 'center'
  },
  spinnerTextStyle: {
    color: '#000',
  },
   buttonContainer: {
    height:45,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom:20,
    marginRight: 5,
    width:250,
    borderRadius:30,
    alignSelf: 'center'
  },
  loginButton: {
    backgroundColor: "#3bd555",
  },
  loginText: {
    color: 'white',
    fontSize:20
  }
});

**Comment by mayu-496** [comment]
Hello Sir @cruzach .. the snack link which you have send for audio recorder is working fine when tested , and it is the same code I'm using with some modifications .. Can you help me to find out why it is not working for me..
