### ISSUE TITLE
Notifications.setBadgeNumberAsync now throws on Android instead of noop?

### ISSUE THREAD

**Issue by slorber** [expo/expo#6349]
## 🐛 Bug Report

Just upgraded SDK 28 to SDK 35, and now I have this error on Android Expo client

```
Error: The method or property Expo.Notifications.setBadgeNumberAsync is not available on android, are you sure you've linked all the native dependencies properly?
```

It was not the case before, and the doc still says that calling this method on Android is supposed to noop: https://docs.expo.io/versions/latest/sdk/notifications/#notificationssetbadgenumberasyncnumber

I think there are 2 choices:
- Say in the doc the method rejects on Android
- Put back the failsafe / no-op behavior on Android

**Comment by slorber** [comment]
cc @Szymon20000 @mczernek could be related to https://github.com/expo/expo/pull/5060 ?

**Comment by cruzach** [comment]
Looks like the change was made in [this commit](https://github.com/expo/expo/commit/0a57b3080146e7c7caf2f4577cd83f055d7eb1c3#diff-f7e0d39ba2efd443e08d4400d2c6d127)

I think it might be useful to log a warning calling this on android (like we do for deleteChannelAndroidAsync), but not throw.

**Comment by mikeRChambers610** [comment]
So what are we supposed to do if we need to clear the badge on Android??

**Comment by cruzach** [comment]
@mikeRChambers610 this is a really old issue, and we've since built a new notifications library- https://docs.expo.io/versions/latest/sdk/notifications/
