### ISSUE TITLE
Location reverseGeocodeAsync returns incorrectly

### ISSUE THREAD

**Issue by sim-stamplet** [expo/expo#635]
reverseGeocodeAsync doesn't return the correct location in text and always return only one result for all coordinates tested
Array [
Object {
"name": "North Atlantic Ocean",
},
]
expected Result is more detailed with street, city and other details :
https://github.com/expo/expo-docs/blob/master/versions/v19.0.0/sdk/location.md

**Comment by Raveler** [comment]
This happens when you give it invalid coords. Make sure that, if the coordinates come from Location.getCurrentPositionAsync, that you pass on .coords, like this:

let location = await Location.getCurrentPositionAsync();
let geocode = await Location.reverseGeocodeAsync(location.coords);

**Comment by dikaiosune** [comment]
@sim-stamplet can you provide more detail about what coordinates you're passing that are failing? Ideally you could provide us with a [snack](https://snack.expo.io) to reproduce. Giving this a close for now, but we'll happily reopen and look into this if we can repro.
