### ISSUE TITLE
[test-suite] tests chosen in test-suite should be persistent across app reloads

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#6356]
Right now, when we choose some modules to test in `test-suite` app and then modify something in the code that causes app to reload, we have to choose these tests again. It becomes pretty annoying in development as in most cases we do want to choose the same tests.

We can remember which tests have been chosen and restore them when the app reloads. (This probably shouldn't apply to detox tests).

**Comment by lukmccall** [comment]
Fast refresh from RN solved this problem 😄

**Comment by lukmccall** [comment]
Nevermind... We need to add code which will rerun the test when component reloads.
