### ISSUE TITLE
Expo facebook login has error

### ISSUE THREAD

**Issue by toeurtenh** [expo/expo#6359]
I have tried to test login by using expo facebook

**App.js**

import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import * as Facebook from 'expo-facebook';

export default class App extends React.Component {
  async logIn() {
    try {
      const {
        type,
        token,
        expires,
        permissions,
        declinedPermissions,
      } = await Facebook.logInWithReadPermissionsAsync('<my_app_id>', {
        permissions: ['public_profile'],
      });
      if (type === 'success') {
        // Get the user's name using Facebook's Graph API
        const response = await fetch(`https://graph.facebook.com/me?access_token=${token}`);
        Alert.alert('Logged in!', `Hi ${(await response.json()).name}!`);
      } else {
        // type === 'cancel'
      }
    } catch ({ message }) {
      alert(`Facebook Login Error: ${message}`);
    }
  }
  render(){
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Button
            onPress={this.logIn}
            title="Press Me"
          />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**app.json**

{
  "expo": {
    "name": "LogInTest",
    "slug": "LogInTest",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "facebookScheme":"my_facebookScheme",
    "facebookAppId": "my_facebookAppId",
    "facebookDisplayName": "TestLogIn",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}

After I clicked a button I got Facebook Login Error: Error with Facebook login, what is the issue?
and ideas?

**Comment by cruzach** [comment]
Hi! It helps a lot if you fill out the entire bug report template, so we have all the information we need to help you

Is this only happening in a standalone app? Have you made sure to follow all of the instructions [in the docs](https://docs.expo.io/versions/latest/sdk/facebook/)? What SDK version and `expo-facebook` version are you using?

**Comment by toeurtenh** [comment]
@cruzach thank you. I will check bug report template next time. 

Yes it is a react native standalone app which I created by using expo.

in app.json

"sdkVersion": "35.0.0"

in package.json

"expo-facebook": "~7.0.0"

**Comment by shawnpetros** [comment]
Hmmm, I have this issue as well, not sure if FB changed something in the last year or so, because the FB auth that I had set up late last year that worked no longer does. Additionally I am seeing this: https://stackoverflow.com/questions/33822789/facebook-oauth2-sorry-something-went-wrong which seems to indicate that if the webview is calling `m.facebook.com` for an OAuth exchange, FB may be blocking it. I am also  experiencing the above problem with a fresh sdkVersion and followed the instructions in the doc exactly.

My button brings up a webview, but that webview instantly shows "Sorry, something went wrong." I will try to initiate FB auth outside of expo-facebook and see if I get any further.

**Comment by alxmrtnz** [comment]
@shawnpetros Any luck with a fix? I'm experiencing what appears to be the same issue in the Expo client run on Simulator:

![image](https://user-images.githubusercontent.com/1167326/72473451-b6477a00-37b4-11ea-951b-930b25827267.png)

**Comment by shawnpetros** [comment]
@alxmrtnz, I can’t honestly tell you what I did to make it work, but it’s behaving now for me. I abandoned the feature for a few days while working on other things and decided I would try it again and just implemented it all over again (following the same tut on expo’s page) and viola...it just worked...

Maybe I had a misconfiguration on the Facebook app side, maybe I misspelled a function call. No clue, I’m also just using Expo to initiate the handshake, I’m taking the cred and user details from the FB graph api call and posting them to Firebase for the auth. It could be that I ended up with a configuration for Firebase and when expo was requesting the token it failed.

**Comment by alxmrtnz** [comment]
Thanks for the response @shawnpetros! 

I got it working on my project this afternoon finally. _I'm not sure if this will be a fix for everyone_, but after correcting permissions, we stopped getting the "Sorry, something went wrong" error.

Turns out we were asking for permissions that don't exist (`first_name`, `last_name`):

**Our previously incorrect code:**
```
await Facebook.logInWithReadPermissionsAsync({
    permissions: ['public_profile', 'email', 'first_name', 'last_name']
});
```

**Switching it to this fixed the issue:**
```
const fbResponse = await Facebook.logInWithReadPermissionsAsync({
  permissions: ['public_profile', 'email']
});
```

and then we accessed the user profile data we wanted by using the fetch:
```
const response = await fetch(`https://graph.facebook.com/me?fields=email,name,id,first_name,last_name&access_token=${token}`);
const user = await response.json();

const {
  email,
  first_name,
  last_name
} = user;
```

**Comment by shawnpetros** [comment]
Glad you got it working @alxmrtnz, I also had to mess around with the permissions and correcting the call to the graph api, in case you're wondering and want to get a user's profile pic, you need to add `picture.type(large)` to the graph call to get the URL for it, when you just ask for `picture` you end up getting the 50x50 version which looks horrible at almost all resolutions.
