### ISSUE TITLE
reverseGeocodeAsync does never return on Android IF you haven't given permissions in a previous session

### ISSUE THREAD

**Issue by Raveler** [expo/expo#636]
If you boot an app that does a reverseGeocodeAsync and you have not requested permission for Permissions.LOCATION in a previous session of the app, the app will

 hang indefinitely when calling reverseGeocodeAsync. If you shut down the app and reboot it, it will work perfectly fine.

This problem does not occur with other Location calls such as getCurrentPositionAsync.

You can't revoke permissions on iOS so I can't test if the problem occurs there as well.

You can try for yourself with this app:
https://exp.host/@aerynus/reversegeocodeasync-bug

make sure to revoke all permissions on the Expo app in Android settings before trying this out!

```
import { Button, StyleSheet, Text, View } from 'react-native';
import { Location, Permissions } from 'expo';
import React from 'react';

export default class App extends React.Component {

	constructor(props) {
		super(props);

		this.state = {
			status: 'Press button...',
		};
	}

  render() {
    return (
      <View style={styles.container}>
	  	<Button title="Request Location" onPress={() => this.requestLocation()} />
		<Text>{this.state.status}</Text>
      </View>
    );
  }

  async requestLocation() {
	  this.setState({
		  status: 'Requesting geocode...',
	  });

	console.log("Ask for location permission...");
	let { status } = await Permissions.askAsync(Permissions.LOCATION);
	console.log("Got back: " + status);

	if (status !== 'granted') {
		console.log("Failed to get geolocation: access not granted, status " + status);
		this.setState({
			status: status,
		});
		return;
	}

	try {
		console.log("Request geocode...");
		let geocode = await Location.reverseGeocodeAsync({latitude: 51.177977, longitude: 4.365066});
		console.log("Geocode:");
		console.log(geocode);

		console.log("DONE");
		this.setState({
			status: 'DONE, we are in ' + geocode[0].city,
		});

	}
	catch (error) {
		console.log("Failed to get geolocation:");
		this.setState({
			status: error,
		});
		console.log(error);
	}
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by quinlanj** [comment]
@jesseruder is it possible that isMissingPermissions in LocationsModule is not correct? If user has Version >23, and only one of the required permissions, isMissingPermissions will return false, and reverseGeocodeAsync could error without updating the promise somewhere later on in the method.

https://github.com/expo/universe/blob/master/exponent/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/LocationModule.java#L101

**Comment by edgareler** [comment]
@Raveler I confirm that this exact issue is also happening to me.

**Comment by edgareler** [comment]
In order to workaround this, I had to reload the app if is the first session of the user:

```
Util.reload();
```

As this is a terrible approach, @jesseruder let me know if I can help you in some way to have this fixed quickly.

Thanks

**Comment by Ruzo** [comment]
With permission from previous sessions, reverseGeocodeAsync works fine until Expo.WebBrowser.openBrowserAsync(url) is used to open a browser window. From that point on, calls to reverseGeocodeAsync never returns.

**Comment by rxb** [comment]
Good to know I'm not crazy. Quitting Expo and restarting the app with permission works.

**Comment by ceefour** [comment]
Still happening on Expo 23 :(

**Comment by dailycommit** [comment]
I'm having the same problem with Expo v21 😱

**Comment by aalices** [comment]
Hello all, sorry it took so long - the issue will be fixed soon! There was a problem that geocoding would not start right after granting permissions so a quick workaround before we merge the fix would be setting a little timeout for geocoding after getting `granted` status.

**Comment by dooboolab** [comment]
@aalices 
Thanks we are really waiting for this!

**Comment by edgareler** [comment]
@aalices was this fixed in what release? I need to remove my workaround of restarting the app after user gives Location permission.

**Comment by aalices** [comment]
@edgareler yes, it should be released next week

**Comment by edgareler** [comment]
Thanks @aalices

**Comment by mgnstudio7** [comment]
on SDK 32 and IOS 12.1 error repeated. I had to set a timeout
