### ISSUE TITLE
[appauth][android] Allow passing mCodeVerifier prop to disable PKCE exchange 

### ISSUE THREAD

**Issue by Lerosen** [expo/expo#6360]
### Environment

Expo CLI 3.8.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD

Target: Android, Client, Standalone

### Steps to Reproduce

Some OAuth providers - for example dropbox - do not support the codeVerifier Challenge (PKCE exchange, https://www.oauth.com/oauth2-servers/pkce/). The native AppAuth Library for Android allows to pass null to mCodeVerifier* props to disable the exchange. If I try to set these props as additionalParameters in the AuthConfig it seems like they are ignored.

1. Configure the AppAuth Module to authenticate against the dropbox api
2. Start the authentication - Dropbox responds with an error page, stating that the field "mCodeVerifierChallengeMethod" is unknown.

### Expected Behavior

I expect the parameters to be set accordingly on the native module so that dropox accepts the request by presenting the log in page. As by calling https://www.dropbox.com/oauth2/authorize?client_id=p8mjlr0xvq3s3w5&response_type=code

### Actual Behavior

Dropbox responds with an error page, stating that the field "mCodeVerifierChallengeMethod" is unknown.

### Reproducible Demo

https://snack.expo.io/@lerosen/appauth-android-bug

**Comment by EvanBacon** [comment]
We will be supporting this feature in the new `expo-auth-session` API.
