### ISSUE TITLE
error 1101

### ISSUE THREAD

**Issue by YunisDEV** [expo/expo#6363]
Hello. I am a starter for react-native.And I am getting this when i want to publish my app to expo:
"
React Native version not supported by Expo. Major versions supported: 0.27.0, 0.31.0, 0.33.0, 0.36.0, 0.37.0, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.1, 0.47.1, 0.48.4, 0.49.3, 0.50.3, 0.51.0, 0.52.0, 0.54.2, 0.55.2, 0.55.4, 0.57.1, 0.59.8, 0.59.10 (error code 1101)
"

**Comment by cruzach** [comment]
Looks like you have an incompatible version of react native pinned in your package.json file. It should be something like 
```
"react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
```
but replace the 35 with your SDK version (should be 33,34,or 35)
