### ISSUE TITLE
Constantly getting ERROR_CODE_INTERNAL_ERROR with AdMob on specific device even though on other devices and emulators it runs fine

### ISSUE THREAD

**Issue by alexnm2566** [expo/expo#6364]
I have Lenovo K3 Note with custom Android 7.1.2 

When running on it the request from AdMob returns with ERROR_CODE_INTERNAL_ERROR
But with other devices and emulators the request is working properly and then it loads Rewarded Ad.

I just don't understand what can it be that on some specific devices it works but not on others?

**Comment by alexnm2566** [comment]
I think this has to do with the custom ROM built-in Ad blocker(though I'm not sure if it's there at all) because some video ads even on other games fail to load. I got this idea when I tried to install AdMob for Android and it just couldn't connect to the Internet

**Comment by cruzach** [comment]
Yeah I think if there's a built-in ad blocker, and multiple other ads from different sources aren't working, then this is most likely not a bug with the Expo SDK. If you still believe it is, could you fill out the full issue template?

**Comment by alexnm2566** [comment]
Yeah I suspect this is definitely some AdBlocker inside my ROM. Thanks anyway!

**Comment by walesonn** [comment]
Fala galera realmente é um bloqueador de anúncios. O erro estava acontecendo comigo pois eu estava usando um bloqueador de anuncios no dns do meu dispositivo, após ler o que nosso amigo disse logo acima me lembrei deste detalhe assim que desativei funcionou. Obrigado.
