### ISSUE TITLE
Error from Metro Bundler after upgrading from Expo 34 to Expo 35 #6365

### ISSUE THREAD

**Issue by emersonhsieh** [expo/expo#6366]
## 🐛 Bug Report

I get an error from the Metro Bundler after upgrading my Expo app from Expo 34.0.3 to Expo 35.0.0 using `expo upgrade`.  I don't know how to debug this because I don't know what the variable names stand for.

### Environment

My app is an Expo app (not ejected). I ran the app on the Expo client on iOS and Android, and got the same issue for both.

`expo diagnostics`:

    Expo CLI 3.9.0 environment info:
        System:
        OS: macOS 10.14.6
        Shell: 3.2.57 - /bin/bash
        Binaries:
        Node: 10.16.0 - /usr/local/bin/node
        npm: 6.13.1 - /usr/local/bin/npm
        Watchman: 4.9.0 - /usr/local/bin/watchman
        IDEs:
        Android Studio: 3.4 AI-183.6156.11.34.5522156
        Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
        npmGlobalPackages:
        expo-cli: 3.9.0

### Steps to Reproduce

My app is originally based on Expo 34. I ran `expo upgrade`, deleted `node_modules` and `package-lock.json`, and ran `npm install`.

### Expected Behavior

I expected the project to run fine after upgrading.

### Actual Behavior

I get the following error when running my app on the Expo client on iOS and Android:

`undefined is not an object (evaluating 'n(r(d[32])).default.config)'`

<img src="https://i.imgur.com/0WCdBBm.png"/>

### Reproducible Demo

`package.json`:

    {
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
        "start": "expo start",
        "android": "expo start --android",
        "ios": "expo start --ios",
        "web": "expo start --web",
        "eject": "expo eject",
        "flow": "flow"
    },
    "dependencies": {
        "@benawad/expo-mixpanel-analytics": "^0.1.7",
        "@expo/vector-icons": "^10.0.3",
        "axios": "^0.19.0",
        "babel-plugin-transform-remove-console": "^6.9.4",
        "blob-to-stream": "^1.0.3",
        "expo": "^34.0.3",
        "expo-constants": "~6.0.0",
        "expo-font": "^6.0.1",
        "expo-image-manipulator": "~6.0.0",
        "expo-image-picker": "~6.0.0",
        "expo-linear-gradient": "~6.0.0",
        "expo-location": "~6.0.0",
        "expo-permissions": "~6.0.0",
        "expo-web-browser": "~6.0.0",
        "firebase": "^6.3.3",
        "formik": "^1.5.8",
        "geofirestore": "^3.3.1",
        "lodash": "^4.17.15",
        "moment": "^2.24.0",
        "moment-timezone": "^0.5.26",
        "node-fetch": "^2.6.0",
        "prop-types": "^15.7.2",
        "react": "16.8.3",
        "react-dom": "^16.8.6",
        "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
        "react-native-countdown-component": "^2.6.0",
        "react-native-elements": "^1.2.5",
        "react-native-gesture-handler": "~1.3.0",
        "react-native-gifted-chat": "^0.9.11",
        "react-native-keyboard-aware-scroll-view": "^0.9.1",
        "react-native-keyboard-spacer": "^0.4.1",
        "react-native-modal-datetime-picker": "^7.6.0",
        "react-native-paper": "^2.16.0",
        "react-native-picker-select": "^6.3.2",
        "react-native-progress": "^3.6.0",
        "react-native-reanimated": "~1.1.0",
        "react-native-svg": "^9.4.0",
        "react-native-vector-icons": "^6.6.0",
        "react-native-web": "^0.11.4",
        "react-native-webview": "^5.8.1",
        "react-navigation": "^3.11.1",
        "react-redux": "^7.1.1",
        "redux": "^4.0.4",
        "redux-thunk": "^2.3.0",
        "sentry-expo": "~1.13.0",
        "tz-lookup": "^6.1.24",
        "util": "^0.12.1",
        "yup": "^0.27.0"
    },
    "devDependencies": {
        "@babel/cli": "^7.5.5",
        "@babel/core": "^7.5.5",
        "@babel/preset-flow": "^7.0.0",
        "babel-eslint": "^7.2.3",
        "babel-preset-expo": "^5.1.1",
        "eslint": "^6.7.0",
        "eslint-config-airbnb": "^18.0.1",
        "eslint-config-exponent": "^5.1.3",
        "eslint-plugin-babel": "^4.1.2",
        "eslint-plugin-flowtype": "^2.50.3",
        "eslint-plugin-import": "^2.18.2",
        "eslint-plugin-jsx-a11y": "^6.2.3",
        "eslint-plugin-react": "^7.16.0",
        "eslint-plugin-react-hooks": "^1.7.0",
        "flow-bin": "^0.105.1"
    },
    "private": true
    }

**Comment by pedro-lb** [comment]
Try running `expo start --clear`, to reset expo cache.

**Comment by emersonhsieh** [comment]
@pedro-lb I have tried that multiple times, but I'm still getting that error.

**Comment by cruzach** [comment]
Hi! Sorry you're having trouble after upgrading, my guess is that there was a breaking change in one of the libraries that was upgraded. I suggest reading the [release notes](https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4) and looking at the [changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md) to see if there are any breaking changes that apply to your project. 

Other than that, narrowing down the root cause of this would help a lot. You have quite a few dependencies so finding out where this error is being thrown, and putting together a minimal repro would be ideal 🙂

**Comment by emersonhsieh** [comment]
I've found the issue! It turns out that the issue is unrelated to the packages. I updated my import statement for Sentry and changed `Sentry.setUserContext` to `Sentry.setContext`, and everything works now. Thanks for the help!
