### ISSUE TITLE
Can't explicitly import react-native-web in a Snack

### ISSUE THREAD

**Issue by mark-friedman** [expo/expo#6384]
It doesn’t appear that I can import from react-native-web in a Snack.  Is that expected behavior?  I was a bit surprised, given that there is the Web tab in Snack for previewing, which presumably is using react-native-web.

As context, I was trying to import `unstable_createElement`, described in http://necolas.github.io/react-native-web/docs/?path=/docs/guides-unstable-uses--page in order to try and wrap a React component for use in react-native-web.

cc @brentvatne

**Comment by brentvatne** [comment]
@tcdavis - this would be nice to have

**Comment by wood1986** [comment]
Can you do the same fix? See https://github.com/react-native-community/react-native-svg/pull/1240/files
