### ISSUE TITLE
expo-google-app-auth loginAsync requires `clientId`

### ISSUE THREAD

**Issue by nolanholden** [expo/expo#6393]
https://docs.expo.io/versions/latest/sdk/google/#loginasync
mentions nothing about default parameter `clientId`, but typescript definition requires it here:
https://github.com/expo/expo/blob/0742e36a96e8fa301fd500fd7f1cfbcc4b48df06/packages/expo-google-app-auth/src/Google.ts#L26-L28

This is required for [`loginAsync`](https://github.com/expo/expo/blob/0742e36a96e8fa301fd500fd7f1cfbcc4b48df06/packages/expo-google-app-auth/src/Google.ts#L128) which passes it to [`getPlatformGUID`](https://github.com/expo/expo/blob/0742e36a96e8fa301fd500fd7f1cfbcc4b48df06/packages/expo-google-app-auth/src/Google.ts#L51).

Should this instead be type `string?`, or included in docs?

**Comment by nonameolsson** [comment]
I have the same problem. I'm using:
```
"expo": "36.0.0",
"expo-google-app-auth": "8.0.0",
```

Is this fix released yet?

**Comment by cruzach** [comment]
published in `expo-google-app-auth 8.0.1`
