### ISSUE TITLE
[docs] Guide for Universal Links

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#6395]
https://forums.expo.io/t/associated-domain-is-always-wildcard/30279/9

**Comment by cruzach** [comment]
Think we already have a guide for this-> https://docs.expo.io/versions/latest/workflow/linking/#universaldeep-links-without-a-custom-scheme 

But maybe they're out of date? I haven't tested the ios side of these docs but the android ones are accurate (at least as of a month ago ish)

**Comment by cruzach** [comment]
Followed the guide above and universal links work as expected
