### ISSUE TITLE
Contacts - firstName, lastName, addresses and image not working

### ISSUE THREAD

**Issue by abdelilah** [expo/expo#6401]
### Environment

  Expo CLI 3.9.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832

App targets: iOS, Android

### Steps to Reproduce

Using **Contacts.presentFormAsync** to present the native "Create contact" view filled with firstName, lastName...etc.

```javascript
Contacts.presentFormAsync(null, {
  [Contacts.Fields.FirstName]: "John", // not working
  [Contacts.Fields.LastName]: "Doe", // not working
  [Contacts.Fields.Company]: 'Doe inc' // works
})
```

### Expected Behavior

firstName, lastName, addresses, image pre-filled in the presented view.

### Actual Behavior

Only certain fields are populated (e.g.: company, jobTitle)

**Comment by cruzach** [comment]
Is this on SDK 35? Following the entire bug report template is very helpful

**Comment by abdelilah** [comment]
Yes, it's on SDK 35.

Sorry for the the unconventional report, I updated it to conform with the template.

**Comment by cruzach** [comment]
Just tested this on this snack https://snack.expo.io/@charliecruzan/presentcontactform and it's working, can you provide more details as to how to reproduce this bug? What OS?

**Comment by abdelilah** [comment]
I encoutered the bug on Android, both the emulator and real device present the same issue (see image below).

- Android emulator on **Android 10**
- Samsung Galaxy S10 on **Android 9**

![contacts-bug](https://user-images.githubusercontent.com/465667/70124189-7b5e0c80-1674-11ea-9158-554beae1892a.gif)

**Comment by cruzach** [comment]
Ah okay, your original post has `App targets: iOS, Android`, I'll check android

**Comment by abdelilah** [comment]
I already fixed firstName, lastName and addresses, only image is remaining.  Can I submit a PR ?

**Comment by cruzach** [comment]
sure! High-quality PRs are always welcome 😄  we have a few guides on contributing [here](https://github.com/expo/expo/tree/master/guides#expo-engineering-guides)

**Comment by abdelilah** [comment]
Done: [https://github.com/expo/expo/pull/6444](https://github.com/expo/expo/pull/6444)

However, I see that in the latest sdk-36 some files were changed and the issue is probably still there.
