### ISSUE TITLE
Veracode Static Analysis Indicates Issues from DBFlow (potentially false positive)

### ISSUE THREAD

**Issue by andrelramos** [expo/expo#6402]
## 🐛 Bug Report

Hello, I am developing an expo app, which is on my employer's expo pro account, this app was developed using expo sdk 33.0.0, and I built an android binary(apk) for a client to do some security testing in this apk, using VERACODE (https://www.veracode.com/) software. To do this, I eject my project and choose to use Expokit, and the result was that we are getting a security issue with SQL Injection, as you can see below:

![image](https://user-images.githubusercontent.com/10236206/69998034-392db180-1534-11ea-9f23-fbbde24dac8f.png)

So I researched this issue and found that this FlowSQLiteOpenHelper.java file is from DBFlow, I read from Expo documents that in Expo sdk 35.0.0, dbflow has been removed from the app/build.gradle, as you can see below:
 
![image](https://user-images.githubusercontent.com/10236206/69997936-0a174000-1534-11ea-9ef8-d4ee5d0dd575.png)

So I performed expo upgrade and checked the instructions (https://docs.expo.io/versions/latest/expokit/expokit/#android-1) to verify it was all right. Then I ejected my project again, and chose to use Expokit, to generate a new binary android (apk), to repeat the security test in VERACODE, and the result was that we are still getting a security issue with SQL Injection, and now we have another issue, Untrusted Initialization, as you can see below:

![image](https://user-images.githubusercontent.com/10236206/69997904-f4a21600-1533-11ea-898d-77ff44e581c1.png)

![image](https://user-images.githubusercontent.com/10236206/69998095-5cf0f780-1534-11ea-91d2-889d5d90ce00.png)

![image](https://user-images.githubusercontent.com/10236206/69998134-6ed29a80-1534-11ea-80ab-352d3644c8f6.png)

![image](https://user-images.githubusercontent.com/10236206/69998146-75f9a880-1534-11ea-9cd7-8fc63b44c7f2.png)

My app is in production and I need to fix this issue, can you help me how can I do this?
 
More Info:
- I am ejecting my project and using expokit.
- expo-cli: 3.8.0
- Expo sdk: 35.0.0

### Environment

  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.8.0

App’s target: Android and iOS

### Steps to Reproduce

To reproduce it’s necessary follow the below steps to create the build required for run the veracode scan:

1 - Eject expo from app (expo 35.0.0)

2 - Follow the veracode build instructions (https://help.veracode.com/reader/4EKhlLSMHm5jC8P8j3XccQ/FO_I~d5tIL7O0b5Xxue4kQ)

3 - Run expo publish

4 - Generate android apk using Android Studio

5 - Scan apk with veracode

### Expected Behavior

Veracode report can’t show high security issues

### Actual Behavior

Expo has 2 high security issues

### Reproducible Demo

https://github.com/joaogabrielsg/emptyProject

**Comment by ide** [comment]
This GitHub issue looks like a report that this tool (Veracode) reports some code that could be potentially vulnerable, which look like false positives. For instance, DBFlow is an internal implementation detail. It is still used in SDK 35. Is there a concrete scenario in which Veracode's report points to actual issues?

**Comment by rittersport3** [comment]
Hi Ide, 

Well, even if it isn't an "actual issue", being flagged as "High Security Risk" is already an issue for adoption. For some corporate procedures, not passing veracode static analysis is non-starter :cry: .

How would you go about it?

Cheers!

**Comment by AdamJNavarro** [comment]
Hey @andrelramos and @rittersport3,

As James mentioned, it looks like these could be false positives and unfortunately with us being a small team we don't have the bandwidth to make this a priority and address it in the near term. We definitely want to get around to ensure that Expo isn't prevented from being used due to corporate procedures.

We're really sorry if this puts you in a hard place internally and results in you not being able to use Expo moving forward. If you are able to whitelist Expo and move forward, that would be great but we understand if that's not possible. Please let us know what the next steps for you are by reaching out via [email](secure@expo.io).

Cheers,
Adam
