### ISSUE TITLE
getFreeDiskStorageAsync reports wrong numbers on Android

### ISSUE THREAD

**Issue by FabianOMB** [expo/expo#6409]
## 🐛 Bug Report
The method getFreeDiskStorageAsync on the FileSystem object from "expo-file-system" should return the number of free bytes. It works fine on iOS but on Android it returns a very high number like 9007199254740991.

### Environment
  Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.18.3 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.9.1

Target: 
       Android 9
       Device: Nokia 7 plus

### Steps to Reproduce
Run the following code on an android device:

```
FileSystem.getFreeDiskStorageAsync().then(freeDiskStorage => {
        let spaceInMb = Math.round(freeDiskStorage/1024/1024);
        console.log(spaceInMb);
});
```

### Expected Behavior
It should return the number of free bytes on the device

### Actual Behavior
Returns a very high number that seems unrelated to the free space

### Reproducible Demo

https://snack.expo.io/@evidensa/freediskspacebug

**Comment by simonlewisjones** [comment]
Same issue here, testing on a Pixel 4. Getting exactly the same number back too (9007199254740991).
