### ISSUE TITLE
expo-server-sdk-go

### ISSUE THREAD

**Issue by adierkens** [expo/expo#641]
One of the project's I'm working on has a back-end written in Go, which didn't have an `expo-server-sdk` implementation, so I wrote one: https://github.com/adierkens/expo-server-sdk-go

It follows the same basic API as the `python` and `js` implementations.

Any feedback on how it's implemented? I'd love to see it get pushed upsteam under the `expo` org

**Comment by adierkens** [comment]
@skevy What's the process for opening up a project under the `expo` org?

**Comment by sjchmiela** [comment]
Hey, @adierkens! Good job on your library! 🎉 I don't think we have the bandwidth to take ownership of this library, but if you're still interested, you could submit a pull request to [`expo/expo-docs`](https://github.com/expo/expo-docs) adding your library to the official Expo documentation somewhere around [here](https://github.com/expo/expo-docs/blob/7ba89d9ac09569eb1ceec0f523bc66e0c56123ea/versions/unversioned/guides/push-notifications.md#2-call-expos-push-api-with-the-users-token). Thank you for your work! 😊
