### ISSUE TITLE
Running iOS archive of detached app - "No version of ___ compatible with this version of Exponent"

### ISSUE THREAD

**Issue by asgeo1** [expo/expo#642]
I have an Expo app, which I have detached.  _(because it doesn't support react-native link, and I want to integrate react plugins like `react-native-intercom`)_

The app runs OK on my device via XCode, i.e. in development mode.

When I create an iOS archive, it does run however, but I get this error:

![2017-09-15 11 05 49](https://user-images.githubusercontent.com/702212/30462089-a09dc176-9a06-11e7-987a-70da65d8b5c2.png)
 
I don't get what it's referring to.

I mean, yes, at some point I updated the app to use Expo SDK v20.  Maybe it's something to do with that?

But the app runs fine in development mode, so I don't see what the issue is.

**Comment by terribleben** [comment]
The archived (production) version of the native code will look for a published copy of your app (e.g. at expo.io/@yourname/yourapp). Can you try running `exp publish`?

**Comment by asgeo1** [comment]
Yup, that worked!  Awesome, thanks.

I didn't realise I had to run that command.  I've been a bit confused about which `exp` commands are relevant to detached apps actually.

I'm still getting my head around how it all works. Cheers
