### ISSUE TITLE
startGeofencingAsync not triggering

### ISSUE THREAD

**Issue by rosnaib11** [expo/expo#6423]
When I run startGeofencingAsync it doesn't start right away. My current region is already inside my current location, this mean I'm already inside the zone when I press start. So I guess I have to set it outside the radius to make it work, but I need to detect it right away when I press the button. I have to turn off my Wifi and turn it back again to get the notification You've enter region:. How to achieve this? It something like I have to trigger that task GEOFENCE_ENGINE when I press start

**Task**

```
TaskManager.defineTask(
  "GEOFENCE_ENGINE",
  ({ data: { eventType, region }, error }) => {
    alert("testing");
    if (error) {
      alert(error);
      // check `error.message` for more details.
      return;
    }

    if (eventType === Location.GeofencingEventType.Enter) {
      const id = region.identifier;
      if (id === "origin") {
        //
      }

      console.log("Enter");
      console.log(region);
      alert(`You've entered region:${region}`);
    } else if (eventType === Location.GeofencingEventType.Exit) {
      alert(`You've left region:${region}`);
      console.log("Exit");
      console.log(region);
    }
  }
);
```

**Button function**

```
  _startGeofence = async () => {
    if (!this.state.deliveryid) {
      alert("Something went wrong, no deliveryid detected.");
    } else {
      const data_origin = [
        {
          identifier: "origin",
          latitude: this.state.pickupLat,
          longitude: this.state.pickupLong,
          radius: this.state.origin_radius
        }
      ];


      const start_origin = await Location.startGeofencingAsync(
        "GEOFENCE_ENGINE",
        data_origin
      );

      await AsyncStorage.setItem(
        "geofence_del_id",
        `"${this.state.deliveryid}"`
      );
    }
  };
```

**Comment by cruzach** [comment]
You could work around this by getting the user's instantaneous Location with `getCurrentPositionAsync`, at the same time that you start geofencing, and checking which region it is in. I'm not sure if an event should be sent when geofencing is started that a device is in a particular region, since geofencing is meant to notify when a device enters or leaves a certain region, but @tsapeta would be a better judge

**Comment by rosnaib11** [comment]
Its weird, because sometimes it works sometimes its not. It happens only on our wifi connection. If I turned off wifi or change to cellular data it works fine. I tried clearing cache of my phone and changing wifi connection.

**Comment by cruzach** [comment]
@rosnaib11 I think the easiest way to solve this is my suggestion above: to get the user's instantaneous Location with `getCurrentPositionAsync`, at the same time that you start geofencing, and checking which region it is in
