### ISSUE TITLE
[android][okhttp] Standalone app crashes on Android 5-7 on some devices and works on 8-10 

### ISSUE THREAD

**Issue by blackwolf08** [expo/expo#6424]
### Environment

![89977422-65B1-4DBA-BA40-29EBAD3D9C0B](https://user-images.githubusercontent.com/31814079/69947410-99f8c200-1513-11ea-8c72-32770804661a.jpeg)

### Steps to Reproduce

App works fine on initial opening, it gets updated the second time and crashes! 

I think it is to do something with the OTA updates

**Comment by ide** [comment]
The crash needs to be fixed. This looks related to poor connectivity (https://github.com/square/okhttp/issues/3955).

**Comment by blackwolf08** [comment]
Let me know if I can be of more help in this.

**Comment by ide** [comment]
Figuring out why the crash is happening and where to properly fix it would be helpful. We try to fix issues properly instead of quick patches that just cause issues later, and the first step is to have a strong understanding of the root cause.
