### ISSUE TITLE
Facebook Platform Policy Violation SDK 35.0.0

### ISSUE THREAD

**Issue by adamhake** [expo/expo#6427]
### Environment

Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.2.10 => 3.4.12 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.9.1

Target: iOS, Android

### Actual Behavior

After upgrading to the latest Expo SDK, 35.0.0, we received an email from Facebook saying that our app, which uses Facebook Login, violates Facebook Platform Policy 8.2:

> Platform Policy 8.2: Native iOS and Android apps that implement Facebook Login must use our official SDKs for Login.
>
> Please make sure your Android app is using the most recent version of our SDK for Login. You can find more information on our Android SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login/android.

They also provided an image of what the login should look like:

![image](https://user-images.githubusercontent.com/1471793/70058633-420e9980-15ad-11ea-9c24-cd99078af136.png)

As a result, Facebook has restricted our application and we can no longer use Facebook Login on Android devices.

In SDK 35.0.0, it looks like FBSDK*Kit was upgraded to `v5.4.1`, but the Android FBSDK is still `v5.0.2` (current version is `v5.11.2`).

I'm also noticing inconsistent behavior with `Facebook.logInWithReadPermissionsAsync` on our Android builds.  Most of the time when I execute `logInWithReadPermissionsAsync`, I get this modal login screen:

![fb_modal_sanitized](https://user-images.githubusercontent.com/1471793/70062915-f6f88480-15b4-11ea-918d-8a25d297fc00.jpg)

However, occasionally I get this screen instead (on the same device):

![fb_screen_sanitized](https://user-images.githubusercontent.com/1471793/70062923-fb24a200-15b4-11ea-8e32-29e8bfac9e33.jpg)

I'm assuming that Facebook doesn't allow the first screen, only the second. With the [behavior options now gone](https://github.com/expo/expo/pull/5499), I'm not sure how to enforce this screen type.
### Reproducible Demo

It's very hard to create a reproducible Demo since it requires Facebook auditing the app and putting the restriction on it.

**Comment by cruzach** [comment]
Hey @adamhake, is this an ExpoKit project, or a managed project?

**Comment by adamhake** [comment]
@cruzach sorry, forgot to mention that. It's a managed project.

**Comment by rodrigoferra** [comment]
I have the same problem, with my simulator it works, but when it goes to my phone it opens the local facebook app that loads the web facebook and the return is complicated. I think that the solution is to remove the facebook app loading and go direct to the web.

**Comment by sjchmiela** [comment]
Both login dialogs presented in the issue description are native login dialogs. The difference is that the first one comes from the Facebook Lite app, while the second one comes from the Facebook app. The first dialog has the logo colors inverted — similarly to how Facebook Lite has the logo colors inverted (blue on white, see https://www.facebook.com/lite).

`expo-facebook` always uses the native Facebook SDK to login (which, as the docs state, “may use the web-view Login dialog” — but it's not ours or the developer's concern). If you always use `expo-facebook` to login, your app is not violating the Policy 8.2.

However, I found a problem with our setup — the default behavior is `LoginBehavior.NATIVE_WITH_FALLBACK`, which **may** use Chrome tabs to authenticate. In this scenario, the SDK expects a `ChromeTabsActivity` to be defined in `AndroidManifest.xml`… but it isn't. I'll see what I can do to fix this.
