### ISSUE TITLE
[Bug] Error on sign up (iOS / iPhone)

### ISSUE THREAD

**Issue by bennygenel** [expo/expo#643]
I got an error while signing up on iOS. Adding a screenshot of error. My guess is its related to error message showing but I didn't actually check the code.

![expo_error](https://user-images.githubusercontent.com/4287862/30471667-3f0a054a-9a02-11e7-8d26-394f3f83288e.jpg)

**Comment by jimmylee** [comment]
@bennygenel thanks for surfacing this, we're basically just showing the wrong error message for when a username or email has been taken.

**Comment by bennygenel** [comment]
@jimmylee I suspected that but actually I was able to sign up with same credentials on website so I think it was not just showing the wrong error message. just a little more info for you guys to find out whats going on. 
Keep up the good work

**Comment by jimmylee** [comment]
Thanks @bennygennel - our error messages are lost and we'll need to figure out why. But I've fixed this issue with undefined is not an object for now.

**Comment by flyingxu** [comment]
When I try to register a user name with a '.' inside, I got the same undefined error message. But when I try to register with the same name on web, I got a very specific error message.
