### ISSUE TITLE
[Notifications][Android] Notifications don't show on Android lock screen 

### ISSUE THREAD

**Issue by Ranatchai** [expo/expo#6432]
## 🐛 Bug Report

Found that in some Android [Redmi 6, Android version 8.1.0], notifications don't show on the lock screen. When I checked in the notification setting, I found that the "lock screen notifications" option is turned off. 

In some devices, this option is turned on.

I checked the expo docs and found that it doesn't support for setLockscreenVisibility that help us control these behaviors yet.

I think we should add support for setLockscreenVisibility in NotificationChannel or at least set the default to VISIBILITY_PUBLIC.

### Referrence
https://stackoverflow.com/questions/53844281/in-android-how-to-show-notifications-in-lock-screen
https://developer.android.com/reference/android/app/NotificationChannel#setLockscreenVisibility(int)

![IMG_1729](https://user-images.githubusercontent.com/5508501/70133658-22649780-16b9-11ea-854a-feb0284ddd86.jpg)

**Comment by esamelson** [comment]
Hey @Ranatchai - sorry for the slow response here. Thanks for the report -- you're right, this is a piece of functionality we're missing. We'd like to add it but can't promise to get to it anytime soon as we're a small team. Is there any chance you'd be willing to open a PR adding this? 😄

**Comment by thisis-Shitanshu** [comment]
Hey @esamelson - This issue is still open. I just wanted to know, has there been any progress in this front or a work-around?

**Comment by Ranatchai** [comment]
I created the pull request here.
https://github.com/expo/expo/pull/6440

**Comment by sjchmiela** [comment]
You should be able to set the `lockscreenVisibility` with the new `expo-notifications` API, as presented [here](https://docs.expo.io/versions/latest/sdk/notifications/#notificationchannelinput). Let me know if you encounter any problems!
