### ISSUE TITLE
Expo encountered a fatal error: java.net.UnknownHostException: Unable to resolve host "d1wp6m56sqw74a.cloudfront.net": No address associated with hostname

### ISSUE THREAD

**Issue by okeybond** [expo/expo#6436]
### Environment

Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.16.2 - /usr/local/opt/node@8/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 

Android
### Steps to Reproduce

In a standalone Android app, turn off the internet and leave the app, then return to the app while offline, it seems to restart the app, showing the splash screen again.
Similar issue to https://github.com/expo/expo/issues/607

### Expected Behavior

The app should not restart but proceed from the last known state

### Actual Behavior

In a standalone Android app, turn off the internet and leave the app, then return to the app while offline, it seems to restart the app, showing the splash screen again.

The error message below can be seen in the logs
`019-12-04 19:29:21.141 21133-21133/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nad.app, PID: 21133
    java.lang.RuntimeException: Expo encountered a fatal error: java.net.UnknownHostException: Unable to resolve host "d1wp6m56sqw74a.cloudfront.net": No address associated with hostname
        at host.exp.exponent.experience.a$2.run(BaseExperienceActivity.java:197)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)`

**Comment by cruzach** [comment]
Hey @okeybond, does this happen on a blank `expo init` project (after building the apk, of course)?

Are you sure the binary version of the app is on SDK 35?

**Comment by okeybond** [comment]
Yes, it’s SDK 35. 

I will try the blank apk

**Comment by joshg2k** [comment]
This issue occurs very infrequently for me as well. It's not on a blank project, and does not occur for everybody.

This is probably obvious, but just in case this is being captured in the onError function of AppLoading. Unfortunately I don't get much more detail out of Sentry past that.

Here is the most granular amount of information I can provide:
<img width="700" alt="Screen Shot 2020-03-30 at 14 31 21" src="https://user-images.githubusercontent.com/4231004/77953766-3731f000-7293-11ea-9018-62aed6bbe9e8.png">

**Comment by kamalpandey** [comment]
Also occurring for me after upgrade to sdk 35.

Error: Unable to resolve host "d1wp6m56sqw74a.cloudfront.net": No address associated with hostname
--

**Comment by mazorvanunu** [comment]
so, as usual, no real response from either react nor android... ? wow - how the hell is this OS controls the market ? ah yes.... i remember, heavy friends have heavy backs.

**Comment by cruzach** [comment]
This seems likely to be related to the legacy Updates code, which has been replaced with `expo-updates`, so if you're seeing this problem please upgrade to SDK 39 or 40, and let me know if you still run into it

**Comment by kovalevroman7** [comment]
I have the same problem. SDK 41

**Comment by richardrobberse** [comment]
@cruzach Same here with SDK 41 on MacOS.

**Comment by superyarik** [comment]
facing this issue with google api
Unable to resolve host "maps.googleapis.com": No address associated with hostname

**Comment by tylerc** [comment]
Been seeing this a handful of times a week with SDK 44, though honestly it's likely just transient network issues on the user's end I think.

I don't believe I saw it before SDK 44, but maybe something was swallowing the error previously.

**Comment by yogesh6260** [comment]
How to resolve this issue?

**Comment by parander** [comment]
Still happens intermittently with SDK 48. Expo Go working on iOS but the same project is giving the UnknownHostException on Expo Go under Android. 

It happened to me when urlRandomness started with an underscore (i.e. _). When I replaced the _ it worked on both Android and iOS (both using Expo Go). Seems like a ridiculous thing but it actually solved the issue for me.
