### ISSUE TITLE
Client crashing when sending post request with large file

### ISSUE THREAD

**Issue by vitorbertolucci** [expo/expo#6438]
### Environment

  Expo CLI 3.9.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

Running on Expo Client in iOS 12.3.1

### Steps to Reproduce

Send a FormData POST request with a file larger than 300MB, either using fetch or axios.

### Expected Behavior

The request would be fulfilled and send back a response or an error.

### Actual Behavior

Works fine for files up to ~200MB, but for larger files expo client crashes with no messages. Expo-CLI continues running and I'm able to reopen the app, but the request is canceled.

### Reproducible Demo

I am using Expo DocumentPicker to select a file from my iPad and then I am uploading it with the following method:

`
handleFileUpload = async (attempId, data, file) => {
    const body = new FormData();

    body.append("description", file.name + " upload");
    body.append("attemp_id", attempId);
    body.append("product_id", data.product);
    body.append("file", {
      uri: file.uri,
      type: "application/octet-stream",
      name: file.uri
        .split("/")
        .pop()
        .replace("file://", "")
    });
    body.append("file_category", "pack");

    const bearer = await AsyncStorage.getItem("bearer");

    const options = {
      method: "POST",
      body,
      headers: {
        Accept: "application/json",
        "Content-Type": "multipart/formdata",
        Authorization: bearer
      }
    };

    fetch("...", options)
      .then(res => res.json())
      .then(json => console.log(json));
}
`

I have also created a [snack demo](https://snack.expo.io/ByGeLRBTr). It's not completely reproducible beacause there are no files in it nor can I expose my API route, but it demonstrates how I am doing the file selection and upload.

I have been searching a lot about how to properly handle large file uploads with react-native but still had no luck finding anything. I would also appreciate some directions regarding it.

Thank you.

**Comment by vitorbertolucci** [comment]
I noticed that it also crashes when trying to 
`
FileSystem.readAsStringAsync(file.uri, {
    encoding: FileSystem.EncodingType.Base64
})
`
I have also tryied to partition the file using length and position options and calling readAsStringAsync inside a loop, but it crashes after a few dozens iterations.

**Comment by cruzach** [comment]
Do you think you could try [get the device logs](https://docs.expo.io/versions/latest/workflow/logging/#optional-manually-access-device-logs) to provide more info on the crash? 

200MB is a lot. We are working on supporting bundling that much into your binary, so that there would be less of a need for a request in that case

**Comment by vitorbertolucci** [comment]
I have only tryied in Expo client, because I am developing for iOS and I do not have a macOS. Also, the link you gave only shows how to see iPad's log using macOS, would there be another way?

**Comment by cruzach** [comment]
The link shows how to view logs for iPhone or iPad

**Comment by vitorbertolucci** [comment]
The section 'View logs for your iPhone or iPad' says it only applies to macOS. If you mean the logs that are displayed in expo-CLI, there are none. Expo client simply closes and nothing gets outputed on expo-CLI nor in dev tools.

**Comment by cruzach** [comment]
Ah, sorry, didn't click that you aren't using a mac. I would imagine there's a similar tool for windows/linux users, would just have to search around for it

**Comment by vitorbertolucci** [comment]
I managed to catch the logs using iTools, here it is.
[iOS Large File Crash Log.txt](https://github.com/expo/expo/files/3929391/iOS.Large.File.Crash.Log.txt)

**Comment by vitorbertolucci** [comment]
@cruzach did you have a chance to take a look at the log?

**Comment by cruzach** [comment]
Yes I did, but couldn't garner too much info from them

What would help a lot is a full repro that I can clone and run locally to simulate the crash, just need to include a test file and test endpoint
