### ISSUE TITLE
Cannot read property 'viewManagersNames' of undefined

### ISSUE THREAD

**Issue by HAIBON** [expo/expo#6439]
I run my app with ios emulator with expo-apple-authentication same introduce. In screen show error "Cannot read property 'viewManagersNames' of undefined".

**Comment by cruzach** [comment]
You'll need to be on SDK 35 to use `expo-apple-authentication`, I suspect that's the problem here. I just tested the [example from the docs](https://docs.expo.io/versions/latest/sdk/apple-authentication/#usage) on a blank expo init project and it worked 😄 

If you still have this issue on SDK 35, please fill out the full bug report template and I'll be happy to re-open

**Comment by FrenchMajesty** [comment]
I have added this package to a bare React Native app that does not use Expo and I followed the instructions to setup with `react-native-unimodules` but I get them same error

**Comment by duylinhdang1998** [comment]
@FrenchMajesty fren
+1 
I have same error 
how did you fix that ? help me

**Comment by shawn-lim** [comment]
@duylinhdang1998 , 
I ran into a similar issue. 

Check your AppDelegate.m file, especially this part:
`RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"__YOUR_APP_NAME_HERE__" initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];`

My issue was 
`RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"__YOUR_APP_NAME_HERE__" initialProperties:nil];`

was not set correctly.

**Comment by bscheideldyrt** [comment]
I'm getting the same error when I try to run snapshot tests, but the app itself runs fine.  The fix from @shawn-lim doesn't work with `react-native-navigation` since this line doesn't exist.  Any other thoughts on how to get snapshot tests working in a bare React-Native app?

**Comment by thangavel-21** [comment]
i am facing this error how can i fix this issue

**Comment by ENGR-MANSOOR** [comment]
Any solution??

**Comment by sivastu** [comment]
i added `npm i expo-face-detector` in pure react-native project. then i got same error like  TypeError: Cannot read property 'viewManagersMetadata' of null, js engine: hermes......Any solution
