### ISSUE TITLE
403 disallowed user agent 

### ISSUE THREAD

**Issue by YajanaRao** [expo/expo#6445]
### Environment

expo 35
expo-google-app-auth: 7

### Steps to Reproduce

```
const config = {
  issuer: "https://accounts.google.com",
  scopes: ["email", "profile"],
  androidClientId:
    <ID>,
};
const authState = await AppAuth.authAsync(config);

or

const { type, accessToken, user } = await Google.logInAsync(config);
```

### Expected Behavior

Google Sign In should happen

### Actual Behavior

![image](https://user-images.githubusercontent.com/38914337/70318847-faa33a00-1846-11ea-8ffb-7351c384fa3a.png)

**Comment by cruzach** [comment]
So this is happening in the Expo Client, not in a standalone app? Have you followed the setup steps listed in the [docs](https://docs.expo.io/versions/latest/sdk/google/#using-it-inside-of-the-expo-app) under `Create an Android OAuth Client ID`

**Comment by YajanaRao** [comment]
I have gone though the documentation steps for setup. It is not a standalone app.

**Comment by cruzach** [comment]
It looks like your config doesn't match that required by `Google.loginAsync` or `AppAuth.authAsync`. I tested this in the android Expo Client and `Google.logInAsync` with a config including just `scopes` and `androidClientId` worked

**Comment by rayasrahiman** [comment]
> I have gone though the documentation steps for setup. It is not a standalone app.

hello there i'm getting an 403 error had installed  
expo install expo-google-app-auth and  import * as Google from "expo-google-app-auth" and did this as well const result = await Google.logInAsync" but i end up with "Error 403: disallowed_useragent" on android but on IOS it works just fine

**Comment by blind675** [comment]
Same problem.

**Comment by rayasrahiman** [comment]
> Same problem using `expo-auth-session/providers/google`

The reason it happens because of your phone authentication with Google. Try running the app in other Android device it should work probably.
Thanks
