### ISSUE TITLE
Error trying to play audio file downloaded to file system on android

### ISSUE THREAD

**Issue by Morras** [expo/expo#6447]
I have a simple exercise app where users can choose some pre defined exercises, download the audio files to their phone and then play the audio as they progress through the exercise.

I have downloaded the file sucessfully, but when I try and load the audio file the app on my android gives and error.

This is the offending code:

```
console.log('filename: ' + exercise.fileName);
const soundObject = Audio.Sound.createAsync(
    { uri: exercise.fileName },
    {
        shouldPlay: true
    }
);
```
and this is the filename and error output that I am getting in the console:
```
filename: file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540morras%252Fexercise/Sit%20up.mp3

[Unhandled promise rejection: Error: com.google.android.exoplayer2.i.v: None of the available extractors (d, e, g, c, c, a, z, b, c, s, a, a) could read the stream.]
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:155:41 in createErrorFromErrorData
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals
```

If I download the audio file on my computer and play it back it works fine.

**Comment by cruzach** [comment]
Hey @Morras , please fill out the full bug report template for this issue. Although the code snippet you included helps, a full repro in snack would be much better.

This was also reported a while back [here](https://forums.expo.io/t/android-audio-cannot-play-back-3gp-recording/7941), you might want to try that fix

**Comment by Morras** [comment]
When trying to reproduce this in a minimal example the code works fine.
It would appear that the file I think I'm downloading might not actually be the file I am downloading. I will need to investigate that further, but as this code works I am closing this task.
