### ISSUE TITLE
Expo.Constants.manifest.extra is undefined

### ISSUE THREAD

**Issue by denghejun** [expo/expo#645]
I use the latest expo version.
And this is a part of my app.json file:

```
"expo": {
    ... ...

    "extra": {
      "test": true
    }
  }
```

Then I use in somewhere else:

```
import * as Expo from 'expo'

let test = Expo.Constants.manifest.extra.test; // Expo.Constants.manifest.extra is undefined here.
```

I'm not sure what happened. 
Could you please give me any help?

**Comment by jimmylee** [comment]
It should work, as any fields that get put into "extra" should be available. This might be a stupid question, but can you try restarting all of your environment?

Otherwise we have a bug on our end.

**Comment by denghejun** [comment]
the thing is I got an undefined when run jest tests

**Comment by ide** [comment]
Is this happening only in your Jest tests (which doesn't read app.json when configuring the mocks) or in your project at runtime as well?

**Comment by denghejun** [comment]
test only

**Comment by ide** [comment]
OK, this is because the jest mock doesn't read values from app.json. You can write this logic yourself and set the mock values for now.

**Comment by denghejun** [comment]
yeah currently I read from app.json ismanually in test，no other way ？

**Comment by terribleben** [comment]
From what I've seen in this thread, it sounds like this is expected behavior. Let me know if I should reopen because of a bug. Otherwise please open a thread on the [forums](https://forums.expo.io) if you'd like to discuss more.

**Comment by ide** [comment]
@denghejun The current behavior is expected but it seems reasonable to want to test against your actual app.json. I added this to jest-expo and published a new version. When you upgrade to SDK 21 can you try jest-expo 21.0.2 and see if Expo.Constants.manifest.extra is defined as expected for you?

**Comment by denghejun** [comment]
cool, I'll try.

**Comment by ide** [comment]
I mean jest-expo, which is made by the Expo team. jest-expo-ts is made by someone in the community. Maybe you could ask them to upgrade to 21.

**Comment by denghejun** [comment]
cool thank you.
