### ISSUE TITLE
[docs] Document how to use a custom metro.config.js for things like assetExts and sourceExts

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#6452]
https://github.com/expo/expo-cli/issues/1019#issuecomment-557030389

**Comment by pgte** [comment]
I'm using expo version 36.0.0 and I'm still unable to override the asset extensions by using `expo.packagerOpts.assetExts` on `app.json`.
Anyone knows the status of this?

**Comment by brentvatne** [comment]
this blog post shows how you can use metro.config.js to config assetExts:
https://medium.com/faun/add-custom-svg-icons-to-your-expo-app-279b492f6a15

**Comment by celandro** [comment]
With the change to expo-updates 0.2.X, this is now even more important

I am using this with expo 0.1.0 :

```const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-sass-transformer"),
    },
    resolver: {
      sourceExts: [...sourceExts, "scss", "sass"]
    },
  };
})();
```

I tried this, but it does not work:
```
module.exports = (async () => {
  const {
    resolver: { sourceExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-sass-transformer"),
      assetPlugins: ['expo-asset/tools/hashAssetFiles'],
    },
    resolver: {
      sourceExts: [...sourceExts, "scss", "sass"]
    },
  };
})();
```

**Comment by appinteractive** [comment]
any luck @celandro

**Comment by ryan-barker-zefr** [comment]
I took out sass because I couldn't figure it out

**Comment by brentvatne** [comment]
we have a docs page for this now: https://docs.expo.io/guides/customizing-metro/

for sourceExts you can do the same thing as i do in https://github.com/expo/expo-cli/issues/2199 but start expo-cli with `EXPO_USE_DEV_SERVER=1 expo start`
