### ISSUE TITLE
Local images not showing in Generated Signed APK release

### ISSUE THREAD

**Issue by Gardens18** [expo/expo#6454]
Local images not showing in Generated Signed APK release

**Dependencies :** 
"@expo/vector-icons": "^10.0.3",
    "expo": "^33.0.0",
    "expo-app-auth": "~5.0.1",
    "expo-calendar": "~5.0.1",
    "expo-constants": "~5.0.1",
    "expo-file-system": "~5.0.1",
    "expo-font": "^5.0.1",
    "expo-linear-gradient": "~5.0.1",
    "expokit": "^33.0.4",
    "g": "^2.0.1",
    "galio-framework": "^0.5.4",
    "install": "^0.13.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.1.tar.gz",
    "react-native-app-link": "^1.0.0",
    "react-native-calendars": "^1.198.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-remote-svg": "^2.0.6",
    "react-native-render-html": "^4.1.2",
    "react-native-responsive-screen": "^1.2.2",
    "react-native-unimodules": "^0.4.2",
    "react-navigation": "^3.11.0",
    "rn-pdf-reader-js": "^0.2.3"

**Comment by cruzach** [comment]
Hi! We need you to fill out the full bug report template for us to help you. Make sure you're `require`ing the images in your code somewhere, and have followed [these instructions](https://docs.expo.io/versions/latest/guides/offline-support/#bundle-your-assets-inside-your-standalone-binary).

It would also help to unzip your apk and see if the image files are included
