### ISSUE TITLE
Your app uses or references the following non-public APIs:  - PhotoLibrary.framework

### ISSUE THREAD

**Issue by SCasarotto** [expo/expo#6456]
Has anyone else run into Apple declining their app due to the following?

```
From Apple
2. 5 Performance: Software Requirements
Guideline 2.5.1 - Performance - Software Requirements


Your app uses or references the following non-public APIs:

- PhotoLibrary.framework

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

Next Steps

If you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

Resources

If there are no alternatives for providing the functionality your app requires, you can use Feedback Assistant to submit an enhancement request.
```

My dependencies are:
```
"dependencies": {
		"@react-native-firebase/app": "^6.0.3",
		"@react-native-firebase/auth": "^6.0.3",
		"@react-native-firebase/firestore": "^6.0.3",
		"@react-native-firebase/storage": "^6.0.3",
		"axios": "^0.19.0",
		"date-fns": "^2.6.0",
		"expo-font": "^7.0.0",
		"expo-image-picker": "^8.0.0",
		"jetifier": "^1.6.4",
		"moment": "^2.24.0",
		"native-base": "^2.13.8",
		"react": "16.9.0",
		"react-native": "0.61.4",
		"react-native-appearance": "^0.2.2",
		"react-native-calendars": "^1.212.0",
		"react-native-gesture-handler": "^1.4.1",
		"react-native-modal-datetime-picker": "^7.6.0",
		"react-native-reanimated": "^1.3.0",
		"react-native-screens": "^1.0.0-alpha.23",
		"react-native-select-contact": "^1.2.1",
		"react-native-snap-carousel": "^3.8.3",
		"react-native-unimodules": "^0.7.0-rc.4",
		"react-native-vector-icons": "^6.6.0",
		"react-navigation": "^4.0.10",
		"react-navigation-stack": "^1.10.3",
		"react-redux": "^7.1.1",
		"redux": "^4.0.4",
		"redux-thunk": "^2.3.0",
		"reselect": "^4.0.0",
		"tipsi-stripe": "^7.5.1",
		"validate.js": "^0.13.1"
	},
	"devDependencies": {
		"@babel/core": "^7.6.4",
		"@babel/runtime": "^7.6.3",
		"@react-native-community/eslint-config": "^0.0.5",
		"babel-jest": "^24.9.0",
		"eslint": "^6.6.0",
		"jest": "^24.9.0",
		"metro-react-native-babel-preset": "^0.56.3",
		"react-test-renderer": "16.9.0"
	},
```

Any suggestions would be great. My assumption is this might be rooted in `expo-image-picker` but that is purely a guess. I am going to dig in more and try to get any more details from Apple if this is a new policy being enforced.

**Comment by brentvatne** [comment]
it looks like we need to re-publish expo-image-picker to include this commit: https://github.com/expo/expo/commit/bded97bdd65769cf64a129a181a263fbcc8c0a47

**Comment by tsapeta** [comment]
Sorry @SCasarotto for that! We hit the same thing during Apple's review but I've forgotten to republish the unimodule after reverting this code. I've just published `expo-image-picker@8.0.1` including commit https://github.com/expo/expo/commit/bded97bdd65769cf64a129a181a263fbcc8c0a47

**Comment by outaTiME** [comment]
Hi guys, im getting the same issue here but im not using `expo-image-picker`, my report on the forums:

https://forums.expo.io/t/apple-binary-rejected-with-sdk36/31086

**Comment by brentvatne** [comment]
@outaTiME - when did you do the build? yesterday?

**Comment by outaTiME** [comment]
@brentvatne 2019-12-10T15:43:38.985Z, two days ago

**Comment by esamelson** [comment]
Hey everyone, really sorry about this -- a fix is in the works right now and should be deployed in the next few hours. Hold tight!!

**Comment by esamelson** [comment]
As of a few minutes ago, we've deployed the fix for this to our builders. I'm so sorry but if you have run into this issue already you'll need to rebuild your app with `expo build:ios` (or use `turtle-cli@0.13.3` or later and then resubmit to the stores 😞 It should be painless going forward but please let us know if you run into any more issues. We're really sorry for the trouble.

**Comment by iuliuvisovan** [comment]
So if we're using Expo what exactly should we do? Just run 'npm install expo-image-picker@latest'?

**Comment by clementoriol** [comment]
We just had the same issue: 
```
Your app uses or references the following non-public APIs:

“PhotoLibrary.framework, PLImageScrollView, PLCropOverlayCropView, unarchivedObjectOfClasses:fromData:error:”

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.
```

The app is really barebone, it's just a basic expo app displaying a webview (`react-native-webview`) and using the notification system from expo. That's it !

App was built 8 days ago, so just before the fix.
We'll try rebuilding and submitting again, I'll keep you posted.

**Comment by brentvatne** [comment]
@iuliuvisovan - you should always use `expo install` to install expo packages so that you get the correct version: `expo install expo-image-picker`.

that said, in this case the change is on the native side so all you'd need to do is rebuild with `expo build:ios`
