### ISSUE TITLE
[expo-apple-authentication] - ExpoAppleAuthenticationButtonContinueBlack isn't exported by @unimodules/react-native-adapter

### ISSUE THREAD

**Issue by danstaak** [expo/expo#6463]
### Environment

xpo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.13.2 - ~/.nvm/versions/node/v10.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.9.1

App is iOS and Android.
iPhone that is running Expo (Model: iPhone 6s) (Software version: 13.2.3)

### Steps to Reproduce

- Installed the [expo-apple-authentication] module as per documentation (`expo install expo-apple-authentication`).
- Followed the 'configuration' part of the documentation (generated keys etc)
- Include the `import * as AppleAuthentication from 'expo-apple-authentication';` statement
- Run the app `npm run start`

### Expected Behavior

Expect to be able to sign in with Apple ID.

### Actual Behavior

- Get the following error:
-- **The native view manager required by name (ExpoAppleAuthenticationButtonContinueBlack) from NativeViewManagerAdapter isn't exported by @unimodules/react-native-adapter. Views of this type may not render correctly. Exported view managers: [ExponentGLView, ExponentCamera, CTKNativeAd, MediaView, ExpoAdsAdMobBannerView, ExpoBlurView, ExpoVideoView, AdOptionsView, ExpoAdsPublisherBannerView, ExpoBarCodeScannerView, AdIconView, ExpoLinearGradient, CTKBannerView].**
- Dismiss this error and click on the button `AppleAuthentication.AppleAuthenticationButton` as per code example in documentation. Get this error:
-- **The method or property expo-apple-authentication.signInAsync is not available on ios, are you sureyou've linked all the native dependencies properly?**

**Comment by brentvatne** [comment]
you are using expo sdk 34, you will need to update to sdk 35 or higher in order to use this library - it was added in sdk 35.

**Comment by dngrhm** [comment]
I was getting a similar error using expo sdk36.  It was because I had used `yarn add expo-apple-authentication` instead of correctly using `expo install` No action necessary.  Just a breadcrumb for a future developer.  https://xkcd.com/979/

**Comment by oporter1** [comment]
I am on SDK 37 and having the issue. Is anyone else seeing this issue still?

**Comment by valentineejk** [comment]
what is the fix for this bug, I amm using expo 50

**Comment by blackMastery** [comment]
@valentineejk  did you find a fix for this
