### ISSUE TITLE
 cannot find symbol new Permissions.PermissionsRequestListener (Bare App)

### ISSUE THREAD

**Issue by guptaamol** [expo/expo#6468]
### Environment

  Expo CLI 2.11.9 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      @types/react: ^16.3.13 => 16.9.16 
      @types/react-native: ^0.60.2 => 0.60.24 
      @types/react-navigation: ^3.0.1 => 3.4.0 
      react: 16.12.0 => 16.12.0 
      react-native: ^0.61.1 => 0.61.5 
      react-navigation: ^4.0.9 => 4.0.10 

 
Android

### Steps to Reproduce

So I am using expo-location in a react-native project and cannot compile my project i am getting the following error.

    Note: /home/amol/Desktop/AccountantComplete/CompleteCode/Accountant/node_modules/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    /home/amol/Desktop/AccountantComplete/CompleteCode/Accountant/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java:361: error: cannot find symbol
            new Permissions.PermissionsRequestListener() {
                        ^
    symbol:   class PermissionsRequestListener
    location: interface Permissions
    /home/amol/Desktop/AccountantComplete/CompleteCode/Accountant/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java:502: error: cannot find symbol
            mPermissions.getPermission(Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED
                        ^
    symbol:   method getPermission(String)
    location: variable mPermissions of type Permissions
    /home/amol/Desktop/AccountantComplete/CompleteCode/Accountant/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationModule.java:503: error: cannot find symbol
                && mPermissions.getPermission(Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED
                            ^
    symbol:   method getPermission(String)
    location: variable mPermissions of type Permissions
    Note: /home/amol/Desktop/AccountantComplete/CompleteCode/Accountant/node_modules/expo-location/android/src/main/java/expo/modules/location/taskConsumers/GeofencingTaskConsumer.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    3 errors

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':expo-location:compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.

### Actual Behavior

Unable to compile project.

**Comment by brentvatne** [comment]
can you share a minimal reproducible example? https://stackoverflow.com/help/mcve

**Comment by Idimma** [comment]
`npm install expo-location@8.0.0`

Should clear the issue

**Comment by lukmccall** [comment]
Please try updated `expo-location` to `8.0.0`. 
Moreover, new `expo-permissions` (`v. 8.0.0`) are only compatible with other packages which have version >= 8.0.0.

**Comment by guptaamol** [comment]
Sure it did, thank a lot and god bless, also thank you for all the amazing
work you guys are doing at expo.
