### ISSUE TITLE
Support `module` or `jsnext:main` imports for installed packages

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#647]
Hi,

I've noticed the current release of Expo ignores the `module` or `jsnext:main` fields in installed modules `package.json` files.

You can find more info about what these fields do [here](https://github.com/apollographql/apollo-client/issues/746).

It looks like currently Expo only imports from the `main` field in `package.json`.

Is it possible to get Expo to respect the fields mentioned above when they're present?

Thanks, cheers!

**Comment by jimmylee** [comment]
Hey @pensierinmusica thanks for bringing this up, if you would like to make a feature request, throw it into https://expo.canny.io/feature-requests and if there is enough demand we can make it happen.

**Comment by pensierinmusica** [comment]
@jimmylee this should take 5 mins to implement for someone who knows the codebase well. I understand you have many feature requests, but isn't the process you describe a bit too long / unnecessary in this case?
