### ISSUE TITLE
AppRegistry.setWrapperComponentProvider has no effect in managed Expo apps

### ISSUE THREAD

**Issue by rafamrs** [expo/expo#6473]
### Environment

```
Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @bugsnag/expo: ^6.4.0 => 6.4.1 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.0 => 4.0.8 
    npmGlobalPackages:
      expo-cli: 3.11.1
```

Developing on: iOS

### Steps to Reproduce

Upgrade from Expo SDK 35 to SDK 36.

### Expected Behavior

No warnings and not a blank screen.

### Actual Behavior

![image](https://user-images.githubusercontent.com/924985/70513961-e73beb80-1b32-11ea-8a70-8564a47e105d.png)

**Comment by deniscreamer** [comment]
the same. after the upgrade

**Comment by andordavoti** [comment]
having the same issue after upgrading

**Comment by brentvatne** [comment]
@rafamrs @deniscreamer @andordavoti - can one of you please provide a reproducible example? i can't reproduce this on my end

**Comment by andordavoti** [comment]
![IMG_0292](https://user-images.githubusercontent.com/24613178/70565619-c73c1480-1b92-11ea-993a-6291c17eccb6.PNG)
Maybe this helps?

**Comment by brentvatne** [comment]
unfortunately no, is there any chance you can add me to your project on github @andordavoti?

**Comment by andordavoti** [comment]
@brentvatne  I am using bitbucket, but I can share it with you, I just need an email address

**Comment by Dagurmart** [comment]
Here is the full error as it appears on my machine

```
AppRegistry.setWrapperComponentProvider has no effect in managed Expo apps. You can instead wrap your app root component to achieve an identical result.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/expo/build/Expo.fx.js:20:65 in AppRegistry.setWrapperComponentProvider
- node_modules/react-native-root-siblings/lib/RootSiblingsManager.js:9:46 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:190368:68 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:190318:51 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:190264:65 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:184612:34 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:184255:30 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:137401:52 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:136476:47 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:126851:58 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:124814:56 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:5:0 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:45 in guardedLoadModule
* http://192.168.88.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:395047:4 in global code

```

**Comment by rafamrs** [comment]
Sorry can't share, my project has sensitive information on it.

**Comment by brentvatne** [comment]
@andordavoti - brent@expo.io

**Comment by narmiel** [comment]
same issue after upgrading

**Comment by andordavoti** [comment]
@brentvatne just shared my bitbucket repo with you

**Comment by brentvatne** [comment]
@andordavoti - can you share it again? it seems i didn't get any notification about it or access, probably because i didn't have a bitbucket account with that email after all :p i do now

**Comment by andordavoti** [comment]
@brentvatne I shared it again now

**Comment by damechen** [comment]
hit same issue after upgrading from 35 to 36

**Comment by brentvatne** [comment]
@andordavoti - i didn't get any email and don't see it in bitbucket :\ did you send it to brent@expo.io?

**Comment by damechen** [comment]
We can comment out the following code in _node_modules/expo/build/Expo.fx.js_ to temporarily disable the annoying warning message:
`
// if (__DEV__) {
//     if (Platform.OS === 'ios') {
//         // @ts-ignore
//         AppRegistry.setWrapperComponentProvider(() => DevAppContainer);
//     }
//     // @ts-ignore
//     AppRegistry.setWrapperComponentProvider = () => console.warn('AppRegistry.setWrapperComponentProvider has no effect in managed Expo apps. You can instead wrap your app root component to achieve an identical result.');
// }
`

**Comment by byCedric** [comment]
We have the same issue in our project, I can back track it all the way to `react-native-root-siblings`. I think [this code might cause the warning](https://github.com/magicismight/react-native-root-siblings/blob/243d6a4a7946cb3e3316aba648be85d8916943d5/src/RootSiblingsManager.tsx#L18-L23). We use that library because we use it indirectly by `react-native-tiny-toast@1.0.4`

<img width="481" alt="Screenshot 2019-12-13 at 23 30 54" src="https://user-images.githubusercontent.com/1203991/70836517-a842ba00-1e00-11ea-9df2-702a4462e339.png">

**Comment by serhiipalash** [comment]
@brentvatne I think most of guys have issue with [react-native-modals](https://www.npmjs.com/package/react-native-modals) library.

https://github.com/jacklam718/react-native-modals/issues/207

And the issue is that it stopped working in SDK36 because of these lines in commit from 11 Nov

https://github.com/expo/expo/commit/8f0536169ad08ecad27f1f98f9b96765a3713489#diff-bbff85a4de912927b05b5d635a5100f1R26-R29

Here is the video with bug

https://drive.google.com/file/d/1JzxIeyxIH-3EPhJpohHE93OsDxHK4DRo/view

and my test repo

https://github.com/serhiipalash/test-expo-react-native-modals

The problem, as I understood, is that you can set only one wrapperComponentProvider, and, when you try to do it multiple times, next wrapperComponentProvider will just replace previous.

I made a pr with fix https://github.com/expo/expo/pull/6530 and also a demo vide how the new code works

https://drive.google.com/file/d/1-KU56oP4xAkAeNA_NV__W6vg6ZLMvcRC/view

**Comment by hhaltas** [comment]
Can someone help me ? 

ERROR -->EXPO

> 
> AppRegistry.setWrapperComponentProvider has no effect in managed Expo apps. You can instead wrap your app root component to achieve an identical result.
> 
> Stack trace:
>   http://192.168.3.101:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:142967:28 in warn
>   http://192.168.3.101:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:106672:23 in warn
>   node_modules\expo\build\Expo.fx.js:20:65 in AppRegistry.setWrapperComponentProvider
>   node_modules\react-native-root-siblings\index.js:18:40 in AppRegistry.setWrapperComponentProvider$argument_0
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   node_modules\react-native-dialog-component\dist\DialogManager.js:1:938 in <global>
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   node_modules\react-native-dialog-component\dist\index.js:1:362 in <global>
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   src\components\Profils\ProfilHeader.js:4:0 in <global>
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   src\screens\Profils\index.js:8:0 in <global>
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   src\RouterPage.js:10:0 in <global>
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   App.js:3:0 in <global>
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   node_modules\expo\AppEntry.js:5:0 in <global>
>   node_modules\metro\src\lib\polyfills\require.js:322:6 in loadModuleImplementation
>   node_modules\metro\src\lib\polyfills\require.js:201:45 in guardedLoadModule
>   http://192.168.3.101:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:209173:4 in global code
> 

```
Package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "axios": "^0.19.0",
    "deprecated-react-native-listview": "0.0.6",
    "expo": "^36.0.0",
    "expo-font": "^8.0.0",
    "native-base": "^2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-dialog-component": "^0.2.17",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-image-grid": "^1.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-photo-grid": "0.0.2",
    "react-native-reanimated": "~1.4.0",
    "react-native-router-flux": "^4.0.6",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-timeline-listview": "^0.2.3",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.0.0"
  },
  "private": true
}

```

How can I solve ?
and a way out PLEASE

**Comment by brentvatne** [comment]
this is resolved in expo@36.0.1

thank you @serhiipalash and @byCedric for the additional info and the pr!

**Comment by Dagurmart** [comment]
I have a dumb question. How do I upgrade to 36.0.1?

**Comment by andordavoti** [comment]
@Dagurmart I thought expo upgrade should do it, but that doesn't seem to do anything:/ it says I'm already on the latest version. does anyone know how to upgrade?

**Comment by brentvatne** [comment]
change the version of the `expo` package in `package.json` to `36.0.1`

**Comment by flieks** [comment]
@brentvatne do you have to update the store for these small releases ?

**Comment by byCedric** [comment]
@flieks it depends what you changed. There is [some documentation describing when you need to create a new build](https://docs.expo.io/versions/latest/workflow/publishing/#limitations). Probably useful to check that out 😄
