### ISSUE TITLE
Font.loadAsync not loading third-party fonts and also vector icons

### ISSUE THREAD

**Issue by ubaidjs** [expo/expo#6476]
### Environment
```
Expo CLI 3.11.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    Target: Android and iOS
```

### Steps to Reproduce
upgrade to expo sdk 36

### Expected Behavior
To load the font like it does in sdk 35.

### Actual Behavior
It is showing this error even though the font is loaded correctly in App.js - 
```
fontFamily "space-mono" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:63:8 in console.error
- node_modules\expo\build\environment\muteWarnings.fx.js:27:24 in error
- node_modules\expo\node_modules\expo-font\build\Font.js:23:16 in processFontFamily
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3683:38 in diffProperties
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3557:6 in addNestedProperty
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:3694:8 in diffProperties
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:4109:29 in createInstance
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15835:12 in completeWork
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19409:28 in completeUnitOfWork
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19380:30 in performUnitOfWork
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19347:39 in workLoopSync
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18997:22 in renderRoot
* [native code]:null in renderRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18709:28 in runRootCallback
* [native code]:null in runRootCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
- node_modules\scheduler\cjs\scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18556:30 in scheduleUpdateOnFiber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7799:17 in classComponentUpdater.enqueueSetState
- node_modules\react\cjs\react.development.js:325:31 in Component.prototype.setState
* http://192.168.43.115:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:133659:27 in dispatch
- node_modules\@react-navigation\core\lib\module\getChildNavigation.js:1:1478 in actionHelpers.actionName
* http://192.168.43.115:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:165555:48 in _callee$
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:271:30 in invoke
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:135:28 in invoke
- node_modules\regenerator-runtime\runtime.js:145:19 in Promise.resolve.then$argument_0
- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:25 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:146:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:194:17 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:407:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**Comment by makirby** [comment]
Having a similar issue. Ejecting to Expokit on 36.0.0 and no fonts are bundled. The same codebase on 35.0.0 does not have this issue after ejecting.

**Comment by zeritte** [comment]
please try running `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c` its probably a caching error

**Comment by ubaidjs** [comment]
> please try running
> `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c`
> its probably a caching error

Thanks @zeritte, this method worked

**Comment by MikeMJ** [comment]
Same thing is true in my case. I upgraded to sdk 36. Noticed that it also ugrades expo-font to 8.0.0. Think it might also have something to do with it because with sdk 35 I had `expo-font:latest`, and when running npm install I'd gotten it upgraded from 7 to 8 and that caused this issue. I then downgraded the expo-font version to 7 and the problem went away. But with sdk 36 even if I downgrade expo-font it doesn't help. That way it complains about not being able to find the FontLoader.js

**Comment by MikeMJ** [comment]
The sdk 36.0.1 has just been released and upgrading to it solved my problem.

**Comment by doyinspc** [comment]
Just upgraded to expo 36 and could not use custom fonts. How do I get 36.0.1

**Comment by MikeMJ** [comment]
Just as you would upgrade any package. You can:
1. Change the expo version in package.json file from "^36.0.0" to "^36.0.1" and issue the "npm install" command. This will go over every single package defined in the package.json file
2. Or just execute "npm install expo@36.0.1"
3. You might also try expo upgrade, but I'm not sure if this will work. I doubt it only works for major version upgrades. But again, this is just a doubt.

**Comment by zeritte** [comment]
> Just as you would upgrade any package. You can:
> 
> 1. Change the expo version in package.json file from "^36.0.0" to "^36.0.1" and issue the "npm install" command. This will go over every single package defined in the package.json file
> 2. Or just execute "npm install expo@36.0.1"
> 3. You might also try expo upgrade, but I'm not sure if this will work. I doubt it only works for major version upgrades. But again, this is just a doubt.

I dont recommend 1st and 2nd solutions. I tried them and failed. I suggest `expo upgrade`, say yes even if 

> it says you are on the latest version, would you like to move on?

**Comment by MikeMJ** [comment]
> > Just as you would upgrade any package. You can:
> > 
> > 1. Change the expo version in package.json file from "^36.0.0" to "^36.0.1" and issue the "npm install" command. This will go over every single package defined in the package.json file
> > 2. Or just execute "npm install expo@36.0.1"
> > 3. You might also try expo upgrade, but I'm not sure if this will work. I doubt it only works for major version upgrades. But again, this is just a doubt.
> 
> I dont recommend 1st and 2nd solutions. I tried them and failed. I suggest `expo upgrade`, say yes even if it says
> 
> > you are on the latest version, would you like to move on?

I think I did the first option and it worked.

**Comment by doyinspc** [comment]
Thanks a lot I took a hint from @zeritte  . I deleted the node_modules folder and the package-lock.json. then ran `npm install`. and its ok .Am using windows os. Thanks everyone

**Comment by MikeMJ** [comment]
Weird. I'd tried everything, including deleting the node_modules folder and the package-lock.json file and it hadn't helped. Upgrading to 36.0.1 worked immediately.

**Comment by loureironanda** [comment]
I tried to upgrade to version 36.0.1 and it didn't work. I do not know what else to do.

**Comment by MikeMJ** [comment]
Have you tried emptying the node_modules folder and then running npm install?

**Comment by gil-air-may** [comment]
@loureironanda check your sdk version on app.json (not only on package.json). Use ` "sdkVersion": "36.0.0",`

**Comment by princefishthrower** [comment]
As of 2020.03.02, you can't upgrade to version 36.0.1 because it doesn't exist. You'll get the error:

`Error: Invalid sdkVersion. Valid options are 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 33.0.0, 34.0.0, 35.0.0, 36.0.0`

**Comment by blakehoffman** [comment]
I was having this exact same issue.  I was able to upgrade to 36.0.1 and it resolved my issue with loading third party fonts.

**Comment by esteban199** [comment]
sdk: 36.0.1

Hello people, the only way i fix it was: 

1. `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c`

2. I use async/await with componentDidMount() to wait until the font is loaded, like the expo doc https://docs.expo.io/versions/latest/guides/using-custom-fonts/: 

```
componentDidMount = async () => {
    await Font.loadAsync({
      'neohellenic-regular': require('../../assets/fonts/GFSNeohellenic-Regular.ttf'),
    });
    this.setState({ loading: false })
  }
```

**Comment by YahiaBadr** [comment]
if you are using any of these libraries i found that they make conflict
react-native-svg or react-native-svg-transformer.
If so, then remove them using yarn remove or npm uninstall.

**Comment by anirban-hazra** [comment]
@ubaidjs thank you for your help

**Comment by creativemind1** [comment]
I'm facing this issue frequently but now after last 2 days I was consistently try to figure this same issue. I had  `"expo": "^36.0.1"`. After following the advice of @MikeMJ I have done `npm i expo@36.0.1`, then Boom! It works!!!

**Comment by MatheusNP** [comment]
> 
> 
> > Just as you would upgrade any package. You can:
> > 
> > 1. Change the expo version in package.json file from "^36.0.0" to "^36.0.1" and issue the "npm install" command. This will go over every single package defined in the package.json file
> > 2. Or just execute "npm install expo@36.0.1"
> > 3. You might also try expo upgrade, but I'm not sure if this will work. I doubt it only works for major version upgrades. But again, this is just a doubt.
> 
> I dont recommend 1st and 2nd solutions. I tried them and failed. I suggest `expo upgrade`, say yes even if it says
> 
> > you are on the latest version, would you like to move on?

Amazing! `expo upgrande` definitely worked for me. Thank you

**Comment by luizfverissimo** [comment]
I fix this problem by removing the expo-font folder inside node-modules/expo/node-modules. In my case I had 2 expo-font installed.

I followed this [link](https://www.gitmemory.com/issue/expo/expo/5507/527495103)!

**Comment by Edenghajakk** [comment]
If anyone still have this font not loaded issue, try check your code where you use `fontFamily: ''`, either its clashed with `fontWeight: ''` or not. eg:

```
// component
<Text style={styles.text}>Testing 123</Text>

// styles
text: {
  fontSize: 12,
  fontFamily: 'Quicksand',
  fontWeight: 'bold' <-- remove this
}
```

So basically, the custom font(let say from Google Fonts) looks unloaded because of the `fontWeight`. Actually, its already loaded, but not showing because it clashed. Try removing it and see.

**Comment by Buzzd-Admin** [comment]
I'm on SDK 38, and this is what worked for me. Use the useFont hook instead of loadASync as per [Expo's latest doc on using Custom Fonts.
](https://docs.expo.io/guides/using-custom-fonts/)
```
// Before
const [fontLoaded, setFontLoaded] = useState(false);

const fetchFonts = async () => {
	return await Font.loadAsync({
		'Your-Font-Name': require('./assets/fonts/Your-Font-Name.ttf'),
	});
};

if (!fontLoaded) {
	<AppLoading startAsync={fetchFonts} onFinish={() => setFontLoaded(true)} />;
}

// After
let [fontsLoaded] = useFonts({
	'Your-Font-Name': require('./assets/fonts/Your-Font-Name.ttf'),
});

if (!fontsLoaded) {
	return <AppLoading />;
} else {
	return (
		// Your Root Componenet Goes Here
	);
}
```

**Comment by psudocode** [comment]
> If anyone still have this font not loaded issue, try check your code where you use `fontFamily: ''`, either its clashed with `fontWeight: ''` or not. eg:
> 
> ```
> // component
> <Text style={styles.text}>Testing 123</Text>
> 
> // styles
> text: {
>   fontSize: 12,
>   fontFamily: 'Quicksand',
>   fontWeight: 'bold' <-- remove this
> }
> ```
> 
> So basically, the custom font(let say from Google Fonts) looks unloaded because of the `fontWeight`. Actually, its already loaded, but not showing because it clashed. Try removing it and see.

this fix my problem but I need some hack to make bold works

```
let customFonts = {
  'Ubuntu': require('./../assets/fonts/Ubuntu-Regular.ttf'),
  'Ubuntu-Bold': require('./../assets/fonts/Ubuntu-Bold.ttf'),
};

export default function({ style, children, ...props}) {
  const newStyle = {...style}
  delete newStyle.fontWeight    // delete default font weight
  const [loaded, setLoaded] = useState(false)

  const _loadFontsAsync = async () => {
    await Font.loadAsync(customFonts);
    setLoaded(true)
  }

  useEffect(() => {
    _loadFontsAsync() 
  }, [])

  if(!loaded){
    return <AppLoading />
  } else {
    return (
      <Text style={{...newStyle, fontFamily: style.fontWeight === 'bold' ? 'Ubuntu-Bold' : 'Ubuntu'}} {...props}>{children}</Text>
    )
  }
}

```
