### ISSUE TITLE
WheelPicker android

### ISSUE THREAD

**Issue by IronCoderXYZ** [expo/expo#648]
Hi, 

So far I have absoltuely loved using expo. But now, I would like to add a wheel picker (inline) to my app, it works fine on iOS but on Android it just shows a red outline. I think it has to do with needing to add custom build scripts, for this I would have to eject from expo; I really don't want to.

Is there another way I can implement a pickerview on android?

Thank you!

**Comment by terribleben** [comment]
Hi, the only result I can find for this is [this library](https://github.com/ElekenAgency/ReactNativeWheelPicker) which does appear to require native code. That means you would need to detach to use it.

You could also probably implement this in pure JS without requiring third party native code.

If you think we should add this to our SDK, please open a feature request on [canny](https://expo.canny.io/feature-requests), we pay attention to those so it's a good way for us to keep track. :)
