### ISSUE TITLE
[MapView][Android] null is not an object - AirMapModule Android coordinateForPoint

### ISSUE THREAD

**Issue by vincentvella** [expo/expo#6481]
### Environment
```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^5.0.0 => 5.0.2
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.1
```

Targeting Android Client and Android Standalone

### Steps to Reproduce
Use `expo install react-native-maps`
Create a ref of the map:
```<MapView ref={ref}```
Attempt to retrieve coordinate at a specific device X/Y by using
`map.current.coordinateForPoint(x, y);`
Receive Error: 
`TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.coordinateForPoint')`

I have been unable to access some of the MapView methods from react-native-maps documented here: https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md
I can also not access the getCamera method which is necessary for the library moving forward as they are deprecating a couple of the other methods used to move the users' view of the map.

### Expected Behavior
Upon accessing that method I should have received a Latitude/Longitude as documented in the react-native-maps `Point` type: ( I receive it on iOS but not on Android)
```
type Point {
  x: Number,
  y: Number,
}
```

### Actual Behavior
I receive a type error:
`TypeError: null is not an object (evaluating '_reactNative.NativeModules.AirMapModule.coordinateForPoint')`

### Reproducible Demo
https://snack.expo.io/@vincentvella/shallow-waffle

**Comment by cruzach** [comment]
Hi! This has been reported in other, open issues, most notably [here](https://github.com/expo/expo/issues/4791), so I'm going to close this as a duplicate

As I say in the linked issue- it's still not clear that this is an issue with expo, and not with react-native-maps. If you can provide more information that indicates the issue lies with Expo and not react-native-maps, that would be a big help!
