### ISSUE TITLE
[ART]Can't use react-native-community/art from SDK36

### ISSUE THREAD

**Issue by sungsong88** [expo/expo#6482]
### Environment

```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
      npm: 6.13.3 - ~/.nvm/versions/node/v12.7.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.1
```

Target: Expo Client on Android and Expo Client on iOS

### Steps to Reproduce

* To reproduce the crash
  1. Install `react-native-progress@4.0.2`

### Expected Behavior

No crashes.
Also, documentation in https://docs.expo.io/versions/latest/sdk/art/ says the ART is part of react-native.
ART no longer part of react-native. It's moved out as react-native-community project. (https://github.com/react-native-community/art)

### Actual Behavior

Crash with message:
`Error while updating property 'stroke' in shadow node of type: ARTShape`

### Reproducible Demo

https://expo.io/@sungsong88/art-demo

For now solution: Make sure plugins use ART from react-native, instead of the react-native-community/art. Ex) react-native-progress@3.6.0

**Comment by davidbiller** [comment]
https://github.com/oblador/react-native-progress/issues/183
Same here for this lib.

**Comment by cruzach** [comment]
`react-native-progress` V4 and above rely on the `react-native-community` version if the ART library, which is not included in the Expo SDK. 

> ART no longer part of react-native

true, but we maintain a fork of it so you can continue using it from that library. A good workaround here is, like you said, to use v3 of `react-native-progress`

**Comment by duylinhdang1998** [comment]
V3 is not working on Expo sdk36 with error  "No component found for view with name ARTShape"

**Comment by gkuhn1** [comment]
I'm facing the same issue when upgrading from SDK 35 to 36.
`"react-native-progress": "^4.0.2"` works like a charm on SDK 35. 
But breaks as reported by OP on 36.

Older versions of `react-native-progress` (3.6.0 and 3.5.0) also don't work on SDK 36 with
`"No component found for view with name ARTShape"` error.

I was not able to find a workaround for this issue and had to roll back to SDK v35.

> `react-native-progress` V4 and above rely on the `react-native-community` version if the ART library, which is not included in the Expo SDK.

This version works fine on SDK 35, even with the `react-native-community/art` version. 

> > ART no longer part of react-native
> 
> true, but we maintain a fork of it so you can continue using it from that library. A good workaround here is, like you said, to use v3 of `react-native-progress`. Otherwise, if it's imperative that you upgrade to v4 of `react-native-progress`, you could use the bare workflow and thus install any native libraries you'd like!

Is it possible that the fork of `react-native` maintained in expo doesn't contain the `ARTShape` component?

**Comment by davidbiller** [comment]
> Is it possible that the fork of `react-native` maintained in expo doesn't contain the `ARTShape` component?

ART no longer part of react-native

**Comment by davidbiller** [comment]
> ART library

This will never be a part of expo? 
Than i have to search an other lib, or change to bare workflow. 
So much work than :D

**Comment by cruzach** [comment]
@gkuhn1 
> Is it possible that the fork of react-native maintained in expo doesn't contain the ARTShape component?

Looks like it's there - https://github.com/expo/react-native/blob/sdk-36/Libraries/ART/ARTShape.m

Seeing as multiple people are having this problem, can someone share a minimal repro of ART working on SDK 35 but breaking on 36 that I can run locally?

@davidbiller as I said above, we maintain a fork of it so you can continue using it from that library. Not sure why you'd say Expo only makes sense when all react native community libraries are included. We include some, and for others we maintain our own implementation, and then for a select few we are using the `react-native` version from our own fork of it.

**Comment by lbornov2** [comment]
Happens on iOS only for me:
```
    "react-native-progress": "^4.0.1",
    "react-native-progress-circle": "^2.1.0",
```

Anyone have a solution?

**Comment by cruzach** [comment]
Sorry everyone, I was mistaken- ART was indeed removed in SDK 36 😦 I'll make an update to our SDK 36 docs to reflect this

**Comment by duylinhdang1998** [comment]
@cruzach when expo fix it :D ?

**Comment by davidbiller** [comment]
> @gkuhn1
> 
> > Is it possible that the fork of react-native maintained in expo doesn't contain the ARTShape component?
> 
> Yeah, it looks like that's the case
> 
> @davidbiller Not sure why you'd say Expo only makes sense when all react native community libraries are included. We include some, and for others we maintain our own implementation, and then for a select few we are using the `react-native` version from our own fork of it.

It just seems to me at the moment that React Native wants to outsource as much as possible to react native community. 

AsyncStorage, ART... there will be more to come in the future. 
We all surely use a lib that is somehow affected by it. 
Amplify.js from AWS imports AsyncStorage from community, so I had to write my own store to overwrite it. 

ART is now the next one. 

Probably the plan is to outsource more and more. 
The libs adapt. Expo will be able to offer fewer functions with each outsourcing.

**Comment by cruzach** [comment]
React native is letting the community play a larger role now, that's correct

Expo is adapting by bringing the bare workflow forward, and to feature parity with the managed workflow. In bare, you can import any community module, or even write your own native code. So, Expo will actually be able to offer **more** functionality in the near future.

Separately, I wanted to address `AsyncStorage`- that module has not been removed from the Expo managed workflow, and will not be removed until we have a suitable replacement for it. In regards to ART, as we say in our docs- "It is barely documented and instead you likely want to use Svg which is more feature complete and better documented and more standard implementation of vector graphics," but I understand that you're using a separate library that relies on it.

**Comment by cruzach** [comment]
Updated the docs and changelog to reflect this removal https://github.com/expo/expo/pull/6570
