### ISSUE TITLE
Fast Refresh breaking useMemo, useEffect, etc.

### ISSUE THREAD

**Issue by gustavopch** [expo/expo#6483]
### Environment

Got this error running `expo diagnostics`:

```
Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at a.run.then.e (/home/gustavo/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/envinfo/dist/envinfo.js:1:97131)
```

But I think this may help:

- Expo v36.0.0
- Expo CLI v3.11.1
- Node.js v10.16.0
- Arch Linux 5.4.2-arch1-1

Emulator:

- Expo (Android) v2.14.0
- Android 9.0 Pie (AVD Nexus 5 API 28; Emulator 29.2.1-5889189; KVM 12.0.0)

### Steps to Reproduce

- Open my repro linked below, which is basically the initial app created by `expo init` with a `useMemo` and a `useEffect` added to the App component.
- With the app running, save the file App.js a few times.

### Expected Behavior

- It should only run the code inside `useMemo` and `useEffect` once, as the dependencies array is empty.

### Actual Behavior

- It actually recomputes `useMemo` and `useEffect` whenever you save the file.
![image](https://user-images.githubusercontent.com/10941958/70580526-ec308780-1b92-11ea-890c-6ac10e3288eb.png)

### Reproducible Demo

https://github.com/gustavopch/repro-fast-refresh-issue

**Comment by gustavopch** [comment]
Tried to put the `console.log` in the module scope and found that it also runs whenever I save any file in the project. So it's not at all specific to `useMemo` and `useEffect`.

The actual undesired result to me happens as `firebase.initializeApp` throws an error saying that it's already initialized whenever I save some file that doesn't export a component. Now I'm thinking this may just be how Fast Refresh is supposed to work instead of bug. In that case, I'll have to perform some kind of check before calling `firebase.initializeApp` to make sure it's not already initialized.

If this is the intended behavior, this issue can be closed.

**Comment by brentvatne** [comment]
i believe this is expected behavior as per https://facebook.github.io/react-native/docs/fast-refresh#how-it-works. this is a good talk for more info on fast refresh: https://youtu.be/Mjrfb1r3XEM?t=64

i will create an issue for the `expo diagnostics` error which it seems is an issue on linux

**Comment by gustavopch** [comment]
@brentvatne Thanks for the link to the talk.

For anybody else reading this in the future, Brian explains that memoization may be affected by Fast Refresh in this exact moment: https://youtu.be/Mjrfb1r3XEM?t=484. Also keep in mind that the docs say:
> You may rely on useMemo as a performance optimization, not as a semantic guarantee. (https://reactjs.org/docs/hooks-reference.html#usememo).
