### ISSUE TITLE
react-native-view-shot broken in SDK36

### ISSUE THREAD

**Issue by Hirbod** [expo/expo#6485]
### bug report
Scale, Transform und Rotation of View ignored

#### Version & Platform

```bash
react-native-view-shot@3.0.2
```

**Platform:** iOS? Android?
iOS and Android

#### Expected behavior
Should make screenshot as seen on the device

#### Actual behavior
Takes screenshot but all rotations, scales and positions (translate, transform, scale) are ignored

#### Steps to reproduce the behavior

Before I upgraded to EXPO SDK 36, I developed a little "Picture designer". People could add pictures and text to the view, translate them, rotate them, scale them. After they've finished, I saved the result using ```captureRef```. It worked perfectly on EXPO SDK 35. Now, after I did upgrade, its' just broken. It still makes screenshot, but it doesn't take the positions or anything else into account, it's just the initial position of the elements.

```jsx
                        <View ref={this.contentRef} style={styles.imageWrapper}>
                            <LinearGradient
                                colors={this.state.dominantColors}
                                style={{
                                    width: Dimensions.get('window').width,
                                    flex: 1,
                                    borderRadius: 0
                                }}>
                                <PinchableBox image={this.state.selectedImage}>

                                    {
                                        this.state.inputIsFocused &&
                                        <BlurView tint={'dark'} intensity={100}  style={styles.inputMask}></BlurView>
                                    }

                                    {
                                        this.state.inputs.map(this.createTextInputs)
                                    }

                                </PinchableBox>
                            </LinearGradient>
                        </View>
```

I have a view, and a LinearGradient + my PinchableBox, which contains Animated.Views (which get manipulated using react-native-gesture-handler) and pictures + text which can be rotated and transformed and repositioned.

**Comment by Hirbod** [comment]
Ok, I found the solution: I was calling `this.setState({ isLoading: true });` right before the screenshot, which caused a re-render. This was not a issue with SDK35, so I guess SDK 36 renders a bit behind. I removed the setState and call it after the screenshot, everything works again as expected. Can be closed but might be helpful for others.

**Comment by tsapeta** [comment]
Ok, I'm closing it but feel free to reopen when the issue comes back 🙂
