### ISSUE TITLE
EXPO notifications is not reliable

### ISSUE THREAD

**Issue by dhcmega** [expo/expo#6486]
Hi, I love EXPO and thanks a lot for it, but in my experience notifications is not reliable and not that good for escalation.
```
Our code broke
It looks like there was an error we need to look at. Sorry about the inconvenience.
```
```
EXPO connection error: Server error: `POST https://exp.host/--/api/v2/push/send` resulted in a `504 Gateway Time-out` response:
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><c (truncated...)
```

This is a recurring problem, but AFAIK I cannot use firebase for notification with iOS right? I can only use it for android, is that right?

Is there any alternative?

Thanks!!

dhcmega

**Comment by dhcmega** [comment]
Also, the status page shows:
https://status.expo.io/
`Push Notifications Broker       Operational`

but the web page and API gives:
`504 Gateway Time-out`

**Comment by cruzach** [comment]
Hi @dhcmega, sorry about the instability this morning! We've updated the status page since then, with an incident for Dec 11, 2019, and are looking into increasing reliability.

In the meantime, you're correct that you can't use Firebase for iOS notifications yet

**Comment by sillyjason** [comment]
Hi Expo team,
I'm experiencing the same issue. Captured error from my notificaton function: Expo responded with an error with status code 504.... <center><h1>504 Gateway Time-out</h1></center>

This thread is suggesting that similar issues in the past had to do with Expo server stability. May I check that is it something with Expo again or is it my code? 

Here's a snippet of my Firebase function: 

return admin.firestore().getUserNotificationTokensSnapshot()
        .then( snapshot => {
            let notificationTokens = {}

            snapshot.forEach( doc => {
                const docID = doc.id
                const docData = doc.data()
                if ( docData.notification ) {

                    const { expoToken } = docData.notification

                    const tokenString = getTokenStringFromToken(expoToken)

                    if ( tokenString ) {
                        notificationTokens[docID] = tokenString
                    }
                }
            })

            const userIDs = Object.keys(notificationTokens)
            const now = Date.now()

            const notificationObjectKey = `${type}-${uid}-${now}`

            let messages = []

            for ( let i=0; i<userIDs.length; i++ ) {
                const pushToken = notificationTokens[userIDs[i]]
                if (Expo.isExpoPushToken(pushToken)) {
                    messages.push({
                        to: pushToken,
                        sound: 'default',
                        title,
                        body,
                        data: {...notificationData, notificationObjectKey},
                    })
                }
            }

            let chunks = expo.chunkPushNotifications(messages)
            let tickets = []

            return Promise.all(chunks.map(chunk => {
                return expo.sendPushNotificationsAsync(chunk)
                    .then( ticketChunk => {
                        tickets.push(...ticketChunk);
                        return Promise.resolve(true)
                    })
            }))
                .then( _ => {
                    let receiptIds = [];
                    for (let ticket of tickets) {
                        if (ticket.id) {
                            receiptIds.push(ticket.id);
                        }
                    }

                    //function to update receipts in the firebase 
                })
                .then( _ => {
                    console.log('done!')
                    return {
                        success: true
                    }
                })
                .catch( e => {
                    console.log('err: ', e.message)
                    return {
                        success: false,
                        errorCode: 'unknown',
                        errorMessage: e.message
                    }
                })

        })

**Comment by Codelica** [comment]
@sillyjason I think there have been some hiccups lately with the Expo push service, we're seeing random 504's logged to Sentry from our delivery backend the last few weeks.  Recovery seems to be quick enough that they don't seem to show on https://status.expo.dev/.  Not sure if this is something being addressed, but we're looking into adding some cache/retry code regardless.

**Comment by proSingularity** [comment]
Also seeing 504 errors more or less regularly. Interestingly, the errors occur much more often at 18:00 UTC than my other daily-scheduled push notifications earlier in the day. 

Today, however, more errors have occured. Between 09:00 and 11:00 UTC and also again around 18:00 UTC. Here is one such error log - essentially a 504 Gateway timeout error page from NGinX

```
2021-10-13T09:00:53.382Z 3b15cc07-2918-40a2-9fd2-add0cf4dde73 ERROR Error: Expo responded with an error with status code 504: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> at Expo.<anonymous> (/var/task/node_modules/expo-server-sdk/build/ExpoClient.js:234:30) at Generator.next (<anonymous>) at /var/task/node_modules/expo-server-sdk/build/ExpoClient.js:8:71 at new Promise (<anonymous>) at __awaiter (/var/task/node_modules/expo-server-sdk/build/ExpoClient.js:4:12) at Expo.getTextResponseErrorAsync (/var/task/node_modules/expo-server-sdk/build/ExpoClient.js:233:16) at Expo.<anonymous> (/var/task/node_modules/expo-server-sdk/build/ExpoClient.js:222:35) at Generator.next (<anonymous>) at fulfilled (/var/task/node_modules/expo-server-sdk/build/ExpoClient.js:5:58) at processTicksAndRejections (internal/process/task_queues.js:97:5) { statusCode: 504, errorText: '<html>\r\n' + '<head><title>504 Gateway Time-out</title></head>\r\n' + '<body>\r\n' + '<center><h1>504 Gateway Time-out</h1></center>\r\n' + '<hr><center>nginx</center>\r\n' + '</body>\r\n' + '</html>\r\n' }
```

**Comment by dhcmega** [comment]
Hi, I have also been getting those errors. A few per week.

**Comment by amagnolo** [comment]
I get "504 Gateway Time-out" errors frequently, twice today. I would expect a higher reliability from expo notification servers.

**Comment by kevgrig** [comment]
FYI, there is also an option of running your own notification servers: https://docs.expo.dev/push-notifications/sending-notifications-custom/

**Comment by kevgrig** [comment]
At some point as Expo continues to scale, it's a lot to ask of them to continue offering a high-volume service for free. Maybe expo should offer a paid tier for its notification server that has higher SLAs, in addition to a free tier.

**Comment by amagnolo** [comment]
> At some point as Expo continues to scale, it's a lot to ask of them to continue offering a high-volume service for free. Maybe expo should offer a paid tier for its notification server that has higher SLAs, in addition to a free tier.

I agree and I would gladly pay for such a service: debugging these errors already cost me probably more than what the subscription would cost.
The free tier could be limited in number of notification sent, but in my opinion shouldn't be so unreliable and place the burden of exponential backoff on clients by design: this kind of defeats the expo mission of streamlining app development.
The same reasoning applies to the implementation of my own notification server (thanks for the hint, though).

**Comment by kevgrig** [comment]
> debugging these errors already cost me probably more than what the subscription would cost

I agree. For example, the current Ruby on Rails client does not report the underlying HTTP error code, the [PR to fix that](https://github.com/expo-community/expo-server-sdk-ruby/pull/36) was open for about a year and only recently merged, and a new version of the Gem wasn't concurrently released (as the project is clearly, and understandably, under-maintained); so, one would need to use something like `gem 'exponent-server-sdk', git: "https://github.com/expo-community/expo-server-sdk-ruby.git", branch: "master"` in their Gemfile (I'm being so specific because I suspect other RoR users will end up at this issue in search of a way to debug the problem).

> The free tier could be limited in number of notification sent, but in my opinion shouldn't be so unreliable and place the burden of exponential backoff on clients by design: this kind of defeats the expo mission of streamlining app development.

That's a bit less clear since the app development is essentially infinitely horizontally scalable (from the point of view of the Expo team) as it doesn't depend on any external Expo server. I'm guessing what has happened is that Expo is continuing to grow a lot -- because it's so good! -- and they can't justify the expense of scaling the notification servers since that's a pure cost center right now. As you mention, though, I suspect many professional users of Expo are willing to pay for a premium tier, and that could end up subsidizing the horizontal and vertical scaling of the free tier.

**Comment by Codelica** [comment]
I'd love to see a paid notification service with higher SLAs to at least receive the payload.  Add support for notification media (images, video, etc) like was was done and [reverted in 2019](https://github.com/expo/expo/pull/6139), critical and time-sensitive alerts on iOS and they can charge me double.  👍

**Comment by amagnolo** [comment]
> > debugging these errors already cost me probably more than what the subscription would cost
> 
> I agree. For example, the current Ruby on Rails client does not report the underlying HTTP error code

I feel your pain... the java client library is in an even worse situation, it's not maintained anymore.

**Comment by amagnolo** [comment]
> I'd love to see a paid notification service with higher SLAs to at least receive the payload. Add support for notification media (images, video, etc) like was was done and [reverted in 2019](https://github.com/expo/expo/pull/6139), critical and time-sensitive alerts on iOS and they can charge me double.

I wonder if someone from expo is aware of this discussion, being a "closed" issue. Maybe there is a better place where we can voice our requests? Does someone have a link?

**Comment by iainheng** [comment]
This 504 Gateway Time-out issue is still happening from time to time in 2022 without any proper error message indicating the actual problem.

**Comment by augustoarnold13** [comment]
Why is this closed if this is still happening ?

**Comment by kevgrig** [comment]
If someone wants to start a little business, you can build a large, reliable notification service that is based on a subscription fee, then add a comment here and I think a lot of people will buy it. If it really takes off, then you can sell it to Expo :)

**Comment by Codelica** [comment]
Well there is OneSignal, Twilio, etc.  But I'm hoping "EAS Notify" fits your description and is running soon.

> EAS Notify, an upcoming iteration of Expo's push notification service, will be a part of EAS's pricing plans.

**Comment by kevgrig** [comment]
> EAS Notify, an upcoming iteration of Expo's push notification service, will be a part of EAS's pricing plans.

That's great! They are building out a more reliable alternative. Here's the source of that quote: https://docs.expo.dev/push-notifications/faq/
