### ISSUE TITLE
AdSupportIOS doesn't work

### ISSUE THREAD

**Issue by AdamPD** [expo/expo#649]
AdSupportIOS throws an exception when being used.  For example:

```
AdSupportIOS.getAdvertisingId((deviceId) => {
    console.log(deviceId);
}, () => {
    console.warn("Advertising ID could not be retrieved");
});
```

The error thrown is:

```TypeError: undefined is not an object (evaluating 'AdSupport.getAdvertisingId')```

The issue seems to be that AdSupport is not in `NativeModules` (dumping `require("NativeModules")` to the console confirms this), hence the undefined error.

This is part of the base react-native so I would expect this to work.

**Comment by AdamPD** [comment]
Looks like the issue is it's not linked as described in the comment here:

https://github.com/expo/expo/blob/master/ios/versioned-react-native/ABI20_0_0/Libraries/AdSupport/AdSupportIOS.js#L17

This appears to be the issue:

https://github.com/facebook/react-native/issues/2444

Since Segment seems to use the IDFA (as described by https://docs.expo.io/versions/latest/guides/building-standalone-apps.html#6-submit-it-to-the-appropriate-store), there doesn't seem to be any reason this couldn't be linked by default.

**Comment by jimmylee** [comment]
As mentioned by other team members before, we probably will not expose the IDFA because Apple carefully checks how it is used since the information is sensitive, so if you want it you may have to detach.

Did I understand what you are suggesting? Let me know if I missed the point.

**Comment by terribleben** [comment]
Going to close this for now - let me know if I should reopen.
