### ISSUE TITLE
Video component definition somehow throws an error in propTypes

### ISSUE THREAD

**Issue by Arlen22** [expo/expo#6494]
The expo video component does not seem to work properly with the React type system. This is an example render function. The as function forces an error if the argument does not match the specified type instead of propagating to the intellisense around it. 

```ts
  function as<T>(obj: T): T { return obj; };
  return createElement(as<ComponentClass<VideoProps>>(Video), {});
```

This gives the following error underlining `Video`. 

```txt
Argument of type 'typeof Video' is not assignable to parameter of type 'ComponentClass<VideoProps, any>'.
  Types of property 'propTypes' are incompatible.
    Type '{ hitSlop?: Validator<Insets>; onLayout?: Validator<(event: LayoutChangeEvent) => void>; pointerEvents?: Validator<"auto" | "none" | "box-none" | "box-only">; removeClippedSubviews?: Validator<...>; ... 74 more ...; rotation: Requireable<...>; }' is not assignable to type 'WeakValidationMap<VideoProps>'.
      Types of property 'source' are incompatible.
        Type 'Requireable<number | InferProps<{ uri: Requireable<string>; overrideFileExtensionAndroid: Requireable<string>; }>>' is not assignable to type 'Validator<PlaybackSource>'.
          Types of property '[nominalTypeHack]' are incompatible.
            Type '{ type: number | InferProps<{ uri: Requireable<string>; overrideFileExtensionAndroid: Requireable<string>; }>; }' is not assignable to type '{ type: PlaybackSource; }'.
              Types of property 'type' are incompatible.
                Type 'number | InferProps<{ uri: Requireable<string>; overrideFileExtensionAndroid: Requireable<string>; }>' is not assignable to type 'PlaybackSource'.
                  Type 'InferProps<{ uri: Requireable<string>; overrideFileExtensionAndroid: Requireable<string>; }>' is not assignable to type 'PlaybackSource'.
                    Type 'InferProps<{ uri: Requireable<string>; overrideFileExtensionAndroid: Requireable<string>; }>' is not assignable to type '{ uri: string; overrideFileExtensionAndroid?: string; headers?: { [fieldName: string]: string; }; }'.
                      Property 'uri' is optional in type 'InferProps<{ uri: Requireable<string>; overrideFileExtensionAndroid: Requireable<string>; }>' but required in type '{ uri: string; overrideFileExtensionAndroid?: string; headers?: { [fieldName: string]: string; }; }'.ts(2345)
```

```txt
  Expo CLI 3.9.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.13 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.9.1
```

**Comment by Arlen22** [comment]
So that error is due to https://github.com/facebook/prop-types/issues/306, but once I fixed that, then it gave me a second error, which is in this module. 

```txt
Argument of type 'typeof Video' is not assignable to parameter of type 'ComponentClass<VideoProps, any>'.
  Types of property 'propTypes' are incompatible.
    Type '{ hitSlop?: Validator<Insets>; onLayout?: Validator<(event: LayoutChangeEvent) => void>; pointerEvents?: Validator<"auto" | "none" | "box-none" | "box-only">; removeClippedSubviews?: Validator<...>; ... 73 more ...; rotation: Requireable<...>; }' is not assignable to type 'WeakValidationMap<VideoProps>'.
      Types of property 'posterStyle' are incompatible.
        Type 'Validator<StyleProp<ViewStyle>>' is not assignable to type 'Validator<StyleProp<ImageStyle>>'.
          Type 'StyleProp<ViewStyle>' is not assignable to type 'StyleProp<ImageStyle>'.
            Type 'ViewStyle' is not assignable to type 'StyleProp<ImageStyle>'.
              Type 'ViewStyle' is not assignable to type 'ImageStyle'.
                Types of property 'overflow' are incompatible.
                  Type '"visible" | "hidden" | "scroll"' is not assignable to type '"visible" | "hidden"'.
                    Type '"scroll"' is not assignable to type '"visible" | "hidden"'. ts(2345)
```

**Comment by Arlen22** [comment]
After fixing that with a PropTypes.any, it gave me this error.

```txt
Argument of type 'typeof Video' is not assignable to parameter of type 'ComponentClass<VideoProps, any>'.
  Types of property 'propTypes' are incompatible.
    Type '{ hitSlop?: Validator<Insets>; onLayout?: Validator<(event: LayoutChangeEvent) => void>; pointerEvents?: Validator<"auto" | "none" | "box-none" | "box-only">; removeClippedSubviews?: Validator<...>; ... 73 more ...; rotation: Requireable<...>; }' is not assignable to type 'WeakValidationMap<VideoProps>'.
      Types of property 'resizeMode' are incompatible.
        Type 'Requireable<string>' is not assignable to type 'Validator<"cover" | "contain" | "stretch" | ResizeMode>'.
          Types of property '[nominalTypeHack]' are incompatible.
            Type '{ type: string; }' is not assignable to type '{ type: "cover" | "contain" | "stretch" | ResizeMode; }'.
              Types of property 'type' are incompatible.
                Type 'string' is not assignable to type '"cover" | "contain" | "stretch" | ResizeMode'. ts(2345)
```

I fixed it with `as React.Requirable<any>` and there were no more errors.

**Comment by Arlen22** [comment]
If I change the `propTypes` field declaration to `static propTypes: React.WeakValidationMap<VideoProps> = {`, it gives me a helpful error if anything doesn't match up. That's what TypeScript is for by the way. To make sure everything is strongly interconnected and any part out of alignment will throw an error.

**Comment by cruzach** [comment]
Hey @Arlen22 , could you please fill out the full github issue template? It will go a long way in helping get this issue diagnosed and solved as fast as possible

**Comment by Arlen22** [comment]
Nevermind the first one, which needs a lot of work that I already did and discovered that prop-types is the culprit. The other two are simple type fixes which should be obvious within the project itself simply by changing `static propTypes = {` to `static propTypes: React.WeakValidationMap<VideoProps> = {`. 

https://github.com/expo/expo/blob/fdc73faf86bc7eb56c4123bafbba7161e6c2c0f1/packages/expo-av/src/Video.tsx#L116

This needs to be `ImagePropTypes.style` which isn't a thing, so we need `PropTypes.any` instead.

https://github.com/expo/expo/blob/fdc73faf86bc7eb56c4123bafbba7161e6c2c0f1/packages/expo-av/src/Video.tsx#L129

This needs to be a proper string enum `resizeMode: PropTypes.oneOf(["contain", "cover", "stretch"]),`

**Comment by anton-sharpdev** [comment]
Hi, I have a warning about `posterStyle` prop:
<img width="353" alt="Снимок экрана 2019-12-18 в 11 08 28" src="https://user-images.githubusercontent.com/30721662/71060443-4c24c080-2187-11ea-92c3-fa077a9b9a02.png">
and code of Video usage:
```
<Video
   source={require('../../../../../assets/truck_loading.mp4')}
   posterSource={require('../../../../../assets/truck_loading.gif')}
   resizeMode={Video.RESIZE_MODE_CONTAIN}
   shouldPlay
   isLooping
   isMuted
   usePoster
   style={styles.video}
   posterStyle={styles.poster}
   onError={() => this.setState({ videoNotLoaded: true })}
/>
```
Poster is used for situation when video cannot be loaded on Android (it's working properly on iOS, but almost always failed to load on Android because codecs errors)
Hope this warning will help you to understand what went wrong

**Comment by omerts** [comment]
I am also getting @anton-sharpdev error, seems like posterStyle is not really working

**Comment by IjzerenHein** [comment]
@anton-chikunov @omerts I've submitted a PR for the `posterStyle` fix. This happened to be only a warning about an invalid prop being passed to the native code. The poster itself and its style have always worked.

**Comment by IjzerenHein** [comment]
@Arlen22 I've had a closer look at all the issues described here and it seems they have all been fixed.

- Prop-types have been removed which should fix almost all the prop-type issues that you were having, see #8679
- The posterStyle and resizeMode props have also been updated

The VideoProps types are now quite clean, you can review them here:
https://github.com/expo/expo/blob/master/packages/expo-av/src/Video.types.ts

I believe all issues have been resolved, let us know if we can close this issue? Regards

**Comment by IjzerenHein** [comment]
Closing this as all reported issues have been fixed. Feel free to reopen with additional information if the problem still exists.
