### ISSUE TITLE
SDK36: cannot print fetch response due to 'value.hasOwnPropery is not a function'

### ISSUE THREAD

**Issue by Egizas** [expo/expo#6496]
## 🐛 Bug Report
After upgrading to SDK36 I started getting `value.hasOwnProperty` is not a function on console.log line.

![image](https://user-images.githubusercontent.com/15939884/70664688-2d946600-1c6b-11ea-991e-83b1fc594b94.png)

on the console.log line after the fetch response is returned.

### Environment

SDK36

expo diagnostics:
```
  Expo CLI 3.11.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.0 - C:\Users\egidi\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4443003
```

### Steps to Reproduce
Fetch any json, and print the response before it is converted to json. If I comment the console.log line, all is working.
```
    fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(response => {
        console.log(response); // <--This is the line thats started causing the issue
        return response.json();
      })
      .then(json => console.log(json));
```

### Expected Behavior
No error

### Actual Behavior

![image](https://user-images.githubusercontent.com/15939884/70656459-68da6900-1c5a-11ea-9f5d-45e7f7ad7f76.png)

### Reproducible Demo
I could not reproduce it in snack, but marked the line which causes issue in my local env.
https://snack.expo.io/@egizas/8dd609

**Comment by cruzach** [comment]
I'm not sure why this happens, but a workaround is to simply `JSON.stringify(response)`, and no error is thrown

**Comment by cruzach** [comment]
Related to this- https://github.com/expo/expo/issues/3348 same issue

I'm not sure this is a bug with Expo @Egizas

**Comment by Egizas** [comment]
Most likely with react native 0.61.

This did not work:
`console.log(JSON.stringify(response));`

but this did work as a workaround:
`console.log('Test', JSON.stringify(response));`

Thanks @cruzach

**Comment by rodrigorm** [comment]
Hey guys, I was going to open the same issue and found this and using the `JSON.stringify` solved my problem. I believe the only issue here is the error message is to crypt and is not easy to detect when all the stack trace points to internal and not a single point of our code.

I think I found the code which cause the error provided on issue: https://github.com/expo/expo/blob/b91f886f5006959a9e30db505d333a31069c1fbd/packages/expo/src/logs/format/ReactNodeFormatter.ts#L10

Did you guys will merge an PR which fix this?

**Comment by senda-dev** [comment]
Same problem here using fetch without wrap the response with JSON.stringify. SDK 39...

**Comment by krunalc** [comment]
Any fix on this? I'm still getting same error in my code.
