### ISSUE TITLE
After upgrading from expo 33 to 35 I got error only in IOS , "Native module cannot be null"

### ISSUE THREAD

**Issue by rosnaib11** [expo/expo#6499]
I saw a lot of question asking similar to this but I don't know which libraries causing the error. Its been a while since I tried running my app on IOS, I already installed a lot of libraries so I can't trace back which module/libraries are causing the error.  Before its working, in android its working fine.

"expo": "^35.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
"sdkVersion": "35.0.0",

![2019-12-11](https://user-images.githubusercontent.com/26837762/70676821-66aef380-1cc8-11ea-9cec-88ad874cba3b.jpeg)

**Comment by brentvatne** [comment]
your react-native version was not updated, notice that it says sdk 33. you should use the `expo upgrade` command to upgrade instead of trying to do it manually, it'll make it a lot easier for you

**Comment by rosnaib11** [comment]
The work around I did is I just removed all unused libraries and its working now
