### ISSUE TITLE
After publish, does Exponent run a diff on the code and only download the delta? 

### ISSUE THREAD

**Issue by Foosballfan** [expo/expo#65]
When publishing an app, the new script is downloaded to the app.
Does it only download the code changes or is it a full download every time?

**Comment by jesseruder** [comment]
No we don't use a delta right now but are planning on using a delta or something similar in the future.

**Comment by Foosballfan** [comment]
Is there a way to calculate or find the size of this download? 

I'm busy producing an app for a country with bad internet connections and so it is quite important to understand the impact of a publish.

Also, please let me know if I should be asking these questions somewhere else.

**Comment by jesseruder** [comment]
This is a fine place for questions! We're usually more responsive on http://slack.getexponent.com/ if you want to have faster conversations.

After you publish you get a url that looks like https://exp.host/@jesse/native-component-list. If you change the url to https://exp.host/@jesse/native-component-list/index.exp?sdkVersion=14.0.0 you can see the manifest. That has a field named `bundleUrl` that links to the file we download on the client.

**Comment by dikaiosune** [comment]
Hi! I'm moving this to a [feature request on Canny](https://expo.canny.io/feature-requests/p/expo-should-only-download-a-diff-after-publish) so we can track it with other enhancements we're planning. Thanks!
