### ISSUE TITLE
[docs] AsyncStorage

### ISSUE THREAD

**Issue by davidbiller** [expo/expo#6502]
import AsyncStorage from '@react-native-community/async-storage';

SDK 36 should work with this right?
Or is it safe under Expo to use AS from react-native again?

What is with external libs? the will import it with the new path?!

**Comment by cruzach** [comment]
Hi! As the [docs say](https://docs.expo.io/versions/latest/react-native/asyncstorage/), import from `react-native` for now

`import AsyncStorage from '@react-native-community/async-storage';` won't work in the managed workflow, but will work in the bare workflow
