### ISSUE TITLE
[docs] Facebook config

### ISSUE THREAD

**Issue by tafelito** [expo/expo#6505]
in the latest docs on how to setup [facebook](https://docs.expo.io/versions/latest/sdk/facebook/) in the `Facebook.initializeAsync` section it says 

> If you don't provide it, Facebook SDK will try to use appId from native app resources (which in standalone apps you would define in app.json, in Expo client are unavailable and in bare you configure yourself according to Facebook setup documentation for iOS and Android). If it fails to find one, the promise will be rejected.

when it says standalone apps, isn't that the same as bare apps, or does it mean apps build without expo? 

Also it's unclear to me if on managed workflow it's necessary or not to set the app info in the `app.json` as it used to be before

**Comment by cruzach** [comment]
> when it says standalone apps, isn't that the same as bare apps, or does it mean apps build without expo?

No, standalone apps mean managed Expo apps once they have been built with `expo build:[ios|android]` (or built with `turtle-cli`)

Bare apps you build on your own, right now, with Xcode or Android studio. 

We specify how you need to configure your app, including app.json fields, in the [Facebook API docs](https://docs.expo.io/versions/latest/sdk/facebook/#configuration). Yes, you will need to set `facebookScheme`, `facebookAppId`, `facebookDisplayName` in app.json for standalone iOS apps (any apps built with `expo build:ios`)
