### ISSUE TITLE
Using expo-crypto in test with Jest returns undefined

### ISSUE THREAD

**Issue by minhnbwork97** [expo/expo#6512]
Hi.
I was testing my app with jest and this happened.

My code: 
```js
    it('snapshot if domain is invalid', async () => {
        const secureKey = await Crypto.digestStringAsync(
            Crypto.CryptoDigestAlgorithm.SHA256,
            'abc'
        )
        console.log('secureKey: ' + secureKey)
    })
```
Result: 
![Screen Shot 2019-12-13 at 09 32 47](https://user-images.githubusercontent.com/38205529/70764911-996df000-1d8b-11ea-959b-73d39ea3c894.png)

This only happens in tests, I have no idea why. 
I tried to mock the return value of function digestStringAsync but it doesn't suit my case, I want to check if it returns the exact value I expect.

Is there anyone having the same issue?

**Comment by EvanBacon** [comment]
Similar to https://github.com/expo/expo/issues/6980#issuecomment-606863968 
Jest is simply mocking out native methods and running unit-tests against them. If you want to test the native code you'll need to run the jest tests in an environment that supports those native features. This means running your test on a simulator or device. I'd recommend looking at Detox, which we use in `apps/bare-expo` to E2E test our modules.

**Comment by ide** [comment]
You should mock out the Crypto module in your test and exclude it from the unit under test. This is for two reasons:

- Much of the Crypto implementation is in Objective-C and Java, which Jest obviously can't run in Node, speaking reasonably. So Crypto and most other modules fundamentally won't run in Jest on your computer.
- Philosophically speaking, when testing your application code, you often want to exclude the behavior of the Crypto module from the unit under test. That is, **the test should mock the Crypto module.**

For tests in which you want to run the real Crypto module in its entirety, you'll need to run the Objective-C and Java code. In short, these are end-to-end tests that run on a device.

**Comment by WolfyUK** [comment]
Create `expo-crypto.js` in your `__mocks__` directory and populate it with something like:

```js
import * as Crypto from "expo-crypto";

export function digestStringAsync(algorithm, data) { 
    return Promise.resolve(`Mocked ${data} encoded as ${algorithm}`);
}

export const CryptoDigestAlgorithm = Crypto.CryptoDigestAlgorithm;
```
