### ISSUE TITLE
Extract TaskManager and BackgroundFetch into unimodules

### ISSUE THREAD

**Issue by esamelson** [expo/expo#6516]
Partial step of #6513 

These two modules need to be extracted into unimodules while keeping the implementation and API the same as much as possible.

Some extra setup during installation will probably be necessary for these modules. We want to aim to keep this as lightweight as we possibly can. If the PR size or installation process for the modules are getting to be out of hand, please pause work and check in with someone else.

Since we expect these PRs to be somewhat larger in scope than other unimodule extractions, please be sure to structure the PRs and code in a way that makes them as easy as possible to review!

**Comment by tsapeta** [comment]
Closing this issue as it duplicates #3453. I copied the note above to that original task though.
