### ISSUE TITLE
Try out DangerJS or GitHub Actions in repo

### ISSUE THREAD

**Issue by esamelson** [expo/expo#6519]
Let's try this out and see what we think and if it helps our process! We want to err on the side of adding less than more things, and definitely don't want to add unnecessary steps to any processes (e.g. don't want to add steps that someone wasn't already doing).

**Comment by brentvatne** [comment]
I've added it for docs but I'd like to switch over to using Github Actions for it - https://github.com/expo/expo/pull/6963. Will be unblocked from this soon when we switch over our org type to the new type that supports actions.

**Comment by tsapeta** [comment]
Since we've already moved a lot to GitHub Actions this issue can be considered as closed 🙂
