### ISSUE TITLE
exponent takes aweful lot of time to start the simulator. 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#652]
And durign for that long period of time I dont get to see any logs,  except following. 

Is there a better way to figure out where lies the bottlenecks?

![image](https://user-images.githubusercontent.com/1026325/30539599-3b8004e2-9c41-11e7-878a-e8d9e0f7b32f.png)

**Comment by jimmylee** [comment]
It looks like you have a a lot warnings to resolve, is there anyway you can make sure for me your xcode, and node are at the latest versions? Could you upgrade npm to 4.6.1?

**Comment by jimmylee** [comment]
Closing this issue, once you've resolved those warnings you can bring up another.

**Comment by jpca999** [comment]
@jimmylee all these warnings are related to npm but im using yarn  which is up to date, so i dont think I need to be concerned about these warnings.
