### ISSUE TITLE
[Android] "androidNavigationBar" set as hidden stops working after first touch

### ISSUE THREAD

**Issue by bauerpl** [expo/expo#6525]
### Environment

```
Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^3.13.0 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.11.1
```

### Steps to Reproduce

I want to hide the navigation bar in Android so I'm using the following configuration (according to the documentation):

```
"androidNavigationBar": {
    "visible": false
}
```

### Expected Behavior
The navigation bar should be hidden all the time.

### Actual Behavior
My app starts with a hidden navigation bar, but it shows up after first touch interaction.

**Comment by cruzach** [comment]
Hi! Just repro'd this on my own, thanks for reporting it! Was this working for you on SDK 35, and stopped working in SDK 36? 

I just tested this on a standalone build, and the same thing happens on standalone builds

**Comment by bauerpl** [comment]
Hi @cruzach! I didn't check SDK 35, because I migrated my app directly from SDK 33 to SDK 36.

**Comment by cruzach** [comment]
Confirmed the same behavior occurs in a standalone SDK 35 app

**Comment by inglesuniversal** [comment]
sorry to report the same issue and problem. It works beautifully once you set it up inside the json file, but as soon as there is some kind of interaction, it even obstructs the bottom custom navigation icons I configure while creating the app with Expo init APPNAME. Hope this can be gone on SDK 37.

**Comment by henrikhasell** [comment]
I am experiencing the same issue in the current SDK.

**Comment by Goufix** [comment]
Same here

**Comment by simply-phil-1** [comment]
I'm needing this fix too.  Would like it backported to SDK35. (at this time, SDK36 is not an option for us -- too many problems)

**Comment by brentvatne** [comment]
@simply-phil-1 - we won’t be backporting it to sdk35. what are the problems that you have encountered in sdk36? please link to relevant issues

**Comment by inglesuniversal** [comment]
well my sincere opinion about this issue on all of us having Expo apps targeting Android phone would not be to backport it to sdk 35, since we've seen a much faster and smoother startup times of the resulting apps on both platforms... What I would kindly suggest to the EXPO team is to try to tackle and fix this bug on the upcoming release of skd 37 without touching the main benefits of the current and stable sdk
