### ISSUE TITLE
Linking : email with a plus sign in queryParams is not decoded correctly

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#6528]
### Environment
SDK35

### Steps to Reproduce

With a Linking eventListener or getInitialURL, the url is parsed using : 
```
import URL from 'url-parse';
const parsed = URL(url, /* parseQueryString */ true);
```
https://github.com/expo/expo/blob/e59f7662cbd09ed1110c155d88fe239064c47e22/packages/expo/src/Linking/Linking.ts line 110

My URL includes an email with this allowed form "x+y@xxx.com" (with a plus sign inside the email).
Decoding by url-parse is incorrect as shown by this additional test in PR https://github.com/unshiftio/url-parse/pull/186 

On https://github.com/unshiftio/url-parse/issues/187, https://github.com/lpinca suggests using a custom function to parse the query string instead of https://github.com/unshiftio/querystringify. See https://github.com/unshiftio/url-parse#usage

### Expected Behavior
URL should be correctly decoded and queryParams have { email: 'x+y@xxx.com' }

### Actual Behavior
URL is decoded but queryParams have { email: 'x y@xxx.com' }, plus sign is replaced by space by https://github.com/unshiftio/querystringify
```
function decode(input) {
  try {
    return decodeURIComponent(input.replace(/\+/g, ' '));
  } catch (e) {
    return null;
  }
}
```

### Reproducible Demo
No, sorry. Is it worth ?

**Comment by cruzach** [comment]
I'm not seeing the case where the `+` is replaced with a space, but rather that the parsed query params aren't being decoded as of SDK 35 -> see this snack https://snack.expo.io/@charliecruzan/moody-strawberries and you'll see that SDK 35 and 36 parse the query params to be `queryParams:{email:"x%2By%40xxx.com"}`

Which we should probably handle escaping for you

**Comment by lc3t35** [comment]
It's because before the parse you are using Linking.makeUrl that encodes queryParams with `queryString = qs.stringify(queryParams);`, so + is transformed with %2B.
The Url is built on server side in my case, so I don't use Linking.makeUrl. I can stringify but it is not forbidden to have a + in a mail ?
