### ISSUE TITLE
Listener registerd in addlistener is not called when selected in expo 36

### ISSUE THREAD

**Issue by Renji3** [expo/expo#6529]
### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      expo-cli: 3.11.1

Bug On Android

### Steps to Reproduce

Follow this [git](https://github.com/Renji3/expo-pushnotifications) I created. Its basicaly the updated version of the push notification snack.
In the README.md futher information are given.

### Expected Behavior

When following the snack and running it via *expo start* I expected that the notification listener was called like in previous versions, as well as like it was stated in the [Expo Documentaion](https://docs.expo.io/versions/latest/sdk/notifications/#eventsubscription).

### Actual Behavior

The notification listener was only called while the app was running but not when the notification was selected while the app was not running.

### Reproducible Demo

As stated above here is the Github repo I created regarding the bug.
https://github.com/Renji3/expo-pushnotifications

**Comment by cruzach** [comment]
Hi! I just tested this on an Android pixel, and selected the notification from the notification center triggered the listener. Specifically, using the snack in the docs, the "data" was populated with the new data present in the notification

Can you try this again using the [snack example](https://snack.expo.io/@charliecruzan/pushnotifications36) and [push notification tool](https://expo.io/notifications)? If it doesn't work, try to provide as much info as possible

**Comment by Renji3** [comment]
Running this snack the same error occures.

If I run the snack while sending push notifications the Data can be received.
If I close Expo including the snack, and then send a push notification. The push notification is received trough expo like it should
clicking on that notification however does only open the App, but does not trigger the listener.
Neither the Origin nor the data variable is set in the App

**Comment by aeshashah** [comment]
> Running this snack the same error occures.
> 
> If I run the snack while sending push notifications the Data can be received.
> If I close Expo including the snack, and then send a push notification. The push notification is received trough expo like it should
> clicking on that notification however does only open the App, but does not trigger the listener.
> Neither the Origin nor the data variable is set in the App
> 
> This occures on an Honor 10

Hi @Renji3 , did you find any workaround for this issue ? We are having same issue on Android , using expo 36.

**Comment by Renji3** [comment]
@aeshashah sadly not so far. This is the thing stoping us from upgrading to expo36.
The thing is that this bug seems to only come up sometimes. I had cases where it worked on the same App and phone while other moments it did create this given bug.

I'm not sure about the possibility of detaching from expo but at this point this is nothing we want to do yet either.

**Comment by aeshashah** [comment]
> @aeshashah sadly not so far. This is the thing stoping us from upgrading to expo36.
> The thing is that this bug seems to only come up sometimes. I had cases where it worked on the same App and phone while other moments it did create this given bug.
> 
> I'm not sure about the possibility of detaching from expo but at this point this is nothing we want to do yet either.

**Comment by aeshashah** [comment]
Thanks @Renji3. Is it working on any earlier expo version ? Is there a expo version for which it works on android and iOS both ? For us , with expo 36 it works on iOS. But on Android it doesn’t not when app is closed and launched by tapping notification , it doesn’t trigger handle notification.

**Comment by greedygreen** [comment]
@aeshashah it works with expo 35. I had the same issue and downgrading from expo 36 to 35 fixed the issue.

**Comment by aeshashah** [comment]
> @aeshashah it works with expo 35. I had the same issue and downgrading from expo 36 to 35 worked on both iOS and Android.

@greedygreen  Thanks . We will downgrade to expo 35 and try it out.

**Comment by greedygreen** [comment]
@aeshashah That's right. We receive the push notification while the app is closed, once we tap on the notification, the app is opened and the function passed to 'Notifications.addListener()' is called and navigates the user to the corresponding screen.

**Comment by aeshashah** [comment]
@greedygreen Thank you so much for confirming the steps. We will downgrade to expo 35 , hopefully that will fix the issue for our app.

**Comment by Renji3** [comment]
I can confirm what @greedygreen said as well.
We were on 35 already and everything worked fine. Upgrading to 36 caused the problem.
Downgrading again fixed it again.

**Comment by levbao** [comment]
Hi @aeshashah downgraded back to 35 and it's fixed.  Thank you guys.

**Comment by aeshashah** [comment]
@Renji3 @greedygreen thank you so much guys for your help. We also downgraded to expo 35 and it works on both iPhone and android.

**Comment by aeshashah** [comment]
> Hi @aeshashah downgraded back to 35 and it's fixed. Thank you guys.

Awesome !

**Comment by Renji3** [comment]
I sill hope this is reviewed by expo in the near futuer as this makes upgrading to version 36 basicaly impossible

**Comment by aeshashah** [comment]
> I sill hope this is reviewed by expo in the near futuer as this makes upgrading to version 36 basicaly impossible

yes , hopefully this open bug will get resolved i  future releases.

**Comment by cruzach** [comment]
I've tested this and still can't exhibit the behavior of the listener not firing when opening the app from a notification. Here are the steps:
- run the code from the snack example I linked earlier locally with `expo start`, get the push token
- kill the expo app
- send push notification using https://expo.io/notifications and the retrieved push token, with `{"data":"goes here"}` in the JSON data field
- tap the notification from the device's notification tray
- app opens and I see `Data: {"data":"goes here"}`

**Comment by Renji3** [comment]
what phone are you using @cruzach ?

**Comment by cruzach** [comment]
Pixel 2, running Android 9

**Comment by RoromiDev** [comment]
Same issue with xiaomi mi8 (works fine on iOS)

**Comment by cruzach** [comment]
Tested on a OnePlus 6T as well, and can't reproduce the issue 🙁

**Comment by aonamrata** [comment]
Hey @Renji3 Did you change anything other than downgrading?
We have the issue with IOS and expo 35. But we are mounting our handler in global, not on `componentDidMount` but not sure if that is the reason as it works when the app is in foreground or minimised

**Comment by Tythiras** [comment]
I'm having the same problem as mentioned, but it only happens while using the builded - non managed application. Still android so installed with apk. This may be why you are having trouble reproducing.

**Comment by maxired** [comment]
@cruzach I do confirm the issue, using android 9 and a OnePlus 3T.

When using the snack, with expo and the expo snack closed, when I open a notification,
the data is not displayed in the snack,

**Comment by cruzach** [comment]
@maxired can you share a screen recording of doing these steps:
- run the code from the snack example I linked earlier locally with expo start, get the push token
- kill the expo app
- send push notification using https://expo.io/notifications and the retrieved push token, with {"data":"goes here"} in the JSON data field
- tap the notification from the device's notification tray
- app opens and I see Data: {"data":"goes here"}

I've done this on multiple android devices and have not been able to reproduce the behavior

**Comment by maxired** [comment]
@crubier there you go https://expo6529.now.sh/repro-expo-6529.mp4

**Comment by chuckwood** [comment]
I had the same issue with the addListener callback not being triggered only in Expo SDK v36 (but working in v35).

I was able to fix my issue by changing the syntax to the following:

**Notifications.addListener(notification => this.handleNotification(notification));**

**Comment by cruzach** [comment]
I'd also make sure you are registering the listener in the root component of your app

**Comment by empregourgente-4** [comment]
I had the same issue on SDK 36. Please fix this serious issue.

Thank you!

**Comment by Tythiras** [comment]
I just wanted to add my experience about this issue.
I have the same issue with handling notification clicks from closed app on android.
The thing is that the issue is only about 10% of the time while running the app through expo. But after having installed the app through builded apk it happens consistently.
Phone: Android 9, pocophone f1

**Comment by maxired** [comment]
@tythiras does it seems to you that the application is launching twice ? For exemple do you see your splashscreen blinking ?

**Comment by Tythiras** [comment]
@maxired Actually yes. There is a white screen (splash screen I think) in the start, short blink, a bit more white screen. And then the app is loaded and my activity indicator shown. The blink isn't happening on iPhone, and on iPhone my notifications are working perfectly.

**Comment by Renji3** [comment]
The solution of @chuckwood is not helpfull. In my case thats the syntax I'm using all along.
Putting it at the top level as you mentioned @cruzach is not working either. I'm running: 

`  Notifications.addListener( notification => { console.log("Notification", notification) });`

at the beginning of constructor in the root Component.
There is not notification reaching the function. The Console log is never fired.

Could you please open this again and give it more attention? This makes using version 36, as well as the new version 37 (where the problem still exists unusable).
This is becoming a bigger problems as Apple soon will get more strict in regards to UIWebView used in expo 35 and lower.

**Comment by cruzach** [comment]
@Renji3 the issue is already open, but a reliable reproducible example is still needed so if you can provide one please do!

**Comment by Renji3** [comment]
https://github.com/Renji3/expo37notificationBug/blob/master/README.md
Here is again a git with the exact error 
The code was directly coppied from your snack: https://snack.expo.io/@charliecruzan/pushnotifications36,
After initializing the folder with expo init beforehand.
The only thing modified is renaming the "AppContainer" to App.js to match the name of the initial App.js

I added a video reproducing the bug and differentiating bewteen the state where the app was not closed beforehand and the state where the app was closed.
It can be seen that if you don't close the app (second time i send notifications) it works, but if it was closed (first and third time) it doesn't work.
I also added step by step instructions again to reproduce.

**Comment by maxired** [comment]
@cruzach to me the source of the issue is really low level, and maybe, it does not have anything to do with Notification.

As I said before, it seems that the Android activity is restarted.
One of the causes might be a configuration change: https://developer.android.com/reference/android/app/Activity.html#configuration-changes . I don't know anything about how it is managed in React-native and expo, but I would love to have opinions from someone familiar with the subject.

If not a configuration change, then it might be linked to a direct call to `startActivity`.
There is not much in Expo + React Native, so might be a good place to start the investigation.

WDYT ?
Any suggestion on how to proceed ?

**Comment by adrianloh128** [comment]
doesn't work on sdk 37 as well. Can anyone confirm with this?

**Comment by adrianloh128** [comment]
@Renji3 
i tried ur apps on github... the listener works when i close the 'pushnotification36' app but not the expo app... or it is supposed to be like this?

**Comment by adrianloh128** [comment]
downgraded from 36 to 35 doesn't work for me as well.. weird

**Comment by adrianloh128** [comment]
@renji3 does your code in the post work in sdk 35? apparently ur coding not working on my sdk 35

**Comment by adrianloh128** [comment]
@Renji3 can i have ur package.json config file for the sdk 35?

**Comment by cruzach** [comment]
@Renji3 running your repo you shared above locally with `expo start` and using the android Expo Client version 2.15.1, I am still seeing the correct behavior whether I open a notification with the Expo app running in the background, or completely closed. Tested on both a pixel and a oneplus

**Comment by danilsk** [comment]
SDK 37 - same problem both for apk's and in Android Expo Client 2.15.1. The listener never fires even for an empty project.  

It does work most of the time when the Expo Client is in the background and the actual app is closed though.

**Comment by Renji3** [comment]
@adrianloh128  I created the app with expo init in this case so I don't have an expo35 version package.json of this git.

@cruzach I can only talk for my Honor 10 using Android 9 and expo client version 2.15.0 installed on the phone. Obviously other seem to have the issues as well. So if you won't be able to reproduce this maybe you could assign another developer to this issue if one is available.

**Comment by danilsk** [comment]
Xiaomi Mi 9 SE (Android 10) - neither SDK 35, 36 nor 37 have the expected behavior of firing an event on the next tick after a closed app gets opened by tapping on the notification. Both for APK and the Expo Client. 

Also, tested with this https://snack.expo.io/@charliecruzan/pushnotifications36 - same problem.

**Comment by adrianloh128** [comment]
@Renji3 i created with expo init too but it has... but there is package.json in your original post's link. 
also does the listener work on expo client or only apk?

**Comment by danilsk** [comment]
Ok, so in my case the issue was caused by Android 10's dark\night mode. Likely has to do with [#6825](https://github.com/expo/expo/pull/6825). That also explains why only some people encountered it. 

The fix is to set userInterfaceStyle to "automatic", it also removes black flashing.

**Comment by Tythiras** [comment]
> Ok, so in my case the issue was caused by Android 10's dark\night mode. Likely has to do with [#6825](https://github.com/expo/expo/pull/6825). That also explains why only some people encountered it.
> 
> The fix is to set userInterfaceStyle to "automatic", it also removes black flashing.

I can confirm dark mode was causing this on my mobile. Adding expo.userInterfaceStyle, "automatic". Under app.json fixed it, and removed the double boot of the app on startup.
Well found!

**Comment by aonamrata** [comment]
Is there a way I can get it working for expo:35 ? I am not sure we are ready to update to version 37.

**Comment by adrianloh128** [comment]
@aonamrata it is working in expo 35

**Comment by maxired** [comment]
@danilsk , @Tythiras  , whoo, that's is great news.
Unfortunately, I don't have dark mode activated, so that is not a direct solution for me ;-)

How did you get to discover dark mode was involved ?

**Comment by adrianloh128** [comment]
@danilsk  @Tythiras good job, will try to upgrade my expo later. but when i try to insert in app.json, it shows me this error 
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v35.0.0/workflow/configuration/
 • should NOT have additional property 'userInterfaceStyle'.

**Comment by maxired** [comment]
> @danilsk , @Tythiras , whoo, that's is great news.
> Unfortunately, I don't have dark mode activated, so that is not a direct solution for me ;-)
> 
> How did you get to discover dark mode was involved ?

Ok my bad. Even If don't use night mode, I set `userInterfaceStyle` to `automatic` in app.json, and it seems to do the job.
thanks a lot @danilsk  and @Tythiras.

@adrianloh128 from what I understand, in SDK35, `userInterfaceStyle`  is only for iOS, so I guess you would have to upgrade.

@cruzach , now that we have more information about the bug, that is is indeed linked to a restart of the activity and the notification not being kept, I guess you will have enough info to create a new issue ?

**Comment by adrianloh128** [comment]
i can confirm the solution by @danilsk works in expo 37.. good job on the solution!

**Comment by Renji3** [comment]
thanks @danilsk I can also confirm that this solved the problem and makes this finally usable.
This still should be looked into further by the expo team as the dark mode should not be the reason the notifications do not work.

Big thanks to @all in finding the problem

**Comment by cruzach** [comment]
Yes I was able to repro with Dark mode enabled on an Android 10 device, thanks for the info! Will investigate

**Comment by ShaggyKris** [comment]
Hi all,

Trying to get this to work in Expo 37. Here's the thing: it DID work at one point, but now it does not. The code is the following (in App.js created by expo init):

```
const registerForPushNotificationsAsync = async () => {
        if (Constants.isDevice) {
            const { status: existingStatus } = await Permissions.getAsync(
                Permissions.NOTIFICATIONS
            );
            let finalStatus = existingStatus;
            if (existingStatus !== "granted") {
                const { status } = await Permissions.askAsync(
                    Permissions.NOTIFICATIONS
                );
                finalStatus = status;
            }
            if (finalStatus !== "granted") {
                alert("Failed to get push token for push notification!");
                return;
            }
            await Notifications.setBadgeNumberAsync(0);
        } else {
            alert("Must use physical device for Push Notifications");
        }

        if (Platform.OS === "android") {
            await Notifications.createChannelAndroidAsync("default", {
                name: "default",
                sound: true,
                priority: "max",
                vibrate: [0, 250, 250, 250],
            });
        }
    };

    function _handleNotification(notification) {
        Vibration.vibrate();
        Alert.alert("Notification Received", "Notification");
        console.log(notification);
        // async function updateBadgeNumber() {
        //     console.log("Getting badge number");
        //     const numItems = await Notifications.getBadgeNumberAsync();
        //     console.log("Num notifications: ", numItems);
        //     const breakpoint = "";
        // }
        // updateBadgeNumber();
    }

    // Load any resources or data that we need prior to rendering the app
    React.useEffect(() => {
        async function loadResourcesAndDataAsync() {
            try {
                SplashScreen.preventAutoHide();

                // Load our initial navigation state
                setInitialNavigationState(await getInitialState());

                // Load fonts
                await Font.loadAsync({
                    ...Ionicons.font,
                    "space-mono": require("./assets/fonts/SpaceMono-Regular.ttf"),
                });
                await registerForPushNotificationsAsync();
            } catch (e) {
                // We might want to provide this error information to an error reporting service
                console.warn(e);
            } finally {
                Notifications.addListener((notification) => {
                    console.log("HEY I GOT SOMETHING");
                    _handleNotification(notification);
                });
                setLoadingComplete(true);
                SplashScreen.hide();
            }
        }

        loadResourcesAndDataAsync();
    }, []);
```

Seeing as this is an iPhone 5 that I'm testing on, Dark Mode isn't an issue. However, I did try setting "userInterfaceStyle" : "automatic", and this did not change anything for me.

**Comment by danilsk** [comment]
@ShaggyKris this issue is unrelated 
See https://docs.expo.io/workflow/configuration/ - iosDisplayInForeground
