### ISSUE TITLE
Expo SDK 36 - wontWeight: '100', '200', '300', '400', '500', '600', '700', '800', '900' broken

### ISSUE THREAD

**Issue by Pikerstrow** [expo/expo#6532]
After upgrading project to SDK 36 noticed that fontWeight in numeric values doesn't make any difference. On SDK 33 everything worked fine...
Font Family - Noto Sans

**Comment by cruzach** [comment]
Just to confirm the behavior I saw- this bug is Android-only right? On iOS, the following code works fine:
```
          <Text style={{ fontWeight: "400" }}> This should be bold</Text>
          <Text style={{ fontWeight: "600" }}> This should be bolder</Text>
          <Text style={{ fontWeight: "800" }}> This should be boldest</Text>
```

**Comment by cruzach** [comment]
Actually, in terms of android, looks like this is an upstream React Native pain, not a bug with Expo - https://react-native.canny.io/feature-requests/p/fontweight-300-not-working-on-android

**Comment by Pikerstrow** [comment]
But this works perfectly on sdk 33. I downgrade sdk version back from 36 and everythng is fine again

**Comment by cruzach** [comment]
Can you share a snack that reproduces that? https://snack.expo.io/
you can set the SDK in the bottom-right corner

**Comment by aleqsio** [comment]
I'm experiencing the same issue, running on android 9 with the expo client 2.14.0.
https://snack.expo.io/@aleqsio/expo-font-weight
The issue doesn't occur on iOS. 
Let me know if i can provide more details.

(this is a comparison image of the reproducible example in two different sdk versions running on the same physical device, the two screenshots were combined in graphics software)
![image](https://user-images.githubusercontent.com/5597580/73089243-22715e80-3ed6-11ea-93f9-1f9703e16d83.png)
