### ISSUE TITLE
Not compiling on file change, with expo start

### ISSUE THREAD

**Issue by xiCO2k** [expo/expo#6535]
### Environment

 Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.3.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.1

### Steps to Reproduce

executed `expo start` and after a code change the app did not did the fast reload, even after CMD+R on iOS Simulator my change was not there. Any ideia what should be?

**Comment by cruzach** [comment]
I just tested this in the same environment, and didn't see this issue. The fact that you're running CMD+R and reloading and it's still not showing changes tells me that maybe you haven't saved the file, or at least the right file? 

Might be worth trying this on a totally blank project

**Comment by xiCO2k** [comment]
double checked to be sure it was saved. will create a new project and check if it still happens. Thansk

**Comment by xiCO2k** [comment]
on a brand new app works great. not sure why its not working on my other app. will try to figure it out

**Comment by cruzach** [comment]
I would try deleting node_modules, re-installing, clearing watchman (`watchman watch-del-all`), making sure there's no other instance of your project still running, then run `expo start -c`
