### ISSUE TITLE
[SDK 36] Problem with Intl after upgrade

### ISSUE THREAD

**Issue by Feridum** [expo/expo#6536]
## 🐛 Bug Report
Hi, I made an upgrade from SDK 35 to SDK 36 and after it I have error in Android device

<img width="333" alt="Zrzut ekranu 2019-12-16 o 16 07 23" src="https://user-images.githubusercontent.com/11918468/70918526-73f91480-201f-11ea-8aa2-67f0aff31779.png">

### Environment

Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.15.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.11 => 16.9.11
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.1

Package use for manage translations `"react-intl": "^3.2.0",`

Error only occurs in Android 
On IOS device it works

### CustomIntlProvider

```
import { IntlProvider } from 'react-intl';
import { translations } from 'i18n';

export const CustomIntlProvider: React.FC<Props> = ({ children }) => {
  const language = // from store
  const setLocale = // save to store

  useEffect(() => {
    I18nManager.allowRTL(false);

    (async () => {
      const lang = await asyncStorage.getItem(StorageItem.Lang);
      if (lang) {
        setLocale(lang);
      }
    })();
  }, [setLocale]);

  return (
    <IntlProvider locale={language} messages={translations[language]}>
      {children}
    </IntlProvider>
  );
};

```

I found this topics on github while I was trying to fix this (can be conncted with this issue)
https://github.com/formatjs/react-intl/issues/1356
https://github.com/react-native-community/jsc-android-buildscripts#international-variant

**Comment by cruzach** [comment]
Unfortunately, to make that change to your build.gradle file, you'll need to use the bare workflow

Have you tried using Expo's [Localization library](https://docs.expo.io/versions/latest/sdk/localization/)? I guess I'm not quite clear exactly what the `IntlProvider` component is doing

**Comment by Feridum** [comment]
IntlProvider is from `react-intl` library - it is react context which provides components and api for translations and formatting string, numbers, etc. It relies on Intl global object.

The whole project with this library works before the upgrade so now this is now somehow a regression. Is it possible to fix it on my side?

**Comment by cruzach** [comment]
Have you tried the solution shared at the end of that issue?

**Comment by Feridum** [comment]
I'm already using this polyfill

**Comment by cruzach** [comment]
To configure that option in build.gradle, you'll need to use the managed workflow. However, you should be able to translate and format strings/numbers/etc. in the managed workflow using the library I linked above- [here's a good article](https://flexport.engineering/internationalizing-the-transmission-react-native-mobile-app-7c90ee10ecbe) showing how to do that using the react-i18next library

**Comment by Feridum** [comment]
I saw this library but in my situation, I will have to rewrite the whole application or stay on SDK 35 where react-intl works perfectly :/. Both of these solutions are bad in the current stage of the project :(

**Comment by brentvatne** [comment]
@Feridum - can you identify precisely what change is leading to this problem? it would be helpful for us to know

**Comment by Feridum** [comment]
@brentvatne I mentioned in the original post I found an old issue on github with similar error and this leads to this repository 
https://github.com/react-native-community/jsc-android-buildscripts#international-variant 
Config for this changed in React Native 0.60 and I think this can cause a problem.

**Comment by brentvatne** [comment]
@Feridum - that's fine but when dealing with an external library (in this case, react-intl) i want to understand exactly what interface it's expecting of the expo runtime and what is not being satisfied

**Comment by ide** [comment]
The stack trace in the original post’s screenshot says there is an invalid regex. I would debug that regex to see what is actually going on so we can fix causes instead of masking symptoms.

**Comment by Feridum** [comment]
After some research I found that Intl polyfill (https://github.com/andyearnshaw/Intl.js/) causes this error and making `Intl.__disableRegExpRestore()` help me to get rid of the error. 

I still dont know why after upgrade from 35 to 36 cause this error but after fix found I think we can close it.

**Comment by cruzach** [comment]
Thanks for digging into this @Feridum 👍

**Comment by shanhuiyang** [comment]
@Feridum I meet 2 issues after upgrade the expo to 36, the 2nd one is exactly the same as you, thank you for saving my whole day.

The 2st issue I met is `ReferenceError: Can't find variable: Intl`. This should not happen because I have wrote the following code line,
```
import "intl";
```
I moved this line to the top of App.tsx then the 1st issue went away and 2nd issue comes.

**Comment by SebSchwartz** [comment]
@shanhuiyang Where did you add this?
I tried to add it in the first component but it's not working :( Still got the error

**Comment by SebSchwartz** [comment]
Found it thanks to your code @shanhuiyang.
I was missing installing: intl and expo-localization
```terminal
yarn add intl expo-localization 
```
Then in the App.tsx in the root folder:
```javascript
// Need manually add Intl polyfill for react-native app
import "intl";
import { Platform } from "react-native";

if (Platform.OS === "android") {
    // See https://github.com/expo/expo/issues/6536 for this issue.
    if (typeof (Intl as any).__disableRegExpRestore === "function") {
        (Intl as any).__disableRegExpRestore();
    }
}
import "intl/locale-data/jsonp/en";

```

**Comment by nandorojo** [comment]
@SebSchwartz Should probably change your solution to use `expo install`.

**Comment by soullivaneuh** [comment]
@SebSchwartz FYI, your hack looks to work also without expo-localization.

**Comment by katonglaksa** [comment]
Hi there, I couldn't seem to get this to work - I received an unexpected token when adding it to the top of my code.

```
import "intl";
import { Platform } from "react-native";
import "intl/locale-data/jsonp/en";

export default function App() {

  if (Platform.OS === "android") {
    // See https://github.com/expo/expo/issues/6536 for this issue.
    if (typeof (Intl as any).__disableRegExpRestore === "function") {
        (Intl as any).__disableRegExpRestore();
    }
}
  return (
    <AuthProvider>
    <StreakProvider>
      <Navigation />
    </StreakProvider>
    </AuthProvider>
  );
}
```

I could make it work by just doing this:

```

  if (Platform.OS === "android") {
    // See https://github.com/expo/expo/issues/6536 for this issue.
    Intl.__disableRegExpRestore()
  }
```

Just wanted to check if anyone could tell me if that's okay?

**Comment by samyarkd** [comment]
> @Feridum I meet 2 issues after upgrade the expo to 36, the 2nd one is exactly the same as you, thank you for saving my whole day.
> 
> ```ts
> import "intl";
> import { Platform } from "react-native";
> 
> if (Platform.OS === "android") {
>     if (typeof (Intl as any).__disableRegExpRestore === "function") {
>         (Intl as any).__disableRegExpRestore();
>     }
> }
> ```
> 
> The 1st issue I met is `ReferenceError: Can't find variable: Intl`. This should not happen because I have wrote the following code line,
> 
> ```ts
> import "intl";
> ```
> 
> I **moved this line to the top of App.tsx** then the 1st issue went away and 2nd issue comes.

what about App.js ???
