### ISSUE TITLE
Assets 2x and 3x are never loaded

### ISSUE THREAD

**Issue by mi-mazouz** [expo/expo#6539]
## 🐛 Bug Report

I tried to test my app on Ipad and I saw that assets 2 and 3x are never loaded.

I followed the structure directory mentioned in the doc like this:

- assets/
    - shape.png
    - shape@2x.png
    - shape@3x.png
- component.tsx

But the only image I can see is shape.png.

I maybe missed something...

**Comment by cruzach** [comment]
Can you provide a full repro please? otherwise it's hard to say what could be going wrong

**Comment by mi-mazouz** [comment]
@cruzach do you mean you want a repository? I'll send you it tomorrow

**Comment by mi-mazouz** [comment]
https://github.com/mi-mazouz/expo-assets-demo

iphone 5:
<img width="403" alt="Screen Shot 2019-12-18 at 9 25 10 AM" src="https://user-images.githubusercontent.com/24244248/71094209-8fc3fe00-2178-11ea-82fa-7a134281e0fe.png">

iphone 8 Plus:
<img width="399" alt="Screen Shot 2019-12-18 at 9 23 38 AM" src="https://user-images.githubusercontent.com/24244248/71094210-905c9480-2178-11ea-82dc-f3f1e6ff29d8.png">

**Comment by mi-mazouz** [comment]
@cruzach  Did you able to reproduce this issue?

**Comment by mi-mazouz** [comment]
@cruzach Can you remove needs repro label please

**Comment by cruzach** [comment]
@mi-mazouz I just tested this on a bare react native project, and got the same behavior, so I don't think this is an issue specific to Expo

You may want to double-check your implementation, and open an issue on the react native repo
