### ISSUE TITLE
Mismatched expo/react-native hash when yarn installing

### ISSUE THREAD

**Issue by jayeszee** [expo/expo#654]
![image](https://user-images.githubusercontent.com/10326244/30562774-7ac7d516-9c74-11e7-84e1-c874dc8ae969.png)

Seems like at one point or another you guys updated the tar for react-native for version expo sdk 20.0.0. This caused a hash mismatch because my local had a cached version (804b58150426c68e4da266490d43ec639d95953d) that it was writing to the yarn.lock file while my clean uncached circleci build was getting (bde7e70913e017f79afe188970adbed8c00b3858). yarn cache clean and yarn installing again fixed this issue but just wanted you guys to know that this is an issue. Maybe someone can offer some insight on what happened?

**Comment by alexeyMohnatkin** [comment]
cleaning yarn cache doesn't work for me

**Comment by ide** [comment]
Not sure what happened. Does `yarn cache clean && rm -fr node_modules yarn.lock && yarn` fix things for you?

**Comment by terribleben** [comment]
Seeing more reports of this in Slack, @ide can you help find a way to unblock people?

**Comment by terribleben** [comment]
It looks like [this proposed solution](https://forums.expo.io/t/yarn-1-0-2-fetch-succeeded-for-undefined-however-extracting-hash-x-did-not-match-requested-hash-y/3239/2) is working for some people.

**Comment by tiaaaa123** [comment]
@terribleben I tried the solution from the expo forums. Does not work when my CI user `yarn`.
I can use npm for now, but it would be great to fix the hash :)

**Comment by ide** [comment]
If you run `yarn cache clean` and delete your `yarn.lock` file does that fix things?

**Comment by jayeszee** [comment]
@ide Sorry for the late reply, seems like deleting yarn.lock, rm -rf node_modules, and yarn cache clean in combination helped me get through this problem.

**Comment by ide** [comment]
Going to close this out. Fix is to clear your caches (see above) and reinstall.
