### ISSUE TITLE
ExpoKit Android SplashScreen not work.

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo#6540]
### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.2.0 => 3.2.0 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: 4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.1

ExpoKit

### Steps to Reproduce
ExpoKit Project

use SplashScreen.preventAutoHide() or  SplashScreen.hide()

### Expected Behavior

work

### Actual Behavior

not work

### Reproducible Demo
https://docs.expo.io/versions/latest/sdk/splash-screen/
Example without AppLoading

My find preventAutoHide or EXSplashScreen only ios ExpoKit File exists
expo build android is work. but expoKit android have this problem

**Comment by rxhivzero** [comment]
https://github.com/expo/expo/issues/6014

**Comment by OscarYuen** [comment]
I got the same issue. It happens in ExpoKit SDK 36.
Both Android & iOS work fine in Expokit SDK 35.
But in ExpoKit SDK 36, the android version would give a white blank screen between native splash screen and the actual home screen.
The splash screen disappear before the App.js is mounted.

**Comment by cruzach** [comment]
Hi! We've deprecated support for Expokit recently with the release of SDK 38 in favor of the bare workflow. We've also extracted out SplashScreen to its own module- https://github.com/expo/expo/tree/master/packages/expo-splash-screen#expo-splash-screen. If you run into issues with SplashScreen in the bare workflow, please open up a new issue with a reproducible demo so we can investigate
