### ISSUE TITLE
RedBox covered by notch on Android

### ISSUE THREAD

**Issue by SimenB** [expo/expo#6542]
### Environment

```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.3 - /var/folders/58/x7ryp52n7mxbtkld6lr0bqg00000gn/T/yarn--1576584425967-0.694206423334043/node
      Yarn: 1.21.1 - /var/folders/58/x7ryp52n7mxbtkld6lr0bqg00000gn/T/yarn--1576584425967-0.694206423334043/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 2.20.0
```

Android client

### Steps to Reproduce

On an Android device with a notch (I'm using Pixel 3 XL), just add the following snippet: `console.error('blahblah')`

### Expected Behavior

For redbox not to be covered by notch

### Actual Behavior

It is covered. For some reason yellowbox works

Sorry about the _incredibly_ low quality on the pictures - taking a screenshot will remove the notch and I don't have any other camera in my apartment 😅 

![Photo on 17-12-2019 at 13 02](https://user-images.githubusercontent.com/1404810/70994502-b299d800-20ce-11ea-95be-c038360bd189.jpg)
![Photo on 17-12-2019 at 13 06](https://user-images.githubusercontent.com/1404810/70994505-b299d800-20ce-11ea-8cd1-efb96967fd51.jpg)

### Reproducible Demo

For whatever reason, I don't get any redbox at all when using a snack... It should be a matter of just doing `console.error` at whatever place in the code, though

**Comment by byCedric** [comment]
I have the same, it only happens on Android for some reason. Tested on an iPhone X, both in simulator and on real device, they are fine. Also happening for `expo@36.0.1`.
