### ISSUE TITLE
readAsStringAsync doesn't support reading some files as binary

### ISSUE THREAD

**Issue by ADustyOldMuffin** [expo/expo#6554]
Recently when trying to use `FileSystem.readAsStringAsync(fileUri)` it returns nothing as the file was m4a on android. The documentation says it will read in as raw binary. I'm not sure if I'm doing something wrong, or if the documentation is not correct.

**Comment by cruzach** [comment]
It would help if you provide a repro, so if you are doing something wrong we can see 😄

**Comment by ADustyOldMuffin** [comment]
```
const recording = new Audio.Recording();
try{
  await recording.prepareToRecordAsync(Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY);
  await recording.startAsync();
  //record for 5 seconds
  await recording.stopAndUnloadAsync();
  FileSystem.readAsStringAsync(recording.getURI()) //<- returns nothing
}
```
This may not be exactly what I had but that was the general gist. If you record using the high quality option, when you plug in the URI to readAsStringAsync you would expect the raw binary data but returns nothing.

**Comment by ADustyOldMuffin** [comment]
It's also of note that I would also play the file back using the Audio API along with checking the stats of the file using FileSystem API to confirm that the file existed and was valid.

**Comment by OzkanAbdullahoglu** [comment]
hi, recording.getURI() does not return the fileUri. It returns an object which should be sth like this,
```
{
 modificationTime: number, 
 isDirectory: bool, 
 size: number, 
 uri: filUri,
 exists: bool,
}
```
just console that in see the properties. then try to read with `recording.getURI().uri`

**Comment by cruzach** [comment]
@OzkanAbdullahoglu `recording.getURI()` is returning the uri for me on SDK 36

@ADustyOldMuffin It looks like you have to set the encoding to base64 - 
```
console.log(
        await FileSystem.readAsStringAsync(recording.getURI(), {
          encoding: FileSystem.EncodingType.Base64,
        })
      );
```

**Comment by ADustyOldMuffin** [comment]
Thank you, I was having errors with the Base64 as in the documentation it says it will return Raw Binary when reading in a file with readAsStringAsync so the documentation should probably be updated. I solved my issue by using a fetch call and it handling all of the uploading of the file for me.

**Comment by cruzach** [comment]
I'm not sure what you mean- could you open up a PR with the docs update you're referring to?

**Comment by SimonHausdorf** [comment]
https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemreadasstringasyncfileuri-options

> Read the entire contents of a file as a string. Binary will be returned in raw format,
