### ISSUE TITLE
SDK36: paths between Linking.makeUrl and Linking.parse do not match

### ISSUE THREAD

**Issue by haasalex16** [expo/expo#6555]
### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.6 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.1

iOS & Android

### Steps to Reproduce

Place the following code in any component  (in the render function):
```
const link = Linking.makeUrl("MagicLink", {to: 'Home'});
console.log("Link: ", link);
const parsedLink = Linking.parse(link);
console.log("Parsed Link: ", parsedLink);
```

### Expected Behavior

Prior, on SDK35 I get the following logs:
```
Link:  exp://127.0.0.1:19000/--/MagicLink?to=Home
Parsed Link:  Object {
  "path": "MagicLink",
  "queryParams": Object {
    "to": "Home",
  },
}
```

Notice that the path passed in ('MagicLink') is the same parsed

### Actual Behavior

After upgrading to SDK36 I get the following logs:
```
Link:  exp://127.0.0.1:19000/--/MagicLink?to=Home
Parsed Link:  Object {
  "hostname": "127.0.0.1",
  "path": "--/MagicLink",
  "queryParams": Object {
    "to": "Home",
  },
  "scheme": "exp",
}
```
The parsed path is "--/MagicLink" when the passed in path is "MagicLink".  I would expect the parse function to return the same path that is initially passed into makeUrl

**Comment by pgdavidApodis** [comment]
Bug confirmed !

**Comment by ianmartorell** [comment]
Can confirm. This is not an issue in `web` because the URL looks like
```
exp://localhost:19006/MagicLink
```
But in `native` it looks like 
```
exp://192.168.1.10:19000/--/MagicLink
```
and that extra `--/` is not removed from the parsed path returned by `Linking.parse`.

**Comment by cruzach** [comment]
Thanks for opening this issue, sorry it's taken so long to respond. It's a huge help when issues are clear and to the point and include a minimal repro. Really goes a long way in getting it fixed, which this should be as soon as that PR lands ^
