### ISSUE TITLE
Expo notifications - network connection was lost

### ISSUE THREAD

**Issue by SPineapple** [expo/expo#6559]
### Environment

 Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.3.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.0 => 4.0.0 

App Target : iOS/Android

### Steps to Reproduce

A week from now, I couldn't login via expo, to use expo notifications, but then I changed my network connection to VPN, and now that I successfully logged-in, I am now facing another issue,
Following this tutorial : 
https://docs.expo.io/versions/latest/guides/push-notifications/
### Actual Behavior
and upon calling the function I get : 

```

[Unhandled promise rejection: Error: The network connection was lost.]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- ... 5 more stack frames from framework internals
```

### Expected Behavior

Before this could happen, I was able to get expo token, and able to receive notifications, but now I keep having issues related to network connections

Is there anything I can do ? Help is appreciated.

**Comment by cruzach** [comment]
What function are you calling? 

I don't think this is a bug with the Expo SDK, but rather related to your VPN connection, and how your computer is connecting to your device. [this issue](https://github.com/expo/expo/issues/213) may give some insight. I suggest trying using the `tunnel` connection in expo-cli
