### ISSUE TITLE
Alert doesn't popup on chrome

### ISSUE THREAD

**Issue by dejawho** [expo/expo#6560]
## 🐛 Bug Report

Hi, I'm trying to convert my react native app to run on the web, a lot of things works out of the box (thanks expo) but I have some issue with Alert, they simply doesn't popup

### Environment

Expo CLI 3.0.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

Target web

### Steps to Reproduce

Run and app expo start -w, with a click event on an item that call an Alert.alert

### Expected Behavior

An alert should popup

### Actual Behavior

nothing happen

### Reproducible Demo

`import React from 'react';
import { StyleSheet, Text, View, TouchableHighlight, Alert } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <TouchableHighlight onPress={()=> {Alert.alert("testalert", "testalert")}}>
      <Text>Open up App.js to start working on your app!</Text>
      </TouchableHighlight>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`

**Comment by cruzach** [comment]
Closing since this is an open feature request on the react-native-web repo -> https://github.com/necolas/react-native-web/issues/1026

Best workaround I can think of for the time being is to use `alert()` instead of `Alert.alert` when on web
