### ISSUE TITLE
Error while updating property 'start' in shadow node of type: RCTView

### ISSUE THREAD

**Issue by jaksm** [expo/expo#6561]
## Description
Opening app with Expo Developer Tools on the phone via QR Code scan (Tunnel, LAN and Local) (Production mode on & off) throws this weird error while opening the same app on iOS Simulator works just fine. I also tried publishing the app and it worked (https://expo.io/@jaksm/doggo-dating).
## Expected Behavior
I ran `yarn start` which should allow me to open the app on my phone.
## Observed Behavior
Expo Dev tools printed no errors and the device shows this screen:

![Screenshot_2019-12-17-13-55-18-025_host exp exponent](https://user-images.githubusercontent.com/30727082/71009972-7163f100-20eb-11ea-98ec-be559f3e8286.jpg)

## Environment
```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.0.0 - /usr/local/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.9 => 16.9.11
      @types/react-native: ^0.60.21 => 0.60.22
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.1
```
Also specify:
- Phone model: XIAOMI POCOPHONE F1 with expo app v2.14.0
- Simulator: Version 11.1 (SimulatorApp-912.1 SimulatorKit-570.3 CoreSimulator-681.5.4)

**Comment by brentvatne** [comment]
can you please provide a reproducible example? here's some information on how to do that: https://stackoverflow.com/help/mcve

you can post it to https://snack.expo.io or share the full example code here.

**Comment by jaksm** [comment]
Finally, I solved it! This issue is not related to expo, [`react-native-copilot`](https://github.com/mohebifar/react-native-copilot) library  was throwing this error and when it got removed from project dependencies everything worked well again.
