### ISSUE TITLE
36.0.0 not a valid SDK version

### ISSUE THREAD

**Issue by wibav** [expo/expo#6567]
### Environment

 Expo CLI 3.11.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

Android

### Steps to Reproduce

i run 
expo inti recordatorios
cd recordatorios
yarn start

run in android simulator

and give this error 

36.0.0 not a valid SDK version

**Comment by cruzach** [comment]
You need to update your version of the Expo Client, see our release notes for how to do that https://blog.expo.io/expo-sdk-36-is-now-available-b91897b437fe

**Comment by Vanals** [comment]
I am having the same issue and even updating the Expo version and the client I still get "36.0.0 not a valid SDK version " when using Android Studio

**Comment by geoseong** [comment]
@Vanals Why don't you uninstall Expo in your emulator and try it again?

**Comment by remo87** [comment]
Thanks! @geoseong

**Comment by uooopss** [comment]
`expo upgrade` it works for me

**Comment by gustakoch** [comment]
> `expo upgrade` it works for me

it works for me too

**Comment by joker7blue** [comment]
Upgrade your expo client on your mobile phone on playstore

It work for me

**Comment by alexxfreitag** [comment]
works for me too, thanks!

**Comment by alexxfreitag** [comment]
`expo client:install:android` work for me :)
