### ISSUE TITLE
Branch.subscribe listeners and calls to Branch.getLatestReferringParams(true) do not behave all times correctly on iOS

### ISSUE THREAD

**Issue by Syesy** [expo/expo#6568]
### Environment

Expo CLI 3.11.1 environment info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.17.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
    npmGlobalPackages:
      expo-cli: 3.11.1

I'm currently developing a standalone application

### Steps to Reproduce

Listeners added with calls to Branch.subscribe are not always triggered on iOS. Moreover calls to Branch,getLatestReferringParams(true) can get stuck.
These problems arise roughly in 50% of app launches.

### Expected Behavior

Listeners added with Branch.subscribe are supposed to always be triggered and call to Branch.getLatestReferringParams(true) should not block.

### Actual Behavior

I suppose that the problem is caused by the way

`(BOOL)application:(UIApplication *)app 
            openURL:(NSURL *)url 
            options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options;` 

is implemented.
In particular: 

`UMAppDelegateWrapper (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options`

sends a message to

`UMAppDelegateWrapper (NSArray<id<UIApplicationDelegate>> *)getSubcontractorsImplementingSelector:(SEL)selector`

which in turn it sends a message to
`UMAppDelegateWrapper (void)ensureSubcontractorsAreInitialized`

in which we find the following line of code

`NSArray<UMSingletonModule*> * singletonModules = [[UMModuleRegistryProvider singletonModules] allObjects];`

Now, due to the undefined order of the objects returned by

`NSSet allObjects` 

it can happens that 

`EXKernelLinkingManager (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)URL
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation`

is called before the one implemented by EXScopedBranchManager. Now because the above method always returns YES, the EXScopedBranchManager's implementation of openURL is never called.

Is it by design or not?

### Reproducible Demo
Here you can find a reproducible demo. Of course, due to the use of Branch, this code can works only in a standalone app
https://snack.expo.io/HkB!RM!CB

**Comment by StarlingMercedes** [comment]
I have the same problem😥, hope it will be resolved soon 🏆 @sjchmiela

**Comment by raheelshah31** [comment]
Same problem affecting almost all adlinks. Any update on this.Any help is appreciated.

**Comment by cruzach** [comment]
Hey @Syesy thanks for the breakdown in your issue report, it sound spot-on since there was a similar issue with the `expo-facebook` module a while back, fixed with this pr - https://github.com/expo/expo/pull/7931 which makes sure the `ExpokitAppDelegate` (which is then calling into `EXKernelLinkingManager`) is always sorted last. Have you tested this on SDK 38?

**Comment by cruzach** [comment]
closing this as I tested it and `EXBranchManager` is always sorted _before_ `ExpokitAppDelegate` as of SDK 38 👍
