### ISSUE TITLE
[docs] Update installation instructions in expo-crypto to reflect that it works in managed projects now

### ISSUE THREAD

**Issue by pcowgill** [expo/expo#6569]
Update [installation instructions in expo-crypto](https://github.com/expo/expo/tree/master/packages/expo-crypto) to reflect that [it works in managed projects now](https://docs.expo.io/versions/latest/sdk/crypto/).

**Comment by cruzach** [comment]
closed in https://github.com/expo/expo/commit/21eb79db30ece24d80f7e896518969e7ea8dce33
