### ISSUE TITLE
SDK 36 Text Selectable

### ISSUE THREAD

**Issue by thebetterjort** [expo/expo#6571]
I'm trying to get SDK 36 to work on the web. I'm trying to make text selectable. It doesn't work.

<Text selectable>Hello Select me</Text>
or
<Text selectable={true}>Select me</Text>

This isn't a SDK 36 things per se, only that I noticed that it doesn't work with Expo Web.

**Comment by cruzach** [comment]
Do you mean adding an onPress to a Text component? I did that in [this snack](https://snack.expo.io/@charliecruzan/shallow-beef-jerky) and it seems to work fine

Closing since this isn't a bug with the Expo SDK, maybe with `react-native-web`? Although hard to say without a full bug report

**Comment by thebetterjort** [comment]
Yes in a text component. I use touchable opacity and it seems to not allow copying the text.

**Comment by heythisischris** [comment]
You can add `userSelect: 'text'` to the Text component to make it selectable in Expo web.
