### ISSUE TITLE
expo-* packages has null/undefined attributes

### ISSUE THREAD

**Issue by guanw** [expo/expo#6572]
### Environment

expo 33.0.7

### Steps to Reproduce
I was trying to get device/application information from packages like expo-device and expo-application:
```
import * as Application from 'expo-application'
import * as Device from 'expo-device';
...
console.log(Application);
console.log(Device);
```

the output shows the package object has the following attr:
![image](https://user-images.githubusercontent.com/7311035/71134530-a7c56d00-21cc-11ea-80a1-2f5e1cd9c646.png)
![image](https://user-images.githubusercontent.com/7311035/71135303-58347080-21cf-11ea-8e99-b1348beaf866.png)

But all of them are null and when I try to get the value from promise like following:
```
Device.getDeviceTypeAsync().then(val => {
      console.log(val);
    })
```
it's giving me error:
![image](https://user-images.githubusercontent.com/7311035/71134592-cfb4d080-21cc-11ea-83e9-0f010cf9be51.png)

Please help.

### Expected Behavior

I expected the promise and attr of those packages to show device and application information.

### Actual Behavior
they all show null or undefined

**Comment by cruzach** [comment]
Those modules were added in [SDK 35](https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4), so you'll need to upgrade to use them
