### ISSUE TITLE
Location Expo

### ISSUE THREAD

**Issue by lecamit83** [expo/expo#6574]
### Environment

Android 9.0
Expo SDK 35
### Actual Behavior
{
          timeInterval: 500,
          accuracy: Location.Accuracy.Balanced,
          distanceInterval: 0,
          enableHighAccuracy: true,
        }
I've configured Location with props intervalTime : 300ms . It's run again about 5000ms with foreground. And run again about 5 minutes with background.

**Comment by cruzach** [comment]
The `timeInterval` is the minimum time to wait between each update. When the app is placed in the background, calls will occur less frequently to preserve battery. The default policy (of mobile platforms -- not something Expo decided) is to notify when there are significant changes in background location.

[This issue](https://github.com/expo/expo/issues/3256) reports something similar and has more explanation
