### ISSUE TITLE
snack-sdk or upstream api failing silently when using snack-sdk in react native app.

### ISSUE THREAD

**Issue by dmueller39** [expo/expo#658]
Originally opened here:

https://github.com/expo/snack-sdk/issues/2

Using this example project:

https://github.com/dmueller39/mobile-snack

This project can "Save" and open a shareable url for a snack, but opening the expo app with live updates never succeeds. It may be that this is a usage issue, but I am not seeing any errors, and there is not anything obvious.

SnackSession works as expected for starting + publishing, but I can't seem to open the snack session using getURLAsync. Using saveAsync does work and those projects open in the Expo app.

Note that for development I am running snack-sdk on the simulator, but trying to open the snack session on a device using the url.

I have investigated supplying a fake UserAgent to see if the metadata was required upstream, but it appears that it is not. Furthermore change the sdkVersion has no effect.

**Comment by dmueller39** [comment]
@satya164 I know you did a talk on snack. Any thoughts?

**Comment by satya164** [comment]
cc @tcdavis

**Comment by dmueller39** [comment]
Here is a published experience of mobile-snack https://exp.host/@dmueller39/mobile-snack

**Comment by tcdavis** [comment]
Thanks @satya164. 
Very excited to look into what's going on here, but won't have a chance until Friday. If saving is working, I suspect it is our issue and not yours @dmueller39

**Comment by aada** [comment]
I'm trying to run snack-sdk example, it gives this error when I try to run it 
`Uncaught (in promise) TypeError: _this2._snack.saveAsync is not a function`
any ideas to get it to save to expo?

**Comment by AdamJNavarro** [comment]
Hey @dmueller39,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate. Thanks again for your initial report!

Cheers,

Adam
