### ISSUE TITLE
Trying expo SDK36, corrupted project after 5 minutes => Error: ENOENT: no such file or directory, open '/home/dka/workspace/native-test/node_modules/expo/AppEntry.js'

### ISSUE THREAD

**Issue by kopax** [expo/expo#6580]
Hello and thanks for sharing expo, 

I am using SDK 36 and after initializing a blank project, it worked great.

After running once `rm -rf node_modules && npm i`, I got my blank project corrupted and so far I can only restart from scratch, which is kind of bad for being enthusiast starting my app with expo. (kind of no-go)

This is the error:

```
Failed to compile
/home/dka/workspace/native-test/node_modules/expo/AppEntry.js
Error: ENOENT: no such file or directory, open '/home/dka/workspace/native-test/node_modules/expo/AppEntry.js'
```

I undertand there's a lot of magic within expo, I am used to work and release package on npm, and I don't understand this. 

Is there a way to fix this?

Thanks and best!

**Comment by kopax** [comment]
Since I haven't done anything, I took the decision to remove everything and start over. I haven't pushed anything on my repo since there was nothing to push.

Now when I do `expo init`, I have:

```
▸ Invalid slug: The path "/home/dka/workspace/native-test" already exists. Please choose a different parent directory or project name.
```

It's quite problematic...

**Comment by brentvatne** [comment]
does `node_modules/expo/AppEntry.js` exist? this sounds like your node_modules directory was deleted 🤔 expo-cli does not do that, this would be up to you or some other tool on your machine. you can run `npm install` or `yarn` again.

**Comment by brentvatne** [comment]
also, please share your repository on github or somewhere where we can pull it to reproduce your issue

**Comment by kopax** [comment]
> does `node_modules/expo/AppEntry.js` exist? 

Hi @brentvatne ant thanks for taking care, yes it was existing, running `npm install` did not change anything. I did remove everything. I will spend full time to evaluate expo during the weekend, I will  produce a repository on GitHub if I can reproduce, or close the issue.

**Comment by kopax** [comment]
I am not able to reproduce that issue. I have no clue what happened but I believe I have not done something out of the explanation here. THat's weird, I will report again if that rehappen  again, thanks to all, @brentvatne merry Christmas!
