### ISSUE TITLE
Error in Expo.fx.js on iOS after upgrading to SDK 36

### ISSUE THREAD

**Issue by vandrieu** [expo/expo#6582]
### Environment

  Expo CLI 3.11.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      npm: 6.13.1 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.1 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.11.2

### Steps to Reproduce

1. Upgrade to SDK 36 as per the docs

1. Clean all caches and reinstall: `watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c`

1. Launch expo: `expo start`

### Expected Behavior

I expect no crash, just like before the upgrade

### Actual Behavior

The iPhone screen reads:

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PatchedProviderComponent`.

This error is located at:
    in DevAppContainer (at Expo.fx.js:25)
    in PatchedProviderComponent (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)
```

The console reads:

```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at Expo.fx.js:26., 
    in PatchedProviderComponent (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/react/cjs/react.development.js:172:36 in warningWithoutStack
- node_modules/react/cjs/react.development.js:612:32 in warning
- node_modules/react/cjs/react.development.js:1944:14 in createElementWithValidation
- node_modules/expo/build/Expo.fx.js:26:13 in PatchedProviderComponent
```

Both logs state the error is located in `node_modules/expo/build/Expo.fx.js`

### Reproducible Demo

I could not reproduce it by creating a new project, so it is somehow related to this project's code

BUT, the same exact code worked just before the upgrade, so anyway, the upgrade breaking the build is an issue.

1. If it's ONLY because of my code, the stack trace should indicate what code (it currently states that the bug is in Expo.fx.js)

2. If it's somehow related to Expo.fx.js, then there is something to be fixed on Expo side

Thanks

**Comment by brentvatne** [comment]
hello! please try this approach to isolate the source of the problem on your end: https://www.codelord.net/2012/04/10/using-binary-search-for-debugging/

> Finding an offending line
> When confronted with a chunk of code that does something I don’t want it to and trying to understand which line exactly is causing it I sometimes simply use binary search on the lines themselves. I start with by commenting out half of the lines and seeing if the problem persists. If it is I know it’s in the lines left, otherwise I know it’s in the lines I commented out. Repeat until you find the culprit!

there isn't much we can do to help here if we cannot reproduce the issue

**Comment by vandrieu** [comment]
@brentvatne 
Sure! I'm just logging it here, in case people having the same problem will search on google, land here, have a reproducible demo and we can all contribute to understand what's happening

**Comment by vandrieu** [comment]
@brentvatne but anyway whoever in expo team wrote the piece of code that fails may help a lot.

```
<DevAppContainer>
            <ProviderComponent>{props.children}</ProviderComponent>
</DevAppContainer>
```

**Comment by brentvatne** [comment]
@vandrieu - i think we can add a validation there that you are exporting a component from App.js

**Comment by vandrieu** [comment]
I found the cause. 
When I remove `import Toast from 'react-native-root-toast';` it runs.
Beginner question: let's say I want to keep the toasts functionality in my app. How would you address this issue? Forking the react-native-root-toast project and debugging it?

**Comment by brentvatne** [comment]
@vandrieu - i will look into that

**Comment by vandrieu** [comment]
Thanks.
I was trying to make a snack with just a main page and the Toast import, but I get `Device: Unable to resolve module 'module://react-native-root-toast.js'` 😕

**Comment by brentvatne** [comment]
cc @tcdavis re snack

**Comment by vandrieu** [comment]
### Reproducible demo

`>  expo init test2`
`>  cd test2/`
`>  npm i react-native-root-toast`
Add `import Toast from 'react-native-root-toast';` in App.js
`>  expo start --ios`

You get :

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PatchedProviderComponent`.

This error is located at:
    in DevAppContainer (at Expo.fx.js:25)
    in PatchedProviderComponent (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

```

**Comment by brentvatne** [comment]
install the expo package version 36.0.2 and that will resolve your issue

```
npm install expo@36.0.2
```

**Comment by vandrieu** [comment]
@brentvatne not, it doesn't

**Comment by brentvatne** [comment]
yes it does. make sure you actually installed it correctly

**Comment by vandrieu** [comment]
Your project works well on my machine. I can't figure out what I am doing wrong! Here is mine: https://github.com/vandrieu/toast

**Comment by brentvatne** [comment]
try your steps from the initial comment to be safe:

```
watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c
```

**Comment by vandrieu** [comment]
@brentvatne it works! thanks for spending so much time helping me. 
`npm install expo@36.0.2` + cache clearing was the solution
Thanks

**Comment by brentvatne** [comment]
excellent, thanks for reporting and following up!

**Comment by Zmeu213** [comment]
Had the same problem but suggested cache cleaning didnt solve it. Only full removing off project directory and then new fresh cloning from git helped

**Comment by fantasyado** [comment]
Same here,  upgrade to expo 36.0.2 and clear cache worked for me!
