### ISSUE TITLE
Root background color always white when using Modal with presentationStyle pageSheet

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#6585]
### Steps to Reproduce

- Set expo.backgroundColor to `"#000000"` in app.json
- Use the `Modal` component from react-native and set the `presentationStyle` to `pageSheet`
- Despite background color being black on the React root view, a white background is visible when the modal opens.

### Expected Behavior

- Root background color should apply in this case. The parts that are white in the "actual behavior" below should be black.

### Actual Behavior

![modal](https://user-images.githubusercontent.com/90494/71202496-354aa080-2251-11ea-9742-63bcbb7f7270.gif)

### Reproducible Demo

https://github.com/brentvatne/modal-sheet-bg-color

**Comment by Hirbod** [comment]
this also affects react-navigation and  react-navite-screens's createNativeStackNavigator

**Comment by mohmdalfaha** [comment]
Any update when this issue be resolved? or any workaround?

**Comment by brentvatne** [comment]
we're hoping to have a solution for sdk37

**Comment by pdugan20** [comment]
Looking forward to it! Thanks @brentvatne.

**Comment by brentvatne** [comment]
hey folks i didn't get around to this for sdk 37 after all, sorry about that

**Comment by emroot** [comment]
oh man, I really didn't wanna eject my app. thanks for looking into this @brentvatne

**Comment by pdugan20** [comment]
@brentvatne hey no worries man, know you guys fit a lot into 37 and thanks for the update.

**Comment by AnotherEye** [comment]
any news?

**Comment by emroot** [comment]
@brentvatne any chance we could get this for SDK 38? 😃
This is the only feature that's blocking shipping my app without ejecting, I'd rather not and wait for 38 if that's feasible.

**Comment by brentvatne** [comment]
@emroot - looking into this today, no promises but if it's a safe and small change then we can try to fit it into an upcoming patch release

**Comment by emroot** [comment]
@brentvatne thank you. You'll be my hero.

**Comment by emroot** [comment]
@brentvatne also, @kmagiera looked into this issues in react native screens. This might help.
https://github.com/software-mansion/react-native-screens/issues/361#issuecomment-604441808

**Comment by AnotherEye** [comment]
hey guys, sorry for the noob question but now that the post is closed can we just type "expo update" to have this feature or there is another way to see the changes?
because i can't see any change with that command..

**Comment by Hirbod** [comment]
@AnotherEye no you can't. You have to wait for a release and a new Expo App update. After that, you prob. have to call `expo-cli upgrade` and it will upgrade the SDKs for you.

**Comment by AnotherEye** [comment]
thanks for the reply and explanation!

**Comment by brentvatne** [comment]
we're going to do a patch release soon and will let people know when it's ready on twitter https://twitter.com/expo

@Hirbod - we pulled in the following improvements for screens:
- https://github.com/expo/expo/commit/9611f2ff9db5312ba3f0ee06474a688ae2168c6d
- https://github.com/expo/expo/commit/4ce278f6569b799fd9fab796d983a8f3111bc0b2

**Comment by Hirbod** [comment]
@brentvatne thanks for the answer. Even though I hijacked this issue (sorry), could you explain why you guys just don’t update to 2.7.0 instead of cheery picking top issues? We can’t set any headerLeft prop on native-Stack, no headerCenter prop and title only accepts a string. And on Android there are header bugs < 2.4.0. all of this stuff has been fixed and you guys do a out of Plan release. Pretty sad..

**Comment by brentvatne** [comment]
@Hirbod - we don't do significant upgrades in the middle of the sdk release, everyone has their pet issues that they would love to see addressed and i know it is annoying to have to wait but we have to be selective about what we pull in and we only do it if we are sure we will not break any existing behavior that people depend on. if you absolutely need a feature the recommendation is to eject

**Comment by Hirbod** [comment]
Sigh...

**Comment by garrytaulu** [comment]
It seems small but I'm so excited for this 😝 thank you!

**Comment by brentvatne** [comment]
@pdugan20 @garrytaulu @Hirbod - this is live now! run `expo client:install:ios` to get the latest version for simulator, update on app store, and do a new build with `expo build:ios` to get the updates in your standalone app

**Comment by Hirbod** [comment]
Thanks @brentvatne. My app just got approved by Apple :D 
Dang it. Thanks!

**Comment by brentvatne** [comment]
@Hirbod - no need to run `expo upgrade` - the changes are all on the native side of the sdk / client runtime

**Comment by Hirbod** [comment]
It works great, beautiful! AND YAAAY, DEBUGGER/PERFORMANCE monitor works too + the developer screen finally shows on top of native modals - unfortunately the element inspector attaches still behind the modal and can't inspect elements in iOS PageSheets/FullscreenModals.

@brentvatne anyway, good work. I'm sure this will be fixed somewhere in the future!
