### ISSUE TITLE
Unable to change StatusBar barStyle when using WebBrowser 

### ISSUE THREAD

**Issue by pdugan20** [expo/expo#6588]
### Environment
Expo SDK 36.0.2 on iOS

### Steps to Reproduce
- Set WebBrowser toolbarColor to "#000"
- Open the WebBrowser
- StatusBar text is the same color as the WebBrowser and cannot be seen

### Expected Behavior
It should be possible to set the StatusBar barStyle to "light-content" or "dark-content"

### Actual Behavior
The StatusBar barStyle currently inherits from the system level settings, and will show as white or black dependent on whether a user has enabled Dark Mode. It's currently not possible to toggle the StatusBar barStyle while the WebBrowser is open.

![Untitled](https://user-images.githubusercontent.com/1837100/71218208-83719b00-2275-11ea-9f1e-45a10a5771c4.gif)

**Comment by cruzach** [comment]
@pdugan20 can you provide the repro for this please?
