### ISSUE TITLE
Asset issue when pushing .ipa to iOS Store

### ISSUE THREAD

**Issue by joshmello** [expo/expo#659]
I opened the .ipa and they are all in there. What could be the issue?
Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/x3/sw7m5_cd3rs6np31x161tldm0000gn/T/3FF96985-FF6A-4974-93BB-9B3768B0AB27/1286761178.itmsp - Error Messages:
		ERROR ITMS-90022: "Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0."
		ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '76x76' pixels, in .png format for iOS versions >= 7.0."
		ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '167x167' pixels, in .png format for iOS versions supporting iPad Pro."
		ERROR ITMS-90023: "Missing required icon file. The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 7.0."

**Comment by terribleben** [comment]
That's odd. What version of application loader are you using? Can you make sure it's a newish non-beta version?

If the issue persists, can you double check that the assets in the .ipa are actually 120x120 (etc.) and not some non-square size?

**Comment by joshmello** [comment]
@terribleben I am using Version 3.6 (1020). I am not on any betas (learned the hard way in the past).
I will link whats inside my .ipa but everything looks good. I inspected all of the assets and they all match. Also, I submitted a build a few days ago with no issues so not sure. I changed my app.json to match standalone code versions but that's it.

**Comment by joshmello** [comment]
@terribleben I think I found the issue. My app-icon.png was too big(go figure). So I lowered the size in half and everything seems to work. Just weird why that would cause it to me. Thanks for the response much appreciated.
