### ISSUE TITLE
Application crash on start Iphone XS Exception type: EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by gDlugokecki** [expo/expo#6591]
## 🐛 Bug Report

Hello,
Its my first issue here, im not sure if it's right place to post. Our application is using EXPO KIT
It does not work on iphone XS (OS 13.3), on other devices - iPhone 6,7,8 it works. Just before start it crashes. I have no idea what might cause the issue. I have tried rebuilding the application. We are testing it on Testlight and iPhone XS tester could not launch it .Im attaching crash log. 

[crashlogIssue.pdf](https://github.com/expo/expo/files/3987567/crashlogIssue.pdf)

**Comment by cruzach** [comment]
Hi there! This is the right place to report Expo bugs, but we need you to fill out the full bug report template please. Alsoo- [this forum post](https://forums.expo.io/t/ios13-crashes-instantly-for-some-exc-bad-access-sigbus/28010/41) deals with the same error, using Expokit. I'm not sure what SDK you're using, so I'm not sure it applies, but it's worth a look!
