### ISSUE TITLE
blank App.js javascript is weird

### ISSUE THREAD

**Issue by kopax** [expo/expo#6592]
Hello again, I wanted to report a weird file I am looking at, from the blank example (SDK36):

```jsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

To me, L12, the `const styles` is initialized after `App`, while App is using `styles` within it's body.

It work because somewhere in expo, App is called, but it's kind of annoying me seeing this. (a bit ugly)

Should we consider moving up `styles` before `App.js`?

**Comment by cruzach** [comment]
That's actually a pretty standard way of doing it, and is also how the rest of the example in our docs are written 😅  so we'll probably keep it the way it is, but thanks for the suggestion!
