### ISSUE TITLE
Bundled image cannot be displayed when running a standalone application

### ISSUE THREAD

**Issue by sylmarch** [expo/expo#6594]
# Bug

Bundled images in the APK are not displayed when launching the application from the APK.

Hereby:

1) the display when launching the application from the development environment (i.e. using the expo client application on the phone) :

![display-startint-app-from-dev-environment](https://user-images.githubusercontent.com/11892658/71260743-e75e9700-233b-11ea-95e3-208a52da2c80.png)

2) the display when launching the application from the standalone application (i.e. after installing the APK on the phone):
![display-starting-app-using-APK](https://user-images.githubusercontent.com/11892658/71260803-0f4dfa80-233c-11ea-9d0a-f2759f166b63.png)

Not that when I unpack the APK, I can check that the logo.png file has been copied into the APK:
![apk-content](https://user-images.githubusercontent.com/11892658/71260839-25f45180-233c-11ea-81e9-ad215f09a2c1.png)

I generate the APK on my computer using the expo turtle-cli tool (i.e. I don't use remote expo servers to compile my code).

# Environment

```bash
$ expo diagnostics

  Expo CLI 3.11.2 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/software/node/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.4 - ~/software/node/bin/npm
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.2
```

```bash
$ turtle --version
0.13.6
```

# Procedure to reproduce the bug

Create a very simple project from scratch.

Create the project and start it:
```bash
# blank project, managed with npm (not yarn)
expo init TestBundledAssets

cd TestBundledAssets/
npm start
```

Copy the logo.png image inside a new folder `TestBundledAssets/assets/images/`. 
Hereby the related file:

![logo](https://user-images.githubusercontent.com/11892658/71261281-440e8180-233d-11ea-9865-8f4ffa9df964.png)

Change the `App.js` file with this content:
```javascript
import React from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Text above the logo image.</Text>
      <Image source={require('./assets/images/logo.png')} />
      <Text>Text below the logo image.</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Add the following section in the `app.json`:
```javascript
...
    "android": {
      "package": "com.example.test_bundled_asset"
    },
...
```

Check in your app.json file the value of `assetBundlePatterns` property:
```javascript
...
    "assetBundlePatterns": [
      "**/*"
    ],
...
```

To generate an APK without using expo remote servers, use turtle-cli tool:

```bash
# install turtle-cli
npm install -g turtle-cli

# install gulp-cli
npm install -g gulp-cli

# install yarn (see https://yarnpkg.com/lang/fr/docs/install/#debian-stable to add yarn repository)
apt install yarn

# download AdoptOpenJDK 8 (see https://adoptopenjdk.net/) and install it in /opt/adopt-openjdk-8-u232-b09/ folder

# configure environment variables for JDK
export JAVA_HOME=/opt/adopt-openjdk-8-u232-b09
export PATH="${JAVA_HOME}/bin:${PATH}"

# check that all is OK to build Android. This will automatically install an Android SDK in ~/.turtle/ folder if Android SDK cannot be found.
turtle setup:android

# configure environment variables for Android SDK
export ANDROID_HOME=~/.turtle/androidDependencies/sdk/
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# go to your project
cd TestBundledAssets

# generate a key to sign your APK.
# - Keystore password: my-keystore-password
# - Key password: my-key-password
mkdir private/
cd private/
keytool -genkey -v -keystore my-keystore.keystore -storetype jks -alias my-key -keyalg RSA -keysize 2048 -validity 10000
cd ..

# remove previous dist/ folder
rm -rf dist

# export application locally. This will create dist/ folder.
expo export --dev --public-url http://127.0.0.1:1234

# start an HTTP server to serve the content of dist/
cd dist/
python3 -m http.server 1234 --bind 127.0.0.1


# check that the android-index.json file can be accessed though a HTTP request:
curl http://127.0.0.1:1234/android-index.json

# go to the project root and generate the APK in the dist/ folder
cd ..

EXPO_ANDROID_KEYSTORE_PASSWORD="my-keystore-password" \
EXPO_ANDROID_KEY_PASSWORD="my-key-password" \
turtle build:android \
  --type apk \
  -o dist/testBundledAssets.apk \
  --keystore-path "private/my-keystore.keystore" \
  --keystore-alias "my-key" \
  --public-url http://127.0.0.1:1234/android-index.json
  --type apk

# connect the phone with an USB cable and install the APK
adb devices
adb install -r dist/testBundledAssets.apk
```

Then, on the phone, disable all network connections and launch the TestBundledAssets application from application menu.

=> when the application is started, your should see the 2 text widgets but the image content is not displayed.

**Comment by cruzach** [comment]
Hey @sylmarch- I just tested this with `expo build:android`, and the logo image does show up on the first app open (completely offline). Everything else seems the same, so I'm tempted to believe this may be a turtle-specific issue

Have you tried a test-run using `expo build:android`?

**Comment by arabold** [comment]
Same issue here. I'm trying to build locally using a local web server on 127.0.0.1:5000 (similar to your steps above). The final APK doesn't load the images but instead tries to download them from localhost. It's a trivial following the basic Expo instructions. Very frustrating. I start to think that Expo isn't work the effort you put in trying to fix it and get it to work with 3rd party libs. Maybe ejecting it is just the easiest and most stable path forward. Did you end up finding a solution or did you eject as well?

**Comment by cruzach** [comment]
@arabold if you run the `expo export` command without the `--dev` flag, then it should bundle your assets correctly. Bundled assets are only supported with production mode JS bundles

**Comment by sylmarch** [comment]
As we had to quickly generate an APK, I ejected expo and generate the APK with the Android SDK.
