### ISSUE TITLE
Permissions not working in standalone iOS build

### ISSUE THREAD

**Issue by dwkoogt** [expo/expo#6597]
## 🐛 Bug Report
Permissions methods (getAsync and askAsyc) not working in standalone iOS build. The app does not pop up dialogs for permissions and proceeds without crashing. The errors are caught in Sentry. It happens at app/node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js in call at line 15:42 for both.

An exception was thrown while calling `ExpoPermissions.getAsync` with arguments `(
    notifications
)`: -[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x2834bddc0

An exception was thrown while calling `ExpoPermissions.askAsync` with arguments `(
    location
)`: -[NSTaggedPointerString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0xfb559f5ff99f56ca

### Environment

  Expo CLI 3.11.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: 4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.2

iOS Standalone
### Steps to Reproduce

This happened on iPhone 6 with iOS 12.4.4 (oh yeah, the iOS updated the night before)

### Expected Behavior

On new install, it should ask for permissions when opening the app.

### Actual Behavior

It is not asking for permissions.

**Comment by cruzach** [comment]
Could you provide a repro? I can try to reproduce this on my end with those permissions, but I recently did a test for `MediaLibrary` and permissions for `camera_roll` came through fine

**Comment by dwkoogt** [comment]
Oops. I had wrong sdkVersion in my app.json file. Well, expo upgrade did update it but I forgot to manually update environment specific app.xxx.json files. Correcting that worked.

**Comment by rahmad-12** [comment]
Can you explain how you fixed this?  I am having the same issue.  I am getting the following error:
Error: An exception was thrown while calling `ExpoPermissions.getAsnyc` with arguments `(location) `: [NSTaggedPointerString countByEnumeratingWithState:objects:count:]:unrecognized selector sent to instance

I looked at my app.json file and my SDK version is 35.0.0.  I am currently using Expo: ^36.0.1

I tried manually changing my app.json SDK version to 36.0.0 but my app crashed.  I got the console.error: "React Native version mismatch".

My app works perfectly on android devices but for some reason my iphone 10 wont render my screen due to the following code line not working:

import * as Permissions from "expo-permissions";

getPermission = async () => {
const {status} = await Permissions.getAsync(Permissions.LOCATION);
//Other code
}

**Comment by PeterTran0609** [comment]
I have the same issue when ask for permission to use photo. I was using this code ` const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);` and I get CAMERA_ROLL undefine. But when change to use `const { status } = await MediaLibrary.requestPermissionsAsync();`  it fine. But the document in Medium said, the old code still work. I don't know why it happen.

**Comment by chris-ryu** [comment]
I'm using 35.0.0, iPhone Xs.

`  const { status: existingStatus } = await Permissions.getAsync(
    Permissions.NOTIFICATIONS
  );`

An exception was thrown while calling 'ExpoPermissions.getAsync' with arguments '(notifications)':-[_NSCFString countByEnumerationWithState:objects:count:]:unrecognized selector sent to instance...

**Comment by oliemansm** [comment]
Same issue as @chris-ryu here

**Comment by oliemansm** [comment]
@chris-ryu I was able to solve it by doing the following:
* Rely on `expo-permissions: "^7.0.0"` in package.json instead of "latest"
* Run `expo r -c` to force expo rebuild

**Comment by chris-ryu** [comment]
> @chris-ryu I was able to solve it by doing the following:
> 
> * Rely on `expo-permissions: "^7.0.0"` in package.json instead of "latest"
> * Run `expo r -c` to force expo rebuild

Thank you, 
The problem solved. :)

**Comment by CWilsonTSP** [comment]
@oliemansm Why is that what fixed your issue? It did not work for me. @dwkoogt what _exactly_ did you mean 

> I had wrong sdkVersion in my app.json file. Well, expo upgrade did update it but I forgot to manually update environment specific app.xxx.json files. 

What is a "wrong sdkVersion" ? I am having the same issue that you were having.

**Comment by oliemansm** [comment]
@CWilsonTSP I had several `expo-...` dependencies in my `package.json`, but the versions were mixed. So some of them were using `"^7.0.0"` while some were using `latest`. That worked fine as long as `latest` was in fact the same as `"^7.0.0"`. But then `8.0.0` was released (or something else incompatible) and then all of a sudden I ran into problems. By forcing all my expo packages to use the same version and not rely on `latest` anywhere it was solved for me.

**Comment by 852-pan0s** [comment]
> @chris-ryu I was able to solve it by doing the following:
> 
> * Rely on `expo-permissions: "^7.0.0"` in package.json instead of "latest"
> * Run `expo r -c` to force expo rebuild

Cool! you solved my same problem!

**Comment by brentvatne** [comment]
always use `expo install` to install packages from the sdk to avoid this issue

**Comment by Rutvik17** [comment]
> @chris-ryu I was able to solve it by doing the following:
> 
> * Rely on `expo-permissions: "^7.0.0"` in package.json instead of "latest"
> * Run `expo r -c` to force expo rebuild

I did this and it started working.
But after a few refreshes i started getting the same error again.

**Comment by Rutvik17** [comment]
This bug is still there, please re-open this issue.

**Comment by brentvatne** [comment]
@Rutvik17 - there have been no other reports of this so the error is likely on your side. please create a new issue with a minimal reproducible example and i would be happy to help, thanks! https://stackoverflow.com/help/mcve
