### ISSUE TITLE
Error boundary is not respected on native platforms

### ISSUE THREAD

**Issue by bisubus** [expo/expo#6598]
### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: Windows 7
    Binaries:
      Yarn: 1.19.1 - C:\Program Files (x86)\nodejs\yarn.CMD
      npm: 6.11.3 - C:\Program Files (x86)\nodejs\npm.CMD

App targets are iOS, Android and Web.

### Steps to Reproduce

Create error boundary from `App` component with `getDerivedStateFromError` and launch it on native platform (iOS, Android). The problem is reproducible with a snack or expo-cli.

### Expected Behavior

`getDerivedStateFromError` should handle the error and prevent it from propagating on both web and native platforms.

### Actual Behavior

`getDerivedStateFromError` is called on error but doesn't prevent native redbox from appearing on native platforms.

### Reproducible Demo

Demo: https://snack.expo.io/r1Mi0K5RS

```js
import { Text } from 'react-native';
import React, { Component } from 'react';

class App extends Component {
	static getDerivedStateFromError(error) {
		console.warn(error);
		return { error };
	}

	state = { error: null };

	render() {
		return this.state.error ? <Text>Error</Text> : <Root/>
	}
}

class Root extends React.Component {
	state = { error: null };

	componentDidMount() {
		setTimeout(() => {
			this.setState({ error: new Error('Root error')});
		}, 2000);
 	 }

	render() {
		if (this.state.error)
			throw this.state.error;

		return <Text>Root</Text>;
	}
}

export default App;
```

**Comment by bisubus** [comment]
The issue is still relevant.

**Comment by bisubus** [comment]
The issue is still relevant.

**Comment by dodicandra** [comment]
same issue for me. i'm using expo sdk `44`

**Comment by bisubus** [comment]
The issue is still relevant.

**Comment by bisubus** [comment]
The issue is still relevant.

**Comment by bisubus** [comment]
The issue is still relevant.
