### ISSUE TITLE
console.error: "You started loading the font "patrickhand-regular", but used it before it finished loading.

### ISSUE THREAD

**Issue by jsphkm** [expo/expo#6599]
I've downloaded a google font and tried to use it using `Font.loadAsync()` with useState, but for some reason I get this error:

```sh
console.error: "You started loading the font "patrickhand-regular", but used it before it finished loading.

- You need to wait for Font.loadAsync to complete before using the font.

- We recommend loading all fonts before rendering the app, and rendering only Expo.AppLoading while waiting for lading to complete."
```

I've followed the [instructions](https://docs.expo.io/versions/latest/guides/using-custom-fonts/):

```
...
import * as Font from 'expo-font';

export default function App(){
  const [fontLoaded, setFontLoaded] = useState(false);
  useEffect(() => {
    Font.loadAsync({
      'patrickhand-regular': require('./assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf'),
    });
    setFontLoaded(true);
  });

  return (
    <View>
      {
        fontLoaded ? (
          <Text style={{ fontFamily: 'patrickhand-regular'}}>
            {'Blah blah blah'}
          </Text>
        ) : null
      }
    </View>
  );
}
```

I don't see why I would get that error, isn't it supposed to render null and not attempt to load the font?  I've also tried setting an empty dependency array in the `useEffect` and got the same message.

Here's my `package.json`:
```
// package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~36.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "^8.0.0",
    "react": "^16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.0.0"
  },
  "private": true
}

```

**Comment by jsphkm** [comment]
Found the mistake, forgot async await 🤦‍♂️

**Comment by jsphkm** [comment]
never mind, I'm still getting the error even with async await, even with or without empty dependency array:

```
useEffect(async () => {
    // https://docs.expo.io/versions/latest/guides/using-custom-fonts/
    await Font.loadAsync({
      'patrickhand-regular': require('./assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf'),
    });
    setFontLoaded(true);
  }, []);
```

**Comment by jsphkm** [comment]
I'm noticing that this problem is occurring for the child components.  There is no error message if only applying the font to its own elements, but with child components, applying `fontFamily` is a no go.  How do I apply the fonts for the child components after the font has been loaded?

**Comment by cruzach** [comment]
Hi! The template project you get when you run `expo init` and select the tabs template uses font loading, and I just tested with that and it looks to work just fine. I suggest trying to switch out one of those font files for the one you're using, and see if it works. If it does, then you're probably using the font somewhere as the warning says
