### ISSUE TITLE
XDE should not show QR codes for detached projects

### ISSUE THREAD

**Issue by 20chix** [expo/expo#660]
Hi I'm trying to scan QR code of project but it doesn't work. it closes the page right away, could you please help?

**Comment by terribleben** [comment]
Hi, sorry about that. Can you share the QR code in question?

**Comment by 20chix** [comment]
@mub sent you an Expo link. Open it in Expo: exp0c163c50e42841da95c450bef2b6095c://192.168.0.7:19002 
If you'd like to unsubscribe and stop receiving these emails click here.

I can’t even publish project, tried from my iPad same story. Maybe is ios 11 update?

**Comment by 20chix** [comment]
https://twitter.com/maha_rugs/status/910595406433746944    Same thing happen to this person

**Comment by terribleben** [comment]
Looks like you're using a detached project. You can't test detached projects in Expo Client, you need to run your project directly from Xcode. Make sure you follow [this guide](https://docs.expo.io/versions/latest/guides/expokit.html#3-ios-configure-build-and-run).

In the meantime, this is a bug in XDE - it should not be showing you a QR code for this project. I will update the issue.

**Comment by 20chix** [comment]
I detach my project months ago and it was working fine for expo client, just got this issue today.

**Comment by Elijen** [comment]
@terribleben I am using Expo Client for development even on a detached project as I find it easier and don't require custom native modules in most places in the app.

I am actually missing the QR code from `exp start` output (as it was removed in a recent update). Could the QR code perhaps be still somehow accessible (a settings option maybe)? I'd like to be able to enable it for `exp start` too, but that's probably for a different GitHub issue.
