### ISSUE TITLE
Build breaking errors with imagepicker in bare react native project

### ISSUE THREAD

**Issue by thekrol01** [expo/expo#6601]
### Expected Behavior

Like the other Expo modules. No errors

![Schermafbeelding 2019-12-21 om 20 55 34](https://user-images.githubusercontent.com/34987076/71313284-b0b97700-2436-11ea-90a3-6c8eaa12ea8b.png)

**Comment by brentvatne** [comment]
hey there! make sure you’re using the latest version of react-native-unimodules

**Comment by brentvatne** [comment]
if you don’t want to update that at the moment you can also ensure that expo-image-picker has the same major version as the other expo modules that you are using.

**Comment by thekrol01** [comment]
He Brent. Thank you for your quick reply., appreciate it. I will do that. Let you know.

**Comment by thekrol01** [comment]
Updating the other expo modules  and uni modules to the next major release solved the issue. thanks!
