### ISSUE TITLE
KeyboardAvoidingView changes component positions when behavior="padding" in SDK 36

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [expo/expo#6606]
## 🐛 Bug Report
After updating the project to use an SDK 36 KeyboardAvoidingView started to behave incorrectly on android. When closing the keyboard the last element does not return to the starting location, I believe it is a problem in the version of React Native packaged in this version of expo.

### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 8.16.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 

### Steps to Reproduce

Create a component encapsulated by a KeyboardAvoidingView and play on android, opening the keyboard and closing the last element will be out of place
### Actual Behavior

The last element is far from the bottom of the screen.

![Screenrecorder-2019-12-23-09-51-25-271](https://user-images.githubusercontent.com/15256199/71359113-07739d80-256a-11ea-9f3c-48af93199392.gif)

### Reproducible Demo

```
import React from "react";
import {
  KeyboardAvoidingView,
  View,
  TouchableOpacity,
  Text,
  TextInput,
  StyleSheet
} from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1 },
  contentContainer: { flex: 1, padding: 20, justifyContent: "center" },
  input: { backgroundColor: "#eee" },
  button: { backgroundColor: "purple", padding: 20 },
  buttonText: { color: "#fff", fontWeight: "bold" }
});

export default function App() {
  return (
    <KeyboardAvoidingView behavior="padding" style={styles.container}>
      <View style={styles.contentContainer}>
        <TextInput style={styles.input} />
      </View>
      <TouchableOpacity style={styles.button}>
        <Text style={styles.buttonText}>THE BUTTON</Text>
      </TouchableOpacity>
    </KeyboardAvoidingView>
  );
}
```

**Comment by cruzach** [comment]
Thanks for reporting this! Confirmed that this does not happen in SDK 36, and tested a standalone android app on SDK 36 and saw the same issue

**Comment by Hirbod** [comment]
Is there a workaround?

**Comment by cruzach** [comment]
changing `behavior="height"` results in the proper behavior for me

**Comment by devstarman** [comment]
@cruzach I experience problems with correctly displaying all elements even when switching to behavior="height", before upgrade to EXPO 36 it was working fine. 

I have KeyboardAvoidingView on few screens and with some of them switching to behavior="height" was enough, but on some, I experience nondeterministic behavior. 

For example, I have a button on the bottom of the screen which is not moving up after the keyboard showed up. But when I try to hide the keyboard and then show it again button finally moves.

**Comment by FelipeBohnertPaetzold** [comment]
An interim solution that resolved at first was to change the behavior to height and set the height of the KeyboardAvoidingView, however I had to abandon ```flex: 1```, in this way.

```js
import React from "react";
import {
  KeyboardAvoidingView,
  View,
  TouchableOpacity,
  Text,
  TextInput,
  StyleSheet
} from "react-native";

const styles = StyleSheet.create({
  container: { height: "100%" }, //changed here
  contentContainer: { flex: 1, padding: 20, justifyContent: "center" },
  input: { backgroundColor: "#eee" },
  button: { backgroundColor: "purple", padding: 20 },
  buttonText: { color: "#fff", fontWeight: "bold" }
});

export default function App() {
  return (
    <KeyboardAvoidingView
        behavior="height" //changed here
        style={styles.container}
    >
      <View style={styles.contentContainer}>
        <TextInput style={styles.input} />
      </View>
      <TouchableOpacity style={styles.button}>
        <Text style={styles.buttonText}>THE BUTTON</Text>
      </TouchableOpacity>
    </KeyboardAvoidingView>
  );
}
```

**Comment by outaTiME** [comment]
Related with https://github.com/expo/expo/issues/7589?
