### ISSUE TITLE
Expo 36 still warning to use old lottie-react-native

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [expo/expo#6607]
Expo 36 still warning to use old lottie-react-native, because of this recommendation I spent some days receiving android crashs without understanding what's happening.

Here is the bug: Expo 36 uses React Native 0.60.x and if you use lottie-react-native 3.x expo cli will warning to use old version, but the Android will receive crashs if you render some lottie, and after update to the recommended version 3.3.x + add lottie-ios 3.1.5, the android crashes stop.

Please I suggest to update the recommended version for lottie-react-native into expo to 3.3.x

**Comment by cruzach** [comment]
thanks for the issue! we're aware of this, and are keeping track in this issue https://github.com/expo/expo/issues/5559#issuecomment-564299709
