### ISSUE TITLE
Facebook error after update SDK 35->36 

### ISSUE THREAD

**Issue by gnardini** [expo/expo#6608]
### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.3

Using Expo Client

### Steps to Reproduce

I updated from SDK 35 to SDK 36 and started getting an error screen after ~5 seconds:
`JSON value '<null>' of type NSNull cannot be converted to a valid URL`
`ABI36_0_0facebook::ABI36_0_0React::JSIExcecutor::defaultTimeoutIncoker`
`ABI36_0_0RCTConvert.m:121`

![fb-error](https://user-images.githubusercontent.com/6062888/71366001-74456280-257f-11ea-9ecc-a9d58c80027e.jpeg)
It consistently happens ~3-5 seconds after the splash screen finishes loading.

I have the following properties on my `app.json` related to fb:
```
    "facebookScheme": "fb_my_scheme_number_",
    "facebookAppId": "my_app_id_",
    "facebookDisplayName": "_my_name_",
    "facebookAutoInitEnabled": Tried both true and false,
    "facebookAutoLogAppEventsEnabled": Tried both true and false,
    "facebookAdvertiserIDCollectionEnabled": Tried both true and false,
```

### Expected Behavior

No Facebook error message

### Actual Behavior

I get an error message that I couldn't find anywhere by Googling and searching past issues.

### Reproducible Demo

I was hoping this is just a config issue I can't find, but if necessary I'll create a project to try and reproduce.

**Comment by cruzach** [comment]
What version of `expo-facebook` are you using? 

Do you get the same error on a blank Expo SDK 36 project?

**Comment by gnardini** [comment]
Hi, sorry, it was not related to facebook, the error message was just very confusing.

My problem was that I was sending a `null` value to the `uri` property of the `source` of an `Image`. My bad.

**Comment by kayumoren** [comment]
@gnardini can you explain your solution to me? I'm having the same issue.
