### ISSUE TITLE
[iOS] getInitialURL resolves to exps prefixed url on iOS standalone production app

### ISSUE THREAD

**Issue by sasurau4** [expo/expo#6609]
### Environment

```
Expo version: 35.0.0
OS: iOS 13.3
appOwnership: standalone
expoReleaseChannel: production
device: iPhoneXs
```

### Steps to Reproduce

1. add Universal Link settings to your app.json following the [linking docs](https://docs.expo.io/versions/v36.0.0/workflow/linking/#universal-links-on-ios)

```json
    "ios": {
	  ...
      "associatedDomains": [
        "applinks:your.domain.com"
      ]
    },
```

2. hosting Apple App Site Association File at `your.domain.com`.

3. Click `your.domain.com` link from Browser.

### Expected Behavior

`Linking.getInitialURL()` resolves to `https://your.domain.com`.

### Actual Behavior

`Linking.getInitialURL()` resolves to `exps://your.domain.com`.

On Android production build and iOS dev build is work fine.
Only on iOS release build, `getInitialURL` reoslves to `exps://your.domain.com`.

### Reproducible Demo

No reproduciable demo, because I don't have any domains to associated with. :bowing_man: 

## Note

If someone face the issue with react-navigation and Universal Link, the workaround is adding RegExp of `exps://your.domain.com` to uriPrefix like below.

```js
const yourDomain = 'https:\\/\\/your\\.\\.domain\\.com\\/'
const expoWorkaroundDomain = 'exps:\\/\\/your\\.domain\\.com\\/'
const uriPrefix = new RegExp(
  `${ExpoLinking.makeUrl('/')}|${yourDomain}|${expoWorkaroundDomain}`
)
```

Thanks for Expo team maintaining awesome library :+1:.
Have a good holidays!

**Comment by cruzach** [comment]
`makeUrl` results in the correct url?

What do you have set in your app.json file under the `scheme` key?

**Comment by sasurau4** [comment]
@cruzach 

> makeUrl results in the correct url?

I'll try to add log for `makeUrl`

> What do you have set in your app.json file under the scheme key?

It's like `myapp`. (This is example value because of confidentiality)

**Comment by cruzach** [comment]
@sasurau4 did you ever test `makeUrl`?

Also curious if the url passed into `Linking.addEventListener('url', callback)` has the correct scheme

**Comment by sasurau4** [comment]
@cruzach I confirmed `makeUrl` was correct and same as I set in `scheme` key in `app.json`.

> Also curious if the url passed into Linking.addEventListener('url', callback) has the correct scheme

I don't know, so I'll try it again.

**Comment by cruzach** [comment]
@sasurau4 I tested this in a standalone iOS app and wasn't able to reproduce. 

`await Linking.getInitialURL()` resulted in `myscheme://`

**Comment by sasurau4** [comment]
@cruzach 
I'm sorry for not enough description on the issue.

When linking from custom URL scheme such as `myapp:///path/into/app?hello=world&goodbye=now`, `getInitialURL()` works fine.
When linking from universal link or applinks such as `https://www.myapp.io/records/12345`, `getInitialURL()` returns `exps://www.myapp.io/records/12345` on iOS standalone app.

Your result is correct because it's a custom URL scheme.

**Comment by sbaughman** [comment]
We also are seeing this issue when using universal links with expo 36 and iOS 13.3.

If the app is already open, the scheme of the url provided to `Linking.addEventListener`'s callback is correct, but if the app is closed and is launched by a universal link, the scheme of the received URL is `exps://` instead of the expected `https://`.  We do not see the issue on Android.

**Comment by alexbuicescu** [comment]
@sbaughman nailed the steps, it's the exact same steps for us (expo 36, iOS simulator 13.2)

**Comment by cruzach** [comment]
Okay, I confirmed this with universal links, thanks for specifying! Will try and dig into this

**Comment by giautm** [comment]
I have same isue with sdk 36 on iOS 13
![Uploading 78815838...]()

**Comment by LinusU** [comment]
It seems like this wasn't fixed in SDK 37. Could someone please confirm that the merged patch will be included in SDK 38?

**Comment by cruzach** [comment]
it will go out with sdk 38, the fix landed after sdk 37 was release 👍

**Comment by Kasnady** [comment]
i'm using sdk 39 and hosted those files on my own server.
Now whenever i open the app, it always redirect to my ios-index.json file.
Does anyone also met this issue?
