### ISSUE TITLE
Do I need an active ($99) Apple developer account for iOS build?

### ISSUE THREAD

**Issue by jcalderaio** [expo/expo#661]
Hello.

I built an app for a client (engineering firm), but they don't want the app on the app/google store. They merely want the .apk/.ipa files so that they can distribute them throughout their company by their own means.

I had no problem getting the Android(.apk) file, but am having problems with the Apple(.ipa) file. The first time, I ran "exp build:ios" my problem was 2FA, so I turned it off on my Apple account. Then, I tried again and it said I had invalid credentials. In my Apple Developer Account it says “Your Developer Program Membership has expired”. 

![image](https://user-images.githubusercontent.com/6464473/30703268-35f8f62c-9ebd-11e7-9837-7942bb8384dc.png)

If I go ahead and pay the $99 to renew my apple membership, should the build finally work so I can get my .ipa file? Actually, I will be having my client make their own Apple account so that I can use it. They are a large company, but they don't want to buy the Enterprise Apple account. I'm sure if they merely buy the single Developer account and I get the .ipa file, they can distribute the app throughout the company in the same way without having to buy the Enterprise account, correct?

**Comment by terribleben** [comment]
Hi - `exp build` will codesign your build for the App Store. That is, the `.ipa` we deliver is ready to be submitted to Apple as-is, from whichever account you used during `exp build`.

So to answer your questions:

- Yes, we do require you to have a $99 Apple developer account right now, and
- The binary will already be signed for App Store distribution, but you can probably re-codesign it in some other manual way (e.g. for enterprise distribution) if you have an Apple computer. I haven't tried this myself so I'm not positive.

**Comment by terribleben** [comment]
Btw, we're hoping to leave github limited to bug reports - I'm going to close this but please feel free to open a topic on the [forums](https://forums.expo.io) if you have more questions.

**Comment by terribleben** [comment]
Oops, I see you did open something on the forums. Sorry
