### ISSUE TITLE
[docs] adding my expo app in the share list from another app

### ISSUE THREAD

**Issue by vandrieu** [expo/expo#6611]
I think a procedure is missing in the docs about how to make an expo app appear in the share list of another app, like this:

![yZ68d](https://user-images.githubusercontent.com/46876905/71373635-28fb7600-25b8-11ea-8c32-8b1ef2d4e7c0.png)

It seems this topic is not addressed in the docs. I searched a lot but couldn't find anything about it.

Could you please document how we can achieve this?

Thanks.

**Comment by mskg** [comment]
Not implemented as of today without detaching. Vote for it here https://expo.canny.io/feature-requests/p/share-extension-ios-share-intent-android
