### ISSUE TITLE
[expo-blur] BlurView doesn't update blur

### ISSUE THREAD

**Issue by Dexwell** [expo/expo#6613]
## 🐛 Bug Report 

When positioning a BlurView over dynamic content such as a FlatList, the blur doesn't update when the content behind it changes, such as when scrolling a FlatList. This is a pretty critical bug as BlurViews are mostly used as layers above dynamic content: navigation and tab bars, bottom sheets, video playback UI, etc.

### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/opt/node@10/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.9.0 => 16.9.0 
      react-native: ^0.61.2 => 0.61.2 
    npmGlobalPackages:
      expo-cli: 3.11.3

Target: iOS via bare React Native 

### Steps to Reproduce

1. Position a BlurView on top of other views
2. Scroll or update other views

### Expected Behavior

The BlurView blur updates as content behind it changes, providing context through the intended frosted glass effect

### Actual Behavior

The BlurView keeps the same blur as it had on first render, obscuring content completely

### Reproducible Demo

Try scrolling on iOS. The top BlurView doesn't update https://snack.expo.io/Bks5vj1kL

**Comment by cruzach** [comment]
Thanks for the snack repro! also, you say this is for bare-RN, but it looks like it happens in managed, as well

**Comment by Dexwell** [comment]
Indeed!

**Comment by kitten** [comment]
I haven’t double-checked this in the Snack above yet, but it does seem to work when `tint` isn’t set/passed at all and when `intensity={100}`

**Comment by Dexwell** [comment]
`intensity` should also probably set the blur strength rather than the opacity.

**Comment by kitten** [comment]
Looking at this though, technically I don’t think there is or should be an intensity? https://developer.apple.com/documentation/uikit/uiblureffect/style

From observation there’s only two blue styles that are commonly applied in other Apple apps: dark or light, but there are a lot of modes that extend those two styles.

**Comment by Dexwell** [comment]
I tried removing the `tint` and keeping `intensity={100}` but I don't see the blur update on scroll in the Snack?

You are right about the intensity, however, I believe the ultra thin, thin, default, and thick materials come down to blur strength. Perhaps we need a `material` prop instead?

**Comment by kitten** [comment]
@Dexwell ok, I was wrong `tint` indeed works correctly, what doesn't work is `zIndex`, so the conditions for `BlurView` to work correctly are:

- `intensity` needs to be `100`, since the mixing makes the blur effect look non-native and wonky
- The `BlurView` needs to be located above the views that are to be blurred, so not alongside them, not below them
- The `BlurView` needs to physically be at a higher rendering index, so after the views that are to be blurred, `zIndex` causes rendering issues

That'd explain why it worked for me (ish) and not for you? For reference, here's the modified Snack: https://snack.expo.io/@kitten/blurview-does-not-update

**Comment by Dexwell** [comment]
I see, however even then it doesn't look like a native UIBlurEffect.

**Comment by sjchmiela** [comment]
Hey all,
- thank you @kitten for an easily comprehensible summary of the issue and the solution,
- `intensity` does indeed affect the opacity and nothing else,
- you may change `tint` to `default` to remove the lightish tint,
- what would be the difference between _native UIBlurEffect_ and what you can achieve right now?

**Comment by Dexwell** [comment]
@sjchmiela I believe the UIBlurEffect is usually stronger (and more saturated?); this looks like just a gaussian blur. It would be amazing if the official [styles](https://developer.apple.com/documentation/uikit/uiblureffect/style) could be supported.

**Comment by sjchmiela** [comment]
I think it depends on what style one would use — `expo-blur` [uses `UIBlurEffectStyle{ExtraLight,Light,Dark}`](https://github.com/expo/expo/blob/b8e06d2735ff05ee122efa21de5686c058cd39f7/packages/expo-blur/ios/EXBlur/EXBlurView.m#L10-L16), so it's a 100% native effect.

Yeah, I agree, that would be amazing… 😃 

We'll keep it on our radar. 🙂

**Comment by Dexwell** [comment]
Thanks! It's mostly about using thicker materials (stronger blur) or the system chrome material. And then there are a few additional styles.

**Comment by giuseppeg** [comment]
I have experienced the same issue and came to the same conclusion as @kitten (hi Phil!). The problem I am having though is that I need to offset the ScrollView content so that when its scroll offset is 0 it is not covered by the BlurView. 

I have tried a bunch of things:

1. Set `marginTop` or `paddingTop` on the ScrollView 🛑
2. Add a spacer View before the ScrollView 🛑
3. Set `contentInset`'s top the blur effect works but:
3.1 the initial scroll offset is 0  
3.2 the scroll bar is still behind the BlurView - so I set `scrollIndicatorInsets` but on iPhone X the offset is too much (doesn't align with the contentInset.top)

Ideally I'd love to go for option 1. which is the one that makes the most sense to me.

I looked at https://github.com/react-native-community/react-native-blur and it seems that for Android they can provide a viewRef to the background View (they take a snapshot of it and use it to create the BlurView effect). If something like that was possible for iOS too and expo-blur this would probably solve my issue (also the `zIndex` one).

**Comment by kitten** [comment]
@giuseppeg I’ve basically got full screen FlatLists and Scrollviews so I have a similar use case.
What I’ve done is that I add the BlurViews to the list’s header and footer (as appropriate one or the other)

The I make them sticky and ensure that they’re above the rest of the content on scrolling. To avoid them being non-sticky when reaching the end I apply a `translateY` with reanimated when scrolling past the ends of the list.

For navigation bars having a BlurView I don’t really need to do anything special other than making sure that they’re transparent.

To take safe areas into account I use react-native-safe-area-context and add the safe area insets as padding to the list’s header and/or footer

**Comment by giuseppeg** [comment]
@kitten I am trying to implement a Safari-like browser bar. When I put the BlurView inside of the ScrollView and make it sticky the scrollbar starts at the top of the view: 

![Screen Shot 2020-01-12 at 4 41 15 PM](https://user-images.githubusercontent.com/711311/72221393-9fa5e680-355a-11ea-9035-18025f7362ba.png)

Furthermore when I react the top and pull down the entire ScrollView content bounces, including the BlurView. Ideally I would like to avoid to fix this behavior but is the procedure below how you fixed this?

> The I make them sticky and ensure that they’re above the rest of the content on scrolling. To avoid them being non-sticky when reaching the end I apply a translateY with reanimated when scrolling past the ends of the list.

**Comment by giuseppeg** [comment]
I made some progress :) @kitten what kind of animation/trickery do you use to prevent the sticky element from moving when applying the translation? I am translating of `nativeEvent.contentOffset.y` on `ScrollView.onScroll` when the offset is negative.

<img src="https://user-images.githubusercontent.com/711311/72224658-1c49bc80-357d-11ea-9b36-cfd6b6bf5e40.gif" width="300">

**Comment by kitten** [comment]
@giuseppeg i am as well but don’t forget to reduce the `scrollEventThrottle`

**Comment by arberK** [comment]
> I think it depends on what style one would use — `expo-blur` [uses `UIBlurEffectStyle{ExtraLight,Light,Dark}`](https://github.com/expo/expo/blob/b8e06d2735ff05ee122efa21de5686c058cd39f7/packages/expo-blur/ios/EXBlur/EXBlurView.m#L10-L16), so it's a 100% native effect.
> 
> Yeah, I agree, that would be amazing… 😃
> 
> We'll keep it on our radar. 🙂

Any update on this?

**Comment by RealDyllon** [comment]
@giuseppeg your suggestion was extremely  helpful, thanks!

But flatlist header contains a searchbar, so whenever the search query in the searchbar changes, the entire header reloads, including my searchbar and all. 😬 This makes typing very cumbersome. 

Any idea how to prevent the header component from reloading or refreshing?

**Comment by adallaserra** [comment]
Plus one on this. If you pull down the iOS control center screen (which itself has that nice iOS blur effect) it updates the ScrollView's blur position.... but otherwise nothing. Do we know why this is happening? 🤓

**Comment by silvestreh** [comment]
I was having the same issue as @adallaserra and found a fix: turns out the order in which you render your components matters.

```jsx
<Container>
  <BlurView style={{ height: 300, position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 1 }} />
  <FlatList data={[]} {...otherProps} />
</Container>
```

In the snippet above, even if the `BlurView`'s `zIndex` says it's supposed to be above everything else (and it's rendered like that) the blur effect isn't updated. If you turn around the order like this, it works:


```jsx
<Container>
  <FlatList data={[]} {...otherProps} />
  <BlurView style={{ height: 300, position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 1 }} />
</Container>
```

**Comment by adallaserra** [comment]
@silvestreh omg dude, you're right! Tried this and it worked. Legend 💞

**Comment by RealDyllon** [comment]
@silvestreh thanks mate, it works. 

The expo docs need to be updated.

**Comment by danilo900** [comment]
@silvestreh  AHAHHAHAHAHA .... 

For sure! It really worked! 

Thankssssss

**Comment by brentvatne** [comment]
zIndex in react-native does not map very well to the equivalently named feature on the web, I'd recommend staying away from it where possible

**Comment by silvestreh** [comment]
I don't want to steal @kitten's credit. His comment above says:

> The `BlurView` needs to physically be at a higher rendering index, so after the views that are to be blurred, `zIndex` causes rendering issues

I just put his words into a code snippet to illustrate the issue 😂

**Comment by silvestreh** [comment]
The one place where this is happening and, AFAIK, we have no control over the rendering index is within the `SectionList` component. If you want to return a `BlurView` in `SectionList`'s [`renderSectionHeader`](https://reactnative.dev/docs/sectionlist#rendersectionheader) prop, then you're out of luck.

**Comment by edi** [comment]
Just to clear one thing ... should `intensity` affect the `opacity` ? Because in the official documentation snack, if you set it to `50`, the `BlurView` becomes transparent as well, so you can also see the content underneith.

[https://i.imgur.com/GkIaLno.png](Screenshot here)

Is that expected behaviour ? Web version works as expected though.

**Comment by yolpsoftware** [comment]
Any update on this? BlurView is not really usable for many cases if it does not update.

**Comment by yolpsoftware** [comment]
Oh wow, now it works. Thanks @silvestreh and @kitten.

**Comment by nandorojo** [comment]
> I was having the same issue as @adallaserra and found a fix: turns out the order in which you render your components matters.
> 
> ```js-jsx
> <Container>
>   <BlurView style={{ height: 300, position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 1 }} />
>   <FlatList data={[]} {...otherProps} />
> </Container>
> ```
> 
> In the snippet above, even if the `BlurView`'s `zIndex` says it's supposed to be above everything else (and it's rendered like that) the blur effect isn't updated. If you turn around the order like this, it works:
> 
> ```js-jsx
> <Container>
>   <FlatList data={[]} {...otherProps} />
>   <BlurView style={{ height: 300, position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 1 }} />
> </Container>
> ```

This worked for me, thank you @silvestreh!

**Comment by nandorojo** [comment]
By chance, did anyone solve this when using `BlurView` as a `headerBackground` for @reactnavigation stack? It seems like the header is rendered before the card there, so I'm not sure how to achieve the same effect.

**Comment by silvestreh** [comment]
@nandorojo if you have no control over the rendering index then you're pretty much SOL. The way I've been handling this is by using `{ headerShown: false }` on the `Stack.Screen`'s `screenOptions` prop and making my own header component.

**Comment by OmarG247** [comment]
@silvestreh you're incredible dude 🥳

**Comment by brentvatne** [comment]
this is fixed in sdk 44!

**Comment by stephen-tyro** [comment]
> I was having the same issue as @adallaserra and found a fix: turns out the order in which you render your components matters.
> 
> ```js
> <Container>
>   <BlurView style={{ height: 300, position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 1 }} />
>   <FlatList data={[]} {...otherProps} />
> </Container>
> ```
> 
> In the snippet above, even if the `BlurView`'s `zIndex` says it's supposed to be above everything else (and it's rendered like that) the blur effect isn't updated. If you turn around the order like this, it works:
> 
> ```js
> <Container>
>   <FlatList data={[]} {...otherProps} />
>   <BlurView style={{ height: 300, position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 1 }} />
> </Container>
> ```

I ran into this issue today. I wonder how this solution would effect a11y (mainly screenreaders) if the `BlurView` contains a heading but is ordered below the `FlatList` it's a heading of?

**Comment by griffinbaker12** [comment]
still relevant today, thank you!
