### ISSUE TITLE
Location.startLocationUpdatesAsync() throws error "TaskManager.defineTask() not being called in global scope" after saving changes

### ISSUE THREAD

**Issue by mustaf115** [expo/expo#6619]
<!-- IMPORTANT: Due to the holidays, please expect limited to no response from the Expo Team during the weeks of Christmas and New Year's (from 12/23 to 1/3). Additionally, issue catch-up will likely extend into the week of January 6. Thanks for your patience, we hope you enjoy the holidays, and have a happy New Year! 

### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - C:\Users\musta\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548

Platform Android 9

### Steps to Reproduce

1. TaskManager.defineTask() in App.js outside of component class.
2. Register task with Location.startLocationUpdatesAsync() anywhere (normal or async function or lifecycle method ot useEffect hook).
3. Log gotten results inside Task.

### Expected Behavior

Background task should be started. On every location update there should be logged new locations array containg freshly caught location regardless of app being open or minimized.

### Actual Behavior

**TaskManager.defineTask must be called during initialization phase!** error is logged in the console. If Location.startLocationUpdatesAsync() is called in async function it also throws error in Client as well. Location is checked once or twice per app refresh.

### Reproducible Demo

```javascript
import React, { Component } from 'react';
import { Platform, Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import * as Location from 'expo-location';
import * as Permissions from 'expo-permissions';
import * as TaskManager from 'expo-task-manager';

export default class App extends Component {
  state = {
    location: null,
    errorMessage: null,
  };

  constructor() {
    super();
    this._ensurePermissionGranted();
    this._startLocationUpdates();
  }
  
  _startLocationUpdates = () => {
    Location.startLocationUpdatesAsync('watch', {
      foregroundService: {
        notificationTitle: 'Geotracker',
        notificationBody: 'Tracking enabled'
      }
    });
  }

  _ensurePermissionGranted = () => {
    if (Platform.OS === 'android' && !Constants.isDevice) {
      this.setState({
        errorMessage: 'Oops, this will not work on Sketch in an Android emulator. Try it on your device!',
      });
    }
  }

  render() {
    let text = 'Waiting..';
    if (this.state.errorMessage) {
      text = this.state.errorMessage;
    } else if (this.state.location) {
      text = JSON.stringify(this.state.location);
    }

    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>{text}</Text>
      </View>
    );
  }
}

TaskManager.defineTask('watch', ({ data: { locations = [] }, error }) => {
  if(error) {
    return console.error(error)
  }
  console.log(locations.reverse()[0]);
})

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    textAlign: 'center',
  },
});
```
This code is as simple as it can get to show what exactly is not working. Whole project is fresh out of expo init command and code above is everything App.js consists of.

**Comment by mustaf115** [comment]
Adding new post because of me not noticing that holiday comment

## 🐛 Bug Report

### Environment


  Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - C:\Users\musta\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548


Platform: Android 9, both device and emulator

### Steps to Reproduce



1. TaskManager.defineTask() in App.js outside of component class.
2. Register task with Location.startLocationUpdatesAsync() anywhere (normal or async function or lifecycle method ot useEffect hook).
3. Log gotten results inside Task.


### Expected Behavior



Background task should be started. On every location update there should be logged new locations array containg freshly caught location regardless of app being open or minimized.

### Actual Behavior



**TaskManager.defineTask must be called during initialization phase!** error is logged in the console. If Location.startLocationUpdatesAsync() is called in async function it also throws error in Client as well. Location is checked once or twice per app refresh.

### Reproducible Demo

```javascript
import React, { Component } from 'react';
import { Platform, Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import * as Location from 'expo-location';
import * as Permissions from 'expo-permissions';
import * as TaskManager from 'expo-task-manager';

export default class App extends Component {
  state = {
    location: null,
    errorMessage: null,
  };

  constructor() {
    super();
    this._ensurePermissionGranted();
    this._startLocationUpdates();
  }
  
  _startLocationUpdates = () => {
    Location.startLocationUpdatesAsync('watch', {
      foregroundService: {
        notificationTitle: 'Geotracker',
        notificationBody: 'Tracking enabled'
      }
    });
  }

  _ensurePermissionGranted = async () => {
    let { status } = await Permissions.askAsync(Permissions.LOCATION);
    if (status !== 'granted') {
      this.setState({
        errorMessage: 'Permission to access location was denied',
      });
    }
  }

  render() {
    let text = 'Waiting..';
    if (this.state.errorMessage) {
      text = this.state.errorMessage;
    } else if (this.state.location) {
      text = JSON.stringify(this.state.location);
    }

    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>{text}</Text>
      </View>
    );
  }
}

TaskManager.defineTask('watch', ({ data: { locations = [] }, error }) => {
  if(error) {
    return console.error(error)
  }
  console.log(locations.reverse()[0]);
})

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    textAlign: 'center',
  },
});
```
This code is as simple as it can get to show what exactly is not working. Whole project is fresh out of expo init command and code above is everything App.js consists of.

**Comment by cruzach** [comment]
Hi! I just tested this Android myself, and only saw this error when modifying the code and saving (so my guess is this might have to do with the new Fast Refresh feature?)

Anyways, reloading the experience in the expo client app would fix it, and I saw location updates in the console

**Comment by allberto** [comment]
Can any send a status pleas? or any helpful of how to make it run ?

**Comment by mczernek** [comment]
If that's the issue we think it is, you should be able to reload your app by tapping at the `Reload` button at the bottom of Red Screen.

If this doen't help, let us know.

**Comment by hadpro24** [comment]
> If that's the issue we think it is, you should be able to reload your app by tapping at the `Reload` button at the bottom of Red Screen.
> 
> If this doen't help, let us know.
> 
> Moreover, this should just be logging an error, with no further consequences. We're thinking how to improve it, but there is no due date for it right now.

thanks you. @mczernek
