### ISSUE TITLE
None of the refresh List app examples work on iOS

### ISSUE THREAD

**Issue by kbrandwijk** [expo/expo#662]
I can't get the refresh functionality of RN FlatList working on iOS. At first, I assumed I did something wrong, but then I found this example: https://snack.expo.io/HJYx3Kx4W, which also doesn't work on iOS (10.3).

Both my code, and the example, work find on Android. Also, RN FlatList seems to work on iOS without Expo, although I don't have an app to test that.

**Comment by ide** [comment]
It looks like there are a couple of bugs in that Snack, where did you find it? It shouldn’t next ScrollViews and the list needs to be sized to fill the screen. Right now I bet it is 0px tall.

**Comment by kbrandwijk** [comment]
Oops, I found it using Google, but when I track down its origin, it brings me to this: https://github.com/facebook/react-native/issues/14756, which is actually the issue I was also having, which is a FlatList with refresh functionality inside a ScrollView (well, a UI toolkit component that turns out renders a ScrollView). So this seems to be totally unrelated to Expo, sorry for blaming you for it :see_no_evil:
