### ISSUE TITLE
react-native netinfo library behaving strange in EXPO SDK 36 for IOS

### ISSUE THREAD

**Issue by rahulpawar1989** [expo/expo#6620]
## System Environment:
OS: Windows 10 OS 64 bit CPU: Intel core i7-9700k @ 3.60GHz Memory: 550.87 MB / 16.00 GB

## Platforms:
Issue related in IOS only

## Versions :
 iOS: 13.1.3 
react-native-netinfo: 5.0.0 
react-native: 0.61.4 
expo: 36.0.0

## Description :
In my expo project i need details like ssid , ipAddress of WiFi to which current phone is connected. i followed below procedure as follows :

first step i did npm install --save @react-native-community/netinfo

second step i imported NetInfo from “@react-native-community/netinfo”;

third step i wrote below code
```
NetInfo.fetch().then(state => {
                console.log(“Connection type”, state.type);
                console.log(“Isconnected?”, state.isConnected);
                console.log("Details ", state.detail);
                });
```
following is the output i can see on my terminal

## Output in-case of Android
```
Connection type wifi

Is connected? true
Detail? Object {
    “ipAddress”: “192.169.0.171”,
    “isConnectionExpensive”: false,
    “ssid”: "DM",
    “subnet”: “255.255.255.0”,
}
```
## Output in-case of iOS.
```
Is connected? true
Detail? Object {
    “ipAddress”: “192.169.0.171”,
    “isConnectionExpensive”: false,
    “ssid”: null,
    “subnet”: “255.255.255.0”,
}
```

So if you see in output details i get all the details like ssid, subnet for Android but in case of IOS ssid is always null even after giving location permission in IOS. As i am newbie to react native i don’t understand where did i do mistake because of which i am not getting WiFi ssid. Please give me a solution for the above mentioned problem. I don't want to eject from Expo.

**Comment by zeritte** [comment]
it is a known issue on iOS simulator, see https://github.com/react-native-community/react-native-netinfo/issues/7

**Comment by cruzach** [comment]
@rahulpawar1989 have you tested this on a bare react native project and it works? Otherwise, this probably isn't an issue with the Expo SDK

@zeritte I might be missing something but I couldn't find anything related in that issue

**Comment by rahulpawar1989** [comment]
@cruzach Thanks for the reply. Yes i did test on bare react native sample project using real time device and it is working. Even i posted this question here :
https://forums.expo.io/t/react-native-netinfo-library-not-working/31139/8

**Comment by cruzach** [comment]
Hm I'm having trouble getting netinfo to work properly in a bare react native project 🤔 

my guess is the app just doesn't meet the [requirements](https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo?language=objc#discussion) that netinfo says it needs for ssid -

**Comment by rahulpawar1989** [comment]
yes my app does meet netinfo requirements to access WiFi. Even i posted same question there please check below link.
https://github.com/react-native-community/react-native-netinfo/issues/263

But unfortunately as you can see, developer replied that he doesn't use Expo for developemnt so he don't have idea about that.

**Comment by AbdeenM** [comment]
Hello, 

Am running into the same issue as @rahulpawar1989 , the details object response contains null for SSID, although the location permission is granted for the expo application.
I went through the [requirements](https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo?language=objc#discussion) mentioned by apple on this matter and i believe my app and expo is at least following the first point which core location usage, however it is mentioned at the end (yellow box note) 

> To use this function, an app linked against iOS 12 or later must enable the Access WiFi Information capability in Xcode.

Could this be the issue? if not has it been resolved or is there some sort of workaround? am developing an application and i need to use the SSID that the users device is currently connected too.

Thanks!

**Comment by omer-to** [comment]
Any news on this? I do get the permission for accessing location, however, I am not able to fetch SSID, it always returns false.
I did not add any permission field to my app.json FYI
(it doesn't have the field, so it goes with the default as far as I know)

**Comment by omer-to** [comment]
SSID RETURNS NULL

**Comment by brentvatne** [comment]
@rahulpawar1989 

```
first step i did npm install --save @react-native-community/netinfo

second step i imported NetInfo from “@react-native-community/netinfo”;
```

this will give you a different version of the library. you should install it with `expo install @react-native-community/netinfo`. this will give you the version that is compatible with the expo sdk version you are using.

@omer-to - please create a new issue and follow the issue template including providing a [mcve](https://stackoverflow.com/help/mcve)

**Comment by AbdeenM** [comment]
Hello @brentvatne 
There is no need to open a new. 
The issue me, @rahulpawar1989 and @omer-to are facing are all the same. 
Getting the SSID on iOS using expo is bugged, it always returns null. 
Location permission is granted and netinfo is installed by running expo install @react-native-community/netinfo. That I can confirm. 

So can you please provide us with some information on how to resolve this issue before closing it. 

Thanks

**Comment by AbdeenM** [comment]
I have just opened a new issue. please have a [look](https://github.com/expo/expo/issues/9937)

**Comment by flyskywhy** [comment]
I can get ssid on ios 13.2.3 by:

## 1. [enable the Access WiFi Information Entitlement feature in Xcode](https://medium.com/better-programming/wifi-permission-changes-for-ios-12-1-iphone-x-and-other-devices-c313e24f90ae)

## 2. request location permission

    npm install expo-location@10.0.0
    cd ios
    pod install

Here 10.0.0 use `s.platform       = :ios, '10.0'` in `expo-location/ios/EXLocation.podspec`, that match the `platform :ios, '10.0'` in `YOUR_RN0.63.2_APP/ios/Podfile`, let `pod install` successfully without hacking `EXLocation.podspec`.

And [Configure Info.plist for iOS](https://github.com/expo/expo/tree/master/packages/expo-location#configure-for-ios)

## 3. now will get real ssid after `Location.requestPermissionsAsync()`
```
import {NativeModules} from 'react-native';
import * as Location from 'expo-location';
import NetInfo from "@react-native-community/netinfo";
...
// step 1
await Location.requestPermissionsAsync();
...
// step 2
console.warn(await NativeModules.RNCNetInfo.getCurrentState('wifi')); // now will get the ssid successfully 😆 

// NetInfo.fetch() below will still get ssid null just after install APP until restart APP,
// because NetInfo.fetch() will automatically run and cache the result when init which runs
// before Location.requestPermissionsAsync()
// So use RNCNetInfo.getCurrentState() above instead to get the fresh real ssid
// console.warn(await NetInfo.fetch());
```
