### ISSUE TITLE
I can't compile connect ECONNREFUSED 127.0.0.1:19001

### ISSUE THREAD

**Issue by georgeMorales** [expo/expo#6621]
Hi,
I am having this problem when compiling.
Checking if there is a build in progress ...

Publishing to channel 'default' ...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
Set EXPO_DEBUG = true in your env to view the stack trace.
command: expo build: android -t apk
using expo-cli 3.11.1
sdk 35
A month ago something similar happened to me and I lost the keystore keys, I never put -c flag ... A couple of weeks ago I created my own keystore and I had no problems compiling, although if I am having problems with Google to reset My application with the new keystore, although this is another issue.
The case is today I wanted to compile an .apk to send a review of the facebook app because they cannot open an .aab file and this is the problem that I have encountered.
Help please

**Comment by cruzach** [comment]
Hi! This is actually listed in our [common development errors](https://docs.expo.io/versions/latest/workflow/common-development-errors/#metro-bundler-econnrefused-12700119001), clearing the local state/cache seems to do the trick

**Comment by annie-elequin** [comment]
What do you do when that link doesn't solve the problem? 

I'm on 3.22.3 (just updated) and it seems as if `expo publish` is trying to listen on 19005, when my packager is running on 19006. Not sure how to set the port (already tried removing .expo)

**Comment by brentvatne** [comment]
> What do you do when that link doesn't solve the problem? 
> 
> 
> 
> I'm on 3.22.3 (just updated) and it seems as if `expo publish` is trying to listen on 19005, when my packager is running on 19006. Not sure how to set the port (already tried removing .expo) 

the easiest thing to do is probably to restart your computer and try again
