### ISSUE TITLE
expo publish creates broken build and app crash on launch

### ISSUE THREAD

**Issue by obiwankenoobi** [expo/expo#6622]
### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.1.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.9 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.3

### Expected Behavior
to build working app

### Actual Behavior

trying to publish the app using `expo publish` creates a broken build and when i try to access the app through the expo client I am getting an error saying 

```
 Unhandled JS Exception: Invariant Violation: "main" has not been registered
```
It doesnt say much so I created an APK and tried to run in through android studio to debug it through logcat and there I received the next error when trying opening the app:

```
2019-12-26 20:51:02.709 5432-5505/? E/ReactNativeJS: TypeError: undefined is not an object (evaluating 's(r(d[1])).default.url')
2019-12-26 20:51:02.714 5432-5505/? E/ReactNativeJS: Invariant Violation: "main" has not been registered. This can happen if:
    * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
    * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
2019-12-26 20:51:02.741 5432-5432/? D/AndroidRuntime: Shutting down VM
2019-12-26 20:51:02.742 5432-5432/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mystoree, PID: 5432
    java.lang.RuntimeException: Expo encountered a fatal error: Invariant Violation: "main" has not been registered. This can happen if:
    * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
    * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
        at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
I dont really know what I did there but note that on debug the app works great. Its only crash when creating an apk or trying to publish. I tried to publish older commits that should definitely work but it seems not to work as well..

Thank you!

**Comment by cruzach** [comment]
Could you try running `expo start --no-dev --minify` to run your app in production mode? That might give more details to the problem

**Comment by obiwankenoobi** [comment]
@cruzach unfortunately I did and it runs just fine! I wish I could debug it somehow after building an APK but the error I showed is the only thing I can get. This error look familiar to you?

**Comment by obiwankenoobi** [comment]
## UPDATE: 
So I tried to publish using `expo publish --release-channel staging-v0.0.1` and it worked great. I do have a logic for managing channels that I took from [here](https://docs.expo.io/versions/latest/distribution/release-channels/#using-release-channels-for-environment-variable-configuration) and I believe this is what crashing my app. My logic for managing the channels is: 

```
import Constants from 'expo-constants'

const env = {
  PROD: {
    url:'https://url.com'
  },
  DEV: {
    url:'https://url.com'
  },
  STAGING: {
    url: 'https://url.com'
  }
}

export function getEnvVars(releaseChannel) {
  if (releaseChannel === undefined) return env.DEV
  if (releaseChannel.indexOf('prod') !== -1) return env.PROD
  if (releaseChannel.indexOf('staging') !== -1) return env.STAGING
}


export default getEnvVars(Constants.manifest.releaseChannel)
```

Can you see where could it break maybe?

**Comment by cruzach** [comment]
Did you change anything else besides publishing to a new release?

I don't think there's a problem with `expo publish`, I think this may be a js issue

**Comment by obiwankenoobi** [comment]
@cruzach didnt changed nothing. Simply changed from `expo publish` to  `expo publish --release-channel staging-v0.0.1`. I also suspect its a js issue but how can I debug it when it only shows after I publish the app?  `expo start --no-dev --minify` do not help and creating an apk let you see the errors after its all compiled and nothing really helpful in it. Hmm.. can you maybe see a problem with my environment management function helper? Its on `expo publish`, what it the value of `Constants.manifest.releaseChannel `? This might be the problem

**Comment by cruzach** [comment]
`expo publish` without specifying a release channel will use the `default` release channel, so it looks like you're not handling that option in your function

Also, just changing the release channel in your publish command won't change the release channel of your built apk (that needs to be set when you build it), to get a better idea of how to implement them, see our [release channel docs](https://docs.expo.io/versions/latest/distribution/release-channels/)
