### ISSUE TITLE
No sound for Android push notifications

### ISSUE THREAD

**Issue by NRKirby** [expo/expo#6634]
### Environment

Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

I am running the app on an Android using the QR code in the Metro Bundler

### Steps to Reproduce

- Send a push notification from backend with `ChannelId` and `Default Sound` parameters to app
- Run app with expo on Android and receive push notification for the same `ChannelId`

### Expected Behavior

A sound is made when a push notification is received.

### Actual Behavior

A push notification is received with no sound.

### Reproducible Demo

[Demo repo](https://github.com/NRKirby/PushNotificationExample)

**Comment by cruzach** [comment]
Are you sure you're sending to the `notifications` channel, and your ring volume is turned up? I just tested this with [this snack i made](https://snack.expo.io/@charliecruzan/androidchannel) and sent a notification with the [push tool](https://expo.io/notifications) and it played a sound
