### ISSUE TITLE
Barometer initial value?

### ISSUE THREAD

**Issue by ufoetzzj** [expo/expo#6635]
I am implementing a feature that can detect user's movement such as Jumping or squatting, using **Expo Barometer**. Therefore I need to **record the **initial value of the air pressure when user first open the App**.**

For example, once user open the App, the initial value of the air pressure is 100, if user decide to jump, the air pressure will be decrease, by that I can compare with the initial air pressure to claim that the user just jump. 

However I can't find a way to record the initial value of the air pressure? Anyone knows?

**Comment by cruzach** [comment]
The pressure difference when jumping or squatting (resulting in a height difference of maybe a meter) probably may not be the best way of tracking those events. I suggest using the [accelerometer module](https://docs.expo.io/versions/latest/sdk/accelerometer/)

As a side note, the barometer uses [CMAltimeter](https://developer.apple.com/documentation/coremotion/cmaltimeter) behind the scenes for iOS, which measures the  change in the current altitude, not the absolute altitude
