### ISSUE TITLE
Android UIViewManager illegal operation - either guard in our fork, or reopen the issue upstream

### ISSUE THREAD

**Issue by terribleben** [expo/expo#664]
https://forums.expo.io/t/facebook-login-error-in-android/3248

It looks like the recommended solution is something in native code, which our users can't do themselves, so we should either do this in our fork, or we should convince upstream RN to reopen the issue and fix there.

**Comment by FiberJW** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
