### ISSUE TITLE
Cannot install .ipa on iphone 6 produced by expo build:ios -t staging 

### ISSUE THREAD

**Issue by kopax** [expo/expo#6646]
## Type

- Bug

## Description

I have build an ipa I want to install it with xcode on an iPhone 6

## Reproduction

```bash
expo init #blank
```

```bash
expo build:ios --apple-id ${EXPO_APPLE_ID} -t simulator --release-channel staging --non-interactive`
```

I have downloaded the ipa using:

```bash
curl -o ${CI_BUILD_TAG}-staging.ipa "$(npx expo url:ipa --non-interactive)"
``` 

Connect the iPhone 6 and within XCode, go to `Window > Devices and Simulator`, on the left panel there is the connected iPhone. 

You can drag and drop the `.ipa` file into the `Installed Apps` list.

## Expected

I expect the ipa to install

## Result

instead I have the following error: 

![image](https://user-images.githubusercontent.com/1866564/71608782-f9360a80-2b83-11ea-8051-a78aa376be31.png)

I have never published on the app store and this is my first native app.

- Is it xcode or the ipa, is there a way to solve this?
- Does that mean **my app is broken and won't work on iOS** because locally it used to work but in fact, I was fooled?  (I am a little nervous with the expo client, is there a chance that the distributed ipa is different like this one)

Thanks in advance for advices and sorry if this is not a bug (it look like it),

**Comment by cruzach** [comment]
The file you get from `expo build:ios -t simulator` is not an IPA, it's a tar.gz

We provide directions for installing that onto a simulator [here](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#5-test-it-on-your-device-or). Please make sure you read the documentation thoroughly before opening a github issue 🙂

**Comment by kopax** [comment]
Yes thanks, I have read that part. I wanted to test the real iOS build (and not the OTA) without owning a dev account. I've heard multiple times that we could have a 1-week app certificate for free so we could install our app but in fact, it seems not to be possible.
