### ISSUE TITLE
AsyncStorage not available in RNW 0.12

### ISSUE THREAD

**Issue by Sharathnasa** [expo/expo#6654]
Hi Team,

I'm getting the below mentioned error when i try run application in the web mode. 

/node_modules/expo/build/Notifications/Notifications.js
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' in '/Users/i322865/node_modules/expo/build/Notifications'

I'm using the latest expo(0.36, same error i faced when i was using 0.35 version as well) and react native web 0.12.0-rc.1. Please help to solve this issue and let me know if you require any further details

Regards,
Sharath

**Comment by cruzach** [comment]
Hi! Sorry, but the Notifications module isn't available for web. I'll update the docs to reflect that

Otherwise, hard to say what could be going on here without all the info we ask for in the bug report template. [This snack](https://snack.expo.io/@charliecruzan/groaning-tortilla) uses AsyncStorage on web without an issue, so you might try debugging with it. 

If you still have problems, please provide a full repro

**Comment by jaulz** [comment]
AsyncStorage is deprecated from `0.12`on `react-native-web` and that's causing the issues I think. 
@cruzach why is it not available on web? At least we do have the `.web.js` files [here](https://github.com/expo/expo/tree/master/packages/expo/src/Notifications) and I'm using it without issues.

**Comment by cruzach** [comment]
It's not explicitly supported. We have some code around it, but it's not a full implementation yet

**Comment by jaulz** [comment]
Ah, thanks for the clarification :blush:

**Comment by actuallymentor** [comment]
> It's not explicitly supported. We have some code around it, but it's not a full implementation yet

Even when not importing the `Notification` module I'm getting this error when using `0.12` of `react-native-web`.

**Comment by zeptonaut** [comment]
Yep - I searched my project for "import.*Notification" and nothing came up. I think this might be getting pulled in as a recursive dependency through another file that _is_ web compatible, which is causing the problems.

Are there any guards in place to prevent Notifications from being pulled in as a transitive dependency of web-compatible files?

**Comment by Norfeldt** [comment]
@cruzach are you sure that the bug issue should be marked closed? 
I'm also having the issue

**Comment by shubhamdeol** [comment]
@cruzach  Please reopen this issue, I'm also having the same problem

**Comment by cruzach** [comment]
If you're having this issue, please share a [minimal reproducible demo](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by actuallymentor** [comment]
> If you're having this issue, please share a minimal reproducible demo

I think we've established that the issue arises when people update their `react-native-web` version.

**Comment by younes0** [comment]
@actuallymentor hey! as you know, the deprecated `react-native` `AsyncStorage` is not compatible with `react-native-web` and we can't use https://github.com/react-native-community/async-storage (which has support for web) unless we link (so need to eject), please see: https://github.com/react-native-community/async-storage/pull/317

**Comment by actuallymentor** [comment]
Browsers have [native storage support](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) that should be easy to implement. This is also perhaps relevant for [expo secure storage](https://docs.expo.io/versions/latest/sdk/securestore/) web support.

**Comment by AdityaRanjanSingh** [comment]
I am facing the same issue as well. did you guys find a workaround

**Comment by actuallymentor** [comment]
Note that this is *NOT a secure storage method*, but an unsecure drop-in you could use for non sensitive items:

```
// This is NOT secure storage, just local storage
const { localStorage } = window

const UnsecureStorage = {
	getItemAsync: key => localStorage.getItem( key ),
	setItemAsync: ( key, value ) => localStorage.setItem( key, value ),
	deleteItemAsync: key => localStorage.removeItem( key )
}

export default UnsecureStorage
```

**Comment by cruzach** [comment]
this would be addressed by https://github.com/expo/expo/pull/8315

**Comment by deltamish** [comment]
Still having this issue after installing react-native-community/async-storage
command used: yarn add @react-native-community/async-storage

 web  Failed to compile.
```
D:/Work/Projects/VS/react-native-test/test-pdf-app/node_modules/expo/build/Notifications/Notifications.js
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' in 'D:\Work\Projects\VS\react-native-test\test-pdf-app\node_modules\expo\build\Notifications'
```
Its highly difficult for a newcomer to find the answer as all closed comments led to hopping back and forth between multiple pages with no definitive solution. 
Guess it would be better to have text saying what exactly to do in AsyncStorage doc in some frequently faced problem sub tag.

**Comment by EvanBacon** [comment]
This is fixed in SDK 38
