### ISSUE TITLE
ExpoPermissions.getAsync(Permissions.LOCATION) throwing error on IOS devices

### ISSUE THREAD

**Issue by rahmad-12** [expo/expo#6656]
**Environment**
Expo CLI 3.11.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

App's target is IOS and Android devices.  Issue exists in IOS device only.

### Steps to Reproduce

Issue occurs when following steps are taken:

1. Expo Start in node terminal which opens project on localhost Expo Developer Tools window
2. Change to Production Mode once Metro Bundler finishes loading and receive message, successfully ran `adb reverse`.  Localhost URLs should work on connected Android device.
3. Use Iphone's camera to scan QR Code, which opens the app on Expo.
4.  Go through app's login form which takes me to main user home page.
5.  Error is thrown when trying to render Map due to Expo Permissions error.

**Actual Code that seems to be the root of the problem.**
```
import * as Permissions from "expo-permissions";

//Exported function
export const locateCurrentPosition = () => {
  return getPermission();
};

//Function to see if user provided permission to use location or ask for location.
**getPermission = async () => {
  const { status } = await Permissions.getAsync(Permissions.LOCATION);

  if (status !== "granted") {
    const response = await Permissions.askAsync(Permissions.LOCATION);
  }

  return getCurrentPosition();**
};

//Function to get user's current location
getCurrentPosition = () => {
  return new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(
      position => {
        let currentRegion = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta: 0.015, //Sets the zoom level for X axis
          longitudeDelta: 0.015 //Sets the zoom level for Y axis
        };
        return resolve(currentRegion);
      },
      error => {
        return reject(error.message);
      },
      { enableHighAccuracy: true, timeout: 10000, maximumAge: 1000 }
    );
  });
};
```

### Expected Behavior
For my Map to render, the function above will provide my Location or ask me for my location through my device (ios phone).  Once that location is provided, it goes through the other functions shown above and creates the region required for the maps api. 

### Actual Behavior
The app generates as expected on all devices.  The only difference is the permissions.LOCATION wont work on IOS device due to the error shown in the screenshot below.  

The issue seems to be because of the function from above throwing an error message.
```
**getPermission = async () => {
  const { status } = await Permissions.getAsync(Permissions.LOCATION);

  if (status !== "granted") {
    const response = await Permissions.askAsync(Permissions.LOCATION);
  }

  return getCurrentPosition();**
};
```

![Expo-Permissions-Error](https://user-images.githubusercontent.com/51925836/71674775-27654700-2d4a-11ea-9a7f-37dbf297a45d.png)

I know my code works because before I upgraded my EXPO-Cli, expo and other dependencies, the map generated correctly on IOS devices.  Now, it works only on Android, but this ExpoPermissions.getAsync function isnt working for my Iphone 10 when Im testing.

**My app.JSON**
```
{
  "expo": {
    "name": "myApp",
    "slug": "myApp_v1",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}
```
**My package.JSON file**
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@mapbox/polyline": "^1.1.0",
    "axios": "^0.19.0",
    "connect-flash": "^0.1.1",
    "escape-string-regexp": "^2.0.0",
    "expo": "^36.0.1",
    "expo-constants": "~8.0.0",
    "expo-intent-launcher": "~8.0.0",
    "expo-location": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "mongoose": "^5.8.1",
    "passport": "^0.4.1",
    "passport-local": "^1.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-geocoder-reborn": "^0.8.3",
    "react-native-geolocation": "^1.0.0",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-maps": "0.26.1",
    "react-native-modal": "^11.5.3",
    "react-native-paper": "^3.2.1",
    "react-native-permissions": "^2.0.3",
    "react-native-reanimated": "~1.4.0",
    "react-native-render-html": "^4.1.2",
    "react-native-responsive-screen": "^1.3.0",
    "react-native-searchable-dropdown": "^1.1.1",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-material-bottom-tabs": "^2.1.5",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.5.6",
    "tcomb-form-native": "^0.6.20"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.1.0"
  },
  "private": true
}
```

**Comment by cruzach** [comment]
I tried to repro this with [this snack](https://snack.expo.io/@charliecruzan/issue6656), but didn't have any trouble getting permissions (used the same code block you shared)

You might be having trouble because you're using a newer version of `expo-permissions` than your pinned `expo` sdk version allows. You should use `expo-permission` v7 with SDK 35 

If you install your expo packages with `expo install [package name]`, it'll automatically install the best version of that package for your project

**Comment by rahmad-12** [comment]
Thank you.  That seemed to fix the issue.  I downgraded the version of Expo-permissions from ~8.0.0 to ~7.0.0.  Now my app works as intended on IOS devices.  I get the popup asking for permission to use my location and my map renders.
