### ISSUE TITLE
SDK version 21 - Unable to resolve module '@expo/vector-icons'

### ISSUE THREAD

**Issue by alvinwoon** [expo/expo#666]
Follow all the steps of upgrading. Did't have this problem when upgrading from 19 to 20.

**Comment by alvinwoon** [comment]
Running ' npm install @expo/vector-icons --save-dev' fix the issue. Not sure why.

**Comment by WarHatch** [comment]
`npm install @expo/vector-icons --save-dev` fixed it for me as well. But I don't think this is a reasonable fix .
