### ISSUE TITLE
Module AppRegistry error

### ISSUE THREAD

**Issue by Shair17** [expo/expo#6664]
A few days ago everything was going well, everything was running perfectly and I got this error out of nowhere, and I tried to update all the modules, reinstall expo-cli, delete and install the modules again, however without results.

![Screenshot_2020-01-02-15-30-09-759_host exp exponent](https://user-images.githubusercontent.com/18153674/71707804-924e6680-2dba-11ea-9b1b-46cbeb33be94.jpg)

# Console output
![image](https://user-images.githubusercontent.com/18153674/71707825-b9a53380-2dba-11ea-84db-81993c4ddf09.png)

# Output console logs

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Shair\Desktop\fastly-app\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Shair\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\Users\Shair\AppData\Local\Microsoft\WindowsApps;C:\Users\Shair\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Shair\AppData\Roaming\npm;C:\Users\Shair\AppData\Local\Yarn\bin
9 verbose lifecycle @~start: CWD: C:\Users\Shair\Desktop\fastly-app
10 silly lifecycle @~start: Args: [ '/d /s /c', 'expo start' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `expo start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @
15 verbose cwd C:\Users\Shair\Desktop\fastly-app
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `expo start`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

# My expo diagnostics
![image](https://user-images.githubusercontent.com/18153674/71707816-a2fedc80-2dba-11ea-887e-80d1f3b41a2a.png)

**Comment by Shair17** [comment]
Also here's my:

### app.json

```
{
  "expo": {
    "name": "Fastly",
    "slug": "fastly-app",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "androidStatusBarColor": "#ffffff",
    "androidStatusBar": {
      "barStyle": "dark-content",
      "backgroundColor": "#ffffff"
    },
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "facebookAppId": "2353635448075929",
    "facebookDisplayName": "Fastly",
    "android": {
      "package": "com.shair.fastly"
    }
  }
}
```
### package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "~36.0.0",
    "@expo/vector-icons": "~10.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~36.0.0",
    "expo-asset": "~8.0.0",
    "expo-constants": "^8.0.0",
    "expo-facebook": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-permissions": "^8.0.0",
    "expo-web-browser": "~8.0.0",
    "firebase": "^7.6.1",
    "native-base": "^2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-paper": "^3.4.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-navigation": "~4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-material-bottom-tabs": "^2.1.5",
    "react-navigation-stack": "~1.10.3",
    "react-navigation-tabs": "~2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "~8.0.0",
    "jest-expo": "~36.0.1"
  },
  "private": true
}

```

### App.js
```
/** React bundle */
import React, { Component } from 'react'
import { View } from 'react-native'

import { createStore, combineReducers, applyMiddleware } from 'redux'

import ReduxThunk from 'redux-thunk'

import { Provider } from 'react-redux'

import { Root } from 'native-base'

import * as Font from 'expo-font'

/** Navigation */
import { createAppContainer, createSwitchNavigator } from 'react-navigation'
import { createStackNavigator } from 'react-navigation-stack'
import { createBottomTabNavigator } from 'react-navigation-tabs'

/** Icons: Ionicons */
import { Ionicons } from '@expo/vector-icons'

/** Screens: loading & accounts */
import LoadingScreen from './src/screens/LoadingScreen'
import LoginScreen from './src/screens/LoginScreen'
import RegisterScreen from './src/screens/RegisterScreen'

/** Screens tabs: Trending, Categories, Cart, Location, Profile */
import OffersScreen from './src/screens/OffersScreen'
import CategoriesScreen from './src/screens/CategoriesScreen'
import CartScreen from './src/screens/CartScreen'
import LocationScreen from './src/screens/LocationScreen'
import ProfileScreen from './src/screens/ProfileScreen'

/** Reducers */
import AuthReducers from './src/reducers/AuthReducers'

const AppContainer = createStackNavigator({
    default: createBottomTabNavigator({
      Offers: {
        screen: OffersScreen,
        navigationOptions: {
          tabBarIcon: ({ tintColor }) => <Ionicons name="ios-flash" size={24} color={tintColor} />
        }
      },
      Categories: {
        screen: CategoriesScreen,
        navigationOptions: {
          tabBarIcon: ({ tintColor }) => <Ionicons name="ios-pricetags" size={24} color={tintColor} />
        }
      },
      Cart: {
        screen: CartScreen,
        navigationOptions: {
          tabBarIcon: ({ tintColor }) => (
            <View style={{ backgroundColor: '#E9446A', borderRadius: 100, width: 50, height: 50, marginBottom: 5, alignItems: 'center', justifyContent: 'center', shadowColor: "#454D65", shadowOffset: { width: 0, height: 2, }, shadowOpacity: 0.25, shadowRadius: 3.84, elevation: 5, }}>
              <Ionicons name="ios-cart" size={30} color="#ffffff" />
            </View>
          )
        }
      },
      Location: {
        screen: LocationScreen,
        navigationOptions: {
          tabBarIcon: ({ tintColor }) => <Ionicons name="ios-pin" size={24} color={tintColor} />
        }
      },
      Profile: {
        screen: ProfileScreen,
        navigationOptions: {
          tabBarIcon: ({ tintColor }) => <Ionicons name="ios-person" size={24} color={tintColor} />
        }
      },
    },
    {
      defaultNavigationOptions: {
        tabBarOnPress: ({ navigation, defaultHandler }) => {
          navigation.state.key === 'Cart' ? navigation.navigate('cartModal') : defaultHandler()
        }
      },
      tabBarOptions: {
        activeTintColor: "#161F3D",
        inactiveTintColor: "#B8BBC4",
        showLabel: false,
      },
    },
  ),
  cartModal: {
    screen: CartScreen
  }
},
{
  mode: 'modal',
  headerMode: 'none',
  // initialRouteName: 'cartModal',
})

const AuthStack = createStackNavigator({
  Login: LoginScreen,
  Register: RegisterScreen,
})

const AppInit = createAppContainer(
  createSwitchNavigator({
    Loading: LoadingScreen,
    App: AppContainer,
    Auth: AuthStack,
  },
  {
    initialRouteName: 'Loading'
  })
)

/** Creando store: auth => para almacenar el login del usuario. */

const rootReducer = combineReducers({
  auth: AuthReducers,
})

const store = createStore(rootReducer, applyMiddleware(ReduxThunk))

/** */

export default class App extends Component {
  constructor(props) {
    super(props)
  }

  componentDidMount() {
    this.loadElements()
  }
  async loadElements() {
    await Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
    })
  }

  render() {
    return (
      <Provider store={store}>
        <Root>
          <AppInit />
        </Root>
      </Provider>
    )
  }
}
```

**Comment by cruzach** [comment]
Hi! This error message usually indicates an error in your js code. We talk about it a little more in our [list of common development errors](https://docs.expo.io/versions/latest/workflow/common-development-errors/#module-appregistry-is-not-a-registered-callable). I suggest trying the solutions there, and maybe searching around our forums and github to see what the root cause was in other people's case, which may help in debugging your project 😄 

Barring any of that, going through the [device logs](https://docs.expo.io/versions/latest/workflow/logging/#view-logs-from-android-device-or-emulator) may help to illuminate what's going wrong

**Comment by Shair17** [comment]
@cruzach I tried run `expo start --no-dev --minify`, however i got same error 😕
