### ISSUE TITLE
android 5.1.1 and simulator, WebView error on SDK36 and Exponent_2.14

### ISSUE THREAD

**Issue by Magrider** [expo/expo#6665]
Expo CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

Android: real device: V5.1.1, simulator(nox): V5.1.1500190725
expo Client: 2.14.0
SDK: 36
error happen on expo client and standalone android

note: webview working fine on SDK 35 and **expo client 2.13** only, 2.14 will shows String resource ID #0x2040003 on real device.

### Steps to Reproduce

1. expo upgrade
2. change WebView from 'react-native' to 'react-native-WebView'
2. yarn start
3. enter Webview Page, error happen

### Expected Behavior

It should render a webview page.

### Actual Behavior

On my android simulator(nox), which is android V5.1.1500190725, it will shows 
net::ERR_CACHE_MISS.  
I found this open issue on react-native-webview, 
https://github.com/react-native-community/react-native-webview/issues/1101
and still waiting reply.
Then I tried to run on my real device, the error becomes String resource ID #0x2040003

![IMG_20200103_103038](https://user-images.githubusercontent.com/7843546/71706583-dbd19c80-2e20-11ea-9592-5d38499507ea.jpg)
![IMG_20200103_103108](https://user-images.githubusercontent.com/7843546/71706584-dbd19c80-2e20-11ea-8e70-7850a5f5e3d9.jpg)

After I search the 0x2040003 error on google, it seems like this is a common issue on android V5.1.1 with context, however for some reasons, I have to use V5.1.1. 

I downgrade my sdk to 35, and it shows same error, until I reinstall expo client 2.13, WebView works fine.

### Reproducible Demo

` <WebView
                    source={{
                        uri: 'google.com',
                    }}
                    onNavigationStateChange={this.onNavigationStateChange}
                    startInLoadingState
                    // scalesPageToFit
                    javaScriptEnabled
                    style={{ flex: 1, paddingTop: StatusBar.currentHeight }}
                />`

Thank you!

**Comment by cruzach** [comment]
Can you try this in a bare react native project? If the same error occurs there, then this is probably an issue specific to `react-native-webview`, and not Expo

**Comment by Magrider** [comment]
> Can you try this in a bare react native project? If the same error occurs there, then this is probably an issue specific to `react-native-webview`, and not Expo

Hi Cruzach,
I just made a bare react native project and it works fine on both Simulator and real device. 
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-webview": "^8.0.2"
  },

Thanks!

**Comment by mikailcetinkaya** [comment]
same problem , any advice ? 
Any work Around ?

**Comment by cruzach** [comment]
Tested this myself on more recent versions of Android and WebView seems to be working fine. So this looks to only affect Android 5? although I'm not sure why

**Comment by Magrider** [comment]
> Tested this myself on more recent versions of Android and WebView seems to be working fine. So this looks to only affect Android 5? although I'm not sure why

Hi Cruzach,
Definitely this issue happen on android 5.1(or 5?), I found 2 same issues on stackoverflow:
https://stackoverflow.com/questions/46810118/exception-on-new-webview-on-lollipop-5-1-devices
https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview
any idea? Thanks for your help

**Comment by cruzach** [comment]
Looks like this was an upstream Android issue, which is [solved in `androidx.appcompat:appcompat:1.2.0`](https://issuetracker.google.com/issues/141351441#comment35), currently [we still use 1.1.0](https://github.com/expo/expo/blob/199ffb41abe30e1869a2b43ffff492399cac7c02/android/app/build.gradle#L119)

**Comment by npedrini** [comment]
It looks like 1.2.0 came out of alpha yesterday. Any ideas when this will be folded into Expo? 

https://developer.android.com/jetpack/androidx/releases/core

**Comment by 026binit** [comment]
looking for the solution

**Comment by kamalpandey** [comment]
+1

**Comment by 026binit** [comment]
still looking for solutions

**Comment by JerryBels** [comment]
Still not resolved.

**Comment by brentvatne** [comment]
@JerryBels - you need to provide more information than that. are you using the latest sdk? we updated androidx.appcompat to 1.2.0 already, so as far as i can tell this is an upstream android issue

**Comment by JerryBels** [comment]
With pleasure :)

```
Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.21390
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

For the webview:

```
    "react-native-webview": "11.6.2",
```

Ran it on an Android 5.1, and got the following error : 

```
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 115,
  "title": "Page Web non disponible",
  "url": "https://google.com",
}
at node_modules\react-native\Libraries\LogBox\LogBox.js:117:10 in registerWarning
at node_modules\react-native\Libraries\LogBox\LogBox.js:63:8 in warnImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
at node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
at node_modules\react-native-webview\lib\WebView.android.js:146:12 in _this.getWebViewHandle
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:265:4 in invokeGuardedCallbackImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:476:2 in invokeGuardedCallback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:500:2 in invokeGuardedCallbackAndCatchFirstError
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:597:41 in executeDispatch
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:621:19 in executeDispatchesInOrder
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2521:28 in executeDispatchesAndRelease
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:838:4 in forEachAccumulated
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2546:20 in runEventsInBatch
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2702:18 in runExtractedPluginEventsInBatch
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2639:35 in batchedUpdates$argument_0
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17712:13 in batchedUpdates$1
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2492:29 in batchedUpdates
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2638:16 in _receiveRootNodeIDEvent
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2713:25 in receiveEvent
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
```

The app works perfectly on a few phones running Android 10/11, and on an emulator running Android 9. If there are more checks you wish me to perform, I will gladly.

**Comment by brentvatne** [comment]
@JerryBels - based on https://github.com/react-native-webview/react-native-webview/issues/1101 this seems to still be an upstream issue in react-native-webview

**Comment by JerryBels** [comment]
@brentvatne Okay so we need to wait for react-native-webview to do something (after more than 2 years?) ... I guess I will inform the client that Android 5.x can't be maintained.

**Comment by brentvatne** [comment]
closing because it looks like the related issue is closed on react-native-webview. also, with EAS Build you can use any version of react-native-webview that you like (although only the version supported by the SDK version that you are using will work inside of Expo Go)

**Comment by NoobMahbub** [comment]
I was facing the same error and here is how I fixed this issue

1. Restarted my android device

2. Removed the https:// from the url
https://techhelpbd.com/gitdown was throwing this error when I removed https:// then it worked fine.

```jsx
import * as React from 'react';
import { WebView } from 'react-native-webview';

export default function Browser() {
  return (
    <WebView
      source={{ uri: 'techhelpbd.com/gitdown' }}
    />
  );
}
```
