### ISSUE TITLE
Blank Screen appears when navigate to another StackNavigator in the DrawerNavigator.

### ISSUE THREAD

**Issue by hsk-kr** [expo/expo#6669]
Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832

+ Snack

Android

### Steps to Reproduce

Here is the [code](https://snack.expo.io/@hanseongkuk/f7bf08) that has implemented in snack

### Expected Behavior

Success to navigate.

### Actual Behavior

It appears the initialRoute screen successfully at the first. but when I navigate to another screen by DrawerNavigator, It appears a blank screen. 
and then when I go back to screen that is initialRoute, It appears a screen. 

When It's on the blank page If I press the menu or home button and then come back to the app, It works without any problems.  

I implemented it in snack and check it out.
I ran it on my device and on Appetize.io and I found it out that they've had the same problem.

I may've used it in a wrong way, because I'm beginner in react native. 
thank you for reading it and I'll be waiting for your answer. 
Happy New Year!

here is the same [question](https://stackoverflow.com/questions/59573407/why-do-i-get-a-blank-screen-after-using-drawer-navigator-in-react-native-to-navi) in stackoverflow.

### Reproducible Demo

Here is the [code](https://snack.expo.io/@hanseongkuk/f7bf08) that has implemented in snack

**Comment by cruzach** [comment]
Hm that's odd, works fine on web and ios

Have you tried this in a bare react native project?

**Comment by hsk-kr** [comment]
Thank you for answering. 
It's moved to react-navigation repo.
