### ISSUE TITLE
 const store = Expo.SecureStore returns undefined for sdk 21

### ISSUE THREAD

**Issue by alvinwoon** [expo/expo#667]

**Comment by alvinwoon** [comment]
Also blog post https://blog.expo.io/expo-sdk-21-0-0-is-now-available-be33b79921b7 stated getValueAsync. It should be getItemAsync (as per doc).

**Comment by ide** [comment]
Thanks - updated the release notes.

Expo.SecureStore has a getter right here - https://github.com/expo/expo-sdk/blob/master/src/Expo.js#L192. Can you debug further?

**Comment by ide** [comment]
Closing this since SecureStore is working for several people with SDK 22+.
