### ISSUE TITLE
ViewPagerAndroid App crash following SDK 36 upgrade 

### ISSUE THREAD

**Issue by apswak** [expo/expo#6671]
### Environment

  Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
      Watchman: 4.9.4 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.11.3

Android

### Steps to Reproduce

Previously on Expo SDK 34, following an `expo upgrade` to SDK36, I get an error

### Expected Behavior

App to work.

### Actual Behavior

Get the following error and app crashes:

ViewPagerAndroid has been removed from React Native. It can now be installed and imported from 'react-native-viewpager' instead of 'react-native'. See https://github.com/react-native-community/react-native-viewpager
- node_modules/react-native/Libraries/react-native/react-native-implementation.js:451:8 in Object.defineProperty$argument_2.get
* http://192.168.1.140:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:142832:48 in render
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:13042:21 in finishClassComponent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:12970:4 in updateClassComponent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20488:8 in beginWork$$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19370:24 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19347:39 in workLoopSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18997:22 in renderRoot
* [native code]:null in renderRoot
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18709:28 in runRootCallback
* [native code]:null in runRootCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
- node_modules/scheduler/cjs/scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18556:30 in scheduleUpdateOnFiber
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:7799:17 in classComponentUpdater.enqueueSetState
- node_modules/react/cjs/react.development.js:325:31 in Component.prototype.setState
- node_modules/react-redux/lib/components/connectAdvanced.js:219:15 in onStateChange
* [native code]:null in onStateChange
- node_modules/redux/lib/redux.js:219:10 in dispatch
- node_modules/react-navigation-redux-helpers/src/middleware.js:38:21 in <anonymous>
* http://192.168.1.140:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:433308:45 in <unknown>
* src/pages/Auth/Login/index.js:117:8 in LoginScreen#fetchAllUserData
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:145:19 in Promise.resolve.then$argument_0
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

I've tried to upgrade only to SDK 35 by selecting NO on "Would you like to update to the latest version, 36.0.0?" but the "Choose a SDK version to upgrade to:" arrow prompt doesn't work, So am unsure whether it's an issue from 34-35 or 35-36.

Any help/advice appreciated - I've done a project wide search (including node modules) for react-native-viewpager which is what seems to be the issue in the logs but there's no sign of it, so pretty lost

**Comment by apswak** [comment]
Turns out this issue is because the react-native version aligned with SDK36 isn't compatible with react-navigation < 4.

Solved it by following instructions here: https://github.com/react-navigation/react-navigation/releases?after=v4.0.4
Scroll down to 4.0.0 migration tips

**Comment by shubhamkackar** [comment]
@apswak i upgraded from react-native 0.5x to 0.6x and simultaneously updated my react-navigation from 3.x to 4.x 

Have faced a lot of issues ever since and have solved all of them till this point but stuck on this one. I went through the link that you posted and have already implemented that, however i am still stuck with the issue. Can you please tell me fixing what exactly did the job for you?

**Comment by shubhamkackar** [comment]
> @apswak i upgraded from react-native 0.5x to 0.6x and simultaneously updated my react-navigation from 3.x to 4.x
> 
> Have faced a lot of issues ever since and have solved all of them till this point but stuck on this one. I went through the link that you posted and have already implemented that, however i am still stuck with the issue. Can you please tell me fixing what exactly did the job for you?


Never mind. Found the solution to my problem. I am using react-native-swiper and that was using ViewPagerAndroid. Found the solution here 
https://github.com/leecade/react-native-swiper/issues/1108

**Comment by valerija432** [comment]
Still have the same error. I'm not using react-native-swiper. 
I am using expo version 36 and "react-navigation": "4.0.10". Any solution???

**Comment by lpitteloud** [comment]
@valerija432 Did you find any solution to this problem ? I am experiencing the same thing lately after upgrading SDK 35 to 36...

**Comment by mfy5013** [comment]
same problem

**Comment by sungsong88** [comment]
I was having the same issue. Turns out, it was the react-native-swiper that had a similar issue. After updating both plugins, I'm good now.

**Comment by nanobap** [comment]
@adipascu same problem, do you find any solutions?
