### ISSUE TITLE
[expo-in-app-purchases] connectAsync()  undefined is not an object only Android

### ISSUE THREAD

**Issue by userhus** [expo/expo#6673]
I get an undefined error when I call the connectAsync () function on an Android device.  I do not receive this error on iOS devices.

I've tried publishing the app in Android and test and alpha environments, but the error persists and I can't connect to PlayStore.

What could be the reason ?

![image](https://user-images.githubusercontent.com/11156343/71766688-904beb00-2f13-11ea-96dd-f9c51a91f292.png)

**Comment by esamelson** [comment]
Hey @userhus -- unfortunately it's really hard for us to have enough information to help you out with your issue if you don't fill out the template we provide 😞 I just tried to reproduce this and was unable to with the code you provided. Could you please open a new issue and fill out the template fully, including a minimal and verifiable reproducible example (ideally either a snack or a small GH repo)? Thanks!

**Comment by manhquyen** [comment]
same error plz help
