### ISSUE TITLE
entryPoint value in app.json creates an error in IOS Simulator

### ISSUE THREAD

**Issue by genechan** [expo/expo#6676]
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.17 
      @types/react-native: ~0.60.23 => 0.60.27 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.3

### Steps to Reproduce
move App.tsx to a different folder and set that folder in app.json entryPoint setting.

### Expected Behavior
to run

### Actual Behavior
error message

### Reproducible Demo
pull this repo
https://github.com/genechan/expo-entrypoint-bug.git

**Comment by esamelson** [comment]
Hey there @genechan ! Under the hood the root entryPoint for Expo projects is actually `node_modules/expo/AppEntry.js`, which imports from App.js in the root folder. This allows Expo to run a few necessary side effects to get your app to load properly, without you having to worry about them. The downside is that Expo depends on App.js/tsx being located in the root folder. You can work around this either by leaving `entryPoint` unset, keeping App.tsx in the root and having itimport from a different file in `src/` (easiest), or replicating the functionality of `node_modules/expo/AppEntry.js` in your custom `entryPoint`. Hope that helps!

**Comment by genechan** [comment]
Thank you for the help @esamelson, it is appreciated.
Just a fyi I was just playing around to see if I can get react-native-web to run with expo and having create-react-app running the webserver so I can run cypress.io to tests with it. Saddly create-react-app wants to run everything under ` src/ `.
I will try your suggestion. Best Regards. Gene

**Comment by EvanBacon** [comment]
The problem here is that react-native and react-native-web require the root component to be registered with `AppRegistry`. By pointing to a raw component you are skipping this step. You can recreate this effect with the following:

```tsx
import 'expo/build/Expo.fx';
import registerRootComponent from 'expo/build/launch/registerRootComponent';
import { activateKeepAwake } from 'expo-keep-awake';

if (__DEV__) {
  activateKeepAwake();
}

function App() {
  /* Your component */
}

registerRootComponent(App);
```

**Some quick notes for future reference**
- `app.json`'s `appEntry` takes the highest priority for entry-point resolution when using `expo-cli`. 
- `import 'expo/build/Expo.fx';` is used for assets and dev-tools, very important that you have this at the top of your custom entry point or you'll hit weird errors.
