### ISSUE TITLE
[expo-module-scripts] Missing eslint universe config dependency

### ISSUE THREAD

**Issue by nandorojo** [expo/expo#6677]
## Issue

When using `expo-module-scripts`, I'm getting this error in VSCode:

ESLint: Failed to load config "universe/native" to extend from. Referenced from: /Users/Fernando/Developer/expo-gatsby-navigation/.eslintrc.js. Please see the 'ESLint' output channel for details.

Eslint isn't working altogether in this folder on VSCode.

Here's my **.eslintrc.js** file:
```es6
// @generated by expo-module-scripts
module.exports = require('expo-module-scripts/eslintrc.base.js');
```

## Solution
```sh
yarn add --dev eslint-config-universe
```
This solves it. Maybe `eslint-config-universe` is missing from `expo-module-scripts` dependencies?

## Example repo

https://github.com/nandorojo/expo-navigation-core

**Comment by esamelson** [comment]
Thanks for catching this @nandorojo ! Any chance you'd be willing to open a PR adding this missing dependency?

**Comment by nandorojo** [comment]
Sure thing! I just added PR #6690
