### ISSUE TITLE
Is calling useScreens still desirable in the App component in SDK36?

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#6678]
In SDK35 I called useScreens() above my App component like this:

```javascript
import { useScreens } from 'react-native-screens';

useScreens();

const App = (props) => {
  ...
}
```

Truth be told, I didn't know what it did, I just knew the Expo documentation asked us to do this if we're using react-navigation in our apps. In SDK36 this breaks navigation and makes the screens look cut off on either side. Is it still desirable to use this function?

**Comment by esamelson** [comment]
Hey @shamilovtim -- unfortunately it's really hard for us to have enough information to help you out with your issue if you don't fill out the template we provide 😞 I just tried to reproduce this and was unable to with the code you provided. Could you please open a new issue and fill out the template fully, including a minimal and verifiable reproducible example (ideally either a snack or a small GH repo)? Thanks!

**Comment by shamilovtim** [comment]
@esamelson Hey, I only opened this for the useScreens question. I understand that I'd need to provide an example for help debugging but is it possible to get clarification on whether we're using this anymore?

**Comment by AndersonSchmidt** [comment]
The useScreens() method makes react-native use the native screens component from the OS. Fragment on Android and UIVIewController on IOS. It improves performance. But this is noticeable only in large applications.

**Comment by OscarYuen** [comment]
I encounter this issue in SDK36

**Comment by OscarYuen** [comment]
2.0.0-alpha.12 still breaks the navigation
