### ISSUE TITLE
IOS store IDFA problem (advertising)

### ISSUE THREAD

**Issue by flieks** [expo/expo#668]
Hi guys,

I'm at the last step in the apple store and get this:
`Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.`

I’m not using facebook Ads…
I can just see some FacebookAds in flow-typed/npm/expo_vx.x.x.js

**Comment by adierkens** [comment]
https://docs.expo.io/versions/latest/guides/building-standalone-apps.html

> Note: When submitting to the iTunes Store, you’ll be asked whether your app uses the advertising identifier (IDFA). Because Expo depends on Segment Analytics, the answer is yes, and you’ll need to check a couple boxes on the Apple submission form. See [Segment’s Guide](https://segment.com/docs/sources/mobile/ios/quickstart/#step-5-submitting-to-the-app-store) for which specific boxes to fill in.

From [Segment’s Guide](https://segment.com/docs/sources/mobile/ios/quickstart/#step-5-submitting-to-the-app-store)
> you’ll want to check the following three boxes:
> 1. “Attribute this app installation to a previously served advertisement”
> 2. “Attribute an action taken within this app to a previously served advertisement”
> 3. “I, YOUR_NAME, confirm that this app, and any third party…”
>  
> Note, you should not check the box labeled “Serve advertisements within the app” unless you are actually going to display ads.

**Comment by ide** [comment]
@adierkens’s answer here is right. Thanks for helping out!

**Comment by flieks** [comment]
Thanks alot. Indeed that fixed it
https://forums.expo.io/t/how-to-build-for-ios-apple-store-account/3233/9

**Comment by jpca999** [comment]
Were you able to have your App available in the App store after these choosing these options?

**Comment by flieks** [comment]
@jpca999 yes
