### ISSUE TITLE
App Crash for Viewpager

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo#6687]
Viewpager android has been removed from react-native.

![Screenshot_2019-12-31-16-31-26-06_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/51107138/71619600-2a95f100-2beb-11ea-9808-e66159debcbe.png)

**Comment by brentvatne** [comment]
you will need to update to a newer version of react-navigation, the version you're using in your app still uses ViewPager from react-native

**Comment by valerija-mobidonia** [comment]
> you will need to update to a newer version of react-navigation, the version you're using in your app still uses ViewPager from react-native

I am using "react-navigation": "4.0.3" and still have this issue. Any solution?
