### ISSUE TITLE
iOS RN autolinking in bare workflow does not work after expo init

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#6689]
### Environment

```
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: yarn install v0.21.3
[1/4] Resolving packages...
success Already up-to-date.
$ jetify
Jetifier found 1135 file(s) to forward-jetify. Using 12 workers...
Done in 1.24s. - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.4 => 0.61.5
    npmGlobalPackages:
      expo-cli: 3.11.3
```

### Expected Behavior

Documentation for RN 0.61.4 everywhere specifies that native modules are autolinked by RN automatically. Using a brand new project with `expo init` there is no autolinking setup. In [RN docs](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) it says that autolinking comes from a `native_modules.rb` file and there is no call to this file from a brand new Podfile created from expo init.

### Actual Behavior

Expected RN autolinking to work out of the box after `expo init`.

### Reproducible Demo

1. `expo init` a bare workflow project
2. `yarn install` a new module such as https://github.com/JuanSeBestia/react-native-wifi-reborn
3. `cd ios && pod install`
4. the module is not autolinked. the Podfile has no autolinking code in it.

**Comment by brentvatne** [comment]
you can opt-in to using it by using whatever setup instructions are provided for it upstream. we should probably add it to the bare workflow projects by default though!

**Comment by shamilovtim** [comment]
@brentvatne thanks for the heads up 💯 . i think it would be great to have a huge disclaimer in the CLI for now, if possible

**Comment by shamilovtim** [comment]
(or at least in the docs somewhere)

**Comment by shamilovtim** [comment]
One thing I forgot to mention is that the RN CLI gives the following warning / error:

```bash
⟩ react-native run-ios
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
  - react-native-reanimated (to unlink run: "react-native unlink react-native-reanimated")
  - react-native-screens (to unlink run: "react-native unlink react-native-screens")
  - react-native-wifi-reborn (to unlink run: "react-native unlink react-native-wifi-reborn")
```

This contradicts the initial configuration on a new bare expo (and RN?) project which is a bit confusing. The RN docs also heavily imply that the autolinking requires no config and should work out of the box which doesn't help the confusion.

**Comment by brentvatne** [comment]
i added this now so new bare projects will use autolinking. if you want to add it to an existing project you can copy the changes from this commit https://github.com/expo/expo/commit/b8e06d2735ff05ee122efa21de5686c058cd39f7
