### ISSUE TITLE
Version mismatch with Expo 21.x.x & React Native

### ISSUE THREAD

**Issue by ShMcK** [expo/expo#669]
I've experienced a version mismatch issue when upgrading to Expo 21. It seems Expo requires the yet unpublished "react-native" 0.48.4. Although 0.48.4 is released, RN 0.48.3 is currently the latest NPM release.

If anyone else comes across the same version mismatch issue, here is a temporary fix in your "package.json".

```json
{
  "dependencies": {
   "react-native": "git://github.com/facebook/react-native#v0.48.4"
  }
}
```

Hoping this saves someone some time.

**Comment by acomito** [comment]
@ShMcK what errors were you getting?

**Comment by ShMcK** [comment]
I was getting the following error, before updating to 0.48.4.

```
scrollview has no proptype for native prop RCTScrollView.overScrollMode of native type string if you haven't changed this prop yourself this usually means that your versions of the native code and javascript code are out of sync
```

**Comment by ShMcK** [comment]
No longer issue with the NPM release of 0.48.4.

**Comment by terribleben** [comment]
Just for posterity, Expo uses a fork, so `expo/react-native#sdk-21.0.2` should be sufficient. Let us know if that wasn't working for you for some reason.

**Comment by ShMcK** [comment]
At the time, I was using 21.0.1.

**Comment by jpca999** [comment]
@terribleben  I got similar issue -   https://github.com/expo/expo/issues/679
