### ISSUE TITLE
How to configure extensions ?

### ISSUE THREAD

**Issue by kopax** [expo/expo#6692]
I am trying to install jest-expo-enzyme.

I do not get what should be the extensions for testing just for the web.

I tought this name was OK: `history-test.test.js`, but it does not pick the test.
https://github.com/expo/expo/tree/master/packages/jest-expo-enzyme#extensions

I found strange (if not ugly) to use a dash within the suffix instead of a dot. I am doing things properly?

`history.-test.web.test.js`

     FAIL   Android  src/store/tests/history.-test.web.test.js
     FAIL   iOS  src/store/tests/history.-test.web.test.js

I do rather not use dash, is there a way to configure this properly?

Thanks and best!

**Comment by kopax** [comment]
I have found that it work, but you need to have have ugly name such as : 

```
history.-test.web.test.js
```

I do rather not use dash, is there a way to configure this?

**Comment by kopax** [comment]
I've tried many extensions and couldn't found how to configure it properly to get it run in it's proper env. I had to uninstall since it was unusable. 

For the record, I have moved the whole part of my jest within `package.json` and did the following `jest.config.js`:

```jsx
const { withEnzyme } = require('jest-expo-enzyme');

module.exports = {
  "preset": "jest-expo-enzyme",
  "testURL": "http://localhost",
  "moduleNameMapper": {
    "\\.svg": "<rootDir>/__mocks__/svgMock.js"
  },
  "testPathIgnorePatterns": [
    "/test.js"
  ],
  "transformIgnorePatterns": [
    "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules-*|sentry-expo|native-base)"
  ],
  "coverageThreshold": {
    "global": {
      "statements": 0,
      "branches": 0,
      "functions": 0,
      "lines": 0
    }
  },
  "coveragePathIgnorePatterns": [
    "/node_modules/",
    "/web",
    "/web-build/",
    "/public",
    "/coverage",
    "/stylguide",
    "src/testUtils/*",
    "webpack.config.js",
    "package.json",
    "package-lock.json",
    "styleguide.config.js",
    "metro.config.js",
    "react-native.config.js",
    "jest.config.js"
  ],
  "collectCoverage": true,
  "collectCoverageFrom": [
    "**/*.{js,jsx}",
    "!**/coverage/**",
    "!**/node_modules/**",
    "!**/babel.config.js",
    "!**/jest.setup.js"
  ],
  "testResultsProcessor": "jest-sonar-reporter",
  projects: [
    // Skipping Node because we want to test DOM presets only
    withEnzyme(require('jest-expo/ios/jest-preset')),
    withEnzyme(require('jest-expo/android/jest-preset')),
    // The Enzyme support added to web is different from that added to native, which `withEnzyme` handles
    // Luckily you won't have to do anything special because it reads the platform from
    // `haste.defaultPlatform` of the provided Jest config
    withEnzyme(require('jest-expo/web/jest-preset')),
  ],
};
```

Extensions weren't respecting the filtering

```jsx
history-test.web.js # not picked up by jest
```

Only file ending with `.test.js` were picked up, so I did:

```
history-test.web.test.js
```

But then it was running for the 3 envs. Thanks in advance if someone can enlight me.

**Comment by brentvatne** [comment]
the jest docs explain the options for this and their defaults:
- https://jestjs.io/docs/en/configuration#testregex-string--arraystring
- https://jestjs.io/docs/en/configuration#testmatch-arraystring

as for why tests run on multiple platforms, see https://blog.expo.io/testing-universal-react-native-apps-with-jest-and-expo-113b4bf9cc44 for more info.

you can clone and run this to see a very basic example (without enzyme though): https://github.com/brentvatne/hello-world-jest-expo-universal

**Comment by EvanBacon** [comment]
Just ran this locally and it works. 
```diff
- history-test.test.js

- history-test.web.js
```

I also tried running `App.test.web.js` which works as expected (runs web-only).
