### ISSUE TITLE
expo-google-app-auth Module : With android build, account.google.com page keep reopening

### ISSUE THREAD

**Issue by morwalz** [expo/expo#6696]
### Environment
SDK 36
I am using expo-google-app-auth for login with google. It is working fine with expo client. But when i created android app there seems to be issue. it open up in app broswer and show accounts to select from. After selecting it go back to same screen. 1 out 5 times it work and redirect to app. 

### Steps to Reproduce
use expo-google-app-auth to login with google. Create an android build, then try to login with google. 
Then this can be reproduced. 

### Expected Behavior
After selecting account, it should redirect to app. 

### Actual Behavior

It does not redirect to app with with access_token, rather it keep reloading.

**Comment by cruzach** [comment]
Make sure you've followed the [directions for using this module in a standalone android app](https://docs.expo.io/versions/latest/sdk/google/#deploying-to-a-standalone-app-on-android), and please share a reproducible demo

**Comment by EvanBacon** [comment]
underlying error/duplicate https://github.com/expo/expo/issues/5615. Will fix in #7450
