### ISSUE TITLE
WebView has been removed from React Native.

### ISSUE THREAD

**Issue by jm4r7in** [expo/expo#6697]
### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/bin/npm
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.0.8 => 3.0.8 
    npmGlobalPackages:
      expo-cli: 3.11.3

### Steps to Reproduce

I migrated my app from SDK Version 31 to SDK Version 36, and I have the error : 

> Invariant Violation: WebView has been removed from React Native.

Whereas I don't use WebView.

Here is my package.json 

`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^36.0.0",
    "expo-av": "~8.0.0",
    "expo-document-picker": "~8.0.0",
    "expo-localization": "~8.0.0",
    "i18n-js": "^3.2.1",
    "lodash": "^4.17.11",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-keyboard": "^2.0.1",
    "react-native-paper": "^2.12.0",
    "react-native-slider": "^0.11.0",
    "react-native-sound": "^0.10.9",
    "react-native-svg": "9.13.3",
    "react-native-webview": "7.4.3",
    "react-navigation": "^3.0.8",
    "victory-native": "^31.0.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.0.0"
  },
  "private": true
}`

Thank you.

**Comment by cruzach** [comment]
You're probably importing it somewhere in your code (or one of your dependencies could be?)

You do have `react-native-webview` already installed, according to your package.json, so I would double-check through your project that you're not using `import { WebView } from 'react-native'` anywhere

If you provide a demo (preferably a snack) that I can use to reproduce this error, I'm happy to reopen the issue

**Comment by jm4r7in** [comment]
@cruzach Thank you for your answer.
I search in all the files, and I don't have any line `import { WebView } from 'react-native'`
It also seems that the dependencies also don't import it, but how can I check it to be sure ?

**Comment by jrrcdev** [comment]
Same problem here, expo 36, already did everything I can think.

![image](https://user-images.githubusercontent.com/19454127/75238559-fb8d9d00-579f-11ea-877e-100b9d347e04.png)

**Comment by princefishthrower** [comment]
Not sure why this is closed... does anyone have a solution or idea? I grepped my whole node_modules, and no uses of webview from 'react-native' are used

**Comment by abenain** [comment]
Same issue here after upgrading my project to expo 36

**Comment by abenain** [comment]
In my case (incrementally upgrading a project from expo 33 to expo 36), deleting node_modules folder + package-lock.json and npm install did suppress this error

**Comment by jrrcdev** [comment]
I upgraded from 35 to 36, downgrade back to 35 was the only solution that works.

**Comment by zorosun** [comment]
I have the same issue here upgrading from expo 33 to expo 36...

**Comment by abenain** [comment]
@zorosun upgrading an expo project is quite a bit of a journey, I had to upgrade several other dependencies, including react-navigation to v4, but I was able to do it eventually. 

Make sure you delete your package-lock.json, node_modules folder and metro cache before node re-installing

Hope it works for you

**Comment by cleanDev-win** [comment]
![Screenshot_2020-03-18-06-49-23](https://user-images.githubusercontent.com/52365167/76953527-841ed980-6917-11ea-81c7-5a9b4096cce3.png)
Now I am facing to same problems after upgrading expo to 36. 
Please let me know solutions. Thanks.

**Comment by cleanDev-win** [comment]
I made the pure expo 36 project and run that. But I could not see this issue.
Only updating to 36, I see this error.
So I thought there might be 2 reasons of this issue.
1. There might be unknown library which work with webview. When updating, those library does not update together.
2. There might be issue on updating to 36 operation.

I`d really appreciate if anyone let me know the reason and the way how to solve it.

**Comment by abenain** [comment]
Did you try deleting both your node_module folder and package-lock.json
while updating to expo 36?

**Comment by cleanDev-win** [comment]
Sure.

**Comment by faria** [comment]
I am upgrading a managed project from 35 to 36. I deleted node_modules and package-lock.json. I changed the one place in my code where I import WebView. I also upgraded React Navigation to the 4.x series.  But when I run expo start -c, I still get: Invariant Violation: WebView has been removed from React Native.   Any ideas?  My package.json has: "react-native-webview": "7.4.3"

**Comment by rosnaib11** [comment]
Same issue

**Comment by brentvatne** [comment]
hi there! please create a new issue and follow the issue template if you are having some issue. webview has been moved to react-native-webview and you can install that as described here https://docs.expo.io/versions/latest/sdk/webview/
