### ISSUE TITLE
Permissions on experience basis

### ISSUE THREAD

**Issue by sonaye** [expo/expo#67]
I think there is a need to implement push notification permissions on experience basis. I just received a push notification from an app that i know nothing about, probably opened it while randomly browsing projects a while ago.

Maybe you can add the slug of the app to the push token `ExponentPushToken[key][slug]` and then from the exponent client we can toggle/remove slug subscriptions. not sure if your backend can handle this, meaning tokens lookup and filtering, or maybe broadcasting later on.

Same goes for geolocation, since it can work in the background as well, a privacy matter, there should be a way to enforce using `Exponent.Location`, and that module can do the checkup similar to push notifications, is it possible to disable `navigator`?

**Comment by sonaye** [comment]
An example:

![img_4902](https://cloud.githubusercontent.com/assets/23000873/23338371/36350900-fc1a-11e6-9139-4a2566690b9f.PNG)

**Comment by jesseruder** [comment]
Yes, this is something we're planning on adding! We're also planning on making `navigator.geolocation` use our location module that is scoped per experience.

**Comment by sonaye** [comment]
any timeline on that @jesseruder?

**Comment by sonaye** [comment]
I am closing this one, as this issue doesn't affect standalone builds.
