### ISSUE TITLE
takePictureAsync Base64 encoding performing slowly

### ISSUE THREAD

**Issue by gianlazz** [expo/expo#670]
When running the function below it takes a very long time to log the base64 results and only seems to work sometimes. Is there something I'm missing?

```
takePicture = async function() {

  this.refs.modal1.open()

  if (this.camera) {
    this.camera.takePictureAsync({
      base64: true,
    }).then(data => {
            console.log(data.base64);
             });
      }
    };
```

I just updated from version 20 -> 21
Here's from my package.json
```
  "dependencies": {
    "@expo/samples": "^2.0.2",
    "axios": "^0.16.2",
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-native-button": "^2.1.0",
    "react-native-modalbox": "^1.4.2",
    "react-navigation": "^1.0.0-beta.12"
  },
```

**Edit**
Adding the argument `quality: 0.1,` seems to have about halved the time of base64 encoding output execution from ~10 seconds to ~5. Also, this may just partially be poor performance from my particular device I'm running this from, though when I ran the 3rd party "react-native-camera" with a detached project and output a base64 encoding from its capture method it only took about ~1 second on the same device... What could be causing this performance discrepancy?

**Comment by aalices** [comment]
I'll take a look. What do you mean by `only seems to work sometimes` ?

**Comment by skevy** [comment]
This seems like normal behavior to me -- if you're base64 encoding the image, and then sending a multi-MB image across the bridge, and _then_ logging the image to the console, I'd expect that to take a very long time and be suboptimal. Avoiding logging is the right call here, and in the future, you can use the Blob module (which is a WIP) to avoid base64 encoding the data at all, and keep the image data living on the native side.

**Comment by nikki93** [comment]
Closing because seems resolved? Logging an entire base64 encoding of an image would indeed be slow.

**Comment by ebrugulec** [comment]
Did you find a solution? I need a answer this question. @gianlazz
