### ISSUE TITLE
Error with Facebook login

### ISSUE THREAD

**Issue by jenil** [expo/expo#671]
I recently updated to Expo v21 and the Facebook login doesn't work anymore, the login popup comes and then I get an error.

```
const {
      type,
      token
    } = await Expo.Facebook.logInWithReadPermissionsAsync('appId', {
      permissions: ['public_profile', 'email', 'user_birthday']
```

![image](https://user-images.githubusercontent.com/971411/30779297-f91cb748-a0ba-11e7-8d0f-0a8ac67496bb.png)

**Comment by charlesvinette** [comment]
Hi @jenil ! Sorry it took a little while to get back to you. I just built a small toy app to test out the module. I used this exact same call as you and everything is going smoothly on my side.

Would you be available to give me some more information? Are you running it as Standalone/Detached or in Expo Client?

**Comment by jenil** [comment]
I was using the Expo client, it worked fine on 20. I haven't touched that code after that day, so have no update if it is working or no as of today.

**Comment by charlesvinette** [comment]
Okok, and you updated your project to 21 using the steps described in the release post (Exposition21) ?

**Comment by charlesvinette** [comment]
I'll close this one as there are no other reported cases and I was successfully able to make this example work in Expo Client on sdk 21. If you are still having problem feel free to ping me directly on Expo's Slack. Thanks!

**Comment by manoj-nama** [comment]
Hey guys, not sure if this is some intermittent issue, but I've also started facing this, for the past week. I continued development by using `behaviour: 'native'` (_it opened a separate browser window and was working_), but after a recent update to XDE/Expo app this has started giving error that only `web` is supported in the Expo Client. 

Now I'm stuck with nothing else that I can do to overcome this. I'm using Expo v22.0.2 SDK.

**Comment by manoj-nama** [comment]
#### A gif to express my pain.

![facebookloginerror](https://user-images.githubusercontent.com/4013897/33369317-28408444-d51a-11e7-9236-c37a08772b31.gif)

**Comment by sachabest** [comment]
Same issue as @jenil, started today. Expo FB Login window opens then closes immediately - debug/stack trace is useless/not informative. No code changes since it was working. Expo version `21.0.2`. /cc @deveshd95

**Comment by nirpeled** [comment]
I'm having a similar issue, connect with a Facebook no longer works for my production app that uses Expo 19 (detached), the development version that uses Expo 22 doesn't work as well, seems like that Expo is using an old version of Facebook's SDK that is probably using an old version of Graph API... what can I do?

**Comment by nikki93** [comment]
Hey @manoj-nama, @sachabest and @nirpeled -- each of these seem to be different issues or different information, even though they are all generally about "Facebook login not working."

Could each of you make a new issue on the repo for your particular issue and include as much details as possible? This will enable us to have separate conversations with you about each one.

Also meanwhile just to make sure, the instructions at https://docs.expo.io/versions/latest/sdk/facebook.html#registering-your-app-with-facebook explain how to set a bunch of configuration that you need to make sure of on the side to make sure Facebook login works properly, including some config on the FB developer site, additional config in app.json for a iOS standalone apps, and some key hash stuff for Android standalone apps.

**Comment by thibault12** [comment]
Hi,
I am currently experiencing some issues with the FB login of my app. Before the update the login was working fine but now the only behaviour that works is 'web'. Is anyone else experiencing this? And does anyone know a fix or has more info about this or the new update?

**Comment by manoj-nama** [comment]
@thibault12 Well basically MY problem was simply due to network. My office network blocked some of the scripts that the `facebook` login popup loaded. Switching to other network resolved this issue. Not sure if you are facing the same issue, but worth a try.
