### ISSUE TITLE
Bare workflow or only unimodules?

### ISSUE THREAD

**Issue by wolrd** [expo/expo#6711]
Hi there,
 
1. I do not understand the difference between using a Bare workflow and an empty project with https://github.com/unimodules/react-native-unimodules. But if I use the Bare workflow, then the expo is installed.
But why is it being installed?
2. I need to use web support. Does Expo use fork https://github.com/necolas/react-native-web or not?

**Comment by wolrd** [comment]
3. Does Bare Workflow use the expo wrapper like Manage Workflow or not?

**Comment by cruzach** [comment]
The bare workflow templates already have unimodules configured to make it simple and easy to get unimodules working in your project fast. For more details about managed vs bare, read [these docs](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/)

Expo does have web support! We are still adding more to this and generally making it better, but definitely encourage you to try it out. If you want to learn more, there are a few posts about Expo for web on our [blog](https://blog.expo.io/)

**Comment by wolrd** [comment]
@cruzach 
I know about the difference between bare and manage workflow. I have another question.

When I install the bare workflow, the expo SDK is installed. But if you install the unimodules separately, then there is no expo SDK. Why do I need an expo SDK in the bare workflow?

```
 "dependencies": {
    "expo": "~36.0.0",
    ...
}
```

**Comment by cruzach** [comment]
Bare template projects contain the `expo` package so that you can run your bare project in the Expo Client, and on web. (with a couple limitations, like blocking off any of your custom native code)

added in this PR https://github.com/expo/expo/pull/5055

**Comment by wolrd** [comment]
@cruzach what is Expo Client? Is it a mobile app with a QR code?

And will the app be without a wrapper when I build the app to .apk?

**Comment by cruzach** [comment]
The [expo client](https://expo.io/tools#client) allows you to run/test your app without having to build binaries

Correct, the bare app will not have the Expo Client shell when you build your apk

**Comment by wolrd** [comment]
@cruzach thank you! 

"with a couple limitations, like blocking off any of your custom native code" - can I use expo modules like an expo-camera?

**Comment by cruzach** [comment]
Yes, most expo modules are, for the most part, compatible with both bare and the managed workflow- see [here](https://docs.expo.io/versions/v36.0.0/bare/unimodules-full-list/) for a full list

`expo-camera` is supported in both 😄 And our goal is to provide support for all of them this year, resulting in feature parity between bare and managed workflows

For web you'll need to refer to the docs of the specific module, and it will say whether it works on web or which methods can/can't be used on web

**Comment by wolrd** [comment]
@cruzach thanks :) I mean expo-camera for expo client with a bare workflow :)
