### ISSUE TITLE
Document Directory & Files Aren't Readable

### ISSUE THREAD

**Issue by ALEEF02** [expo/expo#6715]
### Environment

Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

Currently on iOS, haven't tried it on Android yet

### Steps to Reproduce

Import `expo-file-system`
Get `documentDirectory`, `readAsStringAsync`, `writeAsStringAsync`, and `makeDirectoryAsync`
Try to read or write any file or directory in `documentDirectory`

### Expected Behavior

Return read file in the callback

### Actual Behavior

`Error: File 'path here' isn't readable.`

![image](https://user-images.githubusercontent.com/12904259/72016456-aa8a0f80-3218-11ea-97a0-16d2d9d1ff4d.png)
![image](https://user-images.githubusercontent.com/12904259/72016512-c42b5700-3218-11ea-92b4-790ced97e7a7.png)

### Reproducible Demo
[https://expo.io/@aleef02/BulletinMagExpo](https://expo.io/@aleef02/BulletinMagExpo)
[https://github.com/ALEEF02/Bulletin-Magazine-Mobile-App](https://expo.io/@aleef02/BulletinMagExpo)

**Comment by ALEEF02** [comment]
I just did more debugging to find out that I don't have access to the entire document directory. Running
```js
import * as FileSystem from 'expo-file-system';
const {
	documentDirectory,
	getInfoAsync
} = FileSystem
const storagePath = `${documentDirectory}`
const { exist, md5 } = await getInfoAsync(storagePath, { md5: true });
console.log("Exists: " + exist + " md5: " + md5);
```
returns: `Exists: undefined md5: undefined`
Any ideas why I have no access to the filesystem?

**Comment by cruzach** [comment]
You probably do have access to the document directory, your destructuring just has a typo

`exist` should be `exists`, and I believe `md5` only works on files, not directories, according to the docs. Try running [this snack](https://snack.expo.io/@charliecruzan/bossy-peanut), and it should work

As for the original issue regarding files not being readable, could you share a minimal repro via a snack? It would be much easier to debug and help

**Comment by ALEEF02** [comment]
@cruzach I can't get the repo to upload into a snack. The repo is located at https://github.com/ALEEF02/Bulletin-Magazine-Mobile-App
![image](https://user-images.githubusercontent.com/12904259/72175529-3626ac00-3391-11ea-8751-df233f8d852e.png)

**Comment by ALEEF02** [comment]
Also, just making a snack doesn't work because expo-file-system isn't available on the web
![image](https://user-images.githubusercontent.com/12904259/72176049-70dd1400-3392-11ea-8946-8943826c72ee.png)
https://snack.expo.io/@aleef02/049589

**Comment by ALEEF02** [comment]
I found the issue. Using `encodeURI` for some reason shortens `file:///var/mobile/Containers/Data/Application/E8DEE3B9-1E3B-44CA-8D0F-FBDAF450A771/Documents/ExponentExperienceData/%2540aleef02%252FBulletinMagExpo/` 
to
`file:///var/mobile/Containers/Data/Application/E8DEE3B9-1E3B-44CA-8D0F-FBDAF450A771/Documents/ExponentExperienceData/%252540aleef02%25252FBulletinMagExpo/pdf-testpdf.html` 
https://github.com/ALEEF02/Bulletin-Magazine-Mobile-App/commit/f2a4b7b13a70b12754408a509d133d77c92a7315
