### ISSUE TITLE
Why i getting Deprecated API Usage message from AppStore.

### ISSUE THREAD

**Issue by alicancelik** [expo/expo#6719]
### UIWebView error for expo 33

I am using Expo 33 and never use UIWebView for this project. I think expo-facebook did that but i am not sure a hundred percent. Can someone help me  ? 

they are my dependecies ; 

   "@expo/samples": "~3.0.0",
    "@expo/vector-icons": "^10.0.1",
    "@react-native-community/netinfo": "~2.0.10",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "axios": "^0.19.0",
    "eslint-plugin-babel": "^5.3.0",
    "expo": "^33.0.0",
    "expo-asset": "^5.0.0",
    "expo-constants": "^5.0.0",
    "expo-facebook": "~5.0.1",
    "expo-font": "^5.0.0",
    "expo-google-app-auth": "^7.0.0",
    "expo-google-sign-in": "~5.0.1",
    "expo-image-picker": "^5.0.2",
    "expo-localization": "^5.0.1",
    "expo-permissions": "^5.0.1",
    "expo-web-browser": "^5.0.0",
    "i18n": "^0.8.3",
    "i18n-js": "^3.2.1",
    "moment": "^2.24.0",
    "native-base": "^2.13.4",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-actionsheet": "^2.4.2",
    "react-native-camera": "^3.9.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-gifted-chat": "^0.11.0",
    "react-native-image-progress": "^1.1.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-modal": "^11.4.0",
    "react-native-picker-select": "^6.3.3",
    "react-native-progress": "^4.0.2",
    "react-native-render-html": "^4.1.2",
    "react-native-responsive-screen": "^1.3.0",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-swipe-list-view": "^2.0.6",
    "react-native-swiper-flatlist": "^2.0.2",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0",
    "react-navigation-transitions": "^1.0.12",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "remote-redux-devtools": "^0.5.16",
    "sharp-cli": "^1.10.0",
    "socket.io-client": "^2.3.0"

![Screen Shot 2020-01-09 at 11 33 16](https://user-images.githubusercontent.com/26031105/72051845-0f0aa480-32d5-11ea-8a4b-a8f4fabd1e4e.png)

**Comment by awinograd** [comment]
https://forums.expo.io/t/received-mail-from-apple-about-the-deprecated-api-uiwebview/27117

**Comment by cruzach** [comment]
This should be resolved via https://github.com/expo/expo/pull/6593 and will be released with SDK 37
