### ISSUE TITLE
Share does not work consistently with both url / image and message in iOS

### ISSUE THREAD

**Issue by ryanphung** [expo/expo#6720]
### Environment

```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      npm: 6.11.3 - ~/.nvm/versions/node/v8.13.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.4.1
```

Target: iOS

#### Scenario 1:

Sharing both a url and a message:

```
import { Share } from 'react-native';
...

await Share.share({
  url: 'http://www.google.com',
  message: 'Test message'
});
```

#### Scenario 2:

Sharing a Base64 encoded image in the url and a message:

```
import { Share } from 'react-native';
...

function convertBlobToBase64 (blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader;
    reader.onerror = reject;
    reader.onload = () => {
        resolve(reader.result);
    };
    reader.readAsDataURL(blob);
  })
}

async function shareImage({ message, url }) {
  const r = await fetch(url)
  const blob = await r.blob();
  const base64image = await convertBlobToBase64(blob)
  console.log(base64image)
  return await Share.share({
    url: base64image,
    message
  });
}

await shareImage({
  message: 'Text',
  url: 'https://images.unsplash.com/photo-1554173341-e3cfe8b0cbbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80'
})
```

When the app run, in the share dialog, try out 3 apps:
- iMessage
- WhatsApp
- Facebook

### Expected Behavior

Scenario 1: both URL and Message should appear
Scenario 2: both Image and Message should appear

### Actual Behavior

Sharing | iMessage | Email | WhatsApp | Facebook
------------ | ------------- | ------------- | ------------- | -------------
URL + Message | ✅| ✅| ✅| ❌only URL
Image + Message | ✅| ✅| ❌only Message | ❌only Image

### Reproducible Demo

Link to Expo Snack: https://snack.expo.io/@ryan.phung/bug-report---expo-share-image

But you'll probably need to run this on a device where you have other messenger apps installed.

**Comment by cruzach** [comment]
Hi! Have you tested this on a bare react native project already, and if you did, did it work consistently there? Just asking since Share is from the `react-native` package, so if it's not working in the bare workflow either, it's probably better to open an issue in the RN repo

**Comment by ryanphung** [comment]
@cruzach thanks for your comment. I will try out in a bare react native project.

I looked through the documentation of `expo-sharing`; seems like it only supports sharing of URL, without a message?

**Comment by cruzach** [comment]
Ah yeah, you're right. Sorry I didn't notice/mention that

**Comment by MehmetKaplan** [comment]
@ryanphung could you have solved this problem?

**Comment by seamoss** [comment]
> @ryanphung could you have solved this problem?

It has not been solved.

**Comment by ryanphung** [comment]
> @ryanphung could you have solved this problem?

@MehmetKaplan no I just live with it for now as it's not a deal breaker for my app.

**Comment by kesylo** [comment]
@MehmetKaplan @ryanphung  this is a  real issue for my app. how can i proceed

**Comment by MehmetKaplan** [comment]
> @MehmetKaplan @ryanphung this is a real issue for my app. how can i proceed

Unfortunately I also kept it as it was.
