### ISSUE TITLE
[AppAuth] app crashes when providing response_mode in additional parameters

### ISSUE THREAD

**Issue by jurisjansons** [expo/expo#6721]
## 🐛 Bug Report

Can't add `response_mode` in `additionalParameters` for AppAuth configuration, tested on Android.

### Environment

Expo CLI 3.11.3 environment info:
System:
OS: Windows 10
Binaries:
npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.5.0.0 AI-191.8026.42.35.6010548

### Steps to Reproduce

Take example from expo.io documentation page about AppAuth and add: additonalParameters: { response_mode: "form_post" } and try to authenticate. form_post can be replaced with any other value

### Expected Behavior

To create request to issuer with `response_mode` parameter provided in additionalParameters

### Actual Behavior

App crashes

### Reproducible Demo

You can see the same behavior in this [snack](https://snack.expo.io/@aihen/app-auth-crash2).

**Comment by EvanBacon** [comment]
Can confirm that this will be fixed in #7450

**Comment by EvanBacon** [comment]
Can confirm that this can be done with the new AuthSession API which will replace `expo-app-auth`.
