### ISSUE TITLE
Expo web not resolving react-native-web when working with monorepo

### ISSUE THREAD

**Issue by renanmav** [expo/expo#6723]
### Environment

```
 Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.5.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
```

I’m working with expo web.

### Steps to Reproduce

1. Create a project using expo cli
2. Adapt it to use yarn workspaces (read [this](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces))
3. Follow the [instructions to run the project on the browser](https://docs.expo.io/versions/v33.0.0/introduction/running-in-the-browser/)
4. Try to run it with `expo start --web`

### Expected Behavior

Expo should resolve react-native-web without nohoisting.

### Actual Behavior

When I try to run it, I get the following error:
```
 web  Failed to compile.
/Users/renan/expo/animavita/packages/expo/node_modules/expo/build/Notifications/Notifications.js
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' in '/Users/renan/expo/animavita/packages/expo/node_modules/expo/build/Notifications'
```

### Reproducible Demo

https://github.com/renanmav/expo-web-monorepo-repro

**Comment by cruzach** [comment]
See this issue -> https://github.com/necolas/react-native-web/issues/1515

It's not a problem with `expo-yarn-workspaces`, you need to use `react-native-web` v0.11. Just tested in your repo with that change, and it works 👍

**Comment by getcodestaff** [comment]
Is this a bug? I am receiving this error when I try to launch expo web:

 ERROR in ./node_modules/rn-round-checkbox/RoundCheckbox.js 9:19
Module parse failed: Unexpected token (9:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export default class RoundCheckbox extends React.PureComponent {
>   static propTypes = {
|     onValueChange: PropTypes.func,
|     icon: PropTypes.string,
 @ ./screens/signin/index.js 1:702-747
 @ ./navigation/index.js
 @ ./App.js
 @ ./node_modules/expo/AppEntry.js
 @ multi ./web-build/register-service-worker.js ./node_modules/expo/AppEntry.js
ℹ ｢wdm｣: Failed to compile.
