### ISSUE TITLE
Significantly different ImageManipulator compression results on iOS vs Android.

### ISSUE THREAD

**Issue by GollyJer** [expo/expo#6726]
_**I'm never sure where to post things (here vs forum) so I'm doing both this time because this seems like a potentially major issue.**_
[crosspost](https://forums.expo.io/t/significantly-different-imagemanipulator-compression-results-on-ios-vs-android/31953)

Please provide the following:
1. SDK Version: 36
2. Platforms: Android/iOS

I'm using the follow code to do "full compression" on an image.
```javascript
  const convertedImage = await ImageManipulator.manipulateAsync(uri, [], {
    format: ImageManipulator.SaveFormat.JPEG,
    compress: 0,
  });
```

After running the exact same code on the exact same image, copied to each device, these are the resulting sizes. (in bits)

Android
`size: 72753` 

iOS
`size: 2670519`

These are order of magnitude differences and we get this same disparity at other compression levels. We're hoping to do some compression on the client side to keep server traffic down but it won't be possible with this big an inconsistency.

Is this expected or did I find a bug?

Thanks!
Jeremy

**Comment by cruzach** [comment]
Hi! thanks for the report, but it's usually best to include a snack that reproduces the behavior

I tried to put one together - https://snack.expo.io/@charliecruzan/excited-pretzels - but I'm not seeing a large difference in file size on Android vs iOS

**Comment by GollyJer** [comment]
@cruzach I spent a few hours putting together a repro because I couldn't believe what I was seeing. I wanted to be sure.
Here's the snack: [ImageManipulator Compression](https://snack.expo.io/@gollyjer/imagemanipulator-compression)
You can pick the compression level and then press "Compress Puppy". It always starts with the original image when compressing and then shows the results below.

There are pretty big differences between iOS and Android.

![image](https://user-images.githubusercontent.com/689204/73026708-ca0f6380-3de6-11ea-8f35-04904b028b30.png) ![image](https://user-images.githubusercontent.com/689204/73026472-540afc80-3de6-11ea-9168-3206a9b545fb.png)

### But more curious... you're going to see that the images gets larger when the compression quality gets to 0.5 on iOS and 0.8 on Android.
I must be missing something. Or this is pretty big bug.

Hope this helps! I'd love to get this figured out.

Best,
Jeremy

**Comment by GollyJer** [comment]
One last data point... added ability to choose the file type.
PNG always results in the same large file regardless of compression quality.
![image](https://user-images.githubusercontent.com/689204/73040465-9c3e1500-3e0e-11ea-9062-70d755cc4dc3.png)

**Comment by wodin** [comment]
> @cruzach One last data point... added ability to choose the file type.
> PNG always results in the same large file regardless of compression quality.

I don't know what's going on with the JPEG compression, but converting a random JPEG to PNG is expected to increase the size.

**Comment by GollyJer** [comment]
@wodin You're right... I see PNG can be bigger than the original because is stores pixels instead of blocks (basically). 👍

This definitely doesn't explain why JPEGs are getting bigger at different compression levels.

**Comment by wodin** [comment]
@GollyJer PNG is a lossless compression algorithm whereas JPEG is lossy, so PNGs cannot be compressed as small as JPEGs.

Your image is 5000px x 5000px and each pixel in a PNG is potentially 4 bytes (one each for R, G, B and A), unless you're using indexed mode, which you're unlikely to be if just converting a JPEG to PNG. So if you store that uncompressed it will be about 95MB. And that's exactly what you get if you convert the image to a Windows BMP file.

```
-rw-r--r--  1 michael  wheel    95M Jan 26 08:18 puppy.bmp
```

I agree that I am a bit surprised about the size increase in the JPEG case and also the discrepancy that you're seeing between Android and iOS. I have not tested on iOS, but I do see the same results as you see on Android.

But I think what's going on is that the image in memory is basically 95MB and the the compression algorithms are just less efficient at different compression levels. So it's probably not really that the size is increasing at 0.8, but rather that it's a bit less efficient when you feed in that value than if you feed in 1 or 0.9 etc. I don't know enough about JPEG compression to know why that might be though.

I've just tried compressing the image with the GIMP with the following results:

```
-rw-r--r--  1 michael  wheel   302K Jan 26 08:29 puppy00.jpg
-rw-r--r--  1 michael  wheel   440K Jan 26 08:30 puppy01.jpg
-rw-r--r--  1 michael  wheel   598K Jan 26 08:30 puppy02.jpg
-rw-r--r--  1 michael  wheel   786K Jan 26 08:30 puppy03.jpg
-rw-r--r--  1 michael  wheel   844K Jan 26 08:31 puppy04.jpg
-rw-r--r--  1 michael  wheel   1.2M Jan 26 08:31 puppy05.jpg
-rw-r--r--  1 michael  wheel   1.3M Jan 26 08:32 puppy06.jpg
-rw-r--r--  1 michael  wheel   1.5M Jan 26 08:32 puppy07.jpg
-rw-r--r--  1 michael  wheel   1.6M Jan 26 08:32 puppy08.jpg
-rw-r--r--  1 michael  wheel   1.9M Jan 26 08:32 puppy09.jpg
-rw-r--r--  1 michael  wheel   5.0M Jan 26 08:33 puppy10.jpg
```

So at least with the GIMP I don't see the same sort of thing, but I didn't try with e.g. 85%.

**Comment by btroia** [comment]
I can confirm this same behavior is happening on iOS. Basically, if compression settings are below 0.5 the final image will see some compression, but if compression settings are >= 0.5, the resulting image size **_increases_**.
![puppies](https://user-images.githubusercontent.com/368747/73135834-e690e300-4014-11ea-8587-c9025209a890.jpg)

**Comment by sd** [comment]
Leaving a comment here for those, like us, who find this issue while searching for ways to compress images.

There is no bug in compression levels. The "original" image used as a reference is already compressed at around 50% quality, so the "original file size" of 1.37MB is not what you should use to compare results. 

@wodin tried to make this point, but not directly.

Graphics compression is over the raw bitmap data, not whatever file already had that bitmap in compressed form.

If you open the original file with any graphics app and save it as a 100% JPEG you get a file of about 4MB more or less. And the uncompressed bitmap is 95MB. So the only thing you can learn from this is that perhaps the phone compression algorithms are not as efficient as photoshop or gimp, but they are fairly good nonethless.

**Comment by GollyJer** [comment]
@sd 
It's hard for me to agree with your assessment.
To focus the conversation let's talk only about JPEG images.  JPEG is what most phones take as the the "original photo".

Starting with an original jpeg image (a picture taken with a phone camera) how can it ever be expected that applying compression, will increase the size?

Are you saying the Expo Manipulator uncompresses the image to it's original size and then does an inferior compression?

I'm not trying to truly understand this process so our code is predictable.
At this point we have no way to know if an image will get larger or smaller when applying compression via ` ImageManipulator.manipulateAsync`.

Thanks!

**Comment by sd** [comment]
think of it this way. You have a EXAMPLE.TXT file, and you compress it inside an EXAMPLE.ZIP file. You then try to test other ZIP compression parameters using the EXAMPLE.ZIP as the input. You'll see unexpected results. You need to use the uncompressed input as the reference, not a previously compressed file.

Expo Manipulator, and any other image processor, will not be compressing your original jpeg file, but the actual bitmap inside it. The size of that bitmap is 5000x5000x3 or about 75MB. That's the reference size you should use for comparisons.

JPEG is an "image compression" algorithm, not a general "file compression" technique.

You use Expo Manipulator or any other similar tool, up front or in the backend, to ensure a consistent level of compression on all your images, based on what you consider to be acceptable image quality. The actual size of the file will depend on this quality and the resolution of the original bitmap. 

It will be independent from how the original data was stored before.

If your goal is to save some bytes during data transfer, then you need to use general compression like gz around your files. But for already compressed images, the gains will be pretty minimal.

**Comment by GollyJer** [comment]
Thanks for taking the time to discuss. 🙏

Pictures from phones are WAY bigger than we need for our "track your meals with pictures" app. What we are trying to do is save on server cpu and storage cost by pre-processing images on devices before saving them to our cloud. 

User takes a picture > Expo Manipulator compresses > picture sent to server.

I guess the problem here is the image compressors are not made to act directly on, already compressed, JPEG images. But every phone pic is a JPEG. 😕

Were you able to find a predictable way to compress on device?

Also, none of this explains the massive differences between Android and iOS.  Any thoughts there?

Thanks again. I understand this probably wasn't a conversation you were expecting after posting. 😃

**Comment by sd** [comment]
Compression algorithms have been adjusted for device memory and cpu capacity, so the end result is not always the same. 

Not every phone pic is a JPEG. On iOS, for example, you might be using HEIC files. Both Android and iOS also support RAW formats. And depending on how Expo Manipulator is retrieving the image data, it might even be getting the pure bitmap at full resolution.

Set the `quality` parameter to the value that produces the smallest file sizes while still preserving the quality level you want to use. Most likely it will be something around 0.5-0.7. Quality starts degrading under 0.4, and file size becomes much larger with little perceptible improvements above 0.8. But this depends a lot on the type of images and how you plan to use them.

Also, this "middle range" of qualities is where different compression implementations behave similarly, and are optimized for. It's the lower and upper extremes where their parameters will differ more.

Just don't worry about "original file size". Ignore that. Or use a full-resolution, no-compression TIFF or PNG as your reference. This will also let you see the real quality loss at each compression level. If you start with a precompressed file, higher quality levels will still show whatever quality loss you suffered when compressing the original.
