### ISSUE TITLE
SecureStore.setItemAsync doesn't do anything or error.

### ISSUE THREAD

**Issue by funkjunky** [expo/expo#673]
SecureStore.setItemAsync('true', 'introComplete').then(() => console.log('set: ', arguments));
    SecureStore.getItemAsync('introComplete').catch(() => console.log('intro not set'));

I put this in componentWillMount of my main.js component and intro is never set and the arguments to the set function is always an empty array.

I don't know what else to do, because there is no error and no return.

(I'm testing using an iphone 6s and iOS 10.3.3. Strangely I could have swore it worked last week, but then I updated things.)

**Comment by funkjunky** [comment]
Oh shit, when were the arguments reversed?!

Ok, this is a more logical order. So I forgive y'all. I should have checked as soon as the version changed.

**Comment by funkjunky** [comment]
Wait... does reload clear the store?

**Comment by funkjunky** [comment]
Ok, so I think the javascript errors I was having was prevent other code from working correctly. Once I fixed my other errors, the store started returning correctly.

I still believe you should truly highlight the difference in argument order for setItemAsync! That's a pretty big change.

**Comment by ide** [comment]
The breaking changes section of the release notes explicitly mention this change: https://blog.expo.io/expo-sdk-21-0-0-is-now-available-be33b79921b7?source=linkShare-b76f0303e50d-1506289335

**Comment by funkjunky** [comment]
Right, I was foolish and only looked at the notes for SecureStore. Obviously one should check breaking changes.

Sorry about that and keep up the good work!
