### ISSUE TITLE
Babel.config.js or .babelrc?

### ISSUE THREAD

**Issue by wolrd** [expo/expo#6730]
I need to add a babel preset. And I have 2 files Babel.config.js and .babelrc. I use a bare workflow.

The preset name is "@babel/preset-flow". What file should I add the preset to?

**Comment by wolrd** [comment]
And should I delete {"presets": ["module:metro-react-native-babel-preset"]} from .babelrc for web project?

Info:
"The package babel-preset-expo extends @babel/preset-env on web and is used to configure your project for Unimodules. The core feature is that it won't compile your modules to core.js when targeting web, this means that you get optimal tree-shaking and dead-code-elimination. This step is optional with the React Native CLI but you'll get a much smaller bundle size and faster website if you do choose to use it. This is because module:metro-react-native-babel-preset is made for usage with the Metro bundler and not Webpack." from https://docs.expo.io/versions/v33.0.0/introduction/running-in-the-browser/

**Comment by wolrd** [comment]
Up

**Comment by wolrd** [comment]
@cruzach ? :)

**Comment by cruzach** [comment]
Hi @wolrd, we like to keep github reserved for bug reports, so I'm going to close this issue. In the future, questions like these are better off posted on [our forums](https://forums.expo.io/)

I think the [babel docs](https://babeljs.io/docs/en/configuration) would be a good place to start, they explain the difference of babelrc vs config.js
