### ISSUE TITLE
SDK36 Web - Drawer Navigation Broken

### ISSUE THREAD

**Issue by jjg77** [expo/expo#6738]
Expo Web
Drawer navigator screen pops out OK, but overlay screen is all black (no transparency) and cannot be clicked to close the drawer.

**Comment by cruzach** [comment]
Could you provide a snack that reproduces this? We provide the bug report template so that you can provide all the information we need without the need for back and forth, so we can fix these bugs ASAP 😄

**Comment by jennifer-elyse** [comment]
I came across thee same issue. The opacity of the page gets set to 0 whenever re-navigating to a page.
