### ISSUE TITLE
Camera module expo sdk 21.0.0

### ISSUE THREAD

**Issue by mfoncho** [expo/expo#674]
```js
import React, { Component } from 'react'
import {StyleSheet, Text } from 'react-native';
import { Camera } from 'expo';

export default class Sample extends Component{
    render(){
        return(
            <Camera ref={cam=>this.cam=cam} style={SytleSheet.absoluteFill}>
                <Text onPress={ e=> {
                    this.cam.recordAsync().then( video=> {
                      // process video url
                    })
                }}>Record</Text>
            </Camera>
        );
    }
}
```

**Comment by aalices** [comment]
@mfoncho are you using SDK 21 ?

**Comment by mfoncho** [comment]
exp --version Yields 44.0.0

**Comment by skevy** [comment]
@mfoncho what is the sdk version in your app.json?

**Comment by mfoncho** [comment]
myapp/node_modules/expo/package.json
{"version": "20.1.3"}

After -> yarn upgrade expo
myapp/node_modules/expo/package.json
{"version": "21.0.1"}

Now the entire app is broken
Warning
Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\XXXX\AppData\Local\Expo\schema-21.0.1.json: XDLError: Invalid JSON returned from API: SyntaxError: Unexpected token N in JSON at position 0. Response body: Not Found.
Warning
Warning: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 7.0.0, 8.0.0, 9.0.0
Warning
Warning: https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz is not a valid version. Version must be in the form of sdk-x.y.z. Please update your package.json file.

**Comment by skevy** [comment]
@mfoncho I'd recommend you read the upgrade instructions here: https://blog.expo.io/expo-sdk-21-0-0-is-now-available-be33b79921b7

**Comment by mfoncho** [comment]
@skevy I just read the upgrade guide and followed the instructions but i'm still having the same errors
here is my app.json
```json

  "expo": {
    "name": "xxxxx",
    "description": "xxxxxx.",
    "slug": "xxxxxxx",
    "privacy": "public",
    "sdkVersion": "21.0.1",
    "version": "1.4.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app-icon.png",
    "notification": {
      "icon": "./assets/icons/notification-icon.png",
      "color": "#000000"
    },
    "loading": {
      "icon": "./assets/icons/loading-icon.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf"]
    },
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "xxxxxxxxxx",
    },
    "android": {
      "package": "xxxxxxxxxxxxxxxxxxx",
    }
  }
}

```

**Comment by skevy** [comment]
Your sdkVersion should be `21.0.0`.

**Comment by mfoncho** [comment]
Fixed that.. now i have two new problems same Camera Module.
ExponentCameraModule.takePicture got 3 arguments, expected 2

```javascript
this.camera.takePictureAsync({quality:1, maxDuration:10000, mute:false})
```
recordAsync still throws warnings more pressing is 
undefined is not a function (evaluating 'CameraManager.stopRecording()') 
```javascript
this.cam.stopRecording();
```

**Comment by aalices** [comment]
@mfoncho the above example has mixed parameters from takePictureAsync and recordAsync. Have you downloaded the most recent Expo app from Play/App Store?

**Comment by mfoncho** [comment]
@aalices @skevy  I uninstalled and reinstalled the expo on the device now takePictureAsync works again but recordAsync function still throwing errors on android.  I created new sample app with bear react native without expo and linked the Camera lib from https://github.com/lwansbrough/react-native-camera. Camera lib capture function works as expected.  

Error retrieving camcorder profile params
native_get_camcorder_profile
CamcorderProfile.java

**Comment by mfoncho** [comment]
not specifying the video quality profile solves the Issue..

**Comment by aalices** [comment]
@mfoncho `quality` property for video recording is a constant and not a 0-1 number, please take look at the docs [here](https://docs.expo.io/versions/latest/sdk/camera.html#quality-videoquality--specify-the-quality-of-recorded-video-usage-cameraconstantsvideoqualityvalue-possible-values-for-169-resolution-2160p-1080p-720p-480p-android-only-and-for-43-43-the-size-is-640x480-if-the-chosen-quality-is-not-available-for-a-device-the-highest-available-is-chosen)
