### ISSUE TITLE
How to get link from downloaded files (and open it)

### ISSUE THREAD

**Issue by n1777** [expo/expo#6740]
I try to use FileSystem. I have a Flatlist with items, so i need to get the link from files each time these files be downloaded.

```
const downloadFile = async () => {
	try {
		const url = '.../file.jpg';
		const result = await FileSystem.downloadAsync(
   			url,
   			FileSystem.documentDirectory
		);
		const uri = result.uri;
		const fileInfo = await FileSystem.getInfoAsync(uri);

        console.log(uri); // output file directory
        console.log(fileInfo); // output object: { "exists": true, "isDirectory": false, "size": 319424, "uri": file directory } 
	} catch(error) {
		console.log(error)
	}
}
```

URL for download each time can be different (different files).  **How to get link for each file and open it?** ```FileSystem.documentDirectory``` is the same and not changed.

**Comment by cruzach** [comment]
There's an [example in our docs](https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemdownloadasyncuri-fileuri-options), you'll want to add the file name after `FileSystem.documentDirectory`, like this:

```
FileSystem.downloadAsync(
  url,
  FileSystem.documentDirectory + 'myFileName.txt'
)
```
