### ISSUE TITLE
[expo-ads-admob][IOS [Android works]] - Rewarded ad closes immediately

### ISSUE THREAD

**Issue by Tinmania2018** [expo/expo#6745]
So I have ejected my Expo app a while ago and now would like to use the expo-ads-admob package for the Admob integration. I followed the installation instructions and I can successfully show Banners ads in the Android and IOS app. The Android app also worked without a problem using the Reward ad. However the IOS app closes the Rewarded ad immediately.

The idea is that users view a Rewarded Ad and afterwards an upload with selected information starts.

The problem is that on IOS the ad is loaded, viewable for a second and I can hear the audio start, however it instantly closes and the app continues uploading. The Android app waits until users close the app and after closing starts the submitHandler.

Is anyone familiar with this problem and knows a fix? Below is some code and explanation to hopefully understand it better;

Users click on a upload button and get the choice to pay or do it for free. After selecting free the addUsingAdHandler is started. SetisAddMode closes the modal, after that I get the console log the ad is started and the video is shown.

```
    const addUsingAdHandler = async () => {
        setIsAddMode(false)
        console.log('Rewared video is shown')
        await AdMobRewarded.showAdAsync();
    }
```

On opening the page I add the eventListeners as instructed. The rewardedVideoDidClose listener is used to eventually start the upload.

```
    useEffect(() => {
        AdMobRewarded.setTestDeviceID("EMULATOR");
        AdMobRewarded.setAdUnitID('ca-app-pub-3940256099942544/5224354917');

        AdMobRewarded.addEventListener("rewardedVideoDidRewardUser", () =>
            console.log("Reward is binnen gekomen. ")
        );
        AdMobRewarded.requestAdAsync();
        AdMobRewarded.addEventListener("rewardedVideoDidLoad", () =>
            console.log("Video did load")
        );
        AdMobRewarded.addEventListener("rewardedVideoDidFailToLoad", () =>
            console.log("Failed to load")
        );
        AdMobRewarded.addEventListener("rewardedVideoDidOpen", () =>
            console.log("Video did open")
        );
        **AdMobRewarded.addEventListener("rewardedVideoDidClose", () => {**
**            console.log("video did close")**
**            submitHandler()**
**        }**
        );
        AdMobRewarded.addEventListener("rewardedVideoWillLeaveApplication", () =>
            console.log("Video did leave application")
        );
        AdMobRewarded.addEventListener("rewardedVideoDidStart", () =>
            console.log("Video did start")
        );
    }, [])
```
So When pushing the upload for free button the ad is shown for a second however it inmediatly is closed (logs show this using the event listeners) and the upload starts as expected. On my Android emulator the ad is shown until I press the close button as I would expect to have also on my IOS emulator.

Has anyone come across this as well before?

React-Native version; 0.59.10
Expo Version; 35.0.0
Expo-ads-admob version: 8.0.0

**Comment by cruzach** [comment]
`expo-ads-admob v8.0.0` is meant for use with SDK 36, so I would try upgrading to SDK 36 and seeing if you have the same problem. See [this upgrade guide](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit) for a walkthrough (you'll also want to run `expo upgrade`)

**Comment by Tinmania2018** [comment]
Ok thank you I will try that tomorrow evening and get back to you of this fixed it. 
If SDK 36 breaks more packages in my app then cures my problem is it possible to install expo-ads-admob v7 or something that works with SDK 35?

**Comment by Tinmania2018** [comment]
> Did you eject to Expokit, or the bare workflow? (if expokit, see [this upgrade guide](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit) for a walkthrough (you'll also want to run `expo upgrade`)

I checked my notes and I have ejected to a bare workflow I believe btw.
