### ISSUE TITLE
Expo video - How to click Video the full screen button to display the player horizontally

### ISSUE THREAD

**Issue by chenguzhen87** [expo/expo#6748]
## 🐛 Bug Report
Expo video - How to click Video the full screen button to display the player horizontally
### Environment
ios,android

### Steps to Reproduce
Click the full screen button to display the player vertically

### Expected Behavior
Click the full screen button to display the player horizontally

### Actual Behavior
Click the full screen button to display the player vertically

**Comment by cruzach** [comment]
You can use the `useNativeControls` prop to do this
```
<Video
  source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
  resizeMode="cover"
  useNativeControls
  style={{ width: 300, height: 300 }}
/>
```

Thoroughly reading the [documentation](https://docs.expo.io/versions/latest/sdk/video/) is always a huge help when trying to figure out how to do something with an API
