### ISSUE TITLE
Google login in standalone app

### ISSUE THREAD

**Issue by maharjanaman** [expo/expo#675]
Following every process from https://docs.expo.io/versions/v20.0.0/sdk/google.html, I'm getting error:

- E/TokenRequestor: You have wrong OAuth2 related configurations, please check. Detailed error: INVALID_AUDIENCE

for standalone android app.
Below is my android config in app.json
```
"android": {
      "package": "com.whatever.what",
      "versionCode": 1,
      "config": {
        "googleSignIn": {
          "apiKey": "AIz***************************gK8Iwvk-I",
          "certificateHash": "24C6************************D3EE72"
        },
        "googleMaps": {
          "apiKey": "AIza***************************NgK8Iwvk-I"
        }
      }
    }
```
Am I missing some keys or something?
I'm using sdk version 20.0.0

**Comment by skevy** [comment]
You're positive that you did what's listed here w.r.t. getting the SHA1 from your APK: https://docs.expo.io/versions/v20.0.0/sdk/google.html#add-the-configuration-to-your-app

**Comment by maharjanaman** [comment]
@skevy, yes exactly the same process, I even tried with new clientId but issue still persist. What kind of info are you asking for?

**Comment by lucasmouse** [comment]
Same problem...
