### ISSUE TITLE
Running expo app via detox results in apple warning

### ISSUE THREAD

**Issue by awinograd** [expo/expo#6758]
Hi, I haven't been able to find any recent / up to date guide on using Detox with a managed expo project. I've downloaded the latest ipa (2.14.0) and when it get's installed + run via detox I'm getting the following popup:

![image](https://user-images.githubusercontent.com/303609/72314674-7fa71d80-3655-11ea-82de-afba797e7474.png)

Have you guys run into this before? Any suggestions on how to proceed? I'm on latest SDK / detox / XCode.  Thanks for any help!

```

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.16.0 - ~/.nodenv/versions/8.16.0/bin/node
      Yarn: 1.12.1 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nodenv/versions/8.16.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react: ^5.2.8 => 5.2.8 
      @storybook/react-native: ^5.2.8 => 5.2.8 
      @types/react: ^16.8.22 => 16.8.22 
      @types/react-native: 0.60.23 => 0.60.23 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.6 => 4.0.6 
      detox: 15.1.2
  
```

**Comment by awinograd** [comment]
I was able to work around this issue by downloading the iOS app via `wget` instead of directly in chrome. The new mac OS must have some extra security setting...

**Comment by x5engine** [comment]
how did you do that with wget? @awinograd

**Comment by awinograd** [comment]
@x5engine copy the download link from the expo page and in terminal do `wget <copied link>`. The expo file will be downloaded to the current directory

**Comment by x5engine** [comment]
Yeah too many chains, eject the whole project, works fine now.

**Comment by zhenyanghua** [comment]
> @x5engine copy the download link from the expo page and in terminal do `wget <copied link>`. The expo file will be downloaded to the current directory

I could only find link like this one: `exp://127.0.0.1:19000`, but can't download with this protocol schema with curl or wget. Which link did you use?
