### ISSUE TITLE
No AdMob Apple has identified use of IDFA in Expo 20.0.0

### ISSUE THREAD

**Issue by tofoli** [expo/expo#676]
I'm not using AdMob, but when I send my App to Apple I've identified the use of the ASIdentifierManager class (IDFA), and asked to tell what kind of announcements it existed in my App. The strangest thing of all is that I'm using Expo version 20.0.0 , and in the past compilations such information was not required.

Some help?

**Comment by tofoli** [comment]
![image](https://user-images.githubusercontent.com/2599384/30818698-aa547018-a1f2-11e7-94ba-8452f2d9e363.png)

**Comment by terribleben** [comment]
Hi, are you sure this is related to AdMob? Multiple Expo APIs use the IDFA, and that has not changed recently. Did you follow [these steps](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html#6-submit-it-to-the-appropriate-store) (including the note about the IDFA) when submitting your app?

**Comment by tofoli** [comment]
Now I realized that I did not follow these steps, this misunderstanding occurred because the first time I sent the app to apple was not requested, only the second time.

**Comment by terribleben** [comment]
Sorry about the trouble. Good luck with your project. :)
