### ISSUE TITLE
AdMobRewarded needs customData setting for server side verification 

### ISSUE THREAD

**Issue by jieunnpark** [expo/expo#6762]
### Please note that feature requests opened in the core Expo repository will be closed.

  Thanks for helping us make Expo even better! 😀
  Unfortunately, this is not the right place for feature requests. Please find and upvote your feature (or create a new one) at https://expo.canny.io instead.
=======
to verify server side callback function when after watching reward Ad video, developer needs to set a custom data for Ad Mob such as userkey. we need to see which user triggered this Ad, and can give reward with very confidence. 
but current version of expo-admob, there is no way to set a custom data. 
please refer here https://developers.google.com/admob/ios/api/reference/Classes/GADServerSideVerificationOptions#/c:objc(cs)GADServerSideVerificationOptions(py)customRewardString

**Comment by cruzach** [comment]
As it says in the template, we keep github reserved for bug reports, so any feature requests should go on our canny (link is in your original post)
