### ISSUE TITLE
Included SDKs and privacy configurable via app.json

### ISSUE THREAD

**Issue by theWeird** [expo/expo#6763]
After tracing some calls of our app to AWS instances, reading the sections about statistics and crash reports in https://expo.io/privacy and the list of expo vendors in the forum, I found several articles and discussions about expo, unwanted sdks, unwanted network traffic and expo as big privacy problem.  
Like this one https://hackernoon.com/how-expo-is-fooling-everyone-mc1r34i6

In the discussions ide explained very clear, why several SDKs are included during the build process and why some network requests are made (e.g. OTA). He also mentioned, that developers can always convert to bare workflow to remove unneeded SDKs.

BUT: If the only reason is to remove Facebook SDK and OTA calls, leaving managed workflow to me seems like an overreaction.

My suggestion:

As you did with permission management, give developers the opportunity to DISABLE certain SDKs and expo functionality that makes outbound calls via app.json.

Yes, I understood that without facebook API gyro and camera wont be accessible via expo. But if it is enabled by default, beginner can work with the full feature set and decide later, what they need and what can be excluded.

This way, in my opinion, there would be no need for further discussions whether expo can be used for full GDPR compliant apps or not.

**Comment by theWeird** [comment]
PS: if you would integrate these options in the paid plan, I'd be absolute fine with it ;)

**Comment by kxrz** [comment]
@theWeird - Is there any updates regarding this issue? A GDPR compliant plan would be a game changer. I'm deeply looking for a solution to remove unnecessary SDKs from builds.

**Comment by cruzach** [comment]
Thanks for the feedback! As for your suggestion- that is actually our plan, to give developers the opportunity to include and exclude whichever libraries from their builds they would like. As you said, that's possible right now with the bare workflow, it just has a few limitations. The good news is that those limitations are shrinking, and soon we hope to bring the bare workflow and managed workflow to just about feature parity. 

Just wanted to mention here that Expo is Privacy Shield certified- which helps us to meet the EU requirements for transferring personal data to third countries or international organizations, discussed in [chapter 5 of GDPR](https://gdpr.eu/tag/chapter-5/). Hopefully this helps in satisfying you or your DPO's requirements for the apps you build. Otherwise, there isn't really a specific "certification" one can get for GDPR, afaik, but we aim to follow the [GDPR checklist](https://gdpr.eu/checklist/) in all applicable situations (meaning both for developers making apps with Expo services, and end-users of apps made with Expo)

Let me know if you have any other questions, happy to answer them as best I can 😄

**Comment by qroac** [comment]
Sorry for digging out this topic again. 
But with the privacy shield invalidated by european court, I'd like to ask for an update on this.
https://www.csoonline.com/article/3567061/eu-court-invalidates-privacy-shield-data-transfer-agreement.html

I see it is now possible to drop unused libraries for the sake of APK file size by opting in for lean builds as described in https://github.com/expo/fyi/blob/master/managed-app-size.md.
This way, I can get my APK down to 3 trackers left:
- Facebook Ads
- Google Analytics
- Google Firebase Analytics

Do you plan to give developers the opportunity to opt out from these remaining trackers, too?  
Or is there already a possibility to get rid of these trackers from APK build in managed workflow?

**Comment by dgellow** [comment]
The focus Expo has on the Privacy Shield is a bit concerning from a European perspective. As said by @qroac the EU-US privacy shield framework has been invalidated by the Court of Justice of the European Union and isn't a satisfying answer IMHO.

See https://www.privacyshield.gov/article?id=EU-U-S-Privacy-Shield-Program-Update for details.

Regarding the tracking from 3rd party libraries, I did sniff the network of my application and did not see anything being sent to Google or Facebook, which is a good sign. I haven't try to crash it on purpose to see if something is being sent to Sentry or another similar service, though I might try it later.

I have the following settings in `app.json`:

```js
{
  "expo": {
    // [I removed settings that aren't relevant here]
    // ...
    "updates": {
      "enabled": false,
      "checkAutomatically": "ON_ERROR_RECOVERY" // <= I believe that's redundant and could be removed
    },
    "facebookAdvertiserIDCollectionEnabled": false
  }
}
```

I do not use any 3rd party tracking/analytics SDK and do not see anything being sent to a 3rd party, which is a good sign, the only network traffic I can see is the following (using [Charles](https://www.charlesproxy.com/)):

![image](https://user-images.githubusercontent.com/2451004/112718937-69058300-8ef6-11eb-8732-b2d568ecb356.png)

I don't know why those requests are for given that I explicitly disabled OTA updates in my config, and I believe they shouldn't happen at all when `updates.enabled` is set to `false`, or at minimum developers should be able to opt-out from any network activity with an expo domain. But that's of lesser concern than sending information to Facebook or Google.

@qroac Have you seen requests being sent to 3rd parties? If yes, could you share the actual requests?

**Comment by qroac** [comment]
I haven't monitored any network requests yet. 
The trackers listed in my post have been identified by scanning the APK of my app with MobSF.
https://github.com/MobSF/Mobile-Security-Framework-MobSF

I don't know if they made any reqeusts, but their code are still part of the APK built by expo. 
Without using them, you would stlill have to explain concerned users, why they are part of your App.

**Comment by qroac** [comment]
PS: Here is my feature request on this topic from August 2020, right after this issue has been closed.

**Comment by dgellow** [comment]
It seems that I was mistaken: using Expo SDK 40 I **do not** see any requests to expo.io or exp.host. The device I used for my tests didn't receive the latest update of my application for some reasons. I see no requests at all when using the build based on Expo SDK 40, which is great.
