### ISSUE TITLE
IPhone XR doesn't lock with OrientationLock.PORTRAIT

### ISSUE THREAD

**Issue by CarterBland** [expo/expo#6764]
### Environment

  Expo CLI 3.11.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.11.2

IOS / IPhone XR Specific

### Steps to Reproduce
Attempt to lock phone to portrait mode
```js
ScreenOrientation.lockAsync(OrientationLock.PORTRAIT)
```

### Expected Behavior
I expect the phone to be locked to portrait mode after, but that's not the case.

### Actual Behavior
It doesn't actually lock the phone's orientation. Changing the value to `OrientationLock.PORTRAIT_UP` fixes it though.
### Reproducible Demo

**Comment by cruzach** [comment]
Thanks for reporting this! Since the newer devices (iPhone X, XS, XS Max, and XR ) don't support you using them upside down (FaceID wouldn't work, then, apparently), i don't think the fact that this happens is a bug in itself.

But maybe we could handle it better, and provide more information (possibly in the error message? or falling back to `PORTRAIT_UP`?) What do you think?

**Comment by CarterBland** [comment]
@cruzach Hey Charlie, that's a great idea! One thing I noticed is that on my XS Max it worked as intended, we tested with multiple phones and it seemed only XR was affected.

**Comment by cruzach** [comment]
hm that's odd

So the ScreenOrientation module is being extracted/refactored in https://github.com/expo/expo/pull/6760 , no use in making changes to the current one. I would say to use `PORTRAIT_UP` for now, and the new module should handle this cleaner
