### ISSUE TITLE
[local-auth][android] authenticateAsync results in "user_cancel" error immediately on some devices

### ISSUE THREAD

**Issue by cruzach** [expo/expo#6770]
### Environment

SDK 36
Android
expo-local-authentication: 8.0.0
 (does not occur on SDK 35 / expo-local-authentication v 7)
### Steps to Reproduce

call `LocalAuthentication.authenticateAsync` using Android 9 on a OnePlus 5, or Android 10 on a Samsung Galaxy S10+

### Expected Behavior

Should authenticate

### Actual Behavior

If the app is started from the background (coming from a previous success login), the Fingerprint authentication is working fine, but if the app is completely killed and then opened fresh, `LocalAuthentication.authenticateAsync` returns with this error: 

```
{
  "error": "user_cancel",
  "success": false,
}
```

To reproduce locally, start the app with `expo start --no-dev --minify` and kill both expo app and the dev app, then open from a clean state

### Reproducible Demo

https://github.com/ajimenezdev/ExpoAuthIssueDemo

Here is a screencast that shows the behavior- https://www.loom.com/share/9e44d045471f4b08911a8aa53281f8f3

**Comment by ajimenezdev** [comment]
To add some extra information about this issue I have tried the following steps:

Case 1:
- Eject expo to ExpoKit
- Setup keystore and Android build config
- Try to run on OnePlus 5
❌App is still failing

Case 2:
- Eject expo to Bare workflow
- Setup keystore and Android build config
- Try to run on OnePlus 5
✅App is working

I'll try to check some more debugging from ExpoKit version to see if I can find the problem

**Comment by willianferreiradev** [comment]
Did you manage to fix it? I have the same problem now in 2025, and I haven't found a solution yet.

Expo: 49
Local Authentication: 13.4.1
