### ISSUE TITLE
Execution failed for task ':expo-constants:compileDebugJavaWithJavac'. (React Native)

### ISSUE THREAD

**Issue by AakashHussain** [expo/expo#6772]
Task :expo-constants:compileDebugJavaWithJavac FAILED
E:\react native\rn-course\node_modules\expo-constants\android\src\main\java\expo\modules\constants\ConstantsService.java:142: error: cannot find symbol
      return info.getLongVersionCode();
                 ^
  symbol:   method getLongVersionCode()
  location: variable info of type PackageInfo
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-constants:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
340 actionable tasks: 335 executed, 5 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

thanks!

**Comment by cruzach** [comment]
Hi! Unfortunately, it's really hard to help with just the error message copy/pasted here 🙁 If you fill out the entire bug report template, I'm happy to re-open the issue and try our best to help debug what's going on here.

**Comment by AakashHussain** [comment]
**Description**
@cruzach I am working on a react-native app. When i tried to add react-native-navigation using the provided documentations about it, this is the error i'm getting, have tried all the solutions already available, but not working for me.
thanks!

**android/build.gradle**
`buildscript {
    ext {
        buildToolsVersion = "26.0.2"
        minSdkVersion = 19
        compileSdkVersion = 26
        targetSdkVersion = 26
        supportLibVersion = "26.0.2"
    }

    subprojects {
    project.configurations.all {
	resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.appcompat' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.1.0"
                }
            if (details.requested.group == 'androidx.coordinatorlayout' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.1.0"
                }
            if (details.requested.group == 'androidx.core' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.1.0"
                }
        	}   
        }    
    }

    subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative55") || names.contains("reactNative56") || names.contains("reactNative57")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}

    repositories {
        google()
        jcenter()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenLocal()
        mavenCentral()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven { url 'https://jitpack.io' }
    }
}
wrapper {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
`
**android/app/build.gradle**

`android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.rncourse"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
    }

dependencies {
    implementation project(':react-native-screens')
    implementation project(':react-native-reanimated')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
    implementation project(':react-native-vector-icons')
    addUnimodulesDependencies()

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
}
`
**Environment**
- "react-native": "^0.57.8"
- react-native-navigation": "^4.4.0"
- OS: Windows

**Comment by cruzach** [comment]
I'm not too familiar with `react-native-navigation`, but [`react-navigation`](https://reactnavigation.org/) is an awesome way to handle routing and navigation in an Expo / RN app, not sure if you've already taken a look at that

your RN version is also (I suppose) pretty old. The easiest way to get started with a bare rn project is with `expo init -t bare` 👍

**Comment by AakashHussain** [comment]
@cruzach thank you for the advice. I actually followed a documentation regarding react-native-navigation because i heard its better and easy to use. but now i think i should give react-navigation a try as you said, hoping everything will go well thanks.
