### ISSUE TITLE
Can Expo be packaged into IPA under windows? What to do if you can

### ISSUE THREAD

**Issue by chenguzhen87** [expo/expo#6776]
### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂

**Comment by cruzach** [comment]
You'll need access to a Mac to build an IPA (unless you go through some other third party, but Expo itself doesn't offer that)
