### ISSUE TITLE
No assets in Expokit 36 on android

### ISSUE THREAD

**Issue by sweebee** [expo/expo#6777]
### Environment

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.17.0 - /usr/local/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @bugsnag/expo: ^6.4.1 => 6.5.1 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7
```

### Expected Behavior

Assets should work on release.

### Actual Behavior

After building the release version, the app has no assets (images, fonts).

**Comment by grzmot22** [comment]
Hi, I had the same problem. This commit fixed the missing assets in release bundle https://github.com/expo/expo/commit/88601e4c046cb79949fde0a71f304a54f7dcc382

**Comment by cruzach** [comment]
@sweebee have you rebuilt with the fix mentioned above? If you have an are still seeing this issue, please provide a full repro.  Should mention that I've seen this happen before when you update gradle (Android Studio will prompt you to upgrade, but you shouldn't since Expokit ships with the appropriate version)

**Comment by sweebee** [comment]
Yes i fixed it by reverting to the default gradle version. I did update because Android Studio told me so.
