### ISSUE TITLE
SDK 36 giving error: "Unexpected token '!'. Expected '}' to end an object literal"

### ISSUE THREAD

**Issue by JimVanEeden** [expo/expo#6778]
### Environment

  Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.3 => 4.0.3 
    npmGlobalPackages:
      expo-cli: 3.11.3

Happens on both IoS and Android simulators

### Steps to Reproduce

Update to SDK version 36. Switching back to 35 and everything works as expected again

### Expected Behavior

A working app

### Actual Behavior

This message appears right after loading:

```
Unexpected token '!'. Expected '}' to end an object literal

no stack
```

**Comment by cruzach** [comment]
I've tested quite a few SDK 35 to SDK 36 upgrades, and haven't seen this. If you can provide a reproducible example, then I'm happy to help debug this issue. Probably worth taking a peak at our [changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md#3600), too

**Comment by JimVanEeden** [comment]
I'm not sure what caused the issue, but I reverted back to 35 and then upgraded to 36 again through `expo upgrade` and it's working again. Will report here if I come across this issue again and will close for now.
