### ISSUE TITLE
Linking openSettings is undefined

### ISSUE THREAD

**Issue by byCedric** [expo/expo#6786]
### Environment

```
Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.11.7
```

### Steps to Reproduce

Create a button with `Linking.openSettings()`.

```
import { Linking } from 'expo';

render() {
    return (
        <Button title='open settings' onPress={() => Linking.openSettings()} />
    );
}
```

### Expected Behavior

`Linking.openSettings()` was introduced [here](https://github.com/facebook/react-native/pull/23965) and should be available starting from RN `0.60` (if im correct). Expo already has traces of this code implemented, as [you can see here](https://github.com/expo/expo/blob/master/android/ReactAndroid/src/main/java/com/facebook/react/modules/intent/IntentModule.java#L151).

### Actual Behavior

![Screenshot_20200116-235956](https://user-images.githubusercontent.com/1203991/72570230-a024e100-38bc-11ea-9d82-b302d2c96803.jpg)

### Reproducible Demo

See [this snack](https://snack.expo.io/@bycedric/linking-open-settings-bug).

**Comment by byCedric** [comment]
It's kind of weird that the `react-native/Libraries/Linking/NativeLinking.js` module returns an instance from the turbo registry, without this method. Even though it's requested in the spec, by `TurboModuleRegistry.getEnforcing<Spec>('IntentAndroid')`, and available in the (android) code.

**Comment by cruzach** [comment]
hi Cedric! Thanks for pointing this out

Very odd, and seems like it should be available on the iOS side too https://github.com/expo/expo/blob/master/ios/versioned-react-native/ABI36_0_0/ReactNative/Libraries/LinkingIOS/ABI36_0_0RCTLinkingManager.m#L163

**Comment by outaTiME** [comment]
Hi guys, 

this issue still happening on SDK37 (on iOS only), but is marked at fixed in changelogs 😢 

<img width="583" alt="image" src="https://user-images.githubusercontent.com/140472/78513552-e9c9ed00-7782-11ea-8da6-76b6a351da0c.png">

**Comment by outaTiME** [comment]
@brentvatne great polyfill 😏 currently available on 37.0.5 right ?

**Comment by brentvatne** [comment]
if you init a new project now you will get it. in existing projects, `npm install expo@36.0.6` and switch react-native tag to 37.0.1

**Comment by outaTiME** [comment]
> if you init a new project now you will get it. in existing projects, `npm install expo@36.0.6` and switch react-native tag to 37.0.1

Typo error? did you mean 37.0.6?

**Comment by brentvatne** [comment]
ah yeah sorry
