### ISSUE TITLE
Error :  'ScrollView' has no propType for native prop 'RCTScrollView.onScrollAnimationEnd'  of native type ' BOOL'

### ISSUE THREAD

**Issue by jpca999** [expo/expo#679]
I'm stuck on this error. 

It was working absolutely fine, but suddenly this error started to pop. 
I am using        "expo": "^20.0.0",

I've tried the following versions. 
"react-native": "^0.47.2",
"react-native": "^0.47.1",

"react-native": "^0.47.0",
0.48.4, 

![image](https://user-images.githubusercontent.com/1026325/30834598-d7021e24-a221-11e7-954a-8ec0bdfc7c7c.png)

![image](https://user-images.githubusercontent.com/1026325/30835723-ab1ff5b4-a227-11e7-8671-66e4f85c391a.png)

{
  "name": "app-20",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "axios": "^0.16.2",
    "expo": "^20.0.0",
    "latlng-to-zip": "^0.0.1",
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.12",
    "react-addons-update": "^15.6.0",
    "react-native": "^0.47.2",
    "react-native-calendar": "^0.12.3",
    "react-native-calendars": "^1.5.8",
    "react-native-communications": "^2.2.1",
    "react-native-easy-toast": "^1.0.6",
    "react-native-elements": "^0.16.0",
    "react-native-flexbox-grid": "^0.3.1",
    "react-native-google-place-autocomplete": "^0.3.0",
    "react-native-indicator": "^0.6.7",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-maps": "^0.16.2",
    "react-native-modal": "^3.1.0",
    "react-native-modal-datetime-picker": "^4.11.0",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-progressive-input": "^1.0.3",
    "react-native-segmented-control-tab": "^3.2.1",
    "react-native-signature-pad": "^0.0.8",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^5.0.1",
    "redux-persist": "^4.9.1",
    "redux-thunk": "^2.2.0"
  }
}

{
    "expo": {
    "name": "thapp",
    "description": "thapp",
    "slug": "thapp",
    "privacy": "unlisted",
    "sdkVersion": "20.0.0",
    "version": "1.0.5",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
          "bundleIdentifier": "com.thapp.exp",
          "supportsTablet": true
    },
    "android": {
       "package": "org.thapp.exp",
     }
  }
}

I also tried replacing react-native package with   "react-native": "^0.47.2",  But didnt work.

**Comment by FilipLukac** [comment]
Same here

**Comment by fossecode** [comment]
- Delete your project’s node_modules directory and run npm install again
- Reopen your project in XDE and press “Restart” to clear the packager cache, or run exp start -c if you use use exp, or if you use react-native-scripts press shift + R after starting the packager with npm start.

**Comment by yavorsky** [comment]
@jpca999 It started appearing after bumping my OS to Hight Siera today. Previously, I had the same error, but downgrading react-native from 0.48.x to 0.47.x fixed it. For now, it doesn't work even with 0.47.x. Also works fine if I removing `ListView` or `FlatList`.

**Comment by matheuschagas** [comment]
same issue here

**Comment by tutturen** [comment]
I experienced the same error earlier today. It might be related to iOS 11, not sure.
I fixed it by bumping Expo to 21.0.2, then reinstall node modules, and clear the cache after starting expo.

**Comment by jynweythek223** [comment]
Same. Started after updating xcode to v9

**Comment by zhuyunxiang** [comment]
Sama issue in IOS Expo 21.0.2

**Comment by matheuschagas** [comment]
Thanks @tutturen ! This fixed my issue! :+1:

**Comment by jpca999** [comment]
Lol - I didn’t even update anything.  

I started with creating a new app in Expo and now it’s working fine.

With expo I think they updated the versions...

**Comment by jynweythek223** [comment]
Neither updating Expo, nor creating a new app didn't solve my problem

**Comment by yavorsky** [comment]
@tutturen solution helped me also. But don't forget to update expo version not only in the package.json, but `sdkVersion` in app.json also!

**Comment by jankarres** [comment]
The following solved the issue in my case:

1. Update `expo` in the package.json to `21.0.2`
2. Update `react-native` in the package.json to `0.48.4`
3. Remove old and install new package versions `rm -r node_modules/expo/ node_modules/react-native/ && npm install `
4. Set `sdkVersion` in app.json to `21.0.0` (even if installed version is 21.0.2)
5. Restart expo packager

**Comment by jynweythek223** [comment]
@jankarres solution helped. I believe now the problem was in react-native version (mine was 0.47) and expo version (mine was 20). Updating just expo didn't solve the problem.

**Comment by jpca999** [comment]
Here are my latest package.json & app.json versions. Hope it helps.

{
“name”: “Hello-21-1”,
“version”: “0.0.0”,
“description”: “Hello Expo!”,
“author”: null,
“private”: true,
“main”: “node_modules/expo/AppEntry.js”,
“dependencies”: {
“expo”: “^21.0.0”,
“react”: “16.0.0-alpha.12”,
“react-native”: “https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz”,
“axios”: “^0.16.2”,
“latlng-to-zip”: “^0.0.1”,
“lodash”: “^4.17.4”,
“react”: “16.0.0-alpha.12”,
“react-addons-update”: “^15.6.0”,
}
}

app.json

{
“expo”: {
“name”: “App”,
“description”: " App",
“slug”: “delete-app”,
“privacy”: “unlisted”,
“sdkVersion”: “21.0.0”,
“version”: “1.0.0”,
“orientation”: “portrait”,
“primaryColor”: “#cccccc”,
“icon”: “./assets/icons/app-icon.png”,
“loading”: {
“icon”: “./assets/icons/loading.png”,
},
“packagerOpts”: {
“assetExts”: [“ttf”, “mp4”]
},
“ios”: {
“supportsTablet”: true
}
}
}

**Comment by Baungo** [comment]
Same issue after upgrade ios Expo to 1.20.2

**Comment by ide** [comment]
If you get this error:
>`ScrollView` has no propType for native prop `RCTScrollView.onScrollAnimationEnd` of native type `BOOL`
>If you haven't changed this prop yourself this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

It's very likely that your device is trying to run JS code that doesn't correspond to the native code on your device. The first thing to do is look at your Expo SDK version. In app.json, you should see a field called "sdkVersion" -- for example, it might be "21.0.0" -- which tells the Expo client which version of the native code to run.

### Using the correct version of React Native

We highly recommend that you use a release of React Native that has been tested to work with Expo. In the case of SDK 21, you'd put this in your package.json's "dependencies" section:
```
"react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
```
**The above snippet works only for Expo SDK 21! If you are using a different SDK version, you must use a different version of React Native!**

### Clearing your caches

We also want to ensure that your device doesn't try to run a stale copy of your code. There are several caches with Expo and React Native, so let's clear them just to be safe:

- Stop the React Native packager. Close exp or XDE.
- Force quit the Expo client on your device
- Clear the Watchman cache (if you are using Watchman): `watchman watch-del-all`
- Clear the Metro bundler cache: `rm -fr $TMPDIR/react-*`
- Make sure your npm dependencies are rebuilt and installed correctly: `yarn --force`
- Start up exp (`exp start --clear` to make sure we clear the Metro bundler cache for good) or XDE
- Open your project on your device in the Expo client

**Comment by abdennour** [comment]
Greatr @jankarres  . Your solution is enough 🎉 🎉 🎉
I was looking for this solution  5 days ago , and your answer was 2 days ago. 
Anyway, I found a workaround & I published my app .. https://youtu.be/DLHpnIn6jbk
 Welcome!
