### ISSUE TITLE
getPurchaseHistoryAsync refresh on iOS

### ISSUE THREAD

**Issue by josaric** [expo/expo#6794]
"On iOS, the refresh boolean is ignored and it returns the purchase history in the same way that connectAsync does."
Is it possible that this will work same as android?
"On Android, if refresh is set to true it will make a network request and return up to one entry per item even if that purchase is expired, canceled, or consumed."

https://docs.expo.io/versions/latest/sdk/in-app-purchases/#inapppurchasesgetpurchasehistoryasyncrefresh-boolean

Thanks

**Comment by cruzach** [comment]
I'm not exactly sure what your question is, both Android and iOS work the same in that they both return the [IAPQueryResponse](https://docs.expo.io/versions/latest/sdk/in-app-purchases/#iapqueryresponse) object (same as the return value for `connectAsync`, except on android when the boolean value is `true`, in which case it behaves differently (explained in the docs)
