### ISSUE TITLE
[docs] Location.getCurrentPositionAsync options not in sync with TypeScript definitions

### ISSUE THREAD

**Issue by Xerus2000** [expo/expo#6795]
Expo: 36.0.1
Docs: https://docs.expo.io/versions/v36.0.0/sdk/location/#locationgetcurrentpositionasyncoptions

Now, I don't know what side is right or wrong here, but the docs specify a `maximumAge` parameter for `Location.getCurrentPositionAsync`, which is not available in typescript. At the same time there is a `timeout` option in the ts definition of LocationOptions but not in the docs.

**Comment by cruzach** [comment]
Looks like the [android source makes use of `maximumAge`](https://github.com/expo/expo/blob/8b45846976d16b28329bd5fb067040c16db50089/packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java#L215), and also [uses `timeout`](https://github.com/expo/expo/blob/8b45846976d16b28329bd5fb067040c16db50089/packages/expo-location/android/src/main/java/expo/modules/location/LocationModule.java#L195).

Would you like to open a PR for the types and docs?

**Comment by Xerus2000** [comment]
Unfortunately I am currently quite busy, so don't rely on me here ^^
