### ISSUE TITLE
`CFBundleDisplayName` is required for Segment to work properly with Google Analytics

### ISSUE THREAD

**Issue by Dygerati** [expo/expo#680]
I've implemented Segment on my app, utilizing Expo version 21. The setup within Segment is identical for both, but the events are not reaching Google Analytics for just the iPhone source. I noticed in the RAW events in Segment's debugger that the "name" field is missing from the iOS sourced events only, and I believe this is the cause. Here is one of the events in total:

`{
  "anonymousId": "REDACTED",
  "context": {
    "app": {
      "build": "1.20.0.109748",
      "name": "",
      "namespace": "host.exp.Exponent",
      "version": "1.20.0"
    },
    "device": {
      "adTrackingEnabled": true,
      "advertisingId": "REDACTED",
      "id": "REDACTED",
      "manufacturer": "Apple",
      "model": "iPhone6,1",
      "type": "ios"
    },
    "library": {
      "name": "analytics-ios",
      "version": "3.6.5"
    },
    "locale": "en-US",
    "network": {
      "carrier": "T-Mobile",
      "cellular": false,
      "wifi": true
    },
    "os": {
      "name": "iOS",
      "version": "10.3.2"
    },
    "screen": {
      "height": 568,
      "width": 320
    },
    "timezone": "America/Mexico_City",
    "traits": {},
    "ip": "REDACTED"
  },
  "integrations": {},
  "messageId": "REDACTED",
  "name": "GameList",
  "properties": {},
  "timestamp": "2017-09-25T22:12:30.299Z",
  "type": "screen",
  "userId": "REDACTED",
  "writeKey": "REDACTED",
  "sentAt": "2017-09-25T22:12:59.352Z",
  "receivedAt": "2017-09-25T22:12:59.655Z",
  "originalTimestamp": "2017-09-25T17:12:29.996-0500"
}`

As you can see the `context.app.name` property is blank, which is *not* the case with the Android events.

**Comment by terribleben** [comment]
Hey there - I've compared [our Segment implementation](https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Modules/Api/EXSegment.m#L19-L20) with their [latest docs](https://segment.com/docs/sources/mobile/ios/) and it seems like we're doing exactly what they recommend. There isn't a place for us to provide any other info about the context. Maybe this is an upstream issue? Have you found other reports of behavior similar to what you're observing?

**Comment by Dygerati** [comment]
Hey @terribleben, appreciate your taking a look. I wrote to Segment support as well and they responded that the `context.app.name` was missing, as I mentioned before. They also pointed me to this paragraph in their docs:

https://segment.com/docs/destinations/google-analytics/#providing-required-field-display-name

Is that at all enlightening? I've also responded to them and directed them to this issue as well.

**Comment by terribleben** [comment]
Ah, thanks, that link is helpful. I think we are not providing `CFBundleDisplayName` in the builds we create. We currently only have `CFBundleName`.

**Comment by carriesmith** [comment]
We're also having the same problem (and got the exact same message from Segment help). Is there a work-around so that we can populate context.app.name until a fix is in place?

**Comment by terribleben** [comment]
You may be able to use something like this in your app.json, but I haven't tested this myself:
```
ios: {  infoPlist: { CFBundleDisplayName: "Your app name" } }
```

See the docs for the [infoPlist](https://docs.expo.io/versions/latest/guides/configuration.html#infoplist) key.

**Comment by carsondarling** [comment]
I was having a similar issue (and was also helped by Segment's support team).

I just added `ios.infoPlist.CFBundleDisplayName` to my `app.json`, and it appears to be working, at least on the simulator. Will be submitting a new version to the app store today and will update if this doesn't fix it.

**Comment by terribleben** [comment]
Fix is landed and will take effect when we roll out SDK 23. It will affect apps running any Expo SDK version.
