### ISSUE TITLE
In App Purchases / iOS / Strange things

### ISSUE THREAD

**Issue by rgetValue** [expo/expo#6801]
Hey.
I use the latest version of react-native, expo and expo-in-app-purchases.
Package «expo-in-app-purchases» is used for auto-renewable subscriptions.
On any Android devices and any countries – everything works well (as aspected).
**On iOS devices – sometimes works, sometimes not :(**

If a user comes in from the US, the connection via the `connectAsync` method never ends. There is neither error nor success. It feels like the application is running in an emulator (but it is not).
If you are logged in from the same iPhone, but from another country (e.g. Ukraine) - everything works well (as aspected).

Who knows what may be the problem? Does it look like a bug? Any suggestion?

**Comment by cruzach** [comment]
I would think this probably has to do with the network connection, or for whatever reason the app isn't able to connect with the App Store.

The best way to get issues handled quickly is to provide a full bug report template, along with a reliable reproducible demonstration of the issue

**Comment by rgetValue** [comment]
@cruzach Thank you for reply.
But I can't reproduce this error.
This error is only appears sometimes on iPhones in US :/

And i can't attach «Reproducible Demo» – because this module doesn't work in emulators.

**Comment by SeNaP** [comment]
Hey. I have same problem, but in Android it doesn’t matter which country. Method 

> connectAsync

never ends and not have response error

**Comment by cruzach** [comment]
I'm going to close this issue for lack of info or a reproducible demo
