### ISSUE TITLE
[docs] slider docs has no clue about the compatibility note for managed flow

### ISSUE THREAD

**Issue by sasurau4** [expo/expo#6802]
## Overview

In v35 docs, slider docs has note for deprecation.

> Deprecated. Use react-native-community/react-native-slider instead if you use the bare workflow. The react-native-community/react-native-slider library is not yet supported in the managed workflow.

https://docs.expo.io/versions/v35.0.0/react-native/slider/

But in v36, slider docs has no note for managed flow.

> Deprecated. Use react-native-community/react-native-slider instead.

https://docs.expo.io/versions/v36.0.0/react-native/slider/

I look for changelog about adding support slider for managed flow, but I couldn't find it. Also, I try to use `@react-native-community/slider` but I couldn't.

The doc of v36 leads misunderstand for compatibility about managed flow. 

I think it would be better to restore the note.

## Related commit

https://github.com/expo/expo/commit/b39d999faf452d05432228151061d92d7f83cb05#diff-b67d1f4ee2f7bec31b41c24e10282bcdL6

**Comment by cruzach** [comment]
fixed in https://github.com/expo/expo/commit/a872b0ddcec435cb3daab664f8372c1e0d82ea26
