### ISSUE TITLE
ImagePicker.launchCameraAsync fails on Android 5.0

### ISSUE THREAD

**Issue by selsamman** [expo/expo#6803]
## 🐛 Bug Report
Get Exception:  - Exception occurred while executing exported method launchCameraAsync on module ExponentImagePicker: null on Android 5 when doing ImagePicker.launchCameraAsync() 
### Environment

Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.2 - /usr/local/opt/node@8/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.11.3

Android 5.0 fails
Android 10 works as expected

### Steps to Reproduce

expo init --template bare-minimum
expo install expo-image-picker
- Perform manual installation steps for Android
- import imagePicker `import * as ImagePicker from 'expo-image-picker';`
- Add a button to take pic `<Button onPress={()=>this.takePic()} title="Take a picture" />`:
- Add code to take pic `async takePic() {
    try {
      let result = await ImagePicker.launchCameraAsync();
    } catch (e) {
      console.log(e.toString());
    }
  }`
yarn android
### Expected Behavior

On Android 10, the user is prompted for camera permission and the camera launches

### Actual Behavior
On Android 5 an exception is thrown

Exception occurred while executing exported method launchCameraAsync on module ExponentImagePicker: null

**Comment by cruzach** [comment]
Does this only happen on bare RN projects? or if you perform the same steps expect on an `expo init --template blank` and run on the same device, is the same exception thrown?

**Comment by selsamman** [comment]
Would seem related to bare RN projects.

It seems to work OK with regular expo on Android 5.0.  It asks for permission and then launches the camera.  It was not clear to me whether you needed to have

 `await ImagePicker.getCameraPermissionsAsync();`  

I added that for good measure on the bare expo project but to no avail.

**Comment by lukmccall** [comment]
Hi @selsamman, I think this was fixed by https://github.com/expo/expo/pull/6736. 
That will be available in SDK 37. 

For now, I'm closing this issue. However, feel free to reopen it if this bug will occur in the newest SDK.
