### ISSUE TITLE
Provide better documentation on how to improve perf in production bundles.

### ISSUE THREAD

**Issue by LAITONEN** [expo/expo#681]
Hello! 

My Expo app becomes much slower if I use a published version in comparison to local, testing version (on the actual device). 

**The app uses** Redux, React-Navigation and Firebase database / authentication. The **3 types** of interactions that **get** significantly **slowed down**, as I have noticed, are the interactions involving utilization of more than 1 page, interactions involving React-Navigation and fetching of the firebase database. 

**The app consists** of multiple pages with the hierarchy like that: DrawerNavigator - 3 Tab Navigators (only 1 is currently functioning) - this TabNavigator consists of 3 tabs and each has a StackNavigator with 4 screens.

**Could something be wrong with my code or that's the flaw on Expo's side?**

**I tried:**
1. Republishing the app.
2. Testing the app with dev mode and debugging turned off.
3. Tried testing app locally with Host - Tunnel, it did not start, so I kept testing with LAN.

In addition, I get **errors** from time to time in my Expo XDE:
1.
`
Error: not opened
    at WebSocket.send (/Users/UserName/workspace/MyApps/appName/node_modules/ws/lib/WebSocket.js:219:16)
    at send (/Users/UserName/workspace/MyApps/appName/node_modules/react-native/local-cli/server/util/webSocketProxy.js:26:12)
    at WebSocket.debuggerSocket.onmessage (/Users/UserName/workspace/MyApps/appName/node_modules/react-native/local-cli/server/util/webSocketProxy.js:49:46)
    at WebSocket.onMessage (/Users/UserName/workspace/MyApps/appName/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/UserName/workspace/MyApps/appName/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/UserName/workspace/MyApps/appName/node_modules/ws/lib/Receiver.js:536:18
    at /Users/UserName/workspace/MyApps/appName/node_modules/ws/lib/Receiver.js:368:7
    at /Users/UserName/workspace/MyApps/appName/node_modules/ws/lib/PerMessageDeflate.js:249:5`

2. 
`
Error starting tunnel: XDLError: failed to start tunnel`

3.
`
Warning: Problems validating asset fields in app.json. See https://docs.expo.io/
 • 'icon' should have dimensions 512x512, but the file at './assets/icons/app.png' has dimensions 192x192.`

4. 
`
Error running `xcrun simctl openurl booted exp://localhost:19000`: An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
The operation couldn’t be completed. Operation timed out
Operation timed out`

5.
`Error installing or running app. Error: Process exited with non-zero code: 60`

**Comment by JulianKingman** [comment]
Try debugging with the chrome inspector, running profiles to see what's slow. Also, check to see if you have too many renders. My guess is there are scripts that are running too often, and/or memory leaks, and/or unnecessary renders. Do you have a server you connect to?

**Comment by LAITONEN** [comment]
1. You mean default Chrome's inspector or I need some sort of external plugin? Same applies to 'running profiles'.
2. I might have too many. Depends on how much is 'too many'.
3. Can I verify your guess with Chrome inspector and 'running profiles'?
4. The only connection that I have is Firebase. Auth/Fetch/Create/Edit/Delete/Update

**Comment by JulianKingman** [comment]
1. Default chrome inspector. Press cmd + D, the "Debug Remote JS". There are two targets available for memory, you want debuggerWorker.js. Also try "Performance" tab. Or press cmd + D then press "Start systrace"
2. Too many is between dozens and hundreds per second, depending on complexity
3. Yes.
4. Check to see how often they run.

**Comment by LAITONEN** [comment]
1. I have tested the **local version** of the app using **Expo's Perf Monitor**. The FPS usually fluctuated between 55 and 60, sometimes had drops to 52, once to 42, once to 19, once to 8. But the significant drops were happening when a **really "heavy" process was ongoing**, so it is expected. My phone (iPhone 6) behaves in the same way with some of App Store apps.
2. Despite that, these lags are **NOTHING** compared to what is happening with a published app, where when I click on the React-Navigation's NavBar button to redirect to a next page in the stack, it takes **10 SECONDS** for the app to do that.
3. I have checked [this page](https://facebook.github.io/react-native/docs/performance.html) of RN docs and the most common reasons for low performance have nothing to do with my app, apart from those that are mentioned in the first item of this list, regarding the heavy load on a JS side.

**Comment by LAITONEN** [comment]
Hello, @skevy ! Just to be sure, are you doing something about this issue, or I am supposed to provide more details?

**Comment by LAITONEN** [comment]
@JulianKingman @skevy

**Comment by LAITONEN** [comment]
@JulianKingman @skevy
I have gone for render debugging approach. 

1. The first page in the stack renders 3 times on the boot-up:

- To show ActivityIndicator while fetching data; 
- To apply React-Navigation setParams; 
- To show SectionList after the data was fetched

2. Other pages do it maximum twice, the second time only if TextInput on the screen has `autoFocus={true}`, which prompts the Keyboard to open, which fires the keyboardWillShow method that adjusts the height of the component so that the view does not go beyond the keyboard.

3. But what drew my attention was the fact that the previous screens in the Stack re-render when I open the subsequent screens. To remind, I have 4 screens, so when I open the 2nd / 3rd screen on top of the 1st / 2nd, all the screens in the Stack re-render. That's probably normal since, in my test app, consisting of 2 screens, the same situation occurs, but I thought that it might be useful to point that out.

4. Tested the app's performance through Xcode project. The same issue persists. So something is definitely wrong with my app, not Expo.

**Comment by ilya-uryupov** [comment]
Hello everyone!

Seems that I'm having the same issue as @LAITONEN.
My app works fast while running expo locally, but the published version is painfully slow, like 20 times.

I've tried running it with combinations of `--[no-]dev`,  `--[no-]minify`, `--[no-]strict` flags when debugging and publishing it with `exp publish` - all the same, on both emulator and a real device.

I've profiled my app with systrace while sending a message (it's kind of a chat app), attaching the results.

![cpu published](https://user-images.githubusercontent.com/6151407/31451662-5a409c80-aeb5-11e7-9394-498babe08b50.png)
![cpu local](https://user-images.githubusercontent.com/6151407/31451663-5a662ab8-aeb5-11e7-8daf-e978b0e8a6ab.png)
Here you can see that CPU usage by mqt.js is much higher in the published version.

![render local](https://user-images.githubusercontent.com/6151407/31451667-5da15d9c-aeb5-11e7-82f9-2ff25ba274f8.png)
![render published](https://user-images.githubusercontent.com/6151407/31451668-5dcbef76-aeb5-11e7-81bf-ee5b7d3f4dfd.png)
UI rendering is slower too, but the most interesting - mqt.js runs for about 5 seconds to send a message and 5 seconds to receive and render it. While the local version does it in 0.5 seconds.

**Comment by ilya-uryupov** [comment]
I have ejected my app - and now when I start it with `exp start --no-dev --minify -c -m localhost --offline` and then publish or build an APK with Android Studio, it works fine.

**Comment by LAITONEN** [comment]
Alright. It seems like I have managed to remedy the performance issues:
- removed all console.logs, which, in fact, get called in the published app just like any other code (I previously thought they are skipped / can't affect the performance in the **published** app)
- used shouldComponentUpdate of React
- other minor optimizations of the code

@JulianKingman cheers!

**Comment by JulianKingman** [comment]
Nice! Now I'm working through the same things...

**Comment by phitien** [comment]
Hi @LAITONEN 

I have the issue, my app is extremely slow on iPhone, and images blink when I switch screen. Could you please share more about using shouldComponentUpdate? It's nice to have an example

Thanks a lot
