### ISSUE TITLE
Branch SDK is not working with expo 

### ISSUE THREAD

**Issue by alaminopu** [expo/expo#6815]
I was following [this document ](https://docs.expo.io/versions/latest/sdk/branch/) to integrate branch in our expo project. However, it's keep failing. 

Getting the following error - 

`t.Branch.subscribe is not a function. (In 't.Branch.subscribe(function(t){if(t&&t.params&&!t.error){if(t.params['+non_branch_link'])return;if(!t.params['+clicked_branch_link'])return}})', 't.Branch.subscribe' is undefined)`

Here is my initial branch integration code:

```javascript
 async componentDidMount() {
    if (Constants.appOwnership === 'standalone') {
      const { Branch } = await import('expo-branch');
      Branch.subscribe(bundle => {
        if (bundle && bundle.params && !bundle.error) {
          // `bundle.params` contains all the info about the link.
        }
     }
}
```

*Info*
"expo": "^36.0.0",
"expo-branch": "^2.0.0",

**Comment by cruzach** [comment]
I suggest reading through the comments on this issue to see the best way to handle the import in a standalone app https://github.com/expo/expo/issues/5349, I'll do some testing and update the docs with the best way to handle that

Also, to inspect whether `expo-branch` has been added to your build, search your Expo build logs for "Adding expo-branch"

**Comment by alaminopu** [comment]
@cruzach Thanks for your suggestion.  Actually, I went through all the comment on that issue and tried to make it work in different way explained there. But nothing seems be working for me on SDK 36. 

To make sure, yes, I checked build log and expo-branch was added there.  You can see the part of gradle log 

<img width="564" alt="Screenshot 2020-01-22 at 4 05 28 AM" src="https://user-images.githubusercontent.com/1296554/72847509-e7e8a580-3ccc-11ea-800b-01015840734b.png">

**Comment by alaminopu** [comment]
@cruzach Did you have a chance to take a look?

**Comment by brentvatne** [comment]
@alaminopu - i'm not sure where you got that code example from but as far as i know `await import` is not valid. the correct way to import branch is mentioned here: https://docs.expo.io/versions/latest/sdk/branch/#importing-branch

**Comment by alaminopu** [comment]
@brentvatne I found the code example from this thread https://github.com/expo/expo/issues/5349 

Last time it didn't work the way it mentioned in the documentation. I will give it another try.

**Comment by brentvatne** [comment]
@alaminopu - this seems like a good solution to allow you to have a mock implementation in expo client and import the real implementation in a standalone app https://github.com/expo/expo/issues/5349#issuecomment-579646702

**Comment by alaminopu** [comment]
@brentvatne it's working with https://github.com/expo/expo/issues/5349#issuecomment-579646702
