### ISSUE TITLE
Android Location.getCurrentPositionAsync on Android only works with ACCESS_FINE_LOCATION Permission

### ISSUE THREAD

**Issue by xeruf** [expo/expo#6816]
### Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: Linux 4.15 KDE neon 5.17
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.6.0/bin/npm
    npmPackages:
      @types/react: ^16.9.0 => 16.9.17 
      @types/react-native: ^0.60.15 => 0.60.31 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.7

Target: Android

### Steps to Reproduce

Call
```
await Location.getCurrentPositionAsync({ ... })
```

with any parameters

### Expected Behavior

A location with Low Accuracy is returned if you have ACCESS_COARSE_LOCATION enabled.

### Actual Behavior

The Promise never returns a value, regardless of the parameters. 
Within the Expo App it works, but when building a bundle for Android and installing it it stops working. It just hangs on the call indefinitely with no error.
This happened on a Samsung Galaxy S7 Edge, but was confirmed from multiple different Android devices.

Only after enabling ACCESS_FINE_LOCATION in `android.permissions` in the app.json does the call return, and then it seems to work for all parameters.

**Comment by cruzach** [comment]
Hm yeah, seems like you might need both `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION`, according to [these docs](https://docs.expo.io/versions/latest/sdk/permissions/#android-permissions-equivalents-inside-appjson)

**Comment by CauueSanttos** [comment]
The error also happens on my SAMSUNG S4 MINI Android 6.0.1 device. The promise has no return, regardless of the level of accuracy.

**Comment by faustoct** [comment]
I can say it works on SAMSUNG A5 but doesn't on SAMSUNG GALAXY S7 Edge.

**Comment by donni106** [comment]
Despite latest documentations we also needed to add the permissions manually:

<img width="229" alt="Bildschirmfoto 2022-02-01 um 15 49 46" src="https://user-images.githubusercontent.com/1942953/151990897-7226f29a-d81c-41ff-8776-6a265a0a75ad.png">

The docs say something about automatically added permissions:

![Bildschirmfoto 2022-02-01 um 15 48 06](https://user-images.githubusercontent.com/1942953/151990676-b610083b-83e3-48a0-883a-c8c64a2a92a8.png)
https://docs.expo.dev/guides/permissions/?redirected#android

![Bildschirmfoto 2022-02-01 um 15 47 54](https://user-images.githubusercontent.com/1942953/151990649-70549742-3f14-430f-83bb-865ec86dc06e.png)
https://docs.expo.dev/versions/latest/sdk/location/#geofencing-methods

Should this still work automatically with latest Expo SDK?

**Comment by donni106** [comment]
Sadly never answered on my last post from February 1st, but @github-actions closed it now. 
@brentvatne can you have a short look please.
