### ISSUE TITLE
Unable to load fonts in PRODUCTION MODE

### ISSUE THREAD

**Issue by KavinduWishwanatha** [expo/expo#6817]
### Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7

Android

### Steps to Reproduce

      await Font.loadAsync({
        Roboto: require("native-base/Fonts/Roboto.ttf"),
        Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
        'OpenSans-Semibold': require('./assets/fonts/OpenSans-Semibold.ttf'),
        'OpenSans-Regular': require('./assets/fonts/OpenSans-Regular.ttf'),
        'OpenSans-Light': require('./assets/fonts/OpenSans-Light.ttf'),
        'KulimPark-Bold': require('./assets/fonts/KulimPark-Bold.ttf'),
      });

### Expected Behavior

  Load Fonts

### Actual Behavior

  [Error: Downloaded file for asset 'OpenSans-Semibold.ttf' Located at http://192.168.8.134:19001/assets/assets/fonts/OpenSans-Semibold.ttf?platform=android&hash=33f225b8f5f7d6b34a0926f58f96c1e9?platform=android&dev=false&minify=true&hot=false failed MD5 integrity check]

**Comment by cruzach** [comment]
Since it looks like there's no spaces in the names of your font files, could you check and see if [this fix](https://forums.expo.io/t/asset-failed-md5-integrity-check/13224) resolves your problem?

**Comment by KavinduWishwanatha** [comment]
@cruzach  still getting the same error. And the error font name changes from time to time.

      await Font.loadAsync({
        'Roboto': require("native-base/Fonts/Roboto.ttf"),
        'Roboto medium': require("native-base/Fonts/Roboto_medium.ttf"),
        'OpenSans Semibold': require('./assets/fonts/OpenSans-Semibold.ttf'),
        'OpenSans Regular': require('./assets/fonts/OpenSans-Regular.ttf'),
        'OpenSans Light': require('./assets/fonts/OpenSans-Light.ttf'),
        'KulimPark Bold': require('./assets/fonts/KulimPark-Bold.ttf'),
      });

Error -> [Error: Downloaded file for asset 'Roboto_medium.ttf' Located at http://192.168.1.4:19001/assets/node_modules/native-base/Fonts/Roboto_medium.ttf?platform=android&hash=99fc0816a09395454061301fefa42bf1?platform=android&dev=false&minify=true&hot=false failed MD5 integrity check]

**Comment by KavinduWishwanatha** [comment]
"dependencies": {
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/netinfo": "4.6.0",
    "axios": "^0.19.0",
    "expo": "^36.0.0",
    "expo-font": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "formik": "^2.1.1",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-aws3": "^0.0.9",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-image-view": "^2.1.9",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.8",
    "react-navigation-tabs": "^2.7.0",
    "uuidv4": "^6.0.1",
    "yup": "^0.28.0"
  },

**Comment by KavinduWishwanatha** [comment]
@cruzach If I refer https://github.com/expo/expo/issues/6817#issuecomment-576904401

      await Font.loadAsync({
        Roboto: require("./assets/fonts/Roboto Regular.ttf"),
        Roboto_medium: require("./assets/fonts/Roboto Medium.ttf"),
        'OpenSans-Semibold': require('./assets/fonts/Open Sans Semibold.ttf'),
        'OpenSans-Regular': require('./assets/fonts/Open Sans Regular.ttf'),
        'OpenSans-Light': require('./assets/fonts/Open Sans Light.ttf'),
        'KulimPark-Bold': require('./assets/fonts/Kulim Park Bold.ttf'),
      });

Error: Asset not found: /Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/assets/fonts/Open%20Sans%20Light.ttf for platform: android
    at /Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/node_modules/metro/src/Assets.js:188:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/node_modules/metro/src/Assets.js:52:24)
    at _next (/Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/node_modules/metro/src/Assets.js:72:9)
Error: Asset not found: /Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/assets/fonts/Roboto%20Medium.ttf for platform: android
    at /Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/node_modules/metro/src/Assets.js:188:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/node_modules/metro/src/Assets.js:52:24)
    at _next (/Users/kavinduwishwanatha/Documents/apps/teamchain/bdata-app/node_modules/metro/src/Assets.js:72:9)...

**Comment by KavinduWishwanatha** [comment]
@cruzach I got apk crashing problem fixed using - https://github.com/expo/expo/issues/6805#issuecomment-576258121

**Comment by cruzach** [comment]
@KavinduWishwanatha it's best if your filenames do not contain spaces, sorry my comment may not have been clear. I meant to try the fix explained in this forum post https://forums.expo.io/t/asset-failed-md5-integrity-check/13224
