### ISSUE TITLE
What should I use to list the photos? "CameraRoll.getPhotos()" function deleted?

### ISSUE THREAD

**Issue by cengizakcan** [expo/expo#6823]
SDK VERSION : 36

What should I use to list photos? Has the "CameraRoll.getPhotos ()" function been deleted? If deleted, there is no similar function in "MediaLibrary". what would you suggest we do about it? Or is this feature forgotten in the SDK?

Thanks.

**Comment by cruzach** [comment]
Always a good idea to check the [changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md#-breaking-changes-1) when upgrading your SDK 🙂 
> CameraRoll: Removed CameraRoll from react-native core, developers are encouraged to use expo-media-library instead

https://docs.expo.io/versions/latest/sdk/media-library/
