### ISSUE TITLE
[android][Location] startLocationUpdatesAsync does not work in Background

### ISSUE THREAD

**Issue by ganest** [expo/expo#6826]
### Environment
Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - ~/programs/node-v12.10.0-darwin-x64/bin/node
      npm: 6.10.3 - ~/programs/node-v12.10.0-darwin-x64/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.5

Android Emulator  Pixel_2_API_28, Pixel_2_API_29, Device Xiaomi Mi Mix 2 Android Version 9, Expo Client 
## Steps to Reproduce

Using the example provided in expo docs regarding background location task or the one I provided.

In order to use Background Location Methods:
a) Grant Permissions.LOCATION
b) Try to receive location updates that can also come when the app is in the background using Location.startLocationUpdatesAsync.

Enable the location task, check it has been enabled, move app to the background and wait to see GPS location in the logs 
### Expected Behavior

See in the logs the GPS location (latitude, longitude) every 5 seconds when app is in background (recent screens)

### Actual Behavior

a) when the app in the foreground works
b) when the app is moved to the background (recent screens, no swiped or killed) stops writing to the log, BUT when Maps app is brought to foreground logging starts again, when Maps goes to the background logging stops.

Tested with Android Emulator  Pixel_2_API_28, Pixel_2_API_29, Device Xiaomi Mi Mix 2 Android Version 9, Expo Client 

### Reproducible Demo

https://snack.expo.io/@ganest/background-location-tracking

**Comment by cruzach** [comment]
I just tested this on Android Emulator Pixel 2 API 28, and background location updates were working when app was backgrounded (using the exact code in your snack). Here are my relevant package versions:

```
expo-task-manager": "~8.0.0",
expo-location": "~8.0.0",
```

Maybe you have different location settings in your emulator? you may have to turn off "Improve Location Accuracy" in Settings - Location in the emulator

**Comment by ganest** [comment]
Dear Charlie, thank you for your prompt response,

I use the same package versions of expo-task-manager, expo-location

I turned off "Improve Location Accuracy" in Android Emulator Pixel 2 API 28, with no luck.

I experimented more on the issue, please allow me to point out some additional details:

a) when the app is moved to the background (recent screens, no swiped or killed), stops writing in the log every 5 seconds (as Ι expected) BUT writes in the log every 10 minutes. 

b) If, in the options object of startLocationUpdatesAsync, I set 
`foregroundService: {
  notificationTitle: 'GPS',
  notificationBody: ' enabled',
  notificationColor: '#0000FF'
}`
and the app is moved to the background (i.e. recent screens) continues writing in the log every 5 seconds BUT when the app is swiped stops writing. 

If the above mentioned behaviour is the expected one then everything is OK, and the issue can be closed, otherwise I have to continue testing to find out what is the problem in my case. I understand that when you can't reproduce the problem it is difficult to help, but any idea for further investigation from my side will be appreciated :-).

Thanks again for your help!

**Comment by cruzach** [comment]
Thanks for the detailed explanation!

In the case of a- that's expected. Generally any kind of background activity is expected to drop in frequency when the app is in the background to preserve battery life. The default policy (of mobile platforms -- not something Expo decided) is to notify when there are significant changes in background location.

For b- I believe that is the same bug reported here https://github.com/expo/expo/issues/3503, so I'm going to close this and we can keep track of it there. If i misunderstood you and that's a different issue, let me know and I can reopen 😄

**Comment by ganest** [comment]
Just a short note/suggestion if may allowed.

Perhaps in the documentation of startLocationUpdatesAsync should be clarified that _the value set to timeInterval property applied only in conjunction with  the foregroundService property_, otherwise the Android OS will decide location update frequency and consequently, the run frequency of the task set in startLocationUpdatesAsync

Thanks again
