### ISSUE TITLE
Expo App does not start anymore

### ISSUE THREAD

**Issue by yesIamFaded** [expo/expo#6827]
I can't start my Expo app. I am getting this error:

```
Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
(0 , _config(...).fileExistsAsync) is not a function
```

It was working properly on Monday. My expo cli and sdk versions are 36.0.0, so the newest ones. Did anyone have this problem as well and knows a possible fix for this?

I am using an Android Studio Emulator.

**Comment by brentvatne** [comment]
the error message says

> Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.

what version of expo do. you have. in package.json? and in. app.json?

**Comment by yesIamFaded** [comment]
I have 36.0.0 like I said above I dont know why it fails because it was working on Monday and nothing has changed since.

**Comment by yesIamFaded** [comment]
I just ran expo upgrade and it told me that I am using the newest version but I upgraded anyways and it ended with this: ```ConfigUtils(...).resolveModule is not a function```

**Comment by brentvatne** [comment]
please run `expo diagnostics` and share output

**Comment by yesIamFaded** [comment]
Expo CLI 3.11.7 environment info:
    System:
      OS: Windows 7
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by yesIamFaded** [comment]
@brentvatne I asked on 3 Platforms.. I really need a fix. Removing node modules and running `npm install `didnt fix it either.

**Comment by yesIamFaded** [comment]
Alright I fixed it by myself. Even though I had the newest cli I had to upgrade it again and then I had to change the blacklist.js file located in node-modules/metro-config/src/defaults/blacklist.js to this:

```
    var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
```
