### ISSUE TITLE
Google Admob's Interstitial & Rewarded Ad & Facebook Interstitial Ad closes the App after opening the Ad

### ISSUE THREAD

**Issue by deadcoder0904** [expo/expo#683]
In Android it ~works smoothly~ opens Ads but then closes the app, but in iOS the screen goes blank as soon as Interstitial or Rewarded Ad is clicked & the app crashes.

For repro try [this](https://github.com/deadcoder0904/expo-google-admob) on iOS Simulator

**Comment by deadcoder0904** [comment]
Also on an Android Device the app closes after opening Interstitial or Rewarded Ad.

Checkout Expo's featured project - [Native Component List](https://expo.io/@community/native-component-list)'s Admob Example in Components tab.

Also as I don't own iPhone the example is only opened in iOS Simulator, not on a real phone.

**Comment by deadcoder0904** [comment]
I've deployed my app to Play Store & the Admob is working fine on Android. Someone with iPhone plz check it for iOS.

I think the problem is with Expo Client App of Android. Bcz when I close Interstitial & Rewarded Ad, it closes the app. My guess is its a problem with Navigation but not sure.

**Comment by terribleben** [comment]
Hey there - I just cloned your repro repo, ran `npm install` and then `exp r` and ran the project on both an iOS simulator and an iOS device. The project works great, interstitial and rewarded ads both show correctly for me. Are you still encountering issues here?

**Comment by deadcoder0904** [comment]
Hey @terribleben as stated in my comment above, the issue is with Expo Client. 


When Interstitial & Rewarded Ad is opened, & after we close it the app takes us to the 1st screen where `Scan QR Code` is there & `All Projects` are there. So its the issue with Expo Client. 

Also, Expo XDE has its issue. The SDK is the best, but the Client & XDE needs some serious work. I didn't realise this was open bcz my issue got solved few days after when u released SDK 21, I'll close this. Thanks again 👍

**Comment by ferroblesh** [comment]
@deadcoder0904 how did you solve this? I am facing same issue. If I close an Ad from Expo client on Android it moves to Expo Home screen(Where you scan QR). I didn't see any update regarding that issue

**Comment by deadcoder0904** [comment]
Nope I didn't solve this. Its not an issue with standalone APK installed from Play Store or App Store. Its a problem with Expo Client. They have made Expo SDK the best, but the Expo XDE & Client kinda sucks. I think they should focus on better XDE & Client or should allocate 1 person at least for that job just like Zeit's team has done for NOW. But it's free, so who cares. So don't add ads if you're gonna use Expo Client. Use ads only in a standalone app, it works then. Ask me anything if you didn't got your doubts cleared.

**Comment by ferroblesh** [comment]
@deadcoder0904 thanks for the answer. It's good to know that will work on standalone app. I have a question about the testDeviceID. Is it used even on standalone app and using it with a real account or is it just for testing?

**Comment by deadcoder0904** [comment]
No it is only for Simulator. I don't remember now but check if it works after removing `testDeviceID` in Simulator. If it works, then don't use `testDeviceID`.
