### ISSUE TITLE
SecureStore - Inconsistent behavior between iOS and Android on Uninstall

### ISSUE THREAD

**Issue by qalqi** [expo/expo#6836]
## 🐛 Bug Report

in iOS, after reinstalling the app, we **can** get the items that were set in the previous install.
in Android, after reinstalling the app, we **cannot** get the items that were set in the previous install.

### Environment
    "expo-secure-store": "^7.0.0",

### Expected Behavior

Expected behavior should same and consistent that one should be able to get items after reinstalling in both android and iOS.

**Comment by SimenB** [comment]
Related: #1459

**Comment by cruzach** [comment]
We document that that behavior only occurs on iOS - https://docs.expo.io/versions/latest/sdk/securestore/

According to the issue Simen linked, this isn't possible on Android atm

**Comment by shamilovtim** [comment]
Despite that being documented no steps have been taken to stop user's apps from being bricked on Android despite this being a relatively easy fix

**Comment by cruzach** [comment]
What's your proposed fix? If you can, we'd love a PR that would provide this same functionality on Android

As for a workaround, you could store the data off the device, and identify the device by [`androidId`](https://docs.expo.io/versions/latest/sdk/application/#applicationandroidid), which is unique to each combination of app-signing key, user, and device.

**Comment by FiberJW** [comment]
To agree with Charlie Cruzan, I believe that this is more of a feature request than a bug report so I'm going to close this issue. 

I'd suggest programming for the common denominator, which is the Android case where data does not persist across installs. If you find any other bugs related to SecureStore, feel free to open up another issue!

P.S. There are some changes to storage in Android 11 if you want to read up on that here: https://developer.android.com/preview/privacy/storage
