### ISSUE TITLE
Expo NetInfo crashing 

### ISSUE THREAD

**Issue by rodricass** [expo/expo#6837]
### Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/bin/node
      npm: 6.13.4 - /usr/bin/npm
    npmPackages:
      @types/react: ~16.9.0 => 16.9.17 
      @types/react-native: ~0.60.23 => 0.60.25 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7

###Platforms 
Both

### Steps to Reproduce

I installed netInfo in expo using the recommended command by expo documentation here https://docs.expo.io/versions/latest/sdk/netinfo/ : `expo install @react-native-community/netinfo`
After that I just tried to get the status of the connection to check if everything was working fine adding the next code: 
```
import NetInfo from '@react-native-community/netinfo';

const MyCases = ({ cases }: Props) => {
useEffect(() => {
      (async function anyNameFunction() {
         const netInfoState = await NetInfo.fetch();
         console.warn(netInfoState);
      })();
   }, []);
};
```

### Expected Behavior

Log the connection status in screen

### Actual Behavior

After doing the mentioned previous steps any time I opened the app in iOS it crashes instantly and closes. 
By the other hand, in android it doesn't closes but it shows this error message: `RNCNetInfo.getCurrentState got 3 arguments, expected 2`
I don't know what to do because, supposedly, in Expo enviroment linking is not needed and not possible

**Comment by cruzach** [comment]
Please include a full repro in your bug report, I just tested this locally on SDK 36 with the following code and didn't get any crash on iOS or error message on android, just 

```
Connection type wifi
Is connected? true
```

here's my app.js:
```
import React, { useRef } from "react";
import { StyleSheet, Text, View } from "react-native";
import NetInfo from "@react-native-community/netinfo";

export default class App extends React.Component {
  componentDidMount() {
    NetInfo.fetch().then(state => {
      console.log("Connection type", state.type);
      console.log("Is connected?", state.isConnected);
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          Change code in the editor and watch it change on your phone! Save to
          get a shareable url.
        </Text>
      </View>
    );
  }
}
```

**Comment by rodricass** [comment]
@cruzach Thanks for your reply, I don't know why but I copy and pasted your code into my code and it worked like a charm. I don't know what I was doing different and why I was getting that error

**Comment by chrissreichl** [comment]
I had the same problem (SDK 36.0.0) and solved it by upgrading to react-native-community/netinfo version from 4.6.0 to **5.0.0.** 

1) Delete the netinfo package:
`npm uninstall @react-native-community/netinfo`
`npm uninstall @react-native-community/netinfo@4.6.0`

2) run `expo start` -> you will get an error, because no netinfo package is installed now 

3) stop expo -> Ctrl + C

4) Install the new netinfo Paget:
`expo install @react-native-community/netinfo@5.0.0`

5) execute `expo start` 

Now the problem should be solved

**Comment by mikeRChambers610** [comment]
I upgraded expo from SDK 35 -> 36 as well. Im not even using a netinfo import anywhere in my app.

Not sure how this error could be occuring if I have no netinfo import... 

"Invariant Violation : Netinfor has been removed from React native"

**Comment by brentvatne** [comment]
@mikeRChambers610 - there could be a library in your app that is using it. you can search node_modules for `NetInfo` and see which library is causing the problem
