### ISSUE TITLE
[TypeError: undefined is not an object (evaluating 'asset.downloadAsync')]

### ISSUE THREAD

**Issue by jpca999** [expo/expo#684]
I am using the latest version of expo everything. 

![image](https://user-images.githubusercontent.com/1026325/30870636-6463a4c8-a2b2-11e7-946f-b28169a997bd.png)

// App.js

`[import { AppLoading, Asset, Font } from 'expo';
// import various screens. 
import CalendarScreen from './screens/propertyScreens/CalendarScreen';
import CalendarTodayScreen from './screens/propertyScreens/CalendarTodayScreen';
import HomeScreen from './screens/homeScreens/HomeScreen';

function cacheImages(images) {
  return images.map(image => {
    if (typeof image === 'string') {
      return Image.prefetch(image);
    } else {
      return Asset.fromModule(image).downloadAsync();
    }
  });
}

function cacheFonts(fonts) {
  return fonts.map(font => Font.loadAsync(font));
}

export default class App extends React.Component {

  state = {
    isReady: false,
  }

  async _loadAssetsAsync() {
    console.log(' 89 -- calling  async _loadAssetsAsync()');
    const imageAssets = cacheImages([
      require('./assets/loginAssets/login1_bg.png'),
      require('./assets/loginAssets/login1_mark.png'),
      require('./assets/loginAssets/login1_lock.png'),
      require('./assets/loginAssets/login1_person.png'),
      require('./assets/signupAssets/back.png'),
      require('./assets/signupAssets/signup_person.png')
    ]);

    const fontAssets = cacheFonts([
      require('./assets/fonts/2BF294_D_0.ttf'),
    ]);

    await Promise.all([
      ...imageAssets,
      ...fontAssets,
    ]);
  }

  componentDidMount() {
    console.log(' App.js  componentDidMount called');
  }

  render() {
    const MainNavigator = TabNavigator({
// HERE COMES ALL THE TAB  VIEW ETC
 settings: { screen: SettingsScreen },
 Login: { screen : LoginScreen },
 signin: { screen : SigninScreen },
 followup: { screen: FollowupScreen },
// MORE  TAB  VIEW ETC
});

return (
  <View style={{ flex: 1 }}>
      <Provider store={store}>
        <View style={styles.container}>
          <MainNavigator />
        </View>
      </Provider>
  </View>
);
}
}`

**Comment by nikki93** [comment]
This is not an issue with Expo, so please ask in the forums. The GitHub issue spot is for issues with the library, not for debugging errors in your code. In any case, in your code, the function `cacheFonts(...)` maps `Font.loadAsync(...)` over its parameter, which, at its callsite, is an array of modules. This doesn't correspond to the [interface of `Font.loadAsync(...)`](https://docs.expo.io/versions/latest/sdk/font.html), which requires either a two arguments: a name and a module, or a map of names to modules. Presumable you want to just pass in the map to `Font.loadAsync(...)`, like `Font.loadAsync({ 'coolFont': require('./assets/fonts/2BF294_D_0.ttf') });`.
