### ISSUE TITLE
Server not correctly configured - expo-av Sound.loadAsync()

### ISSUE THREAD

**Issue by Ananas120** [expo/expo#6840]
Hello, i am trying to do a client-server app with client in react-native and server with Flask (python). 
I made a very simple server which uses ‘send_file(filename, mimetype=‘audio/wav’)’ to send a wav file to the client and i use Sound.loadAsync(‘GET’, url) to load the file (and play it after loading) but i get the error : « the server is not correctly configured - The AVPlayerItem has failed with error code -11850 and domain ‘’AVFoundationErrorDomain’’ »

Can someone help me or just say me the format of response expected by loadAsync ? 
The server receives well the request but i suppose ‘send_file(...)’ is not the right way to send file but i don’t know how to do this 

Thank you !

**Comment by Ananas120** [comment]
Solved but i don’t know why when i load mp3 file, it works but when it’s wav file, it doesn’t work... i close this issue discussion and open an issue

**Comment by dmbrooking** [comment]
how did you solve this?

**Comment by Ananas120** [comment]
I just send mp3 file instead of wav file and it works (don’t know why ^^’) you can convert file format with pydub (to save as mp3) if you want
