### ISSUE TITLE
understanding invariant violation requireNativeComponent error

### ISSUE THREAD

**Issue by madhums** [expo/expo#6841]
Hi, I have been working on a new feature in react-native-maps, it gives the ability to use mbtiles as source for map data. Unfortunately I have been [running into](https://github.com/react-native-community/react-native-maps/pull/2388#issuecomment-569784551) this error `Invariant violation: requireNativeComponent: "AirMapMbTile" was not found in UIManager.`

I looked into issues posted in react-native-community and also in Expo to find out what really is going on but I am unable to find any kind of documentation/knowledge on why this error occurs and what could be done to fix it. 

I have seen a lot of comments about removing node_modules, Pods, reinstalling, downgrading etc etc which doesn't seem to solve the real problem without proper understanding. 

Can anyone explain why this happens?

**Comment by cruzach** [comment]
Hi @madhums ! First of all, thanks for working on that feature for `react-native-maps` especially since we pull that library into the Expo SDK 😄 

I'm assuming since you're working on a new feature for it that you're working in the bare workflow, since in the managed workflow you only have access to changing the JS. So this probably isn't a bug with the Expo SDK, so I'm going to close this issue.

As for where to go next, I would make sure you're linking the packages correctly  and exposing `AirMapMbTile`

**Comment by madhums** [comment]
@cruzach Yea so exactly, I am not saying it's a bug I instead want to understand how this exposing works and where to do this. Can you please elaborate?

P.S: I am adding `node_modules/react-native-maps/lib/ios/AirMaps/` to the user header search paths in the build settings of xcode but it doesn't seem to work.

**Comment by madhums** [comment]
Is there any documentation on how to do this?

**Comment by cruzach** [comment]
This page from the react native docs might help https://facebook.github.io/react-native/docs/native-modules-ios

Otherwise, i suggest taking a look at the `react-native-maps` repo

**Comment by madhums** [comment]
Hi @cruzach I am extremely sorry to bother you BUT neither of those two are helpful. I have spent hours going through issues, asking about this particular issue in rn maps community without any help. I also followed the linking process as they suggest on the [rn docs](https://facebook.github.io/react-native/docs/linking-libraries-ios) but I can't get it to work. 

Since this is particularly related to expo I am asking here. There are a lot of issues relating to this particular error all over the web, unfortunately there's no documentation whatsoever on troubleshooting this. So I would like to ask you again, do you know why this happens and how to solve this issue? If not, could you may be cc anyone who does know a little more in depth?

My intention is to create some knowledge so that it's easier to troubleshoot errors such as these.

**Comment by madhums** [comment]
So I am just gonna explain one more time what issue I am facing:

I added a new feature to react-native-maps which includes native code. I have forked react-native-maps, so I am using this new feature with npm install via a GitHub branch. I have ejected expo and I using ExpoKit to make use of OTA updates. When I run the application, I get "Invariant violation requireNativeComponent AirMapMbTile not found in UIManager".

Should I not be using ExpoKit?

**Comment by madhums** [comment]
Ok so with bare workflow it works but with ExpoKit it doesn't. @cruzach do you have any idea why it doesn't work with ExpoKit? And possibly think of ways we can make it work with ExpoKit?

**Comment by cruzach** [comment]
If you're adding a new feature to `react-native-maps`, I would focus on testing it in the bare workflow. Expokit will be deprecated soon in favor of the bare workflow, once we support OTA updates in the bare workflow (SDK 37)

Sorry, I'm not sure exactly why it isn't working in Expokit. Possibly it's missing this change https://github.com/expo/expo/pull/6844 ? If you're not using `expokit v36.0.1`, but that's just a guess
