### ISSUE TITLE
google signIn silently 

### ISSUE THREAD

**Issue by Eugenelee** [expo/expo#685]
how to sign the user in silently when the user opens the app. i want to get a new id token every time when user opens the app.

**Comment by jimmylee** [comment]
Hey @Eugenelee,

Unfortunately it would be difficult to help you with this problem without a code example, but the good news is that it isn't necessarily Expo specific.

Here is a great tutorial I found for you that will be able to help you understand the ins and outs around doing Google Authentication. https://medium.com/@reginald.johnson/social-login-in-react-native-expo-io-and-aws-api-gateway-lambda-authentication-53cac566594b -- This link will explain some of the implementation details more throughly so you can have a better idea of what to do.

Another useful resource is our Google Auth docs: https://docs.expo.io/versions/latest/sdk/google.html#content

If you end up trying google authentication and theres something wrong on our end, please feel free to come back and open another issue.

Best of luck!
