### ISSUE TITLE
Amplitude.logEvent promise not resolving

### ISSUE THREAD

**Issue by ai-dev** [expo/expo#6859]
### Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.11.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.7

### Steps to Reproduce

Try to await on Amplitude.logEvent('EVENT_NAME')

### Expected Behavior

Amplitude.logEvent promise is resolver

### Actual Behavior

The promise is not resolved and no error is provided

### Reproducible Demo
I prepared a demo snack that can recreate the problem: [https://snack.expo.io/Bk!krJ5bU](https://snack.expo.io/Bk!krJ5bU)

**Comment by cruzach** [comment]
Neither of those methods are asynchronous (see the [source](https://github.com/expo/expo/blob/sdk-36/packages/expo-analytics-amplitude/src/Amplitude.ts)), so you don't need to `await` them

Aside from that, it's possible that the Amplitude SDK has trouble running in Snack. With this code, I was able to run it locally and see events in the amplitude project dashboard:

```
export default class App extends React.Component {
  test = () => {
    console.log("testing");
    Amplitude.initialize("MY-API-KEY");
    Amplitude.logEvent("here's my cool event name");
    console.log("blah");
  };
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>Test</Text>
        <Button title="press" onPress={this.test} />
      </View>
    );
  }
}
```

**Comment by ai-dev** [comment]
Here logEvent is defined to returns a promise: [https://github.com/expo/expo/blob/master/packages/expo-analytics-amplitude/src/Amplitude.ts#L53](https://github.com/expo/expo/blob/master/packages/expo-analytics-amplitude/src/Amplitude.ts#L53)

**Comment by cruzach** [comment]
True, but it doesn't look like that's the source of the issue. I've tested `await`ing the calls (the promises resolve, just to `undefined`), not `await`ing them, and in both situations it works and I can see the events in the Amplitude dashboard

**Comment by ai-dev** [comment]
Yeah, I just want to clarify: I'm not saying that it's not working. Even though the promise (not-promise) is not resolving, I can see the event in Amplitude, it works fine.

I guess the issue it's just with the typescript definition of the function. At this point, I agree it's not a bug, but a definition problem.

**Comment by cruzach** [comment]
ah okay, sorry that wasn't clear

**Comment by ai-dev** [comment]
No worries, and thanks for your comments
