### ISSUE TITLE
No version of @exponent/home compatible with this version of Exponent (SDK versions 1.19.2 and platform "ios")

### ISSUE THREAD

**Issue by pritikumbhar** [expo/expo#686]
I have detached project from expo with expo detach. When I install the app from Xcode , it gives me error "No version of @exponent/home compatible with this version of Exponent (SDK versions 1.19.2 and platform "ios")".
My sdkVersion in app.json is 21.0.0.
Need help with this.

**Comment by terribleben** [comment]
In your detached Xcode project, under `Supporting/EXSDKVersions.plist`, you should see something like this. Does that look right?
![image](https://user-images.githubusercontent.com/1316332/30950116-9812dbe0-a3cf-11e7-8b5c-ff4b6d2cd369.png)

**Comment by iThinker** [comment]
I have same issue. I see same thing as on screenshot. I think it does not bundle resources properly. I have 400 megs of sound assets, but produced app is like 40 megs. But I have no idea how to make it bundle stuff properly. All guides say that running from xcode is good enough.

**Comment by terribleben** [comment]
Closing this because I didn't get info back from the original reporter. Let me know if you're still seeing this same error message, and if so, let me know what `EXSDKVersions.plist` says, and also what your `app.json` says for `sdkVersion`.
