### ISSUE TITLE
expo-ads-admob not working in expo SDK 36

### ISSUE THREAD

**Issue by jrvq** [expo/expo#6860]
### Environment

System:
      OS: Linux 4.10 Linux Mint 18.3 (Sylvia)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.12.1 - /usr/bin/npm
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
      expo-ads-admob: "^8.0.0",

Ejected bare app 
Android

### Steps to Reproduce

1. eject to bare  ( expo  SDK 36 )
2. `sudo expo install expo-ads-admob`

### Expected Behavior

The app would start and expo-ads-admob module would work 

### Actual Behavior

I'm getting these warnings:

The native view manager required by name (ExpoAdsAdMobBannerView) from 
NativeViewManagerAdapter isn't exported by @unimodules/react-native-adapter.
Views of this type may not render correctly. Exported view managers: [ExpoLinearGradient].

The native view manager required by name (ExpoAdsPublisherBannerView) from 
NativeViewManagerAdapter isn't exported by @unimodules/react-native-adapter.
 Views of this type may not render correctly. Exported view managers: [ExpoLinearGradient].

Error: The method or property expo-ads-admob.setTestDeviceIDAsync is not available on android, are you sure you've linked all the native dependencies properly?

TypeError: undefined is not an object (evaluating '_ExpoAdsAdMobInterstitialManager.default.setAdUnitID')
  setAdUnitID$
  
### Notes

When I try to recompile the app it will immediately close it without any warnings or errors.
I'm using real device.
I have installed react-native-unimodules.

### Sample Code

```
import { AdMobInterstitial } from 'expo-ads-admob';

console.log(AdMobInterstitial); // {"addEventListener": [Function addEventListener], "dismissAdAsync": [Function dismissAdAsync], "getIsReadyAsync": [Function getIsReadyAsync], "removeAllListeners": [Function removeAllListeners], "removeEventListener": [Function removeEventListener], "requestAdAsync": [Function requestAdAsync], "setAdUnitID": [Function setAdUnitID], "setTestDeviceID": [Function setTestDeviceID], "showAdAsync": [Function showAdAsync]}

try {
      await AdMobInterstitial.setAdUnitID(
        'ca-app-pub-3940256099942544/1033173712'
      );
      await AdMobInterstitial.setTestDeviceID('EMULATOR');
    } catch (e) {
      console.log(e); // [TypeError: undefined is not an object (evaluating '_ExpoAdsAdMobInterstitialManager.default.setAdUnitID')]
    }

```

**Comment by eladwass** [comment]
what is the latest supported version?

**Comment by robertveloso** [comment]
expo init in bare template and adding expo-ads-mobs does not work.
"expo": "~37.0.3",
"expo-ads-admob": "^8.1.0",

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by robertveloso** [comment]
I solved the problem by updating the google-services.json, the documentation is outdated now that AdMob has been integrated to firebase.

**Comment by ha77an** [comment]
@robertveloso 
I solved the problem with this way

Remove the Node module.
 `rm -rf node_modules/`

 install again
 `npm install`

 then try with
`expo start`
