### ISSUE TITLE
typescript warning

### ISSUE THREAD

**Issue by jazzdragon** [expo/expo#6866]
### Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^4.0.12 => 4.0.12
      @types/expo: ^32.0.13 => 32.0.13
      @types/react: ^16.9.0 => 16.9.19
      @types/react-native: ^0.60.15 => 0.60.31
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.2.3

    expo-linear-gradient@8.0.0

### Steps to Reproduce

Add LinearGradient to a typescript project

### Expected Behavior

Typescript produces no errors

### Actual Behavior

Seeing errors:
```
Error:(35, 13) TS2605: JSX element type 'LinearGradient' is not a constructor function for JSX elements.
  Type 'LinearGradient' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

TS2607: JSX element class does not support attributes because it does not have a 'props' property.
```

**Comment by cruzach** [comment]
Could you share how you're using LinearGradient? We provide a few examples in the [docs](https://docs.expo.io/versions/latest/sdk/linear-gradient/), and I'm not getting any TypeScript errors/warnings

**Comment by jazzdragon** [comment]
Adding `"allowSyntheticDefaultImports": true` solves this issue for me

**Comment by aniketicloud** [comment]
The same issue is happening even after I use the LinearGradient as per the docs.
