### ISSUE TITLE
Expo on reactxp - fails when running video

### ISSUE THREAD

**Issue by vinils** [expo/expo#687]
I've create a simple project with expo running on reactxp and every thing is working fine except the video´s reactxp module that fails by some reason it makes ts look for another module typings in this module node_modules

I've forked reactxp on microsoft repo ([here](https://github.com/Microsoft/reactxp/pull/236)) and i'm trying to push this sample there but I'm stacked with this problem.

Is there anyone that could give a hand with that problem?

I think reactxp has a great potential and would be nice to have expo running a cross platform **(including web)** sample there.

**Comment by quinlanj** [comment]
hey @vinils, we don't support it currently, if reactxp gets it working we'd be happy to link to it but we're a small team and we have a lot of resource constraints. 

If you have a feature request, please vote/post about it here https://expo.canny.io/feature-requests
