### ISSUE TITLE
Font.loadAsync throws "Directory for file ... doesn't exist" after changing "slug" in app.json 

### ISSUE THREAD

**Issue by CostachescuCristinel** [expo/expo#6875]
After changing the `"slug"` in `app.json` in an Expo managed app, `Font.loadAsync` started throwing an error, which seems related to a caching issue:

> Directory for file:///Users/work00/Library/Developer/CoreSimulator/Devices/1F0041D9-151F-405C-9642-6CE5788D2751/data/Containers/Data/Application/41AE6FCE-3359-4DFF-9305-FB52449542AD/Library/Caches/ExponentExperienceData/%2540some-user-name%252FSomeDifferentSlug/ExponentAsset-321de678e592d0b8f44f1a82d7ca4b62.ttf doesn't exist.

### Any combination of the following doesn't work:
 * Starting the deveopment server with `expo start -c`
 * Clearing the app list in the Expo client
 * Closing the Expo client app on the device from the task manager, and reopening it

### The following solutions work:
* Changing the `"slug"` back to it's previous value
* Reinstalling the Expo client on the device

The issue happens on both simulator and real iOS devices.
The issue has not been tested on Android devices - I suppose, on Android you could open the app info in the device settings, and then clear cache/storage which behaves similar to reinstalling the Expo client.

### Development Environment:
* expo-cli 3.11.7
* Expo SDK36
* Mac OS 10.15.12
* XCode 11.3 - Simulator Version 11.3 (SimulatorApp-912.5 SimulatorKit-570.3 CoreSimulator-681.17)
* iOS Simluator devices: iPhone 5S, 6S, XR, iPad Pro (9.7 inch) with iOS 12.1/12.2
* iOS Real device: iPhone SE with iOS 13.3

While reinstalling the Expo client is a solution, we shouldn't have to do that.
I also don't understand the reasoning behind using the `"slug"` field instead of the `"name"` field for caching directories, but that's a minor detail.

I would very much appreciate if the Expo client allowed us to manually clear the Expo cache for the apps. Or, when clearing the app list in the Expo client, the cache for these apps to be cleared as well.

**Comment by cruzach** [comment]
hi @CostachescuCristinel - sorry about this, that's a pretty annoying bug since it took a full reinstall to get past

We have an [open issue](https://github.com/expo/expo/issues/5129) already to implement some options in the client app to let users clear the cache

I think it might be more worthwhile to close this and comment on that existing issue with this specific bug so that we know to test for it once we implement this feature.

**Comment by CostachescuCristinel** [comment]
Hi @cruzach,
Sure, I can follow that thread for updates on the cache features. I hope it gets fixed soon.

Best regards!
