### ISSUE TITLE
Problem with Location.getCurrentPositionAsync

### ISSUE THREAD

**Issue by xavigiro15** [expo/expo#688]
Hi,

I'm using Expo XDE v2.20.1, with SDK version 21 and Xcode 9, on a Macbook. I run my app in the iOS simulator.

When I invoke `Location.getCurrentPositionAsync`it hangs indefinitely without returning or throwing an error.

If I call the function here below, it prints the first console log ("starting") but nothing else, and the promise is neither resolved nor rejected.

```js
async function getLocation () {
  const permission = await Permissions.askAsync(Permissions.LOCATION);
  const { locationServicesEnabled } = await Location.getProviderStatusAsync();
  if (permission.status === 'granted' && locationServicesEnabled) {
    console.log('starting');
    let location;
    try {
      location = await Location.getCurrentPositionAsync();
    } catch (e) {
      console.log('error', e);
    }
    console.log('done');
    return location;
  } else {
    return false;
  }
}
```

Notice that `Permissions.askAsync` and `Location.getProviderStatusAsync` work perfectly fine.

And now the crazy part: the same exact code when run on my colleague's computer in the iOS simulator, or directly on my iPhone works all fine.

I've tried to re-install Xcode and Expo, but it didn't help. Do you have any idea what is causing this and how to fix it? Thanks!

**Comment by xavigiro15** [comment]
Any update on this?

@terribleben @jesseruder @brentvatne @nikki93 @ide @skevy @janicduplessis @nsillik @jeff-da

**Comment by terribleben** [comment]
Hi, are you in a detached (ExpoKit) app? We have had one similar report from a user who detached their app and then needed to add `NSLocationAlwaysAndWhenInUseUsageDescription` to the Info.plist.

If you're not using ExpoKit, can you provide a small app that reproduces this behavior with https://snack.expo.io ?

**Comment by xavigiro15** [comment]
Hi @terribleben I'm not in a detached (ExpoKit) app. If you like I can create a small app to reproduce this behaviour although: 1) It would contain exactly the same code I pasted above; 2) Like I mentioned that code actually works fine on my colleague's computer.
Is there anything else that you suggest to try? Thanks!

**Comment by terribleben** [comment]
Can you wrap in a `Permissions.getAsync` call as well, and see if that fixes it? On some devices, if the user rejects permission, Apple will not prompt for permission a second time.

**Comment by skasanibanyan** [comment]
@terribleben I am facing the same issue on android in detached(ExpoKit) app.

**Comment by bhtruong93** [comment]
I just ran into this issue but solved it choosing an option from the locations menu (ex. Debug > Location > Apple)

**Comment by nahuelhds** [comment]
In my case, doing `Location.getCurrentPositionAsync({ enableHighAccuracy: true })` does the trick (I'm on Genymotion)

**Comment by rosnaib11** [comment]
In my case, After I upgraded from sdk v31 to v32 after that my `Location.getCurrentPositionAsync` not working anymore what happen is it goes to infinite waitning.

 Setting `enableHighAccuracy: true` does the trick.
