### ISSUE TITLE
[Web] expo-app-auth support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6883]
Add web support to the `expo-app-auth` package with strong documentation on how to use it. 
The module should implement [AppAuth-js](https://github.com/openid/AppAuth-JS) in the browser.

**Comment by benbowler** [comment]
Hey Even, I might look at building this out in the coming months. Is anyone else on the case? Any style guidelines beyond the contributing.md?

**Comment by EvanBacon** [comment]
No one is currently working on this. We may remodel the native API to look more like the JS API.

**Comment by EvanBacon** [comment]
I'll be closing this in favor of the new AuthSession API which has web support and performs all of the same functionality. https://docs.expo.io/versions/latest/sdk/auth-session/

**Comment by SuperManfred** [comment]
### You're such a legend @EvanBacon ###
