### ISSUE TITLE
[Web] expo-google-sign-in support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6884]
Implement https://developers.google.com/identity/sign-in/web/sign-in

**Comment by jletey** [comment]
@EvanBacon Would love to see this feature! Would love some help getting started 🙏

**Comment by zackify** [comment]
@EvanBacon i needz this, thanks for all your hard work on expo web!

**Comment by joshglenn** [comment]
@EvanBacon You say you want help implementing this on web, what do you envision exactly? Another expo package like `expo-google-app-auth`, but specifically for web? Or, someone using `Platform.OS` checks in [Google.ts](https://github.com/expo/expo/blob/master/packages/expo-google-app-auth/src/Google.ts)?

**Comment by yosukesuzuki** [comment]
@EvanBacon what's the status of this issue after that? I'd like to implement my new application for ios/android/web with this.

**Comment by EvanBacon** [comment]
Closing in favor of expo-auth-session which supports web. We will be deprecating expo-google-sign-in in favor of `expo-auth-session` too. https://docs.expo.io/guides/authentication/#google
