### ISSUE TITLE
[Web] expo-analytics-amplitude support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6886]
https://github.com/amplitude/Amplitude-JavaScript

**Comment by ashermja** [comment]
I was wondering about this, will amplitude-js replace the need for expo-analytics-amplitude, now that it supports react native?

https://help.amplitude.com/hc/en-us/articles/360025220532-React-Native-SDK

**Comment by davidbiller** [comment]
> I was wondering about this, will amplitude-js replace the need for expo-analytics-amplitude, now that it supports react native?
> 
> https://help.amplitude.com/hc/en-us/articles/360025220532-React-Native-SDK

Any infos here?

**Comment by davidbiller** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-04-14 at 19 00 17](https://user-images.githubusercontent.com/7137361/79252615-38ae0b80-7e82-11ea-8a7c-7f7dcaa1f6ff.png)
https://github.com/amplitude/amplitude-javascript#react-native
This library now supports react-native. It has two dependencies on react-native modules you will have to install yourself:

react-native-device-info Tested with version 3.1.4
@react-native-community/async-storage Tested with version 1.6.2

**Comment by brentvatne** [comment]
see this for ios/android: https://docs.expo.io/versions/latest/sdk/amplitude/

this issue is about web support specifically

**Comment by davidbiller** [comment]
> see this for ios/android: https://docs.expo.io/versions/latest/sdk/amplitude/
> 
> this issue is about web support specifically

Yes i know. 
I tested the https://help.amplitude.com/hc/en-us/articles/360025220532-React-Native-SDK 
So we could use the JS SDK, but they require this two native libs. So maybe we can create a PullRequest to check if its an expo app than use expo modules instead of @community modules

**Comment by sreuter** [comment]
@brentvatne I was looking into picking this up. The problem is that all the non-async calls have been deprecated, while amplitude-js doesn't have async calls at all. How would you go about this?

**Comment by sreuter** [comment]
@EvanBacon @brentvatne Any idea on this yet? Right now it seems there's no analytics for module at the time that supports both, mobile and web. Would be awesome to hear your thoughts!

**Comment by brentvatne** [comment]
@sreuter - i'm not sure i follow. we don't have bandwidth to look into this but if you open a pr with a proposal we can possibly land it for sdk 42

**Comment by brentvatne** [comment]
we don't plan on adding support for web support to expo-analytics-amplitude. we will likely move towards deprecating expo-analytics-amplitude in favor of https://www.npmjs.com/package/@amplitude/react-native

**Comment by gyl89** [comment]
I ran into the same issue and contacted amplitude helpdesk.

It seems though that the library @amplitude/react-native is a third-party library that is NOT compatible with expo managed workflow.

My choice is then going to bare workflow or changing the analytics solution.
