### ISSUE TITLE
[Web] expo-analytics-segment support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6887]
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/

**Comment by XavierOlland** [comment]
https://docs.expo.io/versions/latest/sdk/segment/

Or be more specific...

**Comment by gizmoGremlin** [comment]
Hi, I'd like to work on this if its not too time sensitive.

**Comment by EvanBacon** [comment]
@gizmoGremlin, go for it! :D

**Comment by gizmoGremlin** [comment]
I'm having trouble with running the e2e tests in bare-expo (webpack can't find several modules). I'm on linux, Could that be the problem?  I remember reading something in the expo docs about MacOS being priivileged (I can't find it now to confirm unfortunately ). I need to run the e2e tests as the script that initializes segment analytics requires the global variable window.

**Comment by doertli** [comment]
@gizmoGremlin are you still working on this, or did you switch horses?

**Comment by gizmoGremlin** [comment]
Switched 😄

**Comment by doertli** [comment]
Expo Firebase Analytics? Or...?

**Comment by gizmoGremlin** [comment]
No, I'm just not working on it, I got busy. Segment analytics is still a
good choice.

**Comment by doertli** [comment]
@gizmoGremlin can I ask if you've incorporated Segment manually (eg: via HTTP APIs) or not at all? Trying to figure out best way to get analytics events distributed from Expo to rest-of-business systems (Facebook, Salesforce or Adobe Marketing etc). Not a lot of other options for event distribution with Expo at the moment.

**Comment by gizmoGremlin** [comment]
Sorry I can't be of more help. I stop working on this before I really got
into the weeds. Good Luck

**Comment by nandorojo** [comment]
Here's what I did to get segment to work in web.

**1. `expo customize:web`**

- Select `web/index.html`
- Open `web/index.html`
- Add the `segment` JS script in the HTML in your HTML `head` tag. Mine looked like this:

```html
<head>
  ...
  <script type="text/javascript">
    // prettier-ignore
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
			analytics.load("YOUR_KEY_HERE");
			analytics.page();
			}}();
  </script>
</head>
```

Replace your API key where it says `YOUR_KEY_HERE` above.

**2. Create `analytics` folder**

I have a folder where all of my analytics functions sit. Call it `/analytics`. It looks something like this:

- `analytics`
  - `index.ts`
  - `index.web.ts`

**`analytics/index.ts`**

```ts
import * as Segment from 'expo-analytics-segment'

class Analytics {
  constructor() {
    Segment.initialize({
      iosWriteKey: 'your_ios_write_key',
      androidWriteKey: 'your_android_write_key'
    })
  }
  track(event: string) {
    Segment.track(event)
  }
}

const analytics = new Analytics()

export default analytics
```

**`index.web.ts`**

```typescript
declare global {
  interface Window {
    analytics: any
  }
}

const analytics = {
  track: (event: string) => {
    window.analytics.track(event)
  }
}

export default analytics
```

**3. Use `analytics`**

In any file:

```js
import analytics from './path/to/analytics'

analytics.track('works!')
```

**Comment by andy-HM** [comment]
Hello - do you know when this will be officially supported in the Expo toolkit?

**Comment by cruzach** [comment]
FYI Segment has recently released a [brand new react native library that is Expo-compatible](https://github.com/segmentio/analytics-react-native/blob/master/README.md), and it is likely that we will deprecate `expo-analytics-segment` in favor of their new library, so adding web support to the existing `expo-analytics-segment` library probably will not happen, and instead you should ask the Segment team if they plan on adding web support
