### ISSUE TITLE
[Web] expo-face-detector support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6888]
Pending good API to run in a worker.

**Comment by thomas-coldwell** [comment]
Could use [face-api.js](https://github.com/justadudewhohacks/face-api.js)

**Comment by no-1ne** [comment]
https://blog.tensorflow.org/2020/01/photobooth-lite-on-raspberry-pi-with-tensorflow-lite.html 
![image](https://user-images.githubusercontent.com/11027129/135566541-865dea80-5337-44de-8e03-6c92757bba02.png)

https://github.com/tensorflow/tfjs-models/tree/master/blazeface for face detection and then above for smiling probability 
https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection for landmarks

**Comment by no-1ne** [comment]
Reopen feature didn't land yet
