### ISSUE TITLE
[Web] expo-keep-awake support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6889]
https://whatwebcando.today/wake-lock.html

**Comment by safaiyeh** [comment]
I like this one, I'll pick this up this weekend.

**Comment by jarvisluong** [comment]
This sounds interesting, can I take this one? @EvanBacon

**Comment by lallenlowe** [comment]
This would be great on iOS web where we've been having an issue where audio stops playing when the screen locks.

**Comment by markymc** [comment]
@EvanBacon @jarvisluong Any news on this? I saw it was marked as "pending" on https://docs.expo.dev/versions/latest/sdk/keep-awake/.

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/pull/15826

**Comment by markymc** [comment]
Ping to keep this open.

**Comment by markymc** [comment]
@EvanBacon @brentvatne Any chance we can re-open this? It's still not merged.

**Comment by brentvatne** [comment]
@markymc - this is more of a feature request than a bug, so it's not well suited to be an issue. you can track any progress in https://github.com/expo/expo/pull/15826. this feature is not a priority for us at the moment and you may want to use patch-package to pull the diff to your app and modify it as needed

**Comment by zteil** [comment]
> https://whatwebcando.today/wake-lock.html
