### ISSUE TITLE
[Web] expo-notifications support

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6895]
Migrate web notifications from `expo` to `expo-notifications` and ensure they work with https://expo.io/notifications

**Comment by upskillie** [comment]
Is it possible to share the explanation on how can one go about it?

**Comment by jjg77** [comment]
hey Evan, do you know when this feature will be available? SDK37?

**Comment by actuallymentor** [comment]
This issue is tagged as `help=wanted`. What can I do to help this along?

**Comment by actuallymentor** [comment]
Bumping. Please give some indication what can be done and I'm happy to spend some time on a pull request.

**Comment by actuallymentor** [comment]
Tagging @ide and @bbarthec as you commented on my previous PR. What can I do to make this happen? With some basic guidance I'm happy to draft a PR.

**Comment by ide** [comment]
I really appreciate the collaborative sentiment. There isn't a lot of possible work on the client library quite yet because we need to support web credentials (i.e., VAPID) for Expo services. There are several prerequisite steps to get there (e.g., complex database migrations) that take time to complete but will also lay the groundwork to support notifications across more platforms in the future. I expect this work to be done in a few months.

**Comment by actuallymentor** [comment]
Thanks for the elaboration, if there is anything I can support with during the process let me know!

**Comment by victorwads** [comment]
You guys are planning to use Firebase Cloud Messaging to send Web notifications?

**Comment by manny1001** [comment]
Hi everyone, hope you are all well .

Can any date be assumed for this feature? 
Regards ,

**Comment by ide** [comment]
We aren't actively working/planning to work on this right now. Our focus is more on adding support for custom native code and EAS.

**Comment by manny1001** [comment]
> We aren't actively working/planning to work on this right now. Our focus is more on adding support for custom native code and EAS.

okay Thanks for the quick response much appreciated

**Comment by zchwyng** [comment]
+1

**Comment by saulamsal** [comment]
@ide any updates regarding this?

**Comment by ide** [comment]
No, there's nothing to announce. We announce features like this on https://blog.expo.dev/, often as part of SDK release notes if one day this is a feature offered with EAS.
