### ISSUE TITLE
Documentation for experimental MapView react-native-web

### ISSUE THREAD

**Issue by chownation** [expo/expo#6896]
What's the best approach for using the experimental MapView compatible for Web (in lieu of import from react-native-maps)?

**Comment by EvanBacon** [comment]
You can use the experimental Expo fork https://github.com/expo/react-native-maps/pull/2 which has partial web support using Leaflet.

**Comment by YahyaBagia** [comment]
@EvanBacon Thank you man for your efforts. 

As the documentation says [here](https://docs.expo.io/versions/latest/sdk/map-view/#web-setup), we can include javascript SDK in our index.html file.

Does that mean we can use Google Maps on Web, instead of Leaflet?

I followed the instructions, (created API Key for JS, included script tag in index.html, restricted google maps API Key to allow my local ip address, etc.) but it always uses Leaflet on the web.

**Comment by vrinch** [comment]
> @EvanBacon Thank you man for your efforts.
> 
> As the documentation says [here](https://docs.expo.io/versions/latest/sdk/map-view/#web-setup), we can include Google Maps Javascript SDK in our index.html file.
> 
> Does that mean we can use Google Maps on Web, instead of Leaflet?
> 
> I followed the instructions, (created API Key for JS, included script tag in index.html, restricted google maps API Key to allow my local ip address, etc.) but it always uses Leaflet on the web.

Also, it the leaflet map does not load on mobile browsers, both for safari and google chrome

**Comment by vrinch** [comment]
the maker works on system browsers, however, when I try to use markers on mobile browsers, it keeps showing a blank screen without any error whatsoever

**Comment by vrinch** [comment]
> You can use the experimental Expo fork [expo/react-native-maps#2](https://github.com/expo/react-native-maps/pull/2) which has partial web support using Leaflet.

Hello evan, great work from you.
The leaflet map works on system browsers as I have tested it out with a couple of browsers. However, on mobile phone browsers, it dint show, only shows a white screen. After some debugging, I found out that the marker is making the map unavailable on mobile browser. Can you look at this please.
Also, Sometimes the map goes completely grey, and nothing would be seen (probably dint load properly)

**Comment by Josefpa** [comment]
Any Updates on React Native Expo Map for Web?

**Comment by NilsBaumgartner1994** [comment]
Any updates for the web support?
