### ISSUE TITLE
Link in Safari changes to "app-settings:"

### ISSUE THREAD

**Issue by matheusbaumgart** [expo/expo#6897]
When Safari is the default browser, the link `http://localhost:19006/` will briefly open and then return `app-settings:`, making Safari show a "Failed to open page".

<img width="598" alt="image" src="https://user-images.githubusercontent.com/4028897/59018473-1464c400-889a-11e9-9ee0-ac615edd2294.png">

The same link works fine on Chrome.

**Comment by EvanBacon** [comment]
stale closing
