### ISSUE TITLE
Mobx decorators not working with Typescript

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#6898]
```
Module parse failed: Unexpected character '@' (10:2)
You may need an appropriate loader to handle this file type.
```

Any ideas on how to get these to work? I tried adding the babel presets but that won't fix it, using typescript as well. 

Thanks!

**Comment by EvanBacon** [comment]
Please update to a `babel.config.js` (babel 7). We enable `@babel/plugin-proposal-decorators` by default in `babel-preset-expo`.

**Comment by sgup** [comment]
@EvanBacon Does expo still need to bundle the legacy decorators? This doesn't allow the use of modern decorators for mobx: https://mobx.js.org/enabling-decorators.html

`[require('@babel/plugin-proposal-decorators'), { legacy: true }],`

https://github.com/expo/expo/blob/1c16aa1d970422f1e8cff38530b08fe943afacc2/packages/babel-preset-expo/src/index.ts#L396C7-L396C72

**Comment by RyanMG** [comment]
Does anyone have an example of a working setup? My application still throws the `Decorating class property failed. Please ensure that transform-class-properties is enabled and runs after the decorators transform.` error as if this is not configured. I assume I am missing something which I need to add / enable in my babel config file.

**Comment by Yuvix25** [comment]
@RyanMG I'm experiencing the exact same issue.
I'd very much appreciate it if @sgup of @EvanBacon could help here by providing examples of a working babel.config.js.
This is my current configuration:
```js
module.exports = function (api) {
  api.cache(true);
  api.decorators(false);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties", { "loose": true }],
      ["@babel/plugin-transform-class-properties", { "loose": true }]
    ],
  };
};
```
I tried pretty much every combination of these, different orders, fiddling with the legacy/loose options, remove some of these plugins, everything, but I keep getting `Decorating class property failed. Please ensure that transform-class-properties is enabled and runs after the decorators transform.` no matter what I do.

**Comment by sgup** [comment]
@Yuvix25 I'm not using decorators anymore, but this is guess based on @EvanBacon 's PR ([changes here](https://github.com/expo/expo/pull/34647/files#diff-174a2c2dd0f687e7f1d11e3aa1a7e434a9629458785bd215b8b33a1304b2800c))

```ts
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo', 
        // 1. Add this option disable expo's internal decorator plugin config.
        { decorators: false }
    ], 
    plugins: [
      // 2. Add your plugins, and adjust as needed:
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties", { "loose": true }],
      ["@babel/plugin-transform-class-properties", { "loose": true }]
    ],
  };
};
```

**Comment by sgup** [comment]
Ah yes, good catch. Glad it works!
