### ISSUE TITLE
TaskManager doesnt work for me on android and dont know why .

### ISSUE THREAD

**Issue by roei133** [expo/expo#6899]
TaskManager doesn't work for me on android and I don't know why.
I use it with Expo and I did an example as you can see but it doesn't work for me and I don't understand the reason for that.
I just want that my app will start to run automatically in the background every 1 minute.
Please help me.
I call this task at the beginning of the app.js as well.

registerFetchTask();

and this is the code :

```
import * as BackgroundFetch from 'expo-background-fetch';
import * as TaskManager from 'expo-task-manager';

const FETCH_TASKNAME = 'test_task'
const INTERVAL = 60

function test() {
    console.log('function is running')
}

export async function registerFetchTask() {
    TaskManager.defineTask(FETCH_TASKNAME, test);

    const status = await BackgroundFetch.getStatusAsync();
    switch (status) {
        case BackgroundFetch.Status.Restricted:
        case BackgroundFetch.Status.Denied:
            console.log("Background execution is disabled");
            return;

        default: {
            console.debug("Background execution allowed");

            let tasks = await TaskManager.getRegisteredTasksAsync();
            if (tasks.find(f => f.taskName === FETCH_TASKNAME) == null) {
                console.log("Registering task");
                await BackgroundFetch.registerTaskAsync(FETCH_TASKNAME);

                tasks = await TaskManager.getRegisteredTasksAsync();
                console.debug("Registered tasks", tasks);
            } else {
                console.log(`Task ${FETCH_TASKNAME} already registered, skipping`);
            }

            console.log("Setting interval to", INTERVAL);
            await BackgroundFetch.setMinimumIntervalAsync(INTERVAL);
        }
    }
}
```

**Comment by cruzach** [comment]
the `defineTask` method must be called in the global scope of your JavaScript bundle, that's probably the issue

I suggest reading through the docs a bit more, and trying to copy exactly the example we have there - https://docs.expo.io/versions/latest/sdk/task-manager/#example

Closing since this isn't a bug with the Expo SDK

**Comment by josh-gree** [comment]
I am struggling very much with getting `TaskManager` to work - I seem to be able to register a task - get the following in `adb logcat`;

```
08-22 16:14:33.883  3574  3824 I TaskService: Registered task with name 'TESTING' for app with ID '@joshg/bg_tasks'.
```

However there is no entry in `adb shell dumpsys jobscheduler` and I *never* see the task running - does anyone have any guidance on how to go about debugging? Can I do a one time trigger of a Task for example?

Also in terms of the documentation referred to above - the example given very much muddies the waters given its using `startLocationUpdatesAsync` - is there a much more basic working example that anyone can share - and a way of running such that we can be sure it works without having to wait for arbitrary time for the system to schedule?
