### ISSUE TITLE
Scheme for AuthSession

### ISSUE THREAD

**Issue by oron11** [expo/expo#6902]
Hello,

I'm using Linkedin as part of my login process in the app.
I have noticed that there is a need to add scheme to app.json, however, I didn't find any example for it.
I'll be happy to get any help becuase I'm not sure how to do that.
If there is a code snapshot it will be amazing!

Thank you.

**Comment by cruzach** [comment]
it's a really simple process, so there's not much of an example to provide, just setting `"scheme": "myscheme"` in app.json

There's some documentation here - https://docs.expo.io/versions/latest/workflow/configuration/#scheme
