### ISSUE TITLE
Expo barometer not working in IOS?

### ISSUE THREAD

**Issue by ufoetzzj** [expo/expo#6903]
### Environment

IOS Version 13.3(17C54)

### Steps to Reproduce

Running the official barometer code by Snack from Expo Documentation
https://docs.expo.io/versions/latest/sdk/barometer/

But even the official code stop working in IOS platform.

### Expected Behavior

Air pressure should be changing along with altitude, and display the screen.

### Actual Behavior

Barometer not working on IOS device, air pressure doesn't change and stay static.

### Reproducible Demo

Tested on Android platform, barometer works perfectly but not on IOS. Simply just run the official code with snack from Expo documentation of Barometer.

![IMG_2278](https://user-images.githubusercontent.com/25337108/73391555-0fbba880-428d-11ea-85b7-adc1c9bbabc8.png)

**Comment by cruzach** [comment]
on the iOS side, Expo relies on [CMAltimeter](https://developer.apple.com/documentation/coremotion/cmaltimeter) for the barometer sensor. This measures the change in the current altitude, and I believe may only reflect changes to the closest _hectopascal_. I believe the module works, as it shows a different value for me

Did you test this with changes >= 1 hPa?

**Comment by ufoetzzj** [comment]
> on the iOS side, Expo relies on [CMAltimeter](https://developer.apple.com/documentation/coremotion/cmaltimeter) for the barometer sensor. This measures the change in the current altitude, and only reflects changes to the closest _hectopascal_. I believe the module works, as it shows a different value for me
> 
> Did you test this with changes >= 1 hPa?

For me the value never change. Freeze initially at 99000 Pa then never change. Supposedly the value should change rapidly and keeps changing since air pressure is changing all time. I tested on Android Device and it works completely fine. I tested on mutiple IOS devices and neither of them is working.

For example, please do try this official code on Snack:
https://snack.expo.io/?platform=android&name=Basic%20Barometer%20usage&sdkVersion=36.0.0&dependencies=expo-sensors&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv36.0.0%2Fbarometer.js

Thank you for helping! :)

**Comment by cruzach** [comment]
It only reflects changes to the nearest hectopascal, so I guess the question is- how much of a difference in altitude have you tested?

**Comment by ufoetzzj** [comment]
Initially I assume it should have the same functionality as the Android end does: which the hectopascal value keeps changing every millisecond in reflect of real-time air pressure. To answer your question, the difference in altitude I have test is from above my head to the ground. But it doesn't change. Is the IOS barometer require a significant of altitude change to reflect?

Thank you Charlie I definitely apperciate your help.

**Comment by cruzach** [comment]
Yes it does, I guess this depends on a few other variables but after a quick look it seems 1 hectopascal is around 60 feet worth of air

**Comment by ufoetzzj** [comment]
So it does work on your IOS device? because I tested on my Iphone, my friend's Iphone and my Ipad. Neither of them were working with the demo code from Expo document.

**Comment by cruzach** [comment]
To see a difference in 1 hectopascal, i believe your altitude would need to change by ~60 feet

**Comment by JaviEzpeleta** [comment]
Hi @ufoetzzj , 

iOS devices should provide you the relativeAltitude (in meters) with the data the comes from the event listener.

Please take a look at the example from that Expo Snack, debug the variable `data` and you'll see that it's an object of this type:

```
type BarometerMeasurement = {
  pressure: number;
  relativeAltitude?: number;  /* iOS Only */
};
```

It's the relative Altitude what you're looking for?
