### ISSUE TITLE
How to set Sqlite to be case insensitive when string comparing?

### ISSUE THREAD

**Issue by robertototti** [expo/expo#6905]
When i do

```
tx.executeSql(
  "SELECT * FROM products WHERE title LIKE 'eggplant';",
  [],
  (_, result) => {
    console.log(result.rows);
  },
  (_, err) => {
    console.log(err);
  }
);
```

I get empty array but i have column where value “Eggplant”.
how to disable case-sensitive?

**Comment by tcdavis** [comment]
Please ask usage questions on our forums (https://forums.expo.io/c/sdk/) so we can keep github focused on bug reports and keep improving the framework!

https://www.sqlite.org/pragma.html#pragma_case_sensitive_like
