### ISSUE TITLE
Toggle element inspector throws a lot of console errors on iPhone device

### ISSUE THREAD

**Issue by mgscreativa** [expo/expo#691]
Hi! I think I found a bug.

If I enable the element inspector in expo client installed in my iPhone 7+. **Expo client version 1.20.2.109829** iOS 10.3.1 I got lots of console errors and the app keeps loading forever.

To solve it I need to change project name and restart the packager, that way project settings in expo client got reset (debug remote js, toggle element inspector, etc). After this, I can't go back to the original app name because activates the element inspector again, like if there's some app cache somewhere...

More details here https://github.com/react-community/create-react-native-app/issues/419

**Comment by terribleben** [comment]
Hi, from reading the other thread, it looks like you have a version mismatch going on somewhere. Is the problem still happening?
