### ISSUE TITLE
Permissions.askAsync not working as expected

### ISSUE THREAD

**Issue by nikasvan** [expo/expo#6911]
### Environment

  Target: iOS
  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      npm: 6.12.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.8.0

### Steps to Reproduce

Having issue with Permissions.askAsync for notifications. 
const status = await Permissions.askAsync(Permissions.NOTIFICATIONS)

### Expected Behavior

When notification status is "undetermined" using Permissions.askAsync I expect to be presented with prompt dialog telling user to turn on notifications in order to continue.

### Actual Behavior

When I get status of the notifications with Permissions.getAsync, if it's not "granted" I use Permissions.askAsync but nothing is happening(not showing the dialog for notifications)

### Reproducible Demo
```
import * as Permissions from "expo-permissions"

componentDidMount(){
   this.checkPushNotificationState()
}

checkPushNotificationState = async () => {

  const { status: existingStatus } = await Permissions.getAsync(
    Permissions.NOTIFICATIONS
  )

  if (existingStatus !== "granted") {
    const status = await Permissions.askAsync(Permissions.NOTIFICATIONS)
    statusNotifications = status.status
  }
}
```

**Comment by nikasvan** [comment]
I had previously not granted permission and wanted to show dialog second time. Turns out iOS remembers that and won't allow the request again unless I go to app settings and explicitly enable it.

**Comment by nikasvan** [comment]
Closing issue!

**Comment by obiwankenoobi** [comment]
Hey! 

Did you solved it? Ok ios remember your first choice but is that it? nothing to do about it but toggle permission through the phone settings?
