### ISSUE TITLE
Which SHA-1 certificate fingerprint should I use for the Google OAauth client? (Google-Sign-In)

### ISSUE THREAD

**Issue by raRaRa** [expo/expo#6915]
Hey all.

I'm trying to set up Google sign in for my app. I'm wondering if I should use the SHA-1 certificate fingerprint specified in the App signing certificate (created by Google Play Store) or the upload SHA1 that was created by Expo?

Thanks.

**Comment by cruzach** [comment]
Hi! We keep github reserved for bug reports, so I'm going to close this issue. I suggest asking your question on our [forums](https://forums.expo.io/) instead 😄 

I'm also not exactly sure what you mean here, I don't think you need to set up the fingerprint for `expo-google-sign-in` to work https://docs.expo.io/versions/latest/sdk/google-sign-in/
