### ISSUE TITLE
TypeError: (0, _reactNavigationPropsMapper.withMappedNavigationProps) is not a function. 

### ISSUE THREAD

**Issue by py563** [expo/expo#6916]
I am new to react-native, i worked mostly on java and that side of development. After trying getting started in react website, i went on to clone this [repository](https://github.com/azhavrid/movie-swiper) and then created a new expo project following steps on website and copied only the js files and updated package.json file and also tried changing old versions in the repo to below (as i only got a blank screen) i got this error after doing expo start and scanning the QR code on the phone:

``` 
TypeError: (0, _reactNavigationPropsMapper.withMappedNavigationProps) is not a function. 
(In '(0, _reactNavigationPropsMapper.withMappedNavigationProps)()', '(0,
_reactNavigationPropsMapper.withMappedNavigationProps)' is undefined) 

<unknown> 
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:163294:76 
loadModuleImplementation 
    require.js:322:6 

<unknown> 
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:139668:61 
loadModuleImplementation 
    require.js:322:6 

<unknown> 
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123267:28 
loadModuleImplementation 
    require.js:322:6 

<global> 
    AppEntry.js:5 
loadModuleImplementation 
    require.js:322:6 
guardedLoadModule 
    require.js:201:45 

global code 
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:165108:4 
```

![Screenshot from 2020-01-30 17-57-19](https://user-images.githubusercontent.com/6139284/73449878-2e539980-438a-11ea-8c36-e4cc5361c87e.png)

I am wondering is it an issue with the app or expo

**Comment by cruzach** [comment]
Hi! Glad you're giving Expo and RN a try :) 

This doesn't look like a bug with Expo, but that maybe you haven't installed or imported a library correctly. It's also worth noting that the app you're trying to copy over to an Expo project makes use of it's own native code, so you'll have to use the bare workflow to use that - https://docs.expo.io/versions/v36.0.0/bare/exploring-bare-workflow/

You could probably still implement a very similar app in the managed workflow, but you'll need to dig into the code a little bit more and see what changes you'd have to make. Good luck!
