### ISSUE TITLE
exp build is not supported for detached projects

### ISSUE THREAD

**Issue by githubandrewd** [expo/expo#692]
Hi,

I have detached my project because i needed a native module not supported by Expo.

Here are the steps I went through:
1. I did exp detach. That created an Android folder for me.
2. I did exp start. This is the output:
`[exp] Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.

[exp] Starting React Native packager...

[exp] Scanning 781 folders for symlinks in /lalalalmyproject/node_modules (6ms)

[exp] Loading dependency graph.

[exp] Running packager on port 19001.

[exp] Sucessfully ran `adb reverse`. Localhost urls should work on the connected Android device.

[exp] Dependency graph loaded.

[exp] Expo is ready.

[exp] Your URL is

expbd864976438a4a7b82048ca813e03779://lalalalurl`
3. I opened a new tab in another terminal and typed in exp build:android
4. I got an error that exp build is not supported for detached projects.

How do I fix this problem?

**Comment by quinlanj** [comment]
Hi @githubandrewd, as the error message indicates, `exp build` does not support detached projects, see https://docs.expo.io/versions/latest/guides/detach.html#all-you-need-is-to-distribute-your-app-in-the-itunes-store-or-google-play-expo-can-build-binaries-for-you-in-that-case-if-you-detach-we-cant-automatically-build-for-you-any-more

**Comment by quinlanj** [comment]
You will need to build the project yourself

**Comment by githubandrewd** [comment]
I see. Thanks.
