### ISSUE TITLE
Expo-Sharing issue with react-native-view-shot on iOS

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#6920]
Hi guys, 
When i take snapshot using `react-native-view-shot` and them using the `expo-sharing` on iOS i only see "AirDrop", on android works as expected.

```js
import { captureRef } from 'react-native-view-shot';
import * as Sharing from 'expo-sharing';

captureRef(this._shareViewContainer, {
  // defaults
}).then(
  uri => {
    console.log('Image saved to', uri);
    Sharing.shareAsync(uri);
  },
  error => console.error('Oops, snapshot failed', error)
);
```

And here a simple snack:

https://snack.expo.io/@outatime/expo-sharing-screenshot

And the sharing dialog:

![image](https://user-images.githubusercontent.com/140472/73480032-dca21380-4377-11ea-8227-45ba622d4101.png)

If i use the following code:

https://docs.expo.io/versions/latest/tutorial/sharing/#using-expo-sharing-to-share-an-image

here the sharing dialog:

![image](https://user-images.githubusercontent.com/140472/73480180-2d197100-4378-11ea-98e0-1076045425dc.png)

probably something related with the temp file generated by `react-native-view-shot`? any advice will be welcome, thanks !!!

**Comment by cruzach** [comment]
Hi! You have to provide the full URI. I prefixed the uri in the snack with the document directory, and sharing works as intended iOS, although there's no image if you go to share it because `react-native-view-shot` doesn't save to the document directory 😅 )-https://snack.expo.io/@charliecruzan/expo-sharing-screenshot

If you get the full URI, then it will probably work. However- it looks like that library relies on custom native code, so you won't be able to fully use it in the managed workflow (including snack). You can use it in the bare workflow, but if you need a screenshot-taker in managed, you should use [takeSnapshotAsync](https://docs.expo.io/versions/latest/sdk/take-snapshot-async/).

**Comment by marceloxp** [comment]
Prepend a `file://` to your URI:
```
    Sharing.shareAsync("file://" + uri);
```

**Comment by outaTiME** [comment]
@

> Hi! You have to provide the full URI. I prefixed the uri in the snack with the document directory, and sharing works as intended iOS, although there's no image if you go to share it because `react-native-view-shot` doesn't save to the document directory 😅 )-https://snack.expo.io/@charliecruzan/expo-sharing-screenshot
> 
> If you get the full URI, then it will probably work. However- it looks like that library relies on custom native code, so you won't be able to fully use it in the managed workflow (including snack). You can use it in the bare workflow, but if you need a screenshot-taker in managed, you should use [takeSnapshotAsync](https://docs.expo.io/versions/latest/sdk/take-snapshot-async/).

Indeed, but `takeSnapshotAsync` is not pre-installed in expo SDK36 anymore (im using managed workflow), that's why I'm using `react-native-view-shot`

<img width="684" alt="image" src="https://user-images.githubusercontent.com/140472/73583740-a3020300-4472-11ea-9063-be7e81c13684.png">

I will try the @marceloxp solution, thanks !!!

**Comment by outaTiME** [comment]
> Prepend a `file://` to your URI:
> 
> ```
>     Sharing.shareAsync("file://" + uri);
> ```

Awesome work as expected on both devices 🙌 thanks !!!

**Comment by rezahok** [comment]
> Prepend a `file://` to your URI:
> 
> ```
>     Sharing.shareAsync("file://" + uri);
> ```

This worked for me as well. Thanks a lot.

**Comment by SamMakesThings** [comment]
Problem with the above - the share menu opens, but it doesn't show Messages or "save image" as options. Any idea how to enable those?

**Comment by sleekLancelot** [comment]
> Problem with the above - the share menu opens, but it doesn't show Messages or "save image" as options. Any idea how to enable those?

Likewise, prepending “file://“ to the image url doesn’t solve the issue for me. I still do not get save/save to photo in the sharing dialogue.
