### ISSUE TITLE
Expo-Sharing issue running on iOS v.11.4

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#6921]
Hi guys, 
When running on iOS 11.4 im getting the following issue with the same code from https://github.com/expo/expo/issues/6920

<img width="763" alt="image" src="https://user-images.githubusercontent.com/140472/73481135-ed538900-4379-11ea-9536-47e993807ad9.png">

Thanks !!!

**Comment by cruzach** [comment]
You probably need to provide the entire URI, looks like you're only providing part of it. Closing this in favor of https://github.com/expo/expo/issues/6920
