### ISSUE TITLE
SHA-1 for file is not computed

### ISSUE THREAD

**Issue by pgte** [expo/expo#6929]
### Environment

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.11.7
```

iOS

### Steps to Reproduce

By importing a file in a local directory like this:

```js
import HTML from './public/index.html'
```

### Expected Behavior

Should import the file.

### Actual Behavior

Displays error message:

```
SHA-1 for file /Users/pedroteixeira/projects/holdattack/holdattack-ui-reactnative/public/index.html (/Users/pedroteixeira/projects/holdattack/holdattack-ui-melonjs/public/index.html) is not computed
```

### Reproducible Demo

* create a local folder named "public" and place there a file named `index.html` with the contents:

```html
<h1>Hello World!</h1>
```

Then, in App.js, add the following line:

```js
import HTML from './public/index.html'
```

If I replace the import with a `require`, the error is still present:

```js
const HTML = require('./public/index.html')
```

**Comment by pgte** [comment]
BTW, I've tried upgrading everything and reinstalling node_modules, to no avail.

**Comment by cruzach** [comment]
Could you share a snack that reproduces this? I tried this [here](https://snack.expo.io/@charliecruzan/joyous-soda) and couldn't repro

**Comment by pgte** [comment]
@cruzach Ah, I see what you did there. You're exporting the HTML as a ES module. I'm going instead to try to embed this file as an asset instead. Thanks!
