### ISSUE TITLE
Warning: Possible Unhandled Promise Rejection. Error: Seeking interrupted.

### ISSUE THREAD

**Issue by tZilTM** [expo/expo#6937]
iPhone XS
iOS 13.3

I'm just using expo-av: const sound = new Audio.Sound()
then using: loadAsync, stopAsync, unloadAsync, setOnPlaybackStatusUpdate
on audio <b>streams</b> (not files) (mp3, m3u8)

I (think I) always use finally, and only sometimes then and catch with these async (not with setOnPlaybackStatusUpdate) functions...

I believe this warning/error occurs when stopping a stream and unloading.

The code used to work fine with a previous version of Expo.

**Comment by tSixTM** [comment]
iPhone XS
iOS 13.5.1

The problem still persists. I've recreated the project from scratch using the latest packages. However, I'm not using a try catch block and the async keyword. Instead, I'm using the .catch on the Promise from .then after loadAsync. This is the pattern I wish to follow. Which function throws the Promise Rejection Error: Seeking Interrupted? I assumed loadAsync, but possibly (probably) it's an expo av internal error...
