### ISSUE TITLE
after "exp detach" the Android project is complaining that it cannot find CreditCardEntry

### ISSUE THREAD

**Issue by githubandrewd** [expo/expo#694]
It seems that a dependency that is configured with the default android project after "exp detach" cannot find CreditCardEntry, for some reason.

I am trying to run the app from Android studio because of the issue #692 that prevents me from using exp build:android. :/

What should I do?

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.github.thefuntasty:CreditCardEntry:1.4.8.4.
     Searched in the following locations:
         file:/home/svcontractor/tools/android-studio/gradle/m2repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.pom
         file:/home/svcontractor/tools/android-studio/gradle/m2repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.jar
         file:/home/svcontractor/.m2/repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.pom
         file:/home/svcontractor/.m2/repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.jar
         https://jcenter.bintray.com/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.pom
         https://jcenter.bintray.com/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.jar
         file:/home/svcontractor/projects/biomassprototype/.expo-source/android/maven/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.pom
         file:/home/svcontractor/projects/biomassprototype/.expo-source/android/maven/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.jar
         file:/home/svcontractor/projects/biomassprototype/android/app/libs/CreditCardEntry-1.4.8.4.jar
         file:/home/svcontractor/projects/biomassprototype/android/app/libs/CreditCardEntry.jar
         https://maven.fabric.io/public/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.pom
         https://maven.fabric.io/public/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.jar
         file:/home/svcontractor/Android/Sdk/extras/android/m2repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.pom
         file:/home/svcontractor/Android/Sdk/extras/android/m2repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.jar
         file:/home/svcontractor/Android/Sdk/extras/google/m2repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.pom
         file:/home/svcontractor/Android/Sdk/extras/google/m2repository/com/github/thefuntasty/CreditCardEntry/1.4.8.4/CreditCardEntry-1.4.8.4.jar
     Required by:
         android:app:unspecified > host.exp.exponent:expoview:21.0.0

**Comment by flieks** [comment]
https://github.com/expo/expo/issues/689 :)

**Comment by quinlanj** [comment]
Hi @githubandrewd, can you try the fix @flieks had in https://github.com/expo/expo/issues/689. If that doesnt work, we can re open this issue.

**Comment by amaldare93** [comment]
I am having the same issue.
Its a fresh expo project, i just filled out my app.json and detached.

I tried @flieks solution and now im getting:

```
Error:(74, 1) A problem occurred evaluating project ':app'.
> Project with path ':react-native-onesignal' could not be found in project ':app'.
```

**Comment by githubandrewd** [comment]
I can confirm the fix suggestion worked!!
