### ISSUE TITLE
Error code 26: file is not a database

### ISSUE THREAD

**Issue by lamaalqasem** [expo/expo#6944]
Hello everyone,
My Expo SDK version is 36.0.0

### Steps to Reproduce

1- I've created a SQLite Database via DB browser for SQLite with its tables.
2- I've tried to connect to it, but for some reason it can't be seen, like this file doesn't exist, and when I run openDatabase it seems to create a new database, and doesn't see the old ones with the tables with it.
3-  Some people said that the database is created in the FileSystem. So I tried to run the below code to download my database into the project files 
```
const dir = FileSystem.documentDirectory;
        try{
          await FileSystem.makeDirectoryAsync(dir+'SQLite', {
            intermediates: true
          });
const localDatabase = await FileSystem.getInfoAsync(dir+'SQLite/my_db.sqlite3');
          if (!localDatabase.exists){
            FileSystem.downloadAsync(
              'https://drive.google.com/XXXX',
              dir+'SQLite/my_db.sqlite3'
            ).then (({uri,status}) => {
              console.log("database copy to " + uri + "Status is : "+ status);
            })
            .catch(error => {
              console.log("database error: "+ error);
            })
          }
          else{
            console.log("database exists");
            console.log("however, i will copy to update its content");
             FileSystem.downloadAsync(
              'https://drive.google.com/XXXX',
              dir+'SQLite/my_db.sqlite3'
            ).then (({uri,status}) => {
              console.log("database copy to " + uri + "Status is : "+ status);
            })
            .catch(error => {
              console.log("database error: "+ error);
            });
          }
        }
        catch (error){
          console.log("What is my Error? : " + error);
        }
```

* Note: I have used a link to drive because I have seen some people put a direct link to a video or something, So I thought this is possible. because The normal way of using a path with Asset.fromModule didn't work with me with error "Unable to resolve module" 

4- The rest of the code is just inserting into users table (already created before with DB browser for SQLite)

const db = SQLite.openDatabase('my_db.sqlite3');
  setTimeout(() => {
    console.log(db);
    db.transaction(function(txn) {
      txn.executeSql(
        "INSERT INTO users (name, email, password) VALUES ('Lama', 'lama@gmail,com', 'lam123');",  //The string may contain ? placeholders, with values to be substituted listed in the arguments parameter.
      null,
      () => {
        console.log("success");
      },
      (_, error) => {
        console.log("error: "+ error);
      }
    );//end txn
    });
  }); //end set timeout

### Expected Behavior

Inserting into users Table.

### Actual Behavior

error: Error: Error code 26: file is not a database

Not opening the database, therefore, doesn't add records.

### Reproducible Demo

https://snack.expo.io/@lamaalqasem/d3b47c

**Comment by cruzach** [comment]
Hey @lamaalqasem, can you try downloading the database as an asset first, as suggested here - https://forums.expo.io/t/how-to-connect-to-an-existing-database/6154/4?u=charliecruzan

[this forum post](https://forums.expo.io/t/solved-import-asset-db/11469/3) might also help you get this set up. I don't believe this is a bug with Expo, but will leave this issue open for now in case neither of those posts help

**Comment by lamaalqasem** [comment]
> Hey @lamaalqasem, can you try downloading the database as an asset first, as suggested here - https://forums.expo.io/t/how-to-connect-to-an-existing-database/6154/4?u=charliecruzan
> 
> [this forum post](https://forums.expo.io/t/solved-import-asset-db/11469/3) might also help you get this set up. I don't believe this is a bug with Expo, but will leave this issue open for now in case neither of those posts help

I have checked these two links before I post this question and they didn't seem to work for me.
However, I have switched to connect to MySQL database through Flask.

Thank you for your reply.
