### ISSUE TITLE
null is not an object (evaluating 'AppEventsLogger.logEvent')

### ISSUE THREAD

**Issue by nazaslater** [expo/expo#6946]
## 🐛 Bug Report
TypeError: null is not an object (evaluating 'AppEventsLogger.logEvent')

This error is located at:
    in DashboardComponent (at dashboard/index.js:82)
    in DashboardPage (created by ConnectFunction)
    in ConnectFunction (at navigationStore.js:456)
    in StatelessWrapped (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at StackViewLayout.js:400)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at Transitioner.js:141)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:429)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at DrawerView.js:87)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (created by DrawerLayout)
    in RCTView (created by DrawerLayout)
    in DrawerLayout (at DrawerView.js:84)
    in DrawerView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at StackViewLayout.js:400)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at Transitioner.js:141)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:429)
    in NavigationContainer (at Router.js:97)
    in App (at Router.js:122)
    in Router (at route/index.js:33)
    in Provider (at route/index.js:32)
    in _default (at App.js:33)
    in App (at withExpoRoot.js:26)
    in RootErrorBoundary (at withExpoRoot.js:25)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in DevAppContainer (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

logEvent
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:200612:22
BackButton
    NavBar.js:25:3
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
unstable_runWithPriority
    scheduler.development.js:643:23
Component.prototype.setState
    react.development.js:325:31
dispatch
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:165263:27
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:166109:35
_callee$
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:223888:83
tryCatch
    runtime.js:45:44
invoke
    runtime.js:271:30
tryCatch
    runtime.js:45:44
invoke
    runtime.js:135:28
Promise.resolve.then$argument_0
    runtime.js:145:19
tryCallOne
    core.js:37:14
setImmediate$argument_0
    core.js:123:25
_callTimer
    JSTimers.js:146:14
_callImmediatesPass
    JSTimers.js:194:17
callImmediates
    JSTimers.js:458:30
callImmediates
    [native code]:0
flushedQueue
    [native code]:0
invokeCallbackAndReturnFlushedQueue
    [native code]:0

## environment
Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 3.11.7

ExpoKit
iOS Simulator iPhone6s

### Steps to Reproduce

I ran the installation of react-native-fbsdk as described in the documentation https://github.com/facebook/react-native-fbsdk#usage, inserted the code as an example in the SDK documentation https://developers.facebook.com/ docs / react-native / app-events / # verify-your-logged-app-events, however none of the AppEventsLogger events work.

It imports correctly, I can print the AppEventsLogger and all its events on the console, but if you try to use the AppEventsLogger.logEvent ('battledAnOrc') as in the example or any other AppEventsLogger event it pops the null is not an object error.

## Importate, I use the app with expokit, I saw on the internet that most needed to eject the app to use lib react-native-fbsdk.

Can you help me? Can I use react-native-fbsdk whenever I need to eject the app?

**Comment by cruzach** [comment]
To use that module, you will need to eject, but we suggest using the bare workflow instead of Expokit. We will soon be deprecating support for expokit in favor of bare.

I also wanted to suggest taking a look at the [Expo Facebook module](https://docs.expo.io/versions/latest/sdk/facebook/), which you can use in the managed workflow 😄

**Comment by tsapeta** [comment]
I'm closing this as ExpoKit is no longer supported. Also, as Charlie suggested above, you can use our own module for this 🙂
