### ISSUE TITLE
Asset.fromModule `uri` includes duplicate `/assets/assets/`

### ISSUE THREAD

**Issue by kirbysayshi** [expo/expo#6948]
## 🐛 Bug Report

Hello! I am new to Expo, so please forgive me if this bug report turns out to be user error! 🤒 

### Environment

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - ~/nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - ~/nvm/versions/node/v12.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.19
      @types/react-native: ~0.60.23 => 0.60.31
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

### Steps to Reproduce

It appears that using `Asset.fromModule(require('./assets/icon.png'))` (or any other path) results in an invalid `uri` property that contains an implicit and duplicate `assets` in the path. No matter where I try to `require` an asset from (e.g. `assets`, `src`, etc), it always has double `assets` in the path.

```ts
import { Asset } from 'expo-asset';
const test = Asset.fromModule(require('./assets/icon.png'));

// This should log something like: `http://localhost:[port]/assets/icon.png?[long query]
// but instead is: `http://localhost:[port]/assets/assets/icon.png?[long query]
// Curling this results in a 404 / error!
console.log(test.uri);

// This workaround produces a working, expected URL.
// Curling this downloads the file.
const normalized = test.uri.replace(/(assets\/)+/g, 'assets/');
console.log(normalized);
```

### Expected Behavior

I expect the url to be (one `/assets/`):

```
http://127.0.0.1:19001/assets/icon.png?platform=ios&hash=f82b34f900882c5120a1bfbf6df22a27?platform=ios&dev=true&minify=false&hot=false
```

### Actual Behavior
 The url is (notice two `/assets/`):

```
http://127.0.0.1:19001/assets/assets/icon.png?platform=ios&hash=f82b34f900882c5120a1bfbf6df22a27?platform=ios&dev=true&minify=false&hot=false
```

### Reproducible Demo
Repo: https://github.com/kirbysayshi/expo-double-asset-uri-bug

I tried using Snack to repo the issue, but was getting an error about `Device: (0:0) nativeExtensions is not defined`!

**Comment by cruzach** [comment]
From the source, it seems like `/assets/assets`  is the `httpServerLocation` field returned by `getAssetByID` which is upstream in React Native. What makes you say this is an invalid uri? the following works:
```
<Image
  source={{
  uri: Asset.fromModule(require("./assets/icon.png")).uri
  }}
  style={{ width: 400, height: 400 }}
/>
```

**Comment by kirbysayshi** [comment]
Is `<Image />` somehow normalizing the URI?

It's not an _invalid_ URI, but it does result to a 404 when I attempted to pass the URI to a webview to load the asset.

**Comment by cruzach** [comment]
Not sure, we use the `Image` component from `react-native`, so you'd have to check the source code there to see what it's doing behind the scenes. (Same as with the `getAssetByID` method)

**Comment by kirbysayshi** [comment]
Ok. Perhaps it's not a bug in expo, maybe instead is in React native. I was trying to pass that URI to a webview. By default the webview would 404 unless I removed the duplicate `/assets` from the URI.

**Comment by Prathapkarumanchi** [comment]
what if it's for font load? in snack fonts are not working.
Can someone please share a working example of using custom fonts on Expo-snack

**Comment by iki789** [comment]
I have the same issue. I seem to be getting a duplicate `assets/` in uri returned from `Asset.fromModule()`

**Comment by sylvio-ruiz** [comment]
This is an old post but I am seeing people seeing double 'assets' directory in the path, like me.

Make senses for me if you are running a development server on the same network and your assets files already there. There is no reason to cache them, they are already cached on the development server on the same network.  Probably the double 'assets' directory is an indicator for expogo that assets is cached, and the development server does an internat redirect to the asset folder.

Unlike the op, copying and pasting the url on my browser, I get a 200 response and I can see the chunked data.

I believe the curl request made for him does not fit all requirements to receive a 200 answer from the development server like my browser. I am sure if he copies the headers from the browser and add them to the curl builder, certainly it will get a good answer (200).

So, doubling the 'assets' in the path does not affect the result, the server does an internal redirect and handles the request.
