### ISSUE TITLE
after "exp detach" the Android project is complaining , exploded-aaa//com.google.android.gms/play-services-ads/9.8.0/jars/classes.jar file crash.  

### ISSUE THREAD

**Issue by Sunfremont** [expo/expo#695]
"expo": "^21.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not expand ZIP '../nbs/android/app/build/intermediates/exploded-aar/com.google.android.gms/play-services-ads/9.8.0/jars/classes.jar'.

I check the class.jar file in aar . it seem not a good file . 
it can not unzip correctly .

**Comment by sjchmiela** [comment]
Support for SDK21 has been phased out and we've upgraded `play-services-ads` dependency since, so this issue shouldn't be present in supported SDK versions anymore. 🙂
