### ISSUE TITLE
Ejected Android app crashes onBarCodeScanned

### ISSUE THREAD

**Issue by sweebee** [expo/expo#6950]
### Environment

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.17.0 - /usr/local/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @bugsnag/expo: ^6.4.0 => 6.5.0 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7
```

### Steps to Reproduce

```
<Camera
    ratio={'16:9'}
    style={styles.scanner}
    onBarCodeScanned={this.onBarcodeScanned}
/>
```
When the camera is active, it crashes. It wont crash when i remove the ```onBarCodeScanned```

### Expected Behavior

Don't crash

### Actual Behavior

App crashes

### Stack trace

```
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:353)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
```
```
Caused by: java.lang.NullPointerException: 
  at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground (BarCodeScannerAsyncTask.java:36)
  at expo.modules.camera.tasks.BarCodeScannerAsyncTask.doInBackground (BarCodeScannerAsyncTask.java:6)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by cruzach** [comment]
Is your `onBarcodeScanned` method pretty much empty (i.e. definitely not causing the crash)? Does the exact same code cause a crash when running in a managed workflow project?

**Comment by sweebee** [comment]
I fixed it by removing the android and ios folder and I ejected the app again.

**Comment by SleeplessByte** [comment]
I've ran into this multiple times today. The only way to resolve it is to completely clear all _native_ parts.

- bare project
- add expo-camera (per instructions, also add correct maven url)
- test: it will work
- add `onBarCodeScanned={console.log}`

Now, it might work, but most likely it will start crashing. Exact same crash log. 

If it doesn't crash now, it seems that adding other dependencies will at some point "trigger" the crash and now it will keep on happening. There is definitely _something_ wrong with the native code.

Here the scanner is null:

https://github.com/expo/expo/blob/8d441c7e9b081cfdd6a45edc165251d7273225a0/packages/expo-camera/android/src/main/java/expo/modules/camera/tasks/BarCodeScannerAsyncTask.java#L36

Which means that it must never be initialised, or not provided here:

https://github.com/expo/expo/blob/284d4840c02ae895f64a4fef994902027d51e614/packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java#L255

It's existence is not checked here:

https://github.com/expo/expo/blob/284d4840c02ae895f64a4fef994902027d51e614/packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java#L129

-------

Reproducible example? Not quite --

- `git clone`: https://github.com/brentvatne/camera-example
- `yarn`
- `yarn android`

It might, or might not work out of the box. The first time I had it crash within seconds. The second time it took a while. The third project was instant again, but there I added a few native modules.

In the end I ended up with replacing his code with:

```typescript

function ScannerScreen() {
  const [hasPermission, setHasPermission] = useState(null);
  const [scanned, setScanned] = useState(true);

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestPermissionsAsync();
      setHasPermission(status === "granted");
    })();
  }, []);

  const handleBarCodeScanned = ({ type, data }) => {
    setScanned(true);
    console.log({ type, data });
    alert(`Bar code with type ${type} and data ${data} has been scanned!`);
  };

  if (hasPermission === null) {
    return <Text>Requesting for camera permission</Text>;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }

  const width = Dimensions.get("window").width;
  const height = (width / 3) * 4;

  return (
    <View
      style={{
        flex: 1,
        flexDirection: "column",
        justifyContent: "flex-end"
      }}
    >
      <Camera
        style={{ width, height }}
        onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
      />

      {scanned && (
        <Button onPress={() => setScanned(false)} title="Tap to Scan Again"/>
      )}
    </View>
  );
}
```

Which then shows up correctly, and when I press the button it blows up (as it starts to scan).

**Comment by SleeplessByte** [comment]
Some other information:

- I'm on Windows 10
- Testing on an Android device (OS 10)

key | value
-- | --
Architectures | [arm64-v8a, armeabi-v7a, armeabi]
Battery Level | 65%
Boot Time | 2020-03-27T16:25:45Z
Brand | OnePlus
Charging | True
Connection Type | wifi
Family | HD1903
Id | 4e8834cfd00745fb
Language | en_GB
Manufacturer | OnePlus
Name | OnePlus 7T
Online | True
Orientation | portrait
Screen density | 2.625
Screen DPI | 420
Screen height pixels | 2290
Screen resolution | 2290x1080
Screen width pixels | 1080

![image](https://user-images.githubusercontent.com/1964376/77812899-d8a71f00-70a4-11ea-974e-408fba10632b.png)

If there is anything else I can provide, ping ahead! I'll do whatever I can.

**Comment by nnatter** [comment]
Hey,
based on #8847 I figured that this happens when the `expo-barcode-scanner` is not installed. As a workaround, I managed to prevent the crashes by installing `expo-barcode-scanner` with `expo install expo-barcode-scanner`.

**Comment by SleeplessByte** [comment]
This was happening for me even with `expo-barcode-scanner` installed. I haven't looked at this since.

**Comment by sweebee** [comment]
I havent got this issue anymore so closing it.

**Comment by SleeplessByte** [comment]
You closed it last time too, and the issue still existed. Maybe more people can confirm that it's fixed first?

**Comment by krisbaum74** [comment]
i have this exact same issue with expo-camera crashing when i assign a callback to onBarCodeScanning

**Comment by lmichailian** [comment]
Same for me

**Comment by xXDeonoXx** [comment]
same here, app crashs

`      <CameraScanner
        onBarCodeScanned={(result) => {
          if (!scanned) return;
          handleBarCodeScanned(result);
        }}
        ratio={'1:1'}
      >
`

**Comment by MatheusCarvalho95** [comment]
same here

**Comment by otaviomad** [comment]
same here.

**Comment by misaeldossantos** [comment]
I installed expo-barcode-scanner and rebuild the app. For me it worked

**Comment by rdsedmundo** [comment]
I'm also seeing this using expo-camera@11.2.2 and expo-barcode-scanner@10.2.2. This issue should be reopened as it's not resolved.

**Comment by rdsedmundo** [comment]
@cruzach @sweebee can you reopen this? Or should I create a new issue?

**Comment by cruzach** [comment]
To keep things clean, let's open a new issue and please include a minimal reproducible demo. If you're seeing this behavior in a bare app, I suggest you run your app through the Android Studio debugger, since that way when you open a new issue you can point to the exact code that seems to be causing an issue. This means it will be far easier for someone to contribute a PR to fix the issue

**Comment by achou11** [comment]
Pretty sure I was running into this too and upgrading to the latest versions of `expo-camera` (`11.1.X`) and `expo-barcode-scanner` (`10.2.X`) seemed to fix it for me. _note that you may need to upgrade other deps like `react-native-unimodules` to fix build issues_

**Comment by rywager** [comment]
I am having this issue as well. I cannot even get Sentry to catch it but i see it in my google play console.  

java.lang.RuntimeException: 
  at android.hardware.Camera.native_getParameters (Native Method)
  at android.hardware.Camera.getParameters (Camera.java:2249)
  at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend (BarCodeScannerViewFinder.kt:195)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)

**Comment by NikhilVashistha** [comment]
> I am having this issue as well. I cannot even get Sentry to catch it but i see it in my google play console.
> 
> java.lang.RuntimeException: at android.hardware.Camera.native_getParameters (Native Method) at android.hardware.Camera.getParameters (Camera.java:2249) at expo.modules.barcodescanner.BarCodeScannerViewFinder$scanForBarcodes$1.invokeSuspend (BarCodeScannerViewFinder.kt:195) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)

I am also facing the same issue. Did you get any solution for this.
