### ISSUE TITLE
Expo with Jest using Expo vector icons

### ISSUE THREAD

**Issue by WesleyHunt** [expo/expo#6952]
### Environment

 Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
      npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.9.1

Just trying to run tests

### Steps to Reproduce

Follow getting started docs, import icon, try to run basic test:
expo init DeleteMe
npm i jest-expo --save-dev
npm i react-native-testing-library --save-dev
npm i react-test-renderer --save-dev

import import {Feather} from '@expo/vector-icons'; into the basic App.js , use import in the file
<Feather name="minus" style={styles.iconStyle}/>

build basic snapshot test from Jest getting start docs,
npm run test

### Expected Behavior

Test does not fail

### Actual Behavior

/React-RN-MiniApps/ReactNative/DeleteMe/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/AntDesign.ttf:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){
                                                                                             

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@expo/vector-icons/src/AntDesign.ts:2:1)

### Reproducible Demo

https://github.com/WesleyHunt/ExpoJestVectorIconError

Removing vector icon import and use of import resolves the problem.

**Comment by leosuncin** [comment]
I have a related error with `expo-font`

<pre>
 FAIL  __tests__/App.spec.tsx
  ● Test suite failed to run

    /home/jsuncin/Vaults/Personal/projects/unga/node_modules/expo-font/build/Font.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { getAssetForSource, loadSingleFontAsync, fontFamilyNeedsScoping, getNativeFontName, } from './FontLoader';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { useState } from 'react';
      2 | import { StyleSheet, View } from 'react-native';
    > 3 | import * as Font from 'expo-font';
        | ^
      4 | import { AppLoading } from 'expo';
      5 | import Header from './components/header';
      6 | import StartGameScreen from './screens/start-game';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (App.tsx:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.346s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
</pre>

### Reproducible Demo

https://github.com/leosuncin/unga/tree/udemy/guess-a-number

### Environment

- `expo`: 36.0.2
- `native-testing-library` version: 5.0.3
- `jest-preset`: @testing-library/react-native
- `react-native` version: 0.61.4
- `node` version: 13.7.0

**Comment by EvanBacon** [comment]
@WesleyHunt You are using the wrong Jest preset. `jest-expo` extends the default RN preset and adds support for packages like `@expo/vector-icons` (and web, and universal testing: [Learn more](https://blog.expo.io/testing-universal-react-native-apps-with-jest-and-expo-113b4bf9cc44)). To fix, simply change the following in your `package.json`:

```diff
"jest": {
+    "preset": "jest-expo"
-     "preset": "react-native",
-     "transformIgnorePatterns": [
-       "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base)"
-    ],
}
```

@leosuncin your issue is unrelated to the original issue. I imagine your issue has something to do with Babel or TypeScript https://github.com/expo/expo/issues/4293
