### ISSUE TITLE
RCTAssetsLibraryRequestHandlers have equal priority (0) @ SDK 36

### ISSUE THREAD

**Issue by toinyumi** [expo/expo#6953]
### Environment

I'm using `Expokit` and run the app on iOS using Xcode.

```
Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.6 - ~/.npm-global/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.22 => 16.9.17 
      @types/react-native: ^0.57.65 => 0.57.65 
      @types/react-navigation: ^3.0.7 => 3.4.0 
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ~4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7
```

### Steps to Reproduce

Just simply load images on iOS with URI that starts with `assets-library` with a few state changes.

### Expected Behavior

Image should be loaded successfully whenever the state changes.

### Actual Behavior

Red box comes out in DEV mode and blank page in PROD mode

### Reproducible Demo

I'm sorry that the project is private and cannot be shared. 
Here is part of the code. I'm rendering this `View` in a `FlatList`.
Noted that `item.cover` is URL like `assets-library://asset/asset.JPG?id=_______________&ext=JPG`
```
<View style={styles.image}>
          {
            item.cover != undefined &&
            <Image
              style={styles.image}
              source={{ uri: `${item.cover}` }}
            />
          }
</View>
```

**Comment by cruzach** [comment]
What's the error message that you get? You don't have to share the private project, but a minimal demonstration would really help in troubleshooting this issue

**Comment by serjbord** [comment]
After updating to expo 36, and trying to load image from assets, i have the same error
the url look like this : assets-library://asset/asset.JPG?id=66074A56-D365-4853-87EB-6C021D57D0E1&ext=JPG
https://prnt.sc/qy03gh

loading func: 

getLatestGalleryPhoto = async () => {
    const { hasRollPermission } = this.state
    const params = {
      first: 1,
    }

    if (Platform.OS === 'android') delete params.groupTypes

    if (hasRollPermission) {
      await MediaLibrary.getAssetsAsync({ ...params })
        .then(r => {
          const image = head(r.assets)

          this.setState({ lastGalleryPhoto: image })
        })
        .catch(err => {
          console.log(err)
        })
    }
  }

Yes, i am ejected too.

**Comment by toinyumi** [comment]
@serjbord thanks for the error message screen
