### ISSUE TITLE
Expo & Stripe:  Fail to import app to Google Play Console

### ISSUE THREAD

**Issue by Nahani** [expo/expo#6954]
## 🐛 Bug Report

I re open this issue because it has not been resolved : 
https://github.com/expo/expo/issues/5688

The issue is still present with `expokit@36.1.0-rc.0`

**From September 2019, the SCA  is a requirement of the EU Revised Directive on payment service providers. For all app that use payment with Stripe need to update the Stripe library to implement the SCA; But unfortunately is not compatible with Expo SDK due to this issue.**

### Environment

 Expo CLI 3.0.10 environment info:
   System:
     OS: Windows 10
   Binaries:
     Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
   IDEs:
     Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

App -> Android Expokit

### Steps to Reproduce
1/ expo init project
1/ eject to expokit (sdk 36)
2/ Add " implementation 'com.stripe:stripe-android:10.2.1' " in the app build.gradle
3/ Generate a signed APK
4/ Try to upload the APK to Google Play Console

### Expected Behavior
The app should be uploaded to the Google Play console.

### Actual Behavior
> Failed to import.
> You uploaded an APK or Android App Bundle with invalid or missing signing information for some of its files.

### Reproductible demo

Just make the steps above

### Other

This issue with this dependency appear only with an expokit project. (Tested with Expo 34 & 35 & 36)

If I use a vanilla RN project there are no issue. So I think there are something wrong with the generated expokit project configuration.

After discussing with the Google Support they said me that the issue come from these files in the APK:

```
META-INF/BC1024KE.DSA
META-INF/BC1024KE.SF
META-INF/BC2048KE.DSA
META-INF/BC2048KE.SF
META-INF/CERT.RSA
META-INF/CERT.SF
META-INF/MANIFEST.MF
```
I removed all these files and I resigned my apk and now I am able to upload the app to the Google Play Console. But these files are needed to use the Stripe library so we can't di that.

Thank you for your help !

**Comment by cruzach** [comment]
In your steps to reproduce, you don't include installing `expo-payments-stripe`, are you not using that package? Not sure which version of  `com.stripe:stripe-android` is SCA-compliant, but `expo-payments-stripe` [uses v8.1](https://github.com/expo/expo/blob/sdk-36/packages/expo-payments-stripe/android/build.gradle#L74)

**Comment by Nahani** [comment]
No I'm not using that package because Stripe is SCA-compliant from the version `v9.1.1`  with the integration of `com.stripe:stripe-3ds2-android:0.0.5`

**Comment by tsapeta** [comment]
We no longer support ExpoKit and I recommend migrating to bare workflow where this shouldn't be an issue or at least it will be easier to solve. Feel free to reopen this or create a new issue if you're still hitting this in bare workflow.
