### ISSUE TITLE
EXPO WEB: Support for the experimental syntax 'decorators-legacy' isn't currently enabled 

### ISSUE THREAD

**Issue by davidbiller** [expo/expo#6955]
JSCONFIG.json
{ "compilerOptions": { "experimentalDecorators": true } }

babelrc:
{
  "presets": ["babel-preset-expo"]
}

So i get this error: 
Support for the experimental syntax 'decorators-legacy' isn't currently enabled

**Comment by EvanBacon** [comment]
Answered here https://github.com/expo/expo/issues/6898#issuecomment-608299277
