### ISSUE TITLE
On Android, expo-image-picker needs 2 touch events to get the image 

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#6957]
## 🐛 Bug Report

This is a followup of https://github.com/expo/expo/issues/5934 as requested by @lukmccall 

### Environment
```
Expo CLI 3.11.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @bugsnag/expo: 6.4.1 => 6.4.1 
      expo: ^35.0.1 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: 4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7
```

### Steps to Reproduce
On Android, with result = await ImagePicker.launchImageLibraryAsync, click on one image in the list.

### Expected Behavior
Just one click is needed to get the image from library and have result.

### Actual Behavior

2 clicks are needed

### Reproducible Demo
 https://snack.expo.io/@shares/expo-image-picker-issue5934

If you look closer to the snack (updated with SDK35), you will notice that there is a blue "Updating..." banner at the top after you select the image and when it displays the alert, that means the app is reloaded, crashes or is put in foreground/background.

**Comment by cruzach** [comment]
@lc3t35 testing your snack on pixel Android 9, I only need to click one 🤔

**Comment by lukmccall** [comment]
I've also tested it on Android 8 and 9, it worked. Could you provide me with more information like which version of android you are using, your device model? Are you able to reproduce this on the simulator? 

It'll be nice if you check it on SDK 36.

**Comment by lc3t35** [comment]
Huawei P Smart and Galaxy A50

**Comment by lukmccall** [comment]
@lc3t35, in SDK 37, `image picker` will get some fixes. Maybe your problem also will be resolved by them.

**Comment by lc3t35** [comment]
I've built a reproducible demo on snack with Appstate change, can you reproduce the issue ?

**Comment by lc3t35** [comment]
It seems to be fixed in SDK37.

**Comment by cruzach** [comment]
confirmed in the snack above ^
