### ISSUE TITLE
Steps to build the Expo client from source

### ISSUE THREAD

**Issue by thisisjaiswal** [expo/expo#696]
Regarding the steps to build the Expo client from source - 
Get the iOS and Android clients building on your machine using the Set Up section below - 
which says to clone xdl.
so question is we do not need to clone this repo ?

**Comment by terribleben** [comment]
Hi, I'm not sure I understand your question. The Set Up instructions are referring to the `expo/expo` repo, and you additionally need to clone xdl as part of those instructions. Can you be more specific about which repo you're asking about?
