### ISSUE TITLE
expo-print: printAsync produces inconsistent behavior on latest iPadOS

### ISSUE THREAD

**Issue by brownbl1** [expo/expo#6964]
### Environment

```
Expo CLI 3.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
```

Targeting iPadOS 13.3 (17C54) and later with a brother label printer (QL-810W).

### Steps to Reproduce
https://snack.expo.io/@crosswaypa/7108f6

Running the above snack application on an iPad with the specified version above, pressing the PRINT button results in inconsistent behavior in a bundled/published app, as well as during development.

### Expected Behavior

I expected that pressing the PRINT button with a valid Airprint printer url specified will result in a print job being printed successfully every time.

### Actual Behavior

Instead, the first print always works, but often (not always) the `printAsync` function never returns. I determined this by using print statements, and the second console log statement often never gets printed. Often, subsequent button presses print the initial log statement, but nothing is ever printed to the printer.
![image](https://user-images.githubusercontent.com/2136925/73705809-e3f15600-46c4-11ea-81e4-8ae96ad1490a.png)

Running the exact same program on an older version of iOS, it works every time. I have an iPad Mini that works with this same program, and a larger iPad with the latest iPadOS where I'm seeing the inconsistent behavior. A variation of this program was running correctly for months without issue on the older version of iOS. 

Eventually, I get this error, and then repeatedly every time I press the PRINT button.
![image](https://user-images.githubusercontent.com/2136925/73705923-1ef38980-46c5-11ea-961b-d822c022057c.png)

I was trying to determine if calling `selectPrinterAsync` had any effect on this behavior, but I haven't been able to connect it to that yet. The button for calling that is added just for the purpose of logging a valid printer url. Although the issue does seem to happen less frequently when I took out the import for `selectPrinterAsync`.

I'm going to continue to debug this, but wanted to post this here as there definitely seems to be an issue with the change in iOS versions.

**Comment by brownbl1** [comment]
Also, just wanted to add that I really appreciate the work done on this module. I was one of the original users clamoring for this capability and it's worked perfectly up until when we upgraded our iPads the other week!

**Comment by brownbl1** [comment]
Okay, so after a little more digging, it looks like there is, in fact, an interaction between `selectPrinterAsync` and and `printAsync`. @tsapeta you documented it here two years ago:
![image](https://user-images.githubusercontent.com/2136925/73708404-4568f300-46cc-11ea-8a16-67743ddca295.png)

This is all very helpful to understand, yet our app has always used the `selectPrinterAsync` method, and that has always worked. I wonder if with the new upgrade to iPadOS, the `printers` property is not staying populated for some reason?

Although it does seem like my code always gets to line 127:
```
[printInteractionController printToPrinter:printer completionHandler:completionHandler];
```

since I never see an animated print dialog appear. Then, after a few prints, I always get to line 115:
```
reject(@"E_CANNOT_PRINT", @"Printing job encountered an error.", error);
```
but the `error` stack trace/variable doesn't seem that informative unfortunately.

I do not have access to a Mac to debug this code more closely, but I will try to get my hands on one soon. In the meantime, I'd appreciate any insight you may have with the latest iPadOS build.

**Comment by brownbl1** [comment]
Okay, I've finally been able to pinpoint through trial and error exactly when printing fails and when it succeeds. For my setup, printing only works consistently when line 108 is hit in `EXPrint.m`.
![image](https://user-images.githubusercontent.com/2136925/73710592-79471700-46d2-11ea-88dd-dd48f492763d.png)

I confirmed this by hardcoding a printer url and never opening the select printer dialog. Printing hits this fallback method and works every time. But when I select a printer from the dialog, then it finds the `UIPrinter` object in the cache and uses that first method, which breaks after 2 or 3 prints for me.

When I did our initial testing to determine whether it was safe to upgrade the iPads, I tested on the Print Simulator app and not a real Airprint printer. The Print Simulator app is great for testing, but it gives you printer urls using an `ipps://` format, which for some reason doesn't really work. I was getting around this by doing a `url.replace('ipps', 'ipp')`, which essentially forces the fallback method since the url is the `UIPrinter` dictionary key and it will never exactly match. 

So that's partly what was so confusing about this whole issue. There's still a bug with the cached printing method, but we have a workaround: store the printer url after calling `selectPrinterAsync`, restart the app and use the url from our app cache instead of ever opening the dialog. ¯\\_(ツ)_/¯

**Comment by cruzach** [comment]
Thanks for digging @brownbl1 ! Really appreciate the thorough investigation (& workaround!)

Just to clarify- you're still not sure _what_ the problem is with the cached printer, just that there most likely is one?

**Comment by brownbl1** [comment]
No problem! It was necessary to solve this for our use case anyway.. just glad their is a workaround for now. At this point all I know is if you use the exact version of iPadOS that I'm using, you see this issue. I've only confirmed it with the label printer that I have, but it seems like an issue with reusing `UIPrinter` instances on some versions of iOS.

In other words, I still cannot reproduce this issue on older iPads that have not been updated, but the steps to reproduce are:
1. call `selectPrinterAsync`
2. select a printer (this caches the printer object in memory)
3. print to that printer using the `printAsync({ url, html })` method
4. print until you see the red stack trace that I'm seeing above (~2-3 times for me)

**Comment by cruzach** [comment]
Hm, good to know

I can't promise that someone will get around to fixing this quickly, as we're a pretty small team, so if you find the time to dig even further, please update the thread as you've been doing so far (or open up a PR)!

**Comment by brownbl1** [comment]
Totally understand.. I'll let you know if I can find the time! Would it at least be possible if one of you could reproduce this with the hardware you've tested this module with? I only have one airprint printer, and I'd like to rule out the case that it's some weird interaction with just this printer model or something like that. Would be good to know if it's at least reproducible. And as I said, I can't really reproduce it using the Print Simulator due to the `ipps/ipp` mismatch.

**Comment by aaronbesson** [comment]
I have a similar error using an android thermal printer. the first print is fine, the second print if longer sometimes may not print all pages, then the third print will print the extra data from the previous print.
