### ISSUE TITLE
[Expokit Android] [task-manager] App crash after Activity killed

### ISSUE THREAD

**Issue by ken0x0a** [expo/expo#6965]
## 🐛 Bug Report

I'm using expokit, and there is a bug 
- App crash after Activity killed
- App crash on launch endlessly after upgrading app while foreground service is running

~~The following commit https://github.com/expo/expo/commit/99edf99243d746d3a60ba6a30bd36967e49854d8
solve this bug.
Could you publish expokit module including this commit?~~

### Steps to Reproduce

```sh
expo init
expo eject
```

implement background location task.
start that task with foreground service.
kill activity at "Recents Screen"
start app from launcher => crash

### Expected Behavior

App doesn't crash

### Actual Behavior

App crash

**Comment by tsapeta** [comment]
ExpoKit is no longer supported so I'm closing this. I recommend migrating to bare workflow instead of using ExpoKit. Feel free to create a new issue if it still persists in bare workflow, but we've fixed several other issues in background location in the past so I believe it works fine now.
