### ISSUE TITLE
fobjc-arc flag is not Found - IOS - MobSF Vulnerability

### ISSUE THREAD

**Issue by Gardens18** [expo/expo#6966]
MobSF tool finds the vulnerability with expo 33 as below, 

fobjc-arc flag is not Found

App is not compiled with Automatic Reference Counting (ARC) flag. ARC is a compiler feature that provides automatic memory management of Objective-C objects and protects from memory corruption vulnerabilities.

Any solution for this ?

**Comment by cruzach** [comment]
I believe this **is** enabled, can you explain how you determined your app was not compiled with ARC?

**Comment by Gardens18** [comment]
We found this vulnerability using this tool https://github.com/MobSF/Mobile-Security-Framework-MobSF by verifying the generated IPA from xcode, our sdk version is 33 and it has been ejected with expokit and then using xcode, the ipa file has been generated.

**Comment by cruzach** [comment]
Since you're using Expokit, you can enable ARC manually 👍

**Comment by Gardens18** [comment]
Kindly address this vulnerability so that it could resolved by updating the app.js instead of editing in xcode.

**Comment by Gardens18** [comment]
> Since you're using Expokit, you can enable ARC manually 👍

Please explain how to  enable ARC manually

**Comment by cruzach** [comment]
https://stackoverflow.com/questions/9018366/how-to-enable-disable-arc-in-an-xcode-project/9058891
