### ISSUE TITLE
is there way to console.log every few minutes with task manager ? 

### ISSUE THREAD

**Issue by roei133** [expo/expo#6968]
if i want to make a console.log every 5 minute in the background when the app is kill or after reboot and i do the same example as expo said 
so how i can do that ? 
```
import React from 'react';
import { Text, TouchableOpacity } from 'react-native';
import * as TaskManager from 'expo-task-manager';
import * as Location from 'expo-location';

const LOCATION_TASK_NAME = 'background-location-task';

export default class Component extends React.Component {
  onPress = async () => {
    const { status } = await Location.requestPermissionsAsync();
    if (status === 'granted') {
      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.Balanced,
      });
    }
  };

  render() {
    return (

      <TouchableOpacity style={{textAlign: 'center',alignItems: 'center',justifyContent: 'center',paddingTop:200}} onPress={this.onPress}>
        <Text  >Enable background location</Text>
      </TouchableOpacity>

    );
  }
}

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  if (error) {
    // Error occurred - check `error.message` for more details.
    console.log("error:", error);
    return;
  }
  if (data) {
    const { locations } = data;
    // do something with the locations captured in the background
    setInterval(function(){console.log(locations)}, 60)
  }
});
```

**Comment by cruzach** [comment]
Hi! I'm going to close this as we keep Github reserved for bug reports. In the future, it's better to post questions like this on our [forums](https://forums.expo.io/)

Why do you want to console.log something every 60 seconds? I'm not sure you can rely on the background task to be run like that. Generally any kind of background activity is expected to drop in the background to preserve battery life

**Comment by roei133** [comment]
It can be also 20 minute..it doesnt matter..but I just want that this task will keep working when the app is killed and also after reboot.
It doesn't work if I close the app..why?

**Comment by cruzach** [comment]
BackgroundFetch will not work if the app is terminated, only if it's in the background (See https://github.com/expo/expo/issues/3582)

As for location updates in the background, that oftentimes requires a **significant** change in location to fire

**Comment by roei133** [comment]
1. Can yo give some example for that?
2. If you know a way how to do background  task  that work when the app is killed give me also example how to do it.

**Comment by mehmetsalihakcan** [comment]
Hi, @roei133 ,i have same problem do you find any solution?

**Comment by mdecomba** [comment]
Hi, did you find a solution for this issue. 
In my case the task keep working when app is killed but not after device reboot.
