### ISSUE TITLE
Invoking FileSystem.getInfoAsync throws exception on both iOS and Android

### ISSUE THREAD

**Issue by EnriqueDev** [expo/expo#697]
## Problem Description
When trying to get info of a directory the app throws an exception in both iOS and android.

## Code Used
```
import { FileSystem } from 'expo';
const ATTACHMENTS_DIRECTORY = FileSystem.cacheDirectory + 'attachments/';

const copyFileToAttachmentsDirectory = async (source, filename) => {
  const directoryData = await FileSystem.getInfoAsync(ATTACHMENTS_DIRECTORY);
  if(!directoryData.exists) await FileSystem.makeDirectoryAsync(ATTACHMENTS_DIRECTORY);

  await FileSystem.copyAsync({
    from: source,
    to: ATTACHMENTS_DIRECTORY
  });

  return ATTACHMENTS_DIRECTORY + filename;
};
```

## iOS Exception
 ![simulator screen shot 28 sep 2017 12 01 12](https://user-images.githubusercontent.com/25365731/30963269-c14fe2b2-a444-11e7-803c-141a60ee02be.png)

## Android Exception
![screenshot_20170928-121530](https://user-images.githubusercontent.com/25365731/30963901-325d9c04-a447-11e7-8bda-65a234657454.png)

**Comment by terribleben** [comment]
Hi, it looks like you are invoking those methods with the wrong number of arguments. The app is crashing when it tries to analyze an options dictionary that doesn't exist.

**Comment by EnriqueDev** [comment]
So could you put an example of the correct way of implementing it?
Because I'm following the docu step by step.
