### ISSUE TITLE
The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable after eject get this error

### ISSUE THREAD

**Issue by RonakPatel0** [expo/expo#6973]
### Steps to Reproduce
after eject project from expo I get this **The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable .** it compulsory to use Expo SDK so why give bare option while eject. 

### Expected Behavior
run app like Expo SDK after eject.

### Actual Behavior
it trow error **The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable 
![Simulator Screen Shot - iPhone XR - 2020-02-04 at 18 05 04](https://user-images.githubusercontent.com/57698251/73745377-e1503880-4778-11ea-9d6d-c6d64edde4b0.png)
**

**Comment by cruzach** [comment]
You're probably using one of the managed workflow-only modules, listed here- https://docs.expo.io/versions/v36.0.0/bare/unimodules-full-list/#only-available-in-managed-workflow-currently

You could search your project for anywhere you are importing `from "expo"`

**Comment by thibaultdewit** [comment]
@cruzach does that mean we need to remove every single one of these import statements for the app to run?

**Comment by cruzach** [comment]
You can't use those modules that are listed as managed workflow only, yet, so yeah you'll need to remove them from your bare project

**Comment by hanselsen** [comment]
Is there a way to list all these modules? I think I have all of them but I still have the error.

**Comment by hanselsen** [comment]
I removed all additional expo libraries except for the ones that are shipped using `expo init` with bare workflow. Ran `expo start -c`, `gradlew clean`, `expo publish`, `gradlew installRelease`. All successfully, but it still crashes with this error `The Expo SDK requires Expo to run.`.

```package.json
...
  "dependencies": {
    "expo": "~37.0.3",
    "expo-splash-screen": "^0.2.3",
    "expo-updates": "~0.1.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-screens": "~2.2.0",
    "react-native-unimodules": "~0.9.0",
    "react-native-web": "~0.11.7"
  },
...
```
How is this possible?
