### ISSUE TITLE
Expo-Facebook login asked every time login and password into Facebook and don't use installed Facebook app

### ISSUE THREAD

**Issue by AndreUskovv** [expo/expo#6975]
Hello. I have app built on the EXPO library 35 version. Sign up/login on IOS with FB required to provide the login and password of FB, even if you logged in on your Facebook app. For Android, it automatically logs in with cred of Facebook account.
For login /sing up in our app with FB account, I used this documentation https://developers.facebook.com/docs/graph-api/

Can you tell me please, is it some way to solve this issue?
Thank you.

**Comment by cruzach** [comment]
If you're using the graph API without the `expo-facebook` library, then I suggest testing this in a bare react native project first. If it works there, then please fill out the entire bug report template, including a reproducible demo, and I'm happy to re-open the issue :) 

You may also want to try implementing Facebook login into your app with the `expo-facebook` module, which uses Facebook's Graph API behind the scenes. To implement that module, follow [these docs](https://docs.expo.io/versions/latest/sdk/facebook/)

**Comment by AndreUskovv** [comment]
## 🐛 Bug Report

### Environment

Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.1.0 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.11.7

Expo Client on iOS device

### Steps to Reproduce

Hello. I have app built on the EXPO library 35 version. Sign up/login on iOS real device with FB required to provide the login and password of FB, even if you logged in on your Facebook app. For Android and iOS simulator, it automatically logs in with cred of Facebook account.
For login /sing up in our app with FB account, I used this documentation https://developers.facebook.com/docs/graph-api/

### Expected Behavior

Automatically log in with credentials of Facebook account

### Actual Behavior

By pressing the Fb button, the application redirects me to the input page of my account

### Reproducible Demo

  async facebookLogin(socialAuthMutation) {
    const appId = env.FACEBOOK_APP_ID;

    let redirectUrl = 'https://auth.expo.io/@andrewuskov/cruisea-mobile';

    let result = await AuthSession.startAsync({
      authUrl:
          `https://www.facebook.com/v2.8/dialog/oauth?response_type=token` +
          `&client_id=${appId}` +
          `&redirect_uri=${encodeURIComponent(redirectUrl)}`,
    });

    if (result.type === "cancel") {
      return;
    } else if (result.type !== "success") {
      Alert.alert(
        "Whoops!",
        `Seems like you had trouble logging in with Facebook.`
      );
      return;
    }

    let token = result.params.access_token;

    console.log("TOKEN", token);

    const input = { provider: "facebook", accessToken: token };

    try {
      const { data } = await socialAuthMutation({
        variables: { input: input }
      });

      const {
        socialAuth: { token }
      } = data;

      await this.loginWithToken(token);
    } catch (err) {
      if (err.graphQLErrors && err.graphQLErrors.length) {
        const message = err.graphQLErrors.map(x => x.message).join(". ");
        Alert.alert("Hello Cruiser", `${message}.`);
      } else {
        console.error("Failed to login with facebook.", err);
        Alert.alert("Sorry!", `An unexpected error occurred.`);
      }
    }
  }


### Video 
[https://drive.google.com/open?id=1Jml2tGf0dAe1y_PXvs7u90bG9bj5bLDu](url)
