### ISSUE TITLE
Random.getRandomBytesAsync fails in tests

### ISSUE THREAD

**Issue by kieraneglin** [expo/expo#6980]
### Environment
```
  Expo CLI 3.11.7 environment info:
    System:
      OS: OS X El Capitan 10.11.4
      Shell: 5.0.8 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.2 AI-145.3360264
      Xcode: 7.3/7D175 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ~4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.7
```

Building for Android

### Steps to Reproduce

1. Create a plain JS module that uses `Random.getRandomBytesAsync` (mine is in `lib/encryption`)
2. Import and use it as described in the documentation
3. Try to test the module using Jest (as setup from the CLI init)

### Expected Behavior
The module behaves as it does on my Android target and is testable

### Actual Behavior
The module seems to work as expected on my phone, but returns the following in tests:
```
    TypeError: Cannot read property 'length' of undefined

      at getLens (node_modules/base64-js/index.js:23:17)
      at toByteArray (node_modules/base64-js/index.js:55:14)
      at getRandomBytesAsync$ (node_modules/expo-random/src/Random.ts:25:12)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/regenerator-runtime/runtime.js:145:13
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
```

### Notes
I'm new to Expo so I'm not sure if it matters, but code in the `lib` directory causes a refresh on device but the code doesn't actually seem to get picked up.  I have to force a rebuild for the new code to take effect.

Due to this limitation, I'm relying very heavily on Jest testing to verify correctness which is when I found this bug

**Comment by kieraneglin** [comment]
It is an aside but if there's a certain way I should structure my project or a config change that'll help my JS modules be compiled properly on change, that'd be great information to have

**Comment by cruzach** [comment]
> I'm new to Expo so I'm not sure if it matters, but code in the lib directory causes a refresh on device but the code doesn't actually seem to get picked up.

Not sure what could be causing this, and sounds like a really annoying issue so if you can share repro for it, I think opening an issue at https://github.com/expo/expo-cli is very reasonable

**Comment by adblanc** [comment]
Hi, I have kinda the same issue here, getRandomBytesAsync seems to never return in jest tests like so
![6760964c44792224ed4e4aa3f5a2d28a](https://user-images.githubusercontent.com/41756894/78026444-ec2fdf80-735b-11ea-959d-e6b712fc3c9f.png)
which make my jest tests to fail, where as it works nicely without jest.

**Comment by EvanBacon** [comment]
The code running in Jest isn't actually evaluating any native code. You can mock out the native functions like this: [Random-test.ts](https://github.com/expo/expo/blob/11087351b7451a1f560702358ca978194d8f1dc3/packages/expo-random/src/__tests__/Random-test.ts#L1-L9).

```js
import * as Random from "expo-random";

jest.mock("expo-random", () => ({
  getRandomBytesAsync: jest.fn(async () => 0),
  getRandomBase64StringAsync: jest.fn(async () => 0)
}));

jest.mock("base64-js", () => ({ toByteArray: jest.fn(() => {}) }));

it("works", async () => {
  await Random.getRandomBytesAsync(5);
});
```

If you want to test the native code you'll need a runner that starts a native device, I recommend using Detox.
