### ISSUE TITLE
ui_locales not processed in AuthSession

### ISSUE THREAD

**Issue by mschipperheyn** [expo/expo#6984]
## 🐛 Bug Report

The intermediate screen that Expo display doesn't seem to respect the `ui_locales` parameters passed with the authUrl and always displays English text.

```
const redirectUrl = AuthSession.getRedirectUrl();
const [verifier, challenge] = await getChallenge();
const state = randomString(8);

const params = {
    response_type: 'code',
    client_id: clientId,
    redirect_uri: redirectUrl,
    state,
    code_challenge: challenge,
    code_challenge_method: 'S256',
    ui_locales: 'pt-BR',
};

const authUrl =
    `${authorizeUrl}/authorize?` +
    Object.keys(params)
        .map(key => `${key}=${params[key]}`)
        .join('&');
const result = await AuthSession.startAsync({
    authUrl,
});

```

<img width="361" alt="Screen Shot 2020-02-06 at 11 57 31" src="https://user-images.githubusercontent.com/384959/73948547-e2e44280-48d7-11ea-9aad-aa69bec440f7.png">

### Environment

 Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.17 
      @types/react-native: ~0.60.23 => 0.60.28 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.7

In this case: Android

### Steps to Reproduce
- Start an asyncRequest
- Add ui_locales: 'pt-BR'.
- An English screen si displayed

I also tried `ui_locales: 'ptBR'` and `ui_locales: 'pt'`

### Expected Behavior

A Brazilian Portuguese screen is displayed.

### Actual Behavior

An English screen is displayed.

### Reproducible Demo

- we need some kind of open auth server for this.

**Comment by lukmccall** [comment]
Hi @mschipperheyn, your screenshot shows `auth.expo.io` which will redirect you to your auth server. Our server doesn't support any configuration. Moreover setting `ui_locales` and adding it to the `authUrl` will affect only your auth server of choice. 

To better understand how it's working you can check the graph below. 
![excalidraw-2020269353](https://user-images.githubusercontent.com/9578601/74024553-708c6480-49a2-11ea-81dc-54423f76774c.png)

So firstly you create auth URL which points to auth service. You can configure it according to the provider documentation. Then you pass it to the `AuthSession.startAsync` function, which wraps it.
And send it to expo servers, which redirect you to auth URL. 

Sadly you can't control how the expo server workes and which language it uses. However, when you publish your app, `auth.expo.io` won't longer show you this prompt. It'll automatically redirect to auth service.

**Comment by mschipperheyn** [comment]
@lukmccall actually, that doesn't seem to be the case. When I deploy to a staging release channel, I still see a redirect message (more elegantly formatted), but still in English. In production, this will be gone?

Honestly, just supporting English, is ehhhh. Well. I won't say anything, but yeah, that definitely merits a "bug" label. This could be part of a paid service. A facebook style oauth redirect screen. Customize redirect screen? But yeah, it should support all locales.

**Comment by lukmccall** [comment]
Sorry for misleading you. It'll be gone when you open your app outside expo-client. 

Maybe in the future, we'll support other languages. However, for now, we don't plane to do it.

**Comment by lukmccall** [comment]
I'm closing this issue right now. However, feel free to reopen it when the redirect message will be presented in the released app.
