### ISSUE TITLE
[expo-web-browser] crashes when user cancel authentication

### ISSUE THREAD

**Issue by lukmccall** [expo/expo#6988]
### Environment

```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.17.0 - /var/folders/bs/tw1fkxgx3k34ylc56zcshjgm0000gn/T/yarn--1581069311607-0.8700793575541805/node
      Yarn: 1.19.1 - /var/folders/bs/tw1fkxgx3k34ylc56zcshjgm0000gn/T/yarn--1581069311607-0.8700793575541805/yarn
      npm: 6.11.3 - ~/work/expo/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.0
      react-native: 0.61.4 => 0.61.4
```

It happens only on **iOS** (**bare workflow and client**).

### Steps to Reproduce

1. Sign in using AuthSession. 
2. Try to sign in again. 
3. Click the `Cancel` button, when the website redirects to the Google login form.  

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9578601/74020368-b133b000-4999-11ea-9cfe-f54f3f7ab4d8.gif)

### Expected Behavior

`AuthSession` should be cancelled. 

### Actual Behavior

App crashes - `Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)`.
This error occurs here: https://github.com/expo/expo/blob/d1a4d0c96bfe4e38a94382b13b013cb25bc448e5/packages/expo-web-browser/ios/EXWebBrowser/EXWebBrowser.m#L54

Moreover, it is strange cause the access token is present in the `callback URL` variable. What you can see here:
![Screenshot 2020-02-07 at 11 09 31](https://user-images.githubusercontent.com/9578601/74020664-551d5b80-499a-11ea-98f6-55941a1343ac.png)
It looks like the session was ended successfully, but `_redirectResolve` was null. 

### Reproducible Demo

> I've tested it only on [my branch](https://github.com/expo/expo/tree/%40lukmccall/expo-auth-session-extract-to-unimodule) with extracted `auth-session`. However, I didn't change how the auth session works in the client so it should be also reproduced with the released SDK code.
 
https://snack.expo.io/@lukaszkosmaty/expo-web-browser---crash

**Comment by truonghoangpham123** [comment]
Hi @Luk. Have you found a solution to this problem?
I am having a similar problem: rotate the phone when login, the app will crash.

**Comment by lukmccall** [comment]
Hi @truonghoangpham123. Unfortunately, we still don't know what causes this crash, but we're working on it ;)
