### ISSUE TITLE
SDK21: Android: Standalone stalls on getExpoPushTokenAsync

### ISSUE THREAD

**Issue by Palisand** [expo/expo#699]
The standalone version of an app that works fine in dev or when published to expo's servers stalls when it reaches the following code:
```javascript
const token = await Notifications.getExpoPushTokenAsync();
```

**Comment by quinlanj** [comment]
hey @Palisand , could you give us a reproduction of the bug or give us more info on this problem? It will go a long ways when we try to root cause and fix the issue.

**Comment by cpelina88** [comment]
Hello, 

I'm having the same issue where the server stalls at the line while testing on iOS

`const token = await Notifications.getExpoPushTokenAsync();` 

I wrapped the preceding code in a try/catch block, and this is the error message I received:

`{"line":102842,"column":84,"sourceURL":"http://packager.7k-iqr.cpelina88.trim-ios.exp.direct:80/main.bundle?platform=ios&dev=false&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles"}`

Any help would be greatly appreciated!

**Comment by Palisand** [comment]
@cpelina88 I ejected from expo and I'm using OneSignal to handle push notifications.

**Comment by glodfinch** [comment]
I encountered this in SDK 22. It seems to only occur when using AppLoading:
https://gist.github.com/glodfinch/ad859f48f9d06b5754cdef1a69424ab0
This code does not work.

However, the following code does work:
https://gist.github.com/glodfinch/17cdc49650f3bdf87e0df2cf3d92dcf0
