### ISSUE TITLE
Device.osName on Android returns something similar to Device.osBuildFingerprint

### ISSUE THREAD

**Issue by eggnukes** [expo/expo#6990]
### Environment
  Expo CLI 3.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Android Standalone (Expo SDK 35).

package.json dependencies:
```
    "@expo/vector-icons": "^10.0.0",
    "expo": "^35.0.0",
    "expo-asset": "~7.0.0",
    "expo-brightness": "~7.0.0",
    "expo-cli": "^2.21.2",
    "expo-constants": "~7.0.0",
    "expo-device": "~1.0.0",
    "expo-font": "~7.0.0",
    "expo-image-picker": "~7.0.0",
    "expo-keep-awake": "~7.0.0",
    "expo-location": "~7.0.0",
    "expo-permissions": "~7.0.0",
    "expo-print": "~7.0.0",
    "expo-task-manager": "~7.0.0",
    "expo-web-browser": "~7.0.0",
    "libphonenumber-js": "^1.7.20",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-moment": "^0.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-cli": "^2.0.1",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-gifted-chat": "^0.9.11",
    "react-native-maps": "~0.25.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-textfield": "^0.12.0",
    "react-native-reanimated": "~1.2.0",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-persist": "^5.10.0",
    "expo-intent-launcher": "~7.0.0",
    "react-native-screens": "~1.0.0-alpha.23"
```

### Steps to Reproduce
Include `import * as Device from 'expo-device';` and `console.log(Device.osName);` somewhere in your file.

### Expected Behavior
On Android I'm expecting for 'Android' to be logged in console.

### Actual Behavior
Logged value is something similar to the devices `osBuildFingerprint`.
Example:
...
  "brand": "HUAWEI",
  "designName": "HWPRA-H",
  "deviceYearClass": 2014,
  "isDevice": true,
...
  "manufacturer": "HUAWEI",
  "modelId": null,
  "modelName": "PRA-LX1",
  **"osBuildFingerprint": "HUAWEI/PRA-LX1/HWPRA-H:8.0.0/HUAWEIPRA-LX1/401(C432):user/release-keys"**,
  "osBuildId": "PRA-LX1 8.0.0.401(C432)",
  "osInternalBuildId": "HUAWEIPRA-LX1",
  **"osName": "HUAWEI/PRA-LX1/HWPRA-H:8.0.0/HUAWEIPRA-LX1/389(C432):user/release-keys",**
  "osVersion": "8.0.0",
  "platformApiLevel": 26,
  "productName": "PRA-LX1",
  "supportedCpuArchitectures": Array [
    "arm64-v8a",
    "armeabi-v7a",
    "armeabi",
  ],
  "totalMemory": 2915422208,
...

**Comment by Valdnieks** [comment]
I reproduced this bug with a simple Snack.

https://snack.expo.io/@laurismuraans/device-osname-bug

```Object {
  "brand": "samsung",
  "designName": "hero2lte",
  "deviceYearClass": 2015,
  "isDevice": true,
  "manufacturer": "samsung",
  "modelId": null,
  "modelName": "SM-G935F",
  "osBuildFingerprint": "samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXS7ETA4:user/release-keys",
  "osBuildId": "R16NW.G935FXXS7ETA4",
  "osInternalBuildId": "R16NW",
  "osName": "samsung/hero2ltexx/hero2lte:8.0.0/R16NW/G935FXXU3ERL3:user/release-keys",
  "osVersion": "8.0.0",
  "platformApiLevel": 26,
  "productName": "hero2ltexx",
  "supportedCpuArchitectures": Array [
    "arm64-v8a",
    "armeabi-v7a",
    "armeabi",
  ],
  "totalMemory": 3709685760,
}

**Comment by eggnukes** [comment]
Some of affected devices:
- HUAWEI ELE-L29
- HUAWEI PRA-LX1
- samsung SM-N975F

**Comment by buslocteam** [comment]
Hi Guys 

Seeing the same bug, any updates or workarounds

**Comment by seb-glanum** [comment]
Hello everyone ! Same issue here with Samsung SM-J610FN ! Any workaround ?

**Comment by vincenzorin** [comment]
Hello,
Same behaviour with the following devices:

(Supposed) European Samsung J5 SM-J510FN
returning: "samsung/j5xnltexx/j5xnlte:7.1.1/NMF26X/J510FNXXU2BRJ4:user/release-keys"

(Supposed) Huawei Mate 20 Lite (SNE-LX1)
returning:"HUAWEI/SNE-LX1/HWSNE:8.1.0/HUAWEISNE-LX1/131(C432):user/release-keys"

**Comment by jarredt** [comment]
We're also seeing this on certain devices, including a Motorola.

**Comment by jarredt** [comment]
Looking at the code path, this seems very unlikely this is a bug with the library: https://github.com/expo/expo/blob/master/packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.java#L122.

Seems like maybe these particular OEMs misconfigured the value for that the `Build.VERSION.BASE_OS` property? See https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/Build.java#295

**Comment by jetaix** [comment]
Same issue.

My workaround: use `Platform` from `react-native`.

`const platform = Platform.OS === 'android' ? 'Android' : 'iOS';`

**Comment by caioedut** [comment]
Same here...

**Comment by logunovbusiness** [comment]
Same with Nokia 7.2

**Comment by Adri7** [comment]
Same here with Xiaomi Mi A3

**Comment by wandersonalwes** [comment]
any solution for this bug?

**Comment by kbrandwijk** [comment]
It's not a bug, it's some devices natively reporting a different `osName`.

**Comment by terracatta** [comment]
This is 100% a bug. The API documentation heavily implies that the expected value of all Android devices should be "Android". I think this should be reopened.

**Comment by jordanjoecooper** [comment]
+1 I believe this is a bug. 

Whilst it's clear the manufacturers have made a mistake (it won't be rectified) and because the [react-native ](https://reactnative.dev/docs/platform-specific-code#platform-module)  manages this eventuality without issue, Its fair to expect this package to do this same - Either that or the documentation should be updated to reflect the known devices that won't get an accurate response.

**Comment by shawarmaz** [comment]
Incomplete docs, not a bug

**Comment by mspanc** [comment]
That should be reopened. This docs are misleading.

**Comment by Marcados** [comment]
Some Samsung are returning something like `samsung/a53xnaeea/a53x:13/TP1A.210814.014/A536PCJU9EWF9:user/release-keys`

This is definitely not the expected behaviour and misled many many use cases.

**Comment by sang-au** [comment]
I have same issue:  "osName": "samsung/a52qnsxx/a52q:13/TP1A.220624.014/A525FXXU6DWH2:user/release-keys"

**Comment by harunbuljubasic** [comment]
Same with Samsung S20

**Comment by davidcmello** [comment]
Same with Motorola.
"osName" : "motorola/odessa_retail/odessa:11/RPA31.Q2-59-17-4-3/d278a:user/release-keys"

**Comment by diegocuehdz** [comment]
Same with Samsung A32
```
"modelName": "SM-A325M",
"osName": "samsung/a32ub/a32:13/TP1A.220624.014/A325MUBU6DWK2:user/release-keys",
```

**Comment by merveillevaneck** [comment]
I recommend everyone coming across this issue use `Platform` from `react-native` to work around the issue as the maintainers of this package are not going to fix this issue (its 2024 now and this issue is still happening). For now, use the react native counterpart to make sure you have consistent behavior. 

I will add though, that its totally not called for to say that this isn't a bug when the expected behavior is clearly to consistently deliver the correct output for all android devices, as react-native manages to do.

That being said, I'm happy to help resolve the issue if the package is open to contributions :)

**Comment by marandaneto** [comment]
Same here, I disagree with https://github.com/expo/expo/issues/6990#issuecomment-1146346820
OEMs misconfigured the value for the Build.VERSION.BASE_OS and that is also a bug but it is much easier to workaround on this package rather than filing an issue for each OEM.
The [documentation](https://docs.expo.dev/versions/latest/sdk/device/#deviceosname) is misleading since the value might be different than all the listed options.

**Comment by cdcede** [comment]
> Same issue.
> 
> My workaround: use `Platform` from `react-native`.
> 
> `const platform = Platform.OS === 'android' ? 'Android' : 'iOS';`

Have to use this, because the problem persists. 

Not returning the osName
