### ISSUE TITLE
Use specific keys for display and client scoping instead of manifest.id

### ISSUE THREAD

**Issue by tcdavis** [expo/expo#6995]
When manifest contains a scopeKey, use it in place of the id to scope persistent storage, analytics, and notifications

When manifest contains a projectName, use it in place of the id when displaying the identifier of the current project to the user

To continue to support existing self-hosted projects, the presence of the new keys should not be assumed and we should fall back to the existing behaviour

**Comment by tcdavis** [comment]
@esamelson points out manifest.id is also used by AuthSession to communicate with auth.expo.io.    We should continue to manifest.id and not manifest.scopeKey in AuthSession

**Comment by brentvatne** [comment]
this ended up being a big project that @wschurman has spent a non trivial amount of his life working on
