### ISSUE TITLE
Android Video fullscreen exit button doesn't actually exit fullscreen on a Pixel 4

### ISSUE THREAD

**Issue by awinograd** [expo/expo#6997]
### Environment

```
  Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nodenv/versions/12.14.0/bin/node
      Yarn: 1.12.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nodenv/versions/12.14.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react: ^5.2.8 => 5.2.8 
      @storybook/react-native: ^5.2.8 => 5.2.8 
      @types/react: ^16.8.22 => 16.8.22 
      @types/react-native: 0.60.23 => 0.60.23 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.6 => 4.0.6
```

Android expo experience. Works fine on iOS

### Steps to Reproduce

https://snack.expo.io/@ouihealth/f86149

1. Tap on "Fullscreen" button.
1. Tap on "play" button to start video.
1. Tap on "fullscreen-exit" button in bottom right of fullscreen view

### Expected Behavior

Video should be minimized.

### Actual Behavior

Video stays fullscreen

### Reproducible Demo

https://snack.expo.io/@ouihealth/f86149

**Comment by cruzach** [comment]
Does this happen on a certain Android device/version? The snack simulator seems to exit normally

**Comment by awinograd** [comment]
Thanks for taking a look. 

My android device is a Pixel 4. Expo version 2.14.0.

I've seen the video sometimes exit successfully if you don't press play. But if I press play it seems almost to function more as a fit video to screen as I see the video jumping around a little

Any other info I can provide?

**Comment by awinograd** [comment]
By Android version is v10 (QQ1B.200105.004)

**Comment by cruzach** [comment]
Hm...I'm still not able to reproduce this 🙁 I've tried it on an Android 10 emulator, and also tried it while playing the video and while not playing the video

**Comment by awinograd** [comment]
@cruzach Very weird... I just had a friend try to repro on a Pixel 3 and everything was fine. Here's a video of me reproducing the issue:

https://imgur.com/a/K501iqb

I'll note that it worked once or twice, but ultimately always got into this bad state if I kept trying to fullscreen/minimize.

Any other things I can try here to maybe narrow down the root issue? 

---------

After the above I tried rebooting as well as uninstalling + reinstalling the expo client. Now, the fullscreening works the first several times I fullscreen/minimize the video, but again, always eventually ends up breaking. Steps to repro now are:

1. Tap full screen
1. Tap play
1. Tap minimize
1. Tap fullscreen
1. Repeat 3/4 over and over until it stops working

**Comment by awinograd** [comment]
Kept trying and was able to get it to behave like the original post again... https://imgur.com/a/Piwzm8V

I know this is a pretty weird bug. And, if my device is just bizarre for some reason I suppose I can accept that and move on with life :) In that case feel free to close

**Comment by cruzach** [comment]
That's definitely weird that you can only get this to happen on your own device.. Have you tried testing this on the same device you have, but on an emulator instead of the real device? Might help in determining if this a bug on that model (for some reason), or **just** on your device

**Comment by awinograd** [comment]
Can't seem to get the exact same version of android on an emulator. Also can't find any other version to exhibit the same bad behavior.

**Comment by blakehoffman** [comment]
I am also having this exact same problem on a Pixel 4, v10 (QQ1B.200205.002).  Can't seem to reproduce it in the emulator though.  Expo version 3.11.7.  What is weird is it seems positional.  I can get it to work if I make sure to tap on the top side of the exit button.  But the problem pops up when I hit it on the bottom side.  The app just locks up and doesn't do anything.  If I go to switch between apps on the device, but re-tap the app, it corrects itself and acts as it was before going into full screen.

**Comment by ryancmcmanus** [comment]
Also having the issue. Also on a Pixel 4 XL (QQ2A.200405.005). Oddly enough, if my phone's orientation is in landscape when the player is initiated, I can toggle back and forth between full screen and the initial size. However, once my phone returns to portrait, I run into the error. Additionally, on Android, the player's view doesn't rotate when in landscape as it does on iOS.

**Comment by cruzach** [comment]
looks safe to say this is particular to the Pixel 4

**Comment by ryancmcmanus** [comment]
Definitely more likely, I wasn't able to reproduce on a Nexus 5 (M4B30Z) or a Nexus 5X (OPM7.181205.001).

**Comment by yvbeek** [comment]
I'm having the same issue on my Pixel 4.

I can confirm that:
- doesn't help to upgrade to the latest Google Exo player version
- doesn't matter if the project is using Hermes or not
- doesn't help if I remove my `onFullscreenUpdate` or `onPlaybackStatusUpdate` handlers

**Comment by timoisalive** [comment]
Just sayin', I'm reproducing this on my Mi A2 Lite (Android 10, Expo 45).

Exits fullscreen if I press the top part of the fullscreen button, but doesn't when I press the lower half of the button, even though the `onFullscreenUpdate` event fires as expected with statuses 2 and 3. When pressing the lower half, the video freezes although the audio keeps playing. At this point there's no way to return from fullscreen. Before pressing the lower half, it is also possible to exit fullscreen by swiping from left edge of screen, as to go back.
