### ISSUE TITLE
Hide error messages in production

### ISSUE THREAD

**Issue by sonaye** [expo/expo#70]
It would be better if instead of showing a list of errors when the experience fails, to just show a refresh icon only. There is no need for our users to see this when the app/experience is in production.

![img_5931](https://cloud.githubusercontent.com/assets/23000873/23646235/020390c6-0321-11e7-8390-8a224e54e4be.PNG)

The icon and the background of the screen can follow `loading.exponentIconColor` and `loading.backgroundColor` in `exp.json` for a better branding.

**Comment by sonaye** [comment]
@brentvatne

**Comment by terribleben** [comment]
Thanks for the feedback, we've agreed to implement something similar to your suggestion. I don't have an ETA yet, but it's on our near-term roadmap.

**Comment by terribleben** [comment]
Hi, we made improvements to how this works, and users in production won't see your error details any more. Check out the new guide [here](https://docs.expo.io/versions/v16.0.0/guides/errors.html).
