### ISSUE TITLE
SDK21: Android: Standalone cannot launchCamera/ImageLibraryAsync

### ISSUE THREAD

**Issue by Palisand** [expo/expo#700]
```
const result = await ImagePicker.launchCameraAsync();
```
User is prompted to allow for the app to access the camera and after doing so, nothing happens. Subsequent attempts do not result in a prompt.

```
const result = await ImagePicker.launchImageLibraryAsync();
```
Nothing happens.

I have included the `CAMERA` permission in _`package.json`_.

**Comment by quinlanj** [comment]
hey @Palisand , could you give us a reproduction of the bug or give us more info on this problem? It will go a long ways when we try to root cause and fix the issue.

**Comment by aalices** [comment]
I think this is a duplicate of #627

**Comment by terribleben** [comment]
Closing as a duplicate of #627
