### ISSUE TITLE
expo-app-auth.authAsync is not available on android

### ISSUE THREAD

**Issue by sp0033212000** [expo/expo#7003]
### Environment

  Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild

android
### Steps to Reproduce
1) expo eject
2) android studio building
3) install apk in emulator

I'm using azure b2c oauth by expo-app-auth.
The application was executed well at first, but when I clicked login button and toggle authAsync then it do nothing...
No any message...

I tracked it step by step, then I found the message and code below
message: **"The method or property expo-app-auth.authAsync is not available on android, are you sure you've linked all the native dependencies properly?"**
code: **ERR_UNAVAILABLE**

How could I fix this problem?
By the way, the code works well on ios devices and emulators

### Expected Behavior

Click the login button, then entry the oauth process.

### Actual Behavior

The button doesn't do anything.

### Reproducible Demo

LoginScreen.js
<pre>import React, { useContext, useEffect, useState, useCallback } from "react";
import {View,Text,StyleSheet,TouchableOpacity,Image,Button} from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { Context as AuthContext } from "../../context/AuthContext";
import Loading from "../../components/Loding";
import Checker from "../../tools/hex.checker";
import { SCREEN_WIDTH, OS_PLATFORM } from "../../core/Device.Init";

const LoginScreen = ({ navigation }) => {
	const [click, setClick] = useState(false);
	const {
		state: { authState, error },
		SignIn,
		cleanError
	} = useContext(AuthContext);

	useEffect(() => {
		if (!Checker.isEmptyObj(authState)) {
			navigation.navigate("Main");
		}
		if (Checker.isNonEmptyStr(error)) {
			setClick(false);
		}
	}, [authState, error]);

	const onLoginPress = useCallback(() => {
		cleanError();
		setClick(true);
		SignIn();
	}, []);
	return (
		<View style={styles.view}>
			{click ? <Loading /> : null}
			<View style={styles.logoContainer}>
				<Image
					style={styles.logo}
					source={{ uri: "https://www.power-tech.com.tw/en/images/logo.png" }}
				/>
				<Text style={styles.titleText}>A9 Power</Text>
			</View>
			<MaterialCommunityIcons name="azure" style={styles.azureIcon} />
			{/* <Button onPress={onLoginPress} title="Login" /> */}
			<TouchableOpacity style={styles.azureButton} onPress={onLoginPress}>
				<Text style={styles.azureText}>Sign In</Text>
			</TouchableOpacity>
			<Text style={styles.sightText}>Making yore life easier ～</Text>
		</View>
	);
};
</pre>

authContex.js
<pre>
import { AsyncStorage } from "react-native";
import * as AppAuth from "expo-app-auth";
import createContext from "./createContext";
import azureConfig from "../private/azureConfig";
import { navigate } from "../navigationRef";
import actionTypes from "../types/action.types";
import key from "../private/key";
import Checker from "../tools/hex.checker";
import Axios from "axios";

const storageKey = key.StorageKey;

const authReducer = (state, { type, payload }) => {
	switch (type) {
		case actionTypes.SIGN_IN:
		case actionTypes.GET_AUTH_STATE:
			return { ...state, authState: payload };
		case actionTypes.LOGIN_ERROR:
			return { ...state, error: payload };
		case actionTypes.CLEAN_ERROR:
			return { ...state, error: "" };
		case actionTypes.SIGN_OUT:
			return { authState: {}, error: "" };
		default:
			return state;
	}
};

const SignIn = (dispatch) => async () => {
	try {
		console.log("Start Login");
		debugger;
		let authState = await AppAuth.authAsync(azureConfig);
		authState = JSON.stringify(authState);
		console.log("Store the cache");
		await AsyncStorage.setItem(storageKey, authState);
		return dispatch({
			type: actionTypes.SIGN_IN,
			payload: authState
		});
	} catch (error) {
		dispatch({
			type: actionTypes.LOGIN_ERROR,
			payload: error.message
		});
	}
};
</pre>

azureConfig.js
<pre>
export default azureConfig = {
	issuer:
		"https://talent.b2clogin.com/talent.onmicrosoft.com/strategy/v2.0",
	scopes: ["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "openid", "offline_access"],
	clientId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
	redirectUrl: 'com.domain.myapp:/'
};
</pre>

**Comment by cruzach** [comment]
What version of `expo-app-auth` do you have installed on this project?

**Comment by sp0033212000** [comment]
> What version of `expo-app-auth` do you have installed on this project? I tested this on a fresh bare `expo init` project and didn't have that problem

sorry about that...
It was my fault...
I excluded the expo-app-auth because the appAuthRedirectScheme problem.
Now I had fixed it.

**Comment by RudheerPamar** [comment]
@sp0033212000  how did you fixed it? i still get the same error
