### ISSUE TITLE
FileReader onProgress Event does not fire

### ISSUE THREAD

**Issue by ALEEF02** [expo/expo#7004]
### Environment

Expo CLI 3.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

Doesn't work: iOS
Haven't tested: Android
### Steps to Reproduce

1. Get a Blob object
2. Make a new `FileReader`
3. Set the `FileReader`'s `onProgress` property to anything you want
&nbsp;&nbsp;&nbsp;&nbsp;This can also be done using `.addEventListener('progress', callback);`
4. Read the Blob using `.readAsDataURL`

### Expected Behavior

The `onProgress` event should fire a minimum of 1 time, usually more if it's a larger blob

### Actual Behavior

The `onProgress` event never fires, no matter the file size

### Reproducible Demo

https://snack.expo.io/B1ORfXJQU
https://github.com/ALEEF02/Bulletin-Magazine-Mobile-App/commit/61eca4a991532b481a5e694f5a3a266ee483f300

**Comment by cruzach** [comment]
Have you tested this in a bare react native project? If the behavior there is the same, then this probably isn't a bug with the Expo SDK

**Comment by ALEEF02** [comment]
I haven't, as I don't know how to. I'll and figure out how to do that

**Comment by cruzach** [comment]
We have a walkthrough here - https://docs.expo.io/versions/v36.0.0/bare/exploring-bare-workflow/
