### ISSUE TITLE
Scheme for AuthSession - Example/Verification

### ISSUE THREAD

**Issue by oron11** [expo/expo#7005]
Hello,

I already opened a discussion or ask for verification here:
https://github.com/expo/expo/issues/6902

However, it has been closed and I still don't understand what should I write in the app.json.
I looked at the examples here: https://github.com/expo/examples/blob/master/with-webbrowser-redirect/app/app.json 
And I can't understand why the scheme is: 
`"scheme": "expo.examples.with-webbrowser-redirect",`

I think that a simple updated example For AuthSession with app.json file would be amazing.

Thank you,
Oron.

**Comment by cruzach** [comment]
Hi! Sorry I closed the last issue without explaining that a little clearer, we just keep Github reserved for bug reports, and our [forums](https://forums.expo.io/) are meant for questions like these.

the scheme can be (almost) whatever you want it to be. For example, I have some test apps where I've needed a scheme, and I've just used `myapp` as the scheme. You can include `.` characters in it, so another option is to use your package/bundleIdentifier as your scheme. 
Let me know if you still have questions or don't understand 😄
