### ISSUE TITLE
For iOS standalone app, I will need to add "facebookScheme" to app.json from info.plist but can't find info.plist file

### ISSUE THREAD

**Issue by skasanibanyan** [expo/expo#701]
Ad per this [guide](https://docs.expo.io/versions/latest/sdk/facebook.html#ios-standalone-app), I need to add the "facebookScheme" to my app.json which I should in the info.plist file in the ios build. But using Expo, I won't be able to find the info.plist file. 

How can I find this required value(It should look like "fb123456") in Expo?

For more info [Configure Your info.plist](https://developers.facebook.com/docs/facebook-login/ios)

**Comment by sonaye** [comment]
Take a look [here](https://docs.expo.io/versions/latest/guides/configuration.html#infoplist).
> Dictionary of arbitrary configuration to add to your standalone app’s native Info.plist. Applied prior to all other Expo-specific configuration. No other validation is performed, so use this at your own risk of rejection from the App Store.

**Comment by terribleben** [comment]
Hi, Expo doesn't provide access to the native Xcode project, so your project doesn't contain Info.plist (which is a native iOS configuration file). [app.json](https://docs.expo.io/versions/latest/guides/configuration.html#content) is a file included with all Expo apps which is used to configure your project for both iOS and Android. So the guide is saying that `app.json` should look like this:
```
{
  "expo": {
    "facebookScheme": "whatever",
    ...other configuration...
  }
}
```
And you don't need to make any changes to the non-existent Info.plist file.

**Comment by eddyoc** [comment]
I think the point is that the documentation states that the value for facebookScheme is _obtained 
 from_ the info.plist. Annoyingly Expo's own documentation points us to this same Facebook page.

As an undetached Expo project does not contain an info.plist from where does one obtain the value for facebookScheme?
