### ISSUE TITLE
MediaLibrary Error: "This file type is not supported yet" (expo36)

### ISSUE THREAD

**Issue by vmeyet** [expo/expo#7018]
### Environment

```
Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.13.6 - ~/.nvm/versions/node/v12.10.0/bin/npm
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.0 => 16.9.19
      @types/react-native: ^0.60.15 => 0.60.31
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ~4.1.1 => 4.1.1
    npmGlobalPackages:
      expo-cli: 3.11.9
```

App targets: iOS and Android

### Steps to Reproduce

I upgraded to  to expo36 and when using some `MediaLibrary` methods (`saveToLibraryAsync` and `createAssetAsync`) on iOS I got the error: "This file type is not supported yet".

here is the sample code

```typescript
  downloadImageToLibrary = async () => {
    const { uri } =this.props;

    // asking permissions here

    const response = await FileSystem.downloadAsync(
      uri,
      FileSystem.cacheDirectory + `temp-${randomId()}`
    );

    await MediaLibrary.saveToLibraryAsync(response.uri);
  }
```

To be noted:
- Images can be either png or jpeg (without prior knowledge)
- On Android nothing happens, the method doesn't throw an error but nothing is saved.
- On expo35 I was using `CameraRoll` from `react-native` and everything worked fine

### Reproducible Demo

See here https://snack.expo.io/BkdNrIxmU

Thanks in advance.

**Comment by lukmccall** [comment]
Hi @vmeyet, I've tested your demo.

When you download a file from the cloud, you save it in the cache directory. However, you don't provide file extension. `MediaLibrary` needes correct extension to work properly. Because to detected current type on iOS we use code looking like this:
```obj-c
```

**Comment by vmeyet** [comment]
@lukmccall Thanks for your answer, I understand the issue now.

Maybe it'll also be useful to add something about it in the documentation (the localUri should contain the extension).

This used to work regardless of the extension when I was using `CameraRoll.saveToCameraRoll`, the uri could be pointing to a png or a jpeg.

Detecting the mime type from the file itself instead of the extension could be a nice feature to have.

Anyway thanks again, you saved me a lot of debugging hours :).

**Comment by codingkapoor** [comment]
I am getting the same error when I am trying to download a **PDF** on an iPad. (Not sure if the same is the issue even on iOS mobile phone)

Note: This works perfectly fine on Andriod devices.

```javascript
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import * as MediaLibrary from 'expo-media-library';
import * as FileSystem from 'expo-file-system';
import * as Permissions from 'expo-permissions';

export default function App() {
  const saveFile = async fileUri => {
    const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
    if (status === "granted") {
      const asset = await MediaLibrary.createAssetAsync(fileUri);
      await MediaLibrary.createAlbumAsync("Download", asset, false);
      alert('Saved to Downloads');
    }
  }

  const downloadFile = () => {
    const uri = "http://192.168.1.5/assets/holidays.pdf"
    let fileUri = FileSystem.documentDirectory + "holidays.pdf";
    console.log(FileSystem.documentDirectory);
    FileSystem.downloadAsync(uri, fileUri)
      .then(({ uri }) => {
        saveFile(uri);
      })
      .catch(error => {
        console.error(error);
      })
  }

  const _onPress = () => {
    downloadFile();
  }

  return (
    <View style={styles.container}>
      <Text onPress={_onPress}>Open up App.js to start working on your app!</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Please suggest. Thanks.

**Comment by vmeyet** [comment]
@codingkapoor you can't save a pdf to the camera roll (see https://discussions.apple.com/thread/7211229). And `MediaLibrary` doesn't seem suited for what you are trying to achieve.

You can look into the [Sharing API](https://docs.expo.io/versions/latest/sdk/sharing/) to open pdf with appropriate apps or just save it.

**Comment by codingkapoor** [comment]
Much thanks!

**Comment by theambidextrous** [comment]
> I am getting the same error when I am trying to download a **PDF** on an iPad. (Not sure if the same is the issue even on iOS mobile phone). However, when I try to download a **JPG** file it works like a charm!
> 
> Note: This works perfectly fine on Andriod devices.
> 
> ```js
> import React from 'react';
> import { StyleSheet, Text, View } from 'react-native';
> import * as MediaLibrary from 'expo-media-library';
> import * as FileSystem from 'expo-file-system';
> import * as Permissions from 'expo-permissions';
> 
> export default function App() {
>   const saveFile = async fileUri => {
>     const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
>     if (status === "granted") {
>       const asset = await MediaLibrary.createAssetAsync(fileUri);
>       await MediaLibrary.createAlbumAsync("Download", asset, false);
>       alert('Saved to Downloads');
>     }
>   }
> 
>   const downloadFile = () => {
>     const uri = "http://192.168.1.5/assets/holidays.pdf"
>     let fileUri = FileSystem.documentDirectory + "holidays.pdf";
>     console.log(FileSystem.documentDirectory);
>     FileSystem.downloadAsync(uri, fileUri)
>       .then(({ uri }) => {
>         saveFile(uri);
>       })
>       .catch(error => {
>         console.error(error);
>       })
>   }
> 
>   const _onPress = () => {
>     downloadFile();
>   }
> 
>   return (
>     <View style={styles.container}>
>       <Text onPress={_onPress}>Open up App.js to start working on your app!</Text>
>     </View>
>   );
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: '#fff',
>     alignItems: 'center',
>     justifyContent: 'center',
>   },
> });
> ```
> 
> Please suggest. Thanks.

I got exact same error. On android all is fine but iOS only videos and images are saved. Any feasible solution using [MediaLibrary.saveToLibraryAsync](https://docs.expo.io/versions/latest/sdk/media-library/)?

**Comment by akiid777** [comment]
so what Is the solution? 
I use the following and I did not work : 
```

if (Platform.OS === 'ios') {
// use Token and stuffs: 
      axiosMobileApiInstance
          .get(`/client/certificate/${code}.pdf`)
          .then(response => {
          // as my response is array of one single link that contain certificate 
            Sharing.shareAsync(response.data.url[0])
          })
          .catch(err => {
            console.log('error' + err);
          })
```

**Comment by xmityaz** [comment]
> I am getting the same error when I am trying to download a **PDF** on an iPad. (Not sure if the same is the issue even on iOS mobile phone). However, when I try to download a **JPG** file it works like a charm!
> 
> Note: This works perfectly fine on Andriod devices.
> 
> 
> Please suggest. Thanks.

Hi there.
I had a similar issue and managed to get a working solution for iOS using `expo-sharing`.
The only difference from the PDF example was that I needed to export CSV data from my app to the local file.
Hope my example might be useful for someone

```js
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

// ...

const exportCsv = async () => {
  try {
    const csvData = await generateCsvData();
    const csvContent = csvData.map((e) => Object.values(e).join(',')).join('\n');

    try {
      const fileUri = `${FileSystem.documentDirectory}history.csv`;
      await FileSystem.writeAsStringAsync(fileUri, csvContent);
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/csv',
        dialogTitle: 'History',
        UTI: 'public.comma-separated-values-text',
      });
    } catch (error) {
      console.log('Error in saving file', error);
    }
  } catch (error) {
    console.log('Error in getting history data', error);
  }
};

// ...
```
