### ISSUE TITLE
speech to text api

### ISSUE THREAD

**Issue by masihfathi** [expo/expo#702]
do you have any plan in near future to add speech to text api?
 thanks for your graet work in expo.

**Comment by Palisand** [comment]
https://expo.canny.io/feature-requests/p/text-to-speech-api

**Comment by Palisand** [comment]
You can add a feature request [here](https://expo.canny.io/feature-requests).

**Comment by terribleben** [comment]
Thanks for opening this [request](https://expo.canny.io/feature-requests/p/speech-to-text-api), I'll close this issue now.

**Comment by elmarti** [comment]
Could this be a duplicate feature request now as per this issue? https://github.com/expo/expo/issues/629
