### ISSUE TITLE
[expo-calendar] Create Reminder API not saving URL on the device

### ISSUE THREAD

**Issue by narender2031** [expo/expo#7020]
[##](url) 🐛 Create Reminder API not saving URL on the device

## Environment
Using Unimodule on Bare app

[](url)

### Steps to Reproduce
1. Run this snack on the actual IOS device.
2. Create a Calender.
3. Create a Reminder 

### Expected Behavior
It should save a URL on creating a calendar.

### Actual Behavior
reminder object have `null` URL value

![photo6204251109032306841](https://user-images.githubusercontent.com/25151772/74270194-d2492780-4d30-11ea-9646-7f06bd2fb9e0.jpg)

### Reproducible Demo
https://snack.expo.io/@narender2031/reminders-

**Comment by cruzach** [comment]
hm..`await Calendar.getCalendarsAsync(Calendar.EntityTypes.REMINDER);`  isn't returning any calendars for me

**Comment by lukmccall** [comment]
Hi @narender2031, I checked your demo. And it seems no to save URLs only on iOS 13. However, I believe that is an issue in the system not in the Expo. I'm not sure, but I'll do more research.
