### ISSUE TITLE
Cannot import expo notifications

### ISSUE THREAD

**Issue by sp0033212000** [expo/expo#7024]
### Environment

<pre>
  Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
</pre>

**iOS and Android**

### Steps to Reproduce

I followed the step of documentation of "expo push notification".
It worked when I open by expo client app.
Then I executed through xcode, it show the error below.
![IMG_67043E034CD5-1](https://user-images.githubusercontent.com/56681081/74302407-6519ae80-4d91-11ea-81d8-4fa4590e4a2f.jpeg)

### Expected Behavior

Prompt the permissions, Got the token, the register to server

### Reproducible Demo

<pre>
import { Notifications } from 'expo';
import * as Permissions from 'expo-permissions';

const PUSH_ENDPOINT = 'https://your-server.com/users/push-token';

export default async function registerForPushNotificationsAsync() {
  const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
  // only asks if permissions have not already been determined, because
  // iOS won't necessarily prompt the user a second time.
  // On Android, permissions are granted on app installation, so
  // `askAsync` will never prompt the user

  // Stop here if the user did not grant permissions
  if (status !== 'granted') {
    alert('No notification permissions!');
    return;
  }

  // Get the token that identifies this device
  let token = await Notifications.getExpoPushTokenAsync();

  // POST the token to your backend server from where you can retrieve it to send push notifications.
  return fetch(PUSH_ENDPOINT, {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      token: {
        value: token,
      },
      user: {
        username: 'Brent',
      },
    }),
  });
}
</pre>

**Comment by cruzach** [comment]
Push notifications aren't supported outside of the managed workflow, yet. We're working on that and hopefully will have some good news for you very soon 😄
