### ISSUE TITLE
Audio only playing through bluetooth headphones when playing over "ducked" other audio.

### ISSUE THREAD

**Issue by schumannd** [expo/expo#7028]
### Environment

ejected app:

RN: 0.61.4
expo-av: 8.0.0
  
### Steps to Reproduce

When playing audio alone, it seems to be playing (progress gets updated), but no sound arrives at the Bluetooth headphones.

Whil playing around I discovered, that setting `interruptionModeIOS` to `Audio.INTERRUPTION_MODE_IOS_DUCK_OTHERS`, the audio plays as long as other sounds are being ducked in the background. As soon as I remove those sound sources, the audio within my app (while still advancing audio position) stops.

### Expected Behavior

Audio should work over bluetooth

### Actual Behavior

Audio doesn't work over bluetooth

### Reproducible Demo

If anyone could link me to an ejected app using expo-av, that would be great. Otherwise a simple expo app using audio that I can fork

**Comment by schumannd** [comment]
It seems like this bug is dependent on the BT headphone model

Headphone models that work:
- Bose QC 35 II

Headphone models that experience this bug:
- Bose NC 700


I just checked and this problem also exists with react-native-sound (the package we are migrating from), so I guess it is an iOS wide problem.

**Comment by crudexec** [comment]
I think this is still an issue

**Comment by n-sviridenko** [comment]
+1

**Comment by IjzerenHein** [comment]
@schumannd I noticed you closed and re-opened this issue. You mention that this also happens with react-native-sound and seems to be an iOS wide problem. Do you have new evidence this might be in the `expo-av` package somehow?

**Comment by schumannd** [comment]
@IjzerenHein 

It does not happen when using some iOS native apps like apple music, so it should be possible theoretically to implement this functionality correctly.

I know that react-native-sound uses AVFoundation if expo-av uses the same the issue may be in that package.

**Comment by IjzerenHein** [comment]
@schumannd I see. Can you provide us with a simple example app that demonstrates this problem? Then I'll try to muster up a bluetooth headset to see whether I can reproduce the problem. Thanks!

**Comment by schumannd** [comment]
I won't be able to in the near future. We are not using this package anymore. You can basically take any example app that plays audio, and then play around with the bluetooth headphones.

**Comment by IjzerenHein** [comment]
I did some preliminary testing and have so far been unable to reproduce this problem. I tested with Apple airpods which I have to my disposal. 

@schumannd You mention that the problem happens with the Bose NC 700 but not with another Bose BT headset. It's possible the problem is specific to that headset. I did some digging and found lots of people have been having problems with the Bose NC 700. In the meantime Bose has released various firmware updates, please try updating to the latest firmware to see whether the problem has been resolved.

@crudexec @Lyubomyr @n-sviridenko With which Bluetooth headset/speaker did you have problems with?

**Comment by covahn** [comment]
Maybe someone is having this issue for the same reason as me. Try setting **playsInSilentModeIOS** to true and check that your phone is not on silent. 😉

```jsx
setAudioModeAsync({
      playsInSilentModeIOS: true,
}
```

**Comment by mfrfinbox** [comment]
> Maybe someone is having this issue for the same reason as me. Try setting **playsInSilentModeIOS** to true and check that your phone is not on silent. 😉
> 
> ```js
> setAudioModeAsync({
>       playsInSilentModeIOS: true,
> }
> ```

You saved me a lot of time
