### ISSUE TITLE
Saving audio on Firebase Storage

### ISSUE THREAD

**Issue by kevandev** [expo/expo#703]
I'm trying to record and save Audio to Firebase Storage

I'm able to record and play the newly recorded audio in the App, but when trying to save to Firebase Storage, it is not working.

Has anyone solved this?

**Comment by sonaye** [comment]
Firebase storage is not yet supported.
- [X] https://github.com/facebook/react-native/pull/11417
- [ ] https://github.com/facebook/react-native/pull/11573

**Comment by terribleben** [comment]
Sadly we can't support Firebase Storage until the aforementioned changes are merged to react native. We'll update [this thread](https://expo.canny.io/feature-requests/p/full-native-firebase-integration) when we're able to make it available.
