### ISSUE TITLE
How to distribute package for expo? (.web.js, .js configuration)

### ISSUE THREAD

**Issue by kopax** [expo/expo#7034]
I want to distribute a package for expo. This package was created while building my app in expo SDK36. 

Like many expo dependencies, I use massively the `.ios.s`, `.android.js` and `.web.js` extensions.

While importing a source I have distributed on npm, resolver only import `.js` without any distinction.

As an example [this package](https://github.com/yeutech-lab/react-cookiebot/tree/master/src) should work with expo:

![image](https://user-images.githubusercontent.com/1866564/74368892-0bec6200-4e07-11ea-8d4d-d2b4f9e8081a.png)

But it does not, I have to manually import by suffixing in my sources with`.web`. 

How can I configure `expo` or my distributed package in order to be able to import proper sources for each environment when sources are imported from `node_modules` ?

**Comment by awinograd** [comment]
@kopax , webpack doesn't support extensions on your "main" file from `package.json`. I believe a workaround for your package is to do something like:

```
// index.js
export { default } from './CookieBot';
```

and then have `Cookiebot.js` and `Cookiebot.web.js`

**Comment by kopax** [comment]
Hi and thanks for your answer @awinograd. I was effectivly using the `main` field from the `package.json` and I am configuring it as you recommended to try again, I will update my CookieBot sample. 

Where have you seen this information and will it be enough to properly configure expo for ios/native and web ?

Also, just to confirm I understand properly,_ can I instead do this instead:

```
/home/dka/workspace/github.com/yeutech-lab/react-cookiebot/src
├── CookieBot.js
├── CookieBot.native.js
└── index.js
```

**Comment by EvanBacon** [comment]
Answered the SO.

**Comment by thareekanvar** [comment]
@EvanBacon can i know how to use ..web specifc package using this..any example is helpfull ..please
