### ISSUE TITLE
Android standalone builds show expo logo on loading

### ISSUE THREAD

**Issue by sonaye** [expo/expo#704]
<img src="https://user-images.githubusercontent.com/23000873/31021264-fc9848d8-a53d-11e7-9737-bd0a813a64f7.png" width="400">

```
"loading": {
  "backgroundColor": "#171717",
  "loadingIndicatorStyleExperimental": "light"
}
```

As you can see in the screenshot above, when loading the app, the Expo logo shows up for some reason, this shouldn't be the case. The behavior however is correct on IOS, it shows the loading indicator instead. The loading experiences should match on both platforms to avoid any confusion. Instead of showing the Expo logo, we should have the loading indicator on Android.

**Comment by terribleben** [comment]
I believe Android's behavior is to [show a logo](https://docs.expo.io/versions/latest/guides/configuration.html#exponenticoncolor) if no icon is specified.

Moving ahead I think our plan is to focus on the Splash API (currently it still needs improvement). Once it's stable and consistent I wouldn't be surprised if we deprecate the old API.

Ping @jesseruder in case he can provide any other Android info.

**Comment by dikaiosune** [comment]
@sonaye what happens if you specify a transparent png for the logo here? Does the Expo logo still show up?

**Comment by sonaye** [comment]
@dikaiosune No, only the background color would show, but it ruins the logo on IOS instead (only an indicator at the bottom), the API behaves differently depending on the platform.

**Comment by sonaye** [comment]
New splash API fixes this.
