### ISSUE TITLE
Refactoring expo-permissions

### ISSUE THREAD

**Issue by mark-friedman** [expo/expo#7047]
## 🐛 Bug Report

In Expo 36 I see the following in the docs for expo-permissions:

>expo-permissions includes the shared infrastructure for handling system permissions, it does not include the code specific to particular permissions. For example, if you want to use the CAMERA_ROLL permission, you need to install expo-image-picker or expo-media-library.

In the past (at least in v34) it seemed that you didn’t need to install an Expo package which uses a permission in order to ask for that permission in your own component/code.  Is there a way around that requirement?  If not, are there plans to separate out the permissions asking mechanism from specific Expo components that need those permissions?

**Comment by cruzach** [comment]
You don't need to install a specific expo package just to ask for the permission (you can do that with `expo-permissions`). But the actual methods to **use** those permissions are now in each of the specific modules

You also don't need the `expo-permissions` module to ask for permissions, as you can ask for them straight from the module, itself, as of SDK 36! See this from our release notes:

 > In the past, all runtime permissions requests went through the Permissions API, which includes methods and constants for requesting every possible permission Expo can use. This meant that you needed to import from expo-permissions in every file that needed to request permissions from a user.
No more! Now, each module that needs user-facing permissions includes its own methods for requesting and checking the status of permissions. For example, if you use the MediaLibrary API, you can use MediaLibrary.requestPermissionsAsync().
The Permissions module is still available for backwards compatibility and isn’t going anywhere! We’re simply providing these new methods for your convenience 🙂

Let me know if that answers your question

**Comment by mark-friedman** [comment]
Maybe I misunderstand, but our experience was that we needed to add a specific expo package in order for the permission request to actually take effect.  To be specific, we want to use the react-native-image-picker library rather than expo-image-picker so that we can build our own UI for image picking.  Before SDK 36 we could just ask for the `Permissions.CAMERA` and `Permissions.CAMERA_ROLL` permissions and all would be good.  Since SDK 36, simply asking for the permissions no longer works.  However, it did work when we added expo-image-picker in our package.json, **even though we don't actually use expo-image-picker in our code**.

**Comment by cruzach** [comment]
How were you asking for permissions before SDK 36, and what do you mean when you say it doesn't work? Is an error thrown, or does the status always return `undetermined`? 

 All the previous functionality should still be there

**Comment by mark-friedman** [comment]
@josmas, You have more context on this than I do.  Would you like to respond?

**Comment by josmas** [comment]
Sure, so our main issue is that we do ask for CAMERA_ROLL in a custom component:
```
Permissions.askAsync(Permissions.CAMERA_ROLL).then(() => {...}
```
but after upgrading to 36, we get back an `Unrecognized permission cameraRoll` error. We also ask for CAMERA and that one works fine. But the only way around this, that we could find, is to install one of the components that uses CAMERA_ROLL, which will in turn make the permission available to our custom component (even though we are not using the particular expo component, in our case the image picker).

This is actually documented, as @mark-friedman highlighted above:

> expo-permissions includes the shared infrastructure for handling system permissions, it does not include the code specific to particular permissions. For example, if you want to use the CAMERA_ROLL permission, you need to install expo-image-picker or expo-media-library.

So the new refactoring seems to indicate that we cannot use _expo-permissions_ for anything other than expo components.

**Comment by cruzach** [comment]
Ah oaky thanks for pointing that out. Yes, [according to the documentation](https://docs.expo.io/versions/latest/sdk/permissions/#usage-in-bare-workflow) for using permissions in the bare workflow, certain permissions will require you to install certain packages. For instance, you say asking for `CAMERA` permissions worked- this is probably because you have `expo-camera` or `expo-barcode-scanner` installed

**Comment by mark-friedman** [comment]
@cruzach My point is that it would be nice if there were a way to ask for and use permissions without requiring an Expo package which uses that permission.  I.e., to separate out the permission mechanism from the packages which implement functionality requiring those permission.
