### ISSUE TITLE
Sqlite join bug

### ISSUE THREAD

**Issue by KakarN** [expo/expo#705]
I am getting very weird results when using the Expo's SQLite module.

Please consider these two tables, i.e., users and messages:

```
CREATE TABLE IF NOT EXISTS users (
	id integer primary key, 
	email text
);

CREATE TABLE IF NOT EXISTS messages (
	id integer primary key, 
	sender_id integer, 
	thread_id integer, 
	body text, 
	foreign key (sender_id) references users (id), 
	foreign key (thread_id) references threads (id)
);
```

Lets insert some rows into both users and messages:

```
insert or replace into users (id, email) values (1, 'first@mail.com');
insert or replace into users (id, email) values (2, 'second@mail.com');
insert or replace into users (id, email) values (3, 'third@mail.com');

INSERT INTO messages (id, sender_id, thread_id, body) values (1, 3, 1, 'hello world');
INSERT INTO messages (id, sender_id, thread_id, body) values (2, 1, 1, 'test');
INSERT INTO messages (id, sender_id, thread_id, body) values (3, 2, 1, 'check again');
INSERT INTO messages (id, sender_id, thread_id, body) values (4, 1, 1, 'payload');
```

Now to get all the messages, including its related user data I need to select from both the tables:
`select * from messages inner join users on messages.sender_id=users.id where thread_id =1;`

Here the instead of getting results like this (note the `id` and `sender_id`:

```
id          sender_id   thread_id   body         id          email         
----------  ----------  ----------  -----------  ----------  --------------
1           3           1           hello world  3           third@mail.com
2           1           1           test         1           first@mail.com
3           2           1           check again  2           second@mail.co
4           1           1           payload      1           first@mail.com
```

I am getting results like this:
```
id          sender_id   thread_id   body         id          email         
----------  ----------  ----------  -----------  ----------  --------------
3           3           1           hello world  3           third@mail.com
1           1           1           test         1           first@mail.com
2           2           1           check again  2           second@mail.co
1           1           1           payload      1           first@mail.com
```

As you can see from the above results, instead of the `message` id to have its own value, the `message`'s id are replaced by the `sender`'s id. 

[I have made an expo snack demo link here.](https://snack.expo.io/BJ1BoAjo-)

What's going on here?

**Comment by KakarN** [comment]
When only selecting one table, I am getting the expected results:
`select * from messages;`
Returns back with messages own id, instead of the sender_id.
```
[
	{
		"id":1,"sender_id":3,"thread_id":1,"body":"hello world"
	},
	{
		"id":2,"sender_id":1,"thread_id":1,"body":"test"
	},
	{
		"id":3,"sender_id":2,"thread_id":1,"body":"check again"
	},
	{
		"id":4,"sender_id":1,"thread_id":1,"body":"payload"
	}
]
```
As you can see, I think it only happens when JOIN tables.).

**Comment by KakarN** [comment]
Now, this is weirder! When selecting users table and joining the messages table

`select * from users, messages where thread_id = 1 and messages.sender_id = users.id;`

Then I get the messages rows including the user’s data, and, the messages have their own id instead of the sender_id's value.

```
[
	{
		"id":1,"email":"third@mail.com","sender_id":3,"thread_id":1,"body":"hello world"
	},
	{
		"id":2,"email":"first@mail.com","sender_id":1,"thread_id":1,"body":"test"
	},
	{
		"id":3,"email":"second@mail.com","sender_id":2,"thread_id":1,"body":"check again"
	},
	{
		"id":4,"email":"first@mail.com","sender_id":1,"thread_id":1,"body":"payload"
	}
]
```
[Snack demo](https://snack.expo.io/r1Sz-x2oZ)

**Comment by terribleben** [comment]
I believe we just wrap the `sqlite3` library that ships with iOS and Android, so there's low chance Expo-specific changes are happening to your results. Pinging @nikki93 in case you have any ideas.

**Comment by KakarN** [comment]
@terribleben Yes, I hope so. But, I have tried to implement the same tables and rows in a standalone sqlite3 DB in my mac, and the results are very different if two tables are joined.

**Comment by nikki93** [comment]
@KakarN -- I think this is because there are two `id` columns generated in the result. I ran this through 'SQL Fiddle' (basically your example but without too much application-specific baggage):
<img width="1388" alt="screenshot 2017-12-04 16 41 31" src="https://user-images.githubusercontent.com/49151/33577759-0d963926-d912-11e7-91ab-8d7930683021.png">

A JavaScript 'object' (which is what the row is converted to) can have only one 'column' with a given name. So you may have to modify your SQL query to create distinct columns names in the generated results. I do have a reproduction of your case, I'll check if aliasing works.

**Comment by nikki93** [comment]
Indeed, as expected, aliasing columns works... i.e., `SELECT Joining1.id AS id1, Joining2.id AS id2 FROM Joining2 INNER JOIN Joining1 on Joining2.join_id=Joining1.id` produces: ```[exp] Array [
[exp]   Object {
[exp]     "id1": 3,
[exp]     "id2": 1,
[exp]   },
[exp]   Object {
[exp]     "id1": 1,
[exp]     "id2": 2,
[exp]   },
[exp]   Object {
[exp]     "id1": 2,
[exp]     "id2": 3,
[exp]   },
[exp]   Object {
[exp]     "id1": 1,
[exp]     "id2": 4,
[exp]   },
[exp] ]```

**Comment by nikki93** [comment]
In summary, `SQLResultSetRowList`s (https://www.w3.org/TR/webdatabase/#sqlresultsetrowlist) represent reach row of the result by a JavaScript `Object` which can represent only one 'column' with a given name. Your case has two columns with the name 'id', producing unpredictable results (either column would represented). This can be dealt with by appropriately aliasing columns in your query.
