### ISSUE TITLE
Requesting granted Permissions throws an error in bare workflow

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#7050]
### Environment

```sh
  Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.14.1/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.19 
      @types/react-native: ~0.60.23 => 0.60.31 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.11.9
```

### Steps to Reproduce

- expo init - select bare (typescript)
  - using `expo-permissions@8.0.0`
- Install pkg `expo install expo-contacts`
- Run on android `npx react-native run-android` (or any other way on android)
- Running `Permissions.askAsync(Permissions.CONTACTS)` will work as expected the first time. 
  - prompts for permission, returns status (same happens if you add WRITE_CONTACTS permission to android manifest).
- Running it every time after that will throw an error:
```
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Encountered an exception while calling native method: Exception occurred while executing exported method requestPermissionsAsync on module ExpoContacts: null
```
- Using `Contacts.requestPermissionsAsync()` also throws the error.

### Reproducible Demo

This demo works (from [the docs](https://docs.expo.io/versions/latest/sdk/contacts/))
```js
import React, { useEffect } from 'react';
import { View, Text } from 'react-native';
import * as Contacts from 'expo-contacts';
import * as Permissions from 'expo-permissions';

export default function App() {
  useEffect(() => {
    (async () => {
      const { status } = await Contacts.requestPermissionsAsync();
      // Also broken...
//      const { status } = await Permissions.askAsync(Permissions.CONTACTS);

      if (status === 'granted') {
        const { data } = await Contacts.getContactsAsync({
          fields: [Contacts.Fields.Emails],
        });

        if (data.length > 0) {
          const contact = data[0];
          console.log(contact);
        }
      }
    })();
  }, []);

  return (
    <View
      style={{
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Text>Contacts Module Example</Text>
    </View>
  );
}
```

**Comment by lukmccall** [comment]
Unfortunately, I wasn't able to reproduce this. Could you provide more information like your Android version or logs from your device?

**Comment by faustoct** [comment]
I got
````
TypeError: undefined is not an object (evaluating '_ExpoContacts.default.getContactsAsync')
````

**Comment by lukmccall** [comment]
@faustoct, could you provide logs from your device?

To do this:
- Enable USB debugging in your device.
- Connect the device to the computer
- Use these commands:
  -  `adb devices` (to get your device id)
  - `adb -s <id> logcat --pid=$(adb shell pidof -s <your package name>)`
 (Expo client package name: `host.exp.exponent`)

**Comment by david-potgieter** [comment]
If you stumble across `TypeError: undefined is not an object (evaluating '_ExpoContacts.default.getContactsAsync')` - in my case it was not a correctly configured `react-native-unimodules`. Compare your AppDelegate.h, AppDelegate.m and Podfile with the repo here: https://github.com/brentvatne/testwithsixtwo/tree/234b14cd638aa08aa209afbaaafa89c6cdf1c2cd

After adding missing code my error was resolved.
