### ISSUE TITLE
Orientation from DeviceMotion is always 0.

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#7051]
### Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
      npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.2 => 36.0.2
      react: ^16.12.0 => 16.12.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.13.1
```

Target: Android

### Steps to Reproduce

```js
import { DeviceMotion } from 'expo-sensors'
DeviceMotion.addListener( ( { orientation } ) => {
  console.log( orientation, ' is always 0' )
} )
```

### Expected Behavior

To return `Device orientation based on screen rotation. Value is on of 0 (portrait), 90 (right landscape), 180 (upside down), -90 (left landscape).` as per [documentation](https://docs.expo.io/versions/latest/sdk/devicemotion/#devicemotionaddlistenerlistener).

### Actual Behavior

Orientation is always zero.

### Reproducible Demo

See [this snack](https://snack.expo.io/@mentor/awkward-chip). Frustratingly:

1. This works when running through snack (except the 180deg orientation)
2. It does not work when run verbatim from my local expo

Edit: the local problem was indeed because of the orientation setting in the app settings. The above is only relevant for the upside-down problem.

**Comment by cruzach** [comment]
Hm, this is working locally for me (except for the 180 degree orientation, as you said)

Is your screen itself rotating? Make sure you don't have the orientation locked with the `orientation` field of app.json, and that you've installed expo-sensors with `expo install expo-sensors`

**Comment by actuallymentor** [comment]
I notice that the app opens correctly (upside down) given:

- `orientation: 'default'`
- app opens when phone upside down

However when I rotate to anything other than upside down:

- Rotation works
- *Upside down is never triggered* aside from when the app preview is triggered when the phone is already upside down and *only at first load after preview app start*

Suspicion:

- Expo or the preview app have a different routine checking for orientation at start and when running

**Comment by actuallymentor** [comment]
Update: upside down doesn't work at all. The reason it worked for me at first open was that I (forgot that I) manually added:

```js
async componentDidMount() {

	// Put upside down if developing
	if( process.env.NODE_ENV == 'development' ) await ScreenOrientation.lockAsync( ScreenOrientation.Orientation.PORTRAIT_DOWN )
	await ScreenOrientation.unlockAsync()

	// Create and store expo push token
	await askForPushPermissions()
}
```

**Comment by cruzach** [comment]
@actuallymentor so the issue you're reporting is that upside down orientation doesn't work?

**Comment by actuallymentor** [comment]
Yes and no.

Yes: when rotation is enabled the upside down is the only one that doesn't work.

No: this is a sensor package, shouldn't it return orientation based on device, even if the software rotation is locked?

**Comment by cruzach** [comment]
Ah okay, could you edit the original ticket to reflect what it is that you're reporting as an issue?

**Comment by EvanBacon** [comment]
Duplicate https://github.com/expo/expo/issues/2430

**Comment by dminkovsky** [comment]
Alas, #2430 was closed to due to staleness, not because it was fixed. `DeviceMotion` should return orientation that is not dependent on whether the screen is locked.

**Comment by p369m** [comment]
well to solve this problem :
#CASE : Orientation is always zero or  when rotation is enabled the upside down is the only one that doesn't work.

To solve this problem
1.  remove orientation: 'default' from app.json
2.  unlock screen Orientation using , ScreenOrientation.unlockAsync(); {include in expo-screen-orientation}
3. ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.ALL); {include in expo-screen-orientation}

NOTE: I am writing for first time and also I am very new in react-native,pls forgive my mistakes.

**Comment by arimariojesus** [comment]
> well to solve this problem : #CASE : Orientation is always zero or when rotation is enabled the upside down is the only one that doesn't work.
> 
> To solve this problem
> 
> 1. remove orientation: 'default' from app.json
> 2. unlock screen Orientation using , ScreenOrientation.unlockAsync(); {include in expo-screen-orientation}
> 3. ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.ALL); {include in expo-screen-orientation}
> 
> NOTE: I am writing for first time and also I am very new in react-native,pls forgive my mistakes.

This worked for me!

**Comment by p369m** [comment]
> > well to solve this problem : #CASE : Orientation is always zero or when rotation is enabled the upside down is the only one that doesn't work.
> > 
> > To solve this problem
> > 
> > 1. remove orientation: 'default' from app.json
> > 2. unlock screen Orientation using , ScreenOrientation.unlockAsync(); {include in expo-screen-orientation}
> > 3. ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.ALL); {include in expo-screen-orientation}
> > 
> > NOTE: I am writing for first time and also I am very new in react-native,pls forgive my mistakes.
> 
> This worked for me!


Happy to help you 😊!

By the way if you want to get device orientation data without rotating app screen here is a package [react-native-expo-device-orientation](https://www.npmjs.com/package/react-native-expo-device-orientation).
