### ISSUE TITLE
LocalAuthentication fails in bare react native app [ TypeError: Cannot read property <ex: hasHardwareAsync> of undefined]

### ISSUE THREAD

**Issue by etaiklein** [expo/expo#7054]
## 🐛 Bug Report
`TypeError: Cannot read property 'hasHardwareAsync' of undefined`
(The same error is received by calling every other LocalAuthentication method, not just hasHardwareAsync)

from 
```
    LocalAuthentication.hasHardwareAsync()
      .then((value) => {
        console.log('hasHardwareAsync', value);
      })
      .catch((reason) => console.log(reason));
```
### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node .  **`<actually im using 8.9.4 and associated npm version but Im managing with nvm so i can still use expo commands>`**
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: 5.0.3 => 5.0.3
      react: 16.9.0 => 16.9.0
      react-native: 0.61.5 => 0.61.5
      react-navigation: 3.12.1 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.13.1

target: bare react native app (ios)

### Steps to Reproduce
In a bare react native app with directory structure like...

```
| mobile 
. | package.json
. | myapp
. . | ios
. . . | podfile
```
1. Follow manual integration steps with unimodules (with `use_unimodules!(modules_paths: ['../../node_modules'])` and bumping min ios version to 10
2. npm install expo-local-authentication

### Expected Behavior

Calls to `LocalAuthentication.hasHardwareAsync` do not throws `TypeError: Cannot read property 'hasHardwareAsync' of undefined`

### Actual Behavior

Calls to `LocalAuthentication.hasHardwareAsync` throw errors

Here's the output of some logs:

`console.log(LocalAuthentication);` is a real object with keys and values
```
AuthenticationType: Object
1: "FINGERPRINT"
2: "FACIAL_RECOGNITION"
FINGERPRINT: 1
FACIAL_RECOGNITION: 2
__proto__: Object
hasHardwareAsync: ƒ hasHardwareAsync()
supportedAuthenticationTypesAsync: ƒ supportedAuthenticationTypesAsync()
isEnrolledAsync: ƒ isEnrolledAsync()
authenticateAsync: ƒ authenticateAsync()
cancelAuthenticate: ƒ cancelAuthenticate()
__esModule: true
```

`console.log(LocalAuthentication.hasHardwareAsync());`  is a promise with the error described above
```
Promise {_40: 0, _65: 0, _55: null, _72: null}
_40: 0
_65: 2
_55: TypeError: Cannot read property 'hasHardwareAsync' of undefined at hasHardwareAsync$ (http://10.200.18.35:8081/index.bundle?platform=ios:316723:50) at tryCatch (http://10.200.18.35:8081/index.bundle?platform=ios:32636:19) at Generator.invoke [as _invoke] (http://10.200.18.35:8081/index.bundle?platform=ios:32811:24) at Generator.prototype.<computed> [as next] (http://10.200.18.35:8081/index.bundle?platform=ios:32679:23) at tryCatch (http://10.200.18.35:8081/index.bundle?platform=ios:32636:19) at invoke (http://10.200.18.35:8081/index.bundle?platform=ios:32712:22) at http://10.200.18.35:8081/index.bundle?platform=ios:32742:13 at tryCallTwo (http://10.200.18.35:8081/index.bundle?platform=ios:8897:7) at doResolve (http://10.200.18.35:8081/index.bundle?platform=ios:9061:15) at new Promise (http://10.200.18.35:8081/index.bundle?platform=ios:8920:5)
_72: null
_51: 7
__proto__: Object
```

And resolving LocalAuthentication.hasHardwareAsync() results in the same error
```
    LocalAuthentication.hasHardwareAsync()
      .then((value) => {
        console.log('hasHardwareAsync', value);
      })
      .catch((reason) => console.log(reason));
```
```
TypeError: Cannot read property 'hasHardwareAsync' of undefined
    at hasHardwareAsync$ (**LocalAuthentication.js:8**)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
```

Inspecting **LocalAuthentication.js:8**
```
8    if (!ExpoLocalAuthentication.hasHardwareAsync) {
9        throw new UnavailabilityError('expo-local-authentication', 'hasHardwareAsync');
10    }
```

Inspecting ExpoLocalAuthentication
```
1 import { NativeModulesProxy } from '@unimodules/core';
2
3 export default NativeModulesProxy.ExpoLocalAuthentication;
```

### Reproducible Demo

TODO

**Comment by etaiklein** [comment]
Ah just saw the log in xcode `2020-02-14 16:54:24.101 [warn][tid:com.facebook.react.JavaScript] The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly`

Seems like this is a unimodules issue, so I'll move things there

**Comment by Phontinent** [comment]
use this way
`handleAuthentication = async () => {
    const type = await LocalAuthentication.supportedAuthenticationTypesAsync();
    console.log(type);
  };`

**Comment by abhinav-official** [comment]
use this way
`handleAuthentication = async () => {
    const type = await LocalAuthentication.supportedAuthenticationTypesAsync();
    console.log(type);
  };`

**Comment by iamrekhaverma** [comment]
> Ah just saw the log in xcode `2020-02-14 16:54:24.101 [warn][tid:com.facebook.react.JavaScript] The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly`
> 
> Seems like this is a unimodules issue, so I'll move things there

@etaiklein Were you able to solve this issue?

**Comment by etaiklein** [comment]
> > Ah just saw the log in xcode `2020-02-14 16:54:24.101 [warn][tid:com.facebook.react.JavaScript] The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly`
> > Seems like this is a unimodules issue, so I'll move things there
> 
> @etaiklein Were you able to solve this issue?

Yes, it was an issue with unimodules setup. Although I dont recall what exactly.

**Comment by shaksi** [comment]
> > Ah just saw the log in xcode `2020-02-14 16:54:24.101 [warn][tid:com.facebook.react.JavaScript] The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly`
> > Seems like this is a unimodules issue, so I'll move things there
> 
> @etaiklein Were you able to solve this issue?

i found double checking the pod installation of EXLocalAuthentication (9.3.0) actually takes place by running 'pod install' after finishing the unimodule setup solved my problem.

**Comment by Lisba** [comment]
> > > Ah just saw the log in xcode `2020-02-14 16:54:24.101 [warn][tid:com.facebook.react.JavaScript] The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly`
> > > Seems like this is a unimodules issue, so I'll move things there
> > 
> > 
> > @etaiklein Were you able to solve this issue?
> 
> i found double checking the pod installation of EXLocalAuthentication (9.3.0) actually takes place by running 'pod install' after finishing the unimodule setup solved my problem.

Yes, after the whole installation process I ran **npx pod-install**, then rebuilt the app and it worked.

**Comment by dl-husky73** [comment]
Any updates?  I am seeing same issue.

**Comment by mgwedd** [comment]
Seeing this issue after a fresh unimodule install on a bare RN project. I'll update this post as I learn more about what's going on.

**Comment by brentvatne** [comment]
@mgwedd - can you post a reproducible example?

**Comment by Harshitha91** [comment]
I'm also facing this issue. Any Updates?
expo-local-authentication: 11.0.2
react-native-unimodules: 0.13.3
react-native: 0.63.4

**Comment by brentvatne** [comment]
@Harshitha91  - can you post a reproducible example?

**Comment by Grumbash** [comment]
I had a similar issue when I was trying to use `expo-local-authentication` with bare react-native set up. I have followed all the steps from docs for [installation instructions of unimodules](https://docs.expo.dev/bare/installing-unimodules/). In the end, my issue has been solved by the rebuilding of the app (`react-native run-ios`)

**Comment by daniejoh** [comment]
I ran into the same issue. Was solved by the following steps after installing: 

1. Run yarn (or npm install)
2. Run `pod install`
2. Clean build folder in xcode
2. Running `watchman watch-del-all`
3. Running `yarn start --reset-cache`
4. Re-build app

After these steps, it worked for me.
