### ISSUE TITLE
react-native-firebase v6, dynamicLinks module, getInitialLink() function is not working

### ISSUE THREAD

**Issue by vijayst** [expo/expo#7057]
### Environment
Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild

### Steps to Reproduce
I am using react-native-firebase dynamicLinks module. getInitialLink() is not working whereas onLink() is working. getInitialLink() is triggered when the app opens as a result of firebase dynamic link. onLink() is triggered when the app is already active. Linking module from react-native is able to get the initial link using the getInitialURL() method. 

```
// this is not working in our app
    firebase
      .dynamicLinks()
      .getInitialLink()
      .then(link => {
        if (link) {
          if (link.url.includes('/s/')) {
            this.handleSignupURL(link.url)
          }
        }
      })

    // this works fine, Make the above work
    Linking.getInitialURL().then(url => {
      if (url) {
        const durl = decodeURIComponent(url)
        if (durl.includes('/s/')) {
          const inviteCode = durl.substring(durl.indexOf('/s/') + 3)
          store.dispatch(processInvite(inviteCode, true))
        }
      }
    })

    // this works fine
    firebase.dynamicLinks().onLink(({ url }) => {
      if (url && url.includes('/s/')) {
        this.handleSignupURL(url)
      }
    })
```

### Expected Behavior
getInitialLink() of react-native-firebase dynamicLinks module should get the relevant link.

### Actual Behavior
getInitialLink() of react-native-firebase dynamicLinks module gives null whereas Linking module of react-native gives the URL shortened raw dynamic link.

### Reproducible Demo
I don't have a reproducible demo as this requires a detached Expo SDK

**Comment by cruzach** [comment]
hey @vijayst , is this only an issue in Expokit projects? Implementing the same code in a bare RN project works without an issue?

**Comment by vijayst** [comment]
@cruzach Yes, in a plain react-native project, it works fine.

**Comment by cruzach** [comment]
I'm guessing that method that doesn't work is relying on some native code that isn't linked. In the managed workflow, you can't add custom native code, so using module that rely on it is not recommended. We're working on [bringing in some firebase](https://github.com/expo/expo/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+firebase), so keep an eye out for that in upcoming releases, but until then if you need to use the native firebase libraries, the bare workflow is your best bet
