### ISSUE TITLE
Can not properly handle push notification errors

### ISSUE THREAD

**Issue by Fi1osof** [expo/expo#7058]
## 🐛 Bug Report
The Receipt object does not contain a token, which does not allow to determine which device corresponds to the error.

Discussion: https://forums.expo.io/t/how-to-properly-handle-push-notification-errors/31424

**Comment by ide** [comment]
You are responsible for tracking this information when you send the notifications: your notification payload contains a device token -> the nth returned push ticket corresponds to the nth notification -> you use the push ticket to look up the receipt.

**Comment by Fi1osof** [comment]
@ide Not, it does not contains token. For example:
```
        const ticketChunk = await expo.sendPushNotificationsAsync(chunk);
        console.log('sendPushNotifications ticketChunk', ticketChunk);
```
```
sendPushNotifications ticketChunk [ { id: 'f7e49485-511f-41ea-bbaf-xxxxxxxxxxx', status: 'ok' } ]
```
There not exists device id or token.
I cannot be sure that the order of the elements in the response corresponds to the order in the chunk.

**Comment by ide** [comment]
None of the responses contain a token, but the nth push ticket in the first response corresponds to the nth push message in your first request. Since each push message contains a token, you can assemble the pieces together to link the eventual push receipt back to the push token.
