### ISSUE TITLE
Exception when calling `isEnrolledAsync`

### ISSUE THREAD

**Issue by EltonCarreiro** [expo/expo#7067]
### Environment

```
Expo CLI 3.11.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.0 - /usr/local/opt/node@8/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @sentry/react-native: 1.0.9 => 1.0.9 
      @storybook/react-native: 4.1.18 => 4.1.18 
      @types/react: ^16.8.4 => 16.8.14 
      @types/react-native: 0.57.45 => 0.57.45 
      react: 16.9.0 => 16.9.0 
      react-native: 0.61.5 => 0.61.5 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.2
```

Targeting both iOS and Android bare apps. Installed only `react-native-unimodules` and `expo-local-authentication`.

### Expected Behavior

When we call `isEnrolledAsync` we should receive either `true` or `false`.

### Actual Behavior

Today, when calling `isEnrolledAsync` we are receiving the following message:

`Encountered an exception while calling native method: Exception occurred while executing exported method isEnrolledAsync on module ExpoLocalAuthentication: null`

But it only happens on certain real devices like `Samsung S10e` (`SM-G970F`), `Samsung SM J500M`. Also, it happened with some Xiaomi devices like `Xiaomi Redmi Note 7 Pro`, but worked on `Xiaomi Mi A1`.

We are using `redux-saga` on our codebase so for those who are not familiar, `effects.call` basically asks the framework to call the method.

Here is the code snippet that is throwing the error:

```typescript
import { hasHardwareAsync, isEnrolledAsync } from 'expo-local-authentication';
// other imports here...

export function* checkLocalAuthenticationSupport() {
  try {
    const hasLocalAuthenticationHardware: ReturnTypeResolved<ReturnType<typeof hasHardwareAsync>> = yield effects.call(hasHardwareAsync);
    // Line below throws the error
    const hasLocalAuthenticationRegistered: ReturnTypeResolved<ReturnType<typeof isEnrolledAsync>> = yield effects.call(isEnrolledAsync);

    yield effects.put(
      state.auth.actions.setIsLocalAuthenticationSupported(hasLocalAuthenticationHardware && hasLocalAuthenticationRegistered)
    );
  } catch (error) {
  // We log the error on sentry here
  }
}

```

**Comment by jiteshwadia** [comment]
@EltonCarreiro, I am getting same error on Samsung Galaxy J2 Prime (API 23).
