### ISSUE TITLE
Pin button disappeared in expo.io Android client

### ISSUE THREAD

**Issue by kahless** [expo/expo#707]
There used to be a button in notification area to pin the currently running application on the home screen. Here is a picture from Google with this button: https://docs.expo.io/static/2bbe2eb78d5256a2a6f26e3926d28f9a-06442.png (You can see it on the blue background in the left half of the picture)

But now this button disappeared. I created a fresh new project with create-react-native-app and I can't see this button. Did this feature moved somewhere? Or it has been removed? Or did I broke something?

Here is my setup:
```

npm dependencies:
  "expo": "21.0.0"
  "react-native": "0.48.4"
  "react": "16.0.0-alpha.12"

app.json
  "sdkVersion": "21.0.0"

Android-7.1.1, Expo-1.20 (Android application)
```

**Comment by terribleben** [comment]
Hi there, you're correct. We [temporarily removed this](https://github.com/expo/expo/issues/491) until we can make it compatible with newer versions of Android. Please follow that thread for more info.

**Comment by icflorescu** [comment]
I think this issue should remain open until fixed.

**Comment by icflorescu** [comment]
The pin button is still missing in Expo Android 2.0.0, released on Oct 18.

I don't mean to be rude, but I strongly disagree with the idea of abruptly _temporarily removing this feature until it's made compatible with newer versions of Android_. The ability of pinning an app was a feature of paramount importance for many internal projects that were working perfectly without having to go through Google Play just to have homescreen shortcuts on user devices. Right now, the removal of this feature is a totally unexpected show-stopper in a couple of projects I'm prototyping, as I'm having difficulties explaining my customers why they can't simply have their homescreen shortcuts.  

Can you please provide an estimation on when this feature will be back, even for Android <= 7?...

Thank you.

**Comment by itslittlejohn** [comment]
I would also be interested in knowing a rough time table / priority for fixing this. Thanks!

**Comment by KevinAst** [comment]
The Expo Client (ver 23) was updated on my Pixel 11/17/2017 (in support of Expo SDK 23) -AND- **the PIN BUTTON IS BACK!**

Thought you would want to know.

I am under the impression that the "pin" button has NEVER been available on ios (i.e. only supported on android).  **_Can someone please confirm this?_**

**Comment by icflorescu** [comment]
Thanks, @KevinAst. I've noticed the update this morning and the pin button is back indeed (tested on Android 6 & 7). Can't remember exactly about iOS, but I suspect you're right.
