### ISSUE TITLE
Unable to send OTA updates to the App store. Is it due to new sdk ?

### ISSUE THREAD

**Issue by jpca999** [expo/expo#709]
I wonder if this is happening to others to after updating the new Sdk, 

Here is all the info about my app, kindly suggest how do i need to change my settings so that OTA works for my application.

{
“expo”: {
“name”: “The aPP”,
“description”: " App",
“slug”: “app”,
“privacy”: “unlisted”,
“sdkVersion”: “21.0.0”,
“version”: “1.0.8”,
“orientation”: “portrait”,
“primaryColor”: “#cccccc”,
“icon”: “./assets/icons/app.png”,
“loading”: {
“icon”: “./assets/icons/loading.png”,
},
“packagerOpts”: {
“assetExts”: [“ttf”, “mp4”]
},
“ios”: {
“bundleIdentifier”: “com.app.exp”,
“supportsTablet”: true
},
“android”: {
“package”: “org.app.exp”,
}
}
}

Upon hitting the Publish button it updates the code if i open it inside the expo app but it doesnt update in the ios / android store. 

Ive created a post in the forms too but Im still stuck .. 

https://forums.expo.io/t/how-to-implement-ota-over-the-air-updates-for-a-standalone-app-via-expo-i-tried-but-not-working/3282

**Comment by terribleben** [comment]
Thanks for the question - I answered in the forum thread you linked to. This is also covered in the [docs](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html#7-update-your-app).

**Comment by jpca999** [comment]
Yep I appreciate it.
