### ISSUE TITLE
expo-local-authentication FaceID for Android

### ISSUE THREAD

**Issue by khuang-citylift** [expo/expo#7096]
Since expo-local-authentication has been archived and changed to a read-only repository, I am making the feature request here.

It would be great to see FaceID working for Android devices as well.
Currently, expo-local-authentication only supports FaceID for iOS devices.

**Comment by cruzach** [comment]
as it says in the readme of that archived repo, the new package can be found [here](https://github.com/expo/expo/tree/master/packages/expo-local-authentication). 
Also, I believe the functionality you're looking for was added in this pr- https://github.com/expo/expo/pull/6846
