### ISSUE TITLE
[expo-app-auth] ExpoAppAuth.Get Auth: Network error

### ISSUE THREAD

**Issue by leosuncin** [expo/expo#7099]
### Environment

<pre>
EXPO_DEBUG=true expo diagnostics
Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at /home/jsuncin/.local/lib/node_modules/expo-cli/node_modules/envinfo/dist/envinfo.js:1:97131
    at async Promise.all (index 0)
    at action (/expo-cli@3.13.1/src/commands/diagnostics.js:5:14)
    at Command.<anonymous> (/expo-cli@3.13.1/src/exp.ts:81:7)
</pre>

expo: 36.0.2
react-native: 36.0.0
expo-app-auth: 8.0.0
expo-cli: 3.13.1

Target device: Android 7.0
Expo Client: 2.14.0
Operative System: Manjaro Linux 19.0.0
Node.js: 13.7.0
### Steps to Reproduce

I followed the steps from here https://docs.expo.io/versions/latest/sdk/app-auth/

### Expected Behavior

Authenticate using OAuth with spotify

### Actual Behavior

```ts
async function handleSignIn() {
    try {
      const authState = await AppAuth.authAsync({
        issuer: 'https://accounts.spotify.com/authorize',
        scopes: [
          'user-read-playback-state',
          'user-read-email',
          'playlist-read-collaborative',
          'user-modify-playback-state',
          'user-read-private',
          'playlist-modify-public',
          'user-top-read',
          'user-read-currently-playing',
          'playlist-read-private',
          'user-follow-read',
          'user-read-recently-played',
          'playlist-modify-private',
          'user-library-read',
        ],
        clientId: process.env.SPOTIFY_CLIENT_ID,
        clientSecret: process.env.SPOTIFY_SECRET,
        redirectUrl: process.env.REDIRECT_URL,
      });
      console.info(authState);
    } catch (error) {
      console.error(error);
    }
  }
```

<details>
<summary>Error stacktrace</summary>
<pre>
ExpoAppAuth.Get Auth: Network error
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:15:52 in moduleName.methodInfo.name
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:10:62 in moduleName.methodInfo.name
- node_modules/expo-app-auth/build/AppAuth.js:12:5 in assertValidClientId
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
* http://192.168.1.2:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:131477:38 in _executeAsync
- node_modules/expo-app-auth/build/AppAuth.js:28:17 in _executeAsync
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
- node_modules/expo-app-auth/build/AppAuth.js:22:1 in <global>
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
- node_modules/react-native/Libraries/Components/Touchable/TouchableOpacity.js:264:45 in createReactClass$argument_0.touchableHandlePress
* [native code]:null in touchableHandlePress
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:880:34 in TouchableMixin._performSideEffectsForTransition
* [native code]:null in _performSideEffectsForTransition
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:779:44 in TouchableMixin._receiveSignal
* [native code]:null in _receiveSignal
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:490:24 in TouchableMixin.touchableHandleResponderRelease
* [native code]:null in touchableHandleResponderRelease
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:555:30 in invokeGuardedCallbackAndCatchFirstError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:722:42 in executeDispatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:744:20 in executeDispatchesInOrder
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:907:29 in executeDispatchesAndRelease
* [native code]:null in forEach
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:887:16 in forEachAccumulated
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:932:21 in runEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:1096:19 in runExtractedPluginEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2796:6 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18791:14 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2709:30 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2794:17 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2870:28 in receiveTouches
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
</pre>
</details>

### Reproducible Demo

https://snack.expo.io/@suncin/ae025e

**Comment by collink** [comment]
Same issue, same versions of everything, but on macOS Mojave (10.14.6).

**Comment by collink** [comment]
Update on my +1:

My issue turned out to be that Android requires a change to the manifest to trust user-added certs. When I point my configuration to my org's prod server, which has a cert signed by GoDaddy, it works fine. But when I use our dev server which uses a self-signed cert (even though I've added it to the device), it fails immediately.  I don't think this is likely to be related to @leosuncin's issue.

I don't remember where, or how, but I've seen more of a stack trace (I believe it was from a native Android dev who was having a VERY similar issue). It also started with the whole "Network error" thing, but then went on to give more info about SSL issues and whatnot. It would be very helpful, I think, for us to have more of a stack trace in these situations. I'm not sure if that's an issue with AppAuth-Android not surfacing enough info in the error thrown, or ExpoAppAuth not capturing the stack trace, though.

**Comment by leosuncin** [comment]
It was a configuration error. The correct one is:

```javascript
async function handleSignIn() {
  try {
    const authState = await AppAuth.authAsync({
      issuer: 'https://accounts.spotify.com',
      scopes: [
        'user-read-playback-state',
        'user-read-email',
        'playlist-read-collaborative',
        'user-modify-playback-state',
        'user-read-private',
        'playlist-modify-public',
        'user-top-read',
        'user-read-currently-playing',
        'playlist-read-private',
        'user-follow-read',
        'user-read-recently-played',
        'playlist-modify-private',
        'user-library-read'
      ],
      clientId: process.env.SPOTIFY_CLIENT_ID,
      clientSecret: process.env.SPOTIFY_SECRET,
      // host.exp.exponent:/oauthredirect
      redirectUrl: AppAuth.getDefaultOAuthRedirect(),
      serviceConfiguration: {
        authorizationEndpoint: 'https://accounts.spotify.com/authorize',
        tokenEndpoint: 'https://accounts.spotify.com/api/token'
      }
    });
    console.info(authState);
  } catch (error) {
    console.error(error);
  }
}
```
