### ISSUE TITLE
takePictureAsync() only returning a uri and not an object containing the height, base64, etc

### ISSUE THREAD

**Issue by ShayanJavadi** [expo/expo#710]
What my take picture function is doing
`  

      let result = await this.camera.takePictureAsync({ base64: true });
      console.log(result); // returns only a uri
      console.log(result.base64); // undefined
`

[The docs](https://docs.expo.io/versions/latest/sdk/camera.html#takepictureasync) clearly say that the promise resolves to an object, but I'm only getting a uri in my case. Any help is appreciated. Please let me know if I need to provide any additional data.Thanks!

**Comment by terribleben** [comment]
Hello, thanks for the report. What sdk version is your project? This feature was added recently.

**Comment by ShayanJavadi** [comment]
here's my package.json.  it should be the latest one. I'm meeting with my team tonight to discuss whether we should stick with expo or not so if you could help me with this sooner than later that'd be great

```
"dependencies": {
    "@expo/samples": "^2.0.2",
    "base-64": "^0.1.0",
    "expo": "^20.0.0",
    "lodash": "^4.17.4",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-apollo": "^1.4.15",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-native-action-button": "^2.8.0",
    "react-native-keyboard-aware-scroll-view": "^0.3.0",
    "react-native-masked-text": "^1.6.2",
    "react-native-material-bottom-navigation": "^0.5.1",
    "react-native-material-dropdown": "^0.4.1",
    "react-native-material-tabs": "^3.0.3",
    "react-native-material-textfield": "^0.10.0",
    "react-native-material-ui": "^1.12.0",
    "react-native-modal": "^4.0.0",
    "react-native-swipeable": "^0.6.0",
    "react-native-vector-icons": "^4.4.0",
    "react-navigation": "^1.0.0-beta.12",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^7.0.4",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-preset-es2017": "^6.24.1",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-loader": "^1.8.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.0.1",
    "eslint-plugin-react": "^7.1.0",
    "exp": "^44.0.0",
    "jest-expo": "^20.0.0"
  },
```

**Comment by terribleben** [comment]
Looks like you're using SDK 20.0.0, but the `base64` feature was added in SDK 21.

**Comment by ShayanJavadi** [comment]
@terribleben Yup you are absolutely correct. Spent a good 5 hours trying to figure out why it wasn't working haha. now I'm having a new issue after updating. it would be great if you could help me with it 

https://github.com/expo/expo/issues/713
