### ISSUE TITLE
FacebookAds does not show on Android but show on Ios

### ISSUE THREAD

**Issue by littleboy1407** [expo/expo#7112]
I have the same error on issues [#5028](https://github.com/expo/expo/issues/5028) I wonder anyone have fix this yet ??, I check expo-ads-facebook latest version is 8.0.0 but Audience Network SDK still 5.1.1 version, is facebook ads not support for android or i need to install something else ? pls help me with this case, tks

**Comment by cruzach** [comment]
Have you tried using SDK 36? The facebook sdk was updated [here](https://github.com/expo/expo/commit/5c9913eca88eef7beefa7d1a43cb5a38b37327b9)

Closing this as a duplicate

**Comment by le-van-tuan** [comment]
> Have you tried using SDK 36? The facebook sdk was updated [here](https://github.com/expo/expo/commit/5c9913eca88eef7beefa7d1a43cb5a38b37327b9)
> 
> Closing this as a duplicate

Hi Cruzach,
I have tried to using SDK36 and also see the updated commit from the Expo team but I don't know how to import these changes to local development. Could you show me how to update to latest FBSDK version from local?
Thank you so much!
