### ISSUE TITLE
AppAuth semantic issue breaking build (Xcode 9)

### ISSUE THREAD

**Issue by chrismllr** [expo/expo#712]
Building an ExpoKit ejected project in Xcode 9 (High Sierra) Throws a semantic error within `AppAuth`

This is preventing the app from building. Screenshot below.

I found this issue thread within AppAuth which was resolved 17 days ago, might just need a version bump somewhere:
https://github.com/openid/AppAuth-iOS/issues/120

ExpoKit pod tag: `ios/1.20.5`

![screen shot 2017-10-02 at 3 01 09 pm](https://user-images.githubusercontent.com/9942917/31097050-9eb5941c-a783-11e7-83f5-f92e39127416.png)

**Comment by terribleben** [comment]
It says "Available on iOS 9.0 or newer", suggesting your Xcode project is targeting something older than iOS 9. Can you double check what your target platform is?

**Comment by chrismllr** [comment]
Sure thing - I created the project today in CRNA, and ejected via ExpoKit. Is there a default target platform? Apologies, having trouble locating it in Xcode...

**Comment by terribleben** [comment]
I just tried a fresh `exp detach` and got a project targeting iOS 10. My build also works without that error. I wonder if CRNA is doing something different. It shows up as "Deployment Target" here:

![image](https://user-images.githubusercontent.com/1316332/31097885-bb818b0e-a775-11e7-9fba-0332f79de7a0.png)

**Comment by chrismllr** [comment]
Ok - Yes i've got the same, defaulting to 10.0. That's possible, let me try using exp detach outside of CRNA.

**Comment by chrismllr** [comment]
Getting the same starting with a fresh expo app built through XDE...
Deployment target is same as above, 10.0, but I am also getting this "Update Project Settings" dialog, which seems to be stuck at 8.0:

![screen shot 2017-10-02 at 4 05 56 pm](https://user-images.githubusercontent.com/9942917/31099480-c14b6d64-a78b-11e7-8d98-94756c4d72fe.png)

I have `platform :ios, '9.0'` at the top of `Podfile`, so dont know why those are reading 8.0.

**Comment by terribleben** [comment]
It looks like the `Pods` project is targeting 8.0 (after you run `pod install`), which should be [harmless and non-blocking](https://github.com/CocoaPods/CocoaPods/issues/6863), albeit annoying. I get the same warnings shown in your last screenshot but it doesn't prevent the app from building.

**Comment by chrismllr** [comment]
Modifying the actual `Pods/Pods.pbxproj` file and changing all instances of `8.0` to `9.0` was the only way I could resolve this... going to look into this some more, but it is likely an issue in my local Xcode environment

**Comment by arrygoo** [comment]
This is still happening for me on creating a new expo project (expo 21) and detaching it.

**Comment by chitrangsinghvi** [comment]
Hii @arrygoo, were you able to solve the problem? I am also facing similar problem.

**Comment by maliha-wiva** [comment]
Hi @arrygoo, i am also facing the same issue. Any body has solved this issue?

**Comment by arrygoo** [comment]
I think this needs to be solved by Expo, but in the meantime you can do set the deployment target of AppAuth to be ios 9.

**Comment by terribleben** [comment]
We think we can probably fix it in next ExpoKit release by forcing CocoaPods to update the target SDK version in a postinstall. Still not sure why this issue blocks the build for some people and not for others.

Reopening just to track this until I land a fix.

**Comment by terribleben** [comment]
If you have an existing detached project, you'll have to fix this manually by adding this to your Podfile's postinstall loop:

```
    if target.pod_name == 'AppAuth'
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
```

This is currently the [recommended solution](https://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod) by cocoapods, they won't configure it automatically.

I'll make it so fresh ExpoKit projects already have this hook in their Podfile when it's created.

**Comment by terribleben** [comment]
Fix for future detached projects is landed [here](https://github.com/expo/xdl/commit/8a1d100342c12f3b8fc693693d3565b6c8761d0c) and will go out with our next exp release.

**Comment by maliha-wiva** [comment]
i want to maintain the deployment target for my app is 8 and higher. so my application getting crash in the iOS versions less than 9 when i am setting the deployment target 9 for the AppAuth. i need the solution for my this problem

**Comment by terribleben** [comment]
@maliha-wiva Expo supports iOS [9 and higher](https://docs.expo.io/versions/latest/introduction/faq.html#what-version-of-android-and-ios-are-supported-by-expo-apps) and Android 4.4+.
