### ISSUE TITLE
How to get the blob of a local file without using fetch? Fetch crashes with large files

### ISSUE THREAD

**Issue by raRaRa** [expo/expo#7122]
For context, I'm trying to upload a blob of a video file to Google Drive and Google Photos. It works fine for most files, but if the file is large, e.g. > 300 MB, then `fetch(localFileUri)` will crash, both in the Expo client and also in the standalone app.

I'm using `ImagePicker` to find the video on my Galaxy S10e, and then I use `fetch` to load it from the `result.uri` which was returned from the ImagePicker
```
let result = await ImagePicker.launchImageLibraryAsync({
   mediaTypes: ImagePicker.MediaTypeOptions.All,
   allowsEditing: false,
   quality: 1,
});

if (!result.cancelled) {
    const imageData = await fetch(result.uri) // <-- This line crashes with the error
    const blob = await imageData.blob();
    // Start upload, etc.
}
```

My guess is that `fetch` is trying to load the entire video to memory, which causes the crash, or something else is going on.

Is there an alternative to get the blob of a file, in order to upload it to Google? If I add the video uri to a FormData, then I believe `fetch` will try to convert it to base64, which isn't ideal.

I've also tried writing my own `XMLHttpRequest` - which also crashes.

Here's the crash stack:
```
Stack trace:
  node_modules\whatwg-fetch\dist\fetch.umd.js:473:29 in xhr.onerror
  node_modules\event-target-shim\dist\event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
  node_modules\react-native\Libraries\Network\XMLHttpRequest.js:574:29 in setReadyState
  node_modules\react-native\Libraries\Network\XMLHttpRequest.js:388:25 in __didCompleteResponse
  node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:190:12 in emit
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47 in __callFunction
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26 in __guard$argument_0
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0
  [native code]:null in callFunctionReturnFlushedQueue
  ...
```

  Expo CLI 3.11.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203

App target is iOS and Android as standalone app.

**Comment by cruzach** [comment]
Does this crash only happen in Expo projects, or does it happen in bare react native projects, as well? If it happens in both, then this is probably not a bug specific to the Expo SDK (we try to keep Github reserved for bug reports, and use our [forums](https://forums.expo.io/) for general questions regarding Expo)

**Comment by raRaRa** [comment]
Hi @cruzach 

Unsure if this happens in native projects, what's a good way to try it out? My guess is that it crashes because it runs out of memory. Currently there doesn't seem to be any method to upload large files with Expo.

I've tried using the `FileSystem` API, but it also crashes when I try to read the file, likely because it's trying to read the whole video file as UTF8 or Base64 string.

Would you suggest an alternative method to get access to a blob of a large video file (~500MB)?

**Comment by cruzach** [comment]
Best way to try it on a bare react native project is by running `expo init -t bare-minimum` to initialize a blank project, and go from there 😄

**Comment by raRaRa** [comment]
Thanks @cruzach - I'll give it a try.

On another note, I created a feature request for better blob support here: https://expo.canny.io/feature-requests/p/better-blob-support

But basically:

> What I want to see is better blob support, e.g. the ability to get the first X bytes of a blob for resumable uploads. I noticed that the FileSystem API can read files both in string as Base64 and UTF8, but what if we could read it as a blob - and also utilize the start and length parameters? I think that would solve the problem for many people who have asked for blob support with the Camera.takePictureAsync, etc.

**Comment by vpontis** [comment]
I'm also getting this issue. I'll investigate and see if I can repro on an expo-bare project.

**Comment by raRaRa** [comment]
> I'm also getting this issue. I'll investigate and see if I can repro on an expo-bare project.

How did that go?

**Comment by calebmadrigal** [comment]
I'm also getting this error. Here's my code:

`export const setProfilePic = async (photoObj) => {
    const token = await getAccessToken();
    var data = new FormData();
    const filename = photoObj.uri.replace(/^.*[\\\/]/, '');
    const photoURI = Platform.OS === "android" ? photoObj.uri : photoObj.uri.replace("file://", "");

    console.log('setProfilePic(): filename = ' + filename + ', URI = ' + photoURI);
    data.append("file", {
        name: filename,
        type: photoObj.type,
        uri: photoURI
      });

    console.log('Doing profile pic upload...');
    return fetch(URL_BASE + '/v1/user/profile-pic', {
        method: 'POST',
        body: data,
        headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'Authorization': 'Bearer ' + token
        }
    });
}`

And here's the output of some of those debug log statements:

`setProfilePic(): filename = 6a82a2de-d99d-4be5-93f1-65fbc01084ff.jpg, URI = file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540servitodo%252Fservitodo/ImagePicker/6a82a2de-d99d-4be5-93f1-65fbc01084ff.jpg
Doing profile pic upload...
photoObj:
Object {
  "cancelled": false,
  "height": 1458,
  "type": "image",
  "uri": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540servitodo%252Fservitodo/ImagePicker/de7ac18a-7bc9-481b-b577-b6f6de4ac752.jpg",
  "width": 1944,
}
setProfilePic(): filename = de7ac18a-7bc9-481b-b577-b6f6de4ac752.jpg, URI = file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540servitodo%252Fservitodo/ImagePicker/de7ac18a-7bc9-481b-b577-b6f6de4ac752.jpg
Doing profile pic upload...
UNKNOWN ERROR IN setProfilePic:

Network request failed
- node_modules/whatwg-fetch/dist/fetch.umd.js:473:29 in xhr.onerror
- node_modules/event-target-shim/dist/event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:574:29 in setReadyState
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue`

**Comment by calebmadrigal** [comment]
Update:

I was able to fix this problem by making 2 changes:
* I needed to change `'Content-Type': 'application/json'` -> `'Content-Type': 'multipart/form-data'`
* The `photoObj.type` was `image`, and needed to be changed to something like `image/jpg` for the upload to work. This part may be a bug in the expo photo picker - it probably should return a type like `image/jpg` instead of just `image`.

**Comment by raRaRa** [comment]
@calebmadrigal Appreciate your input, but this issue is related to using fetch to get a large local file, e.g. > 300 MB. Not for uploading, but to get access to the file blob. Although it would be interesting to see if you manage to upload a file that is over 300-500MB?

**Comment by jackblackCH** [comment]
Not solved yet.

**Comment by mikealche** [comment]
Still having this issue. In my case it fails on Android only on production on videos larger that 50MB

**Comment by J-Magic** [comment]
Did anyone ever fix this issue?

**Comment by clevadani** [comment]
Any update on this?

**Comment by shawarmaz** [comment]
fails with small `.m4a` files too ?
