### ISSUE TITLE
[expo-av] Compile error with latest react-native-web

### ISSUE THREAD

**Issue by maggo** [expo/expo#7125]
## 🐛 Bug Report

The Video component from `expo-av` doesn't compile because `ViewPropTypes` is not exported from RNW anymore. 

See https://github.com/necolas/react-native-web/issues/1537

### Steps to Reproduce

1. Install latest `react-native-web@0.12.1`
2. Install latest `expo-av@8.0.0`
3. Import `Video` component in code

### Error

```
./node_modules/expo-av/build/Video.js
Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes' in '…/node_modules/expo-av/build'
```
### Reproducible Demo

Sorry couldn't figure out how to force snack to upgrade react-native-web but here's a version with 0.11.7 which works https://snack.expo.io/@maggo/expo-av-web-issue

**Comment by mauriciord** [comment]
Maybe this can help, @maggo 
https://github.com/expo/expo/pull/7127

**Comment by WazzaJB** [comment]
This seems to be because `ViewPropTypes` is no longer exported by 'react-native-web' as per release: [https://github.com/necolas/react-native-web/releases/tag/0.12.0](https://github.com/necolas/react-native-web/releases/tag/0.12.0)

Not sure what the solution is, however I have just removed ViewPropTypes from `node_modules/expo-av/build/Video.js` for now.

**Comment by cruzach** [comment]
Thanks for reporting! Would be happy to see a PR fixing this, it seems like you had opened one but then closed it?

**Comment by OlekRia** [comment]
Guys, please PR it !

**Comment by maggo** [comment]
I just tried upgrading to `react-native-web@0.12.2` in the `bare-expo` app and now another dependency breaks because of the missing `ActionSheetIOS` export.

```
 web  Failed to compile.
…/expo/node_modules/react-navigation-header-buttons/src/OverflowButton.js
Module not found: Can't resolve 'react-native-web/dist/exports/ActionSheetIOS' in '…/expo/node_modules/react-navigation-header-buttons/src'
```

It seems there's a discrepancy here: `react-native` is in the process of removing components (see https://github.com/facebook/react-native/issues/23313) while `react-native-web` already has those removed (see https://github.com/necolas/react-native-web/issues/1352)

I don't think we can safely update to 0.12.x while this is the case and might be better off to update the docs and tell people that Expo web is only compatible with 0.11. right now. What do you think @cruzach?

**Comment by marnusw** [comment]
`expo-linear-gradient` which imports `ColorPropType` and `ViewPropTypes` has the same problem, and there are likely more broken modules still. What should be the strategy to follow in a proposed PR to remove these imports? Should the original definitions be moved into to the Expo project so they can be maintained, or just dumb down the prop type definitions in Expo so they don't use these definitions at all? e.g. stop spreading `ViewPropTypes`, change to `PropTypes.object` etc. as relevant.

**Comment by cruzach** [comment]
I think @maggo's point to say to use 0.11 is best, but @EvanBacon is more familiar with Expo and web so I'd want his input as well

**Comment by RonAmihai** [comment]
This issue also applies for the expo-camera module... 

Is there any temporary workaround we can take in order to use those specific modules with RNW 0.12.x? 

(Other than removing all the "ViewPropTypes" definitions from the local modules packages, `node_modules/expo-camera/build/Camera.js` in my case - which works well for me)

**Comment by ianmartorell** [comment]
This is especially notable now that Expo SDK 39 is out and it supports RNW 0.13 according to the release notes. I wouldn't say it supports it if some of the packages you install with `expo install` don't compile with that version of RNW. 😕

**Comment by EvanBacon** [comment]
I merged 7 PRs removing prop-types when I was adding support for RNW 13 https://github.com/expo/expo/pulls?q=is%3Apr+Prop-Types+is%3Aclosed+author%3AEvanBacon Please ensure your packages are all using the correct versions. Snack with video component working https://snack.expo.io/@bacon/bfb74c

**Comment by ianmartorell** [comment]
Ah, totally my bad. It was a package which was depending on `expo-linear-gradient` and was resolving to an old version in my `yarn.lock`, even though I installed the latest one separately using `expo install`:

```
expo-linear-gradient@^8.0.0:
  version "8.1.0"
  resolved "https://registry.yarnpkg.com/expo-linear-gradient/-/expo-linear-gradient-8.1.0.tgz#6933765cf1e76ef2928fd8495e779929699ac4c6"
  integrity sha512-AIy2pOXQRcgk2XE5IgAzd1S2jTFLutiDfveNm6m3fPAk00Rw4qFe98qzte1ayNrGYLJvQ2xq/Y7C0BmBP051mg==

expo-linear-gradient@~8.3.0:
  version "8.3.0"
  resolved "https://registry.yarnpkg.com/expo-linear-gradient/-/expo-linear-gradient-8.3.0.tgz#4a976ac0d8d586966187b34cb3a2ac8a701533fa"
  integrity sha512-B7vi0mzWXleKeI2iiFrCC6RiIYxtoK7RWp/Wmaxjlux4Yi6SBDjIoL0tXvfa14C7ZiJjA4wm1/3lcbhiGvQOTg==
```

I removed the old version's block, installed the package again and the lockfile updated to this:
```
expo-linear-gradient@^8.0.0, expo-linear-gradient@~8.3.0:
  version "8.3.0"
  resolved "https://registry.yarnpkg.com/expo-linear-gradient/-/expo-linear-gradient-8.3.0.tgz#4a976ac0d8d586966187b34cb3a2ac8a701533fa"
  integrity sha512-B7vi0mzWXleKeI2iiFrCC6RiIYxtoK7RWp/Wmaxjlux4Yi6SBDjIoL0tXvfa14C7ZiJjA4wm1/3lcbhiGvQOTg==
```

**Comment by 404rakshit** [comment]
Use version `"expo-av": "~13.4.1"` working for me atleast
