### ISSUE TITLE
[AppleAuthentication] How to translate / change AppleAuthenticationButton Text?

### ISSUE THREAD

**Issue by Derewith** [expo/expo#7129]
## 🐛 Bug Report
Hello guys!
I’m here to understand if there is a way to change the label of the
AppleAuthentication.AppleAuthenticationButton .
I need to translate it to Italian but i don’t know how.

Thanks in advance!
### Environment
` Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.13.1`

iOS is the target

### Steps to Reproduce
Using AppleAuthentication.AppleAuthenticationButton

**Comment by OscarYuen** [comment]
Change the Xcode App setting language

**Comment by Derewith** [comment]
@OscarYuen i haven't ejected the project, i'm going to continue using the managed way so i'm unable to open the Xcode App setting language.
Thanks anyway

**Comment by cruzach** [comment]
Unfortunately this is a build-time setting, so the managed workflow doesn't support changing this text for now. Hopefully we will support this soon!

**Comment by Derewith** [comment]
@cruzach if i can help you with something i'm here! Otherwise i'll wait until SDK 37..? Am i right?
Thanks again !

**Comment by cruzach** [comment]
Thanks! Sorry, but this won't be added in SDK 37, unless you choose to move to the bare workflow then (and thus control the Xcode app language yourself)

**Comment by Derewith** [comment]
@cruzach sorry but wouldn't be easier to make the button to have a custom text? I will have a look at Apple's docs by the way..

**Comment by tsapeta** [comment]
@Derewith Unfortunately no, this button is provided by native iOS framework and as far as we can tell there is no other way to change this text yet - the only way we know about is as @cruzach said, by changing app language in Xcode but you can set only one language there.
For now I think this issue should be closed, but we're open to add such functionality once Apple makes it possible (hopefully they will do this soon).

**Comment by cruzach** [comment]
You can add "CFBundleAllowMixedLocalizations": true to your infoPlist property in app.json - see https://docs.expo.io/workflow/configuration/#ios

once you add this you will need to rebuild the standalone app

**Comment by Ozaoujal** [comment]
I’m not sure how Apple handles it internally, but most applications do support multiple languages. In my case, I’m developing an app where users can select their preferred language on the initial screen when they open the app for the first time. while the apple authentication button always displayed in English (the phone language)

Does anybody have a solution?
