### ISSUE TITLE
Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by ShayanJavadi** [expo/expo#713]
Hi, I just updated to sdk 21, and I'm getting the following error: 
<img width="377" alt="screen shot 2017-10-02 at 6 13 03 pm" src="https://user-images.githubusercontent.com/11575429/31103595-66326b50-a79d-11e7-9cdf-b5a9c854f8b3.png">
![screen shot 2017-10-02 at 6 13 09 pm](https://user-images.githubusercontent.com/11575429/31103601-6ad1531a-a79d-11e7-9e13-e4e644b2298c.png)

relevant app/package.json info
    "sdkVersion": "21.0.0",
    "expo": "^21.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "jest-expo": "^21.0.0"

I have no clue where to even begin debugging this issue. Any help is appreciated! let me know if i I need to provide more info

**Comment by terribleben** [comment]
Hi there, this is an annoying issue that happens when you have mismatched JS and native code. Most likely, your project still has cached SDK 20 javascript (from an older version of react native), but the app is running native code for the newest version.

One way to make sure you have the latest JS is to nuke everywhere there could be a cache, e.g. by `rm -rf node_modules && npm i`, and maybe by restarting watchman by running `watchman watch-del-all` (if your machine has it). Then restart your exp project with a clear cache.

**Comment by ShayanJavadi** [comment]
I've tried that a few times now. just tried it again to be sure. It's still not working :(
Any other ideas?

**Comment by ShayanJavadi** [comment]
Thanks a lot for your help by the way

**Comment by terribleben** [comment]
What is shown for `version` when you look at `node_modules/react-native/package.json`? It should be 0.48.something.

If you're using XDE, did you click Restart? If exp, the same thing would be `exp r -c` to make sure there's a clear cache.

**Comment by ShayanJavadi** [comment]
"version": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz"

<img width="983" alt="screen shot 2017-10-02 at 6 27 09 pm" src="https://user-images.githubusercontent.com/11575429/31103914-54bb7cf2-a79f-11e7-9fed-68d053b48a12.png">

yes I've restarded XDE several times

**Comment by terribleben** [comment]
Can you double check the path I wrote in my last comment and show me that file's version? Slightly different thing.

**Comment by ShayanJavadi** [comment]
I think it's the correct one, no?. see the highlighted tab at the top

<img width="720" alt="screen shot 2017-10-02 at 6 30 41 pm" src="https://user-images.githubusercontent.com/11575429/31104007-e7d9433e-a79f-11e7-9340-3d232fa4f999.png">

**Comment by terribleben** [comment]
Can you follow [this guide](https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352)? Sometimes it can be really nasty to get this state cleared out.

**Comment by ShayanJavadi** [comment]
Tried that. still the same error. would it matter if I tried using exp instead of XDE to run the project?

**Comment by ShayanJavadi** [comment]
I got it to work finally. had to switch from npm to yarn. thanks for your help ben!
