### ISSUE TITLE
Expo-gl crashes on ios 13.4

### ISSUE THREAD

**Issue by 0xClpz** [expo/expo#7132]
### Environment

  Expo CLI 3.9.0 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.asdf/installs/nodejs/12.13.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.asdf/installs/nodejs/12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild

App target:
- iOS Standalone
- Expo client

### Steps to Reproduce

Render any component from expo pixi (that uses expo gl) on ios 13.4 (beta)

### Expected Behavior

It works

### Actual Behavior

It crashes

**Comment by fknop** [comment]
This line makes the application crash https://github.com/expo/expo/blob/master/packages/expo-gl/src/GLView.tsx with split of undefined.

**Comment by fknop** [comment]
This line makes the application crash.
https://github.com/expo/expo/blob/304c74f227fa97d4059d18d1fef491af1f0f1396/packages/expo-gl/src/GLView.tsx#L507
The error being split of undefined

**Comment by idudinov** [comment]
the same for `expo-three`, iPhone 8 iOS 13.4 beta 2 (17E5233g), and a bit more context:

```
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.1
```

```
TypeError: glesVersion.split is not a function. (In 'glesVersion.split(/[^\d.]+/g)', 'glesVersion.split' is undefined)
_setNativeRef
    GLView.js:17:16
_computeGroups
    XLoader.js:1039:17
callFunctionReturnFlushedQueue
    [native code]:0
```

**Comment by 0xClpz** [comment]
It works again on the latest iOS beta!!!!! 🎉

**Comment by idudinov** [comment]
hi there! I’m seeing this crash again with the same expo configuration/libraries but on the newer iOS 14.0 (18A5301v)

![D831C697-18B9-4A5E-95CE-E12AAFA99BFE](https://user-images.githubusercontent.com/15375564/86837935-469db200-c0a8-11ea-865d-0ef0e652e743.jpeg)

**Comment by alexanderstrom** [comment]
Also seeing this issue with in GLView.tsx with u.split is not a function.

**Comment by wkozyra95** [comment]
Those issues are not related, new JSC on iOS14 had a breaking change in internal implementation we relied on. More info [here](https://github.com/expo/expo/issues/8971#event-3556814854)

fix is on master https://github.com/expo/expo/pull/9226 and will be available in client with next sdk and for standalone builds a bit earlier

**Comment by wkozyra95** [comment]
The fix was backported to sdk38 and deployed to production.

**Comment by Joshandrews43** [comment]
I am still getting this error on the IOS 14 beta on the IPhone 8. 

Any solutions? 

```
    "expo": "^38.0.10",
    "expo-gl": "8.4.0",
    "expo-gl-cpp": "8.4.0",
```

**Comment by zschiller** [comment]
Same

**Comment by wkozyra95** [comment]
@zschiller You did not provide enough information to identify the problem
I linked to an issue that explains the problem in iOS14 a few comments above and there is info were the fix was applied

- in a bare workflow, you need `8.4.0` expo-gl`
- in managed standalone build it needs to be built after Aug 6 and only for sdk 38 (this fix was in c++, OTA update won't work)
- in the client does not work, it will be fixed for old SDKs with the release of SDK 39
