### ISSUE TITLE
[iOS] Strange behavior with ImagePicker when editing image from camera 

### ISSUE THREAD

**Issue by stay2be** [expo/expo#7134]
### Environment

Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
      npm: 6.13.7 - ~/.nvm/versions/node/v12.16.0/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.1.1 => 4.1.1 
    npmGlobalPackages:
      expo-cli: 3.13.1

App targets: iOS, Android

Tested on iOS: 13.3.1

### Steps to Reproduce

Invoke ImagePicker.launchCameraAsync
```javascript
  const result = await ImagePicker.launchCameraAsync({
    mediaTypes: ImagePicker.MediaTypeOptions.Images,
    allowsEditing: true,
    allowsMultipleSelection: false,
    quality: 1,
    aspect: [1, 1],
  });
```

### Expected Behavior

When taking a picture and getting to the crop interface, the expected behavior is that the image could be moved from to the top and bottom.

### Actual Behavior

The image in the video can't be moved to the top or bottom so some of the sides are cut away.
See this video:

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/13693611/74965728-0a79f580-5416-11ea-8371-bd4a22fe6a8c.gif)

### Reproducible Demo

Use this repo: https://gitlab.com/dk-expo-bugs/expo-imagepicker-bug

**Comment by lukmccall** [comment]
Hi @stay2be. This bug is in the iOS system. We tried to fix it. However, Apple rejects our app when we applied our changes. To more information check [this PR](https://github.com/expo/expo/pull/6442) an also [the original one](https://github.com/expo/expo/pull/5965).

I think we can't do anything with this right now 😞

**Comment by stay2be** [comment]
Hi @lukmccall, that's really sad. I've found some discussion on Stackoverflow: https://stackoverflow.com/questions/12630155/uiimagepicker-allowsediting-stuck-in-center

Seams this bug will never be corrected by Apple, so are there any alternatives? What comes straight out of my mind is the following:

- Ejecting and integrating https://github.com/ivpusic/react-native-image-crop-picker/issues for example
- Disable editing when launching camera (because when selecting Images from camera roll, it work's as expected) and show a self made UI after taking a photo from camera

Are there maybe any other workarounds I'm not aware of without ejecting or rebuilding the whole UI?

**Comment by lukmccall** [comment]
So @stay2be, we have in mind this problem. In future, we will fix it. However, I don't know when. 

If you don't want to eject, you can create a UI by yourself (maybe you could use `expo-image-manipulator` to do it).  

I think it's the only possibility without ejecting :/

**Comment by stay2be** [comment]
@lukmccall Ok, when I have some free time, maybe a will create a module that provides the UI and works with expo and is customizable to some sort of degree. Happy to share it then here. 

Nevertheless, thanks for you feedback.
