### ISSUE TITLE
[expo-av] EXVideoView - Modifications to the layout engine must not be performed from a background thread

### ISSUE THREAD

**Issue by yvbeek** [expo/expo#7137]
## 🐛 Bug Report

We are getting crash reports that are related to the `EXVideoView`. It seems to happen to users running iOS 13.3 and 13.3.1.

**Error**
```
-[EXVideoView _updateNativeResizeMode]
EXVideoView.m, line 552
SIGABRT: Modifications to the layout engine must not be performed from
a background thread after it has been accessed from the main thread.
```

**Backtrace**
![image](https://user-images.githubusercontent.com/966500/74985011-a4d13d80-5404-11ea-8f31-8e94a8b9dbaf.png)

**Packages**
"react-native": "0.61.5"
"expo-av": "8.0.0",

**Comment by cruzach** [comment]
Hi! Can you provide a reproducible demo? The more you make the root cause of this issue clear or easy to find, the more likely it is to be fixed as quickly as possible

**Comment by yvbeek** [comment]
@cruzach Oh that is probably difficult to do. We only see this crash with a small percentage of our iOS users. There is quite a lot logic wrapped around our video component.

Could it be that `setSource:withStatus:resolver:rejecter:` is called from a background queue in this crash? 
https://github.com/expo/expo/blob/ee5af9cb39695818cd0bd860e083c08ad5bd3532/packages/expo-av/ios/EXAV/Video/EXVideoView.m#L266

Steps:
1. Method `setSource:withStatus:resolver:rejecter` is creating a `EXAVPlayerData`
2. The `EXAVPlayerData` has a `withLoadFinishBlock` block
3. That blocks calls `_updateForNewPlayer`
4. That method calls `_updateNativeResizeMode`
5. And then inside that method we find the `setVideoGravity ` calls

Can we guarantee that the `loadFinishBlock` is called on the main queue?
Or should that call to `_updateForNewPlayer` be wrapped in a `dispatch_async` on the main queue?

**Comment by yvbeek** [comment]
I've managed to get this issue on the simulator when I watch a video and then navigate to a different tab on the (react-navigation) tab navigator.

The current queue is the `org.unimodules.ExponentAVQueue (serial)`.
That queue is trying to update the UI by calling `_updateNativeResizeMode`.

@cruzach  I think the solution for this would be to wrap the `withLoadFinishBlock` in a `dispatch_async` on the main queue.

**Comment by cruzach** [comment]
> I've encountered this crash on the simulator when I watch a video and then navigate to a different tab on the (react-navigation) tab navigator.

@yvbeek can you share a minimal repo that exhibits this behavior? I'd suggest doing it in the bare workflow so that you can test the solution you suggested above

**Comment by jphilipstevens** [comment]
@cruzach I see the same thing when I build a feed like structure that has videos. Using https://www.npmjs.com/package/@skele/components for building viewport aware video to start and stop when in view.

I'm not sure @yvbeek can implement the solution since it would mean forming expo and changing ios code.

**Comment by yvbeek** [comment]
@cruzach I'm not sure in which scenario that code is called from a background thread. I won't be able to provide code that reproduces the crash, we can't properly reproduce it with our own app.

I would recommend wrapping that call in a dispatch_async that puts it on the main thread. UI code like that should never be called from a background thread. Currently there is no code preventing that from happening.

For now I'm using a yarn post-install script that patches the library code for us.

**Comment by kharlm** [comment]
> @cruzach I see the same thing when I build a feed like structure that has videos. Using https://www.npmjs.com/package/@skele/components for building viewport aware video to start and stop when in view.
 Where you ever able to find a solution to this I'm facing the same issue

**Comment by yvbeek** [comment]
For people that are having this issue, you can use my fork over at: https://github.com/yvbeek/expo-av

That fork has the following changes:
- Added: Android Live Stream indicator
- Changed: Default to HLS for unknown streams
- Fixed: The background thread UI call issue
- Updated: Android Exo Player to a recent version

When I have the time I’ll split it up in PRs, but work is really busy at the moment.

**Comment by jphilipstevens** [comment]
@kharlm I was not able to test out a fix. We use patch-package with some other components that I want to use for this issue. Unfortunately, work has been too busy for me. I will post when I can.

**Comment by IjzerenHein** [comment]
Hi! We've fixed this issue and released a test-version for you to try out.

You can try it out in a bare project using `yarn install expo-av@8.4.0`.
You can find the changelog here: https://github.com/expo/expo/blob/master/packages/expo-av/CHANGELOG.md

Let us know whether this fixes the problem for you!

**Comment by yvbeek** [comment]
@IjzerenHein Thank you for the update.

It is very hard to reproduce this issue. I'm not sure if the changes would solve this specific issue.

- the `finishBlock` of `EXAVPlayerData` calls `_updateForNewPlayer`
- function `_updateForNewPlayer` calls `_updateNativeResizeMode`
- the code in `_updateNativeResizeMode` should always be run on the main thread

Nothing seems to ensure that `EXAVPlayerData`'s `finishBlock` is called on the main thread. If the code inside `_updateNativeResizeMode` is called on any other thread than the main thread, the app will crash.

**Comment by IjzerenHein** [comment]
@yvbeek Thanks for having a look as well.

Yes that's correct and you're right about `_updateNativeResizeMode`. I should remove that call from `_updateForNewPlayer` entirely as it doesn't do anything anymore. The fixes applied involve ensuring that the ViewControllers and layer are properly destroyed and only created (in the UI thread) after `EXAVPlayerData`'s `finishBlock` has been called. Previously it was possible that calls to `setUseNativeControls` would create the ViewController/Layer while `setSource` was in the process of loading, causing `finishBlock` to update them leading to this error. This should however no longer happen.
