### ISSUE TITLE
splash screen issue

### ISSUE THREAD

**Issue by helios1138** [expo/expo#714]
I'm trying to set up a splash screen for the app and I have two issues:
1. I can't use `loading` and `splash` options in app.json together, setting splash seems to override the loading
2. What I then see (on iOS simulator) is splash screen appearing, then a white screen for a time, then splash screen again and then my app.

my settings are:
```json
"loading": {
  "backgroundColor": "#FF0000"
},
"splash": {
  "backgroundColor": "#FFFF00"
}
```

**Comment by aalices** [comment]
`splash` is actually overriding `loading` as it is an experimental version of it. The docs will be fixed to make all of this clear. The behavior you describe in 2. is also mentioned by some people in #542 and will be fixed in SDK 22.

**Comment by helios1138** [comment]
@aalices I see. Thanks
