### ISSUE TITLE
[Video][iOS] shouldPlay remains true if manually paused (native controls)

### ISSUE THREAD

**Issue by ArtemKolichenkov** [expo/expo#7142]
I am using expo-av in bare RN project (no expo).
Everything works as expected except `shouldPlay` flag on iOS 13.3.1 (tested on real device iPhone 6S and iPhone 5)

RN version = 0.61.5
expo-av version = 8.0.0
I am using `useNativeControls`

When I press pause button on video - `onPlaybackStatusUpdate` reports `shouldPlay` as `true`, no matter how many times I press play/pause button.
On Android it works as expected: you press pause - `shouldPlay` becomes `false`.

I also think there is no way to override native controls "pause" function and I don't really want to create custom controls just because of this. If somebody knows any way to get correct `shouldPlay`  flag on iOS please comment.

**Comment by cruzach** [comment]
Hi @ArtemKolichenkov , could you provide a repro for this? The code is the same for bare and managed projects, so you should be able to reproduce the same bug in a [snack](https://snack.expo.io/)

**Comment by IjzerenHein** [comment]
Hi! I've had a closer look at this and the status field `shouldPlay` is actually supposed to behave in this way on iOS. The `shouldPlay` field represents the prop that is set on the `<Video>` component. It's not supposed to change when Play/Pause is pressed on the native controls. If you want to monitor the playing status then you need to use the `isPlaying` and `isBuffering` status fields instead.

You mention that it does change on Android, however I've been unable to validate this behavior. On Android it should behave the same and `shouldPlay` should be the same value as the prop that is set on the `<Video>` component.

> I also think there is no way to override native controls "pause" function and I don't really want to create custom controls just because of this. If somebody knows any way to get correct shouldPlay flag on iOS please comment.

@ArtemKolichenkov That is correct. Unfortunately customizing of the native controls is limited and not possible in most cases. You can however monitor the `isPlaying` status field or implement your own custom controls if needed.

**Comment by IjzerenHein** [comment]
I'm closing this as the `shouldPlay` is expected to work this way. Feel free to reopen with additional reproduction info if you feel this problem still exists.
