### ISSUE TITLE
expo-local-authentication.isEnrolledAsync not detecting enrolled device.

### ISSUE THREAD

**Issue by devinroche** [expo/expo#7148]
My Samsung A30 has faceID setup but when I run `isEnrolledAsync` false is returned. This doesn't seem right. According to the docs, it should return true.
> Determine whether the device has saved fingerprints or facial data to use for authentication.

Any reason why?

**Comment by cruzach** [comment]
The current implementation doesn't support FaceID on android, yet. However, support for that will be coming in SDK 37 🎉
