### ISSUE TITLE
Expo.Google.logInAsync() does not return idToken (android standalone)

### ISSUE THREAD

**Issue by helios1138** [expo/expo#715]
- I have a problem with a call to `Expo.Google.logInAsync()` that returns the user data (result type is success, no errors present) but all the token fields are `null`
- The issue is on standalone android app, testing on the emulator and on real device. 
- all the keys and clientIds are set up according to https://docs.expo.io/versions/latest/sdk/google.html
- logInAsync() works fine on ios simulators and devices, as well as when testing in Expo app on ios and android. But standalone android doesn't work :(

not sure what I'm doing wrong

**Comment by helios1138** [comment]
any updates on that?

**Comment by helios1138** [comment]
@dikaiosune @janicduplessis ^

**Comment by janicduplessis** [comment]
Hey, are you passing the ‘webClientId’? It is now needed to generate these tokens (it wasn’t before but the generated tokens were not good)

**Comment by helios1138** [comment]
@janicduplessis no, it's not entirely clear from the [docs](https://docs.expo.io/versions/latest/sdk/google.html) how to use `webClientId` or where is it applicable. How would one generate such a token in the google cloud console,
 should it be a [web application client ID](https://gyazo.com/0be1b23f506c95c992ff34699c148bfa)? If so, how should redirects be defined.

**Comment by janicduplessis** [comment]
Yes it should be of type web and doesn’t need any redirect url. You will need to pass both. Sorry the doc isn’t super clear, I’ll try to make it clearer that this is needed and how to get it.

**Comment by helios1138** [comment]
@janicduplessis ok, now the response does include idToken. But I'm not sure how to use it. For iOS I'm using [passport-google-id-token](https://www.npmjs.com/package/passport-google-id-token) which can parse idToken for given `iosStandaloneAppClientId`. The token android is now giving fails to be parsed using either `androidStandaloneAppClientId` or `webClientId`.

**Comment by helios1138** [comment]
@janicduplessis everything worked out, thank you!

**Comment by janicduplessis** [comment]
@helios1138 Awesome, did you have to do anything to parse the android token? Just for future reference.

**Comment by helios1138** [comment]
@janicduplessis yep, still using [passport-google-id-token](https://www.npmjs.com/package/passport-google-id-token), only for standalone apps I gave it web client id and for when running android apps through expo - standalone client id. 

Btw, for iOS the bundle id in standalone client id setup seems not to matter, the same clientId works for apps with different identifiers (I'm using multiple versions of apps like ****.develpment, ***.staging etc.)
