### ISSUE TITLE
EXC_BAD_ACCESS crash when canceling SMS view controller

### ISSUE THREAD

**Issue by jd20** [expo/expo#7154]
## 🐛 Bug Report

I've had couple reports of our ejected app crashing when sending an SMS with `expo-sms` library (v7.0.0). The crash is reported as "EXC_BAD_ACCESS: messageComposeViewController:didFinishWithResult: Attempted to dereference garbage pointer 0xef5ffa89c." (Obviously the pointer value changes each time.) I've attempted to reproduce it unsuccessfully. Also working to obtain a more detailed call stack.

### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.3.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.10.1 - ~/.npm/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @sentry/react-native: ^1.2.2 => 1.2.2 
      @types/react: ^16.8.22 => 16.9.11 
      react: 16.9.0 => 16.9.0 
      react-native: 0.61.5 => 0.61.5 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.13.1

The two crashes we've seen thus far occurred on two different iOS 13.3.1 / iPhone 11 Pro devices.

### Steps to Reproduce

None yet :( I've tried various ways of canceling the SMS view controller in our app, but not able to reproduce this crash so far.

### Expected Behavior

App should not crash.

### Actual Behavior

Crashing when canceling the SMS controller view (according to call stack).

### Reproducible Demo

This is roughly what our code that's calling `expo-sms` is doing:

```javascript
        if (!await SMS.isAvailableAsync()) return false
        const { result } = await SMS.sendSMSAsync(phoneNumber, message)
        // Do something with result...
```

**Comment by cruzach** [comment]
@jd20 please let us know if you're able to consistently reproduce this

**Comment by tsapeta** [comment]
I've tested this scenario during QA for SDK38 and hopefully it's no longer an issue in that SDK. Anyway, I really encourage you to migrate to bare workflow (or managed if you can) and then use the most recent version of `expo-sms` (there is a chance my PR #8575 solved this).
I'm gonna close this but feel free to reopen or create a new bug report if this issue still exists in the latest version.
