### ISSUE TITLE
Invalid Filesystem URI 

### ISSUE THREAD

**Issue by dflourusso** [expo/expo#716]
Hello, i'm trying download a file using:
```
FileSystem.createDownloadResumable("http://remote-uri.com", `${FileSystem.documentDirectory}my_file.ext`)
```
In IOS it works very well, but in android i got this error:

```
 Invalid Filesystem URI 'file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540my_user%252Fmy-react-native-app/my_file.ext', make sure it's in the app's scope.
```
What can i do?

---
Environment:
```
"expo": "^20.0.0",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
```

**Comment by amowu** [comment]
I also have a FileSystem problem, when I run this example code:

```js
const downloadResumable = FileSystem.createDownloadResumable(
  'http://techslides.com/demos/sample-videos/small.mp4',
  FileSystem.documentDirectory + 'small.mp4',
  {},
  ({totalBytesWritten, totalBytesExpectedToWrite}) => console.log(totalBytesWritten/totalBytesExpectedToWrite),
);

downloadResumable.downloadAsync()
  .then(({ uri }) => console.log(uri))
  .catch((error) => console.error(error));
```

I got a `Unable to save file to local URI` error.

And this is my environment:

iPhone 7 iOS 10.0

```
"dependencies": {
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.4"
  }
```

**Comment by sameesiddiqui** [comment]
Any update here? From my debugging it seems like on android, you can access child directories of documentDirectory and cacheDirectory, but not either directory itself.

Example:
`FileSystem.readDirectoryAsync(FileSystem.documentDirectory) // fails with 'invalid uri'`

`FileSystem.readDirectoryAsync(FileSystem.documentDirectory + 'cats/') // success`

**Comment by dflourusso** [comment]
I have a discussion [here](https://forums.expo.io/t/error-invalid-filesystem-uri/3546/3?u=dflourusso) too

I found a solution. I create a folder inside document directory and after it works well.


```javascript
ensureFolderExists () {
    const path = `${FileSystem.documentDirectory}MyFolder`
    return FileSystem.getInfoAsync(path).then(({exists}) => {
      if (!exists) {
        return FileSystem.makeDirectoryAsync(path)
      } else {
        return Promise.resolve(true)
      }
    })
  }

ensureFolderExists().then(() => {
  FileSystem.createDownloadResumable("http://remote-uri.com", `${FileSystem.documentDirectory}MyFolder/my_file.ext`).downloadAsync()
})
```

**Comment by nikki93** [comment]
I just tested this at the root and it works, and I think this may be related to https://github.com/expo/expo/issues/739 so closing for now. Please comment if you face this again!
