### ISSUE TITLE
[expo-app-auth][android] AppAuth.authAsync does not redirect back to app after oauth sign success

### ISSUE THREAD

**Issue by charitynguyenvan** [expo/expo#7160]
### Environment

```
System:
  OS: macOS 10.14.2
Binaries:
  Node: 12.16.0
  Yarn: 1.17.3
npmPackages:
  expo: 36.0.0
  react: 16.9.0
  react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
  expo-app-auth: 8.0.0
```

### Steps to Reproduce

Call `AppAuth.authAsync(config)` to do Oauth2 login

### Expected Behavior
After login success should redirect to app

### Actual Behavior
After login success there is NO redirect to app
**This issue only happens on Android.
It is working perfectly on iOS.**

### Reproducible Demo

```
const config = {
  clientId: 'clientId',
  clientSecret: 'clientSecret',
  redirectUrl: 'registered redirect url callback',
  scopes: ['some scope'],
  serviceConfiguration: {
    authorizationEndpoint: 'https://abc.com/oauth2/authorize',
    tokenEndpoint: 'https://abc.com/oauth2/token',
    revocationEndpoint: 'https://abc.com/oauth2/revoke'
  }
}
const f = async () => {
  try {
    const ret = await AppAuth.authAsync(config)
  } catch (error) {
    console.log('Failed to log in', error.message);
  }
}
f()
```

**Comment by EvanBacon** [comment]
Please use the new `expo-auth-session` API which utilizes `expo-web-browser` to redirect back into the app. On Android in the client `expo-app-auth` uses a hack to go back to the client, this hack mostly doesn't work. It would save the current app then when the redirect brings you to the expo client it would check to see which app was running last and redirect you into that. A better way to do this is to redirect by using the expo server location or app location like `exp://localhost:19006`. I redesigned AuthSession to account for these cases and perform in a more expected manner. https://docs.expo.io/versions/latest/sdk/auth-session/
