### ISSUE TITLE
[expo-file-system][macOS Catalyst] build error

### ISSUE THREAD

**Issue by redpandatronicsuk** [expo/expo#7166]
## 🐛 Bug Report
Building for MacOS Catalyst platform produces the following build error:
```
/.../expo-file-system/ios/EXFileSystem/EXFileSystemAssetLibraryHandler.m:95:21: 'fetchAssetsWithALAssetURLs:options:' is unavailable: not available on macCatalyst
```

### Environment

Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
      Watchman: 4.9.4 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.9.0 => 16.9.0
      react-native: 0.61.5 => 0.61.5
      react-navigation: 4.1.1 => 4.1.1
    npmGlobalPackages:
      expo-cli: 3.13.1

MacOS Catalyst
### Steps to Reproduce
Include `expo-file-system` as a dependency in your RN project and build for MacOS platform.

**Comment by cruzach** [comment]
Hi @redpandatronicsuk - unfortunately Expo doesn't support writing apps for Mac, yet. There's an open [feature request](https://expo.canny.io/feature-requests/p/support-for-ios-marzipanproject-catalyst-apps-that-can-run-on-macos) if you want to give it a vote!

**Comment by kirill-konshin** [comment]
Looks like something has been merged, can you shed some light on overall progress of Catalyst support?

**Comment by tsapeta** [comment]
@kirill-konshin

As @cruzach said, we don't support **MacOS**, but we're open for any fixes for **Mac Catalyst** as it's almost the same as iPadOS 🙂 That's why the PR mentioned above has been merged — sometimes there are just subtle changes that need to be applied in order to get Expo apps working on the Catalyst.
Either way, we cannot guarantee that will always work — we don't do any testing nor quality assurance against Mac Catalyst, but we encourage everyone to submit pull requests that fixes issues you encounter 😄

**Comment by kirill-konshin** [comment]
@tsapeta yep, I'm well aware of the feature request in @cruzach comment, I've commented there about RN 0.61.2 back in October 2019... My question was more about if Expo has any way to use RN's ability to build for MacOS targets (via Catalyst), and if yes — how? I haven't found any information regarding this...

I'm totally OK to do some QA for you and to fix issues.

**Comment by kirill-konshin** [comment]
@tsapeta still waiting for any sort of instructions how to build for mac target
