### ISSUE TITLE
Feature request: add "measure" method to BlurView

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#717]
I'm trying to measure a BlurView via the RN `measure` method, but it seems that the function doesn't exist. For example:
```jsx
<BlurView
    ref={view => this.blurView = view}
    onLayout={e => {
      console.log(e.nativeEvent.layout, windowHeight);
      this.blurView.measure((x,y,w,h,pX,pY) => console.log(x,y,w,h,pX,pY));
    }}
/>
```

**Comment by dikaiosune** [comment]
Hi! We're trying to keep feature requests on [Canny](https://expo.canny.io). Do you think you could open this over there? Thanks!

**Comment by JulianKingman** [comment]
Yep, thanks! Added: https://expo.canny.io/feature-requests/p/add-measure-method-to-blurview
