### ISSUE TITLE
`splash` screen should hide using the same logic as `AppLoading`.

### ISSUE THREAD

**Issue by terribleben** [expo/expo#718]
I believe this is already true on iOS as of pull 1157 internally, but making this ticket to ensure the same thing happens on Android.

**Comment by aalices** [comment]
Just like in iOS, every 20ms we check for new children of root React View. However, there's no native version of `AppLoading` for Android, so I suppose we don't have to care about it as a child - when the main app is rendered -> new `View` is added to root -> splash disappears. 

I was playing around with this a bit and haven't found anything worrying.
