### ISSUE TITLE
How to install HEAD of jest-expo?

### ISSUE THREAD

**Issue by kopax** [expo/expo#7182]
Hello, 

I would like to upgrade react-navigation to v5+, so far I am locked because of `jest-expo` fix not being released.

Is there a way to install from github HEAD somehow?

Usually the command is:

`npm i group/project` but this is a multi-package repository.

**Comment by cruzach** [comment]
As mentioned [here](https://github.com/expo/expo/pull/6999#issuecomment-584477836) you can use patch-package to get around this for now until we publish the new version (will look into doing that soon)

Closing since this isn't a bug report with the Expo SDK

**Comment by kopax** [comment]
@cruzach I never heard of patch-package. I know you mentionned it, I don't know what that is.

Is this related and why not just installing from the GitHub repository? : https://www.npmjs.com/package/patch-package ? 

Do I need to learn this as well in order to upgrade `jest-expo`?

**Comment by cruzach** [comment]
I think installing from a github repository is a little more difficult with a monorepo setup like ours, so you can definitely try to do that but I'm not sure how to go about it. 

But yes, that's the correct npm package we are referring to
