### ISSUE TITLE
Bundled images not showing in produced Android application

### ISSUE THREAD

**Issue by Elprior** [expo/expo#7186]
#### Expo

  Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.19.0 - /usr/bin/node
      npm: 6.13.4 - /usr/bin/npm
    npmGlobalPackages:
      expo-cli: 3.11.3

#### Turtle
0.13.9

#### Target
Android (as a start).
This is **not an ejected** React Native project.

### Steps to Reproduce

Hello,

I'm trying to build my first Expo application for Android.
Some of the images, such as a logo on the sign-up page, I would like bundled in the application.

I have decided to go for a build in my own CI, not using Expo servers.
So the commands that I'm using to build the applications are the following ones.

`expo export --dev --public-url http://127.0.0.1:8000`
then
`turtle build:android --type apk --keystore-path ./config/key/keystore.jks --keystore-alias XXX --public-url http://127.0.0.1:8000/android-index.json`
where EXPO_ANDROID_KEYSTORE_PASSWORD & EXPO_ANDROID_KEY_PASSWORD are set to expected values and XXX is replaced by the actual alias.

The test application is made of one single component comprising of Texts around a presumably bundled Image. The code for the component is accessible here:
[https://github.com/Elprior/ExpoBundledAssets/blob/master/Components/Main.js](https://github.com/Elprior/ExpoBundledAssets/blob/master/Components/Main.js)

The image that should be bundled is located in _../assets/images/bundledimage.png_

As long as I'm using the Expo application in development, the component behaves as expected (btw Expo is such a great initiative), but the packaged version is never displaying the image.

In the intermediate _dist_ folder, I can see that the _android-index.json_ file contains the following reference: `"bundledAssets":["asset_98728d96a4674a89a94c9c51324814e7.png"],"assetUrlOverride":"./assets"`
Where _98728d96a4674a89a94c9c51324814e7.png_ is the image that should be bundled and that I can open in the _dist/assets_ folder.

Finally the produced apk does contain the asset.

I have tried to change the value of **assetBundlePatterns** in the _app.json_ file to no end.
Also I understand that **assetUrlOverride** set to the value above refers to the URL as provided in build phase, but then I struggle to understand what it should be, and what the concept of bundled assets would be if it needs to be changed.

I'm pretty sure this is me not understanding the configuration that I should be using, but I can't find any help about that. Thanks in advance for your help!

### Expected Behavior

The application installed on the phone using the produced apk should include and display the bundled image, without any need for a reference to the URL provided during build phase or even a data connection.

### Actual Behavior

The application displays the texts surrounding the image, but the image is not displayed.

### Reproducible Demo

Here is a repository where the demo can be found:
[https://github.com/Elprior/ExpoBundledAssets](https://github.com/Elprior/ExpoBundledAssets)

**Comment by Elprior** [comment]
Anyone, please?

Thx in advance

**Comment by Elprior** [comment]
Replying to myself in the hope it will be useful to someone in the future...

The culprit is the --dev flag during export.
Building with a local https server removes the need for such a flag, and in that case images are bundled correctly.

**Comment by brentvatne** [comment]
thanks for the follow up @Elprior! perhaps we should warn people if they use `--dev` with `export`...

**Comment by akshg05** [comment]
I am facing issue with images not bundling and showing in release build. dev build works.
Can you help please?
