### ISSUE TITLE
SegmentedControl tintColor not working with iOS 13

### ISSUE THREAD

**Issue by glenngijsberts** [expo/expo#7204]
## 🐛 Bug Report

Not sure if this is the right place for this specific issue but with all different kind of parties involved I tried it first here. Summary: The SegmentedControl tintColor doesn't work anymore for iOS 13. According to [this](https://medium.com/flawless-app-stories/ios-13-uisegmentedcontrol-3-important-changes-d3a94fdd6763) Medium article the property is not working anymore for the `UISegmentedControl`. According to that article the property `selectedSegmentTintColor ` is introduced.

### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/opt/node@12/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
    IDEs:
      Xcode: 11.0/11M336w - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.2 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ~4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.3

Target: iOS 13

### Steps to Reproduce

Mentioned in the [expo docs](https://docs.expo.io/versions/latest/react-native/segmentedcontrolios/) it says you need to use the `SegmentedControlIOS` component from React Native if you are running a managed app. I import it from there and use it how it's described in the documentation (see demo). I tried to use the tintColor property but that doesn't affect the SegmentedControl on iOS 13.

### Expected Behavior

Expected behavior is that I'm able to change the appearance of the `SegmentedControl` component. 

### Actual Behavior

On < iOS 13 the SegmentedControl is working as expected with accepting a `tintColor`. iOS 13 and above is not working, the SegmentedControl doesn't change in Appearance and it's not possible to apply the `tintColor`. Also the new introduced `selectedSegmentTintColor` isn't doing anything.

### Reproducible Demo

https://snack.expo.io/rJLPfwHVI (Make sure to test on both < iOS 13 and > iOS 13

**Comment by cruzach** [comment]
Hi! thanks for the bug reports- have you tried testing if the react-native-community version of segemented control (in a bare workflow project) has or doesn't have this problem?
