### ISSUE TITLE
Compatibility with uuid 7.x, nanoid, and others

### ISSUE THREAD

**Issue by LinusU** [expo/expo#7209]
### Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.13.1
```

### Steps to Reproduce

There are a lot of libraries that requires synchronous random values. Many of those libraries are moving away from `Math.random()` because of the numerous issues with them.

The new standard web platforms api is the `crypto.getRandomValues` API, and this is what e.g. uuid and nanoid uses. This is an excellent API that gives you secure random values. The newly released version 7.x of uuid does no longer work without this API.

I've previously tried to [add `crypto.getRandomValues` into React Native itself](https://github.com/facebook/react-native/pull/20686), but unfortunately that never came to fruition. I still think that that would be the absolut best approach.

The next best approach for vanilla React Native is a polyfill! So that's why I wrote: [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values).

Unfortunately this polyfill doesn't work in Expo since it requires native code.

My proposal is to add the package to Expo as with other native packages, but also go one step further and adding the `require` of the polyfill to Expo itself, so that `crypto.getRandomValues()` will just work out of the box for everyone!

-----

We've already heard from a few users that are having problem with uuid in React Native/Expo, see some previous discussions: https://github.com/uuidjs/uuid/issues/375 https://github.com/uuidjs/uuid/pull/385

What we did for now was add instructions to React Native users to use the polyfill, but unfortunately we cannot offer a solution to Expo users right now 😱 

-----

As always I'm willing to submit PRs for this 👍

**Comment by cruzach** [comment]
Most of the time, we look for additions to the Expo SDK based on desired items on our [canny](https://expo.canny.io/feature-requests), so I think instead of opening an issue here, you're better of creating a good feature request there. 

Good news is that your library is definitely going to be nice for anyone in the bare workflow right now!

**Comment by Hirbod** [comment]
I would merge this one here right away. It's highly beneficial for the community and more then a nice to have feature, it's kinda elementary and he provided a clean package + PR + enough explanation why this would be a good package. Things on canny tend to lay there for months or years until something happens.

**Comment by code-by** [comment]
same on Expo 36

**Comment by GollyJer** [comment]
> 
> 
> Most of the time, we look for additions to the Expo SDK based on desired items on our [canny](https://expo.canny.io/feature-requests), so I think instead of opening an issue here, you're better of creating a good feature request there.
> 
> Good news is that your library is definitely going to be nice for anyone in the bare workflow right now!

It might be worth asking why this isn't in Canny.
My guess is things used to work because there weren't any other options. Now the community has improved but Expo is behind. 

@LinusU has presented a complete solution that provides synchronous functionality to secure random values. It would be GREAT to take advantage of this inside a managed Expo project. Being forced to use async code when it is completely unnecessary is tough to swallow when the solution is right here. 😃

**Comment by ctavan** [comment]
@LinusU @cruzach would it change anything if we duplicated this issue in [canny](https://expo.canny.io/feature-requests)?

This seems like a very low hanging fruit as a proven, stable implementation already exists and @LinusU even offered to provide a pull request.

I guess all we'd need is to learn if such a pull request had any chances of being accepted?

**Comment by cruzach** [comment]
Just so I understand- this would be a feature request for a synchronous implementation of the method in https://docs.expo.io/versions/latest/sdk/random/ ?

**Comment by GollyJer** [comment]
> 
> 
> Just so I understand- this would be a feature request for a synchronous implementation of the method in https://docs.expo.io/versions/latest/sdk/random/ ?

Yes.

**Comment by LinusU** [comment]
@cruzach I would very very much prefer it to be exposed (both is of course okay) under the global `crypto.getRandomValues`. That will really help with compatibility between runtimes, and without it every package has to include their own logic for selecting the expo package when running under Expo, and using the standard `crypto.getRandomValues` on browsers, Deno, etc.

Also, keeping it under the global `crypto.getRandomValues` guarantees that the API won't change, since it's defined by the W3 specification and it's not versioned. It will always work the exact same way.

Finally, `getRandomBytesAsync` always allocates a new array, which isn't always desirable and can lead to extra copying...

The bug report that I opened here really is about adding `crypto.getRandomValues`, adding a sync version of `getRandomBytesAsync` might be desirable as well, but it was not my intended outcome here...

**Comment by GollyJer** [comment]
100% agree with @LinusU.  Standardizing with the community would be the ideal solution.

But I'd take the update to expo-random if it were to come faster. Removing async calls whenever possible simplifies development.

**Comment by brentvatne** [comment]
keeping this open until we release sdk-39. going to follow up with a pr to @LinusU's react-native-get-random-values to use the expo-random native module when in the managed workflow

**Comment by martinheidegger** [comment]
@brentvatne Is there any plan to also expose it under `crypto.getRandomValues` without the import? (automatic web compatibility)

**Comment by brentvatne** [comment]
@martinheidegger - yeah, i want to make sure we play nicely with existing ways to do this in the ecosystem so i opened this pr: https://github.com/LinusU/react-native-get-random-values/pull/13

we don't currently plan on polyfilling this *automatically* though - users will need to import a polyfill like react-native-get-random-values.

**Comment by seigel** [comment]
" users will need to import a polyfill like react-native-get-random-values."

@brentvatne Do you have an example of how would do that for the expo managed environment?

**Comment by brentvatne** [comment]
yup, the readme at https://github.com/LinusU/react-native-get-random-values#installation

**Comment by seigel** [comment]
So nothing special or new needed for the latest release with the lovely synchronous method. Thanks!

**Comment by LinusU** [comment]
For anyone that has followed this thread, I just want to clarify that as of SDK 39 the only thing you need to do to get `crypto.getRandomValues` (and thus `uuid`, etc.) is to install and import [react-native-get-random-values](https://github.com/LinusU/react-native-get-random-values).

You do not need to install `expo-random`.

**Comment by Dakuan** [comment]
does this work with managed apps?

**Comment by Hirbod** [comment]
@Dakuan yes

**Comment by Macilias** [comment]
@Dakuan not really, I tried it, and it looked promising at first but than I runed into: https://stackoverflow.com/questions/66377449/how-to-fix-nativemodules-rngetrandomvalues-getrandombase64-error

**Comment by brentvatne** [comment]
@Macilias - it works fine. install react-native-get-random-values@1.7.0
