### ISSUE TITLE
The command "npm install jest-expo" failed and exited with 1 during . (Travis build failure)

### ISSUE THREAD

**Issue by bryanboyko** [expo/expo#7211]
With a simple expo setup, I'm getting the following error for Travis builds:

`The command "npm install jest-expo" failed and exited with 1 during .`

Any ideas?

**.travis.yml**
```
os: osx
  
language: node_js
node_js:
  - 12.12.0

install:
- npm install jest-expo
```

**Travis build**
https://travis-ci.com/bryanboyko/ExpoDetoxTravis/builds/150878747

**Github PR**
https://github.com/bryanboyko/ExpoDetoxTravis/pull/2

**Comment by cruzach** [comment]
Hey @bryanboyko , similar to your [other recent bug report](https://github.com/expo/expo/issues/71810, we'll need a reproducible demo to help effectively (]here's a really good guide/explanation](https://stackoverflow.com/help/minimal-reproducible-example))

For this issue, you may want to look at the additional logs the error message points you to

**Comment by bryanboyko** [comment]
Hi @cruzach!

A follow up to this issue:

(I believe my former issue may have have been related to either 1. global build artifacts in travis that caused build issues and were a pain to remove and/or 2. a version of XCode that didn't match up with the version of Detox in use and/or 3. an incorrectly chosen language for the Travis build)

**Goal:**
I would like to be able to run detox tests for an expo app with travis.

I created a bare bones expo app that successfully runs a single detox test on my local machine. After pushing to git and running on travis, all dependencies install successfully and then the Travis build scripts fail with the following error.

**Error:**
`Error: Could not find build script in detox.configurations["ios.sim"].build`

**Issue:**
It looks like the issue occurs because there isn't a "build" entry in the "ios.sim" configuration for "detox" in `package.json`. What to put for the "build" configuration for an Expo project? While there is an Exponent.app provided by expo to run tests with detox, I don't see any `.xcodeproject or .xcworkspace` to build with.

**Repro steps:**
- Clone git@github.com:bryanboyko/expo-detox-travis-3.git
- `cd expo-detox-travis-3`
- `npm install`
- `./setup.sh`
- `detox test`
- push to a new branch and create a PR to see travis build

**Travis failure log:**
https://travis-ci.com/bryanboyko/expo-detox-travis-3/builds/151879107

**Comment by bryanboyko** [comment]
Follow up:

`Detox build` command succeeded with the following "build" entry in package.json 

```
  "detox": {
    "test-runner": "jest",
    "configurations": {
      "ios.sim": {
        "binaryPath": "bin/Exponent.app",
        "build": "expo build:ios --type simulator --release-channel e2e_test_channel",
        "type": "ios.simulator",
        "name": "iPhone 8"
      }
    }
  }
```

Detox tests succeed after running the following two commands on my local machine (Even without starting an expo process via `expo start` in another process)

```
$detox build --configuration ios.sim
$detox test --configuration ios.sim --cleanup
```

The same configuration fails in a Travis build due to the following error:

```
detox[6778] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 2) invoke: {"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"firstScreen"}]}}]}},"method":"assertWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForSufficientlyVisible","args":[]}}]}
  (id = -1000) isReady: {}
That might be the reason why the test "Example should have welcome screen" has timed out.
 FAIL  e2e/firstTest.spec.js (383.067s)
  Example
    ✕ should have welcome screen (242127ms)
  ● Example › should have welcome screen
    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
```
