### ISSUE TITLE
expo-media-library read some images in wrong format

### ISSUE THREAD

**Issue by Karlen92** [expo/expo#7212]
### Environment

 Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^2.18.2 => 2.18.3 

### Steps to Reproduce

Please follow this link 
[https://round2-ohio-us-1.s3.us-east-2.amazonaws.com/images/78f892-1582770012622](https://round2-ohio-us-1.s3.us-east-2.amazonaws.com/images/78f892-1582770012622)

This is an image file picked from camera roll and uploaded to s3, no modification are done. I have
many image files, but after changing react-native CameraRoll to in some files it behaves like this. There are such cases in both platforms. Here is the code how I pick images.

``` javascript
 getImages = async () => {
        const { after, has_next_page } = this.state;
        const params = { first: 50 };
        if (after) params.after = after;
        if (!has_next_page) return;
        MediaLibrary
            .getAssetsAsync(params)
            .then(this.processPhotos);
    }
```
**expo-media-library version is 8.0.0** 

Is there something I'm doing wrong, or it's actually a bug ?

**Comment by cruzach** [comment]
Unfortunately this bug report doesn't provide enough information for me to help debug this further. I've used that MediaLibrary method successfully, and without more information (what `processPhotos` is doing), it's hard to help.

Can you provide a full reproducible demo we can use, as well as a detailed description of what the problem is?

**Comment by Karlen92** [comment]
@cruzach Thanks for your quick response. To address your question, I didn't do anything in `processPhotos`, I just upload photos to S3 as they are. But now I made a change in the function in the following way.

```javascript
 // ...
const  changedImage = await ImageManipulator.manipulateAsync(
                     photo.uri,
                     [
                         {
                             resize: {
                                 width: photo.width,
                                 height: photo.height,
                             },
                         },
                     ],
                     {
                         compress: 0.1,
                         format: ImageManipulator.SaveFormat.JPEG,
                     },
                 )
 // upload changedImage
```
I've added Expo `ImageManipulator` to convert image to `JPG` (Solution works without this line `format: ImageManipulator.SaveFormat.JPEG`). This one works fine, but I don't have an explanation for this. I had previous problems with  `exif` and solved the issue in exactly this way, but in that case, the image was displaying fliped, in this case, it was not displaying at all. Note that this issue is only IOS specific.

**Comment by cruzach** [comment]
>  I had previous problems with exif and solved the issue in exactly this way, but in that case, the image was displaying fliped, in this case, it was not displaying at all. Note that this issue is only IOS specific.

I'm not sure I understand what you mean here. Does the solution you shared result in the image not displaying at all?

**Comment by aglumova** [comment]
I encountered a similar issue and traced it to file extension mismatches (in my case it was IOS).

When `MediaLibrary.createAssetAsync()` is called with a file where the extension doesn't match the actual format (e.g., PNG data saved as `.jpg`), iOS Photo Library triggers "repair mode":

1. Reads file extension → Expects JPEG
2. Reads magic bytes (`89 50 4E 47`) → Detects PNG
3. "Corrupted file" → Decode PNG, re-encode as JPEG
4. Apply compression + downsample

**Result:** Quality loss, no errors thrown

This explains why `ImageManipulator.manipulateAsync()` fixed it in your - it re-encodes the image with the correct extension matching the content.

**Solution works for me:**

Detect the actual format from magic bytes before saving:

```typescript
const detectImageFormat = async (fileUri) => {
  const fileInfo = await FileSystem.readAsStringAsync(fileUri, {
    encoding: FileSystem.EncodingType.Base64,
    length: 12,
  });
  
  const bytes = atob(fileInfo).split('').map(c => c.charCodeAt(0));
  
  // PNG: 89 50 4E 47
  if (bytes[0] === 0x89 && bytes[1] === 0x50 && 
      bytes[2] === 0x4E && bytes[3] === 0x47) {
    return "png";
  }
  
  // JPEG: FF D8 FF
  if (bytes[0] === 0xFF && bytes[1] === 0xD8 && bytes[2] === 0xFF) {
    return "jpg";
  }
  
  ...
};
```
