### ISSUE TITLE
Connection to debugger-proxy timed out with Debug Remote JS and Hot Reloading

### ISSUE THREAD

**Issue by jhen0409** [expo/expo#722]
We can see the related issue https://github.com/jhen0409/react-native-debugger/issues/32#issuecomment-331531829, I can only reproduce it on the Expo client, and confirmed the issue isn't related to the project.

<img width="274" alt="screen shot 2017-10-04 at 9 25 01 pm" src="https://user-images.githubusercontent.com/3001525/31178073-8b7362ca-a8dd-11e7-9cea-d2305f97e2dc.png">

## Reproduce steps

1. Initial project of [create-react-native-app](https://github.com/react-community/create-react-native-app) (CRNA 1.0.0, Expo SDK 21, React Native 0.48.4) and run `yarn ios`
2. Disable Live Reload then enable Debug Remote JS (with http://localhost:19001/debugger-ui) and Hot Reloading
3. Restart Expo app ([really close it](https://support.apple.com/en-us/HT201330)) then click recently visited project
4. Running the project and waiting 5 ~ 10s will caused this problem

**Comment by dmnd** [comment]
I'm hitting this too. What state do I have to blow away to make it go away? I'm fine with not using hot reloading until this gets fixed. I tried deleting the `.expo` directory but it still occurs after a rebuild.

**Comment by dmnd** [comment]
There's an `.expo` directory in my project, but another one in my home directory. Deleting the one in my home directory seemed to work — now I don't see this error.

**Comment by Viral-Inc** [comment]
+1

**Comment by lenghia241** [comment]
@dmnd Can i ask what do you mean by home directory? Where can i find it?

**Comment by dmnd** [comment]
@lenghia241 `~/.expo` or `/Users/dmnd/.expo`. I'm on a mac, so your path might be different.

**Comment by febrodriguez** [comment]
@dmnd your suggestion work for me! Thanks!

**Comment by sjchmiela** [comment]
Thanks, @dmnd, for explaining how to fix this issue! It shouldn't happen anymore. 🙂
