### ISSUE TITLE
The "Profile" tab in the Expo client is blank

### ISSUE THREAD

**Issue by ningacoding** [expo/expo#7220]
This issue still happening:

https://github.com/expo/expo/issues/4734
(The "Profile" tab in the Expo client is blank)

**Comment by cruzach** [comment]
Hi, thanks for reporting. Just to make this ticket a little clearer for anyone looking at it- you can reproduce the issue by logging into the Expo client app on your device, then going to `expo.io`, logging into your account, going to Settings, and clicking "Log out of all sessions"

We're investigating this issue and hope to have a fix out soon

**Comment by cruzach** [comment]
@ningacoding we’ve just pushed out a fix for this so you should be able to open the Expo client app and log back in, no need to reset your device or anything

Thanks again for reporting!
