### ISSUE TITLE
takePictureAsync(), quality not working as intended on iOS?

### ISSUE THREAD

**Issue by MylesCaley** [expo/expo#723]
Was expecting to set `quality` between 0 and 1 with values like`0.1`, `0.2`, etc. Anything >= `0.01` has no impact and does no compression. Workaround is using `0.001`, `0.0015`, etc

I traced this back to `EXCameraManager.m`
 
``` NSData *takenImageData = UIImageJPEGRepresentation(takenImage, quality * 100);```

It does appear to work as expected on Android.

https://docs.expo.io/versions/latest/sdk/camera.html

**Comment by ide** [comment]
Thanks for the bug report!

**Comment by ide** [comment]
We've fixed this internally in preparation for the next SDK release (22). Thanks for the precise investigation in your report btw, it was helpful.
