### ISSUE TITLE
AppAuth and Gitlab oAuth

### ISSUE THREAD

**Issue by fredericmalo** [expo/expo#7234]
## 🐛 Bug Report

Hello, official expo.io documentation explains that [AppAuth is working with Gitlab oAuth](https://docs.expo.io/versions/latest/sdk/app-auth/), but I cannot adapt the provided source code to make it work. 

### Environment

latest: 
>   Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.17.0 - /usr/local/opt/node@10/bin/node
      npm: 6.11.3 - /usr/local/opt/node@10/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.1

App's target : iOS

### Steps to Reproduce

1. [official source code sample](https://docs.expo.io/versions/latest/sdk/app-auth/#usage) is working with Google Sign in
2. I've created an app on Gitlab's side: https://gitlab.com/profile/applications
3. First adaptation: 

Instead of 
`let config = {
  issuer: 'https://accounts.google.com',
  scopes: ['openid', 'profile'],
  clientId: '*clientId*'
};
`

I'm pointing to gitlab:
`let config = {
  issuer: "https://gitlab.com",
  scopes: ['openid', 'api', 'read_repository', 'write_repository', ],
  clientId: '*clientId*'
};`

I'm facing a **"redirect_uri_mismatch” error**.

4. Second adaption: I'm overwriting redirectUrl, because I think that [AppAuth.OAuthRedirect](https://docs.expo.io/versions/latest/sdk/app-auth/#appauthoauthredirect) method is returning "host.exp.exponent"

`let config = {
  issuer: "https://gitlab.com",
  scopes: ['openid', 'api', 'read_repository', 'write_repository', ],
  redirectUrl: "https://auth.expo.io/@userid/slug",
  clientId: '*clientId*'
};`

Now I'm facing the "Something went wrong trying to finish signing in. Please close this screen to go back to the app." message, the same as the one presented in GET calls of https://auth.expo.io/@userid/slug

I don't know how to continue further. Can someone help me to resolve the issue ? Thanks !

### Expected Behavior

Gitlab sign-in would provide access+refresh token

### Actual Behavior

Please see above

### Reproducible Demo

Here is latest adaptation of official source: 

/*  App.js  */
import React, { useEffect, useState } from 'react';
import { AsyncStorage, Button, StyleSheet, Text, View } from 'react-native';
import * as AppAuth from 'expo-app-auth';

export default function App() {
  let [authState, setAuthState] = useState(null);

  useEffect(() => {
    (async () => {
      let cachedAuth = await getCachedAuthAsync();
      if (cachedAuth && !authState) {
        setAuthState(cachedAuth);
      }
    })();
  }, []);

  return (
    <View style={styles.container}>
      <Text>dot</Text>
      <Button
        title="Signin"
        onPress={async () => {
          const authState = await signInAsync();
          setAuthState(authState);
          console.log('---- authState')
          console.log(authState)
        }}
      />
      <Button
        title="Sign Out "
        onPress={async () => {
          await signOutAsync(authState);
          setAuthState(null);
        }}
      />
      <Text>{JSON.stringify(authState, null, 2)}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

let config_google = {
  "name":"Google",
  issuer: 'https://accounts.google.com',
  scopes: ['openid', 'profile'],
  clientId: '*clientId*'
};

console.log('oauth');
console.log(AppAuth.OAuthRedirect);

let config_gitlab = {
  issuer: "https://gitlab.com",
  redirectUrl: "https://auth.expo.io/@username/appslug",
  scopes: ['openid', 'api', 'read_repository', 'write_repository', ],
  clientId: '*clientId*'
};

let config = config_gitlab;

let StorageKey = '@dot:CustomGitlabOAuthKey';

export async function signInAsync() {
  let authState = await AppAuth.authAsync(config);
  await cacheAuthAsync(authState);
  console.log('signInAsync', authState);
  return authState;
}

async function cacheAuthAsync(authState) {
  return await AsyncStorage.setItem(StorageKey, JSON.stringify(authState));
}

export async function getCachedAuthAsync() {
  let value = await AsyncStorage.getItem(StorageKey);
  let authState = JSON.parse(value);
  console.log('getCachedAuthAsync', authState);
  if (authState) {
    if (checkIfTokenExpired(authState)) {
      return refreshAuthAsync(authState);
    } else {
      return authState;
    }
  }
  return null;
}

function checkIfTokenExpired({ accessTokenExpirationDate }) {
  return new Date(accessTokenExpirationDate) < new Date();
}

async function refreshAuthAsync({ refreshToken }) {
  let authState = await AppAuth.refreshAsync(config, refreshToken);
  console.log('refreshAuth', authState);
  await cacheAuthAsync(authState);
  return authState;
}

export async function signOutAsync({ accessToken }) {
  try {
    await AppAuth.revokeAsync(config, {
      token: accessToken,
      isClientIdProvided: true,
    });
    await AsyncStorage.removeItem(StorageKey);
    return null;
  } catch (e) {
    alert(`Failed to revoke token: ${e.message}`);
  }
}

**Comment by cruzach** [comment]
`redirectUrl` should be your package name / bundle identifier in a standalone app (+ ':/oauthredirect') , but if you're testing in the expo client then it should be `host.exp.exponent` (+ ':/oauthredirect')

**Comment by fredericmalo** [comment]
Hi Charlie, thanks for your kind reply. I understand your point but I would like to stress that AppAuth is not able to handle Gitlab use case because Gitlab only accept absolute URI as redirect URI and "host.exp.exponent" is not absolute. 

> <img width="399" alt="Capture d’écran 2020-03-09 à 21 45 46" src="https://user-images.githubusercontent.com/3525134/76256551-6df68680-6250-11ea-8e07-d5d300483885.png">

Please note that I've successfully been able to connect Gitlab oAuth thanks to AuthSession with https://auth.expo.io/@username/appslug as redirect URI : 

    let redirectUrl = AuthSession.getRedirectUrl();
    let authUrl = `https://gitlab.com/oauth/authorize?client_id=${GitlabAppId}&redirect_uri=${
      encodeURIComponent(
        redirectUrl
      ) }&response_type=token&scope=api+read_repository+write_repository`;
    let result = await AuthSession.startAsync(
       {
        authUrl:authUrl,
      }
    );

But in fact, I love the way AppAuth is handling oAuth. I would be pleased to know how to configure AppAuth otherwise it would be great to update expo.io documentation as requested in my [PR](https://github.com/expo/expo/pull/7301).

I'm not sure to follow your kind suggestion : do we have to use https://auth.expo.io/@username/appslug:/oauthredirect as redirect URI ? (I'm using expo client (for now) )

Thanks and sorry for disturbing. Kind regards, Frédéric

**Comment by cruzach** [comment]
Oh that screenshot from gitlab helps. According to the [spec](https://tools.ietf.org/html/rfc3986#section-4.3), you might be missing the hier-part (`:/oauthredirect`)

**Comment by fredericmalo** [comment]
Hello Charlie, 
Not sure to follow you: [Appendix A](https://tools.ietf.org/html/rfc3986#appendix-A) of the RFC explains that hier-part should be : 

```
  hier-part     = "//" authority path-abempty
                 / path-absolute
                 / path-rootless
                 / path-empty
```
Because Gitlab accepts only absolute path, expo.io specs indicates it should be 
https://auth.expo.io/@username/appslug

By the way, this redirect URI works with expo.io's AuthSession. 

Do we have to conclude that expo.io's AppAuth is not compatible with Gitlab oAuth mechanism and any other that requests absolute redirect URI as mandatory ?

Thanks, best !

**Comment by EvanBacon** [comment]
Please migrate to using the new AuthSession API which will succeed `expo-app-auth`. It doesn't have a guide for GitLab yet but it should work just fine.
