### ISSUE TITLE
[ExpoKit][TaskManager] Binary rejected on App Store

### ISSUE THREAD

**Issue by holgersindbaek** [expo/expo#7255]
My app is being rejected from Apple because I'm setting the UIBackgroundMode "location" and never use location inside the app:

![Screenshot 2020-03-03 at 17 50 49](https://user-images.githubusercontent.com/698979/75799285-33847980-5d78-11ea-8898-1ce37c1367a7.jpg)

TaskManager specifies that "location" has to be set in UIBackgroundMode: https://docs.expo.io/versions/latest/sdk/task-manager/#configuration-for-standalone-apps. 

Can I remove the "location" and still have TaskManager work? Why is location required in UIBackgroundModes?

**Comment by cruzach** [comment]
Unless you're using background location, you don't need the `location` key in `UIBackgroundModes`. The example in the docs states that it is an example of "app.json that enables background location **and** background fetch'
