### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod “Crashlytics”

### ISSUE THREAD

**Issue by dulcehc** [expo/expo#7256]
### Environment

Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.6 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.11.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.13.1

SDK Version: 36
Platforms(Android/iOS/web/all): iOS

### Steps to Reproduce

I’m using React Native Firebase and I followed the configuration for Crashlytics according to the documentation https://invertase.io/oss/react-native-firebase/v6/crashlytics/ios, but during the pod installation there is an error related to mismatch of versions for the package “@react-native-firebase/crashlytics”: “^6.3.4”.

```
[!] CocoaPods could not find compatible versions for pod "Crashlytics":
  In Podfile:
    ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.14.4`) was resolved to 36.0.0, which depends on
      Crashlytics (~> 3.13.4)

    RNFBCrashlytics (from `../node_modules/@react-native-firebase/crashlytics`) was resolved to 6.3.4, which depends on
      Crashlytics (~> 3.14.0)
Expo uses ‘Crashlytics’, ‘~> 3.13.4’ ExpoKit.podspec but the dependency has a higher version 3.14.0 RNFBCrashlytics.podspec
```

I’m already tried some suggestions like updating the pods:
pod repo update or pod install --repo-update

### Expected Behavior

Pod installation without errors when using React Native Firebase.

### Actual Behavior

Error for Crashlytics during pod installation.

**Podfile**

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'coachmate' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.14.4",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true

  # Install unimodules
  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
  use_unimodules!(
    modules_paths: ['../node_modules'],
    exclude: [
      'expo-bluetooth',
      'expo-in-app-purchases',
      'expo-payments-stripe',
    ],
  )

 # Install React Native and its dependencies
 require_relative '../node_modules/react-native/scripts/autolink-ios.rb'
 use_react_native!

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

      if pod_name == 'ExpoKit'
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'

          # Enable Google Maps support
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS_UTILS=1'

        end
      end

      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end


      # Can't specify this in the React podspec because we need to use those podspecs for detached
      # projects which don't reference ExponentCPP.
      if pod_name.start_with?('React')
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        end
      end

      # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
      # RCT_ENABLE_PACKAGER_CONNECTION disabled
      next unless pod_name.start_with?('React')
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end

    end
  end
end
```

**Comment by soygustavo** [comment]
Hi, i'm having the same issue with the exact same settings

**Comment by soygustavo** [comment]
Hi @dulcehc i made a hackie kind of fix to this that let me build and keep working, it's not ideal but for now it may help you keep working
Just edit the file node_modules/@react-native-firebase/crashlytics/RNFBCrashlytics.podspec and locate this line
# Crashlytics SDK Override
crashlytics_sdk_version = '~> 3.14.0'

and downgrade the version to 3.13.4
crashlytics_sdk_version = '~> 3.13.4'

and then do a pod install --repo-update and should be no issues

and if you do some npm install at some point, you probably need to repeat these steps

**Comment by sejoon-mfort** [comment]
I have the same issue.

**Comment by cruzach** [comment]
I think @soygustavo 's workaround should work, and when we release SDK 37, the bare workflow should enable you to update/change these dependencies much more easily (at that point, Expokit will be deprecated)

**Comment by dulcehc** [comment]
I disabled Crashlytics in the meantime, I will look for another tool like Sentry. 
@cruzach Do you mean that for Expo 37, we won't be able to eject?

**Comment by cruzach** [comment]
No you will. We strongly recommend ejecting to `bare` and not `expokit`, but you still can. However, we will be phasing out support for expokit after SDK 37's release

**Comment by tsapeta** [comment]
As Charlie commented above, ExpoKit is no longer supported and we recommend ejecting to bare instead of ExpoKit. In bare workflow you'll have more control on which versions are being installed 😉
