### ISSUE TITLE
Is Hmac-sha1 supported in the expo-crypto package?

### ISSUE THREAD

**Issue by Eric1015** [expo/expo#7257]
as title

**Comment by cruzach** [comment]
You can see the supported algorithms [here](https://github.com/expo/expo/blob/sdk-36/packages/expo-crypto/src/Crypto.types.ts#L1)

**Comment by emac3** [comment]
and no plan to support HMAC in general?

**Comment by leethree** [comment]
Hmac support would be very helpful

**Comment by jer-sen** [comment]
@cruzach hmac is a must for any cryptographic library, for example to sign requests on the frontend
