### ISSUE TITLE
Is Hot Reloading broken?

### ISSUE THREAD

**Issue by HundredBillion** [expo/expo#7258]
### Please note that discussions opened as issues in the core Expo repository will be closed.
I have an app that I deployed to Testflight. This should not have touched my production app, but when I did  ```expo build``` for Testflight, it Hot Reloaded my production app and pointed to my staging DB.

Is there something I'm doing wrong? 

How do I deploy to Testflight without affecting my production app?

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂

**Comment by cruzach** [comment]
I think you're referring to OTA updates. 

When you run `expo build`, it also runs `expo publish` (unless you pass the `--no-publish` flag). If you want to deploy a separate version of the app to TestFlight, which points to a different version of your javascript bundle, you can use a different [release channel](https://docs.expo.io/versions/latest/distribution/release-channels/) for it
