### ISSUE TITLE
typeerror: undefined is not an object (evaluating '_expo.constants.manifest')

### ISSUE THREAD

**Issue by serkanz** [expo/expo#7265]
## 🐛 Bug Report
I'm trying to upgrade my React Native App from 33.0 to 36.0 . I created an empty project with expo init command and copied my existing App folder into it (I know that I could have used expo upgrade but it didn't work ). I used expo start to run my app and everytime it gave missing module error I used yarn add to install related dependencies. 

Now my app builds and deployed to emulator, but it gives **typeerror: undefined is not an object (evaluating '_expo.constants.manifest')**

I'm giving the link of the screenshot of the emulator : https://ibb.co/xHYT8Df

Is there something that I'm missing with expo-constants library? Because stack trace shows that app crashes before it reaches my root App.

Kind Regards
{
"dependencies": {
    "@react-native-community/datetimepicker": "^2.2.2",
    "axios": "^0.19.2",
    "buffer": "^5.4.3",
    "crypto-js": "^3.1.9-1",
    "dva-core": "^2.0.2",
    "expo": "~36.0.0",
    "expo-constants": "^8.0.0",
    "expo-crypto": "^8.0.0",
    "expo-sqlite-orm": "^1.5.3",
    "haversine": "^1.1.1",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-maps": "^0.26.1",
    "react-native-modal-datetime-picker": "^8.5.1",
    "react-native-pin-view": "^3.0.0",
    "react-native-rsa": "^0.0.3",
    "react-native-search-filter": "^0.1.5",
    "react-native-uuid": "^1.4.9",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.2.2",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "sentry-expo": "^2.0.1"
  }
}

### Environment
 Expo CLI 3.13.1 environment info:
    System:
      OS: Windows 8.1
    Binaries:
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832

**Comment by serkanz** [comment]
I the issue is something related with expo-constants library. We can close the issue.

**Comment by richill** [comment]
has this bug been resolved? because i am experiencing the same issue

**Comment by lkmSasanga** [comment]
I'm getting this error too

**Comment by davidcort** [comment]
I have 3 days with this error  :'(
