### ISSUE TITLE
What is the correct expokit version for SDK21 for detached app?

### ISSUE THREAD

**Issue by pencilcheck** [expo/expo#727]
1.20.5 doesn't work
1.19.2 doesn't work

I followed all the instructions from the blog post, and also updating the ios Podfile properly and update the approprate fields in plist but still not working.
Which version should I use to build for SDK21?

**Comment by pencilcheck** [comment]
Seems like I have to really guess based on the release timeframe between this project and the other expo/react-native project to get it right.

I used 1.20.1 now and it works.

**Comment by terribleben** [comment]
What was the issue with 1.20.5? That would be the correct one.

**Comment by pencilcheck** [comment]
I can't build, keep getting error about some react-native files are
missing. I don't know why.
