### ISSUE TITLE
how to generate signing key finger print google auth 

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#7273]
It's been 5 months and still, I could not integrate google login, 
please let me know how to generate the sh1 key to use fingerprint in google developers' account.

**Comment by cruzach** [comment]
Hi @reactexcel , we have documentation on this [here](https://docs.expo.io/versions/latest/sdk/google/#deploying-to-a-standalone-app-on-android). If you think you're running into a bug, please fill out the entire bug report template, thanks!
