### ISSUE TITLE
EXGLView: iOS: issues with multiple textures

### ISSUE THREAD

**Issue by gre** [expo/expo#728]
here is an example : https://snack.expo.io/HJE_kof3-

it renders a grid of 9 sampler2D image textures.

**on iOS, it renders white, it never succeed to render something.**

on Android, it renders this:

![img_0298](https://user-images.githubusercontent.com/211411/31215699-db5ef65e-a9b0-11e7-8e34-4427bd0ce496.JPG)

**Comment by jimmylee** [comment]
is the screen crack part of the visual effect too? haha (sorry I'm not funny). Assigning @nikki93 to have a look.

**Comment by gre** [comment]
no that's my broken screen 🤣

**Comment by bbarthec** [comment]
I've tested it out with sdk31 and even refactored a bit ([here](https://snack.expo.io/@barthec/nine-textures)) and it's working so I believe problem is already solved 😄 
I'm closing this issue, but feel free to reopen if needed.
