### ISSUE TITLE
[iOS] Image's position is off downward when editing picture taken with ImagePicker

### ISSUE THREAD

**Issue by esdrasevt** [expo/expo#7281]
### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.13.1

 iOS, Managed, Standalone App

### Steps to Reproduce

Implement ImagePicker just how it is suggested in the documentation [here](https://docs.expo.io/versions/latest/sdk/imagepicker/) , but getting picture from camera instead of camera roll / library. When the camera pops-up, put the phone in landscape, and snap a picture. The following screen will be the "editing" screen, which is where the unexpected behavior/bug happens.

### Expected Behavior

I understand that the `ratio` is not applied to iOS, but it is expected that the image would be centered horizontally and vertically in the screen.

### Actual Behavior

The image is off vertically instead of being centered, which makes almost impossible to get a good crop of pictures taken with the phone in landscape mode. See gif below:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9984366/75920965-f080df80-5e25-11ea-99d1-fe1be7f76a03.gif)

### Reproducible Demo

https://snack.expo.io/@esdrasevt/1ba90e

Don't forget to give permissions to camera and camera roll when asked, otherwise the snack won't work.

**Comment by esdrasevt** [comment]
I was just testing around here, and if you look close, the same thing also happens with pictures taken in portrait mode, but since the height of the image taken in portrait mode is larger, you don't get the "black borders" inside the crop area.

**Comment by lukmccall** [comment]
Hi @easadler, this bug is in the iOS. For more information, check out [this issue](https://github.com/expo/expo/issues/7134).

**Comment by esdrasevt** [comment]
@lukmccall I saw that issue you mentioned previously, but I thought they were slightly different issues: The one you mentioned touches on the fact that it won't allow moving the picture up or down. The one I reported is regarding the initial position of the image, which starts way off its vertical "center", and is made even worse when considering the bug you mentioned where we can't move it up or down. When you add a picture from the photo library though, calling `ImagePicker.launchImageLibraryAsync()` instead, you still can't move the picture vertically, but its initial position is centered.

So I guess the question is: are these two slightly different behaviors, part of the same bug ? :
-Not being able to move the picture vertically, and
-The initial position of the picture is off when calling `ImagePicker.launchCameraAsync()` but not when calling `ImagePicker.launchImageLibraryAsync()` .

Thanks in advance.

**Comment by jbromberg** [comment]
Any updates on this? The bug occurs with both landscape and portrait photos.

**Comment by barthap** [comment]
Unfortunately, this is an iOS bug and now we can nothing to fix it 😞

**Comment by AurelienV-42** [comment]
Any updates? 🙁

**Comment by Tobjoern** [comment]
Still facing this issue in 2024
