### ISSUE TITLE
Unable to resolve "react-native" on Monorepo project

### ISSUE THREAD

**Issue by mauriciord** [expo/expo#7283]
## 🐛 Bug Report

<img width="677" alt="Screen Shot 2020-03-04 at 22 49 49" src="https://user-images.githubusercontent.com/1128701/75939948-7aeb3280-5e6a-11ea-8443-851c135d99ab.png">

I'm trying to insert an Expo application inside a monorepo project, but I get an error with React Native. I used [expo-yarn-workspaces](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces) and `metro-config`, but only the web is working. I pasted the error above.

### Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /var/folders/cg/776y_8l900qdrgww25ylv47h0000gn/T/yarn--1583372700609-0.6789692417621209/node
      Yarn: 1.21.1 - /var/folders/cg/776y_8l900qdrgww25ylv47h0000gn/T/yarn--1583372700609-0.6789692417621209/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: 36.0.2 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

It's the **managed workflow** as a package inside a monorepo project. 

### Steps to Reproduce / Reproducible Demo

- Clone https://github.com/mauriciord/golden-stack/tree/feature/expo-app
- Checkout branch `feature/expo-app`
- On the project root folder, `yarn workspace @golden-stack/expo-app start -c -i`

**you can see the edited files here:** https://github.com/FotonTech/golden-stack/pull/30

### Expected Behavior

Run at iOS Simulator successfully

### Actual Behavior
```
Opening iOS simulator
Opening exp://127.0.0.1:19000 in iOS simulator
Unable to resolve "react-native" from "../../node_modules/expo/build/Expo.fx.js"
Failed building JavaScript bundle.
```

**Comment by brentvatne** [comment]
hi! we don't provide support for configuring monorepos. this is a pretty difficult thing to set up and keep working, so you should be prepared to debug issues like this if you're going to try it. further, none of this is specific to expo -- the issues you encounter will either be a result of yarn or metro. expo doesn't do anything that would impact this.
