### ISSUE TITLE
[expo-blur] Blur no longer working and prop warnings after upgrade to expo 36/expo-blur 8

### ISSUE THREAD

**Issue by WolfyUK** [expo/expo#7290]
### Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.23 
      @types/react-native: ~0.60.23 => 0.60.31 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.13.1
```

### Steps to Reproduce

1. Initialise a bare workflow app (with TypeScript)
1. `npm i -S react-native-modal react-native-device-info`
1. `expo install expo-blur`
1. `cd ios && pod install`
1. Create a Modal.tsx component:
```tsx
import React from "react";
import { StyleSheet, TouchableWithoutFeedback, View } from "react-native";
import ReactNativeModal from "react-native-modal";

import { BlurView } from "expo-blur";

export interface ModalProps {
    open: boolean;
    children: React.ReactNode;
    onClose: () => void;
    onClosed: () => void;
}

const Modal = (props: ModalProps): JSX.Element => {
    return (
        <ReactNativeModal
            isVisible={props.open}
            onDismiss={props.onClose}
            onModalHide={props.onClosed}
            onBackdropPress={props.onClose} 
            customBackdrop={<TouchableWithoutFeedback onPress={props.onClose}>
                                <BlurView tint="dark" intensity={100} style={styles.blur} />
                            </TouchableWithoutFeedback>}
        >
            <View style={styles.modal}>
                {props.children}
            </View>
        </ReactNativeModal>
    );
};

export default Modal;

const styles = StyleSheet.create({
    modal: {
        backgroundColor: "#fff",
        padding: 30,
    },
    blur: {
        flex: 1, 
        backgroundColor: "#fff",
        opacity: 1,
        ...(StyleSheet.absoluteFill as any),
    },
}); 
```
6. Update App.tsx to trigger the modal:
```tsx
import React from "react";
import { Button, StyleSheet, Text, View } from "react-native";
import Modal from "./Modal";

export default class App extends React.Component<{}, {
    modalOpen: boolean,
    openCount: number,
    closeCount: number,
}> {
    constructor(props: {}) {
        super(props);

        this.state = {
            modalOpen: false,
            openCount: 0,
            closeCount: 0,
        }
    }

    render() {
        return (
            <>
                <View style={styles.view}>
                    <Text>
                        I should be blurred on iOS...
                    </Text>
                </View>
                <View style={styles.view}>
                    <View style={styles.view}>
                        <Button onPress={this.handleModalOpen} title="Open modal" />
                    </View>
                    <View style={styles.view}>
                        <Text>
                            openCount: {this.state.openCount}
                        </Text>
                        <Text>
                            closeCount: {this.state.closeCount}
                        </Text>
                    </View>
                </View>
                <View style={styles.view}>
                    <Text>
                        ...but &lt;BlurView&gt; has no effect on Android
                    </Text>
                </View>
                <Modal
                    open={this.state.modalOpen}
                    onClose={this.handleModalClose}
                    onClosed={this.handleModalClosed}
                >
                    <View>
                        <Text>
                            Tap the button or outside the modal to close it
                            {"\n\n"}
                        </Text>
                        <Button title="Close" onPress={this.handleModalClose} />
                    </View>
                </Modal>
            </>
        );
    }

    private handleModalOpen = () => {
        this.setState({
            modalOpen: true,
            openCount: this.state.openCount + 1,
        });
    }

    private handleModalClose = () => {
        this.setState({
            modalOpen: false,
        });
    }

    private handleModalClosed = () => {
        this.setState({
            closeCount: this.state.closeCount + 1,
        });
    }
}

const styles = StyleSheet.create({
    view: {
        flex: 1,
        backgroundColor: "#ffe",
        alignItems: "center",
        justifyContent: "center",
    },
});
```
7. Build and run the app
8. Click on the button

### Expected Behaviour

When launching the modal the background should blur on an iOS device.
This was the case when running expo 35 and expo-blur 7.

### Actual Behaviour

The background does not blur and yellow box warnings are displayed since upgrading to expo 36 and expo-blur 8:

> Error setting property 'proxiedProperties' of ViewManagerAdapter_ExpoBlurView with tag #199: Tried to set property `onClick` on view manager of view `ExpoBlurView` when the view manager does not export such prop.

and
> Error setting property 'proxiedProperties' of ViewManagerAdapter_ExpoBlurView with tag #199: Tried to set property `focusable` on view manager of view `ExpoBlurView` when the view manager does not export such prop.

### Reproducible Demo

See [this repo](https://github.com/WolfyUK/ExpoBlurIssue)

**Comment by cruzach** [comment]
Hi @WolfyUK - I made [this snack](https://snack.expo.io/@charliecruzan/adequate-scone) with your code (it's always better to include a snack link) and it seems to work the same in both SDK 35 and 36. Does this issue **only** happen in bare apps? You might want to try a minimal example of BlurView to see if that works first:

```import React from 'react';
import { Image, StyleSheet, View } from 'react-native';
import { BlurView } from 'expo-blur';
const uri = 'https://s3.amazonaws.com/exp-icon-assets/ExpoEmptyManifest_192.png';

export default function App() {
  return (
    <View style={styles.container}>
      <Image style={{ width: 192, height: 192 }} source={{ uri }} />

      {/* Adjust the tint and intensity */}
      <BlurView tint="light" intensity={50} style={styles.notBlurred}>
        <Image style={{ width: 96, height: 96 }} source={{ uri }} />
      </BlurView>
    </View>
  );
}```

**Comment by WolfyUK** [comment]
Thanks for looking into this for me, @cruzach. This does now seem to be working in my managed app (in the updated repo above) but the warnings still persist. These warnings are not generated in a bare Expo app. Do they mean anything to you, or is it likely to be something to do with the `react-native-modal` package?

**Comment by cruzach** [comment]
I'm not sure I follow, the same example works in managed workflow but has the warnings you shared, but in the bare workflow it does not work but displays no warnings?

**Comment by WolfyUK** [comment]
Sorry for the confusion. The example works in both managed and bare workflows but in the bare workflow the warnings are present.

**Comment by cruzach** [comment]
What version of `expo-blur`?

**Comment by alexmady** [comment]
I am seeing this too.

**Comment by brentvatne** [comment]
hello! please provide a mcve: https://stackoverflow.com/help/mcve

**Comment by danilo900** [comment]
My blur only works on the first app draw.
So, what's behind the Container in the moment stay there.

Sdk 37
 "expo-blur": "~8.1.0",

**Comment by lindboe** [comment]
In case it helps: we came across the same issue with expo-linear-gradient.

The issue is wrapping with `TouchableWithoutFeedback`. As [the docs](https://reactnative.dev/docs/touchablewithoutfeedback) say, "TouchableWithoutFeedback works by cloning its child and applying responder props to it." TouchableWithoutFeedback, at least in our case, was then applying `onClick` and `focusable` to its `LinearGradient` child, which doesn't have those as props, due to the way expo's react-native-adapter proxies properties to the custom expo unimodule view manager: https://github.com/expo/expo/blob/master/packages/%40unimodules/react-native-adapter/src/NativeViewManagerAdapter.tsx#L10-L13.

I'm a little fuzzy on the rest, but the reason this errors on iOS only appears to be because according to ViewPropTypes, `onClick` and `focusable` are legitimate props for Android but not for iOS: https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewPropTypes.js.

**Comment by Commoddity** [comment]
> Edit: can confirm I was able to fix this by wrapping `LinearGradient` in a View. The view gets the cloning, and expo's native component no longer gets incorrect props passed to it.

Worked for me. Was getting warnings like `Tried to set property `area` on view manager of view `ExpoLinearGradient` when the view manager does not export such prop.` with a bunch of vars: area, ticks, y, data, etc. Warnings had been driving me nuts. Thanks for such a simple solution
