### ISSUE TITLE
unexpected token issue in expo-google-app-auth using sdk 36

### ISSUE THREAD

**Issue by reactexcel** [expo/expo#7291]
const { type, accessToken, user } = await Google.logInAsync({
        androidClientId:
          "275822838025-lme2ds3v218pr4mipn0kk8nk6n8nou2t.apps.googleusercontent.com",
        scopes: ["profile", "email"],
      });

getting error of **errorUnexpected token o in JSON at position 1**

also when using 
authState = await AppAuth.authAsync(config); //getting token its working fine
await fetch(`https://graph.facebook.com/me?access_token=$authState.{accessToken}`);
getting same issue please help
Thanks in advanced.

**Comment by brentvatne** [comment]
hi! you can post to https://forums.expo.io to get help. the issues are meant for bug report, and it's not clear from the code that you have provided that you are encountering a bug (it may be an issue in your own code/config).
