### ISSUE TITLE
Build stuck for days. 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#730]
![image](https://user-images.githubusercontent.com/1026325/31238610-7a8e2de6-a9c8-11e7-9a69-ee96a733bf60.png)

**Comment by davepack** [comment]
Can you copy and paste the result of `exp build:status`?

**Comment by jpca999** [comment]
it says there was error in the build

**Comment by jimmylee** [comment]
Hey @jpca999 what is the build id?

**Comment by jpca999** [comment]
I don’t know how to get it. 

All I can do is build status that doesn’t provide me with the id.

**Comment by jimmylee** [comment]
Alright well I went and got your username `libertytrust` and I found your project that stalled out, so I'm going to cancel that build for https://expo.io/@libertytrust/recherry

**Comment by quinlanj** [comment]
hey @jpca999 , im going to close this issue, since it has appeared to be resolved by @jimmylee . Please let us know by posting on the forums if your build runs into any additional issues.
