### ISSUE TITLE
Android build error could not load app. hostUri exp.host vs expo.io

### ISSUE THREAD

**Issue by josmas** [expo/expo#7304]
### Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.11.7

The problem happens in an ExpoKit app, but only on Android, iOS works fine.

### Steps to Reproduce

This is not a new app, it has been working for months. Since last Thursday/Friday (March 5) the android build crashes on start. It builds and installs fine, but it crashes with the following error:

`    --------- beginning of crash
2020-03-06 14:22:15.767 13962-13962/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.user.appname, PID: 13962
    java.lang.RuntimeException: Expo encountered a fatal error: Could not load app.
        at host.exp.exponent.experience.a$2.run(BaseExperienceActivity.java:206)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

We can also see:
`E/c: Error fetching cached manifest, falling back to default timeout: java.io.IOException: No hard coded response found`

Which seems to indicate that either the bundle is not available locally, or/and cannot be found with a network call?

I do realise this is not reproducible and it can be on our end, but it basically stopped working overnight. We decompiled two builds out of the same sources, one from before it stopped working, and a new one, and these are the only differences:
<img width="500" alt="one" src="https://user-images.githubusercontent.com/194925/76164734-14576480-6149-11ea-8ccd-707371c0e90e.png">
<img width="502" alt="two" src="https://user-images.githubusercontent.com/194925/76164742-1a4d4580-6149-11ea-96e1-73b6c907d668.png">

We can also see that the hostUri also changes in the same way`"hostUri": "exp.host/@user/app` and the other one is `"hostUri": "expo.io/@user/app`.

Furthermore, if we change the value of _publishedUrl_ in MainActivity.java, we can get the app to open. The change is from:
`@Override
  public String publishedUrl() {
    return "exp://exp.host/@our_user/our_app";
  }`

to 
`@Override
  public String publishedUrl() {
    return "https://expo.io/@our_user/our_app";
  }`

Note that we are using the correct user and app name, just changed them here to report.

We have also tried changing the return to `"exp://expo.io/@our_user/our_app"` but that also crashes on start.

So changing the url to `https://expo.io/` seems to make the app work, but we are concerned that with this change our users won't be able to access the bundle if they are not online, not being able to finish up the app install correctly; would that be a correct assumption?

Could you please advise if the change will have any consequences we are not foreseeing, and also if you know anything about any changes from Tue March 3 2020 to Thursday March 5 that might be causing such change in the `expo publish` output? We haven't upgraded the cli or made any other changes. The issue is consistent no matter where we build, locally mac and linux, and on Cloud Build for our ci system. Same results in all of them.

Just to clarify, we cannot reproduce with a brand new expokit app, which works just fine with no modifications to `return "exp://exp.host/@user/app`.

**Comment by tecshogo** [comment]
>The problem happens in an ExpoKit app, but only on Android, iOS works fine.
>if you know anything about any changes from Tue March 3 2020 to Thursday March 5 that might be causing such change in the expo publish output? We haven't upgraded the cli or made any other changes

Same situation

**Comment by cruzach** [comment]
Hi, thanks for reporting this! It looks like we've changed the result url from `expo publish` from exp.host --> expo.io, like you found out in your investigation. We're looking into fixing this ASAP, so we'll keep you updated here

**Comment by ide** [comment]
@josmas we've deployed an update that uses exp.host as the host in the URLs again. If this works for you now, we'll close this out.

**Comment by SamyOptimize** [comment]
> @josmas we've deployed an update that uses exp.host as the host in the URLs again. If this works for you now, we'll close this out.

@ide Can you please advise on where the update is? is it expo-cli, expo or expokit? We're facing a similar issue as well [#7314 ](https://github.com/expo/expo/issues/7314)

**Comment by ide** [comment]
The update was server-side so that when you publish your project, the server sends back a URL with `https://exp.host` instead of `https://expo.io` as the origin.

**Comment by SamyOptimize** [comment]
Thanks! the issue has been fixed for us too.

**Comment by josmas** [comment]
thanks @idle that seems to fix it for us too. Thanks for the prompt reply and fix!

**Comment by bedynamic** [comment]
hi, sorry for maybe hijacking this issue, but it seems (at least for me) that this could be a reason for my probem, that the iOS Version of my app (sdk 27.0.0, expo-cli 2.2.0) does not reload any new published versions since April. It worked for over 100 releases before. But all new releases aren't catched anymore. I am totally stuck. Any help appreciated. Maybe it has to do with a wrong manifest.url. On a fresh install the initial js files will never be updated.
