### ISSUE TITLE
Include the newest TextInput bug fix in RN 0.62.x into the upcoming SDK37?

### ISSUE THREAD

**Issue by christtrc** [expo/expo#7305]
## 🐛 Bug Report

There is a bug in the react native framework which related to [[Android] selection works incorrect and crashes in TextInput component #26047](https://github.com/facebook/react-native/issues/26047)  and [Changing TextInput selection after setting text crash #25265](https://github.com/facebook/react-native/issues/25265). 

And also there is a PR [Cap selection indices when text changes #26680](https://github.com/facebook/react-native/pull/26680) have been merged to 0.62.x branch. 

Could you please include this bug fix to the upcoming EXPO SDK 37 release ?

**Comment by tsapeta** [comment]
Yeah @christtrc, thanks for letting us know about this bugfix! I'm now cherry-picking this commit to our react-native fork, however keep that in mind we will still use React Native in version `0.61.4` but with some bugfixes cherry-picked from 0.62.x
