### ISSUE TITLE
google signin doesn't work on expo app, and no where in docs says how to fix it

### ISSUE THREAD

**Issue by TylerSustare** [expo/expo#7307]
https://docs.expo.io/versions/latest/sdk/google-sign-in/

[Unhandled promise rejection: Invariant Violation: expo-google-sign-in is not supported in the Expo Client because a custom URL scheme is required at build time. Please refer to the docs for usage outside of Expo www.npmjs.com/package/expo-google-sign-in]

The docs say `To use Google authentication in the Expo client, check out Google or AppAuth.` which seems like a rabbit hole, not really showing how to test this outside of expo

**Comment by cruzach** [comment]
I think I see what's confusing here. When we say to "check out Google or AppAuth," we're referring to `expo-google-appa-auth`, not `expo-google-sign-in`

 [`expo-google-sign-in`](https://docs.expo.io/versions/latest/sdk/google-sign-in/) is for standalone apps (meaning once you've built with `expo build:[android | ios]`)

If you want to test google authentication in the Expo client app, then you can use either the [`expo-app-auth`](https://docs.expo.io/versions/latest/sdk/app-auth/) module or [`expo-google-app-auth`](https://docs.expo.io/versions/latest/sdk/google/)

**Comment by ndipenoch** [comment]
I followed the doc : https://docs.expo.io/versions/latest/sdk/google-sign-in/

I have a stand  alone app running on iOS.

Everything works fine for both Google and Facebook sign on Expo on multiple devices .
But when I submit on TestFlight Google sign in doesn't work. I click the button nothing happens, no error message and I am not routed to the Google sign in web page.
From this line of code const { URLSchemes } = AppAuth;
I can get my REVERSED_CLIENT_ID like said in the doc.

A snippet from my app.json

********app.json********
 "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "***",
      "buildNumber": "1.1.4",
      "infoPlist": {
        "NSPhotoLibraryUsageDescription": "Hello............",
        "NSCameraUsageDescription": "hello......................"
      },
      "config": {
        "googleSignIn": {
          "reservedClientId": "****"
        }},
        "googleServicesFile": "./GoogleService-Info.plist"
    }
    

Any ideas/suggestions why this is happening ?

**Comment by michaelsatumba** [comment]
Hello I have the same exact problem! My app works perfectly on expo but when on testflight - the sign in does not do anything at all - has anyone solved this issue?
