### ISSUE TITLE
Unfortunately, Expo has stopped

### ISSUE THREAD

**Issue by scotttharvey** [expo/expo#731]
My app loads and functions on iOS, but on Android the expo app is crashing. On Android I can load the landing, login, signup screens, but when firing login function the expo app quits and gives error "Unfortunately, Expo has stopped". However the sign-up function is working properly.

**Comment by UladzislauCharneny** [comment]
Got the same issue

**Comment by scotttharvey** [comment]
Are you using React native router flux?

**Comment by davepack** [comment]
We'll continue discussion on the forums here: https://forums.expo.io/t/unfortunately-expo-has-stopped/3614

**Comment by anil1712** [comment]
Anyone got any solution ? I am getting the same issue.
I got this in my cli console

```
..............
:app:installDevDebug
Installing APK 'app-dev-debug.apk' on 'SM-G610F - 7.0' for app:devDebug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 3 mins 37.821 secs
Starting: Intent { cmp=host.exp.exponent/.LauncherActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
```

But when I try to run the app in my device I got the popup “Sample Expo App has stopped … Close app”
Then it got closed.
