### ISSUE TITLE
Fast refresh and console.log doesn't work for our project

### ISSUE THREAD

**Issue by TheGreatMarkus** [expo/expo#7310]
### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    npmGlobalPackages:
      expo-cli: 3.13.1

### Steps to Reproduce

These steps were reproduced on a Ubuntu computer, a Windows computer, and on a fresh install of Ubuntu on a VM to account for differences in the environment.

1. Clone the Github Repo:
   * `git clone https://github.com/RGPosadas/WayFinder.git`
2. Run `npm install && npm start`
3. Open the application on Android phone through USB connection or the QR code.

4. Modify visible parts of the UI and save the file to trigger the Fast Refresh.
   * Example. go to`src/components/campus-toggle/campus-toggle.component.tsx`, modify the text `SGW` and save the file
5. Put some console.logs before the return statement in app.tsx and save the file to have logs showing up in the terminal.

### Expected Behavior

* Fast Refresh would occur on save and console.logs would show up in the terminal.

### Actual Behavior

* Fast Refresh doesn't occur and console.logs don't show up in the terminal.

Essentially, two major features for development don't seem to work for us. This issue appeared randomly after a few weeks into development and we failed to identify what could possibly cause this.

A workaround for now is to use the debugger and manual refresh.

A weird fix to the issue that works some of the time is to `expo init` another blank project, run it, and then copy the file for our project into the folder on the newly created blank project.

We are really curious to know what the issue could be and hope someone could help us, since this bug has been annoying us for some time now.

### Reproducible Demo

please have a look at our project for which we are having this issue and follow the steps given in the section `Steps to Reproduce`:
* `git clone https://github.com/RGPosadas/WayFinder.git`

**Comment by cruzach** [comment]
`console.log` worked for me after cloning your repo, so this probably has to do with your local environment. Can you make sure you're not running this in production mode? 

Otherwise, it's best to share a minimal reproducible demo, since just sharing your entire project has so many variables to it that it can be much harder to track down the source of the problem. Once you are able to reproduce this in a blank `expo init` project, then please an open an issue at the [`expo-cli` repo](https://github.com/expo/expo-cli/issues)

**Comment by TheGreatMarkus** [comment]
No, I was not running in prod mode.

Did fast refresh also work when you cloned the repo?

I don't think it's my local environment since I ran the very same project on a fresh installation of ubuntu, just installing the latest versions or npm and expo-cli, and ran into the same issue. I might have been my phone, but I've uninstalled or cleared the cache on my device every single time before testing.

I would love to share a "minimal reproducible demo" on a "blank project", but I barely understand what causes the issue, let alone what needs to be done to reproduce the same behavior for other projects other than our own.

At this point, it's not a major hindrance, but the issue is so weird and hard to reproduce that I'm desperate to know what could possibly the cause.

**Comment by TheGreatMarkus** [comment]
Another possible reason might be debugging. Does debugging disable fast refresh and/or logs to the terminal? I think the issue started appearing when I learned about shaking my phone to open the debugger.

I notice that my bundleUrl in the logs is: "http://192.168.1.23:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false"

Hot is set to false, might that have to do with anything?

**Comment by cruzach** [comment]
> Hot is set to false

You may need to update your version of the Expo client app, Hot reloading should no longer be an option

**Comment by TheGreatMarkus** [comment]
The expo app on my phone is currently on the latest version. I've looked into updating it through `expo update` and the google play store.

As for debugging, I've tried to trigger fast reload with and without debugging. What I mean to say is that I think the issue has manifested ever since I first started using the remote debugger. Maybe enabling it caused some weird change in the settings or cache that I can't seem to revert.

You didn't answer my question:
> Did fast refresh also work when you cloned the repo?
But I'm assuming it works for you since you closed the bug. At least I know that something might be wrong with my setup, despite my efforts to clean/reset everything. In any case, I opened the bug to get some more information on what could be the cause of the issue, since it was driving me crazy for a while. Thanks for at least replying.

**Comment by TheGreatMarkus** [comment]
Well the issue suddenly went away after changing absolutely nothing about my setup. I just came into work this morning and everything just worked, when it didn't last night.

I guess its just a random bug that probably won't be fixed anytime soon.
