### ISSUE TITLE
[Questions] Want to use Linking.openURL to open expo developement app after ejecting project

### ISSUE THREAD

**Issue by deniske** [expo/expo#7311]
I am trying to use Linking.openURL to open expo development project(exp://localhost:19000). Is there possible to use this method to launch expo app like expo client? 

Thanks

**Comment by cruzach** [comment]
Yes, it's possible! We have documentation for using the `Linking` module in all environments here https://docs.expo.io/versions/latest/workflow/linking/

**Comment by deniske** [comment]
But the app did not work when i used Linking.openURL to launch my another app. Would I need to set some configure on AndroidManifest.xml or MainActivity.java ?
Thanks.

**Comment by cruzach** [comment]
No, you shouldn't need to make any changes to those files in the managed workflow

**Comment by deniske** [comment]
OK, I will read document again and implement Linking.openURL and Linking.makeURL to try to launch my development app with my ejecting app.

I truly appreciate your reply. 
Thanks @cruzach .

**Comment by deniske** [comment]
Hi @cruzach ,
     I followed link https://docs.expo.io/versions/latest/workflow/linking/ to try to open my development app.

     Following is my steps,
     1. Launch my first app which is ejected by expo eject. And run expo start to launch 
         my first app on exp://localhost:19000
     2. Launch my second app on exp://localhost:19004
     3. Implement Linking.openUrl("exp://localhost:190004") to try to open my second app.
 
      But my first app did not work to open my development app when I pressed the button which triggered  Linking.openUrl
  
      Did I miss steps to try to open my second project?

Thanks.
