### ISSUE TITLE
Only getting the "Unhandled promise rejection: Error: Error with Facebook login" error.

### ISSUE THREAD

**Issue by korabdrg** [expo/expo#7312]
The Facebook login used to work perfectly until the client tested it. 
All the error is saying is "Error with Facebook login". 

Here's my code:
logInWithFacebook = async () => {
    try {
      await Facebook.initializeAsync('1698937670237480');
      const {
        type,
        token
      } = await Facebook.logInWithReadPermissionsAsync("1698937670237480", {
        permissions: ['public_profile', 'email']
      });
      const fbResponse = await Facebook.logInWithReadPermissionsAsync("1698937670237480",{
        permissions: ['public_profile', 'email']
      });
      if (type === "success") {
        this.props.signInWithFacebook(token, this.afterFbLogin.bind(this))
      } else {
      }
    } catch ({ message }) {
      alert(`Facebook Login Error: ${message}`);
    }
  };

**Comment by cruzach** [comment]
Closing since this isn't a valid bug report. If you're looking for general help, I recommend  looking at our [documentation](https://docs.expo.io/versions/latest/sdk/facebook/), and posting on our [forums](https://forums.expo.io/)
