### ISSUE TITLE
ImageManipulator.manipulateAsync with rotate option creates white border around the image

### ISSUE THREAD

**Issue by sezginriggs** [expo/expo#7325]
### Environment

Bare expo with following versions;
expo-image-manipulator 8.1.0
react-native-unimodules 0.8.0

Occurs on ios 13.3.1, Android 9 seems fine.

### Steps to Reproduce

When I rotate an image with manipulateAsync(), it creates a white border around the image.

Here is my code snippet

`        const rotateResult = await ImageManipulator.manipulateAsync(
            this.state.photoPreviewImageUri,
            [{ rotate: 90 }],
            { compress: 1, format: ImageManipulator.SaveFormat.JPEG }
        );`

### Expected Behavior

Rotated image without any white border

**Comment by cruzach** [comment]
Hi! Can you provide a repro for this (a Snack works perfect, even if this only occurs in the bare workflow)

It looks like you're using the `next` version of unimodules. Does the same thing happen when using v0.7.0?

**Comment by sezginriggs** [comment]
@cruzach Hi! I was using 0.7.0-rc.4 before upgrading to 0.8.0 and now tried with 0.7.0 and same thing happens.

Here is the Snack example: https://snack.expo.io/ry1A5jvHU

But here it doesn't create any border, it uses the same code but just loads image from local instead of camera/camera roll. Couldn't understand what might be the difference.

**Comment by cruzach** [comment]
Not sure, but you can use `ImagePicker` to get an image from the camera roll

**Comment by sezginriggs** [comment]
@cruzach I've updated the code on Snack, now I can reproduce the border problem.

Here you can access the code: https://snack.expo.io/Hk3PqpPr8

Please select a dark/black photo from gallery, or take some dark photo with camera and rotate it for 10-20 times, you will see a border will appear and border width will increase with each rotation.

**Comment by akempe** [comment]
This issue is in the `rotateImage` function due to floating point rounding by core graphics where the rotated width/height get rounded up.

```
CGAffineTransform t = CGAffineTransformMakeRotation(rads);
rotatedViewBox.transform = t;
CGSize rotatedSize = rotatedViewBox.frame.size;

UIGraphicsBeginImageContext(rotatedSize);
```

The `rotatedSize.width` and `rotatedSize.Height` need to be rounded before calling `UIGraphicsBeginImageContext(rotatedSize);`

**Comment by chhauss-a** [comment]
I still have that issue in `expo-image-manipulator 9.2.2`.
Rotating the image (by 90deg in my case) creates a white boarder. My current workaround is to crop the white boarder

```
[
    { rotate: rotation },
    crop: {
        originX: 0,
        originY: 0,
        width: imageSize.height - 1,
        height: imageSize.width - 1,
    },
]
```

Negative side-effect is that the image is shrinking by 1px on every rotation.

**Comment by adscud** [comment]
Any news after 1 year ?

**Comment by akempe** [comment]
@adscud the fix I mention has been in production with us for 2 years. @cruzach you can take my code above and it will fix this issue.

**Comment by GuillaumeHemmen** [comment]
it's too easy to automatically close pending issues even if stale...
