### ISSUE TITLE
how to get Camera.js tests running in bare-expo?

### ISSUE THREAD

**Issue by wolverineks** [expo/expo#7329]
### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.13.1

### Steps to Reproduce

fork repo
clone repo
`yarn setup:native`
`cd apps/bare-expo`
`yarn android`

### Expected Behavior

app runs on device with camera tests available

### Actual Behavior

app runs on device without camera tests

### Reproducible Demo

N/A

### Other Information

* this issue refers to expo/expo/apps/bare-expo, and not a "non-managed" expo app
* camera tests are available when running test-suite with `expo start`
* this commit](https://github.com/expo/expo/commit/dc814a6b86b23bc80c8ca78b6579f2e3c6b42abc#diff-225580c4eddce6fbc51d58127b6e3219) throws camera tests on the ground when CameraScreen throws an error
* mucking about, i could get as far as `Could not find com.google.android:cameraview:1.0.0` (even after including [this code](https://github.com/expo/expo/issues/3639))

**Comment by wolverineks** [comment]
i was able to get the tests to run by copying the maven folder from `/packages/expo-camera` directly into `apps/bare-expo/android`, and removing `expo-camera` and `unimodules-face-detector-interface` from `apps/bare-expo/package.json#excludedUnimodules`

what are the implications of this?

**Comment by imdanielpiva** [comment]
What is about the `com.google.android:cameraview:1.0.0`?

I just ejected an app from Managed Workflow (SDK37) to ExpoKit and when I run `./gradlew assembleDebug` or `./gradlew installDebug` I get this error:

```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.android:cameraview:1.0.0.
     Required by:
         project :app > project :expo-camera
```

**Comment by wolverineks** [comment]
> Do you anything related to `com.google.android:cameraview:1.0.0` that could be the problem @wolverineks?
> 
> I just ejected an app from Managed Workflow (SDK37) to ExpoKit and when I run `./gradlew assembleDebug` or `./gradlew installDebug` I get this error:
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
>    > Could not find com.google.android:cameraview:1.0.0.
>      Required by:
>          project :app > project :expo-camera
> ```

im not sure what youre asking, but this thread is about a specific app, not expo-camera in general

**Comment by imdanielpiva** [comment]
I missed the *know* word in the sentence, sorry, @wolverineks 😁

But thank you for clarify this. I thought that the problem with `com.google.android:cameraview:1.0.0` could be (still might be though) related to mine, I was just looking for a clue for what/where to debug.
