### ISSUE TITLE
App crashes after upgrading expo from 30 to 36

### ISSUE THREAD

**Issue by ektasahu027** [expo/expo#7347]
I updated my expo SDK from 35 to 36. Android build does not work on android x versions. The application gives error after the 
![Screenshot 1398-12-21 at 14 58 56](https://user-images.githubusercontent.com/41745899/76493976-e9775400-6459-11ea-8b12-6c7d054e4fa9.png)
splash screen. "Application keeps stopping". and no error.

While I am on the development mode my expo app works fine but once I build it crashes.

**Here is my package.json**

"dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "expo": "^36.0.2",
    "expo-asset": "^8.0.0",
    "expo-blur": "^8.0.0",
    "expo-file-system": "^8.0.0",
    "expo-font": "^8.0.0",
    "expo-linear-gradient": "^8.0.0",
    "expokit": "^36.0.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-callkit": "^1.3.4",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^0.19.1",
    "react-native-fullwidth-image": "^0.1.3",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-read-more-text": "^1.1.2",
}

**My app.json**

{
  "expo": {
    "name": "",
    "slug": "",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/icon.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "fallbackToCacheTimeout": 5000
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "userInterfaceStyle": "automatic",
      "supportsTablet": true,
      "bundleIdentifier": "....",
      "publishBundlePath": "ios/.../Supporting/shell-app.bundle",
      "publishManifestPath": "ios/...../Supporting/shell-app-manifest.json"
    },
    "isDetached": true,
    "detach": {
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.14.3-sdk36.0.0-00f587c0-b8c9-4b6b-88f6-2ccd4f20dc9c.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.14.2-sdk36.0.0-ce7e16db-fd5d-4fdd-bdeb-701ba94a04d1.tar.gz"
    },
    "scheme": "expad11b0ff7c8d4457a3fe2b129faeeb1c",
    "android": {
      "package": ".....",
      "googleServicesFile": "./google-services.json",
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    }
  }
}

**Comment by brentvatne** [comment]
hi! we can't provide support for issues that can't be reproduced with a  https://stackoverflow.com/help/mcve. sdk 30 to 36 is a big jump and it will likely take some debugging on your end to deal with this. when you eject your app you are taking on a lot more responsibility.

you could try deleting the ios/android directories and ejecting again with sdk36, then add back your native changes afterwards.

**Comment by ektasahu027** [comment]
@brentvatne Thanks for the suggestion and once I eject again with sdk36, then add back your native changes and make a release build it's working fine without any crashes.
