### ISSUE TITLE
[Questions] Can not open expo development app after ejecting project which implementing Linking.openURL

### ISSUE THREAD

**Issue by deniske** [expo/expo#7348]
Hi everyone,

     I followed link https://docs.expo.io/versions/latest/workflow/linking/ to try to open my development app.

 Following is my steps,
 1. Launch my first app which is ejected by expo eject. And run expo start to launch 
     my first app on exp://localhost:19000
 2. Launch my second app on exp://localhost:19004
 3. Implement Linking.openUrl("exp://localhost:190004") to try to open my second app.

  But my first app did not work to open my development app when I pressed the button which triggered  Linking.openUrl

  Did I miss steps to try to open my second project?
Thanks.
(This issue is similar with #7311 )

**Comment by cruzach** [comment]
Hi again @deniske , we reserve Github for bug reports, and suggest using our [Forums](https://forums.expo.io/) for general questions like this. You may want to try visiting the URL in your OS browser on the device and see if that opens up the correct experience, to make sure there are no issues there
