### ISSUE TITLE
barCodeTypes is ignored on Android when type prop is specified on the BarCodeScanner

### ISSUE THREAD

**Issue by r3b311i0n** [expo/expo#7352]
## 🐛 Bug Report

Limiting barcode types in `expo-barcode-scanner` using `barCodeTypes` doesn't work on Android (iOS works fine) when `type={BarCodeScanner.Constants.Type.back}` is specified.

### Environment

```
  Expo CLI 3.13.2 environment info:
    System:
      OS: Linux 5.5 Arch Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.2
```

Targets: iOS, Android

### Steps to Reproduce

Scan a QR code with `barCodeTypes` set to `BarCodeScanner.Constants.BarCodeType.ean13` and `type` set to `BarCodeScanner.Constants.Type.back` with an Android device after reloading the app.

barcodeScanner:

```
<BarCodeScanner
    type={BarCodeScanner.Constants.Type.back}
    onBarCodeScanned={scanned ? undefined : handleBarcodeScanned}
    barCodeTypes={[BarCodeScanner.Constants.BarCodeType.ean13]}
    style={StyleSheet.absoluteFillObject}
/>
```

### Expected Behavior

Only `ean13` barcodes are scanned on both Android and iOS.

### Actual Behavior

Non `ean13` barcodes are scanned on Android.

**Comment by cruzach** [comment]
Hi! I tried to repro this with [this snack](https://snack.expo.io/@charliecruzan/dce5e1) by trying to scan QR codes, but it wouldn't scan them. Could you provide a full repro?

**Comment by r3b311i0n** [comment]
Hey, thanks for the response. I managed to reproduce it with your snack by adding `type={BarCodeScanner.Constants.Type.back}` and reloading the app.

**Comment by lukmccall** [comment]
Hi @r3b311i0n. Unfortunately, I couldn't reproduce this bug. Could you provide more information? Like your Android version, device model, which code you were able to scan by `adding type={BarCodeScanner.Constants.Type.back}`?

Also, I've assumed that your using SDK 36. Could you test it on SDK 37?

**Comment by tirmey** [comment]
Hello, 

I have the same issue in expo 37.0.3. Even setting the barCodeTypes prop to `[BarCodeScanner.Constants.BarCodeType.qr]`, the scanner can recognize other code types (QRCode, at least).

**Comment by lukmccall** [comment]
Hi @tirmey, which iOS do you use?

**Comment by r3b311i0n** [comment]
Apologies. I kind of forgot about this issue. I updated to expo 37.0.0 and specifying `type` works for me now (also works without `type` specified).
