### ISSUE TITLE
[mailcomposer][ios] Unable to attach a `.db` file

### ISSUE THREAD

**Issue by ghost** [expo/expo#7353]
### Environment

  Expo CLI 3.13.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.0 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ~4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.13.6

SDK Version: 36
Platforms: iOS

### Steps to Reproduce

This is the code:

let emailResult = await MailComposer.composeAsync({
    recipients: ['test@demoit'],
    subject: "DEBUG",
    body: "Test",
    attachments: [file:///var/mobile/Containers/Data/Application/C1C6646C-8F10-489F-A4BB-FBCDAAA997F7/Documents/ExponentExperienceData/%2540mgiorgi%252Fapp/SQLite/app.db]
});

### Expected Behavior

Open Mail app with app.db as attachment

### Actual Behavior

`An exception was thrown while calling ExpoMailComposer.composeAsync with arguments ( { attachments = ( "file:///var/mobile/Containers/Data/Application/C1C6646C-8F10-489F-A4BB-FBCDAAA997F7/Documents/ExponentExperienceData/%2540mgiorgi%252Fapp/SQLite/app.db" ); body = "Text"; recipients = ( "email@email.it" ); subject = "DEBUG"; } ): *** -[NSPlaceholderString initWithString:]: nil argument`

### 

I’ve tryed to copy the file from documentDirectory to cacheDirectory directory but the result is the same… the file exist but the Mail app can’t retrive the file as attachment

Thanks

**Comment by cruzach** [comment]
This probably has to do with the attachment (it should be a string, but I think that's just a typo in your ticket)

Here's an example that works to help you debug - https://snack.expo.io/@charliecruzan/bad-cheese

**Comment by mgiorgi-github** [comment]
The attachments is a string... is the path of file into downloadFolder folder:

attachments: [file:///var/mobile/Containers/Data/Application/C1C6646C-8F10-489F-A4BB-FBCDAAA997F7/Documents/ExponentExperienceData/%2540mgiorgi%252Fapp/SQLite/app.db]

What is wrong?

**Comment by cruzach** [comment]
see the example I shared above 😄

**Comment by mgiorgi-github** [comment]
The problem is the file extension, i've a sqlite db...
https://snack.expo.io/@mgiorgi/bad-cheese-2
I've change small.mp4 to small.db and the error reappears...
I've created metro.config.js too file but the result is the same:





*module.exports = {    resolver: {        assetExts: ["jpg", "png", "ttf",
"db", "sqlite"]    }}*

How can fix it? On Android all work fine
Thanks

Il giorno ven 13 mar 2020 alle ore 16:27 Charlie Cruzan <
notifications@github.com> ha scritto:

**Comment by cruzach** [comment]
Hm.. it might be worth making sure that the Mail app on iOS allows you to attach `.db` file types

**Comment by mgiorgi-github** [comment]
I‘ ve send an email from my iPhone and the attachment was sent fine


Inviato da iPhone

**Comment by cruzach** [comment]
Okay, thanks for checking! We'll look into this once we can, but as we're pretty focused on our upcoming SDK release, it may take some time. If you'd like to dig into this and debug why this might be happening further, that'd be awesome!

**Comment by mgiorgi-github** [comment]
Hi, news about this issue?
Thanks
