### ISSUE TITLE
EXGL: EXGL: gl.pixelStorei() doesn't support this parameter yet!

### ISSUE THREAD

**Issue by huyhomie66** [expo/expo#7359]
Expo Gl submodule can't run in simulator ios react native

**Comment by cruzach** [comment]
From the [source](https://github.com/expo/expo/blob/d8c4a4f298a00216e26ce844faeaa0efe1d7175f/packages/expo-gl-cpp/cpp/EXGLNativeMethods.cpp#L268) it looks like EXGL only supports the `gl.UNPACK_FLIP_Y_WEBGL` param right now

Closing as this isn't a valid bug report

**Comment by Joshandrews43** [comment]
Hi!

I am also getting this error in production using SDK 39.0.0 and the latest version of expo-gl.


Any ideas? It is causing my app to crash.

**Comment by 3GOMESz** [comment]
> From the [source](https://github.com/expo/expo/blob/d8c4a4f298a00216e26ce844faeaa0efe1d7175f/packages/expo-gl-cpp/cpp/EXGLNativeMethods.cpp#L268) it looks like EXGL only supports the `gl.UNPACK_FLIP_Y_WEBGL` param right now
> 
> Closing as this isn't a valid bug report

Not crashing but https://github.com/expo/expo-three/issues/196
