### ISSUE TITLE
Background Location has not been configured when running on expo client

### ISSUE THREAD

**Issue by vitorsilvalima** [expo/expo#7368]
### Environment
Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.18 => 4.1.18
      @types/react: 16.9.16 => 16.9.16
      @types/react-native: 0.60.24 => 0.60.24
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10

Running on a real device using Expo Client

### Steps to Reproduce

1- Put the following config in your app.json
"ios": {
    "infoPlist": {
        "UIBackgroundModes": [
		"location",
		"fetch"
	]
2 - define a task and then call Location.startLocationUpdatesAsync
### Expected Behavior

It should start receiving the background location info

### Actual Behavior
It throws an error with the following message:
```
Background Location has not been configured. To enable it, add `location` to `UIBackgroundModes` in Info.plist file.

Stack trace:
  node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:15:52 in moduleName.methodInfo.name
  node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:271:30 in invoke
  node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:135:28 in invoke
  node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
  node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
  node_modules/promise/setimmediate/core.js:200:23 in doResolve
  node_modules/promise/setimmediate/core.js:66:12 in Promise
  node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
  node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
  node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
  node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:10:62 in moduleName.methodInfo.name
  node_modules/expo-location/build/Location.js:331:49 in startLocationUpdatesAsync
  node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:271:30 in invoke
  node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:135:28 in invoke
  node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
  node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
  node_modules/promise/setimmediate/core.js:200:23 in doResolve
  node_modules/promise/setimmediate/core.js:66:12 in Promise
  node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
  node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
  node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
  node_modules/expo-location/build/Location.js:329:7 in startLocationUpdatesAsync
  src/screens/app/VisitDetail/index.js:80:20 in VisitDetail#startBackground
  node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:271:30 in invoke
  node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:135:28 in invoke
  node_modules/regenerator-runtime/runtime.js:145:19 in Promise.resolve.then$argument_0
  node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
  node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
  [native code]:null in callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
  [native code]:null in flushedQueue
  [native code]:null in invokeCallbackAndReturnFlushedQueue
  ...
```

**Comment by cassiodezotti** [comment]
Hi, whats up? How did you solve that ?

**Comment by mehmetsalihakcan** [comment]
Hi, i have same problem.How you solve this issue?

**Comment by rfink** [comment]
Same problem

**Comment by brentvatne** [comment]
this is documented here: https://docs.expo.io/versions/latest/sdk/task-manager/#configuration-for-standalone-apps

we don't ship it with the app store client because apple is quite strict on this permission

**Comment by Manfrin92** [comment]
> this is documented here: https://docs.expo.io/versions/latest/sdk/task-manager/#configuration-for-standalone-apps
> 
> we don't ship it with the app store client because apple is quite strict on this permission

I didn't get it. I did this configuration and vitorsilvalima also did it as is stated in the "Steps to Reproduce".

**Comment by brentvatne** [comment]
@Manfrin92 - you built a custom expo client?

> TaskManager works out of the box in the Expo client on Android, but on iOS you'll need to test using a custom Expo client.

**Comment by Manfrin92** [comment]
> uilt a custom expo client

Actually I'm not sure. I just ran into my phone using the expo app.
