### ISSUE TITLE
expo web public folder

### ISSUE THREAD

**Issue by zeitamin** [expo/expo#7369]
I want to set CSS background-image to adjust related background-position and background-size in an expo project. I can't use require('/assets/../image.png') I have to do network request, is there any directory like CRA public folder that I can access some assets by URL?

**Comment by cruzach** [comment]
Hi! We keep github reserved for bug reports, so I'm going to close with. For general help with questions like this, you should post on our [forums](https://forums.expo.io/). Make sure to clearly explain your use case, thanks!
