### ISSUE TITLE
How correctly set background color in android adaptive icon

### ISSUE THREAD

**Issue by nikitok** [expo/expo#7374]
Hi!
I want to set white color in my icon appication, but if i set these settings in app.json

```json
    "android": {
      "package": "test.com",
      "adaptiveIcon": {
        "foregroundImage": "./assets/icon3.png",
        "backgroundColor": "#FFF"
      }
    }
```

I get dark green icon (((
My icon3.png for test
![icon3](https://user-images.githubusercontent.com/668653/76778862-9126b600-67bb-11ea-9a57-96b0a654e160.png)

My screenshot from android emulator:
icon3.png
![Screenshot 2020-03-16 at 7 21 38 PM](https://user-images.githubusercontent.com/668653/76778915-a7347680-67bb-11ea-9282-f9adfe840596.png)

**Comment by cruzach** [comment]
Hi! You'll need to rebuild your app for any changes to app.json to take place, otherwise your configuration looks right to me. Did you build the app previously with that value set to a shade of blue? Btw- the `adaptiveIcon.backgroundColor` should default to `#ffffff`, so if that's what you want you should just be able to leave it unspecified

**Comment by nikitok** [comment]
I did these many times, and special create new app, and i have same result (

**Comment by cruzach** [comment]
can you share your whole app.json?

**Comment by nikitok** [comment]
`{
  "expo": {
    "name": "Blank Template",
    "slug": "expoTest",
    "privacy": "public",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon3.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "scheme": "exp9697fa73838d456cb9764e29f57651e6",
    "android": {
      "package": "test.com",
      "adaptiveIcon": {
        "foregroundImage": "./assets/icon3.png",
        "backgroundColor": "#FFF"
      }
    }
  }
}
`

**Comment by cruzach** [comment]
and what SDK version is this? Sorry, that's usually included in the app.json file or else I would've asked for that before

**Comment by zlep** [comment]
I have the same problem. SDK36.

` "android": {
      "package": "com.test_app",
      "versionCode": 1,
      "adaptiveIcon": {
        "foregroundImage": "./assets/icon.png",
        "backgroundColor": "#ff0012"
      },`

I also have a weird blue background instead of my ff0012

**Comment by LucaRed** [comment]
I also have this problem, but I'd word it differently.

The problem is that the icon shown in the recent apps switcher completely ignores the Adaptive Icon set in `android.adaptiveIcon` and shows the wrong generic `icon` instead.

It was already reported [on the Expo forums in July 2019](https://forums.expo.io/t/android-icon-while-switching-apps/25116).

**Comment by cruzach** [comment]
thanks for the info @LucaRed ill take a look

**Comment by cruzach** [comment]
Note that a good workaround for now is to use the `backgroundImage` property, and just make it a blank image of the background color you prefer

**Comment by gbkwiatt** [comment]
backgroundImage does nothing unfortunately.

```json
"icon": "./assets/icon.png",
 "android": {
"adaptiveIcon": {
        "backgroundImage": "./assets/bg-white.png"
      }
}
```

**Comment by gbkwiatt** [comment]
solution is to use  in your app.json `"primaryColor": "#FFFFFF",`

**Comment by MathMesquita** [comment]
Happening here in SDK 37, setting `primaryColor` didn't take any effect. :(

**Comment by JJwilkin** [comment]
Hi, @byCedric  had recommended this thread to me, I notice I'm having much of the same issues.  @nikitok I notice you expo.icon and android.adaptiveIcon.foregroundImage have the same icon. I believe that's what led you to believe only the  background color/image wasn't working however from my experience Expo only pays attention to the expo.icon. If you changed your android.adaptiveIcon.foregroundImage to be different than expo.icon are those changes reflected? They are currently not for me, Expo SDK 38

```
{
  "name": "ChowTime",
  "displayName": "ChowTime",
  "expo": {
    "name": "ChowTime",
    "slug": "ChowTime",
    "version": "3.0.0",
    "icon":"./assets/icon.png",
    "android": {
      "package": "com.yourcompany.chowtime",
      "versionCode": 2,
      "icon": "./assets/green.png",
      "adaptiveIcon": { 
        "foregroundImage": "./assets/green.png",
        "backgroundColor": "./assets/green-background.png" 
      }
    },
    "splash": {
      "image": "./assets/splashScreen.png",
      "resizeMode": "cover"
    },
    "platforms": ["ios", "android", "web"],
    "assetBundlePatterns": ["**/*"]
  }
}
```

**Comment by JosiasBatista** [comment]
I'm having the same issue with similar especifications in my app.json! I don't know what's happening. I followed the expo guide for build the adaptive icon, but it doesn't work properly!

**Comment by brentvatne** [comment]
@JosiasBatista: https://docs.expo.dev/versions/latest/config/app/#adaptiveicon

if the background color isn't working as expected for you then create a new issue and fill out the issue template
