### ISSUE TITLE
react-native-svg 5.3.0 no longer works due to proptypes

### ISSUE THREAD

**Issue by jayeszee** [expo/expo#738]
Seems like Svg is no longer working on expo 21 anymore because it has a dependency to react-native-svg 5.3.0.

![image](https://user-images.githubusercontent.com/10326244/31261503-6c905534-aa09-11e7-8429-7f4464206383.png)
If you look inside the 5.3.0 code, it uses React.PropTypes.bool which doesn't work anymore because the react library (16 alpha 12) no longer has PropTypes. The newer version of react-native-svg handles this problem but 5.3.0 is still using the wrong thing.

**Comment by ide** [comment]
React 16 alpha 12 should still define React.PropTypes but beta 5 won’t. This shouldn’t be an issue for SDK 21 but we’ll have to update it for SDK 22.

**Comment by jayeszee** [comment]
Am I doing something wrong here?
![image](https://user-images.githubusercontent.com/10326244/31280339-dd50cfea-aa60-11e7-9bb6-0fa6aaddc6d3.png)
Clearly I'm using 16.0.0 alpha 12 but im guessing the minor release (^) bumped it up and gave me a version that didn't have propTypes?
