### ISSUE TITLE
[docs] WebBrowser wrong function name

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#7383]
https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/webbrowser.md#webbrowsergetcustomtabssupportingbrowsers

`getCustomTabsSupportingBrowsers` should be `getCustomTabsSupportingBrowsersAsync`

**Comment by cruzach** [comment]
closed in https://github.com/expo/expo/pull/7438
