### ISSUE TITLE
Issue with expo fetch:android:hashes for mapview

### ISSUE THREAD

**Issue by Daneaz** [expo/expo#7390]
The expo fetch:android:hashes will return with google upload certificate instead of app signing certificate.
Hence, the step 9 and 10 descript over here is incorrect 
https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android

**Comment by cruzach** [comment]
There is a section further down:
> **Deploying to the Google Play Store**
> Since your app is most likely using App Signing by Google Play, you will need to grab their app signing certificate in production rather than the upload certificate returned by expo fetch:android:hashes. You can do this by grabbing the signature from Play Console -> Your App -> Release management -> App signing, and then going to the API Dashboard -> Credentials and adding the signature to your existing credential.

If you think this could be made clearer, we'd love to see a PR!

**Comment by Daneaz** [comment]
Thanks cruzach,
It's clear enough, closing the issue
