### ISSUE TITLE
Can not get CAMERA_ROLL permissions alert on TestFlight for Standalone apple Apple

### ISSUE THREAD

**Issue by ndipenoch** [expo/expo#7391]
Camera alert permission works fine both on Expo and TestFlight.
CAMERA_ROLL  alert permission works on multiple devices on Expo but not  on TestFlight.
 In test flight there is no photos under Settings=>App Name

Does anyone know why?

Thank you so much in advance!

Here is the code snipet:

**********************Js File*****************************
 getPermissionAsync = async () => {
    if (Constants.platform.ios) {
      const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
      if (status !== 'granted') {
        alert('Sorry, we need camera roll permissions to make this work!');
      }
    }
  }

**********************app.Json file*****************************
 "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "*****",
      "buildNumber": "1.2.0",
      "infoPlist": {
        "NSPhotoLibraryUsageDescription": "This app will access your photo library to pick an image, and extract the texts.",
        "NSCameraUsageDescription": "This app will access your camera to take pictures, and extract the texts."
      },

**Comment by cruzach** [comment]
Hey @ndipenoch , could you fill out the full bug report template? We need all that information to help you

It's also not clear exactly what the problem is.. does `await Permissions.askAsync(Permissions.CAMERA_ROLL)` resolve, and if so, to what?

**Comment by ndipenoch** [comment]
Bug Report
Environment
React-native app with expo/managed flow.

iOS


Steps to Reproduce
I use the following code to ask for permissions to use camera (and also file upload) for ImagePicker:
getPermissionAsync = async () => {
if (Constants.platform.ios) {
const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);
if (status !== 'granted') {
alert('Sorry, we need camera roll permissions to make this work!');
}
}
}

app.Json file*******
"ios": {
"supportsTablet": true,
"bundleIdentifier": "*****",
"buildNumber": "1.2.0",
"infoPlist": {
"NSPhotoLibraryUsageDescription": "This app will access your photo library to pick an image, and extract the texts.",
"NSCameraUsageDescription": "This app will access your camera to take pictures, and extract the texts."
},

Expected Behavior
It should ask user for permissions.

Actual Behavior
Camera alert permission works fine both on Expo and TestFlight.
CAMERA_ROLL alert permission works on multiple devices on Expo but not on TestFlight.
No image picker.

**Comment by cruzach** [comment]
So the alert never shows? What does `status` resolve to?

**Comment by ndipenoch** [comment]
Problem fix by uninstalling and installing expo Cli.
npm uninstall -g expo-cli
npm install -g expo-cli
