### ISSUE TITLE
[docs] App signing step 8 does not work as promised

### ISSUE THREAD

**Issue by DianaKoenraadt** [expo/expo#7392]
https://docs.expo.io/versions/latest/distribution/app-signing/

In step 8, you're supposed to upload a *.pem file
Google will punish you with an error if you do this: "The upload key is the same as the deployment key. For security reasons we need them to be different. Please use a different upload certificate."

Turns out, step 3 and step 8 generate **identical** PEM files. 
Even when running the command Google suggests ("$ keytool -export -rfc -keystore upload-keystore.jks -alias upload -file upload_certificate.pem") you get the same PEM key and so this step will never be successful.

**Comment by cruzach** [comment]
Step 8 doesn't generate a pem file, you upload the pem file from step 3

If, instead of going through the manual set up, you just run `expo opt-in-google-play-signing`, do you hit the same error?

**Comment by DianaKoenraadt** [comment]
I upload the PEM file from step 3 at step 8 and I get an error from Google. Saying "The upload key is the same as the deployment key. For security reasons we need them to be different. Please use a different upload certificate."

I misphrased: Step 3 and step 7 generate the same PEM file. That's why Google complains.

**Comment by cruzach** [comment]
If, instead of going through the manual set up, you just run `expo opt-in-google-play-signing`, do you hit the same error?

**Comment by DianaKoenraadt** [comment]
Sorry, how is that relevant? I'm not unwilling to do this for you, but I'm really interested in the documentation for the second case, not the first one...

**Comment by cruzach** [comment]
Oh I should've explained that. So `expo opt-in-google-play-signing` essentially does those exact steps for you behind the scenes, so testing that command out would just remove other variables and clearly indicate that there's an issue with how we handle this

**Comment by DianaKoenraadt** [comment]
Okay thanks. I started rerunning it but I can't proceed. I've already tried to configure Google Signing once before and can't continue. Even if I try to do the configuration again, I can't because I am asked to enter a Google Play encryption key which it doesn't show anymore.

**Comment by DianaKoenraadt** [comment]
Sorry, previous comment made no sense. I am creating a new app because we botched the previous one. I'll rerun asap

**Comment by wkozyra95** [comment]
Hi
Most important step is to make sure your old keystore and credentials are safe (The one you should backup in step 1). I would suggest to move it outside of a project directory.

If you don't have option to provide upload keystore then you are most likely safe and in worst case upload keystore will need to be reset. 
Go to `app signing` and check the hashes, in a correct setup
- `App signing certificate` is different than `Upload certificate` (optional, but recomended)
- `Upload certificate` matches result `expo fetch:android:hashes`
If something is different than described above please post differences, it'll help diagnose cause of the problem.

to reset your keystore you will need to provide google team with `pem` file, which can be generated using `expo fetch:android:upload-cert`.

I don't know why this happened, are you sure that you followed all the steps in the correct order?
especially `clear-credentials` and `fetch:android:upload-cert` parts?

**Comment by DianaKoenraadt** [comment]
Thanks for your reply. 

Some further feedback on the documentation, as I am running `expo opt-in-google-play-signing`:

- It is not clear what the four files are that it creates. That *.jdk.back file is is the **old** keystore or the **new** one? Turns out to be the old one.
- Why does expo even _need_ that encryption key from Google?
- Why not backup the **new** one, that is the one I need and shouldn't lose, right?

Outcome:

- Commandline shows me App signing certificate that is **wrong**. It is not the same as in Google Play Console
- What happens if I choose "Yes" for "Is App Signing by Google Play enabled succesfully?"? I don't want to have Expo put an upload key in my Google Play Console. I chose "No" for now.

Other test:

- Take PEM file that is created by `opt-in-google-play-signing`
- Run `PEPK` and take resulting PEM file
- Compare: they are **identical**

**Comment by DianaKoenraadt** [comment]
If you can tell me what "Is App Signing by Google Play enabled succesfully?" does, I will happily continue there. But I don't want my new clean app in Google Play Console to be changed by Expo because we've been going through quite a hassle already..

**Comment by wkozyra95** [comment]
You should not run `opt-in-google-play-signing` if you already run clear credentials previously.

**Comment by wkozyra95** [comment]
> Go to `app signing` and check the hashes, in a correct setup
> 
> * `App signing certificate` is different than `Upload certificate` (optional, but recomended)
> * `Upload certificate` matches result `expo fetch:android:hashes`

Can you check specifically those 3 values.

> they are identical

Which values are identical

**Comment by DianaKoenraadt** [comment]
- App signing certificate is different than Upload certificate: Confirmed
- `expo fetch:android:hashes` is neither equal to App signing certificate in Google Play nor to Upload certificate in Google Play

- `expo fetch:android:hashes` returns a value X and you say this is the upload certificate. But `opt-in-google-play-signing` spits out "App signing certificate" and gives me X. So hashes must be app signing certificate according to the cmd output. Regardless, they're not the same.

However, this entire topic has given me a new avenue to pursue, for which I thank you.

Regardless, this is completely beside the point of the issue: **The documentation implies that the PEM files that are generated at two separate steps of the process must be different. They are not.**

**Comment by DianaKoenraadt** [comment]
Should I be running step 3 and 7 on different keystores maybe?

**Comment by wkozyra95** [comment]
`opt-in-google-play-signing` works under the assumption that there is app signing key on expo servers, but this is not true anymore, because you cleared credentials at the beginning

> The documentation implies that the PEM files that are generated at two separate steps of the process must be different. They are not.

Keystore contains private/public key pair if in your case both pem files(public key) are the same that means that you extracted it from the same keystore, but with two different methods. 

And I repeat do not run `opt-in-google-play-signing` at this point data showed there won't apply to you. The first question asks if you have app signing enabled and in your case answer is yes which should quit creator.

**Comment by DianaKoenraadt** [comment]
> Keystore contains private/public key pair if in your case both pem files(public key) are the same that means that you extracted it from the same keystore, but with two different methods.

Yes, I think this is what I did: That's `expo fetch:android:upload-cert` and `PEPK` tool.

I have created a brand new app in Google Play Console. That is what this is about. So that is why I am running the alternative steps.

Should I have ran `PEPK` tool on different keystore? Because Google wants a _different_ PEM file for step 8...

**Comment by wkozyra95** [comment]
For brand new app you should not run those commands at all

**Comment by wkozyra95** [comment]
![2020-03-18-165723_956x95_scrot](https://user-images.githubusercontent.com/9753141/76980613-ae818e80-6939-11ea-9268-fe4513f1d1a1.png)

**Comment by wkozyra95** [comment]
All new apps have this enabled by default and you should not do anything there

If you want to recover previous app run
`expo build:android --clear-credentials`
after build finish
`expo fetch android:upload-cert`
and sent .pem file to support

**Comment by UncleLodza** [comment]
what they mean here is that the .pem file can take any name, do not use he name 'certificate.perm', give it another name because it will be saved locally as a new file.
 For example instead of running ("keytool -export -rfc -keystore upload-keystore.jks -alias upload -file upload_certificate.pem");
you can run  "keytool -export -rfc -keystore upload-keystore.jks -alias upload -file mykey.pem".
