### ISSUE TITLE
Calendar Glitch with iOS

### ISSUE THREAD

**Issue by rschneid0** [expo/expo#7399]
## 🐛 Bug Report

I think there's an issue with setting recurrenceRules' endDates on iOS...
When I try to run 
```
Calendar.createEventAsync(
      <my_calendar_id>,
      example_event
    )
```
with the example event:
```
{
  "alarms": Array [],
  "endDate": 2020-03-18T18:24:32.000Z,
  "notes": "",
  "recurrenceRule": Object {
    "endDate": 2020-03-18T18:24:32.000Z,
    "frequency": "daily",
    "interval": 1,
  },
  "startDate": 2020-03-18T17:24:32.000Z,
  "timeZone": "America/New_York",
  "title": "Example ",
}
```
I get the error:

```
Error:  [Error: An exception was thrown while calling `ExpoCalendar.saveEventAsync` with arguments `(
        {
        alarms =         (
        );
        calendarId = "B03CE636-825A-476A-9AA7-5C16AF9C695F";
        endDate = "2020-03-18T18:24:32.000Z";
        notes = "";
        recurrenceRule =         {
            endDate =             {
            };
            frequency = daily;
            interval = 1;
        };
        startDate = "2020-03-18T17:24:32.000Z";
        timeZone = "America/New_York";
        title = "Example ";
    },
        {
    }
)`: -[__NSDictionaryM length]: unrecognized selector sent to instance 0x28098cca0]
```
However recurrence rules that do not specify an endDate, and stick to frequency seem to work...

```
Object {
  "alarms": Array [],
  "endDate": 2020-03-18T19:26:25.000Z,
  "notes": "",
  "recurrenceRule": Object {
    "frequency": "daily",
    "interval": 1,
    "occurrence": 3,
  },
  "startDate": 2020-03-18T18:26:25.000Z,
  "timeZone": "America/New_York",
  "title": "This works ",
}
```
### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ~4.0.10 => 4.0.10

Target: iOS

### Steps to Reproduce

Create a calendar event with a recurrenceRule that has an endDate property and it will throw an error instead of saving.

### Expected Behavior

createEvent to save an event to the device native calendar

### Actual Behavior

An exception was thrown while calling `ExpoCalendar.saveEventAsync`

### Reproducible Demo

https://snack.expo.io/BJtAjelLU

The code on line 42 is responsible for the exception, according to the message it appears the endDate property of the recurrenceRule is being turned into an empty object before it hits iOS-land. The docs say that endDate expects a `Date` type, so I expect it's a bug.

**Comment by cruzach** [comment]
It looks  like `endDate` might be expecting a number, not a date, since using `Date.now()` makes your snack work

**Comment by rschneid0** [comment]
Thanks! Using `endDate.getTime()` seems to lead to reasonably expected behavior on both mobile platforms...

**Comment by cruzach** [comment]
@rschneid0 would you like to open up a PR to clarify this in the docs and possibly TypeScript types?

**Comment by rschneid0** [comment]
I'd be happy to! Let me see what ts is all about and I'll give it a shot...
