### ISSUE TITLE
WEBP format for GLSnapshot

### ISSUE THREAD

**Issue by pacoelayudante** [expo/expo#7401]
Hello, please add webp format, I'll try to do a push request in that regard

https://github.com/expo/expo/blob/07ceb6ea539b087b3172241f902a56b2aa5ee90e/packages/expo-gl/android/src/main/java/expo/modules/gl/GLContext.java#L281-L284

**Comment by cruzach** [comment]
Closing since this isn't a bug report, and we keep feature requests on our [canny](https://expo.canny.io/feature-requests), but we'd love to see a PR!

**Comment by pacoelayudante** [comment]
> Closing since this isn't a bug report, and we keep feature requests on our [canny](https://expo.canny.io/feature-requests), but we'd love to see a PR!

whoops sorry about that
