### ISSUE TITLE
Deprecated API Usage message UIWebView for React-native

### ISSUE THREAD

**Issue by birken92** [expo/expo#7402]
Using expo while developing a react-native app. Will SDK 37, fix this issue for uni modules as well?

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

    "expo-file-system": "^8.0.0",
    "expo-location": "^8.0.0",
    "expo-media-library": "^8.0.0",
    "expo-permissions": "^8.0.0",
    "expo-permissions-interface": "^3.0.0",
    "react-native-unimodules": "0.7.0",
    "unimodules-permissions-interface": "^5.0.0"

Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/UIKit-1V5UHAPTOD24G.pcm matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/modules.idx matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/records/EJ/UIWebView.h-17DCX353XRLEJ matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/units/UIKit-1V5UHAPTOD24G.pcm-35LZDCPFUDPTH matches

**Comment by cruzach** [comment]
This has been fixed in SDK 36 (you need to rebuild your app), and in upcoming SDK 37. See here for more information- https://github.com/expo/expo/issues/5497
