### ISSUE TITLE
[docs] Web Performance docs are out of date

### ISSUE THREAD

**Issue by cruzach** [expo/expo#7407]
[What makes my app so large](https://docs.expo.io/versions/latest/guides/web-performance/#-what-makes-my-app-large) section says to configure this in app.json, but when doing that you get an error saying: 
```
expo.web.build.report is deprecated. Please extend webpack.config.js and use env.report instead.
```
Seems like these are the up-to-date docs for that: 
https://github.com/expo/expo-cli/blob/master/packages/webpack-config/README.md

**Comment by EvanBacon** [comment]
fixed in https://github.com/expo/expo/pull/7425
