### ISSUE TITLE
OTA updates are not working in production when connected to wifi

### ISSUE THREAD

**Issue by SamyOptimize** [expo/expo#7409]
### Environment

Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 

Taregets: iOS, Android

### Steps to Reproduce

Not much to this issue to be reproduced,
1- Run expo publish 
2- Restart app while connected to WiFi
3- Expo.Updates throws an error

### Expected Behavior
OTA updates to be downloaded while on WiFi

### Actual Behavior
OTA updates are not being downloaded 

### Reproducible Demo
https://github.com/SamyOptimize/demo2

It won't throw the correct error if it was used on a simulator or during development mode, I had to build an apk and download it to my phone and that's when i get the error at the bottom.

Haven't tried it on a built .ipa yet but i'm guessing it's for a related reason because i can't get the OTA updates to download on our own production app.

OTA updates in an ejected app are not being downloaded in production apps when it's connected to a WiFi connection, it works fine if the phone is only using its own mobile data.

Logging the error for the Updates module for android from our own production app returns this:
```
{
  "framesToPop": 1,
  "nativeStackAndroid": [
    {
      "methodName": "onFailure",
      "lineNumber": 1,
      "file": "ExponentManifest.java",
      "class": "host.exp.exponent.g$b"
    },
    {
      "methodName": "a",
      "lineNumber": 34,
      "file": "ExponentHttpClient.java",
      "class": "host.exp.exponent.s.e"
    },
    {
      "methodName": "a",
      "lineNumber": 1,
      "file": "ExponentHttpClient.java",
      "class": "host.exp.exponent.s.e"
    },
    {
      "methodName": "onResponse",
      "lineNumber": 4,
      "file": "ExponentHttpClient.java",
      "class": "host.exp.exponent.s.e$d"
    },
    {
      "methodName": "execute",
      "lineNumber": 5,
      "file": "RealCall.java",
      "class": "okhttp3.RealCall$AsyncCall"
    },
    {
      "methodName": "run",
      "lineNumber": 3,
      "file": "NamedRunnable.java",
      "class": "okhttp3.internal.NamedRunnable"
    },
    {
      "methodName": "processTask",
      "lineNumber": 1187,
      "file": "ThreadPoolExecutor.java",
      "class": "java.util.concurrent.ThreadPoolExecutor"
    },
    {
      "methodName": "runWorker",
      "lineNumber": 1152,
      "file": "ThreadPoolExecutor.java",
      "class": "java.util.concurrent.ThreadPoolExecutor"
    },
    {
      "methodName": "run",
      "lineNumber": 641,
      "file": "ThreadPoolExecutor.java",
      "class": "java.util.concurrent.ThreadPoolExecutor$Worker"
    },
    {
      "methodName": "run",
      "lineNumber": 784,
      "file": "Thread.java",
      "class": "java.lang.Thread"
    }
  ],
  "userInfo": null,
  "message": null,
  "code": "E_FETCH_MANIFEST_FAILED",
  "line": 20,
  "column": 1111,
  "sourceURL": "/data/user/0/com.optimizeapp.optimizeapp/files/36.0.0/cached-bundle-experience-%40samyoptimize%2Foptimize_app-1658896835-36.0.0"
}
```

and for our own production app on iOS returns this"
```
{
  "framesToPop": 1,
  "code": "E_CHECK_UPDATE_FAILED",
  "message": "The request timed out.",
  "domain": "EXNetwork",
  "userInfo": {
    "_kCFStreamErrorDomainKey": 4,
    "NSErrorFailingURLKey": null,
    "_kCFStreamErrorCodeKey": -2102,
    "NSErrorFailingURLStringKey": "http://exp.host/@samyoptimize/optimize_app",
    "NSLocalizedDescription": "The request timed out.",
    "NSUnderlyingError": {
      "code": "-1001",
      "message": "underlying error",
      "domain": "kCFErrorDomainCFNetwork",
      "userInfo": {
        "_kCFStreamErrorDomainKey": 4,
        "_kCFStreamErrorCodeKey": -2102
      },
      "nativeStackIOS": [
        "0   optimizeapp                         0x000000010514d5bc _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 518316",
        "1   optimizeapp                         0x000000010514d7a8 _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 518808",
        "2   optimizeapp                         0x0000000105112718 _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 277000",
        "3   optimizeapp                         0x00000001050396b8 optimizeapp + 890552",
        "4   optimizeapp                         0x000000010500b910 optimizeapp + 702736",
        "5   optimizeapp                         0x0000000105012268 optimizeapp + 729704",
        "6   CFNetwork                           0x00000001c07b9be4 CFNetServiceBrowserSearchForServices + 93664",
        "7   CFNetwork                           0x00000001c07ca6f4 _CFHTTPMessageSetResponseProxyURL + 9540",
        "8   Foundation                          0x00000001bd92b410 503900AF-2ECD-329F-B742-C07C3E672BEB + 1131536",
        "9   Foundation                          0x00000001bd835138 503900AF-2ECD-329F-B742-C07C3E672BEB + 123192",
        "10  Foundation                          0x00000001bd92d698 503900AF-2ECD-329F-B742-C07C3E672BEB + 1140376",
        "11  Foundation                          0x00000001bd834dd0 503900AF-2ECD-329F-B742-C07C3E672BEB + 122320",
        "12  Foundation                          0x00000001bd92e090 503900AF-2ECD-329F-B742-C07C3E672BEB + 1142928",
        "13  Foundation                          0x00000001bd92db5c 503900AF-2ECD-329F-B742-C07C3E672BEB + 1141596",
        "14  libdispatch.dylib                   0x00000001bd216998 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 260504",
        "15  libdispatch.dylib                   0x00000001bd233184 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 377220",
        "16  libdispatch.dylib                   0x00000001bd20ce8c A3849F96-1C9F-36C5-A15F-70C566F14CFF + 220812",
        "17  libdispatch.dylib                   0x00000001bd20c600 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 218624",
        "18  libdispatch.dylib                   0x00000001bd219110 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 270608",
        "19  libdispatch.dylib                   0x00000001bd2198b0 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 272560",
        "20  libsystem_pthread.dylib             0x00000001bd282b48 _pthread_wqthread + 212",
        "21  libsystem_pthread.dylib             0x00000001bd285760 start_wqthread + 8"
      ]
    },
    "errorCode": "NETWORK_ERROR"
  },
  "nativeStackIOS": [
    "0   optimizeapp                         0x000000010514d5bc _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 518316",
    "1   optimizeapp                         0x0000000105112718 _ZN8facebook5react11JSIExecutor21defaultTimeoutInvokerERKNSt3__18functionIFvvEEENS3_IFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvEEE + 277000",
    "2   optimizeapp                         0x00000001050396b8 optimizeapp + 890552",
    "3   optimizeapp                         0x000000010500b910 optimizeapp + 702736",
    "4   optimizeapp                         0x0000000105012268 optimizeapp + 729704",
    "5   CFNetwork                           0x00000001c07b9be4 CFNetServiceBrowserSearchForServices + 93664",
    "6   CFNetwork                           0x00000001c07ca6f4 _CFHTTPMessageSetResponseProxyURL + 9540",
    "7   Foundation                          0x00000001bd92b410 503900AF-2ECD-329F-B742-C07C3E672BEB + 1131536",
    "8   Foundation                          0x00000001bd835138 503900AF-2ECD-329F-B742-C07C3E672BEB + 123192",
    "9   Foundation                          0x00000001bd92d698 503900AF-2ECD-329F-B742-C07C3E672BEB + 1140376",
    "10  Foundation                          0x00000001bd834dd0 503900AF-2ECD-329F-B742-C07C3E672BEB + 122320",
    "11  Foundation                          0x00000001bd92e090 503900AF-2ECD-329F-B742-C07C3E672BEB + 1142928",
    "12  Foundation                          0x00000001bd92db5c 503900AF-2ECD-329F-B742-C07C3E672BEB + 1141596",
    "13  libdispatch.dylib                   0x00000001bd216998 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 260504",
    "14  libdispatch.dylib                   0x00000001bd233184 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 377220",
    "15  libdispatch.dylib                   0x00000001bd20ce8c A3849F96-1C9F-36C5-A15F-70C566F14CFF + 220812",
    "16  libdispatch.dylib                   0x00000001bd20c600 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 218624",
    "17  libdispatch.dylib                   0x00000001bd219110 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 270608",
    "18  libdispatch.dylib                   0x00000001bd2198b0 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 272560",
    "19  libsystem_pthread.dylib             0x00000001bd282b48 _pthread_wqthread + 212",
    "20  libsystem_pthread.dylib             0x00000001bd285760 start_wqthread + 8"
  ],
  "line": 22,
  "column": 1111,
  "sourceURL": "https://d1wp6m56sqw74a.cloudfront.net/%40samyoptimize%2Foptimize_app%2F0.3.230%2F278a8fa7d16012311a7d603043396d22-36.0.0-ios.js"
}

```

Had a similar issue with the WiFi problem a while back https://forums.expo.io/t/expokit-apks-for-android-crash-when-opening/34344 
Which was fixed based on this github issue https://github.com/expo/expo/issues/7304 so i'm not sure if it has to do with expo's servers again

**Comment by mskg** [comment]
Your manifest URL ist starting with `http` instead of `https`. This is not the normal content that the build produces.

Can you extract the IPA and check the content of the  file `EXSHELL.plist` inside the `.app` package?

**Comment by SamyOptimize** [comment]
@mskg I have extracted the contents of the .ipa and the manifestUrl inside `EXSHELL.plist` is: `exp://exp.host/@samyoptimize/optimize_app`

**Comment by cruzach** [comment]
Hey @SamyOptimize , I just tested your code  on a fresh expokit project, and I was able to see the `new update found` message, and then my app successfully updated, so it looks like there's some other variable at play here

**Comment by SamyOptimize** [comment]
@cruzach Yes i was able to get the "New update found" text which downloads the OTA if I wasn't connected to a WiFi connection and was using my mobile data, after that I couldn't get the error message to show up if I connected to a WiFi connection and tried again. So I uninstalled the app, reinstalled again and opened it with a WiFi connection and when I pressed the button I got the following:
![Screenshot_20200319_175621_com demo](https://user-images.githubusercontent.com/48402367/77211423-ff99aa00-6b14-11ea-8ef7-322c33d104e0.jpg)

The steps that I tried to get that error is:
1-Download the OTA from my mobile data.
2-Then I made another OTA update with expo publish
3-Then tried to download the OTA on from the app using a  WiFi connection.
4-It kept saying no update found.
5-I kept checking by pressing the button
6- It got the update and said "New Update found" but also showed an error and restarted
And now the error keeps showing again while connected to WiFi.
 
The same was happening to our production app on iOS and Android, and for some of our other friends they were facing something like this during a hackathon type event.

In the issue I referenced  [#7304 ](https://github.com/expo/expo/issues/7304)  were having problems with expo's server returning the wrong  `https://expo.io` url instead of ` https://exp.host `, So i'm not sure if that's related. Because that issue was being bypassed by us exactly like what i was describing (Using mobile data/VPN instead of a WiFi connection)

**Comment by cruzach** [comment]
> In the issue I referenced #7304 were having problems with expo's server returning the wrong https://expo.io url instead of https://exp.host

Most likely this isn't related since you're still able to load OTA updates

I've tried using your example code and the steps you listed out above, but I still can't reproduce the error 🙁

**Comment by SamyOptimize** [comment]
Then it seems it still has to do with my region's internet blocking expo's servers from time to time. Because using a VPN we would bypass some of the issues we've been facing with expo since last year including this one and sometimes everything works fine. We've been moving away from relying on expo gradually because our specific issues ( [28769](https://forums.expo.io/t/expo-start-takes-ages/28769) 
 ,[29616](https://forums.expo.io/t/expo-login-throws-an-error-read-econnreset/29616), [29650](https://forums.expo.io/t/expo-push-notification-returns-an-ssl-error/29650), [29150](https://forums.expo.io/t/weird-problem-with-accessing-expo-io-website/29150) ) don't seem like they are gonna go away anytime soon. We'll be ejecting again to the bare workflow soon and hopefully we don't run into the same issues.

**Comment by cruzach** [comment]
You can always [host your own updates](https://docs.expo.io/versions/latest/distribution/hosting-your-app/), if your region has difficulty accessing Expo's servers

**Comment by SamyOptimize** [comment]
Just to make sure, this is possible to do with an ejected ExpoKit project, correct?

**Comment by cruzach** [comment]
Yeah, there's just different configuration (as in setting what URL the project is looking at to fetch its updates)

**Comment by mskg** [comment]
> I've tried using your example code and the steps you listed out above, but I still can't reproduce the error 🙁 

I also can’t reproduce that.

**Comment by SamyOptimize** [comment]
> Yeah, there's just different configuration (as in setting what URL the project is looking at to fetch its updates)

@cruzach Excuse my ignorance, I've followed the guide up until [Build standalone app](https://docs.expo.io/versions/latest/distribution/hosting-your-app/#build-standalone-app) section and I'm lost on what to do about `setting what URL the project is looking at to fetch its updates`. Where do i configure this if I can't use `expo build:ios --public-url <path-to-ios-index.json>`

**Comment by cruzach** [comment]
Since we're very close to releasing SDK 37, and with it, OTA Updates for the bare workflow, it's probably not the best use of your time to set this up in an Expokit project (we should be releasing in the next week or so). The overall experience of working with a bare project is much better than Expokit (hence why we are deprecating expokit in favor of the bare workflow)

**Comment by SamyOptimize** [comment]
Yes, I understand. But I think that if I set up the hosting of our app on a server it will help/eliminate the blocking of our region's internet to expo's server. Because if we still use SDK 37 with OTA Updates for the bare workflow, we would still run into the same issues we've been facing of our users unable to receive OTA updates.

**Comment by cruzach** [comment]
That's fine, you'll still have the option to host updates from your own server in the bare workflow
