### ISSUE TITLE
console.log commands are not shown their code line locations

### ISSUE THREAD

**Issue by ghasemikasra39** [expo/expo#7410]
### Environment

```
  Expo CLI 3.15.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.15.4
App's target: iOS and Android
```

### Steps to Reproduce

Create a new project using `expo init new-project`. Do `console.log()` in your code, or cause error somewhere in your code.

### Expected Behavior

In google chrome console, or in React Native Debugger, the **file name** and the exact **line of code** must be shown on the right-hand side where the `console.log` was written, or where the error happens. Like this : (Here I used pure react native project , No expo):
<img width="1280" alt="Screenshot 2020-03-19 at 21 11 55" src="https://user-images.githubusercontent.com/24314029/77143061-4e086380-6a97-11ea-8603-f9aadcef566b.png">

### Actual Behavior

It always shows `RemoteConsole.js:80`:
<img width="1280" alt="Screenshot 2020-03-19 at 19 54 44" src="https://user-images.githubusercontent.com/24314029/77089900-abf76580-6a1b-11ea-968d-d4d9fd1aba59.png">

### Reproducible Demo
https://github.com/ghasemikasra39/new-expo-project

**Comment by cruzach** [comment]
Hi @ghasemikasra39 , can you please fill out the full bug report template? It asks for all the information we need. I think this is probably something to do with your project or setup, specifically, since I haven't seen this myself or seen someone run into it

**Comment by ghasemikasra39** [comment]
> Hi @ghasemikasra39 , can you please fill out the full bug report template? It asks for all the information we need. I think this is probably something to do with your project or setup, specifically, since I haven't seen this myself or seen someone run into it

I have updated my issue to match the bug report template.

**Comment by ghasemikasra39** [comment]
@cruzach  Do you need more information?

**Comment by cruzach** [comment]
No, but this is probably just due to how `expo-cli` bundles your JS and runs it in the Expo client app. This is pointed out [in the documentation](https://docs.expo.io/versions/latest/workflow/debugging/#source-maps-and-async-functions)

**Comment by m-deacon** [comment]
Is there any update on this issue? I've had the `RemoteConsole.js:80` issue for months now and unable to find a solution. It makes debugging very tricky. 

> No, but this is probably just due to how expo-cli bundles your JS and runs it in the Expo client app. This is pointed out in the documentation

This doesn't feel like it solves anything?

**Comment by ghasemikasra39** [comment]
dear @m-deacon 
I am still getting the same issue.

**Comment by m-deacon** [comment]
@ghasemikasra39 and anyone else with this issue, I've finally found the solution:

> Line numbers for console.log statements don't work by default when using Chrome debugging. To get correct line numbers open up the Chrome Dev Tools settings, go to the "Blackboxing" tab, make sure that "Blackbox content scripts" is checked, and add expo/build/logs/RemoteConsole.js as a pattern with "Blackbox" selected.

source: https://stackoverflow.com/questions/60762842/expo-console-log-commands-are-not-shown-their-code-line-locations
