### ISSUE TITLE
Standalone Android App and Expo client crashing when using map.getCamera()

### ISSUE THREAD

**Issue by NeOMakinG** [expo/expo#7412]
### Environment

  Expo CLI 3.15.4 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.11.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.15.4

### Steps to Reproduce

I'm using map.getCamera() and it's still doing the same thing as https://github.com/expo/expo/issues/4791

Also I linked at the end of this issue logcats from ADB of my android standalone app that I built 10 mins ago with the environnement below.

### Expected Behavior

Working on both iOS and Android standalone apps

### Actual Behavior

Working on iOS, even on expo client, but not on android both expo client and standalone build

### Reproducible Demo

Private project from my enterprise :/

![image](https://user-images.githubusercontent.com/14963751/77113373-fe8c4e00-6a2a-11ea-84b9-0d57792d8f3e.png)

**Comment by cruzach** [comment]
Hey @NeOMakinG thanks for reporting this, I'm running a build to try and reproduce this. I should mention that this won't work in the Expo client until the next Android Client app release

**Comment by NeOMakinG** [comment]
Hello @cruzach, thanks a lot by taking care on this!

Yes I still understood It but it was to make the link between the bugs on standalone and Expo client which looks the exact same because on the standalone android apps it bugs at the exact same time and action and when I remove cameras actions it stop bugging.

Thanks a lot, that’s blocking for my project, can’t wait some news 👍

**Comment by cruzach** [comment]
Hey @NeOMakinG , looks like this is working as intended in a standalone APK for me. Make sure this APK was built after the fix from the issue you linked was released (should say when in that issue)

Here's my code, if it helps you to debug:

```
import React, { useRef } from "react";
import { StyleSheet } from "react-native";
import MapView from "react-native-maps";

export default function App() {
  const handleRegionChange = async () => {
    const camera = await this.mapRef.getCamera();
    alert(JSON.stringify(camera));
  };

  return (
    <MapView
      ref={e => (this.mapRef = e)}
      initialRegion={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421
      }}
      onRegionChangeComplete={handleRegionChange}
      style={styles.container}
    />
  );
}
const styles = StyleSheet.create({
  container: {
    flex: 1
  }
});
```

**Comment by NeOMakinG** [comment]
Did you try to change the region of the camera too? 

Next to my getCamera, I've a .animateToRegion, maybe that's the cause ? 

I rebuilded it yesterdays, it works perfectly fine on iOS and when I remove the camera parts it works on android, with the exact same environment as on the issue

Gonna give a try to your example but it's similar as my one in term of use

**Comment by NeOMakinG** [comment]
Some new @cruzach ? 😥

**Comment by cruzach** [comment]
Did you try my example? Did it crash for you?

**Comment by NeOMakinG** [comment]
Gonna try later without the animateToRegion, it will be the exact same code as your...

Coming back asap

**Comment by cruzach** [comment]
@NeOMakinG I tried to reproduce this with `animateCamera` and could not. Hopefully this snack will help you debug the code - https://snack.expo.io/@charliecruzan/animatecamera

If you still have issues, then please provide the exact steps to reproduce and I can reopen the issue
