### ISSUE TITLE
[iOS] LinearGradient transparent to white is wrong

### ISSUE THREAD

**Issue by charles-goode** [expo/expo#7418]
### Environment

Expo CLI 3.11.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

I'm on SDK 36
### Steps to Reproduce
Put a linear gradient over some colored background.
use `colors={['transparent' ,'white']}

### Expected Behavior
The android version is exactly as expected.

### Actual Behavior
The transparent to white gradient is kind of grayish on iOS. 

### Reproducible Demo
https://snack.expo.io/@charles.goode/thoughtful-apples

**Comment by mauriciord** [comment]
@charles-goode I think it's not a bug, you should try my reproducible demo here: https://snack.expo.io/@mauriciord/thoughtful-apples

Maybe you are wrongly using the `start` and `end` props

**Comment by charles-goode** [comment]
I'm still seeing the type of issue in your snack. At the very least, it is easy to observe there is a graphical difference between the iOS and Android versions. Secondly the android version appears to be correct.

**Comment by cruzach** [comment]
@charles-goode in @mauriciord 's snack it seems like this is working correctly to me

Could you provide more details as to what you think the bug is? Identifying a possible root cause would be very helpful

**Comment by charles-goode** [comment]
Do these look the same to you? The first is Android and the second is iOS. 
<img width="202" alt="android_grad" src="https://user-images.githubusercontent.com/41702266/77578769-248c7500-6ea7-11ea-9dea-8f6281bd668b.png">
<img width="209" alt="ios_grad" src="https://user-images.githubusercontent.com/41702266/77578778-281ffc00-6ea7-11ea-931c-5846abeb020d.png">
On the iOS version, the color gets darker in the middle of the gradient than at the top. But it is a transparent to white gradient; it should only get whiter/lighter.

**Comment by FiberJW** [comment]
I can confirm that this is a problem with Apple platforms, not necessarily Expo's implementation of LinearGradient.

To avoid the grays, the `'transparent'` has to be a transparent variation of the exact color that it's fading out of (think `rgba(...)`.

@tommybru found the solution here https://css-tricks.com/thing-know-gradients-transparent-black/

I have a reproduction case here on snack: https://snack.expo.io/@fiberjw/thoughtful-apples

![Reproduction Image](https://user-images.githubusercontent.com/12488826/87992067-49cb7180-ca9c-11ea-8e17-b7cd0b06ea77.jpg)

If you have another issue with LinearGradient, feel free to open a new issue!
