### ISSUE TITLE
[expo-font] Cannot resolve WOFF fonts using Font.loadAsync

### ISSUE THREAD

**Issue by blakeglucas** [expo/expo#7424]
### Environment
```
  Expo CLI 3.15.4 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

Targets: iOS, Android

### Steps to Reproduce

1. Create a new project using the blank typescript expo template
2. Install expo-font `expo install expo-font`
3. In App.tsx, add
```
...
import * as Font from 'expo-font'
...

export default function App() {

  React.useEffect(() => {
    const loadFonts = async () => {
        await Font.loadAsync({
          'avenir': require('./assets/fonts/AvenirMedium.woff'),
        })
      }
      
    loadFonts()
  }, [])

  return (
    // Your app/component
    <Main />
  )
}
```

### Expected Behavior

The Expo SDK should find and load the .woff font into the Expo font map for use in style objects.

### Actual Behavior

Fonts with a .ttf extension work fine. But when I use a font with a .woff extension, the following happens. I understand WOFF is a web font type, but it's *React* Native...

From the console:
```
Unable to resolve "./assets/fonts/Avenir-Medium.woff" from "App.tsx"
Error: Unable to resolve module `./assets/fonts/Avenir-Medium.woff` from `App.tsx`:

None of these files exist:
  * assets\fonts\Avenir-Medium.woff(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
  * assets\fonts\Avenir-Medium.woff\index(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
```

I'm newer to React Native, but in regular React, I would immediately guess that Webpack (or equivalent) does not have a loader established for *.woff files. My guess is whatever Expo uses to load files does not register .woff files as fonts. **.ttf files work**, so this is most likely the case.

### Reproducible Demo

https://snack.expo.io/Sk3Z6eQUI

I think there was a problem installing `expo-font` on snack, but the demo is valid.

**Comment by cruzach** [comment]
Does this work in a bare React Native project?

**Comment by IjzerenHein** [comment]
Hi 👋 

`.woff` fonts are not supported by react-native. Although they are [supported at the platform level on iOS](https://www.w3.org/Fonts/WG/WOFF2/Implementation.html) (and [woff2 as of iOS 10](https://stackoverflow.com/a/44866859/3785358)), they are not supported on the platform level on Android (only by its browser). They are therefore not a feasible option for usage with react-native/expo. You should use `.otf` or `.ttf`.

Other issue discussing woff #4626
