### ISSUE TITLE
iOS 11 requires a new permission for downloading pictures

### ISSUE THREAD

**Issue by dozoisch** [expo/expo#743]
iOS 11 added a new permission `NSPhotoLibraryAddUsageDescription` which is required to be there to be able to execute `CameraRoll.saveToCameraRoll` (see https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html). Currently saveToCameraRoll will crash the app.

Before only `NSPhotoLibraryUsageDescription` was needed!

Current workaround:

In app.json

```
"ios": {
  "infoPlist": {
    "NSPhotoLibraryAddUsageDescription": "Give <appName> permission to save to your photos",
  }
}
```

**Comment by terribleben** [comment]
Thanks - merged your PR https://github.com/expo/expo/pull/744 and will ship this in our next release.
