### ISSUE TITLE
Duplicate Calendar events being created 

### ISSUE THREAD

**Issue by Gardens18** [expo/expo#7430]
Below is the code I am using to create events in the calendar. But there is no mechanism in expo check whether the event is already exist before creating a new one, thus resulted in duplication of events created, need help on this.

=======================================================

export default class CalendarEvents extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      items: {},
      itemsCalendar: {},
      events: {},
      isLoading : true 
    }
  }

  render() {
    if(this.state.isLoading){
      return(
          <ActivityIndicator/>
      )
    }
    return (
      <Block flex>
        <Block flex style={styles.calendar}>
          <Agenda
            style= {styles.agenda}
            flex
            items={this.state.items}
            loadItemsForMonth={this.loadItems.bind(this)}
            renderItem={this.renderItem.bind(this)}
            renderEmptyDate={this.renderEmptyDate.bind(this)}
            rowHasChanged={this.rowHasChanged.bind(this)}
            // markingType={'period'}
            horizontal={true}
            pastScrollRange={6}
            futureScrollRange={6}
            markedDates={this.state.events}

            //theme={{calendarBackground: '#E4DCE6', agendaKnobColor: '#6B676C'}}
            theme={{  agendaTodayColor: '#0033A0',selectedDayBackgroundColor:'#0033A0',agendaKnobColor: '#84BD00'}}
            
            //renderDay={(day, item) => (<Text>{day ? day.day: 'item'}</Text>)}
          />
        </Block>
        <Block row style={styles.calendarLegends}>
          {calLegends.map((item, key) => (    
            <Block style={styles.legendCover} key={key}>
            <Block style={[styles.legend]} backgroundColor = { calLegends[key].color}></Block>
            <Text size={24}  style={styles.legendTitle}>{calLegends[key].title }</Text>
            </Block>
          ))}
        </Block>
      </Block>
    );
  }

  async componentDidMount() {
    const tdData = await getData("tdevents")
      .then(responseJson => {
        this.setState(
          {
            isLoading: false,
            itemsCalendar: responseJson
          },
          function() {}
        );
      })
      .catch(error => {
        console.error(error);
      });
  }

  loadItems(day) {
    setTimeout(() => {
      for (let i = -15; i < 85; i++) {
        const time = day.timestamp + i * 24 * 60 * 60 * 1000;
        const strTime = this.timeToString(time);
       this.state.items[strTime] = [];
        
        //var numItems = Math.floor(Math.random() * 5);
        const numItems = Object.keys(this.state.itemsCalendar.value).length;
     
        for (let j = 0; j < numItems; j++) {
          let momentStart = this.state.itemsCalendar.value[j].StartTime;
          let momentEnd  = this.state.itemsCalendar.value[j].EndTime;
          let momentDay = this.state.itemsCalendar.value[j].StartTime.substring(0,10);
          
          
          if (strTime == momentDay ){
       
            this.state.items[strTime].push({
              name: this.state.itemsCalendar.value[j].Title,
              location: this.state.itemsCalendar.value[j].Location,
              audience: this.state.itemsCalendar.value[j].Audience,
              type: this.state.itemsCalendar.value[j].Type,
              date:  momentStart ,
              start_time:  momentStart ,
              end_time: momentEnd
              // height: Math.max(50, Math.floor(Math.random() * 150))
            });
            if (this.state.itemsCalendar.value[j].Type == "2") {
              this.state.events[momentDay] = {
                selectedColor: organizationColor.selectedColor,
                selected: true
              };
            } else if (this.state.itemsCalendar.value[j].Type == "1") {
              this.state.events[momentDay] = {
                selectedColor: employeeColor.selectedColor,
                selected: true
              };
            } else if (this.state.itemsCalendar.value[j].Type == "3") {
              this.state.events[momentDay] = {
                selectedColor: dependentsColor.selectedColor,
                selected: true
              };
            } else if (this.state.itemsCalendar.value[j].Type == "4") {
              this.state.events[momentDay] = {
                selectedColor: outreachColor.selectedColor,
                selected: true
              };
            } else {
              // ignore
            }
          }
        }
      }

      const newItems = {};
      Object.keys(this.state.items).forEach(key => {
        newItems[key] = this.state.items[key];
      });
      this.setState({
        items: newItems
      });
    } );
    // console.log(`Load Items for ${day.year}-${day.month}`);
  }
  

  _askForCalendarPermissions = async () => {
    const response = await Permissions.askAsync(Permissions.CALENDAR)
    return response.status === 'granted'
  }

  _askForReminderPermissions = async () => {
    if (Platform.OS === 'android') {
       return true
    }

    const response = await Permissions.askAsync(Permissions.REMINDERS)
    return response.status === 'granted'
  }

  _findCalendars = async () => {

    const calendarGranted = await this._askForCalendarPermissions()
   
    const reminderGranted = await this._askForReminderPermissions()
    
    let calendars = []

    if (calendarGranted && reminderGranted) {
      calendars = await Calendar.getCalendarsAsync()
      
    }

    return calendars
  }

  _createNewCalendar = async (calendars) => {
    const newCalendar = {
      title: 'T&D Events',
      entityType: Calendar.EntityTypes.EVENT,
      color: '#2196F3',
      sourceId:
        Platform.OS === 'ios'
        ? calendars.find(cal => cal.source && cal.source.name === 'Default').source.id
        : undefined,
      source:
        Platform.OS === 'android'
        ? {
          name: calendars.find(cal => cal.accessLevel === Calendar.CalendarAccessLevel.OWNER).source.name,
          isLocalAccount: true
        }
        : undefined,
      name: 'T&D Events',
      accessLevel: Calendar.CalendarAccessLevel.OWNER,
      ownerAccount:
        Platform.OS === 'android'
        ? calendars.find(cal => cal.accessLevel == Calendar.CalendarAccessLevel.OWNER).ownerAccount
        : undefined
    }

    let calendarId = null

    try {   

       await calendars.filter(element => {
        if(element.title == newCalendar.title)
        {
         //await Calendar.createCalendarAsync(newCalendar);
         calendarId = element.id;
        }
        else
        {
         
        }

      });
      if(calendarId == null){
        calendarId = await Calendar.createCalendarAsync(newCalendar);
      }
       
    } catch (e) {
      Alert.alert('the calendar has not been saved', e.message)
    }

    return calendarId
  }

  _addEventsToCalendar = async (calendarId,item) => {
   
    const event = {
      // title: 'my cool event',
      // location: 'Route François-Peyrot 30, 1218 Le Grand-Saconnex',
      // startDate: moment().toDate(),
      // endDate: moment().add(1, 'hours').toDate(),
      // timeZone: 'Europe/Zurich'

      title:item.name,
      location: item.location,
      date:item.date,
      startDate: moment(item.start_time).toDate(),
      endDate: moment(item.end_time).toDate(),
     // startDate: moment().toDate(),
  //  endDate: moment().add(1, 'hours').toDate(),
      timeZone: 'GMT+3'
    }

    try {
      
      await Calendar.createEventAsync(calendarId, event)
    } catch (e) {
      Alert.alert('An error occurred while adding your unavailability to your calendar')
    }
  }

  synchronizeCalendar = async (item) => {
 
    let calendars = await this._findCalendars();
   
    const calendarId = await this._createNewCalendar(calendars);

    try {
      await this._addEventsToCalendar(calendarId,item)
      Alert.alert('The calendar has been synchronized')
    } catch (e) {
      Alert.alert('An error occurred while adding events to the calendar', e.message)
    }
  }

  renderItem(item) {
    return (
      <View style={[styles.item, { height: item.height }]}>
        
          <Text>Date: {moment(item.start_time).format('YYYY-MM-DD').toString()}</Text>
          <Text>From: {moment(item.start_time).format('h a').toString()}</Text>
          <Text>To: {moment(item.end_time).format('h a').toString()}</Text>
          <Text>Name:{item.name}</Text>
          <Text>Location: {item.location}</Text>
          <Text>Audience:{item.audience}</Text>
          {/* <Text>Type: {item.type}</Text> */}
          <TouchableOpacity  style={styles.addCover}  onPress={() => this.synchronizeCalendar(item)}>
          <Image source={ TDIcons[0].addCalendar.image} style={styles.tdicon} />
      
          <Text style={styles.addCalendar}>Add to Calendar</Text>

        </TouchableOpacity>
      </View>
    );
  }
  
  renderEmptyDate() {
    return (
      <View style={styles.emptyDate}>
        <Text />
      </View>
    );
  }

  rowHasChanged(r1, r2) {
    return r1.name !== r2.name;
  }

  timeToString(time) {
    const date = new Date(time);
    return date.toISOString().split("T")[0];
  }
}

==================================

**Comment by cruzach** [comment]
I think you can use [getEventsAsync](https://docs.expo.io/versions/latest/sdk/calendar/#calendargeteventsasynccalendarids-startdate-enddate) to get all the events and check for the one you're about to add

**Comment by Gardens18** [comment]
That needs ID of the event , could please elaborate how to pass the
existing events ID?

**Comment by Gardens18** [comment]
Dont close this until you provide the correct solution to this issue. getEventAsync does not help , do you have an example ?

**Comment by cruzach** [comment]
`getEventsAsync` does not require the event ID, please see the docs:
> Calendar.getEventsAsync(calendarIds, startDate, endDate)
