### ISSUE TITLE
Why can't we read title and body in Push Notifications?

### ISSUE THREAD

**Issue by donfour** [expo/expo#7431]
In my app, I would like to display any received notification's `title` and `body`. However, I couldn't find a straightforward way of reading them.

Currently, the [notification object](https://docs.expo.io/versions/latest/sdk/notifications/#notification) only includes `data`, but not `title` and `body`.

As a workaround, I had to duplicate `title` and `body` in the `data` object itself. As a result, I'm sending something like this to Expo:
```
{
  "to": "ExponentPushToken[xxxxxxxxxxxxxxxxxx]",
  "title": "some title",
  "body": "some body",
  "data": {
    "title": "some title",  <- the same title as above
    "body": "some body" <- the same body as above
  }
}
```
This looks kind of silly to me, is there a better way? Or have I missed anything. Thanks in advance!

**Comment by cruzach** [comment]
`data` is the only part of the notification object that is passed into the app, so the way you're currently handling it is correct 👍
