### ISSUE TITLE
Print.printToFileAsync HTML to PDF adds an extra blank page at the end

### ISSUE THREAD

**Issue by oebilgen** [expo/expo#7435]
### Environment

```
  Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      npm: 6.14.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4/11N132i - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.15.5
```
Observed in iOS, [Snack](https://snack.expo.io/r1IBgIW2B) confirms the issue in Android too. Web looks fine.

### Steps to Reproduce
This code creates an extra page at the end that is blank.
```javascript
const filePath = await Print.printToFileAsync({
    html: 'hello',
    base64: false
})
Sharing.shareAsync(filePath.uri)
```
I applied CSS for `html` such as 
```html
<html><head><style>@page { margin: 20px; height: 90%} html,body {height: 90%;} </style></head><body>hello</body></html>
```
but the blank page is there.

Also note that the images can be broken mid-page, half printed on page N, another half on page N+1 even with `page-break-inside:avoid;` (probably a separate issue)

### Expected Behavior
No unwanted blank page at the end

### Actual Behavior
See the blank page at the end even though I just printed a single word.
[B3662F39-75CF-4D3D-B6A4-C610B52A5447.pdf](https://github.com/expo/expo/files/4365645/B3662F39-75CF-4D3D-B6A4-C610B52A5447.pdf)

### Reproducible Demo
See the code above or the Snack https://snack.expo.io/r1IBgIW2B

**Comment by IjzerenHein** [comment]
Hi! Can you try adding the mobile viewport config to your html?

```html
<head>
  <meta name="viewport" content ="width=device-width,initial-scale=1,user-scalable=yes" />
</head>
```

I've also reduced the margins in your snack slightly, and it now prints a single page:

https://snack.expo.io/@ijzerenhein/print-local-image-example

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-27 at 17 54 25](https://user-images.githubusercontent.com/6184593/77780315-1760b900-7054-11ea-8be4-f3b57ea6e163.png)

**Comment by CapelliC** [comment]
@IjzerenHein: any idea why the local image doesn't show ? This problem is driving me crazy...

**Comment by IjzerenHein** [comment]
@CapelliC Have you checked the image URI? What does it say?

**Comment by CapelliC** [comment]
@ljzerenHein: seems ok to me

file:///var/mobile/Containers/Data/Application/04BA3873-9B3C-4204-A52B-E6F826C73336/Library/Caches/ExponentExperienceData/%2540capellic%252Fimgios/ImagePicker/D9AAF179-F001-4FCF-AEFF-6FF5273EE4A8.jpg

On iOS Expo Print refuses to show locally stored images, but on Android works as expected... and as it was doing (on iOS also) before the upgrade to ver.32, then 33, then 35 ... then 37 that I had to manage because of some recent minor 'improvements' introduced in my app

**Comment by IjzerenHein** [comment]
Hi, can you open a separate issue for this?

**Comment by CapelliC** [comment]
> Hi, can you open a separate issue for this?

Ok, thanks. I did managed to modify your sample to highlight the different treatment that file:// uris get on iOS vs Android. See https://github.com/CapelliC/expo-print-test-pdf-file-uri-missing-ios

**Comment by hipolitotata** [comment]
> > Hi, can you open a separate issue for this?
> 
> Ok, thanks. I did managed to modify your sample to highlight the different treatment that file:// uris get on iOS vs Android. See https://github.com/CapelliC/expo-print-test-pdf-file-uri-missing-ios.
> 
> Opened an issue at #7940

It's worked for me too, thankssss !!!!
