### ISSUE TITLE
Pausing / resuming Video on Android is laggy causes progress reset

### ISSUE THREAD

**Issue by rusakovic** [expo/expo#7446]
Hello.

Please, check, what is a problem.
I created a simple video player.
Problem: if you press play/pause button very often, the video after the pause move 0.5-1 sec forward.

Snack: https://snack.expo.io/@rusakovic/video-glitch-on-pause
If you press pause button at 4000ms, it forwards the video to 0 miliseconds.
But why not to pause at 4000ms? How to fix it? Thank you.

![dfgdfg](https://media.giphy.com/media/YNz0OvRJz2Iq4pcL4a/giphy.gif)

**Comment by cruzach** [comment]
Can you try using `videoRef.pauseAsync()`/ `videoRef.playAsync()` rather than setting `shouldPlay={isPaused}`? That tends to work better

**Comment by rusakovic** [comment]
> Can you try using `videoRef.pauseAsync()`/ `videoRef.playAsync()` rather than setting `shouldPlay={isPaused}`? That tends to work better

Thank you @cruzach !
**1.** I think it will be great to mention it in your documentation. And maybe provide some player examples with best practices. Like, loading, play/pause video and audio player . I know that it's all described into the doc, but for not such professionals as you and your team, it could be difficult. But maybe with this thread, we can create a good platform for editing Expo Video/Audio part 
[Audio Video Docs](https://docs.expo.io/versions/v36.0.0/sdk/av/)

**2.** Video player. Moving from component base of `<Video />` to `ref` base functionality leads to new questions.

**2.1** How to move correctly `PlaybackStatusToSet` of video out of the component?
Such, `isLooping`, `isMuted`, etc.?

**2.2.** What is the best practice for **Customizing Audio Mode**?  Is it good practice to do in in useEffect with zero dependencies?
[Enabling Audio and customizing Audio Mode](https://docs.expo.io/versions/v36.0.0/sdk/audio/#enabling-audio-and-customizing-audio-mode)

![image](https://user-images.githubusercontent.com/17801144/77624024-39721280-6f52-11ea-9c2f-ad778007c1db.png)


**2.3** How to work correctly with audio and video instances at the same time to make them sync? In this example [Github Expo Player](https://github.com/expo/playlist-example/blob/master/App.js) used only or video or audio at the same time.
Is it correct to use `Promise.all` `playAsync` for audio and video instances, like
`Promise.all(await playbackVideoObjectRef.current.playAsync(),
      await playbackSoundInstance.playAsync())`

![image](https://user-images.githubusercontent.com/17801144/77624068-4f7fd300-6f52-11ea-98fc-c29b05a45aea.png)

Snack of current question: https://snack.expo.io/@rusakovic/video-glitch-on-pause

Thank you in advance. Thank you for your job! I'm trying to improve the docs for avoiding repetitive question, and writing a good code with best practicing, using Expo!

**Comment by rusakovic** [comment]
@cruzach 
Thank you.
But with sound and video instances together this bug is not disappear. 
Could you, please, check it?

**Comment by rusakovic** [comment]
@cruzach 
Could you, please, check this issue?
Because it seems as bug, we we trying play/stop with video and audio at the same time.
Thank you

**Comment by ninjz** [comment]
Yeah, I also have been calling `videoRef.pauseAsync()/ videoRef.playAsync()` and experience the a similar issue as @rusakovic though it seems when I call pauseAsync the video actually pauses a few ms from the current position so I see that video go back a couple of frames when hitting pause.

I was previously using `react-native-video` and did not seem to have this issue even when their lib does not support imperative play/pause.

**Comment by IjzerenHein** [comment]
Hi! Unfortunately, changing the `shouldPlay` prop was causing the source video to be reloaded, which caused this problem. We've fixed this in PR #9569.
