### ISSUE TITLE
expo-location:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by zanisis** [expo/expo#7448]
## 🐛 Bug Report

> Task :expo-location:compileDebugJavaWithJavac FAILED
/Users/macbook/Desktop/work/gold-shop-app/node_modules/expo-location/android/src/main/java/expo/modules/location/LocationMo
dule.java:21: error: cannot find symbol
import androidx.annotation.NonNull;

### Environment

Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.15.5

Eject Expo
Android
### Steps to Reproduce

when i upgrade sdk from sdk 35 to sdk 36

it's cannot build android apk for debug or development

when i try with or not package.json expo-location it's still same not work

**Comment by cruzach** [comment]
If you're using Expokit, I recommend using the bare workflow instead. I'd try testing this out on a fresh bare workflow project and seeing if you hit the same error

**Comment by tsapeta** [comment]
☝️ comment above explains everything – closing it but feel free to comment here if this is still an issue, especially in the most recent SDK.
