### ISSUE TITLE
iOS: When Video format is not supported, return more descriptive error instead of -11828 "AVFoundationErrorDomain"

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#745]
`The AVPlayerItem instance has failed with the error code -11828 and domain "AVFoundationErrorDomain"`

I get this error when loading a remote url with a webm format coming from a youtube stream.

**Comment by tcdavis** [comment]
Can you provide a [snack](https://snack.expo.io) that replicates this issue?

**Comment by alejomendoza** [comment]
@tcdavis here is the snack https://snack.expo.io/HkFjpyhhW , the url used there expires in 5 hours I also noticed that the link doesn't have an extension like `.mp4` that might be related. 
<img width="1265" alt="screen shot 2017-10-11 at 2 15 18 pm" src="https://user-images.githubusercontent.com/5351127/31461370-f516baa4-ae8e-11e7-95ee-3f7a280923fc.png">

**Comment by ccuilla** [comment]
We are seeing something a bit different but wonder if it is related. This is with audio:

```
          const playbackObject = new Audio.Sound();
          await playbackObject.loadAsync({ uri: myURI }, {}, true);
```

And this error:

```
{ [Error: The AVPlayerItem instance has failed with the error code -1100 and domain "NSURLErrorDomain".]
  line: 78320,
  column: 35,
  sourceURL: 'http://packager.ib-xcj.ccuilla.mobile.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles' }
```

**Comment by ide** [comment]
Regarding the original issue at hand -- iOS doesn't come with WebM support right now. These are the formats that Apple currently says they support:

- H.264 video, up to 1.5 Mbps, 640 by 480 pixels, 30 frames per second, Low-Complexity version of the H.264 Baseline Profile with AAC-LC audio up to 160 Kbps, 48 kHz, stereo audio in .m4v, .mp4, and .mov file formats
- H.264 video, up to 768 Kbps, 320 by 240 pixels, 30 frames per second, Baseline Profile up to Level 1.3 with AAC-LC audio up to 160 Kbps, 48 kHz, stereo audio in .m4v, .mp4, and .mov file formats
- MPEG-4 video, up to 2.5 Mbps, 640 by 480 pixels, 30 frames per second, Simple Profile with AAC-LC audio up to 160 Kbps, 48 kHz, stereo audio in .m4v, .mp4, and .mov file formats
- Numerous audio formats, including the ones listed in Audio Technologies

https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/MediaLayer/MediaLayer.html#//apple_ref/doc/uid/TP40007898-CH9-SW6

That error code is cryptic though, would be better to report something more understandable.
