### ISSUE TITLE
[docs] Update payments docs: use bare instead of expokit

### ISSUE THREAD

**Issue by ericruleman** [expo/expo#7452]
On https://docs.expo.io/versions/latest/introduction/why-not-expo/, it says:

"One of the most frequent requests we get is for In-App Purchases and Apple and Google Pay integration. We haven't built this yet, but it's on the roadmap."

Checking out https://docs.expo.io/versions/v36.0.0/sdk/payments/, Apple Pay seems to have been added! So documentation needs to be updated.

**Comment by cruzach** [comment]
Hi! That's under the `Limitations of the managed workflow` section, and currently the Payments module is only available in the bare workflow. Although the payments docs - https://docs.expo.io/versions/v36.0.0/sdk/payments/ -  do need to be updated to recommend the bare workflow, and not Expokit

**Comment by EvanBacon** [comment]
Duplicate #6922
