### ISSUE TITLE
expo react native crashing on ios real device.

### ISSUE THREAD

**Issue by Mahesha-Bhat** [expo/expo#7453]
### Environment
Expo CLI 3.11.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832

target:
We use VNC, to project it for user interface access. The devices which we have are iPhone 5s and iPhone 6. 

### Steps to Reproduce
-build the app using expo build:ios
-installing though ios-deploy or impactor on ios real device will with crash. 

crash report:
 
```
error: Error Domain=BKSProcessErrorDomain Code=1 
"Unable to bootstrap process with bundleID com.aq.FOGVERSION2"
 UserInfo={
NSLocalizedDescription=Unable to bootstrap process with bundleID com.aq.FOGVERSION2,
 BKSProcessExitReason=0, 
NSLocalizedFailureReason=Failed to start job,
 NSUnderlyingError=0x282299320 
{Error Domain=NSPOSIXErrorDomain Code=3 
"No such process" 
UserInfo={NSLocalizedFailureReason=The process failed to exec, NSLocalizedRecoverySuggestion=Consult /var/log/com.apple.xpc.launchd/launchd.log 
for more information, NSLocalizedDescription=Unable to get valid task name port right for pid 2019}},
 BSErrorCodeDescription=bootstrap-failed}
```

please help me to fix this.

**Comment by cruzach** [comment]
Hi, can you provide everything we request in the bug report template? Specifically, we need a method to reproduce this locally ourselves, in an as-close-to-blank project as possible.

**Comment by Mahesha-Bhat** [comment]
hi,
I executed 'xattr -cr path/to/your.app' command then it got installed in simulator. but its crashing in the real device. i have no idea which method is causing this issue.

**Comment by cruzach** [comment]
Is this a simulator build? Otherwise, you should use an IPA and test through testflight

When filing a bug report, it's really important to provide all the steps to reproduce the problem. I'll be happy to re-open this once that's been provided 👍
