### ISSUE TITLE
AppleAuthentication – where is the “Sign up with Apple” option?

### ISSUE THREAD

**Issue by darrylyoung** [expo/expo#7454]
Hi, everyone.

I’m looking at using the `AppleAuthentication` module and I noticed that the only options for the text of the button are “Sign **in** with Apple” and “Continue with Apple”. There’s no option for “Sign **up** with Apple”, which is another option shown [here](https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/#creating-a-custom-sign-in-with-apple-button) in Apple’s Human Interface Guidelines. Here's what Apple show in their documentation.

<img width="754" alt="Screenshot 2020-03-24 at 09 54 51" src="https://user-images.githubusercontent.com/1460800/77406840-8a003900-6db5-11ea-9c23-4220b9c67d0d.png">

The `AppleAuthentication.AppleAuthenticationButtonType` enum type [only offers](https://github.com/expo/expo/blob/sdk-36/packages/expo-apple-authentication/src/AppleAuthentication.types.ts#L213-L216) the two I mentioned. Is there a reason the sign **up** version isn’t available?

Thanks!

**Comment by IjzerenHein** [comment]
Hi! The `sign up` option was added later by Apple in iOS 13.2 (that's why it's not in there currently).

We'll going to add it 👍

**Comment by darrylyoung** [comment]
Hi, @IjzerenHein. 👋

Thanks for taking a look at this. I’m happy to hear that it’ll be added. Thank you!
