### ISSUE TITLE
[Web] Camera shows a black screen after going back from another screen.

### ISSUE THREAD

**Issue by deathemperor** [expo/expo#7455]
### Environment

```
Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.4 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: file:./sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.1.2
```

**Expo web**

### Steps to Reproduce

I use the snack example on [this document](https://docs.expo.io/versions/latest/sdk/camera/) for camera. My project use react-navigation, specifically stack navigator on WEB Platform.

### Expected Behavior

When navigating from camera then go back, camera works (images that can be captured are visible).

### Actual Behavior

**On Web**: When navigating from camera then go back, camera shows black screen. When captured, it returns a black image. This only happens on iOS (I guess Android will too). I've read somewhere in the expo forum that if camera is opened by a second screen it will be black like described.

### Reproducible Demo

I don't have any. But a recording of what happens can be seen here: https://photos.google.com/share/AF1QipMIRatNFgainlw3XBngicbG4Y5ZXxwLsyaPld1EjEPXttx9lRAR7A1_r23sSWmRzQ?key=VW5PRFhIbGwxRHppZlc2RkxySnZ3WHBFaUEtTXZR

**Comment by cruzach** [comment]
Hi! This seems like it may be a duplicate of - https://github.com/expo/expo/issues/5952, correct me if I'm wrong though

**Comment by deathemperor** [comment]
@cruzach thanks for pointing that out. I tried using withNavigationFocus without any luck. The code:

```js
<View>
{props.isFocused ?
   <Camera type={Camera.Constants.Type.back} ref={ref => {camera = ref;}}>
    </Camera>
: null}
</View>
```

FYI: when running this code on Chrome on MacOS, the "this tab is using camera" indicator still shows even isFocused = false (aka, Camera component is removed).

**Comment by cruzach** [comment]
Sorry, I'm just now seeing you said this is specific to Web. I think then that this might be related to using `react-navigation` on web, which is still pretty early on in terms of support. Unless you see the same behavior on android/ios

**Comment by deathemperor** [comment]
I can confirm that using `withNavigationFocus` fix this after further testing. Thanks!
