### ISSUE TITLE
[ Expo web ] - wrong element width in web, same code fine on Android

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#7458]
### Environment

```
Environment info:
System:
  OS: macOS 10.15.3
  Shell: 5.7.1 - /bin/zsh
Binaries:
  Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
  npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
  Android Studio: 3.4 AI-183.5429.30.34.5452501
  Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
npmPackages:
  expo: ~36.0.2 => 36.0.2
  react: ^16.13.1 => 16.13.1
  react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
npmGlobalPackages:
  expo-cli: 3.15.5
```

### Steps to Reproduce

[Open this snack](https://snack.expo.io/ryGhucvLU), notice that the header bar width is wrong on web, but fine on android.

### Expected Behavior

Header bar at full width on both android and web.

### Actual Behavior

Android works fine, web shows a wrapping div that makes the header smaller than it should be.

### Reproducible Demo

```js
import React from 'react';
import { Text, View, } from 'react-native'
import { Appbar } from 'react-native-paper'

export default class App extends React.Component {
  render() {
    return (
      <View style={ { flex: 1, flexDirection: 'column', alignItems: 'flex-start' } }>
        <Appbar.Header style={ { width: '100%', paddingVertical: 30 } }>
	          <Appbar.Content title={ 'title' } subtitle={ 'subtitle' }/>
        </Appbar.Header>
        <Text>Hello</Text>
      </View>
    );
  }
}
```

**Comment by cruzach** [comment]
This issue seems like it might be better suited for either the `react-native-paper` repo, or `react-native-web` repo

**Comment by actuallymentor** [comment]
Seeing as it's a translation problem from native to web it is either you or `react-native-web`. What more info do you need?

**Comment by cruzach** [comment]
does a plain RN web project result in the same issue?

**Comment by actuallymentor** [comment]
I have no idea and have never worked with `react-native` outside of expo. If there is a snack-like platform for react native I'm happy to give it a go.
