### ISSUE TITLE
Unable to use barcode scanner on iOS simulator

### ISSUE THREAD

**Issue by mgwidmann** [expo/expo#746]
Heres what I get:

![image](https://user-images.githubusercontent.com/5035724/31313838-086aa374-abbd-11e7-97fc-635a0e1d5cfb.png)

Works fine when running on an actual device. Heres my code: https://github.com/mgwidmann/slack_coder/tree/357226d46b73cb6a1fdc1cfa7b03fa4d48732380/client/mobile
And commenting out this line makes the app work properly:
https://github.com/mgwidmann/slack_coder/blob/357226d46b73cb6a1fdc1cfa7b03fa4d48732380/client/mobile/app/components/Login.js#L39

Edit: Pointed to specific commit instead of master so that it won't change

**Comment by quinlanj** [comment]
hi @mgwidmann , because you cannot use the camera in the simulator, our code is crashing. cc: @aalices - maybe we can prevent the app from crashing altogether when the camera is not available?

**Comment by aalices** [comment]
Hey! BarCodeScanner will be using `Camera` component soon so it should be fixed then. The same for https://github.com/expo/expo/issues/758

**Comment by rgangopadhya** [comment]
Thanks @aalices!
