### ISSUE TITLE
`exp://` protocol changed once app is ejected :fire:

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo#7461]
For example it seems like there is some hash behind the protocol in ejected apps - which a normal expo client doesn't know how to handle.

However if I copy the string and then remove the hash it functions properly (at least without using non-expo linked libraries).

e.g) we get something like this from `expo start` from an ejected app

```
exp30fj8d0sxxxxxxxx://192.168.100.172:19000
```
and when we remove the hash from the protocol, like so:

```
exp://192.168.100.172:19000
```

It functions, is this expected? My expectation would be that a normal expo client should be able to run it, and it would have the same `exp://` protocol.

I've read this result: https://github.com/expo/expo/issues/508 but in our case removing the hash *does* work - and we'd like to keep it working in expo clients if possible. We recognize that any functionality using native libraries, not from expo, will not work. But that's fine for us as most of the app doesn't.

Is there a way to circumvent/stop this protocol behaviour?

**Comment by cruzach** [comment]
You may be able to dig and find where this is happening, but since the expected behavior is for Expokit apps **not** to run in the Expo client app, I'm not sure it makes sense to change this for everyone. 

I should mention that we plan on deprecating the Expokit workflow soon, and suggest you look into transitioning to the bare workflow. Happy to answer any questions about that!

**Comment by jonathanstiansen** [comment]
@cruzach we're still early in testing ExpoKit - but it seems like bare workflows don't offer OTA's vs ExpoKit. Is that the big negative to bare workflow?

On a side note - we can't seem to get OTA's updates to propagate to testflight apps.

**Comment by cruzach** [comment]
That is, but in just a few days we'll be releasing our Updates module for the bare workflow, so you don't have to wait too long!

> we can't seem to get OTA's updates to propagate to testflight apps

This is probably a configuration issue in `EXShell.plist`. Make sure you are publishing from the correct Expo account and to the correct release channel

**Comment by jonathanstiansen** [comment]
@cruzach awesome! where will I see this announcement?
