### ISSUE TITLE
using Updates in web (SSR) causes error

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#7463]
### Environment

  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 5.3.0-beta.22 => 5.3.0-beta.22 
      @types/react: ^16.8.22 => 16.9.23 
      @types/react-native: ^0.60.3 => 0.60.31 
    npmGlobalPackages:
      expo-cli: 3.8.0

### Steps to Reproduce

use `update` on a server rendered page

### Expected Behavior

Works

### Actual Behavior

`ReferenceError: localStorage is not defined`

**Comment by cruzach** [comment]
I think this SO may shed some light here- https://stackoverflow.com/questions/52474208/react-localstorage-is-not-defined-error-showing

**Comment by EvanBacon** [comment]
I updated both updates packages to be SSR compliant in #7625
