### ISSUE TITLE
InAppPurchases setPurchaseListener

### ISSUE THREAD

**Issue by StevenHarlow** [expo/expo#7468]
With InAppPurchases setPurchaseListener, it states:
`You should set the purchase listener globally, and not inside a specific screen, to ensure that you receive incomplete transactions, subscriptions, and deferred transactions`

Is it global enough to set the listener in the main function App() definition? (the function that gets passed to the main AppRegistry.registerComponent call?)

**Comment by cruzach** [comment]
I don't believe so... you'll need to declare it in the global scope. But feel free to test out your use case and let us know if it works, may be worth a docs PR 😄

**Comment by kot-ezhva** [comment]
> I don't believe so... you'll need to declare it in the global scope. But feel free to test out your use case and let us know if it works, may be worth a docs PR 😄

"Global scope" is where?

**Comment by darrylyoung** [comment]
Where did you end up putting the listener, @StevenHarlow? I'm looking to implement in-app purchases in my Expo app and wondered the same thing. The documentation is great in that it describes well how the API works but I'd love to have seen a proper working example.

**Comment by puzpuz** [comment]
Anyone have answer for this? I also struggling on putting the listener. Where is the proper place to place this? 
Where do you mean by global scope? @cruzach

**Comment by darrylyoung** [comment]
@puzpuz I ended up putting the listener in my `App.tsx`  in a `useEffect`. Basically, when the app initially loads, I connect to the store, set the listener, get available purchases, and then disconnect. Then, when a user is trying to purchase via a modal I have elsewhere, I connect to the store when it mounts, deal with the purchase, and then disconnect when it unmounts (in the `return` of a `useEffect`). As the listener was initially set in `App.tsx`, it's _global_ in that it's available throughout the app.

**Comment by puzpuz** [comment]
Thank you @darrylyoung . I use class base component, but I generally get what you mean.
I tried to put my listener in the `App.js` , 

I am not sure if this is the correct place to ask this,
But I find difficulties on getting the transaction ID stored in our own DB, 
In brief my flow would be like this

1. on checkout page, my customer press buy the item
2. I connect to store and on the callback I call my API to set transaction record (as pending). Here I get a **transaction ID**
3. after that I call `purchaseItemAsync` to execute the purchasing
4. My plan is, when the `setPurchaseListener` triggered, I will update the transaction record status accordingly

But if `setPurchaseListener` put under app.js, how would I know which transaction ID I have to update? I thought of using redux to store the transaction ID, but sometimes when the transaction is initially in pending state, I'm afraid that when the transaction is resolved, the transaction ID data is gone. And I don't think we can call redux state in App.js though
