### ISSUE TITLE
how to understand device is rooted?

### ISSUE THREAD

**Issue by milad1367** [expo/expo#747]
I want to know if the device has been rooted, or not? I looked at react native library as well as the expo and did not find anything.

Also, I want to have a list of installed apps on the phone.

**Comment by dikaiosune** [comment]
Hi! This seems like a good question for StackOverflow or our forums. We're trying to keep GitHub issues focused on bug reports.

**Comment by milad1367** [comment]
Thanks for your reminder. But my goal was to help you if you could.
