### ISSUE TITLE
[ Web ] expo-image-picker  getCameraPermissionsAsync not a function

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#7470]
### Environment

```shell
  Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
      npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.2 => 36.0.2
      react: ^16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.15.5
```

Target: web.

### Steps to Reproduce

Use `ImagePicker.getCameraPermissionsAsync()` as per documentation in a browser environment.

### Expected Behavior

To ask for permissions.

### Actual Behavior

Function does not exist. I ended up using the `Permissions` module directly which works fine.

### Reproducible Demo

[Snack](https://snack.expo.io/@mentor/intrigued-cake).

**Comment by cruzach** [comment]
Does this happen when running locally, as well (not in a snack)? That module [should fallback to the Permissions methods](https://github.com/expo/expo/blob/sdk-36/packages/expo-image-picker/src/ExponentImagePicker.web.ts#L47)

**Comment by actuallymentor** [comment]
@cruzach yes locally too. Though I suspect you confirmed that if I'm reading the label/assignment  logs right.
