### ISSUE TITLE
Using MailCompser, working examples as mine stopped working

### ISSUE THREAD

**Issue by teckel12** [expo/expo#7472]
### Environment

  Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^2.11.2 => 2.11.2 
    npmGlobalPackages:
      expo-cli: 3.15.5

Target app: iOS/Android

### Steps to Reproduce

```
import { MailComposer } from 'expo';

        MailComposer.composeAsync({
            subject: 'test',
            body: 'test',
            recipients: ['teckel@domain.com'],
            isHtml: true
        });
```
### Expected Behavior

Should open an email, like it did previously

### Actual Behavior

Throws the error:

> TypeError: undefined is not an object (evaluating `_expo.MailComposer.composeAsync')

**Comment by teckel12** [comment]
So I did a
```
expo install expo-mail-composer
```
And then tried to do:
```
pod install
```
But `cococapod` wasn't installed.  So I installed it, went to the `ios` folder but it throws the error
```
[!] No `Podfile' found in the project directory.
```
Seems there's been some changes since this last worked as I don't believe I had to install cocoapod before for this to work.

Thnaks!

**Comment by teckel12** [comment]
Looking at the "limited" documentation here:

https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/mail-composer.md

I'm a "learn by example" coder, and just showing the method syntax as in above is difficult to understand.  It would seem the issue has something to do with `saveOptions` as I'm not using that.  But, without an example, I'm not really sure what the code should look like.

**Comment by brentvatne** [comment]
from the docs:

<img width="661" alt="Screen Shot 2020-03-25 at 10 59 57 AM" src="https://user-images.githubusercontent.com/90494/77569668-c56b3800-6e87-11ea-8b89-a503af6ea72d.png">

notice `import * as MailComposer from 'expo-mail-composer';`

**Comment by brentvatne** [comment]
here's an example you can run on your phone: https://snack.expo.io/@notbrent/mailcomposer

**Comment by teckel12** [comment]
@brentvatne Thanks.  It's still a bit confusing as it seems that it still needs to be installed via: 
```
expo install expo-mail-composer
```
even though that's in the `bare React Native` section.  For the API section, it says nothing about installing expo-mail-composer.  So still a bit confused, it seems it needs to be installed.

**Comment by brentvatne** [comment]
it's actually not in the bare react native section, it's just in the installation section. perhaps this needs to be made more clear.

the API section doesn't mention Installation instructions because that's what the Installation section is for

**Comment by teckel12** [comment]
@brentvatne Got it, thanks again!  The example was super-informative!

**Comment by Pat-Gekoski** [comment]
@brentvatne I can't find an example anywhere online or in the MailComposer documentation on how we would use MailComposerStatus to determine if the email was sent. Can you point me in that direction?

**Comment by Fabzien** [comment]
@Pat-Gekoski 

You can use something like that:

```
MailComposer.composeAsync({
                    recipients: EMAILDEST,
                    subject: YOURSUJECT,
                    body: YOURBODY,
                    attachments: YOURFILE
                }).then((data) => {
                    if (data.status == 'sent') {
                           // YOUR CODE
                    }
                })
```

**AFAIK, it's only working on iOS. On Android there is no return after using MailComposer.**
