### ISSUE TITLE
Error: Package is no longer supported: Asset

### ISSUE THREAD

**Issue by surbhitrao** [expo/expo#7475]
### Environment
Expo CLI 3.15.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - D:\Program Files\Yarn\bin\yarn.CMD
      npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 

iOS, Android 

### Steps to Reproduce

Added my images in the root assets folder of my project  

### Expected Behavior

 How did you expect your project to behave?
This error shouldn't have been there. I am not able to debug anything else because of this spam

### Actual Behavior

 Will attach a screenshot

![Screenshot_2](https://user-images.githubusercontent.com/13431596/77571135-d69d5e80-6ef2-11ea-9733-edec36cf05ff.jpg)

**Comment by tonnenpinguin** [comment]
You did install expo-asset and change all the imports as noted in the error message, right?

**Comment by surbhitrao** [comment]
> You did install expo-asset and change all the imports as noted in the error message, right?

Yes I did install it also there were no imports in my project that's why I find it even more strange

**Comment by cruzach** [comment]
Can you provide a reproducible demo for this? @tonnenpinguin is right, this is usually caused by your project having an `import {asset} from 'expo';` somewhere in it

**Comment by surbhitrao** [comment]
> Can you provide a reproducible demo for this? @tonnenpinguin is right, this is usually caused by your project having an `import {asset} from 'expo';` somewhere in it

I searched my whole project including node modules but couldn't find a single `import {asset} from 'expo';` . Meanwhile I'll try and make a reproducible demo
