### ISSUE TITLE
expo-three's createTextureAsync doesn't work with photos from ImagePicker

### ISSUE THREAD

**Issue by twhitnah** [expo/expo#748]
As far as I can tell, there is no way to load an image from the ImagePicker, because createTextureAsync requires an Asset and Asset's can only be loaded from locally packaged modules while launchImageLibraryAsync returns an ImageResult.  Is there function that bridges these two classes or is this just not possible with expo-three?

**Comment by tcdavis** [comment]
It's possible to construct Assets directly, although the documentation could be improved: https://snack.expo.io/@thetc/asset-from-imagepicker

**Comment by twhitnah** [comment]
Thanks, that looks like it could work (I'll need to try it out at home tonight).  I thought it might be possible, but then I saw the constructor expected it a hash and I didn't see a way to calculate it, so I didn't think it was intended to be constructed directly.

Thanks.
