### ISSUE TITLE
Concurrent mode / custom main / index.js

### ISSUE THREAD

**Issue by natew** [expo/expo#7483]
This is maybe part question but also part bug. I can't seem to customize the entry. I set `"main": index.js` in my package.json and add index.js, but that doesn't seem to pick it up.

I'm trying to test out concurrent mode for the web app, but without being able to change the index and control the render, I can't. I see in docs that it should be possible though.

I did eject the webpack config, but I see it has a function as entryPoint.

So two things: I think I have a bug not allowing me to customize the render, and second is, what are plans for concurrent mode first class? I do see a couple views throwing warnings still on will/didmount.

**Comment by cruzach** [comment]
Hi! If this is a meant to be part bug report, could you fill out the issue template? Include your version of `expo-cli` and a way to reproduce the issue you're experiencing

**Comment by natew** [comment]
I guess it's a bug? Should I need to do anything besides have a index.js and have package.json main point to it? 

I can try a new expo project and see if it's the same but it's more of a question, I think I'm missing something, perhaps ejecting webpack is the culprit?.

```
  Expo CLI 3.16.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /var/folders/ss/ppy_gf99651fh1lcfms7xhrm0000gn/T/yarn--1585359976921-0.5260843861596345/node
      Yarn: 1.21.1 - /var/folders/ss/ppy_gf99651fh1lcfms7xhrm0000gn/T/yarn--1585359976921-0.5260843861596345/yarn
      npm: 6.13.4 - ~/n/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2
      react: 0.0.0-experimental-aae83a4b9 => 0.0.0-experimental-aae83a4b9
      react-native: ~0.61.4 => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.13.1
```

**Comment by EvanBacon** [comment]
seeing as concurrent mode is still experimental https://reactjs.org/docs/concurrent-mode-intro.html we won’t be investigating supporting it for the time being. As you mentioned, some components in upstream react native web are still using legacy methods like will mount. In order to update to the latest version of react native web we need to fix the community modules that were split out of react native in lean core and effectively broke web support.

**Comment by EvanBacon** [comment]
I can confirm that setting a custom main entry point to `index.js` in the `package.json` does work as expected. Maybe check to ensure you aren't defining a higher priority entry point in `app.json`.
