### ISSUE TITLE
Cannot run into android emulator after updated ( 3.15.4 )

### ISSUE THREAD

**Issue by rbayuokt** [expo/expo#7484]
https://stackoverflow.com/questions/60815264/expo-react-native-couldnt-start-project-on-android-the-system-cannot-find-the/

**Comment by IjzerenHein** [comment]
Hi, can you try deleting `node_modules` and `package-lock.json`, and re-installing the packages?

**Comment by rbayuokt** [comment]
> Hi, can you try deleting `node_modules` and `package-lock.json`, and re-installing the packages?

in project or in npm folder (?)

**Comment by rbayuokt** [comment]
Couldn't start project on Android: The system cannot find the path specified.

I still got that error , even I update my expo sdk to 37 , please help me , I can't forever run this project with hotspot , I need run project with local

**Comment by IjzerenHein** [comment]
It almost seems that it cannot launch the Android emulator. Does it also happen when you have the Android emulator already running?

**Comment by rbayuokt** [comment]
> It almost seems that it cannot launch the Android emulator. Does it also happen when you have the Android emulator already running?

yes, I have already running my android emulator , after this update I can run with expo cli , before this update I can run rn expo in local with android emulator without problem, I think it's only me, all of my friends have this issue too, please help me

**Comment by IjzerenHein** [comment]
@cruzach have you seen something like this before? Any ideas on what he could try or do?

**Comment by cruzach** [comment]
have you tried clearing the cache with `expo start -c`? Also removing your project's `.expo` directory

Just some other ideas- we've been upgrading `expo-cli` quite a bit, so installing the latest version, 3.17.20, is a good idea.

**Comment by rbayuokt** [comment]
> have you tried clearing the cache with `expo start -c`? Also removing your project's `.expo` directory
> 
> Just some other ideas- we've been upgrading `expo-cli` quite a bit, so installing the latest version, 3.17.20, is a good idea.

I've clearing cache , but there is no effect at all, still can't running on android emulator , I'm using latest version of expo-cli too, my friends too, we're frustating right now, we've tried everything but still doesn't work :(

**Comment by rbayuokt** [comment]
before this version my android emulator detected on metro bundler, but after I update to latest version my emulator not detected, also my friends

**Comment by brentvatne** [comment]
try this:
- open the expo client in the android emulator and sign in to your expo account
- look in the projects tab for the projects in development and open it

does that work for you?

the error that you are seeing is coming from here: https://github.com/expo/expo-cli/blob/1db469f5310d390f8d84a7aa2c485fdd726e3b8f/packages/xdl/src/Android.ts#L404-L421

**Comment by rbayuokt** [comment]
I've try that, but still not working, I've seen my project appear in development but when I click it it says error like this :
" Something went wrong , could not load exp://127.0.0.1:19000 "

it never happen to me before, why I got this ? before this ver I always running like this and have no problem, we're confusing right now because this issue

**Comment by mschipperheyn** [comment]
I have the same issue after my local ip changed from 192.168.0.3 to 192.168.0.9. Can't access any network anymore on the emulator. Including websites from Chrome.

**Comment by mschipperheyn** [comment]
The solution that works for me is ridiculous but it does work (Mac OS):
```
Disable laptop Wifi
Turn off emulator
Do a cold boot start of the emulator
Enable laptop wifi
Empty the Expo app cache
yarn start expo:clean
```

**Comment by tsapeta** [comment]
I hope the above comment is the proper solution to this problem ☝️ so I'm closing it.
