### ISSUE TITLE
Activate audio for videos using expo-av while iOS Silent Switch is On 

### ISSUE THREAD

**Issue by rafmst** [expo/expo#7485]
Is it possible to ignore iPhone devices Silent Switch and still display audio on videos, when using expo-av library? I saw some comments on how to do it in pure React Native using a flag like `ignoreSilentSwitch` but this didn't work for expo-av Video component.

Any ideas?

**Comment by cruzach** [comment]
see the `playsInSilentModeIOS` argument in the documentation - https://docs.expo.io/versions/latest/sdk/audio/#audiosetaudiomodeasyncmode

**Comment by rafmst** [comment]
This works also for video? My case is with video audio, not audio tracks alone

**Comment by cruzach** [comment]
from the [video docs](https://docs.expo.io/versions/latest/sdk/video/):
> The audio experience of video (such as whether to interrupt music already playing in another app, or whether to play sound while the phone is on silent mode) can be customized using the Audio API.

**Comment by rafmst** [comment]
Thanks a lot for helping me. I hope you have a nice weekend 🙂

**Comment by takeerdevs** [comment]
@rafmst did you know how to do it in video.. if yes, please share how you've done. Thanks.

**Comment by maurovisintin** [comment]
Something like

`
  useEffect(() => {
    Audio.setAudioModeAsync({
      playsInSilentModeIOS: true
    });
  });
`

**Comment by sethgw** [comment]
Sorry to comment on a closed thread, but this doesn't seem to work for me. 

Could you take a look at this Snack and tell me what I'm missing? 

https://snack.expo.io/@fluid/expo-av-video-silentmode

**Comment by TylerOlthuizen** [comment]
@sethgw did you ever figure this out? I'm having the same issue :/

**Comment by adscud** [comment]
Any news ?

**Comment by sethgw** [comment]
No updates

**Comment by adscud** [comment]
I could provide a tricks if you want. 
You just have to run a silent sound and it works.

```
React.useEffect(
        () => {
            // Tricks to fix that the audio doesn't work even if we set the configuration on iOS: `playsInSilentModeIOS`
            if (Platform.OS === 'ios') {
                const playSilentSound = async () => {
                    await sound.loadAsync(require('./silent-sound.mp3'))
                    await sound.playAsync()
                    await sound.setIsLoopingAsync(true)
                }
                void playSilentSound()
            }

            return () => {
                void sound.stopAsync()
                void sound.unloadAsync()
            }
        },
        [ ],
    )
    ```
    
    It works great for my project, I hope for you too.

**Comment by stuckj** [comment]
I just ran into this. There's a bug. I submitted a new ticket for it here: https://github.com/expo/expo/issues/13617.

@cruzach, thanks for the snack. I made one small modification to it to demonstrate the problem: https://snack.expo.io/@stuckj/expo-av-video-silentmode-bug.

If you don't auto-play the video, audio won't work no matter what you set in the audio initialization. If you autoplay the video it works perfectly.

**Comment by sethgw** [comment]
Thanks @stuckj I think your demonstration is more clear.  To me, it doesn't seem like we should *have* to set `shouldPlay` in order to use this. In my particular case it wouldn't make sense to set shouldPlay, but I still want the audio when the user interacts with the video.

**Comment by stuckj** [comment]
I agree. That's why I filed the bug. :) It certainly seems like a bug to me.

Just a note that you can work around it by programmatically started the video (with `playAsync`). You'll need to overlay your own button or view over the video though to intercept the click.

**Comment by fhugoduarte** [comment]
I'm currently using this work around:

```jsx
<Video
  ref={videoRef}
  source={videoSource}
  useNativeControls
  onLoad={async () => {
    await videoRef.current?.playAsync();
    await videoRef.current?.pauseAsync();
  }}
  resizeMode={Video.RESIZE_MODE_CONTAIN}
/>
```

**Comment by fhugoduarte** [comment]
I'm currently using this work around:

```jsx
<Video
  ref={videoRef}
  source={videoSource}
  useNativeControls
  onLoad={async () => {
    await videoRef.current?.playAsync();
    await videoRef.current?.pauseAsync();
  }}
  resizeMode={Video.RESIZE_MODE_CONTAIN}
/>
```

**Comment by Flip32** [comment]
> I'm currently using this work around:
> 
> ```js
> <Video
>   ref={videoRef}
>   source={videoSource}
>   useNativeControls
>   onLoad={async () => {
>     await videoRef.current?.playAsync();
>     await videoRef.current?.pauseAsync();
>   }}
>   resizeMode={Video.RESIZE_MODE_CONTAIN}
> />
> ```

it works for me! I`m on sdk 45 version.
tnks a lot

**Comment by LucasPMM** [comment]
I just solved by adding `playsInSilentModeIOS: true` on my `App.tsx`. This was applied for the entire application:

```js
import { Audio } from "expo-av";
...

useEffect(() => {
    ...
    Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
}, []);
```

**Comment by stevehs17** [comment]
> ```js
> useEffect(() => {
>     ...
>     Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
> }, []);
> ```

This also worked for me. Thanks @LucasPMM

**Comment by Youreek1909** [comment]
> I just solved by adding `playsInSilentModeIOS: true` on my `App.tsx`. This was applied for the entire application:
> 
> ```js
> import { Audio } from "expo-av";
> ...
> 
> useEffect(() => {
>     ...
>     Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
> }, []);
> ```

Tried for many hours, and finally found this answer. Thank you!

**Comment by machupicchu27** [comment]
> I just solved by adding `playsInSilentModeIOS: true` on my `App.tsx`. This was applied for the entire application:
> 
> ```js
> import { Audio } from "expo-av";
> ...
> 
> useEffect(() => {
>     ...
>     Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
> }, []);
> ```

This still doesn't work for me :/. The only solution that did was setting shouldPlay to true and pausing the video onLoad:
```
<Video
    ref={videoRef}
    ...
    shouldPlay={true}
    onLoad={async () => {
        await videoRef.current?.pauseAsync();
    }}
    useNativeControls
/>
```

**Comment by oleksii-jointoit** [comment]
So I merged couple answers from here into this and it fixed it for me. My app has sounds and videos and I couldn't head videos without part with silent_sound.mp3

App.tsx:

```
useEffect(() => {
    const init = async () => {
      await Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
      });

      const sound = new Audio.Sound();
      if (Platform.OS === 'ios') {
        const playSilentSound = async () => {
          await sound.loadAsync(require('./assets/silent_sound.mp3'));
          await sound.playAsync();
          await sound.setIsLoopingAsync(true);
        };
        playSilentSound();
      }
      return () => {
        sound.stopAsync();
        sound.unloadAsync();
      };
    };
    init();
  }, []);
```

**Comment by manuelmhtr** [comment]
Here's what worked for me:

 1. Create a reference (`ref`) to the `<Video />` component.
 2. Use a state to listen when the video starts playing.
 3. When it does, call `await Audio.setAudioModeAsync({
    playsInSilentModeIOS: true });`.
 4. Immediately after, re-play the video by calling `ref.current.playAsync();`

In summary, my component looks like this:

```jsx
import React, { useState, useEffect, useRef } from 'react';
import { Audio, Video as OriginalVideo } from 'expo-av';

const triggerAudio = async (ref) => {
  await Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
  ref.current.playAsync();
};

const Video = ({ ...props }) => {
  const ref = useRef(null);
  const [status, setStatus] = useState({});

  useEffect(() => {
    if (status.isPlaying) triggerAudio(ref);
  }, [ref, status.isPlaying]);

  return (
    <OriginalVideo
      ref={ref}
      onPlaybackStatusUpdate={(status) => setStatus(status)}
      useNativeControls
      {...props}
    />
  );
};

```

Tested with Expo SDK v45 and iOS 16.

Hope it helps!

**Comment by Mootbing** [comment]
> Here's what worked for me:
> 
> 1. Create a reference (`ref`) to the `<Video />` component.
> 2. Use a state to listen when the video starts playing.
> 3. When it does, call `await Audio.setAudioModeAsync({ playsInSilentModeIOS: true });`.
> 4. Immediately after, re-play the video by calling `ref.current.playAsync();`
> 
> In summary, my component looks like this:
> 
> ```js
> import React, { useState, useEffect, useRef } from 'react';
> import { Audio, Video as OriginalVideo } from 'expo-av';
> 
> const triggerAudio = async (ref) => {
>   await Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
>   ref.current.playAsync();
> };
> 
> const Video = ({ ...props }) => {
>   const ref = useRef(null);
>   const [status, setStatus] = useState({});
> 
>   useEffect(() => {
>     if (status.isPlaying) triggerAudio(ref);
>   }, [ref, status.isPlaying]);
> 
>   return (
>     <OriginalVideo
>       ref={ref}
>       onPlaybackStatusUpdate={(status) => setStatus(status)}
>       useNativeControls
>       {...props}
>     />
>   );
> };
> ```
> 
> Tested with Expo SDK v45 and iOS 16.
> 
> Hope it helps!

Hey does this still work in expo 48? Also does this work with the Audio files too or just expo video?

**Comment by Rodrigueira97** [comment]
Bom juntei algumas sugestoes e consegui chegar em um resultado talvez possa ajudar alguém:

primeiro coloquei no App principal da aplicacao a opcao

```
  useEffect(() => {
    Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
  }, []);
```
  
  logo em seguida coloquei a opcao onLoad com a propriedade de dar play
  
```
  <Video
                      key={item.id}
                      ref={(ref) => addRef(ref, index)}
                      useNativeControls
                      source={{ uri: item.file }}
                      style={styles.videoStyle}
                      resizeMode={ResizeMode.COVER}
                      onPlaybackStatusUpdate={setStatus}
                      isLooping
                      onLoad={() => {
                        videoRef.current?.playAsync();
                      }}
                    />
```
  
  Dessa forma funcionou
