### ISSUE TITLE
Hide/Modify BarCodeScanner header

### ISSUE THREAD

**Issue by simo385** [expo/expo#7487]
Hi everybody,

I'm using BarcodeScanner inside my app and I was wondering if it could be possible to hide/modify the header in home page.

I'd like to put a custom header with menu/buttons/ etc ...

Thanks in advance.
Simone

**Comment by IjzerenHein** [comment]
Hi! I'm not sure what you mean. The BarCodeScanner itself renders only a Camera component.

Can you provide with a screenshot and highlight the "header in home page" that you would want to modify?
