### ISSUE TITLE
[docs] Inconsistencies in expo-calendar

### ISSUE THREAD

**Issue by CampbellMG** [expo/expo#7491]
# Expo-Calendar Documentation

I recently implemented a calendar feature in my Expo app and found the [expo-calendar documentation](https://docs.expo.io/versions/latest/sdk/calendar/#calendargetsourcesasync) regarding calendar creation extremely confusing.

I am interested in opening a pull request with some changes but wanted to run the updates by someone first.

### Source
The documentation for this function specifies that `source (object)` is required (Android only), although I do not believe this is true. When attempting to create a calendar on iOS without this value I received `Error Domain=EKErrorDomain 
Code=14 "Calendar has no source" UserInfo=
{NSLocalizedDescription=Calendar has no source}`

### Source Type
In addition, the `type (string)` member within the source object is described as:

`Type of the account that owns this calendar and was used to sync it to the device. If isLocalAccount is falsy then this must be defined, and must match an account on the device along with name, or the OS will delete the calendar.`

This combined with the code example at the top of the docs led me to believe that the value is not required, however, the Typescript definition defines it as mandatory. I am not sure whether this is a documentation or Typescript issue but I am happy to update either, I just need some clarification. 

## Example Usage
Finally, the code example for creating a calendar under the `Example Usage`, uses the following function for retrieving a calendar source on iOS: 

```javascript 
async function getDefaultCalendarSource() {
  const calendars = await Calendar.getCalendarsAsync();
  const defaultCalendars = calendars.filter(each => each.source.name === 'Default');
  return defaultCalendars[0].source;
}
```

I am confused why this function would be included in the documentation as there is a dedicated function: `Calendar.getSourcesAsync()` and the example assumes that the user already has a local calendar on their device which is unlikely as many users store their calendars on iCloud.

I was considering an alternative that looks like this: 
```javascript 
async function getDefaultCalendarSource() {
  const sources = await Calendar.getSourcesAsync();
  const defaultSources = sources.filter(each => each.name === 'Default');
  return defaultSources[0];
}
```

**Comment by dagan-arbox** [comment]
This is current, I Have reached the same point :)

**Comment by rjtubera** [comment]
Hi do you have any fix for this? I'm also struggling to make it work for calendars hosted in cloud
