### ISSUE TITLE
You are not permitted to view the requested resource

### ISSUE THREAD

**Issue by milad1367** [expo/expo#751]
I know that I should not ask this question, but I have no other way. I want to put a simple post on the`https://forums.expo.io/` , but I will encounter this error . "You are not permitted to view the requested resource".
pls help meee.

**Comment by tcdavis** [comment]
Hmm, do you get that message when navigating to forums.expo.io, or when you try to post?  What page are you on when attempting to create the post, and are you logged in?

Screenshots might be helpful as well.

**Comment by milad1367** [comment]
hi.after register took one day, for my account to become BASIC.After that, I saw this error every time I posted a new post.Interestingly, today I figured this problem was solved and my previous posts appeared one after another !! Within an hour. And now I have the possibility to create a new post. Thank you for your follow up.
