### ISSUE TITLE
Possible incompatibility with @react-native-community/react-native-netinfo

### ISSUE THREAD

**Issue by Andrea-Arguello** [expo/expo#7511]
### Environment

```
Expo CLI 3.15.5 environment info:
    System:
      OS: Linux 5.3 Pop!_OS 18.04 LTS
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.19.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.13.4 - /usr/bin/npm
```

Ejected project on ExpoKit 36.0.1 and Expo 36.0.2.

### Steps to Reproduce
Run ``` yarn add @react-native-community/netinfo ```, I specifically installed the 4.6.0 version, since an expo message prompted me to do so.

### Expected Behavior
App runs without problems.

### Actual Behavior
I instance as the app mounts that uses the library to check for internet connectivity. I am greeted by the following error just by running NetInfo.fetch().then(state => console.log(state.type));
![image](https://user-images.githubusercontent.com/31134106/77805046-9ea73000-7046-11ea-87e4-205cc802b12d.png)

Additionally, another dev on my team left the following comment inside the code back when we were still using Expo SDK 34.

```
/*
TODO: this whole module was originally created with @react-community/net-info
but expo didn't seem to handle it well. Then I replaced it with the deprecated
NetInfo react native api. Please review this in the future in order to assure
future proof.
*/

```

This seems to be a problem in the current SDK.

**Comment by brentvatne** [comment]
you should follow the docs:

https://docs.expo.io/versions/v36.0.0/sdk/netinfo/#installation

> expo install @react-native-community/netinfo

this installs the version that is compatible with your sdk version

**Comment by Andrea-Arguello** [comment]
This installs the version 5.6.2, and I get the following warning
![image](https://user-images.githubusercontent.com/31134106/77809740-b5ee1980-7056-11ea-9899-2ecd4067b3f4.png)

Overmore, it doesn't solve the issue with NetInfo I mentioned

**Comment by brentvatne** [comment]
is your app in bare workflow or expokit?
