### ISSUE TITLE
iOS Build: Issue with Webhook

### ISSUE THREAD

**Issue by kurthopfer** [expo/expo#7512]
Having an issue with the artifactURL in the webhook body payload having a nullstr written.   See below:

![image](https://user-images.githubusercontent.com/39605384/77806530-335b5f00-7042-11ea-82b1-8061a9df2be3.png)

**Comment by kurthopfer** [comment]
Happened twice in a row,  was hoping it was just an oops.
![image](https://user-images.githubusercontent.com/39605384/77806882-43277300-7043-11ea-8bc2-8fa907526f09.png)

**Comment by kurthopfer** [comment]
I verified this takes place on both iOS and Android builds, sample payload from android build:
{
    "status": "finished",
    "id": "55c25ec1-0554-4c41-b7e9-e4a63ebe2ac0",
    "artifactUrl": "https://expo.io/artifacts/null",
    "releaseChannel": "dev"
}

**Comment by dsokal** [comment]
Hi @kurthopfer,
Sorry for the inconvenience. We've already managed to implement the fix. It should be deployed to our web servers later today. We'll let you know when it's done.

**Comment by kurthopfer** [comment]
Thanks @dsokal - let me know and I'll go ahead and test!   Thanks!

**Comment by dsokal** [comment]
@kurthopfer the fix has been deployed. Let me know if it fixes the problem for you.
