### ISSUE TITLE
Force restart option for OTA updates

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#7514]
I don't see any content in the over the air updates documentation for forcefully restarting user's apps so they are guaranteed to receive the update. Most users don't restart their phone often enough to ensure that updates are received in a timely manner. How do we force a restart on a certain screen of our apps if there is an update available?

**Comment by NiwuoDev** [comment]
@shamilovtim Using Updates.reloadFromCache() restarts the app.

```
try {
  const update = await Updates.checkForUpdateAsync();
  if (update.isAvailable) {
    await Updates.fetchUpdateAsync();
    // ... notify user of update ...
    Updates.reloadFromCache();
  }
} catch (e) {
  // handle or log error
}
```
Docs https://docs.expo.io/versions/latest/guides/configuring-ota-updates/

**Comment by cruzach** [comment]
Thanks for sharing that @NiwuoDev 😄 

@shamilovtim in the future, it's better to ask questions like this on our [forums](https://forums.expo.io/), since we keep github reserved for bug reports

**Comment by shamilovtim** [comment]
Thanks! I have no idea how I missed that in the docs. I skimmed them multiple times and couldn't see it. 🤯🤯🤯
