### ISSUE TITLE
Problem using Amplitude and setTrackingOptions

### ISSUE THREAD

**Issue by georgiosd** [expo/expo#7515]
I've added Amplitude analytics into my expo app and I wanted to disable tracking personal data by using setTrackingOptions which is mentioned in the Expo docs. 

`setTrackingOptions` is not available on the version suggested by expo (8.0.0) (I saw the commits and for some reason it was reverted prior to the release of expo sdk 36). 

I added the newer expo-amplitude (8.1.0) package version, and while that method is now available the following error is thrown (both via expo app in an emulator and with a build on a real device - whether Android or iOS).

Any suggestions?

https://imgur.com/MJpADcR

**Comment by cruzach** [comment]
It looks like it was [added back on the native side](https://github.com/expo/expo/commit/b00d33bcc5d99dee70bac67d2f4c81449c72ba2d#diff-fc9b8393ff93230b6bd65dd662c52476) after the SDK 36 release, so this will probably go out with SDK 37 (which should be available very soon)

**Comment by georgiosd** [comment]
@cruzach thank you. Can you give an ETA for 37? we'll need to weigh waiting for it vs alternatives

**Comment by cruzach** [comment]
this week

**Comment by georgiosd** [comment]
@cruzach this still seems to fail but this time on the device. Works fine on iOS emulator. Is it a problem with your build server?

```
*** Terminating app due to uncaught exception 'ExpoFatalError', reason: 'Expo encountered a fatal error: Unhandled JS Exception: Error: The method or property Amplitude.setTrackingOptions is not available on ios, are you sure you've linked all the native dependencies properly?'
```
