### ISSUE TITLE
Build fail with *.graphql files

### ISSUE THREAD

**Issue by fabien0102** [expo/expo#752]
Hello,

My app is working perfectly on development mode but I can't publish it 😢 

Error message:
```bash
Unable to resolve module `./createUserMutation.graphql` from `D:\Projets\climbing-app\app\queries\withCreateUser.js`: could not resolve `D:\Projets\climbing-app\app\queries\createUserMutation.graphql' as a file nor as a folder
```
I suspect that is a problem with the `*.graphql` files, loaded by babel with this configuration:
```
// .babelrc
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        "babel-plugin-inline-import-graphql-ast"
      ]
    }
  }
}
```

All details on my repo => https://github.com/fabien0102/climbing-app/tree/master/app

**Comment by ccheever** [comment]
For workarounds while we get to the bottom of this. you might try making your graphql files into js files that export a string or something like that. Or if you think its a problem with the .babelrc file, you can change that.

**Comment by fabien0102** [comment]
I found the problem and it actually works 😃 Just forgot to provide graphql plugin in production…

My working .babelrc
```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        "babel-plugin-inline-import-graphql-ast"
      ]
    },
    "production": {
      "plugins": [
        "babel-plugin-inline-import-graphql-ast"
      ]
    }
  }
}
```

And working example for the curious 😉 https://github.com/fabien0102/climbing-app

BTW, you can't just export graphql in separate js file (it was my first try)

**Comment by rdickert** [comment]
@fabien0102 thanks for posting back your solution. It helped me today!

**Comment by bonham000** [comment]
I'm still experiencing this same issue even after moving the `babel-plugin-import-graphql` into the `plugins` for `.babelrc`.

The app builds and runs in development using Expo XDE but fails when I try to publish it, when trying to parse `.gql` files. I can't find any solution here... anyone else find any more details on this?
