### ISSUE TITLE
Bluetooth earpiece not working on Android 

### ISSUE THREAD

**Issue by kevP-Sirius** [expo/expo#7520]
Hello i'm using react native for my android app and everything working fine except when i try to listen my music on bluetooth device , my app isn't detecting when i connect the device but when i disconnect the bluetooth device the music stop like if i had a normal earpiece  with a jack that i put out . 
I have no idea how i can fix this i'm using expo-av and i use video component to read my music file or video .

**Comment by cruzach** [comment]
Hey @kevP-Sirius , we'll be happy to help if you can edit your issue to follow the bug report template we provide. Without a reproducible demo, it's really tough to say what the problem might be. I'll re-open this issue once we have all the necessary information

**Comment by kevP-Sirius** [comment]
Okay where can i find the template please  ?
