### ISSUE TITLE
AdMob: AdMobInterstitial.setTestDeviceID is deprecated

### ISSUE THREAD

**Issue by pawelsas** [expo/expo#7522]
### Environment

Bare React Native App using RN 0.61.5

App target: iOS and Android Emulator

### Steps to Reproduce

Install and configure AdMob as described in the docs. Run app on Emulator (iOS or Android).

For me it looks like this:

```
const INTERSTITIAL = Platform.OS === 'ios' ? AD_MOB_IOS : AD_MOB_ANDROID
AdMobInterstitial.setAdUnitID(INTERSTITIAL)
AdMobInterstitial.setTestDeviceID('EMULATOR')
await AdMobInterstitial.requestAdAsync({ servePersonalizedAds: false })
await AdMobInterstitial.showAdAsync()
```

### Expected Behavior

Works without deprecation warnings

### Actual Behavior

`AdMobInterstitial.setTestDeviceID is deprecated. Test device IDs are now set globally. Use AdMob.setTestDeviceIDAsync instead.`

When I use `AdMob.setTestDeviceIDAsync` I get an error.

**Comment by IjzerenHein** [comment]
Hi 👋

> When I use AdMob.setTestDeviceIDAsync I get an error.

What's the error that you are getting when calling `AdMob.setTestDeviceIDAsync`?

**Comment by pawelsas** [comment]
Sorry, my bad. 
I did call `AdMobInterstitial.setTestDeviceIDAsync` instead of `AdMob.setTestDeviceIDAsync`.
I think the docs should be updated.

**Comment by pawelsas** [comment]
Well, I think i need to reopen this one.
After I implemented `AdMobInterstitial.setTestDeviceIDAsync` I got two problems

1. `AdMobInterstitial.setTestDeviceIDAsync` leads to `[TypeError: undefined is not an object (evaluating '_expoAdsAdmob.default.setTestDeviceIDAsync')]`. I called it globally on app init.
2. Ads are not shown anymore on iOS emulator

**Comment by IjzerenHein** [comment]
Hi, just to be on the same page here.

> After I implemented AdMobInterstitial.setTestDeviceIDAsync I got a problem

The legacy function was `AdMobInterstitial.setTestDeviceID`. (without the `Async` suffix)

And the new global function is: `setTestDeviceIDAsync`.

**Comment by pawelsas** [comment]
This is right.
The new function throws an error.

**Comment by Marcados** [comment]
Hi ! This issue is still relevant. I've got 'AdMob: AdMobInterstitial.setTestDeviceID is deprecated', and when using `AdMob.setTestDeviceIDAsync` I've got an error 
> undefined is not an object (evaluating '_expoAdsAdmob.AdMob.setTestDeviceIDAsync')]

Is there a solution I missed or is this issue still unresolved ?

**Comment by IjzerenHein** [comment]
it seems something has gone wrong with the documentation, and the latest `AdMob` page doesn't show the correct API instructions. I fixed it but it will take a bit for it to show up on the website. This page describes the correct API usage:
https://docs.expo.io/versions/v36.0.0/sdk/admob/

The problem you are experiencing is because of the import. `setTestDeviceIDAsync` is not defined on the default export, and you need to import it like this:

```
import { setTestDeviceIDAsync } from 'expo-ads-admob';
```

**Comment by omar-bakhsh** [comment]
this is how i add banner easy 😊

in app.js
` 
import { AdMobBanner,} from 'expo-ads-admob';

 <AdMobBanner
  bannerSize="banner"
  adUnitID="ca-app-pub-yourKeyHere" 
  servePersonalizedAds={false}
  onDidFailToReceiveAdWithError={this.bannerError} />`

in app.json

` "android": {
 
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-yourKeyHere"}`
