### ISSUE TITLE
Accessing download progress while downloading

### ISSUE THREAD

**Issue by mkhaledche** [expo/expo#7523]
Hi
I am trying to access the download progress while downloading a file through the code below. However it doesn't show me the progress while downloading, it just shows it before starting (0) and after finishing (1). How can I access the progress while downloading?

```
  const callback = downloadProgress => {
    const progress =
      downloadProgress.totalBytesWritten /
      downloadProgress.totalBytesExpectedToWrite;
    console.log(progress);
    setProgress(progress);
  };

  const downloadFile = async (endpoint, fileName) => {
    const downloadResumable = FileSystem.createDownloadResumable(
      endpoint,
      FileSystem.documentDirectory + fileName,
      {},
      callback
    );

    try {
      const { uri } = await downloadResumable.downloadAsync();
      setLoadingState("Done");
      console.log("Finished downloading ", uri);
    } catch (e) {
      console.error(e);
    }
  };


```

**Comment by IjzerenHein** [comment]
Hi. I've been unable to reproduce the problem. Can you provide a [snack](https://snack.expo.io/) demonstrating the problem? 

Also, be aware that small files will be dowloaded in a single chunk and you might only see progress events for 0 and 100.

**Comment by mkhaledche** [comment]
Thanks @IjzerenHein for your reply. 
Well, I have made a snack for it and it began to show progress. You simply click the switch button on to to start downloading the data and switch it off to delete them.
https://snack.expo.io/@mkhaled.che/download-data-through-file-system
It seems to be working for small files where progress is shown only on the console not on the screen. However, for large files it began to show negative values. The logs for download progress object and progress were as follows:
 Android SDK built for x86:
►{totalBytesWritten:714,totalBytesExpectedToWrite:-1}
-714
Android SDK built for x86:
►{totalBytesWritten:16202,totalBytesExpectedToWrite:-1}
-16202
Android SDK built for x86:
►{totalBytesWritten:48586,totalBytesExpectedToWrite:-1}
-48586
Android SDK built for x86:
►{totalBytesWritten:97162,totalBytesExpectedToWrite:-1}
-97162

Up to:

Android SDK built for x86:
►{totalBytesWritten:2284996,totalBytesExpectedToWrite:-1}
-2284996

I am not sure why the totalBytesExpectedToWrite is always -1, is there an issue with calculating the data of a very large json file?

**Comment by IjzerenHein** [comment]
Hi, I've checked and your server does not return the `Content-Length` header in the HTTP response request. This makes it impossible for the client to know how much data needs to be downloaded. And therefore `totalBytesExpectedToWrite` returns -1 [(iOS download docs)](https://developer.apple.com/documentation/foundation/nsurlsessiondownloaddelegate/1409408-urlsession?language=objc).

`http://la-sunnah.com/wp-json/hadices/v1/hadices?posts_per_page=1000`

![image](https://user-images.githubusercontent.com/6184593/77917538-fb028d80-729a-11ea-8fb3-3259805ec371.png)


Your server should return the content-length in order for progress tracking to work:
**Example**
![image](https://user-images.githubusercontent.com/6184593/77917876-60567e80-729b-11ea-9eed-dc4e928429e3.png)

**Comment by IjzerenHein** [comment]
I noticed that this is not mentioned in the documentation, will add it!

**Comment by mkhaledche** [comment]
Ok got it. Thanks

**Comment by EKOLX** [comment]
Hi, I'm got exactly the same issue. I'm using same code from documentation. The callback function never fires. As a url I'm passing this: https://upload.wikimedia.org/wikipedia/commons/3/35/Neckertal_20150527-6384.jpg

` const onDownloadPress = async () => {
    let permission = await MediaLibrary.getPermissionsAsync();
    if (!permission.granted) {
      permission = await MediaLibrary.requestPermissionsAsync();
    }

    if (permission.granted) {
      try {
        setDownloadProgress(1);
        const result = await downloader.downloadAsync();
        await saveToDownloadsFolder(result!.uri);
        await sleep(2000);
        setDownloadProgress(-1);
        console.log("Finished downloading to ", result?.uri);
      } catch (err) {
        console.error("Error on donwloading image. ", err);
      }
    }
  };`

`  const downloadCallback = (downloadProgress: any) => {
    console.log("downloadCallbacks", downloadProgress);
    const progress =
      downloadProgress.totalBytesWritten /
      downloadProgress.totalBytesExpectedToWrite;
    setDownloadProgress(progress * 100);
  };

  const downloader = FileSystem.createDownloadResumable(
    //`http:${file.uri.url}`,
    "https://upload.wikimedia.org/wikipedia/commons/3/35/Neckertal_20150527-6384.jpg",
    FileSystem.documentDirectory + file.name,
    {},
    downloadCallback
  );`

**Comment by NilsBaumgartner1994** [comment]
And updates on this?
