### ISSUE TITLE
[docs] Provide best practices or limitations around how frequently we can check for OTA updates

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#7524]
In the docs of Updater there exists a method where we can manually check for updates. There is no guidance on how often this can be done or how much you would tolerate from us. Given that mobile apps can have thousands of concurrent users all checking for updates X often, I thought maybe it would be useful for Expo to provide some sort of rule of thumb for how frequently we are allowed to check for updates from Updater. 

Thank you!

**Comment by cruzach** [comment]
hey @shamilovtim , thanks for asking this! I'll update the docs, but just to answer you here:

There are two scenarios for Updates- either Expo is hosting your updates, or you're hosting them yourself. If you're hosting them yourself, then it's up to you and how much your server can handle. If Expo is hosting your updates, I'd suggest modeling it based on the default behavior- which is to check for an update whenever the app is freshly opened (from a dead state, not from the background). This tends to be about once per day

**Comment by shamilovtim** [comment]
@cruzach with the once per day setting, the problem is that having it checked only on app open isn't going to work for most users given that apps can have long running sessions and most users don't really force close apps from the app switcher or deliberately restart their phones. there's no guarantee that an update will ever happen given that a user could never restart their phone for months at a time and their phone never dies. so what I was planning on doing was checking for updates whenever a certain screen in our app gets mounted (or maybe dismounted even). i imagine that this would happen a few times per day, depending on usage. it would be nice if the Updater had a default setting with some sort of regular check for updates and a default alert that tells the user that their app will get restarted. i built this functionality myself using the example in the docs but it seems to me that this would be a fairly common problem for OTA updates and so maybe some default functionality could be provided on the underlying native side that makes sure our users will definitely get an update once or twice per day even if they don't close their apps and they have them open.

**Comment by cruzach** [comment]
The purpose behind the API is to allow for folks like you to implement their own check for new updates, so I don't think changing the default behavior to this is the best option. The purpose is to provide a baseline default that works for most cases, while still providing an API that allows people to customize the behavior however they'd like

**Comment by shamilovtim** [comment]
yeah I'm not saying the default needs to change I'm just saying that it would seem that there should be an option to check within the background of the application whether an update is available and then serve that update. the problem with this manual implementation is that there seems to be no choice between: a) a timer (bad, probably a non starter) or b) checking multiple times on screen mounts / dismounts.

**Comment by cruzach** [comment]
I'm not sure I understand- you'd like to check for an update multiple times while the application is being used? Even if a user never fully closes their app for months, why not instead just check every time the  root component mounted?

**Comment by shamilovtim** [comment]
@cruzach Sorry I think I'm at the limits of my knowledge here let's make sure we're on the same page. 

1. Is it true that an app can be open for months at a time on a user's phone -- and hence not be served an OTA update? 
2. If #1 is true, wouldn't it render the OTA updater useless? 
3. Because of #2, shouldn't there be some stock functionality *besides updates on app start* which regularly checks for updates?

You've mentioned checking on root component mount. I'm not sure I understand how that's a solution  because it seems to me that's the same thing as #1. The root component is only going to get dismounted if the user shuts down the app. 

If any of my assumptions are wrong here or I'm misunderstanding please feel free to correct me.

**Comment by cruzach** [comment]
1. An app _can_ be open (although I believe iOS puts an app into "sleep" after ~10 minutes of no use in the background, and iirc this was made more aggressive with iOS 13 actually killing some background apps) for a long time, if the user's phone is never shut down or loses battery and they never close their apps. 
2. Only if you are relying on the default behavior. If this is problematic for you, you can customize the check for updates using the `Updates` API
3. The default behavior provides an option that isn't really accessible otherwise, whereas the functionality you're looking for (I think) can be built in using a combination of the `Updates` API and the [`AppState` API](https://docs.expo.io/versions/latest/react-native/appstate/) (i.e. check each time the user foregrounds the app)

**Comment by shamilovtim** [comment]
@cruzach Okay thanks for following up!
