### ISSUE TITLE
sendSMSAsync can create duplicated recipients and messages in third-party messaging apps

### ISSUE THREAD

**Issue by megantaylor** [expo/expo#7535]
### Environment

  Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.9.0 => 16.9.22 
      @types/react-native: ^0.60.15 => 0.60.31 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: 4.3.2 => 4.3.2 
    npmGlobalPackages:
      expo-cli: 2.21.1

Target: iOS, Android

### Steps to Reproduce

button onPress function checks to see if sms is available and then if so, calls the sendSMSAsync function:

```
const someFunction = async () => {
    const canAsyncSMS = await SMS.isAvailableAsync();
    if (canAsyncSMS) {
        return await SMS.sendSMSAsync([String(phoneNumber)], String(textContent))
    }
}
```

### Expected Behavior

recipient number and message text should only appear once in compose screen

### Actual Behavior

this bug is android-only, as far as i know.

there is a button in the ui that is meant to  auto-populate an sms recipient and message text. when the button is clicked, the default messenger app (either standard android messenger app or a third-party sms app that has been set as the default) opens. in the standard messenger app, the compose screen is correctly auto-populated with a recipient phone number and the message text. in several third-party apps that have been tested **(ex: Textra)**, the recipient phone number is duplicated in the to field, and the message text is duplicated in the message input field.

Reading through the java code (https://github.com/expo/expo/blob/1d5998d7b12e09194c889abb361f51d283da5083/packages/expo-sms/android/src/main/java/expo/modules/sms/SMSModule.java#L56), but knowing nothing about smsintent, two things jump out at me as possible culprits:

1. lines 67 - 68
```
    SMSIntent.putExtra(Intent.EXTRA_TEXT, message);
    SMSIntent.putExtra("sms_body", message);
```
seems believable to me that these two lines could create duplicated message body text.

2. lines 118 - 121
```
final StringBuilder addressesBuilder = new StringBuilder(addresses.get(0));
      for (String address : addresses) {
        addressesBuilder.append(';').append(address);
      }
```
i could also imagine that this could duplicate the recipient phone number

### Reproducible Demo

https://snack.expo.io/HJ4TA0yP8

**Comment by jamesst20** [comment]
Happens to me on Expo 41, Android 11, Textra latest version. Samsung Galaxy S20+.
