### ISSUE TITLE
feature request: ios:build with adhoc provision profile

### ISSUE THREAD

**Issue by aniltirola** [expo/expo#754]
I use the command `exp build:ios` successfully with the option `I want to upload my own keystore!` --> everything works;

now it seems, that the expo-build server generates an "iOS Distribution App Store Provisioning Profile" (inside apple account) for the current app-id, if it doesn't exist; then the build process uses this profile; --> that works good;

could you please implement a feature, so that I can choose optionally to use an existing "iOS Distribution Ad Hoc Provisioning Profile", which I generated before inside apple-developer-account.

The advantage of using "Ad Hoc Provisioning Profile" should be, that I can define real devices for testing without using testflight.

**Comment by quinlanj** [comment]
hey @aniltirola, thanks for your input! If you could make a feature request here https://expo.canny.io/feature-requests , that would be awesome. We look through this list and try our best to implement the requested features. In the meantime, closing this issue since it is a feature request.
