### ISSUE TITLE
expo-yarn-workspaces images from another package does work. 

### ISSUE THREAD

**Issue by morwalz** [expo/expo#7545]
Hi,
I am using expo-yarn-workspaces, it is working well but now i am facing a major issue. I have images in another package and using them in main package where i have an expo project. But images does not show up. 
I tried to print the path using 
const imageURI = Expo.Asset.fromModule(require('rnassets/screen-first.png')).uri;
And it is showing up as http://192.168.43.54:19001/assets/../rnassets/screen-first.png?platform=android&hash=87dd2fd995d927e52d6f7dc3eb755fb3?platform=android&dev=true&minify=false&hot=false

And when i open in browser this shows error. 

I tried to make another test where i have I have a component in another package. And it includes images  in same folder. when i use this package in main package then component works but images do not show up. 
I think it has to do something with the path it create automatically.

**Comment by morwalz** [comment]
Hi I tried to fix this from a workaround 

`const { createMetroConfiguration } = require('expo-yarn-workspaces');
let config = createMetroConfiguration(__dirname);
config.server = {
    enhanceMiddleware: (middleware) => {
        return (req, res, next) => {
            // Images does not work so had to use this workaround.
            const assets = '/RNExamsbookLogin/';
            if (req.url.startsWith(assets)) {
                console.log('enhanceMiddleware-------->>>', req.url);
                req.url = req.url.replace(
                    assets,
                    '/assets/src/'
                );
            }
            return middleware(req, res, next);
        };
    }
}

module.exports = config;`

**Comment by renanmav** [comment]
> And it is showing up as http://192.168.43.54:19001/assets/../rnassets/screen-first.png?platform=android&hash=87dd2fd995d927e52d6f7dc3eb755fb3?platform=android&dev=true&minify=false&hot=false

This isn’t available to us @morwalz

**Comment by belgamo** [comment]
+1

**Comment by kyryanBr** [comment]
+1

**Comment by belgamo** [comment]
> I have the same problem. When I place the image in the same package, it works. But from another package, the image simply doesn't show up.

I created a reproducible environment. On iOS work fine. The problem happens only on android.
https://github.com/belgamo/expo-workspaces-image-problem

**Comment by joseaugusto06** [comment]
+1

**Comment by brunohkbx** [comment]
+1

**Comment by belgamo** [comment]
@cruzach can you help us?

**Comment by bogoslavskiy** [comment]
+1

**Comment by bogoslavskiy** [comment]
@morwalz suggestion works great! 
If your directory with assets is located at the top level of packages, outside the expo, you need to rewrite the path to your assets like this

```javascript
config.server = {
  enhanceMiddleware: (middleware) => {
    return (req, res, next) => {
      const assets = '/@shared/assets/';
      if (req.url.startsWith(assets)) {
        // At the beginning of the path to your assets should always be "/assets/"
        // Next exit from the current directory
        req.url = req.url.replace(
          assets,
          '/assets/../@shared/assets/'
        );
      }

      // Fix showing back icon on android
      // This is necessary if you are working with react-navigation and 
      // it is installed globally for monorepo.
      const otherAssets = '/node_modules/';
      if (req.url.startsWith(otherAssets)) {
        req.url = req.url.replace(
          otherAssets,
          '/assets/../../node_modules/'
        );
      }

      return middleware(req, res, next);
    };
  }
}
```

**Comment by belgamo** [comment]
Thank you @bogoslavskiy for your full explanation about the problem and thanks @morwalz for introduced it, it works!

**Comment by brentvatne** [comment]
for people following this issue, here's the upstream issue you can track that would avoid the need for any workaround: https://github.com/facebook/metro/issues/290

**Comment by brentvatne** [comment]
also, the related issue on this repo: https://github.com/expo/expo/issues/5513

**Comment by kickbk** [comment]
Was this issue resolved in sdk 41?

**Comment by brentvatne** [comment]
@kickbk:

> for people following this issue, here's the upstream issue you can track that - when fixed - will do away with the need for any workaround: facebook/metro#290

**Comment by VictorioMolina** [comment]
1. Modify your `metro.config.js` (inside your app package/folder) to something like this:

```js
/* eslint-disable jsdoc/require-jsdoc */
const { getDefaultConfig } = require("expo/metro-config");
const path = require("path");

// Find the workspace root
const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, "../../");

const config = getDefaultConfig(projectRoot);

// Watch all files within the monorepo
config.watchFolders = [workspaceRoot];

// Let Metro know where to resolve packages, and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
];

// Let Metro know from where it should serve the node_modules's assets
config.server = {
  enhanceMiddleware: (middleware) => {
    return (req, res, next) => {
      const assets = "/node_modules/";

      if (req.url.startsWith(assets)) {
        req.url = req.url.replace(
          assets,
          "/assets/../../node_modules/"
        );
      }

      return middleware(req, res, next);
    };
  },
};

module.exports = config;
```

2. Clear expo cache: expo -r c

3. Close the app and run it again on your Android emulator
