### ISSUE TITLE
Problems with push notification

### ISSUE THREAD

**Issue by NicolaiV** [expo/expo#755]
Good afternoon. I have question.
How to make the device (for example, android) receive push notifications even when the application started from the apk is turned off. I made push notifications using this document https://docs.expo.io/versions/latest/guides/push-notifications.html
Thank you

**Comment by ccheever** [comment]
Hi-

Push notifications work this way. You'll need to explain your problem more if I'm misunderstanding it.

**Comment by arvindrajachourasiya** [comment]
Hi,
I have developed push notifications(GCM) functionality in my application, working fine. only issue i am facing is when device is offline/logout within this time if user getting notifications they are missing, not delivering when user come online.
How to do that please suggest me.
Thank You
Tagged: Android push notifications, delivering pending push

**Comment by AlexanderPPetrov** [comment]
Hi, this article may help:
https://medium.freecodecamp.org/why-your-push-notifications-never-see-the-light-of-day-3fa297520793
