### ISSUE TITLE
Delete apps/expo-payments

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#7555]
Every app in the `apps/` folder adds extra time to the yarn install and git clone. We can/should move the IAP demo to NCL + Bare Expo. 

- `apps/expo-payments` is an ExpoKit app which is now deprecated in favor of the Bare Workflow.

**Comment by mauriciord** [comment]
@EvanBacon Sorry, but what is NCL?

**Comment by EvanBacon** [comment]
NCL = `apps/native-component-list`

We essentially have 2 different runners for apps in the expo repo.

- Bare Workflow: `app/bare-expo` -> loads `apps/test-suite` and `apps/native-component-list`
- Managed Workflow: Expo Client (`ios/` and `android/`) -> loads and Expo project (i.e. test-suite and native-component-list)

We optionally require it screens in native component list, so they are effectively skipped when run in a native app that is missing certain modules (like expo-in-app-purchases in the expo client).
