### ISSUE TITLE
detach problem

### ISSUE THREAD

**Issue by NicolaiV** [expo/expo#756]
Good afternoon.
How do I connect the module, requiring multiple changes in the manifest android (AndroidManifest.hml, android / build.gradle, android / app / build.gradle) so that I could continue to use the expo. For example, I want to use this module: https://github.com/geektimecoil/react-native-one signal
I used detach, made edits, and the expo stopped running the project.
Thank you

**Comment by quinlanj** [comment]
hi @NicolaiV , does the documentation here or similar people's problems help? https://docs.expo.io/versions/latest/guides/detach.html
https://github.com/expo/exp/issues/53
https://github.com/expo/expo/issues/403

Also , do you know what specific edit caused the project to stop running?

**Comment by terribleben** [comment]
Hi, if you still need help with this issue, I recommend asking on our [forums](https://forums.expo.io/), unless you think there's a bug with Expo we should be tracking here.
