### ISSUE TITLE
[expo-gl] Asset + texImage2d loading problem... this file!

### ISSUE THREAD

**Issue by pacoelayudante** [expo/expo#7560]
I found in this file a the thing that makes loading images to texImage2d limited to file://, seems like here the input is forced to be file://
¿is there a reason for this?
https://github.com/expo/expo/blob/3d9ef386bde5911d15306a46b50e7b1bcea3abf5/packages/expo-gl-cpp/cpp/EXGLContext.cpp#L82

**Comment by danmaas** [comment]
There is a longer discussion of this issue in #2693

**Comment by pacoelayudante** [comment]
whoops sorry, I'll contribute this info in there I guess?
