### ISSUE TITLE
expo-splash-screen does not autohides in iOS

### ISSUE THREAD

**Issue by rodrigorm** [expo/expo#7564]
### Environment

```
$ yarn expo diagnostics
yarn run v1.22.4
$ /private/tmp/myproject/node_modules/.bin/expo diagnostics

  Expo CLI 3.17.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.0.16 - /usr/local/bin/bash
    Binaries:
      Node: 13.11.0 - /var/folders/r0/t7_njzzn0zn9ysy82nryy51w0000gq/T/yarn--1585715691174-0.17658697551986946/node
      Yarn: 1.22.4 - /var/folders/r0/t7_njzzn0zn9ysy82nryy51w0000gq/T/yarn--1585715691174-0.17658697551986946/yarn
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.3 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.17.2

Done in 3.59s.
```

Target: iOS Standalone (Tested on Simulator)

### Steps to Reproduce

1. Start a new Bare project: `$ expo init --template bare-minimum`
2. Install `expo-splash-screen` using `$ expo install expo-splash-screen && cd ios && pod install`
3. Configure `expo-splash-screen` for iOS: https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-ios
4. Run project on Simulator/Device using `$ react-native run-ios`

### Expected Behavior

Splash screen should autohides when app finish loading.

### Actual Behavior

5. SplashScreen does not hides. Only works if add `SplashScreen.hideAsync()` on main component mount and according to `README.md` file on `expo-splash-scrren`:

> "The native splash screen that is controlled via this module autohides once the ReactNative-controlled view hierarchy is mounted. This means that when your app first renders view component, the native splash screen will hide."
> https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-api

### Reproducible Demo

https://github.com/rodrigorm/expo-splash-screen-issue-7564

**Comment by rodrigorm** [comment]
Added reproducible demo repository.

**Comment by bbarthec** [comment]
@rodrigorm, I confirm that the problem exists - thank you for reporting it 💯
The solution is on the way! 🎉

**Comment by bbarthec** [comment]
New `bare workflow` templates are already published so `expo init --template bare-minimum` will work with `expo-splash-screen` 🎉 
To manually apply update:
- please update `react-native-unimodules` in `package.json` to version `~0.9.0` 
- and in `ios` directory run `pod install`
Autohide should work fine after this package upgrade.

**Comment by rodrigorm** [comment]
Thank you for the rapid response. Can you please point to the changes made so I can aplly to my private project.

**Comment by brentvatne** [comment]
@rodrigorm - you can initialize a new project with expo-cli as @bbarthec suggested and compare, or follow the instructions that he provided for updating react-native-unimodules

**Comment by rodrigorm** [comment]
Ok, it worked, thanks again.
