### ISSUE TITLE
Audio recording needs to be multi-platform.

### ISSUE THREAD

**Issue by dooboolab** [expo/expo#757]
Hi. I am suffering from recorded audio files to be played in both platform because recorded audio has different extentions.

![image](https://user-images.githubusercontent.com/27461460/31395328-7bc9c560-ae1b-11e7-825d-f7f40a16edce.png)

If I want to record the audio to mp4 format on both platform, how should I set the variables?
I am really suffering from this.

**Comment by ccheever** [comment]
Hi-

We expose pretty much all the different options you can use for recording on the different platforms. If you use `RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC` I think that will be something compatible with most things that want to play mp3 audio. (mp4 is a video format).

**Comment by dooboolab** [comment]
@ccheever 
I've tried many options with given variables... but whenever I tried it it gave me this error. It only works in caf for ios.

![image](https://user-images.githubusercontent.com/27461460/31499069-a8eb994a-af9e-11e7-8b16-232a1acedbba.png)

Can you please check this? It always gives error with different extension and outputformat.

**Comment by nappels** [comment]
@dooboolab Did you ever figure this out? I'm suffering from the same issue now. I am thinking about using a service like transloadit, but I'd prefer if there was a way the expo Audio API could handle this for me.

**Comment by nappels** [comment]
@dooboolab in case you're still looking, I ended up using these options and recordings now work on both Android and iOS:

```
android: {
      extension: '.m4a',
      outputFormat: Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_MPEG_4,
      audioEncoder: Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AAC,
      sampleRate: 44100,
      numberOfChannels: 2,
      bitRate: 128000,
    },
    ios: {
      extension: '.m4a',
      outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC,
      audioQuality: Audio.RECORDING_OPTION_IOS_AUDIO_QUALITY_MIN,
      sampleRate: 44100,
      numberOfChannels: 2,
      bitRate: 128000,
      linearPCMBitDepth: 16,
      linearPCMIsBigEndian: false,
      linearPCMIsFloat: false,
    },
```

**Comment by dooboolab** [comment]
Thank you so much. I really appreciate it. However I ended up solving this issue by converting in server in my case it was in firebase function.
