### ISSUE TITLE
[docs] Documentation doesn't reflect latest changes with SDK 37

### ISSUE THREAD

**Issue by sreuter** [expo/expo#7574]
It seems like the docs don't reflect the changes of the SDK v37.

Examples:

https://docs.expo.io/versions/latest/workflow/configuration/#sdkversion ... should be removed
https://docs.expo.io/versions/latest/sdk/auth-session/ ... should reflect installation of unimodule plus updated import

**Comment by positimo** [comment]
Are the breaking changes explained somewhere? I wasn't able to find any info on the `AuthSession` changes.

**Comment by byCedric** [comment]
Hi @sreuter  and @positimo! Thanks for the heads up, just added a deprecation warning to the `sdkVersion` property in the manifest. The full documentation of the "newer" `app.json` is coming soon! Thankfully, the `auth-session` docs are now updated and reflect the new unimodule 😄 

> Are the breaking changes explained somewhere? I wasn't able to find any info on the AuthSession changes.

`AuthSession` was one of the last modules that wasn't extracted to a unimodule yet. I don't think `expo-auth-session` doesn't have breaking changes compared to the last `expo` version. In the future, these [should be documented here](https://github.com/expo/expo/blob/master/packages/expo-auth-session/CHANGELOG.md).

If you encounter any issues with `AuthSession`, feel free to open up a new issue report. Or if you just have a question, post it on [the forums](https://forums.expo.io/) or [join us on Slack](https://slack.expo.io/)!

Hope it helps 😄
