### ISSUE TITLE
Constants.installationId undefined in ios expo client 2.15.x

### ISSUE THREAD

**Issue by awinograd** [expo/expo#7585]
### Environment

  Expo CLI 3.16.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nodenv/versions/12.14.0/bin/node
      Yarn: 1.12.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nodenv/versions/12.14.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.6 => 4.0.6 

### Steps to Reproduce

Run this snack on latest iOS client:
https://snack.expo.io/@ouihealth/65078b

### Expected Behavior

Constants.installationId should be a uuid

### Actual Behavior

Constants.installationId is undefined

### Reproducible Demo

https://snack.expo.io/@ouihealth/65078b

**Comment by cruzach** [comment]
This was a regression, since we moved the code for `Constants.installationId` out into the `expo-constants` code (making it available for bare workflow apps)

If you upgrade to SDK 37, it will work in the Expo client app, and will still work in standalone builds on all SDKs

**Comment by awinograd** [comment]
Thanks for the info @cruzach. Glad to know this will work as expected once we update to SDK 37

**Comment by GuillaumeRZ** [comment]
Same problem here from Expo `SDK35.0`

I will try to upgrade and edit my message if `Constants.installationId` works. 👍
