### ISSUE TITLE
Views are moved by the Keyboard opening even when not wrapped in a KeyboardAvoidingView

### ISSUE THREAD

**Issue by ConorWatsonSoar** [expo/expo#7589]
## 🐛 Bug Report

Creating a new SDK37 project, or upgrading an existing one, causes all views to be pushed up when the Android Keyboard appears on the screen, regardless of the presence of a `KeyboardAvoidingView`. 

| SDK36 with Client v2.14.0 | SDK37 with Client v2.15.0 |
| ------------------------ | ------------------------ |
| ![SDK36](https://user-images.githubusercontent.com/58003329/78178386-7315b280-7457-11ea-9899-8547d0a37b89.gif)  |  ![SDK37](https://user-images.githubusercontent.com/58003329/78178488-a5271480-7457-11ea-8522-6293e535de4b.gif)

### Environment

``` bash
Expo CLI 3.17.5 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.9.1/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.3
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.2.2 => 4.2.2
```

Targeting Android via Standalone and Client. Reproduced on a Samsung Galaxy S10+, with the latest version of the Expo Client installed (v2.15.0).

### Steps to Reproduce

1. Create project in SDK37
2. Create a view with at least 1 text input, and a child view that has the style properties `{ flex: 1, justifyContent: "flex-end" }`
3. Run the project via Expo Android App.
4. Tap on the text input to open the keyboard

### Expected Behavior

Views should only be moved by the Keyboard when they are specifically wrapped in a `KeyboardAvoidingView` or similar component.

### Actual Behavior

Views are moved by the keyboard regardless of the presence of a `KeyboardAvoidingView`

### Reproducible Demo

Here is a snack that reproduces the effect. However, the effect does not seem to manifest itself using the in-built Android simulator.  
https://snack.expo.io/QOSLGAihc

To reproduce the effect, scan the QR code via a real Android Device. To reproduce the pre-SDK37 behaviour, change the Snack to run on SDK36 or below AND downgrade the Expo Client to v2.14.0 via [this link](https://d1ahtucjixef4r.cloudfront.net/Exponent-2.14.0.apk) or by copying the url from the "Download APK" link [here](https://expo.io/tools#client), and modifying the version number in the URL.

**Comment by brentvatne** [comment]
cc @bbarthec

**Comment by ConorWatsonSoar** [comment]
If it helps to debug this issue, it's likely due to a change made in https://github.com/expo/expo/pull/6506. Unfortunately I don't know Android Development well enough to pinpoint the issue.

**Comment by Rohansi** [comment]
This affects my app using SDK 35 in client v2.15.0. Is there any chance of it being patched in SDK 37 or would it need to wait for 38?

**Comment by brentvatne** [comment]
So the issue here seems to be that the default has changed from having `windowSoftInputMode` `adjustPan` behavior to `adjustResize`. This was always confusing before because the default was `adjustPan` and there was no way to switch to `adjustResize` directly, it was implicit (https://github.com/expo/expo/issues/1065) based on seemingly unrelated `androidStatusBar` config.

Experimenting with the current behavior I noticed that it's possible to get `adjustPan` behavior by setting the status bar to hidden. Hope this is helpful @bbarthec!

**Comment by brentvatne** [comment]
related: https://github.com/expo/expo/issues/7635

**Comment by outaTiME** [comment]
Hi guys, 
the same issue after upgrading to Expo 37 (on Android only) with the following code:

```js
import React from 'react';
import { KeyboardAvoidingView } from 'react-native';
import Layout from '../config/layout';

export default ({ useNavigationOffset, ...props }) => {
  return (
    <KeyboardAvoidingView
      behavior="padding"
      {...(useNavigationOffset === true && {
        keyboardVerticalOffset: Layout.APPBAR_HEIGHT,
      })}
      {...props}
    />
  );
};
```

![KeyboardAvoidingView with Android](https://user-images.githubusercontent.com/140472/78608733-c9a83580-7837-11ea-905b-d36d20935452.gif)

It will fixed on this expo version or should we wait until the next release?

**Comment by sebastianlele1017** [comment]
Currently my app with SDK 36 is facing this issue...is there any workaround ?

**Comment by shtefanilie** [comment]
Yep, same issue here. This is really messed up...

**Comment by shystruk** [comment]
+1

**Comment by Chofito** [comment]
Same :/

**Comment by trexpert** [comment]
Same here. Unfortunately this is a big blocker for upgrading to new SDK. Bad thing about this is: the same error occurs within the expo client. So the expo app 2.15 can not be used. We have to keep 2.14 installed.

**Comment by bonafidehan** [comment]
@trexpert this error doesn't appear in Expo client 2.14? It would be great if that's a valid rollback point.

**Comment by Rohansi** [comment]
> @trexpert this error doesn't appear in Expo client 2.14? It would be great if that's a valid rollback point.

Yes, but it also means you need to hold off on SDK 37 entirely because both Expo client 2.15 and standalone SDK 37 exhibit this behavior. Really need a fix for this or I'm going to have to revert to SDK 36 myself.

**Comment by trexpert** [comment]
> @trexpert this error doesn't appear in Expo client 2.14? It would be great if that's a valid rollback point.

Sorry for late feedback. Yes this problem does not occur in 2.14. But i gues this is more related to the SDK update - which is used for 2.15 i guess

**Comment by bbarthec** [comment]
Original problem reported by @ConorWatsonSoar can be resolved by using solution from https://github.com/expo/expo/issues/7815#issuecomment-614721573.

**Comment by adlme** [comment]
This sucks guys! We should be able to switch from adjustResize to adjustPan. Please give us a fix!

**Comment by dvester** [comment]
I cannot show the status bar at all, without having the keyboard resize the view. What is the plan to address this?

**Comment by Ksedline** [comment]
For me this problem reproduces only with GBoard Keyboard, but it's okay with default Xiaomi keyboard.

**Comment by Ksedline** [comment]
I found the solution that fix the problem on Android with StatusBar.
Maybe it will be useful for someone.
Just add to the root View of a Screen this style code:
`{ minHeight: Math.round(Dimensions.get('window').height) }`
Then keyboard will not resize the view.

**Comment by Rohansi** [comment]
> I found the solution that fix the problem on Android with StatusBar.

This does work for most devices but will leave a gap at the bottom of the screen for some newer devices. `Dimensions.get('window')` is [broken for devices with a notch](https://github.com/facebook/react-native/issues/23693).

**Comment by brunohkbx** [comment]
+1

**Comment by kevinjpetersen** [comment]
+1, I really hope for a fix soon!

**Comment by tomas932** [comment]
> I found the solution that fix the problem on Android with StatusBar.
> Maybe it will be useful for someone.
> Just add to the root View of a Screen this style code:
> `{ minHeight: Math.round(Dimensions.get('window').height) }`
> Then keyboard will not resize the view.
> 
> (Tested in Android Google Pixel Emulator, and Xiaomi Mi9T with GBoard)

It worked! Try this everybody. Fixed styles for root component over root navigation. Useful upvote

**Comment by outaTiME** [comment]
Hi guys, any update about this issue? 
sizing the root view with full height or using undefined in android behavior is not a valid solution / workaround, every Expo SDK version is affected by this issue (in expo client 2.15.x and in standalone mode too).

Take a look to the following example, on android (the OS affected)

running with SDK 34 (built on oct' 19) :

![CleanShot 2020-06-03 at 22 25 36](https://user-images.githubusercontent.com/140472/83704715-4b72d000-a5e9-11ea-8656-a533b5a29911.gif)

the same code running on SDK 34 (built today):

![CleanShot 2020-06-03 at 22 09 40](https://user-images.githubusercontent.com/140472/83704726-52014780-a5e9-11ea-8f4f-08512980627e.gif)

and here is the render code:

```js
<Formik
  ref={(ref) => {
    this._form = ref;
  }}
  initialValues={{
    username: this.state.username,
    password: this.state.password,
  }}
  validateOnChange={false}
  validationSchema={yup.object().shape({
    username: yup.string().trim().required(I18n.t('user_required')),
    password: yup.string().trim().required(I18n.t('password_required')),
  })}
  onSubmit={(values) => {
    this.props.login(values.username, values.password);
  }}
  render={({ handleSubmit, isSubmitting }) => (
    <View style={styles.container}>
      <View style={styles.logoContainer}>
        <Image
          style={styles.logo}
          source={require('../assets/images/logo.png')}
        />
      </View>
      <KeyboardAvoidingView behavior="padding">
        <Field
          name="username"
          component={FormTextInput}
          big
          placeholder={I18n.t('user')}
          autoCapitalize="none"
          autoCorrect={false}
          returnKeyType="next"
          onSubmitEditing={() => {
            this._inputPassword.focus();
          }}
        />
        <Field
          name="password"
          component={FormTextInput}
          big
          placeholder={I18n.t('password')}
          autoCapitalize="none"
          autoCorrect={false}
          secureTextEntry
          returnKeyType="done"
          elementRef={(ref) => {
            this._inputPassword = ref;
          }}
        />
      </KeyboardAvoidingView>
      <ActionButton
        // login
        large
        rounded
        text={I18n.t('sign_in_button')}
        isLoading={isSubmitting}
        onPress={handleSubmit}
      />
      <TouchableHighlight
        underlayColor="transparent"
        onPress={this._onPressSupport}
        style={{
          padding: Layout.CONTAINER_PADDING,
        }}
      >
        <Text style={[styles.linkStyle]}>{I18n.t('support_button')}</Text>
      </TouchableHighlight>
      <BlockOverlay
        visible={isSubmitting}
        // fullscreen
      />
    </View>
  )}
/>
```

**Comment by micbigtree** [comment]
Used and upvoted your workaround @Ksedline , nice one. But this needs fixing officially.

**Comment by FrankieJLyons** [comment]
Also having this issue, surely this is a property that should be able to be set in a view component or in the app.json?

**Comment by brunohkbx** [comment]
> Also having this issue, surely this is a property that should be able to be set in a view component or in the app.json?

You can specify it in the `app.json` using the key `softwareKeyboardLayoutMode` under android.

**Comment by chris-chao** [comment]
=

> > Also having this issue, surely this is a property that should be able to be set in a view component or in the app.json?
> 
> You can specify it in the `app.json` using the key `softwareKeyboardLayoutMode` under android settings.

I'm running SDK 37. I tried specifying the `softwareKeyboardLayoutMode` key in the `app.json` but  it gives me a "Property is not allowed" error. Has there been any update with this?

**Comment by Rohansi** [comment]
> I'm running SDK 37. I tried specifying the `softwareKeyboardLayoutMode` key in the `app.json` but it gives me a "Property is not allowed" error. Has there been any update with this?

You need to upgrade to SDK 38 to use it.

**Comment by Shishir198** [comment]
> I found the solution that fix the problem on Android with StatusBar.
> Maybe it will be useful for someone.
> Just add to the root View of a Screen this style code:
> `{ minHeight: Math.round(Dimensions.get('window').height) }`
> Then keyboard will not resize the view.
> 
> (Tested in Android Google Pixel Emulator, and Xiaomi Mi9T with GBoard)

This worked for me Thanks a Lot man..

**Comment by vavdoshka** [comment]
[Here](https://github.com/expo/expo/issues/7815#issuecomment-645545005) it seems like a more long term fix with `softwareKeyboardLayoutMode` in the `app.json`

SDK should be v38 to use that feature. 
Could be useful - I was having [this](https://github.com/th3rdwave/react-native-safe-area-context/issues/110#issuecomment-668864576) issue when upgraded from v37 to v38.

**Comment by tickietackie** [comment]
> I found the solution that fix the problem on Android with StatusBar.
> Maybe it will be useful for someone.
> Just add to the root View of a Screen this style code:
> `{ minHeight: Math.round(Dimensions.get('window').height) }`
> Then keyboard will not resize the view.
> 
> (Tested in Android Google Pixel Emulator, and Xiaomi Mi9T with GBoard)

React Native Doc says, this should better be done with useWindowsDimension. This also works, so I implemented it that way.

https://reactnative.dev/docs/usewindowdimensions

**Comment by e3bmo3ty** [comment]
> minHeight: Math.round(Dimensions.get('window').height)

thats works for me, so weird XD

**Comment by Jarrettgohh** [comment]
As of expo version ~41.0.1, adding the following in `app.json` works

    "android": {
      "softwareKeyboardLayoutMode": "pan"
}
