### ISSUE TITLE
This error message is practically useless

### ISSUE THREAD

**Issue by mark0978** [expo/expo#759]
```
Warning: Problem validating fields in app.json. See https://docs.expo.io/versions/v19.0.0/guides/configuration.html.
 • should be equal to one of the allowed values.
```

Which field(s) is it not happy with?  I've looked at the page but I can't tell which of my params it doesn't like.

**Comment by terribleben** [comment]
You're right. I believe we have a fix pending? cc @skevy

**Comment by skevy** [comment]
We do indeed. There's a server side fix that makes this warning into an error during publish, and a client-side (XDL) fix that makes this error message better.

For now @mark0978, do you want to send me your app.json (or paste it here, with sensitive info removed?). I can tell you which field is invalid.

**Comment by mark0978** [comment]
```
{
  "expo": {
    "name": "appName",
    "description": "app description",
    "slug": "yumm",
    "privacy": "private",
    "sdkVersion": "19.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true
    }
  }
}
```

**Comment by skevy** [comment]
`privacy` should be "unlisted" or "public", not "private"
