### ISSUE TITLE
Error: package expo.loaders.provider.interfaces does not exist (update from SDK 36 to 37)

### ISSUE THREAD

**Issue by Andrea-Arguello** [expo/expo#7591]
### Environment

```
Expo CLI 3.15.5 environment info:
    System:
      OS: Linux 5.3 Pop!_OS 18.04 LTS
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.19.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.13.4 - /usr/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^3.1.4 => 3.11.1 
```

Project is in ExpoKit already updated to SDK 37 also

### Steps to Reproduce
Update from SDK 36 to SDK 37

### Expected Behavior

Android build without issues

### Actual Behavior

```
android/app/src/main/java/host/exp/exponent/MainApplication.java:10: error: package expo.loaders.provider.interfaces does not exist
import expo.loaders.provider.interfaces.AppLoaderPackagesProviderInterface;
                                       ^
android/app/src/main/java/host/exp/exponent/MainApplication.java:27: error: cannot find symbol
public class MainApplication extends ExpoApplication implements AppLoaderPackagesProviderInterface<ReactPackage> {
                                                                ^
  symbol: class AppLoaderPackagesProviderInterface
2 errors 
```

**Comment by Andrea-Arguello** [comment]
Solved by changing the import MainApplication.java of my project
```diff
- import expo.loaders.provider.interfaces.AppLoaderPackagesProviderInterface;
+ import org.unimodules.apploader.AppLoaderPackagesProviderInterface;
```

**Comment by Andrea-Arguello** [comment]
Regarding my previous comment, this is something I noticed that was deleted from the MainApplication.java from [SDK 36](https://github.com/expo/expo/blob/8762a476448406d3d82ed224d239a5013f780af0/android/app/src/main/java/host/exp/exponent/MainApplication.java) to [SDK 37](https://github.com/expo/expo/blob/master/android/app/src/main/java/host/exp/exponent/MainApplication.java). So, this is either a bug that needs to be fixed, or intentional and needs to be added to the upgrading documentation. Therefore, I am leaving this issue open.

**Comment by jb9229** [comment]
after applying the @Andrea-Arguello solution.

i get the other issue
<img width="1137" alt="스크린샷 2020-04-14 오후 12 44 15" src="https://user-images.githubusercontent.com/3200647/79184282-accebc00-7e4e-11ea-948e-a65b01a2678f.png">

**Comment by mczernek** [comment]
@jb9229 This issue seems unrelated. Please provide some more info and open seperate issue.

@Andrea-Arguello Package and location of `AppLoaderPackagesProviderInterface` has changed indeed. However, main purpose of this package is to be used in managed workflow. Hence, we haven't seen it appropriate to include it in migration guide, as most users do not use this package whatsoever.

Can you please provide some details on what is your use case? What made you import this class and (probably) make your application implement the interface?

**Comment by mczernek** [comment]
@Andrea-Arguello Let me close this for now. If I misunderstood you or missed something, we will either reopen or create new issue accordingly.
