### ISSUE TITLE
RNCNetInfo.getCurrentState got 2 arguments, expected 3 after updating to Expo SDK 37

### ISSUE THREAD

**Issue by rafmrs** [expo/expo#7599]
### Environment

```
  Expo CLI 3.17.11 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: 0.61.4 => 0.61.4 
      react-navigation: ^4.3.6 => 4.3.6 
    npmGlobalPackages:
      expo-cli: 3.17.11
```

iOS and Android

### Steps to Reproduce

I just updated my app to Expo SDK 37.

### Actual Behavior

It shows a red error saying `RNCNetInfo.getCurrentState got 2 arguments, expected 3`. I searched for this error on google and found out this on netInfo Github issues page: https://github.com/react-native-community/react-native-netinfo/issues/297. The thing is, that there, the error is the opposite, get 3 arguments and expected 3.

I don't know how, but after I did `expo install @react-native-community/net-info` it worked and I was able to fix other things, but now is back to the same error. 

**EDIT**: On iOS when I try to open the app via Expo Client, it just crashes, no error nothing. This error shows only on Android

**Comment by rafmrs** [comment]
I am using `"@react-native-community/netinfo": "^5.7.0",` right now, tried with 4.6.0 version but got the same error.

**Comment by rafmrs** [comment]
Just figured it out this is actually a `@bugsnag/expo` bug. I asked them to bump the `@react-native-community/netinfo` version.

**Comment by Yashwanthv21** [comment]
@rafmrs is there a temporary fix for this problem? Where you able to run your application?

**Comment by rafmst** [comment]
My problem was actually with another package, specifically @bugsnag/expo, they fixed it so you can solve by updating the package. If you are not using @bugsnag/expo this might mean that another package that you use, is also using a dated version of netinfo package. Let me know if this helps 😉

**Comment by agentlewis** [comment]
Having the same error after upgrading. Trying to work out if there is another package using the old version as you have described. So far no dice.

**Comment by lucianmurmurache** [comment]
I am also facing the same issue. Any luck @agentlewis?

**Comment by rafmst** [comment]
Try to search only on node_modules folder for netinfo and check if any package.json is requiring wrong version

**Comment by lucianmurmurache** [comment]
Thank you for the tip @rafmrs . You're a good man!

**Comment by agentlewis** [comment]
As per @rafmst comment check your modules for explicit dependencies. Mine was aws-appsync see here: https://github.com/aws-amplify/amplify-js/issues/5359
