### ISSUE TITLE
<StatusBar hidden /> not hiding StatusBar

### ISSUE THREAD

**Issue by chownation** [expo/expo#76]
StatusBar (without ability to replicate) randomly appears, despite add <StatusBar hidden /> component in top level view component

**Comment by omerdn1** [comment]
Use `StatusBar.setHidden(true);` on componentWillMount

**Comment by terribleben** [comment]
There's an issue we're aware of with `StatusBar` on iOS when running inside Expo Client only. You may see incorrect behavior when moving between the Expo Client home screen and your app (or other apps). This won't happen in a standalone build created with `exp build`.

**Comment by terribleben** [comment]
Shipping a fix for this with SDK 16 in a few days.

**Comment by terribleben** [comment]
We shipped an update today which should address this, but we just found another (related) issue, and the fix will go out in a few days, perhaps Monday depending on Apple review time. So depending on which issue was affecting your app, this may or may not be fixed.

**Comment by terribleben** [comment]
iOS v1.15.2 (out today) fixes all remaining issues I'm aware of with `StatusBar`. Let me know if you're still seeing problems.

**Comment by chownation** [comment]
@terribleben still seeing issue with StatusBar where most of the times, it pops up as white text (vs. previously black / dark regular theme).

**Comment by terribleben** [comment]
The StatusBar bug that would never die

**Comment by terribleben** [comment]
We are QAing this possible fix for next release: https://github.com/expo/expo/commit/0ab8227df526ca81a14fb4794d849b4e281a1b6e

**Comment by IljaDaderko** [comment]
@terribleben ran into use case that might be similar and might add context. Hiding status bar works fine, but fails in following cases:

1) Status bar is still visible in expo's splashcreen
2) It is hidden in the app, however when bottom drawer is opened (one with airplane mode / wifi etc..) and closed it appears back in the app.

**Comment by terribleben** [comment]
Closing again, as I believe the most recent fix actually did fix this (haven't had any further reports since the fix went out).

**Comment by chownation** [comment]
Thanks Team Expo!
