### ISSUE TITLE
Implicit declaration of function 'RCTAssertMainThread' is invalid in C99

### ISSUE THREAD

**Issue by doc-phily** [expo/expo#760]
I'm using ExpoKit 21.0.0 - ejected from expo so I could use react-native-firebase (for its Firestore support). The offending module EXFrame.m on the path ios/Pods/ExpoKit/ios/Exponent/Versioned/Modules/Internal/Frame/EXFrame.m

**Comment by ccheever** [comment]
can you paste the complete error message here? you're just building it with Xcode?

**Comment by terribleben** [comment]
Did you `pod install` and open the resulting `xcworkspace` file as described in the docs?

**Comment by doc-phily** [comment]
Closing issue because I overcame this by recreating the project using react-native-create-app and coping all my source-code over to the new project using `npm run eject` and following the instructions thereafter.
