### ISSUE TITLE
Icons not appearing And app exceed screen size after SDK Update 37 

### ISSUE THREAD

**Issue by adrientiburce** [expo/expo#7605]
### Environment

```
Expo CLI 3.17.11 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.17.11
```

Target : Android

### Steps to Reproduce

 **1st issue : Icons are not appearing** in my app in expo (android v2.15.0) I'm using : 
* `react-native-vector-icons/FontAwesome`
* `@expo/vector-icons`

As described here :  [forum expo](https://forums.expo.io/t/icons-are-not-appearing-after-the-sdk-33-update/23596), icons are visible when running the app with `expo start`
I also tried to update expo and font packages as explained but it didn't resolved the issue 

Here is a part of my  `package.json` : 
```json
"expo": "^37.0.0",
    "expo-asset": "^8.1.4",
    "expo-cli": "^3.17.5",
    "expo-constants": "^9.0.0",
    "expo-font": "^8.1.0",
```

**2nd issue : screen app is cropped** in the expo again (see below screenshot, at the top) again this problem doesn't appear with `expo start`.

![92144645_212796873358067_2773194790286655488_n](https://user-images.githubusercontent.com/34744867/78250498-39dd5100-74f0-11ea-9a16-1067b5b99c74.jpg)
)

### Expected Behavior
The screen fits correctly with `expo start` (and the icons)
![91997267_897123307414441_5913687783498579968_n](https://user-images.githubusercontent.com/34744867/78249863-5036dd00-74ef-11ea-91e9-7144823a92fe.jpg

### Question 
As I'm here I'd like to ask why I can still see and run the app I ran with `expo start`, even when `expo-cli ` and the `metro bundler` are stopped.

- on the screenshot the second app  : 
![91794715_1361479564054426_920253595650097152_n](https://user-images.githubusercontent.com/34744867/78250790-b2441200-74f0-11ea-817b-ad70655611bc.jpg)

As explained in the  [doc](https://docs.expo.io/versions/latest/workflow/publishing/) : 
> if you turn off your laptop or stop Expo CLI, you won’t be able to load your project from that URL

Is it because of the latency of the tunnel, how does the tunnel works exactly and what's the difference with `expo publish`.

**Comment by mikelgarciaurbina** [comment]
I have the same problem. I upload to SDK 37 and my icons not appear. And my custom fonts are not loading.

**Comment by IjzerenHein** [comment]
So just to recap and to make sure we understand your problem adequately. This problem is not happening when using `expo start` but only when using `expo publish`. Is that correct?

**Comment by danilo900** [comment]
Its happening because of the expo-font problem with SDK 37.
Iam here with the same problem.
On my custom font and on material icon that use expo-font to load.

**Comment by danilo900** [comment]
It worked here guys!

rm -rf node_modules
npm cache clean --force
rm -rf .expo
rm package-lock.json
npm install

**Comment by adrientiburce** [comment]
@danilo900 It doesn't works for me with `expo publish`.

**Comment by geoffreynyaga** [comment]
Had the same problem with icons and also my fonts not loading using the Fonts.loadAsync() call that was working previously. And all my icons were messed up (showing weird symbols and Asian fonts/characters). 

Turns out that there was a duplicate `expo-font` package in `node_modules/expo-font` and in `node_modules/expo/node_modules/expo-font`.

And also turns out its an `npm` issue. 

Use yarn and run `yarn install` and it should clean up the node_modules/expo/node_modules

That solves the font issue and the icons issue.

**Comment by brentvatne** [comment]
we work around the npm issue now by deleting package-lock.json and clearing node_modules when you run `expo upgrade`! so this should not be an issue for folks updating using the latest version of expo-cli anymore
