### ISSUE TITLE
expo-document-picker on dark mode not working properly in Expo SDK 37

### ISSUE THREAD

**Issue by rafmrs** [expo/expo#7609]
I think the new update somehow affected expo-document-picker. I have `8.1.0` and it looks like this after SDK update. I hope this screenshots help in some way

![image](https://user-images.githubusercontent.com/44644902/78259550-22589500-74fd-11ea-92b6-2e7b93de7209.png)

![image](https://user-images.githubusercontent.com/44644902/78259649-43b98100-74fd-11ea-99b5-4710a7c40dad.png)

**Comment by IjzerenHein** [comment]
Hi! Which screenshot appears wrong to you, the first or the second?

**Comment by rafmst** [comment]
Both, they should be dark like it was in the previous version. For example in the first screenshot, the Browser button background was also dark when in dark mode

**Comment by IjzerenHein** [comment]
Screenshots on Expo client 36:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-08 at 09 04 50](https://user-images.githubusercontent.com/6184593/78754615-15fa8f00-7978-11ea-9074-7e04056ad198.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-08 at 09 05 00](https://user-images.githubusercontent.com/6184593/78754625-18f57f80-7978-11ea-9280-0fa98df133fe.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-08 at 09 05 05](https://user-images.githubusercontent.com/6184593/78754637-1c890680-7978-11ea-99dc-8092cb95ca0c.png)

**Comment by rafmst** [comment]
That is exactly what I'm talking about, thanks for sharing.

**Comment by IjzerenHein** [comment]
This seems to not only apply to the document picker. I'm investigating it as we speak. Thanks for reporting this!

**Comment by IjzerenHein** [comment]
Hey! Well it seems that there was a problem with Expo Client 36 which didn't fully respect the `userInterfaceStyle` setting in your `app.json`. You probably have `userInterfaceStyle` set to `light` in your app.json. If you want to support dark-mode please follow the instructions in [Appearance](https://docs.expo.io/versions/v37.0.0/sdk/appearance/) and use the `automatic` option.

**Comment by rafmrs** [comment]
I actually didn't have that property at all, added:

```
{
  "expo": {
    "userInterfaceStyle": "automatic",
```

and its working perfectly. Thanks for the help.

**Comment by IjzerenHein** [comment]
Great, glad it works!
