### ISSUE TITLE
Alternatives to Expo?

### ISSUE THREAD

**Issue by expelledboy** [expo/expo#761]
I am evaluating expo, and require an argument which includes comparison with other frameworks. Any suggestions? Ionic seems to be the only thing 1 to 1 comparable.

**Comment by acomito** [comment]
https://cruxlab.com/blog/reactnative-vs-xamarin/

**Comment by ccheever** [comment]
This might be helpful. https://docs.expo.io/versions/latest/introduction/why-not-expo.html

**Comment by quinlanj** [comment]
Hey @expelledboy, I am closing this github issue, since we want to only keep open the ones with software bug issues. Really appreciate your constructive discussion re: expo + alternatives, and for such things, we usually talk about them in forums.expo.io instead.

**Comment by expelledboy** [comment]
@quinlanj It would be helpful to include a wiki page or a readme section with alternatives.
@acomito @ccheever Thanks really great read!
