### ISSUE TITLE
Trouble building ios after bare eject

### ISSUE THREAD

**Issue by tmorone-rezi** [expo/expo#7610]
### Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.5.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.23 
      @types/react-native: ~0.61.22 => 0.61.22 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.13.1

ios

### Steps to Reproduce

Doing a bare eject of an expo project with the following dependencies:
"expo": "~36.0.0",
"react": "~16.9.0",
"react-dom": "~16.13.0",
"react-native": "~0.61.4",
"react-native-gesture-handler": "~1.5.0",
"react-native-reanimated": "~1.4.0",
"react-native-screens": "2.0.0-beta.13",
"react-native-unimodules": "~0.7.0",
"react-native-web": "~0.12.2",
"react-native-appearance": "~0.3.1",
"react-native-paper": "^3.6.0",
"react-native-picker-select": "^6.6.0",
"react-relay": "experimental",
"react-router": "next",
"react-router-dom": "next",
"react-router-native": "next",
"relay-runtime": "^9.0.0",
"styled-components": "^5.0.1",
"yup": "^0.28.3"

My ios project has additional needs, therefore Podfile includes
use_frameworks!
use_modular_headers!

Building ios produces an error:
interface/ios/UMPermissionsInterface/UMPermissionsInterface.h:4:9: fatal error: 'UMCore/UMModuleRegistry.h' file not found
    #import <UMCore/UMModuleRegistry.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

I found that upgrading the following dependencies will get past the missing header:
  "expo": "~37.0.0",
  "react": "^16.13.0",
  "react-native": "0.61.5",
  "react-native-unimodules": "^0.8.0"

But the ios build now produces a linker error:
  "_OBJC_CLASS_$_RCTImageLoader", referenced from:
          objc-class-ref in EXImageLoader.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Expected Behavior

Podfile should be compatible with use_frameworks!

**Comment by brentvatne** [comment]
you should initialize a new project with `expo init` and choose a bare template and compare with your existing project

**Comment by carsondarling** [comment]
I'm seeing the same issue. After initializing a new bare project, and adding `use_frameworks!` to my Podfile, I get the same error as above.

### Environment 
  Expo CLI 3.17.11 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.17.11

### Error

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTImageLoader", referenced from:
      objc-class-ref in EXImageLoader.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If it's helpful, I can create a repo that reproduces the issue.

It's unfortunate because it was my understanding was that #6503 was supposed to fix this issue.

**Comment by carsondarling** [comment]
I went ahead and created a repo that reproduces this error:

https://github.com/carsondarling/expo37_use_frameworks_error_demo

**Comment by brentvatne** [comment]
thanks @carsondarling!

**Comment by brentvatne** [comment]
this should be resolved now -- https://github.com/expo/expo/commit/4559b35a9f3df9fcdc9bd8fa5bae4b99a6cd4bf9

please delete your yarn.lock and node_modules and reinstall to ensure that you get expo-image-loader@1.0.1

alternatively you can exclude it from your project in the Podfile as described in this section of the react-native-unimodules readme: https://github.com/unimodules/react-native-unimodules#-configure-ios

**Comment by carsondarling** [comment]
@brentvatne Can confirm that it works for me. Thank you for your quick work!
