### ISSUE TITLE
[docs] Help people get the dev menu keyboard shortcut working in Android emulator

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#7612]
It's necessary to change this setting in AVD configuration:

<img width="619" alt="Screen Shot 2020-04-02 at 10 17 11 AM" src="https://user-images.githubusercontent.com/90494/78278764-5e730200-74cb-11ea-918d-978089cabcab.png">

**Comment by WGrose1** [comment]
Any advice on if this still doesn't show the dev menu, I've tried everything and it never shows??

**Comment by brentvatne** [comment]
if this doesn’t fix the issue for you then make sure that you are using the latest version of expo client - run expo client:install:android
