### ISSUE TITLE
[expo-screen-orientation] Wrong property name in emitted event

### ISSUE THREAD

**Issue by awinograd** [expo/expo#7618]
### Steps to Reproduce

https://github.com/expo/expo/blob/9d91150837a667fe3cc468b304394dd3cbc9a902/packages/expo-screen-orientation/src/ExpoScreenOrientation.web.ts#L47

I believe `orientation` should be changed to `orientationInfo: { orientation }` to match the expected payload in the following snipped:

https://github.com/expo/expo/blob/fb527209c69f3b2cfab634c7ea55a967997c967f/packages/expo-screen-orientation/src/ScreenOrientation.ts#L173-L176

### Expected Behavior

orientationInfo is defined

### Actual Behavior

orientationInfo is undefined on web `ScreenOrientation.addOrientationChangeListener`

### Reproducible Demo

n/a

**Comment by brentvatne** [comment]
care to open a pull request?

**Comment by awinograd** [comment]
Hey @brentvatne, yes I can get something open in the next few days
