### ISSUE TITLE
Fonts aren't loading in Expo SDK 34+

### ISSUE THREAD

**Issue by jcush** [expo/expo#7619]
### Environment

Expo CLI 3.17.11 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.1 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.17.11

iOS (iPhone XS running 13.3.1)

### Steps to Reproduce

1. Upgrade Expo SDK from v33 to v34 or v35

OR

1. Install Expo SDK v35

### Expected Behavior

Fonts loaded via Font.loadAsync (and, by extension, useFonts) still load successfully as in previous SDK versions

### Actual Behavior

Firstly, an error occurs suggesting the font has not yet been loaded in using Font.loadAsync and is not a system font. 

The Font.loadAsync promise returns undefined, I thought due to the fact expo-font's tsconfig file extends "expo-module-scripts/tsconfig.base" but expo-module-scripts not installed by Expo...

_NB: Worth mentioning I did remove my node_modules directory and package-lock.json before trying the manual install_

*Update:* I removed my solution, which was to install expo-module-scripts, as the error has now returned without modifying any code...

Please help!

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code.

**Comment by jcush** [comment]
I could have created the example in here.... but ok, I'll create a new issue

**Comment by brentvatne** [comment]
it's easier for us from an issue management point of view to keep issues closed until it is demonstrated that they are actual issues

**Comment by jcush** [comment]
Gotcha, no worries
