### ISSUE TITLE
AuthSession + Auth0 Success Redirect Shows 404

### ISSUE THREAD

**Issue by githubandrewd** [expo/expo#762]
Hi,
We are trying to use auth0 and Expo's AuthSession to authenticate users in a browser and then direct them back to the application with the token, etc..
Right now when using

`exp start`

and testing on iOS and Android through expo app, we see the auth0 lock screen and then it redirects back to our app perfectly.

But after building standalone ipa and apk files from the auth0 lock screen success it redirects to the following url:
https://expo.io/@myuser/{project-slug}/+expo-auth-session#access_token=[TOKEN]&scope=openid&expires_in=7200&token_type=Bearer&state=[somevalue]

This works in development mode with exp start, as mentioned above, but not when we create a release APK.

In the release APK, the page shows "404. Looks like the page you are looking for does not exist. Here are some links to bring you back to Expo", and there are 3 options:
1. return home,2
2. log in to your account,
3. create an account.

We expected the app to actually close the browser and return the access token back to javascript. 

So we are kind of stuck right now. Any help would be really great. Thanks

Our project is configured using
`"expo": "^21.0.2" 

"react": "^16.0.0-alpha.12"

 "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",`

We are using the following commands to generate apk and ipa.

```
exp build:android
exp build:ios
```

**Comment by ide** [comment]
@brentvatne Looks like the linking URI might not be right in standalone apps?

**Comment by ercpereda** [comment]
This is happened to when I publish the app to expo. It works fine in development mode.

**Comment by ercpereda** [comment]
I found my issue if I open the app using the url `https://exp.host/@<user>/<application>` does not work. But if instead I use the `exp://exp.host/@<user>/<application>` works.

**Comment by brentvatne** [comment]
hi there! this is resolved in android standalone apps as of sdk22. be sure to add a `scheme` to your app in `app.json` before you build, so that you can deep link into it. :)

**Comment by smnodame** [comment]
I need some help!!
my android app refresh after finish login with AuthSestion + Auth0
which i can not handle anything after login
this happend just in Android. IOS works fine

**Comment by FezVrasta** [comment]
I experience the same problem with SDK 22. All my devices work properly, but one of a friend of mine doesn't and returns a 404 after the redirect.
