### ISSUE TITLE
Fonts aren't loading in Expo SDK 34+ 

### ISSUE THREAD

**Issue by jcush** [expo/expo#7620]
### Environment

Expo CLI 3.17.11 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.1 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.17.11

iOS (iPhone XS running 13.3.1)

### Steps to Reproduce

1. Upgrade Expo SDK from v33 to v34 or v35

OR

1. Install Expo SDK v35

### Expected Behavior

Fonts loaded via Font.loadAsync (and, by extension, useFonts) still load successfully as in previous SDK versions

### Actual Behavior

Firstly, an error occurs suggesting the font has not yet been loaded in using Font.loadAsync and is not a system font. 

The Font.loadAsync promise returns undefined, I thought due to the fact expo-font's tsconfig file extends "expo-module-scripts/tsconfig.base" but expo-module-scripts not installed by Expo...

_NB: Worth mentioning I did remove my node_modules directory and package-lock.json before trying the manual install_

### Reproducable Example

So, the fonts were all working just fine until the upgrade from SDK 33 (so I doubt it's my code, but I may be wrong!) but the file using Font.loadAsync is below. Due to NDA reasons I can't provide the full working app (I'm sure that's understandable). As I said though, this _exact_ code worked until the upgrade

```
import React, { Component } from 'react';
import { Image, View } from 'react-native';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import * as Font from 'expo-font';
import { createAppContainer, createStackNavigator, createSwitchNavigator } from 'react-navigation';
import BoardScreen from '../screens/boardScreen';
import FAQScreen from '../screens/faqScreen';
import HistoryScreen from '../screens/historyScreen';
import HomeScreen from '../screens/homeScreen';
import LoginScreen from '../screens/loginScreen';
import OnboardingScreen from '../screens/onboardingScreen';
import PlanChoiceScreen from '../screens/planChoiceScreen';
import ProfileScreen from '../screens/profileScreen';
import RegistrationScreen from '../screens/registrationScreen';
import * as appLoadActions from '../actions/appLoadActions';
import * as authActions from '../actions/authActions';
import { isEmpty } from '../libraries/objects';

const createGuestNavigator = ( guestRoute = null ) => {
	return createStackNavigator(
		{
			Onboarding: {
				screen: OnboardingScreen
			},
			PlanChoice: {
				screen: PlanChoiceScreen
			},
			Register: {
				screen: RegistrationScreen
			},
			Login: {
				screen: LoginScreen
			}
		},
		{
			headerMode: 'none',
			initialRouteName: guestRoute || 'Onboarding'
		}
	);
}

const MemberNavigator = createStackNavigator(
	{
		Profile: {
			screen: ProfileScreen
		},
		Home: {
			screen: HomeScreen
		},
		Board: {
			screen: BoardScreen
		},
		History: {
			screen: HistoryScreen
		},
		FAQ: {
			screen: FAQScreen
		}
	},
	{
		headerMode: 'none',
		initialRouteName: 'Home'
	}
);


export const createRootNavigator = ( isLoggedIn = false, guestRoute = null ) => {

	console.log( ':: navigator :: createRootNavigator :: isLoggedIn ? ' + isLoggedIn );
	console.log( ':: navigator :: createRootNavigator :: guestRoute: ' + guestRoute );

	if( isLoggedIn ){
		console.log( '=========================== User logged in ===========================' );
	}

	return createSwitchNavigator(
		{
			Guest: {
				screen: createGuestNavigator( guestRoute )
			},
			Member: {
				screen: MemberNavigator
			}
		},
		{
			headerMode: 'none',
			initialRouteName: isLoggedIn ? 'Member' : 'Guest'
		}
	)

};

class Nav extends Component{

	constructor( props, context ){
		super( props, context);
	}

	async componentDidMount(){

		console.log( 'Did mount' );

		// Load fonts
		await Font.loadAsync({
			'Luna': require( '../assets/fonts/Luna.ttf' ),
			'Yanone': require( '../assets/fonts/YanoneKaffeesatz-Regular.otf' ),
			'Yanone-Light': require( '../assets/fonts/YanoneKaffeesatz-Light.otf' ),
			'Yanone-Extra-Light': require( '../assets/fonts/YanoneKaffeesatz-ExtraLight.ttf')
		});

		this.props.actions.appLoad.fontsLoaded();
		await this.props.actions.auth.apiTokenCheck();
		
	}

	render() {

		console.log( 'Navigator state: ' + JSON.stringify( this.props, null, 4 ) );

		let NavAppContainer = createAppContainer( createRootNavigator( this.props.auth.isLoggedIn, this.props.auth.guestRoute ) );
		let isAppReady = (
			this.props.appLoaded.fonts
			&& this.props.auth.tokenChecked
			&& this.props.auth.userChecked
		);

		return (
			<View style={{width:'100%', height:'100%'}}>
				{ isAppReady ? (
					<NavAppContainer />
				) : (
					<View style={{flex:1}}>
						<Image source={require('../assets/img/brand/splash.png')} />
					</View>
				)}
			</View>
		)
	}
}

function mapStateToProps( state, ownProps ){
	return{
		appLoaded: state.appLoaded,
		auth: state.auth
	}
}

function mapDispatchToProps( dispatch ){
	return{
		actions: {
			appLoad: bindActionCreators( appLoadActions, dispatch ),
			auth: bindActionCreators( authActions, dispatch )
		}
	}
}

export default connect( mapStateToProps, mapDispatchToProps )(Nav);
```

**Comment by jcush** [comment]
I decided to check out the last git commit before the update from GitLab so I could go through step by step and report the process here (with 'foo' etc. used in place of sensitive info) in case it helps identify the issue. So I cleaned out my entire directory and re-cloned the repo.

Before the rest of the steps, here are my `package.json` and `package-lock.json` files (hereafter "package files"):
[v33-package.zip](https://github.com/expo/expo/files/4424311/v33-package.zip)

`$ npm install`

So, initial reason for updating before all these problems occurred when opening the project on the iOS app, I receive a message saying the following:

_The experience you requested uses Expo SDK v(null), but this copy of Expo Client requires at least v34.0.0._

So, next command:

`$ expo update 34.0.0`

The result:

✅ The following packages were updated:
expo-font, expo-image-manipulator, expo-permissions, expo-secure-store, react-native, react, babel-preset-expo, expo

🚨 The following packages were not updated. You should check the READMEs for those repositories to determine what version is compatible with your new set of packages:
bcrypt, braces, react-native-customisable-switch, react-native-keyboard-aware-scroll-view, react-native-responsive-screen, react-native-swiper, react-navigation, react-redux, react-router, react-router-native, react-router-navigation, redux, redux-form, redux-thunk, @react-native-community/cli, eslint, eslint-plugin-react, micromatch, react-devtools

Updated package files:
[v34-package.zip](https://github.com/expo/expo/files/4424342/v34-package.zip)

Next, I stop the Expo server with control+c and start it again with:

`$ expo start -c`

Now the client app tries to build the JS bundle, but hits this error:
_Unable to resolve "expo-image-picker" from "src/components/foo.js"_

So I run:

`$ expo install expo-image-picker`

Updated package files:
[v34-package-w:image-picker.zip](https://github.com/expo/expo/files/4424358/v34-package-w.image-picker.zip)

Bounce the Expo server again (on reloading the JS it still shows the same error, otherwise) by stopping it then running `$ expo start -c`

Client app builds again, this time the error is:
_Unable to resolve "react-native-gesture-handler" from "node_modules/@react-navigation/native/src/Scrollables.js"_

So I run:

`$ expo install react-native-gesture-handler`

Updated package files:
[v34-package-w:gesture-handler.zip](https://github.com/expo/expo/files/4424367/v34-package-w.gesture-handler.zip)

...bounce the server again (including `$ expo start -c`)...

And the font issue occurs! The exact text is:
_fontFamily "Yanone" is not a system font and has not been loaded through Font.loadAsync._

_- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system._

_- If this is a custom font, be sure to load it with Font.loadAsync._

The same error appears for two more fonts too. Having seen, though, in other GitHub issues that people have been asked to upgrade Expo to 34.0.3, I run:

`$ npm install expo@^34.0.0`

This brings `expo` up to `34.0.4`, (`expo-font`, at this point, is at `~6.0.1`) and this seemed to do it! But the weird thing is that I did this before and it failed. I simply repeated my steps for the purpose of this comment and it succeeded! 

So there's something weird going on, but I can't quite put my finger on what.... if I've wasted any of your time then I'm sorry, but I also hope this helps someone.

**Comment by brentvatne** [comment]
hi there! this seems to have been caused by npm not deduping dependencies as we expected it to. new versions of expo-cli will clear your lockfile and node_modules when you upgrade and that resolves this problem: https://github.com/expo/expo-cli/commit/35b250c9961b42b7324e19be7a8271363c717f3a

thanks for the info!

**Comment by jcush** [comment]
@brentvatne No problem, just glad I could help and that my report wasn’t a waste of time after all!
