### ISSUE TITLE
iOS SDK37 - Developer menu doesn't appear using two-finger force touch 

### ISSUE THREAD

**Issue by sketchpad** [expo/expo#7629]
### Environment

iOS client 2.15.2.108043 on a real iPhone device (iOS 13.4).

### Steps to Reproduce

Using a real device, open any project in the Expo client.  Try to open the developer menu using force touch / pressing with two fingers.

### Expected Behavior

The developer menu should open.

### Actual Behavior

Nothing.  Developer menu does not open.

### Reproducible Demo

This happens with any app in the Expo client.

**Comment by cruzach** [comment]
We deprecated the two-finger touch feature from the Expo client (However, on iOS you can turn on AssistiveTouch button in Settings app > Accessibility > Touch > AssistiveTouch and set up shake gesture on single tap action). We'd like to implement a key command you can use through `expo-cli` after running `expo start` that will bring up the Dev Menu for you

**Comment by BettyJJ** [comment]
I really like the two-finger touch feature. It's much easier than shake for me. It's also easier than AssistiveTouch (for which I have assigned other function) and command line through expo-cli. I hope you can bring it back! Thank you very much.

**Comment by brentvatne** [comment]
it seems it was a mistake for us to remove this, we will look into adding it back

**Comment by amirhs712** [comment]
> it seems it was a mistake for us to remove this, we will look into adding it back

Yes plz, I've been shaking my android device for 10 seconds now, it won't just show up. (Using the latest expo-client supporting SDK 39).

**Comment by cruzach** [comment]
hi @amirhs712 , we already added it back last SDK 😃 it's a 3-finger touch now, you can enable it under `options` in your Profile screen
