### ISSUE TITLE
expo-firebase-analytics Getting TypeError: Cannot read property 'logEvent' of undefined

### ISSUE THREAD

**Issue by AurangsEmpire** [expo/expo#7632]
I have tried Analytics.logEvent but getting this error. Help anyone.
`import * as Analytics from 'expo-firebase-analytics'`

` await Analytics.logEvent('opens app', {
                name: 'MobileNumber',
                screen: 'Enter Mobile Number screen',
                purpose: 'Opens app',
            });`
![Screenshot 2020-04-03 at 6 34 41 PM](https://user-images.githubusercontent.com/47293825/78363720-e34c4180-75d9-11ea-96f3-a1a17c9a2013.png)

Getting the error on ComponentDidMount(). Check screenshot.

**Comment by IjzerenHein** [comment]
Hi! Could you verify that you are running the latest (SDK 37) Expo Client and that your sdk-version in app.json is also set to SDK 37 ?

**Comment by IjzerenHein** [comment]
Are you still getting this error?

**Comment by mblodorn** [comment]
> Hi! Could you verify that you are running the latest (SDK 37) Expo Client and that your sdk-version in app.json is also set to SDK 37 ?

This solved the problem for me! I forgot to update the sdk.

**Comment by IjzerenHein** [comment]
Great!
