### ISSUE TITLE
[Expo 37] Upgrade from Expo 36 - TypeError: '_core.ThemeColors.light'

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo#7636]
## 🐛 Bug Report

Hey guys, 
The exact error is: `TypeError: undefined is not an object evaluating '_core.ThemeColors.light'` in `StackViewCard.js` which is React-navigation.

Thanks for all you do! We're trying to follow the update from 36 to 37. Here's what I did:
- upgraded CLI
- ran expo upgrade
- checked breaking changes for things that could effect us (non seemed to)
- ran `watchman watch-del-all && rm -rf node_modules/ package-lock.json && npm cache verify && npm i && expo start -c`
- Running on linux - so `$TMPDIR` doesn't exist, we don't know where the alternative is
- I'm thinking it could have something to do with the new expo doing something with react-navigation?
  - as there is [this issue in React-navigation](https://github.com/react-navigation/react-navigation/issues/7314) that is similar to this error.

### Environment

  Expo CLI 3.17.11 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.0 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.13.6 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^3.11.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.17.11

Target iOS simulator

### Steps to Reproduce

The same steps as above, mixed with the below 

### Expected Behavior

Either it would just work, or if our version of react-navigation is incompatible - then it would be listed as a breaking change or part of the upgrade path.

### Actual Behavior

When attempting to start up the app I get a runtime error showing: 

`TypeError: undefined is not an object evaluating '_core.ThemeColors.light'` from StackViewCard.js which is a react-navigation Component.

```
"dependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/node": "^7.5.5",
    "@babel/preset-typescript": "^7.3.3",
    "@react-native-community/netinfo": "4.6.0",
    "@react-navigation/core": "^5.1.5",
    "@react-navigation/native": "^5.0.6",
    "@reduxjs/toolkit": "^1.2.5",
    "@xstate/react": "^0.8.1",
    "amqplib": "0.5.3",
    "babel-preset-expo": "^5.1.1",
    "binlookup": "^2.0.1",
    "color": "^3.0.0",
    "decimal.js": "^10.0.1",
    "expo": "^36.0.0",
    "expo-analytics": "^1.0.9",
    "expo-application": "~2.0.0",
    "expo-av": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-file-system": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-keep-awake": "~8.0.0",
    "expo-location": "~8.0.0",
    "expo-media-library": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-secure-store": "~8.0.0",
    "geolib": "^3.1.0",
    "lodash": "^4.17.15",
    "mgt-shared": "file:../shared",
    "moment": "^2.22.2",
    "prop-types": "^15.6.1",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-card-flip": "^1.0.4",
    "react-native-fs": "^2.16.4",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-maps": "0.26.1",
    "react-native-masked-text": "^1.7.2",
    "react-native-phone-call": "^1.0.7",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-simple-gauge": "^0.1.10",
    "react-native-snackbar-component": "^1.1.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^3.11.1",
    "react-navigation-hooks": "^1.1.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "simple-crypto-js": "^2.2.0",
    "socket.io": "^2.1.1",
    "socket.io-client": "2.1.1",
    "socketio-jwt-auth": "0.0.6",
    "stripe-client": "^1.1.5",
    "styled-components": "^5.0.1",
    "ts-node": "^8.3.0",
    "typescript": "^3.5.3",
    "xstate": "^4.6.7"
  },
```

The changed packages were:

```
-    "@react-native-community/netinfo": "4.6.0",
+    "@react-native-community/netinfo": "5.5.0",
-    "babel-preset-expo": "^5.1.1",
+    "babel-preset-expo": "^8.1.0",
-    "expo": "^36.0.0",
+    "expo": "^37.0.0",
-    "expo-application": "~2.0.0",
-    "expo-av": "~8.0.0",
-    "expo-constants": "~8.0.0",
-    "expo-file-system": "~8.0.0",
-    "expo-font": "~8.0.0",
-    "expo-keep-awake": "~8.0.0",
-    "expo-location": "~8.0.0",
-    "expo-media-library": "~8.0.0",
-    "expo-permissions": "~8.0.0",
-    "expo-secure-store": "~8.0.0",
+    "expo-application": "~2.1.0",
+    "expo-av": "~8.1.0",
+    "expo-constants": "~9.0.0",
+    "expo-file-system": "~8.1.0",
+    "expo-font": "~8.1.0",
+    "expo-keep-awake": "~8.1.0",
+    "expo-location": "~8.1.0",
+    "expo-media-library": "~8.1.0",
+    "expo-permissions": "~8.1.0",
+    "expo-secure-store": "~8.1.0",

-    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
+    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
-    "react-native-gesture-handler": "~1.5.0",
+    "react-native-gesture-handler": "~1.6.0",
-    "react-native-screens": "2.0.0-alpha.12",
+    "react-native-screens": "~2.2.0",
-    "typescript": "^3.5.3",
+    "typescript": "^3.8.3",
```

**Comment by brentvatne** [comment]
this is unrelated to expo, this is an error message coming from react-navigation. clear your node_modules and make sure the react-navigation package versions are correct

**Comment by jonathanstiansen** [comment]
@brentvatne thanks for the quick response - I did clear that as listed, but what is the *correct version** of react-navigation? How do I find this, it's not in the upgrade guide. Not in breaking changes.

**Comment by brentvatne** [comment]
there isn't a correct version necessarily - a wide range will work. the error you're seeing happens when react-navigation package versions are out of sync. i would suggest updating the latest v4 version because it should be a relatively easy update and it's still supported, while v3 is not. check out https://reactnavigation.org/blog/2019/09/16/react-navigation-4.0 for information on how to update and the v4 docs at https://reactnavigation.org/docs/4.x/getting-started.
