### ISSUE TITLE
Network Error with Axios

### ISSUE THREAD

**Issue by masihfathi** [expo/expo#764]
hi,
i used expo v19 and every thing work correctly but when i upgrade my app to v 21 the app can not connect to api, api has ssl protocol and is accessible (https://abifiltration.ir/api/meetups) but in expo i got Network Error, i used axios to connect to api

**Comment by ccheever** [comment]
Can you post your code? It's hard to debug without that.

**Comment by masihfathi** [comment]
in the api.js file i have:
````
import axios from 'axios';
axios.defaults.baseURL = 'https://abifiltration.ir/api';
const FAKEGROUPID = '5998221e0a6f83293c1d0922';
class MeetApi {
    constructor() {
        this.groupId = FAKEGROUPID;
        this.path = `/groups/${this.groupId}/meetups`;
    }
    async fetchGroupMeetups() {
        try {
            const {data} = await axios.get(this.path);
            return data.meetups;
        }catch (e){
            console.error(e.message);
        }
    }
    async createGroupMeetup(args){
        try{
            const res = await axios.post(`${this.path}/new`,{...args});
            return res;
        }catch (e){
            console.log(e.message);
        }
    }
}
export default MeetApi
```

**Comment by alapini** [comment]
Having the same problem after migrating to SDK 21 with both axios and fetch. ```Network Error``` and the response is ```undefined```.

**Comment by ide** [comment]
If you use the `fetch` API (docs: https://facebook.github.io/react-native/docs/network.html) are you able to contact your endpoint?

**Comment by ide** [comment]
@masihfathi I made a Snack here that shows successfully connecting to your server: https://snack.expo.io/BJmIXVEp-. I was able to fetch the API response with both iOS and Android. If this isn't working for you, I suspect there may be an issue with your phone (e.g. protocols your phone OS supports) or network connection. I'm not sure about Axios, that's a third-party library.

**Comment by masihfathi** [comment]
thanks to create snack for me, it is really weird for me why it is not working with my code.

**Comment by JulianKingman** [comment]
@masihfathi just curious, what ended up being the problem? I'm having an issue with fetch and am researching potentially similar issues.

**Comment by masihfathi** [comment]
@julianKingman, it is solved by updating expo again and clearing expo cache on my laptop one or two week after that as i remember.

**Comment by ikosar** [comment]
Make Sure **"http://"** is in Your URL Address ,
