### ISSUE TITLE
Segment not automatically tracking bugs with Sentry

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo#7645]
### Environment

  Expo CLI 3.16.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.16.1

### Steps to Reproduce

1. Attach Segment destination to Sentry
2. Segment.identify(id)`
3. `throw new Error('test error')`

### Expected Behavior

Bug would be tracked through Segment.

### Actual Behavior

Bug isn't tracked automatically.

I know there's a separate doc for it at https://docs.expo.io/versions/latest/guides/using-sentry/ but the whole point of Segment is to unify tracking. They have support for Sentry, so why do we need to use a separate library and repeat logic like identifying users?

**Comment by cruzach** [comment]
Hey @garrett-gottlieb , thanks for pointing this one out! So this works for me, but the steps to set it up aren't so clear (I'll update the Sentry docs with this, but for now I'll list out the steps below):

- Create a "Javascript Website" source in your segment dashboard (the React Native source doesn't support Sentry)
- Note the key that is displayed to add segment to your site, it should look a random string of characters:
```
analytics.load("A1B2C3D4E5"); // <- this is your write key
```
- Search for “Sentry” within the Destinations Catalog and confirm the Source you’d like to connect to (made in previous step)
- configure your Sentry destination's Public DSN to your Sentry project's DSN, found in Sentry Dashboard > Project Settings > DSN
- In your app, initialize both segment and sentry:
```
Sentry.init({
  dsn:
    "YOUR-DSN-HERE,
  enableInExpoDevelopment: true,
  debug: true,
});

Segment.initialize({
  androidWriteKey: "YOUR-WRITE-KEY",
  iosWriteKey: "YOUR-WRITE-KEY",
});
```
