### ISSUE TITLE
Can't close some intertitial ads on IOS

### ISSUE THREAD

**Issue by arnaud-cortisse** [expo/expo#7647]
### Environment

Expo CLI 3.17.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    npmPackages:
      expo: ^37.0.0 => 37.0.3
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

Target: IOS & Android

Happens on: IOS 13.4, Ipad Air (3th gen) and iPhone 6S, on published app (never tried in standalone app).

### Steps to Reproduce

This one is going to be difficult to reproduce because it only happens with a specific ad. 

1. Call AdMobInterstitial.setAdUnitID() with your own AdUnitID. 
2. Call AdMobInterstitial.requestAdAsync({ servePersonalizedAds: true }).
3. Call AdMobInterstitial.showAdAsync()

### Expected Behavior

I can close the ad via a "X" button. 

### Actual Behavior

The "X" button can't be clicked on some ads. 

![IMG_0001](https://user-images.githubusercontent.com/28689103/78424190-f90a4700-766b-11ea-88ed-bf0dab6030ea.PNG)

As you can see, it looks like the "X" button in on the top-right corner but only partially. Also, you can see there is a empty black space on the bottom (as if the ad was too high). 

### Reproducible Demo

Can't provide one because of the nature of the bug (targetted ad).

**Comment by arnaud-cortisse** [comment]
Hey @cruzach, thanks for your reply! 
I've not tried in a bare RN project yet. I'll keep you posted on that.

**Comment by cruzach** [comment]
Tested this on SDK 41 using [this example](https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/AdMobScreen.tsx) and couldn't repro, so Im going to close this for inactivity
