### ISSUE TITLE
Inconsistency with Constants.linkingUri with Standalone apps

### ISSUE THREAD

**Issue by Dygerati** [expo/expo#765]
I had some issues crop up when switching to a stand-alone version of my app that I eventually traced back to some inconsistencies in the linking URI provided by Expo. 

In dev it looks something like this:
`exp://192.168.0.8:19000/+`

After building the APK it looks like this:
`appslug://`

This issue here for me was the omission of the "+" on the end for a standalone app which I was expecting and using for parsing. I suppose that's not expected behavior? 

Also I should mention that I'm using the latest expo (21)

**Comment by ccheever** [comment]
Hi-

Thanks for reporting this.

In the short term, you can probably work around by just replacing the linking constant with '' at the beginning of a string instead of searching for '+', but we need to make this consistent with the docs (either by fixing it or changing the docs).

**Comment by Dygerati** [comment]
Yup, more-or-less what I'm doing now, but thought it might be something you guys would want to know about.

**Comment by sourabh-khera** [comment]
@Dygerati @Raveler my addEventLIistener method is not working for android, sometimes it executes and sometimes not but for ios everything is working fine..

**Comment by gabrielgilini** [comment]
+1

Here's what I'm doing to circumvent it btw: `Constants.linkingUri.replace(/([^+]+)\+?$/, '$1+')`

**Comment by danikane** [comment]
+1 
Yeah, when app is opened without passing data the linkingUri does not have the +

```
With params:
url: exp://ry-rzg.danikane.my-new-project.exp.direct/+message=Hello
Constants.linkingUri: exp://ry-rzg.danikane.my-new-project.exp.direct/+

Without:
url: exp://ry-rzg.danikane.my-new-project.exp.direct
Constants.linkingUri: exp://ry-rzg.danikane.my-new-project.exp.direct/+
```
I also can't seem to register the 'url' event listener - in componentDidMount or manually thru some item's onPress... It just does not fire... :(

**Comment by exvance** [comment]
My url event listener also doesn't fire. :-(

**Comment by fweffort** [comment]
Do we have any update on this?
This is sort of crucial for a lot of apps

**Comment by DarkSector** [comment]
+1

**Comment by rafaelmotta** [comment]
Yes, is there any planning to fix this issue? or maybe you could provide more details about the implementation for us guys take a look and maybe try to fix.

**Comment by anp** [comment]
@rafaelmotta we do plan to fix this issue, it's just going to be a bunch of work to make sure it doesn't break users' apps who have implemented a workaround, and also to ensure that all of the implementation of the Linking API behaves correctly. In the meantime there are a few workaround suggested in this thread, and we'll update when we have a solution available.

**Comment by frankcalise** [comment]
Should we use this work around if seeing this issue with Android + AuthSession? The token info is received correctly but the window sits at Return to app => and clicking the link (to deep link) just leaves it in the same spot.

Or would I need to switch from using AuthSession.startAsync and use the web browser call?

**Comment by DarkSector** [comment]
Okay @gabrielgilini's workaround does work. 

```
componentDidMount() {
        console.log("LoginScreen did mount");
        Linking.getInitialURL()
            .then(url => {
                console.log("Getting initial URL", url);
            })
            .catch(err => {
                console.warn('Initial URL Error', err)
            });

        Linking.addEventListener('url', e => {
            console.log("Listener invoked");
            WebBrowser.dismissBrowser();
            this._handleDeeplink(e.url);
        });
    }
```

```
_handleDeeplink = (url) => {
        console.log("handling deeplink");
        console.log("URL is ", url);

        console.log("Constants.linkingUri is ", Constants.linkingUri);
        const linkingUri = Constants.linkingUri.replace(/([^+]+)\+?$/, '$1+');
        console.log("Updated linkingUri is ", linkingUri);

        console.log("Parsing queryString");
        const queryString = url.replace(linkingUri, '');
        console.log("Parsed queryString is ", queryString);

        if (queryString) {
            let data = qs.parse(queryString);
            console.log("Data is ", data);
        }
    };
```

Also, according to [this](https://forums.expo.io/t/linking-addeventlistener-url-never-fires-in-android/7442/2) Expo 26 is going to have a fix for this issue. *fingers crossed*

**Comment by frankcalise** [comment]
@DarkSector You are using AuthSession.startAsync with the value of getInitialUrl from Linking instead of getRedirectUrl fromAuthSession here to get this flow to work?

**Comment by DarkSector** [comment]
@frankcalise I am not using AuthSession at all. I am simply using Linking directly. The user logs into a web app once the browser opens and clicks on a button "Authorize App" on the webbrowser. The browser then links to the app `appname://` and I pass on the username, token and all other relevant info in the querystring. Does that answer your question?

**Comment by frankcalise** [comment]
@DarkSector Hm ok. I mean I'm using AuthSesssion which opens up a web browser instance and it hangs at the return to app part. I see the url is my scheme:// it is trying to reach, but it just sits at the web browser page (and clicking return to app link does nothing). I imagine it is the same problem though, because it works in debugging with the XDE.

I could switch from AuthSession.startAsync({...}) to WebBrowser.openAuthSessionAsync() and try to initiate flow that way, then sub to the Linking events.

Although I wonder if I could keep AuthSession in place and just subscribe to the Linking events and see if it connects up. I'll try both.

**Comment by terribleben** [comment]
Hi, just following up here--

- I believe we hotfixed SDK 26 to fix the issue of the missing `+` in Android Constants.linkingUri.
- For SDK 27 and onward, we [refactored this API](https://docs.expo.io/versions/latest/workflow/linking) to be more predictable and consistent. Use `Linking.makeUrl()` and `Linking.parse()` to format and parse deep links in your code.

I'm going to close this because I believe those changes resolve this issue. Let me know (or open a new issue) if you think there are still problems.

**Comment by surndraraj3** [comment]
Constants.linkingUri
let base_scanner_ip = Constants.linkingUri;
base_scanner_ip = base_scanner_ip.replace(/[a-zA-Z/]/g, "");
base_scanner_ip = base_scanner_ip.split(":");
export const DeviceURL = base_scanner_ip[1];

Expo linking Uri is working on development mode for android. When i build application it's turning as empty. Can anyone help me on this
