### ISSUE TITLE
SDK37 Android Expo Client: Couldn't get GCM token on device

### ISSUE THREAD

**Issue by yortyrh** [expo/expo#7653]
## 🐛 Bug Report
While running the guide from https://docs.expo.io/versions/v37.0.0/guides/push-notifications,
I'm getting the error `Couldn't get GCM token on device.`

Please run the following project in local expo client to reproduce it
https://github.com/yortyrh/pushnandroidissue

### Environment
```
  Expo CLI 3.17.15 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.0.0 - D:\Soft\nodejs\node.EXE
      Yarn: 1.19.1 - D:\Soft\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\Soft\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.4
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

This happens in Android using the expo client

### Steps to Reproduce
1) Execute the following steps in windows CMD.
```
git clone git@github.com:yortyrh/pushnandroidissue.git
cd pushnandroidissue
yarn install
yarn start
```
2) Once the application starts, it shows the alert: "Error: Couldn't get GCM token on device"

### Expected Behavior
It should show **Token**: <the push notification token> and no alert 

### Actual Behavior
It shows **Token**: <empty> and the Alert: "Error: Couldn't get GCM token on device"

<img src="https://raw.githubusercontent.com/yortyrh/pushnandroidissue/master/assets/push-notifications-token-issue.png" width="300">

### Reproducible Demo
https://github.com/yortyrh/pushnandroidissue

**Comment by firmanjml** [comment]
Hello, I encountered the same problem and tried following every steps mentioned in most of the issues and SO.

I tried to log in to expo-cli and the app and have a similar issue.
I also tried adding Firebase Installation to Google Console API Restriction and FCM configurations in the app and nothing works. Still getting "Couldn't get GCM token on device." 


Expo CLI version: 3.17.15
Expo Client: 2.15.0
App Expo: 37.0.3
RN Version: SDK 37

**Comment by sinisavukovic** [comment]
I'm having this issue as well and it crashes the app. 
Device I'm using is Android Xiaomi Note 7

**Comment by sjchmiela** [comment]
Hey, sorry for making you run into the issue.

Could you please try this:

- close Expo Client
- open Expo Client
- open [this Snack](https://snack.expo.io/@sjchmiela/sdk36-experience) (there's nothing special about this Snack apart from the fact that it is not an SDK37 experience)
- go back to Expo Client
- open your SDK37 app/the app you're testing this issue on

What does happen then? Opening any experience that is not on SDK37 should help mitigate this bug.

**Comment by sjchmiela** [comment]
**Note:** my expectation is that after opening an SDK36 experience and going back to testing for this issue the `getExpoPushTokenAsync` will never resolve (if you don't provide a custom Firebase project configuration).

**Comment by bill-pairaktaridis** [comment]
Yup, same issue here. Upgraded to SDK 37 this morning and now getting "Couldn't get GCM token on device". Double checked my API key, which was not originally restricted, and even restricted it to just the two services mentioned in the docs.

**Comment by AndrewSouthpaw** [comment]
Same issue as well. I upgraded to SDK 37 and suddenly we're getting these errors in production on our monitoring. 100% Android.

**Comment by sjchmiela** [comment]
A short update:

- we have fixed the issue and a new version of Expo Client app is building as I write this message — when it goes through the short QA we will publish it to expo.io/tools and to Google Play Store
- this issue **should not** affect production apps — if it does, please file a new issue (but before you do, please ensure that you have followed [this guide](https://docs.expo.io/versions/v37.0.0/guides/using-fcm/), talking about how to configure FCM for your standalone app).

**Comment by alex-fournier** [comment]
Same issue with my production app on Android. Everything seems to be configured correctly : Firebase, key restriction, `android.googleServicesFile` in `app.json` and key is showing when I run `expo push:android:show`,

**Comment by sjchmiela** [comment]
To anyone experiencing this issue on an Expo client — could you please install the Expo client from https://d1ahtucjixef4r.cloudfront.net/Exponent-2.15.1.apk and see if the issue remains? (It doesn't on my computer, but you know…)

**Comment by yortyrh** [comment]
> To anyone experiencing this issue on an Expo client — could you please install the Expo client from https://d1ahtucjixef4r.cloudfront.net/Exponent-2.15.1.apk and see if the issue remains? (It doesn't on my computer, but you know…)

Not happening with this APK.

**Comment by joshg2k** [comment]
+1 this. Thank you for working this so quickly @sjchmiela

**Comment by jlpro** [comment]
Yeah, it worked fine for me with that apk, thanks @sjchmiela!

**Comment by sjchmiela** [comment]
The 2.15.1 update, fixing this particular issue, is currently propagating through Google Play Store. You can also install it using `expo client:install:android`. 🙂

**Comment by RoninSTi** [comment]
@sjchmiela 

I'm having this issue on a production stand alone app (built with the latest cli).  The issue is resolved while testing the app on the latest version of the client.

Any suggestions for fixing on a stand alone app?

**Comment by smuxx** [comment]
same problems here on production standalone app even after rebuilding with lates expo-cli 3.17.18... I was hoping that the problem would be resolved after rebuilding

**Comment by sjchmiela** [comment]
Hey, standalone apps problem is a separate issue we’re tracking in https://github.com/expo/expo/issues/7727. 🙂

**Comment by bill-pairaktaridis** [comment]
Confirmed that it works with the newest version of the client. Thanks for the hard work!

**Comment by smuxx** [comment]
@sjchmiela thanks... I have found the 7727 issue

**Comment by RoninSTi** [comment]
@sjchmiela Thank you so much for your help and support.  Your fix in #7727 fixed our issue.  A+!!

**Comment by Vikka0157** [comment]
> Hey, standalone apps problem is a separate issue we’re tracking in #7727.

What should I do I m getting the same issue it's not return the token

**Comment by hkeyland** [comment]
> > To anyone experiencing this issue on an Expo client — could you please install the Expo client from https://d1ahtucjixef4r.cloudfront.net/Exponent-2.15.1.apk and see if the issue remains? (It doesn't on my computer, but you know…)
> 
> Not happening with this APK, Thanks a lot.
> Is this already applied to #7682 ?

Yeah if you use the Android client https://d1ahtucjixef4r.cloudfront.net/Exponent-2.15.1.apk works very well on develop mode in your Android device.

When I build the app, this working but i need to add this in app.json

- android.package
- android.googleServicesFile
- android.config.googleSignIn.apiKey From(/google-services.json -> api_key.current_key)

`"android": {
      "package": "TheNAmeOf.APPintoFirebase.com",
      "googleServicesFile": "./google-services.json",
      "config": {
        "googleSignIn": {
          "apiKey": "XYZ......"
        },
        "googleMaps": {
          "apiKey": "XYZ......"
        }
      }
    }`

I dont know why need to add googleSignIn  but worked for me.

**Comment by diegolaciar** [comment]
+1  
same issue as https://github.com/expo/expo/issues/7785#issuecomment-611868631

**Comment by dyangua** [comment]
> I'm having this issue as well and it crashes the app.
> Device I'm using is Android Xiaomi Note 7



> Hello, I encountered the same problem and tried following every steps mentioned in most of the issues and SO.
> 
> I tried to log in to expo-cli and the app and have a similar issue.
> I also tried adding Firebase Installation to Google Console API Restriction and adding FCM configurations in the app and nothing works. Still getting "Couldn't get GCM token on device."
> 
> Expo CLI version: 3.17.15
> Expo Client: 2.15.0
> App Expo: 37.0.3
> RN Version: SDK 37
> Platform: Android
> 
> #7606

The same issue, i use my Xiaomi note 8
