### ISSUE TITLE
[expo-task-manager] TaskManagerTaskExecutor can't use an async func?

### ISSUE THREAD

**Issue by maaaashin324** [expo/expo#7657]
# Context

Want to use async function inside the task. Then I'm passing an async function into `defineTask` as the second parameter, but now `eslint` tells me the return value type of `TaskManagerTaskExecutor` is `void`, and not `Promise<void>`.

# Question

I can't use any async function in `TaskManagerTaskExecutor`? If we can, the type of `TaskManagerTaskExecutor` should be `void | Promise<void>`.

**Comment by brentvatne** [comment]
hi! please post questions to https://forums.expo.io/

issues are for bug reports
