### ISSUE TITLE
How can i get base64 form ios using expo-image-picker ?

### ISSUE THREAD

**Issue by eugene1215** [expo/expo#7662]
Expo SDK: 36
Expo CLI: 3.17.11

the work flow: user selects image from gallery, then sending it as base64 format to firebase's db. I already set base64:true in ImagePicker.MediaTypeOptions.

### **

- ### Why  it always return local path in IOS platform?

**

 **IOS**:
file:///var/mobile/Containers/Data/Application/15145EC3-1229-47E4-9E80-142ED8C307A3/Library/Caches/ExponentExperienceData/%2540anonymous%252Ffyp2-7c65f06c-5d04-416e-8d94-60916127ac5f/ImagePicker/4C86FF0A-C401-4457-A587-1EBD13854484.png

But in **WEB** platform, it can transform as base64 then insert db.

![image](https://user-images.githubusercontent.com/54785627/78468663-99d03380-774c-11ea-8108-3a07e140ce40.png)

**Comment by brentvatne** [comment]
hi @eugene1215! you need to take the `base64` property off of the result object rather than the `uri`. see the type of the result object: https://github.com/expo/expo/blob/e599b36571d847cfb58b6753b7452661f7ad5870/packages/expo-image-picker/src/ImagePicker.types.ts#L21-L30

**Comment by eugene1215** [comment]
@brentvatne Thank you so much. I got it
