### ISSUE TITLE
[Android] "androidNavigationBar" sticky-immersive behavior breaks down after switching between different running apps

### ISSUE THREAD

**Issue by Porisey** [expo/expo#7663]
### Environment
```
Expo CLI 3.17.11 environment info:
  System:
    OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    npmPackages:
      expo: ^37.0.0 => 37.0.4 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.3.7
```
Target - android device.

### Steps to Reproduce

Start the app with expo cli. Run it on the android device. Navigation bar working as expected, it initially hidden and appears on user swipe up, then immerse again. Tap on the home button, don't close the app explicitly. After return to the app navigation bar changes it behavior to default.

### Expected Behavior

Navigation bar should persist its behavior

### Actual Behavior

Navigation bar changes its behavior

**Comment by cruzach** [comment]
Can you provide the `androidNavigationBar` object from your app.json config? Also, please let me know if this issue persists in an apk

**Comment by pavelkukov** [comment]
I'm experiencing the same issue. When an AdMob add opens, it shows the navigation bar. When the add is closed the navbar is not hiding again. I've tried with both "immersive" and "sticky-immersive". Both are behaving the same way. In my app.json I have `"androidNavigationBar": {
      "visible": "sticky-immersive",
      "backgroundColor": "#fd9900"
    }`. I've tested this only in expo client. https://streamable.com/vwxe40

**Comment by BradonZhang** [comment]
I am having the same issue when going to the home screen or switching between apps. As others have described, sticky-immersive works initially, but the app goes back to the default behavior for the navigation bar when I leave. Same thing happens with "immersive".

This happens in both development and production mode.

```json
"androidNavigationBar": {
    "visible": "sticky-immersive"
}
```

**Comment by Porisey** [comment]
> Can you provide the `androidNavigationBar` object from your app.json config? Also, please let me know if this issue persists in an apk

Here is config
```
"androidNavigationBar": {
    "visible": "sticky-immersive"
}
```

**Comment by pavelkukov** [comment]
I've tested with apk. It is the same. The immersive mode doesn't work.

**Comment by cruzach** [comment]
thank you for the reports everyone! Working on a fix now 👍

**Comment by pavelkukov** [comment]
Thanks for fixing this, @cruzach ! I'm wondering how and when this will be released? Will it be available as a fix in 37.0.xx or we will have to wait for a major release?

**Comment by cruzach** [comment]
We'll patch this to SDK 37, as well

**Comment by joseotaviosantos** [comment]
> We'll patch this to SDK 37, as well

How do I update the expo with this fix?

**Comment by pavelkukov** [comment]
Question from a planning perspective. 

Does someone know when a patch release will be made for SDK 37?

**Comment by cruzach** [comment]
This has been patched to the SDK 37 builders

**Comment by pavelkukov** [comment]
Thanks! Does this mean the only thing necessary is a new build?
