### ISSUE TITLE
Expo IPA from expo.io/tools not working as expected on macOS Catalina

### ISSUE THREAD

**Issue by PiotrAleksander** [expo/expo#7670]
### Environment

Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.0.16 - /usr/local/bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.15.5

App's target systems are iOS and Android

### Steps to Reproduce

Following: https://blog.expo.io/testing-expo-apps-with-detox-and-react-native-testing-library-7fbdbb82ac87 on macOS Catalina I'm not able to run Exponent.app due to the IPA downloaded from expo.io/tools not being 64bit.

### Expected Behavior

I can normally install and run expo on my simulator.

### Actual Behavior

![image](https://user-images.githubusercontent.com/6314591/78506848-d156d400-777c-11ea-80e1-6904b6846311.png)

### Reproducible Demo

It's related to IPA, couldn't reproduce it in Snack

**Comment by brentvatne** [comment]
Does `expo client:install:ios` work on your machine?

**Comment by brentvatne** [comment]
Also, what are the steps you are taking to try to run the app that you are downloading?

**Comment by brentvatne** [comment]
```
╭─~/code/example
╰─$ curl https://dpq5q02fu5f55.cloudfront.net/Exponent-2.15.3.tar.gz -o Expo.tar.gz                                                                                                                                     
╭─~/code/example
╰─$ mkdir Expo.app && tar -xzf Expo.tar.gz -C Expo.app
╭─~/code/example
╰─$ xcrun simctl install booted Expo.app
```

this installs the client successfully.

<img width="698" alt="Screen Shot 2020-04-05 at 1 18 18 PM" src="https://user-images.githubusercontent.com/90494/78509026-ec572300-773f-11ea-8a52-4798a34dbf3c.png">

**Comment by brentvatne** [comment]
closing until you can provide more info to allow me to reproduce. as far as i can tell this is not an issue
