### ISSUE TITLE
getExpoPushTokenAsync hangs on Android device (Expo Client)

### ISSUE THREAD

**Issue by bonafidehan** [expo/expo#7673]
### Environment

  Expo CLI 3.17.15 environment info:
    System:
      OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/node/node-v12.14.1-linux-x64/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - ~/node/node-v12.14.1-linux-x64/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^36.0.0 => 36.0.1 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.3.2 => 4.3.2 
    npmGlobalPackages:
      expo-cli: 3.17.15

Target: Android on Expo Client

### Steps to Reproduce

On Android device, using Expo client, request a token using the reproducible code below.

### Expected Behavior

Token to be returned from `getExpoPushTokenAsync`

### Actual Behavior

- Execute below code on Android device, on Expo client (not standalone)
- Prints 'Getting token', then app hangs on `getExpoPushTokenAsync`, doesn't print 'Got token'
- No errors printed and finally clause is not executed

### Reproducible Demo
```
    import { Notifications } from 'expo'
    import * as Permissions from 'expo-permissions'
    import Constants from 'expo-constants';

    try {
      const p = await Permissions.getAsync(Permissions.NOTIFICATIONS)
      if (Constants.isDevice) {
        if (p.status === 'granted') {
          console.log('Getting token')
          const tok = await Notifications.getExpoPushTokenAsync()
          console.log('Got token')
        }
      }
    } catch (err) {
      console.log(err)
    } finally {
      console.log('Finally')
    }
```

Notifications enabled:
![Screenshot_20200405-161001](https://user-images.githubusercontent.com/536523/78512355-a2c70200-7758-11ea-9fef-3c5b25af2d8a.png)

**Comment by merikwesterveld** [comment]
Same here, expo-cli 3.17.16 and expo app client version 2.15.0. Also configured firebase.

**Comment by tanteemmie** [comment]
We also experience this issue. Running expo app client on android 8
Also configured firebase as per document
Also tried the fix that was mentioned in the issue: https://github.com/expo/expo/issues/7606

**Comment by merikwesterveld** [comment]
> 
> 
> We also experience this issue. Running expo app client on android 8
> Also configured firebase as per document
> Also tried the fix that was mentioned in the issue: #7606

Indeed, also tried the fix mentioned in #7606

**Comment by sjchmiela** [comment]
Hey all,

I'm sorry for making you experience this bug — there are in fact multiple issues tied together here.

When it comes to the _GCM token_ error message, could you please see if following https://github.com/expo/expo/issues/7653#issuecomment-609654153 resolves the problem?

When it comes to `getExpoPushTokenAsync` hanging, the current workaround that should help you mitigate this problem is described here — https://github.com/expo/expo/issues/7606#issuecomment-608506794.

Let me know whether any of these workarounds help you!

**Comment by merikwesterveld** [comment]
> 
> 
> Hey all,
> 
> I'm sorry for making you experience this bug — there are in fact multiple issues tied together here.
> 
> When it comes to the _GCM token_ error message, could you please see if following [#7653 (comment)](https://github.com/expo/expo/issues/7653#issuecomment-609654153) resolves the problem?
> 
> When it comes to `getExpoPushTokenAsync` hanging, the current workaround that should help you mitigate this problem is described here — [#7606 (comment)](https://github.com/expo/expo/issues/7606#issuecomment-608506794).
> 
> Let me know whether any of these workarounds help you!

I tried the #7653 (comment) and didn't get the error but it was hanging agound (what I had last friday). However, I did everything in the #7606 (comment) and it is still hanging unfortunatly.

**Comment by smuxx** [comment]
Hey all, 
we are having the exact same issue as of Friday when we updated to SDK 37... issue 7606 didn't resolve the problem neither

**Comment by tanteemmie** [comment]
Same here, I tried the new comment on 7606 and also no result

**Comment by sjchmiela** [comment]
Ok, so:

- yes, I hereby acknowledge that there is an issue with the currently published Expo client configuration — without a custom Firebase project it is not possible to fetch a Firebase token, thus, it is not possible to fetch an Expo token and the Promise is never resolved. I have put up a PR that should fix this.
- I believed there is a workaround that makes it possible to fetch the tokens with current client app — with your own, custom Firebase project — after more debugging I believe it no more. We'll need to update the client. 🙂

**Comment by sjchmiela** [comment]
Cross-posting from https://github.com/expo/expo/issues/7653#issuecomment-610931991:

> The 2.15.1 update, fixing this particular issue, is currently propagating through Google Play Store. You can also install it using `expo client:install:android`. 🙂

**Comment by smuxx** [comment]
@sjchmiela 
I'm having this issue on a production standalone app (built with the latest cli 3.17.18 today). FCM is enabled as everything was working on SDK 35 before updating to SDK 37...

**Comment by sjchmiela** [comment]
For the record, the standalone apps issue is being tracked in https://github.com/expo/expo/issues/7727.

**Comment by dichai1983** [comment]
This works: https://github.com/expo/expo/issues/7727#issuecomment-611544439

**Comment by dmbejar** [comment]
For standalone apps this issue have an easy solution!!! I had solved it just now, so let's go sharing.

That's it: just verify at Google Console the restrictions you have for the key you had at the google-services.json.file, and make sure you have that key ready for both Cloud Messaging and Firebase Installations API.

The more usual case for the error is that you have the Cloud Messaging selected but not the Firebase Installations API. That's due a change on the SDK, so it's probably you got this problem when you updated the SDK.

STEP BY STEP SOLUTION:

1) Go to your project file `./google-services.json`.
2) Get the key you have you have at that file. This is the key `{client: {api_key: current_key}}`. That's your api key, right? Copy it.
3) Go to [Google Cloud Platform](https://console.cloud.google.com/).
4) Make sure you have selected your project (upper left corner, just the dropdown at the right of the "Google Cloud Platform" logo).
5) Open the menu (upper left corner) and select `APIs & Services` -> `Credentials`.
6) You have some api keys just there. Fine. Look for the key you got at step 2.
7) Click on the pencil at the right side of that api key to edit it.
8) Take a look to the restrictions for that api key. Make sure you have this restrictions: `APPLICATION RESTRICTIONS: None`; `API RESTRICTIONS: Restrict key`. And just below `Restrict Key` you see you can select some APIs in a dropdown. Fine. Just select these: `Cloud Messaging` AND `Firebase Installations API`.
