### ISSUE TITLE
SDK 37: Android and iOS (web works) manifest.scheme error after ejecting

### ISSUE THREAD

**Issue by RWOverdijk** [expo/expo#7681]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/781745/78546712-30a8f880-77fe-11ea-8e64-138fe07d371b.png)

I'm guessing this has something to do with web and linking.

### Environment

  Expo CLI 3.17.16 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.5
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.4 => 0.61.5
    npmGlobalPackages:
      expo-cli: 3.17.16

### Steps to Reproduce

I was on 36, upgraded and then ejected (following the instructions in the blog post). Then I tried running on iOS (npm run ios).

### Expected Behavior

App just runs.

### Actual Behavior

 See screenshot.

### Reproducible Demo

I can't share my codebase right now, but if this error doesn't ring any bells I can strip all logic and try to share something.

## Update

I found out that https://github.com/expo/expo/blob/master/packages/expo/src/Linking/Linking.ts#L9 is looking for a manifest and after teading this https://forums.expo.io/t/getting-null-from-expoconstants-default-manifest-releasechannel-in-recently-bare-ejected-app/26491/9 I learned that there is no such thing on bare.

Expo wants me to eject and go bare (seriously, the terminology is pretty funny) because expokit is deprecated so I did. Should I have created a manifest as well or something?

**Comment by cruzach** [comment]
You should just be able to use the [react native Linking module](https://reactnative.dev/docs/linking), since Expo's linking module really just wraps that with a couple convenience methods/helpers for dealing with the Expo Client app
Let me know if that works!

**Comment by RWOverdijk** [comment]
@cruzach This is error comes from react navigation's useLinking. I don't use linking myself.

**Comment by RWOverdijk** [comment]
Nope, still got a question 😄 @cruzach Linking.makeUrl doesn't exist on react-native Linking

**Comment by brentvatne** [comment]
@RWOverdijk - `Linking.makeUrl` in https://reactnavigation.org/docs/deep-linking/#uri-prefix is just to get the scheme. replace use `const prefix = 'your-scheme'` instead of `const prefix = Linking.makeUrl('/')`

**Comment by nnabinh** [comment]
That helped a lot, thanks. I got exact the same issue and this resolved it.

**Comment by RWOverdijk** [comment]
@brentvatne Try as I might... I can't seem to get it to work. It never finds the root anymore. I know you've helped a lot already, and I appreciate it. But do you maybe have an example of what I should put there? I tried "localhost" but that doesn't seem to be it.

**Comment by brentvatne** [comment]
hey @RWOverdijk - sorry for the slow reply. if i understand the question correctly, you should use your `scheme` as the prefix. so, if your scheme is `myapp`:

```
const { getInitialState } = useLinking(ref, {
  prefixes: ['myapp://'],
  config: {
    // ....
  },
});
```

you can run `npx uri-scheme list` to see the schemes currently setup on your project -- warning: if you aren't using `launchMode="singletask"` on android yet you should add that to your `AndroidManifest.xml` (https://github.com/expo/expo/commit/b7abc5d076761043244e80b43631581e08d53f20#diff-4ed3d55cccd3b763d6c21ad24e69bd86R43). to add a scheme you can do `npx uri-scheme add myapp`

**Comment by RWOverdijk** [comment]
@brentvatne No worries, I wasn't expecting any replies at all at this point 😄 

I can see the scheme for ios yeah. I did add  the launchmode, but there's no scheme being output for android.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="studio.spoonx.myapp">
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.MANAGE_DOCUMENTS"/>
  <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
  <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.READ_CONTACTS"/>
  <uses-permission android:name="android.permission.READ_CALENDAR"/>
  <uses-permission android:name="android.permission.WRITE_CALENDAR"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  <uses-permission android:name="android.permission.WAKE_LOCK"/>
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher"
               android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false"
               android:theme="@style/AppTheme">
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="YOUR-APP-URL-HERE"/>
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="YOUR-APP-SDK-VERSION-HERE"/>
    <activity android:name=".MainActivity" android:theme="@style/AppTheme" android:label="@string/app_name"
              android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
              android:windowSoftInputMode="adjustResize"
              android:screenOrientation="portrait"
              android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
  </application>
</manifest>
```

**Comment by brentvatne** [comment]
ah - do `npx uri-scheme add -a somescheme` to add it to android

**Comment by RWOverdijk** [comment]
I love you Brent. <3

**Comment by brentvatne** [comment]
@EvanBacon built the `uri-scheme` pkg so he is the one to thank! it's pretty awesome https://github.com/expo/expo-cli/tree/master/packages/uri-scheme

**Comment by RWOverdijk** [comment]
Then I love both of you. It's okay, it's 2020 and that's allowed now.

**Comment by samstorino** [comment]
My issue was the way the `Linking` module was being imported. I created a managed workflow project using the `expo-cli`, which added a `useLinking` hook and imported the `Linking` module as follows:

`import { Linking } from 'expo';`

Once I ejected to the bare workflow I had to adjust the import to be more specific, [per the docs](https://docs.expo.io/versions/latest/sdk/linking/):
`import * as Linking from 'expo-linking';`
