### ISSUE TITLE
Native crash fo iOS notifications for ExpoKit production apps

### ISSUE THREAD

**Issue by SamyOptimize** [expo/expo#7683]
### Environment

Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @sentry/react-native: ^1.3.3 => 1.3.3 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 

### Steps to Reproduce

No steps to follow, crash happens on a handful of our users' iOS devices but none on ours that we can test.
There are 86 events of this crash and 22 users affected by it according to Sentry.

### Expected Behavior
No crashes to happen for iOS devices 

### Actual Behavior
Crashes on a handful of iOS devices 

### Reproducible Demo
Can't get a Reproducible Demo since it's only on production apps.

We've been receiving a lot of crash reports from Sentry and from Xcode's crash report screen for the following:

```
NSInvalidArgumentException
-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x283130c30

-[EXUserNotificationManager userNotificationCenter:willPresentNotification:withCompletionHandler:] (ExpoKit/ios/Exponent/Kernel/Services/EXUserNotificationManager.m:72)
```
And when opening the crash in our Xcode project it navigates to 
```
NSDictionary *userInfo = notification.request.content.userInfo;
  if (userInfo && userInfo[@"body"] && userInfo[@"body"][@"_displayInForeground"]) {//<---Last Exception Backtrace (0)
    // If user specifically set `_displayInForeground` in the notification, it always override `notification.iosDisplayInForeground` in `app.json`.
    shouldDisplayInForeground = [userInfo[@"body"][@"_displayInForeground"] boolValue];
  }
```
We have no idea what may be the problem and we've looked around for similar issues 
such as [#6081](https://github.com/expo/expo/issues/6081) which sounded like another similar issue [3223](https://github.com/expo/expo/issues/3223) but we're not sure if this would fix our problem. So we just want some help to push us in the right direction. We're not using Expo Push Notifications services, we're only using the Notifications.getDevicePushTokenAsync and using [apns2](https://github.com/sideshow/apns2) to send notifications to iOS devices

**Comment by sjchmiela** [comment]
If the crash happens near the code section you've pasted it would suggest that `userInfo[@"body"]` is a string in your notification payload (while it is expected to be a dictionary-object).

If you're sending notifications yourself with `apns2` it is possible that in payload you may be passing a `string` `payload.body` — ensure that the payload doesn't contain a stringy `body` property and let me know if it resolved your issue! 🙂

**Comment by tsapeta** [comment]
Due to inactivity in this thread, I'm going to close this. Feel free to comment here if you're still experiencing this issue and the above comment didn't help.
