### ISSUE TITLE
Sharing: is it possible to control the displayed thumbnail & file name & file type in the iOS dialog?

### ISSUE THREAD

**Issue by lsps9150414** [expo/expo#7684]
## What I am seeing in my simulator (iPhone 11 Pro Max 13.4):
![image](https://user-images.githubusercontent.com/5022617/78553743-58b74c80-783c-11ea-83c9-4a6fc9fc6972.png)

## What the [demo shows](https://docs.expo.io/versions/latest/tutorial/sharing/):
![image](https://user-images.githubusercontent.com/5022617/78553784-77b5de80-783c-11ea-95ff-3779d24690f9.png)

## Goal
I would like to display the `thumbnail`, `file name` and `file type`.

**Comment by cruzach** [comment]
This isn't possible right now, but feel free to open a feature request [here](https://expo.canny.io/feature-requests), or open up a PR! 😄

**Comment by lsps9150414** [comment]
@cruzach thanks for replying! Why did the official demo have thumbnail & file type & file size displaying though? Apologize for using  _control_ which isn't the best word, what I want is really to display those info instead of control what to display. Are there some ways to pass in those metadata?
