### ISSUE TITLE
expo-sharing: Getting `invalid scheme(null)` when calling shareAsync

### ISSUE THREAD

**Issue by lsps9150414** [expo/expo#7686]
### Environment

Expo CLI 3.15.4 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.15.4

#### Target
- real iPhone 6 running iOS 12.4.6
- Expo Client: v.2.15.2.108043

### Steps to Reproduce

```javascript
const handleSharePress = async (uri: string): Promise<void> => {
    if (!(await Sharing.isAvailableAsync())) {
      return;
    }
    const result = await Sharing.shareAsync(uri);
    if (!_.isEmpty(result)) {
      navigation.goBack();
    }
  };
```

### Expected Behavior

opens the share dialog.

### Actual Behavior

Throws the following error:
![IMG_BFA322962D91-1](https://user-images.githubusercontent.com/5022617/78554794-6077f080-783e-11ea-961e-afb841209e78.jpeg)

### Reproducible Demo

This only happens on the real device target described above. It works as expected on the iPhone 11 Pro Max 13.4 simulator.

**Comment by cruzach** [comment]
It looks like the `uri` you're providing doesn't match the expected format. I just tested this myself on an iPhone 7 and it was working fine. Make sure you are providing a local file URI as the documentation suggests - https://docs.expo.io/versions/latest/sdk/sharing/#sharingshareasyncurl-options

If the issue continues please provide a reproducible demo we can run

**Comment by lsps9150414** [comment]
Hi @cruzach Thanks for the hint. I am getting the URI with [`react-native-view-shot` ](https://docs.expo.io/versions/latest/sdk/captureRef/#api) using the [recommended high-level API](https://github.com/gre/react-native-view-shot#recommended-high-level-api) instead of `captureRef`.

Here's the Snack I created to recreate the issue: https://snack.expo.io/83CCP_fEw

Here's the result on my iPhone 6 (spec described in the OP):
![IMG_20685C81898A-1](https://user-images.githubusercontent.com/5022617/78642392-3c231f00-78e5-11ea-9e67-48879eb6de63.jpeg)

**Comment by cruzach** [comment]
a local file uri will start with `file://`
