### ISSUE TITLE
Expo code won't load

### ISSUE THREAD

**Issue by James2516** [expo/expo#769]
https://snack.expo.io/SyTJYEn2W

Can't seem to load this on phone/embed code for some reason.

**Comment by jimmylee** [comment]
You've unearthed an interesting bug! This is two part.

## First Part

The docs: https://facebook.github.io/react-native/docs/touchablehighlight.html

Touchable Highlight requires at least one child, here is an example of it working:

https://snack.expo.io/r1BHjQpnZ

## Second Part

Once you got to a broken state with TouchableHighlight, it was impossible to revert out of it! I experienced this as well. I'm sorry that happened to you, I'm going to assign this to a member of our team.

For now you'll just have to create another Snack if you end up in this situation.

**Comment by tcdavis** [comment]
Thanks for reporting!  The mobile part of snack isn't handling invariant violations gracefully, and once it encounters one it stops processing any updates to the code.
I believe if you get into this state it will be enough to close the snack on your phone and reload the Snack (with whatever triggered the error corrected)

**Comment by tcdavis** [comment]
You'll now get a much nicer error (and not have to restart snack) starting in SDK 24 https://snack.expo.io/H1JgM8Qff
