### ISSUE TITLE
Bare projects don't load on Android using targetSdkVersion 28

### ISSUE THREAD

**Issue by IjzerenHein** [expo/expo#7690]
## 🐛 Bug Report

Enabling `targetSdkVersion = 28` in `android/build.gradle` causes error upon opening the app.

```
Unable to load script. Make sure  you're either running a Metro server (run 'react-native start') or that your bundle  'index.android.bundle' is packaged correctly for release.
```

### Environment

Package json dependencies:

```
"dependencies": {
    "expo": "~37.0.3",
    "expo-updates": "~0.1.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-screens": "~2.2.0",
    "react-native-unimodules": "~0.9.0",
    "react-native-web": "~0.11.7"
  },
```

### Steps to Reproduce

- `expo init ExpoBareTargetSDK28`
- `cd ExpoBareTargetSDK28`
- update `targetSdkVersion` in `android/build.gradle` to `28`
- `yarn android`

### Expected Behavior

App loads as expected.

### Actual Behavior

![Screenshot_1586181311](https://user-images.githubusercontent.com/6184593/78566128-129fc000-781f-11ea-8b1c-0f6ec437c5f1.png)

**Comment by brentvatne** [comment]
me and @IjzerenHein resolved this today :)

**Comment by hosmelq** [comment]
I'm getting the same error, is there some workaround to solve this?

**Comment by lilosir** [comment]
@brentvatne I am getting the same issue, how did you resolve this? I am running this on local, should not be for release

**Comment by romelgomez** [comment]
@lilosir 

The error:

```text
Unable to load script. Make sure you're either running a Metro serve (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
```

### Steps to fix

In one terminal run:

**1)** `yarn start`

**2)** `press r`  **To reload the app press "r"**

In other terminal run:

**3)** `yarn android --verbose`

I hope this helps you
