### ISSUE TITLE
App Transport Security (ATS) is disabled

### ISSUE THREAD

**Issue by Mahesha-Bhat** [expo/expo#7692]
hi,
how to enable App Transport Security for ios in infoPlist of app.json.

**Comment by brentvatne** [comment]
you can customize the infoPlist property in app.json for standalone app builds https://docs.expo.io/versions/v37.0.0/workflow/configuration/#ios

**Comment by Mahesha-Bhat** [comment]
Hi,

I need to set NSAllowsArbitrataryLoads to true, can you explain how to do
this in app.json infoplist

**Comment by brentvatne** [comment]
that is always enabled by default so you don't need to do anything for that

**Comment by Mahesha-Bhat** [comment]
> that is always enabled by default so you don't need to do anything for that
> 
> https://github.com/expo/expo/blob/1012b414be26eca78230d64a9df1701f500eccc1/exponent-view-template/ios/exponent-view-template/Supporting/Info.plist#L23-L27

enabling ATS means setting NSAllowsArbitraryLoads to false, using xml format we can do it as you mentioned, how to do it in json format for infoPlist?

**Comment by brentvatne** [comment]
you just said you want to set it to true?

**Comment by brentvatne** [comment]
no you don't use xml you just use json

```json
"expo": {
  "ios": {
    "infoPlist": {
       "NSAppTransportSecurity": { "NSAllowsArbitraryLoads": false }
    }
  }
}
```

**Comment by Mahesha-Bhat** [comment]
> you just said you want to set it to true?

ya, but my intial question was to enable ATS so can you please help me do it.

**Comment by brentvatne** [comment]
ok in the future just so you know we do not answer questions on here, this is for bug reports. please use https://forums.expo.io next time

**Comment by Mahesha-Bhat** [comment]
> no you don't use xml you just use json
> 
> ```json
> "expo": {
>   "ios": {
>     "infoPlist": {
>        "NSAppTransportSecurity": { "NSAllowsArbitraryLoads": false }
>     }
>   }
> }
> ```

thank you for the help.

**Comment by Mahesha-Bhat** [comment]
> ok in the future just so you know we do not answer questions on here, this is for bug reports. please use https://forums.expo.io next time

sure thanks.
