### ISSUE TITLE
NetInfo 5.5.0 is not working in some projects all together

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo#7694]
## 🐛 Bug Report

With our babel settings we can't use the version of NetInfo that is included (5.5.0) breaks our app.
I posted [here](https://github.com/react-native-community/react-native-netinfo/issues/336) but realized that this was a fixed bug in newer versions of NetInfo - even just one minor version fixed it. 

The problem is I could not reproduce it in a new project so it's not simple but others in the Netinfo repo have reported it - that's why they fixed it.

Not sure the best way to go about upgrading just one package without ejecting.

### Environment

  Expo CLI 3.17.11 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.0 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.13.6 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.3.7 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.17.11

### Steps to Reproduce

When we add basic NetInfo listeners and we hit the `finally` block we break every time. 

### Expected Behavior

It works as documented in the docs for NetInfo.

### Actual Behavior

```
TypeError: undefined is not a function (near '...}).finally(function () {...')
Promise.race.then.then._catch%argument_0 
internetReachability.ts:125:11
```

### Reproducible Demo

I tried to get a new Expo app and add this code but it didn't cause an issue - but I can guarantee this is solved in 5.5.1 (or 5.7.0) instead of 5.5.0.

**Comment by cruzach** [comment]
Can you provide a snack that would theoretically throw this error? 

Also, if [this is the fix](https://github.com/react-native-community/react-native-netinfo/pull/311/files), then you could use patch-package for now to apply that JS fix

**Comment by brentvatne** [comment]
included 5.5.1 in bundledNativeModules.json so this will be fixed on next publish of the expo package. for now I believe that manually installing that version in your project (update the version in package.json and run npm install again) will resolve the issue.

https://github.com/expo/expo/commit/90c01cb0cd5dba70a2ab7b9e61761e9f8653c11a

**Comment by brentvatne** [comment]
if you update to the latest version of the expo package (`npm install expo@37.0.6`) and then run `expo install @react-native-community/net-info` you will get version 5.5.1 now :)

**Comment by jonathanstiansen** [comment]
@brentvatne you are a king among men!

**Comment by jonathanstiansen** [comment]
> if you update to the latest version of the expo package (`npm install expo@37.0.6`) and then run `expo install @react-native-community/net-info` you will get version 5.5.1 now :)

`netinfo` not `net-info` for everyone copy and pasting
