### ISSUE TITLE
[Notification] Is it possible to disable app click on launch

### ISSUE THREAD

**Issue by PierreSachot** [expo/expo#7695]
Hey everyone,

I'm developping a webradio app which needs a notification allowing to control the player. I saw that it's impossible to add button inside the notification body without detaching from expo... For this reason, I decided to add a button that allow to play/pause the sound (even if it's not at all what I was expected at the beginning). The problem is that the button always open the app when you click on it... Is there any way to disable it ? 

Thanks a lot !

**Comment by cruzach** [comment]
hi! you can create interactive notifications with Expo, you'll need to use [notifications categories](https://docs.expo.io/versions/latest/sdk/notifications/#notification-categories). 

Otherwise, no I don't think it's possible to prevent your app from launching when you select the notification

**Comment by PierreSachot** [comment]
Hi, thank you for the quick reply. This is what I've done, I created an notification categorie, but this does not resolve my problem ^^' the app always launch on button click
