### ISSUE TITLE
[SDK37] [Build] Android build failed

### ISSUE THREAD

**Issue by Jacky195** [expo/expo#7701]
## 🐛 Bug Report
Is there anyone get this error in Expo build-portal when building the Android? I kept getting it over 10 times, from yesterday to this morning. Thanks for help.

**/app/turtle/workingdir/android/sdk37/tools-public /app/turtle/workingdir/android/sdk37/android/app
/app/turtle/workingdir/android/sdk37/android/app
Error: https://d1wp6m56sqw74a.cloudfront.net/~assets/22e67cc3ae278cb47bca0058382d3330 is too small
    at WriteStream.<anonymous> (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:143:16)
    at WriteStream.emit (events.js:311:20)
    at WriteStream.EventEmitter.emit (domain.js:482:12)
    at internal/fs/streams.js:241:14
    at /app/turtle/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:154:23)**

Build URL: https://expo.io/dashboard/jacky195/builds/8c22d35d-844c-4062-8986-3b8ea23b0183

### Environment
Expo CLI: 3.17.1 (downgrade to 3.13.1 but failed too)
SDK: 37.0.0 (downgraded to 36.0.0 but failed too)
Node: v10.16.0
npm: 6.9.0

**Comment by brentvatne** [comment]
it looks like your app icon is too small - it should be at least 512x512 (preferably 1024x1024), but it is 192x192.

not sure why this is the only error message you receive about this, it should certainly be happening sooner in the process.

**Comment by Jacky195** [comment]
I change app icon "icon.png' to 1024x1024, but still failed ( https://expo.io/dashboard/jacky195/builds/c4ee9095-16ae-477c-a77a-1e969c7f3b37 )

[https://imgur.com/a/Z2MJ8Yp](url)

**Comment by Jacky195** [comment]
> it looks like your app icon is too small - it should be at least 512x512 (preferably 1024x1024), but it is 192x192.
> 
> not sure why this is the only error message you receive about this, it should certainly be happening sooner in the process.

thanks, but still failed. I added information in previous comment

**Comment by dsokal** [comment]
I've checked your build's logs and it turns out that you somehow managed to upload a .json file as an image. The builder is complaining about https://d1wp6m56sqw74a.cloudfront.net/~assets/22e67cc3ae278cb47bca0058382d3330 and this file is a .json file. How did you manage to do so? 
See the "Reading manifest" group and check that `asset_22e67cc3ae278cb47bca0058382d3330` has the `.json` suffix.

**Comment by brentvatne** [comment]
@Jacky195 - it looks like @dsokal has resolved this in https://github.com/expo/expo-cli/pull/1831 - let us know if the issue persists

**Comment by Jacky195** [comment]
@brentvatne  @dsokal  : I just tried, but unluckily still got failed. I updated to latest version of expo-cli. Please check it out. Thanks

Build URL: https://expo.io/dashboard/jacky195/builds/4f271635-3d8c-4359-9f7b-5655b2cad625

  Expo CLI 3.17.18 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v10.16.0/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^2.17.0 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.17.18

**Comment by Jacky195** [comment]
Finally, after I  removed the "empty json file with content:  {}"  (explained in [#1831](https://github.com/expo/expo-cli/pull/1831)) then I can get successful build.
I solved the problem, but seem "too small file issue" still unresolved.
Thanks a lot for supporting me.

**Comment by dsokal** [comment]
Hi @Jacky195,
sorry for the confusion. Like @brentvatne mentioned, I've fixed the problem in https://github.com/expo/expo-cli/pull/1831 but it still needs to be deployed to our builders. We'll probably do that today. I'll you know. Sorry for the inconvenience.

**Comment by dsokal** [comment]
Hi @Jacky195,
the fix has been deployed to our builders. Let us know if you're still experiencing the issue.

**Comment by Jacky195** [comment]
thank you so much @dsokal
