### ISSUE TITLE
"Firebase Analytics is not available in the Expo client." on Expo 37

### ISSUE THREAD

**Issue by bitttttten** [expo/expo#7705]
### Environment

```
Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @emotion/react: ^11.0.0-next.10 => 11.0.0-next.10 
      @testing-library/react-native: ^5.0.3 => 5.0.3 
      @types/react: ^16.9.11 => 16.9.31 
      @types/react-native: ^0.60.22 => 0.60.31 
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
```

### Steps to Reproduce

`expo install expo-firebase-core expo-firebase-analytics`

### Expected Behavior

No warning produced.

### Actual Behavior

You get a warning in the app and on the command line:

```sh

Firebase Analytics is not available in the Expo client. See "https://docs.expo.io/versions/latest/sdk/firebase-analytics" on more information on setting up Firebase Analytics with the standard Expo client.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/expo-firebase-analytics/build/ExpoFirebaseAnalytics.js:40:17 in callAnalyticsModule
- node_modules/expo-firebase-analytics/build/ExpoFirebaseAnalytics.js:51:15 in <global>
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
....
```

I am not sure if this warning is just a false positive, and is it safe to ignore?

**Comment by IjzerenHein** [comment]
Hi! No this warning should not be ignored. Running `expo-firebase-analytics` on the Expo client requires you to configure a valid web-configuration with a valid `measurementId`. Have you set this up?
https://docs.expo.io/versions/latest/sdk/firebase-analytics/#expo-client-limitations--configuration

**Comment by bitttttten** [comment]
Ah you need to configure the web even if you are just using the apps! Then my mistake.

I set up the web app on the Firebase console, even though I am not using it, and added the api key and measure id to my app.json and now it's working!

Many thanks :)

**Comment by prathamudeshmukh** [comment]
I have configured the `web` part in `app.json`, and still I am getting the same error 😞

**Comment by IjzerenHein** [comment]
> I have configured the web part in app.json, and still I am getting the same error 😞. I get this error,

You're probably using an older SDK version. FirebaseAnalytics requires SDK37

**Comment by andordavoti** [comment]
Hi! I get these warnings when running unit tests in jest. I don't get these warnings when running the app in the expo client and I see the data in firebase.

Should these warnings be ignored? I'm using the managed workflow.

![image](https://user-images.githubusercontent.com/24613178/83751991-1063b180-a668-11ea-8d7c-1da520ed711b.png)

**Comment by IjzerenHein** [comment]
@andordavoti Yes you can ignore these warnings in unit tests. Do be aware that these packages are native packages, so if you want to use them then you would need to mock them.

**Comment by andordavoti** [comment]
@IjzerenHein thanks!

**Comment by daurelien** [comment]
@IjzerenHein 
when i configure a android configuration firebase, got `Firebase Analytics is not available in the Expo client.`
and when i configure a web-configuration (+deleting android configuration) got :
`[Unhandled promise rejection: Error: Firebase is not configured. Ensure that you have configured 'google-services.json' correctly.]`

help please :x

**Comment by iqbal7892** [comment]
I am getting this error on sdk48.0.4 so please help how can i resolve this error
No native ExpoFirebaseCore module found, are you sure the expo-firebase-core module is linked properly?
No native ExpoFirebaseAnalytics module found, are you sure the expo-firebase-analytics's module is linked properly?

**Comment by miikapakarinen** [comment]
Running in the same issue after upgrading from Expo 47 to Expo 48. Expo doctor raises no issues and I can't see any version changes for the firebase related libraries after the upgrade.

`No native ExpoFirebaseAnalytics module found, are you sure the expo-firebase-analytics's module is linked properly?`

**Comment by acreddy9** [comment]
> I am getting this error on sdk48.0.4 so please help how can i resolve this error No native ExpoFirebaseCore module found, are you sure the expo-firebase-core module is linked properly? No native ExpoFirebaseAnalytics module found, are you sure the expo-firebase-analytics's module is linked properly?

Same in Expo 49
