### ISSUE TITLE
getOrientationAsync after upgrade to SDK37 does not return a ScreenOrientationInfo object, instead it return orientationId

### ISSUE THREAD

**Issue by kopax** [expo/expo#7706]
I am upgrading from SDK36 to 37 and found this breaking change:

- `Removed Orientation.PORTRAIT and Orientation.LANDSCAPE from ScreenOrientation in favor of their more specific versions. (#6760 by @lukmccall)`

I was able to accomplish my upgrade to the end, but I am reporting an issue in the doc since `getOrientationAsync` does not return a `ScreenOrientationInfo` object anymore, but instead it return the `orientationId`.

This error happen on iOS/Android/Web.

I was using them:

```jsx
import React, { cloneElement } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { compose } from 'redux';
import { createStructuredSelector } from 'reselect';
import {
  addOrientationChangeListener,
  removeOrientationChangeListener,
  getOrientationAsync,
  Orientation,
} from 'expo-screen-orientation';
import omit from 'lodash.omit';

import withDimensions from '../dimensions/withDimensions';
import { orientationChange as orientationChangeAction } from '../reducers/app/layoutReducer/actions';
import { selectOrientation } from '../reducers/app/layoutReducer/selectors';

class ConnectedOrientationProvider extends React.Component {
  constructor(props) {
    super(props);
    this.onOrientationChange = this.onOrientationChange.bind(this);
  }

  // eslint-disable-next-line camelcase
  UNSAFE_componentWillMount() {
    this.subscription = addOrientationChangeListener(this.onOrientationChange);
  }

  async componentDidMount() {
    await this.detectOrientation();
  }

  componentWillUnmount() {
    removeOrientationChangeListener(this.subscription);
  }

  onOrientationChange({ orientationInfo: { orientation } }) {
    this.setOrientation(orientation);
  }

  setOrientation(orientation) {
    const { orientationChange } = this.props;
    orientationChange(this.fixOrientation(orientation));
  }

  fixOrientation(orientation) {
    let newOrientation = orientation;
    /** fix for android having too much orientations */
    newOrientation = newOrientation.split('_')[0]; // eslint-disable-line prefer-destructuring
    /** fix for safari (See https://github.com/expo/expo/issues/6949) */
    if (newOrientation === Orientation.UNKNOWN) {
      const { dimensions: { width, height } } = this.props;
      newOrientation = width > height ? Orientation.LANDSCAPE : Orientation.PORTRAIT;
    }
    return newOrientation;
  }

  async detectOrientation() {
    const { orientation } = await getOrientationAsync();
    this.setOrientation(orientation);
  }

  render() {
    const { children, ...rest } = omit(this.props, ['orientationChange', 'orientation', 'dimensions']);
    return cloneElement(children, rest);
  }
}

ConnectedOrientationProvider.propTypes = {
  orientationChange: PropTypes.func.isRequired,
  dimensions: PropTypes.shape({
    width: PropTypes.number,
    height: PropTypes.number,
  }).isRequired,
};

const mapStateToProps = createStructuredSelector({
  orientation: selectOrientation,
});

const mapDispatchToProps = (dispatch) => ({
  orientationChange: (orientation) => dispatch(orientationChangeAction(orientation)),
});


export default compose(
  withDimensions,
  connect(mapStateToProps, mapDispatchToProps),
)(ConnectedOrientationProvider);

```

Now the `detectOrientation` always return `undefined` on the web.

I have fixed it with: 

```jsx
const orientationId = await getOrientationAsync();
```

This will return `3` (while I was expecting to have a `ScreenOrientationInfo` object as described in the doc here : https://docs.expo.io/versions/latest/sdk/screen-orientation/#screenorientationscreenorientationinfo)

I am able to fix my class with `Orientation[orientationId]` 

# Related

- https://blog.expo.io/expo-sdk-37-is-now-available-dd5770f066a6
- https://github.com/expo/expo/pull/6760

**Comment by kopax** [comment]
I am not able to perform the upgrade to SDK37, despite the fact that I am following the changelog and being aware of the breaking changes. 

I have replaced all the `ScreenOrientation.Orientation.PORTRAIT` and `ScreenOrientation.Orientation.LANDSCAPE` in my workspace, I have tried to build, run with `expo start -c`, I keep having an error trying to read from it.

I thought it could be because of the outdated alpha 5 version of react navigation I am using, but it's not. 

I have stopped for now the migration until I get a bit of an answer that will require more time for testing.

**Comment by IjzerenHein** [comment]
Hi, thanks for reporting this, I've updated the docs in #7711 👍

**Comment by IjzerenHein** [comment]
Hi! Okay it seems there is more going on here. Could you provide a minimal reproducible demo (or code sample, function-call) that throws the error that you mentioned?

**Comment by kopax** [comment]
Sure, I am working on it right now.

**Comment by kopax** [comment]
After removing more and more from my app, I finally hit the point where the error disappeared.

So I can only say it is an issue in my code based, even if there is no `ScreenOrientation.Orientation.PORTRAIT/LANDSCAPE` written anywhere.

I will need more time to investigate.

Will I be able to upgrade later to SDK37->38->39->etc if I let it go now ? or should I upgrade as soon as possible ?

Also, are you aware of possible cache issue that would need some additional precaution while upgrading?

**Comment by lukmccall** [comment]
@kopax, please make sure that you don't have imports like this: 
```ts
import { ScreenOrientation } from 'expo'; 
```
Cause I've run into a similar problem like you.

**Comment by kopax** [comment]
> @kopax, please make sure that you don't have imports like this:
> 
> ```ts
> import { ScreenOrientation } from 'expo'; 
> ```
> 
> Cause I've run into a similar problem like you. And this import caused this issue.

I already did, and the error is misleading because it was not this. I am not sure where the error is and I will let you know when I know it. 

I will close this discussion for now as soon as I get the answer for the last two questions I have:

- Will I be able to upgrade later to SDK37->38->39->etc if I let it go now ? or should I upgrade as soon as possible?
- Also, are you aware of possible cache issue that would need some additional precaution/action while upgrading?

**Comment by lukmccall** [comment]
So, it is possible to upgrade later to a newer version. You can do it whenever you want to. 
However, we recommend doing it one by one. For example, it may not be safe to upgrade straight from 36 to 38. Additionally, upgrading SDK versions incrementally can help you spot bugs and different problems related to breaking changes. 

We aren't aware of any cache issue.

**Comment by kopax** [comment]
Yes, it makes sense to upgrade one version by one. What I was worried about, is because I see all those snacks being obsolete, is to see my app becoming obsolete as well. If doing the upgrade can be done at any time, that is very good news. I'll close this for now and I will post further information when I will solve the upgrade for those showing the same symptoms with their app. Thanks again for being watching issues after releasing new sdk version !
