### ISSUE TITLE
[SDK 37] Screens now showing up blank in react navigation tabs

### ISSUE THREAD

**Issue by bill-pairaktaridis** [expo/expo#7707]
### Environment

```
  Expo CLI 3.17.18 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6200805
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.3.7 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.17.18
```

Targeting Android. iOS works fine.

### Steps to Reproduce

I've been using react navigation 4 and react-navigation-tabs for a while now and specifically Material Top Tab Navigation. I upgraded to Expo 37 this morning and suddenly my screens are blank, except for usually the last screen in the stack but that changes if I fast refresh. 

Attached video:

https://drive.google.com/file/d/1thM0cXhZJLw1Bi9nNJBwDMgeDdK5M0eS/view?usp=sharing

### Expected Behavior

Screens should work as before or the breaking changes docs should be updated

### Actual Behavior

Screens are blank

**Comment by IjzerenHein** [comment]
Hi! Which Expo version did you upgrade from?

**Comment by bill-pairaktaridis** [comment]
36

**Comment by IjzerenHein** [comment]
This might be related to `react-native-screen` which has been updated to `2.2.0` in SDK 37. Could you try installing the latest `react-navigation` and `react-navigation-tabs` versions?

**Comment by bill-pairaktaridis** [comment]
I'm on the latest version without upgrading to `react-navigation` 5 which would require refactoring of my entire navigation stack. What is strange is that on iOS it works fine.

My dependencies:

```
"dependencies": {
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/datetimepicker": "2.2.2",
    "@react-native-community/masked-view": "0.1.6",
    "@react-native-community/netinfo": "5.5.1",
    "country-telephone-data": "^0.6.0",
    "detox": "^15.4.1",
    "detox-expo-helpers": "^0.6.0",
    "expo": "^37.0.6",
    "expo-analytics": "^1.0.15",
    "expo-constants": "~9.0.0",
    "expo-detox-hook": "^1.0.10",
    "expo-facebook": "~8.1.0",
    "expo-file-system": "~8.1.0",
    "expo-gl": "~8.1.0",
    "expo-image-manipulator": "~8.1.0",
    "expo-image-picker": "~8.1.0",
    "expo-intent-launcher": "~8.1.0",
    "expo-localization": "~8.1.0",
    "expo-location": "~8.1.0",
    "expo-media-library": "~8.1.0",
    "expo-permissions": "~8.1.0",
    "expo-pixi": "^1.2.0",
    "expo-postpublish-slack-notify": "^1.2.0",
    "expo-print": "~8.1.0",
    "expo-screen-orientation": "~1.0.0",
    "expo-sms": "~8.1.0",
    "expo-store-review": "~2.1.0",
    "expo-task-manager": "~8.1.0",
    "expo-updates": "~0.1.0",
    "expo-web-browser": "~8.1.0",
    "expokit": "32.0.2",
    "geolib": "^3.0.3",
    "i18n-js": "^3.1.0",
    "libphonenumber-js": "^1.7.23",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
    "react-native-app-link": "^1.0.0",
    "react-native-appearance": "~0.3.3",
    "react-native-elements": "^0.19.1",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-hyperlink": "0.0.14",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-maps": "0.26.1",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-signature-canvas": "^1.6.0",
    "react-native-signature-pad": "^0.1.0",
    "react-native-svg": "11.0.1",
    "react-native-svg-animated-linear-gradient": "^0.1.9",
    "react-native-swipe-verify": "^0.1.6",
    "react-native-testing-library": "^1.12.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-view-shot": "3.1.2",
    "react-native-webview": "8.1.1",
    "react-navigation": "^4.3.7",
    "react-navigation-drawer": "^2.4.11",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.8.11",
    "react-redux": "^5.1.2",
    "redux": "^4.0.5",
    "redux-persist": "^5.10.0",
    "redux-sentry-middleware": "^0.1.8",
    "sentry-expo": "^2.0.3",
    "tiny-emitter": "^2.1.0"
  }
```

**Comment by IjzerenHein** [comment]
> I'm on the latest version without upgrading to react-navigation 5 which would require refactoring of my entire navigation stack.
👍 

Are you using `enableScreens` in your app? Could you try disabling it and see whether that makes any difference?

**Comment by bill-pairaktaridis** [comment]
Alright, so after re-installing everything related to `react-navigation` and `react-navigation-tabs` from [here](https://reactnavigation.org/docs/4.x/getting-started/) and uninstalling and reinstalling `react-native-screens`, it seems to be working fine.  I also had to remove `enableScreens()` which seems to be the main culprit.

I also cleared the data of the Expo app on my device and restarted Watchman for good measure. 

Not quite sure what the actual issue is, since I can't find any reference in the docs anywhere.

**Comment by bill-pairaktaridis** [comment]
Also, slightly unrelated, but fast refresh and accessing the dev menu aren't available on my end

**Comment by IjzerenHein** [comment]
> Also, slightly unrelated, but fast refresh and accessing the dev menu aren't available on my end

Please open a new issue for that or check whether one has already been opened

**Comment by IjzerenHein** [comment]
> Alright, so after re-installing everything related to react-navigation and react-navigation-tabs from here and uninstalling and reinstalling react-native-screens, it seems to be working fine. I also had to remove enableScreens() which seems to be the main culprit.
>
> I also cleared the data of the Expo app on my device and restarted Watchman for good measure.
>
> Not quite sure what the actual issue is, since I can't find any reference in the docs anywhere.

Well first of all glad it's working now. If re-enabling `enableScreens` still causes the problem then this might be an issue with `react-navigation-tabs` in combination with `react-native-screens`. You could  try checking the react-navigation repo and opening an issue there.

**Comment by bill-pairaktaridis** [comment]
Thanks a lot! I'll check over there.
