### ISSUE TITLE
SDK35 - Android 7 to 10 : java.lang.RuntimeException Expo encountered a fatal error: Could not invoke FileReaderModule.readAsText

### ISSUE THREAD

**Issue by lc3t35** [expo/expo#7708]
### Environment

```
Expo CLI 3.13.6 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 3.10.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.1 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: 3.11.1 => 3.11.1
```

on some Android 7, 8, 9 and 10.

### Steps to Reproduce

Launch app, poke around and suddenly app crashes on some Android (a few dozen on hundreds of users without problem).

### Expected Behavior

I don't expect the app to crash randomly.

### Actual Behavior

Bugsnag catches this error that pops up randomly :

```
java.lang.RuntimeException Expo encountered a fatal error: Could not invoke FileReaderModule.readAsText 
    BaseExperienceActivity.java:197 host.exp.exponent.experience.a$2.run
    Handler.java:789 android.os.Handler.handleCallback
    Handler.java:98 android.os.Handler.dispatchMessage
    Looper.java:164 android.os.Looper.loop
    ActivityThread.java:6944 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    Zygote.java:327 com.android.internal.os.Zygote$MethodAndArgsCaller.run
    ZygoteInit.java:1374 com.android.internal.os.ZygoteInit.main
```
### Reproducible Demo

No sorry but maybe you can tell me more about BaseExperienceActivity.java ?

**Comment by IjzerenHein** [comment]
Hi! A reproducible demo would probably be essential in order to help with this.
`BaseExperienceActivity` is just a core class,  don't think that will help us further.
It seems that this has something to do with reading blobs using `FileReader`.  Are you doing that in your app?

**Comment by lc3t35** [comment]
I don't have any call to `FileReader` in my app.

**Comment by lc3t35** [comment]
Could it be related to https://github.com/wkh237/react-native-fetch-blob/issues/205 ?

> RNFetchBlob and the default fetch library can have strange interactions

I'm updating to SDK37 to check if this issue is still there....

**Comment by lc3t35** [comment]
As it is impossible to update to SDK37 bare workflow, I will try to switch standard fetch by react-native-fetch-blob's fetch ? and see what happens ...

**Comment by IjzerenHein** [comment]
Yes you're right, it's indeed `fetch` that is calling this method. `react-native-fetch-blob` is quite an old lib (and archived by its owner) and is not included in Expo.

As this problem only happens occasionally, could it be possible that your server is sometimes returning an invalid response to a `fetch` call?

**Comment by lc3t35** [comment]
thank you @IjzerenHein, what would you recommend as library replacement for fetch/rn-fetch-blob ?
How can I check an invalid response from fetch call ?

**Comment by IjzerenHein** [comment]
Hi Laurent. I don't think using fetch-blob would have necessarily been the solution.
I think what we need to do here is to isolate the problem and create a reproducible case. If we understand the cause then we can start looking at solutions and workarounds.
So unless we have a way to reproduce this, this will be very hard to fix.

**Comment by lc3t35** [comment]
In sdk35, after removing any reference to fetch-blob, using strict fetch, heavy debugging app with Android Studio and server-side (using [morgan-body](https://www.npmjs.com/package/morgan-body)), I found that a big amount of data was sent by the server as answer for a specific fetch request. After fixing the server-side, all went back to normal.
Thank you @IjzerenHein for pointing 
> could it be possible that your server is sometimes returning an invalid response to a fetch call

**Comment by IjzerenHein** [comment]
I'm glad you were able to resolve the issue Laurent! Would you mind sharing what the response was that was causing the crash? It's probably worth reporting this upstream to RN.

**Comment by normenster** [comment]
@lc3t35 @IjzerenHein I`m experiencing the same bug on some androids (6-7). I´m using fetch for accessing a JSON API and also the expo-file-system for downloading offline videos. Is `com.facebook.react.modules.blob.FileReaderModule.readAsText` used in the expo-file-system module?
