### ISSUE TITLE
Reopen Audio recording needs to be multi-platform. #757

### ISSUE THREAD

**Issue by dooboolab** [expo/expo#771]
@ccheever 
I've tried many options with given variables... but whenever I tried it it gave me this error. It only works in caf for ios.

![image](https://user-images.githubusercontent.com/27461460/31499069-a8eb994a-af9e-11e7-8b16-232a1acedbba.png)

Can you please check this? It always gives error with different extension and outputformat.
![image](https://user-images.githubusercontent.com/27461460/31499177-06fa4054-af9f-11e7-8863-0d0ab58b817a.png)

**Comment by ide** [comment]
We're tracking this same issue here (https://github.com/expo/expo/issues/790) so I'm closing this one to consolidate the reports.
