### ISSUE TITLE
Expo-cli stuck on `Installing node_modules and rebuilding package-lock.json`

### ISSUE THREAD

**Issue by nitingupta220** [expo/expo#7710]
I have an app running on expo sdkVersion `33.0.0`
I want to update the sdk to `34.0.0`
I ran the command in terminal to update `expo update 34.0.0` but it gets stuck installing `node_modules` and rebuilding `package-lock.json` 
I have attached the screenshot as well for the same. 
Can anyone help?
@croaky @chrisdrackett 
<img width="1001" alt="Screenshot 1942-01-18 at 4 54 48 PM" src="https://user-images.githubusercontent.com/25584421/78663845-7e9e2900-78f0-11ea-9c76-1271a89521e9.png">

**Comment by nitingupta220** [comment]
I somehow managed to run the app but not below error coming: - 
I get the error that font family Roboto is not a system font but even though I'm loading that font via Font.loadAsync earlier. I don't know why I'm getting this error.
Can anyone help?
<img width="435" alt="Screenshot 1942-01-18 at 7 47 24 PM" src="https://user-images.githubusercontent.com/25584421/78680035-9b465b00-7908-11ea-8f1b-e4558d5b2161.png">
<img width="674" alt="Screenshot 1942-01-18 at 7 47 34 PM" src="https://user-images.githubusercontent.com/25584421/78680053-a1d4d280-7908-11ea-9aa4-769bb76894e9.png">

**Comment by cruzach** [comment]
@nitingupta220 can you try deleting  `package-lock.json` and also `node_modules`, then re-installing?

**Comment by nitingupta220** [comment]
@cruzach I tried it but still stuck at same.

**Comment by brentvatne** [comment]
if you're unable to delete package-lock.json and run npm install then this is a problem the npm setup on your machine.. there isn't much we can do to help about this, i would suggest using yarn instead.  https://classic.yarnpkg.com/lang/en/

**Comment by nitingupta220** [comment]
@brentvatne How can you close the issue without even consulting it to me?
I said that I have already deleted the package-lock.json and node_modules and then tried to run expo update 34.0.0 but still getting the same error.

Are you here to help or just to give nothing help and closing the issue without even consulting it with the reporter?

**Comment by brentvatne** [comment]
@nitingupta220 - i closed the issue because this is unrelated to expo. you need to figure out how to get `npm install` running on your machine.
