### ISSUE TITLE
[docs] Svg page - prompt user to import Svg from expo rather than react-native-svg 

### ISSUE THREAD

**Issue by chanonroy** [expo/expo#7712]
While using `expo` and `react-native-svg`, I was running into this issue when trying to build for mobile:

While using this import:
```
import Svg, { G, Path } from "react-native-svg" 
```

This error was thrown:
```
invariant violation: tried to register two views with the same name RNSVGRect
```

I was able to resolve this error warning by following [this](https://github.com/expo/expo/issues/2599#issuecomment-435914007) advice, to remove `react-native-svg` and import directly from expo as seen here:
```
import { Svg } from "expo"
```

---

The docs page for [Svg](https://docs.expo.io/versions/latest/sdk/svg/) currently points to importing Svg directly from `react-native-svg`. Is it worth updating the docs to prompt the user to import from expo directly?

**Comment by IjzerenHein** [comment]
Hi! Our apologies, I see that the docs need to be updated.

The correct import statement should be:

```
import * as Svg from 'react-native-svg';
```

or 

```
import {G, Path} from 'react-native-svg';
```

**Comment by chanonroy** [comment]
@IjzerenHein - cheers!

quick question - is there any downside to using the import from "expo" rather than "react-native-svg"?

**Comment by IjzerenHein** [comment]
I would not recommend using `import { Svg } from "expo"`. Instead the packages you use should not have a hard dependency on `react-native-svg` but merely a peer-dependency. You should then use `expo install react-native-svg` to install the compatible version.

**Comment by IjzerenHein** [comment]
You can use `npm ls react-native-svg` to find out which packages are also importing svg.

**Comment by chanonroy** [comment]
This worked! Thank you so much 😄

**Comment by IjzerenHein** [comment]
Glad it has worked 😊
