### ISSUE TITLE
SDK37 Upgrade Fail: __fbBatchedBridgeConfig is not set, cannot invoke native modules

### ISSUE THREAD

**Issue by jjg77** [expo/expo#7716]
### Environment

 **Expo CLI 3.17.18** environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: 3.9.2 => 3.9.2 
    npmGlobalPackages:
      expo-cli: 3.17.18

### Steps to Reproduce

expo upgrade (36 -> 37)
yarn add react-native-web@0.11.7
expo start 

Testing expo web.

### WARNINGS

/Users/xxx/Sites/xxx/node_modules/expo/build/logs/LogSerialization.js
Attempted import error: 'react-native/Libraries/Core/Devtools/symbolicateStackTrace' does not contain a default export (imported as 'symbolicateStackTrace').

/Users/xxx/Sites/xxx/node_modules/react-native/Libraries/Performance/Systrace.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ERRORS

__fbBatchedBridgeConfig is not set, cannot invoke native modules
▶ 3 stack frames were collapsed.
__webpack_require__
/Users/xxx/Sites/xxx/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
