### ISSUE TITLE
requireNativeComponent: "RNCSlider" was not found in the UIManager

### ISSUE THREAD

**Issue by JustynaKK** [expo/expo#7719]
### Environment
```
Expo CLI 3.17.18 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Justyna\AppData\Roaming\npm\yarn.CMD
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

### Steps to Reproduce
Since the docs for SDK 37 about Slider says: "Deprecated. Use react-native-community/react-native-slider instead." 
I replaced  `import { Slider } from "react-native";` for `import Slider from "@react-native-community/slider";`

### Actual Behavior
I am getting the error:
`requireNativeComponent: "RNCSlider" was not found in the UIManager` and
`Invariant Violation: View config not found for name RNCSlider`

**Comment by brentvatne** [comment]
sorry these docs are incorrect, we will update them. please use `Slider` from react-native

**Comment by brentvatne** [comment]
updated the docs page, thanks for pointing this out!
