### ISSUE TITLE
@unimodules/core version constraint seems often incorrect

### ISSUE THREAD

**Issue by chrisbobbe** [expo/expo#7728]
If this is already being tracked, please close this and consider folding some of these findings in as a bullet point.

In a bare project, if I have `@unimodules/core` at version 4.0.0, and I `yarn add expo-application`, I get

```
warning " > expo-application@2.1.0" has unmet peer dependency "@unimodules/core@~1.0.0".
```

on this and subsequent runs of `yarn`. I have `@unimodules/core` at version 4.0.0 (I believe this isn't the latest, but we're stuck on `react-native-unimodules` at 0.6.0, no caret, because we're still on React Native v0.59.10. The need for 0.6.0 is explained [here](https://github.com/unimodules/react-native-unimodules/issues/100#issuecomment-566436685)).

In any case, it looks like version 2.1.0 of `expo-application` — which is its latest version! — declares that it won't work unless you're on version ~1.0.0 of `@unimodules/core`, which was superseded in April 2019 (shown with `git log --stat -p -S 2.0.0 packages/@unimodules/core/package.json`).

In fact, at the time `expo-application` was first created, in August 2019, `@unimodules/core` was already at version 3.0.2!

```
$ git log --stat -p -G @unimodules/core packages/expo-application/package.json
commit cf45390bc5f024b16a2eab2fcd4579b6ec317203
Author: Robert Luo <1998.robert@gmail.com>
Date:   Thu Aug 8 14:35:23 2019 -0700

    [expo-application] create expo-application unimodule (#5008)
...
```

```
$ git show cf45390bc:packages/@unimodules/core/package.json | jq -r .version
3.0.2
```

From experimentation, the 1.0.0 version constraint doesn't seem to be meaningful; we haven't, yet, run into problems with `expo-application`. But we've so far maintained that the output of `yarn` is warning-free, to make sure there's a clear signal there, for our own contributors, so it would be a great improvement if this noise (if it is noise) were removed.

Here's some data on the unimodules' version constraints for `@unimodules/core`. 
```
$ grep -h '"@unimodules/core":' **/package.json | sort | uniq -c
    131     "@unimodules/core": "*"
    119     "@unimodules/core": "*",
     20     "@unimodules/core": "~1.0.0"
      6     "@unimodules/core": "^2.0.0-alpha.0",
      5     "@unimodules/core": "~3.0.0",
      4     "@unimodules/core": "~3.0.2"
      1     "@unimodules/core": "~3.0.2",
      1     "@unimodules/core": "~5.0.0",
      1     "@unimodules/core": "~5.0.0-rc.0",
      2     "@unimodules/core": "~5.1.0",
```

So, it looks like most unimodules are lenient, and don't have any meaningful version constraint. Can this be applied across the board? Or, at least, could all new releases of a package be made and declared compatible with current, commonly used versions of `@unimodules/core`?

**Comment by brentvatne** [comment]
hey @chrisbobbe! I have changed the peer dependencies for all of the expo packages to use a lenient `*` for the `@unimodules/core` peer dependency. currently we release all modules at the same time, but we're about to switch to publishing expo module updates much more frequently and then we'll want to be more strict about supported versions of the base packages like @unimodules/core.

**Comment by chrisbobbe** [comment]
Yay, thanks, @brentvatne!
