### ISSUE TITLE
exp build:ios failed at Fetching a new push certificate

### ISSUE THREAD

**Issue by titomheniart** [expo/expo#773]
Hi, I want to build my app for iOS with expo so I execute `exp build:ios` and everything is fine until expo try to fetch a new push certificate

I already tried `exp build:ios -c` but same result

Could you tel me if I am missing something or if I have an other way to build my app for iOS

Cheers

StackTracce: 

[exp] Validating Apple credentials...
[exp] Credentials valid.
[exp] Generating distribution certificate...
[exp] Distribution certificate setup complete.
[exp] Validating app id...
[exp] Fetching a new push certificate...
[exp] Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to fetch push certificate. Request ID 932914b0-aff9-11e7-b3a0-1993410b0374

**Comment by ide** [comment]
It looks like the standalone app builder couldn't find an app with your iOS Bundle ID in the Apple Developer Center. Double check that the iOS bundle ID in your app.json matches the one on Apple's dev site and that you've followed the iOS standalone app instructions closely.

**Comment by titomheniart** [comment]
You're right, it was the problem
Thanks a lot !
