### ISSUE TITLE
Problem with iOS simulator connecting to react-devtools

### ISSUE THREAD

**Issue by robertwt7** [expo/expo#7731]
Hey guys,

I apologise if i'm reporting this on the wrong repo, but for the past few hours i've been trying to connect my iOS simulator that is run by expo to react-devtools in the official release, remotely to chrome, and also at rndebugger but none of them works. I even reported it [here](https://github.com/jhen0409/react-native-debugger/issues/492). However when i try to run it from my own iOS device, suddenly everything works like charm and react dev tools is connected straightaway.

I'm using expo sdk 35, is there any bug related to that? Might be useful for someone in the future trying to get debugging ready. Save few hours

<img width="1277" alt="Screen Shot 2020-04-08 at 2 46 05 pm" src="https://user-images.githubusercontent.com/15647967/78747559-08133100-79ad-11ea-8292-df7588c5e540.png">

Thanks!

**Comment by byCedric** [comment]
Hi @robertwt7, thanks for the issue report! Unfortunately, I could not reproduce this issue using SDK 35. Here are the versions that I've tried:

- `react-devtools`, version `3.6.3`
- React Native Debugger, version `0.10.6`
- Expo Client, version `2.15.3.10122`
- `expo`, version `35.0.1`

If this doesn't work for you, could you try creating a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

Hope this brings you a bit closer 😄

**Comment by robertwt7** [comment]
Hey @byCedric 

Thanks for replying! Really appreciate it

Anyway here's my complete setup:
- `react-devtools`, version `3.6.3`
- React native debugger, version `0.10.9`
- Expo client, version `3.17.18`
- expo, version `35.0.0`

Here's my dependencies in package.json, this is the way i checked my expo version:
```
  "dependencies": {
    "@appandflow/masonry-list": "^0.4.0",
    "axios": "0.19.0",
    "expo": "35.0.0",
    "expo-ads-admob": "~7.0.0",
    "expo-ads-facebook": "~7.0.0",
    "expo-asset": "~7.0.0",
    "expo-constants": "~7.0.0",
    "expo-facebook": "~7.0.0",
    "expo-font": "~7.0.0",
    "expo-google-app-auth": "^7.0.0",
    "expo-image-picker": "~7.0.0",
    "expo-linear-gradient": "~7.0.0",
    "expo-localization": "~7.0.0",
    "expo-permissions": "~7.0.0",
    "expo-web-browser": "~7.0.0",
    "firebase": "7.1.0",
    "html-entities": "^1.2.1",
    "lodash": "4.17.15",
    "moment": "^2.24.0",
    "patch-package": "^6.1.2",
    "path": "^0.12.7",
    "postinstall-postinstall": "^2.0.0",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-animatable": "1.3.2",
    "react-native-dotenv": "^0.2.0",
    "react-native-drawer": "https://github.com/luyx2412/react-native-drawer.git",
    "react-native-dropdownalert": "4.1.0",
    "react-native-expo-image-cache": "4.0.4",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-image-zoom-viewer": "2.2.26",
    "react-native-modalbox": "^1.7.1",
    "react-native-onboarding-component": "^0.0.5",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-render-html": "^4.1.2",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-snap-carousel": "3.8.0",
    "react-native-swipeout": "^2.3.6",
    "react-native-swiper": "^1.5.14",
    "react-native-timeago": "^0.4.0",
    "react-native-webview": "7.0.5",
    "react-navigation": "^3.11.0",
    "react-redux": "7.1.0",
    "redux": "4.0.4",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "sanitize-html": "1.20.1",
    "striptags": "^3.1.1",
    "urijs": "^1.19.1",
    "url": "^0.11.0",
    "util": "0.12.1",
    "wpapi": "^1.2.1"
  },
```


What I did for this was I run expo start -> click on `run on iOS simulator` -> run remote js debugging -> open react native debugger, run command + T to run on port 19001, then react stuck on waiting. Same goes on running `react-devtools` on terminal

**Comment by robertwt7** [comment]
Hey sorry, i just had the craziest day yesterday. I'm not sure what was wrong but I swear it wasn't working yesterday. I just tried it again on simulator and its all working fine. Probably I just need to restart the simulator or some port was blocking them.

Thanks so much for the reply, i'll close this!

**Comment by byCedric** [comment]
No worries, glad it works for you 😄
