### ISSUE TITLE
sdk37 : __fbBatchedBridgeConfig is not set, cannot invoke native modules

### ISSUE THREAD

**Issue by soyo-ung** [expo/expo#7735]
Hi, I read [the issue](https://github.com/expo/expo/issues/7677) about this error (__fbBatchedBridgeConfig is not set, cannot invoke native modules) and I upgraded expo-cli version to 3.17.18, but still got the same error.

#### dependencies in package.json : 
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.2.5",
    "@react-navigation/native": "^5.1.4",
    "@react-navigation/stack": "^5.2.9",
    "expo": "^37.0.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "^0.11.7"
 
The error was : 
### __fbBatchedBridgeConfig is not set, cannot invoke native modules
__webpack_require__
/Users/.../webpack/bootstrap:726

I guess this error is related to some dependencies, but I don't know exactly why and how to fix it so I ask for your help. Thanks.

___________________________________________________________________________

I found this was because of a wrong import from NewAppScreen that wasn't done by me but probably added during some update, etc, by error. So I close this issue!

**Comment by Denver-sn** [comment]
Hello  @soyo-ung i'm facing this issue since some days can you tell me where did u fix the wrong import from NewAppScreen
