### ISSUE TITLE
android dev menu hotkey cmd+m is not working on sdk 36+

### ISSUE THREAD

**Issue by N1gma** [expo/expo#7738]
### Environment

 Expo CLI 3.16.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.16.1

Android

### Steps to Reproduce

- add Nexus 6/Pixel 2 or any other avd
- open avd
- run app from using expo cli using Run on Android device/emulator

### Expected Behavior

- dev menu can be opened via cmd+m or maybe theres other hotkey's

### Actual Behavior

- dev menu cant be opened via cmd+m, only double r working for app reload

### Reproducible Demo

Cant see how I can put reproducible demo, but I followed the guide https://docs.expo.io/versions/v36.0.0/workflow/android-studio-emulator/ - avd command is working. Things changes from sdk36 so dev menu cant be opened now. Enable keyboard input in advanced settings checked.

**Comment by Darapsas** [comment]
Ctrl+M seems to be working in the app only when you open an expo app in the background.

Tested on: expo 37.0.0sdk, android emulator (running pixel 3xl with android 10).

**Comment by N1gma** [comment]
> Ctrl+M seems to be working in the app only when you open an expo app in the background:
> 
> 1. Open avd.
> 2. Run your app from expo-cli using Run on Android device/emulator.
> 3. Open expo app in the background.
> 4. Go back to your application.
> 5. Click Ctrl+m.
> 6. Developer menu opens.
> 
> Tested on: expo 37.0.0sdk, android emulator (running pixel 3xl with android 10).

Thx a lot man, this really works for me!

**Comment by cruzach** [comment]
Hm, even without the Expo Client app open in the background, CMD+M is working for me 🤔 

Closing since this is resolved

**Comment by mbyrne00** [comment]
Still happening

**Comment by EmmanuelTheCoder** [comment]
I'm having same experience. `ctrl + M` isn't working.

**Comment by DanielJaron** [comment]
When running the application from terminal one of the options is pressing m for toggling menu, which does the trick.

![image](https://user-images.githubusercontent.com/41025334/214545857-8c056abb-51ac-4de6-bcf0-4fc32caf87a0.png)

**Comment by Jhon-Idrovo** [comment]
> When running the application from terminal one of the options is pressing m for toggling menu, which does the trick.
> 
> ![image](https://user-images.githubusercontent.com/41025334/214545857-8c056abb-51ac-4de6-bcf0-4fc32caf87a0.png)

I tried this. It says "Toggling dev menu" but nothing happens
