### ISSUE TITLE
Audio.Sound.create: Could not get the local file path after play the Audio URL online ?

### ISSUE THREAD

**Issue by inspireui** [expo/expo#774]
Hi, could i know how to get the local file path after played the online URL, i would like to get it as using for next loading without downloading again?

I have looked into the document or Expo source code but could not find the callback function to handle for this feature, please help! It's ready useful for the app.

**Comment by ide** [comment]
You could use the Expo Asset API to download the sound file separately first, and then use the FileSystem API to move it somewhere permanent. (Docs are all here: https://docs.expo.io, use the search box to find each API's doc page.)

**Comment by inspireui** [comment]
Thank you!
