### ISSUE TITLE
React native: TypeError: null is not an object (evaluating 'SplashScreen.preventAutoHide')

### ISSUE THREAD

**Issue by zeesulehria** [expo/expo#7740]
## 🐛 Bug Report
Getting this error after upgrading to latest expo,  ejecting the project and run it from android-studio

![WhatsApp Image 2020-04-08 at 7 01 08 PM](https://user-images.githubusercontent.com/15047417/78800440-de6e0000-79d4-11ea-91a1-46a3bae9b22b.jpeg)

### Environment
expo": "~37.0.3",
    "expo-analytics-segment": "^8.1.0",
    "expo-asset": "^8.1.4",
    "expo-av": "^8.1.0",
    "expo-constants": "^9.0.0",
    "expo-font": "^8.1.0",
    "expo-image-picker": "^8.1.0",
    "expo-permissions": "^8.1.0",
    "expo-splash-screen": "^0.2.0",
    "expo-updates": "~0.1.0",
    "expo-video-player": "^1.5.7",
    "expokit": "^37.0.0",
    "native-base": "2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",

**Comment by Andruschenko** [comment]
I get the same issue when trying to run on `iOS` or `Android`. Another user on StackOverflow also posted the same issue: https://stackoverflow.com/questions/61067070/

Eject an Expo project with Expo version `37` and then try to run it. No `SplashScreen` is imported anywhere in the App.

**Comment by cruzach** [comment]
As the answer states in the SO link shared above, `AppLoading` is not available in the bare workflow, 

To achieve the same behavior in AppLoading, all you need to do is to follow the examples section in [expo-splash-screen README](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#expo-splash-screen). Using the SplashScreen API directly gives you more control over what's happening in your app

**Comment by Andruschenko** [comment]
The SO link doesn't explicitly mention the `AppLoading` component. I added an answer there to clarify it.
