### ISSUE TITLE
SecureStore isn't working in web

### ISSUE THREAD

**Issue by Mahesha-Bhat** [expo/expo#7744]
Hi,
I am using SecureStore to store the token, it works in android and ios. but when I execute in web its unable to store in localstorage.so request is failing.
when I use AsyncStorage it works in web as well.
please help to solve this problem.

**Comment by brentvatne** [comment]
hi there!

SecureStore isn't supported on web, see the compatibility table on the top of the docs page: https://docs.expo.io/versions/latest/sdk/securestore/

you can open a feature request for it at https://expo.canny.io/feature-requests

**Comment by EvanBacon** [comment]
Unfortunately secure store API isn't available on web, we won't be polyfilling this package because there is no secure way to store values in the browser. If this changes we'll be happy to work on this.

**Comment by Mahesha-Bhat** [comment]
ok. thank you for the reply.

**Comment by Mahesha-Bhat** [comment]
hi,
when i used camelcase properties on react components, I am getting below error.
"React does not recognize the `propertyType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `autocompletetype` instead. If you accidentally passed it from a parent component, remove it from the DOM element"
because can you help me solve this error.

**Comment by brentvatne** [comment]
that is not really in the scope of questions we answer on the issues. issues on expo/expo are for bug reports with expo. maybe try https://stackoverflow.com/questions/49358560/react-wrapper-react-does-not-recognize-the-staticcontext-prop-on-a-dom-elemen

**Comment by eveningkid** [comment]
You can simply use AsyncStorage instead, have a `storage.native.js` file using `SecureStore` and `storage.js` which serves as a fallback for web:
```js
// storage.native.js
import * as SecureStore from 'expo-secure-store';

function getItem(key) {
  return SecureStore.getItemAsync(key);
}

// storage.js
import { AsyncStorage } from 'react-native';

function getItem(key) {
  return AsyncStorage.getItem(key);
}
```

**Comment by lanman2000** [comment]
> You can simply use AsyncStorage instead, have a `storage.native.js` file using `SecureStore` and `storage.js` which serves as a fallback for web:
> 
> ```js
> // storage.native.js
> import * as SecureStore from 'expo-secure-store';
> 
> function getItem(key) {
>   return SecureStore.getItemAsync(key);
> }
> 
> // storage.js
> import { AsyncStorage } from 'react-native';
> 
> function getItem(key) {
>   return AsyncStorage.getItem(key);
> }
> ```

I used this approach just now and it works like a charm. Thanks @eveningkid

**Comment by majiyd** [comment]
@sean-m-oleary would `await SecureStore.setItemAsync(key, value);` work on web?

**Comment by BossBele** [comment]
> 

No, SecureStore.setItemAsync and SecureStore, in general, does not work on web @majiyd

**Comment by majiyd** [comment]
Thank you

**Comment by RamirezErnesto** [comment]
My app currently uses the locally stored JWT to make certain API calls to protected endpoints. SecureStore is great for iOS and Android, but what would be a secure alternative for doing this on the web?

My understanding is that using AsyncStorage to store a JWT is not a good practice because it is unencrypted. Is there a secure workaround to do this in AsyncStorage, Redux, or something else?

**Comment by skibaalex** [comment]
@RamirezErnesto have you figured out a solution?

**Comment by brunoprietog** [comment]
I have the same doubt, where can we store tokens on the web securely?

**Comment by nikkwong** [comment]
The correct solution is probably to use cookies on the web (many JWT libraries support reading the token from cookies rather than headers). This will however complicate your logic; meaning you'll need CSRF protection on web but not mobile. Also, it seems like you are potentially open to XSS vulnerabilities by using `SecureStore` on the native platforms if you are not careful.

**Comment by stayingcozy** [comment]
Another option to securely save information through encryption on web applications is react-secure-storage. You can setup an if condition based on Platform similar to kuchaguangjie's code above but instead of AsyncStorage for web use react-secure-storage.
