### ISSUE TITLE
[docs] Expo Audio Recording Format for WAV [Android]

### ISSUE THREAD

**Issue by ronaiza-cardoso** [expo/expo#7746]
Hi, I need the combination of a working setting for .wav file in android. I see this question on the forum but no one responded since 2017.

https://forums.expo.io/t/expo-audio-recording-format-for-wav/33448

**Comment by cruzach** [comment]
Could you provide more context around what you're looking to do? Maybe an example snack of what you're looking to do in a case where it works // doesn't work. 

Closing this since we keep github reserved for bug reports (but I'm happy to try and help if you can provide more info)

**Comment by rodrigochapeta** [comment]
Hi @ronaiza-cardoso did you ever find a way?

**Comment by JesseAyegba** [comment]
Yeah. @ronaiza-cardoso did you find a solution to your problem? Because I'm having a similar issue.
