### ISSUE TITLE
Internet connection interruption during download

### ISSUE THREAD

**Issue by mkhaledche** [expo/expo#7755]
Hi
I was asking if there is a way to handle interruption of internet connection while using download async function. I was testing the download function, it worked well however I had a problem in the connection while downloading, I received an error (not a promise rejection) "Unable to download from:". I just want to know if there is something to deal with connection interruption as I didn't see anything in the documentation. I think pauseAsync deals with volunatary pause rather than fixed pause, doesn't it?
![IMG-0006](https://user-images.githubusercontent.com/33604455/78848814-227ff580-7a13-11ea-8daa-245ed8b8b6da.PNG)

**Comment by cruzach** [comment]
You can just `catch` the error, and provide logic to notify the user that the download couldn't be completed. You can use the [`netinfo`](https://docs.expo.io/versions/latest/sdk/netinfo/) or [`expo-network`](https://docs.expo.io/versions/latest/sdk/network/) to monitor what kind of connection the user has-
