### ISSUE TITLE
Granularize `FileSystem` read/write permissions per-path

### ISSUE THREAD

**Issue by nikki93** [expo/expo#776]
Right now `Expo.FileSystem` calls are only allowed on `file://` URIs that are given both read and write access for the current application. This prevents making calls like, for example, "copy <image from React Native's `CameraRoll`> to <location in `Expo.FileSystem.documentDirectory`>" since React Native's `CameraRoll` returns URIs that are outside the bounds of the current access that `FileSystem` provides -- in this case we could have that location just be readable but not writeable.

Moving ahead we could expand the URI -> yes/no permission mapping to URI -> read/write/both permissions. This may also get at https://github.com/expo/expo/issues/767 since we could have the root directory of the filesystem itself have read access only with write access to create files inside but not write access to delete the root itself.

**Comment by brentvatne** [comment]
this snack should work once this is resolved: https://snack.expo.io/Bk25nLCAb

**Comment by kaulsalil88** [comment]
i know this is very late in the day but i have the following configuration in my package.json
"expo": "^21.0.0",
"expo-env": "^1.1.0",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
 . On android I need to create a sub folder  and able to use both downloadAsync and createDownloadResumable . On IOS when using createDownloadResumable i am getting the following error on ios :
[EXFileSystem _downloadResumableCreateSessionWithUrl:withScopedPath:withUUID:withOptions:withResumeData:withResolver:withRejecter:]_block_invoke.298 + 418',
     '3   hcl-concerts                        0x000000010186d5cb -[EXDownloadDelegate URLSession:downloadTask:didFinishDownloadingToURL:] + 155',
     '4   CFNetwork                           0x000000010c0d20b2 __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke + 38',
 Do I need to upgrade my expo version , want to avoid that as the release date is very close . Please help .

**Comment by Rutulpatel7077** [comment]
@nikki93 is FileSystem is able to access file:///private ?

**Comment by jarodsmk** [comment]
Coming back to this issue, and possibly these too:
https://github.com/expo/expo/issues/2094
https://github.com/expo/expo/issues/767

The `FileSystem.downloadAsync` function seems to run successfully, however the desired file does not appear in the specified directory.

Take this modified snack as an example:
https://snack.expo.io/@jarodsmk/unnamed-snack

Notice that the status response is 200 for the download, the file URI is returned too, but the file can't be accessed by the user when attempting to navigate to it using their own file explorer
