### ISSUE TITLE
WebBrowser.openAuthSessionAsync and related calls skip user input even when browser session expired

### ISSUE THREAD

**Issue by desnor** [expo/expo#7763]
### Environment

  Expo CLI 3.17.18 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v13.6.0/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.17.18

Happening on iOS in local development and published release (expo managed). Haven't tried on standalone build yet.

### Steps to Reproduce
This issue happens whether using `AuthSession.startAsync`, `AppAuth.authAsync` or `WebBrowser.openAuthSessionAsync`
 user presses 'sign in' button, (app calls one of the above methods to kick start authentication session with a Salesforce oauth provider)
1. user enters credentials successfully
2. app goes through oauth redirects and returns user to our app and we get our access token.
3. user presses 'sign out' button (app calls `revoke` endpoint for token, then calls server endpoint to delete any browser cookie sessions for given account reference)
4. app navigates to sign in screen
5. user presses 'sign in' again (app calls the same method from above to start the authentication session with Salesforce oauth provider again)
6. instead of opening the sign in page, the app redirects itself back with an access token as if the user had successfully entered their credentials, even though any cookies/session data the browser stores should be invalid and necessitate a sign in.

### Expected Behavior

steps 1 - 5 are all as expected. Step six should be
6. app redirects to Salesforce oauth provider sign in page, in unauthenticated state (ie no cookie or session data that is valid)
7. user is required to re-enter their credentials
8. oauth flow takes over and redirects the user into the app if the credentials were correct.

### Actual Behavior
as per initial steps where the user is not even asked to enter their credentials (step 6):
6. instead of opening the sign in page, the app redirects itself back with an access token as if the user had successfully entered their credentials, even though any cookies/session data the browser stores should be invalid and necessitate a sign in.

### Reproducible Demo

The code is in a private repo so I can't share details of it, but it's a very standard oauth flow, and seeing it's happening in all three of the method calls from the top suggests to me that it may be due to something in the `WebBrowser.openAuthSessionAsync` implementation. I have seen on the [apple developer docs that SFAuthenticationSession has been deprecated](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) in favour of [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession). My understanding is that this (SFAuthenticationSession) is the browser used by expo's WebBrowser and the wrappers mentioned above (`AppAuth` and `AuthSession`) for the oauth interactions. I also see that it mentions it's for a one-time login, which perhaps explains why it would hold onto any session data and jump to the conclusion of re-authenticating without directly seeking credentials from the user?

### Notes

Essentially this is making it impossible for a user to sign out of our app, because the system browser that we don't have control over is keeping track of their authentication _despite_ the session value no longer being valid against the server.

I've seen other people looking to find ways to clear cookies from the system browser, which may be what this issue relates to.

I would like users to be able to sign out, and then when they sign back in again they should have to enter their credentials again.

**Comment by cruzach** [comment]
If you **do not** want to share cookies with the OS system browser, you can use [`openBrowserAsync`](https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowseropenbrowserasyncurl) (although it's usually considered best practice to not make users re-enter their login credentials every time)

**Comment by desnor** [comment]
Hi @cruzach thanks for your response, though the issue isn't the fact that the cookies are being shared, but rather that a session related to an invalidated cookie is still somehow able to pass through the provided authentication flow. I agree that it's not good practice to require a user to enter their credentials every time they open the app - but if a user explicitly signs out, and we revoke their session token and invalidate any cookies related to it, I would expect the user to have to re-enter their credentials the next time they try and sign in?

I feel like this isn't an unreasonable expectation to have for an authentication flow, but as it appears to be happening somewhere inside the `expo` / native implementation, I'm not sure exactly why it's happening, but would love to be able to find a way to resolve it so that we can be confident of a session ending when we kill it. Can this issue please be reopened? I feel like it must have affected other people too

**Comment by VladCherniavsky** [comment]
Hi @desnor, did your solve that issue ? I have the same one so it is really interesting what options I have

**Comment by desnor** [comment]
Hi @VladCherniavsky sort of - the only way we were able to be certain of ending the native browser session was by opening up the web app's signout page via the `WebBrowser.openAuthSessionAsync` and then redirecting from the sign out page back into the app. This is a pretty confusing experience for users, because when they press the **sign out** button it pops up the iOS modal saying `XXX would like to sign in via Salesforce` . But at least we can guarantee the destruction of the cookie.

In contract on Android it works find because the browser is the same between an auth session and a regular web browser session when called from `expo`.

Not sure whether you'd really want to use the same implementation as we have, but until there's a way to be able to clear cookies from the native auth browser on iOS while still inside `expo` I'm not sure what alternative there is.

**Comment by VladCherniavsky** [comment]
@desnor thanks for the reply. 

I my case `WebBrowser.openAuthSessionAsync ` call doesn't destruct cookie.
Do I need to set any specific cookie on backend side for `api/logout`  endpoint ?

**Comment by desnor** [comment]
@VladCherniavsky yeah you'll need to implement some logic to handle
removing the cookie on the site that you take the app to when you call
WebBrowser.openAuthSessionAsync  . What I did was just remove the
particular cookie that was being persisted before redirecting via a deep
link back into the app. The user was then taken back to the sign in screen
in our app, and when they next want to sign in (again using the  WebBrowser.
openAuthSessionAsync ) the cookie is no longer present and they are
required to enter their credentials again. Does that give you a better
picture of it?

**Comment by muninderkaur06** [comment]
I'm using openAuthSessionAsync function, my question is that I want the user to directly be logged in to their website using in-app browser like Twitter does. So, I'm setting cookies but still it is not being logged out. What am I doing wrong?

```
  const forumDomain = '.webtoolbox.apple.com'; // Forum root domain
  const forumBaseUrl = 'https://webtoolbox.apple.com'; // Forum base URL
  const forumTestUrl = `${forumBaseUrl}/test-the-forum`; // Target forum page
  
const [isCookiesSet, setIsCookiesSet] = React.useState(false);

React.useEffect(() => {
  const setLoginCookies = async () => {
    const cookies = {
      userid: '246888805', // Replace with the actual user ID
      pw: 'f787878e0', // Replace with the actual password hash
      username: 'username', // Replace with the actual username
    };

    try {
      // Set cookies for the forum domain
      await CookieManager.set(`https://${forumDomain}`, {
        name: 'userid',
        value: cookies.userid,
        domain: forumDomain,
        path: '/',
        version: '1',
      });

      await CookieManager.set(`https://${forumDomain}`, {
        name: 'pw',
        value: cookies.pw,
        domain: forumDomain,
        path: '/',
        version: '1',
      });

      await CookieManager.set(`https://${forumDomain}`, {
        name: 'username',
        value: cookies.username,
        domain: forumDomain,
        path: '/',
        version: '1',
      });

      console.log('Cookies set successfully');
      setIsCookiesSet(true); // Signal that cookies are set
    } catch (error) {
      console.error('Failed to set cookies:', error);
    }
  };

  setLoginCookies();
}, []);

const openForumLink = async () => {
  if (isCookiesSet) {
    try {
      await WebBrowser.openAuthSessionAsync(forumBaseUrl, forumTestUrl);
    } catch (error) {
      console.error('Error opening forum link:', error);
    }
  }
};
```
