### ISSUE TITLE
[expo-splash-screen] cli command hangs forever and does not create iOS splash screen

### ISSUE THREAD

**Issue by Andruschenko** [expo/expo#7767]
### Environment

Output of `expo diagnostics`

```
Expo CLI 3.17.18 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.6 => 37.0.6
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-navigation: ^4.0.10 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.17.18
```

App target: iOS Simulator

### Steps to Reproduce

1. Eject from the managed workflow with `expo eject`
2. Install new version `0.2.0` of `expo-splash-screen`, i.e. `yarn add expo-splash-screen`
3. Since you still have no splash screens in place, run e.g. 

  ```
  yarn expo-splash-screen -r "cover" "#E41620" assets/images/splash.png
  ```

### Expected Behavior

iOS and Android splash screens get created and the command stops execution.

### Actual Behavior

The Android splash screens will be created by the iOS ones won't and the command hangs and never ends.

What's interesting: When you add the `-p "ios"` flag, it does create the splash screens for iOS, i.e. with

```
yarn expo-splash-screen -p "ios" -r "cover" "#E41620" assets/images/splash.png
```

So there might be an issue with the default of running it for both platforms if no `-p` flag is specified.

### Reproducible Demo

A snack is not enough here because the issue is with the `expo-splash-screen` cli command.

To reproduce, initialize a new Typescript Expo project, eject and reproduce as described above.

**Comment by cruzach** [comment]
Interesting, thanks for reporting this

It also seems to work correctly if you pass the `-p all` flag

**Comment by Andruschenko** [comment]
@cruzach Yes, I got the `EEXIST: file already exists` error, but then I just ran the command again and it worked (well, just for Android and hanging as described above) if I remember correctly.

In another attempt after I added splash-screens manually to iOS I rightfully got he error for the iOS side.

**Comment by Andruschenko** [comment]
The android command has many more problems and the app can't build after running `expo-splash-screen`. The command only generates a small set of the requires files, some wrong ones and the manual docs for setting the Splash Screen on Android also don't work. 
I got it working by setting it up manually and will open a PR to update the docs.

There are several issues with the command, e.g. [in these lines](https://github.com/expo/expo/blob/a9160d7c02c59c0c25cafb9811eb7589cc781a2a/packages/expo-splash-screen-command/bin/configureAndroidSplashScreen.js#L166-L169) I believe an `onCreate` function is expected to already be there, but it isn't. Also `Bundle` has to be imported etc. I think this is probably the reason why it hangs.

In the PR for the docs update the necessary changes will become evident. I didn't create many CLIs yet, so I'm not sure I can do all the changes necessary in `configureAndroidSplashScreen.js` but I could give it a try to learn how to do such things.

**Comment by cruzach** [comment]
Yeah, sounds good! Even a docs PR that makes clear what steps are missing is helpful 😄

**Comment by brentvatne** [comment]
as far as i can tell this is resolved.

if you initialize a bare project with `expo init` then run `yarn add expo-splash-screen` and then add a splash.png file and then run `yarn expo-splash-screen -r "cover" "#0a0234" splash.png` it works as expected.

to get the fix, uninstall expo-splash-screen and reinstall it, this will pull in the latest version of the configuration command.

if you encounter another error with this command please create a new issue with a specific description of what is wrong and how to reproduce, thanks!
