### ISSUE TITLE
getExpoPushTokenAsync never resolves

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#7771]
### Environment

  Expo CLI 3.17.18 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Users\hans\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.3 - C:\Program Files\nodejs\npm.CMD

Only tested on Android.

### Steps to Reproduce

I followed the steps in this comment [https://github.com/expo/expo/issues/7606#issuecomment-608604123](https://github.com/expo/expo/issues/7606#issuecomment-608604123), but I don't get a token in the logs.  
I hoped this would fix my issue, because then my original app would probably have the same fix.

### Expected Behavior

Get the push token

### Actual Behavior

No push token

### Reproducible Demo

No demo needed. Followed the steps [here](https://github.com/expo/expo/issues/7606#issuecomment-608604123).

```
#package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
  "private": true
}

```

**Comment by Vikka0157** [comment]
I m also facing the same things
It's a bug 
Never gonna happen when I use fcm

**Comment by awinograd** [comment]
Check the pinned issues:

https://github.com/expo/expo/issues/7673
https://github.com/expo/expo/issues/7653

**Comment by sjchmiela** [comment]
Hey all, sorry for the mishap, it looks like something went wrong on our side and we had to revert _latest_ Android Expo Client version to 2.15.0, which contains the bug described. The 2.15.1 is being uploaded and it will soon be available to install with `expo client:install:android`.

The issue should not appear on Expo Client 2.15.1. If you experience it, ensure that Expo Client, shows "Client version: 2.15.1" in Home, on Projects tab. If it shows an older version, try installing the latest version with `expo client:install:android`.

Let me close this issue tentatively and move the discussion to https://github.com/expo/expo/issues/7673.

**Comment by hanselsen** [comment]
Awesome. It was unclear to me that I had to run `expo client:install:android`.
I get a token now.
