### ISSUE TITLE
[docs] No native ExpoFirebaseCore module found with firebase-recaptcha

### ISSUE THREAD

**Issue by Infinitism** [expo/expo#7781]
[https://docs.expo.io/versions/latest/sdk/firebase-recaptcha/]

I followed the steps described in this doc to set up the phone auth but ran into the issue of "ExpoFirebaseCore module not found, are you sure the expo-firebase-core module is linked properly?"

I installed the expo-firebase-core package too but still ran into this error. How to fix it?

**Comment by rphlmr** [comment]
Did you install firebase too ?
This documentation is incomplete and a pull request is on the way to be more complete.
https://github.com/expo/expo/pull/7773

**Comment by Infinitism** [comment]
Yeah, I have. Like from before. Should I install it again? I am trying to add this feature to an existing project that didn't have this error before.

**Comment by rphlmr** [comment]
I just finish trying making phone auth ^^.

I put here what didn't works at the first try :
https://github.com/expo/expo/issues/7725

I think you can ignore ExpoFirebaseCore installation for phone auth.

This is a quick snippet of my code (custom text input, so, adapt ;) ) : 

```
import * as firebase from "firebase/app";
import "firebase/auth";
import {
  FirebaseRecaptchaVerifierModal,
  FirebaseAuthApplicationVerifier
} from "expo-firebase-recaptcha";



// from firebase console (web project to have the authDomain key)
const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: ""
};

firebase.initializeApp(firebaseConfig);

function LoginScreen() {
  const [phoneNumber, setPhoneNumber] = useState("");
  const [verificationCode, setVerificationCode] = useState("");
  const [verificationId, setVerificationId] = useState("");
  const recaptchaVerifier = useRef(null);

  const onPressSendVerificationCode = async () => {
    const phoneProvider = new firebase.auth.PhoneAuthProvider();

    console.log(recaptchaVerifier);
    const verificationId = await phoneProvider.verifyPhoneNumber(
      `+33${phoneNumber}`, // don't forget international id before phone number
      recaptchaVerifier.current
    );

    console.log("verificationId", verificationId);
    setVerificationId(verificationId);
  };

  return (
    <ScrollView
      style={{
        width: "100%",
        backgroundColor: "#F6F6F6"
      }}
    >
      <View style={{ width: "100%", flex: 1, paddingHorizontal: 30 }}>
        <Title>Login</Title>
        <FirebaseRecaptchaVerifierModal
          ref={recaptchaVerifier}
          firebaseConfig={firebase.app().options}
        />
        <TextInputWithLabel
          label="Phone Number"
          onChangeText={setPhoneNumber}
          value={phoneNumber}
          type="phone-pad"
        />

        <Button onPress={onPressSendVerificationCode} mode="contained">
          Send code
        </Button>

        <TextInputWithLabel
          label="Code de vérification"
          type="phone-pad"
          onChangeText={setVerificationCode}
          value={verificationCode}
        />

        <Button
          onPress={() => {
            console.log(phoneNumber);
            console.log(verificationId);
            console.log(verificationCode);
          }}
          mode="contained"
        >
          Validate
        </Button>
      </View>
    </ScrollView>
  );
}
```

**Comment by Infinitism** [comment]
I tried installing firebase again and this still throws the error. Like I am able to successfully login using the sms verification and all. Just that this warning keeps popping up for some reason. How do we solve the linking issue?

Also, does your text message contain the url of firebase.com instead of the app name?

**Comment by rphlmr** [comment]
Try rm rf node_modules and npm install, in case of.

I change the authDomain to something custom (my website) and the url in the sms is now my website :)

**Comment by IjzerenHein** [comment]
> I installed the expo-firebase-core package too but still ran into this error. How to fix it?

Which Client/SDK version are you using? This library requires that you use SDK 37.

**Comment by Infinitism** [comment]
Upgrading the SDK fixed it for me! Thanks:)

**Comment by dankras** [comment]
(for posterity: see "Upgrading Your App" here: https://blog.expo.io/expo-sdk-37-is-now-available-dd5770f066a6)

**Comment by eklavyadev** [comment]
Still this error in SDK 48, anyway to fix it?

**Comment by Suman-Jaiswal** [comment]
I have this issue in SDK 48: No native ExpoFirebaseCore module found, are you sure the expo-firebase-core module is linked properly?
Please help me.

**Comment by zdennisz** [comment]
This issue is still relevant in Expo SDK 48. Anyone has any idea ?

**Comment by Cleversou1983** [comment]
I'm facing the same issue after upgrading to Expo 48 SDK

**Comment by nanokoko89** [comment]
any update for Expo SDK 48?

**Comment by nanokoko89** [comment]
Expo SDK 48, anyone fixed this?

**Comment by natopedroso** [comment]
Actually is a warning on sdk48 not an error!
But it is annoying

**Comment by quntherdev** [comment]
Same problem error, using SDK 48

**Comment by Xaypanya** [comment]
Same problem

**Comment by stunited-trungdo** [comment]
Same problem, Please reopen this issue

**Comment by xebelge** [comment]
Same problem, please reopen this issue.

**Comment by DarlonHenrique** [comment]
same problem here, SDK 49

**Comment by carlgrefiel** [comment]
can anyone willing to help? same problem sdk 48

**Comment by pedriin1** [comment]
same here - sdk 49

**Comment by maksof-sarwar** [comment]
same here also any one please reopen this thread

**Comment by maksof-sarwar** [comment]
build failed becuase of this core module

**Comment by XSpectrum** [comment]
> urlshortener.at/uWZ79
> 
> fixed for SDK 49 i removed the expo firebase core module and created customize version remove expo-firebase-recapcha and import from custom one

how do you do that please ?

**Comment by maksof-sarwar** [comment]
extract this module to your components direct then import every thing will be same for SDK 49

**Comment by XSpectrum** [comment]
> 

okay let me try it, thanks

**Comment by Spoorthi-creator** [comment]
> urlshortener.at/uWZ79
> 
> fixed for SDK 49 i removed the expo firebase core module and created customize version remove expo-firebase-recapcha and import from custom one

Hello, what do you mean by customize version? Could you please elaborate. I am using SDK 49 and Firebase - 10.2.0

**Comment by maksof-sarwar** [comment]
> ![image](https://github.com/expo/expo/assets/73334558/50e46925-20aa-442f-8c7b-75f31c9ac6e1)

Understand this picture

**Comment by maksof-sarwar** [comment]
Remove expo firebase captch from pkg 
And user this one urlshortener.at/uWZ79

**Comment by Spoorthi-creator** [comment]
> > ![image](https://user-images.githubusercontent.com/73334558/262079698-50e46925-20aa-442f-8c7b-75f31c9ac6e1.png)
> 
> Understand this picture

Will try to , thank you.

**Comment by pedriin1** [comment]
Does this works with Google Analytics?

**Comment by maksof-sarwar** [comment]
Didn't try

**Comment by Cleversou1983** [comment]
> Remove expo firebase captch from pkg
> And user this one urlshortener.at/uWZ79

The transfer is expired... Can you send a new link please? Thanks!

**Comment by maksof-sarwar** [comment]
check this https://github.com/maksof-sarwar/expo-firebase-recaptcha-patch.git

**Comment by ren1suyama** [comment]
Still same issue found on SDK 48

```
 WARN  No native ExpoFirebaseCore module found, are you sure the expo-firebase-core module is linked properly?
 WARN  No native ExpoFirebaseAnalytics module found, are you sure the expo-firebase-analytics's module is linked properly?
 ERROR  Invariant Violation: AsyncStorage has been removed from react-native core. It can now be installed and imported from '@react-native-async-storage/async-storage' instead of 'react-native'. See https://github.com/react-native-async-storage/async-storage, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by maksof-sarwar** [comment]
The patch not depend on firebase core module
Are you using javascript or typescript?
Also use async storage from correct path

**Comment by ren1suyama** [comment]
> The patch not depend on firebase core module Are you using javascript or typescript? Also use async storage from correct path

I'm using TypeScript.

I managed to solve the `WARN` issues by not using `expo-firebase-*` but using `React Native Firebase`.
On the other hand, regarding these issues, I was using Expo Go to examine my app.

```
ERROR  Invariant Violation: AsyncStorage has been removed from react-native core. It can now be installed and imported from '@react-native-async-storage/async-storage' instead of 'react-native'. See https://github.com/react-native-async-storage/async-storage, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

It seems I have to build Dev env instead to solve this problem. Thanks!

**Comment by awarely-alex** [comment]
Besides the annoying warning, I also end up with an error on Android builds with Expo 49. Has anyone run into that and resolved it? 

`
A problem occurred evaluating project ':expo-firebase-core'.
> Could not set unknown property 'classifier' for task ':expo-firebase-core:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.
`
(I guess it wouldn't be a problem with the custom version, so I'll give that a try next - thanks @maksof-sarwar!)

**Comment by Shiv-2712** [comment]
I am unable to receive otp

**Comment by maksof-sarwar** [comment]
@Shiv-2712  may be subscription issue attach right credential to client

**Comment by maksof-sarwar** [comment]
drop start if this was helpful thank you

**Comment by Shiv-2712** [comment]
Start

**Comment by Salman12345a** [comment]
can try this by converting whole code into js.

**Comment by Salman12345a** [comment]
?

**Comment by maksof-sarwar** [comment]
> can try this by converting whole code into js.

Yes just remove type annotation

**Comment by maksof-sarwar** [comment]
> Thank you @maksof-sarwar, your fix worked! I have just one question though, do we need to add the part about `This app is protected by reCAPTCHA and the Google Privacy Policy, etc...` to use Google's reCAPTCHA for production, or did you just add that part to be extra nice?

Yes you can disable recaptcha by using attempinvisible props on recaptcha modal.
Btw i will release optimized version of this code on npm in future

**Comment by maksof-sarwar** [comment]
https://www.npmjs.com/package/@itzsunny/firebase-login
update and optimized version of firebase login

**Comment by JMRMEDEV** [comment]
Hey guys, I created a decent patch to solve the issue, in case someone wants to follow that approach. I originally posted the solution on [**StackOverflow**](https://stackoverflow.com/a/77623727/11123993).

I have lost my mind trying to get rid of that warning on the last days, without losing the benefits and features that `expo-firebase-recaptcha` provides. What I ended up doing is creating a **patch** with `yarn v2+` (I have version 4).

Here is the patch that does not use `expo-firebase-core` anymore:

https://gist.github.com/JMRMEDEV/7d18e354c320e463001d2d2a73218b8f

Follow these steps:

- Have `yarn` version `2` or above (I use `4.0.2`).
- Have `expo-constants` package in your `node-modules`. If you haven't done already, add it to your project.
- Create this directory in the root of your project (if you don't have already): `.yarn\patches`.
- Inside of `.yarn\patches`, create a file called `expo-firebase-recaptcha-npm-2.3.1-6b374029cd.patch` (I guess you can rename it as you please, as long as you reference it in your `package.json` and fill it with the content of https://gist.github.com/JMRMEDEV/7d18e354c320e463001d2d2a73218b8f.
- On your `package.json` reference the package from the patch: `"expo-firebase-recaptcha": "patch:expo-firebase-recaptcha@npm%3A2.3.1#~/.yarn/patches/expo-firebase-recaptcha-npm-2.3.1-6b374029cd.patch"`
- Perform `yarn install` on your project once more.

And vualá, you should have got rid of the annoying warning and keep the original package functionality. Hope it helps!

**Comment by bt-devapps** [comment]
> https://www.npmjs.com/package/@itzsunny/firebase-login update and optimized version of firebase login

Hi,
I am new to react-native and I would like to use recaptcha feature for otp with firebase within expo/react-native. Can you please post a fully-working example with your patch to avoid the warning about "No native ExpoFirebaseCore module found, are you sure the expo-firebase-core module is linked properly?". 

I would really appreciate if you could post a full example including your "useFirebaseLogin"  and recaptcha within a react component? I would like to include this otp feature within my app. 
Thanks

**Comment by maksof-sarwar** [comment]
Sure tomorrow i will upload example code
And also i will remove expo core module from 
useFirebaseLogin hook

**Comment by maksof-sarwar** [comment]
const {recaptcha,recaptchaBanner,sendOtp,verifyOtp} = useFirebaseLogin({auth: /** auth instance from firebase */,firebaseConfig:/** firebase config */});

// for sending otp to phone number 
const verificationId = await sendOtp('+92XXXXXXXX')
// verify otp
verifyOtp('verification Id','XXXXX')


recaptcha // firebase recpatch element 

expo-core-module remove
npm i @itzsunny/firebase-login@latest

**Comment by bt-devapps** [comment]
Hi,
Thanks for this example. 
However, can you please post a full example in a React component and the all the firebase modules that should be imported in conjunction with your hook ?
In fact, I don't understand how I can include "recaptcha" from your hook in the return statement of the React-Native component?
What does "XXXXX" represent in verifyOtp?

**Comment by bt-devapps** [comment]
Never mind, I got it working !!! 
Thanks so much :)

PS : But, still you may still post a full example within a component for beginners; that could be very helpful.

**Comment by Shiv-2712** [comment]
Hi everyone,
Please pardon me for this I am looking for job right now to work with as a MERN Stack or LAMP stack developer my current job doesn't pay enough so that I can survive. Please help me with a refferal and provide your temp mail id so that I can share my profile with you.

**Comment by felipemelendez** [comment]
Hi @maksof-sarwar, after completing my project I ran my build and now I'm getting this error: Build input file cannot be found: '/node_modules/@react-native-google-signin/google-signin/expo/ios/ExpoAdapterGoogleSignIn/GoogleSignInAppDelegate.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

The only google signing method that I am using is related to this phone authentication along with your patch, any ideas why I might be getting this error? Are we supposed to install anything else besides webview to enable this patch?

Thanks in advanced for any insight shared

**Comment by maksof-sarwar** [comment]
> patch

This module depend on react-native-webview,firebase and react-native itself

**Comment by bajajerk** [comment]
any updates?

**Comment by skezu** [comment]
Yeah so I struggled too but thanks to my man's patch it works perfectly fine ! So For anyone who probably is a beginner or whatever here's a simple working implementation example. I hop it helps 😃 :
`React Native v0.72.6`, `Node v20.10.0`, `Expo 49` in `javascript`, `Yarn v4.0.2` ; I am using `react-native-rapi-ui` components so you might have to use different components, but in this way you know how to call the functions etc... :

```js
import ...
// import your firebaseConfig
import { useFirebaseLogin } from "@itzsunny/firebase-login";
import { getAuth, signInWithCredential } from "firebase/auth";

// This is my Login.js page
export default function ({ navigation }) {
  const auth = getAuth();
  const [verificationId, setVerificationID] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
 // Recaptcha Patch
  const {recaptcha,recaptchaBanner,sendOtp,verifyOtp} = useFirebaseLogin(
    {
        auth: auth,
        firebaseConfig: firebaseConfig
    }
    );
const attemptInvisibleVerification = false;

// Phone auth
  const handleSendVerificationCode = async () => {
    try {
      const correctPhoneNumber = `+${pickerValue}${phoneNumber}`; // doesnt matter how you do it you need a +... format
      const verificationId = await sendOtp(correctPhoneNumber)
      setVerificationID(verificationId); // set the verification id
    } catch (error) {
      // show the error or whatever you want
    } finally {
      // do something; not that important
    }
  };

  const handleVerifyVerificationCode = async () => {
    try {
      const credential = await verifyOtp(verificationId,verificationCode);
      await signInWithCredential(auth, credential); // verify the credential
    } catch (error) {
     // show the error. or whatever
    } finally {
      // whatever
    }
  }

return ( // here i'll only show the important parts
<KeyboardAvoidingView behavior="height" enabled style={{ flex: 1 }}>
      <Layout>

        {recaptcha}
         ...
            { // show the phone number input field when verification id is not set.
              !verificationId && (
                <View>
                  <Text>Enter your phone number</Text>
                  <View style={{ flexDirection: 'row', marginTop: 7 }}>
                    <View style={{ marginRight: 8, width: '25%'}}>

                    <Picker
                      style={{ marginRight: 8 }}
                      items={nationalPhoneCodes} // ex: [ { label: 'US', value: '+33' } ]
                      value={pickerValue}
                      labelSize="sm"
                      placeholder="Code"
                      onValueChange={(val) => setPickerValue(val)}
                      />
                      </View>
                      <View style={{ flex: 1 }}>
                    <TextInput
                      placeholder='612345678'
                      autoFocus
                      autoCompleteType='tel'
                      keyboardType='phone-pad'
                      textContentType='telephoneNumber'
                      onChangeText={(phoneNumber) => setPhoneNumber(phoneNumber)}
                      />
                      </View>
                  </View>

                  <Button
                    onPress={() => handleSendVerificationCode()}
                    text="Send Verification code"
                    disabled={loading}
                    style={{
                      marginTop: 20,
                    }}
                    //disabled={!phoneNumber}
                  />
                </View>
              )

            }

            { // if verification id exists show the confirm code input field.
              verificationId && (
                <View>
                  <Text>Enter Verification Code</Text>

                  <TextInput
                    editable={!!verificationId}
                    placeholder="123456"
                    onChangeText={setVerificationCode}
                    keyboardType="number-pad"
                  />

                  <Button
                    text="Confirm Verification code"
                    style={{
                      marginTop: 20,
                    }}
                    disabled={!verificationCode}
                    onPress={() => handleVerifyVerificationCode()}
                  />
                </View>
              )
            }

            {attemptInvisibleVerification && {recaptchaBanner}}

... //close tags etc...
)

}
```

**Comment by AronDevpro** [comment]
Any updates with expo 50?

**Comment by maksof-sarwar** [comment]
> Any updates with expo 50?

What type of error are you getting?

**Comment by AronDevpro** [comment]
> > Any updates with expo 50?
> 
> What type of error are you getting?

# npm resolution error report

While resolving: app@1.0.0
Found: react-native@0.73.4
node_modules/react-native
  react-native@"0.73.4" from the root project

Could not resolve dependency:
peer react-native@"^0.72.7" from @itzsunny/firebase-login@0.0.8
node_modules/@itzsunny/firebase-login
  dev @itzsunny/firebase-login@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

i'm getting this

**Comment by maksof-sarwar** [comment]
> > > Any updates with expo 50?
> > 
> > What type of error are you getting?
> 
> # npm resolution error report
> 
> While resolving: app@1.0.0
> Found: react-native@0.73.4
> node_modules/react-native
>   react-native@"0.73.4" from the root project
> 
> Could not resolve dependency:
> peer react-native@"^0.72.7" from @itzsunny/firebase-login@0.0.8
> node_modules/@itzsunny/firebase-login
>   dev @itzsunny/firebase-login@"*" from the root project
> 
> Fix the upstream dependency conflict, or retry
> this command with --force or --legacy-peer-deps
> to accept an incorrect (and potentially broken) dependency resolution.
> 
> i'm getting this

Did you try npm i --force 
or npm i --legacy-peer-deps


Let me know if this work or not so i will add react native@0.73 compatibility

**Comment by AronDevpro** [comment]
> npm i --force

yeah, please add react native@0.73 compatibility.

**Comment by jacobdenture** [comment]
@maksof-sarwar 
I have some issues, i'm using javascript
`const handleSendVerificationCode = async () => {
    try {
      const verificationId = await sendOtp(phoneNumber);
      setVerificationID(verificationId); // set the verification id
    } catch (error) {
      console.log("sending verification failed", error)
    }
  };
  const handleVerifyVerificationCode = async () => {
    try {
      const credential = await verifyOtp(verificationId, verificationCode);
      const result = await signInWithCredential(auth, credential);
      console.log("result", result); // verify the credential
    } catch (error) {
      console.log("otp verification failed", error)
    }
  };`

I'm getting this error "otp verification failed [TypeError: credential._getIdTokenResponse is not a function (it is undefined)]"

how can i fix it?

Also, i want to use attemptInvissible. here is how i implement it.  but it seems not working.

`const attemptInvisibleVerification = true;

  const {recaptcha, sendOtp, verifyOtp} = useFirebaseLogin({
    auth,
    firebaseConfig: app.options,
    modalOption: attemptInvisibleVerification
  });`

can you guide us how to do the attemptInvisible get to work?

**Comment by maksof-sarwar** [comment]
@jacobdenture  @AronDevpro demo code with js and react native version 0.73
[https://github.com/maksof-sarwar/expo-firebase-recaptcha-patch/tree/main/example/demo](link)

**Comment by AronDevpro** [comment]
> @jacobdenture @AronDevpro demo code with js and react native version 0.73 drop a star if helpful [link](https://github.com/maksof-sarwar/expo-firebase-recaptcha-patch/tree/main/example/demo)

still getting the react native version 0.73 error

**Comment by maksof-sarwar** [comment]
in build or in dev?

**Comment by maksof-sarwar** [comment]
> > in build or in dev?
> 
> dev

Just clone above project and try to run it locally
If this also fail so may be node version issue

**Comment by AronDevpro** [comment]
> > > in build or in dev?
> > 
> > 
> > dev
> 
> Just clone above project and try to run it locally If this also fail so may be node version issue

clone works fine.

**Comment by xdrcft8000** [comment]
> Yeah so I struggled too but thanks to my man's patch it works perfectly fine ! So For anyone who probably is a beginner or whatever here's a simple working implementation example. I hop it helps 😃 : `React Native v0.72.6`, `Node v20.10.0`, `Expo 49` in `javascript`, `Yarn v4.0.2` ; I am using `react-native-rapi-ui` components so you might have to use different components, but in this way you know how to call the functions etc... :
> 
> ```js
> import ...
> // import your firebaseConfig
> import { useFirebaseLogin } from "@itzsunny/firebase-login";
> import { getAuth, signInWithCredential } from "firebase/auth";
> 
> // This is my Login.js page
> export default function ({ navigation }) {
>   const auth = getAuth();
>   const [verificationId, setVerificationID] = useState('');
>   const [verificationCode, setVerificationCode] = useState('');
>  // Recaptcha Patch
>   const {recaptcha,recaptchaBanner,sendOtp,verifyOtp} = useFirebaseLogin(
>     {
>         auth: auth,
>         firebaseConfig: firebaseConfig
>     }
>     );
> const attemptInvisibleVerification = false;
> 
> // Phone auth
>   const handleSendVerificationCode = async () => {
>     try {
>       const correctPhoneNumber = `+${pickerValue}${phoneNumber}`; // doesnt matter how you do it you need a +... format
>       const verificationId = await sendOtp(correctPhoneNumber)
>       setVerificationID(verificationId); // set the verification id
>     } catch (error) {
>       // show the error or whatever you want
>     } finally {
>       // do something; not that important
>     }
>   };
> 
>   const handleVerifyVerificationCode = async () => {
>     try {
>       const credential = await verifyOtp(verificationId,verificationCode);
>       await signInWithCredential(auth, credential); // verify the credential
>     } catch (error) {
>      // show the error. or whatever
>     } finally {
>       // whatever
>     }
>   }
> 
> return ( // here i'll only show the important parts
> <KeyboardAvoidingView behavior="height" enabled style={{ flex: 1 }}>
>       <Layout>
> 
>         {recaptcha}
>          ...
>             { // show the phone number input field when verification id is not set.
>               !verificationId && (
>                 <View>
>                   <Text>Enter your phone number</Text>
>                   <View style={{ flexDirection: 'row', marginTop: 7 }}>
>                     <View style={{ marginRight: 8, width: '25%'}}>
> 
>                     <Picker
>                       style={{ marginRight: 8 }}
>                       items={nationalPhoneCodes} // ex: [ { label: 'US', value: '+33' } ]
>                       value={pickerValue}
>                       labelSize="sm"
>                       placeholder="Code"
>                       onValueChange={(val) => setPickerValue(val)}
>                       />
>                       </View>
>                       <View style={{ flex: 1 }}>
>                     <TextInput
>                       placeholder='612345678'
>                       autoFocus
>                       autoCompleteType='tel'
>                       keyboardType='phone-pad'
>                       textContentType='telephoneNumber'
>                       onChangeText={(phoneNumber) => setPhoneNumber(phoneNumber)}
>                       />
>                       </View>
>                   </View>
> 
>                   <Button
>                     onPress={() => handleSendVerificationCode()}
>                     text="Send Verification code"
>                     disabled={loading}
>                     style={{
>                       marginTop: 20,
>                     }}
>                     //disabled={!phoneNumber}
>                   />
>                 </View>
>               )
> 
>             }
> 
>             { // if verification id exists show the confirm code input field.
>               verificationId && (
>                 <View>
>                   <Text>Enter Verification Code</Text>
> 
>                   <TextInput
>                     editable={!!verificationId}
>                     placeholder="123456"
>                     onChangeText={setVerificationCode}
>                     keyboardType="number-pad"
>                   />
> 
>                   <Button
>                     text="Confirm Verification code"
>                     style={{
>                       marginTop: 20,
>                     }}
>                     disabled={!verificationCode}
>                     onPress={() => handleVerifyVerificationCode()}
>                   />
>                 </View>
>               )
>             }
> 
>             {attemptInvisibleVerification && {recaptchaBanner}}
> 
> ... //close tags etc...
> )
> 
> }
> ```

Thanks you're an angel
