### ISSUE TITLE
svg property strokeWidth on Android: react-native-svg-charts

### ISSUE THREAD

**Issue by hani-q** [expo/expo#7790]
### Environment

  Expo CLI 3.17.21 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.1.1 => 4.1.1

Target is Android

### Steps to Reproduce

Om Expo 36 was using progressCircle

    <ProgressCircle
                    animate
                    backgroundColor={colors.shadow5}
                    style={{
                        paddingTop: 20,
                        position: 'absolute',
                        height: 200,
                        width: 200
                    }}
                    strokeWidth={15}
                    progress={this.state.percentage}
                    progressColor={colors.greenDark}
                    startAngle={-Math.PI * 0.7}
                    endAngle={Math.PI * 0.7}
                />

But after Upgrade to SDK 37 get this Java Cast error 

![image](https://user-images.githubusercontent.com/3755330/78951495-09427c00-7adb-11ea-8c04-6454b70f67e8.png)

Just upgraded to expo SDK 37. 

  "dependencies": {
        "expo": "^37.0.0",
        "expo-av": "~8.1.0",
        "expo-constants": "~9.0.0",
        "expo-file-system": "~8.1.0",
        "expo-image-picker": "~8.1.0",
        "expo-linear-gradient": "~8.1.0",
        "expo-location": "~8.1.0",
        "expo-permissions": "~8.1.0",
        "react": "16.9.0",
        "react-dom": "16.9.0",
        "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
        "react-native-svg": "11.0.1",
        "react-native-svg-charts": "^5.3.0",
    },

All used to work fine on expo 36

  "dependencies": {
        "expo": "~36.0.0",
        "expo-av": "~8.0.0",
        "expo-constants": "^8.0.0",
        "expo-file-system": "~8.0.0",
        "expo-image-picker": "^8.0.2",
        "expo-linear-gradient": "~8.0.0",
        "expo-location": "~8.0.0",
        "expo-permissions": "^8.0.0",
        "react": "^16.12.0",
        "react-dom": "~16.9.0",
        "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
        "react-native-svg": "9.13.3",
        "react-native-svg-charts": "^5.3.0"
    },

**Comment by cruzach** [comment]
Hi! It looks like `react-native-svg-charts` might be indirectly supported, if they rely only on `react-native-svg` native code, which would explain why it was working in SDK 36. If you could provide a repro, we can give this a closer look, but I'd double-check to make sure the code is running correctly in a bare RN project, as well (just to rule out the problem being in `react-native-svg-charts`)

**Comment by hani-q** [comment]
> Hi! It looks like `react-native-svg-charts` might be indirectly supported, if they rely only on `react-native-svg` native code, which would explain why it was working in SDK 36. If you could provide a repro, we can give this a closer look, but I'd double-check to make sure the code is running correctly in a bare RN project, as well (just to rule out the problem being in `react-native-svg-charts`)

I manually downgraded to ""react-native-svg": "9.13.3". I do get a warning on expo start of incompatibility. But nothing is breaking for now and all seems good. 

react-native-svg-charts has  "react-native-svg": "^6.2.1" as a peer-dependency

**Comment by hani-q** [comment]
https://snack.expo.io/@haniq313/rsvg-error

**Comment by cruzach** [comment]
That snack doesn't seem to render the ProgressCircle on either SDK 36 nor 37

**Comment by hani-q** [comment]
> That snack doesn't seem to render the ProgressCircle on either SDK 36 nor 37

Sorry style was not set... Updated it now...

strangely it works here on Snack but doesnt work on my env.. 

https://snack.expo.io/@haniq313/rsvg-error

**Comment by cruzach** [comment]
Hm, maybe try removing node modules and package-lock or yarn-lock, reinstalling, then run with `expo start -c`

**Comment by hani-q** [comment]
> Hm, maybe try removing node modules and package-lock or yarn-lock, reinstalling, then run with `expo start -c`

Just did that.... removed node_modules.. removed yarn-lock... install packages again same result 

Android Emulator API 29
![image](https://user-images.githubusercontent.com/3755330/79134129-e0113c80-7db5-11ea-9ae6-6faf54881956.png)

on an Android Device with API 26 get the same as above

On my physical IOS device using the lastest expo app and IOS version  i get this

![image](https://user-images.githubusercontent.com/3755330/79134328-354d4e00-7db6-11ea-8700-5199441fd903.png)

**Comment by cruzach** [comment]
that last screenshot shows an SDK 36 stacktrace, so I'm a little confused- your original report said that this works on SDK 36 but not SDK 37

Also- please test this in a vanilla RN project to ensure the problem is with Expo

**Comment by hani-q** [comment]
> that last screenshot shows an SDK 36 stacktrace, so I'm a little confused- your original report said that this works on SDK 36 but not SDK 37
> 
> Also- please test this in a vanilla RN project to ensure the problem is with Expo

Sorry.. Now i am confused too.. Just started working on expo and RN so please bare with me.. How are you checking the expo version ?

![image](https://user-images.githubusercontent.com/3755330/79134806-f7045e80-7db6-11ea-8022-c87302388a99.png)

These is my project setup ? How is the stack trace from expo 36... Are you suggesting based on the EXPO Client App installed on the Emulator and the Physical Phones ? on the emulator the client is installed by expo itself. on IOS i just checked i am on the latest version from App Store ?

**Comment by cruzach** [comment]
the `expo` dependency is on v37, meaning SDK 37

**Comment by hani-q** [comment]
> the `expo` dependency is on v37, meaning SDK 37

Yes that is correct and that is where i am assuming myself to be.. on SDK 37....

I upgraded last week from 36... So shared in my initial comment that when i was on SDK 36 all was good. But when i upgraded  to expo 37 (using expo upgrade). It changed the "react-native-svg": "9.13.3", to "react-native-svg": "11.0.1". this 11.0.1 version is causing this problem for me in my local setup. If i manually downgrade back to 9.13.3 it works ok but i do get an expo warning for incompatible version when i start.

Strangely on Snack it is not showing the error.


And again you mentioned "that last screenshot shows an SDK 36 stacktrace" ? so want to know what specifically in the stack trace is showing you this ? ABI_36_0_0 line ? asking again because maybe that is the real issue that my Expo clients are still seeing me using SDK 36 ?
