### ISSUE TITLE
Icons not appearing

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#7792]
### Environment
```
  Expo CLI 3.17.21 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Users\hans\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
```

Tested Android only.

### Steps to Reproduce

It started when I upgraded to SDK 37. I was unaware of the issue untill I published it to my release channel. All the icons were not rendered.

I started deleting stuff util I had nothing more than a bare bone app.
I tried `expo upgrade` using the latest expo-cli because it would remove my `node_modules` and `package-lock.json`.
I reset my `build.gradle`.
I reset my `babel.config.js`

It is working when I run `expo start -c`, when I run `expo publish --release-channel staging` it just does not show.
I have the feeling I found all the threads/bug reports that can be found so I'm running out of options here.

### Expected Behavior

Show icons.

### Actual Behavior

No icons

### Reproducible Demo

This is the code I have.
[https://snack.expo.io/@sosvolaris/icons-not-working](https://snack.expo.io/@sosvolaris/icons-not-working)

It is working in this snack, but not when published.

When published:

![photo_2020-04-10_08-54-55](https://user-images.githubusercontent.com/1150323/78970190-0494bc80-7b09-11ea-889c-6fc6ebcaff49.jpg)

**Comment by yohix** [comment]
This is happening for me too!

**Comment by brentvatne** [comment]
- check if you have multiple versions of expo-font in your node_modules
- show us your app.json and metro.config.js

**Comment by yohix** [comment]
@brentvatne Here are some details

<details>
<summary>expo-font's package.json</summary>
<pre>
{
  "_from": "expo-font@~8.1.0",
  "_id": "expo-font@8.1.1",
  "_inBundle": false,
  "_integrity": "sha512-z6008K7YSA7wpJ1mNyG2eSYUhEoFVjdL2uAbwaHFpsqwxDS4tcdKHoWkanIUiEnsjtHK7Uk0ywKJ8MRzmCaklw==",
  "_location": "/expo-font",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "expo-font@~8.1.0",
    "name": "expo-font",
    "escapedName": "expo-font",
    "rawSpec": "~8.1.0",
    "saveSpec": null,
    "fetchSpec": "~8.1.0"
  },
  "_requiredBy": [
    "/expo"
  ],
  "_resolved": "https://registry.npmjs.org/expo-font/-/expo-font-8.1.1.tgz",
  "_shasum": "40de629d7332887bdafae4756741f6979fc0043e",
  "_spec": "expo-font@~8.1.0",
  "_where": "/root/yohix/xpat/node_modules/expo",
  "author": {
    "name": "650 Industries, Inc."
  },
  "bugs": {
    "url": "https://github.com/expo/expo/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "fbjs": "1.0.0",
    "fontfaceobserver": "^2.1.0"
  },
  "deprecated": false,
  "description": "Load fonts at runtime and use them in React Native components.",
  "devDependencies": {
    "expo-module-scripts": "~1.2.0"
  },
  "gitHead": "3ad68bbd9847ebc8a55272c263b17d998a92f64f",
  "homepage": "https://docs.expo.io/versions/latest/sdk/font/",
  "jest": {
    "preset": "expo-module-scripts"
  },
  "keywords": [
    "react-native",
    "expo",
    "font"
  ],
  "license": "MIT",
  "main": "build/Font.js",
  "name": "expo-font",
  "peerDependencies": {
    "react": "*",
    "react-native": "*"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/expo/expo.git",
    "directory": "packages/expo-font"
  },
  "scripts": {
    "build": "expo-module build",
    "clean": "expo-module clean",
    "expo-module": "expo-module",
    "lint": "expo-module lint",
    "prepare": "expo-module prepare",
    "prepublishOnly": "expo-module prepublishOnly",
    "test": "expo-module test"
  },
  "sideEffects": false,
  "types": "build/Font.d.ts",
  "unimodulePeerDependencies": {
    "@unimodules/core": "*",
    "expo-asset": "*",
    "expo-constants": "*",
    "unimodules-font-interface": "*"
  },
  "version": "8.1.1"
}
</pre>
</details>

<details>
<summary>app.json</summary>
<pre>
{
  "expo": {
    "name": "Xpat",
    "slug": "xpat",
    "platforms": [
      "ios",
      "android"
    ],
    "entryPoint": "index.js",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "com.xpat",
      "buildNumber": "1.0.0"
    },
    "android": {
      "package": "com.xpat",
      "versionCode": 1
    }
  }
}
</pre>
</details>

I couldn't find `metro.config.js` file

**Comment by brentvatne** [comment]
@yohix do you use yarn? do you have multiple copies of the expo-font module inside the node_modules directory?

**Comment by yohix** [comment]
@brentvatne I use **NPM**, I have only one copy of **expo-font**

![Screenshot](https://user-images.githubusercontent.com/61746440/79033511-69fdb180-7bcc-11ea-8e2c-50f826ce30f9.png)

**Comment by yohix** [comment]
@brentvatne I just tried using **yarn** but still facing this issue!

**Comment by yohix** [comment]
@brentvatne Also tried `expo upgrade` still didn't work!

Here is the Repo: https://github.com/yohix/xpat-expo

**Comment by brentvatne** [comment]
@yohix - i'm not sure how to do this on windows but on a *nix system or macos: `find node_modules -name expo-font` and see how many results you get.

**Comment by yohix** [comment]
@brentvatne I just got only one.

![Screenshot](https://user-images.githubusercontent.com/61746440/79034514-2f981280-7bd4-11ea-8704-57f09466b880.png)

**Comment by brentvatne** [comment]
@yohix - the problem is that you are using `index.js` as your entry point and not using `registerRootComponent`

change index.js to this:

```js
import {registerRootComponent} from 'expo';
import App from './App';
import {DefaultTheme, Provider as PaperProvider} from 'react-native-paper';

const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#ff7b31',
    accent: 'yellow',
  },
};
console.disableYellowBox = true;
export default function Main() {
  return (
    <PaperProvider theme={theme}>
      <App />
    </PaperProvider>
  );
}

registerRootComponent(App);
```

**Comment by brentvatne** [comment]
@hanselsen - if you can share your repo with me publicly or privately i can help you understand what's going on and to debug it!

**Comment by yohix** [comment]
Wow, Thank you so much @brentvatne :purple_heart: it works for me!

**Comment by hanselsen** [comment]
@brentvatne I created [https://github.com/hanselsen/expoiconissue](https://github.com/hanselsen/expoiconissue) with the exact problem.
`expo start -c` does have icons. `expo publish` has no icons.

**Comment by brentvatne** [comment]
@hanselsen - you have the exact same issue as i showed the fix for as @yohix. update index.js

```
import { registerRootComponent } from 'expo';
import App from './App';

registerRootComponent(App);
```

out of curiosity, how did you end up with this index.js? what steps did you follow to create your project?

**Comment by yohix** [comment]
@brentvatne I just migrated from React Native CLI which has `index.js` by default!

**Comment by brentvatne** [comment]
interesting, what did you do to migrate over? did you follow a guide somewhere?

**Comment by yohix** [comment]
Nope @brentvatne, I just migrated myself!

1. Copied the `src` folder
2. Copied App.js and index.js
3. Copied dependencies from `package.json`
4. Hacked on some dependence issues like `Asyncstorage`, `Vector Icons` etc

Tada :tada:, that's it! It worked!

**Comment by hanselsen** [comment]
@brentvatne thanks for the support. It is working now when I use `expo publish --target managed`

Very weird how I got this setup. I must say, I don't remember it very well, but I think I used `expo init` to create the app. I do remember that I manually removed the iOS folder, since I did not need it.

After a week or so, I migrated using the release blog post from the Expo blog.

What if I now want to build for Android using CI/CD pipelines.. it will just work without the Android folder?

**Comment by brentvatne** [comment]
i don't understand the question 👀

**Comment by hanselsen** [comment]
Alright. Sorry about that hehe. 
I'm having my CI/CD cycle in the managed Expo environment. This is all really great, but the goal is to have an Android app in the store.
Is this possible if you keep using `--target managed`? Or do I have to eject or something at some point?

**Comment by rainst** [comment]
Hi Everyone, I'm sorry to open this thread again but i'm having the same issue but this fix didn't work for me, this is my situation:

- Started happening since I've migrated to expo v37
- nor icons nor custom ttf fonts are showing after build
- icons and custom fonts work properly when developing on the ios simulator.
- icons and custom fonts and icons are working after build when building from a brand new project
- I have already deleted node_modules and lockfile, and flushed npm cache
- when I run this `find node_modules -name expo-font` there's only one result
- i stripped everything from my app, leaving only the bare minumum modules in package.json and left minimum code in App.js
- no errors in the console

i'm sharing my config:

**package.json**
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "dependencies": {
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-screens": "~2.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@types/lodash": "^4.14.149",
    "@types/markdown-it": "^0.0.9",
    "@types/node": "^13.5.2",
    "@types/react": "^16.9.11",
    "@types/react-native": "^0.60.22",
    "@types/react-native-vector-icons": "^6.4.5",
    "@types/react-redux": "^7.1.7",
    "@types/styled-components": "^4.4.2",
    "@typescript-eslint/eslint-plugin": "^2.18.0",
    "@typescript-eslint/parser": "^2.18.0",
    "babel-preset-expo": "^8.1.0",
    "eslint": "^6.8.0",
    "eslint-config-universe": "^2.2.0",
    "jest-expo": "^37.0.0",
    "prettier": "^1.19.1",
    "react-test-renderer": "^16.12.0",
    "redux-devtools-extension": "^2.13.8",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "private": true
}
```

**app.json**
```
{
  "expo": {
    "name": ""testapp,
    "slug": "",
    "privacy": "testapp",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/AppIcon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#fff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.breincorp.play",
      "buildNumber": "1"
    }
  }
}
```
As you can see i don't have an `index.js` file, the entrypoint is defined in package.json on this line `"main": "node_modules/expo/AppEntry.js"` and it's the same way it's done in the brand new expo project i created to check the default settings.

I tried to do as suggested here to wrap the export of App.js in `registerRootComponent` but still it's not working :(

**Comment by brentvatne** [comment]
@rainst - can you share your project with me privately?

**Comment by rainst** [comment]
This morning with a fresh mind I was able to solve the issue, it looks like I had to delete a folder named `ios` in the root of the project that apparently was holding some information about the build..
I completely missed this folder until today.

@brentvatne thanks for your kind offer :)

**Comment by dtpietrzak** [comment]
In case anyone else gets here and this might help. I had the same issue, but my index.js was correctly set up. After deleting my ios and android folders, like rainst suggested, (Project->ios / Project->android) my icons worked perfectly. I believe I used create-react-native-app appname to create my initial setup, but that was last week, so I don't remember lol.

**Comment by AndreiMsk** [comment]
Same issue with icons - Works after deleting iOS and Android

**Comment by staghouse** [comment]
This is happening on with `bare` builds for me. I have only one `expo-font` and im on the `managed` workflow so theres no `ios` or `android` directories.

Heres my diagnostics:

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.15 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed
```

**Comment by woodcockjosh** [comment]
I still have this issue with a brand new expo project.

**Comment by wbrickner** [comment]
This issue still persists.  Does anyone have an actual solution for this? Some people sprinkled around the internet claim you need to forcibly / manually load the proper icon fonts, even though they're built into expo.  Doing this does not work, I still get boxes instead of icons on both Android and iOS.

When launching the Expo experience in the Expo Go app I get the message

```
fontFamily "material" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.
```

**Comment by DmitryB11** [comment]
expo install sometimes work in this case

**Comment by brentvatne** [comment]
fonts/icons not working for you?

- if you are using expo sdk <= 40, did you change your metro.config.js? if you change the sourceExts you need to make sure you extend @expo/metro-config so .expo.js files are included. this is not an issue on sdk 41+
- did you create a different entry point to your app? (by setting “main” in package.json to point to a different file). if so, you need to use registerRootComponent: https://docs.expo.io/versions/latest/sdk/register-root-component/
- did this seem to happen “out of nowhere”? try to trace back to where this happened: https://expo.fyi/manual-debugging
