### ISSUE TITLE
Broken HostnameVeriﬁer for SSL

### ISSUE THREAD

**Issue by Mahesha-Bhat** [expo/expo#7794]
App is allowing All Hostnames, it does not verify if the certiﬁcate is issued for the URL that connecting to. For example, when a client connects to [example.com](url), it will accept a server certiﬁcate issued for [some-other-domain.com](url).
is there any way i can verify the hostname in expo?
please help me to solve this problem.

**Comment by cruzach** [comment]
Hey @Mahesha-Bhat , as I said in https://github.com/expo/expo/issues/7783, we need more specific information to help you

 If you are referring to AppAuth's [unsafeConnectionBuilder](https://github.com/expo/expo/blob/master/packages/expo-app-auth/android/src/main/java/expo/modules/appauth/UnsafeConnectionBuilder.java), then we [recently made a fix to remove restricted unsafe connection features](https://github.com/expo/expo/commit/21032cb91ab57ab314bd3de20ee7e6bbec93b3cf)
