### ISSUE TITLE
Push Notifications - Error - DeviceNotRegistered - Update Response Body

### ISSUE THREAD

**Issue by Bryksin** [expo/expo#7795]
Hi

According to the [official documentation](https://docs.expo.io/versions/latest/guides/push-notifications/) if we would send a notification to the wrong token which is not registered we will get `DeviceNotRegistered` error in response.

Logically at our end, if we got such response, we need to delete such token from our DB and never use any more. However, the response body contains just an error message:
```
{
  "data": [
    {
      "status": "error",
      "message": "\"ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]\" is not a registered push notification recipient",
      "details": {
        "error": "DeviceNotRegistered"
      }
    }
  ]
}
```

Token itself is present there as part of the full error string, however, each of us needs to implement own functionality to parse that message string and extract actual faulty token.

Could you please upgrade the response body to include the actual faulty token as own K, V field? something like that: 

```
{
  "data": [
    {
      "status": "error",
      "token": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]"
      "message": "Not a registered push notification recipient",
      "details": {
        "error": "DeviceNotRegistered"
      }
    }
  ]
}
```

I would imagine your service is interested in reducing the number of faulty requests, so
If you would simplify work for us at our end I'm sure it will reduce the % of invalid requests for you.

**Comment by cruzach** [comment]
the [documentation](https://docs.expo.io/push-notifications/sending-notifications/#push-tickets) states:

> The requests above will respond with a JSON object with two optional fields, data and errors. data will contain an array of push tickets **in the same order in which the messages were sent** (or one push ticket object, if you send a single message to a single recipient).

So you can easily map ticket to appropriate token, but I agree that this would probably make things easier

**Comment by danieljvdm** [comment]
This seems a bit crazy, especially since we are told to delay our logic to check receipts/tickets until up to 30 minutes after the initial request. If you're delaying this (presumably in a queue) why would you retain your initial messages?

**Comment by quinlanj** [comment]
Landed a fix that will add the `expoPushToken` to the details in the event of a `DeviceNotRegistered` error, will be deployed shortly.

For example:
```
{
  "data": [
    {
      "status": "error",
      "message": "Not a registered push notification recipient",
      "details": {
        "error": "DeviceNotRegistered",
         "expoPushToken": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]"
      }
    }
  ]
}
```

Keeping this issue open to make sure we get confirmation everything is working as intended.

**Comment by redcranesolutions** [comment]
"expoPushToken" is missing in both old way and not present in new way.

Also documentation still states old way but that does not work either.

https://docs.expo.dev/push-notifications/sending-notifications/

**Comment by redcranesolutions** [comment]
> Landed a fix that will add the `expoPushToken` to the details in the event of a `DeviceNotRegistered` error, will be deployed shortly.
> 
> For example:
> 
> ```
> {
>   "data": [
>     {
>       "status": "error",
>       "message": "Not a registered push notification recipient",
>       "details": {
>         "error": "DeviceNotRegistered",
>          "expoPushToken": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]"
>       }
>     }
>   ]
> }
> ```
> 
> Keeping this issue open to make sure we get confirmation everything is working as intended.

Not working as intended.

**Comment by isaachinman** [comment]
@quinlanj @douglowder I am not seeing any `expoPushToken` in the following res payload:

```
{
  "status": "error",
  "message": "The recipient device is not registered with FCM.",
  "messageEnum": 7,
  "messageParamValues": [],
  "details": {
    "error": "DeviceNotRegistered",
    "errorCodeEnum": 3,
    "sentAt": 1677015172
  },
  "__debug": {}
}
```

Using `expo-server-sdk@3.7.0`.

Should a separate issue be opened for this?

**Comment by isaachinman** [comment]
@quinlanj Any timeline on this? I would be happy to help if needed.

**Comment by isaachinman** [comment]
@douglowder @quinlanj Pinging again, as there has been no response and this issue remains closed. Should I open another issue? Can I assist in any way?

**Comment by ide** [comment]
Hi, we'll make an internal task on this. Given other priorities there's no ETA. This is server-dependent behavior so unfortunately a PR won't help here.

**Comment by isaachinman** [comment]
Thanks for a detailed response @ide. Your last sentence there seems to indicate the Expo team might be considering deprecating the PN service – is that indeed the case?

Now that we have an actual response, we can proceed with a workaround by storing the Expo PN token as metadata in the background job itself, but I think it's worth stating plainly that it's poor design and frankly incoherent that these error responses don't contain a reference to the Expo token itself, especially considering the fact that the expectation is we cease use of that token.

**Comment by ide** [comment]
Other services are our primary areas of focus and the push notification service continues to run as-is. It might need to become something existing apps that depend on it can continue to use and new projects that don't depend on it get a small quota for early development, so everyone who relies on the service is not impacted. The API could be more convenient and as you explained the way to tie together all the info needed to stop sending messages is to keep state on the sender's side. The request to send notifications contains the push tokens -> the response contains push tickets for each respective notification -> the push receipts specified by those tickets say if a device is unregistered.
