### ISSUE TITLE
SDK37 Notifications.getExpoPushTokenAsync() never response on Android

### ISSUE THREAD

**Issue by whoami19** [expo/expo#7797]
### Environment

  Expo CLI 3.17.21 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.1.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.6
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.17.21

### Steps to Reproduce

1. Connect your android device (Expo.io application) via tunnel
2. Run Notifications.getExpoPushTokenAsync()

### Expected Behavior

1. Gets a token

### Actual Behavior

1. getExpoPushTokenAsync hangs on Android device

### Reproducible Demo

```
import React from 'react';
import { Text, Vibration, View } from 'react-native';
import { Notifications } from 'expo';
import * as Permissions from 'expo-permissions';
import Constants from 'expo-constants';

export default class AppContainer extends React.Component {
    state = {
        expoPushToken: '',
        notification: {},
    };
    
    registerForPushNotificationsAsync = async () => {
        if ( Constants.isDevice ) {
            const { status: existingStatus } = await Permissions.getAsync(
                Permissions.NOTIFICATIONS
            );
            let finalStatus = existingStatus;
            if ( existingStatus !== 'granted' ) {
                const { status } = await Permissions.askAsync(
                    Permissions.NOTIFICATIONS
                );
                finalStatus = status;
            }
            if ( finalStatus !== 'granted' ) {
                alert( 'Failed to get push token for push notification!' );
                return;
            }
            let token = await Notifications.getExpoPushTokenAsync();
            console.log( token );
            this.setState( { expoPushToken: token } );
        } else {
            alert( 'Must use physical device for Push Notifications' );
        }
    };
    
    componentDidMount() {
        this.registerForPushNotificationsAsync();
        this._notificationSubscription = Notifications.addListener(
            this._handleNotification
        );
    }
    
    _handleNotification = notification => {
        Vibration.vibrate();
        this.setState( { notification: notification } );
    };
    
    render() {
        return (
            <View
                style={ {
                    flex: 1,
                    alignItems: 'center',
                    justifyContent: 'space-around',
                } }>
                <View style={ { alignItems: 'center', justifyContent: 'center' } }>
                    <Text>Token: { this.state.expoPushToken }</Text>
                    <Text>Origin: { this.state.notification.origin }</Text>
                    <Text>Data: { JSON.stringify( this.state.notification.data ) }</Text>
                </View>
            </View>
        );
    }
}
```

### Comment

I followed all the steps that were described in the documentation.

1. For the android, I set up Firebase
2. Downloaded google-services.json.
3. Specified in app.json the path to google-services.json.
4. Specified the server key through the command 
expo push:android:upload --api-key

Tried these clues:
https://github.com/expo/expo/issues/7727#issuecomment-611544439.
https://github.com/expo/expo/issues/7606#issuecomment-608616162

<img width="404" alt="image" src="https://user-images.githubusercontent.com/15385706/79003602-99c0a100-7b5b-11ea-92af-d7cdd27cdc23.png">

This isn't working. Please help me solve this problem.

**Comment by byCedric** [comment]
Hi @whoami19! Thanks for reporting the issue. We've had some issues with the push notifications in Expo Client 2.15.0 on Android. [We patched some issues with push token requests that were hanging (not rejecting or resolving) in the latest Android version (`2.15.1`)](https://github.com/expo/expo/issues/7771#issuecomment-611654778). You can install it with the CLI `expo install:client:android` and select `latest`. Could you try this and see if the token is either resolved or rejected?

Hope it helps 😄

**Comment by Vikka0157** [comment]
@byCedric 
It's working on expo client but when I build the app 
It's not return/alert the token 
How much times it will take to resolve please fix this bug it's destroy my client 
It's a humble request please resolve this 
Thanks

**Comment by whoami19** [comment]
@byCedric Thank you! It finally works!

Command ```expo client:install:android```

**Comment by dichai1983** [comment]
For the standalone app, it still doesn’t work. I tried expo 37.0.7.

**Comment by whoami19** [comment]
@dichai1983 Did you upload server credentials for standalone app?

**Comment by dichai1983** [comment]
@whoami19 

Hi. My app is up and running on App Store and Google Play. It was built with the expo managed-flow. There are no Google Cloud API restrictions. Push notification was working with expo 36. I didn't change anything but upgrade the expo to 37 with the expo upgrade cli. Push notification works with the latest Expo client (2.15.1). For the standalone Android app, everything works except for the push notification.

Thanks.

**Comment by dichai1983** [comment]
This works: https://github.com/expo/expo/issues/7727#issuecomment-611544439

**Comment by mobeendev** [comment]
> For the standalone Android app, push notification still doesn’t work. I tried expo 37.0.7.

Same for me.
Working in Expo Client.
When I build the app, token doesn't show up.
