### ISSUE TITLE
Expo IDE unable to create new projects 

### ISSUE THREAD

**Issue by andrewrd** [expo/expo#78]
I've been attempting to create a new project using the updated IDE however it does not ever finish 'extracting files'. I've left this open for an entire night with no avail. After force exiting, the project appears however the name is not present and these warnings are present in the console.

Warning
Warning: Problem validating asset fields: Invalid URI "./assets/icons/app.png".
Warning
Warning: '@expo/vector-icons' dependency is not installed.
Warning: 'expo' dependency is not installed.

If there is an issue running your project, please run `npm install` in /Users/myusername/Github/exampleproject and restart.

After attempting to npm install, these errors appear in the terminal:

npm WARN enoent ENOENT: no such file or directory, open '/Users/myusername/Github/exampleproject/node_modules/exec-sh/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/myusername/Github/exampleproject/node_modules/exit-hook/package.json'

There are 100's of these missing.

**Comment by jesseruder** [comment]
Hi @andrewrd some computers have trouble downloading and extracting the project files. We're working on a fix but for now you can use these instructions to download manually: https://gist.github.com/jesseruder/a627c0dc0427f074d1aecba997c349ef

**Comment by ErkanSensei** [comment]
Im also having this issue, the IDE freezes on MacOS, however when I use ```expo init```, it has an issue with Lottie, and then exits

**Comment by Alonski** [comment]
I also had this issue and came looking here.
Opening the console I noticed that NPM didn't have permissions to write files.
I reopened Expo as Administrator and was able to create a project in less than a minute where before it was taking much long if at all.

I am running Windows 10 latest update

**Comment by nir2002** [comment]
same issue here (with two different computers)

**Comment by lal12** [comment]
I am not even sure, that is about expo. If I try to extract the tabs archive with 7zip it also stucks.

**Comment by dikaiosune** [comment]
@lal12 do you mean that you had this problem when manually downloading the file?

**Comment by lal12** [comment]
Yes I downloaded the files mentioned in the instructions (https://gist.github.com/jesseruder/a627c0dc0427f074d1aecba997c349ef) for the tabs project template and tried to extract it with 7zip, but 7zip just hangs on 100% just like XDE.

**Comment by dikaiosune** [comment]
@lal12 that sounds to me like your internet connection is failing to download the file completely, the files work fine for me at the moment. Are you behind a corporate firewall that might rewrite responses, or on a low bandwidth connection that may timeout?

**Comment by lal12** [comment]
@dikaiosune No I have no such thing, I tried to extract the same file with linux which worked perfectly. I think I got the problem: The archive contains symlinks, but apparently you need admin rights on windows to create symlinks, so I extracted the archive with 7zip again as admin, which worked without errors.
So I tried to run XDE as admin, now it works perfectly.

**Comment by dikaiosune** [comment]
@lal12 oh yeah, it looks like a version with symlinks was released. This will be resolved when the new starter projects are released early next week, sorry for that!
