### ISSUE TITLE
Pedometer Fails after Detach

### ISSUE THREAD

**Issue by MikeShi42** [expo/expo#780]
On my app, running with ExpoKit (ejected from Expo from CRNA), the `Pedometer.isAvailableAsync()` fails to have its promise ever resolve or reject. 

I've reproduced this problem by cloning https://github.com/expo/native-component-list, detaching, and then trying to run it on an android device (standalone) and I get the same exact issue. However, the example works when it is not ejected (running in the Expo app).

**Comment by terribleben** [comment]
I suspect you may need to add `NSMotionUsageDescription` to your detached app's Info.plist. We should do this for you, but we currently don't, and are tracking that issue [here](https://github.com/expo/expo/issues/592).

**Comment by MikeShi42** [comment]
This was on android, I didn't know that you needed to register with an API key with Google Fit just to access step counter information. For future reference if anyone else comes across this:

https://developers.google.com/fit/android/get-api-key

Which I learned from this project: https://github.com/StasDoskalenko/react-native-google-fit
