### ISSUE TITLE
[expo-app-auth][android][Azure/Microsoft] When Authorizing to Microsoft I receive endpoint only accepts Post, Options request

### ISSUE THREAD

**Issue by jdaly13** [expo/expo#7801]
### Environment

  Expo CLI 3.17.14 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
      react-navigation: ^4.0.6 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.17.14
    "expo-app-auth": "9.0.0",

When running on Andriod emulator or scanning QR Code on android Expo App 
![SmartSelect_20200410-163150_Chrome](https://user-images.githubusercontent.com/1916496/79024569-ff576200-7b48-11ea-9f6d-81de2887fe31.jpg)

### Steps to Reproduce
When using authSync method and supplying it a config - it opens up the web portal to authorize user but Microsoft is giving me error

```
const config = {
  clientId: AuthConfig.appId,
  redirectUrl: Platform.OS === 'ios' ? 'com.wwt.silhouette://com.wwt.silhouette/ios/callback' : 'com.wwt.silhouette://com.wwt.silhouette/android/callback',
  scopes: AuthConfig.appScopes,
  additionalParameters: { prompt: 'select_account' },
  serviceConfiguration: {
    authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
  },
```
};

### Expected Behavior
On IOS simulator the behavior is working just fine and also if I don't use expo-app-auth and use react-native-auth-app and run in android it works normally as well meaning I can authorize and it gives me an access token 

### Actual Behavior
I get attached error message so I can't authorize or sign into application 

### Reproducible Demo
https://snack.expo.io/@jdaly/smiling-fudge

Strange part is if I do it through this demo - it's working like it's supposed to - not sure what the difference would be also doing this on my emulator

**Comment by cruzach** [comment]
The demo is running SDK 37, so I would try upgrading your project from SDK 34, since if it's not working but the Snack is, then it's likely been fixed since then

**Comment by murbanowicz** [comment]
@cruzach I hit this issue right now with Expo SDK 39. What is the solution?
