### ISSUE TITLE
Unable to get Reminders lists without CALENDAR permission

### ISSUE THREAD

**Issue by hkaju** [expo/expo#7808]
### Environment

```
  Expo CLI 3.17.18 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.18
```

### Steps to Reproduce

Call `Calendar.getCalendarsAsync(Calendar.EntityTypes.REMINDER)` with `Permissions.REMINDERS` having been granted but without `Permissions.CALENDAR` on iOS.

### Expected Behavior

Should be able to retrieve Reminders lists with only `Permissions.REMINDERS`.

### Actual Behavior

`[Unhandled promise rejection: Error: CALENDAR permission is required to do this operation.]`

### Reproducible Demo

https://snack.expo.io/EZmpfVyTBV

**Comment by cruzach** [comment]
It seems like from the native iOS documentation that you need both CALENDAR and REMINDERS permission - https://developer.apple.com/documentation/eventkit/creating_events_and_reminders?language=objc

**Comment by hkaju** [comment]
From what I gather, all of the EventKit documentation seems to imply that you can access entity types separately + there are apps out there that are able to operate with Reminders without having calendar permissions (e.g. https://twitter.com/smartgroceryapp).

I think the issue might be that the `getCalendarsAsync` method takes in an entity type but always checks for calendar permissions regardless of the entity type requested (see https://github.com/expo/expo/blob/40eee441bf91d0eff9582800b3eb1a5c0f45c10e/packages/expo-calendar/ios/EXCalendar/EXCalendar.m#L57).

**Comment by cruzach** [comment]
Ah okay, thanks for the extra info
