### ISSUE TITLE
XDE blank window in win 10

### ISSUE THREAD

**Issue by Jancat** [expo/expo#781]
I was first installing the latest xde in win 10, and it show a blank window after startup.

![image](https://user-images.githubusercontent.com/11827786/31570799-b1d9815c-b04d-11e7-98b1-588911f258bf.png)

I clicked View > Reload and it showed Sign In Page in seconds and then disappeared.
![image](https://user-images.githubusercontent.com/11827786/31570805-dcb6ea40-b04d-11e7-8471-2327255da32c.png)

![image](https://user-images.githubusercontent.com/11827786/31570807-e63cf640-b04d-11e7-9579-1edfb4a419da.png)

I had reinstalled but it still the same.

**Comment by serranoarevalo** [comment]
Happening to me too, any fix for this?

**Comment by david340804** [comment]
I also have this issue, going to try installing an older version that didn't have this issue

**Comment by pythonik** [comment]
^ same issue

**Comment by Joe1220** [comment]
same issue...
