### ISSUE TITLE
KeyboardAvoidingView doesn't work in APK release

### ISSUE THREAD

**Issue by Blackoutseeker** [expo/expo#7814]
### Environment

Expo CLI 3.13.1 environment info:
System:
OS: Windows 8.1
Binaries:
Yarn: 1.21.1 - C:\Users\PC\AppData\Roaming\npm\yarn.CMD
npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
react-native-cli: 2.0.1
react-native: 0.61.4
NodeJs: 12.14.0

### Steps to Reproduce

Just encapsule the components inside a KeyboardAvoidingView.

import React, { Component } from 'react'
import {
    Alert,
    View,
    Text,
    TouchableOpacity,
    TouchableNativeFeedback,
    ImageBackground,
    TextInput,
    KeyboardAvoidingView,
    Keyboard,
    TouchableWithoutFeedback,
    ActivityIndicator,
    AsyncStorage,
    StatusBar
} from 'react-native'
import styles from '../styles/AuthStyle'
import Icon from 'react-native-vector-icons/FontAwesome'
import firebase from '../../firebase'
import * as Animatable from 'react-native-animatable'
Icon.loadFont()

export default class Login extends Component {

    constructor(props) {
        super(props)
        this.state = {
            eyeValue: false,
            pressValue: true,
            load: false,
            email: '',
            password: '',
            nome: '',
            endereco: '',
            curso: null,
            ano: null,
            tela: null
        }
    }
    render() {
            return(
                <>
                <StatusBar translucent={true} />
                <ImageBackground
                    source={ require('../fundoverde.png') }
                    style={{ flex: 1 }}
                    imageStyle={{ resizeMode: 'repeat' }} >
                    <KeyboardAvoidingView style={styles.content} contentContainerStyle={{justifyContent: 'center', alignItems: 'center'}} centerContent={true} >
                        <TouchableWithoutFeedback onPress={() => {Keyboard.dismiss()}} style={styles.feedback}>
                            <View style={styles.feedback}>
                                <View style={styles.imageHolder} >
                                    <Animatable.Image source={require('../logosombreada.png')} style={styles.logo}
                                    animation={'bounceInLeft'} useNativeDriver={true} />
                                </View>
                                <View style={styles.formContainer} >
                                    <Icon name="envelope-o" size={30} color={'#fa5c19'} style={styles.email} />
                                    <TextInput
                                        keyboardType={'email-address'} 
                                        style={styles.input}
                                        placeholder={'Digite seu email'}
                                        placeholderTextColor={'#fa5c19'}
                                        autoCapitalize={'none'}
                                        onChangeText={email => this.setState({email})}
                                        value={this.state.email} />
                                    <Icon name="lock" size={30} color={'#fa5c19'} style={styles.pass} />
                                    <Icon name={this.state.pressValue ? 'eye' : 'eye-slash'}
                                    size={30} color={'#fa5c19'} style={styles.eye}
                                    onPress={() => {this.switchPass()}} />
                                    <TextInput
                                        keyboardType={'default'}
                                        secureTextEntry={this.state.eyeValue ? false : true}
                                        autoCapitalize={'none'}
                                        style={styles.inputPass} 
                                        placeholder={'Digite sua senha'}
                                        placeholderTextColor={'#fa5c19'}
                                        onChangeText={password => this.setState({password})}
                                        value={this.state.password} />
                                    <TouchableOpacity style={styles.button}
                                    activeOpacity={0.8}
                                    onPress={() => this.state.email == 'bibliotecaeeep@gmail.com' && this.state.password == 'bibliotecaeeep' ? this.props.navigation.navigate('MainBack') : this.login()} >
                                        {this.state.load == false ?
                                            <Text style={styles.buttonText} >LOGAR</Text>
                                        : <ActivityIndicator size={35} color={'#fff'} />}
                                    </TouchableOpacity>
                                </View>
                                <TouchableNativeFeedback onPress={() => this.props.navigation.navigate('Login')} >
                                    <Animatable.Text style={styles.naoPossui} animation={'pulse'} iterationCount={Infinity} useNativeDriver={true}
                                    >Não possui uma conta? <Text style={styles.naoPossui, {fontWeight: 'bold', textDecorationLine: 'underline'}}
                                    >Faça</Text> agora!</Animatable.Text>
                                </TouchableNativeFeedback>
                            </View>
                        </TouchableWithoutFeedback>
                    </KeyboardAvoidingView>
                </ImageBackground>
                </>
            )
    }
}

StyleSheet:

import { StyleSheet } from 'react-native'

export default styles = StyleSheet.create({
    content: {
        flex: 1,
    },
    imageHolder: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    feedback: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    logo: {
        height: 250,
        resizeMode: 'contain',
        marginTop: 10,
        marginBottom: 5,
    },
    formContainer: {
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    input: {
        width: 320,
        height: 50,
        backgroundColor: '#fff',
        marginVertical: 10,
        borderRadius: 30,
        color: '#fa5c19',
        paddingLeft: 60,
        paddingRight: 20,
        fontSize: 25,
    },
    inputPass: {
        width: 320,
        height: 50,
        backgroundColor: '#fff',
        marginVertical: 10,
        borderRadius: 30,
        color: '#fa5c19',
        paddingLeft: 60,
        paddingRight: 55,
        fontSize: 25,
    },
    button: {
        width: 320,
        height: 50,
        backgroundColor: '#fa5c19',
        marginVertical: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
    },
    buttonLoad: {
        width: 320,
        height: 50,
        backgroundColor: '#fff',
        marginVertical: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
        borderWidth: 3,
        borderColor: '#fa5c19',
    },
    buttonText: {
        fontSize: 20,
        color: '#fff',
    },
    email: {
        position: 'absolute',
        zIndex: 1,
        top: 17,
        left: 20,

    },
    pass: {
        position: 'absolute',
        zIndex: 1,
        left: 25,
    },
    eye: {
        position: 'absolute',
        zIndex: 1,
        right: 15,
    },
    naoPossui: {
        color: '#fff',
        fontSize: 15,
        marginVertical: 10,
    },
})

### Expected Behavior

The keyboard must be up and scrolling.

### Actual Behavior

In Expo app, the KeyboardAvoidingView work's fine, but, in APK the keyboard goes up but the view does not, making it stand in front of it.

### Login Screen (work's fine in Expo and APK):
<img src="https://firebasestorage.googleapis.com/v0/b/project-fa561.appspot.com/o/issue3.png?alt=media&token=57afed77-7b6a-4f15-b904-c0fe3846b9f0"/>

### Login Screen when an input get focus (in Expo):
PS: Before the SDK 37 update, the background image was in place, did not move, but after the update it is "cut in half" and floats over the keyboard. And this background image bug does not occur in the APK.
<img src="https://firebasestorage.googleapis.com/v0/b/project-fa561.appspot.com/o/issue1.png?alt=media&token=652c7a78-aab1-45fb-9e3d-acc995cc81f4" />

### Login Screen when an input get focus (in APK):
<img src="https://firebasestorage.googleapis.com/v0/b/project-fa561.appspot.com/o/issu2.png?alt=media&token=22d6fd63-d33d-4868-bf75-206b57fd295f" />

**Comment by eliasallex** [comment]
try using the **KeyboardAvoidView**, I used it to deal with the avoidance of views.
eg: 
```js
import {
  KeyboardAvoidView, Platform
} from 'react-native';

const KeyboardAvoid = () => (
     <KeyboardAvoidView
         behavior={Platform.Os == "ios" ? "padding" : "height"} // IOS behavior
         style={styles.yourStyles}
     >
         // your view
     </KeyboardAvoidView>
);
```

**Comment by eliasallex** [comment]
> try using the **KeyboardAvoidView**, I used it to deal with the avoidance of views.
> eg:
> 
> ```js
> import {
>   KeyboardAvoidView, Platform
> } from 'react-native';
> 
> const KeyboardAvoid = () => (
>      <KeyboardAvoidView
>          behavior={Platform.Os == "ios" ? "padding" : "height"} // IOS behavior
>          style={styles.yourStyles}
>      >
>          // your view
>      </KeyboardAvoidView>
> );
> ```

See more [here](https://reactnative.dev/docs/keyboardavoidingview)

**Comment by Blackoutseeker** [comment]
@eliasallex Thanks man, but I already used it, and unfortunately it has the same effect. Both work perfectly when using the Expo app, but when I generate the APK, it is as if the KeyboardAvoidingView were replaced by a common View.

**Comment by brentvatne** [comment]
hello! in general when providing a code example to report a bug, it's best to make them minimal, there is too much going on in that code to isolate the issue (https://stackoverflow.com/help/mcve for more info). please also reproduce the issue without using an external library like `react-native-keyboard-aware-scroll-view'` - we do not maintain this and can't provide support for it.

we are tracking this and related topics in https://github.com/expo/expo/issues/7815

**Comment by Blackoutseeker** [comment]
@brentvatne This problem also affects the common KeyboardAvoidingView.

**Comment by sa1dai** [comment]
@Blackoutseeker 
I think the problem is in react-navigation (your header). 
Try this, create KeyboardAvoiding.js:
`import React from 'react';
import { StyleSheet, KeyboardAvoidingView } from 'react-native';
import Constants from 'expo-constants';

const headerHeight = 50;

const KeyboardAvoiding = props => {
  return (
    <KeyboardAvoidingView
      behavior="height"
      //  https://stackoverflow.com/questions/44990478/react-native-keyboardavoidingview-with-sticky-footer
      keyboardVerticalOffset={headerHeight + Constants.statusBarHeight}
      style={styles.flex}
    >
      {props.children}
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
});

export default KeyboardAvoiding;`

Then just replace `<KeyboardAvoingVIew ...>` with `<KeyboardAvoiding>`

**Comment by brentvatne** [comment]
@Blackoutseeker - i understand that you believe `react-native-keyboard-aware-scroll-view` is the same but i cannot reproduce this with `KeyboardAvoidingView` - it works as expected for me in client and standalone apk.

source: https://github.com/brentvatne/issue7814
apk: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40notbrent/keyboardexample-347d9613256a4a269510a39ea9828fdb-signed.apk

the above is an example of what we expect people to provide when creating issues. notice that the repository contains no unrelated code whatsoever, and i also provide an apk because the issue you're describing says you are encountering the problem in that case.

if you would like to create a new issue and put in the same amount of effort that i did above to testing your issue then we would be happy to look into it! thanks
