### ISSUE TITLE
Linking.openURL crashes with `mailto`

### ISSUE THREAD

**Issue by bitttttten** [expo/expo#7817]
### Environment

```sh
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @emotion/react: ^11.0.0-next.10 => 11.0.0-next.10 
      @testing-library/react-native: ^5.0.3 => 5.0.3 
      @types/react: ^16.9.11 => 16.9.31 
      @types/react-native: ^0.60.22 => 0.60.31 
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
```

### Steps to Reproduce

On iOS, and using [the native schema from Apple docs](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MailLinks/MailLinks.html), the code will fail on:

```js
Linking.openURL("mailto:frank@wwdcdemo.example.com")
```

With:

```sh

[Unhandled promise rejection: Error: Unable to open URL: mailto:frank@wwdcdemo.example.com]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:99:50 in fn
- node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js:336:45 in createReactClass$argument_0.touchableHandlePress
* [native code]:null in touchableHandlePress
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:880:34 in TouchableMixin._performSideEffectsForTransition
* [native code]:null in _performSideEffectsForTransition
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:779:44 in TouchableMixin._receiveSignal
* [native code]:null in _receiveSignal
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:490:24 in TouchableMixin.touchableHandleResponderRelease
* [native code]:null in touchableHandleResponderRelease
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:555:30 in invokeGuardedCallbackAndCatchFirstError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:722:42 in executeDispatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:744:20 in executeDispatchesInOrder
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:907:29 in executeDispatchesAndRelease
* [native code]:null in forEach
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:887:16 in forEachAccumulated
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:932:21 in runEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:1096:19 in runExtractedPluginEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2796:6 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18791:14 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2709:30 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2794:17 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2870:28 in receiveTouches
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
```

### Expected behavior

I would expect the mail app to open

**Comment by byCedric** [comment]
Hi @bitttttten, thanks for the issue report! May I ask if you are testing this for a simulator or real device? If you are using a simulator this issue is related to the missing mail app. There is a small but important part in the linked docs you sent:

> **iOS Note**: If the Mail app is not installed, clicking a mailto URL displays an appropriate warning message to the user.

The good news here is that your mailto link works fine on a real Android device 😄

**Comment by brentvatne** [comment]
indeed this works as expected on ios device and android device - https://snack.expo.io/@notbrent/89e884

**Comment by bitttttten** [comment]
Ah yeah, you're right. It works great on a real device, and I was testing on the simulator. Well, thanks a ton! ☺️

**Comment by evasyuk** [comment]
BTW it may crash with same error on real device as well

I found that it is due to special characters not being encoded

it was working recently with extra encoding, but started to fail with message like

`[Error: Unable to open URL: file:///private/var/containers/Bundle/Application/22E8ACAE-3E51-4A1C-8B51-983DD57A1CC8/bruh-staging.app/mailto:support-team@bruh.io%3Fsubject=Lost%20access%20to%20phone%20number]`

after changing 

`await Linking.openURL('mailto:support-team@bruh.io?subject=Lost access to phone number');`

to

`await Linking.openURL(`
`    encodeURI('mailto:support-team@bruh.io?subject=Lost access to phone number'),`
`);`

it started working fine again

**Comment by wolever** [comment]
Hey folks - we've been seeing this issue on physical devices with a simple `mailto:` link:

```
> await Linking.openURL('mailto:support@rxfood.co')
…
Error: Unable to open URL: mailto:support@rxfood.co
```

Expo: 49.0.16
iOS: 17.2.1

Has anyone else seen this? Any idea what could be causing it?

**Comment by phil-hudson** [comment]
+1 seeing it fail on Android Play Store review.

same repro as @wolever  above.

**Comment by jhe04** [comment]
> Hey folks - we've been seeing this issue on physical devices with a simple `mailto:` link:
> 
> ```
> > await Linking.openURL('mailto:support@rxfood.co')
> …
> Error: Unable to open URL: mailto:support@rxfood.co
> ```
> 
> Expo: 49.0.16 iOS: 17.2.1
> 
> Has anyone else seen this? Any idea what could be causing it?

@wolever Had the same issue. I was able to reproduce by spam clicking the contact support button on our app. Seems like `Linking.openURL` creates a Promise, and the spam clicking led to unresolved promises. Even though the user is still able to open up the mail app, we still got the error logs. We resolved it by debouncing the function and cancelling spam calls to the function.
