### ISSUE TITLE
Android Navigation Bar became shown and fixed in case of navigating to other applications

### ISSUE THREAD

**Issue by frodoe7** [expo/expo#7819]
### Environment

  Expo CLI 3.13.8 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.5 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.8

I'm testing using Expo Client App in my Android device 

## Steps to Reproduce
Please create an empty Expo project with sticky-immersive value in androidNavigationBar (in app.json file) , or any other acceptable value

```javascript
"androidNavigationBar": {
      "visible": "sticky-immersive",
      "barStyle": "light-content",
      "backgroundColor": "#00000000"
},
```

### Expected Behavior
by using the below values in app.json file , the navigationBar will be hidden as documented
**but try to navigate to any other apps or click on the navigating button on the navigation bar** , and return back to the app - the expected is to still be immersive and hidden

```javascript
"androidNavigationBar": {
      "visible": "sticky-immersive",
      "barStyle": "light-content",
      "backgroundColor": "#00000000"
},
```

### Actual Behavior
after navigating or click on the navigating button on the navigation bar , the navigation bar will be shown and be fixed (will not be hidden again)

### Reproducible Demo

[Snack Link](https://snack.expo.io/mbfYF!tp7) - however should be tested from real Android device (has Navigation Bar)

**Comment by byCedric** [comment]
Hi @frodoe7, thanks for your issue report! I think this is the same issue as #7663, right? If so, a fix is on it's way! 😄 If you think this is a different issue, lmk!
